### ISSUE TITLE
Changes in settings are not persisted

### ISSUE THREAD

**Issue by alexruf** [AdguardTeam/AdGuardHome#1000]
I installed the latest version of AdGuardHome following the [installation instructions for Raspberry Pi](https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi) in the Wiki.

So far it to worked well. After the installation I tried to configure my upstream DNS servers via the web interface in the settings tab.
But the settings are not persisted after saving them. As soon as you reload the settings tab, all the changes are gone and reset to their initial default values.

I am not totally sure, but I think this might be an issue with file system permissions of the corresponding config files.
Since (like described in the Wiki) AdGuard is downloaded in placed with a non-root unix user homedir, but the service started with root-privileges, the config files might not be accessible anymore.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by NetE1** [comment]
(Experimental things to do)

- Try incognito mode, maybe your browser use cache
- Check manually whether .yml file get updated or not when you make change via web interface If not provide write permission manually.

**Recommend: @ameshkov https://github.com/AdguardTeam/AdGuardHome/issues/1000#issuecomment-531255185**

**Comment by alexruf** [comment]
Embarrassing but true, the settings were indeed updated in the YML file but the web interface didn't update properly.
I had to manually refresh the page a few times until it showed the changes. Anyway, I think this still is a potential bug in the web interface.

**Comment by IldarKamalov** [comment]
Could you provide us steps to reproduce this bug? AdGuard Home logs and some screenshots will be also helpful.
