### ISSUE TITLE
Parental Control Web Service disables Youtube comments

### ISSUE THREAD

**Issue by opav** [AdguardTeam/AdGuardHome#1002]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.98.1

Unable to see or submit Youtube comments.  Youtube show it is in "Restricted mode"

Are there any options or workaround to allow certain adult user's IP to bypass this restriction but still keep the Parental Control Web Service enabled for everyone else?

**Comment by ArchiveBase** [comment]
> Are there any options or workaround to allow certain adult user's IP to bypass this restriction but still keep the Parental Control Web Service enabled for everyone else?

Yes. 
Settings > Clients > Add Client then enter the certain device(user) IP and do not add tick mark to  Parental Control Web Service
