### ISSUE TITLE
Add a possibility to test filtering rules

### ISSUE THREAD

**Issue by alexruf** [AdguardTeam/AdGuardHome#1003]
It would be helpful to have the possibility to enter a hostname or a domain in the filter tab, and then to see if it has a hit in a filter list or the whitelist.

This would help to find out if a hostname is already filtered by an existing rule, or if an entry in the whitelist is effective at all.

**Comment by ArchiveBase** [comment]
1st thing already possible and the second will be available within v1.0 https://github.com/AdguardTeam/AdGuardHome/issues/882 version together.

**Comment by alexruf** [comment]
> 1st thing already possible and the second will be available within v1.0 #882 version together.

How is it currently possible? I would like to enter a hostname and the see if because of what exact rules AdGuard Home would have blocked this specific DNS requests or not.

**Comment by ameshkov** [comment]
> I think this should be a feature in the filter setting to test things out in advance when defining filter lists and custom filter rules.

Yep, now I got it.

Meanwhile, you can use `dig` or `nslookup` to test domains.

**Comment by alexruf** [comment]
> > I think this should be a feature in the filter setting to test things out in advance when defining filter lists and custom filter rules.
> 
> Yep, now I got it.
> 
> Meanwhile, you can use `dig` or `nslookup` to test domains.

Yes that is an option.
Pi hole has a feature like that. You have a simple textbox where you can enter a domain name, and it show you the exact rule which match. Super helpful if you try to figure out what filter rule is causing false-positive matches.

**Comment by planet0** [comment]
Same as my request in #856?

**Comment by ameshkov** [comment]
Yup, really. Closed as dup of https://github.com/AdguardTeam/AdGuardHome/issues/856

#856 is now planned on v.101
