### ISSUE TITLE
Allow to import whitelist entries from files

### ISSUE THREAD

**Issue by alexruf** [AdguardTeam/AdGuardHome#1004]
It would be very helpful to allow users to import whitelist files just like the filter files. This allows users to share and maintain common whitelist entries.
As a previous Pi hole user I am really missing a feature like this in AdGuard Home. There was a community maintained whitelist which contained some hostnames and domains which were safe to unblock or would otherwise break some sites and applications.

**Comment by ArchiveBase** [comment]
It'll be possible when implement https://github.com/AdguardTeam/AdGuardHome/issues/817 https://github.com/AdguardTeam/AdGuardHome/issues/822

**Comment by ameshkov** [comment]
Closed as dup
