### ISSUE TITLE
DHCP server ignores static assignment.

### ISSUE THREAD

**Issue by davidbdeath** [AdguardTeam/AdGuardHome#1005]
The DHCP server ignore the assignment of static IPs with the built in DHCP server.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

We also need to know what exact static assignment is ignored.

**Comment by davidbdeath** [comment]
is it because i'm running adguard home in a docker?

**Comment by ameshkov** [comment]
It shouldn't matter. The log file could help us figure what exactly is wrong

**Comment by davidbdeath** [comment]
I set it up so it's recording a log. How long should I let it run before attaching the log to this thread?

**Comment by ameshkov** [comment]
Just reproduce the issue and that would be enough.

We need to know as much details about the issue as possible

**Comment by davidbdeath** [comment]
Right now it's my shield TV not getting the correct IP address. I stopped trying to assign a static IP to my PC because it caused the custom client settings to not apply.
[logfile.txt](https://github.com/AdguardTeam/AdGuardHome/files/3848710/logfile.txt)

**Comment by szolin** [comment]
What is the MAC address of your device and what IP address did you configure for it as static?

**Comment by davidbdeath** [comment]
00:04:4b:39:8c:32 - 192.168.1.80

It's currently using 192.168.1.62. When i use my router for DHCP it assigns to the correct IP address. I sometime use the shield as a secondary plex server.

**Comment by szolin** [comment]
Thank you for the logs!  Your device requests the server to assign 192.168.1.62 to it and the server does it.  Instead, it should reject .62 and assign .80.

**Comment by davidbdeath** [comment]
I'm using AdGuards DHCP server and assigned the IP in AdGuard, so why doesn't AdGuard reject .62 and assign .80? I am not a noob i know how to setup a DHCP server. When I use my router for DHCP it works fine. I have never assigned .62 using my router. I've also had issues with assigning the correct IP to my NAS and when using a static IP for my desktop the custom client settings don't apply. I can't constantly switch back and not have my stuff work to create logs.

**Comment by ameshkov** [comment]
Marked as bug, assigned to v0.100 milestone

**Comment by szolin** [comment]
> so why doesn't AdGuard reject .62 and assign .80?

it's a bug
