### ISSUE TITLE
iOS download link problem

### ISSUE THREAD

**Issue by Linkontoask** [AdguardTeam/AdGuardHome#1008]
## There is a problem with the download button link, please update. 
[address](https://adguard.com/zh_cn/adguard-ios/overview.html?aid=18081&utm_source=browser_extension&utm_medium=popup&utm_campaign=ios_about)
I think if there is one less `cn`, the link I can access is [https://apps.apple.com/cn/app/apple-store/id1047223162](https://apps.apple.com/cn/app/apple-store/id1047223162)

**Comment by ameshkov** [comment]
@Linkontoask could you please explain what link do you have there?

On my side, "Download" link leads to the proper page

**Comment by NetE1** [comment]
It's Chinese language page https://adguard.com/zh_cn/adguard-ios/overview.html

So it should replace with https://apps.apple.com/cn/app/apple-store/id1047223162 instead https://itunes.apple.com/app/apple-store/id1047223162

**Comment by ameshkov** [comment]
Got it, thank you!

@Martynuk plz take care

**Comment by ArchiveBase** [comment]
Ping @Martynuk. Related to other languages as well.
