### ISSUE TITLE
Blocked services

### ISSUE THREAD

**Issue by ibnbd** [AdguardTeam/AdGuardHome#1010]
I see `Steam` on the Blocked services list, please add `Epic Games` or `Fortnite` there too.

**Comment by ArchiveBase** [comment]
```
||epicgames.com^
||unrealengine.com^
||fortnite.com^
epicgames-download1.akamaized.net
```

_Source
_https://github.com/nextdns/lists/blob/master/services.json
https://unrealstudiohelp.epicgames.com/s/article/Firewall-Whitelisting-for-Unreal-Studio-access?language=en_US__

**Comment by ibnbd** [comment]
@ArchiveBase thanks :)

**Comment by ameshkov** [comment]
Just in case anyone decides to take care of this issue, here's the file that needs to be changed (and it mentions the other two):
https://github.com/AdguardTeam/AdGuardHome/blob/master/home/blocked_services.go#L19

**Comment by ameshkov** [comment]
@IldarKamalov plz assist, I don't know how you were doing this:)

**Comment by IldarKamalov** [comment]
Usually we are using icons from [Icons8](https://icons8.com/icons/set/epic%20games). 
You can use the icon with multiple paths, just compress it in a service like [this](https://jakearchibald.github.io/svgomg/).

About `npm run watch`, we just run it from the `client` folder and it works.

**Comment by onedr0p** [comment]
@IldarKamalov thanks for the info Icons8 looks great, that was much easier. I opened a PR to review.

Also, `npm run watch` what port does this get served on? I cannot find it in the webpack config. Is there some magic that happens so I don't need to go to another port and just use the app?

**Comment by IldarKamalov** [comment]
Yes, `npm run watch` uses the current application port

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardHome/pull/1044
