### ISSUE TITLE
Which ports does AGHome need?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#1011]
I switched from bare iptables to `ufw` so i have to recreate the firewall rules for aghome. So my question is which rules it needs. Can you list them with their protocol and features which require it?

i guess:
```
53/UDP # for dns
80/TCP # for the webinterface
443/TCP # for the https webinterface
```

**Comment by ameshkov** [comment]
Check what ports are exposed by the docker image:
https://github.com/AdguardTeam/AdGuardHome/blob/master/Dockerfile#L23
