### ISSUE TITLE
The new version of AdGuardHome gives the stop command but still shows the running state!

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#1012]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Please file a normal bug report with enough data and steps to reproduce
