### ISSUE TITLE
[Feature request] Refuse to establish TLS connection if sni not match

### ISSUE THREAD

**Issue by OMICRON3069** [AdguardTeam/AdGuardHome#1014]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

As AGH being deployed in VPS, it's very important to avoid scanner from the internet. So it shouldn't establish TLS connection if client haven't provide a correct sni. 

i.e. Test DoT with wrong sni by `openssl s_client -servername fake.com -connect <server_IP>:853`,  and server return a certificate with correct server name:

```
CONNECTED(00000005)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = correct.com
verify return:1
---
Certificate chain
 0 s:CN = correct.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
............. cert data goes here
```

Another TLS application such as caddy(also written in golang), in this situation will refuse to connect
```
CONNECTED(00000005)
139962886459840:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1528:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 313 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

If AGH does not check sni, then anyone on internet can sniff port 853 with DNS query to know there is a DoT server.

I've already using nftables to filter unwanted DNS query, but still can't avoid.

### Proposed Solution

AGH refuse to establish TLS connection if sni not match.

### Alternatives Considered

Add some TCP load balancing software in front of AGH may help, but this will led confuse in statistics page due to source IP address being changed.

**Comment by ameshkov** [comment]
Makes sense, thank you!

**Comment by krombel** [comment]
This implementation causes a lot of aborts for clients which do not pass a SNI at all.
At least that is my impression as I have dozens of this in my logs:
```
2019/12/13 15:15:51 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
2019/12/13 15:15:52 [info] DNS: TLS: unknown SNI in Client Hello:
```
It might be there is a client implementation for DoT which does not send SNI at all which is therefore blocked resolving at all.
**I** don't want that

**Comment by ameshkov** [comment]
Hm, it might be indeed. I guess we should roll it back and make it configurable.

**Comment by krombel** [comment]
Another thing which breaks in this implementation: Multiple server_names are not working anymore.
I use one certificate to provide DoT for multiple domains (by using CN in the certificate). This is breaking here as well...

**Comment by ameshkov** [comment]
@krombel any idea what clients are that?

**Comment by krombel** [comment]
> @krombel any idea what clients are that?

I think unbound is such client. I use it in my infra and it stopped resolving while I had this version running.

**Comment by ameshkov** [comment]
@krombel got it, thank you!

We'll roll it back in the next beta that will be out today.
