### ISSUE TITLE
DHCP static lease is not applied when client reconnects

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1015]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.98.1-95-g21e0
* **How did you setup DNS configuration:**
  * Router + DHCP
* **If it's a router or IoT, please write device model:**
  * RPi3
* **Operating system and version:**
  * Rapsbian

### Steps to reproduce
1. Connect to Wi-Fi from my laptop
2. Check the list of DHCP leases
3. Find my laptop
4. Create a static lease with this Mac and a different IP address
5. Reconnect to Wi-Fi 

### Expected Behavior
The laptop gets a new IP

### Actual Behavior
It gets the old IP

**Comment by KamistixX** [comment]
Same issue here with a Synology NAS (with Docker and with static binary versions of AGH). Would love this to be fixed ! Thanks
