### ISSUE TITLE
请增加 定时重启和开关设置

### ISSUE THREAD

**Issue by 2791717016** [AdguardTeam/AdGuardHome#1017]
请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置请增加 定时重启和开关设置

**Comment by planet0** [comment]
> Please increase the timing restart and switch settings.

I'm not sure why you needed to spam the same request over a dozen times.

**Comment by ameshkov** [comment]
Btw, if I am getting it right, this issue is about the time spent on applying settings, and it's much better in v0.99 beta.
