### ISSUE TITLE
AdGuardHome Router Setup

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#1018]
Below describe specific details as requested due relevant faq page not exist @ameshkov

AdGuardHome router setup for cover all connected devices automatically without configure each of them manually. https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#router

However mentioned procedure no longer possible to set-up on most routers at all since some time (applies to Huawei, TP-Link etc)

_Manufacture explanation_
> _Because we have received the feedback and test it in our lab, we found that the DNS server provided by some internet service providers will be the same as the LAN IP address, which leads many problems.
So we set some restrictions on the latest firmware version of the router to prevent them from being in the same network segment._

It still possible to configure on few models that offer two DNS configuration options. ( DNS for WAN and DNS for DHCP ) then able set it on second area

But users experience following disadvantages,

- Unable to get connected router as a client.
- Unable to monitor or block router's itself DNS activities
 (such as connect to manufactures domains, third-party integrated security or services component related domains, connect to manufacture pre-defined (on firmware) custom dns server or root server.)

For OpenWRT, DD-WRT seems haven't placed this restriction (only checked firmwares, not all)

**Comment by planet0** [comment]
It might be possible to suggest using the AdGuard DHCP Server and turning off the router DHCP function to circumvent this.

**Comment by ArchiveBase** [comment]
@planet0 Actually that's for FAQ page as mentioned above rather than else. by the way i saw on crowdin already has that button from ago😄 Just you may haven't noticed AGHome DHCP server not supported for windows and it may take long time to implement because our @ameshkov wait for something since 2014🤣https://github.com/golang/go/issues/7175 however even use it we have to experience some cons as well.😊

**Comment by szolin** [comment]
@ArchiveBase, can you describe more in detail what you are suggesting?
Ideally, I think we should split our "Routers" section into 2 parts:
1. The first part will be the same tutorial as we have now.
2. Place a note that not all routers can be configured by the previous tutorial.  Enumerate those routers that can't be configured using option 1 and write another tutorial(s) for them.

Currently I don't know what information we should place into section 2.

**Comment by ArchiveBase** [comment]
@szolin make it bit detailed and newbie friendly. try to support for rest of operating systems somehow https://github.com/AdguardTeam/AdGuardHome/issues/616

- If internet stopped work/no query, client appear/ not reachable* after added adguard home server address to the router DNS configuration area or display error when try to add LAN addresses then necessary to use built-in DHCP server or configure each devices manually that's the uncomfortable solution for most windows users ask that question and it's not possible to suggest about docker, virtual machines etc for everyone.

- If the router management interface has two DNS configuration areas for WAN and DHCP then user able to add server address to that DHCP primary DNS but this option not available for all models.
_(Cons: unable to manage router as a client using adguard home)_

In my country, nearly 20 million people own such type* re-branded routers provided by both gov and private ISPs for TDD LTE(4G)

**Comment by ameshkov** [comment]
I guess we can add something about configuring the DHCP server (your point 2).

But I don't fully understand what can be added about point 1, this situation just should not occur if everything is configured properly.

**Comment by ArchiveBase** [comment]
> But I don't fully understand what can be added about point 1, **this situation just should not occur if everything is configured properly**.

See screenshots

<details><summary>Router model</summary>

![Screenshot_58](https://user-images.githubusercontent.com/46082456/70795820-47e95380-1dd3-11ea-9f55-5c8e034e1e02.png)


</details>

<details><summary>router model (ISP)</summary>

![Screenshot_54](https://user-images.githubusercontent.com/46082456/70795310-191ead80-1dd2-11ea-802d-b888e1b1a982.png)

</details>

**Comment by ameshkov** [comment]
Hm, you know, setting DNS in DHCP settings is generally the right and only way to configure AdGuard Home on a router.

**Comment by JACK-THINK** [comment]
I have another method. If your router uses dnsmasq as the DNS and DHCP server, you can make Adguard Home the upstream DNS server of dnsmasq. Read line 71-76 of [this](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/blob/master/script_bootloader/usr/adguardhome/bin/adguardhome_enable.service)

**Comment by ameshkov** [comment]
The problem of this method is that AGH won't see the real clients' addresses.

**Comment by JACK-THINK** [comment]
Yes. But apparently, it is impossible to replace the default DNS server in the firmware of most routers with Adguard-Home DNS server.

**Comment by ArchiveBase** [comment]
> I have another method. If your router uses dnsmasq as the DNS and DHCP server, you can make Adguard Home the upstream DNS server of dnsmasq. Read line 71-76 of [this](https://github.com/JACK-THINK/SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER/blob/master/script_bootloader/usr/adguardhome/bin/adguardhome_enable.service)

Usually no advanced facilities or options in ISP provide routers for home connections.

**Comment by szolin** [comment]
So once again, I don't know what exactly we should do here.
If we should update documentation - what exactly we should change and what text we should add?

As I understand, some users can't configure AGHome on their router devices using just DNS server address field in router's configuration.  Can anyone write a text that can help those users to solve their problems?  If so, I can merge your text into our Wiki.  If not - we should just move this task out of this milestone, as I have no such router devices and I can't test anything or write a tutorial on this issue by myself.

**Comment by ArchiveBase** [comment]
Ah! just a simple thing @szolin 
> some users can't configure AGHome on their router devices using just DNS server address field in router's configuration. Can anyone write a text that can help those users to solve their problems?

You can write about below options if any router not support for that,
- Enable and use built in DHCP server or
- Follow per device configuration method
 
Alternatively, some of those routers may still support if DNS server in different network segment with public IP
