### ISSUE TITLE
[QUESTION] What response does the client receive when the filter is triggered

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1019]
Answer, please, requests filtered by filters receive an empty response or are forwarded as to some address ( as here https://diversion.ch/faq-reader/what-does-pixelserv-tls-do.html) or receive something in response?
 The question arose because if the answer is empty perhaps the request will be sent to the second DNS (DNS router, which is automatically put when you specify the DNS settings dhcp lan router) and can be skipped.

**Comment by ArchiveBase** [comment]
Meantime read https://github.com/AdguardTeam/AdGuardHome/issues/912

**Comment by ameshkov** [comment]
In the beta version we print this information to the filtering log
