### ISSUE TITLE
Couldn't get version check json when updating filters

### ISSUE THREAD

**Issue by krevoit** [AdguardTeam/AdGuardHome#1020]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.98.1
* **How did you setup DNS configuration: 
  *  System
* **If it's a router or IoT, please write device model:**
  *  OpenVZ VPS
* **Operating system and version:**
  *  Debian 8
### Expected Behavior

To load and update filters from websites
### Actual Behavior

When I try to update a filter or add a new filter I get a timed out error as shown here. I have experienced this on multiple different servers I have used for AdGuard and multiple websites which I have attempted to load a hosts list from.

### Additional Information

Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: read udp 127.0.0.1:48382->127.0.0.1:53: i/o timeout | 502

**Comment by szolin** [comment]
dup: #934
