### ISSUE TITLE
DNS Settings description text is inaccurate

### ISSUE THREAD

**Issue by NetE1** [AdguardTeam/AdGuardHome#1022]
Under DNS settings window

Upstream DNS servers
If you keep this field empty, AdGuard Home will use Cloudflare DNS as an upstream.

Currently AdGuardHome doesn't allow to keep that field empty and save
_Error: control/set_upstreams_config | wrong upstreams specification: no default upstreams specified | 400_

In this cause, set tls://8.8.8.8 (Google) as Upstream and save. next scene 

 Now leave Bootstrap DNS servers field empty and save. (AGH allows to do it) but you'll see on network monitoring tools AdGuardHome started to using Cloudflare DNS

Try for v0.99 milestone and Interested https://github.com/AdguardTeam/AdGuardHome/issues/960
- [X] I am running the latest version

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1208

Bootstrap DNS servers (adguard home description)
Bootstrap DNS servers are used to resolve IP addresses of the DoH/DoT resolvers you specify as upstreams.

Bootstrap DNS (wiki)
List of DNS servers used for initial hostname resolution in case an upstream server name is a hostname

Mix it to the description
