### ISSUE TITLE
Reset DHCP configuration

### ISSUE THREAD

**Issue by NetE1** [AdguardTeam/AdGuardHome#1024]
#### Issue Details
Currently once we configured DHCP server next unable reset config either not possible save with empty field after erased inputs. so we have to stop AdGuardHome service and edit .yml file manually for erase exist config.

#### Expected Behavior
Add 'Reset' button so we can revert changes easily even saved anything invalid or outdated details

#### Actual Behavior
All entered configuration remains. selected DHCP interface, gateway IP, range, subnet mask

#### Additional Information
AdGuardHome encryption settings page has 'Reset settings' button

**Comment by ameshkov** [comment]
Yeah, we should do it just like what's done in the encryption settings
