### ISSUE TITLE
[Feature Request] Save\Reserve settings when updating

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#1025]
При обновлении AdGuard Home через веб интерфейс создается папка agh-backup и в нем сохраняется резервная копия предыдущий версии AdGuard Home "AdGuardHome.exe" но не сохраняются настройки "AdGuardHome.yaml" и хотелось бы чтоб сохранялись настройки - потому что бывает такое что мы обновляемся а версия нестабильная и требует fix а его в это время нет и по этой причине нужно откатить версию AdGuard Home а настройки уже не будут подходить для прошлой версии после обновления и временно нужно создавать новые настройки и ждать fix 
При этом у меня настройки очень тонко настроены и чтоб заново их настраивать понадобится очень много времени и усилий что как я считаю плохо - а если можно взять с копий\резервной копии то на много будет удобнее как я считаю

Как раз такая ситуация у меня была в этом запросе: #878 когда я обновился и он у меня не работало как нужно и мне пришлось на лету вам помогать потому что я не мог восстановить прошлые настройки и все дома сидели без интернета (потому что dns был раскидан через роутер) пока я вам помогал

+ И так же желательно сделать функцию восстановления резервной копии из веб интерфейса - сам AdGuard Home и его настройки. А новая версия которая была установлена будет перемещена в папку agh-backup-{version} или agh-backup-new.

**Comment by ameshkov** [comment]
Makes perfect sense, thank you!

**Comment by szolin** [comment]
> но не сохраняются настройки "AdGuardHome.yaml"

Файл `AdGuardHome.yaml` сохраняется в папке `agh-backup` при обновлении.  Попробуйте проверить это ещё раз с более поздней версией, например v0.99.  Если нет - пришлите логи приложения пожалуйста.

> функцию восстановления резервной копии из веб интерфейса

Я не думаю, что это такая необходимая вещь на текущий момент.  Эта задача решается одной командой в терминале.
