### ISSUE TITLE
Ignore certain "$" qualifiers instead of disqualifying their entries

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1026]
Strongly based on #892 and #867, but with a more clearcut and broader goal.

### Prerequisites

- [x] I am running the latest version (0.98.1)
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard Home's support for `$` qualifiers were very limited last time I checked 2-ish months ago, and I propose two things to help on the matter a bit:

1) That certain `$` qualifiers, due to their massive prevalence in major lists and/or the unlikeliness of them breaking other stuff on the pages, will be simply ignored instead of disqualifying the entries.
2) For some `$` qualifiers that are a bit more sensitive, a checkbox menu could be added to AGH's settings to let users decide if they want to ignore the entries instead of disqualifying them.

Here's my proposal:

Add full native support, as it's technically not DNS-related:
• `$badfilter`

Ignoring instead of disqualifying:
• `$third-party` / `$3p`
• `$all`
• `$popup`
• `$xmlhttprequest` / `$xhr`
• `$empty`
• `$document` / `$doc` (blacklistings only)

Add to an advanced settings menu about whether to ignore instead of disqualify:
• `$~third-party` / `$first-party` / `$1p`
• `$image`
• `$font`
• `$popunder`
• `$script`
• `$dom`
• `$subdocument`

Unsure what the best approach would be:
• `$generichide`

Probably best to continue to disqualify for now:
• `$csp`
• `$css`
• `$domain`
• `$frame`
• `$inline-script`
• `$media`
• `$object-subrequest`
• `$other`
• `$redirect`
• `$websocket`
• `$genericblock`
• `$~font`
• `$~image`
• `$~object`
• `$~stylesheet`
• `$~subdocument`
• `$~third-party`
• `$~xmlhttprequest`

Most likely out of scope for this issue report:
• `$network`

### Proposed Solution
For №1 and/or №2 in "Problem Description" to be implemented.

### Alternatives Considered
Adding native support for as many of these things as possible would've been super-awesome, but I've frequently been explained that it's not a realistic option.

### Additional Information
*EasyList Without Element Hiding Rules* and *Liste FR* are very prominent showcases of `$` qualifiers that are currently not supported by AGH.

**Comment by ameshkov** [comment]
> Add full native support, as it's technically not DNS-related:
> $badfilter

Yeah, we're going to do it.

> Ignoring instead of disqualifying:

I disagree with `$third-party` actually. Ignoring it will bring tons of false positives.

**Comment by szolin** [comment]
> $badfilter

https://github.com/AdguardTeam/urlfilter/commit/a27f10be82d3b08df6a773ba9c513a8354f30106

**Comment by ameshkov** [comment]
We came up with a document explaining how to write hosts blocklists:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists

It lists all the supported modifiers.

Also, I'd like to keep the current behavior and continue to throw off rules with unknown modifiers.

On the other hand, it might still be useful to automatically convert parts of traditional adblock-style syntax lists to the DNS-compatible lists.

I think we should consider providing a tool or script for that. We can use the script from here as a basis: https://github.com/AdguardTeam/AdGuardSDNSFilter/tree/master/Filters
