### ISSUE TITLE
Does not work AdGuardHome Beta

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#1028]
Перешел на Beta версию v0.98.1-118-g309f и заметил что в течении некоторого времени AdGuardHome закрывает терминал и он перестает работать - я его запускал через cmd чтоб вам показать.
<details><summary>Screenshot:</summary>

![cmdAdGuardHomeBeta](https://user-images.githubusercontent.com/46345396/65758589-ff9a8d80-e121-11e9-9193-9e9c7ca782cf.png)
</details>

**Comment by szolin** [comment]
6a65c79a037843bccd47d78d280498415a8c0ee1
