### ISSUE TITLE
NSPOSIXERRORDOMAIN:1

### ISSUE THREAD

**Issue by ao-ku** [AdguardTeam/AdGuardHome#1030]
ADGUARD 2.1.2.595 (CL-1.4.138)
MACOS MOJAVE 10.14.6
SAFARI 12.1.2 (14607.3.9)

When trying to access some websites (mostly e-commerce)  I get **"The operation could not be completed. Operation not permitted" (NSPOSIXErrorDomain: 1)**.  When Adguard disabled the website loads normally.
Thanks.

**Comment by ArchiveBase** [comment]
Close this and open on relevant repository https://github.com/AdguardTeam/AdguardForMac/issues/new
