### ISSUE TITLE
After restarting the router, you have to restart the raspberry with AdGuard Home

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1033]
After restarting the router, you have to restart the raspberry with AdGuard Home, because customers do not receive a response from it to the DNS request.

* **Version of AdGuard Home server:**
  * 0.98.1
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B+

**Comment by ameshkov** [comment]
Could it be the same issue as here #633 ?

**Comment by YBS-PC** [comment]
No. A little wrong. Problems at reset of Pi with AGH do not arise. The problem occurs when you restart the router in which as DNS for some clients specified ip of the Pi with AGH . The Internet stops working on those clients for whom as DNS is specified Pi with AGH, and for other clients everything works ok. When I reboot Pi with AGH, these clients get access to the Internet too.

**Comment by ameshkov** [comment]
Huh, to be honest, I don't understand what could be causing this. Any logs from these clients?

**Comment by YBS-PC** [comment]
I do not know how to get the log files. But I think that the option "periodic restart of the service in the absence of an Internet connection" with the ability to select the number and frequency of reboots, as well as the ability to disable it, could solve this problem.

**Comment by ameshkov** [comment]
Logs:

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by YBS-PC** [comment]
;; QUESTION SECTION:
;yandex.ru.	IN	 A

2019/10/05 00:20:21 1792#291 [debug] Using settings for client with IP Clint'sIP
2019/10/05 00:20:21 1792#254 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(): Start handling new UDP packet from Clint'sIP:59204
2019/10/05 00:20:21 1792#254 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 46551
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;yandex.ru.	IN	 A

2019/10/05 00:20:21 1792#254 [debug] Using settings for client with IP Clint'sIP
2019/10/05 00:20:21 1792#291 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 44 ms
2019/10/05 00:20:21 1792#291 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 46551
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;yandex.ru.	IN	 A

;; ANSWER SECTION:
yandex.ru.	268	IN	A	77.88.55.60
yandex.ru.	268	IN	A	5.255.255.60
yandex.ru.	268	IN	A	5.255.255.70
yandex.ru.	268	IN	A	77.88.55.66

2019/10/05 00:20:21 1792#254 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 43 ms
2019/10/05 00:20:21 1792#254 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 46551
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;yandex.ru.	IN	 A

;; ANSWER SECTION:
yandex.ru.	268	IN	A	77.88.55.60
yandex.ru.	268	IN	A	5.255.255.70
yandex.ru.	268	IN	A	77.88.55.66
yandex.ru.	268	IN	A	5.255.255.60

2019/10/05 00:20:23 1792#278 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(): Start handling new UDP packet from Clint'sIP:55688
2019/10/05 00:20:23 1792#278 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 39519
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

**Comment by YBS-PC** [comment]
I tried to open the website yandex.ru

**Comment by ameshkov** [comment]
Was there any issue while you were doing it? The log looks okay

**Comment by YBS-PC** [comment]
at clients where AGH is specified as DNS the Internet began to work after restart of service of AGH

**Comment by tingalvin** [comment]
Could it be when you restart your router, your Pi became unable to get IP address from router, hence requiring a restart?
Does setting a static IP on the Pi help?

**Comment by YBS-PC** [comment]
Pi has static ip in router`s dhcp

**Comment by zombu2** [comment]
thats still dhcp assigned and since router went offline pi lost its ip and probably needed a restart since sometimes it will not request a new one for some reason

set static in the pi and that problem will probably go away

**Comment by planet0** [comment]
@zombu2 is right, there should be a static IP set on the Pi to avoid relying on the DHCP assigned IP.

Below is based off: https://raspberrypi.stackexchange.com/a/39274

For a static IP address on an Ethernet connection:

1. `sudo nano /etc/dhcpcd.conf`

2. Type in the following lines on the top of the file (based of your router):

```
interface eth0
static ip_address=192.168.1.XX/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1
```

3. `sudo reboot`

**Comment by planet0** [comment]
Actually @ameshkov, could there be a feature request to automatically do the above to set a static IP to the Pi? This will avoid issues like this from occurring.  Pi-hole informs the user during setup that a static IP will be set based off the current assigned IP and displays it to the user, then doing the above steps.

**Comment by ameshkov** [comment]
Currently, we're suggesting it only when you try to start the DHCP server.

So you think it makes sense to do it regardless of the DHCP server state?

**Comment by YBS-PC** [comment]
> static domain_name_servers=192.168.1.1
Here because of it i did not put static ip . It is not clear-it is necessary to specify the ip of the router or ip of the agh-raspberry...

**Comment by planet0** [comment]
> it is necessary to specify the ip of the router or ip of the agh-raspberry

For the DNS, you can either point it to the router to use what the router DNS is set for (such as your ISP DNS), or point it to any other DNS (Google 8.8.8.8, Cloudflare 1.1.1.1, even AdGuard DNS, etc.)

It is not ideal to point it back to the Raspberry. Think of this as like the AdGuard Home Bootstrap DNS settings - the DNS you specify is used for Raspberry updates and other local traffic that doesn't really need to be filtered anyway.


> So you think it makes sense to do it regardless of the DHCP server state?

It makes sense to make sure that the IP never changes if Users are pointing their devices to use the IP address as their DNS server - if their router or modem resets, or they accidentally set a device with a static lease of the same IP, or for all other types of scenarios, using the static IP will prevent User errors.

**Comment by ameshkov** [comment]
@planet0 makes sense: https://github.com/AdguardTeam/AdGuardHome/issues/1069

**Comment by YBS-PC** [comment]
static ip did not solve the problem. perhaps DHCP in a router is guilty...

**Comment by zombu2** [comment]
no if it did not make a difference you doing something wrong

**Comment by YBS-PC** [comment]
I think it has to do with
https://github.com/AdguardTeam/AdGuardHome/issues/875

maybe I'm wrong
