### ISSUE TITLE
.com.home Domains to be blocked

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#1034]
### Prerequisites
- [X] I am running the latest version (v0.98.1-118-g309f-dirty)
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Problem: After I started making my router go through my computer running AdGuard Home I started noticing domains with *.com.home start showing up. A lot of the time these were ads/trackers and I had to go through and manually add them to my own list. 

### Proposed Solution
If a domain is blocked-such as example.com-then make it block example.com.home aswell

### Alternatives Considered
Another possible alternative is to add .home after every domain in your blocklist (Though this isn't efficient)

### Additional Information
![image](https://user-images.githubusercontent.com/39284087/65832986-d3e9e580-e290-11e9-9a42-fe3822a2ff1d.png)

**Comment by Cybo1927** [comment]
Another good example

![image](https://user-images.githubusercontent.com/39284087/65877937-631ff780-e37c-11e9-8fb9-3bc6c86c2aa3.png)

**Comment by ArchiveBase** [comment]
For your reading
https://www.dnsknowledge.com/whatis/nxdomain-non-existent-domain-2
https://www.extremenetworks.com/extreme-networks-blog/monitoring-dns-nxdomain
https://www.netscout.com/what-is-ddos/dns-nxdomain-flood
https://blog.cloudflare.com/debugging-war-story-the-mystery-of-nxdomain

**Comment by Cybo1927** [comment]
That's good to know... I turned off my sister, and I's school computers. They run GoGuardian (spyware) and it's stopped. Thanks for the information though this will undoubtedly help in the future.
