### ISSUE TITLE
Error reporting after adding domain name and SSL certificate to encryption settings

### ISSUE THREAD

**Issue by zhaokelei** [AdguardTeam/AdGuardHome#1038]
I built the AdGuard Home server on the server. When I added the SSL certificate of domain name and domain name to the encryption settings, I clicked the wrong report, and a string of false prompts appeared in the lower right-hand corner of the page. DNS over HTTPS and DNS over TLS services could not be used, and only used the conventional UDP protocol's resolution service. I wanted to know what the reason was. Why are errors prompted when ports 443 and 853 are occupied?

**Comment by ameshkov** [comment]
We should test it on our side I guess.

Have you built AGH from the master branch?

**Comment by szolin** [comment]
@zhaokelei Can you print the exact error messages you see, or post a screenshot?
