### ISSUE TITLE
How do I get to https video ads?

### ISSUE THREAD

**Issue by snakwu** [AdguardTeam/AdGuardHome#1045]
How do I get to https video ads?
https://www.youku.com/

**Comment by Omoeba** [comment]
AGH and all other dns-based ad-blockers can only block entire domains. Most videos ads are delivered using the same domain as the content, making them impossible to block via dns without blocking the videos themselves.

**Comment by snakwu** [comment]
The filtering mode of adb plus is also filtered through dns, but adb plus can be implemented.

**Comment by ameshkov** [comment]
If you mean adblock plus then no, it does not use DNS.

**Comment by snakwu** [comment]
我不知道你中文能看明白不？我的路是oprnwrt，然后在另一台机器安装ADG，然后在openwrt上把所有dns请求转发到ADG上去，下面的子设备只能去除http网站的广告，app和https的广告不能去除

**Comment by ameshkov** [comment]
Well, I don't speak Chinese, but Google Translate helps a lot:)

In the case of AG Home, if the ads are loaded from a third-party domain, AG Home can block this domain, regardless of whether it uses http or https. You just need to figure out what domain is responsible for ads on that website.

However, if the ads are loaded from the same domain as the website, then this is not possible to block without blocking the whole website.

**Comment by snakwu** [comment]
这种工作方式有机会改变不，大部份的广告都是同域名下的，这样去除广告效率低

**Comment by ameshkov** [comment]
It depends on the website. Anyways, more flexible ways of blocking will be available when #391 is implemented

**Comment by snakwu** [comment]
#391是一年前提出的，这个什么时候能实现

**Comment by DavidTai780** [comment]
> It depends on the website. Anyways, more flexible ways of blocking will be available when #391 is implemented

Hope AdGuard Home can add a proxy or VPN just like what i am using now with the Kaspersky Internet Security create a proxy and filtering all the ads and anti tracking(url types) for those items cannot be done with AGH.

**Comment by 2Kil** [comment]
> 我不知道你中文能看明白不？我的路是oprnwrt，然后在另一台机器安装ADG，然后在openwrt上把所有dns请求转发到ADG上去，下面的子设备只能删除http网站的广告， app和https的广告不能去除

adb plus的规则貌似有改写js的功能，但是ADG没有，ADG只能屏蔽域名。
