### ISSUE TITLE
Docker: Error starting userland proxy: listen udp 0.0.0.0:68: bind: address already in use.

### ISSUE THREAD

**Issue by pmoerz** [AdguardTeam/AdGuardHome#1049]
Hi there,

maybe i'm blind, but i searched all issues and didn't find a solution.

- [ x] I am running edge/stable Version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

* **Version of AdGuard Home server:**
actual stable and (testwise) edge version

* **If it's a router or IoT, please write device model:**
Raspberry Pi 3 Model B+
 
* **Operating system and version:**
rasbian lite buster

### Expected Behavior
I followed the guide under: https://github.com/AdguardTeam/AdGuardHome/wiki/Docker,
but used the ARMHF - 32bit ARM build.

### Actual Behavior
The installation ends with following message:

> docker: Error response from daemon: driver failed programming external connectivity on endpoint adguardhome (31e515954eb3e112d81559418adb8e09d4411f84bbf94b742a7330658e30b02b): Error starting userland proxy: listen udp 0.0.0.0:68: bind: address already in use.

### Additional Information
When i use host mode, it works. Is there any downside using host mode? The installation via the guide is bridged mode. Sorry i'm completely new to Linux. The Raspi was set up new several times, and just docker and portainer were installed. For installing adguard i didn't use portainer, i did it via ssh console.

Thank You

**Comment by ameshkov** [comment]
Tbh, this sounds more like a Docker issue, not ours.

> When i use host mode, it works. Is there any downside using host mode?

Not really. 

We recommend bridged only because it should work on any platform/OS (host mode does not work on MacOS).

**Comment by pmoerz** [comment]
Thank you.

**Comment by whoizit** [comment]
@pmoerz how do you use host mode?

**Comment by whoizit** [comment]
it started with me when I changed port:
```
#!/bin/sh

sudo docker run \
    --name adguardhome \
    -v /my/own/workdir:/opt/adguardhome/work \
    -v /my/own/confdir:/opt/adguardhome/conf \
    -p 192.168.0.100:53:53/tcp \
    -p 192.168.0.100:53:53/udp \
    -p 192.168.0.100:67:67/udp \
    -p 192.168.0.100:1068:68/tcp \
    -p 192.168.0.100:1068:68/udp \
    -p 192.168.0.100:80:80/tcp \
    -p 192.168.0.100:443:443/tcp \
    -p 192.168.0.100:853:853/tcp \
    -p 192.168.0.100:3000:3000/tcp \
    -d adguard/adguardhome

```

**Comment by sakuyamaij** [comment]
Because Raspbian use port 68 as DHCPD defaultly.

**Comment by fernandodev** [comment]
port 68:UDP is used for client DHCP and not for servers so the correct instruction for starting the docker should remove that

**Comment by bastafidli** [comment]
It seems the wiki 

https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#quickstart

is still incorrect as of today as it still says

> -p 67:67/udp -p 68:68/tcp -p 68:68/udp: add if you intend to use AdGuard Home as a DHCP server.


but per 68 is the port on the client side

https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol#:~:text=The%20DHCP%20employs%20a%20connectionless,on%20UDP%20port%20number%2068.

Also the wiki in section 

https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#dhcp

says

> If you want to use AdGuardHome's DHCP server, you should pass --network host ...  Note that port mapping with -p is not necessary in this case.


which makes the documentation confusing.
