### ISSUE TITLE
Forgot login details

### ISSUE THREAD

**Issue by jayadeepan** [AdguardTeam/AdGuardHome#1050]
I forgot my login details to adguard home. is it possible to reset or change my password?

**Comment by ArchiveBase** [comment]
View AdGuardHome.yaml file using text editor then you can be see the username and password

**Comment by jayadeepan** [comment]
Got it. Thank you.

**Comment by hesss5** [comment]
i think in new beta password are encrypted
and then you have blank   password:  or change it
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset
