### ISSUE TITLE
DHCP settings

### ISSUE THREAD

**Issue by montuIO** [AdguardTeam/AdGuardHome#1052]
I installed and setup the AdGuard Home on Vultr, but I'm unable to get DHCP settings to work. I keep getting this error message below:

Error Details:
open /etc/dhcpcd.conf: no such file or directory

**Comment by ameshkov** [comment]
Well, you won't be able to use a DHCP server on a VPS anyways.

What for the error, @szolin what do you think, should we address it?

**Comment by szolin** [comment]
> should we address it?

We should support setting a static IP on other Linux distributions, not just Raspbian.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/616
