### ISSUE TITLE
How to recover all setting before installing AdGuardHome

### ISSUE THREAD

**Issue by n00d1e5** [AdguardTeam/AdGuardHome#1057]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** v0.98.1
  * 
* **How did you setup DNS configuration:** Linux
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:** Ubuntu 18.04.1
  * 

### Expected Behavior

There should be an option like: AdGuard -s reset

### Actual Behavior

Once I started AdGuardHome on my Linux VPS, in the first configuration (x.x.x.x:3000),  I chose the wrong IP address (y.y.y.y).

Now, I can not access to the setting page:
- y.y.y.y is not accessible from outside
- Can not access 127.0.0.1:3000, because there is no browser
- Can not install any browser because "Temporary failure in name resolution"

**So, how can I reset all settings, please?**

### Screenshots

<details><summary>Screenshot:</summary> None

</details>

### Additional Information

Tried solutions (not working, for sure):
- /etc/hosts checked (only 127.0.0.1)
- /etc/resolv.conf checked (file no existes)
- /etc/network/interfaces checked (empty)
- /etc/resolvconf/resolv.conf.d/base checked (file no existes)

**Comment by n00d1e5** [comment]
Finally, I find a temporary solution:
Every time after machine rebooted, I have to run:
```sysctl -w net.ipv4.conf.all.route_localnet=1```

Still not find a "lifetime" solution.

**Comment by ArchiveBase** [comment]
@n00d1e5 You can edit the AdGuardHome.yaml using text editor or terminal

**Comment by ameshkov** [comment]
@ArchiveBase is right, you simply need to stop AGH, delete the `AdGuardHome.yml` file, and start it again
