### ISSUE TITLE
AGH Dashboard Shown "ERR_TOO_MANY_RETRIES"

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdGuardHome#1062]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.98.1
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 B+
* **Operating system and version:**
  * Latest Raspbian Buster

### Expected Behavior

Login and load AdGuard Home's Dashboard as normal
### Actual Behavior

Occur an  error "ERR_TOO_MANY_RETRIES" for those browser has recently logged in account. This would not occur if I am using other browser that haven't login the AGH or other devices which is not logged in the dashboard recently.

This error page shown when you just access the dashboard management page.

### Screenshots

First IoT Device's Screenshoot
![Screenshot (139)](https://user-images.githubusercontent.com/26398101/66699716-a0409e00-ed1b-11e9-8209-a17ed2970ac4.png)

Second IoT device's Screenshoot
![Screenshot (140)](https://user-images.githubusercontent.com/26398101/66699942-fadaf980-ed1d-11e9-9604-64a37886f4d8.png)

AGH on PC's Screenshoot
![Screenshot (141)](https://user-images.githubusercontent.com/26398101/66699997-6b821600-ed1e-11e9-94e2-30636768d491.png)

### Additional Information
Important  : 
- This problem start to occur after i use the /etc/fstab to mount the "/var/log" directory as tmpfs in RAM. This issue cannot get solved even i reinstall all AGH and reinstall the OS.
- I has also tried this situation in other IoT devices with editing the /etc/fstab to mount "/var/log". The result was same.
- I have multiple devices to run the AGH for backup and difference segment's client, this situation also effected other devices's AGH dashboard. 
- Installation page can be accessed, only those page required the login authorization only cannot be access and occur the problem mentioned above.
- AGH's Dashboard can also access via incognite mode.

This is the log that collected from the AGH.
[agh.log](https://github.com/AdguardTeam/AdGuardHome/files/3720478/agh.log)

New Update on this situation :
this situation seem like issue of Google Chrome, i found it occur on every http authencation web page.

**Comment by ameshkov** [comment]
Could it be that you have a browser extension that removes the `Authorization` HTTP header? Looks as if you do

**Comment by DavidTai780** [comment]
Thank you for your great answer, after testing for each browser extension, i found an extension is trying to do what you said. It is a VPN extension

The extension is https://chrome.google.com/webstore/detail/%E6%B5%B7%E6%A3%A0vpn-%E5%85%8D%E8%B4%B9%E5%9B%9E%E5%9B%BD%E5%8A%A0%E9%80%9F%E5%99%A8/bdlcnpceagnkjnjlbbbcepohejbheilk

Thanks a lot for your answer !
