### ISSUE TITLE
Client ranking problem

### ISSUE THREAD

**Issue by xmapst** [AdguardTeam/AdGuardHome#1063]
Can you use the MAC to identify the client?
My application scenario:
1. Deploy AdGuardHome with raspberrypi
2, openwrt route default route points to the address of [1]
3, the client default to use openwrt DNS
The following occurs:
All clients are ip for openwrt routing

**Comment by ameshkov** [comment]
You can, but it's important that AG Home must be used as a DHCP server in this case
