### ISSUE TITLE
Malware and Phishing filter information for devices that hit the filter

### ISSUE THREAD

**Issue by zombu2** [AdguardTeam/AdGuardHome#1064]
Is there any way we could get a feature that shows us the actual IP and URL of a device that hit the malware and phishing filter? Would be great to know which device it was so we can go and scan the machine for infections ..

**Comment by ameshkov** [comment]
Well, it's all in the query log. The problem is that there's no option to filter them in the query log ("show filtered" will show all blocked requests including ads & trackers).

We'll improve the query log in the future. Meanwhile, the only option is to inspect the querylog file manually.

**Comment by zombu2** [comment]
Which can be quiet cumbersome if you have millions of requests and some chatty roku's 
maybe a second log for the maleware and phishing would be adequate
