### ISSUE TITLE
If you run an old version, not the latest version is suggested for update

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#1065]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** 0.94
* **How did you setup DNS configuration:** system settings in Windows
* **Operating system and version:** Win7 x64

### Expected Behavior
Suggested the latest version.

### Actual Behavior

Not recent version is suggested.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/66746765-642c4b00-ee8b-11e9-8c4c-f622abbdd330.png)

</details>

**Comment by ameshkov** [comment]
That's okay for the old versions that do not support autoupdate
