### ISSUE TITLE
Suggest setting a static IP while doing initial setup

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1069]
See the thread here:
https://github.com/AdguardTeam/AdGuardHome/issues/1033#issuecomment-541629939

I guess instead of suggesting doing it while configuring a DHCP server, we can do this while doing the initial setup.

I am not sure if it's easy to automate on Windows or Mac so on these platforms we can simply show instruction on how to do this manually.

**Comment by szolin** [comment]
Maybe these docs can help us to add support for Windows and OSX in the future:
https://social.msdn.microsoft.com/Forums/en-US/84ab53c2-1188-494d-9aae-028eafe05800/how-do-i-programatically-change-from-dhcp-to-static-ip-and-back-again
https://00f.net/2011/08/14/programmatically-changing-network-configuration-on-osx/

**Comment by ameshkov** [comment]
@szolin let's have a separate issue for this just in case
