### ISSUE TITLE
Unblocked domain still not resolving in AGH

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#1070]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.98.1
* **How did you setup DNS configuration:**
  * Windows Server 2012 R2 DHCP server
* **If it's a router or IoT, please write device model:**
  *  n/a
* **Operating system and version:**
  * Windows Server 2012 R2

### Expected Behavior

After Unblocking a domain name lookup from the Query Log, the domain name being requested should resolve

### Actual Behavior

The domain name is resolving as 0.0.0.0 despite showing as not blocked in the Query Log
Changing the same client to Google DNS shows correct IP resolved.

### Screenshots

<details><summary>Screenshot:</summary>

192.168.0.140 is the AGH server
192.168.0.53 is the client (Windows 10 1903)

This is what a nslookup shows:

![AGH issue2_2019-10-15_13-58-33](https://user-images.githubusercontent.com/17214552/66796658-17f90d80-ef54-11e9-9c3e-a7f5aae00bb0.jpg)

If I change client DNS to Google, same nslookup:

![AGHissue3_2019-10-15_13-58-59](https://user-images.githubusercontent.com/17214552/66796674-22b3a280-ef54-11e9-8d0b-d33fa10f1fae.jpg)

This is the AGH Query Log showing the unblocked request, but resolving to 0.0.0.0
![AGH-issue1_2019-10-15_13-56-59](https://user-images.githubusercontent.com/17214552/66796805-7f16c200-ef54-11e9-83c2-47e401ca7e04.jpg)

</details>

### Additional Information

The following custom filter rule exists - @@||sjvpn.marketo.com^$important

**Comment by ameshkov** [comment]
@AnthonyBe what do you have in the upstream of AGH? Could it be that you have AdGuard DNS there?

**Comment by AnthonyBe** [comment]
Upstream DNS settings in AGH are:
tls://1dot1dot1dot1.cloudflare-dns.com
tls://one.one.one.one
tls://dns.adguard.com

and "Use parallel queries to speed up.." is enabled

Apologies, I hadn't remembered that I added tls://dns.adguard.com as one of the options!
I'll remove it and see what happens.

**Comment by AnthonyBe** [comment]
That resolved the issue!
