### ISSUE TITLE
Incapability to maintain custom filtering rules

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#1071]
#### Steps to Reproduce

- Open below pages in two separate tabs and keep them opened
https://xxx.xxx.xx.xxx/#filters
https://xxx.xxx.xx.xxx/#logs

-  Block any domain name using 'block' button on query log page then go to filters page and refresh, you'll see it updated under 'custom filtering rules'

-  Write any domain names on 'custom filtering rules' field then click apply. If necessary refresh the page to ensure it applied as well 

-  Go to query log page again and block a domain name

-  Then go back to filters page and refresh, you'll see all manually written domain names erased (means from .yaml file)

_(It doesn't occur when perform that task within single tab)_

AdGuard Home v0.98.1 | Windows

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2075

**Comment by Aikatsui** [comment]
Related but not duplicate https://github.com/AdguardTeam/AdGuardHome/issues/2374

**Comment by ameshkov** [comment]
Tbh I think this IS duplicate and will be solved automatically if #2374 is implemented.
