### ISSUE TITLE
Subscribing to a filterlist that gets deleted, causes 2 connection attempts to it per minute.

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1072]
From what I can determine, if one is subscribing to a filterlist that gets deleted by its maintainer, AdGuard Home tries to initiate 2 connections to it (1 AAAA and 1 A) every *minute* without ever taking any breaks. This clogs up the logger quite heavily and also looks a bit weird.

For context, it was in my case about a list I made called `🛰 Update whitelister for «PiHole Blocklist SmartTV»`, previously hosted at https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SmartTVUpdateWhitelister.txt (now a dead link), before I deleted it upon realising that [the list it was supposed to supplement](https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt) really did support submissions to unbreak system updates after all.

My best assumption on how it could be reproduced:

1) Create a list of some sort.
2) Subscribe to it in AdGuard Home.
3) Delete the list from its original URL.
4) Wait up to 2 hours.
5) See that the AdGuard Home logger is going ballistic trying to sync constantly with that now-gone list.

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.98.1
* **How did you setup DNS configuration:**
  * Not applicable
* **If it's a router or IoT, please write device model:**
  * Not applicable
* **Operating system and version:**
  * Windows 10 May 2019 Update

### Expected Behavior

Less frequent syncing attempts in the event of a list syncing failure. Possibly also some kind of infobox warning about list connection failures if it goes on for a few days, so that the owner of the AdGuard Home setup can more easily get to know that there's a problem with it.

### Actual Behavior

Explained in the introduction at the top and in the screenshots below.

### Screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/22780683/66857909-85bf2c80-ef88-11e9-9f72-c009de250a23.png)
![image](https://user-images.githubusercontent.com/22780683/66857987-b43d0780-ef88-11e9-90c8-47c12fa1a1ce.png)
![image](https://user-images.githubusercontent.com/22780683/66858571-d6835500-ef89-11e9-8e88-493f72c54b22.png)

</details>

### Additional Information

None that I am currently aware of.

**Comment by ArchiveBase** [comment]
Currently AGHome detect when we try to add invalid URL ex: https://raw.com/nonexist.txt (actually fail fetch) so the same possible use at here and stop check for updates

However i prefer see AG enhance it properly because that could trigger when internet doesn't work, incorrect DNS configuration or failure and blocked by custom filtering rule then GH should check whether these 3 things fulfilled or not. _(also may occur due maintainer's hosting down)_

I think might be suitable to notify administrator every time when login AGH about certain blocklists seems no longer possible to update so check maintainers website or repository for get a new URL or convert to a local block list

**Comment by ameshkov** [comment]
Well, it seems that this cannot be reproduced on v0.99, the way filters updates are checked is different there
