### ISSUE TITLE
ip-v6 client to exceptions

### ISSUE THREAD

**Issue by zm3ed** [AdguardTeam/AdGuardHome#1075]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.98.1-188-g4f99
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  *  ubuntu 18.04

### Screenshots

<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/38526267/66950420-863bee00-f082-11e9-9012-9bfc615580db.png)

![image](https://user-images.githubusercontent.com/38526267/66950500-b2576f00-f082-11e9-8e66-f825d8ca0b95.png)

</details>

### Additional Information

ipv6 address is specified in the top clients and it is filtered, but I cannot add it to exceptions and global filters are applied to it

**Comment by ArtemBaskal** [comment]
fixed in db703283ba4b2e6f32e73b69902cd611dd372fe7
