### ISSUE TITLE
Make searching for domain name in query log case-insensitive

### ISSUE THREAD

**Issue by apathyNot** [AdguardTeam/AdGuardHome#1076]
Currently, when filtering by domain name in query log, the search is case-sensitive. Any one capital letter will always produce no results found. On mobile devices, the first letter typed is auto capitalized and may not be clear to the user why no results are returned.

Solution: make search case-insensitive.

Thanks

**Comment by ameshkov** [comment]
Yup, thank you!

@apathyNot please upvote the existing issue: #680
