### ISSUE TITLE
AdGuard Home in the Entware repository

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1078]
Hello,

please prepare package for the Entware repository for easy installation in DD-WRT/OpenWRT/AsusWRT firmwares.

More information about this repo here (inc. Russian too):
https://github.com/Entware/Entware
http://bin.entware.net/Readme.txt

Some discussion about this feature in Keenetic community with useful commentaries:
https://forum.keenetic.net/topic/5474-adguard-home-для-entware-возможно/

Thank you.

**Comment by pizdec** [comment]
+ тоже жду

**Comment by aiden09** [comment]
You can test it. This build is for ARM routers. Bit it have some issues. Router use 53 port for own dnsmasq, so AdGuardHome must use not 53 port. If you will disable 53 port in router dnsmasq.conf then you must to set up wlan, lan manually
![Screenshot_2019-12-08-22-07-50-379_com sonelli juicessh](https://user-images.githubusercontent.com/15194348/70396164-676d2e80-1a17-11ea-9a80-fa21e21b5560.jpg)
![IMG_20191208_225759_518](https://user-images.githubusercontent.com/15194348/70396176-8b307480-1a17-11ea-8a62-ef277a56dab5.jpg)

You can download it here http://aiden.servebeer.com:81/explorer/index.php?share/file&user=102&sid=iFkfHCBT

**Comment by aiden09** [comment]
> 
As for used memory. My tenda ac18 have 256mb ram. See usage on a screenshot
![Screenshot_2019-12-09-00-14-18-299_com sonelli juicessh](https://user-images.githubusercontent.com/15194348/70396336-13634980-1a19-11ea-920e-0333b5a6b3c3.jpg)

**Comment by rufengsuixing** [comment]
there is a lot of ways to replace dnsmasq，you can see my luci project to copy some script to use.
mainly in /root/etc/init.d/AdGuardHome
https://github.com/rufengsuixing/luci-app-adguardhome

**Comment by dartraiden** [comment]
Adguard was added to http://bin.entware.net/mipselsf-k3.4/test/

**Comment by ameshkov** [comment]
Cool, thank you!

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1078

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/376
