### ISSUE TITLE
Language issue: it looks as "English" is selected even though the interface is in a different language

### ISSUE THREAD

**Issue by RonKhondji** [AdguardTeam/AdGuardHome#1082]
I just updated to v0.99.0.

Now the language on the dashboard and web interface is changed to dutch.
I am in Holland, so I can sorta understand why the language changed, but I prefer the interface to be english.
Can we please get a language selection setting or something.

Regards,

Ron

**Comment by ameshkov** [comment]
Language selector is in the footer

**Comment by RonKhondji** [comment]
Ah yes. English was selected, interface was dutch. Had to select a different language first, then went back to english. Everything good now.

Thanks.

**Comment by ameshkov** [comment]
Uh, got it, sounds like a bug actually

**Comment by IldarKamalov** [comment]
@RonKhondji Just for check, what is the output of the `window.navigator.language` in the browser console?

**Comment by RonKhondji** [comment]
"nl-NL"
