### ISSUE TITLE
Error: control/version.json | New app version check is disabled by user | 500

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#1083]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.0

### Expected Behavior

- Version check at login should work.
- Version check when pressing the bottom refresh button should work.

### Actual Behavior
- Got red popup message with the error:

   > Error: control/version.json | New app version check is disabled by user | 500

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/96476/67115736-c8764400-f1d6-11e9-9f9a-c6c602d9f735.png)

</details>

**Comment by ameshkov** [comment]
Docker?

**Comment by rfgamaral** [comment]
> 
> 
> Docker?

Yes, sorry, missed that info.

**Comment by frenck** [comment]
Yep, same issue here on the Hass.io Add-on

![image](https://user-images.githubusercontent.com/195327/67127449-ab9f3800-f1f9-11e9-90d0-49b49af4e8b1.png)

**Comment by ameshkov** [comment]
Yeah, we'll publish a hotfix next week for this. We'll see how it goes, maybe there will be more things to fix after the weekend.

**Comment by frenck** [comment]
Don't worry, I'm focussing on the API changes first (Home Assistant depends on the API), trying to get that processed before the beta cutoff upcoming Wednesday.

**Comment by craigmdennis** [comment]
Same problem here using in Docker on a Synology NAS.

**Comment by szolin** [comment]
Auto-update is disabled on Docker, so we should probably show the appropriate message and the link to https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#update

**Comment by ameshkov** [comment]
@szolin or simply suppress the message

**Comment by rfgamaral** [comment]
> 
> 
> Auto-update is disabled on Docker, so we should probably show the appropriate message and the link to https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#update

Yes, disable for Docker containers but still let users know that a new version is available.

**Comment by mithem** [comment]
> > Auto-update is disabled on Docker, so we should probably show the appropriate message and the link to https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#update
> 
> Yes, disable for Docker containers but still let users know that a new version is available.

Would also like that, however I keep getting `{"disabled": true}` for /control/version.json running version 107.3 in a Docker container. Am I missing something or doing something wrong entirely?

What I would have expected (roughly):
```json
{"disabled":false,"new_version":"v0.108.0-b.3","announcement":"AdGuard Home v0.108.0-b.3 is now available!","announcement_url":"https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.108.0-b.3","can_autoupdate":false}
```
