### ISSUE TITLE
The language tag isn't automatically changed to match the current language UI in the first launch.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#1087]
I tried v0.99.0 on Windows 10 Pro.
Thanks for your great work!

It's so thoughtful that AG Home can automatically detect Windows system language for itself language UI in the first launch.
But it forgets to also change the language tag to match the current language UI.
**In the first launch**, you can see it's Traditional Chinese UI, but the language tag is English.
Just a small bug.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/DOLogae.png)
</details><br/>

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1082#issuecomment-543829817

**Comment by ameshkov** [comment]
Dup of #1082
