### ISSUE TITLE
Can't update filter

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1088]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * `0.99.0`
* **How did you setup DNS configuration:**
  * `System`
* **Operating system and version:**
  * `Windows 8.1 x64`
  * `Windows 10 x64 1903`

### Steps

1. Click ![image](https://user-images.githubusercontent.com/5698157/67135035-373fb580-f248-11e9-932b-765a4951a6b4.png)

### Actual Behavior

The filter's rule count does not change and filter files seem like locked and AGH create `.tmp` file to save it.
I have to stop service and delete files then start service to update filters.
See screenshots.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5698157/67134987-c39da880-f247-11e9-9bcc-afb2e60bdc06.png)

</details>

**Comment by ArchiveBase** [comment]
I also experience this issue

**Comment by szolin** [comment]
How long did you wait for the update procedure to complete?
Please note that this procedure can be long because it downloads all your enabled filters and parses all their rules, so it may take several minutes to complete.  During the update DNS server works as usual - you don't have to restart the service or anything.

**Comment by szolin** [comment]
I see now that on Windows update procedure is broken - AGH can't rename files from .tmp to .txt because Windows has these file paths locked (they are being used until new files are ready).

**Comment by ArchiveBase** [comment]
@szolin that doesn't occur on v0.98.1

**Comment by szolin** [comment]
Yes, because for #928 I implemented a new algorithm for this whole thing.  The current problem is that it doesn't account for Windows specific behaviour.

**Comment by bestpika** [comment]
@szolin I am waiting for a long time.
The first filter only 1KB (17 rules).

**Comment by bestpika** [comment]
When I try to delete a filter from explorer, I will see this message.
It says the file is locked by AGH service.
![image](https://user-images.githubusercontent.com/5698157/67221097-7bf06a00-f45d-11e9-93a1-da5a8ab1d526.png)

**Comment by bestpika** [comment]
Here is the log.
```
2019/10/21 23:53:36 6912#278 [debug] github.com/AdguardTeam/AdGuardHome/home.customDialContext(): LookupIPAddr: zerodot1.gitlab.io: [{35.185.44.232 }]
2019/10/21 23:53:39 6912#14 [info] Filter 51 has been updated: 951859 bytes, 33534 rules
2019/10/21 23:53:39 6912#14 [debug] github.com/AdguardTeam/AdGuardHome/home.(*filter).update(): Downloading update for filter 52 from https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
2019/10/21 23:53:39 6912#14 [info] Filter 52 has been updated: 89807 bytes, 3303 rules
2019/10/21 23:53:39 6912#14 [info] Saving filter 2 contents to: C:\AdGuardHome\data\filters\2.txt
2019/10/21 23:53:39 6912#14 [info] Failed to save the updated filter 2: rename C:\AdGuardHome\data\filters\2.txt.tmp C:\AdGuardHome\data\filters\2.txt: Access is denied.
2019/10/21 23:53:39 6912#14 [info] Saving filter 19 contents to: C:\AdGuardHome\data\filters\19.txt
2019/10/21 23:53:39 6912#14 [info] Failed to save the updated filter 19: rename C:\AdGuardHome\data\filters\19.txt.tmp C:\AdGuardHome\data\filters\19.txt: Access is denied.
2019/10/21 23:53:39 6912#14 [info] Saving filter 20 contents to: C:\AdGuardHome\data\filters\20.txt
2019/10/21 23:53:39 6912#14 [info] Failed to save the updated filter 20: rename C:\AdGuardHome\data\filters\20.txt.tmp C:\AdGuardHome\data\filters\20.txt: Access is denied.
2019/10/21 23:53:39 6912#14 [info] Saving filter 51 contents to: C:\AdGuardHome\data\filters\51.txt
2019/10/21 23:53:39 6912#14 [info] Failed to save the updated filter 51: rename C:\AdGuardHome\data\filters\51.txt.tmp C:\AdGuardHome\data\filters\51.txt: Access is denied.
2019/10/21 23:53:39 6912#14 [info] Saving filter 52 contents to: C:\AdGuardHome\data\filters\52.txt
2019/10/21 23:53:39 6912#14 [info] Failed to save the updated filter 52: rename C:\AdGuardHome\data\filters\52.txt.tmp C:\AdGuardHome\data\filters\52.txt: Access is denied.
2019/10/21 23:53:39 6912#14 [debug] Filters: update finished
2019/10/21 23:53:54 6912#50 [info] Stopping AdGuard Home
2019/10/21 23:53:54 6912#50 [info] Stopping the DNS proxy server
2019/10/21 23:53:54 6912#13 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/10/21 23:53:54 6912#12 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2019/10/21 23:53:54 6912#50 [info] Stopped the DNS proxy server
2019/10/21 23:53:54 6912#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin...
2019/10/21 23:53:54 6912#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin
2019/10/21 23:53:54 6912#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).flushUnitToDB(): Flushing unit 436575
2019/10/21 23:53:54 6912#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).commitTxn(): tx.Commit
2019/10/21 23:53:54 6912#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).Close(): db.Close...
2019/10/21 23:53:54 6912#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).Close(): db.Close
2019/10/21 23:53:54 6912#50 [debug] Stats: closed
2019/10/21 23:53:54 6912#50 [debug] 10 elements serialized via json in 0s: 3 kB, 350.1/entry, 0s/entry
2019/10/21 23:53:54 6912#50 [debug] check ok: 10 entries
2019/10/21 23:53:54 6912#50 [debug] ok "C:\AdGuardHome\data\querylog.json": 3501 bytes written
2019/10/21 23:53:54 6912#50 [info] Stopped
```

**Comment by ameshkov** [comment]
Here's what I think -- start using in-memory filter lists on Windows, and keep file-based filter lists on macOS and Linux only.

**Comment by ArchiveBase** [comment]
@bestpika
> I am waiting for a long time.

You dont have to wait such time. Don't you see that "All filters are already up-to-date" notification?

(And as you said if stop service and delete all files then start service again helps to update them)

**Comment by bestpika** [comment]
@ArchiveBase I've to post AGH's log.

**Comment by ArchiveBase** [comment]
@bestpika Yup

https://github.com/AdguardTeam/AdGuardHome/issues/1088#issuecomment-544486819
> Yes, because for #928 I implemented a new algorithm for this whole thing. The current problem is that it doesn't account for Windows specific behaviour.
