### ISSUE TITLE
Custom CSS features

### ISSUE THREAD

**Issue by bpplpp** [AdguardTeam/AdGuardHome#1089]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I want to add custom CSS features, sometimes I want to see more information.

**Comment by ameshkov** [comment]
Do you mean custom CSS for the dashboard? What exactly would you like to change?

**Comment by bpplpp** [comment]
1. For example, the content displayed when accessing the mobile terminal is not complete.
2. I want to display more columns of logs when browsing the PC.
3. Thank you for your reply, maybe I can use the Chrome extension on my computer.

**Comment by ameshkov** [comment]
Well, you can use stylish or something like that.

On the other hand, if you think that there's something that can be useful to everyone, you can pull request this change to us. It'd be better to create an issue first and outline what exactly you'd like to change, though.
