### ISSUE TITLE
edns-client-subnet (ECS) support

### ISSUE THREAD

**Issue by FenghenHome** [AdguardTeam/AdGuardHome#1091]
AdGuardHome is a great dns, I really like it.
But I have a problem, I use my vps to create a public dns, AdGuardHome's edns-client-subnet has a problem, AdGuardHome will pass the vps ip address subnet to the upstream resolution, instead of passing my home ip address subnet to the upstream Parsing, so the ip parsed out is very far away from me.

**Comment by FenghenHome** [comment]
Of course, there is another problem. When AdGuardHome starts dns cache, ecs does not work.

**Comment by ameshkov** [comment]
Yeah, there are basically two different issues:
1. Set ECS extension to the client IP address
2. Handle ECS in the response and use it as a cache key

Both can be solved, of course.

**Comment by FenghenHome** [comment]
Thank you very much, I really look forward to it.

**Comment by AngelFalse** [comment]
I suggest adding a switch to let user choose whether to opt-in this feature. There are certain privacy-focusing users that dislike the idea of ECS

**Comment by ameshkov** [comment]
Sure, it will be disabled by default.
