### ISSUE TITLE
Sign out button shown, even when not using AdGuard Home Authentication

### ISSUE THREAD

**Issue by frenck** [AdguardTeam/AdGuardHome#1093]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.0
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Hass.io/Home Assistant
* **Operating system and version:**
  * HassOS

### Expected Behavior

Since I've disabled authentication (or better said, not enabled it), I did not expect to  see a "Sign out" button.

![image](https://user-images.githubusercontent.com/195327/67144079-f610cb00-f272-11e9-8f6d-75cb93bd1bcb.png)

### Actual Behavior

Well, the button shows, I can click it, which brings me to a Login page, where I can log in with non-existing credentials? So I can't log in either.

### Additional Information

Of course, I do use authentication, but not the one provided by AdGuard Home, instead, I use a n SSO.

**Comment by alexsannikov** [comment]
In addition, I'd say that showing version on the "Sign in (Out)" place was very useful. Can you return this small object back? Thanks.

**Comment by ArchiveBase** [comment]
@alexsannikov It had moved to footer however i prefer see it modify back as old version single line footer instead 2x
