### ISSUE TITLE
Query log pages load bug

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#1094]
#### Query log bug (1)

Open query log page and go to next pages one by one. 1>2>3>4>5>6>7>8>9 and on 9th pages (9 of 10), change rows amount from 50 to 100. You'll see as reached the query log end(5 of 5) means next button will be grayed out.

#### Query log bug (2)

I also experience another problem mostly within this release but not intend to open separate issue because difficult to provide sufficient details to reproduce. Just i cannot see few sub domains queries even viewed manually till end one by one; end at 02:16:25 row last page

But i can see that subdomains on "Top queried domains" and **come to** 'Domain Name' search result(ok)*, time range from 00:07:10 to 00:06:18/ 23:57:59 that unable reach through default view(bug) 

**[Edit:] Query log bug (2)**
I think this occur due something similar **Query log bug (1)** even without change rows and  i was able to load old query pages than to above mentioned time. https://github.com/AdguardTeam/AdGuardHome/issues/1095 might be partial fix but i keep this opened due above(1) because it can be happen even implemented https://github.com/AdguardTeam/AdGuardHome/issues/1095

AdGuard Home v0.99 | Windows 10

**Comment by szolin** [comment]
> Query log bug (1)

We'll try to reproduce it.

> Query log bug (2)

To help us identify the bug you can search for your target query in JSON response to `GET /querylog` request from UI using browser developer tools.
If you find it there, but you can't find it in UI - it's a UI bug.
If you can't find it in JSON response, then you should try to find it in querylog.json file.

**Comment by ArchiveBase** [comment]
> Query log bug (2)

That data stored in querylog then kind of UI bug. See screenshots on https://github.com/AdguardTeam/AdGuardHome/issues/1099 at the moment write this issue(1094) i couldn't reach to view 23:57:59 by default view that showed for search result because last page showed as 02:16:25 around time row with grayed out next button
_(23:57:59 is the past)_

However later i could loaded past pages 21.55.28 and more than it(2nd screenshot) but that queries didn't show for search result (even refresh and searched again, again) so i opened separate issue for it https://github.com/AdguardTeam/AdGuardHome/issues/1099

Read this issue conversation too you can be have good idea to do something better for not happen this problem again https://github.com/AdguardTeam/AdGuardHome/issues/1095

**Comment by ArchiveBase** [comment]
> If you find it there, but you can't find it in UI - it's a UI bug.

Well, i dont know how to find for specific time using developer tools but i saw tool result: 92 queries and UI result: 15 for that domain. maybe querylog file contain more than it? Lol just didnt try yet
