### ISSUE TITLE
Display total number of queries for search result

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#1095]
#### Expected Behavior
Total number of pages must be displayed by default also all available pages amount necessary to display for sort results without delay load

#### Actual Behavior
Begin shows 10 pages for 50 rows or 5 pages for 100 rows then continue as per 5 pages. When sort under domain or client that has less queries then shows per 2 pages or 1 page. Just quite misleading but actually it can be affect for low end devices somehow

#### Additional Information
As i remember that didn't exist on 0.98.1 stable release.

#### Screenshots

![Screenshot_5](https://user-images.githubusercontent.com/46082456/67152550-da550580-f302-11e9-8f91-0d171fa08973.png)

![Screenshot_13](https://user-images.githubusercontent.com/46082456/67152553-dde88c80-f302-11e9-9611-ac662205c6f7.png)

AdGuard Home v0.99 | Windows

**Comment by ArchiveBase** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/46082456/67165684-535f6600-f3b2-11e9-9573-e04c96691c50.png)

1. Total number of pages must be displayed (Req.)
2. Query log retention able set 90days regardless query amount so that's huge if we can enter random page number and jump to it might be better
_(Screenshot source: AGHome v0.99 Filters panel so you can be add the same here with [1.] enhancement)_

**Comment by ameshkov** [comment]
> Total number of pages must be displayed (Req.)

Not that we don't limit the query log size, calculating the total number is problematic

**Comment by ArchiveBase** [comment]
> calculating the total number is problematic

I think it's not difficult because has specific rows amount per page ex: 50, 100 etc then possible divide total queries by selected rows amount and display it. When user change rows amount then possible perform fresh recalculation and display total number of pages

Any chance for have milestone to this too? https://github.com/AdguardTeam/AdGuardHome/issues/624 (date for query log)

**Comment by ameshkov** [comment]
I mean if the log file is huge, calculating the total number of pages takes too much time.

#624 looks simple, assigned to v0.101 for now.

**Comment by ArchiveBase** [comment]
> I mean if the log file is huge, calculating the total number of pages takes too much time.

Yes.

> #624 looks simple, assigned to v0.101 for now.

If so this request isn't important but when sort query log under domain, client etc and view too past date history on hundred or thousand number pages set then i doubt that issue can be occur again https://github.com/AdguardTeam/AdGuardHome/issues/1094 just not because of change rows as mentioned on it but somehow querylog pages may stop load at some point with grayed out next button then user think that no more history for specific domain or client for example.

**Comment by szolin** [comment]
* We can show the total number of pages, but we need to parse the whole log file which can take minutes of time at startup.  I don't think it's *that* necessary.
* Quickly jumping to a particular number of page can be replaced by jumping to a certain time or a time range (#481)

**Comment by ArchiveBase** [comment]
>We can show the total number of pages, but we need to parse the whole log file which can take minutes of time at startup. I don't think it's that necessary.

I see on enterprise solutions either it take time or consume too resource to generate quick but we must accomplish this goal somehow

Well, the reason for request this not especially for jump to certain page easily but to ensure how many pages queries exactly have when sort under specific entity, time range etc. just that is one of most important thing we expect from such software rather than block what we already know or see some top queried domains then basically it will not mislead https://github.com/AdguardTeam/AdGuardHome/issues/1094 https://github.com/AdguardTeam/AdGuardHome/issues/1099 user so far even accidentally occur application or system issue
Or if you may consider implement something like '1500 queries found' on top corner or as notification for search result it might reasonable because user able realize all queries contain within 15 pages(100 rows) for example

> Quickly jumping to a particular number of page can be replaced by jumping to a certain time or a time range (#481)

It may acceptable.

**Comment by ArchiveBase** [comment]
@szolin I changed the topic to make this easy. adguard home has request count feature then use it here for fulfill this requirement. currently users blindly think certain page is the end of search result when no longer possible to click 'next' button. 

- For specific domain search result ex: mail.protonmail.com then easy to show notification '1500 queries found'. (nothing to do)
- For root domain search result ex: google then display total belong to that domain
- For specific domain search result under specific client. (feature already exist then only small task)

https://github.com/AdguardTeam/AdGuardHome/issues/1164 (related task)

This feature not necessary if consider filter log data under time or date range enough https://github.com/AdguardTeam/AdGuardHome/issues/481 but i think it limits what we can do with adguard home log analysis.
