### ISSUE TITLE
Add a "Block client" button to the Query Log

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1097]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

When going to the Query Log (which I often do), I often see the `Block` button right next to the client IP, and I often have to remember that the button instead blocks the domain name much further to the left.

This has inspired me to think: Why not add a `Block Client` button there as well, which automatically adds the client IP to *DNS Settings* → *Disallowed Clients*?

As seen in the screenshot below, it would have saved me a bit of time to simply block highly questionable clients like these directly from the logger, instead of marking and copying the IPs and manually pasting them into *Disallowed Clients*.

![image](https://user-images.githubusercontent.com/22780683/67153196-1a0cf480-f2e5-11e9-9616-3ff9209820a1.png)

### Proposed Solution

Described in *Problem Description* above.

### Alternatives Considered

None that are realistic. Especially if we exclude dramatic things like adding an option to disallow all PR-Chinese IPs by default, which probably isn't even relevant to this feature request.

### Additional Information

May or may not cause conflicts (or simply require some extra adaption work) with #1032, should that one ever become implemented.

**Comment by ArchiveBase** [comment]
Similar request here https://github.com/AdguardTeam/AdGuardHome/issues/896 however not for query log page

**Comment by Grergo** [comment]
I have also received a large number of DNS requests for " pizzaseo.com" recently. Is there any better way to solve this problem once and for all, except for the ban on clients?

**Comment by ameshkov** [comment]
@Grergo add it to the "blocked domains" in the DNS settings section

**Comment by Grergo** [comment]
> add it to the "blocked domains" in the DNS settings section
Thank you

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2050
