### ISSUE TITLE
Error | Couldn't start forwarding DNS server, cause: could not reconfigure the server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: Only one usage of each socket address | 400

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#1098]
При сохранении настроек выдает ошибку а настройки не сохраняет но после повторного нажатия на кнопку "Сохранить" настройки сохраняются а ошибка не появляется. До этого на версии 0.98.1 такого не наблюдалось.
При этом на машине с Windows Server 2012 R2 такой ошибки не наблюдается.

### Issue Details

* **Version of AdGuard Home server:**
  * 0.99.0
* **Operating system and version:**
  * Windows 10 Pro (Registered Trademark) build 1607

### Screenshots

<details><summary>Screenshot:</summary>

![400](https://user-images.githubusercontent.com/46345396/67154033-3157dc00-f2fd-11e9-98fd-44a7e4538829.png)
</details>

**Comment by ArchiveBase** [comment]
Run netstat -abno / netstat -na | findstr "53" / netstat -n | findstr "53"  and see. You can be solve it

**Comment by ArchiveBase** [comment]
Probably it already used by another application. Here another one like you https://community.home-assistant.io/t/community-hass-io-add-on-adguard-home/90684/104

**Comment by Eyeborgs** [comment]
Я заметил эта ошибка у меня проявляется когда AdGuard Home работает через Службы а если напрямую запустить AdGuardHome.exe или через cmd то все работает. И я повторяюсь такой проблемы у меня не было когда были версии прошлые до 0.99.0.

**Comment by ArchiveBase** [comment]
It's strange. How about if you reinstall AGHome?

- sc stop AdGuardHome
AdGuardHome -s uninstall (navigate folder before run)

- Maybe you can download and replace AdGuardHome.exe https://github.com/AdguardTeam/AdGuardHome/releases

- Check any wrong with bind host/port in .yaml file
(you don't need delete .yaml as long as it correct or data folder)

- Run AdGuardHome.exe -s install and see if it solved

If not maybe @ameshkov or other will help ;)

**Comment by szolin** [comment]
Т.е. итого:
* На Windows 10 Pro это воспроизводится, а на Windows Server 2012 R2 - нет.
* если запущено через службу, то воспроизводится, а если не через службу - нет.
Выглядит очень странно, без логов не смогу что-то подсказать. Соберите пожалуйста verbose логи?

**Comment by Eyeborgs** [comment]
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/3750154/log.txt)

**Comment by szolin** [comment]
```
2019/10/20 06:16:48 [info] Creating the UDP server socket
2019/10/20 06:16:48 [info] Listening to udp://[::]:53
...
2019/10/20 06:17:00 [info] Stopped the DNS proxy server
...
2019/10/20 06:17:00 [info] Creating the UDP server socket
2019/10/20 06:17:00 [info] Couldn't start forwarding DNS server, cause: could not reconfigure the server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
...
2019/10/20 06:17:02 [info] Stopping the DNS proxy server
2019/10/20 06:17:02 [info] The DNS proxy server is not started
...
2019/10/20 06:17:02 [info] Creating the UDP server socket
2019/10/20 06:17:02 [info] Listening to udp://[::]:53
```

Очевидно что 53 порт не занят другим приложением, а занят именно AGH.
На этой версии Windows скорее всего срабатывает какой-то отложенный вариант закрытия сокета.  Т.е. сокет мы закрываем, и стараемся открыть новый, но он на самом деле ещё не закрыт - отсюда и ошибка.

**Comment by Eyeborgs** [comment]
Это странно потому что до этой версии 0.99 я не чего из этого не наблюдал.. Что посоветуете?

**Comment by ameshkov** [comment]
@szolin может просто delay небольшой добавим?

**Comment by szolin** [comment]
> до этой версии 0.99 я не чего из этого не наблюдал

сейчас здесь работает новый алгоритм, чуть сложнее, чем предыдущий.

да наверное для windows поставим задержку, попробуем

**Comment by szolin** [comment]
0579e9bf9975cfafd753bd1d717fb4e5ba53176f
