### ISSUE TITLE
Dynamic DNS host names for Allowed Clients options

### ISSUE THREAD

**Issue by jupiter09** [AdguardTeam/AdGuardHome#1100]
### Problem Description

Enhancement Request: "Allowed Clients" option in the DNS settings page where in only IP addresses are allowed.  As most of the consumers are in dynamic IP being issued by ISP so it is not possible to give a static IP address there where AdGuard Home is being running in a home network and a user outside the home network wants to use their AdGuard Home.

### Proposed Solution

Feature Suggestion/Request: Along with the IP address, it is recommended to accept a Dynamic DNS (DDNS) host name in the Allow Clients feature section for the changing IP at the consumer end.  When a client sends dns query from outside the AdGuard Home's network, a check can be performed in real-time where in the client's IP which is sending the dns query and IP look up of the DDNS host name provided in the Allowed Clients section.  Upon match AdGuard Home processes the request and drops it otherwise.

**Comment by ArchiveBase** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/835

**Comment by ameshkov** [comment]
Yep, closed as dup of #835.

Please upvote the original feature request.
