### ISSUE TITLE
Error: control/version.json | | 533

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#1104]
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: couldn't lookup host: static.adguard.com | 502

![KVRYK5H%N@PSHD7D@%L8_MJ](https://user-images.githubusercontent.com/17548936/67203882-d3331200-f43e-11e9-9fc5-2c26d0b43af7.png)

**Comment by thb007** [comment]
@ameshkov

**Comment by ameshkov** [comment]
Can you reproduce it after restarting AGH?

If so, we will need the "verbose"-level log

**Comment by thb007** [comment]
> Can you reproduce it after restarting AGH?
> 
> If so, we will need the "verbose"-level log

Reboot still can't solve the problem

**Comment by ameshkov** [comment]
This is not a log

**Comment by ameshkov** [comment]
1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by thb007** [comment]
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/3750782/log.txt)
log here

**Comment by ameshkov** [comment]
@thb007 removed the log from the comment. Please be more careful next time, your certificate is printed to the log

**Comment by thb007** [comment]
ok

**Comment by ameshkov** [comment]
What do you have there? It seems that this DNS server is not working
`Upstream 0: 127.0.0.1:5356`

**Comment by thb007** [comment]
Thank you very much, I found that my port 5356 was wrong. Correct for 5354

**Comment by thb007** [comment]
I still have a question: I open the address of DOH to display Bad Request. @ameshkov

**Comment by ameshkov** [comment]
Because you've not sent any DNS request I reckon

**Comment by thb007** [comment]
I saw the public doh on google open to show like this`{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"ultraedit.com.","type":1}],"Answer":[{"name":"ultraedit.com.","type":1,"TTL":1589,"Expires":"Mon, 21 Oct 2019 13:18:17 UTC","data":"169.48.65.137"}],"edns_client_subnet":"113.90.237.0/0"}`

**Comment by ameshkov** [comment]
No idea

**Comment by thb007** [comment]
https://rubyfish.cn/dns-query?name=www.google.com
`{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"www.google.com.","type":1}],"Answer":[{"name":"www.google.com.","type":1,"TTL":18,"Expires":"Mon, 21 Oct 2019 12:58:47 UTC","data":"172.217.24.68"}]}`

I use the DOH built by adguard home to open the display "Bad Request"

**Comment by ameshkov** [comment]
This is not a valid DNS request

**Comment by ameshkov** [comment]
https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure/

**Comment by thb007** [comment]
Can adguard home support this UDP wireformat and JSON format? Maybe future versions will add this feature?

**Comment by ameshkov** [comment]
AGH supports UDP wireformat.
We're not going to support JSON though.

**Comment by thb007** [comment]
Why not going to support JSON though.I feel this feature is very good. Can you open the function that supports json by selecting in future versions?

**Comment by ameshkov** [comment]
I don't see why would anyone use it, there is no DNS-over-JSON protocol.

**Comment by ameshkov** [comment]
No, it supports DNS-over-HTTPS

**Comment by thb007** [comment]
| -- SecondDoH : https://xxx.com:443/dns-query
| -- Startup SecondDns : 10.10.10.109
| 2019/10/21 21:25:10 127.0.0.1 : array701.prod.do.dsp.mp.microsoft.com. | A
| -- SecondDoH : https://xxx.com:443/dns-query
| -- Startup SecondDns : 10.10.10.109
| 2019/10/21 21:25:15 127.0.0.1 : www.baidu.com. | A
| - Catch WebException : 400 BadRequest | www.baidu.com. | https://xxx.com:4433/dns-query?ct=application/dns-json&name=www.baidu.com.&type=A&edns_client_subnet=39.108.247.120

not going to support JSON though

**Comment by ameshkov** [comment]
Again, this is not a valid DNS-over-HTTPS query

**Comment by thb007** [comment]
2019/10/21 21:35:43 127.0.0.1 : weibo.com. | A
| 2019/10/21 21:35:43 127.0.0.1 : weibo.com. | A
| 2019/10/21 21:35:45 127.0.0.1 : passport.weibo.com. | A
| 2019/10/21 21:35:45 127.0.0.1 : passport.weibo.com. | A
| 2019/10/21 21:35:50 127.0.0.1 : array701.prod.do.dsp.mp.microsoft.com. | A
| 2019/10/21 21:35:50 127.0.0.1 : array701.prod.do.dsp.mp.microsoft.com. | A
| 2019/10/21 21:35:51 127.0.0.1 : array701.prod.do.dsp.mp.microsoft.com. | A
| 2019/10/21 21:35:51 127.0.0.1 : login.sina.com.cn. | A
| 2019/10/21 21:35:51 127.0.0.1 : login.sina.com.cn. | A
| 2019/10/21 21:35:52 127.0.0.1 : img.t.sinajs.cn. | A
| 2019/10/21 21:35:52 127.0.0.1 : img.t.sinajs.cn. | A
| 2019/10/21 21:35:52 127.0.0.1 : js.t.sinajs.cn. | A
| 2019/10/21 21:35:52 127.0.0.1 : js.t.sinajs.cn. | A
| 2019/10/21 21:35:53 127.0.0.1 : img.t.sinajs.cn. | A


Support dns json log display like this, you can take the time to test the function of this software to understand why I hope you can support DNs json

**Comment by SamZig** [comment]
i got the same trouble
