### ISSUE TITLE
The UI cannot handle the situation when the user has been logged out

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1105]
## Steps to reproduce

1. Log in to AGH web admin interface
2. Clear the browser cookies
3. Try to do anything in the interface (go to settings or refresh it or whatever)

## Expected result

Redirect to the login page

## Actual result

An error alert

**Comment by szolin** [comment]
our tech doc says:
> All requests without a proper Cookie get redirected to Log-In page with prompt for name and password.

UI should handle this situation

**Comment by ameshkov** [comment]
@szolin even API requests? Wouldn't it make sense to return 403 for API requests?
