### ISSUE TITLE
Failed to save the updated filter

### ISSUE THREAD

**Issue by shenzt68** [AdguardTeam/AdGuardHome#1113]
2019/10/23 21:58:38 [info] Filters update procedure is already running
2019/10/23 21:59:04 [info] Filter 1 has been updated: 602513 bytes, 31324 rules
2019/10/23 21:59:04 [info] Failed to save the updated filter 1: rename /usr/bin/data/filters/1.txt /usr/bin/data/filters/1.txt.old: no such file or directory

**Comment by szolin** [comment]
dup: #1112
