### ISSUE TITLE
Don't use Cloudflare by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1116]
Cloudflare DOH might be problematic because of the EDNS padding extension they add.

See https://github.com/AdguardTeam/AdGuardHome/issues/1110#issuecomment-545871645 for instance. Also, I suppose that #1109 was also caused by the very same thing.

Let's change it to Quad9 instead: `https://dns.quad9.net/dns-query`

Also, don't forget to change the text and examples:  https://uploads.adguard.com/up04_1kfna_AdGuard_Home.png

### Q&A

* **Q: Why not Cloudflare DoT?**
* A: DoH is less likely to be blocked on the ISP level.

* **Q: Why not Google DNS?**
* A: While I have nothing against it, people tend to hate everything made by Google

* **Q: Why not AdGuard DNS?**
* A: AdGuard DNS blocks ad trackers by itself. AdGuard Home users should decide what to block by themselves, they don't need a resolver to do it for them. Also, we don't have as many servers as Quad/Google/Cloudflare do so routing might be worse.

* **Q: Why not any other resolver?**
* A: Other public resolvers are considerably smaller than Cloudflare.

**Comment by ZExplore** [comment]
Why such despite for AdGuard DNS? If it not acceptable state, you should enhance it and add to home as default. We're looking for it. :)
_(Anyone can change it so why we must promote another company?)_

> Quad9 was founded in 2017 by a coalition that includes IBM and the Global Cyber Alliance, a nonprofit organization launched by groups including the New York County District Attorney’s Office and the City of London Police.

**Comment by ameshkov** [comment]
Well, we can consider using AdGuard DNS by default in one ane only case -- if we add an endpoint that does no ad & tracking filtering. But it kinda defeats the purpose, the idea of AdGuard DNS is to block this stuff:)

**Comment by ibksturm** [comment]
spasiba siem ot agh 0.99.1 :)

**Comment by ANDOSX** [comment]
**AdGuard Default**
x.x.x.x
x.x.x.x

**AdGuard Secure**
176.103.130.130
176.103.130.131

**AdGuard Family Protection**
176.103.130.132
176.103.130.134

_**Yandex DNS:** Basic, Safe, Family
**CleanBrowsing:** Family Filter, Adult Filter, Security Filter
**Neustar Recursive DNS:** Reliability & Performance 1, Reliability & Performance 2*, Threat Protection, Family Secure, Business Secure_

Good idea?

**Comment by ZExplore** [comment]
Oops. sorry I saw that Q&A now

**Comment by Cloud-O** [comment]
@ZExplore @ANDOSX :D

**Comment by gurgunday** [comment]
Just wanted to add that Quad is a great choice in my opinion. Non-profits (don’t really care if one of the founders is a government organization) are great as defaults when we are talking about critical web services such as DNS 🚀

**Comment by hoshsadiq** [comment]
Just an FYI, very happy with the new choice

> AdGuard Home users should decide what to block by themselves, they don't need a resolver to do it for them

Just for completeness, Quad9 also blocks entries, specifically it blocks malicious domains.

**Comment by hoshsadiq** [comment]
Very happy with the new choice

> AdGuard Home users should decide what to block by themselves, they don't need a resolver to do it for them

Just an FYI, just for completeness, Quad9 also blocks entries, specifically it blocks malicious domains.
