### ISSUE TITLE
pixelserv-tls as blocking address

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1121]
Hello,

I suggest to use optionally pixelserv-tls as the blocking address instead of 0.0.0.0 or NXDOMAIN. What is pixelserv-tls? This is a small web server that returns a transparent image with a 1x1 pixel resolution when accessing a domain from a blocklist (inc. ALL urls contained this domain like https://domainblocked.com/blablabla123/). More information here:
https://kazoo.ga/pixelserv-tls/
https://github.com/jackyaz/pixelserv-tls
https://www.snbforums.com/threads/pixelserv-a-better-one-pixel-webserver-for-adblock.26114/

This solves the problem of broken pictures and frames. Also this will require generating a self-signed CA certificate and manually adding it to the keychains on user devices and mark it as trusted. For this, it is obvious that an appropriate web-interface...

P.S.: I am not sure that his license allows this, but I assume that something like this can also be realized using a lighttpd web server.

Feel free to ask me if you have any questions!

Thank you.

**Comment by Eyeborgs** [comment]
I think this is superfluous, at the moment I like everything

**Comment by imTHAI** [comment]
Hello, 

You can already do that using host syntax. But it won't include the subdomains of the domains.
In fact, it's precisely the reason I requested the option to be able to choose the ip cible for domains AND subdomains: https://github.com/AdguardTeam/AdGuardHome/issues/663

( I'm a fan of pixelserv-tls, I created a docker version that has a some success: https://hub.docker.com/r/imthai/pixelserv-tls )

I'm happy if your request convince the developers more than mine 👍

**Comment by YBS-PC** [comment]
can anyone suggest (step by step) how to set the pixelserv-tls next to the AGH on raspberry pi, please

**Comment by swetoast** [comment]
the kvic repo is the correct repo for pixelserv since the other one is just a clone.

**Comment by szolin** [comment]
When we will implement #1228 - http proxy - will this feature request have a reason?

Also, currently you can start your own http server and set its IP in "Custom IP" setting in DNS configuration section of AGH.

**Comment by ammnt** [comment]
> When we will implement #1228 - http proxy - will this feature request have a reason?
> 
> Also, currently you can start your own http server and set its IP in "Custom IP" setting in DNS configuration section of AGH.

I know. And that 's what I did. It would be more convenient to have this functionality here, but it is up to you.

**Comment by valaria247** [comment]
I don't quite understand what's going here. Does that feature request means to integrate pixelserv-tls to adguardhome? if then i do not recommend.

**Comment by ameshkov** [comment]
Tbh, I don't like the idea either.

This would require AGH to listen to ports 80/443 and make the logic of the HTTP server part quite complicated.

Instead of this, we could add information about pixelsrv to Wiki and explain how to use it with AGH.

**Comment by imTHAI** [comment]
It's a good idea. 
Fo me, since you added the feature "Custom IP" setting in DNS configuration, I send everything to my pixelserv docker container IP, so I'm satisfied.

**Comment by ammnt** [comment]
> Tbh, I don't like the idea either.
> 
> This would require AGH to listen to ports 80/443 and make the logic of the HTTP server part quite complicated.
> 
> Instead of this, we could add information about pixelsrv to Wiki and explain how to use it with AGH.

I'm okay with it too🙆‍♂️

**Comment by szolin** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ
