### ISSUE TITLE
Blocked Services - not working for Whatsapp/Facebook/Youtube etc. apps

### ISSUE THREAD

**Issue by almostserious** [AdguardTeam/AdGuardHome#1122]
Problem/Motivation
When i block the services of Facebook, Whatsapp, Instagram, Youtube the apps on Android Phone still work fine.
The Websites are blocked, but the apps somehow circumvent this.

Expected behavior
If i block Netflix, the Netflix App does not work anymore. I would expect the same also for the other apps. Is there a way to make this work? Do i need to enable a specific setting for them?

**Comment by ArchiveBase** [comment]
Just i don't use these apps on mobile. If that issue able reproduce as well, we might need to consider block all domains belong to specific service (not only for above mentioned) and see discussion about epic games https://github.com/AdguardTeam/AdGuardHome/pull/1044#issuecomment-538443634 between @ArchiveBase @onedr0p

@IldarKamalov had did this one time for Tiktok https://github.com/AdguardTeam/AdGuardHome/commit/c847df99767efd7c39fe7a0d7c23420cd495d7a5 according to community request however it also contain domains that not specially essential(or may used) for tiktok but related to company

> @almostserious
Do i need to enable a specific setting for them?

No

**Comment by ArchiveBase** [comment]
Tested facebook. the situation different than i thought; why i comment above 🤔

**Comment by ameshkov** [comment]
@szolin please check this on some Android mobile. I suspect that these apps might be switching to some fallback DNS when they encounter an NXDOMAIN response. Maybe we should switch `blocking_mode` default value to `null_ip` if so.

**Comment by Snapy** [comment]
@ameshkov Indeed they use Google DNS (8.8.8.8 and 8.8.4.4) as fallback. Can comfirm seeing some udp requests in AG for Android log.

**Comment by szolin** [comment]
youtube app uses `youtubei.googleapis.com`.  If we block it, the app stops working.

**Comment by Bhooty** [comment]
> 
> 
>     * youtube app uses `youtubei.googleapis.com`.  If we block it, the app stops working.
> 
>     * whatsapp uses a sophisticated algorithm and it evades blocking anyway.
> 
>     * instagram and facebook are blocked correctly.

sorry for replying but shouldnt the youtube also be blocked on the mobile by blocking the domain u said if we turn on youtube blocking? Also the facebook also works on android now even when it is on :(
