### ISSUE TITLE
Enhancements to Filters on Query Log page

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#1125]
### Problem Description
The current filters on the Query Log page are quite limited. I would like to request some additional enhancements making it easier to find specific log entries.
For example, on the Dashboard I might see some entries on the Blocked Adult websites graph for the night before. Currently there is no easy way in the UI to either show just entries filtered by the Parental Control web service.

### Proposed Solution
1. The **Response** column filter currently only has "Show All" or "Show Filtered"
It would be helpful if the "Show Filtered" could be split out, or added to, to allow specific searches by filter method, e.g. "Show Filtered by Blacklist" and "Show Filtered by Parental" and whatever other methods are possible.

2. The **Time** column currently has no filters. It would be helpful if you could at least filter down to the hour block of entries. Ideally you could choose a 'start date/time' and 'end date/time' to filter the Query Log.

3. The **Rows** filter at the bottom of the table always defaults back to 50. It would be preferred if it remembered my preference, or let me set a default. I always change it to 100 so it is one more thing I have to do every time I'm using the Query page; I have to scroll to bottom of the page, then change the Rows filter from 50 to 100,

4. The **Previous** and **Next** buttons ONLY exist on the bottom of the table. It would be helpful if these (and the possibly Rows filter) could be duplicated on the TOP of the table.

### Alternatives Considered
To achieve the above currently involves exporting the query log and using 3rd party tools, or, lots of clicking, scrolling and Finding on page searches.

### Additional Information
Am currently using AGH v0.99.2 on Windows

**Comment by ArchiveBase** [comment]
1. Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911 https://github.com/AdguardTeam/AdGuardHome/issues/755 https://github.com/AdguardTeam/AdGuardHome/issues/993
2. Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-515673586
3. Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/802 https://github.com/AdguardTeam/AdGuardHome/issues/845 https://github.com/AdguardTeam/AdGuardHome/issues/855
4. Yes i like it with https://github.com/AdguardTeam/AdGuardHome/issues/1095#issuecomment-544289840

**Comment by ameshkov** [comment]
Closed as dup
