### ISSUE TITLE
[feature request] Hide local MTR lookup in Top Board

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1126]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Problem Description

As shown in the figure below, **Top queried domains** section include many local host **MTR** record, I suppose it meaningless, and even covers real useful information. 

### Proposed Solution

So I want request a switch in setting to switch on/off those local **MTR** has been recorded in **top domains section**

### Additional Information

> ![image](https://user-images.githubusercontent.com/22477230/67621129-0101c780-f840-11e9-8b71-6631ce4b573c.png)
> ![image](https://user-images.githubusercontent.com/22477230/67621376-f5170500-f841-11e9-96dc-f5608e0de405.png)
>

**Comment by ameshkov** [comment]
Huh, I wonder why you have SO MANY requests like these? Could it be a software bug?

**Comment by Mosney** [comment]
> Huh, I wonder why you have SO MANY requests like these? Could it be a software bug?

I am not sure, maybe it is due to my local network is too complex. I deploy a transparent proxy and three DNS queries (include AdGuardHome) on my gateway which caused by the China gov policy of Internet.

**Comment by baujahr** [comment]
Filtering out these requests would be nice.
I'm also getting a lot of PTR requests from Firefox with DoH enabled which fills the logs up.

**Comment by ameshkov** [comment]
@baujahr upvote this issue them, we take the number of upvotes into account when we're planning releases

**Comment by ArchiveBase** [comment]
> @Mosney a switch in setting to switch on/off those local MTR has been recorded in top domains section

> @baujahr Filtering out these requests would be nice. > https://github.com/AdguardTeam/AdGuardHome/issues/946 > https://github.com/AdguardTeam/AdGuardHome/issues/481

**Comment by Mosney** [comment]
I found the reason, it caused by the LAN host want to query rDNS via PTR and cannot be reply correctly so it will repeatly query DNS. Note that I run AGH at my OpenWrt router and take over all queries.
Related information: https://github.com/AdguardTeam/AdGuardHome/issues/1260

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2704

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/2704
