### ISSUE TITLE
What are these random ARP Clients in Client List?

### ISSUE THREAD

**Issue by imadockerman** [AdguardTeam/AdGuardHome#1129]
I am running AdGuard Home through docker in a local network and only internal clients have access to the node running AdGuard Home. However, I have noticed that there are several random ARP clients in the client list. What are these?

![Snapshot](https://i.imgur.com/nAbNfn0.png)

**Comment by szolin** [comment]
Are they really random?  These clients are taken from the output of command `arp -a`.  We should probably add a description for ARP and other runtime clients in our wiki.
