### ISSUE TITLE
Client-specific Filter Options

### ISSUE THREAD

**Issue by marcobarriosfi** [AdguardTeam/AdGuardHome#1130]
Thank  you so much for all the hard work  you have put into AdGuard Home!

Currently  it's possible to block specific services in the client settings, but I would like to see the ability for the user to choose **which filters are enabled on a per-client basis**.

This could implemented as a separate tab in the client settings page.  The default option should be to use the global filter settings, but it would be great to be able to choose which filters are enabled for each client (e.g. children's devices).

**Comment by ArchiveBase** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/435
