### ISSUE TITLE
Feature request: add a config option like base url

### ISSUE THREAD

**Issue by bibugo** [AdguardTeam/AdGuardHome#1131]
i installed AdGuardHome in my vps with my web site, in the past version, i can proxy to 
 AdGuardHome listen on  localhost with a subfolder url , but in the lastest version, the login.html and control/ etc. is fixed in root url, and it conflict with my web site. can i get a option to set AdGuardHome access with a subfolder? or it‘s ok just let all url relatively  but not absolutely fixed to root url / . thanks.

**Comment by szolin** [comment]
dup: https://github.com/AdguardTeam/AdGuardHome/issues/1085
