### ISSUE TITLE
请求增加对HTTPS的过滤/Request to increase HTTPS filtering

### ISSUE THREAD

**Issue by 2791717016** [AdguardTeam/AdGuardHome#1132]
请求增加对HTTPS的过滤/Request to increase HTTPS filtering

**Comment by 2791717016** [comment]
请求在HOME版本中增加对HTTPS的过滤
Request to add HTTPS filtering in the home version

**Comment by Zxilly** [comment]
DNS只是对域名的解析，无法管理域名是以何协议被连接。
DNS only resolve the domain name,it has no way to manage how the domain be connected.

**Comment by ameshkov** [comment]
Duplicate of #391
