### ISSUE TITLE
Hardcoded or predefined whitelist

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardHome#1134]
Hello,

I recommend you add a **hardcoded** or **predefined** whitelist for the following domains:
adguard.com
www.adguard.com
github.com
forum.adguard.com
auth.adguard.com
adguardteam.github.io
dns.adguard.com
kb.adguard.com
github.githubassets.com
camo.githubusercontent.com
api.adguard.com
api-b.adguard.com
api-c.adguard.com
api-d.adguard.com
etc.

This will prevent the availability of hosts required for technical support.

Thank you.

**Comment by ArchiveBase** [comment]
Disagree. I believe AG dislike too because they prefer let full control for users. 😉

**Comment by phixion** [comment]
yeah, bad idea. a compromise would be to provide a curated, transparent whitelist of addresses that are required to run their services that users can add to their lists.

**Comment by LazyAspect** [comment]
@phixion, this is acceptable too, i think. Agree.

**Comment by ameshkov** [comment]
Tbh, I am not a fan of whitelists (especially if they're hardcoded), and I don't think we should interfere if someone wants to block our domains.
