### ISSUE TITLE
What does this wierd string mean in Top clients

### ISSUE THREAD

**Issue by JimLee1996** [AdguardTeam/AdGuardHome#1135]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

<img width="514" alt="image" src="https://user-images.githubusercontent.com/15334330/67839070-b5943580-fb2d-11e9-923f-0d03c1d5c7f0.png">

</details>

**Comment by szolin** [comment]
This information is from WHOIS record.
Please execute `whois IP` command manually and check if this string is there.

**Comment by JimLee1996** [comment]
Thank you. As I've checked, they are the same.
There is nothing wrong with AdGuardHome.
