### ISSUE TITLE
Optimize of the blocking list

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardHome#1138]
Hello,

AdGuard Home supports optimized hosts file? For example:

`0.0.0.0 domain1.com domain2.com domain3.com domain4.com domain5.com`
`0.0.0.0 domain6.com domain7.com domain8.com domain9.com domain10.com`

So using multiple domains in the same row? If not, it would be great if he supported and optimized them, as it allows significant savings of RAM. 

Thank you.

**Comment by szolin** [comment]
Are you talking about "Custom filtering rules" field on "Filters" page?

**Comment by ameshkov** [comment]
Yes, it does support this in both filters and custom filtering rules

**Comment by ameshkov** [comment]
Also, I don't recommend using hosts syntax at all.

Please check out this article:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists
