### ISSUE TITLE
Additions to the simple service blocker

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#1139]
Additions to the blocking Under https://github.com/AdguardTeam/AdGuardHome/blob/e04ffde105f88b6665d90ae8d9fbf0c2e84dedbf/home/blocked_services.go#L22

Update WhatsApp to
{"whatsapp", []string{"||whatsapp.net^", "||whatsapp.com^"}},

Update Facebook to

{"facebook", []string{"||facebook.com^", "||facebook.net^", "||fbcdn.net^"}},

Update Youtube to

{"youtube", []string{"||youtube.com^", "||ytimg.com^", "||youtu.be^"}},

And update TikTok to

{"tiktok", []string{"||tiktok.com^", "||tiktokcdn.com^", "||snssdk.com^", "||amemv.com^", "||toutiao.com^", "||ixigua.com^", "||pstatp.com^", "||ixiguavideo.com^", "||toutiaocloud.com^", "||toutiaocloud.net^", "||bdurl.com^", "||bytecdn.cn^", "||byteimg.com^", "||ixigua.com^"}},

**Comment by szolin** [comment]
Can you open a Pull Request so that you will be a direct contributor?

**Comment by Cybo1927** [comment]
How exactly does that work?

**Comment by Cybo1927** [comment]
So... What do I put for this?
![Screenshot 2019-10-31 at 11 23 04 AM](https://user-images.githubusercontent.com/39284087/67965869-d5306a00-fbd0-11e9-86e8-eecac504428b.png)

**Comment by ArchiveBase** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
