### ISSUE TITLE
AdGuardHome won't automatic use the latest certificate when user renew their certificate

### ISSUE THREAD

**Issue by a962702** [AdguardTeam/AdGuardHome#1142]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- 

- [x] I am running the latest version

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.2
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * TL-WDR4300
* **Operating system and version:**
  * OpenWrt 18.06.4

### Expected Behavior

When user renew their certificate, AdGuardHome Should automatic  use the latest certificate.
### Actual Behavior

AdGuardHome still use the old certificate.
 User need to login WebUI, go to Encryption settings and click save config to use the latest certificate.
### Screenshots

<details><summary>Screenshot:</summary>

![issue](https://user-images.githubusercontent.com/23339548/67995133-de2e4380-fc83-11e9-90fa-e373957693fd.png)
![issue2](https://user-images.githubusercontent.com/23339548/67995196-3402eb80-fc84-11e9-8c4a-634019f14a24.png)

</details>

### Additional Information

Also, it seems when I have multiple domains, the domains will display continuous without separation.

**Comment by ameshkov** [comment]
Yeah, I guess we need to implement some sort of a "file watcher" that will monitor changes to the certificate/key files and update encryption settings automatically.

**Comment by szolin** [comment]
Isn't it better if admin can signal that certificates may have changed via 'reload' command? - #1302 
Automatically updating certificate whenever its date changes may be dangerous (insecure), while, on the other hand, 'reload' command issued by admin explicitly confirms his intention.

**Comment by ameshkov** [comment]
Yeah, I guess you're right.

Once `reload` is ready, we should update the Wiki article with this info and provide an example of a script that does all this:
https://github.com/AdguardTeam/AdGuardHome/issues/1420
