### ISSUE TITLE
Missing Client / only listening addresses

### ISSUE THREAD

**Issue by LuersHub** [AdguardTeam/AdGuardHome#1151]
Hello, 

I've just installed AdGuard Home via Docker on my Synology NAS.
I switched the DNS Server from my Fritzbox to the NAS.

KeyFacts:
IP of AdGuard Home: <IP NAS:8181>    (8181 = 80)
Local DNS Server (Fritzbox) : <IP NAS>

So far so good it works. 

My problem:

AdGuard Home DNS server is listening on the following addresses:
127.0.0.1
172.17.0.2
(I don't know how to change that)

And exactly both IP's are the only Clients I'll get. 

I guess I missed something?

Thanks

**Comment by szolin** [comment]
So what exactly doesn't work for you?  Please post a log or error messages you see.

> 127.0.0.1
> 172.17.0.2

You can configure the listening addresses in Install Wizard during the installation.
Or you can change this in yaml file (see `bind_host`) after installation is complete.

**Comment by LuersHub** [comment]
Well, I would like to see unter TOP Clients the IP's e.g. from "Phone A" or "Phone B" or "Laptop A".
Instead I only see the IP's from above. 

Furthermore the systems tells me:
2019/11/05 14:17:58 [info] AdGuard Home is available on the following addresses: 
2019/11/05 14:17:58 [info] Go to http://127.0.0.1:80
2019/11/05 14:17:58 [info] Go to http://172.17.0.2:80

That is definitely wrong, because "IP NAS:80" is correct.

So my problem is, that instead of separate device ip's, I only get 127.0.0.1 or 172.17.0.2 in the top clients list.

**Comment by szolin** [comment]
First, you need to configure your devices to use AGH as a DNS server (see `http://127.0.0.1:80/#guide`)
Once it's done, you'll see their IP addresses in Top Clients.

Then you need to use those IP addresses in Clients configuration page (create a client "Phone A" and set its IP address).
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.96

> 127.0.0.1
> 172.17.0.2
These are IP addresses of AGH itself.

**Comment by LuersHub** [comment]
Thanks, but it seems still not working.
I changed the DNS on the Phone from IP-NAS to 127.0.0.1:80

I can see that the filter does work (checked an website), like it did before.
But under Top Clients nothing new is listed.

However the AGH tells me that it is available under those 2 addresses, under top clients the IP 172.17.0.1 shows up (the last digit is different).

**Comment by szolin** [comment]
127.0.0.1 is a loopback address - your Phone will try to connect to itself.  Try another IP.

**Comment by LuersHub** [comment]
No, still not working.

Is there any good installation guide for synology docker?
Just to exclude is has something to do with the NAS.

**Comment by ArchiveBase** [comment]
@LuersHub Please refer bit about docker networking, optionally you may able to use macvlan for assign container running on a separate ip. it's necessary to realize about basic concepts then this is not a difficult thing
https://docs.docker.com/v17.09/engine/userguide/networking/#the-default-bridge-network
https://docs.docker.com/network/network-tutorial-standalone/
https://docs.docker.com/network/macvlan/

**Comment by LuersHub** [comment]
Thanks, that is exactly what I've researched the last hours ;)
I think I'll go with the macvlan option or try it on Raspberry Pi.
