### ISSUE TITLE
Adguard Home dns rewirtes function working with ipv6

### ISSUE THREAD

**Issue by yyysuo** [AdguardTeam/AdGuardHome#1153]
- [x] I am running the latest version yes
- [x] I checked the documentation and found no answer yes
- [x] I checked to make sure that this issue has not already been filed yes

### Problem Description
1：main router IP :10.10.10.1
2：Adguard Home on 10.10.10.200 in a docker container
3：my router dhcp setting as below
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	option dhcpv6 'server'
	option ra 'server'
	option ra_management '1'
	option ra_default '1'
        option dhcp_option '6,10.10.10.200'
	list dns 'fd85:XXXX::200'      "ipv6 address of 10.10.10.200，docker address 172.17.0.1
	option force '1'
4：network ipv6 enabled
5：add dns rewrites record    10.10.10.2  www.ap.com
6：nslookup result
nslookup www.ap.com 10.10.10.200
Server:    10.10.10.200
Address 1: 10.10.10.200 LEDEDocker.lan

Name:      www.ap.com
Address 1: 10.10.10.2
Address 2: 2606:4700:20::6819:b219
Address 3: 2606:4700:20::6819:b319

Problem 1：
dns rewrites function append the ip into the dns result，why just replace the dns result only with 10.10.10.2 and do not request the result from the upper dns?

Problem 2：when devices assigned with ipv6 address ask dns result in ipv6 way，the record in the 
log show the request ip is 172.17.0.1，would you please show the ipv6 adress or the device's name?

Question 1：do I set the ipv6 dns adress in right way?what's the right way if I'm wrong?

thank you for your very good product，it's very usefull.

**Comment by szolin** [comment]
> dns rewrites function append the ip into the dns result

* nslookup sends 2 requests: A, AAAA
* You set up DNS rewrite for A record - this is what nslookup receives.
* You didn't set up DNS rewrite for AAAA record - AGH proxies this request to upstream and nslookup receives this response.

> the record in the log show the request ip is 172.17.0.1

Yes, because this IP sent a request.  IPv6 address will be shown only when a client with IPv6 address makes requests.

**Comment by yyysuo** [comment]
> > dns rewrites function append the ip into the dns result
> 
> * nslookup sends 2 requests: A, AAAA
> * You set up DNS rewrite for A record - this is what nslookup receives.
> * You didn't set up DNS rewrite for AAAA record - AGH proxies this request to upstream and nslookup receives this response.
> 
> > the record in the log show the request ip is 172.17.0.1
> 
> Yes, because this IP sent a request. IPv6 address will be shown only when a client with IPv6 address makes requests.

thank you for your reply，what should i do so i can make the client show ipv6 address or device name?

![image](https://user-images.githubusercontent.com/10081071/68293061-24423780-00c8-11ea-82c1-89986bfdf7b1.png)

![image](https://user-images.githubusercontent.com/10081071/68293077-2d330900-00c8-11ea-84b6-a3df74001268.png)

![image](https://user-images.githubusercontent.com/10081071/68293085-32905380-00c8-11ea-8d27-0c1c3eb2a3fa.png)

**Comment by szolin** [comment]
Try using `dig -6` instead, it should use IPv6 rather than IPv4.

**Comment by yyysuo** [comment]
I'm not very familiar with dig，and I'm not a programmer. I got no record in the log page if I use the dig command.

**Comment by szolin** [comment]
Did you google how to use `dig` command?

**Comment by ameshkov** [comment]
> what should i do so i can make the client show ipv6 address or device name?

IPv6 -- you cannot, your AdGuard Home instance works on an IPv4 address.
Device name -- you should add this client to the "Clients" list manually
