### ISSUE TITLE
DuckDuckGo CNAME rewrite issue

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardHome#1156]
Hello,

AGH 0.99.2, VPS Debian 9. I added a CNAME **safe.duckduckgo.com** entry for the **duckduckgo.com** root domain:

![image](https://user-images.githubusercontent.com/45385632/68365800-bbe46c00-0142-11ea-9b78-b59457f11975.png)

The domain is no longer resolved. Dig output is emptry:

![image](https://user-images.githubusercontent.com/45385632/68365830-d74f7700-0142-11ea-99f8-17a7c89d2d10.png)

Everything works fine when I delete this record.

P.S.: I can 't use the shared secure search feature because I don 't need it for YouTube. It is a bug?

Thank you.

**Comment by szolin** [comment]
Thank you!  It was accidentally broken in v0.99.1.
