### ISSUE TITLE
Blocked Services: WhatsApp app still works

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1158]
https://github.com/AdguardTeam/AdGuardHome/issues/1122#issuecomment-550385842

**Comment by ameshkov** [comment]
Well, I don't think we can fix this, whatsapp app is simply unblockable on the DNS-level :(

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1145 > https://github.com/AdguardTeam/AdGuardHome/issues/391

**Comment by Lmarto2** [comment]
Good afternoon, I have the same problem, is there any solution to resolve this?
