### ISSUE TITLE
Safesearch option for DuckDuckGo and Pixabay

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardHome#1159]
Hello,

It probably makes sense to add DuckDuckGo and Pixabay to the safesearch option:
https://help.duckduckgo.com/duckduckgo-help-pages/features/safe-search/
https://pixabay.com/blog/posts/block-adult-content-on-pixabay-at-your-school-or-w-140/

In both cases, CNAME record is required.

Thank you.

**Comment by ameshkov** [comment]
@szolin looks easy, but please don't forget to change the "Safe search" option description in the UI and mention these services there.

**Comment by LazyAspect** [comment]
@ameshkov & @szolin, taking this opportunity, I want to say that it would be great to manage a safesearch for each service separately. Because safesearch for engines disables sites for adults mostly, but for YouTube disables half the content marked as unacceptable for kids. Thank you.

**Comment by ameshkov** [comment]
@LazyAspect could you please file a separate feature request?
