### ISSUE TITLE
Please change "Page %1 of %2" to "Page %1 / %2".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#1166]
of = 之.
Due to different grammar, need to reverse the place holders: %1 of %2 = %2 之 %1 in Chinese UI.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/816AVBW.png)
</details><br/>

Please fix these in several places for Chinese UI as long as you use "%1 of %2".

The idea from AG team is more convenient.
You can change "Page %1 of %2" to "Page %1 / %2".
Only modify "of" to "/" in this case.

**Comment by ameshkov** [comment]
What do you think if we change this to something more universal?

Something like "Page 1 / 10"?

**Comment by lancelot-moon** [comment]
Yes, this is really a good and universal idea!
Please use the solution.

**Comment by lancelot-moon** [comment]
@IldarKamalov 
https://crowdin.com/translate/adguard-applications/17566/en-zhtw#3862624

Did you forget to fix "of" to "/" there?

**Comment by IldarKamalov** [comment]
It's an obsolete string, we'll remove it soon
