### ISSUE TITLE
http: TLS handshake error

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1167]
Hello,

VPS, Debian 9, AGH 0.99.2. I'm not sure it 's a bug. But when I use the web-interface, i at once see a errors in the log:
```
2019/11/08 20:58:50 http: TLS handshake error from IP:53525: EOF
2019/11/08 21:37:59 http: TLS handshake error from IP:55822: EOF
2019/11/08 21:45:27 http: TLS handshake error from IP:56389: EOF
```
I use a certificate from Lets Encrypt for DoH, DoT, and HTTPS. DoT/DoH handshakes works without any errors. Tests on ssllabs.com and sslshopper.com successful. I can send the configuration file, domain and full logs to devteam@adguard.com.

Something similar is described here:
https://stackoverflow.com/questions/34823724/golang-tls-handshake-error
https://stackoverflow.com/questions/39547459/golang-http2-and-tls-handshake-errors

Thank you.

**Comment by ameshkov** [comment]
This means that the client closed connections unexpectedly, this is not really a problem.

I think we should simply log this with DEBUG level, not ERROR.

**Comment by szolin** [comment]
These don't seem like our log messages.  What application writes these logs?

**Comment by ameshkov** [comment]
@szolin it's ours of course. We should've configured `ErrorLog *log.Logger` for the `http.Server` instance.
