### ISSUE TITLE
Google reCAPTCHA for Login page

### ISSUE THREAD

**Issue by thueske** [AdguardTeam/AdGuardHome#1168]
Hey!

Are there any ideas about integrating Google reCAPTCHA for the Login page?

Thanks :)

Tobias

**Comment by ArchiveBase** [comment]
_Google reCaptcha *]^@$% then see https://github.com/AdguardTeam/AdGuardHome/issues/675 https://github.com/AdguardTeam/AdGuardHome/issues/805_

**Comment by AngelFalse** [comment]
Don't think that's a good idea. There are some countries that blocked Google's services totally.(like mine)
And completing reCaptcha is REALLY HARD WORK. (in my experience)
