### ISSUE TITLE
Mark non-localhost filter hits differently in the query log

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1169]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Currently, such entries as `69.25.139.140 conntest.nintendowifi.net` are marked in red in the query logger as if it had been blocked instead of redirected. This can cause considerable confusion as to whether the entries are working as they should. I know I was confused for half an hour or so.

I propose that such entries (i.e. 'hosts'-filtered domains that are neither 127.0.0.1, 192.168.1.1, 0.0.0.0, 0, or ::) be marked with yellow or purple instead of red in the query log (Blue is already taken by DNS rewrites, seemingly), and that the *Unblock* button for such entries get renamed into something else (Maybe "Normalise"?).

* **Version of AdGuard Home server:**
  * 0.99.2
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * N/A
* **Operating system and version:**
  * Used to access the GUI: Windows 10 May 2019 Update
  * Used to test the example entry: Nintendo 3DS, firmware 11.11.0-43E, in Nintendo DS mode

### Expected Behavior
It becomes easily visible when a domain that is set to use a non-localhosts IP with the 'hosts' syntax, has been set as such instead of being shown as blocked.

### Actual Behavior
All 'hosts'-filtered domains are shown as red and blocked, regardless of the entry's targeted IP adress.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/68536245-f7a05100-034f-11ea-82cb-db97c43b4bad.png)

</details>

### Additional Information
The example entry in *Issue Details* is a genuine example based on https://github.com/RiiConnect24/DNS-Server/blob/master/dns_zones.json, and appears to be the combined backend IPs of the Wii/DS online tools *Wiimmfi* and *RiiConnect24*, which are in most cases intended to almost solely be used by their DNS servers.

In addition to their use in the Nintendo retro homebrew community, non-localhost 'Hosts' entries are also often used in censorship bypass filterlists, especially ones intended for PR-China and Indonesia. Being able to properly and very clearly show that AdGuard Home can use such lists, would've been a huge PR boost for it (as far as my zero-marketing-experience mind can determine).

**Comment by ameshkov** [comment]
> Currently, such entries as 69.25.139.140 conntest.nintendowifi.net

Well, we made "DNS Rewrites" settings specifically for such entries.

**Comment by DandelionSprout** [comment]
"DNS Rewrites" currently doesn't support filterlists that I'm aware of, unfortunately.

**Comment by ameshkov** [comment]
I guess you should upvote this feature request then:
https://github.com/AdguardTeam/AdGuardHome/issues/919
