### ISSUE TITLE
Fatal Error: len(units) != s.limit: 23 24

### ISSUE THREAD

**Issue by sephrioth** [AdguardTeam/AdGuardHome#1170]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.2
* **How did you setup DNS configuration:**
  * NAS
* **If it's a router or IoT, please write device model:**
  * Synology
* **Operating system and version:**
  * DSM latest

### Actual Behavior

AdguardHome Container Stoped with this error (not the first time but the same error)

> 2019-11-11 11:00:00 | stdout | 2019/11/11 11:00:00 [fatal] len(units) != s.limit: 23 24
2019-11-11 08:06:49 | stdout | 2019/11/11 08:06:49 [info] Updated filter #1.  Rules: 31804 -> 31813

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Restart container solved this issue.

**Comment by szolin** [comment]
Did you change Statistics configuration settings before this?

**Comment by sephrioth** [comment]
> Did you change Statistics configuration settings before this?

No.. the configuration is untouched for months.
