### ISSUE TITLE
[Feature Request] Support for captive portal detections 

### ISSUE THREAD

**Issue by cubakcabak** [AdguardTeam/AdGuardHome#1171]
### Problem Description

I'm using AdguardHome on laptop, travelling elsewhere sometimes wifi connections such as cafe or hotels need user authenticate themself through web based captive portal, but when the dns pointed to localhost it needed to be changed to the dhcp one so it can authenticate the connections, and then changed back to localhost (AGH) again.

### Proposed Solution

It would be nice if AGH can detect the captive portal and be used on the get go, somekind of "set and forget" after installations, without the user need to change the system dns configurations.

**Comment by ArchiveBase** [comment]
If you are using windows or linux then it's possible to configure network adapter settings for obtain an IP address automatically and keep your adguardhome server address as 127.0.0.1 without change.

**Comment by ArchiveBase** [comment]
Optional solution to perform above mentioned task easily, you can create two .bat files and save on desktop (change according to operating system)

1. netsh interface ip set dns "Wi-Fi" static 127.0.0.1 primary > manual_dns.bat
2. netsh interface ip set dns "Wi-Fi" dhcp > default_dns.bat

If you know the specific server address used by hotspot operator that unable to resolve by public DNS then you can add it to adguard home DNS settings area. alternatively it's possible to force view that captive portal manually without make change if it hosted within local network.

**Comment by ameshkov** [comment]
Tbh, this use-case is unusual for AdGuard Home as it's supposed to be server-side software, not client-side.

**Comment by cubakcabak** [comment]
@ArchiveBase 
thanks for that command line, good enough for me for now, just need to figure out the equivalent command for linux.

@ameshkov
AGH used for it's DoH/DoT capability on desktop because in my country dns are filtered by the country regulators, for their political reasons, hindering access to outside world for some service they deem "inappropriate".

Its fine as it is now, and i thank the dev of AGH for it.

I just thought if it can be used by "non technical" person, it will be wonderful.
