### ISSUE TITLE
Add Norwegian language to AdGuard Home

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1174]
It's on Crowdin, so I figured I should give you guys a heads-up about it, along the lines of #1043.

I also have a bonus question: Currently the translation files on Crowdin are set to be non-exportable and non-importable. The non-exportability is a bit unfortunate for me, as I maintain [something of a fully free Translation Memory for Norwegian Bokmål](https://github.com/DandelionSprout/Norwegian-Fan-Translations/tree/master/Translation%20memories), and in particular I'd need to be able to use the option for "Download in XLIFF" to boost my TM with AdGuard translations easily.
![image](https://user-images.githubusercontent.com/22780683/68702998-0bcf9280-058a-11ea-8028-9eaf1e4e4c5e.png)

**Comment by ameshkov** [comment]
Thank you!

> The non-exportability is a bit unfortunate for me

You should be able to export it now, please check it.

**Comment by DandelionSprout** [comment]
I can confirm it's now exportable. Thank you once again.

**Comment by IldarKamalov** [comment]
@aalpatkina We need your help to approve the Norwegian translation
