### ISSUE TITLE
Anyway I can change the Admin interface login credential after first setup?

### ISSUE THREAD

**Issue by AngelFalse** [AdguardTeam/AdGuardHome#1175]
### Prerequisites

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Problem Description

I suppose to find somewhere to change my Admin interface login password, but ended up empty-handed after looking through every pages in the admin interface.

### Proposed Solution
Add somewhere to change the login credential, or at least the password.

Somewhere in "Settings - General Settings" will be nice.

Something as simple as this shall work:

https://s2.ax1x.com/2019/11/14/MNr4gS.png

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset

**Comment by AngelFalse** [comment]
> 
> 
> https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset

Well.. I'm using AGH under Windows...
And I got these when I type apt install httpd in WSL:
> Package httpd is a virtual package provided by:
>  apache2 2.4.38-3+deb10u3
>  yaws 2.0.6+dfsg-1
>  webfs 1.21+ds1-12
>  tntnet 2.2.1-3+b1
>  nginx-light 1.14.2-2+deb10u1
>  nginx-full 1.14.2-2+deb10u1
>  nginx-extras 1.14.2-2+deb10u1
>  mini-httpd 1.30-0.2
>  micro-httpd 20051212-15.1
>  lighttpd 1.4.53-4
>  ebhttpd 1:1.0.dfsg.1-4.3+b2
>You should explicitly select one to install.

Does that mean I need to install a http server in the list to obtain htpasswd?

**Comment by ArchiveBase** [comment]
apt-get install apache2
_(i think docs need to be updated for ubuntu/debian to avoid conflict or explain about it)_

**Comment by AngelFalse** [comment]
Would it be better if anyone can add a link to the original project repo there? Probably this will solve the problem that there's no existing tutorial for Windows users to reset the password.(at least some users will have idea about how to use htpasswd on windows and the dependencies required to be met.)

Original project repo:
https://github.com/http-auth/htpasswd

Brief:
1.Have npm and node.js ready on the machine.
2."npm install htpasswd"
3."htpasswd -Bnb username passwd"
