### ISSUE TITLE
[Question] Disable recursive queries

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardHome#1177]
Hello,

it 's just a question. Some ISPs require that recursive queries be disabled due to high network load. How do I do this correctly on Debian 9 + AGH 0.99.2 to avoid losing AGH`s functionality?

Thank you.

**Comment by ameshkov** [comment]
AG is not a DNS recursor so this is not a problem, the recursive queries are performed on the DNS resolver side

**Comment by LazyAspect** [comment]
> AG is not a DNS recursor so this is not a problem, the recursive queries are performed on the DNS resolver side

I don 't understand. I receive notifications from my ISP to turn off recursive queries and proof-links:
https://openresolver.com/?ip=194.58.121.92

; <<>> DiG 9.11.2 <<>> @194.58.121.92 yandex.ru
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49012
;; flags: qr rd **ra**; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;yandex.ru.                     IN      A

;; ANSWER SECTION:
yandex.ru.              117     IN      A       77.88.55.55
yandex.ru.              117     IN      A       5.255.255.5
yandex.ru.              117     IN      A       5.255.255.50
yandex.ru.              117     IN      A       77.88.55.50

;; Query time: 8 msec
;; SERVER: 194.58.121.92#53(194.58.121.92)
;; WHEN: Fri Nov 15 14:00:57 MSK 2019
;; MSG SIZE  rcvd: 91`

Does anyone know how to turn them off on Debian 9 if you don 't have a full bind9? Unless most ISPs do so will disable services for violation Terms & Conditions. Please, explain.

Thank you.

**Comment by ArchiveBase** [comment]
> Does anyone know how to turn them off on Debian 9 if you don 't have a full bind9?

 Use firewall-iptables.

**Comment by ameshkov** [comment]
> I don 't understand. I receive notifications from my ISP to turn off recursive queries and proof-links:

This makes little sense. It's more likely they just don't want you to run a public DNS server.
If so, I'd recommend changing the VPS provider.
