### ISSUE TITLE
AdGuard Home is unable to store more than 5 full pages of DNS query logs

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardHome#1178]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.99.2
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Unspecified QNAP
* **Operating system and version:**
  * unspecified

### Expected Behavior
AdGuard Home should be able to store DNS query logs over the last 30 days.

### Actual Behavior
AdGuard Home can only store up to 5 pages of DNS query logs (current maximum is 500 queries).

### Screenshots

<details><summary>Screenshot:</summary>

![3](https://user-images.githubusercontent.com/33634917/68937270-c2a75a80-07a4-11ea-9781-1de8c23ed8f1.png)
![2](https://user-images.githubusercontent.com/33634917/68937272-c33ff100-07a4-11ea-975c-70d2f8e15a97.png)
![1](https://user-images.githubusercontent.com/33634917/68937273-c33ff100-07a4-11ea-996e-62176ff3ec08.png)

</details>

### Additional Information
Helpdesk ID: 2236692

**Comment by szolin** [comment]
When you reach the 5th page it will load more data.
We are improving query logs page in v0.99.3, it's going to be more fast and responsive.

**Comment by lbtboy** [comment]
Three devices are configured with AdGuard Home, NAS QNAP D4 and two Debian 10 devices. On all devices saves only 5000 requests in the log, not 30 days as stated.

**Comment by szolin** [comment]
> saves only 5000 requests in the log, not 30 days as stated.

Do you mean you can see only 5k requests in UI (if so, did you go through all 50 pages?) or there are just 5k lines in `data/querylog.json` file?
What's your AGH version?

**Comment by lbtboy** [comment]
ADH v.v0.99.2.In data / querylog.The JSON file is more than 25000 lines, but the ADH interface displays only 5000 lines, 5 pages of 100 lines.

**Comment by szolin** [comment]
> 5000 lines, 5 pages of 100 lines

5*100=500, not 5000
Did you go to the 5th page?

> When you reach the 5th page it will load more data.

**Comment by lbtboy** [comment]
I dropped all the magazines. Let's see what happens next. When searching the query log by IP, no queries over 5000 lines were displayed, i.e. a void was displayed. What is it connected with?
