### ISSUE TITLE
feedback problem

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1180]
Hostname |OPENWRT
-- | --
Model | Intel(R) Core(TM) i3 CPU @ 2.00GHz 
CPU Info | 2018.775  MHz        +36.0°C
Firmware Version | OpenWrt 	LuCI Master (git-19.299.52050-0b735ea)
Kernel Version | 4.19.81
Local Time | Sat Nov 16 09:25:11 2019
Uptime | 0h 50m 17s
Load Average | 0.00, 0.00, 0.00

add more url lists in Adguardhome,but show me more errors ,need upgrade to support big data.
Error: control/set_upstreams_config | Couldn't write config file: open /usr/bin/AdGuardHome/AdGuardHome.yaml.tmp: too many open files | 500

Error: control/filtering/add_url | Failed to save filter 1573864519 due to open /usr/bin/AdGuardHome/data/filters/1573864519.txt.tmp: too many open files | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://www.threatcrowd.org/feeds/domains.txt: Get https://www.threatcrowd.org/feeds/domains.txt: read udp 127.0.0.1:35246->127.0.0.1:10053: i/o timeout | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://www.threatcrowd.org/feeds/domains.txt: got status code != 200: 503 | 400

Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: couldn't lookup host: static.adguard.com | 502

Error: control/filtering/add_url | Couldn't fetch filter from url https://hosts-file.net/emd.txt: Get https://hosts-file.net/emd.txt: synthetic.wrap: couldn't dial to [::]:443, cause: dial tcp 0.0.0.0:443: connect: connection refused (hidden: dial tcp [::]:443: connect: connection refused) | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://hosts-file.net/fsa.txt: Get https://hosts-file.net/fsa.txt: synthetic.wrap: couldn't dial to 0.0.0.0:443, cause: dial tcp [::]:443: connect: connection refused (hidden: dial tcp 0.0.0.0:443: connect: connection refused) | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://hosts-file.net/pup.txt: Get https://hosts-file.net/pup.txt: synthetic.wrap: couldn't dial to [::]:443, cause: dial tcp 0.0.0.0:443: connect: connection refused (hidden: dial tcp [::]:443: connect: connection refused) | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://tgc.cloud/downloads/iOSAds.txt: Get https://tgc.cloud/downloads/iOSAds.txt: read udp 127.0.0.1:52093->127.0.0.1:10053: i/o timeout | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://gitlab.com/intr0/iVOID.GitLab.io/raw/master/iVOID.hosts: Get https://gitlab.com/intr0/iVOID.GitLab.io/raw/master/iVOID.hosts: read udp 127.0.0.1:32874->127.0.0.1:10053: i/o timeout | 400

Hope upgrade like openwrt adblock and adgurad adblocker extension ,support more rule lists,thank you.

**Comment by szolin** [comment]
> control/filtering/add_url | Failed to save filter 1573864519 due to open /usr/bin/AdGuardHome/data/filters/1573864519.txt.tmp: too many open files

Can you reproduce it after restart?

**Comment by jkle112** [comment]
Reinstall AdguardHome and upgrade to latest version,another problem:

Error: control/filtering/add_url | Couldn't fetch filter from url https://280blocker.net/files/280blocker_domain.txt: Get https://280blocker.net/files/280blocker_domain.txt: read udp 127.0.0.1:56645->127.0.0.1:10053: i/o timeout | 400

Hope upgrade like openwrt adblock and adgurad adblocker extension ,support more rule lists,thank you.

**Comment by jkle112** [comment]
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: couldn't lookup host: static.adguard.com | 502

Error: control/filtering/add_url | Couldn't fetch filter from url https://raw.githubusercontent.com/CNMan/dnscrypt-proxy-config/master/dnscrypt-blacklist-domains.txt: net/http: request canceled (Client.Timeout exceeded while reading body) | 400

Error: control/filtering/add_url | Couldn't fetch filter from url https://raw.githubusercontent.com/lightswitch05/hosts/master/tracking-aggressive.txt: Get https://raw.githubusercontent.com/lightswitch05/hosts/master/tracking-aggressive.txt: read tcp 192.168.168.26:40590->151.101.64.133:443: read: connection reset by peer | 400

Hope upgrade like  adgurad adblocker extension ,support more adblock plus rule lists,thank you.
https://mirror.espoch.edu.ec/malwaredomains/justdomains
http://www.shallalist.de/Downloads/shallalist.tar.gz

I have add over 800 url lists for blocklists,but reinstall it ,need a better way to add blocklists.
