### ISSUE TITLE
Problem with response caching

### ISSUE THREAD

**Issue by skydrome** [AdguardTeam/AdGuardHome#1182]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.2, channel beta
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * Archlinux 5.3.11

### Expected Behavior
DNS Lookups for the same domain in the default of 30 minutes should be responded with the cached host.

If a successful lookup gets cached and I lose access to my upstream provider, subsequent requests should not fail in the cache_time duration.

### Actual Behavior
Every request is being sent to the upstream dns server.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information
would like to not have to use a caching dns server alongside adguardhome if this can be added/fixed
Is this achieved by doing what blocked_response_ttl does but for any response?

**Comment by ameshkov** [comment]
Hm, they should not have failed.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by skydrome** [comment]
I guess this resolved itself after updating and restarting.
Im seeing `Resolve(): Serving cached response` now
