### ISSUE TITLE
VPS: No DNS resolution of private IP addresses (e.g. *.local, *.fritz.box)

### ISSUE THREAD

**Issue by crivchri** [AdguardTeam/AdGuardHome#1183]
### Prerequisites

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.2
* **How did you setup DNS configuration:**
  * VPS
* **If it's a router or IoT, please write device model:**
  * Jelastic Cloud (Docker: https://hub.docker.com/r/adguard/adguardhome)
* **Operating system and version:**
  * Alpine Linux 3.11_alpha20190925 (edge)

### Expected Behavior

I have successfully setup AdGuard Home on a VPS and it is working fine on all my devices (incl. Android, iOS, Mac OS), as well as using 4G and WiFi connections. Depending on the device, I am using DoT (Android) of DoH (iOS) to encrypt the DNS transport.

### Actual Behavior

When I am connected to my home network (via WiFi or VPN), AdGuard Home (VPS) is not able to resolve the private domain names (e.g. *.local, *.fritz.box) to my internal IP range (192.168.178.###).

### Screenshots

<details><summary>Screenshot:</summary>

#### DNS settings:
![image](https://user-images.githubusercontent.com/1508132/69052392-3b0d5600-0a07-11ea-974f-efc3c5829aa3.png)
![image](https://user-images.githubusercontent.com/1508132/69052523-858ed280-0a07-11ea-8556-d22464b0ac4b.png)

#### Encryption settings:
![image](https://user-images.githubusercontent.com/1508132/69052949-95f37d00-0a08-11ea-897c-9157ce0bec80.png)
![image](https://user-images.githubusercontent.com/1508132/69052885-70ff0a00-0a08-11ea-8d45-671e787e3dfb.png)
</details>

**Comment by szolin** [comment]
### Specifying upstreams for rDNS

AdGuardHome automatically gets the names of connected devices using Reverse DNS lookup (rDNS).
It sends a PTR request with an IP address of a client to a DNS server and uses its name for "clients friendly names".
But what if you want AdGuardHome to use another DNS server for a specific IP address range?
You can do it using the same syntax as for general upstream servers, for example:

    [/168.192.in-addr.arpa/]192.168.0.1

This rule instructs AdGuardHome to use `192.168.0.1` DNS server for all rDNS requests to resolve clients' IP addresses `192.168.0.0/16`.

**Comment by crivchri** [comment]
> ### Specifying upstreams for rDNS
> AdGuardHome automatically gets the names of connected devices using Reverse DNS lookup (rDNS).
> It sends a PTR request with an IP address of a client to a DNS server and uses its name for "clients friendly names".
> But what if you want AdGuardHome to use another DNS server for a specific IP address range?
> You can do it using the same syntax as for general upstream servers, for example:
> 
> ```
> [/168.192.in-addr.arpa/]192.168.0.1
> ```
> 
> This rule instructs AdGuardHome to use `192.168.0.1` DNS server for all rDNS requests to resolve clients' IP addresses `192.168.0.0/16`.

Thanks a lot for your answer.

I have added "[/168.192.in-addr.arpa/]192.168.0.1" to the upstream DNS servers, but it does not resolves my issue with the internal domain names (e.g. *.local, *.fritz.box) in my home network (via WiFi or VPN), which should resolve to the internal IP range (192.168.178.###).

**Comment by ameshkov** [comment]
> When I am connected to my home network (via WiFi or VPN), AdGuard Home (VPS) is not able to resolve the private domain names (e.g. *.local, *.fritz.box) to my internal IP range (192.168.178.###).

It sounds as if you might need to add your private domains to DNS rewrites manually (go to DNS settings -> scroll down to DNS rewrites).

**Comment by crivchri** [comment]
> > When I am connected to my home network (via WiFi or VPN), AdGuard Home (VPS) is not able to resolve the private domain names (e.g. *.local, *.fritz.box) to my internal IP range (192.168.178.###).
> 
> It sounds as if you might need to add your private domains to DNS rewrites manually (go to DNS settings -> scroll down to DNS rewrites).

Is it possible to add the whole domains private domains (e.g. *.local, *.fritz.box) or do I need to add each single device manually?

Thanks!

**Comment by ameshkov** [comment]
> Is it possible to add the whole domains private domains (e.g. *.local, *.fritz.box) or do I need to add each single device manually?

There's a feature request that's planned on v0.101: https://github.com/AdguardTeam/AdGuardHome/issues/922

Until it's done, you'll have to add each domain manually :(

**Comment by crivchri** [comment]
@ameshkov Thanks a lot for your help!

**Comment by jschwalbe** [comment]
Does that fix it, though? 

It seems like that fix allows one to tell adguard to _resolve_ *.blah.com to a specific IP, but does it also allow one to cause *.blah.com _to resolve with_ a specific server?

**Comment by ameshkov** [comment]
> It seems like that fix allows one to tell adguard to resolve *.blah.com to a specific IP, but does it also allow one to cause *.blah.com to resolve with a specific server?

This is possible using this:
https://github.com/AdguardTeam/AdGuardHome/issues/1183#issuecomment-555090160

**Comment by jschwalbe** [comment]
@ameshkov maybe I'm not understanding correctly, but it seems like that's backwards and I don't understand how it would work, or it's for a different purpose.

As I see it, for that rule to work, AdGuard has to already know the IP before it resolves the IP.. right? 
Me: "What's the IP for laptop.local"
AG: "Since I already know that `laptop.local` resolves to 192.168.1.4, I'm going to follow the rule that says if the IP is 192.168.*.*, then use Server A"  <-- seems like that logic doesn't work

**Comment by szolin** [comment]
@jschwalbe  https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains

**Comment by ameshkov** [comment]
@jschwalbe no, this is exactly what you want: 

`[/local/]192.168.0.1` means "If domain is `*.local` send DNS queries to `192.168.0.1`

**Comment by JokerQyou** [comment]
If one is using the built-in DHCP server provided by Adguard Home then why can't AGH just return the IP from DHCP leases (both dynamic and static entries)? I tried that and it did not work.
