### ISSUE TITLE
Small bug,I have a valid certificate, sign by cloudflare,but it show error x509

### ISSUE THREAD

**Issue by i553041** [AdguardTeam/AdGuardHome#1187]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
0.99.3
* **How did you setup DNS configuration:**
  * 
Router
* **If it's a router or IoT, please write device model:**
  * 
Raspberry Pi 3 Model B+
* **Operating system and version:**
  * 
Ubuntu 18.04.3

### Expected Behavior

Please verify cloudflare certificate,it is not unknown authority.

### Actual Behavior

I use cloudflare CDN,and use their certificate,I quite sure the certificate is valid,but in AGH,it show this error: "Certificate chain is invalid","Your certificate does not verify: x509: certificate signed by unknown authority" .Although I can use the HTTPS,but the red error text it makes my eyes not comfortable.

Is AGH only support letsencrypt certificate as "known authority"?

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1050" alt="螢幕截圖 2019-11-20 下午9 32 51" src="https://user-images.githubusercontent.com/53026952/69243212-8da06b00-0bdd-11ea-920a-272bd7fbd131.png">

This is my cloudflare settings:

<img width="957" alt="螢幕截圖 2019-11-20 下午9 36 35" src="https://user-images.githubusercontent.com/53026952/69243392-ec65e480-0bdd-11ea-8f05-95b7a9c00c6e.png">

<img width="1021" alt="螢幕截圖 2019-11-20 下午9 37 40" src="https://user-images.githubusercontent.com/53026952/69243427-03a4d200-0bde-11ea-8580-4b859a6567e4.png">

<img width="945" alt="螢幕截圖 2019-11-20 下午9 38 54" src="https://user-images.githubusercontent.com/53026952/69243514-32bb4380-0bde-11ea-9c97-c66bb599f86e.png">

</details>

**Comment by ArchiveBase** [comment]
I think it's not X.509 format, why you dislike to use let’s encrypt then?

Furthermore it's not trusted by client browsers when directly access to origin outside of Cloudflare https://support.cloudflare.com/hc/en-us/articles/115000479507

**Comment by ameshkov** [comment]
Cloudflare root cert is not installed to the roots system storage that's why it is "unknown" to AG.

Please note, that Cloudflare is not a certificate authority so operation systems do not trust their "origin certs".
