### ISSUE TITLE
My proposal for a rewriting of "Reset Web Password" in the wiki

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1195]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.3
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * Raspbian Buster

### Description

Currently, there's some slight confusion and absent details in https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#reset-web-password that made it rather difficult for me to follow the guide. Among them, was that:

• `apt-get install httpd` did not actually work because `httpd` is not an actual package, and that `apache2` should be installed instead.
• I feel it should be specified that *bcrypt* encryption of the hash is mandated by AdGuard Home, which rules out the use of various web-based `htpasswd` generators, e.g. https://www.htaccesstools.com/htpasswd-generator/.
• The need for root could need to be stated more openly; I couldn't even seem to *open* `AdGuardHome.yaml` without sudo, let alone save it.
• A general absence of Windows info, for the (presumably not all that many) users who do run AdGuard Home on Windows only.

As I do not have edit rights for the wiki, and would be surprised if I got such rights anytime soon, here's my attempt at a rewrite of that wiki section:

### Rewrite suggestion

```
### Reset Web Password
Please follow these steps to create a new password for your user account:

1. Install `htpasswd`, which is a part of *Apache2 Web Server*:

Ubuntu:

`sudo apt-get install apache2`

Fedora:

`sudo dnf install apache2`

Windows:

>Choose a download from https://httpd.apache.org/docs/current/platform/windows.html#down, extract the downloaded folder, open a terminal, navigate to its `bin` folder with the `cd` command, and run `.\Htpasswd` (Note the capital H in the Windows version).

Other versions of `htpasswd` could be used, but **only** if they support *bcrypt* hash encryption, which rules out e.g. most web-hosted `htpasswd` generators.

2. Use the `htpasswd` utility to generate a new hash:

Ubuntu/Fedora:

`htpasswd -B -n -b <USERNAME> <PASSWORD>`

Windows:

`.\Htpasswd -B -n -b <USERNAME> <PASSWORD>`

It will print `<USERNAME>:<HASH>` to the terminal.

3. Open `AdGuardHome.yaml` in a text editor with sudo rights.

In the `users:` section, find your username and insert the `<HASH>` value for the `password` setting:

 ```users:
 - name: ...
 password: <HASH>```

Save the file, restart AGH. Now you'll be able to log in to the Web interface using your new password.
```

### Screenshots

None that I presumed could be relevant to this.

</details>

### Additional Information

I'm not really sure if there's *any* web-based `htpasswd` generators that support *bcrypt*, but I went with the assumption that there surely had to be *some* of them hidden out there on the internet.

**Comment by ArchiveBase** [comment]
Indeed https://github.com/AdguardTeam/AdGuardHome/issues/1175

**Comment by ArchiveBase** [comment]
@ameshkov  I think if we move github wiki to [adguard documentation](https://kb.adguard.com/en/home/overview) might be better. additionally others may help with translation and easy to pull request for extend docs.

https://kb.adguard.com/en/home/overview
https://github.com/AdguardTeam/AdguardKnowledgeBase

Currently docker details too insufficient. It doesn't explain anything about how to set-up properly except minimum instruction for get started. It must include guide for configure in various docker environments, networks, troubleshoot guide and some details to secure the instance and it's not secret people check third-party pi-hole guides and seek help through forums etc.

https://github.com/AdguardTeam/AdGuardHome/wiki/Docker

And prefer see some enhancement for the kb site https://kb.adguard.com to check each products and guides easily

https://support.google.com
https://cloud.google.com/java/docs

**Comment by ameshkov** [comment]
@ArchiveBase yeah, I think we should eventually do this. Not right now, though, AdGuard KB is under some rework at the moment.

**Comment by szolin** [comment]
Done

**Comment by ArchiveBase** [comment]
@szolin It seems ignored about windows users, isn't? https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset

**Comment by DandelionSprout** [comment]
As far as I can see, none of my suggested changes have been implemented *at all*, at least not in the GitHub wiki.

**Comment by ameshkov** [comment]
Hm, maybe we just forgot to push the changes.

@DandelionSprout @ArchiveBase please check the current version.

**Comment by DandelionSprout** [comment]
Okay, now it looks much better. Thanks!

**Comment by pcambra** [comment]
https://hostingcanada.org/htpasswd-generator/ has a bcrypt option now
