### ISSUE TITLE
Session cookie issue

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#1196]
When you have several websites on the same domain/ip where adguard UI is configured (I have directadmin on port 2222 and adguard on port 10000), logging into adguard is impossible (all the time 302 redirect back to /login.html). If I log out of DirectAdmin - I can login normally in AGH.

Suggest: rename "session" cookie to "agh_session" or add config option so we can name the cookie.

**Comment by ameshkov** [comment]
Makes sense, thank you!
