### ISSUE TITLE
DHCP Static leases bug

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#1197]
Running the latest version.

In Static DHCP leases only the first 20 entries are displayed in the table.
Everything after this is not shown anywhere.

**Comment by purpleax** [comment]
I am having exactly the same issue

**Comment by ameshkov** [comment]
@purpleax you should try the latest beta version:
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions
