### ISSUE TITLE
[Question] Few questions about encryption

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1198]
Hello,

unfortunately, i could not find such questions... I have few questions about encryption:
- how can I be sure that AGH uses **TLS 1.3** by default for DoT or how prioritize his version? OpenSSL 1.1.1 is required in this case?
- how can I be sure that AGH uses "**strict mode**" by default for DoT?
- how to be sure that AGH does not use vulnerable methods for DoT of ciphers or prioritize them (eg. ECDH+AESGCM:EECDH+CHACHA20)?
- what about **Rebind protection**? Is there any plan? I found only a mention of support
DNSSEC.

Thank you.

**Comment by ameshkov** [comment]
> 1. how can I be sure that AGH uses TLS 1.3 by default for DoT or how prioritize his version? 

By default, it uses the maximum available version

> OpenSSL 1.1.1 is required in this case?

No, AGH uses the standard Golang crypto library, no additional libraries are required.

> how can I be sure that AGH uses "strict mode" by default for DoT?

What do you mean by "strict mode"?

> how to be sure that AGH does not use vulnerable methods for DoT of ciphers or prioritize them (eg. ECDH+AESGCM:EECDH+CHACHA20)?

You cannot at least at this moment. This is worthy of a separate feature request - smth like "allow to configure TLS properties".

> what about Rebind protection? Is there any plan? I found only a mention of support
DNSSEC.

DNS rebinding is a threat to DNS recursive servers. AdGuard Home is a forwarding server so it cannot be a target of such an attack.

**Comment by LazyAspect** [comment]
@ameshkov, thank you for your answers!

> What do you mean by "strict mode"?

Can I be sure that AGH connected to the upstream servers ONLY in DoT mode - that all connections are encrypted? And he doesn 't connected to the upstream servers (Cloudflare, Quad9 etc.) in unprotected protocol for some reason. For example, DoT Stubby client supports this connection mode ("Opportunistic"):
https://dnsprivacy.org/wiki/display/DP/Configuring+Stubby

> DNS rebinding is a threat to DNS recursive servers. AdGuard Home is a forwarding server so it cannot be a target of such an attack.

I meant for the upstream servers (Cloudflare, Quad9 etc.). Sorry I didn 't specified right away...

**Comment by ameshkov** [comment]
There is no opportunistic mode in AG Home so yes, you can be sure.

> I meant for the upstream servers (Cloudflare, Quad9 etc.). Sorry I didn 't specified right away...

Well, we don't provide any special protection for that. In theory, we could provide a "Block internal IP addresses option" that will solve this. However, I'd keep it disabled by default anyway.
