### ISSUE TITLE
Need support huge Data !

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1199]
openwrt x64
kernel 4.19.81

When add blocklists over 500 lists,show me error:open too many files to.
need upgrade for support huge data
If the data files are too big ,the AD block maybe could not to effective .

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1180

**Comment by ameshkov** [comment]
You should configure your device to allow more open files than the default value:
https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1
