### ISSUE TITLE
luci-app-AdguardHome for openwrt

### ISSUE THREAD

**Issue by rufengsuixing** [AdguardTeam/AdGuardHome#1201]
https://github.com/rufengsuixing/luci-app-adguardhome/releases
any suggestions are welcome

**Comment by ameshkov** [comment]
Cool! Is there any way to translate this in English?

**Comment by rufengsuixing** [comment]
translate finish
https://github.com/rufengsuixing/luci-app-adguardhome/releases
![Screenshot_2019-11-25 newifi-d1-home - Base Setting - LuCI(2)](https://user-images.githubusercontent.com/22387141/69553514-43532b80-0fdb-11ea-8e28-2110f87e269a.png)

**Comment by ameshkov** [comment]
Great! Is there any place on Github where these translations are stored? I could pull request some changes or maybe even add a russian translation.

**Comment by rufengsuixing** [comment]
po file store the translate,English str is the tag,and you can add a new po file .i will help you to modify the Makefile

**Comment by ameshkov** [comment]
@szolin let's mention it in the README. Smth like this:

```
What's build with our API:

* Python library
* Hass.io add-on
* OpenWrt luci app

**Comment by phixion** [comment]
sorry for hijacking, are you looking for more translations?
