### ISSUE TITLE
Query Log doesn't show date

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdGuardHome#1202]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Now that AGH supports logging more than 24 hours of data the Query Log should display the date as well as the time for each row, at least for any request not made on the current day. At the moment the date is only shown in a tooltip when hovering over the time no matter how wide you drag the column. In the screenshot below I have filtered the log based on the IP address of a relative's smartphone, who last visited a few days ago. 

![image](https://user-images.githubusercontent.com/1901532/69492100-bf435b80-0e95-11ea-8b8a-59513fa59b29.png)

### Proposed Solution

Show the date for requests not made on the current day or for all requests, with a default column width suitable for displaying both date and time. This could be enabled for all users or dynamic based on the chosen data retention period, e.g. it's not entirely necessary for people who have their AGH set to 24 hours. 

### Alternatives Considered

It may also be nice to have a toggle setting for "always show date" vs. "show date for requests not made today" so people can choose how they want it displayed. I can't speak for everybody but I would find it much easier to notice when I reach the end of today's data while flicking through my Query Log if one request only shows a time and the next also shows the date. This would be beneficial when looking for suspect, missing, or expected requests, or when investigating a sudden increase in requests.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/624 (v0.101)

**Comment by Ultrabenosaurus** [comment]
@ArchiveBase I feel that this is different now. #624 is about Chinese localisation and was opened before AGH could support more than 24 hours of log retention. Now the log can contain more than 24 hours this should be high priority. 

I almost opened this as a bug instead of feature request as it feels like it was "missed" or "forgotten" when extended log retention was added.

**Comment by ArchiveBase** [comment]
@Ultrabenosaurus No. It'll implement suitable for all languages. I agree, it annoying for me too ^_^

> and was opened before AGH could support more than 24 hours of log retention. Now the log can contain more than 24 hours this should be high priority.

I asked milestone for that after released v0.99.0 https://github.com/AdguardTeam/AdGuardHome/issues/1095#issuecomment-544383625 however you can be check adguard home already display filters last time updated date.
