### ISSUE TITLE
Rearranging filters via AdGuardHome.yaml causes crash

### ISSUE THREAD

**Issue by apathyNot** [AdguardTeam/AdGuardHome#1204]
Just a heads up if anyone else encounters this.

AdGuardHome wont resolve DNS queries or start webserver if you rearrange the order of filters in AdGuardHome.yaml file.

No problems.
> ...
> filters:
> - enabled: true
>   url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
>   name: AdGuard Simplified Domain Names filter
>   id: 1
> - enabled: true
>   url: https://example.com/bad.txt
>   name: "01"
>   id: 1570462835
> ...

With problems as described above.
> ...
> filters:
> - enabled: true
>   url: https://example.com/bad.txt
>   name: "01"
>   id: 1570462835
> - enabled: true
>   url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
>   name: AdGuard Simplified Domain Names filter
>   id: 1
> ...

It looks like any filter id whose number is less then the previous filter id makes AdGuardHome not boot properly

...

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by apathyNot** [comment]
Closing for now as I can no longer reproduce. I'll come back with a log if it happens again.
