### ISSUE TITLE
unblocking 'www.google.com' doesn't change query log green

### ISSUE THREAD

**Issue by apathyNot** [AdguardTeam/AdGuardHome#1205]
The query log should change green when we unblock 'www.google.com'

Create new filter.
Name filter
Point URL to list that only contains
`@@|www.google.com^$important`

query log no green for 'www.google.com'

**Comment by ameshkov** [comment]
@apathyNot it will become green for new records. The rule was not applied to the previous DNS queries so they aren't highlighted.

**Comment by apathyNot** [comment]
@ameshkov yes it's not being applied for new records.

I turns out it's due to non-printing characters.. I use docs.google.com to store my filter lists. Well if you download the filter list and run the command in terminal to show non printing characters

> $ cat -e /path/to/file

output is

> M-oM-;M-?@@|www.google.com^$important^M$

**Comment by ameshkov** [comment]
Well, I think you should use a different place to store custom rules. Or just use Google Drive and  store a plain text file there.

**Comment by apathyNot** [comment]
@ameshkov it's only the first line that shows those non printing characters. A workaround is to just make sure the first line is always a comment (#). Thanks
