### ISSUE TITLE
[TLS] AdGuard DNS and AGH

### ISSUE THREAD

**Issue by cl0ud-o** [AdguardTeam/AdGuardHome#1208]
1. AdGuard DNS-over-TLS only work via domain tls://dns.adguard.com we are unable to use tls://176.103.130.130 similar google eg: tls://8.8.8.8 cloudflare eg: tls://1.1.1.1 what's the reason for not support via IP?

2. Could you enhance to only use DOT for both upstream and bootstrap with AGH? (configurable)

3. Why AGH allows to use any port number for bootstrap when use public DNS service IP for upstream?

**Comment by ameshkov** [comment]
> AdGuard DNS-over-TLS only work via domain tls://dns.adguard.com we are unable to use tls://176.103.130.130 similar google eg: tls://8.8.8.8 cloudflare eg: tls://1.1.1.1 what's the reason for not support via IP?

We'll see what can be done about this.

> Could you enhance to only use DOT for both upstream and bootstrap with AGH (mean only DOT)? 

In theory, we can allow adding DOT bootstrap.

@szolin dnsproxy already supports this. Can we port this to AGH? The only limitation is that bootstrap's address should have an IP address, not a domain name.

> Why AGH allows to use any port number for bootstrap when use public DNS service IP for upstream?

Ehm, why not?

**Comment by Onepamopa** [comment]
What's the point of DoT/DoH Bootstrap?!

**Comment by cl0ud-o** [comment]
@ameshkov > Ehm, why not?

Even 0? It seems doesn't matter to AGH what number set for bootstrap or only DNS server IP without port number but when use DOH for upstream, next meter the problem and return error for test upstream if i try any other port number than 53

**Comment by ArchiveBase** [comment]
Sorry about small thing: AGH consider bootstrap port number only when upstream address is a domain regardless DOH or DOT

**Comment by cl0ud-o** [comment]
> Ehm, why not?

Solved. it doesn't connect to cloudflare(default). recently i though AGH bug
