### ISSUE TITLE
Regex syntax question

### ISSUE THREAD

**Issue by LazyAspect** [AdguardTeam/AdGuardHome#1209]
Hello,

i want to block all subdomains **blog.** for all domains and create this rule:
/blog.*/

In this case also blocked subdomains like:
blogs. 
blogger.
blogging.
domain.blog.com
test.blogs.net.co
etc.

How do I properly write a regular expression to avoid this? How do I properly write a regular expression to avoid this?

Thank you.

**Comment by ameshkov** [comment]
Do you really need regex for this?

Why not `||blog.` ?

**Comment by LazyAspect** [comment]
> Do you really need regex for this?
> 
> Why not `||blog.` ?

Thanks for the answer, but I 'm not sure... I ask about regular expressions as Pi-Hole supports something similar:
https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list

**Comment by ameshkov** [comment]
I am not a fan of regular expressions.

Prefer adblock-style syntax when it's possible. It is easier to use and it will work much faster than regular expressions:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists
