### ISSUE TITLE
feedback problem about block AD

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1210]
Hostname | OPENWRT
-- | --
Model | Intel(R) Core(TM) i3 CPU @ 2.00GHz
CPU Info | 2018.775  MHz        +36.0°C
Firmware Version | OpenWrt 	LuCI Master (git-19.299.52050-0b735ea)
Kernel Version | 4.19.81

Install latest adguardhome,visit www.kan-tv.com,find a flash AD,check the servers from the AD,find 3 AD servers, so add the 3 AD servers in custom rule,but could not to block it.

If used dnscrypt-proxy or smartdns,could not find the AD ,need to check the DNS function within adguardhome,maybe add a button for user to close the DNS function.
If upgrade ,the DNS function like simple dnscrypt,used dnscrypt-proxy ,become more powerful and security.

![20191127093159](https://user-images.githubusercontent.com/17021524/69686042-6411a300-10f9-11ea-8ac5-67b801658ce8.png)

Need add a full adguard extension in adguardhome,support all of rules from filterlists.com,thank you!
Download filter files is failed ,show me more error,but check the Internet,could check version in adguardhome, and open websites is OK,so need add openssl-util,libsobium,libopenssl and more files,so need download used curl,wget within ssl/tls.
The full adguard extension in adguardhome is also help to download quickly.

**Comment by DavidTai780** [comment]
Have you block "chushoushijian.cn" ? this will totally fix the ads appears on "www.kan-tv.com".

![Screenshot (172)](https://user-images.githubusercontent.com/26398101/69692138-15213900-110c-11ea-8959-f128f13dbd76.png)

![Screenshot (170)](https://user-images.githubusercontent.com/26398101/69692155-1d797400-110c-11ea-9d0e-1ff1fca7e24d.png)

**Comment by jkle112** [comment]
Thank you.I have not to block "chushoushijian.cn",so I will add it in.
But the filter log was show me block count 0 after add over 200 domain filters in.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #176](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/176) via [**ZenHub**](https://www.zenhub.com/)
