### ISSUE TITLE
What is standard-block.dns.adguard.com

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#1213]
I don't know if this is the right place but what is `standard-block.dns.adguard.com` and why does AdGuard Browsing Security Web Service block access to it?

![image](https://user-images.githubusercontent.com/39284087/69739227-452e0380-112f-11ea-9fae-f688889f0d36.png)

**Comment by Cybo1927** [comment]
When I click 'More Information'...

![image](https://user-images.githubusercontent.com/39284087/69739539-c84f5980-112f-11ea-9e88-e5b011835db6.png)

**Comment by ArchiveBase** [comment]
Check using other DNS provider temporally then you'll realize it ;)
https://kb.adguard.com/en/general/dns-providers

**Comment by Cybo1927** [comment]
@ArchiveBase What do you mean?

Change this?
![image](https://user-images.githubusercontent.com/39284087/69749523-94316400-1142-11ea-9b66-d05a81a5b9f2.png)

**Comment by ArchiveBase** [comment]
Well, if necessary you can use other DNS server and disable browsing security service temporally to test it and sorry for not telling exact answer. I see it's only a static web page hosted by adguard.

**Comment by Cybo1927** [comment]
@ArchiveBase It's okay, I tested it and was confused because it did just appear to be a static page :)
