### ISSUE TITLE
AdGuard is using just one single upstream DNS server

### ISSUE THREAD

**Issue by NEOhidra** [AdguardTeam/AdGuardHome#1215]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.3
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * -
* **Operating system and version:**
  * CentOS 7

### Expected Behavior
Use "Upstream DNS servers" by the order they are defined

### Actual Behavior
Defined "Upstream DNS servers" are not used by the order they are defined

### Additional Information
Here is an example with two DNS servers: dns1 (192.168.1.1) and dns2 (192.168.1.101). Only dns2 can resolve "foo.bar"
If the "Upstream DNS servers" field is configured like so:
```
192.168.1.1
192.168.1.101
```
AdGuard cannot resolve "foo.bar". The same is valid if the order is reversed. The only way for AdGuard to resolve "foo.bar" is to remove dns1 from the list.

I assume that that AdGuard should query the DNS server one by one because of the existing option "Use parallel queries to speed up resolving by simultaneously querying all upstream servers".

**Comment by ameshkov** [comment]
AdGuard tries to use the fastest DNS server so the order is not defined.

In your example I'd suggest using this:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains
