### ISSUE TITLE
Safesearch / youtube blocked videos

### ISSUE THREAD

**Issue by peytonjol** [AdguardTeam/AdGuardHome#1216]
Hi there, thanks for adguardhome. I have an issue as i'm using safesearch but it blocked some youtube acceptable videos like music videos with nude like this 

https://www.youtube.com/watch?v=ufqbtwBSEis

When i was on pihole i used to put some extra on dnsmasq.conf to do the same but i had to delete restrict.youtube.com and restrictmoderate.youtube.com.
Will it be possible to choose which to enable like you do for blocking facebook/instagram and such hosts ? Thanks.

Extra : I want to put some extra safesearch to add in adguardhome:

host-record=safesearch.pixabay.com,176.9.158.70
cname=pixabay.com,safesearch.pixabay.com

host-record=safe.duckduckgo.com,54.241.17.246
cname=duckduckgo.com,www.duckduckgo.com,start.duckduckgo.com,safe.duckduckgo.com
cname=duck.com,www.duck.com,safe.duckduckgo.com

Cheers :)
Thanks.

**Comment by ameshkov** [comment]
1. Regarding Youtube, please upvote this feature request: https://github.com/AdguardTeam/AdGuardHome/issues/1163

> Extra : I want to put some extra safesearch to add in adguardhome:

You can pull request it here:
https://github.com/AdguardTeam/AdGuardHome/blob/master/dnsfilter/safesearch.go

If I am not wrong, it's already there though

**Comment by peytonjol** [comment]
My mistakes. Sorry.. :)
