### ISSUE TITLE
[Question] What are DNS Rewrites and how are they used?

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#1217]
I don't quite understand what a DNS Rewrite is, would be nice if you could also update the Wiki to explain. If possible please provide an example. Thanks!

**Comment by ameshkov** [comment]
Well, it lets you configure a CNAME and/or A/AAAA response for a given domain name.

Basically, it lets you redirect a domain name to another domain name or a different IP address.

**Comment by Cybo1927** [comment]
Ah, Thank you!
