### ISSUE TITLE
UI: "clients"-related improvements

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1218]
1. Add Client ID validation (IP (4 & 6), CIDR, MAC)

**Comment by ArtemBaskal** [comment]
Fixed in 28096d696602485baaa7dbb8a43413a5310435d4

**Comment by szolin** [comment]
On the latest master branch:
<img width="636" alt="" src="https://user-images.githubusercontent.com/38690158/71587330-49827d80-2b2e-11ea-8a67-0079983100d4.png">

`/clients/find` cache doesn't work when filtering by client IP

**Comment by ameshkov** [comment]
On second thought, let's get rid of the clients cache
