### ISSUE TITLE
Extract the client's IP address from HTTP headers in case of a reverse proxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1220]
See the details here:
https://github.com/AdguardTeam/AdGuardHome/issues/1219

Obviously, when AdGuard Home is behind a reverse proxy, we don't see the true user IP address. We should rely on HTTP headers in this case.

Here's the list of headers we should check:

* `CF-Connecting-IP` and `True-Client-IP` (for [Cloudflare](https://support.cloudflare.com/hc/en-us/articles/206776727-What-is-True-Client-IP-))
* `X-Real-IP`
* `X-Forwarded-For`

**Comment by jostyee** [comment]
@szolin why close this issue, no plan to implement it any more?

**Comment by szolin** [comment]
It's fixed in dnsproxy repository and will be available in AGH v0.100!

**Comment by jostyee** [comment]
Thank you.
