### ISSUE TITLE
90 day Query Log & Blocked malware/phishing attacks listing. !?

### ISSUE THREAD

**Issue by nurb2kea** [AdguardTeam/AdGuardHome#1221]
Hi,

-- How to view a complete 90 day Query Log & NOT only for the actuall day, but all of it, and sorted by date?
-- And where to find Blocked malware/phishing attacks listed in the Query Log. ?
Aren't they are color coded ?

Would be super usefull to have this options, to narrow down the attacks URL/IP and block them in the first palce!

I'm on Version: v0.99.3 Mac running as a service

Thanks in advance

**Comment by ArchiveBase** [comment]
> sorted by date?

https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-515673586 and extended options https://github.com/AdguardTeam/AdGuardHome/issues/1164 https://github.com/AdguardTeam/AdGuardHome/issues/594#issuecomment-469129412

> where to find Blocked malware/phishing attacks listed in the Query Log. ?
Aren't they are color coded ?

https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911 (#882 you can add comment about color)

**Comment by nurb2kea** [comment]
> > sorted by date?
> 
> [#481 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-515673586) and extended options #1164 [#594 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/594#issuecomment-469129412)
> 
> > where to find Blocked malware/phishing attacks listed in the Query Log. ?
> > Aren't they are color coded ?
> 
> [#882 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911) (#882 you can add comment about color)

Hi, what kind of answer is that??

**Comment by ArchiveBase** [comment]
Well :) You cannot sort query log as mentioned above using current adguard home version but those features will be added soon.

> How to view a complete 90 day Query Log & NOT only for the actuall day, but all of it, and sorted by date?

Read https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-515673586, https://github.com/AdguardTeam/AdGuardHome/issues/1164, https://github.com/AdguardTeam/AdGuardHome/issues/594#issuecomment-469129412 and if necessary, you can describe further enhancements

> And where to find Blocked malware/phishing attacks listed in the Query Log. ?
Aren't they are color coded ?

https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911 however you may need to add comment about specific color for each filters.

**Comment by szolin** [comment]
Almost all querylog tasks are already mentioned in #481
