### ISSUE TITLE
fetch HTML filter

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1223]
- [YES ] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES ] I checked to make sure that this issue has not already been filed

### Problem Description
Error: control/filtering/add_url | Couldn't fetch filter from url https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus;showintro=0: Data is HTML, not plain text | 400

**Comment by ameshkov** [comment]
Well, this is an HTML file, check the source code:
`view-source:https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus;showintro=0`

Look for a plain text version of it
