### ISSUE TITLE
Что происходит при блокировке запроса?

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1224]
Когда фильтр блокирует запрос ДНС, клиент в ответ на запрос получает некий ответ ( например: {"IP":"192.168.68.250","T":"2019-11-20T13:20:57.710746034+03:00","QH":"evoke-windowsservices-tas.msedge.net","QT":"A","QC":"IN","Answer":"ermBgwABAAAAAQAAGWV2b2tlLXdpbmRvd3NzZXJ2aWNlcy10YXMGbXNlZGdlA25ldAAAAQABwAwABgABAAAACgBIGWZha2UtZm9yLW5lZ2F0aXZlLWNhY2hpbmcHYWRndWFyZANjb20ACmhvc3RtYXN0ZXLADAABiJQAAAcIAAADhAAJOoAAAVGA","Result":{"IsFiltered":true,"Reason":3,"Rule":"||msedge.net^","FilterID":1571432283},"Elapsed":467342})
Что этот код означает? Это значит, что клиент не получит ответ и он обратится ко второму ДНС серверу или клиент получает ответ и не обращается ко второму ДНС серверу?

**Comment by ameshkov** [comment]
Клиент получает ответ, пытается приконнектится по полученному адресу, но так как там никто не ожидает ответа - соединение не удается.
