### ISSUE TITLE
The AD server is upgrading

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1225]
openwrt x64,
filter list is update,but the ad server is also upgrading,so could not to deal with it.
![Image 1](https://user-images.githubusercontent.com/17021524/69966935-5a9d9600-1552-11ea-828b-f981ef7a456d.png)

**Comment by jkle112** [comment]
need to check www.juji.tv

**Comment by szolin** [comment]
What's your question?

**Comment by DavidTai780** [comment]
ads on www.juji.tv is injected by the js from http://www.juji.tv/Runtime/js/vodlist_cpv.js
The ads server address is :
631.dlads.cn
pc.gutouwang.net
pc.5151gj.com
Analaysis and Tracking server:
s23.cnzz.com


This kind of ads injection with the javascript from it's own site is hard to block, they will change the address for a short period. You should use the AdGuard Blocker Browser Extension and activate Easylist China. Easylist China and other Easylist would easily help you to block ads, their filters rules are always updated.

**Comment by jkle112** [comment]
Hope AdGuardHome upgrade to deal with them.
![Image 0](https://user-images.githubusercontent.com/17021524/71391309-9225cc80-263e-11ea-83cd-406593e190b8.png)


![Image 1](https://user-images.githubusercontent.com/17021524/71391315-96ea8080-263e-11ea-84c4-4f3069cfdae9.png)

**Comment by ArchiveBase** [comment]
>@DavidTai780
This kind of ads injection with the javascript from it's own site is hard to block by AdGuardHome, they will change the address for every short period or you have to update the ads server address when there is any change on the domain name of ads server. You should use the AdGuard Blocker Browser Extension and activate Easylist China. Easylist China and other Easylist would easily help you to block ads, their filters rules are always updated.

However suggest if there any,
> @ameshkov Yeah, it's time indeed.
Marked as "help wanted" -- please suggest other lists here. #1325

**Comment by DavidTai780** [comment]
I think the rules for easylist china is based on extension and it match the url not the domain. Usually those ads server use same system but different server. I am no idea for the new ads server. Maybe adguard can create a filter rules for special ads server from china and give some management privileges to a few advanced users to maintainance.

**Comment by jkle112** [comment]
If adguardhome upgrade like adguard extension in Firefox/Chrome,that could deal with them.
If could not do it ,I will used another adblock tool to kill them.
Thank you!

**Comment by ArchiveBase** [comment]
@jkle112 @DavidTai780 that will be possible with the help of a MITM proxy when https://github.com/AdguardTeam/AdGuardHome/issues/391 is ready
