### ISSUE TITLE
Ability to check which Malware/Phishing site was blocked

### ISSUE THREAD

**Issue by bostonnm21** [AdguardTeam/AdGuardHome#1231]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Yes ] I am running the latest version
- [Yes] I checked the documentation and found no answer

### Problem Description
Ability to check which Malware/Phishing site was blocked. This will help me isolate which app on my phone or laptop might be under or exposed to attack. Would be nice if link can be opened by clicking on Dashboard for Malware/Phishing.

And most importantly thanks for creating such a nice and easy to use/understand product

**Comment by ameshkov** [comment]
This is a part of https://github.com/AdguardTeam/AdGuardHome/issues/882
