### ISSUE TITLE
AdGuard Home Crash/Hangs while updating filters

### ISSUE THREAD

**Issue by bostonnm21** [AdguardTeam/AdGuardHome#1232]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.99.3

* **Operating system and version:**
  * Debian GNU/Linux 7 \n \l
* PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
* NAME="Debian GNU/Linux"
* VERSION_ID="7"
* VERSION="7 (wheezy)"

### Expected Behavior
* While filter update is in progress AdGuard home should continue to be available and serve DNS request.

### Actual Behavior
* While filter update is in progress AdGuard home should becomes unresponsive/Hangs and  DNS request goes unresolved/Dead internet

### Additional Information
* I have about 25 Filter URL and I noticed that some of them take long time to update which might be the reason for AdGuard Home to hang. If I un-check few big ones and then run update, it completes.
* Was thinking if we can with have a timeout or way to update filters in Batches , might help.

**Comment by ameshkov** [comment]
Could you please post the list of your filters from AdGuardHome.yaml? This will help us reproduce the issue.

**Comment by bostonnm21** [comment]
url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter

  url: https://adaway.org/hosts.txt
  name: AdAway

  url: https://hosts-file.net/ad_servers.txt
  name: hpHosts - Ad and Tracking servers only

  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List

  url: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
  name: dnsmasq

  url: https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
  name: dnsmasq

  url: https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt
  name: Spam404

  url: https://www.fanboy.co.nz/enhancedstats.txt
  name: Fanboy's Enhanced Tracking List

  url: https://easylist-downloads.adblockplus.org/easylist.txt
  name: EasyList

  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
  name: uBlock filters – Badware risks

  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
  name: uBlock filters

  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
  name: uBlock filters – Privacy

  url: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
  name: uBlock filters – Resource abuse

  url: https://raw.githubusercontent.com/abpvn/abpvn/master/filter/src/abpvn_general.txt
  name: dnsmasq

  url: https://raw.githubusercontent.com/szpeter80/hufilter/master/hufilter.txt
  name: hufilter

  url: https://easylist-downloads.adblockplus.org/advblock.txt
  name: RU AdList

  url: https://raw.githubusercontent.com/yous/YousList/master/youslist.txt
  name: YousList

 url: https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt
name: dnsmasq

url: https://filters.adtidy.org/extension/chromium/filters/11.txt
name: AdGuard Mobile Ads filter

  url: https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt
  name: AdBlockID

  url: https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/UnitedStatesofAmerica.txt
  name: Pi-hole Parser - United States of America

  url: https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
  name: Pi-hole Parser - United States of America

**Comment by ameshkov** [comment]
Hmm, nothing too problematic.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by bostonnm21** [comment]
Sure.. here is log file.

[AdGuardHome_Debian.log](https://github.com/AdguardTeam/AdGuardHome/files/3940292/AdGuardHome_Debian.log)

FYI- Today Application didn't crashed while updating filters. It did crashed just before when I didn't had log file specified.

Thanks again.

**Comment by szolin** [comment]
Please reopen the issue when the problem appears again.

**Comment by bostonnm21** [comment]
Please reopen this issue as application crashed today. UI was hung while updating and NO dns request was getting answered. Logs attached.

[AdGuardHome_Debian.zip](https://github.com/AdguardTeam/AdGuardHome/files/3947298/AdGuardHome_Debian.zip)

**Comment by szolin** [comment]
> UI was hung while updating 

It's normal - the update process takes time!

> NO dns request was getting answered

I don't see it in logs - everything seems normal.  What DNS requests were not answered exactly?

**Comment by bostonnm21** [comment]
I opened google.com and few other random sites and none were working(Timeout error), once I rebooted device all came back to normal.

My internet was fine during this time as devices that doesn't use AdGuard Home were working fine.

**Comment by ameshkov** [comment]
Most of the errors in the log are not about filter lists, there's an `i/o timeout` error as if something was wrong with the network access in general

**Comment by ameshkov** [comment]
@szolin there's another issue in the log: `2019/12/10 14:18:18 22970#202453 [info] Couldn't write config file: Couldn't start forwarding DNS server, cause: could not reconfigure the server, cause: couldn't listen to UDP socket, cause: listen udp x.x.x.x:53: bind: cannot assign requested address`

But I assume it will be fixed in v0.100.
