### ISSUE TITLE
my DNS log time is incorrect. how to correct it ?

### ISSUE THREAD

**Issue by norikohxb** [AdguardTeam/AdGuardHome#1233]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdGuardHome/issues/1234
