### ISSUE TITLE
short domain that resolves to AdGuardHome IP Address

### ISSUE THREAD

**Issue by shreyu86** [AdguardTeam/AdGuardHome#1238]
It would be great to add a easy to remember domain such as `ad.guard` which points to the AdGuardHome Web UI serving stats and configuration options. Currently have to remember/bookmark the AdGuardHome server IP address. Since AdGuardHome is installed and it owns the DNS lookups it can resolve `ad.guard` to the host IP. This is very similar to `pi.hole/admin` where the pihole resolves to the host ip.

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/717

**Comment by ameshkov** [comment]
Temporary solution: you can do this by adding a DNS rewrite manually.

**Comment by shreyu86** [comment]
Thanks for the workaround suggestion @ameshkov
