### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1240]
openwrt x64
install adguardhome ,watch video is not very well,but add more extensions in Firefox that to deal with cookies and security scripts,video play is become very well,so need adguardhome add more feature like :tampermonkey,privacy badger, adgurad adblocker,location guard,foxyproxy standard, privacy badger,noscript ,scriptsafe,https everywhere /smarthttps
hope do it more better,thank you!

**Comment by ameshkov** [comment]
Hehe, well, that's a lot to do, but thanks for mentioning all of them anyway, we might be able to implement some of that.
