### ISSUE TITLE
Apply certain filters to certain clients only

### ISSUE THREAD

**Issue by FM1337** [AdguardTeam/AdGuardHome#1241]
### Problem Description
I want to create a filter list to apply to one client on my network but there doesn't appear to be a way to do that. You can configure clients to use all filters individually but not certain filters (e.g pick and choose unless you do it globally which affects all clients unless you specifically set it so that it uses no filters at all thus making this pointless to even have installed)

### Proposed Solution
Under the modal dialog that you have when adding a new client
![image](https://user-images.githubusercontent.com/5448220/70382978-f3aa2380-193b-11ea-89ad-025d9a999681.png) (this one) add an option to select specific filter lists or maybe even a text area to specify which domains to block.

### Alternatives Considered
Setting up a separate DNS server for this one purpose but this is kinda overkill.

### Additional Information
N/A

**Comment by ArchiveBase** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/435
(usable ways! tags* https://github.com/AdguardTeam/AdGuardHome/issues/817#issuecomment-534275463  entries* https://github.com/AdguardTeam/AdGuardHome/issues/1081)

**Comment by ameshkov** [comment]
Marked as dup
