### ISSUE TITLE
Filter is too slow

### ISSUE THREAD

**Issue by leonardwu** [AdguardTeam/AdGuardHome#1242]
If I use Block domains using filters and hosts files DNS query will be too slow
but CPU and RAM is not high

**Comment by ameshkov** [comment]
Could you please give us more details? I don't understand the question.

**Comment by leonardwu** [comment]
When I turned on the filter, the DNS query became significantly slower.Then I felt that the DNS results were not cached.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by Colin-XKL** [comment]
Disable safebrowse if you don't have a fast and stable connection to the Adguard server.  
![image](https://user-images.githubusercontent.com/49122401/71183741-7bd0e700-22b3-11ea-9c36-cdee77c11b77.png)

**Comment by ArchiveBase** [comment]
> Disable safebrowse if you don't have a fast and stable connection to the Adguard server.

@Colin-XKL did you see https://github.com/AdguardTeam/AdGuardHome/issues/525#issuecomment-520482071? however @leonardwu problem not related to that.
