### ISSUE TITLE
ubuntu will make AdguardHome time incorrect each reboot

### ISSUE THREAD

**Issue by norikohxb** [AdguardTeam/AdGuardHome#1243]
I installed  ubuntu-18.04.3-live-server-amd64 and then install ADGH
at first the time is correct
but each time I reboot Ubunto the time will automatically adjusted to 8 hours later and it will cause my AdguardHome log time incorrect
any one kindly teach me how to correct it

**Comment by norikohxb** [comment]
the AdguardHome has DNS Log history and the time will be different with my local time . it is because when Ubunto each reboot it will modify my ubuntu service time.
so my AdguardHome DNS log time will always incorrect.

**Comment by rufengsuixing** [comment]
windows and linux systems in one computer?

**Comment by norikohxb** [comment]
vmware esxi. system is correct Chinese time. there are ROS  and Openwrt on it . they are all work normally the time is Chinese time. but Utunbu each reboot first 1 minutes the time is mistake and 1 minutes later it will auto correct to Chinese time. but  the AdguardHome start up within the first 1 minute and will use the mistaken time. as the DNS log time stamp

**Comment by norikohxb** [comment]
i close it because those mistake caused by my ESXI's wrong time zone and wrong time
and cause this issue.
