### ISSUE TITLE
[QUESTION] 5 filters with 10K rules or 1 filter with 50K rules

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1244]
При какой настройке AGH будет работать быстрее и эффективнее из двух вариантов:
1) 7 фильтров по 10тыс правил (некоторые правила могут дублироваться)
2) 1 фильтр, в котором все эти 70тыс. правил с исключенными дубликатами
?

**Comment by ameshkov** [comment]
Совершенно никакой разницы между этими вариантами не будет.
