### ISSUE TITLE
Add "Required-Start: $network" to the sysv init script

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1246]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Problem Description

I install ADG at my OpenWrt router which use a USB drive, and I set work dir in `/var` which is `tmpfs` to avoid too much writing. like #876 
I found ADG did not function when I restart my router, I check log and found the reason. ADG start before network ready, ADG only try once at the beginning and do nothing when network not ready, so it will **run without any rule** until next update interval.
### Proposed Solution

Add retry time or interval when cannot download rule file correctly. 

### Additional Information

<details> 
<summary>Log Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/22477230/70436129-8c1ee000-1ac3-11ea-9c49-b7e7e62de057.png)  
</details>

**Comment by ameshkov** [comment]
Hm, AdGuard service should not start until the network is ready.

@szolin have we made this change in v0.100 or v0.99?

**Comment by szolin** [comment]
in v0.99
But we only made it for systemd service.  OpenWrt may use another service mechanism.

**Comment by Mosney** [comment]
> in v0.99
> But we only made it for systemd service. OpenWrt may use another service mechanism.

Yep, OpenWrt use /etc/init.d

**Comment by Mosney** [comment]
ref #1201 , 
I also open an issue in [luci-app-adguardhome](https://github.com/rufengsuixing/luci-app-adguardhome/issues/23), and dev talk to me it is limited can luci do.
In addition, ADG as a DNS resolver in OpenWrt listen port 53, run without rule not a big problem, totally not run may not good thing. So, I think ADG add some retry mechanism better than delay run.

**Comment by ameshkov** [comment]
I wonder is that possible with simply changing the service configuration?

**Comment by rufengsuixing** [comment]
ifup don`t means network is ready ,maybe need to run pppoe.So i will add a ping test on boot start

**Comment by Mosney** [comment]
> I wonder is that possible with simply changing the service configuration?

Maybe can add some conditional delay. But I still think **retry after failure** is essential for a program.

**Comment by ameshkov** [comment]
I really don't think this is a good solution.

We should instead add `Required-Start: $network` to the sysv script.

@szolin check the kardianos/service code, it allows redefining the sysv script.

**Comment by Mosney** [comment]
About service, I had tried `./AdGuardHome -s install` in OpenWrt before I use [luci-app-adguardhome](https://github.com/rufengsuixing/luci-app-adguardhome). And it is not compatible with OpenWrt's `init.d`(ref:https://openwrt.org/docs/techref/initscripts). But it is not a problem until ADG supports OpenWrt officially.

**Comment by rufengsuixing** [comment]
if support init.d,there must be a lot of args to fill,a luci is needed.Maybe  ADG supports OpenWrt officially can do better than me.

**Comment by ameshkov** [comment]
@rufengsuixing does OpenWrt support `Required-Start: ` directive? If so, it makes sense to add `Required-Start: $network` there as well

**Comment by rufengsuixing** [comment]
> @rufengsuixing does OpenWrt support `Required-Start: ` directive? If so, it makes sense to add `Required-Start: $network` there as well
![IMG_20191210_164732](https://user-images.githubusercontent.com/22387141/70513891-7665f500-1b6d-11ea-9f16-fdfa2cf5f5a3.jpg)
you can see from here, k means kill ,s means start.
adH is the s95 after the s20 network ,but still ,because network is ok not means the network can be access to the internet,may need to have pppoe dial or something else,such as Internet authentication need usr to enter the username and password

**Comment by rufengsuixing** [comment]
i can make Adg restart every ifup,but there will be a lot of meanless restart

**Comment by ameshkov** [comment]
I've just realized that the original issue is not about network - it is about `tmpfs` access at the moment when AGH starts.

Can't it be handled by modifying the AGH init script -- adding tmpfs initialization there

**Comment by rufengsuixing** [comment]
it is about download rules failed retry interval.
tmpfs always can be access,maybe after fstab

**Comment by Mosney** [comment]
@ameshkov `tmpfs` always can be accessed, but no rule files after reboot, so the original issue is 
> ADG start before network ready, ADG only try once at the beginning and do nothing when network not ready, so it will run without any rule until next update interval.

**Comment by ameshkov** [comment]
Quick question: can you backup the rules from tmpfs to normal FS and restore it on device startup?

**Comment by rufengsuixing** [comment]
i can and in my luci project i had added it

**Comment by szolin** [comment]
We can't be sure the network is available when AGH is starting, that's why we just need to fix the filters downloading mechanism.  I think we can use a smaller time interval (starting at 5 sec and growing up to an hour which is by default now).

**Comment by Mosney** [comment]
> We can't be sure the network is available when AGH is starting, that's why we just need to fix the filters downloading mechanism. I think we can use a smaller time interval (starting at 5 sec and growing up to an hour which is by default now).

Looks good, just what I said at first, 

> Add retry time or interval when cannot download rule file correctly.

It's a similar solution.
