### ISSUE TITLE
Infinity loop with safebrowsing enabled

### ISSUE THREAD

**Issue by maxtar** [AdguardTeam/AdGuardHome#1247]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.99.3
* **How did you setup DNS configuration:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  *  raspbpi 4.19.66
### Actual Behavior
I enabled SafeBrowsing by web-gui configuration after installation AdGuardHome to my Raspberry Pi couple days ago.
Today after connecting my work notebook to Home Wifi I have stack of Internet.
After diagnosic I noted that AdGuardHome consuming 100% CPU on RaspberryPi. 
In systemd logs on I sow the folloiwng errors:

### Logs
<details><summary>Log:</summary>
Failed to do safebrowsing HTTP lookup, ignoring check:  Get https://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=7CF261FC/8E39D0A0/: dial tcp *.*.*.*:443: socket: too many open files
</details>

### Additional Information
I found that the same problem was fixed in [732](https://github.com/AdguardTeam/AdGuardHome/issues/732)
Maybe need to add LimitNOFILE= to service file? Or what is problem?

**Comment by szolin** [comment]
SafeBrowsing is changed completely in #525 
It's included in the upcoming v0.100 release.
