### ISSUE TITLE
Treat "://example.org" as "||example.org"

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1249]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.99.3)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I've noticed that some EasyList-hosted lists have a decently big handful of domains-blocking entries that start with `://`, for some reason that is difficult to figure out (e.g. `://cdn.ad.` in Liste FR).

### Proposed Solution

Would it be possible to treat entries that start with `://`, `https://`, and/or `http://` as aliases of `||`?

If all three get accepted (while also disregarding `/`'s that show up at the very end of entries), that'd presumably also give AdGuard Home some very limited support for whole-URLs lists (e.g. https://raw.githubusercontent.com/MrThreat/Confirmed-Phish/master/phish.txt).

### Alternatives Considered

I suppose that treating them as pure domains instead of `||`-type entries is a plausible alternative.

### Additional Information

Liste FR and EasyList seem to be the only two lists to deploy `://` entries on a large scale. But since they're among the perhaps 10 most popular lists in the world, I suppose it'd be a good idea to support such entries.

For end-users who are short on time, I aim to convert such entries through a .py file tonight or tomorrow (12th of December) for use in [my makeshift conversion list for AdGuard Home](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt).

**Comment by ameshkov** [comment]
@szolin I guess we can add special treatment for rules starting with `://`, `http://` or `https://`

**Comment by DandelionSprout** [comment]
It looks to me like the issue wasn't properly closed by the request, so I'll take care of closing it instead. 💚

**Comment by ameshkov** [comment]
Wait-wait, too early. The fix was made in the urlfilter library, but we should also start using this new version in AGH.

**Comment by ameshkov** [comment]
Bad bot

**Comment by ameshkov** [comment]
Done: https://github.com/AdguardTeam/AdGuardHome/commit/4808b33c01cbaf573ed7002ee9160f290d7200fb

**Comment by DandelionSprout** [comment]
Okay, so as of v0.100.8, `http://example.org/` and `://example.org/` successfully blocks the domain, whereas `https://example.org/` does *not*, for some reason that I can't seem to be able to figure out, especially since the https://github.com/AdguardTeam/urlfilter/blob/master/rules/network_rule.go#L393 section seems completely normal to me.

Same situation applies when replacing `example.org` with `example.com` or `www.nrk.no`.

**Comment by ameshkov** [comment]
@DandelionSprout the problem is that internally it matches with `http://exampe.org`, not `https://`.
