### ISSUE TITLE
How to build from source for Windows?

### ISSUE THREAD

**Issue by tinykidpro** [AdguardTeam/AdGuardHome#1254]
I have downloaded the source and edited some translation parts for the language.
I need to rebuild it to an installable version on **Windows** or **ARM**
Help me tell me what command to use to build?
**Thank all!**

**Comment by ameshkov** [comment]
You can simply run `make`

**Comment by tinykidpro** [comment]
thank for help me!!! I need to build it as a .exe file, i;m using ubuntu 18 to build it and I need to run it on Windows Server 2012

**Comment by ameshkov** [comment]
Ah, then it's easier, simply run `./release.sh` -- it will build dists for all platforms in the `dist` folder

**Comment by tinykidpro** [comment]
> Ah, then it's easier, simply run `./release.sh` -- it will build dists for all platforms in the `dist` folder

thank u very much
