### ISSUE TITLE
incoherence value between agguard home & homeassistant

### ISSUE THREAD

**Issue by byackee** [AdguardTeam/AdGuardHome#1258]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.99.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Synology RT2600
* **Operating system and version:**
  * Debian 9

### Expected Behavior
Innocence value between Adguard home UI & home assistant. It is just pb of unit I think

### Screenshots

In Home assistant
<img width="430" alt="Capture d’écran 2019-12-14 à 10 57 23" src="https://user-images.githubusercontent.com/4707496/70847145-22a32680-1e61-11ea-9f37-05821b83109b.png">

In Adguard Home
<img width="576" alt="Capture d’écran 2019-12-14 à 10 57 36" src="https://user-images.githubusercontent.com/4707496/70847146-246cea00-1e61-11ea-8724-7cc9d045a296.png">

**Comment by ameshkov** [comment]
@frenck it seems that something is wrong on your side?

**Comment by frenck** [comment]
Yes, this is an issue for Home Assistant, already reported and tracked here:

<https://github.com/home-assistant/home-assistant/issues/28437>

This issue is not for you guys, so can be closed.

**Comment by ameshkov** [comment]
Thank you!
