### ISSUE TITLE
[feature request] Some special TLD check DHCP leases first to support LAN host

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1260]
I noticed DNS query like `hostname.local` also has been forward to upstream DNS, it will return NXDOMAIN generally, and will make some annoying especially both side have no mDNS support.

In the OpenWrt DNS query logic (just an example), it should check the local network host like `DHCP leases file` first, but the question is ADG doesn't as a DHCP server normally (its DHCP feature too simple to use), so it cannot know DHCP leases in the local network normally.

ref:https://openwrt.org/docs/guide-user/base-system/dhcp (All option > domain part)

**Some possible resolution:**
- Set some special TLD (like 'lan' 'local') first check DHCP leases via DNS query to DHCP server.
- Enhance DHCP section and develop it to the full function DHCP server.

**Comment by Mosney** [comment]
**Give a solution for mDNS query leaked to DNS before ADG enhance this. Not elegant but work.** 
Deploy another nameserver as ADG unique upstream. It can be dnsmasq, [SmartDNS](https://github.com/pymumu/smartdns), or something else.

And for SmartDNS, you can take advantage of its powerful features, to this issue, check  `DNS query diversion` which in FAQ No.6. In my instance, I set all `.local` query forward to dnsmasq which is OpenWrt original DNS provider and DHCP server. 
<details> <summary> Screenshot of the previous settings </summary>   

![image](https://user-images.githubusercontent.com/22477230/70863845-58dac600-1f87-11ea-9399-426d9513fd05.png)  

![image](https://user-images.githubusercontent.com/22477230/70863848-67c17880-1f87-11ea-9ed5-515a203c7b1e.png)
![image](https://user-images.githubusercontent.com/22477230/70863854-76a82b00-1f87-11ea-92a7-c2e787736665.png)
</details>

**Comment by szolin** [comment]
Can't you just rewrite all queries to `*.local` using Upstreams settings?

**Comment by Mosney** [comment]
> 
> 
> Can't you just rewrite all queries to `*.local` using Upstreams settings?

Yes, I can, but like I said above, it is not elegant and user-friendly. 
Not only incompatible with mDNS/ZeroConfig but also AGH cannot get the host name via rDNS/PTR correctly. 
I think it is easy to add an advanced option to setting some special TLD to use a special NS like router-self (which has the DHCP leases), and there is no necessary to enhance DHCP part cause it is too complex and many work needs to been done.

**Comment by szolin** [comment]
rDNS rulles can be configured using the same Upstreams settings - just set which upstream server should respond to PTR requests for your IP addresses.

As I see you've got 2 issues here:

1. You don't want A requests for `*.local` to be passed through to a real upstream server.
This can be resolved by Upstreams settings.

2. You want your local IP addresses to be resolved via rDNS into host names by your local DNS server (that is not AGH).
This can also be resolved by Upstreams settings.

Or am I missing something?

**Comment by Mosney** [comment]
I’m so sorry i didn’t notice AGH already can specify upstream for domain, my wrong.
And also refer relative document link below for some potential “big eye guys ” like me.
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains
