### ISSUE TITLE
Link-local IPv6 identifier in client list seems to be ignored

### ISSUE THREAD

**Issue by NullEnt1ty** [AdguardTeam/AdGuardHome#1261]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.99.3-125-gd9ee
  * Docker Image Tag: `adguard/adguardhome:armhf-edge`
  * Docker Image Digest: `sha256:6e77a52a48720aad95ae73d517c3f0a2dd1b16853e9f60fe893df06bcefcd95e`
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * FRITZ!Box 7590
* **Operating system and version:**
  * Windows 10 1909

### Expected Behavior
A client identified by its IPv6 address should act according to the client settings. In my case I disabled "Use global settings" to stop filtering DNS requests for a specific client.

### Actual Behavior
DNS requests, which were send via IPv6, are still getting filtered. IPv4 DNS requests are fine though.

### Screenshots
<details><summary>Screenshot: 
</summary>

Client settings:
![client settings](https://user-images.githubusercontent.com/966433/70861270-e7b9f500-1f2b-11ea-9651-4bc1c0068140.png)

Blocked IPv6 request:
![blocked request](https://user-images.githubusercontent.com/966433/70861333-b55cc780-1f2c-11ea-8d21-e89bcb3291e0.png)

Allowed IPv4 request:
![allowed request](https://user-images.githubusercontent.com/966433/70861348-d1606900-1f2c-11ea-861d-a69c75a0ed87.png)

</details>

### Additional Information
The usage of IPv6 identifier [was added just recently](https://github.com/AdguardTeam/AdGuardHome/commit/db703283ba4b2e6f32e73b69902cd611dd372fe7). It seems to work in the "frontend" as my client is recognized and associated with its friendly name, but not in the "backend" as my requests are still getting blocked.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by NullEnt1ty** [comment]
Using IPv4:

```
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(): Start handling new UDP packet from 192.168.188.96:54490
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 2
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;a.matterncorp.de.	IN	 A

2019/12/15 11:39:05 1#640 [debug] Using settings for client with IP 192.168.188.96
2019/12/15 11:39:05 1#640 [debug] Using upstreams [] for client dominique-pc (IP: 192.168.188.96)
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*TLSPool).Get(): Returning existing connection to 1.1.1.1:853 with updated deadLine
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverTLS).Exchange(): The TLS connection is expired due to Failed to send a request to 1.1.1.1:853, cause: write tcp 192.168.188.2:50122->1.1.1.1:853: write: broken pipe
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): Dialing to 1.1.1.1:853
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): dialer has successfully initialized connection to 1.1.1.1:853 in 6 milliseconds
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream 1.1.1.1:853 successfully finished exchange of ;a.matterncorp.de.	IN	 A. Elapsed 341 ms.
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 341 ms
2019/12/15 11:39:05 1#640 [debug] DNSFwd: Checking record A (193.31.24.80) for a.matterncorp.de.
2019/12/15 11:39:05 1#640 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 2
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;a.matterncorp.de.	IN	 A

;; ANSWER SECTION:
a.matterncorp.de.	86400	IN	A	193.31.24.80
```

Using IPv6:

```
2019/12/15 11:34:25 1#93 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(): Start handling new UDP packet from [fe80::ad94:87b3:c8a5:7cba%eth0]:64247
2019/12/15 11:34:25 1#93 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 2
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;a.matterncorp.de.	IN	 A

2019/12/15 11:34:25 1#93 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).matchHost(): 1 rules matched for host 'a.matterncorp.de'
2019/12/15 11:34:25 1#93 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).matchHost(): Found rule for host 'a.matterncorp.de': '||a.matterncorp.de^'  list_id: 0
2019/12/15 11:34:25 1#93 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NXDOMAIN, id: 2
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;a.matterncorp.de.	IN	 A

;; AUTHORITY SECTION:
a.matterncorp.de.	10	IN	SOA	fake-for-negative-caching.adguard.com. hostmaster.a.matterncorp.de. 100500 1800 900 604800 86400
```

**Comment by NullEnt1ty** [comment]
It works with global scoped IPv6 addresses. Link local addresses do not work in my case. I'm not sure if this intentionally as I'm not too familiar with IPv6.
