### ISSUE TITLE
Error when using custom IP address after restart AGH

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#1262]
После того когда я все настрою на пользовательский IP и перезапущу терминал\службу происходит эта ошибка которая на скриншоте и так же он не перенаправляет на указанный мною пользовательский IP запросы если после перезапуска опять не зайти в настройки и заново не сохранить его.. 

### Issue Details

* **Version of AdGuard Home server:**
  * Beta: v0.100.0
* **Operating system and version:**
  * Windows 10 build 1607

### Screenshots

<details><summary>Screenshot:</summary>

![bags](https://user-images.githubusercontent.com/46345396/70907614-61301100-201a-11ea-9a92-428154974ded.PNG)

</details>

**Comment by ameshkov** [comment]
DNS Rewrite?

**Comment by Eyeborgs** [comment]
Простите я ваш вопрос не понял.. 
Но эта связанно с Custom IP и перезапуском AGH

**Comment by ameshkov** [comment]
А, я понял, спасибо:)
