### ISSUE TITLE
Long server startup AGH

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#1263]
Долгий запуск DNS после того как я запущу терминал\службу AGH
если подробнее то после того как я запущу AGH я некоторое время не могу зайти в интернет и так же на веб страницу самой AGH потому что там написано "Запуск DNS сервера" - эта продолжается если я не ошибаюсь более 7 секунд (точно не измерял) 

### Issue Details

* **Version of AdGuard Home server:**
  *  Beta: v0.100.0
* **Operating system and version:**
  *  Windows 10 build 1607

**Comment by ameshkov** [comment]
Это нормально - мы на старте загружаем все фильтры в первый раз, на это уходит время

**Comment by Eyeborgs** [comment]
однако в версии 0.99.3 все моментально происходит..

**Comment by ameshkov** [comment]
В ней не ждали и из-за этого могло без фильтрации стартануть - этого бы как раз не хотелось

**Comment by Eyeborgs** [comment]
хорошо, спасибо за быстрый ответ :)
