### ISSUE TITLE
Yet more syntax support requests from me

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1266]
### Prerequisites

- [x] I am running the latest version (v0.99.3)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I'd understand it if any of you guys were to begin to think that my syntax requests are getting a bit outlandish and out of control, but since I feel that I have best intentions with them and am mostly only hoping to strengthen AdGuard Home's feature support, here's another two:

During experimentation with [my anti-malware list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt) and its [AdGuard Home-designated version](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt) this morning, I saw that there were two syntaxes that weren't supported by AGH but which was supported by regular adblockers:

1) `||.tk^` doesn't work in AGH, whereas `||*.tk^` works.
2) `||*.tk^$domain=~google.tk` currently invalidates the whole entry, but I feel that it should be possible (although not super-easy) to make it so that such an entry would block all `tk` domains except `google.tk`.

### Proposed Solution

For №1: Treat entries that begin with `||.` as being a wildcard for the parts of a URL before a `.`; in a very similar way as to how `||example.` works, except for wildcarding the earlier parts instead of the later parts.

For №2: Making it so that when `domain=~` is used in an entry that contains wildcarding (e.g. `||example.*`, `||example.`, etc.), that the entry becomes supported by AGH, preferably in such a way that `||example.*$domain=~example.org` would block all `example.*` sites except `example.org`.

### Alternatives Considered

For №1: None that I can come up with in a hurry.

For №2: If you guys were to feel that `$domain` shouldn't be used in such a fashion, you could possibly accomplish this with whichever other `$` value instead.

### Additional Information

I am aware that №1 is a very narrow and very rarely encountered situation, with maybe only 2 or 3 lists in existence being known to block entire TLDs.

**Comment by ameshkov** [comment]
`||.tk^ doesn't work in AGH, whereas ||*.tk^ works.`

That's okay, `||.tk` is not a valid rule.

> ||*.tk^$domain=~google.tk currently invalidates the whole entry, but I feel that it should be possible (although not super-easy) to make it so that such an entry would block all tk domains except google.tk.

I don't like an idea of making syntax too lax -- it may be dangerous.

I really think this is a task for https://github.com/AdguardTeam/AdGuardHome/issues/1160
