### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by AlexHighTower** [AdguardTeam/AdGuardHome#1268]
Hello,

It would be nice to have "proxy" setting in order to access filters urls as well as self version check url
It is useful on old mipsel router where root certificates are old and it is not possible to update them, and now while checking version and retrieving filter error occurs like this

> Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: x509: certificate signed by unknown authority

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/458

**Comment by ameshkov** [comment]
Closed as dup of #458. Please upvote the original task if you want us to make it sooner.
