### ISSUE TITLE
Provide further filter option(s) in query log

### ISSUE THREAD

**Issue by mmotti** [AdguardTeam/AdGuardHome#1269]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
It would be useful to be able to expand the filter options in the query log 

### Proposed Solution
If possible, it would be nice to be able to filter on standard blocks and regexp blocks. Also might be useful if the user was able to see "whitelisted" domains that have been accessed.

**Comment by ArchiveBase** [comment]
> If possible, it would be nice to be able to filter on standard blocks and regexp blocks.

a little https://github.com/AdguardTeam/AdGuardHome/issues/594#issuecomment-469129412 

> the user was able to see "whitelisted" domains that have been accessed.

https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911
