### ISSUE TITLE
AdGuard Home fails to start with exit status 5

### ISSUE THREAD

**Issue by seonwoolee** [AdguardTeam/AdGuardHome#1270]
### Issue Details

I'm running AdGuard Home v0.100 on a Raspberry Pi 3 Model B+ running Arch Linux.

### Expected Behavior
AdGuardHome starts when I run `sudo ./AdGuardHome -s start`.

### Actual Behavior
I instead get the following error
```
2019/12/18 18:06:02 [info] Service control action: start
2019/12/18 18:06:02 [fatal] Failed to start AdGuard Home service: exit status 5
```

### Additional Information
I tried searching the code for what would give an exit status of 5 to no avail.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by seonwoolee** [comment]
The same error is produced and no log file is generated.

My AdGuardHome.yaml
```
log_file: "/tmp/log"
verbose: true
```

**Comment by ameshkov** [comment]
Maybe there's something in syslog?

Try checking /var/log/syslog or /var/log/system.log

**Comment by seonwoolee** [comment]
Those files don't exist on my system; Arch Linux uses the systemd journal.

When I run `journalctl` to check the system logs, I don't find anything in there related to AdGuardHome

**Comment by szolin** [comment]
`sudo ./AdGuardHome` - does it work?

**Comment by seonwoolee** [comment]
Upon updating to the latest version it works. Not sure what the problem was.

**Comment by talesam** [comment]
I'm having the same problem using the latest version, does anyone know how to solve it?

```
ubuntu@dns:/opt/AdGuardHome$ sudo su
root@dns:/opt/AdGuardHome# ./AdGuardHome -s start
2022/08/02 03:14:27 [info] service: control action: start
2022/08/02 03:14:27 [fatal] service: executing action "start": Failed to start AdGuard Home service: exit status 5
root@dns:/opt/AdGuardHome# ./AdGuardHome -s reload
2022/08/02 03:14:40 [info] service: control action: reload
2022/08/02 03:14:40 [error] service: finding AdGuardHome process: no AdGuardHome instances found
root@dns:/opt/AdGuardHome# exit
exit
ubuntu@dns:/opt/AdGuardHome$ sudo ./AdGuardHome -s start
2022/08/02 03:15:20 [info] service: control action: start
2022/08/02 03:15:20 [fatal] service: executing action "start": Failed to start AdGuard Home service: exit status 5
ubuntu@dns:/opt/AdGuardHome$ sudo ./AdGuardHome
2022/08/02 03:18:10.573988 [info] AdGuard Home, version v0.107.8
2022/08/02 03:18:10.581143 [info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
2022/08/02 03:18:10.583088 [info] auth: initialized.  users:1  sessions:1
2022/08/02 03:18:10.583118 [info] Initialize web module
2022/08/02 03:18:10.724097 [info] AdGuard Home is available at the following addresses:
2022/08/02 03:18:10.724416 [info] Go to http://127.0.0.1:80
2022/08/02 03:18:10.724530 [info] Go to http://10.0.0.89:80
2022/08/02 03:18:13.004196 [info] Starting the DNS proxy server
2022/08/02 03:18:13.004380 [info] Ratelimit is enabled and set to 20 rps
2022/08/02 03:18:13.004395 [info] The server is configured to refuse ANY requests
2022/08/02 03:18:13.004422 [info] DNS cache is enabled
2022/08/02 03:18:13.004442 [info] MaxGoroutines is set to 300
2022/08/02 03:18:13.004455 [info] Creating the UDP server socket
2022/08/02 03:18:13.004507 [info] Listening to udp://[::]:53
2022/08/02 03:18:13.004517 [info] Creating a TCP server socket
2022/08/02 03:18:13.004545 [info] Listening to tcp://[::]:53
2022/08/02 03:18:13.004723 [info] Entering the UDP listener loop on [::]:53
2022/08/02 03:18:13.004839 [info] Entering the tcp listener loop on [::]:53
```

**Comment by emitar** [comment]
> root@dns:/opt/AdGuardHome# ./AdGuardHome -s reload
> 2022/08/02 03:14:40 [info] service: control action: reload
> 2022/08/02 03:14:40 [error] service: finding AdGuardHome process: no AdGuardHome instances found

You are sure that AdguardHome are installed? 
./AdGuardHome -s install before start
