### ISSUE TITLE
Query log's «Client» field doesn't support searching by client nicknames

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1273]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

In the Query Log list, the *Clients* textfield does not support any sort of searching by client nicknames whatsoever, regardless of if the nicknames were given through AGH's *Client settings* menu, the RaspPi's /etc/hosts file, or the client units' own callcode names (e.g. `PC-GHWJCIOR`).

Supporting searches by client nicknames would've been **hugely** advantageous if one wants to look up the query logs of multiple but similar things at the same time, be they similar in model, brand, or owner. Currently the only way to do that is with *very* careful assignment of static IPs to make them have IP addresses next to each other (e.g. `192.168.1.90` and `192.168.1.91`, while assigning no other `192.168.1.9x` IPs to anything), which is impractical for many people.

Since I've already named my static-IP clients by product model and in most cases also owner names, it'd have been amazing to be able to e.g. search with *Yamaha* if one owns multiple surround receivers, *T-We* if one owns multiple models of that Scandinavian cable TV set-top box brand, *[My mom's name]* to look through all the units someone is owning, or *telenor* to look through connections from a specific 4G provider.

* **Version of AdGuard Home server:**
  * v0.100.3, although this was also a problem in v0.99.3 and all the way back to at least late July 2019.
* **How did you setup DNS configuration:**
  * N/A (This is a web GUI problem.)
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * GUI is accessed from Windows 10 November 2019 Update

### Expected Behavior

That text input in the *Clients* textbox, leads to the query list filtering down to clients whose nicknames contain such text.

### Actual Behavior

No entries show up with any letter-containing search of any kind (See screenshot below).

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/71130998-b2472d00-21f3-11ea-9c2e-af416ef66f5a.png)

</details>

### Additional Information

None in particular.

**Comment by ArchiveBase** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/853 https://github.com/AdguardTeam/AdGuardHome/issues/481

**Comment by szolin** [comment]
@ameshkov I propose we close #853 in favor of this one, because this one is nicely described.

**Comment by ameshkov** [comment]
@szolin no prob

**Comment by DandelionSprout** [comment]
One potential makeshift alternativ that I only came up with just now, would've been to allow something like '123.45.67.89 + 87.65.43.21' or '123.45.67.89 OR 87.65.43.21', like what can be done in certain search engines to include search results for multiple terms at once.

**Comment by ainar-g** [comment]
The name search is implemented as of snapshot 7c35d208.  Is there anything else to be done here?

**Comment by ameshkov** [comment]
Looks good to me
