### ISSUE TITLE
AGH does not load long term query logs

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#1275]
#### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.2
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Windows 10 1903 (64bit)

#### Bug (1)
I noticed that problem randomly since past versions however reproduced that easy way one more time as mentioned below.

- Performed a clean installation 0.99.3 version 29 days ago
- Query logs retention and statistics retention set to 90 days
- Connected a test client for only one day (ex: 192.168.0.125)
- Several days ago searched 192.168.0.125 but no query log appear
- Yesterday updated to v0.100.2 and checked, still the same

note: that client remain display with total request counts on top clients component

<details><summary>Screenshot:</summary>

![Screenshot_31](https://user-images.githubusercontent.com/46082456/71160504-46f46e00-227a-11ea-8c29-3c40622a815d.png)

</details>

#### Bug (2)

Another small issue in this version. see below 

![New Project](https://user-images.githubusercontent.com/46082456/71163566-ecf6a700-227f-11ea-86f6-cce9bf7d36ab.gif)

**Comment by szolin** [comment]
Please perform `grep 192.168.0.125` on your `querylog.json` file - is it there?

**Comment by ArchiveBase** [comment]
Yes

**Comment by szolin** [comment]
Can you show some of these entries? So I can try to reproduce it on my side.

**Comment by ArchiveBase** [comment]
[querylog.txt](https://github.com/AdguardTeam/AdGuardHome/files/3988806/querylog.txt) - some
[log_file.txt](https://github.com/AdguardTeam/AdGuardHome/files/3988810/log_file.txt) - tested querylog file with temp instance

**Comment by szolin** [comment]
@ArchiveBase Thank you for the logs!

The problem is that because UI stops asking for more data after it receives 0 entries in search result.  UI should continue asking the server until `oldest` field is null.

```
GET /control/querylog?filter_domain=&filter_question_type=&filter_response_status=&filter_client=111.&older_than=

{"data":[],"oldest":"2019-11-15T07:00:40.888071736+03:00"}


GET /control/querylog?filter_domain=&filter_question_type=&filter_response_status=&filter_client=111.&older_than=2019-11-15T07%3A00%3A40.888071736%2B03%3A00

{"data":[],"oldest":"2019-11-15T04:36:39.357478801+03:00"}
```

**Comment by ArchiveBase** [comment]
@szolin @IldarKamalov Bug (2)?
