### ISSUE TITLE
[Question] Option for donation?

### ISSUE THREAD

**Issue by htjain** [AdguardTeam/AdGuardHome#1277]
I am using AGH from past two months and its really good compared to my previous dns ads blocker (PiHole). 
I would like to donate some $$ for your great work but unable to find any donation option. 
Do you guys accept donation ?

**Comment by ameshkov** [comment]
Hi and thank you!:)

Tbh, we don't, and we do not plan to accept donations. We earn by selling other software we develop, and maybe at some point, we'll be able to offer some premium additions to AdGuard Home.

In these circumstances accepting donations seems wrong to me.

**Comment by htjain** [comment]
Thanks for your reply. I respect your decision.
