### ISSUE TITLE
Changing upstream requires restart of AGH to take effect

### ISSUE THREAD

**Issue by ajp2k13** [AdguardTeam/AdGuardHome#1278]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  0.100.4
* **How did you setup DNS configuration:**
  Router
* **If it's a router or IoT, please write device model:**
  Raspberry Pi 3 Model B
* **Operating system and version:**
  Raspbian Buster

### Expected Behavior
Changing upstream DNS should take effect right away

### Actual Behavior
A restart of AGH is reuired before the change in upstream DNS takes effect (check with dnsleaktest.com)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Argh, one more hotfix incoming
