### ISSUE TITLE
Dirty docker images

### ISSUE THREAD

**Issue by mazay** [AdguardTeam/AdGuardHome#1279]
Hi there! Thanks a lot for your work on the AGH.

I was about to upgrade to the latest version and noticed that all of the docker images are `*-dirty`. Does it mean that it's a stable release or there is some bug with in docker build procedure?

**Comment by thueske** [comment]
```
> docker images | grep adguard
adguard/adguardhome       armhf-latest        ae5f90786ea8        4 hours ago         41MB
```

<img width="282" alt="Bildschirmfoto 2019-12-19 um 17 29 08" src="https://user-images.githubusercontent.com/436986/71190717-6349d800-2285-11ea-8656-3e3708161400.png">

**Comment by ameshkov** [comment]
Thank you! Fixed in https://github.com/AdguardTeam/AdGuardHome/commit/32f780366e61bcc8ca192af264729dd40a196eeb

**Comment by mazay** [comment]
Thanks! Does it mean that they will be tagged properly and pushed to the docker hub shortly?

**Comment by ameshkov** [comment]
Yep

**Comment by mazay** [comment]
cool beans!

**Comment by mazay** [comment]
sorry to bother you but images are still not there :/

**Comment by ameshkov** [comment]
@mazay why, it's there already, v0.100.6

**Comment by mazay** [comment]
oh my, you are moving to fast, I was looking for 0.100.5 )))
thanks again
