### ISSUE TITLE
nslookup 返回1.1.1.1

### ISSUE THREAD

**Issue by blucewyan** [AdguardTeam/AdGuardHome#1280]
我在是docker(192.168.2.3)里面建立的adgurad,当我选择114.114.114.114做为我网络的dns的时候  可以返回正确的地址,此时nslookup nslookup pili-live-hdl.qhmywl.com 192.168.2.3 也可以返回正确的IP地址,
![image](https://user-images.githubusercontent.com/59073966/71225015-2c6dd380-2312-11ea-9da8-ab30d8f608a8.png)

但是当我选择192.168.2.3做为我网格的DNS的时候,nslookup nslookup pili-live-hdl.qhmywl.com 114.114.114.114已经返回不了正确的IP地址了,返回了一个1.1.1.1的adress
![image](https://user-images.githubusercontent.com/59073966/71225118-79ea4080-2312-11ea-9c1e-1b7738114648.png)
![image](https://user-images.githubusercontent.com/59073966/71225149-92f2f180-2312-11ea-81d3-f966b5870924.png)
过滤器里面也没有过滤记录,不开启过滤,安全成人,强制安全  也是一样的结果,不知道有没有大神能解决这个问题

**Comment by sh0w1ov3** [comment]
我这使用正常，没遇到这样的问题，
你用dig 和 host 都试下

**Comment by DavidTai780** [comment]
尝试在AdGuardHome的配置开去debug记录所有的日志

**Comment by blucewyan** [comment]
首先,还有一个问题,当我把国内DNS设置为adguard时,我在电脑上用kmplayer打开http://pili-live-hdl.qhmywl.com/dsdtv/4364abb0a9f358049a535f4692cd49b5.flv这个直播地址可以正常播放.但是在adroid电视盒子上却打不开这个电视直播.我用了koolshare的LEDE  adguard是安装在群晖的docker里面的  LEDE开了科学插件,插件国内DNS填的群晖地址,不知道和LEDE有没有关系.

**Comment by blucewyan** [comment]
pili-live-hdl.qhmywl.com
AAAA
CNAME: pili-live-hdl.qhmywl.com.hdlv4.pilidns.com. (ttl=510)
172.17.0.1
响应之后又获得了这样的一个地址

**Comment by sh0w1ov3** [comment]
> 首先,还有一个问题,当我把国内DNS设置为adguard时,我在电脑上用kmplayer打开[http://pili-live-hdl.qhmywl.com/dsdtv/4364abb0a9f358049a535f4692cd49b5.flv这个直播地址可以正常播放.但是在adroid电视盒子上却打不开这个电视直播.我用了koolshare的LEDE](http://pili-live-hdl.qhmywl.com/dsdtv/4364abb0a9f358049a535f4692cd49b5.flv%E8%BF%99%E4%B8%AA%E7%9B%B4%E6%92%AD%E5%9C%B0%E5%9D%80%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E6%92%AD%E6%94%BE.%E4%BD%86%E6%98%AF%E5%9C%A8adroid%E7%94%B5%E8%A7%86%E7%9B%92%E5%AD%90%E4%B8%8A%E5%8D%B4%E6%89%93%E4%B8%8D%E5%BC%80%E8%BF%99%E4%B8%AA%E7%94%B5%E8%A7%86%E7%9B%B4%E6%92%AD.%E6%88%91%E7%94%A8%E4%BA%86koolshare%E7%9A%84LEDE) adguard是安装在群晖的docker里面的 LEDE开了科学插件,插件国内DNS填的群晖地址,不知道和LEDE有没有关系.

玩的好起劲啊，你描述的问题非常不清楚，没有办法能解答你的问题

**Comment by blucewyan** [comment]
问题已经解决了  可以是与pili-live-hdl.qhmywl.com这个域名有关系   现在可以正常返回IP了  电视直播也可以正常观看了 估计是这个域名跳转了太多次  导致获取不到正确的IP
