### ISSUE TITLE
我维护了一个支持adguard的屏蔽列表，综合各大著名list

### ISSUE THREAD

**Issue by gentlyxu** [AdguardTeam/AdGuardHome#1281]
项目地址是 https://github.com/privacy-protection-tools/anti-AD

只要这过滤器里添加 `https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt` 即可

小伙伴们可以对比一下屏蔽效果，这个项目我自己已经用了好几年咯

**Comment by rufengsuixing** [comment]
和分别添加各host list进adguardhome有什么区别

**Comment by lancelot-moon** [comment]
@rufengsuixing
In his list, only domains in basic adblock rule syntax.
AG Home supports many formats of lists.
Basic adblock rule syntax, domain and hosts file.

**Comment by rufengsuixing** [comment]
i want to know what is the advantage of use his list instead of the original host rule，rules are from the same source，host to adblock syntax seems meaningless

**Comment by gentlyxu** [comment]
> 和分别添加各host list进adguardhome有什么区别，反正不是只有域名的正则规则adh也不支持

预先剔除了adh不支持的规则，去除了各个不同规则列表之间重复的部分，对于在路由器等小内存机器上运行的adh会显得更有优势，另外，挨个添加不累么？这个列表当前是从dnsmasq规则移植过来的，所以暂时不支持域名模糊匹配，但支持模糊匹配一点也不难啊。吼～

**Comment by gentlyxu** [comment]
另外，正在测试中的“主动探测可用域名”功能，及时剔除已经失效的域名，精简列表长度，这些对性能均会产生积极的提升作用。相比其他列表越来越大是完全不同的。 @rufengsuixing

**Comment by rufengsuixing** [comment]
主动探测emm，ping？ tcp80/443？有的服务器不响应错误请求或者直接rst的吧，这个功能我觉得再谨慎一点好
yhost有一部分基于作者兴趣屏蔽的域名不知你如何处理的

**Comment by gentlyxu** [comment]
> 主动探测emm，ping？ tcp80/443？有的服务器不响应错误请求或者直接rst的吧，这个功能我觉得再谨慎一点好
> yhost有一部分基于作者兴趣屏蔽的域名不知你如何处理的还有一些可能影响到电脑看视频的

原理是查国内公共dns的解析，空记录的或者返回NXDOMAIN的进行计数，超过阈值的剔除

**Comment by rufengsuixing** [comment]
刚才看了一下你的列表，不光里面有广告屏蔽的规则还有一些不良网站的屏蔽
文件规则的具体来源，比如yhost用的是哪个列表，主要是规则源我觉得需要列个清单讲明白

**Comment by gentlyxu** [comment]
收到，感谢建议

**Comment by sh0w1ov3** [comment]
> 刚才看了一下你的列表，不光里面有广告屏蔽的规则还有一些不良网站的屏蔽
> 文件规则的具体来源，比如yhost用的是哪个列表，主要是规则源我觉得需要列个清单讲明白

前面的一段英文看哭了我
