### ISSUE TITLE
Domains with a dash and rule Adblock syntax

### ISSUE THREAD

**Issue by mgcWil** [AdguardTeam/AdGuardHome#1282]
Hello everyone!
I notice a small problem since update v0.100.2, domains with a dash are filtered when the beginning of the address exists in a rule with Adblock syntax (domains without a dash are ignored), example with the rule ||www.us^ :

![image](https://user-images.githubusercontent.com/53054629/71247332-d2244100-2318-11ea-8f01-f98b3af824c6.png)
![image](https://user-images.githubusercontent.com/53054629/71247794-c2f1c300-2319-11ea-9c50-5b9e282dd1e6.png)
![image](https://user-images.githubusercontent.com/53054629/71247809-ca18d100-2319-11ea-854b-87130670121d.png)

I see that domains with and without dashes are ignored by the same rule with HOST syntax 0.0.0.0 www.us

Regards.

**Comment by ameshkov** [comment]
Yeah, this is a mistake indeed.

**Comment by ameshkov** [comment]
@szolin we should update urlfilter to fix this: https://github.com/AdguardTeam/urlfilter/releases/tag/v0.7.2

**Comment by szolin** [comment]
4808b33c01cbaf573ed7002ee9160f290d7200fb
