### ISSUE TITLE
Please add option `-V` to return the version of AdGuardHome installed.

### ISSUE THREAD

**Issue by JACK-THINK** [AdguardTeam/AdGuardHome#1285]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Alternatives Considered

Please add option `-V` to return the version of AdGuardHome installed.

For example:
```shell
INPUT: ./AdGuardHome -V
OUTPUT: v0.100.6
```

**Comment by rufengsuixing** [comment]
you can use
```
touch /var/run/AdGfakeconfig
$binpath" -c /var/run/AdGfakeconfig --check-config 2>&1| grep -m 1 -E 'v[0-9.]+' -o
rm /var/run/AdGfakeconfig
```
to get the version

**Comment by jimeh** [comment]
A slightly easier workaround for now is feeding `/dev/null` in as the config file, no need to create any temporary empty files then:

```
$ ./AdGuardHome -c /dev/null --check-config 2>&1 | grep -m 1 -E 'v[0-9.]+' -o
v0.100.8
```
