### ISSUE TITLE
Windows's NSLOOKUP could not get response with AGH version after v0.99.3

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdGuardHome#1287]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.100.6
* **How did you setup DNS configuration:**
  *  IoT(Raspberry Pi 3 B+) and also Windows Machine
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 B+
* **Operating system and version:**
  * Latest Version for Raspberry Pi and Windows

### Expected Behavior

Windows's cmd tool(nslookup) could get what i can get as usual without any timeout.

### Actual Behavior

100% get 2 seconds timeout for every nslookup with AdGuard Home version higher than v0.99.3. The results i was tested with the v0.99.3 and v0.100.5->v0.100.6 within AGH run on Windows and Raspbian, Ubuntu platform.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

AdGuard Home's dns query logs show it have receive the dns request from client and looks fine.
Below is the verbose log from my AGH. Nslookup from linux system can function normally.

[AGH.log](https://github.com/AdguardTeam/AdGuardHome/files/3992269/AGH.log)

**Comment by ArchiveBase** [comment]
Cannot reproduce windows 10 1903 probably your firewall?

**Comment by DavidTai780** [comment]
The result has tested in local machine and tested from other pc with nothing to modify with Firewall. I am sure it is not the firewall blocking it. After i switch it back to v0.99.3 on same device with all same settings the nslookup can work normally.

**Comment by ArchiveBase** [comment]
then @szolin will take care about that 😊

**Comment by Who-42** [comment]
i can also reproduce it - with no firewall
![image](https://user-images.githubusercontent.com/37018396/71321013-e51f4880-24b3-11ea-97f6-46797bb5a6d9.png)

**Comment by rufengsuixing** [comment]
because maybe there is no fe80 monitor for example
127.0.0.1
::1
192.xx.0.1
2409:xxxx:316:3d40::1
fd47:xxxx:1556::1
192.xx.192.55

**Comment by Who-42** [comment]
btw ::1 is all IPv6 ;) so fe /fd... is included

**Comment by ameshkov** [comment]
By default, it listens to `0.0.0.0` so it **should** listen to all your network interfaces including `[::]`.

**Comment by ameshkov** [comment]
@DavidTai780 the problem in your case is that AdGuard DNS is unavailable, and we use it for "browsing security" lookups:
```
2019/12/22 16:23:21 3720#138 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): failed to lookup for dns-family.adguard.com in 3002 milliseconds using 176.103.130.131: read udp 192.168.1.190:63365->176.103.130.131:53: i/o timeout
```

If you disable browsing security, the issue will go away.

**Comment by ameshkov** [comment]
@DavidTai780 any idea why AG DNS is unavailable from your place?

**Comment by Who-42** [comment]
@ameshkov i got the same problem as you can see some posts above - but i have no browsing sec active

**Comment by ameshkov** [comment]
@Who-42 yours is very different. For some reason, in your case `nslookup` tries to query a link-local IPv6 address.

You should check your DNS settings, what DNS server addresses do you have there?

**Comment by Who-42** [comment]
but i can use the link local IPv6 to access the ADG Home Webinterface - why its not working for dns querry?

**Comment by ameshkov** [comment]
@Who-42 check `AdGuardHome.yaml`, what do you have in `bind_host`?

**Comment by Who-42** [comment]
@ameshkov 
![image](https://user-images.githubusercontent.com/37018396/71351573-56263500-2574-11ea-8d8f-6ed855d3e07d.png)

**Comment by ameshkov** [comment]
@Who-42 well, no idea then:( Try replacing it with `bind_host: "::"` just in case

**Comment by Who-42** [comment]
@ameshkov maybe this helps IPv4 works / Ipv6 not 
![image](https://user-images.githubusercontent.com/37018396/71354233-94732280-257b-11ea-8c6e-86d515a3b039.png)

![image](https://user-images.githubusercontent.com/37018396/71354296-c5535780-257b-11ea-97bb-2c6e47746dec.png)

**Comment by ameshkov** [comment]
@Who-42 I cannot reproduce this on a Windows VM.

Tbh, I don't consider this an issue at all, link-local addresses aren't supposed to be used for that.

**Comment by Who-42** [comment]
@ameshkov as i understand you can use link-local for communication in a network segement?

**Comment by ameshkov** [comment]
@Who-42 yeah, but don't confuse it with your local network address

**Comment by Who-42** [comment]
@ameshkov so why ADG Home don't listen on all IPv6 traffic as intended - thats what it looks like for me :-D

**Comment by rufengsuixing** [comment]
i test on my router the fe80: can be use when set to 0.0.0.0

**Comment by Who-42** [comment]
strange - hm maybe i should wait a short time there is a beta firmware for my router with DOT/DOH Support
so i can switch to my 2 VPS ADG Home Server and then theres no need for the local one

**Comment by ameshkov** [comment]
@Who-42 I suppose this might be some Windows-specific issue.

Also, I don't think it cannot listen to IPv6 traffic -- it just might be ignoring link-local addresses.

**Comment by Who-42** [comment]
Adguard is running on ubuntu - i was just testing from windows

**Comment by DavidTai780** [comment]
> @DavidTai780 any idea why AG DNS is unavailable from your place?

Sorry for late to reply your message, yes the problem is now solve when the AGH with option disable for browse security and parent control. Thank You

**Comment by ArchiveBase** [comment]
> > @DavidTai780 any idea why AG DNS is unavailable from your place?
> 
> Sorry for late to reply your message, yes the problem is now solve when the AGH with option disable for browse security and parent control. Thank You

But you didn't answer to the question or if you can tell about your ISP name then we can play from our end to check it 😉

**Comment by ameshkov** [comment]
Yeah, maybe we could check out what's wrong and fix this somehow

**Comment by DavidTai780** [comment]
My ISP is DIGIIX-AP DiGi Telecommunications Sdn. Bhd.

**Comment by DavidTai780** [comment]
> @DavidTai780 the problem in your case is that AdGuard DNS is unavailable, and we use it for "browsing security" lookups:
> 
> ```
> 2019/12/22 16:23:21 3720#138 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): failed to lookup for dns-family.adguard.com in 3002 milliseconds using 176.103.130.131: read udp 192.168.1.190:63365->176.103.130.131:53: i/o timeout
> ```
> 
> If you disable browsing security, the issue will go away.

Just now i test it once more times, this issue(failed to lookup dns-family.adguard.com) is now solved even if the option browse security and parent control is enable

**Comment by ameshkov** [comment]
Could you please also show the output of: `traceroute 176.103.130.130`

**Comment by ameshkov** [comment]
> Just now i test it once more times, this issue(failed to lookup dns-family.adguard.com) is now solved even if the option browse security and parent control is enable

Hmm, maybe that was a temporary glitch?

**Comment by DavidTai780** [comment]
Here the record for tracing the route
![Screenshot (10)](https://user-images.githubusercontent.com/26398101/71412619-798ed400-2689-11ea-8942-26edc9469cc4.png)

**Comment by ameshkov** [comment]
Yeah, well, looks okay now:) Thank you anyway!
