### ISSUE TITLE
Youtube: Restricted Mode is enabled by your network administrator.

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1290]
After updating to 100 version began to disappear some videos on youtube. As a result of searches it became clear that the Restricted Mode on youtube constantly turns on with the message "Restricted Mode is enabled by your network administrator." 
had to go back to version 0.99.3

Raspbian Buster
Raspberry B3+
AGH v0.100.6
Use AdGuard browsing security web service - NO
Use AdGuard parental control web service - NO
Enforce safe search - NO

**Comment by ameshkov** [comment]
@YBS-PC I cannot reproduce this for some reason.

Could it be that you have any custom client settings configured?

**Comment by YBS-PC** [comment]
custom client settings were only on pinning ip and mac so that in the log to see not just the ip, but also the name of the client

**Comment by YBS-PC** [comment]
when you disable the protection, the problem disappeared only after a while. at 99.3 as long as no problems arise. incomprehensibly

**Comment by ameshkov** [comment]
@YBS-PC блин я не до конца врубаюсь что происходит и какие настройки установлены.

Но вообще предполагаю что баг такой же как и тут:
https://github.com/AdguardTeam/AdGuardHome/issues/1274

Можете бета-версию AdGuard Home поставить посмотреть есть ли с ней проблемы?

**Comment by YBS-PC** [comment]
Была установлена версия 0.100.6 . Настройки такие же как и в предыдущей версии, но с разницей, что в настройках клиента добавил еще мак адрес (вряд-ли это имеет значение), остальные настройки глобальные, за исключением одного клиента - одного из тв, у которого свой аккаунт на ютюб. И на ютюб  на компе (аккаунт ютюб) отдельный перестали отображаться многие видеоролики. В настройках ютуб нашел, что включен безопасный режим, который не возможно отключить, т.к. указано, что эта настройка включена сетевым администратором. Попробовал отключить все фильтры - ничего не изменилось. Отключил защиту и тоже не изменилось. В опере с включенным впн все нормально без безопасного режима. В файрфокс с doh 1.1.1.1 тоже все нормально отображается.
Установил версию 0.99.3 и в ютюб безопасный режим сам отключился и его настройка стала доступна.

**Comment by ameshkov** [comment]
@YBS-PC так а бета-версию можете все-таки попробовать поставить?

Вот тут ссылки: https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

Минут через 5 будет доступна

**Comment by YBS-PC** [comment]
Могу конечно

**Comment by ameshkov** [comment]
@YBS-PC ну в целом уже доступна

**Comment by YBS-PC** [comment]
v0.100.6-22-gb4f4 эта версия? и надо ли удалять файлы из папки adguard или достаточно команды stop, uninstall, потом install новой версии?

**Comment by ameshkov** [comment]
@YBS-PC да, эта. А удалять ничего не надо

**Comment by YBS-PC** [comment]
Установил, пока все нормально (я пока удалил всех клиентов из вкладки настройки клиентов на время ). Через некоторое время (час/полтора) добавлю клиентов как они были раньше и буду наблюдать. Если завтра не дополню комментарий, значит проблема ушла (надеюсь).

**Comment by ameshkov** [comment]
Отлично, спасибо!

**Comment by YBS-PC** [comment]
провел эксперимент. установил в качестве общего днс https://dns-family.adguard.com/dns-query , перезапустил и все... - безопасный режим в ютюб. Есть предположение, что, т.к. для одного из клиентов был установлен этот днс-сервер (в качестве глобального установлен гугл) в первой версии 0,100,6 каким то образом часть запросов от всех клиентов проходили через https://dns-family.adguard.com/dns-query
На версии v0.100.6-22-gb4f4 пока такого не наблюдается. Пока все нормально. Появилось уведомление о версии v0.100.6-25-g6bf51

**Comment by ameshkov** [comment]
Ну отлично что больше не повторяется

> Появилось уведомление о версии v0.100.6-25-g6bf51

Да, бета-версии чаще выходят.

**Comment by YBS-PC** [comment]
После добавления мак адресов к клиентам, проблема повторилась и на версии v0.100.6-22-gb4f4

**Comment by ameshkov** [comment]
Блин, ну мне тогда надо понять что там за конфигурация.

Можете AdGuardHome.yaml показать?

**Comment by YBS-PC** [comment]
Удалил мак адреса и опять нормально. по крайней мере пока.

**Comment by ameshkov** [comment]
Ну правда, надо посмотреть AdGuardHome.yaml, без него я не могу телепатировать что происходит

**Comment by YBS-PC** [comment]
bind_host: 192.168.7.101
bind_port: 8080
users:
- name: login
  password: 4w0aE1mY3lyGSMNNXmZf.JbteK7G69vxi4oFd.0$2a$10$JmfrL.8KjbDBnO
language: ru
rlimit_nofile: 0
web_session_ttl: 720
dns:
  bind_host: 192.168.7.101
  port: 53
  statistics_interval: 1
  querylog_enabled: true
  querylog_interval: 1
  querylog_memsize: 0
  protection_enabled: true
  blocking_mode: custom_ip
  blocking_ipv4: 192.168.7.101
  blocking_ipv6: '::'
  blocked_response_ttl: 10
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  - 8.8.8.8:53
  - 1.1.1.1:53
  all_servers: true
  edns_client_subnet: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  cache_size: 4194304
  upstream_dns:
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  filtering_enabled: true
  filters_update_interval: 24
  parental_sensitivity: 0
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: true
  url: https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt
  name: Spam404
  id: 1577039348
- enabled: true
  url: https://raw.githubusercontent.com/YBS-PC/AGH/master/agh-whitelist.txt
  name: AGH - whitelist
  id: 1577039349
- enabled: true
  url: https://easylist-downloads.adblockplus.org/malwaredomains_full.txt
  name: Easylist malwaredomains
  id: 1577039350
- enabled: true
  url: https://raw.githubusercontent.com/YBS-PC/AGH/master/blacklist.txt
  name: AGH - blacklist.txt
  id: 1577039351
user_rules:
- ""
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients:
- name: ABC
  ids:
  - 192.168.7.3
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams: []
- name: ABC-1
  ids:
  - 192.168.7.4
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams:
  - 8.8.8.8
  - 1.1.1.1
- name: ABC-2
  ids:
  - 192.168.7.101
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams:
  - 8.8.8.8
  - 1.1.1.1
- name: ABC-3
  ids:
  - 192.168.7.102
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams:
  - 8.8.8.8
  - 1.1.1.1
- name: ABC-4
  ids:
  - 192.168.7.154
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams:
  - https://dns-family.adguard.com/dns-query
- name: ABC-5
  ids:
  - 192.168.7.155
  use_global_settings: true
  filtering_enabled: false
  parental_enabled: false
  safebrowsing_enabled: false
  safesearch_enabled: false
  use_global_blocked_services: true
  blocked_services: []
  upstreams:
  - https://dns-family.adguard.com/dns-query
log_file: ""
verbose: false
schema_version: 6

**Comment by ameshkov** [comment]
Так, ну вот у этих двоих апстримами выбраны dns-family:
```
- name: ABC-4
  ids:
  - 192.168.7.154
  ....
  upstreams:
  - https://dns-family.adguard.com/dns-query
- name: ABC-5
  ids:
  - 192.168.7.155
  ....
  upstreams:
  - https://dns-family.adguard.com/dns-query
```

Ютуб только с ними ломается?

**Comment by YBS-PC** [comment]
При добавлении МАК , после ip следующая строка - МАК адрес. Я их удалил и проблема пока исчезла.
ABC - главный комп, ABC-4 и 5 детски
Ломается у ABC

**Comment by ameshkov** [comment]
DHCP-сервер при этом выключен?
Mac-адрес какой точно добавляете?

**Comment by YBS-PC** [comment]
Нет, не включен. Добавлял МАКи (они точные совпадают и в роутере и на самом устройстве) на будущее.

**Comment by ameshkov** [comment]
@YBS-PC у вас там в директории `data` файла `leases.db` нет случаем? Если есть, можете прислать?

**Comment by YBS-PC** [comment]
такого файла нет

**Comment by ameshkov** [comment]
@YBS-PC я попробую сейчас еще одну бета-версию выкатить с расширенным логгированием -- можете на ней проверить? 

Что-то мне пока в голову не приходит что вызывает баг. Если и на ней повторится проблема -- нужно будет лог посмотреть.

**Comment by ameshkov** [comment]
Вот собственно выкатил уже

**Comment by YBS-PC** [comment]
Не помогло удаление МАК адресов... Сейчас проверил, опять на ютюбе был безопасный режим. Сейчас удалил все индивидуальные настройки ДНС серверов в настройке клиентов. Перезагрузил малинку, очистил кеш ДНС на компе и пока нормально - безопасный режим не включен. Буду наблюдать. Чтобы не портить экперимент, новую бету потом установлю.

**Comment by YBS-PC** [comment]
Удаление индивидуальных настроек ДНС для двух клиентов, видимо, решило проблему. Т.е. если у одного из клиентов в настройках клиента указан днс сервер https://dns-family.adguard.com/dns-query , то почему то он действует и на других клиентов, у которых индивидуальная настройка пустая, т.е. должна действовать глобальная настройка ДНС (гугл в данном случае). Сейчас установил стабильную версию 0.100.6 и пока (после удаления индивидуальной настройки днс у клиентов) тоже проблем не возникало.
Возможно проблема именно в Upstream DNS-серверы для клиента, т.е. эта настройка почему то действует на всех клиентов, а не только на того, для кого настроена.

**Comment by ameshkov** [comment]
> А может проблема в том, что all_servers: true

ТОЧНО!

**Comment by ameshkov** [comment]
А не блин, не подтверждается:(

**Comment by ameshkov** [comment]
Все, я допер в чем дело: https://github.com/AdguardTeam/AdGuardHome/issues/1301

Проблема в кэше -- он общий на все апстримы сейчас7

**Comment by ameshkov** [comment]
@YBS-PC выложил новую бета-версию -- в ней точно все должно быть ок

**Comment by YBS-PC** [comment]
установил v0.100.6-28-g3a07 - буду наблюдать (пока без МАК адресов, они все равно пока не нужны). Вопрос в каком формате можно указывать ДНС серверы для отдельных клиентов - это могут быть DOH, TLS и можно ли указывать сразу два ДНС в столбик (как глобальные) или какие то ограничения?

**Comment by ameshkov** [comment]
Также как и обычные можно указывать
