### ISSUE TITLE
V0.100.6-10-g2809 version of the "DNS Settings" can not be displayed, resulting in the failure to set up the DNS server...

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#1291]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by zxlhhyccc** [comment]
![image](https://user-images.githubusercontent.com/45259624/71353651-a8874600-25b4-11ea-93bc-3b63149829be.png)
![image](https://user-images.githubusercontent.com/45259624/71353679-bc32ac80-25b4-11ea-83c9-90a07910a65f.png)
![image](https://user-images.githubusercontent.com/45259624/71353701-d2406d00-25b4-11ea-9f79-31cd52942305.png)

**Comment by ameshkov** [comment]
What's in the browser console? Any errors?

**Comment by ameshkov** [comment]
Ah, nvm, I reproduced it

**Comment by zxlhhyccc** [comment]
> What's in the browser console? Any errors?
No errors...

**Comment by IldarKamalov** [comment]
Fixed in 5ba45b91c9cfde84fc0866e6b3fca679504975e7

**Comment by ameshkov** [comment]
fixed in the
