### ISSUE TITLE
Allow AdGuard to show clients triggering specific filters like Malware/Phishing

### ISSUE THREAD

**Issue by purpleax** [AdguardTeam/AdGuardHome#1292]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Problem Description
[Feature Request]
I see my AdGuard Home dashboard showing general statistics about the number of DNS requests blocked by AdGuard Browsing Security Module (Malware/Phishing) - but there is nowhere I can find to determine which clients/IP's have triggered this filter, and what were the domains they were trying to get to.

### Proposed Solution
Allow searching the Query Log based on Category, and then allow clicking on the section on the dashboard that will take you to a query with the filter already defined.

For example, the dashboard shows DNS requests blocked by "Malware/Phishing". Clicking on that will then take you to the query log that shows the clients who have triggered the rules in the related category (Malware, Adult Websites, Safe Search, etc), and preferably the destination they were trying to get to.

### Additional Information
This feature request will help make adguard more useful, since there isnt little value in telling me that a client has malware, but no way of telling me which one.

**Comment by ameshkov** [comment]
I guess this is possible once we implement proper query log filters. Once it's done, we can simply link the query log page with necessary filters enabled.

**Comment by swetoast** [comment]
This would be a good goal for adguard since its kinda messy to see which client triggered it at the moment

**Comment by Aikatsui** [comment]
Seems already implemented? #1625

**Comment by ameshkov** [comment]
Yeah, looks so
