### ISSUE TITLE
Hostname as allowed client

### ISSUE THREAD

**Issue by Termi79** [AdguardTeam/AdGuardHome#1295]
Please add the possibility to add hostnames as allowed clients at "DNS settings" -> "Access settings", for example client.myhost.name or *.myhost.name.

Why do this? It would be possible to use an own external server on lines with dynamic IP adresses without have DNS services for everybody. Just use a DDNS service and add the hostname in AdGuard Home

**Comment by ArchiveBase** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/835

**Comment by ameshkov** [comment]
yep, indeed.

@Termi79 plz upvote #835
