### ISSUE TITLE
Unable to disable safe search.

### ISSUE THREAD

**Issue by davidbdeath** [AdguardTeam/AdGuardHome#1298]
Wow you guys really screwed up this release. Not only do custom client settings not apply. Safe search is on without ever turning it on and there is no ability to disable it. Effectivly rendering Adguard Home useless until it's fixed.

Filtered by SafeSearch
Status: NOERROR

**Comment by ameshkov** [comment]
Could you please try the beta version? The issue should be already resolved there.

**Comment by davidbdeath** [comment]
This isn't closed, how do you find the beta version?

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

**Comment by HoochieMamma72** [comment]
This is still an issue even with latest beta. Safe search enforced without any option selected in settings.

**Comment by ameshkov** [comment]
@HoochieMamma72 I am pretty sure it is not at least with the default settings.

What exact version of AG Home do you have?
What settings? Could it be that you have safe search enabled for a specific client?

**Comment by HoochieMamma72** [comment]
Hey @ameshkov 

All good, I figured it out. 

I have a Ubiquiti pro gateway and didn't realise there are 2 spots to put DNS settings. I was putting it into the WAN section in settings but you actually have to manually specify it in the DHCP section under Networking for clients to receive the DNS settings correctly. I was setting DNS for the WAN connection only!

Is this issue in the normal build or do I still need to run the latest beta for it to be resolved? (v0.100.9-91-g9a81)

Thanks, and great program by the way.
