### ISSUE TITLE
Why so many _services._dns-sd._udp.local  records in Query logs

### ISSUE THREAD

**Issue by lukemin** [AdguardTeam/AdGuardHome#1299]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.100.6
* **How did you setup DNS configuration:**
Windows 10
* **If it's a router or IoT, please write device model:**
 NO
* **Operating system and version:**
  CENTOS 7

### Actual Behavior

Lot of  _services._dns-sd._udp.local  records in Query logs from different ips
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
This is a special mDNS service discovery query. Apple devices (Bonjour service) send this query periodically.

**Comment by lukemin** [comment]
thanks a lot
