### ISSUE TITLE
receive specified signal just reload config/hosts not stop 

### ISSUE THREAD

**Issue by rufengsuixing** [AdguardTeam/AdGuardHome#1302]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

such as dnsmasq 
> When it receives a SIGHUP, dnsmasq clears its cache and then re-loads /etc/hosts and /etc/ethers and any file given by --dhcp-hostsfile, --dhcp-hostsdir, --dhcp-optsfile, --dhcp-optsdir, --addn-hosts or --hostsdir. The dhcp lease change script is called for all existing DHCP leases. If --no-poll is set SIGHUP also re-reads /etc/resolv.conf. SIGHUP does NOT re-read the configuration file.

i am the luci author of AdH,https://github.com/rufengsuixing/luci-app-adguardhome
i want to use signal to let AdG reload /etc/hosts ,because ipv6 device always change their ips and i set crontab to set them in /etc/hosts every hour , if i stop and  start Adh ,dns resolve maybe break for seconds,so is there any way to let Adh have a hot reload not breaking requests.

**Comment by ameshkov** [comment]
Makes sense, thank you!
