### ISSUE TITLE
简体中文翻译不全!

### ISSUE THREAD

**Issue by snakwu** [AdguardTeam/AdGuardHome#1304]
![QQ图片20191224233358](https://user-images.githubusercontent.com/5343595/71418562-02b40400-26a6-11ea-9db6-80061a8400c4.png)
![QQ图片20191224233319](https://user-images.githubusercontent.com/5343595/71418565-05aef480-26a6-11ea-9dac-31a3e7429fbb.png)

**Comment by ameshkov** [comment]
你懂英语吗？
你能助攻我们：https://kb.adguard.com/en/general/adguard-translations

**Comment by snakwu** [comment]
不好意思,英文只懂皮毛.

**Comment by hanson-l** [comment]
[1](https://github.com/AdguardTeam/AdGuardHome/blob/1e36deeedac9aba02e410bf5b7529a342a77beab/client/src/__locales/zh-cn.json#L77) [2](https://github.com/AdguardTeam/AdGuardHome/blob/1e36deeedac9aba02e410bf5b7529a342a77beab/client/src/__locales/zh-cn.json#L381)
Should `{{value}}` be changed to `{{count}}`?

**Comment by Mosney** [comment]
I will try to translate.

**Comment by lancelot-moon** [comment]
@aalpatkina 
The outmoded translations were fixed.
Please go to approve the correct translations.
https://crowdin.com/translate/adguard-applications/17566/en-zhcn#3905704
https://crowdin.com/translate/adguard-applications/17566/en-zhcn#3905714

**Comment by Mosney** [comment]
> I will try to translate.

Already done, please approve it.

**Comment by aalpatkina** [comment]
@Mosney your versions have been approved. Thanks

**Comment by ameshkov** [comment]
Please try the latest beta version of AdGuard Home, translations should be okay there

**Comment by lancelot-moon** [comment]
@aalpatkina 
https://crowdin.com/translate/adguard-applications/17566/en-en#3914743

The translation is only fixed in zh-TW, zh-CN and English locales.
Other languages' translators still don't fix it because they don't know you modified the English phrase.
You should disapprove it in other languages locales, with the exception of zh-TW, zh-CN and English locales.

**Comment by ameshkov** [comment]
@lancelot-moon Ildar has updated it in the application code.

However, you're right, we should fix these strings in Crowdin as well.

**Comment by snakwu** [comment]
最新的测试版在那里

**Comment by lancelot-moon** [comment]
@ameshkov 
The translation of `Error checking the DNS server status` in other locales are outmoded because you don't disapprove it on Crowdin.
Other translators don't know the change.

**Comment by ameshkov** [comment]
@lancelot-moon I just think that the mistake in English wouldn't be automatically made in the translations:)
