### ISSUE TITLE
Поиск по журналу / Search by journal

### ISSUE THREAD

**Issue by Yurkill** [AdguardTeam/AdGuardHome#1305]
Добавьте пожалуйста возможность поиска по дате в журнале.
При глубине поиска больше текущего дня становится не понятна дата запроса, то есть хотелось бы еще видеть столбец "дата".
В идеале это выглядело бы как дополнительное поле, где можно было бы задать фильтр по дате "с - по"
----
Please add the ability to search by date in the journal.
When the search depth is greater than the current day, the date of the query becomes unclear, that is, I would like to see the "date" column.
Ideally, this would look like an additional field where you could filter by date "from-to"

**Comment by ArchiveBase** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/481  https://github.com/AdguardTeam/AdGuardHome/issues/624

**Comment by ameshkov** [comment]
Duplicate indeed
