### ISSUE TITLE
Cannot auto-upgrade when I run ADG with separated bin, work dir and config file,

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1307]
Cannot auto-upgrade when I run ADG with separated `bin`, `work dir` and `config file`, 

> /usr/bin/AdGuardHome -c /etc/AdGuardHome.yaml -w /var/AdGuardHome -p 3000 -l syslog

It prints a log message below when I click upgrade button in WebUI:

`[info] rename /var/AdGuardHome/AdGuardHome /var/AdGuardHome/agh-backup/AdGuardHome: no such file or directory
`
  
**It looks like auto-upgrade script try mv old bin file to backup-dir from `work dir` but it not exists.**
As consequences, the auto-upgrade process has been terminated, and WebUI returns an error message.

**Comment by szolin** [comment]
> /usr/bin/AdGuardHome -c /etc/AdGuardHome.yaml -w /var/AdGuardHome -p 3000 -l syslog

I don't think this is a correct setup that you have.  Do you expect that auto-update mechanism will replace the binary in your `/usr/bin` directory?  I think it's wrong.

Auto-update code doesn't touch anything above `working directory` and we should keep it this way.
If you want your AGH instance be accessible from `/usr/bin` - just make a symlink.

**Comment by Mosney** [comment]
> Do you expect that auto-update mechanism will replace the binary in your /usr/bin directory?  

Yes, indeed.
>    /usr/bin/AdGuardHome -c /etc/AdGuardHome.yaml -w /var/AdGuardHome -p 3000 -l syslog

I run AGH on OpenWrt router which use a usb disk, and I hope reduce r/w on disk, so I put workdir to tmpfs and binary at normal disk fs (and config-file not put together too). 
And then on it will fail in the upgrade process, just because `confg-file` and `binary-file` (may include `config-file`) not in work dir.
I think don't touch anything above workdir is good, but this situation also needs to be considered.

**Comment by szolin** [comment]
To get the path to our executable at runtime we have to rely on Go library which, in turn, relies on OS-specific functionality.  If it's used for read-only purposes - no problem.  But to rewrite this file?  I don't think that most users want this behaviour.
However, we can add a configuration setting `binary_path "/usr/bin"` to achieve what you want for your setup.  But I don't like this solution either.

It would be better if you just create a symlink `agh-workdir/data -> /tmp/agh-data`.  This way you'll have:
1. Your binary file is within workdir
2. Your data files are on tmpfs.
And the problem is solved!

**Comment by Mosney** [comment]
That's ok, I agree with that it is not necessary to specify binary path in setting. But did you thought about any file in tmpfs will lose after reboot? 
I came up with 2 solutions now, both needs make a script:
- Make a script to backup binary before shutdown and restore after boot.
- Make a script to download the latest binary after boot, practically no need to web-UI upgrade anymore.
I think there must be some better solution, any idea?

**Comment by szolin** [comment]
no-no, it's simple.  Your workdir should be on USB storage - binary file won't get erased on reboot.  But `data` directory is a symlink to tmps - yes, it will be erased on reboot.  I guess you can have a script that creates a directory `/tmp/agh-data` on startup and that's all.

**Comment by Mosney** [comment]
That's correct, I have limits imagination just now. Thx a lot.

**Comment by Mosney** [comment]
Wait a minute, the original issue is upgrade failed when run AGH like me, so I think it may add a detection mechanism this situation and pop-up prompt after click upgrade button, no need really do upgrade process, and the important thing is user could know why cannot auto-upgrade.

**Comment by Mosney** [comment]
Of course that's an user experience enhance option.

**Comment by szolin** [comment]
You're right, it will be a nice addition to a user-friendly update process.
