### ISSUE TITLE
Non-standard path for certificates on Entware

### ISSUE THREAD

**Issue by Rootdiv** [AdguardTeam/AdGuardHome#1311]
На роутерах Keenetic в Entware путь к сертификатам будет /opt/ect/ssl и изменить его не возможно. Сделайте пожалуйста проверку сертификатов по этому пути для AdGuard Home mips и mipsle.

Листинг прошивочного каталога /etc
`TZ                devices           hosts             mtab              passwd            profile           resolv.conf       uci-defaults
components.xml    group             localtime         nginx             ppp               protocols         services          wlan
cpe.pem           host.conf         modules.autoload  nsswitch.conf     preinit           rc.common         shells`

Листинг каталога /opt/etc/ssl в Entware
`certs        openssl.cnf  private`

**Comment by ameshkov** [comment]
By default, Go looks for root certificates here: https://golang.org/src/crypto/x509/root_linux.go

We should find a way to search more directories.

**Comment by pomazanbohdan** [comment]
ssl dir for padavan /ect/ssl (not opt/ect/ssl)
