### ISSUE TITLE
Can't compile arm5, arm6, arm7 binaries? !

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#1313]
![image](https://user-images.githubusercontent.com/45259624/71480462-18efca80-2834-11ea-9688-1f601fcf80e8.png)

**Comment by ameshkov** [comment]
Why? What happens?

**Comment by zxlhhyccc** [comment]
> Why? What happens?

If I change to screenshot mode, I'll still compile the arm binary...

**Comment by ameshkov** [comment]
We'll fix it here: https://github.com/AdguardTeam/AdGuardHome/issues/1239
