### ISSUE TITLE
Safe mode still an issue.

### ISSUE THREAD

**Issue by davidbdeath** [AdguardTeam/AdGuardHome#1315]
Safe search is still on regardless of how I set it. Is there a way to completely disable it? Will there a be a fix soon?

**Comment by ameshkov** [comment]
I cannot confirm this bug in v0.100.8.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by davidbdeath** [comment]
It's a fresh install of Raspbian on a Pi with a fresh install of Adguard. It is not likely that it's my system. I don't have safe search on globally or on my clients custom setting. The DHCP server is active on AdGuard. I don't have time anymore to trouble shoots AdGuard with every new release.

**Comment by ameshkov** [comment]
> > The DHCP server is active on AdGuard

This might be important indeed, but I can't test it right now.

We'll check if we can reproduce it next week when everyone's back from vacations.

**Comment by slipx06** [comment]
I have the same problem. SafeSearch is always enforced even if disabled at client level. Running Version: 
v0.100.8

**Comment by ameshkov** [comment]
@slipx06 does it go away after restarting AGH?

**Comment by davidbdeath** [comment]
It does not and it does not go away after wiping my Pi and doing a fresh install.

**Comment by slipx06** [comment]
> @slipx06 does it go away after restarting AGH?

Nope

**Comment by szolin** [comment]
@davidbdeath 
I can't reproduce it.  What's your yaml config?

@slipx06 
> Using settings for client with IP 192.168.1.99

Safe search is enabled for your client, so it will be enabled for it no matter what your global setting is.

**Comment by slipx06** [comment]
Its not according to the GUI

![image](https://user-images.githubusercontent.com/7227275/72060896-8b08ea80-32dd-11ea-94fb-6ea74b0be8f6.png)

**Comment by szolin** [comment]
@slipx06 Thank you!  You've found a bug from April 2019.  The settings for SS and SB were mistakenly reversed.

**Comment by szolin** [comment]
@davidbdeath 
> Safe search is still on regardless of how I set it

What do you mean it's still on?  What's shown in GUI?  Please search in your AGH debug logs - do you see the lines with `SafeSearch` there?

**Comment by ameshkov** [comment]
@davidbdeath unfortunately, we still cannot reproduce this issue even when the DHCP server is active (unless you have the same thing as @slipx06).

If your situation is different, it would really help if you could [record the log](https://github.com/AdguardTeam/AdGuardHome/issues/1315#issuecomment-569962175). Once we have it is trivial to figure out what was the problem.

**Comment by davidbdeath** [comment]
I only have the problem on clients i have custom filter settings for. I stopped using custom settings on my tower temporarily and adjusted my global settings to compensate.

**Comment by ameshkov** [comment]
> I only have the problem on clients i have custom filter settings for

Could it be that you had "browsing security" enabled for these clients?

**Comment by davidbdeath** [comment]
I'm sure I did. Are you saying browsing security is broken?

**Comment by ameshkov** [comment]
@davidbdeath the problem is that "browsing security" and "safe search" settings were reversed in the per-client settings: https://github.com/AdguardTeam/AdGuardHome/issues/1315#issuecomment-572530139

So I guess you have the same issue as @slipx06 and it'll be fixed soon. Thank you!

**Comment by davidbdeath** [comment]
Maybe put that on the front page of the github nice and big

**Comment by szolin** [comment]
#1339

**Comment by AnthonyBe** [comment]
Ahhh.. So this explains why my son kept complaining about strict search being enabled even though I had disabled it in his client filter!!!
