### ISSUE TITLE
DNS service upgrade

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1316]
Openwrt x64 
Hope add KadNode function in AdguardHome,
support peers addresses urls and ip filtering by users;
Privacy:enable DHT(DECENTRALIZED NETWORK),Peer Exchange (PeX),Local Peer Discovery to find more peers,enable anonymous encryption mode,random port,enable protocol TCP and uTP;
if support Gnutella2、Gnutella、eDonkey network is more better,need add Dynamic Leecher Protection,Powerrelease with dynamic Hide OS,
Thank you!

**Comment by ameshkov** [comment]
Well, there are too many feature requests for a single Github issue.

Could you please open a new issue for each one of them?

It would also be helpful if you add a detailed explanation on every feature -- what it does, why we should add it, etc.
