### ISSUE TITLE
Cannot Delete Client when IP not active

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#1317]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.8
* **How did you setup DNS configuration:**
  * Windows Server 2012 R2 DHCP Server
* **If it's a router or IoT, please write device model:**
  * n/a
* **Operating system and version:**
  * Windows Server 2012 R2

### Expected Behavior
I should be able to delete a Client from the Client Settings page at any time

### Actual Behavior
When I attempt to delete a Client (based on IP address) that is not currently active on the network I get the following error:

`Error: control/clients/delete | Client not found | 400`

### Screenshots
<details><summary>Screenshot:</summary>

![msedge_2019-12-28_14-44-47](https://user-images.githubusercontent.com/17214552/71538526-ad674380-2980-11ea-86e6-adf386b42775.jpg)

</details>

### Additional Information
This may be a related bug, but when I added 2 additional IP addresses to the Client rule that already contained the IP that was not active, I ended up with 2 identical entries for the Client on the Client Settings page. They both had the same name, the same 3 IP addresses, etc. Once the above bug is resolved, I will re-test this duplicating one but I suspect they are related.

**Comment by ameshkov** [comment]
Nice bug, thank you for reporting it!

**Comment by AnthonyBe** [comment]
Always a pleasure to contribute!

**Comment by szolin** [comment]
I can't reproduce it.  Can you post your clients data from yaml file?

**Comment by AnthonyBe** [comment]
I've just retried it and (frustratingly) it's working perfectly now.

The only thing I can think is that the very first Client (using matched IP) I created when the feature first became available. Possibly something funky occurred with the various schema upgrades since then... of maybe I just some weird file locking issue.
