### ISSUE TITLE
Auto closing of menu sidebar after choosing

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#1318]
AdguardHome v0.100.8
Installed on RaspberryPi 4B
Sony Xperia X with Android 8.0.0
Opera Browser Mobile v55.2

Problem: 
I am using the AdGuardHome GUI with the Opera mobile Browser on my Smartphone. 
If I go to menu button in upper left corner, the sidebar opens and I can choose (for example) "filter" then the site opens, but the sidebar is still open and I have to touch the display so the sidebar disappear.

Solution:
After the "filter" site has been selected and opens, the sidebar should disappear without user interaction.

What also would be great is when menu sidebar can be open thru swiping from left display site to right. (on mobile devices)

Thanks for your great work

**Comment by ArchiveBase** [comment]
smartphones related #978
