### ISSUE TITLE
Cookie warnings remove

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#1319]
Hello is there any way to add an Cookie domainlist?
Its very annoying on each site to accept this massages, if its can be blocked with AdGuardHome it would be great.

Thank you

**Comment by ameshkov** [comment]
Most of the cookie notices filter lists use cosmetic rules, and it's not possible to apply them on the DNS level.

Eventually, when we add proxy support #391 you'll be able to apply cosmetic rules.

**Comment by uservictor** [comment]
This would be great.
Besids the ads, cookie warning messages are the most annoying thing on on almost each website on the internet.
