### ISSUE TITLE
ADguard Home Install on Windows, DoH Error

### ISSUE THREAD

**Issue by kankankankankankan** [AdguardTeam/AdGuardHome#1320]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  Windows：0.100.8

* **How did you setup DNS configuration:**
  * Encryption settings configured successfully
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * win2008 x64

### Actual Behavior
Encryption settings are configured successfully and cannot be used normally

### Screenshots

<img width="977" alt="Safari 浏览器_2019-12-31 18-00-17@2x" src="https://user-images.githubusercontent.com/11487346/71617914-51a6ef80-2bf8-11ea-9b72-43ff4fc5e2bc.png">

<img width="663" alt="iTerm2_2019-12-31 18-15-22@2x" src="https://user-images.githubusercontent.com/11487346/71618218-b3b42480-2bf9-11ea-913e-160d06558b34.png">

</details>

### Additional Information

After the configuration is complete, the terminal runs `curl` Bad Request, how to make` curl` parse normally?

**Comment by szolin** [comment]
Can you set `verbose:true` in config and show verbose application logs?

**Comment by ameshkov** [comment]
Wait, the requests you're trying to send are not valid DNS-over-HTTPS requests.

Try using this tool instead:
https://github.com/ameshkov/dnslookup

**Comment by sh3bang** [comment]
same issue: when i do DoH request, i got a 400 Bad Request message. Adguard Logs:

2023/10/08 19:43:00.756272 1#150 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).ServeHTTP(): Incoming HTTPS request on /dns-query
2023/10/08 19:43:00.757213 1#150 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).ServeHTTP(): Wrong HTTP method: OPTIONS
