### ISSUE TITLE
Gateway is the only client

### ISSUE THREAD

**Issue by tomjanda** [AdguardTeam/AdGuardHome#1322]
Hi,
I just installed AdGuard home on my ASUSTOR NAS and it blocks ads great ;)

I have only one issue, that my Unify Security Gateway (router and DHCP server) is the only client with requests. Maybe I missed something in setup (I used AdGuard wizard for router), so I did not report this as bug.

As a result of this, I cannot use client specific features such as stats or settings. It does not blocks me in using AdGuard now as I use only adblock features, but in near future, I would probably use parental control features ...

Thanks,
Tom

**Comment by ameshkov** [comment]
Well, it sounds as if your router is just working by proxying DNS queries. I am not sure if this can be changed, you should check its documentation.

Please reopen if there is anything we can help with.
