### ISSUE TITLE
Make IPv6 localhost IPs in «Hosts»-syntax entries synonymous with "regular" IPv4 localhost IPs

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1328]
### Prerequisites

- [x] I am running the latest version (v0.100.8)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Hosts-syntax entries that use `::`, `0` or `::1` as prefixes (e.g. `:: example.org`, are currently not supported by AdGuard Home.

Although AGH's IPv6 support in general is fairly limited, at least as far as DNS server capabilities go, I do think it should be feasible to make it so that `::`, `0` and `::1` would be synonymous with `127.0.0.1` and `0.0.0.0` for the purposes of using «Hosts» filters and filterlists.

#### Lists known to be directly affected by the lack of support, are:

* https://raw.githubusercontent.com/abc45628/hosts/master/hosts
* https://raw.githubusercontent.com/arcetera/Minimal-Hosts-Blocker/master/etc/MinimalHostsBlocker/minimalhosts
* https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
* https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHostsCB/etc/MinimalHostsBlocker/minimalhosts
* https://raw.githubusercontent.com/TakoYachty/Gift-Card-Killer/master/Untrusted%20Hosts%20Blocker.txt

#### Much less affected, but is an example of someone using `::1`:

* https://someonewhocares.org/hosts/ipv6/hosts

### Proposed Solution

Make `::`, `0` or `::1` synonymous with `127.0.0.1` and `0.0.0.0`, or in some other way make AdGuard Home treat them as if they were `127.0.0.1` all along.

### Alternatives Considered

Having AdGuard Home be able to treat IPv6 IPs natively would've been even better, which'd also add support for https://raw.githubusercontent.com/lennylxx/ipv6-hosts/master/hosts and https://raw.githubusercontent.com/popcorner/cernet-ipv6-hosts/hosts/hosts, but I presume that'd require much, much more work to accomplish.

### Additional Information

None that I'm aware of.

**Comment by ameshkov** [comment]
> Hosts-syntax entries that use ::, 0 or ::1 as prefixes (e.g. :: example.org, are currently not supported by AdGuard Home.

Wait-wait, last I checked they were supported

**Comment by DandelionSprout** [comment]
If it ever did work, it doesn't seem to do so now as far as I can personally determine. None of these entries:

```
:: www.nrk.no
0 www.nrk.no
::1 www.nrk.no
```

...prevents `www.nrk.no` from being loaded.

**Comment by DandelionSprout** [comment]
I've now also made a test list at https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/AGHSyntaxTester.txt that aims to keep track of whenever new syntaxes have become supported by AGH, and I've also added the IPv6 localhosts to them now.

**Comment by ameshkov** [comment]
> prevents www.nrk.no from being loaded

Ah, got it.

If `::` is specified, it covers IPv6 (AAAA) DNS queries only.

You know, once #1284 is done, it should start working as you want when `NXDOMAIN` is chosen.
It already should be working properly in the Null IP mode.

But in the default mode it tries to emulate hosts files and that's why the difference.

**Comment by DandelionSprout** [comment]
It took me some 40min to make my phone willing to load IPv6 pages properly so that I could test it, but it appears that `::` entries does indeed work in the way you described it as (e.g. blocks only IPv6 requests when in `NXDOMAIN` mode), as does `::1` from the looks of the one applicable test of it I could do tonight.

I'll also assume that IPv6 non-localhost redirection lists à la https://raw.githubusercontent.com/lennylxx/ipv6-hosts/master/hosts will work as intended for their target audiences, and not just for me in my very safe little corner of Norway (who also couldn't find a way to turn off 

That appears to leave us with just `0` still remaining. which leaves AGH in the same situation as https://github.com/uBlockOrigin/uBlock-issues/issues/847, should there for some reason be a synchronisation desire between you guys and gorhill.

**Comment by DandelionSprout** [comment]
That being said, if `::`/`::1` only works for AAAA when using stock settings... then wouldn't the logical outcome be that `127.0.0.1`/`0.0.0.0` would only work for A?

**Comment by ameshkov** [comment]
> then wouldn't the logical outcome be that 127.0.0.1/0.0.0.0 would only work for A instead of blocking both A and AAAA?

Hmmm, yeah, we made an exception for 0.0.0.0 after all, I guess `::` and `::1` are basically the same and we can make exceptions for them as well.

**Comment by ameshkov** [comment]
Wait, I am actually wrong.

We should simply implement /etc/hosts logic properly.

If `:: example.org` is specified in the hosts file:

* `AAAA` query will return `::`
* `A` query will return NXDOMAIN

The idea is that when there's at least one entry in the hosts file for a domain, we should return only the IP addresses specified there.
