### ISSUE TITLE
Client shows 0.0.0.0

### ISSUE THREAD

**Issue by cruunnerr** [AdguardTeam/AdGuardHome#1329]
Hi guys,

I use the actual Version of AdGuard Home. **_Since i updated_** last time I have multiple Query logs show "0.0.0.0" as Client address.

I captured the NIC of my Router to see what happens there... So the client with the IP "10.10.20.203" sends DNS request to my AdGuard Home Server (10.10.10.10).
Adguard sends to the client the IP "0.0.0.0" and in the Web Interface AdGuard shows me, that the Client-Address would be "0.0.0.0"....

I don't understand that.... Sorry guys. Not the best IT-specialist ^^

<img width="1460" alt="Bildschirmfoto 2020-01-04 um 10 10 00" src="https://user-images.githubusercontent.com/22455230/71763432-2bc16980-2edc-11ea-923b-6272797b3938.png">
<img width="1071" alt="Bildschirmfoto 2020-01-04 um 10 10 16" src="https://user-images.githubusercontent.com/22455230/71763433-2c5a0000-2edc-11ea-9915-231e0e2f352b.png">

Edit:
Oh, and it's just a normal Filter-List:
https://raw.githubusercontent.com/cruunnerr/Adguard/master/Blocklist.txt

**Comment by nelox** [comment]
> I have multiple Query logs show "0.0.0.0" as Client address.

I observe the same behaviour (AdGuardHome v0.100.8):

<img width="1128" alt="Screen Shot 2020-01-06 at 19 19 02" src="https://user-images.githubusercontent.com/2967891/71806109-11de7d00-30bc-11ea-8f99-3618df5df7a4.png">

Filter list:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by htjain** [comment]
+1

**Comment by Mosney** [comment]
ditto, rule is https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/full/hosts.txt
![image](https://user-images.githubusercontent.com/22477230/71900790-79b6c580-3199-11ea-9c4e-329d66ecd447.png)

**Comment by szolin** [comment]
Yes, thank you!
A quick fix is coming...
A normal fix will be in #882 where we will stop using "Result"{} json object in logs.
