### ISSUE TITLE
Client Fehler / Client error /

### ISSUE THREAD

**Issue by mcdj0815** [AdguardTeam/AdGuardHome#1331]
### Prerequisites
Clients (runtime)
Data on the clients that use AdGuard Home but are not saved in the configuration are not displayed. No filter requests from the client were listed

Clients (Laufzeit)
Daten zu den Clients, die AdGuard Home verwenden, aber nicht in der Konfiguration gespeichert sind werden nicht angezeigt

Es werden keine Filterabfragen vom Client gelistet->

### Issue Details

* **Version of AdGuard Home server:**
Version: 
v0.100.8
* **How did you setup DNS configuration:**
Router - DNS 192.168.1
* **If it's a router or IoT, please write device model:**
 Raspberry Pi 4 Model
* **Operating system and version:**
Debian

**Comment by ameshkov** [comment]
Could you please explain what's the problem with a little bit more details?

I don't yet understand what's the problem
