### ISSUE TITLE
[Help] I don't know why this happened and I can't seem to fix it...

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#1332]
I've tried restarting both AdGuard Home and Windows and it doesn't seem to fix this...

![image](https://user-images.githubusercontent.com/39284087/71774394-bef2b180-2f65-11ea-871c-d37115f85cee.png)

When I hover over any of the top statistics 

![image](https://user-images.githubusercontent.com/39284087/71774402-ea759c00-2f65-11ea-8061-f1f625d4c90b.png)

**Comment by Cybo1927** [comment]
Update: It just logged me out and when I relogged it's all working now but the CMD shows some stuff

![image](https://user-images.githubusercontent.com/39284087/71774733-e0ef3280-2f6b-11ea-92da-882b80c29baa.png)

**Comment by ameshkov** [comment]
@szolin do you have any idea?

**Comment by szolin** [comment]
I think your yaml file is corrupted.

Find all your `blocked_services` sections and replace them with `blocked_services: []`.
If you'll be able to reproduce the steps how to corrupt the config file this way - please reopen the issue.
