### ISSUE TITLE
Simplified Chinese translation audit

### ISSUE THREAD

**Issue by JACK-THINK** [AdguardTeam/AdGuardHome#1334]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Additional Information

I have made a lot of changes to the tranlation into Simplified Chinese, Please give [them](https://crowdin.com/translate/adguard-applications/17566/en-zhcn) an audit.

**Comment by aalpatkina** [comment]
@JACK-THINK your translations were approved on Crowdin. We will add them to AG Home in the next release.
