### ISSUE TITLE
AdGuard Home is showing router as a top client instead of devices connected through WiFi

### ISSUE THREAD

**Issue by BasilGFX** [AdguardTeam/AdGuardHome#1335]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version (v0.100.8)
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

AdGuard Home is showing the router as a top client instead of devices connected through WiFi
i am using Raspberry Pi 4, I didn't face the same issue when i installed AdGuard Home on my laptop.

![Screenshot_2020-01-07 AdGuard Home](https://user-images.githubusercontent.com/3459064/71834884-3dc52700-30eb-11ea-89d3-14bdedbf345f.png)

My PC is connected through Ethernet.

**Comment by ameshkov** [comment]
Please check the query log, what DNS queries are made from the router?

**Comment by XENORCHISM** [comment]
> Please check the query log, what DNS queries are made from the router?

It's from both my iPhone and iPad, only devices connected through Ethernet are shown with their own IP address.

**Comment by BasilGFX** [comment]
> Please check the query log, what DNS queries are made from the router?

It's from both my iPhone and iPad, only devices connected through Ethernet are shown with their own IP address.

**Comment by DandelionSprout** [comment]
I've noticed that the localhost is shown instead of the client, but almost only when I used DNS-over-HTTPS, which I attributed it to me using an Asuscomm dynamic DNS address as the encryption server address. So I suppose that I'm not the best source of info on this.

**Comment by WildByDesign** [comment]
I had this same issue initially. What you have to do is create a firewall rule on the device that is running AdGuardHome that forwards all DNS requests from the regular DNS port listening on your device (likely 53) to the DNS port that AdGuardHome is listening on (possibly 5353 or whatever you have set). This way, the IP address of WiFi devices will pass through correctly to AdGuardHome.

**Comment by BasilGFX** [comment]
> I had this same issue initially. What you have to do is create a firewall rule on the device that is running AdGuardHome that forwards all DNS requests from the regular DNS port listening on your device (likely 53) to the DNS port that AdGuardHome is listening on (possibly 5353 or whatever you have set). This way, the IP address of WiFi devices will pass through correctly to AdGuardHome.

Didn't work

**Comment by ameshkov** [comment]
I suppose this is a router-specific issue. It might be proxying DNS queries and that's why the router itself becomes the "client".

**Comment by BasilGFX** [comment]
> I suppose this is a router-specific issue. It might be proxying DNS queries and that's why the router itself becomes the "client".

I didn't face the same issue when i installed AdGuard Home on my laptop.

**Comment by midniteslice** [comment]
I had this same issue with a linksys router. I set adguard as the dns server in the dhcp settings, but all my clients populated with the ip of the router as the dns server, adguard also showed it as the only device making queries. I set up an isc dhcp server and the problem disappeared. Went back to the router dhcp and it came back. I have since gone back to the isc dhcp server just becuase...
I'm not at all sure what the reasoning is for this kind of behaviour, but i don't think that it's an adguard home issue. I think it's an issue with how some devices handle things when they are the dhcp server. 
Sorry for the lack of *good* input, but thats all I got. :-)

**Comment by DandelionSprout** [comment]
I've stumbled across another possible solution that I'm surprised that I had forgot for several months:

Are you connecting through a non-localhost IP (e.g. `123.45.67.89`)? That would make the client being shown as the router, even if you're on the same network. If the problem miraculously turns out to be *that* simple, switching the primary DNS server to AGH's LAN address (e.g. `192.168.1.123`) will make the client show up correctly.

**Comment by szolin** [comment]
When you configure wifi router to use AGH as a gateway you should set `Act as Access Point` setting in your router's configuration.  Otherwise it may not pass your device IP through to AGH.  That's why AGH sees only wifi router's IP address.

**Comment by phildespres** [comment]
In my case, this issue was caused by "Use DNSMasq for DNS" being checked in my DD-WRT config.

**Comment by speedster-pta** [comment]
I have a similar issue, excepting that the IP address shown in AGH is my current external IP.

**Comment by ybjlus** [comment]
> In my case, this issue was caused by "Use DNSMasq for DNS" being checked in my DD-WRT config.

Oh I'm so glad I found your comment haha! One little checkbox solved all my problems. Can confirm on ddwrt this solved the issue.

**Comment by vadimka83** [comment]
> I have a similar issue, excepting that the IP address shown in AGH is my current external IP.

I'm having the same issue while using OpenWRT on my router. Do you know how to solve this on OpenWRT router?

**Comment by zohrlaff** [comment]
For anyone using Tomato on their router, the setting that fixes this is called "Use internal DNS" which is under _Advanced_ > _DHCP/DNS_.

**Comment by adamrgolf** [comment]
> 

I'd like to know this too. Any update for OpenWRT users?

**Comment by hunson817** [comment]
> > 
> 
> I'd like to know this too. Any update for OpenWRT users?

I had the same question and this here worked for me: https://forum.gl-inet.com/t/gl-mv1000-with-adguard-all-clients-show-as-localhost/13664

Create a port forward rule from port 53 to 5353 (or whatever you chose as your ADH port). 
So the same solution as on Jan 8, 2020 from [WildByDesign](https://github.com/WildByDesign)

**Comment by adamrgolf** [comment]
> > > 
> > 
> > 
> > I'd like to know this too. Any update for OpenWRT users?
> 
> I had the same question and this here worked for me: https://forum.gl-inet.com/t/gl-mv1000-with-adguard-all-clients-show-as-localhost/13664
> 
> Create a port forward rule from port 53 to 5353 (or whatever you chose as your ADH port). So the same solution as on Jan 8, 2020 from [WildByDesign](https://github.com/WildByDesign)

Thank you, this was very helpful! Cheers!
