### ISSUE TITLE
DNS rewrites not work

### ISSUE THREAD

**Issue by Expert73** [AdguardTeam/AdGuardHome#1338]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

DNS rewrites not work. I am trying to redirect a test.com entry to a local resource 192.168.1.99. And it does not work

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by szolin** [comment]
1. Create a Rewrite entry `test.com  -> 192.168.1.99` in UI
2. Perform DNS lookup via `nslookup` and show us the output.
Please reopen the task then.

**Comment by igrybkov** [comment]
just in case somebody would come here from google, somehow I've got `filtering_enabled` set to `false` in the config and this was the reason for me. Changed it to `filtering_enabled: true` and everything works now.
