### ISSUE TITLE
SafeSearch not working per-device (per IP address)

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#1339]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.8
* **How did you setup DNS configuration:**
  * Router (firewall forwarding port 53 to AGH on port 5353)
* **If it's a router or IoT, please write device model:**
  * Linksys WRT3200ACM
* **Operating system and version:**
  * OpenWrt 19.07.0

### Expected Behavior
I have AdGuardHome working great on OpenWrt router operating system.  The only thing that is not working correctly is SafeSearch per-device. SafeSearch works fine globally, but I only want SafeSearch setup per-device for two specific IP addresses.

Per-device (per IP address) is working correctly and is blocking individual services correctly, such as Facebook. Individual DNS servers is working as well. But SafeSearch is not working per-device at all, unfortunately.

### Actual Behavior
SafeSearch is not working on a per-device (per IP address) basis at all.

### Additional Information
 DNS cache has been flushed on devices and router, AGH has been restarted, etc. I have completed 2-3 hours of troubleshooting based on this issue but have had no success and therefore decided it is time to file this bug report. 

Please let me know if there is any other details or troubleshooting steps that I can take to help resolve this bug. thank you.

**Comment by WildByDesign** [comment]
I noticed the following commit today: https://github.com/AdguardTeam/AdGuardHome/commit/4386e8ddde296f270fada3deba43a48b53b5da4c

I assume that this SafeSearch / SafeBrowsing reversal bug was likely the cause of this issue as well. Thankfully it appears to be a quick fix.

Is there going to be a new beta build or release so that we can test this fix out?

Thank you.

**Comment by ameshkov** [comment]
Yeah, there will be a beta version.

If you're using Docker, you can use the "edge" tag -- it is synced with the master branch.
