### ISSUE TITLE
Modify client name bug

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#1340]
#### Issue Details

- Add a client with specific name ex: desktop
- Modify client name ex: desktops and save then you'll see duplicate clients.
- It's not possible to delete that duplicate client too.

Windows 1909 | v0.100.8

**Comment by ameshkov** [comment]
Nice bug, thank you!

**Comment by szolin** [comment]
v0.100.7 regression

**Comment by AnthonyBe** [comment]
Hmm.. I suspect _this_ might be the underlying cause of my bug (https://github.com/AdguardTeam/AdGuardHome/issues/1317) because at one point I also saw duplicates
