### ISSUE TITLE
Does DNS rewrites support multi-to-one?

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1343]
I want to capture all NTP domain in my network and let them all rewrite to a local NTP server, so is it possible to add a multiple items rewrite to an item? 

![image](https://user-images.githubusercontent.com/22477230/72083484-de5e5580-333c-11ea-9b74-232ecd776531.png)

**Comment by ibksturm** [comment]
i dear, i have the same problem at home, ghe solution was i did some firewallsettings with iptables.

the rule is on openwrt, that all traffic on port 123 (ntp) should forward to my own ntp server

ill put in a few minutes a printscreem of

**Comment by ibksturm** [comment]
![5C612D68-7E69-4FA2-814B-FE0805702B4E](https://user-images.githubusercontent.com/35167101/72084986-c965d000-3304-11ea-91b2-69d65e385e3d.jpeg)

**Comment by Mosney** [comment]
That's ok, but I want to rewrite to a pool.ntp.someserver.com to replace, not a real "local server", just for easy to talk.
Anyway, thanks your solution, it's quite good.

**Comment by ibksturm** [comment]
@Mosney same vision as i got months ago

a) solution first: for every ntp address (like time.apple, some samsungsmarttv shit, ntp.ubuntu, ntp.openwrt and so on) i did name rewrites... was a long long list, thats true

so then i look on the otherside of the moon and tada, solution

b) was born. better than to dns rewrite every ntp adress (you will never ever catch all) i did a iptables rewrite of port 123. on openwrt router (192.168.0.1) i‘m running local ntp server, which sync with 0.ch.pool.ntp.org, 1.ch.and-so-on. in a debian server system (debian, ubuntu server etc) you could also configure a local ntp server with a few clicks

or as i think loud, maybe you will forward all port 123 packets to ip address of your external ntp server

**Comment by Mosney** [comment]
Sounds good, but in plan b, deploy a local NTP forwarder may increase vulnerability on the whole. 
So, redirect all port 123 packages to an anycast NTP IP may better now.
Besides, did you found 'Average processing time' in AGH dashboard increase after adding a few rewrites rules?

**Comment by ameshkov** [comment]
Regarding the original question, you simply need to add multiple DNS rewrite entries.
