### ISSUE TITLE
Unified management panel and filtering IPv6 addresses

### ISSUE THREAD

**Issue by shen09** [AdguardTeam/AdGuardHome#1344]
1. Multi-server nodes, cluster deployment, whether multiple servers using AdGuardHome can be managed uniformly through a management panel, such as setting node dns, filtering ads, etc.
Unified management panel is similar to https://www.appnode.com/ for reference only
2. Can AdGuardHome filter ipv6 addresses, domain names containing ipv6 addresses do not respond directly, and return ipv4 addresses

**Comment by ameshkov** [comment]
> Multi-server nodes, cluster deployment

Maybe in some quite distant future, but not now.

> Can AdGuardHome filter ipv6 addresses, domain names containing ipv6 addresses do not respond directly, and return ipv4 addresses

There will be such an option in v0.101.
