### ISSUE TITLE
Send query logs to remote syslog server

### ISSUE THREAD

**Issue by copacetic82** [AdguardTeam/AdGuardHome#1346]
### Prerequisites

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Problem Description

I am running AGH on CentOS (verison numbers below). I need to forward the query logs to a remote syslog server (e.g. splunk). I have tried using the "log_file" parameter (https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration), but no success. 

AGH Version: v0.100.8
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1062.9.1.el7.x86_64
      Architecture: x86-64

### Proposed Solution
It would be useful to include an option in the GUI to specify a remote syslog server to send query logs to.

### Alternatives Considered
Send query logs to e.g. /var/log/messages

**Comment by ameshkov** [comment]
Please read the answer here: https://github.com/AdguardTeam/AdGuardHome/issues/958#issuecomment-548762723
