### ISSUE TITLE
Update not working after reboot!

### ISSUE THREAD

**Issue by nurb2kea** [AdguardTeam/AdGuardHome#1347]
On macos 10.15.2 doing an update and reboot, Adguar Home isn't working anymore.
When replacing this updates back to Version: v0.100.8 it works.

BUT THIS :AdGuard Home v0.100.8-16-g318e VERSION aren't going to work.

That error happed with the AdGuard Home BLABLA.......-16-g318e and other inbetween Versions before.

Even when doing a brand new install with a BLABLA...-16-g318e -VERSION...

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
@nurb2kea 
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by szolin** [comment]
the latest beta works fine on macos 10.14.6

**Comment by nurb2kea** [comment]
no useful info... :-(



On 14 Jan 2020, at 1:19 pm, Simon Zolin <notifications@github.com> wrote:

the latest beta works fine on macos 10.14.6

BUT NOT ON C64...! dh

**Comment by szolin** [comment]
What's not working exactly?  Please post a screenshot or copy-paste the output you see in terminal.

**Comment by nurb2kea** [comment]
see initial mail...

On 14 Jan 2020, at 4:45 pm, Simon Zolin <notifications@github.com> wrote:

What's not working exactly? Please post a screenshot or copy-paste the output you see in terminal.

**Comment by szolin** [comment]
> see initial mail...

There's nothing useful

**Comment by nurb2kea** [comment]
Install AG Home beta (v0.100.9.xyz.123.....) versions, and it runs until you restart macos 10.15.2.
Then the website tells you that AG Home is running but you’ll get only ‘resolving host’ in any app.

with sudo ./AdGuardHome -s uninstall AND and restart,
and sudo ./AdGuardHome -s install it’ll work, but not with the beta (v0.100.9.xyz.123.....) versions

you can replicate this easy, every time.
Just use macos 10.15.2 and installfor example v0.100.8 and let it run via sudo ./AdGuardHome -s install
Then hit the update to beta button. and let it install the beta. (example:v0.100.9.xyz.123.....)
It’ll work until you restart you macOS.

Then you have to sudo ./AdGuardHome -s uninstall AG Home drag the AG Home app out of your install folder (HDD/users/user)
and restart. Then copy the AG Home  v0.100.x Version app back to your install folder (HDD/users/user) and sudo ./AdGuardHome -s install
If you are lucky then it works with the v0.100.x VERSIONS but not with the v0.100.x.abc.123.... VERSIONS

Hope that helps, don’t have time to give you a full bugreport.

On 14 Jan 2020, at 5:29 pm, Simon Zolin <notifications@github.com> wrote:

see initial mail...

There's nothing useful

**Comment by ameshkov** [comment]
Well, it sounds super weird. I can't reproduce even your initial issue (with AGH now working after reboot) on my Catalina machine.

**Comment by nurb2kea** [comment]
I just came back from my dad’s macbook, and updated from 100.8 to100.9 and the same happened, on another machine.
Install + reboot + not working.

fix:
after reboot, drag AGH out of the folder and uninstall the service via terminal.
Put the AGH app back into the folder and install the service again.

nuffsaid



On 14 Jan 2020, at 8:35 pm, Andrey Meshkov <notifications@github.com> wrote:

Well, it sounds super weird. I can't reproduce even your initial issue (with AGH now working after reboot) on my Catalina machine.

**Comment by ameshkov** [comment]
Could please define "not working"?

Does the AdGuard Home service start successfully?
What do you see in the web admin interface?
What happens if you run `nslookup example.org 127.0.0.1` after the reboot?

**Comment by ameshkov** [comment]
Well, there's one thing I discovered that might be relevant. It seems pretty important for Catalina that the app must run from the "Applications" folder otherwise it does not allow us modifying files in the app folder. Other than that, I observe no issues on Catalina - update works smoothly, everything works properly after the reboot.

**Comment by nurb2kea** [comment]
we’ll see in the next update...

thanks in advance

On 15 Jan 2020, at 10:53 am, Andrey Meshkov <notifications@github.com> wrote:

Well, there's one thing I discovered that might be relevant. It seems pretty important for Catalina that the app must run from the "Applications" folder otherwise it does not allow us modifying files in the app folder. Other than that, I observe no issues on Catalina - update works smoothly, everything works properly after the reboot.
