### ISSUE TITLE
Allow SafeSearch to be enforced on an app basis

### ISSUE THREAD

**Issue by DebrodeD** [AdguardTeam/AdGuardHome#1349]
I appreciate google search having safe search enabled, but I find YouTube's SafeSearch overbearing and often come across videos that are blocked. I'd like to be able to disable SafeSearch for YouTube while keeping it enabled for everything else.

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdGuardHome/issues/1163
