### ISSUE TITLE
Query log contatins not mine ip

### ISSUE THREAD

**Issue by maxtar** [AdguardTeam/AdGuardHome#1350]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.100.8
* **How did you setup DNS configuration:**
  * Raspberry Pi
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B)
* **Operating system and version:**
  * Raspbian

### Expected Behavior

In query log I can see only my local client which use AdGuardHome.

### Actual Behavior

In query log I can see **213.180.193.56** ip in client column. According whois service this ip belong to Google.

### Screenshots

<details><summary>Screenshot:</summary>

![изображение](https://user-images.githubusercontent.com/10290098/72345153-0acef480-36e4-11ea-8154-133287c7fef0.png)

</details>

### Additional Information

I don't understand why log contains this ip. Is Google use my AdGuardHome? :)

**Comment by szolin** [comment]
dup: #1329
fixed in v0.100.9
