### ISSUE TITLE
upgrade think for DNS,maybe not very well

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1351]
Openwrt x64 ,adguarthome 0.100.8
add over 1000 resouces lists
添加了1000多规则源地址，但是无法全部开启，因为有打开太多文件的问题没有修复，同时需要支持广告过滤规则，而不是只支持过滤域名
以下是我觉得升级可能会用到的，有帮助的
1.DNS library in Go 
https://github.com/miekg/dns
DNS库更新，保持最新，减少被远程捕捉和嗅探的可能
2.High performance DNS over HTTPS client & server
https://github.com/m13253/dns-over-https
3.a lightweight, high-performance, powerful intranet penetration proxy server, with a powerful web management terminal.
https://github.com/ehang-io/nps
需要升级成高性能多并发的大数据服务器，因为添加的过滤规则就是一个大数据库
4.Quickly Search Large DNS Datasets 
https://github.com/erbbysam/DNSGrep
5.DNS from different country used different server
https://github.com/ARwMq9b6/dnsproxy
以上两个是配合的，中国等有过滤的国家，访问当地网址优先用当地服务器，访问国外网址用国外服务器
6.CoreDNS is a DNS server that chains plugins 
https://coredns.io
https://github.com/coredns/coredns
增加插件
7.P2P DNS with content key, crypto key and PKI support. DynDNS alternative. 
https://github.com/mwarning/KadNode
8.A Rust based DNS client, server, and resolver 
https://github.com/bluejekyll/trust-dns
9.godoh - A DNS-over-HTTPS C2
https://github.com/sensepost/goDoH
10.DNS-over-QUIC to UDP Proxy
https://github.com/ns1/doq-proxy
用不同的方式和协议来提高拓展性能
11.dns tunnel backdoor
https://github.com/ice-ice/dnstunnel
12.Reverse proxy and service tunnel written in Go
https://github.com/inlets/inlets
13.Solve your DNS hosts from your docker containers, then from your local configuration, then from internet
https://github.com/mageddo/dns-proxy-server
14.super proxy
https://github.com/snail007/goproxy
不同的代理方式，提高在复杂网络中的性能和安全应对，anti-hijacking

**Comment by ameshkov** [comment]
What exactly do you suggest?

你可以用中文写
