### ISSUE TITLE
FULL URL appears on top dashboard 

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1354]
And looks many times query already.
https://ynuf.aliapp.org/savewb.json

![image](https://user-images.githubusercontent.com/22477230/72528887-11599980-38a7-11ea-941b-ee38eddafc49.png)

**Comment by ameshkov** [comment]
could you please check the query log, what's there with this url?

**Comment by Mosney** [comment]
![image](https://user-images.githubusercontent.com/22477230/72529323-081cfc80-38a8-11ea-834e-12e8c72120f5.png)
`https://ynuf.aliapp.org/savewb.json?
`
looks odd, please ignore the strange DNS result cause I use [clash](https://github.com/Dreamacro/clash) fakeIP for sth.

**Comment by ameshkov** [comment]
Yeah, it seems as this is actually what's sent in the DNS question. I have no idea why would any DNS client send this in a DNS query though.

**Comment by Mosney** [comment]
So it may be the client bug, nor AGH. That would make sense.
