### ISSUE TITLE
Maintaing continuity between installations

### ISSUE THREAD

**Issue by txcanyon** [AdguardTeam/AdGuardHome#1355]
- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Problem Description
Is there a way to transfer settings for multiple installations so that they all have the same ? I 2 separate dns servers and would like both to have the same allow/blocks.

### Proposed Solution
Some sort of export function or let us know what database files we can copy to a 2nd installation

### Alternatives Considered
I've just copied installations but I cant see what i have allowed/blocked.

**Comment by szolin** [comment]
You can just copy-paste the necessary information from one AdGuardHome.yaml to another.

**Comment by ameshkov** [comment]
Note that you'll have to restart AG Home before copy/pasting the new configuration file.

Once [configuration reload is implemented](https://github.com/AdguardTeam/AdGuardHome/issues/1302), it will be easier.
