### ISSUE TITLE
中文区最好用的AdGuardHome广告过滤列表，欢迎交流 / Chinese ad filtering list for AdGuard Home

### ISSUE THREAD

**Issue by gentlyxu** [AdguardTeam/AdGuardHome#1357]
毛遂自荐.我维护的项目 anti-AD: https://github.com/privacy-protection-tools/anti-AD

1. 针对中文区的广告过滤；
2. 针对AdGuardHome特别优化，按照[官方Wiki推荐的格式](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#adblock-style)；
3. 支持正则表达式、通配符匹配，高效且具有预见性；

for all China users, thank you!

**Comment by ArchiveBase** [comment]
#1325

**Comment by jkle112** [comment]
感谢推荐，我已经添加了，但是我想知否可以在增加privacy，anti-hijacking,anti-phishing方面的规则。

**Comment by gentlyxu** [comment]
@jkle112  屏蔽privacy收集和大数据收集目前anti-AD是已经支持的。恶意网站、钓鱼的、放木马的当前是有在逐步完善的，都会集成进来的，这会是anti-AD项目今后工作的一个重点部分

**Comment by ameshkov** [comment]
谢谢！我喜欢你的广告过滤列表，我们会考虑加它到AdGuardHome。

**Comment by gentlyxu** [comment]
@ameshkov  Thank you very much for your trust.  😊

**Comment by lancelot-moon** [comment]
@gentlyxu 
Hi,
May you provide hosts file format?
Thanks.

**Comment by ameshkov** [comment]
@lancelot-moon why would you need that?

Adblock-style syntax cannot be easily converted to hosts format, that's why we don't provide AdGuard SDN as a hosts list.

**Comment by lancelot-moon** [comment]
@ameshkov 
I want to subscribe it in my router with Tomato firmware.
That's why I need hosts file format.
Trifle, don't mind.)

**Comment by gentlyxu** [comment]
@lancelot-moon ,Oops! That's too long if you use the hosts list. We have provided the dnsmasq blocking list,you can try it. That's much better than the hosts list

**Comment by lancelot-moon** [comment]
@gentlyxu 
I found that the blacklist of Tomato firmware supports not only hosts file but also domains.
Not every app supports basic rule syntax, ex: DNSCloak.
I suggest you to provide domain format.
Anyway, it's up to you.
B/R

**Comment by lancelot-moon** [comment]
@gentlyxu 
Your list causes imgur's photos broken which are inserted on GitHub when enabling DNS filtering in AG for Android.
I tested on Android.
ex: Open the inserted screenshot on GitHub.
https://github.com/AdguardTeam/AdguardForAndroid/issues/3389

**Comment by syaofox** [comment]
jav321为什么也拦了。。。

**Comment by ameshkov** [comment]
@gentlyxu in v0.103 there will be an option to choose from a list of blocklists in AdGuard Home, added your list: https://github.com/AdguardTeam/AdGuardHome/commit/304a51f17e2a6adf720b8c0eb62da041498415e9
