### ISSUE TITLE
Query Log improvements

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1360]
Hello,

please, add more options in the query log menu:
- show only NOT filtered;
- show only filtered by SafeBrowsing (browsing security web service/antiphishing module);
- show only filtered by CNAME or IP in response;
- show only filtered by Parental Control web service.

Thank you.

**Comment by szolin** [comment]
Almost all query log feature requests are listed here: https://github.com/AdguardTeam/AdGuardHome/issues/481
It's low priority, though.
