### ISSUE TITLE
Add DNSCrypt server-side support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1361]
See the original feature request in the dnsproxy repo:
https://github.com/AdguardTeam/dnsproxy/issues/44

It is already highly upvoted so I think it makes sense to assign it to a milestone already.

**Comment by ameshkov** [comment]
This would be quite problematic to add and I don't see that much desire for this to happen.

There's always DOH/DOT for those who would like encryption.

**Comment by ameshkov** [comment]
Okay, not that problematic after all since DNSCrypt support has been added to dnsproxy: https://github.com/AdguardTeam/dnsproxy/commit/39abe8047a59281128fa40ef879061ce25792d66

**Comment by ainar-g** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/DNSCrypt
