### ISSUE TITLE
Log show which Upstream DNS servers response 

### ISSUE THREAD

**Issue by bzzjh** [AdguardTeam/AdGuardHome#1363]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Additional Information

I have set 4 upstream DNS servers,and now I want to know which upstream DNS servers response  domain request,how to do? thanks ,sorry for my bad english.

**Comment by ArchiveBase** [comment]
Duplicate of #468

> I want to know which upstream DNS servers response domain request

Check on querylog.json

**Comment by ameshkov** [comment]
Closed as dup of https://github.com/AdguardTeam/AdGuardHome/issues/468

Please upvote #468 if you want it
