### ISSUE TITLE
Custom filter rule for IPv6 does not work anymore

### ISSUE THREAD

**Issue by magenbrot** [AdguardTeam/AdGuardHome#1365]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.9
* **How did you setup DNS configuration:**
  * LXC container
* **Operating system and version:**
  * Alpine Linux 3.10.3

### Expected Behavior
I have the following custom filter rules configured. Since the upgrade on v0.100.9 the IPv6 address is not resolved by AdGuard anymore:
```
127.0.0.1 testing.resolver.local
::1 testing.resolver.local
```

### Actual Behavior
The A record is resolved correctly to 127.0.0.1. A query on the AAAA type does not return an answer.

### Screenshots
![Screenshot from 2020-01-23 11-01-53](https://user-images.githubusercontent.com/4865153/72975178-a50ff600-3dd0-11ea-995e-10817c23ec7c.png)
<details><summary>09:42 shows AdGuard answering correctly. Then I've made the update and you can see that it is returning a NOERROR for the AAAA record now.</summary>
</details>

**Comment by ameshkov** [comment]
Got it, I know where it came from.

@szolin I guess we should add a unit test for this particular case.

**Comment by szolin** [comment]
8d2a9ce923eae4673a74f4c4a7e1d9ef840f04d2
#1328
Isn't it what we wanted to achieve?

**Comment by ameshkov** [comment]
No, we want to achieve the same behavior as Linux hosts files, and this is clearly not it.
