### ISSUE TITLE
Is it possible to replace advertise with my own image?

### ISSUE THREAD

**Issue by ada672** [AdguardTeam/AdGuardHome#1371]
as title.

**Comment by Vorlif** [comment]
You can enter your own IP address to which all requests will be sent. 

I think, under this IP address you should be able to run a webser that checks if the http request wants an image and then returns your own image. But this only works if an image is loaded directly and not if a javascript file is loaded first, which then inserts an image at runtime. The javascript file will probably be blocked before loading and therefore the image will not be loaded.

Furthermore, requests for all protocols are sent to this IP and should be blocked there. The loading of a page is then probably a bit slower than blocking it directly.

But in principle it should be possible.

**Comment by ameshkov** [comment]
Additionally, you'll need to use something like pixelsrv-tls, check the links here:
https://github.com/AdguardTeam/AdGuardHome/issues/1121

**Comment by ada672** [comment]
Thanks for point out the way. ^_^
