### ISSUE TITLE
[Feature request] Enhance audit function

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1376]
It may be more user-friendly to check query log avoid confused from the filtered item. OK, this duplicate https://github.com/AdguardTeam/AdGuardHome/issues/1248 and https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911

Actually, Log page could be more efficient, such as make a mini-dashboard for specific device or domain, I mean, count the number of domain queries from a specific device, or device queries from a specific domain.
I really love the 'Long Term Statistics' and 'Audit Log' function in Pi-hole, it is very useful to analyse data and device control. Very hopefully AGH could enhance performance in those areas.
![](https://piholenet.b-cdn.net/wp-content/uploads/2018/12/long-term-stats.png)
![](https://piholenet.b-cdn.net/wp-content/uploads/2018/12/audit-log.png)

**Comment by ArchiveBase** [comment]
Duplicate of #1164 #481

> count the number of domain queries from a specific device

Already available

**Comment by Mosney** [comment]
Okay, looks I'm not the only one want to audit function! Hope it will come true ASAP

**Comment by Mosney** [comment]
> > 计算来自特定设备的域查询数
> 
> 已经有
And where is this function, looks I cannot find it.

**Comment by ArchiveBase** [comment]
儀表板 > 熱門用戶端

**Comment by ArchiveBase** [comment]
Rest of further enhancement that you haven't mentioned https://github.com/AdguardTeam/AdGuardHome/issues/1336

**Comment by Mosney** [comment]
> Duplicate of #1164 #481
> 
> > count the number of domain queries from a specific device
> 
> Already available

I mean top domains list in one device, not the total query count at all device, for audit purpose. As you mentioned, it already been proposed in https://github.com/AdguardTeam/AdGuardHome/issues/1336

**Comment by ArchiveBase** [comment]
> it already been proposed in #1336

I think it still about request count

> I mean top domains list in one device, not the total query count at all device

As per my understand, it mentioned in https://github.com/AdguardTeam/AdGuardHome/issues/1164 and according to feature explanation; it's possible to implement it within query log with https://github.com/AdguardTeam/AdGuardHome/issues/481 and not necessary to add separate page(component) for long term statistics or audit log  then that's  the difference between pi-hole for now but it may change due development team desire.

**Comment by HyperCriSiS** [comment]
I wanted to switch to AdGuard and was really wondering not to find this feature. 
This is a true blocker to move away from Pi-Hole.
