### ISSUE TITLE
Hass.io service calls to AdGuard Home (dockerized) to block/unblock services

### ISSUE THREAD

**Issue by dexterdar** [AdguardTeam/AdGuardHome#1377]
### Feature Request

Similar to the current available service calls in HASS.IO to AdGuard where adguard.enable_url and adguard.disable_url can be called to turn on/off a filter list (under filters), I would like to propose new service calls in HASSIO to block/unblock the services listed under the General Settings (as seen on screenshot attached).  

![Blocked Services](https://user-images.githubusercontent.com/42367754/73259771-5d082d80-422d-11ea-9322-6744a9f726dc.png)

This would allow us parents to automate as well as manually tick switches in our HASS dashboards/lovelace to disable access to such services easily.

### Alternatives Considered

At the moment, I have custom filter lists for YouTube and Netflix where I can use the adguard.enable_url to turn the filters on, which works but requires me to manually lookup the target domain names (and subsequent domains used) and manage the lists.  Why reinvent the wheel if the services are already defined in AdGuard... just needs a way to call block/unblock from HASS.IO :)

**Comment by ameshkov** [comment]
I guess this is better to ask @frenck about this?

Configuring services is available through the API:
https://github.com/AdguardTeam/AdGuardHome/blob/master/openapi/openapi.yaml#L811

**Comment by frenck** [comment]
@ameshkov Feel free to close this. This is a Home Assistant feature request for the integration (not hass.io or add-on related even).

@dexterdar Home Assistant feature requests can be done in the Home Assistant Community forum.
