### ISSUE TITLE
Issue with using AdguardBrowsing services

### ISSUE THREAD

**Issue by FlorisHigh3IT** [AdguardTeam/AdGuardHome#1380]
I use Adguard on my Synology NAS in a docker container. I use macvlan to give the container own addresses because Synology blocks port 53.
Works like a charm for adblocking!

But when I enable AdguardBrowsing or AdguardParantal control I see a lot of erros in my log:

_2020/01/29 09:05:27 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://dns-family.adguard.com:443/dns-query, cause: failed to lookup dns-family.adguard.com, cause: synthetic.wrap: all resolvers failed to lookup, cause: read udp 192.168.0.200:49278->176.103.130.130:53: i/o timeout (hidden: read udp 192.168.0.200:60481->176.103.130.131:53: i/o timeout)_

I thinkt it is using the wrong NIC. The container has two adresses:
192.168.0.200 is listening for DNS requests
192.168.100.2 is the bridge to the NAS/Internet

How can I change Adguard to use the other NIC?

Maybe this is not an Adguard issue or problem but I can't find an other forum to ask this question

**Comment by szolin** [comment]
AGH is trying to resolve an address for dns-family.adguard.com to get SB info from it.
176.103.130.130 is the address of "bootstrap" server - if AGH can't reach it - then it can't resolve dns-family.adguard.com - then SB service won't work.
You should check your network settings.  Try to use nslookup or dig with 176.103.130.130 server address - do they work on the same machine AGH is running on?

**Comment by FlorisHigh3IT** [comment]
It is on the same machine, but I think you are right that something is wrong with my network settings:

nslookup 176.103.130.130                                                                                                            
nslookup: can't resolve '(null)': Name does not resolve                                                                                                     
                                                                                                                                                            
Name:      176.103.130.130                                                                                                                                  
Address 1: 176.103.130.130 176-103-130-130.dns.adguard.com

**Comment by szolin** [comment]
> nslookup 176.103.130.130

this command is invalid - you should write something like `nslookup example.org 176.103.130.130`
