### ISSUE TITLE
Host Rules: support multiple IP addresses for one host

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1381]
```
1.1.1.1 host
2.2.2.2 host
```

2 IP addresses match `host` - we should support this:
* Respond with 2 A records
* Add 2 rules and 2 filter IDs to query logs
* UI should display multiple rules on query logs page

**Comment by ainar-g** [comment]
This is probably already done in the `urlfilter` module.  I should check it and, if it's not implemented. implement it.

**Comment by ameshkov** [comment]
@ainar-g according to this, should be really easy to do that: https://github.com/AdguardTeam/urlfilter/commit/59ecbb23dd71139c387a982b082e5d0d1ce2e708
