### ISSUE TITLE
[Documentation] Clarification on blocklist format support.

### ISSUE THREAD

**Issue by adworacz** [AdguardTeam/AdGuardHome#1385]
### Problem Description

For users coming from Pihole, it's not clear if Adguard Home supports the "domains only" blocklist format that Pihole often uses (ex: https://dbl.oisd.nl/)

Based on the documentation [on the wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists), it appears that it **doesn't**.

Personally, I think that's fine, but if that's the case, there seems to be the misunderstanding on the internet that it does. For example, the maintainer of https://oisd.nl lists Adguard Home as being supported on the domain-only block list.

Based on my experience, I had to add the "/etc/hosts" formatted version of the file before I started seeing requests blocked (might have just been chance though).

### Proposed Solution

Clarify, on the wiki if possible, that the Pihole format of "domains only" (no "0.0.0.0" prefix, etc) is **NOT** compatible. Or if it is, make it clear by listing it as a third format option (right now it just lists the "/etc/hosts" and Adblock formats).

### Alternatives Considered

Add support for domains-only lists. 

I'm personally okay without this, as I do prefer the better Adblock syntax (more control of subdomain matching, etc)

**Comment by ameshkov** [comment]
Thanks for the suggestion!

We do support the domains-only format. Internally, it's converted to `0.0.0.0 example.org`.

**Comment by adworacz** [comment]
Gotcha, thank you for clarifying here.

By converting it to the 0.0.0.0 format internally, this means that wildcard matching is disabled for a domains-only list. This is good to know. 

I don't know what Pihole's behaviour is (if it matches `test.example.com` when `example.com` is specified in the domain-only blocklist), but this is an important distinction.

**Comment by ameshkov** [comment]
> that wildcard matching is disabled for a domains-only list

Actually, it will work just okay.

If the string is not a valid domain (smth like `*.example.org`), AdGuard Home considers that this is an [adblock-style](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#adblock-style) rule so all additional perks of them including wildcard matching will be allowed.

**Comment by adworacz** [comment]
Ahhh that's an important point! Please make sure that is emphasized on the documentation.

(If I get some free time, I might just go ahead and put together a pull request for updating the wiki myself).

**Comment by adworacz** [comment]
Welp, just pulled the wiki down using the link on the right hand side, but after making updates, it turns out that I can't push a branch to the AdguardTeam/AdguardHome.wiki.git repo (got a 403 error).

Having not updated the wiki like this before (this seemed to be the only possible way, since there was no public "edit" button), I believe this means that the wiki is locked down to the Adguard team for right now.

**Comment by ameshkov** [comment]
@adworacz Github does not allow pull requests to the Wiki repo. I guess you could simply add `git diff` here as a comment

**Comment by adworacz** [comment]
Sure thing:

```
diff --git a/Hosts-Blocklists.md b/Hosts-Blocklists.md
index 8ca47e2..c0a0617 100644
--- a/Hosts-Blocklists.md
+++ b/Hosts-Blocklists.md
@@ -1,8 +1,9 @@
 # AdGuard Home - How to write hosts blocklists
 
-There are two different approaches to writing hosts blocklists:
+There are three different approaches to writing hosts blocklists:
 
 - [/etc/hosts syntax](#etc-hosts) - the old, tried and true approach is to use the same syntax as Operation Systems use for the "hosts" files.
+- [domains-only syntax](#domains-only) - Often known as the "Pi-hole" syntax, blocklists imported using this format are internally transformed into the [/etc/hosts syntax](#etc-hosts).
 - [Adblock-style syntax](#adblock-style) - modern approach to writing filtering rules based on using a subset of the Adblock-style syntax. This way blocklists will be compatible with browser ad blockers.
 
 If you are creating a blocklist for AdGuard Home, we recommend using the [Adblock-style syntax](#adblock-style). It has a couple of important advantages over the old-style syntax:
@@ -49,6 +50,19 @@ Examples:
 
 > Please note, that the `IP_address` value is ignored by most of the DNS filtering software.
 
+
+## <a id="domains-only"></a> Domains-only syntax
+This format lists each domain on an individual line, like so:
+
+```
+example.com
+example.org
+```
+
+When AdGuard loads this type of blocklist, it will internally convert each entry to match the [/etc/hosts syntax](#etc-hosts) documented above.
+
+Note: If the string is not a valid domain (something like `*.example.org`), AdGuard Home considers that this is an [adblock-style](#adblock-style) rule so all additional perks of them including wildcard matching will be allowed.
+
 ## <a id="adblock-style"></a> Adblock-style syntax
 
 This is a subset of the [traditional Adblock-style](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) syntax which is used by browser ad blockers.

```

**Comment by sjhgvr** [comment]
> Based on my experience, I had to add the "/etc/hosts" formatted version of the file before I started seeing requests blocked (might have just been chance though).

By that do you mean you are using https://hosts.oisd.nl which is working for you in Adguard Home?

**Comment by adworacz** [comment]
> > Based on my experience, I had to add the "/etc/hosts" formatted version of the file before I started seeing requests blocked (might have just been chance though).
> 
> By that do you mean you are using https://hosts.oisd.nl and that is working for you in Adguard Home?

Yes, that (hosts.oisd.nl) is working just fine in Adguard Home. Memory blows up a bit, but that makes some sense considering the size of the list.

I used the "hosts" version because I wasn't sure that the domains-only version was working with Adguard Home prior to the discussion on this Issue. 

I haven't changed over to the domains-only version yet, and I'm not sure I will considering that it's going to be represented as a "hosts" formatted file internally anyways.

**Comment by ameshkov** [comment]
Hm, I wouldn't say that domains syntax is known as "pi-hole syntax", it's older than me.

Other than that it looks good, I'll try to merge it tomorrow.
