### ISSUE TITLE
OpenWrt: Service Can't Be Enabled

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#1386]
### Issue Details

* **Version of AdGuard Home server:**
  * Beta Released 2020-01-31 (most recent beta at the moment)
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Linksys WRT3200ACM (ARMv7)
* **Operating system and version:**
  * OpenWrt 19.07.0

### Expected Behavior

AGH Service should have functionality to Enable/Disable and service should start at boot time.
### Actual Behavior

AGH Service does not have Enable/Disable functionality and therefore cannot start at boot time on OpenWrt.

AGH service can successfully be installed, started, stopped, restarted. But no enable or disable.

### Additional Information

There is a recent commit related to AGH Service on OpenWrt specifically that first surfaced in this beta build. Link: https://github.com/AdguardTeam/AdGuardHome/commit/e398117d2546efba2aba20e358c68b9ef85f25e6

Typically on OpenWrt, after installing a service, you must enable the service before it will start at boot time:

`/etc/init.d/AdGuardHome enable` or `./AdGuardHome - s enable`

See example here: https://github.com/rufengsuixing/luci-app-adguardhome/blob/d31705101829e6a9a9522ecd1cfa4f49f0795d6c/Makefile#L52

So I can manually start AGH service after OpenWrt boots with:

`/etc/init.d/AdGuardHome start` or `./AdGuardHome - s start`

But I cannot have AGH service start automatically when OpenWrt boots without enable/disable functionality.

**Comment by ameshkov** [comment]
Tbh, I don't think we should add new commands. It's just `install` command should also enable the service right away.

**Comment by WildByDesign** [comment]
@ameshkov  Could it have something to do with permissions of the binary file? I mean, it does execute and run flawlessly. It just does not seem to run at boot time for me on OpenWrt and service shows as Disabled. Any attempt to Enable shows that the command does not exist.

My Linux and OpenWrt command skills and understanding is limited, so maybe someone from OpenWrt community will understand this better than I can at the moment.

**Comment by ameshkov** [comment]
> Any attempt to Enable shows that the command does not exist.

Well, that's because it does not exist yet indeed:)

It seems that we might need to change the init script so that it was using `rc.common` like it's done here:
https://github.com/rufengsuixing/luci-app-adguardhome/blob/d31705101829e6a9a9522ecd1cfa4f49f0795d6c/root/etc/init.d/AdGuardHome

@rufengsuixing could you please consult us? What is the better way to make our `-s install/uninstall` commands work properly?

Should we simply change our init script to something like this?
```
#!/bin/sh /etc/rc.common
 
USE_PROCD=1
START=95
STOP=01
CONFIGURATION=AdGuardHome
```

**Comment by rufengsuixing** [comment]
https://github.com/happyzhang1995/luci-app-adguardhome/blob/master/root/etc/init.d/AdGuardHome
change the BINLOADER_BIN path of it
copy this simple one to /etc/init.d/AdGuardHome and chmod it  with a+x
enable boot start with /etc/init.d/AdGuardHome enabled or make a link of it to /etc/rc.d/S95AdGuardHome , /etc/rc.d/K01AdGuardHome

**Comment by rufengsuixing** [comment]
if you want to make adh work as the default dns service instead of dnsmasq
you must change the port of dnsmasq not to 53 and set adh port to 53
```
backupport=5553
configpath="/etc/Adhconfig.yaml"
set_adh_as_default()
{
	config_editor "dns.port" "53" "$configpath"
	uci set dhcp.@dnsmasq[0].port="$backupport"
	uci commit dhcp
	/etc/init.d/dnsmasq reload
}
set_dnsmasq_as_default()
{
	config_editor "dns.port" "$backupport" "$configpath"
	uci set dhcp.@dnsmasq[0].port="53"
	uci commit dhcp
	/etc/init.d/dnsmasq reload
}
config_editor()
{
	awk -v yaml="$1" -v value="$2" -v file="$3" -v ro="$4" '
	BEGIN{split(yaml,part,"\.");s="";i=1;l=length(part);}
    {
        if (match($0,s""part[i]":"))
        {
            if (i==l)
            {
                split($0,t,": ");
				if (ro==""){
				system("sed -i '\''"FNR"c \\"t[1]": "value"'\'' "file);
				}else{
				print(t[2]);
				}
				exit;
            }
            s=s"[- ]{2}";
            i++;
        }
    }' $3
}
```

**Comment by WildByDesign** [comment]
@ameshkov I made a mistake regarding enabling/disabling of the service. You do _not_ have to create an additional command to enable/disable AGH service. I made an incorrect assumption on that. You have created the correct symlinks in `rc.d` which achieves the boot start. I apologize for my incorrect 

However, the AGH service is failing to Enable correctly. I tried several other (quite basic) `init.d` scripts specifically for AGH service made by community enthusiasts and other developers, and those services did enable correctly for boot time start.

This leads me to believe that there is something within your `init.d` script that is causing it to fail for boot time enabling.

See OpenWrt specific details on `init.d` scripts here: https://openwrt.org/docs/techref/initscripts

There is one thing that I noticed in your `init.d` script on my OpenWrt system that was created by that latest beta version of AGH from 2020/01/31 (most recent beta) that seems may be incorrect for OpenWrt systems:

`[ -e /etc/sysconfig/$name ] && . /etc/sysconfig/$name`

On OpenWrt systems, all system configuration files are located in:

`/etc/config/` (correct)

`/etc/sysconfig/` (this does not exist on OpenWrt systems.

Therefore, that could be part of the problem causing failure to enable the service specifically for boot time.

**Comment by ameshkov** [comment]
@WildByDesign
This fix will most likely resolve all the issues you have. It is available in the new beta version.

@rufengsuixing thank you for helping us!

We've implemented a simple procd init script that works more or less okay: https://github.com/AdguardTeam/AdGuardHome/commit/fc88f59f6160c7d3520f22081cf569025b5fd5c8#diff-e06079fe3b21218b7ea531caffc32b39R411

It does not provide any complex functionality, it just starts/stops AdGuard Home.
