### ISSUE TITLE
SafeSearch Regression (recent beta from 2020-01-31)

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#1387]
### Issue Details

* **Version of AdGuard Home server:**
  * Beta Released 2020-01-31 (most recent beta at the moment)
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Linksys WRT3200ACM (ARMv7)
* **Operating system and version:**
  * OpenWrt 19.07.0

### Expected Behavior

SafeSearch functionality should be able to be enforced per client.

### Actual Behavior

SafeSearch functionality stopped working on this most recent beta build from 2020-01-31. SafeSearch is failing per client in my testing. I have not tested system wide SafeSearch.

On client devices that have SafeSearch enforced, all Google searches and YouTube lookups result in NXDOMAIN. My blocking mode is set as NXDOMAIN.

This same setup and same configuration (with SafeSearch per client) was working successfully on the most recent stable build (v0.100.9) but stopped working on most recent beta build (2020-01-31). Therefore some commit between these two builds may have caused a SafeSearch regression.

### Additional Information

Client devices with SafeSearch enforced are returning NXDOMAIN on all Google searches and any kind of YouTube access attempt also returns NXDOMAIN. Interestingly, in only this beta build, these SafeSearch NXDOMAIN issues are showing up in the **Top blocked domains** section of the Dashboard. Those blockages showed as google.com, google.ca, and m.youtube.com. 

On portable devices such as iPads, m.youtube.com is typical and expected being the mobile version of the site. Also interestingly, those blockages show the "eye" symbol stating that those domains are listed in the Whotracksme blocklist. However, looking through the enabled blocklists, those domains are not on the blocklists at all.  So these domains are being blocked incorrectly with enforced SafeSearch and only on this recent beta build.

I have reverted back to v0.100.9 now with the exact same configuration file, and the SafeSearch issue is gone. My hope is that I have got this bug report completed in time before this issue makes it into the next stable release as https://github.com/AdguardTeam/AdGuardHome/milestone/17 is near completion.

**Comment by WildByDesign** [comment]
@ameshkov This exact issue has come up again today on the **v0.103.0-beta1** release. Previously, I was using v0.102.0 stable release and beta release from **2020-06-29** without any issues regarding Safe Search. This regression seems to be somewhere between beta from **2020-06-29** and today's **v0.103.0-beta1**.

Can you please reopen this issue and have a look?

Basically, NXDOMAIN on Google, YouTube, etc.

**Comment by ameshkov** [comment]
@WildByDesign could you please open a new issue?

It'd also help if you could collect verbose-level log as well because I cannot reproduce this.

**Comment by WildByDesign** [comment]
@ameshkov Coincidentally, after enabling verbose-level logging and restarting the AdGuardHome service, I can no longer reproduce the issue at this time. I will try again tomorrow and I will create a new issue if I am able to reproduce.

Question: If I restart the AdGuardHome service, does that also clear it's built-in DNS cache?

**Comment by szolin** [comment]
> If I restart the AdGuardHome service, does that also clear it's built-in DNS cache?

Yes, of course it does.  Restarting the service means opening a new process.
