### ISSUE TITLE
Feature Request: Maintain query log filter option on refresh

### ISSUE THREAD

**Issue by mmotti** [AdguardTeam/AdGuardHome#1388]
It would save a lot of time with identifying troublesome blocking if the filtering options for Domain, Type, Filtered and Client would be persistent when clicking the refresh button.

I understand that this may not (or may?) be possible when bashing F5, but I imagine with some tweaking it could be made to work with the refresh button next to Query Log?

Cheers!

**Comment by ArchiveBase** [comment]
Duplicate of #845
