### ISSUE TITLE
AdGuard Home DNS server is listening on the following addresses

### ISSUE THREAD

**Issue by wsltshh** [AdguardTeam/AdGuardHome#1392]
Add fe80:: Scope: Link

**Comment by ameshkov** [comment]
Do you mean it should listen to that address? If you're using `0.0.0.0` as a "listen address", this is possible.

**Comment by wsltshh** [comment]
> Do you mean it should listen to that address? If you're using `0.0.0.0` as a "listen address", this is possible.

Sorry, I do n’t speak English, I can only use Google Translate, I do n’t know if the translation is correct
I mean to increase the display of Scope: Link
Easy to view and manually set IPv6 DNS
Because Scope: Link does not change
![QQ截图20200207001633](https://user-images.githubusercontent.com/20556540/73956449-f0351780-493f-11ea-8f5d-b18784eee20d.png)
