### ISSUE TITLE
Set name for clients

### ISSUE THREAD

**Issue by BoBBer446** [AdguardTeam/AdGuardHome#1396]
it would be great if i can set names to my network clients and can set for each client seperate rules

**Comment by ArchiveBase** [comment]
> it would be great if i can set names to my network clients

Already possible to set through client settings. If it not fit for your needs then can you explain more about it

> an set for each client seperate rules

Duplicate of #435 or #1081 (implemented)

**Comment by ameshkov** [comment]
#1081 is in the beta version only, but yeah.
