### ISSUE TITLE
Reduce the ARP scanning period

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#1398]
The current period to update clients is 1 hour.  Can't we make is substantially less?

Or even better, make it configurable in the UI, or the YAML file if need be.

**Comment by ameshkov** [comment]
Mm, what period exactly do you mean? The application update check period?

**Comment by adrianh-za** [comment]
The client name updates runs a process to update client names (host file and arp) every hour.  This interval is hardcoded in clients.go file.

As all of my connected devices explicitly use AGD as DNS server, sometimes the client list and query log only shows the IP address until such time the update has run.

Was thinking that the interval could be reduced.  Or even better, allow the update interval to be configured by the end user.

https://github.com/AdguardTeam/AdGuardHome/blob/master/home/clients.go

line 23
`const (
	clientsUpdatePeriod = 1 * time.Hour
)`

line 188
`func (clients *clientsContainer) periodicUpdate() {
	for {
		clients.addFromHostsFile()
		clients.addFromSystemARP()
		time.Sleep(clientsUpdatePeriod)
	}
}`

**Comment by ameshkov** [comment]
Well, in theory, the first time we encounter an IP address, we should try resolving its hostname. If that does not happen for some of your clients, this is most likely a bug.

Just in case, do you use AGH as a DHCP server?

**Comment by adrianh-za** [comment]
I don't use AGH as DHCP server.

Yeah, definitely not happening immediately for some of my clients. Check an hour later, and they are updated.

**Comment by ameshkov** [comment]
Ah, wait, that's my bad. RDNS resolution happens in this manner, ARP is indeed once an hour
