### ISSUE TITLE
Question: How can one test if DoT or DoH is working?

### ISSUE THREAD

**Issue by BobWs** [AdguardTeam/AdGuardHome#1399]
Hi,
I'm testing Adguard Home at the moment vs pi-hole. One benefit over pi-hole is the easy way the setup DoT or DoH, but how can I test if it is really working and that my DNS is encrypted?

I have setup this in upstream DNS:
tls://dns.quad9.net
sdns://AQMAAAAAAAAADDkuOS45Ljk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0

And all my clients in my LAN network are using my Adguard docker container IP. When surfing ads are blocked so that is working, but I cannot find I way to test the DoT or DoH or DNSCrypt

Anybody a solution or suggestion?

Thanks!

![Screen_Shot](https://user-images.githubusercontent.com/5485820/74101166-330d1000-4b37-11ea-800b-8a7abd9b6457.png)

**Comment by ArchiveBase** [comment]
> how can I test if it is really working and that my DNS is encrypted?

a tutorial https://askubuntu.com/questions/105366/how-to-check-if-dns-is-encrypted/106609#106609

> but I cannot find I way to test the DoT or DoH or DNSCrypt

Check on querylog.json file or https://github.com/AdguardTeam/AdGuardHome/issues/468

**Comment by ameshkov** [comment]
We'll make it easier to check what upstream was used when the query log is finally redesigned.
