### ISSUE TITLE
DNS bind multiple host

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1401]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I want to bind the DNS host to `127.0.0.1` and `::1`.
But the configuration only can set one address.

Work:

```
dns:
  bind_host: 127.0.0.1
```

Not work

```
dns:
  bind_host:
  - 127.0.0.1
  - ::1
```

**Comment by mbaran5** [comment]
Commenting to see if this is something that is possible? I am looking to install this on a system that already runs a DNS server (for local network lookups/overrides) so I need to be able to specify another IP (both IPv4 and IPv6) to use for the AdGuardHome configuration.

**Comment by panache67** [comment]
Being able to set multiple addresses as dns bind_host would be really beneficial, especially given that Ubuntu by default binds to 127.0.0.1:53 and thus Adguard cannot build to 0.0.0.0:53. Even if you only want to bind to one interface, e.g. eth0, it is absolutely needed to bind to multiple addresses to provide both ipv4 and ipv6 coverage.

**Comment by stolenvw** [comment]
this would be really nice to have, i want to bind it to one ipv4 and one ipv6 ip, and not use 0.0.0.0:53 witch makes it bind to all ips on the computer (docker ips, bridged ips, ips on other interfaces)

**Comment by Technikte** [comment]
This is need to get the full usage with ipv4 + ipv6.

**Comment by Vartkat** [comment]
I'm surely missing something... Running Adguard on Docker, Ubuntu 20.04 which has two NICs, one wired one wlan. Adguard  binds to wlan, which is not what I want as the DNS set on DHCP server is the wired nic interface... And of course this behaviour is messing all my lan.

**Comment by wpehrc** [comment]
This would be very useful since I'm currently forced to allow AGH to bind to everything just so that IPv4 and IPv6 DNS will both work, not to mention this does not work in a container (as far as I can tell).

**Comment by ameshkov** [comment]
Worry not, it's planned on the closest release.

**Comment by ainar-g** [comment]
As of snapshot 5d0d32b on the `edge` channel, this should be implemented, including a migration for the configuration file.  The wiki has been updated as well, and it now documents the `dns.bind_hosts` parameter.

I will now close this issue.  If you find any bugs with the new feature, please file them as separate bugs.  Thanks!

**Comment by cjustinhall** [comment]
@ainar-g  I see this from the wiki - 
'bind_hosts (after v0.106.0) - IP addresses on which to serve DNS queries. The addresses must be on different interfaces.'

My limited knowledge believes the ipv4 and ipv6 addresses are on the same interface. Are you saying by this comment that we would NOT be able to bind both an ipv6 and ipv4 address if they are on the same interface?

**Comment by ainar-g** [comment]
@cjustinhall, you are correct!  I've improved that section of our Wiki and also added examples as well as a note about `0.0.0.0`.

**Comment by cjustinhall** [comment]
Had a look at the wiki. Good modifications. Very clear now. Thanks. Will give this a try.
