### ISSUE TITLE
Question: Can AGH check for duplicate domains?

### ISSUE THREAD

**Issue by BobWs** [AdguardTeam/AdGuardHome#1402]
Hi,
I was wondering if Adguardhome is checking and removing duplicate domains in the filter section (Filters and hosts blocklists)?

I've been using pihole for a while now and recently switched to adguardhome. Pihole has the built-in possibility to check the filters for duplicate domains and then remove them. This can also be seen in the logfile. 

Does AGH also have this possibility? I haven't been able to find anything about it anywhere. I did notice that duplicate domains just occur.

Would you consider building this in?

**Comment by ameshkov** [comment]
When the filtering engine is being built from the blocklists, of course, duplicate domain names are ignored.

The source blocklists files are kept intact, though.
