### ISSUE TITLE
Question: Is it possible to add static DHCP-leases in batch (by file)?

### ISSUE THREAD

**Issue by lxz81** [AdguardTeam/AdGuardHome#1403]
I am concidering switching from pihole(+dhcpd) to adguard home. However, I have about 30 static dhcp leases which I would like to migrate. 

Is it possible to add them by file instead of copy-pasting 30 mac addresses/ip-addresses/hostnames?

**Comment by ameshkov** [comment]
The only way would be to edit configuration file `AdGuardHome.yaml` manually and add them there.

1. Try adding one static DHCP lease just to see what the format is
2. Stop AdGuard Home
3. Edit `AdGuardHome.yaml` and add your DHCP leases there
4. Start AGH

**Comment by adamtal3** [comment]
For anyone it may interest in the future.
I've opened the DHCP page, added one IP while the Chrome developer tools was open to get the URL is posts to, copied my IPs from an existing excel file and parsed it to requests like following (update the AdGuard URL according to the one copied from your network tab):

```javascript
`MAC1	IP1	Name1
MAC2	IP2	Name2
MAC3	IP3	Name3`.split('\n').forEach(line => {
    let arr = line.split('\t');
    fetch('YOUR_OWN_ADGUARD_URL_HERE/control/dhcp/add_static_lease', {
        method: 'post',
        body: JSON.stringify({ mac: arr[0].trim(), ip: arr[1].trim(), hostname: arr[2].trim() })
      });
});
```
