### ISSUE TITLE
Feature Request - Centralised Logging For Multiple AdguardHome Servers

### ISSUE THREAD

**Issue by nokiboi39** [AdguardTeam/AdGuardHome#1404]
Hi,
Would it be possible to utilise a central logging location and where the time period of logs could be increased past 90 days ?

Am looking at the scenario where you have more than one AdguardHome Server so the logs would goto a central location and ideally be able to be viewed as one?

Thanks

**Comment by ameshkov** [comment]
Well, usually this is not how it's implemented.

We could think about some logs rotation algorithm instead, but centralizing and viewing sounds like a task for Kibana+ElasticSearch

**Comment by q2dg** [comment]
I think this could be achieved configuring FileBeat to seek querylog.json file, but a "getting started" tutorial could be handy.
