### ISSUE TITLE
 After using ad, ddns resolved to my vps, not my wan's ip, how can I solve it

### ISSUE THREAD

**Issue by authon** [AdguardTeam/AdGuardHome#1410]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ *] I am running the latest version
- [ *] I checked the documentation and found no answer
- [ *] I checked to make sure that this issue has not already been filed

### Issue Details

After using ad, ddns resolved to my vps, not my wan's ip, how can I solve it

**Comment by ameshkov** [comment]
We'll need much more details to figure out how to answer this question.
