### ISSUE TITLE
Error in syslog: AdGuardHome[4886]: 2020/02/17 05:59:49 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'

### ISSUE THREAD

**Issue by txcanyon** [AdguardTeam/AdGuardHome#1414]
- [X ] I am running the latest version : Version: Beta: v0.100.9-91-g9a81
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

OpenWRT 19.07.1 x86_64
Homebuilt Intel i5-4570T

I am seeing some log errors for AGH in the log file:
`Sun Feb 16 23:59:49 2020 daemon.err AdGuardHome[4886]: 2020/02/17 05:59:49 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'
Sun Feb 16 23:59:49 2020 daemon.err AdGuardHome[4886]: 2020/02/17 05:59:49 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'
Mon Feb 17 00:00:00 2020 daemon.err AdGuardHome[4886]: 2020/02/17 06:00:00 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'`

It is not constant, so not sure what specifically is causing it. I do NOT use The Parental control web service feature nor do I use the Enforce Safe Search feature.

Love this on OpenWRT. It has eliminated the need for an additional RPi or X86 nuc to serve as my dns server.

**Comment by ameshkov** [comment]
> It is not constant, so not sure what specifically is causing it. I do NOT use The Parental control web service feature nor do I use the Enforce Safe Search feature.

`dns-family.adguard.com` is used for both parental control and safebrowsing lookups.

We'll need to get the debug-level log to figure out what query is causing this.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by BigBobDalton** [comment]
I am receiving the same error, has this been resolved?

**Comment by ameshkov** [comment]
Hi, to troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Send the log file to `devteam@adguard.com`

**Comment by BigBobDalton** [comment]
Ive updated my DNS servers to include the missing dns.family ip.  Works now

 

Thanks

 

 

Von: Andrey Meshkov <notifications@github.com>
Antworten an: AdguardTeam/AdGuardHome <reply@reply.github.com>
Datum: Mittwoch, 22. April 2020 um 22:13
An: AdguardTeam/AdGuardHome <AdGuardHome@noreply.github.com>
Cc: BigBobDalton <bob@dalton.li>, Comment <comment@noreply.github.com>
Betreff: Re: [AdguardTeam/AdGuardHome] Error in syslog: AdGuardHome[4886]: 2020/02/17 05:59:49 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query' (#1414)

 

Hi, to troubleshoot this issue we need to see AdGuard Home logs.
Configure AdGuard Home to collect logs: 
Specify log_file
Set verbose to True
Restart AdGuard Home and reproduce the issue
Send the log file to devteam@adguard.com
