### ISSUE TITLE
tls is not a valid IP

### ISSUE THREAD

**Issue by HopHop20** [AdguardTeam/AdGuardHome#1415]
I'm trying to use a DOT server to resolve a DOH server. My upstream server is "https://dns.cloudflare.com/dns-query". My bootstrap sever is "tls://8.8.8.8". When is test upstream server I receive message "Specified DNS servers are working correctly". When I click apply button I receive message "Error: control/set_upstreams_config | tls://8.8.8.8 can not be used as bootstrap dns cause: tls is not a valid IP | 400". Only way AdGuardHome will accept "tls://8.8.8.8" as a bootstrap dns is to manually add in AdGuardHome.yaml

Related? https://github.com/AdguardTeam/AdGuardHome/issues/960
It seems we can use DOT as bootstrap but string validation prevents it? Hints the issue I'm having

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1208#issuecomment-558319101
>@ameshkov In theory, we can allow adding DOT bootstrap.
@szolin dnsproxy already supports this. Can we port this to AGH? The only limitation is that bootstrap's address should have an IP address, not a domain name.

**Comment by ameshkov** [comment]
Yeah, in theory, we can use DOH/DOT as bootstrap. We'll need to test this, though.

I'll assign #960 to a milestone.
