### ISSUE TITLE
Query log: Allow searching in response field

### ISSUE THREAD

**Issue by HopHop20** [AdguardTeam/AdGuardHome#1416]
I would like to search for an IP address in the response field to simply see if any other domains that were queried recently are currently resolving to the same IP address.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/481

**Comment by mHatsune** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1933

**Comment by malahal** [comment]
I see a TCP connection to an IP address in my firewall. I would like to see the domain name used to get that IP address. This IP address should be in the 'Answer' part of the data in the query log. But I am unable to search query log using the IP address (of remote hosts).

Is there a way to achieve this?

**Comment by ainar-g** [comment]
For those looking for this functionality, this issue has essentially been merged into #1933.
