### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xwarior2017** [AdguardTeam/AdGuardHome#1417]
im using go 1.13.8
node.js 13.x
but build not success
log error:

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   'client',
1 verbose cli   'run',
1 verbose cli   'build-prod'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'prebuild-prod', 'build-prod', 'postbuild-prod' ]
5 info lifecycle dashboard@0.1.0~prebuild-prod: dashboard@0.1.0
6 info lifecycle dashboard@0.1.0~build-prod: dashboard@0.1.0
7 verbose lifecycle dashboard@0.1.0~build-prod: unsafe-perm in lifecycle true
8 verbose lifecycle dashboard@0.1.0~build-prod: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/adg/AdGuardHome/client/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/go
9 verbose lifecycle dashboard@0.1.0~build-prod: CWD: /root/adg/AdGuardHome/client
10 silly lifecycle dashboard@0.1.0~build-prod: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js'
10 silly lifecycle ]
11 silly lifecycle dashboard@0.1.0~build-prod: Returned: code: 134  signal: null
12 info lifecycle dashboard@0.1.0~build-prod: Failed to exec build-prod script
13 verbose stack Error: dashboard@0.1.0 build-prod: `NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid dashboard@0.1.0
15 verbose cwd /root/adg/AdGuardHome
16 verbose Linux 5.1.0-aml-s905
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "client" "run" "build-prod"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 134
22 error dashboard@0.1.0 build-prod: `NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js`
22 error Exit status 134
23 error Failed at the dashboard@0.1.0 build-prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ] 

> 

thankyou

**Comment by IldarKamalov** [comment]
Can't reproduce on the same node.js and npm version.
Let's try to remove `node_modules` from the client folder and run `npm install`, `npm run build-prod`

**Comment by xwarior2017** [comment]
> Can't reproduce on the same node.js and npm version.
> Let's try to remove `node_modules` from the client folder and run `npm install`, `npm run build-prod`

thankyou its worked now
