### ISSUE TITLE
Particular domain doesn’t show up in query log, isn’t being blocked, can’t block

### ISSUE THREAD

**Issue by japtor** [AdguardTeam/AdGuardHome#1418]
### Issue Details

* **Version of AdGuard Home server:**
v0.100.9
* **How did you setup DNS configuration:**
NAS
* **If it's a router or IoT, please write device model:**
Synology DS218+
* **Operating system and version:**
DSM 6.2.2-24922 Update 4

### Expected Behavior
I’d expect all queries to show up in the query log, and explicitly blocked domains to be blocked.

### Actual Behavior
Got a phishing link (http://w1s-verizon.com/) and tried to block it in AdGuard Home using a domain filtering rule, but that didn’t work. Checked the query log and it wasn’t showing up at all there. 

Tried out some other sites which showed up fine in the query list (and tested other already blocked domains, which also worked correctly), but not that one domain I was trying to block For whatever reason.

Could the hyphen be screwing something up or just some random bug here? I tried it out in the iOS AdGuard extension and that worked to block it. Checked my whitelists/filters in the app and home server and neither had anything that’d match that domain.

**Comment by ArchiveBase** [comment]
- You can search domain name w1s-verizon.com 
- Add ||w1s-verizon.com^$important then flush DNS and check again.

**Comment by japtor** [comment]
> * You can search domain name w1s-verizon.com
> * Add ||w1s-verizon.com^$important then flush DNS and check again.

Had it added like that but it was flushing the DNS that did it, thanks.

**Comment by ArchiveBase** [comment]
> Had it added like that but it was flushing the DNS that did it, thanks.

https://github.com/AdguardTeam/AdGuardHome/issues/1145 will help for that later.
