### ISSUE TITLE
Dont update/install filter in Entware 

### ISSUE THREAD

**Issue by pomazanbohdan** [AdguardTeam/AdGuardHome#1419]
0.100.9~207e023
firmware router - padavan (rt-n56u)
After install AdGuard, i add new filter end error:

`Error: control/filtering/add_url | Couldn't fetch filter from url https://filters.adtidy.org/extension/chromium/filters/1.txt: Get https://filters.adtidy.org/extension/chromium/filters/1.txt: x509: certificate signed by unknown authority | 400`

Time in router - actual
All  rules counter - 0
DNS Queries - XXX and internet work

**Comment by pomazanbohdan** [comment]
`Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: x509: certificate signed by unknown authority | 502`

**Comment by ameshkov** [comment]
Duplicates this one: https://github.com/AdguardTeam/AdGuardHome/issues/1311
