### ISSUE TITLE
Redesigned query log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1421]
I've tried to take into account most of the issues reported here (not all of them, though).

@IldarKamalov please take a look:
https://share.goabstract.com/3368bf70-644d-4629-9463-5245b35a543b?mode=design&sha=10b7a0d539159c8a1fbf1ff60ff07e382694dbe6 (note for others: the img is not private, wait for the implementation)

It will require some changes on the server-side as well (we don't divide domain and client anymore)

**Comment by ArchiveBase** [comment]
See https://github.com/AdguardTeam/AdGuardHome/issues/1498#issuecomment-602088517

**Comment by Ultrabenosaurus** [comment]
@ArchiveBase 24h time please, not AM/PM!

**Comment by ArchiveBase** [comment]
@Ultrabenosaurus Well, it's hard to recognize 24hrs format immediately during check logs as you worry about dates then #1498 for custom formats.

**Comment by lancelot-moon** [comment]
I more like 24-hour clock because we can ignore AM/PM.
But time format in most AG products is localized according to system.
