### ISSUE TITLE
DHCP client not appearing in Query Log

### ISSUE THREAD

**Issue by nelox** [AdguardTeam/AdGuardHome#1422]
### Issue Details

In summary, a DHCP client does not appear in the Query Log. However, all other DHCP clients do.

* **Version of AdGuard Home server:**
  * 0.100.9
* **How did you setup DNS configuration:**
  * `Internet`
`|`
`Router <-> DNS Resolver`
`|`
`DHCP Server <-> AdGuard Home`
* **If it's a router or IoT, please write device model:**
  * pfsense 2.4.4-RELEASE-p3
* **Operating system and version:**
  * Docker adguard/adguardhome::latest

### Expected Behavior
All DHCP Clients should be listed in the Query Log

### Actual Behavior
Successful DNS lookups from DHCP Client 192.168.1.145 are missing from the AdGuard Query Log

### Screenshots

DHCP Client 192.168.1.145

```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 14:10:9f:d3:68:13
	inet 192.168.1.145 netmask 0xffffff00 broadcast 192.168.1.255
	media: autoselect
	status: active
```

Restart DNS on client 192.168.1.145

```
% sudo killall -HUP mDNSResponder
Password:
%
```

Restart DNS Resolver

Feb 21 15:44:55 | unbound | 29939:0 | info: start of service (unbound 1.9.1).
-- | -- | -- | --
Feb 21 15:44:55 | unbound | 29939:0 | notice: init module 1: iterator
Feb 21 15:44:55 | unbound | 29939:0 | notice: init module 0: validator
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.131072    0.262144 1
Feb 21 15:44:52 | unbound | 81473:0 | info: lower(secs) upper(secs) recursions
Feb 21 15:44:52 | unbound | 81473:0 | info: [25%]=0 median[50%]=0 [75%]=0
Feb 21 15:44:52 | unbound | 81473:0 | info: histogram of recursion processing times
Feb 21 15:44:52 | unbound | 81473:0 | info: average recursion processing time 0.201391 sec
Feb 21 15:44:52 | unbound | 81473:0 | info: server stats for thread 3: requestlist max 0 avg 0 exceeded 0 jostled 0
Feb 21 15:44:52 | unbound | 81473:0 | info: server stats for thread 3: 4 queries, 3 answers from cache, 1  recursions, 0 prefetch, 0 rejected by ip ratelimiting
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.262144    0.524288 9
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.131072    0.262144 4
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.065536    0.131072 15
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.032768    0.065536 4
Feb 21 15:44:52 | unbound | 81473:0 | info: lower(secs) upper(secs) recursions
Feb 21 15:44:52 | unbound | 81473:0 | info: [25%]=0.0830123 median[50%]=0.117965 [75%]=0.291271
Feb 21 15:44:52 | unbound | 81473:0 | info: histogram of recursion processing times
Feb 21 15:44:52 | unbound | 81473:0 | info: average recursion processing time 0.169838 sec
Feb 21 15:44:52 | unbound | 81473:0 | info: server stats for thread 2: requestlist max 1 avg 0.03125 exceeded 0 jostled 0
Feb 21 15:44:52 | unbound | 81473:0 | info: server stats for thread 2: 36 queries, 4 answers from cache,  32 recursions, 0 prefetch, 0 rejected by ip ratelimiting
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.524288    1.000000 2
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.262144    0.524288 6
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.131072    0.262144 10
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.065536    0.131072 12
Feb 21 15:44:52 | unbound | 81473:0 | info:    0.032768    0.065536 8
Feb 21 15:44:52 | unbound | 81473:0 | info: lower(secs) upper(secs) recursions
Feb 21 15:44:52 | unbound | 81473:0 | info: [25%]=0.073728 median[50%]=0.125611 [75%]=0.242483
Feb 21 15:44:52 | unbound | 81473:0 | info: histogram of recursion processing times
Feb 21 15:44:52 | unbound | 81473:0 | info: average recursion processing time 0.165056 sec
Feb 21 15:44:52 | unbound | 81473:0 | info: server stats for thread 1: requestlist max 1 avg 0.0263158 exceeded 0 jostled 0
Feb 21 15:44:52 | unbound | 81473:0 | info: server stats for thread 1: 42 queries, 4 answers from cache,  38 recursions, 0 prefetch, 0 rejected by ip ratelimiting
Feb 21 15:44:51 | unbound | 81473:0 | info:    0.262144    0.524288 1
Feb 21 15:44:51 | unbound | 81473:0 | info:    0.131072    0.262144 8
Feb 21 15:44:51 | unbound | 81473:0 | info:    0.065536    0.131072 5
Feb 21 15:44:51 | unbound | 81473:0 | info: lower(secs) upper(secs) recursions
Feb 21 15:44:51 | unbound | 81473:0 | info: [25%]=0.111411 median[50%]=0.16384 [75%]=0.221184
Feb 21 15:44:51 | unbound | 81473:0 | info: histogram of recursion processing times
Feb 21 15:44:51 | unbound | 81473:0 | info: average recursion processing time 0.158828 sec
Feb 21 15:44:51 | unbound | 81473:0 | info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
Feb 21 15:44:51 | unbound | 81473:0 | info: server stats for thread 0: 21 queries, 7 answers from cache,  14 recursions, 0 prefetch, 0 rejected by ip ratelimiting
Feb 21 15:44:51 | unbound | 81473:0 | info: service stopped (unbound 1.9.1).

Query DNS from 192.168.1.145

```
% dig wikipedia.org

; <<>> DiG 9.10.6 <<>> wikipedia.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46589
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;wikipedia.org.			IN	A

;; ANSWER SECTION:
wikipedia.org.		478	IN	A	103.102.166.224

;; Query time: 395 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Fri Feb 21 15:48:18 AEDT 2020
;; MSG SIZE  rcvd: 58

```
Query Log sans 192.168.1.145 and wikipedia.org

<img width="1080" alt="Screen Shot 2020-02-21 at 15 50 59" src="https://user-images.githubusercontent.com/2967891/75005282-086d7080-54c2-11ea-9779-fe33aca44220.png">

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by nelox** [comment]
You may close this one as invalid. I had misconfigured the client to not use the AdGuard DNS. (Facepalm). That has since been corrected and the client appears in the Query Log as expected. Sorry for the trouble.
