### ISSUE TITLE
Digit grouping ("thousands separator") for numbers on the dashboard

### ISSUE THREAD

**Issue by jandillmann** [AdguardTeam/AdGuardHome#1423]
### Problem Description
This is a purely cosmetic feature request, but one that would add to the nice and modern look of the dashboard.

Currently numbers on the dashboard are displayed without any kind of formatting (neither in the cards up top nor in the tables below, except for percentages with two decimal places separated by a period).

For example, the top left card shows `123456` DNS Queries. Especially for longer retention times these numbers get large and are not as readable as they could be.

### Proposed Solution
Format numbers on the dashboard using decimal grouping. Because the percentages already use a decimal point a comma could be used to group thousands (US-Style).

For example, the number from above could be formatted as `123,456` DNS Queries.

### Alternatives Considered
A space character would also increase the readability without confusing Europeans, who use the comma and period the opposite way.

The number from above could be formatted as `123 456` DNS Queries.

**Comment by ameshkov** [comment]
@IldarKamalov this should be trivial, use locale-specific formatiting.
