### ISSUE TITLE
[Feature Request] Add CURL to Dockerfile for HEALTHCHECKS

### ISSUE THREAD

**Issue by UnR34L** [AdguardTeam/AdGuardHome#1426]
I'd like to add some simple healthchecks using CURL.

**Comment by ameshkov** [comment]
Could you please explain this in more detail and, ideally, provide some examples.

**Comment by UnR34L** [comment]
From my understanding of how healthchecks work, a command is sent to the container, if the command gets exit code 0, it's considered healthy, anything else is unhealthy and I can be notified or the container can be restarted by the docker daemon.

A simple way of doing it is to run CURL inside the container.

https://docs.docker.com/compose/compose-file/#healthcheck

**Comment by ameshkov** [comment]
Wouldn't it be better to run nslookup instead of curl?

Also, do you know any docker files which have this healtcheck so that we could take a look at how other people implement this/

**Comment by UnR34L** [comment]
I've only ever seen people use curl.

There's two ways people do it, adding it directly to the Dockerfile using HEALTHCHECK

`HEALTHCHECK [OPTIONS] CMD command`

Example:
`HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost/ || exit 1`

https://docs.docker.com/compose/compose-file/#healthcheck

or adding it later in the compose/run commands. I personally prefer adding it in later in my compose file then I can easily choose my own interval/timeouts.

**Comment by ameshkov** [comment]
It's just AdGuard Home is a DNS server and it makes sense to use nslookup, something like this:
`nslookup example.org 127.0.0.1 || exit 1`

**Comment by UnR34L** [comment]
I see what you mean, now. This is a step up from what I was asking for and it does make more sense.

I was only interested in the general health of the container and getting notified if anything caused problems and stopped the container from starting (recently I saw some images being updated and breaking containers).

This would work as a healthcheck. Thanks.

**Comment by ANDOSX** [comment]
https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr

**Comment by UnR34L** [comment]
> https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr

Saw that but for some containers running at home I think I'll take the risk :)
