### ISSUE TITLE
Hosts blocklist update check scheduling

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#1427]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Please consider adding scheduling for hosts blocklist update checks. e.g. Update all hosts blocklists every 24 hours.

**Comment by ameshkov** [comment]
There's a "Filters update interval" in the general settings, isn't that what you're looking for?
