### ISSUE TITLE
show more information for CNAME matches

### ISSUE THREAD

**Issue by hoshsadiq** [AdguardTeam/AdGuardHome#1429]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Since #1185 it has been possible to block domains that are disguised through CNAMEs. Currently when I see a blocked domain, I can see which list blocks that specific domain. This is also the case for domains matched through CNAME lists (the ones that show up as `Blocked by CNAME or IP in response`).

While the items that were blocked directly isn't an issue, as you can see in the block list the exact reason why it's blocked, for CNAME resolved matches it's not as straight forward. Specifically, all it shows is `Blocked by CNAME or IP in response`, the list that is blocking the domain, and lastly the answer's IPs. It's hard to figure out which item in the list blocked it.

### Proposed Solution
It would be nice to say which exact domain in the list ended up blocking this request. E.g. if badguy.com is blocked, and the badguy.thirdparty.com is a CNAME to badguy.com, the message in the query list should show something like:

|      Domain name      | Type |                                               Response                                               |
|:----------------------|:----:|:-----------------------------------------------------------------------------------------------------|
| badguy.thirdparty.com |   A  | Blocked by CNAME or IP in response<br>A: 8.8.8.8 (ttl=251)<br>Blocked because badguy.com was blocked |

### Alternatives Considered
N/A

### Additional Information
N/A

**Comment by ArchiveBase** [comment]
@hoshsadiq Hover mouse over (?) icon that display next to 'Blocked by CNAME or IP in response' then you can be see the matched rule. I dont know if that had changed after https://github.com/AdguardTeam/AdGuardHome/issues/993 however display exact rule better than the sentence.

**Comment by hoshsadiq** [comment]
Aah pardon me. The ones I was getting confused about was blocked due to an IP address being in the blocklist. You're right, it is there! Thanks.
