### ISSUE TITLE
DHCP on docker does not work when client requests IP

### ISSUE THREAD

**Issue by jorgebnunes** [AdguardTeam/AdGuardHome#1430]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.9
* **How did you setup DNS configuration:**
  * it is working correctly
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B) - AGH on Docker
* **Operating system and version:**
  * Debian Buster

### Problem:

When I configured AGH to use DHCP server instead of main router DHCP and tested it, for a client requesting IP, it shows:

2020/02/26 11:42:50 1#192 [debug] github.com/AdguardTeam/AdGuardHome/dhcpd.(*Server).handleDiscover(): Message from client: Discover.  ReqIP: <nil>  HW: c0:7f:41:d1:c3:6e  Hostname: 
2020/02/26 11:42:50 1#192 [debug] github.com/AdguardTeam/AdGuardHome/dhcpd.(*Server).handleDiscover(): Replying with offer: offered IP 192.168.1.128 for 24h0m0s with options map[OptionSubnetMask:[255 255 255 0] OptionRouter:[192 168 1 1] OptionDomainNameServer:[172 17 0 2] OptionIPAddressLeaseTime:[0 1 81 128] OptionDHCPMessageType:[2] OptionServerIdentifier:[172 17 0 2]]

but client never gets the IP 192.168.1.128

When I enable my router DHCP service then the info is:

2020/02/26 11:44:04 1#192 [debug] github.com/AdguardTeam/AdGuardHome/dhcpd.(*Server).handleDHCP4Request(): Message from client: Request.  IP: 0.0.0.0  ReqIP: 192.168.1.128  HW: c0:7f:41:d1:c3:6e
2020/02/26 11:44:04 1#192 [debug] github.com/AdguardTeam/AdGuardHome/dhcpd.(*Server).handleDHCP4Request(): Request message not for this DHCP server ([192 168 1 1] vs 172.17.0.2)

What I'm doing wrong?
Thank you for your help and patience with a newbie person.

Regards

**Comment by szolin** [comment]
> Request message not for this DHCP server ([192 168 1 1] vs 172.17.0.2)

This means that the client request contains ServerIdentifier extension with data `192.168.1.1`
But this DHCP server is running on `172.17.0.2`, so the client's request can't be processed, because it's directed to another DHCP server.

I don't know what is the correct behaviour in this situation.  I guess we should find out how mainstream DHCP servers handle this extension.

**Comment by ameshkov** [comment]
Well, this is understandable since the dockerized AGH does not know what the host machine IP address.

Maybe it should be run with `--net=host` instead?

**Comment by jorgebnunes** [comment]
Hi again!

--net=host did the trick!

I was running the container specifying all the ports:

-p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp  -p 80:80/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp

And that's why Portainer didn't let me change the bridge mode to network mode Host.

Thank you very much!

**Comment by ameshkov** [comment]
@szolin we may need to mention this in the Docker image readme

**Comment by jorgebnunes** [comment]
yes, please.
