### ISSUE TITLE
Query logs: too slow, hanging when searching

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1431]
New query logs have several issues:

1. initial list is 10x slower (2sec vs 250ms)
2. search list is 4x slower (1sec vs 250ms)
3. hanging when searching data (server keeps returning the same response when there's not enough data to return, I guess)

**Comment by ameshkov** [comment]
Fixed with https://github.com/AdguardTeam/AdGuardHome/commit/f84331abdea214efb1530416a4957ba2dda81e43
