### ISSUE TITLE
AdGuardHome can not count the statistics data after I cleaned the statistics data

### ISSUE THREAD

**Issue by man2018** [AdguardTeam/AdGuardHome#1432]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
yes
- [ ] I checked the documentation and found no answer
yes
- [ ] I checked to make sure that this issue has not already been filed
yes

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior

My vps server has two IPs that one is IPV4 and the other one is IPV6, I created DoH with Adguard Home on vultr server, and i cleaned the statistics data, so It can not work again, i found querylog.json is note exist

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
