### ISSUE TITLE
Document the DNS blocking limitations and issues

### ISSUE THREAD

**Issue by jerrac** [AdguardTeam/AdGuardHome#1433]
### Problem Description
YouTube ads are not blocked. 

When viewing YT videos via the Roku app, or Firefox without any adblocking extension enabled, the preroll ads always play.

Searching the issue queue pulled up multiple comments stating that DNS blocking does not work for YouTube ads. This is confusing because I have seen PiHole successfully block YouTube ads. LinusTechTips actually did a YouTube video doing so.

### Proposed Solution
Please document if AdGuardHome can, or cannot, block YouTube ads in the README, or somewhere new users can find quickly.

### Additional Information
* I'm running AdGuardHome via Docker. Version v0.100.9.
* I enabled all 4 default filter lists.
* From https://github.com/AdguardTeam/AdGuardHome/issues/1325 I added these filters:
  * Peter Lowe's List https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  * StreamingAds https://raw.githubusercontent.com/FadeMind/hosts.extras/master/StreamingAds/hosts
  * Dan Pollock's Hosts https://someonewhocares.org/hosts/zero/hosts

**Comment by ArchiveBase** [comment]
>because I have seen PiHole successfully block YouTube ads. LinusTechTips actually did a YouTube video doing so.

https://github.com/AdguardTeam/AdGuardHome/issues/1325

**Comment by ameshkov** [comment]
> This is confusing because I have seen PiHole successfully block YouTube ads. LinusTechTips actually did a YouTube video doing so.

Could you please link this video?

**Comment by mmotti** [comment]
Pihole can't block YouTube ads. No DNS based adblocker can.

It is impossible without modified YouTube apps or browser extensions.

**Comment by jerrac** [comment]
The video in question: https://www.youtube.com/watch?v=KBXTnrD_Zs4

Just rewatched it, they did mention that blocking YouTube ads was iffy, and they didn't see it happen in the PiHole logs. I hadn't seen the video since it came out, so I didn't remember that. :)

Anyway, I still think it would be a good thing to document that blocking YouTube ads isn't easy/possible somewhere people will find when they start looking. A version @mmotti 's comment in the readme or a wiki page would be awesome.

Thanks!

**Comment by ArchiveBase** [comment]
Well, If certain youtube ads possible to block using browser extension then adguard home will be capable to do it in future

**Comment by ameshkov** [comment]
Well, I think documenting known issues and limitations is a good thing anyway.

Besides Youtube, what do you think makes sense to add?

**Comment by planet0** [comment]
Facebook and Instagram sponsored posts and stories in app, and any TV apps that include advertising will be a hit-and-miss, such as Twitch, free-to-air catch up or on demand apps.

Essentially, any advertising that shares a domain with content will be a known issue and limitation.

**Comment by jerrac** [comment]
> Essentially, any advertising that shares a domain with content will be a known issue and limitation.
Something like this, plus a couple examples, would cover it.

**Comment by ameshkov** [comment]
Argh, bad bot
