### ISSUE TITLE
Add information about running DHCP server in docker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1434]
Mention in the Docker doc that the user should use `--net=host` if they want to use AGH as a DHCP server:
https://github.com/AdguardTeam/AdGuardHome/issues/1430

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1324#issuecomment-576003838
@szolin add https://github.com/AdguardTeam/AdGuardHome/issues/1078 too

>@ameshkov @szolin yeah, it makes sense to keep track of AGH packages that we don't maintain ourselves, but which can be helpful to the users.
Let's add both this[x] and this https://github.com/AdguardTeam/AdGuardHome/issues/1078#issuecomment-570082643 to Wiki.

**Comment by szolin** [comment]
done (wiki repo)
