### ISSUE TITLE
Block apps connectivity and DOH

### ISSUE THREAD

**Issue by eoopx** [AdguardTeam/AdGuardHome#1436]
I get TikTok app as example and even we activated 'TikTok' through blocked services but our mobile devices tiktok android app still loads each person profile albums (many random images) and other contents. 

(blocked_services.go contain all required tiktok domains)
https://github.com/AdguardTeam/AdGuardHome/blob/f84331abdea214efb1530416a4957ba2dda81e43/home/blocked_services.go#L102 

Later, i added ||dns.google.com^$important and ||dns.google^$important to custom filtering rules then it solved means nothing loads. so i see those apps use DOH itself to bypass blocking(?)

(Please note, If we block ||dns.google.com^$important and ||dns.google^$important using custom filtering rules while use google DNS (DOH or whatever) for AdGuardHome then it doesn't make any problem)

Above i only said about one app and many other desktop(/browsers too?) and mobile apps use that trick so do you guys have any idea or method to block those all using built-in new feature?

**Comment by ArchiveBase** [comment]
Add something like 'Disable IPv6' option however it needs auto enable when block certain service. Here example https://github.com/nextdns/metadata/blob/master/parentalcontrol/bypass-methods

**Comment by eoopx** [comment]
Isn't this important?

**Comment by ArchiveBase** [comment]
6. Block Bypass Methods https://github.com/AdguardTeam/AdGuardHome/issues/1446

**Comment by ameshkov** [comment]
Tbh, I am not sure if we should do that manually (I mean blocking `dns.google.com` does not look like a really good solution to me).

Once we add proxy support, it'd be easier to handle these cases.
