### ISSUE TITLE
[feature request] Filtered TTL could be controlled (in Null IP or Custom IP mode)

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1438]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I noticed query filtered domain will return a TTL=10 answer when set non-NXDOMAIN in blocking mode. And I think this TTL is too short and result too many and frequent query from client (even increase my block rate up to 50%).
### Proposed Solution

May add a option to control filtered TTL time to user.

**Comment by hezhijie0327** [comment]
You can change the "blocked_response_ttl" value in "AdGuardHome.yaml"

eg: "blocked_response_ttl: 3600"

**Comment by Mosney** [comment]
> You can change the "blocked_response_ttl" value in "AdGuardHome.yaml"
> 
> eg: "blocked_response_ttl: 3600"

Got it, I only search in Web Console and not check the config file.

**Comment by ameshkov** [comment]
Yeah, not every configuration setting is exposed to the Web.
