### ISSUE TITLE
翻译显示有问题

### ISSUE THREAD

**Issue by yiguihai** [AdguardTeam/AdGuardHome#1439]
版本:  v0.100.9-134-g80df4 编译这个版本的时候出现翻译不完整的问题，已经清理过浏览器缓存
![批注 2020-02-29 114334](https://user-images.githubusercontent.com/22967964/75600326-f6ef1e80-5ae8-11ea-9d23-06415b3b6d73.png)

**Comment by hanson-l** [comment]
他们还没整合翻译，等正式版吧

They haven't integrated the translation yet, wait for the official release.

**Comment by ameshkov** [comment]
顺便说说, 如果你说英语就你可以帮助翻译AdGuard Home: https://github.com/AdguardTeam/AdGuardHome#translate
