### ISSUE TITLE
Non standard port for Upstream DNS

### ISSUE THREAD

**Issue by xiaoqingfengATGH** [AdguardTeam/AdGuardHome#1442]
I know DNS exclusively uses port 53 pretty much. But it would be VERY useful if there were some way to enter a custom Upstream DNS Server with a specific port number. Let me explain why.

My ISP employs a transparent DNS cache. Meaning they intercept all outgoing DNS requests (port 53 intercepting, I tested this by running an OpenVPN server on my VPS on port 53 UDP, I couldn’t connect, but I could connect when using another internet connection) no matter what the destination is and proxy them. This is troublesome for DDNS which I use a lot. It dramatically increases the latency of any changes made to the DDNS records which causes me problems. Not to mention the privacy concerns; and well, I just don’t like it !

I have AdGuardHome running on my network, but of course, its upstream requests are still going to be proxied by my ISP. So my solution to this would be to set up my remote VPS with a DNS server running on a custom port. Then if I could set this as an upstream DNS server in AdGuardHome using the custom port, I could bypass the ISP cache as all upstream requests would not be occurring on port 53 and my ISP would ignore them.

Just a thought. Thanks for reading this.

**Comment by ameshkov** [comment]
> Then if I could set this as an upstream DNS server in AdGuardHome using the custom port

Of course, you can do that for any type of upstream, just specify the port number in the address:

```
8.8.8.8:5353
tls://1.1.1.1:853
https://1.1.1.1:443/dns-query
```
