### ISSUE TITLE
Average Processing Time has just blown out by 10x and I can't work out why

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#1443]
[AdGuardHome.yaml.txt](https://github.com/AdguardTeam/AdGuardHome/files/4275017/AdGuardHome.yaml.txt)
### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.9
* **How did you setup DNS configuration:**
  * Windows Server 2012 R2 DHCP server
* **If it's a router or IoT, please write device model:**
  * n/a
* **Operating system and version:**
  * Windows Server 2012 R2

### Expected Behavior
Normal behaviour had average processing time in the 40-60ms range

### Actual Behavior
Starting approx. 1 week ago I started to see my Amazon Echo's become very slow to respond and often timeout. The same with my smart lights, smart HVAC controllers, etc.
When I investigated, I found AGH was showing average processing time in the 800-1000ms range for days on end.

### Additional Information
I tried disabling `Use AdGuard browsing security web service` but it had no impact.
I dropped statistics retention from 7 days to 24 hours to track more closely but saw no change in average processing time.
I have had to bypass AGH entirely and instead point my device directly to 1.1.1.1 to restore normal performance.

I'm really not sure what else to try here as for all intents and purposes, I'm seeing no other issues or changes in the networking environment at that time that I can attribute to this.

Any suggestions or log analysis that might point to anything to look at would be greatly appreciated!
[AGH.zip](https://github.com/AdguardTeam/AdGuardHome/files/4275005/AGH.zip)

**Comment by AnthonyBe** [comment]
Apologies, I had a brain fart on where the log file was and didn't see it staring me in the face.
Have logged another more specific issue (https://github.com/AdguardTeam/AdGuardHome/issues/1444) and am now wondering if the two are linked..

**Comment by ameshkov** [comment]
Duplicates #1444
