### ISSUE TITLE
Check what are our options for woking without root on Linux

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1447]
Maybe, we can make it this way (we should test it):

1. Make Linux user/group configurable
2. Run with root, run set CAP_NET_BIND_SERVICE for our binary
3. Downgrade to the specified group

If CAP_NET_BIND_SERVICE is persisted, we'll need to extend this task and explain what additional console actions we'll add. 

This comment can be useful:
https://github.com/AdguardTeam/AdGuardHome/issues/1193#issuecomment-576862627

**Comment by szolin** [comment]
Unfortunately, there's no way we can maintain CAP_NET_BIND_SERVICE flag set on a binary file after it's replaced.  We also can't replace the files owned by root user after we do setuid().

**Comment by ameshkov** [comment]
Well, losing auto-upgrade is really painful.

Let's proceed with a simpler approach:

1. Fix #1193 
2. Add more information to the documentation about how to run AGH without root, and how to upgrade it manually in this case
