### ISSUE TITLE
Filter rule for particular domain

### ISSUE THREAD

**Issue by eoopx** [AdguardTeam/AdGuardHome#1452]
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

How to create unblock access rule only for a domain that blocked by CNAME or IP in response? i mean without letting any other domain to use that CNAME or IP

**Comment by ameshkov** [comment]
Simply do something like this: `@@||example.org^` where `example.org` is the domain that you want to unblock

**Comment by eoopx** [comment]
this site `https://getfider.com` uses `cdnjs.cloudflare.com` so how to create unblock rule only belong to that domain without letting for others?

(not about 'blocked by CNAME or IP in response')

**Comment by ameshkov** [comment]
`@@||getfider.com^`

**Comment by eoopx** [comment]
No. `getfider.com` is not blocked and no relation belong to that site hosting but `cdnjs.cloudflare.com` use for that site.

You can enable 'cloudflare' in blocked services next visit to getfider.com and you'll see page broken so i ask how to unblock `cdnjs.cloudflare.com` only for that domain?

**Comment by ameshkov** [comment]
That's what I am talking about, if you add `@@||getfider.com^` rule, it will be unblocked.

**Comment by eoopx** [comment]
Doesn't work. did you test it?

**Comment by ameshkov** [comment]
@eoopx yeah, but I've been testing it with custom filtering rules, but not with "blocked services".

Here's an example:

1. Add `||api.facebook.com^`
2. `nslookup graph.facebook.com` will return `0.0.0.0` because it will be blocked by cname
3. Add `@@||graph.facebook.com^`
4. `nslookup graph.facebook.com` will start working properly

**Comment by ArchiveBase** [comment]
@ameshkov something misunderstand here.

`cdnjs.cloudflare.com` isn't a cname of `getfider.com`
Eg If data.org has embed video from youtube or some images from picscdn.org that already blocked so i dont think if possible to unblock such domains only for data.org.
