### ISSUE TITLE
Top Lists

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1454]
### Problem Description

I need a statistic about how many rules be used in lists.

Seems like:
![](https://user-images.githubusercontent.com/5698157/76117864-a1a29800-6027-11ea-9a6a-3fbcf28926dd.png)

Thanks.

**Comment by ArchiveBase** [comment]
@bestpika https://github.com/AdguardTeam/AdGuardHome/issues/580

**Comment by bestpika** [comment]
@ArchiveBase Thanks.

**Comment by ameshkov** [comment]
Closed as dup of #580
