### ISSUE TITLE
Custom rules don't work

### ISSUE THREAD

**Issue by lnc1995** [AdguardTeam/AdGuardHome#1455]
- [ √] I am running the latest version
- [ √] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

e.g.
tui56.com/ad/

it works on android APP,but doesn't work on router enviroment.
i'm using AdGuardHome_linux_amd64 v0.100.9.

**Comment by lnc1995** [comment]
I ’m  sure other rules are in effect, only my own rules don't work

**Comment by ArchiveBase** [comment]
Follow v0.103 milestone. It may take some time.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/391

**Comment by lnc1995** [comment]
> When add proxy support #391 you'll be able to apply cosmetic rules then follow v0.103 milestone. It may take some time.
Seems doesn't suit my situation.For now, ad blocking is already works.Just some my own rules don't work

**Comment by ArchiveBase** [comment]
`||.domain.com/ads`

Currently adguard home only capable to perform DNS-level blocking, means only domain names. so you have to wait for #391

**Comment by lnc1995** [comment]
> `||.domain.com/ads`
> 
> Currently adguard home only capable to perform DNS-level blocking, means only domain names. so you have to wait for #391

Thanks buddy.I understand what you mean.
