### ISSUE TITLE
Failed to query over https when there is a domain

### ISSUE THREAD

**Issue by uniartisan** [AdguardTeam/AdGuardHome#1456]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details
info :服务器 "https://dns.alidns.com/dns-query"：无法使用，请检查你输入的是否正确

Failed to query over https when there is a domain,however ,https://223.6.6.6/dns-query is ok
* **Version of AdGuard Home server:**
  *  v0.100.9
* **How did you setup DNS configuration:**
  *  https://dns.alidns.com/dns-query
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  * raspberry Pi latest

### Screenshots

![image](https://user-images.githubusercontent.com/31544054/76157244-1e756500-6141-11ea-89ff-bfcb397f4a07.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ArchiveBase** [comment]
@uniartisan That's not a adguard home issue 

Both regular and DOH AliDNS seems works fine.
- DOH - https://dns.alidns.com/dns-query 
- Regular - 223.5.5.5 223.6.6.6 

Do you use AliDNS for bootstrap servers as well? If then probably your ISP or network issue.

**Comment by uniartisan** [comment]
> @uniartisan That's not a adguard home issue
> 
> Both regular and DOH AliDNS seems works fine.
> 
> * DOH - https://dns.alidns.com/dns-query
> * Regular - 223.5.5.5 223.6.6.6
> 
> Do you use AliDNS for bootstrap servers as well? If then probably your ISP or network issue.

![image](https://user-images.githubusercontent.com/31544054/76158068-b462bd00-614c-11ea-9f3a-72d86b6be49d.png)
I use  AliDNS for bootstrap servers right now and it seems to be OK. Thank you !

**Comment by uniartisan** [comment]
> @uniartisan That's not a adguard home problem
> 
> Both regular and DOH AliDNS seems works fine.
> 
> * DOH - https://dns.alidns.com/dns-query
> * Regular - 223.5.5.5 223.6.6.6
> 
> Do you use above addresses for bootstrap servers as well? If then probably your network or ISP issue.

Thank you a lot, it succesfully solved my problem.
