### ISSUE TITLE
Cannot use another AGH (DoT)  as upstream DNS

### ISSUE THREAD

**Issue by i553041** [AdguardTeam/AdGuardHome#1457]
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✔] I am running the latest version
- [✔] I checked the documentation and found no answer
- [✔] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v.0.100.9
* **How did you setup DNS configuration:**
  *  Router
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3B+ & 4B 
* **Operating system and version:**
  * Ubuntu 19.10 

### Expected Behavior

I can use AGH DoT in other AGH upstream

### Actual Behavior

I have 2 Static IP，2 Servers (ubuntu 19.10)，RASPI 3B+ / 4B，2 AGH (difference host, 2 AGH settings almost the same，both v.0.100.9)

In Server A，AGH，upstream DNS，I only key in Server B AGH's DoH address https://www.xxxx.xxx/dns-query，it's ok，do not have any problems. (Server B upstream DNS already set to use cloudflare)

In Server A，AGH，upstream DNS，I also only key in Server B AGH's DoT address，it fail，click "Test upstream“，it show：Server "tls://www.xxxx.xxx": could not be used, please check that you've written it correctly

I already reverse the Server A/B to test，problem still exist.

I confirm my Server A & B，port 853 is open and AGH already listen.

use cloudflare DoT in upstream DNS，it works 

I don't know it is a bug or not，please help to fix.

### Screenshots

<details><summary>Screenshot:<
<img width="364" alt="螢幕截圖 2020-03-08 下午10 05 15" src="https://user-images.githubusercontent.com/53026952/76164423-c31b9500-6189-11ea-92da-257869a3d0fa.png">
/summary>

</details>

**Comment by ArchiveBase** [comment]
I guess you use tls://1.1.1.1 for upstream right? however when use as tls://dns.adguard.com then bootstrap must be eg: 176.103.130.130:53 or other provider address but you cannot use 853 here. 
  Is that the problem?

**Comment by i553041** [comment]
> I assume you use tls://1.1.1.1 for upstream however when use as tls://dns.adguard.com then bootstrap must be eg: 176.103.130.130:53 or other provider address but you cannot use 853 here.
>   Is that the problem?

excuse me,I say it again,I have 2 servers,2 AGH,I use tls://b.myserver.com set it in my server A AGH upstream,I have tried tls://b.myserver.com or tls://b.myserver.com:853,it's not work,and I confirm my 853 port is open and AGH already LISTEN.but if I use DoH in upstream,http://b.myserver.com/dns-query,it don't have any problem.

A / B server reverse the DoT setting, it's the same

if bootstrap must be 176.103.130.130:53,then why my DoH don't have the same problem?DoH use 443 right?

I don't think it's the bootstrap problem.

**Comment by ArchiveBase** [comment]
Sorry, i misunderstood your question. (recently noticed as you were using adguard DNS)
I think that might be your DNS server(b.myserver.com) misconfiguration but you can open common DNS ports and test to troubleshoot this issue from client end.

**Comment by ameshkov** [comment]
I could not reproduce this issue.

I guess we need to see AdGuard Home verbose-level logs to figure out what's the problem.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by i553041** [comment]
> I could not reproduce this issue.
> 
> I guess we need to see AdGuard Home verbose-level logs to figure out what's the problem.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

Thanks for reply.

That's what I do after I re-enabled the log:

1.)delete the log and restart AGH in both server A & B,let AGH generate a clean log

2.)In server A AGH upstream,I key my server B AGH TLS address,tls://b.myserevr.com

3.)click server A AGH "Test upstream" and wait for the redbox show the error

4.)cp the AGH log to /tmp in both server A & B

I can't paste the full log here,it show:

You can't comment at this time — your comment is too long (maximum is 65536 characters).

Please use URL to see my log,

Here is Server A AGH log：

https://www.i553041.ml/rpi3b.txt

Here is Server B AGH log：

https://www1.i553041.ml/rpi4.txt

**Comment by ameshkov** [comment]
@i553041 well, there seems to be a problem with connectivity:
```
2020/03/09 21:59:02 9662#399 [info] couldn't communicate with DNS server tls://agh.i553041.ml: Failed to get a connection from TLSPool to agh.i553041.ml:853, cause: Failed to connect to agh.i553041.ml, cause: synthetic.wrap: all dialers failed to initialize connection: , cause: dial tcp 104.31.90.126:853: i/o timeout (hidden: dial tcp 104.31.91.126:853: i/o timeout, dial tcp [2606:4700:3030::681f:5a7e]:853: connect: network is unreachable, dial tcp [2606:4700:3030::681f:5b7e]:853: connect: network is unreachable)
```

**Comment by i553041** [comment]
> @i553041 well, there seems to be a problem with connectivity:
> 
> ```
> 2020/03/09 21:59:02 9662#399 [info] couldn't communicate with DNS server tls://agh.i553041.ml: Failed to get a connection from TLSPool to agh.i553041.ml:853, cause: Failed to connect to agh.i553041.ml, cause: synthetic.wrap: all dialers failed to initialize connection: , cause: dial tcp 104.31.90.126:853: i/o timeout (hidden: dial tcp 104.31.91.126:853: i/o timeout, dial tcp [2606:4700:3030::681f:5a7e]:853: connect: network is unreachable, dial tcp [2606:4700:3030::681f:5b7e]:853: connect: network is unreachable)
> ```
> 
> Check that the port is allowed in iptables on your server.

I didn't use iptables, because my network is behind my router,I use router's port forward and I confirm my router already set the correct port forward to my Pi, let me describe my network.

Server A， Static IP 183.xx.xx.xx，Airport Extreme (confirmed set Port forward 853 to Pi），Raspberry 3B+，AGH v0.100.9

Server B，Static IP 138.xx.xx.xx，TP-Link Router  (confirmed set Port forward 853 to Pi），Raspberry 4B，AGH v0.100.9

Server A，Pi 3B+ set Server B DoT in upstream fail.

reverse the test

Server B，Pi 4B set Server A DoT in upstream also fail.

That's so strange，I go to some free port scan website to test my port，my 183 / 138 IP，the test result port 853 is open.

<img width="653" alt="螢幕截圖 2020-03-10 上午12 14 25" src="https://user-images.githubusercontent.com/53026952/76234290-7a84da00-6264-11ea-855e-eb2dd2b39aa8.png">

<img width="613" alt="螢幕截圖 2020-03-10 上午12 13 51" src="https://user-images.githubusercontent.com/53026952/76234308-840e4200-6264-11ea-8172-4083029c68a2.png">

2 ips，2 routers，2 Pi，2 AGH，2 ports 853 confirm opened，but use other sides DoT in upstream it's not work，not a bug？

I can use DoH in both sides without any problem.

yes,I can use DoH, just curious why I use other server AGH's DoT I got this problem.

**Comment by i553041** [comment]
@ameshkov 

I suddenly remembered my server 2 agh hosts are using cloudflare CDN，when I turn off the CDN，everything fine,tls works again,thank you for your kindly help.

**Comment by ameshkov** [comment]
Yeah, that explains everything:)
