### ISSUE TITLE
Assigning tags to clients in AdGuardHome UI

### ISSUE THREAD

**Issue by truthsword** [AdguardTeam/AdGuardHome#1461]
I'm running the "latest" AdguardHome version on Docker.

When setting manual filters I read this...

> **ctag**
> $ctag modifier allows to block domains only for specific types of DNS clients. _You can assign tags to clients in AdGuardHome UI_. In the future we plan to assign tags automatically by analyzing the behaviour of each client.

I've gone over the settings pages/tabs several times, and cannot locate where in the AdGuardHome UI I can set tags such as "device_tv". 

Is this feature implemented? Please advise. Thank you.

**Comment by ArchiveBase** [comment]
> Is this feature implemented? Please advise. Thank you.

Yes. #1081 but it's not released yet then try beta version https://hub.docker.com/r/adguard/adguardhome/tags

If you consider that feature insufficient then upvote https://github.com/AdguardTeam/AdGuardHome/issues/435 and add a comment about why is it important
