### ISSUE TITLE
Memory allocations on enabling/disabling large filter lists

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1463]
It seems that we're allocating too much memory when filter lists are enabled, disabled, or updated.

The problem is that `golang` does not "like" to free memory so we end up with high RSS. Ideally, we'd better avoid allocations whenever it's possible.

**Comment by szolin** [comment]
Maybe it's time for us to use `Last-Modified` HTTP header so we won't download any data unless the filter has been changed.
