### ISSUE TITLE
OpenWrt: Top Clients names disappear

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#1465]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.9-139-gb600 (including recent stable release)
* **How did you setup DNS configuration:**
  * AGH as DNS and DHCP (filtering devices via MAC addresses)
* **If it's a router or IoT, please write device model:**
  * Linksys WRT3200ACM (ARMv7)
* **Operating system and version:**
  * OpenWrt 19.07.2

### Expected Behavior

I would expect that the Client device names would remain there in the Top Clients section of the Dashboard next to their IP addresses.

### Actual Behavior

Once the Client devices leave the network (or short time after), the Client names disappear from the Top Clients section of the Dashboard. The IP addresses and statistics remain which is good. Once the client reconnects to the network, the client device names return to the Top Clients section and the names, IP addresses and statistics remain consistent.

So it is just the client names that disappear when clients leave the network and reappear when they rejoin the network.

### Screenshots

<details><summary>Screenshot:</summary>
![AGH-TopClients](https://user-images.githubusercontent.com/26308319/76530169-bb8a1380-6449-11ea-9d6d-c5cd14ccdd8c.png)

The devices at the top are still connected to the network at the time of screenshot. The two devices at the bottom have left the network and their names disappear.

</details>

### Additional Information

I have the devices configured in the Clients section for filtering via MAC addresses specifically. So the Top Clients section of Dashboard is pulling the client device names from the configured Clients section.

I don't know if this problem is related to AGH's built in DHCP server, AGH Client issue or potentially conflict between AGH and OpenWrt.

**Comment by ameshkov** [comment]
Currently, it gets the client names from the DHCP server in real-time so if there's no client with this IP, it won't print any name.

The question is should we persist the client information when there's no more active lease

**Comment by WildByDesign** [comment]
Thank you, that helps me understand the situation better. This is only minor and therefore no urgency. 

At the moment, I don't know whether or not it would be good to persist with that information on disconnected clients or not. Realistically, it is only a minor visual annoyance.
