### ISSUE TITLE
AdGuardHome Cannot Block Youtube Ads

### ISSUE THREAD

**Issue by qy2009** [AdguardTeam/AdGuardHome#1466]
### Prerequisites

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.100.9
* **How did you setup DNS configuration:**
  * use port 53 to replace dnsmasq
* **If it's a router or IoT, please write device model:**
  * OpenWRT
* **Operating system and version:**
  * MacOS

### Expected Behavior
Can block youtube ads

### Actual Behavior
Cannot block youtube ads

### Additional Information
From the log, I can see that AdGuardHome is running and actively blocking some sites.

Thanks!

**Comment by ameshkov** [comment]
Unfortunately, Youtube ads cannot be blocked on the DNS-level
