### ISSUE TITLE
Menu sidebar cannot auto close on query log page

### ISSUE THREAD

**Issue by OMICRON3069** [AdguardTeam/AdGuardHome#1467]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * Latest commit, https://github.com/AdguardTeam/AdGuardHome/commit/b600d7b09d3f11b9f1635af67e0e7388cf62189c
* **How did you setup DNS configuration:**
  * AMD64, Arch Linux/Debian9 with systemd

### Expected Behavior
Open webui with mobile device, then navigate to query log page, side bar should close after I click "query Log".

### Actual Behavior
Side bar still persist after open query log page, I need to manual refresh to see query log

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_2020-03-13-10-50-26](https://user-images.githubusercontent.com/17488410/76585128-931d1a80-6518-11ea-98ff-d6aaa367faea.png)

</details>

### Additional Information
I tested with different Linux machine & mobile devices, all has same problem. Other pages works fine.

**Comment by ArchiveBase** [comment]
Fixed https://github.com/AdguardTeam/AdGuardHome/issues/1318

**Comment by ameshkov** [comment]
Hm, a regression? @IldarKamalov plz take a look
