### ISSUE TITLE
"Blocked domains" in the DNS access settings should accept wildcards

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1469]
Currently, it understands only exact domain names. However, those who abuse public DNS servers often use random subdomain names (for instance, `03131653dot27dot91dot239dot27dot199q1w2e3rty.pku.edu.cn`).

1. "Blocked domains" should accept wildcards
2. Change the help text: `Don't confuse this with filters. AdGuard Home will drop DNS queries with these domains in query's question.`. Add `You can specify exact domain names or wildcards here, i.e. example.org or *.example.org.`.

**Comment by ameshkov** [comment]
@szolin quick update, it would be even better if we support urlfilter matching syntax here as well.

**Comment by WildByDesign** [comment]
> quick update, it would be even better if we support urlfilter matching syntax here as well.

Assuming that you are referring to this (https://github.com/AdguardTeam/urlfilter), that would be incredible for AdGaurd Home. 

This AdGuard Home project is turning out incredible and the pace of development and bug fixes is fantastic. Your dev team's interaction with the open source community in particular is a wonderful thing and will help continue to make your software grow and shine.

By the way, I vaguely recall having a brief conversation with you on a security forum something like 7-10 years ago where I was telling you that it would be amazing to have an adblocking device or some sort based on OpenWrt/dnsmasq (at the time of suggesting). At the time, I believe you said it would be a great thing but rather a niche kind of tool. This is like a dream come true now. Cheers for that! :)

**Comment by ameshkov** [comment]
> 7-10 years ago

I feel so old now :) But yeah, I recall something like that as well.
