### ISSUE TITLE
May AdGuardHome work with Splunk??

### ISSUE THREAD

**Issue by kenkilaw** [AdguardTeam/AdGuardHome#1473]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version

### Problem Description

May AdGuardHome work with Splunk??
says export the log to Splunk for visualize e.g Query Log,Dashboard informations

**Comment by copacetic82** [comment]
I run AGH in a CentOS VM, installed splunk forwarder, and set it to monitor the querylog.json file. Works like a charm.
