### ISSUE TITLE
About "Added a setting to block all AAAA (ipv6) records" Issue

### ISSUE THREAD

**Issue by junxy** [AdguardTeam/AdGuardHome#1474]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

- Turn on "Added a setting to block AAAA (ipv6) records: #473", causing DNS rewrites to not support AAAA records
- I have a problem and it's similar to #473. Disable some domain name AAAA records, not all (disable all, similar effects can be achieved through router or interface settings 😂)

### Proposed Solution

- Fix this: Turn on "Added a setting to block AAAA (ipv6) records: #473", causing DNS rewrites to not support AAAA records. (DNS rewrites should not be affected by this setting?)
- In /etc/hosts rules or DNS rewrites Provide options: `ipv4 only`、`ipv6 only`、`both` (default, keep current)
  - I understand the destructive changes(https://github.com/AdguardTeam/AdGuardHome/commit/140d5553e787b5f4143fd830520fb850ed315e65) now are to avoid writing too much configuration
  - Before 1-2 versions, I think these functions are very useful to use(Is a features, for me😂): 
    - /etc/hosts rules:  `:: example.com`, `dig a example.com` -> upstream record ;  `dig aaaa example.com` -> :: 
    - DNS rewrites: if there's an AAAA rewrite rule, but no A rule, the response to A request use a upstream record. vice versa A -> AAAA 

### Alternatives Considered

- A too complicated solution is not good. If there is a configuration switch, you can keep the previous rules. Although it may not be elegant enough. But it can solve the problem

### Additional Information

- Hope to express my meaning clearly, please let me know if there is something unclear. Thanks
- My English is not very good, above translated using Google

**Comment by szolin** [comment]
Can you describe your problem step by step?
I understand that you have "Disable IPv6" setting "on".
But I don't understand what is the problem now.

**Comment by junxy** [comment]
@szolin I hope to use IPv6 selectively. Not only disable all IPv6.  Can control some domain names can resolve IPv6 , some domain names do not resolve IPv6.

- Can be solved initially by Adguard Hosts syntax. Like this `:: example.com`,result: query example.com AAAA record to :: , query example.com A record will query from upstream.  But this commit changed this rule #1328 8d2a9ce923eae4673a74f4c4a7e1d9ef840f04d2  (So I think there is an option here, Because both cases exist) 
- dns rewrites has the same problem. This commit(140d5553e787b5f4143fd830520fb850ed315e65 ) should provide an option instead of handling it by default. And if you have "Disable IPv6" setting "on", dns rewrites setting AAAA records will not work.

**Comment by ameshkov** [comment]
@junxy I understand what you want "technically", but could you please explain what is the use case for this? I don't understand what you are trying to achieve.

**Comment by junxy** [comment]
@ameshkov Thanks. Some websites support IPv4 and IPv6… 
- In some cases it is best to use IPv4(in my environment), such as www.netflix.com. In this case, it can be solved by disable ipv6. 
- In some cases it is best to use IPv6, such as iptv.pdsu.edu.cn. This site only provides access to IPv6.  It needs to be compatible with the previous rules. The current method is to modify `/etc/hosts` on the PC. Mobile devices that cannot modify `/etc/hosts` require additional methods. In addition, I also sometimes want to explore some IPv6 uses. 
- With the new version of AdGuardHome, Maintenance costs are now much higher. Other solutions may be needed if these requirements do not meet AdGuardHome's product positioning(Or modify and compile a version yourself). I can understand these (It may still be a niche demand, and IPv6 networks are not popular enough)

**Comment by ameshkov** [comment]
@junxy have you tried "fastest IP address" from the newest version of AGH? Does it solve your issue?

**Comment by junxy** [comment]
> @junxy have you tried "fastest IP address" from the newest version of AGH? Does it solve your issue?

Nice features, I'll go try it out. Seems to solve most problems. thx 👍

**Comment by ameshkov** [comment]
Great! I'll close this feature request for now, I hope "fastest IP" address is enough.
