### ISSUE TITLE
Some default filter tips and feature request about log page

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1475]
I noticed [nextDNS](https://nextdns.io) has already listed some good filter sources even some localized filter, need to create a configuration to view those filter, which in "Privacy" >"Add a blocklist", may those filter may help AGH become better!

And next, FEATURE REQUEST which enlightened from nextDNS dashboard too:
If we use multi-filter in AGH, it must exist that A domain has been listed in not only one filter, and in nextDNS dashboard, users can see which filter list this domain(see below screenshot). I think this feature totally could be used by AGH to make convenient to some guys who want to tuning they configuration/filter.
![image](https://user-images.githubusercontent.com/22477230/76682400-df5e7c80-6636-11ea-9aa2-2741e3b2a63b.png)

**Comment by ameshkov** [comment]
There's a problem with this feature request - it would require us to use all the duplicates from all the filtering lists, and this would be really bad for performance and resources usage.
