### ISSUE TITLE
Custom Filtering Rules No Longer Returns Expected A Record

### ISSUE THREAD

**Issue by SlothCroissant** [AdguardTeam/AdGuardHome#1477]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * See Below
* **How did you setup DNS configuration:**
  * Installed on Raspberry Pi 3b+ devices
* **Operating system and version:**
  * Raspbian GNU/Linux 9.8 (stretch)

### Expected Behavior
When I `dig` an internal DNS name ("dns01", in this case"), AGH returns the proper IP.

### Actual Behavior
When I `dig` an internal DNS name ("dns01", in this case"), AGH returns 0.0.0.0 as a blocked DNS record.

### Details

On two of my AGH servers, I have a custom filtering rule setup for an internal DNS name:

`10.1.1.2        dns01`

In my AdGuardHome.yaml, the rule looks like this:

```
user_rules:
- 10.1.1.2        dns01
```

When I dig the record against AGH running 10.100.9, I get the proper response:

```
user@laptop:~$ dig dns01 @10.1.1.2

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> dns01 @10.1.1.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10722
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns01.				IN	A

;; ANSWER SECTION:
dns01.			10	IN	A	10.1.1.2

;; Query time: 3 msec
;; SERVER: 10.1.1.2#53(10.1.1.2)
;; WHEN: Sat Mar 14 13:51:32 CDT 2020
;; MSG SIZE  rcvd: 39
```

However when I `dig` against an AGH server running 0.101.0, I get a 0.0.0.0 response:

```
user@laptop:~$ dig dns01 @10.1.1.4

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> dns01 @10.1.1.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27021
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns01.				IN	A

;; ANSWER SECTION:
dns01.			10	IN	A	0.0.0.0

;; Query time: 3 msec
;; SERVER: 10.1.1.4#53(10.1.1.4)
;; WHEN: Sat Mar 14 13:41:13 CDT 2020
;; MSG SIZE  rcvd: 39
```

AGH running 0.100.9 shows the query in query logs returning 10.1.1.2 (`Filtered by BlackList A: 10.1.1.2 (ttl=10)`, and the following as to "why":
```
Rule: 10.1.1.2 dns01
List: Custom filtering rules
```

AGH running 0.101.0 shows the query in query logs returning 0.0.0.0 (`Filtered by Custom filtering rules A: 0.0.0.0 (ttl=10)`, and the following as to "why":
```
Rule: 10.1.1.2 dns01
List: Custom filtering rules
```

Any thoughts as to why this behavior changed, and is it expected? If expected, how does one now do internal DNS resolution in AGH? I checked DNS Rewrites, but that seems to expect a TLD, etc - I can't just do `dns01`, I'd have to do `dns01.lan` or something similar. At this point, no devices in my network have TLDs like this.

**Comment by ameshkov** [comment]
It can be configured in Settings -> DNS.

By default, we use "null IP" for blocking stuff, but you can configure whichever mode you like more.

Also, I just realized that the naming is not okay. "Default" mode is not actually default anymore and has to be renamed:)

**Comment by ameshkov** [comment]
Ok, it appears "default" is the Default so I am not fully sure why you have this, could you please what blocking mode is enabled in your settings?

**Comment by SlothCroissant** [comment]
Let me clarify - I've got my blocking mode set to "Null IP" - haven't ever changed that, and it works fine for records that are truly blocked. This is not an issue whatsoever.

My problem in this case however - I use custom filters to set my internal DNS names for my devices on my network, so I can ping `dns01` instead of having to use `10.1.1.2` within my LAN. 

Per the instruction on the custom filtering tab, this is how this can work:

    3. 127.0.0.1 example.org – AdGuard Home will now return 127.0.0.1 address for the example.org domain (but not its subdomains).

So I set `10.1.1.2 dns01`

This works fine in 0.100.9, but **not** in 0.101.0 (see my previous `dig` queries) with the same exact config. Did something change in the latest release regarding this behavior?

**Comment by ameshkov** [comment]
Got it, this will work that way only if you use the "Default" mode.

Alternatively, you can use DNS rewrites.

> This works fine in 0.100.9, but not in 0.101.0

This was actually a bug of 0.100.9 -- null IP wasn't working properly.

**Comment by SlothCroissant** [comment]
This is now working, using the "Default" option. Note that in 0.100.9, "Default" wasn't an option for me in the UI:

**Comment by ameshkov** [comment]
Yeah, something was off with the blocking modes in v0.100.x
