### ISSUE TITLE
Add the ability to resolve hostnames from /etc/hosts - like hosts files

### ISSUE THREAD

**Issue by marcov** [AdguardTeam/AdGuardHome#1478]
When using AGH on a home router, it would be really useful to resolve the hostnames of the devices in the LAN.

OpenWrt based routers automatically generate a hosts file in ~~`/tmp/hosts/hosts.auto`~~ `/tmp/hosts/dhcp.cfg01411c`, using both static hostname provided by the user, and hostname gathered with DHCP requests.
However a.t.m. hostnames in this file cannot be resolved by AGH, limiting users ability to interact with other devices in the network without using IP addresses. 

### Proposed Solution
Resolve hostname from a user-specified set of hosts files.

### Alternatives Considered
Have a well-known set of hosts file paths hardcoded, or editable in the yaml config file.

**Comment by ameshkov** [comment]
So would you like us to do all three?

1. `/etc/hosts`
2. `/tmp/hosts/hosts.auto`
3. DHCP (in the case if AdGuard's DHCP server is enabled)

**Comment by ameshkov** [comment]
@szolin additionally to answering A/AAAA, we should also be able to handle PTR requests, check the relevant discussion here: https://github.com/AdguardTeam/AdGuardHome/issues/1458

**Comment by szolin** [comment]
There's no `/tmp/hosts/hosts.auto` on our openwrt device but `/tmp/hosts/dhcp.cfg01411c` instead.

**Comment by marcov** [comment]
@szolin, you are right, `/tmp/hosts/dhcp.cfg01411c` is the right path (`/tmp/hosts/hosts.auto` is a custom mod I did locally).

@ameshkov that would be awesome. 
Even better if for 1. and 2. you could let the user specify an arbitrary list of paths.

**Comment by ameshkov** [comment]
@szolin it seems you forgot about handling PTR
