### ISSUE TITLE
The same rules don't apply on adguard home

### ISSUE THREAD

**Issue by a1797831629** [AdguardTeam/AdGuardHome#1480]
Same rules why can I filter ads on adguard for andriod but if I move these rules to adguard home, I can't filter ads. Android filters ads by VPN, and PC utility DNS filters ads, because DNS can't completely filter ads?

**Comment by ArchiveBase** [comment]
See https://github.com/AdguardTeam/AdGuardHome/issues/1455

**Comment by ameshkov** [comment]
Yeah, DNS-level filtering is rather limited compared to proxy
