### ISSUE TITLE
No link-local ipv6 interfaces in the "Setup guide" tab

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1481]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
0.101.0
* **How did you setup DNS configuration:**
VPS
* **Operating system and version:**
Debian 9

### Expected Behavior
Before the last release, four interfaces were specified in the "Setup guide" tab, two of which are ipv6.

### Actual Behavior
There are currently only two ipv4 interfaces. However, the ipv6 connection works fine as before.

### Screenshots
I can send screenshots, configuration file and ifconfig output to devteam@adguard.com or telegram if necessary.

### Additional Information
ipv6 is **NOT** disabled in DNS settings. Disabling or enabling this option does not affect on the "Setup guide" tab. Domains are resolved correctly in ipv6 - no problem here.

**Comment by ameshkov** [comment]
Are you sure these IPv6 interfaces aren't link-local?

**Comment by ammnt** [comment]
> Are you sure these IPv6 interfaces aren't link-local?

Sure. I used them earlier and I continue to use them now for connection from external networks.

**Comment by ameshkov** [comment]
Hm, well, we deliberately removed them, but maybe you're right and we should list them as well.

@szolin let's just sort the list of network interfaces so that the link-local addresses were the last.

**Comment by ammnt** [comment]
> Hm, well, we deliberately removed them, but maybe you're right and we should list them as well.

You should definitely list them, as when you configure resolvers such as Stubby or Unbound, they specify them as separate DNS servers. For example:
- Unbound:
`config zone`
	`option enabled '1'`
	`option zone_type 'forward_zone'`
	`option tls_upstream '1'`
	`option tls_index 'dns.google'`
	`list zone_name '.'`
	`list server '8.8.8.8'`
	`list server '8.8.4.4'`
	`list server '2001:4860:4860::8888'`
	`list server '2001:4860:4860::8844'`
- Stubby:
`- address_data: 176.103.130.130`
`- tls_auth_name: "dns.adguard.com"`
`- address_data: 176.103.130.131`
`- tls_auth_name: "dns.adguard.com"`
` - address_data: 2a00:5a60::ad1:0ff`
` - tls_auth_name: "dns.adguard.com"`
`- address_data: 2a00:5a60::ad2:0ff`
` - tls_auth_name: "dns.adguard.com"`

Thank you!
