### ISSUE TITLE
"Default" blocking mode is not default anymore and has to be renamed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1482]
This is quite weird:

![](https://uploads.adguard.com/up04_e3809_AdGuard_Home.png)

Let's find a better name for it.

**Comment by szolin** [comment]
This setting is still "default" when first installing AGH:
https://github.com/AdguardTeam/AdGuardHome/blob/480c6ac753fc7e3faae44275ce63f2fc448e0345/home/config.go#L153

**Comment by ameshkov** [comment]
Hm, now I am confused, where [this](https://github.com/AdguardTeam/AdGuardHome/issues/1477) came from then?

**Comment by szolin** [comment]
When installing v101 - this setting is "default" as it's supposed to be.
I think the configuration setting on that user's server with v101 is "null_ip" because it was set by user.

**Comment by ameshkov** [comment]
Yep, hopefully you're right

**Comment by SlothCroissant** [comment]
FYI @szolin  and @ameshkov , my 100.9 install doesn't have "Default" as an option:

![image](https://user-images.githubusercontent.com/5846854/76761121-d5369e00-675c-11ea-90ad-67b30ffe13ae.png)

When setting in the yaml file however, it works.
