### ISSUE TITLE
Wiki: Add FAQ

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1483]
Let's make a wiki page where we answer simple but popular questions

**Comment by vbagirov** [comment]
To kick things off:
"After installing AG Home on a router, how to change dashboard interface's address?"

**Comment by ameshkov** [comment]
Youtube

**Comment by szolin** [comment]
> Q: After installing AG Home, how to change dashboard interface's address?

A:

1. Open `AdGuardHome.yam` in the text editor
2. Modify `bind_host:` value to set a new network interface, e.g.:

	* 0.0.0.0: listen on all network interfaces
	* 127.0.0.1: listen on localhost only

3. Modify `bind_port:` value to set a new port
4. Restart AG Home:

	`./AdGuardHome -s restart`

**Comment by szolin** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ
