### ISSUE TITLE
Import custom filtering rules to blocklists or whitelists

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#1489]
Custom filtering rules for temporally purposes then this's an option for import selected rules to permanent local lists easily #817 also may related https://github.com/AdguardTeam/AdGuardHome/issues/970

![Screenshot_1](https://user-images.githubusercontent.com/46082456/76971316-9fadd280-695f-11ea-811c-6e5d44dc598b.png)

Import Steps
- highlight necessary rules
- click import to local lists
- select blocklists or whitelists
- select existing list to import

**Comment by Archive5** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1734

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1449

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1071

**Comment by ameshkov** [comment]
Actually, it's now possible to add local lists when you add filter lists so we can consider this done
