### ISSUE TITLE
support slash notation in rules

### ISSUE THREAD

**Issue by HopHop20** [AdguardTeam/AdGuardHome#1491]
Currently it's possible to prevent a domain from resolving if it resolves to certain ip address. For example a rule like `||8.8.8.8^$important` will deny access to the domain `dns.google`

It's not currently possible to block a larger swath of IPs such as `123.456.789.0/24` in one rule.

Of course we could create a rule for each individual IP in the /24 but that seems incredibly ineffecient and time consuming. It only gets worse when trying to block a /16...

Solution
Allow rules that support slash notation for example `||123.456.789.0/24^$important`

**Comment by ameshkov** [comment]
`123.456.789.0/24` would be `||123.456.789.` :)

**Comment by HopHop20** [comment]
But wouldn't that match 123.456.789.google.com

**Comment by ameshkov** [comment]
If you want to avoid this kind of false-positives (which I doubt will ever happen), there's an option to use regexes:

`/123.456.789.[0-9]{1,3}/`
