### ISSUE TITLE
'Check the filtering' doesn't show all source lists

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#1493]
- Display all subscription and local filter lists contain checked domain
- Display 'remove' or 'remove duplicates' buttons next to each filter lists name 
(excluding the first list and must be local lists)

Related question, https://github.com/AdguardTeam/AdGuardHome/issues/1475#issuecomment-599456004 (agree with the answer but this doesn't affect for performance)

**Comment by ameshkov** [comment]
@ArchiveBase the thing is that it uses the compiled filtering engine where all duplicates were already eliminated

**Comment by ArchiveBase** [comment]
I noticed recent feature requests then close this issue to avoid unwanted tasks,

- Display all subscription and local filter lists contain checked domain https://github.com/AdguardTeam/AdGuardHome/issues/1364

- Display 'remove' or 'remove duplicates' buttons next to each filter lists name
(excluding the first list and must be local lists) https://github.com/AdguardTeam/AdGuardHome/issues/1449
