### ISSUE TITLE
Adguard Home calling 1.1.1.1 for no reason

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#1496]
I'm runing Adguard home v0.101.0
My firewall is bloking DNS requests from Adguard Home to 1.1.1.1
I'm not using cloudflare DNS servers or have that IP configure anywhere, why this is happening?

![imagen](https://user-images.githubusercontent.com/17175395/77191175-d65c2800-6ada-11ea-9c07-349379cd4c2d.png)

![imagen](https://user-images.githubusercontent.com/17175395/77191297-07d4f380-6adb-11ea-9345-ead454b9c0c5.png)

**Comment by cloudz** [comment]
You don't have these listed in /etc/resolv.conf by any chance?

**Comment by lordraiden** [comment]
> 
> 
> You don't have these listed in /etc/resolv.conf by any chance?

I have a docker installation, where I can find that folder? in the OS where docker is installed? that OS has a different IP.

**Comment by ameshkov** [comment]
Tbh, I have no idea.

Is it possible to check what exact DNS queries are being sent there?

**Comment by lordraiden** [comment]
I found the problem, it was a misconfiguration of the host where I have the docker, sorry.
