### ISSUE TITLE
Query log update slow

### ISSUE THREAD

**Issue by sun5025** [AdguardTeam/AdGuardHome#1497]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by sun5025** [comment]
Query log update slow

**Comment by ameshkov** [comment]
Please explain in detail what exactly is wrong
