### ISSUE TITLE
DHCP IPv6

### ISSUE THREAD

**Issue by keshenmathura** [AdguardTeam/AdGuardHome#1500]
Hi all,

My router is giving out IPv6 addresses and thus also the IPv6 ISP DNS server address. I don't see IPv6 settings in the DHCP settings page of AGH. Is this in the works or am I missing something?

Thanks!

Keshen

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * Adguard is DHCP server
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  * Raspbian Buster

**Comment by ArchiveBase** [comment]
#779

**Comment by ameshkov** [comment]
Yeah, AGH supports DHCPv4 only for now
