### ISSUE TITLE
[Feature Request] Add new labels

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#1501]
Add new labels like

device_server
os_docker (although is not an OS I think it fits)

By they way, what is the purpose of labels? I can't find anything in the wiki

**Comment by ameshkov** [comment]
It's used for `ctag`: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#-ctag

Ideally, we would like AGH to be able to automatically detect OS/device:
https://github.com/AdguardTeam/AdGuardHome/issues/1468

What for `os_docker`, I am not sure about it, it's basically the same as `os_linux`

**Comment by lordraiden** [comment]
ok, I undestand the use now.
Maybe app_docker but basically as you said is os_linux

**Comment by DandelionSprout** [comment]
I spotted this issue a bit late, but would it be possible to add something like `$ctag=mobiledata`, as a workaround for #1096 still being on hold?

So far I've reserved `user_regular` on my end for that purpose, but I presume that that was not the intention behind `user_regular`.
