### ISSUE TITLE
Openwrt stops working after a day

### ISSUE THREAD

**Issue by tingalvin** [AdguardTeam/AdGuardHome#1503]
AdGuard Home v0.101.0 MIPS
Running on this router
  GL.iNet AR750S OpenWrt 18.06.1 r7258-5eb055306f, latest stock router fw
Tech specs
 https://openwrt.org/toh/hwdata/gl.inet/gl.inet_gl-ar750s

This is my second install after removing everything and setting up as new again, both times AGH stops working after about a day. not too familiar with Openwrt, one thing is out of memory, but system overview says I still have plenty.
Mar 23 19:40:06 2020 daemon.err AdGuardHome[7587]: fatal error: runtime: out of memory
[System status](https://imgur.com/a/xXMTyZz) 

full log here.
https://pastebin.com/M52G37Br

**Comment by ameshkov** [comment]
Well, there's definitely is an issue with memory usage, AGH loads the whole filter list in the memory when the update is performed, and this might be what's causing the issue.

We've resolved it in https://github.com/AdguardTeam/AdGuardHome/issues/1463 but have not yet published the beta version.

**Comment by tingalvin** [comment]
noted. will try again when an update is published.

**Comment by ameshkov** [comment]
@tingalvin the temporary solution, for now, is just to stick to smaller lists. I see that you're using quite large ones.

**Comment by outcastveron** [comment]
@ameshkov i have the same issue,just removed some lists and allocated more memory(Openwrt running in Hyper-V). AGH eated almost 800M.

**Comment by ameshkov** [comment]
@outcastveron could you please try the latest beta version?

https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

**Comment by outcastveron** [comment]
@ameshkov OK, I will try later.
