### ISSUE TITLE
How do disable the dns cache

### ISSUE THREAD

**Issue by bzzjh** [AdguardTeam/AdGuardHome#1505]
I setup unbound as DNS cache for AdguardHome's upstream ,and I want to know how to disable dns cache on Adguardhome config file.

Thanks

log :
> 2020/03/24 08:58:53 [info] DNS cache is enabled

**Comment by ameshkov** [comment]
Just set the DNS cache size to 0 in `AdGuardHome.yaml`

Also, there is nothing wrong with having two caches :)
