### ISSUE TITLE
屏蔽

### ISSUE THREAD

**Issue by bianhua123** [AdguardTeam/AdGuardHome#1508]
屏蔽yotube后就一直屏蔽了，解封后也打不开YouTube视频，使用的是使用53端口替换dnsmasq模式
设备是筋斗云  固件是lean源码编译的openwrt   使用的ssr出国，而且cpu占用直接99%

**Comment by Zxilly** [comment]
可以的话用英文吧，这并不是一个中文社区

**Comment by ameshkov** [comment]
Well, I can try to apply my very limited Chinese

**Comment by ameshkov** [comment]
@bianhua123 
请解释我你怎么屏蔽YouTube？我需要看AdGuard Home设置。请显示截图。

**Comment by Zxilly** [comment]
> @bianhua123
> 请解释我你怎么屏蔽YouTube？我需要看AdGuard Home设置。请显示截图。

@ameshkov He means he block youtube and can not unblock it.
He runs AdGuard on OpenWRT,using ShadowsocksR as a transparent proxy.
The device he used is not widely selled.The chip should be Qualcomm IPQ40xx.
He lets the AdGuard running on port 53 and shutdown dnsmasq,which makes the AdGuard been the only DNS resolver.During this period,the CPU usage keeps 99%.

In fact,I can not understand how he operate 'block' either.

**Comment by Zxilly** [comment]
@ameshkov He has made 3 issue with no response...Maybe you can just close this issue.

**Comment by ameshkov** [comment]
Yeah, seems so:(
