### ISSUE TITLE
Only gateway IP shows top clients list, device specific profiles don't work

### ISSUE THREAD

**Issue by a-kempka** [AdguardTeam/AdGuardHome#1509]
The list of clients requesting DNS only shows the IP address of the gateway (192.168.178.1) instead of the client's IP addresses.

### Issue Details
* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * Gateway (UniFi USG) uses AGH as it's primary and secondary DNS
* **device model:**
  * Ubiquiti UniFi USG
* **Operating system and version:**
  * FreeNAS 11.3u1 (FreeBSD 11.3)

### Expected Behavior
For device specific profiles to work, the client's IP needs to be recognized individually (e.g. 192.168.178.123 making a DNS request). 

### Actual Behavior
All of the DNS requests are recognized under the gateway's IP. Thus clients cannot have specific profiles, e.g. disabling parental controls, as blocking for individual clients.

**Comment by mosjonathan** [comment]
In your Network config you need to set the ad guard ip instead of the usg.
If you check the ip config for a client you will see that the dns for the client is the usg ip

**Comment by ameshkov** [comment]
It seems that your devices proxies DNS queries to AdGuard Home and because of that, AGH simply cannot figure out the real client IP. Try following @mosjonathan's advice

**Comment by a-kempka** [comment]
> In your Network config you need to set the ad guard ip instead of the usg.
> If you check the ip config for a client you will see that the dns for the client is the usg ip

Thank you for your reply.
That works as a workaround, of course. However applying this to 50 devices is a major pain, and some of the devices cannot be set up. Strangely I didnt't have this problem with pi hole, which showed the individual clients despite them using the gateway from dhcp.

**Comment by mosjonathan** [comment]
For the following i’m asuming that you are using a cloudkey.

When you login to your cloudkey go to settings.
After that go to networks click in the little pencil behind the Network name you want to change.
There you will find the option DHCP Name Server it is set to automatic set this to manual and fill in the ip of your adguard instance.

Last thing to do is restart all your Network equipment so that it will get a new dhcp lease with the correct dns server

**Comment by a-kempka** [comment]
> For the following i’m asuming that you are using a cloudkey.
> 
> When you login to your cloudkey go to settings.
> After that go to networks click in the little pencil behind the Network name you want to change.
> There you will find the option DHCP Name Server it is set to automatic set this to manual and fill in the ip of your adguard instance.
> 
> Last thing to do is restart all your Network equipment so that it will get a new dhcp lease with the correct dns server

Thanks. This option works. However there is the drawback of having to configure each of the IPs and names again in AdGuard Home.
I've stumbled upon another solution:

1. Set the DNS server in the USG to your provider's or another upstream DNS (like google (8.8.8.8), cloudflare (1.1.1.1) etc.
2. Under Networks > LAN set the DHCP nameserver to manual, put in your AdGuard Home's IP.
3. Renew DHCP on the clients (ipconfig /renew on Windows)
4. "profit"/"great success" :)
Hope this helps
