### ISSUE TITLE
请问adguard home直接取代openwrt的dnsmasq和dhcp服务么

### ISSUE THREAD

**Issue by bianhua123** [AdguardTeam/AdGuardHome#1512]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
你能用adguardhome取代dnsmasq， 可是这是不容易。

看一下DHCP 设置页。
