### ISSUE TITLE
淘宝跳转到国际淘宝

### ISSUE THREAD

**Issue by MiracleLau** [AdguardTeam/AdGuardHome#1513]
请问为何使用后，访问淘宝会自动跳转到world.taobao.com，如果关闭dns，就不会出现这种情况

**Comment by ArchiveBase** [comment]
检查，如果这有帮助 https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains
(проверьте, помогает ли это https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains)

**Comment by ameshkov** [comment]
这取决于您的adguard设置。如果您用国际dns, 就会出现这种。

您能用中国dns。点击"设置"，点击“DNS 设置”，找“上游 DNS 服务器”。

**Comment by MiracleLau** [comment]
感谢各位
