### ISSUE TITLE
用戶名和密碼忘記了，給個機會重新注冊

### ISSUE THREAD

**Issue by ywdj** [AdguardTeam/AdGuardHome#1514]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by hezhijie0327** [comment]
参考
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset
