### ISSUE TITLE
[QUESTION] https for admin interface

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1515]
Дайте ссылку или объясните как включить https для web интерфейса в локальной сети. https://192.168.1.2 вместо http://192.168.1.2 . На том же серваке есть pixelsrv c https по ссылке на другой сетевухе  https://192.168.1.100

**Comment by ameshkov** [comment]
На локальном то зачем? Его все равно не видно нигде.

Кратко:

1. Сгенерировать свой самоподписанный корневой сертификат
2. Использовать его в pixelsrv
3. Установить сертификат из пункта 1 в доверенные корневые на всех устройствах, которые используют AGH
4. Сгенерировать доменный сертификат с прописанным в нем IP адресом
5. Использовать этот сертификат для настройки Encryption в AGH

Не заставляйте только вот каждый пункт расписывать, это на час.
