### ISSUE TITLE
Installation is blocked on OpenWRT

### ISSUE THREAD

**Issue by kstenerud** [AdguardTeam/AdGuardHome#1516]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * Router (default settings)
* **If it's a router or IoT, please write device model:**
  * Archer C7 v2 running openwrt
* **Operating system and version:**
  * OpenWRT 19.07.2

### Expected Behavior

Following https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started

I expect the steps to work

### Actual Behavior

I get blocked at step 2

### Screenshots
![Screenshot at 2020-03-26 11-26-47](https://user-images.githubusercontent.com/245857/77637910-aa1b2e00-6f56-11ea-9dd6-f6fe046c1d08.png)

### Additional Information

It's talking about a "Fix" button, which isn't present. There's no indication as to how to proceed. Clicking "Next" does nothing.

**Comment by ameshkov** [comment]
Well, this is definitely a bug.

The problem is that port 53 is occupied by your local `dnsmasq` instance.

You have two options:
1. Use a different port in AdGuard Home (it will be problematic to configure other devices to use it, though).
2. Disable dnsmasq and run AdGuard Home instead. In this case, you'll also need to run AGH DHCP server.
3. Change port number in the dnsmasq configuration.

**Comment by tingalvin** [comment]
expanding on your point 1,
you could use an alternative port, then in LuCi look for DHCP and DNS and set it to 127.0.0.1#port

that way your router will use AGH, hence all devices. however there will be no individual client identification and you will only see your router as the only client in AGH

**Comment by szolin** [comment]
What must we do on this task, apart from what we're planning to do in https://github.com/AdguardTeam/AdGuardHome/issues/1464 ?

**Comment by ameshkov** [comment]
@szolin well, at least we shouldn't show this "fix me" text. Ideally, we should provide a link to a Wiki page that explains options.

**Comment by youri--** [comment]
Just an added note. I've set AGH DNS to port 5353 and added this to OpenWRT's "Firewall - Custom Rules":

`# Redirect all DNS-queries to AdGuard Home DNS server
iptables -t nat -A PREROUTING -i br-lan -p udp --dport 53 -j DNAT --to 192.168.1.1:5353
iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 53 -j DNAT --to 192.168.1.1:5353`

So every device, even devices that don't respect DNS addresses provided via DHCP (looking at you, Chromecast), will now go through AGH.

**Comment by ArtemBaskal** [comment]
Fixed 89920bc518b6d8bcc7bf754b0b768ad3bf49de9b
