### ISSUE TITLE
rDNS queries every 5 seconds to resolve clients ip

### ISSUE THREAD

**Issue by cyruz-git** [AdguardTeam/AdGuardHome#1520]
Hello guys, running 0.101.0 on OpenWRT here.

I'm trying to configure AGH so that it can resolve my local devices ip addresses and populate the client list.

As of now I have been able to do it running dnsmasq as dhcp and dns listening on 5300 and setting the following upstreams on AGH:

[/lan/]127.0.0.1:5300
[/168.192.in-addr.arpa/]127.0.0.1:5300

Everything works but AGH starts a PTR query for every single device in my network every 5 seconds, spamming the query log with useless information.

I see that with #1478 AGH will populate the client list reading the `/tmp/hosts/dhcp.cfg01411c`. This is already great (and I will probably go this way when it will be released) but for anybody relying on the setup above I think that the PTR query timeout should be tuneable.

**Comment by ameshkov** [comment]
> Everything works but AGH starts a PTR query for every single device in my network every 5 seconds, spamming the query log with useless information.

That's weird, if it was successfully resolved, it should not be happening again.

Could you please record AGH log and share it with us?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
