### ISSUE TITLE
Improve logs page - clear input field when switching from/to logs page

### ISSUE THREAD

**Issue by mKoonrad** [AdguardTeam/AdGuardHome#1523]
### Problem Description
Every time when I move to logs page my earlier search data are filled. I need to remove text to perform another search.

### Proposed Solution

- [ ] Clear input field every time when user switch again to logs page
- [ ] Add small icon to remove filled text fields (like in many often used search fields)

**Comment by ArchiveBase** [comment]
> [ ] Add small icon to remove filled text fields (like in many often used search fields)

https://github.com/AdguardTeam/AdGuardHome/issues/481

**Comment by ameshkov** [comment]
This is a very simple issue we can fix separately
