### ISSUE TITLE
Allow loading certificate/private key from file

### ISSUE THREAD

**Issue by yegle** [AdguardTeam/AdGuardHome#1526]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Maybe I'm missing something but it looks like there's no way to load SSL certificate and private key from a file.
What I'm doing on my server is to renew the certificate from Let's Encrypt and write to a volume shared by multiple docker containers. Manually updating the certificate either via Web UI or via configuration file is PITA.

### Proposed Solution

Since I need to configure Adguard Home to use DoT, I need to programatically update the certificate, and allowing loading certificate and key from files is the easeist solution.

### Alternatives Considered

Add an API to update the key/certificate when certbot renewed the certificate?

**Comment by ameshkov** [comment]
> Maybe I'm missing something but it looks like there's no way to load SSL certificate and private key from a file.

Hm, actually there is:
https://uploads.adguard.com/up04_ui7ua_AdGuard_Home.png

Are you on the latest version of AGH?
