### ISSUE TITLE
What about resolv.conf?

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1533]
Hello,

as far as we know the contents of the **resolv.conf** file are static. Perhaps it makes sense to manage it after installing AGH? Does its contents affect something while the AGH is running?

Cheers!

**Comment by ameshkov** [comment]
Actually, it's not necessarily static.

> Does its contents affect something while the AGH is running?

As I recall, some internally used domain names may be resolved using `resolv.conf`.

At the same time, it's perfectly valid to edit `resolv.conf` and replace everything there with `127.0.0.1`.

**Comment by ammnt** [comment]
> Actually, it's not necessarily static.

In most cases by default, i suppose...

> At the same time, it's perfectly valid to edit `resolv.conf` and replace everything there with `127.0.0.1`.

May it make sense to automate this after the AGH installation is complete? I don 't know if that 's possible.

**Comment by ameshkov** [comment]
> In most cases by default, i suppose...

It's dynamic for every device that uses DHCP to get the IP address so not really most cases.

> May it make sense to automate this after the AGH installation is complete? I don 't know if that 's possible.

I am still not sure about that. There are a lot of people trying to run AGH on their home PC/Macs and this may be problematic for them.

**Comment by ammnt** [comment]
> I am still not sure about that. There are a lot of people trying to run AGH on their home PC/Macs and this may be problematic for them.

Okay, just think about it. I started to figure it out because some of my requests weren 't actually encrypted:
![2020-04-01_19-36-05](https://user-images.githubusercontent.com/45385632/78162815-1cf14100-7450-11ea-8a09-f3c50302b208.png)

**Comment by ameshkov** [comment]
Well, this one we can and should fix regardless of resolv.conf.

Any other example apart from whois DNS queries?

**Comment by ammnt** [comment]
> Well, this one we can and should fix regardless of resolv.conf.

Nice! 

> Any other example apart from whois DNS queries?

`whois.afrinic.net` and `whois.arin.net` too. I suspect all the root registries...

**Comment by ammnt** [comment]
> At the same time, it's perfectly valid to edit `resolv.conf` and replace everything there with `127.0.0.1`.

After that I have a **localhost.localdomain** in the logs.:
![image](https://user-images.githubusercontent.com/45385632/78270742-e7159080-7513-11ea-85a1-1b5a04aa7230.png)
But now all requests to the whois root servers is encrypted. Maybe you want to do something about it...

Thank you!

**Comment by ameshkov** [comment]
@ammnt well that's okay, this is AGH itself resolving that domain
