### ISSUE TITLE
Don't skip point-to-point interfaces

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1534]
### Prerequisites

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * VPS, OpenVZ
* **Operating system and version:**
  * Debian 9

### Actual Behavior
Last night I decided to install AGH on a new VPS based on Debian 9. I also ordered from ISP additional ipv4 and ipv6 addresses, that was adjusted by him automatically. During the installation, AGH suggested that I need go to 127.0.0.1:3000, but I successfully went to an 194.67.78.224:3000 and completed the installation. Unfortunately, I didn 't do a screenshot of it.

Everything is working properly at the moment. All the interface are listened. Filtration works fine. Two ipv4 addresses and two ipv6 addresses respond. But in the "Setup guide" section, I only see this:
https://yadi.sk/i/i-46AiBeH-lK9g

</details>

### Additional Information
I can send logs, YML-configuration file, ifconfig output, or the entire /etc/network/interfaces file if you need it. This problem may be related to this, but I 'm not sure:
https://github.com/AdguardTeam/AdGuardHome/issues/1481

**Comment by szolin** [comment]
What is the value of `bind_host` and `dns.bind_host` settings in your yaml file?
Can you make a screenshot of the IP addresses listed by AGH during installation?
Also, the IP addresses shown by `ifconfig` or `ip a` can help.

**Comment by ammnt** [comment]
> What is the value of `bind_host` and `dns.bind_host` settings in your yaml file?
> Also, the IP addresses shown by `ifconfig` or `ip a` can help.

Thanks for the answer! `bind_host` and `dns.bind_host`:  `0.0.0.0`

The `ifconfig` output:
https://yadi.sk/i/3TkRtIUyluK-Dg

> Can you make a screenshot of the IP addresses listed by AGH during installation?

During installation it was only 127.0.0.1. What other information can help solve this problem?

**Comment by szolin** [comment]
We skip point-to-point interfaces in our code - I don't know why we do this.
We should remove this check.
