### ISSUE TITLE
hpHosts is discontinued now

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1536]
Hello,

hpHosts is discontinued now:
https://hosts-file.net/ad_servers.txt
https://www.malwarebytes.com/browserguardad_servers.txt
https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/

I recommend you to replace it with something else in the next update.

Thank you.

**Comment by DandelionSprout** [comment]
Indeed this is now widely known in the adblocker community, e.g. https://github.com/uBlockOrigin/uBlock-issues/issues/971.

I'd say this could be the right time for the AdGuard team to make a decision(s) on #1325.

**Comment by ameshkov** [comment]
Merging into #1325 then
