### ISSUE TITLE
IP address domains currently aren't processed by AdGuard Home at all

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1537]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.101.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

After it was pointed out to me in the Slack listmaker group that `/^1\.1\..*/`-style IP address entries did not work in any other adblockers than AGH (as they didn't account for the presence of `https://` or `http://`, I came across an even bigger problem that was exclusive to AGH:

IP address domains, such as `https://1.1.1.1` and `https://157.245.249.110` (the latter of which is a mostly functional official mirror of invidio.us), currently aren't processed by AdGuard Home, which also means that their CNAME responses aren't processed either, meaning they can't be blocked under any circumstances in any way.

I'm sure many people's first reaction to this problem is "Wait a minute, m8. DNS servers aren't supposed to process IP addresses. They're meant to turn domains into IP addresses!". Normally they'd be right, but not when the entire goal of the DNS server (i.e. AdGuard Home) is to block any kind of domain that one would want to block.

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * (On the system:) Android 7.1.2

### Reproduce
1) Add some kind of entry to "Custom filtering rules" that is intended to block IP addresses. E.g. `||1.1.`. If you want to be really sure, you can also add entries like `|1.1.*^`, `/^1\.1\..*/`, and/or `/1\.1\..*/`.
2) Visit `https://1.1.1.1`.
3) See that the site remains unblocked.
4) Go to "Query log" in AGH.
5) See that there's no record or mention in the query log about the site having been accessed.

### Expected Behavior
IP addresses with corresponding block entries, are blocked when accessed through a browser as if it was a domain.

### Actual Behavior
IP addresses with corresponding block entries, are not blocked when accessed through a browser as if it was a domain.

### Screenshots
I don't think this issue could be feasibly explained through screenshots, unfortunately.

### Additional Information
Considering https://github.com/easylist/easylist/commit/37a4bf6045 was performed by Fanboy based solely on my advocacy, this problem could prove to give me egg on my face if it couldn't even be properly applied to the kind of domains that they were supposed to apply to in the first place, on the platform I gave as an example. Even more so after they turned out to be broken in browser-type adblockers like uBO as well.

Additionally, this problem would also make at least one of the new entries in #1519 non-functional until this is fixed.

**Comment by ArchiveBase** [comment]
#921

**Comment by ameshkov** [comment]
Well, unfortunately, this is simply impossible to do as long as we operate just as a DNS server.

It will only be possible when we finally implement the filtering proxy :(
