### ISSUE TITLE
Problem query table in General Statistics disappears

### ISSUE THREAD

**Issue by alberisca75** [AdguardTeam/AdGuardHome#1538]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ -] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot (23)](https://user-images.githubusercontent.com/13577530/78274751-f47d4b80-7510-11ea-82e3-d513b1475b35.png)
![Screenshot (22)](https://user-images.githubusercontent.com/13577530/78274754-f5ae7880-7510-11ea-8a0e-f9088bfdc7f5.png)
</details>

### Additional Information

With the Italian language, the ability to select a link on the query table in General Statistics disappears

**Comment by ArchiveBase** [comment]
Fixed in crowdin. @IldarKamalov ;)

**Comment by ArtemBaskal** [comment]
Fixed 8d9f68b778d60e6e63c7738b3ced25095dd12130
