### ISSUE TITLE
DNS access settings, Blocked domains --> Disallowed domains

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#1541]
In access settings of DNS settings:
https://crowdin.com/translate/adguard-applications/17566/en-zhtw#3862906
Blocked domains
`Don't confuse this with filters. AdGuard Home will drop DNS queries with these domains in query's question.`
<details><summary>Screenshot:</summary>

![image](https://crowdin.com/s/93f363g3m483v6f3a307p4v425o4l4m413g4b3i4s4t4d3b3b6s4k453t473n4i46393938373b68643p4v4m47366c3j4a3q476v20535q4?size=origin&1585883000776)
</details><br/>

What blocked domains do you mean?
It sounds like AG Home will ignore/exclude DNS queries with these domains in the list from query's question.
But general users will be really confused between blocked domains by filters and this.
May you change "Blocked domains" to "Ignored domains" or "Excluded domains" here?
Thanks.

**Comment by ameshkov** [comment]
Tbh, these are "blocked" in the same sense as the "blocked" clients from the same section.

Tbh, I think "Ignored" would be even more confusing.

**Comment by lancelot-moon** [comment]
TBH, my original thought is to replace "Blocked" with "Forbidden".
How about "Forbidden" if you think ignore/exclude isn't good?

**Comment by ameshkov** [comment]
To my ear, forbidden just does not sound right, something like "forbidden to visit" or smth like that.

I guess we can try "Disallowed domains" to make it look exactly like "Disallowed clients"

**Comment by lancelot-moon** [comment]
Good idea!
Thanks.

**Comment by HopHop20** [comment]
I have to admit, I still don't understand the purpose of this feature... Can someone provide me an example why we would use this and the end result?

**Comment by ameshkov** [comment]
It's useful to those who run public DNS servers as a measure against DNS amplification attacks which usually look like a DNS query to some domain.
