### ISSUE TITLE
Ad guard block app bank Bradesco

### ISSUE THREAD

**Issue by mpkoslovsky** [AdguardTeam/AdGuardHome#1544]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 317157
 **How did you setup DNS configuration:**
  * home assistant 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**home assistant NuC
  * 

### Expected Behavior
 open app bank Bradesco 

### Actual Behavior

Error to open app Bradesco, after disable protection I can open. 
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Please open query log and check what domains are blocked there? Most likely unblocking an individual domain would be enough
