### ISSUE TITLE
Solve the issue with DNS cache pollution -- add bogus-nxdomain

### ISSUE THREAD

**Issue by yiguihai** [AdguardTeam/AdGuardHome#1545]
DNS cache pollution
Great Firewall of China (GFW)

This is the DNS resolution service I use.

202.103.224.68
202.103.225.68
119.29.29.29
223.5.5.5

![DNS cache pollution](https://user-images.githubusercontent.com/22967964/78424460-430d2000-76a0-11ea-87b1-46c2288280bf.jpg)

My DNS returned an IP address of 127.0.0.1, I don't know how to block this wrong response, I just found a DNS rewrite related setting 
But it's also too much trouble. Why don't I change the other DNS, because they return IP addresses that are close to my actual address and they are great.
The logging is not detailed enough because I did not get the response to what it was returned by the DNS （I can't find anything that DNS returns.）
I also didn't find the option to query the DNS response

**I don't know English. I'm sorry**

**Comment by hezhijie0327** [comment]
试着使用 DNS-over-TLS / DNS-over-HTTPS 作为上游 DNS 服务器。
例如：
https://doh.opendns.com:443/dns-query
tls://dns.google:853

**Comment by yiguihai** [comment]
> 试着使用 DNS-over-TLS / DNS-over-HTTPS 作为上游 DNS 服务器。
> 例如：
> https://doh.opendns.com:443/dns-query
> tls://dns.google:853

这些dns都没有运营商的自带dns友好

**Comment by ArchiveBase** [comment]
@yiguihai 您可以在下面使用,
 
- https://dns.alidns.com/dns-query
223.5.5.5, 223.6.6.6
- https://kb.adguard.com/en/general/dns-providers#yandex-dns
- https://kb.adguard.com/en/general/dns-providers#adguard-dns

127.0.0.1不是一个很大的问题，但是如果您真的想使用Twitter，请使用VPN

**Comment by yiguihai** [comment]
> @yiguihai 您可以在下面使用,
> 
> https://dns.alidns.com/dns-query
> 223.5.5.5, 223.6.6.6
> https://kb.adguard.com/en/general/dns-providers#yandex-dns
> https://kb.adguard.com/en/general/dns-providers#adguard-dns
> 
> 127.0.0.1不是一个很大的问题，但是如果您真的想使用Twitter，请使用VPN

我在路由器部署[TcpRoute2](https://github.com/GameXG/TcpRoute2#tcproute2)带有客户端dns解析纠正功能，最怕的是返回保留地址。流量根本不会发到路由器而是发送回本地。这样直接访问失败！
为什么不添加一个返回ip地址黑名单呢？就算不添加这个日志显示也要有是由那个dns服务返回的解析。最不济响应内容也要添加一个查找的功能吧？找出那个域名响应被污染。

**Comment by ArchiveBase** [comment]
>流量根本不会发到路由器而是发送回本地

所以这不是GFW问题

>为什么不添加一个返回ip地址黑名单呢？

AGH无法阻止IP地址 https://github.com/AdguardTeam/AdGuardHome/issues/1537#issuecomment-608025747 https://github.com/AdguardTeam/AdGuardHome/issues/921

**Comment by ArchiveBase** [comment]
>dnsmasq 是带有这种功能的 bogus-nxdomain='劫持IP'
如果这些基本功能需求都没有的话，我觉得这个dns服务并不合格

https://discourse.pi-hole.net/t/automatically-block-upstream-dns-hijacking-typosquatting-with-dnsmasqs-bogus-nxdomain/13368

@ameshkov 会告诉有关它的任何事情 ;) 
(@ameshkov may tell anything about it)

**Comment by yiguihai** [comment]
回归dnsmasq
浏览器上不了 jav321.com 我以为是只是被封或者倒闭了。无奈谷歌搜索都是指向这个网站然后引起了我的注意。我没有用vpn测试，先是把域名加入tcproute2代理列表，没有访问成功然后查找dns记录发现返回状态为 NXDOMAIN 我用vps解析得到的是Cloudflare的cdn地址然后重写dns返回。成功访问！
发现都是运营商dns搞得鬼
不是返回127.0.0.1就是返回污染地址不然就是NXDOMAIN什么也没有
我设置了4组dns解析服务器，竟然给我返回空值，我测试过了只有运营商的dns是没有数据返回的其它的都有返回ip
那多上游dns解析的选项有什么用？这个项目我不会再关注了。这一次我彻底愤怒了！

**Comment by ameshkov** [comment]
@yiguihai 

我不懂，你为什么把这个Github问题关闭了吗？

请问你说明我，dnsmasq bogus-nxdomain怎么解决这个问题？stop-dns-rebind怎么样？

**Comment by Mosney** [comment]
AGH not designed to avoid DNS pollution, and even DNS result is correct, you still cannot connect some site under GFW. I suggest you just set AGH upstream to ISP DNS, choose a proxy software and it can fix or ignore pollution generally.

Additionally, For my instance, I deploy a Transparent Gateway Proxy which supports by [clash](https://github.com/Dreamacro/clash), and AGH setted the only upstream is clash dns(this resolution need you to know how network work enough).

**Comment by Mosney** [comment]
And the question is (I try to repeat this issue):
In the past, GFW pollute DNS only give some Twitter/FB's IP, even those IP has been blocked in china but proxy software could ignore/fix it. But now, DNS pollution start reply 127.0.0.1, and this time connect of browser/client will no longer sent packages to the upstream gateway or proxy software, just connect to local loopback NIC, so it will failing past bypass ways.
And the feature requested by original guys @yiguihai is that set a DNS result blacklist to avoid this problem, it will useful to mainland china user.

**Comment by Mosney** [comment]
And my question is, how to config when I have more than one IP address need to be added in   bogus_nxdomain , I cannot find any hint at [wiki ](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration), Should it separate by comma look like this?
` bogus_nxdomain: [127.0.0.1,127.0.0.2,127.0.0.3]`
or IP CIDR support? like this 
`bogus_nxdomain: [127.0.0.0/24,192.168.0.0/16,240.0.0.0/4]`
@ameshkov

**Comment by ameshkov** [comment]
> Should it separate by comma look like this?
> bogus_nxdomain: [127.0.0.1,127.0.0.2,127.0.0.3]

Well, this is a standard yaml string array:
https://stackoverflow.com/questions/23657086/yaml-multi-line-arrays

CIDR's aren't supported. Do you think we should?

**Comment by Mosney** [comment]
> Well, this is a standard yaml string array:
> https://stackoverflow.com/questions/23657086/yaml-multi-line-arrays
> 
Thx for yaml syntax.

> CIDR's aren't supported. Do you think we should?

For my experience fight with GFW in China, the pollute IP will not static, even now may only point to 127.0.0.1,  in the future may use other reserved IP range. Actually, now YouTube relevant domain has been polluted to 240.0.0.0/8. So, for my standpoint, I wish it support CIDR, just in case.

**Comment by ameshkov** [comment]
@Mosney got it, thank you!

Added a task for that: https://github.com/AdguardTeam/AdGuardHome/issues/1730
