### ISSUE TITLE
When restart the service or reboot the device, the query logs will be cleared.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#1546]
Build: v0.101.0-47-ge84c
Device: Raspberry Pi 3B+

\# My AdGuardHome.yaml
bind_host: 0.0.0.0
bind_port: 80
users:
\- name: admin
  password: $2y$05$LSJz6ECy0bzne5UFbKfY3Obq5m1nF5GutkeRAlII8YOB1VNkyp57C
http_proxy: ""
language: zh-cn
rlimit_nofile: 0
web_session_ttl: 3600
dns:
  bind_host: 0.0.0.0
  port: 53
  statistics_interval: 1
  querylog_enabled: true
  querylog_interval: 1
  querylog_size_memory: 0
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: nxdomain
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 3600
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  \- 223.5.5.5:53
  \- 223.6.6.6:53
  all_servers: true
  edns_client_subnet: true
  enable_dnssec: true
  aaaa_disabled: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  cache_size: 65536
  cache_ttl_min: 60
  cache_ttl_max: 3600
  upstream_dns:
  \- https://doh.opendns.com:443/dns-query
  \- tls://dns.google:853
  filtering_enabled: false
  filters_update_interval: 1
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 65536
  safesearch_cache_size: 65536
  parental_cache_size: 65536
  cache_time: 3600
  rewrites: []
  blocked_services: []
...

**Comment by hezhijie0327** [comment]
Build v0.101.0-50-g1fa6. Fixed.

**Comment by yeezylife** [comment]
我和你一样在文件里更改了web_session_ttl的值，但是我发现只要在网页里改动AGH的设置。。这个web_session_ttl的值又会自动变回去默认的720..
