### ISSUE TITLE
local DNS 

### ISSUE THREAD

**Issue by Threefish4096** [AdguardTeam/AdGuardHome#1551]
Would it be possible to add the possibility of storing IP for a certain time to AdGuardHome to become a local DNS in all respects?

**Comment by ameshkov** [comment]
Could you please elaborate, I don't fully understand the question. What IP you are talking about?

**Comment by Threefish4096** [comment]
It would be nice if AdGuard Home allowed to keep a mini database containing all the queries that have been resolved in the last 24 hours maybe, or even more.
Doing so would save you from having to query for hostname resolution over and over again if you visit the same site.
It would be a feature that if implemented ad hoc would bring the advantage of not having to resolve hostnames every time but would be enough once to have the ip already in the mini database, perhaps associated with the domain to which it is connected.
Doing so would save you milliseconds in asking DNS as CloudFlare which is the IP of a machine to which you have to connect, for example.

**Comment by ameshkov** [comment]
Well, it sounds like a cache to me, and AGH already has one.

The difference is that DNS cache works differently, it stores data for a time-to-live period specified in every DNS record. The good news is that in AGH you can override this and set whatever TTL you'd like to have, but this will be available in v0.102 (see #1214 )

**Comment by Threefish4096** [comment]
Perfect, if it is already available I have not noticed, thanks for the availability and good work!
