### ISSUE TITLE
[beta] Can't update filter

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1553]
### Issue Details

- Stop service
- Delete all filter (.txt)
- Start service

* **Version of AdGuard Home server:**
  * v0.101.0-52-g8f00 (Windows)
* **Operating system and version:**
  * Windows 10 x64

### Expected Behavior

AGH will create .txt file at `data/filters`.

### Actual Behavior

I see nothing.

### Additional Information

[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/4441863/log.txt)

**Comment by szolin** [comment]
> [error] os.Chtimes(): chtimes C:\AGH\data\filters\65535.txt: The system cannot find the file specified.

Fixed in golibs v0.4.2

**Comment by ameshkov** [comment]
Wait, weird that it happens in `g8f00`, we're using golibs v0.4.2 there

**Comment by ameshkov** [comment]
Ah, I found the issue, the fix is coming soon
