### ISSUE TITLE
hpHosts is dead

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1557]
According to [this article](https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003), AGH default filter have to change.

https://github.com/AdguardTeam/AdGuardHome/blob/fe056cfaf032e252c1d45ccfd093321edbd6c873/home/filter.go#L70

**Comment by ammnt** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1536
