### ISSUE TITLE
Add another /querylog API call with offset/limit params

### ISSUE THREAD

**Issue by ax42** [AdguardTeam/AdGuardHome#1559]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * Home Assistant

### Expected Behavior
`querylog` API should give access to all querylog entries matching a filter (if given), either as a single response or using paging.

### Actual Behavior
Calling the `querylog` via API returns a maximum of 500 entries.

</details>

**Comment by ameshkov** [comment]
Yeah, it's a paged API, you need to make additional requests to get next entries.

Check how it's done on the query log page of AGH itself

**Comment by ax42** [comment]
Thanks.  I can't read the page's source code that well however I've tried to reverse-engineer using API calls and I'll try and put together a PR to update the openapi README page.  I'd like to be confident that I am describing it correctly.  As far as I can tell:

- Each API response includes an `oldest` field
- that field can be directly placed into the `older_than` parameter of the follow-up query

How does the user know when there is nothing left to return?  There seems to be a `Transfer-Encoding: chunked` header while there is still data coming, not sure that's the best indicator though.  Is there a canonical indicator (no entries in `data`, or `1970-01-01` as `oldest` are both things I've seen)?  The API doesn't always return 500 entries either, does it just return the last 24(?) hours by default?

**Comment by szolin** [comment]
Please refer to `AGHTechDoc.md`, section `API: Get query log`.

> How does the user know when there is nothing left to return?

Server will return `"oldest": ""`

**Comment by ax42** [comment]
Thanks -- could you perhaps link to this document please (couldn't find it through Github search).  A link in the README.md of the API probably answers many questions.

**Comment by szolin** [comment]
It's in the root directory
https://github.com/AdguardTeam/AdGuardHome/blob/master/AGHTechDoc.md

**Comment by ameshkov** [comment]
I guess we could also add another `/querylog` API call with a little bit more convenient API, with `offset` and `limit` fields as everyone is accustomed to.

Our current API ensures that there are no too long timeouts when you're on the query log page, but it's indeed not very convenient to use.

**Comment by ax42** [comment]
Thanks.  I'm wanting to build my own stats page (primarily for personal use) to dig down into some questions.  Personally I use R, so consuming an API is ideal.  Previously I had been using pi-hole and was pulling a copy of the DB, API is much preferable.

**Comment by szolin** [comment]
> more convenient API, with offset and limit fields

With `offset` parameter it would be impossible to find the next chunk of logs quickly enough.  The offset value must be either a real file offset (which can change at any time) or a date (which is used now - and it's robust).

**Comment by ameshkov** [comment]
@szolin sure, we'll have to go through the list starting from the very beginning. Not fast, but it's really more convenient. 

Note that this API method is for external usage, we will continue to use the current method ourselves.
