### ISSUE TITLE
Scheduler for internet access

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1563]
Will you make a scheduler for accessing Internet resources? For example, access for some client to fortnite only from 16.00 to 18.00, but the other Internet is not disabled?

**Comment by ArchiveBase** [comment]
@YBS-PC upvote https://github.com/AdguardTeam/AdGuardHome/issues/951 https://github.com/AdguardTeam/AdGuardHome/issues/1203
