### ISSUE TITLE
DHCP support

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardHome#1564]
### Problem Description
It is not currently possible to use DHCP options w/AdGuard Home.

### Proposed Solution
Add built-in DHCP support.

### Alternatives Considered
Allow AdGuard Home to control dhcpd.

### Additional Information
Original submission: see helpdesk ID 2633864

**Comment by ameshkov** [comment]
there is a built in dhcp server in AGH

**Comment by akmLaVx** [comment]
@ameshkov thanks for clarifying - we've been told that AGH does not have one.
