### ISSUE TITLE
Accidently banned Lark

### ISSUE THREAD

**Issue by kmahyyg** [AdguardTeam/AdGuardHome#1565]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**

v0.101.0

* **How did you setup DNS configuration:**

Deployed on my Laptop currently used to send this issue out.

* **Operating system and version:**
 
Windows 10 1909

### Expected Behavior

Working Properly when trying to load Lark Cloud Documents.

### Actual Behavior

Get banned.

![image](https://user-images.githubusercontent.com/16604643/78990167-5a4c8180-7b68-11ea-88d8-4357841878e1.png)

### Additional Information

As #950 introduced the ban to TikTok. The online conferencing software made by the same company which named as "Lark" was also get banned. Lark is using the same domain for users' documents, it get accidentally banned by the TikTok rules.

According to captured data from TLS SNI, the following domain names should be whitelisted:

- `*.byteoversea.com`  ( currently  maliva-mcs.byteoversea.com vaali-mcs.byteoversea.com, mon-va.byteoversea.com)
- `*.larksuite.com` 
- `*.larksuitecdn.com`

**Comment by kmahyyg** [comment]
![image](https://user-images.githubusercontent.com/16604643/79035019-e3a59780-7bec-11ea-9696-df2f33eb63b9.png)

I suddenly found that you've also mistakenly take the largest network disk in China as Ads just because they are operating by the same company?  This domain doesn't serve any tracker or ads.

- pan.baidu.com

**Comment by ameshkov** [comment]
Hm, but according to your log it's not blocked. It's your DNS server that returns NXDOMAIN for it, AGH just shows you the information on the domain that we have.

**Comment by kmahyyg** [comment]
> Hm, but according to your log it's not blocked. It's your DNS server that returns NXDOMAIN for it, AGH just shows you the information on the domain that we have.

Then why I use kdig to tls://1.1.1.1 and get correct answer? this is the problem.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by hnnweb** [comment]
In the first picture
Please hover your mouse over the **right questionmark** to find out which filter that is blocking.
The "Found in the known domains database" is just information about the domainname.

**Comment by kmahyyg** [comment]
![image](https://user-images.githubusercontent.com/16604643/79408043-f6ddac00-7fcc-11ea-97f6-a821ae0b9798.png)

Log File attached here: 
[logfile-20200416.log](https://github.com/AdguardTeam/AdGuardHome/files/4484568/logfile-20200416.log)

**Comment by hnnweb** [comment]
Just by going to their homepage and clicking "[Let's get started](https://www.larksuite.com/create/?from=navigation_bar_free_register&lang=en-US)" triggers "s16.bytesoverseas.com". Atleast for me.

This is what i see in my Console

```
Failed to load ‘https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/css/web.bdbd04e9.css’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Failed to load ‘https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/vendor.afb33441.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Failed to load ‘https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/index.adfe84fc.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Failed to load ‘https://ds-aksb-a.akamaihd.net/aksb.min.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Loading failed for the <script> with source “https://ds-aksb-a.akamaihd.net/aksb.min.js”. create:1:1
Failed to load ‘https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/vendor.afb33441.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Loading failed for the <script> with source “https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/vendor.afb33441.js”. create:75:1
Failed to load ‘https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/index.adfe84fc.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Loading failed for the <script> with source “https://s16.byteoversea.com/ee/suite_passport_fe/static/v2/overseas/index.adfe84fc.js”. create:75:1
Failed to load ‘https://s16.byteoversea.com/ee/suite_password_fe/static/v2/favicon.ico’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Failed to load ‘https://www.googletagmanager.com/gtag/js?id=UA-98246768-8’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-98246768-8”. create:18:1
```

**Comment by kmahyyg** [comment]
Okay, it's not your problem. But the rules problem. AdGuard Simplified Domain Names filter, this blocklist is the killer. I'll manually whitelist the whole domain I need.

**Comment by kmahyyg** [comment]
By the way, I use their client.

**Comment by ameshkov** [comment]
@kmahyyg ah, so blocking `byteoversea.com` is the root cause, we'll unblock it, thank you1

**Comment by Alex-302** [comment]
Removed recenly added rule: `||byteoversea.com^`
