### ISSUE TITLE
About entware version of adguardhome

### ISSUE THREAD

**Issue by GalaxyAlpha** [AdguardTeam/AdGuardHome#1566]
Hello, For easy install to asuswrt-merlin,could you prepare the entware of arm version package,thanks.

**Comment by ammnt** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1078

**Comment by GalaxyAlpha** [comment]
> [＃1078](https://github.com/AdguardTeam/AdGuardHome/issues/1078)

Its only had mipsel version,can it also be used in arm?

**Comment by ammnt** [comment]
> > [＃1078](https://github.com/AdguardTeam/AdGuardHome/issues/1078)
> 
> Its only had mipsel version,can it also be used in arm?

Honestly, I have no idea. While I waited for the version for Entware - already adjust everything on VPS. What I recommend to everyone...

**Comment by GalaxyAlpha** [comment]
> > > [＃1078](https://github.com/AdguardTeam/AdGuardHome/issues/1078)
> > 
> > 
> > Its only had mipsel version,can it also be used in arm?
> 
> Honestly, I have no idea. While I waited for the version for Entware - already adjust everything on VPS. What I recommend to everyone...

Okay,I'll try it,thanks.

**Comment by dartraiden** [comment]
> Its only had mipsel version,can it also be used in arm?

Try to ask at https://t.me/entware
