### ISSUE TITLE
HTTPS-Only Mode or Setting

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#1567]
### Problem Description
Please consider adding an HTTPS only mode or setting (i.e. a setting to block all non-HTTPS traffic).

**Comment by ameshkov** [comment]
Do you mean HTTPS-only for admin-panel only?

**Comment by hl2guide** [comment]
I mean a setting to block all HTTP traffic.

**Comment by ameshkov** [comment]
Well, if "Redirect to HTTPS" is enabled, it basically does that (all HTTP requests will be redirected).

Is it not enough?
