### ISSUE TITLE
DNS Rewrite -  Adding only AAAA record causes queries for A record to return NOERROR

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#1569]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Virtual Machine
* **Operating system and version:**
  * Debian 10

### Expected Behavior

Added a DNS rewrite entry to rewrite `*.netflix.com` -> `::`, IPv6 equivalent of `0.0.0.0`

Returns null IP address for AAAA record
```
❯ dig +short AAAA api.netflix.com
::
```

Actual entries for A records

```
❯ dig +short api.netflix.com
api.geo.netflix.com.
api.eu-west-1.prodaa.netflix.com.
52.215.19.134
52.213.169.106
52.213.123.193
52.31.250.247
52.31.248.159
52.30.251.145
52.211.241.215
52.213.208.129
```

### Actual Behavior

A record queries respond with NOERROR
```
❯ dig A api.netflix.com

; <<>> DiG 9.10.6 <<>> A api.netflix.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54818
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.netflix.com.               IN      A
```

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/62358249/79055425-eb912600-7c44-11ea-9094-1948fef7a334.png)

![image](https://user-images.githubusercontent.com/62358249/79056000-c652e680-7c49-11ea-8b07-f148efb0f028.png)

</details>

### Additional Information

Netflix blocks access when you use HE's Tunnelbroker (https://tunnelbroker.net/) to get IPv6. This is because they treat them as a proxy service and block access due to their contractual obligations.

The way people work around the problem is by either blocking AAAA records for netflix domains or blocking Netflix's IPv6 ranges so it falls back to IPv4 routing over local ISP.

In dnsmasq, you set it to return `::`, IPv6 version of 0.0.0.0,  for all IPv6 records on netflix domains. As a result, netflix client would fail to connect over IPv6 and fallback to IPv4. https://gist.github.com/jamesmacwhite/6a642cb6bad00c5cefa91ec3d742e2a6#method-1-return-null-on-aaaa-lookups-with-dnsmasq

For unbound, there is a python module to block IPv6 for certain domains - https://gist.github.com/FiloSottile/e2cffde2bae1ea0c14eada229543aebd/

**Comment by ameshkov** [comment]
It works as expected.

I guess we need to provide a way to resolve this issue, though. I'll merge this into https://github.com/AdguardTeam/AdGuardHome/issues/1547
