### ISSUE TITLE
add support to allow only specific sites and deny the rest

### ISSUE THREAD

**Issue by eduaddad** [AdguardTeam/AdGuardHome#1571]
Add support to allow only specific sites and deny the rest
* When a site is added to the filter only that site will be considered to be blocked blocking the rest

**Comment by ameshkov** [comment]
You can achieve this by adding a rule like this to custom rules:
`||*`

And then unblock the websites that you want to access:
`@@||example.org`

**Comment by eduaddad** [comment]
||*
@@|google.com.br
@@|google.com
@@|mundoeducacao.bol.uol.com.br
@@|mundoeducacao.bol.uol.com.br
@@|infoescola.com
@@|brainly.com.br
@@|classapp.com.br
@@|angloitape.com.br
@@|classroom.google.com
@@|hangouts.google.com
@@|meet.google.com

this @ameshkov ?

**Comment by ameshkov** [comment]
@eduaddad yep, this will keep only these domains not blocked

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1203
