### ISSUE TITLE
How can I access the configuration interface remotely?

### ISSUE THREAD

**Issue by eduaddad** [AdguardTeam/AdGuardHome#1575]
How can I access the configuration interface remotely?

**Comment by ameshkov** [comment]
Could you please elaborate? What's your current configuration?

**Comment by eduaddad** [comment]
access the administration interface outside the local network

**Comment by ameshkov** [comment]
Hm, most likely that'd require using some reverse proxy with dyndns support. 

I haven't ever configured one myself, maybe someone else can comment on this and give some advice.

**Comment by eduaddad** [comment]
I configured the port but I can only do it on the internal network

**Comment by DandelionSprout** [comment]
I have no idea how to do it on ordinary setups, but I do know how to do it when HTTPS encryption has been set up:

1) Go to AGH's encryption settings and choose a port. 4- and 5-digit ports are far less frequently reserved for other purposes.
![image](https://user-images.githubusercontent.com/22780683/79126966-3d4ec300-7da1-11ea-8528-cb9a44c00b9f.png)
2) Enter your router's settings.
3) Find its (IPv4) port forwarding settings menu.
4) Create an entry that connects the external port, to the same-number internal port at the server's local IP. If you're using an ASUS router, it should normally look like this.: 
![image](https://user-images.githubusercontent.com/22780683/79127398-1d6bcf00-7da2-11ea-9460-794b9516840c.png)
5) Save the entry if it's not already done.
6) If you're at home, set your phone to use mobile data and do whatever last amendments that may be needed for your specific setup.

**Comment by eduaddad** [comment]
Use the defined portal (standard) of HTTPS  but it was not possible to connect outside the internal network

**Comment by eduaddad** [comment]
configured on port 2105 plus is not yet possible

**Comment by eduaddad** [comment]
and is it possible to place for cloudflare?

**Comment by ameshkov** [comment]
Setup AG Home on VPS or acquire a public IP address, these are the only ways I know.

**Comment by eduaddad** [comment]
@ameshkov When I place it without going through the cloudflare it works but when I put it in the cloudflare it doesn't work

![2020-05-18](https://user-images.githubusercontent.com/16819380/82270456-42c49d80-994b-11ea-9b68-32e4f8a4e67a.png)

**Comment by ameshkov** [comment]
@eduaddad make sure that cloudflare IPs are allowed on your server

**Comment by eduaddad** [comment]
@ameshkov  I'm using the address of a linux at home and when the proxy without a proxy works

I think there is no blocking in the proxy
