### ISSUE TITLE
Option to enforce DNSSEC

### ISSUE THREAD

**Issue by jitdor** [AdguardTeam/AdGuardHome#1576]
This was first posted on reddit and the community manager suggested a formal feature request to be made here, so here I am.

The request is for DNSSEC support to be added to Adguard Home at some point. In particular an option to not serve records failing DNSSEC validation on DNSSEC-enabled domains.

Thank you!

**Comment by Eyeborgs** [comment]
#66

**Comment by ameshkov** [comment]
Well, the current implementation in the master branch is rather simple, we just rely on the DNS resolver. 

Let's merge this one in a new issue about full DNSSEC support: https://github.com/AdguardTeam/AdGuardHome/issues/1579
