### ISSUE TITLE
Display more than 5 lines in "DNS rewrites"

### ISSUE THREAD

**Issue by jitdor** [AdguardTeam/AdGuardHome#1578]
Currently, the DNS rewrites section of Adguard Home would display only up to 5 rows at any point in time, regardless of the rows-in-page setting. This makes scrolling through the list harder than it has to be when the list has more than 5 rows.

Since "DNS rewrites" already has its own page in the latest version, I would suggest the 5-row limit be removed and let the height of the table be dynamically sized based on the row-per-page setting.

**Comment by Eyeborgs** [comment]
fully support the idea

**Comment by ameshkov** [comment]
@ArtemBaskal let's make the default height 100%

**Comment by ArtemBaskal** [comment]
Fixed 2837502a7b379b261004d691460792dc61f61492
