### ISSUE TITLE
An issue with wildcard TLS certificate

### ISSUE THREAD

**Issue by TXC** [AdguardTeam/AdGuardHome#1580]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0-92-g8d9f
* **How did you setup DNS configuration:**
  * LXC Container
* **If it's a router or IoT, please write device model:**
  * Not applicable
* **Operating system and version:**
  * Ubuntu 18.04.4 LTS

### Expected Behavior
Visit the AdGuard Home loginscreen and be able to use the webinterface

### Actual Behavior
White screen and warning in JavaScript Console, unable to see the login screen.
If i visit the IP directly, and allow the exception, everything works.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="459" alt="image" src="https://user-images.githubusercontent.com/236697/79127423-29f02780-7da2-11ea-9994-c5986b680123.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/236697/79127512-50ae5e00-7da2-11ea-845d-299e22886079.png">

</details>

### Additional Information
Using a Let's Encrypt wildcard certificate for domain `*.txc.se`.
Using `fullchain.pem` and `privkey.pem` as per the Guide in the Wiki.

```
2020/04/13 11:39:05 http: TLS handshake error from 192.168.50.155:58080: remote error: tls: bad certificate
2020/04/13 14:18:06 http: TLS handshake error from 192.168.50.155:58081: remote error: tls: bad certificate
2020/04/13 14:18:07 http: TLS handshake error from 192.168.50.155:58084: remote error: tls: bad certificate
2020/04/13 14:18:08 http: TLS handshake error from 192.168.50.155:58085: remote error: tls: bad certificate
2020/04/13 14:18:09 http: TLS handshake error from 192.168.50.155:58086: remote error: tls: bad certificate
2020/04/13 14:18:10 http: TLS handshake error from 192.168.50.155:58088: remote error: tls: bad certificate
2020/04/13 14:19:11 http: TLS handshake error from 192.168.50.165:59406: EOF
```

**Comment by ameshkov** [comment]
Does restart help?

**Comment by TXC** [comment]
No, have restarted the SystemD service, but still have the same error.

**Comment by ameshkov** [comment]
That's quite weird, and the error that's printed does not help much.

I am starting to think that the problem is that the certificate is wildcard, and AGH does not handle it properly. We'll check it.

**Comment by TXC** [comment]
Does it help that `adguard.txc.se` is a DNS rewrite to an internal IPv4 in AGH ?

**Comment by ameshkov** [comment]
I don't think this is what causes the issue. It seems that the problem is inside AGH itself.

Btw, try clearing "Server name" in the encryption settings, does it change anything?

**Comment by TXC** [comment]
Still same error when i visit the domainname.

Firefox Developer Edition accepts the cert over TLS 1.3
<img width="712" alt="image" src="https://user-images.githubusercontent.com/236697/79131140-6161d280-7da8-11ea-9e7a-fc8bb5c4623a.png">

**Comment by ameshkov** [comment]
Hm, is the issue specific to Firefox?

**Comment by ameshkov** [comment]
What error Firefox shows in the Network panel?
Enable logging in `about:networking#logging` and check what's there

**Comment by TXC** [comment]
Yes this is a Firefox (tested Stable (75.0) and Developer Edition (76.0b3)) only issue, i've tested with Safari and Chrome, both works fine! 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/236697/79132412-953df780-7daa-11ea-955b-604446c21aff.png">

I went through the log, nothing obvious there.

**Comment by ameshkov** [comment]
Just in case, could you please try generating a new let's encrypt cert specifically for that domain?

**Comment by TXC** [comment]
Same error with this cert.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/236697/79142639-1782e780-7dbc-11ea-90c7-57611218908a.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/236697/79142515-eb676680-7dbb-11ea-92ea-70fe12707f14.png">

**Comment by ameshkov** [comment]
Can you reproduce it on a clean FF profile? Maybe it's some profile-level settings that cause this?

**Comment by TXC** [comment]
Okey!

I close this!
It works in safe-mode, and when i disabled uBlock Origin it also worked.

*facepalm*

(EasyList blocks `/adguard.$domain=~adguard-com.cdn.ampproject.org|~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com` )

Thanks for the great support and software!
