### ISSUE TITLE
hpHosts has been discontinued, needs removed from AdGuardHome

### ISSUE THREAD

**Issue by BlohoJo** [AdguardTeam/AdGuardHome#1581]
### Prerequisites

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Additional Information

hpHosts has been discontinued: [https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003](https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003)

This filter appears to be "hard coded" into AdGuardHome as 3.txt. If filters are going to be hard coded into the application, then this will need to be removed.

**Comment by rapdodge** [comment]
Agreed 👍

**Comment by evilvibes** [comment]
#1536

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardHome/commit/4b57776976481925e119a9fc9d09ea57c3be1531
