### ISSUE TITLE
Abnormally long TTL and no website connections for iOS devices

### ISSUE THREAD

**Issue by whattheschnell** [AdguardTeam/AdGuardHome#1582]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home v0.101.0
* **How did you setup DNS configuration:**
  * DD-WRT, DHCP Disabled, dnsmasq: 
no-resolv
server=8.8.8.8
server=8.8.4.4
dhcp-option=6,10.0.0.100

On Adguard:

Upstream Servers:
1.1.1.1
1.0.0.1

Adguard running on RPi4B

* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4B

* **Operating system and version:**
  * Home Assistant Supervised, https://github.com/hassio-addons/addon-adguard-home

### Expected Behavior

All devices have similar TTL, no timeouts

### Actual Behavior

Android, Windows10, IoT devices all have fast to acceptable DNS response times

iOS devices (1 iPad, 1 iPhone) have longer than expected TTL times, and 99% of web pages just completely fail to load.  If I manually specify 1.1.1.1 or any other common DNS in iOS WiFi settings (bypass home DNS server), then everything works as expected

### Screenshots

<details><summary>Screenshot:

10.0.0.12 is an iPad.  

![image](https://user-images.githubusercontent.com/8886395/79180470-aa794d00-7dcf-11ea-80de-8b799ebfb7be.png)

![image](https://user-images.githubusercontent.com/8886395/79180736-4f942580-7dd0-11ea-949d-b028e297b918.png)

</summary>

</details>

**Comment by ameshkov** [comment]
Tbh, I don't understand what could be the cause here.

I there anything else that you've changed in the AGH settings?

Regarding TTL, it cannot depend on the device, the TTL is coming from the upstream DNS server and it's different for different domains.
