### ISSUE TITLE
Add a "Blocked by CIDR" colour/stamp distinction to the "Top Clients" statistic

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1586]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.101.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I realised around 2 weeks ago that disallowed clients are now shown in a pink-red colour in the "Top Clients" statistic, as seen in the screencap below. This is pretty convenient, so that one doesn't spend unnecessary time on disallowing IPs that have already been blocked.

![image](https://user-images.githubusercontent.com/22780683/79229000-a21e2200-7e62-11ea-8120-41a96521721d.png)

However, this does currently *not* occur if the IP has been disallowed by a CIDR in "Disallowed Clients". This means that `66.42.114.152` is shown as white and not blocked in "Top Clients", even if `66.42.64.0/18` is present in "Disallowed Clients" and indeed does disallow that particular IP.

### Proposed Solution

That clients that have been disallowed by CIDRs, are shown in a shade of red that differs slightly from that of clients disallowed by singular IPs; and also that a "Blocked by CIDR" tag, "Unblock CIDR" button or "Unblock IP" button is shown when hovering over it.

### Alternatives Considered

Whichever other way of distinguishing such CIDR-disallowed client IPs.

### Additional Information

None that I'm aware of at the moment.

**Comment by ameshkov** [comment]
This is possible but requires some work on the client-side to interpret disallowed CIDRs and check the IP addresses properly. However, unblocking IP, in this case, won't be possible -- excluding an IP address from a CIDR range is not a trivial task.

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2150

**Comment by ameshkov** [comment]
Btw, we implemented unblocking CIDRs after all so I guess this feature request is not needed anymore. The fix is available in the edge channel.
