### ISSUE TITLE
Expose cache size and TTL settings

### ISSUE THREAD

**Issue by alexiri** [AdguardTeam/AdGuardHome#1587]
### Problem Description
There's no way to modify the cache size or min/max TTL values from the web interface. These settings should be exposed.

### Proposed Solution
I started hacking on this [here](https://github.com/alexiri/AdGuardHome/tree/cache_opts), but I ran into issues saving the min/max settings. It's probably trivial to do, but I don't know Golang, so hopefully somebody else can pick it up.

**Comment by lordraiden** [comment]
Take a look to this as an inspiration to add cache settings and other advaced ones.
![imagen](https://user-images.githubusercontent.com/17175395/82154423-1e46c380-986e-11ea-8829-09a327a12b0a.png)

**Comment by szolin** [comment]
> but I ran into issues saving the min/max settings

Just add 3 more lines in `dnsforward.go` in `WriteDiskConfig()` - copy cache values to config.
Can you make a PR after that?
