### ISSUE TITLE
[Beta] minimum cache ttl doesn't apply to non cached queries

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#1588]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0-63-g2f9b
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Virtual Machine
* **Operating system and version:**
  * Debian 10

### Expected Behavior

Set min cache ttl but leave max to default value

```
cache_ttl_min: 300
cache_ttl_max: 0
```

When querying a domain that isn't in Adguard cache, it gets it from upstream DNS and returns it with min TTL set to 300 if TTL for the record is less than cache ttl minimum value.

```
❯ dig emea.ng.msg.teams.microsoft.com

; <<>> DiG 9.10.6 <<>> emea.ng.msg.teams.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9549
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1452
;; QUESTION SECTION:
;emea.ng.msg.teams.microsoft.com. IN    A

;; ANSWER SECTION:
emea.ng.msg.teams.microsoft.com. 3600 IN CNAME   emea.ng.msg.teams-msgapi.trafficmanager.net.
emea.ng.msg.teams-msgapi.trafficmanager.net. 300 IN CNAME msgapi-prod-neu.cloudapp.net.
msgapi-prod-neu.cloudapp.net. 300 IN    A       52.114.77.44
```

### Actual Behavior

Returns upstream response without modifying the TTL when the values are less than cache_ttl_min.

Obviously this gets fixed in subsequent query as it is served from cache but not for the first query that isn't served by cache

```
❯ dig emea.ng.msg.teams.microsoft.com

; <<>> DiG 9.10.6 <<>> emea.ng.msg.teams.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35398
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1452
;; QUESTION SECTION:
;emea.ng.msg.teams.microsoft.com. IN    A

;; ANSWER SECTION:
emea.ng.msg.teams.microsoft.com. 3600 IN CNAME  emea.ng.msg.teams-msgapi.trafficmanager.net.
emea.ng.msg.teams-msgapi.trafficmanager.net. 60 IN CNAME msgapi-prod-neu.cloudapp.net.
msgapi-prod-neu.cloudapp.net. 10 IN     A       52.114.77.44
```

**Comment by szolin** [comment]
> minimum cache ttl doesn't apply to non cached queries
> cache_ttl_min: 300
> cache_ttl_max: 0

Isn't it what we wanted in the first place?
https://github.com/AdguardTeam/AdGuardHome/issues/1214

I don't see why it's bad to return DNS records with the original TTL time when this response itself is not from the cache.
The reason why we need these options is to control *cache* behaviour.

**Comment by emlimap** [comment]
Reading the request in linked github issue, what I understand was that requester wanted a capability to override DNS records TTL that are below user defined value to the value set by the user. TTL's below a certain threshold make DNS cache virtually useless. 

You could argue the fact the setting name `cache-min-ttl` means you are talking about the min TTL for DNS records in cache

I think my interpretation of the feature might have been influenced by dnscrypt-proxy which I have been using for a while. Previously with Pi-hole since it doesn't support any form of encrypted DNS by itself. 

dnscrypt-proxy overrides the TTL's if it is below user defined minimum irrelevant of whether it is from cache or not. https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Caching#dns-cache The link to blog in that wiki page goes into detail about the scope of low TTL usage across popular domains.

There is nothing wrong with returning original TTL's on first request. To be honest, it is better than what it is now as the times between second and subsequent record refresh request from client is going to be a lot longer.

My main use case for overriding TTL is to save unnecessary traffic in mobile which results in better battery life. It makes a massive difference when you are in a weak coverage area. I have my phone use VPN and Adguard home runs on the same box as VPN. At the moment Adguard upstreams to dnscrypt-proxy as it doesn't have the capability to set min TTL in stable build.  

For example, Microsoft teams app calls quite a few domains (eg: emea.ng.msg.teams.microsoft.com) that have TTL's set at 60 seconds or below which isn't great for mobile. Ever since I had set the min cache TTL to 300 in dnscrypt-proxy the battery usage percentage for the app reported by the OS has dropped quite a bit.

Another example of really low TTL's is from AWS, they seem to have set the TTL for s3 related domains to 5 seconds at the moment.

```
; <<>> DiG 9.10.6 <<>> s3.eu-west-1.amazonaws.com @1.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16405
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;s3.eu-west-1.amazonaws.com.    IN      A

;; ANSWER SECTION:
s3.eu-west-1.amazonaws.com. 5   IN      A       52.218.102.35
```

**Comment by szolin** [comment]
It's strange that a few DNS requests over UDP make the battery life a lot shorter, because there's nothing really complex there.  Microsoft doesn't make their TTL so low without a reason - I guess they change the server addresses often.

Anyway, the problem with our setting `cache_ttl_min` is that it's designed specifically for cache.  So either:
* we change the setting name to `ttl_min` and we apply this for the original response (that's not from the cache)
* we add another setting `override_ttl_min` specifically for this

**Comment by ameshkov** [comment]
@szolin btw overriding TTL on the earlier stage (before it enters the cache) is a smart solution and it can save us some code.

**Comment by szolin** [comment]
Look like dnsmasq works:
I start it with `dnsmasq -p 5354 --min-cache-ttl=300`

1. first request with dig:
```
;; ANSWER SECTION:
apple.com.              40      IN      A       17.178.96.59
```
2. 2nd request:

```
;; ANSWER SECTION:
apple.com.              296     IN      A       17.142.160.59
```

This is exactly what we do now.
If dnsmasq doesn't need this feature - are we sure we need it?

**Comment by ameshkov** [comment]
It is definitely not too important, I just like the idea of controlling TTL in `dnsproxy.Resolve` instead of doing it in the cache, it looks more error proof

**Comment by emlimap** [comment]
> It's strange that a few DNS requests over UDP make the battery life a lot shorter, because there's nothing really complex there. Microsoft doesn't make their TTL so low without a reason - I guess they change the server addresses often.

I think it is a combination of few things. When it comes to mobile, the longer you keep the mobile radio awake, the more the impact is on the battery. The more traffic you generate, the less the mobile radio is going to go into sleep/low power mode. Also, how strong is your signal and added VPN overhead. Although Wireguard is better than IPSec on that front.

Also, I generally found Teams to be querying a lot more domains than Slack does but this might be because it has tight integrations with other Office 365 applications. 

On Desktop front, it is known to have performance issues for few years now and it seems they are prioritizing features over performance. Also, it is written in Electron which is a debate on its own.

Ever since the lockdown, Microsoft said that they have had unprecedented demand for Teams, so they might want to be able to move people across quickly and short TTL's is one way of doing it.

> Anyway, the problem with our setting cache_ttl_min is that it's designed specifically for cache. So either:

 > -  we change the setting name to ttl_min and we apply this for the original response (that's not from the cache)
 > - we add another setting override_ttl_min specifically for this

Personally I don't have a preference, both options works with me.

I can re-open as a feature request and see how many people would be interested in this behaviour.

Also noticed that in dnscrypt-proxy if you turn off caching, the `cache_min_ttl` setting stops applying. It seems that non cached queries also go through caching pipeline.

**Comment by szolin** [comment]
> The more traffic you generate, the less the mobile radio is going to go into sleep/low power mode

DNS requests are almost never sent on their own.  They usually start the sequence of network activity (HTTP requests, downloading response data).  And DNS 2 packets are really nothing compared to megabytes of data that follow.  So I still don't see how DNS requests can impact battery power.  I speak theoretically, because I obviously don't know all the details.

I don't know yet if it's really necessary to rename the settings, I guess we'll just leave them as they are and just slightly change their behaviour.

**Comment by ameshkov** [comment]
We can keep the setting name the same. IMO, this is just a slightly different and simpler implementation of the very same functionality.

**Comment by emlimap** [comment]
Something I missed. Not sure if it is expected or unexpected behaviour. 

It seems  when `min_cache_ttl` is set to say `300` and you query a domain (s3.amazonaws.com) which CNAME's to another domain with a higher TTL than minimum but that CNAME domain has a lower TTL A record, it causes both CNAME and the A record TTL to be overwritten to minimum.

First query wihout cache
```
;; ANSWER SECTION:
s3.amazonaws.com.	3597	IN	CNAME	s3-1.amazonaws.com.
s3-1.amazonaws.com.	2	IN	A	52.216.132.229
```
Second query from cache

```
;; ANSWER SECTION:
s3.amazonaws.com.	299	IN	CNAME	s3-1.amazonaws.com.
s3-1.amazonaws.com.	299	IN	A	52.216.85.61
```

**Comment by ameshkov** [comment]
That's how cache works - it will always use the minimum TTL value if there are many records.
