### ISSUE TITLE
[Beta] Old logs in query log UI when refreshed without filters

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#1589]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0-63-g2f9b
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Virtual Machine
* **Operating system and version:**
  * Debian 10

### Expected Behavior

Since updating to Adguard Beta from version v0.101.0, the query log UI is flaky when it comes to refreshing. 

At times, it will just get stuck with old logs and refresh button at the top will return same old logs as before. Force refresh in browser doesn't work. Have tried querying the endpoint the UI hits directly using curl to rule out browser caching but doesn't seem to make any difference.

### Actual Behavior

When queried for latest logs, it returns logs that are almost 50 mins old. I am not sure what the lag is between Adguard writing the log and it showing up in UI but would assume not more than few mins at worst case.

When querying at 12:29 UTC, the latest log is from 11:38 UTC.

```
$ date
Wed Apr 15 12:29:31 UTC 2020

$ curl 'http://127.0.0.1/control/querylog?filter_domain=&filter_client=&filter_question_type=&filter_response_status=&older_than=' -H 'Cookie: agh_session=d6cf
3f182d3ec8d9e7b08d20eb03872352e3c6974fe65a5351ee9faf4a517509' | jq .data[0]
{
  "answer": [
    {
      "ttl": 281,
      "type": "CNAME",
      "value": "reddit.map.fastly.net."
    }
  ],
  "answer_dnssec": true,
  "client": "192.168.5.75",
  "elapsedMs": "29.206361",
  "question": {
    "class": "IN",
    "host": "www.reddit.com",
    "type": "AAAA"
  },
  "reason": "NotFilteredNotFound",
  "status": "NOERROR",
  "time": "2020-04-15T11:38:48.151754718Z"
}
```
The logs are still collected and if query log is obtained with a filter, it returns the latest log. 
```
$ curl 'http://127.0.0.1/control/querylog?filter_domain=emea.ng.msg.teams.microsoft.com&filter_client=&filter_question_type=&filter_response_status=&older_than
=' -H 'Cookie: agh_session=d6cf3f182d3ec8d9e7b08d20eb03872352e3c6974fe65a5351ee9faf4a517509' | jq .data[0]
{
  "answer": [
    {
      "ttl": 128,
      "type": "CNAME",
      "value": "emea.ng.msg.teams-msgapi.trafficmanager.net."
    },
    {
      "ttl": 128,
      "type": "CNAME",
      "value": "msgapi-prod-neu.cloudapp.net."
    },
    {
      "ttl": 128,
      "type": "A",
      "value": "52.114.77.44"
    }
  ],
  "answer_dnssec": true,
  "client": "192.168.5.75",
  "elapsedMs": "0.191031",
  "question": {
    "class": "IN",
    "host": "emea.ng.msg.teams.microsoft.com",
    "type": "A"
  },
  "reason": "NotFilteredNotFound",
  "status": "NOERROR",
  "time": "2020-04-15T12:29:02.602918409Z"
}
```

### Additional Information

One interesting thing I found while testing, I did delete the querylog.json and restarted Adguard home to rule out corrupted query log json file. Query logs refreshed normally but after about half and hour when checked again, it stopped updating logs in UI. The query log file isn't big, about 567Kb as of opening this bug report.

The VM does have quite a bit of free memory so it hasn't run out of RAM

**Comment by ameshkov** [comment]
Do you mind sharing the problematic querylog.json in private (my email is am@adguard.com)? I need an example to reproduce it on my side.

**Comment by emlimap** [comment]
So I have been digging further and found that the log times in query UI match the time when querylog.json was last modified. So I guess the query UI by default grabs this file.

I have been keeping an eye on the `querylog.json` file modification times and it seems to be updated once every hour or two. 
For comparison v0.101.0, which I have running elsewhere, seems to be writing to disk every minute or so.

I am not a Golang person so haven't really looked into the code to see what is happening. Had a look in the doc folder which has the architecture diagram but doesn't seem to go into logging part. I do have a couple of questions which hopefully you can answer
1. I presume that Adguard home holds the latest queries logs in memory before they are accumalated for certain period and written to disk. Is this what is queried when you run a query with filters?
2. How often does Adguard home supposed to sync query logs to disk?
3. Does query log UI by default displays the contents of the query log file?

If Adguard home service is stopped or restarted, query logs are synced to disk straight away. The major change I can see so far in the Beta is upgrading to Go 1.14.

I am happy to send you the query logs file by email but just want to rule out the fact that my non-standard setup of running AGH as non-root user isn't causing problems. So that I don't waste your time looking in the wrong direction.

Below is the systemd file that is currently in use. It just uses AGH's default with some additional things like allowing non-root user to bind to port 53 and some restrictions around home directory, control group and kernel modules. I think it might be best to revert to default service file that comes with AGH to see if it works. If it does, then start adding one restriction at a time to see which one is causing problems. Will keep you posted on it.

```
[Unit]
Description=AdGuard Home: Network-level blocker
ConditionFileIsExecutable=/opt/AdGuardHome/AdGuardHome
After=syslog.target network-online.target

[Service]
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PermissionsStartOnly=true
User=aghome
Group=aghome
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/opt/AdGuardHome/AdGuardHome "-c" "/opt/AdGuardHome/AdGuardHome.yaml"
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelModules=yes

WorkingDirectory=/opt/AdGuardHome

StandardOutput=file:/var/log/AdGuardHome.out
StandardError=file:/var/log/AdGuardHome.err
Restart=always
RestartSec=10
EnvironmentFile=-/etc/sysconfig/AdGuardHome

[Install]
WantedBy=multi-user.target
```

**Comment by emlimap** [comment]
So managed to semi reliably reproduce the lock up where query log UI and the file stops getting updated. 

Steps to reproduce:

1. Brand new Ubuntu 18.04.4 installation. You might not need a new install but used one to rule out any conflicts and also keep the logs to minimum by avoiding non test queries.
2. Install AGH as service and go through setup process. Installed it in `/opt/AdGuardHome/` path but didn't change any of the default settings. AGH Version: v0.101.0-108-ge24e
3. Generate some DNS traffic for about 5 minutes. It is somewhere between 3 & 5 minutes where first temporary lock up happens but it recovers within 5 or 10 mins at worst. If you then start to generate traffic again, it locks up for longer period this time. Below is the quick script I used to generate about 5 DNS requests in loop with a second interval between runs. It will run until you press Ctrl + C to stop.

```sh
#!/bin/sh
while :
do
  dig +short google.com @127.0.0.1
  dig +short gmail.com @127.0.0.1
  dig +short microsoft.com @127.0.0.1
  dig +short github.com @127.0.0.1
  dig +short apple.com @127.0.0.1
  sleep 1
done
```
Step 4: Periodically keep refreshing the UI so you can see when it stops updating.

Below are the logs. They just contain test queries so posting it here. Started the DNS query script around 23:13. Ran it until shortly after 23:18 when I noticed that query log UI stopped updating. The UI updated shortly after that so started the script again and it locked up straight away with no updates since 23:17. It has been about 40 mins since I stopped running the script and the query log still shows log from 23:17:09 as the latest.

[AGH-debug-log.zip](https://github.com/AdguardTeam/AdGuardHome/files/4490268/AGH-debug-log.zip)
[querylog.zip](https://github.com/AdguardTeam/AdGuardHome/files/4490270/querylog.zip)

**Comment by szolin** [comment]
> I presume that Adguard home holds the latest queries logs in memory before they are accumalated for certain period and written to disk. Is this what is queried when you run a query with filters?

both memory entries and entries in file are queried.

> How often does Adguard home supposed to sync query logs to disk?

every `querylog_size_memory: 1000`

> Does query log UI by default displays the contents of the query log file?

UI displays entries from memory and the file

I'll check what's happening in beta.

**Comment by ameshkov** [comment]
@szolin could it be that it starts loading data from the wrong file?

**Comment by szolin** [comment]
@emlimap Thank you!  This bug appeared in v0.101.  But in v0.101 memory cache was disabled.  It's re-enabled now in beta.
