### ISSUE TITLE
AdGuardHome built from tar.gz sources has an empty version string

### ISSUE THREAD

**Issue by zhulik** [AdguardTeam/AdGuardHome#1590]
### Issue Details

Steps to reproduce:
1. Download the source code using the [tar.gz](https://github.com/AdguardTeam/AdGuardHome/archive/v0.101.0.tar.gz) archive
2. Run `make` to build it

the very first line of output will be 
`fatal: not a git repository (or any of the parent directories): .git`
but the build will be successful.

After that run the server and open `/control/status` in the browser.

* **Version of AdGuard Home server:** 
  * 0.101.0
* **How did you setup DNS configuration:** 
  * does not matter
* **If it's a router or IoT, please write device model:** 
  * does not matter
* **Operating system and version:** 
  * Arch Linux

### Expected Behavior
The response contains `version: "0.101.0"`

### Actual Behavior
The response contains `version: ""`

### Screenshots

<details><summary>Screenshot:</summary>
![Screenshot_20200415_221811](https://user-images.githubusercontent.com/287062/79384537-5a34f300-7f67-11ea-936b-bd9048293066.png)

</details>

**Comment by ameshkov** [comment]
> Download the source code using the tar.gz archive

The problem is that tar.gz archive does not contain `.git` metadata which is used to set the version field.

**Comment by zhulik** [comment]
@ameshkov exactly, but this is not an excuse, missing version causes misbehaviors: the frontend constantly shows me notification about the new version available, and it's impossible to integrate adguard with home assistant because it expects a valid version string.

**Comment by ameshkov** [comment]
@zhulik well, but why can't you do `git clone` instead of downloading `tar.gz`?

**Comment by zhulik** [comment]
@ameshkov of course I can, but building software from `.tar.gz` is a pretty much natural way. In case if you don't support it, please, remove source tarballs from releases because they are broken

**Comment by ameshkov** [comment]
@zhulik they're added automatically by Github, we can't do anything with them.

**Comment by zhulik** [comment]
@ameshkov you can make them work as expected. The easiest way will be using a simple text file with current version. In case if `.git` is missing the version should be read from this file.

**Comment by Aesculapius** [comment]
This also appears to be the case when installed through snap on Ubuntu - that install suffers from the same incompatibility to integrate in home-assistant.

**Comment by ameshkov** [comment]
@Aesculapius 

> This also appears to be the case when installed through snap on Ubuntu - that install suffers from the same incompatibility to integrate in home-assistant.

Do you mean that you don't see the version string there?

It seems that the reason for that is different. The snap version comes with the built-in auto-update feature disabled, and that's why the whole block with the version and "update" button is hidden. We'd better fix this indeed: https://github.com/AdguardTeam/AdGuardHome/issues/1726
