### ISSUE TITLE
Support for disabling DNS caching

### ISSUE THREAD

**Issue by xiaoqingfengATGH** [AdguardTeam/AdGuardHome#1591]
we use adguardhome for ad filtering，as the primary dns of lan，there are several dns behind adguardhome , run as adguardhome upstream dns and all these upstream have dns cache enabled.
In this case, the DNS cache of adguardhome is meaningless.

At present, adguardhome is unable to turn off DNS cache. I tried to set "cache_size" to 0 in yaml, but it does not work.

Would adguardhome allow to turn off dns cache in the future version?

**Comment by ameshkov** [comment]
> I tried to set "cache_size" to 0 in yaml, but it does not work.

Hmm, this should disable DNS cache. @szolin could you please check what's wrong with it/
