### ISSUE TITLE
Filterlists not updating

### ISSUE THREAD

**Issue by TheHellSite** [AdguardTeam/AdGuardHome#1592]
I installed AdGuardHome a few days ago on a clean install of OpenWrt x86 release.

I had it working before the clean install, but now my filterlists don't update and I get the error message below when accessing the webinterface. A manual update of the filterlists takes way longer than before and still displays zero rules for each list.
![error](https://user-images.githubusercontent.com/34900685/79429414-c34c5300-7fc7-11ea-9a3a-2d1dd5b899f4.png)

**Comment by KamistixX** [comment]
Also, the default **hpHosts - Ad and Tracking servers only** filterlist (url : https://hosts-file.net/ad_servers.txt) does not get updated either.

From the logs : 

`2020/04/16 07:33:05 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: couldn't dial to 3.234.198.254:443, cause: dial tcp 3.234.198.254:443: connect: connection timed out

2020/04/16 07:33:05 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: Get https://hosts-file.net/ad_servers.txt: couldn't dial to 3.234.198.254:443, cause: dial tcp 3.234.198.254:443: connect: connection timed out

2020/04/16 08:33:10 [info] Got status code 404 from URL https://hosts-file.net/ad_servers.txt, skipping

2020/04/16 08:33:10 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: got status code != 200: 404`

**Comment by ameshkov** [comment]
Most likely it's not being updated because you have that broken filter list enabled.

**Comment by TheHellSite** [comment]
My problem has nothing to do with that filterlist. After deleting it from the lists and restarting the adguardhome service it still does not update my filterlists! The red error message also still appears.

**Comment by ameshkov** [comment]
Ah, sorry, I misinterpreted the issue. According to the error message that I am seeing, the problem is that your device lacks root certificate that is used on `static.adguard.com`

**Comment by TheHellSite** [comment]
So how do I resolve this?

**Comment by TheHellSite** [comment]
I reinstalled AdGuardHome and now the messages says this:

"Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns10.quad9.net:443/dns-query', cause: Get https://dns10.quad9.net:443/dns-query?dns=LYEBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ: x509: certificate signed by unknown authority | 502"

**Comment by ameshkov** [comment]
What OS do you have? Make sure that the root certs are up to date there

**Comment by TheHellSite** [comment]
I have OpenWrt 19.07.2 x86

**Comment by TheHellSite** [comment]
I figured it out...

I had to install "ca-bundle ca-certificates" packages.

**Comment by heaion** [comment]
> 你有什么操作系统？确保根证书在那里是最新的

后面如果再有问证书相关的问题，直接让他安装楼下说的ca-bundle和ca-certificates两个包，重启，就可以解决问题，亲身经历。
