### ISSUE TITLE
Support DNS IPv6

### ISSUE THREAD

**Issue by MorgothSauron** [AdguardTeam/AdGuardHome#1595]
On a PiHole it is possible to configure it to listen for both IPv4 and IPv6. This way there is a DNS available for both protocol. I tried AdGuard Home on Pi4 (ARM64) and it's the only feature is see missing.

I know that IPv6 is not commonly used in home network, but it would be useful for those that do use IPv6. Currently I'm stuck with no DNS for IPv6 (PiHole + Docker + IPv6 = total mess). It would be great if AG Home could listen on both IPv4 and IPv6 port for DNS queries.

**Comment by evilvibes** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/779

**Comment by ameshkov** [comment]
Well, you can configure it to listen to 0.0.0.0, isn't that what you're looking for?

**Comment by MorgothSauron** [comment]
> Well, you can configure it to listen to 0.0.0.0, isn't that what you're looking for?

`0.0.0.0` is IPv4 (`INADDR_ANY`). Listening on all interface is `::` in IPv6 (`INADDR6_ANY`)
I deleted the config file and it only suggest IPv4 addresses.

**Comment by ameshkov** [comment]
Actually `0.0.0.0` will cover both v4 and v6. Also, I'd suggest using the latest beta version if you want AGH to work with multiple net interfaces properly.

**Comment by MorgothSauron** [comment]
You are correct. I configured it to listen on all interfaces for the DNS. I can query using both the IPv4 and IPv6:
- IPv4: `dig www.perdu.com @192.168.0.12`
- IPv6: `dig www.perdu.com @2a01:abcd:1234:5678::1234`

In both case I get the correct client IP in the log, something that doesn't work well with PiHole running inside Docker
