### ISSUE TITLE
Error in make project

### ISSUE THREAD

**Issue by metao1** [AdguardTeam/AdGuardHome#1596]
While executing `make ` command I get this error:
go: github.com/AdguardTeam/dnsproxy@v0.26.1: reading github.com/AdguardTeam/dnsproxy/go.mod at revision dnsproxy: unknown revision v0.26.1

I know `dnsproxy@v0.26.1` exists but this error stopped me from creating the project

**Comment by ameshkov** [comment]
Hm, that's weird, check that you're using Go v1.14

**Comment by metao1** [comment]
This is my go info `go version go1.14.2 darwin/amd64`

**Comment by metao1** [comment]
I confirm that it was my Intellij Idea problem. I ran in different environment and it worked
