### ISSUE TITLE
AdGuard Home in openwrt18.06 ipv4 Internet dead

### ISSUE THREAD

**Issue by kai456789** [AdguardTeam/AdGuardHome#1598]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details
use AdGuard Home port 53  but ipv6 Internet OK  ipv4 Internet dead

turn off openwrt lan dhcp server
then use AdGuard Home dhcp server ipv4 and ipv6  Internet ok

* **Version of AdGuard Home server:**
0.101.0
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
ACRH17
* **Operating system and version:**
  openwrt 18.06 by lean

**Comment by ameshkov** [comment]
> ipv4 Internet dead

Could you please explain what do you mean by dead?

Try using `nslookup` to send different DNS queries and check what's the difference there
