### ISSUE TITLE
ads not blocked.

### ISSUE THREAD

**Issue by BigBobDalton** [AdguardTeam/AdGuardHome#1600]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x
![Screen Shot 2020-04-20 um 15 19 09](https://user-images.githubusercontent.com/58954090/79756059-55cb5a00-831a-11ea-9bb1-6245615469e5.png)
] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Sorry, I am not sure what the question is about. Make sure that you're using AdGuard Home as a DNS server on your PC, check the query log and see what's not blocked there.
