### ISSUE TITLE
Add response time to Query Log

### ISSUE THREAD

**Issue by mupkoo** [AdguardTeam/AdGuardHome#1601]
### Problem Description
I think that it will be really useful to see information about the response time for each request. First of all, it is just a nice statistic, and second, it can help identify slow requests.

### Proposed Solution
I can see that the response from the server includes `elapsedMs` which I think is exactly the information that needs, so I would suggest to add a column between **Response** and **Client**.

### Alternatives Considered
If you think that there will be too much information on the table, or that may be this is not something that will be liked by most of the users, an ability to set which columns you would like to have is an option, although it is more time consuming

**Comment by Archive5** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1453 https://github.com/AdguardTeam/AdGuardHome/issues/481

**Comment by ameshkov** [comment]
Yep, closed as dup.
