### ISSUE TITLE
[Feature Request] List DHCP leases

### ISSUE THREAD

**Issue by adamtal3** [AdguardTeam/AdGuardHome#1604]
### Problem Description
The main reason I installed AdGuard (previously Pi-Hole which wasn't working smoothly) is for a DHCP server (my router fails to handle my 50+ devices when it comes to DHCP and renewing leases). I'd like to be able to see the list of active leases (or even better, list of connected clients with host names).

### Proposed Solution
I've tried looking at leases.db, stats.db and sessions.db and didn't see that AdGuard is keeping track on DHCP leases except for the list of static IPs. It would be great if I could follow the DHCP process in my network somehow.

### Alternatives Considered
If there's a database file with the leases, adding a page that simply shows the contents of that database will suffice for seeing what goes on in my network.

### Additional Information
The only thing possible is adding static leases. In Pi-Hole, above the static list table, there's the actual lease table (and with a click of a button a regular lease could be added as a static lease).
I'm not sure if it's possible to keep track on which clients are still alive (maybe by querying the last DNS call they made and if it was less than X seconds ago) but that will be great to know exactly who's on the network and for how long.

**Comment by ameshkov** [comment]
Summoning @szolin here:)

**Comment by szolin** [comment]
> I'd like to be able to see the list of active leases (or even better, list of connected clients with host names).

Settings -> DHCP Settings -> section "DHCP leases"
This is the list of currently active leases, with host names.

**Comment by adamtal3** [comment]
@szolin - Hi, I'm using v0.101.0 and under Settings -> DHCP Settings this are the sections I can see:
"DHCP server (experimental!)"
"DHCP static leases"

Is the "DHCP leases" part of a future version?

If it matters, I'm using AdGuard using the hass.io adon.

**Comment by szolin** [comment]
You have to start DHCP server first.
Then you'll be able to see the current leases.

**Comment by adamtal3** [comment]
@szolin - I just did that and it does show up. Now I'm very confused as I have no idea how 50 devices got IP addresses when the DHCP on the router was set to AdGuard's IP and I didn't click on "Enable DHCP Server" up until now.

Sorry for the confusion and thanks for the quick reply.
