### ISSUE TITLE
dnsmasq-like syntax for UpstreamServer does not allow multiple domains

### ISSUE THREAD

**Issue by theovds** [AdguardTeam/AdGuardHome#1611]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.101.0 (Docker container)
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  *  Rasbian Lite

### Expected Behavior
I would like to specify multiple domains for specific domains in the UpstreamServer section. Something like: [/[domain1][/domain2]/]192.168.1.1. This should work regarding the documentation. It works for a single domain, but I don't get it to work for multiple domains.

### Actual Behavior
Error: Server "[/[domain1][/domain2]/]192.168.1.1": could not be used, please check that you've written it correctly

</details>

### Additional Information
I read the documentation both in the WebGui and here https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains, but it looks like there are differences between them. I tried multiple versions, but I don't get it to work. Please let me know the syntax to use multiple domains. 

Already tried:
[/[domain1][/domain2]/]192.168.1.1
[/[domain1]/[domain2/]]192.168.1.1
[/domain1/][/domain2/]192.168.1.1
[[/domain1/][/domain2/]]192.168.1.1

Thanks!

**Comment by ameshkov** [comment]
@szolin we should fix the documentation, these square brackets somehow made it to examples there:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#examples

@theovds the proper format is something like this: `/example.com/example.org/1.1.1.1`

**Comment by theovds** [comment]
@ameshkov this does seems not to work. I tried /example.com/example.org/1.1.1.1, but this gives me the same error.

If I use square brackets (like [/domain1/domain2/]1.1.1.1), it gives my no error, but then it I cannot resolve those domains.

**Comment by ameshkov** [comment]
Ah, my bad, we'll look into it

**Comment by ameshkov** [comment]
I am glad that it works now:)

**Comment by theovds** [comment]
Hang on, I got it to work :)
If I use square brackets (like [/domain1/domain2/]1.1.1.1), it gives my no error, and it works :)

**Comment by theovds** [comment]
Thank you! I guess that the documentation still needs to be updated to avoid confusion.

**Comment by szolin** [comment]
updated wiki
