### ISSUE TITLE
Does my DNS configuration makes sense?

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#1613]
Hi there,

I'm a bit confused about secure DNS requests and I'm not quite sure if my setup is properly configured or not and was hoping you guys could shed some light. I've read the wiki, I've researched a bit, but I'm still confused.

I have an ASUS router which uses the Tomato firmware, this firmware uses `dnsmasq` internally. To push the AdGuard Home DNS server to all my network clients (wired and Wi-Fi) I use a custom configuration like this:

```
dhcp-option-force=tag:br0,option:dns-server,192.168.0.99
dhcp-option-force=tag:br0,option6:dns-server,[fe80::211:32ff:fe7b:9a85]
dhcp-option-force=tag:br1,option:dns-server,192.168.0.99
dhcp-option-force=tag:br1,option6:dns-server,[fe80::211:32ff:fe7b:9a85]
```

This pushes the AdGuard Home DNS IPv4 and IPv6 to all clients for all my configured LANs (`br0` is the main network and `br1` is the guest Wi-Fi).

In AdGuad Home » DNS Settings » Upstream DNS Servers I use something like this:

```
tls://1dot1dot1dot1.cloudflare-dns.com
```

Assuming I don't have any device with hardcoded DNS servers (like Chromecast devices), all DNS requests coming out from all my LAN clients are encrypted with DNS-over-TLS, correct? Which means, no one outside of my network is able to see what sites I'm visiting, correct?

Now, I use Firefox and recently Mozilla pushed an update where DNS-over-HTTPS was enabled by default pointing to Cloudflare, effectively overriding my network configuration and bypassing my AdGuard Home DNS server, correct? I disabled it though:

![image](https://user-images.githubusercontent.com/96476/80087343-de343f80-8552-11ea-9907-bb7d9bc482a5.png)

This means that Firefox (at least on this machine) is using AdGuard Home DNS server again, correct?

One last question... Is there any reason, at all, for configuring DNS-over-HTTPS/TLS in AdGuard Home and configure my devices/OS/applications/whatever to use that, if possible, instead of the default IPv4/IPv6 method (which is not encrypted)? I don't see a reason to encrypt traffic inside my home network but would love to understand if I'm making the right choice or not.

**Comment by ameshkov** [comment]
> all DNS requests coming out from all my LAN clients are encrypted with DNS-over-TLS, correct? 

yes

> Which means, no one outside of my network is able to see what sites I'm visiting, correct?

your ISP still sees IP addresses and stuff, but they don't see DNS queries

> effectively overriding my network configuration and bypassing my AdGuard Home DNS server, correct?

AdGuard Home implements Mozilla's canary domain: https://support.mozilla.org/en-US/kb/configuring-networks-disable-dns-over-https

So, in theory, you can change nothing in FF settings, it will still use AGH DNS.

> I don't see a reason to encrypt traffic inside my home network but would love to understand if I'm making the right choice or not.

I don't see it either. DOH/DOT makes sense when you host AGH outside of your home network.

**Comment by rfgamaral** [comment]
@ameshkov Perfect, that's what I wanted to hear 😄 It was always bugging me that I had some misconfiguration here and there but I guess I don't need to change anything in my network configuration.

Thank you so much. Keep up the good work and stay safe 👍
