### ISSUE TITLE
AdgardHome PrivateDNS not working

### ISSUE THREAD

**Issue by danwhit123** [AdguardTeam/AdGuardHome#1616]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * Per Device
* **If it's a router or IoT, please write device model:**
  * AWS Server
* **Operating system and version:**
  * Ubuntu Server 18.04 LTS

### Expected Behavior
Be able to put my domain in as my Private DNS on android phone

### Actual Behavior
Fails to connect

### Additional Information
All my nameservers are configured. i can access the AdguardHome page via my domain on wifi and off wifi and works okay. I have a Valid SSL cert on the site. However, when i try and add the private DNS to my phone is always fails to connect.

**Comment by ibksturm** [comment]
hi @danwhit123 did you open ports 443 (https) on firewall on server & router?

**Comment by danwhit123** [comment]
> hi @danwhit123 did you open ports 443 (https) on firewall on server & router?

Yes port 443, 80, 53 and 853

**Comment by ibksturm** [comment]
hi @danwhit123 open port 53 isnt a good idear cause of ddos attacks and in some countrys (don‘t know) theres also restrictions

what kind of setup do you have?

did you see some traffic with

`txpdump port 443 -q `

**Comment by danwhit123** [comment]
> hi @danwhit123 open port 53 isnt a good idear cause of ddos attacks and in some countrys (don‘t know) theres also restrictions
> 
> what kind of setup do you have?
> 
> did you see some traffic with
> 
> `txpdump port 443 -q `

I thought port 53 would need to be open to make the DNS queries?

I am using an AWS EC2 instance. ran the command on my instance and tried to connect via PrivateDNS and nothing comes up

**Comment by danwhit123** [comment]
yes i did see traffic
