### ISSUE TITLE
Add support for cloudflare

### ISSUE THREAD

**Issue by eduaddad** [AdguardTeam/AdGuardHome#1618]
Add support for cloudflare

**Comment by ameshkov** [comment]
What do you mean?

**Comment by eduaddad** [comment]
> What do you mean?

Add support to keep the ip confidential and protected against Denial of Service Attack

**Comment by ameshkov** [comment]
Well, there's nothing we need to do for that. You can just use Cloudflare on your own and configure it to proxy your AG Home domain.

**Comment by eduaddad** [comment]
when I do the Proxy through AdGuard I can't connect

**Comment by Archive5** [comment]
Duplicate of #1575

**Comment by ameshkov** [comment]
Yep, it is.

@eduaddad you need a public static IP address for that. If you don't have it, you may want to look at the VPS setup: https://github.com/AdguardTeam/AdGuardHome/wiki/VPS
