### ISSUE TITLE
Safe guard from dns attack.

### ISSUE THREAD

**Issue by shimuldn** [AdguardTeam/AdGuardHome#1621]
### Problem Description

Using as open DNS for my personal use. Getting unknown user logs. Blocked many IPs. Now i am getting many DNS request logs for a single site. blocked the website and the requester IP but the spammer using new IP all the time. IPs from USA, China, and a few other countries. Most of IPs from cloud service providers.

### Proposed Solution

If the client sends requests only for a single domain or very few domains again & again block the IP automatically and a selection automatic blocked client IPs. Maybe send an email also to the admin, can use the NODEJS mailer.

**Comment by lordraiden** [comment]
You need a firewall in front of adguard DNS, is a suicide expose it to the internet without one.
Then in the FW you can do whatever you want, like block via GEO IP.
You can also enable only DoH and disable DNS (53) so you will be the only one able to do requests because you have the cert.

**Comment by shimuldn** [comment]
Thank you for the reply.
How can i disable the 53 port and use? As soon as i disabled 53 DNS not working.

**Comment by ameshkov** [comment]
> You need a firewall in front of adguard DNS, is a suicide expose it to the internet without one.

Well, not really, I run my own public resolver with no problems.

What you need to do is add this domain to disallowed domains: settings -> dns settings -> scroll down to disallowed domains.

**Comment by shimuldn** [comment]
> disallowed domains

@ameshkov Already added. But the same things happening again & again. Always different domains & different IPs.

**Comment by ameshkov** [comment]
@shimuldn is there anything common in these domain names? You can add wildcards there,

**Comment by shimuldn** [comment]
@ameshkov Nope. Always different domains.

**Comment by ameshkov** [comment]
@shimuldn could you please provide a couple of examples of these DNS queries?

domain names, query types, IP addresses

**Comment by shimuldn** [comment]
> If the client sends requests only for a single domain or very few domains again & again block the IP automatically and a selection automatic blocked client IPs

I think this will help. It also can be optional.

**Comment by ameshkov** [comment]
I am trying to figure out what criteria we can use, that's why I am asking for example

**Comment by shimuldn** [comment]
@ameshkov I have the only a recent log, i don't keep them for long.
TYPE RRSIG
IP address many of them Comcast Cable Communications, cable.virginm.net, ICSI, AT&T Corp.,  CA, Calgary Shaw Communications Inc,  US, Greenwood Village Charter Communications, Inc,  CA, Toronto
Amazon Technologies Inc
CenturyLink Communications, LLC
Maxis Broadband Sdn Bhd

And many more from China, Japan etc.
If you need a full log can send your email or pm

**Comment by ameshkov** [comment]
I don't need the full log, just the domain name and query type, that would be enough.

So, in this case, it was `cable.virginm.net` and `RRSIG`, right? How many queries have been sent by that client?

**Comment by shimuldn** [comment]
Domain name pizzaseo.com
Type RRSIG
Client ip Comcast Cable Communications, cable.virginm.net, ICSI, AT&T Corp., CA, Calgary Shaw Communications Inc, ....

**Comment by ameshkov** [comment]
> 332474 blocked request

Mm, how do you see it as blocked? If the domain is added to disallowed, AdGuard Home drops DNS requests and doesn't even try to respond to them or record them to stats.

Generally, what bothers me about this request is that it'd be rather hard to distinguish DNS amplification from legit queries. For instance, there are devices that query just a single domain name all the time.

**Comment by shimuldn** [comment]
I have not been using the disallowed feature for this attack. Removed the domain from the disallowed list and within few minutes. 

> 332474 blocked request
Now 383845 blocked request
As soon as removed from the disallowed list getting log for request from many clients IPs. An attacker using many IPs to attack so automatically bypass the of set limit restriction. Also always monitoring the DNS server is an extra headache.

> there are devices that query just a single domain name all the time.

There is already "allowlists" option for such devices. This feature can be optional, need to activate manually. An email notification option to send an email for such auto-blocking.

Do you think this feature request unnecessary?
Thank you for your time

**Comment by shimuldn** [comment]
@ameshkov Is there any possibility of this feature?

**Comment by ameshkov** [comment]
@shimuldn filed a new feature request for that: https://github.com/AdguardTeam/AdGuardHome/issues/1665

Please check what I propose there.
