### ISSUE TITLE
Question install AdGuardHome on GCP 

### ISSUE THREAD

**Issue by gluaykung** [AdguardTeam/AdGuardHome#1623]
I'm try to install AdGuardHome on GCP. I'm create VM instances with Debian 9
then I'm install AdGuardHome follow this guide.  [https://github.com/AdguardTeam/AdGuardHome/wiki/VPS](url)

And I'm stuck at `host doubleclick.net 127.0.0.1`

`ratapops@instance-adguard:~/AdGuardHome$ sudo ./AdGuardHome -s install`
`2020/04/26 13:43:42 [info] Service control action: install`
`2020/04/26 13:43:42 [info] Service has been started`
`2020/04/26 13:43:42 [info] Almost ready!`
`AdGuard Home is successfully installed and will automatically start on boot.`
`There are a few more things that must be configured before you can use it.`
`Click on the link below and follow the Installation Wizard steps to finish setup.`
`2020/04/26 13:43:42 [info] AdGuard Home is available on the following addresses:`
`2020/04/26 13:43:42 [info] G to http://127.0.0.1:3000o`
`2020/04/26 13:43:42 [info] Go to http://10.138.0.3:3000`
`2020/04/26 13:43:42 [info] Action install has been done successfully on linux-systemd`
`ratapops@instance-adguard:~/AdGuardHome$ host doubleclick.net 127.0.0.1`
`;; connection timed out; no servers could be reached`

I try to go to http://10.138.0.3:3000 but I'm can't access 

for this i try to change 127.0.0.1 to 1.1.1.1
` ratapops@instance-adguard:~/AdGuardHome$ host doubleclick.net 127.0.0.1`
`;; connection timed out; no servers could be reached`
`ratapops@instance-adguard:~/AdGuardHome$ host doubleclick.net 1.1.1.1`
`Using domain server:`
`Name: 1.1.1.1`
`Address: 1.1.1.1#53`
`Aliases: `
`doubleclick.net has address 172.217.3.206`
`doubleclick.net has IPv6 address 2607:f8b0:400a:809::200e`
`doubleclick.net mail is handled by 10 aspmx.l.google.com.`
`doubleclick.net mail is handled by 30 alt2.aspmx.l.google.com.`
`doubleclick.net mail is handled by 20 alt1.aspmx.l.google.com.`
`doubleclick.net mail is handled by 50 alt4.aspmx.l.google.com.`
`doubleclick.net mail is handled by 40 alt3.aspmx.l.google.com.`

Do I need too set anything else?

Thank you :)

**Comment by ameshkov** [comment]
> I try to go to http://10.138.0.3:3000 but I'm can't access

This is crucial to the admin panel and setup AdGuard Home.

However, `10.138.0.3` is from a private range. It seems that your VM does not have a public IP address and that's why you can't open it in the browser.

**Comment by gluaykung** [comment]
[image: image.png]
[image: image.png]
I'm try 35.197.79.41:3000 too. but still not work. Do you have any
suggestion. 😅

**Comment by ameshkov** [comment]
@gluaykung hmhm, not too many. You should check iptables rules and make sure that connections to port 3000 are possible
