### ISSUE TITLE
'Blocked Services' settings reset

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#1624]
### Issue Details
When using Blocked Services, all the enabled/blocked toggles are reset back to default (disabled). The user then is required to remember that every update causes the settings to be reset and must go back in and re-enable the services to block.

Ideally could we have the blocked services remembered?

* **Version of AdGuard Home server:**
  *  v0.101.0-144-g08b0
* **How did you setup DNS configuration:**
  *  Raspberry Pi 3 B+, DHCP enabled
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 3 B+
* **Operating system and version:**
  *  Latest Raspbian via apt

### Expected Behavior

Blocked Services settings are retained.

### Actual Behavior

Blocked Services settings are forgotten.

**Comment by ameshkov** [comment]
> When using Blocked Services, all the enabled/blocked toggles are reset back to default (disabled). The user then is required to remember that every update causes the settings to be reset and must go back in and re-enable the services to block.

Most likely this is a bug of update.

What version were you using before updating?

**Comment by planet0** [comment]
Wow! That was super fast, thanks @ameshkov @szolin @adguard etc.
