### ISSUE TITLE
[Feature Request] "Drill down" to activity reports

### ISSUE THREAD

**Issue by rodalpho** [AdguardTeam/AdGuardHome#1625]
I would like the following:

1) Click client names everywhere in the UI to show the query log filtered to only that client. These hosts are currently not clickable, and the only way to get this info is to go to the query log and type in the IP address-- the host doesn't match there.

For example, I could click on my wifi lightbulb's hostname in the dashboard under Top Clients. 

2) Similarly, drill down by queried or blocked domain to see which clients tried to lookup that specific host.

Similarly, I could click on "ssl.google-analytics.com" under blocked domains in the dashboard to see a filtered query log for just that domain.

**Comment by Archive5** [comment]
Related https://github.com/AdguardTeam/AdGuardHome/issues/1368 https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-515673586

**Comment by rodalpho** [comment]
Yes those are approaching the same problem, for sure. I do think my solution is more elegant; you see a host or IP and you click on it to drill down. No need for extra UI cruft there, although #481 request for calendar ranges makes a lot of sense in addition to my idea.

**Comment by lordraiden** [comment]
Related to #1502

**Comment by rodalpho** [comment]
I'm running v103.2 and I can't see where to drill down. When I click on a host in the UI on the dashboard or the query log nothing happens, it isn't a clickable link.

**Comment by ameshkov** [comment]
Click on the number

**Comment by rodalpho** [comment]
Ahh, the requests count! That does work, thank you. It may have an issue with being discoverable, however!
