### ISSUE TITLE
DNS Friendly name resolver

### ISSUE THREAD

**Issue by BigBobDalton** [AdguardTeam/AdGuardHome#1626]
I have an issue that I cannot seem to resolve, or perhaps I just don't know where to place the settings.  My AdguardHome is running on a Raspberry.pi with the host name of Raspberry.pi.  I would like to know if I can get Adguardhome to resolve this name as a DNS on my network.  The reason is that just by adding the IP address requires me to place the IP address and associate port number e.g. 3000 to open the web gui on my browser.  It wold be more elegant to use the name so that I could just type in http://raspberry.pi:3000

Honestly, dnsmasq running would resolve this, so would dns-crypt, but the Adguardhome application should have some prevision for this to work. 

The only DNS friendly name that I can get my network to pull is from my router, even the rebind protection fails, whereby that worked flawlessly with the competitions application.

* **Version of AdGuard Home server:**
v0.101.0

Thank you in advance for your help

* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by emlimap** [comment]
You should be able to do this using DNS Rewrites. You can access it by going to Filters -> DNS Rewrites

Add a new rewrite for `raspberry.pi` with the IP address you want it to point to. 

You should then be able to access http://raspberry.pi:3000/

**Comment by BigBobDalton** [comment]
Perfect

 

Thank you soooo much!! 

 

Von: emlimap <notifications@github.com>
Antworten an: AdguardTeam/AdGuardHome <reply@reply.github.com>
Datum: Montag, 27. April 2020 um 22:16
An: AdguardTeam/AdGuardHome <AdGuardHome@noreply.github.com>
Cc: BigBobDalton <bob@dalton.li>, Author <author@noreply.github.com>
Betreff: Re: [AdguardTeam/AdGuardHome] DNS Friendly name resolver (#1626)

 

You should be able to do this using DNS Rewrites. You can access it by going to Filters -> DNS Rewrites

Add a new rewrite for raspberry.pi with the IP address you want it to point to.

You should then be able to access http://raspberry.pi:3000/
