### ISSUE TITLE
[Documentation] Known provider wiki for provider ibksturm needs IP and dnscrypt pin updated

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#1627]
Known providers wiki has the old IP and dnscrypt pin for ibksturm-dns

https://kb.adguard.com/en/general/dns-providers#ibksturm-dns

Hostname `ibksturm.synology.me` now resolves to `83.77.85.7` instead of `178.82.102.190`. Also, the dnscrypt pin needs to be updated to 
```
sdns://AQcAAAAAAAAADzgzLjc3Ljg1Ljc6ODQ0MyDBz1dQALBbwmxiH17PmqJWCs6_AH6-yzp_9LIN4LQ57hgyLmRuc2NyeXB0LWNlcnQuaWJrc3R1cm0
```
Source: https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/public-resolvers.md#ibksturm

Official website still points to old pin though.

**Comment by ibksturm** [comment]
hi @emlimap 

thanks for feedback, now i know what i‘ve forgott 🤔

i will look this week to correct it

greets

**Comment by ibksturm** [comment]
@emlimap 
first a realy realy big thank you for bugreport. i'm running dns server on freetime an in last year, i've got a lot of other project at work an private live... so updates are on merging list, let's whait for the russias @ameshkov :)

so i think we can clouse this thread

**Comment by emlimap** [comment]
@ibksturm Thank you for running a DOH/DOT/Dnscrypt server. I was looking for a server that supported both opennic and encrypted DNS. Your one supported both.

While you are at the task of updating documentation, you might want to update the DNSCrypt pin on your website `https://ibksturm.synology.me/`. It still points to the old one.

Agree with you, this can be closed. You already have a PR open to address this and this is a bug report for documentation repo as opposed to here. Didn't realize documentation was in a repo. I guess in the future, I can send a PR myself :)

**Comment by ibksturm** [comment]
> @ibksturm Thank you for running a DOH/DOT/Dnscrypt server. I was looking for a server that supported both opennic and encrypted DNS. Your one supported both.
> 
> While you are at the task of updating documentation, you might want to update the DNSCrypt pin on your website `https://ibksturm.synology.me/`. It still points to the old one.
> 
> Agree with you, this can be closed. You already have a PR open to address this and this is a bug report for documentation repo as opposed to here. Didn't realize documentation was in a repo. I guess in the future, I can send a PR myself :)

@emlimap:
Your'e Welcome :)

b) i'd updated my website right now... children are in bed 

c) maybe you've got time and put some more doh / dot / dnscrypt server on their serverlist. sadly i'm running out of time cause of COVID-19 :(

**Comment by ibksturm** [comment]
> Agree with you, this can be closed. You already have a PR open to address this and this is a bug report for documentation repo as opposed to here. Didn't realize documentation was in a repo. I guess in the future, I can send a PR myself :)

if you need help with sdns stamps, look:

https://play.golang.org/p/fACN5hsChEG
https://dnscrypt.info/stamps

**Comment by emlimap** [comment]
@ibksturm Thanks for those links. Will try to contribute wherever I can. Looks like you beat me to it on some changes and some haven't been deployed.

**Comment by ibksturm** [comment]
@emlimap rockn roll :)
