### ISSUE TITLE
Fastest IP Address checkbox

### ISSUE THREAD

**Issue by drzulus** [AdguardTeam/AdGuardHome#1629]
I am running the latest version

### Issue Details

* **Version of AdGuard Home server:**
   v0.101.0-144-g08b0
* **How did you setup DNS configuration:**
  Router Keenetic Ultra KN1810
* **Operating system and version:**
KeeneticOS 3.4 Beta 2

### Expected Behavior
Enable checkbox Fastest IP Address 
### Actual Behavior
Internet freezing, system load about 100%, web interface stop answering

</details>

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by drzulus** [comment]
https://pastebin.com/HPBsJQkH

**Comment by ameshkov** [comment]
@drzulus the problem is that this is not a verbose-level log. Could you please configure AG Home as it's described in my previous message?

**Comment by drzulus** [comment]
https://www.filehosting.org/file/details/864456/adguard.log

**Comment by drzulus** [comment]
[adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/4550464/adguard.log)

**Comment by ameshkov** [comment]
@drzulus got them, thank you! Removed the comments just in case as the logs may contain sensitive data.

**Comment by ameshkov** [comment]
@drzulus according to the log at some point queries to the browsing security start to time out, and I don't fully understand why it happens with "fastest IP address" enabled only.

Here's what I see in the log:
```
2020/04/29 07:55:08 793#2890 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): dialer failed to initialize connection to 176.103.130.132:443, in 2153 milliseconds, cause: dial tcp 176.103.130.132:443: i/o timeout
```

It was not happening earlier in the log:
```
2020/04/28 14:24:18 793#71 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): dialer has successfully initialized connection to 176.103.130.132:443 in 43 milliseconds
```

Are you sure the issue is caused by "fastest IP" and not by some other reason?

**Comment by drzulus** [comment]
I am fully sure, because it begin only if checkbox is active. If if uncheck it, cpu load returns to 10-15% and internet stop freezing and web interface of AdGuardHome become responsible.

**Comment by drzulus** [comment]
![Screenshot_20200429_105547](https://user-images.githubusercontent.com/64477313/80582508-8183c980-8a17-11ea-93a7-6e537c0fe06a.png)

**Comment by ameshkov** [comment]
When this box is enabled, AdGuard will query ALL your upstream servers at the same time, and you have 10 of them. This may be CPU intensive if you are using encrypted resolvers only.

Just in case, try reducing their number, keep 2 or 3. Is there any change?

**Comment by drzulus** [comment]
I am leave only :
[/kontakt/]10.114.87.250
tls://dns.quad9.net
tls://dns.google
tls://1.1.1.1
And still nothing progress.
And i downgrade to previous beta version, and it still not helping

**Comment by drzulus** [comment]
If i kill process AGH and run service again, for several times it helps, but after reboot router its 100% freezes internet due overload processor of router.

**Comment by ameshkov** [comment]
@drzulus could you please share you AdGuardHome.yaml with me in private? My email is `am@adguard.com`

**Comment by drzulus** [comment]
Ready!

**Comment by drzulus** [comment]
I was disable all tls and https servers, leave only plain dns and now it's ok
I was setup AdGuardHome on my VPS and use next scheme: my router AGH plain dns ---> my VPS AGH tls+https dns ---> internet.
