### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ttrepper** [AdguardTeam/AdGuardHome#1630]
AdGuard Home - 0.101.0

DNS-Blocking List: Link broken for AdAway
https://adaway.org/hosts.txt <----- 404

Pls see screenshot. 

Thanks a lot in advance,
Thomas

![Bildschirmfoto 2020-04-28 um 15 21 08](https://user-images.githubusercontent.com/3026863/80492225-02818900-8964-11ea-8835-4a064b14fafa.jpg)

**Comment by ameshkov** [comment]
Yep, we'll remove that list from the default lists in the next update
