### ISSUE TITLE
Docker execution `AdGuardHome.yaml` not created again after deletion

### ISSUE THREAD

**Issue by Darcidride** [AdguardTeam/AdGuardHome#1633]
Hi,
I just noticed that the `AdGuardHome.yaml` is only created once, not a second time

In my use case, i did a pull of the image, and then a run with these volumes parameters :
```
docker run --name adguardhome-v0.101.0 \
	-v /opt/adguardhome/work:/opt/adguardhome/work \
	-v /opt/adguardhome/conf:/opt/adguardhome/conf \
	-p 32053:53/tcp \
	-p 32053:53/udp \
	-p 32067:67/udp \
	-p 32068:68/tcp \
	-p 32068:68/udp \
	-p 32080:80/tcp \
	-p 32443:443/tcp \
	-p 32853:853/tcp \
	-p 32000:3000/tcp \
	-d adguard/adguardhome:v0.101.0
```
I run this and it was working, i was on the install screen...
After that, I noticed I wanted to change the DNS master port from 32053 external to 53 external, so I did the tweak in the docker run command

```
docker run --name adguardhome-v0.101.0 \
	-v /opt/adguardhome/work:/opt/adguardhome/work \
	-v /opt/adguardhome/conf:/opt/adguardhome/conf \
	-p 53:53/tcp \
	-p 53:53/udp \
	-p 32067:67/udp \
	-p 32068:68/tcp \
	-p 32068:68/udp \
	-p 32080:80/tcp \
	-p 32443:443/tcp \
	-p 32853:853/tcp \
	-p 32000:3000/tcp \
	-d adguard/adguardhome:v0.101.0
```
 
After a `docker stop && docker rm` and then a `docker run` again, the port wasn't changed. (it was stuck to 32053), I check the local `AdGuardHome.yaml` configuration file and noticed that the port was still 32053, not replaced.

Then I deleted the `AdGuardHome.yaml` because I was wondering this file will be created again at the next `docker run` execution, but it unfortunately wasn't the case :(

Some starting logs :
```
adguardhome@NAS01:/opt/adguardhome$ docker logs adguardhome-v0.101.0
2020/04/28 16:08:06 [error] Couldn't read config file /opt/adguardhome/conf/AdGuardHome.yaml: open /opt/adguardhome/conf/AdGuardHome.yaml: no such file or directory
2020/04/28 16:08:06 [info] AdGuard Home, version v0.101.0, channel release
, arch linux amd64%!(EXTRA string=)
2020/04/28 16:08:06 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html 
2020/04/28 16:08:06 [info] AdGuard Home is available on the following addresses:
2020/04/28 16:08:06 [info] Go to http://127.0.0.1:3000
2020/04/28 16:08:06 [info] Go to http://172.17.0.7:3000
```

I then tried a touch of the file, maybe something under the hood will write it for me ?
Not working again :( :
```
adguardhome@NAS01:/opt/adguardhome$ docker logs adguardhome-v0.101.0
2020/04/28 16:11:46 [info] AdGuard Home, version v0.101.0, channel release
, arch linux amd64%!(EXTRA string=)
2020/04/28 16:11:46 [info] home.upgradeSchema0to1(): called
2020/04/28 16:11:46 [info] home.upgradeSchema1to2(): called
2020/04/28 16:11:46 [info] home.upgradeSchema2to3(): called
2020/04/28 16:11:46 [fatal] DNS configuration is not a map

```
it's a YAML error this time, in fact the file is empty, so i guess nothing is writing it before starting the adguardhome process

EDIT1 : I also tried to delete the whole `/opt/adguardhome/work` and `/opt/adguardhome/work` folders, it's not neither grant the possibility to generate again the configuration file
EDIT2: Fixed by installing an adguardhome in another docker instance (computer) and then using the config yaml file for the other docker instance :) (but ti's still an issue, i guess

**Comment by ameshkov** [comment]
> Then I deleted the AdGuardHome.yaml because I was wondering this file will be created again at the next docker run execution, but it unfortunately wasn't the case :(

Well, it can't be restored because this file is the main storage for AdGuard Home configuration.

When you removed it and restart AGH, it decided that this is the first run after the installation so you need to go to install page again.

**Comment by Darcidride** [comment]
Note : Without the `AdGuardHome.yaml` file, it will use the default port, which aren't accessible for some use case (like mine) on a server, and if the webUI is necessary to generate this configuration file, it will be an issue

**Comment by ameshkov** [comment]
The default port for the DNS server or for the Web admin panel?

**Comment by janjbrand** [comment]
I'm facing a simular problem. I try to install AdGuard on a Raspberry Pi via docker, using a simular docker run command. After starting I get the following log:

`adguard-home  | 2020/06/03 11:13:25 [error] Couldn't read config file /opt/adguardhome/conf/AdGuardHome.yaml: open /opt/adguardhome/conf/AdGuardHome.yaml: no such file or directory
adguard-home  | 2020/06/03 11:13:25 [info] AdGuard Home, version v0.101.0, channel release
adguard-home  | , arch linux arm v6%!(EXTRA string=6)
adguard-home  | 2020/06/03 11:13:25 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html
adguard-home  | 2020/06/03 11:13:25 [info] AdGuard Home is available on the following addresses:
adguard-home  | 2020/06/03 11:13:25 [info] Go to http://127.0.0.1:3000
adguard-home  | 2020/06/03 11:13:25 [info] Go to http://172.19.0.5:3000`

The AdGuardHome.yaml file is not created, while the directory is available and files are created in the /work directory. I already tried to create the yaml-file myself, but after restarting the docker container the ownership is changed to root and the 'bind_host' property is changed to 0.0.0.0, so I'm not able to access the interface. How to solve this problem?

**Comment by janjbrand** [comment]
@ameshkov can you re-open this issue?

**Comment by Darcidride** [comment]
> The default port for the DNS server or for the Web admin panel?

Both, because reverted to default port, in case of missing configuration file...

But the real issue is the WebUI not accessible, because the final configuration is generated from this steps if I remember well

**Comment by ameshkov** [comment]
@janjbrand 

> The AdGuardHome.yaml file is not created, while the directory is available and files are created in the /work directory. I already tried to create the yaml-file myself, but after restarting the docker container the ownership is changed to root and the 'bind_host' property is changed to 0.0.0.0, so I'm not able to access the interface. How to solve this problem?

The `AdGuardHome.yaml` file will be created in the process of the initial setup so you need to open `http://172.19.0.5:3000`.

@Darcidride

> But the real issue is the WebUI not accessible, because the final configuration is generated from this steps if I remember well

But you can map port 3000 to a different port on your host machine, can't you?

Could you please explain why the WebUI is not accessible?

**Comment by janjbrand** [comment]
> But you can map port 3000 to a different port on your host machine, can't you?

This fixed the issue for me, thanks!

**Comment by Darcidride** [comment]
@ameshkov As I explain it earlier, I figured out how to re-generate that file by installing a container on another host and then retrieve the configuration yaml file to the host I wanted initially adguardhome to be installed

But the port forwarding is a good idea, in case you have a browser accessible from another computer and forwarding this port will grant you the possibility to do the "welcome setup" and generate the configuration yaml file on the docker host machine, it's a good workaround in my eyes

Thank you for your replies
