### ISSUE TITLE
log update slowly 

### ISSUE THREAD

**Issue by zhangmlcn** [AdguardTeam/AdGuardHome#1635]
- [x] I am running the latest version
I could not view the latest log even I refresh the search log button frequently
![image](https://user-images.githubusercontent.com/43921261/80704393-10c3d680-8b17-11ea-9bb5-1d07273e218e.png)

**Comment by zhangmlcn** [comment]
It is 20:29 now, Query log shows
![image](https://user-images.githubusercontent.com/43921261/80864178-9b413d00-8cb3-11ea-9c5b-03ae1a056ca9.png)
It can show the latest log if I search a domain name
![image](https://user-images.githubusercontent.com/43921261/80864196-c75cbe00-8cb3-11ea-94ab-df010a6d7259.png)

**Comment by chemodun** [comment]
Hi.

fully confirm
Please compare the log screen at the same time (after 23:25) with filter and without
![Снимок_2](https://user-images.githubusercontent.com/11136617/80925080-ae2c3e00-8d95-11ea-9d91-b07ef99c7cbd.PNG)
![Снимок_3](https://user-images.githubusercontent.com/11136617/80925081-aec4d480-8d95-11ea-83e3-33b585f010c8.PNG)

**Comment by emlimap** [comment]
What version of AGH are you on?

Do you want to give the latest beta a try? Similar issue was fixed on Beta. https://github.com/AdguardTeam/AdGuardHome#contributing

**Comment by chemodun** [comment]
I'm using the docker - adguard/adguardhome:latest.
Did you have a beta tag for docker ?

**Comment by theovds** [comment]
Here are the tags: https://hub.docker.com/r/adguard/adguardhome/tags
So you should use adguard/adguardhome:edge

**Comment by chemodun** [comment]
will try.
But, it's interestin - I applied the name resolution for clients by local router, as it recommened in #1632, and it's look like problem is solved

**Comment by ameshkov** [comment]
Yeah, most likely this is a duplicate and this issue is already resolved in beta
