### ISSUE TITLE
Old problem

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1638]
Openwrt x64 in mini PC,have enough CPU , RAM & disk.

2020/04/30 23:46:09 [fatal] Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:15553: socket: too many open files
2020/04/30 23:46:09 [info] Creating the UDP server socket
2020/04/30 23:46:09 [info] DNS cache is enabled
2020/04/30 23:46:09 [info] Starting the DNS proxy server
2020/04/30 23:46:09 [error] Can't initialize filtering subsystem: filterlist.NewFileRuleList(): /usr/bin/AdGuardHome/data/filters/1578719360.txt: open /usr/bin/AdGuardHome/data/filters/1578719360.txt: too many open files
2020/04/30 23:46:09 [info] Go to http://10.0.0.168:3000
2020/04/30 23:46:09 [info] Go to http://127.0.0.1:3000

 failed to lookup, cause: dial udp 101.101.101.101:853: socket: too many open files (hidden: dial udp 176.103.130.130:443: socket: too many open files), couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://example.doh.blockerdns.com:443/dns-query, cause: failed to lookup example.doh.blockerdns.com, cause: synthetic.wrap: all resolvers failed to lookup, cause: dial udp 101.101.101.101:853: socket: too many open files (hidden: dial udp 176.103.130.130:443: socket: too many open files), couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://dns.digitale-gesellschaft.ch:443/dns-query, cause: failed to lookup dns.digitale-gesellschaft.ch, cause: synthetic.wrap: all resolvers failed to lookup, cause: dial udp 101.101.101.101:853: socket: too many open files (hidden: dial udp 176.103.130.130:443: socket: too many open files), couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://doh.libredns.gr:443/dns-query, cause: failed to lookup doh.libredns.gr, cause: synthetic.wrap: all resolvers failed to lookup, cause: dial udp 101.101.101.101:853: socket: too many open files (hidden: dial udp 176.103.130.130:443: socket: too many open files), dial udp [2607:5300:120:a8a:142:4:204:111]:443: socket: too many open files, dial udp 142.4.204.111:443: socket: too many open files, dial udp 207.148.83.241:443: socket: too many open files, couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://1.1.1.1:443/dns-query', cause: Get https://1.1.1.1:443/dns-query?dns=wjEBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ: all dialers failed to initialize connection: , cause: dial tcp 1.1.1.1:443: socket: too many open files, couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://1.0.0.1:443/dns-query', cause: Get https://1.0.0.1:443/dns-query?dns=vqEBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ: all dialers failed to initialize connection: , cause: dial tcp 1.0.0.1:443: socket: too many open files) | 502

hope upgrade to fix,support more filters and open 10000 files.

**Comment by ameshkov** [comment]
https://www.tecmint.com/increase-set-open-file-limits-in-linux/
