### ISSUE TITLE
Can't change settings; "request aborted"

### ISSUE THREAD

**Issue by gogorz** [AdguardTeam/AdGuardHome#1641]
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.101.0
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 (1GB model)
* **Operating system and version:**
  * DietPi (Debian 10 Buster)

### Expected Behavior
Save the settings in (example) blocklist and general settings.

### Actual Behavior
Doesn't save or tick the checkboxes, the add blocklist "menu" freezes

### Screenshots
<details><summary>Screenshot:</summary>

https://i.ibb.co/T4X0nB5/Screenshot-from-2020-05-03-13-53-21.png

https://i.ibb.co/frCf3Q1/Screenshot-from-2020-05-03-13-56-50.png

</details>

### Additional Information
I suck at English, and sorry for the crappy formatting.

If I'm right, there are issues with POST (the http thing. i seriously suck at explaining things to people.)

https://i.ibb.co/s6wTdL1/pihol.png

**Comment by gogorz** [comment]
Looks like the same thing happens on Chrome. The `add_url` POST _request_ is `pending`.

**Comment by ameshkov** [comment]
Sorry for the late reply!

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by gogorz** [comment]
I enabled verbose logs, restarted AdGuard Home and reproduced the issue, but I don't see anything important in the logs.
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/4622467/log.txt)

**Comment by ameshkov** [comment]
@gogorz could it be that the request is blocked by some extension/add-on you have in Firefox?

**Comment by gogorz** [comment]
It looks like it started working yesterday. I think it was uBlock Origin, which was also causing other issues. Everything started working after I replaced uBO with Nano Adblocker, which is a fork of it. 🤔

**Comment by ameshkov** [comment]
Huh, well, weird stuff happens sometimes. I am glad the issue is resolved
