### ISSUE TITLE
Make reloading log list work better

### ISSUE THREAD

**Issue by jamezrin** [AdguardTeam/AdGuardHome#1642]
Currently, the refresh button in the "Query Log" view reloads the page. 

Instead of this I think it should make the table go to the first page and fetch the data from the server again.

I think I can contribute with a change that does this, but I have to know if it would be welcome. I love this software!

**Comment by ameshkov** [comment]
@jamezrin we're currently reworking the query log page so I guess it'd be better to wait till we finished the rework.

**Comment by ArtemBaskal** [comment]
fixed e39fe1b913839bb6d72c09672145ef187332fd27
