### ISSUE TITLE
Certificate Error with Enforce safe search enabled

### ISSUE THREAD

**Issue by JOduMonT** [AdguardTeam/AdGuardHome#1644]
## when I enable **Enforce safe search**

-> might be  a duplicate of (https://github.com/AdguardTeam/AdGuardHome/issues/576)

### then I search for something google give me an certificate error

![image](https://user-images.githubusercontent.com/5204724/80932525-0856ee80-8dea-11ea-80fa-0357ebd134ff.png)

### the best in this; it's my network is not 192.168.1.0
![image](https://user-images.githubusercontent.com/5204724/80932579-4bb15d00-8dea-11ea-8a6d-42986270d303.png)

### my setup
- AdGuard run under an LXC Debian 10

#### my upstream are
- tls://1.1.1.1
- tls://dns.google
- tls://dns.quad9.net

**Comment by ameshkov** [comment]
@JOduMonT 

Please show me the output of `nslookup www.google.com x.x.x.x` where x.x.x.x is the IP address of AGH.

**Comment by JOduMonT** [comment]
so this morning when I enable SafeSearch everything seams fine
but here the awnser of your question
jond@ux305ua:~$ nslookup www.google.com 192.168.42.2

Non-authoritative answer:
Name:   www.google.com
Address: 216.239.38.120
