### ISSUE TITLE
Error parsing certificate private key : "tls: failed to parse private key"

### ISSUE THREAD

**Issue by lbalogh** [AdguardTeam/AdGuardHome#1645]
### Prerequisites

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * Docker container on a Synology NAS
* **Operating system and version:**
  * DSM 6.2.3-25423

### Expected Behavior
On the _Encryption settings_ page, the _Private key_ field shoud accept my certificate private key

### Actual Behavior
When specifying my private key, **either by pasting the key content or setting a file**, I get the message :

> This is an invalid private key
> Failed to parse private key: tls: failed to parse private key

### Screenshots
<img width="1174" alt="screenshot" src="https://user-images.githubusercontent.com/6897141/80944882-d3976700-8dea-11ea-998f-8e46e1efbb67.png">

### Additional Information
My certificate is a Let's Encrypt wildcard certificate. I use it on several other web servers (Apache, Nginx and lighttpd) without any problem.

Note that I also tried to install AdGuard Home on Debian by following this guide : https://github.com/AdguardTeam/AdGuardHome/wiki/VPS, but same problem

**Comment by lbalogh** [comment]
Well after doing some research I solved my issue by doing :

`openssl rsa -in server.key -out server2.key`

Then, when pasting the content of _server2.key_, it works. But I think there is something wrong on your side, as the original _server.key_ works on other web servers without any problem

**Comment by ameshkov** [comment]
Well, the problem is that you can't share that key so we may never know what's the problem:(

**Comment by lbalogh** [comment]
Yes I understand :/ I'll try the reproduce the case with a certificate I can share. Thanks

**Comment by lbalogh** [comment]
I found this : https://github.com/golang/go/issues/26785, which is something related to a "curve" (I'm not a cryptographic expert so I don't really know what this means).

Anyway, as this can be worked around with the openssl command, I'll close this issue
