### ISSUE TITLE
Client DNS name overrules /etc/hosts in query logs

### ISSUE THREAD

**Issue by s3frank** [AdguardTeam/AdGuardHome#1646]
* **Version of AdGuard Home server:**
AdGuard Home, version v0.101.0
* **How did you setup DNS configuration:**
Router->Switch->RPi4->Clients
* **If it's a router or IoT, please write device model:**
RPi 4
* **Operating system and version:**
Linux adguard.berth.net 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

### Expected Behavior
I am making use of the DNS settings per client option of AdGuard. It works great however it impacts the way the dashboarding is working because instead of showing the client name that is coming from /etc/hosts it starts to show the name given to the DNS client rule. The problem is that I group more then one IP address in these rules. For example all my servers get the same DNS settings (block lists etc)...and so now all I see is servers (x.x.x.x) in the dashboard.

I was not expecting the name of the Client Identifier to overrule what is coming from /etc/hosts when reporting query info. I can understand this is done for anything that isn't in /etc/hosts.

See the screenshot showing two different IPs associated with the same DNS Client setting in AdGuard. I add these using REST api /control/clients/add with ids containing array of IPs.

<img width="606" alt="Screenshot 2020-05-04 at 20 14 09" src="https://user-images.githubusercontent.com/2191242/80964873-2f420e80-8e44-11ea-9925-03998506dee6.png">

**Comment by ameshkov** [comment]
Hm, tbh, I don't think this is a bug.

We consider "Clients" to be the main source of the metadata and if there's a manually created client, we always use its name.

The more or less viable alternative would be to show the hostname as well somewhere there.

**Comment by s3frank** [comment]
I agree with you but only if the client is 1:1 with an identifier such as
ip.

But if you add more then one id to the client record, which is possible and
very useful it really is more of a group instead.

In that case I think the full hostname should be logged first and the
client / group name second.

I think to be honest its a fantastic feature on the back end just maybe
needs some better thought in front end.

Perhaps introduce as a new feature, client grouping?

-FF

**Comment by ameshkov** [comment]
> Perhaps introduce as a new feature, client grouping?

That's what we were trying to avoid by adding an option to have multiple identifiers.

Anyways, all the necessary info is here anyway: hostname, client (group) name, we just should find a way to print it properly.
