### ISSUE TITLE
Adguard home on hassio in docker on unraid

### ISSUE THREAD

**Issue by SavageAUS** [AdguardTeam/AdGuardHome#1647]
Ok not really a bug but looking for advice on running adguard on home assistant which runs in a docker on unraid. I can set it up correctly and point my router dns to the ip but it does not pickup clients so therefor no blocking happens. I’m assuming it has something to do with unraid and the way it does docker or something. But to recap I have unraid running, home assistant running in a docker and then adguard running on home assistant.

**Comment by ameshkov** [comment]
> but it does not pickup clients so therefor no blocking happens

Does it work when you simply run `nslookup example.org AGH_IP_ADDRESS`?

My guess is that the DNS settings for some reason aren't properly propagated to the clients.
