### ISSUE TITLE
DCHP stops working

### ISSUE THREAD

**Issue by ncodee** [AdguardTeam/AdGuardHome#1648]
Hi, I'm wondering if someone could help me. I have a SuperHub 3 router that doesn't allow to change the DNS directly, so I disabled DHCP on the router itself, and enabled it on Adguard Home (RPI, HA), everything worked fine for a day or so, bit randomly the WiFi and Lan stopped working.

I had to re-enable DHCP through the router, otherwise I can't gain internet connection no more.

I'm guessing this is due to some port forwarding issue, but unsure, if someone could point me where to find the issue in the logs, that would be great.

Thanks

**Comment by ameshkov** [comment]
Sorry for the late reply.

Marked as "question", maybe someone can help you with this.

Please note, that you need to supply more details about the issue. How exactly do they stop working? What kind of error is shown when you connect to Wi-Fi?

**Comment by ncodee** [comment]
> Sorry for the late reply.
> 
> Marked as "question", maybe someone can help you with this.
> 
> Please note, that you need to supply more details about the issue. How exactly do they stop working? What kind of error is shown when you connect to Wi-Fi?

Hi, thanks for your reply.
I would've supplied more details, but I don't see it reported in the logs, and there are no errors/warnings shown. The internet connection just stops working, it is as if the whole dns is randomly blocked which stops any form of connection to pass through.

Thanks

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
