### ISSUE TITLE
[Suggestion] Use of monospace font in selected textareas of the web UI

### ISSUE THREAD

**Issue by jitdor** [AdguardTeam/AdGuardHome#1650]
Currently, the font used in various form input elements in the AdGuardHome web UI is proportional, which is ok for the most part.

However, sections of the UI require coding-like inputs, such as:
- Custom filtering rules input textbox (URL `/#custom_rules`)
- Upstream DNS servers input textbox (URL `/#dns`)

These input elements would be a lot more user-friendly if they were to use a monospace font instead.

**Comment by ameshkov** [comment]
This makes perfect sense, thank you!

**Comment by jitdor** [comment]
> This makes perfect sense, thank you!

Thank you. And optionally, syntax highlighing for the texts, such as showing IP addresses in a different color under upstream DNS, and lines with @@ is displayed in a different color from lines starting with || in customer filtering rules :)

**Comment by ameshkov** [comment]
> And optionally, syntax highlighing for the texts

Well, I think this should be a separate feature request:)

This is definitely possible, it'll just require more time.
