### ISSUE TITLE
Adguard behind keepalived not operating correctly

### ISSUE THREAD

**Issue by tahngarth** [AdguardTeam/AdGuardHome#1653]
So I have been trying to get redundancy via docker swarm and keepalived. I have gotten adguard working with host networking in docker swarm, and intend to always run two, with keepalived to point at them. This is all set up and mostly works except the virtual IP doesn't work correctly for actual DNS. The web interface is working correctly and the list of IPs in the Guide section shows the virtual IP, but DNS doesn't work. If I point to the real IP's it works fine, and if I go into the AdGuardConfig.yml and change the host binding for dns to the virtual IP, it also works. This might kind of sort of work, but is not a great solution.

**Comment by ameshkov** [comment]
@tahngarth could you please check if it works properly with the beta version of AGH?

**Comment by tahngarth** [comment]
Running edge version 6d13 seems to be working so far.  I ditched the swarm and just ran the containers  directly and it survived failover as well.

**Comment by ameshkov** [comment]
Most likely this bug was the reason: https://github.com/AdguardTeam/AdGuardHome/issues/1490

It's fixed in the master branch and soon will be also fixed in the stable version

**Comment by FabioEight** [comment]
> So I have been trying to get redundancy via docker swarm and keepalived. I have gotten adguard working with host networking in docker swarm, and intend to always run two, with keepalived to point at them. This is all set up and mostly works except the virtual IP doesn't work correctly for actual DNS. The web interface is working correctly and the list of IPs in the Guide section shows the virtual IP, but DNS doesn't work. If I point to the real IP's it works fine, and if I go into the AdGuardConfig.yml and change the host binding for dns to the virtual IP, it also works. This might kind of sort of work, but is not a great solution.

How do you configured keepalived to check if Adguard is running on the nodes?

**Comment by tahngarth** [comment]
> > So I have been trying to get redundancy via docker swarm and keepalived. I have gotten adguard working with host networking in docker swarm, and intend to always run two, with keepalived to point at them. This is all set up and mostly works except the virtual IP doesn't work correctly for actual DNS. The web interface is working correctly and the list of IPs in the Guide section shows the virtual IP, but DNS doesn't work. If I point to the real IP's it works fine, and if I go into the AdGuardConfig.yml and change the host binding for dns to the virtual IP, it also works. This might kind of sort of work, but is not a great solution.
> 
> @tahngarth How do you configured keepalived to check if Adguard is running on the nodes?
@FabioEight 
I've fumbled my way through all of this, but it is the state of the machine that is tracked, not a particular service. If the machine A goes down, keepalived running on machine B sees this and the IP address switches over to machine B. Adguard is supposed to be running on both at all times.  I have machine A set to a higher priority so that when it comes back up, it switches back to it, that way stats are a little more consistant.
