### ISSUE TITLE
Error: control/filtering/add_url | Failed to save filter 1588918783 due to write /opt/AdGuardHome/data/filters/1588918783.txt.tmp: no space left on device | 400

### ISSUE THREAD

**Issue by dinhminhdung** [AdguardTeam/AdGuardHome#1654]
Error: control/filtering/add_url | Failed to save filter 1588918783 due to write /opt/AdGuardHome/data/filters/1588918783.txt.tmp: no space left on device | 400

**Comment by ameshkov** [comment]
It's in the error message:

**"no space left on device"**

**Comment by dinhminhdung** [comment]
![IMG_20200508_161348](https://user-images.githubusercontent.com/18631716/81391233-f2795e80-9146-11ea-8eed-cd4d29fce834.jpg)

**Comment by dinhminhdung** [comment]
I have a lot of free memory on my device

**Comment by ameshkov** [comment]
@dinhminhdung different partitions may have different size, maybe AdGuard Home is installed to a partition without enough free space?
