### ISSUE TITLE
AdGuard Home WIndows 10 no log statistic

### ISSUE THREAD

**Issue by GodFather0000** [AdguardTeam/AdGuardHome#1655]
Hello.

My AdGuard home on Win 10 have no statistic log and is 0% everywhere.
I trying to navigate in the same time but still have nothing.
I added the two DNS adress directly in my router.

I have Adguard Pro installed on this same computer and when I run the log on the background, all log statistic is updated live and I can see all blocked request.

What can be the problem?

Thanks

![zczzczxc](https://user-images.githubusercontent.com/65033019/81425175-11ff8f80-9125-11ea-8c16-42f8958257ee.PNG)

**Comment by ameshkov** [comment]
It just means that AG Home is not used by your devices.

I can't say why, though, you should check your devices and router settings and try to figure what's wrong with their configuration.

Also, you can easily check if AdGuard Home really works by running something like this from the command line: `nslookup example.org ADGUARD_HOME_IP` (replace ADGUARD_HOME_IP with the IP address).
