### ISSUE TITLE
Docker Command Local Doesn't Expose Port 80

### ISSUE THREAD

**Issue by DannyHinshaw** [AdguardTeam/AdGuardHome#1656]
### Expected Behavior
I expected that when running the docker build locally it would serve me the correct command to run the container.

### Actual Behavior
The command given to run the docker container after `make docker` appears to be missing port `80` from the command.

As it stands now, without exposing that port in the command I can only get through the registration step in the client UI. Once that is finished it switches to serving the dashboard on port `80`, but that cannot be accessed without exposing it in the aforementioned command.

Is this intentional? If so, why or what am I missing? If not I can create a quick PR to add `-p 80:80/tcp` to the command, just let me know.

**Comment by ameshkov** [comment]
Nope, not intentional, thx for mentioning it!
