### ISSUE TITLE
Custom filter editor works with delay

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1657]
### Prerequisites
- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Expected Behavior
Add or remove rules without delay.

### Actual Behavior
The filter editor on my server has some delay. When you add three, four, or more rules in a short period of time, some rules do not appear on the list or appear there with a delay.

### Screenshots
I recorded a GIF with this problem:
https://ibb.co/PrPLZyd

Please, pay attention that the host **gateway.icloud.com** there and did not appear in the list! The exactly the same thing with unblock button or when i edit custom filtering rules manually and save it.

### Additional Information

I can send the logs to email if you want.

**Comment by ammnt** [comment]
Unfortunately my gif record is gone. Here is another one:
https://ibb.co/CJrpn41
Please, pay attention that **||s28vuj.c2434ee0.n40.vp1.v4.drakkardnsv4.com^$important** is not appear in the custom filters section. Thank you.

**Comment by ammnt** [comment]
Any chance to see this fix in the next release?😒

**Comment by ameshkov** [comment]
Hopefully:) Planned for v0.104 for now.
