### ISSUE TITLE
Question about average processing time

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1658]
### Prerequisites
- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Expected Behavior
Я подозреваю, что среднее время обработки DNS запросов рассчитывается с какой-то ошибкой. Чем больше время аптайма сервера - тем больше значение среднего времени сопоставления. Иногда оно может достигать величин, при которых задержка уже была бы заметна на глаз (>80 ms), но этого нет! Не знаю, как проверить есть ли проблема в действительности...

### Additional Information
Решил написать этот вопрос на русском, чтобы была уверенность, что меня поймут. Логи и файл статистики могу выслать на почту.

**Comment by ITensEI** [comment]
\<translation>

**Expected Behavior**

I suspect that the "Average processing time" has some sort of an error. The longer the plugin is running the higher the average gets. Sometimes it gets high enough where you'd notice the delay (> 80 ms), but you don't. I'm not sure how to check if it's an actual bug.

**Additional Information**

Decided to write the issue in Russian so that I can get my point across clearly. I can email the logs if necessary.

\</translation>

**Comment by ameshkov** [comment]
Most likely there's some DNS query that constantly times out and this is the culprit.

We have three options here:

1. Simply ignore queries that time out and don't use them for calculating avg processing time.
2. Replace avg. processing time with median processing time
3. Do nothing:)

If we go with the first approach, we may need to add another metric -- the number of timed out queries.

**Comment by ammnt** [comment]
> 2. Replace avg. processing time with median processing time

Looks reasonable to me 🤟🏻Thank you!

**Comment by miaomiaosoft** [comment]
> 最有可能是某些DNS查询不断超时，这是罪魁祸首。
> 
> 这里有三个选项：
> 
> 1. 只需忽略超时的查询，而不用它们来计算平均处理时间。
> 2. 替换平均。处理时间与中值处理时间
> 3. 没做什么：）
> 
> 如果采用第一种方法，则可能需要添加另一个指标-超时查询的数量。

Need an option to select that DNS responses beyond this time will be discarded.
For example, 500 milliseconds.
Some unstable DNS servers will slow down response times.

**Comment by miaomiaosoft** [comment]
> Most likely there's some DNS query that constantly times out and this is the culprit.
> 
> We have three options here:
> 
> 1. Simply ignore queries that time out and don't use them for calculating avg processing time.
> 2. Replace avg. processing time with median processing time
> 3. Do nothing:)
> 
> If we go with the first approach, we may need to add another metric -- the number of timed out queries.

Need an option to select that DNS responses beyond this time will be discarded.
For example, 500 milliseconds.
Some unstable DNS servers will slow down response times.

**Comment by KizunaH** [comment]
Need enhancement for APT. 
Currently this isn't good for me as well and my main instance(90 days retention) showed 2000ms value for 5-8 days while other testing instances displayed 80-94ms with many clients.
I dont know how average processing time calculated on adguard home (lazy read source) but it might be good to generate using certain short time period eg: last 1 or 5hr.

>there's some DNS query that constantly times out and this is the culprit

I didn't noticed something like that but i guess this might occur due same thing you said or due DNS service issue but only for certain time period then it seems adguard home doesn't adjust APT back.
