### ISSUE TITLE
Improve a time restriction

### ISSUE THREAD

**Issue by bassisd** [AdguardTeam/AdGuardHome#1659]
Dear support i have adguard on my hassio server, i want to ask/say if you will develop sameting about a time/scheduling block of the application like youtube /facebook etc.
best regards

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by bassisd** [comment]
Dear support i have adguard on my hassio server, i want to ask/say if you will develop sameting about a time/scheduling block of the application like youtube /facebook etc.
best regard

**Comment by ameshkov** [comment]
Please upvote this feature request:
https://github.com/AdguardTeam/AdGuardHome/issues/951
