### ISSUE TITLE
For Custom IP HTTPS of Blocking mode issues

### ISSUE THREAD

**Issue by yatounoneko** [AdguardTeam/AdGuardHome#1661]
I see the Blocking mode have the custom IP function, i have set my Nginx web server IP in custom IP.

The Block list website will redirect to my Nginx server, but just working in HTTP.

if block list website have Https, it will show [ERR_CONNECTION_REFUSED].  

_But if Install the certificate into Nginx web server will got the the connection is not secure[ERR_CERT_COMMON_NAME_INVALID]_
_(of course, the certificate is my own domain...i know......)_

So I do not think there is good solve of this problem now, or if you have any good idea? Many thanks.
_(Just achieve the same web page effect as other web blocking applications[like ESET..], only this time it is a custom site)_

**Comment by ameshkov** [comment]
You need to use something like this:
https://github.com/kvic-z/pixelserv-tls

You need a server that will generate domain certificate on-the-fly, and you need to generate and install a root certificate to all your devices.

**Comment by yatounoneko** [comment]
ohhh, i get it. Thanks for your help.
