### ISSUE TITLE
Add categories to lists

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#1662]
Add categories feature to each type of lists page to toggle multiple at once.

- Video platforms (vimeo, dtube etc)
- Games sites (overwatch, call of duty etc)
- Social media (geni, viadeo)

Do not add various companies, sites due requested by people unless too popular around the world and meet certain terms. Let people to create their own or they can find public maintain lists.

**Comment by ameshkov** [comment]
Tbh, I don't think that this is proper categories for lists.

Filter lists should be categorized by what they block. Ads, trackers, social stuff, etc. I doubt that blocking video platforms fits here.

However, if you're talking about categorizing domains in general, this may work.

**Comment by Archive5** [comment]
>Filter lists should be categorized by what they block. Ads, trackers, social stuff, etc.

Sure and i noticed something on [parentalcontrol/categories/social-networks.json](https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/social-networks.json) however except some categories names in it :(

And regarding my feature request, i mean users can add prefer name to categories.
eg, if add many games, software updates, media companies domains as each company domains for each list then difficult task to enable and disable for parental purposes or easy to use for #1203 features.

**Comment by KizunaH** [comment]
#2322
