### ISSUE TITLE
[Feature Request] integrate ingenious way to block YouTube ads

### ISSUE THREAD

**Issue by rodalpho** [AdguardTeam/AdGuardHome#1663]
An extremely clever pihole user figured out a way to block YouTube ads by looking at previously successfully resolved hosts and adding them to the blocklist. Thoughts on integrating into AGH?

https://discourse.pi-hole.net/t/youtube-script-seems-to-be-working-very-well/31316
https://gitlab.com/grublets/youtube-updater-for-pi-hole/

**Comment by ameshkov** [comment]
I really, really doubt this works. But anyway, let's keep an eye on the thread for some time.

**Comment by rodalpho** [comment]
It definitely seems to work, but the problem is it relies on recognizing a specific hostname pattern and Google could easily change that.

**Comment by ameshkov** [comment]
Okay, I kinda understood what it does.

With AdGuard Home you can do the following:
1. Check the query log, find some `r*.googlevideo.com` domain there, get it's IP address
2. Add two DNS rewrites:

```
*.googlevideo.com --> that IP address
redirector.googlevideo.com --> wide-youtube.l.google.com
```

I tried it on my side and it breaks videos randomly (which is understandable, it supplies IP for a wrong cache server all the time).

**Comment by rodalpho** [comment]
It doesn't block everything with r*.googlevideo.com, it looks for resolved manifest.google.com hosts that also happen to _reverse_-resolve to iad*.googlevideo.com and then forces them to go to a known-good googlevideo IP address. At least that's how I read it.

**Comment by ameshkov** [comment]
Hm, but that's not what I see in the shell file:
https://gitlab.com/grublets/youtube-updater-for-pi-hole/-/blob/master/youtube.update.sh

**Comment by rodalpho** [comment]
A lot of it came from his original post a year ago.

https://www.reddit.com/r/pihole/comments/9w5swx/i_think_ive_managed_to_block_youtube_ads_with/

**Comment by ameshkov** [comment]
Yeah, the script **seems** to be doing what I described, but in my case, it creates more problems than solves.

**Comment by ameshkov** [comment]
Here's the relevant part of it:
```
cp $ytHosts $workFile
zgrep -e "reply.*-.*\.googlevideo.*\..*\..*\..*" $piLogs \
    | awk -v fIP=$forceIP '{ print fIP, $6 }' >> $workFile
```
