### ISSUE TITLE
Question about the bootstrap DNS servers

### ISSUE THREAD

**Issue by morfikov** [AdguardTeam/AdGuardHome#1664]
Would the bootstrap DNS server be ever used in the case of setting the upstream DNS servers in the following way?

```
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
```
Also, when I set the upstream DNS server via:

`https://dns.cloudflare.com/dns-query`

what would happen if some other DNS request showed up before resolving the domain of the upstream DNS server? Would it also go via the bootstrap DNS server?

**Comment by ameshkov** [comment]
> Would the bootstrap DNS server be ever used in the case of setting the upstream DNS servers in the following way?

No, they won't.

Moreover, you can use a DNS stamp with a pre-configured IP, in this case bootstrap server won't be used either.

You can make one here:
https://dnscrypt.info/stamps

For example, here's a DNS stamp for AdGuard DNS Non-Filtering config with a pre-configured IP:
sdns://AgcAAAAAAAAADzE3Ni4xMDMuMTMwLjEzNgAaZG5zLXVuZmlsdGVyZWQuYWRndWFyZC5jb20KL2Rucy1xdWVyeQ

**Comment by ameshkov** [comment]
> what would happen if some other DNS request showed up before resolving the domain of the upstream DNS server? Would it also go via the bootstrap DNS server?

No, it will wait until the hostname is resolved

**Comment by morfikov** [comment]
Ok, thank you!
