### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by BigBobDalton** [AdguardTeam/AdGuardHome#1666]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ XX] I am running the latest version
- [ XX] I checked the documentation and found no answer
- [XX ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
Version: 
v0.101.0
AdGuard Home on Raspberry PI

* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior
I receive the following a few times a day
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: x509: certificate signed by unknown authority | 502

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
It means that the root certificates on your devices are old, you should update them.

Try running `update-ca-certificates ` and restarting AGH
