### ISSUE TITLE
Whitelise for specific IPs who can access my DNS

### ISSUE THREAD

**Issue by GOODTESTA** [AdguardTeam/AdGuardHome#1669]
Hello gus, I'm using the AdguardHome v0.101.0
For the latest version, there is a function that I can ban some client in the list,
but as you can see, somebody who just use my DNS server for pinging attach some domain (!?)
The reds I banned in the list is the client that I don't know who they are....

![image](https://user-images.githubusercontent.com/35817374/81816910-8cce0d80-955e-11ea-8076-e44de1068338.png)

So, I'm just wondering if there is a function that whitelist client (IPs) can access my dns server.

**Comment by ameshkov** [comment]
> So, I'm just wondering if there is a function that whitelist client (IPs) can access my dns server.

There is.

Go to DNS 設定, scroll down to 存取設定, there are three options there:

* 已允許的用戶端 -- Allowed clients -- **only these** IP addresses are allowed. Note that you'll have to list all your devices IP addresses (or CIDR ranges)
* 不允許的用戶端 -- Disallowed clients -- that's what you use to block other clients
* 不允許的網域 -- Disallowed domains -- DNS queries for these domains will be dropped. You can check what domains are queried by these clients you're blocking and simply add these domains to disallowed.

**Comment by GOODTESTA** [comment]
Haha, thank you.
You have solved my problem.
