### ISSUE TITLE
IPv6 ip as DNS upstream for a specific domain(s) not accepted

### ISSUE THREAD

**Issue by Melantrix** [AdguardTeam/AdGuardHome#1670]
### Issue Details

* **Version of AdGuard Home server:**
v0.101.0
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
OpnSense
* **Operating system and version:**
Adguard is running in LXC Ubuntu 20.04

### Expected Behavior
There is an option to specifiy a DNS server for specific domain(s). For reverse DNS lookup it's necessary to add a rule like this:
[/168.192.in-addr.arpa/]192.168.0.1 for example. 

For IPv6 you should be able to add a rule like this:
[/x.x.x.x.x.x.x.x.x.x.x.x.a.2.ip6.arpa/]fe80::xxxx:xxxx:xxxx:xxxx

That way ipv4 and ipv6 resolving can work without depending on each other

### Actual Behavior
If you put in the rule
[/x.x.x.x.x.x.x.x.x.x.x.x.a.2.ip6.arpa/]fe80::xxxx:xxxx:xxxx:xxxx
you get the message that this server could not be used for resolving. 
if i change it in:
[/x.x.x.x.x.x.x.x.x.x.x.x.a.2.ip6.arpa/]192.168.0.1
it does accept it, but then ipv6 is depending on ipv4. 

-------------------------------------------------------
My guess is that the ipv6 syntax is not accepted?

**Comment by ameshkov** [comment]
Hm, I've tried something like this and there were no issues:
`[/example.org/]2a00:5a60::ad1:0ff`

However, I was testing it on AdGuard Home v0.102. Could you please update to the latest version and check if it works there?

**Comment by Melantrix** [comment]
I just logged in and tried it with v0.102. there are no problems anymore. 

I guess it's fixed in this version, thanks for replying though!

**Comment by ameshkov** [comment]
Awesome, thank you!
