### ISSUE TITLE
Failed to start AdGuard Home service

### ISSUE THREAD

**Issue by mveerdon** [AdguardTeam/AdGuardHome#1672]
Hi, i have installed the latest version of Adguard on Raspberry Pi.

Installation went well on Pi, default configuration applied via weg gui on port 3000. rebooted the PI and can connect to it via ssh. 
Not via gui on port 80 and/or 3000.

Looking on PI I see that Adguard service isn't running anymore and can't be restarted.

Any ideas how to fix this?

pi@pi:/AdGuardHome $ ./AdGuardHome -s status
2020/05/15 11:01:23 [info] Service control action: status
2020/05/15 11:01:23 [info] Service is stopped
2020/05/15 11:01:23 [info] Action status has been done successfully on linux-systemd
pi@pi:/AdGuardHome $
pi@pi:/AdGuardHome $
pi@pi:/AdGuardHome $ ./AdGuardHome -s restart
2020/05/15 11:01:31 [info] Service control action: restart
2020/05/15 11:01:31 [fatal] Failed to restart AdGuard Home service: exit status 1
pi@pi:/AdGuardHome $
pi@pi:/AdGuardHome $
pi@pi:/AdGuardHome $ ./AdGuardHome -s start
2020/05/15 11:01:38 [info] Service control action: start
2020/05/15 11:01:38 [fatal] Failed to start AdGuard Home service: exit status 1
pi@pi:/AdGuardHome $

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by ameshkov** [comment]
@mveerdon please reopen the issue if it still happens and you can provide necessary logs
