### ISSUE TITLE
Queries blocked by CNAME go out to upstream DNS

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1673]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.101.0
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Actual Behavior
I guess it shouldn 't be like that. DNS queries blocked by CNAME go out to upstream DNS anyway:
![image](https://user-images.githubusercontent.com/45385632/82062022-2833bf80-96d2-11ea-8101-c89caa2de35c.png)
![image](https://user-images.githubusercontent.com/45385632/82062102-46012480-96d2-11ea-99a8-45158bcba3d3.png)
### Additional Information
I think I 've seen a task like this, but I can 't find it...

**Comment by ameshkov** [comment]
Of course it should be, how else can we see what CNAMEs are in the response?
