### ISSUE TITLE
Enabling fastest IP address = more Average processing time

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#1676]
Raspberry b3+
Raspian buster
Agh 102

If i enable "fastest IP address", i get "Average processing time" more than 260ms. And if i enable "parallel request" and disable "fastest IP", I get 36ms. Is this norm?

Using 
https://dns.google/dns-query
https://dns.cloudflare.com/dns-query
sdns://AQQAAAAAAAAAEDc3Ljg4LjguNzg6MTUzNTMg04TAccn3RmKvKszVe13MlxTUB7atNgHhrtwG1W1JYyciMi5kbnNjcnlwdC1jZXJ0LmJyb3dzZXIueWFuZGV4Lm5ldA

**Comment by ameshkov** [comment]
Sure, that's expected. With "fastest IP address" AdGuard Home queries all upstream servers and then tries to connect to all IP addresses, average DNS query will increase in this case.
