### ISSUE TITLE
Allow `Fastest IP address` and `Parallel requests` to toggle each other on and off

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#1678]
### Problem Description
In the Upstream DNS Servers section of the Settings UI, the `Fastest IP address` option has just been added beside the `Parallel requests` option in v0.102.0.

What is not obvious, is that you can only select one of these options, not both. It is one or the other.
When you select one of them, the other option becomes unselectable, which is not entirely intuitive

### Proposed Solution

Allow these settings to 'toggle' one another to make it clearer that you can only have one of them active.

For example, if you have `Parallel requests` enabled, rather than not making `Fastest IP address` selectable, make it so selecting `Fastest IP address` deselects `Parallel requests` and vice-versa.

**Comment by ameshkov** [comment]
"Fastest IP address" implies that all DNS resolvers are quired simultaneously just like when "Parallel requests" is enabled. 

The difference is that in this case, AdGuard Home waits for all responses in order to examine all received IP addresses. That's why these two options cannot be used together.

**Comment by AnthonyBe** [comment]
Yeah. After I sat and thought about it for a few minutes I worked that out. It's a cumulative result. That's why I'm suggesting some change to the UI to make this more obvious.

Essentially, 'Fastest IP address' = 'Parallel requests' + 'more goodness'

**Comment by ameshkov** [comment]
We may indeed make them toggle each other, I am not sure this will be more intuitive, though. Maybe the proper solution would be to replace checkboxes with radio buttons?

**Comment by ameshkov** [comment]
> Essentially, 'Fastest IP address' = 'Parallel requests' + 'more goodness'

Well, not exactly.

* Parallel requests - speeds up the DNS queries.
* Fastest IP - slows down the DNS queries (we should now wait for all resolvers) but improves overall connectivity.

**Comment by AnthonyBe** [comment]
Yes, Radio Buttons rather than checkboxes is definitely a good idea.

I think if you can somehow convey `'Fastest IP address' = 'Parallel requests' + 'more goodness'` then it will be super-clear. Maybe a mouse hover-over tool tip, or just another line of text somewhere on the UI. Not sure to be honest.

**Comment by ameshkov** [comment]
I think we can simply write some one-sentence summary near them.

To summarize, we should:

1. Replace checkboxes with radio buttons.
2. Add one more sentence to the "Fastest IP address" description:
    * `This will slow down the DNS queries as we have to wait for responses from all DNS servers, but improve the overall connectivity.`

The idea that parallel queries speeds up DNS queries is already explained in that option description so  I don't think we should add anything to it.

**Comment by vandalon** [comment]
what exactly does adguard do to determine the "fastest ip address" after it gets all the response from the dns servers?

**Comment by ameshkov** [comment]
> what exactly does adguard do to determine the "fastest ip address" after it gets all the response from the dns servers?

Tries to connect to ports 443 and 80
