### ISSUE TITLE
Load upstreams list from a file

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#1680]
```
My idea is to use 2-3 dns for the IP or domain name in CIDR to analyze. At present, ADGhome supports only [/example.local/] 9.9.9.9. If you use the above method to fill in the configuration file for more than N domain names, it will be very large and not conducive to troubleshooting. Therefore, it is important to use 2-3 DNS resolutions for the CIDR IP and domain name, for example
The way to read ./cidr.txt or ./domain.txt files is very simple.
The contents of cidr.txt are:
DNS = 1.1.1.1, 8.8.8.8, 9.9.9.9 (The three dns are analyzed by the following CIDR list)
3.0.0.0/9
3.128.0.0/9
4.0.0.0/9
4.128.0.0/12
4.144.0.0/12
4.160.0.0/12

The content of domain.txt is:
DNS = 1.1.1.1, 8.8.8.8, 9.9.9.9 (these 3 dns have been analyzed on the following domain name list)
taboola.com
ofgogoatan.com
doubleclick.net
outbrain.com
mgid.com
```

**Comment by ameshkov** [comment]
@thb007 why can't you use Clients settings for that?

You could add Clients with these CIDRs and specify custom upstreams for them

**Comment by thb007** [comment]
> @thb007 why can't you use Clients settings for that?
> 
> You could add Clients with these CIDRs and specify custom upstreams for them

```
No, no, you got it wrong. I need such a function. You can refer to this source project to understand what I mean. https://github.com/shawn1m/overture
```

**Comment by thb007** [comment]
![photo_2020-05-26_20-26-08](https://user-images.githubusercontent.com/17548936/83024647-45b54180-a061-11ea-96a0-18ff5f86ce2a.jpg)
https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf


![photo_2020-05-26_20-31-31](https://user-images.githubusercontent.com/17548936/83024694-55cd2100-a061-11ea-8e8d-8a95cee96f3d.jpg)

I added hundreds of thousands of domain names to ADGH through this format, which is completely unusable. It is estimated that there are too many domain names [/0-100.com/0-6.com/0-gold.net / ... ] 114.114.114.114

**Comment by DandelionSprout** [comment]
If I understand this correctly (Feel free to correct me if I don't), this could presumably also be fixed if AdGuard Home added support for dnsmasq-type lists, which usually involves these kinds of syntaxes:
```
server=/example.org/
server=/example.org/127.0.0.1
address=/example.org/
address=/example.org/127.0.0.1
```

A temporary workaround for thb007 while waiting for #1759 or the addition of dnsmasq list support, could be to convert them into `114.114.114.114 example.org`, since non-'localhosts' hosts files are supported.

**Comment by ameshkov** [comment]
Well, conversion is not that problematic, it can be done with a single regular expression

**Comment by Potterli20** [comment]
[dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) 
There is an adGuardHome conversion address, but if you want to add a locally specified upstream DNS server, you don't need to write it on the upstream DNS column.

**Comment by Potterli20** [comment]
Reference file：https://raw.githubusercontent.com/DNSCrypt/dnscrypt-proxy/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

**Comment by szolin** [comment]
> At present, ADGhome supports only [/example.local/] 9.9.9.9. If you use the above method to fill in the configuration file for more than N domain names, it will be very large and not conducive to troubleshooting.

Did you try to use this syntax one domain per line?  
```
[/a.com/] 9.9.9.9
[/b.com/] 9.9.9.9
...
```

**Comment by ameshkov** [comment]
@szolin just like with certificates, we should provide an alternative for loading upstreams from a file.

1. The path to the file needs to be configured via the config file.
2. On the UI side: if it's configured via file, the upstreams textarea needs to be disabled. Content of the textarea needs to be changed to "Configured in PATH_TO_FILE".
3. Don't forget to describe this behavior in the Wiki.
4. Don't forget to properly handle posts from the web UI - if it's configured that way, you should disregard upstreams sent by the client.
5. Add a "Tips and tricks" link to the section description: 
    ![image](https://user-images.githubusercontent.com/5947035/91536746-db40c580-e91d-11ea-8b9c-ed7da684c7c4.png)
6. This link should lead to an article about configuring upstreams: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams
7. Add information about this new configuration field there

**Comment by ameshkov** [comment]
Will be possible in the next "edge" channel build:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file

**Comment by ihipop** [comment]
any process signal or web api to force ADG to reload this file？

**Comment by ameshkov** [comment]
Not yet. Currently, the only option is to restart AGH.
