### ISSUE TITLE
Add support for PTR/rDNS for DHCP hostnames

### ISSUE THREAD

**Issue by Austrapede** [AdguardTeam/AdGuardHome#1682]
### Issue Details

* **Version of AdGuard Home server:**
  v0.102.0
* **How did you setup DNS configuration:**
  Synology
* **If it's a router or IoT, please write device model:**
  DS218+
* **Operating system and version:**
  Docker (host mode)

### Actual Behavior
PTR/rDNS not working. Adguard Home is configured on Docker with host mode. Adguard is DHCP server. (Sorry for my bad english)

### Screenshots

![Captura de Pantalla 2020-05-16 a les 10 34 04](https://user-images.githubusercontent.com/64137086/82115362-9922b800-9762-11ea-907f-d8208167590b.png)

![Captura de Pantalla 2020-05-16 a les 10 53 06](https://user-images.githubusercontent.com/64137086/82115571-e18ea580-9763-11ea-9104-c352782f4349.png)

Thanks.

**Comment by ameshkov** [comment]
We don't support it yet, but you're right, it makes perfect sense to do that.
