### ISSUE TITLE
Log queries that are "Blocked malware/phishing" separately for later auditing

### ISSUE THREAD

**Issue by adrianmace** [AdguardTeam/AdGuardHome#1683]
### Problem Description
I have just noticed that I have 10 requests blocked due to malware/phishing reasons by the security module, but I have no way to determine what queries they were - or more importantly which clients made the requests.

I want to be able to view a list of these queries separately so that I can audit the devices responsible.

### Proposed Solution
Just like the query log screen, I would like a screen that only shows queries blocked due to the reason of malware/phishing. You could also build a screen for queries blocked due to Adult websites.

### Alternatives Considered
You could add additional filter options on the query log page to filter for these reasons instead of entirely separate screens.

**Comment by Archive5** [comment]
Duplicate of #1292

**Comment by ameshkov** [comment]
> You could add additional filter options on the query log page to filter for these reasons instead of entirely separate screens.

We're going to do this actually
