### ISSUE TITLE
separate search engine safe-search and youtube safe search

### ISSUE THREAD

**Issue by nikeshjauhari** [AdguardTeam/AdGuardHome#1684]
Hi,

Is it possible to add support for 2 separate safesearch section
1) for search engine
2) only for youtube

Many times, we might just need to enable seafeserch only for searchengine but not for youtube.

Thanks,
Nikesh

**Comment by ammnt** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1163

**Comment by ameshkov** [comment]
Closed as dup of #1163
