### ISSUE TITLE
Add more info about DNS names from etc/hosts to "Clients (runtime)"

### ISSUE THREAD

**Issue by RonKhondji** [AdguardTeam/AdGuardHome#1686]
In version v0.102.0 only the ip addresses of the clients are shown on the dashboard.
In version v0.101.0 those ip adresses where resolved to names from my /etc/hosts file. 

I do not have any devices configured in the clients settings. 

Also, on a maybe related note, in the 'clients settings' is a list with clients that use AdGuard Home, but not stored in the configuration. This list shows only ip6 clients. I use ip4.
![chrome_cqoBMRJ3Xf](https://user-images.githubusercontent.com/6552970/82125504-a1044b80-97a6-11ea-8493-07a9345fc15c.png)

Am I missing something or did I find a bug?

**Comment by RonKhondji** [comment]
I've deleted the ip6 clients from my /etc/hosts file. 
Now the 'Clients (runtime)' shows 'No clients fouind'.

**Comment by danselstory** [comment]
yeap the previous version indeed have more information :)

**Comment by szolin** [comment]
Please enable debug logs, then restart AGH - do you see the lines similar to `Clients: added 'localhost4' -> '127.0.0.1'` ?

**Comment by RonKhondji** [comment]
I do not.
I've attached the logfile and my hosts file.
[hosts+log.zip](https://github.com/AdguardTeam/AdGuardHome/files/4644974/hosts%2Blog.zip)
