### ISSUE TITLE
mode to not save the ip address is not working

### ISSUE THREAD

**Issue by eduaddad** [AdguardTeam/AdGuardHome#1689]
the way to not save the IP in statistics and logs is not working.

(anonymize the client's IP)

![20200517_010552](https://user-images.githubusercontent.com/16819380/82135587-beeba380-97da-11ea-82cb-59069c223d18.jpg)

(I deleted the full IP)

**Comment by eduaddad** [comment]
![20200517_010552](https://user-images.githubusercontent.com/16819380/82135635-3a4d5500-97db-11ea-8944-5092f3cf36b8.jpg)

**Comment by eduaddad** [comment]
![20200517_010845](https://user-images.githubusercontent.com/16819380/82135639-46d1ad80-97db-11ea-96cd-7a36ca1c7a05.jpg)

**Comment by danselstory** [comment]
FYI it work for me - althought my auto update failed, but I replaced the linux binary and run the 102 version and this feature works for me

**Comment by eduaddad** [comment]
I updated automatically on Linux but even deactivating and activating the function does not work in my case

**Comment by eduaddad** [comment]
(I'm running by domain and dns-https or dns-tts)

**Comment by ameshkov** [comment]
"Anonymize IP" does not completely removes IP address, it just zeroes the subnet

192.168.0.1 --> 192.168.0.0

**Comment by eduaddad** [comment]
In my configuration is competing
