### ISSUE TITLE
Block button on Clients setting page

### ISSUE THREAD

**Issue by danselstory** [AdguardTeam/AdGuardHome#1690]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [-] I am running the latest version
- [-] I checked the documentation and found no answer
- [-] I checked to make sure that this issue has not already been filed

### Problem Description

Currently red Block button only appears at Front Page Top clients
### Proposed Solution

I think it's a good idea if we can put that red Block button at Settings -> Clients setting page, where are Clients (runtime) page exists.

**Comment by danselstory** [comment]
thanks a lot team !

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2150

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
