### ISSUE TITLE
dns: overflow unpacking uint16

### ISSUE THREAD

**Issue by regae** [AdguardTeam/AdGuardHome#1693]
every 5 minutes i got this info
`[info] error handling UDP packet: dns: overflow unpacking uint16`
my device is raspberry pi 3b+
i already increase these value
`net.core.rmem_max
net.core.wmem_max
net.core.rmem_default
net.core.wmem_default
net.ipv4.udp_rmem_min
net.ipv4.udp_wmem_min`
but the log still persist

can someone help? is it harmless? can be ignored?

**Comment by ameshkov** [comment]
Most likely this is harmless -- it seems there's an invalid DNS query being sent to the DNS server from time to time.

If you enable debug-level logging, you'll be able to find out what device sends it by looking for "Start handling new UDP packet from" preceding that error message.

Here's how to configure debug-level logging:

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
