### ISSUE TITLE
Incorrect rules count

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1694]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.102.0
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9
### Actual Behavior
After the last release, the rule count counter always displays the wrong count - one less. For example, this filter has 15 rules, and displays only 14. At the same time, all rules work:
https://raw.githubusercontent.com/ammnt/AmmoniteFilter/master/test.txt

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/45385632/82157485-61af2b00-988a-11ea-93a7-7ff72222df2c.png)

</details>

### Additional Information
Until the last patch, there was no problem.

**Comment by Archive5** [comment]
Guess recent community PR. Only say,🥱review it
