### ISSUE TITLE
Disable exception rules in untrusted blocklists

### ISSUE THREAD

**Issue by nzm001** [AdguardTeam/AdGuardHome#1695]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

The idea of #1325 is great, but more lists may have disadvantages. Assume that a server was attacked and the blocklist file is now evil and allowing many sites by '||example.org^' or '||example.org^$important' which makes other blocklists useless. Besides, sometimes I don't trust a list but I'd like to have a try, so is it possible to add a blocklist without enabling any exception rule?

Will the rule '||example.org^$important' make other blocklists ineffective?

### Proposed Solution

Add a botton for each or for all blocklist that can ignore exception rules.

**Comment by ameshkov** [comment]
Tbh, I don't think it's scalable. If a blocklist is compromised, it can do an equal amount of harm by blocking something excessively, not just unblocking stuff.

If you want to have full control over filter lists you use, I suggest hosting your own mirror on Github instead, you can use this for this purpose: https://github.com/AdguardTeam/HostlistCompiler 

It'd be rather easy to filter out anything you'd like to.

**Comment by nzm001** [comment]
Thank you. It's a great idea to have my own mirror, and I will definitly create one for myself.

But I'm just wondering if a blocklist suddenly changed by someone evil (maybe this situation is too extreme), for example allow tracking and malware domains by exception rules overwriting other blocklist. It is hard to notice and harmful, because it just allows tracking and malware domains (still able to block ads). On the other hand, blocking excessively is quite noticable and harmless, either my device or internet has problems, so I can see there is something wrong immediately.

Is that situation realistic? Or I'm just thinking too much haha.

**Comment by ameshkov** [comment]
> Is that situation realistic? Or I'm just thinking too much haha.

Tbh, I suppose you're overthinking, there's not that much that can be done.

But anyway, if you're maintaining your own mirror, you'll be able to see what changes are being made to this or that filter list.
