### ISSUE TITLE
Couldn't get version

### ISSUE THREAD

**Issue by debmaj2** [AdguardTeam/AdGuardHome#1696]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://dns10.quad9.net:443/dns-query, cause: failed to lookup dns10.quad9.net, cause: synthetic.wrap: all resolvers failed to lookup, cause: dial udp [2620:fe::fe:10]:53: connect: A socket operation was attempted to an unreachable network. (hidden: dial udp [2620:fe::10]:53: connect: A socket operation was attempted to an unreachable network., read udp 192.168.0.102:51683->149.112.112.10:53: i/o timeout, read udp 192.168.0.102:51678->9.9.9.10:53: i/o timeout) | 502

* **Version of AdGuard Home server:**
  *  v0.102 
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  *  Tenda N300 
* **Operating system and version:**
  * Windows 10 Home 

### Actual Behavior

</details>

**Comment by deftdawg** [comment]
I had this too, in my case upstream DNS was set to ``https://dns10.quad9.net/dns-query` which appears to be having a problem, when I replaced it with 8.8.8.8 everything started to work again.   I believe that's Google's DNS, so probably want to switch to something else soon as you're able to.

**Comment by ameshkov** [comment]
Yeah, it seems `dns10.quad9.net` is unreachable from your place, just replace it with a different DNS server in the DNS settings.

**Comment by debmaj2** [comment]
That's alright, but somehow it couldn't connect to Adguard too. I have tried changing DNS to Adgaurd DNS, but the first 2 errors still persist

**Comment by ameshkov** [comment]
What error is in the log?
