### ISSUE TITLE
syslog error message -  unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query

### ISSUE THREAD

**Issue by nikeshjauhari** [AdguardTeam/AdGuardHome#1697]
Hi, 

I am running AdGuard Home v0.102.0 on ubuntu 20.04 server
I am frequently seeing below errors in syslog

May 18 10:44:05 AdGuard adguard-home.adguard-home[1942]: 2020/05/18 10:44:05 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'
May 18 10:44:06 AdGuard adguard-home.adguard-home[1942]: 2020/05/18 10:44:06 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'
May 18 10:44:07 AdGuard adguard-home.adguard-home[1942]: 2020/05/18 10:44:07 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'

Any idea on what's going on here.

thanks,
Nikesh

**Comment by ameshkov** [comment]
Hm, we need to see what domain name is being tested.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the relevant part of the log file here.

**Comment by Chinaski1** [comment]
Looks like one of our users from [AdGuard Forum](https://forum.adguard.com/index.php?threads/adguard-docker.38470/#post-198395) faced a similar issue.
He sends log_file in the thread I think you'll find it interesting.

**Comment by ameshkov** [comment]
@Chinaski1 could it be related to the today’s AG DNS outage?

**Comment by Chinaski1** [comment]
I guess so. But the first appeal dates back to May 18.
The user also noted that the issue is reproduced almost daily.  

I'll ask him to keep collecting logs and send me the report as soon as the issue arises again.

**Comment by nickbock** [comment]
I get this error every few minutes:

```
;; QUESTION SECTION:
;3.0.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.f.f.ip6.arpa.      IN       PTR

2020/06/18 12:15:16 1#16321 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).checkSafeBrowsing(): SafeBrowsing: checking 3.0.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.f.f.ip6.arpa: a74936c3.dca13321.59fc0bd2.a47ff853.b9a830b4.85493510.5fdaf4fc.246e1e9a.7bc6f261.6d96f3ff.ba69c97b.6d5dd3ab.635e9a14.34a4be26.2e471c15.61c44c61.b72cf696.3164b124.3fe2cc43.306c1f28.7201bc30.89166696.1bf361de.ef38943b.f08e2be6.24dedb10.03f927ae.155a005a.72db7561.53ccb5e4.4657c25b.1703e442.sb.dns.adguard.com.
2020/06/18 12:15:16 1#16321 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).checkSafeBrowsing(): SafeBrowsing lookup for 3.0.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.f.f.ip6.arpa; Elapsed time: 35ms
2020/06/18 12:15:16 1#16253 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).checkSafeBrowsing(): SafeBrowsing lookup for 3.0.0.0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.f.f.ip6.arpa; Elapsed time: 92ms
2020/06/18 12:15:16 1#16321 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'
2020/06/18 12:15:16 1#16253 [info] SafeBrowsing: failed: got an unexpected HTTP status code 400 from 'https://dns-family.adguard.com:443/dns-query'
2020/06/18 12:15:16 1#16253 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).replyFromCache(): Serving cached response
2020/06/18 12:15:16 1#16321 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).replyFromCache(): Serving cached response
2020/06/18 12:15:16 1#16294 [debug] 1 elements serialized via json in 313.646µs: 0 kB, 426/entry, 313.646µs/entry
2020/06/18 12:15:16 1#16253 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NXDOMAIN, id: 61910
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
```

**Comment by ameshkov** [comment]
@szolin take a look plz
