### ISSUE TITLE
Domains with invalid symbols is not blocked😧

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1698]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.102.0
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Expected Behavior
All subdomains for **metric.gstatic.com** must be blocked by the rule: ||metric.gstatic.com^

### Actual Behavior
The subdomains with invalid symbols is not blocked and resolved😧For example:
**ipc\\000lr-dnsotls-ds.metric.gstatic.com
nhc\\000mn-dnsotls-ds.metric.gstatic.com**
In the same time all domains without invalid symbols is blocked fine.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/45385632/82234685-6501ef80-993a-11ea-8906-018e5d60e10d.png)
![image](https://user-images.githubusercontent.com/45385632/82235009-da6dc000-993a-11ea-9827-ba42b3dc7620.png)
</details>

### Additional Information
I use NextDNS servers for upstream, but also do not see these domains in their logs:
![image](https://user-images.githubusercontent.com/45385632/82234732-75b26580-993a-11ea-99c0-e219602cf211.png)
They seem to have their own problem with that...

**Comment by ameshkov** [comment]
> All subdomains for metric.gstatic.com must be blocked by the rule: ||metric.gstatic.com^

No, they shouldn't, invalid domains are invalid -- it does not make much sense to block them, the DNS responses for them will always be empty.

If you want to see them as blocked in the log, try /metric.gstatic.com/, but again, this doesn't make much sense.
