### ISSUE TITLE
add additional cache function to Adguard Home

### ISSUE THREAD

**Issue by yyysuo** [AdguardTeam/AdGuardHome#1702]
Thank you for your great work first.
I have a idea to make Adguard Home better

1.Add a big DNS result cache pool to Adguard Home.
2.Auto request dns result of most visited website in background at a configed  time intervals,add the result to cache pool.
3.The most visited website list can auto generate by the dns report ,and also can be added manually.
4.Only the fastest IP will be added to the cache pool
5.Add refresh button to refresh all result in cache pool

**Comment by yyysuo** [comment]
the most visited website also can be configed by visit times，like larger than 100 times, or can be set to cache all the visited website.

**Comment by ameshkov** [comment]
Basically, you're requesting DNS cache prefetch feature.

There's already a feature request for that:
https://github.com/AdguardTeam/AdGuardHome/issues/1259
