### ISSUE TITLE
[GUIDE] -> How to install AdGuardHome on FreeBSD

### ISSUE THREAD

**Issue by thoggs** [AdguardTeam/AdGuardHome#1703]
Hello,
I made a tutorial instructing the FreeBSD users/community on how to install AdGuardHome on FreeBSD and, I would like to share here, in the context of the project, maybe this will help those who have difficulties installing AdGuardHome on FreeBSD.
I miss something more atomatized for FreeBSD, but for now, this is it:

**GUIDE =>** https://forums.freebsd.org/threads/guide-how-to-install-adguardhome-on-freebsd.75496/

See you...
![Captura de Tela 2020-05-19 às 05 09 06](https://user-images.githubusercontent.com/43221193/82301620-e1262280-998e-11ea-9070-e32530259029.png)

**Comment by ameshkov** [comment]
Guide is not needed since AGH v0.103 supports FreeBSD
