### ISSUE TITLE
v0.102.0 crashes when rewriting any internal CNAME

### ISSUE THREAD

**Issue by devinslick** [AdguardTeam/AdGuardHome#1704]
Previously, AGH worked when rewriting a record to another FQDN, and then rewriting that FQDN to an IP address.   While the rewrite rules don't call them this, I'm calling them CNAMEs for simplicity.
As is the common use-case for CNAMEs, the reason for this is rewrite an application to a server and then rewrite the server name to an IP address.

As of v102, this behavior causes an instant crash of AGH.

I've reproduced this on both ARM and x86.
   Docker Image: adguard/adguardhome:armhf-v0.102.0
   Docker Image: adguard/adguardhome:v0.102.0

 docker run -d  --name adguard --network host adguard/adguardhome:v0.102.0

Add the following rewrite rules:
crash.adguard -> adguard.a.record
adguard.a.record -> 1.2.3.4

### Expected Behavior
Queries for crash.adguard should return 1.2.3.4.

### Actual Behavior
The AGH container crashes when this query is made. 

### Additional Information
Stack trace added below, with network-specific information redacted.

**Comment by ameshkov** [comment]
> Can/should I enable debug logging?

Yeah, this may be useful.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by devinslick** [comment]
Thanks @ameshkov ! 

To me, the log doesn't suggest the cause, but the last even before the service restarts is evaluating an internal record.   How I have this record setup is:

appname.domain.com does a CNAME rewrite to internal.domain.com
internal.domain.com is then rewritten to an IP address.

The last events show those 2 rewrites and then the 'Adguard Home, version v0.102.0, channel release...' line, indicating the service has just started.

Do you want to take a look at the full log?  If so, can I privately share the debug log with you?

![image](https://user-images.githubusercontent.com/1762071/82351649-78589d80-99c2-11ea-8a78-f53f4e865920.png)

**Comment by devinslick** [comment]
@ameshkov , 
I ran some more tests.  It seems that the crash wasn't due to the reboot.  It was happening as soon as one of my CNAME records was being queried.

The fix was removing all of my CNAMES rewrites and instead rewriting them directly to IP addresses.

**Comment by ameshkov** [comment]
> It was happening as soon as one of my CNAME records was being queried

A "panic" message should've been written to syslog, could you please somehow get it from there?

I tried reproducing it but CNAME rewrites seem to be working well on my side

**Comment by devinslick** [comment]
@ameshkov ,
I reviewed syslog and don't see any panics.  

Here are the steps to fully reproduce this issue.

docker run -d --name adguard-broken --network host --restart unless-stopped adguard/adguardhome:latest

Navigate to the admin console
Use the wizard to select the admin port and DNS port. Click Next
Set an admin username/password (test/password)
Login

Add the following rewrite rules:
ingramspark.com -> myaccount.ingramspark.com
myaccount.ingramspark.com -> 198.252.232.29

Query ingramspark.com 


I noticed that there seem to be some records that don't trigger this crash.
In the example below, querying ingramspark.com will crash AGH but querying queryToCrash.com will not.

![image](https://user-images.githubusercontent.com/1762071/82387846-b0c99d00-99fd-11ea-9931-28019c000a69.png)

**Comment by ameshkov** [comment]
Ha, this is interesting. I don't think we support this kind of "chained" rewrites, but panic is anyway not what should be happening.

**Comment by devinslick** [comment]
@ameshkov , Given that the rewrites support FQDN -> FQDN rewrites, it seems natural to want to rewrite that FQDN to an IP address.  
What would you recommend instead of chaining custom rewrite rules?
Filtering rules?
Delegation of the internal zone to another "upstream" DNS server?
Host file entries in the AGH container? 

For now, I've changed all my rewrite rules to rewrite directly to IP addresses, so the crashes aren't happening, but prior to v102 chained rewrites worked without issue.

**Comment by ameshkov** [comment]
What I mean is that it involves two rules

crash.adguard -> adguard.a.record. -> 1.2.3.4

Internally, this would cause a recursion in AdGuard Home, and it seems something goes wrong with handling this recursion.
