### ISSUE TITLE
Publish secondary DNS IP Address - dhcp-option=6

### ISSUE THREAD

**Issue by milothomas** [AdguardTeam/AdGuardHome#1708]
When using AdGuard as DHCP server, only the primary DNS server address is published. This causes some OnePlus devices to [automatically use 8.8.8.8 as the secondary DNS server](https://forums.oneplus.com/threads/secondary-dns-forced-to-8-8-8-8.999920/). 

Can we have an option to publish the same IP address for both primary and secondary DNS server addresses?

**Comment by Sennevds** [comment]
I have the same problem! No my dns rewrites don't work for my cellphone which is quiet annoying.

**Comment by valaria247** [comment]
@ameshkov can you check this https://github.com/AdguardTeam/AdGuardHome/issues/1822#issuecomment-660124900
above @milothomas said problem happen on other brands too so.

**Comment by azrea** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2076 https://github.com/AdguardTeam/AdGuardHome/issues/2075

**Comment by dmshimself** [comment]
I'd definitely like to see this, plus being able to set the domain name

**Comment by ainar-g** [comment]
<p>Hi!&#x2003;We've recently pushed a&#xA0;patch for&#xA0;this.&#x2003;Could you
please update to&#xA0;the&#xA0;latest development snapshot and&#xA0;check
if&#xA0;that fixes the&#xA0;<code>8.8.8.8</code>&#xA0;issue?</p>

**Comment by Sennevds** [comment]
I've just updated to the latest docker(edge) and the 8.8.8.8 address is gone!

**Comment by ameshkov** [comment]
Awesome, thanks for checking it!

**Comment by ainar-g** [comment]
<p>We'll&#xA0;close this issue for&#xA0;now.&#x2003;@milothomas, please feel
free to&#xA0;reopen with&#xA0;more details if&#xA0;the&#xA0;development version
doesn't fix it for&#xA0;you.</p>

**Comment by loll31** [comment]
hey, i tried in last docker images (latest and edge) but they are old versions. I tested dhcp 6 IP option and behavior is incorect. if option is added, client received only 1 dns server and it's the one define by option. As i coud'nt add two addresses, i lost adguardhome dns if i used 'option 6'.
But maybe it's normal if docker image are not uptodate (0.1.4.3).

**Comment by ainar-g** [comment]
<p>@loll31,&#xA0;hi and&#xA0;thank you for&#xA0;your message.&#x2003;There seems
to&#xA0;be a&#xA0;misunderstanding or,&#xA0;perhaps, a&#xA0;documentation issue
here.&#x2003;In&#xA0;this issue we fixed the&#xA0;logic of&#xA0;sending
<i>AdGuardHome</i>'s own IP addresses when&#xA0;users don't specify their own
servers with&#xA0;option&#xA0;6.&#x2003;Currently, options set by&#xA0;users
silently override the&#xA0;ones set by&#xA0;<i>AdGuardHome</i> automatically,
so&#xA0;if&#xA0;you set only one DNS server with&#xA0;option&#xA0;6
then&#xA0;the&#xA0;DHCP clients will only receive the&#xA0;one&#xA0;address.</p>

<p>Maybe&#xA0;we need to&#xA0;print a&#xA0;warning,
on&#xA0;the&#xA0;<code>info</code> level, when&#xA0;users' options override
the&#xA0;automatic ones?&#x2003;Perhaps, another warning when the&#xA0;users only
provide one DNS server address?&#x2003;Or&#xA0;just automatically double
it?&#x2003;Or&#xA0;both?&#x2003;Or&#xA0;just document the&#xA0;whole thing
in&#xA0;a&#xA0;separate wiki article?</p>

<p>@ameshkov,&#xA0;what do you think?&#x2003;I&#xA0;personally favour
the&#xA0;wiki&#xA0;approach.</p>

**Comment by ameshkov** [comment]
@ainar-g users can specify multiple DNS servers using option 6, right?

If so, we should just explain that in the Wiki that if this option is set, you'll need to specify AGH address explicitly.

**Comment by loll31** [comment]
@ainar-g , @ameshkov , thanks for the feedback. i tryed to set 2 IP via option ( - 6 ip ip1,ip2 or - 6 ip ip1 ip2 , w/ or w/o quotes, -6 text "ip1,ip2" or - 6 '''ip','ip'" ...) in vain. 
For comprehension, if options is set, the AGH IP is not used as DNS and users caould define 1 or 2 DNS (or more, i dont know if bootp/dhcp norm accepts it) . To resolve the problem OnePlus, maybe AGH should duplicate same IP if only one addres is set in config file...

**Comment by ainar-g** [comment]
<p>@ameshkov,&#xA0;@loll31,&#xA0;it seems that&#xA0;<i>AdGuardHome</i> currently cannot parse
two IPs there.&#x2003;Or&#xA0;rather, it can only do it if&#xA0;you use the&#xA0;<code>hex</code>
form.&#x2003;So,&#xA0;there are at&#xA0;least two issues&#xA0;here:</p>

<ol>
<li><i>AdGuardHome</i>&#xA0;cannot parse multiple IPs in&#xA0;DHCP
options.&#x2003;This is now&#xA0;#2385.</li>
<li>Our&#xA0;DHCP documentation is a&#xA0;bit lacking.&#x2003;This is
now&#xA0;#2386.</li>
</ol>

**Comment by loll31** [comment]
Do you have the syntax for hex form ?
ex: 192.168.1.1 and  192.168.1.2 two DNS servers should be (or a separator should be added ?)
- 6 hex 0xC0A80101C0A80102

**Comment by ainar-g** [comment]
<p>@loll31,&#xA0;try&#xA0;this:</p>

<pre>6 hex c0a80101c0a80102</pre>

**Comment by loll31** [comment]
@ainar-g client sets only the second ip address ie 02 ?!?

    options:
    - 6 hex 0xC0A80101C0A80102

**Comment by ainar-g** [comment]
<p>@loll31,&#xA0;definitely not&#xA0;the&#xA0;right place
to&#xA0;ask.&#x2003;Please write a&#xA0;new issue.&#x2003;We'll label it
as&#xA0;a&#xA0;question and&#xA0;respond when&#xA0;we have the&#xA0;time.</p>

**Comment by loll31** [comment]
ok. See you
