### ISSUE TITLE
Issue with Adguard Mac and Adguard Home

### ISSUE THREAD

**Issue by Ulmisch** [AdguardTeam/AdGuardHome#1713]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
  * AGH 0.102
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry 4
* **Operating system and version:**
  * Raspbian Buster

### Expected Behavior
Like before, i want to use AGH and Adguard Mac for https filtering to get the best results in filtering.

### Actual Behavior
with https filtering enabled there is no internet connection possible.
there seems to be an issue with AGH 0.102. 
The same constellation works flawless with pi-hole or nxfilter.
Until version 0.101 this system worked as well.

**Comment by ameshkov** [comment]
Hm, I am using AG for Mac alongside AGH with no issues.

Could you please explain how exactly everything is configured?

**Comment by Ulmisch** [comment]
So strange!
After i have restored an old keychain from backup, it is working.
Mac Os did not accept the newly installed certificate.
Hard to understand...

**Comment by Ulmisch** [comment]
I have found out what caused this problem.
You have changed the behaviour of Adguard Home to accept wildcards in the forbidden domains setting under DNS settings.
I had an old entry to deny "local" request. With version 0.102 this entry was interpreted to block connection to local.adguard.com -> Adguard Mac did not work....
Small change, great effect...

Solved for now.

**Comment by ameshkov** [comment]
Got it, I am glad that it's resolved now
