### ISSUE TITLE
Ability to hide DNS names from Query Log ( pass or blocked )

### ISSUE THREAD

**Issue by sesipod** [AdguardTeam/AdGuardHome#1714]
Currently I have a few domains with a tone of hits per minute even seconds. This is completely expected behavior from the guest devices however it fills the query log and is very annoying to sort. 
Is there any plans to add support for hiding domains from the query log ?

![Screenshot_20200521-143506_Chrome](https://user-images.githubusercontent.com/1533744/82598538-6e749d00-9b70-11ea-9b82-efc2bc228f5f.jpg)

Pi-hole has this functionality already would be nice to have here.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/1717

Please upvote it

**Comment by Archive5** [comment]
Duplicate of #594
