### ISSUE TITLE
Device Specific DNS Whitelist

### ISSUE THREAD

**Issue by MercuryXIII** [AdguardTeam/AdGuardHome#1716]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y ] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Problem Description
If you need to whitelist a set of domains, it's universal, and can't be done per device

### Proposed Solution
Underneath client settings, allow us to add device specific whitelists. I use a list that blocks Microsoft Telementry but unfortunately, this list breaks Xbox LIVE functionality. At the current moment, I have the list added to my universal whitelist. 

### Alternatives Considered
N/A

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/435

**Comment by ameshkov** [comment]
>  I use a list that blocks Microsoft Telementry but unfortunately, this list breaks Xbox LIVE functionality. At the current moment, I have the list added to my universal whitelist.

Temporary solution: use `ctag`:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#-ctag

1. Mark your XBox with some tag
2. Add a rule like this: `@@||example.org^$ctag=TAG_NAME`
