### ISSUE TITLE
Exclude certain domains / IPs from statistics

### ISSUE THREAD

**Issue by adrianmace** [AdguardTeam/AdGuardHome#1717]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
A number of devices - monitoring and updaters - check frequently for the same hostnames. Due to the fact that the TTL is overriden by Adguardhome, these checks greatly skew the statistics. My monitoring device makes 21,600 requests to google.com a day - one every 4 seconds - for example.

My Swann cameras have a bug that's causing a lookup every 5 seconds to www.amazonaws.com. 17,280 times per 24 hours.

### Proposed Solution
Offer a way to remove certain domains (www.amazonaws.com) and certain IPs (192.168.1.2) from the statistics gathering process. Still apply the same customised filters and what not, but remove them from the statistics.

### Alternatives Considered
Currently bypassing the Adguardhome for these devices affected and going straight to upstream DNS.

### Additional Information
PiHole has this, but I like Adguardhome's UI and static Go binary more.

**Comment by ameshkov** [comment]
Well, let's see how many upvotes it gets.

**Comment by adrianmace** [comment]
> Well, let's see how many upvotes it gets.

Thanks for getting back to me. All the best.

**Comment by ameshkov** [comment]
One more similar feature request:
https://github.com/AdguardTeam/AdGuardHome/issues/1714

**Comment by Archive5** [comment]
first request about this #594 https://github.com/AdguardTeam/AdGuardHome/issues/594#issuecomment-469129412 and you can get benefit from #1164

**Comment by adrianmace** [comment]
Some images to highlight the problem:   
![image](https://user-images.githubusercontent.com/5071859/82747246-661f9a80-9dda-11ea-840b-dbccd2316374.png)
![image](https://user-images.githubusercontent.com/5071859/82747253-7b94c480-9dda-11ea-88cd-9683b99ccc51.png)

**Comment by ameshkov** [comment]
I wonder would it be enough if we simply add a Client setting: "Do not log queries"?

**Comment by adrianmace** [comment]
That would work for me. The reason they’re named is because I set that up in my search for this setting before realising it didn’t exist. 

I’d like to eventually be able to exclude _domains_, but per-client is good enough if it’s easier / faster to develop.

**Comment by Archive5** [comment]
> I wonder would it be enough if we simply add a Client setting: "Do not log queries"?

If implement, Would it be possible to mod it bit: "Do not display queries"? so we still have them to check when necessary

**Comment by Buddinski88** [comment]
Is there any info here on when this feature will be ready?
I currently have 120k requests in the log coming from my RaspberryPi with Raspberrymatic. Every 15 seconds it checks against my Fritzbox if two devices are online (presence detection). This distorts the statistics enormously :-)

**Comment by ameshkov** [comment]
Will only be done after the frontend rework.

Tbh, I'd like to keep this feature purely on the UI side (show smth like "X domains are hidden (N requests)").

**Comment by Buddinski88** [comment]
> Will only be done after the frontend rework.
Thank you for the update.

> Tbh, I'd like to keep this feature purely on the UI side (show smth like "X domains are hidden (N requests)").

In general that seems to be fine. Will that count then also be excluded from the statistics?

**Comment by ameshkov** [comment]
> In general that seems to be fine. Will that count then also be excluded from the statistics?

No, if it's purely frontend we won't be able to get rid of them there.

**Comment by Buddinski88** [comment]
> > In general that seems to be fine. Will that count then also be excluded from the statistics?
> 
> No, if it's purely frontend we won't be able to get rid of them there.

First of all, thank you for your feedback and sorry that it took me so long.
Basically I understand your answer, but it would only provide a real added value if the numbers are also excluded from the statistics. For example, the statement "5%" requests were blocked would be appropriate.
I think this adjustment is not a short term issue, but for the future - I think - everyone would benefit from exculpating certain devices from the statistics. Example from my side. Due to presence detection, my smarthome system asks my Fritzbox every 30 seconds if two devices are logged into the WLAN. That's X thousands of requests in a few days and that distorts the statistics enormously.

**Comment by danieletorelli** [comment]
Sometimes you might just want to hide some queries from the statistics, while some other times you might not even care of recording some queries at all.
I suppose that leaving the user free to choose would provide way better added value in both cases, since IMO the use cases are so vary that all assumptions here could be misleading.

**Comment by MattXcz** [comment]
I am also +1 for this future request... I have some IOT clients, which spam query log and statistics

**Comment by Toxicolo** [comment]
+1 from my side. Would really nice to a a filter or exclude option!

**Comment by NemoN** [comment]
+1 really an important feature

**Comment by MSlawik** [comment]
+1 !!!!

**Comment by jamboc88** [comment]
+1 !!

**Comment by ameshkov** [comment]
Okay, it's too popular to keep it on v1.0.0. We're doing the frontend rework&redesign in v0.108.0, let's squeeze this one there as well.

**Comment by MattXcz** [comment]
Stats + query log too.So we dont have these request over and over in log

**Comment by HyperCriSiS** [comment]
I also have deceives which do HUGE amounts of querys. It would be good to be able to drop specific domains completely. No log at all.

**Comment by danbo** [comment]
I was going to ask about a slightly different feature - separate statistics out by interface or subnet.

Ultimately I think we're all saying the same thing here - we would very much appreciate a way to filter noise out of statistics. (domain/ips/subnets/interfaces)

**Comment by jiangmw** [comment]
+1

**Comment by ainar-g** [comment]
@jiangmw, please use reactions on the OP instead of “+1”-like comments.  Thanks.

In case people watching this issue have missed it, the most recent releases of AdGuard Home have the feature of ignoring requests by their query domain names, but it's currently only available through the configuration file.  API and UI are coming soon.

**Comment by ainar-g** [comment]
Implemented for both domains and clients on Edge and in the upcoming release.

**Comment by rfgamaral** [comment]
Is it possible to ignore wildcard domains? Adding `*.example.com` doesn't seem to be working :(

**Comment by don-dolarson** [comment]
> Is it possible to ignore wildcard domains? Adding `*.example.com` doesn't seem to be working :(

Wildcards doesn't seem to work for me neither on latest v0.107.32. Anyone else?

**Comment by ainar-g** [comment]
@rfgamaral, @don-dolarson, they aren't supported now.  Please upvote #5720.  (Do not post “+1” comments as one cannot sort by those in Github; a “:+1:” reaction on the top comment is enough.)
