### ISSUE TITLE
Make cache and edns work together.

### ISSUE THREAD

**Issue by ju0594** [AdguardTeam/AdGuardHome#1720]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Cache is not working when EDNS is enabled.
### Proposed Solution

Is it possible to work both at the same time?

**Comment by ameshkov** [comment]
Hm, how so, the cache should be working properly when EDNS is enabled.

How do you test it?

**Comment by ju0594** [comment]
> Hm, how so, the cache should be working properly when EDNS is enabled.
> 
> How do you test it?

sorry, this is my fault. one of my upstream dns use coredns.

Because I don't want to send edns to the coredns, but other upstream dns need edns.

so I use `rewrite edns0 subnet set 0 0` to delete the edns in coredns. Doing so seems to make the cache not work properly.

when I delete this line of code. cache and edns can work both at the same time.

By the way, does anyone know how to properly rewrite or delete the edns in a DNS request?
