### ISSUE TITLE
mercadolibre.com.ar

### ISSUE THREAD

**Issue by pcarbonel** [AdguardTeam/AdGuardHome#1722]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

mercadolibre.com.ar site not show as intended I add even rules to site exclusion but the page not show
I try several browsers with same effect

* **Version of AdGuard Home server:**
  * 0.102.0
* **How did you setup DNS configuration:**
1.1.1.1
1.0.0.1
https://dns.cloudflare.com/dns-query
https://dns.cloudflare.com/dns-query
tls://1.1.1.1
https://dns10.quad9.net/dns-query
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B+
* **Operating system and version:**
  Linux AdguardHome 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

### Expected Behavior
The site no show as any regular site

### Actual Behavior
page show only as text no image not format

### Screenshots

page show as text

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #338](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/338) via [**ZenHub**](https://www.zenhub.com/)
