### ISSUE TITLE
DNS rewrites cause panic logging stats

### ISSUE THREAD

**Issue by chriskillpack** [AdguardTeam/AdGuardHome#1724]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **Operating system and version:**
  * Raspbian

### Expected Behavior
Lookups for DNS rewrites should return a DNS answer with the correct rewrite

### Actual Behavior
server panic
```
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).updateStats(0xc000071180, 0xc0001c0240, 0x135d3c, 0x0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/chris/code/src/github.com/AdguardTeam/AdGuardHome/dnsforward/stats.go:66 +0x31f
github.com/AdguardTeam/AdGuardHome/dnsforward.processQueryLogsAndStats(0xc0001381c0, 0x5)
	/Users/chris/code/src/github.com/AdguardTeam/AdGuardHome/dnsforward/stats.go:51 +0x184
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).handleDNSRequest(0xc000071180, 0xc00016e700, 0xc0001c0240, 0x0, 0x0)
	/Users/chris/code/src/github.com/AdguardTeam/AdGuardHome/dnsforward/handle_dns.go:52 +0x235
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0xc00016e700, 0xc0001c0240, 0x25, 0x25)
```

### Additional Information
This issue was not happening with the prior release. I've instrumented the server and reproduced the issue. The rewrite logic generates the correct CNAME and A/AAAA entries.

Later in the DNS request handling `processFilteringAfterResponse` will [replace](https://github.com/AdguardTeam/AdGuardHome/blob/master/dnsforward/handle_dns.go#L220) `d.Req.Question` with `ctx.origQuestion` for a successful rewrite. However there is a [path](https://github.com/AdguardTeam/AdGuardHome/blob/master/dnsforward/filter.go#L57) through `filterDNSRequest` which does not set `ctx.origQuestion`. This causes `d.Req.Question[0].Name` to become the empty string and hence the slice out of range error in `updateStats`, https://github.com/AdguardTeam/AdGuardHome/blob/master/dnsforward/stats.go#L61

**Comment by szolin** [comment]
It's already fixed in #1704
Thanks for the explanation anyway!
