### ISSUE TITLE
Error: control/filtering/refresh | filters update procedure is already running | 500

### ISSUE THREAD

**Issue by coolbele** [AdguardTeam/AdGuardHome#1729]
v0.102.0
Error: control/filtering/refresh | filters update procedure is already running | 500

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by coolbele** [comment]
> 要解决此问题，我们需要查看AdGuard主日志。
> 
> 1. [配置](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard主页以收集日志：
>    
>    * 指定 `log_file`
>    * 设置`verbose`于`True`
> 2. 重新启动AdGuard Home并重现问题
> 3. 在此处发布日志文件。

2020/05/25 23:21:02 25341#14 [debug] GET /control/filtering/status
2020/05/25 23:21:02 25341#130 [debug] GET /control/tls/status
2020/05/25 23:21:02 25341#82 [debug] GET /control/profile
2020/05/25 23:21:02 25341#82 [debug] GET /control/tls/status
2020/05/25 23:21:02 25341#130 [debug] GET /control/profile
2020/05/25 23:21:02 25341#14 [debug] GET /control/filtering/status
2020/05/25 23:21:02 25341#14 [debug] GET /control/status
2020/05/25 23:21:02 25341#14 [debug] GET /control/status
2020/05/25 23:20:58 25341#15 [debug] POST /control/filtering/remove_url
2020/05/25 23:20:54 25341#15 [debug] GET /control/profile
2020/05/25 23:20:54 25341#14 [debug] GET /control/tls/status
2020/05/25 23:20:54 25341#49 [debug] GET /control/filtering/status
2020/05/25 23:20:54 25341#15 [debug] GET /control/profile
2020/05/25 23:20:54 25341#49 [debug] GET /control/tls/status
2020/05/25 23:20:54 25341#14 [debug] GET /control/filtering/status
2020/05/25 23:20:54 25341#14 [debug] GET /control/status
2020/05/25 23:20:54 25341#14 [debug] GET /control/status
2020/05/25 23:20:30 25341#58 [debug] dnsServer.Resolve: hosts-file.net: [{3.234.198.254 }]
2020/05/25 23:20:30 25341#59 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 9 ms
2020/05/25 23:20:30 25341#59 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream 10.0.10.250:53 successfully finished exchange of ;hosts-file.net.	IN	 A. Elapsed 9 ms.
2020/05/25 23:20:30 25341#60 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 9 ms
2020/05/25 23:20:30 25341#60 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream 10.0.10.250:53 successfully finished exchange of ;hosts-file.net.	IN	 AAAA. Elapsed 9 ms.
2020/05/25 23:20:30 25341#59 [debug] 10.0.10.250:53: response: ok
2020/05/25 23:20:30 25341#60 [debug] 10.0.10.250:53: response: ok
2020/05/25 23:20:30 25341#59 [debug] 10.0.10.250:53: sending request A hosts-file.net.
2020/05/25 23:20:30 25341#60 [debug] 10.0.10.250:53: sending request AAAA hosts-file.net.
2020/05/25 23:20:30 25341#58 [debug] github.com/AdguardTeam/AdGuardHome/home.customDialContext(): network:tcp  addr:hosts-file.net:443
2020/05/25 23:20:30 25341#81 [debug] github.com/AdguardTeam/AdGuardHome/home.(*homeContext).getDataDir(): Downloading update for filter 3 from https://hosts-file.net/ad_servers.txt
2020/05/25 23:20:30 25341#81 [debug] Filters: updating...
2020/05/25 23:20:30 25341#81 [debug] Writing YAML file: /etc/AdGuardHome.yaml
2020/05/25 23:20:30 25341#81 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): Loading filter 3 contents to: /usr/bin/AdGuardHome/data/filters/3.txt
2020/05/25 23:20:30 25341#81 [debug] filter: set properties: https://hosts-file.net/ad_servers.txt: {hpHosts - Ad and Tracking servers only https://hosts-file.net/ad_servers.txt true}
2020/05/25 23:20:30 25341#81 [debug] POST /control/filtering/set_url
2020/05/25 23:20:25 25341#81 [debug] GET /control/filtering/status
2020/05/25 23:20:24 25341#81 [debug] GET /control/filtering/status
2020/05/25 23:20:22 25341#81 [debug] Access: updated lists: 0, 0, 0
2020/05/25 23:20:22 25341#81 [debug] Writing YAML file: /etc/AdGuardHome.yaml
2020/05/25 23:20:22 25341#81 [debug] POST /control/access/set
2020/05/25 23:20:21 25341#73 [info] Entering the tcp listener loop on [::]:5553
2020/05/25 23:20:21 25341#72 [info] Entering the UDP listener loop on [::]:5553
2020/05/25 23:20:21 25341#81 [info] Listening to tcp://[::]:5553
2020/05/25 23:20:21 25341#81 [info] Creating the TCP server socket
2020/05/25 23:20:21 25341#81 [info] Listening to udp://[::]:5553
2020/05/25 23:20:21 25341#81 [info] Creating the UDP server socket
2020/05/25 23:20:21 25341#81 [info] DNS cache is enabled
2020/05/25 23:20:21 25341#81 [info] Starting the DNS proxy server
2020/05/25 23:20:21 25341#81 [info] Upstream 3: 202.96.128.86:53
2020/05/25 23:20:21 25341#81 [info] Upstream 2: 202.96.134.33:53
2020/05/25 23:20:21 25341#81 [info] Upstream 1: 119.29.29.29:53
2020/05/25 23:20:21 25341#81 [info] Upstream 0: 10.0.10.250:53
2020/05/25 23:20:21 25341#81 [info] Bootstrap 5: 202.96.128.86
2020/05/25 23:20:21 25341#81 [info] Bootstrap 4: 202.96.134.33
2020/05/25 23:20:21 25341#81 [info] Bootstrap 3: 202.96.128.86
2020/05/25 23:20:21 25341#81 [info] Bootstrap 2: 202.96.134.33
2020/05/25 23:20:21 25341#81 [info] Bootstrap 1: 119.29.29.29
2020/05/25 23:20:21 25341#81 [info] Bootstrap 0: 10.0.10.250
2020/05/25 23:20:21 25341#81 [info] Stopped the DNS proxy server
2020/05/25 23:20:21 25341#105 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2020/05/25 23:20:21 25341#106 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2020/05/25 23:20:21 25341#81 [info] Stopping the DNS proxy server
2020/05/25 23:20:21 25341#81 [info] Start reconfiguring the server
2020/05/25 23:20:21 25341#81 [debug] Writing YAML file: /etc/AdGuardHome.yaml
2020/05/25 23:20:21 25341#81 [debug] POST /control/dns_config
2020/05/25 23:20:19 25341#106 [info] Entering the tcp listener loop on [::]:5553
2020/05/25 23:20:19 25341#105 [info] Entering the UDP listener loop on [::]:5553
2020/05/25 23:20:19 25341#81 [info] Listening to tcp://[::]:5553
2020/05/25 23:20:19 25341#81 [info] Creating the TCP server socket
2020/05/25 23:20:19 25341#81 [info] Listening to udp://[::]:5553
2020/05/25 23:20:19 25341#81 [info] Creating the UDP server socket
2020/05/25 23:20:19 25341#81 [info] DNS cache is enabled
2020/05/25 23:20:19 25341#81 [info] Starting the DNS proxy server
2020/05/25 23:20:19 25341#81 [info] Upstream 3: 202.96.128.86:53
2020/05/25 23:20:19 25341#81 [info] Upstream 2: 202.96.134.33:53
2020/05/25 23:20:19 25341#81 [info] Upstream 1: 119.29.29.29:53
2020/05/25 23:20:19 25341#81 [info] Upstream 0: 10.0.10.250:53
2020/05/25 23:20:19 25341#81 [info] Bootstrap 5: 202.96.128.86
2020/05/25 23:20:19 25341#81 [info] Bootstrap 4: 202.96.134.33
2020/05/25 23:20:19 25341#81 [info] Bootstrap 3: 202.96.128.86
2020/05/25 23:20:19 25341#81 [info] Bootstrap 2: 202.96.134.33
2020/05/25 23:20:19 25341#81 [info] Bootstrap 1: 119.29.29.29
2020/05/25 23:20:19 25341#81 [info] Bootstrap 0: 10.0.10.250
2020/05/25 23:20:19 25341#81 [info] Stopped the DNS proxy server
2020/05/25 23:20:19 25341#40 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2020/05/25 23:20:19 25341#41 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2020/05/25 23:20:19 25341#81 [info] Stopping the DNS proxy server
2020/05/25 23:20:19 25341#81 [info] Start reconfiguring the server
2020/05/25 23:20:19 25341#81 [debug] Writing YAML file: /etc/AdGuardHome.yaml
2020/05/25 23:20:19 25341#81 [debug] POST /control/dns_config
2020/05/25 23:20:18 25341#81 [debug] DNS 202.96.128.86 works OK
2020/05/25 23:20:18 25341#81 [debug] 202.96.128.86:53: response: ok
2020/05/25 23:20:18 25341#81 [debug] 202.96.128.86:53: sending request A google-public-dns-a.google.com.
2020/05/25 23:20:18 25341#81 [debug] Checking if DNS 202.96.128.86 works...
2020/05/25 23:20:18 25341#81 [debug] DNS 202.96.134.33 works OK
2020/05/25 23:20:18 25341#81 [debug] 202.96.134.33:53: response: ok
2020/05/25 23:20:18 25341#81 [debug] 202.96.134.33:53: sending request A google-public-dns-a.google.com.
2020/05/25 23:20:18 25341#81 [debug] Checking if DNS 202.96.134.33 works...
2020/05/25 23:20:18 25341#81 [debug] DNS 119.29.29.29 works OK
2020/05/25 23:20:18 25341#81 [debug] 119.29.29.29:53: response: ok
2020/05/25 23:20:18 25341#81 [debug] 119.29.29.29:53: sending request A google-public-dns-a.google.com.
2020/05/25 23:20:18 25341#81 [debug] Checking if DNS 119.29.29.29 works...
2020/05/25 23:20:18 25341#81 [debug] DNS 10.0.10.250 works OK
2020/05/25 23:20:18 25341#81 [debug] 10.0.10.250:53: response: ok
2020/05/25 23:20:18 25341#81 [debug] 10.0.10.250:53: sending request A google-public-dns-a.google.com.
2020/05/25 23:20:18 25341#81 [debug] Checking if DNS 10.0.10.250 works...
2020/05/25 23:20:18 25341#81 [debug] POST /control/test_upstream_dns
2020/05/25 23:20:09 25341#81 [debug] GET /control/dns_info
2020/05/25 23:20:09 25341#50 [debug] GET /control/access/list
2020/05/25 23:20:09 25341#50 [debug] GET /control/dns_info
2020/05/25 23:20:09 25341#81 [debug] GET /control/access/list
2020/05/25 23:19:59 25341#81 [debug] GET /control/filtering/status
2020/05/25 23:19:59 25341#50 [debug] GET /control/querylog_info
2020/05/25 23:19:59 25341#81 [debug] GET /control/querylog_info
2020/05/25 23:19:59 25341#50 [debug] GET /control/filtering/status
2020/05/25 23:19:56 25341#50 [debug] GET /control/clients/find?
2020/05/25 23:19:56 25341#50 [debug] GET /control/filtering/status
2020/05/25 23:19:56 25341#81 [debug] GET /control/clients/find?
2020/05/25 23:19:56 25341#50 [debug] QueryLog: prepared data (0/0) older than 2020-05-25 15:19:56.200293318 +0800 CST m=+8.135063769 in 34.455µs
2020/05/25 23:19:56 25341#50 [debug] GET /control/querylog?filter_domain=&filter_client=&filter_question_type=&filter_response_status=&older_than=
2020/05/25 23:19:56 25341#14 [debug] GET /control/querylog_info
2020/05/25 23:19:56 25341#14 [debug] QueryLog: prepared data (0/0) older than 2020-05-25 15:19:56.1951481 +0800 CST m=+8.129918555 in 75.513µs
2020/05/25 23:19:56 25341#81 [debug] GET /control/filtering/status
2020/05/25 23:19:56 25341#50 [debug] GET /control/querylog_info
2020/05/25 23:19:56 25341#14 [debug] GET /control/querylog?filter_domain=&filter_client=&filter_question_type=&filter_response_status=&older_than=
2020/05/25 23:19:55 25341#81 [debug] GET /control/clients/find?
2020/05/25 23:19:55 25341#81 [debug] GET /control/clients/find?
2020/05/25 23:19:55 25341#28 [debug] dnsServer.Resolve: static.adguard.com: [{104.20.30.130 } {104.20.31.130 } {2606:4700:10::6814:1e82 } {2606:4700:10::6814:1f82 }]
2020/05/25 23:19:55 25341#30 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 14 ms
2020/05/25 23:19:55 25341#30 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream 10.0.10.250:53 successfully finished exchange of ;static.adguard.com.	IN	 AAAA. Elapsed 14 ms.
2020/05/25 23:19:55 25341#30 [debug] 10.0.10.250:53: response: ok
2020/05/25 23:19:55 25341#29 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 12 ms
2020/05/25 23:19:55 25341#81 [debug] GET /control/stats_info
2020/05/25 23:19:55 25341#29 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream 10.0.10.250:53 successfully finished exchange of ;static.adguard.com.	IN	 A. Elapsed 11 ms.
2020/05/25 23:19:55 25341#29 [debug] 10.0.10.250:53: response: ok
2020/05/25 23:19:55 25341#50 [debug] Stats: prepared data in 211.344µs
2020/05/25 23:19:55 25341#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin
2020/05/25 23:19:55 25341#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin...
2020/05/25 23:19:55 25341#50 [debug] GET /control/stats
2020/05/25 23:19:55 25341#49 [debug] GET /control/profile
2020/05/25 23:19:55 25341#15 [debug] GET /control/access/list
2020/05/25 23:19:55 25341#82 [debug] GET /control/tls/status
2020/05/25 23:19:55 25341#81 [debug] GET /control/stats_info
2020/05/25 23:19:55 25341#82 [debug] GET /control/tls/status
2020/05/25 23:19:55 25341#30 [debug] 10.0.10.250:53: sending request AAAA static.adguard.com.
2020/05/25 23:19:55 25341#29 [debug] 10.0.10.250:53: sending request A static.adguard.com.
2020/05/25 23:19:55 25341#28 [debug] github.com/AdguardTeam/AdGuardHome/home.customDialContext(): network:tcp  addr:static.adguard.com:443
2020/05/25 23:19:55 25341#14 [debug] github.com/AdguardTeam/AdGuardHome/home.handleGetVersionJSON(): Downloading data from https://static.adguard.com/adguardhome/release/version.json
2020/05/25 23:19:55 25341#15 [debug] GET /control/profile
2020/05/25 23:19:55 25341#50 [debug] Stats: prepared data in 300.571µs
2020/05/25 23:19:55 25341#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin
2020/05/25 23:19:55 25341#50 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin...
2020/05/25 23:19:55 25341#50 [debug] GET /control/stats
2020/05/25 23:19:55 25341#49 [debug] GET /control/access/list
2020/05/25 23:19:55 25341#49 [debug] GET /control/status
2020/05/25 23:19:55 25341#49 [debug] GET /control/status
2020/05/25 23:19:54 25341#50 [debug] Auth: created session b706e66eb2235a3f17a081729d8a81ca809accfb02303906f1296e4850fb0ac3: expire=1592983194
2020/05/25 23:19:54 25341#50 [debug] POST /control/login
2020/05/25 23:19:50 25341#49 [debug] Auth: invalid cookie value: agh_session=b5dcd181c22fda536b94aa42586450a4726e5b9aee1cc234832ddd41d1741c7c
2020/05/25 23:19:48 25341#43 [debug] Filters: update finished
2020/05/25 23:19:48 25341#43 [debug] Filters: updating...
2020/05/25 23:19:48 25341#9 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin
2020/05/25 23:19:48 25341#41 [info] Entering the tcp listener loop on [::]:5553
2020/05/25 23:19:48 25341#9 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin...
2020/05/25 23:19:48 25341#40 [info] Entering the UDP listener loop on [::]:5553
2020/05/25 23:19:48 25341#39 [debug] command arp has failed: exec: "arp": executable file not found in $PATH code:-1
2020/05/25 23:19:48 25341#9 [info] Listening to tcp://[::]:5553
2020/05/25 23:19:48 25341#39 [debug] github.com/AdguardTeam/AdGuardHome/home.(*clientsContainer).addFromSystemARP(): executing arp [arp -a]
2020/05/25 23:19:48 25341#9 [info] Creating the TCP server socket
2020/05/25 23:19:48 25341#9 [info] Listening to udp://[::]:5553
2020/05/25 23:19:48 25341#9 [info] Creating the UDP server socket
2020/05/25 23:19:48 25341#9 [info] DNS cache is enabled
2020/05/25 23:19:48 25341#9 [info] Starting the DNS proxy server
2020/05/25 23:19:48 25341#9 [debug] initialized filtering engine
2020/05/25 23:19:48 25341#7 [debug] Clients: added 10 client aliases from system hosts-file
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'ip6-allrouters' -> 'ff02::2' [10]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'ip6-allnodes' -> 'ff02::1' [9]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'ppq.lan' -> '10.0.10.118' [8]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'localhost' -> '127.0.0.1' [7]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'smartplugconnect.phicomm.com' -> '10.0.10.10' [6]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'cz3.lan' -> '10.0.10.49' [5]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'cz.lan' -> '10.0.10.171' [4]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'ip6-loopback' -> '::1' [3]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'ip6-localhost' -> '::1' [2]
2020/05/25 23:19:48 25341#7 [debug] Clients: added 'OpenWrt' -> '10.0.10.250' [1]
2020/05/25 23:19:48 25341#7 [debug] Clients: removed 0 client aliases
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address 10.0.10.250 -> OpenWrt
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added 10.0.10.250 -> OpenWrt
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address 10.0.10.10 -> smartplugconnect.phicomm.com
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added 10.0.10.10 -> smartplugconnect.phicomm.com
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address 10.0.10.49 -> cz3.lan
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added 10.0.10.49 -> cz3.lan
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address 10.0.10.171 -> cz.lan
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added 10.0.10.171 -> cz.lan
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address 10.0.10.118 -> ppq.lan
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added 10.0.10.118 -> ppq.lan
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: loading hosts from file /tmp/hosts/dhcp.cfg01411c
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address ff02::2 -> ip6-allrouters
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added ff02::2 -> ip6-allrouters
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address ff02::1 -> ip6-allnodes
2020/05/25 23:19:48 25341#1 [info] Go to http://10.0.10.250:3000
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added ff02::1 -> ip6-allnodes
2020/05/25 23:19:48 25341#1 [info] Go to http://119.144.148.83:3000
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added ::1 -> ip6-loopback
2020/05/25 23:19:48 25341#1 [info] Go to http://59.39.242.162:3000
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added ::1 -> ip6-localhost
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address ::1 -> localhost
2020/05/25 23:19:48 25341#1 [info] Go to http://127.0.0.1:3000
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added ::1 -> localhost
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: added 127.0.0.1 -> localhost
2020/05/25 23:19:48 25341#7 [debug] AutoHosts: loading hosts from file /etc/hosts
2020/05/25 23:19:48 25341#1 [info] AdGuard Home is available on the following addresses:
2020/05/25 23:19:48 25341#1 [debug] Start AutoHosts module
2020/05/25 23:19:48 25341#1 [debug] Web: applying new TLS configuration
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): File /usr/bin/AdGuardHome/data/filters/1575618240.txt, id 1575618240, length 225768
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): Loading filter 1575618240 contents to: /usr/bin/AdGuardHome/data/filters/1575618240.txt
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): File /usr/bin/AdGuardHome/data/filters/4.txt, id 4, length 35585
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): Loading filter 4 contents to: /usr/bin/AdGuardHome/data/filters/4.txt
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): File /usr/bin/AdGuardHome/data/filters/2.txt, id 2, length 441137
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): Loading filter 2 contents to: /usr/bin/AdGuardHome/data/filters/2.txt
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): File /usr/bin/AdGuardHome/data/filters/1.txt, id 1, length 693492
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.(*Filtering).load(): Loading filter 1 contents to: /usr/bin/AdGuardHome/data/filters/1.txt
2020/05/25 23:19:48 25341#1 [info] Upstream 5: 202.96.128.86:53
2020/05/25 23:19:48 25341#1 [info] Upstream 4: 202.96.134.33:53
2020/05/25 23:19:48 25341#1 [info] Upstream 3: 202.96.128.86:53
2020/05/25 23:19:48 25341#1 [info] Upstream 2: 202.96.134.33:53
2020/05/25 23:19:48 25341#1 [info] Upstream 1: 119.29.29.29:53
2020/05/25 23:19:48 25341#1 [info] Upstream 0: 10.0.10.250:53
2020/05/25 23:19:48 25341#1 [info] Bootstrap 5: 202.96.128.86
2020/05/25 23:19:48 25341#1 [info] Bootstrap 4: 202.96.134.33
2020/05/25 23:19:48 25341#1 [info] Bootstrap 3: 202.96.128.86
2020/05/25 23:19:48 25341#1 [info] Bootstrap 2: 202.96.134.33
2020/05/25 23:19:48 25341#1 [info] Bootstrap 1: 119.29.29.29
2020/05/25 23:19:48 25341#1 [info] Bootstrap 0: 10.0.10.250
2020/05/25 23:19:48 25341#1 [debug] Stats: initialized
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/stats.createObject(): Deleting old units...
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin...
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).dbOpen(): db.Open
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).dbOpen(): db.Open...
2020/05/25 23:19:48 25341#1 [info] Initialize web module
2020/05/25 23:19:48 25341#1 [info] Auth: initialized.  users:1  sessions:0
2020/05/25 23:19:48 25341#1 [info] Initializing auth module: /usr/bin/AdGuardHome/data/sessions.db
2020/05/25 23:19:48 25341#1 [debug] Writing YAML file: /etc/AdGuardHome.yaml
2020/05/25 23:19:48 25341#1 [debug] Clients: added 0 client aliases from DHCP
2020/05/25 23:19:48 25341#1 [debug] Clients: removed 0 client aliases
2020/05/25 23:19:48 25341#1 [debug] Reading config file: /etc/AdGuardHome.yaml
2020/05/25 23:19:48 25341#1 [debug] github.com/AdguardTeam/AdGuardHome/home.upgradeConfig(): got schema version 6
2020/05/25 23:19:48 25341#1 [debug] Current working directory is /usr/bin/AdGuardHome
2020/05/25 23:19:48 25341#1 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
2020/05/25 23:19:48 24106#20 [info] Stopped
2020/05/25 23:19:48 24106#13 [debug] Finished AutoHosts update loop
2020/05/25 23:19:48 24106#20 [debug] Closed all DNS modules
2020/05/25 23:19:48 24106#20 [debug] querylog: there's nothing to write to a file
2020/05/25 23:19:48 24106#20 [debug] Stats: closed
2020/05/25 23:19:48 24106#20 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).Close(): db.Close
2020/05/25 23:19:48 24106#20 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).Close(): db.Close...
2020/05/25 23:19:48 24106#20 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).commitTxn(): tx.Commit
2020/05/25 23:19:48 24106#20 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).flushUnitToDB(): Flushing unit 441775
2020/05/25 23:19:48 24106#20 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin
2020/05/25 23:19:48 24106#20 [debug] github.com/AdguardTeam/AdGuardHome/stats.(*statsCtx).beginTxn(): db.Begin...
2020/05/25 23:19:48 24106#20 [info] Stopped the DNS proxy server
2020/05/25 23:19:48 24106#49 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2020/05/25 23:19:48 24106#50 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2020/05/25 23:19:48 24106#20 [info] Stopping the DNS proxy server
2020/05/25 23:19:48 24106#20 [info] Stopped HTTP server
2020/05/25 23:19:48 24106#20 [info] Stopping HTTP server...
2020/05/25 23:19:48 24106#20 [info] Stopping AdGuard Home
2020/05/25 23:19:48 24106#20 [info] Received signal 'terminated'
2020/05/25 23:19:15 24106#82 [info] Auth: invalid user name or password: name='root'
2020/05/25 23:19:15 24106#82 [debug] POST /control/login
2020/05/25 23:19:04 24106#82 [info] Auth: invalid user name or password: name='admin'
2020/05/25 23:19:04 24106#82 [debug] POST /control/login
2020/05/25 23:18:59 24106#82 [info] Auth: invalid user name or password: name='admin'
2020/05/25 23:18:59 24106#82 [debug] POST /control/login
2020/05/25 23:18:52 24106#82 [info] Auth: invalid user name or password: name='admin'
2020/05/25 23:18:52 24106#82 [debug] POST /control/login
2020/05/25 23:18:43 24106#81 [debug] Auth: invalid cookie value: agh_session=b5dcd181c22fda536b94aa42586450a4726e5b9aee1cc234832ddd41d1741c7c
2020/05/25 23:18:43 24106#81 [debug] Auth: invalid cookie value: agh_session=b5dcd181c22fda536b94aa42586450a4726e5b9aee1cc234832ddd41d1741c7c

**Comment by ameshkov** [comment]
@coolbele hm, nothing too problematic in the log.

Do you have that issue after restarting AdGuard Home?

**Comment by ian-mcpherson** [comment]
Check the permissions are correct on the data folder and the subfolders, There appears to be an issue folder and file permissions. I am trying to figure what the issue is but so far no luck.

**Comment by xmke** [comment]
> Check the permissions are correct on the data folder and the subfolders, There appears to be an issue folder and file permissions. I am trying to figure what the issue is but so far no luck.

Fixed the issue for me, thanks !
