### ISSUE TITLE
Rules Special characters "^" not working as expected

### ISSUE THREAD

**Issue by kkkgo** [AdguardTeam/AdGuardHome#1732]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0

### Expected Behavior
>^ — separator character mark. Unlike browser ad blocking, there's nothing to "separate" in a hostname, so the only purpose of this character is to mark the end of the hostname.

rule: ||88911.us^
example1 www.88911.us    ---  match
example2 dualstack.log-334788911.us-east-1.elb.amazonaws.com   --notmatch
### Actual Behavior
```
rule: ||88911.us^
example1 www.88911.us    ---  match
example2 dualstack.log-334788911.us-east-1.elb.amazonaws.com   --match
```

**Comment by kkkgo** [comment]
I think the character "-" will not work as expected：
```
rule： ||github.com^
match:  dualstack.log.github.com-east-1.elb.amazonaws.com
not match : dualstack.log.github.com1-east-1.elb.amazonaws.com
``

**Comment by DandelionSprout** [comment]
I was not able to replicate the `88911.us` example, but I was indeed able to replicate the `||github.com^`.

I can also tell from my testing that "AdGuard for Windows" and uBlock Origin are unaffected, meaning that the problem is indeed somewhere in AdGuard Home.
