### ISSUE TITLE
When anonymize IPs is enabled, trim IPs to /16

### ISSUE THREAD

**Issue by Kagura-Nanaa** [AdguardTeam/AdGuardHome#1741]
I turned on anonymous ip in the settings, but I can still see the client ip in the logs. This is the latest version

**Comment by ameshkov** [comment]
Could it be that you're checking old log items?

**Comment by GKPMC** [comment]
> 可能是您正在检查旧的日志项目吗？

No, I cleared the log, it still shows the full ip

**Comment by ameshkov** [comment]
I cannot reproduce this:(

Could you please show a screenshot, maybe I am missing something.

**Comment by GKPMC** [comment]
Sorry, I didn't make my point clear, I meant to hide the IP completely, or just show 123.123.xxx.xxx
![Screenshot_20200601210819](https://user-images.githubusercontent.com/44108528/83412151-3a408c80-a44c-11ea-9d6b-78e52ffd7a64.png)

**Comment by GKPMC** [comment]
> 我无法重现此内容：(
> 
> 您能否显示屏幕截图，也许我丢失了一些东西。

Sorry, I didn't make my point clear, I meant to hide the IP completely, or just show 123.123.xxx.xxx
![Screenshot_20200601210819](https://user-images.githubusercontent.com/44108528/83412245-5b08e200-a44c-11ea-8879-8206b0de741f.png)

**Comment by ameshkov** [comment]
But this is not about that, this feature means that AdGuard Home will anonymize IP addresses of the clients that make DNS queries to it, it can't do anything with it's own IP.

**Comment by GKPMC** [comment]
> 但这不是关于这一点，此功能意味着AdGuard Home将匿名化对它进行 DNS 查询的客户端的 IP 地址，它不能使用它自己的 IP 执行任何操作。
> 
> 匿名意味着它转换 123.123.123.123 -- > 123.123.123.0

I don't think that's enough, it should be 123.123.123.123 to 123.123.0.0

**Comment by ameshkov** [comment]
@GKPMC could you please explain why? I don't see much benefit from that.

你可以用中文

**Comment by GKPMC** [comment]
> @GKPMC您能否解释为什么？我看不到有什么好处。
> 
> 你可以用中文

因为我把它部署在服务器上对外提供dns解析,我希望它可以不记录ip地址以保证隐私,只屏蔽最后一串数字仍然可以查询到使用者所在的省份

**Comment by ameshkov** [comment]
这有意义，我们会做好

**Comment by GKPMC** [comment]
> 这充足，我们会做好

非常感谢
