### ISSUE TITLE
Hope

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1743]
Openwrt x64 within AdguardHome in a mini PC.
Hope add a new function:anti BGP hijacking.
More information:isbgpsafeyet.com

**Comment by DandelionSprout** [comment]
Is this something that is even physically possible to implement on a user's end, and not just on the ISP's end?

If yes, then this could probably be moved to #1446, where this rather shortly worded drive-by request could be elaborated on and assisted on by AdGuard Home's hardcore security enthusiasts.

**Comment by ameshkov** [comment]
I don't think this is in the scope of a home server.

The measures by that link need to be deployed by ISPs
