### ISSUE TITLE
Connected client number

### ISSUE THREAD

**Issue by sheminasalam** [AdguardTeam/AdGuardHome#1745]
Can you add a tab in the dashboard to see how many devices are currently connected to Adguard? And also what all are these? I am asking because, whenever I have to restart Adguard host system my router sets the secondary DNS address as defaults and wont change until the router is rebooted or connection reset. In those circumstances it would be helpful to know which all and how may clients are presently connected.

**Comment by ameshkov** [comment]
Devices do not maintain some persistent connections to AdGuard, they make requests when they need to.

So it would quite problematic to define what devices we consider "connected".

**Comment by sheminasalam** [comment]
I have been using pihole for a long time and in that I had the option to view the connected clients. Thats why I requested for this function.

**Comment by ameshkov** [comment]
Btw, how does it work in Pi-Hole? Which clients they consider "connected"?

**Comment by sheminasalam** [comment]
I have limited knowledge on its technical side but if you are familiar with pihole, its there in the dashboard itself. It helped me to know if my router was pulling queries from pihole or not. Maybe they were checking the persistence with which queries arrives. I think so because in the present IoT system there are negligible devices which doesn't pull queries which in a very short span of time. Its true in the case of any routers or handheld devices. So if a device doesn't pull quires for a particular amount of time, it might be deemed disconnected.

**Comment by werlitong** [comment]
> Btw, how does it work in Pi-Hole? Which clients they consider "connected"?

Probably they consider devices that in the past 24h done queries to server.

**Comment by sheminasalam** [comment]
Nop, i dont think 24 hours is too much time frame. Since we are setting our DNS mostly in router which is connected to multiple devices, I believe a quire from router inevitable within a minute or so. And also now most of the routers check if the network is online and for this they ping an address provided by the parent company. For example my tenda router at regular intervals check with the address api.cloud.tenda.com.cn . So if adguard can find such regular address and the frequency it repeats, it can ensure that the device is online or offline within a short interval of time.
