### ISSUE TITLE
DNS Rewrite appears to be broken in master/Beta build

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#1746]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0-36-g391e (local build from master branch)
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Container (LXC)
* **Operating system and version:**
  * Ubuntu 18.04

### Expected Behavior

I have been running a build that is based on master branch (built on this git hash https://github.com/AdguardTeam/AdGuardHome/commit/391e619979e1849947d55eac78a6664745e4d288) and noticed that the rewrite seems to be broken since the changes to support this wildcard domain name exception feature https://github.com/AdguardTeam/AdGuardHome/issues/1547

So I have an rewrite for `*.reddit.com` pointing to `dualstack.reddit.map.fastly.net`

Same rewrite on current stable build 
```
❯ dig old.reddit.com
; <<>> DiG 9.10.6 <<>> old.reddit.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39520
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;old.reddit.com.			IN	A

;; ANSWER SECTION:
old.reddit.com.		60	IN	CNAME	dualstack.reddit.map.fastly.net.
dualstack.reddit.map.fastly.net. 300 IN	A	151.101.17.140
```

While we are on DNS Rewrite page, noticed that adding any new rewrites throws the following error message even though it is successful. In browser network console, you can see the rewrite endpoint responds with 200 status code and can see the rewrite when you refresh the page manually.

```
TypeError: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

### Actual Behavior

```
❯ dig old.reddit.com
;; Question section mismatch: got dualstack.reddit.map.fastly.net/A/IN
;; Question section mismatch: got dualstack.reddit.map.fastly.net/A/IN
;; Question section mismatch: got dualstack.reddit.map.fastly.net/A/IN
;; Question section mismatch: got dualstack.reddit.map.fastly.net/A/IN
```

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/62358249/83137819-b2702080-a0e1-11ea-9513-8fcf0b4676f1.png)

</details>

**Comment by szolin** [comment]
See also #1754
