### ISSUE TITLE
cant visit https://console.aws.amazon.com/

### ISSUE THREAD

**Issue by teemo0803** [AdguardTeam/AdGuardHome#1747]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**   ##latest
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
What lists do you have?

**Comment by teemo0803** [comment]
those 3 deafault rules------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Andrey&amp;nbsp;Meshkov&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月29日(星期五) 凌晨0:34
收件人:&nbsp;&quot;AdguardTeam/AdGuardHome&quot;<AdGuardHome@noreply.github.com&gt;;
抄送:&nbsp;&quot;teemo0803&quot;<teemo0803@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AdguardTeam/AdGuardHome] cant visit https://console.aws.amazon.com/ (#1747)

**Comment by ameshkov** [comment]
How does it look like?

I've just tried visiting AWS console and everything looks okay. Also, check the query log in AdGuard

**Comment by teemo0803** [comment]
every seting is okay but i cant reach aws

**Comment by teemo0803** [comment]
ssl.google analytic.com

**Comment by ameshkov** [comment]
It's hard for me to diagnose such issues, please try examining the query log, maybe you'll figure out what's the issue.

Try disabling filter lists one by one, or disabling protection, or changing upstream DNS servers

**Comment by teemo0803** [comment]
copy

**Comment by teemo0803** [comment]
thanks nothing to do with adguard
