### ISSUE TITLE
In the statistical chart, the display of 0% and 0 is not at the bottom.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#1750]
Version: v0.102.0-37-g32d1
Device: Raspberry Pi 3B+

![Statistic_Chart](https://user-images.githubusercontent.com/58100052/83207987-1698f000-a187-11ea-8229-33d57fc7419e.jpg)

**Comment by ArtemBaskal** [comment]
This is most likely caused by the bug in @nivo/line
https://github.com/plouc/nivo/issues/929
