### ISSUE TITLE
Parental control block invidio.us

### ISSUE THREAD

**Issue by Archive5** [AdguardTeam/AdGuardHome#1753]
invidio uses for below projects as well.
https://github.com/FreeTubeApp/FreeTube-Vue
https://freetubeapp.io

**Comment by DandelionSprout** [comment]
Having looked into this matter, I can see that no other `InvidioUS` instances (i.e. third-party mirrors) that I know about⁽¹⁾ are blocked by Parental Control, which means that it's not objecting to any actual on-site content. Thus this is indeed a major inconsistency that the AdGuard team should resolve.

Moreover, to the best of my knowledge, it's not just AdGuard Home that uses AdGuard's parental control system, but also "AdGuard DNS — Family Protection" and an opt-in setting in "AdGuard for Windows". This makes such things even more important to fix.

⁽¹⁾ = ↓
```
yewtu.be
invidious.snopyta.org
invidious.13ad.de
invidious.ggc-project.de
invidious.toot.koeln
invidious.fdn.fr
```

**Comment by Chinaski1** [comment]
Hello there!
The domain invidio.us was automatically added to the category "Adult".
I removed it from this category and it will be unlocked soon.
Thank you for the report!
