### ISSUE TITLE
[Question] How does ECS work behind NAT?

### ISSUE THREAD

**Issue by nassoor** [AdguardTeam/AdGuardHome#1755]
If I am reading the RFC right, AGH should just forward the private subnet and the resolver should understand the limitation of the requesting server and examine the source's address.

> In other cases, if a Recursive Resolver knows that it is situated behind a NAT device, it SHOULD NOT originate ECS options with their external IP address and instead rely on downstream Intermediate Nameservers to do so.  It MAY, however, choose to include the option with their internal address for the purposes of signaling its own limit for SOURCE PREFIX-LENGTH.

and
> As a general guideline, if an Authoritative Nameserver on the publicly routed Internet receives a query that specifies an ADDRESS in [RFC1918] or [RFC4193] private address space, it SHOULD ignore ADDRESS and look up its answer based on the address of the Recursive Resolver. 

https://tools.ietf.org/html/rfc7871#section-10

Another question: how do I test if EDNS Client Subnet is working for me or not?

I have been using `dig @1.1.1.1 google.com +subnet=192.168.0.0/24` and replacing the variables with my external subnet and different resolvers and domains. 
Then I compare with `dig google.com`, which seems to confirm that ECS is working.

**Comment by szolin** [comment]
Here's how our EDNSClientSubnet option works:
https://github.com/AdguardTeam/dnsproxy/blob/385ada58acd70d24d6ff4a2acf284fcdbb075a21/proxy/config.go#L61

> I have been using dig @1.1.1.1 google.com +subnet=192.168.0.0/24

Correct

**Comment by nassoor** [comment]
I don't understand, does that mean that AGH does not actually do anything if AGH is inside the network?
Because virtually all clients will have private IPs unless AGH is deployed on the other side of the NAT.

**Comment by szolin** [comment]
> does that mean that AGH does not actually do anything if AGH is inside the network?

Yes:

> If client IP is private (i.e. not public), we don't add EDNS record into a request.

**Comment by nassoor** [comment]
Forgive my ignorance, but what's the point then? Is the option intended for VPS-like deployments?

The question then becomes how safe is it to deploy AGH on the internet. And how can I automate the allowed clients list when my ISP changes my home IP.

And, if possible, how can I force AGH to add EDNS record even if the request is from a private IP?

**Comment by szolin** [comment]
When AGH has a public IP and is available from the Internet, the ECS option works as expected - that's the goal.

> how safe is it to deploy AGH on the internet.

That's up to you to decide, but many people use it this way.

> how can I automate the allowed clients list when my ISP changes my home IP.

How do you want AGH to automate it?  Please feel free to add a feature request.

> force AGH to add EDNS record even if the request is from a private IP?

Currently that's not possible.  Why do you need this option?  Can you show schematically what are you trying to achieve?

**Comment by nassoor** [comment]
First I want to thank you for putting up with me 😁

> When AGH has a public IP and is available from the Internet, the ECS option works as expected

Does this also work if I deploy AGH on my gateway router, and AGH recognizes the public IP, but is not available from the internet? Will it add the EDNS subnet option even if the request is from a private IP? 
______________
After doing more tests, I am receiving different results from different resolvers:
I used Quad9's 9.9.9.11, Google DNS, and OpenDNS to resolve google.com and facebook.com with an external, internal, and no subnet option. What I got was not conclusive to me.

9.9.9.11 does not give an answer for google.com but does give one for facebook.com when I request with a private subnet. (I don't understand why. Is it dependent on the domain's nameserver?)

Google DNS provides different answers for private/public/no subnet.

And OpenDNS apparently ignores the option and provides the same answer whether the option is used or not. (Does that mean OpenDNS does not support ECS requests, but is ECS aware?)

My takeaway is to use resolvers that advertise being ECS aware because they will reply with best answer without being prompted for it, and not rely on AGH to include the option in the request. Am I correct in this conclusion?

**Comment by szolin** [comment]
> Will it add the EDNS subnet option even if the request is from a private IP?

No, of course not.  The option only works for public IP addresses.

I don't know about how Google DNS and OpenDNS work with ECS, but if server supports it, it will use your IP address to get the best (the closest to your location) result for your request.  ECS in AGH matters only if you AGH server is public, because the location of AGH isn't equal to location of your device in this case.

**Comment by nassoor** [comment]
That clears everything up, thank you.

Might I suggest noting in the documentation, or rewording the description to explain that the ECS in AGH will only work for public AGH servers.

>If enabled, AdGuard Home will be sending clients' subnets to the DNS servers.

Maybe should be:
>If AdGuard Home is public, clients' subnets will be sent to the DNS servers.

**Comment by ameshkov** [comment]
Makes sense, I've updated Wiki:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
