### ISSUE TITLE
Improve "reserved domains" performance

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1759]
Chinese users may need to load huge lists like this:
https://uploads.adguard.com/chinalist.txt

Example: #1680 

We may need to improve the performance in this case.

**Comment by banbendalao** [comment]
I think adding "*" wildcards can improve performance, Chinese users may need [/*google*.*/]8.8.8.8

**Comment by banbendalao** [comment]
I think adding "*" wildcards can improve performance, Chinese users may need [/*google*.*/]8.8.8.8

**Comment by jsda** [comment]
https://raw.githubusercontent.com/jsda/opdiy/master/config/AdGuardHome/AdGuardHome.yaml

**Comment by lordraiden** [comment]
Pihole remove duplicates and tells you how many filters are being used per list. This would be nice to see how much the lists overlap.

**Comment by ameshkov** [comment]
I've done some tests and the overhead with such a list is microseconds, there's no performance issue.
