### ISSUE TITLE
Update from 0.101.0 to 0.102.0 hangs

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#1760]
### Prerequisites

- [N] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
  0.101.0
* **How did you setup DNS configuration:**
  Normally
* **If it's a router or IoT, please write device model:**
  NO
* **Operating system and version:**
  Windows 10 1909 18363.836

### Expected Behavior
 Update succeeds, but it doesn't :)

### Actual Behavior
Update hangs on "Please wait, AdGuard Home is being updated" (at the time of writing it's been 10 minutes.

From the event log:
2020/05/31 11:07:46 [info] Updating from v0.101.0 to v0.102.0.  URL:https://static.adguard.com/adguardhome/release/AdGuardHome_Windows_amd64.zip  Package:C:\AdGuardHome_Windows_amd64\agh-update-v0.102.0\AdGuardHome_Windows_amd64.zip

2020/05/31 11:07:48 [info] Stopping all tasks

2020/05/31 11:07:48 [info] Stopping AdGuard Home

The AdGuard Home service service terminated unexpectedly.  It has done this 1 time(s).

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by Onepamopa** [comment]
I killed the service manually, and it updated.

**Comment by ameshkov** [comment]
Huh, that's bad, it's hard to say what's wrong now:(

I'll reopen it if there are any similar issues
