### ISSUE TITLE
Unable to login to AdGuard Home from a Home Assistant iFrame on iOS

### ISSUE THREAD

**Issue by raetha** [AdguardTeam/AdGuardHome#1767]
### Issue Details

* **Version of AdGuard Home server:**
0.102.0
* **How did you setup DNS configuration:**
Unsure what is meant here, but installed in Docker on a Synology NAS.
* **If it's a router or IoT, please write device model:**
N/A
* **Operating system and version:**
Docker

### Expected Behavior
I use Home Assistant and have the AdGuard Home UI set up as an iFrame panel. The iFrame should load the site, allow login, and full access to the complete UI.

### Actual Behavior
Everything works correctly when HA is launched in a computer web browser. However, when launched on an iPhone, either in Safari or the Home Assistant app, after attempting to log on, you are returned to the login screen. No message is generated saying invalid credentials, but if bad credentials are used, that message is displayed. This only happens in the iFrame configuration with Home Assistant, going directly to the AdGuard Home web interface works as expected.

### Additional Information
Have tested with various versions over the past few months. At one point it did work, but I didn't catch exactly when it stopped.

**Comment by ameshkov** [comment]
Could it be that some content blocker in your Safari messes with it?

**Comment by raetha** [comment]
@ameshkov, I had thought about that and disabled my Safari ad blocker config. However the odd thing is that it is working directly in mobile Safari, but not in the Home Assistant Companion app using iframe. I think I confused in the notes above, Safari actually does work. And as far as I know, Webkit doesn't use blocking when embedded in an app.

**Comment by ameshkov** [comment]
> but not in the Home Assistant Companion app using iframe

Do you know what kind of webview they use? Is it Safari View Controller or WebView?

SVC actually uses content blocking

**Comment by raetha** [comment]
Unfortunately I don't know for sure what the app uses for webview, but I think I saw WebView somewhere in the code. I'm not familiar with Swift at all, and don't do much programming these days, so reading that code is somewhat difficult for me. It can be found at https://github.com/home-assistant/iOS if that is helpful.

Either way, I did make sure to test with content blocking turned off just to make sure that wasn't causing an issue by itself. I still just see it try to process my login credentials, but then the session flashes like it wants to move on, but just reloads the login page with no message as to why it didn't work.

**Comment by ameshkov** [comment]
I just don't understand what can be done about this on our side. Maybe it makes sense to report this to HASS iOS app instead

**Comment by raetha** [comment]
Since I've confirmed it is working on mobile Safari, I think it reasonable that it may be an HASS iOS app issue instead, originally I remember it seemed to have the same behavior everywhere, but at some point that did change. So no worries about closing this out, I'll try to refile with the HASS app instead and probably reference this.

**Comment by raetha** [comment]
Actually, I just retested something that reminded me of what I was seeing. Mobile Safari works correctly when pointing directly to the AdGuard Home server. However, in an iFrame of HASS, it fails both in mobile Safari and the HASS iOS app. So it isn't the mobile app, but rather something in how AGH plays with HASS in an iFrame. The mobile app was a red herring, but I've gone back and forth with testing so many times, that was where I kept hitting it because I rarely load HASS directly outside the app.

And that was what led me here, as I've got other applications that authenticate just fine when run in iFrames. So I was assuming that AGH is blocking or misbehaving when run in an iFrame.

**Comment by raetha** [comment]
I did log an issue with the HA frontend, https://github.com/home-assistant/frontend/issues/6280. But not clear where this really lies.

**Comment by ameshkov** [comment]
Hm, I wonder is there some special treatment for cookies set from inside an iframe in mobile Safari.

> Everything works correctly when HA is launched in a computer web browser

Which one? Is it also Safari?

**Comment by whattheschnell** [comment]
Can we re-open this?  Not specific to iOS or HomeAssistant.

I'm running AdguardHome in Docker through UnRaid.  Trying to load iframe through a docker front end organizer (DashAssistant) and I get the same result as OP.

**Comment by PilaScat** [comment]
Same, pls fix the iframe capability

**Comment by kennethpangky** [comment]
Having the same issue as well. Not iOS related, can't do it even on desktop Chrome.

It shows the login screen, then after entering the details, it redirects back to the login screen.

**Comment by sanderlv** [comment]
Issue closed but experience same issue here.

described as in https://community.home-assistant.io/t/adguard-home-login-via-https-proxy-manager-nginx/485314
