### ISSUE TITLE
HSTS in AdGuard Home (Strict-Transport-Security)

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#1768]
Adguardhome requires adding HSTS and forcing Https.

**Comment by Potterli20** [comment]
HTTP_Strict_Transport_Security：
https://en.m.wikipedia.org/wiki/HTTP_Strict_Transport_Security

**Comment by ameshkov** [comment]
This may be an option, let's see how many upvotes this feature request get.

For now the solution would be to configure a reverse proxy (nginx, caddy, or anything else) and configure it to add this header to all responses.

**Comment by Potterli20** [comment]
> This may be an option, let's see how many upvotes this feature request get.
> 
> For now the solution would be to configure a reverse proxy (nginx, caddy, or anything else) and configure it to add this header to all responses.

But I don't want to use an anti-agent, I just want to add it to the original Settings, so I don't need an anti-agent.

**Comment by Kagura-Nanaa** [comment]
我觉得这个功能很有用👍🏻

**Comment by Kagura-Nanaa** [comment]
> 我觉得这个功能很有用👍🏻

I find it useful

**Comment by Potterli20** [comment]
> 我觉得这个功能很有用👍🏻

对哈😂

**Comment by banbendalao** [comment]
> 这可能是一个选项，让我们看看此功能请求获得了多少支持。
> 
> 目前，解决方案是配置反向代理（nginx，caddy或其他任何方式），并将其配置为将此标头添加到所有响应中。

doh client will not try to use http, I think this function is useless

> This may be an option, let's see how many upvotes this feature request get.
> 
> For now the solution would be to configure a reverse proxy (nginx, caddy, or anything else) and configure it to add this header to all responses.

doh client will not try to use http, I think this function is useless

**Comment by ameshkov** [comment]
Guys, Das @banbendalao has pointed out, if you need it for DOH - it is useless.

The only reason for adding it is to make sure that you access the admin interface over HTTPS.

**Comment by Potterli20** [comment]
> 伙计们，Das @banbendalao指出，如果您需要DOH，它就没用了。
> 
> 添加它的唯一原因是确保您通过HTTPS访问管理界面。

If I think this function is not necessary, but I feel that the security transfer is necessary. The current product is the product of secure and private DNS AdGuardHome.

**Comment by Potterli20** [comment]
> Guys, Das @banbendalao has pointed out, if you need it for DOH - it is useless.
> 
> The only reason for adding it is to make sure that you access the admin interface over HTTPS.

If I think this function is not necessary, but I feel that the security transfer is necessary. The current product is the product of secure and private DNS AdGuardHome.

**Comment by ameshkov** [comment]
Why closing it? There're many upvotes already

**Comment by Potterli20** [comment]
> Why closing it? There're many upvotes already

If it doesn't make sense, don't add it. This feature leads me to the question of security.

**Comment by Potterli20** [comment]
Although the DOH client will not attempt to use HTTP, I feel that this is a secure feature.

**Comment by ameshkov** [comment]
Well, okay then. Reopen if you feel that it needs to be done and we'll see how it goes.

**Comment by Potterli20** [comment]
@ameshkov Have you considered HTTP 3.0 protocol??

**Comment by ameshkov** [comment]
@Potterli20 HTTP 3.0 will be supported eventually when it will be added to Go stdlib: https://github.com/golang/go/issues/32204

But to be honest, I am skeptical about DNS-over-HTTPS in general. DNS-over-QuicTransport is a much better concept https://datatracker.ietf.org/doc/draft-ietf-dprive-dnsoquic/

**Comment by Potterli20** [comment]
> @Potterli20 HTTP 3.0 will be supported eventually when it will be added to Go stdlib: [golang/go#32204](https://github.com/golang/go/issues/32204)
> 
> But to be honest, I am skeptical about DNS-over-HTTPS in general. DNS-over-QuicTransport is a much better concept https://datatracker.ietf.org/doc/draft-ietf-dprive-dnsoquic/

Ok, that means I like that feature

**Comment by Potterli20** [comment]
#2049
