### ISSUE TITLE
Rewritten by the hosts file rule

### ISSUE THREAD

**Issue by otomaid** [AdguardTeam/AdGuardHome#1771]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0
* **How did you setup DNS configuration:**
  * Windows 10 ipv4 config
  * AdGuard Pro for iOS
* **If it's a router or IoT, please write device model:**
  * N/A
* **Operating system and version:**
  * Ubuntu 16.04.1 LTS

### Expected Behavior
It should response domain's actual ip as older AdGuard Home.

### Actual Behavior
Response IP from hosts file.

### Screenshots
<details><summary>Screenshot:</summary>

<img width="873" alt="キャプチャ" src="https://user-images.githubusercontent.com/66439606/83800189-a08e0f00-a6d9-11ea-8b5f-f9f2fed3a3e2.PNG">

</details>

### Additional Information
My domain is using Cloudflare services, and I am unable to change my VPS hosts file due to the provider limitation. It has no problem with version prior to v0.102.0 .

**Comment by ameshkov** [comment]
The information from `/etc/hosts` has higher priority than anything else. If you want it to have a different IP, you should simply remove that line from `/etc/hosts`

**Comment by otomaid** [comment]
Sorry for not being clear, the hosts file is in server-side. It has no problem before. The screenshot I provided is the AdGuard Home Logs too
