### ISSUE TITLE
Questions about the DOH server

### ISSUE THREAD

**Issue by Kagura-Nanaa** [AdguardTeam/AdGuardHome#1776]
I'm deploying DOH on the server and it seems that only the same IP can connect, and if the second IP connects, the first The IP will drop. I'm on port 810.

**Comment by Kagura-Nanaa** [comment]
Can only port 443 be used for multi-IP connections?

**Comment by ameshkov** [comment]
Hm, interesting, let us please check it.

Please check `AdGuardHome.yaml`, what value do you have in `bind_host`?

**Comment by Kagura-Nanaa** [comment]
![image](https://user-images.githubusercontent.com/44108528/84010079-ba17ab00-a9a6-11ea-93b0-ba22a53399e4.png)

**Comment by ameshkov** [comment]
Hm, maybe I don't understand the original issue then.

> if the second IP connects, the first The IP will drop

What do you mean here?

**Comment by Kagura-Nanaa** [comment]
> 嗯，那我也许不明白原来的问题。
> 
> > 如果连接了第二个IP，则第一个IP将丢失
> 
> 你这是什么意思

“disconnect”   Google Translate 😂

**Comment by ameshkov** [comment]
你可以写中文，我能看得懂

**Comment by Kagura-Nanaa** [comment]
> 你可以写中文，我能看得懂

好的,发现发现同时只能连接一个ip,当我的朋友用连接doh之后,我就无法使用.我觉得是不是只有443端口才能多ip连接,因为别人提供的doh都是443端口的.但是我无法确认我的想法是不是对的.因为中国需要备案才能使用443端口

**Comment by ameshkov** [comment]
1. You are trying to run your own DOH server, right?
2. Your friend is able to use it, but you aren't, right?

What client-side software do you use to use DOH?

We don't have any specific port limitations in AdGuard Home so I don't think the problem is with the port.

**Comment by Kagura-Nanaa** [comment]
需要向miit提交申请,如果不提交申请服务器可能会有限制（只能连接一个ip？不确定）

**Comment by mHatsune** [comment]
>只能连接一个ip?

沒有。
