### ISSUE TITLE
error handling UDP packet: dns: buffer size too small

### ISSUE THREAD

**Issue by SanderGit** [AdguardTeam/AdGuardHome#1777]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.102.0
* **How did you setup DNS configuration:**
  * To CloudFlare DNS
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi model 2B+
* **Operating system and version:**
  * Raspbian 10.4

### Expected Behavior
Normal operation

### Actual Behavior
CPU spinning 300% with AdGuardHome process.
Logs in error log file.

### Additional Information
AdGuardHome.err shows:

2020/06/08 12:36:43 [info] got invalid number of questions: 0
2020/06/08 12:36:43 [info] got invalid number of questions: 0
2020/06/08 12:36:51 [info] error handling UDP packet: dns: buffer size too small
2020/06/08 12:36:54 [info] error handling UDP packet: dns: buffer size too small

The interrnet connection has been interrupted, it is likely that the issue is related to the interruption, but AdGuardHome could not recover from it by itself.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by SanderGit** [comment]
[AdGuardHome.txt](https://github.com/AdguardTeam/AdGuardHome/files/4746753/AdGuardHome.txt)
Issue in the .err log did not reproduce right now, but AdGuardHome did take up 400% CPU. Restarting the service did not help, DNS resolution did not become available and the CPU usage remained above 100%. I had to reboot the Pi in order to get it back in operation.
It could again be triggered by interrupting the network connection.

**Comment by Onepamopa** [comment]
What is the value of net.core.rmem_max ?

**Comment by SanderGit** [comment]
> What is the value of net.core.rmem_max ?

163840

**Comment by chaelli** [comment]
Still have this (or https://github.com/AdguardTeam/AdGuardHome/issues/1779) issue on v0.105.2 - see attached logs. Hosting it in docker.
[adguard.zip](https://github.com/AdguardTeam/AdGuardHome/files/6944073/adguard.zip)

**Comment by Meldrak** [comment]
Also have this issue in docker on 106.3 version

**Comment by STaRDoGG** [comment]
I'm having this in the docker container: `adguard/adguardhome:latest`, ADGH version: v**0.107.6**

```
last Monday at 11:32:59 PM2022/06/20 23:32:59.627550 [error] unpacking udp packet: dns: buffer size too small
last Monday at 11:33:02 PM2022/06/20 23:33:02.629989 [error] unpacking udp packet: dns: buffer size too small
last Tuesday at 1:32:08 AM2022/06/21 01:32:08.421618 [error] unpacking udp packet: dns: buffer size too small
last Tuesday at 1:32:11 AM2022/06/21 01:32:11.430335 [error] unpacking udp packet: dns: buffer size too small
last Tuesday at 1:46:47 AM2022/06/21 01:46:47.061772 [info] saving filter 1 contents to: /opt/adguardhome/work/data/filters/1.txt
last Tuesday at 1:46:47 AM2022/06/21 01:46:47.063811 [info] updated filter 1: 906544 bytes, 46682 rules
last Tuesday at 1:46:47 AM2022/06/21 01:46:47.539377 [info] Updated filter #1.  Rules: 46602 -> 46682
last Tuesday at 2:15:40 AM2022/06/21 02:15:40.719456 [error] unpacking udp packet: dns: buffer size too small
last Tuesday at 2:15:43 AM2022/06/21 02:15:43.725568 [error] unpacking udp packet: dns: buffer size too small
last Tuesday at 9:44:58 PM2022/06/21 21:44:58.066597 [error] unpacking udp packet: dns: buffer size too small
last Tuesday at 9:45:01 PM2022/06/21 21:45:01.081571 [error] unpacking udp packet: dns: buffer size too small
last Wednesday at 1:46:52 AM2022/06/22 01:46:52.079810 [info] saving filter 1 contents to: /opt/adguardhome/work/data/filters/1.txt
last Wednesday at 1:46:52 AM2022/06/22 01:46:52.081764 [info] updated filter 1: 907433 bytes, 46728 rules
last Wednesday at 1:46:52 AM2022/06/22 01:46:52.498932 [info] saving filter 1646248304 contents to: /opt/adguardhome/work/data/filters/1646248304.txt
last Wednesday at 1:46:52 AM2022/06/22 01:46:52.502705 [info] updated filter 1646248304: 3411312 bytes, 108520 rules
last Wednesday at 1:46:52 AM2022/06/22 01:46:52.502745 [info] Updated filter #1.  Rules: 46682 -> 46728
last Wednesday at 1:46:52 AM2022/06/22 01:46:52.502750 [info] Updated filter #1646248304.  Rules: 128608 -> 108520
last Thursday at 1:46:56 AM2022/06/23 01:46:56.900561 [info] saving filter 1 contents to: /opt/adguardhome/work/data/filters/1.txt
last Thursday at 1:46:56 AM2022/06/23 01:46:56.902930 [info] updated filter 1: 888924 bytes, 45847 rules
last Thursday at 1:46:57 AM2022/06/23 01:46:57.307888 [info] Updated filter #1.  Rules: 46728 -> 45847
yesterday at 1:47:01 AM2022/06/24 01:47:01.812870 [info] saving filter 1 contents to: /opt/adguardhome/work/data/filters/1.txt
yesterday at 1:47:01 AM2022/06/24 01:47:01.815939 [info] updated filter 1: 889864 bytes, 45895 rules
yesterday at 1:47:02 AM2022/06/24 01:47:02.213925 [info] Updated filter #1.  Rules: 45847 -> 45895
yesterday at 7:43:21 AM2022/06/24 07:43:21.743922 [error] unpacking udp packet: dns: buffer size too small
yesterday at 7:43:24 AM2022/06/24 07:43:24.746417 [error] unpacking udp packet: dns: buffer size too small
yesterday at 9:28:12 PM2022/06/24 21:28:12.898253 [error] unpacking udp packet: dns: buffer size too small
yesterday at 9:28:15 PM2022/06/24 21:28:15.904805 [error] unpacking udp packet: dns: buffer size too small
```

**Comment by Dza-byte** [comment]
Just started seeing this as well, running on unraid

**Comment by chlorophycae** [comment]
https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size

**Comment by chaelli** [comment]
Have this again on 0.107.16 in docker. I removed quic://dns-unfiltered.adguard.com:784 as a source because of the link above. are there any better solutions? How can I increase net.core.rmem_max in the docker container?
