### ISSUE TITLE
Sort IP

### ISSUE THREAD

**Issue by S8D** [AdguardTeam/AdGuardHome#1778]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  0.102.0
* **How did you setup DNS configuration:**
  *  OpenWRT
* **If it's a router or IoT, please write device model:**
  *  ER-X-SFP
* **Operating system and version:**
  *  X-WRT Build 20200605

### Actual Behavior
 Sort IP on Setting > Client settings > tab Clients soft IP lists not perfect yet. Please fix it
Size of tab [Time, Domain name,...] on Query log not save after change.
Thanks
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ArtemBaskal** [comment]
Could you please describe in more detail the desired IP sort order? As for the query logs, they are in the process of redesigning now.

**Comment by S8D** [comment]
> Could you please describe in more detail the desired IP sort order? As for the query logs, they are in the process of redesigning now.

In the picture below, the rule of sort IP is not good
2.1
2.10
2.100
2.2
2.20
2.200
...
https://i.ibb.co/brxBHDf/Screenshot-20200609-060632-Firefox.jpg
Exactly must be
2.1
2.2
...
2.10
2.11
...
2.99
2.100
...
2.199
2.200
...
3.1
....

**Comment by ameshkov** [comment]
Why closing it?

**Comment by S8D** [comment]
Sort ip will be fix on next version.

**Comment by ameshkov** [comment]
Yeah, and we need this issue open so that we don't forget to fix it:)
