### ISSUE TITLE
Intermittent downtime (~15 minutes)

### ISSUE THREAD

**Issue by Freekers** [AdguardTeam/AdGuardHome#1779]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Docker 19.03.9 on Ubuntu 20.04

### Expected Behavior
Every now and then, AdGuard Home stops responding to DNS requests, i.e. DNS lookups will timeout. The webinterface will continue to work and port 53 will still be listening, but any DNS queries are not answered for approximately 15 minutes. After a short period of time, AdGuard Home works normally again without human intervention. This happens approximately once or twice per day but I have not been able to find a pattern yet.

### Actual Behavior
AdGuard should not stop responding to DNS requests. Additionally, in case of an issue, it should display an error in the web interface.

### Additional Information
I managed to capture the issue while verbose logging was enabled. [Click here to download the logfile. ](https://data.freek.ws/public/adguard.log)

Additionally, I'm seeing the following errors in my AdGuard container log:
```
[info] error handling UDP packet: dns: overflowing header size
[info] got invalid number of questions: 0
[info] error handling UDP packet: dns: bad rdata
[info] error handling UDP packet: dns: overflow unpacking uint16
[info] error handling UDP packet: dns: buffer size too small
```
Note: I have tried varying the buffer size ranging from 4 megabytes to a (whopping) 256 megabytes, but I keep getting the 'buffer size too small' error every now and then.

I'm running AdGuard Home as Docker and have setup my instance using Ansible as follows: https://github.com/Freekers/ansible-adguard

I do not use any public DNS servers as upstream. Instead, I run Unbound next to AdGuard Home to directly query the root DNS servers. During the issue, unbound was working normally and responding to DNS queries.

**Comment by ameshkov** [comment]
@Freekers could you please tell me at what time in the log the downtime happened?

**Comment by Freekers** [comment]
> 
> 
> @Freekers could you please tell me at what time in the log the downtime happened?

The downtime was present during the entire period logging was enabled, so from the beginning to end of the log was during downtime.

**Comment by ameshkov** [comment]
@Freekers it seems that AGH received almost 15k requests for 1 minute. I suspect that you might've hit the default rate limit.

Do you use the default value?

**Comment by Freekers** [comment]
I've removed the default value due to the large amount of users. So I am not using the default value, it's set to '0' i.e. unlimited.

**Comment by ameshkov** [comment]
Could it be that you're hitting the rate limit of your upstream server? (`139.99.74.182`)?

**Comment by damooooooooooh** [comment]
I'm having similar issues, periodically I will be using my phone and for a few minutes DNS queries appear not to be resolved, still trying to debug the situation.  Even trying to hit the admin url times out, but there is no sign of the device or service restarting.  I am using a 2GB Pi 4 so mem isn't an issue.  I've tried setting the rate limit from 20 to 0 to see if this resolves it.

**Comment by szolin** [comment]
@damooooooooooh Please open a new issue with debug logs attached if your issue persists.
Closing this as I don't see what we can do about it.
