### ISSUE TITLE
used problem with memory

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1780]
Openwrt x64 in a mini PC,
latest AdguardHome
add more than 1000 rules,
Problem:when the mini PC is power up,
Memory
Total Available (69%)
Buffered  (8%)
but used over one hour or two hours,
Memory
Total Available (44%)
Buffered  (11%)
check every apps,only AdguardHome will used more,
so need to check AdguardHome could become full protection that spend more time  maybe after add more rules,
hope AdguardHome could used full protection at started.
![Image 3](https://user-images.githubusercontent.com/17021524/85415410-e125cd80-b59f-11ea-81d7-c706ebdaf4d5.png)

![Image 4](https://user-images.githubusercontent.com/17021524/85415447-ea169f00-b59f-11ea-864d-d782bc895353.png)

Why adguardhome used most memory?

**Comment by ameshkov** [comment]
Sorry, I don't understand what's the question and what would you like us to do

**Comment by xbcyl813** [comment]
maybe memory leak?

**Comment by szolin** [comment]
> maybe memory leak?

No, it's not.  There's nothing wrong unless you show us that AGH stops working after some time.
Memory leak and memory usage are different things.

**Comment by ameshkov** [comment]
That's pretty normal for a golang-written app to consume more after some time.

It will stabilize after that, though.
