### ISSUE TITLE
Nested block-list support

### ISSUE THREAD

**Issue by Mathijs0** [AdguardTeam/AdGuardHome#1781]
### Problem Description
I have 2 separate ad-guard Home instances running on my network, and I would like to keep them in sync without doing stuff twice.

### Proposed Solution
Make one git(-hub) list with all the block-list and one with the white lists I would like to use. And just ad these two lists to both ad-guard Home instances. Once I update this single list with nested block-lists they both update.

### Alternatives Considered
Sync the config folder periodically and restart ad-guard Home. Or do everything twice.

### Additional Information
An example how i would guess this list would look like:
```
+include: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
+include: https://adaway.org/hosts.txt

```

**Comment by ameshkov** [comment]
You can use https://github.com/AdguardTeam/HostlistCompiler to automate building a blocklist that you can then use in both instances.

Also, this issue seems to duplicate #573
