### ISSUE TITLE
Skype file transfer issue

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1782]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.102.0
* **How did you setup DNS configuration:**
  * VPS, Linux, OpenVZ
* **Operating system and version:**
  * Debian 9
### Actual Behavior
For the last week, I 've had a problem transferring files to Skype (desktop and mobile clients). The problem is ONLY observed when connecting through the AGH server. There is no problem connecting to upstream servers directly (NextDNS). Disabling filters or entire filtering does not solve the problem. Turning off the firewall does not solve the problem too. Here 's what I found remarkable in the log:
```
2020/06/09 14:40:00 794#952 [debug] pingDoTCP: contacts.skype.com.: elapsed 121 ms on 137.116.70.43:80
2020/06/09 14:40:03 794#746 [debug] pingDoTCP: pipe.skype.com.: failed to connect to 52.114.76.35:80, elapsed 10000 ms: dial tcp 52.114.76.35:80: i/o timeout
2020/06/09 14:40:03 794#748 [debug] pingDoTCP: pipe.skype.com.: failed to connect to 52.114.128.9:80, elapsed 10000 ms: dial tcp 52.114.128.9:80: i/o timeout
2020/06/09 14:40:04 794#774 [debug] pingDoTCP: client-s.gateway.messenger.live.com.: failed to connect to 52.149.21.60:80, elapsed 10000 ms: dial tcp 52.149.21.60:80: i/o timeout
2020/06/09 14:40:05 794#796 [debug] pingDoTCP: options.skype.com.: failed to connect to 52.148.81.118:80, elapsed 10000 ms: dial tcp 52.148.81.118:80: i/o timeout
2020/06/09 14:40:07 794#824 [debug] pingDoTCP: api.aps.skype.com.: failed to connect to 52.251.112.23:80, elapsed 10000 ms: dial tcp 52.251.112.23:80: i/o timeout
2020/06/09 14:40:07 794#834 [debug] pingDoTCP: msgsearch.skype.com.: failed to connect to 13.66.231.187:80, elapsed 10000 ms: dial tcp 13.66.231.187:80: i/o timeout
2020/06/09 14:40:09 794#866 [debug] pingDoTCP: mobile.pipe.aria.microsoft.com.: failed to connect to 52.114.159.112:80, elapsed 10000 ms: dial tcp 52.114.159.112:80: i/o timeout
```

### Screenshots

<details><summary>Screenshot:</summary>

![E011228A-EC79-42AB-ACAF-A0DC5BC6D6F4_1_201_a](https://user-images.githubusercontent.com/45385632/84146008-9a928800-aa63-11ea-87c2-714620f64cf8.jpeg)

![2020-06-09_15-10-01](https://user-images.githubusercontent.com/45385632/84145935-79319c00-aa63-11ea-8e11-92175958310f.png)

</details>

### Additional Information
The detailed [log.txt](https://github.com/AdguardTeam/AdGuardHome/files/4752020/log.txt) is attached. Please, take a look. I would be very grateful if you could help me understand the cause of this problem! Thank you!🥺

**Comment by ameshkov** [comment]
Does disabling "fastest IP addr" help?

**Comment by ammnt** [comment]
@ameshkov, unfortunately, no😒I 've been using "paralel requests" since yesterday. I tried the following actions:
1. Switch to DoH for the upstream servers;
2. Disable of DNSSEC;
3. Disable of EDNS;
4. Disable of ipv6;
5. Disable "parallel queries and fastest IP" - both options.

What 's the reason for that?🤨

Thanks for help!!🙏

**Comment by ameshkov** [comment]
@ammnt I cannot reproduce it with the desktop Skype version.

What Skype version do you use?

**Comment by ammnt** [comment]
> @ammnt I cannot reproduce it with the desktop Skype version.
> 
> What Skype version do you use?

8.60.0.76. This is the last version. I can also provide remote access for debugging. It 'll be faster, I think.

**Comment by ameshkov** [comment]
Can we discuss it in Telegram DM?

**Comment by ammnt** [comment]
> Can we discuss it in Telegram DM?
Sure:
https://t.me/heresammnt

**Comment by ammnt** [comment]
@ameshkov, FYI:
1. The same issue with fresh installation
2. I don't have this issue when connecting my iOS device via AdGuard VPN🤔
