### ISSUE TITLE
标记客户端

### ISSUE THREAD

**Issue by Kagura-Nanaa** [AdguardTeam/AdGuardHome#1787]
我希望adh可以像nextdns那样为不同的客户端标记名字,这样可以识别没有固定ip的客户端,从而实现adh的客户端功能 但是这样是不是需要多张CA证书？或者是通配符证书？

**Comment by Kagura-Nanaa** [comment]
> 我希望adh可以像nextdns那样为不同的客户端标记名称，这样可以识别没有固定ip的客户端，从而实现adh的客户端功能但是这样是不是需要多张CA证书？或者是通配符证书？

![Screenshot_2020-06-11-11-01-23-540_com quark browser](https://user-images.githubusercontent.com/44108528/84340898-5a064c00-abd4-11ea-85de-e70be3e5a8fa.png)

**Comment by Kagura-Nanaa** [comment]
![IMG_20200611_110659](https://user-images.githubusercontent.com/44108528/84340929-72766680-abd4-11ea-963f-ba268232f732.jpg)

**Comment by Potterli20** [comment]
> 我希望adh可以像nextdns那样为不同的客户端标记名字,这样可以识别没有固定ip的客户端,从而实现adh的客户端功能 但是这样是不是需要多张CA证书？或者是通配符证书？

这个功能有哈

**Comment by Kagura-Nanaa** [comment]
> > 我希望adh可以像nextdns那样为不同的客户端标记名称，这样可以识别没有固定ip的客户端，从而实现adh的客户端功能但是这样是不是需要多张CA证书？或者是通配符证书？
> 
> 这个功能有哈

哪里有

**Comment by ameshkov** [comment]
打开客户端设置，在这儿你可以添加新客户端。

**Comment by Kagura-Nanaa** [comment]
> ：客户端设置，在这儿你可以添加新客户端。

这个我知道,但问题是设备没有固定的ip地址,而adh也在服务器上,不能通过mac识别

**Comment by ameshkov** [comment]
请看https://github.com/AdguardTeam/AdGuardHome/issues/1383，你要像这样的东西？

**Comment by Potterli20** [comment]
> 请看#1383 ，你要像这样的东西吗？

是的

**Comment by Kagura-Nanaa** [comment]
> 请看[＃1383](https://github.com/AdguardTeam/AdGuardHome/issues/1383)，你要像这样的东西吗？

是的

**Comment by Kagura-Nanaa** [comment]
> 请看[＃1383](https://github.com/AdguardTeam/AdGuardHome/issues/1383)，你要像这样的东西吗？

![IMG_20200611_110659](https://user-images.githubusercontent.com/44108528/84365799-905bbf80-ac04-11ea-932f-ff55b5a9fda5.jpg)
就是这种

**Comment by ameshkov** [comment]
> 或者是通配符证书？

是的

**Comment by Kagura-Nanaa** [comment]
> > 或者是通配符证书？
> 
> 是的

希望她可以支持多张单域名证书,通配符证书价格略贵😭 @ameshkov
