### ISSUE TITLE
SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://dns-family.adguard.com:443/dns-query

### ISSUE THREAD

**Issue by Laibalion** [AdguardTeam/AdGuardHome#1788]
Enabling 'Use AdGuard browsing security web service' in the General Settings leads to the following error in the logs and very slow DNS queries
`2020/06/10 21:53:21 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://dns-family.adguard.com:443/dns-query, cause: failed to lookup dns-family.adguard.com, cause: synthetic.wrap: all resolvers failed to lookup, cause: read udp 172.16.0.20:60632->176.103.130.130:53: i/o timeout (hidden: read udp 172.16.0.20:36544->176.103.130.131:53: i/o timeout)`

Possibly related when I add Adguard's DoH (https://dns.adguard.com/dns-query) as upstream, the bootstrap DNS server for some reason can't resolve it:
`Server "https://dns.adguard.com/dns-query": could not be used, please check that you've written it correctly`

However when doing a nslookup of both Adguard's DoH domains using the same configured bootstrap DNS, they resolve fine. 

configured upstreams:
- https://cloudflare-dns.com/dns-query
- https://dns10.quad9.net/dns-query
- https://dns.adguard.com/dns-query <-- doesn't work when testing

configured bootstrap DNS:
- 1.1.1.1
- 9.9.9.10
- 149.112.112.10

* **Version of AdGuard Home server:**
v0.102.0
* **How did you setup DNS configuration:**
Synology DSM 6.2.3-25426 - Docker - Image adguard/adguardhome - using Host network

**Comment by ameshkov** [comment]
Yes, this is indeed caused by the fact that `176.103.130.130` is not reachable.

Could you please show the output of `traceroute 176.103.130.130`?

**Comment by Laibalion** [comment]
`PS C:\Users\geert> tracert 176.103.130.130

over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  172.16.0.1
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6     *        *        *     Request timed out.
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.`

So it gets blocked at router level. I have some GeoIP blocking rules. In which country are the AdGuard dns servers are located?

**Comment by Laibalion** [comment]
Ah nevermind, seems to be in Russia :(, which i block connections from and too.
So no issue with AdGuardHome.

Apologies for a bad bug report :)

**Comment by ameshkov** [comment]
Here's the servers map:
![image](https://user-images.githubusercontent.com/5947035/84361090-d0ef1500-abd3-11ea-8ea7-5933f34ada96.png)

However, we rent the IPs range from a Russian hosting company so I guess this explains it.
