### ISSUE TITLE
没效果咋办

### ISSUE THREAD

**Issue by xiaofengcod** [AdguardTeam/AdGuardHome#1790]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Potterli20** [comment]
没效果就不要弄了

**Comment by xiaofengcod** [comment]
已近放弃了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "potterli"<notifications@github.com&gt;; 
发送时间: 2020年6月12日(星期五) 凌晨0:03
收件人: "AdguardTeam/AdGuardHome"<AdGuardHome@noreply.github.com&gt;; 
抄送: "晓风"<1306307073@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AdguardTeam/AdGuardHome] 没效果咋办 (#1790)





 
没效果就不要弄了

**Comment by ookangzheng** [comment]
用英語描述，不然內文好歹附上 截圖 還是問題及期望的解答吧
空空如也，你要別人怎麼幫你呢

**Comment by ameshkov** [comment]
Please be more specific about what's wrong, it's rather hard to help when there are literally no details supplied.
