### ISSUE TITLE
Last time updated status display for every lists

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#1791]
That is either bug or mistake. If not a bug then move that to a corner as one line status bar and replace that column with useful feature similar #1364

#### Actual Behavior
Last time updated status shows for every lists regardless remote url reachable or not.

**Comment by Archive5** [comment]
I think one or two times had spent for fix filter update time related bugs and recent https://github.com/AdguardTeam/AdGuardHome/issues/1766
Consider to make above change and spend time for implement existing feature request #970 then it solve that issue perfectly

**Comment by ameshkov** [comment]
> Last time updated status shows for every lists regardless remote url reachable or not.

Well, it should be shown isn't it?

Could you please provide some steps to reproduce so that I could see what's the problem more clearly.

**Comment by Archive5** [comment]
> Well, it should be shown isn't it? Could you please provide some steps to reproduce so that I could see what's the problem more clearly.

Block several subscribed lists contain domains and check update.
Some operating systems shows 'Last checked' and 'Last time updated' separately for that

![Untitled](https://user-images.githubusercontent.com/63988538/84635007-77bf0400-aea7-11ea-99e4-6042b023d4fe.png)

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
