### ISSUE TITLE
Unable to add local lists

### ISSUE THREAD

**Issue by Archive5** [AdguardTeam/AdGuardHome#1792]
Add blocklist > Enter path ‪C:\Users\Archive\Portable\resources.txt > Save

Error: control/filtering/add_url | Couldn't fetch filter from url C:\Users\Archive\Portable\resources.txt: data contains non-printable characters | 400

#### What's inside? 
`github.com`

Windows | v0.102.0

**Comment by szolin** [comment]
Please attach your file exactly as it is, because if I create a file with `github.com` contents - it just works fine.

**Comment by Archive5** [comment]
[resources.txt](https://github.com/AdguardTeam/AdGuardHome/files/4779159/resources.txt)

**Comment by szolin** [comment]
It's already fixed in #1694
