### ISSUE TITLE
Client host name / FQDN not displayed in the Top Clients list

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#1795]
* **Version of AdGuard Home server:**
v0.102.0
* **How did you setup DNS configuration:**
Set AdGuard Home IP Address as Primary DNS Server on Router DHCP setup
* **If it's a router or IoT, please write device model:**
Running on HASSIO on Raspberry Pi 3+
* **Operating system and version:**
HA Version 0.111.0

### Expected Behavior
I expect all local client IP addresses to be displayed using their FQDN in the 'Top clients' list on the Dashboard 

### Actual Behavior
Upstream DNS server has entries for all local client IP addresses, however only some clients are displayed in the client list with their FQDN and the rest are displayed as just IP addresses

### Screenshots

![image](https://user-images.githubusercontent.com/59442445/84476047-7ca46d80-ac85-11ea-85ac-1bd23e9885d0.png)

![image](https://user-images.githubusercontent.com/59442445/84477673-e756a880-ac87-11ea-8851-a909d07b95ca.png)

### Additional Information

All of the clients that are listed with just their IP address are also NOT listed on the 'Client Settings; page under 'Clients (runtime)'

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by tescophil** [comment]
Thanks for the reply. In the link you supplied I spotted the configuration I was missing, which is to specify upstream for rDNS, so all I had to do was to add a rule
`[/168.192.in-addr.arpa/]192.168.10.1`
and this has sorted the issue. (My fault for not fully reading the docs).
Thanks for your help. Fantastic project.

**Comment by ameshkov** [comment]
Thank you!

I guess we may need to make this more visible in the DNS settings
