### ISSUE TITLE
Make language tag in HTML same as setting language in AdGuard Home

### ISSUE THREAD

**Issue by pm2kjiagm** [AdguardTeam/AdGuardHome#1797]
### Prerequisites
- [○] I am running the latest version
- [○] I checked the documentation and found no answer
- [○] I checked to make sure that this issue has not already been filed

### Problem Description
When I change the language setting in AdGuard Home, the webpage language tag in HTML still shows "`<html lang="en">`".
This makes some browser, for example Chrome, to use wrong font to render webpage in some situations.

### Proposed Solution
Make language tag sync with language setting of AdGuard Home.
For example, when I set AdGuard Home language to zh-CN, webpage tag shows `<html lang="zh-CN">`.

**Comment by ameshkov** [comment]
I am not sure if Chrome would be able to use this if we change the language dynamically from JS.

@pm2kjiagm could you please explain how we should test this properly?
