### ISSUE TITLE
Add function to resolve DNS requests in AdGuardHome (local network)

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#1798]
Hello, thank you for this project :-)

Can you add an **DNS Cache/Server to AdGuardHome**, it would be very helpful. 
Most of the DNS requests on my network (and I guess other user too) is to an small amount of predefined Domains.
It would be an big adventage if all of this requests would be resolved with an local DNS Cache/Server.

As AdGuardHome is an DNS based Advertisement blocker it fits together to have an DNS Cache/Server function built-in.

_Pdnsd bind9 squid3 DNSmasq_ like services, I found that would do the job, but I guess you know more about it.

**Explanation:**
Devices like _SmartTV, DVB Receiver, Smartphone, PC_ uses a lot of predefined endpoints that are requested every time the Device/App is started and/or used.

_Netflix Facebook Youtube Amazon GooglePlay WhattsApp Opera_ (my default Web Browser) makes more than 70% of all requests in my network. (see Picture)

There would be an big **Privacy and Speed** advantage if requests would be resolved already in AdGuardHome, because DNS requests wouldn't go to an Public resolver and the processing time will be 2ms, basiclly the Ping in Home network.

![AdGuardHome](https://user-images.githubusercontent.com/56163305/84530208-09c9df80-ace3-11ea-9121-06cc1cb14b3e.png)

Hope you consider to add an DNS Cache/Server in future releases.
I use latest release v0.102.0 on RaspberryPi 4B

**Comment by ameshkov** [comment]
@uservictor but AdGuard Home does have a cache, and it's enabled by default.

Please refer to the documentation to see how it can be configured:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
