### ISSUE TITLE
Querlog.json - not writing all queries

### ISSUE THREAD

**Issue by abdalians** [AdguardTeam/AdGuardHome#1799]
### Issue Details

* **Version of AdGuard Home server:**
v0.102.0
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
Ubiquiti ERX
* **Operating system and version:**
Centos 7

### Expected Behavior
I expect all the queries to be written to Queryjson.log

### Actual Behavior
Queryjson.log file is not being written consistently. time delayed and not all entries show up

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
> Queryjson.log file is not being written consistently. time delayed and not all entries show up

There's an in-memory buffer with up to 1000 records.

Writing every query to the file right away would create unnecessary pressure on the disk and may be harmful in the case of SSD

**Comment by abdalians** [comment]
Can we have the option though ?

**Comment by ameshkov** [comment]
There is an option: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration

Called `querylog_size_memory`, you can make it low
