### ISSUE TITLE
Upstream DNS servers options

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1800]
If you don't want the user to select both options, why not use the drop-down list or radio buttons?

![img](https://user-images.githubusercontent.com/5947035/82048151-c1f07200-96bc-11ea-961b-a3326cb50510.png)

**Comment by RonKhondji** [comment]
That is allready done.

![chrome_nTXswsmTmm](https://user-images.githubusercontent.com/6552970/84587311-5960f600-ae1e-11ea-9e7b-7455b295bc2a.png)

 Will be in V 103.

**Comment by nikeshjauhari** [comment]
when are we going to see V 103?

**Comment by ameshkov** [comment]
> when are we going to see V 103?

Soon. 

We'll have to change the scope because initially, v0.103 included too many **really heavy** tasks like the new DHCP server implementation and the content filtering proxy server. We'll plan it for the next releases and focus on bugfixing and some UI improvements like the new query log.
