### ISSUE TITLE
Bypass YouTube Ads by adding a dot

### ISSUE THREAD

**Issue by MrksHfmn** [AdguardTeam/AdGuardHome#1801]
### Problem Description
YouTube advertising cannot be blocked via DNS. however, there is a workaround

### Proposed Solution
https://www.reddit.com/r/webdev/comments/gzr3cq/fyi_you_can_bypass_youtube_ads_by_adding_a_dot/

It's already possible to add DNS rewrites, but they are not valid with an ending dot (youtube.com.). Otherwise I would simply redirect from youtube.com to youtube.com.

**Comment by ameshkov** [comment]
Unfortunately, this is not technically possible to implement on the DNS level :(
