### ISSUE TITLE
Docker Port Issues - Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by 2Max4** [AdguardTeam/AdGuardHome#1802]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ y] I am running the latest version
- [ y] I checked the documentation and found no answer
- [y ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *Docker - latest Build
* **How did you setup DNS configuration:**
  *Not there yet - once everything works redirect via. router
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 (4GB)
* **Operating system and version:**
  * Ubuntu 20.02

### Expected Behavior
Start Docker container without Error-Code

### Actual Behavior
When running Docker with the documented command and exchanged paths for workdir and confdir docker stops with the error that bind address is already in use.

### Screenshots

`Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.`

**Comment by ameshkov** [comment]
> Ubuntu 20.02

Ubuntu runs `systemd-resolved` by default and that's the problem.

You may want to disable it first:
https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu

**Comment by 2Max4** [comment]
Thanks for the fast response! I also stumbled across this suggests - however disabling it doesn't seem to be that simple since eg. Some of the conf. Files just don't exist and also with with ignoring them the "name resolution of Ubuntu" failed.

I am now trying to set up an own network in docker - let's see if it helps. However if this is a known "issue" it would be great to find a official workaround in the docs...

Greetings

**Comment by ameshkov** [comment]
Well, the point is that if you disable it and run AdGuard Home on the same port, Ubuntu will start using it instead.

**Comment by 2Max4** [comment]
Hey - thanks for your support!

Since I managed to get everything up and running using Ubuntu 20.02 on the Raspberry 4 it might be a good idea to tell others which steps it might take to set it up - wich are not obvious in the first place. If this isn't the right place - please tell me and move the comment...

- So the first step - and also the main reason why I wrote here - is the Ubuntu on-board DNS service. That should be disabled - just like @ameshkov told.

- Another point is, that you should not simply pull the :latest version. You have to use the tag for your architecture :arm64-latest

I also had the issue Name or Service not known - Make sure, that the hostname is written in the /etc/hosts file as 127.0.0.1 <hostname> - then it should work :)

Hope it helps everyone
Greetings

**Comment by david101-hunter** [comment]
Hi, Finally, what should I do to overcome this isssue?
