### ISSUE TITLE
没有攻击防御机制，架设在公网会被攻击

### ISSUE THREAD

**Issue by mylucien** [AdguardTeam/AdGuardHome#1804]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by Potterli20** [comment]
很正常，你可以不甩

**Comment by ameshkov** [comment]
I guess you mean some kind of a DNS amplification attack?

AdGuard Home does provide some protective measures:

1. There is a default rate limit set to 20rps (which you can change in the settings).
2. DNS Settings -> Access settings. There you can configure which clients are allowed or disallowed, which may also be useful.

Generally, if you are running a public DNS resolver, you need to monitor the query log and block unwanted clients or domains from time to time.
