### ISSUE TITLE
Is it possible to resolve hostnames when using a router as DHCP and forwarding DNS to AGH on RPi3?

### ISSUE THREAD

**Issue by christasich** [AdguardTeam/AdGuardHome#1805]
Right now, all my clients in AGH query log are showing as my router IP (192.168.86.1). In the past, my PiHole installation had the ability to discern individual clients from the router. I don't quite remember the config, but I know I was using the router as DHCP and PiHole as DNS. Is it possible to do this with AGH on my RPi3? I did recently upgrade my router to a Google Nest Router so it might also be that it's not possible with the limited config options in the Nest Router.

**Comment by ameshkov** [comment]
Well, most likely your router is proxying DNS queries for some reason. This is not common, but it does happen with some routers. I have no experience with Google Nest so it's rather for me to say if this is possible to disable that.

You may also want to look for a way to disable DHCP on your router and use the one provided by AGH.

**Comment by ameshkov** [comment]
This seems to be relevant: https://www.reddit.com/r/GoogleWiFi/comments/8xcvnw/google_wifi_with_a_different_dhcp_server/

**Comment by christasich** [comment]
Ah, I think that's it. When I look at the DNS server my PC gets from the router, it shows the router IP.

![image](https://user-images.githubusercontent.com/5304026/84605401-791a0d80-ae62-11ea-8d20-ffaf58418c59.png)

Basically, it's broadcasting it's IP as the DNS server, and then it forwards all requests to the upstream DNS that I've specified (in this case the AGH server). Do I have that right?

**Comment by ameshkov** [comment]
> Do I have that right?

Yeah, seems so.

> I would just put my Nest Router in bridge mode, but then I lose the mesh functionality.

The guy on Reddit proposed a more tricky solution - narrowing the DHCP range to one IP on the Google router, and exclude that IP from the range that the second DHCP uses. Sounds plausible.

**Comment by christasich** [comment]
I tried to implement it but I'm struggling to enable the AGH DHCP server.

![image](https://user-images.githubusercontent.com/5304026/84605792-c64bae80-ae65-11ea-81b8-63becef2d3f9.png)

My RPi3 has a static IP at eth0. I think it might be complicated by the fact that it's running on HassIO. I think that means it's probably in a Docker container? Any advice on how to fix it?

**Comment by ameshkov** [comment]
Huh, if it is indeed inside Docker, this makes things quite complicated.

Here's how we check if the device has static IP:
```
		body, err := ioutil.ReadFile("/etc/dhcpcd.conf")
		if err != nil {
			return false, err
		}

		return hasStaticIPDhcpcdConf(string(body), ifaceName), nil
```

I guess `/etc/dhcpcd.conf` file is missing in the container (which is understandable). As an option, you can trick it by creating an empty file there.

**Comment by christasich** [comment]
That fixed the first error, but I'm still unable to enable the DHCP.

![image](https://user-images.githubusercontent.com/5304026/84606068-1fb4dd00-ae68-11ea-9939-e5ebf6414700.png)

It says I can still enable it in the error message, but the button is dimmed and won't let me select it.

**Comment by christasich** [comment]
I was able to force it by manually editing the AdGuard yaml file. Limited the IP range seems to have worked! I now have client IPs and names populated in AdGuard. Thanks for the help!

**Comment by christasich** [comment]
I was able to force it by manually editing the AdGuard yaml file. Limited the IP range seems to have worked! I now have client IPs and names populated in AdGuard. Thanks for the help!

**Comment by ameshkov** [comment]
Awesome, please let me know if you encounter any issues with this approach later.

**Comment by VR6Pete** [comment]
Hi, 

I come here with the same problem and have the Google Wifi mesh setup. 

Google support useless as always. 

I can see the clients listed under Clients (runtime) Data on the clients that use AdGuard Home, but not stored in the configuration - but no requests listed even when I create an explicit client configuration.

Has anyone managed to get this working without messing around setting up additional DHCP servers. 

Cheers !
