### ISSUE TITLE
Adguard Home call to non existent IP's in my network

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#1809]
Adguard is 10.10.50.5
All the IPs in destination belong to networks that doesn't exist, what functionality of AGH is doing this calls? It should only do DNS traffic, and this is not.

![image](https://user-images.githubusercontent.com/17175395/84866115-94ab3100-b079-11ea-9a67-334b68c7f424.png)

**Comment by szolin** [comment]
Why do you think it's AGH that makes these connections?
Please use `netstat -anp` on the system where AGH is runing and find the process name.

**Comment by ameshkov** [comment]
I don't think we're initiating any connections to port 32400.

Please do what @szolin proposes, maybe even run tcpdump and find out what process makes these connections.

If it is indeed AdGuard Home (which I doubt), please reopen this issue.
