### ISSUE TITLE
[not ad related] soft banned from Google services with AdGuard Home as DNS

### ISSUE THREAD

**Issue by dgraziotin** [AdguardTeam/AdGuardHome#1811]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0
* **How did you setup DNS configuration:**
  * On a Synology, DNS IP put in router to serve my house
* **If it's a router or IoT, please write device model:**
  * Synology DS918+, Fritz!Box 7590
* **Operating system and version:**
  * macOS and iOS, latest versions

### Expected Behavior

I use Google Services as expected.

### Actual Behavior

Google soft bans me. What I mean with this. I can access all Google Services, but either some functionalities are blocked or some content is blocked. This only when I use AdGuard Home as my DNS. Forcing any other DNS service at the OS level (plus closing the browser, waiting a little, and trying again) fixes the issue, so this is does not seem related to any other software I am using. This is also present on all devices in my house, used by different users.

Issues include having a very small subset of Youtube videos available to watch, being prevented to use Google Pagespeed Insights, and so on.

- Parental control, safe search, browsing security are disabled.
- Right now I am running *without entries* in AdGuard Home DNS blocklist, because I was trying to debug whether it was a filter list I was using. Apparently, it is not.

Upstream DNS servers, used with "fastest IP address" mode

- tls://dns.quad9.net
- tls://dns.adguard.com
- tls://dot-de.blahdns.com
- tls://dns.switch.ch

### Screenshots

<details><summary>Screenshot:</summary>

Concrete example, maybe replicable by other users:
Youtube channel https://www.youtube.com/user/commentiquette/videos

With AdGuard Home

<img width="1327" alt="Screen Shot 2020-06-18 at 11 15 50" src="https://user-images.githubusercontent.com/153179/85003352-62bbcc80-b156-11ea-90f7-a50ea309c717.png">

With Cloudflare DNS

<img width="1327" alt="Screen Shot 2020-06-18 at 11 19 19" src="https://user-images.githubusercontent.com/153179/85003361-65b6bd00-b156-11ea-9dff-7714d4bde9a3.png">

</details>

### Additional Information

Feel free to ask for anything to help you debug this.

**Comment by ameshkov** [comment]
I don't recommend using these resolvers together, it'd be inconsistent.

AdGuard DNS and BlahDNS block different domains so a query may be blocked by one and not blocked by the other, the outcome would be unpredictable.

With AdGuard Home I suggest using only DNS resolvers that don't do filtering on their own -- AdGuard DNS unfiltered, Quad, Cloudflare, and configure blocklists on your own.

Regarding the issue, this is either caused by the blocklists or resolvers. Try disabling blocklists one by one to see which one causes it.

**Comment by dgraziotin** [comment]
Yup, removing BLAH and using tls://dns-unfiltered.adguard.com fixes the issue. Thanks for the super prompt reply! I added the upstream resolvers by quickly browsing through https://kb.adguard.com/en/general/dns-providers to see which provided DNS-over-TLS and should have paid more attention on whether they were filtering or not.
