### ISSUE TITLE
 [fatal] Can't initialize TLS module at OpenWrt v0.102.0

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1812]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuardHome v0.102.0
* **How did you setup DNS configuration:**
  *  Router
* **If it's a router or IoT, please write device model:**
  *   amd64 device
* **Operating system and version:**
  *  OpenWrt 19.07.3

### Expected Behavior

Bootup like before
### Actual Behavior

fatal log occurs in system log
```
Thu Jun 18 22:22:07 2020 user.notice AdGuardHome[29811]: 2020/06/18 14:22:07 [info] Stopped
Thu Jun 18 22:22:26 2020 user.notice AdGuardHome[31276]: 2020/06/18 14:22:26 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
Thu Jun 18 22:22:26 2020 user.notice AdGuardHome[31276]: 2020/06/18 14:22:26 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
Thu Jun 18 22:22:26 2020 user.notice AdGuardHome[31276]: 2020/06/18 14:22:26 [info] Auth: initialized.  users:1  sessions:1
Thu Jun 18 22:22:26 2020 user.notice AdGuardHome[31276]: 2020/06/18 14:22:26 [fatal] Can't initialize TLS module
Thu Jun 18 22:22:31 2020 user.notice AdGuardHome[31439]: 2020/06/18 14:22:31 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
Thu Jun 18 22:22:31 2020 user.notice AdGuardHome[31439]: 2020/06/18 14:22:31 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
Thu Jun 18 22:22:31 2020 user.notice AdGuardHome[31439]: 2020/06/18 14:22:31 [info] Auth: initialized.  users:1  sessions:1
Thu Jun 18 22:22:31 2020 user.notice AdGuardHome[31439]: 2020/06/18 14:22:31 [fatal] Can't initialize TLS module
Thu Jun 18 22:22:36 2020 user.notice AdGuardHome[31601]: 2020/06/18 14:22:36 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
Thu Jun 18 22:22:36 2020 user.notice AdGuardHome[31601]: 2020/06/18 14:22:36 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
Thu Jun 18 22:22:36 2020 user.notice AdGuardHome[31601]: 2020/06/18 14:22:36 [info] Auth: initialized.  users:1  sessions:1
Thu Jun 18 22:22:36 2020 user.notice AdGuardHome[31601]: 2020/06/18 14:22:36 [fatal] Can't initialize TLS module
Thu Jun 18 22:22:41 2020 user.notice AdGuardHome[31758]: 2020/06/18 14:22:41 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
Thu Jun 18 22:22:41 2020 user.notice AdGuardHome[31758]: 2020/06/18 14:22:41 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
Thu Jun 18 22:22:41 2020 user.notice AdGuardHome[31758]: 2020/06/18 14:22:41 [info] Auth: initialized.  users:1  sessions:1
Thu Jun 18 22:22:41 2020 user.notice AdGuardHome[31758]: 2020/06/18 14:22:41 [fatal] Can't initialize TLS module
Thu Jun 18 22:22:46 2020 user.notice AdGuardHome[31916]: 2020/06/18 14:22:46 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
Thu Jun 18 22:22:46 2020 user.notice AdGuardHome[31916]: 2020/06/18 14:22:46 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
Thu Jun 18 22:22:46 2020 user.notice AdGuardHome[31916]: 2020/06/18 14:22:46 [info] Auth: initialized.  users:1  sessions:1
Thu Jun 18 22:22:46 2020 user.notice AdGuardHome[31916]: 2020/06/18 14:22:46 [fatal] Can't initialize TLS module
Thu Jun 18 22:22:51 2020 user.notice AdGuardHome[32074]: 2020/06/18 14:22:51 [info] AdGuard Home, version v0.102.0, channel release, arch linux amd64
Thu Jun 18 22:22:51 2020 user.notice AdGuardHome[32074]: 2020/06/18 14:22:51 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
Thu Jun 18 22:22:51 2020 user.notice AdGuardHome[32074]: 2020/06/18 14:22:51 [info] Auth: initialized.  users:1  sessions:1
Thu Jun 18 22:22:51 2020 user.notice AdGuardHome[32074]: 2020/06/18 14:22:51 [fatal] Can't initialize TLS module
Thu Jun 18 22:22:51 2020 daemon.info procd: Instance AdGuardHome::instance1 s in a crash loop 6 crashes, 1 seconds since last crash
```
### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22477230/85033352-6af62500-b1b3-11ea-805e-5358b5786bf1.png)

</details>

### Additional Information

I used this version when it was first released, except for #1735 there no other bugs until now, and I installed a tcpdump on OpenWrt yesterday and reboot my router today (after it runs 2 weeks) then I found AGH cannot startup. It seems like some TLS lib or depends wrong, but I don't know why.

**Comment by ameshkov** [comment]
@Mosney please check that the certificate that you're using is not expired

**Comment by Mosney** [comment]
Addition: I switch back to version 0.101.0, It works well.

**Comment by Mosney** [comment]
> @Mosney please check that the certificate that you're using is not expired

God, Catch this. you are right, May more specific log next time, I still think it was TLS depend relevant.

**Comment by Mosney** [comment]
Or maybe I should turn debug log on first, it's my fault

**Comment by ameshkov** [comment]
> God, Catch this. you are right, May more specific log next time, I totally think it was TLS depend relevant.

This is actually a valid bug, AdGuard mustn't crash when the certificate is expired, and we fixed this in the master branch.

**Comment by Mosney** [comment]
> > God, Catch this. you are right, May more specific log next time, I totally think it was TLS depend relevant.
> 
> This is actually a valid bug, AdGuard mustn't crash when the certificate is expired, and we fixed this in the master branch.

Can't wait for new release! Log spam is tooooo annoying.  #173
