### ISSUE TITLE
Can't connect to AdGuard Home Web Interface

### ISSUE THREAD

**Issue by edchuchuchu** [AdguardTeam/AdGuardHome#1815]
Same issue happen on pi4B. https://github.com/AdguardTeam/AdGuardHome/issues/395#issue-371604572
Firewall looks fine on my end.
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
I had tried the solution - I ran sudo systemctl daemon-reload after I ran sudo systemctl enable adguard-home and sudo systemctl start adguard-home and it is NOT working for me.

**Comment by emlimap** [comment]
Run `systemctl status adguard-home` to check the status of the service and any error messages if it isn't running.

If the service is running, then you could check to see if AdGuard is listening on any ports.

If your OS supports netstat, the run `netstat -lnptu` and see if AdGuard Home shows up on port 80.

If it doesn't come with netstat, then try `ss -tlnp`

**Comment by edchuchuchu** [comment]
Thanks for responded.
`systemctl status adguard-home` returns `Unit adguard-home.service could not be found.`. But I can verify the service is running by `./AdGuardHome -s status`
Besides, `ss -tlnp` shows AdGuard Home is listening port 80.
```
State    Recv-Q    Send-Q        Local Address:Port       Peer Address:Port
LISTEN   0         128               127.0.0.1:80              0.0.0.0:*       users:(("AdGuardHome",pid=4274,fd=12))
LISTEN   0         128          192.168.86.161:53              0.0.0.0:*       users:(("AdGuardHome",pid=4274,fd=23))
LISTEN   0         128                 0.0.0.0:22              0.0.0.0:*       users:(("sshd",pid=1104,fd=3))
LISTEN   0         128                    [::]:22                 [::]:*       users:(("sshd",pid=1104,fd=4))
```

**Comment by emlimap** [comment]
AdGuard Home is listening at `127.0.0.1`. As a result, the web interface is is only accessible locally within the Pi and not over the network.

Find `AdGuardHome.yaml` file, it should be in the same folder as AdGuardHome binary and change the `bind_host` parameter at the top of the file to one of the below options and restart the service.

```
bind_host: 192.168.86.161
```
or 
```
bind_host: 0.0.0.0
```
If you had used AdGuardHome to install the service (`./AdGuardHome -s install`), then the service would be called `AdGuardHome` unless you renamed it or created the service file on your own. So try `systemctl status AdGuardHome`

**Comment by edchuchuchu** [comment]
Cool. changes the `bind_host` solved my issue.
I think this instruction might need to update. https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi
