### ISSUE TITLE
Use get-method to get the block file

### ISSUE THREAD

**Issue by 280blocker** [AdguardTeam/AdGuardHome#1816]
I have an ad blocking filter file on my website. We get a lot of post-method accesses from ag-dns every day.
The cache server(cloudflare CDN) doesn't work well for post-method file access. It increases the load on origin web server.

The origin web server logs are shown below. I'm guessing the cause of this is Adguard Home, but I'm not sure if it's the AdguardDNS server or Other Adguard products could be the cause.
Or is it due to the user's improper use of Adguard?

If you are using post-method to get the adblock filter in Adguard  products, please use get-method.

280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:01 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:01 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:01 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:02 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:02 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:02 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:02 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:03 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:07 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"
280blocker.net 162.158.119.77 - - [19/Jun/2020:03:57:07 +0900] "POST /files/280blocker_domain_ag.txt HTTP/1.1" 200 7787 "-" "ag-dns"

**Comment by 280blocker** [comment]
I was able to block the retrieval of certain files using post-method on a cache server.
The server load problem has been solved.

**Comment by ameshkov** [comment]
@280blocker hm, we mustn't be using POST requests anywhere so I am not sure where it comes from. `ag-dns` is also a strange user agent, I can't find anything like that in our sources.

You can check `CF-Connecting-IP` header and see where these queries come from. Maybe they all are coming from the same IP?
