### ISSUE TITLE
上游服务器增加更多语法

### ISSUE THREAD

**Issue by Kagura-Nanaa** [AdguardTeam/AdGuardHome#1818]
[/example.local/]9.9.9.9希望这种语法可以支持通配符.或者域名中包含特定字符则指定特定的上游服务器.如/ab/1.1.1.1 域名中包含ab,则使用1.1.1.1作为上游服务器

**Comment by Potterli20** [comment]
有的

**Comment by Potterli20** [comment]
范例:
9.9.9.9 - 基于 UDP 协议的 DNS 服务器（DNS-over-UDP）
tls://dns.quad9.net – 基于 TLS 协议的 DNS 服务器（DNS-over-TLS）
https://dns.quad9.net/dns-query – 基于 HTTPS 协议的 DNS 服务器（DNS-over-HTTPS）
tcp://9.9.9.9 – 基于 TCP 协议的 DNS 服务器（DNS-over-TCP）
sdns://... – 基于 DNS Stamps 格式的 DNS 服务器（DNS-over-HTTPS 或 DNSCrypt）
[/example.local/]9.9.9.9 – 为特定域指定上游 DNS 服务器

**Comment by Kagura-Nanaa** [comment]
> 范例：9.9.9.9-基于UDP协议的DNS服务器（DNS-over-UDP）
> tls：//dns.quad9.net –基于TLS协议的DNS服务器（DNS-over-TLS）
> [https：//dns.quad9。 net / dns-query](https://dns.quad9.net/dns-query) –基于HTTPS协议的DNS服务器（DNS-over-HTTPS）
> tcp：//9.9.9.9 –基于TCP协议的DNS服务器（DNS-over-TCP）
> sdns：// ... –基于DNS邮票的格式的DNS服务器（HTTP-over-HTTPS或DNSCrypt）
> [/example.local/]9.9.9.9 –为特定域指定上游DNS服务器

又是你,还是不好好读题
如果你会中文 那么就好好读题
如果不会 那就等官方回答吧😓

**Comment by Potterli20** [comment]
> > 范例：9.9.9.9-基于UDP协议的DNS服务器（DNS-over-UDP）
> > tls：//dns.quad9.net –基于TLS协议的DNS服务器（DNS-over-TLS）
> > [https：//dns.quad9。 net / dns-query](https://dns.quad9.net/dns-query) –基于HTTPS协议的DNS服务器（DNS-over-HTTPS）
> > tcp：//9.9.9.9 –基于TCP协议的DNS服务器（DNS-over-TCP）
> > sdns：// ... –基于DNS邮票的格式的DNS服务器（HTTP-over-HTTPS或DNSCrypt）
> > [/example.local/]9.9.9.9 –为特定域指定上游DNS服务器
> 
> 又是你,还是不好好读题
> 如果你会中文 那么就好好读题
> 如果不会 那就等官方回答吧

如果是这样还不如，ad:8.8.8.8
这样够简洁了叭
还说什么，/ab/1.1.1 1

**Comment by Kagura-Nanaa** [comment]
> > > 范例：9.9.9.9-基于UDP协议的DNS服务器（UDP-over-UDP）
> > > tls：//dns.quad9.net –基于TLS协议的DNS服务器（DNS-over-TLS）
> > > [https：//dns.quad9。 net / dns查询](https://dns.quad9.net/dns-query) –基于HTTPS协议的DNS服务器（HTTP-over-HTTPS）
> > > tcp：//9.9.9.9 –基于TCP协议的DNS服务器（DNS-over-TCP）
> > > sdns：// ... –基于DNS邮票的格式的DNS服务器（HTTP-over-HTTPS或DNSCrypt）
> > > [/example.local/]9.9.9.9 –为特定域指定上游DNS服务器
> > 
> > 
> > 又是你，还是不好好读题
> > 如果你会中文那么就好好读题
> > 如果不会那就等官方回答吧
> 
> 如果是这样还不如，ad：8.8.8.8
> 这样够简洁了叭
> 还说什么，/ ab / 1.1.1 1

那现有语法中[/example.local/]9.9.9.9岂不是更麻烦？
不是简洁的问题

**Comment by Potterli20** [comment]
> > > > 范例：9.9.9.9-基于UDP协议的DNS服务器（UDP-over-UDP）
> > > > tls：//dns.quad9.net –基于TLS协议的DNS服务器（DNS-over-TLS）
> > > > [https：//dns.quad9。 net / dns查询](https://dns.quad9.net/dns-query) –基于HTTPS协议的DNS服务器（HTTP-over-HTTPS）
> > > > tcp：//9.9.9.9 –基于TCP协议的DNS服务器（DNS-over-TCP）
> > > > sdns：// ... –基于DNS邮票的格式的DNS服务器（HTTP-over-HTTPS或DNSCrypt）
> > > > [/example.local/]9.9.9.9 –为特定域指定上游DNS服务器
> > > 
> > > 
> > > 又是你，还是不好好读题
> > > 如果你会中文那么就好好读题
> > > 如果不会那就等官方回答吧
> > 
> > 
> > 如果是这样还不如，ad：8.8.8.8
> > 这样够简洁了叭
> > 还说什么，/ ab / 1.1.1 1
> 
> 那现有语法中[/example.local/]9.9.9.9岂不是更麻烦？
> 不是简洁的问题

如果是麻烦，可以不用这个功能，默认就行

**Comment by Kagura-Nanaa** [comment]
> > > > > 范例：9.9.9.9-基于UDP协议的DNS服务器（UDP-over-UDP）
> > > > > tls：//dns.quad9.net –基于TLS协议的DNS服务器（DNS-over-TLS）
> > > > > [https：//dns.quad9。 net / dns查询](https://dns.quad9.net/dns-query) –基于HTTPS协议的DNS服务器（HTTP-over-HTTPS）
> > > > > tcp：//9.9.9.9 –基于TCP协议的DNS服务器（DNS-over-TCP）
> > > > > sdns：// ... –基于DNS邮票的格式的DNS服务器（HTTP-over-HTTPS或DNSCrypt）
> > > > > [/example.local/]9.9.9.9 –为特定域指定上游DNS服务器
> > > > 
> > > > 
> > > > 又是你，还是不好好读题
> > > > 如果你会中文那么就好好读题
> > > > 如果不会那就等官方回答吧
> > > 
> > > 
> > > 如果是这样还不如，ad：8.8.8.8 
> > > 这样够简洁了叭
> > > 还说什么，/ ab / 1.1.1 1
> > 
> > 
> > 那现有语法中[/example.local/]9.9.9.9岂不是更
> > 麻烦？不是简洁的问题
> 
> 如果是麻烦，可以不用这个功能，默认就行

如果你没有懂我的意思,那么请不要再说了

**Comment by Potterli20** [comment]
> > > > > > 范例：9.9.9.9-基于UDP协议的DNS服务器（UDP-over-UDP）
> > > > > > tls：//dns.quad9.net –基于TLS协议的DNS服务器（DNS-over-TLS）
> > > > > > [https：//dns.quad9。 net / dns查询](https://dns.quad9.net/dns-query) –基于HTTPS协议的DNS服务器（HTTP-over-HTTPS）
> > > > > > tcp：//9.9.9.9 –基于TCP协议的DNS服务器（DNS-over-TCP）
> > > > > > sdns：// ... –基于DNS邮票的格式的DNS服务器（HTTP-over-HTTPS或DNSCrypt）
> > > > > > [/example.local/]9.9.9.9 –为特定域指定上游DNS服务器
> > > > > 
> > > > > 
> > > > > 又是你，还是不好好读题
> > > > > 如果你会中文那么就好好读题
> > > > > 如果不会那就等官方回答吧
> > > > 
> > > > 
> > > > 如果是这样还不如，ad：8.8.8.8
> > > > 这样够简洁了叭
> > > > 还说什么，/ ab / 1.1.1 1
> > > 
> > > 
> > > 那现有语法中[/example.local/]9.9.9.9岂不是更
> > > 麻烦？不是简洁的问题
> > 
> > 
> > 如果是麻烦，可以不用这个功能，默认就行
> 
> 如果你没有懂我的意思,那么请不要再说了

你这是没有例子的项目乱说

**Comment by ameshkov** [comment]
我不懂为什么这样的功能有用。请提供一些实际的例子。

**Comment by Potterli20** [comment]
#1680

**Comment by ameshkov** [comment]
#1680 is a little bit different.

@Kagura-Nanaa 你可以看看 #1680 然后告诉你这是否适合吗？

**Comment by Kagura-Nanaa** [comment]
> 我不懂为什么这样的功能有用。请提供一些实际的例子。

一些网址使用指定的上游可能会解析过慢或者失败，需要手动为它们指定解析器，但是这些网址通常会有许多子域，使用下图中的规则只能指定一个网址（？）
<img width="405" alt="0JuoqqQbty" src="https://user-images.githubusercontent.com/44108528/85348841-5e652a00-b52f-11ea-8ba6-1da5766f2e4e.png"> 所以我想，他应该支持通配符，如[/*.example.local/]9.9.9.9

**Comment by Kagura-Nanaa** [comment]
一些网址使用指定的上游可能会解析过慢或者失败，需要手动为它们指定解析器，但是这些网址可能会有许多子域，一个一个添加会很麻烦，使用下图中的规则只能指定一个网址（？）
<img width="432" alt="chrome_BfU1WDRzsy" src="https://user-images.githubusercontent.com/44108528/85349046-f6fbaa00-b52f-11ea-9a87-394a1cd0b5c8.png">
所以我想，他应该支持通配符，如[/*.example.local/]9.9.9.9

**Comment by Kagura-Nanaa** [comment]
或者，像这样
<img width="487" alt="chrome_dZ2Q6tpp5n" src="https://user-images.githubusercontent.com/44108528/85349437-05969100-b531-11ea-9b8a-3b9539ea219f.png"> 和自定义过滤规则一样（？）
<img width="311" alt="chrome_BEDbNRKGcl" src="https://user-images.githubusercontent.com/44108528/85349514-3b3b7a00-b531-11ea-8da3-756a59da6f4c.png">

**Comment by Potterli20** [comment]
#1759

**Comment by ameshkov** [comment]
@Kagura-Nanaa 

`[/example.org/]` 就是 `example.org` + `*.example.org` 一样
