### ISSUE TITLE
What is going on here? "duplicated" domans in log

### ISSUE THREAD

**Issue by gpioneer90** [AdguardTeam/AdGuardHome#1819]
I'm not sure how to descibe this better so please look at the screenshot
![Screenshot 2020-06-22 at 01 55 01](https://user-images.githubusercontent.com/35205174/85257555-a6028d80-b42b-11ea-91f7-a1dbf22110bb.png)

With every blocked request, a new "allowed" request is duplicated and appended .attlocal.net (my router. If I switch routers, it appends that router's domain..)

Is this normal behavior? Adblocking still works. Am just wondering why it resends the request and duplicates it for every blocked request

**Comment by ameshkov** [comment]
This is called "search domain". Your system is configured to retry every query answered with NXDOMAIN by appending a "search domain" to the domain name.

This is not a problem, but if you want you can change your system settings to get rid of these queries.

**Comment by gpioneer90** [comment]
What do you mean by "system"? The Adguard Home? The Pi it's installed on? The router?

**Comment by ameshkov** [comment]
Neither, I mean the device that uses the DNS server

**Comment by gpioneer90** [comment]
Thank you. 

(in my case, my device is a Chromebook and I can't find an option to modify this setting. But changing Adguard Home's DNS response from NXDOMAIN to Null IP got rid of the duplicate domains. I'm sure, as you say, it's not an issue, but getting rid of the duplicates makes looking at AGH's log easier, with less entries)
