### ISSUE TITLE
DHCP: add custom DNS address

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1822]
DHCP options will be added in #1585
It's probably a good idea to have an ability to add secondary DNS address.

**Comment by valaria247** [comment]
Does this same #1708?

**Comment by valaria247** [comment]
@szolin #1708 has assigned to v0.106 milestone while this v0.104 then either reopen this or assign #1708 to v0.104

**Comment by jd1900** [comment]
How is this?

I really miss this option, as a failure in the Raspberry PI (where I have the AdGuard with DHCP) will crash my clients.
