### ISSUE TITLE
adguard home linux and dhcp server

### ISSUE THREAD

**Issue by pippo73** [AdguardTeam/AdGuardHome#1825]
### Prerequisites

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuardHome v0.102.0
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 =
* **Operating system and version:**
 $ uname -a
Linux sk4mc 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

### Expected Behavior
"check the presence of a DHCP server" detects the dhcp server running on the same system

### Actual Behavior
If I click the detect button in _settings -> dhcp settings_ it does not detects the presence of a isc-dhcp-server running on the same server

**Comment by szolin** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.


Also, can you provide tcpdump output of DHCP messages?
