### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1826]
Openwrt x64 within Adguard Home latest version

Add Suricata Network IDS/IPS System and Comode Antivirus Linux edition/BitDefender For Unices in Adguard Home,thank you!

Mainland China currently has the ability to hijack overseas traffic. The most effective way to prevent this hijacking is to use certificate pinning. The certificate pinning was canceled in the Chrome browser at the end of April 2018. Since version 72, Firefox has also turned off certificate pinning by default. Without certificate pinning, it will not be able to resist such national-level hacking attacks.

HTTP public key pinning (also known as HTTP public key pinning, English: HTTP Public Key Pinning, abbreviated as HPKP) [1] is a type of HTTPS website that prevents attackers from using digital certificate certification authority (CA) wrongly issued certificates to perform man-in-the-middle attacks The security mechanism is used to prevent CA from being invaded or other situations that will cause the CA to issue unauthorized certificates. When public key fixation is used, the website will provide a hash list of authorized public keys, instructing the client to accept only the public keys on the list in subsequent communications.

Could add a extension function to used firefox extension add more function by myself?
Cookie Jar
Sandbox your cookies.
Decentraleyes
Protects you against tracking through "free", centralized, content delivery.
IPFuck
Location Guard
Hide your geographic location from websites.
Privacy Badger
Privacy Badger automatically learns to block invisible trackers.

Canvas Fingerprint Protection:
WebRTC Protection:
Remove Google Analytics (UTM) Tracking:

**Comment by ameshkov** [comment]
Please add a comment about that to #1446 

> Could add a extension function to used firefox extension add more function by myself?

What exactly would you like to have in such an extension?
