### ISSUE TITLE
[Bug]Whois cannot be displayed on the home page domain list

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#1827]
On the v0.102.0-88-g7d93-r96f8
Whois cannot be displayed on the home page domain list
I am sorry that I cannot post on GitHub

**Comment by Potterli20** [comment]
![IMG_20200624_010407_579](https://user-images.githubusercontent.com/28734349/85433287-c90d7880-b5b6-11ea-9768-584118b3ce8a.jpg)

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1817 ?

**Comment by Potterli20** [comment]
> Duplicate of #1817 ?

Yes

**Comment by ameshkov** [comment]
Closed as dup then, we'll fix this in #1817

**Comment by Potterli20** [comment]
> Closed as dup then, we'll fix this in #1817

OK
