### ISSUE TITLE
Adguard Safebrowsing

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdGuardHome#1829]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  v0.102.0
* **How did you setup DNS configuration:**
  Router
* **If it's a router or IoT, please write device model:**
  Dlink Dir-825 AC
* **Operating system and version:**
 Solus KDE

### Expected Behavior
No log saying safebrowsing error

### Actual Behavior
Set up adguard home and everything is working but from time to time throwing error in log

2020/06/24 15:39:15 [info] SafeBrowsing: failed: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=PlUBAAABAAAAAAAACDY4ODhiNWUyCGUwMGFkZmYwCDkxNzlhMjkxAnNiA2RucwdhZGd1YXJkA2NvbQAAEAAB": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Screenshots

![image](https://user-images.githubusercontent.com/46019727/85542280-bb013b80-b63a-11ea-89a7-432b24fafb9d.png)

<details><summary>Screenshot:</summary>

</details>

### Additional Information
When A website is blocked, the adguard blocked gui which shows up in the browser not showing. Maybe it is removed now but not sure as came back after a while.
Also adguard is working fine but showing this error in the terminal

**Comment by ameshkov** [comment]
Could it be a temporary network issue?

**Comment by Bhooty** [comment]
Its working fine now 
I think it was a filter problem 
After the adguard filter 
Update it didn't showed it again 
Thanks for the reply :D 
![parental](https://user-images.githubusercontent.com/46019727/85853316-1b77b080-b7d4-11ea-88bc-3ddc9498c9f1.jpg)
![phishing](https://user-images.githubusercontent.com/46019727/85853335-24688200-b7d4-11ea-81e0-794d2519e21a.jpg)
This doesn't shows up anymore 
Is it because i am using nullip to block or its removed 
Just a question :D

**Comment by ameshkov** [comment]
Most likely it was removed.

We usually use `wmconvirus.narod.ru` to test if safebrowsing works as expected.
