### ISSUE TITLE
Unblock third-party domains only for certain site

### ISSUE THREAD

**Issue by valaria247** [AdguardTeam/AdGuardHome#1830]
I found this question > https://github.com/AdguardTeam/AdGuardHome/issues/1452 but no explained solution.

- this is not a solution https://github.com/AdguardTeam/AdGuardHome/issues/1452#issuecomment-598151327
- that's the problem https://github.com/AdguardTeam/AdGuardHome/issues/1452#issuecomment-601510172

I use the same example,

- block `cloudflare.com`
- visit `getfider.com` and will apear broken site
- it affected by `cdnjs.cloudflare.com`

If create unblock rule for `cdnjs.cloudflare.com` then it apply to all other sites use that feature (cdnjs.cloudflare.com) so how to unblock only for `getfider.com`? this may be possible because AGH has proxy feature

**Comment by valaria247** [comment]
i dont know about syntax but i mean
@@||cdnjs.cloudflare.com^/getfider.com/othersite.com

**Comment by ameshkov** [comment]
Unfortunately, this won't work on the DNS-level :(

**Comment by valaria247** [comment]
> Unfortunately, this won't work on the DNS-level :(

I know and AGH will have proxy feature within upcoming version. So is it possible to reopen this feature request?
Because this need additional improvement as explained above

**Comment by ameshkov** [comment]
> So is it possible to reopen this feature request?

Well, there would be no need for that feature request on the proxy-level, it will be there from the beginning.
