### ISSUE TITLE
Parental Filter Not Blocking Content

### ISSUE THREAD

**Issue by TheSpad** [AdguardTeam/AdGuardHome#1831]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * Version: v0.102.0
* **How did you setup DNS configuration:**
  * Manual client config
* **If it's a router or IoT, please write device model:**
  * N/A
* **Operating system and version:**
  * Docker 19.03.11 on Raspbian: Linux pi1 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux

### Expected Behavior
Adult content should be blocked by parental filter

### Actual Behavior
Log shows content as filtered but returns valid DNS record and client loads site as normal

### Screenshots
![Annotation 2020-06-24 182918](https://user-images.githubusercontent.com/8425502/85603828-a2981d80-b648-11ea-9e93-c708a4b98401.jpg)

### Additional Information
Have tried multiple browsers and clients, behaviour is the same. Have also tried client-specific settings with the same result.

**Comment by phossG** [comment]
Could it be a secondary DNS server that's responding? Most devices provide the option, but obviously there could be exceptions.

If so, filling the secondary in as localhost 127.0.0.1 could help.

**Comment by TheSpad** [comment]
No secondary DNS, also checked to make sure DOH was disabled in the browser(s).

**Comment by ameshkov** [comment]
I am not sure we can do anything - the log shows everything properly - AGH returns 176.103.130.135 which is the "Access Denied" page.

You can verify this using dig or nslookup from the command line.

**Comment by TheSpad** [comment]
Thanks guys, Knowing now that 176.103.130.135 is the AGH blockpage I sat down with wireshark and figured out what was happening.

The stuff that was NXDOMAIN-ing was no problem, but the stuff that returned a valid address was then being re-queried against my IPS DNS by my router (it has basic web filtering capabilities) when the HTTP request went out and the "correct" IP was being returned.

Forced the router to use AGH for DNS lookups and now things are being blocked as expected.
