### ISSUE TITLE
Add Step to Setup Guide in Web Interface to Add Clients to Authorized Device List

### ISSUE THREAD

**Issue by WinObs** [AdguardTeam/AdGuardHome#1832]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

After installation and getting the service running on Linux Mint - devices setup with new DNS address were not working. After several hours of troubleshooting I came across the Authorized Device List under DNS Settings. Added my main device and it immediately was able to access the DNS service across my home network.

### Proposed Solution

Add a step to the Setup Guide that includes adding devices to the Authorized Device List in DNS Settings on the web interface.

### Alternatives Considered

None

### Additional Information

I did many searches looking for a solution and could not find this as a required step. I am not sure if that means my setup is unique or not quite the norm, but it was this step that sorted out the issue for me immediately. I was able to then add all my other devices and get them working with AdGuard Home.

![Annotation 2020-06-24 170050](https://user-images.githubusercontent.com/40800748/85627784-16342d80-b63d-11ea-94da-81e7848d510e.png)

**Comment by ameshkov** [comment]
@WinObs thank you!

> After several hours of troubleshooting I came across the Authorized Device List under DNS Settings

Hmm, do you mean the DNS settings of your router?

**Comment by WinObs** [comment]
No – in the AdGuard Home web interface.

Under Settings>DNS Settings>Access Settings>Allowed Clients

[cid:image003.png@01D64B89.5F6A8EF0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ameshkov** [comment]
Hmm, by default AGH does not limit access unless there's at least one record in that list.

Could it be that you've added some records there before running into this issue?

**Comment by WinObs** [comment]
Well, it is very possible I thought I fixed it by adding my device IP to that authorized list but also fixed it otherwise during all that troubleshooting.

I just removed all of my entered IP addresses and the service continues to work on three out of twelve devices – no reason to believe the others are not also working.

Now I just wish I knew what was my original issue.

😊

Thanks for the assist and feedback. Really enjoying AdGuard Home.

Rich

P.S. You can close this one out I guess!

**Comment by ameshkov** [comment]
Thank you!
