### ISSUE TITLE
为啥顶级客户端显示的都是127.0.0.1

### ISSUE THREAD

**Issue by 412026849** [AdguardTeam/AdGuardHome#1837]
![S00627-08430063](https://user-images.githubusercontent.com/25706285/85910694-f4ac8f00-b852-11ea-9d8c-11292134a9ce.png)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by 412026849** [comment]
我是openwrt内嵌的agh

**Comment by Potterli20** [comment]
无解

**Comment by XrosSJ** [comment]
我之前在pandavan上用也是一样的问题 后来换到树莓派上 设备dns改成树莓派ip就能显示各设备了 但我手上的安卓设备显示不出来 iOS/PC可以

**Comment by ameshkov** [comment]
This just means that your router proxies DNS queries to AdGuard Home.

The solution depends on your router, sometimes it's possible to disable proxying, sometimes it's not.
