### ISSUE TITLE
[Feature Request] Add Time/Date Profiles for Devices/Clients

### ISSUE THREAD

**Issue by sturmstar** [AdguardTeam/AdGuardHome#1838]
e.g. Livingroom TV Device (eg. IP 192.168.1.x) - should be on Safesearch, Blocking Adult Sites between 6AM and 7PM
from 7PM to 6AM only blocking ADs and Malicious Sites

That would be awesome - could be used with any multi-user device at home

best regards

**Comment by ameshkov** [comment]
Sounds a lot like #951 

I'll merge it there
