### ISSUE TITLE
When you blank out Upstream DNS Server it doesnt default to Quad9

### ISSUE THREAD

**Issue by jdpg2** [AdguardTeam/AdGuardHome#1839]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

If you keep this field empty, contrary to the flavor text "**AdGuard Home will use Quad9 as an upstream**" the server doesn't apply the default and stops doing DNS lookups.

### Expected Behavior

Should use the stated default of Quad9

### Actual Behavior

Doesn't perform DNS resolution

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by szolin** [comment]
What version do you use?

What are the values of
```
upstream_dns:
bootstrap_dns:
```
in AdGuardHome.yaml file?

Please attach debug logs:
1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by ameshkov** [comment]
Cannot reproduce this.

Please reopen if you're able to repro and you've collected logs
