### ISSUE TITLE
[Feature Request] Domain DHCP Name Forwarding

### ISSUE THREAD

**Issue by jdpg2** [AdguardTeam/AdGuardHome#1841]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Unable to get DHCP Static names from the network DHCP Server.  Dashboard displays IP addresses for items even though they have Static Names associated with their Static IP Address assigned by the DHCP server on the domain.  This would make the dashboard more readable (and is a feature in Pi-Hole)

### Proposed Solution

Provide this capability vi the configuration

**Comment by Potterli20** [comment]
![image](https://user-images.githubusercontent.com/28734349/85952876-d5227d00-b99e-11ea-9df2-5374fd376872.png)
it?

**Comment by ameshkov** [comment]
You may need to configure an upstream to use for rDNS resolution:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-rdns
