### ISSUE TITLE
[Feature Request] Enable Drill Through to the Query log from the Dashboard

### ISSUE THREAD

**Issue by jdpg2** [AdguardTeam/AdGuardHome#1842]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Enable Drill through from the query log by IP/Domain.  A user selects the IP/Domain and then is take to the Query log that is pre filtered by that IP or Domain

**Comment by mHatsune** [comment]
Duplicate of #1625
