### ISSUE TITLE
Query Log to Ram?

### ISSUE THREAD

**Issue by weedb0y** [AdguardTeam/AdGuardHome#1844]
On the raspberry pi, with sensitivity towards writing lot of read/writes to the SD card, is it possible to load as much as possible into the ram thru log2ram?

I would love to have query logs be in the RAM for the most part to ensure SD cards don't die too early. 

Thoughts?

**Comment by ameshkov** [comment]
There are two relevant settings:

```
  querylog_file_enabled: true
  querylog_size_memory: 1000
```

* querylog_size_memory -- buffer size (number of log records), AdGuard Home will only write chunks of that size to the file
* querylog_file_enabled -- you can completely disable writing the log to file.

**Comment by weedb0y** [comment]
Thank you!!
