### ISSUE TITLE
[beta] BUG和建议

### ISSUE THREAD

**Issue by qpzr** [AdguardTeam/AdGuardHome#1845]
1.BUG：
我已经勾选 最快的IP地址
那么 nslookup time-ios.apple.com 就应该只返回一个最快的IP
然而 
time-ios.apple.com
类型: A, 无加密DNS
响应细节
域名
time-ios.apple.com
状态
已处理
DNS 服务器
8.8.8.8:53
耗时
1046 毫秒
响应代码
NOERROR
响应
CNAME: time-ios.g.aaplimg.com. (ttl=2642)
A: 17.253.116.125 (ttl=813)
A: 17.253.84.253 (ttl=813)
A: 17.253.84.123 (ttl=813)

2.建议：响应细节里增加规则，跟旧版本的查询日志里一样，有个规则方便排查错误
在最新的beta版本: v0.102.0-101-gda6c中 查询日志-响应细节  里面没有响应规则
如果出现错误的拦截，没有响应规则，排查起来会麻烦
例如：
08:09:54
2020/6/30
btrace.qq.com
类型: A, 无加密DNS
已拦截
AGH-diy

响应细节
域名
btrace.qq.com
状态
已拦截
DNS 服务器
—
耗时
8 毫秒
响应代码
NXDOMAIN

**Comment by Potterli20** [comment]
> BUG：
> 我已经勾选 最快的IP地址
> 那么 nslookup time-ios.apple.com 就应该只返回一个最快的IP
> 然而
> time-ios.apple.com
> A
> CNAME: time-ios.g.aaplimg.com. (ttl=773)
> A: 17.253.84.123 (ttl=220)
> A: 17.253.68.253 (ttl=220)
> A: 17.253.68.125 (ttl=220)
> 
> 在最新的beta版本中 查询日志-响应信息 里面没有响应规则
> 如果出现错误的拦截，没有响应规则，排查起来会麻烦
> 建议：响应信息里增加规则，跟旧版本的查询日志里一样，有个规则方便排查错误

你是局域网选择？还是广域网？

**Comment by Potterli20** [comment]
如果没有响应规则，就是空白，没有加黑名单

**Comment by qpzr** [comment]
> > BUG：
> > 我已经勾选 最快的IP地址
> > 那么 nslookup time-ios.apple.com 就应该只返回一个最快的IP
> > 然而
> > time-ios.apple.com
> > A
> > CNAME: time-ios.g.aaplimg.com. (ttl=773)
> > A: 17.253.84.123 (ttl=220)
> > A: 17.253.68.253 (ttl=220)
> > A: 17.253.68.125 (ttl=220)
> > 在最新的beta版本中 查询日志-响应信息 里面没有响应规则
> > 如果出现错误的拦截，没有响应规则，排查起来会麻烦
> > 建议：响应信息里增加规则，跟旧版本的查询日志里一样，有个规则方便排查错误
> 
> 你是局域网选择？还是广域网？

我装在路由器上的运行的，是局域网。smartdns就可以 只返回一个IP。 然而AGH 我只勾选了最快的IP地址 却还是返回多个IP地址

**Comment by qpzr** [comment]
> 如果没有响应规则，就是空白，没有加黑名单，这个是我图![Screenshot_2020-06-30-07-40-44-361_com android chrome](https://user-images.githubusercontent.com/28734349/86066810-c4106380-baa5-11ea-89a9-ace82c1dcdbb.jpg)

我不知道 是不是就这些 time-ios.apple.com 类似带-的网址 属于个例

**Comment by Potterli20** [comment]
> > > BUG：
> > > 我已经勾选 最快的IP地址
> > > 那么 nslookup time-ios.apple.com 就应该只返回一个最快的IP
> > > 然而
> > > time-ios.apple.com
> > > A
> > > CNAME: time-ios.g.aaplimg.com. (ttl=773)
> > > A: 17.253.84.123 (ttl=220)
> > > A: 17.253.68.253 (ttl=220)
> > > A: 17.253.68.125 (ttl=220)
> > > 在最新的beta版本中 查询日志-响应信息 里面没有响应规则
> > > 如果出现错误的拦截，没有响应规则，排查起来会麻烦
> > > 建议：响应信息里增加规则，跟旧版本的查询日志里一样，有个规则方便排查错误
> > 
> > 
> > 你是局域网选择？还是广域网？
> 
> 我装在路由器上的运行的，是局域网。smartdns就可以 只返回一个IP。 然而AGH 我只勾选了最快的IP地址 却还是返回多个IP地址

![Screenshot_2020-06-30-08-58-11-583_com android chrome](https://user-images.githubusercontent.com/28734349/86070695-de4f3f00-baaf-11ea-8dc9-ea641908f932.jpg)
是第三个？？

**Comment by Potterli20** [comment]
> > 如果没有响应规则，就是空白，没有加黑名单，这个是我图![Screenshot_2020-06-30-07-40-44-361_com android chrome](https://user-images.githubusercontent.com/28734349/86066810-c4106380-baa5-11ea-89a9-ace82c1dcdbb.jpg)
> 
> 我不知道 是不是就这些 time-ios.apple.com 类似带-的网址 属于个例
> 下面这个是我在AGH转发 SMARTDNS 查到的结果
> 07:38:00
> time-ios.apple.com
> 响应细节
> 域名
> time-ios.apple.com
> 状态
> 已处理
> DNS 服务器
> 127.0.0.1:6053 这个是 SMARTDNS
> 耗时
> 8 毫秒
> 响应代码
> NOERROR
> 响应
> CNAME: time-ios.g.aaplimg.com. (ttl=3249)
> A: 17.253.84.123 (ttl=0)

这些可能弄一下分流

**Comment by qpzr** [comment]
> > > > BUG：
> > > > 我已经勾选 最快的IP地址
> > > > 那么 nslookup time-ios.apple.com 就应该只返回一个最快的IP
> > > > 然而
> > > > time-ios.apple.com
> > > > A
> > > > CNAME: time-ios.g.aaplimg.com. (ttl=773)
> > > > A: 17.253.84.123 (ttl=220)
> > > > A: 17.253.68.253 (ttl=220)
> > > > A: 17.253.68.125 (ttl=220)
> > > > 在最新的beta版本中 查询日志-响应信息 里面没有响应规则
> > > > 如果出现错误的拦截，没有响应规则，排查起来会麻烦
> > > > 建议：响应信息里增加规则，跟旧版本的查询日志里一样，有个规则方便排查错误
> > > 
> > > 
> > > 你是局域网选择？还是广域网？
> > 
> > 
> > 我装在路由器上的运行的，是局域网。smartdns就可以 只返回一个IP。 然而AGH 我只勾选了最快的IP地址 却还是返回多个IP地址
> 
> ![Screenshot_2020-06-30-08-58-11-583_com android chrome](https://user-images.githubusercontent.com/28734349/86070695-de4f3f00-baaf-11ea-8dc9-ea641908f932.jpg)
> 是第三个？？

是的 第三个

**Comment by Potterli20** [comment]
> > > > > BUG：
> > > > > 我已经勾选 最快的IP地址
> > > > > 那么 nslookup time-ios.apple.com 就应该只返回一个最快的IP
> > > > > 然而
> > > > > time-ios.apple.com
> > > > > A
> > > > > CNAME: time-ios.g.aaplimg.com. (ttl=773)
> > > > > A: 17.253.84.123 (ttl=220)
> > > > > A: 17.253.68.253 (ttl=220)
> > > > > A: 17.253.68.125 (ttl=220)
> > > > > 在最新的beta版本中 查询日志-响应信息 里面没有响应规则
> > > > > 如果出现错误的拦截，没有响应规则，排查起来会麻烦
> > > > > 建议：响应信息里增加规则，跟旧版本的查询日志里一样，有个规则方便排查错误
> > > > 
> > > > 
> > > > 你是局域网选择？还是广域网？
> > > 
> > > 
> > > 我装在路由器上的运行的，是局域网。smartdns就可以 只返回一个IP。 然而AGH 我只勾选了最快的IP地址 却还是返回多个IP地址
> > 
> > 
> > ![Screenshot_2020-06-30-08-58-11-583_com android chrome](https://user-images.githubusercontent.com/28734349/86070695-de4f3f00-baaf-11ea-8dc9-ea641908f932.jpg)
> > 是第三个？？
> 
> 是的 第三个

一般来说都是DNS反馈有问题，有些DNS直接反馈空的

**Comment by Potterli20** [comment]
不是规则问题，而是DNS的问题，我也有遇到过问题，我也只能把DNS一个个看

**Comment by qpzr** [comment]
> 不是规则问题，而是DNS的问题，我也有遇到过问题，我也只能把DNS一个个看

我觉得你应该单用 SMATDNS 查一次 time-ios.apple.com
在用AGH 在查一次 time-ios.apple.com
对比一下就很明显了
同样都是填了一堆上游DNS
SMARTDNS 就是返回一个IP
AGH 还是返回好几个IP
是不是AGH去SMARTDNS那里搬砖优选最快的IP技术没到家

**Comment by qpzr** [comment]
要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游

**Comment by Potterli20** [comment]
> 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游

你会发现最快的IP是最慢的IP，其实有多个IP就更好不过

**Comment by qpzr** [comment]
> > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> 
> 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处



> > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> 
> 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处

这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了

**Comment by Potterli20** [comment]
> > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > 
> > 
> > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> 
> > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > 
> > 
> > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> 
> 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了

国内的网络环境你又不知道😂😂

**Comment by qpzr** [comment]
> > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > 
> > > 
> > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > 
> > 
> > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > 
> > > 
> > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > 
> > 
> > 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了
> 
> 国内的网络环境你又不知道😂😂

怕你是没用远古时期的 右键 连接到敲国外IP就能直接出去看YOUTUBE吧  什么买国外VPS 影梭 加密SSR弱爆了

好了 尬问尬答那么久  到底 这个1.BUG会不会修复 2.这个 在响应细节里 增加回 响应规则的建议 会不会采纳

如果没戏  我就关问题 自娱自乐继续东拼西凑自己玩了

**Comment by Potterli20** [comment]
> > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > 
> > > > 
> > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > 
> > > 
> > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > 
> > > > 
> > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > 
> > > 
> > > 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了
> > 
> > 
> > 国内的网络环境你又不知道joyjoy
> 
> 怕你是没用远古时期的 右键 连接到敲国外IP就能直接出去看YOUTUBE吧 什么买国外VPS 影梭 加密SSR弱爆了
> 
> 好了 尬问尬答那么久 到底 这个1.BUG会不会修复 2.这个 在响应细节里 增加回 响应规则的建议 会不会采纳
> 
> 如果没戏 我就关问题 自娱自乐继续东拼西凑自己玩了

哈哈哈哈，这个bug是有的，我也测试了最快IP是个bug，我不用他们的什么ss之类的，我是用trojan的

**Comment by qpzr** [comment]
> > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > 
> > > > > 
> > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > 
> > > > 
> > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > 
> > > > > 
> > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > 
> > > > 
> > > > 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了
> > > 
> > > 
> > > 国内的网络环境你又不知道joyjoy
> > 
> > 
> > 怕你是没用远古时期的 右键 连接到敲国外IP就能直接出去看YOUTUBE吧 什么买国外VPS 影梭 加密SSR弱爆了
> > 好了 尬问尬答那么久 到底 这个1.BUG会不会修复 2.这个 在响应细节里 增加回 响应规则的建议 会不会采纳
> > 如果没戏 我就关问题 自娱自乐继续东拼西凑自己玩了
> 
> 哈哈哈哈，这个bug是有的，我也测试了最快IP是个bug，我不用他们的什么ss之类的，我是用trojan的

那意思就是 丢着问题 等他们解决？  我就不关问题咯？

**Comment by CooreyCN** [comment]
> > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > 
> > > > > 
> > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > 
> > > > 
> > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > 
> > > > > 
> > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > 
> > > > 
> > > > 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了
> > > 
> > > 
> > > 国内的网络环境你又不知道joyjoy
> > 
> > 
> > 怕你是没用远古时期的 右键 连接到敲国外IP就能直接出去看YOUTUBE吧 什么买国外VPS 影梭 加密SSR弱爆了
> > 好了 尬问尬答那么久 到底 这个1.BUG会不会修复 2.这个 在响应细节里 增加回 响应规则的建议 会不会采纳
> > 如果没戏 我就关问题 自娱自乐继续东拼西凑自己玩了
> 
> 哈哈哈哈，这个bug是有的，我也测试了最快IP是个bug，没有反馈一个IP，，我不用他们的什么ss之类的，我是用trojan的

宁就是adguard国区负责人吗

**Comment by Potterli20** [comment]
> > > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > > 
> > > > > > 
> > > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > > 
> > > > > 
> > > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > > 
> > > > > > 
> > > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > > 
> > > > > 
> > > > > 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了
> > > > 
> > > > 
> > > > 国内的网络环境你又不知道joyjoy
> > > 
> > > 
> > > 怕你是没用远古时期的 右键 连接到敲国外IP就能直接出去看YOUTUBE吧 什么买国外VPS 影梭 加密SSR弱爆了
> > > 好了 尬问尬答那么久 到底 这个1.BUG会不会修复 2.这个 在响应细节里 增加回 响应规则的建议 会不会采纳
> > > 如果没戏 我就关问题 自娱自乐继续东拼西凑自己玩了
> > 
> > 
> > 哈哈哈哈，这个bug是有的，我也测试了最快IP是个bug，没有反馈一个IP，，我不用他们的什么ss之类的，我是用trojan的
> 
> 宁就是adguard国区负责人吗
是就好

**Comment by qpzr** [comment]
> > > > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > > > 
> > > > > > > 
> > > > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > > > 
> > > > > > 
> > > > > > > > 要不是出现这个问题，我早就放弃SMARTDNS 单用AGH了。
> > > > > > > > 就是用了几天发现有情况，继续保留SMARTDNS给AGH当上游
> > > > > > > 
> > > > > > > 
> > > > > > > 你会发现最快的IP是最慢的IP，其实有多个IP就更好不过，有好处，没坏处
> > > > > > 
> > > > > > 
> > > > > > 这个我懂，但是我没有飞天遁地跑出去的需求。不需要备着那么多候选的IP ，给一个快一点的就行了
> > > > > 
> > > > > 
> > > > > 国内的网络环境你又不知道joyjoy
> > > > 
> > > > 
> > > > 怕你是没用远古时期的 右键 连接到敲国外IP就能直接出去看YOUTUBE吧 什么买国外VPS 影梭 加密SSR弱爆了
> > > > 好了 尬问尬答那么久 到底 这个1.BUG会不会修复 2.这个 在响应细节里 增加回 响应规则的建议 会不会采纳
> > > > 如果没戏 我就关问题 自娱自乐继续东拼西凑自己玩了
> > > 
> > > 
> > > 哈哈哈哈，这个bug是有的，我也测试了最快IP是个bug，没有反馈一个IP，，我不用他们的什么ss之类的，我是用trojan的
> > 
> > 
> > 宁就是adguard国区负责人吗
> > 是就好

如何看待EDGE 测试版本 手机浏览器 查询日志 直接死火？  哈哈哈
