### ISSUE TITLE
Failed to start AdGuard Home on OpenWRT

### ISSUE THREAD

**Issue by RiwiHow** [AdguardTeam/AdGuardHome#1846]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * MiWIFI Mini
* **Operating system and version:**
  * OpenWrt 19.07.3

### Expected Behavior
Start AdGuard Home

### Actual Behavior
Do not start

### Additional Information
```
root@OpenWrt:/opt/AdGuardHome# ./AdGuardHome
[error] Couldn't read config file /opt/AdGuardHome/AdGuardHome.yaml: open /opt/AdGuardHome/AdGuardHome.yaml: no such file or directory
[info] AdGuard Home, version v0.102.0, channel release, arch linux mipsle
[info] This is the first time AdGuard Home is launched
[info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
[error] Auth: bbolt.Open: invalid argument
[fatal] Couldn't initialize Auth module
```

**Comment by szolin** [comment]
You won't be able to start AGH using the default file system.
Please read this:
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#limitations

**Comment by RiwiHow** [comment]
> You won't be able to start AGH using the default file system.
> Please read this:
> https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#limitations

Thanks! AGH is working now.

**Comment by Freebase394** [comment]
I Need to Now what you dit to make it working.

What commands you have inserted and typed.
I'm try to run 2 instances of Adguard on same COmputer | IP and the second instance onside Docker Container is giving me this  same error.

2023/07/01 01:00:32.386436 9989#1 [info] AdGuard Home, version v0.107.32
2023/07/01 01:00:32.387529 9989#1 [debug] current working directory is /home/rodas/AdGuardHome
2023/07/01 01:00:32.388721 9989#1 [debug] reading config file: /home/rodas/AdGuardHome/AdGuardHome.yaml
2023/07/01 01:00:32.405762 9989#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 20
2023/07/01 01:00:32.406762 9989#1 [debug] reading config file: /home/rodas/AdGuardHome/AdGuardHome.yaml
2023/07/01 01:00:32.431317 9989#1 [info] tls: using default ciphers
2023/07/01 01:00:32.435689 9989#1 [debug] hosts container: starting
2023/07/01 01:00:32.436633 9989#1 [debug] hosts container: refreshing
2023/07/01 01:00:32.437357 9989#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"
2023/07/01 01:00:32.437821 9989#1 [debug] hosts container: added ip-host pair "::1"-"localhost"
2023/07/01 01:00:32.438247 9989#1 [debug] hosts container: added ip-host pair "::1"-"ip6-localhost"
2023/07/01 01:00:32.438695 9989#1 [debug] hosts container: added ip-host pair "::1"-"ip6-loopback"
2023/07/01 01:00:32.439113 9989#1 [debug] hosts container: added ip-host pair "ff02::1"-"ip6-allnodes"
2023/07/01 01:00:32.439549 9989#1 [debug] hosts container: added ip-host pair "ff02::2"-"ip6-allrouters"
2023/07/01 01:00:32.439969 9989#1 [debug] hosts container: added ip-host pair "127.0.1.1"-"adguardserver"
2023/07/01 01:00:32.441308 9989#1 [debug] hosts container: sending upd
2023/07/01 01:00:32.448060 9989#1 [debug] filtering: initialized 64 services
2023/07/01 01:00:32.463949 9989#1 [info] safesearch default: reset 253 rules
2023/07/01 01:00:32.473702 9989#1 [debug] dhcpd: warning: creating dhcpv4 srv: dhcpv4: invalid IP is not an IPv4 address
2023/07/01 01:00:32.476331 9989#1 [debug] clients: removed 0 client aliases
2023/07/01 01:00:32.476621 9989#1 [debug] clients: added 0 client aliases from dhcp
2023/07/01 01:00:32.477184 9989#25 [debug] clients: removed 0 client aliases
2023/07/01 01:00:32.477229 9989#1 [debug] writing config file "/home/rodas/AdGuardHome/AdGuardHome.yaml"
2023/07/01 01:00:32.477598 9989#25 [debug] clients: added ff02::2 -> "ip6-allrouters" [1]
2023/07/01 01:00:32.477786 9989#25 [debug] clients: added 127.0.1.1 -> "adguardserver" [2]
2023/07/01 01:00:32.477974 9989#25 [debug] clients: added 127.0.0.1 -> "localhost" [3]
2023/07/01 01:00:32.478154 9989#25 [debug] clients: added ::1 -> "localhost" [4]
2023/07/01 01:00:32.478331 9989#25 [debug] clients: added ff02::1 -> "ip6-allnodes" [5]
2023/07/01 01:00:32.478603 9989#25 [debug] clients: added 5 client aliases from system hosts file
2023/07/01 01:00:32.507368 9989#1 [info] Initializing auth module: /home/rodas/AdGuardHome/data/sessions.db
2023/07/01 01:00:32.507717 9989#1 **_[error] auth: open DB: /home/rodas/AdGuardHome/data/sessions.db:_** open /home/rodas/AdGuardHome/da                              ta/sessions.db: permission denied
2023/07/01 01:00:32.507938 9989#1 [fatal] initializing auth module failed

**Comment by RiwiHow** [comment]
> I Need to Now what you dit to make it working.
> 
> What commands you have inserted and typed. I'm try to run 2 instances of Adguard on same COmputer | IP and the second instance onside Docker Container is giving me this same error.
> 
> 2023/07/01 01:00:32.386436 9989#1 [info] AdGuard Home, version v0.107.32 2023/07/01 01:00:32.387529 9989#1 [debug] current working directory is /home/rodas/AdGuardHome 2023/07/01 01:00:32.388721 9989#1 [debug] reading config file: /home/rodas/AdGuardHome/AdGuardHome.yaml 2023/07/01 01:00:32.405762 9989#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 20 2023/07/01 01:00:32.406762 9989#1 [debug] reading config file: /home/rodas/AdGuardHome/AdGuardHome.yaml 2023/07/01 01:00:32.431317 9989#1 [info] tls: using default ciphers 2023/07/01 01:00:32.435689 9989#1 [debug] hosts container: starting 2023/07/01 01:00:32.436633 9989#1 [debug] hosts container: refreshing 2023/07/01 01:00:32.437357 9989#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost" 2023/07/01 01:00:32.437821 9989#1 [debug] hosts container: added ip-host pair "::1"-"localhost" 2023/07/01 01:00:32.438247 9989#1 [debug] hosts container: added ip-host pair "::1"-"ip6-localhost" 2023/07/01 01:00:32.438695 9989#1 [debug] hosts container: added ip-host pair "::1"-"ip6-loopback" 2023/07/01 01:00:32.439113 9989#1 [debug] hosts container: added ip-host pair "ff02::1"-"ip6-allnodes" 2023/07/01 01:00:32.439549 9989#1 [debug] hosts container: added ip-host pair "ff02::2"-"ip6-allrouters" 2023/07/01 01:00:32.439969 9989#1 [debug] hosts container: added ip-host pair "127.0.1.1"-"adguardserver" 2023/07/01 01:00:32.441308 9989#1 [debug] hosts container: sending upd 2023/07/01 01:00:32.448060 9989#1 [debug] filtering: initialized 64 services 2023/07/01 01:00:32.463949 9989#1 [info] safesearch default: reset 253 rules 2023/07/01 01:00:32.473702 9989#1 [debug] dhcpd: warning: creating dhcpv4 srv: dhcpv4: invalid IP is not an IPv4 address 2023/07/01 01:00:32.476331 9989#1 [debug] clients: removed 0 client aliases 2023/07/01 01:00:32.476621 9989#1 [debug] clients: added 0 client aliases from dhcp 2023/07/01 01:00:32.477184 9989#25 [debug] clients: removed 0 client aliases 2023/07/01 01:00:32.477229 9989#1 [debug] writing config file "/home/rodas/AdGuardHome/AdGuardHome.yaml" 2023/07/01 01:00:32.477598 9989#25 [debug] clients: added ff02::2 -> "ip6-allrouters" [1] 2023/07/01 01:00:32.477786 9989#25 [debug] clients: added 127.0.1.1 -> "adguardserver" [2] 2023/07/01 01:00:32.477974 9989#25 [debug] clients: added 127.0.0.1 -> "localhost" [3] 2023/07/01 01:00:32.478154 9989#25 [debug] clients: added ::1 -> "localhost" [4] 2023/07/01 01:00:32.478331 9989#25 [debug] clients: added ff02::1 -> "ip6-allnodes" [5] 2023/07/01 01:00:32.478603 9989#25 [debug] clients: added 5 client aliases from system hosts file 2023/07/01 01:00:32.507368 9989#1 [info] Initializing auth module: /home/rodas/AdGuardHome/data/sessions.db 2023/07/01 01:00:32.507717 9989#1 **_[error] auth: open DB: /home/rodas/AdGuardHome/data/sessions.db:_** open /home/rodas/AdGuardHome/da ta/sessions.db: permission denied 2023/07/01 01:00:32.507938 9989#1 [fatal] initializing auth module failed

Sorry, this router is in my hometown and I won't be back there until February next year. I don't remember what I input at that time. 🥲
