### ISSUE TITLE
Query log: Offer ability to jump to specific page

### ISSUE THREAD

**Issue by twcau** [AdguardTeam/AdGuardHome#1851]
### Problem Description
At present, Query log shows paginated data from querylog.json.

However, it is only possible to move between pages using either the previous or next buttons. The user cannot choose to jump to a specific page.

This is inconsistent with other parts of the Management Interface, for example Settings > Client Settings.

Further, as the user moves to a specific page, the URL does not update with the page number. This means that there is no way for the browser back/forward buttons to work (an accessibility and usability issue), and there is no way to jump straight to or return to a specifc page in the results.

### Proposed Solution
a) to both the top and bottom of Query Log, add a drop-down/selector for the user to choose the specific page number they'd like to jump to.
b) as the user moves between pages, update the URL to add and display a property for the specific page of the logs being viewed.

### Alternatives Considered
No plausible alternatives identified.

### Additional Information
N/A

**Comment by mHatsune** [comment]
See discussion on https://github.com/AdguardTeam/AdGuardHome/issues/1095
