### ISSUE TITLE
[Question|Feature Request] Update filters(blacklist) from terminal

### ISSUE THREAD

**Issue by DmitryZemlyuk** [AdguardTeam/AdGuardHome#1858]
### Problem Description
Hi. Can I receive updates for filters(blacklist) from terminal without usage web-interface? I want to add check update filters to cron with usage custom time for request updates.

### Additional Information
AdGuard Home launched on Ubuntu 18.04

**Comment by ameshkov** [comment]
Well, you can use curl and use the API to trigger filters updates:
https://github.com/AdguardTeam/AdGuardHome/blob/master/openapi/openapi.yaml

Look for `/control/filtering/refresh` method there.
You can use basic HTTP auth (i.e. add the Authorization header to the request).
