### ISSUE TITLE
Quad9 and ColudFlare DoT broken

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#1859]
### Issue Details

* **Version of AdGuard Home server:**
v0.102.0
* **How did you setup DNS configuration:**
DHCP Lease directs  DNS traffic to AdGuard Home
* **If it's a router or IoT, please write device model:**
Raspberry Pi 3 Model B running Home Assistant 0.112.1
* **Operating system and version:**
HASSIO Supervisor 228, Docker version 19.03.8

### Expected Behavior
I expect Quad9 (tls://9.9.9.9) and CloudFair (tls://1.1.1.1) over TLS to work correctly

### Actual Behavior
When testing upstream DNS from the config page with the following entries errors are reported (see images)
```
tls://8.8.8.8
tls://8.8.4.4
tls://9.9.9.9
tls://1.1.1.1
```
### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/59442445/86470216-e0750000-bd32-11ea-80e9-1911388ff5c6.png)

</details>

### Additional Information
There are no problems reported with the DoT services on the Quad9 and CloudFlare service status pages. Both Google DoT addresses respond without any issues/problems.

**Comment by ameshkov** [comment]
Cannot reproduce this issue on my side.

Try using https://github.com/ameshkov/dnslookup and check that these servers are accessible from the device where you host AGH

**Comment by tescophil** [comment]
Cannot see a way to do this as the Raspberry Pi is the target, which there is no binary for, and HASSIO is _very_locked down, so cannot build from source either. Any other way to check this ?

**Comment by ameshkov** [comment]
Well, it seems that for some reason you simply cannot connect to these addresses, maybe some networking issue

**Comment by tescophil** [comment]
I can use 9.9.9.9:53 and 1.1.1.1:53, just not over TLS on 853.., could this be a certificate issue ?

**Comment by ameshkov** [comment]
I doubt it, according to the error message, it seems that it simply cannot establish the connection.

Btw, it may be that your ISP blocks port 853. If so, it'd be interesting to know what ISP is that.

**Comment by tescophil** [comment]
That cannot be it, because 8.8.8.8:853 and 8.8.4.4:853 work perfectly (see the top of the trace..)

**Comment by ameshkov** [comment]
Hm, yeah, that's weird indeed.

Just in case, try using telnet: `telnet 1.1.1.1 853`

**Comment by tescophil** [comment]
No Problem...
```
phil@Desktop-PC:~/Downloads/linux-amd64$ telnet 1.1.1.1 853
Trying 1.1.1.1...
Connected to 1.1.1.1.
Escape character is '^]'.
close
Connection closed by foreign host.

phil@Desktop-PC:~/Downloads/linux-amd64$ telnet 9.9.9.9 853
Trying 9.9.9.9...
Connected to 9.9.9.9.
Escape character is '^]'.
close
Connection closed by foreign host.
phil@Desktop-PC:~/Downloads/linux-amd64$ 
```
Looks OK ?

**Comment by ameshkov** [comment]
Yeah, it does, I wonder what's wrong with the TLS handshake then.

It seems that the issue is somehow caused by the TLS handshake. Try collecting tcpdump: `sudo tcpdump host 1.1.1.1 -w capture.pcap`

**Comment by tescophil** [comment]
OK, ran that command in one terminal and tried a few lookups to 1.1.1.1:853 in another. Capture attached.

[capture.pcap.gz](https://github.com/AdguardTeam/AdGuardHome/files/4870256/capture.pcap.gz)

plus the capture is a slightly more 'friendly' format:

<pre><font color="#34E2E2"><b>Starting tcpick 0.2.1 at 2020-07-03 15:48 BST</b></font>
<font color="#AD7FA8"><b>Timeout for connections is 600</b></font>
<font color="#8AE234"><b>tcpick: reading from capture.pcap</b></font>
<font color="#AD7FA8"><b>1      </b></font><font color="#FCE94F"><b>SYN-SENT      </b></font><font color="#8AE234"><b> 192.168.10.197:58490 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>1      </b></font><font color="#FCE94F"><b>SYN-RECEIVED  </b></font><font color="#8AE234"><b> 192.168.10.197:58490 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>1      </b></font><font color="#8AE234"><b>ESTABLISHED    192.168.10.197:58490 &gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#CC0000">...........</font>#<font color="#CC0000">...</font>i<font color="#CC0000">.</font>f<font color="#CC0000">...</font>54<font color="#CC0000">..</font>&amp;<font color="#CC0000">.</font>p<font color="#CC0000">.</font>W,<font color="#CC0000">....</font>%YXn.<font color="#CC0000">...</font> <font color="#CC0000">...</font>sO=<font color="#CC0000">...</font>(<font color="#CC0000">.</font>%<font color="#CC0000">......</font>p<font color="#CC0000">..</font>&quot;k<font color="#CC0000">..</font>3<font color="#CC0000">.</font>Y<font color="#CC0000">.</font>B<font color="#CC0000">...</font>&amp;<font color="#CC0000">.....</font>/<font color="#CC0000">.</font>0<font color="#CC0000">.</font>+<font color="#CC0000">.</font>,<font color="#CC0000">...</font>	<font color="#CC0000">...</font>
<font color="#CC0000">.....</font>/<font color="#CC0000">.</font>5<font color="#CC0000">...</font>
<font color="#CC0000">.........</font>w<font color="#CC0000">..........</font>
<font color="#CC0000">.</font>
<font color="#CC0000">......................................</font>+<font color="#CC0000">........</font>3<font color="#CC0000">.</font>&amp;<font color="#CC0000">.</font>$<font color="#CC0000">...</font> m|<font color="#CC0000">..</font>h.<font color="#CC0000">..</font>v<font color="#CC0000">...</font>R<font color="#CC0000">.</font>vXCF<font color="#CC0000">.</font>g<font color="#CC0000">...</font>N<font color="#CC0000">.</font>N<font color="#CC0000">.....</font>j
U<font color="#CC0000">..</font>xLM<font color="#CC0000">.</font>_G<font color="#CC0000">.</font>jLB<font color="#CC0000">.</font>F<font color="#CC0000">..</font>O<font color="#CC0000">.</font>B<font color="#CC0000">.</font>R&gt;<font color="#CC0000">....</font>j<font color="#CC0000">.</font>fv<font color="#CC0000">.</font>&gt;<font color="#CC0000">..</font>k+Qwx<font color="#CC0000">.</font>c<font color="#CC0000">.</font>\<font color="#CC0000">.....</font>k#Z<font color="#CC0000">.</font>S<font color="#CC0000">.</font>g+<font color="#CC0000">..</font>H<font color="#CC0000">....</font>)<font color="#CC0000">.</font>^<font color="#CC0000">.</font>g<font color="#CC0000">......</font>$<font color="#CC0000">..</font>
C<font color="#CC0000">.</font>}<font color="#CC0000">.</font>av<font color="#CC0000">......</font>M<font color="#CC0000">.</font>X/<font color="#CC0000">.</font>zM<font color="#CC0000">.</font>f<font color="#CC0000">.</font>p&quot;<font color="#CC0000">......</font>O|d<font color="#CC0000">..</font>X<font color="#CC0000">.</font>,<font color="#CC0000">..</font>.<font color="#CC0000">.</font>?<font color="#CC0000">.</font>9<font color="#CC0000">..........</font>&amp;<font color="#CC0000">.</font>&quot;<font color="#CC0000">..</font>@TU<font color="#CC0000">....</font>a<font color="#CC0000">.</font>;<font color="#CC0000">.......</font>_<font color="#CC0000">.......</font>&amp;B<font color="#CC0000">.</font>&quot;/J =<font color="#CC0000">....</font>&quot;<font color="#CC0000">.</font>[<font color="#CC0000">..</font>2d<font color="#CC0000">..</font>K<font color="#CC0000">....</font>+<font color="#CC0000">.</font>a<font color="#CC0000">..</font>dRAC<font color="#CC0000">.....</font>:<font color="#CC0000">.....</font>]hcgP<font color="#CC0000">..</font>{&lt;r<font color="#CC0000">...</font>JT<font color="#CC0000">.</font>J<font color="#CC0000">.</font>5<font color="#CC0000">...</font>x<font color="#CC0000">....</font>W<font color="#CC0000">..</font>Q<font color="#CC0000">.</font>u<font color="#CC0000">.......</font>E<font color="#CC0000">....</font>4<font color="#CC0000">.</font>`<font color="#CC0000">....</font>/<font color="#CC0000">.</font>8<font color="#CC0000">..................</font>b<font color="#CC0000">.</font>FR<font color="#CC0000">.</font>!u]<font color="#CC0000">..</font>&apos;s0<font color="#CC0000">.</font>^<font color="#CC0000">..</font>*<font color="#CC0000">.</font>A<font color="#CC0000">...</font>L<font color="#CC0000">.</font>SP<font color="#CC0000">...</font>.:<font color="#CC0000">.</font>w<font color="#CC0000">.....</font>x8<font color="#CC0000">...</font>I<font color="#CC0000">..</font>:U<font color="#CC0000">.</font>2<font color="#CC0000">.....</font>W<font color="#CC0000">.</font>}<font color="#CC0000">.</font>F<font color="#CC0000">.</font>C<font color="#CC0000">.</font>&apos;<font color="#CC0000">.</font>a*q<font color="#CC0000">.</font>%Q<font color="#CC0000">..</font>namO)
<font color="#CC0000">.</font>xllZm`<font color="#CC0000">.</font>E<font color="#CC0000">...</font>BE<font color="#CC0000">.</font>q<font color="#CC0000">...</font>,<font color="#CC0000">.........</font>2<font color="#CC0000">.</font>G<font color="#CC0000">.</font>Ee<font color="#CC0000">......</font>f*<font color="#CC0000">.</font>y<font color="#CC0000">....</font>`<font color="#CC0000">.</font>k<font color="#CC0000">......</font>!<font color="#CC0000">....</font>j<font color="#CC0000">...</font>P<font color="#CC0000">.</font>i<font color="#CC0000">.</font>rb<font color="#CC0000">.</font>_?<font color="#CC0000">..</font>l<font color="#CC0000">.</font>\7jN<font color="#CC0000">.......</font>&apos;<font color="#CC0000">..</font>A<font color="#CC0000">.....</font>9/`GZ<font color="#CC0000">....</font><font color="#CC0000">\.</font>R<font color="#CC0000">....</font>:<font color="#CC0000">....</font>($<font color="#CC0000">....</font>AZW<font color="#CC0000">......</font>U<font color="#CC0000">.</font>2<font color="#CC0000">.</font>Z1D<font color="#CC0000">.</font>?<font color="#CC0000">.</font>%J=<font color="#CC0000">..</font>Q	<font color="#CC0000">..</font>&amp;~M/<font color="#CC0000">.</font>@U+<font color="#CC0000">...</font>:<font color="#CC0000">.</font>$<font color="#CC0000">..</font>d5<font color="#CC0000">.</font>q8<font color="#CC0000">.....</font>L#<font color="#CC0000">.</font>?M<font color="#CC0000">.</font>%ss<font color="#CC0000">...</font>8zk<font color="#CC0000">..</font>	<font color="#CC0000">..</font>W,<font color="#CC0000">...</font>C.<font color="#CC0000">..</font>I<font color="#CC0000">....</font>rS]<font color="#CC0000">...</font>)<font color="#CC0000">.</font>\<font color="#CC0000">.</font>&apos;<font color="#CC0000">....</font>{<font color="#CC0000">..</font>x<font color="#CC0000">......</font>4<font color="#CC0000">.</font>?<font color="#CC0000">.</font>hjo<font color="#CC0000">...</font>p<font color="#CC0000">...</font>Q<font color="#CC0000">.</font>?<font color="#CC0000">..</font>e<font color="#CC0000">...</font>0<font color="#CC0000">.</font>pS<font color="#CC0000">.</font>&lt;<font color="#CC0000">......</font>J<font color="#CC0000">....</font>4<font color="#CC0000">.</font>d?<font color="#CC0000">.</font>{<font color="#CC0000">..</font>en+c<font color="#CC0000">..</font>dk<font color="#CC0000">.</font>S8.)<font color="#CC0000">.....</font>I<font color="#CC0000">..</font>u<font color="#CC0000">.......</font>r<font color="#CC0000">....</font>]<font color="#CC0000">...</font>`<font color="#CC0000">...</font>M<font color="#CC0000">.</font>S7<font color="#CC0000">..</font>M<font color="#CC0000">.....</font>e[^<font color="#CC0000">..</font>X<font color="#CC0000">.</font>V<font color="#CC0000">.</font>
L<font color="#CC0000">..</font>\<font color="#CC0000">..</font>9<font color="#CC0000">.....</font>4V<font color="#CC0000">...</font>%<font color="#CC0000">.</font>p<font color="#CC0000">....</font>bq<font color="#CC0000">.</font>u<font color="#CC0000">.</font>4]<font color="#CC0000">.....</font>i=<font color="#CC0000">.</font>H*o<font color="#CC0000">.....</font>M@$/<font color="#CC0000">..</font>7<font color="#CC0000">.</font>s<font color="#CC0000">.</font>%<font color="#CC0000">....</font>h&apos;<font color="#CC0000">.</font>}4<font color="#CC0000">.</font>Hj<font color="#CC0000">.</font>VkcW<font color="#CC0000">..</font>-<font color="#CC0000">...</font>`#%#T<font color="#CC0000">...</font>!k_<font color="#CC0000">..</font>ht=&amp;fA<font color="#CC0000">..</font>la<font color="#CC0000">.</font>Z<font color="#CC0000">.</font>YC+<font color="#CC0000">..</font>	<font color="#CC0000">...</font>V<font color="#CC0000">..</font>?<font color="#CC0000">.</font>b<font color="#CC0000">.....</font>j<font color="#CC0000">..</font>{<font color="#CC0000">....</font>M<font color="#CC0000">......</font>=<font color="#CC0000">.</font>Moa<font color="#CC0000">.</font>kQ`<font color="#CC0000">...</font>
<font color="#AD7FA8"><b>1      </b></font><font color="#FCE94F"><b>FIN-WAIT-1    </b></font><font color="#8AE234"><b> 192.168.10.197:58490 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>1      </b></font><font color="#FCE94F"><b>TIME-WAIT     </b></font><font color="#8AE234"><b> 192.168.10.197:58490 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>1      </b></font><font color="#EF2929"><b>RESET         </b></font><font color="#8AE234"><b> 192.168.10.197:58490 </b></font><font color="#EF2929"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>2      </b></font><font color="#FCE94F"><b>SYN-SENT      </b></font><font color="#8AE234"><b> 192.168.10.197:58508 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>2      </b></font><font color="#FCE94F"><b>SYN-RECEIVED  </b></font><font color="#8AE234"><b> 192.168.10.197:58508 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>2      </b></font><font color="#8AE234"><b>ESTABLISHED    192.168.10.197:58508 &gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#CC0000">....</font>{<font color="#CC0000">.</font>`<font color="#CC0000">..</font>&amp;<font color="#CC0000">.....</font>/<font color="#CC0000">.</font>0<font color="#CC0000">.</font>+<font color="#CC0000">.</font>,<font color="#CC0000">...</font>Y<font color="#CC0000">.</font>&apos;<font color="#CC0000">..</font>i<font color="#CC0000">....</font>f<font color="#CC0000">.....</font>
<font color="#CC0000">.....</font>/<font color="#CC0000">.</font>5<font color="#CC0000">...</font>
<font color="#CC0000">.........</font>w<font color="#CC0000">..........</font>
<font color="#CC0000">.</font>
<font color="#CC0000">......................................</font>+<font color="#CC0000">........</font>3<font color="#CC0000">.</font>&amp;<font color="#CC0000">.</font>$<font color="#CC0000">...</font> <font color="#CC0000">..</font>a<font color="#CC0000">.</font>k<font color="#CC0000">....</font>B<font color="#CC0000">.</font> <font color="#CC0000">....</font>
<font color="#CC0000">..</font>Y<font color="#CC0000">......</font>U	<font color="#CC0000">.</font>oMl
1-<font color="#CC0000">....</font>&quot;ll<font color="#CC0000">.</font>1;<font color="#CC0000">....</font>s	<font color="#CC0000">.</font>x<font color="#CC0000">.</font>%<font color="#CC0000">....</font>%<font color="#CC0000">..</font>d<font color="#CC0000">..</font>r<font color="#CC0000">.</font>J<font color="#CC0000">....</font>&quot;B<font color="#CC0000">...</font>L0gb<font color="#CC0000">....</font>iC<font color="#CC0000">..</font>ng<font color="#CC0000">.......</font>C3D<font color="#CC0000">..</font>$<font color="#CC0000">.</font>Qw<font color="#CC0000">.</font>~A<font color="#CC0000">..</font>BK%<font color="#CC0000">.</font>+&amp;<font color="#CC0000">.....</font>c<font color="#CC0000">...</font> 9<font color="#CC0000">.</font>$~<font color="#CC0000">.............</font>J<font color="#CC0000">...</font>J&apos;<font color="#CC0000">.</font>j<font color="#CC0000">.</font>aO,<font color="#CC0000">...</font>2<font color="#CC0000">....</font>24D\<font color="#CC0000">.</font>6<font color="#CC0000">..</font>9C<font color="#CC0000">.....</font>h<font color="#CC0000">.</font>k<font color="#CC0000">..........</font>l<font color="#CC0000">.</font>k<font color="#CC0000">.</font>h<font color="#CC0000">..</font>_zaX<font color="#CC0000">..</font>&gt;r<font color="#CC0000">.</font>^<font color="#CC0000">...</font>=?<font color="#CC0000">..</font>m<font color="#CC0000">...</font>*w<font color="#CC0000">..</font>)&apos;X&lt;<font color="#CC0000">.......</font>ed<font color="#CC0000">.</font>5|<font color="#CC0000">.....</font>q<font color="#CC0000">.</font>Z-9<font color="#CC0000">.</font>Y<font color="#CC0000">.</font>h<font color="#CC0000">.</font>WP+<font color="#CC0000">......</font>S<font color="#CC0000">..</font>~<font color="#CC0000">..</font>c<font color="#CC0000">...</font>h<font color="#CC0000">.</font>p<font color="#CC0000">...</font>C!<font color="#CC0000">..</font>J<font color="#CC0000">.......</font>l<font color="#CC0000">.</font>y <font color="#CC0000">.</font>(<font color="#CC0000">..</font>&quot;ZL2C`<font color="#CC0000">....</font>M+<font color="#CC0000">.</font>P<font color="#CC0000">.</font>D<font color="#CC0000">..</font>(<font color="#CC0000">...</font>2<font color="#CC0000">.....</font>D<font color="#CC0000">..</font>8-J<font color="#CC0000">....</font> <font color="#CC0000">....</font>jaa<font color="#CC0000">..</font>J<font color="#CC0000">........</font>f<font color="#CC0000">.</font>3<font color="#CC0000">..</font>?<font color="#CC0000">.</font>fj<font color="#CC0000">.</font>%<font color="#CC0000">...</font>k<font color="#CC0000">.</font>@V<font color="#CC0000">.</font>&lt;&quot;4<font color="#CC0000">....</font>)<font color="#CC0000">.....</font>o<font color="#CC0000">...</font>%l<font color="#CC0000">.</font>I<font color="#CC0000">.....</font>~<font color="#CC0000">.</font>&quot;<font color="#CC0000">.</font>Y<font color="#CC0000">..</font>Kt
<font color="#CC0000">..</font>1q<font color="#CC0000">.</font>)<font color="#CC0000">.</font>&quot;YtZZ<font color="#CC0000">.</font>d<font color="#CC0000">.</font>b<font color="#CC0000">.</font>|<font color="#CC0000">.</font>x<font color="#CC0000">.</font>]<font color="#CC0000">.</font>%4Z<font color="#CC0000">..</font>_<font color="#CC0000">...</font>6k<font color="#CC0000">.</font>m<font color="#CC0000">.......</font>J<font color="#CC0000">......</font>,<font color="#CC0000">...</font>N<font color="#CC0000">.</font>_7<font color="#CC0000">.</font>0~0<font color="#CC0000">.</font>+_<font color="#CC0000">.</font>m<font color="#CC0000">..</font>-\<font color="#CC0000">...</font>B<font color="#CC0000">...</font>F<font color="#CC0000">.......</font>	<font color="#CC0000">.</font>sz<font color="#CC0000">..</font>F5<font color="#CC0000">..</font>JI<font color="#CC0000">......</font>
1Y<font color="#CC0000">.</font>\Q<font color="#CC0000">....</font>[*<font color="#CC0000">..</font>#L<font color="#CC0000">..</font>S&quot;}o<font color="#CC0000">.</font>Z<font color="#CC0000">...</font>B<font color="#CC0000">........</font>k<font color="#CC0000">..</font>3<font color="#CC0000">.....</font>3r<font color="#CC0000">..</font>-Tf(<font color="#CC0000">.</font>S<font color="#CC0000">...</font>g<font color="#CC0000">.....</font>Z<font color="#CC0000">..</font>,<font color="#CC0000">.</font>E<font color="#CC0000">...</font>)<font color="#CC0000">.</font>R<font color="#CC0000">.</font>2<font color="#CC0000">..</font>=}<font color="#CC0000">.....</font>F<font color="#CC0000">..</font>4<font color="#CC0000">....</font>*@h^&amp;]&amp;z<font color="#CC0000">..</font>22<font color="#CC0000">.</font>
{dl<font color="#CC0000">...</font>d<font color="#CC0000">.......</font> <font color="#CC0000">........</font>%<font color="#CC0000">..</font>	;<font color="#CC0000">...........</font>Z:<font color="#CC0000">.</font>a\<font color="#CC0000">.</font> &amp;<font color="#CC0000">.</font>T<font color="#CC0000">...</font>=`<font color="#CC0000">.</font>er<font color="#CC0000">.</font>+x<font color="#CC0000">...........</font>&quot;<font color="#CC0000">..</font>^<font color="#CC0000">.....</font>m<font color="#CC0000">...</font>)b<font color="#CC0000">..</font>a<font color="#CC0000">.</font>$<font color="#CC0000">....</font>h<font color="#CC0000">.</font>@<font color="#CC0000">........</font>u<font color="#CC0000">..</font>S<font color="#CC0000">.....</font>J<font color="#CC0000">..</font>Z<font color="#CC0000">...</font>.uKVj<font color="#CC0000">.....</font>L2<font color="#CC0000">.</font>9<font color="#CC0000">....</font>S$<font color="#CC0000">.....</font>b<font color="#CC0000">..</font>]<font color="#CC0000">...</font>Z<font color="#CC0000">.</font>&gt;<font color="#CC0000">..</font>&lt;=<font color="#CC0000">....</font>@=uJ<font color="#CC0000">...</font>~<font color="#CC0000">.</font>g<font color="#CC0000">.</font>~<font color="#CC0000">..</font>!u<font color="#CC0000">....</font>?<font color="#CC0000">..</font>%<font color="#CC0000">..</font>T5<font color="#CC0000">.</font>4<font color="#CC0000">......</font>@<font color="#CC0000">.</font>)<font color="#CC0000">.</font>&amp;<font color="#CC0000">.</font>Z<font color="#CC0000">.......</font>|<font color="#CC0000">.</font>Y<font color="#CC0000">..</font>UtJ<font color="#CC0000">......</font>g[<font color="#CC0000">..</font>%%<font color="#CC0000">...</font>U<font color="#CC0000">.........</font>&gt;<font color="#CC0000">...</font>}E<font color="#CC0000">..</font>XZ<font color="#CC0000">.....</font>4&amp;<font color="#CC0000">...</font>r<font color="#CC0000">.</font>
<font color="#CC0000">...</font>d<font color="#CC0000">.</font>0<font color="#CC0000">..</font>w<font color="#CC0000">...</font>S<font color="#CC0000">.</font>C<font color="#CC0000">...</font>6<font color="#CC0000">..</font>(*<font color="#CC0000">...</font>+<font color="#CC0000">...</font>|<font color="#CC0000">.</font>V<font color="#CC0000">..</font>pNH<font color="#CC0000">..</font>u<font color="#CC0000">..</font>?} r<font color="#CC0000">..</font>l<font color="#CC0000">...</font>}<font color="#CC0000">...</font>`<font color="#CC0000">.</font>a(<font color="#CC0000">.</font>V<font color="#CC0000">.</font>o<font color="#CC0000">.</font>5<font color="#CC0000">.</font>o<font color="#CC0000">....</font>]<font color="#CC0000">.</font>i<font color="#CC0000">.</font>Q2<font color="#CC0000">.....</font> <font color="#CC0000">....</font>e!<font color="#CC0000">.....</font>)Ls<font color="#CC0000">.</font>o<font color="#CC0000">..</font>mT<font color="#CC0000">.</font>
<font color="#AD7FA8"><b>2      </b></font><font color="#FCE94F"><b>FIN-WAIT-1    </b></font><font color="#8AE234"><b> 192.168.10.197:58508 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>2      </b></font><font color="#FCE94F"><b>TIME-WAIT     </b></font><font color="#8AE234"><b> 192.168.10.197:58508 </b></font><font color="#FCE94F"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>2      </b></font><font color="#EF2929"><b>RESET         </b></font><font color="#8AE234"><b> 192.168.10.197:58508 </b></font><font color="#EF2929"><b>&gt; </b></font><font color="#34E2E2"><b>1.1.1.1</b></font>:<font color="#729FCF"><b>domain-s</b></font>
<font color="#AD7FA8"><b>tcpick: done reading from capture.pcap</b></font>

<font color="#34E2E2"><b>20 packets captured</b></font>
<font color="#34E2E2"><b>2 tcp sessions detected</b></font>
phil@Desktop-PC:~/Downloads/linux-amd64</pre>

**Comment by ameshkov** [comment]
Here's what happens:

1. The client sends TLS ClientHello to the server.
2. It does not receive the full ServerHello (but it does receive the second part of it, though)

It seems as if something messes up the TLS connection.

![image](https://user-images.githubusercontent.com/5947035/86480691-2ba10a00-bd57-11ea-8f05-fd40e28e36dc.png)

Here's how it should look like (you can use wireshark to inspect it):

[capture2.pcap.zip](https://github.com/AdguardTeam/AdGuardHome/files/4870326/capture2.pcap.zip)

**Comment by tescophil** [comment]
Have no idea why this would be specific to 1.1.1.1 and 9.9.9.9 but work perfectly with 8.8.8.8. I have all traffic on port 853 bypassed on my gateway/UTM so I know that is not messing with anything...

**Comment by tescophil** [comment]
So, 24 hours after removing tls://1.1.1.1 from the DNS configuration, the system is still sending out requests to 1.1.1.1 on port 853. This must be a bug...?

![image](https://user-images.githubusercontent.com/59442445/86512636-b50a1800-bdfb-11ea-9650-21e5aa106ae8.png)

**Comment by tescophil** [comment]
The only way I found to fix the above was to remove AdGuard from Home Assistant, reboot and re-install...

**Comment by tescophil** [comment]
Started new ticket for this issue....
