### ISSUE TITLE
Upstream DNS servers from a previous install are being queried

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#1860]
### Issue Details

* **Version of AdGuard Home server:**
v0.102.0
* **How did you setup DNS configuration:**
Router hands out DHCP lease with AdGuard as the primary DNS Server
* **If it's a router or IoT, please write device model:**
 Raspberry Pi 3 Model B
* **Operating system and version:**
HassOS 4.10, Home Assistant 0.112.2

### Expected Behavior
I expect AdGuard to only use the DNS upstream servers I spefici in the config

### Actual Behavior
Bizarr one this..., I was having problems using tls://1.1.1.1 and tls://1.0.0.1 so deleted them from the upstream DNS servers list, so currently my settings look like this
```
[/mylocaldomain.duckdns.org/]192.168.10.1
[/168.192.in-addr.arpa/]192.168.10.1
https://cloudflare-dns.com/dns-query
```
However, the system is still sending out traffic on port 853 to both 1.1.1.1 and 1.0.0.1/
I have uninstalled AdGuard via the Home Assistant config, hard rebooted, re-installed, and still I see these outgoing requests. I even rebooted my gateway to make sure these were not 'old' sessions...
### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/59442445/86516406-37a0d080-be18-11ea-847b-3743f9acede0.png)

</details>

**Comment by tescophil** [comment]
Cleared after 24 hours... very weird...

**Comment by ameshkov** [comment]
Really weird indeed.

If you run into an issue like that one more time, it makes sense to enable "verbose" logging in AdGuard Home and check if there's anything suspicious in the logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
