### ISSUE TITLE
[Question] How to control the app after installation from snap?

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1864]
Hello,

please, explain where i can find the yaml file configuration after install of package from snap repo and how to control it (start|restart|stop). I can't find any instructions in the wiki section unfortunately🙄

Maybe need to add this information to the wiki too?🤨

Thank you.
Cheers!

**Comment by ameshkov** [comment]
Well, the commands are standard for any snap.

* `snap services` - to view active services
* `snap logs adguard-home` - to view the latest service logs
* `snap start/stop/restart adguard-home` - to control the service

**Comment by ammnt** [comment]
@ameshkov , perfect! Thanks a lot!🤝🏽
