### ISSUE TITLE
detailed ip addresses with Docker

### ISSUE THREAD

**Issue by mhertaya** [AdguardTeam/AdGuardHome#1865]
Hi,

Maybe it's a Docker's limitation, but I only have the Docker's PI as a client (172.17.0.1).

So I don't think it's possible to have separate rules for each client...

My config on synology docker :
version: '3.2'
services:
  adguard:
    image: adguard/adguardhome:latest
    restart: always
    network_mode: bridge
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 167:67/udp
      - 168:68/tcp
      - 168:68/udp
      - 180:80/tcp
      - 1443:443/tcp
      - 1853:853/tcp
      - 3000:3000/tcp
    environment:
      - TZ=Europe/Brussels
    volumes:
      - /volume1/docker/data/adguard/work:/opt/adguardhome/work
      - /volume1/docker/data/adguard/conf:/opt/adguardhome/conf

Thanks

**Comment by ameshkov** [comment]
I think it shouldn’t be like this, but anyway - try running it with host networking just in case - https://docs.docker.com/network/host/

i.e. add this argument:

—network host

**Comment by mhertaya** [comment]
> I think it shouldn’t be like this, but anyway - try running it with host networking just in case - https://docs.docker.com/network/host/
> 
> i.e. add this argument:
> 
> —network host

tested.

same issue

**Comment by ameshkov** [comment]
What about binary version of AdGuard Home? Does it have the same issue?

**Comment by mhertaya** [comment]
Hi,

I have installed on an RPI 3 and the clients are correctly identified.

I also tested on a VPS and I get the same problem as on the docker, all clients are identified by the same ip.

Now, I'm going to use the RPI, until I find a solution to docker/VPS

Michel

**Comment by hoefs** [comment]
I use the docker network as host and I can see all clients...
