### ISSUE TITLE
client identification with dns over https

### ISSUE THREAD

**Issue by creampie95** [AdguardTeam/AdGuardHome#1867]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

when using dns over https encryption, devices' ip are not distinguished. 

### Additional Information

nextdns has the feature to set a profile for each device with configuration id

**Comment by ameshkov** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/1383
