### ISSUE TITLE
rDNS IPv6 not working

### ISSUE THREAD

**Issue by HellStorm666** [AdguardTeam/AdGuardHome#1868]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * V0.102.0
* **How did you setup DNS configuration:**
  * Debian install
* **Operating system and version:**
  * Debian 10 x64

### Expected Behavior
rDNS resolve local IPv6 addresses to device names.
Just like 192.168.1.123 displays in the clients list as test.device.local I would expect that 2001:981:123::123 would be listed as test.device.local

### Actual Behavior
2001:981:123::123 is listed as 2001:981:123::123 XS4All Broadband pool

### Config
At the Upstream DNS servers I have:
[/1.168.192.in-addr.arpa/]192.168.1.254
[/1.2.3.0.1.8.9.0.1.0.0.2.ip6.arpa/]2001:981:123::254

**Comment by ameshkov** [comment]
Planned on v0.105 because there's a massive refactoring in progress, and we'd better finish it first.

**Comment by HellStorm666** [comment]
> 
> 
> Planned on v0.105 because there's a massive refactoring in progress, and we'd better finish it first.

Ok, thanks.
ETA for v0.105?

**Comment by ameshkov** [comment]
I'd say ~3 months

**Comment by gamedeviced** [comment]
Is this still a thing? Or am I just to stupid to form a correct dns upstream rule for IPv6 rDNS?

**Comment by ameshkov** [comment]
Yeah, it's still open

**Comment by EugeneOne1** [comment]
@HellStorm666, we've finally refactored the entire rDNS module along with enhancing functionality in #2704.  It seems that the issue was solved along the way.  Could you please check if it works on the latest edge snapshots?

**Comment by EugeneOne1** [comment]
We'll close this issue for now.  Please, feel free to reopen it if our solution won't work in your case.  :)

**Comment by jumpsmm7** [comment]
This issue is present inside the current "Edge" version. RDNS Lookups are not present for IPV6. WHOIS appears to be being used and it is listing the ISP's information for each IPV6 client. This is occuring when AdguardHome is being ran directly on the router.
