### ISSUE TITLE
IPv4 queries leaking to IPv6 DNS on Windows 10

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdGuardHome#1876]
After I set the AGH IP as primary DNS in IPv4 settings of my wireless adapter, all IPv4 queries are not reaching AGH IP, which was working perfectly for many weeks before today. Reddit is blocked by my ISP, and even though I have set AGH (with Cloudflare DoT as upstream) as primary DNS, I am not able to access it. When I checked the AGH logs, many DNS queries were missing, including the main www.reddit.com query.

And when I run ipconfig /all in command prompt, the DNS servers appear in the following order:

- Automatic IPv6 DNS (used from router, unconfigured in adapter settings in control panel)
- AGH IP (configured in adapter settings in control panel)
- Secondary IPv4 DNS (configured in adapter settings in control panel)

I did not know where the queries were going instead of AGH, but since I was not able to load Reddit, I figured they were using the router as DNS somehow. And since the only DNS server that is linked to my ISP is the IPv6 DNS, the queries must be using it.

So, how do I set AGH as exclusive DNS server, since my IPv4 queries leak to automatic IPv6 DNS? A temporary solution I figured out was to completely disable IPv6 for my wireless adapter in adapter settings in control panel.

**Comment by DandelionSprout** [comment]
My first thought, is that setting AGH as the DNS server for IPv6 as well, could be worth testing out.

It'll likely take some trial and error to find and set the correct IPv6 address in the Windows settings, however.

**Comment by DandelionSprout** [comment]
In the event that you do become able to connect to your AGH server over IPv6, and still can't access Reddit even then, https://raw.githubusercontent.com/bebasid/bebasid/master/releases/hosts seems to be your best bet.

**Comment by ameshkov** [comment]
> A temporary solution I figured out was to completely disable IPv6 for my wireless adapter in adapter settings in control panel.

This solution is not bad at all.

The other solution would be to add IPv6 address to the AGH server and configure your computer to use it as an IPv6 DNS server.

**Comment by BlitW0** [comment]
@ameshkov I don't understand your 2nd solution. Can you please tell me the steps for adding the IPv6 address to AGH?

**Comment by ameshkov** [comment]
@BlitW0 it depends on the device/server where you're running AGH and whether it has an IPv6 address or not it.

If it does, it's enough to configure AGH to listen to 0.0.0.0 (all net interfaces)

**Comment by BlitW0** [comment]
I am running it on Windows 10 primarily. So, it will work with IPv6 if I set AGH to listen on 0.0.0.0 during initial setup?

**Comment by szolin** [comment]
Yes, it should work by default

**Comment by BlitW0** [comment]
Thanks, it worked after I set the `bind_host` under `dns` to `0.0.0.0` in the configuration file and restarted the server.
