### ISSUE TITLE
Sorting various IP Address Columns in the UI (eg in dhcp static leases) does not sort correctly. They are treated as strings instead of numeric.

### ISSUE THREAD

**Issue by Tloram** [AdguardTeam/AdGuardHome#1877]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.102.0
* **Operating system and version:**
  * Ubuntu Server 20.04 LTS

### Expected Behavior
When clicking on the various IP Address column headers around the UI (eg in DHCP Settings > Static Leases) to sort, the rows should be sorted numerically.

### Actual Behavior
IP Address columns are not sorted numerically, but treated as strings, thus the order is jumbled up making larger lists of leases very hard to organise and manage.

</details>

**Comment by ArtemBaskal** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/1778
