### ISSUE TITLE
Time based blocking the sites

### ISSUE THREAD

**Issue by nikeshjauhari** [AdguardTeam/AdGuardHome#1880]
All,

can we have a feature where admin can block the sites based on time schedule for a given set of clients (IP address)
example: block youtube.com between 9:00 AM EST -- 4 PM EST for client X. Y and Z

thanks,
Nikesh

**Comment by mHatsune** [comment]
See https://github.com/AdguardTeam/AdGuardHome/issues/1203 https://github.com/AdguardTeam/AdGuardHome/issues/951

**Comment by ameshkov** [comment]
Dup
