### ISSUE TITLE
Some dns config miss

### ISSUE THREAD

**Issue by asterriya** [AdguardTeam/AdGuardHome#1881]
Downloaded beta v0.103.0-beta1. Try to use dns cache new feature but there is absent some of new dns options in WebUI

Like those:
    "cache_ttl_min_override": "Override minimum TTL",
    "cache_ttl_max_override": "Override maximum TTL",
    "enter_cache_size": "Enter cache size",
    "enter_cache_ttl_min_override": "Enter minimum TTL",
    "enter_cache_ttl_max_override": "Enter maximum TTL",
    "min_exceeds_max_value": "Minimum value exceeds maximum value",
    "value_not_larger_than": "Value can't be larger than {{maximum}}"

Also, they are absent into yaml config file

**Comment by ameshkov** [comment]
Everything's in the DNS settings:
![image](https://user-images.githubusercontent.com/5947035/87307127-bcc76c00-c521-11ea-970e-b30115d78b6b.png)

**Comment by asterriya** [comment]
Also disappeared parental control. As suggestion dont ask to paste custom or basic filter. Make installed basic filters within start. Like it was on stable version

**Comment by ameshkov** [comment]
Disappeared from where?

**Comment by asterriya** [comment]
> Everything's in the DNS settings:
> ![image](https://user-images.githubusercontent.com/5947035/87307127-bcc76c00-c521-11ea-970e-b30115d78b6b.png)

I saw this but it's not all config settings that mentioned here https://github.com/AdguardTeam/AdGuardHome/commit/2d5287fcf31dfa7b484da9d01cbdc9f18584f56a

**Comment by asterriya** [comment]
> Disappeared from where?

from admin panel

**Comment by ameshkov** [comment]
You're quoting translation strings, not settings.

> from admin panel

I don't understand where exactly.

**Comment by asterriya** [comment]
> I don't understand where exactly.

Please install official last stable release first. Then goes here http://31.184.208.53:3561/#settings and you will see at the end option to block sites like twitch, amazon, twitter etc. Part of parental control option.

> You're quoting translation strings, not settings.

What do you mean?

**Comment by ameshkov** [comment]
Filters -> Blocked services

> What do you mean?

I mean that [this](https://github.com/AdguardTeam/AdGuardHome/issues/1881#issue-655819527) is not a list of settings, this is a list of strings that are used in the interface.

**Comment by asterriya** [comment]
So there is no way move it to WebUI? It will be good enough and then why it's absent into yaml config? 

As suggestion dont ask to paste custom or basic filter. Make installed basic filters within start. Like it was on stable version

**Comment by ameshkov** [comment]
> So there is no way move it to WebUI? It will be good enough and then why it's absent into yaml config?

Do you realize that you're talking about localization strings?

> As suggestion dont ask to paste custom or basic filter.

What do you mean?

Make installed basic filters within start. Like it was on stable version

**Comment by asterriya** [comment]
[url=https://www.upload.ee/image/12004194/1234.png][img]https://www.upload.ee/thumb/12004194/1234.png[/img][/url]
Want to see like before on stable version. It's ok to see more pre-installed filters after first install but not that thing like in picture. I have a lot of lists and it's annoying always to see two choices. Why not install pre-configured lists at once? 

If there any chance to see option for adding custom lists in bulk?

**Comment by ameshkov** [comment]
In the previous versions, we always had three pre-installed filter list and that was all.
Now, in addition to that, there's an option to choose from a list of known blocklists.

With the current UI, we don't think that adding them to the pre-installed list would make any good. We may change this in the future after the redesign, but not right now.

**Comment by asterriya** [comment]
So dns cache will stay and moved to the stable release or it's just an experiment? Love this function. For now, it's working good with load-balancing feature of upstream dns

Is there any chance to see more options for dns cache feature at future?

**Comment by ameshkov** [comment]
DNS Cache was always present, the only change in this update is that DNS cache settings are now exposed to the UI.

> As suggestion: add option as live background prefetching from upstream dns and using it for cache.

There's already a feature request about that: #1259
