### ISSUE TITLE
Question: How to fix "running "packr": exec: "packr": executable file not found in $PATH"

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#1882]
![Xnip2020-07-13_21-06-04](https://user-images.githubusercontent.com/58100052/87307785-c74b2b00-c54c-11ea-9279-b31f37c83ae0.jpg)

**Comment by ameshkov** [comment]
Clone the master branch once again, it was fixed a few minutes ago

**Comment by hezhijie0327** [comment]
emmm...
I still seem to have this problem when running "CHANNEL=release make release".
![Xnip2020-07-14_08-01-18](https://user-images.githubusercontent.com/58100052/87365294-736e2f80-c5a8-11ea-95bb-0ca7b043763e.jpg)

**Comment by hezhijie0327** [comment]
Commits: da4a1ec
release: dependencies client
	@echo Starting release build: version $(VERSION), channel $(CHANNEL)
	CHANNEL=$(CHANNEL) $(GORELEASER_COMMAND)
	$(call write_version_file,$(VERSION))
	PATH=$(GOPATH)/bin:$(PATH) packr clean
 
--> After adding "PATH=$(GOPATH)/bin:$(PATH)", it works!!!
release: dependencies client
	@echo Starting release build: version $(VERSION), channel $(CHANNEL)
	PATH=$(GOPATH)/bin:$(PATH) CHANNEL=$(CHANNEL) $(GORELEASER_COMMAND)
	$(call write_version_file,$(VERSION))
	PATH=$(GOPATH)/bin:$(PATH) packr clean

![Xnip2020-07-14_12-39-10](https://user-images.githubusercontent.com/58100052/87384716-08841f00-c5cf-11ea-9d62-9a2c82bd034e.jpg)

**Comment by hezhijie0327** [comment]
Commits: da4a1ec
# Validate channel
ifneq ($(CHANNEL),relese) <--
ifneq ($(CHANNEL),beta)
ifneq ($(CHANNEL),edge)

"release" channel error.

**Comment by ameshkov** [comment]
@hezhijie0327 fixed it, thank you!
