### ISSUE TITLE
What to do if dns is useless？

### ISSUE THREAD

**Issue by po888375** [AdguardTeam/AdGuardHome#1883]
I have installed AdGuard Home, and opened port 53, set the dns to my vps address on the computer, but the number of dns queries on the web page has not increased. If you manually use the dig or nslookup command to query, the dns query will increase. How is this going? And I added rules, the rules did not take effect

**Comment by ameshkov** [comment]
What if you use nslookup without specifying DNS server in the command? In this case it uses the default system DNS and if you configured everything correctly, it will send the DNS query to AGH.
