### ISSUE TITLE
dns cache

### ISSUE THREAD

**Issue by po888375** [AdguardTeam/AdGuardHome#1885]
I built the AdGuard Home, but only when manually using dig or nslookup to analyze, the background dns query will increase, and the web page will not increase directly. What should I do? I have set the dns of windows10 as my server ip, and then I still have a doubt that dns will be cached, then if I have opened a webpage, the second time it will not query from my AdGuard Home, Returned directly locally, is this dns meaningless?

**Comment by szolin** [comment]
Could you please rephrase your questions?  I don't understand what's not working for you and what you are trying to achieve.

**Comment by po888375** [comment]
> Could you please rephrase your questions? I don't understand what's not working for you and what you are trying to achieve.

Hello, that is, I have set up dns, but normal browsing of the web will not trigger dns query, why? I can use dig or nslookup command to query

**Comment by szolin** [comment]
> normal browsing of the web will not trigger dns query

Browsers use system default DNS server.  You should set up AGHome as default DNS server on your system.

**Comment by po888375** [comment]
> Browsers use system default DNS server. You should set up AGHome as default DNS server on your system.

Hello, I have set dns as the preferred dns, but it is still useless
This is a screenshot of my settings, the preferred dns is my server ip address
[Screenshot](https://s1.ax1x.com/2020/07/15/Uwft4x.png)

**Comment by ameshkov** [comment]
Please show the output of `nslookup example.org`

**Comment by po888375** [comment]
> Please show the output of `nslookup example.org`

`C:\Users\admin>nslookup example.org
服务器:  My server ip.16clouds.com
Address:  My server ip

非权威应答:
名称:    example.org
Address:  93.184.216.34`

**Comment by ameshkov** [comment]
No idea then. Here's what may be useful to you:

1. You may be using some network filtering software that intercepts DNS and reroutes it somewhere else.
2. If you're using VPN or Proxy extension or software, your browser may ignore the DNS settings.
3. Firefox may be using Cloudflare DNS DOH by default and ignore your system DNS settings.

That's more or less it, I have no idea what else could it be.
