### ISSUE TITLE
Can’t view source device in query log when viewing from a mobile browser (beta channel)

### ISSUE THREAD

**Issue by seannymurrs** [AdguardTeam/AdGuardHome#1886]
When viewing the query log on my iPhone, the column with the name of the client is cut off. I’m unable to scroll horizontally. As a result, it’s impossible to see where the query originated when looking at the log on a mobile device. I’m running the latest beta version (v0.103.0).

**Comment by ameshkov** [comment]
It should be visible in the dialog window that shows when you tap on a log record

**Comment by seannymurrs** [comment]
That does indeed work for queries that were allowed. If it was blocked, however, the dialog window doesn’t seem to show the client. 

-- 
Sean Murray

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/e46db985e83b5637131d6aded0594a7b30cddf69
