### ISSUE TITLE
Show a link to the FAQ article about Ubuntu when port 53 is in use

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1889]
We need to help people find the proper instruction for setting up AdGuard Home on Ubuntu when port 53 is in use: https://uploads.adguard.com/up04_Ubuntu_18.04_0mk9l.png

Here's what we should do.

When ALL are true:
1. Error text contains "address already in use"
2. DNS server port set to 53
3. Autofix is not available

In this case we should:

1. Add an explanation as on this screenshot: https://uploads.adguard.com/up04_Ubuntu_18.04_49gjc.png
2. It should lead to https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse

```
Port 53 is often occupied by DNSStubListener or systemdns-resolved services. Please read <a href="link">this instruction</a> on how to resolve this.
```

**Comment by valaria247** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1892
