### ISSUE TITLE
Plugin stopping to block anything

### ISSUE THREAD

**Issue by ebloved** [AdguardTeam/AdGuardHome#1890]
Good day!

* **Version of AdGuard Home server:**
  AdGuard ver. v0.102.0 as a Hassio ver. 0.112.3 plugin 
* **How did you setup DNS configuration:**
  Via DHCP, with AdGuard as a primary DNS server
* **If it's a router or IoT, please write device model:**
  Mikrotik RB2011

### Expected Behavior
AdGuard blocking "unwanted" links

### Actual Behavior
AdGuard unsystemathically stops blocking all "unwanted" links from any lists. Even when I add "||google.com^" to custom filtering rules, it says "Not found in your filter lists" after check.
Only plugin eg entire AdGuard Home reinstallation solves this problem for another 10-12 hours.
There are no warnings or errors in log files, and meanwhile plugin is serving DNS requests normally (including DNS rewrites).

### Screenshots

<details><summary>Screenshot:</summary>
![adguard-dashboard](https://user-images.githubusercontent.com/35403960/87710483-7e92ac80-c7ae-11ea-8230-2601b96855c2.JPG)
</details>

### Additional Information

Reinstalled addon again. It worked perfectly about 2 days, but then it somehow turned itself off (when I've opened control panel, I saw red "OFF" label near AdGuard logo on the top of the page). When I turned it on again it still don't want to block any addresses and even custom filtering rules said, that nothing found in any lists.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by ebloved** [comment]
Thanks for your reply!
Here are some logs:
[self_disable.log](https://github.com/AdguardTeam/AdGuardHome/files/4954147/self_disable.log)
It is a part of a big, 4 days log.  The most annoying A entry for me (and it repeats most) is "report.appmetrica.yandex.net", so according to line 09:52:24 426#770849 I can say, that at 09:52:24 this entry was blocked, but a few seconds later, according to line 09:52:28 426#770846, DNS query was served as normal. Meanwhile, according to dasboard, around 10 AM protection was disabled (Red "OFF" label on top of the dashboard). So, some strange things happened between two lines, but I can't understand - what?
[log_after_restart.log](https://github.com/AdguardTeam/AdGuardHome/files/4954192/log_after_restart.log)
Another log just after restart (enabled the protection before, off course). And again "report.appmetrica.yandex.net" is not blocked, but I don't know why.

**Comment by ameshkov** [comment]
Just before it happened, there were some requests to the REST API that could've done it:
```
2020/07/21 09:52:24 426#770734 [debug] GET /control/filtering/status
2020/07/21 09:52:24 426#770734 [debug] POST /control/filtering/config
2020/07/21 09:52:24 426#770734 [debug] Writing YAML file: /data/adguard/AdGuardHome.yaml
2020/07/21 09:52:24 426#37 [debug] initialized filtering engine
2020/07/21 09:52:24 426#770734 [debug] POST /control/safebrowsing/disable
2020/07/21 09:52:24 426#770734 [debug] Writing YAML file: /data/adguard/AdGuardHome.yaml
2020/07/21 09:52:24 426#770734 [debug] POST /control/dns_config
2020/07/21 09:52:24 426#770734 [debug] Writing YAML file: /data/adguard/AdGuardHome.yaml
2020/07/21 09:52:24 426#770734 [debug] GET /control/filtering/status
```

Could it be that you have some rules in Hassio that could e causing it?

@frenck is there any logs on the Hassio side that could help to find what's causing it?

**Comment by ebloved** [comment]
@ameshkov no, I've never ever made scripts/automations, that colud possibly affect AdGuard plugin by myself. I should dig deeply to give you the correct answer.
But I think I've found the problem. Again, reinstalled the plugin, set it up, then copied working config right next to inoperable an hen diffed them. Found one tiny line, that I think, ruins everything: "filtering_enabled: false". Am I right? If yes, the only thing left - to understand, how it's happening.

**Comment by frenck** [comment]
The add-on itself does not communicate with the API of AdGuard Home. The Home Assistant integration does. However, by default, it only reads. POST requests are only made if things are controlled from Home Assistant; either manually or automated.

If this was the case though, it would be logged in the Home Assistant logbook (as Home Assistant logs any change made in the state machine).

**Comment by ebloved** [comment]
Is it possible to delete thiss issue?
As @frenck told, found in HA Logbook the record: "AdGuard Protection turned off". I don't know how and why that was triggered, but I should do some investigation aka log reading, 'cause it appeared right after the HA update.
@ameshkov thank you for participation.
