### ISSUE TITLE
In the "Top Client", the configured device information is not displayed; the device information comes from DHCP and the WHOIS is displayed normally.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#1893]
Version: v0.103.0-beta2-SNAPSHOT-4175d82
System: Ubuntu 20.04 LTS

![DHCP](https://user-images.githubusercontent.com/58100052/87843535-f6182700-c8e7-11ea-8ed2-05390cd89548.jpg)
![WHOIS](https://user-images.githubusercontent.com/58100052/87843537-f9131780-c8e7-11ea-88a9-6357a4a40db6.jpg)
![Client settings](https://user-images.githubusercontent.com/58100052/87843541-fd3f3500-c8e7-11ea-8a23-6d81e6423991.jpg)

**Comment by ameshkov** [comment]
For this kind of clients, we only display the hostname.

**Comment by hezhijie0327** [comment]
Alright :)

**Comment by Ulmisch** [comment]
@ameshkov in the actual beta and snapshot version the "userfriendly names" are out of function (i have added all clients manually). 
Also arp or rdns does not work to display the client names...

**Comment by ameshkov** [comment]
Yeah, can confirm this
