### ISSUE TITLE
ignore localhost spam (oracle cloud telemtry)

### ISSUE THREAD

**Issue by bruvv** [AdguardTeam/AdGuardHome#1894]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
I am running adguard on oracle cloud. Oracle cloud has some telemetry to tell me how my vps is running. But this means that adguard is getting bommed with dns requests:
```
15:16:40
telemetry-ingestion.eu-frankfurt-1.oraclecloud.com
A

    A: 130.61.0.198 (ttl=100)
    A: 130.61.4.180 (ttl=100)
    A: 130.61.2.179 (ttl=100)

localhost oracle (10.0.0.35)
```
This happens every 60 seconds. With pihole you can ignore localhost queries which is a big thing I am missing. This way the log is filled with useless stuff and I would like to have a clean overview of what devices are talking to my adguard so I can quickly and easy find urls to block or to allow (whitelist).

### Proposed Solution
Add an option to ignore localhost queries.

### Alternatives Considered
Perhaps hide them in the logs so i can see better what is going on in adguard.

### Additional Information
No that I know of. if I have to add anything let me know.

**Comment by mHatsune** [comment]
Similar request for dashboard https://github.com/AdguardTeam/AdGuardHome/issues/1126 (https://github.com/AdguardTeam/AdGuardHome/issues/594)

>This way the log is filled with useless stuff and I would like to have a clean overview of what devices are talking to my adguard so I can quickly and easy find urls to block or to allow (whitelist)

May be you like this https://github.com/AdguardTeam/AdGuardHome/issues/1164

**Comment by bruvv** [comment]
Thanks closing in favor of this one: https://github.com/AdguardTeam/AdGuardHome/issues/946
