### ISSUE TITLE
Facility to check Family DNS blocking status and report undetected domains

### ISSUE THREAD

**Issue by valaria247** [AdguardTeam/AdGuardHome#1896]
From https://github.com/AdguardTeam/AdGuardHome/issues/1133#issuecomment-636209708
How can we report about adult sites for now?

**Comment by ameshkov** [comment]
You can report them to our support -- `support@adguard.com`

**Comment by valaria247** [comment]
But you said this or it's ok if consider to cover within #1133
>Should i create separate feature request for that while it explained above?
>>Yeah, ideally it should be a different feature request if I am getting it right
