### ISSUE TITLE
TYPE65479 entries in Query Log

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#1901]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.102.0
* **How did you setup DNS configuration:**
  * Raspberry Pi 3 Model B+
* **Operating system and version:**
  * Up-to-date stable Raspberry Pi OS

### Expected Behavior

Entry types are 'A' or other relevant entries.

### Actual Behavior

Duplicate 'A' entries appear in the Query Log with the type as TYPE65479.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="897" alt="TYPE65479-2" src="https://user-images.githubusercontent.com/65204836/88022007-d1cf7b00-cb71-11ea-9d2b-692828b295a1.png">

<img width="898" alt="TYPE65479-1" src="https://user-images.githubusercontent.com/65204836/88022014-d5630200-cb71-11ea-8c5e-2240b81027b0.png">

</details>

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by planet0** [comment]
Sure @ameshkov, please see log file below.
https://drive.google.com/file/d/137H9xxTLWCp1KWxGV97WK_gqG3vu-YXE/view?usp=sharing

**Comment by planet0** [comment]
Hmm, looks like they are both coming from two local IPs, and they are Apple TVs.

I also just realised there is a Reddit topic about this on /r/AdGuardHome:
https://www.reddit.com/r/Adguard/comments/hgaxzo/type65479_requests_on_adguard_home/

As well as one on Pi-hole:
https://discourse.pi-hole.net/t/what-is-query-type-65479-in-the-logs/34884

Looks like this is for Encrypted DNS, and Pi-hole has recently done a pull request so all-type blocking will be done in Pi-hole v5.1.

How does that compare with how AdGuard Home handles it?

**Comment by ameshkov** [comment]
> Also, it looks like the UI isn't able to display TYPE65479 properly.

There will be no problem in v0.103.

> Looks like this is for Encrypted DNS, and Pi-hole has recently done a pull request so all-type blocking will be done in Pi-hole v5.1.

AdGuard adblock-style rules block all types.
Not sure about /etc/hosts type rules.

@szolin could you please check it?

**Comment by szolin** [comment]
If request with `qtype=TYPE65479` is received, and `qname` is matched by filters, then we respond with NXDOMAIN error.

**Comment by ameshkov** [comment]
Any filters? /etc/hosts type included?

**Comment by szolin** [comment]
Yes
e.g. for `0.0.0.0 blockhost`
we respond with NXDOMAIN if `qname=blockhost` and `qtype=TYPE65479`

**Comment by planet0** [comment]
Thank you @ameshkov and @szolin!
