### ISSUE TITLE
cannot filter cname

### ISSUE THREAD

**Issue by zhangguanzhang** [AdguardTeam/AdGuardHome#1902]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [- ] I am running the latest version
- [- ] I checked the documentation and found no answer
- [- ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.102.0
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

![image](https://user-images.githubusercontent.com/18641678/88089898-601e1e00-cbbf-11ea-8172-8f228c3adeb4.png)
![image](https://user-images.githubusercontent.com/18641678/88089948-71ffc100-cbbf-11ea-99cf-8a62a46ef6fa.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
As I can see, there's a DNS rewrite configured for jetbrains.com, I don't fully understand what's the issue.

What's the desired behavior?

**Comment by zhangguanzhang** [comment]
In Wireshark, you can see DNS requests that resolve the Cname, and I want the response to be 127.0.0.1 instead of the domain name and IP

**Comment by zhangguanzhang** [comment]
It's my network. 192.168.2.1 is the main route set by my gateway. For some reason the parse request was sent to the main route
