### ISSUE TITLE
[Help]Please change the URL of the anti-AD filter

### ISSUE THREAD

**Issue by gentlyxu** [AdguardTeam/AdGuardHome#1903]
Hello,
     I am the maintainer of the anti-AD project. Yesterday gitee blocked my friend's project because too many people were accessing his project(the picture of below) . The risk is that someday in the future, anti-AD may also be blocked by gitee, so please migrate the anti-AD filter's URL to `https://anti-ad.net/easylist.txt`,This list will always be kept up to date. I am the owner of the domain name `anti-ad.net`, and I will keep that the domain name is always healthy and available. I'm sorry for the inconvenience! 

![gitee-blocked](https://user-images.githubusercontent.com/1243610/88117990-12210e80-cbef-11ea-8631-3ddcb377d8bd.jpg)

**Comment by lancelot-moon** [comment]
https://github.com/privacy-protection-tools/anti-AD
Why do you not simply use the GitHub link?
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt

**Comment by gentlyxu** [comment]
as we all know, github is tooooo slow in mainland china......

**Comment by Alex-302** [comment]
@gentlyxu Hi. What is an old URL? I am not sure if your filter is included on our end.

**Comment by gentlyxu** [comment]
the old URL is: https://gitee.com/privacy-protection-tools/anti-ad/raw/master/easylist.txt

and you can refer: https://github.com/AdguardTeam/AdGuardHome/commit/304a51f17e2a6adf720b8c0eb62da041498415e9
