### ISSUE TITLE
Feature request: IP blocking

### ISSUE THREAD

**Issue by sjhgvr** [AdguardTeam/AdGuardHome#1904]
First things first; I know internet traffic does not pass Adguard Home, DNS requests do.

I've had this happen a couple of times now;

A page saying I won (or could win) something like a Galaxy S10+ .. I think the most recent was: "schrotflinte10 . live" which I think resolved to " 217.116.16.235 ". (Appearently now results in SERVFAIL)

However.. this domain was not known by google, or any blocklist. The IP however, ís: https://www.google.com/search?q=%22217.116.16.235%22+filetype%3Atxt

Now there are thousands of bogus/harmful domains pointing to that IP: https://viewdns.info/reverseip/?host=217.116.16.235&t=1

So the feature request hereby sounds;

I'd like to see an option to import IP-blacklists, to which resolved IPs can be matched.

This way we can block access to yet unknown harmful domains ;)

Thank you very much :D

Note: Previously posted on reddit [here](https://www.reddit.com/r/Adguard/comments/hvaq76/)

**Comment by ameshkov** [comment]
Well, the good news is that this is already possible :)

![image](https://user-images.githubusercontent.com/5947035/88147750-51a72500-cc06-11ea-9127-53b4c702a65a.png)

Just add a rule like this:
`|8.8.8.8^`

You can add IP lists as is, but I'd suggest transforming them to `|IPADDR^`, you can read more about special characters here:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists
