### ISSUE TITLE
Feature Request: Force clear cache

### ISSUE THREAD

**Issue by hoshsadiq** [AdguardTeam/AdGuardHome#1905]
### Problem Description
I had created a new domain, with new DNS entries, however, because I did a `dig` request locally to just before the DNS had propagated, it refused to return valid values despite the DNS records TTL having expired. I found out that this was because AdGuardHome has a local DNS cache, however, this meant that my DNS refused to resolve. I couldn't find any documentation on this either besides the config values, so I ended up taking a stab in the dark and restarted AdGuard Home as I'd figured the cache must be in memory.

### Proposed Solution
- First, the documentation should be updated to mention that there is local caching happening, and how it can be cleared.
- In addition to the that, a nice to have solution is an option somewhere in the UI to clear the cache.

**Comment by ameshkov** [comment]
Quick update: cache will be cleared if you disable and then enable protection.

**Comment by ameshkov** [comment]
This may be implemented alongside #1685

**Comment by hoshsadiq** [comment]
> Quick update: cache will be cleared if you disable and then enable protection.

Odd, I did try that, but the record still wouldn't resolve. If it happens again, I'll definitely double check and perhaps raise a bug issue.

**Comment by mHatsune** [comment]
#1145

**Comment by linus-ha** [comment]
I have to clear my DNS cache on a regular basis, and it cannot be the official solution to set the cache size to zero, wait a bit and re-enable the cache afterwards. A button would be really helpful here!

**Comment by SiNONiMiTY** [comment]
Quick workaround is to set the cache size to 0 and disable optimistic caching, then revert to original size.

**Comment by meichthys** [comment]
> Quick update: cache will be cleared if you disable and then enable protection.

This does not seem to work for me. Queries continue to be served from cache. Do we also need to set the cache size to 0 before re-enabling protection?

**Comment by meichthys** [comment]
Ok, Then to re-enable caching, can we just change the cache size, or do we need to also toggle protection?

**Comment by Eyeborgs** [comment]
> This does not seem to work for me. Queries continue to be served from cache. Do we also need to set the cache size to 0 before re-enabling protection?

@meichthys, As a temporary solution to reset the cache, I'm restarting the service

**Comment by ammnt** [comment]
@ainar-g, FYI. It looks done already in: https://github.com/AdguardTeam/AdGuardHome/issues/5190
