### ISSUE TITLE
Beta3 update update message remains

### ISSUE THREAD

**Issue by shangri0la** [AdguardTeam/AdGuardHome#1906]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>
<img src="http://joxi.ru/Vm6OMlKujBwYZ2">
<img src="http://joxi.ru/823aJEWUDEVknr">

</details>

### Additional Information

update version

**Comment by ameshkov** [comment]
I reckon you're on the "edge" update channel? If so, the issue will go away when the next update is available (probably in an hour or even sooner)

**Comment by shangri0la** [comment]
> I reckon you're on the "edge" update channel? If so, the issue will go away when the next update is available (probably in an hour or even sooner)

ok! thanks
By the way, why did the automatic update for beta disappear?

**Comment by ameshkov** [comment]
> By the way, why did the automatic update for beta disappear?

Did it? It should be working as well
