### ISSUE TITLE
message beta 3 available even if beta 3 is already installed

### ISSUE THREAD

**Issue by zadigre** [AdguardTeam/AdGuardHome#1908]
* **Version of AdGuard Home server:**
  *  0.103.0-beta3

running on Raspberry Pi 4

access with the latest version of Safari and Firefox on macOS Catalina

### Expected Behavior
no message saying update available after installation of the latest update

### Actual Behavior
I still have the "AdGuard Home v0.103.0-beta3 is now available! Click here for more info." message showing at the top after installing the beta 3... and rebooting my raspberry pi. 

is this normal ? just information message?

**Comment by weedb0y** [comment]
Yes, I’m getting the same. Also wanted to confirm, no auto updates right? Because icon at the bottom only checks but never updates

**Comment by ameshkov** [comment]
We're going to publish the v0.103 release later today. At first, it will be pushed to the beta channel so you'll be able to check that this bug is fixed.

> Also wanted to confirm, no auto updates right

It will be back once 0.103 hits the beta channel.

**Comment by zadigre** [comment]
Hi, 

I just received the 0.103 update. updated with the "update" button just fine. 
thank you!
