### ISSUE TITLE
Filtering no longer works

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1912]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.1
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

I just installed the last version right now and looks like the filtering is not work anymore. No one domain is blocked with my filter:
https://ammnt.app/filter.txt

**Comment by ameshkov** [comment]
Worry not, hotfix is already on the way  😭

**Comment by ammnt** [comment]
> Worry not, hotfix is already on the way 😭

Stop scaring me! :D
