### ISSUE TITLE
Vetted blocklists thread

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1913]
AdGuard Home lets the user choose from a list of [vetted blocklists](https://github.com/AdguardTeam/AdGuardHome/blob/master/client/src/helpers/filters/filters.json).

If you have in mind any lists that can be added there, please leave a comment in this thread, we'll consider it.

Previous task with a relevant comments thread: https://github.com/AdguardTeam/AdGuardHome/issues/1325

## Requirements

* Maintained
* Clear purpose
* We prefer (mostly) original lists to compilations (like Energized or oisd.nl). Maybe we should add a special section for compilations (?)

**Comment by nezorflame** [comment]
StevenBlack's one would be nice to have, along with the Energized lists.

**Comment by ameshkov** [comment]
As I recall, there were some people against Energized: https://github.com/AdguardTeam/AdGuardHome/issues/1325#issuecomment-575005823

> @DandelionSprout 
> Since the Energized lists are compiled almost entirely from other lists (except for ~20,000 of the entries that come from Energized Core), I personally would have chose to prioritise adding the best ones among the source lists instead.

Can we just include the Energized Core?

**Comment by DandelionSprout** [comment]
Sadly not, because of https://github.com/AdroitAdorKhan/EnergizedProtection/issues/60.

**Comment by ameshkov** [comment]
Weird stuff, so adding Energized means that the whitelist should be added as well

**Comment by ameshkov** [comment]
We should consider adding Luminati and Avast to the list of "Services", see the lists here: https://github.com/durablenapkin/block

**Comment by ameshkov** [comment]
Hungarian list: https://github.com/hufilter/hufilter/blob/master/hufilter-dns.txt

**Comment by YBS-PC** [comment]
it will be good if you replace Spam404 link
from https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
to https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt

**Comment by ameshkov** [comment]
@YBS-PC the "adblock-list" is supposed to be used by traditional adblockers and not in host-level blockers and there's a risk that at some point there will be added some unsupported modifiers like $third-party or $document. That's why I'd better keep simple hosts list for now.

**Comment by emlimap** [comment]
URLhaus Malicious URL Blocklist - https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist

This list is being used by ublock origin to replace Malware domains list. The author also has an AGH specific list https://gitlab.com/curben/urlhaus-filter#domain-based-adguard-home

**Comment by DandelionSprout** [comment]
It is now pretty safe to assume that anything Energized-related is ruled out entirely. On the other hand, I'm currently testing out [Block List Project: Ads](https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt), with good results so far.

**Comment by josephbu** [comment]
> This list is being used by ublock origin to replace Malware domains list. The author also has an AGH specific list https://gitlab.com/curben/urlhaus-filter#domain-based-adguard-home

Based on my experience I would suggest using the "Lite version" of the URLhaus list, that version contains the current online domains/IPs only. 

The full list results in false positives as it contains entries that once contained malware but may have been fixed 6 months or a year ago, but are still included in the list as historic.

**Comment by ameshkov** [comment]
One more interesting list - `WindowsSpyBlocker - Hosts spy rules` by @crazy-max 
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

**Comment by DandelionSprout** [comment]
It is now reasonably safe to assume that **no** projects or lists made by Energized Protection should ever be included in AdGuard Home or any other AdGuard project: `https://github.com/EnergizedProtection/block/issues/562`

**Comment by crazy-max** [comment]
@ameshkov

> One more interesting list - `WindowsSpyBlocker - Hosts spy rules` by @crazy-max
> https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

Feel free to get back to me if you use this list.

**Comment by lordraiden** [comment]
These are a must have
https://abp.oisd.nl/
https://phishing.army/download/phishing_army_blocklist_extended.txt
https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-domains.txt

To block DoH
https://raw.githubusercontent.com/thiagocrepaldi/doh_servers/master/dohservers.txt
https://raw.githubusercontent.com/thiagocrepaldi/doh_servers/master/dohservers2.txt
https://heuristicsecurity.com/dohservers.txt  (it doesn't work now)

**Comment by ameshkov** [comment]
One more interesting list:
https://github.com/jerryn70/GoodbyeAds

**Comment by uservictor** [comment]
This list is nice for blocking trackers.
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt

Have a nice day

**Comment by planet0** [comment]
**Developer Dan's Ads & Tracking**
Website: https://www.github.developerdan.com/hosts/
List: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by ZeroClover** [comment]
The Malware Domain List vetted by AGH no longer appears to be valid.

https://www.malwaredomainlist.com/hostslist/hosts.txt

**Comment by zero77** [comment]
https://abuse.ch/

**Comment by josephbu** [comment]
> The Malware Domain List vetted by AGH no longer appears to be valid.

@ZeroClover An effective replacement is URLhaus, they have a "Lite version" which contains current online domains/IPs only. 

There is a [project](https://gitlab.com/curben/urlhaus-filter) that is already automatically [building the list in a suitable format](https://gitlab.com/curben/urlhaus-filter#domain-based-adguard-home) twice per day.

**Comment by ZeroClover** [comment]
@josephbu

It appears that this list is designed for AGH, but I'm not quite sure what the point of adding IP filter entries to a DNS-based filter list is.

**Comment by DandelionSprout** [comment]
AdGuard Home is capable of blocking domains by the IP addresses of their CNAME responses. This results in IP entries and even CNAME entries being accepted by AGH.

**Comment by planet0** [comment]
**Anudeep's Blacklist**

> A well-maintained and curated host file containing domains that serve ads, tracking scripts and malware. Each domain is tested and verified before adding to the list. Any reported false positives will be removed as soon as possible.

Website: https://github.com/anudeepND/blacklist
List: https://hosts.anudeep.me/mirror/adservers.txt

> It is highly recommended to use the mirror link as it provides Last-Modified header which ensures that you are getting the latest version.

Same author of the well-known [Whitelist](https://github.com/anudeepND/whitelist).

**Comment by QuantumWarpCode** [comment]
> This results in IP entries and even CIDR entries being accepted by AGH.

If CIDR entries work then should we add Spamhaus DROP list? Not all internet infrastructure abides by these rules so blocking them could be beneficial. [https://www.spamhaus.org/drop/edrop.txt](https://www.spamhaus.org/drop/drop.txt) [https://www.spamhaus.org/drop/dropv6.txt](https://www.spamhaus.org/drop/dropv6.txt)

Less infrastructure follows the EDROP list, so it's more likely to provide actual benefit. [https://www.spamhaus.org/drop/edrop.txt](https://www.spamhaus.org/drop/edrop.txt)

**Comment by begundal** [comment]
Indonesian and Malaysian block list https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt

**Comment by ameshkov** [comment]
Some of the lists mentioned were added in https://github.com/AdguardTeam/AdGuardHome/issues/2638

One more suggestion from https://github.com/AdguardTeam/FiltersRegistry/issues/430 - https://github.com/FutaGuard/FutaFilter

**Comment by sjhgvr** [comment]
> > This results in IP entries and even CIDR entries being accepted by AGH.
> 
> If CIDR entries work then should we add Spamhaus DROP list? Not all internet infrastructure abides by these rules so blocking them could be beneficial. https://www.spamhaus.org/drop/drop.txt https://www.spamhaus.org/drop/dropv6.txt
> 
> Less infrastructure follows the EDROP list, so it's more likely to provide actual benefit. https://www.spamhaus.org/drop/edrop.txt

I created this for that; https://oisd.nl/edropRegexed.php

Ontopic; "oisd full": https://abp.oisd.nl/

Homepage; https://oisd.nl

**Comment by ameshkov** [comment]
I'll be reviewing the thread before v0.106 release #2644 

Regarding OISD, I suggest adding the basic version to the "General" section.

The full version deserves a separate category ("compilations"), but that would lead to adding other compilations as well (Energized for one), and I am still afraid of people that simply check all the available boxes and then suffer from false positives.

**Comment by sjhgvr** [comment]
Regional Blocklist: TUR: nurcan Türk ad-list (https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt)
Results in 404. Maybe remove?

**Comment by ameshkov** [comment]
One more: https://github.com/prodaft/malware-ioc

**Comment by cbuijs** [comment]
I created below repo to be able to "GEO-Blocking" on DNS responses. It is a bit heavy at hand (REGEX based, we need a CIDR filter thingy for filtering our IP-addresses from responses, still need to check if the RFE is already done):

https://github.com/cbuijs/geo-ip/tree/master/adblock

Updated every 24h. Work great in AGH.

**Note:** I will collapse some of the regexes soon in an update making these 50-75% smaller.

**Note 2:** This functionality for reference: https://github.com/folbricht/routedns/blob/master/doc/configuration.md#Response-Blocklist (with the `filter = true|false` functionality)

**Comment by uservictor** [comment]
https://github.com/duckduckgo/tracker-radar

You can add this list, there is an instruction how to build.

**Comment by DandelionSprout** [comment]
I know I may be very late with this, even when considering that nothing has resulted from this thread after 11½ months, but now is the time for me to place my roulette tokens on one of my own lists:

[Dandelion Sprout's Anti-Malware List for AdGuard Home](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt)

It is designed specifically for AdGuard Home and its syntax (incl. RegEx, `://`, and IPs), it is updated weekly or more often, and specialises in particular in preventing malware redirections, in which area it defeats paid industry security agencies' paid lists by 2 or 3 *magnitudes*.

**Comment by ameshkov** [comment]
@DandelionSprout it resulted, we just create additional issues for actually adding or updating lists.

**Comment by gyCfjSnO** [comment]
Can we please have the ticked firebog lists added/vetted?

https://v.firebog.net/hosts/lists.php?type=tick

**Comment by Potterli20** [comment]
International/China accelerated ad filtering rules subscription.
国际/中国加速广告过滤规则订阅
Trli rules is the only global library that provides a complete set of rules, and the rules are updated 24 hours a day, probably starting at 0:00 US time.
冷莫(trli)的规则唯一一个提供全球比较全的库，规则是24小时更新，大概是第二天的从美国时间0点开始。

文件库:trli.coding.net/public
说明库:github.com/Potterli20/hosts
Library: trli.coding.net/public
That library: github.com/Potterli20/hosts

adguardhome:https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adguardhome.txt

The project is available globally and has been made out of a black and white list of global examples.
Of course, the blacklist has mistakenly killed the domain name processing.

**Comment by DandelionSprout** [comment]
My current understanding is that when it comes to lists that should be natively included in AGH as opt-ins, such requests are now supposed to be submitted to https://github.com/AdguardTeam/HostlistsRegistry, although it doesn't seem to me to have taken effect in stable AdGuard versions yet.

For general simple suggestions, however, I can only presume that this thread is still the intended place.

**Comment by gyCfjSnO** [comment]
Can we look at adding some of the lists from Zelo72 https://github.com/Zelo72/adguard

**Comment by timkgh** [comment]
> Can we look at adding some of the lists from Zelo72 https://github.com/Zelo72/adguard

Zelo72 seems to be gone, does anyone know what happened to him and whether there are replacements for this list? https://github.com/AdguardTeam/AdGuardHome/issues/1913#issuecomment-949855502

**Comment by gyCfjSnO** [comment]
> > Can we look at adding some of the lists from Zelo72 https://github.com/Zelo72/adguard
> 
> Zelo72 seems to be gone, does anyone know what happened to him and whether there are replacements for this list? [#1913 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/1913#issuecomment-949855502)

Oh no! I really enjoyed using Zelo72's lists 🥲 I hope it's temporary.

**Comment by timkgh** [comment]
> > > Can we look at adding some of the lists from Zelo72 https://github.com/Zelo72/adguard
> > 
> > 
> > Zelo72 seems to be gone, does anyone know what happened to him and whether there are replacements for this list? [#1913 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/1913#issuecomment-949855502)
> 
> Oh no! I really enjoyed using Zelo72's lists 🥲 I hope it's temporary.

The list is now https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt

**Comment by ainar-g** [comment]
Starting with AdGuard Home 0.107.17, AdGuard Home will use the [Hostlists Registry](https://github.com/AdguardTeam/HostlistsRegistry) as the source of its filtering rule lists.  Please send your suggestions to that repo.  See #3972.  Thanks!
