### ISSUE TITLE
Consider using "REFUSED" or "Null IP" instead of NXDOMAIN by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1914]
It seems that Firefox may query CF DOH when it encounters NXDOMAIN. Also, we've seen strange behavior on iOS as well.

I don't like using null IP as the default though as it may interfere with a server running locally. Let's experiment with REFUSED.

**Comment by ameshkov** [comment]
@szolin 

All my experiments showed that the only approach that works 100% and does not lead to any issues with browsers using different fallbacks is "null IP".

So here's what I propose:

1. Change default to: `Default: Respond with zero IP address (0.0.0.0 for A; :: for AAAA) when blocked by Adblock-style rule; respond with the IP address specified in the rule when blocked by /etc/hosts-style rule`
2. Don't forget to change the `English` strings
3. Make sure that the strings are updated in Crowdin

**Comment by loyingEcu** [comment]
I can't filter ads when I use an Android device?

**Comment by EntropySmoke** [comment]
Why change it for AdGuard Home and not AdGuard for Android?

**Comment by ameshkov** [comment]
In the case of AdGuard for Android, we are sure that Android won't fallback to a different DNS server when it encounters an NXDOMAIN response. This is not the case with AGH, depending on how DNS is configured, the system may choose to fallback to a different DNS server.

**Comment by ayushnix** [comment]
> All my experiments showed that the only approach that works 100% and does not lead to any issues with browsers using different fallbacks is "null IP".

@ameshkov Can you elaborate what you found in your experiments?

I noticed that when I reply with `REFUSED` for blocked domains, my Android device queries `blocked.domain.mylocal.domain`, which obviously turns out to be a `NXDOMAIN`. Why does Android (and possibly other operating systems) behave this way?
