### ISSUE TITLE
Кнопки Next и Previous недоступны в верхней части журнала

### ISSUE THREAD

**Issue by mHatsune** [AdguardTeam/AdGuardHome#1915]
https://github.com/AdguardTeam/AdGuardHome/issues/1125#issuecomment-546563735 > 4 or https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-548359763 > 1
This feature had on v0.102

**Comment by ameshkov** [comment]
mm, I didn't get it

**Comment by mHatsune** [comment]
Sorry i'm still trying write it correctly in russian. I noticed it looks like wrong. 😄
Above mentioned feature had on v0.102 "The Previous and Next buttons on the top"

**Comment by ameshkov** [comment]
yeah, now it's better:)


Most likely we will get rid of paging on the log page and replace it with automatically loading of the next page when you scroll to the bottom

**Comment by mHatsune** [comment]
Only #666 available related it but no milestone.

**Comment by ameshkov** [comment]
This is a part of the redesign that we're doing right now. No task because it's discussed internally, we'll create issues on GH when the design is ready and it's time to code

**Comment by mHatsune** [comment]
@ameshkov back-to-top button needs to add. it must appear so far when user scroll down 1 1/2+ length (do not display it by default). when user clicked that button then necessary to load new queries too otherwise again we have to refresh browser tab.
User able to go to top by mouse or browser scroll bar if it less than 1 1/2 pages length

(unnecessary issues #1849 #1850 #1851)

![image](https://user-images.githubusercontent.com/63988538/88452074-ac56b000-ce96-11ea-8812-0f2e8189da0e.png)

**Comment by ameshkov** [comment]
> back-to-top button needs to add

Yeah, this makes sense.
