### ISSUE TITLE
Less information on Response details tooltip

### ISSUE THREAD

**Issue by gontazaka** [AdguardTeam/AdGuardHome#1916]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Proposed Solution

Please Display A/AAAA/CNAME records in "Allowed" queries.
There is less information to see than Not filtered queries. (Upstream, Elapsed)

Before I forget, I found a duplicate table in the source code.
https://github.com/AdguardTeam/AdGuardHome/blob/v0.103.2/client/src/components/Logs/Cells/getResponseCell.js
Line#58, Line#66

### Additional Information

<details><summary>Screenshot:</summary>

_Not filtered query_
![agh_notfilterd](https://user-images.githubusercontent.com/40248057/88337846-5daff580-cd72-11ea-87a8-ec4e32593acc.png)
_Allowed query_
![agh_allowed](https://user-images.githubusercontent.com/40248057/88337923-81733b80-cd72-11ea-88ac-90f529486ecd.png)

</details>

**Comment by ameshkov** [comment]
@IldarKamalov same issue with "Blocked" status -- even if "response" or "original_response" fields are available, "Response" / "Original Response" fields aren't shown.
