### ISSUE TITLE
Incorrect protocol displayed in new query log

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdGuardHome#1917]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.2
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Windows 10 1909

### Expected Behavior

Proper DNS protocol is displayed based on the DNS upstream that was queried.

### Actual Behavior

Plain DNS is displayed for both DoT and DoH upstreams.

### Screenshots

<details><summary>Screenshot (DoH):</summary>

![Screenshot (16)](https://user-images.githubusercontent.com/42700209/88344724-e83c2900-cd61-11ea-910a-f63a0923fad3.png)

</details>

<details><summary>Screenshot (DoT):</summary>

![Screenshot (18)](https://user-images.githubusercontent.com/42700209/88345191-14a47500-cd63-11ea-9d13-277cb59f257e.png)

</details>

**Comment by ameshkov** [comment]
Hi, this is a protocol of the incoming DNS query, not the one that's been sent to the upstream

**Comment by BlitW0** [comment]
Can you please explain to me in which case it will show DoT or DoH?

**Comment by ameshkov** [comment]
If you configure AdGuard Home to be a DOH or DOT server, this would be possible

**Comment by Rru247** [comment]
Still do not understand well. LOL.
Does it mean, do we need to enable "Encryption settings"?

If we have not enabled it, only we get half benefit from AGH? because incoming DNS query become plaintex O_0

**Comment by ameshkov** [comment]
AdGuard Home itself is a DNS server and it can listen for DNS queries using different protocols including DOH and DOT.

But if you're running it in your local network, it's not really important to encrypt DNS traffic.

**Comment by Rru247** [comment]
>AdGuard Home itself is a DNS server and it can listen for DNS queries using different protocols including DOH and DOT.

 Ah! now got you said thing.

I have another question. we use dedicated software similar AGH to get benefit from DOH/DOT instead put plaintext DNS addresses to our devices. Isn't it possible to keep both outgoing and incoming DNS queries encrypted? eg: with AG DNS.

**Comment by ameshkov** [comment]
> Isn't it possible to keep both outgoing and incoming DNS queries encrypted?

Sure, AGH can work as a DOH/DOT server as well, you can configure it in the Encryption settings.

**Comment by Rru247** [comment]
Again do not understand. I'm running AGH in my local network. only LAN devices connect to AGH then as per my understand it's not important to enable "encryption settings" as you said because no external clients connect to AGH.

AGH use AG DNS DOH by default (my instance) then i mean isn't it possible to keep both outgoing and incoming (discussion with AG public DNS) encrypted? It looks like to me. i ask something from you encrypted but you answer me plaintext.

**Comment by ameshkov** [comment]
> outgoing and incoming (discussion with AG public DNS) encrypted

They are encrypted.

What's not encrypted is your LAN devices connecting to AdGuard Home and this is shown in the query log.

**Comment by Rru247** [comment]
Now understand what happening. Thanks.

**Comment by Rru247** [comment]
May be need to explain shortly in wiki otherwise many people will ask about that. :D
