### ISSUE TITLE
Add the used DNS to the query log

### ISSUE THREAD

**Issue by wysnxzm** [AdguardTeam/AdGuardHome#1919]
There is corresponding DNS information in the log file, but the page is not displayed, I hope it can be displayed

**Comment by nzm001** [comment]
Agree. Both "Compact" and "Default" view don't display response ip. I also hope a 'Complicated' view (just like version 0.102). Besides, if I want to search query log now, I can't specify both domain and client (e.g. search dns query 'google.com' from client '192.169.1.10').

**Comment by wysnxzm** [comment]
> Agree. Both "Compact" and "Default" view don't display response ip. I also hope a 'Complicated' view (just like version 0.102). Besides, if I want to search query log now, I can't specify both domain and client (e.g. search dns query 'google.com' from client '192.169.1.10').

Need more information to display, it will be more interesting haha🤣

**Comment by mHatsune** [comment]
#468

**Comment by ameshkov** [comment]
> There is corresponding DNS information in the log file, but the page is not displayed, I hope it can be displayed

It is displayed in v0.103.3
