### ISSUE TITLE
DNS access list performance with huge "Disallowed Clients" lists

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1923]
Example: 
https://github.com/DandelionSprout/adfilt/blob/master/AdGuardHomeDisallowedIPs.txt

I suppose we may spend too much time matching such a huge list if we do it in a straightforward manner.

Please check that we at least keep the list sorted and parsed to CIDRs.

**Comment by szolin** [comment]
There's no problem on server side, the algorithms are quite optimal already.
