### ISSUE TITLE
Force Safe Search shows query logs, while the Force Safe Search is disabled in the general settings

### ISSUE THREAD

**Issue by carstenflokstra** [AdguardTeam/AdGuardHome#1924]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details
~So I installed Adguard Home on my Raspberry Pi 3 to block ads and tracking on the whole network. But it seems that the stats are not correctly displayed. How did I know? I turned of Force Safe Search and it is still showing up in my results of the last 24 hours, which seems to be odd. Furthermore, the requests and blocked requests are still counting after I installed Adguard Home. This is okay, but the displaying labels say that this request happened in the last 24 hours, which seems not correct.~

After research the data is correct, but the Force Safe Search option is bugged. It shows query logs while the Force Safe Search is disabled. This can result in an unintended safe search or just a visual bug in the info. 

* **Version of AdGuard Home server:**
  * 0.103.2 (Running the Dutch translations)
* **How did you setup DNS configuration:**
  * ISP Router where the DNS is set to my Raspberry Pi 3
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3
* **Operating system and version:**
  *  Raspbian (don't know which version)

### Expected Behavior
~I expect that the 24 hours card shows the correct results. Now it seems like a total overview since Adguard is installed, which is also fine. It would be nice to have two options. One that shows the info about the past 24 hours, and one that provides overall info since running.~

The Force Safe Search should display `0` due to the settings that are enabled in the General Settings.

### Actual Behavior
~The 24 hours tab shows overall data instead of the last 24 hours, noticed by the Force Safe Search queries that were enabled the first day and is disabled a day later. It still shows this info.~

It displays `96` results and the query logs are also filled which seems that it is still doing a safe search or the info is some kind of misplaced (memory leaks etc.) 

### Screenshots

![image](https://user-images.githubusercontent.com/24441267/88379673-ac29b800-cda3-11ea-9be6-2a4794c26aa6.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Could you please click on that number and check when these requests were made?

**Comment by carstenflokstra** [comment]
Well it seems that the info is indeed correct... Maybe the Safe Search stat is bugged? 
![Screen Recording 2020-07-24 at 11 55 07](https://user-images.githubusercontent.com/24441267/88380400-ca43e800-cda4-11ea-94d8-2805913dc20c.gif)

**Comment by ameshkov** [comment]
What I mean is that you can click on the number of "Geforceerd veilig zoeken", it will lead you to the query log

**Comment by carstenflokstra** [comment]
![image](https://user-images.githubusercontent.com/24441267/88380727-5d7d1d80-cda5-11ea-8fbb-eef636a9577c.png)
Well, it seems that we have another problem here. I disabled Force Safe Seach, and there a still some logs here. 

![image](https://user-images.githubusercontent.com/24441267/88380864-a0d78c00-cda5-11ea-9bf2-f066e7c8629a.png)

**Comment by carstenflokstra** [comment]
I will change the title description :)

**Comment by szolin** [comment]
Query logs show what happened in the past.
Disabling safe-search will only affect newer requests.  The old ones will still be shown as "safe search" and marked red.

**Comment by ameshkov** [comment]
@szolin wait, but as I understand, this is today's data.

@carstenflokstra have you disabled safe search before the 10:30?

**Comment by szolin** [comment]
If so, please reopen the issue.
I just couldn't reproduce it.

**Comment by carstenflokstra** [comment]
You are correct @ameshkov! I disabled Safe Search teo days ago and the wuerry logs do still show data from today.

**Comment by ameshkov** [comment]
Could it be that you have safe search enabled for one of the configured clients?

**Comment by carstenflokstra** [comment]
Nope, I have it all on my network. No default client configs

**Comment by ameshkov** [comment]
Tbh I also cannot reproduce this:( Is there any reliable way to do this? Could you please try reproducing it again?

**Comment by carstenflokstra** [comment]
Queries do not show up now if I make a new request. I'll check tomorrow morning to make sure that it is not a time-bound issue. Maybe it is a memory leak with some dates? It happened also after upgrading the software. Maybe I should reboot it.

**Comment by carstenflokstra** [comment]
After a restart, the query logs still appear, but there are no more new queries done. So Safe Search is indeed disabled :)
