### ISSUE TITLE
Connection error since upgrading to 0.103.0

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#1928]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version - 0.103.2
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.2
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior

Home Assistant would connect to AGH.
### Actual Behavior

Home Assistant is not able to connect to AGH. 
### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

[More info in Home Assistant's repo issue.](https://github.com/home-assistant/core/issues/38112)

**Comment by ameshkov** [comment]
@frenck is already aware of this, it needs to be handled on the HA side.

To be honest, I thought that updates are disabled for AGH when it's used alongside HA, have you updated it manually?

**Comment by agneevX** [comment]
No, my install is on a separate SBC, but the error is similar.
