### ISSUE TITLE
Change static IP allocation

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#1929]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **If it's a router or IoT, please write device model:**
  *  Pi 3B+
* **Operating system and version:**
  *  Raspberry Pi OS Buster

I want to change the static IP allocation. When I installed AGH, the then IP was set. How do I change it now?

**Comment by ameshkov** [comment]
Open `/etc/dhcpcd.conf` and look for "static ip_address" string there

**Comment by agneevX** [comment]
How do I set rewrites for a TLD like `.home`, such that any query ending with `.home` would be redirected to an IP?

Also, does AGH have a discord?

**Comment by szolin** [comment]
> How do I set rewrites for a TLD like .home, such that any query ending with .home would be redirected to an IP?

`*.home -> 1.2.3.4`

**Comment by agneevX** [comment]
You mean here? That does not seem to work. 

<img width="513" alt="image" src="https://user-images.githubusercontent.com/19761269/88408616-6e538080-cdf1-11ea-833a-6453c19af2df.png">

**Comment by szolin** [comment]
It's being fixed currently
https://github.com/AdguardTeam/AdGuardHome/issues/1926
