### ISSUE TITLE
Support clusters or configuration replication accross multiple nodes

### ISSUE THREAD

**Issue by siavashs** [AdguardTeam/AdGuardHome#1931]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Currently it's not possible to synchronize the configuration across multiple running instances of AdGuard Home when a change is made through UI.

### Proposed Solution
Nodes should form a cluster either by manual configuration or automated discovery and synchronize configuration, stats and logs.
This can be useful for high available setup and ease node management.

### Alternatives Considered
Using file synchronization services like [Syncthing](https://github.com/syncthing) to keep `AdGuardHome.yaml` updated across nodes.
But this method can cause issues for users who activate the DHCP server.
Also I'm not sure if the service will reload the configuration automatically and also the **query stats and logs** cannot be safely synchronized this way.

### Additional Information
I'm willing to contribute this feature but it requires more thought and discussion.

**Comment by bitchecker** [comment]
:+1:

**Comment by ameshkov** [comment]
Hello and sorry for the late reply!

It seems that your feature request duplicates https://github.com/AdguardTeam/AdGuardHome/issues/573

Please check the discussion there, it seems to be relevant. If you're willing to contribute it, let's discuss, I'll be glad to assist.
