### ISSUE TITLE
Ability to specify upstream for Blocked services 

### ISSUE THREAD

**Issue by Heshmatkhah** [AdguardTeam/AdGuardHome#1932]
### Problem Description
There is very strong censorship in Iran, Iran government do DNS poisoning in addition to IP filtering and blocking **DNS over HTTPS Servers**

So if you want to visit a site like `youtube` the answer will be `10.10.34.35` or something like that which is called [**Peyvandha** ](https://fa.wikipedia.org/wiki/%D8%B5%D9%81%D8%AD%D9%87_%D9%BE%DB%8C%D9%88%D9%86%D8%AF%D9%87%D8%A7).

### Proposed Solution
What I want is the ability to specify upstream for `Blocked services`, so if the user specifies an upstream for them, and doesn't block them (through the Blocked services), the AdGuard uses that specific upstream for this services. So I can use a DNS over LTS for this upstream.

The problem with changing the whole upstreams is that in that case I will lose am ability to use many Iranian sites that are only resolvable over a normal DNS query within the country.

Also, It will be great if you add some other services like `Telegram` to Blocked services list

**Comment by mHatsune** [comment]
See https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains

>Also, It will be great if you add some other services like Telegram to Blocked services list

You can vote #1692 (adguard and community members may not prefer to see some services in this list)

**Comment by Heshmatkhah** [comment]
Hi
Thanks for sharing #1692 with me.

While I was writing a response to you I found a list of domains for that services in the source code

my problem with  [**Specifying upstreams for domains**](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains) was that I don’t know the full list of domains.

Tanks a lot

**Comment by KizunaH** [comment]
Unfortunately, `blocked services` component use for an opposite purpose.

>my problem with Specifying upstreams for domains was that I don’t know the full list of domains.

First, add domains that you may know about certain service then open the site or app. after that check query log then you can be find rest of domains used by it  otherwise search on forums, repositories or that company website
