### ISSUE TITLE
Client List Identifier

### ISSUE THREAD

**Issue by damooooooooooh** [AdguardTeam/AdGuardHome#1935]
Client list is showing incorrect client identifier/IP address. 

Version is 0.103.3
Platform is Raspberry Pi 4 2GB

![Screenshot_20200724-195306~2](https://user-images.githubusercontent.com/1326094/88433161-78777e00-cdf5-11ea-96ff-4295e5540955.png)

**Comment by ameshkov** [comment]
Could you please check the list of clients in AdGuardHome.yaml? Is it also wrong?

**Comment by damooooooooooh** [comment]
This isn't an issue.  It is down to the truncation of the Client ID field on the UI when browsed from a small form factor.
