### ISSUE TITLE
Please post binaries of latest version

### ISSUE THREAD

**Issue by BlohoJo** [AdguardTeam/AdGuardHome#1937]
Was disappointed to see that binaries are no longer being posted.

Please post binaries of the latest AdGuard Home builds, as they used to be, stopping with version 0.102.0.

I am not proficient with Git and am unable to get it to work right. I don't have a ton of time to spend trying to troubleshoot that... I just want a working AdGuard binary.

**Comment by mHatsune** [comment]
see https://github.com/AdguardTeam/AdGuardHome/issues/1911#issuecomment-663150788

**Comment by frenck** [comment]
Imho this project does no longer provides the privacy protection it claims, I've raise #1941 as a result of this.

**Comment by szolin** [comment]
Download our official binaries from here: https://static.adguard.com/adguardhome/release/version.json
