### ISSUE TITLE
Small optical glitch

### ISSUE THREAD

**Issue by Ulmisch** [AdguardTeam/AdGuardHome#1939]
### Screenshots
Just take a look. at the graph in the malware and adult section, it is not at the bottom if the count is "0".

<details><summary>Screenshot:</summary>

<img width="1203" alt="Bildschirmfoto 2020-07-25 um 07 58 55" src="https://user-images.githubusercontent.com/51493890/88450129-f87d0280-ce4c-11ea-9462-71b25453ff9f.png">

**Comment by ameshkov** [comment]
@IldarKamalov can we quickly address this? I remember this was a bug in the chart library that was not fixed at the time when it was first reported, maybe things changed now?

**Comment by IldarKamalov** [comment]
I tried, but without success. I'm waiting for a response from the community of this package

**Comment by IldarKamalov** [comment]
@ameshkov It is easier to replace the chart library than to fix this problem.

**Comment by ameshkov** [comment]
Well, we'll do that eventually when we develop the redesigned version
