### ISSUE TITLE
Add release assets based on platform and guides to product page

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#1942]
#### Problem Description
adguardhome so far designed to home users (everyone are not so technical). current way to get the setup file is quite complicated to them with github. (find release location and check version assets) then search guide to install. i know this isn't a sensitive thing for most technical persons and developers.

1. Add release assets to product page based on platform/operating system. (include 32/64bit as below)
2. Once user clicked to download then pop up installation guide available for that operating system.
3. Consider to add new button or replace one of "how it works", "how to setup" button with @ameshkov funny release notes.

#### Product Page

![image](https://user-images.githubusercontent.com/63988538/88457974-6fee7880-cec5-11ea-88f2-a4948c873d06.png)

See a sample on wire website  https://wire.com/en/download/ (it also opensource project)
https://adguard.com/en/adguard-home/overview.html (no need to change the URL)

#### Short Guide
![image](https://user-images.githubusercontent.com/63988538/88458323-2e130180-cec8-11ea-8696-44ad7bf44132.png)

---

**Comment by ameshkov** [comment]
We now have an automated installation script that kinda covers this:
https://github.com/AdguardTeam/AdGuardHome#getting-started

**Comment by KizunaH** [comment]
@ameshkov download options already vanished

> We now have an automated installation script that kinda covers this:
> https://github.com/AdguardTeam/AdGuardHome#getting-started

May be
