### ISSUE TITLE
Unable to compile from source on native 32-bits systems, using musl

### ISSUE THREAD

**Issue by frenck** [AdguardTeam/AdGuardHome#1945]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  AdGuard 0.103.3
* **How did you setup DNS configuration:**
  *  n/a
* **If it's a router or IoT, please write device model:**
  *  Any armhf/armv7/armv6 or i386 based CPU
* **Operating system and version:**
  *  Alpine 3.12

### Expected Behavior

Being able to build from source.

### Actual Behavior

Go build fails with the following error:

```
Error relocating /usr/bin/go: __nanosleep_time64: symbol not found
Error relocating /usr/bin/go: __nanosleep_time64: symbol not found
Error relocating /usr/bin/go: __nanosleep_time64: symbol not found
Error relocating /usr/bin/go: __nanosleep_time64: symbol not found
Error relocating /usr/bin/go: __nanosleep_time64: symbol not found
Error relocating /usr/bin/go: __nanosleep_time64: symbol not found
```

### Additional Information

The Home Assistant add-ons build on a CI cluster, with a bunch of machines. As we build for 5 architectures (armhf, armv7, aarch64, amd64 & i386), we actually have all CPUs natively available and do not use cross builds at all.

In general, this is faster and more reliable, especially with some other things we build that are far more intensive.

However, the AdGuard Home project isn't buildable on 32-bits CPUs in case the OS uses musl, as Alpine does.

Alpine 3.12 ships with musl 1.24, according to the release notes of musl: 

`This release moves all 32-bit archs to 64-bit time_t, enabling them to represent times beyond January of 2038.`

Source: <https://musl.libc.org/releases.html>

Consider this is my only alternative right now on building a reproducible package for AdGuard Home, and the fact the documentation does not mention this (as a matter of fact, this is pointed to as the alternative?).

I would like to have some advice on what is needed to build AdGuard Home on a 32 bits, musl-based, systems.

Dockerfile used: <https://github.com/hassio-addons/addon-adguard-home/blob/master/adguard/Dockerfile>

**Comment by ameshkov** [comment]
Quick question: have you considered an alternative approach?

For instance, would it be possible to add a preflight(?) step to your pipelines that will produce the binaries for all the necessary platforms, and then use these binaries in the consequent build steps?

In order to produce the binaries, you can simply run a script like this:

```
git clone --branch "v0.103.3" --depth=1 "https://github.com/AdguardTeam/AdGuardHome" /tmp/adguard
cd /tmp/adguard
CHANNEL=release make release
```

Prerequisites: goreleaser, snapcraft, node, npm.

Alternatively, instead of configuring all these tools, you can use the same image we use to build the release:
`docker run --volume $(pwd):/build --rm --env CHANNEL=release --net=host adguard/golang-ubuntu make release`

**Comment by frenck** [comment]
The problem remains the same, as the machine-building is still 32 bits... even with pre-flighting it or using the proposed docker images.

**Comment by ameshkov** [comment]
Well, at least now I understand your frustration with our changes as I am quite frustrated myself thinking about how to resolve this :)

Two more options to consider:

1. Set up a separate repo that will build the binaries and publish them. Here's an working example of a [GH action](https://github.com/ameshkov/testghactions/blob/master/.github/workflows/build.yml) and here's [it's result](https://github.com/ameshkov/testghactions/releases/tag/v0.103.3).
2. For this version of addon use the binaries that I attached to `v0.103.3` release on Github. Hopefully, the binaries verification process will be sorted out before the next release.

The current binaries can be verified manually, here's the instruction:

1. Build everything:
    ```
    git clone --branch "v0.103.3" --depth=1 "https://github.com/AdguardTeam/AdGuardHome" /tmp/adguard
    cd /tmp/adguard
    docker run --volume $(pwd):/build --rm --env CHANNEL=release --net=host adguard/golang-ubuntu make release
    ```

2. Unpack the dist you are going to verify, calc the executable file checksum, compare. For example:
    ```
    $ tar xvfz AdGuardHome_linux_arm64.tar.gz
    $ shasum -a 256 AdGuardHome/AdGuardHome

    f0b16d6088aa090d3f03cd4648d68ef5396f0914561161e9a7987b06ebe92052  AdGuardHome/AdGuardHome
    ```

**Comment by frenck** [comment]
The concerns raised earlier, I've raised before making this change. I'm not really frustrated and have not problems with moving to build something from source, however learned later that doesn't work either for my use-case.

Thanks for the repo setup/demo. That is absolutely an option, my main concern for the add-on is reproducibility, for which the downloaded version (download URL if AdGuard Home), must be ensured.

So, since I fail to get is to build from source for all architectures, I'm personally longing for having an option to download specific versions (as discussed briefly in #1941).

**Comment by frenck** [comment]
Closing, as I've went for the provided binaries for now.
