### ISSUE TITLE
ADGuardHOME作为转发器规则不生效

### ISSUE THREAD

**Issue by wujungod** [AdguardTeam/AdGuardHome#1946]
你好我在windows server下的DNS转发器指向了ADGuardHOME发现阻止规则不生效，是不支持这样的使用方法么？
I am running the latest version
I checked the documentation and found no answer
I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
Please provide more information, from your description I don't understand what exactly is wrong.

Also, make sure that you configured your devices to use AGH DNS server.

**Comment by KizunaH** [comment]
請分步說明

**Comment by Potterli20** [comment]
服务器是不是没有开或占用53和853？

**Comment by wujungod** [comment]
你好问题是这样的，我使用windows的dns服务器设定转发器为adguatd的ip，当设定阻止访问某一个网址例如||baidu.com
^依然能够访问，并且以为需要等待，等待30分钟均可以访问。

potterli <notifications@github.com> 于 2020年8月14日周五 08:39写道：

**Comment by wujungod** [comment]
另外在不使用windows dns的情况下有效，我使用的版本为0.103.3

吴俊 <wujungod@gmail.com> 于 2020年8月15日周六 13:42写道：

**Comment by wujungod** [comment]
吴俊 <wujungod@gmail.com> 于 2020年8月15日周六 13:46写道：

**Comment by wujungod** [comment]
另外，手机uc浏览器会被禁止使用，禁用过滤器后可以使用，我知道这不是adguard的锅，但是根据日志查询放行uc.com
相关的请求后也不能使用，建议日志查询是否能更加详细。

吴俊 <wujungod@gmail.com> 于 2020年8月15日周六 13:52写道：

**Comment by ameshkov** [comment]
在adguard DNS设置试试变化拦截模式，试试选择无效IP。
