### ISSUE TITLE
"Blocked" and empty points in the log options

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1951]
Hello,

please, pay attention on the "Blocked" (untranslated) and empty points in the log options:
![image](https://user-images.githubusercontent.com/45385632/88474782-926aab00-cf32-11ea-9b1b-cdb16d1fa030.png)

Thank you.

Cheers!

**Comment by uservictor** [comment]
Related to this issue, this is on my Android Smartphone (Android 8.0 with screenresolution 1920x1080)
English
![Screenshot_20200729-003725](https://user-images.githubusercontent.com/56163305/88729445-38393800-d134-11ea-95c9-eb374170924e.png)

German
![Screenshot_20200729-004209](https://user-images.githubusercontent.com/56163305/88729544-759dc580-d134-11ea-8364-116d6b7010fb.png)
_Gesperrte jugendgefährden-
de Webseiten_
should look like this:
_Gesperrte
jugendgefährdende
Webseiten_

In querylog is also an cosmetic issue:
![Screenshot_20200729-004151](https://user-images.githubusercontent.com/56163305/88729927-39b73000-d135-11ea-926b-5d3c720cf804.png)
The refresh circle is "misplaced", maybe an smaller font for "Anfragenprotokoll" would solve this. (Language is German)

On **Setup guide** the page dont fit the screen and the ipv6 adress could be cut in better way, or smaller font.
![sketch-1595977330484](https://user-images.githubusercontent.com/56163305/88731799-7b48da80-d137-11ea-8bae-90d989659fa4.png)

![sketch-1595977429353](https://user-images.githubusercontent.com/56163305/88731930-8439ac00-d137-11ea-9b37-f3a5d1ba91b6.png)

Hope this helps.

**Comment by uservictor** [comment]
In querylog is also an cosmetic issue:
![sketch-1595977763985](https://user-images.githubusercontent.com/56163305/88736002-d4653e00-d138-11ea-9842-e8562c1a7628.png)
The refresh circle is "misplaced", maybe an smaller font for "Anfragenprotokoll" would solve this. (Language is German)

**Comment by uservictor** [comment]
On **Setup guide** the page dont fit the screen.

And the ipv6 adress could be cut in better way, or smaller font.

![sketch-1595979041168](https://user-images.githubusercontent.com/56163305/88739730-8a318c00-d13b-11ea-9d3d-bfaa3eb44226.png)
![sketch-1595979121373](https://user-images.githubusercontent.com/56163305/88739740-8f8ed680-d13b-11ea-8ae7-394d914b14a0.png)

**Comment by ameshkov** [comment]
@IldarKamalov could you plz take a look?

**Comment by uservictor** [comment]
Hello, please look at **Settings -> DNS Settings** scroll to **DNS cache configuration**

This category does not fit the screen, it has empty space on right side, the other categorys are fine.

![Screenshot_20200730-161328](https://user-images.githubusercontent.com/56163305/88934613-20bb9580-d281-11ea-8095-f51459048ae7.png)
![sketch-1596118962048](https://user-images.githubusercontent.com/56163305/88934630-27e2a380-d281-11ea-9ad4-ebffea494581.png)
![Screenshot_20200730-161348](https://user-images.githubusercontent.com/56163305/88934652-2e711b00-d281-11ea-948c-8bea58a4bea8.png)
