### ISSUE TITLE
[Feature request] Yandex Safebrowsing

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1952]
Hello,

please consider adding Yandex Safebrowsing feature. They have an open API and combined with Google Safebrowsing and AdGuard Antiphishing, this will give a best protection ever😅:
https://yandex.ru/dev/safebrowsing/

Thank you.

Cheers!

**Comment by ameshkov** [comment]
They use the same protocol as Google so I guess this needs to be merged to https://github.com/AdguardTeam/AdGuardHome/issues/1834
