### ISSUE TITLE
[UI] "Заблокировать" and "Разблокировать" buttons overlap the client name

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1953]
Hello,

in the logs section "Заблокировать" and "Разблокировать" buttons overlap the client name:
![image](https://user-images.githubusercontent.com/45385632/88475387-ec21a400-cf37-11ea-9cf8-f0bd8f8dbbd5.png)
Thank you.

Cheers!

**Comment by Eyeborgs** [comment]
Эта так же наблюдается на главной "Панель управления" в разделе "Частые клиенты"..

**Comment by ameshkov** [comment]
This is intended (at least in this iteration of the UI)
