### ISSUE TITLE
[UI] Menu items swap places when they are activated and deactivated:

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1954]
Hello,

menu items every time swap places when they are activated and deactivated:
https://youtu.be/_W5X1G2XHU4

Thank you.

Cheers!

**Comment by IldarKamalov** [comment]
I can't reproduce it, there's no code that can produce this swap

**Comment by ammnt** [comment]
> I can't reproduce it, there's no code that can produce this swap

How i can help you here?

**Comment by IldarKamalov** [comment]
Maybe it's something specific to the browser, what browser is it?

**Comment by ammnt** [comment]
> Maybe it's something specific to the browser, what browser is it?

Safari 13.1.2. I just try to reproduce it in the last version of chrome and there are no issues. Looks like this is actually safari fault🤬
