### ISSUE TITLE
DHCP: automatic hostnames

### ISSUE THREAD

**Issue by AlecRust** [AdguardTeam/AdGuardHome#1956]
### Problem Description

I switched from Pi-hole to AGH recently. Everything was seamless apart from a surprising issue with hostnames. I previously relied on Pi-hole's automatic hostnames to avoid needing to set up static leases on the DHCP server.

For example with Pi-hole my iPhone named "Alec's iPhone" would automatically be available at `alecs-iphone.lan` **without a static lease**. The device would receive a new IP occasionally but always be available at `alecs-iphone.lan`.

To achieve this with AGH it seems I have to do two things for each device:
1. Set up a DHCP static lease. This wasn't necessary on Pi-hole and in some ways defeats the purpose of what I'm trying to achieve. This AGH lease requires a "Hostname" which I originally thought I would be able to ping but it appears not. I'm not sure where this "Hostname" is actually used.
2. Add a custom filtering rule like below. It appears _this_ is where the hostname is actually defined, allowing me to `ping alecs-iphone.lan`. But it also means that any requests through this rule show as "blocked" in my stats.

    ```
    192.168.1.15 alecs-iphone.lan
    ```

The two required steps for each device and their drawbacks makes trying to achieve my goal not really worth it in AGH, since each device needs a static lease anyway so there's a fixed IP to use. And the impact to the stats make them basically useless (says over 50% of all queries were blocked etc.).

### Proposed Solution

If AGH automatically created resolvable hostnames from the names of devices like Pi-hole that would allow me to remove my static leases and custom filtering rules.

If AGH gave some way to _change_ these device names and the underlying hostname without setting a static lease for the device (similar to how you can name devices in your router) then it would be far better than Pi-hole, and afaik basically make static leases redundant if you only used the hostname to communicate with the device.

### Alternatives Considered

The closest similar request I could find is https://github.com/AdguardTeam/AdGuardHome/issues/783, but not sure this is a duplicate of that.

### Additional Information

I am running the [AdGuard Home Home Assistant Community Add-on](https://github.com/hassio-addons/addon-adguard-home) so don't have easy access to the filesystem to create a file for listing these. And the point of this issue is that a list in a hosts file that needs to be manually maintained shouldn't be necessary.

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1468

**Comment by ameshkov** [comment]
Quick question -- do you use AdGuard's DHCP server?

**Comment by AlecRust** [comment]
@ameshkov yes, I do.

**Comment by ameshkov** [comment]
@szolin do you remember why we limited resolution to static leases only? It sounds perfectly okay to do this for dynamic leases as well.

**Comment by szolin** [comment]
> do you remember why we limited resolution to static leases only?

It's not implemented.  We implemented support for PTR requests only - #1682
