### ISSUE TITLE
[ui] Number of rows in the log section

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1957]
Hello,

please, add a function to select the number of lines on the journal section: 5,10, 25, 50, 100, 200, 250, etc. There are currently very few default rows on this page😩

Thank you.

Cheers!

**Comment by KizunaH** [comment]
see #1915

**Comment by ameshkov** [comment]
Since we're going to implement "infinite scroll" there, this option would be redundant.
