### ISSUE TITLE
Pushbullet Android app is blocked

### ISSUE THREAD

**Issue by truthsword** [AdguardTeam/AdGuardHome#1959]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3

* **Operating system and version:**
  * Docker on Synology 

### Expected Behavior
Pushbullet app works

### Actual Behavior
Pushbullet app blocked. by Blocked by AdGuard Simplified Domain Names filter
||pushbullet.com^

**Comment by ammnt** [comment]
dup:
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/403
