### ISSUE TITLE
Publish privacy policy on front page (README.md)

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#1960]
I found this old issue https://github.com/AdguardTeam/AdGuardHome/issues/393 but it would be useful to be explicit about the privacy policy on the front page of the project (README.md). Somewhat related to https://github.com/AdguardTeam/AdGuardHome/issues/1941 also.

If I install and run this software, does it:
* connect to any servers to report metrics, usage, upload logs, ...
* what all services does it connect to and why
* is the software audited for any security holes given that it can be run on cloud VMs semi-private or open to the world

Others can add to the list of things that should be disclosed.

Thank you!

**Comment by ameshkov** [comment]
I think copy/pasting the privacy policy does not make much sense, but we can compile a short summary and give a link to the full policy as well.
