### ISSUE TITLE
Playable block and unblock buttons

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#1961]
**Two bugs**

1. Someone has added mini game to query log but it haven't mentioned on release notes. ;)
(block, block,.... unblock, unblock.....)
2. Some times unblock doesn't take effect at once same as on old versions and we have to unblock one more time.

**Comment by szolin** [comment]
> Some times unblock doesn't take effect at once same as on old versions and we have to unblock one more time.

When this happens, can you check whether a new rule appears in Custom Rules?
In other words, are you saying that you press Unblock, you *see* a new rule in Custom Rules but it doesn't work?

**Comment by KizunaH** [comment]
> When this happens, can you check whether a new rule appears in Custom Rules?

Yes. rule appear (first unblock).

>In other words, are you saying that you press Unblock, you see a new rule in Custom Rules but it doesn't work?

Yes. unblock then refresh browser tab or open it using private window but unable to visit to the site then need to unblock one more time to solve that. However this doesn't happen always so far.

**Comment by szolin** [comment]
I think that's because you don't give time to AGH to apply new rules?
If you wait a couple of minutes, doesn't the unblocking rule starts to work?

**Comment by KizunaH** [comment]
No. i didn't wait minutes. so far less than minute that goes for move between browser tabs and open new private window. adguardhome running in i3/6GB RAM has device with several other tools and none of applications consume more capacity.
But such problem did not exist on old versions.

**Comment by szolin** [comment]
Please record a debug log the next time this happens.

**Comment by KizunaH** [comment]
@szolin i couldn't reproduce that properly (debug log) then fix the first bug. @ameshkov labels, milestones ;)

**Comment by ameshkov** [comment]
@szolin how do we apply new custom rules? Could it be that at the moment when the filtering engine is reloaded, new custom rules list is already saved? 

@KizunaH I don't get the first bug, what are the steps to reproduce?

**Comment by szolin** [comment]
> Could it be that at the moment when the filtering engine is reloaded, new custom rules list is already saved?

Filtering is always works with the latest version of filtering rules.  If custom rules are updated while the filtering is being restarted, a new restart will be triggered.  In the end, the rules seen in custom rules section are applied.

**Comment by KizunaH** [comment]
![bugr](https://user-images.githubusercontent.com/63988538/89227258-8b652c00-d607-11ea-87d7-80a3d457a30b.gif)

**Comment by KizunaH** [comment]
That mini game came with redesign and still exist on v0.103.3

**Comment by ameshkov** [comment]
Uh, I get it. I'll try not to forget about it in the upcoming redesign. There should be a little different color indication and buttons for rows with this domain after you click "Block"
