### ISSUE TITLE
Use block and delete confirmation window instead rely on the browser

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#1962]
- Client delete.
- Block top client.
- Delete blocklist, whitelist.
- Delete rewrite.
- Clear query log, statistics.

**Comment by ameshkov** [comment]
Could you please explain what do you mean?

**Comment by KizunaH** [comment]
![image](https://user-images.githubusercontent.com/63988538/89103182-d4bc4c80-d44a-11ea-8263-f765d8a1d73d.png)

**Comment by ameshkov** [comment]
@ArtemBaskal just use JS confirm for this:

* `Are you sure you want to delete {NAME}?`
* `Are you sure you want to block {NAME}?`
* `Are you sure you want to clear the query log?`
* `Are you sure you want to clear statistics?`

**Comment by KizunaH** [comment]
Not important?

**Comment by ameshkov** [comment]
@KizunaH we've checked all the listed actions and there's a confirmation window for each one of them

**Comment by KizunaH** [comment]
@ameshkov i checked docker edge build due no hotfix releases but still appear browser window instead adguardhome confirmation window. (checked right now too)

**Comment by ameshkov** [comment]
Wait, we don't want to replace the confirmation dialog with a custom dialog window at least at this point. What's important is to check that this confirmation window is used in these operations.

**Comment by KizunaH** [comment]
I mean about custom dialog window (similar when user add new client or add block list then pop-up application's own window)
Eg: past we used to login to adguardhome through a browser window (same as above screenshot) i couldn't find that FR in closed issues.
 
Basically that enhance adguardhome appearance.

**Comment by ameshkov** [comment]
Tbh I prefer native browser confirmation dialogs in this particular case.
