### ISSUE TITLE
Adguard Home dashboard should resolve client names (easier)

### ISSUE THREAD

**Issue by Tiscan** [AdguardTeam/AdGuardHome#1963]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Problem Description
I have a Upstream DNS server entry like:

[/local/lan/51.10.in-addr.arpa/]10.51.1.1

This **does** allow me to see client names in the dashboard.

This took me a while to figure out. However this isn't very straight forward and isn't required in other software like this.

### Proposed Solution

Still think this would be a good FR to simplify... perhaps have the subnet included like:

[/local/lan/10.51.1.0/]10.51.1.1

Automatically parse the reverse resolve?

Also I don't think the above works for IPV6 but not sure it can.

**Comment by szolin** [comment]
> [/local/lan/10.51.1.0/]10.51.1.1

`10.51.1.0` is not a valid domain name here, so this doesn't follow the correct syntax.

However, in

> [/local/lan/51.10.in-addr.arpa/]10.51.1.1

`51.10.in-addr.arpa` is the correct domain name suffix which includes 10.51.0.0/24 for PTR requests.

We should come up with another, more clear specification for this.  Maybe to use another special character or something.

**Comment by Tiscan** [comment]
Yep that is my point.

It would be great if there was a more straight forward way to do this. I would bet that most installs don't have reverse lookup enabled because of how "complex" this is. I realize it's not complex for all folks but most don't have this level of understanding.

**Comment by ameshkov** [comment]
> We should come up with another, more clear specification for this. Maybe to use another special character or something.

Maybe some setting that allows specifying LAN DNS server?

**Comment by Tiscan** [comment]
Also for those who don't have a LAN DNS server in the DHCP settings for Adguard it would be nice to be able to specify a local search domain.

**Comment by ameshkov** [comment]
Merged with https://github.com/AdguardTeam/AdGuardHome/issues/2704
