### ISSUE TITLE
AdGuardHome not working on Raspberry Pi 3 on a Nest Wi-Fi network

### ISSUE THREAD

**Issue by gserviano7** [AdguardTeam/AdGuardHome#1965]
### Issue Details

* **Version of AdGuard Home server:**
  * <v0.103.3>
* **How did you setup DNS configuration:**
  * <Raspberry Pi 3 is on a static IP, both setup on Pi and using the Google Wi-Fi app I setup Nest Wi-Fi's DNS to Pi's static IP>
* **If it's a router or IoT, please write device model:**
  * <Raspberry Pi 3 and Nest Wi-Fi Router>
* **Operating system and version:**
  * <Raspberry Pi OS, Android 10, WIndows 10>

### Expected Behavior
<I setup AdGuardHome on Raspberry Pi 3, updated my Nest Wi-Fi's DNS settings to the Pi's IP address, and then updated AdGuardHome to block eBay, so I expected all of my devices connected to the same Wi-FI network to not be able to access eBay.>

### Actual Behavior
<All devices are still able to access eBay.>

**Comment by szolin** [comment]
> and then updated AdGuardHome to block eBay

How exactly did you do that?  via "Blocked services" ?
What URL you're accessing?

**Comment by gserviano7** [comment]
I did it via Blocked Services. I am using ebay.com to test.

**Comment by szolin** [comment]
Could you please execute `nslookup ebay.com` on your computer and post here what it prints?

**Comment by gserviano7** [comment]
[image: image.png]

Note that I am on a VPN for work, and my Pixel 3 phone also is able to
connect to eBay.

Yours sincerely,

Genesis Serviano

**Comment by szolin** [comment]
> [image: image.png]

Your image was not uploaded properly.

**Comment by gserviano7** [comment]
Non-authoritative answer:
Name: ebay.com
Addresses: 66.135.196.249 | 66.135.195.175

Yours sincerely,

Genesis Serviano

**Comment by szolin** [comment]
OK, buf is the address of DNS server that nslookup prints equal to IP address of AGH?

**Comment by gserviano7** [comment]
I disconnected from my VPN. The DNS address listed is the same as my
Raspberry Pi's IP address. But when I switch to my VPN, it shows something
else.

Yours sincerely,

Genesis Serviano

**Comment by gserviano7** [comment]
So it looks like my laptop is blocked to eBay as I setup on AGH. How can I
test that the ad filtering is working?
Unfortunately I am still able to access eBay on my smartphone.

Yours sincerely,

Genesis Serviano

**Comment by szolin** [comment]
> But when I switch to my VPN, it shows something else.

This means you're not using AGH, that's why ebay isn't blocked.

**Comment by szolin** [comment]
> How can I test that the ad filtering is working?

You can request any domain which is blocked by your filters.  If you're using AGH, the domain will be blocked.

**Comment by gserviano7** [comment]
So how do I set up AGH correctly so I will be using AGH on all of my
network's connected devices, both phones and laptops?

Yours sincerely,

Genesis Serviano

**Comment by szolin** [comment]
That depends on your specific configuration, I can't help you with that.
You should configure your devices to use AGH IP address as DNS server.

**Comment by gserviano7** [comment]
Simon. Why was this closed? I'm still experiencing issues.

**Comment by szolin** [comment]
But are those issues related to AGH?  I wish I could help you but how can I know how to setup DNS server for your VPN?  I guess this is the question you need to ask your VPN provider?

**Comment by KizunaH** [comment]
@gserviano7 Here you go #1769 (vote and comment on it)
This's additional fever to developers ;)

**Comment by gserviano7** [comment]
Thank you
