### ISSUE TITLE
Unable to pull arm64 version of Adguardhome

### ISSUE THREAD

**Issue by panks21** [AdguardTeam/AdGuardHome#1966]
### Issue Details

Running Adguard home on ubuntu18.04 on Raspberry Pi 4. But now I am not able to pull the latest arm64-image

root@pghome_pi4:~# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
adguard/adguardhome   arm64-latest        64c45c4be3e7        2 months ago        47.1MB
root@pghome_pi4:~# docker pull adguard/adguardhome:arm64-latest
arm64-latest: Pulling from adguard/adguardhome
Digest: sha256:bebe974ba64b28881db15052b6f6fe1c9bc71ee2b5882c20f9c5a62cca61ca6e
Status: Image is up to date for adguard/adguardhome:arm64-latest
docker.io/adguard/adguardhome:arm64-latest

**Comment by emlimap** [comment]
Starting with 0.103, they do multiarch builds. So you just need to drop the `arm64-` and the command would be.

```
docker pull adguard/adguardhome:latest
```

Docker will automatically pull the correct architecture for the system it is running on

```Instead of a multitude of arch-specific tags, we now publish multi-arch images to Docker Hub. So if you were using some arm64-latest tag, don't do that anymore and simply switch to latest.```

https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.103.1

**Comment by panks21** [comment]
Great. That solves it. However the version on the dashboard still shows as 0.102.0
