### ISSUE TITLE
DNS rewrites priority

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1967]
- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
- [x] I checked the documentation and found no answer

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Actual Behavior
I have two IPv4 for my domain (DoT/DoH) - it needs me to have two connection endpoints in the same time. But due to the fact that only one of the address can be specified in the /etc/hosts file - whether one connection endpoint is used.

This address is also displayed as DNS rewrites in the log. You can disable this at the server level only temporarily - until the next reboot.

To solve this problem, I added two records for these two IPv4 for one domain in the "DNS rewrites" section. Now everything is working fine and _nslookup_ output returns me both IPv4 for one domain, and the /etc/hosts file is ignored as expected. But there are no more rewrites events in the log. So, I feel like here something is wrong:
1. These DNS rewrites should be in the journal (UI issue);
2. Users must somehow understand which record(s) will be in priority.

Please, advise!🤯

Thank you.

**Comment by szolin** [comment]
I've just added 2 rewrite entries and they appear in Query log.
Are you sure your nslookup asks the correct AGH server and are you sure you have reloaded query logs page?

> Users must somehow understand which record(s) will be in priority.

This is obvious - the first IP in Rewrites list will be the first in response.

**Comment by ammnt** [comment]
Works fine now. Thanks
