### ISSUE TITLE
Custom Quick Filter

### ISSUE THREAD

**Issue by abdalians** [AdguardTeam/AdGuardHome#1969]
I am trying to add a quick filter in dnsfilter/blocked_services.go like this.. 
`        {"kids", []string{"||*.com^$ctag=user_child", "||*.net^$ctag=user_child", "||*.org^$ctag=user_child", "||*.ca^$ctag=user_child", "||*.co^$ctag=user_child"}},`

and once compiled, it shows up under Filter > Blocked Services but turning it on doesnot filter the requests. What am I missing? 

Thanks

**Comment by szolin** [comment]
Did you test these rules in `custom filtering rules` section?

**Comment by ameshkov** [comment]
1. In order for ctag-rules to work, you need to also add tags to your clients.
2. Maybe it'd be easier to simply use custom filtering rules to achieve the same. You can either use $ctag or simply use $client modifier: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#-client

**Comment by abdalians** [comment]
The rule works if I add it to custom filtering rules. I was simply trying to have a quick filter as a starting point and eventually add a way to allow the ability to create a custom quick filter.

**Comment by ameshkov** [comment]
@szolin could it be that we don't use client info when "blocked services" are being matched?

**Comment by szolin** [comment]
Oh, `$ctag` modifiers don't work in `dnsfilter/blocked_services.go` - this is just for blocked services feature.

**Comment by abdalians** [comment]
Ah ok thanks another way to achieve this with  different tag perhaps client ?

**Comment by szolin** [comment]
No, it would require additional code to handle those modifiers.
This case is just not supported - there's a task about custom blocked services here somewhere - you may want to upvote it.

**Comment by ameshkov** [comment]
I am not sure what exactly you are trying to achieve.

You could simply keep these rules in the custom filtering rules OR in a separate file and simply use ctag to define to which client groups the rules are applied. I just don't understand what's the point in using both ctag and blocked services.

**Comment by abdalians** [comment]
The point is a single click block for all the devices tagged such as children... to certain / all services when they say won't do their chores and want to watch TV. The quick filters are an easy way to achieve this.. how else can this be done ?

**Comment by ameshkov** [comment]
1. Create a blocklist that does this, add these rules there
2. Add this blocklist in the DNS blocklists settings
3. You'll be able to quickly check/uncheck that list

**Comment by abdalians** [comment]
ok thanks
