### ISSUE TITLE
ubuntu 68 in use

### ISSUE THREAD

**Issue by lukasa1993** [AdguardTeam/AdGuardHome#1970]
trying to run docker image on ubuntu 20, cant figure out whats using 68/udp port if i don't open that port for docker everything runs perfectly but i wonder what its for and how i can actually open it

**Comment by szolin** [comment]
> i wonder what its for

Did you try to google?  It's for DHCP

> how i can actually open it

https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#-running-dhcp-server

**Comment by ameshkov** [comment]
You may simply remove that port mapping and it will work just okay. If you don't plan to use DHCP, this is perfectly okay.

**Comment by lukasa1993** [comment]
okay thank you
