### ISSUE TITLE
Call to AdGuard API "disable_url" removes URL and name instead of disabling it.

### ISSUE THREAD

**Issue by mostlychris** [AdguardTeam/AdGuardHome#1971]
### Issue Details

* **Version of AdGuard Home server:**
  2.5.0
* **How did you setup DNS configuration:**
  Using Home Assistant in a Docker Container
* **Operating system and version:**
  Ubuntu 18.04

### Expected Behavior
When calling "disable_url" it should uncheck the box and disable the url in the block list settings.

### Actual Behavior
The name and URL are removed from the block list, leaving a dash for the name and zero for the rules count. This prevents re-enabling the same URL again using the "enable_url" call since the URL has been blanked out.

### Screenshots
<details><summary>Screenshot:</summary>

<img width="681" alt="2020-07-30 06_55_48-AdGuard Home - Home Assistant" src="https://user-images.githubusercontent.com/3884025/88920069-cf37ea00-d231-11ea-85fc-703d95ed40ee.png">

**Comment by szolin** [comment]
> Using Home Assistant in a Docker Container

I think you're reporting a bug to an incorrect repository.
We don't have "disable_url" API.
Our API looks like this:

```
	POST /control/filtering/set_url

	{
	"url": "..."
	"whitelist": true
	"data": {
		"name": "..."
		"url": "..."
		"enabled": true | false
	}
	}
```
