### ISSUE TITLE
Failure to start after snap install

### ISSUE THREAD

**Issue by hegleran** [AdguardTeam/AdGuardHome#1975]
I'm running Ubuntu 20.04. I performed a snap install of adguard-home. After completion I started adguard-home by running /snap/adguard-home/606/AdGuardHome. I walked through the initial setup steps in the web interface - binding the appropriate interface and port for the web admin page, and binding the appropriate interface and port for dns listening. I was then able to succesfully log in to the dashboard. Once that completed I installed as a service via sudo ./AdGuardHome -s install. I wanted to test that the service would start on boot, and as such rebooted. I see in syslog the multiple failed attempts to start AdGuardHome. 
Jul 30 15:54:55 pc systemd[1]: AdGuardHome.service: Failed with result 'exit-code'.
Jul 30 15:55:05 pc systemd[1]: AdGuardHome.service: Scheduled restart job, restart counter is at 27.
Jul 30 15:55:05 pc systemd[1]: AdGuardHome.service: Main process exited, code=exited, status=1/FAILURE

When attempting to start AdGuardHome manually, I see:

me@pc:/snap/adguard-home/606$ sudo ./AdGuardHome 
2020/07/30 15:53:26 [error] Couldn't read config file /snap/adguard-home/606/AdGuardHome.yaml: open /snap/adguard-home/606/AdGuardHome.yaml: no such file or directory
2020/07/30 15:53:26 [info] AdGuard Home, version 0.103.3, channel release, arch linux amd64
2020/07/30 15:53:26 [info] This is the first time AdGuard Home is launched
2020/07/30 15:53:26 [info] Checking if AdGuard Home has necessary permissions
2020/07/30 15:53:26 [info] AdGuard Home can bind to port 53
2020/07/30 15:53:26 [fatal] Cannot create DNS data dir at /snap/adguard-home/606/data: mkdir /snap/adguard-home/606/data: read-only file system

I'm not sure why the snap install of adguard-home would not have all of the permissions needed in /snap/adguard-home. Any ideas on how I can resolve? Please let me know of any additional information I can provide.

**Comment by ameshkov** [comment]
> Once that completed I installed as a service via sudo ./AdGuardHome -s install

You don't need to do that when running a snap. Snap automatically runs AGH as a daemon.

I guess you should remove the service that you've installed (AdGuardHome -s uninstall) and reinstall the snap just in case.
