### ISSUE TITLE
Ubuntu Appliance auto reboots due to timeout on initial config

### ISSUE THREAD

**Issue by blademan007** [AdguardTeam/AdGuardHome#1977]
### Issue Details

* **Version of AdGuard Home server:**
0.103.3
* **How did you setup DNS configuration:**
IoT
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4 
* **Operating system and version:**
Ubuntu Appliance core18

### Expected Behavior
Expected time to complete network config. 

### Actual Behavior
While moving through fields to completing static IPv4 config, unit rebooted. Following reboot, I quickly entered static config and began to enter values

**Comment by ameshkov** [comment]
You need to report this to Ubuntu: https://help.ubuntu.com/community/ReportingBugs

**Comment by blademan007** [comment]
Ok. I asked Adguard support this same question. The support/forum for the AdGuard Ubuntu appliance could use some clarification. Thanks for the info.

> From: Adguard <support@adguard.com>
> Subject: RE: Support Forum for AdGuard Home Ubuntu appliance
> Date: June 30, 2020 at 10:37:03 PM PDT
> To: xxx
> Reply-To: Adguard <support@adguard.com>
> 
> Hello, xxx! 
> 
> Thank you for reaching out to AdGuard Support! 
> 
> If you have questions about AdGuard Home, please files them on GitHub as separate issues, and our developers will be glad to help. Here's the appropriate repository: https://github.com/AdguardTeam/AdGuardHome/issues
> 
> Let us know should you have any additional questions. Have a great day!
> 
> Best wishes,
> AdGuard Support
> 
> 
> 
> On Tue, 30 Jun 2020 15:56:41 -0700,xxx wrote:
> > Which forum should be used for this appliance https://ubuntu.com/appliance/adguard?
> 
> 
> From: Adguard <support@adguard.com>
> Subject: RE: Re: Support Forum for AdGuard Home Ubuntu appliance
> Date: July 3, 2020 at 4:34:02 AM PDT
> To: xxx
> Reply-To: Adguard <support@adguard.com>
> 
> Hello! 
> 
> Thank you for your feedback! 
> 
> There is no separate thread for AdGuard Home yet, however you can find some answers and ask them yourself here: https://forum.adguard.com/index.php?forums/off-topic.72/
> 
> Let us know should you have any additional questions. Have a great day!
> 
> Best wishes,
> AdGuard Support
> 
> 
> 
> On Wed, 1 Jul 2020 11:57:10 -0700, xxx wrote:
> > Thanks so much.
> > 
> > Is there a forum for AdGuard Home? I didn't see one here:
> > https://forum.adguard.com/index.php
> > 
> > Based on 1 day of use, great appliance. ;)
> >
