### ISSUE TITLE
unable to ssh into Ubuntu AdGuard appliance

### ISSUE THREAD

**Issue by blademan007** [AdguardTeam/AdGuardHome#1978]
### Issue Details

* **Version of AdGuard Home server:**
0.103.3
* **How did you setup DNS configuration:**
IoT
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4
* **Operating system and version:**
 Adguard Ubuntu appliance

### Expected Behavior
ssh login using ubuntu creds as [documented here](https://ubuntu.com/appliance/adguard/raspberry-pi).

### Actual Behavior
login fails

### Additional Information
Tried using shorter less complex password, and login still fails.

**Comment by ameshkov** [comment]
I am sorry but it seems this is a question for Ubuntu and Canonical, not us.
