### ISSUE TITLE
Send frequently accessed domain query request again before cache expire

### ISSUE THREAD

**Issue by nzm001** [AdguardTeam/AdGuardHome#1980]
'Smartdns will send domain query request again before cache expire, and cache the result for the next query. Frequently accessed domain names will continue to be cached.' from https://github.com/pymumu/smartdns/blob/master/ReadMe_en.md

I wonder if we can make use of our 90 days log in AdGuardHome. If I frequently accessed a certain site in past 90 days, then this cache is going to be cached before it expires and be automatically overrided with a long ttl (an hour) to reduce cpu usage.

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1259
