### ISSUE TITLE
Blocked services upgrade

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1981]
Openwrt x64 in mini PC
Hope adguardhome upgrade to add blocked services in China.
http://www.xunlei.com/

https://www.bytedance.com/,https://www.douyin.com/,https://www.toutiao.com/,https://www.tiktok.com/,https://www.ixigua.com/,https://www.helo-app.com/,https://www.larksuite.com/,http://www.babe.co.id/

https://www.tencent.com/,http://www.qq.com/,http://www.wechat.com/

http://www.uc.cn/,https://www.taobao.com/,http://www.ddchong.com/,http://www.youku.com/,http://www.tudou.com/.https://www.etao.com/,https://www.tmall.com/,https://www.dingtalk.com/,http://www.1688.com,http://www.xiami.com,https://www.alipay.com/,https://www.laiwang.com/

https://www.unionpay.com/

http://www.le.com/
http://www.iqiyi.com/
https://www.baidu.com/
https://www.sogou.com/
www.micropoint.com.cn
http://www.filseclab.com/

https://www.360.cn/,https://www.so.com/

https://www.ijinshan.com,http://www.cmcm.com/,https://www.duba.com/

http://www.jiangmin.com/
http://www.immomo.com/

http://www.rising.com.cn/,http://www.ikaka.com/

https://www.ntuiw.com/
http://www.ntuiw.cc/
http://www.shadplus.com/
https://www.2016ruanwen.com/

weather website

Hope the edge channel upgrade quickly.
Thank you!

**Comment by KizunaH** [comment]
@jkle112 what are these all about and the purpose for block that local friendly companies domains?
However don't be too aggressive with china as western countries make sound.

You can add local blocklist through add blocklist > add a custom list > enter local file path or wait for #1692

AGH already has added `douyin.com`, `toutiao.com`, `tiktok.com` - tiktok and personally i dont see specific reason for add rest of services you mentioned above and most are only popular inside country.

**Comment by KizunaH** [comment]
@jkle112 You can add local blocklist through add blocklist > add a custom list > enter local file path or wait for #1692 (with #951)
However don't be aggressive with china as other countries make sound. If add them then it's necessary put other giant competitors into blocked services.
Eg: unionpay - visa, master, american express
Eg: baidu - google, bing, yandex, startpage
Eg: 360/ filseclab - symantec, avast, eset, mcafee

AGH already has added `douyin.com`, `toutiao.com`, `tiktok.com` - tiktok and personally i dont see specific reason for add rest of services you mentioned above and some are only popular inside country. In this cause, that force local people to use foreign companies.

**Comment by jkle112** [comment]
Not only these websites, need block services, that have most subnet or different domains.

**Comment by szolin** [comment]
I agree with @KizunaH , it seems like a dup of #1692
