### ISSUE TITLE
DNS-over-TLS - "broken pipe" errors

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1986]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Actual Behavior
Regardless of the client resolver sometimes I have a "broken pipe" error withins a few minutes. At this time, no one domain will be resolved for the network clients😤As I understood this error concerns only the DoT protocol.

### Screenshots
<summary>Here is no verbose log screenshot:</summary>
<details>

![image](https://user-images.githubusercontent.com/45385632/89124778-4398b480-d4e2-11ea-8773-98b78417308b.png)

</details>

<summary>But looks like DNS processing works fine and the records has returned:</summary>
<details>

![image](https://user-images.githubusercontent.com/45385632/89124915-43e57f80-d4e3-11ea-9f6d-132670279d61.png)

</details>

### Additional Information
I will try to catch this moment with verbose log. What other data will be needed to solve this problem?

P.S.: I had the same error with Stubby resolver. I am now using the built-in Keenetic resolver. Therefore, it's about the server part, not the client🤔

P.P.S.: There is no such error if I use NextDNS directly or if I use the DoH protocol🤨

Thank you.

**Comment by ameshkov** [comment]
I'd really like to see the verbose log

**Comment by ammnt** [comment]
@ameshkov, it happened again yesterday. The [verbose log](https://github.com/AdguardTeam/AdGuardHome/files/5014225/log.txt) is attached. Please, look at what happened at 19:15 with the **external.fhel4-1.fna.fbcdn.net** host and its cname **scontent.fhel4-1.fna.fbcdn.net**. 

As far as I understand, the server received records for these hosts, but due to handshake problems or something like that this information does not reach to the clients resolver😬

Thank you.

**Comment by ameshkov** [comment]
It just means that the client closed the connection so AGH just cannot write an answer.

Not sure why this happens, but I am pretty sure this is not an AGH bug.
