### ISSUE TITLE
Option for logging AGH's own DNS requests.

### ISSUE THREAD

**Issue by adamgibbo** [AdguardTeam/AdGuardHome#1990]
**_Problem Description_**
AdGuard Home does make DNS requests itself, but does not show on the query log.

**_Proposed Solution_**
In the interests of openness, please allow an option for logging of AdGuard Home's DNS requests

**_Alternatives Considered_**
Understandably AdGuard Home makes a lot of requests due to safebrowsing. Perhaps make this a disabled by default option or enabled in .yaml file only.

**Comment by ameshkov** [comment]
@szolin is it easy to do or not? Tbh, there's always a simple solution - write this to the regular log file.

> Understandably AdGuard Home makes a lot of requests due to safebrowsing

It makes many requests, but not DNS requests. Once the domain name is resolved, it's cached and not queried anymore.

**Comment by adamgibbo** [comment]
Even though this specific request is for AGH. This is also something that I'd thought about with AdGuard for Android too. I think the log should show **ALL** DNS requests.

**Comment by szolin** [comment]
Let's first define explicitly what is "Query Log".
As I understand it's a log of requests AGH receives from the outside (i.e. a client connects via TCP or UDP and sends a DNS request to AGH) and processes according to its configuration.
Of course we can add anything there, including our own direct requests to upstream servers and requests to family.adguard server.  But if we do so, my understanding of "Query Log" becomes incorrect, then let someone define what is "Query Log".

**Comment by ameshkov** [comment]
Well, I kinda agree. I think internal queries should go to the regular log, not the query log
