### ISSUE TITLE
AdGuard browsing security web service is too slow😭

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#1991]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * VPS
* **Operating system and version:**
  * Debian 9

### Actual Behavior
As we understood in https://github.com/AdguardTeam/AdGuardHome/issues/1982, AdGuard browsing security web service slows down DNS queries too much. Only one way to fix this - disable this service completely.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/45385632/89106800-7173ef80-d435-11ea-9ee2-a1c1fc441cff.png)

![image](https://user-images.githubusercontent.com/45385632/89102359-1203e880-d411-11ea-8968-ddb10c82cf4f.png)

</details>

### Additional Information
AdGuard browsing security web service is one of two reasons I use AdGuard Home😭This is also related us to https://github.com/AdguardTeam/AdGuardHome/issues/1658. Please find a way to fix this and increase the speed of processing queries when this service is enabled.

Thank you.

**Comment by ameshkov** [comment]
Not a bug

**Comment by ameshkov** [comment]
There's a visible slowdown in the last couple of days due to not ideal routing to DNS servers, we'll resolve it soon.

However, I'd like to stress that the safebrowsing responses are cached by AGH and this overhead is only present for the first query to a domain.

**Comment by gitthangbaby** [comment]
i measured +200ms for each api feature today.
is there any benefit of API over simply adding a blocklist (malware, kid oriented) or using family DNS servers? i ran check of 100s of domains compared to other local and remote DNS services, and the slow down is as stated: massive, and it feels the same way on the devices.
i isolated vulnerable users into a group with the API turned on. However the Clients table in the main window start showing the corresponding client name instead of device name which is pretty inconvenient (i definitely prefer the device name from ARP/rDNS).

**Comment by lordraiden** [comment]
> There's a visible slowdown in the last couple of days due to not ideal routing to DNS servers, we'll resolve it soon.
> 
> However, I'd like to stress that the safebrowsing responses are cached by AGH and this overhead is only present for the first query to a domain.

Why don't you store the "AdGuard browsing security" blocklist locally in our adguard installations? In case you don't want to share the IOCs you can maybe store it encrypted.

**Comment by ameshkov** [comment]
Unfortunately, I am not aware of any way that would allow encrypting the lists and using them without decrypting locally.

**Comment by terual** [comment]
> Unfortunately, I am not aware of any way that would allow encrypting the lists and using them without decrypting locally.

Why would you decrypt the list locally? You could hash the domain under scrutiny, and then check against the pre-downloaded list of hashes.
