### ISSUE TITLE
Fastest IP address Related configuration

### ISSUE THREAD

**Issue by wysnxzm** [AdguardTeam/AdGuardHome#1992]
Provide dns response timeout settings and ip response timeout settings, the current timeout seems to be 10 seconds

**Comment by lordraiden** [comment]
Considering that the timeout is 10 seconds and it looks like an easy fix shouldn't this be addressed earlier?

**Comment by wysnxzm** [comment]
> Considering that the timeout is 10 seconds and it looks like an easy fix shouldn't this be addressed earlier?

I think the DNS timeout should be within 200ms
IP response timeout is within 600ms
However, you also need to consider the worst case, that is, all DNS timeouts and IP timeouts. At this time, you should choose an IP with a relatively fast response. This may exceed the set timeout period.

**Comment by wysnxzm** [comment]
> @wysnxzm, the latest edge build should provide the desired functionality. It's described in [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file). In brief, `AdGuardHome.yaml` configuration file now has the new `FastestTimeout` setting. It defines the timeout for pinging the resolved addresses, so that pinging process won't take more than it.
> The timeout for used upstreams, however, is already configurable with the `upstream_timeout` setting.

Thank you. Love you

**Comment by EugeneOne1** [comment]
@wysnxzm, would you like to test it before closing the issue?

**Comment by wysnxzm** [comment]
> @wysnxzm, would you like to test it before closing the issue?

no problem

**Comment by EugeneOne1** [comment]
@wysnxzm, any updates since?  Can we close the issue?

**Comment by wysnxzm** [comment]
> @wysnxzm, any updates since? Can we close the issue?

Very good. I don't see any problems
