### ISSUE TITLE
Reverse DNS Queries

### ISSUE THREAD

**Issue by damooooooooooh** [AdguardTeam/AdGuardHome#1993]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * Version: 0.103.3
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * Raspberry Pi OS Lite (Debian)

### Expected Behavior
I'm seeing a number of reverse DNS lookup for LAN.  i.e. 10.1.168.192.in-addr.arpa and these are being sent to the external DNS provider set in my configuration.  Local Reverse DNS should not leak onto the internet?

### Actual Behavior
Local Reverse DNS should stay on LAN

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by szolin** [comment]
Do you use AGH's DHCP server and is that IP address is a DHCP lease address?

**Comment by damooooooooooh** [comment]
Hi there, no I do not use the AGH DHCP server.  My router manages DHCP on the local LAN and assigns devices that use AGH with AGH IP address as the DNS server.

The origin of the DNS query appears to be the AGH instance itself and the queries seem to lookup only to the devices that are using AGH as the DNS server.  AGH seems to perform a DNS lookup of all these devices every 10 mins to the second.

**Comment by szolin** [comment]
Please read this section https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-rdns
I think you need to redirect the requests to `192.in-addr.arpa` to another server (or a non-existing server).

**Comment by damooooooooooh** [comment]
Ok that has resolved it, thank you for all the hard work on this great product
