### ISSUE TITLE
[Feature request] Custom DoH, API and Dashboard endpoints

### ISSUE THREAD

**Issue by JoseGalRe** [AdguardTeam/AdGuardHome#1997]
### DoH

> ### Problem Description
> Currently the path "/dns-query" is being used for to call all queries
> ### Proposed Solution
> Allow the user to customize the path
> ex: https://mysecretweb/mysupersecretquerypath

### Dahsboard and API
> ### Problem Description
> Currently the path "/" is being used for the dashboard, and this is great but,
> in a vps anyone can know that an instance of adguardhome is running,
> a way to "hide" is using security by obscurity, allowing to the user to customize the path
> ### Proposed Solution
> Allow the user to customize the path
> ex: https://mysecretweb/mysupersecretdashboardpath
> and maybe show some error like NXDOMAIN on "/" path

### Notes
> Similar to https://github.com/AdguardTeam/AdGuardHome/issues/1996

**Comment by szolin** [comment]
> in a vps anyone can know that an instance of adguardhome is running,

Do you run AGHome on a standard port 443?  In that case, "anyone can know that an instance of adguardhome is running".
You can setup a reverse proxy which will rewrite paths as you want.

**Comment by JoseGalRe** [comment]
> > in a vps anyone can know that an instance of adguardhome is running,
> 
> Do you run AGHome on a standard port 443? In that case, "anyone can know that an instance of adguardhome is running".
> You can setup a reverse proxy which will rewrite paths as you want.

Yeah i running DoH on 443 port by privacy

And with a reverse proxy, I would have to use an external tool,
and it might be easier for a normal user to just adjust the path in settings,

in addition, using httpd, nginx, etc, is to use more resources of the vps,
and some "basic" vps have little ram,
and even these tools are "light" having 10 or 20 free MiBs in RAM could be good

**Comment by szolin** [comment]
> having 10 or 20 free MiBs in RAM could be good

10 mb for nginx is not a huge price for safety and speed that you get from it.  Actually it might save you some RAM if you disable encryption in AGH altogether - you won't need it if you setup nginx to do all the TLS stuff.

**Comment by JoseGalRe** [comment]
> if you disable encryption in AGH altogether - you won't need it if you setup nginx to do all the TLS stuff.

but if encryption is disabled, DoH will no longer be available?

**Comment by szolin** [comment]
DoH will be available via nginx:

`You --(DoH)-> nginx --(unencrypted HTTP)-> AGH`

You can set `allow_unencrypted_doh: false` in yaml config

**Comment by JoseGalRe** [comment]
> DoH will be available via nginx:
> 
> `You --(DoH)-> nginx --(unencrypted HTTP)-> AGH`
> 
> You can set `allow_unencrypted_doh: false` in yaml config

I will definitely try this, thanks for the tip,

if couldn't add the custom endpoints natively,
maybe could add a how to guide in the wiki with nginx settings

**Comment by szolin** [comment]
It's already online! :)
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy

**Comment by JoseGalRe** [comment]
> It's already online! :)
> https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy

I had seen it but it doesn't mention of `allow_unencrypted_doh` for DoH
and checking the repo after your comment I find on line 101 of (home/config.go)...
`Allow DOH queries via unencrypted HTTP (e.g. for reverse proxying)` 😅 

it would be nice to add this also to the wiki 😄

**Comment by szolin** [comment]
> it would be nice to add this also to the wiki

done
