### ISSUE TITLE
Webinterface not working well with nginx proxy

### ISSUE THREAD

**Issue by PurifyPioneer** [AdguardTeam/AdGuardHome#1999]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * "v0.103.3" (Docker)
* **How did you setup DNS configuration:**
  * Router provides adress of adguard dns via dhcp
* **If it's a router or IoT, please write device model:**
  * Router is Fritz-Box 7590, Adguard Host is Raspberry Pi 4 running docker
* **Operating system and version:**
  * Raspbian GNU/Linux 10 (buster)

### Expected Behavior
When accessing "hostname/adguard/" i expect to receive the login page under the same url.

### Actual Behavior
Accessing "hostname/adguard/" redirects to "hostname/login.html" instead of "hostname/adguard/login.html". 

### Screenshots
![2020-08-05 20_56_47-Cmder](https://user-images.githubusercontent.com/4218214/89458465-5b349f00-d767-11ea-9783-887126eb2527.png)
Nginx-Configuration

### Additional Information
Changing the url manually to "hostname/adguard/login.html" after being redirected does show the login page.
Once logged in the webinterfaces works as expected.

I tried some nginx options like rewrites but i have the feeling that adguard is doing some internal redirect when not beeing logged in.

I appreciate any help and want to say thanks for the otherwise great piece of software!

**Comment by szolin** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy
