### ISSUE TITLE
[Feature request] Up/downtime monitor page

### ISSUE THREAD

**Issue by JustHmmmm** [AdguardTeam/AdGuardHome#2002]
### Problem Description

 - I'm running AdGuardHome on my VPS. Just for personal use. But I think AdGuardHome should have up/downtime page. And calculate uptime percent.
### Proposed Solution

 * I think AdGuard team should add up/downtime monitor page to AdGuardHome. It like [https://www.githubstatus.com/](https://www.githubstatus.com/)

**Comment by ameshkov** [comment]
Well, AdGuard Home is not a centralized service so we cannot make a status page for it.

You can make one yourself using a service like status statuspage.io, it provides different ways to poll the service status automatically.

**Comment by KizunaH** [comment]
@JustHmmmm Several uptime monitoring services (statuspage.io paid)

Free service with rebrand, custom domain facility.
https://uptimerobot.com/pricing/
https://blog.uptimerobot.com/status-pagescustom-domains-are-now-https-enabled/

Free uptime monitoring service with more advanced features.
https://www.site24x7.com/

**Comment by JustHmmmm** [comment]
I'm using Instatus to create Status page. Btw, thanks for your information.
