### ISSUE TITLE
[Feature request] Block clients in Client setting

### ISSUE THREAD

**Issue by JustHmmmm** [AdguardTeam/AdGuardHome#2004]
### Problem Description

It uncomfortable when go to Client settings and comeback to DNS settings to block unwanted user. 
### Proposed Solution

I think add block/unblock button at Client settings is good solution for this.

**Comment by GOODTESTA** [comment]
You can specify your country IPs in CIDR.
That can block all unwanted client and more safe.
![image](https://user-images.githubusercontent.com/35817374/89663544-44797e00-d908-11ea-8cdc-6d03e485c604.png)

**Comment by JustHmmmm** [comment]
Thanks for your information <3
