### ISSUE TITLE
Communicate with google DNS even its not defined  

### ISSUE THREAD

**Issue by k1ng440** [AdguardTeam/AdGuardHome#2006]
### Prerequisites

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.3
* **How did you setup DNS configuration:**
  * Router provides the address of adguard dns via dhcp or force redirect
* **If it's a router or IoT, please write device model:**
  * pfsense, adguard home on windows 10
* **Operating system and version:**
  * Windows 10 2004

### Expected Behavior
should only communicate with defined upstream servers

### Actual Behavior
communicating with google DNS during reverse DNS lookup

### Screenshots
https://puu.sh/GfzXG/cb25a57e38.png

**Comment by szolin** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by ameshkov** [comment]
Could it be that at the moment when this query was sent, Google DNS was set as upstream?
