### ISSUE TITLE
Donations to World Food Programme blocked...

### ISSUE THREAD

**Issue by truthsword** [AdguardTeam/AdGuardHome#2008]
![](https://i.imgur.com/HLQO73U.png)
![](https://i.imgur.com/3nkQ7sG.png)
data/adguard-simplified/list.txt
AdGuard Home version v0.103.3

**Comment by JustHmmmm** [comment]
Just remove that rule. It is not AdGuardHome's issue.

**Comment by RonKhondji** [comment]
Well, it is in AdGuard's DNS filter list.

As a work arround you can add:
@@||iraiser.eu^$important
to your 'custom filtering rules'.

**Comment by truthsword** [comment]
I did that however this site does not belong in the filter list. How does that get corrected?

**Comment by RonKhondji** [comment]
Maybe [https://github.com/AdguardTeam/AdGuardSDNSFilter/issues](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues) is the best place.
Though I think that leaving it here for the devs to find it will work just as well.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #419](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/419) via [**ZenHub**](https://www.zenhub.com/)
