### ISSUE TITLE
[Questions] Docker deployment

### ISSUE THREAD

**Issue by boxav** [AdguardTeam/AdGuardHome#2009]
[1] https://hub.docker.com/r/adguard/adguardhome
`docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 80:80/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp -d adguard/adguardhome`

You should create a data directory on a suitable volume on your host system, e.g. /my/own/workdir, and a config directory on a suitable volume on your host system, e.g. /my/own/confdir.

Can you provide me actual host system example (full path) so i can understand this.

[2] I use adguardhome for LAN computers and i dont like to assign separate LAN IP for the docker (like virtualbox bridge mode) so now it depend on the device IP(host system 192.168.0.105) and docker ip (172.17.0.1)
If i set host system (this pc also use for daily works) IP as dns server address in other computers then all devices call to the physical machine (not to the docker instance directly). is there way to accomplish this without setting separate LAN IP to docker?

problem, i have a simple isp router with public ip so i doubt to expose separate LANs. its good chance for someone to break my home easily (i dont know to cover such docker instance using host system linux firewalls)

**Comment by ameshkov** [comment]
> Can you provide me actual host system example (full path) so i can understand this.

Well, any folder anywhere can be mapped. For instance `/opt/adguardhome` is a valid path as well.

> problem, i have a simple isp router with public ip so i doubt to expose separate LANs. its good chance for someone to break my home easily (i dont know to cover such docker instance using host system linux firewalls)

Why do you think your host system has a public IP? `192.168.0.105` is a private LAN API.

**Comment by boxav** [comment]
> Why do you think your host system has a public IP? `192.168.0.105` is a private LAN IP.

No. i know 192.168.0.105` is a private LAN IP.

Currently docker instances have own `172.17.0.0/16` (Not something like `192.168.0.105` provide by the home router)
And that PC ip address is `192.168.0.105` and i mean i dont like to assign separate LAN IP address to the docker instance (eg: `192.168.0.106`)

Public IP has for my internet connection. :/

I mean i afraid to set up separate LAN IP `192.168.0.106` for the docker instance (as bridge to host network similar virtualbox bridge mode) then i dont know to cover it using host system linux firewall.

So i mean any proper solution for that? also considering recent comment.

**Comment by ameshkov** [comment]
I just don't understand why would you need to have a separate IP for your Docker instance.

Mapped ports are already available on the IP of your host machine

**Comment by boxav** [comment]
i think it's ok rather than advanced set up. thank you

**Comment by boxav** [comment]
> I just don't understand why would you need to have a separate IP for your Docker instance.
> Mapped ports are already available on the IP of your host machine

It doesn't see the LAN IP. How to fix?
(Installed docker and ran above deployment command only)

![Screenshot from 2020-08-11 09-37-09](https://user-images.githubusercontent.com/69413450/89851275-4ec0a400-dbb6-11ea-9069-582ce5cbfd3c.png)

**Comment by boxav** [comment]
This video i see they create bridge to host network (similar virtualbox bridge) https://youtu.be/oWASrVZPKbE?t=462 (i dont use such GUI application, only terminal) and i dont know if that the only way for solve this problem.

**Comment by ameshkov** [comment]
> It doesn't see the LAN IP. How to fix?

You can't see the real network from inside the Docker container unless you run it with `--net host` (which is a whole different topic).

Please note, that local ports will still be mapped and available on your host IP as well.

**Comment by ameshkov** [comment]
> This video i see they create bridge to host network (similar virtualbox bridge)

Do they explain why they need it? This is definitely not a mandatory step

**Comment by boxav** [comment]
> > This video i see they create bridge to host network (similar virtualbox bridge)
> Do they explain why they need it? This is definitely not a mandatory step

I just searched if there any way to solve it myself till get reply from adguard. lol



> > It doesn't see the LAN IP. How to fix?
> 
> You can't see the real network from inside the Docker container unless you run it with `--net host` (which is a whole different topic).
> Please note, that local ports will still be mapped and available on your host IP as well.

"unless you run it with `--net host` " - not necessary
Thank you :+1:
