### ISSUE TITLE
Filter Rules unblock does not take effect correctly

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdGuardHome#2010]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.3
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 B+
* **Operating system and version:**
  * Raspbian Buster

### Expected Behavior

The rules created by users or other filter list with $important should have the higher priority to unblock or blocking the domain. 

Example: 
AdGuard DNS filter(||gm99.com^)
Third Party Filter List(@@||gm99.com^$important)
Custom filtering rules(Default Unblock list in AGH with @@||gm99.com^$important)

@@||gm99.com^**$important** in **Custom filtering rules** or **Third Party Filter List** should have higher priority than ||gm99.com^ in **AdGuard DNS filter**

and

AGH should be able to unblock and mark the dns query to this domain as allowed and reply the query to devices as normal

### Actual Behavior

The AGH mark the unblocked domain with allowed but it return an address of 0.0.0.0 instead of the IP address of the domain when it is query by devices.
This issue is only occurs sometimes not every query send to AGH is always get result of 0.0.0.0

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/26398101/89735072-74548d00-da92-11ea-8095-0f623a0a0249.png)

<details><summary>Screenshot:</summary>

</details>

### Additional Information

[AdGuardHome.log](https://github.com/AdguardTeam/AdGuardHome/files/5047727/AdGuardHome.log)

**Comment by ameshkov** [comment]
That's why you should not use an upstream DNS server with its own filtering like `dns.adguard.com`.

Replace it with `dns-unfiltered.adguard.com`
