### ISSUE TITLE
Suggestion: Improve pagination UI and UX

### ISSUE THREAD

**Issue by ingria** [AdguardTeam/AdGuardHome#2011]
### Issue Details

* **Version of AdGuard Home server:**
  *  0.103.3
* **How did you setup DNS configuration:**
  * Router
* **Operating system and version:**
  * Ubuntu 20.04 x64

### Actual Behavior
Pagination shows only the current page, dots around it, and arrows. Current page link is not in disabled state. Also dots are shown on the both sides even on the first and the last page.
![pagination-1](https://user-images.githubusercontent.com/2178368/89739890-12ddef80-da8d-11ea-8ed5-0da7e4787a6c.png)

### Expected Behavior
Pagination should show the nearest pages (e.g. n-2, n-1, n, n+1, n+2). Dots on the left side should be hidden if there are no pages "on the left" of the current page (and the same thing for the right-side dots).

Something like this:
![pagination-2](https://user-images.githubusercontent.com/2178368/89739886-0c4f7800-da8d-11ea-9b6c-0b2394d4bd48.png)

**Comment by ameshkov** [comment]
We're going to remove pagination on the query log page and replace it with auto-loading of the next page
