### ISSUE TITLE
Blocking issue

### ISSUE THREAD

**Issue by rchieng** [AdguardTeam/AdGuardHome#2012]
Hello, I recently installed Adguard Home on my pi. But I am running into an issue which I have been trying to fix here. 

It has no problems blocking ads but it is also being very strict as in blocking some entire domain name such as www.apple.com, www.cnn.com, etc. 

Has anyone ever encountered such an issue before?

**Comment by JustHmmmm** [comment]
> Hello, I recently installed Adguard Home on my pi. But I am running into an issue which I have been trying to fix here.
> 
> It has no problems blocking ads but it is also being very strict as in blocking some entire domain name such as [www.apple.com](http://www.apple.com), [www.cnn.com](http://www.cnn.com), etc.
> 
> Has anyone ever encountered such an issue before?

This isn't AdGuardHome issue. I think you can try this allow list: https://raw.githubusercontent.com/raghavdua1995/DNSlock-PiHole-whitelist/master/whitelist.list

**Comment by ameshkov** [comment]
The domains being blocked depend on what blocklists you're using.

Default AdGuard DNS filter does not block neither apple nor cnn.

**Comment by rchieng** [comment]
Hello Ngô Quý,

Thank you for the whitelist. Yeah I check the default filter. Maybe something went wrong while I was installing it. But yeah I’ll check it out again then. 

Thank you very much

**Comment by rchieng** [comment]
Hello again. Looks like I found and fixed the problem here. I'm new at this but apparently all I needed to do was restart AGH. 

Perhaps it would revert some settings that were causing the problems back to default?
