### ISSUE TITLE
Provide per DNS upstream statistics

### ISSUE THREAD

**Issue by wysnxzm** [AdguardTeam/AdGuardHome#2013]
You can intuitively see which DNS is "slowing down" the speed, so as to kick out the inefficient DNS

**Comment by gyCfjSnO** [comment]
**Problem Description**
Unable to view which DNS Resolver is working the most efficiently

**Proposed Solution**
Have a statistic page where you can view how many queries each listed DNS Resolver has actioned and the average processing time etc.

**Comment by peepsnet** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1453

**Comment by ainar-g** [comment]
We've added this on the Edge channel while working on #1453.  Merging into that one.

@wysnxzm, you can test the feature on the Edge channel now.
