### ISSUE TITLE
Query Log files causing 100% CPU usage on Raspberry Pi

### ISSUE THREAD

**Issue by BallistiX09** [AdguardTeam/AdGuardHome#2015]
### Issue Details

* **Version of AdGuard Home server:**
  * Version 0.103.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 2 Model B v1.1
* **Operating system and version:**
  * Raspbian GNU/Linux 9

### Expected Behavior
AdGuard Home should be able to have the query logs setting enabled without causing the program to stop responding to DNS requests due to maxed-out CPU usage.

### Actual Behavior
After upgrading from v0.95 to v0.103.3, AdGuard worked perfectly for a few hours, but stopped working at some point during the night. After stopping the AdGuard service, deleting the two querylog.json files from the AdGuard directory, and setting "querylog_file_enabled" to false, AdGuard worked fine again after restarting, with minimal CPU usage. 

~~After the restart, I checked the config file again, and the "querylog_file_enabled" setting had been set back to true, which I'm thinking will now cause this to happen again.~~ "querylog_enabled" is currently set to false, but I'm sure this was already the case after upgrading since the checkbox on the settings page was unticked.

### Additional Information
This was a problem I ran into a while after setting up AdGuard Home for the first time a few months ago, where all of the devices connected to my router lost internet connectivity. I also couldn't connect to the AdGuard admin page, and after connecting to the Raspberry Pi through SSH instead, I noticed that my storage was completely full. 

I tracked that down to a load of querylog.json files (roughly 500MB each), and after turning off logging through config and deleting the files, AdGuard started working properly again after restarting the service. I thought that old log files were supposed to be cleared out automatically, but that didn't seem to be happening.

This time it only happened after updating to the latest AdGuard Home version, which included some changes in the settings screen for logging behaviour. I checked after upgrading that the "Enable log" button was disabled, and cleared both the logs and statistics just to be sure. Somehow though, it still started saving to these querylog.json files overnight. When I realised what was happening, I checked that I had plenty of space, and I had around 50% left, so that wasn't the problem this time, but the CPU usage was at 100%, with the AdGuardHome service using nearly all of that usage.

I'm not sure if there's a problem with my setup which is causing these files to be problematic, but it definitely seems that just having one of those 500MB querylog files is enough to have AdGuard's CPU usage bring the system to a halt. I currently have the query log disabled, but as mentioned above, it seems like was already the case after updating.

In both cases this has happened, I've fully restarted the service as well as the Raspberry Pi, neither of which have helped at all. I'm not experienced with Linux but can get by with guides, etc, so if anybody could let me know if this is a bug, or if it's a problem specifically with my setup, it would be appreciated! Thanks!

**Comment by szolin** [comment]
Hello!  Could you please enable debug logs and try to reproduce the issue with 100% cpu?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by szolin** [comment]
I've set `querylog_file_enabled: false` and couldn't reproduce the issue with it being reset.
Have you stopped AGH first before editing yaml file?

**Comment by BallistiX09** [comment]
> I've set `querylog_file_enabled: false` and couldn't reproduce the issue with it being reset.
> Have you stopped AGH first before editing yaml file?

I thought I stopped the service before changing the config, since I remember the wiki saying that changes wouldn't be saved without doing that, but I'm guessing I must not have stopped it properly because it's keeping the changes now after making sure the service had stopped. Looks like the config settings being reverted isn't a problem after all, sorry about that!

I've enabled the query logging, along with setting the log file and enabling verbose mode in the config. I'll keep an eye on it and see how it goes, and I'll get back to you as soon as it happens again. Thanks!

**Comment by ameshkov** [comment]
@szolin this reminds me of this issue: https://github.com/AdguardTeam/AdGuardHome/issues/2019

They both seem to be kinda similar.

**Comment by BallistiX09** [comment]
@szolin Hey there, it's happened again, I've uploaded the latest log file which should hopefully help!

Strangely, this time, disabling the query log and deleting the existing query log files never fixed the problem. The last two times this happened, even when restarting never helped, disabling and deleting those query log files instantly fixed the problem, so I assumed it was down to that. I'm now thinking that might have been a coincidence after all.

I've also noticed that after running `sudo ./AdGuardHome -s stop`, and confirming that it has stopped through `sudo ./AdGuardHome -s status`, the service still seems to continue running. I'm still able to connect to the web control panel, and `ps -aux` shows that `/home/pi/AdGuardHome/AdGuardHome --host 192.168.0.28` is still running and using most of the CPU.

I'm not too sure how to fix it this time since the previous method hasn't worked, and I've not been able to find anything by searching for the errors in the log. I've got my router set up to just use its default DNS for now, but I can set it back up again later if you need any more testing.

Also, not sure if it helps at all, but all three times this has happened now has been during the night at some point when I've not been actively using the internet.

[AdGuardHome-Log.txt](https://github.com/AdguardTeam/AdGuardHome/files/5073786/AdGuardHome-Log.txt)

**Comment by szolin** [comment]
```
2020/08/14 09:59:14 450#1665 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 192.168.0.28:44975
2020/08/14 09:59:14 450#1665 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 29213
2020/08/14 09:59:14 450#1665 [debug] AutoHosts: answer: raw.githubusercontent.com -> []
2020/08/14 10:00:10 450#1665 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 56088 ms
2020/08/14 10:00:10 450#1665 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 29213
2020/08/14 10:00:10 450#1665 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: all upstreams failed to respond, cause: Failed to get a connection from TLSPool to tls://1.1.1.1:853, cause: Failed to connect to 1.1.1.1, cause: write tcp 192.168.0.28:52022->1.1.1.1:853: i/o timeout (hidden: Failed to get a connection from TLSPool to tls://1.0.0.1:853, cause: Failed to connect to 1.0.0.1, cause: write tcp 192.168.0.28:50448->1.0.0.1:853: i/o timeout)
```

AGH needs much more CPU power to handle high incoming network load while there are even minor network issues with the outgoing connectivity, especially when TLS is used to connect to an upstream server.
We should **stop accepting new requests** (and creating more goroutines) on reaching a high value of unhandled requests (e.g. 50).  There are goroutines with ID `257213` in the log file, which means that AGH has already created 250.000 goroutines, because the old goroutines take too long to finish their work.

**Comment by ameshkov** [comment]
@szolin well, there's an option to specify MaxGoroutines in `dnsproxy`

**Comment by ameshkov** [comment]
> There are goroutines with ID 257213 in the log file

I don't think you can conclude this based on the goroutine ID, they're not always reused.
