### ISSUE TITLE
How to add custom block lists?

### ISSUE THREAD

**Issue by boxav** [AdguardTeam/AdGuardHome#2016]
How to add new local blocklist if i am running docker instance? connect to container and add local list possible but it's hard to maintain it. lol

For windows or linux: we can use local file very easily. c:/users/name/mylist/list.txt

1. How to set host system file path? (explain with example path) it'll be easy to maintain
(or may be, is there way to link as remote url from host system? i dont want to run web server but it's not a bad idea because i dont need to run it always)

2. Do i need make any change to docker instance or config? (for 1) if then please explain.

**Comment by ameshkov** [comment]
Quick question: do you really need to use Docker?

Read here about mapping volumes:
https://docs.docker.com/storage/volumes/

**Comment by boxav** [comment]
Thank you for the info.

>Quick question: do you really need to use Docker?

It's kinda not necessary for home network. i thought to evaluate with it.

**Comment by ameshkov** [comment]
It's just you can run AdGuard Home natively on Windows, this will solve some of your questions automatically.
