### ISSUE TITLE
Change docker ports result container exited

### ISSUE THREAD

**Issue by boxav** [AdguardTeam/AdGuardHome#2017]
`docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 80:80/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp -d adguard/adguardhome`

I thought to change -p 80:80/tcp to -p 5080:5080/tcp (or maybe -p 80:5080/tcp)
Ago replaced above command with -p 5080:5080/tcp and deployed new container next it got exited quickly. Why?

**Comment by ameshkov** [comment]
Sorry, but I have no idea. Please read more about Docker, read the logs and try to figure it out on your own.

We can help with some regular issues, but this does not look like it.

**Comment by boxav** [comment]
Sorry. now not problem. (ago it exited)
