### ISSUE TITLE
是不是在页面增加个自动刷新！！！

### ISSUE THREAD

**Issue by havefunhaifeng** [AdguardTeam/AdGuardHome#2018]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by havefunhaifeng** [comment]
0.0.

**Comment by havefunhaifeng** [comment]
0.0.

**Comment by ameshkov** [comment]
我看不懂什么自动刷新？

尽量纤细描述你的问题，而这个问题是如何出现的。

**Comment by havefunhaifeng** [comment]
就是那个订阅过滤的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrey Meshkov"<notifications@github.com&gt;; 
发送时间: 2020年8月12日(星期三) 下午4:43
收件人: "AdguardTeam/AdGuardHome"<AdGuardHome@noreply.github.com&gt;; 
抄送: "迎难而上&amp;#x2122;"<937019966@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AdguardTeam/AdGuardHome] 是不是在页面增加个自动刷新！！！ (#2018)





 
我看不懂什么自动刷新？
 
尽量纤细描述你的问题，而这个问题是如何出现的。
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
