### ISSUE TITLE
Adguardhome网页上游出现无法应用

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#2021]
版本为：v0.103.3-SNAPSHOT-2f8e34e
![Screenshot_2020-08-13-22-04-56-807_com android chrome](https://user-images.githubusercontent.com/28734349/90145470-86943b00-ddb2-11ea-9d1b-c1e1e37e8cc1.jpg)
终端显示已有上游dns
![Screenshot_2020-08-13-22-07-02-873_com termux](https://user-images.githubusercontent.com/28734349/90145545-a0ce1900-ddb2-11ea-840c-3ea0823cc555.jpg)

**Comment by ameshkov** [comment]
Fixed
