### ISSUE TITLE
I think the "Click here" update notes for edge snapshots should lead to the changelog and not the releases page

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#2023]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.103.3-SNAPSHOT-9b9902f)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.3-SNAPSHOT-9b9902f
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * Raspbian Bullseye Unstable 32-bit

### Actual Behaviour + Expected Behavior

Currently, when update prompts are shown in the edge snapshots, the *Click here* link leads to https://github.com/AdguardTeam/AdGuardHome/releases, which only contains info for stable and beta builds, and not for the edge snapshots.

For lack of any immediately better options that I know about, I can only presume it would be better to have the button lead to https://github.com/AdguardTeam/AdGuardHome/commits/master in the edge snapshot builds instead.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/90207370-65e5d880-dde6-11ea-9d81-3b54eaaa5d8d.png)

</details>

### Additional Information

None that I'm currently aware of.

**Comment by ameshkov** [comment]
Yeah, I guess the commits history is the only viable choice we have now.
