### ISSUE TITLE
客户端排行能不能按设备统计,ip经常会变,mac地址又识别不了

### ISSUE THREAD

**Issue by lidonglang** [AdguardTeam/AdGuardHome#2024]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
你有什么建议吗？

**Comment by sky96111** [comment]
手机使用静态地址，或者将DHCP服务器交给adh接管。mac无法识别请检查手机是否使用随机mac来保护隐私，如有，请对此wlan使用真实mac

**Comment by ameshkov** [comment]
有唯一见事情能帮助 - #1383

**Comment by lidonglang** [comment]
> mac无法识别请检查手机是否使用随机mac来保护隐私，如有，请使用wlan使用真实mac

所有设备的mac都无法识别,有安卓 ios Windows mac os

**Comment by lidonglang** [comment]
> > mac无法识别请检查手机是否使用随机mac来保护所有权，如有，请使用wlan使用真实mac
> 
> 所有设备的mac都无法识别，有安卓ios Windows mac os

ipv4内网地址可以正常识别,ipv6的地址经常变更,就很麻烦

**Comment by lidonglang** [comment]
> 你有什么建议吗？

客户端统计里,可不可以合并单个设备的所有请求,包含设备ipv4和ipv6地址的

**Comment by lidonglang** [comment]
> > 你有什么建议吗？
> 
> 客户端统计里，可不可以合并合并设备的所有请求，包含设备ipv4和ipv6地址的

类似于openwrt 里的 nlbwmon

**Comment by ameshkov** [comment]
在客户端排行吗？

**Comment by lidonglang** [comment]
> 在客户端排行吗？

是的

**Comment by ameshkov** [comment]
我们会考虑

**Comment by lidonglang** [comment]
> 我们会考虑

谢谢
