### ISSUE TITLE
Unexpected DNS queries?

### ISSUE THREAD

**Issue by Ncage1974** [AdguardTeam/AdGuardHome#2025]
Hi guys. I just installed adguard home tonight. I'm switching over from a pihole. The main reason is switched is because adguard home natively supports DOH (dns over https) so my dns queries can't be snooped on. I changed the upstream dns server to be quad9 main server (https://dns.quad9.net/dns-query). I was reviewing my firewall's logs and noticed there were still dns queries going on port 53 to adguards remote dns servers from the machine i installed adguard home on:
176.103.130.130
176.103.130.131

What gives? Shouldn't all dns queries be going to quad9 servers and not adguards' dns servers? I didn't expect to see any unencrypted dns queries (port 53) going out.

**Comment by ameshkov** [comment]
Hello, 

If you enabled "AdGuard browsing security web service" or parental control, AGH will connect to AdGuard DNS servers to do this.
