### ISSUE TITLE
DNS-over-HTTPS

### ISSUE THREAD

**Issue by lbtboy** [AdguardTeam/AdGuardHome#2026]
Hello.

There is a configured AdGuard Home on a remote VPS OS Debian 10.5, but for some reason I can't connect to it via DNS-over-HTTPS address http:://domianname:port/dns-query. The certificate is fully valid, the corresponding port is open for HTTPS, but there is no connection. Over an unencrypted connection, all devices are connected without any problems. Tell me what can be and how to fix it? Or should it not work as a DoH, and the encrypted connection is only for the web interface?

**Comment by ameshkov** [comment]
> Or should it not work as a DoH, and the encrypted connection is only for the web interface?

It should if you configured it correctly.

Try using https://github.com/ameshkov/dnslookup to check if your server is available. If it's not, the error message may help understand what's wrong with it.
