### ISSUE TITLE
in-addr.arpa Addresses in Top queried domains section

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#2027]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Linksys WRT3200ACM
* **Operating system and version:**
  * OpenWrt 19.07.3

### Actual Behavior

In the Dashboard, within the _Top queried domains for the last 7 days_ section, I have recently been getting a lot of **in-addr.arpa addresses** in the 10 most queried DNS entries. This is something that I personally have only noticed during the 0.103.x releases and possibly the 0.103.x beta releases. I don't know what this represents or why it has started and represents a big percentage of my DNS queries. I have not seen this at all before the 0.103.x releases. Also, nothing has changed in my setup.

Everything appears to be working as expected. So possibly this is just a visual glitch?

**Comment by szolin** [comment]
Can you give a complete example of those addresses?  Are those IP addresses match the IP addresses of the devices that send requests to AGH?

**Comment by WildByDesign** [comment]
> Can you give a complete example of those addresses? Are those IP addresses match the IP addresses of the devices that send requests to AGH?

I was able to dig into this further thanks to the excellent query log abilities in AdGuardHome.

Here is a list of the ones which are accounting for about 50% of my DNS requests:

> 1.41.57.45.in-addr.arpa
205.39.115.96.in-addr.arpa
20.153.118.96.in-addr.arpa
250.255.255.239.in-addr.arpa
200.220.139.72.in-addr.arpa
210.70.36.52.in-addr.arpa
56.88.112.50.in-addr.arpa
16.218.149.54.in-addr.arpa

After doing some quick WhoIs searching by IP (reversed order of octets, of course) and they are from Comcast, Netflix, Amazon, etc.  I also realized that, out of the 12 or so devices on my network, all of the **in-addr.arpa** requests were made from my IPTV box. No other devices on the network were making these requests, just the IPTV box. 

Possibly there was an update to the IPTV box in the past week or so that may have caused this change in behaviour for DNS lookups on the IPTV box specifically.

Before I close this issue since it is likely related just to my IPTV box and not AGH, could you please give my some idea as to why the cable company who makes the software on this IPTV box might decide to make a change that would cause a change in the way they do DNS lookups on the IPTV device?

The reason why I ask for your idea or opinion on this is because I don't have a great understanding of **in-addr.arpa** requests or why the cable company would make this change. I've had the IPTV box for approximately 6 months and it updates every couple of weeks, but only in this past week or so I have observed these **in-addr.arpa** requests.

Also, I have been blocking the IPTV box DNS requests for **analytics.xcal.tv** for a number of months now already because that single domain was approximately 90% of my DNS requests at the time as the IPTV box seemed to do a ridiculous amount of lookups for it. Could these **in-addr.arpa** requests somehow be happening due to my blocking of this **analytics.xcal.tv** domain?

Thank you.

**Comment by szolin** [comment]
It wants to resolve a host name by IP.  You can resolve them by yourself (via nslookup or dig) and see what are these IP-addresses.  I can't imagine why it needs this info.

**Comment by fengzhiwenisgod** [comment]
Reverse parsing of DNS
