### ISSUE TITLE
Android as appliance?

### ISSUE THREAD

**Issue by Wibblyw** [AdguardTeam/AdGuardHome#2030]
Any plans to be able to deploy Adguard Home on an unused Android phone, converting it to an appliance?

**Comment by ameshkov** [comment]
AdGuard Home is supposed to be a server-side software. It is possible to use it on Android if you run AdGuard Home on a public server and setup your Android device to use it either by using AdGuard for Android or simply by configuring "Private DNS" in Android settings.

**Comment by Wibblyw** [comment]
Is AdGuard Home available for general use on a public server?

Question is really if I would at some point be able to use an (old) Android device _as_ the server/appliance? It could be a good use of an 'old' phone given some folk replace them frequently.

**Comment by ameshkov** [comment]
> Is AdGuard Home available for general use on a public server?

For general use, there's AdGuard DNS.

AdGuard Home is a "personal" server, you need to set up one yourself: https://github.com/AdguardTeam/AdGuardHome/wiki/VPS

> Question is really if I would at some point be able to use an (old) Android device as the server/appliance? It could be a good use of an 'old' phone given some folk replace them frequently.

Tbh, I never tried. In theory, Linux/ARM build of AdGuard Home should work on an Android device.
