### ISSUE TITLE
Query Logs flushed upon restart

### ISSUE THREAD

**Issue by daymr** [AdguardTeam/AdGuardHome#2032]
### Issue Details

Upon restart of the FreeNAS Jail containing adguardhome, all of the query logs are deleted.

* **Version of AdGuard Home server:**
  * 0.103.3

* **Operating system and version:**
  * FreeNAS Jail 11.3-RELEASE-p12

### Expected Behavior
query logs should not be deleted, as they are set properly to retain for 30 days.

### Actual Behavior
All dns query logs are get flushed and start fresh on FreeNAS Jail startup. settings are all maintained...

</details>

### Additional Information
Jail was setup on FreeNAS with system of FreeNAS Jail 11.3-RELEASE-p12. Installed via the following manual procedure:

=> install root ca
`pkg install ca_root_nss`
=> First we will download the executable directly from GitHub:
`cd /opt && fetch https://static.adguard.com/adguardhome/release/AdGuardHome_freebsd_amd64.tar.gz`

=> Unzip:
`gunzip AdGuardHome_freebsd_amd64.tar.gz && tar xf AdGuardHome_freebsd_amd64.tar && rm AdGuardHome_freebsd_amd64.tar`

=> We will create the service essentially to run the application whenever your FreeBSD is restarted, in /etc/rc.d

`vi /etc/rc.d/adguardhome`

=> Copy and paste the code below to do this:

Bash:

```
#!/bin/sh

. /etc/rc.subr

name="adguardhome"
rcvar="adguardhome_enable"
adguardhome_user="root"
adguardhome_command="/opt/AdGuardHome/AdGuardHome"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${adguardhome_command}"

load_rc_config $name
: ${adguardhome_enable:=no}

run_rc_command "$1"
```

=> And then, we will give permission and create and mark the service to start with FreeBSD:

`chmod +x /etc/rc.d/adguardhome && sysrc adguardhome_enable="YES"`

=> That done, everything is ready... Now we will run the AdGuardHome executable:

`cd AdGuardHome/ && ./AdGuardHome`

upon realizing the bug, I also gave full 777 to the adguard data folder...this did not help

`chmod 777 /opt/AdGuardHome/data`

Any assistance/information will be greatly appreciated.

**Comment by daymr** [comment]
I think I was able to get around this issue. But its a dirty solution! any help on the proper permissions requirements would be greatly appreciated.

ssh into freenas jail...

then `chmod 777 *`

**Comment by ameshkov** [comment]
I am not an expert in FreeBSD so it's hard for me to comment on this :(
