### ISSUE TITLE
AGH doesn't follow the pre-defined blocklists order when add them

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2034]
![Screenshot from 2020-08-22 13-23-27](https://user-images.githubusercontent.com/63988538/90950385-fa050f00-e47a-11ea-9394-8fafb016f8cd.png)

**Comment by ameshkov** [comment]
That's just how it's implemented, I don't think we can or should change this -- we show the lists in the order in which they were added

**Comment by KizunaH** [comment]
> That's just how it's implemented, I don't think we can or should change this -- we show the lists in the order in which they were added

But more complicated and there's a suitable feature request then atleast it'll help to display under each category https://github.com/AdguardTeam/AdGuardHome/issues/1662

**Comment by ameshkov** [comment]
Well, if we do introduce a list with categories, this would make sense. But with the current UI, I am okay with how it's done.

**Comment by KizunaH** [comment]
#2322
