### ISSUE TITLE
Client settings item should only one identifier each? And identifier support CIDR?

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#2037]
> Version: 0.103.3, OpenWrt 19.07 (Linux amd64)

The screenshot below, I add two IP in one client item, the requests count only show the first IP's counts.
 ![image](https://user-images.githubusercontent.com/22477230/90971569-e376ba80-e543-11ea-894c-331cff8a6f53.png)

 Then I add my cellphone provider's IP range via CIDR, it looks weird, requests count point 2, and those clients not obey assigned upstream too, looks this function totally broken. And I think 112.225.0.0/11 is special cause I test other IP-CIDR, the requests count number working at least.
 ![image](https://user-images.githubusercontent.com/22477230/90971710-2b4a1180-e545-11ea-8aa6-139d351377fb.png)

**Comment by szolin** [comment]
```
top_clients: [
{1.1.1.1: 1},
{2.2.2.2: 2},
{3.3.3.3: 3},
]

client.id = [ 1.1.1.1, 2.2.2.2, 3.3.3.0/24 ]

"Request count" == 1+2+3
```
