### ISSUE TITLE
Query log doesn't display name for blocked services

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2038]
Eg: Skype

![Screenshot from 2020-08-23 16-36-08](https://user-images.githubusercontent.com/63988538/90975759-40cd3480-e561-11ea-8549-32e034fc7353.png)

edge build

**Comment by szolin** [comment]
```
GET /control/querylog

	{
	...
		"service_name": "...", // set if reason=FilteredBlockedService
	...
	}
```

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/340052090c187c74d5e94b9baf55450cabb5bac3
