### ISSUE TITLE
Filterlists causing Adguard Home to block all dns queries

### ISSUE THREAD

**Issue by waffshappen** [AdguardTeam/AdGuardHome#2042]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3 , raspi 32 bit arm version
* **How did you setup DNS configuration:**
  * dnsmasq handing it out as DHCP option
* **If it's a router or IoT, please write device model:**
  * Router: Zbox Nano with Fedora, Adguard Home: Raspberry Pi 3B
* **Operating system and version:**
  * Raspian current 32bit, Fedora 32 on Raspi4 with rpi4-uefi

### Expected Behavior

When adding the following filterlists:
 * https://www.joewein.net/dl/bl/dom-bl-base.txt
 * https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry
AGH should load them and process them with the actual contents.

### Actual Behavior

AGH interprets both lists to mean "block any and all dns requests". 
( tested: heise.de golem.de google.de google.com and whatever else was loading in the background at that time )

**Comment by ameshkov** [comment]
@waffshappen I can't reproduce this.

Could you please check the query log in AdGuard Home and show me what filtering rule has been used to block these domains?

**Comment by waffshappen** [comment]
Heisenbug, this is not reproducible anymore despite re-adding the lists. 
I do know that it showed "blocked by:" the above two lists whenever adding them yesterday but it is now working as it should and i cleared the query logs since.

Not sure if i should close it, since it did happen.

**Comment by ameshkov** [comment]
Please reopen it if you reproduce it again

**Comment by waffshappen** [comment]
Managed to reproduce:

![adguardlist1](https://user-images.githubusercontent.com/44290023/91075268-51e37780-e62d-11ea-9887-56584ff90007.png)

![adguardlist2](https://user-images.githubusercontent.com/44290023/91075291-5b6cdf80-e62d-11ea-8b87-723d8fbfd1bf.png)

**Comment by ameshkov** [comment]
Well, I do see `www.` rule in this list: `https://www.joewein.net/dl/bl/dom-bl-base.txt`

I guess it needs to be fixed there.
