### ISSUE TITLE
Unnecessary blocking on filtering engine reload

### ISSUE THREAD

**Issue by waffshappen** [AdguardTeam/AdGuardHome#2043]
As in previous Thread: 

1. Unnecessary blocking on filtering engine reload;

_Originally posted by @ameshkov in https://github.com/AdguardTeam/AdGuardHome/issues/2041#issuecomment-679194695_

**Comment by waffshappen** [comment]
I narrowed this down to building the new filterlist - It remains alive while downloading but the second it starts building the new filterlist it is only doing that and not responding anymore.

pprof cpu usage during 2 minute rebuild

![pprofduringrebuild](https://user-images.githubusercontent.com/44290023/91097840-f4aced80-e64f-11ea-92c8-753aeb63e5f9.png)

pprof memory usage during lifetime

![pprofmemory_rebuild](https://user-images.githubusercontent.com/44290023/91097858-fc6c9200-e64f-11ea-9e76-c24dca459679.png)

**Comment by ameshkov** [comment]
@szolin

Blocking on filtering engine reload is an obvious issue, but there are some other things that can also be improved.

1. 13 seconds on domain name validation seems too much
2. We can also save some time and avoid calling `NewRule` if we do de-duplication inside `RuleStorageScanner`. Alternatively, de-duplication can be conducted when we download blocklists. The benefit of this approach is that we would be able to show how many rules are discarded from every blocklist.

**Comment by lordraiden** [comment]
> @szolin
>     2. We can also save some time and avoid calling `NewRule` if we do de-duplication inside `RuleStorageScanner`. Alternatively, de-duplication can be conducted when we download blocklists. The benefit of this approach is that we would be able to show how many rules are discarded from every blocklist.

Is this going to be implemented? deduplication and statistics on how much was duplicated in each list?

**Comment by szolin** [comment]
NewRule() has become much faster now and we won't get performance improvements from implementing a complex logic just to save some calls to NewRule() function.  We need to come up with another solution to improve speed more.
