### ISSUE TITLE
[Docker] AGH wizard interface cannot open on custom ports although container running

### ISSUE THREAD

**Issue by azrea** [AdguardTeam/AdGuardHome#2045]
I cannot use port 3000 (it used by another instance) so i'm trying to use port like 3005, 3058. it doesn't work (connection refused).

`docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 4050:4050/tcp -p 443:443/tcp -p 853:853/tcp -p 3005:3005/tcp -d adguard/adguardhome:edge`

docker ps -a shows `0.0.0.0:53->53/udp, 0.0.0.0:53->53/tcp, 0.0.0.0:68->68/tcp, 0.0.0.0:443->443/tcp, 80/tcp, 0.0.0.0:853->853/tcp, 0.0.0.0:3000->3000/tcp, 0.0.0.0:4050->4050/tcp, 0.0.0.0:67-68->67-68/udp  adguardhome`

1. That works if i replace 3005 with default 3000
2. After completed wizard and restart instance, why docker ps -a still shows `80/tcp` (note: if ran with port 4050(instead 80) and 3000) (80, 3000 ports written in dockerfile, it might be the reason)

i guess that possible to solve by creating own image. next i have no way to get updates automatically. 

### Expected Behavior
Works for any port.

### Actual Behavior
Doesn't work and only support for port 3000

**Comment by ameshkov** [comment]
Docker file has nothing to do with this.

You see, exposed ports just signal about which ports you can map and make available on your host machine, but there's no way we can restrict anything from inside the docker file.

> That works if i replace 3005 with default 3000

Maybe it's occupied on your host machine?
