### ISSUE TITLE
Addition of Features...

### ISSUE THREAD

**Issue by Leurie02** [AdguardTeam/AdGuardHome#2048]
Hello there... Adguard Home for pi is good... can you please add some tabs for Reboot, Clear Logs, Shutdown, and more on the Hardware side...

BTW... some of the Whitelisted sites are still not working... i need to change my DNS on my connection just to open the sites... please fix it... thanks... and also the Youtube ads are so abundance... all are not blocked...

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Hello there... Adguard Home for pi is good... can you please add some tabs for Reboot, Clear Logs, Shutdown, and more on the Hardware side...

BTW... some of the Whitelisted sites are still not working... i need to change my DNS on my connection just to open the sites... please fix it... thanks... and also the Youtube ads are so abundance... all are not blocked...

### Alternatives Considered

Hello there... Adguard Home for pi is good... can you please add some tabs for Reboot, Clear Logs, Shutdown, and more on the Hardware side...

**Comment by ajaydcruz** [comment]
A small widget on CPU, Memory Consumption and uptime would also be helpful.

**Comment by KizunaH** [comment]
>Reboot, Shutdown, and more on the Hardware side...

I think that's not important to AGH.

>Clear Logs

Already available.

>Some of the Whitelisted sites are still not working

Can you provide example?

>also the Youtube ads are so abundance... all are not blocked.

AGH only perform DNS level blocking then use extension.

>A small widget on CPU, Memory Consumption and uptime would also be helpful.

#1685

**Comment by ameshkov** [comment]
Ad-related issues need to be reported elsewhere: https://github.com/AdguardTeam/AdGuardSDNSFilter

Also note that Youtube can't be blocked on the DNS level

**Comment by Leurie02** [comment]
Ahhh so only the app on android and windows are able to block it?

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/3146
