### ISSUE TITLE
Add experimental DNS-over-QUIC support to AdGuard Home

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2049]
We finally added it to the latest dnsproxy version:
https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.32.0

We support it for both the server-side and the client-side.

### Server-side support:

1. Add DNS-over-QUIC port to "Encryption settings" in AdGuard Home.
2. Mention that it is experimental.
3. The default port is 784.

### Client-side support:

1. Add it to Examples:
    * Looks like this: `quic://dns-unfiltered.adguard.com:784`
    * The only DNS provider that supports it now is AdGuard DNS
    * Mention that it's experimental and may not be reliable at the moment
2. Check that it's possible to enter quic upstream

**Comment by Potterli20** [comment]
#1768

**Comment by KizunaH** [comment]
For prevent misunderstand: adguard dns not included in mentioned PR then consider to update DNS providers page.

**Comment by Kagura-Nanaa** [comment]
> 我们终于将其添加到了最新的dnsproxy版本中：[https](https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.32.0) :
> [//github.com/AdguardTeam/dnsproxy/releases/tag/v0.32.0](https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.32.0)
> 
> 我们在服务器端和客户端都支持它。
> 
> ### 服务器端支持：
> 1. 将DNS-over-QUIC端口添加到AdGuard Home中的“加密设置”。
> 2. 提及这是实验性的。
> 3. 默认端口是784。
> 
> ### 客户端支持：
> 1. 将其添加到示例：
>    
>    * 看起来像这样： `quic://dns-unfiltered.adguard.com:784`
>    * 现在唯一支持它的DNS提供商是AdGuard DNS
>    * 提及它是实验性的，目前可能不可靠
> 2. 检查是否可以在上游输入quic

安卓app中好像无法使用quic

**Comment by ameshkov** [comment]
> 安卓app中好像无法使用quic

它快要能用了，我们计划上个月发行新的版本。

**Comment by Kagura-Nanaa** [comment]
> > 安卓app中好像无法使用quic
> 
> 它快要能用了，我们计划上个月发行下个月😆

> > 安卓app中好像无法使用quic
> 
> 它快要能用了，我们计划上个月发行新的版本。

下个月😆

**Comment by ameshkov** [comment]
哈哈，对不起，其实是下个月

**Comment by debpalash** [comment]
@ameshkov is my local upstream DoQ server format `127.0.0.1:784 `or `quic://127.0.0.1:784`? I've enabled port 784 with `v0.108.0-b.9` but it throws error for both formats while testing.
