### ISSUE TITLE
Redesign query logs block/unblock buttons

### ISSUE THREAD

**Issue by ArtemBaskal** [AdguardTeam/AdGuardHome#2050]
Buttons that we need to provide:

Block / Unblock (as usual)

Additional options:

* Block for this client
* Unblock for this client

Check what syntax you need to use for this: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#-client
If this is a manually created client, use its name. If this is a "runtime" client, use it's IP address.

Additionally, add "Block this client" (https://github.com/AdguardTeam/AdGuardHome/issues/1097) in both cases (it does not depend on whether the query is blocked or not). Note, that you need to show javascript confirm dialog if the user clicks on this button.

Confirmation text: `AdGuard Home will be dropping all DNS queries from this client. Are you sure you want to block the client "XXXXX"?`

Use the same text in the confirmation dialog that we show when the user blocks client from the Dashboard.

**Comment by KizunaH** [comment]
#1097

**Comment by KizunaH** [comment]
Sorry, #1097 (it's not related FR)

**Comment by ameshkov** [comment]
@ArtemBaskal 

Additionally, add "Block this client" (#1097) in both cases (it does not depend on whether the query is blocked or not). Note, that you need to show javascript confirm dialog if the user clicks on this button.

Confirmation text: AdGuard Home will be dropping all DNS queries from this client. Are you sure you want to block the client "XXXXX"?

Use the same text in the confirmation dialog that we show when the user blocks client from the Dashboard.
