### ISSUE TITLE
Security function

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#2051]
Openwrt x64 in mini PC
Hope add certificate pinning in.
The certificate pinning was canceled in the Chrome browser at the end of April 2018. Since version 72, Firefox has also turned off certificate pinning by default. Without certificate pinning, it will not be able to resist such national-level hacking attacks.
This is more important.

Sandbox the cookies that through the mini PC for more security.
need add WebRTC Protection.

**Comment by ameshkov** [comment]
Why would you need that? You can control what certificates your server trusts by changing the set of root certs that you have installed and enabled in your OS
