### ISSUE TITLE
Bootstrap DNS Resolver not working?

### ISSUE THREAD

**Issue by Ncage1974** [AdguardTeam/AdGuardHome#2052]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

Adguard Version: 0.103.3
Operating system its running on Ubuntu Server 20.04.1
running the snap package install

So i woke up this morning with no internet. Found out dns wasn't working. So i of course tried to reboot my adguard server which didn't help. I tried to mess with the upstream dns settings thinking maybe quad 9 could be down (i was using https://dns.quad9.net/dns-query) . I changed it to 8.8.8.8 which fixed the issue. So i tried to update it to another DOH provider (https://1.1.1.1/dns-query) which also didn't work. I also tried adguards own DOH (https://dns.adguard.com/dns-query) which didn't work. I decided to try quad9 unencrpted UDP dns (9.9.9.9) which worked fine. To be complete i tried dns-over-tls (tls://dns.quad9.net) which again didn't work. So any encrypted dns does not work. Only unencrypted UDP dns seems to work. 

I've had adguard home running for about 2 months and haven't made any config changes since i originally set it up.

Any clue? Let me know if there is anything else i can provide you.

thanks....

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by Ncage1974** [comment]
> To troubleshoot this issue we need to see AdGuard Home logs.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

I will do that and have it up here soon.

thanks...

**Comment by Ncage1974** [comment]
> To troubleshoot this issue we need to see AdGuard Home logs.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

Thanks for the reply. Took me a little time to figure out where everything was but finally got it figured out. I took an example for the log file. let me know if this is enough or if you need more:
`2020/08/28 15:28:19 5876#423 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10521 ms
2020/08/28 15:28:19 5876#444 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream https://dns.quad9.net:443/dns-query failed to exchange ;www.google.com.     IN       A in 10079 milliseconds. Cause: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10049 ms
2020/08/28 15:28:19 5876#444 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 10079 ms
2020/08/28 15:28:19 5876#444 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 4591
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0`


thanks....

**Comment by ameshkov** [comment]
It's unclear what causes this timeout.

Two options: either Quad9 server is unavailable or the bootstrap DNS server is unavailable.
What do  you use as a bootstrap?

**Comment by Ncage1974** [comment]
> It's unclear what causes this timeout.
> 
> Two options: either Quad9 server is unavailable or the bootstrap DNS server is unavailable.
> What do you use as a bootstrap?

The bootstrap i use is the default (i never changed it):
9.9.9.10
149.112.112.10
2620:fe::10
2620:fe::fe:10

Like i said thing i did try other DOH servers Cloudeflare (https://1.1.1.1/dns-query), Adguards (https://dns.adguard.com/dns-query). I also tried googles (https://dns.google/dns-query).

**Comment by ameshkov** [comment]
Try using 8.8.8.8 as a bootstrap just in case

**Comment by Ncage1974** [comment]
> Try using 8.8.8.8 as a bootstrap just in case

I tried that with googles upstream ("https://dns.google/dns-query") and also tried 1.1.1.1 as a bootstrap. Still nothing :(. What i decided to try that does work is https://9.9.9.9/dns-query which seems to means it is a failure on the bootstrap. I think i have two choices at this point: either reinstall adguard home or live with https://9.9.9.9. Do you have any other suggestions?

**Comment by ameshkov** [comment]
Sorry for the late reply. Tbh, I don't understand why the bootstrap does not work, but I am almost sure reinstalling AGH won't help with that.

Using DNS server without a domain name is indeed a solution as in this case you won't need to use the bootstrap DNS server.
