### ISSUE TITLE
Assign blacklists to particular clients

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2054]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description
I want to assign filter lists to clients. The way I have seen it so far, you can only apply filter lists globally.

**Comment by ameshkov** [comment]
Duplicates this one:
https://github.com/AdguardTeam/AdGuardHome/issues/435

This is an old issue where you can keep track of all "client-specific" settings we implement.

There's no way to assign lists per client at the moment, but this is on our todo list.
