### ISSUE TITLE
Setting a large DNS Cache Size in the Web GUI will exceed the unit32 range.

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdGuardHome#2056]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
0.103.3
* **How did you setup DNS configuration:**
Server
* **Operating system and version:**
Debian 10 amd64

### Expected Behavior
Allow larger DNS Cache Size.

### Actual Behavior
Try to set a DNS Cache of 4294967296 bytes (4GiB), but out of the range of uint32, it was resulting in the JSON parser unable to process values.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/91681325-b0a27700-eb80-11ea-83b1-294814742107.png)

</details>

### Additional Information

The Web GUI should ideally use more common units such as MiB / GiB and convert them to byte after writing the YAML configuration file.

**Comment by ameshkov** [comment]
This issue needs to be fixed on the UI in a consistent manner - just don't allow to enter a value that exceeds int.maxvalue for fields that are posted as integers.

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/2a5b0b8da1f85727e36a4601c51bdfb79ef2583f
