### ISSUE TITLE
List URL in DNS blocklists for AdAway is incorrect

### ISSUE THREAD

**Issue by state-of-affairs** [AdguardTeam/AdGuardHome#2057]
I just installed the latest version of AdGuard Home (0.103.3).  When I go to Filters --> DNS blocklists, there are three rule lists that are provided as default rule lists, including one for AdAway.  The default URL for AdAway points to the following web page:

https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt

I believe this URL should actually point to the raw file, not the web page.  I am referring to the following URL:

https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

When I change the URL to the raw file, AdGuard Home receives about 7959 rules.  Previously, no rules were received and the Rule Count was 0.  Can you confirm that this is a bug?

**Comment by ameshkov** [comment]
Yep, this is a bug, it's already fixed in the master branch
