### ISSUE TITLE
Virtually unresponsive after internet outage

### ISSUE THREAD

**Issue by alex-phillips** [AdguardTeam/AdGuardHome#2058]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

For some reason when my internet goes out (no power loss, just ISP has internet issues), when everything comes back online, AdGuard gets put into a state that seems unresponsive. All DNS requests on the network fail while I'm still able to ping external IPs (ex: 8.8.8.8 is pingable, but cannot resolve google.com). Stopping / starting / restarting the service on the Pi doesn't seem to do anything. It's almost as if AdGuard is overwhelmed. Eventually, I have to add in additional external DNS servers into my router until AdGuard finally returns to normal with resolving requests over time.

When this happens, even on the Pi itself I am unable to resolve any external DNS queries.

* **Version of AdGuard Home server:**
  * v0.103.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Unifi USG
* **Operating system and version:**
  * Raspbian Stretch

### Expected Behavior
When the network returns, DNS resolving should return to normal. If not, restarting the AdGuard service should.

### Actual Behavior
AdGuard is unable to resolve any DNS queries. Even DNS rewrites inside AdGuard are not returned.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by alex-phillips** [comment]
Here is some more information related to the issue. When this does happen, the logs in `/var/log/syslog` are flooded with the following:

```
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 13436 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 12457 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10793 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10755 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10754 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10754 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10741 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10741 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 13898 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10913 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10918 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10919 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10919 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10915 ms
Aug 31 21:08:07 raspberrypi AdGuardHome[340]: 2020/08/31 21:08:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: timeout exceeded: 10920 ms
```

**Comment by ameshkov** [comment]
> when everything comes back online, AdGuard gets put into a state that seems unresponsive

How long does it take it to get operational after that?

> Stopping / starting / restarting the service on the Pi doesn't seem to do anything.

This one is really-really weird. Does your log from the above comment is after the service restart?

**Comment by alex-phillips** [comment]
@ameshkov Thanks for the reply.

> How long does it take it to get operational after that?
Unfortunately I can't 'wait' as I'm working from home, so when this does happen I go into my router and add additional upstream DNS servers which help restore my network connectivity. I'd say at a minimum 10 or 20 minutes.

> This one is really-really weird. Does your log from the above comment is after the service restart?
That log is from `/var/log/syslog`. When I restart AdGuard from the command line, the restart process does take quite a while, but it does say that it 'restarted successfully'. 

I'm not sure where the actual AdGuard log files are (I can't seem to find them on the machine). It seems to me like AdGuard looses its upstream DNS connection so requests coming in 'pile up' while waiting for a response and ultimately times out. My Pi's 1m load was around 4 when I checked the last time this happened.

**Comment by ameshkov** [comment]
By default, it will write the syslog, but you can make AGH write logs to a file, check the configuration file description here: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

Ideally, I'd like to understand what exactly is written to the log after the internet connection is restored.

**Comment by alex-phillips** [comment]
Next time this happens I'll attempt to get the full log file as I think the logs from yesterday have already rotated out.

**Comment by alex-phillips** [comment]
@ameshkov It happened again this morning. Not much more in the logs, but here they are from today. It eventually came back at 14:40 with no additional logging. Let me know if I need to enable any additional logging levels or anything. But when this happened, access was completely lost to the outside (and seemingly into the network as well, not sure if this was due to network saturation).

[AdGuardHome-redacted.log](https://github.com/AdguardTeam/AdGuardHome/files/5178174/AdGuardHome-redacted.log)

**Comment by ameshkov** [comment]
Here's what I need to know:

1. When exactly the network connectivity was lost (ISP issues started)
2. When it was back (i.e. you could ping 8.8.8.8)
3. When AGH was operational again

Ideally, I'd like to get the log with `verbose` set to `true`.

**Comment by alex-phillips** [comment]
@ameshkov 

>     1. When exactly the network connectivity was lost (ISP issues started)

It looks like it started around 8:30 EDT.

>   2. When it was back (i.e. you could ping 8.8.8.8)

During this time, the internet wasn't 'completely' out. From inside the network, I can still ping 8.8.8.8 but all DNS queries are not resolved.

>   3. When AGH was operational again

Looks like AGH came back and full network was restored around 10am EDT. Total downtime was around 2 hours.

I've set verbose to true, so will report back next time this happens with more information.

**Comment by kvervo** [comment]
I believe I am having this problem with the only exception, that restarting the service does help in may case. 
I am using the same gear as indicated in this issue.

I will try to reproduce the problem to have 100% reproducibility.

**Comment by Daskew78** [comment]
I also have this issue. Running the latest version of Adguard (although the issue has been present in all previous versions). After an internet dropout Adguard stops working and I have to reboot the VM for it to start working again. Very strange and annoying.

**Comment by ameshkov** [comment]
@Daskew78 the issue is resolved in the beta and edge channels, please try it.

**Comment by Daskew78** [comment]
> @Daskew78 the issue is resolved in the beta and edge channels, please try it.

Thanks for the reply, I read on another thread it might be to do with DoH connections still being active, I'm now using TLS. Was this the issue as i've no need to upgrade to beta if so.
