### ISSUE TITLE
DHCP Static leases back up.

### ISSUE THREAD

**Issue by RonKhondji** [AdguardTeam/AdGuardHome#2059]
I've just created a lot of static leases.
Now, suppose the machine AdguardHome is running on breaks down and I have to install it on another machine.

I can store a copy of AdguardHome.yaml in the cloud and copy that back to the new machine to have most settings back the way they were.

Is there a file that holds all the static leases so I could do the same for those?

If not than it would be nice to have some way to backup all the AdGuarsHome DNS and DHCP settings for in case of a calamity.

**Comment by szolin** [comment]
`leases.db` contains all dhcp leases.  You can copy it to a new installation and it should work.
