### ISSUE TITLE
stacktrace

### ISSUE THREAD

**Issue by packet1** [AdguardTeam/AdGuardHome#2060]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
 0.103.3
* **How did you setup DNS configuration:**
system
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
Ubuntu 18.04.1 , snap install for adguard home

### Expected Behavior
no stack trace
### Actual Behavior
stacktrace in the logs - what is broken?
### Screenshots

see logs below

Sep  1 15:56:57 adguard gnome-software[1873]: message repeated 4 times: [ Failed to load snap icon: local snap has no icon]
Sep  1 16:00:29 adguard systemd[1]: Started Run anacron jobs.
Sep  1 16:00:29 adguard anacron[1976]: Anacron 2.3 started on 2020-09-01
Sep  1 16:00:29 adguard anacron[1976]: Normal exit (0 jobs run)
Sep  1 16:00:42 adguard gnome-software[1873]: no app for changed ubuntu-dock@ubuntu.com
Sep  1 16:00:42 adguard gnome-shell[1398]: Object .Gjs_AppIndicatorIconActor__1 (0x5556cb529680), has been already finalized. Impossible to set any property to it.
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: == Stack trace for context 0x5556c6db7330 ==
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #0 0x7ffdf28248d0 I   resource:///org/gnome/gjs/modules/_legacy.js:83 (0x7fe06c5b5de0 @ 87)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #1 0x5556c71c7b88 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:93 (0x7fe0500c1340 @ 58)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #2 0x7ffdf28254b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #3 0x7ffdf2825570 b   self-hosted:916 (0x7fe06c5f12b8 @ 367)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #4 0x7ffdf2825660 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #5 0x5556c71c7b00 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:190 (0x7fe0500adf78 @ 22)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #6 0x7ffdf28262b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #7 0x5556c71c7a58 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:219 (0x7fe0500ad5e8 @ 225)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #8 0x7ffdf2826e90 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #9 0x5556c71c79e0 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/extension.js:61 (0x7fe050083780 @ 37)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #10 0x5556c71c7920 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (0x7fe06c3592b8 @ 441)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #11 0x5556c71c78a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (0x7fe06c359d58 @ 13)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #12 0x7ffdf2827b90 b   self-hosted:251 (0x7fe06c5c4ab0 @ 223)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #13 0x5556c71c7820 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (0x7fe06c359cd0 @ 64)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #14 0x5556c71c77a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (0x7fe06c359de0 @ 87)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #15 0x7ffdf2829090 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #16 0x7ffdf28298a0 b   resource:///org/gnome/shell/ui/sessionMode.js:205 (0x7fe06c26f4d8 @ 254)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #17 0x7ffdf282ac90 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #18 0x5556c71c7660 i   resource:///org/gnome/shell/ui/sessionMode.js:167 (0x7fe06c26f2b8 @ 40)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #19 0x7ffdf282bff0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #20 0x5556c71c75b8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (0x7fe06c253a28 @ 188)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #21 0x7ffdf282d350 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #22 0x5556c71c7530 i   resource:///org/gnome/shell/ui/screenShield.js:902 (0x7fe06c251b38 @ 18)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #23 0x7ffdf282e6b0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #24 0x7ffdf282eec0 b   self-hosted:916 (0x7fe06c5f12b8 @ 367)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #25 0x7ffdf282fd10 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #26 0x5556c71c74b0 i   resource:///org/gnome/shell/ui/lightbox.js:186 (0x7fe06c338a28 @ 29)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #27 0x5556c71c7428 i   resource:///org/gnome/shell/ui/tweener.js:112 (0x7fe06c5c8e68 @ 37)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #28 0x5556c71c7388 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7fe06c5d2b38 @ 54)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #29 0x5556c71c7268 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7fe06c5d2bc0 @ 1626)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #30 0x5556c71c71d8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7fe06c5d2c48 @ 100)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #31 0x5556c71c7160 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7fe06c5d2cd0 @ 10)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #32 0x7ffdf2832cb0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #33 0x5556c71c70d0 i   resource:///org/gnome/shell/ui/tweener.js:244 (0x7fe06c5cf808 @ 159)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #34 0x7ffdf2834010 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #35 0x5556c71c7050 i   resource:///org/gnome/shell/ui/tweener.js:219 (0x7fe06c5cf780 @ 15)
Sep  1 16:00:42 adguard gnome-shell[1398]: Object .Gjs_AppIndicatorIconActor__1 (0x5556c8a1c640), has been already finalized. Impossible to set any property to it.
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: == Stack trace for context 0x5556c6db7330 ==
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #0 0x7ffdf28248d0 I   resource:///org/gnome/gjs/modules/_legacy.js:83 (0x7fe06c5b5de0 @ 87)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #1 0x5556c71c7b88 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:93 (0x7fe0500c1340 @ 58)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #2 0x7ffdf28254b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #3 0x7ffdf2825570 b   self-hosted:916 (0x7fe06c5f12b8 @ 367)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #4 0x7ffdf2825660 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #5 0x5556c71c7b00 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:190 (0x7fe0500adf78 @ 22)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #6 0x7ffdf28262b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #7 0x5556c71c7a58 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:219 (0x7fe0500ad5e8 @ 225)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #8 0x7ffdf2826e90 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #9 0x5556c71c79e0 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/extension.js:61 (0x7fe050083780 @ 37)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #10 0x5556c71c7920 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (0x7fe06c3592b8 @ 441)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #11 0x5556c71c78a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (0x7fe06c359d58 @ 13)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #12 0x7ffdf2827b90 b   self-hosted:251 (0x7fe06c5c4ab0 @ 223)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #14 0x5556c71c77a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (0x7fe06c359de0 @ 87)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #15 0x7ffdf2829090 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #16 0x7ffdf28298a0 b   resource:///org/gnome/shell/ui/sessionMode.js:205 (0x7fe06c26f4d8 @ 254)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #17 0x7ffdf282ac90 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #18 0x5556c71c7660 i   resource:///org/gnome/shell/ui/sessionMode.js:167 (0x7fe06c26f2b8 @ 40)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #19 0x7ffdf282bff0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #20 0x5556c71c75b8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (0x7fe06c253a28 @ 188)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #21 0x7ffdf282d350 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #22 0x5556c71c7530 i   resource:///org/gnome/shell/ui/screenShield.js:902 (0x7fe06c251b38 @ 18)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #23 0x7ffdf282e6b0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #24 0x7ffdf282eec0 b   self-hosted:916 (0x7fe06c5f12b8 @ 367)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #25 0x7ffdf282fd10 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #26 0x5556c71c74b0 i   resource:///org/gnome/shell/ui/lightbox.js:186 (0x7fe06c338a28 @ 29)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #27 0x5556c71c7428 i   resource:///org/gnome/shell/ui/tweener.js:112 (0x7fe06c5c8e68 @ 37)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #28 0x5556c71c7388 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7fe06c5d2b38 @ 54)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #29 0x5556c71c7268 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7fe06c5d2bc0 @ 1626)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #30 0x5556c71c71d8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7fe06c5d2c48 @ 100)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #31 0x5556c71c7160 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7fe06c5d2cd0 @ 10)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #32 0x7ffdf2832cb0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #33 0x5556c71c70d0 i   resource:///org/gnome/shell/ui/tweener.js:244 (0x7fe06c5cf808 @ 159)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #34 0x7ffdf2834010 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #35 0x5556c71c7050 i   resource:///org/gnome/shell/ui/tweener.js:219 (0x7fe06c5cf780 @ 15)
Sep  1 16:00:42 adguard gnome-shell[1398]: Object .Gjs_AppIndicatorIconActor__1 (0x5556cc50dcd0), has been already finalized. Impossible to set any property to it.
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: == Stack trace for context 0x5556c6db7330 ==
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #0 0x7ffdf28248d0 I   resource:///org/gnome/gjs/modules/_legacy.js:83 (0x7fe06c5b5de0 @ 87)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #1 0x5556c71c7b88 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/indicatorStatusIcon.js:93 (0x7fe0500c1340 @ 58)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #2 0x7ffdf28254b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #3 0x7ffdf2825570 b   self-hosted:916 (0x7fe06c5f12b8 @ 367)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #4 0x7ffdf2825660 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #5 0x5556c71c7b00 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:190 (0x7fe0500adf78 @ 22)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #6 0x7ffdf28262b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #7 0x5556c71c7a58 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/statusNotifierWatcher.js:219 (0x7fe0500ad5e8 @ 225)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #8 0x7ffdf2826e90 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #9 0x5556c71c79e0 i   /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/extension.js:61 (0x7fe050083780 @ 37)

Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #10 0x5556c71c7920 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (0x7fe06c3592b8 @ 441)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #11 0x5556c71c78a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (0x7fe06c359d58 @ 13)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #12 0x7ffdf2827b90 b   self-hosted:251 (0x7fe06c5c4ab0 @ 223)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #13 0x5556c71c7820 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (0x7fe06c359cd0 @ 64)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #14 0x5556c71c77a0 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (0x7fe06c359de0 @ 87)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #15 0x7ffdf2829090 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #16 0x7ffdf28298a0 b   resource:///org/gnome/shell/ui/sessionMode.js:205 (0x7fe06c26f4d8 @ 254)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #17 0x7ffdf282ac90 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #18 0x5556c71c7660 i   resource:///org/gnome/shell/ui/sessionMode.js:167 (0x7fe06c26f2b8 @ 40)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #19 0x7ffdf282bff0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #20 0x5556c71c75b8 i   resource:///org/gnome/shell/ui/screenShield.js:1282 (0x7fe06c253a28 @ 188)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #21 0x7ffdf282d350 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #22 0x5556c71c7530 i   resource:///org/gnome/shell/ui/screenShield.js:902 (0x7fe06c251b38 @ 18)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #23 0x7ffdf282e6b0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #24 0x7ffdf282eec0 b   self-hosted:916 (0x7fe06c5f12b8 @ 367)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #25 0x7ffdf282fd10 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #26 0x5556c71c74b0 i   resource:///org/gnome/shell/ui/lightbox.js:186 (0x7fe06c338a28 @ 29)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #27 0x5556c71c7428 i   resource:///org/gnome/shell/ui/tweener.js:112 (0x7fe06c5c8e68 @ 37)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #28 0x5556c71c7388 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7fe06c5d2b38 @ 54)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #29 0x5556c71c7268 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7fe06c5d2bc0 @ 1626)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #30 0x5556c71c71d8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7fe06c5d2c48 @ 100)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #31 0x5556c71c7160 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7fe06c5d2cd0 @ 10)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #32 0x7ffdf2832cb0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe06c5d2230 @ 386)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #33 0x5556c71c70d0 i   resource:///org/gnome/shell/ui/tweener.js:244 (0x7fe06c5cf808 @ 159)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #34 0x7ffdf2834010 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe06c5b5de0 @ 71)
Sep  1 16:00:42 adguard org.gnome.Shell.desktop[1398]: #35 0x5556c71c7050 i   resource:///org/gnome/shell/ui/tweener.js:219 (0x7fe06c5cf780 @ 15)
Sep  1 16:00:42 adguard gnome-software[1873]: no app for changed ubuntu-appindicators@ubuntu.com

**Comment by ameshkov** [comment]
I see nothing related to AdGuard Home in the log, I guess you need to report it to Ubuntu devs.
