### ISSUE TITLE
BUG: "update_failed" string is not working correctly in WebUI.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2062]
Version: v0.103.3-4efc464e

![Xnip2020-09-03_08-41-01](https://user-images.githubusercontent.com/58100052/92057582-90152f80-edc1-11ea-961a-c0236e34477a.jpg)

**Comment by Gill-Bates** [comment]
I have no issues (Debian Buster)
![grafik](https://user-images.githubusercontent.com/25774289/92232733-53276680-eeaf-11ea-90f3-7321a5099418.png)

**Comment by hezhijie0327** [comment]
"AdGuard Home is up-to-date" is the string called "updates_version_equal". The issued string is "update_failed".
