### ISSUE TITLE
Separate clients on the local network

### ISSUE THREAD

**Issue by spot320** [AdguardTeam/AdGuardHome#2063]
Could you add the ability to separate clients on the local network, the fact is that to connect the dchp server to adguardhome, you need a static address. In this case, all my restrictions are imposed on the router.

**Comment by ameshkov** [comment]
Could you please elaborate? What exactly do you want us to do? Provide as many details as possible

**Comment by spot320** [comment]
> Could you please elaborate? What exactly do you want us to do? Provide as many details as possible

I will use the latest version of your application on an openwrt router. I don't have a static address. I'm trying to separate clients on the local network, nothing happens without a static ip, it shows the entire statistics of the router. Is it possible to somehow separate clients on a local network without having a static ip?

**Comment by ameshkov** [comment]
It's possible that your router is proxying DNS queries to AdGuard Home and that's why AGH simply does not see the original client.

If you're on openwrt, can't you fully replace dnsmasq with AdGuard Home?

**Comment by spot320** [comment]
> 
> If you're on openwrt, can't you fully replace dnsmasq with AdGuard Home?

It's possible that your router is proxying DNS queries to AdGuard Home and that's why AGH simply does not see the original client.

**Comment by spot320** [comment]
> It's possible that your router is proxying DNS queries to AdGuard Home and that's why AGH simply does not see the original client.
> 
> If you're on openwrt, can't you fully replace dnsmasq with AdGuard Home?

how to fix?

**Comment by ameshkov** [comment]
Just change the port in dnsmasq to something different from 53, and change AdGuard Home DNS port to 53, it should be enough.

**Comment by spot320** [comment]
> Just change the port in dnsmasq to something different from 53, and change AdGuard Home DNS port to 53, it should be enough.
#
tried it but doesn't work.

**Comment by ameshkov** [comment]
> list sever 127.0.0.1:53

Why 127.0.0.1 and not 0.0.0.0?

**Comment by spot320** [comment]
> > list sever 127.0.0.1:53
> 
> Why 127.0.0.1 and not 0.0.0.0?

I installed myself from the instructions 4pda, I ask for a petition, I do not understand much about this.

**Comment by spot320** [comment]
> > list sever 127.0.0.1:53
> 
> Why 127.0.0.1 and not 0.0.0.0?

do you understand Russian?

**Comment by spot320** [comment]
changed 127.0.0.1 to 0.0.0.0 everything works as before, it is impossible to add koients.

**Comment by ameshkov** [comment]
Понимаю-понимаю.

Короче, в OpenWRT есть свой DNS-сервер -- dnsmasq. Его надо выключить (или перенастроить на другой порт), и сделать, чтобы AGH слушал на его месте.

Сделать это нужно не в настройках DHCP, их вот вам вообще трогать не нужно, а в AdGuardHome.yaml - там настраивается bind_host/bind_port в секции dns. Но перед этим вам нужно dnsmasq перенастроить, чтобы он 0.0.0.0:53 не занимал.

А там где на 4pda инструкция выложена спросить не у кого? Я то тоже не эксперт по OpenWRT:)

**Comment by spot320** [comment]
> Понимаю-понимаю.
> 
> Короче, в OpenWRT есть свой DNS-сервер -- dnsmasq. Его надо выключить (или перенастроить на другой порт), и сделать, чтобы AGH слушал на его месте.
> 
> Сделать это нужно не в настройках DHCP, их вот вам вообще трогать не нужно, а в AdGuardHome.yaml - там настраивается bind_host/bind_port в секции dns. Но перед этим вам нужно dnsmasq перенастроить, чтобы он 0.0.0.0:53 не занимал.
> 
> А там где на 4pda инструкция выложена спросить не у кого? Я то тоже не эксперт по OpenWRT:)

В том то и проблема что dhcp на столько плотно интегрирован в openwrt что его отключить это пояском потерять ряд функций роутера, я уже пробовал решить этот вопрос с автором поста, но он не смог помоч.

**Comment by ameshkov** [comment]
Я же говорю - DHCP отключать НЕ НУЖНО.

Вам надо просто DNS-сервер dnsmasq перевесить на другой порт, а AGH - повесить на его место.

**Comment by spot320** [comment]
> Я же говорю - DHCP отключать НЕ НУЖНО.
> 
> Вам надо просто DNS-сервер dnsmasq перевесить на другой порт, а AGH - повесить на его место.

Спасибо это уже пончтнее, попробую отпишусь.

**Comment by spot320** [comment]
> Я же говорю - DHCP отключать НЕ НУЖНО.
> 
> Вам надо просто DNS-сервер dnsmasq перевесить на другой порт, а AGH - повесить на его место.

В общем не чего у нас не выходит, вещаю dnsmasq на 5100 порт, AGH на 53, перезагружаю роутер интернет работает  но на сайты не пускает, смотрю netstat -tlp, dnsmasq на 5100,а AGH не присвоен порт надпись domain. Я понимаю может звучит глупо, но я перепробовал множество вариантов настроек, но не к чему не привело. Автор поста по установке agh человек не глупый в openwrt и то пишет что тоже понять не может почему так.
Вот лог:
2020/09/10 04:25:49 [info] Failed to update filter http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts: Get "http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts": dial udp 1.1.1.1:53: connect: network is unreachable
2020/09/10 04:25:49 [error] os.Chtimes(): chtimes /tmp/AdGuardHome/data/filters/1575618243.txt: no such file or directory
2020/09/10 04:25:49 [info] Couldn't request filter from URL http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts, skipping: Get "http://sbc.io/hosts/alternates/fakenews-gambling-porn-social/hosts": dial udp 1.1.1.1:53: connect: network is unreachable

**Comment by spot320** [comment]
Если можешь помоги разобрать пожалуйста

**Comment by spot320** [comment]
В настройка опенврт в веб морде есть админка agh 
В ней есть  пунк где можно выбрать по умолчанию какой порт использовать для agh (скрин ниже)я испробовал все варианты которые там имеются при этом правил конфиг agh указывая в нем 53 порт, и вешая qnsmasq на 5100 порт это делается в конфиге dhcp.но не что не работает кроме как run as dnsmasq upstream server на 5553 порту.

**Comment by spot320** [comment]
![1599697508844](https://user-images.githubusercontent.com/64120245/92667685-1c60ae80-f2fc-11ea-9fb7-af886961ed6e.jpg)
![1599697535974](https://user-images.githubusercontent.com/64120245/92667713-35695f80-f2fc-11ea-9d45-3fe721bbba8c.jpg)
![1599697574121](https://user-images.githubusercontent.com/64120245/92667734-474b0280-f2fc-11ea-87d8-64f8e4b1edf2.jpg)
![1599697609876](https://user-images.githubusercontent.com/64120245/92667758-57fb7880-f2fc-11ea-82c9-0bef35bacf2b.jpg)
На скринах единственный рабочий вариант, без разделения клиентов.

**Comment by ameshkov** [comment]
Тэкс, а там на одном из скринов опция "Use port 53 replace dnsmasq", она не работает чтоли?

**Comment by spot320** [comment]
> Тэкс, а там на одном из скринов опция "Use port 53 replace dnsmasq", она не работает чтоли?

Если ее включить и при этом поменять порт в конфиге адгуарда на 53, то после перезагрузки он почему-то автоматом вешает его на 1745 порт, полное хз

**Comment by ameshkov** [comment]
Я так понял что этот модуль openwrt'шный контролирует настройки и самому лезть в yaml-файл уже не нужно. Просто попробуйте этот режим выбрать и посмотрите будет ли работать все.

**Comment by spot320** [comment]
> Я так понял что этот модуль openwrt'шный контролирует настройки и самому лезть в yaml-файл уже не нужно. Просто попробуйте этот режим выбрать и посмотрите будет ли работать все.

Я пробовал изменить только его не меняя не какие другие конфиги он все равно автоматом после перезагрузки присваеват 1745, сейчас настроил руками use 53 port
В конфиге agh 53 вместо 1745
Dnsmasq повесил на 6900
И изменил строку 127.0.0.1#1745 на 127.0
0.1#53

**Comment by spot320** [comment]
Жду поднятия интерфейсов и напишу что да как с фото

**Comment by spot320** [comment]
Все также ещё и в интернет не пускает хотя на роутер он приходит, сейчас получается что на dnsmasq весит на 6900 , в этот момент сам agh все равно на 1745

**Comment by spot320** [comment]
Заметил что если выбрать redirect 53 port to AGH  и поправить его конфиг на 53 порт, также поправить dnsmasqq на 6900 и 127.0.0.1#53 то после перезагрузки все в настройках веб морды сохраняется типо agh висит на 53, но если посмотреть netstat -tlp то ад не привязан не к какому порту domain

**Comment by spot320** [comment]
Попробую написать китайцам которые написали скрипт под опенар, не уверен что поймут меня, но думаю стоит попробовать

**Comment by ameshkov** [comment]
Ну да, скорее им надо писать, мне прям тяжело что-то посоветовать.

**Comment by spot320** [comment]
> Ну да, скорее им надо писать, мне прям тяжело что-то посоветовать.

Все не чего, только они не отвечают.
