### ISSUE TITLE
GUI: Reduce Size of the Query Log to show more entries

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2064]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Problem Description
Please reduce the size of the Query Log more in a compact way:

![grafik](https://user-images.githubusercontent.com/25774289/92232192-6dad1000-eeae-11ea-9b8d-cce50d95ab45.png)

This Design creates too many pages to scroll.

![grafik](https://user-images.githubusercontent.com/25774289/92232237-80bfe000-eeae-11ea-8b80-1b0fd659dcda.png)

**Comment by ameshkov** [comment]
The query log now supports infinite scrolling so this issue is resolved
