### ISSUE TITLE
Proxmox + AdGuardHome DHCP

### ISSUE THREAD

**Issue by AkgunFatih** [AdguardTeam/AdGuardHome#2066]
Hello, i am running Proxmox on my dedicated server and running AdGuardHome as a VM ( Virtual Machine ) in ububtu 20.04

everything works like it should be but i have one issue where dhcp does not edit resolv.conf file when i create a new linux vm

i need to set the correct settings in resolv.conf file everytime i create new VM

i asked this on the proxmox forum https://forum.proxmox.com/threads/how-to-make-sure-the-corrent-nameservers-are-added-to-a-vm.75334/

and they told me thats an dhcp option

**Comment by ZeroClover** [comment]
DHCP Option 6 is used to push the DNS server. #1708 

However, the AGH should send its IP address to the client as the only DNS server.

AGH only has basic DHCP functionality; I recommend you to run a separate DHCP server for Proxmox (e.g., the free RouterOS CHR, which is what I do). They usually have more powerful features.

**Comment by AkgunFatih** [comment]
> DHCP Option 6 is used to push the DNS server. #1708
> 
> However, the AGH should send its IP address to the client as the only DNS server.
> 
> AGH only has basic DHCP functionality; I recommend you to run a separate DHCP server for Proxmox (e.g., the free RouterOS CHR, which is what I do). They usually have more powerful features.

Yes, i have just installed OPNsense and it works like a charm
