### ISSUE TITLE
Docker deployment issues

### ISSUE THREAD

**Issue by azrea** [AdguardTeam/AdGuardHome#2067]
1. Unable to replace installation wizard port 3000 to 3005, 30058. it result web interface unreachable
(no issue if replace port 80 with random ports)

>https://github.com/AdguardTeam/AdGuardHome/issues/2045#issuecomment-682375700 Maybe it's occupied on your host machine?

No. i also tested on https://labs.play-with-docker.com/

**Comment by zkzipoo** [comment]
when mapping the ports, maybe just change the ports on your host machine, not the container.
as follows:
`docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 4050:4050/tcp -p 443:443/tcp -p 853:853/tcp -p 3005:3000/tcp -d adguard/adguardhome:edge`

**Comment by azrea** [comment]
>when mapping the ports, maybe just change the ports on your host machine, not the container.

@zkzipoo i dont understand

**Comment by ameshkov** [comment]
Please read about Docker networking:
https://docs.docker.com/config/containers/container-networking/

`-p 53:53/udp` -- here the port on the left side means port on your host machine. port on the right side means port inside the docker container.

**Comment by azrea** [comment]
@zkzipoo thank you. now i noticed it correctly. @ameshkov thanks.
