### ISSUE TITLE
Continuous scrolling of query log is, at least, performance degrading

### ISSUE THREAD

**Issue by unixben** [AdguardTeam/AdGuardHome#2068]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.3-SNAPSHOT-07db05dd 
* **How did you setup DNS configuration:**
  * Docker image
* **If it's a router or IoT, please write device model:**
  * N/A
* **Operating system and version:**
  * Ubuntu 20.04.1 LTS 

### Expected Behavior
Performance should not degrade over time when viewing the query log.

### Actual Behavior
Scrolling through the query log results in large numbers of log entires being cached in the browser and over time this becomes unusable. It also makes the footer inaccessible, provides the user with no concept of how long the log is and the scroll bar no longer provides a reliable indication of position on the page.

### Screenshots
N/A

### Additional Information
Google Chrome 84.0.4147.135 (Official Build) (64-bit)

Please make this a user configurable option or remove entirely.

**Comment by ameshkov** [comment]
Yep, and it still is much better than how the paging looked like before this change.

I'll merge this task in #2075, we'll see if we can make paging a configurable option.
