### ISSUE TITLE
BUG: "Location" and "Network" icon is extremely large in "Clients (runtime)".

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2069]
Version: v0.103.3-8dc0108

![Xnip2020-09-05_22-02-47](https://user-images.githubusercontent.com/58100052/92306727-f36eaf80-efc3-11ea-8d36-1cbc5490b173.jpg)

**Comment by ameshkov** [comment]
The style in the query log is also problematic -- no more paddings, font-size is bigger than it was, etc:
![image](https://user-images.githubusercontent.com/5947035/92306779-64996d00-ef9a-11ea-93d6-efc7a0ccb177.png)

@ArtemBaskal restore the original style.
