### ISSUE TITLE
Cannot chose certain addresses with the installer when an interface has multiple addresses

### ISSUE THREAD

**Issue by PauloHeaven** [AdguardTeam/AdGuardHome#2071]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  0.103.3
* **How did you setup DNS configuration:**
  *  System
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  *  Ubuntu 20.04.1

### Expected Behavior

In the installer, I want to be able to chose between every address set up on my server

### Actual Behavior

I can either select all addresses, one IPv4, or one IPv6. And if I choose an IPv4, it won't listen to IPv6 and vice-versa.

### Screenshots

<details><summary>Screenshot:</summary>

![Capture d’écran, le 2020-09-05 à 22 21 57](https://user-images.githubusercontent.com/19797934/92316818-34b48e80-efc7-11ea-8f58-1c2f71c785a1.png)

</details>

**Comment by ameshkov** [comment]
Currently, it supports listening just to one network interface OR two all interfaces.

We're going to support it later, merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
