### ISSUE TITLE
Enabling non-secured DNS, DoT, DoH and HTTPS separately

### ISSUE THREAD

**Issue by PauloHeaven** [AdguardTeam/AdGuardHome#2072]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

It can be annoying sometimes when a port from one of these services is already in use on an IP address because it prevents you to enable all of them. Yes, we can change the port number, but if we don't need one of them, disabling it is a cleaner solution. In my case, I have nginx listening on 443, and I don't need DoH nor plaintext DNS. DoT will do.

### Proposed Solution

Having the possibility to individually check a service to enable it among everything that occupies a port.

**Comment by ameshkov** [comment]
That's simple, keep the HTTPS port empty, in this case, there will be no DOH there.

You may also use nginx as a reverse proxy for both admin interface and DOH: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy
