### ISSUE TITLE
Access control lists

### ISSUE THREAD

**Issue by PauloHeaven** [AdguardTeam/AdGuardHome#2073]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

If we use AdGuardHome on a server, it can be accessed by anyone.

### Proposed Solution

Implement the ability to restrain DNS answers to select subnets.

**Comment by ebanDev** [comment]
It is in fact possible to filter by clients! Go to https://IP.OF.MY.DNS.SERVER/#dns and look at the bottom, you have an Allowed Clients box :)
