### ISSUE TITLE
Can't identify domain names when using DoH

### ISSUE THREAD

**Issue by elcidowneador** [AdguardTeam/AdGuardHome#2074]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.103.3
* **How did you setup DNS configuration:**
 IoT
* **If it's a router or IoT, please write device model:**
 QNAP 

### Expected Behavior
When using DoH for upstream servers, i see domains in query log and statistics.

### Actual Behavior
If i use DoH upstream DNS instead of regular DNS, i can't identify queried domains, because appears like this:

```
7655582d-6324-ab25-5f16-1b3a4f6edfb6.local57,35048%

38963c71-5748-06db-2189-6c8ca7aa3079.local55,53446.48%
```

If i use regular DNS, this is not happen.

**Comment by ameshkov** [comment]
Please collect AdGuard Home logs for both cases -- plain DNS upstream and DOH upstream.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

Find these domains there and check what's going on with them.

If something is unclear with analyzing the log, post it here.
