### ISSUE TITLE
View AGH Stats via Terminal

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#2077]
I'd find it quite handy to be able to view an AGH snapshot, similar to what Glances provides for the system usage side of things, within a CLI.

This removes all the unnecessary white space and allows raw data to be viewed in headless environments, as well as headed environments.

**Comment by ameshkov** [comment]
Could you please explain what Glances is and point me to an example of their CLI interface?

Also, does it really matter if the environment is headless or not? You can make the admin interface listen to 127.0.0.1 and simply query the API to get the stats.
