### ISSUE TITLE
希望增加新功能

### ISSUE THREAD

**Issue by xiaoqi2020** [AdguardTeam/AdGuardHome#2080]
是否可以增加油猴脚本的功能？这样就可以统一为局域网电脑配置浏览器脚本了！

**Comment by Teaffanie** [comment]
不可能的他只是个dns

**Comment by ameshkov** [comment]
油猴脚本啊？你的意思是跟“AdGuard for Windows / Android / Mac”版本一样的功能吗？

**Comment by xiaoqi2020** [comment]
> •"Windows / Android / Mac 的守护者"？"

是的，应该是可以实现的吧？

**Comment by xiaoqi2020** [comment]
> 油猴脚本啊？你的意思是跟“AdGuard for Windows / Android / Mac”版本一样的功能吗？

是的，应该可以实现的吧？

**Comment by ameshkov** [comment]
不能用 “DNS” 发现这样的 🤷

**Comment by xiaoqi2020** [comment]
> 不能用 “DNS” 实现这样的 🤷

adguardhome可以像adguard一样使用广告过滤脚本，为啥不能像adguard一样加载油猴脚本呢？

**Comment by ameshkov** [comment]
因为 AdGuard 能滤全部的网络流量，所以它可以更改网页的 html，加油猴脚本。AdGuard Home 只能滤 DNS，所以它只能拦截域名而已。

**Comment by xiaoqi2020** [comment]
> 因为 AdGuard 能滤全部的网络流量，所以它可以更改网页的 html，加油猴脚本。AdGuard Home 只能滤 DNS，所以它只能拦截域名而已。
好的，明白了，谢谢您的解答！
