### ISSUE TITLE
Cannot access web interface

### ISSUE THREAD

**Issue by zkzipoo** [AdguardTeam/AdGuardHome#2082]
### Issue Details

* **Version of AdGuard Home server:**
  * adguard/adguardhome:latest from docker
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Asus AC86U
* **Operating system and version:**
  * Linux N1-NAS 5.5.0-rc6-aml-s9xxx #rc1.037 SMP PREEMPT Wed Feb 5 16:55:20 MSK 2020 aarch64 GNU/Linux

### Expected Behavior
Access web interface to do configurations

### Actual Behavior
This site can’t be reached saying that it refused to connect. But the service is working and it blocks ads.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

1. list of opening ports on my server and docker ps
![image](https://user-images.githubusercontent.com/3366892/92419250-39627980-f164-11ea-92db-2f1af8b14df3.png)

_Every other service can be accessed both with the ip and my local hostname(N1-NAS), but just adguard home refuse the connection. For example, Heimdall also listens on port 80 (mapping to 8088 on the local machine) can be accessed._

2. the service is working and generates logs

![image](https://user-images.githubusercontent.com/3366892/92419376-1daba300-f165-11ea-865c-4b2502752037.png)

3. TCP ports testing
8088 - Heimdall
9000 - Portainer
8081 - Adguardhome 

![image](https://user-images.githubusercontent.com/3366892/92419551-25b81280-f166-11ea-85d4-726332fdf6ce.png)

4. My AdGuardHome.yaml:
<pre><code>bind_host: 0.0.0.0
bind_port: 8081
users:
- name: zkzipoo
  password: $2a$10$nzJ4RvLbA1dXznxzSefq.Oe4xKvuJd/CR2TguHjnQ8jeStNqCoxMq
http_proxy: ""
language: en
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: 0.0.0.0
  port: 53
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 1
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - '[/50.168.192.in-addr.arpa/]192.168.50.1'
  - 1.1.1.1
  - 8.8.4.4
  - https://dns10.quad9.net/dns-query
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: false
  url: https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt
  name: AdAway
  id: 2
- enabled: false
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
- enabled: true
  url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
  name: Peter Lowe's List
  id: 1599225375
- enabled: true
  url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
  name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
  id: 1599225376
- enabled: true
  url: https://anti-ad.net/easylist.txt
  name: 'CHN: anti-AD'
  id: 1599225377
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 6</code></pre>

Please help and it really drives me crazy. I have been playing with it for days and haven't got a clue. Also, it seems to block Emby metadata search and plugin update as well.

**Comment by ameshkov** [comment]
> bind_port: 8081

Change the port to 80 here.

Please note, that this port is used INSIDE the docker image.
On your host machine you have mapped 8081 -> 80 so on your host machine it will be available on port 8081
