### ISSUE TITLE
[Feature request] Improved DNS server configuration exposure

### ISSUE THREAD

**Issue by Seia-Soto** [AdguardTeam/AdGuardHome#2084]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Recently, these days, I am watching a lot of DDoS attacks on the DNS server and I think AdGuard Home should pass the configs in AdGuard Home's configuration file to the original DNS provider/library. For instance, I have watched a lot of requests to attempt DNS amplification or to cause a malicious query for recursive DNSs and I don't think AdGuard Home is ready for security things. Selecting go as backend was a nice choice, so I don't want to proxy the DNS query again with another solution like bind9 server to expose my DNS server public. I am not mad at this but these security things would be nice.

### Proposed Solution

At least, I think it would be nice if there is a security-related configuration for AdGuard Home. Not only blocking the requests and rate-limiting but also ensuring the QoS by disabling the recursive option for DNS things.

### Alternatives Considered

None.

### Additional Information

I recently got an email from the Vultr security team and there needs to be a recursive option disabled. Following is the original content of the email:

```
Dear Customer,

Recent network security audits have detected some issues on your instances.  Please review the following reports and help us to ensure the security of our network:




== Recursive DNS servers ==
DNS is used to translate hostnames into IP addresses.  When DNS servers are misconfigured, they can be used to conduct DDOS attacks.  We recommend that all public DNS servers are configured to not permit recusrive DNS queries.  This configuration will still allow DNS for your domain names to work properly, but will prevent abuse

On Windows machines, you can disable recursive DNS:
1) Open 'Server Manager'
2) Expand Roles -> DNS Server -> DNS -> (Your Server's Name)
3) Right click on your server name, choose Properties
4) On the 'Advanced' tab, select 'Disable recursion (also disables forwarders)'
5) Click OK

On Linux machines, there are a few common DNS servers:

BIND:
1) Open your BIND configuration file
2) In the 'options' section, make sure you have 'recursion no;' and 'additional-from-cache no;'
3) Restart BIND after making any changes

DNSMasq:
Unfortunately, there is not a straight forward way to disable this within DNSMasq.  You would either need to modify the DNSMasq configuration so that it no longer listens on public IP addresses, or firewall off UDP port 53 to all hosts except your desired ones.

If for some reason you cannot make the necessary changes and you are not hosting your own DNS, we would suggest that you firewall off all incoming UDP port 53 traffic.

Please see https://blog.cloudflare.com/reflections-on-reflections/ for more information on reflection attacks.

The following IPs have been detected running open recursive DNS servers:




If you believe these reports to be false positives, please let us know.

-- Vultr.com Support Team --
```

**Comment by ameshkov** [comment]
> disabling the recursive option for DNS things

AdGuard Home is not a recursor but a forwarder, disabling recursion makes no sense for us. The same reason why dnsmasq does not provide any option for that.

Regarding the measures that we provide to mitigate DNS amplification, rate limiting, and having an access control list are basically the only viable options. The default rate limit is set to 20rps which is not bad (in the worst case, you'll create 100KB/s load at the attacked server which is basically nothing), but I still recommend you inspect the query log from time to time and block unknown clients (or better add domains that they use to the list of "disallowed domains").

I'd suggest explaining to Vultr that you have configured a rate limiter for your public DNS server and you're monitoring the situation with possible DNS amplification attacks, and there's no reason to worry about your server.
