### ISSUE TITLE
Reverse lookups return empty answers for hosts from /etc/hosts

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2085]
**Issue Details**

* **Version of AdGuard Home server:**
  * v0.103.3-SNAPSHOT-07db05dd

Query log
![Screenshot from 2020-09-09 13-51-36](https://user-images.githubusercontent.com/63988538/92565448-d9bfb780-f2a4-11ea-80fd-be39e6235e6d.png)
(Custom rules exist for ||in-addr.arpa^$important)

No rewrite rules in DNS rewrites (i didn't add since installation)
![Screenshot from 2020-09-09 13-53-26](https://user-images.githubusercontent.com/63988538/92565898-a16ca900-f2a5-11ea-8cf5-7e25a0182898.png)

**Comment by KizunaH** [comment]
Bug - 2
Why or does DNS rewrite override `||name^$important` rule?

**Comment by ameshkov** [comment]
Please do the following:

1. Open dev tools
2. Go to the network tab
3. Refresh the query log page
4. Find `/control/querylog` request
5. Find the log item that corresponds to that log record
6. Copy&Paste it here

**Comment by KizunaH** [comment]
That seems not possible with new infinite scrolling query log, it's quite buggy. i have to load 5hrs+ for locate corresponds log records and when i keep scrolling so far 4hrs then auto bring me back to current time. sometimes query log load faster and there's a preview shaking issue.

I shall upload video samples explaining that bugs through new issue but i dont know how to provide above you requested details.

**Comment by ameshkov** [comment]
Hm, so the issue can't be reproduced?

Alternatively, you can simply open the query log file and locate that request there

**Comment by KizunaH** [comment]
> Hm, so the issue can't be reproduced?

It's quite difficult with developer tools. i didnt realize ago that you were looking for particular log record. 💫

> Alternatively, you can simply open the query log file and locate that request there

{"IP":"192.168.8.118","T":"2020-09-09T06:03:21.930173488Z","QH":"2.0.17.172.in-addr.arpa","QT":"PTR","QC":"IN","CP":"","Answer":"gLyBgAABAAAAAAAAATIBMAIxNwMxNzIHaW4tYWRkcgRhcnBhAAAMAAE=","Result":{"Reason":10,"ReverseHost":"9b44805c1169."},"Elapsed":80957}

{"IP":"192.168.8.118","T":"2020-09-09T06:03:21.930173488Z","QH":"2.0.17.172.in-addr.arpa","QT":"PTR","QC":"IN","CP":"","Answer":"gLyBgAABAAAAAAAAATIBMAIxNwMxNzIHaW4tYWRkcgRhcnBhAAAMAAE=","Result":{"Reason":10,"ReverseHost":"9b44805c1169."},"Elapsed":80957}

**Comment by ameshkov** [comment]
172.17.0.2 -- do you have a record in the /etc/hosts with this IP or does it come from AGH DHCP?

**Comment by KizunaH** [comment]
`etc/hosts` and i see it on AGH clients (runtime) list. In this cause above, i expect AGH follow the user defined filtering rule (if exist).

**Comment by ameshkov** [comment]
Hm, these queries are processed automatically by AdGuard itself and that's why they don't get to the filtering engine at all.

**Comment by ameshkov** [comment]
I guess I can tweak the priorities a bit though

**Comment by ameshkov** [comment]
Well, on the other hand, that would be wrong. These come from your hosts files. Just like DNS rewrites, it has higher priority than filtering rules for AGH.
