### ISSUE TITLE
Enhancement for DNS blocking mode

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2089]
See the below screenshot. It has separate areas for blocking mode explanation and toggle buttons. Past toggle options had under single line but it also has extended, may be for compatible with mobile screens. anyway this take unnecessary area.
![Screenshot from 2020-09-10 13-33-24](https://user-images.githubusercontent.com/63988538/92709014-c71ab080-f380-11ea-91c5-cc7ff39423d5.png)
![Screens](https://user-images.githubusercontent.com/63988538/92709160-e1ed2500-f380-11ea-95e8-436a69c29752.png)

**Comment by ameshkov** [comment]
Merged to https://github.com/AdguardTeam/AdGuardHome/issues/2075
