### ISSUE TITLE
Cannot change minimum TTL override in UI

### ISSUE THREAD

**Issue by KilometerM** [AdguardTeam/AdGuardHome#2091]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 2 and Raspberry Pi Zero W
* **Operating system and version:**
  * Ubuntu Core 18 (RPi 2, snap version) and Raspbian 10/Buster (RPi Zero W, armv6 binary from github)

### Expected Behavior
Under "Override minimum TTL" I would be able to successfully specify a new minimum TTL as long as it did not exceed 3600.

### Actual Behavior
Any value other than 0 produces a "Minimum value exceeds maximum value" message in red text even when that value is less than 3600.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/65037176/92761388-dc76e700-f34e-11ea-8029-9b130f333a72.png)

</details>

### Additional Information
I have reproduced this issue in Firefox and Chrome (latest versions) on macOS and in Safari on iOS. I am able to successfully modify the override ttl values by changing them within the yaml file and restarting the service.

**Comment by Ulmisch** [comment]
You have to edit the maximum TTL first.
E.g. set it to 14400.
Then you will be able to adjust the minimumTTL.

**Comment by KilometerM** [comment]
Ah, I see. Thank you. I was interpreting “maximum value” as 3600 as referenced in the helper text. So in this case, you can’t set a minimum without overriding the maximum? Because in this case, “0” means you’re not overriding the max, not that you’re actually overriding the max ttl to 0 seconds. 

I’d think you should be able to set a minimum ttl, but not care how high maximum could be set. If not, maybe a reword of the error or helper text should be considered, so it’s not clear that you have to set both and that you have to set max before you can adjust minimum.

**Comment by ameshkov** [comment]
We should make it clear in the UI. @ArtemBaskal let's just show an empty input if the value is not set for min/max TTL.

Also, I am not sure that this is right to not allow overriding just the minimum TTL, please check the code and verify if it is or not.

**Comment by lhzw** [comment]
I met this problem yesterday night, oh, that's too strange, after a long time, I got the point.

**Comment by ameshkov** [comment]
@ArtemBaskal 

> let's just show an empty input if the value is not set for min/max TTL

This is not done

**Comment by lhzw** [comment]
I tested the edge docker image, I could set a large value in the cache-min-ttl field, saved okay. But the actual min-ttl was still 3600s.

**Comment by ameshkov** [comment]
@ArtemBaskal `dnsproxy` needs to be updated to v0.32.6. Please do this and don't forget to run `go mod tidy` after updating `go.mod`.
