### ISSUE TITLE
AdGuard Home with VLANs - No Data/Logs

### ISSUE THREAD

**Issue by SavellM** [AdguardTeam/AdGuardHome#2092]
### Prerequisites

I am running the latest version

### Issue Details

* **Version of AdGuard Home server:**
0.103.3
* **How did you setup DNS configuration:**
pfSense Router -> LAN DHCP Settings -> DNS Server -> <IP of AdGuard>
pfSense Router -> IoT DHCP Settings -> DNS Server -> <IP of AdGuard>
pfSense Router -> Guest DHCP Settings -> DNS Server -> <IP of AdGuard>
pfSense Router -> Rules for IoT/Guest to allow access to IP of AdGuard.
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4
* **Operating system and version:**
Raspberry Pi OS
### Expected Behavior
AdGuard is not showing any logs or IP addresses of any network other than the network it is installed upon.
It is serving traffic as DNS is working on IoT and Guest VLANS but there is no way to query the logs or see any IP's from any other network other than the main network it is installed on.
### Actual Behavior
No IP's shown for VLANS
### Additional Information
I would really like AdGuard to allow other networks logging, so we can monitor/whitelist and so on anything that is going on in our other networks.

**Comment by ameshkov** [comment]
Tbh, this seems to be router-specific and it's hard for me to advise anything.

Marked as "help wanted", maybe some other people who have the same router may shed some light.

**Comment by josephbu** [comment]
I have multiple AdGuard instances that are answering queries from networks other than the one they are installed on, the logging of the remote IP addresses is working perfectly ok.

- Is pFsense Nat'ing the queries to the LAN DHCP server, so you only see the LAN IP of the pFsense in your query logs?
- Is pFsense doing some sort of DNS redirect/intercept sending the queries elsewhere?

You could verify with tcpdump on the PI to see if the queries are arriving directly from the other networks with their source IP intact.

**Comment by mrfrankbell** [comment]
Just in case this helps someone else, I experienced this when I had content filtering enabled on the VLAN (Unifi Dream Machine).
