### ISSUE TITLE
DNS cache check and the cache hit ratio

### ISSUE THREAD

**Issue by lhzw** [AdguardTeam/AdGuardHome#2093]
### My version:
2020/09/12 01:51:34 69#1 [info] AdGuard Home, version v0.103.3, channel release, arch linux amd64

### Problem Description
I'd like to check the dns cache, and the cache hit ratio. But I didn't find it anywhere.

### Proposed Solution
Like dnsmasq, show the caches and the queries forwarded and queries answered locally:
dnsmasq[1]: queries forwarded 305, queries answered locally 348

Show it on the web gui, or a command are both fine to me.

Thank you for your awesome work.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/1685

**Comment by lhzw** [comment]
Duplicates #1453
