### ISSUE TITLE
Remove the limit on cache-min-ttl, 3600 is too short to me

### ISSUE THREAD

**Issue by lhzw** [AdguardTeam/AdGuardHome#2094]
### Prerequisites

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Problem Description

As now the cache-min-ttl's limit is 3600s, to me it's too short, I want to enlarge it but I cannot with the official docker image. Or I will have to build it by myself, it's just a waste of the energy from my viewpoint, and I cannot use the official ones smoothly.
And I think the limit of one hour is too arbitrary, there's no reason to use one hour as the limit other than half an hour or two hours. So I think the best is to let the user make the decision.

### Proposed Solution

Please remove the limit on cache-min-ttl, we should believe our users can do the corrent thing, know the pros and cons, just like linux.

**Comment by ameshkov** [comment]
@ArtemBaskal please change the validation and allow any values in that field (up to int max value).

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/2a5b0b8da1f85727e36a4601c51bdfb79ef2583f
