### ISSUE TITLE
Optimize the menu and submenu

### ISSUE THREAD

**Issue by lhzw** [AdguardTeam/AdGuardHome#2095]
### Problem Description

I am new to your outstanding product, so I browse the web gui, but the menu is a little inconvenient. Such as I have to click the menu "Settings", then click one submenu, scroll down, then I want to check another one, oh I need to scroll back to the head, then repeat the click and click procedure, it's boring.
To a new submenu page, I need to scroll back and at least two clicks, unhappy.

It's very unfriendly to the newcomers, as the experts just use the yaml to configure it.

### Proposed Solution

1. Put the menu to the side, then it's fixed there, and we can expand the menu it it has submenus, then we can move to a new page very easily.

2.1 Keep the menu on the top, but float it, then we don't need to scroll to the head to find the top menu;
2.2 Auto pop the submenu if it has submenus when mouse is hovering on it, then we can save one click, that's much better.

**Comment by ameshkov** [comment]
> Put the menu to the side, then it's fixed there, and we can expand the menu it it has submenus, then we can move to a new page very easily.

That's exactly what we're planning to do in the re-designed version.
