### ISSUE TITLE
Release 103.3 tar.gz file contains wrong version

### ISSUE THREAD

**Issue by schuby-doo** [AdguardTeam/AdGuardHome#2097]
Hallo,

i downloaded the latest Realease 0.103.3 as tar.gz for arm (https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.103.3/AdGuardHome_linux_arm.tar.gz)
When i start AdGuardHome with parameter --Version it says it's "AdGuardHome v0.102.0"

* **Version of AdGuard Home server:**
  - should be 0.103.3 but is 0.102.0
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4
* **Operating system and version:**
  * Raspberry OS

### Expected Behavior
downloading Release 103.3 and starting it with ./AdGuardHome --version should show Version 103.3 not 102.0

### Actual Behavior
./AdGuardHome --version shows 102.0

### Screenshots
![AdguardHome-Issue](https://user-images.githubusercontent.com/19798905/92998199-c74db400-f518-11ea-8faf-e244723bcbc9.jpg)

### Additional Information
https://github.com/hassio-addons/addon-adguard-home/issues/78

The hassio-addon downloads the arm.tar.gz-File and runs it in docker.
See Docker File https://github.com/hassio-addons/addon-adguard-home/blob/master/adguard/Dockerfile

**Comment by ameshkov** [comment]
My mistake, sorry about this. There should have been no `arm` tar.gz at all, `armv6` or `armv7` is supposed to be used instead.

For release v0.103.3 I've fixed this, `arm` points to the same archive as `armv6`.
