### ISSUE TITLE
Allow AdGuard to finish setup with DHCP only configured network interfaces

### ISSUE THREAD

**Issue by DiogoConstantino** [AdguardTeam/AdGuardHome#2101]
### Problem Description
When setting up AdGuard it doesn't allow me to complete it because none of my network interfaces is setup with a static IP Address

### Proposed Solution
Warn users about the possible, risk but allow them to continue, DHCP maybe in use to do static leases for one or more of the network interfaces.

### Alternatives Considered
N/a

### Additional Information
DHCP maybe in use to do static leases for one or more of the network interfaces, and with Ubuntu Core Appliance it's not simple for most people to reconfigure network interfaces to avoid this issue, they would have to setup it all again, and that's very annoying, and possibly also unecessary.

**Comment by ameshkov** [comment]
> When setting up AdGuard it doesn't allow me to complete it because none of my network interfaces is setup with a static IP Address

It actually does allow you to continue, it is not mandatory to set a static IP.

Why do you think it is?
