### ISSUE TITLE
Infinite query log bugs

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#2103]
See short videos about bugs explanations.

1. Query log contain wrong date records in middle. (see the date and time area)
https://mega.nz/file/YG5z3IiZ#AMoCPJN-55U5bf0M7FCY_FOjKWhkyGvLtHVP9QWVdCo
2. Scrolling get locked when scrolling too much. (this's not mouse issue)
https://mega.nz/file/YSgXyaLI#L7ERtzd5Gxe1VEBEstPbj8xCQkFGvEvFoa1TOebX-Ps
3. Flashing query log when scrolling longer. (it may possible to reproduce easily when has less records)
https://mega.nz/file/tDgBjA6Y#zoGVsM4SYSHRH_tYLFMwM1Tke2ry5rm-4-0tAec7pHQ
4. Scrolling so far 1-2 days bring back to current time then unable to view old queries.
https://mega.nz/file/wDwVjSCA#HkMkl6I9ylEH8dOA9JVatbK_owv7t8D7ROjhQgTV9V8

According to my experience, loading several days or more history quite worst task with AGH (even before implement infinite mode)

v0.103.3-SNAPSHOT-07db05dd | Chromium Version 85.0.4183.102 (Official Build) snap (64-bit)

**Comment by ameshkov** [comment]
Do you mind sharing querylog*.json files with us privately? I cannot reproduce 1,3 and 4 on my side, but maybe with your log file I'll be able to do it.

**Comment by Rru247** [comment]
> Do you mind sharing querylog*.json files with us privately? I cannot reproduce 1,3 and 4 on my side, but maybe with your log file I'll be able to do it.

That's impossible. may be take a note about that bugs for later enhancements or try to enhance query log by guessing possible reasons. this's still edge builds then other users may report and help with querylog files.
I tried to give some help for get these fixed before reach stable :)

**Comment by ameshkov** [comment]
Yeah, no problem:)

Do you have any hint about how to reproduce these? I see on your videos that it happens about 00:00 so maybe it happens when query log files are rotated. Could you please check your both querylog files -- are these records located in the very end or beginning of these files?

**Comment by temporallyaccount** [comment]
Query log has 6 days logs for now - 23664 records (from 09/09 to 09/15) 

09/09 - 2937 records 
09/10 - 4188 records
09/11 - 3439 records
09/12 - 3190 records
09/13 - 5493 records
09/14 - 4098 records
09/15 -   319 records

I dont have idea about specific way to reproduce and i can't find exact records belong to 1st issue due .json file written using different timezone but when checked using atom (find in buffer) then couldn't find such date mixed records.

**Comment by ameshkov** [comment]
Does this mixing always happen about 00:00?

**Comment by temporallyaccount** [comment]
> Does this mixing always happen about 00:00?

No. in other times too. Yesterday i noticed a one similar eg: 11:15:15 - 10:08:05 - 11:16:18 (log bit longer and didn't had time to make a video) but today i can't view that history due 4th bug.

**Comment by ameshkov** [comment]
I guess we need to provide some "query log anonymizing" tool that would make sharing logs possible:)

**Comment by temporallyaccount** [comment]
It'll be good for that purpose and related feature request #1176 (it also for sharing according to explanation)

**Comment by ameshkov** [comment]
@temporallyaccount please use this tool:
https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts/querylog

But please check that the error is reproducible with the anonymized query log as well.

**Comment by temporallyaccount** [comment]
> @temporallyaccount please use this tool:
> https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts/querylog
> 
> But please check that the error is reproducible with the anonymized query log as well.

I thought to add a comment because i felt bad that i already late many days to provide it (actually too busy and couldn't take a moment to sit for this) and thank you for made it. I'll check if it possible to reproduce using anonymized log and will provide necessary details very soon.

**Comment by temporallyaccount** [comment]
Bugs and anonymized query log. Sorry for delay many days to provide.

>1. Query log contain wrong date records in middle. (see the date and time area)

It's reproducible with anonymized query log
https://mega.nz/file/tWJzwQwS#QjNLfu50i-gtO95_wm4G-a5jSnNeHluCzoofkxXqXGc
https://mega.nz/file/oKBDkaBD#T1H-SiqiI07_3R6n8WaNeokdH5RrjLB9qOzqLzDn0D4

Version: v0.104.0-beta1-SNAPSHOT-20226edb
Docker version 19.03.13, build 4484c46d9d

Bugs 3 and 4
It must be reproducible somehow, doesn't need anonymized query log for it

**Comment by ameshkov** [comment]
Awesome, thank you!

**Comment by temporallyaccount** [comment]
> Plz don't remove the files from Mega until the issue is resolved.

No. but there's a problem on free accounts if i forgot to login within 3 months https://help.mega.nz/webclient/accounts-pro-accounts.html#will-my-free-pro-account-ever-expire

**Comment by ArtemBaskal** [comment]
@temporallyaccount Does this issue reproduce in the latest release? Most likely this problem has been solved in
https://github.com/AdguardTeam/AdGuardHome/issues/2229
