### ISSUE TITLE
Add support for modifying "edns-buffer-size".

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2104]
[DNS flag day 2020](https://dnsflagday.net/2020/index.html)

![Xnip2020-09-15_13-55-02](https://user-images.githubusercontent.com/58100052/93171125-11be7300-f75b-11ea-8db4-cf7a1d07eef8.jpg)

**Comment by ameshkov** [comment]
This makes sense for authoritative and recursor servers, not forwarders like AGH

But thank you, anyway:)
