### ISSUE TITLE
Seperate Configurations?

### ISSUE THREAD

**Issue by 91ajames** [AdguardTeam/AdGuardHome#2109]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Alternatives Considered
Couldn't find if this was asked.

Is it possible to have separate config files for UpStream DNS / Bootstrap DNS Servers from joint AdList and maybe from other settings by Default?
Wanted to have a automation script without taking away the First Startup Dashboard like creating a password. Since its possible to get into it without a password bypassing the setup on p 3000 due to seeing a yml file. Not sure if you want to count that as a bad thing for security.

**Comment by ameshkov** [comment]
Not for bootstrap, but it's possible to load upstreams list from a file: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file

Please note, that you need to use Edge or Beta versions to have this.
