### ISSUE TITLE
Hosts-Blocklist wiki should mention how modifiers are chained

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#2111]
The [wiki article](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#modifiers) for Hosts-Blocklist should mention that modifiers are chained with `,` and should list an example somewhere

**Comment by ameshkov** [comment]
Done: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#modifiers
