### ISSUE TITLE
[Feature request] Block diferent DNS record types

### ISSUE THREAD

**Issue by JoseGalRe** [AdguardTeam/AdGuardHome#2112]
### Problem Description
Currently we only can block type AAAA in DNS section.

### Proposed Solution
Create a segment that allows blocking the different types of DNS recods in global mode and in the future to different devices.

`for example block TYPE65 in global mode or ip devices with IOS14`

**Comment by ameshkov** [comment]
Do you mean that you'd like to block TYPE65, but keep other query types untouched?

**Comment by JoseGalRe** [comment]
> Do you mean that you'd like to block TYPE65, but keep other query types untouched?

anyone, it would be good to have a control to be able to block any type, TXT, A, PTR, CNAME, CAA, TYPE65, etc.
at least the mosts common

**Comment by ameshkov** [comment]
I mentioned how it could be implemented here: https://github.com/AdguardTeam/AdGuardHome/issues/1570#issuecomment-693288528

**Comment by DandelionSprout** [comment]
I'm in favour of a way to block all RRSIG requests. I am aware of absolutely no legimitate uses of such requests anyway; they only seem to be used by hackers to request `pizzaseo.com`.

**Comment by ameshkov** [comment]
> they only seem to be used by hackers to request pizzaseo.com

I'd suggest adding this to Disallowed domains then. Blocking requests is not the same.

**Comment by devinslick** [comment]
Would this help allow/block LetsEncrypt TXT record lookups?
I believe AGH wildcard rewrites effect TXT records.  It would be nice to have a way to override this behavior.
Being able to allow, block, or use an upstream for a different record time might fix cert renewal in split dns AND accomplish what OP is requesting, but that sounds like a big effort.

**Comment by ameshkov** [comment]
Merged into #2337

**Comment by ameshkov** [comment]
> Would this help allow/block LetsEncrypt TXT record lookups?

Well, why not
