### ISSUE TITLE
[FeatureRequest] Blocking Page?

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2114]
Hi there,

an 5th Option "Redirect to Blocking Page" would be awesome. Running an own Webserver only to show a blocking page is a little bit too much (Option No 4).

```
1. REFUSED: Respond with REFUSED code
2. NXDOMAIN: Respond with NXDOMAIN code
3. Null IP: Respond with zero IP address (0.0.0.0 for A; :: for AAAA)
4. Custom IP: Respond with a manually set IP address
```

**Comment by ameshkov** [comment]
Unfortunately, it's not easy at all and it anyway would require running a server on a specific IP and a rather complicated setup.

AdGuard Home would need to listen to one IP, blocking page server to another IP, and that IP would be served in A responses (not sure what to do with AAAA).

All in all, this is really complicated and the benefits are questionable.
