### ISSUE TITLE
Bug: Query Log Search field will not consider Client Name

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2116]
`Version: v0.104.0-beta1-SNAPSHOT-deeaca5d`

Query Log search field will not consider Client Name (only IP works)

![image](https://user-images.githubusercontent.com/25774289/93563640-980bcc80-f988-11ea-8aff-880884c55575.png)

**Bug or Feature?**

**Comment by ameshkov** [comment]
Neither bug nor feature, using client name for searching just not implemented yet.

Duplicates: https://github.com/AdguardTeam/AdGuardHome/issues/1273
