### ISSUE TITLE
A special control panel option for very tall screens

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#2118]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.104.0-beta1-SNAPSHOT-3a71374f)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

On my PC screen, which most of the time is 1440x2560 in portrait orientation (Long story), the default height of many objects in the control panel does not fill the space well at all: 
![image](https://user-images.githubusercontent.com/22780683/93722873-3327c080-fb9a-11ea-889f-84133f2130b6.png)

However, with the following entries, the space is much better utilised on large and/or tall monitors, thus I'd have liked some kind of option or setting within AGH to use such wider/taller CSS elements:
```
[The AGH server's domain]#?#.container:style(max-width: 99vw !important)
[The AGH server's domain]#?#.card-table-overflow--limited:style(max-height: 30vh !important)
[The AGH server's domain]#?##disallowed_clients:style(min-height: 300px)
[The AGH server's domain]#?#.dashboard .card:not(.card--full):style(height: unset !important)
```
![image](https://user-images.githubusercontent.com/22780683/93722931-b77a4380-fb9a-11ea-96a3-11b9cfda2a56.png)

Very similarly, the blocklist menu always shows 10 listrows per page by default, with no known way to change it. An option / auto-feature to change it to 20/25 when loading the menu would be lovely: 
![image](https://user-images.githubusercontent.com/22780683/93722977-20fa5200-fb9b-11ea-8198-a806c0210f90.png)

### Proposed Solution
The idea I had when writing this request, was for a setting that'd initiate a "Very tall monitor mode" and save the turning-on of such a setting in the browser; since having the setting turned on on a PC, would be a very bad thing if it also turned it on on phones.

### Alternatives Considered
* That a "Very big monitor mode" that also targeted 4K screens was made, instead of merely a "Very tall monitor mode".
* That the CSS elements for big/tall monitors was triggered by detecting the screen resolution, which is already being done to show the dashboard on small phones in 1 column instead of 2.
* Standalone settings to choose the default amount of rows in "Filters" and "Client settings", without depending on the monitor size.

### Additional Information
I've been thinking about submitting this for some months now, but never got around to doing it before now.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
