### ISSUE TITLE
Still letting ads through

### ISSUE THREAD

**Issue by aliekiddo** [AdguardTeam/AdGuardHome#2119]
AdGuard Home 2.5.0 on Home Assistant 0.114.4 running as a VM on FreeNAS-11.3-U4.1

### Expected Behavior
Ads blocked, blocked services sites to be blocked, redirects to send traffic to specified site

### Actual Behavior
My ultimate aim would be to block YouTube video ads on Chromecast, so this is why I have set up AdGuard to act as a network level blocker. I have been running AdBlock Plus on my Macbook / PC's and AdAway / DNS66 on Android devices until now.

I have disabled ABP on my macbook to test AdGuard, AdGuard is acting as the networks DNS and DHCP server (192.168.1.2), I can see that it is 'working' from the dashboard.
I am still seeing ads on though on webpages, redirects are not working, and blocked services are being allowed through i.e. Facebook on all of my devices.

In MacOS Terminal however, it acts like the sites **are** being blocked or redirected:

> ~ % host facebook.com
> Host facebook.com not found: 3(NXDOMAIN)

> ~ % host amazon.com
> amazon.com is an alias for google.com.
> google.com has address 172.217.169.78
> GoOgLe.Com has IPv6 address 2a00:1450:4007:80a::200e
> google.com mail is handled by 10 aspmx.l.google.com.
> google.com mail is handled by 20 alt1.aspmx.l.google.com.
> google.com mail is handled by 50 alt4.aspmx.l.google.com.
> google.com mail is handled by 30 alt2.aspmx.l.google.com.
> google.com mail is handled by 40 alt3.aspmx.l.google.com.

### Screenshots

Router configured to use AdGuard's IP 192.168.1.2 as the DNS and DHCP:
<img width="392" alt="Screenshot 2020-09-21 at 00 07 33" src="https://user-images.githubusercontent.com/7974754/93724389-797f1e80-fb9e-11ea-8034-07d57d0f86ee.png">

Block lists used:
<img width="1201" alt="Screenshot 2020-09-21 at 00 11 29" src="https://user-images.githubusercontent.com/7974754/93724485-6882dd00-fb9f-11ea-8002-16dde99bb6b1.png">

DNS Config:
<img width="1076" alt="Screenshot 2020-09-21 at 00 11 08" src="https://user-images.githubusercontent.com/7974754/93724505-9a943f00-fb9f-11ea-9cbc-f1e02e06828f.png">

Redirect Amazon to Google:
<img width="1184" alt="Screenshot 2020-09-21 at 00 25 05" src="https://user-images.githubusercontent.com/7974754/93724652-eeebee80-fba0-11ea-8905-aeb4673b4b83.png">

Redirect Result:
<img width="1678" alt="Screenshot 2020-09-21 at 00 13 35" src="https://user-images.githubusercontent.com/7974754/93724523-be578500-fb9f-11ea-8ef8-524ae81c11cc.png">

Ad Block Test Page Results:
<img width="393" alt="Screenshot 2020-09-20 at 23 58 43" src="https://user-images.githubusercontent.com/7974754/93724268-759ecc80-fb9d-11ea-9d7c-f7466c3d109d.png">

Blocked Services - Facebook:
<img width="1203" alt="Screenshot 2020-09-20 at 23 54 21" src="https://user-images.githubusercontent.com/7974754/93724609-94529280-fba0-11ea-887d-fba6c1af7fab.png">

Facebook still showing
<img width="1206" alt="Screenshot 2020-09-20 at 23 54 37" src="https://user-images.githubusercontent.com/7974754/93724264-691a7400-fb9d-11ea-844a-dd736bd84640.png">

Macbook DNS automatic settings showing connected to AdGuard
<img width="736" alt="Screenshot 2020-09-20 at 23 51 02" src="https://user-images.githubusercontent.com/7974754/93724709-7fc2ca00-fba1-11ea-886a-30ee73520636.png">

**Comment by ameshkov** [comment]
> Redirect Result:

Note that DNS redirect is different from a web redirect, it will simply break amazon if you do it this way.
Also, note that it's `www.amazon.com`.

> Facebook still showing

There're several options:
1. Chrome may be caching the DNS resolution result from previous times
2. If you use a VPN or a proxy extension, it will ignore DNS.

One more thing to try: change blocking mode to "Null IP" and see if it changes anything.

**Comment by aliekiddo** [comment]
> > Redirect Result:
> 
> Note that DNS redirect is different from a web redirect, it will simply break amazon if you do it this way.
> Also, note that it's `www.amazon.com`.

Thanks, I've been trying to find _any_ evidence that it's working by testing out redirects and Facebook blocking for something more obvious, so neither are intended to be permanent fixtures :)

> > Facebook still showing
> 
> There're several options:
> 
>     1. Chrome may be caching the DNS resolution result from previous times
> 
>     2. If you use a VPN or a proxy extension, it will ignore DNS.
> 
> 
> One more thing to try: change blocking mode to "Null IP" and see if it changes anything.

I've had a bit of luck now in an incognito windows to block ads on the test site https://ads-blocker.com/testing/ and I've been able to block Facebook (on Chrome, not Firefox) so this may likely be a caching issue per browser. I have also changed the mode to Null IP which may also have contributed.
 
I'm not using a VPN and I'd disabled the adblock browser extension fully. I had flushed the DNS on my macbook between testing sessions, so I had assumed there would have been enough to clear any local data.

I will clear the local browser data and see if that starts yielding results

**Comment by aliekiddo** [comment]
Everything appears to be good except for in Firefox which is still showing ads, despite clearing data, history, restarting etc...

**Comment by ameshkov** [comment]
> Everything appears to be good except for in Firefox which is still showing ads, despite clearing data, history, restarting etc...

Firefox by default uses Cloudflare DNS, this may be the reason. You can disable it in the network settings.

**Comment by aliekiddo** [comment]
> > Everything appears to be good except for in Firefox which is still showing ads, despite clearing data, history, restarting etc...
> 
> Firefox by default uses Cloudflare DNS, this may be the reason. You can disable it in the network settings.

That certainly explains it, I've seen on a few other devices that Facebook is being blocked.
I'll mark this as closed as I've been able to achieve the aim of proving AdGuard is successfully working on my network.

Thanks for your help Andrey :)
