### ISSUE TITLE
Improvement: Move Language Settings to "General Settings"

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2121]
I would recommend moving the language settings to the "General Settings" section.

![image](https://user-images.githubusercontent.com/25774289/93765284-e92ff080-fc14-11ea-9234-8739cdbb1c38.png)
![image](https://user-images.githubusercontent.com/25774289/93765326-f8af3980-fc14-11ea-9164-31658a90a3bc.png)

This would have several advantages:

- you save space on each page (especially useful on mobile devices)
- the footer is useless on Query Log since the introduction of Infinity Scroll

**Comment by KizunaH** [comment]
It's good to have it somewhere that able to see often rather hidden in mysterious settings area. Recent redesign (or older version) footer was changed and now it display in two lines on desktop (also bit larger for mobile page but may be for compatible with screens). again, language selection suitable to display on login screen as well.

AdGuardHome add internal stats https://github.com/AdguardTeam/AdGuardHome/issues/1685 update and account management options within upcoming versions then it might be possible to throw less important contents similar 'Homepage', 'Privacy policy', 'Copyright' and 'Version' to there but **it's important to keep 'Language' and 'Report an issue' buttons in the footer or top**.

**Comment by ameshkov** [comment]
This is up to our designer, I am okay with anything, be it footer or general settings.

Marked as dup, the final decision will be made by the designer when we'll be baking the redesigned version.
