### ISSUE TITLE
Improvement: More intensive RGB color value for blocked Query Logs

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2123]
The selected red for the background color of the query log is too bright. Especially on the iPhone the contrast is much too low. I recommend a more intensive RGB color value.

Current setting:

![image](https://user-images.githubusercontent.com/25774289/93766175-51330680-fc16-11ea-941f-02c9e1c20ce1.png)

**Comment by ameshkov** [comment]
Well, this is subjective. Personally, I prefer the current color, making it more intensive would be annoying.
