### ISSUE TITLE
Add ARMv8 to future releases, potentially append a v8 binary to the most recent non-beta release

### ISSUE THREAD

**Issue by sanecito** [AdguardTeam/AdGuardHome#2125]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

The problem is that currently there is no clear way to install AdGuard Home on routers running w/ [ARMv8 CPUs like the Turris MOX](https://doc.turris.cz/doc/en/howto/mox/mox-a-cpu) which is roughly two years old at this point. As newer routers come out w/ ARMv8 CPU's there will similarly be no way to install AdGuard Home on them.

### Proposed Solution

Provide Linux ARMv8 in future releases. Potentially append ARMv8 to the most recent non-beta release at time of writing so that people can start using it rather than wait for a future release: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.103.3

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by ameshkov** [comment]
v0.104 is coming soon, I guess we can add it there no prob

**Comment by szolin** [comment]
> As newer routers come out w/ ARMv8 CPU's there will similarly be no way to install AdGuard Home on them.

ARMv8 builds are marked as `arm64` - please try to install `AdGuardHome_linux_arm64.tar.gz` on your device.
