### ISSUE TITLE
Service is probabilistically unavailable

### ISSUE THREAD

**Issue by 991547436** [AdguardTeam/AdGuardHome#2126]
After using for a period of time, the dns service will become unavailable, and the background process will still be displayed normally, and it will work after restarting the service. One to three times a day.Is the number of concurrent services too large? Is there any way to print logs?

version:0.103.3

使用一段时间后dns服务会变得不可用,后台进程任然显示正常，重启服务后才行。一天会有一到三次。是服务并发数太大了吗，有什么办法可以打印日志

![企业微信截图_16004295174716](https://user-images.githubusercontent.com/15355274/93962623-d12fac80-fd8d-11ea-8251-0f0852ac8ee3.png)
![企业微信截图_16004295048073](https://user-images.githubusercontent.com/15355274/93962634-d68cf700-fd8d-11ea-8fee-8f1d180a9771.png)

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by 991547436** [comment]
> To troubleshoot this issue we need to see AdGuard Home logs.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

the log file /var/log/AdGuardHome.out
[AdGuardHome.zip](https://github.com/AdguardTeam/AdGuardHome/files/5280020/AdGuardHome.zip)


![QQ截图20200925092657](https://user-images.githubusercontent.com/15355274/94216347-bc7c2180-ff11-11ea-91b3-1ad4394ad9ab.png)

**Comment by szolin** [comment]
> Specify log_file
> Set verbose to True

Did you follow these steps?  You should, because we need debug logs.

**Comment by 991547436** [comment]
> > Specify log_file
> > Set verbose to True
> 
> Did you follow these steps? You should, because we need debug logs.

I changed the open files of the system to 65535 and the problem was solved. Thank you
