### ISSUE TITLE
upgrade ideas

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#2127]
openwrt x64, gl-inet.com mv1000w

抵抗主动探测的代理HTTPT，在github.com 上有源代码，希望可以利用该代码开启安全隧道，如果可以，udp,http, tcp,https,tls 都通过HTTPT，那么所有的查询会更安全，同时所有的常规服务器都可以使用了。
另外升级可用的源代码
原题：调查伊朗最近部署的协议过滤器
2020 年初，伊朗部署了协议过滤器，只允许 DNS、HTTP 和 HTTPS 协议，审查任何使用其它协议的连接。马里兰大学的 Kevin Bock 等人对此展开了调查（PDF），并测试了他们最近开源的遗传算法 Geneva 对抗协议过滤器的能力。研究人员发现，伊朗对禁止协议的审查是丢弃来自客户端的所有数据包，来自服务器的数据包不受影响，客户端仍然会收到来自服务器的数 据包。但由于客户端无法确认或回应，连接事实上被审查了。它与防火长城不同是单向审查而不是双向，此外协议过滤器只审查 TCP 流量，仅限于端口 53、80 和 443，其它端口发送的流量没有过滤。研究人员称 Geneva 在两小时内就发现了三种能挫败协议过滤器的方法。Geneva 的代码托管在 GitHub 上，目前只支持 Linux 系统，不支持 OS X 或 Windows。
不对请谅解，谢谢！
openwrt x64, gl-inet.com mv1000w

The proxy HTTPT, which resists active detection, has source code on github.com. I hope that this code can be used to open a secure tunnel. If possible, udp, http, tcp, https, tls are all through HTTPT, then all queries will be more secure, and at the same time All regular servers can be used.
Also upgrade the available source code
Original title: Investigating the recently deployed protocol filters in Iran
In early 2020, Iran deployed a protocol filter, allowing only DNS, HTTP and HTTPS protocols, and censoring any connections that use other protocols. Kevin Bock and others from the University of Maryland conducted an investigation (PDF) on this and tested their recently open source genetic algorithm Geneva against protocol filters. Researchers found that Iran’s review of the prohibited protocol is to discard all data packets from the client. The data packets from the server are not affected, and the client still receives the data packets from the server. But because the client could not confirm or respond, the connection was actually censored. It differs from the Great Firewall in one-way inspection rather than two-way inspection. In addition, the protocol filter only inspects TCP traffic, which is limited to ports 53, 80 and 443. The traffic sent by other ports is not filtered. Researchers say Geneva discovered three ways to defeat protocol filters within two hours. Geneva's code is hosted on GitHub, and currently only supports Linux systems, not OS X or Windows.
If not true ,I am sorry, thank you!

**Comment by ameshkov** [comment]
As far as I understand, this information is about Iranian government firewall and it is not fully relevant to what we do with AdGuard Home.

**Comment by jkle112** [comment]
In China:
The firewall was discovered and started to block ESNI (Encrypted Server Name Indication). TLS1.3 introduces ESNI (not yet an official specification), which uses encrypted SNI to prevent intermediaries from viewing specific websites that clients want to visit. Because they do not know the websites that users visit using ESNI, the censors either do not block any ESNI connections or block all ESNI connections. The firewall chose the latter. The test found that the firewall prevents ESNI connections by dropping data packets from the client to the server. In addition, ESNI blocking will not only occur on port 443, but also on all ports from 1 to 65535. After blocking the ESNI handshake, the firewall will continue to block any connections related to the (source IP, destination IP, destination port) 3-tuple for a period of time.
Hope Dnscrypt-proxy upgrade to deal with the firewall to block more.
If not true ,I am sorry, thank you!
