### ISSUE TITLE
Misleading information during service installation

### ISSUE THREAD

**Issue by AngelFalse** [AdguardTeam/AdGuardHome#2128]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I am using agh on my own computer to act as a encrypted DNS proxy for this very computer. Lately I backed up (**copied**) my configuration file (AdGuardHome.yaml) and reinstalled my computer, after the re-installation, I put the config file in the same dir of the main executable and executed `AdGuardHome -s install` in the Terminal, then agh prompted texts about firstrun configuration:

```
There are a few more things that must be configured before you can use it.
Click on the link below and follow the Installation Wizard steps to finish setup.
2020/09/24 xx:xx:xx [info] AdGuard Home is available on the following addresses:
2020/09/24 xx:xx:xx [info] Go to http://192.168.1.193:3000
2020/09/24 xx:xx:xx [info] Go to http://[::1]:3000
2020/09/24 xx:xx:xx [info] Go to http://127.0.0.1:3000
2020/09/24 xx:xx:xx [info] Action install has been done successfully on windows-service
```

At first I thought that the former configuration file did not accepted by agh and it has been replaced with a empty config file, but then I did some digging and found the config file has not changed a bit and agh is running just like the config told it to.

The program is working all right, but some maybe mislead to think the program did not accept the original config while installing the service, so I am suggesting to **do a config file discovery during service installation and only shown these first-run text if config file is not discovered**.

* **Version of AdGuard Home server:**
  * v0.103.3, the latest pre-release has the same issue
* **How did you setup DNS configuration:**
  * Local system
* **Operating system and version:**
  * Windows 10 Version 10.0.18362.30

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/28922095/94115833-dae40d80-fe7c-11ea-877a-5073cb0d567f.png)

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/8c411c463030e0188a27c85db5ad545ab442cce8
