### ISSUE TITLE
Can the information of a device not appear in the log

### ISSUE THREAD

**Issue by popeshaka** [AdguardTeam/AdGuardHome#2129]
As the title
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
It can. Please be much more specific than this.
