### ISSUE TITLE
Add official opkg support

### ISSUE THREAD

**Issue by sanecito** [AdguardTeam/AdGuardHome#2130]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I checked to make sure that this issue has not already been filed

### Problem Description

Currently if one installs AdGuardHome via [the method described in the OpenWrt forum to /opt/](https://forum.openwrt.org/t/howto-running-adguard-home-on-openwrt/51678) it as the post warns, can be blown away by OpenWrt updates unless it's on an external drive via USB. Not all routers have a USB port however, so one could be stuck reinstalling AdGuard Home every month.

### Proposed Solution

The AdGuard Home project adopts maintaining a package for opkg to use. Since AdGuard Home would be managed by opkg, it would ensure one is running the arguably most secure, least buggy version w/o having to worry about reinstalling after OpenWrt updates.

### Alternatives Considered

I looked at https://github.com/rufengsuixing/luci-app-adguardhome and while it's awesome that someone has taken on making AdGuard Home manageable w/ opkg, it hasn't been updated in almost 10 months which means as I understand it it's now 7 non-beta releases behind the official project. Furthermore the maintainer has been inactive for the same amount of time.

### Additional Information

N/A

**Comment by skaox** [comment]
Already in the official [OpenWrt package repository](https://github.com/openwrt/packages/tree/master/net/adguardhome)

**Comment by ameshkov** [comment]
This is very unfortunate that luci-app-adguardhome is not developed anymore.

Maybe someone would like to fork and support it so I'll keep this issue open and mark is as "help wanted".
