### ISSUE TITLE
Ads not being blocked after last update on homeassistant adgaurd

### ISSUE THREAD

**Issue by rkbest13** [AdguardTeam/AdGuardHome#2132]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by rkbest13** [comment]
Since yesterday’s update all my blocked statistics dropped to 0%. While the adgaurd shows running as expected. I am seeing ads on webpages that were clean earlier.

**Comment by ameshkov** [comment]
Please check the filter lists that are installed in AdGuard Home. Are they enabled? What's the rules count?

**Comment by rkbest13** [comment]
Everything is updated and all filterlist enabled. I have few hundred of block lists that show active. Either the webpages have found a way to food adgaurd or something is working.

**Comment by ameshkov** [comment]
`nslookup ad.doubleclick.net AGH_IP_ADDRESS` -- check what's the output of this command on your computer.
