### ISSUE TITLE
latest, beta and edge Docker images do not work on Raspberry Pi Zero

### ISSUE THREAD

**Issue by FLIPNEUS** [AdguardTeam/AdGuardHome#2133]
### Prerequisites
- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
  * v103.3
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi Zero
* **Operating system and version:**
  * Raspbian GNU/Linux 10 (buster) armv6l / kernel 5.4.51+ / Docker v19.03.13

### Expected Behavior
When running a container using the adguardhome:latest, adguardhome:beta or adguardhome:edge images, I would expect the container to run, similar to how it would run if I would use the adguardhome:armhf-latest image (which is no longer being updated since you moved to the new CI process (#1875), but still works as of v102)

### Actual Behavior
The container doesn’t even launch. No logs are being stored, and in the ‘work’ volume I only have a core dump. I have a strong suspicion that the armv6 image in the Docker builds is not compatible with the Zero.

**Comment by c0b41** [comment]
try `linux_armv6`
`

**Comment by FLIPNEUS** [comment]
Thanks for the tip, that allowed me to further investigate this, which took me to https://github.com/moby/moby/issues/41017

I enabled experimental features in my Docker daemon, and this is my current command:

`docker run -d --name adguardhome --network host --platform linux/arm/v6 --restart=unless-stopped -v adguardhome-conf:/opt/adguardhome/conf -v adguardhome-work:/opt/adguardhome/work adguard/adguardhome:latest`

But it still core dumps on me and I can’t get any logging going. The linux_armv6.tar.gz packages works, but I would prefer to run this in a Docker container.

**Comment by ameshkov** [comment]
The difference between the old images and the new ones is not the CI process, but pretty massive changes to Dockerfile, we now use buildx to build a multi-arch docker image.

I don't have access to a Pi Zero device so it won't be easy to troubleshoot this one.

Just in case, have you removed previously downloaded image before running it with `--platform`?
Have you tried any other multi-arch docker image? Literally any image would do -- just to test if the issue with AGH or with docker itself?

**Comment by FLIPNEUS** [comment]
> I don't have access to a Pi Zero device so it won't be easy to troubleshoot this one.

Let me know which steps I should do to help troubleshoot.

> Just in case, have you removed previously downloaded image before running it with `--platform`?

Yup, I did both `docker rmi` to remove the individual and `docker system prune` to be sure.

> Have you tried any other multi-arch docker image? Literally any image would do -- just to test if the issue with AGH or with docker itself?

Yup, I had no issues with the portainer/portainer-ce:latest, portainer/agent:latest and ghost:latest images, all which appear to be multi-arch. Let me know if you want me to try some other ones.

**Comment by ameshkov** [comment]
> Yup, I had no issues with the portainer/portainer-ce:latest, portainer/agent:latest and ghost:latest images, all which appear to be multi-arch. Let me know if you want me to try some other ones.

Hm, well, the only difference I see is that these images don't have arm6 arch while AGH does have it.

Let's try something really-really simple:
```
docker run --rm --net=host alpine echo "test"
```

**Comment by FLIPNEUS** [comment]
No output. Container crashed immediately and went back to the prompt:
```
# docker run --rm --net=host alpine echo "test"
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
52278dd8e579: Pull complete 
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
#
```

When I added `--platform=linux/arm/v6` it did work, because it appears that without doing that, Docker pulls the armv7 image by default, according to https://github.com/moby/moby/issues/41017
```
# docker run --rm --net=host --platform=linux/arm/v6 alpine echo "test"
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
b4b72e716706: Pull complete 
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
test
# 
```

**Comment by ameshkov** [comment]
What about doing the same with AdGuard Home image?

Check this command:
```
docker run --rm --name testadguardhome --network host --platform linux/arm/v6 adguard/adguardhome:latest
```

What's printed to the output?

**Comment by FLIPNEUS** [comment]
Nothing, unfortunately. Seems to crash immediately:

```# docker run --rm --name testadguardhome --network host --platform linux/arm/v6 adguard/adguardhome:latest
Unable to find image 'adguard/adguardhome:latest' locally
latest: Pulling from adguard/adguardhome
b4b72e716706: Already exists 
fbd9a1625483: Pull complete 
ad6ec05c4e59: Pull complete 
a9ac367dd3e9: Pull complete 
935614f097ed: Pull complete 
Digest: sha256:288f3c75ab3da2caa8be3b271ff2908983e605bba09d2f9b9f9d44321014e99c
Status: Downloaded newer image for adguard/adguardhome:latest
#```

**Comment by ameshkov** [comment]
I guess we need an expert at docker to figure out what's wrong here.

@crazy-max would you mind taking a look? Is this an issue with buildx triggered by that moby bug?

**Comment by crazy-max** [comment]
@ameshkov This has been fixed in containerd/containerd#4530 (containerd v1.4.1 / Docker v19.03.13 if I'm not wrong).

**Comment by tianon** [comment]
Unfortunately that's not in any releases of either containerd or Docker yet.

**Comment by crazy-max** [comment]
@tianon Ok thx for the info

**Comment by Wuodan** [comment]
The latest (v0.104.3) Docker image does indeed not work on a Raspberry Pi Zero.

When I run the image interactivelly with:
`docker run -it --entrypoint=sh adguard/adguardhome`
and then in the container manually execute the entrypoint:
`/opt/adguardhome/AdGuardHome`
then it prints
`Illegal instruction (core dumped)` and exits with error 132.

Running the image non-interactively results in error 132 without the error message.

I suspect the binary not being trully armv6 or at least not armv6l.

## Workaround
The released binary in [AdGuardHome_linux_armv6.tar.gz](https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.104.3/AdGuardHome_linux_armv6.tar.gz)  works on the Pi Zero.
With that I was able to build a Docker image **on the Pi Zero**, it's even about half the size.
 
- Image on Docker hub: wuodan/adguardhome
- Dockerfile and buildx-script: https://github.com/wuodan-docker/adguardhome

Building AdGuardHome from source on the Pi Zero failed, both with the provided Docker-builder and on the Pi itself.

* **Version of AdGuard Home server:**
  * v0.104.3
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi Zero W 
* **Operating system and version:**
  * HypriotOS kernel 5.4.79 armv6l

**Comment by ameshkov** [comment]
@Wuodan I guess this should be reported to Docker.

> Building AdGuardHome from source on the Pi Zero failed, both with the provided dockerfile and on the Pi itself.

Since AG Home is written in Go, you don't have to build it on Pi to make it work. Just

**Comment by KilometerM** [comment]
FYI, the latest image and docker version seem to be working again on a pi zero.

**Comment by FLIPNEUS** [comment]
Confirm fixed. Thanks all!
