### ISSUE TITLE
adguard-malware-shavar erroneously blocking DigitalOcean Spaces

### ISSUE THREAD

**Issue by Maffsie** [AdguardTeam/AdGuardHome#2134]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * arm7 Docker image + OpenWRT router
* **Operating system and version:**
  * Alpine Linux, OpenWRT

### Expected Behavior
DNS queries to DigitalOcean Spaces addresses resolve normally

### Actual Behavior
DNS queries to DigitalOcean Spaces addresses do not resolve

### Screenshots

<details><summary>Query log:</summary>

![image](https://user-images.githubusercontent.com/68005/94428714-1c303200-0189-11eb-9f18-12f2415b2ef8.png)

</details>

### Additional Information
I tried to go through the support section of the AdGuard website, but it didn't have the AdGuard malware protection lists as an option when reporting a problem.

**Comment by ameshkov** [comment]
Thanks for reporting it! Should be okay in a couple of hours
