### ISSUE TITLE
Make sure AdGuard Home blocks TYPE65 queries for domains that are blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2135]
When domain is blocked, we should prevent all kinds of DNS queries.

@szolin could you please double-check that we do this in AGH (and in AG DNS as well)?

**Comment by szolin** [comment]
AGH replies with REFUSED code by default for all types of queries if the domain is blocked.
AG DNS replies with `0.0.0.0/::` for A/AAAA queries, NXDOMAIN for all other types.

**Comment by ameshkov** [comment]
Yep, sounds good.

What for other blocking modes in AGH? Custom IP?

**Comment by szolin** [comment]
`null ip` mode:
A request -> `0.0.0.0`
AAAA request -> `::`
other -> REFUSED

`custom ip` mode:
A request -> `<IP>`
AAAA request -> `<IP>`
other -> REFUSED

**Comment by HorayNarea** [comment]
> When domain is blocked, we should prevent all kinds of DNS queries.

I disagree and would say the current behaviour (as @szolin said "AGH replies with REFUSED code by default for all types of queries if the domain is blocked.") is a bug since if `example.com` is blocked but not `sub.example.com` and the domain uses DNSSEC then all subdomains will be broken…

I have personally already run into this problem and worked around it by disabling DNSSEC-verification at clients but that's really not a solution.

**Comment by ameshkov** [comment]
> is a bug since if example.com is blocked but not sub.example.com and the domain uses DNSSEC then all subdomains will be broken…

Could you please explain how exactly does blocking `example.org` messes with DNSSEC and what exactly shouldn't be blocked then?

**Comment by HorayNarea** [comment]
If you query the `A` record from `sub.example.com`, the `DNSKEY` and/or `DS` and/or `RRSIG` record (depending on the exact way DNSSEC is configured) from `example.com` will also be queried to verify the signature, which will fail since all queries to `example.com` are answered with `REFUSED`

You can actually see this in action with for www.example.com here: https://dnssec-debugger.verisignlabs.com/www.example.com

What should happen in my opinion is only blocking A/AAAA/CNAME queries and make "refuse all querytypes" an option

**Comment by ameshkov** [comment]
> What should happen in my opinion is only blocking A/AAAA/CNAME queries and make "refuse all querytypes" an option

But how would this fix the issue you're having? The client will still need to query A/AAAA records in order to receive RRSIG, kinda like dig +trace +dnssec works.

What should happen in my opinion is only blocking A/AAAA/CNAME queries and make "refuse all querytypes" an option

**Comment by HorayNarea** [comment]
Because most DNS-blocklists still use hostsfile syntax like you write in https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists

` ||example.org^ - block access to the example.org domain and all its subdomains`
vs.
` 0.0.0.0 example.org - (attention, old-style /etc/hosts syntax) block example.org domain (but NOT its subdomains)`

**Comment by ameshkov** [comment]
Sorry, I am failing to see how this solves the issue with broken DNSSEC.

You can unblock the subdomain you need with `@@||sub.example.org^`

My point is that anyway the client would need to query A record of `example.org` to verify the signature and in any case it would fail because A records are blocked.

**Comment by HorayNarea** [comment]
> My point is that anyway the client would need to query A record of `example.org` to verify the signature and in any case it would fail because A records are blocked.

uhm… no?
the client does not need to query A record of the domain when it wants the A record of a subdomain?

maybe you misunderstood me because I used a real domain as an example?

**Comment by ameshkov** [comment]
> If you query the A record from sub.example.com, the DNSKEY and/or DS and/or RRSIG and/or NSEC and/or NSEC3 record (depending on the exact way DNSSEC is configured) from example.com will also be queried to verify the signature, which will fail since all queries to example.com are answered with REFUSED

I was talking about this

**Comment by HorayNarea** [comment]
I don't understand how in this situation A from example.com is needed?

I mean, you can literally see that it never gets queried:

```
$ drill -T -D www.example.com

;; Number of trusted keys: 2
;; Domain: .
[T] . 172800 IN DNSKEY 257 3 8 ;{id = 20326 (ksk), size = 2048b}
. 172800 IN DNSKEY 256 3 8 ;{id = 46594 (zsk), size = 2048b}
. 172800 IN DNSKEY 256 3 8 ;{id = 26116 (zsk), size = 2048b}
Checking if signing key is trusted:
New key: .	172800	IN	DNSKEY	256 3 8 AwEAAdauOGxLhfAKFTTZwGhBXbk793QKdWIQRjiSftWdusCwkPhNyJrIjwtNffCWXGLlZAbpcs414RE3oS1qVwV+AdXsO92SBu5haGlxMUk0NqZO7Xlf84/wrzGZVRRouPo5pNX/CKS8Mv9UOi0olKGCu31dNfh8qCszWZcloLDgeLzSnQSkvFoGe69vNCfh7feESKedkBC2qRz0BZv9+oJI0IY/3D7WEnV0NOlf8gSHozhfJFJ/ZAKtvw/Q3ogrVJFk0LyVaU/NVtVA5FM4pVMIRID7pfrPi78aAzG7b/Wh/Pce4jPAIpS3dApq25YkvMuPvfB91NMf9FemKwlp78PBVcM= ;{id = 46594 (zsk), size = 2048b}
	Trusted key: .	3600	IN	DNSKEY	256 3 8 AwEAAbPwrxwtOMENWvblQbUFwBllR7ZtXsu9rg/LdyklKs9gU2GQTeOc59XjhuAPZ4WrT09z6YPL+vzIIJqnG3Hiru7hFUQ4pH0qsLNxrsuZrZYmXAKoVa9SXL1Ap0LygwrIugEk1G4v7Rk/Alt1jLUIE+ZymGtSEhIuGQdXrEmj3ffzXY13H42X4Ja3vJTn/WIQOXY7vwHXGDypSh9j0Tt0hknF1yVJCrIpfkhFWihMKNdMzMprD4bV+PDLRA5YSn3OPIeUnRn9qBUCN11LXQKb+W3Jg+m/5xQRQJzJ/qXgDh1+aN+Mc9AstP29Y/ZLFmF6cKtL2zoUMN5I5QymeSkJJzc= ;{id = 22545 (zsk), size = 2048b}
	Trusted key: .	3600	IN	DNSKEY	257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
	Trusted key: .	172800	IN	DNSKEY	257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
	Trusted key: .	172800	IN	DNSKEY	256 3 8 AwEAAdauOGxLhfAKFTTZwGhBXbk793QKdWIQRjiSftWdusCwkPhNyJrIjwtNffCWXGLlZAbpcs414RE3oS1qVwV+AdXsO92SBu5haGlxMUk0NqZO7Xlf84/wrzGZVRRouPo5pNX/CKS8Mv9UOi0olKGCu31dNfh8qCszWZcloLDgeLzSnQSkvFoGe69vNCfh7feESKedkBC2qRz0BZv9+oJI0IY/3D7WEnV0NOlf8gSHozhfJFJ/ZAKtvw/Q3ogrVJFk0LyVaU/NVtVA5FM4pVMIRID7pfrPi78aAzG7b/Wh/Pce4jPAIpS3dApq25YkvMuPvfB91NMf9FemKwlp78PBVcM= ;{id = 46594 (zsk), size = 2048b}
Key is now trusted!
	Trusted key: .	172800	IN	DNSKEY	256 3 8 AwEAAfC/6HLClwss6h7rPfoG2cliv4/SPJRd2HPEglRsvKZRbPP2RLfiobeAkczcdqaD5q8loEt14lcTgDqwzOISZ3YvSVkM4JRMFwKzcjukKo5CsDVbMmhTD0C0yxWICRQ1M+Y5/XkZAT7mt4cb3fWcN9xgyq1wEXQX+zdLQHrNEVQSiL5SoA5cOtCSoQ45n8bKDXdw/0jjP9Rw1FVKsdzLVkQSrVMm8k30WUkHm/SK/n/954KENkdQOA6Li2vO9nicQdegyAkDeNJCdPN/p3jEhCTQLyO4AlAmyaPcDHeeo7OXr/VsYu4NTDde9hBuS0zx/rewD+BvSnmnNHNmH2FjUE8= ;{id = 26116 (zsk), size = 2048b}
[T] com. 86400 IN DS 30909 8 2 e2d3c916f6deeac73294e8268fb5885044a833fc5459588f4a9184cfc41a5766
;; Domain: com.
[T] com. 86400 IN DNSKEY 256 3 8 ;{id = 24966 (zsk), size = 1280b}
com. 86400 IN DNSKEY 257 3 8 ;{id = 30909 (ksk), size = 2048b}
Checking if signing key is trusted:
New key: com.	86400	IN	DNSKEY	256 3 8 AwEAAdVECVAFFKnwlH7lDYpsSvv50Z7EJP518luWdiN7X5igYJo6dLij/noOhYO0ppmTghphtSqHn75/qMmETK9NiUfLW4M9X8j/IvIr1xrTPEb6+dipDE9xKjhMGFUufOeXHiBoMQiKLNzlssYuz90oQrEwCKpa5R4cYYFiZaoeezi2NQeIAY82dh/8auvFzqCOewWx/J2zVh8YHqfkGeXyzsM= ;{id = 24966 (zsk), size = 1280b}
	Trusted key: .	3600	IN	DNSKEY	256 3 8 AwEAAbPwrxwtOMENWvblQbUFwBllR7ZtXsu9rg/LdyklKs9gU2GQTeOc59XjhuAPZ4WrT09z6YPL+vzIIJqnG3Hiru7hFUQ4pH0qsLNxrsuZrZYmXAKoVa9SXL1Ap0LygwrIugEk1G4v7Rk/Alt1jLUIE+ZymGtSEhIuGQdXrEmj3ffzXY13H42X4Ja3vJTn/WIQOXY7vwHXGDypSh9j0Tt0hknF1yVJCrIpfkhFWihMKNdMzMprD4bV+PDLRA5YSn3OPIeUnRn9qBUCN11LXQKb+W3Jg+m/5xQRQJzJ/qXgDh1+aN+Mc9AstP29Y/ZLFmF6cKtL2zoUMN5I5QymeSkJJzc= ;{id = 22545 (zsk), size = 2048b}
	Trusted key: .	3600	IN	DNSKEY	257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
	Trusted key: .	172800	IN	DNSKEY	257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
	Trusted key: .	172800	IN	DNSKEY	256 3 8 AwEAAdauOGxLhfAKFTTZwGhBXbk793QKdWIQRjiSftWdusCwkPhNyJrIjwtNffCWXGLlZAbpcs414RE3oS1qVwV+AdXsO92SBu5haGlxMUk0NqZO7Xlf84/wrzGZVRRouPo5pNX/CKS8Mv9UOi0olKGCu31dNfh8qCszWZcloLDgeLzSnQSkvFoGe69vNCfh7feESKedkBC2qRz0BZv9+oJI0IY/3D7WEnV0NOlf8gSHozhfJFJ/ZAKtvw/Q3ogrVJFk0LyVaU/NVtVA5FM4pVMIRID7pfrPi78aAzG7b/Wh/Pce4jPAIpS3dApq25YkvMuPvfB91NMf9FemKwlp78PBVcM= ;{id = 46594 (zsk), size = 2048b}
	Trusted key: .	172800	IN	DNSKEY	256 3 8 AwEAAfC/6HLClwss6h7rPfoG2cliv4/SPJRd2HPEglRsvKZRbPP2RLfiobeAkczcdqaD5q8loEt14lcTgDqwzOISZ3YvSVkM4JRMFwKzcjukKo5CsDVbMmhTD0C0yxWICRQ1M+Y5/XkZAT7mt4cb3fWcN9xgyq1wEXQX+zdLQHrNEVQSiL5SoA5cOtCSoQ45n8bKDXdw/0jjP9Rw1FVKsdzLVkQSrVMm8k30WUkHm/SK/n/954KENkdQOA6Li2vO9nicQdegyAkDeNJCdPN/p3jEhCTQLyO4AlAmyaPcDHeeo7OXr/VsYu4NTDde9hBuS0zx/rewD+BvSnmnNHNmH2FjUE8= ;{id = 26116 (zsk), size = 2048b}
	Trusted key: com.	86400	IN	DNSKEY	256 3 8 AwEAAdVECVAFFKnwlH7lDYpsSvv50Z7EJP518luWdiN7X5igYJo6dLij/noOhYO0ppmTghphtSqHn75/qMmETK9NiUfLW4M9X8j/IvIr1xrTPEb6+dipDE9xKjhMGFUufOeXHiBoMQiKLNzlssYuz90oQrEwCKpa5R4cYYFiZaoeezi2NQeIAY82dh/8auvFzqCOewWx/J2zVh8YHqfkGeXyzsM= ;{id = 24966 (zsk), size = 1280b}
Key is now trusted!
	Trusted key: com.	86400	IN	DNSKEY	257 3 8 AQPDzldNmMvZFX4NcNJ0uEnKDg7tmv/F3MyQR0lpBmVcNcsIszxNFxsBfKNW9JYCYqpik8366LE7VbIcNRzfp2h9OO8HRl+H+E08zauK8k7evWEmu/6od+2boggPoiEfGNyvNPaSI7FOIroDsnw/taggzHRX1Z7SOiOiPWPNIwSUyWOZ79VmcQ1GLkC6NlYvG3HwYmynQv6oFwGv/KELSw7ZSdrbTQ0HXvZbqMUI7BaMskmvgm1G7oKZ1YiF7O9ioVNc0+7ASbqmZN7Z98EGU/Qh2K/BgUe8Hs0XVcdPKrtyYnoQHd2ynKPcMMlTEih2/2HDHjRPJ2aywIpKNnv4oPo/ ;{id = 30909 (ksk), size = 2048b}
[T] example.com. 86400 IN DS 31589 8 1 3490a6806d47f17a34c29e2ce80e8a999ffbe4be
example.com. 86400 IN DS 31589 8 2 cde0d742d6998aa554a92d890f8184c698cfac8a26fa59875a990c03e576343c
example.com. 86400 IN DS 43547 8 1 b6225ab2cc613e0dca7962bdc2342ea4f1b56083
example.com. 86400 IN DS 43547 8 2 615a64233543f66f44d68933625b17497c89a70e858ed76a2145997edf96a918
example.com. 86400 IN DS 31406 8 1 189968811e6eba862dd6c209f75623d8d9ed9142
example.com. 86400 IN DS 31406 8 2 f78cf3344f72137235098ecbbd08947c2c9001c7f6a085a17f518b5d8f6b916d
;; Domain: example.com.
[T] example.com. 3600 IN DNSKEY 256 3 8 ;{id = 41461 (zsk), size = 1024b}
example.com. 3600 IN DNSKEY 257 3 8 ;{id = 45620 (ksk), size = 2048b}
example.com. 3600 IN DNSKEY 257 3 8 ;{id = 31406 (ksk), size = 2048b}
[T] Existence denied: www.example.com. DS
;; No ds record for delegation
;; Domain: www.example.com.
;; No DNSKEY record found for www.example.com.
[T] www.example.com.	86400	IN	A	93.184.216.34
;;[S] self sig OK; [B] bogus; [T] trusted
```

**Comment by ameshkov** [comment]
Huh, so it's kinda different from how dig +trace works:)

But when a domain blocked by a hosts list, this would break requesting the full chain. A/AAAA are answered with the IP address from that list, and other types are answered with an empty NOERROR response.

The case that you're talking about might be solved if we implement a `$dnstype` modifier that would allow targeting DNS queries with a specific type.

Anyways, I do still think that we should not allow any question type by default. DNS query may be used to transfer data by itself.

**Comment by HorayNarea** [comment]
> The case that you're talking about might be solved if we implement a `$dnstype` modifier that would allow targeting DNS queries with a specific type.

That would not work with existing lists that are not using your format…

> Anyways, I do still think that we should not allow any question type by default.

I think that's wrong since "ads and stuff" literally need to come over HTTP(S) so you always need A or AAAA for that… but ok, can we than at least have like an array in the configfile where I can set query types that I want to always allow?

>  DNS query may be used to transfer data by itself.

Citation needed ;D

**Comment by HorayNarea** [comment]
> You could add just one rule that allows all queries of a given type for all domains.

Hmm… I guess that might be a good enough workaround.

**Comment by thb007** [comment]
@ameshkov fuck type65 ，This type65 request is poisonous, please arrange to block

![type65](https://user-images.githubusercontent.com/17548936/94929260-6c93f080-04f7-11eb-8974-bd68f20aca52.png)
![t](https://user-images.githubusercontent.com/17548936/94929342-8af9ec00-04f7-11eb-9df0-b226cceca2c9.png)

**Comment by Ulmisch** [comment]
I am wondering if type 65 requests have to be blocked.
@ameshkov please have a look here: https://tools.ietf.org/html/draft-ietf-dnsop-svcb-https-01
Type 65 request seem to be a "normal" behavior.

**Comment by ameshkov** [comment]
I am not talking about blocking ALL OF THEM, my point is that when a domain is blocked, TYPE65 requests need to be blocked as well
