### ISSUE TITLE
Unable to access port 3000 after install. How to get API status?

### ISSUE THREAD

**Issue by yurividal** [AdguardTeam/AdGuardHome#2136]
On latest stable version installed on RPi, i want to access the admin page, to be able to get the status via API.
But, after being set up, AGH no longer listens in port 3000. Where can i get the status and query stats?
My ultimate goal is to build a python script that gets the status and sends to InfluxDB, so that i can put it on a Grafana Dashboard.

**Comment by ameshkov** [comment]
> But, after being set up, AGH no longer listens in port 3000. Where can i get the status and query stats?

Check `AdGuardHome.yaml` -- look for `bind_port` there.

Also, the port that is to be used is defined by the user when they go through the setup wizard on the first run.

**Comment by yurividal** [comment]
The Bind port is for the GUI. That is working fine. I want to know how I can get to the status page. The python adguardhome module tries to get http://IP:3000/control/status but this returns connection refused.
How do I access status or rest API?

**Comment by ameshkov** [comment]
It accepts only authenticated requests, you need to use HTTP basic auth to pass it.

**Comment by ameshkov** [comment]
Ah, I got it, you use the python library, sorry I missed that.

 I guess it would be better to ask the maintainer, @frenck.

Three things to note:
1. This bind_port is not just for the GUI, it's for the REST API as well.
2. The requests need to be authenticated: https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi#authentication

@frenck does it allow using a custom port and setting username/password for HTTP basic auth?

**Comment by yurividal** [comment]
Thank you. I was able to access /control/status on port 80 when authenticated. Unfortunately it only replies very simple information. I was trying to programmatically get statuses like total queries and total blocks. Thanks anyway.

**Comment by ameshkov** [comment]
@yurividal please check out the [REST API doc](https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi#how-to-read-the-api-doc), it's not that hard to use it directly, and it contains all the information that's shown in UI.
