### ISSUE TITLE
UI: Improvement: "Remove Disable Protection Button by Toggle-Button"

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2137]
Remove the "Disable Protection" and replace "ON/OFF" with a Toggle-Button.

![grafik](https://user-images.githubusercontent.com/25774289/94543584-8957cc00-024a-11eb-8e80-f93192949595.png)

**Comment by ameshkov** [comment]
This screen will look differently in the redesigned version, this issue won't be relevant by then.
