### ISSUE TITLE
Client settings are overridden by DNS rewrites

### ISSUE THREAD

**Issue by rayures** [AdguardTeam/AdGuardHome#2139]
* **Version of AdGuard Home server:**
0.103.3
* **How did you setup DNS configuration:**
proxmox LXC, Ubuntu 20.04
* **If it's a router or IoT, please write device model:**
n/a
* **Operating system and version:**
Ubuntu 20.04.1 LTS

### Expected Behavior
custom dns resolver for specific clients is used to resolve a FQDN. 

### Actual Behavior

DNS rewrite is rewriting

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5716188/94576134-4bbc6880-0275-11eb-9cb3-33204fda0672.png)
![image](https://user-images.githubusercontent.com/5716188/94576234-655db000-0275-11eb-97ca-36c31ed71f6a.png)

</details>

### Additional Information

i want all clients to user the default AdGuardHome settings, rewrites, blocklists and upstream dns server. 
i want 1 client to use no blocklist en a different dns server. This is not working, dns rewrites are always rewriting. 

what am i doing wrong?

**Comment by ameshkov** [comment]
Nothing wrong, the problem is that DNS rewrites are global and can't be configured per-client.

When #2102 is implemented, you'll be able to configure them more granularly.

**Comment by rayures** [comment]
just for clarification, the option ' use global settings ' does not disable dns rewrites? 
 
![image](https://user-images.githubusercontent.com/5716188/94659079-085d0b00-0304-11eb-8c98-d11085182881.png)

**Comment by szolin** [comment]
Correct, DNS rewrites are always active.
