### ISSUE TITLE
Use DoH on Android at Home with WiFi

### ISSUE THREAD

**Issue by hanmey97** [AdguardTeam/AdGuardHome#2140]
Hello everybody.
I have an AdGuard Home Server installed in my home. This runs with an Asus router. The Adguard server is set there as the primary DNS server.
I have set Adguard as the private DNS on my Android smartphone. It works as it should.
However, when I am at home in WLAN with the cell phones, every request from the cell phones is listed under the IP 192.168.1.1 (router). Is there a possibility of not routing the requests in the WLAN via DoH or of sorting them according to the devices?

**Comment by ameshkov** [comment]
It seems that the solution would be something like this: https://github.com/AdguardTeam/AdGuardHome/issues/1383
