### ISSUE TITLE
Disable statistics the same way it is possible to disable protocols

### ISSUE THREAD

**Issue by halest** [AdguardTeam/AdGuardHome#2141]
### Problem Description
On HomeAssistant I moved from PiHole to AdGuard and was suprised it doesn't have the option to switch to an "anonymous mode" like it was possible there. While it is possible to disable protocols, most of the critical information still shows up in the statistics without an option to turn it off. I do not want to know or see what my clients are doing. That is none of my business.

### Proposed Solution
Add a "disable statistics" button, analog to the "disable protocols" button.

### Alternatives Considered
Create an "anonymous mode" that doesn't keep any data.

### Additional Information
Using HomeAssistant-Plugin

**Comment by ainar-g** [comment]
This is implemented as of edge snapshot dbe8b92d.  Can you please check if our implementation works for you?

**Comment by halest** [comment]
Thanks @ainar-g ! I'm currently running the Homeassistant-Plugin so I can't easily do that but I did instead proofread the changes in the commit and it looks good to me. Smart and simple solution :)

**Comment by ainar-g** [comment]
I see, thanks!  The feature seems to work in our tests, so I'll close this issue for now.
