### ISSUE TITLE
Add a directory for admin panel.

### ISSUE THREAD

**Issue by SkyYkb** [AdguardTeam/AdGuardHome#2142]
Hi, everyone, I have a suggestion for AdGuard Home.
(My English is poor so please ignore my language mistakes, thanks.)

### Prerequisites
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I can't run AdGuard Home admin panel with other webpage services (e.g. Nextcloud, AriaNg) on port 443 due to the url of admin panel doesn't have a directory.

### Proposed Solution
Add a directory after domain, like example.com:443/adguard so I can access AdGuard Home behind a reserve proxy.

Thanks.

**Comment by Disqu3-mirOir-qt** [comment]
y can do that with apache 

https://opensource.com/article/18/3/configuring-multiple-web-sites-apache

**Comment by SkyYkb** [comment]
Sorry, I read this passage but I still don't know what to do... This solution needs webpage files of websites...
Did AdGuard Home provided admin panel webpage files?

**Comment by szolin** [comment]
There's a guide here how to configure a proxy server:
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy
