### ISSUE TITLE
adgh has no protection

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#2143]
It stands to reason that a non-existent or unresolvable retry should be passed 3 times, but adgh will always try to request resolution, resulting in a high CPU memory usage! Like cf game "fire in the hole"

**Comment by ameshkov** [comment]
Could you please be more specific?

**Comment by thb007** [comment]
> Could you please be more specific?

For example, for this non-existent domain name "wangyou.pcgames.com.cn", adgh will try to resolve its ip address and keep trying to resolve it. So what do you think this will do? So when a domain name cannot be resolved, it can be automatically queried 3-5 times. There is no need to keep trying to resolve it.
You can add this function Number of tries if upstream DNS fail to customize tries = 3, so that when upstream DNS fail, it tries 3 times. Do you understand it?

**Comment by ameshkov** [comment]
Do you mean that AGH does not cache negative results?

**Comment by thb007** [comment]
> Do you mean that AGH does not cache negative results?

no no no，You can understand that we make three requests for each domain name that fails to resolve. If the resolution fails three times, we will ignore the request for this domain name until the next time the client sends a request for this domain name.

**Comment by ameshkov** [comment]
AGH makes as many requests as the client that sends it. We don't do extra requests unless you're using the "fastest IP address" feature.

**Comment by thb007** [comment]
> AGH makes as many requests as the client that sends it. We don't do extra requests unless you're using the "fastest IP address" feature.

wu wu
