### ISSUE TITLE
DNS allowlists tab crashes after opening "Choose blocklists" modal

### ISSUE THREAD

**Issue by ArtemBaskal** [AdguardTeam/AdGuardHome#2144]
### Steps to reproduce
Open "Choose blocklists" modal of #filters tab, then open #dns_allowlists tab.

### Expected Behaviour
The tab opens successfully.

### Actual Behaviour
The tab crashes.

**Comment by ameshkov** [comment]
Well, there should be no "Choose blocklists" option at all on the allowlists tab

**Comment by ArtemBaskal** [comment]
The modal is the same for the both tabs and only the content is different
