### ISSUE TITLE
Graph hover UI issue/Graph doesn't fill box

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#2147]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3B+
* **Operating system and version:**
  * Raspberry Pi OS Buster

### Expected Behavior

1. Graph fills the box,
2. Hovering over the graph shows info from where the pointer is actually is.

### Actual Behavior

1. In the screenshot below, please note the gaps below the graph and on the left side,
2. The hover info is also wrong and errs to the right side instead of aligning with the pointer.

### Screenshots

<details><summary>Screenshot:</summary>

Pointer doesn't show up in the screenshot but it's reproducible in Safari and Chrome (macOS).

<img width="300" alt="Screen Shot 2020-10-03 at 2 50 55 PM" src="https://user-images.githubusercontent.com/19761269/94988238-5b93bf80-0589-11eb-9139-39e161cfdc80.png">

</details>

**Comment by ameshkov** [comment]
A known issue with the charts library we're currently using. We're going to replace it eventually when doing the redesign.

**Comment by agneevX** [comment]
@ameshkov both are known issues?

**Comment by ameshkov** [comment]
Yep
