### ISSUE TITLE
Smartphone compatible design for user interface

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2152]
1. Cards seems resistant to touch scrolling (sometimes unable to scroll by touching on cards) <details><summary>Screenshot:</summary>
   ![IMG_20201004_103947](https://user-images.githubusercontent.com/63988538/95008623-bab70a00-0645-11eb-936c-3f355e8b5bd1.png)
</details>

2. Block button doesn't appear (if touched client IP then block button less obtrusive)
(By default mobile users cannot recognize if such feature exist)<details><summary>Screenshot:</summary>
![IMG_20201004_103929](https://user-images.githubusercontent.com/63988538/95008995-83962800-0648-11eb-8f61-56d0f96a222a.png)
</details>

3. Previous/Next and pages numbers contents are too large<details><summary>Screenshot:</summary>
![IMG_20201004_103905](https://user-images.githubusercontent.com/63988538/95009098-6e6dc900-0649-11eb-91db-38b275aa0837.png)
</details>

4. Action buttons are incompatible<details><summary>Screenshot:</summary>
![IMG_20201004_103752](https://user-images.githubusercontent.com/63988538/95009372-c6a5ca80-064b-11eb-9c47-7bd12297377a.png)
</details>

5. DNS examples are incompatbile<details><summary>Screenshot:</summary>
![IMG_20201004_103736](https://user-images.githubusercontent.com/63988538/95009667-0a99cf00-064e-11eb-896c-8133495d94be.png)
</details>

6. DHCP settings page buttons are incompatible (too affected with other languages)<details><summary>Screenshot:</summary>
![IMG_20201004_103717](https://user-images.githubusercontent.com/63988538/95009951-ed660000-064f-11eb-9740-f532d48456c1.png)
</details>

7. DHCP interface selections incompatible<details><summary>Screenshot:</summary>
![IMG_20201004_103717](https://user-images.githubusercontent.com/63988538/95009951-ed660000-064f-11eb-9740-f532d48456c1.png)
</details>

8. No proper auto arrange for router setup guide description (only that guide)<details><summary>Screenshot:</summary>
![IMG_20201004_103501](https://user-images.githubusercontent.com/63988538/95010097-e55a9000-0650-11eb-80ff-f911b3c196b5.png)
</details>

(tested above using 5inch android device)

- Footer too large for mobile screens (also desktop screens) Read: https://github.com/AdguardTeam/AdGuardHome/issues/2121#issuecomment-696099313 <details><summary>Screenshot:</summary>
![IMG_20201004_103811](https://user-images.githubusercontent.com/63988538/95010239-f061f000-0651-11eb-966e-855fec0511da.png)

</details>

- Hide outdated strings from crowdin (obsolete)

**Comment by ameshkov** [comment]
@ArtemBaskal let's address those that can be fixed quickly: 2, 4, 6, 7

Others can wait until the redesign.

**Comment by KizunaH** [comment]
@ArtemBaskal Some issues with recent commits

>1. Block button doesn't appear (if touched client IP then block button less obtrusive)
(By default mobile users cannot recognize if such feature exist)

It still isn't good <details><summary>Screenshot:</summary>
![Screenshot_2020-10-08-19-37-43](https://user-images.githubusercontent.com/63988538/95477740-dc502280-09b2-11eb-81a3-c63bf7373b07.png)

</details>

>4. Action buttons are incompatible

You have forgot to fix DNS block/allow lists pages<details><summary>Screenshot:</summary> 
![Screenshot_2020-10-08-19-40-43](https://user-images.githubusercontent.com/63988538/95477670-cc384300-09b2-11eb-8591-fe9d70028b58.png)

</details>

**Comment by ameshkov** [comment]
> It still isn't good

We should roll it back,  I don't like the way it works now. Yes, the touch is needed to see the button, but I don't think this is that much of a problem.

**Comment by ameshkov** [comment]
Closing as everything that we could do with the pre-redesign version is now done.

**Comment by Aikatsui** [comment]
@ArtemBaskal double-check about 1st bug
