### ISSUE TITLE
Automatically block torrent sites and anything related to torrents/magnets

### ISSUE THREAD

**Issue by mysticvpn** [AdguardTeam/AdGuardHome#2153]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
So you're basically suggesting us to have a blocklist that blocks torrenting-websites?

If you know any list like that, please suggest it here: #1913
