### ISSUE TITLE
Who What When Where Why !!!!

### ISSUE THREAD

**Issue by AkgunFatih** [AdguardTeam/AdGuardHome#2155]
Hello i am running Proxmox Host + Adguard VM (virtual machine)

now that Adguard Home is running for several hours
i wanted to see the logs
and i see this xe-0.telnetscanproject.org in my client list 

how can he be in my client list ?

![image](https://user-images.githubusercontent.com/66688048/95156297-8010b700-0796-11eb-854e-fbcafbe654c3.png)

**Comment by KizunaH** [comment]
@AkgunFatih AdGuardHome is a DNS server then anyone can use it for resolve domain names if you haven't restricted who should connect through adguardhome settings or your network firewall.
Check the IP address of that client by hover mouse around it or extend column size. you can block that client within top clients component by click on 'block' button appear next to client name.

**Comment by ameshkov** [comment]
If you're running a public server, you can control who can access it in DNS settings -> Allowed clients.
