### ISSUE TITLE
speed problem

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#2158]
Openwrt x64 in mini PC/gl-inet.com mv1000w
Upstream DNS servers:add more Chinese DNS servers in,using Load-balancing.
General statistics
for the last 24 hours
Average processing time	6490 ms ,it is very slow.
Some body said in TG group:maybe has error with scripts.
Maybe add too much rules .
Hope to check the problem.
Thank you.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
