### ISSUE TITLE
Feature Request - Time Schedule for Clients

### ISSUE THREAD

**Issue by state-of-affairs** [AdguardTeam/AdGuardHome#2160]
I wanted to recommend a feature for AdGuard Home, i.e., a time schedule for clients.  For example, I have a client that I would like AdGuard to provide DNS services to from 8 am to 9:30 am.  Outside of that time period, I would like the DNS service requests to be refused (e.g., DNS packets rejected or blocked).

**Comment by KizunaH** [comment]
From existing feature request submissions, this can be archieve using https://github.com/AdguardTeam/AdGuardHome/issues/1203 https://github.com/AdguardTeam/AdGuardHome/issues/435
(User need to create a block everything regex rule in a timed blocklist and assign to necessary clients)

**Comment by ameshkov** [comment]
Closed as dup
