### ISSUE TITLE
Feature Request - Ability to select different format layout in Top Clients box on Dashboard

### ISSUE THREAD

**Issue by state-of-affairs** [AdguardTeam/AdGuardHome#2162]
On the Dashboard page, there is a reporting box called "Top Clients".  This box has two columns, i.e., "IP" and "Requests count".  The entries under the IP column show the IP address of the client.

Some of my clients have an IP address is associated with a client name (i.e., using the Client settings).  In this case, the entry under the IP column is displayed in a side-by-side format:

Client Name (IP Address)

I would like to recommend a format option where the entry is display in an over-and-under format with the parenthesis removed:

Client Name
IP Address

I note that the Query log uses this type of format in its "Client" column.  (However, the IP address is on the top and the client name is on the bottom.)

This option allows for some benefits:  Client names can be longer without having to resize the column width.  Moreover, the over-and-under format breaks the IP address away from the client name, making the Top Clients box easier to read.

**Comment by ameshkov** [comment]
Makes sense, thank you!

Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
