### ISSUE TITLE
How to add custom list?

### ISSUE THREAD

**Issue by azrea** [AdguardTeam/AdGuardHome#2163]
I installed this software on docker. it working charm including blocklist updates and apache2(non-docker) running in same linux machine. I tried to add custom blocklist but after clicked 'save' then icon grayed out
I can view blocklists index and check lists via web browser (sample link: http://192.168.0.105:8080/blocklist/sample.txt)

How to solve?

**Comment by ameshkov** [comment]
Could it be that the blocklist is not available from inside the docker?

**Comment by azrea** [comment]
> Could it be that the blocklist is not available from inside the docker?

It looks like i need to change access permission for docker container to reach host system net interface. so i think to use local file path method instead.

When deployed AGH container, i used /my/own/workdir > /home/user/netdata so i created new folder named 'blocklist' in it but AGH doesn't recognize the path (/home/user/netdata/blocklist/sample.txt) If AGH recognize to use that folder for save existing blocklists (workdir/data/filters/), why i can't use it for save and add own lists? maybe above path isn't right from container

**Comment by ameshkov** [comment]
> maybe above path isn't right from container

Well, you could run shell into the container and check it there manually:
https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell

**Comment by azrea** [comment]
cmd `docker exec -it <container> sh`
path sample `/opt/adguardhome/work/sample.txt`
