### ISSUE TITLE
建议加上过滤规则过滤数的统计

### ISSUE THREAD

**Issue by woboo110** [AdguardTeam/AdGuardHome#2166]
建议加上过滤规则过滤数的统计，可以更直观的看到该条过滤规则的有效程度，是否起作用，方便取舍

**Comment by KizunaH** [comment]
重複 https://github.com/AdguardTeam/AdGuardHome/issues/580 https://github.com/AdguardTeam/AdGuardHome/issues/1336

**Comment by ameshkov** [comment]
请加票 #580
