### ISSUE TITLE
Raspberry Pi : Adguard home and Smart DNS Proxy

### ISSUE THREAD

**Issue by chicungunya** [AdguardTeam/AdGuardHome#2168]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

Raspberry Pi 3 Model B

### Expected Behavior
Hello,
I'm trying to configure AdGuard Home on my Raspberry Pi but I use too Smart DNS to watch content from other country.
Impossible to work with both.
Do you have an idea ?

#1 I tried with my pi address as primary DNS and Smart DNS with my secondary DNS : Smart DNS works but I have still ads
#2 I tried DHCP server from Ad Guard Home and put DNS servers from Smart DNS in my router but still doet not work

Thanks a lot

**Comment by josephbu** [comment]
Smart DNS providers usually do this by providing specific responses for the domains of interest.

If you were able to identify all the relevant domains that are related to the content you want to watch, you may be able to use conditional forwarding in the "Upstream DNS servers" settings.

For example a rule such as:

`[/siteofinterest.com/]9.9.9.9:53`

Will cause AdGuard to ask that specific IP address for DNS results for that specific domain. Obviously you would replace 9.9.9.9 with the IP address of your Smart DNS provider, and you might need to make several rules depending on how many domains there are in question.

**Comment by chicungunya** [comment]
> Smart DNS providers usually do this by providing specific responses for the domains of interest.
> 
> If you were able to identify all the relevant domains that are related to the content you want to watch, you may be able to use conditional forwarding in the "Upstream DNS servers" settings.
> 
> For example in addition to your regular upstream servers, adding a rule such as:
> 
> `[/siteofinterest.com/]9.9.9.9:53`
> 
> Will cause AdGuard to ask that specific IP address for DNS results for that specific domain. Obviously you would replace 9.9.9.9 with the IP address of your Smart DNS provider, and you might need to make several rules depending on how many domains there are in question.

Hello @josephbu 
thanks a lot for your answer.
I tried to do this but I have a redirect to smartdnsproxy.com with this settings when I try to go to 6play or tf1

In my upstream DNS : 

https://dns10.quad9.net/dns-query
[/6play.fr/]45.77.61.165 
[/tf1.fr/]45.77.61.165

**Comment by ameshkov** [comment]
> I tried to do this but I have a redirect to smartdnsproxy.com with this settings when I try to go to 6play or tf1

Isn't this what you're trying to achieve?

> [/6play.fr/]45.77.61.165
> [/tf1.fr/]45.77.61.165

Looks okay to me

**Comment by chicungunya** [comment]
> > I tried to do this but I have a redirect to smartdnsproxy.com with this settings when I try to go to 6play or tf1
> 
> Isn't this what you're trying to achieve?
> 
> > [/6play.fr/]45.77.61.165
> > [/tf1.fr/]45.77.61.165
> 
> Looks okay to me

I need 6play or TF1 use Smart DNS proxy (France location) to connect and Adguard home to block their ads.

With this settings, I can't connect to 6 play or TF1 because there is just a redirection to the website smartdnsproxy.com

**Comment by ameshkov** [comment]
@chicungunya 

> With this settings, I can't connect to 6 play or TF1 because there is just a redirection to the website smartdnsproxy.com

Well, this is not bad, it means that AGH setup is right and the DNS query was indeed sent to their server.

Could it be that you're not logged in your smartdnsproxy account?
I guess it makes sense to check with their support service as well.

**Comment by chicungunya** [comment]
> @chicungunya
> 
> > With this settings, I can't connect to 6 play or TF1 because there is just a redirection to the website smartdnsproxy.com
> 
> Well, this is not bad, it means that AGH setup is right and the DNS query was indeed sent to their server.
> 
> Could it be that you're not logged in your smartdnsproxy account?
> I guess it makes sense to check with their support service as well.

Yes I will ask them.
Thanks a lot for your support !
