### ISSUE TITLE
Is there will be a realtime dashboard in the future version?

### ISSUE THREAD

**Issue by wxf26054** [AdguardTeam/AdGuardHome#2169]
![image](https://user-images.githubusercontent.com/22016320/95566636-67352980-0a54-11eb-903c-baeaf01c57cc.png)

**Comment by KizunaH** [comment]
@wxf26054 是 v0.108 https://github.com/AdguardTeam/AdGuardHome/issues/1739

**Comment by wxf26054** [comment]
ok, 谢谢
