### ISSUE TITLE
Want to add "Block IPv6 results" feature for any single server in “Upstream DNS server” section

### ISSUE THREAD

**Issue by PussAzuki** [AdguardTeam/AdGuardHome#2170]
### Problem Description
Today's DNS servers basically support IPv4+IPv6 query results, and I want to just block some IPv6 results from some of them for many reasons.

You might want to say there is a feature called ”disable IPv6“ already. But I think that function is too heavy and I do not want to kill all IPv6 results ...

### Proposed Solution
Add a symbol such as -6 or other identifiers to implement the function

And I hope to add the ”dual stack selection“ function which can solve some strange problems, such as the IPv4 latency of some websites is much lower than that of IPv6, but the system still tries IPv6 and so on.

**Comment by PussAzuki** [comment]
My opinion is to add convenience to the function of this [chapter](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#loading-the-list-of-upstream-servers-from-a-file) in wiki. I think both of my suggestions can solve the problem of too many rules that need to be written to a great extent.

**Comment by ameshkov** [comment]
Why do you want it to be controlled per upstream, though?

This could lead to inconsistent results when two different upstreams return different responses.

**Comment by PussAzuki** [comment]
Because I think that will solve the problem of DNS pollution in the fastest IP address mode. After my tests with several mainland-based and global service-enabled DNS servers that support DoT, the last choice in the fastest IP address mode is basically the result of DNS located in the mainland, and then this result is pollution to some domain names. So I should need it ? My idea is that after solving the pollution problem, the fastest ip address mode should work better.

I think combined with dual-stack threshold optimization may solve more problems?

**Comment by ameshkov** [comment]
Do these "polluted" servers use specific IP addresses? You could use bogus-nxdomain instead

**Comment by PussAzuki** [comment]
Ah, I mean, sometimes the results returned by these servers are inevitably contaminated because of some problems, rather than all the results under that server are contaminated. And these servers happen to be able to resolve the fast ip addresses of services located in China.
So now you know what I mean, do you ?

**Comment by ameshkov** [comment]
What I am trying to understand is what's that "contamination". Could you please show an example?

**Comment by PussAzuki** [comment]
For example, when parsing the IP address of google.com, the server in China can return a normal and correct result, but if you give a prefix like www or others, it will return a result that cannot be used. I think this could be proved easily. However, this is not the case with the global public DNS, but the latter generally cannot provide the IP address of the CDN of the service in Chinese mainland. This makes it slow or slow for Chinese mainland residents to access services in the mainland.

**Comment by ameshkov** [comment]
> it will return a result that cannot be used

What the result would be?

Is it the same set of IP addresses all the time?

You see, there's a [`bogus_nxdomain` setting](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) in AdGuard Home that allows you to transform responses with the specified IP addresses to NXDOMAIN.

**Comment by PussAzuki** [comment]
Sometimes it could just be Facebook's IP addresses and it is easy to be solved , sometimes could be just a strange IP addresses like 2001::1f0d:5124 , which can make user confused.
I do not think it would be the same set of IP addresses all the time.

**Comment by ameshkov** [comment]
My thinking is that the feature you're suggesting does not actually solve the pollution issue. It may help short-term, but what if they start returning IPv4 addresses for instance?

> sometimes could be just a strange IP addresses like 2001::1f0d:5124

Is there anything common among these addresses? Subnet maybe?

**Comment by PussAzuki** [comment]
My opinion: first solve the problem on IPv6, then solve the problem on IPv4. The proposal now is to implement the former, because Chinese mainland services generally have IPv4 addresses, so disabling AAAA requests to Chinese mainland's DNS can solve a problem. Since there are other reliable global DNS servers, there should be no need to worry about these problematic DNS servers returning only IPv4 addresses. 

I used to use software named [smartdns](https://github.com/pymumu/smartdns) to perform DNS resolution and diversion on all domain names in the certificate used by the domain name. So I didn't pay much attention. I'm sorry I can't help.

**Comment by ameshkov** [comment]
Does smartdns successfully filter out such invalid responses?

If it does, do you know what method it uses to do this?

**Comment by PussAzuki** [comment]
The software allows the user to set an allow / block list based on the IP address for each DNS upstream, thus giving the user the choice to filter the results. For example, for Chinese mainland users, they only need to set the upstream of DNS in the mainland to allow only the IPv4 results in Chinese mainland, and set the upstream of global DNS to filter the IPv4 and IPv6 results in Chinese mainland to achieve the goal of DNS query diversion. This can solve the problem of confusion to a great extent.

If a problem can be solved by one software, I don't need to overcombine it with multiple software, do I?

**Comment by ameshkov** [comment]
Sure, I am just trying to figure out the best way to solve the DNS pollution issue

> For example, for Chinese mainland users, they only need to set the upstream of DNS in the mainland to allow only the IPv4 results in Chinese mainland, and set the upstream of global DNS to filter the IPv4 and IPv6 results in Chinese mainland to achieve the goal of DNS query diversion

Is there an example of the working configuration that solves this?

**Comment by PussAzuki** [comment]
Sure, see below

In view of the fact that the software's web control interface is not as fast and efficient as handwritten, I changed its [startup script](https://paste.ubuntu.com/p/zkvMgVMX5P/).

Then create [main config file](https://paste.ubuntu.com/p/q9CJjZ9zGP/) and create multiple blank files according to the contents of the main configuration file

Then using "curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt" to get the China IPv4 CIDR, then do similar to IPv6. Then mark each line with whitelist-ip or blacklist-ip, and write it to the corresponding file.

**Comment by ameshkov** [comment]
What are these whitelist-ip and blacklist-ip settings? Does it make sense to add the same setting to AGH?

**Comment by PussAzuki** [comment]
It's easy to explain, whitelist-ip and blacklist-ip are just tags for matching. When the query result hits these tags, the corresponding allow or block actions are triggered. 

It should make sense to add the similar settings to AGH, but it should not conflict with the functions currently under discussion.

**Comment by ameshkov** [comment]
> It should make sense to add the similar settings to AGH, but it should not conflict with the functions currently under discussion.

Doesn't it solve this issue as well?

Having these blacklist/whitelist tags you can blacklist `::/0` effectively disabling IPv6 for a particular upstream

**Comment by PussAzuki** [comment]
That's a good idea, but in that software named smartdns you can just use whitelist function, and get all IPv6 away. The blacklist and whitelist functions can work independently, and you can also choose not to make any restrictions.

**Comment by ameshkov** [comment]
Yeah, what I mean is that whitelist/blacklist kinda solves this issue automatically so maybe it'd be better to implement it and not the requested feature.

**Comment by PussAzuki** [comment]
But the blacklist/whitelist looks like requiring additional files to save data, even if there is only one row of data.

I'd rather add both than one of them but I am not good at coding.

**Comment by ameshkov** [comment]
In our case, this is likely to be just new fields in AdGuardHome.yaml.

**Comment by PussAzuki** [comment]
If you just add these functions to the upstream part of DNS, it really only needs a few extra characters, but I think Chinese mainland users may use files such as chnroute. 

At least in my opinion, at least two additional files should be added to store the whitelist and the blacklist IP, so ...

**Comment by PussAzuki** [comment]
Excuse me, are there any new developments in this function?

**Comment by ameshkov** [comment]
No updates yet. We usually keep an eye on the number of upvotes on an issue, and that's how we decide what to implement.

**Comment by PussAzuki** [comment]
> > it will return a result that cannot be used
> 
> What the result would be?
> 
> Is it the same set of IP addresses all the time?
> 
> You see, there's a [`bogus_nxdomain` setting](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) in AdGuard Home that allows you to transform responses with the specified IP addresses to NXDOMAIN.

I doubt the solution you mentioned here. I tried to add two black hole routed IP to the configuration file, and then restarted the software, but it didn't seem to solve the problem, or returned the two problematic IP to the client, turned on debug mode and didn't see why. 
In addition, I tried to use the baniop function on openwrt to block access to these two IP, but the results of debug showed that the goal was unreachable, but the action had not been changed.

**Comment by PussAzuki** [comment]
Separate a question from a request
