### ISSUE TITLE
禁止反向DNS查询

### ISSUE THREAD

**Issue by xiaoqi2020** [AdguardTeam/AdGuardHome#2171]
如题，请问大哥大佬，怎么禁止这类反向查询的DNS？
![图片](https://user-images.githubusercontent.com/50669177/95650091-d756b480-0b13-11eb-9dc3-189675af1478.png)

**Comment by ameshkov** [comment]
你可以显示全的域名吗？

**Comment by xiaoqi2020** [comment]
![image](https://user-images.githubusercontent.com/50669177/95855330-c9f72f80-0d8a-11eb-8413-a0deefa9f5bc.png)
你是指这个吗？

**Comment by xiaoqi2020** [comment]
> 你可以显示全的域名吗？
https://user-images.githubusercontent.com/50669177/95855330-c9f72f80-0d8a-11eb-8413-a0deefa9f5bc.png

**Comment by ameshkov** [comment]
是，谢谢。

你可以试试用这样的规则：`||dynamic.163data.com.cn`，把这个规则加入到自定义过滤。

这个规则将屏蔽这些查询请求，可是你在被拦截排行还看这些请求。

**Comment by xiaoqi2020** [comment]
> 是，谢谢。
> 
> 你可以试试用这样的规则：`||dynamic.163data.com.cn`，把这个规则加入到自定义过滤。
> 
> 这个规则将屏蔽这些查询请求，可是你在被拦截排行还看这些请求。

好的，我试试，谢谢~！ 没有彻底屏蔽的方式吗？这样子的话就只能看到一个屏蔽一个了！

**Comment by netitgo** [comment]
我也很多反向DNS查询。。。是不是不启用ADG的DHCP，由主路由分配IP的话，就会有rDNS出现呢？
