### ISSUE TITLE
openwrt DNS forwarding Bug?

### ISSUE THREAD

**Issue by lqh280** [AdguardTeam/AdGuardHome#2176]
I use Adguard Home on my openwrt router, Network>DHCP/DNS>DNS forwarding, add 127.0.0.1#5353, Saved, reboot openwrt or sometime later, it will add another record like 127.0.0.1#5053 or 127.0.0.1#5333, why?

**Comment by ameshkov** [comment]
I am pretty sure this has nothing to do with AdGuard Home. Looks lie this is either a bug of the openwrt app you're using (luci-app-adguardhome probably?) or the firmware.

Tbh, I don't know why it's done.
