### ISSUE TITLE
Gzipped Blocklists?

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#2177]
#### Feature Description

Please consider adding support for gzipped blocklists or similar.

Quartering the download size of every blocklist update would be nice 👍 

e.g:

![a1](https://user-images.githubusercontent.com/17044982/95689717-712a7880-0c5e-11eb-9e69-c35dd6a103ae.PNG)

**Comment by josephbu** [comment]
Most modern web servers will compress/gzip on the fly, so often it's not that much difference as to the actual data transfer.

Additionally the application then also needs to have support to extract/decompress/manage the files.

**Comment by DandelionSprout** [comment]
It would be a huge accomplishment if AdGuard Home became able to interpret compressed filterlists (Not just .tar.gz, but also .zip and .7z), because I'm not aware of *any* adblocker tools in existence that are able to do that.

I support this notion all the way, for the record.

**Comment by ameshkov** [comment]
> because I'm not aware of any adblocker tools in existence that are able to do that

Well, we don't do that for a reason.

As @josephbu explained, this is already a part of all modern web servers. For instance, filter lists that are downloaded from Github are already compressed (see the Content-Encoding header in the server response).

**Comment by hl2guide** [comment]
Please reconsider this issue as it has many basic advantages. Even support for a generic .zip format would be great.

A real world example that I'm running into is that I have a over 60MB blocklist (that cannot be uploaded to GitHub because of their size limit). As a zip it is around just 17MB.

Link: https://github.com/hl2guide/Filterlist-for-AdGuard/blob/master/2.5%20ALPHA%201/filter_blocklist.zip?raw=true

**Comment by ameshkov** [comment]
> that cannot be uploaded to GitHub because of their size limit

Uploaded via their web interface? What about committing it to a repo?
