### ISSUE TITLE
Custom Blocked Services

### ISSUE THREAD

**Issue by danselstory** [AdguardTeam/AdGuardHome#2178]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [-] I am running the latest version
- [-] I checked the documentation and found no answer
- [-] I checked to make sure that this issue has not already been filed

### Problem Description

I want to block certain sites from certain devices (per devices blocking)

### Proposed Solution

I believe it's best if we can customize our own "Blocked Services" page? like adding URLs that we want to block ourselves?
http://x.x.x.x/#blocked_services

**Comment by ameshkov** [comment]
> I want to block certain sites from certain devices (per devices blocking)

You can do that using custom filtering rules already, see this: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client
