### ISSUE TITLE
[Feature request] [Question] Add connectivity check [it's possible via dns?]

### ISSUE THREAD

**Issue by JoseGalRe** [AdguardTeam/AdGuardHome#2180]
### Problem Description
Different device platforms verify connectivity at random time or when connecting to a network

### Proposed Solution
I dont know if this can be done via DNS, but if possible
add a option in general settings or a new miscellaneous section to manager the connectivity check
but, I also don't know if this could affect the security of AdGuardHome

example:

#### Android
```
via "http://connectivitycheck.gstatic.com/generate_204" return a 204 http code to check conectivity so,

redirect, move or replace "http://connectivitycheck.gstatic.com (http://connectivitycheck.gstatic.com/generate_204)"

to "http://myadguardinstace.com (http://myadguardinstace.com/generate_204)" and return 204 code
```

#### Windows "I have no idea if this can be done"
```
via "www.msftconnecttest.com/connecttest.txt" return a 200 http code with etag to check conectivity so,

redirect, move or replace "http://www.msftconnecttest.com (www.msftconnecttest.com/connecttest.txt)"

to "http://myadguardinstace.com (http://myadguardinstace.com/connecttest.txt)" and return 200 code
```

### Additional Information
I found this urls to check the connectivity

#### Windows
```
www.msftconnecttest.com
www.msftncsi.com
```

#### Android
```
connectivitycheck.gstatic.com
connectivitycheck.android.com
```

#### Apple "i dont know if this is the url"
```
captive.apple.com
```

### Alternatives Considered
I currently use an nginx to set a connectivity check for Android,
but it would be great to have this in AdGuardHome avoiding modifying the system settings of each device,
if possible

nginx settings
```
location "/idontusegoogle" {
    return 204;
}
```

android settings
```
settings put global captive_portal_http_url http://myadguardinstace.com/idontusegoogle
settings put global captive_portal_https_url https://myadguardinstace.com/idontusegoogle
settings put global captive_portal_fallback_url https://myadguardinstace.com/idontusegoogle
settings put global captive_portal_other_fallback_urls https://myadguardinstace.com/idontusegoogle
```

**Comment by ameshkov** [comment]
The only thing you can do via DNS is redirecting domains `connectivitycheck.gstatic.com  -> myadguardinstace.com `.

Route it to your nginx instance and return either 204 or 200 responses depending on the hostname.
