### ISSUE TITLE
VPS security concern

### ISSUE THREAD

**Issue by Toudahl** [AdguardTeam/AdGuardHome#2181]
Hi,

Multiple places in your documentation, you are describing how to run adguard home on a VPS, and how that would allow you to get the benefit of adguard at all times.
So, to that end, i have set up an instance of adguard home in docker in google cloud.

I have of course enabled DoH and DoT. Right now, DoT is exposed to the world, while the UI/DoH is only for two IPs.
My concern however is that exposing port 443 to all IPs to allow use of DoH will allow someone to attempt brute forcing my login.

Are there any way build into adguard home to change the port the UI is served on?   
Is it safe to expose the UI to the world? I have a pretty hefty password

**Comment by ameshkov** [comment]
Hi, the only way to do this right now is to use a reverse proxy in front of AGH: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy

**Comment by Toudahl** [comment]
@ameshkov Thanks for your reply. What about my security question?
Would it be safe to expose the UI to the world? Provided I have a proper username?

**Comment by ameshkov** [comment]
> Would it be safe to expose the UI to the world? Provided I have a proper username?

Yeah, it would be safe, brute-forcing may take years if you use a complicated username/password.

PS: we should think about implementing a rate-limit on the login form anyway.
