### ISSUE TITLE
Question: Setting domain-name in DHCP-Settings

### ISSUE THREAD

**Issue by derolidev** [AdguardTeam/AdGuardHome#2184]
Hi there.

I'm thinking about to move from Pi-hole to AdGuard Home, because the gui is much more lightweight and reduced to the basic requirements. Actually I'm missing a option to set a domain-name via dhp-option like Pi-hole offers it. 
Is there any configuration where a domain-name can be set or does AdGuard not offer this function?

Thanks a lot.

![Unbenannt](https://user-images.githubusercontent.com/63025466/95891434-5e5e9380-0d85-11eb-9460-e4f5f8e72a1f.PNG)

**Comment by ameshkov** [comment]
You can do pretty much the same using DNS rewrites, just add a rewrite and point `adguard-home` to the IP address of your AGH.
