### ISSUE TITLE
Top clients area didn't show the Clients' IP position in the newest version of ADGHome. How to solve this problem?

### ISSUE THREAD

**Issue by wxf26054** [AdguardTeam/AdGuardHome#2186]
![image](https://user-images.githubusercontent.com/22016320/95939389-8cd48100-0e0e-11eb-9d0c-7fd688e40a57.png)

**Comment by ameshkov** [comment]
Well, it was never shown there:)

Do you want it to look like this?
```
1. client (IP) 123123
2. client2 (IP2) 23213
...
...
100. client100 (IP100) 123
```

**Comment by wxf26054** [comment]
No.
![image](https://user-images.githubusercontent.com/22016320/95963310-1c435980-0e3a-11eb-9bec-62f4a65ef57f.png)

Before, the top clients area would show the exact ip position of every client like red color cycle on the screenshot above.

**Comment by ameshkov** [comment]
Got it.

We don't show this for custom clients (the ones that are added via "Clients" or added via the /etc/hosts file).
It seems that this is what happened in your case - check if you added /etc/hosts records for these IP addresses, or if you added a client manually

**Comment by wxf26054** [comment]
Like this

Client IP
Exact IP position

**Comment by wxf26054** [comment]
Thank you! I've got the reason why it dosen't show the clients' IP position.
Now it has come to a normal display.
![Uploading image.png…]()
