### ISSUE TITLE
AdGuardHome + FritzBox + DNS over TLS

### ISSUE THREAD

**Issue by clipse2004** [AdguardTeam/AdGuardHome#2187]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

* **Version of AdGuard Home server:**
  *Newest
* **How did you setup DNS configuration:**
  * Router -> Internet Access Data -> Raspberry Pi4 IP Adress, and follow Upstream Server:
https://dns10.quad9.net/dns-query
https://dns.adguard.com/dns-query
https://doh.ffmuc.net/dns-query
In the Router under Home Network -> Standard
 
* **If it's a router or IoT, please write device model:**
  * Router FritzBox 6591 and Raspberry Pi4
* **Operating system and version:**
  * Raspbian

### Actual Behavior
Hello everyone,
I have now switched from PiHole to AdGuardHome and run it on my Raspberry Pi.
But I don't quite get along with DNS over TLS and the general setup.
Let's start with the settings in the router, currently I have specified the Raspberry Pi under Access Data -> DNS Server. Does it make sense to do this under Home Network -> IPv4 and IPv6 -> DNS Server? It should be checked only all requests that go out, right?
With DNS over TLS I have the problem that I don't know what to enter in AdGuardHome under "Certificate", there is the tab Path for the certificate file or content of the certificate. Exactly the same I have with the private key.
I have already activated DNS over TLS in my router, but what do I enter as "DNS server resolution name"?

Thank you for your help!

**Comment by ameshkov** [comment]
> Let's start with the settings in the router, currently I have specified the Raspberry Pi under Access Data -> DNS Server. Does it make sense to do this under Home Network -> IPv4 and IPv6 -> DNS Server? It should be checked only all requests that go out, right?

Never used FritzBox, but I suppose that's right, you should use it everywhere.

> With DNS over TLS I have the problem that I don't know what to enter in AdGuardHome under "Certificate", there is the tab Path for the certificate file or content of the certificate. Exactly the same I have with the private key.

You don't need that for a local DNS server.

Running your own encrypted resolver makes sense only if you're running AdGuard Home on a public server and that's clearly not your case.

**Comment by clipse2004** [comment]
Yes but I have selected the Fritzbox as DNS server in the Fritzbox under Home Network and NOT AdGuard, so you think I should set that there too?

**Comment by ameshkov** [comment]
It's hard for me to say. You should try it and see if it does not break anything :)
