### ISSUE TITLE
[Beta] Unable to resize upstream DNS servers input box

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#2189]
On latest beta (0.104.0-beta2), there is no longer an option to resize the upstream DNS input box.

![image](https://user-images.githubusercontent.com/62358249/96046566-9a6c2400-0e6b-11eb-98f8-ec7aac5fd4ed.png)

On 0.103.3, you can see the resize button in bottom right side. This option is provided by the browser and looks like it got disabled at some point during UI changes. Not sure if it is intentional or accidental.

![image](https://user-images.githubusercontent.com/62358249/96046490-79a3ce80-0e6b-11eb-8762-1208f9b40511.png)

**Comment by ameshkov** [comment]
This field is not a textarea anymore since now it supports highlighting (try entering a comment there -- start a line with `#`).
