### ISSUE TITLE
url for AdAway returns github page

### ISSUE THREAD

**Issue by martinezrw** [AdguardTeam/AdGuardHome#2190]
AdAway blacklist wont populate because the URL provided references a github page, updating to use raw file resolves issue.

URL provided in new install = https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt
Updating to this resolves the issue,  https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

**Comment by KizunaH** [comment]
See https://github.com/AdguardTeam/AdGuardHome/pull/2047/files

**Comment by yololftw** [comment]
I updated it manually by using edit button and pasting the updated URL but I get : `Error: control/filtering/set_url | URL doesn't exist | 400`
Is this because this is a default blacklist?
