### ISSUE TITLE
Filter query log by client hostname (including reverse resolved)

### ISSUE THREAD

**Issue by dsheets** [AdguardTeam/AdGuardHome#2191]
### Problem Description
The machines on my network all have short, memorable, well-known names. I want to use these names to browse the query log but the query log filter only inspects literal fields of the json log entries.

### Proposed Solution
Host names used as query log filters are checked through the known client directory and, if found, the resultant query is OR of existing functionality and client IP.

### Alternatives Considered
1. If resolution succeeds, ONLY the resolved IP is used for the filter.
2. Logs extended to include resolved client host names.
3. Support for logging to an external service like an ELK deployment.

**Comment by ameshkov** [comment]
Looks like a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1273

**Comment by dsheets** [comment]
Indeed it is... I somehow missed that in my search. :-/

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/594
