### ISSUE TITLE
Local Domains like NAS are not resolved

### ISSUE THREAD

**Issue by lordvalium** [AdguardTeam/AdGuardHome#2194]
* **Version of AdGuard Home server:**
 (0.103.3) 
* **How did you setup DNS configuration:**
(IP of the Raspberry is in my local Router. Raspberry is host for AGH)
* **If it's a router or IoT, please write device model:**
   (Raspberry Pi 3 Model B) 
* **Operating system and version:**
 (latest rasbian for Pi3 ) 

### Expected Behavior
Have a local Synology Nas. I want to open it with http://myNAS

### Actual Behavior
Can just open it with the IP http://192.168.188.21

### Additional Information
Tried so far: 

- added to /etc/hosts on the raspberry 
`192.168.188.21 myNAS`

I have tried that https://github.com/AdguardTeam/AdGuardHome/issues/694 and that https://github.com/AdguardTeam/AdGuardHome/issues/461
Both dont work. 
![image](https://user-images.githubusercontent.com/2970225/96166815-c8f70700-0f1e-11eb-869d-3acd7a666cff.png)

**Comment by phixion** [comment]
add a local resolver (your router for example) for your internal domain:
![upstream](https://i.phx.ms/l9qw.png)

or add a rewrite:
![rewrite](https://i.phx.ms/SKoX.png)

**Comment by lordvalium** [comment]
@phixion thank you for your reply. 
Tried the DNS rewrite with 
myNAS and the IP. Does not work. 

You have the suffix .yourdomain.com 

Does that have any reason? In my NAT is no domain.

**Comment by phixion** [comment]
Try rewrite If you dont use a domain

**Comment by lordvalium** [comment]
> Try rewrite If you dont use a domain

I dont understand what to do. 
Thx in advance

**Comment by ameshkov** [comment]
1. Clean you custom filtering rules
2. Add a DNS rewrite - `mynas` (lower case) and `192.168.188.21`
3. It should work. If it's no, please show the output of the `nslookup mynas command`

**Comment by lordvalium** [comment]
@ameshkov 

Added custom filter rule as proposed:

1. `nslookup mynas` in terminal on raspberry 

> Server:		127.0.0.1
Address:	127.0.0.1#53
>
>Non-authoritative answer:
*** Can't find mynas: No answer

2. `nslookup mynas` in terminal from my linux laptop locally
>Server:		127.0.0.53
Address:	127.0.0.53#53
>
>** server can't find mynas: SERVFAIL

It is not working. 
I also have cleaned up my /etc/hosts because i had there names for resolving clients in local network.

**Comment by ameshkov** [comment]
`127.0.0.1#53 ` -- do you have AdGuard Home running there or is it some other tool?

Do you see this query in AGH query log?

**Comment by lordvalium** [comment]
Yes I have adguard home running on a raspberry.
The ip of the pi is dns server in my router.

No, no other tool. Just some osx/iOS and Linux clients.

No I see that in terminal ssh session 


Am 20.10.2020 um 00:56 schrieb Andrey Meshkov <notifications@github.com>:

﻿
127.0.0.1#53 -- do you have AdGuard Home running there or is it some other tool?

Do you see this query in AGH query log?

**Comment by ameshkov** [comment]
Could you please examine the query log and check if you see this `mynas` query there?

I am not able to reproduce this issue on my side. I see 2 options:

1. You aren't querying AGH (if you can't find your `mynas` query in the log - that's it)
2. Something is wrong with the DNS rewrite you added (plz show me a screenshot)

**Comment by lordvalium** [comment]
Hi, first i had mynas just as synonym. Real name of the NAS is "monster" :+1: 

The the incident:

I have checked the query log and just see calls from my computer. 
Some seconds before i tried to open my NAS by name, not IP: `http:\\monster:8181`

![image](https://user-images.githubusercontent.com/2970225/96628719-e78c4200-1312-11eb-977a-6c2a3f8002c3.png)

to your first point 1: 
I can find monster, but with the suffix .fritz.box

to your second point 2:
![image](https://user-images.githubusercontent.com/2970225/96628866-17d3e080-1313-11eb-992c-2405231e64ab.png)

**Comment by ameshkov** [comment]
> I can find monster, but with the suffix .fritz.box

Weird. `fritz.box` most likely is the "search" domain.
Just in case, try adding `monster.fritz.box` and see if it helps.

**Comment by lordvalium** [comment]
Unbelievable @ameshkov  but with monster.fritz.box everything is working

I dont understand it but its working :) Great thx

**Comment by phixion** [comment]
I dont want to overcomplicate this but **adding** these two to your upstream DNS should allow you to leave out the FQDN and go by the hostname:

```
[/fritz.box/]192.168.188.1
[/188.168.192.in-addr.arpa/]192.168.188.1
```

I am assuming here that your fritz router has the IP 192.168.188.1 and that your fritz router is the DHCP server of your network.

**Comment by lordvalium** [comment]
I did thank you :+1: 
So with adding that to the upstream DNS i could leve out the .fritz.box from the rewrite setting :)

**Comment by phixion** [comment]
Awesome!

**Comment by lordvalium** [comment]
Your support was amazing

**Comment by lordvalium** [comment]
Dear @phixion  its not working anymore. 

I cant enter "monster"

![image](https://user-images.githubusercontent.com/2970225/110161623-e7866d80-7ded-11eb-99c4-02ab40569ad3.png)

**Comment by ameshkov** [comment]
Please check that you're using latin characters and there're no extra spaces anywhere.

**Comment by phixion** [comment]
try to use `monster.fritz.box` instead of `monster`; it might be related to this issue https://github.com/AdguardTeam/AdGuardHome/issues/2582

Martin

**Comment by thewavelength** [comment]
@phixion I found this thread and I think it's the same issue. I have set `local_domain_name` to `php`. The host on which AdGuard is running is named `base`. Resolving `base` (without `.php`) works but it doesn't work for any other connected client. This works for Pi-Hole as expected and is a blocker for me to fully switch to AdGuard Home sadly.

```
D:\>nslookup base
Server:  base
Address:  192.168.178.101

Non-authoritative answer:
Name:    base
Addresses:  ::ffff:192.168.178.101
          192.168.178.101


D:\>nslookup base.php
Server:  base
Address:  192.168.178.101

Non-authoritative answer:
Name:    base.php
Address:  192.168.178.101


D:\>nslookup gmt
Server:  base
Address:  192.168.178.101

*** base can't find gmt: Non-existent domain

D:\>nslookup gmt.php
Server:  base
Address:  192.168.178.101

Non-authoritative answer:
Name:    gmt.php
Address:  192.168.178.103
```

**Comment by ameshkov** [comment]
@thewavelength have you tried adding a DNS rewrite `base -> 192.168.178.101`? "Filters" -> "DNS rewrites"

**Comment by thewavelength** [comment]
@ameshkov Sorry, the problem is not with `base` but with all other clients in my network (e. g. `gmt` not resolving, but `gmt.php`). Do I really have to add a DNS rewrite for every device/client manually? :-/

**Comment by ameshkov** [comment]
@ainar-g what do you think? How dnsmasq behaves in this case?

**Comment by thewavelength** [comment]
@ameshkov Just throwing in that in Pi-Hole this works and they are using dnsmasq too.

**Comment by ainar-g** [comment]
@thewavelength, do you have AGH as your network's DHCP server?  `local_domain_name` only works when it is.

**Comment by thewavelength** [comment]
@ainar-g I do, the DHCP of my ISP router is disabled. Here's my config. Please ignore it's invalid as I removed some not-important entries for privacy reasons.
[config.txt](https://github.com/AdguardTeam/AdGuardHome/files/6533772/config.txt)

**Comment by ainar-g** [comment]
@thewavelength The reason why AGH can resolve `base` without the `.php` TLD is probably because `base` is in your base machine's /etc/hosts file, while `gmt` isn't.  You can either add it there—along with its IP—and see if that fixes the issue there.  You can also try and add a [`$dnsrewrite`] rule.  Again, the DHCP hosts are resolved only with the ` local_domain_name` present.

[`$dnsrewrite`]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by thewavelength** [comment]
@ainar-g Thanks for the clarification. So it's not a bug. Then I'd like to ask in a different way: are there plans to support this feature in the future? Adding devices manually is a workaround, sure, but not a good one imho.

**Comment by ainar-g** [comment]
@thewavelength, I am not aware of such plans, tbh.  [`$dnsrewrite`] rules already give the user the ability to essentially create a DNS zone of their own.  Perhaps there will be a pretty UI on top of it, but again, I don't know of such plans.

[`$dnsrewrite`]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite
