### ISSUE TITLE
Upstream and Bootstrap questions

### ISSUE THREAD

**Issue by ps-a** [AdguardTeam/AdGuardHome#2195]
I don't have more knowledge about DNS. i though to ask my questions from adguard.

agh supports tls address for bootstrap (tls://8.8.8.8). can you explain what's the benefit compared to plain 8.8.8.8 in bootstrap? literally i know it mean about encrypt and description says "Bootstrap DNS servers are used to resolve IP addresses of the DoH/DoT resolvers you specify as upstreams" actually what data it help to hide and how does it help to enhance privacy?

why `tls://94.140.14.140` doesn't work? google, quad9, cloudflare support for it already

**Comment by ameshkov** [comment]
> can you explain what's the benefit compared to plain 8.8.8.8 in bootstrap? 

If you use a domain name (like `tls://dns.google` or `tls://dns.adguard.com`), Bootstrap DNS is used one time to resolve this domain IP address. You can do it via a plain unencrypted DNS request, or use a TLS bootstrap and have this query encrypted.


> why tls://94.140.14.140 doesn't work? google, quad9, cloudflare support for it already

It will work in the future, we just need to obtain a proper certificate for the IP address.
