### ISSUE TITLE
Logins to console.helium.com broken

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdGuardHome#2196]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Brume GL-MV1000
* **Operating system and version:**
  * elementary OS 5.1.7 Hera

### Expected Behavior
Log into console.helium.com

### Actual Behavior
Page never redirects to auth.helium.com to allow for log in. Stuck at blank page.

### Additional Information
Disabling Adguard home process resolves the issue

**Comment by ameshkov** [comment]
I cannot reproduce this with AGH. Could you please try disabling blocklists one by one to figure out which one is problematic?

**Comment by sysfu** [comment]
I'm unable to reproduce the issue myself while at home using same router and firmware running Adguard home process. Will try again at work and disable blacklists one by one to see if that resolves.
