### ISSUE TITLE
Nginx proxy v0.104.0-beta2 can not log in

### ISSUE THREAD

**Issue by CalmLong** [AdguardTeam/AdGuardHome#2197]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  [AdGuard Home v0.104.0-beta2](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.104.0-beta2)
* **Operating system and version:**
  Ubuntu 18.04

### Actual Behavior

Nginx proxy [AdGuard Home v0.104.0-beta2](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.104.0-beta2) can not log in

Reference https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy 
but in `v0.104.0-beta2` this configuration seems to be missing something

After clicking login, the page will automatically refresh, but it does not enter the background

### Additional Information

nginx conf

```nginx
server
{
   listen 443 ssl http2;
   server_name dns.com;

   _ssl_config_

   location /admin/ {
       proxy_pass http://0.0.0.0:3053/;
       proxy_redirect / /admin/;
       proxy_cookie_path / /admin/;
   }


   location / {
       proxy_pass http://127.0.0.1:3053/dns-query;
       proxy_http_version 1.1;
       proxy_redirect off;
       proxy_buffering off;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr; 
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by ameshkov** [comment]
Weird, I don't remember any changes on our side. Anyways, we'll test it, thank you

**Comment by Onepamopa** [comment]
Try adding:
proxy_pass_header  Set-Cookie;
proxy_pass_header  P3P;

**Comment by CalmLong** [comment]
Thanks, but it doesn't work
