### ISSUE TITLE
Parental control, browsing security and ad-filtering solution weakness

### ISSUE THREAD

**Issue by ps-a** [AdguardTeam/AdGuardHome#2198]
This setup will automatically cover all the devices connected to your home router (or it can be dedicated server router, access point) and you will not need to configure each of them manually. even if i configured every home devices DNS settings manually, this still a trash when i want to take care of stubborn children or co-workers. beginner knowledge enough for change DNS on a computer. 

i'm not interest to install high privilege vulnerable tool on devices for prevent change DNS and it's a battery drain solution for phones.

Known solution: they must have less IT knowledge or listen to what i said. (for offices: there're enterprise products. we can't afford them for home)

As built-in DHCP in ag home, isn't it possible to develop something to lockdown selected ports. 53, 443, 853...  process (filter and ignore) whole traffic/requests through agh receive from any devices in network? +https://github.com/AdguardTeam/AdGuardHome/issues/101 is nice

**Comment by ameshkov** [comment]
> isn't it possible to develop something to lockdown selected ports. 53, 443, 853... process (filter and ignore) whole traffic/requests through agh receive from any devices in network?

In theory, yes it's possible. And in the future, we would like AdGuard Home to control all the traffic and not just DNS. However, this would require quite some time to develop. In order to achieve this, AdGuard Home needs to become a router.

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2206
