### ISSUE TITLE
Not blocking ads- AdGuard Home in Home Assistant 

### ISSUE THREAD

**Issue by GMA100** [AdguardTeam/AdGuardHome#2200]
I followed all the steps for the router install but it’s not blocking ads, especially on my iPhone. Greatly appreciate your help!

**Comment by ameshkov** [comment]
Do you see DNS queries from your iPhone in the query log?

**Comment by stefancvetkovic** [comment]
I also cannot make it work. I added dns server into my udm pro router, and have ad guard home on my hassio, and on all devices I can see ads.
In my query log I can see bunch of things, some of them are blocked, some of them not, but I can see only the ip address of my router, no other devices?

**Comment by ameshkov** [comment]
> and on all devices I can see ads.

Do a simple test - try opening `doubleclick.net` in your browser and see if it's blocked.

> but I can see only the ip address of my router, no other devices?

Some routers forward DNS queries to the specified DNS servers instead of using DHCP to propagate the real IP addresses. This may be the reason.

**Comment by ollfa** [comment]
I have the same problem. It worked flawlessly for about 6 month then stopped working in october this year. A few days ago it suddenly started to work again. Today at exactly 08 it stopped working again, i can see the chart in the control panel go from 100+ to zero. 

During this time I have not configured or updated adguard.

**Comment by ameshkov** [comment]
@ollfa it may mean that something out of AdGuard Home control has changed. It's either your router settings or your devices settings are changed.

Make sure that AGH is still used by your devices.
Check that known ad trackers are blocked on the devices (`doubleclick.net` for instance).
