### ISSUE TITLE
ADD DNS Srv记录

### ISSUE THREAD

**Issue by e703** [AdguardTeam/AdGuardHome#2201]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
Could you please explain what exactly would you like us to do?
