### ISSUE TITLE
Windows "No Internet"

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#2204]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
Latest

* **How did you setup DNS configuration:**
System

* **Operating system and version:**
Windows 10 2004, latest updates

### Expected Behavior
- Check the problem description

### Actual Behavior
After some hours of using AGH as the system resolver (DNS set to 127.0.0.1 on the network interface), Windows decides there's no internet connection, even though there's fully working internet connection, AGH is resolving properly.

### Screenshots
![windows_nointernet](https://user-images.githubusercontent.com/3053279/96493901-42a83100-124e-11eb-9d67-7bb422e3a60c.png)
<details>
<summary>Screenshot: No Internet</summary>
</details>

### Additional Information
I've tried:
- Disable all filters
- Remove all custom filters
- Disable "protection"

The problem with "No Internet" always appears, sometimes after few hours, sometimes - 2-3 days.
The problem disappears completely if I set the system resolver to 8.8.8.8 or anything, really, but when I'm using AGH - it always appears again.

This is really inconvenient because a lot of apps use the "windows's internet or not detection thing" to determine if there is a working connection, and stop working as soon as they see "No internet", example - Weather, Netflix, etc.

Here are all my "Upstream DNS":
tls://1.1.1.1
tls://dns.google
tls://dns.quad9.net
tls://dot.securedns.eu
https://dns.cloudflare.com/dns-query
sdns://AgUAAAAAAAAAACAe9iTP_15r07rd8_3b_epWVGfjdymdx-5mdRZvMAzBuQ5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs

Bootstrap is 8.8.8.8 and 1.1.1.1
Requests are set to parallel.

**Comment by AxelMilb** [comment]
Here the same 
Version: v0.104.0-beta2-SNAPSHOT-3a96fdd0

**Comment by ameshkov** [comment]
Examine the query log - do you see any blocked microsoft domains there? Try unblocking them and check if things change.

Also look for requests to `www.msftncsi.com` and `dns.msftncsi.com`, make sure they're not blocked.

**Comment by Onepamopa** [comment]
@ameshkov AGH shouldn't be blocking anything when "protection" is off, correct? Because the problem also occurs when it's off.

**Comment by ameshkov** [comment]
@Onepamopa is it easy to reproduce this issue?

If so, please collect AdGuard Home verbose log. I'll also need to know the exact time when the issue was reproduced.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by Onepamopa** [comment]
@ameshkov It's easy to reproduce - just enable AGH and wait, the problem is - it doesn't occur at an exact time, so it's between few hours and few days. I have no way of knowing when exactly windows "lost internet".

**Comment by Onepamopa** [comment]
Okay, I've enabled AGH verbose logging + custom event viewer log for all DNS client events.
Let's see...

**Comment by Onepamopa** [comment]
From windows event log:
03:54:17 AM: DnsQueryEx for the name dns.msftncsi.com is pending
03:54:17 AM: ame resolution for the name, dns.msftncsi.com, will not fall back to LLMNR or NetBIOS


NO entries for msftncsi exist in AGH verbose log, at all. Here's what's in the log for 03:54:17-18:

2020/10/21 03:54:17 23828#170905 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 127.0.0.1:55723
2020/10/21 03:54:17 23828#171123 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 127.0.0.1:55722
2020/10/21 03:54:17 23828#170905 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 10496
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ksn-cinfo-geo.kaspersky-labs.com.	IN	 A

2020/10/21 03:54:17 23828#171123 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 9032
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ksn-cinfo-geo.kaspersky-labs.com.	IN	 AAAA

2020/10/21 03:54:17 23828#171123 [debug] IPv6 is disabled. Reply with NoError to ksn-cinfo-geo.kaspersky-labs.com. AAAA request
2020/10/21 03:54:17 23828#170905 [debug] Using settings for client localhost with IP 127.0.0.1
2020/10/21 03:54:17 23828#170905 [debug] AutoHosts: answer: ksn-cinfo-geo.kaspersky-labs.com -> []
2020/10/21 03:54:17 23828#171123 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 9032
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;ksn-cinfo-geo.kaspersky-labs.com.	IN	 AAAA

;; AUTHORITY SECTION:
ksn-cinfo-geo.kaspersky-labs.com.	10	IN	SOA	fake-for-negative-caching.adguard.com. hostmaster.ksn-cinfo-geo.kaspersky-labs.com. 100500 1800 60 604800 86400

2020/10/21 03:54:17 23828#170911 [debug] https://dns.google.com:443/experimental: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:17 23828#170906 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*TLSPool).Get(): Returning existing connection to 1.1.1.1:853 with updated deadLine
2020/10/21 03:54:17 23828#170907 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*TLSPool).Get(): Returning existing connection to 8.8.4.4:853 with updated deadLine
2020/10/21 03:54:17 23828#170906 [debug] tls://1.1.1.1:853: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:17 23828#170908 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*TLSPool).Get(): Returning existing connection to 9.9.9.9:853 with updated deadLine
2020/10/21 03:54:17 23828#170780 [debug] 8.8.4.4:53: sending request AAAA dot.securedns.eu.
2020/10/21 03:54:17 23828#171139 [debug] 1.1.1.1:53: sending request AAAA dot.securedns.eu.
2020/10/21 03:54:17 23828#170906 [debug] tls://1.1.1.1:853: response: Failed to read a request from tls://1.1.1.1:853, cause: EOF
2020/10/21 03:54:17 23828#170910 [debug] https://dns.cloudflare.com:443/dns-query: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:17 23828#171138 [debug] 1.1.1.1:53: sending request A dot.securedns.eu.
2020/10/21 03:54:17 23828#171031 [debug] 8.8.8.8:53: sending request A dot.securedns.eu.
2020/10/21 03:54:17 23828#170907 [debug] tls://dns.google:853: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:17 23828#171032 [debug] 8.8.8.8:53: sending request AAAA dot.securedns.eu.
2020/10/21 03:54:17 23828#170908 [debug] tls://dns.quad9.net:853: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:17 23828#170779 [debug] 8.8.4.4:53: sending request A dot.securedns.eu.
2020/10/21 03:54:17 23828#170906 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverTLS).Exchange(): The TLS connection is expired due to Failed to read a request from tls://1.1.1.1:853, cause: EOF
2020/10/21 03:54:17 23828#170906 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): Dialing to 1.1.1.1:853
2020/10/21 03:54:17 23828#170908 [debug] tls://dns.quad9.net:853: response: Failed to read a request from tls://dns.quad9.net:853, cause: EOF
2020/10/21 03:54:17 23828#170908 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*dnsOverTLS).Exchange(): The TLS connection is expired due to Failed to read a request from tls://dns.quad9.net:853, cause: EOF
2020/10/21 03:54:17 23828#170908 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): Dialing to 9.9.9.9:853
2020/10/21 03:54:17 23828#170907 [debug] tls://dns.google:853: response: ok
2020/10/21 03:54:17 23828#170905 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 11 ms
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking CNAME ksn-cinfo.geoksn.kaspersky.com. for ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (62.67.238.148) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (81.19.104.15) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (81.19.104.163) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (62.67.238.138) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (62.67.238.150) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (81.19.104.18) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] DNSFwd: Checking record A (81.19.104.86) for ksn-cinfo.geoksn.kaspersky.com.
2020/10/21 03:54:17 23828#170905 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 10496
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ksn-cinfo-geo.kaspersky-labs.com.	IN	 A

;; ANSWER SECTION:
ksn-cinfo-geo.kaspersky-labs.com.	1766	IN	CNAME	ksn-cinfo.geoksn.kaspersky.com.
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	62.67.238.148
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	81.19.104.15
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	81.19.104.163
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	62.67.238.138
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	62.67.238.150
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	81.19.104.18
ksn-cinfo.geoksn.kaspersky.com.	3247	IN	A	81.19.104.86

2020/10/21 03:54:17 23828#170908 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): dialer has successfully initialized connection to 9.9.9.9:853 in 12 milliseconds
2020/10/21 03:54:17 23828#170906 [debug] github.com/AdguardTeam/dnsproxy/upstream.createDialContext.func1(): dialer has successfully initialized connection to 1.1.1.1:853 in 12 milliseconds
2020/10/21 03:54:17 23828#170910 [debug] https://dns.cloudflare.com:443/dns-query: response: ok
2020/10/21 03:54:17 23828#171139 [debug] 1.1.1.1:53: response: ok
2020/10/21 03:54:17 23828#171138 [debug] 1.1.1.1:53: response: ok
2020/10/21 03:54:17 23828#171073 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dot.securedns.eu in 20 milliseconds using 1.1.1.1:53. Result : []
2020/10/21 03:54:18 23828#170906 [debug] tls://1.1.1.1:853: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:18 23828#170908 [debug] tls://dns.quad9.net:853: sending request A ksn-cinfo-geo.kaspersky-labs.com.
2020/10/21 03:54:18 23828#170906 [debug] tls://1.1.1.1:853: response: ok
2020/10/21 03:54:18 23828#170908 [debug] tls://dns.quad9.net:853: response: ok
2020/10/21 03:54:18 23828#170911 [debug] https://dns.google.com:443/experimental: response: ok
2020/10/21 03:54:18 23828#171031 [debug] 8.8.8.8:53: response: ok
2020/10/21 03:54:18 23828#171032 [debug] 8.8.8.8:53: response: ok
2020/10/21 03:54:18 23828#171072 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dot.securedns.eu in 145 milliseconds using 8.8.8.8:53. Result : []
2020/10/21 03:54:18 23828#170780 [debug] 8.8.4.4:53: response: ok
2020/10/21 03:54:18 23828#170779 [debug] 8.8.4.4:53: response: ok
2020/10/21 03:54:18 23828#171071 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dot.securedns.eu in 167 milliseconds using 8.8.4.4:53. Result : []

**Comment by ameshkov** [comment]
The fact is that nothing is received by AGH is very-very strange and it actually means that the problem may be on the client-side. I wonder could it be ignoring DNS servers located on localhost?

**Comment by Onepamopa** [comment]
@ameshkov I've no idea if it does... now I've set the DNS server to listen on 0.0.0.0 and placed both 128.0.0.1 and 192.168.1.101 just in case it ignores 127.0.0.1 .... let's see.
