### ISSUE TITLE
Automatically update blocklists when idle

### ISSUE THREAD

**Issue by sjhgvr** [AdguardTeam/AdGuardHome#2207]
Not sure how it's taking care of atm, but I would suggest Adguard Home to automatically find the best time (within the set update interval) to update it's blocklists according to times when there are little to none DNS requests being handled.

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/3044

**Comment by ainar-g** [comment]
We will merge it into #3044.  Thanks for reporting!
