### ISSUE TITLE
Some Comments Break Filtering

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#2214]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.103.3
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * openSUSE Tumbleweed x86_64 (Kernel: 5.8.14-1-default)

### Expected Behavior
When you have a website blacklisted which also has a comment (such as, `||grabify.link #Comment`) it should still filter the domain

### Actual Behavior
The blocking is bypassed because of the comment

### Screenshots

<details><summary>Screenshot:</summary>

https://i.imgur.com/kFkXPmY.png

https://i.imgur.com/pu9oEDp.png

</details>

### Additional Information
It works with filters in non adblock syntax such as `https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt`

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/urlfilter #9](https://github.com/AdguardTeam/urlfilter/issues/9) via [**ZenHub**](https://www.zenhub.com/)
