### ISSUE TITLE
Strange behavior in the terminal

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#2215]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.104.0-beta3
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Windows 10 build 2004

### Screenshots

<details><summary>Screenshot: </summary>

![image](https://user-images.githubusercontent.com/46345396/96957817-63011580-1504-11eb-8797-e97a7344fa69.png)
![image](https://user-images.githubusercontent.com/46345396/96957878-8af07900-1504-11eb-96f7-beae884f6a80.png)

</details>

**Comment by ameshkov** [comment]
Could it be that the query log file is corrupted?

**Comment by ameshkov** [comment]
You can use this tool to anonymize and share your query log:
https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts/querylog

Also, if the anonymization tools prints any errors in the output, that could also be interesting

**Comment by Eyeborgs** [comment]
strange but it was an isolated case - and everything works as it should

if there is a new bug I will inform you

**Comment by Eyeborgs** [comment]
Я определил в чем проблема - когда я прокручиваю журнал запросов до конца - страница начинает лагать типо загрузки а в терминале покатается эта ошибка которая на скрине..

I determined what the problem is - when I scroll through the request log to the end, the page starts to error the type of loading, and in the theremin this error is shown which is on the screen ..

**Comment by ameshkov** [comment]
@Eyeborgs ну вот - мне нужен ваш лог, чтобы понять, в чем дело.

Используйте утилиту для анонимизации лога - https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts/querylog

**Comment by Eyeborgs** [comment]
@ameshkov у меня к сожалению в этом вопросе про утилиту мало опыта, прошу прощения..

**Comment by ameshkov** [comment]
@Eyeborgs ну если не жалко, можете просто свой лог нам прислать на devteam, мы посмотрим из-за чего именно в логе появляются эти записи.

Даже не весь лог нужен - попробуйте в нем оставить только первые строк 200 и посмотрите будет ли кидать в логе эту ошибку?

**Comment by Eyeborgs** [comment]
@ameshkov можете напомнить что включит для логирования в AdGuardHome.yaml

**Comment by ameshkov** [comment]
Ничего не включать, я про querylog*.json

**Comment by Eyeborgs** [comment]
Я не понимаю как это работает - я сейчас хочу вызвать данную проблему но все работает правильно и в консоле нет данной проблемы..

Хотя проблема в браузере есть при просмотре в журнале - бесконечная прокрутка вниз но она не обновляет запросы а если колесиком мышки поднять вверх а потом еще раз в них он погружает следующие результаты и так далее с этим багом..

Что странно раньше это было в консоле а сейчас нет..
