### ISSUE TITLE
DoH DNS Address

### ISSUE THREAD

**Issue by moofawsaw** [AdguardTeam/AdGuardHome#2218]
I require assistance setting up / retrieving the DoH DNS Address for my Adguard Home setup I have configured. The purpose is to use this through the Adguard Android App to block mobile traffic while using data.

CleanBrowsing offers this address and when I use this as a custom DNS inside of the Adguard mobile app for android I am able to apply all of the CleanBrowsing DNS filters through mobile data. Their browser platform looks identical to Adguard Home excpet they have provided a DoH DNS Address. Does Adguard Home provide this?

**Comment by KizunaH** [comment]
See instruction for adguardhome https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption
Correspond DNS solution to cleanbrowsing in adguard https://kb.adguard.com/en/general/dns-providers#adguard-dns

**Comment by moofawsaw** [comment]
> See instruction for adguardhome https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption
> Correspond DNS solution to cleanbrowsing in adguard https://kb.adguard.com/en/general/dns-providers#adguard-dns

I have set up Adguard Home and have it working properly using Cleanbrowsing as my Upstream DNS server. However I want to have my Adguard Home filters work over **mobile data.** Cleanbrowsing provides a custom DoH DNS Address that applies all of the custom filters I created through the Cleanbrowsing platform (similar to Adguard Home). My question is, how do I generate the custom DoH DNS Address for my Adguard Home setup so that I may apply them to work over mobile data using the Adguard mobile app?

**Comment by KizunaH** [comment]
>I installed Homebrew but I am not sure how to SSH into the server running my HTTP website as a user with sudo privileges (Step 1).

In this cause, you already using your Mac device and installed homebrew

**Comment by moofawsaw** [comment]
I ran `sudo certbot certonly --manual --preferred-challenges=dns` and when it asked for a domain name(s) it asks for a FQDN and not a URL. When I purchased my domain name, where do I find the FQDN address?

**Comment by KizunaH** [comment]
See https://en.wikipedia.org/wiki/Fully_qualified_domain_name
(https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#get-an-ssl-certificate)

In this guide has both default and wildcard instruction https://certbot.eff.org/lets-encrypt/osx-other
Alternatively you also can check https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#alternative-to-certbot-lego

**Comment by moofawsaw** [comment]
Thank you for the documentation however I am hoping for assistance on particular steps when configuring the DNS-over-HTTPS encryption. In this case, when I run the command `sudo certbot certonly --manual --preferred-challenges=dns` it asks for the url. In the documentation it states I need to register a domain name. I have purchased a domain name but when I enter the url it asks for a FQDN and not a url. What am I doing wrong?

**Comment by moofawsaw** [comment]
```
Please deploy a DNS TXT record under the name
_acme-challenge.adguard-home.webflow.io with the following value:
```
I have entered the domain name however there is an additional step not listed in the documentation (above). How do I deploy a DNS TXT record as is being asked in the terminal prompt?

**Comment by KizunaH** [comment]
I guess in namecheap or AWS DNS control panel then you have to wait till it propagated
See https://www.namecheap.com/support/knowledgebase/article.aspx/317/2237/how-do-i-add-txtspfdkimdmarc-records-for-my-domain

**Comment by ameshkov** [comment]
> How do I deploy a DNS TXT record as is being asked in the terminal prompt?

It depends on the domain name registrar you're using, it is done through their panel.

Personally, I prefer using Lego instead of Certbot: https://go-acme.github.io/lego/
They have an instruction for every DNS provider: https://go-acme.github.io/lego/dns/
