### ISSUE TITLE
Request: Advanced query log view

### ISSUE THREAD

**Issue by Dubz** [AdguardTeam/AdGuardHome#2223]
### Problem Description
Tracing domain issues/blocks is not as easy as it could be. Right now I have to check multiple places to try and find what might be being blocked, and maybe not even know what I'm looking for (I could find out if I was on site personally, but remote troubleshooting is a tad more cumbersome with AdGuard than PiHole is.

### Proposed Solution
Expand the query log to a more advanced view. Have a column for DNSSEC validation, and another for block reasons (ad list, malware list, custom blacklist, external DNS block, etc). Additionally, expand the search capabilities on this page (for example, to be able to find DNSSEC failures).

### Alternatives Considered
PiHole currently has this in their log, although not separated, but there nonetheless. I'd prefer to switch to AdGuard long term if possible, as it has some capabilities built in to it (such as DoH/DoT clients and servers) that PiHole does not.

**Comment by ameshkov** [comment]
Please try the beta version and check what we've done there, most of the requested features are there already.

If there's some filters/details missing, please file a feature request that lists what you'd like to have, but please make it as detailed as possible.

**Comment by Dubz** [comment]
@ameshkov I just deployed the beta version to see the difference, however the query log page looks the same as before. The only difference is, the select dropdown options are fixed in the beta version to not show a blank option. The rest of the query log, however, is the same.

Ideally, I think the simplest solution would probably be to add response codes as a searchable term. So if I search for SERVFAIL codes, I should be getting back domains that failed DNSSEC validation.

Additionally, with DNSSEC validation enabled, the green lock on the left should not show as such. There should be a broken lock that's red, causing more attention to be drawn to this domain. It may have been validated, but it didn't pass.

**Comment by ameshkov** [comment]
Filed a new FR, please upvote: https://github.com/AdguardTeam/AdGuardHome/issues/2226

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1606
