### ISSUE TITLE
Re-assess the current blocked services list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2224]
* Blocking QQ affects other services: https://github.com/AdguardTeam/AdGuardHome/pull/1775#issuecomment-714873641
* We may need to add other popular regional services: Wechat, Weibo, Viber

**Comment by KizunaH** [comment]
There's a little bit push-back for adding regional services once again. 
according to recent discussion explanations then @ameshkov newly suggested IM apps domains have no interaction or affect with other services or non cloud-based software updates, so it's fine to add if you don't see as this product(adguardhome) leads to introduce/advertise new services to people.

However do not add regional **social media platforms anyway (weibo similar combination of facebook and twitter but generally available in local language and focus on local contents, people) then it's not recommended.
Here's good solution for it and else (Solution to block worldwide services under particular categories #2230) and additional extension if someone has special purpose https://github.com/AdguardTeam/AdGuardHome/issues/1692 (Add custom blocked services)

At the same time, one more service/PR that doesn't suitable to the component - add Microsoft telemetry to blocked services https://github.com/AdguardTeam/AdGuardHome/pull/2283
It also seems required a new component dedicated for address it as for #2230 and see below about example image.

![Screenshot_20201109_144221](https://user-images.githubusercontent.com/63988538/98513577-a8f70100-229a-11eb-9b28-6ceaf9f3fcf9.png)

**Comment by ameshkov** [comment]
One more: https://github.com/AdguardTeam/AdGuardHome/issues/2625
