### ISSUE TITLE
docker v0.104.0 crashes on startup

### ISSUE THREAD

**Issue by thejinx0r** [AdguardTeam/AdGuardHome#2227]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

When I try to start the new docker container, I get this error:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Reverting back to tag v0.103.3 resolved the issue.

**Comment by ameshkov** [comment]
Hi, what's your host OS?

**Comment by thejinx0r** [comment]
The docker host os is debian 10.

**Comment by ameshkov** [comment]
64-bit?

**Comment by thejinx0r** [comment]
Yes. x64.

**Comment by ameshkov** [comment]
This is very very weird.

Is it amd64 or arm64?

I am trying an amd64 machine but cannot reproduce this.

From the error text it looks like you pulled an image for a wrong arch

What arch do you have? 368/amd64/arm

**Comment by thejinx0r** [comment]
Weird. I was using watchtower and it must have pulled an intermediate image. When I pulled again, it pulled something and now it works.

Lesson learned: don't use watchtower to update adguard.
