### ISSUE TITLE
Query Log: "Loading..." placeholder is never hidden even when there's nothing to load

### ISSUE THREAD

**Issue by PassWall-OpenWrt** [AdguardTeam/AdGuardHome#2229]
https://github.com/AdguardTeam/AdguardFilters/issues/66554#issue-731779472

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ *] I am running the latest version
- [* ] I checked the documentation and found no answer
- [* ] I checked to make sure that this issue has not already been filed

### Issue Details
Windows 7 SP1 x64 使用 AdGuardHome_windows_amd64 版本: 0.104.0
用 Google Chrome 86.0.4240.111浏览器在 web 管理页面(http://管理ip/#logs?response_status=&search=) 查询日志 界面 会出现网页无限下拉 死循环的bug 表现为鼠标滚轮一直滚下去到最后 会自动跳回旧的日志 一直反复

* **Version of AdGuard Home server:**
  0.104.0
* **Operating system and version:**
  Windows 7 SP1 x64

### Actual Behavior

</details>

**Comment by ameshkov** [comment]
谢谢，其实这是bug，我们快修理了。
