### ISSUE TITLE
CanAutoUpdate should not decide by  util.HaveAdminRights

### ISSUE THREAD

**Issue by ihipop** [AdguardTeam/AdGuardHome#2231]
https://github.com/AdguardTeam/AdGuardHome/blob/d1e55c31af13a7fd88516d1e498747ee2aa69209/home/control_update.go#L101-L114

if we run AdGuardHome by systemd like this

```
[Unit]
Description=Adguard Home
Requires=network.target
After=network.target

[Service]
Type=simple
####ExecStartPre=-/sbin/setcap cap_net_bind_service=+ep /config/ihipop/AdGuardHome/AdGuardHome
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/config/ihipop/AdGuardHome/AdGuardHome
Restart=always
RestartSec=2s
User=dnsmasq
PermissionsStartOnly=true
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
```

The `CAP_NET_BIND_SERVICE` capability is grant by systemd and not exists in filesystem
`AmbientCapabilities` doc https://www.freedesktop.org/software/systemd/man/systemd.exec.html#AmbientCapabilities=
It's safe to upgrade then

**Comment by ihipop** [comment]
#1193 #1944

**Comment by ihipop** [comment]
IMO,the best way is to have a `capget syscall` to see if we have `CAP_NET_BIND_SERVICE` capability

**Comment by ihipop** [comment]
Suggestions：
- deprecated `no-check-update` option
- add new `update-policy` option

New policy：
 - auto: 
auto update if possible (with a new version and execute file is located and writable  on file system  ,ignore the  Capabilities stuff )
 - manual: (default)
same as auto but will not update self until administrator click it on admin panel
 - disable: 
same as the old `no-check-update`, will not perform any update check so will no self-update

**Comment by EugeneOne1** [comment]
This should be fixed as of snapshot [641db73](https://github.com/AdguardTeam/AdGuardHome/commit/641db73a86a6d9d047f47c403bca70af320f23e9).  Could you please check if our solution fixes the issue for you?

**Comment by ihipop** [comment]
> This should be fixed as of snapshot [`641db73`](https://github.com/AdguardTeam/AdGuardHome/commit/641db73a86a6d9d047f47c403bca70af320f23e9). Could you please check if our solution fixes the issue for you?

I take a glance at the code ,Nice and clean fix than what I've suggested !!!
I will take a try and close my issue if it works fine

**Comment by ainar-g** [comment]
<p>@ihipop,&#xA0;hi, any news?&#x2003;Can we close the&#xA0;issue
for&#xA0;now?</p>

**Comment by ainar-g** [comment]
<p>I'll&#xA0;close this issue for now.&#x2003;Please feel free to reopen with
more details if you think it should be&#xA0;reopened.</p>
