### ISSUE TITLE
new dns-over-quic feature in v0.104, query log always show as "Plain DNS"

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/AdGuardHome#2233]
* **Version of AdGuard Home server:**
v0.104.0
* **How did you setup DNS configuration:**
quic://dns.adguard.com
enabled quic in encryption
* **Operating system and version:**
Ubuntu 20.04

### Expected Behavior
Use another AdGuard Home to make query to the server using dns-over-quic, in Query Log, suppose the request column should show "Type: A, DNS-over-QUIC"

### Actual Behavior
It is currently showing all as "Type: A, Plain DNS"

### Additional Information
It would be confusing if the query is from original DNS port 53 or from new dns-over-quic.

**Comment by ameshkov** [comment]
Plain DNS means that the request was received by AdGuard Home over plain DNS.

You can check what upstream was using in the DNS response details.
