### ISSUE TITLE
Mouseover DNS statistic bar is shifted

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardHome#2237]
Should that be so?

![2020-10-29 18-57-43](https://user-images.githubusercontent.com/6276915/97614305-10e75500-1a1a-11eb-8740-e7154f4a21df.gif)

AdGuard Home v0.104.0
Tested with Firefox 82.0.2 and Edge Chromium 86.0.622.56, both with same result
Checked with German and English overlay of AGH. Both the same result

Regards

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/a19523b2589afa34f8e6f831e36b80834630413e
