### ISSUE TITLE
Client proto is shown as "Plain DNS" when DoQ is in use

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2241]
## Steps to reproduce

1. Configure AdGuard Home to be a DoQ resolver
2. Use an app to make DoQ queries (for instance, use `dnslookup`)
3. Check the query log and find your request there

These are actually two issues that should be fixed at once.

1. There's no "client_proto" in the `/querylog` response: https://uploads.adguard.com/up04_AdGuard_Home_gyk81.png
2. The UI does not know how to handle `doq` when it's there

**Comment by ainar-g** [comment]
<p>@ArtemBaskal&#x2003;I've implemented the&#xA0;backend part
in df34ee5c.&#x2003;Can you please fix the&#xA0;frontend&#xA0;part?</p>
