### ISSUE TITLE
[Question] DNSCrypt's Anonymized DNS

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdGuardHome#2244]
I haven't seen much support for this protocol, I personally think it would be a good thing to add so users can use the 'anonymized DNS' for websites they don't want their IP address associated with but who also don't want the slow speeds of Tor. Is there any reason it shouldn't be supported?

Previous request: https://github.com/AdguardTeam/AdGuardHome/issues/1226

DNSCrypt Example: https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L678

Extra: https://github.com/DNSCrypt/dnscrypt-protocol/blob/master/ANONYMIZED-DNSCRYPT.txt

**Comment by ameshkov** [comment]
Well, it'd be better to upvote the original request.

So far, my opinion about it hasn't changed: https://github.com/AdguardTeam/AdGuardHome/issues/1226#issuecomment-576020416
