### ISSUE TITLE
Top clients area didn't show any client except 127.0.0.1

### ISSUE THREAD

**Issue by garypang13** [AdguardTeam/AdGuardHome#2245]
* **Version of AdGuard Home server:**
  v0.104.0

* **How did you setup DNS configuration:**
 The clients uses https://dns.supes.top/dns-query as it's primary DNS

* **Operating system and version:**
 Ubuntu 20.04.1 LTS

![image](https://user-images.githubusercontent.com/48883331/97785662-733e8200-1be1-11eb-8427-0c47ee94b098.png)

![image](https://user-images.githubusercontent.com/48883331/97785674-83eef800-1be1-11eb-9ce9-da13237a3041.png)

My nginx configuration

![image](https://user-images.githubusercontent.com/48883331/97785849-869e1d00-1be2-11eb-8c43-92a8cefd96f8.png)

**Comment by ameshkov** [comment]
This is just how your router works. It makes DNS queries on behalf of the real client devices, and that's why AdGuard Home only sees it, not the clients.

**Comment by ameshkov** [comment]
Ah, wait, my bad. You're talking about nginx as a reverse proxy?

You should make sure that the `X-Forwarded-For` header is set to the real client's IP address.
