### ISSUE TITLE
High ram usages after last update

### ISSUE THREAD

**Issue by shimuldn** [AdguardTeam/AdGuardHome#2246]
Before RAM use was a maximum was 550MB without SWAP not always almost full RAM usage 750-860MB with swap usages also. I am the only user on my ubuntu 20.04 server!

Is this a bug?

<img width="797" alt="Screenshot 2020-10-31 at 11 33 53 PM" src="https://user-images.githubusercontent.com/12117121/97788125-75521200-1bdc-11eb-8319-79e943a70986.png">

**Comment by ameshkov** [comment]
Most likely it's not. We tuned the memory optimization so that we were allocating more, but using less CPU time. Please note, that it will go down after some time when OS reclaims the unused memory.

**Comment by shimuldn** [comment]
> Most likely it's not. We tuned the memory optimization so that we were allocating more, but using less CPU time. Please note, that it will go down after some time when OS reclaims the unused memory.

Still using 650MB of ram. The Ubuntu server only has AGH installed. Before the recent update, the RAM usage was maximum 550MB on the same server.

**Comment by ameshkov** [comment]
Rebuild AGH with `GCPERCENT` set to 10 if you want to change to the old behavior.

Although, in this case, the overall CPU usage is considerably higher.

**Comment by shimuldn** [comment]
> Rebuild AGH with `GCPERCENT` set to 10 if you want to change to the old behavior: https://github.com/AdguardTeam/AdGuardHome/blob/master/internal/home/memory.go#L23
> 
> Although, in this case, the overall CPU usage is considerably higher.

Thank you.
