### ISSUE TITLE
x509: certificate signed by unknown authority - Same 911. But dont work.

### ISSUE THREAD

**Issue by dheeoo** [AdguardTeam/AdGuardHome#2247]
/opt/AdGuardHome/AdGuardHome
2020/10/31 19:53:55 [info] AdGuard Home, version v0.104.0-SNAPSHOT-9761f133, channel edge, arch linux mips
2020/10/31 19:53:56 [info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
2020/10/31 19:53:56 [info] Auth: initialized.  users:1  sessions:1
2020/10/31 19:53:56 [info] Initialize web module
2020/10/31 19:53:57 [info] AdGuard Home is available on the following addresses:
2020/10/31 19:53:57 [info] Go to http://127.0.0.1:81
2020/10/31 19:53:57 [info] Go to http://10.10.10.254:81
2020/10/31 19:53:57 [info] Go to http://45.8.20.191:81
2020/10/31 19:54:02 [info] Starting the DNS proxy server
2020/10/31 19:54:02 [info] Ratelimit is enabled and set to 20 rps
2020/10/31 19:54:02 [info] The server is configured to refuse ANY requests
2020/10/31 19:54:02 [info] DNS cache is enabled
2020/10/31 19:54:02 [info] MaxGoroutines is set to 50
2020/10/31 19:54:02 [info] Creating the UDP server socket
2020/10/31 19:54:02 [info] Listening to udp://0.0.0.0:5353
2020/10/31 19:54:02 [info] Creating a TCP server socket
2020/10/31 19:54:02 [info] Listening to tcp://0.0.0.0:5353
2020/10/31 19:54:02 [info] Entering the UDP listener loop on 0.0.0.0:5353
2020/10/31 19:54:02 [info] Entering the tcp listener loop on 0.0.0.0:5353

2020/10/31 19:54:05 [info] **SafeBrowsing: failed:** couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=IT0BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": _x509: certificate signed by unknown authority_
2020/10/31 19:54:06 [info] **SafeBrowsing: failed**: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=5HABAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": _x509: certificate signed by unknown authority_
2020/10/31 19:54:06 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=dcYBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": x509: certificate signed by unknown authority
2020/10/31 19:54:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=EvoBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": x509: certificate signed by unknown authority
2020/10/31 19:54:07 [info] SafeBrowsing: failed: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=eiEBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": x509: certificate signed by unknown authority

C2020/10/31 19:54:08 [info] Received signal 'interrupt'
2020/10/31 19:54:08 [info] Stopping AdGuard Home
2020/10/31 19:54:08 [info] Stopping HTTP server...
2020/10/31 19:54:08 [info] Stopped HTTP server
2020/10/31 19:54:08 [info] Stopping the DNS proxy server
2020/10/31 19:54:08 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2020/10/31 19:54:08 [info] Stopped the DNS proxy server
2020/10/31 19:54:08 [info] Stopped

Router:

Firmware
DD-WRT v3.0-r40559 std (08/06/19) 

Kernel
Linux 3.10.108-d8 #17379 Tue Aug 6 02:06:30 +04 2019 mips

Yesterday all works, today no...

Help

**Comment by ameshkov** [comment]
Looks like your firmware does not have the root CA that's used to sign `dns.adguard.com` certificate (Go Daddy root to be precise). Make sure, that your local CA store is up-to-date.

**Comment by dheeoo** [comment]
Today works again, automatically...

**Comment by dheeoo** [comment]
Tnx feedback
