### ISSUE TITLE
filters to trigger webhooks

### ISSUE THREAD

**Issue by balupton** [AdguardTeam/AdGuardHome#2249]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I'd like the ability to specify filters that trigger webhooks, the use case is the following:

1. when a certain blocklist is accessed by a certain client, a particular webhook is triggered

The goal is the following:

1. when a porn website is accessed by one of my devices, it triggers a zapier webhook that sends a message to my nofap community channel for social accountability

### Proposed Solution

Up to discretion of the aghome team

### Alternatives Considered

Already got it going for hosts file selection, but this only works on desktop computers, not mobile:

https://github.com/bevry/dotfiles/blob/dcf47d3162dec61f608a1e3449166f82e509b6a9/commands/select-hosts#L44-L56

**Comment by ameshkov** [comment]
This use case is just too specific. I am not against web-hooks in general, but this functionality needs to be planned very carefully.

Meanwhile, you can instead use the REST API and poll the query log periodically. It has all the data you need.

**Comment by balupton** [comment]
> This use case is just too specific. I am not against web-hooks in general, but this functionality needs to be planned very carefully.

For sure.

> Meanwhile, you can instead use the REST API and poll the query log periodically. It has all the data you need.

Perfect!

---

Thanks so much

**Comment by balupton** [comment]
Any link to the REST API docs?

**Comment by ameshkov** [comment]
Here it is: https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

**Comment by balupton** [comment]
So not rendered anywhere, go to render it via clone?

**Comment by ameshkov** [comment]
You'll need to use the `/querylog` method

**Comment by ameshkov** [comment]
> So not rendered anywhere, go to render it via clone?

Nope, clone & run yarn start
