### ISSUE TITLE
Upstream_dns_file is configured, bootstrap_dns is also invalid

### ISSUE THREAD

**Issue by WoChen5770** [AdguardTeam/AdGuardHome#2251]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
bootstrap_dns is no longer the value I set, it becomes “https://dns10.quad9.net:443/dns-query”
I will bootstrap_dns set a low-latency dns, quad9 has too high latency for me

**Comment by ameshkov** [comment]
> bootstrap_dns is no longer the value I set, it becomes “https://dns10.quad9.net:443/dns-query”

I can't reproduce this. bootstrap_dns is not changed when you set `upstream_dns_file`.

Could you please add a more detailed explanation of your problem?

**Comment by WoChen5770** [comment]
I set a global https://dns.google in Upstream_dns_file, this problem will not occur

**Comment by gistsy** [comment]
https://kb.adguard.com/en/general/dns-providers
