### ISSUE TITLE
Conflict with portainer

### ISSUE THREAD

**Issue by itsnotsaved** [AdguardTeam/AdGuardHome#2253]
I installed portainer and adguardhome on docker (linux) but after reboot system then agh container keep restarting again and again or get exited. next i have to stop portainer and restart agh then start portainer again to solve that problem. how to solve that?

adguardhome
`docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 8085:8085/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp -d adguard/adguardhome`
`docker update --restart unless-stopped container_id`

portainer https://www.portainer.io/installation/
`docker volume create portainer_data`
`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce`

**Comment by gistsy** [comment]
or you can suggest me alternative tool for use to update docker image/containers (for linux)
(the only purpose for use portainer but it doesn't perfect for that task)

**Comment by ameshkov** [comment]
I don't think this is directly relevant to AGH, and it's hard for me to suggest anything, I prefer using pure docker.

Marked as help wanted, maybe someone else case suggest something reasonable.

**Comment by BobWs** [comment]
I’m running portainer and agh also in Docker on a Synology nas but I don’t have any problems with it. They both start just fine. The only difference I can think of with your setup is that I’m running agh with macvlan. So agh gets its own ip instead of via the host or bridge mode. Maybe you could try that and see if it works.

**Comment by gistsy** [comment]
> I’m running portainer and agh also in Docker on a Synology nas but I don’t have any problems with it. They both start just fine. The only difference I can think of with your setup is that I’m running agh with macvlan. So agh gets its own ip instead of via the host or bridge mode. Maybe you could try that and see if it works.

i have many containers and no issue if portainer container doesn't start with system boot (or start portainer after AGH). That only affect to AGH container, no other containers so i dont think i should follow macvlan setup

i prefer if there any other simple tool for update docker images/containers
