### ISSUE TITLE
[Question] Auto load clients in Client Settings?

### ISSUE THREAD

**Issue by zilexa** [AdguardTeam/AdGuardHome#2255]
Not really an FR yet, I am just wondering why `Settings > Client Settings > Clients` shows an empty list, while the dashboard does show (Top) clients? Would be nice if you could just list those clients here, for further editing (for example, to give them a name easily). .

**Comment by ameshkov** [comment]
But they are there, scroll down to "Clients (runtime)"

**Comment by zilexa** [comment]
That is also empty (for a moment I thought this would be embarrassing). 

Screenshots showing clients on Dashboard but no clients in Client Settings:
![Screenshot from 2020-11-02 16-01-47](https://user-images.githubusercontent.com/3430004/97883198-d5ec6680-1d24-11eb-9c01-b1adb5f56b34.png)

![Screenshot from 2020-11-02 16-02-03](https://user-images.githubusercontent.com/3430004/97883209-da188400-1d24-11eb-91a7-800903fb9a17.png)

**Comment by ameshkov** [comment]
Hm, tbh I have no idea why they're not processed and added automatically. AGH should've at least parsed ARP table to get their hostnames.

You can check AGH logs to see why this happens.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Check the log, look for ARP and reverse DNS lookups there

**Comment by zilexa** [comment]
Thanks, I tried combing though the log, but I cannot find anything out of the ordinary. However I am also absolutely not an expert, not sure what I should look for. If you are willing to give it a try: https://pastebin.com/55jhHxU8 otherwise I understand this is a lot of work..

**Comment by zilexa** [comment]
Strangely, after restarting AGH (needed after I modified the config file for verbose logging), I now see this, still not the IP addresses I see in the Dashboard, but at least it is not blank:

![Screenshot from 2020-11-02 16-39-22](https://user-images.githubusercontent.com/3430004/97887363-17cbdb80-1d2a-11eb-9a7c-7d808621f017.png)

**Comment by ameshkov** [comment]
We only list clients we have information on there - either a hostname or whois data.

If there's no information save for IP address, it won't be listed there.

**Comment by zilexa** [comment]
Ok that makes sense. I will have to add the clients I need in that list, to my /etc/hosts file. Thanks!
