### ISSUE TITLE
为什么adgh有8080？？

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#2256]
root@debian: ./coredns
listen tcp :8080: bind: address already in use
root@debian: lsof -i:8080
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
AdGuardHo 352 root   36u  IPv4  21687      0t0  TCP 172.31.120.27:http-alt->228.static.tfn.net.tw:https (ESTABLISHED)

**Comment by ameshkov** [comment]
检查AdGuardHome.yaml，在这里找8080端口
