### ISSUE TITLE
DNS very slow after update to 0.104.0

### ISSUE THREAD

**Issue by pattyland** [AdguardTeam/AdGuardHome#2257]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  0.104.0
* **How did you setup DNS configuration:**
  *  DHCP via Router
* **If it's a router or IoT, please write device model:**
  *  FRITZ!Box
* **Operating system and version:**
  *  Home Assistant OS with Docker

### Expected Behavior

Fast DNS resolving like in 0.103

### Actual Behavior

Very slow resolving:
```
pattyland@air ~ % time nslookup hassio     
Server:		192.168.178.3
Address:	192.168.178.3#53

Non-authoritative answer:
Name:	hassio.local
Address: 192.168.178.3

nslookup hassio  0,00s user 0,01s system 0% cpu 19,128 total
pattyland@air ~ % time nslookup hass.io 
Server:		192.168.178.3
Address:	192.168.178.3#53

Non-authoritative answer:
Name:	hass.io
Address: 52.217.93.59

nslookup hass.io  0,00s user 0,01s system 0% cpu 10,243 total
```
The first request in an internal domain configured for dns rewrite in AG, the second is a standard external domain.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I'm experiencing this problems across all devices like Macbooks, iPhones and Fire TVs

**Comment by ameshkov** [comment]
I am not sure what's wrong here.

Anyway, to troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

In this log you can check how the query for `hassio` was processed and at what moment it was written back to the client.

**Comment by xylesoft** [comment]
I'm encountering precisely the same issue after updating to 0.104.0 yesterday, one insight i've discovered is when I restart AdGuardHome the response times return to normal, but after 10 minutes or more, it reverts back to being really slow again. 

I've discovered via the verbose logging that it starts to slow down when queries to `lb._dns-sd._udp.lan` (and similar) events are logged, which these requests appear repeatedly with errors. 

Now when I do a name lookup I get a slow response:
```
$ time nslookup stackoverflow.com
Server:		10.0.0.50
Address:	10.0.0.50#53

Non-authoritative answer:
Name:	stackoverflow.com
Address: 151.101.65.69
Name:	stackoverflow.com
Address: 151.101.1.69
Name:	stackoverflow.com
Address: 151.101.129.69
Name:	stackoverflow.com
Address: 151.101.193.69

nslookup stackoverflow.com  0.00s user 0.01s system 0% cpu 6.754 total
```

**Verbose Log from AdGuardHome:**
```
2020/11/04 09:39:13 100080#5658 [debug] SafeBrowsing: found in cache: db._dns-sd._udp.lan: not blocked
2020/11/04 09:39:13 100080#5658 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).checkSafeBrowsing(): SafeBrowsing lookup for db._dns-sd._udp.lan; Elapsed time: 0ms
2020/11/04 09:39:13 100080#5658 [debug] 10.0.0.50:53: sending request PTR db._dns-sd._udp.lan.
2020/11/04 09:39:13 100080#5591 [debug] 10.0.0.50:53: response: read udp 10.0.0.50:33551->10.0.0.50:53: i/o timeout
2020/11/04 09:39:13 100080#5591 [debug] github.com/AdguardTeam/dnsproxy/upstream.exchange(): upstream 10.0.0.50:53 failed to exchange ;lb._dns-sd._udp.lan.	IN	 PTR in 10000 milliseconds. Cause: read udp 10.0.0.50:33551->10.0.0.50:53: i/o timeout
2020/11/04 09:39:13 100080#5591 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 10000 ms
2020/11/04 09:39:13 100080#5591 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 7533
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;lb._dns-sd._udp.lan.	IN	 PTR

2020/11/04 09:39:13 100080#5591 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: read udp 10.0.0.50:33551->10.0.0.50:53: i/o timeout
2020/11/04 09:39:13 100080#5308 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 10.0.0.50:46228
2020/11/04 09:39:13 100080#5308 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 7533
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;lb._dns-sd._udp.lan.	IN	 PTR

2020/11/04 09:39:13 100080#5308 [debug] SafeBrowsing: found in cache: lb._dns-sd._udp.lan: not blocked
2020/11/04 09:39:13 100080#5308 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).checkSafeBrowsing(): SafeBrowsing lookup for lb._dns-sd._udp.lan; Elapsed time: 0ms
2020/11/04 09:39:13 100080#5308 [debug] 10.0.0.50:53: sending request PTR lb._dns-sd._udp.lan.
2020/11/04 09:39:13 100080#5634 [debug] 10.0.0.50:53: response: read udp 10.0.0.50:33130->10.0.0.50:53: i/o timeout
2020/11/04 09:39:13 100080#5634 [debug] github.com/AdguardTeam/dnsproxy/upstream.exchange(): upstream 10.0.0.50:53 failed to exchange ;b._dns-sd._udp.lan.	IN	 PTR in 10000 milliseconds. Cause: read udp 10.0.0.50:33130->10.0.0.50:53: i/o timeout
2020/11/04 09:39:13 100080#5634 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 10000 ms
2020/11/04 09:39:13 100080#5634 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 11573
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;b._dns-sd._udp.lan.	IN	 PTR

2020/11/04 09:39:13 100080#5634 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: read udp 10.0.0.50:33130->10.0.0.50:53: i/o timeout
2020/11/04 09:39:13 100080#5309 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 10.0.0.50:47670
2020/11/04 09:39:13 100080#5309 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 11573
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;b._dns-sd._udp.lan.	IN	 PTR

2020/11/04 09:39:13 100080#5309 [debug] SafeBrowsing: found in cache: b._dns-sd._udp.lan: not blocked
2020/11/04 09:39:13 100080#5309 [debug] github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).checkSafeBrowsing(): SafeBrowsing lookup for b._dns-sd._udp.lan; Elapsed time: 0ms
2020/11/04 09:39:13 100080#5309 [debug] 10.0.0.50:53: sending request PTR b._dns-sd._udp.lan.
```

**Comment by ameshkov** [comment]
@xylesoft @pattyland could you please try setting `max_goroutines` to a bigger number (300 for instance) in `AdGuardHome.yaml` and see if things change? In v0.104.0 we configured it to be 50 by default, and I guess this could slow down everything if there are too many queries that are timing out.

**Comment by xylesoft** [comment]
@ameshkov I've implemented 300 against the `max_goroutines` configuration and reconfigured my Upstream hosts to:
```
[/xylenet.lan/]10.0.0.50:53
tls://1.1.1.1
tls://1.0.0.1
```

Unfortuantly I'm still experiencing the slow down, even to the point when I try to save settings under "DNS Settings" I get an error during these slowed down periods.

**Verbose Log**
```
2020/11/04 12:59:02 114272#60929 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 5950
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sonarr.xylenet.lan.	IN	 A

2020/11/04 12:59:02 114272#60887 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: read udp 10.0.0.50:58517->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#60929 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: read udp 10.0.0.50:51311->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#61225 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 10.0.0.50:44484
2020/11/04 12:59:02 114272#61247 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 10.0.0.50:46557
2020/11/04 12:59:02 114272#61247 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 33293
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sonarr.xylenet.lan.	IN	 A

2020/11/04 12:59:02 114272#61225 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 5950
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sonarr.xylenet.lan.	IN	 A

2020/11/04 12:59:02 114272#61247 [debug] 10.0.0.50:53: sending request A sonarr.xylenet.lan.
2020/11/04 12:59:02 114272#61225 [debug] 10.0.0.50:53: sending request A sonarr.xylenet.lan.
2020/11/04 12:59:02 114272#60930 [debug] 10.0.0.50:53: response: read udp 10.0.0.50:34831->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#60930 [debug] github.com/AdguardTeam/dnsproxy/upstream.exchange(): upstream 10.0.0.50:53 failed to exchange ;sonarr.xylenet.lan.	IN	 AAAA in 10000 milliseconds. Cause: read udp 10.0.0.50:34831->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#60930 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 10000 ms
2020/11/04 12:59:02 114272#60930 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 56290
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sonarr.xylenet.lan.	IN	 AAAA

2020/11/04 12:59:02 114272#60930 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): error handling DNS (udp) request: talking to dnsUpstream failed, cause: read udp 10.0.0.50:34831->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#61248 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 10.0.0.50:34951
2020/11/04 12:59:02 114272#61248 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 23920
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;sonarr.xylenet.lan.	IN	 AAAA

2020/11/04 12:59:02 114272#61248 [debug] 10.0.0.50:53: sending request AAAA sonarr.xylenet.lan.
2020/11/04 12:59:02 114272#60903 [debug] 10.0.0.50:53: response: read udp 10.0.0.50:57080->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#60903 [debug] github.com/AdguardTeam/dnsproxy/upstream.exchange(): upstream 10.0.0.50:53 failed to exchange ;sonarr.xylenet.lan.	IN	 A in 10000 milliseconds. Cause: read udp 10.0.0.50:57080->10.0.0.50:53: i/o timeout
2020/11/04 12:59:02 114272#60903 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 10000 ms
```

**Comment by ameshkov** [comment]
Are you sure there's a DNS server on `10.0.0.50:53`? That's weird that it times out all the time.

**Comment by xylesoft** [comment]
10.0.0.50 is the machine which AdGuardHome resides on.

**Comment by xylesoft** [comment]
Possibly yes, I've now removed the configuration, but now I cannot resolve `*.xylenet.lan` hosts. I'm not DNS expert at all, so please excuse any of my ignorance here.

**Comment by ameshkov** [comment]
Well, the question is where exactly have you configured these `*.xylenet.lan` domains?

There should be a DNS server that is able to resolve them. It could be your router, or maybe AdGuard Home (if you're using DNS rewrites).

**Comment by xylesoft** [comment]
They are webservices on 10.0.0.50, so only nginx and 10.0.0.50's `/etc/hosts` is aware of them.  I'm not aware of DNS rewrites in AdGuardHome, so will look into those now thank you.

**Comment by ameshkov** [comment]
> 10.0.0.50's /etc/hosts is aware of them

Hm, AdGuard Home scans `/etc/hosts` and it should serve them as well. Check if you see these hosts in "Settings" -> "Clients" -> "Clients (runtime)" table

**Comment by ookangzheng** [comment]
I got too many UDP TIME_OUT, I change `max_goroutines` from `50` to `300`.
I solve my problem...

**Comment by ameshkov** [comment]
Good. This means the reason is indeed the new default for `max_goroutine` in v0.104.0 which is too small. https://github.com/AdguardTeam/AdGuardHome/commit/bc2091784011882348a70159da31ad578ef6e7b3 should resolve this.

**Comment by xylesoft** [comment]
> > 10.0.0.50's /etc/hosts is aware of them
> 
> Hm, AdGuard Home scans `/etc/hosts` and it should serve them as well. Check if you see these hosts in "Settings" -> "Clients" -> "Clients (runtime)" table

No, the subdomained hosts do not appear to be imported from etc/hosts into Clients table.

**Comment by ameshkov** [comment]
@xylesoft do you mind sharing the hosts file contents? At least with one host?

Also, take a look at AGH log, look for "AutoHosts" lines. Is there anything relevant?

**Comment by xylesoft** [comment]
@ameshkov here is the relevant part of my `/etc/hosts`:
```
10.0.0.50 xylenet
10.0.0.50 adguard.xylenet.lan
10.0.0.50 xylenet.lan
10.0.0.50 nodered.xylenet.lan
10.0.0.50 host1.xylenet.lan
10.0.0.50 host2.xylenet.lan
10.0.0.50 host3.xylenet.lan
```
I've `cat <log> | grep "AutoHosts"` on:
- `/var/logs/AdGuardHome.out`
- `/var/logs/AdGuardHome.out`
- `~/verbose-adguard.log`   (My configured verbose log)

**AdGuard Home Log**
```
2020/11/04 15:32:02 132402#15 [debug] Start AutoHosts module
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: loading hosts from file /etc/hosts
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 127.0.0.1 -> localhost
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> xylenet
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added reverse-address 10.0.0.50 -> xylenet
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> adguard.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> nodered.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> host1.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> host2.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> host3.xylenet.lan
```
Only `XyleNet` appears in the "Clients (Runtime)" table.

**Comment by xylesoft** [comment]
@ameshkov Thank you for your help.

**Comment by pattyland** [comment]
Has something been changed here again? It was never really that good, but in the last weeks a restart of AGH every few days was enough, in the last days I have to restart the Docker container almost every hour... If I don't do that, all my devices take a very very long time for DNS resolution after a short time...

**Comment by ameshkov** [comment]
@pattyland if you're on the stable version, then no, there're no changes. There're some relevant fixes in beta though, you could try it and see how it goes.

**Comment by pattyland** [comment]
@ameshkov I'm glad to hear that! I run AGH as an addon with Home Assistant, so I'm unsure how I could test the beta :/

**Comment by pattyland** [comment]
@ameshkov after updating to 105.2 this got a lot better but far from perfect. I need to restart the docker container every 2 hours now... The worst scenario is when I turn on a few devices on at the same time, like Fire TV and my laptop, AGH goes down right away. 
(I'm also missing the IPv6 Addresses in the set up guide, but I think this is another issue)￼

**Comment by ameshkov** [comment]
@pattyland just in case, could you please change `max_goroutines` to `0` and see what changes?

**Comment by pattyland** [comment]
@ameshkov Thanks for the fast reply! Changing this settings seems to help a lot, I monitored the log while using a fair amount of devices doing stuff, and the times in the query log are barely in three digits. That was different before. So I guess this setting is too low?

**Comment by ameshkov** [comment]
@pattyland 

Probably. The default value is for local servers with low load, it's simply not enough when there's any considerable load on the server. Maybe, we should do it differently, keep it `0` by default and let people set it to a smaller value if they run AGH on some low-end hardware.

**Comment by pattyland** [comment]
@ameshkov So my server is local on an older NUC. Thanks to IoT, there are about 40 devices in my WLAN that communicate a lot, especially when Multiroom music starts. The numbers in the graph are always per hour, correct? At a rough skim of the query log, I would say that 20 requests per second come up every now and then.

**Comment by ameshkov** [comment]
Low-end is something like MIPS router with 128MB RAM:)

**Comment by pattyland** [comment]
Ok no, my NUC has a few GB, but good to know that AGH could run on this things!
I'm still getting (fewer) slow resolutions... it's so random, I really can't find a pattern here

'''

Response details
DNS server
tls://1.0.0.1:853
Elapsed
5457 ms
Response
CNAME: nrdp-ixanycast.ftl.netflix.com. (ttl=86394)
CNAME: nrdp.prod.dradis.netflix.com. (ttl=294)
CNAME: nrdp.prod.eu-west-1.internal.dradis.netflix.com. (ttl=54)
CNAME: dualstack.apiproxy-nrdp-prod-nlb-3-a71b4c004683cf09.elb.eu-west-1.amazonaws.com. (ttl=54)
A: 54.155.136.132 (ttl=54)
A: 54.77.110.160 (ttl=54)
A: 54.220.170.166 (ttl=54)
Response code
NOERROR
'''

**Comment by ameshkov** [comment]
Just in case, try using `https://1.0.0.1/dns-query` instead of DOT and see if anything changes.

**Comment by pattyland** [comment]
So as [Cloudflare docs](https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure) said I should use `https://cloudflare-dns.com/dns-query`I tried that, and in the last minutes it was pretty good. But I said this yesterday too, so I guess I have to test longer :D 

Thanks for all your help and advices!

**Comment by pattyland** [comment]
@ameshkov Wow, stopping using DOT helped a lot! This are they're
