### ISSUE TITLE
Upstream server stopped accepting ports in 104

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#2258]
my upstream server was a private server running on a custom port

127.0.53.1:5353

This no longer is accepted in 104

The docker image refuses to work with it as well.. 

Documentation still seems to say it exists.. 

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains

**Comment by ameshkov** [comment]
I am not able to reproduce this.

Here's how I tested:

1. Set my upstreams to this:
```
94.140.14.140:5353
[/example.org/]94.140.14.14:5353
```
2. Tried `nslookup example.org` and `nslookup example.com`
3. As expected, the first one went to `94.140.14.14:5353` and the second one went to `.140:5353`

**Comment by bcookatpcsd** [comment]
Thank you for writing back.. in my gui, I get an error saying that I can not save.. I do not have the [/example.org/], I literally just have the one and only entry of 

127.0.53.1:5353 

listed.

My upstream is tls://1.1.1.1

Stopping the process and editing the yaml does get the entry listed.. but Adguard will not forward traffic there. 

fwiw, the :5353 is a coredns instance, which works as defined.. 

(here to help if you need me.. - thank you again.)

**Comment by ameshkov** [comment]
What does "Test upstream" show?

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
