### ISSUE TITLE
Query log sort condition doesn't remain after refresh

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#2259]
#### Steps to reproduce

1. Go to query log and select sort condition: processed
`http://ip-adddress:port/#logs?response_status=processed&search=`

2. Refresh browser tab then query log display log as 'all queries' mode but UI sort selection and address bar URL remain as it

v0.104.0-beta3-SNAPSHOT-6b64bfac

**Comment by KizunaH** [comment]
Consider to address this feature request https://github.com/AdguardTeam/AdGuardHome/issues/845

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
