### ISSUE TITLE
"Log_LocalTime=True" has no effect

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#2264]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] checked to make sure that this issue has not already been filed

### Issue Details

Setting "log_localtime=true" in AdGuard.yaml does not result in AdGuard Home using local time based on time zone set in Raspberry Pi 2 settings.

AdGuard Home (version 0.104)
Raspberry Pi 2 (fully updated)
AdGuard Home is set as local DNS
AdGuard Home local DNS server uses self-signed HTTPS certificate and DNS-over-HTTPS encryption over port 443

### Expected Behavior
AdGuard Home should switch to using local time based on time zone set in Raspberry Pi 2 settings if AdGuardHome.yaml specifies "log_localtime=true".

### Actual Behavior
AdGuard Home uses UTC regardless of time zone settings in Raspberry Pi 2 and regardless of settings set in AdGuardHome.yaml.

**Comment by ameshkov** [comment]
I guess there's some confusion.

I suppose you're expecting time zone to be applied to the Query Log.

But this setting changes what time zone is used by AGH when it writes the regular program log (syslog by default).

**Comment by EntropySmoke** [comment]
I think you were correct in that I assumed Query Log is related to Log_LocalTime=True.
