### ISSUE TITLE
Incorrect username and password documentation

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#2265]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] checked to make sure that this issue has not already been filed

### Issue Details

**It is possible that the issue described below is due to AdGuard Home local DNS server using self-signed HTTPS certificate and DNS-over-HTTPS encryption over port 443**

AdGuard Home documentation for AdGuardHome.yaml username and password strings is misleading. You cannot simply change your password for AdGuard Home Web Portal in AdGuardHome.yaml and expect the password string in AdGuardHome.yaml to be the one you can use for AdGuard Home Web Portal because AdGuard Home encrypts passwords with BCrypt. To change your AdGuard Home Web Portal login password via AdGuardHome.yaml, you must first encrypt the password with BCrypt. AdGuardHome.yaml must specify the encrypted version of your AdGuard Home Web Portal login password. Free BCrypt converters can be found on the web.

AdGuard Home (version 0.104)
Raspberry Pi 2 (fully updated)
AdGuard Home is set as local DNS
**AdGuard Home local DNS server uses self-signed HTTPS certificate and DNS-over-HTTPS encryption over port 443**

### Expected Behavior
Password shown in AdGuardHome.yaml is not encrypted.

### Actual Behavior
Password shown in AdGuardHome.yaml is encrypted with BCrypt.

**Comment by ameshkov** [comment]
Thank you!

Updated Wiki article, it now mentions that the password is stored as a BCrypt-encoded hash.

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration
