### ISSUE TITLE
 [info] error handling UDP packet: dns: buffer size too small

### ISSUE THREAD

**Issue by pauliemnz** [AdguardTeam/AdGuardHome#2268]
Anybody else seeing these errors on their Adguard DNS server?

Tried installing on two different PC's both running Windows 10 PRO as the operating system of the DNS server and getting the same info messages

2020/11/02 06:51:36 [info] error handling UDP packet: dns: buffer size too small

2020/11/02 06:51:39 [info] error handling UDP packet: dns: buffer size too small

2020/11/02 07:06:31 [info] error handling UDP packet: dns: buffer size too small

2020/11/02 07:06:34 [info] error handling UDP packet: dns: buffer size too small

2020/11/02 07:17:54 [info] error handling UDP packet: dns: buffer size too small

2020/11/02 07:17:57 [info] error handling UDP packet: dns: buffer size too small

**Comment by ameshkov** [comment]
This just means something sends non-DNS packets to AdGuard Home.

I could say more if you could take a pcap and see what exactly is there.
