### ISSUE TITLE
Not every hostname from /etc/hosts can be resolved by AGH

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2269]
@ameshkov here is the relevant part of my `/etc/hosts`:
```
10.0.0.50 xylenet
10.0.0.50 adguard.xylenet.lan
10.0.0.50 xylenet.lan
10.0.0.50 nodered.xylenet.lan
10.0.0.50 host1.xylenet.lan
10.0.0.50 host2.xylenet.lan
10.0.0.50 host3.xylenet.lan
```

**AdGuard Home Log**
```
2020/11/04 15:32:02 132402#15 [debug] Start AutoHosts module
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: loading hosts from file /etc/hosts
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 127.0.0.1 -> localhost
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added reverse-address 127.0.0.1 -> localhost
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> xylenet
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added reverse-address 10.0.0.50 -> xylenet
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> adguard.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> nodered.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> host1.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> host2.xylenet.lan
2020/11/04 15:32:02 132402#69 [debug] AutoHosts: added 10.0.0.50 -> host3.xylenet.lan
```
Only `XyleNet` appears in the "Clients (Runtime)" table.

_Originally posted by @xylesoft in https://github.com/AdguardTeam/AdGuardHome/issues/2257#issuecomment-722301976_

**Comment by ameshkov** [comment]
@ainar-g check this out, `reverse-address` for some reason is only added for TLD only.

**Comment by ainar-g** [comment]
<p>@xylesoft&#x2003;Hello, and&#xA0;thank you for&#xA0;your report!&#x2003;Can
you please update to&#xA0;at&#xA0;least 298f74b and&#xA0;confirm, that&#xA0;all
hosts from&#xA0;<code>/etc/hosts</code> are now accounted&#xA0;for?</p>

**Comment by ainar-g** [comment]
<p>The&#xA0;fix seems to&#xA0;work in&#xA0;our internal tests.&#x2003;@xylesoft,
please reopen if&#xA0;the&#xA0;development version or&#xA0;the&#xA0;upcoming
patch release doesn't fix the&#xA0;issue for&#xA0;you.</p>
