### ISSUE TITLE
Domain not filtered even if in blacklist

### ISSUE THREAD

**Issue by Havock94** [AdguardTeam/AdGuardHome#2274]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.104.0
* **How did you setup DNS configuration:**
  * AdGuard is running as DHCP server
* **Operating system and version:**
  * Synology DS918+

### Expected Behavior
I expect the following rule to block the domain
`||meowpushnot.com^`

### Actual Behavior
The domain https://meowpushnot.com is not blocked, and ads are still shown on every page

### Screenshots

<details><summary>Screenshot:</summary>

Domain gets correctly filtered when it **doesn't** contain protocol
![image](https://user-images.githubusercontent.com/7635248/98291965-3b9e5400-1fac-11eb-842c-bbe37938cccb.png)

Domain not filtered when includes protocol
![image](https://user-images.githubusercontent.com/7635248/98291985-4527bc00-1fac-11eb-9f32-683bdc9a99bc.png)

</details>

**Comment by ameshkov** [comment]
1. What device do you use?
2. How did you configure your device to use AdGuard Home?
3. What browser do you use to open that website?
4. Does that browser really use AdGuard Home's DNS server?
5. Could it be that you're using some VPN at the same time?
6. Could it be that the browser operates in some kind of a "compression" mode and circumvents using the system DNS?

**Comment by Havock94** [comment]
> 1. What device do you use?
AdGuard Home is installed on a Docker container on a Synology DS918+, I tested connections on Android and Windows
> 2. How did you configure your device to use AdGuard Home?
AdGuard Home is the DHCP server and it's correctly set as DNS IP on the various devices
> 3. What browser do you use to open that website?
I tried Chrome on Android and Windows, and Edge and Firefox on Windows
> 4. Does that browser really use AdGuard Home's DNS server?
I can see the AdGuard Home IP as the DNS IP in the network options on both Android and PC, how do I make sure the browser is using the same DNS? 
> 5. Could it be that you're using some VPN at the same time?
No VPN are present on the devices
> 6. Could it be that the browser operates in some kind of a "compression" mode and circumvents using the system DNS?
Not really, I also tried on incognito mode so I think it's not circumventing the DNS

**Comment by ameshkov** [comment]
> I can see the AdGuard Home IP as the DNS IP in the network options on both Android and PC, how do I make sure the browser is using the same DNS?

Try opening any website (example.org, for instance) and check the query log in AdGuard Home, do you see the DNS query for that website's domain?

**Comment by Havock94** [comment]
I tried what you suggest, and didn't notice any entry for the url example.org
So I double checked the network config and noticed that Android automatically adds the 8.8.8.8 as 2nd DNS, and this might bypass AdGuard Home. The only way to prevent this is to set it manually, but this makes the DHCP useless. Forcing both 1st and 2nd DNS to AdGuard IP works flawlessly.
I will check if the same happens on Windows.
Since all the traffic gets through AdGuard DHCP, is it possible to force AdGuard as the only DNS? 


![Screenshot_20201105-221727~2](https://user-images.githubusercontent.com/7635248/98297540-d733c280-1fb4-11eb-9458-0bb8ecfbd8bb.jpg)

**Comment by ameshkov** [comment]
Hm, interesting.

Just in case, try changing the blocking mode in AdGuard Home, set it to "null IP".

**Comment by Havock94** [comment]
Just a quick update, I've set the blocking mode to Null IP, but it still doesn't work in case the device automatically picks up a secondary DNS which is not the AGH IP.
For now, I have to manually set both DNS to match AGH IP, or use a VPN that allows me to push the DNS IP to the device.

Would it be possible to force both DNS to the AGH IP in case AdGuard also acts as a DHCP?

**Comment by ameshkov** [comment]
Yeah, I guess we should be doing that by default.

**Comment by ameshkov** [comment]
Actually, there's already a feature request for that: https://github.com/AdguardTeam/AdGuardHome/issues/1708

I've re-assigned it to v0.105.
