### ISSUE TITLE
Simplify CI/CD scripts

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2276]
<p>Our&#xA0;packaging is actually relatively simple.&#x2003;We <em>probably</em>
don't need to&#xA0;build the&#xA0;project in&#xA0;a&#xA0;docker
environment.&#x2003;We <em>probably</em> don't need <code>goreleaser</code>
and&#xA0;can just use <code>snapcraft</code> as-is.&#x2003;A&#xA0;lot
of&#xA0;these things can be done in&#xA0;a&#xA0;simple <i>Shell</i>
script, making those actions run faster, consume fewer resources, and&#xA0;just
be more understandable.&#x2003;The&#xA0;<code>Makefile</code> also&#xA0;requires
some love: actions for&#xA0;developers and&#xA0;actions for&#xA0;CI/CD scripts
should be clearly&#xA0;separated.</p>

**Comment by ameshkov** [comment]
Agreed. `goreleaser` is undoubtedly a very nice tool, but I'd prefer us to have more control over how things are being built.

**Comment by ainar-g** [comment]
Most of the job here is done as of 933ca2af.  The rest of the bugfixes and improvements will probably be done as separate issues.
