### ISSUE TITLE
Error: control/install/get_addresses | 404 page not found | 404

### ISSUE THREAD

**Issue by 3323** [AdguardTeam/AdGuardHome#2278]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
This URL only works when the initial setup is in progress (i.e. there's no AdGuardHome.yaml)
