### ISSUE TITLE
Cannot start AdGuard Home Service

### ISSUE THREAD

**Issue by dennyamarojr** [AdguardTeam/AdGuardHome#2279]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
 AdGuard Home v0.104.0 
* **How did you setup DNS configuration:**
Upstream DNS servers
https://doh.opendns.com/dns-query
https://dns.cloudflare.com/dns-query
Bootstrap DNS servers
208.67.222.222
208.67.220.220
2620:119:35::35
2620:119:53::53
1.1.1.1
1.0.0.1
2606:4700:4700::1111
2606:4700:4700::1001
The other options, I let in the default configuration.
 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
 Windows 10 Pro 1703, 64-bit

### Expected Behavior
I expect to AdGuard Home services works, but something is preventing this to happen, I try to find in the issues section available here and didn't any issue opened or closed about the issue I got.

### Actual Behavior
I follow the installation and configuration steps available in the documentation and in the CMD works perfectly, but when I go to the services the Adguard Home Service is not running, is just there and when I try to run manually appear Error 1067, which I search for solutions and didn't work too, because it shows another issue. :( 

### Screenshots
The following screenshots is when I install and try to start the service in CMD

![AdGuard Home Error 001](https://user-images.githubusercontent.com/36896116/98445197-2409bd00-20cb-11eb-82a4-584f502d5fe5.JPG)
![AdGuard Home Error 002](https://user-images.githubusercontent.com/36896116/98445200-253aea00-20cb-11eb-92a0-17c45e436be8.JPG)
The next picture, is when I try to run the service manually.

![AdGuard Home Error 003](https://user-images.githubusercontent.com/36896116/98445218-4b608a00-20cb-11eb-8770-eaabbd76b3c1.JPG)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by SuXiChao1101** [comment]
I have also encountered the same problem, it seems that after turning off Windows logging, ADGuardHome cannot run. Opening ADGuardHome Service in Windows service will prompt "error 1067". I am also thinking, can ADGuardHome run independently without Windows logs or similar environments?

The script for closing Windows logs is roughly as follows:

`
set "key=HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\EventLog-System"
for /f "delims=" %%A in ('reg query %key%') do (
      echo "%%A"
      reg add "%%A" /v "Enabled" /t REG_DWORD /d 0 /f
      reg add "%%A" /v "EnableProperty" /t REG_DWORD /d 0 /f
)
`
