### ISSUE TITLE
Make maximum upstream querying time configurable

### ISSUE THREAD

**Issue by SkyYkb** [AdguardTeam/AdGuardHome#2280]
### Problem Description
If multiple encrypted DNS added as upstream servers, it's sometimes slow when querying all of specified servers. So sometimes clients resolving hosts with AdGuard Home will throw a timeout to user.

### Proposed Solution
Add an option to limit maximum upstream querying time, if time exceeded, just response the record already received to the client.

By the way, are there any public DoQ (DNS over QUIC) servers available now? Seems like this would improve the time of querying upstreams.
Thanks.

**Comment by ameshkov** [comment]
So you'd like the default timeout to be configurable?

> By the way, are there any public DoQ (DNS over QUIC) servers available now? Seems like this would improve the time of querying upstreams.

For now, the only one is AdGuard DNS.

**Comment by SkyYkb** [comment]
> So you'd like the default timeout to be configurable?

Yeah I’d love to. 
So what is the timeout by default?
Thanks for your reply...

**Comment by ameshkov** [comment]
As I recall, by default it is 10 seconds

**Comment by PussAzuki** [comment]
What? I think 2 seconds is the standard timeout and 6 seconds is the maximum timeout, just like nslookup did on Windows. 

I suggest that we also make some performance optimizations on top of this (especially for embedded devices such as routers), such as limiting the maximum CPU occupancy ratio so that the device does not fill up with CPU and cause serious query timeouts.   <--- This is the serious problem that I have encountered today.

**Comment by QingKongBaiYu** [comment]
yeah, it's terrible to wait for 10 secs for a dns query if one of the upstream servers dead.

**Comment by EugeneOne1** [comment]
@SkyYkb, hello again.  Latest builds from `edge` and `beta` channels are implementing the new `upstream_timeout` setting.  The reference already available in the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).  Could you please check if the feature works for you?

**Comment by EugeneOne1** [comment]
Unfortunately, the `reload` command for _AdGuard Home_ running as service doesn't actually reloads the configuration file.  This is a known issue, so you should use `restart` command instead.

If the above wouldn't work, could you please try other upstream modes?  Thanks.

**Comment by QingKongBaiYu** [comment]
> 
> 
> @SkyYkb, hello again. Latest builds from `edge` and `beta` channels are implementing the new `upstream_timeout` setting. The reference already available in the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file). Could you please check if the feature works for you?

For me, adguardhome return no response if I use `Fastest IP address`, so it's Hard to judge whether the setting works.
I have turned to `parallel requests` a few months ago since some domains are inaccessible without proxy in my country.

**Comment by SkyYkb** [comment]
@EugeneOne1 Works fine for me now. Thanks sincerely.
---
@QingKongBaiYu I won't get no response with this configuration... I guess that no server could be reached in the time you limited, so AGH wouldn't return a result. Maybe try a longer limit?

**Comment by EugeneOne1** [comment]
@SkyYkb, glad to hear that.  Thanks for testing.  We'll close the issue for now.
