### ISSUE TITLE
lb._dns-sd._udp.0.1.168.192.in-addr.arpa

### ISSUE THREAD

**Issue by Zendio** [AdguardTeam/AdGuardHome#2286]
### Issue Details

Since the last update I'm seeing a lot of requests (from my Apple devices) to lb._dns-sd._udp.0.1.168.192.in-addr.arpa and a few similar addresses. Googling "lb._dns-sd._udp.0.1.168.192.in-addr.arpa" brings up posts from PiHole saying I shouldn't be seeing this. It seems to be some sort of loop

* **Version of AdGuard Home server:**
  * 0.104.0
* **How did you setup DNS configuration:**
  * LAN DNS set to Adguard Home. 
  * Adguard Home upstream DNS set to router IP
  * Router uses ISP DNS
  * DHCP active on router, not on Adguard
* **If it's a router or IoT, please write device model:**
  * RPI3B
* **Operating system and version:**
  * Home Assistant (HassOS, which I thought was Alpine Linux) 

### Expected Behavior
I shouldn't be seeing these addresses.

### Actual Behavior
Addresses popping up in the stats and query logs.

### Screenshots

<details><summary>Screenshot:</summary>

![CleanShot 2020-11-09 at 10 04 13](https://user-images.githubusercontent.com/5435734/98521036-36bef600-2273-11eb-9e1d-eb0d32c51f27.png)

</details>

### Additional Information
Didn't see these addresses before upgrading to 104.0

**Comment by ameshkov** [comment]
Rebooting Apple device often helps with this. This issue is not on AG Home side.
