### ISSUE TITLE
Why are these considered adult sites?

### ISSUE THREAD

**Issue by balupton** [AdguardTeam/AdGuardHome#2289]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.0
* **How did you setup DNS configuration:**
  * router
* **If it's a router or IoT, please write device model:**
  * eero
* **Operating system and version:**
  * n/a

### Expected and Actual Behavior

Why are these blocked as adult sites, isn't adult sites meant to be for blocking porn?

- l.gm.mob.com
- cdn.geni.us

If their blocking is intentional, is there more fine grained filters for what is to be blocked? Like what [nextdns](https://balupton.com/nextdns) offers?

### Screenshots

![0C580F7B-665A-4711-BDCD-ECD447A04122](https://user-images.githubusercontent.com/61148/98674246-a5ec3580-23ac-11eb-971c-6c8e595fe7d9.png)
![26655A92-3872-4F82-9D66-7DFC199B02E8](https://user-images.githubusercontent.com/61148/98674263-aab0e980-23ac-11eb-872f-e01141a14b39.png)

**Comment by ameshkov** [comment]
These are false positives indeed, it will soon be fixed.
