### ISSUE TITLE
"Disallow/Block All, Except Whitelisted Domains" Rule/Filter

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#2291]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
For many mobile devices, VPN software Kill Switches do not work correctly. I'd like to disallow/block all clients from connecting to any and all domains, except for the ones I specify/whitelist. That way I can use AdGuard Home as a secondary security redundancy device (DNS/domain-based Kill-Switch) and allow connections only do domains used for anchoring/bootstrapping/enrolling to VPN services. 

### Proposed Solution
Create a "Disallow/Block All, Except Whitelisted Domains" Rule/Filter for AdGuard Home local DNS server.

**Comment by ameshkov** [comment]
This is rather easy to achieve using custom filtering rules.

Add a rule like this to block everything:
`||*.*`

And then unblock domains you need by adding exception rules:
`@@||example.org^`

**Comment by EntropySmoke** [comment]
Thank you! That worked almost 100% of the time, but /^[a-z]{7,15}$/ had to be added to block Smart TV domains. I also had to add ||net^&important to block one strange domain that was logged simply as "net" , but description showed an actual domain address. I didn't record it properly.
