### ISSUE TITLE
DHCP settings and v2ray servers problem

### ISSUE THREAD

**Issue by mikeingz** [AdguardTeam/AdGuardHome#2292]
Hi
I have a simple setup : Adguard Home is installed on a RPI4, connected to a router. On my PC I use Clash (a proxy client) to access v2Ray servers (socks5 proxy).
Everything works fine, but as soon as I setup the DHCP on adguard (instead of the router), all my v2ray servers are timeout. So I can't use this proxy anymore (proxy address: 127.0.0.1 , port :7890 ) 

![image](https://user-images.githubusercontent.com/2438157/98763533-28104480-2415-11eb-9403-76dc8b524e26.png)

Any idea how to solve that? Thanks

**Comment by devinslick** [comment]
@mikeingz , is your PC getting an IP issued from AGH?
If so, can you do an nslookup to resolve the v2ray servers from your PC?
