### ISSUE TITLE
Error: control/dhcp/status | 404 page not found | 404

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#2295]
Не работает DHCP сервер хотя на прошлых версиях 0.103.3 все работало..

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.1
* **Operating system and version:**
  * Windows 10 (2004), Windows Server 2012

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/98824597-8c96c800-2444-11eb-8690-0dbc4fda1fdb.png)

</details>

**Comment by EntropySmoke** [comment]
Same problem here, only began happening starting with version 0.104.1. How do I downgrade back to 0.104?

**Comment by ameshkov** [comment]
Argh, it seems a hotfix may be incoming soon.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by ameshkov** [comment]
Are you both on Windows?

**Comment by Eyeborgs** [comment]
> Argh, it seems a hotfix may be incoming soon.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.


[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/5525084/log.txt) (I changed it a bit removed my DNS hosts and some IP addresses)

**Comment by ameshkov** [comment]
@Eyeborgs это нормально, что DHCP недоступен на Windows, он там никогда и не работал. А вот ошибки - лишние, мы это поправим

**Comment by Eyeborgs** [comment]
@ameshkov понял

**Comment by Eyeborgs** [comment]
@ameshkov я еще заметил что нет кнопки для проверки обновления как это было раньше
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/98837839-814b9880-2454-11eb-89dd-0511a7515371.png)
</details>

**Comment by ameshkov** [comment]
@Eyeborgs что-то не могу повторить. Вообще честно говоря не понимаю как этого на винде достичь. Этой кнопки нет только если AGH установлен из докера или снапстора, либо если явно запущен с параметром --no-check-update

**Comment by Eyeborgs** [comment]
Да, точно стоит --no-check-update, просто я думал чтоб он автоматически не проверял а принудительно можно было бы проверить - по хорошему было бы хорошо так сделать

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/98846280-e8bb1580-245f-11eb-82cd-9036d0fd86b2.png)
</details>

**Comment by EntropySmoke** [comment]
> 
> 
> Are you both on Windows?

I am using Windows 10, but AdGuard Home is running on Raspberry Pi 2. H Any ETA on the fix?

**Comment by ameshkov** [comment]
> but AdGuard Home is running on Raspberry Pi 2. H Any ETA on the fix?

What's important is what OS is AGH running.

Please explain how this error looks like in your case.
The log could also be useful

**Comment by WildByDesign** [comment]
Mine is running on OpenWrt, 0.104.1 AGH, but my DHCP page is ok. All of the errors for me are occurring on the Encryption Settings page.

 Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400

I will try to get more details and logs later when I have more access to it.

**Comment by ameshkov** [comment]
> Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400

Well, that's kinda okay. Are you trying to actually enable it or is this error shown right away when you open that page?

**Comment by WildByDesign** [comment]
> > Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400
> 
> Well, that's kinda okay. Are you trying to actually enable it or is this error shown right away when you open that page?

This is shown anytime I view the page. I haven’t enabled it. I apologize for not getting logs yet. I will try later and potentially open another issue in case this is a separate issue.

**Comment by ainar-g** [comment]
<p>Можете&#xA0;обновиться до&#xA0;последнего снепшота из&#xA0;<i>edge</i>-канала
и&#xA0;посмотреть, есть&#xA0;ли теперь&#xA0;ошибки?</p>

**Comment by Eyeborgs** [comment]
@ainar-g Ошибки больше нет на странице DHCP (просто осталось надпись что ОС не поддерживает DHCP сервер)

Я конечно раньше не смотрел но появилась другая странная ошибка в терминале когда пролистываешь журнал..

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/99296250-81ce9f80-2857-11eb-84ae-ff4cf71a8277.png)


</details>

**Comment by ainar-g** [comment]
<p>Эти&#xA0;ошибки странные, но&#xA0;к&#xA0;данной теме, вероятнее всего,
не&#xA0;относятся.&#x2003;Если&#xA0;они вас беспокоят, давайте заведём отдельную
тему, а&#xA0;эту тему про ошибки на&#xA0;странице настроек <i>DHCP</i> мы
пока&#xA0;закроем.</p>
