### ISSUE TITLE
Mobile Wifi Connection Issue when Macbook Closed

### ISSUE THREAD

**Issue by moofawsaw** [AdguardTeam/AdGuardHome#2296]
After setting my Hitron router's DNS to match the server address provided by Adguard in the Setup Guide I noticed that if I close my Macbook [OSx Catalina 10.15.7], after about 10-15 minutes the Wifi on my mobile device [Xiaomi Pocophone F1 (MIUI 12)] loses signal. As soon as I open my Macbook however, the signal comes back and the internet is connect. 

I tested on another mobile device [LG Stylo 3] and there was no connectivity issue when I closed my Mac. 

What would be causing a mobile device to lose signal when my Macbook is closed? Note that this is the same Macbook where I initially configured Adguard Home.

**Comment by ameshkov** [comment]
Well, the question is why your other device does not lose connectivity. DNS server is crucial for the internet connection so once it goes it's expected for the internet to be unavailable.

I guess Android devices may fallback to Google DNS.

**Comment by moofawsaw** [comment]
If I understand correctly, closing my Macbook disconnects Adguard Home because the internet connection is lost in sleep mode and since AGH was installed on the Macbook it needs to always remain powered on in order to communicate with the router?

**Comment by ameshkov** [comment]
That's right
