### ISSUE TITLE
AdGuardHome not blocking ads

### ISSUE THREAD

**Issue by dennyamarojr** [AdguardTeam/AdGuardHome#2298]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details
Recently I got some problems because AdGuardHome services was not running, so I make a clean installation of Windows 10 and now I'm having the issue that AdGuard is not blocking all the ads, I try to 

* **Version of AdGuard Home server:**
 AdGuard Home v0.104.1 
* **How did you setup DNS configuration:**
Upstream DNS servers
tls://1.1.1.1
https://doh.opendns.com/dns-query
https://security.cloudflare-dns.com/dns-query
https://dns.cloudflare.com/dns-query
Bootstrap DNS servers
208.67.222.222
208.67.220.220
1.1.1.2
1.0.0.2
2606:4700:4700::1112
2606:4700:4700::1002
1.1.1.1
1.0.0.1
2606:4700:4700::1111
2606:4700:4700::1001 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
Windows 10 Version 20H2 (OS Build 19042.630), 64-bit 

### Expected Behavior
Expected to run AdGuard Home to block ads to avoid install extensions in browser, so I can setup the DNS in the router (in the future) and block ads and get more security for all the devices connected in the network.

### Actual Behavior
I was trying to run AdGuardHome and everything works fine, but I got a problem with AdGuard not blocking ads

### Screenshots
![001](https://user-images.githubusercontent.com/36896116/98863186-db306c00-241c-11eb-84bd-9b3bca83b213.JPG)
![002](https://user-images.githubusercontent.com/36896116/98863187-dc619900-241c-11eb-9381-30b1769690ca.JPG)

<details><summary>Screenshot:</summary>

</details>

### Additional Information
In the screenshot I try to follow the guide in the FAQ where we run the command nslookup example.org to see the address is matching with the dns address of AdGuardHome and for me the server are displaying as Unknown. May I need help in the initial configuration, to see if I'm doing something wrong. In the initial config, I choose 443 port in the Admin Web Interface and let 53 for the DNS server, also try to let for all the interfaces in the Admin Web Interface, and DNS Server too. In the moment, Admin web Interface is set to Ethernet (With my Local IP Address) and set to 443 (HTTPS) port.

**Comment by ameshkov** [comment]
First of all, you need to configure your Windows PC to use AdGuard Home as a DNS server (check the setup guide, you can do it on your router or in Windows settings).

Only once it's done, it makes sense to do nslookup commands.

**Comment by dennyamarojr** [comment]
I configure Windows to use AdGuard Home as a DNS Server, I also reinstall AdGuard home to see and it seems not working

**Comment by ameshkov** [comment]
Do you see `example.org` in AdGuard Home query log? If not, then something is not okay with the Windows configuration.

**Comment by dennyamarojr** [comment]
Yes I see this in the query log, I'm trying to reinstall again and see if works now but it seems not working :(

**Comment by ameshkov** [comment]
Try `nslookup ad.doubleclick.net` and check what response is returned. Should be `::` or smth like. this.

**Comment by dennyamarojr** [comment]
Now is showing this
C:\Users\Windows\Downloads\AdGuardHome>nslookup ad.doubleclick.net
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  2804:14d:c810:672:179:234:0:11

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out

:(

**Comment by ameshkov** [comment]
well, something is definitely not okay.

Try `nslookup ad.doubleclick.net IPADDR` where IPADDR is the ip address of AdGuard Home. Does it work?

**Comment by dennyamarojr** [comment]
Works now, show this
C:\Users\Windows\Downloads\AdGuardHome>nslookup ad.doubleclick.net 127.0.0.1
Server:  localhost
Address:  127.0.0.1

Non-authoritative answer:
Name:    ad.doubleclick.net
Addresses:  ::
          0.0.0.0

**Comment by ameshkov** [comment]
Well, the problem is that Windows for some reason does not use it.

Make sure that you configured DNS as it explained here:
https://www.privateinternetaccess.com/blog/changing-your-dns-settings-on-windows-10/

Try 127.0.0.1 or any other address that AG Home lists in Setup guide.

I'll keep this question open, maybe someone else more familiar with Windows-specific issues may help.

**Comment by dennyamarojr** [comment]
I try to put the other address and it seems not working too, I will try to keep the http port for the adguard home and see what's happen

**Comment by dennyamarojr** [comment]
I try here with port 80 (http) and is not working too, the problem is that windows are ignoring the DNS servers from AdGuard Home. I check here and in the query log says that block youtube and github but even restarting the service, github and youtube is possible to be accessed

**Comment by dennyamarojr** [comment]
Here's the screenshot
![003](https://user-images.githubusercontent.com/36896116/98876403-1473d680-2433-11eb-8e34-2699749509a0.JPG)

**Comment by dennyamarojr** [comment]
OK, what I will tell is weird but I think that AdGuardHome is working now. What I do is configure the AdGuardHome using 443 port (HTTPS) and them set the DNS in windows to my local ip address as showed in the list of dns server for AdGuardHome.

After that I configure the Upstream and Bootstrap DNS Servers, after that I add some filters at this point nothing is blocked.
What I do was, open CMD as admin and type
1 - ipconfig /registerdns
2 - ipconfig /flushdns
3 - Restart the computer.

After doing this, it seems to be blocking everything now. 
Photopea website - has ads
Probuilds.net - has ads

Here's some screenshots
![004](https://user-images.githubusercontent.com/36896116/98882916-345ec680-2442-11eb-942d-5dcc95852372.jpg)
![005](https://user-images.githubusercontent.com/36896116/98882919-358ff380-2442-11eb-955c-bb2127a70b9d.jpg)
![006](https://user-images.githubusercontent.com/36896116/98882923-36c12080-2442-11eb-9dfb-92b30675a780.jpg)
![007](https://user-images.githubusercontent.com/36896116/98883103-a6371000-2442-11eb-99bb-da3a6d892f53.jpg)

**Comment by dennyamarojr** [comment]
I'm testing it seems that for the most websites I'm acessing the ads are gone, on youtube, sometimes appears and sometimes doesn't appear for me.
Here's a screenshot from mediafire where we can find some ads in the page (but is been blocked 👍 
![008](https://user-images.githubusercontent.com/36896116/98887078-1d23d700-244a-11eb-9c33-3c1af241eaad.jpg)
 )

**Comment by badmojr** [comment]
> Well, the problem is that Windows for some reason does not use it.
> 
> Make sure that you configured DNS as it explained here:
> https://www.privateinternetaccess.com/blog/changing-your-dns-settings-on-windows-10/
> 
> Try 127.0.0.1 or any other address that AG Home lists in Setup guide.
> 
> I'll keep this question open, maybe someone else more familiar with Windows-specific issues may help.

I use [YogaDNS](https://www.yogadns.com/) as a client.
![yoga](https://user-images.githubusercontent.com/40524316/98896166-65c6a900-24b9-11eb-9e6c-32145534979a.PNG)

**Comment by ameshkov** [comment]
Please note that not every ad is possible to block on a DNS level.

It's good that the issue with Windows configuration is resolved now.
