### ISSUE TITLE
Can't block client (TypeError: Cannot read property 'concat' of null)

### ISSUE THREAD

**Issue by vietch2612** [AdguardTeam/AdGuardHome#2300]
### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home v0.104.1
* **How did you setup DNS configuration:**
  * Router. On Google Cloud VM
* **Operating system and version:**
  *  Ubuntu 18.04 LTS

### Steps to reproduce

1. Go to AdGuard Dashboard
2. In the client list, click Block on some client

#### Expected Result
Blocked the client
#### Actual result
Showing error message: "TypeError: Cannot read property 'concat' of null"

### Screenshots

![image](https://user-images.githubusercontent.com/14076603/98957450-cabee500-2533-11eb-928d-7c3cfec95d2f.png)

**Comment by ArtemBaskal** [comment]
Request `access/list` could respond with `disallowed_clients: null` by mistake. Could you check the request?

**Comment by vietch2612** [comment]
Hi @ArtemBaskal,

It looks like the `disallowed_clients` return `null` in the very beginning when I finished the setup process.

`curl 'http://url/control/access/list' \ --compressed \ --insecure`

Response
`{"allowed_clients":[],"disallowed_clients":null,"blocked_hosts":["version.bind","id.server","hostname.bind"]}`

By the way, It worked right now after a day, I don't know why lol. I think we can just force `disallowed_clients` to return `[]` when it's null?
