### ISSUE TITLE
/dhcp/find_active_dhcp - never finishes it's work (may be specific to a snap version)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2301]
There's is no timeout (anymore?) for this method.

**Comment by TooYoungTooSimp** [comment]
I'm using agh on plain ubuntu without snap, and after I reset dhcp settings and when try to reconfigure it. This problem happens. So this should not be a snap related issue?

**Comment by ameshkov** [comment]
Yeah, it seems global. The solution for now would be tp enable DHCP via AdGuardHome.yaml

**Comment by ainar-g** [comment]
<p>As&#xA0;far&#xA0;as&#xA0;I&#xA0;can tell, there is a&#xA0;timeout
for&#xA0;request reading
<a href="https://github.com/AdguardTeam/AdGuardHome/blob/v0.104.1/internal/dhcpd/check_other_dhcp.go#L110">here</a>,
but&#xA0;not&#xA0;for&#xA0;writing and&#xA0;not&#xA0;for&#xA0;the&#xA0;DNS
resolution
<a href="https://github.com/AdguardTeam/AdGuardHome/blob/v0.104.1/internal/dhcpd/check_other_dhcp.go#L57">above</a>.&#x2003;By&#xA0;the&#xA0;way, is the&#xA0;DNS request even
needed there?&#x2003;Either way, I&#xA0;couldn't find any other places where
a&#xA0;timeout could be added.&#x2003;I'm also not&#xA0;sure if&#xA0;<i>Go</i>
allows us to&#xA0;set a&#xA0;timeout for&#xA0;<code>net.ResolveUDPAddr</code>,
but&#xA0;I'll keep&#xA0;looking.</p>
