### ISSUE TITLE
Static IP address is not detected if set via /etc/network/interfaces

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2302]
See the report here:
https://t.me/adguard_en/107079

**Comment by ainar-g** [comment]
<p>I&#xA0;can't find any reference to <code>/etc/network/interfaces</code>
in&#xA0;the&#xA0;code we have now.&#x2003;Unless&#xA0;I&#xA0;misunderstand
something, this is actually a&#xA0;feature request and&#xA0;should thus&#xA0;be
in&#xA0;the&#xA0;<code>v0.105.0</code> milestone.&#x2003;What do
you&#xA0;think?</p>

**Comment by ameshkov** [comment]
Yeah, it should be reassigned to v0.105 indeed.

However, please verify that enabling the DHCP server is possible even when we cannot detect that the IP is static.

**Comment by ainar-g** [comment]
<p>I&#xA0;was able to&#xA0;enable DHCP on&#xA0;a&#xA0;<i>Debian</i> system
where&#xA0;we couldn't detect if&#xA0;the&#xA0;IP is static,
so&#xA0;I&#xA0;guess this issue should be relabelled
as&#xA0;<code>feature request</code> and&#xA0;<code>v0.105.0</code>?</p>

**Comment by ameshkov** [comment]
Yep
