### ISSUE TITLE
Why can't the full ipv6 address be displayed?

### ISSUE THREAD

**Issue by HsuXwAsTe** [AdguardTeam/AdGuardHome#2307]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.1
* **How did you setup DNS configuration:**
  * router
* **If it's a router or IoT, please write device model:**
  * openwrt 19.07
* **Operating system and version:**
  * openwrt 19.07

### Expected Behavior

I want to display the full ipv6 address
### Actual Behavior

ipv6 address suffix is... Replace.

### Screenshots

<img width="442" alt="Snipaste_2020-11-13_17-38-47" src="https://user-images.githubusercontent.com/72607204/99058099-9e878080-2594-11eb-95a4-df4e63227b51.png">
<img width="929" alt="Snipaste_2020-11-13_17-40-56" src="https://user-images.githubusercontent.com/72607204/99058102-9fb8ad80-2594-11eb-9b15-b2cd22083920.png">
<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
