### ISSUE TITLE
Error : control/dns_config | | 504

### ISSUE THREAD

**Issue by boyphongsakorn** [AdguardTeam/AdGuardHome#2309]
* **Version of AdGuard Home server:**
0.104.1
* **How did you setup DNS configuration:**
IoT
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4 Model B
* **Operating system and version:**
Home Assistant 

i can't Disable protection, Upstream DNS servers, or change and save 
after 3 minutes i got "Error : control/dns_config 504"

![ee](https://i.ibb.co/0fxpzVM/613-C27-E7-A2-C9-4-C1-A-9-BB0-FE073-A913-D4-B.png)

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by SkyYkb** [comment]
Are you running AdGuard Home web interface behind a reserve proxy?

**Comment by boyphongsakorn** [comment]
> Are you running AdGuard Home web interface behind a reserve proxy?

No, but I used proxy addons ,before I install ,i delete proxy add-ons After that I install AdGuard add-ons
