### ISSUE TITLE
Unable to apply new DNS settings, GUI gets stuck! 

### ISSUE THREAD

**Issue by cait4code** [AdguardTeam/AdGuardHome#2310]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
Router give out Adguard Home IP via DHCP
* **If it's a router or IoT, please write device model:**
Raspberry PI 4 2GB
* **Operating system and version:**
 Latest Raspberry PI OS

### Expected Behavior
Attempting to change upstream DNS server under the DNS tab when clicking apply I would expect the changes to be made

### Actual Behavior
When clicking apply, the button greys out and gets stuck. Change of DNS server doesn't change even after leaving for 10 minutes and refreshing page 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information
Currently stuck using Cloudflare DNS over HTTPs, wanting to change to experiment with DNS over QUIC

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
