### ISSUE TITLE
Some devices stop showing up on log

### ISSUE THREAD

**Issue by asdfok** [AdguardTeam/AdGuardHome#2314]
I had this issue since the first day of using it. I'm not sure why or how did this happen.
![Screenshot_2020-11-15-09-24-00-932_com android chrome](https://user-images.githubusercontent.com/20973422/99161428-d8878c80-2724-11eb-8c5a-1b7511eb84f4.jpg)

**Comment by ameshkov** [comment]
Could you please provide more details? It's unclear to me what's wrong from the screenshot.

**Comment by asdfok** [comment]
> Could you please provide more details? It's unclear to me what's wrong from the screenshot.

In the morning, around 7am. I checked this log, just to see if it's still recording. It's not. It's my phone, from 03:27:28 until 09:16:46 is not recorded.
I tried to disable and re-enable it, and then checked the Query Log. it's still not showing. I leave it, rechecked again at 09:24 and suddenly it start to recording again.
