### ISSUE TITLE
DNS over HTTPS and Docker

### ISSUE THREAD

**Issue by pernodpepper** [AdguardTeam/AdGuardHome#2316]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.1 (Latest)
* **How did you setup DNS configuration:**
  * Docker (Portainer on Synology) using a different port internal (8088) and a normal port external using reverse proxy (443)
* **If it's a router or IoT, please write device model:**
  * Synology DS218+
* **Operating system and version:**
  * DSM 7 (Docker)

### Expected Behavior
I'm trying to setup DNS over HTTPS using port 443

### Actual Behavior
When opening the page an error shows up "Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400" and I can't get it to work. I also tried changing it to 8088 (the http port used for AdGuard) but it gave me the same error.

### Additional Information
I'm not sure if this can work on the way I set it up but I don't know if it can be done better. Port 443 is in use by the reverse proxy server so that won't be an option to use for AdGuard only.

**Comment by ameshkov** [comment]
You just need to use any other free port to configure HTTPS there - any not occupied by other programs or AGH itself.

**Comment by pernodpepper** [comment]
> You just need to use any other free port to configure HTTPS there - any not occupied by other programs or AGH itself.

Seems to fix the issue, but is the /dns-query also available on the http port? I'm using a reverse proxy and I don't need the certificate settings and https port.

**Comment by ameshkov** [comment]
Check this out: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#disable-doh-encryption-on-adguard-home

**Comment by pernodpepper** [comment]
After some trying I managed to reach my goal. Protect my phone with AdGuard Home DNS over mobile data. I changed the reverse proxy to the HTTPS port and that works, and I also portforwarded DNS over TLS.  Using the AdGuard app I can now use DNS of HTTPS. Thanks guys!

**Comment by bigjeans** [comment]
Hello,

I have the same problem as you described above, or rather you solved it and I didn't :(

I also have a reverse proxy set up for my adguard.
Source
Protocol: HTTPS
Hostname: adguard.synology.....me
Port: 433
Enable HSTS: Yes

Destination
Protocol: HTTP
Hostname: 192.168.2.4
Port: 8080

Do I have to enter the port, e.g. 445, in adguard and unblock it on the router?

What about the certificate? I have a wildcard on synology where the adguard domain is subsumed under my domain us synology or download it to the disk and select and paste, but which file is their 11pcs.

As a private key? privkey.pem but there is also ECC-privkey.pem and this RSA-privkey.pem

Certificate? cert.pem, chain.pem and others which one to use? and have you used it?

Please help.
