### ISSUE TITLE
Do not disable DNS Rewrites when Protection is disabled

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#2317]
### Problem Description
While browsing the web and when I bump into issues I usually turn off protection by toggling the "Disable protection" button:

![image](https://user-images.githubusercontent.com/96476/99247622-1ce75b00-27ff-11eb-9b9a-89c75cd99d59.png)

This also disables "DNS Rewrites" and all the services on my local network go down as well.

### Proposed Solution

Never disable "DNS Rewrites" when "Disable protection" is ON. "DNS Rewrites" should always be enabled because they are rewrites for your local DNS resolution, they are not meant to "protect" anything.

### Alternatives Considered

I've since moved all my custom DNS Rewrites to my router's `dnsmasq` configuration.

Would prefer to keep this in AdGuard because when it would be one less configuration to worry about when I upgrade my router in the future.

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdGuardHome/issues/1558
