### ISSUE TITLE
Self-signed certificate gets "Certificate chain is invalid" message

### ISSUE THREAD

**Issue by seraphia83** [AdguardTeam/AdGuardHome#2320]
I generate a self-signed certificate that is marked with the comment "Certificate chain is invalid" within the web interface.
Now I need to know how / where to import the root CA certificate for getting rid of this message.

I already copied it to /usr/share/ca-certificates/extra/ and imported it with the command "sudo dpkg-reconfigure ca-certificates".

Didn't help... Any ideas?

Thanks in advance,

Markus

* **Version of AdGuard Home server:**
  * 0.104.1
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Ubuntu 20.04.1

**Comment by ameshkov** [comment]
Here's where AdGuard Home gets roots to validate the cert:
https://golang.org/src/crypto/x509/root_linux.go

Make sure that the root cert is there.
