### ISSUE TITLE
Mobileconfig generator and other implementation don't display on setup guide

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#2323]
See the release notes https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.104.0
iOS and MacOS .mobileconfig generator
![MmYzf2H](https://user-images.githubusercontent.com/63988538/99376471-92ceed80-28f7-11eb-932a-457ea00e70f5.png)

I noticed other implementation part on crowdin https://crowdin.com/translate/adguard-applications/17566/en-en#3862936
Is it outdated?

v0.104.1-SNAPSHOT-6358240e

**Comment by ameshkov** [comment]
Hi! They are displayed only when Encryption is configured in AdGuard Home.

**Comment by Aikatsui** [comment]
Maybe it's good to display them by default on setup guide as grayed or with hint as "You need to configure adguardhome encryption"

**Comment by ameshkov** [comment]
Well, that would be a lot of text shown. IMO, the current approach is cleaner.
