### ISSUE TITLE
AdGuard Home DNS over HTTPS and TLS

### ISSUE THREAD

**Issue by grubeli** [AdguardTeam/AdGuardHome#2329]
Not sure if I made some mistake or something just don't working.

I have a domain (example1.com) which I'm using as a blog (port 80 and 443 are used)
I've created _acme-challenge (TXT) on my domain and now DNS server admin panel is served via https.
I want to use DNS over TLS since 443 port for DoH is used by the blog.
When I try to use tls://example1.com as a DoT it's not working,
DNS server itself works.

Did I miss or doing something wrong?

* **Version of AdGuard Home server:**
  * Version: 0.104.1
* **How did you setup DNS configuration:**
  * Router
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior
Able to use tls://example1.com

### Actual Behavior
DNS apps on android say that it's invalid address

### Additional Information
I want to use my blogging domain:853 as a DoT

**Comment by ameshkov** [comment]
You know, in your case I'd suggest using nginx as a reverse proxy that serves both AdGuard Home and your blog.

For instance, you could serve AdGuard Home from a location (`example1.org/adguard` or smth like that):
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy

Regarding the original question - use telnet to check if port 853 is open.
