### ISSUE TITLE
Wrong character encoding when contacting Support via Outlook 2010 & 2013

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardHome#233]
> Мы используем Adguard DNS иногда возникают ситуации, когда блокируется нормальный сайт и наши пользователи пытаются связаться с вашей поддержкой через ссылку на заблокированном сайте, но при этом возникает проблема с кодировкой письма. При нажатии на ссылку " Связаться с поддержкой " открывается Outlook и в нём вместо текста нечитаемые символы.

![image](https://user-images.githubusercontent.com/15856304/35849823-901170dc-0b2b-11e8-9623-88a53d4985d5.png)

> Это наблюдается и Outlook 2010 и 2013. Браузер - Google Chrome. Причём видно, что сначала открывается страница с предупреждением на английском, а потом сама сразу же переключается на русский. При использовании Firefox, переключения на русский не происходит и кодировка остаётся читаемой, но на английском языке.

![image](https://user-images.githubusercontent.com/15856304/35849850-b0b3977a-0b2b-11e8-850d-e8414fd90871.png)

### Expected behavior

The encoding doesn't change

### Actual behavior

It changes to a wrong one

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Family protection DNS
| How did you setup DNS configuration:| Router
| Device model:| n/a
| Operating system and version:| n/a

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardDNS #12](https://github.com/AdguardTeam/AdGuardDNS/issues/12) via [**ZenHub**](https://www.zenhub.com/)
