### ISSUE TITLE
DHCP page not available

### ISSUE THREAD

**Issue by fadver** [AdguardTeam/AdGuardHome#2330]
### Issue Details

v0.104.1-SNAPSHOT-8a9c6e8a
Ubuntu 20.04.1 LTS
Установил adguard-home как обсуждалось [тут](https://github.com/AdguardTeam/AdGuardHome/issues/2228), иначе dhcp не работал. 
ADH работал нормально день-два и сейчас работает, включая dhcp, только страница //my_adh_ip/ # dhcp НЕ открывается. Возможно я что-то упустил ...?

**Comment by ameshkov** [comment]
Не, это баг в edge-канале, уйдет в новой версии которая в 2 часа дня сегодня появится.

**Comment by fadver** [comment]
Спасибо за информацию!

**Comment by ameshkov** [comment]
Сейчас обновим в edge-канале билд чтоб долго не ждать, через полчаса проверьте

**Comment by fadver** [comment]
Обновил. Все работает. Спасибо!
