### ISSUE TITLE
How the Parental control function should work.

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2331]
I use the latest stable version 104.1 (AdGuard Home_linux_mipsel_softfloat), on OpenWrt 19.07.4. the Parental control function Does not work. This option is enabled in the settings. But if I enter "porn" in the Yandex search page, all adult content is available. How do I set it up so that there is no adult content at all?

**Comment by ameshkov** [comment]
Safe search relies on Yandex itself, we simply force the specific IP address as described here: https://yandex.ru/support/search/schoolsearch.html

Make sure that your browser does not cache the previous Yandex IP address. Try incognito tab for a clean test.

**Comment by fizsef** [comment]
OK. Yandex itself handles the search, but I can go directly to the porn site. Why does AdGuard Home allow you to open porn sites?

**Comment by ameshkov** [comment]
@fizsef it should bock porn sites, of course.

Do you see a DNS query to that porn site in the query log?

**Comment by fizsef** [comment]
Да, вижу в журнале. И не блокируются они. Вот посмотрите в прикрепленном файле.  Как можно это исправить? 19.11.2020, 12:12, "Andrey Meshkov" <notifications@github.com>: @fizsef it should bock porn sites, of course.Do you see a DNS query to that porn site in the query log?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
