### ISSUE TITLE
An URL that switches/toggles protection on/off ?

### ISSUE THREAD

**Issue by zilexa** [AdguardTeam/AdGuardHome#2332]
I am simply looking for an easy way to disable protection without having to (open browser) go to the webui and hitting the button. Instead: a URL  that instantly toggles the protection mode (off when it was on, on when it was off). Is this possible?

That way, I could add the URL to my bookmark toolbar (on desktop) or to my Android Homescreen or Firefox new-tab screen. 

As an improvement: a similar URL that toggles protection on/off but  allows you to add a cTag (`http://192.168.88.2:3000/..../...&ctag=clientname`) or something, to identify the client and allow toggling protection for a specific client.

**Comment by jdefelice19** [comment]
There’s no “easy” way to do this via a browser. You can do it via the API but it requires a POST request, which you can’t do natively in a browser without an extension. Other than using a browser extension, you have a few choices:

- Create a local HTML form and bookmark it (probably the path of least resistance and closest to what you’re looking to do)
- If you’re an iOS user, you can use a shortcut that toggles AGH on and off (I created a shortcut to do this, as well as a few others)

You could also use Postman but that’s a bit heavyweight for what you’re looking to do. 

HTH

**Comment by jvoisin** [comment]
This looks a bit dangerous, since it would allow websites to turn your AGH off :P

**Comment by jdefelice19** [comment]
It  uses the same username/password authentication and base url that you use to log into the admin portal, which in turn leverages the API, so it’s not any more or less risky than having the admin portal available for management/enabling/disabling. 

FWIW, I would prefer the option to get a JWT for authentication, which I believe pi-hole supports, but the API is otherwise pretty robust.

**Comment by zilexa** [comment]
@jdefelice19 I understand you have created the HTML file? Would you mind sharing it? I have no clue how to do that.. 

> Create a local HTML form and bookmark it (probably the path of least resistance and closest to what you’re looking to do)
