### ISSUE TITLE
How do I fully uninstall AGH on Ubuntu 20.04?

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdGuardHome#2333]
I need to remove AGH from an Ubuntu machine completely but I can't find full instructions anywhere. I uninstalled the service and remove all files, by while setting up it also required to bind to port 53, so everytime I connect to a network `/etc/resolv.conf` contains `nameserver 127.0.0.1` at the top. How do I remove all binding from port 53, in other words, how do I undo all changes I made while setting up AGH?

**Comment by ameshkov** [comment]
Ehm, it depends on what changes you made.

The only thing that's made automatically is registering a service, and that you already uninstalled.

You also may have done something like what's described here: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse
