### ISSUE TITLE
The DOH with nginx reverse proxy does not work on the  Secure DNS in the New Microsoft Edge (windows)

### ISSUE THREAD

**Issue by leo15dev** [AdguardTeam/AdGuardHome#2334]
### Issue Details

* **Version of AdGuard Home server:**
 AdGuard Home v0.104.1
* **How did you setup DNS configuration:**
System
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4 Model B
* **Operating system and version:**
Server: Ubuntu 20.04.1; Testing system Windows 10

### Expected Behavior
The Adguard Home DOH with nginx reverse proxy work on the  Secure DNS in the New Microsoft Edge (windows)

### Actual Behavior
When use the **https://your.domain/dns-query** in the Secure DNS in the New Microsoft Edge, the nginx access log showed that  "POST /dns-query HTTP/1.1" 200 468 "-" "Chrome"

When use the  **https://your.domain/dns-query(?dns)** in the Secure DNS in the New Microsoft Edge, the nginx access log showed that  "GET /dns-query?dns=AAABAAABAAAAAAABBmdvb2dsZQNjb20AAAEAAQAAKRAAAAAAAABZAAwAVQAAAAAAAAAAAAAAAAAA HTTP/2.0" 200 55 "-" "Chrome"

However, both of the above two methods did not successfully work. Because when I opening the web pages, it do not have the 
filtered effect. And in the query log on the Adguard Home Dashboard, I could not find the any new query log by that device ( New Microsoft Edge ) .

The same issue (non filtered effect) was happened when I set with the **https://dns.adguard.com/dns-query**.  I thinks the chrome or firefox should have the same issue.

When do not use the default https port (443), the  Secure DNS in the New Microsoft Edge does not accept the setting like **https://your.domain:port/dns-query**, so it needs use the reverse proxy server.

**Comment by ameshkov** [comment]
I cannot reproduce this.

![image](https://user-images.githubusercontent.com/5947035/99644724-574f3300-2a5f-11eb-9df8-5e90dea41ec1.png)

https://adguard.com/en/test.html

![image](https://user-images.githubusercontent.com/5947035/99644753-5e764100-2a5f-11eb-8008-17e086671161.png)

Make sure you have HTTP/2 enabled in nginx.

**Comment by leo15dev** [comment]
After I double check with another DOH which was provided by other machine , I found there is something  wrong with my nginx.conf. After modified it, the issue was solved ! Thanks for your kindly reply!
