### ISSUE TITLE
能否增加手机版查询日志页面显示的参数？

### ISSUE THREAD

**Issue by woboo110** [AdguardTeam/AdGuardHome#2335]
能否增加手机版查询日志页面显示的参数？比如DNS服务器、耗时等？目前需要点开才能查看

**Comment by ameshkov** [comment]
对不起，我不懂你要什么参数。你要手机应用程式吗？

**Comment by woboo110** [comment]
目前手机查询日志页面只能看到时间和请求的域名，需要点一下域名才能显示具体响应细节，比如DNS服务器，耗时、客户端详情等

**Comment by Aikatsui** [comment]
這會很難

**Comment by ameshkov** [comment]
@woboo110 谢谢，我知道了。这是故意的。手机的屏幕很小，我们觉得能看更多查询比能看请求的细节很重视。

如果你要看更多参数，你可以用你浏览器的“桌面版网站”功能。
