### ISSUE TITLE
AdGuardHome拦截广告

### ISSUE THREAD

**Issue by xiaoqi2020** [AdguardTeam/AdGuardHome#2340]
AdGuardHome对广告的拦截效果真的聊胜于无，添加了各种广告NDS清单都没什么用，https的广告更是无法拦截，究竟要怎么配置才能真正的拦截广告呢？请技术大佬帮忙解答一下，谢谢！

**Comment by ameshkov** [comment]
以后我们打算添加能滤https的代理到AdGuard Home，请看 #1228. 不过这个功能是真复杂的，我们开展需要很长时间。
