### ISSUE TITLE
[구식의] Invalid string

### ISSUE THREAD

**Issue by eoopx** [AdguardTeam/AdGuardHome#2341]
DNS settings --> Upstream DNS servers
"서버 주소를 한 줄에 하나씩 입력해주십시오. 업스트림 DNS 서버 구성에 대해 "자세히 알아보십시오z'. 여기에 선택가능한 DNS 목록"

**Comment by ameshkov** [comment]
Thank you, we'll fix it!

Meanwhile, if you want to contribute to translations, we're doing it via Crowdin:
https://github.com/AdguardTeam/AdGuardHome#help-with-translations

**Comment by NataKiss** [comment]
AdGuard Home 프로그램에서 서버 주소 입력에 문제가 있으신가요?
“서버 주소를 한 줄에 하나씩 입력해주십시오. 업스트림 DNS 서버 구성에 대해 자세히 알아보십시오.“라고 적어주신 것은 어떤 문제가 있는지 파악하기가 어렵습니다. 프로그램이나 번역에 에로사항이 있으시면 자세히 알려주시면 감사하겠습니다.

**Comment by eoopx** [comment]
@NataKiss https://crowdin.com/translate/adguard-applications/17566/en-ko#3862834
Here is a <0>list of known DNS providers</0> to choose from. --> 여기에 선택가능한 DNS 목록 </0>이 있습니다.

**Comment by eoopx** [comment]
@NataKiss https://crowdin.com/translate/adguard-applications/17566/en-ko#3917402 틀린

**Comment by NataKiss** [comment]
@eoopx AdGuard에 관심이 가져 주셔서 감사합니다!
