### ISSUE TITLE
Upcoming Ads

### ISSUE THREAD

**Issue by SidEwigk** [AdguardTeam/AdGuardHome#2344]
After the last Updates ads restart to coming up in apps on my android Phone...why?

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Please check this instruction and make sure you configured your devices to use AGH:
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#doesntblock
