### ISSUE TITLE
The query log does not display the data correctly.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2345]
Version: v0.104.3-046ec13f

The blocked domain name is not marked in red and the filter name is not displayed
The domain name that was not blocked does not display the upstream DNS server name, and all elapsed time is 0.00ms (even if DNS cache is turned off).

<img width="878" alt="Xnip 2020-11-21 08 24 20" src="https://user-images.githubusercontent.com/58100052/99862458-cac68100-2bd4-11eb-9287-68fcf68b2773.png">
<img width="1484" alt="Xnip 2020-11-21 08 29 49" src="https://user-images.githubusercontent.com/58100052/99862463-cdc17180-2bd4-11eb-8df8-7757b2be6086.png">
<img width="860" alt="Xnip 2020-11-21 08 25 14" src="https://user-images.githubusercontent.com/58100052/99862472-d4e87f80-2bd4-11eb-8559-1ae0b0eaf20e.png">

**Comment by ameshkov** [comment]
Weird, I cannot reproduce this.

**Comment by hezhijie0327** [comment]
Well, I found out why this happened. The "querylog_size_memory: 0" in the settings is the cause of the problem. But what puzzles me is that the value of 0 did not cause this problem in previous versions. And now after I set it to 1000, the previous log still shows 0ms.
<img width="1320" alt="Xnip 2020-11-23 23 02 45" src="https://user-images.githubusercontent.com/58100052/99978335-c969a400-2de0-11eb-9da8-2b982b92a483.png">
<img width="1330" alt="Xnip 2020-11-23 23 06 06" src="https://user-images.githubusercontent.com/58100052/99978356-cff81b80-2de0-11eb-988c-7975c6781ca2.png">

**Comment by hezhijie0327** [comment]
0 < querylog_size_memory  <= 5: The same issue like 0. 
      querylog_size_memory > 5: It becomes normal.

**Comment by ameshkov** [comment]
Thank you! Definitely a bug.

**Comment by ainar-g** [comment]
<p>Should&#xA0;be fixed as&#xA0;of&#xA0;snapshot 60d72fb9.&#x2003;Please feel
free to&#xA0;reopen with&#xA0;more details if&#xA0;it&#xA0;isn't!</p>
