### ISSUE TITLE
Вопросы по работе шифрования и блокировки взрослых сайтов.

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2347]
Добрый день. Версия программы: 0.104.3 . 
1. Вопрос. 
В настройках DNS указан "tls://dns-unfiltered.adguard.com" ,
![НеШифруетсяПроупскает порно1](https://user-images.githubusercontent.com/74646605/99873914-7d5a0c00-2bf4-11eb-9c0c-78ad669af136.jpg)  но запросы не шифруются, смотрите скрин журнала 
![НеШифруетсяПроупскает порно](https://user-images.githubusercontent.com/74646605/99874047-a4650d80-2bf5-11eb-84d8-f830f8a81f54.jpg)

2. Вопрос. В настройках включен родительский контроль, но не блокирует взрослые сайты. Это видно на скрине журнала выше, где порно сайт 365porno.one обработан успешно 
![НеШифруетсяПроупскает порно2](https://user-images.githubusercontent.com/74646605/99874034-87c8d580-2bf5-11eb-833a-ef73a7939c30.jpg)

**Comment by Eyeborgs** [comment]
Нас счет шифрования в журнале - эта отображается по какому протоколу (DoT, DoH, DoQ или обычное подключение по 53 порту) подключены ваши устройства к AdGuard Home а все ваши запросы зашифрованы "DNS-сервер" через TLS как вы настроили в "Upstream DNS-серверы". 

Нас счет "родительского контроля" я не могу не чего сказать потому что я этим не пользуюсь - сильно замедляет DNS - я просто фильтры ищу в замен этой функции..

**Comment by fizsef** [comment]
> Нас счет шифрования в журнале - эта отображается по какому протоколу (DoT, DoH, DoQ или обычное подключение по 53 порту) подключены ваши устройства к AdGuard Home а все ваши запросы зашифрованы "DNS-сервер" через TLS как вы настроили в "Upstream DNS-серверы".
> 
> Нас счет "родительского контроля" я не могу не чего сказать потому что я этим не пользуюсь - сильно замедляет DNS - я просто фильтры ищу в замен этой функции..

Спасибо за ответ. Я не силен во всем этом, настройки у меня все по умолчанию, кроме того что прописал в Upstream DNS-серверы "tls://dns-unfiltered.adguard.com" , чтобы запросы стали зашифрованными. Или этого недостаточно или вообще не это? Подскажите, какие настройки нужны , чтобы днс запросы зашифровать, чтобы  остаться в сети инкогнито.
На счет род.контроля, тоже отключу рас он торможзит. Поделитесь фильтрами, если есть. спс.

**Comment by Eyeborgs** [comment]
Нас счет шифрования не чего менять не надо - вы все правильно сделали и ваши DNS запросы зашифрованные.

Поделится фильтрами не могу - потому что я помогал другу настраивать их где то год назад по этому не помню где я их искал..
Может кто то поможет с поиском фильтров тут.

**Comment by fizsef** [comment]
> Нас счет шифрования не чего менять не надо - вы все правильно сделали и ваши DNS запросы зашифрованные.
Как же они зашифрованы, если в журнале  написано обратное? 
![1](https://user-images.githubusercontent.com/74646605/99877328-6e805300-2c0e-11eb-9674-e92fc7e05358.jpg)

**Comment by Eyeborgs** [comment]
как я говорил - журнал отображает подключение "клиентов" к AdGuard Home а вот когда наводишь мышку на знак вопроса там как раз и отображается в "DNS-сервер" через какой сервер был получен ответ.

Вот как у меня подключение идет - роутер подключается к AdGuard Home через TLS соединения в локальной сети и по этому у меня и отображается DoT в запросе..
![--](https://user-images.githubusercontent.com/46345396/99877424-2f063680-2c0f-11eb-9f06-889d6a2346d1.png)

**Comment by fizsef** [comment]
А , немного стало понятнее. А подключение роутера к АдгуардХоум по TLS для чего, если это внутренняя ваша сеть?

**Comment by Eyeborgs** [comment]
Для тестирования грубо говоря

**Comment by fizsef** [comment]
Понятно. Вот если Upstream DNS-серверы  я указал  "tls://dns-unfiltered.adguard.com" то запросы мои стали зашифрованными, но при этом перестает рекламу блокировать. Как то можно настроить, чтобы и рекламу блокировал, и пакеты были зашифрованные ?

**Comment by Eyeborgs** [comment]
ну тут два пути, или использовать другой зашифрованный DNS с фильтрацией который блокирует рекламы и другие сайты или в фильтрах включить дополнительные фильтры - если знаете можете свои добавить или воспользоваться шаблоном: Фильтры -> Добавить черный список -> Выбор из списка а дальше галочки ставите на нужные фильтры и нажимаете сохранить

**Comment by fizsef** [comment]
Но главная  проблема в том, что если использовать tls://dns-family.adguard.com  то он блокирует Комменты в Ютуб ( это все и портит.

**Comment by Eyeborgs** [comment]
Ну с этим должна разобраться команда AdGuard DNS потому что мне кажется эта серьезная ошибка раз блокируются комментарии в YouTube..

Тогда попробуйте tls://dns.adguard.com ну или с шаблонами поиграйтесь..

**Comment by fizsef** [comment]
Игрался , в фильтры добавлял 
@@||googlevideo.com^
@@||youtube.com^
@@||mtalk.google.com^
но не помогает

**Comment by Eyeborgs** [comment]
> воспользоваться шаблоном: Фильтры -> Добавить черный список -> Выбор из списка а дальше галочки ставите на нужные фильтры и нажимаете сохранить

Я имел введу тут: <details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/99878230-fff2c380-2c14-11eb-9018-eeb0ced1788d.png)
![image](https://user-images.githubusercontent.com/46345396/99878189-aa1e1b80-2c14-11eb-8635-1e3a9d47e0b3.png)
![image](https://user-images.githubusercontent.com/46345396/99878192-bace9180-2c14-11eb-9074-4fb7152dd177.png)

</details>

**Comment by fizsef** [comment]
> Если вы шаблоны в фильтрах настроили тогда верните tls://dns-unfiltered.adguard.com в "Upstream DNS-серверы"

если вернуть dns-unfiltered, ну тогда реклама вообще пересатет блокироваться

**Comment by fizsef** [comment]
Реклама и взрослый контент блокируется, но и комменты блокируются в ютуб. Какой то замкнутый круг (  Вот семейный днс от яндекс блокирует порно и с комментами в ютуб все хорошо, но он не блокирует рекламу. ((( как все это настроить

**Comment by Eyeborgs** [comment]
Я все что знал вам рассказал больше я не знаю как я могу вам помочь, по идеи в понедельник команда AdGuard Home должна вам помочь тут..
Просто то что у вас не в моих силах исправить или помочь...

**Comment by ameshkov** [comment]
`365porno.one` - его просто в списках у нас не было. Добавили теперь, спасибо
