### ISSUE TITLE
Filter out internal network look ups

### ISSUE THREAD

**Issue by gerroon** [AdguardTeam/AdGuardHome#2348]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

I get a lot of `XXX.1.168.192.in-addr.arpa` type  of dns look ups in the log listing, they litter the logs. 

### Proposed Solution
It would be nice to be able to just hide them, since they seem to be just internal network related lookups. So basically it would be nice if there is an option to hide internal ones, or only show external DNS lookups.

Thanks

**Comment by Aikatsui** [comment]
This can be achieve using https://github.com/AdguardTeam/AdGuardHome/issues/594 or https://github.com/AdguardTeam/AdGuardHome/issues/1164 (and both)

**Comment by ameshkov** [comment]
Merged here: https://github.com/AdguardTeam/AdGuardHome/issues/2704
