### ISSUE TITLE
Default Malware domain list is no longer maintained

### ISSUE THREAD

**Issue by clhuby** [AdguardTeam/AdGuardHome#2349]
The Malware Domain List (https://www.malwaredomainlist.com/hostslist/hosts.txt) used as a default block list appears to be dead, and has not had any update or domains in its blocklist (except localhost) since the 12th of November.

Consider changing it to a regularly updated/maintainted list such as urlhaus's malware domain list: https://urlhaus.abuse.ch/downloads/hostfile/

**Comment by josephbu** [comment]
As per [my comment in issue 1913](https://github.com/AdguardTeam/AdGuardHome/issues/1913#issuecomment-702996193), for anyone who decides to use URLhaus (and you should) I would recommend using the "Lite version" which contains current online domains/IPs only. The full list results in false positives as it contains all historic entries forever, even if they were fixed year(s) ago. 

The URLhaus Lite version is very effective and there is a project that is already automatically [building the list in a suitable format](https://gitlab.com/curben/urlhaus-filter#domain-based-adguard-home).

**Comment by clhuby** [comment]
Thanks for that tip, I have updated my AGH lists with the lite versions!
