### ISSUE TITLE
File generation incorrect for: mobileconfig for DNS-over-TLS

### ISSUE THREAD

**Issue by josephbu** [AdguardTeam/AdGuardHome#2352]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.3
* **Operating system and version:**
  * Ubuntu 20.04.1 LTS

### Expected Behavior

File generation for .mobileconfig DNS-over-TLS to be successful.

### Actual Behavior

In the web interface followed these steps: Setup Guide -> DNS Privacy -> Download .mobileconfig for DNS-over-TLS

The `dot.mobileconfig` file that was generated & downloaded is not a valid xml file or recognised by iOS for import.

Having a closer look, the top line of the generated file `dot.mobileconfig` it includes an error message `getting host: address xxx: missing port in address`, top 3 lines of my generated file are as follows:

```
getting host: address syd.adfilter.net: missing port in address
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```
Additionally under the array for section `<key>PayloadContent</key>` there is no `<key>ServerName</key>` or associated `<string>` as you would expect.

### Additional Information

Based on the behaviour I have observed, the generation of the mobileconfig files tries to automatically detect hostname, IP, port based on the hostname/port that you use to access the web management interface.

For example, on my VM I have a "management" IP & http port that I mostly use to manage it as opposed to the public hostname over https, if I access the web interface via that "mangement" IP address I will get different contents in `doh.mobileconfig`.

To generate a correct `doh.mobileconfig` I needed to do this from the "public" hostname so that the details in the file are correct. 

Back to this issue for DOT, I have tried to generate the file when accessing the web interfaces on both http and https ports, using the public hostname and IP, as well as the private management IP, in all cases I get the `missing port in address` error.

My guess is that it might be easier to move away from auto detection for the generating values for these config files, an option might be to use the details for server name and port from "Settings -> Encryption settings"?

If you need any further information please let me know!

**Comment by ameshkov** [comment]
> My guess is that it might be easier to move away from auto detection for the generating values for these config files, an option might be to use the details for server name and port from "Settings -> Encryption settings"?

The information there may be ambiguous. For instance, you may use a wildcard certificate and keep the "server name" empty.

**Comment by josephbu** [comment]
> The information there may be ambiguous.

True, that is a fair point!

**Comment by ainar-g** [comment]
<p>We&#xA0;<em>do</em> need to&#xA0;move away from&#xA0;this silly autodetection
mechanism, but&#xA0;the&#xA0;bug in&#xA0;the&#xA0;original post can be fixed
quicker.&#x2003;@EugeneOne1 should be able to&#xA0;do that this&#xA0;week.</p>

<p>As&#xA0;for&#xA0;a&#xA0;better mechanism, we need to think about
it.&#x2003;For&#xA0;now we probably will fallback
to&#xA0;the&#xA0;<code>tls.server_name</code> parameter
from&#xA0;the&#xA0;configuration file for&#xA0;now.&#x2003;And&#xA0;respond
with&#xA0;something like&#xA0;a&#xA0;<code>500</code>&#xA0;error.</p>

**Comment by ameshkov** [comment]
> And respond with something like a 500 error.

Response like that if we can't find a way to detect the server name.
Response content should indicate what happened.

**Comment by ainar-g** [comment]
Yes, that's what I meant as well, thanks for clarifying.

**Comment by ainar-g** [comment]
<p>We've&#xA0;decided to&#xA0;solve the&#xA0;issue in&#xA0;a&#xA0;more
systematic fashion instead&#xA0;of&#xA0;yet&#xA0;another
patch.&#x2003;@josephbu, can you please take a&#xA0;look at&#xA0;#2358
and&#xA0;tell us, if&#xA0;that&#xA0;would solve your&#xA0;issue?</p>

**Comment by ainar-g** [comment]
<p>I'll&#xA0;close this issue for&#xA0;now.&#x2003;Please feel free to&#xA0;open
a&#xA0;new one if&#xA0;you think there are more&#xA0;issues.</p>
