### ISSUE TITLE
Семейные днс не блокируют порно, но зато блокируют комментарии в Ютуб.  

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2354]
На днях оставлял вам такую же заявку. Приводил пример порно сайта, который успешно пропускает  AdguardHome. Вы ответили, что проблема решена и указанный сайт добавлен в ваши списки. Но все остальные порно сайты, практически любой найденный поисковыми системами, открывается и успешно проходит ваши фильтры. Приводит пример даже не хочется, это не один , а практически любой, тем не менее, чтобы не быть голословным приведу скрин. При это , у меня апстрим днс используется семейный, плюс к этому включена опция Родительский контроль. 
Но зато, при включенном семейном днс(tls://dns-family.adguard.com),  успешно блокируются  комментарии в Ютуб. Если использовать другой днс, то Комментарии в Ютуб нормально показываются, и это явно не в Ютуб  дело. 
![1](https://user-images.githubusercontent.com/74646605/100002432-9837a680-2dd5-11eb-9cb0-d97a0193ea2f.jpg)

**Comment by ameshkov** [comment]
Вы пишите лучше вот сюда такие вещи: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/new

Ну и лучше конкретный домен приводите текстом, а то перепечатывать их со скриншота не так чтоб прям удобно:)
Да, какие-то домены с малым количеством трафика могут пропускаться. У нас база приличного размера, но на полноту претендовать тяжело.

> Но зато, при включенном семейном днс(tls://dns-family.adguard.com), успешно блокируются комментарии в Ютуб.

Просто в Youtube включается детский режим. В нем действительно блокируются комментарии в Youtube.
