### ISSUE TITLE
Confusing error message when checking for DHCP on IPv6 enabled raspbian

### ISSUE THREAD

**Issue by mdehaas** [AdguardTeam/AdGuardHome#2355]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details

I have started with 0.104.0 (I think) in which I configured DHCP and it was working fine. Then came updates and trouble started in my home network. First I ran into the issue that checking for other DHCP was looping forever. Then came the most recent release in which the test for other DHCP gives me a a really confusing error: 
`dhcpv6: Couldn't resolve UDP address 192.168.2.1:546: address 192.168.2.1: no suitable address found`
I would expect my configured IPv6 address there. besides that I do not see AGH binding to the mentioned port on IPv4 or IPv6 when starting AGH interactively. Since I didn't find any mention of this error using various searches this leads me to believe this is an error on my side. But I really want to use AGH as DHCP so I can use mu client configuration.
I have static IP's configured through dhcpcd.conf

I can't really find the place to post this on the forum so I'm sorry if I'm totally misplacing this.

* **Version of AdGuard Home server:**
  * 0.104.3
* **How did you setup DNS configuration:**
  * Trying to setup AGH as DHCP
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 2 -->
* **Operating system and version:**
  * Raspbian Latest

### Expected Behavior
Get no error from check for other DHCP servers

### Actual Behavior
Confusing error is given and no change in the interface to enable DHCP

### Screenshots

</details>

**Comment by ameshkov** [comment]
@ainar-g what could it be?

**Comment by jakesteele** [comment]
I am also getting the same issue, Raspberry Pi 4, IPv4 and IPv6 enabled.

**Comment by ainar-g** [comment]
<p>@mdehaas, @jakesteele, could you update your <i>AGH</i>
to&#xA0;the&#xA0;latest edge snapshot (36c7735b or&#xA0;later) and&#xA0;see
if&#xA0;the&#xA0;issue is still&#xA0;there?</p>

**Comment by mdehaas** [comment]
@ainar-g the error is displayed correctly now. I see the IPv6 address in the error message. This issue can be closed as far as I'm concerned.
I hoped not to be getting an error but unfortunately the error persists. It seems Raspbian keeps the port in use for the DHCP Client. I tried to update the config to static using an interface file in /etc/network/interfaces.d but tah seems to have knocked my RPi of the network :'(. Time for bed now. Will start fresh tomorrow. Thanks for the support.

**Comment by amrmzr** [comment]
Hi Greetings!

Using Latest AGH 0.107.44 on raspbian OS pi4 model B getting this exact same error on enabling ipv6 Address. please fix it.
Thanks
