### ISSUE TITLE
Make the mobileconfig API parameterized and more robust

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2358]
<p>We've&#xA0;already had quite a&#xA0;few bugs about&#xA0;the&#xA0;mobileconfig
HTTP API and&#xA0;its autoselection
of&#xA0;hostnames.&#x2003;Instead&#xA0;of&#xA0;churning&#xA0;out more temporary
solutions, let's solve the&#xA0;issue in&#xA0;a&#xA0;more systematic way
in&#xA0;<b>v0.105.0</b>:</p>

<p>(Updated&#xA0;<b>2020-11-27</b> after&#xA0;@ameshkov's&#xA0;comments.)</p>

<ol>
<li><del>The&#xA0;mobileconfig API MUST&#xA0;NOT respond with&#xA0;naked IP
addresses or&#xA0;hosts with&#xA0;ports.</del></li>
<li>The&#xA0;client MUST provide the&#xA0;host that&#xA0;is expected
in&#xA0;the&#xA0;output XML, for&#xA0;example in&#xA0;a&#xA0;GET query
parameter.&#x2003;This allows us to&#xA0;use the&#xA0;API in&#xA0;situations
where the&#xA0;server supports several hosts,
as&#xA0;well&#xA0;as&#xA0;with&#xA0;client&#xA0;IDs.&#x2003;But&#xA0;if&#xA0;they
don't, use <code>tls.server_name</code>, and&#xA0;if&#xA0;it's not&#xA0;set,
return a&#xA0;500&#xA0;error.</li>
<li>The&#xA0;UI MUST&#xA0;NOT show the&#xA0;links to&#xA0;the&#xA0;mobileconfig
API unless&#xA0;<code>tls.server_name</code> is set.&#x2003;Perhaps show
a&#xA0;form for&#xA0;getting a&#xA0;link with&#xA0;the&#xA0;desired
host&#xA0;instead.</li>
</ol>

<p>Things&#xA0;to&#xA0;think about and&#xA0;figure&#xA0;out:</p>

<ol>
<li><b>Q:</b>&#xA0;Should&#xA0;we make the&#xA0;<code>tls.server_name</code> parameter
required?&#x2003;What&#xA0;about&#xA0;servers that&#xA0;can accept connections
targeting multiple&#xA0;hosts?<br/><b>A:</b>&#xA0;It&#xA0;is required,
but&#xA0;only when&#xA0;clients don't provide a&#xA0;host
of&#xA0;their&#xA0;own.</li>
<li><b>Q:</b>&#xA0;Should&#xA0;there be a&#xA0;default host when&#xA0;the&#xA0;client
doesn't provide one, or&#xA0;should we be strict and&#xA0;always
require&#xA0;one?<br/><b>A:</b>&#xA0;The&#xA0;default
is&#xA0;<code>tls.server_name</code>.</li>
<li><b>Q:</b>&#xA0;Should&#xA0;we ban GETting the&#xA0;mobileconfig API
over&#xA0;plain&#xA0;HTTP?<br/><b>A:</b>&#xA0;No,&#xA0;since&#xA0;clients
provide the&#xA0;host&#xA0;now.</li>
<li><b>Q:</b>&#xA0;What&#xA0;about&#xA0;wildcard&#xA0;certificates?<br/><b>A:</b>&#xA0;If&#xA0;<code>tls.server_name</code>
is set, it does&#xA0;not&#xA0;matter what certificate is
used.&#x2003;If&#xA0;not, handle this in&#xA0;the&#xA0;UI and&#xA0;ask users
to&#xA0;enter the&#xA0;required&#xA0;hostname.</li>
</ol>

<p>@ameshkov,&#xA0;can you please validate my thoughts&#xA0;here?</p>

**Comment by ameshkov** [comment]
> The mobileconfig API MUST NOT respond with naked IP addresses or hosts with ports.
> Should we make the tls.server_name parameter required? What about servers that can accept connections targeting multiple hosts?
> Should we ban GETting the mobileconfig API over plain HTTP?

Since it now uses the hostname provided by the client, it does not matter how it was requested.

> Should there be a default host when the client doesn't provide one, or should we be strict and always require one?

Yep, if the hostname parameter is empty, we can use `config.tls.server_name`.
If it's not set either, we should return error 500.

> What about wildcard certificates?

If `config.tls.server_name` is configured, it does not matter what certificate is used.
If it is not configured, we should handle this in the UI and ask the user to enter the desired hostname -- add it to the checklist here: https://github.com/AdguardTeam/AdGuardHome/issues/2075

**Comment by ainar-g** [comment]
<p>The&#xA0;backend and&#xA0;the&#xA0;documentation are&#xA0;mostly
done.&#x2003;@ArtemBaskal, could you please add
the&#xA0;frontend&#xA0;logic?</p>

**Comment by ainar-g** [comment]
<p>I&#xA0;feel like&#xA0;this is done for&#xA0;now.&#x2003;@ameshkov, should we
keep this issue open for&#xA0;future improvements, for&#xA0;example multiple
hosts support, or&#xA0;should we close this issue for&#xA0;now?</p>

**Comment by ameshkov** [comment]
@ainar-g nope, let's close it
