### ISSUE TITLE
Won't handle any dns request for the first boot up

### ISSUE THREAD

**Issue by edlimchoong** [AdguardTeam/AdGuardHome#2360]
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://security.cloudflare-dns.com:443/dns-query', cause: Get "https://security.cloudflare-dns.com:443/dns-query?dns=-3wBAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": context deadline exceeded | 502

Restart the Adguard service will solve the issue. My raspberry pi is connected through Ethernet. I think it's because the internet is not up before the Adguard DNS service start and try to connect to internet.

![image](https://user-images.githubusercontent.com/65737204/100365495-920c1a80-2fcd-11eb-95bc-4c5db03f8a26.png)

**Comment by ainar-g** [comment]
<p>Hi,&#xA0;and&#xA0;thank you for&#xA0;your report!&#x2003;Please tell us,
what's your OS, how&#xA0;did you install <i>AdGuardHome</i> and&#xA0;how&#xA0;do
you start&#xA0;it (that&#xA0;is, per&#xA0;<i>systemd</i>, <i>openrc</i>,
manually, and&#xA0;so&#xA0;on)?</p>

**Comment by edlimchoong** [comment]
This is my current version of OS. I followed the installation guide using the curl command. I just installed it and everything is automatic. It starts by itself every time it boots up without any intervention.
![image](https://user-images.githubusercontent.com/65737204/100519766-fe228600-3167-11eb-8f5e-b93103dbc9d0.png)

**Comment by ainar-g** [comment]
<p>We've&#xA0;had a&#xA0;couple of&#xA0;similar issues reported
in&#xA0;the&#xA0;past: #633, #1033.&#x2003;Do any of&#xA0;the&#xA0;solutions
proposed there, especially setting your IP to&#xA0;static, solve
your&#xA0;issue?</p>

**Comment by edlimchoong** [comment]
Thanks. After setting up static ip address on raspberry pi, it works. Before I just set the static ip address on router, it won't help.

**Comment by edlimchoong** [comment]
I think it won't really solve it permanently. I think maybe my router boot up way too slower than raspberry pi. I have used the crontab to restart the service after 3 minutes for my router to completely boot up. Maybe developer can take a look at it. Let it self check and restart the service? Thanks

**Comment by ainar-g** [comment]
It sounds like an issue with the router, so your solution of restarting _AdGuardHome_ a few minutes after restarting the router sounds reasonable.  We may return to this issue a few months later, but right now we don't have anything better to suggest, sorry.
