### ISSUE TITLE
AdGuard Home & MIPSLE 路由软重启阻塞

### ISSUE THREAD

**Issue by sasalemma** [AdguardTeam/AdGuardHome#2361]
版本：AdGuardHome_linux_mipsle_softfloat.tar.gz 0.104.3 非 LUCI 版本
设备：NEWIFI-D2（NEWIFI-3）7621A MIPSLE 32M ROM 512M RAM 
系统：OPENWRT 19.07.3 
           openwrt-19.07.3-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin

硬件设备，系统文件限制，db数据库不支持放在 ROM ，不支持mmap，所以不能使用 AdGuardHome -s install 成为服务，整个AGH 以root 权限 运行在RAM中。
为了测试，系统只开了 AGH。

RAM 中目录如下：

/tmp/AdGuardHome/AdGuardHome         -----主程序
/tmp/AdGuardHome/AGH.log                    -----日志
/tmp/AdGuardHome/AdGuardHome.yaml -----配置
/tmp/AdGuardHome/data/stats.db
/tmp/AdGuardHome/data/sessionsdb
/tmp/AdGuardHome/data/filters ----> /AdGuardHome/data/filters  ---- ln -s软链接到ROM目录

ROM 中目录如下：

/AdGuardHome/AdGuardHome         -----主程序
/AdGuardHome/AdGuardHome.yaml -----配置
/AdGuardHome/data/stats.db [A]
/AdGuardHome/data/sessionsdb [A]
/AdGuardHome/data/filters [C]

启动方式：

cp /AdGuardHome/AdGuardHome /tmp/AdGuardHome/AdGuardHome
cp /AdGuardHome/AdGuardHome.yaml /tmp/AdGuardHome/AdGuardHome.yaml
cp /AdGuardHome/data/stats.db /tmp/AdGuardHome/data/stats.db
cp /AdGuardHome/data/sessionsdb /tmp/AdGuardHome/data/sessionsdb
ln -s /AdGuardHome/data/filters /tmp/AdGuardHome/data/filters

/var/AdGuardHome/AdGuardHome -l /tmp/AdGuardHome/AGH.log [B]

[A] 使用任务计划，每隔2小时 cp /tmp/AdGuardHome/data/*.db /AdGuardHome/data/*.db 
[B] var 软连接 ----> tmp，tmp没有执行权限，所以用 var 目录启动。
[C] 只是为了拦截文件不需要重新下载，直接放 ROM 了。
AGH正常启动，正常使用。

问题：

1. 使用一段时间后，LUCI 界面中点击重启进行系统重启，没有反应，会自动跳转会原界面。 
2. SSH 中，reboot失效，需要 reboot -nf 重启。
3. reboot -nf 强制重启可行，偶发会导致 LED 灯控制失效，POWER LED 闪烁，其他 LED 灯灭。

复现：

NEWIFI-D1 也是如此。系统 OPENWRT 19.07.3 

现有解决方案：

KILL 掉 AGH 进程，再 reboot ，能成功软重启，相对完美解决战斗。

只是不知道 AGH 那里阻塞了重启进程的执行 ？？ 有老铁知道不 。

**Comment by SkyYkb** [comment]
嗯，朋友，这里是GitHub，并且这个项目的maintainer/contributor貌似没得中国人，所以你还是用英语来的好些。
As for maintainers and contributors, here's the translated version:

> Version：AdGuardHome_linux_mipsle_softfloat.tar.gz 0.104.3 non-LUCI version
Device：NEWIFI-D2（NEWIFI-3）7621A MIPSLE 32M ROM 512M RAM (A router)
OS：OPENWRT 19.07.3
openwrt-19.07.3-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin


> Due to the restrictions of the storage and hardware, `.db` database can't be placed in ROM (aka. disk). There's no mmap support, so it's unable to register AGH as a service with command `AdGuardHome -s install`. AGH runs in RAM (aka. memory) as root.
Beside the OS, there was only AGH running.

> Directories in RAM：

> /tmp/AdGuardHome/AdGuardHome -----binary file
/tmp/AdGuardHome/AGH.log -----log file
/tmp/AdGuardHome/AdGuardHome.yaml -----configuration file
/tmp/AdGuardHome/data/stats.db
/tmp/AdGuardHome/data/sessionsdb
/tmp/AdGuardHome/data/filters ----> /AdGuardHome/data/filters ----soft linked to ROM with `ln -s`

> Directories in ROM：

> /AdGuardHome/AdGuardHome -----binary file
/AdGuardHome/AdGuardHome.yaml -----configuration file
/AdGuardHome/data/stats.db [A]
/AdGuardHome/data/sessionsdb [A]
/AdGuardHome/data/filters [C]

> 启动方式：

> cp /AdGuardHome/AdGuardHome /tmp/AdGuardHome/AdGuardHome
cp /AdGuardHome/AdGuardHome.yaml /tmp/AdGuardHome/AdGuardHome.yaml
cp /AdGuardHome/data/stats.db /tmp/AdGuardHome/data/stats.db
cp /AdGuardHome/data/sessionsdb /tmp/AdGuardHome/data/sessionsdb
ln -s /AdGuardHome/data/filters /tmp/AdGuardHome/data/filters

> /var/AdGuardHome/AdGuardHome -l /tmp/AdGuardHome/AGH.log [B]

> [A] `cp /tmp/AdGuardHome/data/.db /AdGuardHome/data/.db` will run in every 2 hrs.
[B] var is soft linked ----> tmp，tmp doesn’t have execute permission, so start with var directory.
[C] To avoid downloading blocklist files multiple times, it's placed in ROM.
AGH works properly.

> Issue：

> After using it for a period of time, click Restart in the LUCI interface to restart the system. If there is no response, it will automatically jump to the original interface.
In SSH, `reboot` fails and requires `reboot -nf` to restart.
`reboot -nf` forced restart is able to use. Sometimes the LED light control will fail, the POWER LED will flash, and other LED lights will be off.

> The same is true for NEWIFI-D1. OS: OPENWRT 19.07.3

> Existing solutions:

> Kill the AGH process and reboot again can soft restart successfully, which is a relatively perfect solution to the issue.

> Just don't know how AGH is blocking the execution of the restart process? ? Is there anybody knows?

**Comment by sasalemma** [comment]
> 里是GitHub，并且这个项目的maintainer/contributor貌似没得中国人，所以你还是用英语来的好些。
> As for maintainers and contributors, here's the translated version:

感谢，只是在天朝，各类论坛如恩山，ks一类，大多是以易用为主，直接给方案，而基本不会讨论实现方式。而原因也知道，说了实现方法，第二天就有人拿去赚钱了。而路由这块，我也没有找到把玩mips一类的外国论坛，老毛子又是魔改op系，大环境都为arm系，比如梅林，又不像x86系统类，有pcbeta或者墙外MDL，想找点有用的，翻墙google搜中文也大多是CSDN一类抄书的，偶尔简书那边有答案，但还是太少了。要么就是自己翻源码了。所以这个有钓鱼成分，总的来说，表示感谢！应该直接用E文能更快得到答案。

不过这个我觉得不能说是bug了，只是启动方式问题。

一般像这类的二进制的执行程序，默认都会用procd当服务管理，关机重启时必然会调用kill子进程来解决，所以在/etc/init.d/中注册下自启动，以procd服务形式，而非普通的sh脚本启动方式来启动，自然就完美解决战斗了。用非procd管理就得手动kill掉AGH进程，进行重启。

/etc/init.d/AdGuardHome

`#!/bin/sh /etc/rc.common
START=98
USE_PROCD=1
PROG=`/var/AdGuardHome/AdGuardHome -l /tmp/AdGuardHome/AGH.log`
start_service() {
        /bin/sh /AdGuardHome/AdGuardHome.start
	procd_open_instance
	procd_set_param respawn
	procd_set_param command "$PROG"
	procd_close_instance
}
stop_service() {
	/bin/sh /AdGuardHome/AdGuardHome.stop
}
restart() {
	stop
	start
}`

AdGuardHome.start

`mkdir /tmp/AdGuardHome/
touch /tmp/AdGuardHome/AGH.log
cp -f /AdGuardHome/AdGuardHome /tmp/AdGuardHome/AdGuardHome
cp -f /AdGuardHome/AdGuardHome.yaml /tmp/AdGuardHome/AdGuardHome.yaml
cp -f /AdGuardHome/data/stats.db /tmp/AdGuardHome/data/stats.db
cp -f /AdGuardHome/data/sessionsdb /tmp/AdGuardHome/data/sessionsdb
ln -s /AdGuardHome/data/filters /tmp/AdGuardHome/data/filters`

AdGuardHome.stop

`cp -f /tmp/AdGuardHome/AdGuardHome.yaml /AdGuardHome/AdGuardHome.yaml
cp -f /tmp/AdGuardHome/data/stats.db /AdGuardHome/data/stats.db
cp -f /tmp/AdGuardHome/data/sessionsdb /AdGuardHome/data/sessionsdb`


so，大概可以close comment了。

**Comment by SkyYkb** [comment]
是的，很多bin文件的启动方式确实最好是写到init.d里面，比如我对我的aria2和内网穿透服务就是这么处理的。也挺好其实，这么操作在我的系统环境里也可以用systemctl控制。

**Comment by ameshkov** [comment]
> 嗯，朋友，这里是GitHub，并且这个项目的maintainer/contributor貌似没得中国人，所以你还是用英语来的好些。

谢谢，我其实说中文，但水平不太高，所以我很难理解复杂问题的描述。

> 不过这个我觉得不能说是bug了，只是启动方式问题。

对，我也不觉得这是bug。
