### ISSUE TITLE
AdGuardHome only uses stderr for its output

### ISSUE THREAD

**Issue by Belphemur** [AdguardTeam/AdGuardHome#2363]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

When running AdGuardHome I realize that all the log goes to /var/log/AdGuardHome.err, the /var/log/AdGuardHome.out is completly empty all the time.

### Expected Behavior
Use STDOUT for non error behavior, use STDERR for error/crash/problems.

### Actual Behavior
Everything is outputed into STDERR

**Comment by ainar-g** [comment]
<p>This&#xA0;is the&#xA0;intended behaviour.&#x2003;<i>AdGuardHome</i> is
not&#xA0;a&#xA0;file processing utility, so&#xA0;there is really no&#xA0;primary
output.&#x2003;<i>POSIX</i>
<a href="https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_366">defines</a>
<i>Standard&#xA0;Error</i>&#xA0;as:</p>

<blockquote>
<dl>
<dt>Standard Error</dt>
<dd>An output stream usually intended to be used for diagnostic messages.</dd>
</dl>
</blockquote>

<p>And&#xA0;pretty much all of&#xA0;our log messages are&#xA0;diagnostic.</p>

**Comment by Belphemur** [comment]
Your messages are not diagnostic/debugging message but standard output that should be on stdout like:
```
2020/11/27 14:05:17 [info] Service control action: run
2020/11/27 14:05:17 [info] AdGuard Home, version 0.104.3, channel release, arch linux amd64
2020/11/27 14:05:17 [info] AdGuard Home is running as a service
2020/11/27 14:05:17 [info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
2020/11/27 14:05:17 [info] Auth: initialized.  users:1  sessions:5
2020/11/27 14:05:17 [info] number of certs - 2
2020/11/27 14:05:17 [info] got an intermediate cert
2020/11/27 14:05:17 [info] Initialize web module
2020/11/27 14:05:17 [info] AdGuard Home is available on the following addresses:
2020/11/27 14:05:17 [info] Go to http://127.0.0.1:80
2020/11/27 17:05:18 [info] Filter 1 has been updated: 734088 bytes, 38866 rules
2020/11/27 17:05:18 [info] Saving filter 1 contents to: /opt/AdGuardHome/data/filters/1.txt
2020/11/27 17:05:20 [info] Filter 1606425400 has been updated: 69399 bytes, 3560 rules
2020/11/27 17:05:20 [info] Saving filter 1606425400 contents to: /opt/AdGuardHome/data/filters/1606425400.txt
2020/11/27 17:05:20 [info] Filter 1606425402 has been updated: 7489 bytes, 372 rules
2020/11/27 17:05:20 [info] Saving filter 1606425402 contents to: /opt/AdGuardHome/data/filters/1606425402.txt
2020/11/27 17:05:20 [info] Filter 1606425404 has been updated: 150432 bytes, 8850 rules
2020/11/27 17:05:20 [info] Saving filter 1606425404 contents to: /opt/AdGuardHome/data/filters/1606425404.txt
2020/11/27 17:05:20 [info] Filter 1606426036 has been updated: 3598786 bytes, 116986 rules
2020/11/27 17:05:20 [info] Saving filter 1606426036 contents to: /opt/AdGuardHome/data/filters/1606426036.txt
```

stderr is usually kept for debugging/error like:
```
2020/11/27 14:05:17 [info] dns: POST /dns-query?body_hash=fc3f9e09b65a7ce1e47b02b2991f5934eccb5bca444ef8619f541537f636529a: dns server is not running
2020/11/27 14:05:17 [info] dns: GET /dns-query?ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA: dns server is not running
2020/11/27 14:05:17 [info] dns: POST /dns-query?body_hash=44371fd1c7475cd8590c0faa3f100cbf0311fa48fe7460fc9ee02d81274f29df: dns server is not running
2020/11/28 04:51:53 [info] SafeBrowsing: failed: couldn't do a POST request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=iigBAAABAAAAAAAABDc0ZTgENGViZAJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": http2: client connection force closed via ClientConn.Close
```
It doesn't make any sense to mix them all into one log file when you actually have a clear distinction between: Log we know are normal and are supposed to happens and the error representing unexpected behaviour.

# Documentation
* https://stackoverflow.com/questions/3385201/confused-about-stdin-stdout-and-stderr
* https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

I've been administering servers for more than 10 years, your service is the first that I encountered that only uses sderr.
