### ISSUE TITLE
Avoid running AdGuardHome as Root

### ISSUE THREAD

**Issue by Belphemur** [AdguardTeam/AdGuardHome#2364]
### Problem Description
Currently, AdGuardHome is always running as root, which for a program that deal with network call is less than ideal. 

### Proposed Solution
It can be achieved with changing the systemd configuration to give the right capabilities to bind on the default ports (like 53,80,443).

### Alternatives Considered
Running AdGuardHome in a docker to reduce the possible impact in case of security issue.

### Additional Information
Don't think you'll never have security issue, it always happens especially with the number of libraries used by the project that deal with the network.

**Comment by ihipop** [comment]
- `AdGuardHome` is **not** always running as root , It's you that run `AdGuardHome` as root
- Relative issue https://github.com/AdguardTeam/AdGuardHome/issues/1699 https://github.com/AdguardTeam/AdGuardHome/issues/2231

**Comment by ainar-g** [comment]
<p>I&#xA0;agree that&#xA0;always running the&#xA0;whole program
under&#xA0;<code>root</code> is icky, but&#xA0;that's the&#xA0;best we can
do&#xA0;currently.&#x2003;On&#xA0;our wiki we have
a&#xA0;<a href="https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#running-without-superuser">page</a>
that&#xA0;describes how&#xA0;one can run <i>AdGuardHome</i>
without&#xA0;superuser privileges (or&#xA0;<i>systemd</i> for&#xA0;that matter)
on&#xA0;<i>Linux</i>.&#x2003;Some people on&#xA0;<i>Linux</i> also&#xA0;use our
<i>Snap</i> packages for&#xA0;that.</p>

**Comment by Belphemur** [comment]
@ihipop The default install script and even the first run require root. I know I can override the systemd service file, and do a chown on the folder but then the autoupdater will fail as you pointed out in your own issue.

I have other application like syncthing (also a go app) that has no problem running with its user, have its config file generated at first run & autoupdate without ever needing root.

@ainar-g You could implement a system where the app could drop root after it has initialized (if you really need to have root to start). Nginx does that by example.
You have code example for go like:
https://gist.github.com/jsimonetti/e31dced5875903d65677e66e103168cf
https://stackoverflow.com/questions/41248866/golang-dropping-privileges-v1-7

**Comment by ihipop** [comment]
> @ihipop The default install script and even the first run require root. I know I can override the systemd service file, and do a chown on the folder but then the autoupdater will fail as you pointed out in your own issue.

The the first run does not require root see Relative issue #1699 https://github.com/AdguardTeam/AdGuardHome/commit/b43223d30226f70b4616c71429f93a38e89cb163

> 
> @ainar-g You could implement a system where the app could drop root after it has initialized (if you really need to have root to start). Nginx does that by example.


`Nginx` will create `worker process` under none root user, The `master process` is always run under root and also need root permission to start and listen

**Comment by ameshkov** [comment]
There's a simple instruction on how to run AGH without root:
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#running-without-superuser

**Comment by Belphemur** [comment]
@ihipop True enough about Nginx, but the worker are the one handling the request while the master is the one spawning/managing the worker. This mean there isn't any network request handled by a process running as root.

@ameshkov For now it's not a solution until the autoupdate can run without root as said by @ihipop in  #2231 

After #2231 is fixed, I think this should be reopen to redo the installation script to not require root and set correctly a AdGuard user to run everything.

**Comment by l1x** [comment]
New documentation about running AdGuard wo/ root
https://adguard-dns.io/kb/adguard-home/getting-started/#running-without-superuser

**Comment by Kahz3l** [comment]
The documentation is still missing important parts, especially how to run with unprivileged user as a service. Otherwise it will be as root after reboot again and then change AdGuardHome.yaml to root:root

Adjust binary like in the documentation:
```
sudo setcap 'CAP_NET_BIND_SERVICE=+eip CAP_NET_RAW=+eip' ./AdGuardHome
```
Adjust service with correct username and group:
```
sudo nano /etc/systemd/system/AdGuardHome.service
```

```
[Unit]
Description=AdGuard Home: Network-level blocker
ConditionFileIsExecutable=/opt/AdGuardHome/AdGuardHome
After=syslog.target network-online.target
StartLimitIntervalSec=5
StartLimitBurst=10

[Service]
# adjust here
User=<username>
Group=<group>

ExecStart=/opt/AdGuardHome/AdGuardHome -s run
WorkingDirectory=/opt/AdGuardHome

StandardOutput=journal
StandardError=journal

# Allow binding to privileged ports (53, 80, 443)
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

Restart=always
RestartSec=10
EnvironmentFile=-/etc/sysconfig/AdGuardHome

[Install]
WantedBy=multi-user.target
```
Make sure ownership is correct:
```
sudo chown -R username:group /opt/AdGuardHome
```
Reload and start:
```
sudo systemctl daemon-reload
sudo systemctl enable --now AdGuardHome
```
Check status
```
journalctl -u AdGuardHome -e
```

Check if really the correct user is running the service:
```
ps aux | grep AdGuardHome
```


> user  3099236 38.2 15.3 2508344 607464 ?      Ssl  Jun15 300:05 /opt/AdGuardHome/AdGuardHome -s run
