### ISSUE TITLE
Can't Enable DHCP over Mesh Wifi

### ISSUE THREAD

**Issue by crypticraven** [AdguardTeam/AdGuardHome#2368]
* **Version of AdGuard Home server:**
  *  0.104.3
* **How did you setup DNS configuration:**
  * Currently forced through Mesh nodes or statically set on devices in network
* **If it's a router or IoT, please write device model:**
  *  Google WiFi Mesh
* **Operating system and version:**
  *  AGH is running on Raspien (20-Aug-2020)

### Expected Behavior

Would like to enable DHCP on AGH; but with the check; it won't allow it to be enabled because there's another DHCP service running in the network.

### Actual Behavior

Because Google WiFi doesn't let you disable the service. Because this service can't be disabled, the AGH server won't allow me to enable DHCP.

### Additional Information

Other solutions instruct to restrict what Google hands out to a single IP and assign the server you want to use as the reserved address. Then enable the DHCP server services on the AGD server. This would allow for better log tracking within the network and allow user-administrators to isolate which devices are accessing (or trying to access) sites and services.

**Comment by ameshkov** [comment]
@ArtemBaskal make sure that we still allow to enable DHCP even if there's another DHCP found on the network.

@crypticraven the temporary solution would be to enable DHCP in `AdGuardHome.yaml`

**Comment by crypticraven** [comment]
@ameshkov I looked for a way to do this and couldn't find it. There wasn't any documentation or instruction on how to force-enable the service.

**Comment by ameshkov** [comment]
@crypticraven look for DHCP configuration fields there: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

You'll need to set:

* `enabled` to `true`
* `interface_name` to your network interface name
* fill out the `dhcpv4` settings: `gateway_ip`, `subnet_mask`, `range_start`, `range_end`

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/6aacb2105cd5673fa792f84597a607eb8e2cb542
