### ISSUE TITLE
Document DHCP automatic hostnames's behaviour and TLD

### ISSUE THREAD

**Issue by daredevil-ferreira** [AdguardTeam/AdGuardHome#2370]
Even if a machine on my local network is served by AGH with an IP adress via DHCP, when I nslookup this machine I got this message : 

** server can't find <my machine> : NXDOMAIN ==> Message on the AGH server

** server can't find  <my machine> : SERVFAIL ==> Message on a Linux machine I have on the local network

This is frustrating as I can see in the "Best Clients" part of AGH that the machine is listed with the right name and right IP address

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

We'll also need to know the hostname you're trying to resolve.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by daredevil-ferreira** [comment]
in my machine octopicr10s-2, i do a:

pi@octopicr10s-2:~ $ nslookup octopimk3s-2
Server:         192.168.1.5
Address:        192.168.1.5#53

** server can't find octopimk3s-2: NXDOMAIN


the 192.168.1.5 machine helds AdGuardHome.
[adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/5620854/adguard.log)

**Comment by ameshkov** [comment]
> in my machine octopicr10s-2, i do a:

Do you see a client with this hostname in DHCP settings in AdGuard Home?

**Comment by daredevil-ferreira** [comment]
yes, It has 2 interfaces Wifi + Ethernet , one has a fixed adress (fixed by AdGuard), one has a dynamic adress (defined also by AdGuard)
![Capture d’écran du 2020-12-02 11-57-57](https://user-images.githubusercontent.com/46318626/100864116-d8fa8400-3495-11eb-8a16-715aa311804e.png)

**Comment by ameshkov** [comment]
@ainar-g take a look plz, seems to be a regression of https://github.com/AdguardTeam/AdGuardHome/issues/1956

**Comment by ainar-g** [comment]
<p>Works&#xA0;for&#xA0;me on&#xA0;our <i>Pi</i>&#xA0;machine:</p>

<pre>$ nslookup eero.lan</pre>
<pre>Server:&#x09;&#x09;192.168.10.95
Address:&#x09;192.168.10.95#53

Non-authoritative answer:
Name:&#x09;eero.lan
Address: 192.168.0.50</pre>

<p>@daredevil-ferreira,&#xA0;are you sure that&#xA0;you're using
the&#xA0;<code>.lan</code> TLD in&#xA0;your&#xA0;requests?</p>

**Comment by daredevil-ferreira** [comment]
yes, when i add .lan names are resolved

**Comment by ameshkov** [comment]
@ainar-g should we add it to Wiki?

**Comment by JayXon** [comment]
Is it possible to make this configurable? People might prefer other TLDs or not using TLD at all.

**Comment by ainar-g** [comment]
<p>@ameshkov,&#xA0;definitely.&#x2003;I'll relabel this issue
as&#xA0;a&#xA0;docuentation&#xA0;one.</p>

<p>@JayXon,&#xA0;we can make that configurable, especially since&#xA0;it seems
like&#xA0;there isn't really a&#xA0;consensus on&#xA0;what TLD is the&#xA0;best
for&#xA0;such situations.&#x2003;Not&#xA0;using a&#xA0;TLD at&#xA0;all sounds
to&#xA0;me like&#xA0;it could cause confusion, but&#xA0;we'll see.&#x2003;I'll
write a&#xA0;separate issue about&#xA0;that.</p>

**Comment by ainar-g** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP
