### ISSUE TITLE
Assign a resolved IP address to the upstream doh server.

### ISSUE THREAD

**Issue by liuzrui0111** [AdguardTeam/AdGuardHome#2372]
When I use the contents of upstream_dns_file for parsing I have a problem that when setting [/abc.com/]https://xxxx.com/dns-query, the parsing of doh addresses changes. 
That is, the address of xxxx.com may be parsed to an address close to me, or it may be parsed to an address far away from me. So can you set up upstream_dns_file to parse xxxxx.com to make sure the address is the closest one to the server? That is, an override like function to specify the IP address of xxxx.com.

**Comment by ainar-g** [comment]
<p>Wouldn't&#xA0;setting the&#xA0;right IP for&#xA0;the&#xA0;domain in&#xA0;your
<code>/etc/hosts</code> file solve the&#xA0;issue?</p>
