### ISSUE TITLE
Safebrowsing from AdGuard

### ISSUE THREAD

**Issue by michaelb-ae** [AdguardTeam/AdGuardHome#2380]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.3
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Odroid C1
* **Operating system and version:**
  * Ubuntu 20.04 LTS

### Expected Behavior
When activate Safe Browsing mechanism have a little update in latency of response

### Actual Behavior
When i activate the browsing security the median time request go from 100ms (w/o cache and secure dns upstream) to 5 thousand ms (w/o cache and secure dns upstream) and it's very slow.

### Maybe a solution
A potential solution is to generate a local list updated often to reduce the number of request to your API (if technically possible)

### Additional Information
The very same mechanism on Windows 10 version have also a very long response time too

**Comment by ameshkov** [comment]
> When i activate the browsing security the median time request go from 100ms (w/o cache and secure dns upstream) to 5 thousand ms (w/o cache and secure dns upstream) and it's very slow.

This may mean that queries to safebrowsing are blocked.

Check AdGuard Home logs to see what's going on.

> A potential solution is to generate a local list updated often to reduce the number of request to your API (if technically possible)

In some distant perspective this is possible.
