### ISSUE TITLE
The language selected is not applied on the login page

### ISSUE THREAD

**Issue by michaelb-ae** [AdguardTeam/AdGuardHome#2381]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
When i open my adguard home page it reset language in english (on login form) and when i connect myself it revert back to the languages i have choosed

### Proposed Solution
use a cookie to store the language even when not connected

### Alternatives Considered
use the local storage to do so

**Comment by Aikatsui** [comment]
Reset language (present) to english is unnecessary because adguardhome doesn't has or need account registration then it's enough to keep "administrator" user language as default for home page even after introduced #997 (user accounts)

**Comment by michaelb-ae** [comment]
yes but actually the administrator is in french not English, so i don't understand why it reset to English if i'm not logged, why does it not show itself in the languages i have selected (i ask to see if it's a problem on my side or a normal behavior).

**Comment by ameshkov** [comment]
So basically the problem is that the language you chose is not applied on the login page, right?

**Comment by ameshkov** [comment]
@ArtemBaskal take a look plz, it should be relatively easy to fix.

**Comment by michaelb-ae** [comment]
exact, i have checked on the yaml language is "fr" but on login page when i first connect is in English, but on the launch of login page it show in English.
If i'm connecting myself the langage is french so only the login page don't follow this settings.

**Comment by michaelb-ae** [comment]
@ameshkov its seem to be a bug (corrected on this release) of local storage who was wiped on every boot of edge, sorry for the loss of time
