### ISSUE TITLE
Jeuxvideo.com

### ISSUE THREAD

**Issue by muxflash** [AdguardTeam/AdGuardHome#2384]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.3
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Ubuntu 18.04.1

### Expected Behavior

Jeuxvideo.com is not an adult site

### Actual Behavior
All my connection to Jeuxvideo.com are blocked in category adult site

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/58588833/100848686-c1b19b80-3481-11eb-8d3a-c6e3485dc29d.png)

</details>

**Comment by ameshkov** [comment]
Fixed it, thanks for reporting!

**Comment by ameshkov** [comment]
It may take some time for the changes to be applied.
