### ISSUE TITLE
Wiki page about running AGH as a DHCP server

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2386]
<p><a href="https://github.com/AdguardTeam/AdGuardHome/issues/1708#issuecomment-736852712">Context</a>.</p>

<p>We&#xA0;need a&#xA0;wiki page that&#xA0;describes:</p>

<ol>
<li>how&#xA0;to&#xA0;setup and&#xA0;test our DHCP&#xA0;server;</li>
<li>what&#xA0;options are set automatically and based
on&#xA0;which&#xA0;values;</li>
<li>DHCP&#xA0;option formats in&#xA0;the&#xA0;config.</li>
</ol>

**Comment by ameshkov** [comment]
Assigned to a milestone so that we don't forget about it

**Comment by ainar-g** [comment]
<p>In&#xA0;#2388 @loll31 also suggests that&#xA0;we add examples
with&#xA0;common options, like&#xA0;the&#xA0;proxy server option.&#x2003;We
should also add ways to&#xA0;test the&#xA0;configuration
of&#xA0;the&#xA0;server, in&#xA0;case the&#xA0;clients ignore some
of&#xA0;the&#xA0;options sent by&#xA0;servers.</p>

**Comment by ainar-g** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP
