### ISSUE TITLE
Publish proxy 

### ISSUE THREAD

**Issue by loll31** [AdguardTeam/AdGuardHome#2388]
As DNS option 6,  is it possible to manage option 252 for automatic proxy information in AGH configuration file. 

By example, 
```
options:
- 252 text "url"
```

Regards

**Comment by ainar-g** [comment]
<p>There&#xA0;is no&#xA0;<code>text</code> option type currently.&#x2003;You can
try using <code>hex</code>.&#x2003;Example
for&#xA0;<code>socks://proxy.example.org</code>:</p>

<pre>252 hex 736f636b733a2f2f70726f78792e6578616d706c652e6f7267</pre>

<p>To&#xA0;get the&#xA0;hex value on&#xA0;a&#xA0;Unix&#xA0;system:</p>

<pre><code>echo -n 'socks://proxy.example.org' | od -An -tx1 -v | tr -d ' \n'; echo</code></pre>

<p>Or,&#xA0;shorter, with&#xA0;<code>xxd</code>:</p>

<pre><code>echo -n 'socks://proxy.example.org' | xxd -p</code></pre>

**Comment by ainar-g** [comment]
<p>@loll31,&#xA0;did that solution help?&#x2003;Or&#xA0;are you requesting
a&#xA0;new option&#xA0;type?</p>

**Comment by loll31** [comment]
@ainar-g, sorry for delay, i tried with hex format and the information is correctly sent to client. 
In fact, I spent some time since friday to check with iOS device plus automatic proxy config in vain : it does not seem to take care of automatic proxy configuration and i lose my time to resolve it... So i finally checked with wireshark the dhcp packet on PC and it's ok. On the same way, i also used option 15 for domain name (suffix). 
Thanks for support. It's should be interesting to add in Wiki as example the most useful options not available in AGH GUI (dns servers, domain name, private/proxy autodiscovery).
Regards

**Comment by ainar-g** [comment]
<p>We'll&#xA0;definitely add that to&#xA0;the&#xA0;wiki, thanks!&#x2003;I'm
going to&#xA0;close this issue for&#xA0;now.</p>
