### ISSUE TITLE
Конкретный днс в Upstream DNS-серверы для конкретного устройства.  

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2389]
AGH установлен на роутер, все устройства дома подключены к этому роутеру и ходят в интернет через него . Есть необходимость для конкретного устройства (ноутбук), использовать определенный ДНС, не тот который указан в настройках Upstream DNS-серверы, а другой. Как это можно сделать?  В списке "Клиенты (runtime)"  активен только 127.0.0.1 ,  от него идут все запросы. Спасибо .

**Comment by ameshkov** [comment]
Пока не исправится проблему с распознаванием клиентов - никак.

Вероятно у вас роутер сам проксирует через себя DNS-запросы, например там стоит локальный dnsmasq который это делает. Можно этот dnsmasq перевесить на другой порт, а AdGuard Home повесить на 0.0.0.0:53.

Альтернативный вариант - вообще вырубить этот dnsmasq (я предполагаю это он) и включить в DHCP в AdGuard Home.

**Comment by fizsef** [comment]
> Пока не исправится проблему с распознаванием клиентов - никак.
А кто это должен сделать-решить? Есть ли надежда, что будет исправлена.

**Comment by fizsef** [comment]
А кто это должен сделать-решить? Есть ли надежда, что будет исправлена.

**Comment by ameshkov** [comment]
Нет, это же специфическая для вашего роутера ситуация, мы со своей стороны не можем ее решить.
