### ISSUE TITLE
Modify doubleclick responses?

### ISSUE THREAD

**Issue by stefan1983** [AdguardTeam/AdGuardHome#2390]
I am using the latest Adguard Home (Docker) version and wanted to ask if it is possible to modify DNS results containing doubleclick.net!? 

So, for example I go to google.com and search for lets say an Apple Watch, then I get advertisements (shopping) results shown as search result. Clicking on those links will return into something like this:
![image](https://user-images.githubusercontent.com/8542806/100919317-ee919d00-34d9-11eb-9119-a99ee3280420.png)

When looking at the URL, you see that there are actually two URLs combined into one...., first the doubleclick.net and secondly the real URL of the desired store web page.:
`https://ad.doubleclick.net/ddm/clk/320663103;149810799;h;u=ds&sv1=57098582326&sv2=3213871954589068&sv3=5874274374094017378&gclid=Cj0KCQiAk53-BRD0ARIsAJuNhptEiVU-okQcxfIPGlluVtNYxSFMvpV6cMjCmIPU3jf0KGOID2WT-foaAj3eEALw_wcB;%3fhttps://www.saturn.de/de/product/_apple-watch-series-6-gps-40mm-2686134.html?utm_source=google&utm_medium=cpc&utm_campaign=SHP_CMP_Saturn+4+Smart&gclid=Cj0KCQiAk53-BRD0ARIsAJuNhptEiVU-okQcxfIPGlluVtNYxSFMvpV6cMjCmIPU3jf0KGOID2WT-foaAj3eEALw_wcB&gclsrc=aw.ds`

Currently I help myself with copying out the second part of the URL and pasting it into a new browser tab / window (can be very annoying with such long URLs...). 
Therefore it would be nice if Adguard could modify DNS results in a similar way by itself.
That would be very helpful (ease of use).

Thanks

**Comment by ameshkov** [comment]
Unfortunately, this is not possible to modify it this way on the DNS level, we only see the domain name.
