### ISSUE TITLE
Can't update to latest snapshot version

### ISSUE THREAD

**Issue by MehdyDriouech** [AdguardTeam/AdGuardHome#2391]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [No] I am running the latest version : 
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.104.3-SNAPSHOT-641db73a
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 Model B
* **Operating system and version:**
  * RaspbianOS

### Expected Behavior
While a bluebar apear to say there's a new version, there is a button to update.

### Actual Behavior
While a bluebar apear to say there's a new version, i'can't update. I can just see a "learn more" about the new version, but no way to install it

### Screenshots
https://drive.google.com/file/d/1-IZDwFTX-wKGNIHJRYCE8KcHMeBfWvhy/view?usp=sharing
![Capture](https://user-images.githubusercontent.com/28147413/101084495-54e7ef80-35ae-11eb-9353-f7de71b5e87a.PNG)

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Thanks for your help

**Comment by ameshkov** [comment]
Could it be that you're running AGH without root?

**Comment by fupenghao** [comment]
I am having the same Issue.
Prerequisites

Please answer the following questions for yourself before submitting an issue. YOU MAY DELETE THE PREREQUISITES SECTION.

    [No] I am running the latest version :
    [Yes] I checked the documentation and found no answer
    [Yes] I checked to make sure that this issue has not already been filed

Issue Details

    Version of AdGuard Home server:
        v0.104.3-SNAPSHOT-641db73a
    How did you setup DNS configuration:
        (no idea what this means)
    If it's a router or IoT, please write device model:
        Raspberry Pi 3 Model B+
    Operating system and version:
        RaspbianOS raspberrypi 4.19.66-v7+  armv7l

Expected Behavior

While a bluebar apear to say there's a new version, there is a button to update.
Actual Behavior

While a bluebar apear to say there's a new version, i'can't update. I can just see a "learn more" about the new version, but no way to install it

&AGH Service is run with root.

Screenshots
<img width="692" alt="Screen Shot 2020-12-04 at 10 12 52 AM" src="https://user-images.githubusercontent.com/10663021/101112915-4e429200-3619-11eb-8780-9dc3bec4ffee.png">

<img width="1085" alt="Screen Shot 2020-12-04 at 10 13 42 AM" src="https://user-images.githubusercontent.com/10663021/101112982-69150680-3619-11eb-9ac5-980113177844.png">

**Comment by EugeneOne1** [comment]
This should be fixed as of snapshot 8501a85. You will have to upgrade to it manually, sorry about that. Could you please check if our solution fixes the issue for you when the next edge snapshot will be available?

**Comment by MehdyDriouech** [comment]
Thanks for the fix ;)

**Comment by vlitkowski** [comment]
Hello,

how to manually update ? (running on raspbian)

**Comment by fupenghao** [comment]
Hi,
    For me
1. I just download the latest edge version for my raspberry 32-bit
armv7(raspberry 4 is different you will have to check which one you need to
download).
2. Then tar -xvf the downloaded file.
3. Stop the Adguard Service. (Go to the originally Installed Adguard
folder. Then ./AdguardHome -s stop)
4. Backup the originally Adguard file
5. Cp the new Adguard to the originally installed Adguard folder to replace
the old Adguard file.
6. ./AdguardHome -s start
7. Done

2020年12月9日(水) 2:15 vlitkowski <notifications@github.com>:

**Comment by Taewan-P** [comment]
Hello, I had this same issue too, and I am trying to manually update my AGH.
I tried to use the command `curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh` from README.md, but it fails saying, "Failed to install AdGuard Home service: Init already exists: /etc/systemd/system/AdGuardHome.service" as I already installed AGH.
How should I solve this?

**Comment by ameshkov** [comment]
@Taewan-P download the binary for your OS/arch from the releases page: https://github.com/AdguardTeam/AdGuardHome/releases

Unpack it, replace the old binary, restart AdGuard Home.

**Comment by Taewan-P** [comment]
@ameshkov Solved. Thank you!
