### ISSUE TITLE
Make autohost TLDs configurable

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2393]
<p><a href="https://github.com/AdguardTeam/AdGuardHome/issues/2370">Context</a>.</p>

<p>Currently,&#xA0;our autohost feature uses the&#xA0;<code>.lan</code> TLD,
but&#xA0;there
<a href="https://unix.stackexchange.com/a/92517/105635">isn't really a&#xA0;consensus</a>
on&#xA0;what TLD is the&#xA0;best for&#xA0;such situations.&#x2003;So,&#xA0;we
probably need to&#xA0;make it&#xA0;configurable.</p>

**Comment by alexpovel** [comment]
This would be a fantastic feature. Would like this a lot. Glad I found this issue.

As far as "no consensus" goes, I had read [this thread](https://serverfault.com/questions/17255/top-level-domain-domain-suffix-for-private-network). Now I'd like to go the `home.mydomain.com` (or similar) route. `.lan` works fine for now, but as mentioned in those threads, it's not safe until we have proper reserved TLDs for home/private/internal use (`.lan` is currently nothing official AFAIK: not a global TLD but also not explicitly reserved for internal use).

I hope this would be a [YAML config option](https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#config-4)? Would prefer that over a GUI approach.

**Comment by ainar-g** [comment]
@alexpovel, yeah that's the piece.  You could try, but be aware that PRs are unfortunately taking a lot of time to get reviewed right now, and the code is also a bit… macaroney with the configuration.

**Comment by Lenart12** [comment]
Changing dhcp option in the config files under dhcp->dhcpv4->options by setting `- 15 hex 6c616e` (setting dhcp domain name to `lan`) seems to make local rewrites like host1.lan work, however it would still be nice if we could change that via gui or in the configs to something other than lan.

**Comment by alexpovel** [comment]
@Lenart12 , `.lan` is the current, hard-coded default, so it should definitely work, see also [this earlier comment](https://github.com/AdguardTeam/AdGuardHome/issues/2393#issuecomment-763049432). It also works without doing anything.

The interesting part would be if *other* values work, *or* what it says in

```bash
cat /var/lib/dhcp/dhclient.*leases
```

on one of your machines that received a DHCP lease with that `- 15 hex 6c616e` option set. In my network, it doesn't mention `lan` anywhere, because I *haven't* set that option - so all as expected. Does it show a value there for you? That would make things different.

**Comment by ainar-g** [comment]
This is implemented as of snapshot 3764c1d.  The Wiki is also updated.  Please feel free to file new issues if you have any problems!

**Comment by alexpovel** [comment]
Where in the wiki? I was only able to find [this entry](https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#automatic-hosts) which references back this issue as a WIP.

**Comment by ainar-g** [comment]
@alexpovel, it's on the [“Configuration” page], in `dns`→Other setings→`autohost_tld`.  (The page really needs a proper refactoring, to be honest.)  But you are correct, the DHCP page needs to be updated as well.  We're going to update it soon™.

[“Configuration” page]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
