### ISSUE TITLE
PXE Server Configuration Support

### ISSUE THREAD

**Issue by FM1337** [AdguardTeam/AdGuardHome#2395]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I want to use Fog on the network to do PXE booting, but as I'm using adguard for the dhcp server, there doesn't appear to be anyway to configure the settings I require for actually getting it to work.

### Proposed Solution
Adding support for pxe boot, I'm not sure if adguard is using dnsmasq or anything that would allow me to actually specify things like ``next-server`` and ``filename``

### Alternatives Considered
Moving back to pi-hole as a recent reddit poster said they had luck doing it on there using dnsmasq

### Additional Information
For those not familar with Fog: https://fogproject.org/

**Comment by FM1337** [comment]
Edit: I've read through the wiki and tried to configure options 66 (tftp server) and 67 (pxe file) it times out on the tftp server and I can confirm the issue is happening on adguard's side. Any suggestions?

**Comment by FM1337** [comment]
Turns out I'm an idiot and ProxyDHCP was the answer

**Comment by centralhardware** [comment]
>  ProxyDHCP was the answer

i have same problem  and i don't understand how to resolve problem, can you write in more detail how you solve this problem.

**Comment by matefits** [comment]
Same problem here

**Comment by neoestremi** [comment]
Is it possible to have your final dhcp configuration ?
I tried adding options :
66 hex [hex translated IP of server]
67 text [bootfile].efi (tried with hex too)

With a TFTP client, I can get the [bootfile].efi on my computer without problem, so the PXE server shouldn't be the problem, its IP is fixed (by configuration, not in DHCP rule), but when I PXE boot, it fails.

**Comment by djismgaming** [comment]
> Turns out I'm an idiot and ProxyDHCP was the answer

@FM1337 are you able to give us a little more detail? Was this a container you used to address the need for this to work?
Any input will be greatly appreciated!

**Comment by andekande** [comment]
In short, a DHCP proxy is an additional service that just replies to clients requesting pxe information.
This can be achieved by dnsmasq for example, so you don't need to configure AdGuard's DHCP service at all and in consequence also avoid that suddenly ALL clients boot from pxe (that have it enabled in Bios).
Setup: https://manski.net/tags/proxydhcp/

> The PXE Proxy DHCP server behaves much like a DHCP server by listening for ordinary DHCP client traffic and responding to certain client requests. However, unlike the DHCP server, the PXE Proxy DHCP server does not administer network addresses, and it only responds to clients that identify themselves as PXE clients.
The responses given by the PXE Proxy DHCP server contain the mechanism by which the client locates the boot servers or the network addresses and descriptions of the supported, compatible boot servers.

**Comment by realmax44** [comment]
Hallo @FM1337 Can you perhaps describe in a little more detail what exactly you did? I just can't get it to work. My setup: 1. Raspi 3b+ with DietPi, Adguard Home (DNS and DHCP) and Unbound 2. Unraid Server with Debian VM running iVentoy. 

I would be very happy about an answer!
