### ISSUE TITLE
Regional list for Spanish related domains.

### ISSUE THREAD

**Issue by KaoDome** [AdguardTeam/AdGuardHome#2398]
### Prerequisites

[🗸] I am running the latest version
[🗸] I checked the documentation and found no answer
[🗸] I checked to make sure that this issue has not already been filed

### Problem Description

At this moment there are vetted lists for different languages but Spanish isn't one of them.

### Proposed Solution

AdGuard (extension) offers a filter for Spanish & Portuguese in the language-specific section that seems to be curated by team members, while there are rules in there that don't apply there are also DNS level queries that could be added to a list focusing on those languages.

### Alternatives Considered

Maybe the EasyList for Spanish that AdBlock Plus uses which could be used as a source instead, but ideally since there's already one under the AdGuard umbrella I think it'd be preferable to use that one.

### Additional Information

_Off-topic, but remember to remove the MalwareDomainList.com security list on the next update as it's currently unmaintained (I was about to write a bug report for it but it's been brought to your attention already)._

**Comment by ameshkov** [comment]
@KaoDome there's a separate topic for discussing filter lists: #1913 

Regarding Spanish, domains from AdGuard Spanish/Portuguese are already included in the AdGuard DNS filter: https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json#L99
