### ISSUE TITLE
Separate SafeSearch from search browsing and youtube.

### ISSUE THREAD

**Issue by michaelb-ae** [AdguardTeam/AdGuardHome#2399]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Actually i use a lot the safe search of DNS but YouTube have the shittiest safe search i have seen in my life, with many false positive and legitimate video are blocked without any reason because of their bot.

### Proposed Solution

Add an option only for the YouTube (and other video website if there's are) safe search and separate it completely from the safe search of search engine.

### Additional Information

None.

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdGuardHome/issues/1163

**Comment by michaelb-ae** [comment]
oh sorry i have reed device instead of service when i have searched :/

**Comment by ameshkov** [comment]
No worries:)
