### ISSUE TITLE
AdGuardHome.yaml being owned by root on Linux, makes it hard to edit from most GUI file explorers

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#2400]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.104.3)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.3 ARM64
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 4GB
* **Operating system and version:**
  * Raspberry Pi OS 64-bit Buster-Backports

### Expected Behavior
The `AdGuardHome.yaml` configuration file can be opened through practically all GUI file managers, e.g. PCManFM.

### Actual Behavior

So, there's a background story to this one.

I downloaded AdGuard Home [in TAR.GZ form from GitHub](https://github.com/AdguardTeam/AdGuardHome/releases), which are downloaded to `/tmp`. I extract them into a new folder in `/home`, because I presumed that's what Linux users are supposed to do with things they've downloaded for long-term use. The rest of the setup goes well, except I had to move the files from `/home/pi/AdGuard Home` to `/home/pi/AdGuardHome` after the initial installation because that space somehow caused the service to fail to start up on boot.

Flash forward a couple months after I last reinstalled AdGuard Home, and I begin to notice that every file and folder that resulted from packing out the original TAR.GZ, are being owned by root. This means that the vast majority of GUI file managers (in my case PCManFM) are completely unable to edit or change any of the AdGuard Home files, most crucially `AdGuardHome.yaml`, since the managers offer no working way to change file permissions despite claiming the ability to do so.

After some guidance from a Linux expert I know on Discord, I ran `sudo chmod 777 -R /home/pi/AdGuardHome` to make it easier to handle AdGuard Home from PCManFM, but I doubt that could possibly be seen as the intended way to do this, so I'll ask a few questions to be sure:

1) Is the files that are created after running the installation process for the downloaded TAR.GZ from GitHub, actually supposed to be owned by root?
2) Are there any officially recommended directories on Linux that AdGuard Home is intended by you guys to be installed in (e.g. tmp, home, etc, usr, etc.)?

### Screenshots

I don't think screenshots would explain the matter sufficiently, unless I spent 25min making a GIF of it.

### Additional Information

I was very sleepy at the time I wrote this report, but I felt I was able to make the explanation make much more sense than I had feared I would.

Doing additional research after I initially wrote this report, it seems like the TAR.GZ itself and the extracted executable is owned by `pi` instead of `root`, which makes me it even more strange how they became owned by `root` post-installation.

**Comment by ameshkov** [comment]
> Is the files that are created after running the installation process for the downloaded TAR.GZ from GitHub, actually supposed to be owned by root?

Well, it's natural for a service that runs with root privileges to do this.

It's possible to run AGH without root, but that won't be easy if you're not an expert at Linux. You'll need to grant it [necessary capabilities](https://github.com/adguardteam/adguardhome/wiki/Getting-Started#running-without-superuser) and modify the service file so that it was launched under a non-root user. Maybe even create this user yourself.

> Are there any officially recommended directories on Linux that AdGuard Home is intended by you guys to be installed in (e.g. tmp, home, etc, usr, etc.)?

I prefer installing it to `/opt` as our [install script](https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh) does.
