### ISSUE TITLE
Add services who are on nextdns but not on your

### ISSUE THREAD

**Issue by Macqael** [AdguardTeam/AdGuardHome#2401]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Is this possible to add these services to be blocked by switch (list of domain on nextdns repo)

- 9gag
- blizzard
- dailymotion
- disney +
- hulu
- imgur
- leagueoflegend
- pinterest
- roblox
- spotify
- telegram
- tinder
- vimeo
- zoom

### Proposed Solution

Add them in the services "zone"

### Alternatives Considered

N/A.

### Additional Information

https://github.com/nextdns/metadata/tree/master/parentalcontrol/services

**Comment by uNitrous** [comment]
🧑‍🎄

**Comment by DandelionSprout** [comment]
Making a list for Vimeo should be reasonably easy:
```
||vimeo.com^
||vimeocdn.com^
*vod-adaptive.akamaized.com^
```

Pinterest:
```
||pinterest.TLD
||pinimg.com^
```

Imgur:
```
||imgur.com^
```

Dailymotion:
```
||dailymotion.com^
||dm-event.net^
||dmcdn.net^
```

**Comment by uNitrous** [comment]
@724e0c2 not all will be added?

Some suggestions: (big guys missing)
- Mail: gmail, hotmail, yahoo (alternative to mail.ru)
- Chat: kik, icq, yandex, jio, imo, google duo
- Conference: microsoft teams (alternative to zoom), slack (alternative to discord)
- News: bbc, wallstreet (alternative to dailymirror)
