### ISSUE TITLE
The Slow response to queries ans my Web panel loading is very slow

### ISSUE THREAD

**Issue by Suansuan-Keai** [AdguardTeam/AdGuardHome#2402]
Hi!
Thank you for your hard works on this helpful project at first !
But I have some serious problems what I cannot slove by myself:
I don't know why cause it to be so slowly.
I can't visit my web panel and maybe it will taken for seconds to get a result,even longer.
I've checked my server's hardware resource, there is a lot of hardware resources are available.
It runs on CentOS 8,with 2Gb RAM and a singal-core CPU.(It can meet the requirements,I think.)
Maybe it's not cause by the poor performance.
I can provide it's log file(s) if you need it to catch the problem , could you help me?
Thanks in advance !

**Comment by Suansuan-Keai** [comment]
Btw,It will be smooth and fast after restarting the service for a while.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

We'll also need to know when exactly the issue happened.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by Suansuan-Keai** [comment]
Oh,I got it.
I will post my logfile when the problem recur.

**Comment by Suansuan-Keai** [comment]
> To troubleshoot this issue we need to see AdGuard Home logs.
> 
> We'll also need to know when exactly the issue happened.
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

Oh,I got it.
I will post my logfile when the problem recur.

**Comment by Suansuan-Keai** [comment]
[debug.zip](https://github.com/AdguardTeam/AdGuardHome/files/5677272/debug.zip)

@ameshkov 
Here is my log file.

**Comment by Suansuan-Keai** [comment]
It's so big when the problem recur.

**Comment by ameshkov** [comment]
It seems `ulimit` on your server is too low: `accept4: too many open files; retrying in 1s`, you need to increase it.

https://gist.github.com/somandubey/52bff8c7cc8639292629

**Comment by Suansuan-Keai** [comment]
@ameshkov Thx for your reply.
Could you help me check did I increase it successfully?
`
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7814
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
`

**Comment by ameshkov** [comment]
Seems so.

`ulimit -n` -- this command outputs the current open files limit.
