### ISSUE TITLE
Не очищается журнал

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2404]
В настройках "Сохранение журнала запросов" выбран 24 часа. Но в журнал не очищается после 24 часов, видны записи и ранее 24 часов. Соответственно разрастается файл "querylog.json".  Как сделать, чтобы журнал очищался после выбранного периода?
![1](https://user-images.githubusercontent.com/74646605/101455588-e0150c80-3943-11eb-94aa-9fe17a0a3790.jpg)

**Comment by ainar-g** [comment]
<p>Добрый&#xA0;день.&#x2003;Что значит в&#xA0;вашем сообщении «видны
записи»?&#x2003;После 24 часов предыдущий файл переименовывается
в&#xA0;<code>querylog.json.1</code>, по аналогии со многими лог-файлами
в&#xA0;<i>Unix</i>, а&#xA0;при запросе страницы логов он&#xA0;считывается.</p>

**Comment by fizsef** [comment]
Опцию "Сохранение журнала  24 часа" я понимал как, что журнал сохранит записи только последних  24 часов, а не как, что все будет храниться, только в разбивке по 24 часа по разным файлам. Так это нужно чуть понятнее описать в комментарии к настройке. Спс.

**Comment by fizsef** [comment]
А нет никакой настройки, чтобы автоматически удалялись файлы за выбранный период, или по истечении какого периода?

**Comment by ameshkov** [comment]
Именно так и происходит. Когда приходит время, старый журнал перезаписывает то, что было в `querylog.json.1`
