### ISSUE TITLE
Refactor HTTP handling

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2405]
<p>Currently,&#xA0;the&#xA0;HTTP API logic is intertwined
with&#xA0;the&#xA0;rest of&#xA0;our logic.&#x2003;This is obviously suboptimal
and&#xA0;has already led to&#xA0;inflated development times and&#xA0;complexity
in&#xA0;refactoring and&#xA0;testing.&#x2003;Thus, move all HTTP logic
into&#xA0;a&#xA0;new package (<code>aghhttp</code>?
<code>httpapi</code>?).&#x2003;Along&#xA0;the&#xA0;way, refactor as&#xA0;many
global variables as&#xA0;possible.</p>

<p>This&#xA0;is a&#xA0;large issue, so&#xA0;perhaps it's better to&#xA0;review
it in&#xA0;smaller&#xA0;parts.</p>

**Comment by ameshkov** [comment]
Duplicates #2554
