### ISSUE TITLE
No warning Page 

### ISSUE THREAD

**Issue by s3vdev** [AdguardTeam/AdGuardHome#2408]
Today i just installed AdGuard Home on my Raspberry Pi 3b+. Everything works great and maybe little faster than my Pi-hole. But i missing the Warning Page if any pages gets blocked by AdGuard Home. Its showing me only a Text in German that says: 

"Die Website ist nicht erreichbar
Prüfen Sie, ob "ichnaea.netflix.com" einen Tippfehler enthält.
DNS_PROBE_FINISHED_NXDOMAIN"

Is there no warning page like in the Docs?!?

**Comment by ibksturm** [comment]
Salü

Deutsch: Du kannst in den Systemeinstellungen irgendwo tief drin (bin grad am Handy und ned am Rechner zuhause) Einstellen, was als Errormeldung zurück gegeben werden soll. Eine Mögliche Lösung ist, dass du dir auf deinen Pi ein Nginx oder sonstwas Webserver draufhaut, da dir ne Landingpage bastelst und dann in der DNS Antwort darauf verlinkst

Ist das soweit verständlich (quick and Dirty)? 

Andi

**Comment by ibksturm** [comment]
![09A52344-4A56-497D-BBAC-08FEC0904F2F](https://user-images.githubusercontent.com/35167101/101680333-d46b3800-3a60-11eb-86cf-acdb5a5ead06.png)


gefunden

**Comment by s3vdev** [comment]
Hey Andy 

lieben Dank :) das ist glaube ich eine gute Lösung. Dachte vor dem Umstieg von Pi-Hole auf AdGuard, das diese "Seiten" bereits dabei wären, da sie ja in der Doku exakt so beworben werden. Aber dieser Weg ist min. genau so gut.

Dankeschön 😀

**Comment by ibksturm** [comment]
Salü

Andi mit i bitte ;)

Vorteil ist, dass du den nginx auch als Loadbalancer zusätzlich verwenden kannst, falls du da weitere Dienste laufen hast. Schau mal bei meinem Git nach, falls du Inspiration brauchst

**Comment by ibksturm** [comment]
> Hey Andy
> 
> lieben Dank :) das ist glaube ich eine gute Lösung. Dachte vor dem Umstieg von Pi-Hole auf AdGuard, das diese "Seiten" bereits dabei wären, da sie ja in der Doku exakt so beworben werden. Aber dieser Weg ist min. genau so gut.
> 
> Dankeschön 😀

b) die Landingpage funktioniert, wenn du direkt die AGH DNS Server im Router verwendest, die Leiten dass dann via CNAME Rewrite auf Ihre Landingpage um

**Comment by s3vdev** [comment]
Hey Andi,

schaue mit dein repository gleich an :) du meinst mit AGH DNS diese default DNS server von https://adguard.com/de/adguard-dns/overview.html in die Fritz!Box unter Zugangsdaten => DNS-Server? Dort stehen gerade die lokalen IPs vom Raspberry Pi (AdGuard Home) drin. 

Könnte unter Heimnetz => Netzwerk => Netzwerkeinstellungen => IPv4-Konfiguration noch einen lokalen DNS Server einstellen welcher gerade auf die FritzBox selbst lautet.

**Comment by ameshkov** [comment]
Hi all. As I can see, the original question is already answered so I am closing the issue.
