### ISSUE TITLE
NotFilteredError

### ISSUE THREAD

**Issue by Mytonn** [AdguardTeam/AdGuardHome#2409]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

Upgraded to v0.105.0-beta.1 from 0.104.3 via Web Panel. There are named "NotFilteredError" entries on query log page for blocked queries.

* **Version of AdGuard Home server:**
v0.105.0-beta.1

* **Operating system and version:**
Ubuntu 20.04

### Expected Behavior
Should be there are named "Blocked" entries on query log page for blocked queries.

### Screenshots

https://imgur.com/QAI1B2K

**Comment by mgcWil** [comment]
Hello, I see the same thing, on a snapshot update to the last one, v0.105.0-SNAPSHOT-ef178610.
And I also notice that "DNS rewitres" appear as "Blocked service".

**Comment by woboo110** [comment]
同样情况

**Comment by gerroon** [comment]
I have the same issue with 0.105.0-beta.1

**Comment by uservictor** [comment]
Get same issue on 0.105.0-beta.1

In Query Log there are entry **NotFilteredError** for blocked sites and no color indication like green and red for Passed and Blocked query.

It worked on 0.104.3

**Comment by fr45er** [comment]
same issue here also

**Comment by ameshkov** [comment]
The issue is resolved in the edge channel, I am not sure why it's still open.

**Comment by gerroon** [comment]
How do we get that version?

**Comment by uservictor** [comment]
@gerroon 
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions
@ameshkov 
thanks for answear and fix
