### ISSUE TITLE
ipset is not being set.

### ISSUE THREAD

**Issue by k1ng440** [AdguardTeam/AdGuardHome#2411]
### Prerequisites
`Ipset add` is not being called

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
ipset discovery has found about 40 domains on startup but IP addresses are not being sent to ipset

* **Version of AdGuard Home server:**
  * 0.104.3
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Ubuntu VM on UNRAID
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior
ipset should be called every time an IP address found for a certain domain

### Actual Behavior
ipset is not being called at all

### Additional Information

```
dns:
  ipset:
  - netflix.com,netflix.com.edgesuite.net,nflximg.com.edgesuite.net/netflix
  - ext-twitch.tv/twitch
  - jtvnw.net/twitch
  - ttvnw.net/twitch
  - twitch.tv/twitch
  - twitchcdn.net/twitch
  - twitchsvc.net/twitch
  - akadns.net/akamai
  - akagtm.org/akamai
  - akam.net/akamai
  - akamai.com/akamai
  - akamai.net/akamai
  - akamaiedge.net/akamai
  - akamaihd.net/akamai
  - akamaistream.net/akamai
  - akamaitech.net/akamai
  - akamaitechnologies.com/akamai
  - akamaitechnologies.fr/akamai
  - akamaized.net/akamai
  - edgekey.net/akamai
  - edgesuite.net/akamai
```

**Comment by EugeneOne1** [comment]
Unfortunately, we can't reproduce your issue. Please try the following:
1. Make sure that `ipset` is installed and the appropriate lists are created manually;
1. Install AdGuardHome from the [edge channel](https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions) and try to reproduce the issue.

If none of the above helped, please run AdGuardHome with `v` flag (or set `verbose` field to `true` in configuration file) and attach output logs to your response.
