### ISSUE TITLE
Android 11: long (infinite?) delay for every request. 

### ISSUE THREAD

**Issue by zilexa** [AdguardTeam/AdGuardHome#2413]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

AGH 0.104.3 running bare/natively on Ubuntu Budgie 20.04.1.
Intel based system (Core i3-9100, 32GB ECC).
Unbound in Docker but testing only with 1.1.1.1 (excluding Unbound as a cause).
On my router (Mikrotik hEX POE), the DNS server and the DHCP DNS address are both set to the IP address of the host pc (192.168.88.2).

### Expected Behavior
All my devices: Windows work laptops, iPad, two Android 10 Pixel 1 smartphones work perfectly fine. 

Android 11 Pixel 4a should work fine after:
- disabling MAC randomisation
- disabling Google's own DNS settings
- disabling power options that disable WiFi when screen is off.

The Pixel 4a receives an IP from my router and I see in the WiFi settings, my AGH host pc IP as the DNS server, as expected.
I would expect this device to work fine with AGH, just like all other devices.

### Actual Behavior
On the Android 11/Pixel 4a device: Every site I open (Firefox for Android latest version and Kiwi Chromium browser) and every app I open takes up to 15-30 seconds, sometimes a minute or longer to load. It is actually not even loading anything yet, clearly just waiting for a response. Some apps just load forever. I can't use most banking and shopping apps. It just takes forever.
Tested AGH settings, none of these issues solved it:
- With and without protection. 
- With only default blocklist or only OISD. 
- Rebooting AGH each time after changing the settings. 

Workarounds that do solve it (=not using AGH):
A) The moment I change DNS on my phone (changing the WiFi settings of the connected network to static IP/gateway/DNS) to 1.1.1.1, the issue is solved. 
B) Leave it to DHCP but change the DNS server in my router to 1.1.1.1, the issue is also solved.

### Additional Information
I have this issue since I bought the phone a month ago. I have been testing extensively, postponing a bug report because I couldn't believe/understand the issue. But now it is clear there is nothing I can do to solve it. Unfortunately the phone came with Android 11 preinstalled.
Currently I simply leave 1.1.1.1 as DNS in the WiFi settings (forcing static IP/gateway/DNS). All other devices still get the AGH host pc IP address as DNS server via my router.

**Comment by pendie** [comment]
I use the mikrotik ccr1009 also everything goes normally which is important your nat settings

**Comment by zilexa** [comment]
@pendie do you also tried Pixel 4a? 
Because this issue is really limited to this phone, it's the only v11 phone I have.

I can share my NAT settings of course, but it is the default of Mikrotik RouterOS. No changes. I'll post it later.

**Comment by pendie** [comment]
> 
> 
> @pendie do you also tried Pixel 4a?
> Because this issue is really limited to this phone, it's the only v11 phone I have.
> 
> I can share my NAT settings of course, but it is the default of Mikrotik RouterOS. No changes. I'll post it later.

im use Xiaomi Mi 10 Android 11
the point is your nat settings 
/ip firewall nat
add action=redirect chain=dstnat comment=DNS disabled=yes dst-port=53 protocol=tcp to-ports=53
add action=redirect chain=dstnat comment=DNS disabled=yes dst-port=53 protocol=udp to-ports=53
src address except your ip adguard

**Comment by zilexa** [comment]
Thanks for the tip! I am definitely going to try this asap (tomorrow morning).
Do you have any idea why this would be necessary for Android 11?

**Comment by zilexa** [comment]
@pendie 
Sorry I am not an expert with RouterOS. This part I understand: 
```
/ip firewall nat
add action=redirect chain=dstnat comment=DNS disabled=yes dst-port=53 protocol=tcp to-ports=53
add action=redirect chain=dstnat comment=DNS disabled=yes dst-port=53 protocol=udp to-ports=53
```
But how do you apply this:  `src address except your ip adguard`
Do you add an exception within those 2 `redirect` rules, or is this a 3rd rule?

**Comment by ameshkov** [comment]
1. Do you see queries from your device in the AdGuard Home query log?
2. What happens you install "Termux" or some app like that and try executing a command like this: `nslookup example.org AGHIP` (where AGHIP is the IP address of your AGH)

**Comment by zilexa** [comment]
@ameshkov 
1. yes I see some queries in AGH.
2. Even with 1.1.1.1 I have the same issue as with AGHIP. When I execute `nslookup at5.nl 1.1.1.1` six times, 3 times I wait 20-30 seconds. Once even got connection time out. 2 times I got an immediate response.

@pendie could you please get back to me on my questions in my previous post?

**Comment by ameshkov** [comment]
> Even with 1.1.1.1 I have the same issue as with AGHIP. When I execute nslookup at5.nl 1.1.1.1 six times, 3 times I wait 20-30 seconds. Once even got connection time out. 2 times I got an immediate response.

Makes me think that there's some problem with the device settings, and not with AGH.
