### ISSUE TITLE
Support DNS-over-QUIC in mobileconfig and setup guide

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2418]
<p>The&#xA0;<i>mobileconfig</i> HTTP API must support <i>DNS-over-QUIC</i>, and
the <i>DNS Privacy</i> tab on the <i>Setup guide</i> page must also show
a&#xA0;link to the new&#xA0;API.</p>

**Comment by ameshkov** [comment]
We won't be able to support it in `mobileconfig` since iOS does not support it.

Regarding Setup Guide, it seems we already print it there:
https://uploads.adguard.com/up04_AdGuard_Home_52mlv.png
