### ISSUE TITLE
При отключении фильтров, файлы фильтров не удаляются

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2421]
При отключении фильтров файлы этих фильтров остаются и продолжают занимать место в памяти. Было бы логично, если при отключении фильтра файлы соответствующие файлы удалялись сразу.

**Comment by ameshkov** [comment]
На самом деле не очень логично, потом для включения придется заново все выкачивать.

**Comment by fizsef** [comment]
Но не факт, что после отключения их заново включат когда либо. Но если включат, то закачаются снова, свежие.

**Comment by ameshkov** [comment]
Я элементарно могу случайно выключить, а ждать потом пока многомегабайтный фильтр скачается точно не хотелось бы

**Comment by fizsef** [comment]
Ну я специально выключил, но не знаю где хранятся файлы, как мне их удалить? Есть у вас в веб интерфейсе такая возможность? Так нет вроде. Или должна быть такая возможность из веб , или должны удалиться  при отключении.

**Comment by ameshkov** [comment]
Зачем, удаляются они при удалении фильтра

**Comment by fizsef** [comment]
Ну, если памяти много и есть возможность хранить ненужные данные в памяти роутера, возможно вы и правы. Но поверьте, много кому места не хватает и каждый метр на счету.

**Comment by ameshkov** [comment]
Ну тогда просто удаляйте ненужные фильтры
