### ISSUE TITLE
Блокировка рекламы яндекс

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2422]
Какими фильтрами блокировать рекламу яндекс? Например вот эту, на главной странице 
![1](https://user-images.githubusercontent.com/74646605/101981403-a6af0a80-3c7d-11eb-81cc-7a170c34c864.jpg)

**Comment by ameshkov** [comment]
В AdGuard Home - никак, маловато возможностей.

Тут вам уже стандартный AdGuard для Windows/Mac/Android нужен.
