### ISSUE TITLE
Как не записывать в лог файл блокировки по конкретному пользовательскому правилу

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2424]
Некоторые клиенты, например у меня это телевизор, отправляет огромное количество запросов, в каждую секунду по запросу. И все это записывается в лог. И лог файл распух и стал огромным. Как настроить, чтобы выборочно записывать конкретного клиента в файл лог, по правилу клиента. Такой настройки очень не хватает. 
![1](https://user-images.githubusercontent.com/74646605/102006739-7a09fa00-3d34-11eb-8daf-07a5ef665a0c.jpg)

**Comment by Aikatsui** [comment]
Решение этой проблемы --> https://github.com/AdguardTeam/AdGuardHome/issues/594#issuecomment-469129412 https://github.com/AdguardTeam/AdGuardHome/issues/1164

**Comment by ameshkov** [comment]
Пока что никак, но подобные пожелания у нас уже есть.

Вообще рекомендую в `AdGuardHome.yaml` попробовать поднять значение `blocked_response_ttl` -- тогда клиент будет реже перезапрашивать заблокированный домен.
