### ISSUE TITLE
Remove "280 blocker adblock domain lists" from the built-in filters list

### ISSUE THREAD

**Issue by Srgr0** [AdguardTeam/AdGuardHome#2427]
"280blocker adblock domain lists" is listed in the block list of AdGuard Home, but the link is broken due to the url change by the filter creator. Regarding this change, the filter creator says that "many users use it without checking the contents of the file and the license". Therefore, it is considered that this filter should not be included in the built-in filter list where the filter can be used just one click.
https://280blocker.net/blog/20201019/2620/

**Comment by Aikatsui** [comment]
> @Srgr0 Therefore, it is considered that this filter should not be included in the built-in filter list where the filter can be used just one click.

>https://280blocker.net/blog/20201019/2620/
AdguardHomeを利用されている方はAdGuardHome.yamlの設定ファイルに直接日付入りURLを書き込んでサービスを再起動すれば自動化できるかと思います。その他のOSもおそらくある程度自動化できるかと思います。

**Comment by ameshkov** [comment]
Well, I am not ready to keep a list in "Vetted" if setting it up is THAT complicated.

**Comment by Srgr0** [comment]
@Aikatsui 
I know it is technically possible.
Filter creators are concerned that each user will use the filter without knowing the "filter licenses and restrictions (prohibition of commercial use, etc.)". Therefore, the current style that allows you to use the filter with one click without checking the license etc. is not recommended.
Before each user use the filter, it is necessary to be able to confirm the license etc. of the filter in some way.

**Comment by badmojr** [comment]
https://github.com/FutaGuard/FutaFilter/pull/22

Here's a mirror.
