### ISSUE TITLE
"Blocked" client is not marked as "blocked" in some cases

### ISSUE THREAD

**Issue by PassWall-OpenWrt** [AdguardTeam/AdGuardHome#2428]
AdGuardHome_windows_amd64
Version: 
0.104.3
我在仪表盘，客户端排行中点击“拦截”拦截某个客户端。点击过两次或者两次以上，在“设置>DNS设置>访问设置>不允许的客户端”列表中就会出现同一个 ip 两次或者两次以上。
In "Dashboard>Top clients" klick "block" to a client twice or more ,the IP address will list the multiple same IP in "Setting
>DNSsetting>DNS server configuration>Disallowed clients" .

我希望的效果是: 在客户端排行列表里对已经被拦截的客户端有作标示，例如在后面加上 “(blocked)”  ；或者直接 “拦截” 的按钮变成 “放行” ,因为已经 “拦截" 的客户端 已经不需要再做 “拦截” 了。然后 “不允许的客户端列表” 应当做一个判断，当手动添加 IP 有重复就提示出现重复的 IP 。

**Comment by ameshkov** [comment]
很奇怪，我不能重复这个错误。

客户端排行中点击“拦截”的时候，你该看对话窗口：
![image](https://user-images.githubusercontent.com/5947035/102071258-46e96880-3e11-11eb-996b-5cd3b0b18db7.png)

你看不看？

点击”OK“以后，AdGuard Home更新客户端排行，结果选择的客户端是表示的。

**Comment by Aikatsui** [comment]
老麻煩 https://github.com/AdguardTeam/AdGuardHome/issues/2150#issuecomment-705615388

**Comment by ameshkov** [comment]
@Aikatsui are you able to reproduce this?

**Comment by PassWall-OpenWrt** [comment]
> 很奇怪，我不能重复这个错误。
> 
> 客户端排行中点击“拦截”的时候，你该看对话窗口：
> ![image](https://user-images.githubusercontent.com/5947035/102071258-46e96880-3e11-11eb-996b-5cd3b0b18db7.png)
> 
> 你看不看？
> 
> 点击”OK“以后，AdGuard Home更新客户端排行，结果选择的客户端是表示的。

是有提示 但是 它没有判断 在 DNS设置里面的拦截列表里是否已经存在这个客户端 如果你当前点的拦截的这个客户端已经在列表里了 它就会再次添加到那个列表里面。

**Comment by PassWall-OpenWrt** [comment]
https://www.youtube.com/watch?v=u6ag1YdB_FM

@ameshkov

**Comment by Aikatsui** [comment]
> @Aikatsui are you able to reproduce this?

Yes. v0.105.0-SNAPSHOT-e2738fdf

**Comment by ameshkov** [comment]
@ArtemBaskal check the video here: https://github.com/AdguardTeam/AdGuardHome/issues/2428#issuecomment-744389840

**Comment by ameshkov** [comment]
@ainar-g steps to reproduce:

1. Send a DNS query to AGH from some non-local IP
2. Restart AGH (so that the runtime clients list was empty)
3. Open dashboard and try to block that client

The problem is that the client is not in the runtime clients list so `/control/clients` request returns nothing for it, therefore the UI cannot check whether it's disallowed or not.

**Comment by ainar-g** [comment]
Should be fixed as of snapshot 679bbcdc2.  Can you please check if our solution fixes the issue for you?

**Comment by Aikatsui** [comment]
@ainar-g да. Теперь нормально

**Comment by PassWall-OpenWrt** [comment]
@ainar-g It's fixed .thanks !
