### ISSUE TITLE
Настройка пользовательских правил

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2429]
В настройках пользовательских правил очень не хватает возможность блокировки по периоду времени. 
Например, в это правило
||yahoo.com^$client=TV32|TV40
добавить  и временной интервал действия данного правила, указав время начала и время окончания действия правила. 
Добавьте плз такую возможность.

**Comment by ameshkov** [comment]
Это все-таки надо не на уровне правила настраивать, а на уровне отдельного фильтра, а про это есть уже задача.

**Comment by Aikatsui** [comment]
@fizsef --> https://github.com/AdguardTeam/AdGuardHome/issues/1203

**Comment by fizsef** [comment]
А каким образом отдельное  правило применить по временному интервалу для конкретного клиента?

**Comment by ameshkov** [comment]
Ну пока что никак, речь о том, что задачи про эту фичу уже открыты, но пока не сделаны.
