### ISSUE TITLE
Блокировать сервисы по временному интервалу

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2430]
В настройках клиента
![1](https://user-images.githubusercontent.com/74646605/102007155-a4a98200-3d37-11eb-991f-2e928ee74436.jpg)

нет возможности блокировать сервисы по временному интервалу. Для каждого сервиса указать время начала и время окончания действия правила. Очень не хватает. Чтобы дети могли пользоваться этими сервисами только в выделенное им время, это большая проблема в современное время. Полностью отключить интернет тоже не получается, так как для учебы, домашних заданий, нужен доступ в интернет.

**Comment by Aikatsui** [comment]
Duplicate of #951 https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by ameshkov** [comment]
Closed as dup

**Comment by fizsef** [comment]
Какой же это дубликат?!  Здесь сервис блокируется полностью, а там в правиле можно  указать конкретный поддомен сервиса. Ну если считаете это дубликатом, то должна быть возможность и здесь указывать временной интервал.
