### ISSUE TITLE
Add Cloudron as installation method

### ISSUE THREAD

**Issue by gramakri** [AdguardTeam/AdGuardHome#2433]
We have made a AdGuard Home package for Cloudron. Would be great to have it listed as one of the deployment methods. 

Usually, one can go to https://my.demo.cloudron.io (username: cloudron password: cloudron) and try out the app. But we have black listed AdGuard Home in the demo instance because we feared it could be used as an open resolver.

The code for the package itself is at https://git.cloudron.io/cloudron/adguard-home-app (it's based on Docker) and we also have automated selenium tests for testing updates (it's cloudron specific though).

**Comment by ameshkov** [comment]
We'll add Cloudron to the "Projects that use AdGuard Home" list since we only maintain a limited set of installation methods.

> But we have black listed AdGuard Home in the demo instance because we feared it could be used as an open resolver.

It is, but the default rate limit is rather strict (20rps) and you can make it even stricter if you want (see the config file).

**Comment by gramakri** [comment]
> We'll add Cloudron to the "Projects that use AdGuard Home" list since we only maintain a limited set of installation methods.

@ameshkov Thanks, that should be good as well. Should I submit a PR somewhere for that?

> It is, but the default rate limit is rather strict (20rps) and you can make it even stricter if you want (see the config file).

Unfortunately, on the demo, AdGuard Home configs are editable (it's like that for all apps).

**Comment by ameshkov** [comment]
> Should I submit a PR somewhere for that?

Not necessarily, I'll update the README soon anyway

**Comment by ameshkov** [comment]
Added to README and to "Other options" on Wiki: https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#installation
