### ISSUE TITLE
Could I use domain to login AdGuardHome dashboard only and not IP address?

### ISSUE THREAD

**Issue by Hokia** [AdguardTeam/AdGuardHome#2435]
Both http and https

**Comment by ameshkov** [comment]
Well, it's not the same, but if you enable "Redirect to HTTPS automatically", you'll only be able to use the domain you have the certificate for.

**Comment by Hokia** [comment]
Not really~Even I enable "Redirect to HTTPS automatically", I could use “Insecure connections” to login, not domain only.
<a href="https://sm.ms/image/1kXcpLxijPDWqTE" target="_blank"><img src="https://i.loli.net/2020/12/15/1kXcpLxijPDWqTE.png" ></a>

**Comment by Hokia** [comment]
> Well, it's not the same, but if you enable "Redirect to HTTPS automatically", you'll only be able to use the domain you have the certificate for.
Not really~Even I enable "Redirect to HTTPS automatically", I could use “Insecure connections” to login, not domain only.
<a href="https://sm.ms/image/1kXcpLxijPDWqTE" target="_blank"><img src="https://i.loli.net/2020/12/15/1kXcpLxijPDWqTE.png" ></a>

**Comment by ameshkov** [comment]
Yeah, you can, but that'd require accepting an invalid certificate.

If you want strictly the hostname, I guess you need to use a reverse proxy like nginx to proxy AGH and manage all the access rules there.

**Comment by Hokia** [comment]
> Yeah, you can, but that'd require accepting an invalid certificate.
> 
> If you want strictly the hostname, I guess you need to use a reverse proxy like nginx to proxy AGH and manage all the access rules there.

I see. Can I take nginx and AGH together? Is that conflicted？

**Comment by ameshkov** [comment]
Yep, you can configure nginx to be a reverse proxy for AGH, no problem.

**Comment by Hokia** [comment]
> Yep, you can configure nginx to be a reverse proxy for AGH, no problem.

Thinks
