### ISSUE TITLE
Check the filtering result contain unwanted reason string

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#2436]
**Reproduce steps**

Check a domain contain on blocklists
>midpopedge.com
Reason: NotFilteredError
Filtered by AdGuard DNS filter
Rule: ||midpopedge.com^

v0.105.0-SNAPSHOT-e2738fdf

**Comment by ainar-g** [comment]
<p>Should&#xA0;be fixed as&#xA0;of&#xA0;commit a2d39c81.&#x2003;Can you please
check if&#xA0;our solution fixes the&#xA0;issue for&#xA0;you?</p>

**Comment by Aikatsui** [comment]
да
