### ISSUE TITLE
Query log shows random "Processed" or "NotFilteredError" for blocked domains and no color indication

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#2438]
"Processed" or "NotFilteredError" appear randomly for blocklist domains and below tested with default AdGuard DNS filter - `midpopedge.com`

- If it showed "NotFilteredError" status then response details contain the filter list used and the particular rule
<details><summary>Screenshot:</summary>

![YJSAu2Z](https://user-images.githubusercontent.com/63988538/102093803-2a225480-3e54-11eb-8b45-f4959318243a.png)

</details>

- If it showed "Processed" then doesn't contain details about filter list (very difficult to reproduce often)
<details><summary>Screenshot:</summary>

![QNjTd4u](https://user-images.githubusercontent.com/63988538/102093872-3e665180-3e54-11eb-9761-fe2726ccd150.png)

<details><summary>Screenshot:</summary>

</details>

v0.105.0-SNAPSHOT-e2738fdf

**Comment by ainar-g** [comment]
<p>Should&#xA0;be fixed as&#xA0;of&#xA0;commit a2d39c81.&#x2003;Can you please
check if&#xA0;our solution fixes the&#xA0;issue for&#xA0;you?</p>

**Comment by Aikatsui** [comment]
да
