### ISSUE TITLE
OpenBSD support?

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2439]
<p><i>OpenBSD</i>&#xA0;is an OS that is relatively popular on routers, so we may
want to support it in the future.&#x2003;Apart from a few external libraries,
that will probably require patching, it shouldn't be that hard
to&#xA0;support.</p>

**Comment by qbit** [comment]
fwiw - I have a WIP port of AGH for OpenBSD. Currently I am running the latest stable release on arm64 without issues.

https://github.com/AdguardTeam/AdGuardHome/pull/2417 was specifically for fixing master on OpenBD :D.

I do want to add another change that allows for running as non-root. This would let one forward the dns requests from priv ports (via pf) to AGH running as a non-root user.

**Comment by Aikatsui** [comment]
@qbit https://github.com/AdguardTeam/AdGuardHome/issues/723 https://github.com/AdguardTeam/AdGuardHome/issues/1324

**Comment by ainar-g** [comment]
Edge builds for OpenBSD are now built and published.  Betas are coming in a couple of weeks.  What works:

 *  DNS, including client settings and filtering.

 *  Logging.

 *  Statistics.

What doesn't work yet:

 *  DHCP; this will be fixed in #3225.

 *  Service actions; this will be fixed in #3226.

 *  Probably other things, heh.  We'll keep testing.

I'll close this issue.  Please file new ones if you find bugs in the OpenBSD version.

**Comment by fireglow** [comment]
For anybody looking for the builds, they are here:
    * OpenBSD: [64-bit (experimental)](https://static.adguard.com/adguardhome/edge/AdGuardHome_openbsd_amd64.tar.gz)
    * OpenBSD ARM: [64-bit (experimental)](https://static.adguard.com/adguardhome/edge/AdGuardHome_openbsd_arm64.tar.gz)
