### ISSUE TITLE
Check the filtering display not found in your lists for unblock custom filtering rules

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#2440]
v0.105.0-SNAPSHOT-e2738fdf

**Comment by ameshkov** [comment]
Hm, I don't understand, could you please explain what are the steps to repro and expected result?

**Comment by Aikatsui** [comment]
Steps:
1. Add @@||example.org^ to custom filtering rules and apply
2. Enter domain to check the filtering for test

I can't reproduce now. i'll reopen if noticed that problem again
