### ISSUE TITLE
FreeBSD on ARM64 support

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2441]
<p><i>Go</i>&#xA0;has become capable of supporting <code>freebsd/arm64</code>
back in 1.14, so maybe we could add it as well in one of the
future&#xA0;releases.</p>

<p>But&#xA0;only after&#xA0;#2276.</p>

**Comment by kisst** [comment]
Any update here? I have an arm64 based PfSense where I would love to replace the over-complicated pfBlockerNG, with a nice and slim AdGuardHome. 
After that maybe a submission to https://github.com/pfsense/FreeBSD-ports/tree/devel/dns would be a nice.

**Comment by ainar-g** [comment]
@kisst, hello.  We plan to land the support in the next version.

**Comment by conradseba** [comment]
This would be awesome!! I'm in the same situation, a Netgate Pfsense arm64 and sick of PfBlockerNG weirdness.

**Comment by ainar-g** [comment]
The beta is out.  The port will ship with the next release, v0.107.0, which should be out in early July.

We'll close this issue for now.  If anyone has any issues with this port, please file a new one.  Thanks.
