### ISSUE TITLE
[Feature Request] Want a grouping function for DNS upstream

### ISSUE THREAD

**Issue by PussAzuki** [AdguardTeam/AdGuardHome#2446]
When there is DNS grouping function, maybe you don't have to copy & paste a bunch of DNS upstream, and you can reduce the file size.
The main way to use it can be like this. 
`tls:// [2001:4860:4860::8844] -group Google` 
`[/example.local/]Google`
`[/example2.local/]Google`
`[/example3.local/]Google`
`[/example4.local/]Google`

Without having to be like this.
`[/example.local/]tls:// [2001:4860:4860::8844]`
`[/example2.local/]tls:// [2001:4860:4860::8844]`
`[/example3.local/]tls:// [2001:4860:4860::8844]`
`[/example4.local/]tls:// [2001:4860:4860::8844]`

**Comment by hezhijie0327** [comment]
It supports like [this](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains):
[/example.local/example2.local/example3.local/example4.local/]tls://[2001:4860:4860:8844]

**Comment by PussAzuki** [comment]
> It supports like [this](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains):
> [/example.local/example2.local/example3.local/example4.local/]tls://[2001:4860:4860:8844]

How about this?
`tls:// [2001:4860:4860::8844] -group trust`
`tls:// [2606:4700:4700::1001] -group trust`
If you set up two different upstream and group them together, you should need it.

**Comment by hezhijie0327** [comment]
In my opinion, whether can support muti-upstream in one line, such like `[/www.google.com/]https://doh.opendns.com:443/dns-query,tls://dns.google:853`

**Comment by PussAzuki** [comment]
> In my opinion, whether can support muti-upstream in one line, such like `[/www.google.com/]https://doh.opendns.com:443/dns-query,tls://dns.google:853`

If it is helpful, please click the + 1 above.
