### ISSUE TITLE
Enable / Disable DNS blocklists does not work.

### ISSUE THREAD

**Issue by sihartley** [AdguardTeam/AdGuardHome#2447]
### Issue Details
When a custom, or any list is added to the DNS blocklists, once it is enabled using the check box under "enable" the block list works fine.
However, unchecking the checkbox under "enable" does not disable the blocklist. The only way to disable the blocklist is to remove it! To re-enable said blocklist, it has to be re-added.
This is the case in the webui, and also when using an automation either in .yaml file or Node-Red.

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
What version of AdGuard Home are you using?

So far, I can reproduce it neither in release nor in the latest edge build.

**Comment by sihartley** [comment]
Using Adguard Home Version: 0.104.1
This happened about two hours ago, added a DNS blocklist, enabled it.
When I disabled it (unchecked the enabled box) the blocks were still in place. The only way to remove those blocks, was to remove the actual DNS blocklist.

**Comment by ameshkov** [comment]
Just in case, the latest release is v0.104.3.

> When I disabled it (unchecked the enabled box) the blocks were still in place.

Please note that it may take some time to unblock things as the blocked responses are cached by the clients.
I bet this is what happened.
