### ISSUE TITLE
Let us select whom secure dns we want to enable

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdGuardHome#2450]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

For the duplicate i have searched at encrypted and don't see duplicate if there is a duplicate sorry.

### Problem Description
I only use DNS over Quic (with your ios application and your dnsproxy) so i want to only enable this on my AdGuard home (and the https portal of course)

### Proposed Solution
Add a way to enable or disable Dns over Https, Dns over Tls or Dns over Quic separately (or disable all of them but let the portal on https).

**Comment by ameshkov** [comment]
If you keep TLS and HTTPS ports empty, this would disable DoT and DoH.

This would also disable HTTPS on the admin web portal so it's not the same as you want.

**Comment by michaelb-ae** [comment]
it's not the most wanted feature, so in your place i will label it as low priority, but when everything else is done it can be a nice bonus to the configuration portal
