### ISSUE TITLE
How to solve complie error: too many arguments in call to d.filteringEngineWhite.Match?

### ISSUE THREAD

**Issue by wxf26054** [AdguardTeam/AdGuardHome#2456]
GOOS=linux GOARCH=amd64 GO111MODULE=off go get -v github.com/gobuffalo/packr/...
PATH=/root/go/bin:/root/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr -z
CGO_ENABLED=0 go build -ldflags="-s -w -X main.version= -X main.channel=release -X main.goarm=" -asmflags="-trimpath=/root/ad/AdGuardHome-master" -gcflags="-trimpath=/root/ad/AdGuardHome-master"
#github.com/AdguardTeam/AdGuardHome/dnsfilter'
dnsfilter/dnsfilter.go:555:41: too many arguments in call to d.filteringEngineWhite.Match
        have (string, []string)
        want (string)
dnsfilter/dnsfilter.go:577:35: too many arguments in call to d.filteringEngine.Match
        have (string, []string)
        want (string)
Makefile:28: recipe for target 'AdGuardHome' failed
make: *** [AdGuardHome] Error 2

![image](https://user-images.githubusercontent.com/22016320/102601191-cc934e00-415a-11eb-9399-9f218ff70a28.png)

This is the error log above.

**Comment by ainar-g** [comment]
We don't support building with `GO111MODULE='off'`, sorry.  Please enable _Go_ modules when building _AdGuardHome_.

**Comment by wxf26054** [comment]
Sorry, but which variable should I use?

**Comment by ainar-g** [comment]
Which version of _AdGuardHome_ are you trying to build?  Also, please provide the output of `go version` and `go env` commands.

**Comment by ameshkov** [comment]
@wxf26054 just try using `make build` to build AGH
