### ISSUE TITLE
Blocked Queries text overlaps in web UI

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#2457]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** 0.104.3
* **How did you setup DNS configuration:** N/A
* **If it's a router or IoT, please write device model:** N/A
* **Operating system and version:** Debian Buster

### Expected Behavior
Text should not overlap. 

### Actual Behavior

Text overlaps. 

### Screenshots

<img width="265" alt="image" src="https://user-images.githubusercontent.com/19761269/102689327-30814980-4223-11eb-9300-c2f3a6e644ed.png">

### Additional Information

N/A

**Comment by Aikatsui** [comment]
@agneevX Can you check v0.105.0 edge builds? It seems cannot reproduce

**Comment by ameshkov** [comment]
This will look differently in the redesigned version anyway

**Comment by agneevX** [comment]
Duplicate of what? There's not enough context in your reply with regard to the issue.

**Comment by ameshkov** [comment]
@agneevX we're working on a major redesign right now, and some of the current UI issues are simply not relevant to the new UI - these elements look differently there.

**Comment by agneevX** [comment]
Ah! Is this 0.105?

**Comment by ameshkov** [comment]
Nope, unfortunately, this will be quite later, maybe 106 or 107
