### ISSUE TITLE
"DNS cache configuration" does not accept any "Override minimum TTL" value

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2459]
Hello I am using AdGuardHome **0.105.0-beta.1**

Raspberry Pi 4B
Raspberry OS Lite (December 2nd 2020)
Linux raspberrypi 5.4.79-v8+ aarch64
AdGuardHome_linux_armv6.tar.gz

There is a Bug on **DNS cache configuration**. The UI does not accept any value in **Override minimum TTL**!
I just can set the **Override maximum TTL** value and to apply changes .

If I put a value to min TTL then I can not apply changes and I get this error massage: 

**Error: control/dns_config | cache_ttl_min must be less or equal than cache_ttl_max | 400**

To reproduce, I used this values:
Cache value : 8388608
Min TTL : 14400
Max TTL : 172800

Have a nice weekend

**Comment by EugeneOne1** [comment]
This should be fixed as of snapshot bdff46e.  Could you please check if our solution fixes the issue for you?

**Comment by uservictor** [comment]
It works properly on v0.105.0-SNAPSHOT-bdff46ec
thanks
