### ISSUE TITLE
[Feature Request] filterlists for "disallowed domains" and "blocked clients"

### ISSUE THREAD

**Issue by HorayNarea** [AdguardTeam/AdGuardHome#2461]
### Problem Description
I'm running a semi-public AdGuard Home instance (accessible from the Internet but information about it is shared in private), this requires having (gigantic :D) blocklists for clients¹ and disallowed domains².

The great @DandelionSprout offers a client-blocklist at https://github.com/DandelionSprout/adfilt/blob/master/AdGuardHomeDisallowedIPs.txt which solves one part of this problem, but to use it I currently need to paste it manually into the AGH webinterface³.

As far as I know there is currently no public blocklist that contains domains that (semi-)public resolvers almost always want to drop completly but I have a very small private list for that, the same inconvenience applies here.

### Proposed Solution
Either add an option to get client/domain "drop"lists by URL or add an option to specify a filepath for these lists, so one can manage the list updates via cron for example.

### Alternatives Considered
None as I don't know of any.

### Additional Information
¹ to completely drop queries from IPs/networks that are abusing DNS
² to completely drop queries for domains that are only used for abuse
³ after some cleanup since the webinterface doesn't allow comments (neither `!` nor `#`) and whitespace seems to trip it up to

**Comment by ameshkov** [comment]
This kinda sounds like a feature request from @DandelionSprout himself:
https://github.com/AdguardTeam/AdGuardHome/issues/1032

Please check it, is yours a duplicate?

**Comment by HorayNarea** [comment]
Oh sorry… Github Search is really unhelpful :/

Yes, the "disallowed clients" part is a duplicate but for "disallowed domains" it is new …  I think both parts are needed to completely remove the painpoints when running a public AGH instance

**Comment by ameshkov** [comment]
Added info about it to that issue, merging this one there.
