### ISSUE TITLE
Improve the installation script, add simple "reinstall/update"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2462]
Assigned on v0.106, but it looks relatively simple.

1. [ ] Detect existing AdGuard Home, suggest user to reinstall it. If the user agrees, replace the binary and restart AdGuard Home.
2. [ ] Merged here: fix #2989 - Run install.sh with existing install zip

**Comment by uservictor** [comment]
Maybe it would be helpful to add an seperate menu for "system" settings.
Between General settings and DNS settings you can add System settings.

It can contain options like:
Reinstall
Choose Update channel (edge) (beta) (stable)
Choose System language

Service restart
Disable protection
Report Issue
