### ISSUE TITLE
Specify the URL to use a DNS

### ISSUE THREAD

**Issue by 499906881** [AdguardTeam/AdGuardHome#2480]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Proposed Solution

github.com only uses 8.8.8.8 to resolve
google.com only uses 1.1.1.1 to resolve
Other DNS does not participate in resolution

**Comment by ameshkov** [comment]
You can do that already:
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains
