### ISSUE TITLE
Add pedoporn Filter | https://projectarachnid.ca/en/

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdGuardHome#2486]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I want to see a filter added like the two api (adult and malware) who block pedoporn content on our DNS.

### Proposed Solution

Create an api on your server who work with https://projectarachnid.ca/en/, since these url are secret (to prevent bad people to go to these website), and add it to home guard (like that we can block it without having them).

This website does not contain any link to a list, you must contact them to ask a way to have access to it, we can't do it ourself since this services is only proposed to entreprise or big content provider (or a dns like your service can add), this services is free of charge of course.

**Comment by Aikatsui** [comment]
About 2nd request: It's not recommend to add this filter to AGH due moral reasons and children. It can be include to 1st(enhanced parental control) category listed on https://github.com/AdguardTeam/AdGuardHome/issues/2230

**Comment by michaelb-ae** [comment]
@Aikatsui in my case i'm more for a mandatory list but ethically it's not recommanded, so i ask about a 3rd list only for letting choice on the admin of ADH, who mabe want to ban pedoporn on his network but let adult website usable.

**Comment by Aikatsui** [comment]
Including above explanation, AdGuardHome admin may be a young child, teenage or adult (both male and female) then overall comment, i wanted to ensure this product remain on certain standard for address that. Just doesn't feel interest about decoupling adult sites (it means, let users to visit adult sexual sites but not child sexual sites) it's better to not watch both :) 
Family DNS (known as parental control in AGH) enough for address both issues and it doesn't contain most dating sites, communities etc according to some tests. Otherhand redundancy, projectarachnid may suitable and use by projects individually that don't have own adult content filtering service.

**Comment by michaelb-ae** [comment]
nothing forbid ADH to automatically check the "pedoporn" when we check adult website.
