### ISSUE TITLE
Blocking all pages

### ISSUE THREAD

**Issue by zs-alt** [AdguardTeam/AdGuardHome#2490]
I installed AdGuard Home on Debian as DNS and I would like to block all websites except those on the whitelist, e.g. * .microsoft.com
Is it possible to do this in a simple way?

If I have entered the application incorrectly, please correct me.

**Comment by ameshkov** [comment]
Do something like this:

* `||*` -- to block everything
* `@@||microsoft.com` -- to unblock MS and it's subdomains

More info on the syntax is here: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists
