### ISSUE TITLE
Invalid $dnsrewrite rules should be discarded

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2492]
I've tried experimenting with $dnsrewrite and added an invalid rule:
`||example.org^$dnsrewrite=A:NOERROR:127.0.0.1`

The result was that the rule was applied, but the response was NXDOMAIN, which is unexpected.
Instead of that, I suggest simply discarding this kind of rules at the moment when they're parsed by urlfilter.

**Comment by ainar-g** [comment]
The thing that is happening is that the parser interprets your input as a shorthand form of a new `CNAME`, and so it returns the rewrite that tries to resolve the host `A:NOERROR:127.0.0.1`.  That means we have to define what exactly makes a host valid and use that.
