### ISSUE TITLE
[Feature request] Device Model in .mobileconfig configuration

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2493]
Hello,

in continue of #1383 please add device model identification for clients in logs. This string is directly encrypted in base64 in endpoint URL:
`          <key>ServerURL</key>`
`          <string>https://agh.stub.domain/dns-query/client-identifier-name/b64:QXBwbGUgaVBob25lMTMsNA</string>`
`        </dict>`

**QXBwbGUgaVBob25lMTMsNA -> Apple iPhone13,4 -> iPhone 12 Pro Max**

Please do not confuse this with the client identifier. That's the Apple device identifier. As I know, it doesn't work for DoT.

Thank you.
Cheers🤙

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2497
