### ISSUE TITLE
Docker (bridge mode) and port 68 binding

### ISSUE THREAD

**Issue by Not-Code** [AdguardTeam/AdGuardHome#2496]
### Problem Description
The documentation provided on docker hub (https://hub.docker.com/r/adguard/adguardhome), requires the binding of the following ports when using bridge mode:
-p 67:67/udp -p 68:68/tcp -p 68:68/udp
From what I understand (after a little search on the net) it seems that port 67 is used by the DHCP server and port 68 is used by the DHCP client.
If port 68 is really needed by AdGuard this is going to be an issue for every user that doesn't want to use the DHCP part of the application. In my case I had a dhclient that was already binding the UDP port 68 (I have a static rule on the router that it is indeed the DHCP server and the machine is getting the static IP through DHCP).

### Proposed Solution
I think that if port 68 is not needed by AdGuard it should not be requested by the application. If the port is needed, I think that it would be better to decouple the application and provide the DHCP server as an "additional" functionality (for example as an additional pod, a sidecar container or an application plugin). Maybe it's just me, but I found the application for its DNS blocking capability. So if other capabilities, other than DNS server, are provided and these are going to collide with my network configuration I will probably just move on.
In general I think that it would be better, in any case, to provide the DHCP server functionality as an "add-in" and not as a core capability of the application.

### Additional Information
In any case, keep up the good job and thanks for you effort.

**Comment by ameshkov** [comment]
> From what I understand (after a little search on the net) it seems that port 67 is used by the DHCP server and port 68 is used by the DHCP client.

These ports aren't needed if you're not going to use AdGuard's DHCP server, you can simply omit these port mappings, everything will continue to work just okay.

I've updated README on docker hub to reflect this
