### ISSUE TITLE
Additional validation in $dnsrewrite rules

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2498]
Context: #2101, #2452, #2492.

We need to decide, which additional validations we want for the `$dnsrewrite` response modifier.  Among the ones that are likely to be requested:

 *  The FQDN in the `MX` and `PTR` rewrites.
 *  The hostname in the full-form `CNAME` rewrites.
 *  The hostname in `SVCB`/`HTTPS` rewrites.

Any more I've missed?

**Comment by DandelionSprout** [comment]
Presuming I understand the question correctly: I get quite a few `TXT` DNS requests to my server, e.g. `hostname.bind`, `id.server`, `version.bind`, etc. For those, they can be treated as hostnames, but without being limited to regular TLDs.

There's also `RRSIG` requests (to e.g. `pizzaseo.com`), which I doubt the legitimacy of as a whole. If they are to be treated as legitimate requests, then the hostname is sufficient.

**Comment by ainar-g** [comment]
@DandelionSprout

If I recall correctly, `TXT` records can contain arbitrary textual data, so I don't think we'll apply any validations there besides the byte size.

As for `RRSIG` records, we currently don't support them.  If you have a need for them, please file a separate issue about it and we'll try to add them in v0.106.0 as well.
