### ISSUE TITLE
Custom services and Home Assistant Toggles

### ISSUE THREAD

**Issue by tnowakow** [AdguardTeam/AdGuardHome#2502]
- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed

### Problem Description
I love the pre-built services and toggles, would it be possible to create custom services? An example would be for roblox, it needs two filter entries to block it.

Even better would be to call these services from Home Assistant integration as a toggle switch.

### Proposed Solution
Allow the ability to add a service name on the page and the filter rules needed

### Additional Information
I love the integration with Home Assistant but surprised the pre-built services don't show up as toggle switches.  Would love to have that ability and the ability to add custom ones. Thank you,  I'm not a programmer and was told on reddit my best bet to reach out to devs would be here.

**Comment by ameshkov** [comment]
Hi, thank you!

> Even better would be to call these services from Home Assistant integration as a toggle switch.

Well, I guess this should be requested in the Home Assistant repo.

Regarding custom services, there's already a feature request about that: https://github.com/AdguardTeam/AdGuardHome/issues/1692
