### ISSUE TITLE
Development practises

### ISSUE THREAD

**Issue by jvoisin** [AdguardTeam/AdGuardHome#2505]
Recently, a single commit adding 20,843 lines of code was merged, adding a "client2" folder, instead of using a branch.
Would it be possible to avoid large code dumps like this in the future?
It makes it hard to review and understand the code, as well as backporting fixes to stable versions.

Thanks

**Comment by ameshkov** [comment]
Well, there actually was a branch, but there was no pull request.

The thing is that we have a self-hosted bitbucket repo that is mirrored on Github 1-to-1, and the internal code review takes place there. However, all branches are mirrored to Github so it's possible to review what's being done.

Regarding the codebase size, most of the code comes from an auto-generated openapi API client. Also, we're rewriting the UI part of the code, so expect some substantial changes coming up later.
