### ISSUE TITLE
Error while update check

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2507]
Hello I am using AdGuardHome v0.105.0-SNAPSHOT-5e20ac7e on my RaspberryPi 4B (32bit armv6 edge channel)
Recently I disconnected internet connection for about 10 minutes, after connecting again and going to admin webinterface I get this message:

_Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/edge/version.json: *fmt.wrapError version.json: invalid character '}' looking for beginning of object key string | 502_

After clicking few times on update button i get same message until the update button disappear (its not visible/selectable).

Have a nice day

**Comment by ddonindia** [comment]
there is a syntax error  in https://static.adguard.com/adguardhome/edge/version.json. I think we need remove last ","

`{
  "version": "v0.105.0-SNAPSHOT-3706f559",
  "announcement": "AdGuard Home v0.105.0-SNAPSHOT-3706f559 is now available!",
  "announcement_url": "https://github.com/AdguardTeam/AdGuardHome/commits/master",
  "selfupdate_min_version": "0.0",

  "download_darwin_386": "https://static.adguard.com/adguardhome/edge/AdGuardHome_darwin_386.zip",
  "download_darwin_amd64": "https://static.adguard.com/adguardhome/edge/AdGuardHome_darwin_amd64.zip",
  "download_freebsd_386": "https://static.adguard.com/adguardhome/edge/AdGuardHome_freebsd_386.tar.gz",
  "download_freebsd_amd64": "https://static.adguard.com/adguardhome/edge/AdGuardHome_freebsd_amd64.tar.gz",
  "download_freebsd_arm64": "https://static.adguard.com/adguardhome/edge/AdGuardHome_freebsd_arm64.tar.gz",
  "download_freebsd_armv5": "https://static.adguard.com/adguardhome/edge/AdGuardHome_freebsd_armv5.tar.gz",
  "download_freebsd_armv6": "https://static.adguard.com/adguardhome/edge/AdGuardHome_freebsd_armv6.tar.gz",
  "download_freebsd_armv7": "https://static.adguard.com/adguardhome/edge/AdGuardHome_freebsd_armv7.tar.gz",
  "download_linux_386": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_386.tar.gz",
  "download_linux_amd64": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_amd64.tar.gz",
  "download_linux_arm64": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_arm64.tar.gz",
  "download_linux_armv5": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv5.tar.gz",
  "download_linux_armv6": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv6.tar.gz",
  "download_linux_armv7": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv7.tar.gz",
  "download_linux_mips64le_softfloat": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mips64le_softfloat.tar.gz",
  "download_linux_mips64_softfloat": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mips64_softfloat.tar.gz",
  "download_linux_mipsle_softfloat": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mipsle_softfloat.tar.gz",
  "download_linux_mips_softfloat": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mips_softfloat.tar.gz",
  "download_linux_ppc64le": "https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_ppc64le.tar.gz",
  "download_windows_386": "https://static.adguard.com/adguardhome/edge/AdGuardHome_windows_386.zip",
  "download_windows_amd64": "https://static.adguard.com/adguardhome/edge/AdGuardHome_windows_amd64.zip",
}`

**Comment by ainar-g** [comment]
Thanks for reporting that!  We're in the process of updating our release process, and this is one of the bugs we've accidentally introduced.  We'll fix it in a few hours!

**Comment by ainar-g** [comment]
Should be fixed as of snapshot 933ca2af.  Can you please check if our solution fixes the issue for you?

**Comment by mgcWil** [comment]
Hello, for me, no more error on the json file, but the archives are empty :(

**Comment by ddonindia** [comment]
This error is gone with latest edge build for arm64

**Comment by ainar-g** [comment]
@mgcWil Thanks for testing, we're testing and rolling out another fix.

**Comment by ainar-g** [comment]
The _Windows_ and _macOS_ ZIP archives should be fixed as of 2298a9ed.

**Comment by uservictor** [comment]
On new version "v0.105.0-SNAPSHOT-2298a9ed" the error massage like in first post is solved. 

It shows connection error now (thats fine while there is no internet connection at this time) but there is still a bug with the "check for updates button" he disappears after few clicks. 

To reproduce it:
disconnect internet
check for update on agh ui
click few times on update button 

have a nice day agh team

**Comment by ainar-g** [comment]
@uservictor, thanks for checking!  As for the disappearing button, seems unrelated to this issue, but can you please file a separate issue about that?  We'll try to fix it.
