### ISSUE TITLE
Add error log category

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2511]
Hello, while this project is in pre-release/testing status it would be helpful if you add an category like "Query log" but for status/error messages.

Something like "Status log" for the time until 1.0 version of AGH is released.

The log should contain all error/confirmation messages that are shown while using/setup AGH for example:
Clicking on update button shows "Error: control/version.json | Couldn't get version check json", this should be saved in the log.

It would make report issues more comfortable (especially on mobile devices)

**Comment by Aikatsui** [comment]
Related https://github.com/AdguardTeam/AdGuardHome/issues/1685

**Comment by ameshkov** [comment]
Well, the thing is that these are printed to log (syslog by default, but you could configure it to write it to a file).

**Comment by ameshkov** [comment]
Generally, I don't really like the idea to save logs anywhere else. It's too complicated considering the way logs are written right now.
