### ISSUE TITLE
How to full uninstall Pi4

### ISSUE THREAD

**Issue by sagaardu** [AdguardTeam/AdGuardHome#2512]
### Problem Description

Hello,

How can you completely uninstall adguard from the system and erase all files and dependencies?

I just find a way to disable the service.

Cheers

**Comment by planet0** [comment]
For Raspberry Pi OS, provided you used the default location (Home folder) as per the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi), you can use in terminal
`sudo ./AdGuardHome/AdGuardHome -s uninstall`
to first disable and remove the service, and then you can delete the AdGuardHome folder using
`sudo rm -rf AdGuardHome`

It might be worth providing uninstall instructions in the [Wiki article](https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi) as well.

**Comment by ameshkov** [comment]
Yep, it makes sense to add it to FAQ indeed: https://github.com/AdguardTeam/AdGuardHome/issues/2517
