### ISSUE TITLE
Cant unblock Ip from dns query list in top queries 

### ISSUE THREAD

**Issue by legouju** [AdguardTeam/AdGuardHome#2515]
### Issue Details

* **Version of AdGuard Home server:**
  * (0.104.3)
* **How did you setup DNS configuration:**
  * DNS is set on my router so it is network wide
* **If it's a router or IoT, please write device model:**
  * [Steam Link](https://en.wikipedia.org/wiki/Steam_Link#Android/iOS) (yes u read that right)
* **Operating system and version:**
  * Arch Linux for Arm (armv7l kernel: 5.4.24)

### Expected Behavior

want to unblock the ip bellow (192,168,0,12) and expected an unblock button
![image](https://user-images.githubusercontent.com/44247490/103473074-50e3f480-4d49-11eb-85a2-2f74f84b3bd0.png)

### Actual Behavior

ad guard home does not change block button to unblock button to allow me to unblock
![image](https://user-images.githubusercontent.com/44247490/103473062-3d388e00-4d49-11eb-9a6b-302d43529276.png)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I started using adguard home on 1/1/2020 and just ran into this issue on 1/2/2020

**Comment by ameshkov** [comment]
@ArtemBaskal have we already solved this in v0.105 beta?

**Comment by IldarKamalov** [comment]
Same issue as this one https://github.com/AdguardTeam/AdGuardHome/issues/2428
