### ISSUE TITLE
Incorrect adguard DNS filter

### ISSUE THREAD

**Issue by jimger** [AdguardTeam/AdGuardHome#2516]
The problem is with
https://online.novasports.gr/

Although to adguard developers it may seems it is blocking it correctly, it breaks the site when using the adguard DNS, as streaming never loads. The only way is to use another DNS. As it is difficult for me to saw u the problem (it is paid streaming service), I can assure that the site breaks. It seems adguard for Android works ok.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #531](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/531) via [**ZenHub**](https://www.zenhub.com/)
