### ISSUE TITLE
Question: Correct SDNS Stamp Addresses

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#2520]
Could AdGuard Team please provide a full list of its SDNS Addresses? The generator at https://dnscrypt.info/stamps/ can generate several addresses for AdGuard DoH (94.140.14.14, 94.140.15.15) and they all work, but what are the official DoH and DoQ addresses? 

I use:
sdns://AgEAAAAAAAAADDk0LjE0MC4xNC4xNAAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk
sdns://AgEAAAAAAAAADDk0LjE0MC4xNS4xNQAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk

**Comment by ameshkov** [comment]
Well, DNS stamps are just a way to encode resolver addresses.

The official address is `https://dns.adguard.com/dns-query` (the IP address is defined by the domain name)
However, I'd suggest using `https://dns-unfiltered.adguard.com/dns-query` in AdGuard Home since with AGH you define what should be blocked or not, why would you need results that are filtered on the DNS server side.

**Comment by EntropySmoke** [comment]
The problem with specifying https://dns.adguard.com/dns-query in AdGuard Home is that it requires keeping outbound UDP port 53 open for initial plaintext DNS bootstrapping. I can't use https://dns.adguard.com/dns-query if I block UDP port 53.

I want to prevent all plaintext DNS information leaving my network. When I specify SDNS addresses below, I can keep outbound UDP port 53 blocked because SDNS addresses use TCP port 443 and Raspberry Pi TCPDump shows only encrypted DNS resolution without initial bootstrapping:
sdns://AgEAAAAAAAAADDk0LjE0MC4xNC4xNAAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk
sdns://AgEAAAAAAAAADDk0LjE0MC4xNS4xNQAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk

**Comment by ameshkov** [comment]
Well, the easiest way to avoid this would be to use `https://94.140.14.14/dns-query` (default) or `https://94.140.14.140/dns-query` (non-filtering)

**Comment by EntropySmoke** [comment]
I'll try that, but why not SDNS stamps? And which ones are the correct ones?

**Comment by ameshkov** [comment]
> I'll try that, but why not SDNS stamps? And which ones are the correct ones?

Merely because when you look at one, it's unclear what is the actual DNS server encoded there.

Both are correct, and using just the first one would be enough.
