### ISSUE TITLE
www.googleadservices.com returns 127.0.0.1 with protection disabled

### ISSUE THREAD

**Issue by nicolaevladescu** [AdguardTeam/AdGuardHome#2528]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.104.3
* **How did you setup DNS configuration:**
  * System?
* **Operating system and version:**
  * Docker container

### Expected Behavior
Disable protection = resolve all domains

### Actual Behavior
www.googleadservices.com returns 127.0.0.1
"DNS Server" field is missing in the "Response details" of Query Log Response column of the entry

### Screenshots

<details>
<summary>
Query Log and dig output
</summary>

![ss1](https://user-images.githubusercontent.com/465824/104070160-e3373d00-520e-11eb-86b1-081db0f947f9.jpg)
![ss2](https://user-images.githubusercontent.com/465824/104070289-35785e00-520f-11eb-9c16-b800c1ba1ed3.jpg)

</details>

**Comment by ameshkov** [comment]
Could it be that you're using a DNS server with filtering (like AdGuard DNS) as an upstream?

You'd better use a non-filtering upstream with AdGuard Home.

**Comment by nicolaevladescu** [comment]
It could be, but because the "DNS Server" field is missing in the "Response details" of Query Log Response column of the entry, i can't tell, i am using a bunch of upstream DoH servers. I am thinking of opening a separate bug about this.

**Comment by nicolaevladescu** [comment]
So i removed the upstream servers and tested them one by one, indeed i found the culprits that have extra filters:

- https://dnsforge.de/dns-query
- https://doh-de.blahdns.com/dns-query
- https://doh-fi.blahdns.com/dns-query

Sorry for the trouble.
