### ISSUE TITLE
Add Custom Block page

### ISSUE THREAD

**Issue by FrancescoFdd5** [AdguardTeam/AdGuardHome#2529]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v ] I am running the latest version
- [v ] I checked the documentation and found no answer
- [v ] I checked to make sure that this issue has not already been filed

I would like to ask if it was possible that in the next versions the possibility of returning an error page in case of blocked url is added.
And to add the option to put a url as an error page

Like this one: [https://user-images.githubusercontent.com/29142494/74101828-250ebd80-4b3e-11ea-97d0-be3a9cc6ec1b.png](url)

**Comment by ameshkov** [comment]
Here's how it's recommended to do now:
https://github.com/AdguardTeam/AdGuardHome/issues/454#issuecomment-548269055

For now, we don't plan to go further and implement our own TLS pixel.
