### ISSUE TITLE
Custom Search for Clients

### ISSUE THREAD

**Issue by sudheeshb** [AdguardTeam/AdGuardHome#2530]
I want to search for a particular clients for certain dates. I don't see an option for this. I can do a filter in 'Query logs' window and scroll down. But but the scrolling is limited and seems to be working only for a half a day. But there is an option to store the logs for 30days. 90days etc. How do I perform search for a client say 10 days ago?

**Comment by ameshkov** [comment]
For now the only thing you can do is search for the client's IP address. AGH does not support searching by client name yet.

**Comment by sudheeshb** [comment]
Thanks. I am searching via IP address only.  But If search via Query log window, I get only recent logs ( probably half a day before ) . I  want an option for searching for certain dates via IP address.  As the logs are stored for 30 days , I believe I should be able to get the clients log up to 30 days.    I don't see see an option to that.  

For example:  I want to search for a client (IP address only ) for the query logs 5 days ago.  How do I do that?  .

**Comment by ameshkov** [comment]
Most likely this is a different bug. Could you please try the latest beta version of AGH and see if it's already fixed?

**Comment by sudheeshb** [comment]
Thanks.  I will check that.   Do we have different ways of searching  in the new version?  ( Instead of search by IP and scrolling down? ).  Scrolling down is not very efficient if you want to get logs says 20 days before.

I noticed that json file contains logs for longer duration.  I can do the search on json fie, but again not an efficient way doing this.

**Comment by ameshkov** [comment]
querylog.json contains all the log data, you can use it. Or you could use the REST API to do the same (it also supports offset/limit parameters, you could specify a large value there).

**Comment by sudheeshb** [comment]
Thanks. I will try to use querylog.json file and search inside that.  Is there any example code on how to use REST API for this purpose?

**Comment by ameshkov** [comment]
Check the spec here: https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

You don't need any special code for loading query logs, you can just open it in your browser:
`http://AGH/control/querylog?search=&offset=0&limit=100`

**Comment by sudheeshb** [comment]
Thanks.  Will check that!.  I have unrelated question.  I did a posting in the reddit and didn't a response on that.  https://www.reddit.com/r/Adguard/comments/klyr83/adguard_home_schedule_for_block_list/

// Post below.   I am using cron job for this and seems to be working well.   Is there any better way to achieve this?


I have recently moved to Adguard home from pihole. I was a long time pihole user. In pihole I can adjust the block based on time using some cron jobs.

Example: I want to block only some websites ( say facebook, reddit etc ) during certain time ( say 9 am to 1pm ) for certain devices. This was possible in Pihole with cronjobs.

I am thinking of the following to do it in Adguard Home. The below three steps will run as a cron job at 9am and 1pm.



Stop Adguard home ( via command line )

Modify AdGuardHome.yaml as per the needs ( ie update the blocked website details )

Start Adguard home.

Questions:

Will it work?

Is there any better way to achieve the same thing?

**Comment by ameshkov** [comment]
I guess it'd be better to reply there on Reddit then.

Here we go: https://www.reddit.com/r/Adguard/comments/klyr83/adguard_home_schedule_for_block_list/gip9m0a/?context=3

**Comment by sudheeshb** [comment]
Thanks!. Much appreciated..

**Comment by sudheeshb** [comment]
How do I retain my current settings, if I upgrade to a beta version?.  Do I need to take backup of  AdguardHome.yaml  from the current version and use that?.
Is there are compatibility issue for AdguardHome.yaml  between  the beta and current stable version?

I am using in FreeBSD ( pfSense router ).

**Comment by sudheeshb** [comment]
Also can you specify how to use 'older_than'   via REST API?

The following works.
http://192.168.1.1:81/control/querylog?older_than=2021-01-09T18:39:15.788276067-08:00

But If I change the time to some arbitrary number  it doesn't work.

for example  http://192.168.1.1:81/control/querylog?older_than=2021-01-08T18:39:15.788276067-08:00 doesn't work.  Here I simply changed the date from 2021-01-09 to 2021-01-08.   Looks I have to specify the exact time which was present in the query logs?.

**Comment by ameshkov** [comment]
> How do I retain my current settings, if I upgrade to a beta version?

You'd just need to back up `AdGuardHome.yaml`

> Also can you specify how to use 'older_than' via REST API?

I guess it'd be easier to avoid using it and stick to `offset`/`limit`
