### ISSUE TITLE
Upstream DNS for Specific Domain can be configured using IPv4 only

### ISSUE THREAD

**Issue by yonghan** [AdguardTeam/AdGuardHome#2532]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** 0.104.3
  * 
* **How did you setup DNS configuration:** router
  * 
* **If it's a router or IoT, please write device model:** Virtual Alpine Linux Edge on LXC, host proxmox
  * 
* **Operating system and version:** Alpine Linux 3.13 (edge)
  * 

### Expected Behavior

queries to specific domain forwarded to secondary dns server using ipv6
### Actual Behavior

queries to specific domain not forwarded if configured using ipv6
### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I have a dnsmasq listening on port 5353 to serve internal domains. Adguard is the main DNS server listening on port 53.
When I configured upstream DNS server in Adguard to point to my dnsmasq using ipv6, like this:
[/lan/]::1:5353
queries to the lan domain will fail. However, if I configured using ipv4 this way:
[/lan/]127.0.0.1:5353
queries will go through.

**Comment by ameshkov** [comment]
What about `[/lan/][::1]:5353`?

**Comment by yonghan** [comment]
That works!
