### ISSUE TITLE
Add SRV record like dnsmasq

### ISSUE THREAD

**Issue by kenyloveg** [AdguardTeam/AdGuardHome#2533]
Hi, Guys
 How to translate below dnsmasq record to Adguard Home?
`srv-host=_vlmcs._tcp.lan,OpenWrt-SE.lan,1688,0,100`
Thanks.

**Comment by ameshkov** [comment]
@ainar-g can we use `$dnsrewrite` for this?

**Comment by ainar-g** [comment]
@ameshkov, I don't see why not, but you'll need to decide whether it should go in v0.105.0 or in the next patch.

**Comment by ameshkov** [comment]
@ainar-g 

Ah, so it's not supported in v0.105 yet?

Nvm, let's plan it for v0.106 then.

**Comment by DandelionSprout** [comment]
I appear to get SRV records as of 0.105.0-beta2, as well as NAPTR, neither of which I think I've received before, if that is relevant to anything. 
![image](https://user-images.githubusercontent.com/22780683/106111116-f3767400-614b-11eb-8efb-2fc885557324.png)

Admittedly it may also be because I began using my phone's native Android settings for static LAN IP a week ago.

**Comment by ameshkov** [comment]
Hmm, @ainar-g how does that response look in serialized form? `[object Object]` looks weird, is it our mistake?

**Comment by ainar-g** [comment]
@ameshkov, @DandelionSprout, it's a real server bug.  Filed a separate issue, fix should be ready soon.

**Comment by ainar-g** [comment]
@kenyloveg, @DandelionSprout, as of snapshot 75ac1a53 you should be able to send `SRV` records using these custom rules:

```none
||_xmpp-server._tcp.example.org^$dnsrewrite=NOERROR;SRV;10 60 8080 xmpp.example.org
```

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to file new issues if you find any problems with the solution.

**Comment by SMAW** [comment]
> @kenyloveg, @DandelionSprout, as of snapshot [75ac1a5](https://github.com/AdguardTeam/AdGuardHome/commit/75ac1a5346d665193ea43caf1a567c1e47bfcc5e) you should be able to send `SRV` records using these custom rules:
> 
> ```
> ||_xmpp-server._tcp.example.org^$dnsrewrite=NOERROR;SRV;10 60 8080 xmpp.example.org
> ```

Has anyone got this working? I've tried to create a record like that, but when I run a nslookup to the record I get back teh following : can't find _****._tcp: Not implemented.
