### ISSUE TITLE
Error compiling client2 dependency!

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#2534]
![image](https://user-images.githubusercontent.com/45259624/104128206-2cb79180-53a1-11eb-94d2-ea5e756f0eaa.png)
![image](https://user-images.githubusercontent.com/45259624/104128301-c97a2f00-53a1-11eb-8144-719175b4616f.png)

**Comment by ameshkov** [comment]
What version of nodejs you're using? Should be either node 12 or node 14

**Comment by zxlhhyccc** [comment]
> What version of nodejs you're using? Should be either node 12 or node 14

nodejs  v14.15.3

**Comment by ameshkov** [comment]
Weird. Anyways, check what environment we use in Github actions:
https://github.com/AdguardTeam/AdGuardHome/blob/master/.github/workflows/build.yml

https://github.com/AdguardTeam/AdGuardHome/runs/1655542400
