### ISSUE TITLE
nslookup of local clients (upstream dnsmasq) doesn't display the correct IPv6 address

### ISSUE THREAD

**Issue by qosmio** [AdguardTeam/AdGuardHome#2535]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.105.0-SNAPSHOT-ce55625d
* **How did you setup DNS configuration:**
  *  Router
* **If it's a router or IoT, please write device model:**
  *  R7800 OpenWRT
* **Operating system and version:**
  *  OpenWRT Master

### Expected Behavior
NOTE: This is querying dnsmasq directly on port 1745
```
Name:	iphone-6s-plus.lan
Address: 192.168.1.53
Name:	iphone-6s-plus.lan
Address: fd00:cafe:cafe::53
```

### Actual Behavior
```
Non-authoritative answer:
Name:	iphone-xs-max.ate.cx
Address: 192.168.1.125
Name:	iphone-xs-max.ate.cx
Address: ::ffff:192.168.1.125
```

### Additional Information
I currently have AdGuard running as my primary and dnsmasq as my upstream for all local addresses.
```[///1.168.192.in-addr.arpa/lan/]127.0.0.1:1745```

**Comment by ainar-g** [comment]
Hi, thank you for your report and sorry for the long silence.  Is the behaviour the same when you query AdGuard Home directly, not over `dnsmasq`?

**Comment by ainar-g** [comment]
@qosmio, there have been a couple of releases since then.  Does this still occur?

**Comment by ainar-g** [comment]
There were no further updates from the OP, so closing.
