### ISSUE TITLE
DHCP bug after DHCP reboot

### ISSUE THREAD

**Issue by teamvlcateb** [AdguardTeam/AdGuardHome#2537]
### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by teamvlcateb** [comment]
### Issue Details



* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior


### Actual Behavior


### Screenshots


<details><summary>Screenshot:</summary>



</details>

### Additional Information

**Comment by ameshkov** [comment]
I am pretty sure that this is a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/2304

You could try the beta version to see if it's fixed in your case
