### ISSUE TITLE
Please change some feature

### ISSUE THREAD

**Issue by leonardwoo** [AdguardTeam/AdGuardHome#2539]
1. Can I hide PTR records in the log? Most of the time PTR logs are not needed to be viewed. It would be better to make it an option.
2. Can block services support custom lists? Although the existing list covers a lot of services, there are always some services that are region specific.
3. I hope to show the monitoring data of the hardware condition of the host. Especially for devices like the Raspberry Pi, it is more necessary.

THANK YOU

**Comment by ameshkov** [comment]
Hello,

There are already existing feature requests for all three points, eventually we'll implement all that.

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/594 #1692 #1685

**Comment by ameshkov** [comment]
Regarding PTR, described everything here: https://github.com/AdguardTeam/AdGuardHome/issues/2704
