### ISSUE TITLE
Добрый, не блокирует VK.COM ((( уже по всякому....

### ISSUE THREAD

**Issue by Pheasant2003** [AdguardTeam/AdGuardHome#2540]
Добрый, не блокирует vk.com AdGuard Home(((  

правила прописал все))
||vk.com^$important
@@||vk.com^$important
127.0.0.1 vk.com 
/vk.com/

и нехирашеньки(( 
как победить? 

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Pheasant2003** [comment]
Да, дополнение.
во вкладке Заблокированные сервисы, все заблокировал!

**Comment by ameshkov** [comment]
К сожалению, блокировки на уровне DNS недостаточно для ВК, нужны косметические правила (а значит, "большой" AdGuard).
