### ISSUE TITLE
this CPU has no floating point hardware, so it cannot run (use armv5 on an armv7 device)

### ISSUE THREAD

**Issue by FrancYescO** [AdguardTeam/AdGuardHome#2542]
Simply use the install script on an armv7l device (Technicolor DGA4130) is not working as it asks to install the armv5 version (that will work) can we manage this case in the install script?
```
root@DGA4130:/tmp# sh install.sh
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Script called with root privileges
[info] AdGuard Home will be installed to /opt/AdGuardHome
[info] Downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv7.tar.gz -> AdGuardHome_linux_armv7.tar.gz
[info] Unpacking package from AdGuardHome_linux_armv7.tar.gz -> /opt
runtime: this CPU has no floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5.
[error] Cannot install AdGuardHome as a service
```

**Comment by EugeneOne1** [comment]
@FrancYescO, we've finally updated the installation script, so that should fix this issue.  Could you please check, if it work properly for you?

You can also look at the options, this script now accepts.  They are enumerated in [`README.md`](https://github.com/AdguardTeam/AdGuardHome#automated-install-linux-and-mac).

**Comment by jmytch** [comment]
Hello I have a Technicolor DJA0230 that runs ARMv7, however when I install AdGuardHome, the result shows core-dumped that cause router to crash/reboot on it own. What's the go here? 

I've tried ARMv5 as it install successfully but unable to access AdGuardHome on said mention ip such as `http://192.168.0.1:3000` and I even add `/install.html` after the port. It didn't work at all. What am I doing wrong here?

**Comment by FrancYescO** [comment]
Probably the issue is due to the filesystem used, try changing the launch script to use /tmp as config folder.
________________________________
Da: jmytch ***@***.***>
Inviato: giovedì 24 giugno 2021 04:10
A: AdguardTeam/AdGuardHome ***@***.***>
Cc: Francesco M ***@***.***>; Mention ***@***.***>
Oggetto: Re: [AdguardTeam/AdGuardHome] this CPU has no floating point hardware, so it cannot run (use armv5 on an armv7 device) (#2542)


Hello I have a Technicolor DJA0230 that runs ARMv7, however when I install AdGuardHome, the result shows core-dumped that cause router to crash/reboot on it own. What's the go here?

I've tried ARMv5 as it install successfully but unable to access AdGuardHome on said mention ip such as http://192.168.0.1:3000 and I even add /install.html after the port. It didn't work at all. What am I doing wrong here?

**Comment by FrancYescO** [comment]
Btw, i can confirm that actuallly the installer work, it still try to install the ARMv7 than try with the v5 and need some fixes due to the filesystem of this device but is okay
```
root@modemtim:~# curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v

starting AdGuard Home installation script
channel: release
operating system: linux
cpu type: armv7
AdGuard Home will be installed into /opt/AdGuardHome
checking curl
checking tar
script is executed with root privileges
no need to uninstall
downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv7.tar.gz -> AdGuardHome_linux_armv7.tar.gz
unpacking package from AdGuardHome_linux_armv7.tar.gz into /opt
runtime: this CPU has no floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5.
trying to use armv5 cpu
restarting with root privileges
starting AdGuard Home installation script
channel: release
operating system: linux
cpu type: armv5
AdGuard Home will be installed into /opt/AdGuardHome
checking curl
checking tar
script is executed with root privileges
no need to uninstall
downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv5.tar.gz -> AdGuardHome_linux_armv5.tar.gz
unpacking package from AdGuardHome_linux_armv5.tar.gz into /opt
2021/06/24 15:27:12 [info] Service control action: install
2021/06/24 15:27:12 [info] Service has been started
2021/06/24 15:27:12 [info] Almost ready!
AdGuard Home is successfully installed and will automatically start on boot.
There are a few more things that must be configured before you can use it.
Click on the link below and follow the Installation Wizard steps to finish setup.
2021/06/24 15:27:12 [info] AdGuard Home is available on the following addresses:
2021/06/24 15:27:12 [info] Go to http://127.0.0.1:3000
2021/06/24 15:27:12 [info] Go to http://[::1]:3000
2021/06/24 15:27:12 [info] Go to http://192.168.168.1:3000
2021/06/24 15:27:12 [info] Go to http://192.168.1.1:3000
2021/06/24 15:27:12 [info] Go to http://192.168.168.129:3000
2021/06/24 15:27:12 [info] Go to http://79.27.199.18:3000
2021/06/24 15:27:12 [info] Action install has been done successfully on unix-systemv
AdGuard Home is now installed and running
you can control the service status with the following commands:
sudo /opt/AdGuardHome/AdGuardHome -s start|stop|restart|status|install|uninstall
```
