### ISSUE TITLE
Please provide an Android/iOS app to Whitelist or Blacklist traffic (similar to FlutterHole)

### ISSUE THREAD

**Issue by yanniedog** [AdguardTeam/AdGuardHome#2545]
Please provide an Android/iOS app to Whitelist or Blacklist traffic (similar to FlutterHole)

**Comment by ameshkov** [comment]
Well, we'd be happy if anyone decides to implement anything like that.

So far, there's an iOS app that does that: https://apps.apple.com/us/app/adguard-home-remote/id1543143740

**Comment by yanniedog** [comment]
Please consider working with the FlutterHole dev team

**Comment by ameshkov** [comment]
Well, it's up to them, not to us. If there's anyone willing to develop such an app, we'd be happy to assist.

**Comment by yanniedog** [comment]
Can't you build it into the Adguard (Android) app?

**Comment by ameshkov** [comment]
We don't have such plans yet, AdGuard Home is a separate product.
