### ISSUE TITLE
Clickable "Blocked malware/phishing"

### ISSUE THREAD

**Issue by hnnweb** [AdguardTeam/AdGuardHome#2547]
The ability to click on "Blocked malware/phishing" on startpage to filter out which host that has access the malware / phising links.

This makes i possible to see what was blocked in Query log.

**Comment by ameshkov** [comment]
This one is clickable:

![image](https://user-images.githubusercontent.com/5947035/104319802-74016780-54f2-11eb-9d3e-70dac59a67ad.png)

**Comment by hnnweb** [comment]
Ah great!
