### ISSUE TITLE
Support multiple TLS certificate

### ISSUE THREAD

**Issue by git-noise** [AdguardTeam/AdGuardHome#2548]
### Problem Description
Only one TLS certificate seems to be supported by the GUI.

### Proposed Solution
Support at least two TLS certificates - one for the admin interface and one for the DNS services

### Alternatives Considered
One can use a reverse proxy and work around that limitation using virtualhosts. However, I am not sure the client address is adequately sent to and processed by Adguard upstream

### Additional Information
Thanks a lot for your work!

**Comment by ameshkov** [comment]
Merging into https://github.com/AdguardTeam/AdGuardHome/issues/741#issuecomment-759330329

Please upvote that task if you want this to be implemented sooner.
