### ISSUE TITLE
[Feature Request] Additional Blocklists per Client Group and/or ctg for a complete blocklist, not just for one line

### ISSUE THREAD

**Issue by TerminatorX42** [AdguardTeam/AdGuardHome#2553]
Problem:
For certain client groups I would like to use additional blocklists (as pihole allows). 
The only possibility I found is to use the ctg-feature, but that only allows additional lines/domains, not additional blocklists (via url).

### Proposed Solution
Allow additional blocklists per client group, 

### Alternatives Considered
or if it is easier allow "tagging" of the blocklists, resulting in them only being used for the clientgroups tagged accordingly.

**Comment by ameshkov** [comment]
We're going to add this shortly after redesign (so either v0.107 or v0.108)

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/435
