### ISSUE TITLE
AdGuard only saves about 15 minutes of query logging

### ISSUE THREAD

**Issue by scorpinus** [AdguardTeam/AdGuardHome#2557]
Version of AdGuard Home server: v2.6.1 running as an add-on in Home Assistant.
Home Assistant OS: Home Assistant OS 5.10
Supervisor version: 2020.12.7 
HA is running of an 500GB SSD on a Pi4, freespace is 461GB.

I'm having issues with the logging of AdGuardHome, the problem is that I have enabled the logging and set it to 90 days retention (through the generic settings in the WebUI), but when I check the 'Query Log' in the WebUI I can always only see the last 15 minutes. Also when I restart the AdGuard add-on I start with an empty query log. Why isn't it logging and retaining more?

What can I check or do?

**Comment by ameshkov** [comment]
Most likely this issue is already fixed in v0.105 beta. Could you please try it?

**Comment by scorpinus** [comment]
I'm not sure how. I install it through the supervisor add-on store and that only lets me install v2.61.

**Comment by scorpinus** [comment]
I'll wait and see then if that fixes my issue. Thx for your replies 👍

**Comment by ainar-g** [comment]
@scorpinus, did the update fix the issue?

**Comment by scorpinus** [comment]
Yeah that update fixed it.
