### ISSUE TITLE
ECH (Encrypted Client Hello) server-side support

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2558]
Hello,

it seems that ESNI will never be officially approved as RFC standard. So let's discuss the possibility of implementing ECH (Encrypted Client Hello) server-side support instead ESNI and advertises it via HTTPSSVC DNS record. This is necessary for transfer the encrypted host name due handshakes. More information here:
https://blog.cloudflare.com/encrypted-client-hello/
and here:
https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/

Correct me if I misunderstand anything😬

Thank you!
Cheers👻

**Comment by ameshkov** [comment]
Requires no changes on AdGUard Home side.
