### ISSUE TITLE
VPS Question?

### ISSUE THREAD

**Issue by Reynee07** [AdguardTeam/AdGuardHome#2560]
I'm not sure where to post / ask this question so excuse me if I am posting in the wrong place. I wouldn't mind setting up a VPS for Adguard Home but I'm not sure how you would go about that exactly and what would be a good cheap VPS that isn't too expensive?

**Comment by Aikatsui** [comment]
It's not necessary to use VPS, you can run it in your personal PC or router. We cannot recommend any company but you may able to choose after review about latency, privacy policy, pricing, and customer support etc.
https://github.com/AdguardTeam/AdGuardHome/wiki/VPS

**Comment by Reynee07** [comment]
> It's not necessary to use VPS, you can run it in your personal PC or router. We cannot recommend any company but you can check online and compare them before purchase
> https://github.com/AdguardTeam/AdGuardHome/wiki/VPS

Thanks for the response. I currently have Adguard Home setup on old windows machine that basically sits on all the time etc... I thought It might be a good idea to use it via using a VPS because it wouldn't be limited to home only and plus it probably more reliable becuase if the power goes it in our home it would need to be reboot manually. I was thinking maybe ChicagoVPS but I'm not exactly sure on that. I would need something that would be yearly and not monthly if anything.

**Comment by Aikatsui** [comment]
Check the above link. It has several providers mentioned, some are offer free credits $50-100 (eg: vultr, digitalocean) then usually cost according to your usage. As i said above you need to compare them according to your own way and decide.
