### ISSUE TITLE
Have a way to only log modified rules

### ISSUE THREAD

**Issue by michaelb-ae** [AdguardTeam/AdGuardHome#2561]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
In some case our space may be little or we don't want to have thousand of domain registered we will never do anything with.

### Proposed Solution
Add a way to only log modified response (accepted, rewritten, blocked, ip or CNAME) and don't log unfiltered domain.

### Additional Information
With this kind of filtering it will not only reduce size of log file (like other issue have asked), but will simplify the detection and correction of false-{positive,negative}, since we don't have to read many unfiltered domain who are not usefull and only add noise in the log.

**Comment by ameshkov** [comment]
But you can choose to see only "filtered" queries in the Query log, why is it not enough?

**Comment by michaelb-ae** [comment]
yes but at least let us change the default view, (and select filtered by default), but my view permit to reduce log size, but your permet to reduce dev, sot it's up to you 👍

**Comment by ameshkov** [comment]
Tbh, I don't like the idea of having a "selective" log like that in the name of just reducing the log size.

> change the default view

That could be a different feature request.
