### ISSUE TITLE
Any Plans On Adding Automatic Blocking For Clients Requesting Specific Domains?

### ISSUE THREAD

**Issue by brian31405** [AdguardTeam/AdGuardHome#2563]
- [ Y ] I am running the latest version
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed

I have found out recently that my AdGuardHome has been summiting specific request every second from ips around the world, They all request the same Domain "pizzaseo.com" , The huge amount of request even slows down my server's respond speed,No matter how hard I tries to block these wilful client, These client still manage to change their ip and return to my DNS Server doing continuious request, Any way to let AdGuardHome block them it self?

**Comment by ameshkov** [comment]
Not really.

However, you can simply add `pizzaseo.com` to the list of "Disallowed domains" in DNS settings. This way AGH will simply drop queries from such clients and they won't spam your stats.

Here's a list of the most popular domains used by them:
```
*dot199q1w2e3rty.*
version.bind
id.server
hostname.bind
*.tstng.net
pizzaseo.com
5hz.org
1x1.cz
dd0s.ga
hitnslab.cn
*.hitnslab.cn
67b.org
```

**Comment by brian31405** [comment]
> Not really.
> 
> 
> 
> However, you can simply add `pizzaseo.com` to the list of "Disallowed domains" in DNS settings. This way AGH will simply drop queries from such clients and they won't spam your stats.
> 
> 
> 
> Here's a list of the most popular domains used by them:
> 
> ```
> 
> *dot199q1w2e3rty.*
> 
> version.bind
> 
> id.server
> 
> hostname.bind
> 
> *.tstng.net
> 
> pizzaseo.com
> 
> 5hz.org
> 
> 1x1.cz
> 
> dd0s.ga
> 
> hitnslab.cn
> 
> *.hitnslab.cn
> 
> 67b.org
> 
> ```

Ameshkov:
  I think you misunderstand my question, I mentioned that there's many wilful clients requesting "pizzaseo.com".
About 20 request are sent to my server per second. All of them are sent by different ip addresses. I ment to block clients who make this request.
