### ISSUE TITLE
HostGator Question?

### ISSUE THREAD

**Issue by Reynee07** [AdguardTeam/AdGuardHome#2565]
I know you guys aren't affilated with HostGator or anything but I have something I want to ask to the community. I were to go to HostGator and click the shared host plan would be the better option (Ex. Hatchling Plan, or Baby Plan) and what would I enter for the domain and suck when filling it out? I want to just host Adguard Home on a VPS.

Thanks.

**Comment by Aikatsui** [comment]
You said VPS, see https://www.hostgator.com/vps-hosting
above you trying with website hosting, i'm not sure if possible for manage to run that due resources limitations, need to explore further however you may still violate their TOS https://www.hostgator.com/web-hosting

**Comment by Reynee07** [comment]
Ah okay. You can close this them. thanks

**Comment by Aikatsui** [comment]
Please note, when use a VPS then you need to know how to secure it (including get benefit from firewalls, monitoring tools and other security solutions) otherwise if someone gained unauthorize access (known as hack) to your server then will compromise your home network and devices
