### ISSUE TITLE
Lot of "dummy" requests

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2566]
Hello, I am not sure if this is a bug.

I get a high count of requests called " dummy" basicly 4 per hour. In "Top queried domains" section its on second place.

I am using AdGuardHome v0.105.0-SNAPSHOT-56cb8a4d

![Screenshot_20210115-203902](https://user-images.githubusercontent.com/56163305/104772337-8b02bc80-5773-11eb-9bbf-9daa445133ee.png)

**Comment by Aikatsui** [comment]
Probably any installed application error or misbehave activity on that clients

**Comment by ameshkov** [comment]
Yeah, it seems some device or app misbehaves, this does not come from AGH itself.

Anyways, if you figure out where they come from, please let us know.

**Comment by uservictor** [comment]
It comes from my ISP router/modem, as far I can say blocking "dummy" requests has no side effects.
