### ISSUE TITLE
Big question about vps and latency

### ISSUE THREAD

**Issue by michaelb-ae** [AdguardTeam/AdGuardHome#2567]
Hello,
Actually i have a question to migrate my ADH to a VPS, since you have experience with this kind of thing (see your dns),
Does you have some recommandation for a minimal latency (VPS provider or configuration of the server).

Thanks

**Comment by ameshkov** [comment]
Well, it's easier to choose a simple option with many locations like DO or Vultr, just use a location that's closer to you.

Regarding configuration, there are no special requirements. However, if you're getting a VPS, I suggest getting a TLS certificate and using DoH or DoQ whenever you can.
