### ISSUE TITLE
Nat port forward to force use AdGuardHome doesn't work

### ISSUE THREAD

**Issue by Gogolathome** [AdguardTeam/AdGuardHome#2568]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.3
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * OPNsense 20.7.7_1
* **Operating system and version:**
  * FreeBSD 12

### Expected Behavior

All DNS traffic force use of AGuardHome
### Actual Behavior

AdGuardHome responds with source address of LAN interface instead of NAT address
### Screenshots

<details><summary>Screenshot:</summary>

![GOODresponse](https://user-images.githubusercontent.com/77412327/104792612-3d03ae00-579f-11eb-90ad-b3bc33f20842.jpg)
![FALSEresponse](https://user-images.githubusercontent.com/77412327/104792644-586eb900-579f-11eb-84e4-b55a64e11982.jpg)

</details>

### Additional Information

When I run my standard setup with Unbound listening on port 53 and forwarding to DNScrypt-proxy listening on port 10053 and my NAT and firewall rules active DNS traffic is transparently handled. A DIG command to for instance @8.8.8.8 gives an answer as if 8.8.8.8 was used. See first screenshot.
But when I disable Unbound/DNScrypt-proxy and run AdGuardHome I don't get an answer with DIG, but I can see the traffic like in second screenshot.
The difference is that AdGuardHome answers with the IP address of my LAN interface.
I can't imagine that there is a setting that is wrong in AdGuardHome.
I also disabled protection as a test but that makes no difference.

**Comment by ameshkov** [comment]
I am not fully sure why this happens, but you may want to inspect the code that's responsible for setting this:
https://github.com/AdguardTeam/dnsproxy/blob/543ff66daeeb233275815941e339aaebfd3e0745/proxyutil/udp_unix.go

See `UDPRead ` and `UDPWrite`

**Comment by Gogolathome** [comment]
I am sorry, but this goes beyond my knowledge, and I didn't explain it well enough as I read back my OP.
I tried to force all DNS requests through AdGuardHome with a port forward 53 to 127.0.0.1. That didn't work.
As a test I port forwarded to another host running AdGuardHome and that worked as it should.
Then I port forwarded to a listening interface 192.168.10.1 instead of 127.0.0.1 and that worked, so problem solved.
It is guessing why intercepting all DNS traffic with a port forward to 127.0.0.1:53 doesn't work. AdGuardHome is listening on all interfaces.

<img width="435" alt="Schermafbeelding 2021-01-18 om 11 14 30" src="https://user-images.githubusercontent.com/77412327/104903490-5fa0ed00-5980-11eb-9558-cf038d5e5b82.png">
