### ISSUE TITLE
DoH invalid certificates

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#2570]
### Issue Details

* **Version of AdGuard Home server:**
0.104.3
* **How did you setup DNS configuration:**
Router DHCP assigned
* **If it's a router or IoT, please write device model:**
Raspberry Pi 3 Model B
* **Operating system and version:**
Debian 10

### Expected Behavior
I expect DoH to work...

### Actual Behavior
So, unsure if this is a bug, but this morning all DoH providers stopped working in AdGuard Home.
My main upstream DNS was set to Cloudflare: https://cloudflare-dns.com/dns-query If I hit the 'Test upstream Servers' button on the UI I get:

"Server "https://cloudflare-dns.com/dns-query": could not be used, please check that you've written it correctly"

When I enter this into a browser I get an "Invalid Certificate Authority message", so I assume thats the issue. However I tried a number of different DoH providers and I get exactly the same thing, including https://dns.adguard.com/dns-query

The only DoH URL I can currently get to work is https://dns-unfiltered.adguard.com/dns-query ( which is odd, because the filtered adguard URL does not work...)

No idea whats going on here, but I dont know what local problem I could have that would cause this...(assuming its not a global issue which I doubt)

### Screenshots
![image](https://user-images.githubusercontent.com/59442445/104845383-0c219700-58cd-11eb-83c9-76824d73730d.png)

![image](https://user-images.githubusercontent.com/59442445/104845419-48ed8e00-58cd-11eb-831c-283d6ad24da5.png)

**Comment by ameshkov** [comment]
There're many possible reasons:

1. Make sure the root certificates on your devices are up-to-date.
2. Examine these certificates, maybe you're using some MITM proxy or something like that.

Anyways, this has no direct connection to AdGuard Home so I am closing this.
