### ISSUE TITLE
Scheduler capabilities

### ISSUE THREAD

**Issue by theyort** [AdguardTeam/AdGuardHome#2572]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Problem Description

It would be nice if with de client configuration, we have to be able to to schedule ON/OFF dns for a range or only for a device, like for example, no surf between 23:00 to 07:00 for some devices, and non-blocking for the others
### Proposed Solution

Add a scheduler on the clients configuration screen
### Alternatives Considered

The only alternative i've found, it's a cron to stop the adguard to switch off during the night (adguardhome is only used at home by 3 devices of my son)

**Comment by ameshkov** [comment]
Duplicates #951

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1203
