### ISSUE TITLE
Query Log: ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Cebeerre** [AdguardTeam/AdGuardHome#2578]
### Issue Details

* **Version of AdGuard Home server:**
  *  0.105.0-beta.2 (but same issue with the latest stable snapshot, upgraded to beta trying to fix the issue)
* **How did you setup DNS configuration:**
  *  Router
* **If it's a router or IoT, please write device model:**
  *  x86_64 board
* **Operating system and version:**
  *  OpenWRT 19.07.4 (stable, x86_64 target)

### Expected Behavior

To be able to filter the Query Log based on the selected criteria. 

### Actual Behavior

In the Query Log, when selecting "Blocked Threads" or "Blocked Adult Websites" raises an error even whith 0 entries in that categories based on the statistics.

`Error: control/querylog?search=&response_status=blocked_safebrowsing&older_than=&limit=20 | Network Error`

`Error: control/querylog?search=&response_status=blocked_parental&older_than=&limit=20 | Network Error`

The actuall call to `/control/querylog?search=&response_status=blocked_parental&older_than=&limit=20` returns a `ERR_EMPTY_RESPONSE`

I've tried to see something in the logs in verbose but only the GET requests appears. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

* Query Log Retention: 24h
* Statistics Retention: 24h
* DNS queries in 24h: Roughly 40k
* I've moved the /data directory to a tmpfs as I thought that maybe the problem was due to a slow SD, but the issue reproduces anyway.

**Comment by ameshkov** [comment]
What kind of error do you see in the browser's dev console -> network tab?

**Comment by Cebeerre** [comment]
> What kind of error do you see in the browser's dev console -> network tab?

![Screenshot 2021-01-19 at 20 54 58](https://user-images.githubusercontent.com/44902718/105085870-b0a40480-5a98-11eb-9c09-e0d0da23e583.png)

**Comment by ameshkov** [comment]
Hmm, this one is weird. There should be at least some HTTP response status.

Do you see anything relevant in AdGuard Home log when you enable it?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue

**Comment by Cebeerre** [comment]
That's the weird thing as well, the log file doesn't show any error, nothing ... just:

```
2021/01/19 20:07:14 21428#132 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:07:25 21428#132 [debug] QueryLog: prepared data (2/50015) older than 0001-01-01 00:00:00 +0000 UTC in 10.396784308s
2021/01/19 20:07:25 21428#143 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:07:35 21428#143 [debug] QueryLog: prepared data (2/50017) older than 0001-01-01 00:00:00 +0000 UTC in 10.382340635s
```

**Comment by ameshkov** [comment]
What about the "Network" tab in the browser? Do you see what exactly do those responses contain? Response headers, response status, etc

**Comment by Cebeerre** [comment]
There's no response status, as it's raising a `ERR_EMPTY_RESPONSE`

Headers:

````
Request URL: http://localhost:8081/control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
Referrer Policy: strict-origin-when-cross-origin
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: es,en-US;q=0.9,en;q=0.8,ca;q=0.7
Connection: keep-alive
Cookie: agh_session=9fdcea5d526af695d27b9ab1d3aa15366f57ec6a4b19ba7a906c9c26b62fe74c
Host: localhost:8081
Referer: http://localhost:8081/
sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
search: 
response_status: blocked_parental
older_than: 
limit: 20
````

**Comment by ameshkov** [comment]
Hm, that's super weird, I can't reproduce this and I can't even see in our code how this is possible without. The only possibility is if AGH crashes. In this case there should be something in syslog about the crash.

**Comment by Cebeerre** [comment]
AGH keeps working as expected answering DNS requests and I can even just go back to the main page without issues.

I've tried with Safari and doest the same thing. Tried with Firefox and it does the same thing, but it takes like two minutes to raise the `ERR_EMPTY_RESPONSE`. 

Funny thing, is that even the browser just sends a single `GET` the log shows multiple queries and it says 2 from X, when the statistics say 0. 

```
2021/01/19 20:32:30 24948#91 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:32:41 24948#91 [debug] QueryLog: prepared data (2/50019) older than 0001-01-01 00:00:00 +0000 UTC in 10.218064657s
2021/01/19 20:32:41 24948#140 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:32:51 24948#140 [debug] QueryLog: prepared data (2/50020) older than 0001-01-01 00:00:00 +0000 UTC in 10.352839324s
2021/01/19 20:32:51 24948#161 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:33:01 24948#161 [debug] QueryLog: prepared data (2/50027) older than 0001-01-01 00:00:00 +0000 UTC in 10.413324549s
2021/01/19 20:33:01 24948#196 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:33:12 24948#196 [debug] QueryLog: prepared data (2/50040) older than 0001-01-01 00:00:00 +0000 UTC in 10.38306669s
2021/01/19 20:33:12 24948#242 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:33:22 24948#242 [debug] QueryLog: prepared data (2/50043) older than 0001-01-01 00:00:00 +0000 UTC in 10.284059952s
2021/01/19 20:33:22 24948#239 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:33:32 24948#239 [debug] QueryLog: prepared data (2/50044) older than 0001-01-01 00:00:00 +0000 UTC in 10.124780873s
2021/01/19 20:33:32 24948#245 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:33:43 24948#245 [debug] QueryLog: prepared data (2/50047) older than 0001-01-01 00:00:00 +0000 UTC in 10.306393883s
2021/01/19 20:33:43 24948#259 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:33:53 24948#259 [debug] QueryLog: prepared data (2/50048) older than 0001-01-01 00:00:00 +0000 UTC in 10.093854085s
2021/01/19 20:33:53 24948#254 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:34:03 24948#254 [debug] QueryLog: prepared data (2/50051) older than 0001-01-01 00:00:00 +0000 UTC in 10.24438147s
2021/01/19 20:34:03 24948#278 [debug] GET /control/querylog?search=&response_status=blocked_parental&older_than=&limit=20
2021/01/19 20:34:13 24948#278 [debug] QueryLog: prepared data (2/50056) older than 0001-01-01 00:00:00 +0000 UTC in 10.197450247s
```

**Comment by ameshkov** [comment]
No idea what's going on so far:(

Could it be that you have some software interfering with this?

**Comment by Cebeerre** [comment]
Clearing the log and the statistics make it work again, but all the times I've tried it goes back to this weird behaviour when the log grows. 

I've restarted the whole thing (including the router itself), I'll try to detect when starts failing again.

**Comment by dlmpx** [comment]
Hello, I encountered the same problem, is it solved?
