### ISSUE TITLE
Top visited and blocked categories on dashboard

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#2579]
New components for AdGuardHome dashboard

![image](https://user-images.githubusercontent.com/63988538/105100254-9c372a80-5adf-11eb-8865-5e7bd08dd59b.png)
(Credits: https://www.mimecast.com/products/web-security)

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2230

**Comment by ameshkov** [comment]
This kinda duplicates the categories feature request. If at some point we add categories, we'll of course add some stats regarding them as well.
