### ISSUE TITLE
AdGuard DNS significantly slows down DIRECTV app for Roku

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardHome#258]
App: https://channelstore.roku.com/details/140474/directv-now

### Steps to reproduce
1. Enable AdGuard DNS in the router
2. Launch the DIRECTV app on a Roku
3. User reports extensive video buffering and loading

### Expected behavior
Extensive video buffering and loading

### Actual behavior
Shouldn't affect DIRECTV this much

<details><summary>Screenshot:</summary>

N/A

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, 176.103.130.130
| How did you setup DNS configuration:| Router
| Device model:| unspecified Roku
| Operating system and version:| Roku firmware

**Comment by vozersky** [comment]
@akmLaVx is there any way to record a dns requests log?
