### ISSUE TITLE
Advertisement filtering rules cannot be deleted

### ISSUE THREAD

**Issue by da-gongren** [AdguardTeam/AdGuardHome#2580]
Advertisement filtering rules cannot be deleted

Version: AdGuardHome_linux_arm64 0.105.0-beta.2

environment：CentOS Linux release 7.9.2009 (AltArch)

![image](https://user-images.githubusercontent.com/51149477/105123673-73c92380-5b13-11eb-8c4f-1d431be65088.png)

![image](https://user-images.githubusercontent.com/51149477/105123681-762b7d80-5b13-11eb-9b84-605259b8e730.png)

**Comment by Aikatsui** [comment]
For now, Refresh and try again otherwise erase filter entries from adguardhome.yml file

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
