### ISSUE TITLE
Username should not be case sensitive

### ISSUE THREAD

**Issue by Gill-Bates** [AdguardTeam/AdGuardHome#2581]
During login, the username seems to be case sensitive.

in my Case: admin will work, Admin not.

Bug or Feature?

**Comment by mdawsonuk** [comment]
I have made a PR and tested it locally, this now works as expected. Hopefully this can be brought forward and merged for v0.107.6 or v0.108.0

**Comment by mdawsonuk** [comment]
Hi @ameshkov is there any chance of this being merged into v0.108?

**Comment by ainar-g** [comment]
I don't think we'll make this change.  A user's login is a piece of the sensitive authentication data.  Unlike, say, a display name, which (if AGH user accounts ever get it) should be searchable in a case-insensitive manner.

@mdawsonuk, I'll close this issue and your PR.  Apologies for this taking way too long.

**Comment by mdawsonuk** [comment]
> I don't think we'll make this change.  A user's login is a piece of the sensitive authentication data.  Unlike, say, a display name, which (if AGH user accounts ever get it) should be searchable in a case-insensitive manner.
> 
> 
> 
> @mdawsonuk, I'll close this issue and your PR.  Apologies for this taking way too long.

It is pretty unusual for usernames to be case-sensitive, this is pretty commonplace practice ranging from Operating Systems accounts to forums and other online accounts.
