### ISSUE TITLE
Blocklist domains are allowed

### ISSUE THREAD

**Issue by laxotor** [AdguardTeam/AdGuardHome#2583]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.104.3
* **How did you setup DNS configuration:**
  *  VPS
* **Operating system and version:**
  *  Ubuntu 20.04

### Actual Behavior

Certain domains registered on the block list are allowed.

For example
@@://www.googleadservices.com^|
@@dnsotls-ds.metric.gstatic.com^
@@||launches.appsflyer.com^|
@@||app.adjust.com^|
etc

### Screenshots

<details><summary>Screenshot:</summary>

![14](https://user-images.githubusercontent.com/43947445/105230654-0667d200-5ba9-11eb-8df2-043952263821.png)
![15](https://user-images.githubusercontent.com/43947445/105230657-0798ff00-5ba9-11eb-9fe0-c024761dff98.png)

</details>

**Comment by alexpovel** [comment]
Taking `@@://www.googleadservices.com^|`  as an example, see the comment [above that line](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt):

```text
! https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/289
! Fixing Google Shop and Google Ads in search results.
! These ads cannot be hidden on the DNS-level, so we should not break clicks on the adverts
```

That comment and the issue at AdguardTeam/AdGuardSDNSFilter/issues/289 explain the reasoning behind allowing them. It's not a bug and you can disable the blocklist.

**Comment by ameshkov** [comment]
You can also disable individual rules by adding a `$badfilter` modifier like this:
`@@://www.googleadservices.com^|$badfilter`
