### ISSUE TITLE
Is there a ignore address or skip address feature?

### ISSUE THREAD

**Issue by elonj** [AdguardTeam/AdGuardHome#2586]
Hello, 
Is there a ignore address or skip address feature? Because a domain can have multiple ips, some of the ips can not be connected. Is there a feature to ignore the unconnectable ips and only use the valid ips?

For example, google.com has the following dns result:
A: 216.58.194.170 (ttl=180)
A: 216.58.195.74 (ttl=180)
A: 172.217.6.78 (ttl=180)
A: 172.217.6.46 (ttl=180)
A: 172.217.164.110 (ttl=180)
A: 142.250.72.206 (ttl=180)

The 216.58.194.170 and 216.58.195.74 cause timeout issue in my network. Can adguard home ignore or skip 216.58.194.174 and 216.58.195.78 to get next valid ips (eg: 172.217.6.78)? Probably similar to the ignore-address feature of the dnsmasq.

If there is other solutions, please give me a hand. This troubles me a lot. Thanks

**Comment by ameshkov** [comment]
@elonj it can be enabled via the configuration file, just find `bogus_nxdomain` there: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration

**Comment by elonj** [comment]
Can you please explain a little bit about bogus_nxdomain? I list some ips in bogus_nxdomain. If one of the ips in the bogus_nxdomain gets returned from DNS, will it try to get another one ip that is not in the list of bogus_nxdomain? Also, if I list ips in bogus_nxdomain, they will work automatically without any enable option, right? Thanks

**Comment by ameshkov** [comment]
`bogus_nxdomain` works exactly like it does in `dnsmasq` (it is added for compatibility reasons).

So when AdGuard Home encounters a bogus IP in a DNS response, it will simply respond with NXDOMAIN and not check other IPs.

If you want to filter out "bad" IP addresses, I suggest you try enabling "fastest IP address" policy in AGH DNS settings.

**Comment by elonj** [comment]
> `bogus_nxdomain` works exactly like it does in `dnsmasq` (it is added for compatibility reasons).
> 
> 
> 
> So when AdGuard Home encounters a bogus IP in a DNS response, it will simply respond with NXDOMAIN and not check other IPs.
> 
> 
> 
> If you want to filter out "bad" IP addresses, I suggest you try enabling "fastest IP address" policy in AGH DNS settings.

Thanks. I will try the "Fastest up address ".
