### ISSUE TITLE
Long DNS Processed Time

### ISSUE THREAD

**Issue by begundal** [AdguardTeam/AdGuardHome#2590]
Some of my dns processed time took very long, is this a normal behaviour?
![dns process](https://user-images.githubusercontent.com/342539/105383027-44193900-5c43-11eb-8722-f9bb80567583.jpg)

```
pi@rpi4:~ $ uname -a
Linux rpi4 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
pi@rpi4:~ $

```
Using Version: 0.104.3

**Comment by ameshkov** [comment]
Well, yeah, some queries may take more time than others, that depends on the upstream you're using.

You can take a look at AGH logs if you want to check what exactly takes time.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`

**Comment by begundal** [comment]
![trace](https://user-images.githubusercontent.com/342539/105493094-80a06f80-5ceb-11eb-90d6-60cc9dee3d6e.jpg)
depends on the upstream I'm using, is that means it's the upstream fault? or because of my latency to the dns upstream?
My latrency to the dns upstream that is dns.cloudflare.com is roughly 3-4ms

**Comment by ameshkov** [comment]
Latency is just a part of that. The upstream needs to get that response from authoritative servers first, this may take time.
