### ISSUE TITLE
Question: Running AdGuard Home via Loopback VS Local IP?

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#2591]
Assume that:
- Router IP is 10.0.0.2
- Raspberry Pi is the local DNS server running AdGuard Home and has static IP 10.0.0.5 configured in dhcpcd.conf
- Router is set to use 10.0.0.5 for DNS resolution
- All local clients are set to use 10.0.0.5 for DNS resolution 
 
If I want the same Raspberry Pi to also be its own client and to resolve DNS using AdGuard Home service, I can set static DNS IP in Raspberry Pi dhcpcd.conf to either 10.0.0.2 or 10.0.0.5 or 127.0.0.1.

All 3 (10.0.0.2, 10.0.0.5, and 127.0.0.1) IP's seem to work, but what is the correct configuration? I think specifying router IP (10.0.0.2) for static DNS address in Raspberry Pi dhcpcd.conf creates a needless loop, but I am not sure about Raspberry Pi IP 10.0.0.5 VS Localhost IP 127.0.0.1... Are there any Pros or Cons?

I use "block-all, except" custom rules/filters in AdGuard Home and some blocked domains only show up when I specify 127.0.0.1 Localhost IP address for DNS resolution in Raspberry Pi dhcpcd.conf .

There is also 127.0.1.1, but isn't that an obsolete remnant?

**Comment by ameshkov** [comment]
Well, I might be wrong here, but 127.0.0.1 seems to be better to me since it's guaranteed to be up and reachable (not true for other interfaces).
