### ISSUE TITLE
security concern with VPS config

### ISSUE THREAD

**Issue by markkoek** [AdguardTeam/AdGuardHome#2592]
Hello,

I came across AdGuard today and it looks interesting. Thank you!

However I have one concern relating to security.

After I followed your instructions to install AdGuard Home on a VPS at https://github.com/AdguardTeam/AdGuardHome/wiki/VPS I was left with an open resolver out on the internet. The service resolves for anybody.

Might I suggest adding a feature to the setup that limits DNS requests to those from a configured set of IP addresses? For home users, it could probably default to the IP address that is using the setup web interface.

Thanks,

Mark

**Comment by ameshkov** [comment]
Hi,

First of all, AGH comes with rate limit enabled by default (20rps) which is rather low and mitigates DNS amplification.

Regarding the requested feature, AGH indeed allows you configuring that -- please check "DNS Settings" -> scroll down to "Access Settings"

**Comment by markkoek** [comment]
Thanks for your reply. I had missed that setting. My recommendation would be to enable this setting by default, as I think many people won't enable it. Rate limiting is good of course, but being an open resolver may result in your IP ending up on blacklists.
