### ISSUE TITLE
Security Blocklist for AdGuard Home: Malicious URL Blocklist.

### ISSUE THREAD

**Issue by Manish-Sahay** [AdguardTeam/AdGuardHome#2595]
### Problem Description

Need a dedicated blocklist for blocking malicious URLs based on a regularly updated database.

### Proposed Solution

Adding '**Malicious URL Blocklist**' in the selected '**AdGuard Home**' blocklists list under the '**Security**' category.

The official description of the blocklist says: "A blocklist of malicious websites that are being used for malware distribution, based on the **Database dump (CSV)** of Abuse.ch [URLhaus](https://urlhaus.abuse.ch/). Blocklist is updated twice a day."

The homepage of blocklist: https://gitlab.com/curben/urlhaus-filter.

This blocklist is available in both, Regular and Lite, modes. Yes, it supports the AdGuard Home format :).

### Alternatives Considered

The current 'Hacked Malware Web Sites' list is also good but the one I'm mentioning here is based on the Database dump (CSV) of URLhaus by abuse.ch, which has multiple contributors submitting malicious URLs.

### Additional Information

It would be great to have this list as an alternative list for blocking Malicious URLs.

**Comment by ameshkov** [comment]
Duplicates #1913 

Also, that list is already mentioned there.
