### ISSUE TITLE
DNS request for DNS rewrite entries not served when no upstream DNS servers are available

### ISSUE THREAD

**Issue by matthijsberg** [AdguardTeam/AdGuardHome#2596]
### Problem Description
My internet connection failed recently. After that I could not reach my local network HA instance and my Ubiquiti network disengaged. Both are relying on DNS. HA uses TLS and is accessed on hostname to not have errors. UI devices use DNS to resolve the container on my server that hosts the UI server. It looks like AdGuard stops serving DNS responses when the upstream servers cannot be reached (it can't do that), but also stops for DNS rewrites.

### Proposed Solution
I expect the AdGuard to still serve DNS rewrites when no upstream server is available so that my local DNS resolving continues to operate and HA / UI keep working. I cannot find any config setting for this. I have checked the docs and can't find anything relevant about this.

### Alternatives Considered
none.

### Additional Information
none.

**Comment by ameshkov** [comment]
Hm, well, most likely this is due to all goroutines being in use, this is possible if all upstreams time out. Look for `max_goroutines` setting in AdGuardHome.yaml, it's equal to 300 by default.

**Comment by matthijsberg** [comment]
Thanks for the pointer! I've looked up the `max_goroutines` and the value in my config is 50. (0.104.1 and 0.104.3). My installation comes in a container, so I am not sure if config files from previous version, or from the latest branch are used.

Would changing this to 300 resolve my issue, or do I need to further increase this number. I have a rather simple setup with 3 upstream servers and approx. 30 DNS rewrites.

**Comment by ameshkov** [comment]
It depends, you could try setting it to 0 (disabling this limit completely) and see if it helps

**Comment by matthijsberg** [comment]
Hi, I ran a test, no internet uplink, and upped it to 300 and that worked, but became slow after some time (20min or so). I changed it to 0 and now it keeps working.

Are there any downsides to changing this to 0? Like CPU / MEM usage or other wise? I don't see any in the short time and limited requests test I did. 

Thanks for all the support!

**Comment by ameshkov** [comment]
I am glad to hear that it helped!

> Are there any downsides to changing this to 0? Like CPU / MEM usage or other wise? 

Well, in theory, when the internet outage happens, it may cause higher memory usage due to the number of spawned goroutines. But there should be really a lot of queries incoming for that overhead to become considerable.

**Comment by matthijsberg** [comment]
Cool, thanks. I'm good for now. Not sure if you want to change the default anyhow, but i'll leave that up to you. Will close this. :-)

**Comment by Potterli20** [comment]
@ameshkov why?
![图片](https://user-images.githubusercontent.com/28734349/106924556-24593900-674a-11eb-937c-1654478bcd00.png)

**Comment by ameshkov** [comment]
@Potterli20 is it stable? how can we reproduce this?

**Comment by Potterli20** [comment]
> w can we reproduce this?

You should pay attention to MAX_GOROUTINS, because I use TXT upstream file, too many files lead to denial of service, I have had this situation three times today, just when I saw the issue of issues, I knew this problem, I have set it to 0, but I read the diary to have the same problem.

**Comment by ameshkov** [comment]
If your server has relatively high load, it's okay to increase MaxGoroutines or set it to 0.

"too many files" -- do you mean "too many open files" error? In this case, you would simply need to increase ulimit - https://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux

**Comment by Potterli20** [comment]
> 
> 
> If your server has relatively high load, it's okay to increase MaxGoroutines or set it to 0.
> 
> "too many files" -- do you mean "too many open files" error? In this case, you would simply need to increase ulimit - https://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux

Is too big TXT upstream file, is about the file of 3M, he will lead to refuse service, has no problem now.
