### ISSUE TITLE
Questions Adguard Home

### ISSUE THREAD

**Issue by alexismarchand3** [AdguardTeam/AdGuardHome#2599]
Bonjour,
 
Je souhaiterais savoir si vous proposez de vendre des machines avec plusieurs cartes réseaux compatible avec vos produits.
Si non, quels caractéristique physique recommandez-vous pour faire fonctionner le produit Adguard Home ?
Avez-vous des tests de débit ?
En effet je viens de bénéficier de la fibre chez moi et j'ai peur que faire passer tout le trafic réseau par un seul serveur avec une carte Ethernet 1GB réduise fortement la vitesse pour du streaming, téléchargement ou jeu en ligne.
 
Bien à vous

**Comment by ameshkov** [comment]
Hello,

AdGuard Home is not a proxy (yet), it is a DNS server, it simply cannot influence your bandwidth so no worries, your 1Gbps network will be intact:)
