### ISSUE TITLE
Netflix app + Chromecast compatibility issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdGuardHome#260]
@adguard-bot commented on [Fri Mar 23 2018](https://github.com/AdguardTeam/AdguardFilters/issues/13722)

### Issue URL (Incorrect Blocking)
[https://netflix.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnetflix.com)
### Comment
> Hi, with AdGuardDNS on Tablet my Netflix App don't find my Chromecast 2.
> 
> AdguardDNS on Tablet + Netflix App + Fire TV/Nexus Player working.
> AdguardDNS on tablet + Youtube app + Chromecast 2 working.
> Google DNS on Router + Netflix App on Smartphone + Chromecast 2 working.
> 
> It's only Chromecast 2 + Netflix app that won't work on a tablet with AdGuardDNS, ists from the DNS I think, can you fix it?

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/CUOKDY9.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | DNS
Browser: | DNS configure in the router
Filters: | English

**Comment by vozersky** [comment]
can't testm got no chromecast :( @nkartyshov

**Comment by As3ro** [comment]
The problem remains
