### ISSUE TITLE
Inconsistent response for non-existing domains

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2600]
First (served not from the cache) `dig -t a piggies.are.pink @192.168.11.144` has `EDNS` section in response.
Second, third, etc responses don't have it.

Responses need to be consistent.

**Comment by EugeneOne1** [comment]
As it said in [RFC 6891](https://tools.ietf.org/html/rfc6891#page-7):

> OPT RRs MUST NOT be cached, forwarded, or stored in or loaded from master files.

It seems that [that](https://github.com/AdguardTeam/dnsproxy/issues/80) issue also goes against the standard.

**Comment by ameshkov** [comment]
No one says it should be cached. We should respond with our own EDNS extension when it's needed and not just forward what's received from the upstream. I suggest you checking how coredns works in this regard.
