### ISSUE TITLE
Unable to open Private Key generated by certbot

### ISSUE THREAD

**Issue by pdtan** [AdguardTeam/AdGuardHome#2601]
I'm using AGH 0.104.3. When putting `/etc/letsencrypt/live/xxx/fullchain.pem`:

    Certificate chain is valid
    Subject: CN=xxx
    Issuer: CN=R3,O=Let's Encrypt,C=US
    Expires: 2021-04-26 20:31:11
    Hostnames: xxx

But when putting `/etc/letsencrypt/live/xxx/privkey.pem`: `open /etc/letsencrypt/live/xxx/privkey.pem: permission denied`

**Comment by ainar-g** [comment]
`permission denied` errors usually mean that the `AdGuardHome` binary can't read the certificate, and not that the certificate is invalid.  Please make sure that `AdGuardHome` is running from under a user that can have read access to the file or from under `root`.

**Comment by pdtan** [comment]
> `permission denied` errors usually mean that the `AdGuardHome` binary can't read the certificate, and not that the certificate is invalid. Please make sure that `AdGuardHome` is running from under a user that can have read access to the file or from under `root`.

AGH ran under `root` user. Why can it read `fullchain.pem` but can't read `privkey.pem`? I `chmod -R 755` to `/etc/letsencrypt/live/` and `/etc/letsencrypt/archive/` but still `permission denied`

**Comment by pdtan** [comment]
uninstall then install not using snap, problem solved.

**Comment by ameshkov** [comment]
If you want to use snap, you need to copy/paste cert&key to the snap data directory: `/var/snap/adguard-home/current`
