### ISSUE TITLE
Adguard Home - where is database

### ISSUE THREAD

**Issue by Bammede** [AdguardTeam/AdGuardHome#2602]
I wanted to backup my Adguard Home installation and cannot find its database. My Adguard Home is on docker and there is no files under these directories:
adguard/conf
adguard/work

Where Adguard Home stores data?

**Comment by Aikatsui** [comment]
@Bammede Can you copy-paste the command you ran last time to deploy docker container?

Eg: docker run --name adguardhome -v /my/own/workdir:/opt/adguardhome/work -v /my/own/confdir:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 68:68/tcp -p 68:68/udp -p 80:80/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp -d adguard/adguardhome

According to above commend then `/my/own/workdir` and  `/my/own/confdir`

**Comment by Bammede** [comment]
This is "volumes" section from my docker-compose:

volumes:
      - "./adguard/work:/opt/adguardhome/work"
      - "./adguard/conf:/opt/adguardhome/conf"
      - "./proxy/certs:/opt/adguardhome/certs:ro"

Adguard works well, but work and conf directories are empty. Not sure, where the data are stored to make a backup of it.

**Comment by ameshkov** [comment]
Are you pulling `latest` or `edge` image?

> Adguard works well, but work and conf directories are empty. Not sure, where the data are stored to make a backup of it.

The data must be stored in these directories, just make sure that you've properly mapped them.

**Comment by Bammede** [comment]
I pull latest image.

I cannot find any files that contain Adguard Home data. /work and /conf are empty.
After I did this
`sudo docker-compose up -d --no-deps --build adguard`
The adguard's data has been erased and I am prompt to setup all over again. Had to restore whole server's backup. As you can see, I cannot even update it because all data are erased.

The docker-compose has this set:
volumes:
- "./adguard/work:/opt/adguardhome/work"
- "./adguard/conf:/opt/adguardhome/conf"
- "./proxy/certs:/opt/adguardhome/certs:ro"

However, I got this in OPT directory: /opt/adguard/work and /opt/adguard/conf
No adguardhome directory has been created.

**Comment by Aikatsui** [comment]
@Bammede You didnt follow the issue template then we dont know about the operating system and docker version etc.

I believe that is a mistake with the exact path and it might be preserve somewhere else on your disk. 
Use absolute path eg: -v /dockerapps/adguard/workdir:/opt/adguardhome/work
