### ISSUE TITLE
Add more websites/apps to Blocked services

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardHome#2604]
Add more websites/apps to Blocked services:

- [⏳ ] Globo = Globoplay, Canais Globo/Canais Globosat, Premiere, Combate 
- Telecine
- Nintendo = Nintendo Switch Online, Nintendo eShop
- [⏳ ]  HBO = HBO Max, HBO GO, HBO Espana, HBO Now, Discover+
-  Xbox = Xbox LIve, Xbox Game Pass, Xbox Xcloud
- Microsoft =  Microsoft Store
- Electronic Arts = EA Play and Origin
- [ ✅] Disney = Disney+ Hotstar, Star Plus, Disney Plus, Disney Now 
- ESPN = WatchESPN, Watch ESPN Brasil
- [ ✅]  Deezer
- Apple Music
-  Claro  = Claro Música, Claro Video, Claro Gaming 
- Net Now
- Sky play/Sky online
- Vivo play
-  DirecTV Go
-  Oi play
-  Paramount play
-  Pluto tv
-  Samsung TV Plus
- Tumblr
-  Google Meet
-  Ubisoft connect/Ubisoft club
- [ ✅]  VK
- [ ✅]  Playstation
- [ ✅]  Battle/Blizzard
- Stadia
- Gog  = Gog galaxy 
- Apple TV
- AT&T TV
- Tim = Tim music
- Nvidia = Geforce Now
- Conmebol TV
- Discovery+
- Europa+
- PlayPlus
- UOL Play
- LG Channels
- STARZPLAY 
- rlaxx TV
- Panflix 
- Guigo TV
- Cinema virtual
- Paramount+
- Stingray
- Looke
- Noggin
- Estádio TNT Sports
- History+
- AXN 
-TNT GO

**Comment by DandelionSprout** [comment]
Deezer:
```
||deezer.com^
||dzcdn.net^
```

GOG Galaxy:
```
||gog.com^
```

Ubisoft Connect:
```
||ubi.com^
||upc.ubisoft.com^
```

**Comment by uNitrous** [comment]
Several services have added: 9Gag, Dailymotion, Disney+, Hulu, Viber, WeChat, Weibo https://github.com/AdguardTeam/AdGuardHome/issues/2401

Forward some popular services from https://github.com/AdguardTeam/AdGuardHome/issues/2401#issuecomment-773346880

>Some suggestions: (big guys missing)
>
- Mail: gmail, hotmail, yahoo (alternative to mail.ru)
- Chat: kik, icq, yandex, jio, imo, google duo
- Conference: microsoft teams (alternative to zoom), slack (alternative to discord)
- News: bbc, wallstreet (alternative to dailymirror)

Maybe other very popular websites?

**Comment by DandelionSprout** [comment]
MS Teams: https://raw.githubusercontent.com/jbunner/adblock/master/a-msteams.txt
Roblox: https://raw.githubusercontent.com/jbunner/adblock/master/a-roblox.txt
Scratch(.mit.edu): https://raw.githubusercontent.com/jbunner/adblock/master/a-scratch.txt

**Comment by ainar-g** [comment]
Additional request from @c1xx is YouTube Kids:

> When I block YouTube, YouTube Kids is also blocked.
>
> Create a separated "specific service" for YouTube Kids

**Comment by cakens** [comment]
I'd suggest adding ability for custom toggle Blocked services. Else, the list to satisfy all possible permutations is quite long.

For example, I want to block YouTube, but we subscribe to YouTube TV, which I don't want to block.

I get I could just block YouTube manually. I want the ability to quickly toggle.

**Comment by ainar-g** [comment]
This is a rather old issue.  AGH is now using <https://github.com/AdguardTeam/HostlistsRegistry> for its list of services, so please create separate issues about the ones you'd like there, following the README in that repo.

For custom blocked services, see #1692.
