### ISSUE TITLE
如何在底部显示备案号？

### ISSUE THREAD

**Issue by xiaoqi2020** [AdguardTeam/AdGuardHome#2605]
我是安装在VPS服务器上的，应管理局要求，需在底部显示备案号！

**Comment by ameshkov** [comment]
我不懂，什么备案号？

**Comment by ameshkov** [comment]
请给我详细的描述。备案号是什么意思？什么要求？什么底部？

**Comment by rampageX** [comment]
@xiaoqi2020 你有病吗？难道你要把 AGH 管理页面作为首页？麻烦你不要把这种“特色”的东西摆出来出丑！

**Comment by ameshkov** [comment]
@xiaoqi2020 我觉得我知道了你的意思，但我觉得你需要有备案号在登录页面，不再管理页面。

反正，你要自身改变 AGH 的页面底部，就自身编辑它。

看看这儿： https://github.com/AdguardTeam/AdGuardHome/blob/master/client/src/components/ui/Footer.js#L63

**Comment by xiaoqi2020** [comment]
> @ xiaoqi2020你有病吗？难道你要把AGH管理页面作为首页？麻烦你不要把这种“特色”的东西摆出来出丑！

你有病吗？关你屁事？老子愿意，你管的着？傻逼！
