### ISSUE TITLE
Client with a "Client ID" is not shown in the query log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2607]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.105.0-SNAPSHOT-fc9ddcf9

I have two "Clients" configured:
1. One for a "client ID" -- `https://domain/dns-query/my-client` -- let's call it "my-client"
2. One for the IP address (for instance, 127.0.0.1) -- let's call it "local-client"

When a query is made to `https://domain/dns-query/my-client` from `127.0.0.1`, AdGuard Home uses "my-client" client settings. However, in the query log, I see "local-client" instead.

### Expected Behavior
I should see "my-client" in the query log.

### Actual Behavior
I see "local-client" in the query log

I suppose we should mark `clients/find` as deprecated and add a new method that's better suited for this.

Instead of a list of IPs and client IDs, it should accept IP/ID pairs.

Moreover, I suppose the response format should be changed as well.

Here's what we're interested in:
1. Client info (for manual clients)
2. IP info (hostname, whois info, etc)

**Comment by gpz1100** [comment]
I have added "https://adguard.domain.com/dns-query/abc123"  to firefox (119.x) as the dns provider.  Should it not include "abc123" somewhere in the visible query log?  I can use "abc123" as a search key and it will return appropriate entries but with no search key entered the client column just shows the ip and hostname of the device.
