### ISSUE TITLE
Flags to build a subset of releases; better docs

### ISSUE THREAD

**Issue by gxgani** [AdguardTeam/AdGuardHome#2608]
Each time there's update done to process for building from source, it seems to get opposite of intuitive, though I understand it's being streamlined for better deployment.

Previously, I was able to build from source for multiple Architecture and Operating System by customizing gorelease and have the distributables organized by architecture but I don't get it how it's done now.

**Comment by ameshkov** [comment]
Something like this:
```
make CHANNEL=release \
    GPG_KEY_PASSPHRASE=PUT_GPG_PASS_HERE \
    VERBOSE=2 \
   build-release
```

@ainar-g can we document it somewhere?

**Comment by ainar-g** [comment]
@gxgani, can you please describe what would be the desired result?  I'm asking, because I've been thinking about some changes, like the ability to build a release only for a subset of platforms, and perhaps we can modify the build scripts to make them more useful for both developers and people making custom distributions.

**Comment by gxgani** [comment]
@ainar-g I currently build Adguard for Linux and macOS against amd64 and arm64 architectures. I was thinking if this or something similar would be a good approach

```
make GOOS='linux, darwin' GOARCH='amd64, arm64' SNAPCRAFT=0
```

**Comment by ainar-g** [comment]
I see.  We'll do that in the 0.106.0 release cycle, which should start soon™.  Until then, you can modify the `platforms` variable in `scripts/make/build-release` to only include the versions that you need.

**Comment by gxgani** [comment]
@ainar-g quick question, how do I release a build without it resetting the version to 0.0.0 (I am hacking UI to my specs)

**Comment by ainar-g** [comment]
Setting the `VERSION` macro to your desired release version when calling `make` should be enough.  So, something like:

```sh
make VERSION='v1.2.3' CHANNEL='release' ... build-release
```

**Comment by ainar-g** [comment]
@gxgani, sorry for the wait.  We've just merged an enhancement that should allow you to do only build releases for certain OSes or architectures.  See the description of the new parameters [here].  Do you see any more documentation improvements we could make?

[here]: https://github.com/AdguardTeam/AdGuardHome/tree/6de54b3b99ec969376a3d48250216c22fa5894b3/scripts#build-releasesh-build-a-release-for-all-platforms

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to reopen with more details if you think it should be reopened.

**Comment by gxgani** [comment]
@ainar-g How do we pass a tag for a channel?

**Comment by gxgani** [comment]
> @gxgani, sorry for the wait. We've just merged an enhancement that should allow you to do only build releases for certain OSes or architectures. See the description of the new parameters [here](https://github.com/AdguardTeam/AdGuardHome/blob/55d4c7ee4fd4b906521bbdb2bb822cebcef377f5/scripts/README.md#build-releasesh-build-a-release-for-all-platforms). Do you see any more documentation improvements we could make?

So far the documents look great! One thing that could use improvement would be,
 - version script, could either retrieve the channel's latest version or from current branch tag
 - on macOS, https://github.com/AdguardTeam/AdGuardHome/blob/f5adf15c8c5ee0162169b0abb7554709df856542/Makefile#L19 make doesn't recognize "|" operator


Thanks for the amazing work!

**Comment by ainar-g** [comment]
@gxgani 

Thanks for testing out!

> make doesn't recognize "|" operator

The `|` in there isn't a `make` or a Shell operator, it's actually a part of Go's `GOPROXY` notation.  If you have any issues because of it, you're probably running Go 1.14 or older, because this notation was only introduced in Go 1.15.  If it's not that, please add the error message that you're getting so that we could investigate.

> version script, could either retrieve the channel's latest version or from current branch tag

I am not sure what exactly you mean here, but if you set the version manually when invoking `make`, it should use it instead of the one generated by the version script:

```sh
make build-release VERSION='v1.2.3' # …
```

**Comment by gxgani** [comment]
@ainar-g 

You're correct about the GOPROXY, I had to eventually upgrade because during compilation, the error prompted me to get Go 1.15 or greater but I never checked if that solved the pipe operator issue.

Concerning the version script, currently if you do not provide any version (which is what usually I would do), it would pick up 0.0.0 for any channel that you pass.

**Comment by ainar-g** [comment]
The later scripts detect `v0.0.0` and call the version script anyway.  If the feature that you want is really necessary for you, it would be better for you to describe what you want, preferably with examples of `make` invocation and the resulting versions, in a new issue or discussion.

**Comment by ainar-g** [comment]
@gxgani, heads up!  We renamed the parameter `SNAP` into `BUILD_SNAP` in `master`, because otherwise there seem to be some conflicts with some Snapcraft environments.  So if you skipped Snap builds with:

```sh
make build-release SNAP=0 # …
```

You should now do:

```sh
make build-release BUILD_SNAP=0 # …
```
