### ISSUE TITLE
DNS answer in query log is sometimes not a string

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2609]
Context: https://github.com/AdguardTeam/AdGuardHome/issues/2533#issuecomment-768890246.

Stop lying to the frontend that we send a string and make sure that we **actually** always send a string.

**Comment by ainar-g** [comment]
@DandelionSprout, this should fixed as of snapshot 3af079a.  Can you please check if our solution fixes the issue for you?

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to reopen if the problem isn't actually fixed for you.

**Comment by DandelionSprout** [comment]
Seems to be fixed as of 0.105.0-beta.3 (I lacked time to switch to the nightly buildd last week): 
![image](https://user-images.githubusercontent.com/22780683/106639823-a9dfbc00-6585-11eb-947e-f0eed158e333.png)
