### ISSUE TITLE
Query logs retention

### ISSUE THREAD

**Issue by denniswham** [AdguardTeam/AdGuardHome#2610]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.3
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3B+

### Expected Behavior
I set the Query Logs Retention to 24 hours. Any items that are logged over 24 hrs should have been deleted and do not show up in the Query Logs search result.

### Actual Behavior
I set the Query Logs Retention to 24 hours. Any items that are logged over 24 hrs still show up in the Query Log search results.

**Comment by ameshkov** [comment]
Here's how it works right now: every 24 hours the log file is rotated, prev file is renamed to `querylog.json.1`, the current one is created and called `querylog.json`, so in fact, it stores up to 48 hours (depending on the time of the day).
