### ISSUE TITLE
ios 14 configuration profiles  doh.mobileconfig create failed

### ISSUE THREAD

**Issue by freelingchang** [AdguardTeam/AdGuardHome#2612]
ios 14 configuration profiles 
when  i download  https://192.168.0.1/apple/doh.mobileconfig
log:
getting host: address 192.168.0.1: missing port in address

running  docker adguard/adguardhome:latest

**Comment by ameshkov** [comment]
Hello,

You need to have TLS configuration in AdGuard Home and use the configured hostname to download the mobileconfig file: https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption
