### ISSUE TITLE
Installing for MacOS

### ISSUE THREAD

**Issue by moofawsaw** [AdguardTeam/AdGuardHome#2613]
I migrated my Mac that had Adguard Home installed (Catalina) to a 2020 Mac with the M1 Chipset and was experiencing issues with the upstream server so I figured I would do a fresh install by removing Adguard Home using `sudo /opt/AdGuardHome/AdGuardHome -s uninstall`.

Then when I downloaded the MacOS 64-bit file and run it (from here: https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started), I received the following error:

```
2021/01/29 15:03:14 [error] Couldn't read config file /Users/user/Downloads/AdGuardHome 8/AdGuardHome.yaml: open /Users/user/Downloads/AdGuardHome 8/AdGuardHome.yaml: no such file or directory
2021/01/29 15:03:14 [info] AdGuard Home, version 0.104.3, channel release, arch darwin amd64
2021/01/29 15:03:14 [info] This is the first time AdGuard Home is launched
2021/01/29 15:03:14 [info] Checking if AdGuard Home has necessary permissions
2021/01/29 15:03:14 [fatal] Permission check failed.

AdGuard Home is not allowed to bind to privileged ports (for instance, port 53).
Please note, that this is crucial for a server to be able to use privileged ports.

You have two options:
1. Run AdGuard Home with root privileges
2. On Linux you can grant the CAP_NET_BIND_SERVICE capability:
https://github.com/AdguardTeam/AdGuardHome/internal/wiki/Getting-Started#running-without-superuser
logout

```

I installed Adguard Home and had it configured no problem while on my old Mac running Catalina. It was also working when I migrated between computers. What went wrong after uninstalling and trying to re-install?

**Comment by ameshkov** [comment]
Have you placed it to the "Applications" directory? For some reason it's important to have it there.

**Comment by moofawsaw** [comment]
I tried launching from the applications folder and receive the same error. Here is what is shows when I check post 53:

MacBook-Air:~ user$ netstat -vanp tcp | grep 53
tcp4       0      0  192.168.0.11.51344     130.211.16.53.443      ESTABLISHED 131072 131874    600      0 0x0102 0x00000008
tcp6       0      0  2607:fea8:44df:4.50853 2a04:4e42:1e::39.443   ESTABLISHED 1147808 131376    600      0 0x0102 0x00000008
tcp6       0      0  2607:fea8:44df:4.49853 2607:f8b0:400b:8.443   ESTABLISHED 131072 131072  67617      0 0x0102 0x00000000
tcp4       0      0  192.168.0.11.49803     185.199.109.153.443    ESTABLISHED 323656 131768    600      0 0x0102 0x00000008

**Comment by ameshkov** [comment]
Try `sudo lsof -nP -iUDP:53`, check the PID column, lookup what process occupies the port.

**Comment by moofawsaw** [comment]
Nothing happens when I type in that command:

kyleunderhill@MacBook-Air ~ % sudo lsof -nP -iUDP:53
Password:
kyleunderhill@MacBook-Air ~ % sudo lsof -nP -iUDP:53
kyleunderhill@MacBook-Air ~ % sudo lsof -nP -iUDP:53

**Comment by ameshkov** [comment]
Weird. Is it the same when you run `sudo ./AdGuardHome -s install`?

**Comment by moofawsaw** [comment]
Yes here is the result:

kyleunderhill@MacBook-Air ~ % sudo ./AdGuardHome -s install
sudo: ./AdGuardHome: command not found

**Comment by ameshkov** [comment]
You should call it from the directory where AdGuardHome binary is located

**Comment by moofawsaw** [comment]
What would the command be from the applications folder?

**Comment by ameshkov** [comment]
Just copy/paste AdGuardHome folder to `/Applications` (so that it was `/Applications/AdGuardHome`) and run it from there: `sudo /Applications/AdGuardHome/AdGuardHome -s install`

**Comment by moofawsaw** [comment]
Dragging the AdGuardHome Unix Executable File - 20.4 MB into the applications folder and running the command returned:

kyleunderhill@MacBook-Air ~ % sudo /Applications/AdGuardHome/AdGuardHome -s install
Password:
sudo: /Applications/AdGuardHome/AdGuardHome: command not found
kyleunderhill@MacBook-Air ~ %

**Comment by ameshkov** [comment]
Apparently, you haven't created the `AdGuardHome` directory so  it's natural that it can't be found.

Try installing it using the standard installation script, it will install it to the proper location (remove the old binary before doing that): `curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh`

**Comment by moofawsaw** [comment]
I think I messed something up because here is what I get when running your script:

kyleunderhill@MacBook-Air ~ % curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh
[info] Starting AdGuard Home installation script
[info] Channel release
[error] Cannot detect your CPU
kyleunderhill@MacBook-Air ~ %

**Comment by ameshkov** [comment]
Oh, interesting, we may not be ready to M1.

What output do you see for this command: `uname -m`?

**Comment by moofawsaw** [comment]
kyleunderhill@MacBook-Air ~ % uname -m
arm64

**Comment by ameshkov** [comment]
Thank you! Added it to the install script, please try again in 10-15 minutes

**Comment by moofawsaw** [comment]
Here is the latest:

kyleunderhill@MacBook-Air ~ % curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Please note, that AdGuard Home requires root privileges to install using this script.
[info] Restarting with root privileges
Password:
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Script called with root privileges
[info] AdGuard Home will be installed to /Applications/AdGuardHome
[info] Downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_darwin_arm64.zip -> AdGuardHome_darwin_arm64.zip
[info] Unpacking package from AdGuardHome_darwin_arm64.zip -> /Applications
[AdGuardHome_darwin_arm64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of AdGuardHome_darwin_arm64.zip or
        AdGuardHome_darwin_arm64.zip.zip, and cannot find AdGuardHome_darwin_arm64.zip.ZIP, period.
[error] Cannot unpack the package

**Comment by ameshkov** [comment]
Argh, my bad:( We don't build for Mac ARM CPU, completely forgot about it.

Try again in 5 mins, I've switched it to amd64 build for now.

**Comment by moofawsaw** [comment]
Working. Thank you for your help!

**Comment by moofawsaw** [comment]
After factory reset of one of my Mac M1 machines I tried to fresh install and received the following error when running the auto-install command above that worked 10 days ago:

ki@Kis-MacBook-Pro ~ % curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Use amd64 build on Mac M1 until the native ARM support is added
[info] Please note, that AdGuard Home requires root privileges to install using this script.
[info] Restarting with root privileges
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Use amd64 build on Mac M1 until the native ARM support is added
[info] Script called with root privileges
[info] AdGuard Home will be installed to /Applications/AdGuardHome
[info] Downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_darwin_amd64.zip -> AdGuardHome_darwin_amd64.zip
[info] Unpacking package from AdGuardHome_darwin_amd64.zip -> /Applications
replace /Applications/LICENSE.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
[error] Cannot unpack the package

**Comment by ainar-g** [comment]
I seems like the decompressing software is saying that there is already a file named `LICENSE.txt` in the directory.  You need to remove the old files first.

**Comment by ameshkov** [comment]
@ainar-g nope, this is a consequence of repacking darwin build, it tries to unpack to `/Applications`, not to `/Applications/AdGuardHome`

**Comment by moofawsaw** [comment]
@ameshkov is there an action to take on my end to resolve?

**Comment by ameshkov** [comment]
Remove `/Applications/AdGuardHome` manually
Try installing again in 10 minutes

**Comment by moofawsaw** [comment]
ki@Kis-MacBook-Pro ~ % curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Use amd64 build on Mac M1 until the native ARM support is added
[info] Please note, that AdGuard Home requires root privileges to install using this script.
[info] Restarting with root privileges
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Use amd64 build on Mac M1 until the native ARM support is added
[info] Script called with root privileges
[info] AdGuard Home will be installed to /Applications/AdGuardHome
[info] Downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_darwin_amd64.zip -> AdGuardHome_darwin_amd64.zip
[info] Unpacking package from AdGuardHome_darwin_amd64.zip -> /Applications/AdGuardHome
sh: line 240: ./AdGuardHome: Bad CPU type in executable
[error] Cannot install AdGuardHome as a service

**Comment by ameshkov** [comment]
Weird, amd64 build worked before on your M1. If it does not want to launch it anymore, I guess you'll need to wait until we support M1 natively.

**Comment by moofawsaw** [comment]
I think it may have been because the M1 was set up using the Migration Assistant. I hadn't tried reformatting and re-installing on a fresh system.

Is there a status tracker where I can monitor updates on native support for the M1's?
________________________________

**Comment by ameshkov** [comment]
The easiest way would be to subscribe to releases of this repo (click "watch" -> choose releases)

**Comment by edgexyz** [comment]
I'm using Intel i5 core, but I still face the same "cannot install AGH as a service" problem🤔
OS: macOS Big Sur 11.2.3

The log looks like this:
sudo curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh

[info] Starting AdGuard Home installation script
[info] Channel release
[info] Please note, that AdGuard Home requires root privileges to install using this script.
[info] Restarting with root privileges
[info] Starting AdGuard Home installation script
[info] Channel release
[info] Script called with root privileges
[info] AdGuard Home will be installed to /Applications/AdGuardHome
[info] Downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_darwin_amd64.zip -> AdGuardHome_darwin_amd64.zip
[info] Unpacking package from AdGuardHome_darwin_amd64.zip -> /Applications/AdGuardHome
sh: line 240: ./AdGuardHome: is a directory
[error] Cannot install AdGuardHome as a service

**Comment by EugeneOne1** [comment]
@edgexyz, the updated installation script will be available in the nearest future (two days).  We'll let you know right away.

**Comment by edgexyz** [comment]
thanks!

**Comment by EugeneOne1** [comment]
@edgexyz, the script is ready!  Follow the [`README.md`](https://github.com/AdguardTeam/AdGuardHome#automated-install-linux-and-mac).
