### ISSUE TITLE
wrong path to the AdGuardHome binary in rc.d script on FreeBSD 

### ISSUE THREAD

**Issue by sashkab** [AdguardTeam/AdGuardHome#2614]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
 0.104.3
* **How did you install AdGuard Home:**
manually consulting [setup script](https://github.com/AdguardTeam/AdGuardHome/blob/v0.104.3/scripts/install.sh#L220), because curl | sh is bad.
* **How did you setup DNS configuration:**
unable
* **If it's a router or IoT, please write device model:**
no
* **Operating system and version:**
FreeBSD 12.2p3

### Expected Behavior
After running `sudo /opt/AdGuardHome/AdGuardHome -s install`, rc.d script `/usr/local/etc/rc.d/AdGuardHome`  uses proper path to AdGuardHome Binary

### Actual Behavior
rc.d script has wrong path to the AdGuardHome binary.

```sh
$ cat /usr/local/etc/rc.d/AdGuardHome
#!/bin/sh
# PROVIDE: AdGuardHome
# REQUIRE: networking
# KEYWORD: shutdown
. /etc/rc.subr
name="AdGuardHome"
AdGuardHome_env="IS_DAEMON=1"
AdGuardHome_user="root"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f /opt/AdGuardHome"
run_rc_command "$1"
```

### Additional Information

[Setup script](https://github.com/AdguardTeam/AdGuardHome/blob/v0.104.3/scripts/install.sh#L220) installs AdGuard binary as `/opt/AdGuardHome/AdGuardHome`. But [rc.d](https://github.com/AdguardTeam/AdGuardHome/blob/641db73a86a6d9d047f47c403bca70af320f23e9/internal/home/service.go#L517) script tries to launch `/opt/AdGuardHome`.

**Comment by sashkab** [comment]
I fixed this by manually editing the rc.d file:

```sh
#!/bin/sh
# PROVIDE: AdGuardHome
# REQUIRE: networking
# KEYWORD: shutdown
. /etc/rc.subr
name="AdGuardHome"
AdGuardHome_env="IS_DAEMON=1"
AdGuardHome_user="root"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f /opt/AdGuardHome/AdGuardHome -l syslog -w /opt/AdGuardHome -c /opt/AdGuardHome/AdGuardHome.yaml"
run_rc_command "$1"
```

(note, I passed few extra options, not sure if it was required, but at least AdGuard is now working.)

**Comment by ainar-g** [comment]
Hi, and thank you for your report!  I've pushed a fix to `install.sh` to the `master` branch recently.  It should set the binary path correctly.  Can you please check if that solution fixes the issue for you?

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to reopen with more details if you think it should be reopened.

**Comment by sashkab** [comment]
@ainar-g thanks -- didn't get a chance to test it yet, sorry.
