### ISSUE TITLE
DNS server no longer monitors encrypted DNS-over-HTTPS

### ISSUE THREAD

**Issue by AxelMilb** [AdguardTeam/AdGuardHome#2615]
AdGuard Home DNS server is listening on the following addresses https://my.domain.com:400/dns-query Doesn't work since version:v0.105.0-SNAPSHOT-eeeb0383.
tls://my.domain.com:853 works under Android as my.domain.com without problems

**Comment by Freekers** [comment]
Do you see any errors in the logs? Might be related to an issue I'm having.

**Comment by ameshkov** [comment]
Are you running a snap version?

**Comment by ameshkov** [comment]
@ainar-g I've added a temporary fix for this so that edge channel builds started to work, but we'd better find a better way to fix this: https://github.com/AdguardTeam/AdGuardHome/commit/cd88137333419e954ef929a918b81d2a36da577d

**Comment by ainar-g** [comment]
@ameshkov, is there anything left to do in this issue?  I've committed a better version of the fix back in 3e0238aa9.

**Comment by ameshkov** [comment]
Yep
