### ISSUE TITLE
Clients identifiers and upper case - Invalid client ID format error

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2616]
Hello,

the client identifiers for DoH (possible for DoT too) did not accept upper case:
![image](https://user-images.githubusercontent.com/45385632/106360215-4c9aff00-6328-11eb-9f25-1d75b77bffa1.png)
![image](https://user-images.githubusercontent.com/45385632/106360277-997ed580-6328-11eb-909f-f41d1f7e7cdf.png)

Please, correct it soon😤

Thank you.

**Comment by ameshkov** [comment]
Actually, this is done for a reason. Client ID may also be used as a part of the domain name (`tls://client.example.org`), and you can't have upper case characters in a domain name.

**Comment by ammnt** [comment]
@ameshkov, actually not. And NextDNS is example:
![image](https://user-images.githubusercontent.com/45385632/106388618-6bfd5f00-63f0-11eb-8243-5ff83691a87a.png)

Uppercase client IDs can be used using .mobileconfig or Stubby:
![image](https://user-images.githubusercontent.com/45385632/106388600-51c38100-63f0-11eb-9b75-37c33921ccc4.png)

**Comment by ammnt** [comment]
@ameshkov, там не должно быть проблем с совместимостью. Дело вообще не в домене или URL'e. Это, фактически, значения "ServerName" (для .mobileconfig) и "tls_auth_name" (для Stubby), которые передаются при рукопожатии. И в клиентах, где указывается субдомен в качестве клиента тоже работает:
![image](https://user-images.githubusercontent.com/45385632/106389339-de237300-63f3-11eb-836f-d9ae9144da92.png)

![image](https://user-images.githubusercontent.com/45385632/106389369-fbf0d800-63f3-11eb-8da3-097e8da9407b.png)

![image](https://user-images.githubusercontent.com/45385632/106389385-10cd6b80-63f4-11eb-8df4-0af5fe666bfe.png)

**Comment by ameshkov** [comment]
@ammnt в доменных именах бывают только lower-case символы. Вы естественно можете вбить символы в любом регистре, но они неявно будут преобразованы к нижнему регистру во время выполнения запроса.

На мой взгляд это только создает лишнюю путаницу, пусть лучше ограничения будут у нас жестче, но не будет возникать лишних вопросов.

**Comment by ammnt** [comment]
@ameshkov, я понял в чем моя ошибка - в логе отображается имя клиента, а не его идентификатор DoT/DoH. Он как раз таки может быть в любом регистре. Это okay🤞
