### ISSUE TITLE
Invalid server name error for the correct domain

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2617]
Hello,

now i can adjust encryption only via .yaml configuration file because the form did not accept my domain:
![image](https://user-images.githubusercontent.com/45385632/106360392-3b062700-6329-11eb-9efd-a6956e54e0f2.png)

Looks like he is not accept some new gTLDs?🤔

Thank you.

**Comment by ameshkov** [comment]
Yeah, that's definitely a bug :)

@IldarKamalov how do you validate server names? We should allow any domain name there, regardless of the TLD.
