### ISSUE TITLE
ipset freezing adblock

### ISSUE THREAD

**Issue by k1ng440** [AdguardTeam/AdGuardHome#2619]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  version v0.105.0-SNAPSHOT-cd881373
* **How did you install AdGuard Home:**
  *  Github Commit
* **How did you setup DNS configuration:**
  *  System
* **If it's a router or IoT, please write device model:**
  *  
* **Operating system and version:**
  *  Ubuntu 20.10

### Expected Behavior

Adguard should respond to DNS query

### Actual Behavior

Adguard dns does not respond when ipset rules are provided.. seems like mutex deadlock

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

```
  ipset:
  - www.netflix.com,fast.com,netflix.com,netflix.net,netflix.ca,netflixinvestor.com,netflixtechblog.com,nflxvideo.net,nflximg.com,nflximg.net,nflxext.com,nflxso.net,nflxsearch.net,vo.llnwd.net,netflix.com.edgesuite.net,nflximg.com.edgesuite>
  - steamcdn-a.akamaihd.net,steamcommunity-a.akamaihd.net,steamcommunity.com,steamcontent.com,steampowered.com,steamstatic.com,steamusercontent.com,steamuserimages-a.akamaihd.net,valvesoftware.com/steam
  - reddit.com,redd.it,redditstatic.com/reddit
  - gcr.io/gcr
  - ext-twitch.tv/twitch
  - jtvnw.net/twitch
  - ttvnw.net/twitch
  - twitch.tv/twitch
  - twitchcdn.net/twitch
  - twitchsvc.net/twitch
  - akadns.net/akamai
  - akagtm.org/akamai
  - akam.net/akamai
  - akamai.com/akamai
  - akamai.net/akamai
  - akamaiedge.net/akamai
  - akamaihd.net/akamai
  - akamaistream.net/akamai
  - akamaitech.net/akamai
  - akamaitechnologies.com/akamai
  - akamaitechnologies.fr/akamai
  - akamaized.net/akamai
  - edgekey.net/akamai
  - edgesuite.net/akamai
  - zoom.us/zoom
  - discord.com/discord
  - discord.gg/discord
  - discord.media/discord
  - discordapp.com/discord
  - discordapp.net/discord
  - youtube.com/youtube
  - ytimg.com/youtube
  - ytimg.l.google.com/youtube
  - s.ytimg.com/youtube
  - youtube.l.google.com/youtube
  - googlevideo.com/youtube
  - i.google.com/youtube
```

**Comment by ameshkov** [comment]
We've just implemented some changes to the ipset feature so I guess that's the reason.

Could you please also record AGH log as well?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by k1ng440** [comment]
AGH just freezes after random seconds. I can see few queries being responded to clients before it happens.

**Comment by k1ng440** [comment]
here is the log file
https://paste.ubuntu.com/p/XJgkgM6dY7/

and its freezes after saying this:
```
;; QUESTION SECTION:
;ichnaea.netflix.com.   IN       A

2021/02/01 04:29:51 6271#978 [debug] https://dns.cloudflare.com:443/dns-query: sending request A ichnaea.netflix.com.
2021/02/01 04:29:51 6271#977 [debug] https://dns.quad9.net:443/dns-query: sending request A ichnaea.netflix.com.
2021/02/01 04:29:51 6271#977 [debug] https://dns.quad9.net:443/dns-query: response: ok
2021/02/01 04:29:51 6271#928 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 51 ms
2021/02/01 04:29:51 6271#978 [debug] https://dns.cloudflare.com:443/dns-query: response: ok
```

**Comment by ainar-g** [comment]
Hi, and thank you for your report!  I can't seem to reproduce the problem.  Can you please add the following information:

1.  The full `ipset` section of the config.  The one in the OP looks like it cuts off on the first line:

    ```
    […],nflximg.com.edgesuite>
    ```

2.  Your full list of upstreams.  Looking at the log, I assume that the Cloudflare and the Quad9 ones are used?  Are there any others?

Thanks!

**Comment by k1ng440** [comment]
Hi,

1.
```
  ipset:
  - www.netflix.com,fast.com,netflix.com,netflix.net,netflix.ca,netflixinvestor.com,netflixtechblog.com,nflxvideo.net,nflximg.com,nflximg.net,nflxext.com,nflxso.net,nflxsearch.net,vo.llnwd.net,netflix.com.edgesuite.net,nflximg.com.edgesuite.net/netflix
  - steamcdn-a.akamaihd.net,steamcommunity-a.akamaihd.net,steamcommunity.com,steamcontent.com,steampowered.com,steamstatic.com,steamusercontent.com,steamuserimages-a.akamaihd.net,valvesoftware.com/steam
  - reddit.com,redd.it,redditstatic.com/reddit
  - gcr.io/gcr
  - ext-twitch.tv/twitch
  - jtvnw.net/twitch
  - ttvnw.net/twitch
  - twitch.tv/twitch
  - twitchcdn.net/twitch
  - twitchsvc.net/twitch
  - akadns.net/akamai
  - akagtm.org/akamai
  - akam.net/akamai
  - akamai.com/akamai
  - akamai.net/akamai
  - akamaiedge.net/akamai
  - akamaihd.net/akamai
  - akamaistream.net/akamai
  - akamaitech.net/akamai
  - akamaitechnologies.com/akamai
  - akamaitechnologies.fr/akamai
  - akamaized.net/akamai
  - edgekey.net/akamai
  - edgesuite.net/akamai
  - zoom.us/zoom
  - discord.com/discord
  - discord.gg/discord
  - discord.media/discord
  - discordapp.com/discord
  - discordapp.net/discord
  - youtube.com/youtube
  - ytimg.com/youtube
  - ytimg.l.google.com/youtube
  - s.ytimg.com/youtube
  - youtube.l.google.com/youtube
  - googlevideo.com/youtube
  - i.google.com/youtube
```

2. yes, I am using cloudflare and quad9 in parallel request mode

thanks

**Comment by ainar-g** [comment]
We still weren't able to reproduce the issue, unfortunately, but we have a few theories.  We've added more debug logging as well as some minor fixes.  Can you please test using at least version 3e0238a and post the new verbose logs?  Thanks!

**Comment by k1ng440** [comment]
here you go

https://termbin.com/v3les

**Comment by k1ng440** [comment]
here you go

https://termbin.com/58lp

**Comment by ainar-g** [comment]
Thanks, it's very helpful!  Do you have your upstream mode set to “Parallel requests” or “Fastest IP address” on the “DNS settings” page?  If so, does setting it to “Load-balancing” improve this?  Or, alternatively, leaving only one upstream?

**Comment by ainar-g** [comment]
I've pushed another fix recently.  It should already be on the `edge` channel.  Can you also check it when you have the time?  Thanks!

**Comment by k1ng440** [comment]
thank you very much. the issue has been resolved.
