### ISSUE TITLE
Add ddns support to client filter

### ISSUE THREAD

**Issue by ItherNiT** [AdguardTeam/AdGuardHome#2620]
Hi,

It would be great if we can add support for ddns in the client filter option. I'm currently running a adguard home in the cloud so that my parents router can use it for dns requests. I recently noticed that I'm also getting requests from China. I would like to prevent my server from being used with dns amplification attacks. Unfortunately my parents are not on a dedicated IP, it tends to change every few days or on router restarts. I have a duck dns domain and a noip ddns setup on on their network, but the client filter only allows CIDR or IP ranges. Hopefully this is an easy request.

### Problem Description
Allowed clients are IP's and CIDR only.

### Proposed Solution
Allow ddns (like duckdns and noip) in the client filter section

**Comment by k1ng440** [comment]
you could just whitelist your parents ISP's CIDR. you can find the CIDR from 

use this tool to figure out
```
https://bgp.he.net/
```

**Comment by travisboss** [comment]
Other option is to setup as a DNS over TLS/HTTPS and setup this up at your parents house to access over these protocols.

**Comment by DandelionSprout** [comment]
To block requests from PR-China, paste the entirety of http://ipverse.net/ipblocks/data/countries/cn.zone (except the `#` lines) into Settings → DNS Settings → Disallowed clients.

The main question is *much* more tricky. If you know which IP addresses your parents receive from No-IP, you can use bgp.he.net (as suggested above) to search the address(es), click on AS[number] at the search result page → Prefixes IPv4. Then copy those results into Sublime Text, use Ctrl+H in `.*` mode to replace `.*Valid` and `<the unusual space after the CIDRs>.*` with emptiness, and then add every one of the results as a client identifier. Alternately giving a thumbs up to #1487.
