### ISSUE TITLE
CMD command to deny connexion to the portal

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdGuardHome#2621]
### Problem Description
On my vps if i never use the portal i can't disable the connection page (disable the textbox).

### Proposed Solution
Let us by command disable connexion to the portal, like that if we have to configure our DNS, we can do : 
SSh connection : `ssh user@domain.tls`
Go to Adguard : `cd /folder/of/adguard/`
Forbid connection : `AdGuardHome --Lock`
Authorize connection : `AdGuardHome --Unlock`

### Additional Information
This methods can add a layer of security for Administrator, who have configured their AdGuard home and don't touch it anymore.
The feature in this request add security to the account : https://github.com/AdguardTeam/AdGuardHome/issues/1667
The requested feature i ask is to block any possibility of connecting on the portal without administrator (of the server) approval so it don't protect the same thing.

**Comment by ameshkov** [comment]
Marked as "low" priority since this kind of access control in normal circumstances should be configured independently using iptables or similar tools.

**Comment by Macqael** [comment]
yes and it's not a real priority it's just a way to prevent unauthorized access on a publicly accessible VPS (when we use Dns Over Https).
I have thinked of it since i'm migrating my ADG Home to a VPS (to use it on my BOX too) and when i use 4G.

**Comment by cybernats** [comment]
You can set different port eg:4226 for web interface (AGH configuration). it'll be a real security
Another layer security, configure which IP can access to that port via VPS provider firewall or instance software firewall

**Comment by Macqael** [comment]
@cybernats ah et du coup le Dns Over Https reste disponible en 443 ? (je demande car je l'utilise avec mon router Synology)
