### ISSUE TITLE
Access settings for client identifier

### ISSUE THREAD

**Issue by agitoxin** [AdguardTeam/AdGuardHome#2624]
Hello

I'm trying the client ID in DoH with my phone and it works like a charm.
However, I couldn't utilize this feature to block unknown devices from network because the `DNS settings>Access settings>Allowed clients` only takes CIDR or IP addresses.

Since we could identify devices from DoH now, is it possible to allow or block a client by its identifier?

**Comment by Izya12** [comment]
Good afternoon.
I would like to add, we need the ability to pass only the allowed doh clients, blocking the rest.  

Добрый день.
Хотел бы дополнить, нужна возможность пропускать только разрешенных doh клиентов, остальных блокируя.

**Comment by ameshkov** [comment]
@Izya12 please upvote the original issue if you want it to be implemented.

**Comment by coxde** [comment]
This is a great feature to keep my ADH server private.

**Comment by windware-ono** [comment]
Even if I attempt to set the global setting to have an invalid upstream only allowing the defined clients by identifier to access to a proper upstream, this breaks for all the defined clients as well.

Same if I define clients by identifier and let it use a proper upstream but define a 0.0.0.0/0 as clients with an invalid upstream.

This needs to be implemented to avoid strangers from utilizing the resolver.

**Comment by ainar-g** [comment]
@windware-ono, if you want to create an allowlist of clients then you  can already do that with the DNS Settings → Access settings → Allowed clients setting.  Although it currently only works for IP addresses and subnets, not ClientIDs.

**Comment by windware-ono** [comment]
Yes, I'm aware of it but currently I'm running AH on a public network and anyone who finds it's running a resolver can utilize it but if I can limit who can use it via client identifier as a sort of password, that would be very useful.

**Comment by carrot-eggs** [comment]
Customizing the upstream through the client ID cannot take effect, and it will still be resolved through the upstream DNS set globally, as shown in the figure：

![1](https://user-images.githubusercontent.com/35254441/123546637-0ab79d00-d790-11eb-9492-4ba7c9b9ccbf.png)
![2](https://user-images.githubusercontent.com/35254441/123546709-510cfc00-d790-11eb-8b41-18ab86f6d011.png)
![3](https://user-images.githubusercontent.com/35254441/123546717-5702dd00-d790-11eb-92d8-ff38c6981b61.png)
![4](https://user-images.githubusercontent.com/35254441/123546720-59653700-d790-11eb-942c-992312761f00.jpg)

My adguardhome is installed on a VPS, and I cannot set up a dedicated upstream DNS for a certain device through the client ID. 

adguardhome version: v0.106.3

**Comment by ainar-g** [comment]
@carrot-eggs, hi, this issue is about access settings.  Please post your report as a separate issue.  Thanks.

**Comment by ainar-g** [comment]
@agitoxin, this feature is now implemented on the `edge` channel as of snapshot e08a64e.  Can you please check if it works for you?

**Comment by agitoxin** [comment]
@ainar-g , I have refreshed the service to the latest snapshot 232cd381ff322e55db259872b9a568f5a392b57f and tested the "Allowed clients" and "Disallowed clients" with multiple client IDs, it works excellent! Also, I have tried to allow a device's IP but disallow its client ID. This result in allowing the device, which is surprisingly match to the description. Thanks a lot. I'll close the issue.
