### ISSUE TITLE
MalwareDomainList and The Big List of Hacked Malware Web Sites filters issues

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2625]
Hello,

MalwareDomainList is empty now and deprecated. Please, remove it:
https://www.malwaredomainlist.com/hostslist/hosts.txt

Also looks like The Big List of Hacked Malware Web Sites have wrong URL:
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list

Must be this one:
https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts

Thank you.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2224
