### ISSUE TITLE
In Edge channel, DoH return with empty response.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#2628]
Version: `v0.105.0-SNAPSHOT-39f6689b`
Command: `echo -n 'q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | base64 -D | curl -H 'content-type: application/dns-message' --data-binary @- https://localhost.zhijie.online/dns-query -o - | hexdump`

<img width="570" alt="Xnip 2021-02-02 11 42 58" src="https://user-images.githubusercontent.com/58100052/106549697-7cc2e780-654c-11eb-979d-1d73537c0d91.png">

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by hezhijie0327** [comment]
> Command: `echo -n 'q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | base64 -D | curl -H 'content-type: application/dns-message' --data-binary @- https://localhost.zhijie.online/dns-query -o - | hexdump`

I ran the same command in both edge and latest channel, edge channel has not any query logs.
[debug_edge.log](https://github.com/AdguardTeam/AdGuardHome/files/5909999/debug_edge.log)
[debug_latest.log](https://github.com/AdguardTeam/AdGuardHome/files/5910001/debug_latest.log)

**Comment by ameshkov** [comment]
@ainar-g it seems HTTPS server hasn't been even started

**Comment by ainar-g** [comment]
This could be related to the same issue that caused #2619.  I've pushed a fix for it in f5c47b6.

**Comment by ainar-g** [comment]
I pushed 28b9abf, which should fix this issue.  Can you please make sure that it does for you?  Thanks!

**Comment by hezhijie0327** [comment]
OK, building now.

**Comment by hezhijie0327** [comment]
It works!!!

**Comment by ainar-g** [comment]
Great, thanks for testing!  I'll close this issue for now.  Please feel free to open new ones if you find any other breakages.
