### ISSUE TITLE
$dnsrewrite doesn't perform address-level redirections

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#2631]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (0.105.0-beta.3)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.105.0-beta.3
* **How did you install AdGuard Home:**
  * Github releases
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 4GB
* **Operating system and version:**
  * Raspberry Pi OS Bullseye 32-bit

### Expected Behavior

For reasons explained below, I wish for an even more powerful `$dnsrewrite` feature; one that would be able to redirect requests to different domains entirely and cause web browsers to try to load the target domain (in the case below, `x.facebook.com`), instead of just fetching CNAME info from the target domain onwards.

### Actual Behavior

I admit that I haven't followed the discussion of and implementation of `$dnsrewrite` closely, and only began experimenting with it earlier this afternoon, and I honestly feel a bit disappointed by it.

Given a scenario where I've used `mobile.facebook.com$dnsrewrite=x.facebook.com`, `$dnsrewrite` does not seem able to redirect the requests in such a way that writing `mobile.facebook.com` in a browser address bar would make it try to load `x.facebook.com`.

Instead, as shown in the screencap below, it tries to redirect to `x.facebook.com`, but only as a relay to seemingly then load the CNAME values for `x.facebook.com`, using *those* values as the end result that it uses.

My understanding of the screencap is `mobile.facebook.com` → `x.facebook.com` → `m.facebook.com` → `(...)` → `2a03:2880:(...)`, with that last one being used by AGH to fetch the IP and CNAME results for `mobile.facebook.com`.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/106638033-b105ca80-6583-11eb-83fc-25ea4d519c40.png)

</details>

### Additional Information

At the time of testing, I had set the minimum TTL value to 300 for unrelated reasons.

**Comment by ameshkov** [comment]
I am not sure the desired behavior is possible to achieve on the DNS level, you need an HTTP redirect for that.

**Comment by ainar-g** [comment]
Not sure I understand the end-goal, but are you sure that something like:

```
|mobile.facebook.com^$dnsrewrite=1.2.3.4
|mobile.facebook.com^$dnsrewrite=1.2.3.5
```

Where those IPs are the actual IPs of `x.facebook.com`, is not what you're looking for?

**Comment by DandelionSprout** [comment]
The end-goal is that `mobile.facebook.com` gets redirected to `x.facebook.com` and tries to load that page instead. But I accept Meshkov's explanation that it wasn't how DNS servers really worked like.
