### ISSUE TITLE
Annoying autoupdate error

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2632]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.105.0-SNAPSHOT-6fe22764
* **How did you install AdGuard Home:**
  * VPS
* **Operating system and version:**
  * Debian 10

### Actual Behavior
Have the error while autoupdate. The app is actually updated as result, but return error everytime.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/45385632/106645774-ddc6db80-659d-11eb-95da-6e74edf4dcff.png)

![image](https://user-images.githubusercontent.com/45385632/106645851-fb944080-659d-11eb-9a34-85790116690c.png)

![image](https://user-images.githubusercontent.com/45385632/106645948-1f578680-659e-11eb-8b71-3522cf1104c6.png)
</details>

### Additional Information
The [detailed logs](https://github.com/AdguardTeam/AdGuardHome/files/5913595/log.txt) is attached.

**Comment by ainar-g** [comment]
Does this mostly happen after a restart?  It might be that the new version info isn't initialised properly.

**Comment by ammnt** [comment]
@ainar-g, I remembered that I updated the second time without rebooting the server from version 0.105.0-SNAPSHOT-6fe22764 to 0.105.0-SNAPSHOT-9cd9054c and was this error message again. More [logs](https://github.com/AdguardTeam/AdGuardHome/files/5913870/log.txt) here.

**Comment by ainar-g** [comment]
Thanks for the logs!  I don't see any errors with the update itself, so it's probably some sort of an interface issue.  Perhaps the restart happens so quickly that the frontend doesn't receive the HTTP response and so the frontend thinks that the update has failed.

Do you access the web interface directly or over an HTTP proxy?  If there is a proxy, does the error also appear when you use the web interface directly?

**Comment by ammnt** [comment]
> Thanks for the logs! I don't see any errors with the update itself, so it's probably some sort of an interface issue. Perhaps the restart happens so quickly that the frontend doesn't receive the HTTP response and so the frontend thinks that the update has failed.
> 
> Do you access the web interface directly or over an HTTP proxy? If there is a proxy, does the error also appear when you use the web interface directly?

Only directly. This is my test empty server. So i actually can give you access and you can reproduce this error next time. What do you think?

**Comment by ainar-g** [comment]
Probably not this week, apologies.  But we will track this issue!  I couldn't personally reproduce the error message, but there were a couple of other weird things in the interface that I want to investigate.

**Comment by ammnt** [comment]
@ainar-g, the last edge version is 0.105.0-SNAPSHOT-9cd9054c now? After your question about proxy I turned on Cloudflare DDoS protection, which is essentially a web-proxy and now there is no update at all🤯

**Comment by ainar-g** [comment]
Update checking caches the results for a few hours, if I recall correctly.  So that's *probably* not that weird.  Also, a web proxy shouldn't really affect the autoupdate, unless it somehow filters out outgoing requests.

**Comment by ammnt** [comment]
@ainar-g, the last updates has been completed fine. You can close this task if you want.
