### ISSUE TITLE
Annoying notification about SSL certificate expiration - 3 months for Letsencrypt

### ISSUE THREAD

**Issue by alexsannikov** [AdguardTeam/AdGuardHome#2633]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104
* **How did you install AdGuard Home:**
  * GitHub release
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  *Raspberry Pi 
* **Operating system and version:**
  * Raspbian

### Expected Behavior

Notify about SSL certificate expiration within defined period. In my case LetsEncrypt certificates are issued for 3 months only and updated not earlier than 1 month before validity expiration. It would be great to have an option to disable notification or adjust this period (like “Notify N days before validity’s expiration”).
### Actual Behavior 

I see notification always even for 3 months valid certificate. 
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
That shouldn't be happening, the notification is only shown when the cert is 5 days from expiration.

Merged into https://github.com/AdguardTeam/AdGuardHome/issues/1400
