### ISSUE TITLE
Suddenly stopped working! 

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2634]
It worked stably for a long time, but it didn't start today. There are such errors in the log, what is the reason?

Wed Feb  3 09:11:52 2021 daemon.info procd: Instance AdGuardHome::instance1 s in a crash loop 6 crashes, 12 seconds since last crash
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/build/internal/home/web.go:134 +0x50
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: created by github.com/AdguardTeam/AdGuardHome/internal/home.(*Web).Start
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/build/internal/home/web.go:198 +0x50
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: github.com/AdguardTeam/AdGuardHome/internal/home.(*Web).tlsServerLoop(0x1cf22a0)
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/usr/local/go/src/sync/cond.go:56 +0xe8
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: sync.(*Cond).Wait(0x1d16520)
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/usr/local/go/src/runtime/sema.go:513 +0x14c
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: sync.runtime_notifyListWait(0x1d16528, 0x0)
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/usr/local/go/src/runtime/proc.go:310
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: runtime.goparkunlock(...)
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: goroutine 21 [sync.Cond.Wait]:
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]:
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/build/internal/util/auto_hosts.go:89 +0xb4
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: created by github.com/AdguardTeam/AdGuardHome/internal/util.(*AutoHosts).Start
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: 	/build/internal/util/auto_hosts.go:279 +0x128
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: github.com/AdguardTeam/AdGuardHome/internal/util.(*AutoHosts).watcherLoop(0x1353a68)
Wed Feb  3 09:11:52 2021 daemon.err AdGuardHome[17619]: goroutine 19 [select]:

**Comment by ainar-g** [comment]
Hello, please add the following information to help us diagnose the issue:

1.  What OS and which OS version are you running?
1.  What version of AdGuard Home are you running?
1.  How did you install AdGuard Home (for example, a Snap package, a Docker container, a Github release, and so on)?

**Comment by fizsef** [comment]
OpenWrt 19.07.4 r11208-ce6496d796
104.3
Github

**Comment by ameshkov** [comment]
@ainar-g assigned to v0.105 for now

**Comment by ameshkov** [comment]
> There are such errors in the log, what is the reason?

There should be more lines about AdGuard Home in the log, could you please grab them all?

**Comment by fizsef** [comment]
Is version 0.105 stable already? I have says that 0.104.3 is acutal.
![1](https://user-images.githubusercontent.com/74646605/106745097-b3266280-6631-11eb-8857-0919077c9653.jpg)

**Comment by ainar-g** [comment]
No, v0.105.0 hasn't been released yet.

Could you please provide more logs?

**Comment by fizsef** [comment]
Well, I've uninstalled, re-installed , did some digging around, and it worked like that. Therefore, I can no longer provide full logs at the time of the problem, unfortunately. Thanks for the help.

**Comment by ainar-g** [comment]
You're welcome!  Please report any new issues.
