### ISSUE TITLE
hosts file like entry shows blocked in log

### ISSUE THREAD

**Issue by sachinwadhwa** [AdguardTeam/AdGuardHome#2635]
I am using Official Docker Image (latest).

If I add a hosts file style entry in custom filtering rules (example below):

192.168.1.1 homeassistant.mydomain.local

It works fine but shows blocked in query log. Actually its not blocked and return correct internal IP.

![image](https://user-images.githubusercontent.com/34010654/106765900-35625700-6631-11eb-84cc-0dc55d94a85b.png)

**Comment by ameshkov** [comment]
You may want to use DNS rewrites instead of custom rules.
