### ISSUE TITLE
bind_host 0.0.0.0

### ISSUE THREAD

**Issue by Bammede** [AdguardTeam/AdGuardHome#2636]
Not sure is it bug. Adguard works fine. However, each time I restart the docker, the "bind_host" on top of AdGuardHome.yaml is changed to "0.0.0.0" from the actual Adguards' IP. Again Adguard works fine though.

Should I worry about it?

**Comment by ameshkov** [comment]
No worries, that's because we set it 0.0.0.0 in the docker image: https://github.com/AdguardTeam/AdGuardHome/blob/master/scripts/make/Dockerfile#L52
