### ISSUE TITLE
stops working with fatal error

### ISSUE THREAD

**Issue by VinitSonawane** [AdguardTeam/AdGuardHome#2637]
Stops working in between with following message in AdGuardHome.err
[fatal] accept tcp 192.168.26.6:8080: ac
cept: invalid argument
Service restart solves the problem, but again after some time it stops working.

**Comment by ainar-g** [comment]
Hello, please add the following information to help us diagnose the issue:

1.  What OS and which OS version are you running?
1.  What version of AdGuard Home are you running?
1.  How did you install AdGuard Home (for example, a Snap package, a Docker container, a Github release, and so on)?

**Comment by VinitSonawane** [comment]
Hello !
Please find the requested information
1) Debian buster V10
2) latest stable (installed yesterday)
3) GitHub Release

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by VinitSonawane** [comment]
Please Find the logs :-
[AdGuard_log.txt](https://github.com/AdguardTeam/AdGuardHome/files/5926120/AdGuard_log.txt)
and the service status snapshot(it is stopped) :- 
![Status Snapshot](https://user-images.githubusercontent.com/66167039/106902121-784e2880-671e-11eb-8146-f355ff939be7.png)

**Comment by ameshkov** [comment]
Nothing helpful in the log:(

Could you please look for relevant info in syslog? `/var/log/syslog` or `/var/log/system.log`, the keyword is "panic"

**Comment by VinitSonawane** [comment]
This is the AdGuardHome.err file in /var/logs/
[AdGuardHome_err.txt](https://github.com/AdguardTeam/AdGuardHome/files/5926285/AdGuardHome_err.txt)

I saw the error in it at line 63 timestamp 2021/02/03 23:45:37
and then on the line 64 timestamp 2021/02/04 09:46:46, I manually restarted service and it started.
It again happened, stopped (on line 82 at 2021/02/04 11:42:26) and manually restarted (on line 84 at 2021/02/04 11:42:26).

**Comment by VinitSonawane** [comment]
I looked up in syslog not found panic

**Comment by ameshkov** [comment]
The problem is with the web admin panel:

This line is logged in `cleanupAlways()` which is called after `web.httpServer` finishes its work with an error different from `http.ErrServerClosed`
```
2021/02/03 23:45:37 [info] Stopped
```

And then the actual error is logged (that comes from inside the HTTP server):
```
2021/02/03 23:45:37 [fatal] accept tcp 192.168.26.6:8080: accept: invalid argument
```

This may happen if something on your server forcibly closed that socket. Check your server, what could be doing it? Could be a cron job or something like this.

**Comment by VinitSonawane** [comment]
Actually I am using it on the linux image deployed on android device which is connected to network via WLAN.
I think, because of the WiFI hiccups, it loses it's ip for a short time, and that's the reason for this.
I have deployed network trigger script to restart AdGuardHome service every time, hope it will work.

Thank you so much for your inputs !

**Comment by ameshkov** [comment]
Yeah, this explains it indeed. It may help if you change the listen address to `0.0.0.0` instead.

**Comment by bladyle** [comment]
> ope it will work.
> 
> Thank you so much for your inputs !

Sorry for bumping old post but I'm in the same situation. Can you share your script for restarting AdguardHome?
Thanks!
