### ISSUE TITLE
Actualize vetted blocklists in v0.105

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2638]
There are some viable lists suggested there: #1913 

Plus we should fix some mistakes: https://github.com/AdguardTeam/AdGuardHome/issues/2625

**Comment by Aikatsui** [comment]
Update translations before release this version. last months fixed some issues but those're not updated yet atleast for pre-releases
(It'll be better If keep a habit about that for every releases)

**Comment by ameshkov** [comment]
Oh, thanks, we should indeed.

**Comment by ainar-g** [comment]
@ameshkov, I'm thinking about creating two new `recurring` issues: one about blocklists and one about translations.  Although, with regards to blocklists, I think I could just relabel this one.  What do you think?

**Comment by ameshkov** [comment]
Yeah, why not.
