### ISSUE TITLE
"Blocked" and "Filtered" is the same thing?

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2640]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.105.0-SNAPSHOT-5081ead0
* **How did you install AdGuard Home:**
  * GitHub
* **If it's a router or IoT, please write device model:**
  * VPS
* **Operating system and version:**
  * Debian 10

### Actual Behavior
I have two entries in the logs section: "Blocked" and "Filtered". And they have the same functions?

<details><summary>Video:</summary>

https://youtu.be/dw5Uv9EfV60

</details>

**Comment by ameshkov** [comment]
Blocked -- blocked by filters
Filtered -- changed in any way (blocked, safe browsing, safesearch, rewrites, etc)
