### ISSUE TITLE
Docker Image - SSL Protocol Error (record length too long)

### ISSUE THREAD

**Issue by asheroto** [AdguardTeam/AdGuardHome#2642]
I received an error while following your Docker tutorial

https://hub.docker.com/r/adguard/adguardhome

It says SSL Protocol Record Length too Long when testing with Firefox.

I deleted the container and pulled the edge build and it started up fine with that.  Just wanted to give you a heads up.

**Comment by ameshkov** [comment]
Most likely, this is a glitch with Docker Hub, no worries
