### ISSUE TITLE
I have some problems again

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#2645]
Help please. I have some problems again. The memory is consumed, the web interface is not loaded. I attach the full log file. Thanks. Version 0.104.3. OpenWrt 19.07
[AdGuardHome2-5-14_31.log](https://github.com/AdguardTeam/AdGuardHome/files/5932135/AdGuardHome2-5-14_31.log)

**Comment by ainar-g** [comment]
Hello.

```
fatal error: runtime: out of memory
```

Looks like there is either a memory leak or your system simply doesn't have enough RAM.  Could you please add, how much RAM does the machine have?

**Comment by fizsef** [comment]
RAM: 128 MB ROM: 128 MB 
And not through the fault of AdguardHome, this memory leak occurred, it is not possible to find out from the log?

**Comment by ameshkov** [comment]
We are not aware of any memory leaks in AGH. How many blocklists do you have? More blocklists, more memory is required.

**Comment by fizsef** [comment]
Not much, just four lists, taking up 2.5 MB in total.

**Comment by ameshkov** [comment]
Well, that's not much. Normally, AGH won't use much RAM even if it uses many blocklists. Try disabling all lists and see if it starts up normally, then enable them one by one.

**Comment by ainar-g** [comment]
Another thing you could also try is lowering cache sizes by settings `cache_size`, `safebrowsing_cache_size`, `safesearch_cache_size`, and `parental_cache_size` to lower values.

**Comment by fizsef** [comment]
And how will the decline in these indicators affect the work of the program itself? At the moment, such indicators are cache_size: 4194304
safebrowsing_cache_size: 1048576
safesearch_cache_size: 1048576
parental_cache_size: 1048576

**Comment by ainar-g** [comment]
@fizsef, sorry for the late response.  A smaller cache means that some queries may take longer to respond, because they won't be served from cache.

**Comment by ainar-g** [comment]
@fizsef, hello.  Does the issue still occur with the latest releases of AGH?

**Comment by ainar-g** [comment]
No further updates, so closing.
