### ISSUE TITLE
server.go problem (tls)

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdGuardHome#2647]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

when i go https web admin interface (runing 802 port) doh /dot /quic request work perfect only web admin interface 

always get this error

2021/02/05 13:42:22 [debug] web: https: http: TLS handshake error from ip(hidden):50126: EOF

**Comment by ameshkov** [comment]
Is there any other visible problem or is it just the error message in the log?

**Comment by Disqu3-mirOir-qt** [comment]
only this for the momment

**Comment by Disqu3-mirOir-qt** [comment]
i get this sometime too 

2021/02/05 15:32:48 [debug] web: https: http2: server: error reading preface from client ip:46649: read tcp 146.59.157.181:802->ip:46649: i/o timeout

**Comment by ameshkov** [comment]
Well, you can safely ignore these, some network glitches may result in these records, this is not a bug.
