### ISSUE TITLE
Access from wan

### ISSUE THREAD

**Issue by TeHashX** [AdguardTeam/AdGuardHome#2648]
Hi, I setup a server and it's working fine but I want to access it from outside on my android phone, I opened ports 53 and 853 like in this guide but can't connect. 
https://www.reddit.com/r/Adguard/comments/cydqq0/how_to_use_adguard_home_when_not_on_my_lan/

**Comment by ameshkov** [comment]
Well, the easiest way (although not free) is to run AGH on a public server and configure it as a DOH/DOT/DOQ server:
https://github.com/AdguardTeam/AdGuardHome/wiki/VPS
https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption
