### ISSUE TITLE
这个是什么问题？The server is configured to refuse ANY requests？

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#2649]
![图片](https://user-images.githubusercontent.com/28734349/107118962-52ac5500-68bf-11eb-82d3-c930ebe5d54e.png)

**Comment by ameshkov** [comment]
没问题，ANY 是 DNS 查询的类型，建议不允许这个类型。

**Comment by zeroxia** [comment]
这个log也太吓人了。就不能把 ANY 加个引号之类的。

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

如果是局域网使用：
搜索 refuse_any ，改成 false 。
rate_limit 也可以设置为0 。
