### ISSUE TITLE
AGH stops working after reboot

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#2650]
Raspberrypi 4B 5.4.79-v8+
RaspberryOS Lite
Linux ARM: 32-bit ARMv6 (AGHome)
v0.105.0-SNAPSHOT-00700c13
Router and Raspberry are over ethernet connected

Problem description:
Since last release(s) I got problems with AdGuardHome after reboot of my raspberry.

After run "$ sudo reboot" from terminal my raspberry starts and runs as usual, I can access AGH user interface but it didnt resolve (pass-thru) any DNS inquiry. (only the DNS entries cached still work)

So far I just found one solution to get it work:
run "$ sudo reboot"
(then immidetly) reboot ISP router

After both are booted up than they work fine.

Last time I reboot my rpi it worked fine, about 1-2 month ago, if you need more info, feel free to ask.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by uservictor** [comment]
Couldnt reproduce it, maybe there was an conflict on my raspberrypi and affected AdGuardHome.

**Comment by uservictor** [comment]
@ameshkov Sadly the problem is still present.

I enabled the log file but it shows nothing, it shows just the time while i reboot and then when it starts working again (about 10-15 minutes of empty log).

Today i update to new version (v0.106.0-a.71+5d0d32b9) after that it stops working. No website will load, i rebooted router and raspberrypi, it didn't help the only solution was to setup my isp dns in my router so i can acces the internet again.

Hope you can investigate what causes the problem.

**Comment by ameshkov** [comment]
I am not sure this is the same problem.

I honestly have no clue what's the problem with the first one, probably you need to read the system log and figure out when AdGuard Home was actually started.

Regarding the second one, we need the log.

**Comment by ainar-g** [comment]
@uservictor, perhaps you've been affected by #2868?  We've fixed that one just recently, and you'll need to manually fix your config file if that's the case.
