### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by yfwwangyue** [AdguardTeam/AdGuardHome#2652]
![image](https://user-images.githubusercontent.com/67235308/107174593-93ae8180-6a05-11eb-889c-7deddb41be2e.png)
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/beta/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/beta/version.json: Get "https://static.adguard.com/adguardhome/beta/version.json": x509: certificate signed by unknown authority | 502

**Comment by ameshkov** [comment]
Make sure you have root certificates up-to-date on your device. Most likely they're outdated.
