### ISSUE TITLE
Feature Request: Captive Portal Re-Direction for Common Requests

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#2655]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
Many Android devices bypass device-set DNS, bypass device-set VPN, and use WiFi-set DNS + Public IP Address to connect to connectivitycheck.gstatic.com/generate_204, especially when the device in question enters sleep mode. Normally, Google contacts that domain to verify Captive Portal connection and as a "Keep Alive" method, but the evil giant uses that domain to track clients and Public IP's those clients use. AdGuard whitelists that domain and ADB commands that are supposed to disable that connection (settings put global captive_portal_detection_enabled, settings put global captive_portal_server localhost, settings put global captive_portal_mode 0) do not work on many devices.

There are other apps that use Google's clients3.google.com/generate_204 feature, such as WhatsApp.

### Proposed Solution

Create a Re-Direct feature specifically for common Captive Portal and "Keep Alive" domains to return proper "Client is Alive" response without contacting Google or leaving Loopback interface. 

### Alternatives Considered
Fully blocking the domain in question works, but it prevents the device to being fully responsive.

### Additional Information
Maybe this is already possible with AGH's current redirect feature, but I don't know how to configure it for my needs. Sure, I can re-direct it, but to where can I re-direct it to emulate Google's response to make the device think it is connected to Google???

**Comment by ameshkov** [comment]
Well, you need a web server that responds with `204 No Content` response to any plain HTTP request for any `Host` request. Then just add a DNS rewrite that redirects Google's domain to the IP address of that server.

Tbh, I sincerely doubt that Google uses this URL to track anything. Its purpose is purely technical - check if there's a captive portal or not. Google has better ways to track users and their IPs.
