### ISSUE TITLE
AdGuard Home installed but login is a blank screen

### ISSUE THREAD

**Issue by dhiaabdelli** [AdguardTeam/AdGuardHome#2658]
### Steps to reproduce

1.Install AdGuard Home using
2.Go to http://172.30.20.1:3000

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.105.0-SNAPSHOT-63e4adc0, channel edge, arch linux mips softfloat
* **How did you install AdGuard Home:**
  * Github releases
* **How did you setup DNS configuration:**
  * could not set it up since I could not access the screen
* **If it's a router or IoT, please write device model:**
  * it's a router mr3020 openwrt
* **Operating system and version:**
  * Windows 10

### Expected Behavior

Should see the login page

### Actual Behavior

The page is blank

When I tried to setup adguard  using port 3000 the page was bank too soo I used the new beta port 3001 and the page was working after that I tried the login page but it was blank too

I checked my chrome console and I find this :  Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING login.2e821e35c65418d1b19f.js:1

**Comment by ainar-g** [comment]
Hi, could you please clarify if you're running AdGuard Home on Linux, like the AdGuard Home version section says, or on Windows, like the operating system section says?

Also, are there any errors in the logs?  Can you [configure] AdGuard Home to collect more logs by setting  `verbose` to `true` and post logs here as an attachment?

Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

**Comment by dhiaabdelli** [comment]
Yes I'm running AdGuard Home on Linux

[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/5960047/log.txt)

**Comment by spec1re** [comment]
Same here on an old QNAP NAS, blank page after update.

AdGuardHome --version
`AdGuard Home, version v0.105.0, channel release, arch linux arm v5`

uname -a
`Linux QNAP 3.4.6 #1 Tue Oct 6 11:39:23 CST 2020 armv5tel unknown`

Reverting back to 
`AdGuard Home, version 0.104.3, channel release, arch linux arm v5`

And all fine again.

**Comment by ameshkov** [comment]
Could you please check the browser console? Any errors there?

What browser do you use?

**Comment by dhiaabdelli** [comment]
i use chrome and i have this error Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING login.2e821e35c65418d1b19f.js:1

**Comment by ameshkov** [comment]
Do you use any kind of proxy? I don't see what else could be the reason.

**Comment by ainar-g** [comment]
@dhiaabdelli, @spec1re, I've just pushed 7b01408, which should improve the situation for some cases.  Could you please update and see if that fixes the issue?  Thanks!

**Comment by spec1re** [comment]
AdGuardHome --version
`AdGuard Home, version v0.106.0-SNAPSHOT-7b014082, channel edge, arch linux arm v5`
![image](https://user-images.githubusercontent.com/11883076/107668840-66760380-6c91-11eb-8b2b-660a5b17890c.png)
Google Chrome in Incognito Mode (with cache cleared)

AdGuardHome --version
`AdGuard Home, version v0.105.0, channel release, arch linux arm v5`
![image](https://user-images.githubusercontent.com/11883076/107669346-edc37700-6c91-11eb-88c4-b67c423545a1.png)
Here no such error.

**Comment by dhiaabdelli** [comment]
same problem for me
Version : AdGuard Home, version v0.106.0-SNAPSHOT-7b014082, channel edge, arch linux mips softfloat

when im installing adguard the page on port 3000 is blank but 3001 is not. after the install the page is blank again like the port 3000

**Comment by ameshkov** [comment]
Tbh, I have no idea besides a proxy that modifies responses.

**Comment by spec1re** [comment]
No Proxy involved here, tested AdGuard Home v0.105.0 on FreeBSD 12 and Debian Buster and no problem with the new Version,  its just the arm v5 build that is somehow broken.

**Comment by ameshkov** [comment]
Ah, that's interesting, I haven't thought about it that way. This may be a golang-related bug then, we'll test it.

**Comment by dhiaabdelli** [comment]
I think it's only broken in the arm v5 and MIPS builds

**Comment by dhiaabdelli** [comment]
Today this problem happened to me again on ubuntu server running AdGuard Home, version v0.105.0, channel release, arch linux amd64 and i did some tests and I am 100% sure now that it is being caused by my windows anti-virus.
whenever I disable the real-time protection the issue disappears. I left the real-time protection off for 2-4 hours and the issue never occurred a few moments ago i switched it back on and the problem was back within a minute

**Comment by ainar-g** [comment]
@dhiaabdelli, thank you for the information, it's very helpful!

@spec1re, do you also use Windows with an antivirus to access the web interface?  If so, does disabling the protection help?

**Comment by spec1re** [comment]
Updatet to v0.105.1 few minutes ago, now everything works as expected. 

Much appreciated, thanks!

**Comment by ameshkov** [comment]
Tbh, I have no idea what we changed to fix this issue, but I am happy to hear it's resolved :)

**Comment by mateusztylec** [comment]
I encountered the same problem. In my case it was due to the fact that I was running 3 replicas of the docker container. Probably something went wrong with database. I will leave that info here
