### ISSUE TITLE
Reachable from localhost, but timeout on 127.0.0.1 and public domain on docker image

### ISSUE THREAD

**Issue by tbelbek** [AdguardTeam/AdGuardHome#2659]
Hello, I set up a docker adguard container on my windows server. Setup ok, WebUI reachable from port 3000 but when I do nslookup, dig etc. there is some weird problem. server answers OK for "localhost", but drops to timeout when I set the server address to "127.0.0.1" or public domain and also public ip. Firewall rules, docker ports are configured properly.

![image](https://user-images.githubusercontent.com/9684414/107477902-a9e54a80-6b89-11eb-98fd-086c84e388d3.png)

And here is the answer I got when timeout happens.

![image](https://user-images.githubusercontent.com/9684414/107477846-91753000-6b89-11eb-8d33-116bb31c2517.png)

Is there anything that I miss?

**Comment by ainar-g** [comment]
Hi, could you please clarify some things:

1.  What version of AdGuard Home are you running?
1.  Do you make these requests from the same machine?
1.  Can you provide one example of a lookup command that fails and another one that succeeds?

Thanks!

**Comment by tbelbek** [comment]
Hello,

Using the latest image from docker, adguard/adguardhome:latest means v0.104.1 I think.

I tried making request from local and also from a remote computer. The commands I tried are 
**from local;**
nslookup google.com tbelbek.com --> this is the public domain, FAIL
nslookup google.com 127.0.0.1, FAIL
nslookup google.com localhost, SUCCESS

**from remote;**
nslookup google.com tbelbek.com, FAIL
nslookup google.com 87.98.219.187, FAIL

If there is any info you require, I can also provide that.

Thnx!

**Comment by ainar-g** [comment]
Thanks for the info!  I wasn't able to reproduce the issue on my Linux machine.  I've forwarded this issue to some colleagues for additional testing.  Perhaps they will have more questions later.

**Comment by tbelbek** [comment]
I had my instance running on windows with latest docker engine version, FYI

**Comment by tbelbek** [comment]
I fixed this problem. There was a VPN app listens port 53 for VPN over DNS. I closed that feature and voila, it worked. anyways, thank for your help.
