### ISSUE TITLE
Family filter: Some porn sites still work

### ISSUE THREAD

**Issue by Esokrates** [AdguardTeam/AdGuardHome#266]
Please have a look at the findings from here:
https://hackernoon.com/porn-filters-compared-opendns-neustar-cleanbrowsing-norton-yandex-and-adguard-41f207062c4
Direct link to the list:
https://pastebin.com/raw/ztA7HQVE

**Comment by TPS** [comment]
Wouldn't a pretty simple meta-workaround consist of comparing not-previously-classified sites via, e.g., OpenDNS regular vs OpenDNS Family, (of course, w/ some site that the TOS would _allow_ such)?

**Comment by ameshkov** [comment]
Blocking adult websites was greatly improved since then
