### ISSUE TITLE
Statistics are reset after each reboot

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2661]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.105.0
* **How did you install AdGuard Home:**
  * Github releases
* **If it's a router or IoT, please write device model:**
  * VPS
* **Operating system and version:**
  * Debian 10

### Expected Behavior
Statistics are saved after reboot.

### Actual Behavior
Statistics are reset after each reboot actually.

### Additional Information
The [logs](https://github.com/AdguardTeam/AdGuardHome/files/5960694/log.txt) is attached.

**Comment by ainar-g** [comment]
Hi, can you please show, what your statistics interval is set to?  It's the `statistics_interval` setting in the configuration file.

**Comment by ammnt** [comment]
@ainar-g,  `statistics_interval: 30`. The difference in this installation was that I install the server under an unprivileged user via sudo. Possible need to check the installation script... It seemed to me that I had already created such a problem before, but I can not find it now in repo😪

**Comment by ainar-g** [comment]
The current stats code seems to hide a lot of useful information, unfortunately.  I've just pushed a623ac6, where I added more verbose logging to the code.  Could you please update and collect the new logs?  Thanks!

**Comment by ammnt** [comment]
@ainar-g, unfortunately, that server is gone, but i tried to reproduce it on my VM and it looks fine now🤷🏻‍♂️ IDK how to help here🙄

**Comment by ammnt** [comment]
@ainar-g, i found it:
https://github.com/AdguardTeam/AdGuardHome/issues/1785
May be useful😒

**Comment by ammnt** [comment]
@ainar-g, I have successfully reproduced the issue again on the latest edge version. The [log](https://github.com/AdguardTeam/AdGuardHome/files/5990167/log.txt) attached - please, take a look. The also screenshots is as confirmation is attached:
![2021-02-16_19-40-44](https://user-images.githubusercontent.com/45385632/108094102-82154b80-708f-11eb-9c0b-fc64e441f83d.png)
![2021-02-16_19-42-58](https://user-images.githubusercontent.com/45385632/108094106-83467880-708f-11eb-87f0-08e552b342f5.png)
The second screenshot - its after reboot. Thank you.

**Comment by ainar-g** [comment]
That's not statistics though, that's query log.

How exactly do you reboot the machine?  AdGuard Home keeps a buffer of recent queries in the RAM, so if it is not shut down properly, that buffer could remain unflushed to the filesystem.

**Comment by ammnt** [comment]
@ainar-g, via my hosting provider panel and this was not before on 0.102.0, 0.103.0 etc. version🤨

**Comment by ainar-g** [comment]
I don't think that that particular mechanism has changed much in the recent releases.  At least I don't remember that.  If you can, you should set up your machine to kill the AGH process with `SIGINT`, which should force flushing, and wait until it goes down.  Alternatively, you could also set `dns.querylog_size_memory` to a lower value, so that the flushing happens more often.

**Comment by ammnt** [comment]
@ainar-g, i set `querylog_size_memory 10` instead 1000 and restart the server. All query logs and statistics are gone after that😂

**Comment by ainar-g** [comment]
Are you sure that your `data/querylog.json` is not deleted by some other entity?  That's the file where the logs are kept.  And the statistics data is also in the `data/` directory.

**Comment by ammnt** [comment]
@ainar-g, yes, i'm sure. Moreover, part of the statistics disappears, and not all.

**Comment by ainar-g** [comment]
I have no ideas besides the VPS's filesystem shenanigans.  We've never seen anything similar.  If you have a stable reproduction on a machine that is not on the same VPS, please let us know.
