### ISSUE TITLE
Wrong version tag on Docker Hub

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2663]
Source report: https://t.me/adguard_en/118070

> I guess something went wrong in your pipeline which is responsible for publishing docker image on docker hub. At the moment alternative tag to latest version of AdGuardHome is v0.0.0 instead of v.0.105.0

**Comment by mazay** [comment]
Would you consider releasing a HF?

**Comment by ainar-g** [comment]
@mazay, we're planning to push v0.105.1 on Monday, which should fix this.

**Comment by ainar-g** [comment]
@mazay, the new bugfix release is out.  The version seems to be set correctly this time.

**Comment by mazay** [comment]
Cool, thanks a lot!
