### ISSUE TITLE
Which dns is being used?

### ISSUE THREAD

**Issue by fsheidaiee** [AdguardTeam/AdGuardHome#2665]
Hi
I have entered some dns sdns and the app is picking the best dns.
how can I know which dns is being used?
thanks

**Comment by LordMerlin** [comment]
I have a similar question.
In the screenshots of beta version 105, it was clear that it was shown which type of DNS was used, DOH or DOT, or normal. Update 0.105.0 has come and there is no such thing. Everything is displayed as "Plain DNS", although I do not have conventional servers in the list of DNS servers at all, and in the extended information about the request it is clear that these are responses from the DOH or DOT server.

**Comment by ameshkov** [comment]
First - the protocol over which AGH received the query:
https://uploads.adguard.com/up04_AdGuard_Home_eoio2.png

And this is the upstream that has been used:
![image](https://user-images.githubusercontent.com/5947035/107613823-22b3d780-6c5a-11eb-855d-f507feaa369f.png)
