### ISSUE TITLE
Error: control/access/set | json.Decode

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#2666]
Не могу добавить IP в "Запрещенные клиенты" выдает ошибку Error: control/access/set | json.Decode: attempted to read more than 65536 bytes | 400 - на данный момент у меня заблокировано IP 8985.. (https://t.me/adguardru/350?comment=105933)

### Issue Details

* **Version of AdGuard Home server:**
  * v0.105.0
* **Operating system and version:**
  * Windows 10, Windows Server

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/107612334-15e1b480-6c57-11eb-8dce-ccc502191a55.png)
</details>

**Comment by ainar-g** [comment]
Спасибо за информацию!  Проблема должна быть исправлена в версии f016ae17 на канале *edge*.  Можете проверить, работает ли наше решение для вас?

**Comment by Eyeborgs** [comment]
@ainar-g проверил, теперь все работает
