### ISSUE TITLE
Unable to build on Arch Linux (v0.105.0)

### ISSUE THREAD

**Issue by graysky2** [AdguardTeam/AdGuardHome#2668]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.105.0
* **How did you install AdGuard Home:**
  * Github release
* **Operating system and version:**
  * Arch Linux

### Expected Behavior
Running `make` should successful build AdGuardHome

### Actual Behavior

Following [how-to-build](https://github.com/AdguardTeam/AdGuardHome#how-to-build), standard Arch toolchain is installed in addition to the deps:
* go v1.15.8
* nodejs v15.8.0
* npm v6.14.11
* yarn v1.22.10

* Build log is [here](https://gist.github.com/graysky2/51046f3c0687098ba33dd7e40c240098).
* Debug log (/build/.npm/_logs/2021-02-11T11_26_38_425Z-debug.log) is [here](https://gist.github.com/graysky2/282c862e382a6f1a6e0faaa41dad4e6f).

Link to AUR package for [AdGuardHome](https://aur.archlinux.org/packages/adguardhome/).

**Comment by ainar-g** [comment]
Hi, and thank you for the report.  The log looks rather weird.  Like it's running commands out of order.  Could you please add which `make` and which version you're using (for example, GNU Make, BSD Make, and so on)?  Also, do you happen to use `make -j` either directly or through `MAKEFLAGS` by chance?

**Comment by graysky2** [comment]
@ainar-g

Arch ships `make` from GNU and is current  v4.3.  The `MAKEFLAGS` for my system use `make -j9` but interestingly when I force `make -j1`, then build, it finishes without error.

**Comment by ainar-g** [comment]
I see.  I don't think we've ever supported `-j`, to be honest.  In the issue you provide, the previous developer said that we should fix it, but I can't seem to find any proof that any work was done towards that.  Do you have any clues?

`-j` is a [non-POSIX] feature, and as far as I know its semantics may vary between versions of `make`.  At the very least, we must document the current behaviour.  As for actual support, I'll need to investigate how difficult that will be.

[non-POSIX]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html

**Comment by graysky2** [comment]
OK, no problem.  We can build with `make -j1` ... I'll leave it to you to decide next steps.  Maybe make a note of this on the [how-to-build](https://github.com/AdguardTeam/AdGuardHome#how-to-build) section in case other users run across it.

**Comment by ainar-g** [comment]
I added a paragraph about `make -j` to our readme.

We'll consider refactoring the makefile again to make dependencies more explicit without losing the ability to build different parts of the server separately, but I don't think that that will be an easy task, unfortunately.

Anyway, thanks for the report!

**Comment by graysky2** [comment]
You're welcome.  Thanks for the quick engagement.
