### ISSUE TITLE
Upstream Test Error

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#2670]
Just updated to version 0.105.0 on Raspberry Pi 4 Model B 4GB with the latest Raspberry Pi OS updates and get this: 
Error: "control/test_upstream_dns | Network Error"

I've confirmed network connectivity with all devices that I run this server on

Just an FYI, Thanks

**Comment by ainar-g** [comment]
Hi, and thank you for your report!  Could you please add the following information:

 *  What do the errors look like in the “Console” and “Network” tabs of your browser's developer tools?
 *  Do you have HTTPS enabled by chance?
 *  Are there any errors in the verbose logs?  You can make your logs verbose by setting `verbose` to `true` in your configuration file.

Thanks!

**Comment by ainar-g** [comment]
Additional question, do you happen to use an HTTP proxy or something like Pi-Hole's `unbound`?

**Comment by zrgardn** [comment]
Hello, as of right now I tell you that HTTPS is disabled in my Adguard Home portal and I do not use Pi-Hole in any way, shape or form. I actually went from Pi-Hole to Adguard Home as it is more customizable and user friendly. I will follow up with you in regards to the verbose logs and Developer options when I get the chance. Thank you for your time!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zrgardn** [comment]
Hello, attached is a screenshot of what is going on, I hope this helps! Just an FYI this issue is not affecting the performance of the server at least in my case. Let me know if you need any further information.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ainar-g** [comment]
The author seems to have become a ghost, and the screenshot seems to be missing.  I'm going to close this one.  If the author resurfaces, we'll look into it again.
