### ISSUE TITLE
Cannot get DoT identifiers working

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#2672]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.105.0
* **How did you install AdGuard Home:**
  *  Github release
* **How did you setup DNS configuration:**
  *  Debian 10 install, DHCP assigned DNS, Wildcard SSL and Public DoT
* **If it's a router or IoT, please write device model:**
  * N.A
* **CPU architecture:**
  * Intel Celeron
* **Operating system and version:**
  * Debian 10

### Expected Behavior
In the latest release the ability was added to set identifiers ClientID to identify speficic users of encrypted services like DoT. I cannot get this to work

### Actual Behavior
My previous setup had an SSL certificate for mydomain.duckdns.org. I could set the Pirvate DNS setting on android to mydomain.duckdns.org and I would see both internal and external requests to adguard switching betwen WiFi and GSM.

In order to use the new client ID functionality I obtained a wildcard certificate for `*.mydomain.duckdns.org`.

Entering this new certificate in the Settings -> Encrytption settings page produces an error for the Server Name filed at the top of the page because `mydomain.duckdns.org` does not match `*.mydomain.duckdns.org`.

So, I tried setting the server name to `adguard.mydomain.duckdns.org`. This stopped the error. I then created three client ID's for the three android phones in the house, and tried to update the private DNS settings on them to eg. `phone1.adguard.mydomain.duckdns.org` but the phone would not connect. I tried `adguard.mydomain.duckdns.org` and this did work (makes sense..). In the end I could only get it to accept the clientID's I had created by deleting the server name completely from the Settings -> Encryption settings page.

The phone will then connect using `phone1.mydomain.duckdns.org`, but the queries that come in over GMS are still tagged with the GSM IP address and not with the phone1 identifier setup in the client list.

In this state the phone will connect if I use `anyname.mydomain.duckdns.org`, but will not connect if I try `anyname.anyname.duckdns.org`, so if I set the servername back to `adguard.mydomain.duckdns.org` and then try and get the phone to connect to `adguard.mydomain.duckdns.org` it will, but it will NOT connect to `phone1.adguard.mydomain.duckdns.org`

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

So, how exactly do you set this up so it works ?? (I assume there must be a way....)

**Comment by ainar-g** [comment]
Hello, just to clarify: you are entering `mydomain.duckdns.org` in the “Server name” field on the “Encryption settings” page, but the page says that it is not correct?

**Comment by ameshkov** [comment]
Does your wildcard certificate only contain `*.mydomain.duckdns.org`? In theory, it should have two sub-altnames: `*.mydomain.duckdns.org` AND `mydomain.duckdns.org`

**Comment by tescophil** [comment]
Exactly..

If I enter mydomain.duckdns.org in the Server Name field at the top of the page, this produces an error under the Certificate section, saying that certificate chain is invalid (because its for *.mydomain.duckdns.org)

![shot](https://user-images.githubusercontent.com/59442445/107763787-09c52800-6d27-11eb-8c14-ebc38de7ecbd.png)

**Comment by ameshkov** [comment]
Check `Hostnames` - it seems that it only contains `*.domain.duckdns.org`. You need the cert to also contain a sub altname for `domain.duckdns.org`.

For instance, check how `adguard.com` cert looks like:
![image](https://user-images.githubusercontent.com/5947035/107764054-98926e80-6d40-11eb-8952-c9796f273f57.png)

**Comment by tescophil** [comment]
> Does your wildcard certificate only contain `*.mydomain.duckdns.org`? In theory, it should have two sub-altnames: `*.mydomain.duckdns.org` AND `mydomain.duckdns.org`
> 
> In this case you'd be able to use `mydomain.duckdns.org` as the "server name", and use `client.mydomain.duckdns.org` for clients.

As far as I can see it just contains *.mudomain.duckdns.org. I used `certbot` to get the cert, no idea if there are any command line options to request multiple names ??

**Comment by ameshkov** [comment]
I usually use `lego` for that, I just specify two domains there:
```
	./lego \
	--dns cloudflare \
	--domains "${domainName}" \
	--domains "${wildcardDomainName}" \
	--email "${email}" \
	run
```

**Comment by tescophil** [comment]
Sweet, working perfectly now, Great feature !

**Comment by lightmaster** [comment]
I have confirmed that I have a cert that is valid for both `dns.example.com` and `*.dns.example.com` and yet Android gives me an error when I try to use `device.dns.example.com`

**Comment by ameshkov** [comment]
@lightmaster just in case, we recently published an article on the public server setup: https://adguard.com/en/blog/adguard-home-on-public-server.html

> yet Android gives me an error when I try to use device.dns.example.com

If you have `adb` installed, you can examine logcat and see what exactly is wrong with it.

**Comment by lightmaster** [comment]
That article helped. I had forgotten to setup a DNS record for *.dns.example.com

One change I would suggest for that article is instead of telling people to make a `A` record for `*` domain to their IP Address, make a `CNAME` from `*` to `example.com`. If they ever need to change their IP, only have to update 1 record.
