### ISSUE TITLE
Fatal Error: DNSCrypt DNS-over-QUIC, Anonymized DNS

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#2674]
Попробовал сделать DNSCrypt через DNS-over-QUIC и DNSCrypt Anonymized DNS и после этого AGH полностью убивался - в Windows помогало только вернуть AdGuardHome.yaml{я просто делаю резервную копию} и после переустановить службу AdGuardHome.exe --service uninstall а после AdGuardHome.exe --service install и все тогда начало работать - если просто службу запустить после фатальной ошибки не чего не выходит и служба просто останавливается...

Протокол DNSCrypt через DNS-over-TLS работает нормально

### Issue Details

* **Version of AdGuard Home server:**
  * v0.105.0
* **Operating system and version:**
  * Windows 10, Windows Server

### Screenshots

<details><summary>Screenshot:</summary>

DNSCrypt через DNS-over-QUIC
![DNSCrypt-DNS-over-QUIC](https://user-images.githubusercontent.com/46345396/107833666-0e302600-6da5-11eb-9046-a6abd3498830.png)
DNSCrypt Anonymized DNS
![image](https://user-images.githubusercontent.com/46345396/107834482-56e8de80-6da7-11eb-9183-9963f646a039.png)
Лог из CMD
![image](https://user-images.githubusercontent.com/46345396/107834597-9c0d1080-6da7-11eb-9d03-d050978413c8.png)

</details>

**Comment by ameshkov** [comment]
Ну Anonymized DNSCrypt мы просто не поддерживаем, может в этом дело?

**Comment by Eyeborgs** [comment]
@ameshkov Ну а почему она ломает весть AGH ?

**Comment by ameshkov** [comment]
А вы через интерфейс задавали или через yaml?

**Comment by Eyeborgs** [comment]
@ameshkov через интерфейс

**Comment by ameshkov** [comment]
@ainar-g @EugeneOne1 не хватает минимальной валидации апстримов - надо хотя бы проверять, что мы можем распарсить нормально апстрим.

**Comment by EugeneOne1** [comment]
Снэпшот 1122e71 должен решить возникшую у вас проблему, но, к сожалению, лишь частично.  Дело в том, что одна из наших библиотек все еще не дает возможность настроить _DNSCrypt_ через _DNS-over-QUIC_.  Тем не менее, ожидается, что _AdGuard Home_ больше не будет требовать переустановки, чтобы запуститься после ошибки, которую вы нашли.  Не могли бы вы проверить, решилась ли возникшая проблема у вас?

**Comment by Eyeborgs** [comment]
@EugeneOne1 проверил, теперь AGH не убивается после ошибки.

**Comment by EugeneOne1** [comment]
@Eyeborgs, благодарим за тестирование.  Проблему с _DNS-over-QUIC_ мы проинспектируем и постараемся решить в скором времени.  Можете открыть новый тикет, если у вас возникнет эта или любая другая проблема.
