### ISSUE TITLE
DHCP server failed after upgrade 0.105

### ISSUE THREAD

**Issue by chicman** [AdguardTeam/AdGuardHome#2676]
- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
V0.105
* **How did you install AdGuard Home:**
Github release
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
Nano pi R2S
* **CPU architecture:**
ARM64
* **Operating system and version:**
friendlyWRT

### Expected Behavior

DHCP server was all functional until upgraded to V0.105. 

### Actual Behavior

WebGUI shows error:
" Error: control/dhcp/set_config | enabling dhcp: checking static ip: open /etc/network/interfaces: no such file or directory | 500 "

There is no such /etc/network folder under friendlyWRT.

Please let me know if any additional information would be needed.

Best Wishes!

**Comment by ainar-g** [comment]
This is probably already fixed in the `edge` channel, and will be fixed in v0.105.1, which is coming soon.

**Comment by Akirainblack** [comment]
Tested the edge channel and it's still borked for docker.

**Comment by ainar-g** [comment]
@chicman, @Akirainblack, yes, apparently our build system wasn't pushing Docker images to the edge channel for some time.  We fixed it about three hours ago and published the fixes both to the edge channel and the beta channel.  v0.105.1 should be ready soon as well.

**Comment by Akirainblack** [comment]
Ah, right, excellent, I had updated it just before I remarked. I'll try again tomorrow, thank you.

**Comment by Akirainblack** [comment]
Confirmed, it appears to be working again in 0.105.1 have tried enabling and disabling and enabling again as well as connecting a new device.

Though the lease expiry looks different for new leases:
2021-02-17T07:32:18.762411351Z
when it used to look like: 
2021-02-16T14:53:59Z
Just as an FYI (I am assuming it's just not truncated, but thought I'd let you know) :D

**Comment by ainar-g** [comment]
Thanks for testing!  We'll look into the format change in a new issue.
