### ISSUE TITLE
API /control/dhcp/status returns key RangeStart instead of range_start inside 'v6' object

### ISSUE THREAD

**Issue by jojost1** [AdguardTeam/AdGuardHome#2678]
### Issue Details
* **Version of AdGuard Home server:**
v0.105.0
* **How did you install AdGuard Home:**
Source
* **How did you setup DNS configuration:**
System
* **If it's a router or IoT, please write device model:**
Raspberry Pi Zero W

### Expected Behavior
The 'v6' object in `/control/dhcp/status` returns:
`"v6":{"range_start":"","lease_duration":86400}`

### Actual Behavior
The 'v6' object in `/control/dhcp/status` returns:
`"v6":{"RangeStart":"","lease_duration":86400}`

### Additional Information
All of a sudden I'm seeing a key `RangeStart` instead of the expected `range_start`. I'm not using the DHCP server at the moment. The full response I'm getting:
`{"enabled":false,"interface_name":"","v4":{"gateway_ip":"","subnet_mask":"","range_start":"","range_end":"","lease_duration":86400},"v6":{"RangeStart":"","lease_duration":86400},"leases":[],"static_leases":[{"mac":"18:3e:ef:c3:e8:56","ip":"192.168.1.42","hostname":"M1-Air","expires":"1970-01-01T01:00:01+01:00"}]}`

**Comment by ainar-g** [comment]
Should be fixed on the edge channel as of snapshot aebcd74e.  Can you please recheck?

**Comment by jojost1** [comment]
Hi, I can confirm it's fixed! Fresh install on edge channel gives:
`{"enabled":false,"interface_name":"","v4":{"gateway_ip":"","subnet_mask":"","range_start":"","range_end":"","lease_duration":0},"v6":{"range_start":"","lease_duration":0},"leases":[],"static_leases":[]}`
