### ISSUE TITLE
Adguard Unresponsive - DNS Resolution too long - High CPU Usage

### ISSUE THREAD

**Issue by Warlord1981** [AdguardTeam/AdGuardHome#2679]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed

### Issue Details

Adguard gets unresponsive a few minutes after it is started, DNS queries take too long (5000ms) or timeout. Only solution is to disable and re-anable Adguard. Then works again for some minutes until it goes back to same behaviour. During the issue CPU0 usage monitored with Netdata is almost 50% on "nice" cpu process and monitored with htop it's 90+% on the process of AdGuardHome. Using DoH & DoT servers of Cloudflare, Quad9 & Adguard in Parallel mode as Upstream Servers.

* **Version of AdGuard Home server:**
  v0.105.0
* **How did you setup DNS configuration:**
  Router - Latest Voxel firmware + Latest Kamoj addon
* **If it's a router or IoT, please write device model:**
  NETGEAR R7800

**Comment by ddomengeaux** [comment]
Same issue on a Gl-inet S1300. Turning off tls for upstream servers seems to have fixed the issue for me.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by Warlord1981** [comment]
@ddomengeaux Thank you for your comment. You removed all tls servers from the list or you disabled tls port completely?

@ameshkov Thank you. I stopped Adguard Home and made the two following changes to the AdGuardHome.yaml file and restarted it, but i cannot find any log files on the specified folder. (sda1 is my USB stick)

log_file: /mnt/sda1/AdGuardHome/
verbose: true

**Comment by ameshkov** [comment]
You need to specify the full path to the log file, i.e. `/mnt/sda1/AdGuardHome/log.txt`

**Comment by Warlord1981** [comment]
Thank you for your help, I specified the full path, however there is no log file created.

log_file: /mnt/sda1/AdGuardHome/log.txt
verbose: true

**Comment by ameshkov** [comment]
Have you restarted AG?

**Comment by Warlord1981** [comment]
Of course. I first stop AGH, than make any changes to yaml file and then re-start AGH. I just also tried the path /mnt/sda1/AdGuardHome/adguard.log which made no difference. Additionally I tried different folder in USB stick but with no avail.

If I leave log_file blank what is the default location for the verbose log?

**Comment by nexeck** [comment]
`2021/02/15 08:14:10 11801#65 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): error handling DNS (tls) request: talking to dnsUpstream failed, cause: client id check: client server name "" doesn't match host server name "adguard.dummy.cx"
2021/02/15 08:14:14 11801#65 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 10
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;frontier-va.tiktokv.com.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: do; udp: 8192
; PADDING: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

2021/02/15 08:14:14 11801#65 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): error handling DNS (tls) request: talking to dnsUpstream failed, cause: client id check: client server name "" doesn't match host server name "adguard.dummy.cx"
2021/02/15 08:14:21 11801#65 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 11
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;www.google.com.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: do; udp: 8192
; PADDING: 0000000000000000000000000000000000000000000000000000000000`

**Comment by nexeck** [comment]
Rolling back to 0.104.x fixed this problem for me.

**Comment by Warlord1981** [comment]
> 
> 
> Rolling back to 0.104.x fixed this problem for me.
> 
> The Problem seems to only happen with some Android Smartphones. My MacBook doesn't triggered this problem.

Thank you for your comment. This is my first attempt on Adguard Home, therefore I wouldn't know how previous builds behave.

**Comment by ameshkov** [comment]
@nexeck 
```
2021/02/15 08:14:14 11801#65 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): error handling DNS (tls) request: talking to dnsUpstream failed, cause: client id check: client server name "" doesn't match host server name "adguard.dummy.cx"
```

This issue should go away in v0.105.1. Some clients do not send TLS SNI with the query and that triggered the issue.

**Comment by ameshkov** [comment]
@Warlord1981 tbh, I have no clue what's wrong.

Could it be that you have AGH launched inside Docker? In this case, the log might be stored inside the container.

> Using DoH & DoT servers of Cloudflare, Quad9 & Adguard in Parallel mode as Upstream Servers

Try using different settings here, "load-balancing" for instance.

**Comment by Warlord1981** [comment]
> 
> 
> @Warlord1981 tbh, I have no clue what's wrong.
> 
> Could it be that you have AGH launched inside Docker? In this case, the log might be stored inside the container.
> 
> > Using DoH & DoT servers of Cloudflare, Quad9 & Adguard in Parallel mode as Upstream Servers
> 
> Try using different settings here, "load-balancing" for instance.

My AGH is installed via Kamoj Addon on a Netgear R7800 router that has Voxel Firmware installed. It's not on a Docker.

Using Load-Balancing seems to be better for now.

Also disabling "Adguard browsing security service" seems to lower CPU usage.

Should we enable DNSSEC or using encrypted servers like above makes no sense? Does this setting use s lot of CPU?

**Comment by ameshkov** [comment]
> Should we enable DNSSEC or using encrypted servers like above makes no sense? Does this setting use a lot of CPU?

Yeah, you'd better enable it. It doesn't use any additional CPU because basically it just instructs the upstream DNS servers to check DNSSEC for you.

**Comment by Warlord1981** [comment]
> 
> 
> > Should we enable DNSSEC or using encrypted servers like above makes no sense? Does this setting use a lot of CPU?
> 
> Yeah, you'd better enable it. It doesn't use any additional CPU because basically it just instructs the upstream DNS servers to check DNSSEC for you.

Thank you. Also using too many upstream servers uses much more CPU? Is it wise to mix DoH & Dnsctypt servers?

Load balancing method uses the less cpu out of the 3 options?

**Comment by ameshkov** [comment]
> Also using too many upstream servers uses much more CPU? 

Only if you use parallel queries or fastest IP.

> How about Bootstrap servers. Just input cloudflare's ip's and call it a day?

Yep
