### ISSUE TITLE
Family filter: Enfore safe search for duckduckgo

### ISSUE THREAD

**Issue by Esokrates** [AdguardTeam/AdGuardHome#268]
I have noticed that https://duckduckgo.com/ is not enforced for safe search. According to https://duck.co/help/features/safe-search you could enforce safe search through safe.duckduckgo.com.

**Comment by ameshkov** [comment]
I am not sure if simple resolving duckduckgo.com to safe.duckduckgo.com will work, but it's worth testing, thank you!
