### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yikexiaoyao** [AdguardTeam/AdGuardHome#2680]
Error: control/filtering/refresh | filters update procedure is already running | 500

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by alexpovel** [comment]
Duplicate of #2671 (of which #2687 is also a duplicate)?
