### ISSUE TITLE
nslookup timedout when use browsing security and parent control service in General Settings.

### ISSUE THREAD

**Issue by wxf26054** [AdguardTeam/AdGuardHome#2683]
![image](https://user-images.githubusercontent.com/22016320/107872047-5143e380-6ee2-11eb-88d5-e989030023b2.png)
These are errors in the log output.
![image](https://user-images.githubusercontent.com/22016320/107872088-8b14ea00-6ee2-11eb-9b36-7bc96f9bcdd0.png)

**Comment by ameshkov** [comment]
Well, it just means that `dns-family.adguard.com` is not reachable from your place.

Could it be your ISP blocking it?

**Comment by wxf26054** [comment]
No, It shows ping value is high, but not blocked by the ISP.
![image](https://user-images.githubusercontent.com/22016320/107916762-ce825d80-6fa1-11eb-8e58-695f8b915506.png)

**Comment by ameshkov** [comment]
Well, pinging is not the same as making a query, also packet loss is quite high.

Try using [dnslookup](https://github.com/ameshkov/dnslookup) and do some simple DNS queries:
`dnslookup example.org https://dns-family.adguard.com/dns-query`

**Comment by wxf26054** [comment]
It has normal Query answer.
![image](https://user-images.githubusercontent.com/22016320/108647052-a4292680-74f2-11eb-8236-c916f2167832.png)
