### ISSUE TITLE
docker hub tag v0.105.0

### ISSUE THREAD

**Issue by tob123** [AdguardTeam/AdGuardHome#2684]
### Prerequisites

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

docker tag v0.105.0 is missing on docker hub. The manual suggests to install the latest version.
However, I would like to stick to one version in particular. it is not clear to me what tag on docker hub matches the v0.105.0 release.

### Proposed Solution

please tag the image that matches the v0.105.0 release as such on docker hub or consider to set the tag when you create a new release ? (v0.106.0 or v0.105.1) ?
### Additional Information

version v0.104.1 and v0.104.2 etc. can all be found on docker hub.
see also here for a short note on the latest tag:
https://docs.docker.com/develop/dev-best-practices/

**Comment by ameshkov** [comment]
> However, I would like to stick to one version in particular. it is not clear to me what tag on docker hub matches the v0.105.0 release.

Due to the bug in the deployment process it's marked as v0.0.0. The next update (v0.105.1) should be okay though.
