### ISSUE TITLE
Reverse proxy with client configuration

### ISSUE THREAD

**Issue by Macqael** [AdguardTeam/AdGuardHome#2685]
Hello 
I actually have a question about the new function 0.105 have bringed client id in DOH,
How do we configure reverse proxy to work with these ?
is the same configuration as the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy) or we have to do some change to have https://dns.com/dns-query/clientid to work ?

(in my case i work with nginx)
Thanks

**Comment by ameshkov** [comment]
It should work just okay with the proxy configuration from FAQ, just add the `/clientid` postfix to the path.
