### ISSUE TITLE
Cannot blocking ADs anymore. I tried to restore the settings and import backuped settings, but anying worked.

### ISSUE THREAD

**Issue by wxf26054** [AdguardTeam/AdGuardHome#2689]
The blocklist and custom list all cannot work And have no blocking efforts

**Comment by wxf26054** [comment]
I continuously query blocked domains 6 times, then the query comes to a normal query.

**Comment by ameshkov** [comment]
Please provide a detailed explanation, it's impossible to understand what's the problem when you describe it like that.

**Comment by wxf26054** [comment]
`@@||www.bing.com^$important
@@||ip.taobao.com^$important
@@||www.youtube.com^$important
@@||tools.3g.qq.com^$important
@@||pdc.micloud.xiaomi.net^$important
@@||security.browser.miui.com^$important
@@||proxy.sec.miui.com^$important
@@||up.cm.ksmobile.com^$important
@@||data.mistat.xiaomi.com^$important
@@||api.ad.xiaomi.com^$important
@@||nav.browser.miui.com^$important
||hub5btmain.sandai.net
@@||exp.sug.browser.miui.com^$important
@@||dldir1.qq.com^$important
@@||qurl.f.360.cn^$important
||ludashi.com
||/ludashi/
||munion.baidu.com
||s3m6.nzwgs.com^$important
@@||jspassport.ssl.qhimg.com^$important
@@||bj.ke.com^$important
@@||tj.ke.com^$important
@@||www.ke.com^$important
@@||ke.com^$important
@@||hot.browser.miui.com^$important
@@||api.browser.miui.com^$important
@@||ssl-cdn.static.browser.mi-img.com^$important
@@||u.api.look.360.cn^$important
@@||info.pinyin.sogou.com^$important
@@||thirdwx.qlogo.cn^$important
@@||click.mz.simba.taobao.com^$important
@@||sdkconfig.ad.xiaomi.com^$important
@@||sf1-ttcdn-tos.pstatp.com^$important
@@||cnbj1.fds.api.xiaomi.com^$important
@@||news.qhstatic.com^$important
@@||res.qhupdate.com^$important
@@||s.360.cn^$important
@@||i.snssdk.com^$important
/caohang/
@@||f11.baidu.com^$important
@@||otheve.beacon.qq.com^$important
@@||ini.update.360safe.com^$important
@@||update.360safe.com^$important
@@||cdn.cnbj1.fds.api.mi-img.com^$important
@@||safe.track.uc.360.cn^$important
@@||openbox.mobilem.360.cn^$important
||fclog.baidu.com^$important
@@||a.hl.mi.com^$client='222.94.45.162'
@@||a.hl.mi.com^$important
@@||144.dragonparking.com^$important
@@||msg.qy.net^$important
@@||zconfig.alibabausercontent.com^$important
@@||appdownload.alicdn.com^$important
@@||mini.eastday.com^$important
@@||ttpcstatic.dftoutiao.com^$important
||xmtransfer.dpqct.com^$important
/xmtransfer/
||MgP6ChGz.retjidc.cn^$important
/retjidc/
@@||admin.online.360.cn^$important
@@||feed.browser.miui.com^$important
@@||profile3.se.360.cn^$important
@@||profile2.se.360.cn^$important
@@||profile1.se.360.cn^$important
@@||profile.se.360.cn^$important
@@||www.so.com^$important
@@||so.com^$important
@@||smart.sug.so.com^$important
@@||policy.jd.com^$important
@@||mars.jd.com^$important
@@||bdsp.x.jd.com^$important
@@||wq.360buyimg.com^$important
||99.95chuanqi.vip:99^$important
||99.95chuanqi.vip^$important
||95chuanqi.vip^$important
||95chuanqi^$important
/95chuanqi/
/duosf/
/945/
/zsf.com/
||cq.chuanqi3366.vip^$important
/chuanqi3366/
||www.fbwat.ch^$important
||drive.app.goo.gl^$important
||luandinh.s3.amazonaws.com^$important
||xz.chinavipsoft.com^$important
||ymjqn.bijiatu.com^$important
||hectorstatic.baidu.com^$important
||dss2.baidu.com^$important
||dss3.baidu.com^$important
||sp2.baidu.com^$important
||ss1.bdstatic.com^$important
||sta.xsfaya.com^$important
||softdown.panshixk.com^$important
||down.leisurelypanda.com^$important
||d.wn51.com^$important
||rq.drcct.cloud.duba.net^$important
||rq.upgrade.cmpc.cmcm.com^$important
||jcxyt.cangyakeji.cn^$important
||duba-defend.zhhainiao.com^$important
||wsid.liangxiekeji.cn^$important
||jgztg.binghuokeji.cn^$important
||mgfkm.binghuokeji.cn^$important
||gqwmz.chengsi.cn^$important
||sta2.xsfaya.com^$important
||down.wdmuz.com^$important
||myqnj.xsfaya.com^$important
||dhztq.leisurelypanda.com^$important
||update.wn51.com^$important
||download.xsfaya.com^$important
||g.jyapi.yebankeji.cn^$important
||rq.r9t1.com^$important
||p.jyapi.yebankeji.cn^$important
||mmtkm.zsincer.com^$important
||zmiwn.bijiatu.com^$important
||down.znshuru.com^$important
||mgyzt.zycultura.com^$important
||tjtv3.wn51.com^$important
||infoc2.duba.net^$important
||ebqhwz.gdpoly.cn^$important
||down1.nanjingchenxi.com^$important
||08imgmini.eastday.com^$important
@@||dl.360safe.com^$important
@@||src.dl.360safe.com^$important
/ieeod0/
/liangxiekeji/
/5887979/
@@||pdown.stat.360safe.com^$important
@@||inst.360safe.com^$important
@@||down.360safe.com^$important
@@||dl2.360safe.com^$important
@@||vconf.f.360.cn^$important
@@||updateh.360safe.com^$important
@@||api.driver.360safe.com^$important
@@||dlb.driver.360safe.com^$important
@@||sdl.360safe.com^$important
/tanwan/
/17tanwan/
/mediav/
@@||diagnosis.ad.xiaomi.com^$important
@@||loc.map.baidu.com^$important
@@||www.msftconnecttest.com^$client='117.132.198.177'
@@||api-shoulei-ssl.xunlei.com^$important
@@||api.miui.security.xiaomi.com^$important
@@||appsupport.qq.com^$important
@@||api-mcp.adsp.xunlei.com^$important
@@||api.sec.miui.com^$important
@@||qsb.browser.miui.com^$important
@@||tracking.miui.com^$important
@@||pass.cainiao.com^$important
@@||static.iask.cn^$important
@@||pic.iask.com.cn^$important
@@||pic.iask.cn^$important
@@||watson.telemetry.microsoft.com^$important
@@||self.events.data.microsoft.com^$important
@@||ic3.events.data.microsoft.com^$important
@@||u.qurl.f.360.cn^$important
/lieqinews/
||nk2.ytyvn.com^$important
||ytyvn^$important
||8zrct4vf.ucframe.csnxqht.cn^$important
/8zrct4vf/
/ucframe/
/csnxqht/
/5jfglnr6/
/k0jbvgE1/
/yAu8SZgH/
/eastday/
@@||bkimg.cdn.bcebos.com^$important
@@||resolver.msg.xiaomi.net^$important
@@||policy.video.iqiyi.com^$important
@@||ag.qq.com^$important
@@||v20.events.data.microsoft.com^$important
@@||edge.activity.windows.com^$important
@@||nexus.officeapps.live.com^$important
@@||seupdate.360safe.com^$important
@@||stat.360safe.com^$important
@@||updatem.360safe.com^$important
@@||big.softdl.360tpcdn.com^$important
@@||agd2.p.360.cn^$important
||pp4.gndh444.top^$important
/pp4/
/gndh444/
@@||cdn-file-ssl-bizhi.ludashi.com^$important
@@||stat.sd.360.cn^$important
/hg127/
/dwnvrevnwejijvirjb/
/398xy/
@@||soa-vip-ssl.xunlei.com^$important
||wangjianbing.hao.360.cn^$important
@@||as.weixin.qq.com^$important
@@||se.360.cn^$important
@@||r.browser.miui.com^$important
@@||hd.browser.miui.com^$important
@@||e.weather.com.cn^$important
@@||mb.yidianzixun.com^$important
||dy.dun.ornglad.com^$important
/ornglad/
||www.ahsbk.cn^$important
/ahsbk/
@@||ozone.10jqka.com.cn^$important
@@||stat.10jqka.com.cn^$important
@@||data.sec.miui.com^$important
@@||adv.sec.miui.com^$important
@@||metok.sys.miui.com^$important
@@||auth.be.sec.miui.com^$important
@@||activity.tuifish.com^$important
@@||dlswbr.baidu.com^$important
@@||confluence.hypers.com^$important
@@||cmshow.gtimg.cn^$important
@@||www.laomaotao.net^$important
@@||smartad.10010.com^$important
@@||pay.wsds.cn^$important
@@||etl-xlmc-ssl.sandai.net^important
@@||optimus-ads.amap.com^$important
||tgb.z6rfbg.cn^$important
/z6rfbg/
||mm.cgbsc9.cn^$important
/cgbsc9/
@@||your-domain.com^
@@||ads.privacy.qq.com^$important
@@||gstaticadssl.l.google.com^$important
@@||ib11.go2yd.com^$important
@@||c121.1017.cn^$important
@@||c5.1017.cn^$important
@@||c9.1017.cn^$important
/chinafoodtv/
/1810100099/
/cnlive/
/cnliveimg/
@@||wwwdrv5.pp8.com^$important
||backstagewww.wnwb.com^$important
/uugtv/
/baidu.code.jjyx.com/
||z.xrccp.com^$important
/xrccp/
||cube.3600.com^$important
||cube.dhrest.com^$important
/dhrest/
||/mediav.com/
||/mediav./
/cube./
/5gcloudshop/
||5gcloudshop.com^
||rqaiot.com^
/ooxx14.rqaiot.com/
/ooxx14/
/rqaiot/
s.hao.360.com`

This is my custom blocklist, but it dosen't work with AdGuardHome. Is there any worong with my blocklist?

**Comment by wxf26054** [comment]
Just like this, I repeat the query several times. It will show me a normal query.
![image](https://user-images.githubusercontent.com/22016320/108498484-e599b600-72e7-11eb-8611-3d96385c7379.png)

**Comment by wxf26054** [comment]
Sorry, it's my fault.... I turned down the related options...
