### ISSUE TITLE
Telegram service not being blocked

### ISSUE THREAD

**Issue by dbrits17** [AdguardTeam/AdGuardHome#2690]
In Filters > Blocked Services, I've toggled on the option to block Telegram services. However, the service is still accessible using the Android app. I'm running Adguard Home v0.105.1 on a Raspberry Pi.

(Thank you so much for adding that service in the last major release.)

**Comment by ameshkov** [comment]
Telegram app cannot be fully blocked on the DNS level, we can only block the website and short links (t.me)
