### ISSUE TITLE
AdGuard Home doesn't use client's custom setting if device connected via DOT, but fine via plain DNS

### ISSUE THREAD

**Issue by wantaquddin** [AdguardTeam/AdGuardHome#2691]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.105.1
* **How did you install AdGuard Home:**
Github releases
* **How did you setup DNS configuration:**
IoT
* **If it's a router or IoT, please write device model:**
Raspberry Pi 3 Model B
* **CPU architecture:**
ARM
* **Operating system and version:**
Raspbian 10 (Buster)

### Expected Behavior
AdGuard Home should use custom client settings when client is connected via DOT

### Actual Behavior
Adguard Home still uses global settings on client

### Screenshots

<details><summary>Screenshot:</summary>

![screencapture-agh-2021-02-16-12_51_59](https://user-images.githubusercontent.com/45927437/108039678-5f773880-7077-11eb-83a6-69090bf836e1.png)

</details>

### Additional Information
1. Device is Xiaomi Mi Note 10 running Android 10, using Private DNS set to AdGuard Home
2. No problem if device uses plain DNS

**Comment by ainar-g** [comment]
Hello, I can't seem to reproduce the issue.  Are the queries from the client showing the correct IP address on the “Query Log” page?  That is, do you see your `192.168.X.X` IP there or something like `127.0.0.0`?

Also, providing a [verbose log], possibly anonymised, of one such query might help.

[verbose log]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by wantaquddin** [comment]
After checking AGH query log, I found the root cause of the problem. Nothing to do with AGH at all. Turns out instead of AGH getting DOT requests from my device's IP address, what AGH get is my router's IP address instead. I guess it has something to do with my router's NAT/firewall rules & NAT loopback settings.
