### ISSUE TITLE
iOS 14 configuration profile returning "no host in query parameters and no server_name"

### ISSUE THREAD

**Issue by Carnage555** [AdguardTeam/AdGuardHome#2693]
### Issue Details

* **Version of AdGuard Home server:** v0.105.1
* **How did you install AdGuard Home:** Docker
* **How did you setup DNS configuration:** System

### Expected Behavior
I should be able to download a .mobileconfig file from the Setup guide as I have Adguard Home running behind a reverse proxy for TLS/DNS-over-HTTPS.

### Actual Behavior
There is no option to download it under the setup guide, and manually downloading it from https://mydomain.com/apple/doh.mobileconfig results in the error `{"message":"no host in query parameters and no server_name"}`.

### Additional Information
I do not have encryption enabled under the encryption settings in the Adguard Home dashboard since my reverse proxy is handling the HTTPS encryption. Attempting to enable it, filling out my domain name and certificates causes the dashboard to not load at all. I am unable to enable it without filling in the information mentioned above.

Aside from that, I have `allow_encrypted_doh` set to true in the config as per the wiki, and strict SNI set to true in the config as well as I read in an issue it was necessary if a reverse proxy was used for encryption (despite not being mentioned in the wiki). Am I missing any other setup steps here causing my issue? The wiki only mentions to route the Adguard IP in the reverse proxy and to make the config change mentioned above.

For the record, DNS-over-HTTPS seems to work fine when manually configured (e.g. in FIrefox on my desktop under network settings, with https://mydomain.com/dns-query) as it shows in the query log that the protocol is DNS-over-HTTPS.

**Comment by ameshkov** [comment]
You should download it from `https://mydomain.com/apple/doh.mobileconfig?host=mydomain.com`
