### ISSUE TITLE
Statistics of request count of top clients not always displayed correctly

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#2694]
- Open the AdGuard Home page and refresh it
- Click on any top [client statistic](https://uploads.adguard.com/Chinaskilgrri.png)
- [Query Log](https://uploads.adguard.com/Chinaskiufnjn.png) is displayed statistics for all clients and not just the selected one

**Comment by Eyeborgs** [comment]
probably because of this the rules do not work for me: @@||*^$client=unfilter
although I did as here: https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#idclient 4. Client ID
