### ISSUE TITLE
Cannot get the query logs beyond  4 to 5 hours

### ISSUE THREAD

**Issue by sudheeshb** [AdguardTeam/AdGuardHome#2697]
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

I am running the latest version : yes v0.105.1
I checked the documentation and found no answer: Yes.  Issue is supposed to get resolved in this versio.
I checked to make sure that this issue has not already been filed:  Not for this release.

### Issue Details
I have enabled 30 days of query logging.  I searched for a client ( with IP address ) using the Web Interface.  I cannot get any logs beyond 4 to 5 hours.   This is via scrolling down continuously.

What is the best way to get the logs during certain dates for certain clients?.  Looks like this is not supported.    Continuous scrolling down is not very efficient and is also limited to 4 to 5 hours.  Rest API ( offset/limit ) also not very useful here.

**Comment by ainar-g** [comment]
Hi, I cannot reproduce the issue on any of our machines.  Could you please add the following information?

1.  Which CPU architecture and OS are you using?
1.  How did you install AdGuard Home (for example, built from source, GitHub release, Docker, Snap, and so on)?
1.  Perhaps [configure] AdGuard Home to collect verbose logs and post the logs here as an attachment?

Thanks.

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by sudheeshb** [comment]
This is what I have done to reproduce the issue.  

1. Go to 'Quey log' from the web interface
2. Search for some client by IP address.
3. Keep scrolling down to get the old data.  You cannot scroll down beyond a ping which 4 to 5 hours less than the current time.

Questions:

What is the best way to get the logs for certain time duration for certain clients?.  Say I want all the logs from one date x to date x+1.  Scrolling down is not an efficient way of doing this.

1.  I am using it in pfsense router which uses FreeBSD 64 bit.
2. I downloaded the binaries for FreeBSD and using that directly.
3.  Will try that.

**Comment by ameshkov** [comment]
Could you please share the anonymized querylog file with us?

Use `scripts/querylog` for that:
https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts#querylog-query-log-helpers

**Comment by sudheeshb** [comment]
Thanks will do that.  Can you please answer the below question?.  I want to know whether is there any way to do this which I am not aware of.

What is the best way to get the logs for certain time duration for certain clients?. Say I want all the logs from one date x to date x+1. Scrolling down is not an efficient way of doing this.

**Comment by ameshkov** [comment]
> What is the best way to get the logs for certain time duration for certain clients?. Say I want all the logs from one date x to date x+1. Scrolling down is not an efficient way of doing this.

Well, there is no way you can filter by time period with how it's currently implemented.

So I guess the only way is to use the API directly: https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

Note that we don't support searching by client name, only by the client IP.
