### ISSUE TITLE
No update button?

### ISSUE THREAD

**Issue by leendersf** [AdguardTeam/AdGuardHome#2698]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * Version: v0.102.0
* **How did you install AdGuard Home:**
  * https://pimylifeup.com/raspberry-pi-adguard-home/

* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior
There should be an Update button?

### Actual Behavior
I only see: AdGuard Home v0.105.1 is now available! Click here for more info.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
The version is just too old to do the automatic update.

You need to update manually, i.e. download the latest release and replace `AdGuardHome` binary.

**Comment by leendersf** [comment]
Thank you! I’m on v0.105.1 now!
