### ISSUE TITLE
View Cache

### ISSUE THREAD

**Issue by marcelloinfoweb** [AdguardTeam/AdGuardHome#2699]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
You don't need to show what's in the cache, but the amount of items stored and items ordered, that's all!

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/1685
