### ISSUE TITLE
Add a checkbox to disable hostname resolution and stop AdGuardHome from sending PTR requests.

### ISSUE THREAD

**Issue by wpehrc** [AdguardTeam/AdGuardHome#2702]
### Problem Description

Related: #2348
AdGuardHome itself is currently sending a *lot* of completely useless PTR queries (1.1.168.192.in-addr.arpa) the the *upstream* server as it attempts to do hostname resolution, even though the remote upstream is not able to answer any of them, since this is in the private address space. Hostname resolution has never worked for me as there is nothing on my network that can actually answer this kind of queries, so I wish there is a more straightforward way to disable this feature entirely.

### Proposed Solution

Add a checkbox in the general settings page to completely disable this feature, thus stop AdGuardHome from sending PTR requests to the remote upstream and leaking local IP addresses.
### Alternatives Considered

Temporary workaround:
- Force all queries silently made by AdGuardHome itself to circle back to itself and then drop all PTR requests in the private address spaces in AdGuardHome (168.192.in-addr.arpa)
  - This **only** works if your host system is configured to send DNS requests to AdGuardHome as well, as in either hard-coded resolv.conf or specified as a DHCP option, because only this way you will be able to catch the PTR queries silently made by AdGuardHome (since it circles back to itself). Otherwise AdGuardHome will essentially keep silently sending a bunch of bogus PTR queries to whatever the remote DNS is essentially silently and leaking a list of your local IP addresses every 10 minutes.
  - It does not work in containers at all, I see PTR queries like `1.0.88.10.in-addr.arpa` on my upstream DNS server every 10 minutes, and this query is made by AdGuardHome itself, there is no way that I can manage or stop it.
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-rdns

### Additional Information

I am not using AdGuardHome's built-in DHCP server, nor do I have any intention of doing so. The DNS server on the device that runs my DHCP server is unable to answer any of the PTR queries either. I really do not know which DNS component is responsible for answering this kind of requests but I assume it would be dnsmasq? If anyone has more information on this, it'd be greatly appreciated.

**Comment by DandelionSprout** [comment]
I know I've questioned the validity of `(...).1.168.192.in-addr.arpa` in my query log several times by now, but I can't for the life of me memorise what they're even meant to accomplish, especially when the queries are made by upstream servers like `Censys`.

![image](https://user-images.githubusercontent.com/22780683/108307548-41602400-71ae-11eb-93b5-62cb73069575.png)

**Comment by ameshkov** [comment]
Moved here: https://github.com/AdguardTeam/AdGuardHome/issues/2704

I suppose it will cover this case as well.
