### ISSUE TITLE
Running Adguard home instance doesn't pickup changes when invoking the binary with reload paramater

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardHome#2707]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.105.1
* **How did you install AdGuard Home:**
  * Github releases
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Virtual Machine
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 10

### Expected Behaviour

When there is an existing instance of Adguard home, running `/path/to/AdGuardHome/AdGuardHome -s reload` should pick up any changes made to the configuration file made manually or through other program.

### Actual Behaviour

When AGH is invoked with reload parameter, existing Adguard home instance doesn't pickup the changes until the service is restarted as a whole.

Steps to reproduce:

1. Start Adguard home
2. Add a comment entry to `dns_upstream` array in configuration file like `'# test comment'` for example
3. Call AGH binary with reload paramater, `/path/to/AdGuardHome/AdGuardHome -s reload`
4. Check the DNS upstream GUI to see if the changes are picked up

### Additional Information

The default systemd file provided by AGH is modified to run it as non root user.

<details><summary>systemd file:</summary>

```
[Unit]
Description=AdGuard Home: Network-level blocker
ConditionFileIsExecutable=/opt/AdGuardHome/AdGuardHome
After=syslog.target network-online.target

[Service]
StartLimitInterval=5
StartLimitBurst=10
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
PermissionsStartOnly=true
User=aghome
Group=aghome
ExecStart=/opt/AdGuardHome/AdGuardHome "-s" "run"

WorkingDirectory=/opt/AdGuardHome



StandardOutput=file:/var/log/AdGuardHome.out
StandardError=file:/var/log/AdGuardHome.err
Restart=always
RestartSec=10
EnvironmentFile=-/etc/sysconfig/AdGuardHome

[Install]
WantedBy=multi-user.target
```

</details>

**Comment by ameshkov** [comment]
Unfortunately, this is expected, `reload` only picks up a few settings changes.

We're yet to implement the "normal" reload.
