### ISSUE TITLE
Introduce some custom options in the dashboard

### ISSUE THREAD

**Issue by Suansuan-Keai** [AdguardTeam/AdGuardHome#2708]
### Problem Description
The Dashboard can introduce some custom options to make it only shows the data that I care about.

### Proposed Solution
We can let the user choose what data do they want to see on the panel , and use the space of the data that needn't show to show more details of data users interested in.
For example , I'm not using the browsing security web service and I do not need enforce safe search.
![Orignal](https://user-images.githubusercontent.com/69025582/108447559-130c4280-729b-11eb-96de-8d6d5468af02.png)
So, if I only care about the number of DNS queries and blocked queries , I think each chart occupies half of the space of 4 chart is a way.
By the way , it can introduce a pie chart to show percentage of each query types .

**Comment by Aikatsui** [comment]
See https://github.com/AdguardTeam/AdGuardHome/issues/689

**Comment by Suansuan-Keai** [comment]
@Aikatsui 
Got it.
And how about  introducing a pie chart to show percentage of each query types?

**Comment by Aikatsui** [comment]
提交[新的](https://github.com/AdguardTeam/AdGuardHome/issues/new/choose)FR

**Comment by ameshkov** [comment]
Marked as dup
