### ISSUE TITLE
Rule counter triggered

### ISSUE THREAD

**Issue by Izya12** [AdguardTeam/AdGuardHome#2709]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

There is no way to see how many times the rule was triggered.
### Proposed Solution

To understand the effectiveness of the rules, I would like to be able to view the number of triggers for each rule and filter logs not only by clients but also by rules.

**Comment by Aikatsui** [comment]
This's too extended feature similar https://github.com/AdguardTeam/AdGuardHome/issues/1408 and there're related issues  https://github.com/AdguardTeam/AdGuardHome/issues/580 https://github.com/AdguardTeam/AdGuardHome/issues/1336 however you can be achieve this via https://github.com/AdguardTeam/AdGuardHome/issues/1164

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/580
