### ISSUE TITLE
Settings Backup / Restore - 2 Systems

### ISSUE THREAD

**Issue by ProfHaase** [AdguardTeam/AdGuardHome#2710]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Hi,

I would like to export my AdGuardHome settings and import them on another system in order to have the same settings on two systems for a Failover.
I copied the AdGuardHome.YAML file, but the second system does not start up with this file.

Apparently the IP address of the system is stored in the YAML file and not just the AGH settings, could that be the problem?

Thank you

### Proposed Solution
A sensible export / import function would be great.

**Comment by Aikatsui** [comment]
See your question already answered [here](https://github.com/AdguardTeam/AdGuardHome/issues/1147#issuecomment-549900458)

**Comment by ameshkov** [comment]
Dup of #1147
