### ISSUE TITLE
SHUTDOWN REBOOT FEATURE

### ISSUE THREAD

**Issue by FeelDomotique69** [AdguardTeam/AdGuardHome#2717]
HI

I appreciate ADGUARHOME but would be great if reboot shutdown  would be easy to find to avois connecting via ssh to shutdown linux.

perhaps missing something too ;-)

regards

Philippe

**Comment by Aikatsui** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2677

**Comment by ameshkov** [comment]
Marked as dup
