### ISSUE TITLE
Can the number of times of rule use be displayed in DNS blocklists 

### ISSUE THREAD

**Issue by VwEl** [AdguardTeam/AdGuardHome#2719]
Can you display the number of times the rule is used in the DNS blocklists, that is, the number of interceptions, so that it is convenient to adjust the more practical rules in the application

**Comment by Aikatsui** [comment]
See https://github.com/AdguardTeam/AdGuardHome/issues/2709

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/580
