### ISSUE TITLE
control/install/check_config | Network Error

### ISSUE THREAD

**Issue by felixbay** [AdguardTeam/AdGuardHome#2721]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Aikatsui** [comment]
We don't know how to help you, please follow relevant issue template
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started
