### ISSUE TITLE
Limit only plain DNS by CIDR/IP

### ISSUE THREAD

**Issue by sigaloid** [AdguardTeam/AdGuardHome#2722]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
I'd like to block only plain DNS by CIDR/AS code, not DoH.

### Proposed Solution
Allow blocking subdivided by connection type, or just find out what code I need to edit/patch 

### Alternatives Considered
Whitelisting my CIDR, but elsewhere I cannot use DoH. 

### Additional Information
Doesn't need to be a whole new option or configuration, I'm fine with just finding out what line of code I need to comment out in order to skip client checking if the request is DoH.

**Comment by ameshkov** [comment]
Here it is: https://github.com/AdguardTeam/AdGuardHome/blob/master/internal/dnsforward/filter.go#L16

If `d.Req` is not empty -- this is DOH.

**Comment by sigaloid** [comment]
Thanks :grinning:
