### ISSUE TITLE
Auto-populate hostnames of DHCP clients

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#2723]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Currently, it's a hassle to manage DHCP leases... because I don't know the hostnames for all clients. 

The `hostname` column is empty as a result. Would be nice if AdGuardHome is able to query the hostnames of connected clients and fill the field automatically. 

### Proposed Solution

Auto detect connected devices' hostnames.

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by ameshkov** [comment]
AdGuard Home works as a DHCP server in your case, right?

We could auto-generate something like `192-168-0-155.lan` for instance.

**Comment by agneevX** [comment]
Yes, I'm running AGH as the DHCP server as its the only way to get per-device stats.

What I meant is the actual hostname of the device... in case one is not available, then a _generated-based-on-IP_ hostname can be assigned (or both could exist!)

Also `.lan`, can that be customized? AFAIK my Orbi router does not support DHCP domain names so would be nice if AGH could help here.

**Comment by ameshkov** [comment]
> Also .lan, can that be customized?

Not in the current version, but we have a task about that already.

**Comment by ameshkov** [comment]
@ainar-g what do you think about this one? Looks trivial, can we do it alongside https://github.com/AdguardTeam/AdGuardHome/issues/2393 ?

**Comment by ainar-g** [comment]
@ameshkov, perhaps, although I'm going to need more research into the current code to understand, how intrusive the change will be.  Will set to v0.106.0 for now, and we'll see how it goes.

**Comment by EugeneOne1** [comment]
Hello, @agneevX!  The feature should be available as of snapshot a1450c55955e51a81c138f565a7d0dab68fea6b0.  Could you please check if there are any unassigned hostnames left?

**Comment by agneevX** [comment]
Hi! Sorry, until this makes it to a stable release, I won't be able to test.

**Comment by EugeneOne1** [comment]
I see, we'll close the issue for now.  Please, feel free to reopen it if our solution won't work properly for you.
