### ISSUE TITLE
 adguard problem

### ISSUE THREAD

**Issue by mghaly6** [AdguardTeam/AdGuardHome#2725]
**hi I have an issue with adguard on raspberry pi** 

Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns10.quad9.net:443/dns-query', cause: Get "https://dns10.quad9.net:443/dns-query?dns=0p8BAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ": synthetic.wrap: all dialers failed to initialize connection: , cause: dial tcp [2620:fe::10]:443: connect: network is unreachable (hidden: dial tcp [2620:fe::fe:10]:443: connect: network is unreachable) | 502

**Comment by ameshkov** [comment]
Well, for some reason, `dns10.quad9.net` is only resolved to IPv6 addresses in your case.

Try setting a different bootstrap DNS server or try using a different upstream server (`https://1.1.1.1/dns-query` for example).

**Comment by mghaly6** [comment]
thanks for your advice work perfectly :)
