### ISSUE TITLE
Build on Illumos (Solaris) failed: "undefined: interfaces.BindToInterface"

### ISSUE THREAD

**Issue by anjog** [AdguardTeam/AdGuardHome#2753]
I was curious if building AdGuardHome on OmniOS (Illumos, Solaris-Fork) would be successful. But both 

`env GOOS='illumos' GOARCH='amd64' make`

and

`env GOOS='solaris' GOARCH='amd64' make`

failed with (last 11 output lines):

> webpack 5.18.0 compiled with 3 warnings in 71936 ms
Done in 75.08s.
env COMMIT='$(git rev-parse --short HEAD)' CHANNEL='development' GPG_KEY='devteam@adguard.com' GPG_KEY_PASSPHRASE='not-a-real-password' DIST_DIR='dist' GO='go' GOPROXY='https://goproxy.cn,https://goproxy.io,direct' PATH="${PWD}/bin:$(go env GOPATH)/bin:${PATH}" SIGN='1' VERBOSE='0' VERSION='v0.0.0' "/usr/xpg4/bin/sh" ./scripts/make/go-build.sh
\# github.com/insomniacslk/dhcp/dhcpv4
../go/pkg/mod/github.com/insomniacslk/dhcp@v0.0.0-20201112113307-4de412bc85d8/dhcpv4/bindtointerface.go:9:9: undefined: interfaces.BindToInterface
*** Error code 2
make: Fatal error: Command failed for target `go-build'

This seems to be an issue similar to this one [here](https://github.com/elastic/beats/issues/15256), because Solaris and its forks are BSD OSes too and therefore should also make use of [bindtodevice_bsd.go](https://github.com/insomniacslk/dhcp/blob/cc9239ac62943a78e89ef4880c8ebdd0ca9ae21e/interfaces/bindtodevice_bsd.go#L12).

Reading this, I also tried building with GOOS=netbsd:

`env GOOS='netbsd' GOARCH='amd64' make`

which finished without throwing an error but the resulting binary wasn't executable (process was killed immediately and ldd reports "ldd: ./AdGuardHome: file is not a dynamic executable or shared object").

I'm not a golang specialist, so is there a way to force usage of "bindtodevice_bsd.go", which would be a good chance to successfully build AdGuardHome on Solaris?

**Comment by ainar-g** [comment]
Hi.  As you can see, the issue is in the external module, [`github.com/insomniacslk/dhcp`].  If you think that Illumos support can be implemented there, you should probably file an issue with them.

[`github.com/insomniacslk/dhcp`]: https://github.com/insomniacslk/dhcp
