### ISSUE TITLE
canyoublockit.com vs. AdGuardHome v0.104.3

### ISSUE THREAD

**Issue by OverengineeredNetwork** [AdguardTeam/AdGuardHome#2756]
* **Version of AdGuard Home server:**
  * v0.104.3
* **How did you install AdGuard Home:**
  * Built from source + docker following these steps: https://github.com/boostchicken/udm-utilities/tree/master/AdguardHome
* **How did you setup DNS configuration:**
  * Forced_intfc settings in 10-dns.sh script
* **If it's a router or IoT, please write device model:**
  * Ubiquiti Dream Machine Pro
* **CPU architecture:**
  * ARM (I think)
* **Operating system and version:**
  * Controller 6.0.43 / Firmware 1.8.6

### Expected Behavior
Block ads and pass ad-blocking tests.

### Actual Behavior
Generally blocks ads, but does not perform well against canyoublockit.com and other ad-blocking test sites.

### Screenshots

<details><summary>Screenshot:</summary>

[Screen Shot 2021-02-24 at 10 44 00 PM](https://user-images.githubusercontent.com/12820826/109104594-e076a580-76f1-11eb-8536-883829662ce8.png)

</details>

### Additional Information
AdGuardHome + AdGuard Chrome Browser extension seems to pass the canyoublockit.com test. But AdGuardHome on its own does not.

**Comment by bbartlomiej** [comment]
This depends heavily on the blocklists you use. I tried your canyoublockit.com link and on both basic and extreme test I don't see advertisements. AdBlockHome + uBlock Origin

**Comment by uservictor** [comment]
On second test "eXtreme Test" for DNS based AdBlockers like AGH it works fine for me.

No ads and banners, I use AGH SDNS, Adaway, Spam404 and NoCoin list.

**Comment by OverengineeredNetwork** [comment]
Thanks for the feedback.

@bbartlomiej I couldn't find a ublock origin list. It looks like a similar utility to AdGuardHome. Is there a ublock origin list somewhere that I'm missing?

@uservictor I appear to be using the same lists except for SDNS.
[Screen Shot 2021-02-24 at 10 44 00 PM](https://user-images.githubusercontent.com/12820826/109104594-e076a580-76f1-11eb-8536-883829662ce8.png)

**Comment by uservictor** [comment]
SDNS is the default AGH DNS list, on the "first" test like your picture i see the same ads.
The other test doesnt show any ad.

You get shown ads that are not in the list you use, this has nothing to do with AGH, as its function is "just" to check if an requested url is on the blacklist that you use or not, when its on the list then it will be blocked.

**Comment by OverengineeredNetwork** [comment]
@uservictor Understood.

Is there a Ublock origin list or a better way to consolidate these lists?

I think I read about blocking Google DNS at the firewall level to stop those ads too.

**Comment by uservictor** [comment]
I am not sure if there is any ad shown on this page or if those pictures are just example placeholder.

When I click on those pcture or look on the url of it, all redirects to the mainsite "canyoublockit.com" if they are ads they should have some ad related url.

You can disable all ad blockers and clear cache, then test in on the site.
As far I can say the filterlists block it all and the pictures are no ads.
