### ISSUE TITLE
AdGuardHome installed wrong Init script

### ISSUE THREAD

**Issue by berna1995** [AdguardTeam/AdGuardHome#2757]
* **Version of AdGuard Home server:**
  * 0.105.1
* **How did you install AdGuard Home:**
  * Github release, manually
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * DGA4130
* **CPU architecture:**
  * ARM
* **Operating system and version:**
  * OpenWRT 15.05

### Expected Behavior
After install, i would exepct AdGuard to run and enable the correct init script

### Actual Behavior
Init script is installed in /etc/init.d but it's not the correct one for OpenWRT and so it doesn't "enable" it.

### Additional Information
Problem might be related to how OpenWRT is detected.

https://github.com/AdguardTeam/AdGuardHome/blob/0d67aa251d18f8ab47cfd90072e9d0387dff4224/internal/util/helpers.go#L68-L79

There is no guarantee that /etc/os-release file will be present in the host system, you should rather look for /etc/openwrt_release.

**Comment by EugeneOne1** [comment]
We've tried to improve the _OpenWRT_ detection as of snapshot 91403d0.  Could you please check if our solution fixes the issue for you?

**Comment by berna1995** [comment]
I unfortunately cannot, at the moment, im running AdGuard Home in my main router and i would love not to reinstall it from scratch.

**Comment by EugeneOne1** [comment]
Well, thanks for opening an issue anyway.  Our testers checked the solution on our test machines, including the _OpenWRT_ one, before it was merged to `master`.  The closest update which will include that commit is `0.105.2`.  We'll close the issue for now.  Feel free to reopen it if the bug persists after updating.

**Comment by adworacz** [comment]
I just ran into this bug using a custom build from [Divested](https://forum.openwrt.org/t/divested-wrt-no-nonsense-hardened-builds-for-linksys-wrt-series/80522), which is effectively running OpenWRT HEAD with a few patches.

Looking at the AdguardHome code, it's checking for `/etc/release`, which doesn't exist on my image.

However `/etc/openwrt_release` DOES exist, and contains the following:
```
DISTRIB_ID='Divested-WRT'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r17276+9-b1bff5cb57'
DISTRIB_TARGET='mvebu/cortexa9'
DISTRIB_ARCH='arm_cortex-a9_vfpv3-d16'
DISTRIB_DESCRIPTION='Divested-WRT SNAPSHOT r17276+9-b1bff5cb57'
DISTRIB_TAINTS='no-all'
```
