### ISSUE TITLE
provide uid/gid settings in config file

### ISSUE THREAD

**Issue by kenyloveg** [AdguardTeam/AdGuardHome#2763]
Hi, dear developpers
 I would assume current gid value of adguardhome on openwrt is gid=0.
Could you make an option or change the default gid to a new one, so the iptables can operate based on the gid?
Thanks.

**Comment by kenyloveg** [comment]
This was a discussed 5 years ago, but for dnsmasq.
FYI
https://openwrt-devel.openwrt.narkive.com/sazTnNOJ/patch-rfc-dnsmasq-run-as-dedicated-uid-gid

**Comment by ameshkov** [comment]
Well, we don't maintain an openwrt package. If you're using one, I guess you need to address this question to it's author.

**Comment by kenyloveg** [comment]
ok then.
Maybe add gid/uid setting in configuration files? At lease provide an option for this situation.
Thanks.

**Comment by ameshkov** [comment]
It seems dnsmasq itself decides under which user it works, AGH is different, it does not do this and it will work under the same user that started the process. So you just need to edit the openwrt service file and make sure it is started under the user you need.

**Comment by ainar-g** [comment]
Just fyi, Go only started properly supporting `setuid` and `setgid` on Linux in Go 1.16, to which we plan to switch in the v0.107 cycle.  So we won't really be able to do anything with those syscalls until that milestone.

**Comment by kenyloveg** [comment]
> Just fyi, Go only started properly supporting `setuid` and `setgid` on Linux in Go 1.16, to which we plan to switch in the v0.107 cycle. So we won't really be able to do anything with those syscalls until that milestone.

Thanks for your information.
Would you add this function via config file or even better (with drop down list read from /etc/passwd)?

**Comment by ainar-g** [comment]
The details are currently unclear, sorry.  We'll need to take care of the current and the next cycle first.

**Comment by kenyloveg** [comment]
> The details are currently unclear, sorry. We'll need to take care of the current and the next cycle first.

Sure, just take it in mind, it's not critical to the current build. I'm happy what adguardhome can do now.

**Comment by ameshkov** [comment]
@ainar-g will you transform this issue into enhancement or a feature request then?

**Comment by ainar-g** [comment]
This is implemented as of snapshot 3b874784.  Can you please check if our solution works for you?

**Comment by ainar-g** [comment]
We'll close this issue for now.  Please file new ones if you encounter any issues.  Thanks.
