### ISSUE TITLE
Apple M1 Chip - Native Support

### ISSUE THREAD

**Issue by Clay-Hammer** [AdguardTeam/AdGuardHome#2771]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
Currently when using the AdGuard application on a Mac with the Apple M1 chip, one must use the Rosetta emulator to run the application. The use with Rosetta provides inadequate performance and does not provide a great user experience. 

### Proposed Solution
Create ***native*** support for the Apple M1 chips.

**Comment by Clay-Hammer** [comment]
I uninstalled the application because of this issue, hence why I did not select "running the latest version" in the Prerequisites section.

**Comment by ameshkov** [comment]
M1 will be supported automatically by ARM64 builds when we start using Go v1.16 for building AGH.

We intend to do that in v0.106, so marking this as a duplicate.

**Comment by ainar-g** [comment]
The main ticket is #2443.  Also, @ameshkov, the current plan is to support it in v0.107, **not** in v0.106.
