### ISSUE TITLE
CNAME-cloaked Trackers

### ISSUE THREAD

**Issue by timyardley** [AdguardTeam/AdGuardHome#2779]
Is there a way to utilize the cname cloaked trackers in adguard home? Short of compiling the list manually?

https://github.com/AdguardTeam/cname-trackers

**Comment by ameshkov** [comment]
Well, it's already utilized, AdGuard Home blocks CNAME trackers by default.

**Comment by WildByDesign** [comment]
@ameshkov Are the cname-trackers part of (or included in) the AdGuardSDNSFilter list?

Sorry for the likely simplistic question, but my understanding of cname tracker blocking is very limited at the moment. Thank you.

**Comment by ameshkov** [comment]
@WildByDesign look, the DNS filter includes the original trackers because the products that use it are capable of scanning CNAMEs, they don't need the list of their "disguises".

This full list is included in AG Tracking Protection list (and probably soon will be included in EasyPrivacy) so that we could cover all other content blockers including those, that cannot scan CNAMEs.

**Comment by timyardley** [comment]
@ameshkov i appreciate the clarification. Based on the fact that the advised team published this blog yesterday, wrote an academic paper on it, and just made that list available... I’m sure you can understand the confusion. 

Thank you for providing the clarification that adguard home already has the ability to do this as part of its core functionality and therefore does not need the additional filter lists. From the adguard team blog, it was unclear that adguard home also had this capability.

**Comment by ameshkov** [comment]
No worries, I am happy to clarify:)

**Comment by WildByDesign** [comment]
@ameshkov Thank you so much. I appreciate the extra info. I will read more into the blog post and all other details posted as well because I am quite excited about this now that I have a better understanding. Your Team is fantastic, always. Cheers!
