### ISSUE TITLE
Cannot connect to internet after installing and setting on Raspberry Pi

### ISSUE THREAD

**Issue by quyleanh** [AdguardTeam/AdGuardHome#2781]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home, version v0.105.1, channel release, arch linux arm64
* **How did you install AdGuard Home:**
  * Use [Automated install linux and mac method](https://github.com/AdguardTeam/AdGuardHome#automated-install-linux-and-mac)
* **How did you setup DNS configuration:**
  * I installed Adguard Home on Raspberry Pi, which is connected with router.
  * On Pi device, I already had `LEMP` server running on `port 80`. So I changed Admin Web interface web to Pi's `eth0` IP (`192.168.1.6:3300`). DNS server was configured with default value: Listen all (`0.0.0.0:53`).
  * On router, I opened port `3300` and `53` for Pi's `eth0` IP (`192.168.1.6`)
  * Configured router, my device DNS server to `192.168.1.6`
  * On Pi, all needed ports were allowed with `ufw`
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B+
* **CPU architecture:**
  * Arch Linux ARM64
* **Operating system and version:**
  * Ubuntu Server 20.04.2

### Expected Behavior
* The DNS server running on Pi works.
* On the Admin Interface Web, the statistics is updated.

### Actual Behavior
* The DNS server running on Pi does not work. Cannot access to internet.
* On the Admin Interface Web, the statistics is not update. There is zero on all statistics.

### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/9365035/110085019-2c48df00-7dc3-11eb-8a2e-033fbe3dc026.png)

</details>

### Additional Information
* I tried to restart AdguardHome service, there is no strange log and error.
* I turned on `log_file` and set `verbose` to `true`, but there is no strange log. 
* I think there are some problem with `resolv.conf` file and resolve service.

**Comment by ainar-g** [comment]
Hi, and thank you for your report.  Can you please tell us:

 1.   Is your Pi's IP, `192.168.1.6` a static lease?  Could that be the case that the machine's IP has changed?

 2.   Can you provide the verbose log as an attachment?

 3.   If the router is also the DHCP server, is your router set up to also send `192.168.1.6` as the DNS server to the clients?

 4.   If you use, for example, `nslookup example.com 192.168.1.6` or `dig example.com @192.168.1.6`, does it work?  Do the statistics reflect those queries?

Thanks!

**Comment by quyleanh** [comment]
Thank you for your quick response.

1. No, my router set up with DHCP mode. The `192.168.1.6` is currently assigned to Pi.
2. I try to reinstall AdguardHome again and here is my [Adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/6090344/Adguard.log)
3. My router is DHCP server, and I set up its DNS server address with Pi's address (`192.168.1.6`)
4. I checked on my Pi and my Mac. The following is result.
* On Pi
```shell
/opt/AdGuardHome nslookup example.com 192.168.1.6
Server:         192.168.1.6
Address:        192.168.1.6#53

Non-authoritative answer:
Name:   example.com
Address: 93.184.216.34
Name:   example.com
Address: 2606:2800:220:1:248:1893:25c8:1946

/opt/AdGuardHome dig example.com @192.168.1.6

; <<>> DiG 9.16.1-Ubuntu <<>> example.com @192.168.1.6
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46076
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;example.com.                   IN      A

;; ANSWER SECTION:
example.com.            36653   IN      A       93.184.216.34

;; Query time: 3 msec
;; SERVER: 192.168.1.6#53(192.168.1.6)
;; WHEN: Fri Mar 05 19:13:07 +07 2021
;; MSG SIZE  rcvd: 45

```
* On Mac
```shell
➜  /Users/quyleanh nslookup example.com 192.168.1.6
;; connection timed out; no servers could be reached

➜  /Users/quyleanh dig example.com @192.168.1.6

; <<>> DiG 9.10.6 <<>> example.com @192.168.1.6
;; global options: +cmd
;; connection timed out; no servers could be reached
```

And here is my [Adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/6090393/Adguard.log) after doing these commands.

Thank you.

**Comment by ainar-g** [comment]
Thanks, that's very helpful!  Unfortunately I don't see anything wrong in the logs either.  We'll investigate deeper later, and until then, please make sure that port 53 is actually open and is available to the outside world.  Like running `sudo ufw status`, and so on.

**Comment by quyleanh** [comment]
Thank for your response. Here is log.

```shell
/opt/AdGuardHome sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
80,443/tcp (Nginx Full)    ALLOW IN    Anywhere
22/tcp                     ALLOW IN    Anywhere
3000                       ALLOW IN    Anywhere
853                        ALLOW IN    Anywhere
3300                       ALLOW IN    Anywhere
80,443/tcp (Nginx Full (v6)) ALLOW IN    Anywhere (v6)
22/tcp (v6)                ALLOW IN    Anywhere (v6)
3000 (v6)                  ALLOW IN    Anywhere (v6)
853 (v6)                   ALLOW IN    Anywhere (v6)
3300 (v6)                  ALLOW IN    Anywhere (v6)

53                         ALLOW OUT   Anywhere                   # allow DNS calls out
123                        ALLOW OUT   Anywhere                   # allow NTP out
80/tcp                     ALLOW OUT   Anywhere                   # allow HTTP traffic out
443/tcp                    ALLOW OUT   Anywhere                   # allow HTTPS traffic out
21/tcp                     ALLOW OUT   Anywhere                   # allow FTP traffic out
68                         ALLOW OUT   Anywhere                   # allow the DHCP client to update
53 (v6)                    ALLOW OUT   Anywhere (v6)              # allow DNS calls out
123 (v6)                   ALLOW OUT   Anywhere (v6)              # allow NTP out
80/tcp (v6)                ALLOW OUT   Anywhere (v6)              # allow HTTP traffic out
443/tcp (v6)               ALLOW OUT   Anywhere (v6)              # allow HTTPS traffic out
21/tcp (v6)                ALLOW OUT   Anywhere (v6)              # allow FTP traffic out
68 (v6)                    ALLOW OUT   Anywhere (v6)              # allow the DHCP client to update
```

**Comment by quyleanh** [comment]
Ha... I think I know the problem. The port `53` is allowed out only. When I allow in the problem is seems fixed.

```shell
/opt/AdGuardHome sudo ufw allow 53
Rule added
Rule added (v6)
/opt/AdGuardHome sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
80,443/tcp (Nginx Full)    ALLOW IN    Anywhere
22/tcp                     ALLOW IN    Anywhere
3000                       ALLOW IN    Anywhere
853                        ALLOW IN    Anywhere
3300                       ALLOW IN    Anywhere
53                         ALLOW IN    Anywhere
80,443/tcp (Nginx Full (v6)) ALLOW IN    Anywhere (v6)
22/tcp (v6)                ALLOW IN    Anywhere (v6)
3000 (v6)                  ALLOW IN    Anywhere (v6)
853 (v6)                   ALLOW IN    Anywhere (v6)
3300 (v6)                  ALLOW IN    Anywhere (v6)
53 (v6)                    ALLOW IN    Anywhere (v6)

53                         ALLOW OUT   Anywhere                   # allow DNS calls out
123                        ALLOW OUT   Anywhere                   # allow NTP out
80/tcp                     ALLOW OUT   Anywhere                   # allow HTTP traffic out
443/tcp                    ALLOW OUT   Anywhere                   # allow HTTPS traffic out
21/tcp                     ALLOW OUT   Anywhere                   # allow FTP traffic out
68                         ALLOW OUT   Anywhere                   # allow the DHCP client to update
53 (v6)                    ALLOW OUT   Anywhere (v6)              # allow DNS calls out
123 (v6)                   ALLOW OUT   Anywhere (v6)              # allow NTP out
80/tcp (v6)                ALLOW OUT   Anywhere (v6)              # allow HTTP traffic out
443/tcp (v6)               ALLOW OUT   Anywhere (v6)              # allow HTTPS traffic out
21/tcp (v6)                ALLOW OUT   Anywhere (v6)              # allow FTP traffic out
68 (v6)                    ALLOW OUT   Anywhere (v6)              # allow the DHCP client to update
```
<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/9365035/110122928-d9871b80-7df2-11eb-913b-f8cfebc12201.png)
</details>

And the [Adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/6090789/Adguard.log) too.

Could you please take a look at this? If there is no problem. I will close this issue.

**Comment by ainar-g** [comment]
If I'm reading that correctly, `ufw` doesn't allow incoming traffic on port 53.  That could be the issue.  Please try allowing both incoming and outgoing traffic on that port and look if that fixes the issue.

**Comment by ainar-g** [comment]
Yes, AdGuard Home needs incoming traffic on port 53 allowed.  If that fixed your issue, it's better to close it.

**Comment by quyleanh** [comment]
Thank you for your kind and helpful.

I will close this issue.
