### ISSUE TITLE
Blocking access to network devices in the local network

### ISSUE THREAD

**Issue by przemasik** [AdguardTeam/AdGuardHome#2786]
I have a strange symptom after running Adguard Home on Raspberry Pi 4 B.
I have my web server running on Rasp (nginx) with the domain xxx.yyy.zzz. In addition, on individual ports I have a router panel and a NAS server (7654, 7655) running outside.
I cannot get to these panels via the local network via the address xxx.yyy.zzz: 7654 and xxx.yyy.zzz: 7655. From the WAN side, no problem. When I turn off security in Adguard, everything works. The Adguard panel running on port 7656 works outside and inside the network.
Via local addresses 192.168.1.1:7654, 192.168.1.2:7655 it works without any problems. Only through the domain it blocks something.

### Prerequisites

- [YES ] I am running the latest version
- [YES ] I checked the documentation and found no answer
- [YES ] I checked to make sure that this issue has not already been filed

### Issue Details

Version of AdGuard Home server: 0.105.1
How did you install AdGuard Home: Raspberry Pi 4 (Raspbian)

**Comment by ameshkov** [comment]
> When I turn off security in Adguard, everything works

Is there anything useful in the Query Log?

**Comment by przemasik** [comment]
OK, this thread can be closed. I solved the problem after using DNS Rewrite.
