### ISSUE TITLE
Extend the list of known companies/trackers/services

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2793]
Extend the list of known categorized domains: https://github.com/AdguardTeam/AdGuardHome/blob/master/client/src/helpers/trackers/adguard.json

Some additional sources:
https://github.com/LM-Firefly/Rules/tree/master/Domestic-Services

**Comment by ainar-g** [comment]
@ameshkov, are you sure that we shouldn't mark this issue as a recurring one?
