### ISSUE TITLE
Add editing options in DNS rewrite

### ISSUE THREAD

**Issue by badgv** [AdguardTeam/AdGuardHome#2796]
It is possible to add editing options in DNS rewrite options

**Comment by ainar-g** [comment]
Hi, could you elaborate on what you would like to achieve?  Also, have you tried using the [`$dnsrewrite` mechanism] in the “Custom filtering rules” section?

[`$dnsrewrite` mechanism]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by DENightOne** [comment]
I think what he means is that you cant edit existing DNS rewrites, meaning to change the rewrite you have to completely delete the rewrite entry in the rewrites tab.  i.e click on the bin icon, then create a new entry.   I have also often made a stupid little error while typing in an IP address too fast and doing it wrong, It would be much easier if I could just click EDIT and only change the error in the IP address.   That being said its not a huge issue for me, so I would treat is as a feature request not an issue
