### ISSUE TITLE
Shouldn't rely on /etc/resolv.conf in macOS

### ISSUE THREAD

**Issue by EugeneOne1** [AdguardTeam/AdGuardHome#2797]
Currently, we use `/etc/resolv.conf` as a source of nameservers while setting the static IP address on macOS:
https://github.com/AdguardTeam/AdGuardHome/blob/2d7042425eb96fcf0097734a6e043186dc7e7946/internal/sysutil/net_darwin.go#L109
However, there is a note inside `/etc/resolv.conf` which states:
```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
```
We should find out a better way of interacting with resolvers in macOS.

**Comment by ameshkov** [comment]
It's not consulted, but it is generated every time the network changes so you can use it as a source of information.

**Comment by EugeneOne1** [comment]
It seems that information in the `/etc/resolv.conf` file is continuously updated.  There is no need to find another way of collecting actual resolvers in macOS.
