### ISSUE TITLE
AGH accepts all XFF headers without restriction

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdGuardHome#2799]
In #1220, AGH accepts some HTTP headers to get the visitor's raw IP.

However, the AGH does not restrict which IPs can send these headers, but accepts them from all IPs.

This means that when the AGH is deployed publicly and uses DoH, rate limiting may be completely useless. The AGH administrator will not be able to use the AGH's own functionality to block malicious users.

I constructed some malicious requests on my AGH server to illustrate the problem more clearly. Obviously, Cloudflare and Google could not have used my server as an upstream.

<details><summary>Screenshot:</summary>
<img width="1168" alt="1" src="https://user-images.githubusercontent.com/13190004/110677495-311cf100-8210-11eb-8dd1-8a106dc19d9b.png">
<img width="1232" alt="2" src="https://user-images.githubusercontent.com/13190004/110677504-337f4b00-8210-11eb-9ffe-721fab8ecb7a.png">
</details>

I recommend that AGH add a separate configuration to allow users to set trusted IPs and trust the local loopback by default (127.0.0.1).

**Comment by SukkaW** [comment]
@ainar-g 

I am afraid it is not a feature request. It should be considered as a security issue.

AGH should implement a restriction to prevent "faking IP".

**Comment by ameshkov** [comment]
> rate limiting may be completely useless

The thing is that rate-limiting currently only works for UDP, it is a measure for mitigating DNS amplification attacks, and other protocols aren't used for that.

This issue does make Access settings useless, though. It's labeled as "enhancement" (which is not a feature request) since it adds functionality (trusted IPs list).

**Comment by EugeneOne1** [comment]
@ZeroClover, there is a new build in the edge channel available.  It implements the trusted proxies feature.  It's also documented in an appropriate [wiki section](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#using-with-reverse-proxy).  Could you please check if it works for you?

**Comment by EugeneOne1** [comment]
We'll close the issue for now.  You're welcome to open the new issues in case of encounter those.
