### ISSUE TITLE
Three SDNS links listed in Knowledge Base for Quad 9 DNS, are failing to work.

### ISSUE THREAD

**Issue by MardukNT** [AdguardTeam/AdGuardHome#2800]
Hello AdGuard team,
I'm attempting to use **Quad9** for my upstream DNS servers with AdGuard Home, and discovered three of the **SDNS** links listed in the AdGuard KB (**[https://kb.adguard.com/en/general/dns-providers#quad9](https://kb.adguard.com/en/general/dns-providers#quad9)**) are popping up errors.

**Errors:**
Server "**sdns://AwAAAAAAAAAAAAATdGxzOi8vMTQ5LjExMi4xMTIuOQ**": could not be used, please check that you've written it correctly. [**Under: Standard 2, DNS-over-TLS, IPv4**]

Server "**sdns://AwAAAAAAAAAAAAAVdGxzOi8vZG5zMTAucXVhZDkubmV0**": could not be used, please check that you've written it correctly. [**Under: Unsecured, DNS-over-TLS, IPv4**]

Server "**sdns://AwAAAAAAAAAAAAAVdGxzOi8vZG5zMTEucXVhZDkubmV0**": could not be used, please check that you've written it correctly. [**Under: ECS Support, DNS-over-TLS, IPv4**]

**Note:** 
Using the corresponding **TLS://** addresses work correctly with AdGuard Home.  So this is only an issue when attempting to use the **SDNS://** addresses listed above, as an Upstream server.

**Supplemental info:** 
None of the Quad9 IPv6 DNS addresses were checked for accuracy. As I currently have IPv6 disabled on my network, by design.

**System info:**
OS Mod: Twister OS version 1.9.9
OS: Raspbian GNU/Linux 10 (buster) aarch64
Host: Raspberry Pi 4 Model B Rev 1.1
Kernel: 5.10.17-v8+
Shell: bash 5.0.3
CPU: (4) @ 2.000GHz
Memory: 593MiB / 3742MiB
Disk (/): 12G / 110G (11%)

**Router info:**
Asus RT-AX88U Router

**AdGuard info:**
AdGuard Home - Version: **v0.105.2**

**Installed using:**
Automated install steps on GitHub

**Upstream DNS servers used:**
[/168.192.in-addr.arpa/]192.168.50.1
#Asus RT-AX88U Router
#----------
sdns://AAAAAAAAAAAABzkuOS45Ljk
#Quad 9 Standard, IPv4
#----------
sdns://AgEAAAAAAAAAAAANZG5zLnF1YWQ5Lm5ldAovZG5zLXF1ZXJ5
#Quad 9 Standard, DNS-over-HTTPS, IPv4
#----------
sdns://AwAAAAAAAAAAAAANZG5zLnF1YWQ5Lm5ldA
#Quad 9 Standard, DNS-over-TLS, IPv4
#----------
sdns://AQEAAAAAAAAAEjE0OS4xMTIuMTEyLjk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0
#Quad 9 Standard, DNSCrypt, IPv4
#----------
sdns://AAAAAAAAAAAADTE0OS4xMTIuMTEyLjk
#Quad 9 Standard 2, IPv4
#----------
sdns://AgEAAAAAAAAAAAANZG5zLnF1YWQ5Lm5ldAovZG5zLXF1ZXJ5
#Quad 9 Standard 2, DNS-over-HTTPS, IPv4
#----------
tls://149.112.112.9
#Quad 9 Standard 2, DNS-over-TLS, IPv4
#----------
sdns://AQEAAAAAAAAAEjE0OS4xMTIuMTEyLjk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0
#Quad 9 Standard 2, DNSCrypt, IPv4
#----------
sdns://AAAAAAAAAAAACDkuOS45LjEx
#Quad 9 ECS, IPv4
#----------
sdns://AgEAAAAAAAAAAAAPZG5zMTEucXVhZDkubmV0Ci9kbnMtcXVlcnk
#Quad 9 ECS, DNS-over-HTTPS, IPv4
#----------
tls://dns11.quad9.net
#Quad 9 ECS, DNS-over-TLS, IPv4
#----------
sdns://AQMAAAAAAAAADTkuOS45LjExOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA
#Quad 9 ECS, DNSCrypt, IPv4
#----------

**Bootstrap DNS servers used:**
9.9.9.9
9.9.9.11
149.112.112.9
149.112.112.11
149.112.112.112

-- Let me know if you require any additional info.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardKnowledgeBase #769](https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/769) via [**ZenHub**](https://www.zenhub.com/)
