### ISSUE TITLE
DNS listening address changes from 127.0.0.1 to 0.0.0.0 after startup

### ISSUE THREAD

**Issue by laggardkernel** [AdguardTeam/AdGuardHome#2807]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * version v0.105.2, channel release, arch darwin amd64
* **How did you install AdGuard Home:**
  * Github releases
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Macbook
* **CPU architecture:**
  * x86_64
* **Operating system and version:**
  * macOS 10.14.6

### Description
DNS is set to bind on `127.0.0.1` in configuration, but it changes to `0.0.0.0` on specific condition. Seems only UDP listening address is affected.

Related conf

```
dns:
  bind_host: 127.0.0.1
  port: 53
```

How to reproduce the bug.

```
❯ AdGuardHome --version
AdGuard Home, version v0.105.2, channel release, arch darwin amd64

# Clear the DNS set in "System Preferences -> Network",
# change it back to the DNS dispatch by the router
❯ networksetup -setdnsservers "Wi-Fi" empty

# Check the conf file to make sure `bind_host` is set `127.0.0.1`.
# Then start adguard home
❯ sudo AdGuardHome -w /usr/local/etc/adguardhome -s start
2021/03/12 13:19:33 [info] Service control action: start
2021/03/12 13:19:33 [info] Action start has been done successfully on darwin-launchd

~
❯ sudo lsof -i :53
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
AdGuardHo 77951 root   15u  IPv4 0x75e1237716cbfaa9      0t0  UDP localhost:domain
AdGuardHo 77951 root   22u  IPv4 0x75e1237726b74fc9      0t0  TCP localhost:domain (LISTEN)

# Set 127.0.0.1 as the default DNS on the OS. No different with setting it in "system preferences -> network"
❯ networksetup -setdnsservers "Wi-Fi" 127.0.0.1

# Here's the problem. Listening address is changed dynamically.
❯ sudo lsof -i :53
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
AdGuardHo 77951 root   15u  IPv4 0x75e1237716cbfaa9      0t0  UDP *:domain  # weird
AdGuardHo 77951 root   22u  IPv4 0x75e1237726b74fc9      0t0  TCP localhost:domain (LISTEN)

# It does serve queries on non loopback interfaces
# 192.168.2.242 is the address assigned on my machine in the Wi-Fi network
❯ dig @192.168.2.242 -p 53 www.google.com

; <<>> DiG 9.16.12 <<>> @192.168.2.242 -p 53 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55992
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         87      IN      A       216.58.194.196

;; Query time: 768 msec
;; SERVER: 192.168.2.242#53(192.168.2.242)
;; WHEN: Fri Mar 12 13:39:29 CST 2021
;; MSG SIZE  rcvd: 59

# And only UDP listening address is affected
❯ dig @192.168.2.242 -p 53 +tcp www.google.com
;; Connection to 192.168.2.242#53(192.168.2.242) for www.google.com failed: connection refused.
```

**Comment by ainar-g** [comment]
We had a very similar issue recently in #2623, but that one was about Big Sur.  We'll investigate, thanks!

**Comment by EntropySmoke** [comment]
This may be related (or not). My Raspberry Pi DNS is set to 127.0.0.1 in dhcpd.conf, but AdGuardHome.yaml reports host bind on 0.0.0.0. Is this a correct configuration?

**Comment by EugeneOne1** [comment]
@laggardkernel, latest build was just pushed to the edge channel.  Could you please check if it fixes the issue for you?

**Comment by EugeneOne1** [comment]
@laggardkernel, we'll close the issue for now.  Please, feel free to reopen it if our solution won't fix it for you.

**Comment by laggardkernel** [comment]
@EugeneOne1 Yes. Tested with 0.107.0-b.7 and I can confirm the problem resolved. Thanks.
