### ISSUE TITLE
Adguard DNS Status page

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardHome#281]
Every few weeks, AGDNS will go down for me.  I'd love to have dedicated (even automated), authoritative page (on an independent server, naturally) that shows what, if any issues, AGDNS is detected as having.

A great example close-to-home, as-it-were: https://status.github.com/

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardDNS #6](https://github.com/AdguardTeam/AdGuardDNS/issues/6) via [**ZenHub**](https://www.zenhub.com/)

**Comment by TPS** [comment]
**_Now solved @  https://status.adguard.com/!_**
