### ISSUE TITLE
Provide better information about hot to change admin password for AdGuard  Home

### ISSUE THREAD

**Issue by freed00m** [AdguardTeam/AdGuardHome#2810]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version -- *almost* I have 0.105.1
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.105.1
  * **How did you install AdGuard Home:**
  * opkg install adguardhome

### Expected Behavior
To be able to read the documentation steps a and be able to complete the steps easily

### Actual Behavior
The instruction given does not provide the exact example command and hashing parameters, leaving users guessing.

### Additional Information

Will provide PR to the documentation after I find the answer of how the password is hashed.

**Comment by freed00m** [comment]
[0001-Provide-htpasswd-example.patch.txt](https://github.com/AdguardTeam/AdGuardHome/files/6136491/0001-Provide-htpasswd-example.patch.txt)


Something like this, the wiki is not public and we can't create PR towards it

**Comment by ameshkov** [comment]
Done, thank you!

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset
