### ISSUE TITLE
auth protection

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdGuardHome#2822]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no 

actualy auth adguardHome not have protection i mean if people wan,t try bruteforce auth http he can retry unlimited maybe max-retry good idea

good idea to add client ip for log dns if fail login for parsing to fail2ban 

ty

**Comment by ameshkov** [comment]
Filed it here: https://github.com/AdguardTeam/AdGuardHome/issues/2826
