### ISSUE TITLE
Better Caddy reverse proxy config?

### ISSUE THREAD

**Issue by Mr-Sheep** [AdguardTeam/AdGuardHome#2833]
This is not really a bug report, but the sample reverse proxy config for Caddy given in the [FAQ](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy) can be simplified
Assuming that AdGuard is listening on port 2053
```
doamin {
	encode gzip zstd
	tls email@example.com
	reverse_proxy 127.0.0.1:2053
}
```
Also, I think `allow_unencrypted_doh` should be set to `true`

**Comment by Mr-Sheep** [comment]
Also, when trying to use AGH behind reverse proxy with Cloudflare CDN enabled, I cannot login to the admin page will `Error code: SSL_ERROR_NO_CYPHER_OVERLAP`

**Comment by ameshkov** [comment]
> Also, when trying to use AGH behind reverse proxy with Cloudflare CDN enabled, I cannot login to the admin page with Error code: SSL_ERROR_NO_CYPHER_OVERLAP

I am almost sure this one should be solved on the caddy-side.

**Comment by Mr-Sheep** [comment]
> I am almost sure this one should be solved on the caddy-side.
I'll try to figure it out lol, caddy v2 is very different from its predecessor

**Comment by ainar-g** [comment]
@Mr-Sheep, we have updated the FAQ and included your version as well.  Sorry for the delay and thanks!
