### ISSUE TITLE
Wrong mobileconfig file extension 

### ISSUE THREAD

**Issue by bgpntx** [AdguardTeam/AdGuardHome#2835]
When I try to download iOS and macOS configuration for both DoH and DoT the server generates doh.xml and dot.xml files instead of dot.mobileconfig and doh.mobileconfig.

* **Version of AdGuard Home server:**
  * 

Steps to reproduce: navigate to 'Setup guide' menu, try to download iOS and macOS configuration configurations.

**Comment by EugeneOne1** [comment]
This should be fixed as of snapshot 5243399d9d72121a7df9ca6d542043661cbbefaa.  Could you please check if our solution fixes the issue?

**Comment by EugeneOne1** [comment]
We'll close the issue for now. Feel free to reopen it if the bug persists after updating.  The same goes for any other issue you'll face.  :)
