### ISSUE TITLE
Add DNSCrypt upstreams support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#284]
This is a quite useful feature for those would like to install a self-hosted version of AdGuard DNS.

**Comment by ameshkov** [comment]
We need to be able to configure "sdns://*" URL as an upstream.

**Comment by ibksturm** [comment]
did you solved the sdns:// url?

**Comment by ameshkov** [comment]
We have not yet. In the current version, if you want to have a dnscrypt upstream, you need to setup dnscrypt-proxy and use it's address as an upstream in AdGuard Home.

**Comment by ibksturm** [comment]
Don't Worry :)

i'm Running my own dnscrypt & doh-server (ibksturm & doh-ibksturm), so i was just wundering

greeets
