### ISSUE TITLE
Improve the DHCP data validation on the UI

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2842]
Context: #2541, #2838.

Currently, there are at least three issues:

1. The frontend seems to only validate the last part of the `range_start` and `range_end` IPv4 addresses.  It should instead calculate the difference properly and allow settings, for example, `range_start` to `1.2.3.4` and `range_end` to `1.2.4.1`.
2. The frontend should validate that the new static lease's IP address is within the subnet defined by the netmask.
3. The frontend seems to reject MAC addresses without colons.  This seems overly strict, as `112233AABBCC` and `11:22:33:AA:BB:CC` are technically the same.  In fact, some hardware manufacturers use the first form instead of the second one.

    Note, that the frontend still should send the form with the colons to the backend.

**Comment by mc9662** [comment]
Hi, I'm not 100% sure this is data validation related, but it may be part of that.  I'm running Version: v0.106.0-b.1 on an RPI3

If I stop the service via sudo ./AdGuardHome -s stop 

and manually set DHCPv4 Options in AdGuardHome.yaml to have a secondary DNS (I'm running 2 instances of AdGuardHome for failover) e.g.
 
DHCPv4
    #
    options:
    - 6 ips 192.168.0.10,192.168.0.11

save the yaml, restart the service and make a change in the GUI e.g. change the DHCP lease time to any other value and click "save config" the settings I manually added to the yaml revert to

DHCPv4
    #
    options: []

The GUI seems to reset the yaml and discard any manual changes.  It would be better if the GUI only changes the yaml sections that are editable within the GUI. 

Thanks

Matt

**Comment by ainar-g** [comment]
@mc9662, thanks for reporting.  I've filed a new issue about it.  See #2927.
