### ISSUE TITLE
DHCP: DNS response from static leases

### ISSUE THREAD

**Issue by timo0** [AdguardTeam/AdGuardHome#2845]
I'm using currently the DHCP with static leases and I was expecting that if I do a nslookup to the hostname I will get a proper response. But unfortunately no answer is returned:

```
nslookup avengers
Server:		10.89.1.3
Address:	10.89.1.3#53

** server can't find avengers: NXDOMAIN
```

Version v0.106.0-a.69+eb9526cc

**Comment by ameshkov** [comment]
@ainar-g probably a regression introduced by your recent changes to dhcp

**Comment by ainar-g** [comment]
Hi, have you tried using `nslookup avengers.lan`?  See https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#autohosts.

**Comment by timo0** [comment]
Thanks for the fast feedback! Works as currently expected!

Yes than my issue would be a duplicate to #2393. Closed :)
