### ISSUE TITLE
Provide DNS-over-HTTPS and DNS-over-TLS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#285]
Subj

Details on the task: https://github.com/AdguardTeam/AdGuardHome/issues/285#issuecomment-456449852

**Comment by gedw99** [comment]
That's compelling.
So you point all your mobiles and laptops to your own DNS running on docker with Cloudland and you have privacy for DNS requests and no ADS.
Finally ..

**Comment by KrasnayaPloshchad** [comment]
DNSCrypt-proxy support DoH too, and the server can be accepted via `sdns://` stamp.

**Comment by Bluscream** [comment]
Is DNSCrypt the same as `sdns://` or `tls://` ?

**Comment by ameshkov** [comment]
No, it's a protocol, while sdns is a form of recording DNS server address

**Comment by Bluscream** [comment]
Ah okay that means we need outgoing and icoming support for all three

**Comment by ashwarsadh** [comment]
Other service provider has this feature:
https://blahdns.com/

**Comment by ameshkov** [comment]
`DOH` support has been added to `dnsproxy` in v0.9.11: https://github.com/AdguardTeam/dnsproxy/releases/tag/v0.9.11

Here's what we need to do now:

1. Add new settings section, check the mockup: https://uploads.adguard.com/up04_54sep_Diagrams_-_AGHome_Encryption__Moqups.png
2. Use these new settings field on both Web and DNS server initialization
3. If any certificate in the chain is about to expire (<30 days), show a non-dismissable warning topline with the following text: "Your SSL certificate is about to expire. Update [Encryption settings](https://example.org/)."

Validation rules:
1. Check that the text entered to the "Certificates" field is a list of PEM-encoded certificates.
2. Check that the text entered to the "Private key" field is a PEM-encoded private key.
3. If server name is specified, check that it matches subaltnames of any of the specified certificates.
4. HTTPS and TLS ports are **different** positive integers in the range of 80-65535. Setting HTTPS or TLS to 0 disables DOH/DOT.

**Comment by ameshkov** [comment]
Done: https://github.com/AdguardTeam/AdGuardHome/pull/590
