### ISSUE TITLE
Update the knowledgebase for AdGuard Home

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#2872]
The [knowledgebase for AdGuard Home](https://kb.adguard.com/en/home/overview) is quite minimal in information with a lot of features of AdGuard Home not being explained as to what their function is, and what effect that will have on the system.

Is there any chance this will be updated in the future?

**Comment by ameshkov** [comment]
We generally tend to keep AdGuard Home wiki [here on Github](https://github.com/AdguardTeam/AdGuardHome/wiki) and not there.

In the future we may migrate it, when the things are more stable.
