### ISSUE TITLE
Enable HTTPS for Snap on non-classic systems

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#2887]
On systems such as Ubuntu Core, the classic methods of using HTTPS don't apply and none of the current options provided by AdGuard will work (that I know of).

The Nextcloud snap team also faced this issue, and managed to [build in HTTPS support](https://github.com/nextcloud/nextcloud-snap/commit/ea5b58ef0c0e4fba2a8f50030c0dffd2a1752a8a) .

With the above commit, simply typing in the CLI `sudo nextcloud.enable-https` executed a script for setting up HTTPS on these types of systems.
To quote the command's description from the [source](https://github.com/nextcloud/nextcloud-snap) : 

> Enable HTTPS via self-signed certificates, Let's Encrypt, or custom certificates. HTTP will redirect to HTTPS. Non-custom certificates will automatically be kept up-to-date. See nextcloud.enable-https -h for more information. Note that it requires sudo.

This would also simplify it on all systems using snapd, which is recommended by CertBot.

Since its inception it has required little maintenance as well, which is a positive for the AdGuard Home project.

Having used the above suggestion from Nextcloud, I can say it works very well. I also think the same idea would work well with AdGuard Home.

**Comment by ameshkov** [comment]
It seems that `enable-https` is just a shortcut for running certbot.

I don't really understand what's wrong with AGH's current approach? Is it not possible to use a cert generated elsewhere?

**Comment by jslawler** [comment]
It is possible to use a cert generated elsewhere but it is still a hugely manual process that could be simplified, and even autonomous.

There is no way that I know of to generate a certificate on Ubuntu Core by itself, due to its containerised nature. The same applies to all other systems like this.
This means, 2 devices would be needed.

It's not an impossible task to add the cert, but it does make it a more manual process, which could be improved on for people who aren't as knowledgeable in these areas.
As solutions exist in the wild, I thought it might be a good addition for AdGuard Home.

**Comment by ameshkov** [comment]
> It is possible to use a cert generated elsewhere but it is still a hugely manual process that could be simplified, and even autonomous.

I agree, it's just there's already a different feature request for this kind of LE integration: #1603 

> There is no way that I know of to generate a certificate on Ubuntu Core by itself, due to its containerised nature. The same applies to all other systems like this.

Tbh, I thought that Ubuntu Core supports running non-snap binaries as well. Is it?
