### ISSUE TITLE
Multiple DNS servers

### ISSUE THREAD

**Issue by VwEl** [AdguardTeam/AdGuardHome#2895]
Multiple DNS servers can be set to monitor different ports to provide different resolution effects

**Comment by ameshkov** [comment]
Could you please provide an example of the functionality you're trying to achieve?
What difference between these two servers?

Could it be that the same functionality can be achieved by having different client configurations in AGH?

**Comment by VwEl** [comment]
> 
> 
> Could you please provide an example of the functionality you're trying to achieve?
> What difference between these two servers?
> 
> Could it be that the same functionality can be achieved by having different client configurations in AGH?

Like smart dns, multiple DNS servers can be configured. Different DNS can be configured with different settings, which can respond to different needs and provide more accurate DNS resolution for traffic distribution
![0](https://user-images.githubusercontent.com/28218636/113333735-63c09200-9355-11eb-9ac8-fc1c5176e356.png)
![1](https://user-images.githubusercontent.com/28218636/113333748-67ecaf80-9355-11eb-9eec-c510cc49e5a4.png)

**Comment by ameshkov** [comment]
We use "Clients" functionality for the same purpose.

Different clients may use different functionality or different upstream servers.

**Comment by VwEl** [comment]
> 
> 
> We use "Clients" functionality for the same purpose.
> 
> Different clients may use different functionality or different upstream servers.

Can add port binding ？Other service designated port 7913/7914

**Comment by ameshkov** [comment]
Hm, not really, and we have no plans to - it will overcomplicate things.

What's wrong with other ways of attributing a client?
