### ISSUE TITLE
"Download configuration file" for Apple doesn't use relative URLs

### ISSUE THREAD

**Issue by MattElekHarris** [AdguardTeam/AdGuardHome#2905]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home, version v0.105.2, channel release
* **How did you install AdGuard Home:**
  * OPNsense mimugmail community repository
* **How did you setup DNS configuration:**
  * Router DNS
* **If it's a router or IoT, please write device model:**
  * OPNsense router running on Asus netbook
* **CPU architecture:**
  * arch freebsd amd64
* **Operating system and version:**
  * FreeBSD 12.1-RELEASE-p15-HBSD amd64

AdGuard Home, version v0.105.2, channel release, arch freebsd amd64

### Expected Behavior
When using AdGuard Home behind a reverse proxy with a custom URL, like defined in the [docs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy), downloading an Apple DNS .mobileconfig file should use relative URLs like everything else already does.

### Actual Behavior
The download configuration button uses an absolute URL, for example https://192.168.1.1/apple/doh.mobileconfig?host=xyz, instead of using a relative URL, such as https://192.168.1.1/adguardhome/apple/doh.mobileconfig?host=xyz.

**Comment by ainar-g** [comment]
Should be fixed on the edge channel as of snapshot 23c9f528.  Can you please check if our solution fixes the issue for you?

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to reopen with more details if you think that something should be fixed.

**Comment by MattElekHarris** [comment]
Sorry for the delayed response. I installed the latest edge channel build, and the issue is now fixed! Thanks!
