### ISSUE TITLE
3764c1d - Pull request: dnsforward: fix nxdomain for internal aaaa reqs

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#2910]
I think this is still happening.. 

This is a Chromebook, and what it is doing has many names.. 

https://arstechnica.com/gadgets/2020/08/a-chrome-feature-is-creating-enormous-load-on-global-root-dns-servers/

My understanding; and I could be wrong, is this commit would help this.. 

![image](https://user-images.githubusercontent.com/55087301/113416984-773d1e80-9390-11eb-9e34-ec5eeda974a8.png)

Otherwise, my understanding is that it would help this:

![image](https://user-images.githubusercontent.com/55087301/113417295-16621600-9391-11eb-8a59-dc9aba95e904.png)

Which seems to still be happening as well.. 

Please let me know if I can help further..

**Comment by ainar-g** [comment]
I'm sorry, perhaps I'm missing some context, but what is the issue exactly?  Please fill out the actual issue form and describe both the expected behaviour and how the current behaviour is different from the desired.  Thanks!

**Comment by bcookatpcsd** [comment]
sorry for the confusion.. 

vlan10.dns is a private/internal tld

ppofmkbaaz is the chrome dns surveying which causes dozens of queries.. 

my understanding of 3764c1d was that it would stop sending those AAAA _and_ A requests upstream for resolution.. 

I may not have understood the purpose of 3764c1d, which is why I shared the two screenshots. 

Adugardhome _looks_ to have added vlan10.dns and passed it upstream, but recieved a REFUSED response

the private/internal domain vlan10.dns is being answered by 192.168.10.105:531.

so I was confused on the REFUSED response/rcode.. 


```
drill blahasdfasdf.vlan10.dns @192.168.10.105 -p 531 AAAA
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 41594
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; blahasdfasdf.vlan10.dns.	IN	AAAA
```


```
drill blahasdfasdf.vlan10.dns @192.168.10.200 -p 53 AAAA
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 47385
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; blahasdfasdf.vlan10.dns.	IN	AAAA
```


```
drill blahasdfasdf.vlan10.dns @192.168.10.200 -p 53 A
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 22429
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; blahasdfasdf.vlan10.dns.	IN	A
```

```
drill blahasdfasdf.vlan10.dns @192.168.10.105 -p 531 A
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 20534
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; blahasdfasdf.vlan10.dns.	IN	A


```

Thank you in advance.. 

I may be _totally_ wrong or confused.. 

it looks inconsistent at least..

**Comment by ainar-g** [comment]
It's clearer now, thanks.  The purpose of that commit was actually to restore the previous behaviour for clients who send both `A` and `AAAA` requests for domains, including autohost ones.  By “autohost” I mean the ones that end with `autohost_tld`, which is `lan` by default, which are called “internal” there, because they are devices within the user's private network.

I still don't see the full picture with regards to what exactly is the issue, unfortunately.  Is `192.168.10.200:53` the address of AdGuard Home?  Is the issue that it responds with `NOERROR` on `AAAA` queries, unlike the server on `192.168.10.105:531`?

**Comment by ainar-g** [comment]
It that fits your case, you can set `aaaa_disabled` to `true` in your configuration file.  That will make AGH respond with an empty answer to all `AAAA` queries.  You could also use the “Disallowed domains” input on the “DNS settings” page to make AGH drop any queries for things like TLD-only requests.  For example, a regular expression `/^[^.]+$/` will make AGH drop all requests that only contain TLDs.

Does any of these features work for you?
