### ISSUE TITLE
Can not query IPv6 upstream occasionally

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#2918]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.105.2
* **How did you install AdGuard Home:**
 Github releases
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
amd64 device
* **CPU architecture:**
AMD64
* **Operating system and version:**
OpenWrt19.07
### Expected Behavior

Query IPv6 upstream as before
### Actual Behavior

Cannot query IPv6 upsteam like IPv4
### Screenshots

<details><summary>Client Setting:</summary>

![image](https://user-images.githubusercontent.com/22477230/113526058-fded3800-95ea-11eb-8388-3835ea959411.png)
</details>

<details><summary>NextDNS log:</summary>

![image](https://user-images.githubusercontent.com/22477230/113526341-49ecac80-95ec-11eb-94b8-6e7bcdc68e01.png)
</details>

<details><summary>Query on OpenWrt ditectly:</summary>

![image](https://user-images.githubusercontent.com/22477230/113526272-0eea7900-95ec-11eb-94b2-1e0edd6b8f25.png)
</details>

<details><summary>listening addresses(contain IPv6 address):</summary>

![image](https://user-images.githubusercontent.com/22477230/113542305-90570100-9616-11eb-90e3-ddbbc6dba521.png)
</details>

### Additional Information

I want audit a device, so I specified extra IPv6 upstream from NextDNS to this device in April 1. And now I find NextDNS lack of recent log, so I check on AdGuardHome found it cannot query IPv6 upsteam for now, the first 2 days looks good, but today and yesterday totally cannot. I change client upstream setting only left IPv6, not work anymore. I also test query on OpenWrt directly via kdig and result looks good, so I don't know why AdGuardHome cannot query (even I restart AGH and reboot OpenWrt), I run AGH bin file from github release as init.d services on OpenWrt directly. 
Give `ip a` info for check:
```
9: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether a0:XX:XX:XX:XX:a0 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.1/24 brd 10.1.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet6 2408:XXXX:XXXX:62f0::1/60 scope global dynamic 
       valid_lft 257169sec preferred_lft 170769sec
    inet6 fd88::1/60 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::XXXX:XXXX:XXXX:34a0/64 scope link 
       valid_lft forever preferred_lft forever

16: pppoe-wan: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc fq_codel state UNKNOWN qlen 3
    link/ppp 
    inet 27.X.X.113 peer 27.X.X.1/32 scope global pppoe-wan
       valid_lft forever preferred_lft forever
    inet6 2408:XXXX:XXXX:XXXX:b040:6766:486f:98dc/64 scope global dynamic 
       valid_lft 258654sec preferred_lft 172254sec
    inet6 fe80::XXXX:XXXX:XXXX:98dc/10 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by ainar-g** [comment]
Hi, your configuration for the client seems to be wrong: in addresses with IPv6 the address must be in square brackets:

```
tls://[a:b:c::d]:853
```

Otherwise, the parser doesn't really know where the IPv6 address ends and where the port start.  Can you try adding the brackets and report if that fixes the issue?
