### ISSUE TITLE
Timestamp of Log entries is UTC, not local time

### ISSUE THREAD

**Issue by BaymaxAndHiro** [AdguardTeam/AdGuardHome#2919]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

The log entries are stamped in UTC time, that is, four hours ahead of my local time (Eastern); they should be timestamped to the local time.  I have uninstalled AdGuardHome, ensured the timezone is correct via raspi-config, rebooted, and reinstalled to no effect.  The local time of the Raspberry Pi server is correct.

* **Version of AdGuard Home server:**
  * v0.105.2
* **How did you install AdGuard Home:**
  * Built from Github release
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 Model B
* **CPU architecture:**
  * ARM v8
* **Operating system and version:**
  * Raspberry Pi 5.10.17-v7l+

### Expected Behavior
The log should display the results timestamped to the local time.

### Actual Behavior
The log timestamps are in UTC, that is, four hours ahead of my current timezone, Eastern.

### Screenshots
The current time the screen snapshot was taken was local time at 22:11:21 on 4-Apr-2021, but the timestamp for the log shows UTC time of 02:11:21 on 5-Apr-2021.
![Screenshot_2021-04-05 AdGuard Home](https://user-images.githubusercontent.com/49417695/113530289-265a3f80-95b5-11eb-942f-b5fa497c03f0.png)

**Comment by ainar-g** [comment]
If I recall correctly, the date is shown based on your browser's locale.  Which browser do you use?  Can you make sure that the time on the system which you use to access the admin interface has the correct timezone as well?

**Comment by BaymaxAndHiro** [comment]
Yeah, it's stupid Firefox.  I tried it in Brave and no problem.  So, please close this issue.
As for Firefox, no matter what I've done, it refuses to recognize local time for AdGuardHome.  I found an article that talked about this very issue and said to change "privacy.resist" in "about:config", and I disabled it to no avail.  I'll keep looking, but as I said, please close this as it's Firefox, not AdGuardHome.
