### ISSUE TITLE
[Feature request] Get the ability to read geoip/geosite data from other files

### ISSUE THREAD

**Issue by PussAzuki** [AdguardTeam/AdGuardHome#2925]
### Prerequisites

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed
- This request is associated with these requests #2446 #2445 **But** all can be used independently

### Problem Description

With the current functionality, it's still tricky to assign a large number of specific domains upstream, and it also requires additional files to store them, which makes it a bit annoying to make changes via the web side, so there should be a way to make it easier.

### Proposed Solution

If it can read geoip/geosite files [here](https://github.com/Loyalsoldier/v2ray-rules-dat/), it makes [/geosite:cn/geosite.dat:category-games@cn/]1.1.1.1 possible.
which should make it easier to write/update the rules 

If #2445 is implemented then operations like this will also be possible:
such as 223.5.5.5@geoip:cn is that the return data forwarded to the DNS upstream of 223.5.5.5 will be verified as belonging to China, thus reducing the contamination of its returned data with that returned by other dns upstream

I still think the fastest IP mode has a number of flaws

**Comment by WROIATE** [comment]
I'm interested in this issue. So how about the finally solution with set upstream domain filter?

**Comment by LasmGratel** [comment]
Why is this issue closed?

**Comment by Margele** [comment]
https://github.com/Margele/AdGuardHome-Geosite

@LasmGratel @WROIATE
