### ISSUE TITLE
DHCP options are erased when the configuration is updated via the HTTP API

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2927]
@mc9662 in https://github.com/AdguardTeam/AdGuardHome/issues/2842#issuecomment-813918013 has found an issue: any change in the DHCPv4 configuration made over HTTP API erases the DHCP options users set in the configuration file.  That obviously shouldn't happen.

**Comment by ainar-g** [comment]
Should be fixed on the edge channel as of snapshot 65553a29.  @mc9662, can you please check if our solution fixes the issue for you?

**Comment by mc9662** [comment]
Yep, looks good, I've tested the :edge docker image and can confirm my DHCPv4 -6 options in AdGuardHome.yaml were maintained after a change to the DHCPv4 settings via the web interface.  Expected changes via the settings in the web interface were made to AdGuardHome.yaml

Thank you for the swift fix - appreciated, Matt
