### ISSUE TITLE
Runtime clients' host are no longer shown in query logs

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2929]
See https://github.com/AdguardTeam/AdGuardHome/issues/2704#issuecomment-814884441.  This was probably broken on the backend side when we implemented richer query log information during #1273.  Going to fix ASAP.

**Comment by ainar-g** [comment]
@zadigre, hi, and thank you for your report.  We've pushed a fix that should once again show the names of the devices in your network in the query log.  Can you please update to the latest edge release and check if our solution fixes the issue for you?

**Comment by zadigre** [comment]
Fixed.
All fine now (only seeing the 5000ms timeout for non existing local PTR records… but I guess this is a different bug).
