### ISSUE TITLE
Clarify and fix static leases and autohosts with disabled DHCP servers

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2934]
1.  Configure and enable the DHCP server.

1.  Add a valid static lease, for example `myhost`.

1.  Make a DNS query for `myhost.lan` and get a successful response.

    So far so good.

1.  Disable the DHCP server **without** restarting AGH.

1.  Make a DNS query for `myhost.lan` and get a successful response.

    I'm not sure that this is intended.

1.  **Restart** AGH.

1.  Make a DNS query for `myhost.lan` and get an `NXDOMAIN`.

    I think this is intended, but this is inconsistent with the result from the request after disabling the DHCP server and before restarting AGH.

@ameshkov, I think that we should respond with `NXDOMAIN` on step 5 here.  What do you think?

**Comment by ameshkov** [comment]
Probably you're right, we should respond with NXDOMAIN
