### ISSUE TITLE
Admin interface (https secured) is to be accessible from only a particular network interface

### ISSUE THREAD

**Issue by DavidOsipov** [AdguardTeam/AdGuardHome#2935]
### Prerequisites

- [x]  I am running the latest beta version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

No way to attach a secured https admin interface to a particular network interface

_For example:_ 
I established a VPN connection to my server. I want my Adguard Home admin interface, which is using secure https connection, to be accessible only from the network interface my VPN in running on. I do not want my admin interface to be accessible for public, but at the same time, I want to use DoH on port 443, which would be accessible from all interfaces.

_Detailed example:_ 
If we have the following:
- Server's interface 1: **eth0**, IP: 1.1.1.1
- Server's interface 2 (local VPN interface): **wg10**, IP: 192.168.100.1

It would be great, if:

1. I would be able to connect to my Adguard home admin interface only via **wg10** using https port 443. 
2. DoH on port 443 should be accessible via interfaces **eth0** and **wg10**
3. Adguard home admin interface shouldn't be accessible through the interface **eth0** and IP 1.1.1.1

_Why connecting to Adguard admin interface via secure https connection through VPN interface wg10? Isn't it already secure, because you're connecting through your VPN?_

Because it's not comfortable connecting via http and struggling with my browser's multiple warnings.

**Comment by ainar-g** [comment]
Thanks for the report!  I am going to merge this into #2914, since this issue has the same solution as that one: the separation of the settings of the HTTP admin interface from the DoH settings.
