### ISSUE TITLE
AdGuard Home and Guest-SSID + DHCP = Issue!

### ISSUE THREAD

**Issue by Xophile** [AdguardTeam/AdGuardHome#2938]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.105.2
* **How did you install AdGuard Home:**
apt -get install from adguard repository

* **How did you setup DNS configuration:**
DHCP via AGH. DHCP disabled in router.

* **If it's a router or IoT, please write device model:**
rPi4
* **CPU architecture:**
rPi4
* **Operating system and version:**
Latest Raspbian

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

support@adguard.com asked me to go here and ask for help:

Hi!

Running AdGuard Home perfectly fine on my "own" network and DHCP is enabled in AGH due my ISP blocking DNS-changes in the router.

Now I want to setup Guest-SSID's for 2,4Ghz and 5Ghz. I guess that creates another IP-range which confuses Adguard Home's DHCP-server and I cannot get an IP-adress when I connect to the Guest-SSID's.

My "regular" network runs at 192.168.1.XX and I am not sure what range the Guest-Wifi will use. I have a Sagemcom F@st 5370e.

Is it possible to "combine" AdGuard Home and Guest-SSID's with different IP-range?

Any input would be greatly appreciated!

Thanks!

**Comment by ainar-g** [comment]
Hi, and thank you for the report.  Could you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and either post the logs of the failing attempt here as an attachment or send them to the support E-Mail?

Also, could you show or send your DHCP server configuration?

Thanks!

[Configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by zadigre** [comment]
your router probably has "isolate network" or something like that for guest ssid... which means devices connected to guest network will not be able to connect to anything on your local network, which includes your RPI/AdGuard Home. 

some router have a separate DHCP server for the guest network... but most consumers routers do not.
yours should have "allow local network access"... enable this and it should work.
