### ISSUE TITLE
Process DHCP hostnames with spaces

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2946]
[Context]:

> I may have found the cause of this problem...
> 48:e1:e9:24:94:26 192.168.25.18 Meross Smart Switch
> hostname has spaces between words. this is the default hostname (and not changeable) reported by the device with the dhcp request. adguard probably doesn't not like this space.
> […]

I *think* that the least-bad solution here is to just replace spaces with hyphens, but I'm not sure.  We could also just write an error to the log, but that' just poor usability.  We'll have to think about that a bit more.

[Context]: https://github.com/adguardTeam/adGuardHome/issues/2704#issuecomment-816942761

**Comment by zadigre** [comment]
I would be ok with hyphens... this is what I've see with some other dhcp servers.

**Comment by ainar-g** [comment]
@zadigre, the hyphen solution has been implemented in the latest edge builds.  Can you please check if your original case works now?

**Comment by zadigre** [comment]
@ainar-g,
I've deleted all the statics IP address for devices that were problematic... I waited a few hours until the devices renewed their IP address... I can confirm it's working fine now with the hyphens.

**Comment by ainar-g** [comment]
Thanks for the confirmation!  We'll close the issue now.  If you find any problems with that, please feel free to file a new one.
