### ISSUE TITLE
redline/graph missing for low blocked numbers

### ISSUE THREAD

**Issue by zadigre** [AdguardTeam/AdGuardHome#2950]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
edge channel v0.106.0-a.114+e671f43a
* **How did you install AdGuard Home:**
  * GitHub release
* **How did you setup DNS configuration:**
  * DHCP server from adguard
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 running latest 64 bits Raspberry OS
* **CPU architecture:**
  * ARM64
* **Operating system and version:**
  * Raspberry OS

### Expected Behavior
red line shown for the blocked graph

### Actual Behavior
red line shown only for spikes in the graph

### Screenshots
Screenshot:
![Capture d’écran, le 2021-04-12 à 15 38 23](https://user-images.githubusercontent.com/4810599/114452103-0f63b080-9ba6-11eb-8913-2380f82fb7ab.png)

**Comment by ainar-g** [comment]
Dup of #2942 or #2944?  (Which may or may not be dups of each other, now that I think about it.)

**Comment by zadigre** [comment]
> Dup of #2942 or #2944? (Which may or may not be dups of each other, now that I think about it.)

it looks like it... 
I didn't check these "optical issues" because wording didn't mean anything for me... 

I have the same problem on Safari in MacOS and iOS. And also Microsoft Edge on MacOS.

**Comment by ainar-g** [comment]
I've asked my colleagues to look at all those reports asap.  I'll close this one for now.
