### ISSUE TITLE
Ability to change server name for kubernetes.docker.internal 

### ISSUE THREAD

**Issue by depler** [AdguardTeam/AdGuardHome#2951]
For now, AdGuardHome identifies itself like **kubernetes.docker.internal** (at least windows version), despite that it has nothing to do with docker when running as standalone executable. Is there any way to change that name?

**Comment by depler** [comment]
![IMG_20210413_022049](https://user-images.githubusercontent.com/13541699/114474545-22569f00-9bff-11eb-9e43-76ac083bd41b.jpg)

**Comment by ameshkov** [comment]
What version of AdGuard are you using? It'd be better to try the latest edge build as PTR queries were reworked there.

**Comment by depler** [comment]
It's v0.105.2, don't really want to upgrade until release. Thanks anyway.
