### ISSUE TITLE
AdGuard Home doesn't boot automatically

### ISSUE THREAD

**Issue by Zelmanyr** [AdguardTeam/AdGuardHome#2953]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed  (I did and posted there but didn't know if I would be replied to in a closed issue)

### Issue Details

* **Version of AdGuard Home server:**
  * 0.105.2
* **How did you install AdGuard Home:**
  *  Github releases
* **How did you setup DNS configuration:**
  * It's a local dns server that I run on my own machine for this particular machine for now. I changed the dns server address in the settings. AdGuard Home works quite well, it just doesn't start automatically at boot.
* **If it's a router or IoT, please write device model:**
  * A Windows PC
* **CPU architecture:**
  * Intel Skylake 6500
* **Operating system and version:**
  * Windows 10 21H1

### Expected Behavior
AdGuard Home should boot automatically.

### Actual Behavior
It doesn't boot at all, even if I wait several minutes.

</details>

### Additional Information
I can launch AdGuard Home manually when I'm logged in a session but I would prefer it to start automatically at boot of course.

**Comment by Zelmanyr** [comment]
As I said here : https://github.com/AdguardTeam/AdGuardHome/issues/2263 I tried multiple things to launch AdGuardHome.exe at boot nothing worked, unfortunately...

**Comment by ameshkov** [comment]
First of all, have you installed AdGuard Home as a service? `AdGuardHome.exe -s install`?

**Comment by Zelmanyr** [comment]
Ah... My bad I apologize, it seems I didn't read carefully the very fist page of the wiki where this command line is. I tried it now and it works beautifully, sorry for wasting your time.
