### ISSUE TITLE
Is the result of npm/yarn build available as a tarball?

### ISSUE THREAD

**Issue by yurivict** [AdguardTeam/AdGuardHome#2958]
In order to build an ```AdGuardHome``` package we need to run the npm/yarn stem and package the result.

It would be a lot more convenient if you could distribute pre-built html tarballs, like the Authelia project distributes authelia-public_html.tar.gz here https://github.com/authelia/authelia/releases

All packaging systems would greatly benefit from this, since file downloads aren't allowed during package build and they have to build and store html tarballs themselves.

Thank you,
Yuri

**Comment by ameshkov** [comment]
@yurivict wouldn't it be easier to use a Docker image that contains everything?

We're building AGH in `adguard/golang-ubuntu` for that purpose: https://github.com/AdguardTeam/AdGuardHome/blob/master/bamboo-specs/release.yaml#L9

**Comment by yurivict** [comment]
Unfortunately Docker doesn't work on FreeBSD yet.

Also packages are fundamentally different way of installing software, and IMO both Docker and package should work.

**Comment by ainar-g** [comment]
Thanks for the suggestion.  We'll look into it, but not during this development cycle.

In the meantime, any reason why you don't want to just use the official FreeBSD binaries we provide?  (I'm assuming that the packaging systems in question are for FreeBSD?)

**Comment by yurivict** [comment]
> In the meantime, any reason why you don't want to just use the official FreeBSD binaries we provide?

FreeBSD ports have to build binaries from source when possible.

**Comment by ainar-g** [comment]
@yurivict, as of current `master`, you should be able to:

1.  Download the frontend files from [our server].

1.  Extract them into the project root on your machine.

1.  Call:
    ```sh
    make build-release SIGN=0 OS='freebsd' ARCH='amd64' BUILD_SNAP=0 FRONTEND_PREBUILT=1
    ```

1.  Get a working `AdGuardHome` in the `dist/` dir.

Can you please check that this works for you?

[our server]: https://static.adguard.com/adguardhome/edge/AdGuardHome_frontend.tar.gz

**Comment by ainar-g** [comment]
We'll close this issue for now.  Please feel free to open new ones if you have any issues with the functionality.
