### ISSUE TITLE
Custom Client Rules not Working

### ISSUE THREAD

**Issue by mariusberlinghof** [AdguardTeam/AdGuardHome#2962]
* **Version of AdGuard Home server:**
  * v0.105.2
* **How did you install AdGuard Home:**
  * On a Raspberry Pi 3 Model B , installed from the latest GitHub-release
* **How did you setup DNS configuration:**
  * Setup in the FritzBox router: default gateway for every client is the raspi 
* **If it's a router or IoT, please write device model:**
  *  Router: FritzBox 7490, V07.21
  * AdGuardHome Server: Raspberry Pi 3 Model B
* **CPU architecture:**
  * BCM2837 SoC with a 1.2 GHz 64-bit
* **Operating system and version:**
  * Debian 10.9

### Expected Behavior

A custom client filter rule should block the listed domain for this client. Nonetheless the requests are still passed after updating the rules.
Generic rules for every client (e.g. `||api.samsungcloud.com^$important`) are still working.

Custom Rules are:
```
||public-cdn.acc.indazn.com^$client='Monitor'
||connectivitycheck.gstatic.com^$client=10.0.0.5
||connectivitycheck.gstatic.com^$client='10.0.0.5'
||connectivitycheck.gstatic.com^$client='Soundbar'
||fcm.googleapis.com^$client=10.0.0.5
||www.googleapis.com^$client=10.0.0.5
```

### Actual Behavior
After adding a custom filter rule the requests from this device are still processed and not blocked. Generic filters are applied and work as planned.

### Screenshots

<details><summary>Screenshot:</summary>

#### working custom filter rule (all clients):
![image](https://user-images.githubusercontent.com/36261096/114867393-09174380-9df5-11eb-9123-6f3e13de9d6d.png)

#### not working custom filter rule (specific client):
![image](https://user-images.githubusercontent.com/36261096/114867504-32d06a80-9df5-11eb-9b53-4fa8c2394603.png)

#### custom filter list:
![image](https://user-images.githubusercontent.com/36261096/114867677-60b5af00-9df5-11eb-94dc-0c7e1aa298a9.png)

#### custom filter check (alls clients):
![image](https://user-images.githubusercontent.com/36261096/114867751-72975200-9df5-11eb-9e19-0721f57c412d.png)

</details>

**Comment by ameshkov** [comment]
Cannot reproduce on my side.

Could it be that these clients have custom settings and "Block domains using filters" is disabled?

**Comment by mariusberlinghof** [comment]
> Cannot reproduce on my side.
> 
> Could it be that these clients have custom settings and "Block domains using filters" is disabled?

Yeah, seems like I've had the client configured wrong. After apliying the global settings, it worked. Thanks!
