### ISSUE TITLE
Known DNS Providers wrong DNS for Applied Privacy DNS

### ISSUE THREAD

**Issue by citizen-17** [AdguardTeam/AdGuardHome#2979]
The settings for Applied Privacy DNS are outdated https://kb.adguard.com/en/general/dns-providers#applied-privacy-dns

DNS, IPv4 | 94.130.106.88 -> 146.255.56.98
DNS, IPv6: 2a01 | 4f8:c0c:83ed::1 -> 2a02:1b8:10:234::2
DNS-over-HTTPS | https://doh.applied-privacy.net/dns-query -> https://doh.applied-privacy.net/query
DNS-over-TLS | tls://dot1.applied-privacy.net -> no changes

**Comment by Aikatsui** [comment]
@citizen-17 You can update it. Fork https://github.com/AdguardTeam/AdguardKnowledgeBase then edit https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/01.general/17.dns-providers/docs.en.md and make pull request.
