### ISSUE TITLE
$dnsrewrite appends answer twice

### ISSUE THREAD

**Issue by EugeneOne1** [AdguardTeam/AdGuardHome#2981]
Adding a custom filtering rewrite rule for some PTRs makes _AGH_ respond with a duplicated address.

For example, adding a rule:
```
||168.192.168.192.in-addr.arpa^$dnsrewrite=noerror;ptr;abc.com
```
Makes answer's section look like this:
```
;; ANSWER SECTION:
168.192.168.192.in-addr.arpa. 10 IN	PTR	abc.com.
168.192.168.192.in-addr.arpa. 10 IN	PTR	abc.com.
```

At the same time, adding rule:
```
||4.3.2.1.in-addr.arpa^$dnsrewrite=noerror;ptr;henlo.com
```
Makes answer's section proper again:
```
;; ANSWER SECTION:
4.3.2.1.in-addr.arpa.	10	IN	PTR	henlo.com.
```

**Comment by ameshkov** [comment]
We'd better handle this in v0.106.0 since this is a bug in the functionality we've added rather recently.

**Comment by EugeneOne1** [comment]
@ameshkov, I'm not really sure if this caused by newly added feature, since we've found some weird code in rewriting logic, which may be related.  Needs investigation anyway.
