### ISSUE TITLE
Run install.sh with existing install zip

### ISSUE THREAD

**Issue by thedannywahl** [AdguardTeam/AdGuardHome#2989]
install.sh exits on error if it cannot successfully download the package via curl.  I suggest that it should check for the file first before attempting to download it.

https://github.com/AdguardTeam/AdGuardHome/blob/55cd4ae2546971f762713e6af16c1bbfcff8b1bb/scripts/install.sh#L229

```shell
if [ ! -f "${PKG_NAME}" ]; then
  download "${URL}" "${PKG_NAME}" || error_exit "Cannot download the package"
fi
```
Use case: I was migrating my DNS server from Pi-hole to AdGuard and downloaded `install.sh` before uninstalling pihole and when running the install script (after uninstall pihole) it errored as the system did not have DNS resolvers configured.  I was able to manually download the install zip using the `curl --dns-server` option (`curl --resolve` could also  work).

After the zip was downloaded install.sh still failed as it doesn't check for the existence of the installer zip before attempting to download it.  By wrapping in a conditional check the installer is able to run in an "offline" manner and complete installation and setup.

If there is a desire for this I can create PR.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2462
