### ISSUE TITLE
Inspect `InitTLSCiphers` function

### ISSUE THREAD

**Issue by EugeneOne1** [AdguardTeam/AdGuardHome#2993]
The file `internal/home/tls.go` contains some unclear logic in the following function:
https://github.com/AdguardTeam/AdGuardHome/blob/2d87a0458ef0425629e9f11dbb382e2ec0089ad0/internal/home/tls.go#L602-L604
Initially, the function was added during #1384 into the `util` package which has already been removed.

The documentation for it prompts to follow the `crypto/tls/common.go` to find `initDefaultCipherSuites` function, the implementation of which is suspiciously similar.  Perhaps, there is a way to use its results directly.

**Comment by ainar-g** [comment]
Go 1.17 ignores the order of the cipher suites, so we can probably greatly simplify it in v0.108.
