### ISSUE TITLE
Add YouTube Kids to "block specific services"

### ISSUE THREAD

**Issue by c1xx** [AdguardTeam/AdGuardHome#2995]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
When I block YouTube, YouTube Kids is also blocked.

### Proposed Solution
Create a separated "specific service" for YouTube Kids

### Alternatives Considered
-

### Additional Information
-

**Comment by ainar-g** [comment]
Merged into #2604.  Thanks!
