### ISSUE TITLE
CAA and HPKP records generation

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#2997]
Hello,

please, consider to add CAA and HPKP records generation. It may be worth adding TLSA, CERT, HTTPS, SVCB etc. to this section as well.

You may also be able to combine this request with this one:
https://github.com/AdguardTeam/AdGuardHome/issues/1862

Thank you.
Cheers😜

**Comment by ameshkov** [comment]
HPKP is dead.
CAA -- I am not sure what it is

**Comment by ammnt** [comment]
> CAA -- I am not sure what it is.

DNS Certification Authority Authorization. "CAA records allow domain owners to declare which certificate authorities are allowed to issue a certificate for a domain.". P.S.: I'm talking about setting up the server itself to improve his security level. Not dnsrewrite function😅

**Comment by ameshkov** [comment]
I am not entirely sure what we can do with this CAA record on AdGuard Home side, it's up to you to set it up for your server.

**Comment by BirdInFire** [comment]
> I am not entirely sure what we can do with this CAA record on AdGuard Home side, it's up to you to set it up for your domain name.

Maybe since it's generated a less tech guy have just to copy it in his hosting domaine provider (like Apple do for their news custom domain support).

**Comment by ameshkov** [comment]
Still I don't fully understand who needs that. CAA records aren't used in the process of certificates validation:

RFC 6844: 
> Relying Applications MUST NOT use CAA records as part of certificate validation

It'd probably be better to close this feature request since there's nothing we can do.

**Comment by sliterok** [comment]
@ameshkov could you please investigate the behaviour in the mentioned issue? I'm using AdGuardHome as NS and it would be really great to have CAA and TXT records so it could be used with letsencrypt to make SSL certificates.

**Comment by ameshkov** [comment]
> I'm using AdGuardHome as NS

Huh, tbh, this is not what we kept in mind when developing AdGuard Home.

@sliterok for TXT you definitely can use `$dnsrewrite`:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by sliterok** [comment]
> @sliterok for TXT you definitely can use `$dnsrewrite`: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

Oh thank you that definitely works out!
