### ISSUE TITLE
Locks up HomeAssistant

### ISSUE THREAD

**Issue by bwt615** [AdguardTeam/AdGuardHome#3002]
About every 24 hours now since installing AdGuard on my home assistant pick have to reboot. Checking the logs prior, I have:

Can't update connectivity information: Error: Timeout was reached

spammed in the log. Assume it is AdGuard as uninstalling fixed the problem.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.
