### ISSUE TITLE
add edit option to dns rewrite section

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#3007]
Hello can you please add some edit option to dns rewrite section? 
like a pencil
![Screenshot_20210425-202559](https://user-images.githubusercontent.com/56163305/116004878-0b537c00-a605-11eb-89c3-851e4fb9b2bd.png)

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/1577
