### ISSUE TITLE
add statistic for list use/requests

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#3009]
Hello, please add some statistic where user can see what lists are the most used.

An bar or pie chart would be great where we can see what lists are mainly used, as its highly dependent of individual browsing behaviour what lists are neccesary or contains the right rules.

In that way the user can see what list have an benefit and rarely or unused lists can be removed to keep the system light and fast (raspberry pi for example).

Hope you consider it, thanks

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/580
