### ISSUE TITLE
Make it possible to disable certain client sources

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#3020]
Make it possible to disable certain client sources

Clients might want to disable some of our client information enriching functionality, like WHOIS and `arp`, for various reasons.  [Here] is one example with `arp`, and I'm pretty sure I remember somebody wanting to disable either rDNS or WHOIS.  And in fact, we already have a separate boolean for `/etc/hosts` parsing.

It could be a setting in a new separate block, like:

```yaml
'clients':
  'disabled_sources':
  - 'rdns'
```

@ameshkov, what do you think?

[Here]: https://github.com/AdguardTeam/AdGuardHome/issues/2943#issuecomment-828164108

**Comment by ammnt** [comment]
Yes! Please add the WHOIS and ARP Request Disable features. Good idea😘

**Comment by ameshkov** [comment]
Yeah, good idea

**Comment by alexdelprete** [comment]
Was this implemented? I was looking for a way to disable importing /etc/hosts in the config. Didn't find it in the UI. Thanks.
