### ISSUE TITLE
The last update made the service not work on the Raspberry Pi

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardHome#3021]
The last update made the service not work on the Raspberry Pi

![Captura de tela 2021-04-28 142300](https://user-images.githubusercontent.com/16819380/116446367-4637f880-a82d-11eb-9098-f9caf92f9973.png)
![image](https://user-images.githubusercontent.com/16819380/116446446-57810500-a82d-11eb-99cb-970e5f91f373.png)

**Comment by ainar-g** [comment]
Hi, we can't reproduce that.  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment?  Thanks.

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by eduardoaddad** [comment]
Clean install fails
(I can't run the service)
