### ISSUE TITLE
Error configuring in the new version

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardHome#3023]
Error: control/install/configure | dnsServer.Prepare: setting up resolvers: systemResolvers: lookup test1619633852636749211.org on [fe80::96ea:eaff:fe25:bdf%eth0]:53: parsing "fe80::96ea:eaff:fe25:bdf%eth0": the passed string is not a valid IP address | 500

In the configuration of the previous version, there was no problem in the configuration of the AdGuard Home.

![image](https://user-images.githubusercontent.com/16819380/116453709-9450fa00-a835-11eb-9cbd-43040fc04a61.png)

**Comment by ainar-g** [comment]
Dup of #3022?

**Comment by eduardoaddad** [comment]
bind_host: 0.0.0.0
bind_port: 80
beta_bind_port: 0
users:
- name: ""
  password: ""
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 0.0.0.0
  port: 53
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 90
  querylog_size_memory: 1000
  anonymize_client_ip: true
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - https://dns10.quad9.net/dns-query
  - https://dns.google/dns-query
  - https://dns.cloudflare.com/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: true
  max_goroutines: 50
  ipset: []
  filtering_enabled: false
  filters_update_interval: 1
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: true
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites:
  - domain: jogar.wiki
    answer: addns.ddns.net
  blocked_services: []
  local_domain_name: lan
  resolve_clients: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name:  ""
  force_https: true
  port_https: 445
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters: 
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
- enabled: false
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 2
- enabled: false
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
- name: Eduardo
  tags: []
  ids:
  - eduardo
  use_global_settings: false
  filtering_enabled: true
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: true
  use_global_blocked_services: true
  blocked_services: []
  upstreams:
  - quic://dns-unfiltered.adguard.com:784
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 10

**Comment by eduardoaddad** [comment]
> Dup of #3022?

I'm not sure if it's the same bug.

**Comment by ainar-g** [comment]
Judging by the fact that the error messages are almost identical, I still think that this is a duplicate.  I will close this issue as duplicate, as we've pushed the fix to the `edge` channel.  Thanks for the thorough report!

**Comment by eduardoaddad** [comment]
@ainar-g the error continues in version v0.106.1

**Comment by ainar-g** [comment]
@eduardoaddad, are you sure that it's the same error?  That error should not appear on v0.106.1 any more.  Could you attach a new screenshot?
