### ISSUE TITLE
All DNS Request  Fail (when protection is enabled) after upgrading to v0.106.0

### ISSUE THREAD

**Issue by Ncage1974** [AdguardTeam/AdGuardHome#3029]
### Issue Details
I'm running the snap package of adguard home. As soon as my system automatically upgraded to Version: 
v0.106.0 i could no longer resolve dns request (when protection was enabled). Took me a couple hours to figure this out. 

* **Version of AdGuard Home server:**
   * v0.106.0
* **How did you install AdGuard Home:**
  * Snapcraft
* **How did you setup DNS configuration:**
  * i'm not sure exactly what you looking for here but upstream dns servers are:
  * https://9.9.9.9/dns-query
  * https://149.112.112.112/dns-query
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  *  AMD64
* **Operating system and version:**
  * Ubuntu Server 20.04.2 LTS

### Expected Behavior

 DNS Queries to be resolved when protection is enabled.

### Actual Behavior

DNS Queries are not resolved when protection is enabled.

### Screenshots

<details><summary>Screenshot:</summary>

Here is what happens when protection is enabled:  
![image](https://user-images.githubusercontent.com/1213549/116492259-700b1280-a861-11eb-8723-a7c5c0808752.png)

I've checked the query log and i don't see anything being blockrd

Here is what happens when protection is disabled:  

![image](https://user-images.githubusercontent.com/1213549/116492292-86b16980-a861-11eb-9aa8-7826106f0179.png)

</details>

**Comment by Ncage1974** [comment]
I'm closing the issue. I uninstalled adguard-home and reinstalled it. That fixed my issue. Why i have no idea. I. had run adguard for months (probably over a year actually) and just starting having issue after the upgrade (snaps upgrade automatically) and setup my setting identically to what they where before and now its working fine *shrug*.

**Comment by Ncage1974** [comment]
I'm reopening the issue back up. I just couldn't let it go. I found the specific settings that was causing the issue (i didn't have to disable protection):
![image](https://user-images.githubusercontent.com/1213549/116499405-b5cfd700-a871-11eb-9621-2120e81ca427.png)

If that is "Enabled" it causes the issue. Every dns query after its enabled will fail (well at least it did for me.).

**Comment by ameshkov** [comment]
Can you please tell me what response do you get if visit `https://dns.adguard.com/info.txt`

**Comment by ainar-g** [comment]
There haven't been any significant changes to that functionality.  Could you please attach [verbose logs] of failing requests?  Thanks.

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Ncage1974** [comment]
@ainar-g @ameshkov the service must have been down last night. I reenabled it this morning and everything is good. I'm going to close the issue again. Thanks...
