### ISSUE TITLE
v.106.0 Private DNS should support Dot, DoH and co.

### ISSUE THREAD

**Issue by benbrummer** [AdguardTeam/AdGuardHome#3031]
Currently i configured local name resolution in the "Upstream DNS servers"
`# Local network
[/168.192.in-addr.arpa/]tls://dns.lan.domain.com
[/lan.domain.com/]tls://pfsense.lan.domain.com`

With the separate configuration for "Private DNS servers" it is not possible to use it there. It looks like just IP-Adresses are allowed.

I'm not sure if the section for "Private DNS servers" should replace this configuration at all. But in the current way it is somewhat confusing. And with lets-encrypt being available in local networks nowadays it should be possible to use encryption everywhere.

**Comment by ainar-g** [comment]
Hi, the Private DNS servers setting should already accept DoT and DoH URLs.  Could you please add the following information:

1.  What entries exactly do you put into that field?
2.  The [verbose logs] of the request you're sending.

Thanks!

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by benbrummer** [comment]
This was a error on my side:

1. The certificate on pfsense.lan.domain.com was invalid
2.  I had to modify the Bootstrap DNS servers
Option 1: Add pfsense to DNS rewrites in AdGuard and afterwards ad 127.0.0.1 to Bootstrap DNS servers
Option 2: Add pfsense ip to Bootstrap DNS servers

Everything works now. Next time i will check the logs in advance. Thanks for the great tool :-)

**Comment by ainar-g** [comment]
Thanks for investigating!
