### ISSUE TITLE
Snapcraft install: cannot find required base "core20"

### ISSUE THREAD

**Issue by BigBobDalton** [AdguardTeam/AdGuardHome#3035]
Version 1.06 fails six ways to Sunday on RaspberryPi.

Manual install fails with

[fatal] dnsServer.Prepare: setting up resolvers: systemResolvers: lookup test1619705025005935946.org on Et

Snap install fails with

- Mount snap "adguard-home" (2253) (cannot find required base "core20")

Thankfully I backed up my Raspberry before I attempted the installation otherwise nothing would be working

Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Thanks for the report.  The first one is a duplicate of #3022.  The fix is already rolled out on the `edge` channel and will be released with v0.106.1 in the next few days.

The Snap one is a bit weirder.  We will investigate.

**Comment by BigBobDalton** [comment]
Hi,
This has been resolved since 2021. Thank you.
