### ISSUE TITLE
Serveurs DNS upstream

### ISSUE THREAD

**Issue by muxflash** [AdguardTeam/AdGuardHome#3040]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.0
* **How did you install AdGuard Home:**
  * update from link on the page
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **CPU architecture:**
  * 
### Expected Behavior
I choose my AD/DNS Server : 192.168.1.10 as Serveurs DNS upstream
For each request ADGuard must forward request to my DNS Server 192.168.1.10

### Actual Behavior
I can't do GPUPDATE or load GPO, It seems don't tranfer request to 192.168.1.10

### Screenshots

<details><summary>Screenshot: Upstream</summary>

![image](https://user-images.githubusercontent.com/58588833/116673279-7dc8b100-a9a3-11eb-82d5-e6b0db5b584a.png)

</details>

### Additional Information

I have the problem after my last adguard home update

**Comment by ainar-g** [comment]
Hi, what exactly is `192.168.1.10` in your network?  Is that the address of the machine on which AdGuard Home is running or your network's router?

**Comment by ainar-g** [comment]
No further updates from the OP, closing.
