### ISSUE TITLE
Client ranking does not show the source, such as WiFi or LTE

### ISSUE THREAD

**Issue by VwEl** [AdguardTeam/AdGuardHome#3041]
Client ranking does not show the source, such as WiFi or LTE.

This function has been disabled?

**Comment by ameshkov** [comment]
Could you please explain what you mean?

**Comment by VwEl** [comment]
> 
> 
> Could you please explain what you mean?

Previously there will be similar from mobile devices and regions
![20210501140858](https://user-images.githubusercontent.com/28218636/116773274-28fe6680-aa87-11eb-92ee-172d0d8fdd7f.png)
![20210501141310](https://user-images.githubusercontent.com/28218636/116773352-8db9c100-aa87-11eb-83e1-7acd6111ab36.png)
![20210501141444](https://user-images.githubusercontent.com/28218636/116773353-914d4800-aa87-11eb-997f-7ed72e19f2b5.png)

**Comment by ameshkov** [comment]
Hm, I cannot reproduce this issue.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.
