### ISSUE TITLE
Static DHCP leases

### ISSUE THREAD

**Issue by Radistx100** [AdguardTeam/AdGuardHome#3042]
Settings DHCP
After the update, more than half of the static MAC address table disappeared, out of 20 devices, 7 remained.
Latest version, OS - debian 10.

**Comment by ainar-g** [comment]
Hello.  This sounds like a duplicate of 3027, which should be mostly fixed in v0.106.1.  If it's not, please fill the whole issue template to help us diagnose the issue.

**Comment by Radistx100** [comment]
the malfunction appeared in version v0.106.0, previously the list was complete, I will try to enter all the addresses and see

**Comment by ainar-g** [comment]
No further updates, so closing.
