### ISSUE TITLE
Safe search blocks the entire google app on android

### ISSUE THREAD

**Issue by Ashwin-droid** [AdguardTeam/AdGuardHome#3043]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v 0.106.0
* **How did you install AdGuard Home:**
  * one command install on your readme file
* **How did you setup DNS configuration:**
  * DHCP but at a Router level
* **If it's a router or IoT, please write device model:**
  * Router : TLW840N IOT: Raspberry pi zero w
* **CPU architecture:**
  * ARMV6
* **Operating system and version:**
  * Raspberrian os

### Expected Behavior
Safe search should block the trackers and let the use of the search engine

### Actual Behavior
On windows 10 it works like a charm but on the google app on android it dosen't work and blocks the whole app

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20210430-195206_Google.jpg](https://user-images.githubusercontent.com/58349846/116708714-9a89d680-a9ed-11eb-8099-0fa745dd97a6.jpg)

![Screenshot_20210430-195306_Adblock Browser.jpg](https://user-images.githubusercontent.com/58349846/116708831-b7bea500-a9ed-11eb-9bb2-7f5059a0fdaa.jpg)

</details>

### Additional Information
I followed [this](https://pimylifeup.com/raspberry-pi-adguard-home/) guide

**Comment by ainar-g** [comment]
Hi, and thank you for the report.  Just to make sure I understand you correctly, you are using AGH as the DHCP server of your network, right?  And the Windows 10 machine in this network works fine, but an Android machine has issues with the Google app, is that correct?

**Comment by Ashwin-droid** [comment]
Yes, confirm that 

Than you for your quick response

**Comment by ainar-g** [comment]
I see, thanks.  We'll try to reproduce and fix the issue.

**Comment by ameshkov** [comment]
Might be a Google's issue tbh. We just follow their instruction.

Alternatively, try disabling Safe Search and add this rule to your custom filtering rules:
`||google.com^$dnsrewrite=forcesafesearch.google.com`

It does pretty much the same but in a more controlled way.

**Comment by Ashwin-droid** [comment]
With today's AGH (V 0.106.1) upgrade it was fixed. Thanks for your time and effort
