### ISSUE TITLE
Log search does not work

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#3048]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.106.1
* **Operating system and version:**
  *  Windows 10

### Additional Information

При поиске не полного имени домена который был запрошен несколько часов назад журнал зависает то есть крутится колесико загрузки бесконечно и еще при этом дает нагрузку на ЦП но если отменить поиск нажать на [x] то журнал в браузере начинает мигать то есть как будто бесконечно обновление идет..
Проверял на Google Chrome и Mozilla Firefox.
В версии 0.105.2 журнал работает нормально на всех браузерах.

**Comment by ainar-g** [comment]
Добрый день.  Скажите, какое значение стоит в настройке «Сохранение журнала запросов» в «Основных настройках»?  Мы не можем воспроизвести такую ситуацию, но возможно дело в размере логов?

**Comment by Eyeborgs** [comment]
@ainar-g 24 часа, "Анонимизировать IP-адрес клиента" не включено 
если не сможете воспроизвести я могу попробовать записать видео.

**Comment by ainar-g** [comment]
Не думаю, что _Adguard_ для _Windows_ здесь виноват, так как связи между ним и _AdGuard Home_ почти нет.  Есть вероятность, что нынешний лог попросту плохо оптимизирован под особенности работы файловых систем на _Windows_.  Можете включить на _AdGuard Home_ режим [подробных логов] и либо прикрепить лог поиска ± пару минут сюда, либо прислать нам на devteam@adguard.com с пометкой «_AdGuardHome Issue 3048_» в теме.

Насчёт проблем с _Adguard_ для _Windows_ можете написать туда же отдельным письмом, тоже желательно приложив логи.

Спасибо.

[подробных логов]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Eyeborgs** [comment]
Так же я заметил что если AGH 0.106.1 работает долго ну несколько дней без перерыва то интернет начинает работать очень медленно но после перезагрузки службы AGH в Windows интернет опять начинает работать нормально..

**Comment by Eyeborgs** [comment]
> Не думаю, что _Adguard_ для _Windows_ здесь виноват, так как связи между ним и _AdGuard Home_ почти нет. Есть вероятность, что нынешний лог попросту плохо оптимизирован под особенности работы файловых систем на _Windows_. Можете включить на _AdGuard Home_ режим [подробных логов](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) и либо прикрепить лог поиска ± пару минут сюда, либо прислать нам на [devteam@adguard.com](mailto:devteam@adguard.com) с пометкой «_AdGuardHome Issue 3048_» в теме.
> 
> Спасибо.

хорошо, ожидайте 
я вам напишу как пришлю логи через Email

**Comment by Eyeborgs** [comment]
@ainar-g отправил лог через Email

**Comment by ainar-g** [comment]
Спасибо, логи получили.  На первый взгляд, лог отрабатывает быстро.  Но есть теория, что большое количество фильтров могут быть причастны.  Скажите:

1.  Вы обращаетесь к _AGH_ через какой-то домен?  Сохраняется ли проблема с медленным логом, если обращаться к веб-интерфейсу _AGH_ напрямую через _IP_-адрес?
1.  Если вы отключите все фильтры в «Чёрных списках _DNS_», лог начинает отвечать быстрее?

**Comment by Eyeborgs** [comment]
@ainar-g 
1. да я сделал перезапись на вымышленный домен "dns.local" который берет IP AGH, нас счет быстроты через домен или напрямую через IP я тогда заметил что одинаково все идет.. но эта было после нескольких дней работы - сейчас после как я вам записал логи я перезапускал службу и по этому он работает быстро и я не могу в данный момент воспроизвести данную проблему - надо думаю подождать...
2. не могу проверить - надо подождать несколько дней..

**Comment by Eyeborgs** [comment]
Не знаю почему но я больше не могу воспроизвести эту проблему с журналом.. Я закрываю запрос.

**Comment by Eyeborgs** [comment]
@ainar-g обновил до версии v0.106.3 после полностью очистил все логи в "Настройка журнала" и в "Конфигурация статистики" после в Google Chrome открыл "Посмотреть код" и через него сделал "Очистка кеша и жесткая перезагрузка" и после этого Журнал работает нормально но если этого не сделать он зависает после обновления при поиске..

**Comment by ainar-g** [comment]
@Eyeborgs, на всякий случай уточню ещё раз: это всё ещё воспроизводится как в *Google Chrome*, так и в *Mozilla Firefox*?  И ещё, вы не пробовали с других ОС?  Возможно, в браузерах есть какие-то расширения, которые так влияют на страницу лога?

**Comment by Eyeborgs** [comment]
@ainar-g, Я постараюсь но чуть позже все проверить -  другой ОС у меня нету - проверю на своем компьютере через имеющихся браузера то есть: Google Chrome, Mozilla Firefox, Microsoft Edge и по возможности на IE 

Так же я сделаю видео если будут баги и сюда выложу ссылку на него.

Но сейчас я не могу проверить связи с тем что я далеко от оборудования нахожусь..
