### ISSUE TITLE
learning  $dnstype modifier

### ISSUE THREAD

**Issue by gentlyxu** [AdguardTeam/AdGuardHome#3051]
### Issue Details

* **Version of AdGuard Home server:** 
  * v0.106.1
* **How did you install AdGuard Home:** 
  *  Github releases
* **How did you setup DNS configuration:** 
  * Router
* **If it's a router or IoT, please write device model:** 
  * Raspberry Pi 4
* **CPU architecture:** 
  * ARM
* **Operating system and version:** 
  * Linux raspberrypi 5.4.51-v7l+

### Expected Behavior

Do not block the domain "www.iconfont.cn"

### Actual Behavior

blocked

### Screenshots

<details><summary>Screenshot:</summary>

<img width="910" alt="blocked1" src="https://user-images.githubusercontent.com/1243610/116769654-38be8080-aa70-11eb-920a-02e5b8959105.png">

</details>

### Additional Information

The old rule I use are:
```
/^(\S+\.)?advert/
```
I want to block all domain names with 'advert' in keywords. Someone reported to me that the domain "www.iconfont.cn" was mishandled -- https://github.com/privacy-protection-tools/anti-AD/issues/410 

So I updated the rule as follow:

```
/^(\S+\.)?advert/$dnstype=~CNAME,important
```
I want adgh to exclude CNAME queries, But it is not working now, CNAME query is still blocked(see the screenshot)

So how can I solve the problem?

**Comment by banbendalao** [comment]
When I use `/^(\S+\.)?advert/$dnstype=CNAME`, `www.iconfont.cn` will not be blocked. This may be a BUG
