### ISSUE TITLE
Support Windows on arm64

### ISSUE THREAD

**Issue by pb5050** [AdguardTeam/AdGuardHome#3057]
arm64 for the surface pro x please =D

**Comment by ainar-g** [comment]
Just as a reminder, the support for Windows on arm64 is only coming in Go 1.17, which will probably be released around August or September of 2021.

**Comment by pb5050** [comment]
any upodate?

**Comment by ainar-g** [comment]
The milestone is already set.  As it says in the [changelog], we'll remove Go 1.16 support in the v0.108 cycle, which hasn't begun yet.  v0.108.0-b.1 will probably be the first release to include experimental support for that platform.

[changelog]: https://github.com/AdguardTeam/AdGuardHome/blob/550b1798a169d07139f8f079bc5c83271a181f7f/CHANGELOG.md#deprecated

**Comment by ainar-g** [comment]
@pb5050, we're now pushing 64-bit ARM builds for Windows to the `edge` channel.  Can you please check if the build works for you?

https://static.adguard.com/adguardhome/edge/AdGuardHome_windows_arm64.zip

**Comment by pb5050** [comment]
checking out

**Comment by pb5050** [comment]
well im home now but its just 
saaying this

runtime: signal received on thread not created by Go.

**Comment by ainar-g** [comment]
@pb5050, I see, thanks for checking it!  Could you please provide the following information:

1.  Can you please attach the whole error message text here?  There is usually a backtrace as well.

2.  Can you show us, how run it?  Did you run it under an admin account?  Did you install it as a service?  A sequence of commands would be perfect.

**Comment by pb5050** [comment]
givve me a little bit im sorry things got hectic and i have had no ttime to even  get on the coputer  i just re installed  windows too it may help! how would u like me to run this 

> @pb5050, I see, thanks for checking it! Could you please provide the following information:
> 
>     1. Can you please attach the whole error message text here?  There is usually a backtrace as well.
> 
>     2. Can you show us, how run it?  Did you run it under an admin account?  Did you install it as a service?  A sequence of commands would be perfect.

**Comment by pb5050** [comment]
bingo its working iand all seems great

**Comment by ainar-g** [comment]
Thanks for testing!
