### ISSUE TITLE
Raspberry Pi: IP address IPv6 in eth0

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardHome#3059]
When using wireless connection there is no problem although activating the cable network is in error

Tested in the last 3 versions (v0.106.1, v0.106.0 and v0.105.2)

`Error: control/install/configure | dnsServer.Prepare: setting up resolvers: systemResolvers: lookup test1620004111819677533.org on [fe80::96ea:eaff:fe25:bdf%eth0]:53: parsing "fe80::96ea:eaff:fe25:bdf%eth0": the passed string is not a valid IP address | 500`

**Comment by ainar-g** [comment]
Hello again.  I've already responded somewhere else, but this error should not appear any more.  Can you please provide the full verbose log as an attachment?  Thanks.

**Comment by darkman1983** [comment]
For me it seems to be the same problem as i posted before as duplicate and it is fixed with 0.106.1 !
