### ISSUE TITLE
Raspberry Pi: Permission error in network configuration

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardHome#3060]
When configuring static IP through the AdGuard configurator, there is a permission error

![image](https://user-images.githubusercontent.com/16819380/116834289-ba5aff00-ab93-11eb-9780-04b2b93c4d85.png)

**Comment by ainar-g** [comment]
Please fill the full issue template, as this will allow us to better diagnose the issue.  In particular, we need to know how you installed AGH and how you're starting it.
