### ISSUE TITLE
DNS on adguard

### ISSUE THREAD

**Issue by JMDLama** [AdguardTeam/AdGuardHome#3061]
In log file adguard is searching for : as exemple : many times : 
"**SafeBrowsing: failed: couldn't do a GET request to 'https://dns-family.adguard.com:443/dns-query', cause: Get "https://dns-family.adguard.com:443/dns-query?dns=_zYBAAABAAAAAAAABDE5MTMCc2IDZG5zB2FkZ3VhcmQDY29tAAAQAAE": context deadline exceeded (Client.Timeout exceeded while awaiting headers)**" 

There is port configuration https already assign to 443. However this port is already used for let's encrypt on my NAS. 
How can I change it ? 
Thank you

**Comment by ainar-g** [comment]
Hello.  It seems like the machine can't reach our safe-browsing provider.  Does the issue still persist?  If so, are you sure that `dns-family.adguard.com` is not blocked by a firewall or something like that?  Thanks.

**Comment by JMDLama** [comment]
Yes the problem still persist, and there is no filter in my firewall
Thanks
*Jean-Marie * DANIEL LAMAZIÈRE


Le mer. 5 mai 2021 à 13:19, Ainar Garipov ***@***.***> a
écrit :

**Comment by JMDLama** [comment]
Yes the problem still persist, and there is no filter in my firewall
As exemple, the system is saying that it is nos in plain text : [info]
Couldn't fetch filter from url https://dns-family.adguard.com: data is
HTML, not plain text
Thanks
*Jean-Marie * DANIEL LAMAZIÈRE


Le mer. 5 mai 2021 à 13:19, Ainar Garipov ***@***.***> a
écrit :

**Comment by ameshkov** [comment]
Probably, the connection to AdGuard DNS is not ideal from your place.

I'd suggest simply disabling "Use AdGuard browsing security" service in AdGuard Home settings.
