### ISSUE TITLE
Auto updating query log

### ISSUE THREAD

**Issue by Ashwin-droid** [AdguardTeam/AdGuardHome#3066]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

There is no problem just finishing touch 

### Proposed Solution

Auto updating query log as this better than lame refresh button (also applicable to dashboard)

**Comment by ainar-g** [comment]
Merging into #2554.  Dashboard autoupdate is already in the works.  Thanks.

**Comment by lux5am** [comment]
More than 2 years already 🥲
