### ISSUE TITLE
[Incorrect blocking] Unable to launch Deezer app on SmartTV

### ISSUE THREAD

**Issue by SBI-boy** [AdguardTeam/AdGuardHome#307]
Hello, I'm not able to use the Deezer app on my Samsung SmartTV while using your default DNS servers

### Expected behavior
Normal app use

### Actual behavior
App doesn't launch... I get an unreachable server error message

### Your environment
|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130 & 176.103.130.131
| How did you setup DNS configuration: |System
| Device model: |Samsung MU6500
| Operating system and version: |Tizen OS v.1230

**Comment by SBI-boy** [comment]
@Alex-302 I wasn't able to collect any log information from the TV and router, maybe you can suggest me to use an specific software for that purpose

**Comment by ameshkov** [comment]
Not really, unfortunately. 

Once we publish the self-hosted version of AG DNS, @SBI-boy will be able to use it instead and examine the local DNS logs to figure what's wrong, but it's not yet ready for public use.
