### ISSUE TITLE
Provide option for custom service defenition from the config.

### ISSUE THREAD

**Issue by kisst** [AdguardTeam/AdGuardHome#3076]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

Handling  per client rules in custom rules is possible, but not too handy in practice due to the complex rule expressions.
The list of services defined is short, and not extendable.

### Proposed Solution

Allow users to extend the `internal/dnsfilter/blocked.go` serviceRulesArray with custom definitions, even better if this can be consumed like the block list itself, aka based on a feed. 

Specific use-case, blocking CDN access to any CSS JS etc static lib which with browser plugin can be injected back into cache so page functionality does not break, hence it can be blocked on DNS level, but for clients where this is not an option, this "service" should be enabled, OR  an other specific use-case is connectivity check endpoints, most of the device talk home with performing "am I online" connectivity checks, this can be by default blocked, but some devices will just drop the connection if they don't "think" that they are online, so having this defined as a service, would make it easy to switch on and off.

### Alternatives Considered

The current way to do this now, is use labels, and label specific rules, which works :tm: but pretty complex to handle.
### Additional Information

Icons, and etc in case custom service definitions can be generic.

**Comment by ameshkov** [comment]
Duplicates #1692
