### ISSUE TITLE
Filter List by device

### ISSUE THREAD

**Issue by zzyonn** [AdguardTeam/AdGuardHome#3078]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Unable to specify list by device, only service lika whatsapp etc ...

### Proposed Solution
Add the possibility to select filter list by device 
EX :
Create list group ==> Children and all
       Specify filter list by group
Add desired device and affect to group or filter list

It be usefull, for exemple to work at home, specify a "basic" list for work computer to not block some work service but block unwanted ads .

Actually all is blocked and add each site to open by client is to complicated

The filter by device can be done by MAC address for those are on SLAAC, to simplify the IPV6 filtering too.

Regards

**Comment by ameshkov** [comment]
Duplicates #435
