### ISSUE TITLE
AdGuardHome clients not seen in Docker install

### ISSUE THREAD

**Issue by truthsword** [AdguardTeam/AdGuardHome#3085]
### Issue Details

* **Version of AdGuard Home server:**
  * .106.1
* **How did you install AdGuard Home:**
  *  Docker
* **How did you setup DNS configuration:**
  *  Router
* **If it's a router or IoT, please write device model:**
  *  ASUS RT-AC86U
* **CPU architecture:**
  *  Synology
* **Operating system and version:**
  *  DSM 6.2.3

### Expected Behavior
Top clients list shows only Docker IP ... 172.17.0.x

### Actual Behavior
Added 3 clients; 2 defined by LAN IP, 1 defined by MAC address. None appear under top clients,

### Screenshots
![](https://i.imgur.com/RqbsR0k.png)

<details><summary>Screenshot:</summary>

### Additional Information
 Also tried setting client specific filters. None appear. Only the Docker IP is present.

Using NAS IP in DNS field (port 53 UDP/TCP) linked to container port 53.

**Comment by ainar-g** [comment]
Hello.  We cannot reproduce the issue.  Do you run your container with `--network host`?  Because otherwise your container predictably sees all clients as coming from the forwarded network.

**Comment by truthsword** [comment]
> Do you run your container with` --network host`?

No. I am running in bridge mode (no macvlan in use)

Filtering is occurring on all clients, but, as stated above, custom filtering and client specific reporting do not work.

I only have ports 53 and 3000 matched to the container. All other external ports are set as "Auto". Could that be the issue?

Would the yaml file be helpful?

**Comment by ainar-g** [comment]
As far as I know, if you don't use `--network host`, then your Docker container will see all clients as coming from one source.  I'm not sure that there is a way to forward the client IP addresses to the container without that option.

**Comment by truthsword** [comment]
I didn't realize that. A quick test of "host" done here, and that solves my issue. Now I if I can get the friendly "client" name to appear on the query page (instead of IP), I'll be set.

Thanks for your help!
