### ISSUE TITLE
Dig: Warning: ID mismatch: expected ID 27503, got 0

### ISSUE THREAD

**Issue by attinderdhillon** [AdguardTeam/AdGuardHome#3087]
After the update ipv6 queries are very slow. dig command is throwing some warnings..

'root@Server:~# dig google.com @2405:201:xxxx
;; Warning: ID mismatch: expected ID 11421, got 0
;; Warning: ID mismatch: expected ID 11421, got 0
;; Warning: ID mismatch: expected ID 11421, got 0
'

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by attinderdhillon** [comment]
**dig command**
`dig bing.com @2405:201:xxx
;; Warning: ID mismatch: expected ID 16657, got 0

; <<>> DiG 9.16.6-Ubuntu <<>> bing.com @2405:201:xxx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16657
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;bing.com.			IN	A

;; ANSWER SECTION:
bing.com.		3324	IN	A	13.107.21.200
bing.com.		3324	IN	A	204.79.197.200

;; Query time: 4 msec
;; SERVER: 2405:201:xxx#53(2405:201:xxx
;; WHEN: Thu May 06 22:46:18 IST 2021
;; MSG SIZE  rcvd: 69
`

**DEBUG**

`tail -f log.txt | grep bing.com
;bing.com.	IN	 A
2021/05/06 22:46:13 1406#2994 [debug] etchostscontainer: answer: bing.com -> []
2021/05/06 22:46:13 1406#2996 [debug] https://dns.google:443/dns-query: sending request A bing.com.
2021/05/06 22:46:13 1406#2995 [debug] 8.8.8.8:53: sending request A bing.com.
2021/05/06 22:46:13 1406#2997 [debug] tls://dns.google:853: sending request A bing.com.
2021/05/06 22:46:13 1406#2998 [debug] https://doh.opendns.com:443/dns-query: sending request A bing.com.
2021/05/06 22:46:13 1406#2994 [debug] DNSFwd: Checking record A (13.107.21.200) for bing.com.
2021/05/06 22:46:13 1406#2994 [debug] DNSFwd: Checking record A (204.79.197.200) for bing.com.
;bing.com.	IN	 A
bing.com.	3329	IN	A	13.107.21.200
bing.com.	3329	IN	A	204.79.197.200
;bing.com.	IN	 A
2021/05/06 22:46:18 1406#3030 [debug] etchostscontainer: answer: bing.com -> []
2021/05/06 22:46:18 1406#3030 [debug] DNSFwd: Checking record A (13.107.21.200) for bing.com.
2021/05/06 22:46:18 1406#3030 [debug] DNSFwd: Checking record A (204.79.197.200) for bing.com.
;bing.com.	IN	 A
bing.com.	3324	IN	A	13.107.21.200
bing.com.	3324	IN	A	204.79.197.200
`

**Comment by ameshkov** [comment]
Please don't do `grep bing.com`, I need to see the full picture

**Comment by attinderdhillon** [comment]
`
[ad.txt](https://github.com/AdguardTeam/AdGuardHome/files/6438920/ad.txt)
`

**Comment by attinderdhillon** [comment]
Working fine after removing multiple upstream DNS Server. Now I only have "8.8.8.8"

**Comment by ameshkov** [comment]
What exact upstreams did you have enabled?
What mode were you using? Load-balancing/parallel/fastest IP?

**Comment by attinderdhillon** [comment]
With parallel requests.

`
  - 8.8.8.8
  - https://dns.google/dns-query
  - tls://dns.google
  - https://doh.opendns.com/dns-query
  - quic://dns-unfiltered.adguard.com:784
`

**Comment by ameshkov** [comment]
I've been able to reproduce this.

**Steps to reproduce:**

1. Upstreams from https://github.com/AdguardTeam/AdGuardHome/issues/3087#issuecomment-834087963
2. Enable "Parallel requests"
3. Start doing `dig Ngoogle.com AGH`, change the domain all the time (it's important that it shouldn't be served from cache)
4. At some point you'll run into this issue.

**Comment by Spark1y** [comment]
This "Warning: ID mismatch" error 
can be reproduced from version 0.106.1 to 0.106.2 with "Parallel requests" option enabled,
if the option is set to "load balancing" then everything is normal.

**Comment by attinderdhillon** [comment]
Working fine in Adguard edge ( v0.107.0-a.29+5acae6e2 ), Thank You.
