### ISSUE TITLE
Error message in the query log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#3089]
### Issue Details

* **Version of AdGuard Home server:** v0.107.0-a.16+ba63a330
* **How did you install AdGuard Home:** Synology NAS
* **How did you setup DNS configuration:** System
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:** x86
  * 
* **Operating system and version:** Synology DSM(Debian I guess)

### Expected Behavior
No error.

### Actual Behavior
Error message.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/117351908-f5707180-aeb6-11eb-995b-423c0f1adbe2.png)

![image](https://user-images.githubusercontent.com/8361299/117351962-0ae59b80-aeb7-11eb-8708-b61c0b66a821.png)

![image](https://user-images.githubusercontent.com/8361299/117352001-1933b780-aeb7-11eb-96a9-7add5d17e1ce.png)

</details>

**Comment by Alex-302** [comment]
@IldarKamalov Please take a look.

**Comment by ameshkov** [comment]
@Alex-302 а что ты жал, чтобы такое получить? У тебя там `response_status=null`, откуда переходил на Query Log?

**Comment by Alex-302** [comment]
Выскочило когда разные запросы искал.
Вот с таким адресом повторяется
`http://192.168.88.102:88/#logs?response_status&search=support-`
