### ISSUE TITLE
Unable to do google image search if AdguardDNS is configured

### ISSUE THREAD

**Issue by Siutat** [AdguardTeam/AdGuardHome#309]
### Steps to reproduce

1. Configured DNS point to Adguard DNS
2. Open Browser (Firefox Latest/Chrome/iOS Safari)
3. Google Search any Images
4. Returning broken result.
5. Go back to router and configure DNS pointing to 8.8.8.8, repeat step 2 to 4, perfect result.

### Expected behavior

Should be able to do Google image search with normal results set.

### Actual behavior

only few results are displayed.

<details><summary>Screenshot:</summary>

![ray-thinkpad 2018-08-29_013118](https://user-images.githubusercontent.com/42781077/44739754-47b83c80-ab2b-11e8-969e-2b339d6e7696.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use: | Default, 176.103.130.130,  176.103.130.131
| How did you setup DNS configuration:| Router
| Device model:| Windows 10
| Operating system and version:| Microsoft Windows [Version 10.0.17134.191]

**Comment by ameshkov** [comment]
Can't reproduce it either :(

**Comment by gedw99** [comment]
What if you try it from a different ISP ?
Maybe your ISP is doing it ?
