### ISSUE TITLE
Safebrowsing bug

### ISSUE THREAD

**Issue by DavidOsipov** [AdguardTeam/AdGuardHome#3090]
### System Details:
* **Version of AdGuard Home server:**
  * Adguard Home v0.106.1
* **How did you install AdGuard Home:**
  * Snap package
* **How did you setup DNS configuration:**
  * Ubuntu VPS
* **CPU architecture:**
  * x86_64
* **Operating system and version:**
  * Ubuntu 21.04
* **Unbound is present:**
  * Unbound  1.13.1 (with DNSSEC features and hardenings on)

### Expected Behavior
Web page https://testsafebrowsing.appspot.com/s/malware.html is blocked by Adguard Home with Adguard Browsing security web service 

### Actual Behavior
Adguard Browsing security web service is turned on
![1](https://user-images.githubusercontent.com/38164582/117368130-a0326100-aeb2-11eb-88d4-ea5c6db5882c.PNG)

The web page https://testsafebrowsing.appspot.com/s/malware.html is reported as malicious by Google Safe Browsing. As I remember a Google Safe Browsing API is being used by Adguard home
![2](https://user-images.githubusercontent.com/38164582/117368196-b6d8b800-aeb2-11eb-92d7-5d1609507c76.PNG)

But instead of blocking access to the web page, Adguard home resolves the hostname and the webpage can be accessed by a web browser. 

![3](https://user-images.githubusercontent.com/38164582/117368318-e38ccf80-aeb2-11eb-87f8-69e318bc6e01.PNG)

**Comment by ameshkov** [comment]
We're not using Google Safebrowsing, but generally, we don't mind adding that test domain to our blacklist as well.
