### ISSUE TITLE
DHCP static lease capitalization issues since v0.106

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#3096]
### Issue Details
DHCP static leases since v0.106 are now all lowercase and uneditable since the upgrade.
e.g. from `Device-Name` to `device-name`.

* **Version of AdGuard Home server:**
  * v0.106.2 
* **How did you install AdGuard Home:**
  * wget via GitHub 
* **How did you setup DNS configuration:**
  * IoT 
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B+ 

### Expected Behavior

Static leases were untouched.

### Actual Behavior

All names have been lowercased.

### Additional Information

I noticed a few major updates regarding DHCP static leases, but couldn't find anything about capitalisation. 
In regards to being uneditable, I seem to remember being able to edit my DHCP leases, but I could be wrong.

**Comment by planet0** [comment]
Looking further, it seems like the device name remains untouched all across AdGuard Home, just not the static leases list on the DHCP settings page.

**Comment by ameshkov** [comment]
Tbh I am not sure if that's a bug or not, let's wait for @ainar-g

**Comment by EntropySmoke** [comment]
Does AGH have host name naming rules? Raspberry Pi raspi-config states that host names must be lower-case and can only have hyphen or dot as symbols.

**Comment by planet0** [comment]
I've been using both upper and lower case with hyphens... Having another look at raspi-config now and it still mentions that letters are case-insensitive.

![Screenshot_20210508-075545.png](https://user-images.githubusercontent.com/65204836/117512503-17f7ad00-afd3-11eb-948c-5c40c2e794bc.png)

**Comment by EntropySmoke** [comment]
Yeah, I was also wrong. You can't have punctuation in host names, but you must have a dot in domain names - http://www.differencebetween.net/technology/difference-between-hostname-and-domain-name/ .

**Comment by planet0** [comment]
Also just to provide a visual reference regarding this issue:

<details><summary>Current Device Names:</summary>


![image](https://user-images.githubusercontent.com/65204836/117519667-e0473000-afe7-11eb-97f5-023b75c25f45.png)

</details>

<details><summary>Unexpected Lowercase Device Names:</summary>


![image](https://user-images.githubusercontent.com/65204836/117519722-14baec00-afe8-11eb-9b9c-01ecbaf719b0.png)

</details>

**Comment by planet0** [comment]
I just realised that I also have the names set up as Clients.
The client names are still capitalised, where are the DHCP names have been automatically made all lowercase.

<details><summary>Clients:</summary>


![image](https://user-images.githubusercontent.com/65204836/117519929-1df88880-afe9-11eb-8273-980133c52a91.png)

</details>

<details><summary>Clients (runtime):</summary>


![image](https://user-images.githubusercontent.com/65204836/117519953-336db280-afe9-11eb-8ba2-d7ab58078101.png)

</details>

So trying to wrap my head around this.

Are DHCP names now forced to be lowercase?
But Client names can still be fine?

Why does raspi-config state hyphens and both lower and upper case are okay, but now AdGuard Home forces lowercase?

**Comment by planet0** [comment]
Nothing has broken @ainar-g, but it has now become more difficult to manage my hostnames with forcing lowercase since #2952. Could we have hostnames allow both upper and lower case again, as hostnames are still able to be case-insensitive and with hyphens?

**Comment by ainar-g** [comment]
Sorry, but the current behaviour is intended and it makes a lot of things easier on the backend.  Once we solve some issues with data storage, we may think about adding some kind of display names or aliases to static leases, but until then we recommend to just always use lowercased hostnames everywhere.

I'm going to close the issue, but if you have additional thoughts please feel free to add them.

**Comment by planet0** [comment]
Thanks @ainar-g, I appreciate the response and now understand.
