### ISSUE TITLE
Night Mode for GUI

### ISSUE THREAD

**Issue by samsam-rolon** [AdguardTeam/AdGuardHome#3103]
Juste a Night Mode theme for GUI which can be selected manualy or related to current time

**Comment by planet0** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/613

Seems that they are planning on this for their redesign:

> Hey all, we'll definitely do that, but only **after** we finish with the massive redesign #2554

_Originally posted by @ameshkov in https://github.com/AdguardTeam/AdGuardHome/issues/613#issuecomment-777266138_
