### ISSUE TITLE
The last updated time showing in `DNS blocklists` is not correct

### ISSUE THREAD

**Issue by woodpenker** [AdguardTeam/AdGuardHome#3104]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
  * v0.106.2
* **How did you install AdGuard Home:**
  * 
  * Github releases
* **How did you setup DNS configuration:**
  * 
  * System
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
  * AMD64
* **Operating system and version:**
  * 
  * Ubuntu 20.04

### Expected Behavior

The last updated time should be shown as `2021年5月8日00:56`, but it shows `2021年5月8日24:56`

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/7452124/117520828-e08dfe00-afdc-11eb-9e46-936348580a0f.png)

</details>

**Comment by ameshkov** [comment]
As I recall, we simply use the browser's own function to format date&time: `Date.toLocaleString(navigator.language, options);`. Probably, this needs to be fixed/resolved on the browser side (maybe in the browser settings).
