### ISSUE TITLE
Unable to add DHCP leases

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3107]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:** `0.106.2`
* **How did you install AdGuard Home:** GH Releases/Install script
* **How did you setup DNS configuration:** Router/WAN DNS
* **If it's a router or IoT, please write device model:** N/A
* **CPU architecture:** `arm64`
* **Operating system and version:** Ubuntu 20.04.2

### Expected Behavior

DHCP leases would get added.

### Actual Behavior

DHCP leases aren't getting added...

![image](https://user-images.githubusercontent.com/19761269/117530526-42f5f700-affb-11eb-8e84-fd33790648ae.png)

### Additional Information

- Adding a bogus hostname results in `Network error`
- Using Unbound

<img width="225" alt="image" src="https://user-images.githubusercontent.com/19761269/117530555-67ea6a00-affb-11eb-91f2-6fb491297e82.png">

**Comment by ainar-g** [comment]
Hello.  The domain name is a required parameter.  Does the error message go away if you enter a valid domain name?

**Comment by EntropySmoke** [comment]
I get the same issue if I try to add Static Leases before enabling DHCP Server and saving configuration. After enabling DHCP Server, adding Static Leases is not a problem.

**Comment by ainar-g** [comment]
This should be fixed on the `edge` channel as of revision c890f5c1.  Could you please check if the problem is gone?

**Comment by agneevX** [comment]
Sorry, I use stable builds only. I'm closing this issue, thank you.
