### ISSUE TITLE
Disallowed domains must be case insensitive

### ISSUE THREAD

**Issue by HorayNarea** [AdguardTeam/AdGuardHome#3115]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

In the DNS settings one can configure "disallowed domains", queries to these domains actually are not answered but they still appear in the logs and the clients who send these queries appear in the statistics on the dashboard.

### Expected Behavior
AGH handles "disallowed domains" exactly like "disallowed clients", so these queries should not appear in logs and statistics.

### Actual Behavior
AGH only ignores queries for "disallowed domains" but still includes them in logs and dashboard statistics.

### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/1871153/117553570-a3fce980-b052-11eb-9a10-f7d0a2b7b248.png)
![image](https://user-images.githubusercontent.com/1871153/117553636-ffc77280-b052-11eb-9d6d-01566bd7ac0d.png)

</details>

### Additional Information
I consider this a bug, if you don't agree please understand this as a feature request for a config flag to have both "disallowed"-things be treated alike.

**Comment by ameshkov** [comment]
Definitely a bug.

**Comment by ameshkov** [comment]
Appears to be a rather simple bug:

* `dig -t a version.bind. @127.0.0.1` -- gets blocked
* `dig -t a VERSION.BIND. @127.0.0.1` -- not blocked

The bug is originally in the https://github.com/AdguardTeam/urlfilter library.

**Comment by ameshkov** [comment]
@DandelionSprout that's exactly how disallowed domains work - the queries are simply dropped. You can see REFUSED result only when for some reason domain has passed the check.

**Comment by EugeneOne1** [comment]
Hello to you, @HorayNarea and @DandelionSprout.  We've brought the little fix for this issue.  It's available in the latest edge builds as of snapshot f41d5b98670c94dd6f3b3e1c5ed47f961d6b8a98.  Could you please check, if it works fine now?

**Comment by HorayNarea** [comment]
On quick glance it looks like it works :+1: 
I'll run the edge build for a few hours now to have a real world test.

**Comment by DandelionSprout** [comment]
I'm on the beta channel (as opposed to Nightly) and can't test tonight, at least.

**Comment by EugeneOne1** [comment]
We'll close the issue for now.  Please, feel free to reopen it in case you face it again.
