### ISSUE TITLE
Bug report: Blocklists aren't working all the time - data added

### ISSUE THREAD

**Issue by bloodyskullz** [AdguardTeam/AdGuardHome#3131]
Hi,

Issue:
Blocklist is not blocking everything stated in the lists. Entries from default blocklists to custom ones added are slipping through the cracks.

Example of domain: 
"doubleclick.net" was processed in IE 11, failed in chrome because of my adblocker "Ublock Origin".

Verified via screenshot below.

Version of adguard home & hardware: v0.106.2 installed on Ubuntu 20.04LTS on an intel NUC 6th gen with 4GB of RAM.

Installed via automated install.

I noticed this issue when my blocklist for adult content wasn't being filtered and blocked correctly. Tested with default list and the issue presented itself again. Please feel free to reach out to me for more information either here or via email mrglitch1989@gmail.com (this is faster). Will be more than happy to assist.

Thanks

![image](https://user-images.githubusercontent.com/79482326/117897340-97fe6b00-b290-11eb-8fd7-5b36c20c65e1.png)

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by bloodyskullz** [comment]
Where do I find the .yaml file?

**Comment by ameshkov** [comment]
Right near `AdGuardHome` binary file

**Comment by bloodyskullz** [comment]
I am sorry but I don't know which directory this is located. Can you give me a path to the location?

Thanks

**Comment by ameshkov** [comment]
I am not sure how exactly you installed AGH, but if you followed the standard procedure, it would be in `/opt/AdGuardHome`

**Comment by bloodyskullz** [comment]
I used this command to do the install

`curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh`

**Comment by EugeneOne1** [comment]
Yes, it should be there, if you're using Linux (Ubuntu in your case).  Also, don't forget to turn _AGH_ off before editing the configuration file, if it isn't.  Otherwise, your changes will be rewritten.

```
cd /opt/AdGuardHome
sudo ./AdGuardHome -s stop
```

You should also turn it on manually afterwards.

```
cd /opt/AdGuardHome
sudo ./AdGuardHome -s start
```

**Comment by bloodyskullz** [comment]
`;; QUESTION SECTION:
;www.flameporn.com.	IN	 A

2021/05/12 21:36:27 1986661#2406 [debug] etchostscontainer: answer: www.flameporn.com -> []
2021/05/12 21:36:27 1986661#2406 [debug] github.com/AdguardTeam/AdGuardHome/internal/dnsfilter.check(): Parental: checking www.flameporn.com: bec9.pc.dns.adguard.com.
2021/05/12 21:36:27 1986661#2406 [debug] https://dns-family.adguard.com:443/dns-query: sending request TXT bec9.pc.dns.adguard.com.
2021/05/12 21:36:27 1986661#2406 [debug] https://dns-family.adguard.com:443/dns-query: response: ok
2021/05/12 21:36:27 1986661#2406 [debug] Parental: received hashes for www.flameporn.com: [bec9036f81bc7e7f11893a3af0fe66bc95a60599b5dd5697d13cfe29a92b9a1f bec904a0bed28d6fcbdbf75e2b4c9c4769078ac85157b7d34a630f8574162046 bec908c13c5533257a5a62a153645af5eb36db8632c28bc1b41dffbc6352626b bec909e45db15da984f55f0feaf05f3aee401a7af9a23d7dd4735a37239b524f bec90bc6ccd839949ec4b7b6323366a571c28aa7f02921ff9dadf6cc2d65a845 bec90db169deb15ccf95efb2d3b67e1a4f4cf567504e0864449a323d9b41fb0e bec91200ac2fa26279449f6820c9dabd909bc276528b230ce422aafc00d81cf0 bec91376827f461f51436d5783917d7b3b869c705286de560cd99d633d755e47 bec917596ea4121c094ef021f1361953e1e2d9ee66c2c00bebef8f93917c9499 bec917b4f8d1a0e6e7ab947598bb8dece5b5433fca94085bc5f5101b972a9d62 bec91dcb99b827c116ff6e6f5ee09a61251025536dc29bd499102e386dc3ea93 bec92bb49a00c6e367107d51bdce1e982a435e7edbac48ba8985753c30571a2b bec92bf6daddef2971f527ca49a06b8518c6ed24f5a752166b485cf559dda285 bec92fe98d4800c17d2c63106ee87bc254c17217747a594a92c0b3798422a8a3 bec93fbab6bb8c9ccddcafe6e475a06c12376cd74ae5c89efa79822fc4f0b504 bec940db7fe21cce89db3ac7a60e05d1fa29ca69c02cd739198531f30f5f2598 bec94ae71b1bf89722f78866ced82d4b4859464e588c54694add1ef0085a8e42 bec94bb37a954747e4b68be6f90f8e7c8a489c7670ebdf72175f5a9e905d84ec bec95000c79242bfa11c2621e1e7b98c0fafc77af6cced74e76d937d5fb33cdc bec950d63abebcc7193ea2b5f47ab12423bb71ba432d2cef22fcabf5076a3b2e bec950f9495956445b7f589f1123e30c9c2036198229a6dd146c5a8bf95c0ac2 bec9522fd9ff6519cda9670e8fd00c668ac3a8e12616e4b22740a7b25bd2399b bec952792656109aea59132f21afcc34c96a712b663fecdb0032660137fa78a0 bec95bab879cb84c467d1bfae9517889c6b8b013cf510150d9baa31ca5c26b0c bec95d1c1685530c6b0ff09bc2f7ae6aaf61f0c71ce7fe46a53b7182fa37d8fa bec96084d8fb54323357db2626d75c47d079d50d94e14577cf7ee27486b56ec7 bec964d350f79e8493107d648e8ef7f9ed9cca1f8bb834329e2b26769656fd42 bec96926dbcf7e953759b42dbdaeeeb3f022ef00c77b86eb5cc51a4efad3b947 bec96c2a9e84deb0accadaf62427ceb4d0d9b41ecc7f72d1292eb4a538c5e0cc bec9745190cd928f55f390125d10d65be4436cf0bff42af22145beb6f9523552 bec9750bb64d607a54393ba59f1fb2b9332c673b1b49100dac31c8c5a85dde3e bec975e567f8c6e96ea59b446afaaf407cf8079860f6021112d3509a7d6fd2b5 bec977d1d9f18007e63a78ed70e407fb1febea4d08df452d0036b903421039fc bec97bab906931a49ad3b9fc0249058b30f1e1ea13e2b254bab68eea2fe01842 bec97cce897990a8ad7bfd42ba152eb485fa63ee0db561ff3c862266aec17b63 bec9870d9c7a9bd94391f23b07c7263899e6618ace3e991eb78faf5d93b60f09 bec98ff0b3e4154b4667e201d822ebe2fa9d1ca35fbdb6a4c0bfb5de22b08d90 bec9928316ca011c720e99fd3c6ed1bbb3c1e3dba473eb9c5fcb3cc4a19ee717 bec995a67552f1206c0800a236162ae0a0ca1ec33a7de53c4499a9a9c488d390 bec995f64e7d48a96d1c249b90897f0defadc3494b83e93aee501decc4b17460 bec99b068720b8218b358c465e7d6b43a7e31d645eb2540377e2edf0cebe2e57 bec99bb68095bb77cbb8cb7bd760f1b7529c946c9024cea05d48384fc539c7fc bec99d8d9fccd385a68deefcb08b88623aa3391eaa49516c1c09d8c8ca05dc9d bec9a541ea05a3ed57ef416259163b50686b5f106b347e20c4709b50c4a85ab0 bec9b5cba3a3efc472f08b330696b2d424e36ddb714a8813a18dc43927230106 bec9b8c2adc8f4eecfbb12eca780b0a3b64b9c4db5e83f761c8319448b5729d8 bec9b95046387f389cbdacc5c0256bf5b05f01ae44d48d8648c8171f73b74273 bec9bbf9b631c7aed1c2f156044474a731d1b38067064b1dfc26f130113c2f22 bec9c5c5a91eae0cc1de5bb2dd17c2e1a4c905c16696858a90c305ccb14ec0ae bec9cded8f377d0d9ea3d905046fb578afd517df3de32986d5ac871ed9b59217 bec9ce8dc94c166368610ef0ee4face8cd31051b31fe0d9272be711e50369550 bec9d7f46e0160810b5d17a55e98ac6bc9ca7e2f92c1fce1badb444210bda24c bec9d9408e8177cc640d0cfd618beb3a0579def531775e981fca1d1e3926ad21 bec9de40f1b440998a4fb45db8ee1374bf49ff03981db093092088a7400a5f50 bec9e4f692df3f998d1ceb60c1c7591c83ee3ee3273d15fa4b3c2319a124d6a2 bec9e782370c13c5bc521f85c7d3679446e405977208271e596c499cda01ceee bec9ed4c978eebe2a2fc59813a572ee622c696dc482b766c2ffcc342e3118770 bec9ef4de321fcccd251355ded7888a1b22caa78aee3352070d6757b6b6323f2 bec9f1678831411728ca882d1830b4d98745bdd96eb23027759196737066495d bec9f6a204f7fa0b2e1b6e04a786513715a9e4a2bb4b9f708623fd2140657286 bec9f6fb7ce04087f68cbd11a1b18b76e2a2ac51480c60b5333f117c4a0b5a6f bec9f7f6715315592b37d32267125e75558b211102debab74f63bba424a4425f bec9fd6d41161dd78eb14d6b5e28e5f2d91e95b67b55ebd61150cb178618fecd bec9fdf865297bb4b7576b5423eca77c69a097fee53ec216033b6b4b28b3baf9 bec9fffbfba3993e326c58a6ba1ed3d627770a1404da4d0915c87e0ba30bda42]
2021/05/12 21:36:27 1986661#2406 [debug] Parental: stored in cache: [190 201]
2021/05/12 21:36:27 1986661#2406 [debug] github.com/AdguardTeam/AdGuardHome/internal/dnsfilter.(*DNSFilter).checkParental(): Parental lookup for www.flameporn.com; Elapsed time: 12ms
2021/05/12 21:36:27 1986661#2406 [debug] https://doh.opendns.com:443/dns-query: sending request A www.flameporn.com.
2021/05/12 21:36:27 1986661#2406 [debug] https://doh.opendns.com:443/dns-query: response: ok
2021/05/12 21:36:27 1986661#2406 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream https://doh.opendns.com:443/dns-query successfully finished exchange of ;www.flameporn.com.	IN	 A. Elapsed 69 ms.
2021/05/12 21:36:27 1986661#2406 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(): RTT: 69 ms
2021/05/12 21:36:27 1986661#2406 [debug] DNSFwd: Checking record A (213.174.132.103) for www.flameporn.com.
2021/05/12 21:36:27 1986661#2406 [debug] ipset: starting processing
2021/05/12 21:36:27 1986661#2406 [debug] ipset: skipped processing for request
2021/05/12 21:36:27 1986661#2406 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 48312
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0`

That is one query that has been going through even though I have it in my blocklist. Second one below is for doubleclick.net

`;; QUESTION SECTION:
;ad.doubleclick.net.	IN	 A

2021/05/12 21:29:33 1986661#611 [debug] using settings for client dad-pc with ip 192.168.1.177 and id ""
2021/05/12 21:29:33 1986661#611 [debug] etchostscontainer: answer: ad.doubleclick.net -> []
2021/05/12 21:29:33 1986661#611 [debug] filtering: found rule "||doubleclick.net^" for host "ad.doubleclick.net", filter list id: 1
2021/05/12 21:29:33 1986661#611 [debug] github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).filterDNSRequest(): Host ad.doubleclick.net is filtered, reason - "FilteredBlackList", matched rule: "||doubleclick.net^"
2021/05/12 21:29:33 1986661#611 [debug] ipset: starting processing
2021/05/12 21:29:33 1986661#611 [debug] ipset: skipped processing for request
2021/05/12 21:29:33 1986661#611 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 18438
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0`

From what I can understand the blocklist was searched but it ignored my custom one which had the URL being blocked and completely ignored it. I am 10000% sure my blocklist has the URL listed.

**Comment by bloodyskullz** [comment]
Hi,

@ameshkov is info i provided enough? Is it an actual bug?

**Comment by ameshkov** [comment]
@bloodyskullz the log does not seem to be enough.

I see that `www.flameporn.com` is not blocked because it's not in our adult websites list (yet). Is it what you meant? If you encounter a domain that should be listed there, please report it to our support service at `support@adguard.com`, we'll add it promptly.

**Comment by bloodyskullz** [comment]
@ameshkov I'm confused, if I have a blocklist which already contains that site, shouldn't it take effect instantly?

Is there a filesize limit for blocklists?

**Comment by ameshkov** [comment]
There's no limit. Can you share that blocklist?

**Comment by bloodyskullz** [comment]
https://github.com/bloodyskullz/Adguard-blocklist/tree/main/porn%20block

it's a large list so it would be best to download and do a search for the title. I didn't add the www portion as I replicated it based on the default adguard which also didn't contain that.

**Comment by ameshkov** [comment]
You added it to your AGH with `https://raw.githubusercontent.com/bloodyskullz/Adguard-blocklist/main/porn%20block/pornblock.txt` this URL right?

**Comment by bloodyskullz** [comment]
Tes that is right, it still didn't take effect.

**Comment by ameshkov** [comment]
Ah, I see, you're adding spaces which shouldn't be there.

`|| example.org ^` --> `||example.org^`

Also, I see that you're converting simple hosts lists to AG syntax. I suggest you using [this tool](https://github.com/AdguardTeam/HostlistCompiler) for that. It will take care of duplicates, validation, etc, etc.
