### ISSUE TITLE
DNS-over-Quic display in Query Log page

### ISSUE THREAD

**Issue by leo15dev** [AdguardTeam/AdGuardHome#3133]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.107.0-a.17+3678655e
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  *  loT
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 4 Model B
* **CPU architecture:**
  *  ARM
* **Operating system and version:**
  *  Ubuntu 20.04.2 LTS 

### Expected Behavior

If DNS query by DoQ, it should be presented like Type: A, DNS-over-Quic
### Actual Behavior

The DNS query by DoQ, it  presented as Type: A, DNS-over-HTTPS
### Screenshots

![DOQ](https://user-images.githubusercontent.com/68909774/117900702-54414b00-b2fc-11eb-839d-dbb2945d5a8a.jpg)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
You're confusing the protocol the query was received from with the protocol that was used to contact the upstream.
