### ISSUE TITLE
Show local PTR DNS servers and other parameters that were deduced

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#3136]
It is often useful both for users and for us to know which values AGH is using when users don't use custom settings.  The most obvious example of that is the “Private DNS servers” setting.  There should be some kind of way to see the actual value used by AGH in the UI.

**Comment by ameshkov** [comment]
There're two pretty simple solutions:

1. Change placeholder to "Keep this field empty to use the system default DNS server":
![image](https://user-images.githubusercontent.com/5947035/118297494-e4db7f00-b4e6-11eb-92d8-e8965da1ffe4.png)

2. Change placeholder to the actual default DNS address (if not set, keep the default DNS resolver there):
![image](https://user-images.githubusercontent.com/5947035/118297554-fe7cc680-b4e6-11eb-82d8-d2818adc98bb.png)

@ainar-g please choose the solution you like more.

**Comment by ainar-g** [comment]
@ameshkov  I don't think that putting them into the placeholder is a good idea, since people usually assume that placehoders only contain, well, placeholder text.  How about just adding another text?

![Screenshot from 2021-05-14 19-13-10](https://user-images.githubusercontent.com/4964986/118298777-94652100-b4e8-11eb-8ff0-aa3bf4d3e4b7.png)

**Comment by ameshkov** [comment]
Ah, well, this is a good solution indeed :)
