### ISSUE TITLE
Slow DNS Resolutions

### ISSUE THREAD

**Issue by bigverm23** [AdguardTeam/AdGuardHome#3137]
### Issue Details

* **Version of AdGuard Home server:**
  v0.106.2
* **How did you install AdGuard Home:**
  Docker
* **How did you setup DNS configuration:**
  Router DHCP, Host machine has static ip 10.0.0.15
* **If it's a router or IoT, please write device model:**
  Unifi USG
* **CPU architecture:**
  AMD64
* **Operating system and version:**
  Ubuntu Server 20.04

### Expected Behavior
Fast DNS Resolutions

### Actual Behavior
Slow DNS Resolutions and Page Load

### Additional Information
Followed the directions: 
Deactivate DNSStubListener and update DNS server address. Create a new file: /etc/systemd/resolved.conf.d/adguardhome.conf (create a /etc/systemd/resolved.conf.d directory if necessary):

[Resolve]
DNS=127.0.0.1
DNSStubListener=no
Specifying "127.0.0.1" as DNS server address is necessary because otherwise the nameserver will be "127.0.0.53" which doesn't work without DNSStubListener.

Activate another resolv.conf file:

mv /etc/resolv.conf /etc/resolv.conf.backup
ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
Stop DNSStubListener:

systemctl reload-or-restart systemd-resolved

What looks odd to me is my /etc/resolved.conf looks like:
/etc/resolv.conf

nameserver 127.0.0.1
nameserver 10.0.0.15

**Comment by ameshkov** [comment]
Tbh I am not sure about `resolved.conf`. But in order to troubleshoot performance issues, we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.
