### ISSUE TITLE
v0.106.2更新后，dns填写加密dns重启后无法使用

### ISSUE THREAD

**Issue by havefunhaifeng** [AdguardTeam/AdGuardHome#3138]
v0.106.2更新后，dns填写加密dns**重启后**无法使用
填写普通dns正常
![屏幕截图 2021-05-13 033356](https://user-images.githubusercontent.com/61355997/118036223-e437d100-b39e-11eb-8f74-9bde1e62136c.png)

**Comment by ameshkov** [comment]
看起来你系统的时间不准，所以 AdGuard 不能证实服务器的https证书。

还有，Google 看起来被拦截。

**Comment by qpzr** [comment]
+1 quic也是
从v 0.106b4开始  只要上游dns填了 quic 服务器  dns就罢工了 什么网站都打不开 提示找不到dns
