### ISSUE TITLE
Ability to manually set locally served and private networks

### ISSUE THREAD

**Issue by BirkhoffLee** [AdguardTeam/AdGuardHome#3142]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

in [internal/aghnet/subnetdetector.go#87](https://github.com/AdguardTeam/AdGuardHome/blob/master/internal/aghnet/subnetdetector.go#L87), the LAN subnets are hardcoded. I have this use case where `100.64.0.0/10` is considered a private, secure network (Tailscale). For PTR questions from that network, Adguard Home simply restricts them (in [internal/dnsforward/dns.go#327](https://github.com/AdguardTeam/AdGuardHome/blob/master/internal/dnsforward/dns.go#L327)) and returns an NXDOMAIN. If I request with an IP within `locServedNets`, the PTR question is correctly handled.

### Proposed Solution

`locServedNets` should be configurable in `AdGuardHome.yaml` as an array.

### Alternatives Considered
There is no apparent alternatives.

### Additional Information
None.

**Comment by ainar-g** [comment]
@ameshkov, I remember we've discussed this.  This shouldn't be too hard to do in v0.107, considering the current code.  What do you think?

**Comment by ameshkov** [comment]
Let's do it, but v0.107 kinda overloaded, let's plan it for a later milestone.

**Comment by EugeneOne1** [comment]
@BirkhoffLee, hello again.  We've just pushed the latest edge build that implements the feature.  Could you please install it and try to set up your own private networks?  You may also read the description of the new `private_networks` field of configuration in the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration).

**Comment by jumpsmm7** [comment]
@EugeneOne1 

Can you guys update documentation on how to better use this feature? After updating my edge version a few days after this was added, my client names are no longer in the client list. ( i am still able to resolve client names locally). They just are not registering to AdGuardHome statistics and logs.

**Comment by jumpsmm7** [comment]
@EugeneOne1 

On both the stable, and beta versions, I am having no issue resolving client names to either query log or statistics. It appears that the only impacted version is the Edge version.

**Comment by EugeneOne1** [comment]
@jumpsmm7, hello and thanks for the remark.  There is indeed a bug introduced.  We'll fix it in the nearest future.

**Comment by jumpsmm7** [comment]
@EugeneOne1 , thank you for a timely response. And I completely understand. Awesome work with all the strides you all are taking thus far in regards to AdGuardHome. I will continue to test improvements as they progress.

**Comment by EugeneOne1** [comment]
@jumpsmm7, well, the latest build in the edge channel is ready to be tested.  Could you please take a look at it?  FYI, we've changed the runtime clients' sources priority, so AGH will now get a hostname from rDNS first.

**Comment by jumpsmm7** [comment]
@EugeneOne1 I have made a discovery if you will humor me a bit longer. it is regarding the ARP discoveries.

**Comment by jumpsmm7** [comment]
Some of the devices discovered under ARP, do have an RDNS associated as well. 
Is there away this could be a joined feature as well. Maybe RDNS is not working hard enough and needs to be user after ARP is discovered as well. 
![image](https://user-images.githubusercontent.com/49514613/159549393-da66c98a-29ba-4589-a705-f90f2c87ecbb.png)

**Comment by EugeneOne1** [comment]
@jumpsmm7, well, we're already have a couple of related issues (#1949, #3020).  However, if I recall correctly, no one ever suggested resolving clients recieved from ARP with rDNS.  This may be helpful since some implementations of ARP don't support hostnames.

@ameshkov, @ainar-g, what do you think?

**Comment by jumpsmm7** [comment]
Here is also an example using **arp -an**

/tmp/home/root# arp -an
`? (192.168.1.133) at 74:e1:82:36:05:ef [ether]  on br0`
`? (192.168.1.183) at 00:c3:f4:df:12:7e [ether]  on br0`
`? (192.168.1.17) at e4:5f:01:45:57:9d [ether]  on br0`
`? (192.168.1.12) at 34:97:f6:70:16:50 [ether]  on br0`
##shortened for readability.##

**Comment by jumpsmm7** [comment]
@EugeneOne1 @ainar-g @ameshkov , If you decide to make this a feature request, I would be willing to contribute my time and resources to testing it for you.

**Comment by ainar-g** [comment]
@EugeneOne1, @jumpsmm7, I'm not against that, but I also don't think that we should do that in the v0.108 cycle, as we already have quite a lot of changes planned.  If that's an enhancement that you would like to have, please write a separate issue about that, and we'll reexamine it once the v0.109 cycle starts.

**Comment by EugeneOne1** [comment]
@BirkhoffLee, we'll close the issue for now since it seems being resolved.  Consider reopening it in case of problems occured with the implementation.
