### ISSUE TITLE
DNS always stop and restart again and page control Adguard Home down

### ISSUE THREAD

**Issue by vinhlilo90** [AdguardTeam/AdGuardHome#3144]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ V] I am running the latest version
- [ V] I checked the documentation and found no answer
- [V ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.106.1
* **How did you install AdGuard Home:**
  *  From Github
* **How did you setup DNS configuration:**
  *  Router
* **If it's a router or IoT, please write device model:**
  *  Xiaomi Mi Router 4
* **CPU architecture:**
  *  MIPSle
* **Operating system and version:**
  *  OpenWRT 21.02.0 rc-1

### Expected Behavior

Some time my Adguard Home on my router have error on webcontrol and DNS some time stop and restart

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/61305337/118267357-24ee3200-b4e6-11eb-930d-cb6205056c92.png)
![image](https://user-images.githubusercontent.com/61305337/118267795-ca090a80-b4e6-11eb-84e3-2d5aa2ef3b6c.png)

</details>

**Comment by ainar-g** [comment]
Hello and thank you for your report.  Please add the following information to help us identify the problem:

1.  Have you tried the latest released version, v0.106.2?
1.  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment?

Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by vinhlilo90** [comment]
> Hello and thank you for your report. Please add the following information to help us identify the problem:
> 
> 1. Have you tried the latest released version, v0.106.2?
> 2. Can you [configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment?
> 
> Thanks!

Yes I tried version v0.106.2 and it have same problem too
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/6478751/log.txt)

**Comment by ainar-g** [comment]
Thanks for the log!  We've got several versions.

1.  I see that you have a lot of filters.  If you disable some of them in the config file by setting `enabled: false`, does it fix the issue?
1.  Does the machine forward requests from port 53 to AGH on port 5353?  If so, if you set the `dns.local_ptr_upstreams` parameter in the config file to either your router's address or to some other DNS upstream, does the situation improve?

**Comment by vinhlilo90** [comment]
> Thanks for the log! We've got several versions.
> 
> 1. I see that you have a lot of filters.  If you disable some of them in the config file by setting `enabled: false`, does it fix the issue?
> 2. Does the machine forward requests from port 53 to AGH on port 5353?  If so, if you set the `dns.local_ptr_upstreams` parameter in the config file to either your router's address or to some other DNS upstream, does the situation improve?

Thanks for your suggestion . Can you check this ? 
![image](https://user-images.githubusercontent.com/61305337/118276083-6f28e080-b4f1-11eb-81b3-c5447af1419d.png)

**Comment by ainar-g** [comment]
@vinhlilo90, good day.  Have you tried the workaround №1, disabling some filters?  Does the issue still persist?
