### ISSUE TITLE
[DHCP] Can't add static lease

### ISSUE THREAD

**Issue by m1s1ek** [AdguardTeam/AdGuardHome#3159]
Hardware: RPI4 
System: Docker
ADGuardHome version:  v0.106.3

When I try to add a static DHCP lease I get the error:

2021/05/19 18:40:48.664210 1#27 [debug] POST /control/dhcp/add_static_lease
2021/05/19 18:40:48.665740 1#27 [debug] web: plain: http: panic serving x.x.x.x:16813: runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
net/http.(*conn).serve.func1(0x40009ee000)
        net/http/server.go:1801 +0xfc
panic(0x7472c0, 0x13c6980)
        runtime/panic.go:975 +0x420
net.networkNumberAndMask(0x0, 0x1, 0x4000271348, 0x94e00, 0xd, 0xe, 0x4000c07021)
        net/ip.go:476 +0x20
net.(*IPNet).Contains(0x0, 0x4000c06e8c, 0x4, 0x4, 0x0)
        net/ip.go:500 +0x28
github.com/AdguardTeam/AdGuardHome/internal/dhcpd.(*v4Server).addLease(0x40000bf560, 0x40001266c0, 0x0, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/dhcpd/v4.go:287 +0x320
github.com/AdguardTeam/AdGuardHome/internal/dhcpd.(*v4Server).AddStaticLease.func1(0x40000bf560, 0x40001266c0, 0x40002715b8)
        github.com/AdguardTeam/AdGuardHome/internal/dhcpd/v4.go:378 +0x1d0
github.com/AdguardTeam/AdGuardHome/internal/dhcpd.(*v4Server).AddStaticLease(0x40000bf560, 0x0, 0x0, 0x0, 0x4000c06f80, 0x10, 0x4000c06f90, 0x6, 0x6, 0x4000c06e8c, ...)
        github.com/AdguardTeam/AdGuardHome/internal/dhcpd/v4.go:384 +0x180
github.com/AdguardTeam/AdGuardHome/internal/dhcpd.(*Server).handleDHCPAddStaticLease(0x4000454000, 0xf53c60, 0x40001ec0e0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/dhcpd/http.go:462 +0x1f0
github.com/AdguardTeam/AdGuardHome/internal/home.ensure.func1(0xf53c60, 0x40001ec0e0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:234 +0x1c8
github.com/AdguardTeam/AdGuardHome/internal/home.(*httpHandler).ServeHTTP(0x40000a2278, 0xf53c60, 0x40001ec0e0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:252 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0xf537a0, 0x400086c1c0, 0x400080e200)
        github.com/NYTimes/gziphandler@v1.1.1/gzip.go:336 +0x1d8
net/http.HandlerFunc.ServeHTTP(0x4000099c20, 0xf537a0, 0x400086c1c0, 0x400080e200)
        net/http/server.go:2042 +0x40
github.com/AdguardTeam/AdGuardHome/internal/home.optionalAuth.func1(0xf537a0, 0x400086c1c0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/auth.go:598 +0xe0
github.com/AdguardTeam/AdGuardHome/internal/home.(*authHandler).ServeHTTP(0x40001ac000, 0xf537a0, 0x400086c1c0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/auth.go:607 +0xa0
github.com/AdguardTeam/AdGuardHome/internal/home.postInstall.func1(0xf537a0, 0x400086c1c0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:354 +0xb0
github.com/AdguardTeam/AdGuardHome/internal/home.(*postInstallHandlerStruct).ServeHTTP(0x40001ac020, 0xf537a0, 0x400086c1c0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:363 +0xa0
net/http.(*ServeMux).ServeHTTP(0x40001ee940, 0xf537a0, 0x400086c1c0, 0x400080e200)
        net/http/server.go:2417 +0x190
github.com/AdguardTeam/AdGuardHome/internal/home.limitRequestBody.func1(0xf537a0, 0x400086c1c0, 0x400080e200)
        github.com/AdguardTeam/AdGuardHome/internal/home/middlewares.go:68 +0x158
net/http.HandlerFunc.ServeHTTP(0x40001cc1e0, 0xf537a0, 0x400086c1c0, 0x400080e200)
        net/http/server.go:2042 +0x40
net/http.serverHandler.ServeHTTP(0x40001980e0, 0xf537a0, 0x400086c1c0, 0x400080e200)
        net/http/server.go:2843 +0xbc
net/http.(*conn).serve(0x40009ee000, 0xf56820, 0x4000810200)
        net/http/server.go:1925 +0x6f4
created by net/http.(*Server).Serve
        net/http/server.go:2969 +0x2e8

**Comment by ainar-g** [comment]
Hello, and thanks for the report.  How did you do this request?  It looks like the server isn't configured.

**Comment by m1s1ek** [comment]
You right, I tried add dhcp leases with disabled DHCP service. I enabled it and everythings works fine :)
