### ISSUE TITLE
Runs in Recursive DNS Server mode by default?

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#3160]
### Problem Description
I'm not sure if AdGuard for Windows operates as a Recursive DNS Server by default or not.

### Proposed Solution
Explain further in wiki and other documentation.

### Alternatives Considered
I've looked into DNS servers for Windows (to act as upstream) but can't find any that run in recursive mode.

### Additional Information

== My Current DNS settings ==

Upstream DNS server : tls://dns.quad9.net

Bootstrap DNS server : 9.9.9.9

DNSSEC : Enabled

**Comment by ameshkov** [comment]
AdGuard is a DNS forwarder, not a recursor.

I don't think it makes sense to add anything to the documentation. The mere need to set DNS upstream tells that AGH forwards queries and not goes through the recursion.

Regarding the recursor setup, if you are really sure that's what you need, consider running a local unbound instance and configure AGH to use it as an upstream. IMO, this does not provide any advantages, though. Mind that the queries that are made by a recursor are not encrypted so will be visible to your ISP.
