### ISSUE TITLE
Unable to block client when configured though clientID

### ISSUE THREAD

**Issue by Final-Hawk** [AdguardTeam/AdGuardHome#3162]
### Prerequisites
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ]  I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
   v0.106.3
* **How did you install AdGuard Home:**
  Raspberry pi install script, not docker
* **How did you setup DNS configuration:**
  iOS Profile/router/manual on device
* **CPU architecture:**
  armv7l
* **Operating system and version:**
  * Raspberry pi OS lite

### Expected Behavior
When on the main Adguard screen, under client you can hover over a client and block them. This drops all of their dns requests.

### Actual Behavior
When setup via a client ID, the block button does not appear.

### Screenshots
Setup via local IP address, block button shows:
![image](https://user-images.githubusercontent.com/63589370/118967603-451e6500-b9ae-11eb-8515-e9ab768cefa2.png)

Setup via client ID for DNS over HTTPS on ios configuration, block button does not show: (i am hovering over it)
![image](https://user-images.githubusercontent.com/63589370/118967675-59faf880-b9ae-11eb-885d-f3acff56c5c8.png)

**Comment by ainar-g** [comment]
Related issue: #2624.  It seems like there are several things at play here, so the issue won't be a straightforward one.  We'll still try to implement it in the v0.107 cycle though.

**Comment by ainar-g** [comment]
This feature is implemented on the `edge` channel as of snapshot e08a64e.  Can you please check if it works for you?

**Comment by Final-Hawk** [comment]
Awesome. Thanks! Seems to all be working now.
