### ISSUE TITLE
Windows version, about auto updating in usage

### ISSUE THREAD

**Issue by tbelbek** [AdguardTeam/AdGuardHome#3165]
Hello,

I created a powershell script to auto update my adguard running as a windows service. I gave the Windows 64bit link in here;

![image](https://user-images.githubusercontent.com/9684414/119216127-709e6e00-bada-11eb-9f18-1c2db1646349.png)

But this link goes to v0.106 version, not the latest one. For auto updating purposes, could you also keep the links on the main page updated?

Thank you for your support.

**Comment by ainar-g** [comment]
Sorry for the long silence.  The latest release version is v0.106.3.  After that, we have only released beta versions for v0.107.0.  Are you sure that it's not your browser's cache?
