### ISSUE TITLE
Bad request error on DoH

### ISSUE THREAD

**Issue by elcidowneador** [AdguardTeam/AdGuardHome#3167]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-a.34+6f7fd33a
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * ARM
* **Operating system and version:**
  * QTS 4.5.3

### Expected Behavior
```
curl -k -H "accept: application/dns-json" "https://xxxxxxx:1069/dns-query?name=example.com&type=AAAA"
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"example.com","type":28}],"Answer":[{"name":"example.com","type":28,"TTL":86400,"data":"2606:2800:220:1:248:1893:25c8:1946"}]}
```

### Actual Behavior
```
curl -k -H "accept: application/dns-json" "https://xxxxxxx:1069/dns-query?name=example.com&type=AAAA"
Bad Request
```

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information
I am not able to make work AdGuard Home with DoH. Tried `edge` and `latest` channel with no luck.

This is the error i was able to see after enabling debug:

```
2021/05/22 22:42:06.745612 1#804 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).ServeHTTP(): Incoming HTTPS request on /dns-query?name=www.google.es&type=A


2021/05/22 22:42:06.746022 1#804 [debug] net/http.StatusText(): Cannot parse DNS request from 


2021/05/22 22:42:08.046737 1#811 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).ServeHTTP(): Incoming HTTPS request on /dns-query?name=www.google.es&type=A


2021/05/22 22:42:08.047364 1#811 [debug] net/http.StatusText(): Cannot parse DNS request from 
```

**Comment by ameshkov** [comment]
You're sending not a DOH query. Rather you're using some custom JSON protocol similar to what Google DNS provides.

If you want to test DOH queries, use kdig or [dnslookup](https://github.com/ameshkov/dnslookup)
