### ISSUE TITLE
[FR] Add an option to exclude PTR, SRV queries in statistics dashboard

### ISSUE THREAD

**Issue by SukkaW** [AdguardTeam/AdGuardHome#3169]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

RT.

![image](https://user-images.githubusercontent.com/40715044/119242006-127e9300-bb8d-11eb-9691-06b698527d93.png)

### Proposed Solution

Added an option to exclude all PTR, SRV queries.

### Alternatives Considered

Add a filter feature for statistics to make it possible to exclude them out.

E.g. Cloudflare analytics dashboard:

![image](https://user-images.githubusercontent.com/40715044/119242055-7608c080-bb8d-11eb-86bb-d258814a836b.png)

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/1717

Good UI reference, thank you!
