### ISSUE TITLE
Comparison page with Pi-Hole is missing "per client device" configuration

### ISSUE THREAD

**Issue by thewavelength** [AdguardTeam/AdGuardHome#3170]
In https://github.com/AdguardTeam/AdGuardHome/wiki/Comparison the table is outdated and shows that Pi-Hole can't handle per client device configuration. In https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md it is corrected already.

**Comment by ameshkov** [comment]
Done, thank you
