### ISSUE TITLE
Disable Protection Timer

### ISSUE THREAD

**Issue by sachinwadhwa** [AdguardTeam/AdGuardHome#3171]
One thing I really miss moving from Pi-hole is disable timer, which allows user to disable protection for certain time.

When, I have disable protection for testing or enabling click throughs, mostly I forgot to re-enable it until I realised ad start to appear again. Similar to Pi-hole it will be great to have feature to disable protection for a duration.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/1333
