### ISSUE TITLE
Please update the link of anti-ad in the default list.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#3174]
AG home wrongly uses https://anti-ad.net/easylist.txt.

https://anti-ad.net/
It should use one of these:
https://anti-ad.net/adguard.txt
https://anti-ad.net/domains.txt

**Comment by MEDict** [comment]
Don't be troublesome. As for AdGuardHome, easylist.txt is the adequate block list. The adguard.txt is a list adapted for AdGuard program. The domains.txt is for other DNS-based tracker like Pi-Hole.
![image](https://user-images.githubusercontent.com/10000094/119342215-4fe73b80-bcc7-11eb-9839-c7d821d405fe.png)

**Comment by ameshkov** [comment]
@MEDict thanks for explanation!

**Comment by lancelot-moon** [comment]
According to that screenshot above, https://anti-ad.net/adguard.txt solves incorrect blocking in easylist.
It seems that AdGuard.txt includes easylist.txt for anti-ad and even more rules.
