### ISSUE TITLE
Enabling Safe Search disables service

### ISSUE THREAD

**Issue by dclark16** [AdguardTeam/AdGuardHome#3177]
* **Version of AdGuard Home server:**
  *  v0.106.3
* **How did you install AdGuard Home:**
  Straight from the install script on Github
* **How did you setup DNS configuration:**
  Router is configured to route DNS queries to Ad Guard Home
* **If it's a router or IoT, please write device model:**
  Netgear D6400, Ad Guard is running on Ubuntu Server on a Pi4
* **CPU architecture:**
  ARM64
* **Operating system and version:**
  Ubuntu 21.04 - Fully patched
  Also Tried Manjaro

### Expected Behavior
When enabling Safe search for Youtube, Google etc the respective sites should forward to a safe-search version

### Actual Behavior
Devices fail to resolve IP address for the services, I.E Youtube.com fails to load at all.

### Screenshots
![image](https://user-images.githubusercontent.com/84709493/119327074-8054b880-bc7a-11eb-9120-9db129ac74c1.png)
![image](https://user-images.githubusercontent.com/84709493/119327110-88acf380-bc7a-11eb-966b-f81f86c2e881.png)
![image](https://user-images.githubusercontent.com/84709493/119327129-8cd91100-bc7a-11eb-8fd7-048b8992f5ee.png)

## Additional Information
Disabling the safe search feature results in sites working again. I've tested this at the Global level and per device level to the same result.

**Comment by ameshkov** [comment]
Cannot reproduce this.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by dclark16** [comment]
From the verbose log file I spotted that the Pi isn't listening on port 127.0.0.1:53, I've manually configured the Network adapter to resolve to the Pi's IP, Is there a way to change how AdGuard Home binds ports? Or should it have bound to 0.0.0.0:53 at install?

**Comment by dclark16** [comment]
Wow I must have had my stupid head on this morning! I've not disabled the Ubuntu systemd-resolve, will try this later and attempt to fix the AdGuard Home config file to bind 0.0.0.0:53
