### ISSUE TITLE
landline telephone does not work anymore with AG home

### ISSUE THREAD

**Issue by Sylvio82** [AdguardTeam/AdGuardHome#3178]
### Issue Details
Since installing Adguard Home on my Raspberry Pi zero w my landline telephone (I hope this is the correct english word) does not work anymore. Neither incoming nor outgoing calls. Even if I disable he protection in AG home nothing changes.

This must have something to do with the DNS server, because if I e.g. set a cloudlare dns server in my router then there is the same problem. If I set google dns server in my router it does work!

* **Version of AdGuard Home server:**  0.106.3

* **How did you install AdGuard Home:** raspberry pi zero w (raspberry pi os lite)

* **How did you setup DNS configuration:** rouer: draytek vigor2760 (primary and secondary dns server set to raspberry)

**Comment by ainar-g** [comment]
Hi and thank you for your report.  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment?

Thanks.

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by attinderdhillon** [comment]
I have the same issue with cloudflare DNS and VoWifi ( Jio network - India ), Works fine with Google and OpenDNS.
Had the same issue with PiHole and cloudflare.

The problem seems to be with Cloudflare.

**Comment by Sylvio82** [comment]
Ok, seems that my internet provider has a problem. My neighbor hast the same disruption with his telephone. 
I hope tomorrow I can say more.

@attinderdhillon
yes, with cloudflare and adguard dns server in the router I had these problems too. Pi-Hole was fine. Very strange...:)

**Comment by Sylvio82** [comment]
The disruption with my telephone is gone. Everythings seems fine. Sorry for the panic ;)
