### ISSUE TITLE
Local DNS resolution not working since v0.106

### ISSUE THREAD

**Issue by grayfrost90** [AdguardTeam/AdGuardHome#3181]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * via tutorial for raspberry pi install
* **How did you setup DNS configuration:**
  * from DHCP
* **If it's a router or IoT, please write device model:**
  * RPi Model 4B
* **CPU architecture:**
  * 
* **Operating system and version:**
  * Raspberry Pi OS Lite 32bit

### Expected Behavior
performing a lookup for hostname.lan should resolve

### Actual Behavior
does not resolve - Non-existent domain

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information
prior to 0.106 I had the following additional upstream servers in my DNS config:
[/lan/]192.168.1.1
[/168.192.in-addr.arpa/]192.168.1.1

this meant that resolution for *.lan addresses worked as did reverse lookups. I've now replaced this with the new private DNS servers - adding 192.168.1.1 (router) and ticking the 'Enable reverse resolving of clients' IP addresses'

reverse resolution works as expected, but not normal resolution. I've tried removing the new 0.106 functionality and running as I used to but this doesn't work either. The query logs are either empty, or in the case of my work device, now have the work domain added in to the FQDN as well.

**Comment by ainar-g** [comment]
Hi, and thanks for the report.  Do you still have `[/lan/]192.168.1.1` in your upstreams?  If AGH is your DHCP server, you can probably try and remove it.  Otherwise, it should remain there.

**Comment by grayfrost90** [comment]
I commented out the [/lan/]192.168.1.1 and [/168.192.in-addr.arpa/]192.168.1.1 lines after upgrading to 0.106. I have 3 subnets on my LAN at the moment, two of which get their DHCP from the router (work & iot) and the home gets it's addresses from Adguard. I do need to tidy that up at some point, but I can't get it to work with any combination of settings in the config

**Comment by ainar-g** [comment]
That's weird.  Can you [configure] AdGuard Home to collect logs and post the
logs here as an attachment?

Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by thewavelength** [comment]
I think I have the same issue. It seems to be random, not really reproducible. Sometimes I can reach the server where AGH is running (`base.php` - local domain name is set to `.php`) and sometimes I can't. DNS rewrites don't seem to work at all. I don't know what causes this. I created a log file where this is happening. Can I send you the debug log + configuration privately somehow? It seems to contain sensitive data.

**Comment by grayfrost90** [comment]
Hi @ainar-g, I've got the log file but there's a lot of info in there that I'm not sure I want to post up here (?) is there a specific bit you need or a way to post it privately?

**Comment by ainar-g** [comment]
@grayfrost90, you can send the logs to devteam@adguard.com, and please add the words “AdGuard Home Issue 3181” to the subject line.  Thanks!

**Comment by ainar-g** [comment]
We have received the logs, thanks!  We'll try to analyse them in the nearest couple of days.

**Comment by ssrahul96** [comment]
I ve the save issue, i can confirm that before 0.106.3 it was working fine
![image](https://user-images.githubusercontent.com/15570570/121795163-c7a3e880-cc2b-11eb-90f7-177fcb6d16d8.png)

In dashboard also the ip are not resolved
![image](https://user-images.githubusercontent.com/15570570/121795174-e99d6b00-cc2b-11eb-829c-6893017d42bd.png)


Additionally,
I used to get entries in Client (Runtime), its also missing after the update

**Comment by grayfrost90** [comment]
hi @ainar-g has there been any progress on this?

**Comment by ainar-g** [comment]
@grayfrost90, hi, and sorry for the long time with no news.  Have you tried the following configuration:

1.  In your “Upstream DNS servers” input, leave your current upstream **and** ` [/lan/]192.168.1.1`.
2.  In your “Private reverse DNS servers” input, leave **only** `192.168.1.1`.

**Comment by grayfrost90** [comment]
i'll give it a go, thanks!

**Comment by ssrahul96** [comment]
> @grayfrost90, hi, and sorry for the long time with no news. Have you tried the following configuration:
> 
> 1. In your “Upstream DNS servers” input, leave your current upstream **and** ` [/lan/]192.168.1.1`.
> 2. In your “Private reverse DNS servers” input, leave **only** `192.168.1.1`.

Its working fine after i updated the entry in private DNS

**Comment by grayfrost90** [comment]
I've tried a number of combinations and it's still not working. It isn't a massive issue as there's only a couple of things I need to access internally via DNS and I can use IPs instead, just annoying that it did work.

**Comment by ainar-g** [comment]
I honestly have no idea what else could be wrong there.  Could you please provide a list of queries that fail with the configuration that I've mentioned?  For example with `nslookup` or `dig`?

**Comment by grayfrost90** [comment]
Hi @ainar-g. I kind of gave up with this but I was playing around tonight and changed my local lookups to use a different domain name - instead of .lan - and that works fine. So it seems that using .lan is the problem. I've reconfigured everything to use .localhost and this is working as it was pre 106. I seem to recall reading some bits about the default local domain name in Adguard being .lan but you will be able to set it to anything you like soon (or maybe you can now?) perhaps that's causing the issue?

anyway, for my small need this seems to have resolved the local lookups, but thought you might be interested.

thanks for your help
