### ISSUE TITLE
Ability to disable private PTRs completely

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#3184]
A lot of people seem to be under the impression that the “Enable reverse resolving of clients' IP addresses” checkmark is supposed to disable private PTR requests, which it doesn't.  It's probably because of the UI design flaw: since it's close to the Private DNS servers input, people think that it's related.  We should:

1.  Add an **actual** checkmark to disable private PTR requests and make them return `NXDOMAIN`.
2.  Make it clearer in the UI that the current checkmark has more to do with clients than it is to upstreams.  It will probably disappear or become a different input either way in #3020.

This should be solved early in the v0.107 cycle, so that we have it in early betas.  There seems to be decent demand for this.

**Comment by DandelionSprout** [comment]
`||192.168.$important,dnstype=PTR` should be able to do this already.

**Comment by Omoeba** [comment]
I currently have the following rules to handle PTR queries.

```
||168.192.in-addr.arpa^$important,dnstype=PTR,dnsrewrite=NXDOMAIN;;
||254.169.in-addr.arpa^$important,dnstype=PTR,dnsrewrite=NXDOMAIN;;
||10.in-addr.arpa^$important,dnstype=PTR,dnsrewrite=NXDOMAIN;;
/((3[0-1])|(2[0-9])|(1[6-9]))\.172\.in-addr\.arpa$/$important,dnstype=PTR,dnsrewrite=NXDOMAIN;;
||127.in-addr.arpa^$important,dnstype=PTR,dnsrewrite=NOERROR;PTR;localhost
||0.8.e.f.ip6.arpa^$important,dnstype=PTR,dnsrewrite=NXDOMAIN;;
||d.f.ip6.arpa^$important,dnstype=PTR,dnsrewrite=NXDOMAIN;;
```

Link-local and private addresses return `NXDOMAIN` and `127.0.0.1/8` returns `localhost`.
