### ISSUE TITLE
Better detection of request recursion

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#3185]
The two mechanisms that were proposed by our dev team are:

1.  Compare client IPs to the list of known upstreams.  This is easy, but doesn't work in situations where there are more than two hops.
2.  Have a LRU map of IDs of requests, along with information like query type and domain.  A bit more complex, but provides better overall support.

I personally think that we should go with option two.  @ameshkov, do you have anything to add?

**Comment by EugeneOne1** [comment]
The second option (i.e. LRU cache) have been chosen and implemented in 48b8579.

**Comment by ameshkov** [comment]
The way it's implemented is dangerous.

This is completely normal to receive DNS queries with the same ID, DNS clients retransmit the same query when they do not receive the response in N seconds (timeout is implementation-specific).

Consider this point: we are **only** interested in the recursion when the query is sent to "Private reverse DNS servers". We are not interested in other cases.
