### ISSUE TITLE
Per-client upstream not working if identify by DOH

### ISSUE THREAD

**Issue by moolex** [AdguardTeam/AdGuardHome#3186]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [y] I am running the latest version
- [y] I checked the documentation and found no answer
- [y] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * RouterOS
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * RancherOS

### Expected Behavior
Per client upstream should works by identify (IP address or special clientID from DOH)

### Actual Behavior
Per client upstream not working if identify by DOH clientID (but works with IP address)

**Comment by ainar-g** [comment]
Thanks for the report!  We'll try to fix it in the next few days.

**Comment by ainar-g** [comment]
@moolex, this should be fixed as of `edge` snapshot 3be783bd.  Can you please check if upstreams are now selected properly?  Thanks!

**Comment by moolex** [comment]
> @moolex, this should be fixed as of `edge` snapshot [3be783b](https://github.com/AdguardTeam/AdGuardHome/commit/3be783bd3418f3c51f388e67ad8388361a8670ea). Can you please check if upstreams are now selected properly? Thanks!

Sorry for late response, I can make sure it works as expect, Thanks!
