### ISSUE TITLE
Spread lists update throughout the day to avoid memory hit

### ISSUE THREAD

**Issue by NicoLeOca** [AdguardTeam/AdGuardHome#3193]
Hi,

I try to use quite a significant number of lists on a raspberry 3B+ as a secondary instance.
My primary Nuc bears with the lists well.
But when the Pi tries to update all the lists, apparently at the same time; the AGH install just breaks because of the extensive memory usage. if I install AGH with docker, docker stops the containers too.

I had a look on reddit and the high memory usage during update is known.
What do you think about my workaround?

Thank you

**Comment by ainar-g** [comment]
When #3044 is done, this should be solved as well, so we'll merge this issue into that one.  Perhaps we can add an “auto” option for that there.  Thanks!

**Comment by NicoLeOca** [comment]
thank for the answer
