### ISSUE TITLE
How to configure browsing security / parental control with HTTPS?

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#3197]
When these services are enabled and one visits a blacklisted website, we get a pretty page like this:

![image](https://user-images.githubusercontent.com/96476/119822400-84d3d800-beeb-11eb-8d5f-ee7be116a294.png)

But if the blacklisted website being access with HTTPS, first I'll get this:

![image](https://user-images.githubusercontent.com/96476/119822555-b056c280-beeb-11eb-86e1-c7aa915d9410.png)

Is it possible to configure AdGuard Home to show those pretty pages in HTTPS, so that one doesn't get the "secure connection not available" message, or is this not possible at all?

**Comment by ainar-g** [comment]
I don't think that it's currently possible, unless your network is already MITM'd.  There are some RFCs that, if accepted and implemented, could signal to the browser that a domain has been blocked (see https://github.com/AdguardTeam/AdGuardHome/issues/3176#issuecomment-846950950), but until they are, we'll probably not be able to signal that when accessing HTTPS pages.

I'll merge this issue into #3176, if you don't mind.
