### ISSUE TITLE
Incorrect permissions assigned to filters.txt files

### ISSUE THREAD

**Issue by gabrielwhite** [AdguardTeam/AdGuardHome#3198]
### Issue Details

* **Version of AdGuard Home server:**
v0.106.3

* **How did you install AdGuard Home:**
Docker

* **CPU architecture:**
ARM64

* **Operating system and version:**
Armbian 21.05.2 Buster with Linux 5.10.34-meson64

### Expected Behavior

I would expect the nnnnnnnnn.txt files created in work/data/filters to have 744 permissions.

### Actual Behavior

All the files created by adguardhome in conf and work have 744 permissions, EXCEPT for the nnnnnnnnnn.txt files in work/data/filters which are created with 700 permissions.

This causes problems for my backup program as it can't read the files.

**Comment by ainar-g** [comment]
Thanks for the report.  There are a few places where permissions are a bit weird.  We'll inspect them and change them if necessary in the next few days.

**Comment by ainar-g** [comment]
This should be changed as of `edge` build f3687104.  Can you please see if that works for you?

**Comment by gabrielwhite** [comment]
Yes, that works. Thanks! For what it's worth it only changes the incorrect old permissions to the new permissions on download of a new ruleset (the rulesets without updates didn't change their permissions). But I guess that's a short term problem in most cases.

**Comment by ainar-g** [comment]
Yes, they should be overwritten later.  We'll close this issue for now, thanks for testing!
