### ISSUE TITLE
Use backslash(\) instead of slash(/) to escape quotes in the client name 

### ISSUE THREAD

**Issue by Jinsung-L** [AdguardTeam/AdGuardHome#3201]
https://github.com/AdguardTeam/AdGuardHome/blob/69f526b13d1f553dfcd3e3bad363c2ac148bef54/client/src/actions/index.js#L624

According to the documentation, it says 

> If the client name contains quotes, use \ to escape them.

https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client

So the code should be

```javascript
const baseRule = `||${domain}^$client='${client.replace(/'/g, '\\\'')}'`; 
```

**Comment by ameshkov** [comment]
Oh, thanks for noticing this!
