### ISSUE TITLE
DNS Statistics

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardHome#3213]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
Unable to view which DNS Resolver is working the most efficiently

### Proposed Solution
Have a statistic page where you can view how many queries each listed DNS Resolver has actioned and the average processing time etc.

### Alternatives Considered
N/A

### Additional Information

Hi,

I want to suggest a feature/idea.

Can we get a statistics page for the upstream servers and bootstrap servers please?

I would like it to show how many queries each upstream and bootstrap servers have served and what the average response time is for each server.

Kind regards,
A happy AdGuard User

**Comment by ainar-g** [comment]
Looks like a dup of #2013.
