### ISSUE TITLE
AdGuard Home stopped responding and Raspberry PI had to be restarted

### ISSUE THREAD

**Issue by twennywonn** [AdguardTeam/AdGuardHome#3218]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

I am a new user to Adguard Home as of last night.  I freshly installed AGH on a raspberry pi 4 and everything was great.  At 9:17 this morning I noticed all my devices were not connected to the internet.  I tried navigating to the IP address and the GUI would not load.  I pulled the power from my Raspberry PI and this solved the issue.

* **Version of AdGuard Home server:**
  * v0.106.3 
* **How did you install AdGuard Home:**
  * Through putty by pasting in commands
* **How did you setup DNS configuration:**
  *My UDMP DHCP DNS points to my Raspberry PI which is on a static IP then AGH forwards to quad 
* **Unifi Dream Machine:**
  *Raspberry Pi 4 
* **CPU architecture:**
  * 
* **Operating system and version:**
  *Raspberry Pi OS

### Expected Behavior
Stable with no hangups 

### Actual Behavior
About 12 hours after install AGH became unresponsive and had to be power cylced

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1049" alt="Screen Shot 2021-06-01 at 10 27 31 AM" src="https://user-images.githubusercontent.com/24308598/120350077-46139880-c2c4-11eb-84a3-6e5cec137d2a.png">

</details>

**Comment by ainar-g** [comment]
Hello and thank you for your report.  Could you please [configure] AGH to make verbose logs and post the log here as an attachment?  Also, we have released the first beta version of the next release, which has more settings that could help you, so you could also try that.  Thanks.

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by twennywonn** [comment]
I'm sorry for my ignorance but I don't know how to do that stuff.  It looks
like I would do it in SSH?

**Comment by ainar-g** [comment]
Yes, you need to access the machine, find the configuration file, edit it, and restart AdGuard Home.  On Linux, it is usually installed at `/opt/AdGuardHome`, so the configuration file will probably be at `/opt/AdGuardHome/AdGuardHome.yaml`.  There you can also configure it to write the logs into a file, if you want that.  See our Wiki page about [configuration], especially the “Log settings” part.

[configuration]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration
