### ISSUE TITLE
Whitelists not affecting subdomains

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3221]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* Version of AdGuard Home server: 0.106.3
* How did you install AdGuard Home: GH Releases
* How did you setup DNS configuration: N/A
* If it's a router or IoT, please write device model: N/A
* CPU architecture: N/A
* Operating system and version: N/A

### Expected Behavior

When a whitelist has a following format, it should automatically apply to all subdomains.

```
akamaihd.net
```

Meaning `cdn.akamaihd.net` should also be allowed, except it does not.

### Actual Behavior

Subdomains are getting blocked, since they exist in a blocklist.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/19761269/120453310-8ea88000-c3b0-11eb-89b3-54b4cf38242b.png">

Is there a priority between blocklists, whitelists and custom rules that could be affecting this?

**Comment by TheCeet** [comment]
When you read the filter rules info, you'll need to make it like:
`@@||akamaihd.net`
See: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#examples
