### ISSUE TITLE
Show whitelisted domains contain on blocklists in different color than to green in querylog 

### ISSUE THREAD

**Issue by itsnotsaved** [AdguardTeam/AdGuardHome#3234]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ainar-g** [comment]
Hi, and thanks for the suggestion.

@ameshkov, is this something that we want to do in the new UI?

**Comment by ameshkov** [comment]
@itsnotsaved could you please explain what's the reason for this FR?

**Comment by itsnotsaved** [comment]
It help to see if i have whitelisted domains for temporally purposes (but forgotten) and when they're keep connecting. i think this https://github.com/AdguardTeam/AdGuardHome/issues/1203 FR better than this.
