### ISSUE TITLE
Lint function via CLI

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#3238]
Hello,

please consider about to add lint function via CLI because sometimes the conf file is very big and too hard to understand what is wrong there. `nginx -t` is a good sample!

Thank you.
Cheers😚

**Comment by ainar-g** [comment]
Hello.  Do you mean the already available `./AdGuardHome --check-config`?

See https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments.

**Comment by ammnt** [comment]
@ainar-g, omg! Yes, I am too ancient a user and before, probably, this function was not😆Thanks anyway!
