### ISSUE TITLE
HTTP security headers

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#3240]
Hello,

please consider to add some appropriate HTTP headers for the frontend and DoH endpoints:
1. Strict-Transport-Security
2. Public-Key-Pins
3. Content-Security-Policy
4. X-Content-Type-Options
5. X-Xss-Protection
6. Last-Modified
7. Cache-Control
8. X-Frame-Options
9. X-Robots-Tag
10. Referrer-Policy
11. Permissions-Policy
12. X-Permitted-Cross-Domain-Policies
13. Expect-CT
etc.

Thank you.
Cheers😚

**Comment by ameshkov** [comment]
I don't think we should simply add random HTTP headers without any justification.

1. Adding any header like that on our side can break existing AGH deployment.
2. If anyone needs to stricter security and add additional headers like that, it is always possible to configure a reverse proxy like nginx or caddy in front of AGH. This is actually the recommended way.

And we definitely should not add them to DOH responses, these headers are not supposed to be used with DOH.
