### ISSUE TITLE
Manual for Docker installation must be corrected?

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#3241]
Hello,

1. You forgot to add DoQ port here:
https://github.com/AdguardTeam/AdGuardHome/wiki/Docker

```
docker run --name adguardhome \
    -v /my/own/workdir:/opt/adguardhome/work \
    -v /my/own/confdir:/opt/adguardhome/conf \
    -p 53:53/tcp -p 53:53/udp \
    -p 80:80/tcp -p 3000:3000/tcp \
    -p 67:67/udp -p 68:68/tcp -p 68:68/udp \
    -p 443:443/tcp \
    -p 853:853/tcp \
    -d adguard/adguardhome
```

2. I'm sure you need to add autostart command for the container:
https://docs.docker.com/config/containers/start-containers-automatically/

Please, take a look.

Thank you.
Cheers😚

**Comment by ainar-g** [comment]
@ammnt, we've updated the Docker page.  Can you take a look and tell us if something is still missing?

**Comment by ammnt** [comment]
@ainar-g, looks really better now! Thank you and have a nice holidays!😇
