### ISSUE TITLE
Removing leases.db unsets client-requests data

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3242]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Environment

* **Version of AdGuard Home server:** 0.106.3
* **How did you install AdGuard Home:** GH Releases
* **How did you setup DNS configuration:** AGH DHCP
* **If it's a router or IoT, please write device model:** 
* **CPU architecture:** arm64
* **Operating system and version:** Ubuntu 20.04

### Issue Details

I had to remove `leases.db` because a certain DHCP client's hostname was showing up blank. 

After I started up AGH, the client's hostname was correctly visible

However, after I renewed leases on a few devices, I noticed that Top Clients was showing incorrect data for hostnames.

### Expected Behavior

Historical queries would get mapped correctly to the client.

Is there a way I can rectify this at this time?3

**Comment by ainar-g** [comment]
Hi.  Unfortunately I don't think that this is currently possible, as these statistics are joined to the data from the leases database.  Such situations should become less frequent once we find a better storage format in #2290.

**Comment by agneevX** [comment]
Ah ok! As of now, how are queries mapped to clients?

If it's dynamic, I'm not sure why it can't be mapped, unless AGH tends to give the same DHCP IP to clients?

**Comment by ainar-g** [comment]
They are mapped by ClientID and, if there is none, by IP address.  So, if your DHCP clients receive a different IP address, the stats won't be accurate.  Creating clients by MAC would fix it, but our current stats don't know anything about MAC, unfortunately.  Most of these issues should get solved once we have a better database.

I'll close this issue, if you don't mind, as there is little we can do here at the moment.  Apologies for the inconvenience!
