### ISSUE TITLE
More access control options

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#3243]
Hello,

please consider to add more access control options:
1. Add, remove and disable users;
2. Password changes and disable it;
3. IP and subnet restrictions (incl. access only from local networks or via unique url maybe, idk);
4. Session frame time options (web_session_ttl?);
5. Disable authorization entirely?
etc.

Thank you.
Cheers😚

**Comment by ainar-g** [comment]
Merging into #997.
