### ISSUE TITLE
cpu spikes every 5-10 seconds when using router to resolve lan addresses

### ISSUE THREAD

**Issue by shmizan** [AdguardTeam/AdGuardHome#3255]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Using the Windows binary, installed as service
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 10 x64

### Expected Behavior
Service should run without cpu spikes every 5-10 seconds when using router to resolve lan addresses

### Actual Behavior
Service runs and has cpu spikes every 5-10 seconds when using router to resolve lan addresses

### Additional Information
I use the following upstream servers:
```
https://dns.google/dns-query
https://dns10.quad9.net/dns-query
[/lan/]192.168.1.1
```
`192.168.1.1` is my router and the suffix is set to `.lan`.
if this line ([/lan/]192.168.1.1) is added, then the cpu usage of AdguardHome.exe spikes to 5-8% every 5-10 seconds, even with little to none "dns activity" (e.g. the query log is barely updating with queries).
I set Windows' Resource Monitor to monitor the exe cpu usage overnight and this is how it looks:
```
"(PDH-CSV 4.0) (Daylight Time)(-180)","\\VN-PC\Process(AdGuardHome)\% Processor Time"
...
"06/09/2021 03:24:52.311","0"
"06/09/2021 03:24:53.303","0"
"06/09/2021 03:24:54.309","0"
"06/09/2021 03:24:55.324","0"
"06/09/2021 03:24:56.324","20.32014037278016616"
"06/09/2021 03:24:57.310","42.781729668753044393"
"06/09/2021 03:24:58.312","0"
"06/09/2021 03:24:59.301","0"
"06/09/2021 03:25:00.308","0"
"06/09/2021 03:25:01.314","0"
"06/09/2021 03:25:02.308","0"
"06/09/2021 03:25:03.316","0"
"06/09/2021 03:25:04.309","0"
"06/09/2021 03:25:05.300","0"
"06/09/2021 03:25:06.314","20.031091211999108026"
"06/09/2021 03:25:07.307","37.747369838764370797"
"06/09/2021 03:25:08.313","0"
"06/09/2021 03:25:09.307","0"
"06/09/2021 03:25:10.312","0"
"06/09/2021 03:25:11.302","0"
"06/09/2021 03:25:12.308","0"
"06/09/2021 03:25:13.322","1.5417135388694844789"
"06/09/2021 03:25:14.310","0"
"06/09/2021 03:25:15.301","0"
"06/09/2021 03:25:16.315","20.038218864011302145"
"06/09/2021 03:25:17.314","9.384054674355285286"
"06/09/2021 03:25:18.301","30.061425047741341388"
"06/09/2021 03:25:19.307","0"
"06/09/2021 03:25:20.317","0"
"06/09/2021 03:25:21.310","0"
"06/09/2021 03:25:22.312","0"
"06/09/2021 03:25:23.301","0"
```
in the task manager it shows up at around 5-8%, and procmon has somewhat bigger numbers, not sure what's the real value, but the issue is clear anyway.

if I remove "[/lan/]192.168.1.1" from the upstream servers, I don't see this behavior.
if I remove it and instead use dns rewrites of the local clients, I see this behavior again.

I couldn't find any client or program that's causing it.
any help would be appreciated.

**Comment by ainar-g** [comment]
Hello and thank you for your report.  Is there any weird activity in the Query Log at that time?  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment?  Also, if you could test if the issue is still broken in the recent beta version, v0.107.0-b.1, that would be great.  Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by shmizan** [comment]
thanks for looking into this!
I tried updating to the latest beta version that you mentioned, it's still displaying the same behavior.
I've provided 4 files in 2 groups:
AGH verbose log with Resource Monitor reading while `[/lan/]192.168.1.1` is active:
[log_with_issue.log](https://github.com/AdguardTeam/AdGuardHome/files/6639860/log_with_issue.log)
[DataCollector01_with_issue.txt](https://github.com/AdguardTeam/AdGuardHome/files/6639852/DataCollector01_with_issue.txt)

AGH verbose log with Resource Monitor reading while `[/lan/]192.168.1.1` is **IN**active:
[log_without_issue.log](https://github.com/AdguardTeam/AdGuardHome/files/6639853/log_without_issue.log)
[DataCollector01_without_issue.txt](https://github.com/AdguardTeam/AdGuardHome/files/6639854/DataCollector01_without_issue.txt)

**Comment by ainar-g** [comment]
Thank you for the logs!  We will be looking into it in the next few days.

**Comment by ainar-g** [comment]
Just as a quick thought: I assume that `192.168.1.1` is your network's router?  Can you try putting it into the “Private reverse DNS servers” field and make sure that the “Use private reverse DNS resolvers” checkmark is checked?  You can also try unchecking the “Enable reverse resolving of clients' IP addresses” checkmark.

**Comment by shmizan** [comment]
unfortunately it doesn't make a difference, the cpu usage is still high every 10 seconds (or less).

**Comment by shmizan** [comment]
problem found:
the logs showed this every 10 seconds:
```
2021/06/12 11:50:33.480470 9576#138 [debug] GET /control/status
2021/06/12 11:50:33.540475 9576#138 [debug] GET /control/filtering/status
2021/06/12 11:50:33.601495 9576#138 [debug] GET /control/parental/status
2021/06/12 11:50:33.662475 9576#138 [debug] GET /control/safebrowsing/status
2021/06/12 11:50:33.724468 9576#138 [debug] GET /control/safesearch/status
```
and `GET /control/filtering/status` shows up in the documentation as an API request.
I have Home Assistant with AdGuard Home integration running and it looks like these API calls are generated from that integration.
sorry for the goose chase, I'll close the issue for now (unless you think that the CPU usage for these api calls is too much)
