### ISSUE TITLE
Set up DHCP failed when setting static ip by cloud-init

### ISSUE THREAD

**Issue by conghuayu** [AdguardTeam/AdGuardHome#3257]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * install.sh (with root privilege)

AdGuardHome -v --version output:
https://pastebin.ubuntu.com/p/fwZqBztMY5/

### Expected Behavior
set up DHCP server

### Actual Behavior
return an errbox "Error: control/dhcp/set_config | enabling dhcp: setting static ip: open /etc/dhcpcd.conf: no such file or directory | 500"

### Screenshots
<details><summary>config:</summary>

![C0EF244D-8A02-4A1C-B3A1-231791B6ACB0](https://user-images.githubusercontent.com/26649570/121781379-648c6480-cbdf-11eb-8305-d92b52e21e25.png)

</details>

<details><summary>err box:</summary>

![7B0AF308-ABF4-4CC0-92EE-AFFDC9CBDA25](https://user-images.githubusercontent.com/26649570/121781404-81289c80-cbdf-11eb-8a0b-b320b1b4f8c6.png)

</details>

### Details

I use Proxmox VE as virtual environment and run AGH on a Debian 10.9.0 with 2 cores  and 1GB ram vm.
Gateway is a router(R6850) and the ip address is 10.0.0.1 
According to the document, static ip is needed when using AGH, so I give it a static ip by cloud-init. (in this case which is 10.0.1.3 and the netmask is 22)

But cloud-init configure the ip address by adding a config file to `/etc/network/interfaces.d/50-cloud-init`
[content of 50-cloud-init](https://pastebin.ubuntu.com/p/S8V9kp4b4T/)
rather than directly rewrite the `/etc/network/interfaces`
[content of interfaces](https://pastebin.ubuntu.com/p/Kzh4jd7jHZ/)

So maybe DHCP process only check the `/etc/network/interfaces` and find that it is still not static and return the err.
The reason I guess so is that as long as I set up static ip through  `/etc/network/interfaces` just looks like this
[content of interfaces (manually setting static ip)](https://pastebin.ubuntu.com/p/qRDVVPzpwB/)
the DHCP function works fine.

And here is the [log](https://pastebin.ubuntu.com/p/TvZHfh6X3Y/).

I want to know is this a bug or a feature?
is there a best practice to set up DHCP when using both linux with cloud-init and AGH?

**Comment by ainar-g** [comment]
The main error should be fixed on `edge` and `beta` channels.  We'll still need to see if we should make some changes wrt `/etc/network/interfaces.d/`.

**Comment by ainar-g** [comment]
Okay, it seems like we should take `source` directives into account.  We'll see if we'll be able to do that in the v0.107.0 cycle.

**Comment by EugeneOne1** [comment]
@conghuayu, the latest build in the `edge` channel provides support for `source` directives in `etc/network/interfaces` file.  Could you please check, if it works with your configuration?

**Comment by EugeneOne1** [comment]
@conghuayu, we'll close the issue for now.  Please feel free to reopen it if the problem persists.
