### ISSUE TITLE
How can I remove this issue?

### ISSUE THREAD

**Issue by man2018** [AdguardTeam/AdGuardHome#3258]
Adguard Home is running on my OpenWrt, the version is v0.106.3, the issue will be appeared in the web, how to solve it?
![image](https://user-images.githubusercontent.com/18020785/121793520-7d723580-cc32-11eb-92c5-935070894a00.png)

**Comment by ameshkov** [comment]
Probably related to this incident: https://status.adguard.com/incidents/j4jglcd8njyr
