### ISSUE TITLE
Pre-fetch commonly queried domains

### ISSUE THREAD

**Issue by adrianmace** [AdguardTeam/AdGuardHome#3262]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

My house's usage pattern is predictable, but the cached domains are only valid for a certain time before they need to be fetched again from the origin. This adds time to resolve for things that we are _always_ using. (YouTube, Plex, etc).

This is exasperated when the upstream DNS server I am querying has a high latency (due to personal preference, security benefits, etc).

### Proposed Solution

I would like you to implement the feature that [0xERR0R/blocky](https://github.com/0xERR0R/blocky) implements whereby it pre-fetches domains that have been queried more than X times in the last Y hours so that they are always in cache.

**Comment by ameshkov** [comment]
We already have a feature request about that.

However, we prefer to implement optimistic DNS instead (see #2145) which serves the same purpose.
