### ISSUE TITLE
Still "Required Field" when inputted words in text |Browsh Browser|

### ISSUE THREAD

**Issue by minilistra** [AdguardTeam/AdGuardHome#3269]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
  * v0.107.0-b.1
* **How did you install AdGuard Home:**
  * 
  * Github
* **How did you setup DNS configuration:**
  * 
  * Laptop/Router/Laptop/Internet
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
  * Amd
* **Operating system and version:**
  * 
  * Windowo 10

### Expected Behavior

It accepts credentials
### Actual Behavior

It doesnt
### Screenshots

<details><summary>Screenshot:</summary>

![error](https://user-images.githubusercontent.com/84135577/122069786-0a321480-ce28-11eb-8e8a-9b4713375503.png)
</details>

### Additional Information

Im trying browsh lol

**Comment by minilistra** [comment]
Command to fix Issue


`browsh --firefox.with-gui`

Then log in on the firefox window



> Gotta look at this pixels

![screen](https://user-images.githubusercontent.com/84135577/122176743-858ed700-ceb7-11eb-9cba-1850826dd3d7.png)
Thanks!

**Comment by ainar-g** [comment]
We're glad that you were able to fix the issue!  Unfortunately, according to our frontend team we basically only support last four versions of Chrome, Firefox, and Safari, plus Firefox ESR and some Edge versions.  We'll close this issue for now.
