### ISSUE TITLE
If you reconnect the Wan cable, the DNS stops working.

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#3270]
There is a Redmi AC2100, Openwrt on the core 5.4.82, AdGardHome v.106.3. If you reconnect the Wan cable, the DNS stops working. Ping works, everything is fine, but there is no DNS. If you stop the AdGardHome service and restart it, everything becomes normal. What is the reason for this and how to solve it?

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by hplee0120** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/3217
This may be the same problem. I have the same problem as you. This problem can be triggered when the DoH server is used upstream. This does not happen if you use a normal port DNS or DoT server

**Comment by fizsef** [comment]
Yes, I use a DoH server https://family.cloudflare-dns.com/dns-query
And how is this problem solved? I really need this DoH server to [encrypt](url) requests and block adult content. 
![1](https://user-images.githubusercontent.com/74646605/122227042-3482e100-cebf-11eb-945e-777440c4dccd.jpg)

**Comment by ainar-g** [comment]
@fizsef, hello, have you been able to collect the verbose logs?  If you don't want to post them here, you can send the logs to devteam@adguard.com, and please add the words “AdGuard Home Issue 3270” to the subject line.  Thanks!

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/3217
