### ISSUE TITLE
After restarting my router, I have to restart the AdGuard Home server for it to start working again

### ISSUE THREAD

**Issue by larrryfisherthefisherman** [AdguardTeam/AdGuardHome#3272]
After restarting my router, I have to restart the AdGuard Home server for it to start working again. I have tried to set a static ip address on the adguard home server and it made no difference. I really don't know what else to try.

* **Version of AdGuard Home server:**
Version: 
v0.106.3
* **How did you install AdGuard Home:**
with the install script from github
* **How did you setup DNS configuration:**
Router/pfSense
* **If it's a router or IoT, please write device model:**
VMware ESXi VM 64bit
* **CPU architecture:**
AMD64
* **Operating system and version:**
Debian 10

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by larrryfisherthefisherman** [comment]
Well I went to reinstall because the "AdGuardHome" command wasn't working but I didn't realize I needed to call the whole path which was "sudo /opt/AdGuardHome/AdGuardHome -s start|stop|restart|status|install|uninstall". Anyway after the reinstall its working as it should.
