### ISSUE TITLE
Private rDNS can't point to specified upstream

### ISSUE THREAD

**Issue by Haraguroicha** [AdguardTeam/AdGuardHome#3273]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.0
  * v0.107.0
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * amd64
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior

before v0.106.0 (e.g. v0.105.0), the behavior was expected by following config was set

```
# internal rDNS
[/120.10.in-addr.arpa/]10.x.x.A
[/168.192.in-addr.arpa/]10.x.x.B

# other rDNS
[/in-addr.arpa/]8.8.8.8
[/ip6.arpa/]8.8.8.8
```

* `dig -x 10.120.0.1` return a PTR records from A upstream
* `dig -x 192.168.0.1` return a PTR records from B upstream

### Actual Behavior

`dig -x 10.120.0.1` or `dig -x 192.168.0.1` return a record which was unexpected, that is random response from Private rDNS Servers when enable Private rDNS feature or always return nothing when disabled Private rDNS feature

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Hello.  We cannot reproduce this on the master branch—which is what I assume you meant by “v0.107.0”, because that version isn't released yet.  Can you [configure] AdGuard Home to collect verbose logs by setting  `verbose` to `true` and post the logs here as an attachment?  In particular, you should see something like:

```none
2021/06/18 11:30:27.007885 12058#876 [debug] Upstream 0: 10.x.x.A:53 is reserved for next domains: 120.10.in-addr.arpa.
2021/06/18 11:30:27.008650 12058#876 [debug] Upstream 1: 10.x.x.B:53 is reserved for next domains: 168.192.in-addr.arpa.
```

Also, make sure that you put those lines into the “Private reverse DNS servers” section.

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Haraguroicha** [comment]
all use same config file but I left the setting by following into Upstream Servers section and left Private rDNS with 10.122.15.53 and 10.121.55.228

```
[/168.192.in-addr.arpa/]10.121.55.228
[/120.10.in-addr.arpa/]10.122.15.53
[/121.10.in-addr.arpa/]10.122.15.53
[/122.10.in-addr.arpa/]10.122.15.53
[/123.10.in-addr.arpa/]10.122.15.53
[/in-addr.arpa/]8.8.8.8
[/ip6.arpa/]8.8.8.8
```

In previous version I can resolve PTR w/o issue, and verbose log for upstreams:
```
2021/06/18 09:51:44 1#1 [info] AdGuard Home, version v0.105.0-SNAPSHOT-2bf2d5a1, channel edge, arch linux amd64
...
2021/06/18 09:51:44 1#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 7
...
2021/06/18 09:51:45 1#1 [debug] Upstream 0: 8.8.8.8:53 is reserved for next domains: xxx.xxx.xxx.
2021/06/18 09:51:45 1#1 [debug] Upstream 1: 10.121.55.228:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:51:45 1#1 [debug] Upstream 2: 10.121.55.228:53 is reserved for next domains: 168.192.in-addr.arpa.
2021/06/18 09:51:45 1#1 [debug] Upstream 3: 10.121.55.228:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:51:45 1#1 [debug] Upstream 4: 10.121.55.228:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:51:45 1#1 [debug] Upstream 5: 8.8.8.8:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:51:45 1#1 [debug] Upstream 6: 10.122.15.53:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:51:45 1#1 [debug] Upstream 7: 10.122.15.53:53 is reserved for next domains: 120.10.in-addr.arpa.
2021/06/18 09:51:45 1#1 [debug] Upstream 8: 10.122.15.53:53 is reserved for next domains: 121.10.in-addr.arpa.
2021/06/18 09:51:45 1#1 [debug] Upstream 9: 10.122.15.53:53 is reserved for next domains: 122.10.in-addr.arpa.
2021/06/18 09:51:45 1#1 [debug] Upstream 10: 10.122.15.53:53 is reserved for next domains: 123.10.in-addr.arpa.
2021/06/18 09:51:45 1#1 [debug] Upstream 11: https://xxx.xxx.xxx:443/dns-query
2021/06/18 09:51:45 1#1 [debug] Upstream 12: https://dns.adguard.com:443/dns-query
2021/06/18 09:51:45 1#1 [debug] Upstream 13: 8.8.8.8:53 is reserved for next domains: in-addr.arpa.
2021/06/18 09:51:45 1#1 [debug] Upstream 14: 8.8.8.8:53 is reserved for next domains: ip6.arpa.
```

in this version I can resolve `10.120.x.x` and `10.121.x.x` and `10.122.x.x` also `10.123.x.x` by specified 10.122.15.53 and resolve `192.168.x.x` by 10.121.55.228

after I upgrade w/o change any config
```
2021/06/18 09:54:44.089520 1#1 [info] AdGuard Home, version v0.107.0-a.82+dbe8b92d
...
2021/06/18 09:54:44.093687 1#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 7
2021/06/18 09:54:44.093793 1#1 [info] Upgrade yaml: 7 to 8
2021/06/18 09:54:44.093863 1#1 [info] Upgrade yaml: 8 to 9
2021/06/18 09:54:44.093927 1#1 [info] Upgrade yaml: 9 to 10
2021/06/18 09:54:44.094008 1#1 [info] Upgrade yaml: 10 to 11
...
2021/06/18 09:54:44.234041 1#1 [debug] Upstream 0: 8.8.8.8:53 is reserved for next domains: xxx.xxx.xxx.
2021/06/18 09:54:44.234196 1#1 [debug] Upstream 1: 10.121.55.228:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:54:44.234359 1#1 [debug] Upstream 2: 10.121.55.228:53 is reserved for next domains: 168.192.in-addr.arpa.
2021/06/18 09:54:44.234554 1#1 [debug] Upstream 3: 10.121.55.228:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:54:44.234697 1#1 [debug] Upstream 4: 10.121.55.228:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:54:44.234841 1#1 [debug] Upstream 5: 8.8.8.8:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:54:44.234988 1#1 [debug] Upstream 6: 10.122.15.53:53 is reserved for next domains: xxx.xxx.
2021/06/18 09:54:44.235137 1#1 [debug] Upstream 7: 10.122.15.53:53 is reserved for next domains: 120.10.in-addr.arpa.
2021/06/18 09:54:44.235288 1#1 [debug] Upstream 8: 10.122.15.53:53 is reserved for next domains: 121.10.in-addr.arpa.
2021/06/18 09:54:44.235442 1#1 [debug] Upstream 9: 10.122.15.53:53 is reserved for next domains: 122.10.in-addr.arpa.
2021/06/18 09:54:44.235591 1#1 [debug] Upstream 10: 10.122.15.53:53 is reserved for next domains: 123.10.in-addr.arpa.
2021/06/18 09:54:44.235766 1#1 [debug] Upstream 11: https://xxx.xxx:443/dns-query
2021/06/18 09:54:44.235921 1#1 [debug] Upstream 12: https://dns.adguard.com:443/dns-query
2021/06/18 09:54:44.236051 1#1 [debug] Upstream 13: 8.8.8.8:53 is reserved for next domains: in-addr.arpa.
2021/06/18 09:54:44.236139 1#1 [debug] Upstream 14: 8.8.8.8:53 is reserved for next domains: ip6.arpa.
```
resolve any previous was successful IP addresses as null PTR


unless I cut rDNS upstreams config from Upstream Servers into Private rDNS sections

**Comment by ainar-g** [comment]
Yes, reverse DNS upstreams must be in the “Private reverse DNS servers” section.  Also, there you can replace the last two lines of your upstreams with a simple `8.8.8.8`, since these upstreams are only used for reverse DNS.  If you do this, is the issue solved?

**Comment by Haraguroicha** [comment]
That unexpected behavior was resolved after I'm move them to "Private reverse DNS servers", but I think that can make more detailed explanation likes this issue described situation or notice a warning to user that config was misplaced "Private reverse DNS servers" upstreams in "Private reverse DNS servers" section.

e.g. describe that was same format of "Upstream DNS servers" or place a note for reference this example 
![image](https://user-images.githubusercontent.com/1715541/122587981-1a006180-d091-11eb-8915-007186c52725.png)

**Comment by Haraguroicha** [comment]
Additionally, I found [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-rdns) was describe the syntax as for general upstream servers and make private IP range split out of Upstream Servers since v0.106.0, but release note was not notice or warnings that was a breaking changes.

Also I'm digging all of rDNS issues and I found @ameshkov comment that is a breaking changes in this [thread](https://github.com/AdguardTeam/AdGuardHome/issues/2704#issuecomment-789692744)

If it wouldn't make a notice for misplaced upstreams or make description more detailed for Private rDNS, this issue can close for my unconcerned of documents

**Comment by ainar-g** [comment]
It's true that the documentation there is still suppar.  We'll try to make the interaction between the two inputs clearer, thanks!

**Comment by ainar-g** [comment]
@Haraguroicha, we've updated the wiki page.  Could you please check the new [reverse DNS upstreams section][1] and tell us if the documentation is now clear enough?  Thanks!

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-rdns

**Comment by Haraguroicha** [comment]
I think that is enough detail for a player, but need to point out the PTR resolve for private range IP addresses is only affect when setting in private rDNS upstreams section and must enable "Use private reverse DNS resolvers"

**Comment by Haraguroicha** [comment]
I think this issue can merge to #3307 for tracking same thing?

**Comment by ainar-g** [comment]
Hm, yes, we should probably do that.
