### ISSUE TITLE
AdGuard blocking iOS CW App from playing videos

### ISSUE THREAD

**Issue by myanimator** [AdguardTeam/AdGuardHome#3278]
### Issue Details
* **Version of AdGuard Home server:**
  * 0.106.3
* **How did you install AdGuard Home:**
  * Added to Home Assistant as Integration
* **How did you setup DNS configuration:**
  * Set router's DNS server to Home Guard / Home Assistant IP
* **If it's a router or IoT, please write device model:**
  * Deco M9 Mesh Router
* **CPU architecture:**
  * Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz
* **Operating system and version:**
  * Home Assistnat - core-2021.6.6

### Expected Behavior
Launched iOS CW app to watch tv shows

### Actual Behavior
App launches and displays show list, including latest. However, when playing a show the video never loads.

### Additional Information
Disabling AdGuard protection allowed the videos to play.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #695](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/695) via [**ZenHub**](https://www.zenhub.com/)

**Comment by myanimator** [comment]
There has been no solution as far as I've been aware.
