### ISSUE TITLE
timed disabled protection

### ISSUE THREAD

**Issue by midyrp** [AdguardTeam/AdGuardHome#3280]
I like the fact you can disable protection. 
And yes, I can turn it on to, but why not automating and avoiding forgetting turning it on again: 

it would be great if the disabled state could be timed (t.ex. disabled for 1 min, 15 min, 1 hour, 2 hours, 1 day, indefinite)

**Comment by ainar-g** [comment]
Sounds like a dup of #1203 or at the very least a very related feature request.  I'll merge this into that one, if you don't mind.
