### ISSUE TITLE
Proposal for additional Fedora info in the wiki FAQ

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#3281]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.107.0-b.2, installed from GitHub)
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

While I set off the entirety of Tuesday on doing one proper setup of Fedora Workstation 34 aarch64, I had **far** more problems getting `systemctl` to recognise AGH on Fedora boot, than on any other distro I had tried.

After some 5 hours did I come across https://github.com/AdguardTeam/AdGuardHome/issues/765#issuecomment-752262353, but I had to do one additional thing to fix the problem on my end:

It turns out that SELinux is extremely overzealous in its firewall protection and its anti-`/home/` behaviour. It's not merely enough to copy an existing installation from `/home/username/Documents` to `/usr/local/bin` and reinstall the service from there. AGH's *initial* setup must've occured from a clean slate in `/usr/local/bin`, which finally seems to have made AGH start as a service on boot.

This allowed me to avoid the dreaded (and honestly bewilderingly non-verbose) "203 exited-code" status, so I can only presume that it's nice info to add to the FAQ and to the Fedora section's title.

### Proposed Solution

In the wiki pages, add info on SELinux and various causes of status '203 / exited-code' in Fedora, and to add them more prominently if possible. Probably also add info in "Getting Started" on that AGH is completely unable to run as a service from `/home/` on distros that use SELinux.

### Alternatives Considered

None that I can't think of.

### Additional Information

I know I did **a lot** to try to fix the problem, including `forking=1`; setting `AdGuardHome/data` to be writeable by all users (In one instance I failed to reproduce later on, the `data` folder was write-protected for non-root users); and extending `StartLimitInterval` and `StartLimitBurst` in `/etc/systemd/system/AdGuardHome.service` to 15 and 30 respectively.

**Comment by ainar-g** [comment]
@DandelionSprout, sorry for the long wait.  We've added your suggestions to the [Getting Started][1] and the [FAQ][2] entries.  Do you think that the information we've added is enough?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#installation
[2]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#fedora

**Comment by ainar-g** [comment]
I'll close this issue for now.  Feel free to report new documentation issues!
