### ISSUE TITLE
Add "Save/Load Configuration" buttons and functionality

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#3282]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.107.0-b.2, installed from GitHub)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

In the past two days, it has dawned on me that transferring AGH configurations from one PC to another, is not easy. Currently the only method is to copy and paste the `AdGuardHome.yaml` file itself, which is **not** a particularly reliable solution, as the pasted file has a high chance (but is not guaranteed) of being overwritten before being applied; of ASCII/Unicode mismatches if the transfer occured through text copying instead of file copying; user permission problems during pasting or with the pasted file; and potential other fatal errors that I have yet to properly isolate and describe.

### Proposed Solution

Buttons for "Save configuration" and "Load configuration" in the AGH admin control panel. Clicking the latter, should open a "Which file to choose" prompt on the admin's PC, as opposed to on the AGH-hosting PC.

Presumably, the easiest approach would be for "Load configuration" to completely overwrite the previous config, which is how uBlock Origin's config buttons work like.

### Alternatives Considered

None that seem realistic to me, especially considering Linux's total failure at being supported by cloud storage desktop-apps.

### Additional Information

(Old AGH installation → New AGH installation)
OS: Raspberry Pi OS Bullseye 32-bit → Fedora Workstation 34 aarch64
Hardware: Raspberry Pi 4 4GB → Raspberry Pi 4 8GB

**Comment by ammnt** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1147

**Comment by ainar-g** [comment]
I think that this is indeed a dup of ammnt's issue, so I will merge this into that one, if you don't mind.
