### ISSUE TITLE
Adguard not working with asus router

### ISSUE THREAD

**Issue by stuffu** [AdguardTeam/AdGuardHome#3287]
Hi

this might win a prize for most vague bug report but I’ll give it a try. Don’t laugh :)

I’m have been using adguard in home assistant for a few months and been very happy with it.

Then I wasn’t able to connect to anything outside of my LAN and my router shows internet access as disconnected. I changed dns servers to a manual dns server (cloudflare, same as I use in adguard) and it worked again. This was maybe two months ago (I can be a bit off with how long ago it actually was).

The only thing I can think of related to the issue is that adguard was updated when the issue occurred. I can recall that something wasn’t right with that update, like I couldn’t access adguard at all from within HA. Shortly after after there was another update that made adguard accessible again in HA but I still couldn’t use adguard as a dns.

testing upstream from within adguard shows nothing odd.

### Issue Details

* **Version of AdGuard Home server:**
  v0.106.3
* **How did you install AdGuard Home:**
  Home assistant add on store
* **How did you setup DNS configuration:**
  Router wired to home assistant/adguard home
* **If it's a router or IoT, please write device model:**
   Raspberry Pi 4, router is asus rt-ax92u

**Comment by ainar-g** [comment]
Hello.  Sorry, but I don't quite understand.  Are there are any issues you experience currently?

**Comment by stuffu** [comment]
Yes, when using AdGuard as DNS, my router refuses to connect to internet at all. Other manual DNS works fine. I think it's related to an update to Adguard about two months ago, prior to that it worked just fine. Tried resetting both adguard as well as the router without success.

**Comment by gyCfjSnO** [comment]
Are you using Asuswrt-Merlin?

**Comment by stuffu** [comment]
Nope, it's not available on RT-AX92Ul. Using stock firmware.

**Comment by gyCfjSnO** [comment]
> Nope, it's not available on RT-AX92U. Using stock firmware.

Can you post a screenshot of your WAN and LAN DHCP settings?

**Comment by stuffu** [comment]
Thanks for helping out! Attaching them.
<img width="747" alt="Screenshot 2021-06-29 at 11 11 20" src="https://user-images.githubusercontent.com/4310040/123771760-9d108b80-d8cb-11eb-93ed-daa9d8675584.png">
<img width="646" alt="Screenshot 2021-06-29 at 11 12 26" src="https://user-images.githubusercontent.com/4310040/123771773-a00b7c00-d8cb-11eb-97ae-c2a641792c5f.png">

**Comment by gyCfjSnO** [comment]
> Thanks for helping out! Attaching them.
> <img alt="Screenshot 2021-06-29 at 11 11 20" width="747" src="https://user-images.githubusercontent.com/4310040/123771760-9d108b80-d8cb-11eb-93ed-daa9d8675584.png">
> <img alt="Screenshot 2021-06-29 at 11 12 26" width="646" src="https://user-images.githubusercontent.com/4310040/123771773-a00b7c00-d8cb-11eb-97ae-c2a641792c5f.png">

Settings seem fine.

I previously had an incident with my AdGuard Home on a Pi4 where the upstream DNS wasn't working so I ended up reinstalling which fixed the problem and hasn't occurred since. I would suggest reinstalling.

**Comment by stuffu** [comment]
Did a reinstall, and same issue occurs. Not sure where the issue is but I can access my Home Assistant without any problems.

<img width="358" alt="Screenshot 2021-06-29 at 13 51 29" src="https://user-images.githubusercontent.com/4310040/123792969-837a3e80-d8e1-11eb-866e-f8ef6af1b25d.png">

**Comment by stuffu** [comment]
Maybe I got some more clues. Even if it says disconnected some sites work but most won’t. I would say that in general, the .com sites I’ve tested won’t work. (Except GitHub.com). A few .se sites works but far from all.

Does it make any sense?

**Comment by ainar-g** [comment]
Could you also tell us, which upstreams do you use?

Also, have you tried any of our beta releases?  We have recently fixed an issue with the DNS-over-HTTPS upstreams, and the fixed version is available in v0.107.0-b.3.

If that doesn't help, please [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment.  Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by stuffu** [comment]
I use:

**Comment by leo15dev** [comment]
> 
> 
> Thanks for helping out! Attaching them.
> <img alt="Screenshot 2021-06-29 at 11 11 20" width="747" src="https://user-images.githubusercontent.com/4310040/123771760-9d108b80-d8cb-11eb-93ed-daa9d8675584.png">
> <img alt="Screenshot 2021-06-29 at 11 12 26" width="646" src="https://user-images.githubusercontent.com/4310040/123771773-a00b7c00-d8cb-11eb-97ae-c2a641792c5f.png">

In wan setting, there is no need to manual setup the DNS, just used automatically.
In DHCP setting, please set the DNS server to your HA IP (192.168.86.178), after that, all of your local IPV4 DNS request  will through your HA Adguard Home (if you set the Adguard Home bind your HA port 53).

**Comment by stuffu** [comment]
@leo15dev It worked, big thanks for you suggestion! Strangely I didn't have that setup when it worked earlier. Since changing the DNS in DHCP settings I can't access my router anymore but that's maybe another question...

**Comment by leo15dev** [comment]
> 
> 
> @leo15dev It worked, big thanks for you suggestion! Strangely I didn't have that setup when it worked earlier. Since changing the DNS in DHCP settings I can't access my router anymore but that's maybe another question...

It should be able to access your router in local network. The router url is like http://192.168.86.1 (port 80) or https://192.168.86.1:port, it depends on what you set in the router web interface setting.  If you could not access your router, you need do the network or setup troubleshooting, e.g. check do you turn on the DHCP setting on the Adguard Home? or unplug the wan network cable to see if you can access the router or not?

**Comment by stuffu** [comment]
Doh, didn't think of the local ip... router.asus.com didn't work as I usually use. The issue is resolved but something must have changed along the way since I didn't need to put the DNS in DHCP settings before. Hopefully this will help someone else out as well.

Thanks all for helping out and resolving the issue.

**Comment by MarioPinto** [comment]
To maybe shed some light on this bug report:

I've had the exact same problem as @stuffu. AdGuard Home was working without a problem when configured as the DNS server in the ASUS configuration (I have an DSL-AC68u) and then suddenly stopped.

After some digging around I found out that the cause of the problem was an ASUS firmware update and not something with AdGuard Home.  The last firmware it worked with was Version 3.0.0.4.386_39648 from 2020/09/02.
Both subsequent Version 3.0.0.4.386_41995 and Version 3.0.0.4.386_43252 cause the problem described by @stuffu.

Setting AdGuard Home as DHCP server instead of DNS server is a good work around but it has the drawback of not working for devices connected to a guest network. (Or maybe I am missing something here)

Hope this helps someone.
