### ISSUE TITLE
Locked by filter statistic counts backwards

### ISSUE THREAD

**Issue by lJay-Jayl** [AdguardTeam/AdGuardHome#3294]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Download from adguard.com linux_armv7
* **How did you setup DNS configuration:**
  * Standalone->System
* **If it's a router or IoT, please write device model:**
  * Rasperry Pi 4 Model B
* **CPU architecture:**
  * ARM
* **Operating system and version:**
  * Pi-OS 32-Bit

### Expected Behavior
Locked by filter statistic counts forwards

### Actual Behavior
Locked by filter statistic counts backwards

### Screenshots
My Systems runs 24/7. If I go for the AdGurad overview it shows a count of 689.285 blocked by filter. After a refresh it shows 683.895.
A few days ago I had already something around 702k blocked by filter. 
The rest of the system works pretty fine. Keep up the good work.

<details><summary>Screenshot:</summary>

![AdGuard-20210628-0640](https://user-images.githubusercontent.com/85472488/123742102-704c7c00-d8ab-11eb-80ba-9a21500469b9.png)
![AdGuard-20210628-0641](https://user-images.githubusercontent.com/85472488/123742111-73e00300-d8ab-11eb-8755-6680e710f549.png)

</details>

**Comment by ainar-g** [comment]
Hi.  The statistics only show the counts for the statistics period.  After that, it erases the old data, so the count predictably goes down.  What period is set in “General settings” → “Statistics retention”?

**Comment by lJay-Jayl** [comment]
Hi ainar-g,
you are absolute right! 

I could still remember the holding period of the logs. i had forgotten that a value was also stored in the settings for the statistics. 
My fault!

Maybe you could mirror the value of the holding period of the protocols on the overview page. For guys like me :)

I love your product. You guys are the best.

Many regards
