### ISSUE TITLE
Statistics Page

### ISSUE THREAD

**Issue by Jean-Paul76** [AdguardTeam/AdGuardHome#3295]
Hi

As per discussion #3180 , I'd like to make a formal feature request for this:

> Can we get a statistics page for the upstream servers and bootstrap servers please?
>
>I would like it to show how many queries each upstream and bootstrap servers have served and what the average response time is for each server.

I think it would be useful as well if one could see some statistics on AdGuard's own DNS Cache as well. 

I'm including a link to [GRC's DNS Speed Benchmark](https://www.grc.com/dns/benchmark.htm) as inspiration :-)

Another happy AdGuard user

**Comment by Aikatsui** [comment]
Related https://github.com/AdguardTeam/AdGuardHome/issues/2013

**Comment by ainar-g** [comment]
Merging into the one mentioned by @Aikatsui.  Thanks!
