### ISSUE TITLE
Access setup issues

### ISSUE THREAD

**Issue by carrot-eggs** [AdguardTeam/AdGuardHome#3299]
hi,Customizing the upstream through the client ID cannot take effect, and it will still be resolved through the upstream DNS set globally, as shown in the figure：
![图片](https://user-images.githubusercontent.com/35254441/123819640-84848d80-d92c-11eb-988d-d755429e0485.png)
![图片](https://user-images.githubusercontent.com/35254441/123819683-8c443200-d92c-11eb-8b9f-81b782f57969.png)
![图片](https://user-images.githubusercontent.com/35254441/123819716-91a17c80-d92c-11eb-9733-4f0cbe5a7026.png)
![图片](https://user-images.githubusercontent.com/35254441/123819745-96663080-d92c-11eb-9855-6ac4fad0becd.png)
My adguardhome is installed on a VPS, and I cannot set up a dedicated upstream DNS for a certain device through the client ID.
adguardhome version: v0.106.3

**Comment by ainar-g** [comment]
Hello again.  This seems like something we've fixed in the main branch, in #3186.  Can you install a beta version, say v0.107.0-b.3, and check if this issue is still there?

**Comment by carrot-eggs** [comment]
@ainar-g 
Hi,
I upgraded to v0.107.0-b.3. After testing, I have been able to use custom upstream DNS through the client ID. The problem has been resolved.
Thank you for your support, and hope AdGuardHome gets better and better!
