### ISSUE TITLE
Windows Update broke AdGuard Home

### ISSUE THREAD

**Issue by Pradhansb** [AdguardTeam/AdGuardHome#3301]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Pradhansb** [comment]
Hello! I am not sure this is the correct place to post this. About 3 weeks ago, I installed AdGuard Home on a Windows machine. I changed the DNS in the router and the ipV4 in Windows. Everything was working perfectly. Then Windows updated, and I totally lost the internet. I ended up reinstalling AdGuardHome from scratch. I notice that under the properties of each network, you can now change the DNS servers for IPv4. SOOO...now my hard-wired cxn no longer works. My wireless cxns seem to work fine. 
I want to make sure I am doing the right thing. I am not clear as to whether changing the IPv4 which is listed under the Windows setup is essential? Or is that only for AdGuard Windows.
Secondly, I have tried to change the IPv4 address on my hard-wired cxn both on the adapter and in the new Property box. Nothing works. As soon as I do this, I lose the internet on that machine.

Like I said, all was fine just 2 days ago! Forgive me if this is not clear/or if I am wordy.
Thanks,
Pradhan

**Comment by ainar-g** [comment]
Hello.  What do you mean when you say that you've changed the DNS on your router?  If you plan to only use AGH on that Windows machine, you shouldn't change any router settings.
