### ISSUE TITLE
DNS via Router setup stopped working

### ISSUE THREAD

**Issue by mattiaswerner** [AdguardTeam/AdGuardHome#3303]
### Issue Details

DNS stops working when pointing my ASUS Router DNS to the IP of my HTPC running adguard-home snap

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Snapcraft
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * ASUS RT-AC68U (firmware v.  3.0.0.4.386_43129-g60defb2)
* **CPU architecture:**
  * Intel i3-3220 (4) @ 3.300GHz
* **Operating system and version:**
  * Ubuntu Server 20.04.2

### Expected Behavior
I set the DNS in my router to 192.168.1.99 (the IP of my htpc) and everything should work

### Actual Behavior
As soon as I set the DNS in my router, pages stop loading. Reverting the DNS setting fixes the issue.

### Additional Information
My setup used to work just fine. I did some testing of the snap at different channels and discovered I couldn't change back from edge to stable. I removed it and held off an setting it up again. Today I purged any previous traces of the snap, installed the stable snap and set it up from scratch again. I was very surprised to see it not working, and have spent most of today trying to figure out if I had changed something on my end, and the only thing I could think of is a firmware update of the router. Could possibly be a newer snap version in stable as well, unsure of when I turned it off.

Any help you could provide would be greatly appreciated. 

Thank you for your time.

**Comment by mattiaswerner** [comment]
Found someone else with the same issue on an ASUS router.

https://community.home-assistant.io/t/router-loses-internet-connection-when-using-adguard-home-dns/310827

**Comment by Aikatsui** [comment]
>I set the DNS in my router to 192.168.1.99 (the IP of my htpc) and everything should work

Did you set the custom DNS in the DHCP area DNS settings?
(Leave WAN DNS settings as default, connect automatically)

**Comment by mattiaswerner** [comment]
> > I set the DNS in my router to 192.168.1.99 (the IP of my htpc) and everything should work
> 
> Did you set the custom DNS in the DHCP area DNS settings?
> (Leave WAN DNS settings as default, connect automatically)

That worked, I feel a bit sheepish now. Thanks for setting me straight :)
