### ISSUE TITLE
Fastest IP: do not probe when there's just a single IP in the response

### ISSUE THREAD

**Issue by tony198911** [AdguardTeam/AdGuardHome#3315]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Problem Description
Some  domains just have one IP address, and the IP will not open with 80 or 443, once ADG (DNS settings->Fastest IP address) meet these kind of IP will not pass the IP back until time out (like 1sec).
pic as below
https://github.com/tony198911/build-openwrt/blob/a548314b77413e89dd06f1234171dee429cb74e4/adg_1.png

### Proposed Solution
When domain just have one IP,  just skip the speed check.

### Additional Information
Thank you for your contribution! ADG is Great!

**Comment by ainar-g** [comment]
This should be implemented as of 4b5a66ee.  Can you please check if our solution works for you?

**Comment by tony198911** [comment]
> This should be implemented as of [4b5a66e](https://github.com/AdguardTeam/AdGuardHome/commit/4b5a66ee617cc364c26a3d4293ae4dba378c3f26). Can you please check if our solution works for you?

solved, thx :)
