### ISSUE TITLE
Abnormal termination

### ISSUE THREAD

**Issue by cunvoas** [AdguardTeam/AdGuardHome#3318]
Hello,
With version **v0.107.0-b.3**

 I have many times abnomal termination on ARM Synology DSM7 (native, not docker)

This is the stack trace :

      2021/07/06 13:01:55.363651 [error] dns: bad type <nil> in tableIPToHost for 192.168.1.4
      panic: runtime error: index out of range [0] with length 0
      
      goroutine 16547 [running]:
      github.com/AdguardTeam/dnsproxy/proxy.filterMsg(0x37f4f50, 0x37f4f50, 0x37f0000, 0x0)
              github.com/AdguardTeam/dnsproxy@v0.38.0/proxy/cache.go:260 +0x1ac
      github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(0x3224340, 0x332c6c0, 0x0, 0x0)
              github.com/AdguardTeam/dnsproxy@v0.38.0/proxy/proxy.go:480 +0x35c
      github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).processUpstream(0x322a000, 0x37ac8a0, 0x0)
              github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:543 +0x68
      github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).handleDNSRequest(0x322a000, 0x3224340, 0x332c6c0, 0x0, 0x0)
              github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:102 +0x21c
      github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0x3224340, 0x332c6c0, 0x3, 0x30b7d60)
              github.com/AdguardTeam/dnsproxy@v0.38.0/proxy/server.go:127 +0x1e4
      github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(0x3224340, 0x33f46c0, 0x90, 0x90, 0x35edeac, 0x4, 0x4, 0x379ac78, 0x308b390)
              github.com/AdguardTeam/dnsproxy@v0.38.0/proxy/server_udp.go:105 +0x194
      github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0x3224340, 0x33f46c0, 0x90, 0x90, 0x35edeac, 0x4, 0x4, 0x379ac78, 0x308b390, 0x1a9af70, ...)
              github.com/AdguardTeam/dnsproxy@v0.38.0/proxy/server_udp.go:74 +0x5c
      created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
              github.com/AdguardTeam/dnsproxy@v0.38.0/proxy/server_udp.go:73 +0x334

**Comment by ainar-g** [comment]
Thank you for the report!  We'll try to fix asap.

**Comment by Disqu3-mirOir-qt** [comment]
2021/07/06 13:01:55.363651 [error] dns: bad type <nil> in tableIPToHost for xxx.xxxx.xxx

i have same things only whith PTR request .arpa

**Comment by ainar-g** [comment]
This should be fixed on the `edge` channel as of revision 1571609e.  Could you please check if that fixes the panic?

**Comment by cunvoas** [comment]
edge arm7-32 bit deployed ( v0.107.0-a.97+1571609e ) and running since 15 minutes.

After 2 hours usage without panic error, I will repost here an aknowledgement as good job.
Thanks a lot for your reactivity

**Comment by cunvoas** [comment]
2 hours running without error and 20k queries sended.
This is solved for me.
Thanks
