### ISSUE TITLE
Search log by date

### ISSUE THREAD

**Issue by Saku241** [AdguardTeam/AdGuardHome#3322]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I want to be able to check logs from a certain date. If I want to check logs from 5 days ago, I need to load all logs until 5 days ago...

**Comment by ainar-g** [comment]
Dup of #481 and #2554, depends on #2290.
