### ISSUE TITLE
Show a pop-up webpage showing that a page was blocked 

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdGuardHome#3326]
I think it would be really cool if we got a pop up in the browser or redirected to a page telling us that the page we were trying to access was blocked because sometimes manually whitelisting things takes a while so it would be nice if we go to a blocked page, we get a webpage saying it was blocked by adguard and we get the choice to log in to whitelist it.

**Comment by ainar-g** [comment]
Dup of #3176.
