### ISSUE TITLE
DNSCrypt server not responding

### ISSUE THREAD

**Issue by GENERAL-AN** [AdguardTeam/AdGuardHome#3328]
### Issue Details

When trying to setup the dnscrypt server, I test the install using the method in the documentation and get
`15:56:06 [fatal] failed to establish connection with the server: read udp SERVER_IP:41120->SERVER_IP:5443: read: connection refused`

I have created a dnscrypt server using dnsproxy, which I get a response from when checking it and am using with DNSCloak on iOS.

Output of `AdGuardHome -v --version:`

`AdGuard Home
Version: v0.106.3
Channel: release
Go version: go1.15.11
Build time: 2021-05-19T13:25:09Z+0000
GOOS: linux
GOARCH: amd64
Race: false
Main module:
	github.com/AdguardTeam/AdGuardHome (devel)
Dependencies:
	github.com/AdguardTeam/dnsproxy@v0.37.4 (sum: h1:YIoJkIp828LKmmmgxXvZHUKfGLsqTQAK8g+4DXbDbyU=)
	github.com/AdguardTeam/golibs@v0.5.0 (sum: h1:qwhEKjDrT0UcwDnHrNU2Yg/DLR9b/GsUncnXYW6VzAU=)
	github.com/AdguardTeam/urlfilter@v0.14.5 (sum: h1:WyF0hg0MwKevsqNPkoaZFH8f5WRi/yuy/7qePtYt5Ts=)
	github.com/NYTimes/gziphandler@v1.1.1 (sum: h1:ZUDjpQae29j0ryrS0u/B8HZfJBtBQHjqw2rQ2cqUQ3I=)
	github.com/aead/chacha20@v0.0.0-20180709150244-8b13a72661da (sum: h1:KjTM2ks9d14ZYCvmHS9iAKVt9AyzRSqNU1qabPih5BY=)
	github.com/aead/poly1305@v0.0.0-20180717145839-3fee0db0b635 (sum: h1:52m0LGchQBBVqJRyYYufQuIbVqRawmubW3OFGqK1ekw=)
	github.com/ameshkov/dnscrypt/v2@v2.1.3 (sum: h1:DG4Uf7LSDg6XDj9sp3maxh3Ur26jeGQaP5MeYosn6v0=)
	github.com/ameshkov/dnsstamps@v1.0.3 (sum: h1:Srzik+J9mivH1alRACTbys2xOxs0lRH9qnTA7Y1OYVo=)
	github.com/beefsack/go-rate@v0.0.0-20200827232406-6cde80facd47 (sum: h1:M57m0xQqZIhx7CEJgeLSvRFKEK1RjzRuIXiA3HfYU7g=)
	github.com/cheekybits/genny@v1.0.0 (sum: h1:uGGa4nei+j20rOSeDeP5Of12XVm7TGUd4dJA9RDitfE=)
	github.com/digineo/go-ipset/v2@v2.2.1 (sum: h1:k6skY+0fMqeUjjeWO/m5OuWPSZUAn7AucHMnQ1MX77g=)
	github.com/fsnotify/fsnotify@v1.4.9 (sum: h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=)
	github.com/go-ping/ping@v0.0.0-20210216210419-25d1413fb7bb (sum: h1:2opwLSXqxE0Za64PdpskXuvLYDj/XHQAD8tLcYpSlvY=)
	github.com/gobuffalo/envy@v1.9.0 (sum: h1:eZR0DuEgVLfeIb1zIKt3bT4YovIMf9O9LXQeCZLXpqE=)
	github.com/gobuffalo/packd@v1.0.0 (sum: h1:6ERZvJHfe24rfFmA9OaoKBdC7+c9sydrytMg8SdFGBM=)
	github.com/gobuffalo/packr@v1.30.1 (sum: h1:hu1fuVR3fXEZR7rXNW3h8rqSML8EVAf6KNm0NKO/wKg=)
	github.com/google/renameio@v1.0.1-0.20210406141108-81588dbe0453 (sum: h1:vvZyWjAX9oDB+DWpMsZMyv6Q3NZtim2C5Zcdh+H0OmQ=)
	github.com/AdguardTeam/dhcp@v0.0.0-20210517101438-550ef4cd8c6e (sum: h1:M6YnFP12o0/SjBEPt6b2r8ZkIy/wsV14TK8X9Tb6DEE=)
	github.com/joho/godotenv@v1.3.0 (sum: h1:Zjp+RcGpHhGlrMbJzXTrZZPrWj+1vfm90La1wgB6Bhc=)
	github.com/joomcode/errorx@v1.0.3 (sum: h1:3e1mi0u7/HTPNdg6d6DYyKGBhA5l9XpsfuVE29NxnWw=)
	github.com/josharian/native@v0.0.0-20200817173448-b6b71def0850 (sum: h1:uhL5Gw7BINiiPAo24A2sxkcDI0Jt/sqp1v5xQCniEFA=)
	github.com/kardianos/service@v1.2.0 (sum: h1:bGuZ/epo3vrt8IPC7mnKQolqFeYJb7Cs8Rk4PSOBB/g=)
	github.com/lucas-clemente/quic-go@v0.20.1 (sum: h1:hb5m76V8QS/8Nw/suHvXqo3BMHAozvIkcnzpJdpanSk=)
	github.com/marten-seemann/qtls-go1-15@v0.1.4 (sum: h1:RehYMOyRW8hPVEja1KBVsFVNSm35Jj9Mvs5yNoZZ28A=)
	github.com/mdlayher/ethernet@v0.0.0-20190606142754-0394541c37b7 (sum: h1:lez6TS6aAau+8wXUP3G9I3TGlmPFEq2CTxBaRqY6AGE=)
	github.com/mdlayher/netlink@v1.4.0 (sum: h1:n3ARR+Fm0dDv37dj5wSWZXDKcy+U0zwcXS3zKMnSiT0=)
	github.com/mdlayher/raw@v0.0.0-20191009151244-50f2db8cc065 (sum: h1:aFkJ6lx4FPip+S+Uw4aTegFMct9shDvP+79PsSxpm3w=)
	github.com/miekg/dns@v1.1.40 (sum: h1:pyyPFfGMnciYUk/mXpKkVmeMQjfXqt3FAJ2hy7tPiLA=)
	github.com/patrickmn/go-cache@v2.1.0+incompatible (sum: h1:HRMgzkcYKYpi3C8ajMPV8OFXaaRUnok+kx1WdO15EQc=)
	github.com/pkg/errors@v0.9.1 (sum: h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=)
	github.com/rogpeppe/go-internal@v1.7.0 (sum: h1:3qqXGV8nn7GJT65debw77Dzrx9sfWYgP0DDo7xcMFRk=)
	github.com/satori/go.uuid@v1.2.0 (sum: h1:0uYX9dsZ2yD7q2RtLRtPSdGDWzjeM3TbMJP9utgA0ww=)
	github.com/ti-mo/netfilter@v0.4.0 (sum: h1:rTN1nBYULDmMfDeBHZpKuNKX/bWEXQUhe02a/10orzg=)
	github.com/u-root/u-root@v7.0.0+incompatible (sum: h1:u+KSS04pSxJGI5E7WE4Bs9+Zd75QjFv+REkjy/aoAc8=)
	go.etcd.io/bbolt@v1.3.5 (sum: h1:XAzx9gjCb0Rxj7EoqcClPD1d5ZBxZJk0jbuoPHenBt0=)
	golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83 (sum: h1:/ZScEX8SfEmUGRHs0gxpqteO5nfNW6axyZbBdw9A12g=)
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4 (sum: h1:4nGaVu0QrbjT/AK2PRLuQfQuh6DJve+pELhqTdAj3x0=)
	golang.org/x/sys@v0.0.0-20210330210617-4fbd30eecc44 (sum: h1:Bli41pIlzTzf3KEY06n+xnzK/BESIg2ze4Pgfh/aI8c=)
	golang.org/x/text@v0.3.5 (sum: h1:i6eZZ+zk0SOf0xgBpEpPD18qWcJda6q1sxt3S0kzyUQ=)
	gopkg.in/natefinch/lumberjack.v2@v2.0.0 (sum: h1:1Lc07Kr7qY4U2YPouBjpCLxpiyxIVoxqXgkXLknAOE8=)
	gopkg.in/yaml.v2@v2.4.0 (sum: h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=)
	howett.net/plist@v0.0.0-20201203080718-1454fab16a06 (sum: h1:QDxUo/w2COstK1wIBYpzQlHX/NqaQTcf9jyz347nI58=)`

* **Version of AdGuard Home server:**
  *  v0.106.3
* **How did you install AdGuard Home:**
  *  Install script
* **How did you setup DNS configuration:**
  *  System
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 10

### Expected Behavior

A response when checking the dnscrypt server using `dnscrypt lookup-stamp\
    --domain 'example.com'\
    --stamp 'sdns://AQcAAAAAAAAADTEyNy4wLjAuMTo0NDMg8R3bzEgX5UOEX93Uy4gYSbZCJvPeOXYlZp2HuRm8T7AbMi5kbnNjcnlwdC1jZXJ0LmV4YW1wbGUub3Jn'\
    --type 'a'`
### Actual Behavior

This output `15:56:06 [fatal] failed to establish connection with the server: read udp SERVER_IP:41120->SERVER_IP:5443: read: connection refused`
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Hello and thank you for your report.  Are you positive that AdGuard Home is set to listen to DNSCrypt requests on port 5443?  Is this port open to the machine that is trying to perform the request?  Can you [configure] AdGuard Home to collect verbose logs by setting  `verbose` to `true` and post the logs here as an attachment?

Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by GENERAL-AN** [comment]
[adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/6802696/adguard.log)

It does not appear to be on. 

Also, I am just wondering, should I enable tls `tls: true` to get the DNSCrypt Server to work?

**Comment by ainar-g** [comment]
Yes, the log doesn't show DNSCrypt server starting.  What are the values of `port_dnscrypt` and `dnscrypt_config_file` in your `AdGuardHome.yaml`?

**Comment by GENERAL-AN** [comment]
> Yes, the log doesn't show DNSCrypt server starting. What are the values of `port_dnscrypt` and `dnscrypt_config_file` in your `AdGuardHome.yaml`?

I used the documentation's default 5443 and ./dnscrypt.yaml.

**Comment by GENERAL-AN** [comment]
I changed the settings to 
![image](https://user-images.githubusercontent.com/14866477/125662822-d9573d8b-5aef-4aad-b3fc-2be1a07e3b58.png)
and nothing in the logs.
[adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/6817785/adguard.log)

**Comment by GENERAL-AN** [comment]
Still nothing. I even unzipped and ran the beta version.

Log: [agh.log](https://github.com/AdguardTeam/AdGuardHome/files/6881346/agh.log)

Config: 
![image](https://user-images.githubusercontent.com/14866477/127062125-3bcb90cd-3ea7-4905-9bfb-e1043662ab91.png)

**Comment by ainar-g** [comment]
Sorry for the delay.  None of the logs show that DNSCrypt is actually up.  You should see messages like:

```none
2021/07/27 12:18:11.543226 89940#41 [info] Creating a DNSCrypt UDP listener
2021/07/27 12:18:11.543371 89940#41 [info] Listening for DNSCrypt messages on udp://[::]:8000
2021/07/27 12:18:11.543468 89940#41 [info] Creating a DNSCrypt TCP listener
2021/07/27 12:18:11.543611 89940#41 [info] Listening for DNSCrypt messages on tcp://[::]:8000
```

Are you sure that this is the config that your AGH actually reads?

**Comment by GENERAL-AN** [comment]
> Sorry for the delay. None of the logs show that DNSCrypt is actually up. You should see messages like:
> 
> ```
> 2021/07/27 12:18:11.543226 89940#41 [info] Creating a DNSCrypt UDP listener
> 2021/07/27 12:18:11.543371 89940#41 [info] Listening for DNSCrypt messages on udp://[::]:8000
> 2021/07/27 12:18:11.543468 89940#41 [info] Creating a DNSCrypt TCP listener
> 2021/07/27 12:18:11.543611 89940#41 [info] Listening for DNSCrypt messages on tcp://[::]:8000
> ```
> 
> Are you sure that this is the config that your AGH actually reads?

Yes, I am. I have verbose logging enabled and output to a file.

**Comment by ainar-g** [comment]
Are you sure that nothing else is binding to these ports?  That is, what does

```sh
sudo lsof -i :8000
```

show?  Because if that doesn't show anything, and the config file is correct, then unfortunately I have no idea what else could be wrong.

**Comment by GENERAL-AN** [comment]
> Are you sure that nothing else is binding to these ports? That is, what does
> 
> ```shell
> sudo lsof -i :8000
> ```
> 
> show? Because if that doesn't show anything, and the config file is correct, then unfortunately I have no idea what else could be wrong.

It shows nothing. I even tried it on a laptop and got the same results as above. I think I will try Docker or a VM next.

**Comment by GENERAL-AN** [comment]
Just tried with Docker and the log does not show anything. May be related to https://github.com/AdguardTeam/AdGuardHome/issues/2669#issuecomment-782303302

**Comment by GENERAL-AN** [comment]
Does the provider name have to be the same as the hostname of the machine? 

> Where `example.org` is the name of your host and `./dnscrypt.yaml` is the name of the configuration output file.

I just tried creating  a server in an Ubuntu 20.04 container and got the same results. Or does there need to be a domain name (i.e. a DOH/DOT server)?

**Comment by ameshkov** [comment]
> Does the provider name have to be the same as the hostname of the machine? Or does there need to be a domain name (i.e. a DOH/DOT server)?

The provider name can be any valid domain name, it does not matter which one you choose.

**Comment by GENERAL-AN** [comment]
In the absence of a solution I have chosen to use dnsproxy to forward requests to AdGuard Home.

**Comment by ameshkov** [comment]
Hm, that's weird, AdGuard Home uses dnsproxy internally so it is pretty much the same.

**Comment by GENERAL-AN** [comment]
Weird. I am seeing this behavior on a Linode Instance.

Log: [log.txt](https://github.com/AdguardTeam/AdGuardHome/files/6995406/log.txt)
Config: ![image](https://user-images.githubusercontent.com/14866477/129629280-fe42f326-3794-4ba4-a003-7c139bde1bd3.png)

For what it's worth, I have witnessed this on dnsproxy, even within my network; testing gives me an i/o timeout. I am currently using https://github.com/jedisct1/encrypted-dns-server to forward requests at home.

**Comment by ainar-g** [comment]
@GENERAL-AN, I've only now realised this, but… why do you have TLS disabled?  DNSCrypt won't work without it.

**Comment by GENERAL-AN** [comment]
> @GENERAL-AN, I've only now realised this, but… why do you have TLS disabled? DNSCrypt won't work without it.

I don’t currently have a domain name, and as such can’t enable TLS.

The documentation for DNSCrypt should be updated, since one other person had this issue here https://github.com/AdguardTeam/AdGuardHome/discussions/2741.

**Comment by ainar-g** [comment]
Thanks for rechecking, we'll update the docs before the release!
