### ISSUE TITLE
Only serve customers in designated countries

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdGuardHome#3329]
Because I see in the system log that many crawlers have browsed my server

or Block the ip/domain of known crawler robots? (e.g. censys)

release or block the entire ASN?

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/125180283-d8e01500-e22a-11eb-99db-28cc4b2cca49.png)
![image](https://user-images.githubusercontent.com/75058881/125180285-da114200-e22a-11eb-9efd-18db01d99c5c.png)

**Comment by ainar-g** [comment]
That mostly sounds like a dup of #352, #2925, and some others.

If you want to really protect your public server, it's better to use a combination of DoH or DoT, ClientIDs, and/or allowlist access settings.  See #2624.
