### ISSUE TITLE
CNAMEs not made lowercase before matching

### ISSUE THREAD

**Issue by sjhgvr** [AdguardTeam/AdGuardHome#3335]
Using oisd abp full on v0.106.3

Visiting filterlist.com (yes without the s) (CNAME HDRedirect-LB7-5a03e1c2772e1c9c.elb.us-east-1.amazonaws.com) is allowed
Visiting HDRedirect-LB7-5a03e1c2772e1c9c.elb.us-east-1.amazonaws.com is blocked
Visiting hdredirect-lb7-5a03e1c2772e1c9c.elb.us-east-1.amazonaws.com is blocked

Since lowercase "hdredirect-lb7-5a03e1c2772e1c9c.elb.us-east-1.amazonaws.com" is present in oisd abp full, I expect filterlist.com to be blocked.

It seems after domain lookup CNAMEs are not made lowercase before matching.

**Comment by ainar-g** [comment]
Thank you for your report!  That should be fixed as of snapshot `f419896` on the `edge` channel.  Could you please check if the solution works for you?

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to reopen with more details if you think that something should be fixed.
