### ISSUE TITLE
ETC/Hosts gone bonkers!

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#3346]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Raspberry Pi 2 running AdGuard Home v0.107.0-b.4 as local DNS server, NOT DHCP server.

After the latest update (v0.107.0-b.4), AdGuard Home "Client (Runtime)" section stopped showing correct client IP addresses from ETC/Hosts file. 

"Client (Runtime)" displays all the host names from ETC/Hosts correctly, but shows the same exact IP for all of the host names and that IP changes every time I refresh the page. One moment it shows 10.0.0.1 for all the hosts, the next moment it shows 10.0.0.2, etc. It affects localhost (127.0.0.1) and host name (127.0.1.1) addresses. 

AdGuard Home function does not appear to be affected. It recognizes IP addresses and client hosts correctly everywhere, except "Client (Runtime)" section.

It may be important to know that I force static (PERM) ARP for each host using "ETC/Ethers" file, but I don't think that is the problem. Uninstalling and re-installing AdGuard Home has no effect.

**Comment by ainar-g** [comment]
Thank you for your report! That should be fixed as of snapshot ff4905b on the edge channel. Could you please check if the solution works for you?

**Comment by EntropySmoke** [comment]
Yes, fixed! Thank you for a prompt response!
