### ISSUE TITLE
rDNS failing 

### ISSUE THREAD

**Issue by qehs244** [AdguardTeam/AdGuardHome#3352]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Issue Details

* **Version of AdGuard Home server:**
v0.107.0-b.4
* **How did you install AdGuard Home:**
Can't remember
* **How did you setup DNS configuration:**
System
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
AMD64
* **Operating system and version:**
Debian 10

### Expected Behavior

I expected the clients (runtime) to display hostnames and associated IP addresses
### Actual Behavior

rDNS is returning the same IP for each client detected, if you refresh the page 
the IP changes to the same one for each client, but a different one than the previous page refresh

### Screenshots

![Screenshot at 2021-07-13 12-23-11](https://user-images.githubusercontent.com/34272265/125443757-7e0142c8-91f1-4c86-b793-82cff2fa505e.png)

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Adguard is pointing to the correct local DNS server to perform the rDNS

**Comment by ainar-g** [comment]
Dup of #3346.
