### ISSUE TITLE
Keep DNS rewrites when protection is disabled

### ISSUE THREAD

**Issue by jicho** [AdguardTeam/AdGuardHome#3356]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
When I temporary disable the protection this also results in a disabled DNS rewrite as a result I can't use my internal used domain names 

### Proposed Solution
When disabling protection it would be nice when it is possible to keep the DNS rewrite function active so internal subdomains that are not in an external DNS are still internally available.

I'm talking about the DNS rewrites on this page:
http://x.x.x.x/#dns_rewrites

### Additional Information
I'm using AGH only internally and have custom domains running to access some internal services with ease, but... when I disable protection I need to come up with the IP's to access the services and... I need to access AGH by IP so I can enable protection again.

**Comment by ainar-g** [comment]
Dup of #1558.

**Comment by jicho** [comment]
Argh... sorry... I looked for an issue like mine, but didn't found it :(
