### ISSUE TITLE
ECS pass-through from clients to upstream servers

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3360]
Can the setting `edns_client_subnet` be enhanced so that if a client passes ECS info in the DNS query it is just passed through to the upstream servers?

E.g. consider this setup: `[LAN: clients --> dnsmasq] --VPN--> [VPS: Adguard Home] --> upstream server (8.8.8.8)`

If `dnsmasq` is configured with the add-subnet option, e.g. `add-subnet=1.2.3.0/24`, then dnsmasq will pass the 1.2.3.0/24 subnet to Adguard Home as ECS. It would be very useful to pass along the same ECS to the upstream server (8.8.8.8) if allowed to do so (some users may not want this behavior by default due to privacy).

I understand that `edns_client_subnet` can pass ECS when the client has a public IP, but there is a use case where the client can connect to an Adguard Home VPS via VPN hence the client has a private IP but they run in different locations. Now, it would make sense for the ECS to be that of the VPN server, but _the client uses VPN only to tunnel the DNS traffic_, the rest of the traffic is direct, not via the VPN server, so it helps for the upstream DNS servers to return CDN IPs that are close to the client, not the VPN server.

This may be related to #2514 but it is not the same.

`edns_client_subnet` should support 3 modes:
- the current one, where it can pass the IP address of the client (if public)
- pass-through any ECS from the client, don't attempt to change it in any way
- pass a **fixed** IP/subnet regardless of the client IP or ECS from the client (see use case in https://github.com/AdguardTeam/AdGuardHome/issues/2514#issuecomment-882083190)

**Comment by timkgh** [comment]
Out of curiosity if anyone is deeply familiar with ECS and CDNs, does ECS help these days or has the world pretty much moved to anycast and returning near IPs based on DNS doesn't make much of a difference these days?

**Comment by agneevX** [comment]
@timkgh I can tell you for a fact that a lot of video streaming websites are faster when I use Google DNS because with ECS, it almost always points to ISP's hosted cache. 

Here's how I'm doing it at the moment:

![image](https://user-images.githubusercontent.com/19761269/126511886-6e5da86c-acd7-4a6d-8905-7b38496be265.png)

**Comment by timkgh** [comment]
I see, you use specific upstream DNS per CDN. But this is a pain to maintain in general.

My discovery is that my ISP DNS is super fast, responds in <1ms to almost all queries and CDN works well with it of course even without ECS. But ... privacy please (yes, I understand it's not total privacy because of SNI, but at least I don't give them a trivial way to monetize and track me).

**Comment by agneevX** [comment]
> I see, you use specific upstream DNS per CDN. But this is a pain to maintain in general.

No, all domains listed there are queried to Google DNS (DoH) only.

**Comment by ameshkov** [comment]
Tbh, I think this should be merged into https://github.com/AdguardTeam/AdGuardHome/issues/1727

We should:

1. Forward ECS to the upstream
2. Use ECS instead of the client IP in this case

Not sure if this should be enabled by default.

**Comment by timkgh** [comment]
Works for me, as long as it gets implemented :)
