### ISSUE TITLE
Major fix for the blocklist-syntax wiki page

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#3369]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.107.0-b.5)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

A major aspect of `$badfilter` that neither the official guides of AdGuard Home nor uBlock Origin explain, is how Hosts IPs must be removed in order for `$badfilter` to work.

This means that `127.0.0.1 example.org` is badfiltered by `example.org$badfilter`, and ***not*** by `127.0.0.1 example.org$badfilter`

### Proposed Solution

I propose that https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#-badfilter be rewritten into the following: ↓

————————————————————————————————
The rules with the `$badfilter` modifier disable other basic rules to which they refer. It means that the text of the disabled rule should match the text of the `$badfilter` rule (without the `badfilter` modifier, nor Hosts prefix IPs).

Examples:

* `||example.com$badfilter` disables `||example.com`
* `example.org$badfilter` disables `example.org` and `127.0.0.1 example.org`
* `@@||example.org^$badfilter` disables `@@||example.org^`

————————————————————————————————

### Alternatives Considered

None in particular.

### Additional Information

None that I'm aware of. I'm just not sure how I'd explain to https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter that they need this fix too.

**Comment by ameshkov** [comment]
> This means that 127.0.0.1 example.org is badfiltered by example.org$badfilter, and not by 127.0.0.1 example.org$badfilter

Actually, I don't think we support badfiltering host rules at all. If this works as you described, I am surprised:)

**Comment by DandelionSprout** [comment]
Okay, so testing with a different domain than the one I had originally used (as that one turned out to already be in a whitelist I was using), I am now in the awkward situation that I was pretty wrong about this: 
![image](https://user-images.githubusercontent.com/22780683/126777599-ddbe9ca1-b0a4-4484-82b2-1800dc8523cb.png)

Making the matter furthermore weird, is that the OP's approach actually does work in uBO: 
![image](https://user-images.githubusercontent.com/22780683/126777830-b32d8fb7-d054-4b6d-94d9-6766fbfae545.png)

**Comment by ainar-g** [comment]
@ameshkov, @DandelionSprout, I think I'll simply describe the current behaviour for now.  That is, the fact that `127.0.0.1 example.org$badfilter` isn't supported.

**Comment by ameshkov** [comment]
@DandelionSprout uBO interprets these rules differently. AGH actually returns the IP address specified in the rule and if you have multiple rules it will return multiple IPs. uBO just converts them to something like `||example.org^`.

**Comment by ainar-g** [comment]
I've updated the Wiki page.  Is there anything else left to do here?

**Comment by ainar-g** [comment]
I'll close this one for now, since there were no other proposals.
