### ISSUE TITLE
Entries with two vertical lines in front and one after, are not recognised as valid entries.

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#3371]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.5
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 8GB
* **CPU architecture:**
  * ARM64
* **Operating system and version:**
  * Fedora Workstation 34

### Expected Behavior

Entries with two vertical lines in front and one after, e.g. `||example.org|`, should be recognised by AdGuard Home as valid entries, because `||` means to block all subdomains, while `|` means end-of-domain.

### Actual Behavior

The "Check the filtering" function does not recognise `||example.org|`, `@@||example.org|`, or `||www.nrk.no|` as valid entries.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/126779660-2059b03b-904f-4932-9421-72eda0e07576.png)

</details>

### Additional Information

This discovery was the result of in-depth research for #3369, and was meant to be rather important for the "Doomed until proven to work" attempt to unblock `vk.com` across all major adblockers *and* AdGuard Home in https://github.com/DandelionSprout/adfilt/blob/f86e04ff345afa2090e22b7643f21e370389543c/FalukorvList.txt#L75-L82, until I simply went with `@@/(^|/)vk\.com/?$/` instead.

**Comment by ameshkov** [comment]
@ainar-g this is a legit bug, we have such rules in the AdGuard DNS filter.

**Comment by DandelionSprout** [comment]
Doesn't seem like EugeneOne1 ever took care of this, as the problem still remains.

**Comment by EugeneOne1** [comment]
@DandelionSprout, finally, the latest build in the edge channel should fix the matching of this kind of rules.  Could you please check if it does?

**Comment by DandelionSprout** [comment]
I can confirm it works now. Thanks again.
