### ISSUE TITLE
DNSCrypt queries aren't showing up in the query log at all

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#3372]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.5
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 8GB
* **CPU architecture:**
  * ARM64
* **Operating system and version:**
  * Fedora Workstation 34

### Expected Behavior

Queries made by DNSCrypt clients, show up in the query log.

### Actual Behavior
After I was able to generate a working DNSCrypt address, namely `sdns://AQEAAAAAAAAAEjg0LjIwMi40NC41Mzo1NjQwNCDsdKplWV-GlLOA-lEBpZ11QS381gnDyqpTXz5sSwTaeSwyLmRuc2NyeXB0LWNlcnQuZGFuZGVsaW9uc3Byb3V0LmFzdXNjb21tLmNvbQ`, it didn't take long until I discovered that there weren't any DNSCrypt-tagged queries in the query logs... and that no queries were shown in the log of the two DNSCrypt clients I had set up to use that `sdns://` address.

This is despite the fact that they are being logged in [the verbose log file](https://github.com/AdguardTeam/AdGuardHome/files/6871490/AGHLogFile.txt). Furthermore, entries that are blocked on my server, e.g. `brighteon.social`, are still being blocked as intended for those two DNSCrypt clients.

Additionally, roughly 15% of the times I try to refresh the query log, the error `Error: control/querylog?search=&response_status=&older_than=&limit=20 | Network Error` shows up. The log is also somewhat slower than normal to load in general.

### Screenshots

<details><summary>Screenshot:</summary>

↓ Notice the absence of any queries from clients with the text "PC" or "Moto One Zoom", the two units I had set up DNSCrypt on in their AdGuard for Windows/Android installations.

![image](https://user-images.githubusercontent.com/22780683/126848401-7f9c3bad-edb3-493b-b94e-d92a1f745a10.png)

↓ This was the config I used to generate the DNS stamp. I feel very certain I had (and have) the "No logs" button unchecked.

![image](https://user-images.githubusercontent.com/22780683/126848825-b5a11820-d478-4c6c-92ec-44c0f8442ec1.png)

</details>

### Additional Information

Related to, but not a clone of, #2662

**Comment by DandelionSprout** [comment]
I'm seldom the best at looking through verbose debug logs, but one type of lines has drawn my attention since I posted the OP:

`2021/07/24 00:43:14.788226 2643#214 [error] querylog: adding record: no client ip, skipping`

wut

**Comment by ainar-g** [comment]
Thank you for your report and sorry for the long waiting.  I've confirmed that something is definitely wrong there.  We'll fix it in the nearest couple of days.

**Comment by EugeneOne1** [comment]
@DandelionSprout, this should be fixed in the latest edge build.  Could you please install it and check if our solution works for you?

**Comment by DandelionSprout** [comment]
I'll make sure to test it tomorrow.

**Comment by DandelionSprout** [comment]
Seems to indeed have been fixed in v0.107.0-a.113+fc063f58
