### ISSUE TITLE
Problem on initial setup (Windows)

### ISSUE THREAD

**Issue by PtDragon** [AdguardTeam/AdGuardHome#3375]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  AdGuard Home v0.106.3 Latest 
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * Not a router, Windows 10 x64
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 10 x64 with all latest updates

### Actual Behavior

Error: control/install/configure | dnsServer.Prepare: setting up resolvers: systemResolvers: can't get addresses: start command executing: open NUL: The system cannot find the file specified. | 500
### Screenshots

Finish configuration fully ignoring DNS setting of system as they can be defined later.
<details><summary>Screenshot:</summary>
![изображение](https://user-images.githubusercontent.com/5212271/126903417-e5d5923f-f110-4935-9cdc-6d65a9cdafeb.png)

</details>

**Comment by ainar-g** [comment]
Hello and thank you for your report!  If you open a console—either `cmd.exe` or a Powershell one—and type something like `nslookup adguard.com`, does it show a valid DNS request result or an error along the lines of `executable not found`?

**Comment by PtDragon** [comment]
> 
> 
> Hello and thank you for your report! If you open a console—either `cmd.exe` or a Powershell one—and type something like `nslookup adguard.com`, does it show a valid DNS request result or an error along the lines of `executable not found`?

Server:  UnKnown
Address:  192.168.4.134

Non-authoritative answer:
Name:    adguard.com
Addresses:  104.20.91.49
          172.67.3.157
          104.20.90.49

**Comment by ainar-g** [comment]
Sorry for the late reply.  Is there any kind of antivirus software that could prevent AGH from executing correctly?

**Comment by PtDragon** [comment]
No antivirus no firewall at all (Microsoft ones are disabled and no others installed).

**Comment by ainar-g** [comment]
I see, thanks.  The most recent `edge` channel release, v0.107.0-a.152+2365ddd2, should contain some logging improvements.  Could you please test it when you have the time and report the results?
