### ISSUE TITLE
in-addr.arpa sorry to keep bringing this up.. 

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#3376]
AdGuard Home, version v0.107.0-b.5

![image](https://user-images.githubusercontent.com/55087301/126903591-b52fb74b-eb99-486d-9a6c-72d1eab5ccca.png)
Looks like supported syntax

![image](https://user-images.githubusercontent.com/55087301/126903612-776f7b48-29e5-445f-9c48-80926e494c1e.png)
Looks like correct settings

`[I] bcook@voidlnx /o/AdGuardHome> drill brian.wireguard @192.168.10.100
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 30363
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; brian.wireguard.     IN      A

;; ANSWER SECTION:
brian.wireguard.        2400    IN      A       172.16.42.1

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 192.168.10.100
;; WHEN: Sun Jul 25 10:57:11 2021
;; MSG SIZE  rcvd: 49
`
working as configured for A

`[I] bcook@voidlnx /o/AdGuardHome> drill -x 172.16.42.1 @192.168.10.100
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 12571
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; 1.42.16.172.in-addr.arpa.    IN      PTR

;; ANSWER SECTION:

;; AUTHORITY SECTION:
1.42.16.172.in-addr.arpa.       10      IN      SOA     fake-for-negative-caching.adguard.com. hostmaster.1.42.16.172.in-addr.arpa. 100500 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 192.168.10.100
;; WHEN: Sun Jul 25 10:58:10 2021
;; MSG SIZE  rcvd: 174
`
not working as configured for PTR

`[I] bcook@voidlnx /o/AdGuardHome [SIGINT]> drill -p 531 -x 172.16.42.1 @192.168.10.105
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 28830
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; 1.42.16.172.in-addr.arpa.    IN      PTR

;; ANSWER SECTION:
1.42.16.172.in-addr.arpa.       2400    IN      PTR     brian.wireguard.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 192.168.10.105
;; WHEN: Sun Jul 25 10:59:39 2021
;; MSG SIZE  rcvd: 71
`
Upstream working for PTR

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains

I think I'm following the syntax.

If I break the config down to 

[/wireguard/]192.168.10.105:531
[/16.172.in-addr.arpa/]192.168.10.105:531

The results are the same.. 

Make it more qualified

[/42.16.172.in-addr.arpa/]192.168.10.105:531 

All reacts the same

[/16.172.in.addr.arpa./]192.168.10.105:531 

gives an errror:
Error: control/dns_config | wrong upstreams specification: wrong hostname specification: 16.172.in-addr.arpa. | 400

Update.. 
![image](https://user-images.githubusercontent.com/55087301/126903941-453b3cc8-de66-4828-961b-6254ad84b544.png)

I used to have 192.168.10.100 and 192.168.10.200 in the local system /etc/resolv.conf

the 200 was nothing functional.. so everything should be going to the 100.. Adguard was using the 200.. (as shown in the first pictures) but when I removed the 200 from resolv.conf it then shows this.. 

But still does not seem to correctly forward the PTR as specified in upstream

`  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - 192.168.10.128
  - '[/wireguard/16.172.in-addr.arpa/]192.168.10.105:531'
  - '[/vlan10.dns/168.192.in-addr.arpa/]192.168.10.105:531'
  upstream_dns_file: ""
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  local_domain_name: lan
  resolve_clients: true
  use_private_ptr_resolvers: false
  local_ptr_upstreams: []
`

The config settings seem to match the gui.. 

Thanks in advance.

**Comment by bcookatpcsd** [comment]
192.168.10.128 is also working correctly for PTR.. 

`[I] bcook@voidlnx /o/AdGuardHome> drill -x 172.16.42.1 @192.168.10.128
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 3864
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; 1.42.16.172.in-addr.arpa.    IN      PTR

;; ANSWER SECTION:
1.42.16.172.in-addr.arpa.       2400    IN      PTR     brian.wireguard.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; EDNS: version 0; flags: ; udp: 4096
;; SERVER: 192.168.10.128
;; WHEN: Sun Jul 25 11:14:39 2021
;; MSG SIZE  rcvd: 106
`

**Comment by ainar-g** [comment]
We have updated the [rDNS upstream configuration section](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-rdns) of our Wiki.  `in-addr.arpa` domains with locally served networks, including the `192.168.0.0/16` ones shouldn't be in the main upstream input, so your configuration is partially invalid.  Please read the new documentation and tell us if there is anything missing.

**Comment by bcookatpcsd** [comment]
For personal use that looks like it would work, I'll try it and report back. I'm also trying to use this for work, where I have various 10.20.0.0/20 (ten buildings worth) along with corresponding 172.16.0.0/24's and 10.120.0.0/24's

Having various authoritative end points..

So I will always be looking for more than one ptr authority..

Thanks for always responding.

**Comment by bcookatpcsd** [comment]
![image](https://user-images.githubusercontent.com/55087301/127054927-375423ab-659a-4dec-a939-0538f973c242.png)

This works..  but it wasn't clear from the documentation that it would work.. I needed to re-read it a few times.. 

But this does work and forwards correctly..

**Comment by ainar-g** [comment]
Glad that the documentation helps.  The labels on the inputs themselves need more work, and we'll probably add a UI hint about private vs. public upstreams at some point.  If there are no other questions here, I'll close the issue, if you don't mind.
