### ISSUE TITLE
DHCP only resolves Apple devices' name

### ISSUE THREAD

**Issue by ztxgoo** [AdguardTeam/AdGuardHome#3378]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v107.0b.5
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * MikroTik RouterBOARD RB750Gr3 hEX
* **CPU architecture:**
  * MIPS
* **Operating system and version:**
  * Openwrt 19.07.7

### Expected Behavior

Correctly resolves all lan devices' IPs into names.
### Actual Behavior

Only resolves Apple devices' names, other devices show up as IPs.

### Additional Information

Openwrt with AdGuardHome running as sole DNS and DHCP provider (dnsmasq and odhcpd uninstalled).

```
cat /etc/resolv.conf
nameserver 127.0.0.1
```

**Comment by ainar-g** [comment]
Good day.  What do you mean by “resolves Apple devices' names”?  Can you provide an example of a query, for example an `nslookup` one, that succeeds for an Apple device but not for a different device?  A possibly anonymised screenshot of the “DHCP leases” section on the “DHCP settings” page would also be appreciated.

**Comment by ztxgoo** [comment]
Thanks for the speedy reply, by that I mean name resolution only works on Apple devices for some reason.

<img width="1196" alt="Screen Shot 2021-07-27 at 7 50 14 PM" src="https://user-images.githubusercontent.com/87951538/127121364-d29228fa-ba2a-41af-8bae-3351f296b309.png">

![Screenshot_20210727-195303_Settings](https://user-images.githubusercontent.com/87951538/127121386-13504b59-f46d-4493-ba3b-8f6be3b7348e.png)


_Android phone showed up without its device name resolved._

![Screenshot_20210727-200702_Terminal_Emulator](https://user-images.githubusercontent.com/87951538/127120910-e59b8a65-8c11-423e-a3fd-c3c9e4cdbfe3.png)


_I only managed to do a nslookup on my other Android phone but the result only confuses me further.(Android might have their own system-wide-hard-coded dns?)_

**Comment by ztxgoo** [comment]
Btw I don't have any upstream private reverse DNS in place I thought ADH alone would suffice.

**Comment by ainar-g** [comment]
Yes, these lines show that your device isn't using `192.168.1.1`:

```none
Server:         8.8.4.4
Address:        8.8.4.4:53
```

This could happen when you try to manually change the address of the DNS server that AGH sends.  Are you using any DHCP options?

**Comment by ztxgoo** [comment]
Indeed, it's using Google dns instead of the local dns although I also suspect that some apps on Android don't respect systems dns (https://www.reddit.com/r/pihole/comments/iivdgq/psa_termux_on_android_does_not_use_system_dns/), which could be the case in the screenshot too?

For DHCP settings I just set up the ipv4 setting under admin page, with listening interface being lan(192.168.1.1)and gateway ip as same.

**Comment by ztxgoo** [comment]
Bumped into this page which leads me to believe this cloud be an Android thing.

https://community.spiceworks.com/topic/2218883-android-devices-wont-resolve-local-server-names
