### ISSUE TITLE
Use system timezone 

### ISSUE THREAD

**Issue by muhlinux** [AdguardTeam/AdGuardHome#3383]
### Problem Description

The date is shown based on your browser's locale, not the machine where AdGuard is running. This can cause mismatch of time because of browser privacy settings  (like #2919)

### Proposed Solution

An option to use the system (docker or server) timezone would make the time consistent across all devices, no matter what. :+1:

**Comment by ainar-g** [comment]
Mostly a dup of #3079, so I'll merge this one into that one, if you don't mind.
