### ISSUE TITLE
mobileconfig generation for DoH missing port number

### ISSUE THREAD

**Issue by webmihir** [AdguardTeam/AdGuardHome#3384]
I am running my https server on a custom port (8002) for various reasons. When attempting to generate the DoH mobileconfig file for iOS, there is no way to enter the port number in hostname (adding a hostname:8002 at the end shows error).

After generating the .mobileconfig file I opened it in a text editor to check, and the port number is not present anywhere in the file. the following line exists in my config file:

<string>https://hostname/dns-query/client-id</string>

I am expecting the generated file to instead have:
<string>https://hostname:8002/dns-query/client-id</string>

**Comment by ainar-g** [comment]
Are you running v0.106.3?  Sounds like a dup of #3172.

**Comment by webmihir** [comment]
Thanks. You're right- I switched to the beta channel and see this is already fixed. Thank you!
