### ISSUE TITLE
Support for HTML pages as source list (with tested code solution)

### ISSUE THREAD

**Issue by BigB84** [AdguardTeam/AdGuardHome#3385]
### Problem Description

HTML pages lists are not supported, like great [yoyos one](https://pgl.yoyo.org/adservers/serverlist.php?showintro=0;hostformat=hosts)

### Proposed Solution

Use HTML parser/web automation lib and try to make content readable without html tags `<body>` `<p>` tags

### Alternatives Considered

This is sample code I tested. 

It downloads file, if url contains `.html` or `.php` it uses [this great lib](https://github.com/jaytaylor/html2text) that parses html from reader and saves to file.

I haven't been reading your code so I don't know how you store records, but you can optimize it for your needs as parsed webpage is returned as string  

````
import (
	"fmt"
	"io"
	"net/http"
	"os"
	"runtime"
	"strings"

	"jaytaylor.com/html2text"
)

func SmartDownloadFile(filepath string, url string) (err error) {
	// Create the file
	out, err := os.Create(filepath)
	if err != nil {
		panic(err)
	}

	// Get the data
	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	// Check server response
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("bad status: %s", resp.Status)
	}

	if strings.Contains(url, ".php") || strings.Contains(url, ".html") {
		// If we recognize that file is html we have to render
		text, err := html2text.FromReader(resp.Body)           // Parsing here
		if err != nil {
			panic(err)
		}
		out.WriteString(text)
		runtime.GC()

	} else {

		// Writer the body to file
		_, err = io.Copy(out, resp.Body)
		if err != nil {
			return err
		}
	}
	out.Close()
	return nil
}

````

### Additional Information

I'm still new to go(lang) but if you point me `.go` file in what you do mentioned processing I can try make a pull request. :) 

I love this project :heart:

**Comment by ameshkov** [comment]
I believe adding this support to AGH may lead to unexpected results, for instance when people add a random web page as a filter source.

Instead of adding native support for this, I suggest you create a repo and re-host yoyo's list in the plain-text format and then use it. For instance, you could write a Github Action that does just that.
