### ISSUE TITLE
DNS allowlists component ignore adblock rules

### ISSUE THREAD

**Issue by Aikatsui** [AdguardTeam/AdGuardHome#3396]
#### Issue Description

(create allowlist.txt file)
1. Add `||github*^$important`
2. Add `@@|raw.githubusercontent.com^`

Check any github name related domain

Ubuntu 20.04.2 | v0.106.1-SNAPSHOT-a0abad66

**Comment by DandelionSprout** [comment]
`||` + `$important`, overrides `@@` without `$important`.

`@@|raw.githubusercontent.com^$important` should most likely work.

**Comment by Aikatsui** [comment]
No. If add `||github*^$important` in an allowlist file then it consider as whitelist rule for everything eg: `api.github.com`, `githubapp.com`, `github.io`, `github.githubassets.com` etc.

**Comment by ameshkov** [comment]
Works as expected, all github* domains are marked as allowed in the query log.

**Comment by Aikatsui** [comment]
It's possible to use DNS blocklists component for both block/unblock access purposes then i thought allowlist component work same as it but it treat both `||` and `@@||` as a same thing 😃
