### ISSUE TITLE
Failed to sufficiently increase receive buffer size when using DoQ

### ISSUE THREAD

**Issue by martinspaniol** [AdguardTeam/AdGuardHome#3399]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Docker Image on Synology Diskstation

### Expected Behavior
When starting the AdGuardHome docker container the buffer should be increased as needed.

### Actual Behavior
On startup the following error occurs:
`failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.`

According to the linked github article the buffer can be increased using `sysctl -w net.core.rmem_max=2500000`. Maybe this can be implemented in the docker container.

**Comment by ameshkov** [comment]
The problem is that it's not possible to run sysctl commands in a Docker container:
https://stackoverflow.com/questions/54845095/cannot-run-sysctl-command-in-dockerfile

**Comment by PietroMB** [comment]
There are any solutions?
I've the same problem
