### ISSUE TITLE
Accept any value for log rotation and stats retention durations

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#3404]
(Description added by @ainar-g on 2021-11-03.)

Currently, we only accept a subset of values for the query log rotation time and statistics retention duration settings.  But there is basically no reason to not just allow users to set their own values there, however big or small.

**Comment by ainar-g** [comment]
I personally think that sooner or later we'll just have to remove the enum and simply accept any reasonable duration.  Perhaps leaving the predefined values on the UI.  @ameshkov, what do you think?

**Comment by ameshkov** [comment]
Why not

**Comment by Disqu3-mirOir-qt** [comment]
i think good idea too add custum input hours log retention

**Comment by mailforvenky** [comment]
I second this, i think pi hole shows stats since install and so should AG Home

**Comment by IOAyman** [comment]
Is there any ETA for this, please?

**Comment by ainar-g** [comment]
Implemented in the latest Edge builds.
