### ISSUE TITLE
Panic when validating TLS certificate

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#3411]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.107.0-b.6
* **How did you install AdGuard Home:**
  *  GitHub releases

* **Operating system and version:**
  *  macOS BigSur version: 11.5 (20G71)

### Steps to reproduce
1. Run AdGuard Home service
2. Open web interface and go to Encryption settings
3. Enter the server name, Enable **Redirect to HTTPS automatically** feature, set certificate path, set a private key and press **Save configurations**
4. Wait for a while (usually less than a minute)
5.  AdGuard Home service stops responding

> Note: In my case is being used Certificate with invalid chain

#### Logs
>2021/08/03 17:09:49.368860 2750#15 [debug] web: plain: http: panic serving 127.0.0.1:53048: cannot handle unexported field at {home.tlsConfigSettings}.TLSConfig.cert:
	"github.com/AdguardTeam/AdGuardHome/internal/dnsforward".TLSConfig
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported

**Comment by ainar-g** [comment]
Will ship in the next few days with v0.107.0-b.7.
