### ISSUE TITLE
Accept client IDs from hostnames in DoH as well

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#3418]
Currently, the DoQ and DoT servers accept client IDs from the hostname (e.g. `CLIENT-1.example.com`), while the DoH one, from the path in the URL (e.g. `https://example.com/dns-query/CLIENT-1`).  @ameshkov proposes that the DoH server should also try and get the client ID from the hostname, but only if there is no client ID in the URL path.  That is, a request for `https://CLIENT-1.example.com/dns-query/CLIENT-2` will be processed as a request for `CLIENT-2` and **not** `CLIENT-1`.

@ameshkov, is this correct?

**Comment by ameshkov** [comment]
That's right
