### ISSUE TITLE
s3.us-west-1.wasabisys.com erroneously blocked as adult website

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdGuardHome#3421]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [* ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  v0.106.3
* **How did you install AdGuard Home:**
 Baked into Gl-iNet firmware 1.05
* **How did you setup DNS configuration:**
 9.9.9.9
149.112.112.112
* **If it's a router or IoT, please write device model:**
 Brume GL-MV1000
* **CPU architecture:**
  arm
* **Operating system and version:**
  macOS 10.15.7

### Expected Behavior
lets user connect to wasabi

### Actual Behavior
blocks s3.us-west-1.wasabisys.com as adult website
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Fixed it, thank you
