### ISSUE TITLE
Allow to change height of inputs in DNS settings

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#3438]
### Problem Description
6 lines is too few
![image](https://user-images.githubusercontent.com/8361299/129042272-64b75699-e878-4796-91a5-b558d86f2b3e.png)

### Proposed Solution
Auto resize when adding new lines(may be limited for example by 10-15 lines)

### Alternatives Considered
Make text input(s) resizable by dragging like there
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/129042953-82f5b18e-2e2b-42dc-8dd5-b4792dec2554.png)

</details>

**Comment by IldarKamalov** [comment]
Closed by https://github.com/AdguardTeam/AdGuardHome/commit/91c1c9e61d8c984251f1b59988b2b2867dd48ea0
