### ISSUE TITLE
Limit time waiting for upstream DNS servers

### ISSUE THREAD

**Issue by nep-0** [AdguardTeam/AdGuardHome#3439]
### Problem Description

Option "Fastest IP address" is too slow sometimes.

### Proposed Solution

Instead of waiting for all upstream DNS servers to respond, allow users to customize the maximum time on waiting. If exceed the time, pick the fastest IP from the responses that **has been received**.

**Comment by ainar-g** [comment]
Looks like a dup of #1992.
