### ISSUE TITLE
DHCP does not work after v0.106.3

### ISSUE THREAD

**Issue by kgnfth** [AdguardTeam/AdGuardHome#3447]
Actually it works if the ip is in the same subnet but my ips are not in the same subnet of  `95.***.***.12`
i am running a dedicated proxmox server on 
`95.***.***.12` main proxmox ip
Gateway: `95.***.***.1`
Netmask: `255.255.255.192`
Broadcast: `95.***.***.63`

and i have a subnet 
`135.***.**.32/29` adguard is using static ip `135.***.**.32`
Gateway: `95.***.***.12`
Netmask: `255.255.255.248`
Broadcast: `135.***.**.39`

![raw](https://user-images.githubusercontent.com/73314940/129391309-0198a2b9-d18c-4185-854a-4b3702c2505d.png)

i have created a Adguard virtual machine in proxmox to use as a dhcp server for my other proxmox virtual machines,
in version `v0.106.3` it was working just fine, but after upgrading, my DHCP static leases are gone.

DHCP Leasing still works see image

![ysvM1mQoIF](https://user-images.githubusercontent.com/73314940/129390721-26bc9ad3-d289-4a19-be23-00d41c1703de.png)

but adding a DHCP static lease does not work because its not in the same subnet of `95.***.***.12` which actually makes sense
but again it worked great in `v0.106.3`, thats why i used Adguard as a dhcp server
![image](https://user-images.githubusercontent.com/73314940/129390998-9792fb89-f502-4bde-b72c-835c6571cf49.png)

**Comment by ainar-g** [comment]
Hello and thank you for the thorough report.  If AGH is available on the `135.***.**.32` address, why not make that address the gateway?

**Comment by kgnfth** [comment]
@ainar-g LoL it works 🤦‍♂️, and DHCP static leases are back when i set the gateway to `135.***.**.32`

The reason i opened this issue without testing it again with `135.***.**.32` is because when i fist used AGH it did not work with that ip, thats the reason i used `95.***.***.12` as gateway

**Comment by ainar-g** [comment]
I see.  So, the issue is solved now?

**Comment by kgnfth** [comment]
Yes
