### ISSUE TITLE
Improved query log search

### ISSUE THREAD

**Issue by webmihir** [AdguardTeam/AdGuardHome#3448]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Problem Description
In query log, there is no way to do exact matches. For example, when searching for "198.168.1.1", it also returns results for "192.168.1.100".

### Proposed Solution
Add ability to do "exact match" queries, perhaps by allowing search queries with double-quotes around them. For example, instead of searching for 192.168.1.1 I can search for "192.168.1.1" (with quotes) - the latter would not include results for 192.168.1.100

### Additional Information
x.x.x.1 is usually the gateway/router in the home, and a common query to search. Several other devices in the home network will have an IP address that will be in x.x.x.100 to x.x.x.199 range which would all get returned when searching for x.x.x.1.

**Comment by ainar-g** [comment]
Hello.  What version are you using?  The current query log works exactly like you described.

**Comment by r1bnc** [comment]
I am using docker build v0.106.3 but has that problem too. It doesnt display the exact match.

**Comment by ainar-g** [comment]
@webmihir, @r1bnc, we still cannot reproduce this.  Can any of you send a screenshot of a query log with value *manually* entered with double quotes and not showing the correct results?  Thanks.

**Comment by r1bnc** [comment]
![image](https://user-images.githubusercontent.com/8337343/130439715-85f42db2-bbd6-452c-aadb-69a55788ec62.png)

If you click the `Click to view queries` for an specific client is where it fails. As shown below, it shows the target search IP but when you scroll down for more logs, it shows other client IP.

![image](https://user-images.githubusercontent.com/8337343/130440019-9865343f-28b6-4564-a3e7-8b9c1ba6e991.png)

But I we manually go to All Queries, and type to the search  "X.X.X.X" it seems to work fine.

**Comment by ainar-g** [comment]
@r1bnc, thanks for the screenshots.  That's issue #3312.  Which is why I specifically mentioned “manually”.  We'll fix that one before the final release.

@webmihir, does your issue also only concern clicks on IPs in the log and on the dashboard?

**Comment by webmihir** [comment]
Thanks @ainar-g - I agree, I am unable to reproduce it by manually quoting. I had the same experience as @r1bnc which is tracked via #3312.

**Comment by ainar-g** [comment]
Thanks for the information.  I'm going to merge this into that issue then.
