### ISSUE TITLE
"couldn't initialize statistics module" error on the clean install of AdGuard Home

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#3450]
`Error: control/install/configure | couldn't initialize statistics module | 500`

![image](https://user-images.githubusercontent.com/5947035/129444441-1006d474-8ded-42b0-adbc-01e3a2dabf12.png)

The problem seems to be with the installation script. To reproduce this issue, I install AGH release first, then reinstalled edge (without removing anything before), and then I ran into this issue.

Also, the second issue is with the uninstall script -- it does not stop the running AdGuard Home instance.

**Comment by sysadmin-info** [comment]
```
sudo systemctl stop AdGuardHome.service
sudo systemctl disable AdGuardHome.service
cd 
cd AdGuardHome
sudo ./AdGuardHome -s uninstall
sudo reboot
cd
cd AdGuardHome
sudo ./AdGuardHome -s install
```

problem solved

Just in case. You can download the package and extract it this way
```
cd
wget https://static.adguard.com/adguardhome/release/AdGuardHome_linux_arm.tar.gz
sudo tar xvf AdGuardHome_linux_arm.tar.gz
```

Problem solved.
