### ISSUE TITLE
get the real IP from user with Cloudflare

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdGuardHome#3451]
Understanding the True-Client-IP Header:
https://support.cloudflare.com/hc/en-us/articles/206776727-Understanding-the-True-Client-IP-Header

Configuring Cloudflare IP Geolocation:
https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation

![image](https://user-images.githubusercontent.com/75058881/129447721-563644e4-7b5d-45c4-9579-79651243ae2c.png)

![image](https://user-images.githubusercontent.com/75058881/129447718-76815744-f771-4ec6-b209-c97347f67808.png)

Restoring original visitor IPs:
https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs

or...... you will get these:
![image](https://user-images.githubusercontent.com/75058881/129447679-9278fd1f-449b-4404-9d8b-c5a55b8e266f.png)

**Comment by ainar-g** [comment]
What version are you using?  This should be fixed on beta with `trusted_proxies`, see #2799.

**Comment by c2xusnpq6** [comment]
> What version are you using? This should be fixed on beta with `trusted_proxies`, see #2799.

```
v0.107.0-b.7
```
![image](https://user-images.githubusercontent.com/75058881/129595016-9df03dab-c585-4521-a22c-80a274f76e07.png)

**Comment by ainar-g** [comment]
@c2xusnpq6, have you set the `trusted_proxies` setting?

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6, have you set the `trusted_proxies` setting?

But I am using Cloudflare, and how do I set it up to get the real user IP? pls help...😬

**Comment by EugeneOne1** [comment]
@c2xusnpq6, you can find the description of the whole configuration file  [here](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).  In short, there is a new setting in the `AdGuardHome.yaml` configuration file called `trusted_proxies`, it accepts both IP addresses and CIDR networks.  To make AdGuard Home extract the real visitor's address from request's headers, appended by proxy server, the server itself should be "trusted", so just put the address of your one into this field.

**Comment by leo15dev** [comment]
@c2xusnpq6 Try to add this [ IP Ranges ](https://www.cloudflare.com/ips) in the trusted_proxies in the AdGuardHome.yaml , it should solve your problem. When Cloudflare updates their IP Ranges, they will publish on that Page.
