### ISSUE TITLE
Create static lease from dynamic lease

### ISSUE THREAD

**Issue by anbraten** [AdguardTeam/AdGuardHome#3459]
### Problem Description

In addition to create a new static release from scratch, it would be nice to use some data from the current dynamic leases list, to support the user at finding the correct mac address of a new device for example.

### Proposed Solution

To further improve UX to easier add a new static release it would be nice if we add some button behind all dynamic leases which allows to transform a dynamic release to a static one, by somehow opening the add static lease popup and pre-set the mac, hostname and ip. This allows the user to simply convert a dynamic lease to a static one and further edit the static lease (choosing a different IP) if wanted, but helps finding out the mac for example.

**Comment by ainar-g** [comment]
@anbraten, hello.  We have finally added this feature in the recent Edge builds, and it's going to be released in Beta and Release soon.  Could you please check if the UI works for you?

**Comment by anbraten** [comment]
Awesome. Thanks for the info. I will give it a try.
