### ISSUE TITLE
Send fake IP value to DNS server to enhance privacy

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdGuardHome#3460]
`What IP (range) do you want to use?`
`2.16.9.78` (Germany) / `2.16.9.78/24` / `EU` / `JP` `TW` (for asian user?) / `CH` 

`EDNS Client Subnet`🤔

**Comment by c2xusnpq6** [comment]
It may cause a longer loading time, but... 😙

**Comment by ameshkov** [comment]
Duplicate of #2514
