### ISSUE TITLE
DHCP server not working on v0.107.0-b.6 through v0.107.0-b.8 (docker/pi)

### ISSUE THREAD

**Issue by devinslick** [AdguardTeam/AdGuardHome#3462]
### Prerequisites
- [ x] I am running the latest version  (reproduceable on b6, b7, and b8).  DHCP is not working on any of them.
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details
* **Version of AdGuard Home server:**
    v0.107.0-b.6 and later
* **How did you install AdGuard Home:**

  sudo docker run -d --name adguard --cap-add=NET_ADMIN --net=host -v /docker/adguard/work/:/opt/adguardhome/work -v /docker/adguard/conf/:/opt/adguardhome/conf -v /docker/adguard/logs/:/var/log/agh -v /docker/ssl:/ssl:ro --restart unless-stopped adguard/adguardhome:v0.107.0-b.6

* **How did you setup DNS configuration:**
  Clients -> Pi (AGH) -> External

* **If it's a router or IoT, please write device model:**
  Raspberry Pi 2 Model B

* **Operating system and version:**
 Raspbian 10

### Expected Behavior
AGH DHCP should be able to issue/renew IP address leases

### Actual Behavior
Clients behave as if there is no DHCP server on and after v0.107.0-b.6

### Screenshots
Not applicable

### Logs
2021/08/17 12:56:26.563039 [info] AdGuard Home, version v0.107.0-b.8
2021/08/17 12:56:26.681363 [info] dhcp: loaded leases v4:161  v6:0  total-read:161 from DB
2021/08/17 12:56:26.795240 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2021/08/17 12:56:26.795869 [info] auth: initialized.  users:2  sessions:3
2021/08/17 12:56:26.800326 [info] number of certs - 3
2021/08/17 12:56:26.800421 [info] got an intermediate cert
2021/08/17 12:56:26.800664 [info] got an intermediate cert
2021/08/17 12:56:27.100724 [info] Initialize web module
2021/08/17 12:56:27.261169 [info] dhcpv4: listening
[dhcpv4] 2021/08/17 12:56:27 Server listening on 0.0.0.0:67
[dhcpv4] 2021/08/17 12:56:27 Ready to handle requests
2021/08/17 12:56:27.263991 [info] AdGuard Home is available at the following addresses:
2021/08/17 12:56:27.264712 [info] Go to https://REDACTED.REDACTED:443
2021/08/17 12:56:27.267279 [info] Go to http://127.0.0.1:80
2021/08/17 12:56:27.267715 [info] Go to http://127.0.0.1:3001 (BETA)
2021/08/17 12:56:27.268010 [info] Go to http://[::1]:80
2021/08/17 12:56:27.268278 [info] Go to http://[::1]:3001 (BETA)
2021/08/17 12:56:27.268498 [info] Go to http://REDACTED-IP:80
2021/08/17 12:56:27.268716 [info] Go to http://REDACTED-IP:3001 (BETA)
2021/08/17 12:56:27.268940 [info] Go to http://172.17.0.1:80
2021/08/17 12:56:27.269156 [info] Go to http://172.17.0.1:3001 (BETA)
2021/08/17 12:56:29.249308 [info] Starting the DNS proxy server
2021/08/17 12:56:29.249409 [info] Cache TTL override is enabled. Min=600, Max=10800
2021/08/17 12:56:29.250193 [info] The server is configured to refuse ANY requests
2021/08/17 12:56:29.250277 [info] DNS cache is enabled
2021/08/17 12:56:29.250769 [info] MaxGoroutines is set to 50
2021/08/17 12:56:29.251219 [info] Creating the UDP server socket
2021/08/17 12:56:29.252392 [info] Listening to udp://[::]:53
2021/08/17 12:56:29.252449 [info] Creating a TCP server socket
2021/08/17 12:56:29.253172 [info] Listening to tcp://[::]:53
2021/08/17 12:56:29.253226 [info] Creating a TLS server socket
2021/08/17 12:56:29.254073 [info] Listening to tls://[::]:853
2021/08/17 12:56:29.254138 [info] Creating a QUIC listener
2021/08/17 12:56:29.260157 failed to sufficiently increase receive buffer size (was: 176 kiB, wanted: 2048 kiB, got: 352 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2021/08/17 12:56:29.261459 [info] Listening to quic://[::]:784
2021/08/17 12:56:29.261793 [info] Entering the UDP listener loop on [::]:53
2021/08/17 12:56:29.264367 [info] Entering the DNS-over-QUIC listener loop on [::]:784
2021/08/17 12:56:29.265010 [info] Entering the tls listener loop on [::]:853
2021/08/17 12:56:29.265583 [info] Entering the tcp listener loop on [::]:53
[dhcpv4] 2021/08/17 12:56:31 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:31.436580 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:56:35 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:35.951477 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:56:40 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:40.452721 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:56:44 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:44.962256 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:56:49 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:49.470469 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:56:53 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:53.977364 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:56:58 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:56:58.489391 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:02 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:02.995627 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:07 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:07.508235 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:11 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:12.013295 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:15 Handling request from 0.0.0.0:68
2021/08/17 12:57:15.623062 [info] dhcpv4: hostname "CLIENT-NAME" already exists
2021/08/17 12:57:15.638378 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:16 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:16.520149 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:16 Handling request from 0.0.0.0:68
2021/08/17 12:57:16.717804 [info] dhcpv4: hostname "CLIENT-NAME" already exists
2021/08/17 12:57:16.732960 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:18 Handling request from 0.0.0.0:68
2021/08/17 12:57:18.612153 [info] dhcpv4: hostname "CLIENT-NAME" already exists
2021/08/17 12:57:18.626598 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:20 Handling request from 0.0.0.0:68
2021/08/17 12:57:20.642703 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:21 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:21.028992 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:21 Handling request from 0.0.0.0:68
2021/08/17 12:57:21.734072 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:23 Handling request from 0.0.0.0:68
2021/08/17 12:57:23.908774 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:25 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:25.538725 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:27 Handling request from 0.0.0.0:68
2021/08/17 12:57:27.874405 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:30 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:30.046698 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:34 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:34.558715 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:36 Handling request from 0.0.0.0:68
2021/08/17 12:57:36.608732 [info] dhcpv4: hostname "CLIENT-NAME" already exists
2021/08/17 12:57:36.624250 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:37 Handling request from 0.0.0.0:68
2021/08/17 12:57:37.651807 [info] dhcpv4: hostname "CLIENT-NAME" already exists
2021/08/17 12:57:37.666703 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:39 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:39.078861 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:39 Handling request from 0.0.0.0:68
2021/08/17 12:57:39.493857 [info] dhcpv4: hostname "CLIENT-NAME" already exists
2021/08/17 12:57:39.509070 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:41 Handling request from 0.0.0.0:68
2021/08/17 12:57:41.631527 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:42 Handling request from 0.0.0.0:68
2021/08/17 12:57:42.555731 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:43 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:43.575389 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:44 Handling request from 0.0.0.0:68
2021/08/17 12:57:44.558623 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:48 Handling request from REDACTED-CLIENT-IP:68
2021/08/17 12:57:48.082170 [info] dhcp: stored 161 leases in db
[dhcpv4] 2021/08/17 12:57:48 Handling request from 0.0.0.0:68
2021/08/17 12:57:48.683684 [info] dhcp: stored 161 leases in db

### Additional Information
Network is a flat /24.  

Tested rolling back b7 to v6. This didn't fix the issue
Tested rolling back b6 to v5. This did fix the issue.
Tested upgrading b5 to the new b8. This caused the issue again.
Rolled back to b5 and this fixed the issue again.

**Comment by ainar-g** [comment]
Thank you for your report.  By “not working”, do you mean that the clients don't receive IPs at all?  Also, can you collect [verbose logs] and either attach them here or send them to devteam@adguard.com?

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by devinslick** [comment]
Yes, that's what I meant.  No IPs are being issued and existing IPs are not being renewed.  
I'll reproduce the issue and send the logs.    Thank you!

**Comment by ainar-g** [comment]
We have received the logs, thanks.  I'm not sure when we'll be able to properly analyse them, but we do want to fix as many DHCP issues before the final release as possible.

**Comment by EugeneOne1** [comment]
@devinslick, we've just pushed the latest build to the edge channel.  It should recover DHCP server's behavior as it was in v0.107.0-b.5.  Could you please check, if it works properly?

**Comment by devinslick** [comment]
Thanks @EugeneOne1 ! It works perfectly.  It's good to be back on the latest branch.
