### ISSUE TITLE
Errors with edge Version:  v0.107.0-a.136+550b1798

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#3479]
Versions | OPNsense 21.7.1-amd64FreeBSD 12.1-RELEASE-p19-HBSDOpenSSL 1.1.1k 25 Mar 2021

CPU type | AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G (4 cores)

Install latest edge version AdguardHome in,but always show me errors.
![Screenshot from 2021-08-21 05-51-50](https://user-images.githubusercontent.com/17021524/130297514-bed01933-6c56-4752-8a3e-78f5f6d3d734.png)

Hope to fix them quickly ,because I could not see anything information in dashboard,could not to add more rules.
Thank you!

**Comment by ameshkov** [comment]
I cannot reproduce this.

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by jkle112** [comment]
Sorry,I installed a new opnsense , maybe the system add more applications to spend more memory,I deal with the problem: close another applications, added more rules in,then start all applications,I guess Adguard home upgrade the configuration need spend more money.
Thank you, maybe could close the problem, optimization memory is more better.
