### ISSUE TITLE
DHCP and HDHomeRun issue

### ISSUE THREAD

**Issue by kour1er** [AdguardTeam/AdGuardHome#3480]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.107.0-b.8
* **How did you install AdGuard Home:**
  * GitHub Release
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * macOS 11.5.2

###  Behavior
When I connect an HDHomeRun Connect Duo (firmware version 20210624) DHCP on AdGuard Home does not allocate any IP information. The HDHomeRun is connected via ethernet.

### Additional Information
The rest of my network devices correctly receive IP setting information from AdGuard Home, via either ethernet or wifi. Things I have tested:

* completely reinstalling AdGuard Home from scratch
* trying the latest edge version
* deleting leases.db
* tried altering icmp_timeout_msec to 3000 and 250

I'm wondering whether this might be related to: [3366](https://github.com/AdguardTeam/AdGuardHome/issues/3366) ?

I have now also rolled back to previous versions of AdGuard Home and the last version that works correctly for me is v0.107.0.b.5. Running that release correctly allocates IP settings via DHCP to my HDHomeRun Connect Duo.

Please let me know if I can provide additional information.

**Comment by ainar-g** [comment]
Thanks for the report.  A similar report is #3462, although the system is different there.  We'll try to locate the problem.

**Comment by EugeneOne1** [comment]
@kour1er, there is the new build on the edge channel, which should fix the issue.  Could you please check, if it works properly?

**Comment by kour1er** [comment]
Just tried edge build: v0.107.0-a.156+eeda06f9

Works perfectly - thanks for taking the time to resolve my issue! 👍

**Comment by EugeneOne1** [comment]
@kour1er, thanks for testing!
