### ISSUE TITLE
dnscrypt servers in logs look different than doh, dot, doq

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#3488]
![image](https://user-images.githubusercontent.com/55087301/130363734-7139daba-66f2-4017-b134-d45844b17330.png)

Version: v0.107.0-b.8

![image](https://user-images.githubusercontent.com/55087301/130363785-bb3002a0-cf43-4750-98d2-22fa23161d9c.png)

All of my dns servers are sdns stamps.. 

![image](https://user-images.githubusercontent.com/55087301/130363826-975e720a-fec9-4e30-ae10-5f735d29a423.png)
(etc..)

**Comment by ameshkov** [comment]
The thing is that we haven't come up with a nice syntax for representing a DNSCrypt server, that's why we simply print the SDNS.

I suppose your request should be merged into https://github.com/AdguardTeam/AdGuardHome/issues/2801

**Comment by gyCfjSnO** [comment]
My DNS Stamps servers are now decoded in the log, when was this introduced? I'm on v0.107.0-b.14
