### ISSUE TITLE
Transient hostname of client has been modified

### ISSUE THREAD

**Issue by mingtdlb** [AdguardTeam/AdGuardHome#3512]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you setup DNS configuration:**
  * 
* **CPU architecture:**
  * aarch64
* **Operating system and version:**
  * centos-2009

The transient hostname of my CentOS client has been modified.
Because the DNS of adguardhome is used, the transient hostname of CentOS client is modified. I checked the DNS settings, Reverse resolving of clients' IP addresses is disabled. Is it caused by other settings?

![centos7](https://user-images.githubusercontent.com/84701966/131217846-b33e3fee-9b27-4da1-a23d-9abcf0f8247f.png)

![adguard](https://user-images.githubusercontent.com/84701966/131217851-b26f70e0-41ea-4e44-8692-580964c266d8.png)

![image](https://user-images.githubusercontent.com/84701966/131218050-30d1df48-1f51-4b6c-b189-a4529f7ed62b.png)

**Comment by da-gongren** [comment]
How to prevent AdGuardHome from assigning hostname to clients?
Adguardhome enables DHCP and DNS servers

**Comment by da-gongren** [comment]
Adguardhome enables DHCP and DNS services, How to prevent ADH from assigning host names to clients.

**Comment by ainar-g** [comment]
Hello and sorry for the late reply.  If you add an rDNS record for the IP address of the machine to AGH, clear the caches, and reboot the machine, does the problem disappear?  For example, if the IP address of the machine is `192.168.1.2` then try adding:

```
||2.1.168.192.in-addr.arpa^$dnsrewrite=NOERROR;PTR;my.example.local.
```

Where `my.example.local.` is the FQDN with the desired domain name.
