### ISSUE TITLE
Не видится ClientID в веб-интерфейсе

### ISSUE THREAD

**Issue by intari** [AdguardTeam/AdGuardHome#3515]
### Issue Details

* **Version of AdGuard Home server:**
v0.106.3

root@guard:/opt/AdGuardHome# ./AdGuardHome -v --version
AdGuard Home
Version: v0.106.3
Channel: release
Go version: go1.15.11
Build time: 2021-05-19T13:25:09Z+0000
GOOS: linux
GOARCH: amd64
Race: false
Main module:
	github.com/AdguardTeam/AdGuardHome (devel)
Dependencies:
	github.com/AdguardTeam/dnsproxy@v0.37.4 (sum: h1:YIoJkIp828LKmmmgxXvZHUKfGLsqTQAK8g+4DXbDbyU=)
	github.com/AdguardTeam/golibs@v0.5.0 (sum: h1:qwhEKjDrT0UcwDnHrNU2Yg/DLR9b/GsUncnXYW6VzAU=)
	github.com/AdguardTeam/urlfilter@v0.14.5 (sum: h1:WyF0hg0MwKevsqNPkoaZFH8f5WRi/yuy/7qePtYt5Ts=)
	github.com/NYTimes/gziphandler@v1.1.1 (sum: h1:ZUDjpQae29j0ryrS0u/B8HZfJBtBQHjqw2rQ2cqUQ3I=)
	github.com/aead/chacha20@v0.0.0-20180709150244-8b13a72661da (sum: h1:KjTM2ks9d14ZYCvmHS9iAKVt9AyzRSqNU1qabPih5BY=)
	github.com/aead/poly1305@v0.0.0-20180717145839-3fee0db0b635 (sum: h1:52m0LGchQBBVqJRyYYufQuIbVqRawmubW3OFGqK1ekw=)
	github.com/ameshkov/dnscrypt/v2@v2.1.3 (sum: h1:DG4Uf7LSDg6XDj9sp3maxh3Ur26jeGQaP5MeYosn6v0=)
	github.com/ameshkov/dnsstamps@v1.0.3 (sum: h1:Srzik+J9mivH1alRACTbys2xOxs0lRH9qnTA7Y1OYVo=)
	github.com/beefsack/go-rate@v0.0.0-20200827232406-6cde80facd47 (sum: h1:M57m0xQqZIhx7CEJgeLSvRFKEK1RjzRuIXiA3HfYU7g=)
	github.com/cheekybits/genny@v1.0.0 (sum: h1:uGGa4nei+j20rOSeDeP5Of12XVm7TGUd4dJA9RDitfE=)
	github.com/digineo/go-ipset/v2@v2.2.1 (sum: h1:k6skY+0fMqeUjjeWO/m5OuWPSZUAn7AucHMnQ1MX77g=)
	github.com/fsnotify/fsnotify@v1.4.9 (sum: h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=)
	github.com/go-ping/ping@v0.0.0-20210216210419-25d1413fb7bb (sum: h1:2opwLSXqxE0Za64PdpskXuvLYDj/XHQAD8tLcYpSlvY=)
	github.com/gobuffalo/envy@v1.9.0 (sum: h1:eZR0DuEgVLfeIb1zIKt3bT4YovIMf9O9LXQeCZLXpqE=)
	github.com/gobuffalo/packd@v1.0.0 (sum: h1:6ERZvJHfe24rfFmA9OaoKBdC7+c9sydrytMg8SdFGBM=)
	github.com/gobuffalo/packr@v1.30.1 (sum: h1:hu1fuVR3fXEZR7rXNW3h8rqSML8EVAf6KNm0NKO/wKg=)
	github.com/google/renameio@v1.0.1-0.20210406141108-81588dbe0453 (sum: h1:vvZyWjAX9oDB+DWpMsZMyv6Q3NZtim2C5Zcdh+H0OmQ=)
	github.com/AdguardTeam/dhcp@v0.0.0-20210517101438-550ef4cd8c6e (sum: h1:M6YnFP12o0/SjBEPt6b2r8ZkIy/wsV14TK8X9Tb6DEE=)
	github.com/joho/godotenv@v1.3.0 (sum: h1:Zjp+RcGpHhGlrMbJzXTrZZPrWj+1vfm90La1wgB6Bhc=)
	github.com/joomcode/errorx@v1.0.3 (sum: h1:3e1mi0u7/HTPNdg6d6DYyKGBhA5l9XpsfuVE29NxnWw=)
	github.com/josharian/native@v0.0.0-20200817173448-b6b71def0850 (sum: h1:uhL5Gw7BINiiPAo24A2sxkcDI0Jt/sqp1v5xQCniEFA=)
	github.com/kardianos/service@v1.2.0 (sum: h1:bGuZ/epo3vrt8IPC7mnKQolqFeYJb7Cs8Rk4PSOBB/g=)
	github.com/lucas-clemente/quic-go@v0.20.1 (sum: h1:hb5m76V8QS/8Nw/suHvXqo3BMHAozvIkcnzpJdpanSk=)
	github.com/marten-seemann/qtls-go1-15@v0.1.4 (sum: h1:RehYMOyRW8hPVEja1KBVsFVNSm35Jj9Mvs5yNoZZ28A=)
	github.com/mdlayher/ethernet@v0.0.0-20190606142754-0394541c37b7 (sum: h1:lez6TS6aAau+8wXUP3G9I3TGlmPFEq2CTxBaRqY6AGE=)
	github.com/mdlayher/netlink@v1.4.0 (sum: h1:n3ARR+Fm0dDv37dj5wSWZXDKcy+U0zwcXS3zKMnSiT0=)
	github.com/mdlayher/raw@v0.0.0-20191009151244-50f2db8cc065 (sum: h1:aFkJ6lx4FPip+S+Uw4aTegFMct9shDvP+79PsSxpm3w=)
	github.com/miekg/dns@v1.1.40 (sum: h1:pyyPFfGMnciYUk/mXpKkVmeMQjfXqt3FAJ2hy7tPiLA=)
	github.com/patrickmn/go-cache@v2.1.0+incompatible (sum: h1:HRMgzkcYKYpi3C8ajMPV8OFXaaRUnok+kx1WdO15EQc=)
	github.com/pkg/errors@v0.9.1 (sum: h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=)
	github.com/rogpeppe/go-internal@v1.7.0 (sum: h1:3qqXGV8nn7GJT65debw77Dzrx9sfWYgP0DDo7xcMFRk=)
	github.com/satori/go.uuid@v1.2.0 (sum: h1:0uYX9dsZ2yD7q2RtLRtPSdGDWzjeM3TbMJP9utgA0ww=)
	github.com/ti-mo/netfilter@v0.4.0 (sum: h1:rTN1nBYULDmMfDeBHZpKuNKX/bWEXQUhe02a/10orzg=)
	github.com/u-root/u-root@v7.0.0+incompatible (sum: h1:u+KSS04pSxJGI5E7WE4Bs9+Zd75QjFv+REkjy/aoAc8=)
	go.etcd.io/bbolt@v1.3.5 (sum: h1:XAzx9gjCb0Rxj7EoqcClPD1d5ZBxZJk0jbuoPHenBt0=)
	golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83 (sum: h1:/ZScEX8SfEmUGRHs0gxpqteO5nfNW6axyZbBdw9A12g=)
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4 (sum: h1:4nGaVu0QrbjT/AK2PRLuQfQuh6DJve+pELhqTdAj3x0=)
	golang.org/x/sys@v0.0.0-20210330210617-4fbd30eecc44 (sum: h1:Bli41pIlzTzf3KEY06n+xnzK/BESIg2ze4Pgfh/aI8c=)
	golang.org/x/text@v0.3.5 (sum: h1:i6eZZ+zk0SOf0xgBpEpPD18qWcJda6q1sxt3S0kzyUQ=)
	gopkg.in/natefinch/lumberjack.v2@v2.0.0 (sum: h1:1Lc07Kr7qY4U2YPouBjpCLxpiyxIVoxqXgkXLknAOE8=)
	gopkg.in/yaml.v2@v2.4.0 (sum: h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=)
	howett.net/plist@v0.0.0-20201203080718-1454fab16a06 (sum: h1:QDxUo/w2COstK1wIBYpzQlHX/NqaQTcf9jyz347nI58=)
root@guard:/opt/AdGuardHome#

  * 
* **How did you install AdGuard Home:**
  * 
snapcraft  
* **How did you setup DNS configuration:**
* На телефоне с андроидом либо через Private DNS либо через custom dns в Adguard for Android
  * 
* **If it's a router or IoT, please write device model:**
  * 
Виртуалка на VMware ESXi VM со свежей Ubuntu 20.04 для AdGuard Home
* **CPU architecture:**
  * 
AMD64
* **Operating system and version:**
  * 
AdguardHome на Ubuntu 20.04 
Клиент - Android 11

### Expected Behavior

Я прописываю Private DNS в андроид как clientid.adguarddomain.maindomain.com 
Либо прописываю в Adguard for Android его же как tls://clientid.adguarddomain.maindomain.com:853 или как https://adguarddomain.maindomain.com/dns-query/clientid или quic://clientid.adguarddomain.maindomain.com:784

в веб-интерфейсе AdGuardHome вижу этот clientid.

### Actual Behavior

Подключаю телефон к WiFi - все  как ожидается.
Отключаюсь от WiFi и подключаюсь к МТС - запросы проходят, я их вижу в веб-интерфейсе, но не вижу clientid.
(и при использовании Private DNS и при использовании все трех вариантов с Adguard for Android
Отключаюсь от МТС и подключаюсь к Тиньков-Мобайл и вижу clientid при любом варианте подключения (и PrivateDNS и все три варианта с AdGuard Home)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

В логе Adguard Home при этом видно запросы приходят с clientid, в логе nginx(DoH через него идет, DoT - напрямую) видно что dns-over-https запросы с clientid в url доходят.

Выключение IPv6 у МТСа не помогает.
Установка опции запрета IPv6 у AdGuard Home - не помогает.
Отключение IPv6  вообще через ЛК провайдера (они нативный дают) - не помогает.

**Comment by ainar-g** [comment]
Добрый день!  Можете ответить на сделующие вопросы:

1.  Проблема возникает исключительно при подключении к МТС?
1.  Не может быть так, что у вас заведён ещё один клиент с МТСовским _IP?_ 
1.  Вы не видите _ClientID_ в логах, в статистике, или где-то ещё?

**Comment by intari** [comment]
1. Не удалось воспроизвести любыми другими способами подключения.
2. Не одновременно. Ну и - а разве это может влиять на запросы через DoH/DoT?
3. В логах(которые "журнал", https://<adguard_home>/#logs?response_status=&search= ). в /var/log/AdGuardHome.err - видно что в самих запросах подстрока есть но вот получения ClientID - не вижу (если он туда пишется)

да, воспроизводится на разных устройствах (с теми же признами - мтс - нету, тиньков или WiFi - есть).

**Comment by ainar-g** [comment]
>  Не одновременно. Ну и - а разве это может влиять на запросы через DoH/DoT?

На сами запросы нет, но на отображение их в логе и статистике — да, может.  Можете посмотреть в файле `querylog.json`, который лежит в директории `data`, есть ли у этих запросов поле `CID`?

И ещё, будем признательны, если поставите последнюю бета-версию и посмотрите, воспроизводится ли это там, потому что в этом цикле было уже несколько различных исправлений этого функционала.

**Comment by intari** [comment]
Все страньше и страньше.
в querylog.json поле CID есть и корректное (но появляется если подождать или если перезапустить AdGuard Home)
В веб-интерфейсе если я ввожу MyClientID в поиск https://guard.viorsan.com/#logs?response_status=&search=MyClientId - запросы соответствующие отображаются при том что в полях на экране MyClientID нет. сначала нет. после перезапуска AdGuard Home - часто (не всегда) появляется.

После установки беты  - v0.107.0-b.8 - DoT & DoH заработали нормально.
