### ISSUE TITLE
GeoIP filter

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#352]
Add the ability to filter traffic from certain countries or continents.

Example:
  I want to block any ip that once resolved from the server where AdguardDNS is running, nothing is returned to me and therefore I can not connect to that ip located on the blocked continent.

What do you think? It could be interesting as a thing.

**Comment by ameshkov** [comment]
This is possible, but it is quite complicated feature so let's wait and see how many upvotes does it get

**Comment by JamesXatu2** [comment]
Ok, thanks !

Il mar 9 ott 2018, 00:34 Andrey Meshkov <notifications@github.com> ha
scritto:

**Comment by Threefish4096** [comment]
Can I know if the idea has been taken into consideration and will be realized or remains too complex as a thing to be realized and will remain unsolved?

**Comment by ameshkov** [comment]
@Threefish4096 

It is not on the v0.97 milestone yet, we have a number of more pressing issues. But there's a chance it will be implemented in the future.

**Comment by chris-kwl** [comment]
Would love to have this feature as well.
Although my public instance only allows DoH and DoT, I keep seeing requests from e.g. China.
Sure there are possibilities to put all IPs of countries on the whitelist but with e.g. DE, CH, AT that would be several hundred thousand entries and the country of originis is available after the first request anyway, because it is displayed in the log.

**Comment by SCPdesign** [comment]
This would be a great feature. Right now I'm limited to a FreeBDS package that causes so many issues and left to it's own devices takes down the firewall itself. AdGuardHome GeoIP Blocking would be great.

I'm not sure how AdGuard will do it as Maxmind Free or Paid or whatever. Either way, I hope it comes to fruition!

**Comment by ainar-g** [comment]
Merging into #1487, since a GeoIP database support would be necessary anyway.
