### ISSUE TITLE
Reinstall is not working

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#3522]
@jxwinks commented on [Tue Aug 31 2021](https://github.com/AdguardTeam/AdguardForMac/issues/920)

### Steps to reproduce

1. Intall AdguardForMac
2. Uninstall AdguardForMac
3. Reinsall AdguardForMac
2.
3.
4.

### Expected behavior
 Adguard should reinstall

### Actual behavior
claims INIT already exists but directory is NOT to be found

<details><summary>Screenshot:</summary>

</details>Last login: Sun Aug 29 10:11:36 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
winkelmans-imac:~ winkelman$ curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v
starting AdGuard Home installation script
channel: release
operating system: darwin
cpu type: amd64
AdGuard Home will be installed into /Applications/AdGuardHome
checking curl
checking unzip
note that AdGuard Home requires root privileges to install using this script
restarting with root privileges
Password:
starting AdGuard Home installation script
channel: release
operating system: darwin
cpu type: amd64
AdGuard Home will be installed into /Applications/AdGuardHome
checking curl
checking unzip
script is executed with root privileges
no need to uninstall
downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_darwin_amd64.zip -> AdGuardHome_darwin_amd64.zip
unpacking package from AdGuardHome_darwin_amd64.zip into /Applications
Archive:  AdGuardHome_darwin_amd64.zip
   creating: /Applications/AdGuardHome/
  inflating: /Applications/AdGuardHome/AdGuardHome  
  inflating: /Applications/AdGuardHome/LICENSE.txt  
 extracting: /Applications/AdGuardHome/AdGuardHome.sig  
  inflating: /Applications/AdGuardHome/README.md  
  inflating: /Applications/AdGuardHome/CHANGELOG.md  
2021/08/30 16:54:04 [info] Service control action: install
2021/08/30 16:54:04 [fatal] Failed to install AdGuard Home service: Init already exists: /Library/LaunchDaemons/AdGuardHome.plist
cannot install AdGuardHome as a service
winkelmans-imac:~ winkelman$ 

### Your environment

* Environment name and version: (e.g. Chrome 59): Mac Big Sur 11.2.3
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by EugeneOne1** [comment]
@jxwinks, please, try the following steps:

 1. Run `curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -u`.  Ignore any occurred errors.
 2. Manually remove the existing `.plist` file with `rm /Library/LaunchDaemons/AdGuardHome.plist`.
 3. Restart the machine.

For now it's should be possible to install the AdGuard Home with the command you used before, e.g. `curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v`.

**Comment by R-Ata** [comment]
sorry for post here.. but today y see momentarily the icon of Adguard turn yellow with a `%` in middle of the icon.

I never saw anything like this before 

after clicking on the AdGuard icon it showed me an **Ad** in the same box of actions of Adguard.. i mean here:

![Capturaa](https://user-images.githubusercontent.com/33556647/131502908-b6d17ed5-ad94-4ebb-adba-9af1724848e7.PNG)

after closing and opening the browser everything was normal

**Comment by jxwinks** [comment]
Thank you Eugene, but my primary problem is that the directory referenced is no where to be seen..

I know how to get to /Library in Finder, but I don’t have /Library/Launchdaemons as a directory. Hence, I cannot remove the offending plist.

_______________________
John WInkelman
129 Garcilla Drive
Rancho Mission Viejo, CA 92694
949.351.1091
On Aug 31, 2021, 5:36 AM -0700, Javier ***@***.***>, wrote:
	sorry for post here.. but today y see momentarily the icon of Adguard turn yellow with a % in middle of the icon.
I never saw anything like this before
after clicking on the AdGuard icon it showed me an Ad in the same box of actions of Adguard.. i mean here:
after closing and opening the browser everything was normal
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ainar-g** [comment]
@R-Ata, this repository is about AdGuard Home.  Please send all issues about the browser extension to [its repo] and keep these issues on-topic.  Thanks.

[its repo]: https://github.com/AdguardTeam/AdguardBrowserExtension

**Comment by EugeneOne1** [comment]
@jxwinks, there are several directories called `Library` on macOS:

  * The global one
  * One for each user in it's home directory

AdGuard Home uses the global `Library` located in `/`, so please make sure you're looking in the right place.  Here is the simplest way to do it:

 1. Open terminal
 2. Run `open /Library`
