### ISSUE TITLE
Exporting logs from UI

### ISSUE THREAD

**Issue by bloodyskullz** [AdguardTeam/AdGuardHome#3524]
Hey,

Was wondering if it is possible to have a method of extracting logs via the UI? Basically exporting them to csv but based on the systems added to the system.

For example I want to extract logs for all queries adguard processed for my machine for a specified date/range.

Would be nice for administering and not having to go via the CLI. If this is available please direct me to where I can find it.

Thanks

Version of adguard home & hardware: latestet installed on Ubuntu 20.04LTS on an intel NUC 6th gen with 4GB of RAM.

Installed via automated install.

**Comment by ainar-g** [comment]
Sounds like a dup of #3389.
