### ISSUE TITLE
Return `NOERROR` for `HTTPS` queries automatically 

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3531]
### Problem Description

Every DNS query with type `HTTPS` returns `NOERROR` with no real data returned. 

![1A833970-A92E-4569-B220-84D014BA039F](https://user-images.githubusercontent.com/19761269/131708714-54bd6d75-9025-4433-a2ba-28f03859c1e8.jpeg)

### Proposed Solution

Return NOERROR without sending the query to upstreams.

**Comment by ainar-g** [comment]
Please add an explanation as to why do you think we should do that.  `HTTPS` is a perfectly valid type of request a user might want us to forward to an upstream.  And if a domain name is in a blocklist, we already don't forward it anywhere.

**Comment by agneevX** [comment]
Well `HTTPS` returns `NOERROR` and no other data; it's static and returns the same thing every time. 

Perhaps this should not be automatic, but it'd be good to use custom filtering rules.

**Comment by ainar-g** [comment]
That's not quite true.  Here's `HTTPS` response for `blog.cloudflare.com`, for example:

```none
2021/09/01 20:37:19 ;; opcode: QUERY, status: NOERROR, id: 1234
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;blog.cloudflare.com.   IN       HTTPS

;; ANSWER SECTION:
blog.cloudflare.com.    300     IN      HTTPS   1 . alpn="h3,h3-29,h3-28,h3-27,h2" ipv4hint="104.18.26.46,104.18.27.46" ipv6hint="2606:4700::6812:1a2e,2606:4700::6812:1b2e"

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: do; udp: 4096
```

`HTTPS` and `SVCB` records are still an experimental technology, but that doesn't mean that we should block it all together.
