### ISSUE TITLE
Option to temporarily disable blocking

### ISSUE THREAD

**Issue by F3000** [AdguardTeam/AdGuardHome#3533]
A user could choose between 1,5,10,15 minutes to disable the blocking .after that time the blocking should be activated automatically.

This time frame could also be managed via API

**Comment by ameshkov** [comment]
Definitely will be done after the refactoring is finished.

Closing as dup of #1333

**Comment by F3000** [comment]
Thanks . Where I can see the status of the refactoring ? @ameshkov

**Comment by ameshkov** [comment]
@F3000 it's currently done in a private branch. I'd really like to avoid telling the ETA since we missed it about 4 times already, but I really-really hope it'll be ready to use by the end of the year.
