### ISSUE TITLE
[req] time based specific service blocking, fe YouTube blocked up to 6pm

### ISSUE THREAD

**Issue by mlokaleu** [AdguardTeam/AdGuardHome#3536]
Hi,

is it possible to achieve a time-based service blocking in AdGuard?
I would like to block YouTube for most of the day, lets say up to 6pm.

is it possible? how can it be done? thx!

**Comment by ameshkov** [comment]
Eventually, we'll do that. Closing as a dup of #2703

**Comment by BrianGilbert** [comment]
@ameshkov the OP of #2703 has closed that issue, can you please re-open one of them?

**Comment by ameshkov** [comment]
@BrianGilbert this is the proper original issue for this: https://github.com/AdguardTeam/AdGuardHome/issues/951
