### ISSUE TITLE
Clients (runtime) does not populate

### ISSUE THREAD

**Issue by alexfornuto** [AdguardTeam/AdGuardHome#3549]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * GitHub Release, i.e. `https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh`
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * KVM Virtual Machine
* **CPU architecture:**
  *  AMD64
* **Operating system and version:**
  * Debian 10

### Expected Behavior
As devices in my network begin to use AdGuard as their DNS server (confirmed in logs), I expect those devices to populate in the **Clients (runtime)** field, so I can more easily add them to the configured devices list.

### Actual Behavior
The **Clients (runtime)** field remains empty. The only way to add known clients is manually, which does not scale and is a PITA for devices where IP addresses change and MAC addresses are harder to identify.

### Screenshots

<details><summary>Screenshots:</summary>

Showing that the client is using AdGuard:
![query-log](https://user-images.githubusercontent.com/2349184/132025835-1369875f-3766-4c4c-85da-5fd7f7a3efe2.png)

Showing that the client is not listed:
![empty-clients](https://user-images.githubusercontent.com/2349184/132025891-9bf718a3-b4d6-475f-a5ba-d606aa07c3c7.png)

</details>

### Additional Information
Not sure what else to add, but will provide as needed.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by alexfornuto** [comment]
But of course, it started showing results and clients after I logged this issue, and I had to cut the service anyway as it was creating problems in my home network. Sorry for the noise.
