### ISSUE TITLE
Panic / Termination filterMsg

### ISSUE THREAD

**Issue by lex-obrien** [AdguardTeam/AdGuardHome#3551]
### Issue Details

running 

AdGuard Home, version v0.107.0-b.9
Running from openWrt, downloaded from github release
Arm v7
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

Receive a panic which caused the service to die and then restart.

I have only seen it once, but panics are definitely not good :)

 panic: runtime error: index out of range [0] with length 0

 goroutine 43834 [running]:
 github.com/AdguardTeam/dnsproxy/proxy.filterMsg(0x28191d0, 0x28191d0, 0x1e70000, 0x0)
 	github.com/AdguardTeam/dnsproxy@v0.39.4/proxy/cache.go:427 +0x1ac
 github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(0x252c540, 0x2061b90, 0x0, 0x0)
 	github.com/AdguardTeam/dnsproxy@v0.39.4/proxy/proxy.go:502 +0xc0
 github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).processUpstream(0x21b7600, 0x24fc420, 0x0)
 	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:544 +0x68
 github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).handleDNSRequest(0x21b7600, 0x252c540, 0x2061b90, 0x0, 0x0)
 	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:102 +0x21c
 github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0x252c540, 0x2061b90, 0x3, 0x2661c20)
 	github.com/AdguardTeam/dnsproxy@v0.39.4/proxy/server.go:127 +0x1e4
 github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(0x252c540, 0x2998540, 0xe0, 0xe0, 0x28fce80, 0x10, 0x10, 0x27bc2e8, 0x256c448)
 	github.com/AdguardTeam/dnsproxy@v0.39.4/proxy/server_udp.go:105 +0x194
 github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0x252c540, 0x2998540, 0xe0, 0xe0, 0x28fce80, 0x10, 0x10, 0x27bc2e8, 0x256c448, 0x1ac9440, ...)
 	github.com/AdguardTeam/dnsproxy@v0.39.4/proxy/server_udp.go:74 +0x5c
 created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
 	github.com/AdguardTeam/dnsproxy@v0.39.4/proxy/server_udp.go:73 +0x334

**Comment by lex-obrien** [comment]
Also, I just realized that dnsproxy has its own repo: https://github.com/AdguardTeam/dnsproxy
Apologies if I should have opened it over there.

**Comment by lex-obrien** [comment]
It seems to be happening a few times per day, but each time it does successfully restart and continue (same stack trace).

**Comment by ameshkov** [comment]
Just in case, could you please record the verbose-level log as well?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by EugeneOne1** [comment]
@lex-obrien, the latest build in the edge channel should fix the issue.  Could you please check, if it still panics?

**Comment by lex-obrien** [comment]
Thank you, trying it now!

**Comment by EugeneOne1** [comment]
@lex-obrien, we'll close the issue for now.  Please, feel to reopen it if the panic recurs.

**Comment by haberdabers** [comment]
Do you know when v0.107.0-b.10 will be released?

**Comment by ainar-g** [comment]
@haberdabers, in a couple of hours, if all goes to plan.
