### ISSUE TITLE
adguard browsing security web service block disneyplus on firetv and android app

### ISSUE THREAD

**Issue by strausmann** [AdguardTeam/AdGuardHome#3553]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Snapcraft
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Unifi Security Gateway
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior
Calling Disney+ on the Amazon FireTV and our Android Apps with the Disney+ App and activated adguard home function "adguard browsing security web service".

### Actual Behavior
Currently, neither the FireTV nor the Android devices with the Disney+ app can log in nor access the content.

- I have deactivated all block lists as a test. Access is still not possible. I then disconnected the tablet and smartphone from the Wi-Fi network and closed the Disney+ app. So that the DNS cache is cleared.
- I deactivated all AdGuard protection as a test. After that, the apps all worked again. Then I disconnected the tablet and smartphone from the WLAN and closed the Disney+ app. So that the DNS cache is cleared.
- Test activated all blocklist and protection again and deactivated the "adguard browsing security web service". Access was then possible without problems with the Disney+ apps.
- The problem does not exist with the iPhone app, XBOX app, LG TV app, or in the browser on any platform, including the Android in the browser.

### Screenshots
![image](https://user-images.githubusercontent.com/4519228/132120532-7e11f74d-804d-46de-a517-4f21a8f399ed.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Could you please try checking the query log and see if there's any domain that's blocked by the browsing security?

We cannot reproduce it on our side.

**Comment by strausmann** [comment]
Unfortunately, this is also my problem. The logs do not show any message at all. I even just turned off the IPv6 DNS resolution.

**Comment by ameshkov** [comment]
That's quite strange, are you sure you narrowed it down to the browsing security service specifically?

What happens if you change the upstream DNS server?

**Comment by strausmann** [comment]
I think I've narrowed it down to that quite clearly. Currently, I am gradually activating the DNS block lists. Always a list every 6 hours. But as soon as I activate the browsing security feature, it's over. Then nothing works in the app.

I have already changed the upstream from the Quad9 DNS which is set in the default, to the CloudFlare DNS-over-HTTPS. In between I had both Quad9 and CloudFlare running in load balancing.

Translated with www.DeepL.com/Translator (free version)

**Comment by ameshkov** [comment]
This is soo strange, then browsing security must've blocked at least something.

Could you please record verbose-level log so that we could take a look?

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.
