### ISSUE TITLE
MobileConfig file generated by AdGuard does not work correctly on iOS devices.

### ISSUE THREAD

**Issue by enxoco** [AdguardTeam/AdGuardHome#3568]
### Issue Details

AdGuard generated mobileconfig file is missing bootstrap DNS server addresses which appear to be required by newer version of iOS.  When I install the generated mobileconfig file on my MacBook running Big Sur everything works fine.  However when I try to install it on an iPhone 12 running iOS 14.5 nothing happens.  None of the DNS queries on the iPhone are going through my AdGuard server.  It only works if I manually edit the mobileconfig file and add bootstrap servers like this:
```
<key>ServerAddresses</key>
	<array>
		<string>2606:4700:4700::1111</string>
		<string>2606:4700:4700::1001</string>
		<string>1.1.1.1</string>
		<string>1.0.0.1</string>
	</array>
```

### Expected Behavior
Installing AdGuard generated mobileconfig file on an iOS device should cause DNS queries to pass through AdGuard server.

### Actual Behavior
iOS device traffic does not pass through AdGuard server, unless the mobileconfig file is modified to include bootstrap DNS servers.

### Additional Information
I would be happy to take a closer look at the code and potentially put in a PR to resolve the issue.

**Comment by ainar-g** [comment]
Thank you for your report, we'll try to fix this in the upcoming beta.

**Comment by ainar-g** [comment]
We have made some changes to the mobileconfig API logic, including adding the bootstrap servers, in the most recent `edge` build.  The feature will also land in the upcoming beta.  Can you please check if our solution works for you?

**Comment by enxoco** [comment]
@ainar-g Yep looks good to me.  Thanks!
