### ISSUE TITLE
DNSCrypt server timing out

### ISSUE THREAD

**Issue by Cybercave** [AdguardTeam/AdGuardHome#3576]
### Issue Details

I have a Lindode server and a domain name. DoH works.
I have tested AdGuard Home's DNSCrypt server and I get an i/o timeout. I have no idea if I am doing this right. I am almost sure I am not messing anything up. 

* **Version of AdGuard Home server:**
  *  v0.106.3
* **How did you install AdGuard Home:**
  * Github releases through install script
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 11

### Expected Behavior
The DNSCrypt response to a test using `dnscrypt --lookup  ...` should return a valid response.

### Actual Behavior
The response gets an i/o timeout, even testing in-LAN or over localhost.

### Additional Information

I have tested DNSProxy as well and get the same results.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by Cybercave** [comment]
May I send the log via email? There is too much metadata to censor.

**Comment by ainar-g** [comment]
Yes, our E-Mail address for such things is devteam@adguard.com.  Please add “AdGuard Home Issue 3576” into the subject line.

**Comment by Cybercave** [comment]
Just sent.

**Comment by ainar-g** [comment]
We have received your logs, thanks!  We'll inspect them and report back.

**Comment by Cybercave** [comment]
I installed the beta channel on the Linode instance and tested again and got a response. I have an AdGuard Home instance at home, which I will have to figure out what to do with.

**Comment by Cybercave** [comment]
I just tested it on my home instance, and got a response. I regenerated the config, and made the `--provider-name` argument my hostname. I _was_ doing something wrong.
