### ISSUE TITLE
Option to backup settings or sync settings

### ISSUE THREAD

**Issue by Unstable0** [AdguardTeam/AdGuardHome#3578]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

- [x] I am running the latest version

### Problem Description

I have 2 unused computers so I installed AdGuardHome on both computers (let the first computer = A and the second computer = B)
On computer A I edited adguard home settings and I want to sync the settings to computer B, I can just copy the YAML config file to computer B but it's inconvenient.

### Proposed Solution

I'm suggesting make an option on the web panel to download config. So I can go into the web panel on computer A and download the config file, then on computer B web panel load the config I downloaded.

### Alternatives Considered

Make both computer settings sync so I can have a primary and secondary DNS servers (In case I have to shut down computer A all devices on my network will use computer B as secondary DNS server)

### Additional Information

This can be useful as backup too, in case you messed up the settings you can choose to restore from the previous config file or reset all settings

**Comment by ainar-g** [comment]
Sounds like a dup of #1147.
