### ISSUE TITLE
Deezer app on Android showing full screen ads

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdGuardHome#358]
Yes, Deezer the music streaming app on Android is showing full screen ads with default Adguard dns.

**Comment by karina-archazh** [comment]
@SeriousHoax Hi!
Could you please try to re-install Deezer with enabled Adguard DNS?

**Comment by karina-archazh** [comment]
@SeriousHoax if you're an Android user could you please try to clear Deezer app cache in app settings, then re-install Deezer (with enabled Adguard DNS of course)?

**Comment by SeriousHoax** [comment]
> @SeriousHoax if you're an Android user could you please try to clear Deezer app cache in app settings, then re-install Deezer (with enabled Adguard DNS of course)?

Yes Yes I did that. I'm an Android user. I cleared cache, reinstalled the app and still having the same issue.

**Comment by karina-archazh** [comment]
Can you specify your system preferences and adguard settings?

**Comment by SeriousHoax** [comment]
> Can you specify your system preferences and adguard settings?

Wait, did you think I'm talking about Adguard app with Adguard dns enabled? I'm sorry if I was not clear. I'm talking about Adguard dns only. I don't have the app. Adguard dns is set up in the wifi setting.

**Comment by karina-archazh** [comment]
@SeriousHoax Our DNS server service doesn't guarantee 100% filtering.
I can suggest you try our app and test Deezer app filtering with HTTPS filtering and Adguard DNS option enabled.
Here is a link:
https://adguard.com/en/adguard-android/overview.html#howToInstall

**Comment by ameshkov** [comment]
Let's ask @Alex-302 if we can block Deezer ads on the DNS level or is it problematic

**Comment by SeriousHoax** [comment]
> This is impossible.

For clarification, is it impossible for almost every in app full screen ads? Cause I've see them in some other apps to with Adguard dns enabled.

**Comment by ameshkov** [comment]
The "upgrade" ad is hard-coded, it cannot be blocked even if you use the AG for Android app :(

**Comment by ameshkov** [comment]
> For clarification, is it impossible for almost every in app full screen ads? Cause I've see them in some other apps to with Adguard DNS enabled.

Usually, if an ad is third-party than it's possible to block it one way or another.
If this is a first-party hardcoded ad like in this case, it cannot be blocked.

**Comment by Alex-302** [comment]
@SeriousHoax could you please make screenshot of ad? I see only their premium subscription banner.

**Comment by SeriousHoax** [comment]
> The "upgrade" ad is hard-coded, it cannot be blocked even if you use the AG for Android app :(

I'm not talking about the "upgrade" ad. That's obvious. I've seen other third party apps.

**Comment by SeriousHoax** [comment]
> @SeriousHoax could you please make screenshot of ad? I see only their premium subscription banner.

Ok I will share screenshots soon.

**Comment by SeriousHoax** [comment]
> @SeriousHoax could you please make screenshot of ad? I see only their premium subscription banner.

Here's a screenshot. I got this right after I opened the app. 
Snap it from the recent activity to confirm that the Deezer app is showing this. 

https://imgbox.com/r7FtpS3F

**Comment by SeriousHoax** [comment]
This one? 


https://mega.nz/#!zOgR3AgK!hGkVGiDIfF0nYkbvKAx4ipIj7eLtf6eik9hhAZ5PFnc

**Comment by Alex-302** [comment]
Yes. I don't see requests to third-party domains. Maybe this ad is cached or built-in to apk.

**Comment by Alex-302** [comment]
This is impossible to block ads in this app using DNS.

**Comment by SeriousHoax** [comment]
> 
> 
> This is impossible to block ads in this app using DNS.

I see. Ok. Thanks.
