### ISSUE TITLE
Support no-etc-hosts in config file

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3584]
### Problem Description
The config file does not appear to have an option for the cmd line `--no-etc-hosts`

### Proposed Solution
Add an equivalent option for `--no-etc-hosts` in the config yaml file so that it does not need to be passed on the cmd line

**Comment by ainar-g** [comment]
Tangentially related to #3020, but only when it comes to clients and not DNS resolution.

@ameshkov?

**Comment by ameshkov** [comment]
Generally, clients affect DNS resolution so I guess we can merge it there.

**Comment by ainar-g** [comment]
Merging into that issue then.
