### ISSUE TITLE
The Query log pages showed no logs and 502 error after update to v0.107.0-a.161+fac574d3

### ISSUE THREAD

**Issue by leo15dev** [AdguardTeam/AdGuardHome#3592]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.107.0-a.161+fac574d3
* **How did you install AdGuard Home:**
  *  Docker
* **How did you setup DNS configuration:**
  *  loT
* **If it's a router or IoT, please write device model:**
  *  Raspberry 4B
* **CPU architecture:**
  *  ARM
* **Operating system and version:**
  *  Ubuntu 20.04.3 LTS

### Expected Behavior

Query log page will show the logs based on your settting
### Actual Behavior

When you enter the query logs pages, the query logs in the page is empty and generated an error shown in a red toast like:
`Webservice currently unavailable ,<small>Error 502</small></h1>,[object Object]</div>, </body>, </html>, | 502</DOCTYPE>`

But when you check the work/data, the querylog.json.1 or querylog.json stored some the query log information, but any log information before the 09/14 0:00 was disappeared. Query logs retention  and Statistics retention set to  30 days. And in dashboard, you can see the total number of requested count  is showed for last 30 days and it showed the correct numbers.   

There is no error message in the previously edge version. 

I also tried to clear query logs in the dashboard, but there is no help to solve this problem.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

In nginx `access.log`  showed that 
` "GET /control/querylog?search=&response_status=&older_than=&limit=20 HTTP/1.1" "502 3893 " `

In nginx `error.log` showed that 
`upstream prematurely closed connection while reading response header from upstream`

The configuration in the `nginx.conf` and `site.conf` is the same as before. But there is no such error in the previously edge build.

**Comment by ainar-g** [comment]
Hello and thank you for the report!  Our testers have actually noticed the issue yesterday, and we have already pushed a fix to the `edge` channel.  As of snapshot 9a1d3ec, it should be fixed.  Can you please check if our fix worked for you?

**Comment by leo15dev** [comment]
@ainar-g Thanks for your information. It had fixed in the v0.107.0-a.163+eeb99db9 build. I think I can close this issue right now, thank you!
