### ISSUE TITLE
AdGuard Home BLOCKING whole internet access

### ISSUE THREAD

**Issue by danselstory** [AdguardTeam/AdGuardHome#3593]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

Unless I click "Disabled Protection", our internet is fully blocked. Is there a way to check why? I used default filter list and used Cloudflare DNS.

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

![image](https://user-images.githubusercontent.com/29477088/133181367-af384ffb-35ba-4ca8-90db-5152e735e9b1.png)

**Comment by danselstory** [comment]
This only happens today and it works just fine since 2 years ago. I am using the latest version.

**Comment by danselstory** [comment]
Issue found - disabling both "browsing security web service" and "parental control web service" fix it (I can browse internet if that disabled. So that API maybe having issue? 

![image](https://user-images.githubusercontent.com/29477088/133182121-75904397-82ef-4690-93c4-6611434de525.png)

**Comment by ameshkov** [comment]
Maybe they're unavailable from your place for some reason?

To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by danselstory** [comment]
It works now after few hours "outage". Can I have the API endpoint url so
maybe I can write ping script to see when its not working?

I will enable verbose next time it happens again.

Regards,
Danny

**Comment by ainar-g** [comment]
If I recall correctly, the endpoint is https://dns-family.adguard.com/dns-query.

@ameshkov, am I correct?

**Comment by danselstory** [comment]
Thanks!

Nevertheless, isnt when some "part" of the feature doesnt work, shouldn't
Adguard home let user know (alert in dashboard) and auto "bypass" that
feature and allow internet to work properly?

I am using cloudflare family DoH FYI 🙏 and enable that 2 options in
Adguard to block porn etc. Looks like cloudflare family doesn't block porn
sites.

Regards,
Danny
