### ISSUE TITLE
NOERROR+NODATA response is not cached

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdGuardHome#3598]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.0-b.11
* **How did you install AdGuard Home:**
Snapcraft
* **How did you setup DNS configuration:**
DoH with [dnsproxy](https://github.com/AdguardTeam/dnsproxy)
* **CPU architecture:**
AMD64
* **Operating system and version:**
Debian 11

### Actual Behavior

According to RFC4074:

> Suppose that an authoritative server has an A RR but has no AAAA RR for a hostname. Then, the server should return a response to a query for an AAAA RR of the name with the response code (RCODE) being 0 (indicating no error) and with an empty answer section

In this case, AdGuard Home does not cache responses, even when the minimum cache TTL is set.

### Expected Behavior

AdGuard Home follows the same settings as NXDOMAIN to cache NOERROR+NODATA

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/133390676-89618281-7677-4fef-8ce6-a851a2f2b210.png)

![image](https://user-images.githubusercontent.com/13190004/133392290-100e9f6f-91cd-4185-ac58-c1e65ca187d0.png)

</details>

### Additional Information

This also seems to affect the [dnsproxy](https://github.com/AdguardTeam/dnsproxy)

**Comment by ameshkov** [comment]
@ainar-g legit issue, we'll need to get the TTL from the SOA section in this case.

**Comment by EugeneOne1** [comment]
@ZeroClover, hello and apologies for a late response.  This seems being implemented in #3707.  Could you please check it out in any version of AGH since **v0.107.0**?

**Comment by EugeneOne1** [comment]
@ZeroClover, hello again.  I'm going to close the issue for now, feel free to reopen it on any problems with the implementation.
