### ISSUE TITLE
Split settings for serving admin UI via https from enabling DoH/DoT/DoQ

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3599]
### Problem Description
I would like to enable the admin UI to run over HTTPS, but I do not need/want DoH, DoT or DoQ.

### Proposed Solution
Admin UI over HTTPS should be independent from DoH/DoT/DoQ. Perhaps each should have its own on/off switch.

**Comment by ainar-g** [comment]
Dup of #741.  Will be implemented along with #2075 and #2554, probably during the v0.108 cycle.
