### ISSUE TITLE
AG stops rDNS after some time for Top Clients

### ISSUE THREAD

**Issue by MeganerdNL** [AdguardTeam/AdGuardHome#3605]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.11
* **How did you install AdGuard Home:**
  * OPNsense plugin via [this repo](https://github.com/mimugmail/opn-repo)
* **How did you setup DNS configuration:**
  * Internet: DNSCrypt servers. Local: Unbound.
* **CPU architecture:**
  * AMD64 (on a Protecli FW4B)
* **Operating system and version:**
  * OPNsense 21.7.2_1-amd64 (FreeBSD 12.1)

### Expected Behavior
Top Clients should always show a hostname when possible.

### Actual Behavior
Top Clients show hosnames after start, but after some time (10-15mins) more and more IP's are shown. These IP's are actually served via rDNS (there is a PTR record) when I test it on another box. And restarting AdGuard solves the problem too.

### Additional Information

I run AdGuard on OPNsense.
Local DNS is done by Unbound on OPNsense. 
Unbound listens on port 53530 and AdGuard port 53. 
Every device first queries AdGuard and AdGuard can query Unbound when applicable for internal hosts/IPs 
In DNS Settings under Upstream DNS servers I have a line: 
`[/mydomain.org/]127.0.0.1:53530`
In DNS Settings under Private reverse DNS I have a line (my local subnet is 10.0.0.0/8):
`[/10.in-addr.arpa/]127.0.0.1:53530`
It works great at first.
But after some time - 10-15 minutes  - it seems to forget the hostname and IPs are shown...
These IP's are actually served via rDNS on Unbound (there is a PTR record), when I test it on another box. 

Restarting AdGuard solves the problem, temporarily.

EDIT: I noticed when I activate Static ARP in my DHCP server on OPNsense, AdGuard will remember the IP-hostname combinations. Still, the IPs are normally reverserd-resolvable via rDNS, so it shoudn't forget them, or am I wrong?

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) AdGuard Home to write verbose-level log.
2. Reproduce the issue.
3. Post the log file here.

**Comment by MeganerdNL** [comment]
I have OPNsense now configured to use static ARP and I cannot turn that off atm. In this mode AdGuard Home remebers the hostnames.
