### ISSUE TITLE
The dependency service does not exist, on Windows

### ISSUE THREAD

**Issue by mgcWil** [AdguardTeam/AdGuardHome#3609]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  v0.107.0-a.165+48b0cefb and v0.107.0-b.11
* **How did you install AdGuard Home:**
  GitHub releases
* **Operating system and version:**
  Windows 10

### Actual Behavior
Hello everyone, I have a problem with the service, it is impossible to start it.

The command AdGuardHome -s install, returns the message :
"Failed to start AdGuard Home service: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it."
AdGuardHome -s start: 
"Failed to start the service: Failed to start AdGuard Home service: The dependency service does not exist or has been marked for deletion."
and "Error 1075: The dependency service does not exist or has been marked for deletion" with the services console.

A new value "DependOnService" in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AdGuardHome is present, having as data "After=syslog.target network-online.target".

### Additional Information
To solve the problem, one solution is to remove the "DependOnService" value.
But this is not enough, we also need to change the startup type of the service which is now in "disabled" state.
And since the service still does not restart, a reboot must be done !

This "bug" exists, it seems to me, since the [modifications](https://github.com/AdguardTeam/AdGuardHome/commit/53f7c0b2df88e70e1174d3be88792b858971c0a1#diff-532187fabc89b471039ea70be6885a8a6378aab7d0d05850b62ad5657f8cb1ac) on the file "service.go" concerning these dependences.

Thanks for your solutions

**Comment by ainar-g** [comment]
Hello and thank you for the report!  We have just released v0.107.0-a.168+6ac28ee8. which should fix this bug.  Can you please check if our solution fixes the issue for you?

**Comment by mgcWil** [comment]
Hello, bug corrected for me on the Edge version, I'm waiting for your correction on the Beta.
Thank you ;)
