### ISSUE TITLE
Allow AdGuard Home to be reached anonymously over DNSCrypt

### ISSUE THREAD

**Issue by Cybercave** [AdguardTeam/AdGuardHome#3611]
### Problem Description

Currently trying to reach an instance anonymously results in an error when using dnscrypt-proxy, `[WARNING] [Server-name] couldn't be reached anonymously`.

### Proposed Solution

Add an option to the config file so that anonymous queries may go through. 
`allow_anonymous_dnscrypt: true`
Also add this functionality to AdGuard Home.

### Alternatives Considered

Using a DNSCrypt server such as https://github.com/jedisct1/encrypted-dns-server and using the AGH server as upstream.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/1226
