### ISSUE TITLE
DNS rewrite can't rewrite record to A or AAAA

### ISSUE THREAD

**Issue by asushugo** [AdguardTeam/AdGuardHome#3616]
* **Version of AdGuard Home server:**
  v0.107.0-b.11
* **How did you install AdGuard Home:**
  GitHub releases
* **How did you setup DNS configuration:**
  OpenWrt
* **CPU architecture:**
  arm

Hello! I am want to rewrite the DNS record to ipv4, but it doesn't work!

Here is setting:
![image](https://user-images.githubusercontent.com/18640537/133766605-dbc8ed05-1283-4ad9-90a8-06dca34f109d.png)

Here is log
![image](https://user-images.githubusercontent.com/18640537/133766381-fc0fbb7d-1d10-48cf-88c8-dfae051ffa27.png)

**Comment by ainar-g** [comment]
Hello and thank you for your report.  We've pushed a fix to the `edge` channel recently.  Can you please check if it fixes the issue for you?

**Comment by ainar-g** [comment]
We'll close this issue for now.  Feel free to report new issues if you find any bugs.

**Comment by asushugo** [comment]
v0.107.0-b.12 work fine! Thanks!
![image](https://user-images.githubusercontent.com/18640537/136643613-1c17e4dc-13e9-4158-b203-46d064ea925d.png)
