### ISSUE TITLE
Recommended rewording step 3 of setup

### ISSUE THREAD

**Issue by sgbeal** [AdguardTeam/AdGuardHome#3619]
### Problem Description

Step 3 of the setup process says:

> It is highly recommended to configure password authentication to your AdGuard Home admin web interface.

However, that step is *required*, not just "highly recommended."

### Proposed Solution

i recommend either changing that verbiage to "A password *must* be configured..." or make this step optional. (i *hate* having to password-protect services on my home LAN, considering i'm the only person who uses them.)

**Comment by sgbeal** [comment]
Absolutely. So long as it's saying what it means, i'm happy :). Thank you! Closing ticket...

**Comment by sgbeal** [comment]
Related FYI, i just accidentally found that the RPi setup docs are out of date and specifically say that a password is optional and explain (incorrectly/out of date, as far as i can tell) how to clear or set the password via the yaml file:

<https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi>

**Comment by ainar-g** [comment]
@sgbeal, yes, we have a dedicated issue about updating that page.  See #2795.  You can add your concerns there if no one else has yet.
