### ISSUE TITLE
[Suggestion] - Per client blocklists/allowlists + disable blocking timer

### ISSUE THREAD

**Issue by t3dium** [AdguardTeam/AdGuardHome#3620]
Just a couple suggestions for adguard home:

The most useful feature for it to have would be per client blocklists/whitelists, as of right now we’re able to do this with individual domains, or to specify different upstreams per client which has been my current solution this, but native per client blocklists/whitelists would be helpful.

Also, having a disable blocking timer would also be a useful feature to have.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/435

We'll definitely do this in the upcoming versions. Hopefully, in v0.108.
