### ISSUE TITLE
CUstom toggle "Blocked services"

### ISSUE THREAD

**Issue by cakens** [AdguardTeam/AdGuardHome#3623]
### Problem Description
I'd like to suggest adding ability for custom toggle "Blocked services". 

For example, I want to block YouTube, but we subscribe to YouTube TV, which I don't want to block. Using the existing YouTube Blocked Service also blocks YouTube tv. (Im guessing the rules are prefix wildcarding YouTube.com)

### Proposed Solution
I'd like to suggest adding ability for custom toggle "Blocked services". 

### Alternatives Considered
I realize I could just block YouTube manually. I want the ability to quickly toggle.

**Comment by ameshkov** [comment]
Tbh, making it that gradual is not possible at this moment. You can use custom filtering rules for that, though.

**Comment by ainar-g** [comment]
Duplicate of #1692.
