### ISSUE TITLE
IPSET_NAME 只有第一个生效

### ISSUE THREAD

**Issue by nameless3721** [AdguardTeam/AdGuardHome#3638]
- [ ✔] I am running the latest version
- [ ✔] I checked the documentation and found no answer
- [✔ ] I checked to make sure that this issue has not already been filed
linux arm64  openwrt
  ipset:
  - gvt1.com/gv,gv1
  - googlevideo.com/gv,gv1
![image](https://user-images.githubusercontent.com/50364156/134229427-d72ba912-8924-4402-a1d1-3bb7a3261f90.png)

ipset list 只有gv 有添加ipset   gv1 没有添加
降级到 v0.106.3 正常

**Comment by ainar-g** [comment]
Hello and thank you for your report!  We have pushed the fix to the `edge` update channel, and it should be shipped in version v0.107.0-a.172+e1e064db.  Could you please check if our solution works for you?  Thanks!

**Comment by nameless3721** [comment]
Thank you, is fixed!
