### ISSUE TITLE
Disallowed clients is automatically Disabled in v0.107.0-a.173+5aed8db5

### ISSUE THREAD

**Issue by leo15dev** [AdguardTeam/AdGuardHome#3643]
### Issue Details

* **Version of AdGuard Home server:**
  *  v0.107.0-a.173+5aed8db5
* **How did you install AdGuard Home:**
  *  Docker
* **How did you setup DNS configuration:**
  *  loT
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 4 Model B
* **CPU architecture:**
  *  ARM64
* **Operating system and version:**
  *  Ubuntu 20.04.3

### Expected Behavior

Disallowed clients  setting can be added what you want to ban 
### Actual Behavior

Disallowed clients is automatically Disabled in v0.107.0-a.173+5aed8db5
### Screenshots

![Screenshot 2021-09-23 at 08-28-47 AdGuard Home](https://user-images.githubusercontent.com/68909774/134439199-70719792-7ee5-4257-972e-b4cef9324f72.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@leo15dev, as the annotation to the setting says: "If allowed clients are configured, this field is ignored".  Have you got any entries in the **Allowed clients** field?

**Comment by leo15dev** [comment]
> @leo15dev, as the annotation to the setting says: "If allowed clients are configured, this field is ignored". Have you got any entries in the **Allowed clients** field?

Oh, I had added some entries in the `Allowed clients`, thanks for your reply, I will close this issue right now. Thanks again!
