### ISSUE TITLE
AdGuard Home Keeps Resetting

### ISSUE THREAD

**Issue by jamess5** [AdguardTeam/AdGuardHome#3650]
Hi,

Every time I restart the Docker container / my server, all the settings reset. When the container starts up, in the logs, I get:

2021/09/24 18:51:43.750234 [info] This is the first time AdGuard Home is launched

I have set up the volumes for the container to save configuration - but it seems like it's not saving and resets every time.

I cannot find any article related to this. Do you have any suggestions on how I can fix this?

Many thanks,
James

**Comment by agneevX** [comment]
Can you share your `docker run` command?

**Comment by jamess5** [comment]
Found the issue - the volumes did not give enough permissions to save. Rectified this and it now works.

**Comment by Kendrik01** [comment]
I'm currently running into the same issue and I'm not sure how to correct it.  Can someone assist?

**Comment by Kendrik01** [comment]
I'm using docker-compose.  Here's my configuration.

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: always

#AdGuardHome - DNS Ad Blocking for Home
  adguardhome:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/adguardhome/work:/opt/adguardhome/work'
      - $DOCKERDIR/appdata/adguardhome/conf:/opt/adguardhome/conf'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '3000:3000/tcp'

**Comment by agneevX** [comment]
>  no-new-privileges: true

I think this could be the culprit.

**Comment by Kendrik01** [comment]
That appears to have solved the issue.  Thanks!

**Comment by madeira83** [comment]
Hi i am getting the same issue and having a hard time fixing it. Pardon as i am a novice with this. I am running docker desktop on windows. if i stop the service from docker desktop and then start the service there is no issues. If I restart my windows computer it factory resets adguard server and prompts me to create new user name and password. I have tried uninstalling and reinstalling the container. I looked at the previous comments regarding permissions and i dont know how to find that option. Also, if you need to see the docker run command can you give me the exact command to enter to get this info. thanks
