### ISSUE TITLE
Displaying statistics

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#3653]
Good afternoon. I use the latest stable version 106.3 The question is, when displaying statistics from what time(hour) to what time is it considered? The settings specify saving statistics for 24 hours. But no matter how you look, there are always 15-20 thousand requests, at least at the beginning of the day, at least at the end. How can I determine from what hour the number of requests specified in the statistics was processed? Why is the statistics not reset to zero at the beginning of a new day? If there is such a setting, tell me how to configure it.
![2](https://user-images.githubusercontent.com/74646605/134774011-3907a5fe-6b43-4f05-9762-1f22993a381d.jpg)
![3](https://user-images.githubusercontent.com/74646605/134774012-0b6c2321-22d9-422b-8600-1c68142e4da2.jpg)

**Comment by HorayNarea** [comment]
It's a sliding window, it always shows the last 24 hours(/7 days/30 days/90 days) from _now_.

**Comment by fizsef** [comment]
And it is impossible to configure it so that it shows exactly from 00:00 hours? Specifically for a calendar day?

**Comment by HorayNarea** [comment]
Correct, that is (currently) not possible.

**Comment by ameshkov** [comment]
Tbh, we don't have plans to change this any time soon. Maybe at some point we'll allow choosing a different time frame and this will become a possibility, there's already a feature request about that.
