### ISSUE TITLE
Inconvenience of the user filters view window.

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#3657]
Why wasn't it possible to make the viewport of custom filters stretchable? It is very inconvenient when there are a lot of records, and the window is small. Scrolling is inconvenient. Usually, in modern software, the user always has the ability to change the size of the window(text field). 
![2](https://user-images.githubusercontent.com/74646605/134801084-f34fb90b-5733-4ae9-bfc1-cd2a36801cc9.jpg)

**Comment by ameshkov** [comment]
Hmm, it actually can be stretched. What browser is it?

**Comment by fizsef** [comment]
Google Chrome 88.0.4324
Brave V1.29.81
Microsoft Edge 
It doesn't work in any browser

**Comment by ameshkov** [comment]
Ah, found the reason, I am using v0.107 beta, it's already added there.

**Comment by ainar-g** [comment]
Dup of #3438.
