### ISSUE TITLE
YouTube stopped blocking ads today

### ISSUE THREAD

**Issue by iAYMANi** [AdguardTeam/AdGuardHome#367]
I'm using the APPLE TV4 DNS: 176.103.130.130 , since recently your dns stopped blocking ads in YouTube, Today?

**Comment by alectrocute** [comment]
YouTube uses random subdomains on the same domains that serve user content to host advertisements. No DNS adblocker will ever be able to block YouTube ads, ever.

**Comment by ameshkov** [comment]
@alectrocute generally, you are right. However, it seems that the way Youtube loads ads it country-specific. For some users, it does use third-party domains.
