### ISSUE TITLE
Check that "load balancing" strategy properly selects the fastest upstream more often

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#3672]
Check the discussion here: https://github.com/AdguardTeam/AdGuardHome/discussions/3601

We need to double-check that it works as it is supposed to.

**Comment by timkgh** [comment]
I think a better strategy for the metric would be to do something like this: every 5 min (or some time interval) send a few requests to **all** servers and keep a count of which one responds fastest, e.g. whichever one gets to 10 (or some number) of fastest responses first. Then that's the server to use for the next 5 min and then repeat the race.
This will ensure that the connections to all servers are kept warm which is important with DoH and DoT connection reuse, we don't want to measure the TLS handshake time, but rather actual response time from the upstreams. Averaging TLS handshake time in the metric is not ideal.

**Comment by EugeneOne1** [comment]
We've improved the description of `all_servers` setting in the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).

**Comment by timkgh** [comment]
@EugeneOne1  This bug was not about documentation but rather that the "load balancing" implementation does not work as expected. Empirical evidence shows that the _slower_ of 2 DNS servers is picked more often.
