### ISSUE TITLE
Android private dns not working.

### ISSUE THREAD

**Issue by shimuldn** [AdguardTeam/AdGuardHome#3696]
Tested on Version: v0.107.0-b.12 and v0.106.3

I have few AGH servers and running. But suddenly android private dns stop working from few days ago for all android phone connected to my servers. Did not change anything to the server. SSL update on September 2021  and August 2021 letsencrypt.

Dns on 53 and over HTTPS and TLS working fine on all servers. Mobile data, WIFI all same.

From android logs:
```
1-10-02T16:52:19.730 - 11434, httpsResult result [android.net.captiveportal.CaptivePortalProbeResult@ba12042], [false, true]
  2021-10-02T16:52:19.730 - 11434, httpResult result [android.net.captiveportal.CaptivePortalProbeResult@7b0853], [false, true]
  2021-10-02T16:52:25.288 - Strict mode hostname resolved: PrivateDnsConfig{true:xxx.domain.com/[/xxx.xxx.yyy.ddd]}
  2021-10-02T16:52:33.816 - PROBE_PRIVDNS ae632a6c-dnsotls-ds.metric.gstatic.com 8526ms - Error: Unable to resolve host "ae632a6c-dnsotls-ds.metric.gstatic.com": No address associated with hostname
```

`true:xxx.domain.com/[/xxx.xxx.yyy.ddd]` (Valid IP)
So android able to resolve the ip address of agh server.

It's really wired that all server stop working for private dns when different server, different vps provider and different android  phones.

`dns.adguard.com` working fine.

**Comment by Disqu3-mirOir-qt** [comment]
exactly same issue for my users , android dns private not work (tls) but client(app) tls work

i get no logs or error , realy hard debug this 

maybe problem with certificat revoking ( IdentTrust DST Root CA X3)

i generated new certificat , not solved 

thanks 

i try downgrade beta 11 same issue

**Comment by Habetdin** [comment]
> maybe problem with certificat revoking ( IdentTrust DST Root CA X3)

I have faced the issue exactly next minute after the IdentTrust DST Root CA X3 expiration timestamp.

> i generated new certificat , not solved

Force renewal with `--preferred-chain "ISRG Root X1"` option (supported by certbot as well as by acme.sh) solved the problem for me. You can debug your host's SSL trust chains by using https://www.ssllabs.com/ssltest/ and similar services.

**Comment by Akruidenberg** [comment]
> > maybe problem with certificat revoking ( IdentTrust DST Root CA X3)
> 
> I have faced the issue exactly next minute after the IdentTrust DST Root CA X3 expiration timestamp.
> 
> > i generated new certificat , not solved
> 
> Force renewal with `--preferred-chain "ISRG Root X1"` option (supported by certbot as well as by acme.sh) solved the problem for me. You can debug your host's SSL trust chains by using https://www.ssllabs.com/ssltest/ and similar services.

How to do this with traefik?

**Comment by tdemeyere** [comment]
I have faced the same problem.
M'y Let's Encrypt certificate is generated by my Synology NAS, which run the official AdGuard Home docker image.
I can't modify the prefered chain, so I have manually removed the third certificate in the fullchain.pem.
I think a proper solution would be to remove the expired certificate from the root.pem in the official docker image, no ?

**Comment by rafagale** [comment]
Im facing the same issue, thanks @tdemeyere for your workaround

**Comment by shimuldn** [comment]
@Habetdin 

Thank you.

`--preferred-chain "ISRG Root X1"` fixed the problem.

**Comment by Disqu3-mirOir-qt** [comment]
i use zeroSSL fixed for me

**Comment by ainar-g** [comment]
See also: #3689.
