### ISSUE TITLE
long time response using google drive or icloud drive services

### ISSUE THREAD

**Issue by alesaund** [AdguardTeam/AdGuardHome#3702]
Hello,
i do massive use of Google Drive and icloud Drive on web interface on both windows and mac, using Chrome and Safari.

Connection speed is very slow using this services and response require a lot (5/20 sec) . i have gigabit connection at home.

when using windows on chrome it appear a page whit this error: DNS_PROBE_STARTED

**Comment by EugeneOne1** [comment]
@alesaund, hello.  Could you please provide some details about your setup:

 1. Which version of the AdGuard Home is used?
 1. What the CPU and the OS are on the AdGuard Home's machine?
 1. How did you set the DNS configuration?

Also, if the issue reproduces with AGH turned off?

**Comment by EugeneOne1** [comment]
@alesaund, any updates since?  If the problem recurs?
