### ISSUE TITLE
AdGuard Home "without additional software"

### ISSUE THREAD

**Issue by nightznero** [AdguardTeam/AdGuardHome#3720]
Hello! I have a problem,cause i was reading that AdGuard Home dont requirment any other applications to work but... after installation when i close my pc(and ofc cmd with adguard home) the ADH stop working. It there any solution for that? Or since is beta i have to power my pc on 24/7 to properly ADH working? Grettings :)

**Comment by TheCeet** [comment]
Buy a Raspberry Pi?
