### ISSUE TITLE
problem on source compiling

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#373]
hi there in russia

on compiling the source, i've got this problem

### Steps to reproduce

1. apt install nodej openlang
2. git clone https://github.com/AdguardTeam/AdGuardHome
cd AdGuardHome
make

### Expected behavior

it should compile

### Actual behavior

<details><summary>Screenshot:</summary>

```

github.com/gobuffalo/packr/packr
mkdir -p /root/AdGuardHome/build/gopath/src/github.com/AdguardTeam/AdGuardHome/build/static ## work around packr bug
cd /root/AdGuardHome/build/gopath/src/github.com/prometheus/client_golang && git reset --hard v0.8.0
HEAD is now at c5b7fcc Merge pull request #226 from prometheus/beorn7/alloc
perl -0777 -p -i.bak -e 's/pprofOnce.Do\(func\(\) {(.*)}\)/\1/ms' /root/AdGuardHome/build/gopath/src/github.com/coredns/coredns/plugin/pprof/setup.go
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/pprofOnce.Do\(func\(\) { <-- HERE (.*)}\)/ at -e line 1.
perl -0777 -p -i.bak -e 's/c.OnShutdown/c.OnRestart/' /root/AdGuardHome/build/gopath/src/github.com/coredns/coredns/plugin/pprof/setup.go
GOPATH=/root/AdGuardHome/build/gopath PATH=/root/AdGuardHome/build/gopath/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin packr build -ldflags="-X main.VersionString=v0.1-271-ga267" -o AdGuardHome
Error: /root/AdGuardHome/build/gopath/src/github.com/golang/protobuf/protoc-gen-go/testdata/import_public/a.pb.go:25:8: expected type, found '=' (and 8 more errors)
Usage:
  packr build [flags]

Flags:
  -h, --help   help for build

Global Flags:
  -v, --verbose   print verbose logging information

Makefile:25: recipe for target 'AdGuardHome' failed
make: *** [AdGuardHome] Error 255
```

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

Running armbian on a bananpi m64 (debian v 4.4)

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

**Comment by ameshkov** [comment]
@ibksturm hey there! What version of `go` do you have?

**Comment by ameshkov** [comment]
I can confirm that the version in the master branch can be built just okay with the following go versions:

```
$ go version
go version go1.10.3 darwin/amd64
```

```
$ go version
go version go1.11 darwin/amd64
```

**Comment by ibksturm** [comment]
hi andrej (right?) 

i'm using 1.7.4 (as in the debian packages), but  now i'm compiling go 1.11 from github source...

**Comment by ameshkov** [comment]
> hi andrej (right?)

Yeah:)

> i'm using 1.7.4 (as in the debian packages), but now i'm compiling go 1.11 from github source...

You need to use 1.9+, 1.7 is quite old

**Comment by ibksturm** [comment]
spasibo (a russia co worker of me teached me some words)

**Comment by ameshkov** [comment]
@ibksturm Bitte :)

**Comment by OMICRON3069** [comment]
Hi~
It seems I got same issue on compiling.
```
mkdir -p /home/Aaron/AdGuardHome/build/gopath/src/github.com/AdguardTeam
if [ ! -h /home/Aaron/AdGuardHome/build/gopath/src/github.com/AdguardTeam/AdGuardHome ]; then rm -rf /home/Aaron/AdGuardHome/build/gopath/src/github.com/AdguardTeam/AdGuardHome && ln -fs /home/Aaron/AdGuardHome /home/Aaron/AdGuardHome/build/gopath/src/github.com/AdguardTeam/AdGuardHome; fi
GOPATH=/home/Aaron/AdGuardHome/build/gopath go get -v -d .
GOPATH=/home/Aaron/AdGuardHome/build/gopath GOOS=linux GOARCH=amd64 go get -v github.com/gobuffalo/packr/...
mkdir -p /home/Aaron/AdGuardHome/build/gopath/src/github.com/AdguardTeam/AdGuardHome/build/static ## work around packr bug
cd /home/Aaron/AdGuardHome/build/gopath/src/github.com/prometheus/client_golang && git reset --hard v0.8.0
HEAD is now at c5b7fcc Merge pull request #226 from prometheus/beorn7/alloc
perl -0777 -p -i.bak -e 's/pprofOnce.Do\(func\(\) {(.*)}\)/\1/ms' /home/Aaron/AdGuardHome/build/gopath/src/github.com/coredns/coredns/plugin/pprof/setup.go
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/pprofOnce.Do\(func\(\) { <-- HERE (.*)}\)/ at -e line 1.
Makefile:25: recipe for target 'AdGuardHome' failed
make: *** [AdGuardHome] Error 255
```
System : Ubuntu 18.04 on google compute engine 

I'm using go version 1.11 which download from https://dl.google.com/go/go1.11.linux-amd64.tar.gz 

BTW the go version 1.10.4 downloaded by apt will got same result

**Comment by ameshkov** [comment]
@hmage ?
