### ISSUE TITLE
AGH does not accept ED25519 algorithm for HTTPS encryption

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#3737]
I generate my own certificates and keys for localhost and use AGH only for private LAN clients. 

AGH accepts certificate and key created created with RSA algorithm:
`openssl genrsa -out localhost.key 4096`
AGH does not accept certificate and key created with
`openssl genpkey -algorithm ed25519 -out localhost.key`

Any idea why? Is it just a limitation?

**Comment by ainar-g** [comment]
The error message has now been merged.  I think that that's enough for now.  We should revisit this in the future, though, if enough web browsers start to actually work well with such private keys.
