### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by mrtargaryen** [AdguardTeam/AdGuardHome#374]
How do I uninstall. I've encountered a number of errors but don't have time to address them now. SO I'd like to completely uninstall AdGuard Home and try again later.

Thanks.

**Comment by hmage** [comment]
Hi!

If you were following our [installation instructions in readme](https://github.com/AdguardTeam/AdGuardHome#installation) and didn't do anything else, then uninstalling is simple -- just delete the `AdGuardHome` directory.

If you did something else during installation, you will need to undo these actions manually.

Hope this helps. If not, feel free to reply here.

**Comment by mrtargaryen** [comment]
Yeah, I think in the rush of the day I screwed it up. I just click on the the executable file to install it, I'm pretty sure it didn't install correctly as I received numerous red error boxes in the UI. Would you have any idea what directory the files would have installed into so I can delete them?

**Comment by hmage** [comment]
It's not an installer, it's an executable. We don't have "double click to install" functionality. You just run it. Simply deleting will suffice.

**Comment by mrtargaryen** [comment]
No worries. Thanks.
