### ISSUE TITLE
Allowlist does not seem to work for CNAME

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3741]
AGH v0.107.0-b.13

I'm using this NextDNS affiliate tracking domains as an **allow** list in AGH:
https://raw.githubusercontent.com/nextdns/metadata/master/privacy/affiliate-tracking-domains

It has an entry:
`customtraffic.impactradius.com # CNAME of goto.target.com`
https://github.com/nextdns/metadata/blob/master/privacy/affiliate-tracking-domains#L303

But it doesn't seem to work in AGH, the lookup `goto.target.com` is still blocked:
```
> dig goto.target.com

;; ANSWER SECTION:
goto.target.com.	10	IN	A	0.0.0.0
```

![image](https://user-images.githubusercontent.com/23507658/137569947-e1d902aa-0d5e-4615-a737-ac6e17cf60d4.png)

This appears to be a CNAME issue:
```
> dig goto.target.com @8.8.8.8

;; ANSWER SECTION:
goto.target.com.	512	IN	CNAME	goto-target-com.customtraffic.impactradius.com.
goto-target-com.customtraffic.impactradius.com.	300 IN A 34.102.140.44
```

AGH allows `customtraffic.impactradius.com`:

![image](https://user-images.githubusercontent.com/23507658/137570017-ed1cf46a-b1c5-424a-80f1-a6dec2abb54f.png)

Related: https://github.com/AdguardTeam/AdGuardHome/discussions/3700

**Comment by timkgh** [comment]
@EugeneOne1  It makes sense, thanks. It seems that I would want the equivalent of that NextDNS list but in `@@||...^` ABP format (or with wildcards) to allow subdomains too.

Any suggestions for such an allow list that works well with AGH?

**Comment by EugeneOne1** [comment]
@timkgh, again, you may always add your own custom rules list with entries you needed.  All the supported rules formats are described in detail in our [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists).

If you have any questions, you can always search through GitHub discussions, especially the [Q&A topic](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a).  We're going to close the issue for now if you don't mind.
