### ISSUE TITLE
v0.107.0-b.13 - DHCP 6 ips  function is broken, worked in official release v0.106.3

### ISSUE THREAD

**Issue by hijglander** [AdguardTeam/AdGuardHome#3744]
- [ X] I am running the latest BETA version. v0.107.0-b.13
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home, version v0.107.0-b.13
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * Via Adguard 
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 Model B && Raspberry Pi 3 Model B
* **CPU architecture:**
  * ARMv7
* **Operating system and version:**
  * Debian v11 && Rasbian v10

### Expected Behavior
Two DNS servers get propagated via DHCP to the DHCP Clients

### Actual Behavior
Only the IP of the Adguard installation is advertised to the clients.. switching back to the official release fixes this issue.

**Comment by EugeneOne1** [comment]
@hijglander, hello and thanks for the report!  We can reproduce it and it's a legit bug.  Going to fix it in the nearest time.

**Comment by EugeneOne1** [comment]
@hijglander, we've just updated the edge channel with build that should fix this issue.  Could you please install it an check if it now uses the values from configuration file?
