### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by iam-py-test** [AdguardTeam/AdGuardHome#3747]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

There appears to be a typo on https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#modifiers, adding an extra `, which causes the text to display incorrectly 

I am not running AdGuard Home, so the other fields are irrelevant. This is my first time opening an issue in an AdGuard repo, so please forgive me if I make an error

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior

I would expect it to display similar to this:
`client=127.0.0.1` is the [`client`](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client) modifier with its value, ` 127.0.0.1 ` ,is the delimiter. And finally, ` dnstype=A ` is the [dnstype](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnstype) modifier with its value, A.

### Actual Behavior

It displays weirdly, with odd parts in code style, raw Markdown being shown, and one link not working

### Screenshots

<details><summary>Screenshot:</summary>
<img src="https://user-images.githubusercontent.com/84232764/137811961-ab831384-553e-422e-8028-050057513ab7.png">

</details>

**Comment by EugeneOne1** [comment]
@iam-py-test, hello and thank you for the report!  There is actually a mistake with an extra "`", we'll fix it in the nearest future.
