### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#375]
Given you have MacOS binaries, any chance of Windows binaries as I would like to run this on a Windows server.

**Comment by ameshkov** [comment]
It can be compiled for Windows, but it does not work at the moment, we didn't have enough time to figure the exact reason. We will, though:)

**Comment by hmage** [comment]
Hi.

As of now, we can't support Windows because the DNS server library we're using has an outstanding bug -- https://github.com/coredns/coredns/issues/2002.

I'm not saying it will never happen, and there's a possibility we will switch from coredns to another solution if neccessary.

**Comment by ameshkov** [comment]
Lol, apparently, Eugene had enough time :)

Actually, there're a lot of people demanding windows build so we might need to figure a workaround and not waiting for it to be fixed in coreDNS.

**Comment by Daist** [comment]
Hi, have you tried running this software in WSL (Windows Subsystem for Linux)?

**Comment by hmage** [comment]
@Daist not yet, but it could work there, yes.

**Comment by hmage** [comment]
@TPS Thanks for understanding.

Once I get ahold of windows machine I’ll do test it under WSL.

**Comment by TPS** [comment]
NP, but my Disqus post on the AGHome announcement asks for a _lot_ more! 😚

**Comment by hmage** [comment]
It *does* work under WSL.

🎉 

![capture](https://user-images.githubusercontent.com/739119/47102204-c0429c00-d244-11e8-9311-016265e1a8bd.PNG)

**Comment by AnthonyBe** [comment]
One major downside with relying on WSL is that it is only included in Windows 10 and Windows Server Insider Preview Build (aka. Windows 2019) so that heavily restricts where it could be used.

Reference: https://docs.microsoft.com/en-au/windows/wsl/about

It would be much better (obviously) if it could run natively on any currently supported version of Windows client or server OS. I do appreciate the blocker at the moment (if I'm not mistaken) is in the Go dependency which takes control of this problem out of your hands to a large degree.

**Comment by TPS** [comment]
@AnthonyBe Of _course_, you're right, but this is just meant to be a quick-&-dirty hack so enthusiasts can try it out on Windows.  I'm reasonably sure @AdGuardTeam is reserving v1.0 for an official _native_ Windows release.

@hmage Any wiki so we don't have to go through _(what looks to be, based on posts' time-difference)_ ~2 hours of trial-&-error?

**Comment by ewrogers** [comment]
If you want something working **today** on v0.9, use Docker:

- Windows 10 x64 Pro/Enterprise/Education users can simply [https://docs.docker.com/docker-for-windows/install/](Install Docker for Windows). This can run containers natively using Hyper-V.

- Legacy Windows users can install [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/). This will use the `docker-machine` VM behind the scenes to run your containers.

- Alternatively, use [VirtualBox](https://www.virtualbox.org) with your choice of Linux distro (Ubuntu would be friendly for most).

- For older Windows XP/7/8 machines, consider [Ubuntu Wubi](https://wiki.ubuntu.com/WubiGuide) which allows installation side-by-side with Windows (and can be uninstalled easily).

My AdGuard Docker images can be found here:

- [https://hub.docker.com/r/ewrogers/adguard-home-linux/](Linux x86 32-bit)

- [https://hub.docker.com/r/ewrogers/adguard-home-linux/](Linux x86 64-bit)

- [https://hub.docker.com/r/ewrogers/adguard-home-linux/](Linux ARM - Raspberry Pi)

**Comment by hmage** [comment]
Under WSL it also works today.

**Comment by TPS** [comment]
@hmage Did you get to post a wiki w/ your steps to install/run AdGuardHome via WSL?

**Comment by AnthonyBe** [comment]
@hmage Which Linux distro did you use in WSL?

**Comment by ilgrank** [comment]
...still hoping for an update :) 👍

**Comment by AnthonyBe** [comment]
me too! :)

While I do have it running on my Win10 PC using WSL, I'm finding that the average processing time is consistently >140ms and I'm definitely noticing the impact on general web page opens/loads. Given my PC hardware is Core i7, 16GB RAM, etc. and not under any load, I can only assume there is an overhead in the WSL layer so having native Windows binaries (and ideally x64 binaries) will, I hope, improve performance significantly.

**Comment by ameshkov** [comment]
It seems that we'll be able to do it in v0.92 btw.

> I'm finding that the average processing time is consistently >140ms

It's possible that the upstream is too slow.

**Comment by AnthonyBe** [comment]
That's wonderful news!

**Comment by ameshkov** [comment]
Resolved in the master branch
