### ISSUE TITLE
Package for Synology router

### ISSUE THREAD

**Issue by ClassicUA** [AdguardTeam/AdGuardHome#376]
Сделайте пакет для Synology router.

**Comment by Alex-302** [comment]
ping

**Comment by ameshkov** [comment]
Ну у нас на это не особо есть время, но если кто-то нам пулл-реквестнет - мы посмотрим

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1078

**Comment by ameshkov** [comment]
http://bin.entware.net/mipselsf-k3.4/test/
