### ISSUE TITLE
Static IP leases outside of dynamic IP range not possible in 107

### ISSUE THREAD

**Issue by turnma** [AdguardTeam/AdGuardHome#3767]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

https://github.com/AdguardTeam/AdGuardHome/issues/2838 talks about a change to AdGuard Home to allow static leases if they are INSIDE the subnet range even if they're OUTSIDE of the DHCP scope range.  I have an config on an instance of AGH (106.3) that allows me to have reservations outside of the scope range, but another instance I've built recently on v0.107.0-a.194+ea8950a8 no longer allows me to do this. When I try I get the error "Must be in range _scope-range_".  So, assuming that issue 2838 FIXED this issue then it appears to have been reintroduced in the 107.x code.

* **Version of AdGuard Home server:**
v0.107.0-a.194+ea8950a8
* **How did you install AdGuard Home:**
Manually 
* **How did you setup DNS configuration:**
n/a
* **If it's a router or IoT, please write device model:**
n/a
* **CPU architecture:**
rPi
* **Operating system and version:**

### Expected Behavior
I'd expect to be able to add static IP leases outside of the range, as I could in older versions.

### Actual Behavior
I'm prevented from doing this, as written above.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@turnma, it should be fixed as of snapshot 30511ec.  Could you please check if the problem persists?

**Comment by turnma** [comment]
Tested and now working again perfectly.  Thanks.
