### ISSUE TITLE
Add a docker image for AdGuard Home

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdGuardHome#377]

**Comment by hexeth** [comment]
A docker image would be a huge help

**Comment by sc0rp10** [comment]
I can PR this in 6-8 hrs

**Comment by ashmckenzie** [comment]
https://github.com/ashmckenzie/adguard-home-docker and https://hub.docker.com/r/ashmckenzie/adguard-home 😁

**Comment by hmage** [comment]
Done via #392

**Comment by ameshkov** [comment]
Reopening as with v0.91 release we'll have to rework docker image considerably.

**Comment by ewrogers** [comment]
Please mention me when 0.91 is released and I will re-work the docker images to better support these changes.

**Comment by ameshkov** [comment]
@ewrogers will do, thank you!

**Comment by jimaek** [comment]
Hey, I was wondering on the ETA of Docker images. I would prefer to use the official image instead of third-party. And hopefully you can add instructions on how to persist the settings

**Comment by integrii** [comment]
I ended up building and hosting my own dockerfile on docker hub, but I am curious why AdGuard does not maintain a public image.  This would make updates really easy, because we would all subscribe to `:latest`.

**Comment by ameshkov** [comment]
@integrii we registered an official account on hub.docker.com and prepared everything for automatic images publishing.

Shortly after v0.93 is released, we'll announce the official images as well.

The `latest` tag will correspond to the `master` branch (so it will be unstable), and `vXX.XX` tags will be published automatically for every new Github release.

**Comment by integrii** [comment]
Awesome @ameshkov !  I really like AdGuard.  Thanks!!

**Comment by ameshkov** [comment]
Here we go, the `latest` builds are already on docker hub and you can try them:
https://hub.docker.com/r/adguard/adguardhome

Please note, that these builds are automatically pushed there on every `master` change so they might be buggy / unstable.

**Comment by hexeth** [comment]
Deploying the current docker image just returns this and stops. 

```Usage:
/AdGuardHome [options]
Options:
  -c, --config                       path to config file
  -o, --host                         host address to bind HTTP server on
  -p, --port                         port to serve HTTP pages on
  -s, --service                      service control action: status, install, uninstall, start, stop, restart
  -l, --logfile                      path to the log file. If empty, writes to stdout, if 'syslog' -- system log
  -v, --verbose                      enable verbose output
  -h, --help                         print this help```

**Comment by ameshkov** [comment]
Uh, yeah, this parameter short name was changed in one of the commits. We'll fix it, thank you!

**Comment by ameshkov** [comment]
@hexeth in a few minutes the updated images will be pushed: https://travis-ci.org/AdguardTeam/AdGuardHome/jobs/489222773

**Comment by ameshkov** [comment]
It's final: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.93
