### ISSUE TITLE
Missing log entries

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3772]
v0.107.0-b.13

Not sure whether this has to do with optimistic caching or using domain specific upstreams or a combination of both. I use optimistic caching and the rule below for upstreams because I don't want safe search from the general upstreams:
`[/www.google.com/www.youtube.com/m.youtube.com/youtubei.googleapis.com/youtube.googleapis.com/www.youtube-nocookie.com/]https://8.8.8.8/dns-query`

Initially I see a few entries in the `query.json*` log files for the google/youtube domains above with an `Upstream` of 8.8.8.8 as expected but then I _never_ see any more entries again with an `Upstream` set for these domains. There are log entries _without_ `Upstream` and a very short `Elapsed` time which I assume are served from the cache.

I'm not sure why, whether AGH always answers from the cache or the log file is just missing entries when the query is the result of an optimistic cache miss.

**Comment by ameshkov** [comment]
@ainar-g @EugeneOne1 I suggest solving it in the following way: add "Upstream" information to the cache items. Also, add a marker that distinguishes cached items from those resolved from the upstream.

Here's how these records should look like in the Query Log's response details:
![image](https://user-images.githubusercontent.com/5947035/142896993-95282722-1bbf-4588-ac11-d259cac0cfd8.png)

**Comment by EugeneOne1** [comment]
@timkgh, I'll close the issue for now.  Please feel free to reopen it if the introduced logic will produce any problems.

**Comment by timkgh** [comment]
I will give it a try in b16 and report back if there are still issues.
