### ISSUE TITLE
adguard-malware-shavar blocks Netflix-CDN *oca.nflxvideo.net

### ISSUE THREAD

**Issue by osxdoc** [AdguardTeam/AdGuardHome#3779]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Home Assistant (Docker)
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * ODROID-N2+
* **CPU architecture:**
  * ARM

### Expected Behavior
Since today filter update, Adguard Home blocks Netflix-CDN (in Germany) *oca.nflxvideo.net

### Actual Behavior
Netflix website works, but no videoplabakc possibe on any Device in network (LGTV/iMac/iPad/Windows11...)

### Screenshots
<img width="1196" alt="Bildschirmfoto 2021-10-28 um 18 57 26" src="https://user-images.githubusercontent.com/19705969/139301357-419548cf-1721-41c3-9520-23a63036360e.png">

<details><summary>Screenshot:</summary>

<img width="364" alt="Bildschirmfoto 2021-10-28 um 18 59 01" src="https://user-images.githubusercontent.com/19705969/139301544-d46383fc-851e-4ef3-9d82-1533fe6a7e1f.png">

</details>

**Comment by ainar-g** [comment]
Hello everyone and apologies for the late response.  In the future, please report such via the [issue reporting form][1] or by sending an E-mail to support@adguard.com.  I've forwarded your report to the people who maintain the lists, and they said that the domain pattern should be removed from the list now.  If not, please write them.

[1]: https://reports.adguard.com/en/new_issue.html

**Comment by meizenga** [comment]
Same. Adding @@||oca.nflxvideo.net to the custom filters did the trick. Also, I didn't see any blocks in the log, everything was PROCESSED
