### ISSUE TITLE
adguard-malware-shavar Blocks a number of safe sites

### ISSUE THREAD

**Issue by Saber1998** [AdguardTeam/AdGuardHome#3780]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

Starting today 10/28/2020 Adguard Home started blocking a number of safe sites. So far the safe sites I have had to unblock are as follows:

login.microsoftonline.com
coingecko.com
messaging.officeppe.com
laptop-updates.brave.com
aadcdn.msauth.net
coinmarketcap.com

2 of the domains are Microsoft domains involved for Authentication, I'm not sure I follow the logic of how those are threats..

**Comment by Saber1998** [comment]
This appears to be resolved as AdGuard Home is no longer blocking the domains above after testing it by removing them from the white list. I'll keep an eye on it for 48-72 hours for further confirmation and if all is well I will close this issue.

**Comment by YBS-PC** [comment]
trendmicro requests  from asus router are blocked
ntd-asus-2014b-en.fbs20.trendmicro.com
rgom10-asus-en.url.trendmicro.com
etc

**Comment by Saber1998** [comment]
Issue appears to be resolved, and I'm seeing the domains listed by YBS-PC resolving correctly from my AdGuard Home installations, so I'm going to close this issue.

**Comment by prologic** [comment]
Came here to say that v0.107.17 is all of a sudden classifying my bank's domain as malware `www.my.commbank.com.au` and `netbank.com.au` and `commbank.com.au` -- Note I cannot upgrade due to #5927

**Comment by josephbu** [comment]
> Came here to say that v0.107.17 is all of a sudden classifying my bank's domain as malware `www.my.commbank.com.au` and `netbank.com.au` and `commbank.com.au` -- Note I cannot upgrade due to #5927

@prologic Yep it's being flagged by AdGuard for whatever reason :-\

```
$ dig www.commbank.com.au @94.140.14.15

;; ANSWER SECTION:
www.commbank.com.au.	3600	IN	A	94.140.14.33
```
You can go to Settings -> General Settings and untick "Use AdGuard browsing security web service".

Alternatively you can add a rules under Filters -> Customer Filtering Rules something like `@@||commbank.com.au^$mybankimportant`

**Comment by intari** [comment]
All .dreamwidth.org subdomains (including not existing ones) gets blocked too in Chrome.
Disabling "Use AdGuard browsing security web service" in general settings doesn't appear to help.
Firefox(which should also use Google's safebrowsing) which doesn't go via adguard home in my setup appears to work.
