### ISSUE TITLE
username filtering function

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdGuardHome#3783]
There are so many network scanners out there, can we have a username filtering function?

![image](https://user-images.githubusercontent.com/75058881/139521577-2ec8cc53-59ad-4118-8f5e-01d6034ad48f.png)

e.g. **Only accept** prefix `dns-` and remove the prefix string automatically.

IF prefix string setting: `dns-`
```
https://mydns.me/dns-query/dns-my-pc --> userID: my-pc
quic://dns-android-tv.mydns.me:8853 --> userID: android-tv
```

IF prefix string setting: `Gu2w8g--` (as a sort of... verification?): 
```
https://mydns.me/dns-query/Gu2w8g--my-pc --> userID: my-pc
quic://Gu2w8g--android-tv.mydns.me:8853 --> userID: android-tv
```

**Comment by ainar-g** [comment]
Hello.  I cannot quite understand the issue.  You can already filter out users based on their ClientIDs using the DNS Access Settings.
