### ISSUE TITLE
Continuous logging to file (querylog.json) not working

### ISSUE THREAD

**Issue by wynnchel** [AdguardTeam/AdGuardHome#3788]
- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

* **Version of AdGuard Home server:**
  v0.106.3
* **How did you install AdGuard Home:**
  Docker
* **How did you setup DNS configuration:**
  System
* **If it's a router or IoT, please write device model:**
  NUC
* **CPU architecture:**
  AMD64
* **Operating system and version:**
  Debian Buster 10.1

### Expected Behavior
Logs are continuously written to the querylog.json file.

### Actual Behavior
Logs are only written to the querylog.json file, if the container is restarted or recreated

**Comment by ainar-g** [comment]
Hello.  Please show the command you use to start AGH.  In particular, make sure that your `workdir` and `confdir` volumes are mounted to some persistent storage.

**Comment by wynnchel** [comment]
Hi, sorry for the late reply:

I'm using the offical docker image of adguard which ist started by the docker-compose command. I didn't alter anything in the container.

The `workdir` and the `confdir` are mounted to persistent storage:

```
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
 ```

**Comment by ainar-g** [comment]
I see.  That may be related to #3781.  The upcoming v0.107.0-b.14 release will contain the fix for that issue.
