### ISSUE TITLE
Dockerize AdGuard Home and Create Hass.io addon

### ISSUE THREAD

**Issue by Boosik** [AdguardTeam/AdGuardHome#379]
I wonder if you could dockerize AdGuard Home and create Hass.io addon with it?
Tutorial to Hass.io addons: https://developers.home-assistant.io/docs/en/hassio_addon_tutorial.html
There is already a PiHole addon - https://github.com/hassio-addons/addon-pi-hole - so I think that AdGuard Home addon should be possible.

**Comment by hmage** [comment]
Seems like a duplicate of #377. Need to dockerize it first before hass.io can be done.

**Comment by ameshkov** [comment]
Actually, we should keep this open as it's not just about docker image, but about a hassio addon.

**Comment by noorbertt** [comment]
> Seems like a duplicate of #377. Need to dockerize it first before hass.io can be done.

This part looks like done :) : https://github.com/AdguardTeam/AdGuardHome/issues/377#issuecomment-430996374

**Comment by frenck** [comment]
Hi, I'm the creator of the Community Hass.io Add-ons project.
Just wanted to let you know, the add-on is being built.

**Comment by ameshkov** [comment]
@frenck awesome, thank you!

**Comment by frenck** [comment]
@ameshkov While we are on a subject here... I'd like to get in touch with you (or one of the other developers) for some questions?

Can we hook up on Discord or something else?

**Comment by frenck** [comment]
Context btw: Persistent storage of data, since IMHO your Docker images are broken A.F. (or I'm missing something, but the code did not give me much more either).

**Comment by ameshkov** [comment]
It makes sense to wait for v0.91 release as it brings some considerable changes and we'll have to rework the docker image once it's done.

> Can we hook up on Discord or something else?

I don't use Discord, but you can reach me by email: `am@adguard.com` or in Telegram if you use it.

**Comment by frenck** [comment]
This is now awaiting milestone 0.92

**Comment by ameshkov** [comment]
> Any progress on this? I have everything ready to go, but just missing the configuration storage location refactoring I guess...

Sorry for the delay. I really hope Santa will help us crack the built-in DHCP server issues and we'll push the release next week.

**Comment by frenck** [comment]
Add-on is finished now and doing some final tests before release.

Planned release for all Hass.io supported systems and architectures (amd64, armhf, aarch64 and i386).

**Comment by frenck** [comment]
Home Assistant add-on for Hass.io has been released.

Release Twitter message:
https://twitter.com/Frenck/status/1083480233322385408

Repository:
https://github.com/hassio-addons/addon-adguard-home


@ameshkov That should make this issue ready to close.
Thanks, @Boosik for suggesting it!

**Comment by Boosik** [comment]
Thank you for the creation of the addon @frenck and for docker images @ameshkov 
I'm closing this issue.

**Comment by ameshkov** [comment]
@frenck thank you!
