### ISSUE TITLE
Adding "The Big List of Hacked Malware Web Sites" makes queries for localhost return 0.0.0.0

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3790]
Adding the builtin security list **The Big List of Hacked Malware Web Sites** causes DNS queries for `localhost` to return `0.0.0.0`

I _think_ it's because of this entry that turns localhost into a blocked domain:
https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/blob/master/hosts#L18

I know that such queries shouldn't end up on DNS servers, but they do, clients are broken and we have no control over them.

Can AGH have a built-in rule to always return 127.0.0.1 for localhost A queries and ::1 for AAAA queries?

**Comment by ainar-g** [comment]
This seems like an issue with that particular list, and adding hacks to prevent such behaviour doesn't seem wise to me.  In fact, someone might have legitimate reasons to rewrite `localhost` to something other than 127.0.0.1.

@ameshkov, what do you think?

**Comment by timkgh** [comment]
It is an AGH vetted list, it should not be breaking `localhost`.

**Comment by ameshkov** [comment]
https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/pull/15
