### ISSUE TITLE
LTS version

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdGuardHome#3798]
I hope there can be a LTS version, a version that can be placed on the cloud server, except for the first setting, nothing to worry about.

**Comment by ainar-g** [comment]
How do you see an LTS version being different?  What you're describing is pretty much what we aim for anyway.

**Comment by c2xusnpq6** [comment]
> How do you see an LTS version being different?  What you're describing is pretty much what we aim for anyway.

okay~😁
