### ISSUE TITLE
Can't refresh stats

### ISSUE THREAD

**Issue by eiruuru** [AdguardTeam/AdGuardHome#380]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

**Comment by hmage** [comment]
Thanks for report, but you provided no information, therefore can't help you.

Would you please write down in plain words what happens and what you click, screenshots are also super helpful.
