### ISSUE TITLE
[Feature] Read-Only User / RBAC

### ISSUE THREAD

**Issue by steveredden** [AdguardTeam/AdGuardHome#3806]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
I would like the ability to create additional read-only users.
I would like the ability to grant access to the `*/control/querylog` path

### Proposed Solution
Allow for new user creation, stored in `AdGuard.yaml::users`
Allow for discrete allowances per page (I'm specifically hoping for the `Query Log` page to be enabled

### Alternatives Considered
N/A

### Additional Information
Allows read-only users (say, a spouse) to view what was blocked and why...

**Comment by ainar-g** [comment]
Merging into #997.
