### ISSUE TITLE
Adguard Home: 1 device does not appear in Query Log

### ISSUE THREAD

**Issue by AJK301** [AdguardTeam/AdGuardHome#3808]
Have been using Adguard Home on a Pi for some time and things seemed to be working fine, except for one Linux laptop. It appears in the query log immediately after booting, with requests showing for about 5 minutes. After that, there are no further requests showing from that device (neither by hostname nor IP), not processed, not blocked, not allowed. But the statistics show it as the 4th leading source of requests over the past 7 days. All other devices (about 15) appear as expected. And it seems like ads are blocked, although I have other ad and tracker blockers in use, so that could be misleading. Ideas?

**Comment by ainar-g** [comment]
Hello and thank you for the report.  A few questions:

1.  Do you have IP anonymisation enabled?
2.  Are you sure that the laptop in question actually uses AGH?  That is, if you add a custom rule that disables access to, say, `example.com`, does the site become unavailable from that laptop?

**Comment by AJK301** [comment]
Thanks for the reply.


1. I do not have IP anonymisation turned on.


2. This is the interesting part. I have attached a query log screenshot filtered for AlanLaptop that I just ran (11/8 at about 10:00). It shows AlanLaptop being processed until about 11/7 at 09ish and then nothing after that. I also tried your experiment and blocked a site then tried to access it. it displayed no problem (!), so it appears the AlanLaptop is somehow intermittantly bypassing AGH.


Note that when I first noticed the problem, it seemed that AlanLaptop would appear in the logs for a few minutes after booting, and then nothing. That would be consistent with what is in the log as I booted the system on 11/7 at about the time shown. However, there was nothing at all in the log after I booted this morning for AlanLaptop. 


I've used AGH for several years and nothing like this happened. Everything's always been flawless. However, it is interesting that I just switched AlanLaptop from being a windows machine to Linux Mint. I'm at a loss!


Alan

On Monday 08 November 2021 07:00:42 AM (-05:00), Ainar Garipov wrote:



Hello and thank you for the report. A few questions:

Do you have IP anonymisation enabled?
Are you sure that the laptop in question actually uses AGH? That is, if you add a custom rule that disables access to, say, example.com, does the site become unavailable from that laptop?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by ainar-g** [comment]
How exactly are you setting AGH as the DNS server of AlanLaptop?  It seems like the issue is not with AGH but with how the DNS server settings are getting overridden?

**Comment by AJK301** [comment]
We use a Netgear router to assign DNS servers. I have the primary server set to 192.168.0.29 (the address of my system that runs AGH), the secondary DNS set to 1.1.1.1, and the tertiary set to 9.9.9.9. It does seem as though the router is deciding to send the traffic from my laptop to a non-primary DNS server, but all the other devices seem to process through the AGH server correctly. But it made me curious to see what my laptop says it is doing. The result:


 ***@***.***:~$ nmcli dev show | grep DNS
IP4.DNS[1]:                             192.168.0.29
IP4.DNS[2]:                             1.1.1.1
IP4.DNS[3]:                             9.9.9.9
IP6.DNS[1]:                             2001:558:feed::1
IP6.DNS[2]:                             2001:558:feed::2


So it seems as though the laptop has the settings I would expect.


Also out of curiosity, I looked through the entire log (unfortunately not very far back) for my laptop entries. It appears to be processing perfectly from the time I booted on 11/7 to about 9:45, and then the entries stopped. and have yet to start again.


Thanks for your help,
Alan

On Monday 08 November 2021 10:52:36 AM (-05:00), Ainar Garipov wrote:



How exactly are you setting AGH as the DNS server of AlanLaptop? It seems like the issue is not with AGH but with how the DNS server settings are getting overridden?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by ainar-g** [comment]
If you want a 100 % blocking, then the AGH address should be the *only* DNS address for your system.  Otherwise, the system is free to use the other servers whenever it wants.  If you set *only* AGH IP addresses, is the issue resolved?

**Comment by AJK301** [comment]
It becomes more interesting. I changed the router DNS primary, secondary, and tertiary all to be 192.168.0.29. It logged two entries for my laptop, correctly, but no further activity has been logged. As a specific test, I used my phone to go to yahoo.com, for which AGH logged three entries. I then went to yahoo.com from my laptop, and AGH logged no entries.


Then I randomly started using my phone (in airplane mode, wifi on) to go to various sites. Some were logged and most were not. For example, google.com was never logged. Even after clearing the cache.


It also seems like other devices have times when they appear to either somehow by AGH or they pass thru AGH without their requests being logged.


I'm at a loss.



2021 07:13:44 AM (-05:00), Ainar Garipov wrote:



If you want a 100 % blocking, then the AGH address should be the only DNS address for your system. Otherwise, the system is free to use the other servers whenever it wants. If you set only AGH IP addresses, is the issue resolved?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by AJK301** [comment]
And to add to my confusion, AGH logged no queries for alanlaptop from about 13:47 to 16:02, then started logging them again until 16:09, then stopped again, per the attached log.


It's haunted!


On Tuesday 09 November 2021 15:33:10 PM (-05:00), Alan Kaechele wrote:


It becomes more interesting. I changed the router DNS primary, secondary, and tertiary all to be 192.168.0.29. It logged two entries for my laptop, correctly, but no further activity has been logged. As a specific test, I used my phone to go to yahoo.com, for which AGH logged three entries. I then went to yahoo.com from my laptop, and AGH logged no entries.


Then I randomly started using my phone (in airplane mode, wifi on) to go to various sites. Some were logged and most were not. For example, google.com was never logged. Even after clearing the cache.


It also seems like other devices have times when they appear to either somehow by AGH or they pass thru AGH without their requests being logged.


I'm at a loss.



2021 07:13:44 AM (-05:00), Ainar Garipov wrote:



If you want a 100 % blocking, then the AGH address should be the only DNS address for your system. Otherwise, the system is free to use the other servers whenever it wants. If you set only AGH IP addresses, is the issue resolved?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by oHTGo** [comment]
Excuse me @ainar-g, I had a similar problem in this issue, is that after I open it on my phone, it blocks the websites that I block, the problem happens after more than a while, everything doesn't block anymore.
I made sure I have the correct DNS on the router about my Pi and also set the DHCP correctly, what should I do?

**Comment by AJK301** [comment]
I switched to a Pihole DNS server and found the same odd behavior. The client in question runs Linux Mint and it seems as though it does some management of DNS no matter how the router is configured for DNS. Beyond my grasp of DNS management, but replacing the client's /etc/resolv.conf link with a link to my own resolv.conf, wherein my DNS server is specifically identified and other alternatives eliminated, the problem is resolved. So far, the hack hasn't broken anything else and I have not tried switching back to AGH from Pihole so can't comment on that configuration.

**Comment by EugeneOne1** [comment]
@AJK301, unfortunatelly, we can't reproduce the issue.  Can you confirm that the AlanLaptop machine only uses the AGH's address as the only DNS server?  Note also that Google Chrome may select it's own DNS server, e.g. if the *Use secure DNS* setting is active.

**Comment by AJK301** [comment]
Thanks for researching and see my comments from yesterday, ie, the same problem happened when I experimented with Pihole as the DNS server. It seems that the combination of my router, my ISP, and this implementation of Linux (Ubuntu based) was circumventing the "set AGH (or Pihole) as the only DNS server in the router". After some hacking on Linux, I think I have overcome the problem. It also was happening but to a far less noticeable degree on a Pi OS machine, which also seems to be behaving better after a logically similar hack.

On Wednesday 01 December 2021 07:20:16 AM (-05:00), Eugene wrote:



@AJK301, unfortunatelly, we can't reproduce the issue. Can you confirm that the AlanLaptop machine only uses the AGH's address as the only DNS server? Note also that Google Chrome may select it's own DNS server, e.g. if the Use secure DNS setting is active.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


--
