### ISSUE TITLE
Curious why Adguard Home will access port 80 of other addresses

### ISSUE THREAD

**Issue by CallMeR** [AdguardTeam/AdGuardHome#3811]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [* ] I am running the latest version
- [*] I checked the documentation and found no answer
- [* ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.106.3
  
* **How did you install AdGuard Home:**
  *  Snapcraft

* **How did you setup DNS configuration:**
  *  Router

* **If it's a router or IoT, please write device model:**
  *  x86 computer

* **Operating system and version:**
  *  ubuntu 21.10

### Expected Behavior

Only access port 443 of the upstream DNS, because I only use DoH

### Actual Behavior

I only enable the Adguard Home service, the others are the system defaults.
But there will still be the behavior of accessing port 80 of other IP addresses. 
I checked the information of the IP address and it is not the address related to the upstream DoH I set. 
Nor is it the relevant address of my APT update source.

### Screenshots

upstream DoH :
```
https://doh.pub/dns-query
https://dns.alidns.com/dns-query
```
<details><summary>Screenshot:</summary>
<img width="496" alt="image" src="https://user-images.githubusercontent.com/11908641/140632175-a107651d-362a-41ff-9096-d6a391f4d555.png">

</details>

### Additional Information

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/11908641/140632236-e0efe1ac-9f46-479a-8be2-944a9bd2c577.png">

**Comment by rodalpho** [comment]
I assumed that was just AGH getting filter lists but that IP looks like "sogou.com", in mainland China. They're some subsidiary of Tencent making (amongst other things) browser addon adware targeting Chinese users. If you're running in a linux VM and don't browse in X, that's completely bizarre. I would run netstat or something similar to track down the process connecting there. If nothing comes up locally you may have a rootkit.

**Comment by ainar-g** [comment]
Those are most probably filter lists.  AdGuard Home will try to update the filter lists, if you have added any URL-based ones.  I don't know of any other plain HTTP URLs AdGuard Home could access.  Could it be something related to Snapcraft?

**Comment by CallMeR** [comment]
Maybe because in the DNS settings, I set the "fastest IP" option, when I set it to "load balancing", this phenomenon disappeared.

**Comment by ainar-g** [comment]
Ah, right, opening an “empty” TCP connection is the way Fastest IP “pings” the resulting IPs.  It uses port numbers 80 and 443.

**Comment by CallMeR** [comment]
problem solved :)
