### ISSUE TITLE
Didn't block elements with adGuard filters

### ISSUE THREAD

**Issue by spellozz** [AdguardTeam/AdGuardHome#3812]
Didn't block elements with adGuard filters. 
I add annoyance filter manually from github https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
But when I go to yandex.ru I have banner
![Снимок](https://user-images.githubusercontent.com/1436152/140634840-c4d3a093-0d2d-49e5-89c8-972f65a7bb38.PNG)

When I switch this filter in Adguard for Windows, its dissapear. So I think that some restrictions did't work in AdGuard Home. May be it works only with primitive banner blocking, without Java. 
Also I have the same problem with other site. Basic adguard filter didn't works properly in AdGuard home, but if I switch it in Adguard windows it works nice and banner away. 
![1](https://user-images.githubusercontent.com/1436152/140635035-3de60978-4bfc-488b-a6df-83cf456a9a10.PNG)
![2](https://user-images.githubusercontent.com/1436152/140635036-fb8620d8-3a6b-4a47-ab6f-6476a782851b.PNG)
Also they have different blocking rules. 
 
![adwinrules](https://user-images.githubusercontent.com/1436152/140635121-486d2c93-f378-479b-8840-8a1cc7a75399.PNG)
![adhomrules](https://user-images.githubusercontent.com/1436152/140635123-19e11b7f-aaaa-4a85-85a8-5b3928d2395f.PNG)

**Comment by emlimap** [comment]
AdGuard Home is a DNS based adblocker so it can only block domain name and not elements. If you want to block elements then you have to use the windows/browser based AdGuard

**Comment by ainar-g** [comment]
Like emlimap said, the content of the web pages cannot be filtered on the DNS level.  Additionally, Yandex are pretty smart with how they work around ad blockers, both DNS-level and content-level, so you'd need an extra extension to fully block these.
