### ISSUE TITLE
One of the Upstream-DNS-Server down - the whole network very slow

### ISSUE THREAD

**Issue by Jones1024** [AdguardTeam/AdGuardHome#3813]
When an Upstream-DNS-Server is down, then the all DNS request is very slow. I choose "Fastest". Why is Adguard Home trying to request all DNS Server from my list? Why can't Adguard answer my DNS request when the first DNS server responds?

KR

**Comment by Jones1024** [comment]
Suggested solution: Is it possible to create a DNS "speed" ranking-table for all my DNS providers? Maybe once a minute? For each DNS request, the top DNS entry from the speed ranking-table can then be used.

Better than querying all providers with every DNS request.

KR

**Comment by emlimap** [comment]
You might not want to set the `Fastest IP Address` option which most likely will make the slow responding upstream situation even worse as it waits for all upstream DNS servers to respond before checking which is the fastest IP address to reach the website if it receives more than one IP address. 

The default load balancing option should automatically use the fastest servers more often. Alternatively you can try `Parallel Requests` which will send the DNS query to all servers and pass the first response it gets.

The upcoming release (0.107) has an option to set upstream timeout. If you are running the beta/edge version, then you change `upstream_timeout` option in the configuration YAML file, which defaults to `10s` - 10 seconds. It is not available in the Web UI, so editing configuration file is the only option https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

**Comment by Jones1024** [comment]
![grafik](https://user-images.githubusercontent.com/10610324/140647965-008bbed4-ee33-4dd8-b770-672c504288e9.png)

I already use the Parallel Requests. Where ist the "default load balancing option"? I havn´t.

KR

**Comment by ainar-g** [comment]
The v0.107 branch already contains quite a few fixes for the upstream selection mechanism.  Could you please try installing one of the latest betas and see if that fixes the issue?  Thanks.

**Comment by Jones1024** [comment]
Sorry. No beta testing in my home network...
