### ISSUE TITLE
Error: control/stats

### ISSUE THREAD

**Issue by AdrenalineX** [AdguardTeam/AdGuardHome#382]
<img width="346" alt="screen shot 2018-10-17 at 12 12 55 pm" src="https://user-images.githubusercontent.com/24303913/47107445-910d3a00-d206-11e8-9102-e126ea79895c.png">

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

**Comment by hmage** [comment]
We've been trying to solve numerous reports of this issue, and we think we've figured out what's wrong.

Can you try this attached binary and see if it works? Let us know if it does or doesn't work.

[AdGuardHome_v0.9-10-gb299_MacOS.zip](https://github.com/AdguardTeam/AdGuardHome/files/2488732/AdGuardHome_v0.9-10-gb299_MacOS.zip)

**Comment by hmage** [comment]
P.S: You may need to visit the issue page instead of using your email client to be able to download the binary.

**Comment by AdrenalineX** [comment]
I'm getting the same error messages.

I get this message in Terminal:
listen tcp 127.0.0.1:3000: bind: address already in use

Do I need to change the port?

**Comment by AdrenalineX** [comment]
How would I know if I'm running another instance?

DeadPool:~ patriot$ lsof -ni :3000
COMMAND    PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    1732 patriot  280u  IPv4 0x4f489663c407bae5      0t0  TCP 127.0.0.1:50988->127.0.0.1:hbci (ESTABLISHED)
Google    1732 patriot  325u  IPv4 0x4f489663cbd29765      0t0  TCP 127.0.0.1:50978->127.0.0.1:hbci (ESTABLISHED)
Google    1732 patriot  334u  IPv4 0x4f489663cecc9765      0t0  TCP 127.0.0.1:50990->127.0.0.1:hbci (ESTABLISHED)
DeadPool:~ patriot$

**Comment by hmage** [comment]
> How would I know if I'm running another instance?

It'd be running in the Terminal window somewhere :)

Forgot to add `sudo` -- try `sudo lsof -ni :3000`. Thanks for helping me out troubleshoot this ^.^

**Comment by AdrenalineX** [comment]
Ok, so if I simply quit Terminal, it stops the processes?

DeadPool:~ patriot$ sudo lsof -ni :3000
Password:
COMMAND    PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
AdGuardHo 1442    root    3u  IPv4 0x4f489663db8c0465      0t0  TCP 127.0.0.1:hbci (LISTEN)
AdGuardHo 1442    root    7u  IPv4 0x4f489663d0a93765      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50101 (CLOSED)
AdGuardHo 1442    root    9u  IPv4 0x4f489663db8bf165      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50094 (CLOSED)
AdGuardHo 1442    root   10u  IPv4 0x4f489663ca5ba765      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50104 (CLOSED)
AdGuardHo 1442    root   11u  IPv4 0x4f489663ce5e2765      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50105 (CLOSED)
AdGuardHo 1442    root   12u  IPv4 0x4f489663c95ccae5      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50107 (CLOSED)
AdGuardHo 1442    root   13u  IPv4 0x4f489663d0014465      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50108 (CLOSED)
AdGuardHo 1442    root   14u  IPv4 0x4f489663cfe2eae5      0t0  TCP 127.0.0.1:hbci->127.0.0.1:51264 (ESTABLISHED)
AdGuardHo 1442    root   18u  IPv4 0x4f489663cbd28465      0t0  TCP 127.0.0.1:hbci->127.0.0.1:50990 (ESTABLISHED)
Google    1732 patriot  261u  IPv4 0x4f489663c7de5465      0t0  TCP 127.0.0.1:51264->127.0.0.1:hbci (ESTABLISHED)
Google    1732 patriot  334u  IPv4 0x4f489663cecc9765      0t0  TCP 127.0.0.1:50990->127.0.0.1:hbci (ESTABLISHED)
DeadPool:~ patriot$

**Comment by hmage** [comment]
> Ok, so if I simply quit Terminal, it stops the processes?

Yes, right now you have running instance of AdGuardHome, process ID 1442.

Try to find the Terminal window where it's running. Close it. Unzip the attached version, and then try running it again. You can't have more than one instance of AdGuardHome running at same time.

**Comment by AdrenalineX** [comment]
Hmmm, does AdGuardHome need to be in a specific folder/location? (i.e. ./AdGuardHome)?

It definiately doesn't seem to be working... I typed in the sample "porn sites" and sure enough, lots of porn!

**Comment by AdrenalineX** [comment]
DeadPool:~ patriot$ sudo /Users/deadpool/Downloads/AdGuardHome_v0-2/AdGuardHome 
Password:
2018/10/17 12:44:35 AdGuard Home web interface backend, version v0.9-10-gb299
main.renameOldConfigIfNeccessary(): File /Users/deadpool/Downloads/AdGuardHome_v0-2/AdguardDNS.yaml doesn't exist, nothing to do
main.askUsernamePasswordIfPossible(): File /Users/deadpool/Downloads/AdGuardHome_v0-2/AdGuardHome.yaml exists, won't ask for password
2018/10/17 12:44:35 Reading YAML file: /Users/deadpool/Downloads/AdGuardHome_v0-2/AdGuardHome.yaml
2018/10/17 12:44:35 Writing YAML file: /Users/deadpool/Downloads/AdGuardHome_v0-2/AdGuardHome.yaml
2018/10/17 12:44:35 Writing DNS config: /Users/deadpool/Downloads/AdGuardHome_v0-2/Corefile
2018/10/17 12:44:35 Writing filter file: /Users/deadpool/Downloads/AdGuardHome_v0-2/dnsfilter.txt
2018/10/17 12:44:35 Go to http://127.0.0.1:3000
2018/10/17 12:44:35 filterFileNames = [/Users/deadpool/Downloads/AdGuardHome_v0-2/dnsfilter.txt]
2018/10/17 12:44:35 listen tcp 127.0.0.1:3000: bind: address already in use
DeadPool:~ patriot$

**Comment by hmage** [comment]
> listen tcp 127.0.0.1:3000: bind: address already in use

You're still running another instance of AdGuardHome somewhere. You can run only one.

> I typed in the sample "porn sites" and sure enough, lots of porn!

You need to configure your computer to use your IP as DNS and then set in AdGuardHome's settings to filter adult content.

**Comment by hmage** [comment]
> Hmmm, does AdGuardHome need to be in a specific folder/location? (i.e. ./AdGuardHome)?

No, any location. `./AdGuardHome` is how you launch it from that location.

**Comment by AdrenalineX** [comment]
> You need to configure your computer to use your IP as DNS and then set in AdGuardHome's settings to filter adult content.

Hmmm, ok, I'll have to figure out how to do that....

Also, will this be able to block YouTube ads and other "In-App" ads?

**Comment by ameshkov** [comment]
Most of the in-app ads - yes.
Youtube ads - most likely no, YT uses first-party domains for loading ads metadata. Blocking them will cripple the YT app itself.

**Comment by hmage** [comment]
> Also, will this be able to block YouTube ads and other "In-App" ads?
 
Depends how the ads are implemented. Youtube, for example, as per #367 sometimes delivers ads on a first-party domain name.

Some in-app ads might do the same.

**Comment by AdrenalineX** [comment]
Got it. Thanks!

**Comment by AdrenalineX** [comment]
I'm not seeing in Settings where to:

> You need to configure your computer to use your IP as DNS and then set in AdGuardHome's settings to filter adult content.

**Comment by hmage** [comment]
On Mac that's done in your system preferences. More detailed guide is here -- https://github.com/AdguardTeam/AdGuardHome/wiki#how-do-i-set-up-my-devices-to-use-my-adguard-home

**Comment by AdrenalineX** [comment]
Step 3. Enter your AdGuard Home server addresses there.

Is that going to be: http://localhost:3000

**Comment by AdrenalineX** [comment]
Thanks! And what settings would I set on my Apple Airport Extreme?

**Comment by hmage** [comment]
As long as your mac is running 24/7 and never sleeps, tell Airport Extreme to use your mac's IP address as DNS server.

**Comment by ibksturm** [comment]
i wrote on debian a systemd job as a work around 


`  GNU nano 2.7.4                                  File: /etc/systemd/system/adguard.service                                             

[Unit]
Description=AdGuardHome DNS
#ConditionFileIsExecutable=/etc/AdGuardHome/AduGuardHome

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/etc/AdGuardHome/AdGuardHome -c AdGuardHome.yaml

WorkingDirectory=/etc/AdGuardHome

#User=root
#Group=root

#Restart=always
#RestartSec=120
#EnvironmentFile=-/etc/sysconfig/dnscrypt-proxy

[Install]
WantedBy=multi-user.target



`

**Comment by ibksturm** [comment]
@AdrenalineX i made a new thread

**Comment by hmage** [comment]
@AdrenalineX are you still seeing this problem?

<img width="346" alt="screen shot 2018-10-17 at 12 12 55 pm" src="https://user-images.githubusercontent.com/24303913/47107445-910d3a00-d206-11e8-9102-e126ea79895c.png">

**Comment by ewrogers** [comment]
Not OP, but trying to build a Docker container this and I get the same issue.

I'm running Docker 18.06.01 on macOS 10.14 "Mojave", using an Alpine base image.
The execution is via `CMD ./AdGuardHome --host 0.0.0.0 --port 3000` to start the container. Sure enough I can navigate in Safari to "http://localhost:3000" and see these exact errors.
