### ISSUE TITLE
DHCP Page Not Loading on Debian Bullseye

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#3824]
Running latest AGH Edge build on Raspberry Pi 2 that I just upgraded from Buster to Bullseye. AGH DHCP page just stopped loading, regardless of browser. There are no errors in AdGuard Home logs...

**Comment by EntropySmoke** [comment]
I uninstalled and re-installed AdGuard Home and found out the cause of this issue - "Reset Settings" button on DHCP page makes the whole page blank permanently until AdGuard Home service is stopped, and AdGuardHome.yaml is replaced with a backed up one.

Does AdGuard Home use ICMP for anything? The only settings I apply via AdGuardHome.yaml:
 - Enabling Strict SNI
 - Settings ICMP Timeout to 0 (which is supposed to disable it)

**Comment by ainar-g** [comment]
Thanks for the report.  Can you see if there are any errors in the browser console?  It probably has something to do with the UI and recent changes in data validation.

**Comment by EntropySmoke** [comment]
There are no pop-up errors in lower-right corner of the screen and no error messages in "/var/log/AdGuardHome.err" if that's what you're asking. After pressing "Reset Settings", the page becomes plain white.

**Comment by ainar-g** [comment]
I mean your browser's console.  In Firefox, it's usually either <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>.

@Chinaski1, please try and reproduce this when you have the time.

**Comment by Feedayi** [comment]
i have the same issue, and got this error:
sorry its long

TypeError: a is undefined
    p http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    H http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    L http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    L http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    validateIfNeeded http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    componentDidMount http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    os http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    pl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    _l http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Js http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Wn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    el http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    notify http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    notifyNestedSubs http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    handleChangeWrapper http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    g http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    r http://192.168.2.99/main.75b7efbb5179fbde746a.js:11
    dispatch http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    e http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    l http://192.168.2.99/main.75b7efbb5179fbde746a.js:43
    _invoke http://192.168.2.99/main.75b7efbb5179fbde746a.js:43
    t http://192.168.2.99/main.75b7efbb5179fbde746a.js:43
    a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    s http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    promise callback*a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    s http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    promise callback*a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    s http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    exports http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    exports http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    Ae http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    r http://192.168.2.99/main.75b7efbb5179fbde746a.js:11
    C http://192.168.2.99/main.75b7efbb5179fbde746a.js:80
    ns http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    gl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    fl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Js http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Wn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    M http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Qt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Yt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Vt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    mt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    sa http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Zi http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    dl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    cl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    sl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Js http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Ys http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    zl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    ql http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    tl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    ql http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    render http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:80
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:80
    a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
main.75b7efbb5179fbde746a.js:27:82385
TypeError: a is undefined
    p http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    H http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    L http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    L http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    validateIfNeeded http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    componentDidMount http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    os http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    pl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    _l http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Js http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Wn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    el http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    notify http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    notifyNestedSubs http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    handleChangeWrapper http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    g http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    r http://192.168.2.99/main.75b7efbb5179fbde746a.js:11
    dispatch http://192.168.2.99/main.75b7efbb5179fbde746a.js:6
    e http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    l http://192.168.2.99/main.75b7efbb5179fbde746a.js:43
    _invoke http://192.168.2.99/main.75b7efbb5179fbde746a.js:43
    t http://192.168.2.99/main.75b7efbb5179fbde746a.js:43
    a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    s http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    promise callback*a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    s http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    promise callback*a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    s http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    exports http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    exports http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    Ae http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    r http://192.168.2.99/main.75b7efbb5179fbde746a.js:11
    C http://192.168.2.99/main.75b7efbb5179fbde746a.js:80
    ns http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    gl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    fl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Js http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    unstable_runWithPriority http://192.168.2.99/main.75b7efbb5179fbde746a.js:35
    qn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Kn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Wn http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    M http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Qt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Yt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Vt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    mt http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    sa http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Zi http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    dl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    cl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    sl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Js http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    Ys http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    zl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    ql http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    tl http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    ql http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    render http://192.168.2.99/main.75b7efbb5179fbde746a.js:27
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:80
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:80
    a http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:1
    <anonymous> http://192.168.2.99/main.75b7efbb5179fbde746a.js:1

**Comment by EugeneOne1** [comment]
@EntropySmoke, we've accidentially closed the issue within the commit but also pushed the latest edge build.  Could you please install it and check, if the resetting button on the DHCP settings page now works properly?
