### ISSUE TITLE
@@ rules won't unblock domains blocked by a hosts file

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#383]
Another reason for moving everything to the dnsfilter module

**Comment by ameshkov** [comment]
Fixed in https://github.com/AdguardTeam/AdGuardHome/pull/443

**Comment by puja108** [comment]
Any ETA on next release (I guess 0.91) that would contain this? Or maybe plans to do another release in between? I see there's still 9 open issues in the milestone for 0.91.

**Comment by ameshkov** [comment]
@puja108 if we're not able to implement everything we've planned in two weeks, we will publish an intermediate release. The necessary minimum is #423 and #450

**Comment by puja108** [comment]
Thanks @ameshkov you're doing great work!
