### ISSUE TITLE
Windows 11 Custom DoH Entry not working

### ISSUE THREAD

**Issue by webmihir** [AdguardTeam/AdGuardHome#3833]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.0-b.14
* **How did you install AdGuard Home:**
  * Install script
* **How did you setup DNS configuration:**
  * DHCP, DNS
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4

Windows 11 allows addition of custom DoH addresses. For privacy I am not including my actual domain name (replaced with example.com). My AGH DNS Server runs on 192.168.86.10. I added the custom DoH address using Powershell as follows:

```
Add-DnsClientDohServerAddress -ServerAddress '192.168.86.10' -DohTemplate 'https://dns.example.com/dns-query/my-laptop' -AllowFallbackToUdp $False -AutoUpgrade $True
```

I confirmed using `Get-DnsClientDohServerAddress` cmdlet that this was successfully added. I can also confirm that I have independently verified that the address listed in the DohTemplate works (I changed my Google Chrome setting to use that DoH address and can see my browsing URLs get resolved in AGH query logs).

I then set my WiFi network adapter settings to use encrypted DoH using the instructions here: https://www.bleepingcomputer.com/news/microsoft/windows-11-includes-the-dns-over-https-privacy-feature-how-to-use/ 

Finally, I reconnected to the DHCP by using `ipconfig /renew` command from command-line.

### Expected Behavior
Windows connects to the DNS server using DoH

### Actual Behavior
Windows is unable to resolve any DNS queries unless the encryption setting in network adapter is removed (i.e. use regular plain text DNS instead of DoH)

### Other Information
I added my NextDNS config using the same process and was able to successfully have Windows 11 connect and use their DoH. (I replaced my actual NextDNS account config ID with xxxxxx below, and the IP address with xx as well to protect my account details).
```
Add-DnsClientDohServerAddress -ServerAddress '45.90.28.xx' -DohTemplate 'https://dns.nextdns.io/xxxxxx/my-laptop' -AllowFallbackToUdp $False -AutoUpgrade $True
```
I validated by opening command-prompt, running `nslookup bing.com` and in my query-log of NextDNS account I see a DoH request made for bing.com.

**Comment by ainar-g** [comment]
Hello and thank you for the thorough report.  A couple of questions:

1.  Is the certificate for `dns.example.com` recognised as your system as valid?

2.  Can you perform DoH requests from the machine using the [`dnslookup`][1] utility?  E.g.:

    ```ps
    .\dnslookup example.org https://dns.example.com/dns-query/my-laptop
    ```

3.  Can you enable [verbose logging][2] on your AGH and see if it gets any requests from that machine?

Thanks.

[1]: https://github.com/ameshkov/dnslookup
[2]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by vNa3006** [comment]
You should remove /my-laptop and try again

**Comment by dragoangel** [comment]
@ainar-g actually Windows 11 really can't use DoH from Adguard home while mentioned console utility - works.
