### ISSUE TITLE
Charts are off zero

### ISSUE THREAD

**Issue by richardwonka** [AdguardTeam/AdGuardHome#3834]
Version:  v0.106.3 on current homeassistant (managed)

![4204AEEF-FE99-40C1-98AE-597B93DFBB6C](https://user-images.githubusercontent.com/304005/141257694-3640bfe5-073d-4a86-9244-caa4eaf1b4a6.png)

**Comment by ainar-g** [comment]
Hello.  There were similar issues during the v0.106 cycle, but we couldn't reproduce them, see #2942.  Is there a way for you to install a beta release of AGH v0.107 and see if it's fixed there?

**Comment by richardwonka** [comment]
I could reproduce earlier, but now it’s all good again…

I’d prefer not to do beta testing this time. 

Richard Wonka 

—
Throw off the bow lines! Dream! Discover!

**Comment by ainar-g** [comment]
I see.  Perhaps it has something to do with rare data shapes of the graphs that only appear every once in a while.  I'll leave the issue open for a few days; please feel free to check back if this happens again.

**Comment by richardwonka** [comment]
Thank you for the quick response. 🙂

Richard Wonka 

—
Throw off the bow lines! Dream! Discover!

**Comment by TheCeet** [comment]
Since 0.107, I’m having this issue too. Only noticed on iPhone safari browser. 
![3CC24F70-98B6-41D4-B83A-486CB3279DE3](https://user-images.githubusercontent.com/82833275/147873850-704598b8-7693-4a90-9e34-4c62d5d491d1.png)

**Comment by TheCeet** [comment]
Issue is still happening, desktop view & mobile browser.

**Comment by Iam-lcl** [comment]
It appears that if the svg path for the chart begins with `M0,32` then there is a CSS that moves the chart down, probably as this would be the zero-line?
```
.card-chart-bg path[d^="M0,32"] {
    transform: translateY(32px);
}
```

Changing the first coordinate to anything else than `M0,32` ex. `M0,31` then the chart will get displayed correctly.
```
<path d="M0,32L3,41L6,43L9,41L12,41L15,43L18,26L22,26L25,23L28,42L31,45L34,46L37,47L40,21L43,12L46,17L49,26L52,46L55,31L58,33L62,24L65,0L68,29L71,27L74,42L77,30L80,39L83,37L86,25L89,44L92,40L95,41L99,43L102,44L105,29L108,35L111,40L114,40L117,39L120,39L123,42L126,40L129,32L132,41L135,27L139,48L142,36L145,36L148,33L151,27L154,35L157,35L160,43L163,35L166,41L169,35L172,24L175,41L179,36L182,26L185,30L188,29L191,28L194,22L197,39L200,39L203,42L206,37L209,46L212,26L216,20L219,42L222,41L225,43L228,40L231,47L234,35L237,35L240,47L243,46L246,48L249,45L252,46L256,37L259,34L262,50L265,50L268,49L271,47L274,58" fill="none" stroke-width="2" stroke="#cd201f"></path>
```

Chart that is all zero
```
<path d="M0,32L3,32L6,32L9,32L12,32L15,32L18,32L22,32L25,32L28,32L31,32L34,32L37,32L40,32L43,32L46,32L49,32L52,32L55,32L58,32L62,32L65,32L68,32L71,32L74,32L77,32L80,32L83,32L86,32L89,32L92,32L95,32L99,32L102,32L105,32L108,32L111,32L114,32L117,32L120,32L123,32L126,32L129,32L132,32L135,32L139,32L142,32L145,32L148,32L151,32L154,32L157,32L160,32L163,32L166,32L169,32L172,32L175,32L179,32L182,32L185,32L188,32L191,32L194,32L197,32L200,32L203,32L206,32L209,32L212,32L216,32L219,32L222,32L225,32L228,32L231,32L234,32L237,32L240,32L243,32L246,32L249,32L252,32L256,32L259,32L262,32L265,32L268,32L271,32L274,32" fill="none" stroke-width="2" stroke="#5eba00"></path>
```

**Comment by TheCeet** [comment]
@ainar-g Did you see the comment from @Iam-lcl above?
Possible fix
