### ISSUE TITLE
Customized filtering by client is not working

### ISSUE THREAD

**Issue by Gandulf78** [AdguardTeam/AdGuardHome#3836]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Issue Details

The customization per client does not seem to work. 
I tried to remove all the filters for one of the clients but the queries were still blocked.  

* **Version of AdGuard Home server:**
 V0.106.3
* **How did you install AdGuard:**
Docker
* **How did you setup DNS configuration:**
 IoT
* **If it's a router or IoT, please write device model:**
 WDMycloudEX2Ultra
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior
It is possible to customize the filtering depending on the DNS client. 

### Actual Behavior
The global filtering is always applied. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@Gandulf78, hello and thanks for the report!  Could you please provide the following info:

 1. How exactly did you set custom filters for the client?
 1. What are these filters?

Also, could you please try one of the latest edge/beta builds and check if the issue reproduces there?

**Comment by Gandulf78** [comment]
Hi!   
  
I tried to reproduce yesterday and it is working fine actually.   
  
I believe that for some reasons the AGH server was not considering the actual IP address of the client but   considered the   generic router address (I do not use the AGH DHCP) so my client particular settings was not applied.   
  
  
  
    
  

  
  
>

**Comment by EugeneOne1** [comment]
@Gandulf78, well, I'll close the issue for now if you don't mind.
