### ISSUE TITLE
PTR blocking - broken completely

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdGuardHome#3842]
Running the latest version of AGH I'm not able to block PTR queries for public addresses. AGH is DNS-only, not DHCP server. I clearly remember ||*.in-addr.arpa^$important rule black-holing PTR queries, but now it doesn't do that at all now.

**Comment by EntropySmoke** [comment]
||*^$client=127.0.0.1 is supposed to prevent localhost from resolving domains, but that rule does not apply to localhost resolving PTR domains. **All** PTR's go through...

**Comment by EugeneOne1** [comment]
@EntropySmoke, hello and thank you for the report.  Indeed the logic has been broken during the `v0.107.0` cycle.  However, the newest edge build should fix the problem, so could you please install it and check if the filtering is OK there?

**Comment by EntropySmoke** [comment]
The latest edge version resolved the issue for me. Thank you for such a quick turn-around!

**Comment by EugeneOne1** [comment]
@EntropySmoke, thanks for testing!  We'll close the issue for now.
