### ISSUE TITLE
Awarding the best AdGuard contributors in 2021

### ISSUE THREAD

**Issue by el-termikael** [AdguardTeam/AdGuardHome#3844]
Hello, @Aikatsui! 

My name is Helen, I'm a content manager at AdGuard. Currently we’re preparing a blog post about the most active community contributors of the year, and you undoubtedly deserve a spot there. Congratulations and big thanks for your help!

Please contact me at e.ter-mikaelyan@adguard.com to discuss the best way to send you our special gift bag and other details.

**Comment by ainar-g** [comment]
@Aikatsui, apologies for the GitHub notification abuse, but this seemed like the best way to reach out, heh.

Closing this issue, since it's basically a one-time announcement.  Perhaps, we should try to do this on the discussions pages next year, if we confirm that notifications there work the same way.

**Comment by Aikatsui** [comment]
Hi Helen @el-termikael,

I couldn't respond to last year notification too. Thank you and adguard team for the gift however i dont expect it and i will continue to help for development and localization at my free times. 🎁✌️

Have a pleasant day! 🎉

It's nice to see that new product has appeared already; it will be helpful for many parties e.g. especially for families, small teams that difficult to maintain 24/365 dedicate adguardhome environment also easy to set-up and connect devices from different networks and locations.

Happy holidays and best wishes for the new year! 🌷

**Comment by el-termikael** [comment]
Hi!
Are you sure about the presents? We can send them to you, if you want.

Hopefully, you'll like the new product 😊

Merry Christmas and happy holidays to you too! 🎄
