### ISSUE TITLE
AdGuard Home in OpenWRT won't start if /tmp/hosts doesn't exist

### ISSUE THREAD

**Issue by cjom** [AdguardTeam/AdGuardHome#3845]
### Issue Details

AdGuard Home
Version: v0.107.0-a.206+9c8e0875
Channel: edge
Go version: go1.16.9
Build time: 2021-11-15T14:52:07Z+0000
GOOS: linux
GOARCH: arm64
Race: false

* **How did you install AdGuard Home:**
  Using the curl command from github page.
* **How did you setup DNS configuration:**
  Router
* **If it's a router or IoT, please write device model:**
  Xiaomi AX3600 running OpenWRT
* **CPU architecture:**
  arm64
* **Operating system and version:**
  OpenWrt SNAPSHOT r17529-02d2f1e065
  Kernel 5.10.61

### Expected Behavior
AdGuard Home DNS server automatically start at boot

### Actual Behavior
Running AdGuardHome from SSH console I can see it crashes because /tmp/hosts does not exist.

root@AX3600_OpenWrt:/opt/AdGuardHome# ./AdGuardHome
2021/11/15 21:03:40.090142 [info] AdGuard Home, version v0.107.0-a.204+884a9850
2021/11/15 21:03:40.103181 [info] dhcp: loaded leases v4:19  v6:0  total-read:19 from DB
2021/11/15 21:03:40.104504 [fatal] initing hosts container: hosts container: "tmp/hosts" at index 1: open /tmp/hosts: no such file or directory

### Additional Information
If a zero size file is created with the command "touch  /tmp/hosts" then AdGuardHome runs as expected.

**Comment by spot320** [comment]
try to install according to this instruction https://4pda.to/forum/index.php?showtopic=911457&view=findpost&p=97541945

**Comment by EugeneOne1** [comment]
@cjom, hello and thanks for the report.  We've just pushed the newest build to the edge channel.  It should fix the issue, so could you please install it and check if the problem persists?  Thanks.

**Comment by cjom** [comment]
Thank you, @EugeneOne1 it's fixed!
/tmp/hosts does not exist after rebooting the router and still Adguard Home is up and running as expected!

**Comment by EugeneOne1** [comment]
@cjom, thanks for testing!  It should now just log the warning.
