### ISSUE TITLE
Make hosts' rewrites appear consistently in query log

### ISSUE THREAD

**Issue by EugeneOne1** [AdguardTeam/AdGuardHome#3846]
Currently, `$dnsrewrite` rules generated from the operating system's hosts file are applied but omitted in query log's results:

| Hosts' `$dnsrewrite` | Other `$dnsrewrite` rules |
|----------------------|---------------------------|
| <img width="343" alt="image" src="https://user-images.githubusercontent.com/38542664/141978149-42097bc6-8b09-4c57-bbea-96e185bee508.png"> | <img width="611" alt="image" src="https://user-images.githubusercontent.com/38542664/141979950-a736ee80-8424-4f88-bdb3-1085f2f54e8b.png"> |

This is a bit confusing relative to the other more complete `$dnsrewrite`s.

Steps to implement:

 1. Such rules should be written in form it has been read from the actual file, e.g. `127.0.0.1 localhost`;
 
 1. Decoding from older query log files should consider translating such entries.
 
 1. Frontend should support the new ID value for the rules list which is currently `-1` to mark such rewrites more precisely.

**Comment by Chinaski1** [comment]
Requests blocked by `Block Services` function are also marked as `custom filtering rules`
@IldarKamalov

**Comment by Chinaski1** [comment]
![image](https://user-images.githubusercontent.com/49645813/143032529-c53174a4-630c-4a5b-a469-ae8527691645.png)

**Comment by Chinaski1** [comment]
![image](https://user-images.githubusercontent.com/49645813/143032702-bb537e26-4f8b-4bd1-b98e-983419715ab4.png)
