### ISSUE TITLE
Setup Wizard stuck on step 2

### ISSUE THREAD

**Issue by double-ee** [AdguardTeam/AdGuardHome#3849]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Issue Details

AdGuard Home
Version: v0.106.3
Channel: release
Go version: go1.15.11
Build time: 2021-05-19T13:25:36Z+0000
GOOS: linux
GOARCH: arm
GOARM: v6
Race: false
Main module:
        github.com/AdguardTeam/AdGuardHome (devel)

* **How did you install AdGuard Home:**
 Using the instruction found at https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi
* **How did you setup DNS configuration:**
 Haven't reached that step
* **If it's a router or IoT, please write device model:**
  Raspberry Pi 3 Model B Plus Rev 1.3
* **CPU architecture:**
  ARMv7 Processor rev 4 (v7l)
* **Operating system and version:**
  PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

### Expected Behavior
I clicked on the "Next" button on step 2 of the setup wizard.  I expected the wizard to proceed to step 3.

### Actual Behavior
Nothing happened.  I can go back to step 1 with the "Back" button, but clicking the "Next" button yields no results.

### Additional Information
Any "AdGuardHome" commands return this response: -bash: AdGuardHome: command not found

**Comment by EugeneOne1** [comment]
@double-ee, hello and thanks for the report!  Could you please install one of the latest edge or beta builds and see if this behavior reproduces there?

You can install it in the same way as the instruction tells, but replacing the `release` part of the URL with `beta` or `edge`.  Thus the final command would be something like:

```sh
wget 'https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv6.tar.gz'
```
