### ISSUE TITLE
Feature request, multiple IP addresses for listening

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#385]
hi there
small idear, maybe you could hack it that in the .yaml file with the port for coredns we also could give one or two or more ipv4 / ipv6 adresses

**Comment by hmage** [comment]
Great idea, thanks!

No promises when and how, though, but most likely will add yaml `bind` in `coredns` section and will generated Corefile accordingly.

**Comment by happyhater** [comment]
type coreDNSConfig struct {
..
        Bind                string          `yaml:"bind"`
..


CoreDNS: coreDNSConfig{
...
Bind:                "1.2.3.4",
..


const coreDNSConfigTemplate = `:{{.Port}} {
...
bind {{.Bind}}
...


:)

**Comment by mHatsune** [comment]
#1708

**Comment by PauloHeaven** [comment]
I'm annoyed by this problem too. I have multiple IP addresses on my server and web servers listen on several of them.

I would also like to be able to chose separate addresses for the web interface, DoH, DoT and plaintext DNS. I think many of us have a complex configuration that could use a bit more flexibility...

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
