### ISSUE TITLE
Version for AsusWRT Merlin routers?

### ISSUE THREAD

**Issue by gspannu** [AdguardTeam/AdGuardHome#3850]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Any plans for **releasing a version** that can be installed on **Asus WRT Merlin routers**? 

### Proposed Solution

Asus Merlin routers are great for development purposes.

https://www.asuswrt-merlin.net/
https://diversion.ch/amtm.html

There is a massive consumer base, but currently the ad-blocking feature set is limited to Diversion (diversion.ch).
Few people have ported Pi-Hole across to Asus WRT Merlin, but other than that, there is no other solution.
_It would be a great opportunity to have AdGuard Home available on the platform as well._

### Alternatives Considered

Pi-Hole is an alternative and available (in dev form) for Asus WRT Merlin routers

**Comment by ainar-g** [comment]
I don't quite get your request, sorry.  If it's a Linux-based OS, then AdGuard Home should already be supported by it.  Can you elaborate, which issues you're encountering?

**Comment by lbtboy** [comment]
AdGuardHome v0.106.3   ###https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_arm64.tar.gz installed on two RT-AX88U and GT-AC 2900 routers with AsusWRT Merlin 386.3_2 firmware, everything works fine.

![Снимок экрана 2021-11-19 15:20:05](https://user-images.githubusercontent.com/57795912/142608135-67d24aff-c7e8-4ea7-a4b7-d719d24b8605.png)
![Снимок экрана 2021-11-19 15:21:22](https://user-images.githubusercontent.com/57795912/142608142-f5e6d01b-3848-4e2e-a60a-50b88ec98db6.png)

**Comment by gspannu** [comment]
> AdGuardHome v0.106.3 https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_arm64.tar.gz installed on two RT-AX88U and GT-AC2900 routers with AsusWRT Merlin 386.3_2 firmware, everything works fine.

Thanks…

1) Can you please post some instructions as to how you installed AdGuard Home?
2) It it required to install Entware first?
3) Or do I just download and extract the AdGuardHome_linux_arm64.tar.gz? To which folder should I extract the AdGuard files? Somewhere on the attached USB drive (I would guess)
4) Any other dependant packages that need to be installed first?

**Would you mind posting some detailed instructions please…** 
Thanks.

**Comment by lbtboy** [comment]
1. Entware required for installation.
2. Just download and extract AdGuardHome_linux_arm64.tar.gz to any directory on usb (whichever is convenient for you).
3. In `/opt/etc/init.d/ `create an autorun script `S99adguardhome` with the contents:

#!/bin/sh

ENABLED=yes
PROCS=AdGuardHome
ARGS="$OPTIONS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:`the path of your where is unpacked AdGuardHome`
. /opt/etc/init.d/rc.func

5. Set the rights to `chmod 755 /opt/etc/init.d/S99adguardhome/`
6. Run AdGuardHome `/opt/etc/init.d/S99adguardhome start`
7. Enjoy using

**Comment by EugeneOne1** [comment]
@gspannu, I'll close the issue for now.  Feel free to reopen it with a feedback on issues during the process if those occured.

**Comment by gspannu** [comment]
> 1. Entware required for installation.
> 2. Just download and extract AdGuardHome_linux_arm64.tar.gz to any directory on usb (whichever is convenient for you).
> 3. In `/opt/etc/init.d/ `create an autorun script `S99adguardhome` with the contents:
> 
> #!/bin/sh
> 
> ENABLED=yes PROCS=AdGuardHome ARGS="$OPTIONS" PREARGS="" DESC=$PROCS PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:`the path of your where is unpacked AdGuardHome` . /opt/etc/init.d/rc.func
> 
> 4. Set the rights to `chmod 755 /opt/etc/init.d/S99adguardhome`
> 5. Run AdGuardHome `/opt/etc/init.d/S99adguardhome start`
> 6. Enjoy using
> 
> * Any other dependant packages that need to be installed first?
>   If only `nano` for editing and `mс` for viewing files

Hi @lbtboy 

I was able to install AdGuard without any issues. However, I am not able to configure it using the AdGuard Home page.
My Router address is 192.168.1.1
After starting AdGuard, I navigate to 192.168.1.1:3000 and it opens the web page (Setup Wizard).
- Web Interface page can be set to 192.168.1.1, port 33333
- DNS listener interface: 
 I cannot set it to 192.168.1.1 (as it states that 192.168.1.1 _bind: address already in use_)
 Neither can I set to All Interfaces (same error)

**How do I resolve this remaining issue, please?**

Thanks...

**Comment by gspannu** [comment]
> @gspannu, I'll close the issue for now. Feel free to reopen it with a feedback on issues during the process if those occured.

@EugeneOne1 
Can you **please re open this issue** - as there is an issue in configuration post installation. Hopefully, @lbtboy will bed able to assist in the solution.

**Comment by lbtboy** [comment]
- Web Interface page can be set to 192.168.1.1, port 33333

**Choose the port of the web interface that is not busy, I have 3000 by default, everything works.**

- DNS listener interface:
I cannot set it to 192.168.1.1 (as it states that 192.168.1.1 bind: address already in use)
Neither can I set to All Interfaces (same error)

**Install the same port that you need other than 53. In the file `firewall-start` in` /jffs/scripts` prescribe:**
 
**iptables-t nat -I PREROUTING policy -i br0 -p udp -m udp --dport 53-j REDIRECT --to-port** `your port`
**iptables-t nat -I PREROUTING policy -i br0 -p tcp -m tcp --dport 53-j REDIRECT --to-port** `your port`

**Comment by gspannu** [comment]
> * Web Interface page can be set to 192.168.1.1, port 33333
> 
> **Choose the port of the web interface that is not busy, I have 3000 by default, everything works.**
> 
> * DNS listener interface:
>   I cannot set it to 192.168.1.1 (as it states that 192.168.1.1 bind: address already in use)
>   Neither can I set to All Interfaces (same error)
> 
> **Install the same port that you need other than 53. In the file** `firewall-start` **in**` /jffs/scripts` **prescribe:**
> 
> **iptables-t nat -I PREROUTING policy -i br0 -p udp -m udp --dport 53-j REDIRECT --to-port** `your port` **iptables-t nat -I PREROUTING policy -i br0 -p tcp -m tcp --dport 53-j REDIRECT --to-port** `your port`

Hi, Thanks...

- Was able to successfully complete configuration...  I used port 192.168.1.1 and Port 53535
- Created the /jffs/scripts/firewall-start file (as it did not exist) and copied the entries you mentioned with port 53535
- made sure the firewall-start file is executable (chmod 755)
- restarted router.
- Can access the AdGuard web interface at 191.168.1.1:30000 as well.

However, **no queries are being processed by AdGuard**.

**What other setings on the router will I need to change?**

My current DNS page looks like the attached screenshot and my DNS Filter  is set to Router (as I want all queries to go via the  Router).

See attached screenshots...

<img width="976" alt="DHCP" src="https://user-images.githubusercontent.com/137664/142772496-e3eb55b6-964f-4104-85ea-4a8501c0e2a3.png">
<img width="973" alt="DNSFilter" src="https://user-images.githubusercontent.com/137664/142772499-a890a383-c03e-4191-85ae-ae6e8e0754b7.png">

**_As some added information:_**
```
ssh into router
nslookup google.com
The router resolves, but no entries in AdGuard Query log. Meaning DNS was not resolved by AdGuard

I then tried nslookup google.com 192.168.1.1
The router resolves, but no entries in AdGuard Query log. Meaning DNS was not resolved by AdGuard

I then tried nslookup google.com 192.168.1.1:53
The router resolves, but no entries in AdGuard Query log. Meaning DNS was not resolved by AdGuard

I then tried nslookup google.com 192.168.1.1:53535
Now I see the entry in AdGuard Query log !
```

**So AdGuard Home seems to be working and resolving, just _not acting as the default DNS Resolver_.**

**Comment by gspannu** [comment]
My **/tmp/mnt/USB-ASUS/AdGuardHome/AdGuardHome.yaml** file for reference...
```
bind_host: 192.168.1.1
bind_port: 30000
beta_bind_port: 0
users:
- name: ???????????????
  password: ?????????????????
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
  - 192.168.1.1
  port: 53535
  statistics_interval: 90
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 6h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - https://dns10.quad9.net/dns-query
```

My **/jffs/scripts/ firewall-start** file for reference
```
iptables-t nat -I PREROUTING policy -i br0 -p udp -m udp --dport 53-j REDIRECT --to-port 53535
iptables-t nat -I PREROUTING policy -i br0 -p tcp -m tcp --dport 53-j REDIRECT --to-port 53535
```

My **/opt/etc/init.d/S99adguardhome** file for reference..
```
#!/bin/sh

ENABLED=yes
PROCS=AdGuardHome
ARGS="$OPTIONS"
PREARGS=""
DESC=$PROCS
PATH=$PATH:/tmp/mnt/USB-ASUS/AdGuardHome
. /opt/etc/init.d/rc.func

```

**Comment by lbtboy** [comment]
`query log_size_memory: 1000` set the value to 0 so that requests are recorded immediately, there will be no records until 1000 requests are processed.

- `querylog_size_memory` - Number of entries kept in memory before they are flushed to disk.

- https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration
- 
![Screenshot_00001 - LAN - DHCP Server - Enhanced by YazDHCP - 192 168 1 1 - 21 11 2021_22_54_34](https://user-images.githubusercontent.com/57795912/142773394-8592d306-f7c1-455b-84d4-940ed905e6ce.jpg)
![Screenshot_00002 - ASUS Wireless Router RT-AX88U - DNS-based Filtering - 192 168 1 1 - 21 11 2021_22_54_59](https://user-images.githubusercontent.com/57795912/142773396-ec430104-cb73-43c6-8ac4-706bf9ee80c7.jpg)

**Comment by gspannu** [comment]
> `query log_size_memory: 1000` set the value to 0 so that requests are recorded immediately, there will be no records until 1000 requests are processed.
> 
> * `querylog_size_memory` - Number of entries kept in memory before they are flushed to disk.
> * https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration

### Managed to figure it out...

**The issue was in the iptables command.**

I had to change 
**iptables-t** nat -I PREROUTING **policy** -i br0 -p udp -m udp --dport **53-j** REDIRECT --to-port your port

to 
iptables **-t** nat -I PREROUTING -i br0 -p udp -m udp --dport 53 **-j** REDIRECT --to-port your port

I understand the query log parameter; but I was doing a manual refresh.... so the value in the yaml file was not playing a role.
IOt was an incorrect command in iptables...

**Comment by lbtboy** [comment]
**I'm sorry, I don't know why it turned out that way for me, and it's written that way:**

iptables -t nat -I PREROUTING -i br0 -p udp -m udp --dport 53 -j REDIRECT --to-port 16553
iptables -t nat -I PREROUTING -i br0 -p tcp -m tcp --dport 53 -j REDIRECT --to-port 16553

**Comment by gspannu** [comment]
> > I think.... Managed to figure it out...
> > The issue was in the iptables command.
> > I had to change
> > iptables-t nat -I PREROUTING policy -i br0 -p udp -m udp --dport 53-j REDIRECT --to-port your port
> > to
> > iptables -t nat -I PREROUTING -i br0 -p udp -m udp --dport 53 -j REDIRECT --to-port your port
> > I understand the query log parameter; but I was doing a manual refresh.... so the value in the yaml file was not playing a role.
> > It was an incorrect command in iptables...
> 
> **I'm sorry, I don't know why inattention happened, that's exactly what I have prescribed:**
> 
> iptables -t nat -I PREROUTING -i br0 -p udp -m udp --dport 53 -j REDIRECT --to-port 16553 iptables -t nat -I PREROUTING -i br0 -p tcp -m tcp --dport 53 -j REDIRECT --to-port 16553

👍 
All working... many thanks for your help...

**Comment by gspannu** [comment]
All working properly....

I have published guide [here](https://www.snbforums.com/threads/adguard-home-adblocker-clean-install-on-asus-merlin-no-3rd-party-scripts.75818/post-725187) if anyone interested.

Many thanks @lbtboy

**Comment by lbtboy** [comment]
> All working properly....
> 
> I have published guide here if anyone interested.
> 
> Many thanks @lbtboy

I then tried changing the WAN DNS1 server to 127.0.1.1 and WAN DNS2 to 127.0.0.1. But the edits in the Web GUI prevents the use of the router loopback address 127.0.0.1. I worked around the issue by using setting WAN DNS1 to 127.0.1.1 and WAN DNS2 to 127.0.0.1 by using the nvram set and commit commands:

DNS1=127.0.1.1
nvram set wan0_dns="$DNS1"
nvram set wan_dns="$DNS1"
nvram set wan_dns1_x="$DNS1"
nvram set wan0_xdns="$DNS1"
nvram set wan0_dns1_x="$DNS1"
nvram set wan_dns2_x="$DNS2"
nvram set wan0_dns2_x="$DNS2"

DNS2=127.0.0.1
nvram set wan1_dns="$DNS1"
nvram set wan_dns="$DNS1"
nvram set wan_dns1_x="$DNS1"
nvram set wan1_xdns="$DNS1"
nvram set wan1_dns1_x="$DNS1"
nvram set wan_dns2_x="$DNS2"
nvram set wan1_dns2_x="$DNS2"

nvram commit
service restart_dnsmasq

![Screenshot_00007 - ASUS Wireless Router RT-AX88U - Internet Connection - 192 168 1 1 - 23 11 2021_18_10_12](https://user-images.githubusercontent.com/57795912/143029940-6ddfca43-d436-4525-a4ad-cdfec8067c3f.jpg)
