### ISSUE TITLE
Latest AdGuard Home (Windows 10) edge version shuts down unexpectedly soon after starting the service/process -- v0.107.0-a.208+9bac4b3d

### ISSUE THREAD

**Issue by flavorgold1** [AdguardTeam/AdGuardHome#3851]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

The latest AdGuard Home (Windows 10) edge version shuts down unexpectedly soon after starting the service/process -- v0.107.0-a.208+9bac4b3d.
When you log into the web-ui, "Network Error" pops up below (bottom right). I think that's because it loses its connection with the process/server (because it shuts down unexpectedly).
The version right before this one didn't do that.
For now, I have switched to the beta version and it's working fine.
Can someone confirm if this is happening on their own Windows 10 installation?

* **Version of AdGuard Home server:**
  * v0.107.0-a.208+9bac4b3d
* **How did you install AdGuard Home:**
  * Unzipped in C:/Program Files/AdGuardHome
* **How did you setup DNS configuration:**
  * All
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 10 - latest

### Expected Behavior
Should start and not shut down.

### Actual Behavior
It just shuts down the process unexpectedly.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information
From the Windows Event Log: The AdGuard Home service service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service.

I have the service set to restart in 1 minute if it even fails.

**Comment by ainar-g** [comment]
@Chinaski1, please try and reproduce it.

**Comment by Chinaski1** [comment]
Hi @flavorgold1 

I tried to reproduce the specified issue and don't account for any problems.

To understand the situation, we need the logs of AdGuard Home.
Please, send them to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by ainar-g** [comment]
See also: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog.

**Comment by flavorgold1** [comment]
Is there any way for me to get the `edge` version just prior to this one? It'll help me narrow down the issue.

I will get you the logs soon as well.

**Comment by flavorgold1** [comment]
Does this help?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xd8b3b4]

goroutine 98 [running]:
github.com/AdguardTeam/urlfilter.(*DNSEngine).MatchRequest(0x0, 0xc00b130040, 0x1e, 0x0, 0x0, 0x0, 0x0, 0xc00b12e028, 0x3, 0xc0003538b8, ...)
        github.com/AdguardTeam/urlfilter@v0.15.0/dnsengine.go:125 +0x114
github.com/AdguardTeam/AdGuardHome/internal/aghnet.(*HostsContainer).MatchRequest(0xc0003844d0, 0xc00b130040, 0x1e, 0x0, 0x0, 0x0, 0x0, 0xc00b12e028, 0x3, 0xc0003538b8, ...)
        github.com/AdguardTeam/AdGuardHome/internal/aghnet/hostscontainer.go:137 +0x118
github.com/AdguardTeam/AdGuardHome/internal/filtering.(*DNSFilter).matchSysHosts(0xc000116000, 0xc00b130040, 0x1e, 0x1, 0xc0000863c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/AdguardTeam/AdGuardHome/internal/filtering/filtering.go:467 +0x1bb
github.com/AdguardTeam/AdGuardHome/internal/filtering.(*DNSFilter).CheckHost(0xc000116000, 0xc00b130040, 0x1e, 0x970001, 0xc0000863c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/AdguardTeam/AdGuardHome/internal/filtering/filtering.go:443 +0x179
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).filterDNSRequest(0xc0001c1400, 0xc0002a02d0, 0x8, 0x8, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/filter.go:71 +0x167
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).processFilteringBeforeRequest(0xc0001c1400, 0xc0002a02d0, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:488 +0xa5
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).handleDNSRequest(0xc0001c1400, 0xc000126380, 0xc000322000, 0x0, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:99 +0x3b4
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0xc000126380, 0xc000322000, 0x2940080, 0x30)
        github.com/AdguardTeam/dnsproxy@v0.39.9/proxy/server.go:127 +0x245
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(0xc000126380, 0xc003146030, 0x30, 0x30, 0x0, 0x0, 0x0, 0xc0124a6000, 0xc00009c0b8)
        github.com/AdguardTeam/dnsproxy@v0.39.9/proxy/server_udp.go:105 +0x2e5
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0xc000126380, 0xc003146030, 0x30, 0x30, 0x0, 0x0, 0x0, 0xc0124a6000, 0xc00009c0b8, 0x2548150, ...)
        github.com/AdguardTeam/dnsproxy@v0.39.9/proxy/server_udp.go:74 +0x92
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
        github.com/AdguardTeam/dnsproxy@v0.39.9/proxy/server_udp.go:73 +0x3d5
```

**Comment by ainar-g** [comment]
@flavorgold1, it does, thanks!  We'll try to fix it as soon as we can.

**Comment by EugeneOne1** [comment]
@flavorgold1, hello again.  The latest edge build should fix the panic.  Could you please check, if it actually does?  Thanks.

**Comment by flavorgold1** [comment]
> @flavorgold1, hello again. The latest edge build should fix the panic. Could you please check, if it actually does? Thanks.

Just tried the latest `edge`: `Version: v0.107.0-a.209+d41779cf`, on Windows 10 (with all the latest updates).

It works. No crashes detected thus far.

Thanks for the work you put in.

**Comment by EugeneOne1** [comment]
@flavorgold1, I'll close the issue for now.  Feel free to open new issues for the found bugs.
