### ISSUE TITLE
waiting for 5 minute after fresh install, dns query still count 0

### ISSUE THREAD

**Issue by cekra007** [AdguardTeam/AdGuardHome#3852]
i have problem with adguard, dns query in dashboard still count 0 after i use browsing 5 minute. i dont know whats wrong. i use adguard v0.106.3 and os armbian 20.10 focal.
I have set the router to use ip device adguard for dns router

![Untitled](https://user-images.githubusercontent.com/16054105/142375523-fd95d32c-d417-4c05-a5d5-50af8899f849.png)
.

**Comment by cekra007** [comment]
this result for adguard running port
![image](https://user-images.githubusercontent.com/16054105/142375925-7bcfe743-1faf-4d8b-8601-6f93cfc734a7.png)

**Comment by flavorgold1** [comment]
Does `netstat -tulpn` show AdGuardHome listening on port 53 as `:::53` or `0.0.0.0:53`?

And, does this machine have firewall in place?

**Comment by ainar-g** [comment]
Hello.  Your screenshot shows that the actual port 53 is taken by `systemd-resolved`.  Have you tried [disabling it][1]?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse

**Comment by flavorgold1** [comment]
`systemd-resolved` is listening on 127.0.0.53:53.

**Comment by cekra007** [comment]
I decided to re-install and change it to port 53 again, but when in step 2, I can't use port 3000 and switch to port 30000.
after instalation : 
![image](https://user-images.githubusercontent.com/16054105/142519592-e5dbeb03-0ad1-472d-a0fb-9e9205867507.png)
after complete setup : 
![image](https://user-images.githubusercontent.com/16054105/142519678-24f4cc57-0cf3-41c4-918a-c1636f04002d.png)

**Comment by flavorgold1** [comment]
Share the output of: `netstat -tulpn | grep 53'

And, did you even set the upstream servers?

**Comment by ainar-g** [comment]
@cekra007, please try disabling `systemd-resolved`.  Without it, all DNS queries will go there and not to AGH.
