### ISSUE TITLE
Improvement in parental control

### ISSUE THREAD

**Issue by Gandulf78** [AdguardTeam/AdGuardHome#3853]
### Problem Description
Couple of requests :
- As per Google recommendation for safe search (see https://support.google.com/websearch/answer/186669?hl=en), all Google regional domains should be redirected to forcesafesearch.google.com
- add an option to chose between moderate and strict safe search on YouTube (should be modifiable per client)
- Add an option to completely disable search engine without safe search (as Ecosia.org)

**Comment by ainar-g** [comment]
Hello.

We already give the IP address of `forcesafesearch.google.com` for all regional domains.  Or do you see a domain that doesn't get the IP?

I think that there was already a feature request about a separate YouTube setting in AGH, but I can't find any.  @ameshkov, please remind me, did we ever write an issue about it?

I'm not sure if the third one is even viable, considering that any domain can be a search engine.  This sounds like something that is better handled as a filtering rule list that you can enable in AGH.

**Comment by Gandulf78** [comment]
I need to check again for the first one actually. The second one would be a great improvement since the strict safe search is too restrictive for teenagers. And since these the two settings (search engine and YouTube) are linked I had to completely disable it and I am currently another upstream dns.

**Comment by ameshkov** [comment]
> I think that there was already a feature request about a separate YouTube setting in AGH

As I recall, that's how we should implement this in the refactored version.

**Comment by ainar-g** [comment]
@ameshkov, I added that as a point to the refactoring issue.

**Comment by Gandulf78** [comment]
Hi. 
Yes, regional domains are working. I believe that I was confused because of Apple experimental private relay interfering with my setup. 
For search engines, my point is that you only know on which search engines you are enforcing safe search. Parents won't know it. The idea would be an option to propose to block the major search engines (not the exotic ones of course) which are not enforcing DNS safe search (for example Ecosia.org).
An alternative less user friendly would be to give close to the check-box the list of search engines on which you can enforce safe search with a note to parents to advise them to disable manually the others. 
In all cases, parents should know on which search engines safe search is enable and which aren't.

**Comment by ainar-g** [comment]
@Gandulf78

 >  For search engines, my point is that you only know on which search engines you are enforcing safe search. Parents won't know it.

But the list is right there in the UI:

![Screenshot from 2021-11-29 14-57-42](https://user-images.githubusercontent.com/4964986/143864073-bffc8f17-2da9-46b7-995e-4819fc32a406.png)

Do you think that this is not enough?

 >  The idea would be an option to propose to block the major search engines (not the exotic ones of course) which are not enforcing DNS safe search (for example Ecosia.org).

This, again, sounds like a filter list idea rather than a separate feature, at least to me.  @ameshkov, do we want to support some kind of “allowlist of search engines”, either as a separate filtering rule list or as a separate filtering feature?
