### ISSUE TITLE
CPU consumption at 100% in Raspberry Pi

### ISSUE THREAD

**Issue by omata** [AdguardTeam/AdGuardHome#386]
### Steps to reproduce

1. Install **AdGuard Home** for Raspberry Pi
2. Start the service

### Expected behavior

I expected that it could work just like **pi-hole** service, with minimal CPU consumption and amazing performance.

### Actual behavior

It did fire the **Raspberry Pi** CPU up to 100% with each request rendering the service useless after the second request. Just with open one Web site the Pi is getting 100% of CPU usage. In comparison, **pi-hole** doesn't even touch the CPU usage, it is always under 1%. I'm guessing that **Go Language** doesn't have good performance in **ARM** based devices, or it is because the monolitic nature of **AdGuard Home**.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9
| How did you setup DNS configuration:| Mikrotik Router
| If it's a router or IoT, please write device model:| Raspberry Pi first version/generation
| Operating system and version:| Raspbian GNU/Linux 9.4 (stretch)

**Comment by hmage** [comment]
Hi!

By default, we use dns-over-tls. Try settings upstream servers to 8.8.8.8 and 8.8.4.4 without `tls://`, this should help dramatically with performance.

**Comment by omata** [comment]
> Hi!
> 
> By default, we use dns-over-tls. Try setting upstream servers to 8.8.8.8 and 8.8.4.4 without `tls://`, this should help dramatically with performance.

Just being curious, ¿Why change **CloudFlare DNS** by the **Google** `DNS`?

**Comment by hmage** [comment]
Doesn't matter as long as it's not tls.

**Comment by hmage** [comment]
Also, are you using raspberry pi to browse the web interface? We recommend you use your desktop's browser to access the dashboard.

**Comment by omata** [comment]
> Also, are you using raspberry pi to browse the web interface? We recommend you use your desktop's browser to access the dashboard.

No, I'm using my desktop browser, (Chrome for OSX). My **Raspberry PI** have a headless slim version of Debian Stretch.

**Comment by omata** [comment]
> Doesn't matter as long as it's not tls, since first gen Pi can't handle DNS encryption via DoH.

What `DoH` does mean?

**Comment by hmage** [comment]
@omata sorry, I was meaning to write `DoT` — that's DNS over TLS — https://en.wikipedia.org/wiki/DNS_over_TLS

CloudFlare supports it and we're using it as default, apparently it wasn't a great idea to have it as defaults on first gen raspberry pi — we tested on third gen, which handles that quite well.

**Comment by omata** [comment]
> @omata sorry, I was meaning to write `DoT` — that's DNS over TLS — https://en.wikipedia.org/wiki/DNS_over_TLS
> 
> CloudFlare supports it and we're using it as default, apparently it wasn't a great idea to have it as default on first-gen raspberry pi — we tested on third-gen, which handles that quite well.

👍🏻

Do you know how much CPU use **AdGuard Home** in a 3rd gen **Raspberry Pi**?

Thank you!

**Comment by omata** [comment]
About CPU use it is using more than 4.5 times than **pi-hole** does. So, about the CPU load yours is lower than mine. I can say that **Ad Guard Home** statistics aren't bad. I will give a shoot again when it get more polished and open bugs fixed.

Thanks a lot!

**Comment by hmage** [comment]
I assume this issue can be closed.
