### ISSUE TITLE
How do you get the older `edge` versions of AdGuard Home?

### ISSUE THREAD

**Issue by flavorgold1** [AdguardTeam/AdGuardHome#3860]
I'm trying to download the `edge` version of AdGuard Home from before this one.

**Comment by TheCeet** [comment]
‘Assets’ at the bottom from an release. 
https://github.com/AdguardTeam/AdGuardHome/releases

**Comment by flavorgold1** [comment]
> ‘Assets’ at the bottom from an release. https://github.com/AdguardTeam/AdGuardHome/releases

That's `beta`, not `edge`.

**Comment by TheCeet** [comment]
> > ‘Assets’ at the bottom from an release. https://github.com/AdguardTeam/AdGuardHome/releases
> 
> That's `beta`, not `edge`.

Oops. My bad!
I think it’s not possible. But the devs will answer tomorrow
