### ISSUE TITLE
Make it clear that $client with a name only applies to persistent clients

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3867]
### Discussed in https://github.com/AdguardTeam/AdGuardHome/discussions/3235

<div type='discussions-op-text'>

<sup>Originally posted by **agneevX** June  7, 2021</sup>
I'm trying to block `graph.facebook.com` on all clients except a specific few using this rule:

```regex
||graph.facebook.com^$important,$client=~client-1|~client-2|~client-3
```

However that does not seem to work. 

I've also tried

```regex
||graph.facebook.com^
@@||graph.facebook.com^$important,$client=client-1|client-2|client-3
```

</div>

AGH version: 0.106.3

When client names contain hyphens, the rule doesn't seem to apply to them.

**Comment by ainar-g** [comment]
Your rule contains a mistake: the second `$` is not needed.

I also cannot reproduce the issue, clients with hyphens are excluded.  Please provide something closer to the actual rules you're using.

**Comment by agneevX** [comment]
That was from earlier.

This is the rule I'm using currently

```
||*graph.facebook.com^$important,client=~device-1geuciwo268huw|~android-device
```

**Comment by ainar-g** [comment]
Sorry, but I still cannot reproduce the issue in v0.107.0-b.15.  I set my client name to `device-1geuciwo268huw`, use `nslookup graph.facebook.com`, and get the IP.  From all other clients, the query is blocked.

**Comment by agneevX** [comment]
Ok, while I'm unable to use a beta build right now, I will close this issue until maybe when 0.107 is released and I still have this issue :)

**Comment by agneevX** [comment]
So I took the plunge and created a container with the `edge` image and the issue seems to be present:

![Screenshot (61)](https://user-images.githubusercontent.com/19761269/143260011-ef44b85f-0f38-4c3e-99fa-7436402cbef0.png)

**Comment by ainar-g** [comment]
@agneevX, please show the settings for that client.  Something like the following screenshot:

![Screenshot from 2021-11-24 18-39-20](https://user-images.githubusercontent.com/4964986/143269143-9f38bc69-f6a5-4457-ba4b-091a6ef3a4bd.png)

**Comment by agneevX** [comment]
This is not a custom client.

**Comment by ainar-g** [comment]
Well, there's your problem.  The names only work for clients that you've manually added.  We'll update the documentation in the wiki to make it clearer.

**Comment by agneevX** [comment]
Can this additionally be made into a feature request? 

If IP address is supported as a client, why can't client names be supported too?

**Comment by ainar-g** [comment]
@agneevX, that is tricky to do right in the general case, since the “names” of the runtime clients are taken from several sources and may change at run time.

**Comment by agneevX** [comment]
If it's retrieved via DHCP, I don't think it changes until done manually.

**Comment by ainar-g** [comment]
We have updated the wiki to make the distinction clearer.

 >  If it's retrieved via DHCP, I don't think it changes until done manually.

There are several sources for the names of runtime clients, and their priority might change, so it's not at all a good identifier.  I think that a better UI that would allow people to turn runtime clients into persistent ones could improve the situation here, and I will talk to my colleagues about that, as well as about better syntax highlighting of the custom rules input to make errors like the extra `$` more obvious.
