### ISSUE TITLE
Please, add support for per user basis DNS filtering.

### ISSUE THREAD

**Issue by omata** [AdguardTeam/AdGuardHome#387]
Per user basis `DNS` filtering could be a terrific feature for home, where kids have different rules than everybody. I'm guessing that it can be handled by the `IP` or the `MAC` address.

Thanks in advance.

**Comment by hmage** [comment]
Great idea, thanks!

Will be added to the to-do list. No promises when and how, though.

**Comment by omata** [comment]
> Great idea, thanks!
> 
> Will be added to the to-do list. No promises when and how, though.

Thank you very much!

**Comment by s-timm** [comment]
I also would like to see this feature implemented. We have childen too and per user filtering (e.g. save search ON for children's tablet, but OFF for parents' laptop) would be GREAT! 
Additionally, if you could enable a basic scheduler (e.g. block access to *.youtube.* from 5pm to 7pm...) that would be soooo welcomed! :-)

**Comment by prologic** [comment]
> Additionally, if you could enable a basic scheduler (e.g. block access to _.youtube._ from 5pm to 7pm...) that would be soooo welcomed! :-)

In my case I want to premaritally block `.youtube.` across all my children's devices :P

**Comment by ameshkov** [comment]
Done: #727
