### ISSUE TITLE
Indication in the log detail of the source of a result: cache vs a particular upstream vs [etc]

### ISSUE THREAD

**Issue by Cheddoleum** [AdguardTeam/AdGuardHome#3871]
Had a bit of a time discovering why AdGuard Home kept returning NXDOMAIN for a record which existed, and had existed for some time, on the authoritative server.  Turning off "Optimistic Caching" fixed it. it would have been easier to find if the log entry -- in the detail rollover would be fine -- indicted that it was a cached result.  More generally, seems like it'd be useful to indicate any source of the result in the log.

**Comment by ainar-g** [comment]
The initial work is being done in #3772, with some better indication of the system hosts rules in #3846.  I'll close this issue, since those two seem to mostly cover the feature requests.  Feel free to file new ones if you find anything suspicious!
