### ISSUE TITLE
Upstream for specific client doesn’t work

### ISSUE THREAD

**Issue by optimusleobear** [AdguardTeam/AdGuardHome#3872]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * GitHub install script
* **How did you setup DNS configuration:**
  * Ubuntu on AWS
* **CPU architecture:**
  * AMD 64
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior

I have set upstream DNS server for specific client, so the client should use that. 

### Actual Behavior

All the clients are still using the global upstream DNS server in spite of the client settings. 

### Screenshots

![D64119B0-157C-4776-BF50-465492597DF2](https://user-images.githubusercontent.com/33143885/143169895-4d0fe77b-da1e-4767-b4b3-8a26541233b0.jpeg)
![39DD6F2E-0BDD-46C3-99FB-C6778E4CD579](https://user-images.githubusercontent.com/33143885/143169913-18334824-08b6-4d5c-bca4-eeb519570e4f.jpeg)

**Comment by agneevX** [comment]
Since the server used is in fact specified in the client's settings, I think it uses the default `Load-balancing` setting.

**Comment by ainar-g** [comment]
Sounds like a dup of #3186.  @optimusleobear, could you please check if the latest beta releases fix the issue for you?
