### ISSUE TITLE
No IPv6 Blocking?

### ISSUE THREAD

**Issue by WilsonFlips** [AdguardTeam/AdGuardHome#388]
Does AdGuard Home support IPv6 Blocking/Filtering?

I’m running AdGuard Home on a Pi. I’ve added the IPv6 Cloudflare dns servers to the configuration, and they seem to pass the upstream test. I’ve also added the Pi’s IPv6 address as the dns entry on my router configuration. So far I haven’t been able to get IPv6 blocking to work.

**Comment by ameshkov** [comment]
AdGuard Home does respond with NXDOMAIN for AAAA requests for blocked domains:

```
$ nslookup -query=AAAA doubleclick.net
Server:		192.168.7.2
Address:	192.168.7.2#53

** server can't find doubleclick.net: NXDOMAIN
```

> So far I haven’t been able to get IPv6 blocking to work.

Could you please specify how did you test?

**Comment by sassansh** [comment]
How come when I run it, I don't get NXDOMAIN but 127.0.0.1:

<img width="349" alt="screen shot 2018-11-03 at 1 07 42 am" src="https://user-images.githubusercontent.com/40008576/47949695-dfa81d00-df04-11e8-8f5d-55a0ca69064c.png">

**Comment by sassansh** [comment]
> How come when I run it, I don't get NXDOMAIN but 127.0.0.1:
> 
> <img alt="screen shot 2018-11-03 at 1 07 42 am" width="349" src="https://user-images.githubusercontent.com/40008576/47949695-dfa81d00-df04-11e8-8f5d-55a0ca69064c.png">

Oh, its because I had enabled the other filters:

<img width="700" alt="screen shot 2018-11-03 at 1 09 26 am" src="https://user-images.githubusercontent.com/40008576/47949722-20079b00-df05-11e8-9b0c-1018c312ae10.png">

If you only leave the first one on, you get NXDOMAIN.

**Comment by ameshkov** [comment]
> If you only leave the first one on, you get NXDOMAIN. If I'm not mistaking, NXDOMAIN is faster than 127.0.0.1... Something to look into maybe?

If a domain is blocked by an adblock-syntax rule like `||example.org`, AG Home returns NXDOMAIN.
If there's a matching host in one of the hosts files, AG Home returns the IP that's configured by the hosts file.
