### ISSUE TITLE
AdGuardHome can't block ad in a software

### ISSUE THREAD

**Issue by blue2018** [AdguardTeam/AdGuardHome#3883]
### Issue Details

* **Version of AdGuard Home server:**
      v0.106.3
* **How did you install AdGuard Home:**
      Built from GitHub releases
* **How did you setup DNS configuration:**
      ystem/Router
* **If it's a router or IoT, please write device model:**
      ASUS RT-AC68U
* **CPU architecture:**
      Intel(R) Core(TM) i7-4702MQ
* **Operating system and version:**
       win11 pro latest version 

       
### Actual Behavior
       AdGuardHome can't block  ad in a software named xunlei or Thunder (a download tool), it also includes the popup ad In the lower right corner of the desktop.
       Version: 11.3.3.1846.

### Screenshots
![捕获2](https://user-images.githubusercontent.com/13889354/143528610-3d55c7b3-a384-4802-bf04-5195b1bda324.JPG)
![捕获](https://user-images.githubusercontent.com/13889354/143528614-7ae6e758-58f8-4e7c-b8ea-f93a4a985d19.JPG)

Please fix it, thanks a lot.

**Comment by Funny-T** [comment]
Adguard home is just a dns filter, this is not a problem. You need to add rules yourself, and in principle not all ads can be blocked.

**Comment by blue2018** [comment]
> Adguard home is just a dns filter, this is not a problem. You need to add rules yourself, and in principle not all ads can be blocked.

Ok, i know, thanks for your reply.
