### ISSUE TITLE
[AGH 0.106.3 as Home Assistant addon] Filtering stopped working

### ISSUE THREAD

**Issue by Stooovie** [AdguardTeam/AdGuardHome#3885]
### Issue Details

Filtering stopped working. SOME traffic is obviously (seen in query log) going through AGH but not all. For example, when I go to www.imore.com from my desktop (a web mag filled with ads), I see a couple of blocked entries but NOT the imore.com domain itself. Happens with all websites. This is NOT CONSISTENT though - when I enter the same URL on my phone (same wifi), I DO see the imore.com domain.

Adult sites protection is usually ignored - sometimes I get the blocking screen instead, but more often than not I just get the porn site, unfiltered. 

* **Version of AdGuard Home server:**
  * 0.106.3
* **How did you install AdGuard Home:**
Home assistant 2021.11.5 add-on 4.2.0 (Home Assistant OS running on RPi4). HA Supervisor 2021.10.8. HAOS 6.6. Everything fully updated.

* **How did you setup DNS configuration:**
as DNS server on router. Worked fine for two years.

* **If it's a router or IoT, please write device model:**
TP-LINK Archer AX10

* **CPU architecture:**
ARMHF

### Expected Behavior
All traffic to go through AGH and filtered according to blocklists.

### Actual Behavior
SOME traffic goes through AGH and filtering mostly doesn't work.

### Additional Information
Only noticed this today. Ads are not filtered. Nslookup google.com DOES list 192.168.0.181 (IP of the Pi running Home Assistant) as expected. I'm not aware of any updates or other changes.

UPDATE: I am seeing "Privacy warning - This network is blocking encrypted DNS traffic" in the iOS 15 Wifi settings. I think that's new. Any clues?

**Comment by Stooovie** [comment]
Also, these look REALLY weird
![Screenshot 2021-11-26 at 23 03 40](https://user-images.githubusercontent.com/10572373/143657938-44e15da0-4be3-4d76-b0f9-2279bdc93dcb.jpg)
.

**Comment by ainar-g** [comment]
Hello and thank you for the report.  What browsers do you use to check if AGH is working?  Google Chrome, for example, is known to both [create a bunch of random DNS queries][1] and [ignore the local DNS server][2].

 >  UPDATE: I am seeing "Privacy warning - This network is blocking encrypted DNS traffic" in the iOS 15 Wifi settings. I think that's new. Any clues?

If [this] is to be believed, it means that that message appears if your network “does not meet certain requirements”.  The article goes on to link to another article with recommendations.

[1]: https://unix.stackexchange.com/questions/363512/chrome-dns-requests-with-random-dns-names-malware
[2]: https://networkguy.de/google-chrome-ignores-the-local-dns-server/
[3]: https://discussions.apple.com/thread/251905649

**Comment by Stooovie** [comment]
Hi, Safari on iOS 15, Safari and Edge (= probably similar to Chrome) on MacOS 12 Monterey.  It somehow sort of started working after powercycling the whole Pi but it's still kind of flaky and definitely not as good as before. I was able to get much better protection with the exact same filter lists before. I wish I could be more precise but I can't - the AGH addon for Home Assistant doesn't output much actionable logs, even with logging set to Debug.

Thanks for the notice on Chrome ignoring DNS.

**Comment by ainar-g** [comment]
Another thing to consider: if you're using Apple Private Relay, it will use its own DNS servers by default.  See #3248.

**Comment by Stooovie** [comment]
No, I'm not.
