### ISSUE TITLE
Disablу protection

### ISSUE THREAD

**Issue by lbtboy** [AdguardTeam/AdGuardHome#3886]
**AdGuard Home версия: v0.106.3**

**Чем отличается режим** `Панель управления > Отключить защиту`

![AdGuard Home  - 27 11 2021_05_03_41](https://user-images.githubusercontent.com/57795912/143662098-db37345a-f996-49d4-9517-fd8b6c48452e.jpg)

**от** `Настройки > Основные настройки > Блокировать домены с использованием фильтров и файлав хостов`?

![AdGuard Home - 27 11 2021_05_05_39](https://user-images.githubusercontent.com/57795912/143662155-a09ccbc2-af71-4c10-b8b4-21032f380d1e.jpg)

**Comment by EugeneOne1** [comment]
@lbtboy, здравствуйте.  В #1558 мы изменили логику фильтрации – кнопка `Отключить защиту` отключает фильтрацию запросов с помощью любых правил кроме правил типа `dnsrewrite`, а кнопка `Блокировать домены с использованием фильтров и файлов хостов` отключает и `dnsrewrite` правила.  

Соответствующие настройки в [конфигурационном файле](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file):

 *  `Отключить/Включить защиту`: `protection_enabled`;
 *  `Блокировать домены с использованием фильтров и файлов хостов`: `filtering_enabled`.
 
Пожалуй, стоит уточнить роль этих настроек на странцие в wiki.

**Comment by lbtboy** [comment]
Здравствуйте. Это для меня исчерпывающий ответ. Спасибо.

**Comment by EugeneOne1** [comment]
@lbtboy, мы обновили соответствующую страницу в [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file), так что теперь она содержит информацию актуальную для обеих версий.  Еще раз спасибо за ваш вклад.
