### ISSUE TITLE
Couldn't get stats error

### ISSUE THREAD

**Issue by sassansh** [AdguardTeam/AdGuardHome#389]
### Steps to reproduce
1. Started the program using terminal on mac.
2. Browsed to http://localhost:3000/
3. Got an empty dashboard with red errors on bottom right (screenshot attached)
4. Setting pages, etc work fine.

### Expected behavior
No errors and a dashboard displaying stats.

### Actual behavior
Presented with empty dashboard with red errors on bottom right (screenshot attached).

<details><summary>Screenshot:</summary>
<img width="1548" alt="screen shot 2018-10-17 at 10 30 20 pm" src="https://user-images.githubusercontent.com/40008576/47133251-c775a400-d25c-11e8-832a-00d8a9d92cd9.png">

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9
| How did you setup DNS configuration:| System
| If it's a router or IoT, please write device model:| MacBook Pro (13-inch, 2016)
| Operating system and version:| MacOS Mojave 10.14.1 Beta (18B67a)

**Comment by sassansh** [comment]
Here is what the terminal window displayed:

2018/10/17 22:30:09 Couldn't get stats_top from coredns: *url.Error Get http://127.0.0.1:8618/stats: dial tcp 127.0.0.1:8618: connect: connection refused

2018/10/17 22:30:09 Couldn't get stats_top from coredns: *url.Error Get http://127.0.0.1:8618/stats_history?start_time=2018-10-16T22:30:09-07:00&end_time=2018-10-17T22:30:09-07:00&time_unit=hours: dial tcp 127.0.0.1:8618: connect: connection refused

2018/10/17 22:30:09 Couldn't get stats_top from coredns: *url.Error Get http://127.0.0.1:8618/stats_top: dial tcp 127.0.0.1:8618: connect: connection refused

**Comment by sassansh** [comment]
found the answer in another thread.

**Comment by hmage** [comment]
Hi! Thanks for reporting anyway!

Try the hotfix release -- [v0.9-hotfix1](https://github.com/AdguardTeam/AdGuardHome/releases). It should solve your problem if it isn't already solved.
