### ISSUE TITLE
Dashboard-Top clients-Requests count-Client does not change timely after disable Anonymize client IP

### ISSUE THREAD

**Issue by MkQtS** [AdguardTeam/AdGuardHome#3890]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

There are two source DNS request IP in my network. One is `172.16.16.16#127`, another is `127.0.0.1#127`. When *Anonymize client IP* is enabled, *Dashboard-Top clients-Client* shows `127.0.0.0` and `172.16.0.0`. Then disable  *Anonymize client IP* and clear query logs and statistics. *Dashboard-Top clients-Requests count* return to zero, but *Client* still shows `127.0.0.0` and `172.16.0.0`, not `127.0.0.1` and `172.16.16.16`. Click it, it turns to `http://172.16.16.16:128/#logs?response_status=&search=127.0.0.0` and no result can be shown. Manually search `127.0.0.1`, results can be shown.

Restart Adguard Home can solve the problem.

* **Version of AdGuard Home server:**
  * v0.107.0-b.15
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * x86 computer
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * LuCI openwrt-18.06-k5.4 branch (git-21.322.62925-ea9b160)

### Expected Behavior

Disable  *Anonymize client IP* and clear query logs and statistics. *Dashboard-Top clients-Requests count-Client* shows `127.0.0.1` and `172.16.16.16` immediately.

### Actual Behavior

Disable  *Anonymize client IP* and clear query logs and statistics. *Dashboard-Top clients-Requests count-Client* still shows `127.0.0.0` and `172.16.0.0`.

**Comment by MkQtS** [comment]
@EugeneOne1, Sorry for late response. It's fixed in `v0.107.0-a.223+86cffcd1`, thank you.

**Comment by EugeneOne1** [comment]
@MkQtS, closing the issue for now.
