### ISSUE TITLE
Add DNS zone via web interface

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/AdGuardHome#390]
Hello. I would like to be able to create your DNS zone based on Adguard Home through its interface. In order not to keep a few dns server. Thus, release port 53 for Adguard Home

**Comment by CWo42** [comment]
+1
same here, can you give us a little more DNS control? Thx

**Comment by ibksturm** [comment]
+1

**Comment by prologic** [comment]
To elaborate on @alvussar -- I have a similar use-case where up until now I've been using CoreDNS for my home network and several Docker Swarm mode clusters. I use CodeDNS for two purposes (//three really//):

1. Locally host a zone so I can have both *.mydomain.com (//which is also publically available via DigitalOcean Name Servers//) and *.intern.mydomain.com (//which is only available internally to my network//)
2. DNS Cache
3. DNS Forwarder (//usually to Google DNS servers//)

So it would be nice if AdGuardHome also grew the ability to have locally hosted zones, created through the Web Interface, as well as an appropriate API to manage it that way too. It would also be really awesome if this was extended to PTR records for an IN-ARPA zone and integrated in the builtin DHCP server.

With this AdGuardHome now becomes a fully fledged and quite powerful tool to: Manage and Filter DNS, Provide DHCP leases (//with where to find name servers//) as well as locally hosted zones (//for those special enough to understand how that's useful//)

Thanks heaps! (//also happy to contribute to this as time permits//)

**Comment by ameshkov** [comment]
Hi @prologic, thanks for a detailed explanation!

Could you please share an example of the CoreDNS config file you're using? Just for us to better understand your needs.

**Comment by prologic** [comment]
Certainly :) It's actually quite simple:

`Corefile`:
``
.:53 {
    auto mydomain.com {
        directory /data/zones
	}
    cache
    health
    proxy . 10.0.0.1:53 {
        except mydomain.com
        policy round_robin
    }
    prometheus 0.0.0.0:9153
    errors stdout
    log stdout
}
```

Right now my home network is a bit crippled in the fact I'm unable to resolve any local hostnames :) -- I can live with that for now because I'm loving AdGuardHome in general so I'll just have to remember a bunch of IP Addresses :D -- However I now do have an entire set of internal only applications that are now inaccessible until this feature is added.

**Comment by adrianmace** [comment]
I would also like this feature, with the ability to specify custom SRV records in particular to assist my Windows hosts with some service discovery that is not currently possible.

Previously I was achieving this with PiHole by including a secondary `personal.conf` file in the `conf.d/` but this is seemingly not possible with AGH.

**Comment by jerrac** [comment]
Full DNS support would be amazing. As in, adding A, MX, CNAME, etc, records. I have not found any simple tool that does that, and AdGuardHome is already a DNS server, so it seems like a good fit.

That said, for simple stuff, wouldn't just adding a custom rule do the job? 

Just add something like `192.168.222.123 foo.myhome.life` to the `/#custom_rules` page, and I'd think you'd be good to go.

**Comment by Deanosim** [comment]
I'd also like to add my support for bring this to adguard home, currently I'm using custom dnsmasq files under dnsmasq.d/ in pihole with docker, and with that I can create an dns record I want. It would be amazing if Adguard could support full dns records.

**Comment by jessechahal** [comment]
> I'd also like to add my support to bring this to adguard home, currently I'm using custom dnsmasq files under dnsmasq.d/ in pihole with docker, and with that I can create any dns record I want. It would be amazing if Adguard could support full dns records.

Why do you do this manually in pihole? It is natively supported in the GUI for A and AAAA records. The next release of Pi-hole will support CNames (already merged to master but not in latest release).

**Comment by Deanosim** [comment]
Because https://github.com/uklans/cache-domains has a script that exports to dnsmasq files and it's far too many entires to enter into the pihole web interface. but I don't just use dnsmasq config files for A records I also use srv and various other records for different things.

**Comment by kt1024** [comment]
ability to setup dns zone would be great for home and company usage. 
my personal use case is to provide mx records, for my home lab, to send alert/logs to local `citadel` mail server.

**Comment by kt1024** [comment]
does dnsrewrite support MX records? (not A record)

**Comment by kt1024** [comment]
got it. thanks

**Comment by ainar-g** [comment]
Since there were no other reactions, I'm inclined to close this issue as complete.  If the `dnsrewrite` rule feature lacks functionality, please file new issues.

**Comment by ainar-g** [comment]
I see.  We might extend the current *Filtering → DNS rewrites* section in the future, but that's a bit in the air right now.  Using `dnsrewrite` rules is the way to do that in the meantime.
