### ISSUE TITLE
Having a rough time attempting to use AdGuard Home

### ISSUE THREAD

**Issue by Jaladhjin** [AdguardTeam/AdGuardHome#3901]
So I setup AdGuard Home on a brand new Pi 4 running Manjaro.

Everything went excellent & I could access the interface on my Pi so I thought awesome this was as easy as I'd hoped.

So I went to go hit my AdGuard Home IP from any other machine in my home to access the web interface & have been unsuccessful.

I did go through the setup process in case that needed to be done on the initial installed machine before I could access the Web UI but nope.

I can ping it & also SSH to it.

Here's what my AdGuardHome.yaml looks like.

I did select pretty much all default options on initial setup & set my Username & Password figuring I'd configure it all from there.

And I'll tell you I'm veeeeery inexperienced with more advanced networking & especially Linux related settings.

I don't have segregated networks or isolation setup & again can totally ping & SSH to the Pi & can also still access the web UI from the Pi only.

Grateful for any & all assistance & advice!

https://i.imgur.com/pdlJZ74.png

---I edited the title because I'm not trying to pick a fight.

But with that similar service I didn't have this issue on the same Pi, same network, I could hit it right away so I don't deny it might be my own lack of knowledge or expertise.

Thanks again for any help I'm really sad I can't hit my AGH web interface :-(

**Comment by Jaladhjin** [comment]
I edited the title because I'm not trying to pick a fight.

But with that similar service I didn't have this issue on the same Pi, same network, I could hit it right away so I don't deny it might be my own lack of knowledge or expertise.

Thanks again for any help I'm really sad I can't hit my AGH web interface :-(

**Comment by EugeneOne1** [comment]
@Jaladhjin, hello and thanks for the report.  Could you please provide some information to troubleshoot the issue:

 1. How exactly did you install the AdGuard Home (via docker / via installation script / manually)?
 1. What version of AdGuard Home did you installed?
 1. What is the output of `sudo lsof -i :80` on the Pi with AdGuard Home running (if `lsof` is available)?
 
It would also be very helpful if you could reproduce the issue and collect some [verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us.  You may send those here or to devteam@adguard.com.

**Comment by Jaladhjin** [comment]
I'd gladly help however I can.

I can constantly reproduce the issue since I can't hit the AGH web UI from any other machine in my home besides the Pi itself.

How do I oh I see the verbose logs is clickable.

I installed in terminal via the Curl command: curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v

I just installed it the other day like 2 days ago now so whatever version the Automated Install did :-)

The output of that command says command not found

[pi@Pijaro ~]$ sudo lsof -i :80
[sudo] password for pi:
sudo: lsof: command not found

Happy to provide the logs but once I do the things in that guide where do I get the log(s) from to share with you?

Thanks much for your help!

**Comment by EugeneOne1** [comment]
@Jaladhjin, logs should have been written to the file you specified in the `log_file` setting.

**Comment by Jaladhjin** [comment]
I didn't know I could or should write logs to a file I specified.

I apologize I'm not very talented with Linux.

I can ssh in & do nano & open the yaml file & set verbose to true.

What do I set for the file so it goes into like documents or whatever?

**Comment by EugeneOne1** [comment]
@Jaladhjin, well, you may use `pwd` to get the path to the current directory (e.g. after logging in with ssh).  You'll get something like:
```
/path/to/dir
```

Add some filename to the end of the path, for example:
```
/path/to/dir/log.txt
```

Simply put the final path to `log_file` and start AGH.  The log file will be created automatically.

**Comment by Jaladhjin** [comment]
Thanks very much again I apologize I'm not trying to be difficult.

So I tried to do as you instructed & set a log path.

In my yaml file I set it like this & I do not see any agh.txt generated in the path expected.

log_file: /home/pi/documents/agh.txt
verbose: true

**Comment by EugeneOne1** [comment]
@Jaladhjin, the AGH should be stopped before modifying the configuration file because the changes will be rewriten otherwise.  If you installed it as a service via script, you should be able to turn it off with:

```sh
/path/to/agh/dir/AdGuardHome -s stop
```

And to start it after configuration changes:

```sh
/path/to/agh/dir/AdGuardHome -s start
```

The `/path/to/agh/dir` is usually the same as the path to the configuration file.

**Comment by Jaladhjin** [comment]
so I did it but nothing is happening still no log file :-(

I will show you all of what I have done.

I am using BitVise to both SSH & SFTP to check for the file in the directory.

https://i.imgur.com/c2KE0rF.png

https://i.imgur.com/srUhW7t.png

**Comment by Jaladhjin** [comment]
I ended up re-doing the Pi to Ubuntu Server over Manjaro & everything worked as expected no problems whatsoever.

Thanks very much for trying to help as much as you did @EugeneOne1

Before I go 1 other question.. can I add pretty much any blocklists I would have added on a Pi-hole into AGH with the same links? 🤔😁

I'm guessing yes of course.

**Comment by EugeneOne1** [comment]
@Jaladhjin, blocklists aren't depend on the OS or architecture you're using so you may use those for sure.

**Comment by Jaladhjin** [comment]
Awesome sure I wasn't sure if some were formatted certain ways for either platform so I needed to use AGH specifically formatted ones or something.

Awesome well hey I really appreciate all the advice, assistance & info!

Last question what is your opinion on large blocklists?

I see communities this one likely included either saying the more the merrier or try to keep them under x amount more isn't always better.

I do understand the more blocklists the bit more taxing all the blocking on the Pi.

I also understand the more blocklists the more that may need to be whitelisted to get something that might not be functioning to function.

Are there any official-ish responses out there? :-)
