### ISSUE TITLE
Add bind9 server in Server DNS upstream - Server could not be used, please check that you've written it correctly

### ISSUE THREAD

**Issue by mauriziozito** [AdguardTeam/AdGuardHome#3905]
I'm sorry for my english
when i try to add the ip address of my bind9 server it tells me:
Server x.x.x.x: 53 cannot be used, make sure you spelled it correctly.
What am I doing wrong?
if i use the same bind9 server as dns directly from client it works.
Is there a log that indicates more clearly what the problem is?

Thank you

**Comment by mauriziozito** [comment]
error is:
server "x.x.x.x:53" could not be used, please check that you've written it correctly

**Comment by EugeneOne1** [comment]
@mauriziozito, we'll need some additional info from you to troubleshoot it:

 1. What version of AGH do you use?  How did you installed it and what the OS hosts it?
 1. If the server is available from that machine?  You may check it with `dig @x.x.x.x -p 53 example.com`.

Could you also [configure AGH](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) to collect verbose log and send it here or to devteam@adguard.com?
