### ISSUE TITLE
It is recommended to add shunt port or shunt group

### ISSUE THREAD

**Issue by chenyajunai** [AdguardTeam/AdGuardHome#3909]
It is recommended to add a shunt port or shunt group. Domestic and foreign countries can use different groups of DNS, and then use the configuration file IP section and domain name to distinguish which group of DNS is used at home and abroad.

Although the current version can be in the form of [/host.com/]1.2.3.4, but only one dns can be added. Use the upstream_dns_file configuration file in Ad Guard Home.yaml. If there are many domain names, the startup will fail.

**Comment by EugeneOne1** [comment]
@chenyajunai, I'm not sure I understand what do you mean by "shunt port/group"?  What the configuration file is implied in the question?  Are you trying to use different upstream servers for different clients?  In this case you may want to try [client-specific](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientsettings) upstreams.

The file specified by `upstream_dns_file` is equivalent to the web-based setting input.  You may specify several DNS servers for domains like this:

```
[/domain1/domain2/]primary.dns.any
[/domain1/]secondary.dns.first
[/domain2/]secondary.dns.second
```

Could you please share the exact content of the file that makes AGH fail the startup?  You may post it here or send to devteam@adguard.com.
