### ISSUE TITLE
AGH Ignores Custom Allow Rules on different browsers and making up list references

### ISSUE THREAD

**Issue by CassTG** [AdguardTeam/AdGuardHome#3911]
Issue on:

Windows 11
Version:  v0.107.0-b.15 Docker on Debian
Browsers affected - All

So a couple of sites i visit keep getting blocked, so at first i clicked unblock in query log, but if the site pulls info from a subdomain i.e api. or media. i then have to go unblock them individually.

So i put in a custom filtering rule to allow the whol domain and subdomains, trying with both important and document tags

However if i visit from the same device (same ip no reboot) in a different browser the whole process starts again and it blocks them again ignoring any custom rules.

So i thought next i would check the list that the domain is flagged on in the query logs, and neither of the 2 domains appear at all in the list not in full or in part., so they should not being blocked at all.

AGH has been pretty perfect up till this point but now it is just becoming an annoyance as none of this makes any sense, as if i boot back into OSX and use edge or chrome i face no issues on these sites at all, it only happens on Windows 11

**Comment by EugeneOne1** [comment]
Hello, @CassTG, and thanks for the report.  Could you please [configure](github.com/adguardTeam/adGuardHome/wiki/FAQ#verboselog) AdGuard Home to collect some verbose logs, reproduce the issue and send the resulting log file here or to devteam@adguard.com?

**Comment by CassTG** [comment]
Sure i shall do this shortly.

**Comment by CassTG** [comment]
Oh your configure link gives a 404 lol, ill search for it
