### ISSUE TITLE
Rewrite rule  for local_domain_name: lan  is ignored when DHCP is enabled

### ISSUE THREAD

**Issue by netlest** [AdguardTeam/AdGuardHome#3912]
- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

When param local_domain_name is defined as 'lan' and DHCP Server is enabled  it is not possible to add new DNS rewrite rule from within the same domain ".lan" (at least it is not resolving). 

* **Version of AdGuard Home server:**
0.106.3
* **How did you install AdGuard Home:**
Docker
* **How did you setup DNS configuration:**
NAS
* **CPU architecture:**
  AMD64
* **Operating system and version:**
docker container Alpine Linux

### Expected Behavior

Rewrite rule  for subdomain of "lan" should return DNS response.

### Actual Behavior

Defined rewrite rule from within domain "lan" (defined as local_domain_name) is being ignored. DNS doesn't respond with given IP  (only when DHCP is also enabled).

**Comment by EugeneOne1** [comment]
@netlest, please read this [wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) to make it clear what `local_domain_name` setting is used for.  Briefly, it's for accessing devices leased by AGH's DHCP server and it deliberately avoids any filtering during processing.
