### ISSUE TITLE
 The TTL is always 10s with Blocking mode used ‘Default' , the ttl will be min TTL value

### ISSUE THREAD

**Issue by dominicx** [AdguardTeam/AdGuardHome#3927]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.107.0-b.15
* **How did you install AdGuard Home:**
  * Github release
* **How did you setup DNS configuration:**
  * AdGuard IPs as DNS in DHCP settings
* **If it's a router or IoT, please write device model:**
  *  null
* **CPU architecture:**
  * amd64
* **Operating system and version:**
  * Debian 10

### Expected Behavior
If I query a blocked domain name, the TTL value in the result returned by AdGuardHome should be the value of the configuration item "Override minimum TTL", such as 600. 

### Actual Behavior
AdGuardHome always returns the TTL value: 10 seconds

### Screenshots
![snap20211211164235](https://user-images.githubusercontent.com/4507275/145670460-9af69b16-2af6-4bf5-a1c0-0f323fdaa428.png)

**Comment by Harvester57** [comment]
I believe you are mistaken about the expected behavior. The TTL for blocked requests is controlled by the `blocked_response_ttl: 10` entry in your YAML configuration file.

By default, it is set to 10 seconds because you do not want your clients to wait your minimum TTL (600 seconds in your case) before retrying a resolution, in case of a false-positive that you manually unblock.

**Comment by dominicx** [comment]
> I believe you are mistaken about the expected behavior. The TTL for blocked requests is controlled by the `blocked_response_ttl: 10` entry in your YAML configuration file.
> 
> By default, it is set to 10 seconds because you do not want your clients to wait your minimum TTL (600 seconds in your case) before retrying a resolution, in case of a false-positive that you manually unblock.

Thanks for your suggestion, I ignored the configuration item "blocked_response_ttl". If AdGuardHome does not clear the cache of the special domain name after clicking the "Unblock" button on the ui, I can only temporarily cancel the entire filter to deal with it.

**Comment by dominicx** [comment]
> I believe you are mistaken about the expected behavior. The TTL for blocked requests is controlled by the `blocked_response_ttl: 10` entry in your YAML configuration file.
> 
> By default, it is set to 10 seconds because you do not want your clients to wait your minimum TTL (600 seconds in your case) before retrying a resolution, in case of a false-positive that you manually unblock.

I tested this situation, and after clicking the "unblock" button on the interface, AdGuardHome gave the correct resolution record of the specific domain name.
![snap20211212201143](https://user-images.githubusercontent.com/4507275/145711665-e92c2af5-059c-4f73-8780-ad4db5b61272.png)

**Comment by ainar-g** [comment]
@dominicx, hello.  Is your issue resolved?

**Comment by dominicx** [comment]
> @dominicx, hello. Is your issue resolved?

resolved. please closed it. thx.
