### ISSUE TITLE
openwrt adguard home 密碼不能用  192.168.1.182:3000

### ISSUE THREAD

**Issue by leung9250** [AdguardTeam/AdGuardHome#3928]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by stevenzhu25** [comment]
What exactly do you mean?
Did you follow a guide when installing AdGuard Home on your OpenWRT device? 
https://forum.openwrt.org/t/howto-running-adguard-home-on-openwrt/51678

You can also try to change the existing password with your AdGuard Home instance, by using htpasswd tool like [this guide](https://docs.cloudron.io/apps/adguard-home/#change-password)

**Comment by leung9250** [comment]
已解決

在 2022年4月16日 週六 16:30，stale[bot] ***@***.***> 寫道：
