### ISSUE TITLE
Prepare and publish a Privacy policy for AG Home

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdGuardHome#393]

**Comment by ameshkov** [comment]
Here're some key points:

1. AdGuard periodically downloads https://github.com/AdguardTeam/AdGuardHome/blob/master/version.json to check if there's a newer version
2. AdGuard periodically checks filters updates
3. If you enable (it's disabled by default) the "use browsing security service" option, AdGuard Home connects to the browsing security server and passes an 8-character prefix of the domain name's SHA256 hash. The server responds with a list of full hashes and AG Home checks if there's a match.
4. If you enable (it's also disabled by default) the "use parental control service" option, AdGuard Home connects to the parental control web service using the same protocol as in point 3.

That's about it I guess.

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/LegalDocs/pull/20

**Comment by ameshkov** [comment]
@IldarKamalov please add "Privacy policy" link to the footer when AGH privacy notice gets published
