### ISSUE TITLE
O serviço DHCP, não funciona no raspberry - pi

### ISSUE THREAD

**Issue by romulosccp09** [AdguardTeam/AdGuardHome#3931]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

Estou fazendo um teste com o AdGuard, no raspberry pi, e antes usava o pi-hole, os dois apresentam um problema, de não
entregar Ip quando selecionamos, como servidor dhcp, com pi-hole, até consegui, ele em uma VM.

**Comment by ainar-g** [comment]
Hello.  What exactly do you mean by “IPs not being delivered”?  Can you show queries that aren't being resolved with e.g. `dig` or `nslookup`?

Also, which version are you running, and have you tried the latest beta releases?  Thanks.

**Comment by romulosccp09** [comment]
O computador faz uma solicitação de ip, e o DHCP, não manda pra o computador o Io da redeEm 13 de dez de 2021 08:49, Ainar Garipov ***@***.***> escreveu:

Hello.  What exactly do you mean by “IPs not being delivered”?  Can you show queries that aren't being resolved with e.g. dig or nslookup?

Also, which version are you running, and have you tried the latest beta releases?  Thanks.

**Comment by ainar-g** [comment]
Apologies for the late response.

How did you install AdGuard Home on your Pi?  If through Snapcraft, it could be #3976.  There are solutions on the `edge` channel.

You can also [enable verbose logging][1] and look for debug messages that contain `dhcp` in them.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by romulosccp09** [comment]
Sim instalei por snap, e estou usando o ubuntu server 20.10. o modelo do raspi é o 3b. Obrigado pela resposta.Em 24 de dez de 2021 08:54, Ainar Garipov ***@***.***> escreveu:
Apologies for the late response.
How did you install AdGuard Home on your Pi?  If through Snapcraft, it could be #3976.  There are solutions on the edge channel.
You can also enable verbose logging and look for debug messages that contain dhcp in them.
