### ISSUE TITLE
Can't connect to AdGuard Home Web Interface

### ISSUE THREAD

**Issue by ihrubab** [AdguardTeam/AdGuardHome#395]
I flashed the latest 2018-10-09-raspbian-stretch-lite.img to the SD card and started the headless setup. Then I followed the instruction from this page:
https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi

### Expected behavior
I should be able to see the AdGuard Home web interface by using that address or using the address using the IP if my raspberry pi.

### Actual behavior
When I try to connect to the http://localhost:3000/ I get "This site can't be reached"

**Comment by ameshkov** [comment]
Hi! Replace `localhost` with your Pi's IP address

**Comment by ihrubab** [comment]
I did and I still get 
"This site can’t be reached
192.168.10.200 refused to connect."

**Comment by dfmcvn** [comment]
Does the port 3000 already opened? Maybe your firewall blocked it.

**Comment by dfmcvn** [comment]
> Do I need to manually open it? I mean I haven't change the default settings found in Raspbian.

Try `sudo iptables -L`

If output looks like
```
[root@vps192261 AdGuardHome.wiki]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
[root@vps192261 AdGuardHome.wiki]#
```
that mean iptables doesn't block any port, firewall is not the problem :P

**Comment by ihrubab** [comment]
> > Do I need to manually open it? I mean I haven't change the default settings found in Raspbian.
> 
> Try `sudo iptables -L`
> 
> If output looks like
> 
> ```
> [root@vps192261 AdGuardHome.wiki]# iptables -L
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination
> [root@vps192261 AdGuardHome.wiki]#
> ```
> that mean iptables doesn't block any port, firewall is not the problem :P

I got the same results, so Firewall isn't the problem. What else could be doing this?

**Comment by ihrubab** [comment]
I ran **sudo systemctl daemon-reload** after I ran **sudo systemctl enable adguard-home** and 
**sudo systemctl start adguard-home** and it is working. I still didn't manage to figure out why it wasn't working in the first place.

**Comment by dfmcvn** [comment]
Maybe daemon-reload already listening on port 53, so coredns (AdGuardHome) couldn't lauch :P

**Comment by dfmcvn** [comment]
I dunno but it looks like this issue.
https://github.com/AdguardTeam/AdGuardHome/issues/402

**Comment by ihrubab** [comment]
> I dunno but it looks like this issue.
> #402

Is this supposed to be the normal when I run **host doubleclick.net 127.0.0.1**:

> Using domain server:
> Name: 127.0.0.1
> Address: 127.0.0.1#53
> Aliases: 
> 
> doubleclick.net has address 127.0.0.1
> doubleclick.net has address 127.0.0.1
> doubleclick.net has address 127.0.0.1

**Comment by dfmcvn** [comment]
Look strange, but Yes.

**Comment by evansan** [comment]
change bind_host to 0.0.0.0.

**Comment by ihrubab** [comment]
> change bind_host to 0.0.0.0.

Can you tell me how to change bind_host to 0.0.0.0. on rpi3 running raspbian?

**Comment by dfmcvn** [comment]
> > change bind_host to 0.0.0.0.
> 
> Can you tell me how to change bind_host to 0.0.0.0. on rpi3 running raspbian?

![image](https://user-images.githubusercontent.com/22710598/47267146-dc5a7c00-d569-11e8-8fa6-c526664ad4ae.png)

**Comment by ihrubab** [comment]
> > > change bind_host to 0.0.0.0.
> > 
> > 
> > Can you tell me how to change bind_host to 0.0.0.0. on rpi3 running raspbian?
> 
> ![image](https://user-images.githubusercontent.com/22710598/47267146-dc5a7c00-d569-11e8-8fa6-c526664ad4ae.png)

Thanks. Everything is working the way it should.

**Comment by ameshkov** [comment]
I guess it can be closed now

@dfmcvn @evansan thank you so much!

**Comment by lifesux0369** [comment]
Hello, facing same issue. Cannot connect on static IP 192.168.1.XXX:3000 using port DNS port 53. If i change to like 1027 in adguardhome.yaml i am able to open the page but its not connecting.

host doubleclick.net 127.0.0.1 results in connection time out, no servers could be reached.

tried the solution - I ran sudo systemctl daemon-reload after I ran sudo systemctl enable adguard-home and sudo systemctl start adguard-home and it is NOT working for me. 

IP table command shows same results 

sudo iptables -L

If output looks like

[root@vps192261 AdGuardHome.wiki]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by edchuchuchu** [comment]
Had same issue on pi4b. Any suggestion?

**Comment by chrisuk82** [comment]
I've exactly the same issue. I could initially access it to setup, but since I made it my DHCP and reset my devices, I can no longer connect.

Status via pi says it's running, but I can't access the web interface.

**Comment by ihrubab** [comment]
Have you tried installing Adguard on a fresh Rpi setup? My problems resolved when I formatted my SD Card and tried the whole process again. Also make sure that your VPN is OFF when connecting to Adguard home.
