### ISSUE TITLE
Optimistic caching stopped working in latest edge build

### ISSUE THREAD

**Issue by leo15dev** [AdguardTeam/AdGuardHome#3950]
### Issue Details

* **Version of AdGuard Home server:**
  *   v0.107.0-a.240+4be69d35
* **How did you install AdGuard Home 
  *  Docker
* **How did you setup DNS configuration:**
  *  DoH
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi  4B
* **CPU architecture:**
  *  ARM64
* **Operating system and version:**
  *  Ubuntu 20.0.3

### Expected Behavior

Optimistic caching should be work fine after you enabled this feature. Even when you used watchtower to automatically update the docker container.
### Actual Behavior

By reviewing the query log web page, I found that the optimistic caching stopped working at least from  20211215 edge build. 
### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

![Screenshot 2021-12-17 at 08-27-23 AdGuard Home](https://user-images.githubusercontent.com/68909774/146469102-dadbc971-a3e8-4459-bfeb-2d606445190d.png)

![Screenshot 2021-12-17 at 08-38-05 AdGuard Home](https://user-images.githubusercontent.com/68909774/146469568-150cbdb9-940f-4fb9-8ad5-20b062ee9391.png)

**Comment by EugeneOne1** [comment]
@leo15dev, hello.  Unfortunatelly, we can't reproduce the issue.  Could you please provide some additional information:

 1. Are the responses contain anything meaningful for caching (e.g. actual answers or at least any `SOA` records)?
 1. If the settings of caching remained the same after update?  Is it possible, the watchtower has somehow rewritten the `.yaml` configuration file or the container's configuration?

**Comment by leo15dev** [comment]
@EugeneOne1 Thanks for yor reply.
1.  If respose from the cached, the Elapsed time should be less than 1 ms, and the Response details should be have the  (served from cache)  word.
2. I do not change any setting after or before the watchtower automatically update the docker container. To my knowledge, the watchtower will not modify any file or container's configuration while it automaticallu updated the container. Besides, I used it for a while, there is no issue to use it to update other containers or update the Adguard Home EDGE docker version. 
3.  After the watchtower automatically update to the v0.107.0-a.241+b3210cfa, the Optimistic caching worked again. I do not kwnow what happen on it, but it works! 
![1](https://user-images.githubusercontent.com/68909774/146562661-8e84290f-aae2-46fb-bc02-cd07396cfc77.jpg)

Since the issue seems to solved by unknowen reason, I will imediatelly close the issue. Thank you again!

**Comment by leo15dev** [comment]
After update to v0.107.0-a.241+b3210cfa, the same situation happened again!  Since the Adguard Teams could not reproduce the same issue, so I am not sure  I need reopen the issue or not. I decide to leave the comments here,  if someone will have the same issue in the future, they could find the similar clues.

**Comment by EugeneOne1** [comment]
@leo15dev, it'd be really helpful if you would collect [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us.  You may either post it here or send to devteam@adguard.com.
