### ISSUE TITLE
Nwe Client option : Select Filtering list by client

### ISSUE THREAD

**Issue by caca9512** [AdguardTeam/AdGuardHome#3951]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I want select specific list of filter for some client.

exemple : I want the ad's on the iphone of my kid (some game give bonus when they watch video.) But I want block the porn filter I Add.

Is it possible to add the option in the clients to select the desired filters among those installed.

Thanks

**Comment by Insight16** [comment]
I would not have refused such a function :)

**Comment by ainar-g** [comment]
Hello.  This will be addressed in v0.108, so I'm merging this one into the overall refactoring and redesign issue, #2554.
