### ISSUE TITLE
Set the corresponding dns resolution server by subscribing to a specific domain name list

### ISSUE THREAD

**Issue by sxx1314** [AdguardTeam/AdGuardHome#3954]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

- [ v0.107.0-a.240+4be69d35] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

I can do this by adding specific dns settings, but there will be restrictions.

For example:
[/000webhost.com/]8.8.4.4:53

But ...
```
Error: control/dns_config | json Encode: attempted to read more than 65536 bytes | 400
```

### Proposed Solution

Set the corresponding dns resolution server by subscribing to a specific domain name list.
For example:

ChinaList | https://adguard.yojigen.tech/ChinaList.txt
GoogleHostsList | https://adguard.yojigen.tech/GoogleHostsList.txt
ChinaWhiteList | https://adguard.yojigen.tech/ChinaWhiteList.txt
ChinaBlackList | https://adguard.yojigen.tech/ChinaBlackList.txt

### Alternatives Considered

It can be set to read the second configuration file directly.

For example:
/opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -c2  /opt/adguardhome/conf/c2.yaml  -h 0.0.0.0

**Comment by ainar-g** [comment]
Hello.  Have you tried using [upstream files][1]?  There is no size limit there.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file

**Comment by fernvenue** [comment]
> Hello. Have you tried using [upstream files](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file)? There is no size limit there.

I don't think he did, he didn't even mark that he checked the documentation. I use [felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) on AdGuardHome like [this](https://github.com/fernvenue/adguardhome-upstream), that works good to me.
