### ISSUE TITLE
Porno,ads, and blocked services are coming though even thou blocked.

### ISSUE THREAD

**Issue by hlevy99** [AdguardTeam/AdGuardHome#3957]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * TP-LINK - DECO HC4
* **CPU architecture:**
  * Intel(R) Xeon(R) CPU E5-2430L
* **Operating system and version:**
  * )MV 5.x

### Expected Behavior
Porno sites, ads, and even blocked services should be blocked

### Actual Behavior
With filters turned on these types of sites are showing up on devices.

### Screenshots

<details><summary>Screenshot:</summary>
Dashboard
![image](https://user-images.githubusercontent.com/66905311/146648571-716d795a-8a2c-4ee6-95e3-c87e5f9e3056.png)

Showing Ebay services are blocked
![image](https://user-images.githubusercontent.com/66905311/146648511-0771e96b-7b5f-4fdc-bb55-82e39d8fc0e9.png)

ebay working.
![image](https://user-images.githubusercontent.com/66905311/146648539-057d086b-3c36-40a0-8720-a6d22572b823.png)

</details>

### Additional Information
This has been working for a while now but i am unsure because I use watchtower on which update allowed the content to not be blocked.

**Comment by Michel-0** [comment]
Works fine for me, when blocking "*EBay*" at the same config page like posted in your screenshot:
![image](https://user-images.githubusercontent.com/42518412/146650649-225e9682-5ca0-4e4e-8283-ab9670dcf5fc.png)
**eBay offline.**

So i guess there is something wrong with the DNS settings on your system. Either your router doesn't forward it properly to your docker system or your client has it's own DNS, not requesting DNS at your router.

**Comment by hlevy99** [comment]
Hey i see what happened. I didnt see that there was a secondary DNS added.
I removed the entry and its working again. Thanks for the quick response!

**Comment by Michel-0** [comment]
You're welcome... maybe mark the issue as solved now.

Btw. in my router i configured two DNS servers.
Primary is the AdGuard DNS, secondary is some public DNS (not AdGuard related).
So if my AdGuard Home Server is offline or shut down for some reason my network will stay online (non-ad-protected).
However as long as AdGuard Home is online, ad blocking works perfectly, altough there's a second DNS configured.
However on my AdGuard server i did not configure a secondary.

**Comment by EugeneOne1** [comment]
@hlevy99, I'll close the issue for now since it seems to be resolved.
