### ISSUE TITLE
DNS Over HTTPS fails when WAN IP Changes

### ISSUE THREAD

**Issue by LewisSpring** [AdguardTeam/AdGuardHome#3958]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.106.3
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * OpenWRT DHCP settings
* **If it's a router or IoT, please write device model:**
  * N/A
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 11 (Linux nuc 5.10.0-9-amd64 # 1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux)

### Expected Behavior
When the WAN IP address changes, DNS Over HTTPS resolution should continue.

### Actual Behavior
DNS queries are not resolved, they time out.
The Container needs restarting for DNS Resolution to continue.

### Screenshots

<details><summary>Screenshot of failed NSLookup:</summary>

![image](https://user-images.githubusercontent.com/40576482/146650443-e3aacd7f-c4a5-41e9-bd5e-ce76115d0f29.png)

</details>

### Additional Information
My PiHole running DNSCrypt-Proxy suffers from the same issue.
If I change the DNS AGH uses (before restarting the container, after WAN IP change), the issue does not fix. The container needs to be restarted.

The Docker container is bridged.
There are no apparent log entries.

**Comment by EugeneOne1** [comment]
@LewisSpring, hello.  The issue looks similar to #3217.  Could you please try one of the latest edge/beta builds and check if the issue reproduces there?

**Comment by LewisSpring** [comment]
Hi @EugeneOne1 , I didn't spot that one since It used different keywords.
I'll try it and get back to you.

**Comment by LewisSpring** [comment]
Good Evening @EugeneOne1 , seems like the latest Edge build has fixed the issue.
I've had some WAN changes and the resolution has continued.
When can I expect to see these fixes in a stable release?

Thanks for your help.

**Comment by ainar-g** [comment]
Either later today or tomorrow, if all goes to plan.
