### ISSUE TITLE
AdGuard Home & pixelsrv-tls

### ISSUE THREAD

**Issue by gspannu** [AdguardTeam/AdGuardHome#3959]
**Is there any guide for installing Pixelsrv along with AdGuardHome?**

There are articles/ links that discuss how to configure AdGuard Home to use pixelsrv, but _I cannot find anything that provides a guide to install pixelsrv_.

My setup is as follows:
- Debian 11 running on a VPS (in the cloud)
- AdGuard Home (Beta version) running on the Debian server
- AdGuard Home encryption enabled, https enabled. (I am using Lets Encrypt certificates for encryption, generated using certbot utility)
- AdGuard Home providing plain, DoT and DoH to connecting clients
- DoT on port 783, DoH on port 443, Plain DNS on port 53
- All others ports blocked via firewall

**Questions:**
- How do I install pixelsrv?
- Any **guides/ help/ links** to setup pixelsrv properly, so that it replaces both http and https ads with single pixel?

Objective:
Removing extra blank spaces in web pages.
</div>

**Comment by ainar-g** [comment]
Please don't open issues that duplicate Discussion topics.  Thanks.
