### ISSUE TITLE
Home Assistant Integration: enable entity_category: config for adguard setting entities

### ISSUE THREAD

**Issue by raidnet-ms** [AdguardTeam/AdGuardHome#3965]
## Problem Description

I suggest to adopt latest best practice to manage configuration entities in home assistant because actually there are too many undesired settings entities by default regarding adguard in the lovelace dashboard (and Google home or Alexa if they are configured).
### Proposed Solution

Hide most of unecessary default switches as recently outlined as best practice for entities using the "entity_category: config" parameter as described here: https://developers.home-assistant.io/blog/2021/10/26/config-entity/

**Comment by frenck** [comment]
This is a Home Assistant issue, not related to this project.
