### ISSUE TITLE
Does not work on port 53 when connecting WireGuard and OpenVPN clients

### ISSUE THREAD

**Issue by lbtboy** [AdguardTeam/AdGuardHome#3966]
AdGuardHome v0.106.3 & v0.107.0-b.15 OS Debian 10 (buster)

Здравствуйте.
AdGuardHome установлен на удаленном VPS настроен на порту 16553 и переадресацией с 53 порта на 16553 в UFW. Так же настроен на VPS сервер WireGuard и OpenVPN. При таких настройках все работает, при подключении к  WireGuard и OpenVPN с любых девайсов из любой точке страны.

![16553](https://user-images.githubusercontent.com/57795912/146765947-e6b55df4-035e-4289-849d-e6d3743a166a.png)
![ufw_16553](https://user-images.githubusercontent.com/57795912/146765950-8a476a27-9146-43e1-a52e-1eea150ced5b.png)
 
Решил настроить AdGuardHome на порту 53, что бы не было лишних переадресаций, проверил порт 53 свободен ` lsof -i -P -n` `lsof -i :53` настроил, отключил переадресацию в UFW.

![53](https://user-images.githubusercontent.com/57795912/146766462-2a89e534-da20-442c-98fe-d37dfed8ee09.png)
![ufw_53](https://user-images.githubusercontent.com/57795912/146766464-edf5ac05-64ba-4cef-bb68-4a4c5e013a47.png)

**Проблема заключается в том настроив AdGuardHome на порту 53 клиенты, девайсы подключаются к  WireGuard и OpenVPN, но интернета при этом нет. Подскажите в чем проблема, может что-то надо настроить дополнительно в AdGuardHome для того что бы на клиентах подключённых к  WireGuard и OpenVPN появился доступ к сети?** 

![Screenshot_20211220_175727](https://user-images.githubusercontent.com/57795912/146771977-75d94ba5-3848-4fd9-86d7-7348fec21cb0.jpg)
![Screenshot_20211220_175743](https://user-images.githubusercontent.com/57795912/146771979-9d791d06-d5b1-4ac6-9cb8-eb9af7437782.jpg)
![Screenshot_20211220_180133](https://user-images.githubusercontent.com/57795912/146771982-d1b7cd1e-00d7-4356-a1d5-86fcd5c49e79.jpg)

**Comment by ainar-g** [comment]
Добрый день.  А на каком адресе установлен AGH?  `10.9.0.1` — это точно он?

Можете ли вы с машин, на которых есть эта проблема, воспользоваться, например, `dig` и посмотреть, отображаются ли запросы в журнале?

(И ещё, вам лучше [сменить пароль][1], так как на ваших скриншотах его хэш.)

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset

**Comment by lbtboy** [comment]
> Добрый день. А на каком адресе установлен AGH? 10.9.0.1 — это точно он?

![Screenshot 2021-12-22 at 19-33-36 AdGuard Home](https://user-images.githubusercontent.com/57795912/147109105-710d6047-9a6b-44f4-b47e-997da3bda8af.png)


> (И ещё, вам лучше сменить пароль, так как на ваших скриншотах его хэш.)

Да ради Бога расшифровывайте сколько влезет, Вы думаете я настолько дурной что открыл Вам реальный хэш?

**Comment by ainar-g** [comment]
На вашем скриншоте AGH всё ещё слушает на 16553 порту.  Перед тем, как сменить порт в файле, вы останавливали AGH?

 >  Можете ли вы с машин, на которых есть эта проблема, воспользоваться, например, `dig` и посмотреть, отображаются ли запросы в журнале?

Этот вопрос всё ещё актуален.  Если что-то типа `dig 'example.com' @'10.9.0.1'` не сработает, то возможно там есть ещё какие-то правила файервола.

**Comment by lbtboy** [comment]
> На вашем скриншоте AGH всё ещё слушает на 16553 порту. Перед тем, как сменить порт в файле, вы останавливали AGH?

Ну что за глупый вопрос, конечно же останавливал и конечно же перзапускал и конечно же делал stop и start.

**Вы наверное не поняли задач,и на порту 16553 с переадресацией с 53 поэтому нет необходимости в `dig`. А если настроить на порту 53 не работает, верней работает так, подключение к WG и OpenVPN, а интернета нет на клиенте!**

**Comment by ameshkov** [comment]
Не очень понятно, как мы вообще можем на что-то влиять.

AG просто слушает на указанном порту, никаких дополнительных преобразований он не делает. Кроме фаервольных правил у нас идей нет. Судя по таймауту в браузере, пакеты до нас не доходят.

Если хотите проверить, доходит ли хоть что-то, в AdGuardHome.yaml можно включить уровень логгирования `verbose: true` и посмотреть, приходит ли хоть что-то.

**Comment by lbtboy** [comment]
Почему так на 16553, а на 53 нет может что то в ADH надо настроить в AdGuardHome.yaml прописать? 

> Кроме фаервольных правил у нас идей нет.

Какие идеи на этот счёт, поделитесь.

**Comment by ameshkov** [comment]
> Почему так на 16553, а на 53 нет может что то в ADH надо настроить в AdGuardHome.yaml прописать?

`AdGuardHome.yaml` по сути это та же конфигурация, что вы в веб-админке настраиваете + несколько дополнительных настроек, которые UI не выведены. Для портов там ничего особенного нет.

> Какие идеи на этот счёт, поделитесь.

Тяжело предполагать не имея возможности пощупать и посмотреть.

Проверьте iptables-save, попробуйте по очереди поудалять правила. Ну и проверьте на всякий случай что редирект правила действительно были убраны и iptables был релоаднут с новыми правилами.

**Comment by lbtboy** [comment]
> Проверьте iptables-save, попробуйте по очереди поудалять правила. Ну и проверьте на всякий случай что редирект правила действительно были убраны и iptables был релоаднут с новыми правилами.

Это было все проделано в первую очередь, результан нулевой. Фаервол вообще пробовал отключал.

> Тяжело предполагать не имея возможности пощупать и посмотреть.

Что вам для этого нужно и вообще возможно ли?

**Comment by ameshkov** [comment]
> Что вам для этого нужно и вообще возможно ли?

Рут:) Но вообще у меня, к сожалению, не так много свободного времени.

Давайте для начала проверим, проблема эта вашего конфига или мы со стороны AGH можем чем-то помочь.
Если просто dnsmasq запустить на 53 порту, проблема та же возникает?

**Comment by lbtboy** [comment]
> Если просто dnsmasq запустить на 53 порту

dnsmasq где на сервере где установлен ADH, если да то там его нет и не был ни когда установлен, только служба systemd-resolved которая тоже ни когда не запускалась и не включена.
