### ISSUE TITLE
A few questions before setting it up

### ISSUE THREAD

**Issue by anudeepND** [AdguardTeam/AdGuardHome#397]
### Steps to reproduce
N/A

### Expected behavior
N/A

### Actual behavior
N/A

I came to know about Adguard Home from a post in [hacker news](https://news.ycombinator.com/item?id=18238503), there it's mentioned that
`AdGuard Home has the same software under the hood as we use for our public AdGuard DNS servers (which are quite popular) so it is ready for the heavy load.`

And in the GitHub wiki under [VPS](https://github.com/AdguardTeam/AdGuardHome/wiki/VPS)

`you can use it on your machine by changing system DNS settings to use your VPS's public IP address.`

So are we taking about opening up our DNS server to the whole internet? What are the risks of DNS amplification attacks?

Also,
Its mentioned that:
`It understands adblock rules syntax, so you don't need 10k lines hosts files to block doubleclick subdomains.`

AdGuard Home will also support [this](https://easylist.to/easylist/easylist.txt) kind of rulesets? 

Is it a standalone DNS resolver? Or is it dependent on upstream DNS servers?

Cheers,
Anudeep

**Comment by dfmcvn** [comment]
If you don't want your server public to the internet, just 
```
sudo iptables -I INPUT -p tcp ! -s 1.2.3.4 --dport 53 -j DROP
sudo iptables -I INPUT -p udp ! -s 1.2.3.4 --dport 53 -j DROP
```
Replace 1.2.3.4 with your IP address

Or simply listen only on LAN network.

**Comment by dfmcvn** [comment]
>is it dependent on upstream DNS servers?

Yes, imagine it works like an proxy server for DNS traffic.

**Comment by dfmcvn** [comment]
>is it dependent on upstream DNS servers?

Yep, imagine it works like a proxy server for DNS traffic.
