### ISSUE TITLE
Client ID cannot contain capital letters

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#3971]
### Actual Behavior

I cannot use capital letters downloading a DNS profile or adding a Client ID
### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/146930497-6d79037f-889d-4d80-853c-bea56a9bc7fb.png)

</details>

**Comment by ammnt** [comment]
@Chinaski1, already reported by me before, but no success:
https://github.com/AdguardTeam/AdGuardHome/issues/2616
😞

**Comment by ainar-g** [comment]
@ameshkov, do we really still want to retain that behaviour?  If so, maybe we should at least make the error message clearer?

I personally don't think that we should prevent users from using uppercase ClientIDs as long there is an understanding that all comparisons are still done in a case-insensitive manner.

**Comment by ameshkov** [comment]
@ainar-g 
I'd prefer a clearer error message that explains which characters are allowed.

**Comment by ainar-g** [comment]
We've pushed a commit with a more informative error message.  I guess this issue can be closed then.
