### ISSUE TITLE
Show which IP addrs are duplicated in error messages

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#3975]
* **Version of AdGuard Home server:**
  *  v0.107.0
* **How did you install AdGuard Home:**
  *   GitHub releases
* **How did you setup DNS configuration:**
  *  System
* **Operating system and version:**
  *  Windows 10, Windows Server
### Screenshots
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46345396/146970371-e5b23b6c-ab32-4b16-b6c4-ab39ad790495.png)

</details>

Вы можете оставьте проверку дубликатов и выводить уведомления но при этом чтоб была возможность все равно сохранять сохранения в "Запрещённые клиенты" потому что у меня заблокированных IP 9311 в CIDR диапазоне но при этом не все они в CIDR диапазоне и скорее всего что то там не позволяет это сделать а искать это не реально.. 
В v.106.3 такого не было и все работало как нужно.. Временно возвращаюсь на v.106.3

**Comment by Eyeborgs** [comment]
Ну или в Крайнем случае пускай уведомляют какие IP конфликтуют но только не в CIDR диапазоне..

**Comment by ainar-g** [comment]
@Eyeborgs, на канале `edge` мы улучшили валидациционное сообщение:

![Screenshot from 2021-12-28 16-17-08](https://user-images.githubusercontent.com/4964986/147578507-2e12e1f6-bccf-4930-a2f4-acc8355953ae.png)

Вы можете протестировать, работает ли это в вашем случае?  Или можете подождать релиза, так как релиз 0.107.1 должен выйти в ближайшие дни.

**Comment by Eyeborgs** [comment]
@ainar-g Протестировал и вроде как работает нашел три дубликата но странно то что я удалил один дублирующий IP и сохранил настройки а два оставил и он перестал выводить ошибку что есть дубликаты и просто успешно все сохранял - такое ощущение что после первого удаленного дубликата эта система просто переставала работать ну проверять и просто сохраняла значения

**Comment by ainar-g** [comment]
@Eyeborgs, спасибо за проверку!

 >  странно то что я удалил один дублирующий IP и сохранил настройки а два оставил и он перестал выводить ошибку что есть дубликаты и просто успешно все сохранял

Мы не можем это воспроизвести, к сожалению.  Если у вас эта проблема стабильно воспроизводится, откройте, пожалуйста, новый тикет с описанием шагов.
