### ISSUE TITLE
Current update 1.07 refuses to use previous .yaml

### ISSUE THREAD

**Issue by BigBobDalton** [AdguardTeam/AdGuardHome#3979]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details
I tried to manually upgrade the newest version (arm6) to my Raspberrypi this morning, however when just adding the new executable the application will not start.  Error 1, and checking the log file it indicates that port 3000 is already in use.

When I run the command 

sudo losf -i tcp:3001

it returns nothing, meaning the port is not in use.  Rebooting does not solve the issue.

If I delete the .yaml file,  then Adguard starts a new installation, completion of that installation still does not create a new Adguard.yaml file

~/AdGuardHome $ sudo ./AdGuardHome 
2021/12/22 10:00:54.757730 [info] AdGuard Home, version v0.107.0
2021/12/22 10:00:54.778863 [error] parsing configuration file: port 3001 is already used

Am I missing something?

**Comment by EugeneOne1** [comment]
@BigBobDalton, hello and thanks for the report.  This is definitely a bug introduced in #3835.  We're going to fix it in the nearest future.

**Comment by EugeneOne1** [comment]
@BigBobDalton, I suppose, you have the same value of `3001` in the `beta_bind_port` setting.  As a temporary workaround, you may change it to `0`.

**Comment by BigBobDalton** [comment]
Yes, that worked perfectly.

Thanks 👍

> BigBobDalton, I suppose you have the same value of `3001` in the `beta_bind_port` setting. As a temporary workaround, you may change it to `0`.

**Comment by EugeneOne1** [comment]
@BigBobDalton, after a little investifation I can say it's actually an intended behavior since any value except of `0` in `beta_bind_port` enables the additional beta server so it should also be checked.  Sorry for confusing.
