### ISSUE TITLE
Since v0.107.0 requests to adguard host rewritten to 127.0.0.1

### ISSUE THREAD

**Issue by firebowl** [AdguardTeam/AdGuardHome#3986]
Sind update to v0.107.0 I cannot connect to adguard via DNS name.
In the Query Log I see that the requests got rewritten to 127.0.0.1:

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.0
* **How did you install AdGuard Home:**
Install script from GitHub
* **How did you setup DNS configuration:**
Proxmox installed on Intel NUC
* **CPU architecture:**
INTEL / AMD64
* **Operating system and version:**
Ubuntu 21.10

### Expected Behavior
AdGuard UI should open via DNS.

### Actual Behavior
AdGuard DNS Request is rewritten to 127.0.0.1

### Screenshots
![image](https://user-images.githubusercontent.com/73579226/147127142-29f7f5ec-d018-4d23-8fe3-7162dbeadc5b.png)

**Comment by ainar-g** [comment]
Hello.  It seems like your `/etc/hosts` file has this record for `adguard.fritz.box`.  In v0.107.0, rewrites have a higher priority, including the `/etc/hosts` ones.  You should probably either delete these entries or edit them.

**Comment by firebowl** [comment]
That's it...Thank you!
![image](https://user-images.githubusercontent.com/73579226/147147172-51ff1953-e70a-493e-95e6-daed92cdfd2a.png)
Now it's working again.
Perhaps this should be described when the standard behavior has changed. I have not created the entry in the hosts by hand.

**Comment by ainar-g** [comment]
We'll try to make that more noticeable in the release notes, thanks!
