### ISSUE TITLE
after update to 107

### ISSUE THREAD

**Issue by Loki954** [AdguardTeam/AdGuardHome#3990]
after update to 107 the nothing is blocked . all statistic in dashboard is 0
i reinstall from "scratch" same thing. 
i run it on raspberry pi 4

**Comment by gspannu** [comment]
> after update to 107 the nothing is blocked . all statistic in dashboard is 0
> i reinstall from "scratch" same thing.
> i run it on raspberry pi 4

Please post your yaml file - so someone can have a look at your settings?

**Comment by ainar-g** [comment]
Please fill out the whole issue template, and specify how you installed AGH.  You should also enable [verbose logs][1] to make sure that you see all warnings and errors in the logs.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Loki954** [comment]
now i format the sd card, reinstall the rapberry os and install again and all good. Maybe the update messed up the os ...can't tell but all good now. Thank you for your time !!! BR
