### ISSUE TITLE
DNS rewrites are not working correctly since upgrading to v0.107

### ISSUE THREAD

**Issue by ducksuflay** [AdguardTeam/AdGuardHome#4003]
* **Version of AdGuard Home server:**
v0.107.0

* **How did you install AdGuard Home:**
Installed using the Raspberry Pi guide (https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi)

* **How did you setup DNS configuration:**
The Raspberry Pi is my router and DNS server (configured as 192.168.0.1 for DNS through DHCP)

* **If it's a router or IoT, please write device model:**
Raspberry Pi 4 Model B Rev 1.4

* **CPU architecture:**
ARMv7 Processor rev 3 (v7l)

* **Operating system and version:**
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

### Expected Behavior
DNS rewrites added should resolve to the internal (manually added) IP address when queried internally instead of the external IP address configured for that domain.

### Actual Behavior
DNS rewrites are no longer happening since upgrading to v0.107. I have two external domains that should resolve to my internal NAS but now resolve externally. This is happening across all my devices, not just the Mac that I'm testing on. All other AdGuard functionality appears to be working as expected.

**ping resolves to external address**

_Last login: Fri Dec 24 10:16:02 on ttys000
xxxxxxx@xxxxxx-iMac ~ % ping diskstation.xxxxxxxxx
PING xxxxxxx.xxxxxx.me (86.x.x.x): 56 data bytes
64 bytes from 86.x.x.x: icmp_seq=0 ttl=64 time=16.184 ms
64 bytes from 86.x.x.x: icmp_seq=1 ttl=64 time=12.914 ms
64 bytes from 86.x.x.x icmp_seq=2 ttl=64 time=9.114 ms
64 bytes from 86.x.x.x: icmp_seq=3 ttl=64 time=13.987 ms
--- xxxxxxx.xxxxxxx.me ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 9.114/13.050/16.184/2.560 ms_

**nslookup resolves internally**

xxxxxx@xxxxxx-iMac ~ % nslookup diskstation.xxxxxxxx
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	diskstation.xxxxxxxx
Address: 192.168.0.2

**Mac DNS configured to point to Router only**

_xxxxxxx@xxxxx-iMac ~ % cat /etc/resolv.conf                
search router.local
nameserver 192.168.0.1_

### Screenshots

<img width="727" alt="Screenshot 2021-12-24 at 10 40 31" src="https://user-images.githubusercontent.com/96617901/147348314-f121d7ab-a38d-4d30-8918-26c2fbaae433.png">

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Hello and thank you for the report!  A few questions to help us reproduce the issue:

1.  I've noticed that your second rewrite is an FQDN (ends with a dot).  Does the `diskstation` one also end with a dot?  Does it work if you remove it?

2.  If I understand the situation correctly, `ping` resolves the wrong IP, while `nslookup` resolves the correct one?  If so, do you see requests from this client in the query log when using `ping`?

3.  Are the other devices also Apple devices or are there other OSes?

4.  Does it work if you replace these rewrites with the newer [`$dnsrewrite`][1] rules?  Like:

    ```none
    ||diskstation.xxxx^$dnsrewrite=NOERROR;A;192.168.0.2
    ```

Thanks!

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by ducksuflay** [comment]
Hi, thanks for the quick response.

1. I've masked the final part of the address as it's my personal domain. It is something like this: diskstation.mypersonaldomain.com. I've just blanked the rest out as per the IP addresses in the ping etc.
2. I don't appear to see anything in the log for the ping however I do see the valid rewrite in the log
<img width="324" alt="Screenshot 2021-12-24 at 11 51 21" src="https://user-images.githubusercontent.com/96617901/147350457-c441cb62-3bc1-48f9-b90d-b3c3815fc130.png">
3. I've just tested it on my windows machine and it resolves correctly (192.168.0.2). I have tried to clear all cache on the Mac but it still doesn't work. It just seems odd that it stopped resolving correctly at the same time as the upgrade. I've also ensured I've turned off all iCloud Private Relay so the "VPN" isn't getting in the way.
4. I'll try the new rewrite rule now.

**Comment by ducksuflay** [comment]
For 4. I'm assuming I add this in the Custom Filtering Rules section?

**Comment by ducksuflay** [comment]
So I get this for the Mac

Response details
Status
Rewritten
Elapsed
0.05 ms
Response code
NOERROR
Response
A: 192.168.0.2 (ttl=10)

and this for the Windows device

Response details
Status
Rewritten
Elapsed
0.45 ms
Response code
NOERROR
Rule(s)
||mydomainhere.com^$dnsrewrite=NOERROR;A;192.168.0.2
Custom filtering rules
Response
A: 192.168.0.2 (ttl=10)

**Comment by ainar-g** [comment]
Thanks for all the data!

Yes, these rules go to the “Custom Filtering Rules” page.  If non-Apple platforms as well as `nslookup` work as before, then I assume that it could be something related to `ping` on macOS.

The discrepancy between the two looks very weird.  Do you have any sort of separate client settings for those devices?  Perhaps protection or filtering is disabled for one of them?

**Comment by ducksuflay** [comment]
Interesting, I've added the rewrites back in to the standard GUI and they now work again (I removed them to add the custom rewrite rules). Ping resolves correctly...

**Comment by ainar-g** [comment]
Perhaps it is an issue with DNS caches not being flushed in some ways?  I've asked around, and it seems like discrepancies in the way `ping` and `nslookup`/`dig` resolve hosts aren't unheard of on the macOS.  They say that a reboot or `dscacheutil -flushcache` helps sometimes but not always.

**Comment by ducksuflay** [comment]
Yea, tried a reboot and cache flush. Odd that it I experienced exactly the same thing on my iPad and iPhone. All are now working as expected.

**Comment by ainar-g** [comment]
@ducksuflay, are there any issues now?  We've pushed a new version to the `edge` channel that changes some of the behaviour of rewrites to be closer to v0.106.3, so if the issues return, you should probably try and update to the `edge` version or wait for v0.107.1, which should probably be out some time next week.

**Comment by ducksuflay** [comment]
All appears to be working correctly now. Thanks.
