### ISSUE TITLE
DNS Rewrite configuration

### ISSUE THREAD

**Issue by KGBist2000** [AdguardTeam/AdGuardHome#4009]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Problem Description

1. when for one domain different DNS records are needed, in V0.106.3 and V0.107.0 the client has to be documented several times.

e.g. 
- test.domain.de -> 10.0.0.1
- test.domain.de -> fd00::1

2. Possibility to sort and to edit the entries

### Proposed Solution

1. implementation of a submenu for each domain to be able to define a set of records to have only one entry in the table.
2. button for sorting with drag and drop and an edit button for each entry

**Comment by ainar-g** [comment]
1.  You may be interested in [`$dnsrewrite` rules][1], which you can edit in your text editor of choice and then just pasted into the “Custom filtering rules” input.  In fact, the current (legacy) DNS rewrites mechanism is going to be merged with the `$dnsrewrite` one at some point, see #2499.  And this format also accepts comments.

2.  That is actually already planned in the new design.  The metaissue about that is #2554.

I'm going to merge this issue into the latter, if you don't mind.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite
