### ISSUE TITLE
Update Installation Steps on the Wiki for Ubuntu 18.04

### ISSUE THREAD

**Issue by dimasahmad** [AdguardTeam/AdGuardHome#401]
Please update [the Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/VPS) with additional steps to disable dnsmasq on ubuntu 18.04, since it's listening on port 53 and preventing AdGuardHome to run.

Reference: https://mmoapi.com/post/how-to-disable-dnsmasq-port-53-listening-on-ubuntu-18-04

**Comment by mderazon** [comment]
This is what worked for me in Ubuntu 18.10
https://askubuntu.com/a/907249/253516

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/685
