### ISSUE TITLE
Upstream DNS server still used when clients are served from cache

### ISSUE THREAD

**Issue by Iceman248** [AdguardTeam/AdGuardHome#4015]
Is this behavior as designed? I've noticed the vast majority of DNS queries are from cache, yet I still get seemingly all or at least most of those queries showing up in my upstream DNS server log.

**Comment by agneevX** [comment]
The listed DNS server is the one where the records are **originally from**.

**Comment by Iceman248** [comment]
I understand that, but if I look in the upstream DNS servers log, I still see it there, so adguard home must have still sent the query upstream even though it served my client from the cache. I just didn't understand why it was still send it upstream if it was serving my client from the cache.

**Comment by agneevX** [comment]
#3995 should cover queries like this.

**Comment by EugeneOne1** [comment]
@Iceman248, as **agneevX** correctly noticed in the referenced issue, the current optimistic cache documentation is far from perfect.  Most probably our implementation confuses you with refreshing expired cache entries in background.  Have you got the **Optimistic caching** setting enabled.

**Comment by Iceman248** [comment]
Optimistic cache was on, but even after turning off, it seems exactly the same. There definitely wasn't any less upstream DNS queries. There were more uncached responses from AGH to my clients. That is the only difference I noticed.

**Comment by EugeneOne1** [comment]
The answers that became uncached are the ones that resolved explicitly now.  The upstream server is used in any case regardless of wether the optimsitic cache is enabled or disabled since entries are expiring over time.

What is your question exactly about?  If you want to decrease the number of requests to the upstream server, you may try increase the **Cache size**.  You may also use **Override minimum TTL** to rewrite the TTL of responses and make AGH cache it for a longer time.

**Comment by Iceman248** [comment]
Understood. Thanks.

I just found it odd that it still kept going upstream when it was using cached results, but now I understand that is by design.

Ideally, I would minimize some of the upstream queries, which is why I did increase cache and set overrides. Here are my settings that I've had for quite some time. Should I make them higher?

Cache size
DNS cache size (in bytes)
**8388608**
Override minimum TTL
Extend short time-to-live values (seconds) received from the upstream server when caching DNS responses
**3600**
Override maximum TTL
Set a maximum time-to-live value (seconds) for entries in the DNS cache
**86272**

**Comment by EugeneOne1** [comment]
Optimal values for these settings are mostly chosen empirically.  Keep in mind that responses with TTL overriden with a bigger value have a higher probability to stay outdated longer.  This is about the balance between refreshing upstream requests number and the actual data recency.

I'll close the issue for now if you don't mind.  Please consider using Github's **Discussions** section for questions like this.

**Comment by donald2612** [comment]
> What is your question exactly about? If you want to decrease the number of requests to the upstream server, you may try increase the **Cache size**. You may also use **Override minimum TTL** to rewrite the TTL of responses and make AGH cache it for a longer time.


Excuse me, can I chime in here? What is found by the OP, is that exactly that behaviour you describe is simply not working. That leads to the upstream servers always asked regardless of served from cache or not.

I have checked upstream logs with adguards logs, to double-check that.
