### ISSUE TITLE
DNS rewrites don't work with subdomains of the same domain

### ISSUE THREAD

**Issue by hauntedghost** [AdguardTeam/AdGuardHome#4016]
I'm looking for a way to setup DNS redirects from amazon.com to smile.amazon.com. 
I currently have a DNS Rewrite setup with the following settings and the redirect is not sending me to the correct URL.
![dns_redirect](https://user-images.githubusercontent.com/22357763/147388408-b0174623-5282-4ab3-9452-3aa139cbf752.png)

**Comment by agneevX** [comment]
Because that's not how DNS works? It allows you to set a custom IP, not a host name.

**Comment by ZeroClover** [comment]
Because that's not what a DNS server should do.

To do what you want, you need to run an HTTP server, then install your own Root CA for all clients in your network to implement MitM, and then resolve amazon.com to your HTTP server. Finally configure the HTTP Server to send HTTP redirects (HTTP 301 / 302 / 307 / 308).

**Comment by hauntedghost** [comment]
Understood. I guess I thought that would be the function of the dns server
to forward the request to smile.amazon vs Amazon since Adguard home is a
proxy server.
Appreciate your help. I'll look into the mitm proxy.

**Comment by EugeneOne1** [comment]
@hauntedghost, hello and thanks for the report.  Looks like a bug actually.  Consider using `||amazon.com^$dnsrewrite=NOERROR;CNAME;smile.amazon.com` custom rule as a temporary workaround.

**Comment by ainar-g** [comment]
The others are correct in their recommendations about the HTTP redirects, but the fact that a `*.amazon.com → smile.amazon.com` doesn't result in clients getting the correct `CNAME` of `smile.amazon.com` is definitely a bug.  Will fix.

**Comment by ainar-g** [comment]
The issue with the incorrect CNAME rewrite to a subdomain should now be fixed on the `edge` channel.  Once again, thanks for the report!
