### ISSUE TITLE
Nothing blocked

### ISSUE THREAD

**Issue by trhdon123** [AdguardTeam/AdGuardHome#402]
### Steps to reproduce

1. Successfully launch and add third-party filters.
2. Open dashboard page of AGH in browser.
3. Open a website full of ads eg. `https://www.dailymail.co.uk/home/index.html`

### Expected behavior

Ads should be blocked like demo gif from Adguard blog.
### Actual behavior

Nothing blocked. Tried with some other websites I get the same result. With all those filters I've added but using adblock extension in browser, ads are mostly blocked.

<details><summary>Screenshot:</summary>

Launch successfully.
![screenshot from 2018-10-19 08-28-32](https://user-images.githubusercontent.com/20873969/47192734-08fb7180-d379-11e8-9b96-6b2263489e3c.png)

Nothing blocked. Also refresh dashboard to check and nothing in statistic.
![screenshot from 2018-10-19 08-08-20](https://user-images.githubusercontent.com/20873969/47192689-d3568880-d378-11e8-9ae4-99f4c8f3ba01.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9-hotfix1
| How did you setup DNS configuration:| IPv4 via system settings: Cloudflare 1.1.1.1 and Google DNS 8.8.8.8
| If it's a router or IoT, please write device model:| none
| Operating system and version:| ElementaryOS 5.0 (Ubuntu 18.04 based)

**Comment by dfmcvn** [comment]
Try flushing DNS cache at `chrome://net-internals/#dns`.
Idk if Vivaldi can use this link, or maybe `vivaldi://net-internals/#dns`.

**Comment by trhdon123** [comment]
Unfortunately no method suggested by @ewrogers and @dfmcvn works :(
What I've done:
1. Flush system DNS cache: `sudo systemd-resolve --flush-caches`
2. Flush browser DNS cache:
    - Firefox:
        - Clear cache using browser's built-in tool
        - Set `network.dnsCacheExpirations` to `0` in Firefox's `about:config`
        - Exit browser
        - Run third-party tool (bleachbit) to clear system and browser cache
        - Set `network.dnsCacheExpirations` back to default `60`
    - Chromium same as Firefox but clear cache in `chrome://net-internals/#dns`

**Comment by ameshkov** [comment]
@trhdon123 hi! could you please just in case disable all the additional filters and keep the AdGuard SDN filter alone? I am afraid that AG might be misinterpreting some of the exception rules (those starting with `@@`) in easyprivacy/easylist.

**Comment by trhdon123** [comment]
doesn't worked.
![screenshot from 2018-10-19 15-51-02](https://user-images.githubusercontent.com/20873969/47208016-f30ca180-d3b6-11e8-883a-6f0b5d89f90f.png)

**Comment by ameshkov** [comment]
I just realized that we're troubleshooting it wrong way:)

First of all, please open a terminal/cmd and run this command:
```
nslookup ad.doubleclick.net AG_HOME_IP_ADDRESS
```

You should see something like this:
```
$ nslookup ad.doubleclick.net 192.168.7.2
Server:		192.168.7.2
Address:	192.168.7.2#53

** server can't find ad.doubleclick.net: NXDOMAIN
```

**Comment by trhdon123** [comment]
I got this
`nslookup: couldn't get address for 'AG_HOME_IP_ADDRESS': failure`

**Comment by ameshkov** [comment]
You need to replace AG_HOME_IP_ADDRESS with the real IP address you used for configuring the DNS server

**Comment by dfmcvn** [comment]
![image](https://user-images.githubusercontent.com/22710598/47210633-aa0c1b80-d3bd-11e8-9f47-dc8785849cdf.png)

then sth went wrong with your dns server, the result should looks like this

**Comment by dfmcvn** [comment]
> I noticed the number 53. I set mine as 2048. Should that be considerable?

Oh, 53 is default DNS port, you should leave it as is.

**Comment by trhdon123** [comment]
> > I noticed the number 53. I set mine as 2048. Should that be considerable?
> 
> Oh, 53 is default DNS port, you should leave it as is.

Hmm I read the install instructions that I could change the port after first launch to be able to launch AGH without root permission. Don't remember if things worked in first launch. Lemme change it back.

**Comment by trhdon123** [comment]
Interesting I couldn't launch AGH with port 53 anymore. I've done it successfully since release 0.9.
Console says port 53 is being used [properly by system dns process]. Even the use of `sudo` doesn't help.

**Comment by dfmcvn** [comment]
Does the command `netstat -ntlup | grep 53` show up anythin?

**Comment by dfmcvn** [comment]
```
pkill systemd-resolved
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
```
then
```
pkill AdGuardHome
pkill coredns
./AdGuardHome
```
[Sauce.](https://askubuntu.com/questions/898605/how-to-disable-systemd-resolved-and-resolve-dns-with-dnsmasq)

**Comment by trhdon123** [comment]
Finally it works. Thanks a lot @dfmcvn

**Comment by dfmcvn** [comment]
I think you can close this issue now @ameshkov 
Chúc bác một ngày vui vẻ @trhdon123

**Comment by ameshkov** [comment]
@dfmcvn thank you so much!
