### ISSUE TITLE
Failed to install edge version

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#4027]
### Issue Details

* **Version of AdGuard Home server:** current Edge(27.12.2021 18:30)
* **How did you install AdGuard Home:** GitHub release
* **How did you setup DNS configuration:**
* **If it's a router or IoT, please write device model:** Synology DS214play(Intel)
* **CPU architecture:** i386
* **Operating system and version:** Synology DSM(linux-based)

### Actual Behavior

Got following error after password configuration. Old config was removed.

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/8361299/147492800-f13409fd-56b1-4c2f-91a4-f3832127d94b.png)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://user-images.githubusercontent.com/8361299/147492925-665c61bb-f5a1-444f-8c59-b84d397332c7.png)

</details>

**Comment by ainar-g** [comment]
Should be fixed on the `edge` channel.  Could you please check?
