### ISSUE TITLE
Version not showing in shell

### ISSUE THREAD

**Issue by scebbers** [AdguardTeam/AdGuardHome#4030]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.107
* **How did you install AdGuard Home:**
  * pkg install (freeBSD package manager)
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * FreeBSD 12.2 jail on FreeNAS

### Expected Behavior
When doing ./adguardhome -v --version or ./adguardhome --version it should report the version number.

### Actual Behavior
Result:
```
root@adguard:/usr/local/bin # ./adguardhome -v --version
AdGuard Home
Version:
Channel: development
Go version: go1.17.1
GOOS: freebsd
GOARCH: amd64
...
```

**Comment by ppfeufer** [comment]
Seems to work on `arm64`

![image](https://user-images.githubusercontent.com/2989985/147563356-ad4bed64-a87c-416b-86f6-d9dfaca9d4fa.png)

**Comment by ainar-g** [comment]
Hello.

 >  pkg install (freeBSD package manager)

It's probably an issue with the package.  We cannot reproduce that with our official binaries from the [Releases page][1].  Please refer to the package maintainers.

[1]: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.0
