### ISSUE TITLE
DNS rewrite TTL not comply with Override minimum TTL

### ISSUE THREAD

**Issue by xndby** [AdguardTeam/AdGuardHome#4035]
* **Version of AdGuard Home server:**
0.107.0
* **How did you install AdGuard Home:**
GitHub releases
* **How did you setup DNS configuration:**
System
* **CPU architecture:**
AMD64
* **Operating system and version:**
OpenWRT

### Expected Behavior
DNS rewrite TTL is expected to be consistent with Override minimum TTL

### Actual Behavior
DNS rewrite TTL is always 10s. No configuration option is available to adjust it.

### Screenshots
N/A

### Additional Information
N/A

**Comment by EugeneOne1** [comment]
@xndby, hello.  Responses rewritten by `dnsrewrite` modifier are treated as blocked so you may assign the value for their TTL with `blocked_response_ttl` in `AdGuardHome.yaml` configuration file.  Note that this will also change TTL of all filtered respones.

**Override minimum TTL** setting only affects unfiltered responses and is primarily used to store those in cache for a longer time.

**Comment by ainar-g** [comment]
Just as an info, we're having more and more people wishing for a more fine-grained control of the TTL, including the recent discussion #4018 and several issues.  We will need to see if there is something to be done about it.

**Comment by rahulmangaldas** [comment]
I agree, rewrites need a separate TTL

**Comment by mada199122** [comment]
me too... please

**Comment by RainmakerRaw** [comment]
Reopening to save duplicating the issue (I hope that's OK). I have over 47,000 requests blocked to `logs.netflix.com` today on our busy home network. I have split DNS (LAN IP versus static WAN IP) on my servers, so I'm forced to set TTL to 10 for blocked requests. This in turn impacts rewrites, so clients can switch between local and public IPv4 space within 10s of leaving the home network, and DNS and my other servers continue to work and resolve. Being able to set rewrites to 10s and blocked to 3600 would greatly quiet my traffic and logs. Is this still being considered? Thanks in advance.
