### ISSUE TITLE
CPU takes up 100%

### ISSUE THREAD

**Issue by keyangfeng01** [AdguardTeam/AdGuardHome#4039]
AdGuard Home. Version:. v0.108.0-a.20+380cff07，CPU takes up 100% of the problem that only appears in this version. I hope to fix this BUG as soon as possible.

**Comment by keyangfeng01** [comment]
![54CB1E4A-9B84-4553-B2A8-2945D5F9764B](https://user-images.githubusercontent.com/96828139/147667762-4c8da28e-56a5-470c-955f-f5df3126d3cb.png)

**Comment by EugeneOne1** [comment]
@keyangfeng01, hello.  Could you please collect [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) to help us troubleshoot the issue?  You may post it here or send to the devteam@adguard.com.

**Comment by keyangfeng01** [comment]
Hello, what should I do to grab the log file?

**Comment by keyangfeng01** [comment]
@ EugeneOne1

**Comment by EugeneOne1** [comment]
@keyangfeng01, firstly, how did you install the AGH?  The way to grab the logs usually depends on it, but I've left the link to the instructions on how to do it in previous answer.

**Comment by keyangfeng01** [comment]
Installed
 #Linux x64
wget https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_amd64.tar.gz -O AdGuardHome.tar.gz

Subsequent upgrades are automatically detected as updated

I am a student from China, my English level is average, and I can't understand the help document.

I hope you can help me find the relevant operation method.

I tried to restart the server and still couldn't fix the problem.

**Comment by keyangfeng01** [comment]
EugeneOne1

**Comment by EugeneOne1** [comment]
@keyangfeng01, you're welcome to use any language you're comfortable in.

To begin with, stop AdGuard Home.  Then open the `AdGuardHome.yaml` file and change the following lines:

 *  Set `log_file` to the path to write log into.  Note that it should be a file, not directory.
 *  Set `verbose` to `true`.

**Comment by keyangfeng01** [comment]
I tried to kill the process and it came back to normal, thanks for your help

**Comment by EugeneOne1** [comment]
@keyangfeng01, well, I'll close the issue for now.  Reopen it if the problem repeats.

**Comment by karuboniru** [comment]
I am having same problem, with version `v0.108.0-a.20+380cff07` (docker newest edge image), the problem of excessive CPU usage happens randomly after long running (several hours I think) and remains that.

I will do a log capture when have time to do so but please remain the issue open?

**Comment by ainar-g** [comment]
@karuboniru, we're now investigating it in #4042.  We're planning to release a fix later today.
