### ISSUE TITLE
Nest Support

### ISSUE THREAD

**Issue by egarciarivera** [AdguardTeam/AdGuardHome#404]
### Steps to reproduce

Nest application (from iOS) won't connect, keeps spinning waiting for a response. This only happens when the DNS in the router is set to AdGuard Home. The following filters don't fix the issue:

@@||nest.com^
@@||home.nest.com^
@@||https://home.nest.com^

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9
| How did you setup DNS configuration:| Router DNS
| If it's a router or IoT, please write device model:| Google Wifi
| Operating system and version:| MacOS Mojave

**Comment by dfmcvn** [comment]
I don't see Adguard block Nest's domain. Do you find any others reason may occur this error?

```
[root@vps192xxx home]# nslookup home.nest.com 139.99.xx.xxx
Server:         139.99.xx.xxx
Address:        139.99.xx.xxx#53

Non-authoritative answer:
home.nest.com   canonical name = vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com.
Name:   vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com
Address: 52.44.228.61
Name:   vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com
Address: 52.200.91.244
Name:   vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com
Address: 34.235.44.226
Name:   vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com
Address: 52.203.188.182
Name:   vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com
Address: 34.225.250.123
Name:   vhome-hme01-production-1616512027.us-east-1.elb.amazonaws.com
Address: 54.165.253.56
```

**Comment by egarciarivera** [comment]
The Nest itself connects to the internet fine, and even Homebridge is working, but the app won't connect. In the log I can't find any blocked request either. Is the app having some sort of IP conflict?

**Comment by ameshkov** [comment]
I suspect that it relies on DNS resolution and the problem might be that Cloudflare DNS does not respond with what Nest expects.

Try replacing the upstream DNS in AdGuard Home settings with your network default DNS servers.

**Comment by egarciarivera** [comment]
I set the upstream to 8.8.8.8:53 (the router's default) and the app still won't connect.

**Comment by egarciarivera** [comment]
I set the upstream to 8.8.8.8:53 (the router's default) and the app still won't connect.

**Comment by egarciarivera** [comment]
I managed to find another iPhone and the app worked on that phone. Ended up resetting my network settings on the phone and that fixed the app. Bizarre behavior. Thanks for your help.

**Comment by ameshkov** [comment]
Weird, but good that it's solved now:)
