### ISSUE TITLE
v0.107.1 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection

### ISSUE THREAD

**Issue by r0bj** [AdguardTeam/AdGuardHome#4044]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.1
* **How did you install AdGuard Home:**
docker
* **How did you setup DNS configuration:**
system
* **CPU architecture:**
AMD64
* **Operating system and version:**
Ubuntu 20.04.3

### Expected Behavior
AdGuardHome resolves DNS names and error logs are not generated.

### Actual Behavior

AdGuardHome stopped resolving DNS names and error logs are generated:
```
2021/12/29 18:43:10.501746 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501750 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501754 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501758 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501762 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501766 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501770 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501774 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501778 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
2021/12/29 18:43:10.501783 [error] handling tcp: setting deadline: set tcp 172.17.0.2:853: use of closed network connection
```

### Additional Information
AdGuardHome version v0.107.0 works as expected in this case so it seems that v0.107.1 introduced this issue.

**Comment by ainar-g** [comment]
Thanks for the report!  This is probably related to #4042.  We're investigating and planning a fix later today.
