### ISSUE TITLE
100% Cpu Load as a result of the newest update

### ISSUE THREAD

**Issue by t3dium** [AdguardTeam/AdGuardHome#4045]
Os: Ubuntu server
Device: Raspberry pi 3b+
version: 0.107.1

After updating adguard home, cpu usage is stuck at 100%. It’s broken my dns server as whenever it hits 100% the system is unable to resolve dns queries. Because of this, I’ve now lost internet access on almost all my devices as well as any other service that was selfhosted on the same machine. Can we please get a bug fix asap?

**Comment by ainar-g** [comment]
Dup of #4042.  The fix is being investigated and prepared for a hotfix.
