### ISSUE TITLE
macOS: Service must be started from Applications folder

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#4046]
It is necessary to add a notification in the log "Service must be started from Applications folder" when trying to start from another directory.

**Comment by two-dogs** [comment]
I am on macos-catalina, i load/unload the service via terminal window, my default dir/folder on terminal open is ~/ and the load unload execute error free, while discussing macos quirks, updating the adguard-home via web from other than the host machine glitches the process, i believe permissions on other than local are not passed to process, someone else would need to verify.
