### ISSUE TITLE
How is this different from pihole?

### ISSUE THREAD

**Issue by TheRockStarDBA** [AdguardTeam/AdGuardHome#405]
This is just a question that I am trying to understand  - is this different from what is available already - PiHole ? Advantages ?

**Comment by ameshkov** [comment]
Hi @TheRockStarDBA!

I've answered this question here:
https://www.reddit.com/r/Adguard/comments/9oxj6m/meet_adguard_home_a_way_to_protect_the_entire/e7xeswu/

Also, this one is relevant as well:
https://www.reddit.com/r/pihole/comments/9oxdz0/adguard_home_vs_pihole_discussion/e7ynd9g/

Sorry for the links, I'd just like to not copy/paste :)
