### ISSUE TITLE
add an option to enable DNS query on Dashboard 

### ISSUE THREAD

**Issue by lifegpc** [AdguardTeam/AdGuardHome#4051]
I would like to enable DNS over HTTPS.
I already use apache2 to proxy the dashboard. ( https://an.kanahanazawa.com/ )
I think provide DNS via dashboard is a good idea. In that case I just need proxy the dashboard.
I already try DNS over HTTPS in settings.
It need bind another port (443 is already used by apache2) and do not works. (I get connection refused error)

**Comment by ainar-g** [comment]
Hello!  I'm not quite what your feature request is, but if you want to set up a DNS-over-HTTPS server with a proxy in front of it, we have a guide on the Wiki: <https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#how-to-configure-a-reverse-proxy-server-for-adguard-home>.  Does this work for you?

**Comment by baoang** [comment]
That looks great. Apache2 is my preference.

I think the OP correctly proxied the web UI part(dashboard), but DoH part was not successful as there was *connection refused error*. 

The dashboard part has a good example from the wiki reference, but it may lack the DoH part.

Probably, we encountered the same problem (https://www.reddit.com/r/Adguard/comments/so3pv5/what_is_the_purpose_of_setting_dnsquery_block_in/)
