### ISSUE TITLE
Feature Request - Custom Client block lists settings

### ISSUE THREAD

**Issue by Saber1998** [AdguardTeam/AdGuardHome#4052]
On my network I have "smart devices" that I have a specific blocklist for that I don't want to enable globally. Example my smart TV, I just want to have use the Adguard Home DNS blocklist, and separate upstream DNS servers. Under client settings I can specify the upstream DNS servers but not able to specify a specific DNS block list and just has an option to use global block lists.

**Comment by two-dogs** [comment]
@Saber1998 ,according to (https://kb.adguard.com/general/dns-providers)
these two dns servers:
#quic://dns.adguard.com
#https://dns.adguard.com/dns-query 
should provide dns with adguard adblocking by default , and yes i agree with you, client specific blocklist would be fun.

**Comment by Saber1998** [comment]
@two-dogs 

I use Unbound, and like the near instant DNS lookup that unbound provides once its cached. I also use nextDNS in conjunction with the Adguard DNS block list and those 2 combined make a near perfect combination of blocking the smart TV from calling home as well as removing ads. 

Right now, as a work around I just have AdGuard Home installed in a Docker container that I tell my DHCP server to have my Smart TV's use. The global block list I use is more restrictive and prohibits some of the Smart TV functions. I've gone through and whitelisted them before with mixed results. Setting up a 3rd DNS server with just using Adguard Blocklist and forward over to nextDNS provides a nice complete package that does everything I'd like. So I'd like to be able to just customize the client to only use a specific block list if that's possible to have added to Client settings.

**Comment by ainar-g** [comment]
This will be addressed during the refactoring / redesign in the v0.108 cycle.  See #2075 and #2554.  Merging into those.
