### ISSUE TITLE
Cannot delete or edit DNS Blocklist filters

### ISSUE THREAD

**Issue by royerlraph79** [AdguardTeam/AdGuardHome#4054]
<img width="1440" alt="Screen Shot 2021-12-31 at 3 08 45 PM" src="https://user-images.githubusercontent.com/30907279/147837946-d1ea8b2b-b395-40d8-9f78-40ee8fd970a2.png">

I'm using the latest version of AdGuard Home and the delete/edit buttons don't show up in my DNS Blocklist filters.

**Comment by mcnk328** [comment]
![imagepic](https://user-images.githubusercontent.com/24218586/147881648-ba77390f-cc79-4c3e-84f0-b78e26b2cb33.png)
try adjust the lower dividing line

**Comment by royerlraph79** [comment]
Man it doesn't work, it only does this weird shit

**Comment by ainar-g** [comment]
Hello.  Which version of Safari are you using?

**Comment by royerlraph79** [comment]
The latest version, 15.2 (17612.3.6.1.6)
  
  
  
    
  

  
  
>

**Comment by IldarKamalov** [comment]
@royerlraph79, hello.  Unfortunately, we cannot reproduce this issue.  Please make sure that you've followed the recommendation by mcnk328 above.

**Comment by royerlraph79** [comment]
I managed to make it work, but the icons don’t appear
  
  
  
  
  
  
  

  
  
>

**Comment by TheCeet** [comment]
Maybe delete browser cache, cookies?

**Comment by royerlraph79** [comment]
Oh crap it strangely worked, thanks!
  
  
  
  
  
  
  

  
  
>
