### ISSUE TITLE
AdGuardHome的性能有问题，不够用，我日均解析200万，每次解析量增大就会导致adh崩溃断网，希望增强adh性能

### ISSUE THREAD

**Issue by hengyv1998** [AdguardTeam/AdGuardHome#4058]
There is a problem with the performance of adguardhome. My daily analysis is about 2 million, the network will be disconnected daily, and I need to restart

**Comment by sxx1314** [comment]
log都没有，你让人家怎么复现。。。

**Comment by cxw620** [comment]
兄弟，个人使用怎么会这么多，难道给别人用了？这个国内好像是违法的。要不然多买几个服务器，要不然单个服务器docker多部署几个然后负载均衡？

**Comment by hengyv1998** [comment]
ok，谢谢












Other&nbsp;shore&nbsp;flow
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月3日(周一) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdGuardHome] AdGuardHome的性能有问题，不够用，我日均解析200万，每次解析量增大就会导致adh崩溃断网，希望增强adh性能 (Issue #4058)




 
兄弟，个人使用怎么会这么多，难道给别人用了？这个国内好像是违法的。要不然多买几个服务器，要不然单个服务器docker多部署几个然后负载均衡？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cxw620** [comment]
在国内且真的是给别人用尽量弄几个服务器，或者借助zerotier部署虚拟内网，尽量减少暴露在公网的请求，DoH就少点用，据说特征非常明显，DoT还好，手机也只支持这个好像。要不然真有可能改天被请去喝茶。

**Comment by hengyv1998** [comment]
ok，明白了，谢谢大佬












Other&nbsp;shore&nbsp;flow
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月3日(周一) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdGuardHome] AdGuardHome的性能有问题，不够用，我日均解析200万，每次解析量增大就会导致adh崩溃断网，希望增强adh性能 (Issue #4058)




 
在国内且真的是给别人用尽量弄几个服务器，或者借助zerotier部署虚拟内网，尽量减少暴露在公网的请求，DoH就少点用，据说特征非常明显，DoT还好，手机也只支持这个好像。要不然真有可能改天被请去喝茶。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kuke21** [comment]
> 在国内且真的是给别人用尽量弄几个服务器，或者借助zerotier部署虚拟内网，尽量减少暴露在公网的请求，DoH就少点用，据说特征非常明显，DoT还好，手机也只支持这个好像。要不然真有可能改天被请去喝茶。

安卓9 dot 苹果14 doh和dot都可以使用

**Comment by Birbber** [comment]
Closing this issue as completed. Feel free to re-open it if needed.
