### ISSUE TITLE
Wildcard DNS Rewrites does not working

### ISSUE THREAD

**Issue by strausmann** [AdguardTeam/AdGuardHome#4059]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.2
* **How did you install AdGuard Home:**
   * GitHub Releases
* **How did you setup DNS configuration:**
  * Unifi Dream Maschine Pro
* **If it's a router or IoT, please write device model:**
  * UDM Pro
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04.3 LTS

### Expected Behavior

I want to create a DNS rewrite rules for the wildcard subdomain *.mydns.domain.de. For this I want to use the following entries.

* *.mydns.domain.de 172.16.99.250
* *.mydns.domain.de 172.16.99.251
* *.mydns.domain.de 172.16.99.252
* *.mydns.domain.de 172.16.99.253

But the NSLOOKUP returns only the first DNS rewrite entry.

### Actual Behavior

For an entry for the subdomain itself, all DNS rewrites are returned in the NSLOOKUP.

* mydns.domain.de 172.16.99.250
* mydns.domain.de 172.16.99.251
* mydns.domain.de 172.16.99.252
* mydns.domain.de 172.16.99.253

I expect all DNS rewrite entries to be returned. As it also works with non wildcard entries.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/4519228/147860347-062a27ca-d109-4100-9e22-ca713390b6ee.png)

![image](https://user-images.githubusercontent.com/4519228/147860355-d34c15c2-39bd-4a8a-8570-cd87db8c1177.png)

</details>

**Comment by ferferga** [comment]
Afaik what you want is not [possible in the DNS specification](https://datatracker.ietf.org/doc/html/rfc1034#section-4.3.3) and it doesn't make much sense either (where would the request go?)

You're probably looking for CNAMEs or a DNS Round Robin mechanism.

**Comment by strausmann** [comment]
A DNS Round Robin mechanism...

**Comment by ferferga** [comment]
I never saw any DNS Round robin mechanism with wildcards (providers can allow it, but that doesn't mean it's standard) and DNS Round Robin traditionally works rotating the order of the responses given in each request (as it's name implies), which is something that goes beyond the scope of adguard, which simply rewrites the query. So no, this is might look similar to Round Robin but afaik it's far from the standard.

**Comment by strausmann** [comment]
@ainar-g many thanks, this helps me
