### ISSUE TITLE
[Request] Pull request for Wiki

### ISSUE THREAD

**Issue by dfmcvn** [AdguardTeam/AdGuardHome#406]
I don't find any option to make a pull request on the Wiki page so I will leave this direct link here.
I've just written a tutorial for self-compiling AdGuardHome from code, for CentOS/RHEL7.

https://hastebin.com/raw/hedijejuha

**Comment by ameshkov** [comment]
mm

**Comment by dfmcvn** [comment]
Sorry, missclick to Create button, updated the post :P

**Comment by ameshkov** [comment]
Wow, awesome, thank you!

**Comment by ameshkov** [comment]
@hmage plz review

**Comment by dfmcvn** [comment]
Trying to rewrite the commands for Ubuntu-compatible, can I leave the Ubuntu version in this comment section later?

**Comment by dfmcvn** [comment]
Update: some of mah friends reported that AdGuardHome may not works correctly if IPv6 is enabled.

```
#temporarily disable ipv6 by sysctl.conf file
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
sysctl -p
```
