### ISSUE TITLE
[error] handling tcp: closing conn: use of closed network connection - repeat errors

### ISSUE THREAD

**Issue by gspannu** [AdguardTeam/AdGuardHome#4065]
### Issue Details

Multiple error lines relating to tcp:closing conn, use of closed network connection - being recorded in log file.

* **Version of AdGuard Home server:**
v0.108.0-a.24+e9c59b09, beta, release - in all versions
* **How did you install AdGuard Home:**
GitHub release

* **CPU architecture:**
linux_amd64
* **Operating system and version:**
Debian x11 - running on Cloud hosted VPS

Here is my log file...

> 2022/01/02 22:26:23.160381 [info] Entering the UDP listener loop on [::]:53
> 2022/01/02 22:26:23.160465 [info] Entering the tcp listener loop on [::]:53
> 2022/01/02 22:26:23.160489 [info] Entering the tls listener loop on [::]:35853
> 2022/01/02 22:26:23.160508 [info] Entering the DNS-over-QUIC listener loop on [::]:784
> 2022/01/02 22:26:28.439917 [error] handling tcp: setting deadline: set tcp abc.def.ghi.xyz:35853: use of closed network connection
> 2022/01/02 22:26:28.439991 [error] handling tcp: closing conn: use of closed network connection
> 2022/01/02 22:26:28.482265 [error] handling tcp: setting deadline: set tcp abc.def.ghi.xyz:35853: use of closed network connection
> 2022/01/02 22:26:28.482359 [error] handling tcp: setting deadline: set tcp abc.def.ghi.xyz:35853: use of closed network connection
> 2022/01/02 22:26:28.482401 [error] handling tcp: setting deadline: set tcp abc.def.ghi.xyz:35853: use of closed network connection
> 2022/01/02 22:26:28.482414 [error] handling tcp: closing conn: use of closed network connection

## I have tried using stable, beta, edge releases - but issue appears in all versions.

_Using amd64 version on a Debian x11 server machine, hosted in the Cloud._

The bug my be related to an earlier reported bug (_but presumably fixed_)
https://github.com/AdguardTeam/AdGuardHome/issues/4042

**Comment by gspannu** [comment]
Providing more information..

**Log file from Beta version.... (same issue)**
_Public IP addresses masked_

> 2022/01/02 23:06:10.913885 [info] AdGuard Home, version v0.108.0-b.1
> 2022/01/02 23:06:10.913930 [info] AdGuard Home is running as a service
> 2022/01/02 23:06:10.944203 [info] Initializing auth module: /home/debian/AdGuardHome/data/sessions.db
> 2022/01/02 23:06:10.945422 [info] auth: initialized.  users:1  sessions:3
> 2022/01/02 23:06:10.947272 [info] number of certs - 3
> 2022/01/02 23:06:10.947293 [info] got an intermediate cert
> 2022/01/02 23:06:10.947311 [info] got an intermediate cert
> 2022/01/02 23:06:11.069562 [info] Initialize web module
> 2022/01/02 23:06:12.012235 [info] AdGuard Home is available at the following addresses:
> 2022/01/02 23:06:12.012474 [info] Go to http://127.0.0.1:30000
> 2022/01/02 23:06:12.012482 [info] Go to http://[::1]:30000111.222.333.444
> 2022/01/02 23:06:12.012486 [info] Go to http://111.222.333.444:30000
> 2022/01/02 23:06:12.012489 [info] Go to http://10.1.1.254:30000
> 2022/01/02 23:06:12.012493 [info] Go to http://[0001:0001:1:00::000:0001]:30000
> 2022/01/02 23:06:12.012508 [info] Go to http://10.106.0.2:30000
> 2022/01/02 23:06:12.033182 [info] Go to https://dns.dummy.website.com:443
> 2022/01/02 23:06:15.280741 [info] Starting the DNS proxy server
> 2022/01/02 23:06:15.280775 [info] Cache TTL override is enabled. Min=3600, Max=172800
> 2022/01/02 23:06:15.280779 [info] Ratelimit is enabled and set to 20 rps
> 2022/01/02 23:06:15.280782 [info] The server is configured to refuse ANY requests
> 2022/01/02 23:06:15.280787 [info] DNS cache is enabled
> 2022/01/02 23:06:15.280795 [info] MaxGoroutines is set to 300
> 2022/01/02 23:06:15.280806 [info] Creating the UDP server socket
> 2022/01/02 23:06:15.280931 [info] Listening to udp://[::]:53
> 2022/01/02 23:06:15.280938 [info] Creating a TCP server socket
> 2022/01/02 23:06:15.280974 [info] Listening to tcp://[::]:53
> 2022/01/02 23:06:15.280979 [info] Creating a TLS server socket
> 2022/01/02 23:06:15.280996 [info] Listening to tls://[::]:35853
> 2022/01/02 23:06:15.281000 [info] Creating a QUIC listener
> 2022/01/02 23:06:15.289264 [info] Listening to quic://[::]:784
> 2022/01/02 23:06:15.294041 [info] Entering the UDP listener loop on [::]:53
> 2022/01/02 23:06:15.294202 [info] Entering the tcp listener loop on [::]:53
> 2022/01/02 23:06:15.294238 [info] Entering the tls listener loop on [::]:35853
> 2022/01/02 23:06:15.294256 [info] Entering the DNS-over-QUIC listener loop on [::]:784
> 2022/01/02 23:06:37.622734 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:06:37.622806 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:06:37.622825 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:06:37.622871 [error] handling tcp: closing conn: use of closed network connection
> 2022/01/02 23:06:37.664152 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:06:37.664920 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:06:37.664974 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:06:37.665013 [error] handling tcp: closing conn: use of closed network connection
> 2022/01/02 23:08:05.196260 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:08:05.196347 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:08:05.196374 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:08:05.196393 [error] handling tcp: closing conn: use of closed network connection
> 2022/01/02 23:08:05.237938 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:08:05.238000 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:08:05.238020 [error] handling tcp: setting deadline: set tcp 111.222.333.444:35853: use of closed network connection
> 2022/01/02 23:08:05.238069 [error] handling tcp: closing conn: use of closed network connection
>

**Comment by ainar-g** [comment]
Thanks for the report!  It's most probably a logging issue rather than an actual error.  We'll fix it in v0.107.3.

**Comment by ainar-g** [comment]
@gspannu, the version `v0.108.0-a.28+008f58c8` on the `edge` release channel should contain a fix for this issue.  Can you please check if it works for you?

**Comment by ainar-g** [comment]
I'll close this issue for now.  Please feel free to write if you have any other problems and can't find a solution.
