### ISSUE TITLE
Disallowed domains - No server respond

### ISSUE THREAD

**Issue by realizelol** [AdguardTeam/AdGuardHome#4066]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.108.0-b.1
* **How did you install AdGuard Home:**
  *  GitHub releases
* **How did you setup DNS configuration:**
  *  Router 
* **If it's a router or IoT, please write device model:**
  *  AMD Ryzen 7 4800U
* **CPU architecture:**
  *  AMD64
* **Operating system and version:**
  *  OpenWRT

### Expected Behavior

Should return a `NXDOMAIN` or `NODATA` or something else so that DNS status will be returned
and the client will get a response and not asking anymore.

### Actual Behavior

Most of the clients will wait too long for a response.

### Screenshots

On Windows:
```
PS C:\Users\chris> nslookup version.bind
Server:  OpenWrt
Address:  192.168.2.33

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to OpenWrt timed-out
```
Unix:
```
time dig version.bind @192.168.2.33

; <<>> DiG 9.10.6 <<>> version.bind @192.168.2.33
;; global options: +cmd
;; connection timed out; no servers could be reached

real	     0m15.019s
user         0m0.003s
sys          0m0.006s
```

### Additional Information
Or if this is not to be considered. Add an alternative method to not show these request in querylog. Like `||example.tld^$nolog` `/dummy/$nolog`.

**Comment by ainar-g** [comment]
This is working as intended.  The request doesn't even reach any kind of processing stage, it is simply dropped.
