### ISSUE TITLE
aarch64 version

### ISSUE THREAD

**Issue by nephaste** [AdguardTeam/AdGuardHome#407]
Hi and thanks for this great project

just built AdGuardHome as Qnap NAS qpkg

https://www.qnapclub.eu/fr/qpkg/649

I wonder if it was possible for you to propose an ARM64 release ?

thanks again,

**Comment by hmage** [comment]
Hi! Congrats, you're the first user to request arm64 🎉 

I've just added arm64 version to [releases page](https://github.com/AdguardTeam/AdGuardHome/releases).

Enjoy 😎
