### ISSUE TITLE
关于【浏览安全】网页服务及【家长安全】服务在中国区的使用十分缓慢的问题

### ISSUE THREAD

**Issue by cxw620** [AdguardTeam/AdGuardHome#4070]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

**Some problems about _Use AdGuard browsing security web service_ and _Use AdGuard parental control web service_
Although they only exist in China.**

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Problem Description

在中国使用【浏览安全】网页服务及【家长安全】服务会导致DNS解析非常缓慢。原因是中国特殊的网络环境。
Using _Use AdGuard browsing security web service_ and _Use AdGuard parental control web service_ in China will cause the DNS resolution to be very slow. The reason is China's special network environment.

### Proposed Solution

在中国大陆设置提供【浏览安全】网页服务及【家长安全】服务的服务器并部署CDN。可以考虑拉赞助。
Set up servers that support _Use AdGuard browsing security web service_ and _Use AdGuard parental control web service_ in Mainland China and deploy necessary CDN. Consider seeking sponsorship.

### Alternatives Considered

提供资源给需要这两项服务的用户自行部署。不过这可能导致隐私问题。
Provide any resources for self-deployment by users who need these two services. However, this may cause privacy issues.

**Comment by Aikatsui** [comment]
@cxw620 You can achieve browsing security and parental control facilities using below providers. It's possible to set them for specific device(s) through client settings. Additionally you can enable safe search as well. Each providers have different performance for different locations and other countries also have such specific network environments
https://kb.adguard.com/en/general/dns-providers#114dns
https://kb.adguard.com/en/general/dns-providers#onedns

**Comment by Birbber** [comment]
Closing as completed.
