### ISSUE TITLE
Auto Update of AdGuard Home not Working MacOS

### ISSUE THREAD

**Issue by zibzabzob** [AdguardTeam/AdGuardHome#4071]
Hi all,
I have 2 instances of Adguard home running. One on a Raspberry pi 4 and one on an 2012 Mac mini. The Raspberry Pi auto updates fine, but the Mac says auto update failed, please update manually.
Is this just a Mac problem, or possibly a permissions issue? I'd rather not update manually whenever a new release come out.

Any help would be much appreciated. :-)

Thank you.

**Comment by ainar-g** [comment]
Hello and thank you for the report!  Here are some questions that will help us clarify the situation:

1.  Is your AGH installed into `/Applications`?  Newer macOS versions will only accept third-party applications installed there, if I recall correctly.

2.  If you [enable verbose logs][1] and try to update, do you see any errors there?

Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by zibzabzob** [comment]
Hi ainar-g, thanks for getting back to me. Yes, it's installed in the applications folder. I can't use the start / stop commands in terminal - says "command not found"!
I noticed that "root" user was not enabled. I've now activated that. Do you think I should uninstall and re-install as "root"?

Thanks

**Comment by two-dogs** [comment]
@zibzabzob , i noticed that if i update from the web-app on a remote machine within the same lan the process crashes, done it twice, and twice i had to reinstall, from the localhost via webapp the process works flawless.
Version:  AdGuard-Home v0.108.0-b.1 on macos catalina
@ainar-g ,  is there a way to force updates via webapp from localhost only? perhaps someone can test on other mac, i tested on remote MBP-Catalina to localhost iMac-Catalina

**Comment by zibzabzob** [comment]
Hi @two-dogs, thanks for your reply. I'can't even update via the web app from the localhost or using a remote machine on the Lan. Can't run any terminal commands even if I navigate to the folder in terminal. Still errors. Think there must be something wrong with the install.

**Comment by two-dogs** [comment]
@zibzabzob  how did you install? i used this method, https://github.com/AdguardTeam/AdGuardHome#automated-install-linux-and-mac , worked out of the box

**Comment by ainar-g** [comment]
Apologies for the late response.

@zibzabzob, can you please show the exact commands you're running and the exact output?

@two-dogs, I'm not sure what you mean by “the process crashes”.  Do you mean the actual `AdGuardHome` process crashing or just the UI not updating in time?

**Comment by two-dogs** [comment]
> Apologies for the late response.
> 
> 
> 
> @zibzabzob, can you please show the exact commands you're running and the exact output?
> 
> 
> 
> @two-dogs, I'm not sure what you mean by “the process crashes”.  Do you mean the actual `AdGuardHome` process crashing or just the UI not updating in time?

@ainar-g, the issue only happens when i try to update via the web-app NOT on localhost, there is no issue on localhost

**Comment by ainar-g** [comment]
@two-dogs, we still need to know what exactly happens.    The `AdGuardHome` process crashing or the UI not updating in the browser.  If it's the second, we'd really appreciate if you could post the logs from the browser console here.  Perhaps it's a CORS issue.  Thanks.

**Comment by zibzabzob** [comment]
Hi, apologies for the delay. I installed it as per the link above - the one on the AdGuard Home page. I've since moved it from MacOS to another Raspberry Pi and it's working great. Updates in a couple of seconds with no issues. When I tried to upgrade on MacOS, a red banner appeared saying 'auto update failed, please use manual installation'. AdGuard didn't crash, just wouldn't update through the GUI.

**Comment by two-dogs** [comment]
@zibzabzob , were you on web page on the local machine? , on local i did not have issue, on other than local i saw as you mentioned

**Comment by ainar-g** [comment]
@zibzabzob, I see, thanks.  Is there anything else we can do in this isssue then?

**Comment by zibzabzob** [comment]
> @zibzabzob , were you on web page on the local machine? , on local i did not have issue, on other than local i saw as you mentioned

Hi, I was not directly on the machine, connected via webpage on local network.

**Comment by zibzabzob** [comment]
> @zibzabzob, I see, thanks. Is there anything else we can do in this issue then?

I don't think so, I'll close the issue. Strange it works on Pi's but not the Mac.
Thanks for your help.
