### ISSUE TITLE
[Upstream DNS servers] wrong upstreams specification even when test passes

### ISSUE THREAD

**Issue by jacktheripper19** [AdguardTeam/AdGuardHome#4074]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.2
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04.1

### Expected Behavior
Setting up the upstream dns server using the hostname of the resolver should work

### Actual Behavior
the test passes but the specification control returns an error **HOSTNAME** is not a valid IP 

### Additional Information
I have a setup where the upstream dns resolver unbound can change ip occasionally but it is on the same network as ADH, which means that it can be found using its hostname.  
In the DNS settings, Upstream DNS servers, using [/local/]unbound:53 as an upstream server passes the test "Specified DNS servers are working correctly" but when applying the changes I get Error: control/dns_config | wrong upstreams specification: unbound is not a valid IP | 400

**Comment by ainar-g** [comment]
Hello and thank you for your report!

It seems like there are two issues here:

1.  Using hostnames for plain DNS is currently not supported.

    @ameshkov, considering that we have bootstrap IP addresses, perhaps we could add a `udp://` scheme support with hostnames?

2.  The upstream test API should indeed validate the domain-specific upstreams as well.  That looks like a bug.

**Comment by jacktheripper19** [comment]
Ok I see. In that case, do you have an idea of a good way to handle this kind of setup where upstream dns changes ip regularly ?

**Comment by ameshkov** [comment]
@jacktheripper19 would it be possible to use TLS on the unbound side? AGH currently will only resolve domain names for encrypted upstreams.

**Comment by ameshkov** [comment]
@ainar-g 

> @ameshkov, considering that we have bootstrap IP addresses, perhaps we could add a udp:// scheme support with hostnames?

Makes sense to me.

**Comment by EugeneOne1** [comment]
@jacktheripper19, we've just pushed the latest build to the `edge` channel.  For the moment it should only invalidate upstream servers like the one in the issue.  Could you please check if it properly reports the error and doesn't break testing of other upstream servers you have? 

We'll also fill the separate feature request on support the `udp://` schema since it needs modifying external libraries.

**Comment by EugeneOne1** [comment]
@jacktheripper19, I'll close the issue for now if you don't mind.  See #4166 for the status of plain DNS hostnames support.
