### ISSUE TITLE
Management GUI - Dark Mode

### ISSUE THREAD

**Issue by dhcpserver** [AdguardTeam/AdGuardHome#4077]
### Problem Description
Dark mode for management interface to stop the glaring pain of the bright colors when I'm connecting in mom's darkened basement.  The management gui should be as dark as the heart of a high-school goth kid that actually comes from a nice family.

### Proposed Solution
Options for dark mode could go under Settings/General or just on the bottom of the management pages near the English drop-down.  Ideally, a sticky, which would take up space in the yaml file, unfortunately.  Even just a cookie to save it would be fine.

### Alternatives Considered
Move out of Mom's basement.  Not possible at this juncture.

### Additional Information
If AGH was a person, I'd propose marriage.  That is my level of unadulterated love.  We could live in forementioned mom's basement and be together forever.  Free from the binds of working and paying for rent or laundry.  The sun would never redden our pale faces.  AGH Dark Mode would prevent any lines in our faces from squinting at the previously bright background.

Please give me hope.

**Comment by Nevotic** [comment]
Defintely agree. I'm currently using Noir on Safari (MacOS) to make it dark. But would love a native solution.

**Comment by TheCeet** [comment]
Duplicate:
https://github.com/AdguardTeam/AdGuardHome/issues/613
