### ISSUE TITLE
Custom domain from /etc/hosts resolv failed partly

### ISSUE THREAD

**Issue by bostoneboy** [AdguardTeam/AdGuardHome#4079]
### Issue Details

* **Version of AdGuard Home server:**
  *  Since v0.107.2
* **How did you install AdGuard Home:**
  * GitHub release
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * router on vmware ESXI
* **CPU architecture:**
  * x86_64
* **Operating system and version:**
  * OpenWRT

### Expected Behavior
ALL custom domain can resolved from OS's /etc/hosts file.

### Actual Behavior
Some custom on /etc/hosts can resolv and some can not since upgrade to v0.107.0 from v0.106.
AFTER try man times,  I FOUND that 
the new version can only resolv the first line's custom domain when multi line contain the same IP address.

### Screenshots
![image](https://user-images.githubusercontent.com/526946/148019217-008817d9-35e2-434b-9928-8a3836a39f02.png)

</details>

**Comment by EugeneOne1** [comment]
@bostoneboy, hello and thanks for the report.  Latest build from the `edge` channel should improve the parsing of `/etc/hosts` and most likely fix the issue.  Could you please install it and check if it actually does?

**Comment by EugeneOne1** [comment]
@bostoneboy, I'll close the issue for now.  Please feel free to reopen it if the issue reoccurs.

**Comment by bostoneboy** [comment]
It fixed in v0.107.3, thx
