### ISSUE TITLE
Not working on MacOS Mojave 10.14.1 Beta

### ISSUE THREAD

**Issue by LucasExequielAdguard** [AdguardTeam/AdGuardHome#408]
Nothing is working, No filters are being applied. Stats still show 0. Not even logs appear.

![captura de pantalla 2018-10-19 a la s 17 34 19](https://user-images.githubusercontent.com/44304762/47242486-42f26500-d3c5-11e8-82b6-2cb66e8df08d.png)
![captura de pantalla 2018-10-19 a la s 17 34 14](https://user-images.githubusercontent.com/44304762/47242492-44bc2880-d3c5-11e8-8b0e-37d8af4b14bd.png)
![captura de pantalla 2018-10-19 a la s 17 34 12](https://user-images.githubusercontent.com/44304762/47242497-45ed5580-d3c5-11e8-88ad-cb075b9d793f.png)
![captura de pantalla 2018-10-19 a la s 17 34 04](https://user-images.githubusercontent.com/44304762/47242499-471e8280-d3c5-11e8-9974-43a49a490fc5.png)
![captura de pantalla 2018-10-19 a la s 17 33 54](https://user-images.githubusercontent.com/44304762/47242501-484faf80-d3c5-11e8-8caa-798b0997d9e6.png)
![captura de pantalla 2018-10-19 a la s 17 33 43](https://user-images.githubusercontent.com/44304762/47242502-48e84600-d3c5-11e8-9680-490af581d58b.png)

**Comment by ameshkov** [comment]
Make sure that you've configured your devices to use AG Home:
https://github.com/AdguardTeam/AdGuardHome/wiki#how-do-i-set-up-my-devices-to-use-my-adguard-home

**Comment by LucasExequielAdguard** [comment]
Problem fixed. You were right, I had set the wrong address. Thanks! :)
![captura de pantalla 2018-10-19 a la s 19 39 41](https://user-images.githubusercontent.com/44304762/47246907-c072a100-d3d6-11e8-8d22-9f8980cb2931.png)
