### ISSUE TITLE
Justa quick question ...

### ISSUE THREAD

**Issue by mrtargaryen** [AdguardTeam/AdGuardHome#409]
"Router

This setup will automatically cover all the devices connected to your home router, and you will not need to configure each of them manually.

Open the preferences for your router. Usually, you can access it from your browser via a URL (like http://192.168.0.1/ or http://192.168.1.1/). You may be asked to enter the password. If you don’t remember it, you can often reset the password by pressing a button on the router itself. Some routers require a specific application, which in that case should be already installed on your computer/phone.

Find the DHCP/DNS settings. Look for the ’DNS’ letters next to a field which allows two or three sets of numbers, each broken into four groups of one to three digits.
**_**Enter your AdGuard Home server addresses there**_**."

So, is this suggesting to put my NAS's LAN IP address in my router's LAN>DHCP>DNS field?

**Comment by ewrogers** [comment]
Assuming your NAS is running AdGuard Home, yes that is correct!

**Comment by mrtargaryen** [comment]
> Assuming your NAS is running AdGuard Home, yes that is correct!
> 
> If you're using a Synology NAS, I recommend the Docker approach. :)

I'm using a QNAP TS-253Be and I've installed the .qpkg that was created for QNAP X64 models and have put 192.168.1.219 (NAS IP) into the DHCP>DNS field and my devices are still showing ads. Also, no devices show in AdGuard Home [https://imgur.com/a/xScvcDv](url)

**Comment by mrtargaryen** [comment]
The person who created the QNAP .qpkg wrote:

Listen on 9638 for web admin
CoreDNS port listen on 16553 (instead of 53
