### ISSUE TITLE
Add blocked services toggle for Google.

### ISSUE THREAD

**Issue by CipherOps** [AdguardTeam/AdGuardHome#4092]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

Add a blocked service toggle for Google.

**Comment by Cybercave** [comment]
There is this repository, which I have been using https://github.com/nickspaargaren/no-google.

Although I have blocked the IPs for both Google and Cloud, which causes AGH to have high RAM usage due to over 24 million IPs being loaded.

**Comment by ainar-g** [comment]
Merging into #2604.
