### ISSUE TITLE
DNS-over-TLS

### ISSUE THREAD

**Issue by lc99310** [AdguardTeam/AdGuardHome#4097]
希望官方开启DNS-over-TLS或搭建的方法。

**Comment by kuke21** [comment]
你说印格雷西不好么 他们看不懂中文的呢

**Comment by ainar-g** [comment]
Hello.  Please elaborate on what you are trying to do and what kind of difficulties you're encountering.  In any language you're comfortable with.  Thanks!

* * *

(自动翻译。)

你好。 请详细说明你想做什么，你遇到了什么样的困难。 请用你能接受的任何语言。 谢谢!

**Comment by kuke21** [comment]
dns-over-tls 我倒是搞定了 但国内明文规定 有法律限制 dns 如果你做商业会坐牢 这个给你提个醒 满足几个条件udp 53对外 ip根证书 不能自签 tcp 853 对外 最后是等公共dns扫到你的53了就通了

**Comment by cxw620** [comment]
> dns-over-tls 我倒是搞定了 但国内明文规定 有法律限制 dns 如果你做商业会坐牢 这个给你提个醒 满足几个条件udp 53对外 ip根证书 不能自签 tcp 853 对外 最后是等公共dns扫到你的53了就通了
(Translation)In China, personal publicly providing DNS service is illegal.

我在想ADH能不能提供自签IP证书的功能, 甚至做mTLS的功能, 直接不用域名. 
If ADH can provide the function of self-signed IP certificates, even mTLS, I would be really happy.

目前测试DoT是很稳定的. 然后UDP53只开放给Zerotier搭建的内网使用(本来就是避免DNS污染,一般也不用这个). 
要更加安全的话, 还可以DoT也走Zerotier, 反正大部分人一般是定居某地的, 就近机房开个ADH就行了. (吐槽金山云的渣网络)
同时YogaDNS支持指定DoT或者DoH的ip, 也不用给DoT或者DoH用的域名解析了, 这样公网ip也不会暴露了.

**Comment by rmdes** [comment]
I think I have the same issue, my Adguard instance has already SSL certificate from the nginx proxy in front but when I add my domain and try to add my private and pem key I just can't get it to accept the connection on port 443
my instance is running here : https://rmdes.noho.st/#
I also tried to convert my nginx generated certbot key to rsa and add it but the key is invalid :/
