### ISSUE TITLE
no internet warrning when block taobao.com

### ISSUE THREAD

**Issue by kuduacz** [AdguardTeam/AdGuardHome#4098]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

When i block taobao.com page ( generate 20% of traffic) my router (tenda nova mw5) show me warrning that there is no internet connection (led blink red) but i have acces to internet.
how can i block taobao ( to lower traffic) and have no internet warrning

**Comment by DandelionSprout** [comment]
There may or may not be a router setting to determine which domain the router shall ping to check for internet connections.

However, since the router is PR-Chinese, it'd surprise me a lot if the router manufacturer was that merciful.

**Comment by ainar-g** [comment]
That sounds like a router issue indeed.  Please inspect your router's settings and manuals to see, if the domain for internet access check can be changed.

**Comment by Birbber** [comment]
Closing this issue as completed. Feel free to re-open if needed.
