### ISSUE TITLE
Не могу зайти в настройки Adguard с основного браузера windows 10.

### ISSUE THREAD

**Issue by densik3799** [AdguardTeam/AdGuardHome#4099]
![Снимок](https://user-images.githubusercontent.com/35930686/148525444-7bf0ed19-4db3-42c3-9e06-b653b3478b16.PNG)
![Снимок PNGfdffdf](https://user-images.githubusercontent.com/35930686/148525448-bf08d214-3e6b-4b1a-a0c2-bbe5bb8ec181.PNG)
![Снимок PNGfffdfdf](https://user-images.githubusercontent.com/35930686/148525450-08df5def-3147-427a-97b9-b0fcd0af06ba.PNG)
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Actual Behavior

Добрый день Уважаемая поддержка!)Как мне удалить Adguard Home?Я уже два сервера создал по ошибки и хочу один только и чтоб можно было не с виртуальной машине заходить в настройки Adguard а с основой а у меня с основного браузера не получается войти в Adguard Home(((((((((((((((((Помогите пожалуйста???
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by densik3799** [comment]
Получается первый скрин это мой первый сервис там я все настроил только через виртуальную машину виртуал бокс.Но там не смог зайти в основной браузер в настройки adguard.Тут перешёл на сайт https://snapcraft.io/adguard-home и там скопировал строку и вставил в терминал пошла установка и настройка как все настроилось такой адрес http://localhost:79/ написало сайт не доступен(((Это получается второй сервак но даже войти не могу((((Хочу их либо два удалить и по новой но не знаю как удалить команду ввожу /AdGuardHome -s uninstall пишет не верная команда(((
![Снимок PNGjkjkjkk](https://user-images.githubusercontent.com/35930686/148526367-ef4e6e53-5db9-45bc-acd2-e918a8ad8073.PNG)

**Comment by EugeneOne1** [comment]
@densik3799, насколько я вижу, в виртуальной машине у вас Ubuntu.  Чтобы удалить AGH, установленный через из Snapcraft Store, попробуйте:
```sh
sudo snap remove adguard-home
```

Если вы устанавливали AGH, используя скрипт с главной страницы репозитория на GitHub, то по умолчанию исполняемый файл должен быть расположен в `/opt/AdGuardHome`, то есть для его удаления необходимо обратиться к нему как-то так:
```sh
sudo /opt/AdGuardHome/AdGuardHome -s uninstall
```

Помогло ли что-то из вышеперечисленного?

Также, пожалуйста, используйте раздел **Discussions** репозитория на GitHub для подобного рода вопросов.

**Comment by densik3799** [comment]
Извините я уже эту машину удалили и забыл удалить свой вопрос Уважаемый ЮджинУан1
