### ISSUE TITLE
[Feature Request] Allow temporarily disabling filtering for a certain device

### ISSUE THREAD

**Issue by mustakimali** [AdguardTeam/AdGuardHome#410]
Sometime temporarily disabling dns filtering is necessary . So It would be great to have a easy way to disable filtering for requests originating from a specific device.

Example mockup:

![image](https://user-images.githubusercontent.com/1546896/47255327-50f8c200-d467-11e8-9f30-45cc336be044.png)

**Comment by ibksturm** [comment]
good idear

**Comment by ameshkov** [comment]
This is now possible via "Clients" settings: #727

**Comment by mustakimali** [comment]
Thanks, trying out AdGuard Home again. Glad to see both my requested feature (DHCP and this one) is implemented and working perfetly. 👍
