### ISSUE TITLE
Periodic high cpu load

### ISSUE THREAD

**Issue by silvanverschuur** [AdguardTeam/AdGuardHome#4104]
I've migrated from using Adguard Home in a VM to using the Docker container (version `0.107.2`). Every 10/12 hours I see a spike in CPU usage for about 90 minutes. I have never seen this behaviour when I was running Adguard Home inside a VM.

Thing I have tried without success:
* Disable memory optimization 
* Use docker host network instead of bridged mode

The average CPU usage of Adguard used to be somewere between 0-3%. The strange thing is that these spikes also occur in the middle of the night, so I don't think it's related to a DNS lookup. My average number of DNS queries / 24h is 40.000.
I've added some screenshots of the CPU usage of the Adguard docker container.

### Screenshots
![image](https://user-images.githubusercontent.com/3354864/148636829-3dda7c1a-431f-4bf1-943b-a36f03c22f98.png)

![image](https://user-images.githubusercontent.com/3354864/148636746-c4f10df8-8ce0-4283-bcff-d994fc2bcbb8.png)

**Comment by Harvester57** [comment]
Wouldn't be linked to the refresh update period (i.e. when refreshing and parsing your blocklists) ?

**Comment by silvanverschuur** [comment]
My update interval is 24h and I only have 1 blocklist. The CPU spikes occur every 10 / 12 hours. So I'm not convinced this is causing the CPU spikes, but I will keep an eye on it.

**Comment by ainar-g** [comment]
Hello, thank you for the report, and apologies for the late response.  Can you enable [verbose logging][1] and look, what kind of logs are printed during the CPU spikes?  Or send the logs to devteam@adguard.com with the corresponding subject line, if you think you could do that.  Thanks!

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by silvanverschuur** [comment]
@Birbber I have not seen these CPU spikes anymore using the latest version(s) so I think this issue van be closed.

**Comment by Jleagle** [comment]
@silvanverschuur Are you running docker? If so did you update to `adguard/adguardhome:latest`?

Looks like i have the same issue: https://github.com/AdguardTeam/AdGuardHome/issues/4531 - but updating doesn't seem to fix it.

**Comment by silvanverschuur** [comment]
@Jleagle Yes I'm running docker. I use the latest version of adguard and did not see any spike since my previous comment.

**Comment by 6r33z3** [comment]
Hi all. Just want to chip in - been having this identical issue on openwrt running both adguardhome natively (via opkg) or docker, after baffling there's massive system load during unmanned hours without anythign scheduled in cron, finally I've figured out the reason of causing the periodic CPU spike is due to homeassistant's adguardhome addon/plugin, which periodly makes http request to all HA properties of adguardhome (can be seen via verbose logging), and the process is very expensive to for embedded systems. Disarmed the HA plugin and it's been peaceful since then.

**Comment by Jleagle** [comment]
> Hi all. Just want to chip in - been having this identical issue on openwrt running both adguardhome natively (via opkg) or docker, after baffling there's massive system load during unmanned hours without anythign scheduled in cron, finally I've figured out the reason of causing the periodic CPU spike is due to homeassistant's adguardhome addon/plugin, which periodly makes http request to all HA properties of adguardhome (can be seen via verbose logging), and the process is very expensive to for embedded systems. Disarmed the HA plugin and it's been peaceful since then.

That seems to be it, nice one!!
