### ISSUE TITLE
The ability NOT to save the data of a specific device in logs.

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#4105]
Version 107.2
I have some devices that create traffic too actively, in particular, the TV sends requests to the address every second cdn.samsungcloudsolution.com . Because of this, the statistics and log files take up a lot of space, and the router's RAM becomes insufficient. You can also make it so that you can not save requests for specific devices in statistics and in the log.
![1](https://user-images.githubusercontent.com/74646605/148644347-9519beaa-847a-4f16-bfd9-fc9dea2f90d6.jpg)

**Comment by jamesmacwhite** [comment]
From a router perspective, you are better off making sure the working directory where AdGuard Home writes query/statistics data is a persistent storage location such as USB, rather than RAM or tmpfs as you'll definitely hit this with many chatty devices or a network that's generating a lot of DNS/query data.

Unless using additional/persistent storage for query logging data such as USB, you might also have to use lower retention settings to avoid this as well.

**Comment by fizsef** [comment]
That's all clear. But why not give the user a choice whether to store or ignore data from a specific device. It would be reasonable and correct. For example, I don't have a USB port on the router, and the amount of RAM is also small, so what should I not use AGH at all?!

**Comment by jamesmacwhite** [comment]
@fizsef There's an argument that running AdGuard Home directly on a router on that has limitations on flash space, storage or RAM is potentially going to be problematic for performance generally, but as a feature suggestion I don't disagree that it could be useful. I just noticed from your other posts you mentioned OpenWrt, which I also use and can understand some of the limitations in regards to routers.

**Comment by fizsef** [comment]
I don't really understand you. What can the proposed function do for you? If you don't need it, don't use it. And whoever needs it will use this functionality. The opportunity to have a choice is always better than not having such an opportunity.

**Comment by jamesmacwhite** [comment]
I'm not dismissing your idea at all, sorry if it's come across like that. In my reply I did state it could be useful for those in such a situation like yourself. What I'm saying is there is also the general consideration of running AdGuard Home on a router with lower hardware, I don't know your specific router so I don't know if that's the case. OpenWrt these days recommends the 16/128 model (16 MB flash 128 MB RAM) as a baseline minimum. When working on the wiki page for [AdGuard Home on OpenWrt](https://openwrt.org/docs/guide-user/services/dns/adguard-home), we've noted that from testing, even the 16/128 recommended minimum is probably borderline for running AdGuard Home performantly in many cases.

**Comment by fizsef** [comment]
I have an AC Redmi 2100 router, 128/128 memory. 128 RAM with such volumes of logs and statistics becomes insufficient. Therefore, it is necessary to be able to exclude such devices from statistics and the log.

**Comment by ainar-g** [comment]
Looks like a dup of #3140.  Merging and closing.
