### ISSUE TITLE
API: /control/clients/update throws "invalid name" error

### ISSUE THREAD

**Issue by pawelantczak** [AdguardTeam/AdGuardHome#4106]
### Issue Details

AdGuard Home
Version: v0.107.2
Channel: release
Go version: go1.16.12
Build time: 2021-12-29T19:56:11Z+0000
GOOS: linux
GOARCH: arm
GOARM: v6
Race: false

Using API to update client settings for existing clients (created manually or via API) doesn't work.

### Expected Behavior
Client settings should be updated.

### Actual Behavior
"invalid name" error is returned.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/171534/148654310-ef2d9119-7665-4d04-80df-8bae797c43aa.png)
![image](https://user-images.githubusercontent.com/171534/148654324-c5dc7f27-c9ba-4c25-9365-032b8d1fb6ce.png)

</details>

**Comment by EugeneOne1** [comment]
@pawelantczak, it seems the request you're trying to POST has an incorrect format.  It should consist of fields `"name"` and `"data"`, where `"name"` specifies the client to update and `"data"` contains the modified client's data (including the name if needed).  I can assume, in this case it should be something like:

```json
{
	"name": "localhost",
	"data": {
		"name": "localhost",
		"ids": [
			"string"
		],
		"use_global_settings": true,
		"filtering_enabled": false,
		"parental_enabled": true,
		"safebrowsing_enabled": true,
		"safesearch_enabled": true,
		"use_global_blocked_services": true,
		"blocked_services": [
			"string",
		],
		"upstreams": [],
		"tags": [],
	}
}
```

Does it work?

**Comment by pawelantczak** [comment]
Thanks. I don't know why I've messed up json.
