### ISSUE TITLE
Заблокированные сервисы НЕ РАБОТАЮТ((((Сайты так же работают.

### ISSUE THREAD

**Issue by densik3799** [AdguardTeam/AdGuardHome#4107]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

![Снимок PNGгнгн](https://user-images.githubusercontent.com/35930686/148659976-e28bf756-4ae0-4e15-9c21-4295f6376ac1.PNG)
![Снимок PNGгнгнгн](https://user-images.githubusercontent.com/35930686/148659978-d61cedf7-323d-41bd-9ad2-282b8b1e9131.PNG)
Добрый вечер Уважаемые разработчики!))Не работает блокировка сайтов не один сайт не блокируется(((Настройки сохранил!

**Comment by densik3799** [comment]
Версия Adguard Honve версия: 
v0.107.2 Windows 10 LTSC 64 bit.Названия  роутера TL-WR740N.Версия 4.22.Устанавливал конфигурацию по умолчанию ничего не менял. процессор i5 4570.Устанавливал с каченного  сайте https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.2 извлек из архива все делай как было указано в установке через cmd прописал В Windows запустите cmd.exeс правами администратора и запустите AdGuardHome.exe итд сайт настройки вот это https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#installation

**Comment by EugeneOne1** [comment]
@densik3799, здравствуйте.  Ответьте, пожалуйста, на следующие вопросы:

 1. Как вы настраивали DNS для устройства, на котором хотите блокировать сервисы?  Через настройки роутера или вручную на устройстве?  Включает ли эта конфигурация другие сервера помимо машины, на которой установлен AGH?
 1. Работают ли другие виды блокировок (правила, родительский контроль, безопасный поиск и т.д.)?
 1. Не могли бы вы предоставить нам логи, отражающие ситуацию?  Если AGH запускается через `cmd.exe`, то вы можете просто запустить его с флагами `-v` и `--logfile <полный путь к файлу>`.  Финальная команда должна выглядеть примерно так:
```
AdGuardHome.exe -v --logfile C:/path/to/log/file.txt
```

**Comment by densik3799** [comment]
Добрый вечер Уважаемый EugeneOne1.Настраивал его через роутер прописав там адреса как на скрине 192.168.0.100 и такой же адрес в компьютере в pv6 192.168.0.100 и в pv6 2a10:50c0::ad1:ff  2a10:50c0::ad2:ff
![Снимок](https://user-images.githubusercontent.com/35930686/148822073-c81a7bf6-87ae-41cc-b3d2-245e5971727e.PNG)
![Снимок PNGапапап](https://user-images.githubusercontent.com/35930686/148822780-981ee1c7-2ad6-4682-bf11-924a854a955d.PNG)
![Снимок PNGпапапап](https://user-images.githubusercontent.com/35930686/148822810-95f66f75-9345-4710-8e1e-770ff36be4a9.PNG)
![Снимок PNGпрпррр](https://user-images.githubusercontent.com/35930686/148822831-47c89890-1a14-4fd7-b805-aca5906a3e59.PNG) Я очень хочу чтоб работала функция заблокированные сервисы.Чтоб можно любой сервис в списке заблокировать.Она же для этого и предназначена?У меня мало знаний к вашим терминам(((((Я затрудняюсь Вам на это ответить(((((((((Через город или вручную на трафик? Включает ли эта настройка другие серверы на разных машинах, на которых установлен AGH?).Реклама блокируется везде+ расширением.
![Снимок PNGпапп](https://user-images.githubusercontent.com/35930686/148823746-a9bd8c40-0924-45f5-b609-796783846075.PNG) Как же то все сложно очень.
Указал глобальную службу DNS 
![Снимок PNGiuiuii](https://user-images.githubusercontent.com/35930686/148826721-f013258b-e3fb-4774-a9c0-377806e94007.PNG).Я Adguard Hom установил в диск D.
![Снимок PNGTRTRRTR](https://user-images.githubusercontent.com/35930686/148828717-bd8f91e8-bb15-42b9-a223-4b401cbb49b9.PNG).Опиши пожалуйста очень подробно как создать эти логи?Для меня это очень сложно((((

**Comment by densik3799** [comment]
![Снимок PNG мимии](https://user-images.githubusercontent.com/35930686/148975236-f9b99bc9-174f-440d-807a-cbbe0dada272.PNG)
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7847917/file.txt)
Это он Уважаемый ЮджинУан1

**Comment by densik3799** [comment]
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848003/file.txt)

**Comment by EugeneOne1** [comment]
@densik3799, все верно – это то, что нужно.  Однако, судя по временным меткам в логе, AGH не успевает обработать ни один запрос.  Будьте добры, соберите лог еще раз, но в этот раз между перед отключением AGH попробуйте открыть сервис, который пытаетесь заблокировать (насколько я понял, речь о сайте vk.com).

**Comment by densik3799** [comment]
Спасибо большое за быстрый ответ Уважаемый ЮджинУан1.А как?Соберите журнал еще раз, но в этот раз между отключением AGH.Это мне сделать опять заблокировать сайт вк и потом отключить AdguarHom от интернета?И собрать журнал???

**Comment by EugeneOne1** [comment]
Последовательность действий должна быть примерно следующей:

 1. Запустить AGH тем же самым образом;
 1. Заблокировать сервис VK;
 1. Попытаться зайти на vk.com;
 1. Остановить AGH и отправить лог.
 
Благодарю за активное содействие!

**Comment by densik3799** [comment]
Это я Вас Благадарю,что отозвались мне помочь Уважаемый разработчик ЮджинУан1  и прекрасного продукта AdguardHom
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848185/file.txt)

**Comment by densik3799** [comment]
А как тогда Вы пишите с отключением Adguard?Как мне его выключить командой от cmd?

**Comment by EugeneOne1** [comment]
Позвольте узнать, а как именно вы устанавливали AGH?  Важно понимать, что для работы блокировки необходимо, чтобы AGH был запущен постоянно.

Судя по журналу, вы отключаете его комбинацией `Ctrl`+`C`.  Это корректный способ в случае запуска через `cmd.exe`.

**Comment by densik3799** [comment]
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848312/file.txt)
Я его выключаю командой 
AdGuardHome -s stop наверное тоже не вышло(((

**Comment by densik3799** [comment]
Запускаю так AdGuardHome -s start: Запустить службу.А как мне его остановить Adguard?

**Comment by densik3799** [comment]
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848422/file.txt)
ПОЧТИ ПОЛУЧИЛОСЬ)))Я записывал сейчас пришлю.

**Comment by densik3799** [comment]
Вот видео https://cloud.mail.ru/public/CXKa/qKyGTbqUM

**Comment by densik3799** [comment]
Где-то не правильно сделал?

**Comment by densik3799** [comment]
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848620/file.txt)
![Снимок](https://user-images.githubusercontent.com/35930686/148989681-782385b1-da5f-4eee-8b52-038ecd0e6374.PNG)
вместо vk какой-то ;a.root-servers.net.	IN	 A

**Comment by densik3799** [comment]
Edf;ftvsq EugeneOne1/Можете сами зайти сделать через удаленный доступ?

**Comment by densik3799** [comment]
Я случайно закрыл тему((((((((((((((((

**Comment by densik3799** [comment]
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848806/file.txt)
Блокировал сайт mail.ru и там опять ​​какой-то ;a.root-servers.net

**Comment by densik3799** [comment]
[file.txt](https://github.com/AdguardTeam/AdGuardHome/files/7848886/file.txt)
Все равно нет сайта vk в списке.

**Comment by densik3799** [comment]
Добрый вечер Уважаемый EugeneOne1 .Даже на виртуальной машине виртуал бокс windows LTSC 64 bit тоже не работает функция заблокированные сервисы.
![Desktop Screenshot 2022 01 12 - 18 10 25 74](https://user-images.githubusercontent.com/35930686/149167104-77958ed9-a08a-4f93-bc86-43e4d0bb9c2c.png)

**Comment by densik3799** [comment]
Может мне его переустановить?Или Вы сами сможете его правильно установить и настроить?Может это из-за настроек?

**Comment by EugeneOne1** [comment]
@densik3799, честно говоря, я почти уверен, что дело именно в конфигурации.

Давайте для начала определимся, где вы хотите использовать AGH?  Под "использовать" я имею в виду именно машину-хост, т.е. машину, которая будет принимать и обрабатывать запросы от остальных устройств – выступать DNS сервером.  Насколько я понимаю, в вашем случае это либо машина на Windows, либо виртуальная машина на Ubuntu.  Видите ли, от этого зависит, как должен быть настроен AGH.

**Comment by densik3799** [comment]
Спасибо большое,что ответили))))))))))))))Я  его использую на основной машине windows 10 LTSC 64 bit.Через роутер TP-Link-WR740N.Версия 4.22.Только windows и мой роутер Уважаемый ЮджинУан1

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/149175427-1006f1b5-fb53-4fd7-81b4-18984c5fb511.PNG)
Вот пишут эта функция не доработана(

**Comment by densik3799** [comment]
У него все работает https://www.youtube.com/watch?v=9BeDgFjPkao у меня нет((((((((((((((на минуте 3:53 - 4:39 Функция "Заблокированные сервисы

**Comment by densik3799** [comment]
Ответили на канале ютуб:скорее всего изменились регулярные выражения. Поэтому их лучше написать самостоятельно.

**Comment by EugeneOne1** [comment]
@densik3799, скриншоты демонстрируют, что вы можете получить доступ к веб-интерфейсу AGH (открыть в браузере), однако в панели задач я не вижу консоли, из чего я делаю вывод, что AGH запущен как-то иначе.  Позволю себе предположить, что вы установили его в качестве сервиса:

```none
AdGuardHome.exe -s install
```

Давайте для начала попробуем добиться его остановки – в случае успеха AGH должен перестать открываться в браузере.  Для начала попробуйте удалить сервис с помощью команды:

```none
AdGuardHome.exe -s uninstall
```

Если доступ из браузера сохранится, придется прибегнуть к диспетчеру задач – необходимо остановить все процессы, имеющие в названии `AdGuardHome`.  Если доступ сохранится и после этого, стоит удалить исполняемый файл (`AdGuardHome.exe`), а лучше всю директорию, и скачать архив заново.

Пожалуйста, опишите полученный результат – ожидается, что доступ к AGH будет утрачен, и с этим уже можно работать :)

**Comment by densik3799** [comment]
Добрый вечер Уважаемый ЮджинУан1 Вот скриншот.Ды Вы правы он запущен у меня как служба,я же писал выше и сайт с установкой его.Сейчас буду пробовать его удалить и пробовать,что Вы написали.
![Снимок](https://user-images.githubusercontent.com/35930686/149368234-061b88c7-dc86-4251-b3a8-971da39eb4cb.PNG)

**Comment by densik3799** [comment]
![Снимок PNGрпрпр](https://user-images.githubusercontent.com/35930686/149369617-2de90a8a-4ea4-4407-a78f-61dfe64696d5.PNG)
Вот удалил....И все работает без изменений и служба тоже.
![Снимок екекееPNG](https://user-images.githubusercontent.com/35930686/149369726-c1cdd95a-283e-401c-a6b8-154ea1de6e5b.PNG)

**Comment by densik3799** [comment]
и вход в браузер тоже нормально без изменений.

**Comment by densik3799** [comment]
![Снимок PNGеенен](https://user-images.githubusercontent.com/35930686/149370070-32b08088-7fbd-4ad2-8681-38333570e402.PNG)
Остановил службу доступа нет

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/149372183-c9c752ac-9275-4b25-bdf5-a5b2ceec5067.PNG)
какой с этих скачать я скачивал amd64 это правильно?

**Comment by densik3799** [comment]
Все делаю по этой инструкции для windows https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#installation

**Comment by EugeneOne1** [comment]
Позвольте узнать, а как именно вы остановили службу?  Командой `AdGuardHome.exe -s stop`?

**Comment by densik3799** [comment]
Установка
![Снимок PNG 3](https://user-images.githubusercontent.com/35930686/149376034-12a5a557-3381-4979-a2a1-7f5504b82303.PNG)
![Снимок PNG 4](https://user-images.githubusercontent.com/35930686/149376037-e7295a57-1921-4f42-8adf-bfd3b57dee56.PNG)
![Снимок PNG 5](https://user-images.githubusercontent.com/35930686/149376038-bef0cd53-b673-4ee9-abf3-7061203e0561.PNG)
![Снимок PNGииимимим](https://user-images.githubusercontent.com/35930686/149376040-9e1e8a9c-b26c-42fc-b94b-7c7d2491450f.PNG)
![Снимок PNGм 2](https://user-images.githubusercontent.com/35930686/149376042-f50c6b75-83c1-475e-9572-427ba6f1a8dc.PNG)

**Comment by densik3799** [comment]
Нет я отключил службу через диспетчер устройств и преминул потом команду через cmd AdGuardHome -s uninstall: удалить службу AdGuard Home.Как Вы и писали.

**Comment by densik3799** [comment]
сейчас буду пробовать)Дай то БОГ чтоб все работало.

**Comment by densik3799** [comment]
Все так же ничего не блокирует и при установке на скрине он подвис и я нажал обновить страницу и заново начал настраивать так и было в тот раз

**Comment by densik3799** [comment]
Я очень рад EugeneOne1))))Вы мне теперь поможете и знаете в чём проблема?))))))))))))

**Comment by densik3799** [comment]
![Снимок PNG(https://user-images.githubusercontent.com/35930686/149376714-f59842c2-2237-4eb8-ae9e-9ca97d2fa332.PNG)
![Снимок PNGкекее](https://user-images.githubusercontent.com/35930686/149376829-b10ec2df-ff79-44b7-8a32-94271997f0fb.PNG)

**Comment by EugeneOne1** [comment]
Вы завершили первоначальную настройку?  Если да, не могли бы вы проверить, есть ли доступ к веб-интерфейсу с других устройств в сети?  Например, получается ли со смартфона в браузере перейти на `192.168.1.100:80`?

**Comment by densik3799** [comment]
Сейчас попробую))))Ждите.....

**Comment by densik3799** [comment]
Извините за ожидания((((((((((((((Со второго пк не заходит пишет перейти не на защищенный сайт и потом не заходит с телефона с гугла поиска по этому адресу не заходит.У меня телефон очень старый((((((((((((((

**Comment by EugeneOne1** [comment]
А второй ПК подключен к той же сети (к тому же роутеру)?

Также, имеет смысл попробовать перейти на `http://192.168.1.100`, поскольку судя по ошибке, браузер второго ПК ограничивает доступ к незашифрованным соединениям.  Обратите внимание, необходимо написать именно `http`, а не `https`.

**Comment by EugeneOne1** [comment]
Впрочем, если вы хотите заблокировать доступ к сервисам только на одном компьютере, попробуйте использовать в качестве DNS сервера адрес `127.0.0.1`.  Это специальный адрес, позволяющий компьютеру указать на самого себя.  Кроме того, имеет смысл также попробовать вписать этот адрес в оба поля (первичный и вторичный DNS сервера), поскольку я не уверен, как ведёт себя Windows при указании лишь одного адреса – вполне вероятно, что второй адрес заполняется автоматически.

**Comment by densik3799** [comment]
Да второй Пк подключен к роутеру только по кабелю от роутера в пк.Сейчас попробую перейти.И прописать адреса А эти адреса ввести в пк в pv 4 и в pv 6 или ещё в роутере?

**Comment by EugeneOne1** [comment]
Адреса надо прописать на том же ПК, на котором работает служба AGH.  В IPv4 надо прописать `127.0.0.1`, а IPv6 для начала лучше вообще отключить.

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/149390918-f305bf8d-d37f-48b5-859b-b61b41a02c7d.PNG)
только на пк там где Adguard?

**Comment by EugeneOne1** [comment]
Что ж, если компьютеры в одной сети, значит у вас должно получиться провернуть то же, что описано в [этой](http://fadmin.ru/vopros/kak-proverit-svyaz-kompyuterov-mezhdu-soboy) статье.

**Comment by densik3799** [comment]
Прописал так же(Не блокирует.Я его прописал на своей машине где Установлен Adguard

**Comment by EugeneOne1** [comment]
Когда я говорил о первичном и вторичном серверах, я имел в виду "предпочитаемый" и "альтернативный" – их оба необходимо заполнить адресом `127.0.0.1`.

**Comment by densik3799** [comment]
![Снимок PNGbvbvb](https://user-images.githubusercontent.com/35930686/149393531-0d3fc216-1511-4c58-ab96-d4d049aa9d20.PNG)
![Снимок PNGлололл](https://user-images.githubusercontent.com/35930686/149393534-a8a9cf5d-e0fb-434b-87bb-912dcf0ee41c.PNG)

**Comment by densik3799** [comment]
и на том пк там DNS сервера 94.140.14.14 и 94.140.15.15

**Comment by densik3799** [comment]
а тут другие dns сервера

**Comment by densik3799** [comment]
Напишите пожалуйста какие адреса надо ввести и куда?Вы можете самии зайти и настроить чтоб я не тратил Ваше время?

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/149395124-08de2c3b-e7a6-40ea-935d-df068083ca28.PNG)
Я только на этом и хочу чтоб работало все!!!

**Comment by densik3799** [comment]
![Снимок PNGнонно](https://user-images.githubusercontent.com/35930686/149395944-243a84c2-11db-4ce7-8210-e734e4bcced2.PNG)
не работает

**Comment by densik3799** [comment]
Я после этого не запускал Adguard Hom или запустить его?

**Comment by densik3799** [comment]
Запустил службу зашёл в Adguard

**Comment by densik3799** [comment]
![Снимок PNGпрпрпрпр](https://user-images.githubusercontent.com/35930686/149396672-5e6f5858-2a65-48ec-a9b4-64a013a6746d.PNG)
Я же его новый создал и уже столько фильтров заблокировано может это старый остался?(((

**Comment by densik3799** [comment]
![рпрпрпр](https://user-images.githubusercontent.com/35930686/149396912-c8d20925-3e9f-4726-bb0a-99be0c5e0705.PNG)
что в этом адресе мне прописать?

**Comment by EugeneOne1** [comment]
То же самое – `127.0.0.1`

**Comment by densik3799** [comment]
Вот что пишет
![Снимок PNGHJHJHJHJH](https://user-images.githubusercontent.com/35930686/149397352-55ead87d-788c-43bf-94ea-e7edd6234753.PNG)

**Comment by densik3799** [comment]
Уважаемый EugeneOne1  можете сами его настроить через удаленный доступ?

**Comment by EugeneOne1** [comment]
Хорошо, тогда пускай пока будет пустым.  Тот факт, что доступ по адресу `192.168.1.100` получить не удается даже с этого же самого ПК, говорит о том, что что-то настроено неверно.

А есть ли доступ к веб-интерфейсу по адресу `127.0.0.1`?

**Comment by densik3799** [comment]
Зайдите пожалуйста и настройте через программу TeamViewer

**Comment by densik3799** [comment]
Уважаемый EugeneOne1 Я уже буду спать завтра утром на работу рано очень((((Спасибо огромное за Вашу помощь и терпения!!!!!!!!!!!!!!Как тяжело в том разобраться в чем проблема?!((((Завтра времени будет больше выходные будут.Добрых Вам снов!

**Comment by densik3799** [comment]
Добрый вечер Уважаемый ЮджинУан1)))Может мне его удалить и записать видео как я его устанавливаю?

**Comment by densik3799** [comment]
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/7871563/log.txt)
Вчера мы тогда в файле что-то меняли и он образовался в диске D

**Comment by densik3799** [comment]
Записал сейчас пришлю))) первое https://cloud.mail.ru/public/QKBk/UpT5XBcmi

**Comment by densik3799** [comment]
https://cloud.mail.ru/public/KxA9/g64LHPhTM

**Comment by densik3799** [comment]
3 https://cloud.mail.ru/public/NwaP/kF9UviSbF

**Comment by densik3799** [comment]
Сейчас по новой установил только это выбрал 
![Снимок](https://user-images.githubusercontent.com/35930686/149615298-aea49399-8fa3-46b3-bc23-53389ac69371.PNG)
все так же без изменений

**Comment by densik3799** [comment]
Добрый день Уважаемый ЮджинУан1 !))Вы мне поможете с данной проблемой?

**Comment by densik3799** [comment]
Что я делаю не так Уважаемый ЮджинУан1 ?  КАК ПРАВИЛЬНО ЕГО НАСТРАИВАТЬ ЕСЛИ Я СЛЕДУЮ ИНСТРУКЦИИ https://cloud.mail.ru/public/E6Rz/dBbANnJpb

**Comment by densik3799** [comment]
На другой вирт машине и другой windows блокируются сервисы только иногда маил ру нет видео записал.Или где-то adguard hom прописал настройки не правильные или что-то в самой системе неисправность.Или надо что-то включить.https://cloud.mail.ru/public/gYzS/5dn3cFRTY

**Comment by densik3799** [comment]
![Снимок PNGyuuyu](https://user-images.githubusercontent.com/35930686/149637520-e7b666ba-2e8d-4d87-835d-1d2f56708c83.PNG)
Если этот адрес убрать с браузеров то все работает и блокирует))))Но как же быть чтоб мои браузера были по умолчанию Adguard и работал dns
![tytyty](https://user-images.githubusercontent.com/35930686/149637573-059859f8-e7f3-4b1f-8b84-a30df34ce6c7.PNG)
![Снимок](https://user-images.githubusercontent.com/35930686/149637574-0d69509c-c772-4a44-a481-60be38eb5090.PNG)

**Comment by densik3799** [comment]
![Снимок PNGdfdfd](https://user-images.githubusercontent.com/35930686/149637589-c9b433b4-4241-4b2b-a32d-6659ea59f638.PNG)
адрес с браузера убрал и dns отвалился(((

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/149638765-8b6403fb-4455-4882-af69-df8dd35093bc.PNG)
Оставил этот адрес в Adguard Hom а с браузеров по убирал и отключил безопасный DNS и все блокирует и все работает)))Спасибо большое за Ваше время и помощь Уважаемый ЮджинУан1
