### ISSUE TITLE
Filtering rules using name of clients are not working

### ISSUE THREAD

**Issue by Gandulf78** [AdguardTeam/AdGuardHome#4118]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

I have activated the DHCP server on AGH. Clients are identified by their MAC address.

* **Version of AdGuard Home server:**
  * v0.107.2
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * NAS
* **If it's a router or IoT, please write device model:**
  * WDMyCloudEx2Ultra OS5
* **CPU architecture:**
  * ARMv7

### Expected Behavior
Filtering rules by name of clients (||twitter.com$client='iPhone kid'^$important) are working.

### Actual Behavior
Filtering rules by name of clients are currently not working. Only rules by IP address (||twitter.com$client='10.0.0.3'^$important) are working.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@Gandulf78, I presume it doesn't work due to the mistake in the rule, since rule's modifiers should be separated with commas.  Could you please try something like:
```none
||twitter.com$client='iPhone kid',important
```
If it works?

Using the modifiers is also described in this [section](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#modifiers) of wiki.

**Comment by Gandulf78** [comment]
Yes, it is working.   
  
Thank you !
  
  
  
    
  

  
  
>

**Comment by EugeneOne1** [comment]
@Gandulf78, great!  I'll close the issue for now.  Please also consider editing #4108.
