### ISSUE TITLE
Browsing security web service

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#4121]
![image](https://user-images.githubusercontent.com/55087301/148820840-9d54c915-0da0-49cb-9a3b-8a8c9d470d7c.png)

I have multiple outbound links, and lost my main link where DNS routes out for recursion.

I forwarded recursion to another machine on the other side of the network.

These queries (security web service) do no go through the specified upstream, but seem to route instead.

By not having a working default route on the machine running adguard, no recursion was possible until I unchecked this box.

*sigh*

~ 20 minutes

Can these queries use the provided upstream? 

Thank you in advance.

**Comment by DandelionSprout** [comment]
I remember from last year that the AdGuard team is very secretive about how the Browsing Security module works, and which entries they use.

Even [my attempt at reverse-engineering their entries](https://github.com/DandelionSprout/adfilt/blob/master/uBO%20list%20extensions/AdGuardSafeBrowsing-ReverseEngineered.txt) ever got to maybe 1/1000th as many entries as what they use.

**Comment by bcookatpcsd** [comment]
When it stops working, it's crippling.

After I'm done w/ my temper tantrum, I might try AGH again.. 

I just went back to unbound and hblock.

It doesn't have graphs, but it does have the allure of logs to debug problems.. 

I would imagine they are using Quad9 on the other side of their service. 

https://exchange.xforce.ibmcloud.com/

**Comment by ainar-g** [comment]
Hello.  Yes, the safe browsing and parental control services currently use the hardcoded upstream of AdGuard DNS servers.  After all, it uses the AdGuard malware / adult website database.

@ameshkov, how about allowing to set custom upstreams for the situations involving proxies?

**Comment by ameshkov** [comment]
I don't really understand what would custom upstream solve here since you would still need to get to AG DNS to make the query.

Also, this is an optional feature disabled by default, no one is forced to use it.
