### ISSUE TITLE
Incorrect configuration in FAQ for disabling DoH encryption

### ISSUE THREAD

**Issue by rm3l** [AdguardTeam/AdGuardHome#4122]
Hi there!

In the "[How to configure a reverse proxy server for AdGuard Home? > Disable DoH encryption on AdGuard Home](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#disable-doh-encryption-on-adguard-home)" FAQ section, it is written:

> Set `allow_unencrypted_doh: false` in `AdGuardHome.yaml` to allow AdGuard Home respond to DoH requests without TLS encryption.

Instead, we should actually read: "Set **`allow_unencrypted_doh: true`**  in `AdGuardHome.yaml` to allow AdGuard Home **to** respond to DoH requests without TLS encryption." :) 

I would have contributed a PR to fix this, but it looks like this is not possible with GitHub Wikis.

Thanks.

**Comment by EugeneOne1** [comment]
@rm3l, hello and thanks for the report.  This is indeed a typo, thanks for the report.  We'll fix it soon.

**Comment by EugeneOne1** [comment]
@rm3l, fixed.  I'll close the issue if you don't mind.

**Comment by rm3l** [comment]
Thanks, @EugeneOne1 !
