### ISSUE TITLE
ADH的DHCP功能无法正常使用

### ISSUE THREAD

**Issue by ameete** [AdguardTeam/AdGuardHome#4123]
不管是openwrt下装adguardhome插件还是在群晖下docker运行adguardhome都无法启动DHCP。
报错未无法检测是否使用静态地址，i/o timeout，无法检测网络是否有dhcp服务器
需要什么特别的设置吗，还是有bug？openwrt创建新接口也不行，群晖的是bridge接口

**Comment by ainar-g** [comment]
Hello.  As I understand, you are trying to enable the DHCP server, but AGH cannot verify that the IP of your router is static?  Is the IP address of your router static?  If so, can you please add the version of AGH and the logs of errors you're getting?  Thanks!

* * *

(自动翻译。)

你好。 据我所知，你是想启用DHCP服务器，但AGH无法确认你的路由器的IP是静态的？ 你的路由器的 IP 地址是静态的吗？ 如果是的话，请你添加AGH的版本和你得到的错误日志？ 谢谢!

**Comment by Birbber** [comment]
@ameete Hi! Is this issue still relevant?

**Comment by ainar-g** [comment]
No response for over a year.  Closing.

**Comment by facklemackle** [comment]
我也遇到了同样的问题
I've encountered the same problem
