### ISSUE TITLE
DnsRewrite rule not working at all

### ISSUE THREAD

**Issue by mathquis** [AdguardTeam/AdGuardHome#4126]
[ x ] I am running the latest version
[ x ] I checked the documentation and found no answer
[ x ] I checked to make sure that this issue has not already been filed

### Issue Details

- Added a custom rule in the textarea : `||mydomain.com^$dnsrewrite=NOERROR;A;<ip>`
- GUI respond with the correct rule
- `nslookup mydomain.com <adguard-ip>` on Windows 10 (64 bits) respond `Non-existent domain`

* **Version of AdGuard Home server:**
  * v0.107.2 and v0.108.0-a.24+e9c59b09
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Freebox
* **CPU architecture:**
  * ARM64
* **Operating system and version:**
  * Raspbian

### Expected Behavior
- - `nslookup mydomain.com <adguard-ip>` should respond with the IP configured in the rewrite: `<ip>`

### Screenshots
![AdGuard-Home](https://user-images.githubusercontent.com/22168943/149002502-8f8a238f-172a-4976-8640-937c7252b8b1.png)
![AdGuard-Home (1)](https://user-images.githubusercontent.com/22168943/149002554-284d7a59-7eed-40a7-aa82-247d8f37aa09.png)

**Comment by mathquis** [comment]
Turns out the previous DNS Rewrite system (v0.106) worked even if the client does not use "Use global settings" (unfiltered DNS resolution).

The new system only works when using this option.

![AdGuard-Home (3)](https://user-images.githubusercontent.com/22168943/149004008-9773b776-4c69-4889-a379-590f37ae541a.png)

Closing.

**Comment by ppfeufer** [comment]
Have a look under `Filters` » `DNS Rewrites`. Maybe that helps.
