### ISSUE TITLE
Feature Request: Allow disabling of blocked site landing pages

### ISSUE THREAD

**Issue by 88keyz** [AdguardTeam/AdGuardHome#413]
Would it be possible to allow the disabling of the blocked site landing pages for the Security and Parental Control features.  Doing so would simply display a page not found error.

**Comment by dany20mh** [comment]
I hope we get this feature as well, cause it would be very helpful.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/454#issuecomment-499694337
