### ISSUE TITLE
AG does not work properly with DoT when it requires a hostname

### ISSUE THREAD

**Issue by 88keyz** [AdguardTeam/AdGuardHome#414]
Cannot enable DNS over TLS when using CleanBrowsing as the upstream DNS provider even though DoT is supported by CleanBrowsing (https://cleanbrowsing.org/dnsovertls).

Tried with all of the following, all produce connection errors when you "Test upstreams".
```
tls://185.228.168.9:853
tls://185.228.169.9:853
tls://185.228.168.168:853
tls://185.228.169.168:853
tls://185.228.168.10:853
tls://185.228.169.11:853
```

All work without DoT.

Both CloudFlare (tls://1.1.1.1:853) and Quad9 (tls://9.9.9.9:853) work with DoT enabled.

**Comment by ibksturm** [comment]
i think thats a problem of cleanbrowsing themself, not of adguardhome... did you write them a mail, that his dot server falls down?

@cleanbrowsing

**Comment by cleanbrowsing** [comment]
Thanks for tagging us here @ibksturm.

We never tested it with AdGuardHome, so I don't know much how it works, but is there a way to enable debug to see where it is failing? For example, is it a connection failure, certificate issue, etc? How is the test upstream performed? Any information would be helpful. 

I know quite a few people running it with Android's DNS over TLS without any issues, but it requires a hostname instead of an IP address. Would it work if you tried our hostname instead of the IP:

```
security-filter-dns.cleanbrowsing.org
adult-filter-dns.cleanbrowsing.org
family-filter-dns.cleanbrowsing.org
```

@88keyz If you don't mind giving us the output of (maybe in pvt):

```
nslookup -type=txt -class=chaos version.bind 185.228.168.10
nslookup -type=txt -class=chaos version.bind 185.228.168.168
```

It will help us see to which one of our datacenters your traffic is being routed to, so I can try to replicate. This tool is also useful to quickly troubleshoot dns over tls:

https://github.com/dcid/dns-over-tls-php-client

**Comment by ibksturm** [comment]
root@nas1:~# nslookup -type=txt -class=chaos version.bind 185.228.168.10
Server:         185.228.168.10
Address:        185.228.168.10#53

Non-authoritative answer:
version.bind    text = "CleanBrowsing v1.4a - dns-edge-europe-frankfurt"

Authoritative answers can be found from:

root@nas1:~# nslookup -type=txt -class=chaos version.bind 185.228.168.10
Server:         185.228.168.10
Address:        185.228.168.10#53

Non-authoritative answer:
version.bind    text = "CleanBrowsing v1.4a - dns-edge-europe-frankfurt"

Authoritative answers can be found from:

**Comment by ibksturm** [comment]
root@nas1:~# nslookup -type=txt -class=chaos version.bind 185.228.168.168
Server:         185.228.168.168
Address:        185.228.168.168#53

Non-authoritative answer:
version.bind    text = "CleanBrowsing v1.4a - dns-edge-europe-frankfurt"

Authoritative answers can be found from:

**Comment by 88keyz** [comment]
Here are the results.

```
C:\>nslookup -type=txt -class=chaos version.bind 185.228.168.10
Server:  adult-filter-dns.cleanbrowsing.org
Address:  185.228.168.10

Non-authoritative answer:
version.bind    text =

        "CleanBrowsing v1.4a - dns-edge-usa-east-newyork"
```
```
C:\>nslookup -type=txt -class=chaos version.bind 185.228.168.168
Server:  family-filter-dns.cleanbrowsing.org
Address:  185.228.168.168

Non-authoritative answer:
version.bind    text =

        "CleanBrowsing v1.4a - dns-edge-usa-east-newyork"
```
```
$ php dnstls.php adguard.com cleanbrowsing
adguard.com has address 104.20.31.130
adguard.com has address 104.20.30.130
```

This is the error that is produced in AdGuard Home

![cleanbrowsing_dot_error](https://user-images.githubusercontent.com/5501415/47269569-e78fb680-d52d-11e8-83aa-82f765c80a25.jpg)

**Comment by ameshkov** [comment]
This is a bug indeed, AG does not work properly with DoT when it requires a hostname.

**Comment by ameshkov** [comment]
Resolved with https://github.com/AdguardTeam/AdGuardHome/commit/4a357f1345bed8bb43027236feff0bc4b92de8fc

Here's how to use it:
https://github.com/AdguardTeam/AdGuardHome/issues/453
