### ISSUE TITLE
GUI improvement: Client Settings Page - Contextual Sorting when clicking on column headers

### ISSUE THREAD

**Issue by gspannu** [AdguardTeam/AdGuardHome#4143]
Client Settings Page.
Clicking on column headers sorts the columns.

Assume the clients are defined by their IP addresses like

> 192.168.1.10
> 192.168.1.11
> 192.168.1.20
> 192.168.1.31 
> 192.168.1.100
> 192.168.1.101
> 192.168.1.205 etc…

Sorting on the Client column should sort it like the above (i.e. mathematically incrementing ).. however, the sorting is actually done as if the data was text

> 192.168.1.10
> 192.168.1.100
> 192.168.1.101
> 192.168.1.11
> 192.168.1.20
> 192.168.1.205
> 192.168.1.31 

**Could this small GUI improvement be included in the next build please?**

**Comment by ainar-g** [comment]
Thanks for the report!  How would you prefer the clients to be sorted when a CIDR, a MAC, or a ClientID is used?  The fact is, the client identifiers are text that is interpreted differently depending on the content.

I think we could use the IP comparison if both identifiers are IP addresses and switch to text comparison if either one of them is text, but I'm not sure.

@IldarKamalov, would that be feasible?

**Comment by gspannu** [comment]
> Thanks for the report! How would you prefer the clients to be sorted when a CIDR, a MAC, or a ClientID is used? The fact is, the client identifiers are text that is interpreted differently depending on the content.
> 
> I think we could use the IP comparison if both identifiers are IP addresses and switch to text comparison if either one of them is text, but I'm not sure.
> 
> @IldarKamalov, would that be feasible?

I think **mathematical number sort** (if any numbers are involved, else text).
The would be the simple approach; although it may not be that simple to implement !

**Comment by ainar-g** [comment]
@gspannu, I think you mean what is called [natural sorting][1].  We'll consider that in the future, but for now the today's `edge` release applies IP address comparison logic for the appropriate identifiers.  Can you please check if our solution works for you?

[1]: https://en.wikipedia.org/wiki/Natural_sort_order

**Comment by gspannu** [comment]
> @gspannu, I think you mean what is called [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order). We'll consider that in the future, but for now the today's `edge` release applies IP address comparison logic for the appropriate identifiers. Can you please check if our solution works for you?

**Just tested... IP address sorting works like a charm.** 
Thanks.
