### ISSUE TITLE
Не видит не одного клиента adguard Hom Частые клиенты за 24 часа

### ISSUE THREAD

**Issue by densik3799** [AdguardTeam/AdGuardHome#4144]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

![Desktop Screenshot 2022 01 16 - 12 22 51 36](https://user-images.githubusercontent.com/35930686/149654367-c9c88d63-6162-4055-b0a0-a8b6496c3e14.png)
![Снимок](https://user-images.githubusercontent.com/35930686/149654369-bc4125ba-bbda-4ebc-956b-41ab9da4b367.PNG)
![Снимок PNGЕНЕНЕН](https://user-images.githubusercontent.com/35930686/149654370-e691e4bf-c88e-4d29-b014-ba45984c1a87.PNG)
Добрый день Уважаемый разработчики!!!Помогите пожалуйста много раз переустанавливал Adguard Hom и раньше были видны Частые клиенты сейчас windows 10 установил по новой и все равно не отображаются частные клиенты.Помогите пожалуйста решить данную проблему?

**Comment by densik3799** [comment]
Есть тут кто???

**Comment by ainar-g** [comment]
Добрый день.  Заполните, пожалуйста, шаблон в описании проблемы.  Для нас особенно важно знать ОС, версию, и метод установки.  Также, для того, чтобы ваши устройства работали только с AGH, вам нужно проставить адреса сервера в *оба* поля.

**Comment by densik3799** [comment]
Добрый вечер Айнар.Спасибо большое,что ответили))))Думал уже никто не ответит.Проблема в том,что Adguard Hom не видит подключенных к нему устройств через роутер тр-Link wr-740n.Windows 10 LTSC 64 bit.Это куда вписать два адреса в pv4 или в роутере?

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/150544661-ad5b1dfd-5687-4f2a-a2b3-ebcb7e8d2689.PNG)
Сюда их вписать правильно?Установка была через cmd c этого сайта https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#installation

**Comment by ainar-g** [comment]
Каким именно образом подключены устройства?  «Через роутер» значит, что AdGuard Home установлен в качестве DHCP-сервера на этом роутере или схема какая-то иная?

 >  Это куда вписать два адреса в pv4 или в роутере?

Если AdGuard Home не является DHCP-сервером, то IP-адрес машины, на которой он установлен, надо вставить в оба поля в настройках ОС-клиентов.

**Comment by densik3799** [comment]
Да через  маршрутизатор он почему-то эти DHCP-сервера сбрасывает(
![Снимок PNGмсмва](https://user-images.githubusercontent.com/35930686/150546884-ffc79635-574d-4ede-ab01-810e4524fea3.PNG)
Сюда их вписывал и тут их убирал 
![Снимок PNGвавава](https://user-images.githubusercontent.com/35930686/150547072-ddf88f30-ebb3-4b40-a88e-bbba06b87c8c.PNG)

**Comment by densik3799** [comment]
Где синим обвел там он не хочет работать(А красным я там все убирал ставил 0.0.0.0.

**Comment by densik3799** [comment]
Я понимаю это надо сделать на пк?то IP-адресом машины, на котором он установлен, необходимо вставить в оба поля задействованных ОС-клиентов.Пришлите пожалуйста скриншот куда их вставить и какие адреса?

**Comment by densik3799** [comment]
![кук](https://user-images.githubusercontent.com/35930686/150551427-945bb569-8434-4a62-ac28-48db47485af8.PNG)
Я эти адреса ввел на другом пк нет интернета и устройств не видно телефонов которые подключены к маршрутизатору.

**Comment by ainar-g** [comment]
На ваших скриншотах видно, что AdGuard Home не является DHCP-сервером в вашей сети.  Им является роутер (это ведь скриншоты его панели?).

На какой машине установлен AdGuard Home?  Для этой машины есть статический IP-адрес?  Если адрес для машины с AdGuard Home не настроен статически, его адрес будет меняться, что приведёт к проблемам с соединением.

**Comment by densik3799** [comment]
Да это скриншоты маршрутизатора моего роутера.А как сделать чтоб Adguard Hom DHCP являлся моей сетью скажите пожалуйста Уважаемый Айнар?Adguard Hom установлен на основной машине windows 10 LTSC.Не пойму Вашего вопроса(Для этой машины есть готовый IP-адрес?)Как узнать готовый IP-aврес?

**Comment by densik3799** [comment]
![Снимок PNGапапапап](https://user-images.githubusercontent.com/35930686/150567033-11252695-944c-4899-aaaa-34381a038403.PNG)

**Comment by densik3799** [comment]
Спасибо большое что помогаете мне!!!Я уже с 8 января не могу решить данную проблему(((

**Comment by densik3799** [comment]
![Снимок PNGмсмсмсм](https://user-images.githubusercontent.com/35930686/150567549-7c016415-3f4f-49ba-8b10-89327f6984dd.PNG)
Только мою машину основную и видит.

**Comment by densik3799** [comment]
![Снимок PNGимимим](https://user-images.githubusercontent.com/35930686/150567886-91485622-ea96-456a-9430-601aa6a8d8b8.PNG)
Тут этот IP-адрес есть?

**Comment by densik3799** [comment]
Мне очень жаль я наверное не смогу это все настроить(((((Это тут эти адреса???
![Снимок PNGапапп](https://user-images.githubusercontent.com/35930686/150569708-33fe54e4-3a6a-443b-9399-e4611124829f.PNG)
А не могли бы Вы мне его сами настроить через удаленный доступ Уважаемый Айнар?

**Comment by densik3799** [comment]
Куда мне эти мас адреса вести нужно?

**Comment by densik3799** [comment]
Спасибо огромное Уважаемый Айнар))))))))))))))))))))Я ОТКЛЮЧИЛ ЗАЩИТНИК WINDOWS И ЗАРАБОТАЛО!!!!!!!!!!!!!!!!!!!!!!!!!
![Снимок](https://user-images.githubusercontent.com/35930686/150572756-1f5a59ac-9f21-40ef-a632-ca7a69365942.PNG)

**Comment by densik3799** [comment]
Но почему-то второй пк не видит и второй телефон(
![Снимок PNGимм](https://user-images.githubusercontent.com/35930686/150573523-48a20b92-f67c-4b7e-a161-6006f68780e3.PNG)
в роутере есть в adguard hom нет(((

**Comment by densik3799** [comment]
5 адресов не знаю что за адреса если только пк работает  один в данный момент.

**Comment by densik3799** [comment]
Доброе утро Айнар!)))Заново переустановил Adguard Hom и испытал через заблокированные сервисы сайты и на пк и на андроиде блокирует и уже на андроиде блокирует рекламу в хроме увидел его
![Снимок](https://user-images.githubusercontent.com/35930686/150630758-86cc8998-a28f-428e-8a2c-ced23ad649e2.PNG)
 что блокируется реклама))) Адреса так прописаны. Андроиде работает.(даже не знаю какой адрес-клиент в Hom отвечает за андроид.По роутеру два пк есть андроид и тоже есть но в Hom я не могу найти андроид(В пк только тут прописано.
![Снимок PNGсмсм](https://user-images.githubusercontent.com/35930686/150630793-9346a96b-5e87-45c5-b73f-09c5e721e932.PNG)
больше ничего нигде не настраивал другой пк там все адреса по умолчанию.

**Comment by densik3799** [comment]
Скажите пожалуйста как узнать какие это клиенты?Сейчас только пк включен и все.
![Снимок PNGрпрп](https://user-images.githubusercontent.com/35930686/150630956-7c310864-ce66-488f-b755-7f55b3916fbe.PNG) и 4 клиенты работают.

**Comment by densik3799** [comment]
![Снимок](https://user-images.githubusercontent.com/35930686/150634121-27db523a-2e18-486b-a8bf-2a79f3d3021c.PNG)
Очистил журнал два клиента это роутер и пк?Только пк в данный момент работает.

**Comment by densik3799** [comment]
Афнар!Спасибо огромное Вам за помощь и терпения!!!Я УДАЛИЛ Adguard Hom.Не смог я его настроить правильно и даже с одним адресом как я делал раньше пропадает интернет.)а раньше работало без отвалов).Буду без него.
