### ISSUE TITLE
Add dark mode in adguard home like in pi hole

### ISSUE THREAD

**Issue by MaxedLevelHero** [AdguardTeam/AdGuardHome#4148]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by EugeneOne1** [comment]
@MaxedLevelHero, hello.  We already have the feature request (#613) about that.  Closing as a duplicate.
