### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by MaxedLevelHero** [AdguardTeam/AdGuardHome#4149]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

* * *

i feel that the latest version has been awfully slugish emm i mean everything form how to long it takes to load and whenever i add a couple of blocklists it just freezes and overall experience is not snappy compared to pi hole . i switched to adguard home from pi hole seeing all the benefits and all but i didnt expect this. the queries are also slower than pi hole . im gravely dissapointed .i wish for adguardhome team to optimize the code and implement the latest and fastest technologies and softwares.Waiting for good updates and optimizations. And btw add dark mode Firstt !!!!

**Comment by jamesmacwhite** [comment]
Who knew tat issue titles could be that long. I think the GitHub devs should consider a max length. Wow!

It might worth [posting this as a discussion](https://github.com/AdguardTeam/AdGuardHome/discussions) instead!

**Comment by ainar-g** [comment]
Hello.  Please fill out the full issue template so that we could diagnose the performance issues better.

The dark theme feature request is #613.
