### ISSUE TITLE
[Feature Request] 'Clear statistics' option on Dashboard

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#415]
Could there be an option somewhere to clear the statistics from AdGuard Home? It would be useful especially after modifying the filters, or when I want to have new statistics after setting it up and playing around on first install.

**Comment by rfgamaral** [comment]
I've just setup AdGuard and I'm still in the "playing around" phase and I was looking for such an option (just like Pi-Hole as) and couldn't find one. I'm here showing my support for such a feature 👍 

In the meantime, deleting the `/opt/adguardhome/work/data/querylog.json` file does the trick.

**Comment by ArchiveBase** [comment]
Already implemented https://github.com/AdguardTeam/AdGuardHome/issues/446

**Comment by ameshkov** [comment]
Yup, available in the v0.99 beta version. Closing this issue now
