### ISSUE TITLE
Config values in dhcp.dhcpv4.options are not sent

### ISSUE THREAD

**Issue by Maxouwell** [AdguardTeam/AdGuardHome#4152]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.107.2 (Home Assistant AdGuard Home addon v4.4.2 https://github.com/hassio-addons/addon-adguard-home )
* **How did you install AdGuard Home:**
  * Addon for Home Assistant OS (Docker install as far as I understand)
* **How did you setup DNS configuration:**
  * ?
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 3 Model B
* **CPU architecture:**
  * ARM
* **Operating system and version:**
  * Home Assistant OS

### Expected Behavior
The DHCP server should send any options defined in the configuration file

### Actual Behavior
The defined options are not sent

### Screenshots
AdGuardHome.yaml dhcp configuration : 
![image](https://user-images.githubusercontent.com/13748802/149680752-5d5fd5fc-5757-4bbe-a39e-fafe2ea2e5b5.png)

DHCP test request : 
![image](https://user-images.githubusercontent.com/13748802/149680847-10291edb-bddd-4d45-8dad-2f6ecbaef79b.png)
( With https://blog.cy.md/2013/01/10/dhcp-test-client/ )

### Additional Information
The configuration file is loaded, as the "verbose: true" option is working

**Comment by EugeneOne1** [comment]
@Maxouwell, hello.  As per [RFC 2131](https://datatracker.ietf.org/doc/html/rfc2131#section-4.3.1):

> The server MUST return to the client:
>    * ...
> 
>    * Parameters **requested by the client**, according to the following rules:
>
>         -- IF the server has been explicitly configured with a default value for the parameter, the server MUST include that value in an appropriate option in the 'option' field, ELSE
> 
>         -- IF the server recognizes the parameter as a parameter defined in the Host Requirements Document, the server MUST include the default value for that parameter as given in the Host Requirements Document in an appropriate option in the 'option' field, ELSE
> 
>         -- The server MUST NOT return a value for that parameter,

It seems AGH simply doesn't put non-requested options into the DHCP reply which is an expected behavior.  However, wording of the document may be interpreted variously to be fair.

Could you please try to explicitly request the options needed?  It seems the tool you referred to allows specifying those with an `--option CODE=VALUE` parameter.

**Comment by Maxouwell** [comment]
Hello and thanks for the response,

You're indeed right, the device (a Livebox TV decoder) which needed the option 125 is working as intended.
I was fooled by the response of my internet provider adsl modem (a Livebox v3), which responded the 125 option systematically.

Thanks for your help.
