### ISSUE TITLE
请问是否采用我的规则

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#4159]
International/China accelerated ad filtering rules subscription.
国际/中国加速广告过滤规则订阅
Trli rules is the only global library that provides a complete set of rules, and the rules are updated 24 hours a day, probably starting at 0:00 US time.
冷莫(trli)的规则唯一一个提供全球比较全的库，规则是24小时更新，大概是第二天的从美国时间0点开始。 

文件库:trli.coding.net/public
说明库:github.com/Potterli20/hosts
Library: trli.coding.net/public 
That library: github.com/Potterli20/hosts

adguardhome:https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adguardhome.txt

**Comment by ainar-g** [comment]
Hello.  If you would like this filter rule list to be added to AGH, you should probably write to the vetted list thread there: #1913.  I'll close this issue.

If this is not what you wanted, please write a more elaborate proposal, in any language.

* * *

(自动翻译。)

你好。如果你希望这个过滤规则列表被添加到AGH，你可能应该写到那里的审核列表主题：#1913。我将关闭这个问题。

如果这不是你想要的，请写一份更详细的建议，用任何语言。
