### ISSUE TITLE
docker version v0.107.2    validating ports: duplicated values: [3000]

### ISSUE THREAD

**Issue by yanxin152133** [AdguardTeam/AdGuardHome#4161]
docker image version v0.107.2 
"validating ports: duplicated values: [3000]" appears when deploying

**Comment by EugeneOne1** [comment]
@yanxin152133, hello.  I suppose this is a duplicate of #4095.  Note the [comment](https://github.com/AdguardTeam/AdGuardHome/issues/4095#issuecomment-1008904663).
