### ISSUE TITLE
traefik issue with dns challenge - rewrite rules ignored by certain clients

### ISSUE THREAD

**Issue by averon420** [AdguardTeam/AdGuardHome#4168]
Hello,

I use adguardhome and iptables to force any DNS requests to my adguardhome server. I made a rewrite rule to redirect my public domain to my internal IP of the related server. The idea is to use DNS challenge to get a valid SSL cert for an internal service (traefik).

The issue is, that my traefik service can't resolve the public IP of my domain anymore, because of the rewrite rule.

I tried to force a public DNS server, via client settings, for my traefik server, so the server can resolve my public IP and my other clients still resolve the internal IP, but it doesn't ignore the rewrite rule. 

How can I make a rewrite rule, which is ignored by certain clients?

Running newest version of Adguardhome on my Unify dream machine (docker container)

Thanks for the help

**Comment by EugeneOne1** [comment]
I think, the `~client` modifier may help here.  For example:

```none
||example.org^$dnsrewrite=NOERROR;A;1.2.3.4,~client='client-name'
```

This should ignore the rule for client with name `client-name`.  If it is what you're trying to achieve?

**Comment by averon420** [comment]
> 

thanks a lot! didnt even know about those features. took me a while but it works now as intended.

`||example.orge^$dnsrewrite=NOERROR;CNAME;hostname.local,client=~10.1.0.10|10.1.0.0/24`

thanks again!
