### ISSUE TITLE
[Help] No internet connectivity

### ISSUE THREAD

**Issue by Vercety87** [AdguardTeam/AdGuardHome#417]
Hi,

Just installing AdGuard Home in my server.

But while setting my DNS to my AdGuard Home server, my device say "Connected to Wifi, but no internet connectivity.

My AdGuard Home server ip is 192.168.0.28, and I set this IP to my device DNS setting.

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9-hotfix1
| How did you setup DNS configuration:| Android Wifi Configuration
| Operating system and version:| Ubuntu 10.0.4.1

**Comment by Vercety87** [comment]
Thanks for your help. 

I used port 1024, just added this port to iptables but same problem. 

Nslookup doesn't return anything with my ip.

**Comment by ameshkov** [comment]
> I used port 1024, just added this port to iptables but same problem.

Did you use port 1024 for the DNS server?

Please show me the output of this command:
```
nslookup -port=1024 example.org 192.168.0.28
```

**Comment by Vercety87** [comment]
Here the result:

nslookup -port=1024 google.fr 192.168.0.28                            Server:192.168.0.28
Address:192.168.0.28#1024

Non-authoritative answer:
Name:google.fr
Address: 216.58.213.131
Name:google.fr
Address: 2a00:1450:4007:805::2003

**Comment by ameshkov** [comment]
So the DNS server is okay. Are you sure your device supports configuring a DNS server on a non-standard port?

**Comment by Vercety87** [comment]
I tried with my Android Phone running Android 9 and on my iPhone 6s they must be ok with that? I'm gonna tried on port 53.

**Comment by Vercety87** [comment]
Works great with port 53. Thanks for your help.
