### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by Nobel-AK** [AdguardTeam/AdGuardHome#4173]
No IPv6 Hostname resolv over FRITZ!box DHCP and unbound@5335 
Everthing searched and tested but the ptr-request ends with serverfail

**Comment by ainar-g** [comment]
Hello.  Please add the following information to help us diagnose the problem:

 *  What is your OS?

 *  Is AdGuard Home the DHCP server of your network?

 *  Which DNS queries fail to resolve?  An example using `dig` or `nslookup` would be great.

Thanks.
