### ISSUE TITLE
这个怎么解决 responding to udp request

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#4174]
相关问题https://github.com/AdguardTeam/dnsproxy/issues/196
然后我的adgh就出现这些问题
![Screenshot_2022-01-21-09-59-18-120_com termux](https://user-images.githubusercontent.com/28734349/150452601-dfa24171-390d-44ea-b2d9-02aca897d160.jpg)

我服务器是禁了ping，这个问题好奇怪

**Comment by ainar-g** [comment]
Hello.  Are you sure that it's not a firewall?  Can you inspect your system's logs to see if SELinux or things like that don't interfere?

 * * *

(自动翻译。)

你好。 你确定这不是一个防火墙吗？ 你能检查一下你的系统日志，看看SELinux或类似的东西是否没有干扰？

**Comment by Potterli20** [comment]
> Hello. Are you sure that it's not a firewall? Can you inspect your system's logs to see if SELinux or things like that don't interfere?
> 
> (自动翻译。)
> 
> 你好。 你确定这不是一个防火墙吗？ 你能检查一下你的系统日志，看看SELinux或类似的东西是否没有干扰？

Don't. But it's weird.

**Comment by ainar-g** [comment]
We currently don't have any other theories besides firewalls and other access control stuff like that, sorry.

 * * *

(自动翻译。)

除了防火墙和其他访问控制之类的东西，我们目前没有任何其他理论，抱歉。
