### ISSUE TITLE
希望使用nginx后，AdGuardHome能正确获取客户端IP ：Hopefully, after using nginx, AdGuardHome can correctly obtain the client IP

### ISSUE THREAD

**Issue by hacamer** [AdguardTeam/AdGuardHome#4175]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

当我使用nginx反代AdGuardHome时
DoH无法显示客户端IP 显示为服务器IP
When I use nginx anti-AdGuard Home
DoH cannot display client IP as server IP
### Proposed Solution

Use real_ip_header to fetch client IP
使用 real_ip_header 来获取客户端IP

**Comment by Potterli20** [comment]
多看wiki

**Comment by ainar-g** [comment]
Hello.  Like Potterli20 above has said, we have some information about that on the [FAQ page][1] on the Wiki.  The thing that isn't mentioned there (but is mentioned on the [other page][2]) is that you also need to set the `trusted_proxies` setting to the IP address of your proxy.  We'll update the FAQ to reflect that.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy
[2]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration

**Comment by ainar-g** [comment]
We've now added the information to the Wiki.  Please feel free to open new issues when you find the information there incomplete or incorrect.
