### ISSUE TITLE
AdHome page information for blocked site

### ISSUE THREAD

**Issue by Vercety87** [AdguardTeam/AdGuardHome#418]
The first time I used AdHome, when trying to browse a blocked website, AdHome was showing me an information page with explanation for user.

Now this page doesn't show, I just have an error:

This site can’t be reached
googleads.g.doubleclick.net refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9-hotfix1
| How did you setup DNS configuration:| System
| Operating system and version:| Ubuntu 10.0.4.1
--

**Comment by ameshkov** [comment]
The behavior is different for the websites blocked by the parental control or browsing security modules (an access denied page) and for the websites blocked by any of the filters.

We will add an option to return a "blocked request" page for the latter as well (there's a feature request about that).

**Comment by ibksturm** [comment]
any news about the custom blocking page?

**Comment by ameshkov** [comment]
> any news about the custom blocking page?

Not until we deal with DHCP and web setup #423 #425
