### ISSUE TITLE
EDNS Client Subnet feature cannot be used when using a VPN

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#4187]
### Prerequisites
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

I use Wireguard and WG-based VPNs where clients have non-public IPs with non-private subnets. E.g. Tailscale uses the CGNAT IP range (`100.64.0.0/10`) to assign IPs to machines.

As a result, I cannot use ECS (EDNS Client Subnet) with AdGuard Home, since clients don't have public IPs.

### Proposed Solution

The ability to specify a custom ECS subnet per configured client, e.g. `1.1.1.0/24`. AdGuard Home sends this subnet as ECS data to upstream servers.

### Alternatives Considered

Using DNS-over-HTTPS or DNS-over-TLS without a VPN. This is not really suitable because certs need to be created and renewed manually and does not preserve privacy that comes with a VPN

**Comment by ainar-g** [comment]
Merging into #1472.
