### ISSUE TITLE
Client IP resolution when running in Cloud.

### ISSUE THREAD

**Issue by sudheeshb** [AdguardTeam/AdGuardHome#4188]
Adguard Home Version: v0.106.3 in Debian.

  I am running AdGuard Home in Cloud sever.  I connected to Adguard Home via Wireguard VPN tunnel.  The Wireguard server runs in the cloud  server and client in my pfsense router.   Everything works fine except for Client IP resolution.  All the Client IP is shown as pfsense IP ( say 10.6.0.1 ), which is as expected.

Issue:  I need the Client IP resolution for every device. Hence  I configured Pfsense to pass EDNS0 with dnsmasq.   This works well in pihole.   Details here.  

https://www.reddit.com/r/pihole/comments/me7wjo/pihole_on_cloud_hostname_resolution/

However Adguard home shows only my pfsense IP as the Client IP  for all the devices even with EDNS0 enabled.   Please suggest a  solution for the same.

**Comment by gtxaspec** [comment]
#3978 I think we have the same issue

**Comment by sudheeshb** [comment]
Thanks. Agree.  Looks like the issue is same.  This works well in pihole.

**Comment by ainar-g** [comment]
Merging into #3976.
