### ISSUE TITLE
Backup settings

### ISSUE THREAD

**Issue by Codgi-123** [AdguardTeam/AdGuardHome#4189]
need a feature that can back up current settings for easy migration and restoration

**Comment by ppfeufer** [comment]
Cronjob » `cp /opt/AdGuardHome/AdGuardHome.yaml /to/where/ever/you/want/`

**Comment by Codgi-123** [comment]
> Cronjob » `cp /opt/AdGuardHome/AdGuardHome.yaml /to/where/ever/you/want/`

Thanks, this is indeed a good approach, but a visual approach might be better

**Comment by kerryland** [comment]
Also not true. This does not backup dhcp static leases. You really need to backup the entire AdGuardHome directory.

**Comment by ainar-g** [comment]
Duplicate of #1147
