### ISSUE TITLE
Verify DNS filtering fails with doubleclick.net

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#419]
When following the [guide to set up AdGuard Home on Raspberry Pi](https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi), there is the section to verify DNS filtering.

Leaving everything set as default (so only the AdGuard SDNS filter is enabled), using `host doubleclick.net 127.0.0.1` always results in it not being blocked.

> Using domain server:
> Name: 127.0.0.1
> Address: 127.0.0.1#53
> Aliases:
> 
> doubleclick.net has address 216.58.203.110
> doubleclick.net has IPv6 address 2404:6800:4006:809::200e
> doubleclick.net mail is handled by 30 alt2.aspmx.l.google.com.
> doubleclick.net mail is handled by 40 alt3.aspmx.l.google.com.
> doubleclick.net mail is handled by 50 alt4.aspmx.l.google.com.
> doubleclick.net mail is handled by 10 aspmx.l.google.com.
> doubleclick.net mail is handled by 20 alt1.aspmx.l.google.com.

If I use a different one, like `host ad.doubleclick.net 127.0.0.1` or `host g.doubleclick.net 127.0.0.1`, then I get the expected `Host ad.doubleclick.net not found: 3(NXDOMAIN)`.

> Using domain server:
> Name: 127.0.0.1
> Address: 127.0.0.1#53
> Aliases:
> 
> Host ad.doubleclick.net not found: 3(NXDOMAIN)

Is `doubleclick.net` meant to go through? At the moment it is even though the Wiki uses it to verify filtering.

**Comment by ameshkov** [comment]
Good catch:)

Ads aren't loaded from that domain, but anyway, it makes sense to have it blocked:
https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/962b11b8ae5fde0b01a49087c6f3e26cbe3dd53e
