### ISSUE TITLE
Ability to log in json format

### ISSUE THREAD

**Issue by onedr0p** [AdguardTeam/AdGuardHome#4193]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I would like AGH to log in JSON format, this would be nice for machine to machine aggregation of logs, for example with use for tools like `Loki` or the `ELK` stack.

### Proposed Solution

Add an option to ship logs in json format.

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by ammnt** [comment]
This is really best practice for Elasticsearch and OpenSearch logs parsing. This is important👏🏼

**Comment by onedr0p** [comment]
Closing this issue, doesn't appear to have any priority from the developers and I no longer use AGH.

**Comment by D13410N3** [comment]
@onedr0p Hello, what logs are you talking about? If it is about "dns query log" - it is in JSON and may be easy collected via everything you want - logstash, vector, promtail etc.
