### ISSUE TITLE
Many requests for a specific domain

### ISSUE THREAD

**Issue by jay9455** [AdguardTeam/AdGuardHome#4198]
Hi I have installed AdGuard Home on my personal aws and am using it personally.

Normally, only about 10,000 requests were received a day, but when I suddenly checked, I got 760000 requests today.

All requests were going to 'microsoft.com', and the request IP was China or Hong Kong, and dozens to hundreds of requests were coming in every second.

In this case, I am worried that my aws resources will be consumed a lot and I will be charged a lot.

How can I solve this?

I have attached a picture of the monitoring status below.

![whatap](https://user-images.githubusercontent.com/83913698/150999082-e903a9b5-ead2-4a83-80f8-5f7041b96e57.PNG)

![1](https://user-images.githubusercontent.com/83913698/150999123-080028d5-6327-4c55-a44c-6a6f0d8176dd.PNG)

![2](https://user-images.githubusercontent.com/83913698/150999126-f5e8b896-a130-45e5-b98c-84e84ab22aba.PNG)

**Comment by Birbber** [comment]
Closing this one as completed. Feel free to re-open if needed.
