### ISSUE TITLE
provide a dedicated version-flag for cli

### ISSUE THREAD

**Issue by WoodenDoors** [AdguardTeam/AdGuardHome#420]
Adguard Home currently always prints a line containing the current version, first thing when it starts. If I just want to check the version of the binary, without actually starting it, the closest I have is the `--help`flag.

```shell
$ ./AdGuardHome --help
2018/10/23 00:07:55 AdGuard Home web interface backend, version v0.9-hotfix1
[...]
```
Problem is that this is probably not an intended use case (or maybe it is?), so to me it feels wrong to depend on it.

### Expected behavior
1. a dedicated `-v`/`--version` Flag to print just a line containing the current version.
2. print to stdout (currently prints to stderr)
3. exit with a return code of `0` (currently is `64`)

It would also be really great if you could use something like [SemVer](https://semver.org/) with a patch-decimal (instead of the current `hotfix1`-suffix), if that's feasible, since that's slightly easier to parse and more importantly searching for a specific version like `v0.9` returns both (`v0.9` and `v0.9-hotfix`). Maybe that's planned for Version 1+, so I'll keep my fingers crossed on that for now.

**Comment by szolin** [comment]
v0.101
