### ISSUE TITLE
cannot access login panel after update

### ISSUE THREAD

**Issue by shukryshuk** [AdguardTeam/AdGuardHome#4206]
after updated to version v0.107.3, i cannot access my  adguardhome login panel and dashboard, happened when only if i connected to dns-over-tls. and one more , when i ping my server from windows11 and android, the output show it redirect to 127.0.0.1. 

![image](https://user-images.githubusercontent.com/55014736/151097278-2247f1d6-a156-4e68-9a64-90a62c9318ae.png)

this happened in windows 11 and my android phone
my server is in linode

**Comment by ainar-g** [comment]
Hello.  Please add the following information:

1.  What was the version before that?  v0.107.2?

2.  Can you enable [verbose logging][1] and look, what kind of logs are printed?

3.  Is the web UI accessible if you try the IP address instead of the hostname?

Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by shukryshuk** [comment]
> 

1. yes v0.107.2
2. i enabled it and pretty much show normal log 
3. i tried with ip address, yes same things happened, i still cant access login panel

**Comment by ainar-g** [comment]
Does your Linode VM have a static IP?  Also, which IP is in the top-level `bind_host` parameter of the configuration file?  Perhaps, the server IP has changed?

**Comment by shukryshuk** [comment]
> Does your Linode VM have a static IP? Also, which IP is in the top-level `bind_host` parameter of the configuration file? Perhaps, the server IP has changed?

yes it is static ip.
bind_host: 0.0.0.0

**Comment by ainar-g** [comment]
I assume that there is an HTTP proxy in front of AGH, considering that it's on the cloud?  If there is, perhaps there's something with the proxy?

Other than that, I currently don't have any clues, sorry.

**Comment by shukryshuk** [comment]
> I assume that there is an HTTP proxy in front of AGH, considering that it's on the cloud? If there is, perhaps there's something with the proxy?
> 
> Other than that, I currently don't have any clues, sorry.

do u know how can i look into it?

**Comment by shukryshuk** [comment]
> That depends on what kind of proxy is used. Usually, there should be something in the proxy's logs.

SOLVED

I restored my /etc/hosts file to default

thank you .
