### ISSUE TITLE
Document the manual update process

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4208]
(Split from #4203.)

We should document the manual update process either in the “FAQ” page of the Wiki or on the “Getting Started” page.  Making sure that we mention stopping AGH and updating services (e.g. `systemctl daemon-reload`.)

**Comment by mercyground** [comment]
As part of the work i did with OpenWrt and the growing size of the 107 build https://github.com/AdguardTeam/AdGuardHome/issues/3801

I ended up creating this script for AGH updates on smaller space routers to update over the top of AGH (cuts the space requirements down as we dont backup AGH). Obviously needs a bit of tweaking to get the proper arch for the device the script runs on. But a starting point for manual updates?

```
#!/bin/sh
#Stop AGH
/etc/init.d/AdGuardHome stop 

#Grab updated AGH from server and save to /tmp
wget https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mips_softfloat.tar.gz -P /tmp

#unzip updated file over top of AGH in /opt
tar x -vzf /tmp/AdGuardHome_linux_mips_softfloat.tar.gz -C /opt

#cleanup /tmp
rm /tmp/AdGuardHome_linux_mips_softfloat.tar.gz

#Restart AGH
/etc/init.d/AdGuardHome start
echo 'Updated'
```

**Comment by ainar-g** [comment]
@mercyground, thanks!  Any reason why you're using the `init.d` action instead of `AdGuardHome -s stop`, for example?

Also, when unpacking directly to `/opt`, people should be aware that that won't delete files that are already in there.  Currently, that shouldn't cause any issues, but some future readers of this issue may get confused.

**Comment by mercyground** [comment]
old habits die hard :) init.d for control. 

It was just a quick simple "fix this" script as my router had limited space. I have an R4S NanoPi now and a bigger SDCard so its less of an issue but along with a few others we're trying to make it easier for OpenWrt users to include AGH on their routers.

While some issues like space usage can be dealt with by using exroot and external usb drives, I was just wanting to help improve the experience. Disk space checks and warnings to the UI as feedback and an improved process for upgrades seemed to be the way forward.  The script solved a problem but it is a band-aid fix. I wanted to help you guys provide a more polished experience.

**Comment by mercyground** [comment]
As an addition for documentation I wrote up this for the OpenWrt Wiki. It was part of my how can I make things smaller investigation and might be worth adding to your wiki as reference or explanation?

https://openwrt.org/docs/guide-user/services/dns/adguard-home#data_files

(copied here for quick reading)
```
Data Files:

The AdGuardHome/data folder contains the following.

root@OpenWrt:/opt/AdGuardHome/data# ll -h
drwxr-xr-x    3 root     root         512 Oct 29 09:42 ./
drwxrwxrwx    4 root     root         736 Oct 30 09:06 ../
drwxr-xr-x    2 root     root         800 Nov  2 09:52 filters/
-rw-r--r--    1 root     root       45.4M Nov  2 20:42 querylog.json
-rw-r--r--    1 root     root        8.9M Oct 29 09:00 querylog.json.1
-rw-r--r--    1 root     root       32.0K Oct 30 05:28 sessions.db
-rw-r--r--    1 root     root        4.0M Nov  2 21:00 stats.db
querylog files : These are your DNS queries. Can be removed.

sessions.db : active logins to AGH currently. This can be deleted but you will need to relog back in.

stats.db : Your statistics database. can purge but you will lose your statistics data.

The filters folder contains all your filter downloads. Purge if it is full but it will re-download your filters. 
If your filters are too large for your diskspace you will have to disable large filters and restrict their usage.

The AdGuardHome/agh-backup folder contains the previous version of AGH. 
This also can be removed if space is at a premium.
```

**Comment by ainar-g** [comment]
@mercyground, please file a separate issue about that.  I wanted a single place that explains the AdGuard Home file system for a long time, so why not now, heh.

**Comment by ainar-g** [comment]
We have now added a [detailed guide][1] on manual updates to the FAQ.  The old location on the [“Getting Started” page][2] now has a link to it as well.

I'll leave this issue open until we find all links to the old location and rewrite them to point to the new one.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update
[2]: https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#manual-update

**Comment by mercyground** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update

>Download the new AdGuard Home package from the [releases page][releases]. If you want to perform this step from the command line:

I assume there should be some auto magic replace going on there? the magic smoke is out of the box.

**Comment by ainar-g** [comment]
@mercyground, the magic is now fixed, thanks for reporting!
