### ISSUE TITLE
Make the announcement URL for updates more useful

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4209]
For beta and final releases, link directly to the release page.

For the `edge` releases to the Wiki / README section where we list the links to the current releases.

In any case, I think we should also add a link to the Wiki section that we're going to create in #4208 as well.

**Comment by mercyground** [comment]
a link to https://github.com/AdguardTeam/AdGuardHome/commits/master for edge in the documentation would be good. 

Mostly for users who are unfamiliar with github. It only give you that link from under AGH when there is an update and people might not bookmark it. Documenting it so people can check would improve things.

**Comment by jumpsmm7** [comment]
how about a way to discern the release of the beta or edge build, for packagers that would like to be able to notify users of a new edge or beta release. Currently I am able to parse githubs release section for the latest stable release.

**Comment by ainar-g** [comment]
@jumpsmm7, I'm not quite sure what you mean.  The [releases page][1] contains beta versions as well.

[1]: https://github.com/AdguardTeam/AdGuardHome/releases
