### ISSUE TITLE
Add logging to /var/log/AdGuardHome.err on FreeBSD and OpenBSD

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4213]
Just like on macOS and Linux, let's write stderr and stdout to `/var/log/AdGuardHome.err` and `AdGuardHome.out` correspondingly.

**Comment by ainar-g** [comment]
@cookiemonsteruk, we'll bump the priority, thanks.  You can already make it write logs by filling in the `log_file` parameter in `AdGuardHome.yaml`, but the default behaviour obviously has to be changed.

**Comment by cookiemonsteruk** [comment]
And are there logging level directives available like INFO, ERROR, DEBUG, etc?

**Comment by ainar-g** [comment]
@cookiemonsteruk, the default level is `info` and `debug` is enabled through the `verbose` parameter.  Please see our [documentation][1].  Also, it's better to keep the Q&A in the [Discussions][2].  Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
[2]: https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a

**Comment by cookiemonsteruk** [comment]
Understood, thank you.
