### ISSUE TITLE
ADH failed to handle a rule collection containing 500w rules

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#4214]
上面如提
文件https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adguardhome.txt
![-3adde5739f640780](https://user-images.githubusercontent.com/28734349/151277003-00773832-1179-4eba-b3d7-2397f0437878.jpg)

**Comment by cxw620** [comment]
我也使用了这个规则, 但没遇到这个问题. 你是用docker部署的还是怎么样, 说清楚点才便于分析问题所在.
I also use this ad-filter rule, however i don't meet with such issue. Please describe your configuration in details so that we can help you solve such issue.
我觉得是内存不足了导致程序崩溃, 这个规则太大了.
I think it's because your server ran out of memory which cause ADH's crash, for this rule collection contains too many rules.

**Comment by Potterli20** [comment]
> 我也使用了这个规则, 但没遇到这个问题. 你是用docker部署的还是怎么样, 说清楚点你的ADH的配置才便于分析问题所在. 提供一下ADH的运行日志. I also use this ad-filter rule, however i don't meet with such issue. Please describe your configuration in details so that we can help you solve such issue. By the way please share us your ADH's log. 我觉得可能是内存不足了导致程序崩溃, 这个规则太大了. 尝试一下重启ADH看看问题是否仍然存在. I think it's because your server ran out of memory which caused ADH's crash, for this rule collection contains too many rules. You can try to restart ADH.

我昨晚更新了规则，之前是540w的规则，大于150m的规则。机器会无响音。我临时更改规则，变为220w的规则

**Comment by cxw620** [comment]
> > 我也使用了这个规则, 但没遇到这个问题. 你是用docker部署的还是怎么样, 说清楚点你的ADH的配置才便于分析问题所在. 提供一下ADH的运行日志. I also use this ad-filter rule, however i don't meet with such issue. Please describe your configuration in details so that we can help you solve such issue. By the way please share us your ADH's log. 我觉得可能是内存不足了导致程序崩溃, 这个规则太大了. 尝试一下重启ADH看看问题是否仍然存在. I think it's because your server ran out of memory which caused ADH's crash, for this rule collection contains too many rules. You can try to restart ADH.
> 
> 我昨晚更新了规则，之前是540w的规则，大于150m的规则。机器会无响音。我临时更改规则，变为220w的规则

突然发现你是这个规则的维护者😀
现在这个规则是50多MB, 应该就是220w左右的规则了. 你试一下把规则简化合并一下?

**Comment by Potterli20** [comment]
> > > 我也使用了这个规则, 但没遇到这个问题. 你是用docker部署的还是怎么样, 说清楚点你的ADH的配置才便于分析问题所在. 提供一下ADH的运行日志. I also use this ad-filter rule, however i don't meet with such issue. Please describe your configuration in details so that we can help you solve such issue. By the way please share us your ADH's log. 我觉得可能是内存不足了导致程序崩溃, 这个规则太大了. 尝试一下重启ADH看看问题是否仍然存在. I think it's because your server ran out of memory which caused ADH's crash, for this rule collection contains too many rules. You can try to restart ADH.
> > 
> > 
> > 我昨晚更新了规则，之前是540w的规则，大于150m的规则。机器会无响音。我临时更改规则，变为220w的规则
> 
> 突然发现你是这个规则的维护者😀 现在这个规则是50多MB, 应该就是220w左右的规则了. 你试一下把规则简化合并一下? 很好用的规则,不过误拦截有点多

误拦这个是要多反馈哈哈哈哈
规则基本是来自全球

**Comment by cxw620** [comment]
> > > > 我也使用了这个规则, 但没遇到这个问题. 你是用docker部署的还是怎么样, 说清楚点你的ADH的配置才便于分析问题所在. 提供一下ADH的运行日志. I also use this ad-filter rule, however i don't meet with such issue. Please describe your configuration in details so that we can help you solve such issue. By the way please share us your ADH's log. 我觉得可能是内存不足了导致程序崩溃, 这个规则太大了. 尝试一下重启ADH看看问题是否仍然存在. I think it's because your server ran out of memory which caused ADH's crash, for this rule collection contains too many rules. You can try to restart ADH.
> > > 
> > > 
> > > 我昨晚更新了规则，之前是540w的规则，大于150m的规则。机器会无响音。我临时更改规则，变为220w的规则
> > 
> > 
> > 突然发现你是这个规则的维护者😀 现在这个规则是50多MB, 应该就是220w左右的规则了. 你试一下把规则简化合并一下? 很好用的规则,不过误拦截有点多
> 
> 误拦这个是要多反馈哈哈哈哈 规则基本是来自全球

我等一下翻看记录.
另外你把这个issue标题改英文吧, ADH failed to handle a rule collection containing 500w rules.
然后把原来那个500w的放出来

**Comment by Potterli20** [comment]
https://t.me/AdGuard_chinese/32306

**Comment by Potterli20** [comment]
https://t.me/AdGuard_chinese/32313

**Comment by Karmylr** [comment]
no need to load this much rules.

**Comment by Potterli20** [comment]
> no need to load this much rules.

我知道是，无需加载这么，但是我的规则就是这样
也是顺带测试

**Comment by Karmylr** [comment]
> > no need to load this much rules.
> 
> 我知道是，无需加载这么，但是我的规则就是这样 也是顺带测试

做了去除重复规则了吗

**Comment by Potterli20** [comment]
> > > no need to load this much rules.
> > 
> > 
> > 我知道是，无需加载这么，但是我的规则就是这样 也是顺带测试
> 
> 做了去除重复规则了吗

做了

**Comment by ameshkov** [comment]
我试试了这个列表，没有什么问题。反正，你能用 https://github.com/AdguardTeam/HostlistCompiler 要压缩它。

**Comment by Potterli20** [comment]
> 我试试了这个列表，没有什么问题。反正，你能用 https://github.com/AdguardTeam/HostlistCompiler 压缩它。

https://t.me/AdGuard_chinese/32313
https://t.me/AdGuard_chinese/32306
这两个才是540w的规则
https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adguardhome.txt
这个我已经更改为220w的规则

**Comment by Potterli20** [comment]
> 我试试了这个列表，没有什么问题。反正，你能用 https://github.com/AdguardTeam/HostlistCompiler 压缩它。

在本地处理540w的规则压缩，他处理不了

**Comment by Potterli20** [comment]
> 我试试了这个列表，没有什么问题。反正，你能用 https://github.com/AdguardTeam/HostlistCompiler 压缩它。

这个是压缩，变成一级域名，可那些二级之类域名就无法屏蔽了

**Comment by ameshkov** [comment]
我看了，这个列表自动优化很难。你还能收动作。

来我举个例子吧，一个规则 `||binance.com^` 能代替 30000+ 你列表的规则。

**Comment by Potterli20** [comment]
> 我看了，这个列表自动优化很难。你还能手动作。
> 
> 来我举个例子吧，一个规则 `||binance.com^` 能代替 30000+ 你列表的规则。

哈哈哈哈，这个我是知道的。但是同时使用500w的规则。好像adgh的程序也会有问题的。
这个500w的规则，用Improt-External-Sources/hosts-sources 的sourecs.list的全部列表，加上其他同时处理的

**Comment by ameshkov** [comment]
> 但是同时使用500w的规则。好像adgh的程序也会有问题的。

AGH 没有任何限制，但列表越大，AGH用的内存越多。

**Comment by Potterli20** [comment]
> > 但是同时使用500w的规则。好像adgh的程序也会有问题的。
> 
> AGH 没有任何限制，但列表越大，AGH用的内存越多。

🌝🌝这个规则让很多机器，无法开启dns。是卡了几分钟左右

**Comment by ameshkov** [comment]
我说的是这部看起来AGH的bug，只是AGH的机器强大为这个列表不够。

**Comment by DandelionSprout** [comment]
What does "500w" refer to? 500 wide? 500 ware? 500 Wi-Fi?

**Comment by Potterli20** [comment]
> What does "500w" refer to? 500 wide? 500 ware? 500 Wi-Fi?

It's the 5 million rule

**Comment by cxw620** [comment]
> What does "500w" refer to? 500 wide? 500 ware? 500 Wi-Fi?

w means _wan_ in Chinese, which equals to 10,000. 500w means 500 * 10,000, **5,000,000**

**Comment by cxw620** [comment]
> 

国内域名直接看备案, 如果是专门做广告/收集隐私的直接一把梭全干掉, 费点力还可以查查天眼查把关联的一把梭全干掉.
国外的就麻烦.
