### ISSUE TITLE
v107 over haproxy

### ISSUE THREAD

**Issue by apnagaev** [AdguardTeam/AdGuardHome#4215]
Добрый день!
Я использую следующую схему публикации adguard:
WAF->Haproxy->adguard(docker)
В версии 106 IP клиента (doh) отображался верно с использованием хедера X-Forwarded-Proto и опции option forwardfor, но в версии 107 почему-то IP клиента приходит неверный (X-Forwarded-Proto судя по всему игнорируется), в интерфейсе в IP клиента отображается IP haproxy. Можно это как-то поправить? Конфиг haproxy:
```
frontend http_frontend
  mode http
  bind :80
  bind :443 ssl crt /docker/ssl/work alpn h2,http/1.1
  option http-server-close
  option forwardfor
  option forwardfor except 127.0.0.0/8
  http-request add-header X-CLIENT-IP %[src]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }

  acl edot hdr_dom(host) -i dot.mydomain.ru
  http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
  http-response set-header X-Content-Type-Options nosniff
  http-response set-header Permissions-Policy "geolocation=(), camera=()"
  http-response set-header Expect-CT "max-age=86400, enforce"
  http-response set-header X-Frame-Options SAMEORIGIN
  http-response set-header X-XSS-Protection "0"
  http-request redirect scheme https code 301 if !{ ssl_fc }

  use_backend edot if edot

backend edot
  mode http
# balance roundrobin
  option httpclose
  option forwardfor if-none
  option redispatch
  option http-server-close
  cookie SERVERID insert indirect nocache
  server edot1 adguard_ip1:8445 ssl verify none check cookie edot1
  server edot2 adguard_ip2:8445 ssl verify none check cookie edot2 backup
```

Может я что-то делаю не так?
Заранее спасибо!

**Comment by EugeneOne1** [comment]
@apnagaev, здравствуйте.  Обратите внимание на #2799 – в нем мы добавили поле `trusted_proxies` в конфигурационный файл AGH.  По умолчанию "доверенными" считаются лишь прокси, хостом которых выступает та же самая машина.  Полагаю, в вашем случае необходимо добавить адрес(а) HAProxy в это поле.

Обратите также внимание, что поддерживаемые заголовки, содержащие настоящие IP адреса клиентов, следующие:

1. `CF-Connecting-IP`
2. `True-Client-IP`
3. `X-Real-IP`
4. `X-Forwarded-For`

Сработало ли это в вашем случае?  Спасибо заранее.

**Comment by apnagaev** [comment]
Спасибо! Действительно, если прописать trusted_proxies работает. На всякий случай конфиг haproxy:

```
frontend http_frontend
  mode http
  bind :80
  bind :443 ssl crt /docker/ssl/work alpn h2,http/1.1
  option http-server-close
  option forwardfor
  option forwardfor except 127.0.0.0/8
  http-request add-header X-CLIENT-IP %[src]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  capture request header X-Forwarded-For len 15

  acl adguard hdr_dom(host) -i dot.mydomain.ru
  acl edot hdr_dom(host) -i edot.mydomain.ru

  acl localnet src -m ip -f /docker/haproxy/local.txt
  acl localnet hdr_ip(X-Forwarded-For,1) -f /docker/haproxy/local.txt

  use_backend adguard if adguard localnet
  use_backend edot if adguard
```
