### ISSUE TITLE
Double entry for localhost in /etc/hosts leads to 100% CPU usage

### ISSUE THREAD

**Issue by l-x** [AdguardTeam/AdGuardHome#4216]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.3
* **How did you install AdGuard Home:**
  *  GitHub releases
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * amd64
* **Operating system and version:**
  * Native (not Docker) Linux  4.14.167-0-vanilla  Alpine SMP Thu Jan 23 10:14:19 UTC 2020 x86_64 Linux
* **`/etc/hosts`:**
```
127.0.0.1	localhost.localdomain localhost
::1		localhost localhost.localdomain
```
 
### Expected Behavior
`dig localhost` executed on the AGH host returns without an error

### Actual Behavior
`dig localhost` executed on the AGH host instantly leads to 100% cpu usage and the verbose log spammed with several hundred `[debug] hosts container: handling the request` entries per second until it crashes silently a few minutes later.

### Additional Information
Removing one of the two entries for `localhost` in `/etc/hosts` fixes the issue.

I can reproduce the issue only for `localhost` entries, not for other domains.

**Comment by l-x** [comment]
Addendum:

When i change my `/etc/hosts` to

```
127.0.0.1	localhost.localdomain localhost
::1		localhost.localdomain localhost
```

everything is fine.

**Comment by EugeneOne1** [comment]
@l-x, hello and thanks for an exhaustive report!  We've just pushed the latest `edge` build that should fix the problem.  Could you please try it and confirm that our solution fixes the issue?

**Comment by l-x** [comment]
@EugeneOne1 I'd like to try your fix, but I have no clue where to find the latest `edge` build... ^^

**Comment by EugeneOne1** [comment]
@l-x, I suppose the issue may be closed.  Feel free to reopen it if the problem reoccurs.
