### ISSUE TITLE
Dashboard Statistics

### ISSUE THREAD

**Issue by amd93** [AdguardTeam/AdGuardHome#422]
### Steps to reproduce

1. For Example Blocked by Filters about 8200 
2. Wait some time.. 
3. Refresh statistics at dashboard - and Blocked by Filters shows less than 8000 

### Expected behavior
Show normally numbers greater than 8000

### Actual behavior
I think that the problem with the show more than 8000

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.9-hotfix1
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| VPS Server
| Operating system and version:| Debian Server 9.5

**Comment by ameshkov** [comment]
It shows stats for the last 24 hours only, not for all time.

Could you please compare the total value with what's shown on the "blocked" chart?

**Comment by amd93** [comment]
I have 16522 DNS Queries and 7990 Blocked by Filters....
