### ISSUE TITLE
Replace BUILD_TIME with SOURCE_DATE_EPOCH for reproduceable builds

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4221]
Currently, we compile in the date of the *build.*  And we compile it in as plain text.

[Reproducible-Builds.org recommends][1] using the commit date instead, given through the environment variable `SOURCE_DATE_EPOCH` and as a Unix timestamp.  This should improve the life of people building their own AGH, such as package maintainers, since this will only require a shallow clone of the repo and the “correct” Go version to build a bit-by-bit identical copy of a binary.

The documentation in `scripts/README.md` obviously should be updates as well.

@jamesmacwhite, @yurivict, @simonbcn, if I recall correctly, you maintain AdGuard Home packages?  Do you have any objections to this?

[1]: https://reproducible-builds.org/docs/source-date-epoch/

**Comment by jamesmacwhite** [comment]
@ainar-g Thanks for this. I've contributed to the [AdGuardHome package in OpenWrt](https://github.com/openwrt/packages/tree/master/net/adguardhome), but I am not the primary maintainer of it, so I'm probably not the best person to speak for the OpenWrt package as a whole.

I'd imagine this [relates to the Makefile](https://github.com/openwrt/packages/blob/master/net/adguardhome/Makefile#L28-L34) and how they are being used when compiling in OpenWrt.

**Comment by ainar-g** [comment]
If we're doing this, we'll probably need to change the `BUILD_DATE` argument inside the `Dockerfile` as well.
