### ISSUE TITLE
Cant open Paypal

### ISSUE THREAD

**Issue by lordvalium** [AdguardTeam/AdGuardHome#4225]
Hi, 
i cant open paypal when ADG running. 

Can reproduce that https://paypal.com/ does **not** open on 
- iOS iPhone
- Windows 11 with Chrome Browser
- 
system: 
- rasperry Pi
- Version: v0.107.3

what i have added already to the custom filtering rules

@@||paypal.com^$document,jsinject,extension,network,important
@@||paypal.com/authflow/twofactor/?returnUri=*^$document,jsinject,extension,network,important
@@||paypalobjects.com^$document,jsinject,extension,network,important

**Comment by EugeneOne1** [comment]
@lordvalium, hello.  AdGuard Home is a network-level blocker so the `document`,`jsinject`,`extension`, and `network` modifiers are probably bothering AGH to interpret rules properly.  Try to left those with only the `important` modifier.  If that helped?

**Comment by lordvalium** [comment]
Thanks @EugeneOne1 , i have remove removed and its now as the following: 

@@||paypal.com^$important
@@||paypal.com/authflow/twofactor/?returnUri=*^$important
@@||paypalobjects.com^$important

But still not loading

**Comment by EugeneOne1** [comment]
@lordvalium, could you please perform an `nslookup` request for `paypal.com`:

```none
nslookup paypal.com <your-AGH-address>
```
The query log should show afterwards if the domain was blocked or not.  Thanks.

**Comment by lordvalium** [comment]
nslookup paypal.com 192.168.188.45

Server:  UnKnown
Address:  192.168.188.45

Non-authoritative answer:
Name:    paypal.com
Addresses:  64.4.250.37
          64.4.250.36

**Comment by stevenzhu25** [comment]
> Non-authoritative answer: Name: paypal.com Addresses: 64.4.250.37 64.4.250.36

This means your AdGuard Home instance wasn't blocking paypal.com domain.

How about 
`nslookup paypal.com`
Does this query also go to the same address but didn't receive the same set of IP in response?

**Comment by lordvalium** [comment]
yes there is the absolutely same answer.

BR and thanks

**Comment by stevenzhu25** [comment]
> yes there is the absolutely same answer.

Are you still not able to open PayPal.com?
Does the error message said something like `Server DNS address could not be found` or `err not resolved`? Based on your response it doesn't look like an issue with DNS resolution.

**Comment by lordvalium** [comment]
Thanks for your fast reply. 

Its
`ERR_CONNECTION_TIMED_OUT`

The situation is really weird, because everything else with around 6 WiFi clients is running at home.

**Comment by stevenzhu25** [comment]
> `ERR_CONNECTION_TIMED_OUT`

That's something with your local network or ISP... You might want to check your local equipment (AP/Modem/Switch) or with your ISP and see if there's any issue. 

Try https://www.drivereasy.com/knowledge/err-connection-timed-out/
Only try method 1,3,4,5...

Also, try to open with another browser on those devices, that'll help you isolate whether it's issue with your IP or network equipment, or it's with your individual devices.

**Comment by lordvalium** [comment]
I have tried that, and its just paypal. And it worked before we had ADGH. 
And we tried also with other clients in the NAT. Also not workign

**Comment by EugeneOne1** [comment]
@lordvalium, to troubleshoot the issue we'll need to take a look at your [verbose log](github.com/adguardTeam/adGuardHome/wiki/FAQ#verboselog).  Could you please collect it with the issue reproduced and send here or to the devteam@adguard.com?

**Comment by lordvalium** [comment]
Hey i could fix it. It was because the IP was blacklisted. After resetting the whole fiberchannel connector from the streeet i got a new ip. then it worked again. 
paypal is a bit to strange
