### ISSUE TITLE
Using the schedule (time) in user rules.

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#4228]
Version 107.3
Why don't you add the ability to block on a schedule (time) . In user rules, it is very often necessary to block a resource for a client in a certain period of time. 
![1](https://user-images.githubusercontent.com/74646605/151655753-f7e4bb38-0f04-4601-81e1-2b402fff625d.jpg)

**Comment by EugeneOne1** [comment]
@fizsef, hello.  We'll merge this into similar #951.
