### ISSUE TITLE
Act as DHCP server

### ISSUE THREAD

**Issue by mustakimali** [AdguardTeam/AdGuardHome#423]
Not all home router have option to change the default DNS server. Therefore each device needs to have the dns server set manually to the device where AdGuardHome is running. It's a difficult task (think about your small IOT devices).

So If AdGuardHome could act as a DHCP server and define itself as the DNS server when leasing IPs to new devices - this would be a life-saver.

This is the single reason I just moved back to Pi-hole despite liking the sleek interface, the convenience of running the DNS server and web interface from just one binary.

**Comment by ameshkov** [comment]
Makes sense indeed, thank you!

**Comment by frenck** [comment]
This feature would definitely make it a proper Pi-hole alternative.

**Comment by ameshkov** [comment]
Resolved in the master branch.

It's experimental now so we expect some DHCP-related bugs
