### ISSUE TITLE
Custom port for UI 

### ISSUE THREAD

**Issue by Toudahl** [AdguardTeam/AdGuardHome#4232]
I would like to be able to serve the UI on a custom port.
This way I can block access to the UI, while opening doh to the world.

**Comment by Takaki-Sakura** [comment]
agreed

**Comment by EugeneOne1** [comment]
@Toudahl, hello.  We're already woking on this in the process of refactoring AdGuard Home.  See issue #2075, and there are some others as well.  We'll merge this into the one.

**Comment by Toudahl** [comment]
> @Toudahl, hello. We're already woking on this in the process of refactoring AdGuard Home. See issue #2075, and there are some others as well. We'll merge this into the one.

That's great.

Whats the issue number? I do not see it listed in 2075.
Which milestone/version do you expect it to be part of?

**Comment by EugeneOne1** [comment]
@Toudahl, indeed, the the issue wasn't listed.  We've already updated it.  The expected milestone is v0.108.0.  Thanks.

**Comment by Toudahl** [comment]
#741 for any one wondering
