### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sysadmin-info** [AdguardTeam/AdGuardHome#4236]
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=JQIBAAABAAAAAAAABnN0YXRpYwdhZGd1YXJkA2NvbQAAHAAB": all dialers failed: 2 errors: "dial tcp [2620:fe::10]:443: connect: network is unreachable", "dial tcp [2620:fe::fe:10]:443: connect: network is unreachable" | 502

AdGuard installed on a raspberry Pi. It was working normally until February 1st 2022. After the reboot of the raspberry pi 4b. Raspberry Pi is connected to the main router wit openwrt. Everything is set as it should be. No changes. Have no idea what is wrong.

**Comment by ainar-g** [comment]
This looks like a network error.  We've had a similar issue recently, #4205, and there it most probably was about a VPN that the user was using alongside AdGuard Home.  Please check that IPv6 connectivity is good.  You can also try to use an upstream server other than Quad9.

**Comment by sysadmin-info** [comment]
Thanks. Problem solved. You are right.
