### ISSUE TITLE
Use the response RR type when filtering

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4238]
(Split from #4230.)

Currently, when we filter a DNS response, we use the request resource record type in the filtering request.  That creates issues with e.g. `CNAME` responses to `A`/`AAAA` queries.  @ameshkov proposes using the type of the response RRs rather than the request ones.

I feel like there could be issues with misbehaving upstreams though.  Like an upstream that responds with `AAAA` records on an `A` request, for example.  We'll see how much of an issue that would be.

**Comment by ameshkov** [comment]
@ainar-g this is actually a simple improvement, but worthy of implementing in a patch and not waiting for v0.108.0 release (since we need the same change for AdGuard DNS).

**Comment by ainar-g** [comment]
@ameshkov, I thought about that, but I feel like this is a change in behaviour that isn't necessarily a bug fix, and I prefer to leave such changes to “major” (minor in SV) versions.  In any case, nothing prevents us completing it on the main branch and then cherry-picking it into the release branch if there is an actual need for it.

I'll take AGD into account.
