### ISSUE TITLE
Allow a "source address" modifier in custom filtering rules, in addition to the existing "client" modifier

### ISSUE THREAD

**Issue by xavierf1970** [AdguardTeam/AdGuardHome#4240]
### Prerequisites
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Problem Description
I implemented a kind of split horizon mechanism based on custom filtering rules. These rules use the "client" modifier with a named client to avoid verbose rules. I created an "Internal" client with all the internal subnets. This way the split horizon mechanism is working well.
But this has a side effect on the display of individual clients' name, especially in the "query log" or "top clients" views. The "Internal" client name takes precedence over the individual names. Thus all the internally connected clients are identified as "Internal".

### Proposed Solution
Add a new rule modifier, "source address", identifying the source addresses by their name, or their IP address or CIDR. Add also a new part in the GUI to manage named source addresses, like named clients.

### Alternatives Considered
Modify the display of individual clients' name wherever they are displayed, to "prioritize" individual clients over subnet clients.

### Additional Information
n/a

**Comment by xavierf1970** [comment]
One clarification, the "Internal" name takes at least precedence over runtime clients' names, either rDNS or /etc/hosts.

**Comment by ainar-g** [comment]
@xavierf1970, hello and thank you for the request!

 >  Add a new rule modifier, "source address", identifying the source addresses by their name, or their IP address or CIDR. Add also a new part in the GUI to manage named source addresses, like named clients.

You can already do that:

```none
||example.com^$client=192.168.0.0/16
```

It's documented on [our Wiki][1].

 >  Modify the display of individual clients' name wherever they are displayed, to "prioritize" individual clients over subnet clients.

This feature is actually already planned for v0.108.0, see #4064.  We plan to make more information about clients' data available in the statistics and the query logs.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client

**Comment by xavierf1970** [comment]
Thanks @ainar-g for your reply

> You can already do that:
> 
> ```
> ||example.com^$client=192.168.0.0/16
> ```
I knew that I could do that. But I want to avoid verbosity and duplication. I have >10 rewrite rules and ~6 internal subnets for every rule.

**Comment by ainar-g** [comment]
I see.  In that case, I'm more inclined to merge this into issue 4064 and improve the statistics storage and its UI, if you don't mind.  A separate type of permanent client seems like a bit of an overkill.
