### ISSUE TITLE
Safesearch blocking Youtube completely

### ISSUE THREAD

**Issue by msboparai** [AdguardTeam/AdGuardHome#4243]
- [ v0.107.3] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * <v0.107.3>
* **How did you install AdGuard Home:**
  * <Openwrt router(Pi4)>
* **How did you setup DNS configuration:**
  * <Router) -->
* **If it's a router or IoT, please write device model:**
  * <Raspberry Pi 4 Model B>
* **CPU architecture:**
  * <ARM>
* **Operating system and version:**
  * <Openwrt>

### Expected Behavior
On selecting safesearch option youtube should open in restricted mode

### Actual Behavior
On activating safesearch device could not reach youtube at all(not even restricted mode), although in query log it shows safesearch. On disabling safesearch youtube starts working.

### Additional Information
On my old Pi4 running Adguardhome version (v0.106.3) everything works fine and on activating safesearch youtube opens in restricted mode.

**Comment by dioey** [comment]
are you enable the Optimistic caching on DNS settings? try disable if you do, i have problem with that, some site wont work after enable Optimistic caching

**Comment by msboparai** [comment]
Optimistic caching is already disabled.

**Comment by dioey** [comment]
Hem thats weird can you ping restrictmoderate.youtube.com  ,that for youtube restrict mode?

**Comment by EugeneOne1** [comment]
@msboparai, also, if it doesn't ping, could you please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  You may either send it here or to devteam@adguard.com.

**Comment by msboparai** [comment]
ping for restrictmoderate.youtube.com works

**Comment by msboparai** [comment]
<img width="1152" alt="youtube" src="https://user-images.githubusercontent.com/38821535/152623054-b32fe8a9-987d-4c56-9622-95a0f5399e27.png">
<img width="1393" alt="ping" src="https://user-images.githubusercontent.com/38821535/152623063-abd04c3a-6130-46d7-9b8f-dc3b890fc4c4.png">
Youtube is enabled under adguardhome and safesearch is also enabled.

**Comment by agneevX** [comment]
What does the browser console say?

**Comment by Birbber** [comment]
@msboparai Sorry for the long silence! Is this issue still relevant in the latest version?

**Comment by ainar-g** [comment]
No response for over a year.  Closing.
