### ISSUE TITLE
Clarification of Client Name, ID / Host Name, Device Name 

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#4244]
### Problem Description
In the **DNS settings > Allowed clients** section the **client ID** is rather ambiguous. Is it just the device's **Host Name** or **Device Name**? I've tried the host names for my three Windows 10 PCs on the same network but when I do (one per line) it just blocks them.

e.g.

```
SLK
MSD
TYE
```

Maybe an issue with uppercase?

### Proposed Solution
Please clarify the term in the UI.

### Alternatives Considered
Using clunky IP addresses instead.

### Additional Information
none

**Comment by EugeneOne1** [comment]
@hl2guide, hello.  The term "client ID" is described on the [wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#idclient).  It's ain't a hostname or device name, it's an expicitly configured identifier for the client on the **Client settings** section.

**Comment by ainar-g** [comment]
@hl2guide, we've improved both the [Wiki][1] as well as the UI messages in version v0.108.0-a.67+f53f48cc on the edge channel.  Can you please check, if the new texts make things clearer?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid
