### ISSUE TITLE
Statistics about the resolvers used

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#4247]
### Problem Description
Currently there are no statistics about how many times each resolver is query and that would be interesting in load balancing mode when you have several resolver to now which one are faster for you.
![imagen](https://user-images.githubusercontent.com/17175395/152603838-1fbea68a-f84c-443c-b2ca-84c42ed2df81.png)

### Proposed Solution
Add statistics panel with the total queries per resolver and the average time of processing

### Alternatives Considered
none

### Additional Information
![imagen](https://user-images.githubusercontent.com/17175395/152604432-b7550ec1-36b8-47a4-9b94-5cd929570fd3.png)

**Comment by agneevX** [comment]
@lordraiden where's that screenshot from?

**Comment by lordraiden** [comment]
> @lordraiden where's that screenshot from?

It was a picture of Google search images. I search DNS dashboard or something like that but it can't find it now

**Comment by peepsnet** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1453
