### ISSUE TITLE
statistic all 0 and error when open dashboard in windows

### ISSUE THREAD

**Issue by shukryshuk** [AdguardTeam/AdGuardHome#4249]
Version: v0.107.3

only happened to windows 11 browser tested in mozilla and chrome,,, not happened in my android phone this error

![image](https://user-images.githubusercontent.com/55014736/152638081-ee446def-1fe9-4e63-9e17-26674de15c34.png)

the error:-
Error: control/clients/find?ip0=naza&ip1=shairul&ip2=aidil&ip3=norhan&ip4=linda&ip5=danis&ip6=andi&ip7=shuk&ip8=kodi&ip9=rizman&ip10=kamal&ip11=pc&ip12=mansur&ip13................

**Comment by ainar-g** [comment]
Hello.  Are there any errors in the web browser's console?

Also, do you enter an IP address to reach AdGuard Home's UI, or some kind of hostname, like `dns.myhost.local`?

Thanks.

**Comment by shukryshuk** [comment]
> Hello. Are there any errors in the web browser's console?
> 
![image](https://user-images.githubusercontent.com/55014736/152805928-6b1c0877-ae7c-446c-a3c9-51e9201154cd.png)

> Also, do you enter an IP address to reach AdGuard Home's UI, or some kind of hostname, like `dns.myhost.local`?
> hosted in public server linode. enter my domain name https:subdomain.mydomain.com

**Comment by ainar-g** [comment]
Could you please show the error that is right above the `<path>` ones?  The one with `net:ERR_CONNECTION_RESET`?

Is the certificate for your `subdomain.mydomain.com` valid on your Windows system?

Also, does it work if you use the IP address instead of the domain name?

Thanks.

**Comment by ainar-g** [comment]
That sheds some light on that, thanks.  It's really weird.  Do other pages work?  For example, the “Settings → General settings” page?

**Comment by shukryshuk** [comment]
> That sheds some light on that, thanks. It's really weird. Do other pages work? For example, the “Settings → General settings” page?

yes, all pages work, except dashboard and clients

**Comment by EugeneOne1** [comment]
@shukryshuk, sorry for the late response.  How have you configured the HTTP proxy server?  In particular, what does it pass to the `HOST` header?

Could you also please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) with the error reproduced?  You may post it here or send it to devteam@adguard.com.

**Comment by cadusilva** [comment]
I had a similar issue (#4358) and after I blocked a bunch of CIDRs, never happened again. Every page worked, except home and clients. There was errors in common with this issue here but I didn't try to load the page via the mobile browser to check as you did. I host AdGuardHome at home with a public IP and hostname.
