### ISSUE TITLE
Web setup

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#425]
We've learned a lot about most common issues users face while trying to install and use AdGuard Home. Addressing all of them is the most important thing we should do now.

Here are the improvements I suggest:

1. Introduce a simple installation script for Linux / macOS that will register AdGuard Home as a service and perform necessary pre-configuration.
2. Introduce an official docker image and support `docker pull`
3. Add a "setup" page to the web admin interface that will help users configure their devices.

## Checklist

* [ ] Installation script (linux only): https://github.com/AdguardTeam/AdGuardHome/issues/570
* [x] DHCP server: https://github.com/AdguardTeam/AdGuardHome/issues/423
* [x] Web setup
* [x] Docker image on `hub.docker.com`: https://github.com/AdguardTeam/AdGuardHome/issues/562

## Web setup

If initial setup is necessary, serve `install.html` page instead of `index.html`.

### Setup steps

1. Greetings
    Welcome user and explain briefly that initial setup is required.
    https://uploads.adguard.com/up04_7dd91_Diagrams_-_AGHome_Wizard__Moqups.png

2. Confirm settings
    https://uploads.adguard.com/up04_58lg8_Diagrams_-_AGHome_Wizard__Moqups.png

    **Admin Web Interface**

    Listen address: X.X.X.X
    Listen port: 80

    **DNS server**

    Listen address: X.X.X.X
    Listen port: 53

    Buttons:
    Back, Next

3. Authentication
    https://uploads.adguard.com/up04_1zu4h_Diagrams_-_AGHome_Wizard__Moqups.png

    Configure admin username and password.

    * Username
    * Password
    * Confirm password

    Buttons:
    Back, Next

4. Configure devices
    https://uploads.adguard.com/up04_ic3k6_Diagrams_-_AGHome_Wizard__Moqups.png

    You need to configure your devices to use AdGuard Home as a DNS server.

    **Available options**

    * Configure your Router (click expands an instruction)
    * Configure AdGuard Home as a DHCP server (click expands an instruction and additional settings)
    * Configure your devices manually (click expands an instruction)

    Buttons:
    Back, Next

5. Thank you for using AdGuard Home!
    https://uploads.adguard.com/up04_hhs9e_Diagrams_-_AGHome_Wizard__Moqups.png

    On the devices configured to use AdGuard Home, visit `http://adguard.home` to access the admin interface.

    Buttons:
    Finish -> leads to `http://adguard.home`

**Comment by Bluscream** [comment]
Maybe even push it to APT repositories or create one for AG products?

PS: It would also be neat if the AG installation script would ask for webinterface bind address+port and DNS port and would check for iptables and add rules to allow it's traffic if iptables or ip6tables was found.

**Comment by ameshkov** [comment]
> Maybe even push it to APT repositories or create one for AG products?

Eventually, yes, but that's not a part of this task.

**Comment by ameshkov** [comment]
> How on earth do I update AdGuardHome if an update comes?

Which btw comes a bit later today:)

For now, you'll simply need to download the new binary and replace the old one.
In one of the future versions when we implement auto-update #448 it will be easier.

**Comment by ameshkov** [comment]
Web setup is almost done, and I decided to move the installation script requirements to another task: https://github.com/AdguardTeam/AdGuardHome/issues/570
