### ISSUE TITLE
Cached items get removed when upstream fetch is unsuccessful

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#4254]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.107.3
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * arm64
* **Operating system and version:**
  * Ubuntu 20.04.3

### Issue Details

It seems that cached records get deleted when an upstream query is unsuccessful, after the cached query is served.

<img src="https://user-images.githubusercontent.com/19761269/152690925-86df3f17-69e1-40e8-8e6f-9e8f575ae4cc.png" width="380">

I lost at internet at 5:16:29 PM, so when the query was made one second later, a cached query was served. 
At 5:36:31, when the internet was back up already, the query was fetched from upstreams, instead of from the cache.

However I'd say this requires some more testing.

### Additional Information

I remember v0.107.0 serving cached records for an infinite amount of time when upstreams were unreachable. This is why actually the network was functional even though I had misconfigured upstreams, funny story!

**Comment by EugeneOne1** [comment]
@agneevX, hello.  The responses are cached for a TTL value they had so that the upstream server won't be queried until the response expires.  If you have the "Optimistic caching" enabled, the last response should only be returned one more time.  In any case the expired cache items are removed if those couldn't be resolved again so I would say this is the intended behavior.  Did my answer clarified the logic?

**Comment by agneevX** [comment]
>  If you have the "Optimistic caching" enabled, the last response should only be returned one more time. In any case the expired cache items are removed if those couldn't be resolved

I do have Optimistic Caching enabled. I don't think this behavior is right, it should still serve expired queries rather than deleting items it could not get a reply to.

Has this behavior changed recently? While I'm using DNS-over-HTTPS resolvers now, this was not the case before.

**Comment by EugeneOne1** [comment]
@agneevX, well, you're right.  This is a bug, we'll fix it soon.

**Comment by agneevX** [comment]
Thanks @EugeneOne1 as always 👍

**Comment by gspannu** [comment]
> 
> <img alt="" width="380" src="https://user-images.githubusercontent.com/19761269/152690925-86df3f17-69e1-40e8-8e6f-9e8f575ae4cc.png">
> 
@agneevX 
### Quick question: 
**What tool/ app** are you using that shows query logs as above? Would you mind sharing this information please? 
--- 
My query log (from my Cloud hosted AdGuardHome) 

Looks like this on a mobile web page (Safari on iOS)
![IMG_2E1D111D4CB8-1](https://user-images.githubusercontent.com/137664/153025903-9324c208-f6f3-4a1e-a279-5bee58923996.jpeg)
---

and like this on my desktop macOS browser (Safari)
<img width="1017" alt="Screenshot" src="https://user-images.githubusercontent.com/137664/153026716-3c8db198-daf1-41bc-8f13-0cfb000773f2.png">

**Comment by agneevX** [comment]
This is the AdGuard Home Remote app @gspannu.

**Comment by gspannu** [comment]
> 

Is it the Rocket Science app or some other one? 
https://rocketscience-it.nl/
https://apps.apple.com/gb/app/adguard-home-remote/id1543143740
