### ISSUE TITLE
High CPU use when Adguard is running on HA/RP4

### ISSUE THREAD

**Issue by Joejoeinc** [AdguardTeam/AdGuardHome#4255]
### Issue Details

CPU on HA/RP4 when Adguard is running is averaging a constant 29%. If I disable Adguard service the HA CPU drops to normal levels (less than 5%)

* **Version of AdGuard Home server:**
 4.4.4
* **How did you install AdGuard Home:**
Installed in HA
* **How did you setup DNS configuration:**
Router configured to talk to HA/Adguard
* **If it's a router or IoT, please write device model:**
  Netgear 7000P
* **Operating system and version:**
 Home Assistant On RP4 (Home Assistant 2022.2.2)

### Expected Behavior
Previously Adguard was using less than 1% CPU

### Actual Behavior
29% CPU use on HA 

### Screenshots
<img width="305" alt="image" src="https://user-images.githubusercontent.com/45809533/152707768-adabd344-0e90-4950-86ce-5c6532c8f10c.png">

### Additional Information
I was able to reproduce the same issue on a second HA setup.

**Comment by Joejoeinc** [comment]
I was using https://dns.cloudflare.com/dns-query as the upstream DNS and as soon as I switched over to 1.1.1.1 the CPU load goes away.

**Comment by ainar-g** [comment]
Hello.

 >  v4.4.4

This looks like the version of the [Home Assistant addon][1], not of AdGuard Home itself.  The version of AdGuard Home can be seen in the right bottom corner of the UI.

 >  Note: I then restarted ADguard and put https://dns.cloudflare.com/dns-query back in the CPU load has not returned

Is the issue still relevant?  Perhaps, Home Assistant didn't reboot AGH after installing the new version of AGH?

[1]: https://github.com/hassio-addons/addon-adguard-home

**Comment by Birbber** [comment]
Closing this issue as completed. Feel free to re-open it if needed.
