### ISSUE TITLE
Doesn't block ads

### ISSUE THREAD

**Issue by Ikif** [AdguardTeam/AdGuardHome#4256]
- [ver.: 4.4.4] I am running the latest version
- [checked] I checked the documentation and found no answer
- [checked] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *ver.: 4.4.4
* **How did you install AdGuard Home:**
  * Home Assistant 
* **How did you setup DNS configuration:**
  * Asus RT-AC68
* **CPU architecture:**
  * Raspberry Pi 4 
* **Operating system and version:**
  * Rasbian

### Expected Behavior
Expect to block ads

### Actual Behavior
Doesn't block ads

### Additional Information
Just installed AdGuard Home from Home Assistant on Raspberry Pi4 (Rasbian 64).
As I started AdGuard Home it blocked 28 requests , and after that it stopped to block at all.
I see [DNS Queries] changes , but counter of block stopped on 28.

**Comment by EugeneOne1** [comment]
@Ikif, hello.  Are you sure about the version?  FYI, it's shown in the bottom right corner of the dashboard under the language selector:
![image](https://user-images.githubusercontent.com/38542664/152777943-5bac388b-8bb9-4d19-acba-968d5d98ce5c.png)

Also, could you please collect a [verbose log](https://github.com/adguardTeam/adGuardHome/wiki/FAQ#verboselog) to help us troubleshoot the issue?  You may either post it here or send to devteam@adguard.com.

**Comment by Ikif** [comment]
Version:  v0.107.3
At the morning I see the counter of [Blocked by Filters] is increased , but I don't see that it block ads at all.
I also added blocklists from "Adblock Plus" where it works properly and AdGuard Home doesn't block the same ads.

**Comment by Ikif** [comment]
![image](https://user-images.githubusercontent.com/47120186/152798473-6872c527-687b-4ca5-abda-8625a4d157c4.png)

**Comment by Ikif** [comment]
![image](https://user-images.githubusercontent.com/47120186/152799008-bdc16f58-71a3-4cbd-a998-24fc1ee52ad1.png)

**Comment by Ikif** [comment]
In  “Block domains using filters and hosts files” I added all block lists.
I also enabled "Parental Control", " Browsing security web service".
"DNS allowlists" , "DNS rewrites" and "Custom filtering rules" are empty.

**Comment by Ikif** [comment]
I tried to add Amazon and Youtube in "Blocked services".
On my laptop I still open these sites.... 
In "Query Log" :
![image](https://user-images.githubusercontent.com/47120186/152804640-7de0ff15-4b18-4659-b477-a22bbfe1877d.png)

**Comment by ainar-g** [comment]
When you're doing `nslookup`, is the IP address in the `Address:` field (the one with the red X) the address of the Raspberry Pi with AdGuard Home?

Also, how did you configure the clients?  Did you configure your DHCP server to send the IP address of AdGuard Home for both primary **and** secondary DNS?  If the clients in that Wi-Fi network don't receive AdGuard Home IP addresses **only,** DNS queries will go around it.

**Comment by Ikif** [comment]
Yes , the IP (nslookup) is of RPi with AdGuard Home.

IP of RTPi  in DNS fields of router:
![image](https://user-images.githubusercontent.com/47120186/152824695-75d5b41f-2147-4ecd-9fde-da5ba36a0c9e.png)


I didn't changed configuration of DHCP in the router only added IP of RPi to DNS field :
![image](https://user-images.githubusercontent.com/47120186/152825598-1a0e48aa-24c1-47c0-a988-66c7a746ef59.png)

**Comment by Ikif** [comment]
Amazon address I put to block service:
![image](https://user-images.githubusercontent.com/47120186/152831234-97cff3af-86ac-4fc2-a4c1-c8748a78b717.png)

My PC properties (work laptop) :
![image](https://user-images.githubusercontent.com/47120186/152831480-b8ad9d07-9548-4122-8a50-fdcd7f7bde5e.png)

**Comment by ainar-g** [comment]
Sorry, I'm out of ideas.  Perhaps, someone who had a similar setup could chime in either here, or on the Home Assistant forums.

**Comment by CipherOps** [comment]
AdGuard Home is your only upstream DNS server correct? Also, I notice you're on a Windows machine, if you have IPv6 enabled on a Windows machine it bypasses local filtering, no idea why, but it does. Also, you should go into filters and enable the OISD blocklist, it is really good and will help catch more ads.

**Comment by agneevX** [comment]
Well, if the query is hitting AdGuard and not being blocked, it could be because of incorrect settings:

Just double-checking, is this option checked, @Ikif?

![Screenshot (124)](https://user-images.githubusercontent.com/19761269/152947640-92d5edff-19c1-4092-a1cc-78198830afd8.png)

**Comment by agneevX** [comment]
As @ainar-g points out, this could be because of DNS suffix.

What does `Connection-specific DNS Suffix` in `ipconfig /all` print out?

**Comment by Ikif** [comment]
> As @ainar-g points out, this could be because of DNS suffix.
> 
> What does `Connection-specific DNS Suffix` in `ipconfig /all` print out?

 Connection-specific DNS Suffix  . : ger.corp.intel.com
