### ISSUE TITLE
Issue with syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP, syscall.SIGQUIT making invalid judgement on syscall. AdGuardHome does not properly Fork off to form its own process. 

### ISSUE THREAD

**Issue by jumpsmm7** [AdguardTeam/AdGuardHome#4257]
If I enable logging using 
`-l "/path_to_some/log_file"`
if I want to view the end log file with 
`tail -f  "/path_to_some/log_file"`
once I 
`ctrl+c` in the terminal to get out of the `log_file` 
AdGuardHome takes the signal as a interrupt and shutsdown.

Here are some places in go where things need to be investigated
https://github.com/AdguardTeam/AdGuardHome/blob/dc480ae70f978bca4d407283e316ccedd388c86a/internal/home/home.go#L106
https://github.com/AdguardTeam/AdGuardHome/commit/7ddc71006ba78dcbe7c3a6e7cdd133f2d5602943

The same thing happens if syslog is specified as the location for logs to be seen. if syslogger gets restarted, then adguardhome initiates a interrupt shutdown. 

Here are some examples

 `/usr/bin/tail -f /opt/var/log/AdGuardHome.log`
`2022/02/06 20:52:39.510662 [info] Ratelimit is enabled and set to 20 rps`
`2022/02/06 20:52:39.510676 [info] The server is configured to refuse ANY requests`
`2022/02/06 20:52:39.510693 [info] DNS cache is enabled`
`2022/02/06 20:52:39.510720 [info] MaxGoroutines is set to 300`
`2022/02/06 20:52:39.510768 [info] Creating the UDP server socket`
`2022/02/06 20:52:39.510980 [info] Listening to udp://[::]:53`
`2022/02/06 20:52:39.510997 [info] Creating a TCP server socket`
`2022/02/06 20:52:39.511099 [info] Listening to tcp://[::]:53`
`2022/02/06 20:52:39.513590 [info] Entering the tcp listener loop on [::]:53`
`2022/02/06 20:52:39.513739 [info] Entering the UDP listener loop on [::]:53`
`2022/02/06 20:53:56.344429 [info] auth: user "XXXXXXX" successfully logged in from ip XXXXXXXXXX`
`^C # **where I  used ctrl+c**`

Here is me going back into the log after the fact.

` /usr/bin/tail -f /opt/var/log/AdGuardHome.log`
`2022/02/06 21:54:40.645087 [info] Received signal "terminated"`
`2022/02/06 21:54:40.645174 [info] stopping AdGuard Home`
`2022/02/06 21:54:40.645189 [info] stopping http server.`
`2022/02/06 21:54:40.651524 [info] stopped http server`
`2022/02/06 21:54:40.651711 [info] Stopping the DNS proxy server`
`2022/02/06 21:54:40.651866 [info] Stopped the DNS proxy server`
`2022/02/06 21:54:40.663713 [info] Stopped`

**Comment by ainar-g** [comment]
I cannot reproduce this on Ubuntu.  Are you sure that there wasn't anything other than `tail -f` involved?  And how was AGH launched?

**Comment by ainar-g** [comment]
I have tried starting it as a simple binary (not a service) as well, but I cannot reproduce that.  Can you please provide both the script that you use to launch AGH?  Also, is `/usr/bin/tail` a GNU `tail` or an alias for the Busybox `tail`?

**Comment by jumpsmm7** [comment]
I have the same results calling adguardhome from binary. 
`tail: invalid option -- 'V'`
`BusyBox v1.25.1 (2022-01-01 13:43:18 EST) multi-call binary.`

`Usage: tail [OPTIONS] [FILE]...`

`Print last 10 lines of each FILE (or stdin) to stdout.`
`With more than one FILE, precede each with a filename header.`

`        -f              Print data as file grows`
`        -c [+]N[kbm]    Print last N bytes`
`        -n N[kbm]       Print last N lines`
`        -n +N[kbm]      Start on Nth line and print the rest`
`        -q              Never print headers`
`        -s SECONDS      Wait SECONDS between reads with -f`
`        -v              Always print headers`
`        -F              Same as -f, but keep retrying`

`N may be suffixed by k (x1024), b (x512), or m (x1024^2).`
That is the information I get when checking the tail version.

**Comment by jumpsmm7** [comment]
Actually I get the same output from /usr/bin/tail -f as well.

**Comment by ainar-g** [comment]
Again, please provide the actual script you're using to launch your AGH.  I am not able to reproduce that behaviour with or without `nohup`, as well as with either GNU or Busybox `tail`.

**Comment by jumpsmm7** [comment]
> Again, please provide the actual script you're using to launch your AGH. I am not able to reproduce that behaviour with or without `nohup`, as well as with either GNU or Busybox `tail`.
Okay so the script is launched 
`/opt/etc/init.d/S99AdGuardHome`  
is the name of the launch file

`#!/bin/sh`
`ENABLED="yes"`
`WORK_DIR="/opt/etc/AdGuardHome"`
`PID_FILE="/opt/var/run/AdGuardHome.pid"`
`PROCS="AdGuardHome"`
`ARGS="-s run -c "${WORK_DIR}/AdGuardHome.yaml" -w "$WORK_DIR" --pidfile "$PID_FILE" --no-check-update -l "/opt/var/log/AdGuardHome.log""`
`PREARGS="nohupenv TZ=${WORK_DIR}/localtime"`
`PRECMD=""`
`POSTCMD=""`
`DESC="$PROCS"`
`PATH="/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`
`export TZ="$(cat /etc/TZ)"`
`. /opt/etc/init.d/rc.func`

and I am attaching the rc.func  `/opt/etc/init.d/rc.func` 


[rc.func.txt](https://github.com/AdguardTeam/AdGuardHome/files/8019474/rc.func.txt)

**Comment by jumpsmm7** [comment]
@ainar-g 

here is a JPEG of my ssh terminal session to show you the steps from a terminal perspective 

![SSH-Terminal](https://user-images.githubusercontent.com/49514613/152891818-46b0bf32-be0f-468a-b08b-c2e7854bf270.jpg)

**Comment by jumpsmm7** [comment]
Here is more details when I trap the values
![Trapvalues](https://user-images.githubusercontent.com/49514613/152899707-5c116f9c-6f8e-4f5d-b32a-f7104de04104.jpg)

**Comment by jumpsmm7** [comment]
@ainar-g 

Here is another test I tried

![image](https://user-images.githubusercontent.com/49514613/152900835-185eff32-0326-46f4-a111-86c393c79724.png)

**Comment by jumpsmm7** [comment]
@ainar-g 
So in short, from the images provided above, whenever I Ctrl+C from the tail -f it some how alarts adguardhome to kill the process. Two things could be occuring (or more than one at the same time). Either some how adguardhome is detecting the Ctrl+C to escape the tail -f as a SIGINT thus it is shutting down in response, or AdGuardHome is recieving SIGKILL from tail -f from the Ctrl+C given to tail -f. The latter of which I find very hard to believe. I find it hard to believe that tail -f could send a SIGKILL

**Comment by jumpsmm7** [comment]
@ainar-g 
Here is me using ctrl+\ 

![image](https://user-images.githubusercontent.com/49514613/152912921-86d7d12a-16b9-4542-90ad-b9bf8704d7cf.png)

**Comment by dave14305** [comment]
If you start AGH, and immediately exit the ssh session, is it fine, even if you login again and run the tail?

**Comment by jumpsmm7** [comment]
yes

**Comment by jumpsmm7** [comment]
One possible issue is 

The kernel will send a SIGPIPE signal to the other process on the pipe when tail has terminated. The default action for this signal (if a handler is not installed) is to terminate the process.

**Comment by jumpsmm7** [comment]
![i

@dave14305 
> If you start AGH, and immediately exit the ssh session, is it fine, even if you login again and run the tail?

Humoring your thought process abit further I logged out again after starting the session, logged back in and ran tail -f
![image](https://user-images.githubusercontent.com/49514613/152916178-cdc19120-a650-4844-acf9-adac231c5aea.png)

it shows the hangup signal being sent from a new SSH session. Fortunately, I run this with nohup which means no hangups.
![image](https://user-images.githubusercontent.com/49514613/152916232-b406b2b4-8aaa-4f76-83fa-33ee6a192678.png)

**Comment by jumpsmm7** [comment]
As far as I can tell, this issue is still present. It is involved in the way AdGuardHome handles system calls. 

Here is what nextdns (another go package distribution.) did to resolve this issue. Asuswrt-Merlin Users also observed this same system call handling issue when running nextdns. 

https://github.com/nextdns/nextdns/commit/8d525d8d6338d1c4f302ad5b383aebde50edd9cd

**Comment by jumpsmm7** [comment]
> I cannot reproduce this on Ubuntu. Are you sure that there wasn't anything other than `tail -f` involved? And how was AGH launched?

The reason why you are unable to produce this on Ubuntu is because the INIT signals are inherited and handled differently on Ubuntu OS or any other Debian Based OS environment. When running AdGuardHome from a terminal session on an RT-AX88U router, the AdGuardHome process spawns as a child process to the parent that calls it. (i.e. the parent that calls it.) Once the Parent dies or is killed,  the child process eventually is handled by INIT, which will eventually kill the process. Users have reported AdGuardHome death to be approximately 2 days after starting. I have added a Handler that is impervious to INIT signals to restart AdGuardHome the moment it stops.

**Comment by jumpsmm7** [comment]
@ainar-g

In this situation, AdGuardHome does not fork away from the parent that starts it, thus once the Parent process that started it ends of finishes, AdGuardHome is passed to INIT. When viewing the Tail -f log, the AdGuardHome process is able to recieve the INIT signal from the Ctrl+C used to exit the the Tail -f log session. As @dave14305 has noted that this event only occurs if the tail -f is ran in the same terminal session in which the install process has occured.

**Comment by jumpsmm7** [comment]
Heres logs to indicate the Parent child link
`
/tmp/home/root# ps -T | grep AdGuardHome
13572 Sam-Netw  3500 S    {S99AdGuardHome} /bin/sh /opt/etc/init.d/S99AdGuardHome monitor-start
13834 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13836 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13837 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13838 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13839 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13842 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13843 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13849 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13851 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13852 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
13926 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
19202 Sam-Netw  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog
`

**Comment by jumpsmm7** [comment]
Here is an example that shows this child process relationship

`RT-AX88U-C7C0:/tmp/home/root# ps -T | grep AdGuardHome`
`13572 ********  3500 S    {S99AdGuardHome} /bin/sh /opt/etc/init.d/S99AdGuardHome monitor-start`
`13834 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13836 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13837 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13838 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13839 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13842 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13843 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13849 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13851 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13852 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`13926 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`
`19202 ********  730m S    AdGuardHome -s run -c /opt/etc/AdGuardHome/AdGuardHome.yaml -w /opt/etc/AdGuardHome --pidfile /opt/var/run/AdGuardHome.pid --no-check-update -l syslog`


Running this command after installing and exiting the installer shows that the children are passed to PID 1 (a.k.a) INIT

`RT-AX88U-C7C0:/tmp/home/root# awk '/PPid:/{print $2}' /proc/13572/status`
`1`
`@RT-AX88U-C7C0:/tmp/home/root# awk '/PPid:/{print $2}' /proc/13834/status`
`1`

**Comment by jumpsmm7** [comment]
The above outputs shows that previous analysis is proof in concept, when the terminal session or the parent installer process finishes the process is passed to INIT on the Asus Router Platform. This indicates that AdGuardHome fails to fork off from a parent process and form its own PID. Implications indicate due to lack or limited handling capabilities of Adguardhome,  that the process will eventually be killed if that is the nature of the INIT setup.

**Comment by jumpsmm7** [comment]
Thanks to @dave14305 recommendations. Calling AdGuardHome using the AsusWRT-Merlin RC.services for stopping/starting/etc. has resolved the issue presented with syscall. It appears when starting AdGuardHome using terminal session (without RC.services), AdGuardHome becomes susceptible to the sub shell environmental behaviors it is spawned from. I am closing this issue because I do not believe there is anything that can be done to fix this type of issue. However I wanted to provide feedback for future package handlers and issues spawned from such observed behaviors. I appreciated the AdGuardHome Devs for all of their continued support of AdGuardHome.
