### ISSUE TITLE
 address already in use

### ISSUE THREAD

**Issue by nahaczpiotr** [AdguardTeam/AdGuardHome#4259]
Admin web interface
 Listening interface
 All Interfaces
 Harbor
 80
 listen tcp 0.0.0.0:80: bind: address already in use
 Your AdGuard Home administrator web interface will be available at the following addresses:
 http://127.0.0.1/
 http://172.17.0.1/
 http://192.168.0.48/

 http://::1/
 DNS server
 Listening interface
 All Interfaces
 Harbor
 53
 listen udp 0.0.0.0:53: bind: address already in use
 Port 53 is often occupied by the "DNSStubListener" or "systemd-resolved" services.  Please read [this instruction](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse) to know how to solve this problem.
 You will need to configure your devices and router to use the DNS server on the following addresses:
 127.0.0.1
 172.17.0.1
 192.168.0.48

 ::1
 Static IP address
 AdGuard Home is a server, so it needs a static IP address to work properly.  Otherwise, at some point, your router might assign a different IP address to this device.
 I am using Pihole on the raspberry pire 2b and would like to add adGuard too
 How to do ?

**Comment by EugeneOne1** [comment]
@nahaczpiotr, hello.  Could you please give a few clarifications?

 1.  Which OS hosts the AdGuard Home?
 1.  How did you install AdGuard Home?
 1.  What version of AdGuaard Home is used?

**Comment by jumpsmm7** [comment]
@nahaczpiotr 
> Admin web interface Listening interface All Interfaces Harbor 80 listen tcp 0.0.0.0:80: bind: address already in use Your AdGuard Home administrator web interface will be available at the following addresses: http://127.0.0.1/ http://172.17.0.1/ http://192.168.0.48/
> 
> http://::1/ DNS server Listening interface All Interfaces Harbor 53 listen udp 0.0.0.0:53: bind: address already in use Port 53 is often occupied by the "DNSStubListener" or "systemd-resolved" services. Please read [this instruction](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse) to know how to solve this problem. You will need to configure your devices and router to use the DNS server on the following addresses: 127.0.0.1 172.17.0.1 192.168.0.48
> 
> ::1 Static IP address AdGuard Home is a server, so it needs a static IP address to work properly. Otherwise, at some point, your router might assign a different IP address to this device. I am using Pihole on the raspberry pire 2b and would like to add adGuard too How to do ?

using an ssh terminal 
what is the output from :

`netstat -nlp | grep 80`

**Comment by nahaczpiotr** [comment]
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Download ans install AdG
sudo apt update
sudo apt full-upgrade
sudo reboot

curl -s -S -L
https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
| sh -s -- -v

After i use http://192.168.048:3000 by brave browser
 My raspberry Pi has a fixed address192. 168.0.48

Is last version of adguard home
/opt/AdGuardHome/AdGuardHome -s status
2022/02/08 08:23:00 [info] service: control action: status
2022/02/08 08:23:00 [info] service: running
2022/02/08 08:23:00 [info] service: action status has been done
successfully on linux-systemd

opt/AdGuardHome/AdGuardHome --version
AdGuard Home, version v0.107.2


|---------------------------------------------|
NAHACZ Piotr

Tel : +33769946245
@ : ***@***.***

LinkedIn : CV Linkedin
|---------------------------------------------|

**Comment by tannertechnology** [comment]
You won't be able to use AdGuard Home and Pihole on the same device. You will need to disable Pihole to give Adguard access to the required ports.

**Comment by nahaczpiotr** [comment]
Ok thx
I don't can use pihole and adguard at the same time?

|---------------------------------------------|
NAHACZ Piotr

Tel : +33769946245
@ : ***@***.***

LinkedIn : CV Linkedin
|---------------------------------------------|

Le mer. 9 févr. 2022 à 07:02, Tanner Anderson ***@***.***> a
écrit :

**Comment by tannertechnology** [comment]
@nahaczpiotr If you get both running, which one will work? Will it be adguard or pihole trying to block your ads?

**Comment by Junkitkit** [comment]
May I know how to solve this issue in openwrt on virtual box linux os?

**Comment by tannertechnology** [comment]
@Junkitkit Either run AdGuard Home or PiHole, not both on the same box.

**Comment by Junkitkit** [comment]
Thank you.
