### ISSUE TITLE
Running A Root Server Locally On Your DNS Resolver

### ISSUE THREAD

**Issue by muhanadali100** [AdguardTeam/AdGuardHome#4260]
Can add a feature that make the DNS Work without Forwards ?

**Comment by ainar-g** [comment]
Do you mean, AdGuard Home working as a recursive DNS resolver *à la* `unbound`?  If so, this is a dup of #790.

**Comment by muhanadali100** [comment]
https://blog.technitium.com/2021/07/running-root-server-locally-on-your-dns.html 

Thats what i mean
