### ISSUE TITLE
Allow choosing IP version preference for upstream servers

### ISSUE THREAD

**Issue by chemcodex** [AdguardTeam/AdGuardHome#4262]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.3
* **How did you install AdGuard Home:**
GitHub releases
* **How did you setup DNS configuration:**
System
* **CPU architecture:**
AMD64
* **Operating system and version:**
Windows 10 21H2

### Expected Behavior
Adguard Home communicate with Google DNS(DoT/DoH) in IPv6

### Actual Behavior
It just ignore the AAAA record and request with IPv4

**Comment by ainar-g** [comment]
Hello.  What exactly is the issue you're dealing with?  The current algorithm prioritizes IPv4 addresses over IPv6 ones because situations where IPv4 is available but IPv6 isn't are more common than the reverse.

**Comment by chemcodex** [comment]
well, i use ipv6 to bypass some network blocking/interference in china thats why i do this.
so can i force enable ipv6 for DoH/DoT server

**Comment by ainar-g** [comment]
I see, thanks!  We'll consider ways we could do that.

**Comment by gspannu** [comment]
> 
> ### Expected Behavior
> Adguard Home communicate with Google DNS(DoT/DoH) in IPv6
> 
> ### Actual Behavior
> It just ignore the AAAA record and request with IPv4

Are you saying that even if you put
```
https://dns64.dns.google/dns-query
tls://dns64.dns.google
```
as your upstream DNS servers, AGH still sends the request to the Google IPv4 addresses?

**I too am keen to understand the behaviour of AGH**

**Comment by cfouche3005** [comment]
I can add that normal dns and dns over tls works fine

**Comment by ainar-g** [comment]
@gspannu, from what I can see, those have only IPv6 addresses, so those are used.  AdGuard Home merely prioritizes IPv4 addresses.  It doesn't completely ignore IPv6 addresses.

**Comment by daryll-swer** [comment]
Any updates on this in 2023? DNS traffic originating from AdGuard Home uses 99.99% IPv4, even though the underlying host has native IPv6.

Here's data from the Cloudflare peering portal for my ASN, whereby we can see 99% of DNS traffic to them, from my network (AdGuard Home) is IPv4. IPv6 is ignored completely.

![image](https://user-images.githubusercontent.com/80836254/223686793-f41d1203-6532-460d-9bb6-acd289a3accf.png)

**Comment by ainar-g** [comment]
@chemcodex, we've added this feature in the latest Edge release.  You can enable IPv6 preference for bootstrapping DoH, DoT, and DoQ upstreams by stopping AGH, setting `dns.bootstrap_prefer_ipv6` to `true`, and restarting AGH again.  Can you please check if the feature works for you?

**Comment by chemcodex** [comment]
@ainar-g thank you, its working perfectly. wait for it to be pushed to stable channel
<img width="867" alt="image" src="https://user-images.githubusercontent.com/45501123/229781894-1adc1ead-d85c-4726-9ba3-b67e7e2a36ae.png">

**Comment by daryll-swer** [comment]
Does this fix **only** for bootstrapping **or** also fixes for main DNS queries sent via upstream? @chemcodex/@ainar-g?

**Comment by chemcodex** [comment]
> Does this fix **only** for bootstrapping **or** also fixes for main DNS queries sent via upstream? @chemcodex/@ainar-g?

i think it fixes the upstream queries, though the string name is `dns.bootstrap_prefer_ipv6`.
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/45501123/229791257-6960f04c-7df2-4ae8-8bf5-107f79b1fc8c.png">

**Comment by ainar-g** [comment]
@daryll-swer, I'm not sure what you mean, sorry.  The change makes it possible to prefer IPv6 addresses of hostnames that you use for DoH, DoT, and DoQ.  That is, if you use `https://dns.adguard-dns.com/dns-query` as the DoH upstream then by default AGH will prefer IPv4 addresses of `dns.adguard-dns.com` (e.g. `94.140.14.14`), but with this flag set to `true` it will prefer the IPv6 ones (e.g. `2a10:50c0::ad1:ff`).

**Comment by daryll-swer** [comment]
> @daryll-swer, I'm not sure what you mean, sorry. The change makes it possible to prefer IPv6 addresses of hostnames that you use for DoH, DoT, and DoQ. That is, if you use `https://dns.adguard-dns.com/dns-query` as the DoH upstream then by default AGH will prefer IPv4 addresses of `dns.adguard-dns.com` (e.g. `94.140.14.14`), but with this flag set to `true` it will prefer the IPv6 ones (e.g. `2a10:50c0::ad1:ff`).

Yes, that's what I meant. I'm unable to test the edge build as I do not have the time, but will surely check it out in stable release. I can easily fetch real-time data from Cloudflare portal for network to verify.

**Comment by grzchr15** [comment]
https://internet.nl/site/dns.adguard-dns.com/2025187/#

please can we get tls configuration also fixed?

**Comment by ainar-g** [comment]
@grzchr15, that looks like an issue related to AdGuard DNS< not AdGuard Home, so it's off-topic in this repository.  Also please see #5670.

**Comment by daryll-swer** [comment]
@ainar-g So it's been 30 days of testing. As per the data I pulled from Cloudflare peering portal, we can see that indeed AdGuard Home **is** sending queries over IPv6, however it is still preferring IPv4 most of the time based on the data, even though the underlying IPv6 network and routing is symmetrical and identical to IPv4.

AdGuard Home still needs further improvements in this regard. IPv6 when set to preferred should be preferred 100% with v4 as fallback in case v6 is unreachable.

![image](https://user-images.githubusercontent.com/80836254/236697582-16f780a8-bed0-4025-8114-f7ed35313f5d.png)

**Comment by kiwilad-nz** [comment]
Will this be pushed to stable any time soon?

Cheers.

**Comment by uenokatsura** [comment]
@kiwilad-nz I believe it's already on stable now and is enabled by default.
________________________________
寄件者: kiwilad-nz ***@***.***>
寄件日期: Saturday, August 19, 2023 8:39:28 PM
收件者: AdguardTeam/AdGuardHome ***@***.***>
副本: Ueno Katsura ***@***.***>; State change ***@***.***>
主旨: Re: [AdguardTeam/AdGuardHome] Allow choosing IP version preference for upstream servers (Issue #4262)


Will this be pushed to stable any time soon?

Cheers.

**Comment by kiwilad-nz** [comment]
I'm on v0.107.36 but don't see that string in my yaml.

I'm also doinf a pftop on the destination ipv4 and ipv6 from my pfsebse but ipv4 are only being used from my wan.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dminca** [comment]
Hi there, it’s 2026 and IPv6 adoption has increased roughly.
Do you think it’s worth to take a look at this topic once again and respect “Parallel requests” setting, thus preferring an equal DNS upstream resolution prioritization between IPv4/6 ? 

I’m currently on v0.107.71 and it’s still prioritizing IPv4 upstream servers even though the latency between IPv4/6 is identical (got 22ms on both currently).
