### ISSUE TITLE
DNS servers aren't assigned after system reboot

### ISSUE THREAD

**Issue by neilio** [AdguardTeam/AdGuardHome#4268]
### Issue Details

* **Version of AdGuard Home server:**
AdGuard Home
Version: v0.107.3
Channel: release
Go version: go1.16.12
Build time: 2022-01-25T13:34:45Z+0000
GOOS: darwin
GOARCH: arm64
Race: false
Dependencies:
* **How did you install AdGuard Home:**
Downloaded from Github
* **How did you setup DNS configuration:**
Running on an M1 Mac Mini (2020 edition)
* **CPU architecture:**
amd64
* **Operating system and version:**
macOS 12.2

### Expected Behavior
I am using AGH for DHCP as well as filtering. After rebooting the OS, AdGuardHome should launch and propagate its IP as a DNS server to itself and the rest of the network. When I look at the AGH mac's network settings I should see its network IP (192.168.2.2) as the main DNS server.

### Actual Behavior
After a reboot the DNS servers are set to 169.x.x.x and DNS is not working on the AGH system itself or the rest of the network.  I need to manually stop, and then restart the AdGuardHome service from the command line to fix this.
</details>

**Comment by Birbber** [comment]
Closing this issue as completed. Feel free to re-open if needed.
