### ISSUE TITLE
"head: unrecognized option: c" on DD-WRT OS

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#4269]
![Screenshot_2022-02-10-03-26-36-710_com termux](https://user-images.githubusercontent.com/28734349/153275651-cf27ba9f-ba71-4289-9b38-1db59d15d189.jpg)

**Comment by ainar-g** [comment]
>  `head: unrecognized option: c`

This looks like a compatibility issue.  The POSIX standard, indeed, doesn't specify the `-c` flag.  Even though most implementations support it.  We should fix that.

 >  `Read-only file system`

Perhaps, the home directory is mounted as readonly?  Have you tried a different location?

 >  `Permission denied`

After `chmod +x`, it should have worked.  I don't know, which distributive DD-WRT is based on, but we have an [FAQ entry][1] about similar issues on Fedora.  Please see if those solutions work for you.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#fedora

**Comment by Potterli20** [comment]
dd-wrt有x86的系统，可以研究一下，因为我的分支是每天更新。dd-wrt和openwrt系统不一样。可能要优化一下

Dd-wrt has x86 systems that can be researched as my branch is updated daily. Dd-wrt and OpenWRT systems are different. It might have to be optimized
![Screenshot_2022-02-10-09-12-24-259_com termux](https://user-images.githubusercontent.com/28734349/153317750-21bdc9fe-c8bd-4d79-8bbc-c158ba3f50a3.jpg)

**Comment by Potterli20** [comment]
https://download1.dd-wrt.com/dd-wrtv2/downloads/betas/

**Comment by ainar-g** [comment]
@Potterli20 

The `head -c` issue should now be fixed in the master branch.

Regarding the `Read-only file system` and similar errors.  Have you tried inspecting `/proc/mounts`?

**Comment by Potterli20** [comment]
> @Potterli20
> 
> The `head -c` issue should now be fixed in the master branch.
> 
> Regarding the `Read-only file system` and similar errors. Have you tried inspecting `/proc/mounts`?

Since my router does not have a USB flash drive attached, I install it directly with a script

**Comment by ainar-g** [comment]
@Potterli20, the default location it tries to install to is `/opt/AdGuardHome`.  Judging by your terminal output, you are in the home director of the `root` user, so I assume it's `/root/`?  If that's where you want to install it, use the `-o` flag:

```sh
curl … | sh -s -- -c edge -o "$( pwd )" -v
```

**Comment by Potterli20** [comment]
> @Potterli20, the default location it tries to install to is `/opt/AdGuardHome`. Judging by your terminal output, you are in the home director of the `root` user, so I assume it's `/root/`? If that's where you want to install it, use the `-o` flag:
> 
> ```shell
> curl … | sh -s -- -c edge -o "$( pwd )" -v
> ```

 curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGua
rdHome/master/scripts/install.sh | sh -s -- -c edge -o "$( pwd )" -v
starting AdGuard Home installation script
channel: edge
operating system: linux
cpu type: mipsle_softfloat
AdGuard Home will be installed into /tmp/root/AdGuardHome
checking tar
script is executed with root privileges
no need to uninstall
downloading package from https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_mipsle_softfloat.tar.gz -> AdGuardHome_linux_mipsle_softfloat.tar.gz
successfully downloaded AdGuardHome_linux_mipsle_softfloat.tar.gz
unpacking package from AdGuardHome_linux_mipsle_softfloat.tar.gz into /tmp/root
successfully unpacked, contents: 
-rwxrwxrwx    1 root     root      35717120 Feb 12 00:04 AdGuardHome
-rw-rw-rw-    1 root     root           331 Feb 12 00:04 AdGuardHome.sig
-rw-r--r--    1 root     root         35141 Feb 12 00:04 CHANGELOG.md
-rw-r--r--    1 root     root         35149 Feb 12 00:04 LICENSE.txt
-rw-r--r--    1 root     root         23236 Feb 12 00:04 README.md
2022/02/12 17:07:19 [info] service: control action: install
2022/02/12 17:07:19 [fatal] service: executing action "install": Failed to install AdGuard Home service: open /etc/init.d/AdGuardHome: read-only file system
installation failed, removing /tmp/root/AdGuardHome
cannot install AdGuardHome as a service

**Comment by ainar-g** [comment]
@Potterli20, thanks for trying out the fix for the script!  The fix seems to work.

I still don't know what happens that causes the `read-only file system` errors, but if seems like those have more to do with the OS as opposed to AdGuard Home.  I'll close the issue for now, if you don't mind.  If you ever find the reason for those errors, please inform us so that we could add some documentation about that.
