### ISSUE TITLE
Garmin fitness devices sync stop

### ISSUE THREAD

**Issue by sevkar** [AdguardTeam/AdGuardHome#427]
With AdGuardHome Garmin fitness device can't sync their data. With direct dns all works correct. 

There is no any blocking marks on log. 

### Steps to reproduce
1. Just sync device and get error. 
2. Set direct 1.1.1.1 dns and sync device without error. 
3. Set AdGuardHome on and sync device, get error. 

### Expected behavior
Syncing data without error. 

### Actual behavior
No syncing

</details>

### Your environment
Rasperry Pi/Rasbian and PC/Debian 9.5. 

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.9 and 0.9-hotfix
| How did you setup DNS configuration:| System and router
| If it's a router or IoT, please write device model:|  Ubiquiti ER-4
| Operating system and version:| Latest Rasbian and Debian

**Comment by sevkar** [comment]
I have tried everything and no go. All off, zero filters. Get error. With direct 1.1.1.1 works correct.

Nice app, but useless with these small bugs. Like that I can't unblock sites.

**Comment by ameshkov** [comment]
I have tried everything and no go. All off, zero filters. Get error. With direct 1.1.1.1 works correct.

We might need to introduce some extended logging to figure what's wrong here.
Just in case, please try setting 8.8.8.8 as an upstream and check if there's any change.

> Nice app, but useless with these small bugs. Like that I can't unblock sites.

How so? Could you please give an example?

**Comment by sevkar** [comment]
I tried 1.1.1.1 and 1.0.0.1 without tls. No go still. 

I tested unblock one site and no change, get still blocked. Installation is without script. And I can't get data from Garmin's devices.

**Comment by sevkar** [comment]
With Pi Hole Garmin syncing works.
