### ISSUE TITLE
v0.107.3 no longer does strict search for client IPs

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#4271]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Environment

* **Version of AdGuard Home server:**
  * v0.107.3
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Issue details

Client IPs selected for search, whether it is through Dashboard -> Top Clients or from Query Log itself are not quoted, thus leading to the API returning more results than intended.

While I think this is a limitation of the API to "search" by IP rather than return results for an absolute IP address, searching for `10.0.0.1` searches for `10.0.0.1*` IPs. 

I reported this in #3838.

### Additional Information

During the beta cycle, all searches were quoted, that usually returned results from that specific client. It no longer does that.

**Comment by agneevX** [comment]
CC @jojost1, would it be possible to quote all client IP searches? The issue I reported seems to be back.

**Comment by ainar-g** [comment]
Weird.  I really thought that we've fixed that.  @IldarKamalov, please take a look.

**Comment by ainar-g** [comment]
@agneevX, this should be fixed on the edge channel in version v0.108.0-a.72+b43aa86c.  Can you please check?  (Don't forget to clear the browser's cache.)

**Comment by agneevX** [comment]
Can confirm the fix. Thanks @ainar-g @IldarKamalov.
