### ISSUE TITLE
Wrong AGHome service status

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#4273]
1. Open the console and stop the service;
2. Check its status;
3. Status shows `not installed` instead of `stopped`.

[Screenshot](https://uploads.adguard.com/Chinaskiijvww.png) with the issue

**Comment by EugeneOne1** [comment]
As for macOS, the package [service](https://github.com/kardianos/service) has a related issue (kardianos/service#285) which currently isn't resolved.  I suppose we should come up with some workaround, perhaps a fork.

**Comment by ainar-g** [comment]
@EugeneOne1, I do think that if we are able to make a version that solves the issue then we should make a fork, propose a merge, and use the fork until our fix is merged.

**Comment by EugeneOne1** [comment]
It's also reproducable on Linux with `systemd`.

**Comment by EugeneOne1** [comment]
It seems updating the [github.com/kardianos/service](https://github.com/kardianos/service) to the `v1.2.1` have [fixed](https://github.com/kardianos/service/compare/v1.2.0...v1.2.1) the `status` issue on both `launchd` (macOS) and `systemd` (Linux) systems.

@Chinaski1, could you please try to reproduce it in the latest edge/beta builds?

**Comment by Chinaski1** [comment]
![image](https://user-images.githubusercontent.com/49645813/169029764-3099073b-759d-47b0-916a-b51a93160f9f.png)
