### ISSUE TITLE
Change the default port for DoQ to 853

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#4276]
IANA agreed to allocate that port for DoQ so there should be no issues with it anymore.

We'll need to make the appropriate changes to dnsproxy as well.

**Comment by ainar-g** [comment]
That's a change in the defaults, so setting to v0.108.0.  We should also make sure to document the history of change for this value in the Wiki and the change log.

**Comment by thb007** [comment]
@ainar-g @ameshkov 
If the doq port is changed to 853, why is the port of dot? Android's private dns currently defaults to 853 for dot.

**Comment by Potterli20** [comment]
I would like to ask that QUIC can use CDN?

**Comment by agneevX** [comment]
> If the doq port is changed to 853, why is the port of dot? Android's private dns currently defaults to 853 for dot.

DNS over QUIC uses UDP, so 853/udp, whereas DNS over TLS uses the TCP transport, 853/tcp.

**Comment by agneevX** [comment]
> I would like to ask that QUIC can use CDN?

Please elaborate. Not sure what QUIC has to do with CDNs.
