### ISSUE TITLE
Add built-in update (and possibly UI)

### ISSUE THREAD

**Issue by fonix232** [AdguardTeam/AdGuardHome#428]
Right now updating AdGuard, especially hosted on a VPS, is a hassle. I keep SSH off on my VPS, so it means I have to go to their control panel, enable SSH, connect, stop the service, replace the binary, restart the whole shebang, then disable SSH again.

It would be nice if service detection and an update feature was built into the app itself. It doesn't have to be fancy, just store build ID, and check GitHub every few hours if a new release was posted, if there is, notify the user on the web UI, and allow them to download and install it.

**Comment by ameshkov** [comment]
Yeah, this makes perfect sense, thank you for the suggestion!

**Comment by fonix232** [comment]
I know it's a different language, but maybe [Sonarr](https://github.com/Sonarr/Sonarr)'s update mechanics can be checked out - they solved the whole shutdown-update-restart cycle quite nicely, from a web UI.

**Comment by ameshkov** [comment]
We were looking into this actually:
https://github.com/inconshreveable/go-update

**Comment by Bluscream** [comment]
I tried making my own (not very effective) updater, maybe someone can help me

```bash
sudo service aghome stop
cp AdGuardHome.yaml AdGuardHome.bak.yaml
ver="0.93"
wget "https://github.com/AdguardTeam/AdGuardHome/releases/download/v$ver/AdGuardHome_v{$ver}_linux_arm64.tar.gz"
exit
tar -zxvf "AdGuardHome_v{$ver}_linux_arm64.tar.gz" AdGuardHome/AdGuardHome
sudo service aghome restart
```

**Comment by ameshkov** [comment]
Well, you might need to `cp` with sudo as well

**Comment by Bluscream** [comment]
> 
> 
> Well, you might need to `cp` with sudo as well

I am more looking to the 404 error

**Comment by ameshkov** [comment]
Try something like this:
https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

**Comment by Bluscream** [comment]
Okay thanks, that one worked

```bash
# sudo service aghome stop
sudo cp AdGuardHome.yaml AdGuardHome.bak.yaml
arch="linux_arm64.tar.gz"
ver=$(curl -s https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
filename="AdGuardHome_${ver}_linux_arm.tar.gz"
echo "Updating AdGuardHome to ${ver} (${filename})"
wget -N https://github.com/AdguardTeam/AdGuardHome/releases/download/${ver}/${filename} -O ${filename}
tar -zxvf $filename -C ../
sudo service aghome restart
```

```
nano update.sh;root chmod +x update.sh;./update.sh
```
**BE SURE TO CHECK THE `arch=` before running the updater!**

**Comment by frenck** [comment]
Please note, this is not wished for on container solutions (e.g., Docker or Hass.io add-on), since it is shipped as part of a stateless piece.

Consider add-on a detection or env variable to allow for disabling this.

**Comment by ameshkov** [comment]
@frenck makes sense, thank you for mentioning it!

**Comment by ameshkov** [comment]
@szolin testing instruction:

1. Build AGH with redefined `versionCheckURL`: `-X main.versionCheckURL=NEW_URL`
2. Publish a test `versions.json` to the `NEW_URL`
3. Prepare and publish somewhere another build that will be "the test new version"
4. Run AGH as a service
5. Try the built-in update and check that it works as intended

**Comment by ameshkov** [comment]
One more thing to do: 
1. Start using `selfupdate_min_version` field from `version.json`
2. Use all files from the `zip`, not just the main binary
