### ISSUE TITLE
Configuration of a reverse proxy to one AdGuardHome instance with different block lists

### ISSUE THREAD

**Issue by c-key** [AdguardTeam/AdGuardHome#4280]
### Prerequisites

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Is there a way to configure different reverse proxy urls to one AdGuardHome instance with different block lists?
One example maybe for a better understanding.
I configure a reverse proxy url named .../tracking-filter-doh/..., this route will be used to block only tracking lists. Another reverse proxy url named .../ad-filter-doh/... will be used to block tracking and ads. Both reverse proxy urls will be redirect to one local AdGuardHome running instance.
Is there a way to configure this behaviour? Maybe with special settings (headers or something else) in the reverse proxy url configuration which redirect to AdGuardHome?

### Proposed Solution
I think one way to do this is, to run multiple instance of AdGuardHome in which are different lists of blocking types like tracking and/or ads.

### Alternatives Considered
But maybe it is possible to configure a header or something else to use only selected block lists of the one local running AdGuardHome instance. Something like ctag or clientip differentiation.

### Additional Information

**Comment by ainar-g** [comment]
Hello.  In v0.108.0 we are going to add the feature of having different filtering lists for different clients; see #435.  That, along with [ClientIDs][1] would allow you to use different URLs to get different types of filtering.  Would that work for you?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid

**Comment by c-key** [comment]
Thanks for your answer. It looks like what I am looking for. I will wait for v0.108.0 and test ist.
