### ISSUE TITLE
DNS request encryption, despite Encryption in Dashboard not enabled?

### ISSUE THREAD

**Issue by meeha-meeha** [AdguardTeam/AdGuardHome#4282]
### Prerequisites

- [x] I am running the latest version
    - Version: v0.107.3 as the time of writing
- [x] I checked the documentation and found no answer
    - checked, my documentation interpretation is ambiguous 
- [x] I checked to make sure that this issue has not already been filed
    - both open and closed issues
    
### Issue Details

* **Version of AdGuard Home server:** v0.107.3 
* **How did you install AdGuard Home:** Automated install (Linux and Mac) - from GitHub, using `curl`
* **How did you setup DNS configuration:** System
* **If it's a router or IoT, please write device model:** N/A
* **CPU architecture:** AMD64
* **Operating system and version:** Ubuntu 21.10

### Walkthrough of what I did

When on the page [https://adguard-dns.com/en/public-dns.html](https://adguard-dns.com/en/public-dns.html), when clicking Method 2 for Linux, there's a little suggestion to install "AdGuard Home". 

So I went ahead and installed AdGuard Home on my personal laptop instead of just modifying my DNS settings to point to the AdGuard DNS servers.
I live in a student's dormitory and hence don't have access to a router -- it's all WiFi.
So the server installed on my laptop is only used by my laptop. 

Installation was successful and I can see everything is working, based on the statistics on the Adguard dashboard (127.0.0.1). 

Upon checking out the "Comparing AdGuard Home to Other Solutions" Wiki page here - [https://github.com/AdguardTeam/AdGuardHome/wiki/Comparison](https://github.com/AdguardTeam/AdGuardHome/wiki/Comparison), it is mentioned that AdGuard Home basically uses "Running as a DNS-over-HTTPS or DNS-over-TLS server" out-of-the-box, whereas the Pi-Hole would need extensions.

Going to the Settings -> Encryption Settings of my AdGuard Home dashboard (127.0.0.1) reveals that Encryption is not enabled, however.

Researching encryption in the Wiki - [https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#install](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#install) mentions that "It does not make much sense to configure DNS encryption inside of your own local network. The purpose of securing your DNS traffic is to secure it from third-parties that might be analyzing or modifying it. For instance, from your ISP." 

In the Settings -> DNS Settings, I am using 
```
# encrypted DNS-over-HTTPS 
https://dns.adguard.com/dns-query
# encrypted DNS-over-TLS
tls://dns.adguard.com
```
as the upstream DNS servers.

### What am I trying to achieve

- DNS over HTTPS for all outgoing requests (securing from ISP for example)
- DNS over TLS for all outgoing requests (securing from ISP for example)
- Tracker and Ad blocking for my laptop

### My Questions

1. Does it make sense to have the AdGuard Home server installed on my personal machine, which won't act as an access point for other devices?
The alternative is just using the public AdGuard DNS servers I guess!
2. Even though encryption is not explicitly enabled in the Encryption settings of the AdGuard Home server, are my DNS requests still encrypted using DoH/DoT, masking (hiding) them from my ISP?
3. My final question has to do more with whether I've understood the AdGuard Home Server documentation correctly: So, it would make sense to enable encryption in the dashboard if the AdGuard Home server is located in a DigitalOcean droplet (for example), and I set my DNS settings to point to the droplet? 

### Conclusions

I think the AdGuard Team is doing a great job!
Thank you for taking the time to answer my questions.

**Comment by agneevX** [comment]
> Even though encryption is not explicitly enabled in the Encryption settings of the AdGuard Home server, are my DNS requests still encrypted using DoH/DoT, masking (hiding) them from my ISP?

`Encryption` is for receiving queries from clients only. Since you're already using secure transports for upstream DNS servers, its already encrypted.

> So, it would make sense to enable encryption in the dashboard if the AdGuard Home server is located in a DigitalOcean droplet (for example), and I set my DNS settings to point to the droplet?

If your DNS server is located outside your network, then yes, you should enable encryption. 

No, setting your DNS IP configuration to your droplet's IP defeats the purpose of setting up AdGuard Home. This is where you should use secure transport instead of plaintext DNS.

**Comment by meeha-meeha** [comment]
Thank you for the reply!

So,
>No, setting your DNS IP configuration to your droplet's IP defeats the purpose of setting up AdGuard Home. This is where you should use secure transport instead of plaintext DNS.
That's why there's there's a server name / domain name option, not an IP in the Encryption settings?

Referring back to my 1st question - so essentially it is good to have AdGuard Home Server installed on my machine, as it would encrypt the DNS requests, instead of having Ubuntu point to the static IPs of the AdGuard Public DNS Servers?

Kind regards

**Comment by agneevX** [comment]
> That's why there's there's a server name / domain name option, not an IP in the Encryption settings?

Not really. When you specify an IP address on your device, it's standard DNS, unless it's specified otherwise. 

> so essentially it is good to have AdGuard Home Server installed on my machine, as it would encrypt the DNS requests, instead of having Ubuntu point to the static IPs of the AdGuard Public DNS Servers?

Yes, it is. With AGH, it's proxying requests on behalf of you; it's unencrypted from you to AGH, encrypted from AGH to its upstreams.

**Comment by meeha-meeha** [comment]
Yes, I understand!

Well thank you for taking the time to answer all my questions!

Kind regards
