### ISSUE TITLE
DNS ERROR

### ISSUE THREAD

**Issue by munadutta** [AdguardTeam/AdGuardHome#4285]
i am using adguard home.. with docker

i set up dns on my laptop its working fine.. but when i set the dns with router and mobile..

its showing no internet connection..

whats the issue with this ?

**Comment by agneevX** [comment]
Please fill the prerequisites @munadutta.

**Comment by Birbber** [comment]
Closing this issue as incomplete. Please fill in the prerequisites if it's still relevant.
