### ISSUE TITLE
Only allow configured clients to use the block list 

### ISSUE THREAD

**Issue by speeed001** [AdguardTeam/AdGuardHome#4291]
- [ √] I am running the latest version  v0.107.3
- [ √] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed ( No related questions found? )

### Problem Description
Filter add function Allow only added clients to use .
I can't seem to find this problem, can anyone help me?

**Comment by ainar-g** [comment]
Hello.  We can't quite understand, what the feature request is about.  Just for the context, we plan to make it possible to configure separate block lists for different clients in v0.108.  See feature request #435.
