### ISSUE TITLE
Fallback DNS server in case of AGH downtime

### ISSUE THREAD

**Issue by maxauvy** [AdguardTeam/AdGuardHome#4293]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Depending on various events, the machine hosting AdGuard Home may go down unexpectedly. Thus, devices connected to the network cannot query their DNS server (AGH).
I use AGH as my DHCP server, as my ISP does not allow to change DNS configuration.

### Proposed Solution
An ideal solution would be to be able to advertise (through DHCP?) a fallback DNS server (the one from the ISP, or any other DNS server), which would be used only if the primary server does not answer.
Maybe something like `dhcp-option=6,AGH_IP,SecondaryDNS_IP` for dnsmasq?

Thanks a lot :)

**Comment by agneevX** [comment]
> I use AGH as my DHCP server

> An ideal solution would be to be able to advertise (through DHCP?)

If the DHCP server is down, then how would it advertise said DNS IPs?

**Comment by maxauvy** [comment]
Hello 😃 

> If the DHCP server is down, then how would it advertise said DNS IPs?
That shouldn't be a problem if the device has a valid DHCP lease. Of course if one switches on a device while the DHCP server is already down, there's no easy solution.

Thanks y'all for your answers!

**Comment by agneevX** [comment]
Well leases expire and its not prudent to depend upon them.

As I said, you can try setting multiple DNS servers in DHCP options and see whether the odds are in your favor when the DHCP server and the primary DNS server goes down.

**Comment by EugeneOne1** [comment]
@maxauvy, if there are no more questions, we'll close the issue.  Feel free to start a [discussion](https://github.com/AdguardTeam/AdGuardHome/discussions) on the topic.
