### ISSUE TITLE
Does AdGuardHome allow uprstream resolvers?

### ISSUE THREAD

**Issue by rugabunda** [AdguardTeam/AdGuardHome#4296]
I'd like to use AdGuardHome with Dnscrypt proxy upstream, is this possible?

**Comment by fernvenue** [comment]
I suggest you describe your issue more clearly. AdGuardHome allows many upstream protocols, including DNSCrypt, please read [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams).

**Comment by ainar-g** [comment]
@rugabunda, the upstreams are set on the “Settings → DNS settings” page in the UI.  Are you having any issues with that?

**Comment by rugabunda** [comment]
> @rugabunda, the upstreams are set on the “Settings → DNS settings” page in the UI. Are you having any issues with that?

Thank you, I haven't actually used the software yet, I'm just inquiring. Thanks!

When I say upstream, I'm talking a local dnscrypt-proxy client.

**Comment by fernvenue** [comment]
> > @rugabunda, the upstreams are set on the “Settings → DNS settings” page in the UI. Are you having any issues with that?
> 
> Thank you, I haven't actually used the software yet, I'm just inquiring. Thanks!
> 
> When I say upstream, I'm talking a local dnscrypt-proxy client separate from adguard, so I would simply point the upstreams to dnscryp-proxies listening address?:
> 
> listen_addresses = ['127.0.1.1:53']

Yes, you can easily add it to AdGuardHome upstream in the web UI.

**Comment by rugabunda** [comment]
> > > @rugabunda, the upstreams are set on the “Settings → DNS settings” page in the UI. Are you having any issues with that?
> > 
> > 
> > Thank you, I haven't actually used the software yet, I'm just inquiring. Thanks!
> > When I say upstream, I'm talking a local dnscrypt-proxy client separate from adguard, so I would simply point the upstreams to dnscryp-proxies listening address?:
> > listen_addresses = ['127.0.1.1:53']
> 
> Yes, you can easily add it to AdGuardHome upstream in the web UI.

Thank u Sister Didz

🇨🇦 HONK 🇨🇦
