### ISSUE TITLE
adguard-malware-shavar overblocking f003.backblazeb2.com

### ISSUE THREAD

**Issue by nohn** [AdguardTeam/AdGuardHome#4300]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.3
* **How did you install AdGuard Home:**
  * Github releases
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian Buster

### Expected Behavior
*f003.backblazeb2.com is resolved to correct ip

### Actual Behavior
* f003.backblazeb2.com is blocked by adguard-malware-shavar

### Additional Information

This issue breaks backuo tools like restic, see https://github.com/restic/restic/issues/3636

**Comment by ainar-g** [comment]
Hello.  Such issues are better reported using the [issue reporting form][1] or sending an E-mail to support@adguard.com.  I've forwarded your report to them, and they said that the domain should be removed from the list now.

[1]: https://reports.adguard.com/en/new_issue.html
