### ISSUE TITLE
CDNs should not exist in blocked services

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#4303]
AdGuard Home implements a lot of blocked services that can be enabled or disabled by default.

While I think there's an excessive amount of services that do not meet a certain criteria for blocking, CDNs should just not be blocked.

AGH should not attempt to block CDNs as it quite impossible to do so given there's millions of websites that could be using them and its therefore misleading to have an option that works in 20% of all cases.

It also makes no sense to block CDNs given they power a significant portion of the web.

I think Cloudflare should be removed.

**Comment by ainar-g** [comment]
I don't really think that we should do that.  CDNs can track users, and many privacy-aware people will use means of reducing the amount of information CDNs can gather, including browser extensions like [Decentraleyes][1].  In fact, Cloudflare was not added by the AGH developers, but rather was a community contribution.  See #1128 and #1155.  Users who don't want to block it should simply not enable this service on the blocked services page.

As for whether or not our list of services is excessive, perhaps #1692 could be extended to also allow people to remove some of the default services that AGH comes with.  Some kind of categorization on the UI could probably help as well.  I'll probably open an issue about the latter.

[1]: https://decentraleyes.org/
