### ISSUE TITLE
Stats Dates Incorrect

### ISSUE THREAD

**Issue by wexcide** [AdguardTeam/AdGuardHome#4310]
### Issue Details

* **Version of AdGuard Home server:**
  * Version: v0.107.3
* **How did you install AdGuard Home:**
  * Automated Install Script
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Netgear Orbi
* **CPU architecture:**
  * ARM
* **Operating system and version:**
  * Raspbian Latest

### Expected Behavior
30 Day stats should be reporting for the day they are logged/queried.

### Actual Behavior
Stats are showing on incorrect day. Example: AdGuard Home was deployed 18 Feb 22, however stats are being reported as part of 17 Feb 22
### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22379316/154785733-b567ab52-d47f-46a7-a9ba-4e78ea8822e2.png)

</details>

### Additional Information
Have tried re-deploying and changing stats timeline. The query log is all correct, all the entries reflect correct date and time, however when stats are summarized, the date is incorrect. However, it switches over and starts the new date around 9 pm. In my case, it starts summarizing the 18th at 9pm, so most of the stats for the 18th will actually be produced on the 19th until it switches over around 9pm to the 20th.

**Comment by fernvenue** [comment]
In my test, the time shown here is converted to follow the browser time, not the server time. Maybe you can check if your browser time and server time match. It's just my personal test and speculation, please refer to the actual situation, I hope it can help you.

**Comment by wexcide** [comment]
Interesting. Good find. There seems to be a disconnect between hardware time of my system and system time. I tried 3 browsers on my computer (Chrome, FF & Safari) with the same results. The browsers are using HW time for the stats graph. However, when viewed from my phone (iOS, Chrome), it displays correctly. Strange that it only applies to the stats graph and not the log.

**Comment by EugeneOne1** [comment]
@wexcide, hello and thanks for the report.  We'll merge this issue into #4434.  Please follow it to track the progress.
