### ISSUE TITLE
AdGuard hang after no answer from upstream dns.

### ISSUE THREAD

**Issue by byniow** [AdguardTeam/AdGuardHome#4315]
If upstream proxy are dead Adguard should still work. But no, i cannot restart or reload service but need to manually edit config .yaml file and remove faulty dns. Today this is quad9, tommorow can be diffrent. But AdGuard still should work even if only one upstream dns live.

2021/12/29 14:13:35.174920 [info] Start reconfiguring the server
2021/12/29 14:13:35.174946 [info] Stopping the DNS proxy server
2021/12/29 14:13:35.175013 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/12/29 14:13:35.175031 [info] Stopped the DNS proxy server
2021/12/29 14:13:35.275821 [info] Starting the DNS proxy server
2021/12/29 14:13:35.275876 [info] Ratelimit is enabled and set to 20 rps
2021/12/29 14:13:35.275887 [info] The server is configured to refuse ANY requests
2021/12/29 14:13:35.275896 [info] DNS cache is enabled
2021/12/29 14:13:35.275908 [info] MaxGoroutines is set to 300
2021/12/29 14:13:35.275922 [info] Creating the UDP server socket
2021/12/29 14:13:35.275974 [info] Listening to udp://[::]:53
2021/12/29 14:13:35.275987 [info] Creating a TCP server socket
2021/12/29 14:13:35.276023 [info] Listening to tcp://[::]:53
2021/12/29 14:13:35.276133 [info] Entering the UDP listener loop on [::]:53
2021/12/29 14:13:35.276171 [info] Entering the tcp listener loop on [::]:53
2021/12/29 14:13:48.414614 [info] upstream "https://dns10.quad9.net/dns-query" fails to exchange: couldn't communicate with upstream: couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap https://dns10.quad9.net:443/dns-query, cause: failed to lookup dns10.quad9.net, cause: synthetic.wrap: all resolvers failed to lookup, cause: read udp 192.168.10.2:33601->149.112.112.10:53: i/o timeout (hidden: read udp 192.168.10.2:38076->9.9.9.10:53: i/o timeout)
2021/12/29 14:13:58.415305 [info] upstream "8.8.8.8" fails to exchange: couldn't communicate with upstream: read udp 192.168.10.2:48714->8.8.8.8:53: i/o timeout
2021/12/29 14:13:58.433026 [info] Start reconfiguring the server
2021/12/29 14:13:58.433053 [info] Stopping the DNS proxy server
2021/12/29 14:13:58.433123 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/12/29 14:13:58.433141 [info] Stopped the DNS proxy server
2021/12/29 14:13:58.533949 [info] Starting the DNS proxy server
2021/12/29 14:13:58.533984 [info] Ratelimit is enabled and set to 20 rps
2021/12/29 14:13:58.534001 [info] The server is configured to refuse ANY requests
2021/12/29 14:13:58.534010 [info] DNS cache is enabled
2021/12/29 14:13:58.534021 [info] MaxGoroutines is set to 300
2021/12/29 14:13:58.534034 [info] Creating the UDP server socket
2021/12/29 14:13:58.534086 [info] Listening to udp://[::]:53
2021/12/29 14:13:58.534099 [info] Creating a TCP server socket
2021/12/29 14:13:58.534128 [info] Listening to tcp://[::]:53
2021/12/29 14:13:58.534246 [info] Entering the UDP listener loop on [::]:53
2021/12/29 14:13:58.534286 [info] Entering the tcp listener loop on [::]:53
2021/12/29 14:19:43.359432 [info] Received signal "terminated"
2021/12/29 14:19:43.359519 [info] stopping AdGuard Home
2021/12/29 14:19:43.359530 [info] stopping http server...
2021/12/29 14:19:43.375771 [info] stopped http server
2021/12/29 14:19:43.375843 [info] Stopping the DNS proxy server
2021/12/29 14:19:43.375885 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/12/29 14:19:43.375902 [info] Stopped the DNS proxy server
2021/12/29 14:19:43.532462 [info] Stopped

**Comment by fernvenue** [comment]
Look at these lines in your log:

> 2021/12/29 14:13:48.414614 [info] upstream "https://dns10.quad9.net/dns-query" fails to exchange: couldn't communicate with upstream: couldn't initialize HTTP client or transport, cause: couldn't initialize HTTP transport, cause: couldn't bootstrap [https://dns10.quad9.net:443/dns-query](https://dns10.quad9.net/dns-query), cause: failed to lookup dns10.quad9.net, cause: synthetic.wrap: all resolvers failed to lookup, cause: read udp 192.168.10.2:33601->149.112.112.10:53: i/o timeout (hidden: read udp 192.168.10.2:38076->9.9.9.10:53: i/o timeout)
2021/12/29 14:13:58.415305 [info] upstream "8.8.8.8" fails to exchange: couldn't communicate with upstream: read udp 192.168.10.2:48714->8.8.8.8:53: i/o timeout

It says: `all resolvers failed to lookup`, that means you already lost connection with all your upstreams, not like you said: *even if only one upstream dns live*, your instructions and what's actually going on in the log are different. Also, according to what your log says: `couldn't bootstrap` and `read udp...i/o timeout`, maybe you should check your Bootstrap DNS servers first, and why `read udp...i/o timeout` happens. Of course, that's just my personal speculation, please refer to the actual situation, I hope it can help you.

**Comment by byniow** [comment]
Now i have main DNS ( with deleted quad9 entry):
https://1.0.0.1/dns-query
https://1.1.1.1/dns-query
https://1.1.1.2/dns-query
https://1.0.0.2/dns-query
https://security.cloudflare-dns.com/dns-query
tls://security.cloudflare-dns.com
sdns://AgcAAAAAAAAABzEuMC4wLjGgENk8mGSlIfMGXMOlIlCcKvq7AVgcrZxtjon911-ep0cg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk
tls://1.1.1.1
tls://1.0.0.1
tls://1dot1dot1dot1.cloudflare-dns.com
https://cloudflare-dns.com/dns-query
8.8.8.8

And bootstrap:
9.9.9.10
149.112.112.10
1.1.1.1
8.8.8.8
1.0.0.1
1.1.1.2
1.0.0.2

After deleting quad9 entry i check connectivity via ping to 8.8.8.8 and 1.1.1.1 and there are not any problems. Other pings via domain name works too (system where i installed AdGuard have own google dns). I think - i have a lot redundant entries, should work always....

**Comment by fernvenue** [comment]
> Now i have main DNS ( with deleted quad9 entry): https://1.0.0.1/dns-query https://1.1.1.1/dns-query https://1.1.1.2/dns-query https://1.0.0.2/dns-query https://security.cloudflare-dns.com/dns-query tls://security.cloudflare-dns.com sdns://AgcAAAAAAAAABzEuMC4wLjGgENk8mGSlIfMGXMOlIlCcKvq7AVgcrZxtjon911-ep0cg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk tls://1.1.1.1 tls://1.0.0.1 tls://1dot1dot1dot1.cloudflare-dns.com https://cloudflare-dns.com/dns-query 8.8.8.8
> 
> And bootstrap: 9.9.9.10 149.112.112.10 1.1.1.1 8.8.8.8 1.0.0.1 1.1.1.2 1.0.0.2
> 
> Before deleting quad9 entry i check connectivity via ping to 8.8.8.8 and 1.1.1.1 and there are not any problems. Other pings via domain name works too (system where i installed AdGuard have 8.8.8.8 google dns). I think - i have a lot redundant entries, should work always.... I select load balancing option.

Yes, if you don't know what's the differences between the options, *Load-balancing* is always a good choice. Of course you can follow my recommandation if you interest https://github.com/AdguardTeam/AdGuardHome/issues/4314#issuecomment-1046105145:

- For IPV4:

```
#google
tls://8.8.8.8
tls://8.8.4.4
https://8.8.8.8/dns-query
https://8.8.4.4/dns-query

#cloudflare
tls://1.1.1.1
tls://1.0.0.1
tls://162.159.36.1
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
https://162.159.36.1/dns-query
```

- For IPv6:

```
#google
tls://[2001:4860:4860::8888]
tls://[2001:4860:4860::8844]
https://[2001:4860:4860::8888]/dns-query
https://[2001:4860:4860::8844]/dns-query

#cloudflare
tls://[2606:4700:4700::1001]
tls://[2606:4700:4700::1111]
https://[2606:4700:4700::1001]/dns-query
https://[2606:4700:4700::1111]/dns-query
```

These upstreams use encrypted protocols and they all have SSL certificates configured on their IP addresses, so there is no need for additional resolution by Bootstrap DNS servers, that means they can respond to requests as quickly as possible in *Parallel Request* mode with trusted and unfiltered answear.

**Comment by byniow** [comment]
Ok, thank You. I now use Your entries. But i think it's worth looking at this bug though.

**Comment by Birbber** [comment]
@byniow Apologies for the long silence! Is this issue still reproducible on the latest release?

**Comment by byniow** [comment]
Hi. No, after set entries from @fernvenue i have no problems with AdGuard. Maybye worth add this entries as default on fresh installs.
