### ISSUE TITLE
Feature Request - Allow connection to Dashboard web UI from other machines

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#432]
Right now, it seems that you can only connect to the AGH web UI via http://localhost:3000, and it is not possible to connect via actual IP address from either the host machine or another machine?

It would be appreciated if we could connect from other machines, i.e. http://adguardhome_machine_IP:3000

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.9 Hotfix 1
| How did you setup DNS configuration:| Windows Server DHCP
| If it's a router or IoT, please write device model:| na
| Operating system and version:| Ubuntu 18.04.1 running on Windows 10 WSL

**Comment by dfmcvn** [comment]
Change `bind_host` to `0.0.0.0`

**Comment by AnthonyBe** [comment]
Perfect! Thank-you!

this is something that could be added to the readme.md on line 97 where it describes the bind_host setting.

**Comment by ameshkov** [comment]
After #425 is done, you'll be able to select a proper net interface during the initial setup.
