### ISSUE TITLE
No funciona el bloqueo de anuncios ni el bloqueo de servicios.

### ISSUE THREAD

**Issue by nurhg** [AdguardTeam/AdGuardHome#4320]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots
![serviciosAdguard](https://user-images.githubusercontent.com/95660829/154987394-454a8f3c-58e6-4566-9b64-a880a95f3eef.png)
![servidorDHCP](https://user-images.githubusercontent.com/95660829/154987399-19fd5c74-1f5d-4989-b7ff-ae2947bfcafc.png)
![sinbloqueo](https://user-images.githubusercontent.com/95660829/154987401-45bc54fe-8e85-44d6-8bc2-07e6ea0d3eb5.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by jumpsmm7** [comment]
> Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).
> ### Prerequisites
> 
> Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**
> 
>     * [ x] I am running the latest version
> 
>     * [ x] I checked the documentation and found no answer
> 
>     * [ x] I checked to make sure that this issue has not already been filed
> 
> 
> ### Issue Details
> 
>     * **Version of AdGuard Home server:**
>       
>       *
> 
>     * **How did you install AdGuard Home:**
>       
>       *
> 
>     * **How did you setup DNS configuration:**
>       
>       *
> 
>     * **If it's a router or IoT, please write device model:**
>       
>       *
> 
>     * **CPU architecture:**
>       
>       *
> 
>     * **Operating system and version:**
>       
>       *
> 
> 
> ### Expected Behavior
> ### Actual Behavior
> ### Screenshots
> 
> ![serviciosAdguard](https://user-images.githubusercontent.com/95660829/154987394-454a8f3c-58e6-4566-9b64-a880a95f3eef.png) ![servidorDHCP](https://user-images.githubusercontent.com/95660829/154987399-19fd5c74-1f5d-4989-b7ff-ae2947bfcafc.png) ![sinbloqueo](https://user-images.githubusercontent.com/95660829/154987401-45bc54fe-8e85-44d6-8bc2-07e6ea0d3eb5.png)
> Screenshot:
> ### Additional Information

![image](https://user-images.githubusercontent.com/49514613/155255003-3b70a4ad-c75e-467b-b254-0c3038096a0b.png)

Deshabilite cualquier fuga de DNS del navegador y debería funcionar. Haga referencia a la imagen de arriba. Su configuración de DNS de Mozilla Firefox debería verse así.
