### ISSUE TITLE
Solo un cliente registra consultas

### ISSUE THREAD

**Issue by nurhg** [AdguardTeam/AdGuardHome#4325]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

Tengo habilitado el servidor DHCP y solo un cliente esta registrando consultas a pesar de que todos estan cursando trafico por el servidor y no hay otra manera de poder realizar salida a internet.

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

![registro](https://user-images.githubusercontent.com/95660829/155234378-fb1e4bcb-db53-4e4a-ae9a-58537e545b48.png)

</details>

**Comment by jumpsmm7** [comment]
> Tengo habilitado el servidor DHCP y solo un cliente esta registrando consultas a pesar de que todos estan cursando trafico por el servidor y no hay otra manera de poder realizar salida a internet.

Asegúrese de que sea el único DHCP que haya habilitado. Deshabilite el alojamiento DHCP en cualquier otro dispositivo de su red, incluido su enrutador de Internet.

**Comment by agneevX** [comment]
Also please fill up the prerequisites. It's hard to provide assistance when we have no idea of your environment.
