### ISSUE TITLE
Adguard login page not opening

### ISSUE THREAD

**Issue by nitin-gan** [AdguardTeam/AdGuardHome#4328]
I installed Adguard home on Raspberry Pi4 and it worked properly overnight.

In morning, i tried to login to portal, it is giving me only default apache page.

Clueless what happened overnight?

can someone assist? I am a newbie to this adguard thing.

**Comment by agneevX** [comment]
Sounds like some other web server is instead taking up that port.

**Comment by dentex** [comment]
Same, after (clean) reboot. I had a power loss, but shut down the system while on ups. At new boot, default Apache page... What to do?
