### ISSUE TITLE
AdGuard Home seems cause my PC BSOD

### ISSUE THREAD

**Issue by toorich** [AdguardTeam/AdGuardHome#4329]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.3
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 10 21H2

### Expected Behavior
The program run normally.

### Actual Behavior
BSOD with `KERNEL_SECURITY_CHECK_FAILURE`

### Additional Information
Here is the dump file: https://drive.google.com/file/d/1s0QWJF8zMVzPU8CMG1QKwsEMk_D3Oyaw

**Comment by ainar-g** [comment]
Hello and thanks for the report and the dump!  The dump file seems to indicate that something went wrong inside the OS.  Have you tried running the `sfc /scannow` command to recheck system files?

**Comment by toorich** [comment]
> Hello and thanks for the report and the dump! The dump file seems to indicate that something went wrong inside the OS. Have you tried running the `sfc /scannow` command to recheck system files?

Tried, but sfc returns "Windows Resource Protection did not find any integrity violations." , and i tried `DISM /Online /Cleanup-Image /RestoreHealth` to rule out the possibility of system file corruption. It successed, but still BSOD.

**Comment by toorich** [comment]
> > Hello and thanks for the report and the dump! The dump file seems to indicate that something went wrong inside the OS. Have you tried running the `sfc /scannow` command to recheck system files?
> 
> Tried, but sfc returns "Windows Resource Protection did not find any integrity violations." , and i tried `DISM /Online /Cleanup-Image /RestoreHealth` to rule out the possibility of system file corruption. It successed, but still BSOD.

And when I disabled AdGuard Home service, the system will not BSOD.

**Comment by ainar-g** [comment]
Thanks for the info!  We'll investigate shortly.

**Comment by ainar-g** [comment]
Thanks for the info!  We'll investigate shortly.

**Comment by jumpsmm7** [comment]
> > Hello and thanks for the report and the dump! The dump file seems to indicate that something went wrong inside the OS. Have you tried running the `sfc /scannow` command to recheck system files?
> 




> > Hello and thanks for the report and the dump! The dump file seems to indicate that something went wrong inside the OS. Have you tried running the `sfc /scannow` command to recheck system files?
> 
> Tried, but sfc returns "Windows Resource Protection did not find any integrity violations." , and i tried `DISM /Online /Cleanup-Image /RestoreHealth` to rule out the possibility of system file corruption. It successed, but still BSOD.

Have you added any new hardware recently, anything you could think of? Also, did you have any major updates to your windows recently that may have changed how it handles your computer peripherals. The reason I ask is because this could be related to a issue with a peripheral or piece of hardware, especially if you just changed windows or OS versions, or added a new piece of hardware or peripheral.

**Comment by toorich** [comment]
BSOD again...
Here is the dump file: https://drive.google.com/file/d/1wAkQlwU64qV3fgLvE7cXAtnbeRmB0zRH

**Comment by toorich** [comment]
@ainar-g Today my PC again and again...
Here is the dump file: https://drive.google.com/file/d/17JZ93Mta2WH2MhZ3P--9L3G4HXXOFY6f

**Comment by ainar-g** [comment]
@toorich, do you have some kind of non-Microsoft antivirus installed?  This crash seems to look a lot like the one often caused by some antivirus software, and in particular Avast.

**Comment by toorich** [comment]
> @toorich, do you have some kind of non-Microsoft antivirus installed? This crash seems to look a lot like the one often caused by some antivirus software, and in particular Avast.

I installed 360 Antivirus and Lenovo PC Manager (included Huorong antivirus engine) on my PC, but no Avast Antivirus Software installed.

**Comment by jumpsmm7** [comment]
> > @toorich, do you have some kind of non-Microsoft antivirus installed? This crash seems to look a lot like the one often caused by some antivirus software, and in particular Avast.
> 
> I installed 360 Antivirus and Lenovo PC Manager (included Huorong antivirus engine) on my PC, but no Avast Antivirus Software installed.

Try disabling any "self-installed" anti-virus software for temporary testing. Report back if you are still experiencing the same BSOD issue. I am wondering if there is some sort of conflict occurring when ran along side one of your anti-virus.

**Comment by toorich** [comment]
> > > @toorich, do you have some kind of non-Microsoft antivirus installed? This crash seems to look a lot like the one often caused by some antivirus software, and in particular Avast.
> > 
> > 
> > I installed 360 Antivirus and Lenovo PC Manager (included Huorong antivirus engine) on my PC, but no Avast Antivirus Software installed.
> 
> The anti-virus software business can sometimes be quite tricky, or a nuisance in the sense that sometimes they falsely categorize something as a virus, or they maybe conflicting when ran with another similar by design software. For example, in the instance of running two anti-virus software, one might unintentionally create a issue where there wasn't one before because anti-virus software don't run complimentary side by side with one another. The anti-virus software may simply define a similar software as a virus to prevent any competing software. Also, the anti-virus software may be using its own DNS servers and AdBlockers if it comes built in. There are a lot of factors you should consider here.
> 
> My advice, try disabling any "self-installed" or non-Microsoft anti-virus software for temporary testing. Report back if you are still experiencing the same BSOD issue. I am wondering if there is some sort of conflict occurring when ran along side one of your anti-virus.

Problem solved. It maybe caused by an old version of LuDaShi's driver.
