### ISSUE TITLE
How to block AdGuard Home from... AdGuard?

### ISSUE THREAD

**Issue by 7ArxS2PrqAUF9Gom** [AdguardTeam/AdGuardHome#4332]
I do not want AdGuard Home to contact any domains, except those specifically allowed by me via my own custom filters, but AdGuard Home queries do not list domains AdGuard Home uses for filter updates and queries do not list domains used by AdGuard Home for AdGuard Home updates.  I am not sure if there are other domains AdGuard Home contacts silently...

Filter updates can be disabled in AdGuard Home options, but there are no controls for domains it uses to update itself. I'd like to be able to manually check for AdGuard Home updates, but not have them checked automatically or at least see them in query list or just have some controls to disable them. I do not want any "keep-alive" connections. 

Are there specific IP ranges I can block in my router firewall to prevent AdGuard Home from checking for updates? 

Also, a secondary issue is DNS-over-QUIC port. Default settings specify port 784 for DoQ, but other AdGuard documentation mention port 8853. Which one is the correct one?

**Comment by agneevX** [comment]
> Filter updates can be disabled in AdGuard Home options, but there are no controls for domains it uses to update itself.

> Are there specific IP ranges I can block in my router firewall to prevent AdGuard Home from checking for updates?

[RTFM](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments).

> Also, a secondary issue is DNS-over-QUIC port. Default settings specify port 784 for DoQ, but other AdGuard documentation mention port 8853. Which one is the correct one?

DoQ is not finalized. It will change to 853/udp anyways (#4276).

**Comment by itsnotsaved** [comment]
>but there are no controls for domains it uses to update itself. RTFM.

@agneevX Is there any option? i couldn't find

**Comment by agneevX** [comment]
> @agneevX Is there any option? i couldn't find


```text
  --no-check-update                  Don't check for updates.
```
