### ISSUE TITLE
Client-specific filters

### ISSUE THREAD

**Issue by hexclann** [AdguardTeam/AdGuardHome#4334]
### Problem Description
In current version of Adguard, there is no way to have client-specific filters which means whatever the ad-filters you add to the adguard will be applicable to all the clients using Adguard DNS. Device or client specific filter feature has many advantages including easy parental controls, block unnecessary requests from a particular smart home device, filters based on OS or use cases. 

This feature is even helpful to host file maintainers to identify potential bad domains or false-positives or beta testing filterlists by isolating the problem to only one device without affecting other devices on the network. Overall this features gives a fine-grained control over all the devices on the network.

### Proposed Solution
Since there is already a feature to give names or assign IP address to connected devices using DHCP and DNS over HTTPS can have client name at the end of the URL, a group management can be introduced to manage client specific filters. 

### Alternatives Considered
Pi-hole

**Comment by EugeneOne1** [comment]
@hexclann, if I got you correctly, you can actually set the client-specific filtering, see the [wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#perclientblocking).  Did it help?

**Comment by demifiend9** [comment]
> @hexclann, if I got your request correctly, you can actually set the client-specific filtering, see the [wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#perclientblocking). Did it help?

I think he means a feature where you can specify which blocklists to apply per a client or client group.
For example, I want my own PC and phone to use a very aggressive blocklist, but have the rest of the house use safer blocklists.
Pi-hole can do this.

The client-specific filtering you linked looks too cumbersome and unrealistic to deploy for this scenario.

**Comment by gitthangbaby** [comment]
You can't manage blocklist per client. You can only manage domain per client, so to whitelist a blocklist you need to parse all domains and add it to rules. Or turn off ALL blocklists per client, which is not useful.

Needless to say, this is the nr.1 missing feature in 2018+.
