### ISSUE TITLE
Private edns-client-subnet

### ISSUE THREAD

**Issue by Matchlighter** [AdguardTeam/AdGuardHome#4341]
### Problem Description
My local DNS setup is a bit complicated. I run Adguard as my first DNS server, which then forwards requests for my domain to a PowerDNS system. All other queries go to Quad9. I'd like to be able to get ECS information (down to, if possible, the /32 subnet of the querying client) from Adguard DNS in PowerDNS.

I set the `Enable EDNS client subnet` option in AdGuard and was surprised that nothing was happening. I starting digging into why, and found https://github.com/AdguardTeam/dnsproxy/blob/85d124d1b4d1529c7dd2c6df55b90e516b15bafd/proxy/proxy.go#L528 that that'll only add the ECS data _if_ the originating IP is a public one.

### Proposed Solution
Add an option to enable adding of ECS data to local queries _per_ Upstream.

### Alternatives Considered
The "per Upstream" bit seems like it would make things a bit complicated, so I've also considered making AdGuard the secondary DNS behind `dnsdist` (part of the PowerDNS system) (So queries go to `dnsdist` then AdGuard instead of to AdGuard and then (if my domain) to `dnsdist`). This should work fine, but will create 2 points of failure for general DNS resolution (dnsdist and AdGuard instead of just AdGuard), but this is acceptable to me. However, it does have the problem that AdGuard will then see all queries as coming from one IP instead of the actual client IP. So this would want a change in AdGuardHome, making it consult the ECS data when 1) determining client-specific settings and 2) logging queries.

**Comment by agneevX** [comment]
This will probably get marked as a duplicate since there's already open issues on this.

**Comment by Matchlighter** [comment]
Fair enough - I agree that (eg) https://github.com/AdguardTeam/AdGuardHome/issues/2514 does cover my Alternatives Considered. As noted, it's not the ideal solution with the extra Point-of-Failure, (hence creating this issue), but it will certainly be effective and will solve my use case.

**Comment by Birbber** [comment]
Closing this issue as a duplicate.
