### ISSUE TITLE
Filters' rules get emptied upon reboot

### ISSUE THREAD

**Issue by trhdon123** [AdguardTeam/AdGuardHome#436]
### Steps to reproduce

1. Set AGH to launch on startup by adding `@reboot ~/.adguardhome/AdGuardHome` to crontab (`sudo crontab -e`)
2. Reboot
3. Launch AGH dashboard in browser. Open **Filters** tab

### Expected behavior

Fetched rules from filters host should remain.
### Actual behavior

Fetched rules get emptied. Rules count is 0. Try testing some sites and nothing got blocked (obviously).

<details><summary>Screenshot:</summary>
Before reboot

![screenshot from 2018-10-26 20-07-55](https://user-images.githubusercontent.com/20873969/47568750-1eb1fd80-d95c-11e8-8a3b-1ce274ad04fb.png)

After reboot
![screenshot from 2018-10-26 20-12-19](https://user-images.githubusercontent.com/20873969/47568604-c24ede00-d95b-11e8-84f0-8de80b00dc3b.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.9hotfix
| How did you setup DNS configuration:| default
| If it's a router or IoT, please write device model:| none
| Operating system and version:| Elementary OS 5.0 (Ubuntu 18.04 based)

**Comment by dfmcvn** [comment]
Maybe try delaying the cron:
`@reboot ; sleep 60 ; ~/.adguardhome/AdGuardHome`

**Comment by dfmcvn** [comment]
Don't forget to update the latest version, maybe the error already fixed in newer version.

```
git pull
make
pkill AdGuardHome
pkill coredns
cd ~/.adguardhome/
./AdGuardHome
```
