### ISSUE TITLE
DNS rewrites not applied

### ISSUE THREAD

**Issue by rgoy** [AdguardTeam/AdGuardHome#4361]
### Issue Details

* **Version of AdGuard Home server:**
  v0.107.5
* **How did you install AdGuard Home:**
  Automated install script
* **How did you setup DNS configuration:**
  Raspberry Pi running AdGuard which serves as DHCP and DNS servers
* **If it's a router or IoT, please write device model:**
  Raspberry Pi 3 Model B
* **CPU architecture:**
  ARM
* **Operating system and version:**
  Raspberrian 5.10 (bullseye)

### Expected Behavior
Expecting any query to resolve *.corp.home.lan to be resolved to nas.home.lan

### Actual Behavior
AdGuard responds NXDOMAIN to any single request made to *.corp.home.lan while it shows as the rule being applied in the "Check filtering" box

### Screenshots

![Screen Shot 2022-03-04 at 1 08 06 PM](https://user-images.githubusercontent.com/24394257/156819831-ccf8714d-15ce-4f91-802f-7d30353ea410.png)
![Screen Shot 2022-03-04 at 1 12 37 PM](https://user-images.githubusercontent.com/24394257/156819833-fb6648bc-5f9e-4401-89f4-6534923b6c80.png)

### Additional Information

As read in previous issues, I do have the box "Block domains using filters and hosts files”  checked.
I tried to few variations without success:
- corp.home.lan => nas.home.lan
- corp.home.lan => 192.168.1.27
- Tried to use a custom filtering rule

Any ideas of what could be causing this? Thank you!

**Comment by EugeneOne1** [comment]
@rgoy, hello.  What have you got in the `local_domain_name` field of `dhcp` section in the configuration?  Note that empty value leads to using `lan` as local TLD that may cause the issue.

**Comment by rgoy** [comment]
Hi @EugeneOne1 , I have  `local_domain_name: home.lan`

**Comment by rgoy** [comment]
Hi, just following up on this issue. Thanks!

**Comment by Birbber** [comment]
@rgoy Hi. Sorry for the long silence! Is this issue still reproducible on the latest release?

**Comment by rgoy** [comment]
Hey @Birbber,

Thanks for following up. I am no longer using AdGuard's DHCP server due to some instability I have experienced but the latest version or not using the built-in DHCP seem to have corrected the issue I was experiencing with DNS Rewrite.
