### ISSUE TITLE
New version on freebsd repository

### ISSUE THREAD

**Issue by leandroscardua** [AdguardTeam/AdGuardHome#4365]
Hello AdguardTeam,

Any plan to update the freebsd version on freshports?
The current version is  0.107.0.b.7.

Reference:  0.107.0.b.7 (https://www.freshports.org/www/adguardhome/)

**Comment by mdawsonuk** [comment]
The maintainer for this FreeBSD package is listed as [yuri@FreeBSD.org](mailto:yuri@FreeBSD.org?subject=FreeBSD%20Port:%20www/adguardhome) - maybe try emailing them?

**Comment by leandroscardua** [comment]
HI @mdawsonuk ,

Thank you for your reply,

I already did it a few weeks ago.

**Comment by mdawsonuk** [comment]
> HI @mdawsonuk ,
> 
> 
> 
> Thank you for your reply,
> 
> 
> 
> I already did it a few weeks ago.

Hopefully there's some progress made! 🙂

**Comment by leandroscardua** [comment]
I hope too.
