### ISSUE TITLE
Adding dark mode for AdGuard.

### ISSUE THREAD

**Issue by HarryDotMYx** [AdguardTeam/AdGuardHome#4370]
Hi, This is just my suggestion to put dark mode AdGuard. Hopefully this proposal is accepted by the community. Thank you.

**Comment by fernvenue** [comment]
> Well, the UI is not our top priority at the moment, but we'll take this feature request into account once we start working on the final design. -- https://github.com/AdguardTeam/AdGuardHome/issues/613#issuecomment-469146714.

I think you should check first if someone has suggested.

**Comment by EugeneOne1** [comment]
@HarryDotMYx, hello.  As @fernvenue correctly noticed, this is a duplicate of #613.
