### ISSUE TITLE
Version:  v0.108.0-b.4 Opnsense Plugin -  no default upstreams specified | 400

### ISSUE THREAD

**Issue by pugs686** [AdguardTeam/AdGuardHome#4378]
Prerequisites
Please answer the following questions for yourself before submitting an issue. YOU MAY DELETE THE PREREQUISITES SECTION.

 I am running the latest version
 I checked the documentation and found no answer
 I checked to make sure that this issue has not already been filed
Issue Details
Error: control/dns_config | validating private upstream servers: no default upstreams specified | 400

Version of AdGuard Home server:
v0.108.0-b.4
How did you install AdGuard Home:
Opnsense plugin mimugmail 1.6_1
How did you setup DNS configuration:
Adguard, Unbound, DNSCrypt Proxy
If it's a router or IoT, please write device model:
Protectli 4
CPU architecture:
ARM64
Operating system and version:
Opnsense 21.7.5
Except Behavior
Should be able to add DNS without error saying that no default DNS has been set

Actual Behavior
Unable to save or update ANY DNS settings

More Info:

Adguard Home plugin for Opnsense.

On update to   v0.108.0-b.4 no longer able to change DNS settings as there has been an introduced error:

Version: 
v0.108.0-b.4

"**_Error: control/dns_config | validating private upstream servers: no default upstreams specified | 400_**"

Changing as per documentation to specifying a default upstream with  character #  ,does not work/ignored

Upstream DNS Servers
127.0.0.1:5335

Private reverse dns servers
[/local.domain.in-addr.arpa/]127.0.0.1:5335
[/10.1.in-addr.arpa/]127.0.0.1:5335

Both tick boxes selected (use private reverse.... and enable reverse resolving....)

Where Adguard is on Port 53
Where Unbound is on Port 5335 and used to resolve internal addresses and external forwarding to 5300
Where DNSCryptProxy is used on Port 5300 for external DNS Servers
And....
Opnsense - System - Settings -General
      Untick: Do not use the local DNS service as a nameserver for this system
      Untick: Allow DNS server list to be overridden by DHCP/PPP on WAN

Tried Using:

  Upstream DNS Servers
  [/in-addr.arpa/]127.0.0.1:5335

And in Private reverse DNS servers
  [/10.1.in-addr.arpa/]127.0.0.1:5335

Or any other combination with '#' default (as per https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams) results with the same error

Whatever changed has resulted the code to look for a default I assume however # does not work when using this plugin I dont think.

Possibly related to
https://github.com/AdguardTeam/AdGuardHome/issues/4292
Or
https://github.com/AdguardTeam/AdGuardHome/issues/3381

???

Where I have tried to reconfigure as per that topic but still the error

**Comment by MeganerdNL** [comment]
Is this solved? I have the same issue. Extremely annoying.

**Comment by maidmeow4** [comment]
Same issue.

**Comment by warrickbayman** [comment]
Hi. Version v0.107.19 still seems to have the same issue.

**Comment by dayt47** [comment]
I got the same error. Didn't had a problem with adguard home Home assistant addon. Tried to use this one "[/168.192.in-addr.arpa/]192.168.1.1"

**Comment by shehzman** [comment]
Running into this issue as well with the plugin. v0.107.40
