### ISSUE TITLE
Feature Request - MAC address to 'Friendly name' mapping table

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#438]
Looking at IP addresses in the Top Clients table and Query Log means I still have to **know** what device has that IP address to take an action, or at least understand the correlation.

This request is to include a MAC Adress to 'friendly name' mapping table so that in the above scenarios, instead of showing an IP address, if a friendly name exists in the mapping table, then it will show the user-defined friendly name associated with the IP address.

This could initially be a simple manually editable txt or xml file but ultimately should be included in the UI so that users can see the devices already known by AGH and assign a friendly name to them, as well as add MAC address and friendly name for new/unknown devices.

**Comment by jtenniswood** [comment]
Totally agree with this need, I have been using pihole in docker, using --add-host="devicename.10:192.168.x.x", but this system doesn't seem to use the host file to map ip's to names, which is a real shame, as it limits the usability of the information coming back.

**Comment by ameshkov** [comment]
First of all, we need to figure out the MAC address corresponding to the IP address.

There are several options.

1. Automatic: in case if AG Home operates as a DHCP server (#423), this is quite easy;
2. Automatic: inspecting ARP cache (`arp -a`);
3. Manual: Allow configuring mapping in the UI;

Second, we need to have a separate settings screen specifically for inspecting known clients & editing their properties.

**Comment by jtenniswood** [comment]
As a quick win, it would be great if the system could use the hostnames to give IP's usable names.
That's enough for me.

**Comment by ameshkov** [comment]
Added hostnames to the list of options, thank you!

**Comment by AnthonyBe** [comment]
Given the number of DHCP IP devices on my network, I really would prefer not to rely on hostname mapping which is why my initial req was MAC-to-IP. While most of my devices likely retain the same IP allocated by my DHCP server, I do have some devices that are less frequently on my network and thus could be allocated a different IP address from time to time.

I'm reluctant to use DHCP capability in AGH unless it is full-featured. E.g. I don't even use my router's built-in DHCP server because it only lets you assign the most basic features, IP and gateway, so I use the DHCP Server on a Windows Server 2012 R2 box.

Inspecting ARP cache would be perfectly fine for me.

**Comment by ameshkov** [comment]
@AnthonyBe we're going to implement all 4 options, not just one of them.

**Comment by AnthonyBe** [comment]
Thanks @ameshkov , glad to hear that. I wasn't sure if it was going to be a staggered implementation or not so I just wanted to provide perspective from a keen user! :)

**Comment by rashidjehangir** [comment]
Hi Guys, any progress on this? It is very difficult to figure out IP addresses of multiple devices. @ameshkov

**Comment by DooMl** [comment]
@rashidjehangir it will be released with the version 0.92 ( https://github.com/AdguardTeam/AdGuardHome/milestone/4 ), and it's close assuming by the replies on each issue although there is still no ETA.

**Comment by rashidjehangir** [comment]
> @rashidjehangir it will be released with the version 0.92 ( https://github.com/AdguardTeam/AdGuardHome/milestone/4 ), and it's close assuming by the replies on each issue although there is still no ETA.

Thanks - will be a really user friendly feature. Right now its a nightmare to reference IP's

**Comment by ameshkov** [comment]
Guys, no ETA on this yet. I've preliminarily assigned it to milestone 0.93 to emphasize that improving this part of AG Home is one of the most important feature requests, but most likely I'll divide it into several tasks or even create a new milestone dedicated to "Client management". You see, it's not just about assigning names. In the future, AGH should let you have different (to some extent) client-specific configurations.

**Comment by ameshkov** [comment]
First part of this issue will be ready in v0.94 -- using hosts files: #637 

But that's not the end, we'll extend it later in v0.95.

**Comment by rashidjehangir** [comment]
Hi Guys, I have added the IP addresses but Adguard Homes says - The system cannot find the file specified. Is there a format that I am entering wrong? I have used a space after the IP Address - for example 192.168.1.1 MyPC

**Comment by ameshkov** [comment]
@rashidjehangir could you please explain where exactly have you added them? Is it the local hosts file?

**Comment by rashidjehangir** [comment]
Yes- local hosts file as per the instructions

**Comment by ameshkov** [comment]
Have you restarted AGH after doing that?

> The system cannot find the file specified

Where does this error come from? Can you please share the AGH log?

**Comment by rashidjehangir** [comment]
Sure. Pardon my ignorance but how do I share the log?

**Comment by rashidjehangir** [comment]
Yes. I have restarted. Now the error is not showing up but still cant see the friendly names

**Comment by ameshkov** [comment]
@rashidjehangir you know, there's a more simple solution, open `http://AGH_ADDRESS/control/clients` URL and check if your IP address is listed there

**Comment by rashidjehangir** [comment]
@ameshkov tried - says "site cant be reached" in browser

**Comment by ameshkov** [comment]
@rashidjehangir check that you didn't forget the port

**Comment by rashidjehangir** [comment]
@ameshkov did it - can see the Adguard interface but its blank

**Comment by ameshkov** [comment]
@rashidjehangir what OS are you on? What's the exact path to the hosts file?

**Comment by rashidjehangir** [comment]
@ameshkov Using Windows 10 - path is C:\Windows\System32\drivers\etc

**Comment by ameshkov** [comment]
@rashidjehangir got it, thank you! Is it 32-bit or 64-bit Windows?

@szolin could you please check it on a Windows machine?

**Comment by rashidjehangir** [comment]
@ameshkov 64-bit Windows. Another question - do I use a space or a TAB between IP Address and friendly name? I have tried both unsuccessfully.

**Comment by ameshkov** [comment]
> Another question - do I use a space or a TAB between IP Address and friendly name?

Both are okay, It shouldn't matter

**Comment by Orava2** [comment]
IP -> MAC address -> Vendor name, would be enough for me.  This is what many routers do. 
In Windows:
https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-sendarp
http://standards-oui.ieee.org/oui.txt

Network view tab would be handy. Like in Fing app.

**Comment by szolin** [comment]
> 1. Automatic: in case if AG Home operates as a DHCP server (#423), this is quite easy;
> 2. Automatic: inspecting ARP cache (`arp -a`);
> 3. Semi-automatic: using hostnames
> 4. Manual: Allow configuring mapping in the UI;
> 
> Second, we need to have a separate settings screen specifically for inspecting known clients & editing their properties.

p.1, p.4 are done: we can set name for a specific MAC in UI and we translate MAC to IP, IP to name when our DHCP server is running.
p.2 & p.3 are still to be considered.

**Comment by AnthonyBe** [comment]
So I basically have to use AGH DHCP server. Not happy with that to be honest.

**Comment by ameshkov** [comment]
That's why we're not closing this issue yet:)

**Comment by ameshkov** [comment]
> 2. Automatic: inspecting ARP cache (arp -a);

Done: #826

**Comment by siewers** [comment]
Sorry for necroposting, but as far as I understand, this issue was about using the possiblity to have AdGuard Home translate MAC addresses into friendly names and not requiring the use of the AdGuard Home DHCP server.
I can't seem to get that to work, and the wiki also states that in order to resolve a client by MAC, you have to use the DHCP server, which is not possible in my case (using an AmplifyHD router).
