### ISSUE TITLE
Upstream test to local unbound server failed

### ISSUE THREAD

**Issue by sowilo-be** [AdguardTeam/AdGuardHome#4380]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.5
* **How did you install AdGuard Home:**
Instance 1: mimugmail plugin // instance 2: Official script installer for Linux
* **How did you setup DNS configuration:**
Local network recursive DNS resolving via Unbound
* **If it's a router or IoT, please write device model:**
Instance 1 = Intel J4125 based Firewall box // Instance 2 = Raspberry Pi 4B 
* **CPU architecture:**
Instance 1 = AMD64 // Instance 2 = ARM64
* **Operating system and version:**
Instance 1 = OPNsense 22.1.2_1-amd64 // Instance 2 = Rasbian [Latest - Debian 11]

### Expected Behavior
Working upstream servers from both instances on both devices

### Actual Behavior
Both upstream servers work on instance 2 (Raspberry), but on instance 1 only the unbound instance on the same device works.

### Screenshots

<details><summary>Screenshot:</summary>

![11](https://user-images.githubusercontent.com/80890169/157503690-a6bd4a89-63b5-4b34-8c34-d7225fcc2548.png)

![22](https://user-images.githubusercontent.com/80890169/157504180-7b27b43e-c3cd-4d22-beae-14fb08024e4e.png)

![33](https://user-images.githubusercontent.com/80890169/157504186-ea1d43af-4f80-49e5-8d99-1fe1550da4ef.png)

</details>

### Additional Information

Hello, I'm running two instances of Adguard Home. Instance number one cannot use upstream server 10.100.30.30:5533.
Although I can reach this server via that port with the PowerShell command: Test-NetConnection -p 5335 10.100.30.30.
Also via the Opnsense box I can ping and do a probe port test to instance 2 on port 5533.

Both instances work with recursive DNS resolvement, BUT I want to add 10.100.30.30:5533 to instance one as a fallback upstream DNS. But it keeps giving the error: Server "10.100.30.30:5533": could not be used, please check that you've written it correctly.
Only my Raspberry Pi can use both upstream servers, but the other way around it keeps failing.

-----

1:
- Opnsense Firewall Service (mimugmail repo) with upstream to Unbound recursive DNS resolver, using port 5335.
- Platform is AMD64, intel based system. Opnsense is based on FreeBSD
- IP = 10.100.30.1
- Upstream is 127.0.0.1:5335

2:
- Raspberry Pi 4B. Adguard installed via official automated script and Unbound via apt install unbound, port set to 5533
- Platform ARM64, Debian 11
- IP = 10.100.30.30
- Upstreams are 127.0.0.1:5533 and 10.100.30.1:5335 (=Instance 1 on Opnsense)

**Comment by fernvenue** [comment]
Please confirm whether your upstream can correctly respond to DNS requests, AdGuardHome will send a test request to the upstream and use the upstream response as a criterion to determine whether the upstream is available. It might be a good idea to check Unbound's logs for requests from AdGuardHome.

**Comment by sowilo-be** [comment]
Hi @fernvenue 

Both plain DNS and DNSSEC are working

-----------------

_Raspberry Pi**:~ $ dig github.com @127.0.0.1 -p 5533**_

; <<>> DiG 9.16.22-Debian <<>> github.com @127.0.0.1 -p 5533
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64250
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             285     IN      A       140.82.121.4

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5533(127.0.0.1)
;; WHEN: Fri Mar 11 14:56:22 CET 2022
;; MSG SIZE  rcvd: 55

_Raspberry Pi **:~ $ dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5533**_

; <<>> DiG 9.16.22-Debian <<>> sigfail.verteiltesysteme.net @127.0.0.1 -p 5533
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 41709
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;sigfail.verteiltesysteme.net.  IN      A

;; Query time: 283 msec
;; SERVER: 127.0.0.1#5533(127.0.0.1)
;; WHEN: Fri Mar 11 14:56:40 CET 2022
;; MSG SIZE  rcvd: 57

---------------

I added loggin to Unbound, checked config and restarted the service right now:

![11](https://user-images.githubusercontent.com/80890169/157883707-749ca2e2-ec61-4801-a699-f6efead4fe3d.png)

And I set the upstream DNS to 127.0.0.1:5533 which is the Unbound server on the raspberry pi. It works fine.
But on the other host, the Opnsense machine, this Adguard instance gives again the same error.

![22](https://user-images.githubusercontent.com/80890169/157884979-cf198b58-9cb2-4d8f-8d9f-886d8dec0cbd.png)

Although the traffic happens on the same VLAN, like I said, I can reach the IP and port in both directions.
I start to fear that it is some weird AM64 and ARM64 combination issue.

But I don't hope so

**Comment by fernvenue** [comment]
I noticed that you are testing on the DNS server directly, I suggest you to test on instance one via 10.100.30.30:5533 so we can verify if there is any problem with the connection of the two devices.

**Comment by sowilo-be** [comment]
Alright, you're helping me think straight. Learning a few things today.
So I tried to DIG from Opnsense to the Raspberry Pi and this did gave me an error.

Resolving to the local unbound on 10.100.30.1 works fine:

![11](https://user-images.githubusercontent.com/80890169/157895186-00997fa2-4973-4d0f-898f-3e30afc6fbe0.png)

Trying to resolve from 10.100.30.30 doesn't work

![22](https://user-images.githubusercontent.com/80890169/157895215-28e5122b-ecb9-480c-864d-eefa3fec1949.png)

Mmmh weird since this is in my INFRA VLAN, there are not many restrictions in-between devices. Like I said, IP and port 5533 can be reached from Opnsense. So Firewall and rule based all should be good.

So from Opnsense I cannot resolve via the Raspberry Pi. But local resolving on the pis works.

Any ideas what direction I should try to look? 
Your help is highly appreciated so far :-)

**Comment by fernvenue** [comment]
I think there is a high possibility that your Unbound is only listening on 127.0.0.1 and not successfully listening on 10.100.30.30. You can check the port usage of 10.100.30.30:5533 on instance two, or test upstream using its own 10.100.30.30:5533 instead of 127.0.0.1:5533.

**Comment by sowilo-be** [comment]
The upstream 10.100.30.30:5533 does not respond indeed, only on loopback address and port 5533. Although strange, I already tried to set the unbound.conf interface to 0.0.0.0, 10.100.30.30 and before 127.0.0.1. Than I restart the service but it doesn't change the situation.

sudo netstat -tulpn | grep :5533

And it does show it is listening on the interface I configured. There is also no UFW or anything configured on the host which might prevent some things.

**Comment by sowilo-be** [comment]
Okay I finally managed to solve it after some information I found here:

https://nlnetlabs.nl/documentation/unbound/unbound.conf/

So all was configured correctly. Just there has to be some kind of access control coming from unbound.

I added the bellow comment and configuration value to unbound.conf

# Access control list
access-control: 10.0.0.0/8 allow

What a relief to have found it. Before I just used Unbound and Adguard as local services on my Opnsense box. It was easy to setup Adguard on a remote host with a public resolver. But I wanted recursive to control my data more. So I'm very happy now. Thanks again, I learned a lot during the process.

**Comment by fernvenue** [comment]
Glad to help, and I think this will be a reference for others with similar issues.
