### ISSUE TITLE
query log search doesn't indicate no results

### ISSUE THREAD

**Issue by elandorr** [AdguardTeam/AdGuardHome#4381]
### Issue Details

* **Version of AdGuard Home server:**
v0.107.5
* **How did you install AdGuard Home:**
irrelevant
* **How did you setup DNS configuration:**
irrelevant
* **If it's a router or IoT, please write device model:**
irrelevant
* **CPU architecture:**
irrelevant
* **Operating system and version:**
irrelevant

### Expected Behavior
show results, even if the result is none

### Actual Behavior
spinning wheel of death

### Additional Information

If you search for something that doesn't exist, there's no indication the search will ever finish. The spinning wheel of death keeps rolling happily ever after.

**Comment by ainar-g** [comment]
Good day.  I cannot reproduce this.  I get “Nothing found”, see the screenshot.  Please fill the whole issue template.

![Screenshot from 2022-03-10 16-18-19](https://user-images.githubusercontent.com/4964986/157670039-1fb5ed10-4d6e-4910-9c30-a8a9df4e93a8.png)

**Comment by elandorr** [comment]
The issue template is pointless for this - I wrote which version, the rest is irrelevant, always the same.

![image](https://user-images.githubusercontent.com/56206745/157687029-b8ed0959-f537-426e-b5bd-c6c5f72da2be.png)

Adguard logs show nothing, browser console is fine. Firefox complains because FF takes some things more seriously than Chrome, but nothing related to this. ("was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type." and an inconsequential CSS warning)
Browser choice makes no difference, restarting makes no difference.

If there is yet another log I could enable I'd help you.

**Comment by Toudahl** [comment]
I just tested on 0.107.5 - using my phone.
I have no issue on Firefox for android, I get the "nothing found" message.

**Comment by elandorr** [comment]
It's always been like this for us throughout the updates, so I thought that's just how it was. Figured I'd post on gh eventually.

No idea how to debug this even, without knowing the code. The network console spams an infinite loop with no errors. I checked an individual request too - totally fine, but infinite. 

Just a minor issue, but a bit odd.

**Comment by Toudahl** [comment]
So it seems the question is. Why is there a difference.
@elandorr you must describe how to reproduce the error.
Environment, installation steps, settings etc.

Because right now, with the info you gave it seems it is a problem local to you

**Comment by elandorr** [comment]
@Toudahl I already said this is irrelevant. It happens across several installations, different systems. The only thing they have in common is that it's adguard, and well, x64. 

And again, it's not a 'local' issue, there aren't any errors, it's not related to browsers, everything is a-okay. Tell me how to coax a more detailed log out of adguard without dumping private data and I'll provide one.

**Comment by Toudahl** [comment]
It seems no one else has this problem, and no one else can reproduce it. So it's local to you.

You refuse to provide the information that people need to have a chance at helping you. Good luck.

**Comment by elandorr** [comment]
With this attitude I'm not going to help you. I couldn't personally care less about it - I thought you'd appreciate a minor bug report.

The majority of people never use the search, so obviously there won't be any reports. Common sense. Even fewer people exist who care enough about adguard home to use github.
Several users who I've recommended adguard home to notified me of this, they simply don't bother with more than a brief mention. Who would? I had github open and figured I might help you out.

And you must learn how to read: The info you seek has been written twice already, and a bit of logic does the rest:

>The only thing they have in common is that it's adguard, and well, x64

Or do I need to make it any clearer for Mr. Attitude?

>Version of AdGuard Home server:
v0.107.5

From the initial post. But I also said it's happened in previous versions, therefore not being related to any specific version, either. Common sense would dictate it's not something ancient, but the number was given in the original post anyway.

What can we learn from this? What is statistically significant? We can conclude this happens with the given, latest, version, on at least Windows and Linux, which the overwhelming majority of users are based on, therefore not being platform dependent, nor on the setup. It wouldn't matter which platforms anyway, as long as they're separate ones, indicating it's universal.

What is the logical course of action? Detailed logs. Ideally without dumping the entire process which may include private data. It's probably just something tiny that few ever noticed because it's so inconsequential.

But you can do that on your own now. I'm out.

**Comment by Toudahl** [comment]
@elandorr
you are hilarious. I'm just a random user like you. Your arrogant approach is not helping you. I have been using agh for 3 years and never had the problem you describe.

Im not doubting that the problem exists. But when you won't give any details, what do you expect people to do?
Your "clues" are pointless. I have used multiple versions of adguard over the years all of them x64.

This is basically the conversion:
Person1: I have an issue.
Person2: Oh damn, can you explain the details so I can help you?
Person1: No.

**Comment by elandorr** [comment]
Apparently unsubscribing doesn't stop github from sending mails on mentions, so please refrain from that.

The details have been laid out several times already.

- Latest version + many previous
Ergo, it's not a regression.
- Mixed Windows, Linux platforms, logically anything that still exists today and not 98, limiting you to Win 7,10 gens and the usual popular suspects like Ubuntu.
Ergo, not platform dependent, specifying kernel 5.10.0 is completely irrelevant and not useful.
- Mentioning x64 was a joke, 32 is obviously less than significant, the other options even more so.
Arch obviously wouldn't have anything to do with this anyway.
- Browsers have been tested and available logs given (i..e, none available, save for exactly what I copy pasted earlier, warnings about unrelated CSS properties, mimetype). Both latest FF/Chrome, covering more than 90% of marketshare by a long shot.
This would be most apt to ask for, and has been given.
No need to expect Netscape build 1984 compiled during solstice.

Who would ever even expect a simple tool like adguard home to magically have a minor bug like this in the BSD version from 3.5months ago rev-c that 5 people use at 3 in the morning specifically, but only on a Pentium III?
The only helpful measure are logs, and I offered my free time for providing them as needed.

The bug, if you still can't see it, is that search doesn't indicate that no results have been found, triggering an infinite loop instead.

I'm sorry you cannot see why your attitude is aggravating. If someone offers to provide logs in his free time you say thanks and are grateful for it. Enough senseless bureaucrats away from the screens already.

**Comment by agneevX** [comment]
@elandorr are you using a reverse proxy by any chance?
