### ISSUE TITLE
option to add upstream server per list

### ISSUE THREAD

**Issue by averon420** [AdguardTeam/AdGuardHome#4385]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description
I want to use LanCache in cooperation with my Adguard server, but I don't want to lose the statistic, therefor I can't add the AGH as an upstream server for the LanCache. I'd like to use a script to generate a list of all the domains that need to be forwarded to the LanCache server. The issue is, when I added an upstream rule like [/domain.example/]LanCacheIP to either the blacklist or the whitelist it didn't work.

### Proposed Solution
if I could add a list with upstream rules via either blocklist or whitelist, that would solve my issue.

### Alternatives Considered
a folder with dnsmaqs rules imported automaticaly on change 

Thanks!

**Comment by fernvenue** [comment]
AdGuardHome already support [Loading Upstream From File](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file), please follow that wiki and edit `upstream_dns_file` in your `AdGuardHome.yaml` to use it, that will solve your problem.. And just like we discussing in https://github.com/AdguardTeam/AdGuardHome/issues/4316, AdGuardHome will add an option to auto-update the upstream list in [v0.109.0](https://github.com/AdguardTeam/AdGuardHome/milestone/29).
