### ISSUE TITLE
Added "DNS Block List" import and export function

### ISSUE THREAD

**Issue by garywu520** [AdguardTeam/AdGuardHome#4392]
I have it enabled on different workstations, but configuring the "DNS Block List" is too tedious and I would like to be able to export/import the configuration quickly. thanks

**Comment by agneevX** [comment]
Lists aren't something that you change frequently, The `AdGuardHome.yaml` file contains the lists.

**Comment by Clems92** [comment]
Good to know if you need to duplicate installation on several machines! 
thanks.

**Comment by ainar-g** [comment]
Additionally, see #1147 and #573.
