### ISSUE TITLE
Add Traffic Destination Map to Dashboard

### ISSUE THREAD

**Issue by fpellicciotti** [AdguardTeam/AdGuardHome#4398]
In the dashboard, it would be nice to see a "Destination map" of internet traffic that you have visited. Something similar to what NextDNS has.

![image](https://user-images.githubusercontent.com/12274971/158393139-c9d5f7ca-aefe-4fe1-b5de-dfd78e208641.png)

**Comment by agneevX** [comment]
Duplicate of #1605.

**Comment by Birbber** [comment]
Closing as a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1605.
