### ISSUE TITLE
specifiy port for local Upstream DNS

### ISSUE THREAD

**Issue by exxus** [AdguardTeam/AdGuardHome#4402]
Thank you for this nice and easy to use Ad-blocker.

When switching prom pi-hole I came across this issue.
I am using a local my DNS server on the same device as AdGuardHome.
I can't add my local DNS Server to upstream DNS servers, since it is listening to port 5300.
How can I specify the the port of the upstream DNS?
I tried:
127.0.0.1:5300
127.0.0.1#5300
127.0.0.1.5300

If it is not possible I want to add this as a feature request.
In Pi-hole it is possible with 127.0.0.1#5300

Best regards

**Comment by EugeneOne1** [comment]
@exxus, hello.  Have you tried `127.0.0.1:5300`?  AFAIK, it's the most common way to specify the port.  Thanks.

**Comment by exxus** [comment]
Yes, also not working.
192.168.1.4:5300

**Comment by EugeneOne1** [comment]
Is there any error message?  Or it simply drops the requests?  Note also, that PTR requests for [locally-served address registries](https://datatracker.ietf.org/doc/html/rfc6303) are handled by **Private reverse DNS servers**.

**Comment by exxus** [comment]
The message is:
Server "127.0.0.1:5300": could not be used, please check that you've written it correctly

**Comment by EugeneOne1** [comment]
Well, it's quite possible the listener of `127.0.0.1:5300` doesn't actually serves the DNS requests.  Could you please perform a request for some domain from the same machine with the `dig`/`nslookup` utility, e.g.:

```sh
dig @127.0.0.1 -p 5300 google.com
```
or
```sh
nslookup -port=5300 google.com 127.0.0.1
```

**Comment by exxus** [comment]
Thank you for the hints.
Here are the outputs:

```
dig @127.0.0.1 -p 5300 google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u6-Debian <<>> @127.0.0.1 -p 5300 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29431
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		2218	IN	A	173.194.74.102
google.com.		2218	IN	A	173.194.74.139
google.com.		2218	IN	A	173.194.74.138
google.com.		2218	IN	A	173.194.74.113
google.com.		2218	IN	A	173.194.74.101
google.com.		2218	IN	A	173.194.74.100

;; Query time: 2 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Wed Mar 16 13:13:02 UTC 2022
;; MSG SIZE  rcvd: 135
```

```
nslookup -port=5300 google.com 127.0.0.1
Server:		127.0.0.1
Address:	127.0.0.1#5300

Non-authoritative answer:
Name:	google.com
Address: 173.194.74.102
Name:	google.com
Address: 173.194.74.139
Name:	google.com
Address: 173.194.74.138
Name:	google.com
Address: 173.194.74.113
Name:	google.com
Address: 173.194.74.101
Name:	google.com
Address: 173.194.74.100
Name:	google.com
Address: 2607:f8b0:4001:c0d::64
Name:	google.com
Address: 2607:f8b0:4001:c0d::71
Name:	google.com
Address: 2607:f8b0:4001:c0d::8a
Name:	google.com
Address: 2607:f8b0:4001:c0d::66
```

**Comment by exxus** [comment]
Thank you very much for your help.
I will try to get the verbose log. I just want to mention one very important fact.
I am using AdGuardHome inside a Docker container. But the other DNS Server is not running inside a docker container.
So I think my mistake was using 127.0.0.1
But even using the address of my  device (in my case 192.168.1.4:5300) does not help.
But I get a different error message:
Error: control/test_upstream_dns | Network Error

So I guess my mistake is in somehow configuring my docker container wrong.
Thank you anyway.

**Comment by exxus** [comment]
ok, I was only listening to 127.0.0.1:5300, now I am also listening to the address from my local network 192.168.1.4:5300
and AdGuard works perfectly fine.
