### ISSUE TITLE
Adguard home could not use dns port 53 I had to use 5353 and now none of my devices are being reported

### ISSUE THREAD

**Issue by eserk** [AdguardTeam/AdGuardHome#4407]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  *  CURL command
* **How did you setup DNS configuration:**
  *  On my router, I pointed the dns to the pi
* **If it's a router or IoT, please write device model:**
  *   Raspberry pi 4 B
* **CPU architecture:**
  *  amd64
* **Operating system and version:**
  *   latest version of dietpi
  * 

### Expected Behavior

dns is using 5353 instead of 53 for the port
### Actual Behavior

My devices are not being listed in the queried results, but websites are being blocked
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by agneevX** [comment]
> Adguard home could not use dns port 53 I had to use 5353 and now none of my devices are being reported

If you set up your router to point to AGH, its likely to use port 53. 

Can you elaborate on why it "could not use" port 53? Do you have another daemon listening on that port and interface? 

Can you provide the output of  `sudo lsof -i -P -n | grep LISTEN | grep :53` ?

**Comment by eserk** [comment]
***@***.***:~$ sudo lsof -i -P -n | grep LISTEN | grep :53
AdGuardHo   401 adguardhome   15u  IPv6   11384      0t0  TCP *:53 (LISTEN)
unbound     420     unbound    4u  IPv4   11322      0t0  TCP 127.0.0.1:5335
(LISTEN)
AdGuardHo 12202        root   32u  IPv6 3921749      0t0  TCP *:5353
(LISTEN)

**Comment by agneevX** [comment]
What about `sudo lsof -i -P -n | grep AdGuard`?

**Comment by eserk** [comment]
***@***.***:~$ sudo lsof -i -P -n | grep AdGuard
AdGuardHo  4813 adguardhome   12u  IPv6  27068      0t0  TCP *:8083 (LISTEN)
AdGuardHo  4813 adguardhome   14u  IPv6  28114      0t0  UDP *:53
AdGuardHo  4813 adguardhome   15u  IPv6  28115      0t0  TCP *:53 (LISTEN)
***@***.***:~$

**Comment by agneevX** [comment]
AdGuard Home is in fact listening on port 53 UDP and TCP.

**Comment by agneevX** [comment]
But its IPv6 only, so I guess that is how you have your network configured?

**Comment by eserk** [comment]
It's not reporting my devices stats though

**Comment by agneevX** [comment]
A screenshot would help a lot.

**Comment by playday3008** [comment]
Looks like a have same problem, AdGuardHome only listen in ipv6, but not in ipv4

**Comment by agneevX** [comment]
Please check `bind_hosts` inside AdGuardHome.yaml.

**Comment by eserk** [comment]
Thanks, I'll check it out. Also my adguard screen says dns server starting,
but thats it, ill send pics soon

**Comment by Birbber** [comment]
@eserk Hi. Sorry for the long silence! Is this issue still relevant?

**Comment by Birbber** [comment]
Closing this one as completed. Feel free to re-open if needed.
