### ISSUE TITLE
How to optimize the experience in mainland China

### ISSUE THREAD

**Issue by jiayouba233** [AdguardTeam/AdGuardHome#4410]
According to [Blocky's test data](https://blocky.greatfire.org/), [AdGuard,](https://blocky.greatfire.org/detail/466103/https%3A%2F%2Fdns.adguard.com) [Cloudflare](https://blocky.greatfire.org/detail/466102/https%3A%2F%2Fdns.cloudflare.com)(except [IP with HTTPS](https://1.1.1.1/dns-query)) and [Google](https://blocky.greatfire.org/detail/265917/https%3A%2F%2Fdns.google.com)'s Doh / Dot server are blocked in mainland China(If sometimes these Doh/Dot servers can be used normally, it is only temporary), and if there is a privacy risk with no encrypted DNS servers and will be carried out by Fire Great Wall for DNS poisoning. Thanks to developers such as [V2Fly](https://github.com/v2fly) and [Trojan](https://github.com/trojan-gfw), these tools can make netizens in mainland China crossing the  [Great Fire Wall](https://en.wikipedia.org/wiki/Great_Firewall), and set the system agent to let the AdGuard Home take the proxy server for DNS requests, but there is a problem: Make DNS The requested IP address is the IP of the proxy server. At this time, the service that accesses China usually occurs slowly, but if you do not take the proxy server for DNS resolution, the domain name resolution will fail directly.

So there is a solution that makes users in mainland China can request DNS requests in the source IP?

**Comment by fernvenue** [comment]
Actually if you check the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#loading-upstreams-from-file) you can already solve this problem, you can use [felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) with AdGuardHome like [fernvenue/adguardhome-upstream](https://github.com/fernvenue/adguardhome-upstream) very simply. And it should be emphasized that these projects are **NOT** and **CANNOT** be used to help you break through any firewall, they are only used to get a better network experience.

I hope you can carefully check the existing materials, especially the official documents or wiki before asking questions, and I think this issue can probably be closed.

**Comment by jiayouba233** [comment]
I'm sorry for this issue, but thank you very much for your answer
