### ISSUE TITLE
v0.108.0-a.96+82505566 doesn't even start on linux docker and on windows?

### ISSUE THREAD

**Issue by flavorgold1** [AdguardTeam/AdGuardHome#4424]
Is anyone else having any issues with `v0.108.0-a.96+82505566`? Just want to confirm before I file a full-report. Thanks in advance.

**Comment by JohnFawkes** [comment]
yea im getting error spammed in logs
2022/03/24 13:54:02.196100 [info] AdGuard Home, version v0.108.0-a.96+82505566
2022/03/24 13:54:02.199181 [error] parsing configuration file: validating ports: duplicated values: [0]

**Comment by ainar-g** [comment]
@JohnFawkes, thank you for testing!

@flavorgold1, does the update fix the issue for you as well?

**Comment by flavorgold1** [comment]
> @JohnFawkes, thank you for testing!
> 
> @flavorgold1, does the update fix the issue for you as well?

Yes, `v0.108.0-a.97+3603b1fc` fixes this issue. Thank You.
