### ISSUE TITLE
Let us totally disable connection form

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdGuardHome#4426]
### Problem Description
I actually use a [secure SSO (single signon)](https://www.authelia.com/) linked with my nginx server, who support 2FA and once logged with authelia the connection append, but i have to reconnect with the Adguard form.

### Proposed Solution
Can you provide a way (in the yaml file) to actually disable the native authentication process for these kind of settings.

**Comment by fernvenue** [comment]
Agree, I use Cloudflare Access to connect to my local services, for AdGuardHome I also need an extra authentication.

**Comment by ainar-g** [comment]
Apologies for the long response time.  I've missed this issue somehow.

If you have an Nginx server in front of AdGuard Home, you could set the `Authorization` header using the `Basic` algorithm.

**Comment by fernvenue** [comment]
I'm sorry for the late reply today. Based on @ainar-g said above, I have configured the rewriting rules for the Request Header on Cloudflare, and it's working well. Now my AdGuardHome instance no longer requires additional verification and is fully authenticated through Cloudflare's Zero Trust, I hope this can provide ideas for others who have the same need.
