### ISSUE TITLE
Domains that begin with https cannot be blocked

### ISSUE THREAD

**Issue by cyouhi** [AdguardTeam/AdGuardHome#4427]
version: v0.107.5
system: debian11
For example https://us.l.qq.com/exapp
Adding this domain name to the Custom filtering rules cannot be intercepted

**Comment by EugeneOne1** [comment]
@cyouhi, hello.  `https://us.l.qq.com/exapp` is not a domain actually, the only `us.l.qq.com` part is.  If it worked?

**Comment by cyouhi** [comment]
If it does not come with (https://) it works
However, in the Query Log, this domain name is https://
![image](https://user-images.githubusercontent.com/33261078/160309960-e07584ec-105b-4317-96e3-e5e95c0a6055.png)

**Comment by EugeneOne1** [comment]
@cyouhi, well, these requests still aren't seem correct, we've also got a discussion (#3331) on the topic.  The way to block such queries is to use a regular expression, for example:

```
/https:\/\/us\.l\.qq\.com\/exapp/
```

**Comment by cyouhi** [comment]
Thanks, I tried to use it.
It works.
