### ISSUE TITLE
dns rewrite wait for upstream dns response when set to "ask for all upstream dns server, and choose the fast on"

### ISSUE THREAD

**Issue by 1349422030** [AdguardTeam/AdGuardHome#4433]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ *] I am running the latest version
- [ *] I checked the documentation and found no answer
- [ *] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.5
* **How did you install AdGuard Home:**
Built from source
* **How did you setup DNS configuration:**
 System
* **If it's a router or IoT, please write device model:**
PC
* **CPU architecture:**
 AMD64
* **Operating system and version:**
Windows 11

### Expected Behavior
if i set a dns rewrite, then adh should not ask the upstream dns server, but just tell me the key i set to.

### Actual Behavior
when i set to ask all dns server, and give the fastest one, on client will time out when query for it

### Screenshots
![image](https://user-images.githubusercontent.com/35253997/160255578-effc08dd-1d4b-4770-90e8-16ebcbc86bd6.png)

**Comment by fernvenue** [comment]
I rewrited the domain `t.cn` to `1.1.1.1` and using **Fastest IP address** mode:

```
~# nslookup t.cn 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   t.cn
Address: 1.1.1.1
```

Couldn't reproduce this issue in my tests, make sure to save your settings after making changes and provide more test data.

**Comment by 1349422030** [comment]
> 
Sorry, i can not reproduce this problem, so it will be closed. If i success reproduce, i think i will reopen it.
