### ISSUE TITLE
Statistics show for the wrong date after 00:00 UTC

### ISSUE THREAD

**Issue by chr-lei** [AdguardTeam/AdGuardHome#4434]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Issue Details

* **Version of AdGuard Home server:**
  * v0.108.0-b.5
* **How did you install AdGuard Home:**
  * official Docker image
* **How did you setup DNS configuration:**
  * Docker container running on router
* **If it's a router or IoT, please write device model:**
  * Unifi Dream Machine
* **CPU architecture:**
  * Arm64

### Expected Behavior
Statistics graphs show queries on the correct date, either using local time or UTC. I'd expect to see stats showing for 26 March until 00:00 local time, OR start to see queries after 20:00 local / 00:00 UTC show for 27 March, without affecting the date displayed for 26 March queries (see below).

### Actual Behavior
On a system in GMT-04:00 (America/New_York), after 00:00 UTC, the statistics for the current day are show under the previous day's date. For example in the screenshots below, the 25000+ queries were all logged on 26 March 2022 and the screenshot was taken at 20:55 local time / 00:55 UTC. The statistics were properly shown as 26 March until 00:00 UTC, at which point all queries (even those that were made after 00:00) are showing as 25 March. This will eventually straighten out after 00:00 local time / 04:00 UTC, but there is a 4-hour gap (which is the offset from UTC) where the stats are a bit weird; and the following day, the issue reoccurs in that 4-hour window between local 00:00 and 00:00 UTC. Interestingly, at 21:00 local, AGH seems to start a new 'day' of stats, but the wrong dates are displayed and the offset doesn't make sense (see screenshots for a bit of an explanation)

From what I can tell, the Docker container is using the correct time zone and has the correct time:
`/opt/adguardhome/work # date`
`Sat Mar 26 20:57:13 EDT 2022`

My browser time also appears to be passing through to the interface correctly as my query logs do show the correct date and time. Deleting and rebuilding the container from 0.108.0-b4 to -b5 did not seem to correct the issue.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="1384" alt="Screen Shot 2022-03-26 at 9 00 36 PM" src="https://user-images.githubusercontent.com/75548091/160262221-fbb74c1b-d9a8-44b3-b1e8-02cbe96b77c4.png">

Interestingly, at 21:00 local, queries started showing for 26 March again as if it was a new day but this should be 27 March. Plus, the offset makes no sense in this case:
<img width="1396" alt="Screen Shot 2022-03-26 at 9 07 12 PM" src="https://user-images.githubusercontent.com/75548091/160262368-3438d68f-bc97-4cde-9692-c93f6c09a581.png">

</details>

### Additional Information
~~I believe this is new behavior in the 0.108 betas. I don't recall seeing this issue in 0.107 or 0.106.~~
Confirmed that this occurs in v0.108.0-b5 and v0.107.3 - v0.107.5

**Comment by chr-lei** [comment]
A few other observations:
I deleted the stats db file last night and after a little while, it looked like the stats were logging on the correct date, even prior to 00:00 local. However this morning, all stats are showing as logged on 27 March even though some were clearly logged on 26 March. 

I also noticed that if I change the stats retention to 7 days, the graphs adjust and properly show query volume at the correct date and time. This sort of leads me to think that this is just a display issue with the 30 day retention graphs, and not an actual data issue. 

Happy to provide any additional info or test things for you - this is a weird one!

**Comment by chr-lei** [comment]
I will spin up an instance of v0.107.3 and report back after I get some statistics in place and tonight. Sorry for missing #4310 - I tried to not create a duplicate but overlooked that one!

Thank you.
________________________________

**Comment by chr-lei** [comment]
@EugeneOne1 -  I can confirm that this does also happen with v0.107.3. After the clock passed 20:00 local time, the March 29 stats showed zero, exactly as outlined above. Let me know if there's anything else I can test or info I can provide. Thank you.

**Comment by ainar-g** [comment]
@chr-lei, we have made some improvements to the statistics code in v0.107.10.  Could you please check if your issue has been fixed as well?

**Comment by chr-lei** [comment]
Just pulled .10 down tonight and it is looking good so far! Stats are set to 1 month and I’m seeing the proper number shown today, and it’s 21:39 right now. Nice work!
________________________________

**Comment by EugeneOne1** [comment]
@chr-lei, thanks for testing it.  We'll close the issue for now, but feel free to reopen it if the dates break again.
