### ISSUE TITLE
Groping of clients request count

### ISSUE THREAD

**Issue by ArielXfire** [AdguardTeam/AdGuardHome#4442]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Home network, several devices support 2.4GHz and 5GHz networks. Some spots in home are not covered by 5GHz WiFi signal and then devices switchover to 2.4GHz. Would be nice to have the possibility to see statistics based on a grouping and not split by device type/IP.
(PS: I have 1 router + 2 APs, it doesn't make sense to invest more into hardware; DHCP assigns IPs by MAC)
From picture below, rows highlighted in yellow should be added;

![image](https://user-images.githubusercontent.com/102585397/160573767-9f1cb69d-0fcf-445b-8f7d-39b3f24074bd.png)

**Comment by fernvenue** [comment]
> [AdGuardHome Wiki:](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#identifying-clients) CIDR range. For instance, 192.168.0.1/24. Allows attributing a whole range of IP addresses (in the example it is 192.168.0.*) to the same client. 

So clearly you can set all your devices in one tag by `192.168.10.0/24`, `192.168.10.*` or something like that.

**Comment by agneevX** [comment]
Is your router reporting those hostnames, with the band used appended in the end @ArielXfire?

**Comment by ArielXfire** [comment]
@fernvenue - thanks. I will look it it; At first it not an option that could suit me, as my IP range is 192.168.10.x only

@agneevX no.
on my TP-Link router I allocate IPs via DHCP to hosts based on MAC, for majority of devices in my network: (IoT/ Air Conditioning / laptops / etc.) and for guests it all DHCP pool. Since these guests stay maximum a couple of hours or 2-3 days they could not bring high traffic into statistics.

On the pi where Adguard resides I've mapped IP to name listed here and added for my clarity Band of WiFi  (Since Adguard is not doing DHCP in my case, tagging by MAC did not worked on returning results; I've tried it 4 months back)
This let me see my wife was using solely 2.4GHz due to coverage ==> I've upgraded main router for more coverage.

![image](https://user-images.githubusercontent.com/102585397/160823022-7ffec5bc-970f-416a-8580-8b0c312d7b39.png)
I've assigned tags "device_printer" or "device_phone" but was unable to group statistics by this tagging.

What I'm looking is to be able to define a sort of Groups, and based to each groups 2 or 3 hosts. Statistics and monitoring to be done by group.
Plain language:
**Phone_user1 group** (to include hosts **_phone_user1_2.4GHz_** & **_phone_user1_5GHz_**)
**Phone_user2 group** (to include hosts **_phone_user2_2.4GHz_** & **_phone_user2_5GHz_**)
In this way a combined overview would be available.

**Comment by fernvenue** [comment]
> it not an option that could suit me, as my IP range is 192.168.10.x only

@ArielXfire I don't understand, why it isn't an option?

Let's see the example you gave:

> Phone_user1 group (to include hosts phone_user1_2.4GHz & phone_user1_5GHz)

According to your screenshot, *phone_user1_2.4GHz*'s address is `192.168.10.51`, and *phone_user1_5GHz*'s address is `192.168.10.50`, so we can easily set them as one client by `192.168.10.50/31`, It includes two addresses, `192.168.10.50` and `192.168.10.51`, now we can call it *phone_user1*. Other devices can also be represented and defined by CIDR like this way.

**Comment by agneevX** [comment]
That's a good suggestion, but is there a reason why you manually create new clients?
