### ISSUE TITLE
how to turn off https login page

### ISSUE THREAD

**Issue by NDWCZ** [AdguardTeam/AdGuardHome#4443]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version

### Problem Description
--：someone always trying to login the adguard server by https without dns-query
### Proposed Solution
--：How to turn off HTTPS automatically jump to the login page

**Comment by ainar-g** [comment]
Hello.  Please use [GitHub discussions][1] for questions.

Disabling the HTTP interface is issue #1964.  Until it's done, you can set `bind_host` to `127.0.0.1`, which will only allow HTTP(S) requests from localhost.

[1]: https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a

**Comment by NDWCZ** [comment]
您好，您的邮件我已收到，紧急情况请致电：13078033735。谢谢
