### ISSUE TITLE
Intermittent occur DNS return REFUSED(DNS_PROBE_FINISHED_NXDOMAIN)

### ISSUE THREAD

**Issue by yatounoneko** [AdguardTeam/AdGuardHome#4444]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.5
* **How did you install AdGuard Home:**
  * GitHub releases(updated by web page)
* **How did you setup DNS configuration:**
  * PC System(physical machine)
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows server 2019

### Expected Behavior
Normal should return the correct IP or wait for loading.

### Actual Behavior
Open the website somtime will return REFUSED(Chrome will appear DNS_PROBE_FINISHED_NXDOMAIN), and the normal IP is returned after repeatedly refreshing the web page.

Not just one website, the same situation occurs intermittently across multiple websites.
When problem in occurring, REFUSED will be return to all sites result if have not been visited within this period of time.

### Screenshots

Multiple DNS are the same record
Screenshot:
![](https://oxo.hk/index.php?explorer/share/file&hash=c4b5mmJR3kBET6fswQT3l1BtcynJjHqq-kRXUmNLn7fHaG9kW5wMhAGGk18Bw57jD1N_zQ)
![](https://oxo.hk/index.php?explorer/share/file&hash=d024of82wK_fU_22r9ajAw5fTafNerpMFRL1SrKVI-DZ_Lu83kF8exmtdqw1lOAnRFhwrA)

After that, there will be some extremely time-consuming records
![](https://oxo.hk/index.php?explorer/share/file&hash=f88cCWULHspyv1ufbwtH3TLsi_Fr6Frf6JTM49npX_EeyMraRaD0URt-TgoUZ0Zy_4HUtg)

### Additional Information

FYI, this problem doesn't just happen in the latest version, it's been found in several previous versions.

**Comment by fernvenue** [comment]
There is no doubt that the domain `share.dmhy.org` already blocked by the firewall or poisoned by your ISP, you should use DoT or DoH etc, for these specific domains.

```
[/dmhy.org/]tls://8.8.8.8
[/dmhy.org/]tls://1.1.1.1
```

And if you worried about geo-based DNS or CDN results, maybe you wanna try this: https://github.com/AdguardTeam/AdGuardHome/issues/4410#issuecomment-1073004846.

**Comment by yatounoneko** [comment]
@fernvenue Thank you for your reply, but I know this problem is not affected by ISP. I'm in Hong Kong now, _not mainland_.

@EugeneOne1 I did not enable EDNS client subnet... Because it's not clear what use he has.
Also, I will try to set up the verbose log and send it to you. 
<details>
<summary>FYI</summary>
FYI, I used the OpenWRT for main router and also set the DHCP option "6,192.168.2.212". 
<br>The client direct gets the DNS server is 192.168.2.212(AdGuard Home server).

And, I have been set the Dnsmasq DNS server forward to AdGuard Home server. (Dnsmasq is default DNS server in OpenWRT)
<br>I don't know if it will have any impact?
</details>

I can't confirm when the time will occur the problem but I will keep updated you if the problem occurred. Thank you.

**Comment by EugeneOne1** [comment]
@yatounoneko, we've received it, thanks.  We've found lots of lines like this:

```
... [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(): Ratelimiting X.X.X.X:NNNN based on IP only
```

Each of them points to the same IP (real IP is redacted).

It seems that the client at `X.X.X.X` sends lots of queries and reaches both AdGuard Home's rate limit and perhaps the upstreams' as well.  I suppose this client is Dnsmasq which has caching disabled.  Could you please try to enable it if it is?

Also, do you use AGH's DHCP or another one?

**Comment by yatounoneko** [comment]
@EugeneOne1 Oh... That IP is my main router (Openwrt), and normally Dnsmasq shouldn't make any query requests because the client is getting DNS information directly from AdGuard.

DHCP is Dnsmasq arrange.

I see that Dnsmasq caching has been enabled, but I found the Dnsmasq maximum number of concurrent queries is default 150. I tried to set the number same as AdGuard(20). Let's see if the problem will happen again...

At least now, we can be certain that because of my router over-query that causes the problem to occur, right?

**Comment by EugeneOne1** [comment]
@yatounoneko, I guess you have lots of requests from the main router in the statistics.

>  At least now, we can be certain that because of my router over-query that causes the problem to occur, right?

Yeah, looks like that.  Let's see if the issue persists.

**Comment by EugeneOne1** [comment]
@yatounoneko, any update since?  If the `REFUSED` code still occurs?

**Comment by pdario** [comment]
Same here: a lot of DNS_PROBE_FINISHED_NXDOMAIN that solve themselves at secondo attempt. Please fix!!

**Comment by yatounoneko** [comment]
> Same here: a lot of DNS_PROBE_FINISHED_NXDOMAIN that solve themselves at secondo attempt. Please fix!!

Can you find the and client has any Irregular count number  in your client list

**Comment by pdario** [comment]
What do you mean with "irregular count number"? What figures should I look for?

**Comment by yatounoneko** [comment]
> What do you mean with "irregular count number"? What figures should I look for?

Home page have dhcp list, will count the number of dns queries. 

Usually, some devices that should not be present have a high record of DNS query times, for example, the router hijacks the DNS.  Or some devices have too many queries to exceed the adguard query limit per second.

Of course, this is just my personal situation, the details still need to see the error response of the log.

**Comment by pdario** [comment]
Which home page do you mean?
I can't see any DHCP label on https://adguard-dns.io/it/dashboard/.

The PC I'm using (and where I see the problema) has 3,484 blocked requests now out of 18,714.
Are these numbers, ok?

My home router is set to use Google DNS.

**Comment by EugeneOne1** [comment]
@pdario, so the issue is related to AdGuard DNS?  Please file an issue to [it's repo](https://github.com/AdguardTeam/AdGuardDNS).

**Comment by pdario** [comment]
I'll try there too, but it always happened with AdGuard

**Comment by EugeneOne1** [comment]
@pdario, this repo is of AdGuard Home.  Perhaps, you'll also find these repositories helpful:

 *  [AdGuard For Mac](https://github.com/AdguardTeam/AdguardForMac)
 *  [AdGuard For Windows](https://github.com/AdguardTeam/AdguardForWindows)
 *  [AdGuard For iOS](https://github.com/AdguardTeam/AdguardForiOS)
 *  [AdGuard For Android](https://github.com/AdguardTeam/AdguardForAndroid)

However, I think the issue may be closed for the moment.
