### ISSUE TITLE
9.9.9.9 is not reachable

### ISSUE THREAD

**Issue by OliverQing** [AdguardTeam/AdGuardHome#4449]
Hello . cause  my server couldn't reach any other dns server but one work, How can I do to customize this address to replace the 9.9.9.9  ？？

Thanks for the log, it's very helpful.

```
2021/04/01 16:49:39 1#40 [debug] 9.9.9.10:53: sending request AAAA dns10.quad9.net.
2021/04/01 16:49:39 1#42 [debug] 149.112.112.10:53: sending request AAAA dns10.quad9.net.
2021/04/01 16:49:49 1#40 [debug] 9.9.9.10:53: response: read udp 172.17.0.3:57004->9.9.9.10:53: i/o timeout
2021/04/01 16:49:49 1#42 [debug] 149.112.112.10:53: response: read udp 172.17.0.3:48214->149.112.112.10:53: i/o timeout
```

Judging by these lines, none of the bootstrap servers could be reached.  Please make sure that:

1.  Your container is set up to allow outgoing UDP requests.
2.  Your VM, too, doesn't have any blockers, like firewalls, that could block DNS traffic.
3.  You could also try and set both bootstrap servers and upstream servers on the DNS settings page to the IP addresses of some accessible local DNS servers and try again.

_Originally posted by @ainar-g in https://github.com/AdguardTeam/AdGuardHome/issues/2907#issuecomment-812056635_

**Comment by fernvenue** [comment]
Seems like you put someone else's log and comment here, I don't get it but yeah, you can customize your upstream servers easily.

On web UI you can just set it in **Settings - DNS Settings - Upstream DNS servers**, and you can change your bootstrap servers also in **Bootstrap DNS servers** here. In `AdGuardHome.yaml`, you can change it just like what [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) says.

That both works, just choose the way you need. Hope you can check the documentation first next time :)

**Comment by ainar-g** [comment]
Please post your questions to the the [Discussion forums][1].  I'll close this issue for now.

[1]: https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a
