### ISSUE TITLE
Ability to set upstream DNS per domain/TLD

### ISSUE THREAD

**Issue by nightah** [AdguardTeam/AdGuardHome#445]
Currently if you utilise AdGuardHome for DNS it will always send requests to your defined upstream server(s), even if the queried hostnames include local domains such as `.lan` `.local` etc.

If AdGuardHome had the ability to specify an upstream DNS server per domain/TLD this would save a request upstream and also ensure that the right DNS server recieves a request for the appropriate hostname(s).

With other services such as Pi-hole because it utilises dnsmasq this is quite simple to do for both Forward and Reverse DNS lookups:
```
server=/.lan/10.10.10.254
rev-server=10.10.10.0/24,10.10.10.254
server=/.wlan/10.10.11.254
rev-server=10.10.11.0/24,10.10.11.254
```

Would love to see this in a future release so I can finally give AdGuard the look it deserves, keep up the great work!

**Comment by ameshkov** [comment]
Makes sense, thank you!

**Comment by darookee** [comment]
Should be possible using the CoreDNS [file](https://coredns.io/plugins/file/) plugin and modifying the [template](https://github.com/AdguardTeam/AdGuardHome/blob/master/config.go#L239). And then maybe just let the user enable/disable an option to use a zone file which could be modified by hand...?

**Comment by ameshkov** [comment]
@darookee we're going to drop `forward` plugin soon and replace it with our own simple plugin (which will support DoH and DNSCrypt). `forward` is awesome for servers under heavy load, but it limits us in AdGuard Home.

**Comment by darookee** [comment]
@ameshkov sounds good. But I guess that would be independent from beeing able to add your own 'zones'?
After looking at the original ticket again I guess I missunderstood. I was under the impression the request was to add an option to specify your own zones, not DNS servers that should the request should be forwarded to for specific zones... 🤷‍♂️

**Comment by rothgar** [comment]
I also am looking for this feature. :+1: Commenting to subscribe to the issue and bump it for visibility.

Is there a way to set an upstream server via filters?

**Comment by ibksturm** [comment]
i made this workaround

dnsmasq (localzone dns & dhcp / dhcpv6) 
- zonefile local lan
- server 127.0.2.1:54 to AGH (resolvs the rest of the world)

**Comment by ameshkov** [comment]
Done https://github.com/AdguardTeam/AdGuardHome/commit/5b417d9f17e0074dc51a5ff5cf0e6aa6dadff512

**Comment by prologic** [comment]
YES! Thank you thank you thank you!!! :)
