### ISSUE TITLE
Preseted filter's disabled time values

### ISSUE THREAD

**Issue by Clems92** [AdguardTeam/AdGuardHome#4451]
Hello here!

### Problem Description
Sometimes it is useful to disable the filter for a few time to acces to a specific bloquedcontent, and quite often I forget to reactivate the filter after while!

### Proposed Solution
Instead of having the "disable" button on the dashboard web interface, we could have a rolling menu after clicking on "disable" with preseted values like "disable for 5 / 30 / 60 / Custom".
After clicking on the desired value, the filter will reactivate itself automoticaly. 
Nice to have a time countdown according to the value.

### Discussed in https://github.com/AdguardTeam/AdGuardHome/discussions/4450

<div type='discussions-op-text'>

<sup>Originally posted by **Clems92** March 31, 2022</sup>
Hi all!

I switched from another ads blocking solution to AdGuardHome, so happy to use it right now!

Nevertheless, I'm missing some intersting fonctiunalities, the most useful one is the ability to easily disable the filter for a preseted period of time, using the web interface. 
Instead of having the "disable" button on the dashboard, we could have a rolling menu after clicking on "disable" with values like "disable for 5 / 30 / 60 / Custom". 

Sometimes it is useful to disable the filter for a few time to acces to a content, and quite often I forget to reactivate it!

Thanks!
</div>

**Comment by fernvenue** [comment]
I'm a little confused about your description.

> ...disable the filter for a few time to acces to a specific bloquedcontent

I think you should set some temporary rules in *Custom filtering rules* instead of disable whole protection. As you can see in [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists), you can control the rules more flexibly in *Custom filtering rules*, even only allow some clients or one client to access some of the target you want, and does not change the behavior of other clients.

**Comment by Clems92** [comment]
Hi Fernvenue, thanks for your answer!

You certainly have the best and most secure solution, but unfortunately not the easiest for a non expert user. 

The use case of my request is the following:
one family member would like to watch a video from a replay streaming platform, but unfortunately the current rules are blocking the access. 
Never she (my wife 😊 ) will go in AGH user interface to edit rules or whatever, instead she push the "disable protection" button and most of the time she forget to re enable the protection after :) 

So if pushing "disable" button would open a roller menu like "disable for 5 / 30 / 60 / Custom", it would have 2 benefits: open opening the access to the content and secure automatically the network after. 
To be honest I’m used to that functionality from PiHole. 

Hope it helps to understand my point 😊

**Comment by ainar-g** [comment]
As I've noted in the discussion, this is basically the request #2823, so I'll close this one and merge.

As for the current UI, you can already disable it non-temporarily from the Query log page by pressing either _Unblock_ or _Unblock for this client only_ button.  The UI needs a lot of work, and that work will be done in the future.

**Comment by Clems92** [comment]
Ok thanks. 

Just to be sure, I'm talking about that button 

![image](https://user-images.githubusercontent.com/102724862/169498249-1b3dceca-a34b-407c-a827-27cae15c2192.png)
