### ISSUE TITLE
Need configuration settings on Pi 4

### ISSUE THREAD

**Issue by Zer0Gideon** [AdguardTeam/AdGuardHome#4453]
Hello
I post message on AdGuard support but I get reply for post here question.

I need exactly setting for AdGuard Home on raspberry pi 4, I installed but for wizard start to finish If can steps what need be checked and unchecked options and what filters is recommended for blocking...

I no good understand option for wizard step where is set network All interface or need change to eth0 in both options what is best recommended.

Also need how to configure UFW firewall ports in raspberry os.

Thanks

**Comment by fernvenue** [comment]
I don't think throwing a problem out and waiting for someone else is a good way to solve a problem. The development teams and community members of these projects already provided so great documentation:

- [AdGuardHome Configuration Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration)
- [UFW Community Help Wiki](https://help.ubuntu.com/community/UFW)

There are also suitable descriptions for each option in the AdGuardHome dashboard, and you can also go [AdGuardHome Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) to get some help and discuss with others, but not here. **Issues is used for feature requesting or bug reporting.** Hope everyone will read the instructions carefully before opening an issue, I believe if we don't do this it will cause trouble for the development team and community members.

**Comment by Zer0Gideon** [comment]
Thanks for information will see from links now I close.
