### ISSUE TITLE
The next step does not work, what should I do?

### ISSUE THREAD

**Issue by xyxmos** [AdguardTeam/AdGuardHome#4454]
![image](https://user-images.githubusercontent.com/102278948/161204946-2ffee926-1778-4f33-80c9-3658493a59fd.png)

**Comment by EugeneOne1** [comment]
@xyxmos, hello.  It seems that port `80` (which is used for web admin interface) is already bound by some other process.  See the [wiki page](https://github.com/adguardteam/adguardhome/wiki/FAQ#bindinuse).

Could you please try to set another port?  If it helped?

**Comment by Birbber** [comment]
Closing this issue due to no reply. Please re-open if needed.
