### ISSUE TITLE
安装脚本有问题

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#4455]
![Screenshot_2022-04-01-15-21-15-128_com.termux.jpg](https://user-images.githubusercontent.com/28734349/161215062-a9cca6e7-1d9a-4426-a302-dd928db91365.jpg)

**Comment by fernvenue** [comment]
That means the existing AdGuard Home installation is detected, just check and try again. Source code [here](https://github.com/AdguardTeam/AdGuardHome/blob/6824eec3084a1a77e0d702c292f6453400df669a/scripts/install.sh#L517).
