### ISSUE TITLE
Command line to add / remove filters

### ISSUE THREAD

**Issue by z4rn0x** [AdguardTeam/AdGuardHome#4456]
Hello!
It's not a problem or a bug, but more a feature request: would it be possible to add / remove filters via a command line? I'm using Adguard on my network for my kids (parental control) and I would like to add and remove some filters easily. I'm using Adguard via Home Assistant, and the addon doesn't allow this feature, so I was thinking that a command line would be a good option. Any hope to see this feature in a near future?

**Comment by fernvenue** [comment]
Sure, you can add or remove filters by editting `AdGuardHome.yaml` on your console, just use vim or sed or anything you want to edit it, that's quite simple. Make sure you have reloaded or restarted the AdGuardHome service after editting the configuration file, if you worried about your service you can check your configuration file first by `--check-config` flag. And you can get more information about that from [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file). 

Hape this can help you :)

**Comment by z4rn0x** [comment]
Thank you, this is very promising! Unfortunately I can't find this file... Do you know where it's located? I'm using HA OS on a linux distro. I searched for the file with VS...

**Comment by fernvenue** [comment]
It's in the root directory of AdGuardHome, on most Unix systems the default directory is `/opt/AdGuardHome`, but on macOS it's `/Applications/AdGuardHome`. It depends on how you installed AdGuardHome.

Or you can use `find` command to find the configuration file in whole `/` directory like this:

```
~# find / -name AdGuardHome.yaml
/opt/AdGuardHome/AdGuardHome.yaml
```

Tips: Remember to backup the configuration file before editing it, and you can use `--check-config` to test it before applying.

**Comment by z4rn0x** [comment]
Well, I guess I don't have access to it via Home Assistant. I think I will have to create a VM outside of HA. Thanks for the help!

**Comment by ainar-g** [comment]
As @fernvenue mentioned, you can do that by editing the configuration file.  The format is documented on the [wiki page][1], and its changes are mentioned in the [change log][2].  If you have further questions related to AdGuard Home, we have the [Discussion forums][3].  I'll close this issue for now.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
[2]: https://github.com/AdguardTeam/AdGuardHome/blob/master/CHANGELOG.md
[3]: https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a
