### ISSUE TITLE
dhcp lease (feature request)

### ISSUE THREAD

**Issue by pendie** [AdguardTeam/AdGuardHome#4457]
dhcp server lease period like mikrotik

**Comment by fernvenue** [comment]
You can use `lease_duratio` option to lease duration in seconds, just like the [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) says:

> `lease_duration` - lease duration in seconds. If `0`, use the default duration of 24 hours.

That works both on DHCPv4 and DHCPv6.
