### ISSUE TITLE
DNS rewrite 修改

### ISSUE THREAD

**Issue by colorsakura** [AdguardTeam/AdGuardHome#4459]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

![image](https://user-images.githubusercontent.com/32534829/161407645-8b869310-6eca-4cda-907c-557df4ae037f.png)

无法对已添加的host进行修改，希望可以添加修改的功能。

**Comment by fernvenue** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1577.

**Comment by stevenzhu25** [comment]
目前来说你可以通过删除后重新添加， 或者也可以尝试停止AdGuard Home进程然后手动修改AdGuardHome.yaml.

**Comment by chenyajunai** [comment]
Because it can't be modified, I added it in the custom rules

**Comment by Birbber** [comment]
Closing as a duplicate of [#1577](https://github.com/AdguardTeam/AdGuardHome/issues/1577).
