### ISSUE TITLE
"Clear Log" button

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#446]
Can we have a clear log button just in case someone or some authority want's access to the server?

**Comment by GOODTESTA** [comment]
Very important, I hope this future will be implement....

**Comment by Bluscream** [comment]
This shouldn't be hard to implement for 0.96, right?

**Comment by ameshkov** [comment]
@Bluscream upvote the feature request to make it sooner. We choose from the most upvoted.

**Comment by davidbdeath** [comment]
I want this feature as well.

**Comment by bingobob** [comment]
Yes please, I'd like this also.

**Comment by Bluscream** [comment]
@davidbdeath @bingobob Click on the 👍 below my first post to upvote the suggestion. Adding additional comments will waste developer time and it will take longer.

**Comment by RedFoxy** [comment]
still not implemented in v0.107.36?
