### ISSUE TITLE
 Server "tls: //dns11.quad9.net": cannot be used, check if you wrote it correctly

### ISSUE THREAD

**Issue by logiksmok** [AdguardTeam/AdGuardHome#4466]
I have a problem with the "Primary DNS Servers" service
When you enter https / tls there you will get an error:
 Server "tls: //dns11.quad9.net": cannot be used, check if you wrote it correctly

It does not matter if it is the Raspberry PI / Is the Ubunut server - this error occurs.

![image](https://user-images.githubusercontent.com/72006749/162142228-e07aedae-ce1b-404e-b813-29cdb02dfeb1.png)

**Comment by fernvenue** [comment]
What if you use IP address here like this:

```
# dns11.quad9.net
tls://9.9.9.11
```

Still getting error?

**Comment by logiksmok** [comment]
tls://1dot1dot1dot1.cloudflare-dns.com
or
tls://1.1.1.1
Still getting error

**Comment by fernvenue** [comment]
> its ok :)

So you can use IP address for `dns11.quad9.net`, and actually you should use IP address first, the Quad9 DNS Servers are configured with SSL certificates on their IP addresses, so there is no need for additional resolution by Bootstrap DNS servers.

> tls://1dot1dot1dot1.cloudflare-dns.com
> or
> tls://1.1.1.1
> Still getting error

Seems like you have no connection with `1.1.1.1`, you can try traceroute to 1.1.1.1 to see what's happen. Cloudflare's DNS Servers are also configured with SSL certificates on their IP addresses.

**Comment by logiksmok** [comment]
interesting, because it also works up to 1.1.1.1, but there is a bug in 1.1.1.2 and 1.1.1.3

**Comment by fernvenue** [comment]
> interesting, because it also works up to 1.1.1.1, but there is a bug in 1.1.1.2 and 1.1.1.3

Never define something as a bug lightly :)

Cloudflare does not officially support DoT on 1.1.1.2 and 1.0.0.2, you can use DoH configs instead:

```
https://1.1.1.2/dns-query
https://1.0.0.2/dns-query
```

It provides the same service, and there is also no need for additional resolution by Bootstrap DNS servers.

**Comment by logiksmok** [comment]
thx work :)
