### ISSUE TITLE
AdGuard Home auto-update

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#448]
- [x] Automatic Check for new version
- [ ] configurable auto-update
- [x] Manual Update from within the webinterface
- [x] Update notifications within the webinterface (and maybe even within connected AG clients)

**Comment by ameshkov** [comment]
>  Automatic Check for new version
> Update notifications within the webinterface (and maybe even within connected AG clients)

These are done already

**Comment by Bluscream** [comment]
Then check them ;)

**Comment by ameshkov** [comment]
What's `configurable auto-update` though?

**Comment by Bluscream** [comment]
> What's configurable auto-update though?

When you have the "silent auto-update" setting enabled it just does the update process in the background and restarts itself everytime a new update was found.

**Comment by ameshkov** [comment]
> When you have the "silent auto-update" setting enabled it just does the update process in the background and restarts itself everytime a new update was found.

Silent auto-update should be a separate feature request, that's for sure

**Comment by Bluscream** [comment]
I'd say this is pretty much done (use docker for autoupdate)
