### ISSUE TITLE
Question. Many stranger DNS requests

### ISSUE THREAD

**Issue by lifeindarkside** [AdguardTeam/AdGuardHome#4488]
30.03.2022 i see some strange dns requests from another country

IP Sample:

- 162.55.101.232
- 94.130.52.221
- 66.204.14.43
- 81.169.145.90
- 178.237.56.152
- 192.165.82.183
- 162.55.33.74
- 109.70.148.223
- 176.58.105.179

requests domain 
Edupage.org

Answer from  AdGuard HOME server 
```
Детали ответа
Статус
Обработан
DNS-сервер
https://dns.google:443/dns-query (получено из кеша)
Затрачено
0.41 мс
Код ответа
NOERROR
Ответ
TXT: forward-email=sp1tychy:sp_1@poczta.onet.pl (ttl=3530)
TXT: forward-email=sp5swiecie:szkola55@wp.pl (ttl=3530)
TXT: forward-email=pzsplegionowo:pzsplegionowo@gazeta.pl (ttl=3530)
TXT: forward-email=msp12piekary:msp12piekary@interia.pl (ttl=3530)
TXT: forward-email=tomekc-demo:tomek@librus.pl (ttl=3530)
TXT: forward-email=zspig1:zspog1@gmail.com (ttl=3530)
TXT: forward-email=sp34:zsp6-sekretariat@tlen.pl (ttl=3530)
TXT: forward-email=gimkaliszpom:gimnazjumkaliszpom@wp.pl (ttl=3530)
TXT: forward-email=gimlisow:gimlisow@interia.pl (ttl=3530)
TXT: forward-email=zlgdlugoleka:zlgdlugoleka@wp.pl (ttl=3530)
TXT: forward-email=password:daniel.kyska@asc.sk (ttl=3530)
TXT: forward-email=spdemo:sylwester.wydmuch@librus.pl (ttl=3530)
TXT: forward-email=abuse:jan@asc.sk (ttl=3530)
TXT: forward-email=zspkotowo:zspkotowo@e.pl (ttl=3530)
TXT: forward-email=hilfe:asc@raabe.de (ttl=3530)
TXT: forward-email=spbielawy:spbielawy@vp.pl (ttl=3530)
TXT: forward-email=spchojne:spchojne@op.pl (ttl=3530)
TXT: forward-email=sprakowiec:sprakowiec@wp.pl (ttl=3530)
TXT: forward-email=jejgim:jejgim@poczta.onet.pl (ttl=3530)
TXT: forward-email=spwitoszow:sp-witoszow@neostrada.pl (ttl=3530)
TXT: forward-email=zs2choszczno:sekretariatch@vp.pl (ttl=3530)
TXT: forward-email=mos-przytok:mos.przytok@wp.pl (ttl=3530)
TXT: forward-email=spleszczydol:szkolaleszcz@interia.pl (ttl=3530)
TXT: forward-email=lo25:lo25@lo25.pl (ttl=3530)
TXT: forward-email=gimmakow:gimnazjumwojciech@op.pl (ttl=3530)
TXT: forward-email=spuciechowice:spuciech@poczta.fm (ttl=3530)
TXT: forward-email=dobrodzienps:ewamacha63@o2.pl (ttl=3530)
TXT: forward-email=p35lublin:poczta@p35.lublin.eu (ttl=3530)
TXT: forward-email=soswchojna:sosw_chojna@interia.pl (ttl=3530)
TXT: forward-email=zs3hajnowka:sp6hajnowka@wp.pl (ttl=3530)
TXT: forward-email=psppolczyn:pspnr1@post.pl (ttl=3530)
TXT: forward-email=spszczesne:sp_szczesne@o2.pl (ttl=3530)
TXT: forward-email=zsskoronowo:zsskoronowo@wp.pl (ttl=3530)
TXT: forward-email=gim82bem:gim82bem@o2.pl (ttl=3530)
TXT: forward-email=sp3mikolow:sp3mikolow3@poczta.onet.pl (ttl=3530)
TXT: forward-email=sp5otwock:sp5_otwock@op.pl (ttl=3530)
TXT: forward-email=bielinski:zszgorakalwaria@wp.pl (ttl=3530)
TXT: forward-email=pp4jastrzebie:pp4@um.jastrzebie.pl (ttl=3530)
TXT: forward-email=sp46:sp46@mokotow.waw.pl (ttl=3530)
TXT: forward-email=sp285waw:sp285@edu.um.warszawa.pl (ttl=3530)
TXT: forward-email=sp12:sekretariat@sp12w.edu.pl (ttl=3530)
TXT: forward-email=spnowezduny:spzduny@op.pl (ttl=3530)
TXT: forward-email=gim94:atram24@op.pl (ttl=3530)
TXT: forward-email=gimpruszcz:gimpruszcz@gazeta.pl (ttl=3530)
TXT: forward-email=pspszwagrow:szwagrow@onet.eu (ttl=3530)
TXT: forward-email=sgimbrzoza:sgimbrzoza@op.pl (ttl=3530)
TXT: forward-email=przedszkole3mogilno:p3.mogilno@gmail.com (ttl=3530)
TXT: forward-email=sp37tychy:sp37tychy@wp.pl (ttl=3530)
TXT: forward-email=comeniusgarden:sp58@wp.pl (ttl=3530)
TXT: forward-email=szkolajeziorki:szkolajeziorki@o2.pl (ttl=3530)
TXT: forward-email=sp3glowno:sp3glowno@op.pl (ttl=3530)
TXT: forward-email=spadamowo:spadamow@wp.pl (ttl=3530)
TXT: forward-email=ken:zslloken@wp.pl (ttl=3530)
TXT: forward-email=gimjablonna:gimnazjum@jablonna.neostrada.pl (ttl=3530)
TXT: forward-email=zszabiele:spzabiele8a@poczta.onet.pl (ttl=3530)
TXT: forward-email=przedszkolegoldap:przedszkolemw@wp.pl (ttl=3530)
TXT: forward-email=spolszewo:spolszewo@op.pl (ttl=3530)
TXT: forward-email=szkolaklukowahuta:zkiwklukowahuta@poczta.onet.pl (ttl=3530)
TXT: forward-email=zswzdow:swzdow@poczta.wp.pl (ttl=3530)
TXT: forward-email=spbychlew:spbychlew13@gmail.com (ttl=3530)
TXT: forward-email=sprogozno:sp.rogozno@vp.pl (ttl=3530)
TXT: forward-email=zsniemce:zsniemce@gmail.com (ttl=3530)
TXT: forward-email=sp1skierniewice:sp1skierniewice@republika.pl (ttl=3530)
TXT: forward-email=zs1bukowno:zs1bukowno@wp.pl (ttl=3530)
TXT: forward-email=gimnazjumtrzebunia:trzebunia@op.pl (ttl=3530)
TXT: forward-email=ps4chrzanow:ps4@chrzanow.pl (ttl=3530)
TXT: forward-email=spkosieczyn:szkola.kosieczyn@neostrada.pl (ttl=3530)
TXT: forward-email=mdk1tychy:mdk1tychy@wp.pl (ttl=3530)
TXT: forward-email=zpokadz:zpokadz@wp.pl (ttl=3530)
TXT: forward-email=zsbocki:zs_bocki@wp.pl (ttl=3530)
TXT: forward-email=przedszkolandia334:przedszkolandia334@op.pl (ttl=3530)

```
Who can say, whats happend? what is this? What i need to do if this situation repeat again?

**Comment by EugeneOne1** [comment]
@lifeindarkside, hello.  Would you feel comfortable continuing the conversation in Russian?

Also could you please clarify a bit:
 *  What is the DNS type of this request?
 *  What do you mean by "IP sample"?

This response doesn't look extraordinary actually since this is a mechanism of e-mail forwarding.

**Comment by lifeindarkside** [comment]
> 

Да, комфортно.

Сегодня повторяется снова. 
На текущий момент я уже заблокировал запросы на данный домен.

> * What do you mean by "IP sample"?

IP адреса с которых осуществлялся запрос.

> * What is the DNS type of this request?
![image](https://user-images.githubusercontent.com/66727826/163381636-e5d16d39-57fa-4194-bdbe-d91344ae31ef.png)

**Comment by lifeindarkside** [comment]
> This response doesn't look extraordinary actually since this is a mechanism of e-mail forwarding.

Интересно почему через мой DNS сервер это проходит.

**Comment by EugeneOne1** [comment]
@lifeindarkside, замечательно, тогда продолжим на русском.

Судя по всему DNS-сервер обслуживает клиентов из внешней сети.  Если я правильно понимаю, AGH установлен на каком-то удаленном сервере.  Собирались ли вы использовать его в качестве публичного DNS сервера?

Если да, то хорошим решением было бы добавить соответствующие сети в поле "Разрешённые клиенты" на странице "Настройки DNS" – так AGH будет обслуживать только этот список адесов и сетей.  Если же AGH установлен в сети, к которой у вас есть "внутренний" доступ, то лучше переконфигурировать AGH, чтобы он обслуживал только внутренние интерфейсы (поле `dns.bind_hosts` в `AdGuardHome.yaml`).

**Comment by lifeindarkside** [comment]
> 

На текущий момент он является публичным (незакрытым), т.к. у клиентов динамические адреса (сотовая связь, широкополосный провайдер интернета)

Большая часть устройств не умеет подключаться через HTTPS/TLS (роутеры, мобильные устройства)


Мобильные устройства на андроид нативном уровне не могут подключиться к dns серверу по TLS для конкретного клиента. Только используя полный домен (например *domain.ru).

**Comment by EugeneOne1** [comment]
Насколько мне известно, Android поддерживает DNS-over-TLS нативно начиная с 9-й версии (Android Pie), так что с правильно настроеным шифрованием его использование не должно вызвать проблем.  Если я правильно понял, что у вас wildcard сертификат (*.domain.ru), то использовать DoT/DoH/DoQ хотя бы с [Android устройствами](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#android) можно через [механизм ClientID](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid).

Тем не менее, запросы от остальных устройств придется ограничивать через "Разрешенных клиентов".  Адреса, которые вы привели, находятся в совершенно разных подсетях – я думаю, не составит труда избавиться от большинства из этих запросов просто выбрав подходящие подсети.  Как правило, у провайдеров их не очень много.

**Comment by lifeindarkside** [comment]
> [Android устройствами](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#android) можно через [механизм ClientID](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid).
> 
> Тем не менее, запросы от остальных уст

К сожалению, это невозможно. устройства выдают ошибку.
Либо не подключаются к DNS серверу


> я думаю, не составит труда избавиться от большинства из этих запросов просто выбрав подходящие подсети. Как правило, у провайдеров их не очень много.

Добавить стоит с CIDR префиксом примерный пул адресов. Верно?

**Comment by EugeneOne1** [comment]
@lifeindarkside, вполне вероятно, что проблема где-то между устройством и AGH, например, неверная конфигурация клиентов – без текста ошибки сказать трудно.

Насчет CIDR префиксов – все верно.  В идеале, сначала стоит проанализировать адреса, которые выдаются провайдером, и на основе этой информации уже выбрать максимально длинный префикс.

**Comment by lifeindarkside** [comment]
> без текста ошибки сказать трудно.

В основном его нет. При попытке ввести любой адрес с ClientID просто нельзя сохранить персональный dns сервер.
например адреса:
10.domain.ru или https://domain.ru/dns-query/10

попросту нельзя сохранить даже. Но если удастся сохранить, то будет простая надпись "Ошибка подключения"

**Comment by EugeneOne1** [comment]
На всякий случай уточню несколько моментов:
 *  Выставлены ли все необзодимые значения на странице "Настройки шифрования" и включено ли само шифрование?
 *  На стороне AGH действительно настроен клиент с условным ClientID `10`?

Также, советую обратить внимание на [эту страницу руководства](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#reverse-proxy).

**Comment by lifeindarkside** [comment]
> * Выставлены ли все необзодимые значения на странице "Настройки шифрования" и включено ли само шифрование?

да. 
![image](https://user-images.githubusercontent.com/66727826/163419275-85d11da1-e535-451f-8a6f-fa5e9958849b.png)
![image](https://user-images.githubusercontent.com/66727826/163419329-b4dd5063-ff90-42bb-8c0d-e125b0d35c90.png)



> * На стороне AGH действительно настроен клиент с условным ClientID `10`?

Да.

Подключить к серверу dns с client id возможно только используя приложение Adhuard и прописанном в нем адресе dns сервера

**Comment by EugeneOne1** [comment]
Ладно, я думаю, вам имеет смысл просмотреть наш раздел Discussions по поводу проблемы с зашифрованным DNS.  Смело открывайте новую тему, если ничего подобного еще не обсуждалось.

Что же касается изначального вопроса – я закрою этот тикет, если вы не против.

**Comment by lifeindarkside** [comment]
Хорошо, спасибо.
