### ISSUE TITLE
Dns start block google.ru for me

### ISSUE THREAD

**Issue by Gavcheg** [AdguardTeam/AdGuardHome#449]
1. Try open google.ru
2. Get "DNS_PROBE_FINISHED_NXDOMAIN"
3. If i use another dns, it works.
4. google.com also works as expected

Can anyone check it? If for others all ok, then i try more investigating problem on my side.

Ps. I use "family protection" ip's.

**Comment by dfmcvn** [comment]
I don't see any problem with default AdGuard DNS

```
# nslookup google.ru 176.103.130.130
Server:         176.103.130.130
Address:        176.103.130.130#53

Non-authoritative answer:
Name:   google.ru
Address: 74.125.68.94
```

Consider:
- Check your upstream DNS config.
- Check the firewall, if you are running AGH on a VPS, some provider blocked port 53 by default.

**Comment by ameshkov** [comment]
Safe-search enforced requests were cached on 176.103.130.132/4, this will be resolved shortly, thank you for letting us know!
