### ISSUE TITLE
Adguard Public dns doesn't block these site

### ISSUE THREAD

**Issue by omarfarah110** [AdguardTeam/AdGuardHome#4490]
https://gsmgeeky.com/frpfile-ramdisk-bypass-passcode-tool-for-disable-ios-15-without-jailbreak/

https://www.mobileflasherbd.com/2022/03/mtk-auth-bypass-tool-v34-free-download.html

https://gsmatoztool.com/

**Comment by ainar-g** [comment]
This is the repository of AdGuard Home, an on-premise DNS server.  If you want to report an issue with AdGuard's other products or filters, please use [this form][1].

[1]: https://reports.adguard.com/en/new_issue.html
