### ISSUE TITLE
DHCP设置功能，新增指定DNS地址的功能，dhcp-option6

### ISSUE THREAD

**Issue by CallMeR** [AdguardTeam/AdGuardHome#4495]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Problem Description

In my intranet environment, there are 2 servers running Adguard Home to provide DNS service (eg. 192.168.1.1, 192.168.1.2), but the DHCP of Adguard Home specifies the local IP address(eg. 192.168.1.1 ) as the DNS server by default during operation, and I have to manually add additional DNS servers in the client .

### Proposed Solution

It is hoped that the DHCP server of Adguard Home can support dhcp-option 6, that is, let the client obtain the specified DNS server list.

**Comment by fernvenue** [comment]
AdGuardHome already supports DHCP Option 6, please read [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#configuration).

**Comment by CallMeR** [comment]
> AdGuardHome already supports DHCP Option 6, please read [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#configuration).

3Q~
