### ISSUE TITLE
如何过滤到CNAME的查询请求？

### ISSUE THREAD

**Issue by SnowMikuLive** [AdguardTeam/AdGuardHome#4496]
如何过滤掉CNAME的查询请求？

**Comment by SnowMikuLive** [comment]
如何过滤掉CNAME的查询请求？

**Comment by fernvenue** [comment]
Please describe your problem as specifically as possible. If you mean filtering requests, then:

```
*$dnstype=CNAME,dnsrewrite=SERVFAIL
```

Just read the [AdGuardHome Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite) to get more information about that.

If you filtering query log, we already have https://github.com/AdguardTeam/AdGuardHome/issues/2939 for that. Please make sure you have checked the existing material before opening an issue next time, and I think this should go to discussions.
