### ISSUE TITLE
DNS settings not saving

### ISSUE THREAD

**Issue by sgb999** [AdguardTeam/AdGuardHome#4506]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
  *  v0.107.6
* **How did you install AdGuard Home:**
  * 
  * installed from docker
* **How did you setup DNS configuration:**
  * 
  * router
* **If it's a router or IoT, please write device model:**
  * 
  * Raspberry Pi 4 Model B
* **CPU architecture:**
  * arm64
* **Operating system and version:**
  * Docker version 20.10.14, build a224086

### Expected Behavior

The DNS settings are supposed to be stay what I set them to, e.g., Upstream DNS servers to https://1.1.1.1/dns-query and 
Bootstrap DNS servers to 1.1.1.1
### Actual Behavior

after setting dns settings for Upstream and Bootstrap, I recieve a green pop up saying it has saved and a log saying it was changed in my docker logs, checking the configuration around an hour or so later it changes back to default quad 9 settings, all the other dns settings are the same value to what i modified i.e., DNS Server configuration stays the same after i have modified it
### Screenshots

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/59648138/163982023-6cfbb73c-da24-4cfc-97ee-46ae69484b63.png">
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/59648138/163982153-46267472-7f7c-4d75-865c-fbbdf0ef9c12.png">

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Hello, and thanks for the report.  How have you configured the Docker volumes?

**Comment by strobowski** [comment]
same issue for me
i used wget https://github.com/tteck/Proxmox/blob/main/install/adguard-install.sh on proxmox
I cannot change or add to dns server https://dns10.quad9.net/dns-query

**Comment by steve1123456** [comment]
Also having same issue. Running as LXC in Proxmox. Any ideas? Thanks.
