### ISSUE TITLE
Queries with dns.google string suffixed 

### ISSUE THREAD

**Issue by hexclann** [AdguardTeam/AdGuardHome#4510]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.6
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * DOT and DoH
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior
DNS queries should not be modified.

### Actual Behavior
Most of the DNS queries made by the devices are suffixed with `*.dns.google` or the hostname `*.adguard.example.com`

### Screenshots

![chrome_UGjbPSGZkz](https://user-images.githubusercontent.com/59732888/164193157-2ce8d546-38f0-42ec-86e8-24c2e9ae6720.png)

![chrome_SMNcF4aLxE](https://user-images.githubusercontent.com/59732888/164193165-cc9b7e1a-3a8c-489f-ab64-fcec1dc3c787.png)

How to get rid of these queries?

**Comment by EugeneOne1** [comment]
@hexclann, hello.  Have you got any custom filtering rules or DNS rewrites?  These are usually responsible for modifying the requests.

**Comment by hexclann** [comment]
I don't have any DNS rewrites, I have some [custom filtering rules](https://pastebin.com/xe444JqJ) which are created when I blacklisted few domains in the query log. 

I have also tried disabling these settings but the issue persists 
![chrome_dIweOMjovx](https://user-images.githubusercontent.com/59732888/164908809-e703dc82-1577-459b-9704-743977d76ec0.png)

**Comment by ainar-g** [comment]
@hexclann, are these requests coming from a Windows machine, by any chance?  Also, do you use AdGuard Home as the DHCP server in that network?

**Comment by anudeepND** [comment]
@ainar-g It's not limited to Windows machine, it's coming from multiple devices. DHCP is handled by the router

**Comment by hexclann** [comment]
@ainar-g It's not limited to windows machines. And Adguard is not the DHCP server

**Comment by ainar-g** [comment]
I see.  This still probably has something to do with the clients' settings, not AdGuard Home's.  In fact, AdGuard Home cannot append anything to queries.  See some answers here, and perhaps those will help: <https://serverfault.com/questions/74067/windows-appending-domain-suffix-to-all-lookups>.

**Comment by hexclann** [comment]
Thanks for the information
