### ISSUE TITLE
Not listener IP

### ISSUE THREAD

**Issue by IzeroCs** [AdguardTeam/AdGuardHome#4519]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  4.5.1
* **How did you install AdGuard Home:**
  *  Hassio
* **How did you setup DNS configuration:**
  *  IoT
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 4 4GB
* **CPU architecture:**
  *  AARCH64
* **Operating system and version:**
  *  Debian GNU/Linux 11 (bullseye)

### Actual Behavior

When I start up, or just run Raspberry, the addon only listens to IP: 172.30.32.1, and IP: 192.168.31.107 is not listening. And when I restart the addon in hassio, IP: 192.168.31.107 can listen.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 4.5.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.4.6
 Home Assistant Supervisor: 2022.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
[21:17:24] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[21:17:26] INFO: Starting AdGuard Home server...
[services.d] done.
2022/04/23 21:17:26.504358 [info] AdGuard Home, version v0.107.6
2022/04/23 21:17:26.521360 [info] Initializing auth module: /data/adguard/data/sessions.db
2022/04/23 21:17:26.522770 [info] auth: initialized.  users:0  sessions:0
2022/04/23 21:17:26.522840 [info] Initialize web module
2022/04/23 21:17:26.564239 [info] AdGuard Home is available at the following addresses:
2022/04/23 21:17:26.564340 [info] Go to http://127.0.0.1:45158
[21:17:26] INFO: Starting NGinx...
2022/04/23 21:17:27.271207 [info] Starting the DNS proxy server
2022/04/23 21:17:27.271272 [info] Ratelimit is enabled and set to 20 rps
2022/04/23 21:17:27.271284 [info] The server is configured to refuse ANY requests
2022/04/23 21:17:27.271296 [info] DNS cache is enabled
2022/04/23 21:17:27.272431 [info] MaxGoroutines is set to 300
2022/04/23 21:17:27.273684 [info] Creating the UDP server socket
2022/04/23 21:17:27.276928 [info] Listening to udp://172.30.32.1:53
2022/04/23 21:17:27.277006 [info] Creating a TCP server socket
2022/04/23 21:17:27.278083 [info] Listening to tcp://172.30.32.1:53
2022/04/23 21:17:27.279493 [info] Entering the UDP listener loop on 172.30.32.1:53
2022/04/23 21:17:27.280558 [info] Entering the tcp listener loop on 172.30.32.1:53
```

**Comment by Potterli20** [comment]
Delete: this/data/adguard/data/sessions. The db, is normal

**Comment by IzeroCs** [comment]
You can't do it that way. The problem is that if I run or restart Adguard
in Hassio, it listens to two IPs: 172.30.33.1 and 192.168.31.107. If I
reboot the Raspberry or run the reboot command it just listens to IP:
172.30.33.1. Previous versions of Adguard did not have this problem, I
freed port 53 and it didn't solve the problem. Now every time I restart
Raspberry I have to go into Hassio to restart Adguard, very annoying.

Vào 0:07, CN, 24 thg 4, 2022 trli ***@***.***> đã viết:
