### ISSUE TITLE
How to see DNS events beyond the 5000th log entry? Or, how to see Blocked events over longer timeframe?

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#452]
This morning I was surprised to see that my AGH had registered some 'Blocked malware/phishing' events for the first time. Hovering my mouse cursor over the 'Blocked malware/phishing' graph at the top of the Dashboard I could see that they had occurred a few hours earlier.

However, when I went into the Query Log, I found that there had already been 5000 DNS query events since, and as such, the events I was interested to investigate had been rolled off.

How do I go about investigating these events in this situation?

Are there planned changes in upcoming version to possible also log 'block' events in a seperate log file for longer retention?

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.9 hotfix 1
| How did you setup DNS configuration:| Windows Server 2012 R2 DHCP
| If it's a router or IoT, please write device model:| Windows Server 2012 R2
| Operating system and version:| Ubuntu 18.04.1 running under Windows 10 WSL

**Comment by ameshkov** [comment]
Actually, AG Home stores log for 24 hours but shows only last 5k records in the dashboard UI.

The easy solution would be to make "Download log file" return the whole log and not just 5k records.

**Comment by AnthonyBe** [comment]
If the AGH UI can handle that amount of data them that would be excellent

**Comment by tomiams** [comment]
Such a feature of prolonging the statistics on the front page beyond 24h would be most welcomed for a more accurate overview. (week, month, year options would be superb).

Also, restarting AdGuardHome should not reset the statistics as is currently the case.

**Comment by ameshkov** [comment]
> Also, restarting AdGuardHome should not reset the statistics as is currently the case.

Hm, it actually does not reset stats (it's calculated on the AG Home startup using the current query log for the last 24h).

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/776#issuecomment-499468432

**Comment by szolin** [comment]
Query log's history size is up to 90 days now and an unlimited searching will be implemented in #1099
