### ISSUE TITLE
API to get all service options available for setting blocked_services

### ISSUE THREAD

**Issue by RoboMagus** [AdguardTeam/AdGuardHome#4520]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I'm trying to create an automatic schedule that will block / unblock specific services through the AdGuardHome API using `blocked_services/set`. I've been working on getting this API access in a python module so I can then call this through HomeAssistant on demand and on schedule. This works quite well, given that I've first taken a look at the blocked_services page of my local instance.
However when the set of available services would change (#3092, #3814), there is no automated way of telling.

### Proposed Solution

I would propose adding another function to the blocked_services API that allows anyone using the API to get an extensive list of services available on this interface.
E.g. `GET` `/blocked_services/services`. This could then either just return a list of service names compatible with the `/blocked_services/set` function, or a structure that contains their ID, name, (and icon).

### Alternatives Considered

Hard coding the currently available list and updating this every time the interface is updated. However that's not ideal

### Additional Information

Would like to eventually further integrate AdGuardHome into HomeAssistant, by extending the [python wrapper](https://github.com/frenck/python-adguardhome). Then having all allowed data that can be passed over the API available programmaticaly becomes even more important.

**Comment by ainar-g** [comment]
Merged in #4535.

**Comment by NebzHB** [comment]
Dears,
About https://github.com/AdguardTeam/AdGuardHome/pull/4535 , Is it possible to have the full name in that service list too ? example : 'ok' is displayed 'OK.ru' in the web interface ('disneyplus' : 'Disney+', ...)
