### ISSUE TITLE
Blocking by ctag does not work

### ISSUE THREAD

**Issue by s1lviu** [AdguardTeam/AdGuardHome#4526]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I've added the following custom rule, and `$ctag` does not block the internet access for its associated clients:
`||google.*^$ctag=device_phone`

_(If I replace $ctag with $client, the blocking works fine.. `||google.*^$client='xx.xx.159.24'`)_

### Expected Behavior

Accessing google.com for example should be blocked
### Actual Behavior

I can access any of google TLDs.

**Comment by ainar-g** [comment]
Hello.  We cannot reproduce that.  Does the query log show that the request is coming from a persistent client that it recognizes?

**Comment by s1lviu** [comment]
Yes, the query log shows the client id added in /#clients.

To mention that the clients are authenticating via DoH client id (e.g.: https://dns.adguarddns.tld/dns-query/**clientid**)
![image](https://user-images.githubusercontent.com/9863576/165306763-20473c2d-54ef-4b3d-b253-9ec2d5646cf5.png)

**Comment by s1lviu** [comment]
> We still cannot reproduce that, sorry. Please provide the following information:
> 
> 1. Which version of AdGuard Home are you using?

v0.107.6

> 2. Besides the ClientID, what are other identifiers that the persistent client in question has?  That is, is it only identified by the ClientID or by IP or CIDR as well?

Only by their ID.

> 3. Does the client use global settings or are there some other custom ones?

Global settings.

> 4. Can you [enable verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog), make a couple of requests with that client, and send the logs to us at [devteam@adguard.com](mailto:devteam@adguard.com) with the subject “AdGuard Home Issue 4526”?

Will do.
> 
> Thanks.

**Comment by ainar-g** [comment]
@s1lviu, thanks, we have received it.  There are two weird things there.  The first thing is this line:

```none
2022/04/26 15:36:14.362280 3714438#410 [debug] request came from proxy server 172.x.x.x
2022/04/26 15:36:14.362319 3714438#410 [debug] proxy 172.x.x.x is not trusted, using original remote addr
```

If your AdGuard Home is behind an HTTP proxy, you should set the `trusted_proxies` property in the configuration file.  See [this entry][1] in the FAQ.

The second weird thing is that something like this isn't shown:

```none
using settings for client Client-Name with ip 192.168.12.34 and clientid "my-client"
```

Could you send us the `clients` section from your `AdGuardHome.yaml` to the same address for us to try and reproduce the issue?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#real-ip-addresses-of-clients

**Comment by s1lviu** [comment]
I've added the Cloudflare trusted proxies, I can see now the real IP, but still ctag does not block the associated client :(
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/9863576/165349118-0fcde581-beb2-41f4-849d-9620858d1621.png">

**Comment by ainar-g** [comment]
Do you have the “Block domains using filters and hosts files” checkbox checked on the _Settings → General settings_ page?  Also, is the protection enabled on the Dashboard?

**Comment by s1lviu** [comment]
> Do you have the “Block domains using filters and hosts files” checkbox checked on the _Settings → General settings_ page? Also, is the protection enabled on the Dashboard?

Yes. Don't forget that If I replace $ctag with $client, the blocking works fine. 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/9863576/165353004-28314182-855a-4247-84a4-3c7b1cb34189.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/9863576/165353028-74ac84a6-6c13-4ab4-b59f-81cbb3b70622.png">

**Comment by ainar-g** [comment]
Thanks!  We'll also add some more debug logging in the next few days.  Perhaps that will clarify the situation.

**Comment by s1lviu** [comment]
It worked with `~` : `||google.*^$ctag=~device_phone` 

Does it seem it is working reversely than explained in the docs?

<img width="974" alt="image" src="https://user-images.githubusercontent.com/9863576/165369463-e3cb5ea6-e5fb-48f2-b0b2-6175bed8e45c.png">

**Comment by s1lviu** [comment]
I think I found something important, in the Client settings, the Requests count remains zero.
![image](https://user-images.githubusercontent.com/9863576/165497656-410a923a-5baa-4107-a691-7034c57d8ad5.png)

**Comment by ainar-g** [comment]
@s1lviu, we've added more logging in the latest beta as well as the latest edge builds.  Could you please backup your AdGuard Home data (and especially `AdGuardHome.yaml`), install the latest beta or edge build, and make another snapshot of the logs?

**Comment by s1lviu** [comment]
@ainar-g I think I found the problem. An issue from a VPN module changed the DoH id on the fly. Thanks for your support!
