### ISSUE TITLE
Remove CNAME records from response RR set

### ISSUE THREAD

**Issue by SnowMikuLive** [AdguardTeam/AdGuardHome#4537]
我不想让Adguard Home响应CNAME的查询数据，应该怎么设置？
例如：
CNAME: inappcheck-lb.itunes-apple.com.akadns.net. (ttl=120)
CNAME: inappcheck-cn.itunes-apple.com.akadns.net. (ttl=120)
CNAME: ioshost.qtlcdn.com. (ttl=120)
A: 119.36.65.151 (ttl=120)
A: 180.95.178.92 (ttl=120)

这组数据中的前三个CNAME的响应怎么样才能被丢弃掉？

我希望得到的响应数据：
A: 119.36.65.151 (ttl=120)
A: 180.95.178.92 (ttl=120)

**Comment by SnowMikuLive** [comment]
I don't want Adguard Home to respond to CNAME query data, what should I do?
  E.g:
  CNAME: inappcheck-lb.itunes-apple.com.akadns.net.  (ttl=120)
  CNAME: inappcheck-cn.itunes-apple.com.akadns.net.  (ttl=120)
  CNAME: ioshost.qtlcdn.com.  (ttl=120)
  A: 119.36.65.151 (ttl=120)
  A: 180.95.178.92 (ttl=120)

  How are the responses to the first three CNAMEs in this data discarded?

  The response data I want to get:
  A: 119.36.65.151 (ttl=120)
  A: 180.95.178.92 (ttl=120)

translated by google

**Comment by ainar-g** [comment]
It is currently impossible to do that, and I'm honestly not even sure if that would be valid, since those IPs technically don't belong to the host you've queries.

Why do you want to delete them?  Perhaps there is a better way to solve your original task?

**Comment by SnowMikuLive** [comment]
> It is currently impossible to do that, and I'm honestly not even sure if that would be valid, since those IPs technically don't belong to the host you've queries.
> 
> Why do you want to delete them? Perhaps there is a better way to solve your original task?

Filter out 65 browser type HTTPS DNS services to prevent iOS devices from bypassing regular DNS services

**Comment by ainar-g** [comment]
If you want to completely filter out all DNS queries with the HTTPS question type, you can simply use the `dnstype` modifier:

```none
*^$dnstype=HTTPS
```
