### ISSUE TITLE
Wrong answer order sometimes with CNAME

### ISSUE THREAD

**Issue by Radeon24** [AdguardTeam/AdGuardHome#4540]
### Issue Details

I observe a bug that, sometimes, the answer of a CNAME is in the wrong order : A first then CNAME. The consequence is that with Android device the request can't work (on Windows it seems that it works normally).

* **Version of AdGuard Home server:**
  * v0.107.6
* **How did you install AdGuard Home:**
  * Automated install
* **How did you setup DNS configuration:**
  * Proxmox LXC (Alpine Linux)

 * **Actual settings :**
 DNS upstream : 
 ```
 https://dns10.quad9.net/dns-query
 https://dns.cloudflare.com/dns-query
 [/mydomain.local/mydomain.eu/]10.42.10.53
 [/mail.mydomain.eu/]#
 ```
 No DNS rewrite
 The upstream server 10.42.10.53 for local resolution is a PowerDNS server : I observed the problem only with this resolutions.
 Requests directly to my PowerDNS server does not have the issue : CNAME are in the good order.
 The IP address of AGH is 10.42.10.52.

### Expected Behavior
When the answer is correct : 
```
dig amy.mydomain.eu @10.42.10.52

; <<>> DiG 9.11.5-P4-5.1+deb10u7-Debian <<>> amy.mydomain.eu @10.42.10.52
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38853
;; flags: qr aa rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;amy.mydomain.eu.           IN      A

;; ANSWER SECTION:
amy.mydomain.eu.    60      IN      CNAME   proxy1.mydomain.eu.
proxy1.mydomain.eu. 60      IN      A       100.64.142.200

;; Query time: 2 msec
;; SERVER: 10.42.10.52#53(10.42.10.52)
;; WHEN: sam. avril 30 14:59:29 CEST 2022
;; MSG SIZE  rcvd: 85

```

### Actual Behavior
Few seconds before, from the same test client, the answer was in the wrong order : 

```
dig amy.mydomain.eu @10.42.10.52

; <<>> DiG 9.11.5-P4-5.1+deb10u7-Debian <<>> amy.mydomain.eu @10.42.10.52
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8122
;; flags: qr rd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;amy.mydomain.eu.           IN      A

;; ANSWER SECTION:
proxy1.mydomain.eu. 16      IN      A       100.64.142.200
amy.mydomain.eu.    16      IN      CNAME   proxy1.mydomain.eu.

;; Query time: 0 msec
;; SERVER: 10.42.10.52#53(10.42.10.52)
;; WHEN: sam. avril 30 14:59:02 CEST 2022
;; MSG SIZE  rcvd: 85
```

The A record is send before the CNAME, this results a non working answer on Android devices (maybe on other devices too).

**Comment by agneevX** [comment]
Is your conditional forwarding upstream consistently returning correct results?

AdGuard Home has no reason to manipulate the DNS chain.

**Comment by EugeneOne1** [comment]
@Radeon24, hello.  As @agneevX correctly noted, this may be actually an upstream issue, not AGH's one.  Could you please check the query log for these two requests?  If the upstream indeed responds inconsistently the log entries will contain the appropriate resource records ordered differently as well.  Thanks.
