### ISSUE TITLE
Bug with "FQDN Client"

### ISSUE THREAD

**Issue by CordoWEB** [AdguardTeam/AdGuardHome#4542]
When a client use AdguardHome server with a FQDN, "theclient.domain.fr" & "TheClient.domain.fr" are view like differents clients.
This is not good for stats ;(

Adguard Home  v0.107.6 on Linux Ubuntu 22.04 et Linux Centos 6.10.

**Comment by agneevX** [comment]
> When a client use AdguardHome server with a FQDN, "theclient.domain.fr" & "TheClient.domain.fr" are view like differents clients.

This is a bit weird because domain names are case-insensitive. I have a bunch of clients with advertised NetBIOS names in Pascal case, but AGH normalizes them, as it should.

**Comment by CordoWEB** [comment]
![AdGuard](https://user-images.githubusercontent.com/17181694/166139631-de063db0-3f76-46ec-8e51-dabfb7635e92.png)

My FQDN is dns-spf.xxxxxxxx.xxx but someone use Dns-spf.xxxxxxxx.xxx in "private DNS" on Android and i have this.

**Comment by agneevX** [comment]
> but someone use Dns-spf.xxxxxxxx.xxx in "private DNS" on Android and i have this.

You mean to tell me you're running an open resolver?

**Comment by CordoWEB** [comment]
Yes but filter by firewall :)

**Comment by CordoWEB** [comment]
> @CordoWEB, hello and thanks for the report. We're able to reproduce the bug, the **ClientID** string is indeed case-sensitive for the moment. We're going to fix it soon.

Thank you so much :)

**Comment by EugeneOne1** [comment]
@CordoWEB, hello again.  We've just pushed the latest edge build, that should fix the issue.  Could you please check if it does?

**Comment by CordoWEB** [comment]
I'm sorry i don't have "test environment"

**Comment by EugeneOne1** [comment]
@CordoWEB, well, the issue seems resolved, at least on our test machines, so I'll close it for now.  Please, feel free to reopen it in case you'll face it again.  Thanks again.
