### ISSUE TITLE
dns重写或者自定义过滤器希望能订阅列表

### ISSUE THREAD

**Issue by BA7JCM** [AdguardTeam/AdGuardHome#4545]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
目前我所在的地区访问一些网站有困难，但是这些困难可以通过写hosts解决，但那些网站在我所在地区可用的IP是随时可能变的，我手上有一份定时更新的hosts文件，但我手头上需要用到这份hosts的设备有相当一部分是无法写hosts的，故我打算使用adguard home里面的dns重写或者自定义规则来订阅这个列表，让adgh通过这份列表解析列表中的域名

### Proposed Solution
给dns重写加上订阅列表的功能

### Alternatives Considered
目前暂时使用拦截列表来订阅这份hosts，让它拦截这些解析按照hosts规则中的响应来给客户端答复

### Additional Information
目前上面所说的“访问有困难”的网站主要是GitHub和jsdelivr，这俩可以通过hosts解决

**Comment by Somalia0932** [comment]
对呀，目前的dns重写，一条一条的，不太方便。

**Comment by cxw620** [comment]
曲线救国的话,ADH也支持host类型的广告拦截规则,做成广告拦截的订阅列表可作权宜之计

**Comment by BA7JCM** [comment]
> 曲线救国的话,ADH也支持host类型的广告拦截规则,做成广告拦截的订阅列表可作权宜之计

我目前就是这么干的，但得把响应设置成默认才行好像，只有默认，拦截的时候才会按hosts响应如果对应规则是一条hosts的话，不然就只会按照设置的值响应，但默认值拦截的话被非hosts拦截的域名浏览器会报没解析，不知道什么情况

**Comment by cxw620** [comment]
> > 曲线救国的话,ADH也支持host类型的广告拦截规则,做成广告拦截的订阅列表可作权宜之计
> 
> 我目前就是这么干的，但得把响应设置成默认才行好像，只有默认，拦截的时候才会按hosts响应如果对应规则是一条hosts的话，不然就只会按照设置的值响应，但默认值拦截的话被非hosts拦截的域名浏览器会报没解析，不知道什么情况

本地查看能成功返回默认的0.0.0.0,难道浏览器认为0.0.0.0就是nxdomain?

**Comment by BA7JCM** [comment]
> > > 曲线救国的话,ADH也支持host类型的广告拦截规则,做成广告拦截的订阅列表可作权宜之计
> > 
> > 
> > 我目前就是这么干的，但得把响应设置成默认才行好像，只有默认，拦截的时候才会按hosts响应如果对应规则是一条hosts的话，不然就只会按照设置的值响应，但默认值拦截的话被非hosts拦截的域名浏览器会报没解析，不知道什么情况
> 
> 本地查看能成功返回默认的0.0.0.0,难道浏览器认为0.0.0.0就是nxdomain?

选返回拒绝，浏览器也报nxdomain，搞不懂，看查询日志里面它说它返回的拒绝，感觉不管设置什么拦截响应，只要不是默认的里面按hosts响应的，被拦截之后浏览器都会报没解析，另外一些新域名，浏览器也非常喜欢把nxdomain的响应缓存下来，而adgh有时候长时间没请求过一个域名的时候的第一个请求，浏览器也是报没有解析的，新域名+adgh的这个问题+浏览器喜欢缓存nxdomain=部分新域名一会有解析一会没解析，没解析的时候除非去清除浏览器的dns缓存或者等浏览器的dns缓存过期，不然怎么刷新都是nxdomain

**Comment by BA7JCM** [comment]
> @BA7JCM, hello. Currently, the only way to make AGH respond with IPs from the hosts-style filter list is to use the operating system's hosts file (e.g. `/etc/hosts`) or to use the **default blocking mode**. If I understood it correctly, your browser can't deal with `0.0.0.0`? What exactly happening?

It's not just 0.0.0.0. When I choose "Refused", the browser also reports nxdomain,and the "system's hosts file",you mean to run the hosts file on the AGH server or the hosts file of the client device?

**Comment by BA7JCM** [comment]
> @BA7JCM, hello. Currently, the only way to make AGH respond with IPs from the hosts-style filter list is to use the operating system's hosts file (e.g. `/etc/hosts`) or to use the **default blocking mode**. If I understood it correctly, your browser can't deal with `0.0.0.0`? What exactly happening?

I tried to visit 0.0.0.0, browser report ERR_ADDRESS_INVALID

**Comment by BA7JCM** [comment]
> Domains blocked by non-hosts-style rules in the mode are turning into `0.0.0.0` which is an unspecified IP address pointing to nowhere. Again, what is the exact issue this address causes with the browser?

I don't know, no matter whether I choose "default" or "REFUSED", the domain name blocked by agh will be reported by the browser as nxdomain. At the beginning, "ERR_ADDRESS_INVALID" can still be displayed normally, but I don't know why it becomes nxdomain later. span

**Comment by BA7JCM** [comment]
> @BA7JCM, yeah, I mean the `/etc/hosts` file on the AGH's host machine. AGH dynamically refreshes the list from it so you may update it while AGH is running.
> 
> However, the hosts-style blocklists are performing domain substitution in **default blocking mode**: <img alt="image" width="1427" src="https://user-images.githubusercontent.com/38542664/166976277-8abc0277-93e7-4a94-8f74-cb269049eb11.png"> Domains blocked by non-hosts-style rules in the mode are turning into `0.0.0.0` which is an unspecified IP address pointing to nowhere. Again, what is the exact issue this address causes with the browser?

![image](https://user-images.githubusercontent.com/79561519/167066435-fad9c1ff-e386-40ac-bdd1-d8ddfd2eb0b6.png)
Why does it return here 0.0.0.0 instead of the value in hosts,hosts file link : https://raw.githubusercontent.com/jianboy/github-host/master/hosts

**Comment by EugeneOne1** [comment]
@BA7JCM, it seems the list only contains an IPv6 for the checked host, no IPv4.  This is why host is considered blocked and rewritten with `0.0.0.0`.  Some IPv4 address should be specified to be returned for `A` request.

**Comment by BA7JCM** [comment]
> @BA7JCM, it seems the list only contains an IPv6 for the checked host, no IPv4. This is why host is considered blocked and rewritten with `0.0.0.0`. Some IPv4 address should be specified to be returned for `A` request.

Now I can only use the shell script to regularly obtain this hosts file and delete the ipv6 address and write it to the hosts, because the places where I am often active must also have ipv4, but the places with ipv4 may not necessarily have ipv4. ipv6, I can only sacrifice ipv6 in exchange for compatibility, I don't know if there is any good solution

**Comment by EugeneOne1** [comment]
@BA7JCM, hello again.  Currently it's not possible to rewrite IP addresses with an absent protocol from hosts-styled rules.  If you'd like to forward these requests to an upstream server, it'd be better to reflect all single-family rules in a custom list.  

For example, if you have an IPv4 (`A` request type) rule for `example.com`:
```none
1.2.3.4 example.com
```
You may forward IPv6 (`AAAA`) requests to an upstream with:
```none
@@|example.com^$dnstype=AAAA
```
And vice versa.  If that helped?

**Comment by BA7JCM** [comment]
> @BA7JCM, hello again. Currently it's not possible to rewrite IP addresses with an absent protocol from hosts-styled rules. If you'd like to forward these requests to an upstream server, it'd be better to reflect all single-family rules in a custom list.
> 
> For example, if you have an IPv4 (`A` request type) rule for `example.com`:
> 
> ```
> 1.2.3.4 example.com
> ```
> 
> You may forward IPv6 (`AAAA`) requests to an upstream with:
> 
> ```
> @@|example.com^$dnstype=AAAA
> ```
> 
> And vice versa. If that helped?

So how do I specify that the ipv6 of some specific domain names use specific dns for parsing, for example, I want to pass the ipv6 record of the domain name of jsdeliver to the dns server 2001:da8::666 for parsing

**Comment by EugeneOne1** [comment]
@BA7JCM, unfortunately this isn't implemented currently, but we already have a feature request for this (#4489).  Please consider upvoting it.  I'll close this issue if you don't mind.
