### ISSUE TITLE
针对响应时长进行阈值告警，并记录，以便管理员进行优化。

### ISSUE THREAD

**Issue by Somalia0932** [AdguardTeam/AdGuardHome#4546]
Response details
Status
Processed
DNS server
192.168.10.10:53
Elapsed
10000 ms
Response code
NOERROR

比如设置设置阈值超过200ms，就记录该域名。
![image](https://user-images.githubusercontent.com/42663232/166393611-9f0384f0-4c07-4094-81c1-57a8f5795fa0.png)

**Comment by LinEvil** [comment]
那你要怎么优化

**Comment by cxw620** [comment]
> Apologies for the late response. If you want per-upstream statistics, it's feature request #2013. Did I understand the feature request correctly?

[Somalia0932](https://github.com/Somalia0932) wants to record some domain names that take too long to resolve, requests #2013 is basically consistent with his request in this issue

**Comment by ainar-g** [comment]
@cxw620, thank you for the additional context.  I'll merge this issue into that one then.
