### ISSUE TITLE
Hey we Need UserManager and Ldpa

### ISSUE THREAD

**Issue by v4rrimka-san** [AdguardTeam/AdGuardHome#4547]
Hey, first my english is not the Best please not judging.

I love AGH, I installed it on my pfsense so I wanted to change my pwd but no other hash compared to the original wants to work.
yes this is a Bug i think, but not that is my request

I would like a user manager and an ldap backend for AGH, that would be great
A plugin for PFsense would be better than OPNsense, but that's not important to me

**Comment by ainar-g** [comment]
We have a [Wiki article][1] about changing the web password, and the v0.108.0 release should allow you to do that from the Web UI.

LDAP support is #3187, so I'll merge this issue into that one.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset
