### ISSUE TITLE
Adguard DNS Issues when using Adguard DHCP and configuring Hostname in Static Lease

### ISSUE THREAD

**Issue by ElGranPepo** [AdguardTeam/AdGuardHome#4549]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed

### Issue Details

When configuring a DHCP static lease (mac 00:00:00:00:00:00 IP 182.168.1.5 Hostname LocalDevice) i am unable to ping or NS lookup using hostname 

* **Version of AdGuard Home server:**
  *  v0.107.6
* **How did you install AdGuard Home:**
  *  Home Assistant (Docker)
* **How did you setup DNS configuration:**
  *  Using Adguard DNS
* **If it's a router or IoT, please write device model:**
  *  Windows PC running Debian used specifically for Home Assistant
* **CPU architecture:**
  *  AMD64
* **Operating system and version:**
  *  Debian 5.10.46-5

### Expected Behavior
 Ping LocalDevice should resolve to 192.168.1.5

### Actual Behavior
 Receive error  ping: LocalDevice: Name or service not known
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@ElGranPepo, hello.  To configure a static lease you'll need to specify the real MAC address of the device.  It won't receive the lease otherwise.  If that worked?

**Comment by ElGranPepo** [comment]
Correct I have about 25 devices added in my DHCP reservations list, all with correct Mac addresses and !Ps

example was given

**Comment by ElGranPepo** [comment]
devices are not responding either with .lan or without.  devices are correctly connecting to internet and are receiving filtering.

**Comment by EugeneOne1** [comment]
How exactly do you perform a lookup for the devices?  Could you please provide a `dig`/`nslookup` command?  Also, how does query log shows these requests?

**Comment by ElGranPepo** [comment]
![image](https://user-images.githubusercontent.com/60438864/166945349-20bbc5c8-5b16-41d2-a377-29999352fbd1.png)

**Comment by EugeneOne1** [comment]
@ElGranPepo, thanks for the details.  AGH should respond for `*.lan` with `NXDOMAIN` in three cases:

 1. the AGH's DHCP server is disabled and the upstream responds with `NXDOMAIN`;
 1. the requestor's IP address isn't within the private range ([RFC 6303](https://datatracker.ietf.org/doc/html/rfc6303)).  If you have custom `dns.private_networks`, please insure your requesting machine is within at least one of those;
 1. the hostname isn't leased by AGH.

If all of the above is true then could you please collect [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  Possibly with a couple of similar requests performed.  Thanks.

**Comment by ElGranPepo** [comment]
So in my case:

1. AGH's DHCP is enabled
2. my address is 10.1.x so I think im good here
3. confirming what this means.  if the hostname is being provided by the DHCP server as part of a reservation doe that invalidate it?

**Comment by EugeneOne1** [comment]
@ElGranPepo, so, I think, we'll need you to collect the log.  You may send it to devteam@adguard.com with the issue number in the subject.
