### ISSUE TITLE
Allow IP or Hosts to be hidden from Logs

### ISSUE THREAD

**Issue by michaelr0** [AdguardTeam/AdGuardHome#4551]
Hi There,

I'm using AdGuard Home on OpenWrt.

My config is as follows.

DHCP hands out OpenWrt IP address as DNS, AdGuard is running on this device (OpenWrt has been configured to provide DNS on port 5353 and AdGuard uses port 53)

OpenWrt's DNS is used for local hostname resolution, but the DNS server on port 5353 also uses Quad 9 for upstream resolution.

AdGuard uses Quad 9 for upstream and directs the request to port 5353 if it needs to resolve a local address or PTR.

However I'm noticing that there are a bunch of requests appearing in the logs from localhost.
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/54159303/167064991-d46298d2-4606-4f6a-8626-70e845212a7b.png">

Is it possible to hide these from the logs, so that DNS resolution from localhost can still use AdGuard and function as expected, but I'm not interested in seeing the logs for localhost.

Thanks.

**Comment by EugeneOne1** [comment]
@michaelr0, hello.  What version of AdGuardHome are you using?  Looks like [#3157](https://github.com/AdguardTeam/AdGuardHome/issues/3157).

**Comment by EugeneOne1** [comment]
@michaelr0, could you please check it on the latest edge or beta build?  The mentioned issue is a part of the **v0.107.7** milestone so there are no stable releases with the fix yet.

**Comment by michaelr0** [comment]
> @michaelr0, could you please check it on the latest edge or beta build? The mentioned issue is a part of the **v0.107.7** milestone so there are no stable releases with the fix yet.
> 
> Consider also making a backup of the `AdGuardHome.yaml` file and of the `data` directory.

Hi @EugeneOne1,

Thanks, I have tried https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv7.tar.gz and https://static.adguard.com/adguardhome/beta/AdGuardHome_linux_armv7.tar.gz

Both of these result in `AdGuardHome --version
./AdGuardHome/AdGuardHome: line 1: syntax error: unexpected word (expecting ")"` when trying to run.

**Comment by ainar-g** [comment]
@michaelr0, that is a very weird looking command.  `./AdGuardHome/AdGuardHome` must not be an argument to `AdGuardHome`.

**Comment by michaelr0** [comment]
> @michaelr0, that is a very weird looking command.  `./AdGuardHome/AdGuardHome` must not be an argument to `AdGuardHome`.

That is just me running AdGuardHome from a folder called AdGuardHome, it didn't matter what parameters I did or did not pass, the result was the same error message.

Thanks

**Comment by EugeneOne1** [comment]
@michaelr0, this error indicates that the binary is built for another CPU architecture.  You may get the appropriate architecture from the `uname -m` command output and find it [here](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms#releases) afterwards.

Note that the output of `uname -m` may differ so you may need to match the one in the following table:

| AMD64 | x86 | 64-bit ARM | ARMv5 | ARMv6 | ARMv7 | 64-bit MIPS (LE) | 32-bit MIPS (LE) |
|-|-|-|-|-|-|-|-|
| `x86_64`, `x86-64`, `x64`, `amd64` | `i386`, `i486`, `i686`, `i786`, `x86` | `armv5l` | `armv6l` | `armv7l`, `armv8l` | `aarch64`, `arm64` | `mips64` | `mips`|

Are my instructions clear enough?  Thanks.

**Comment by michaelr0** [comment]
Hi @EugeneOne1, thanks for that table.

However I'm using a Raspberry Pi 4 Model B, which reports:
```bash
root@OpenWrt:~# uname -m
aarch64
root@OpenWrt:~#
```

So based on that table I'd use https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv7.tar.gz however as noted above that is one of the downloads that gives me issues.

**Comment by michaelr0** [comment]
> Hi @EugeneOne1, thanks for that table.
> 
> However I'm using a Raspberry Pi 4 Model B, which reports:
> 
> ```shell
> root@OpenWrt:~# uname -m
> aarch64
> root@OpenWrt:~#
> ```
> 
> So based on that table I'd use https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_armv7.tar.gz however as noted above that is one of the downloads that gives me issues.

Interesting, It looks like this is the correct one (arm64 instead of armv7, which suggests that 64bit arm or arm64 is not armv5), https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_arm64.tar.gz

**Comment by EugeneOne1** [comment]
@michaelr0, you're absolutely right, I've just confused you with the wrong column order, sorry about that.  It should be correct now.  And `arm64` is indeed a correct build for `aarch64`.

**Comment by michaelr0** [comment]
Thanks, I can now run the beta and it looks like the pending milestone has it resolved.
