### ISSUE TITLE
Enable Safe Search, but keep full access to google

### ISSUE THREAD

**Issue by Cliffback** [AdguardTeam/AdGuardHome#4556]
When I enable Use Safe Search, it also blocks YouTube videos (not all, but a lot), and I would like an option to keep full access to google, while still enforcing safe search, if that is possible.

**Comment by dioey** [comment]
you can do it but first you need to tag user client, for example for regular client i add user_regular tag, and if for admin who can bypass safe search and other i add admin tag, this the list i add for google safe search and other except youtube. https://raw.githubusercontent.com/dioey/AdGuard/main/Google%20Safe%20Search you can add this on filter dns blocklist, but you need tag client first before adding that rule

**Comment by Cliffback** [comment]
> you can do it but first you need to tag user client, for example for regular client i add user_regular tag, and if for admin who can bypass safe search and other i add admin tag, this the list i add for google safe search and other except youtube. https://raw.githubusercontent.com/dioey/AdGuard/main/Google%20Safe%20Search you can add this on filter dns blocklist, but you need tag client first before adding that rule

Thanks for the reply! So let's say I wanted this for all users, could I just add your list, but remove ctag=user_regular from each line?

Also, if I want to do it your way by using client tags, is it possible to set user_regular for all users except the ones that I set to admin?
