### ISSUE TITLE
Statistics by user's time zone

### ISSUE THREAD

**Issue by Suansuan-Keai** [AdguardTeam/AdGuardHome#4560]
![Snipaste_2022-05-08_08-10-40](https://user-images.githubusercontent.com/69025582/167276238-271f108b-736a-4944-a3ca-a52fafc002b9.png)
My server is using the UTC+8 time zone. Bue the Statistics of new day's querise won't appear until it's 8 o'clock of my local time.
Could tell me whether it is caused by my settings or the AdGuardHome ?

**Comment by Suansuan-Keai** [comment]
> The UI uses your browser's time zone. Or do you mean something else by “won't appear”?

Could you tell me how to check my broser's time zone?

**Comment by Suansuan-Keai** [comment]
All data will be counted, but my local time zone is East 8, so the data from 0:00 to 8:00 in the morning will be counted to the previous day.

**Comment by ainar-g** [comment]
@Suansuan-Keai, you can use https://webbrowsertools.com/timezone/.  Or look at the _Query log_ page of AGH to see, which time is shown for the latest entries.

**Comment by Suansuan-Keai** [comment]
> @Suansuan-Keai, you can use https://webbrowsertools.com/timezone/. Or look at the _Query log_ page of AGH to see, which time is shown for the latest entries.

![Snipaste_2022-05-12_22-40-45](https://user-images.githubusercontent.com/69025582/168101794-e0610d96-bf74-4c0d-8aa0-5628c81d377f.png)
![Snipaste_2022-05-12_22-41-08](https://user-images.githubusercontent.com/69025582/168101843-0610bc1d-a597-4863-844d-d24631d62eef.png)
It seems that the time zone is correct.

**Comment by ainar-g** [comment]
I remember now.  This is #4434.  Weirdly, that issue did not get assigned a milestone.  I'll merge this issue into that one, and we'll try to fix this in v0.107.7 if we're able to do so.

**Comment by Suansuan-Keai** [comment]
I see. Thank you for your work!
________________________________
发件人: Ainar Garipov ***@***.***>
发送时间: 2022年5月12日 22:58
收件人: AdguardTeam/AdGuardHome ***@***.***>
抄送: 酸酸 ***@***.***>; Mention ***@***.***>
主题: Re: [AdguardTeam/AdGuardHome] Statistics by user's time zone (Issue #4560)


I remember now. This is #4434<https://github.com/AdguardTeam/AdGuardHome/issues/4434>. Weirdly, that issue did not get assigned a milestone. I'll merge this issue into that one, and we'll try to fix this in v0.107.7 if we're able to do so.

―
