### ISSUE TITLE
Turn Off filtering for single client not working

### ISSUE THREAD

**Issue by Mastahh** [AdguardTeam/AdGuardHome#4561]
Hello,
I installed AdGuardHome on OpenWrt
Version: v0.107.5
I configured in service to block only YouTube, and it is blocking it.
Now I want to enable it to only one to machine with IP 192.168.1.100 
I tried client settings - not working.
Custom filtering also not working **@@||*^$client=192.168.1.100**

**Comment by Mastahh** [comment]
I did following settings
![image](https://user-images.githubusercontent.com/10340023/168492768-eb2fb9b9-c81b-428a-98cf-a033b5dfcd2d.png)
![image](https://user-images.githubusercontent.com/10340023/168492799-1f84afbb-55bc-45eb-b848-9729a9fc482d.png)
Youtube service also unchecked, i clicked Unblock All

Upstream tab is empty, I expect that it will use upstream DNS (Openwrt:5353), without any filterings
Did: .>>>service adguardhome restart
ipconfig /flushdns

still have

Non-authoritative answer:
Name:    www.youtube.com.lan
Addresses:  ::
          0.0.0.0

**Comment by Mastahh** [comment]
I think that i need use both IPv4 and IPv6 addresses to unblock specific clients

**Comment by ainar-g** [comment]
@Mastahh, yes, you should use the IP address that your client actually sends queries from.  When using DoH, DoQ, or DoT, you can also use a [ClientID][1].

Is your issue fixed now?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid

**Comment by EugeneOne1** [comment]
@Mastahh, we'll close the issue for now if you don't mind.
