### ISSUE TITLE
Default Dns not provided with ip Settings

### ISSUE THREAD

**Issue by Mastahh** [AdguardTeam/AdGuardHome#4562]
Hello,

I installed AGH on openwrt, and i have issue with nslookup on my work pc.
It have own list if DNS servers defined by names. It was working good till i installed AGH.
On my personal pc all works, but work pc always tries to use different server if I use NsLookup.

Is it issue with AGH or something wrong configured in Openwrt?

AGH works on 53 port and OpenWrtDNS on 5353 port
Just disabled AGH and all started working.

NSLookup

![image](https://user-images.githubusercontent.com/10340023/167780357-5d64a3b6-c2fc-46d8-9ff2-a1f9432b7be6.png)

**Comment by EugeneOne1** [comment]
@Mastahh, hello.  A few questions to clarify the problem:
 1. How do your devices receive the DNS configuration?  Do you use the AGH's DHCP or the OpenWrt's one?
 2. What version of AGH are you using?

**Comment by Mastahh** [comment]
> @Mastahh, hello. A few questions to clarify the problem:
> 
>     1. How do your devices receive the DNS configuration?  Do you use the AGH's DHCP or the OpenWrt's one?
> 
>     2. What version of AGH are you using?

Hello.
1. DHCP on OpenWRT
2. Version: v0.107.5

**Comment by EugeneOne1** [comment]
@Mastahh, I see.  Which DNS addresses does OpenWrt's DHCP propagate via leases, especially the "work pc"?  Also, what is the current DNS configuration on "work pc"?

Note that it's recommended to use two identical addresses of the same machine in DHCP leases to enforce the device to only use the ones.

**Comment by Mastahh** [comment]
Hm, just enabled all back again and it is working.
I did

OpenWRT changed port for DNS to 5353
Enable AdGuardHome Service, DNS working on port 53
Started AdGuardHome Service

At the moment cannot reproduce this issue :(

**Comment by EugeneOne1** [comment]
@Mastahh, well, I'll close the issue for now if you don't mind.  Please consider reopening the issue if it will occur again.  Thanks.
