### ISSUE TITLE
DNS blackhole, WIFI to cellular, AdGuard Pro v4.4.0 iOS

### ISSUE THREAD

**Issue by antplus** [AdguardTeam/AdGuardHome#4566]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

**### Issue Details**

I was eagerly awaiting the new release so the issue with DNS queries being blackholed after moving from WIFI to cellular.  I'm sad to report that after moving to the latest version the issue exists.  No amount of toggling airplane mode or AdGuard DNS protection will restore the service.  I have thoroughly tested AdGuard Pro with both AdGuard VPN and ProtonVPN, the result is the same, DNS queries are not completed after the phone moves from Cellular to WIFI. 

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Expected Behavior
I expect AdGuard to continue to resolve DNS queries after moving from WIFI to cellular.

### Actual Behavior
AdGuard Pro does not resolve DNS queries when moving from WIFI to cellular. 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information
Can you please shed some light on the test cases you ran when you advised the issue was resolved in v4.4.0?  Was a VPN in use?  What other test conditions were used to call this update a success?

**Comment by EugeneOne1** [comment]
@antplus, closing the issue since it isn't related to the AdGuard Home.
