### ISSUE TITLE
Can't open WiFi Login Portal while using AdGuard Home

### ISSUE THREAD

**Issue by PaperCutBad** [AdguardTeam/AdGuardHome#4567]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.107.6
* **How did you install AdGuard Home:**
  * Installed as service on Windows
* **How did you setup DNS configuration:**
  * NextDNS as upstream DNS and using 127.0.0.1 and ::1 in adapter options.
* **If it's a router or IoT, please write device model:**
  * No
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 10 21H2

### Expected Behavior
When connecting to campus WiFi login portal should open.

### Actual Behavior
 Login portal doesn't open, shows DNS error. Using automatic DNS/disabling AdGuard Home opens up login portal.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@PaperCutBad, hello and thanks for the report.  How does these queries appear in the query log?  Are they blocked or even processed?

If so, could you please configure the AGH to collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and reproduce the issue?  Then send the log file to the devteam@adguard.com along with the issue number in the subject.  Thanks.

**Comment by PaperCutBad** [comment]
> @PaperCutBad, hello and thanks for the report. How does these queries appear in the query log? Are they blocked or even processed?
> 
> If so, could you please configure the AGH to collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and reproduce the issue? Then send the log file to the [devteam@adguard.com](mailto:devteam@adguard.com) along with the issue number in the subject. Thanks.


> @PaperCutBad, additionally, is the WiFi login portal on an IP address or a domain name? Because if it's the latter, you'll need to [set the previous default WiFi DNS upstream for that domain name](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains).


Queries don't appear in query log so I don't think they are processed. Also login portal is on an IP Address. Sending verbose log now. Thanks

**Comment by PaperCutBad** [comment]
> If so, could you please configure the AGH to collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and reproduce the issue? Then send the log file to the [devteam@adguard.com](mailto:devteam@adguard.com) along with the issue number in the subject. Thanks.

I reproduced issue many times many time but verbose file is still empty. No logs. But still can't open LogIn portal. Will try with fresh installation.
Thanks.

**Comment by mercyground** [comment]
If you are using a different upstream for your DNS then you wont get the redirection from the wifi dns to the portal. The wifi portal is internal to the network and thus not known to your AGH or the upstream DNS. You have to ensure the wifi dns is included in the search for this to work.
