### ISSUE TITLE
Issue of performance of application in container

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#4568]
Hello,

I have a problem with the performance of the Docker application in container. When I add my lists, the container falls, although without using container, the AGH works stable. The logs is here:
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/8694733/log.txt)

and screenshots too:
![2022-05-15_13-25-26](https://user-images.githubusercontent.com/45385632/168468221-84214a4c-3e00-4bed-b3b3-d52fe061a885.png)

This loading never ends and will be infinite🤨 Here is log of Docker (daemon.log):
![2022-05-15_13-25-38](https://user-images.githubusercontent.com/45385632/168468223-4bf01258-948a-40ca-808a-4a769f86471e.png)

And OOMKilled status is false:
![image](https://user-images.githubusercontent.com/45385632/168468340-10460c51-bbfe-44af-b169-60064ad2637c.png)

Docker Compose file is here:
https://gist.github.com/ammnt/0f00f024dbbd9ce2ed8ff339ac759ac1

I tried to increase the amount of resources, but it did not give the desired result. I also tried to use Docker Swarm cluster to resolve this issue, but no success too. I will be grateful to any advice😋

Thank you.
Best regards.

**Comment by EugeneOne1** [comment]
@ammnt, hello and apologies for the late response.  Could you please answer a couple of questions:

  * How many filter lists have you got configured and how many rules each has?  Could you please try to run it with some significantly smaller payload, a single default filter list for example?
  * How much memory AGH uses outside the container?
  * What are the restrictions for the AGH's container?  Note that filter updating process requires about a half of all lists size additionally.

The log file looks like an OOM may indeed happen.

**Comment by ammnt** [comment]
@EugeneOne1, I'm sorry but I don't have access to this setup anymore. Please forget about it. Thanks for your response anyway🙂

**Comment by EugeneOne1** [comment]
@ammnt, please feel free to reopen it along with the requested info if the issue reoccurs.  Thanks.
