### ISSUE TITLE
Can blocked request TTL setting be exposed in web gui? 

### ISSUE THREAD

**Issue by gbtota** [AdguardTeam/AdGuardHome#4569]
I would like to control the blocked request TTL value from the gui; i can always flush DNS caches during configuration.

I read that this can be controlled with yaml config but that not convenient.

**Comment by ainar-g** [comment]
@ameshkov, what do you think?

**Comment by ameshkov** [comment]
Yeah, why not

**Comment by ainar-g** [comment]
This will be released in the upcoming v0.107.39.
