### ISSUE TITLE
can it respond not found on given url?

### ISSUE THREAD

**Issue by zhang0peter** [AdguardTeam/AdGuardHome#457]
i use it on a router to connect to my school network.
i need to access school-internal network, which can only access by Intranet .
but these websites's domains also have their address records on outer DNS server like 8.8.8.8, but those records are useless because these  records are wrong, and no one can access these websites outside the school!
So i want AdGuardHome to respond no such dns record found if i query url like xxx.xxx.edu .
and my computer will turn to another dns server to query, and the problem can be solved.

**Comment by ameshkov** [comment]
What you want will be possible when we implement #445
