### ISSUE TITLE
Firefox "security.sandbox.content.win32k-disable=true" crashes AGH login page

### ISSUE THREAD

**Issue by OpenSourceGhost** [AdguardTeam/AdGuardHome#4572]
When "security.sandbox.content.win32k-disable" is set to "true" in Firefox ESR 91.9 "about:config", AGH login page crashes. AGH is running on Raspberry Pi 4 (Bullseye 64bit). Firefox is running on Windows 10 (21H2 x64).

**Comment by ainar-g** [comment]
What do you mean by “login page crashes”?  Does it not load at all or does it load, but only partially?  A screenshot as well as the contents of the browser console would be really appreciated.

**Comment by OpenSourceGhost** [comment]
It takes me to Firefox crash reporter page after accepting (self-generated) HTTPS certificate. It is probably a Firefox issue, not AGH issue because "Win32 Lockdown" is mentioned in release notes for Firefox 100.1 - https://www.mozilla.org/en-US/firefox/100.0.1/releasenotes/ .  I think "security.sandbox.content.win32k-disable" is broken prior to version 100.1.

**Comment by ainar-g** [comment]
I see.  Shall I close this issue then?

**Comment by OpenSourceGhost** [comment]
I think so :)
