### ISSUE TITLE
不能使用DNS-over-TLS

### ISSUE THREAD

**Issue by ixcm-winlog** [AdguardTeam/AdGuardHome#4574]
v0.107.6 已经正确配置证书，853端口开放，使用android私人DNS测速无法连接，经过测试android系统无问题
使用nmap扫描udp，853端口未开放
（853/udp closed unknown）
防火墙已关闭

**Comment by ainar-g** [comment]
@ixcm-winlog, you have reopened the issue.  Is there any new data?  Also, please fill out the whole issue template.

**Comment by cxw620** [comment]
> v0.107.6 已经正确配置证书，853端口开放，使用android私人DNS测速无法连接，经过测试android系统无问题 使用nmap扫描udp，853端口未开放 （853/udp closed unknown） 防火墙已关闭

国内机器检查一下安全组有没有开放853UDP, 国外机器有可能是阻断了.

**Comment by liwenjie119** [comment]
如果是国内机器请注意检查家长控制和浏览安全需要关闭，因为国内不好连到官方的检查服务器

**Comment by ixcm-winlog** [comment]
为了排除端口问题在内网进行测试了一下，依然提示无法连接。
