### ISSUE TITLE
AdGuardHome - failed to connect on first setup

### ISSUE THREAD

**Issue by guidokieboom** [AdguardTeam/AdGuardHome#4577]
Tried to to first install via HA Settings, Addons, Add, Search
At first screen of the setup I get stuck. I have a basic HA installation on Raspberry PI4.
I've tried various options (with and without the SSL options, port 80, port 3000, turning off MFA.
I have all latest versions of HA: OS8.1 | Core 2022.5.5
I keep getting back to this screen:
Can you advise what to fill in?

<img width="389" alt="Screenshot 2022-05-21 at 09 06 55" src="https://user-images.githubusercontent.com/65387179/169641201-ceb1344c-80c9-407f-8318-2f46d8ee828f.png">

**Comment by ainar-g** [comment]
Hello.  This doesn't look like the default AdGuard Home login form.  Please send issue reports with the HomeAssistant plugin to the [developers of the plugin][1].  Thanks.

[1]: https://github.com/hassio-addons/addon-adguard-home
