### ISSUE TITLE
有没有大老帮我看看。我实在没有办法了

### ISSUE THREAD

**Issue by gsxzn163** [AdguardTeam/AdGuardHome#4579]
<!DOCTYPE html><p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; caret-color: rgb(240, 246, 252); color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">OpenWrt R22.4.1 GDQ Spring[2022] by eSir / LuCI Master (git-22.103.65959-d9db1b0)是openwrt的版本。</font></font></p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(240, 246, 252); color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">本地版本：.，云版本：v0.10.6.这个是我的内核。</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">下边有显示更新成功。</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">更新核心...</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">收集到的错误：</font></font></p><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(240, 246, 252); color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><li style="box-sizing: border-box; margin-left: 0px;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">opkg_conf_parse_file: /etc/opkg.conf:5: 忽略无效行：`opkg install adguardhome'</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">开始下载</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">--2022-05-22 05:36:45--<span class="Apple-converted-space"> </span></font></font><a href="https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.6/AdGuardHome_linux_amd64.tar.gz" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">https://github.com/AdguardTeam/AdGuardHome/releases/下载/v0.107.6/AdGuardHome_linux_amd64.tar.gz 13.3M</font></font></a><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">0s<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">10650K ......................................................................................... ..................................... 99% 44.9M 0s<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">10700K ......................... 100% 58.1M=0.8s<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">2022-05-22 05： 36:47 (13.2 MB/s) - '/tmp/AdGuardHomeupdate/AdGuardHome_linux_amd64.tar.gz' 保存 [10972388/10972388]</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">下载成功 start copy<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">start copy<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">awk: /etc/AdGuardHome.yaml: No such file or directory<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">AdGuardHome turn关闭</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">启用=1</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">rm: can't remove '/usr/bin/AdGuardHome/AdGuardHome': No such file or directory<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">mv: write error: No space left on device<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">mv failed 也许空间不足 请使用 upx 或将 bin 更改为 /tmp/<span class="Apple-converted-space"> </span></font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">AdGuardHome是显示更新了，</font></font></li></ul><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(240, 246, 252); color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">这是我的usr/bin/AdGuardHome/AdGuardHome执行路径</font></font></p>

名称 | 版本
-- | --
除去 | adguardhome
除去 | luci-app-adguardhome

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; caret-color: rgb(240, 246, 252); color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">家庭名称更新办法</font></font><br style="box-sizing: border-box;"><a href="http://192.168.5.1/cgi-bin/luci/admin/system/packages#" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">移除</font></font></a><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;"><span class="Apple-converted-space"> </span>adguardhome 0.1076-1</font></font><br style="box-sizing: border-box;"><a href="http://192.168.5.1/cgi-bin/luci/admin/system/packages#" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">移除</font></font></a><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;"><span class="Apple-converted-space"> </span>luci-app-ad 1.8-9我在</font></font><br style="box-sizing: border-box;"><font style="box-sizing: border-box; vertical-align: inherit;"><font style="box-sizing: border-box; vertical-align: inherit;">网上把的试管结束了一个晚上没有成功</font></font></p>OpenWrt R22.4.1 GDQ Spring[2022] by eSir / LuCI Master (git-22.103.65959-d9db1b0)是openwrt的版本。

本地版本：.，云版本：v0.10.6.这个是我的内核。
下边有显示更新成功。
更新核心...
收集到的错误：

opkg_conf_parse_file: /etc/opkg.conf:5: 忽略无效行：`opkg install adguardhome'
开始下载
--2022-05-22 05:36:45-- [https://github.com/AdguardTeam/AdGuardHome/releases/下载/v0.107.6/AdGuardHome_linux_amd64.tar.gz 13.3M](https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.6/AdGuardHome_linux_amd64.tar.gz)
0s 
10650K ......................................................................................... ..................................... 99% 44.9M 0s 
10700K ......................... 100% 58.1M=0.8s 
2022-05-22 05： 36:47 (13.2 MB/s) - '/tmp/AdGuardHomeupdate/AdGuardHome_linux_amd64.tar.gz' 保存 [10972388/10972388]
下载成功 start copy 
start copy 
awk: /etc/AdGuardHome.yaml: No such file or directory 
AdGuardHome turn关闭
启用=1
rm: can't remove '/usr/bin/AdGuardHome/AdGuardHome': No such file or directory 
mv: write error: No space left on device 
mv failed 也许空间不足 请使用 upx 或将 bin 更改为 /tmp/ 
AdGuardHome是显示更新了，
这是我的usr/bin/AdGuardHome/AdGuardHome执行路径

名称	版本
除去	adguardhome
除去	luci-app-adguardhome
家庭名称更新办法
[移除](http://192.168.5.1/cgi-bin/luci/admin/system/packages#) adguardhome 0.1076-1
[移除](http://192.168.5.1/cgi-bin/luci/admin/system/packages#) luci-app-ad 1.8-9我在
网上把的试管结束了一个晚上没有成功

**Comment by gsxzn163** [comment]
![Uploading F2A7D2AD-AEDA-488E-AB9F-59162107E08A.png…]()

**Comment by CelicaS** [comment]
别用垃圾魔改版openwrt问题少99%

**Comment by funny-fury** [comment]
`mv: write error: No space left on device`

The storage device has no space, please check the mount point. Or ask the firmware publisher for help.

**Comment by FianW** [comment]
可能是overlay空间不足，adguardhome的日志会占用大量空间，可以试试把日志清空再更新。
打开控制面板，设置，常规设置，最底部两项，点击清除查询日志和清除统计数据即可。
同时建议把这两项的保存时间缩短并定期清理。
