### ISSUE TITLE
Add upstream proxy settings to AdGuard Home

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdGuardHome#458]
Regarding AdGuard Home features, an essential one would be the integration of a proxy (with authentication) into it.

At the very least, as a temporary solution, add an option to mask/randomize the IP address going to the upstream DNS to fetch the website addresses.

**Comment by ameshkov** [comment]
Do you mean an upstream proxy, right?

**Comment by ameshkov** [comment]
This proxy is supposed to be used when AG downloads filters updates, right?

I am not sure using it for anything else would be viable

**Comment by tomiams** [comment]
Yes, that is exactly what it would be used for.
Potentially, when AdGuard Home auto-update (or GUI update) feature is implemented, the update checks and download could be fetched through the proxy as well.

**Comment by ameshkov** [comment]
@tomiams got it. Makes sense indeed

**Comment by hmage** [comment]
@tomiams  While you wait for the GUI, you can already use upstream HTTP proxy by setting the `HTTP_PROXY` environment variable for AdGuardHome:
```
export HTTP_PROXY=http://proxy.lan:3128/
```

or, if there's username and password:
```
export HTTP_PROXY=http://user:password@proxy.lan:3128/
```

**Comment by tomiams** [comment]
@hmage Thank you for the awesome tip! Works really well.

**Comment by desimone** [comment]
Hey AdGuard team (@hmage , @ameshkov)

We recently added a recipe to do just this with Pomerium. Look forward to your thoughts. :) 
https://github.com/pomerium/pomerium/pull/359

**Comment by ameshkov** [comment]
@desimone looks good, thank you!
