### ISSUE TITLE
Query Log - googleadservices.com Allowed by Adguard dns filter

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#4580]
### Prerequisites
-I am running the latest beta version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed

### Issue Details

I don't have any custom filtering rules or any allowlists yet my query log keeps saying googleadservices.com is being allowed by adguard dns filter which is odd because that is a blocklist, not a whitelist.

* **Version of AdGuard Home server:**
  v0.108.0-b.7
* **How did you install AdGuard Home:**
  curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c beta
* **How did you setup DNS configuration:**
 adguard dhcp
* **If it's a router or IoT, please write device model:**
  Pi 0 2 W (running ethernet)
* **CPU architecture:**
  armv8
* **Operating system and version:**
 dietpi v5 beta (not optimized software)

### Expected Behavior
I expect the domain to be blocked, not allowed

### Actual Behavior
googleadservices.com is allowed

### Screenshots
![Capture](https://user-images.githubusercontent.com/89283708/169706652-c636b7de-a1f3-4aad-afe2-80e8491600e9.PNG)

**Comment by funny-fury** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exceptions.txt#L157-L162

see also AdguardTeam/AdGuardSDNSFilter#289 #2583

**Comment by Dynasty-Dev** [comment]
Thank you, still confused on why there are allowed domains on a blocklist. In my opinion  they should be on a separate whitelist file.

**Comment by Dynasty-Dev** [comment]
Guess I will be removing the adguard dns blocklist. Sad, i actually liked it.

**Comment by emlimap** [comment]
You can always override whitelists from blocklists. To counter the whitelist in AdGuard blocklist, you can add the following to custom filtering rules under filter's menu. `$important` modifier will ensure that it takes precedence over any filters from the blocklists you have added.

```
||googleadservices.com^$important
```

If you are interested in the syntax, it is documented here https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists

**Comment by ainar-g** [comment]
Please report the filter list bugs / suggestions to the [filter list repository][1].  Thanks.

[1]: https://github.com/AdguardTeam/AdGuardSDNSFilter

**Comment by wzqvip** [comment]
explained here: https://github.com/hagezi/dns-blocklists#referral
So it's fine to allow this domain by default.
