### ISSUE TITLE
Adguard blocklist selection - Online malicious url blocklist outdated link

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#4581]
The Online malicious url blocklist recently changed its source link, please update. Choosing this will cause an error

**Comment by ppfeufer** [comment]
Here's the new link » https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt

**Comment by funny-fury** [comment]
> https://gitlab.com/malware-filter/urlhaus-filter/-/blob/main/README.md
> 
> Announcement (2022/05/21): curben.gitlab.io has been migrated to malware-filter.gitlab.io

Maybe need to wait until the next release to fix, because it is written in the filters.json file.

https://github.com/AdguardTeam/AdGuardHome/blob/79d85a24e970450767997d2e3a1b1876f652f0f7/client/src/helpers/filters/filters.json#L81-L86

**Comment by Dynasty-Dev** [comment]
How come "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt" has way more malware domains than "https://curben.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt" which is the one currently being used in the new beta and edge releases? They are both for adguard home so why is the one with less domain being used?

**Comment by ainar-g** [comment]
@ameshkov, what do you thing about the suggestion above?  The non-lite version is quite massive, and I'm not sure what the policy is regarding the size of the default filters.

**Comment by ameshkov** [comment]
@ainar-g metadata of this list has been already updated in https://github.com/AdguardTeam/HostlistsRegistry.

I think we'd better implement #3972 sooner and resolve all issues related to lists there instead of doing it in two different places.

**Comment by ainar-g** [comment]
I'll close this issue then.
