### ISSUE TITLE
geoip dns based routing

### ISSUE THREAD

**Issue by CelicaS** [AdguardTeam/AdGuardHome#4583]
- [ √ ] I am running the latest version
- [ √ ] I checked the documentation and found no answer
- [ √ ] I checked to make sure that this issue has not already been filed

### Problem Description

Thanks to the developer
I like the intuitive and beautiful interface and powerful features of AdGuard Home
because of policy
China's dns pollution blocks some websites, such as google, from being able to resolve their correct ip
And 8.8.8.8 or 1.1.1.1 cannot be used in China, and using vpn to parse Chinese websites is slow
Request to increase the routing function based on geoip dns:
For example, for Chinese websites: 223.5.5.5 (Chinese public dns)
For non-Chinese websites: 1.1.1.1or8.8.8.8

### Proposed Solution

geoip dns based routing

### Alternatives Considered

current plan：
AdGuard Home → chinadns-ng (not support DNS over TLS (SSL) or DNS over HTTPS) → https-dns-proxy(
One system runs multiple dns on multiple ports)

chinadns-ng:
https://github.com/zfl9/chinadns-ng

### Additional Information

from google translate

**Comment by ainar-g** [comment]
Merging this into #1487, thanks.
