### ISSUE TITLE
Adguard DHCP server or local REWRITE doesn't work if no internet.

### ISSUE THREAD

**Issue by keshabit** [AdguardTeam/AdGuardHome#4590]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Adguard DHCP server or local REWRITE doesn't work if no internet.

* **Version of AdGuard Home server:**
  * <-- v0.108.0-b.7 -->
* **How did you install AdGuard Home:**
  * <-- GitHub releases -->
* **How did you setup DNS configuration:**
  * <-- System -->
* **If it's a router or IoT, please write device model:**
  * <-- VMWare VM -->
* **CPU architecture:**
  * <-- x86 -->
* **Operating system and version:**
  * <-- Debian 5.10.106-1 -->

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Merging into #4825.
