### ISSUE TITLE
Infinite loop in the query log

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4591]
### Discussed in https://github.com/AdguardTeam/AdGuardHome/discussions/4576

<div type='discussions-op-text'>

<sup>Originally posted by **ElBarto2022** May 19, 2022</sup>
If i try to open the logs of "Blocked adult websites","Blocked malware/phishing" and "rewritten" over the webinterface i only see the circle going round and nothing else. I use the actual version on a pfsense with FreeBSD. (Querylog.json has 24MB, sessions.db has 32KB and stats.db has 64KB)</div>

**Comment by ainar-g** [comment]
@ElBarto2022, the latest edge release should contain a fix for the issue.  Could you please check if it fixes the bug for you as well?

**Comment by ElBarto2022** [comment]
I check it and everything ist working. Thank you!
