### ISSUE TITLE
"Sign Out" button disappeared from GUI

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [AdguardTeam/AdGuardHome#4594]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
Latest 0.108 edge
* **How did you install AdGuard Home:**
SSH command - curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge
* **How did you setup DNS configuration:**
Via AGH wizard. Only local clients can resolve domains via AGH. There is no WAN access. Custom IPTables are created on DNS server to further restrict access to AGH.
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4
* **CPU architecture:**
ARM64
* **Operating system and version:**
Bullseye

### Additional Information

I logged out of AdGuard Home GUI, used HTPassWd.exe to generate new password hash, used OpenSSL (1.1.1o) daemon to generate new self-signed SSL certificate and key, then used PuTTY and WinSCP to:

    Stop AdGuard service
    Paste new SSL certificate and key into appropriate directory
    Open AdGuardHome.yaml
    Paste new B-Crypt hash
    Save & close AdGuardHome.yaml
    Restart AdGuard service
    Restart Raspberry Pi 4

Afterwards I visited AdGuard Home GUI, entered username and new password, which worked, but Sign Out button was no longer there. I ran AGH exclusively for local clients, with GUI access strictly bound to my local IP on management VLAN and secured by custom IPTables. There was no way to access AGH GUI over WAN.

**Comment by ainar-g** [comment]
The _Sign out_ button shouldn't disappear like that, and it sounds like we need to fix that bug.  Are there any errors in the browser console?

As for the question, you can remove `$DATA_DIR/sessions.db` and restart AGH.

**Comment by OpenSourceGhost** [comment]
Forgot to mention that I began having "Network Control" errors after password change, even though the server was resolving domains for all the clients without issues. 

My solution was just to restore Raspberry Pi snapshot and perform the same steps to change my password. That didn't result in any issues.

**Comment by OpenSourceGhost** [comment]
Ever since the last edge build came out earlier today, sessions.db files disappeared completely even after AGH restart and RPi reboot, but login works correctly. I assume the latest update intoruced changes to session cookies?

**Comment by ainar-g** [comment]
Apologies for the very belated response.  I don't think that we introduced any changes back then or later.  Is the issue still occurring?

**Comment by ainar-g** [comment]
Closing since there has been no response.
