### ISSUE TITLE
adgh fills in quic dns upstream cannot be resolved

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#4605]
1. I am running the latest version
Version: v0.108.0-b.8
2. I checked the documentation and found no answer
3. I checked to make sure that this issue has not already been filed
4. CPU architecture
   AMD64
5. Operating system 
   debian 10

###Expected Behavior
The upstream of quic works normally, but the update Version: v0.108.0-b.8 cannot be used

**Comment by thb007** [comment]
When the quic port is non-784 port, the quic of other ports cannot be used

**Comment by ainar-g** [comment]
Please fill out the full template and also add the precise upstream address with which you have issues.  Thanks.

**Comment by thb007** [comment]
For example, upstream DNS
quic://dns-unfiltered.adguard.com:784 works fine,
quic://dns-example.com:8853 Unable to connect

Use dnslookup to test the normal resolution of quic://dns-example.com:8853, adgh prompts whether the filling is wrong

**Comment by thb007** [comment]
Switch AdGuard Home v0.107.6 quic://dns-example.com:8853 to resolve normally

**Comment by ainar-g** [comment]
@thb007, once again, please fill out the full issue template.

Also make sure that your `dns-example.com` is actually resolvable by the bootstrap DNS servers.

**Comment by thb007** [comment]
> dns-example.com
I need to hide some specific parts of quic, otherwise it will be used illegally, I will send the log to your support mailbox

**Comment by thb007** [comment]
> @thb007, once again, please fill out the full issue template.
> 
> Also make sure that your `dns-example.com` is actually resolvable by the bootstrap DNS servers.

Can you check both mailboxes? I have sent logs to these 2 mailboxes. AdGuardHome@noreply.github.com/support@adguard.com

**Comment by ainar-g** [comment]
@thb007, the correct E-Mail is [devteam@adguard.com](mailto:devteam@adguard.com).  You can see it in the header of the [AdGuard organization on GitHub](https://github.com/AdguardTeam).  You can also add [verbose query logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) to your E-Mail.

Also, could you please answer, if your address is resolvable by the bootstrap DNS servers?  Because it needs to be resolvable.

**Comment by ainar-g** [comment]
@thb007, apologies for the very late response.  I see a lot of `EOF` and `Application error 0x2` errors in your logs, which might mean that the server you're trying to reach is either 
down or refusing connections (e.g. a DDOS protection or firewall).  Is this issue still a problem?

**Comment by thb007** [comment]
> @thb007, apologies for the very late response. I see a lot of `EOF` and `Application error 0x2` errors in your logs, which might mean that the server you're trying to reach is either down or refusing connections (e.g. a DDOS protection or firewall). Is this issue still a problem?

dnsproxy (https://github.com/AdguardTeam/dnsproxy) has fixed this problem.
