### ISSUE TITLE
[error] handling tcp: handling tls request: talking to dns upstream: ... read: connection reset by peer

### ISSUE THREAD

**Issue by gitisz** [AdguardTeam/AdGuardHome#4609]
### Issue Details
* **Version of AdGuard Home server:**
  * v0.107.6
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * NA
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Host: debian bullseye

### Expected Behavior
Fewer error logs

### Actual Behavior
After reviewing `docker logs adguardhome` I see about 20 or so of the following error message daily:
```
2022/05/29 04:32:15.914935 [error] handling tcp: handling tls request: talking to dns upstream: requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=<REMOVED ENCRYPTION STRING>": read tcp 172.17.0.2:38392->9.9.9.10:443: read: connection reset by peer
2
```
### Additional Information
Adguard appears to be working as expected.

**Comment by ainar-g** [comment]
Hello.  This just means that the upstream server has refused a connection (e.g because of a rate limiter or some network error).  AdGuard Home should reconnect after that, so if there are no issues with AGH itself, you can just ignore those.

**Comment by gitisz** [comment]
Thanks for that, sounds like throttling then!
