### ISSUE TITLE
Create custom DNS entries

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdGuardHome#461]
Feature request:
A way to create custom DNS entries within any zones that may be local to the network.

Customer ID: 2040378

**Comment by marcotuna** [comment]
Looking also for something like this. 
Currently I am adding my DNS entries on Custom filtering rules like this:

192.168.5.5 dev.home.local
192.168.5.6 git.home.local

However this entries get listed on the logs as something blacklisted.
Having something like Cloudflare Dashboard for DNS on AD Guard would be awesome for internal DNS Server in conjunction with AD Guard Block policies.

https://docs.microsoft.com/en-us/office365/admin/media/4744d759-e92c-4e19-844d-a11dd5f37a31.png?view=o365-worldwide

**Comment by ameshkov** [comment]
@marcotuna 
Yeah, well, this is what we have in mind. Thank you for suggesting Cloudflare as an example, their DNS panel is very nice indeed.

**Comment by hoshsadiq** [comment]
Would be nice tip have this an api too.

**Comment by ibksturm** [comment]
yeah, would be great!

**Comment by szolin** [comment]
'Rewrites' feature
