### ISSUE TITLE
SSH "netstat -a" command triggers PTR responses

### ISSUE THREAD

**Issue by OpenSourceGhost** [AdguardTeam/AdGuardHome#4612]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Running "netstat -a" command in SSH trigger AGH ".in-addr" PTR re-write responses for hosts listed in "etc/hosts" even when a custom rule/filter to block ".in-addr" domains is set. The same command triggers PTR responses for gateway IP, but gateway IP is not listed in "etc/hosts" and PTR response to it is blocked by ".in-addr" blocking rule. 

* **Version of AdGuard Home server:**
Latest 0.108 Edge

* **How did you install AdGuard Home:**
curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge

* **How did you setup DNS configuration:**
Local DNS server exclusive for LAN clients, not DHCP server

* **If it's a router or IoT, please write device model:**
Raspberry Pi 4

* **CPU architecture:**
ARM64

* **Operating system and version:**
Raspi OS Lite - 64bit (Bullseye)

### Expected Behavior
Running SSH "netstat -a" command should not trigger ".in-addr" PTR responses.

### Actual Behavior
Running SSH "netstat -a" command in SSH trigger AGH ".in-addr" PTR re-write responses for hosts listed in "etc/hosts" even when a custom rule/filter to block ".in-addr" domains is set. The same command triggers PTR responses for gateway IP, but gateway IP is not listed in "etc/hosts" and PTR response to it is blocked by ".in-addr" blocking rule.

**Comment by ainar-g** [comment]
On the v0.108 edge you can disable the `/etc/hosts` handling completely by setting `clients.runtime_sources.hosts` to `false`.  That will also disable the resolving of `A` queries, but you can readd those that you need to your custom filtering rules by using the `dnsrewrite` rules.

**Comment by OpenSourceGhost** [comment]
I am more interested in knowing whether it is normal for "netstat" commands to trigger .in-addr responses in general. So far it is the only thing that triggers such responses. 

What is the benefit of using AGH Clients list instead of /etc/hosts? I use both at the same time. They mirror each other, except for loopback/hostname entry because Linux uses 127.0.1.1 for hostname.
