### ISSUE TITLE
listen tcp :53: protocol not available

### ISSUE THREAD

**Issue by apeng2012** [AdguardTeam/AdGuardHome#462]
### Actual behavior

    peng@openmediavault:~/AdGuardHome$ sudo ./AdGuardHome
    2018/11/23 20:26:10 AdGuard Home web interface backend, version v0.9-hotfix1
    main.renameOldConfigIfNeccessary(): File /home/peng/AdGuardHome/AdguardDNS.yaml doesn't exist, nothing to do
    main.askUsernamePasswordIfPossible(): File /home/peng/AdGuardHome/AdGuardHome.yaml exists, won't ask for password
    2018/11/23 20:26:10 Reading YAML file: /home/peng/AdGuardHome/AdGuardHome.yaml
    2018/11/23 20:26:10 Writing YAML file: /home/peng/AdGuardHome/AdGuardHome.yaml
    2018/11/23 20:26:10 Writing DNS config: /home/peng/AdGuardHome/Corefile
    2018/11/23 20:26:10 Writing filter file: /home/peng/AdGuardHome/dnsfilter.txt
    2018/11/23 20:26:10 Go to http://127.0.0.1:3000
    2018/11/23 20:26:10 filterFileNames = [/home/peng/AdGuardHome/dnsfilter.txt]
    2018/11/23 20:26:10 Added 0 rules from /home/peng/AdGuardHome/dnsfilter.txt
    2018/11/23 20:26:10 Loading stats from querylog
    2018/11/23 20:26:10 listen tcp :53: protocol not available
    peng@openmediavault:~/AdGuardHome$

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0) v0.9-hotfix1
| How did you setup DNS configuration:| (System/Router/IoT)System
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)N3150
| Operating system and version:| (e.g. Ubuntu 18.04.1)Linux openmediavault 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64

**Comment by hmage** [comment]
Hi.

What Linux distribution are you using? Debian? Ubuntu? Do you have any linux kernel security installed and activated like SElinux, AppArmor, GrSecurity, SecComp or something similar?

**Comment by apeng2012** [comment]
Linux openmediavault 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64
[openmediavault](http://www.openmediavault.org/)  is the next generation network attached storage (NAS) solution based on Debian Linux.

**Comment by Bhooty** [comment]
Sudo systemctl disable system-resolved
Restart then try again

**Comment by apeng2012** [comment]
![notfound](https://user-images.githubusercontent.com/3783662/50400699-a5038800-07c3-11e9-80b1-ce9868bd623f.PNG)

p.s. The system has two network cards, bridged

**Comment by be2clack** [comment]
I also have such a problem? Ubuntu! how to solve ??????

**Comment by ultimatevn** [comment]
Im using Debian 9 and cant install AdGuardHome, it's said
Port 53 is not available for binding -- this will make DNS clients unable to contact AdGuard Home.
What i do...

**Comment by CWo42** [comment]
systemctl disable systemd-resolved.service 
service systemd-resolved stop


solves your problem @ultimatevn

**Comment by ultimatevn** [comment]
@CWo42 not working :(

**Comment by CWo42** [comment]
strange on my debian that was working
can you eval whats using 53?

**Comment by ultimatevn** [comment]
@CWo42 I dont know what application use port 53, i dont see that port in netstat

> root@debian:/home/ultimatevn# netstat -lpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5094            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5062            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5126            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5030            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5127            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5095            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5159            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5031            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5063            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5128            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5096            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5064            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5032            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5160            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:8072            0.0.0.0:*               LISTEN      4800/nginx: master  
tcp        0      0 0.0.0.0:5097            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5161            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5033            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5129            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5065            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5001            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5130            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5002            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5098            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5162            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5066            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5034            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5003            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5035            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5067            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5099            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5131            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5163            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      2984/smbd           
tcp        0      0 0.0.0.0:5132            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5004            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5164            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5100            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5036            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5068            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5005            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5069            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5165            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5133            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5101            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5037            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5006            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5134            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5166            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5070            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5102            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5103            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5007            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5135            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5039            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5167            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5071            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5136            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5168            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5040            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5008            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5072            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5073            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5137            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5041            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5169            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5105            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5009            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5106            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5042            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5010            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5074            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5011            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5139            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5107            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5043            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5075            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5171            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5108            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5044            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5172            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5076            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5012            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5140            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5013            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5173            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5077            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5141            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5045            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5109            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      664/sshd            
tcp        0      0 0.0.0.0:5142            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5174            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5014            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5046            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5110            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5078            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5143            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5175            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5111            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5047            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5015            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5079            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      611/cupsd           
tcp        0      0 0.0.0.0:5176            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5080            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5144            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5112            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5048            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5016            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5177            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5049            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5081            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5017            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5113            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5145            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 127.0.0.1:18682         0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5178            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5050            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5146            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5114            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5018            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5147            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5179            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5051            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5115            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5019            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5083            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      4022/python3        
tcp        0      0 0.0.0.0:5020            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5052            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5148            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5180            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5116            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5117            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5149            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5085            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5181            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      2984/smbd           
tcp        0      0 0.0.0.0:5054            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5086            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5118            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5150            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5022            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5151            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5023            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5087            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5055            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5119            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5024            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5056            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5088            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5120            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5152            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5089            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5025            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5153            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5057            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5026            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5058            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5154            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5122            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5090            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5091            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5123            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5027            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5059            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5155            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5156            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5092            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5028            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5060            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5124            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5093            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5061            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5029            0.0.0.0:*               LISTEN      4802/java           
tcp        0      0 0.0.0.0:5157            0.0.0.0:*               LISTEN      4802/java           
tcp6       0      0 :::8843                 :::*                    LISTEN      2294/docker-proxy   
tcp6       0      0 :::139                  :::*                    LISTEN      2984/smbd           
tcp6       0      0 :::8080                 :::*                    LISTEN      2371/docker-proxy   
tcp6       0      0 :::8880                 :::*                    LISTEN      2280/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      694/apache2         
tcp6       0      0 :::3218                 :::*                    LISTEN      6354/docker-proxy   
tcp6       0      0 :::8883                 :::*                    LISTEN      1954/docker-proxy   
tcp6       0      0 :::8884                 :::*                    LISTEN      1941/docker-proxy   
tcp6       0      0 :::22                   :::*                    LISTEN      664/sshd            
tcp6       0      0 ::1:631                 :::*                    LISTEN      611/cupsd           
tcp6       0      0 :::3000                 :::*                    LISTEN      5875/AdGuardHome    
tcp6       0      0 :::8443                 :::*                    LISTEN      2306/docker-proxy   
tcp6       0      0 :::1883                 :::*                    LISTEN      1979/docker-proxy   
tcp6       0      0 :::1884                 :::*                    LISTEN      1966/docker-proxy   
tcp6       0      0 :::445                  :::*                    LISTEN      2984/smbd           
tcp6       0      0 :::6789                 :::*                    LISTEN      2409/docker-proxy   
udp        0      0 0.0.0.0:631             0.0.0.0:*                           614/cups-browsed    
udp        0      0 0.0.0.0:52089           0.0.0.0:*                           4022/python3        
udp        0      0 0.0.0.0:5001            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5002            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5003            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5004            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5005            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5009            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5013            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5016            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5020            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5021            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5027            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5031            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5032            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5033            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5038            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5044            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5051            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5052            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5053            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5064            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5074            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5081            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5082            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5084            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5086            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5103            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5104            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5121            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5125            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5134            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5138            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5145            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5158            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:5170            0.0.0.0:*                           4802/java           
udp        0      0 0.0.0.0:38096           0.0.0.0:*                           4022/python3        
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           5594/chrome --type= 
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           5549/chrome         
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           5549/chrome         
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           5549/chrome         
udp   213504      0 0.0.0.0:5353            0.0.0.0:*                           4022/python3        
udp   213504      0 0.0.0.0:5353            0.0.0.0:*                           4022/python3        
udp   213504      0 0.0.0.0:5353            0.0.0.0:*                           4022/python3        
udp   213504      0 0.0.0.0:5353            0.0.0.0:*                           4022/python3        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           4022/python3        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           579/avahi-daemon: r 
udp        0      0 0.0.0.0:44573           0.0.0.0:*                           4022/python3        
udp        0      0 0.0.0.0:68              0.0.0.0:*                           941/dhclient        
udp        0      0 172.17.255.255:137      0.0.0.0:*                           2983/nmbd           
udp        0      0 172.17.0.1:137          0.0.0.0:*                           2983/nmbd           
udp        0      0 172.30.33.255:137       0.0.0.0:*                           2983/nmbd           
udp        0      0 172.30.32.1:137         0.0.0.0:*                           2983/nmbd           
udp        0      0 192.168.1.255:137       0.0.0.0:*                           2983/nmbd           
udp        0      0 192.168.1.22:137        0.0.0.0:*                           2983/nmbd           
udp        0      0 0.0.0.0:137             0.0.0.0:*                           2983/nmbd           
udp        0      0 172.17.255.255:138      0.0.0.0:*                           2983/nmbd           
udp        0      0 172.17.0.1:138          0.0.0.0:*                           2983/nmbd           
udp        0      0 172.30.33.255:138       0.0.0.0:*                           2983/nmbd           
udp        0      0 172.30.32.1:138         0.0.0.0:*                           2983/nmbd           
udp        0      0 192.168.1.255:138       0.0.0.0:*                           2983/nmbd           
udp        0      0 192.168.1.22:138        0.0.0.0:*                           2983/nmbd           
udp        0      0 0.0.0.0:138             0.0.0.0:*                           2983/nmbd           
udp        0      0 0.0.0.0:33027           0.0.0.0:*                           579/avahi-daemon: r 
udp6       0      0 :::33686                :::*                                579/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                579/avahi-daemon: r 
udp6       0      0 :::3478                 :::*                                2435/docker-proxy   
udp6       0      0 :::10001                :::*                                2263/docker-proxy   
udp6       0      0 :::1900                 :::*                                2451/docker-proxy   
raw6       0      0 :::58                   :::*                    7           615/NetworkManager

**Comment by ameshkov** [comment]
@ultimatevn what exact error do you see in the AGH console output?

Are you running AGH under root?

**Comment by ElectricReality** [comment]
Im also having the same problem here on plesk on debian 9. "Port 53 is not available for binding -- this will make DNS clients unable to contact AdGuard Home."

**Comment by ultimatevn** [comment]
Already run on root privilege...

**Comment by ameshkov** [comment]
@ultimatevn could you please share your AdGuardHome.yaml?

Try changing DNS interface from 0.0.0.0 to 127.0.0.1 for instance.

**Comment by apeng2012** [comment]
> @apeng2012 could you please try building AG from the master branch? There were some massive changes lately and it might help

v0.95-hotfix can run
