### ISSUE TITLE
More phishing links

### ISSUE THREAD

**Issue by kickass42zer0** [AdguardTeam/AdGuardHome#4621]
More phishing sites for the block lists.

vwol.link/XZUnv

I asked once before where I should request additions to the block lists as I don't think the github page is the appropriate place.  Never got an answer.

Please advise as to where I should post these links as they come in.

I use a dedicated adguard server, and so does several of my clients, so I would like to have the phishing stuff blocked.

Thank you very much for all your hard work and the great dns software software known as adguard.
Let me know if I can help with anything.

**Comment by ainar-g** [comment]
Hello.  The link that you should use to report AdGuard's block list issues is <https://reports.adguard.com/en/new_issue.html>.  That notifies the team working on the filtering rule lists.  Please use this link to report any kind of false-positive or false-negative results.
