### ISSUE TITLE
Add rules for Skype in Blocked service

### ISSUE THREAD

**Issue by Piber0** [AdguardTeam/AdGuardHome#4625]
Rules : 
- edge-skype-com.s-0001.s-msedge.net
- skype-edf.akadns.net
- skypedata.akadns.net

Source [nextdns](https://github.com/nextdns/metadata/raw/master/parentalcontrol/services/skype)

**Comment by ainar-g** [comment]
Apologies for the long silence.  We have added these to the latest Edge release.  Thank you for proposing this.
