### ISSUE TITLE
Add green logo

### ISSUE THREAD

**Issue by AAraonWPaul** [AdguardTeam/AdGuardHome#4626]
I saw that there used to be a green logo, please add this back I think it suits the interface better and once the dark mode is added it will be visible.
![image](https://user-images.githubusercontent.com/105821894/171887939-5cb29efe-eadc-4fd9-aa95-a4b18e935c55.png)

**Comment by agneevX** [comment]
The current SVG provides better compatibility with custom themes, IMO.

![image](https://user-images.githubusercontent.com/19761269/172198217-61ee70c2-24a3-4c3e-9e7c-1abedd57c4e4.png)

**Comment by Birbber** [comment]
@AAraonWPaul Hi, sorry for the long silence! We're planning a redesign, so you can check [this issue](#2554) to see the details.
Closing this one as a duplicate.
