### ISSUE TITLE
Remove adguard browsing security and parental servince from dashboard if it is not enabled

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#4632]
Like title saids. I think it would make the interface cleaner and give better insight since the other graphs will make longer. Though I don't know how helpful this suggestion is as there will be a new interface soon.

**Comment by ainar-g** [comment]
Indeed, there are plans for a new UI in the v0.108 cycle.  I'll close this one in favour of #2554.
