### ISSUE TITLE
Upstream DNS for specific domain

### ISSUE THREAD

**Issue by rapdodge** [AdguardTeam/AdGuardHome#4633]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Make custom upstream DNS for specific domain can use asterisk like DNS rewrite
![image](https://user-images.githubusercontent.com/33513626/172074931-821ef116-86da-458d-b30f-e2a15049c6da.png)

### Proposed Solution
Make it can using asterisk for all subdomains
![image](https://user-images.githubusercontent.com/33513626/172075099-193f126c-d577-4725-9092-52b12364ebee.png)

### Alternatives Considered
Nothing

### Additional Information
It's very inconvenient to enter one by one, and they are all in the same domain

**Comment by fernvenue** [comment]
Actually, it dose work for all subdomains, I think maybe you should read the [documentaion](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains) first.

**Comment by rapdodge** [comment]
> Actually, it dose work for all subdomains, I think maybe you should read the [documentaion](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-domains) first.

Aaaah... Yes, yes, i thought is not include all the subdomain, thank you

Closed
