### ISSUE TITLE
Windows-specific corrections in the DNSCrypt guide

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#4639]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (0.108.0-b.8)
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.108.0-b.8
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * N/A
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 11 stable AMD64

### Expected Behavior
That accomodations are made to clarify the steps at https://github.com/AdguardTeam/AdGuardHome/wiki/DNSCrypt, as explained in "Actual Behavior".

### Actual Behavior
At https://github.com/AdguardTeam/AdGuardHome/wiki/DNSCrypt, there are some minor errors in the guide steps when attempting them on Windows:
1) For reasons I'm not 100% certain about, `'dnscrypt_config_file': './dnscrypt.yaml'` will cause AdGuard Home to fail to start up outright on Windows. Instead, the full pathname must be specified, instead of just `./dnscrypt.yaml`
2) When using the AdGuard-supplied `dnscrypt` command line tool, `dnscrypt generate --provider-name '2.dnscrypt-cert.example.org' --out ./dnscrypt.yaml` could be confusing to Windows users who haven't yet learned how to use PowerShell and `cd`, especially since opening `dnscrypt.exe` from File Explorer will cause it to close instantly. It could be specified something like: *"Open PowerShell, use `cd [full-filepath]` to maneuver to the folder you extracted the .ZIP to, and run `.\dnscrypt.exe generate --provider-name '2.dnscrypt-cert.example.org' --out ./dnscrypt.yaml`"*
3) The backslash-for-linebreak format used in "Check your installation by running:", causes the error `Missing expression after unary operator '--'.` Instead, it appears that Windows users must run the format with no linebreaks, e.g. `.\dnscrypt.exe lookup-stamp --domain 'example.com' --stamp 'sdns://AQcAAAAAAAAADTEyNy4wLjAuMTo0NDMg8R3bzEgX5UOEX93Uy4gYSbZCJvPeOXYlZp2HuRm8T7AbMi5kbnNjcnlwdC1jZXJ0LmV4YW1wbGUub3Jn' --type 'a'`

### Screenshots

N/A

### Additional Information
The problem has been tested across 2 Windows computers across a 16hr time period, the other of which ran 0.107.7 stable.

**Comment by ainar-g** [comment]
Thanks for letting us know.  Re. 3, PowerShell weirdly uses `` ` `` (an ASCII backtick) as a character that shows that a command continues on the next line.

**Comment by ainar-g** [comment]
Apologies for the long wait.  We've updated the examples in the Wiki.  Could you please check if these work for you?

**Comment by ainar-g** [comment]
We'll close the issue now.  Please feel free to report new ones.  Thanks!
