### ISSUE TITLE
The "Upstream DNS servers" menus fails to recognise TCP+IPv6 addresses

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#4640]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.108.0-b.9
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * N/A
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 11 stable AMD64

### Expected Behavior
The "Upstream DNS servers" box recognises addresses that are both `tcp://` and IPv6.

### Actual Behavior
Trying to add `tcp://2001:4652:5f5:0:bd84:5904:79ef:3fd7` to the "Upstream DNS servers" textbox and then pressing "Apply", causes the error message `Error: control/dns_config | validating upstream servers: cannot prepare the upstream tcp://2001:4652:5f5:0:bd84:5904:79ef:3fd7 ([]): failed to parse tcp://2001:4652:5f5:0:bd84:5904:79ef:3fd7: parse "tcp://2001:4652:5f5:0:bd84:5904:79ef:3fd7": invalid port ":3fd7" after host
 | 400`

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/172309447-38ee3a47-b4e7-479f-83f5-96b97d4f2bb7.png)

</details>

### Additional Information

AdGuard for Android *seems* to recognise and connect to `tcp://2001:4652:5f5:0:bd84:5904:79ef:3fd7`, so I'm 85% certain that connection problems aren't at fault.

**Comment by ppfeufer** [comment]
Try `tcp://[2001:4652:5f5:0:bd84:5904:79ef:3fd7]`

**Comment by DandelionSprout** [comment]
That seemed to go quite a bit better. Thanks for the tip.

**Comment by ainar-g** [comment]
I'll reopen this and label as Documentation and UI issue, since this behaviour is a bit unintuitive and must be documented better.

**Comment by ainar-g** [comment]
@DandelionSprout, we've added IPv6 examples both to the UI as well as to the Wiki.  We'll close this issue, but feel free to open new ones if you find inadequate documentation.
