### ISSUE TITLE
'DNS privacy' info doesn't update on 'Setup Guide' tab  

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardHome#4642]
### Issue Details

After successfully updating the encryption settings 'DNS privacy' info on Setup Guide doesn't update until the page is manually refreshed: https://uploads.adguard.com/annrgy_4f3z0.mp4   

### Expected Behavior
The tab should already be refreshed once the settings were applied.

**Comment by ainar-g** [comment]
@Birbber, the newest version on the Edge channel should fix this and #4641.  Can you please check?
