### ISSUE TITLE
DoQ connection to NextDNS doesn't work anymore

### ISSUE THREAD

**Issue by HellboyPI** [AdguardTeam/AdGuardHome#4644]
### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.7
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * System
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04.4 LTS

After updating AdGuard Home to latest stable version (v0.107.7) DoQ (DNS-over-QUIC) connection to NextDNS stopped working. 
In v0.107.7 AdGuard Home team added support for the final version of the DoQ standard.

NextDNS does not yet support this. They also use udp port 8853. 

Is it possible to make a workaround until NextDNS team updates their DoQ implementation? 

This problem is also mentioned on NextDNS forum:
https://help.nextdns.io/t/83hddp1/is-quic-protocol-down

**Comment by HellboyPI** [comment]
> Maybe you can try to set the port in your config like this:
> 
> ```
> quic://example.dns:8853
> ```
I have already tried that. Unfortunately, it does not work.

**Comment by f7b6h9** [comment]
> Maybe you can try to set the port in your config like this:
> 
> ```
> quic://example.dns:8853
> ```
> 
> And clearly they should support the final version of the DoQ standard.

I tested NextDNS DoQ on port 853 and it still works, so it's not about the port.
![image](https://user-images.githubusercontent.com/55645184/172502127-ac0577c2-d323-4b45-9494-f6157476319e.png)

**Comment by unknown4849** [comment]
so far only quic adguard dns still work (maybe already support or configured?) , btw Tiarap quic dns also doesn't work at lastest version adguard home.

**Comment by HellboyPI** [comment]
Tried also with:
quic://dot-de.blahdns.com:784

It doesn't work. At the moment, with v0.107.7 of AdGuard Home only connections to AdGuard DoQ resolvers are possible.

**Comment by ameshkov** [comment]
RFC-version of DoQ is not compatible with the old draft versions, hence the issue.

AdGuard Home has already switched to the RFC-version of DoQ.
AdGuard DNS supports both the old drafts and the RFC-version.

Unfortunately, this behavior is only normal for the server-side since it can distinguish the version the client wants to use. The client just uses the RFC-version and if the server is not compatible it won't get through.

Probably, the only way is to fix this on the NextDNS side. The fix is rather trivial, though. I'd suggest NextDNS to use the same approach as we do to support the old clients: https://github.com/AdguardTeam/dnsproxy/commit/c3b50a44f5b41cc0f385a0402e5dc127f08b0d1d#diff-6f8ef90801bf531405c62f0548dd80dc2edec8e10f96b0cd50c34544a7ea9c53R154

**Comment by HellboyPI** [comment]
Thank You for the help. I have sent your answer to NextDNS. 
They responded:
_„I think there is a misunderstanding on the RFC. The RFC specifies that DoQ enforces the same size limit for DNS messages, and it says that DoT and DNS over TCP are doing so via a 2 bytes size and DoH via the definition of the RFC. It does not say DoQ is using a 2 bytes message size.“_

I'm not enough qualified in this matter. So, it would be best that AdGuard Home developers continue this conversation with NextDNS developers.

**Comment by beerisgood** [comment]
> Maybe it would be best that AdGuard Home developers continue this conversation with NextDNS developers?
>

NextDNS team isn’t very active so you shouldn’t hope for a fast answer - if ever.

**Comment by HellboyPI** [comment]
They responded pretty fast in this case. They wrote, that they are planning to update their DoQ implementation very soon (next week).
That being said, this thread can be closed. For now. 😃

**Comment by Deleted-Account** [comment]
DoQ seems not working in AdGuardHome v1.08
Both official or thirdparty (such as ksey/adguardhome https://hub.docker.com/r/ksey/adguardhome) docker version
have the same issue
Add DoQ server to Upstream DNS severs then click "Test upstreams" button will reply 'Server "XXXXXX": could not be used, please check that you've written it correctly'

**Comment by ameshkov** [comment]
@HellboyPI am I understanding that right that they've reviewed the RFC and admitted that there must be a prefix?

Just in case, here's the relevant part of the [RFC](https://datatracker.ietf.org/doc/rfc9250/):

>   All DNS messages (queries and responses) sent over DoQ connections
>   MUST be encoded as a 2-octet length field followed by the message
>   content as specified in [RFC1035].

**Comment by HellboyPI** [comment]
They wrote that there was a misunderstanding, but not anymore, and that they will update their servers.

**Comment by leo15dev** [comment]
> They wrote that there was a misunderstanding, but not anymore, and that they will update their servers.

NextDNS had fixed this issue, now their DoQ can work in the AdGuard Home
