### ISSUE TITLE
YAML, /#logs - issue

### ISSUE THREAD

**Issue by happyhater** [AdguardTeam/AdGuardHome#465]
2018/11/28 22:22:17 Couldn't save YAML config: rename adguard.yaml.tmp adguard.yaml: no such file or directory
2018/11/28 22:22:17 rename adguard.yaml.tmp adguard.yaml: no such file or directory

and issue in /#logs when you load external filters and block them, you cannot load anymore this page:
TypeError: undefined is not an object (evaluating 'l[d].name')

**Comment by happyhater** [comment]
also:

npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

**Comment by happyhater** [comment]
Filters: []filter{
		{ID: 1, Enabled: true, URL: "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt", Name: "AdGuard Simplified Domain Names filter"},
		{ID: 2, Enabled: false, URL: "https://adaway.org/hosts.txt", Name: "AdAway"},
		{ID: 3, Enabled: false, URL: "https://hosts-file.net/ad_servers.txt", Name: "hpHosts - Ad and Tracking servers only"},
		{ID: 4, Enabled: false, URL: "http://www.malwaredomainlist.com/hostslist/hosts.txt", Name: "MalwareDomainList.com Hosts List"},
	},

Example from first link with mbzl-pro.xyz:
host mbzl-pro.xyz 127.0.0.1
result:
blocked

after refresh the page /#logs
and you got this Error in console:
TypeError: undefined is not an object (evaluating 'l[d].name')

**Comment by hmage** [comment]
How are you launching adguard home? 

If systemd, could you please provide systemd logs? `journalctl -a > log` and attach the log file to the issue.

**Comment by hmage** [comment]
It was likely a race condition, try building from source newest master and see if the problem still remains.

**Comment by hmage** [comment]
Yep, managed to reproduce the issue. The latest commit 45ae984f3bd7bad1f21c1e8f9910558cc2986cba fixes the issue.

**Comment by happyhater** [comment]
Bug still alive.

**Comment by happyhater** [comment]
[Error] TypeError: undefined is not an object (evaluating 'l[d].name')
Cell — bundle.7bca668e8a003e830e80.js:48758
(anonymous function) — bundle.7bca668e8a003e830e80.js:3403
map
t — bundle.7bca668e8a003e830e80.js:3373
map
nt — bundle.7bca668e8a003e830e80.js:3349
ca — bundle.7bca668e8a003e830e80.js:14345
Ga — bundle.7bca668e8a003e830e80.js:15200
Va — bundle.7bca668e8a003e830e80.js:15223:161
Ci — bundle.7bca668e8a003e830e80.js:15476
Ii — bundle.7bca668e8a003e830e80.js:15462
ki — bundle.7bca668e8a003e830e80.js:15404
Qa — bundle.7bca668e8a003e830e80.js:15362
enqueueSetState — bundle.7bca668e8a003e830e80.js:13995
setState — bundle.7bca668e8a003e830e80.js:11632
onStateChange — bundle.7bca668e8a003e830e80.js:6710
[native code]
notify — bundle.7bca668e8a003e830e80.js:16602
notifyNestedSubs — bundle.7bca668e8a003e830e80.js:16579:174
[native code]
onStateChange — bundle.7bca668e8a003e830e80.js:6710
[native code]
g — bundle.7bca668e8a003e830e80.js:4514
(anonymous function) — bundle.7bca668e8a003e830e80.js:1383:87
w — bundle.7bca668e8a003e830e80.js:17168
(anonymous function) — bundle.7bca668e8a003e830e80.js:17150
o — bundle.7bca668e8a003e830e80.js:3583
(anonymous function) — bundle.7bca668e8a003e830e80.js:3590
promiseReactionJob

	ya (bundle.7bca668e8a003e830e80.js:45:66403)
	callback (bundle.7bca668e8a003e830e80.js:45:70721)
	uo (bundle.7bca668e8a003e830e80.js:45:46054)
	so (bundle.7bca668e8a003e830e80.js:45:45854)
	Pi (bundle.7bca668e8a003e830e80.js:45:90187)
	Ci (bundle.7bca668e8a003e830e80.js:45:85577)
	Ii (bundle.7bca668e8a003e830e80.js:45:84922)
	ki (bundle.7bca668e8a003e830e80.js:45:83943)
	Qa (bundle.7bca668e8a003e830e80.js:45:82846)
	enqueueSetState (bundle.7bca668e8a003e830e80.js:45:47683)
	setState (bundle.7bca668e8a003e830e80.js:37:1920)
	onStateChange (bundle.7bca668e8a003e830e80.js:17:4470)
	(anonymous function)
	notify (bundle.7bca668e8a003e830e80.js:61:2705)
	notifyNestedSubs (bundle.7bca668e8a003e830e80.js:61:2347)
	(anonymous function)
	onStateChange (bundle.7bca668e8a003e830e80.js:17:4496)
	(anonymous function)
	g (bundle.7bca668e8a003e830e80.js:12:53927)
	(anonymous function) (bundle.7bca668e8a003e830e80.js:1:26062)
	w (bundle.7bca668e8a003e830e80.js:61:13429)
	(anonymous function) (bundle.7bca668e8a003e830e80.js:61:13214)
	o (bundle.7bca668e8a003e830e80.js:12:34016)
	(anonymous function) (bundle.7bca668e8a003e830e80.js:12:34113)
	promiseReactionJob
