### ISSUE TITLE
rDNS doesn't work as configured

### ISSUE THREAD

**Issue by GreatMichaelLee** [AdguardTeam/AdGuardHome#4654]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  tried both on 0.107.0 and 0.108.0-b9
* **How did you install AdGuard Home:**
  * Github Release
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * No
* **CPU architecture:**
  * X86 PVE lxc container
* **Operating system and version:**
  *  debian 11

### Expected Behavior

I run Adguardhome on a debian 11 LXC host on PVE. configuration like this:
Adguardhome bind to 192.168.2.248 and there is a smartdns daemon run there as AdGuard's upstream(configured on conf file in AD)
all dhcp clients and hostnames configured on from the gateway (192.168.2.1 which is a openwrt router and it also runs smartdns but provide the revert DNS service), if I use dig -x 192.168.2.x @192.168.2.1 on 192.168.2.248 where the AD/SmartDNS stand host, I can properly get the PTR query result with a hostname.xxx.com of the other clients,but if I directly use 'nslookup 192.168.2.x‘， it will prompt the NXDOMAIN error, I have already enable the prividate rDNS and configured 192.168.2.1 there both in upstream server and private rDNS upstream server but it looks like doesn't work as expected.

### Actual Behavior

see above 
### Screenshots

![image](https://user-images.githubusercontent.com/20067401/172998746-a9d22acd-49c1-4302-b609-7f97be6f2b9b.png)
![image](https://user-images.githubusercontent.com/20067401/172998782-17391cd5-e709-42a0-be9e-65685bd4b2a3.png)
dig using the 192.168.2.248(local AD) and dig with 192.168.2.1
![image](https://user-images.githubusercontent.com/20067401/172999078-3d3ce3c9-542d-49f0-ac8e-eed57022b34b.png)

<details><summary>Screenshot:</summary>

</details>
NA
### Additional Information

NA

**Comment by GreatMichaelLee** [comment]
this is the result try on AdGuardHome installed machine (192.168.2.248)
![image](https://user-images.githubusercontent.com/20067401/173007724-8a679f5a-3337-495b-a694-e06036ecb35c.png)

**Comment by GreatMichaelLee** [comment]
My understanding is that AdGuard not using the configured private rDNS server to do the PTR query as expected somehow, as if I dig a common LAN host (192.168.2.2)with the upstream private rDNS upstream server in explicitely it could work and return with PTR result, but if I dig directly the AdGuard bind address it return the SOA, as snapshot above, however I have do configured the  private rDNS upstream server(`192.168.2.1`) there, but looks like it not be used also I even configure` [/in-addr.arpa/]192.168.2.1` in the main upstream server

**Comment by ainar-g** [comment]
@GreatMichaelLee, can you please show (possibly anonymized) contents of your “Private reverse DNS servers”?  Also, you technically don't need to put the ` [/in-addr.arpa/]` part there, because these upstreams are only used for rDNS.  Try just putting `192.168.2.1` in there.

**Comment by GreatMichaelLee** [comment]
> @GreatMichaelLee, can you please show (possibly anonymized) contents of your “Private reverse DNS servers”? Also, you technically don't need to put the ` [/in-addr.arpa/]` part there, because these upstreams are only used for rDNS. Try just putting `192.168.2.1` in there.

Hi, thanks for the reply, what do you mean the "content of your 'Private rDNS servers'"? the private rDNS server192.168.2.1(a dnsmasq as dhcp server and a smartdns as its upstream server there) and all PTR query for the LAN ip address will return itheir hostname + xxx.com (define in dnsmasq ) which bind in OpenWRT dnsmasq conf.  you can find it in snapshot which I masked it 

the /in.addr.arpa/ is not used in the Private rDNS server config fied but define in the ‘Upstream DNS Server', I use this just in case which I think if private rdns server work properly it is helpless, I can remove it.

thanks.

**Comment by GreatMichaelLee** [comment]
I believe my issue is similar to #4497 mentioned, however, my private network space is in the same subnet space. and put 192.168.2.1 there doesn't work.

**Comment by GreatMichaelLee** [comment]
issue resolve. I found the root cuase, this is due to applied a download blocking rules which contain a line to block any 'in-addr.arpa', I address this from the log with verbose. so May I just suggest here that wether if you guys can make an configure option or switch in the web GUI that make the ADH daemon can override or not overrid any rules that contain the blocking PTR queries if some rules put it there?
