### ISSUE TITLE
Unable to remove blocklists

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#4659]
I am running the latest edge version 
I checked the documentation and found no answer
I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  *  v0.108.0-a.148+d3f39b0a
* **How did you install AdGuard Home:**
  * curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge
* **How did you setup DNS configuration:**
  * AGH handles DHCP
* **If it's a router or IoT, please write device model:**
  * N/A, Ubuntu Server on a laptop
* **CPU architecture:**
  * amd64
* **Operating system and version:**
  * Ubuntu LTS 22.04

### Expected Behavior
* Expected to be able to remove blocklists

### Actual Behavior
* Blocklists can't be removed, it shows that the blocklist was removed but it still shows up

### Screenshots

![image](https://user-images.githubusercontent.com/89283708/173171496-318d9661-0d72-4841-88c9-af5d67b77f73.png)

**Comment by Dynasty-Dev** [comment]
Update, it appears that the problem isn't that the list isn't being removed just that it gets removed just not from the interface. I tried editing the blocklist and changing the name and source link to another blocklist and I got this error.

![image](https://user-images.githubusercontent.com/89283708/173175990-a7a7aadc-9a01-48b3-ad6d-f0e80a70c85e.png)

**Comment by ainar-g** [comment]
@IldarKamalov, it seems like the frontend doesn't send the URL of the list to the backend.  Please investigate.

**Comment by ainar-g** [comment]
@Dynasty-Dev, this should be fixed on the Edge channel as of v0.108.0-a.155+b04d1ed6.  Can you please check if the fix works for you?

**Comment by AAraonWPaul** [comment]
> @Dynasty-Dev, this should be fixed on the Edge channel as of v0.108.0-a.155+b04d1ed6. Can you please check if the fix works for you?

Works fine now, thank you all!
