### ISSUE TITLE
Ability to sync settings and custom filtering rules across different instances

### ISSUE THREAD

**Issue by jitdor** [AdguardTeam/AdGuardHome#4663]
### Problem Description
I am currently running 3 instances of AdGuard Home within my local network, for redundancy purpose. One is on a Raspberry Pi, the other is on a ESXi guest, and the last one is a Docker container. Whenever I am adding or changing a rule, I have to carry out the update 3 times.

### Proposed Solution

- Add the ability within AdGuard Home to sync and replicate settings from a designated master node within the network, or
- Have the ability to specify a hosted yaml file via an HTTPS link, or
- Allow AdGuard Home to sync settings over the cloud when logged in to the Adguard account 

### Alternatives Considered
To mount an external AdGuardHome.yaml config file with R/W access - but this will not survive Docker image version upgrades

**Comment by ainar-g** [comment]
Merging into #573.
