### ISSUE TITLE
DNS error notification does not show the faulty DNS nameserver in Vietnamese

### ISSUE THREAD

**Issue by f7b6h9** [AdguardTeam/AdGuardHome#4665]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.7 and older

### Expected Behavior
The faulty DNS nameserver would show up

### Actual Behavior
The notification just show the DNS nameserver as ""':

### Screenshots

![image](https://user-images.githubusercontent.com/55645184/173213946-7e56dbf6-b6ad-4bc1-b06d-c482d0fd06f4.png)

</details>

**Comment by ainar-g** [comment]
@f7b6h9, hello.  This should be fixed on the Edge channel as of v0.108.0-a.155+b04d1ed6.  Can you please check if the message is fixed for you now?
