### ISSUE TITLE
adguardhome cannot be parsed correctly, and the IP in the blocklist is returned

### ISSUE THREAD

**Issue by Miooiio** [AdguardTeam/AdGuardHome#4668]
some details：GitHub releases，v0.107.7，Debian11，CPU：AMD64 ,DNS:tls://dns.alidns.com
Bootstrap DNS:1.1.1.1:53 9.9.9.9:53 223.5.5.5:53
In order to improve the loading and downloading speed of GitHub, I used github520 (a project that uses hosts to obtain the fastest IP address of GitHub), but I found that when I visited GitHub, the browser told me that I could not link GitHub for a timeout, sometimes I could not find the address, and sometimes I could load it correctly, but there was no record in the background, or the link was reset. I tried many methods, Including restarting the server and updating the blocklist, adguardhome can't return the correct IP from the list to help me link GitHub.   
![image](https://user-images.githubusercontent.com/107167205/173295859-3291ca87-0e15-42d1-8a02-262d4732ac3c.png)
![微信截图_20220613144708](https://user-images.githubusercontent.com/107167205/173295924-94d3897a-dd82-43b8-8c65-a6c4c57d8e70.png)
![微信截图_20220613144225](https://user-images.githubusercontent.com/107167205/173295953-fe01d3ad-1268-4abd-a0b2-3d1b234425a3.png)
![微信截图_20220613143856](https://user-images.githubusercontent.com/107167205/173295978-e932ac9d-c72d-4755-8a77-830952335935.png)
![微信截图_20220613143848](https://user-images.githubusercontent.com/107167205/173296013-d2338633-0681-4219-85fc-13589b6c0067.png)

However, it is strange that when I use NSLOOKUP, it can return the correct IP, and there are corresponding records in the background
![image](https://user-images.githubusercontent.com/107167205/173296229-8ffb56d5-dc25-4d8b-8d74-62f69a57dc9f.png)

![image](https://user-images.githubusercontent.com/107167205/173296286-c37400a5-a7e3-4294-ac56-5d4ff4b523a3.png)

**Comment by Miooiio** [comment]
add some details:
![image](https://user-images.githubusercontent.com/107167205/173296427-80ce447c-3ffe-4e65-ba48-aa25ba3f2618.png)
If this is my setting problem, please tell me how to set it. Thank you

**Comment by Miooiio** [comment]
github520 project https://github.com/521xueweihan/GitHub520
Sometimes it can be parsed correctly, but most of the time it will display pages that can't be linked. This is really strange. Other websites don't use this kind of thing

**Comment by ainar-g** [comment]
Hello.  If `nslookup` shows the correct IP address, it could be your browser.  Browsers have their own DNS settings, including DNS-over-HTTPS.  Make sure that you use AdGuard Home's address there as well.
