### ISSUE TITLE
v0.91 refuses to upgrade if /etc/resolv.conf points to itself

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#467]
I was unable to use 0.91 on my Raspberry Pi, for some reason the DNS doesn't work and http://192.168.x.x:3000/ refuses to connect.

I can reinstall and continue to use the older 0.9 hotfix 1 without an issue.

### Steps to reproduce

1. Completely uninstall 0.9 hotfix 1
2. Install 0.91 and start the service

### Expected behavior
AdGuard Home works as before.

### Actual behavior
DNS doesn't work, and the Dashboard refuses to load.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.91
| How did you setup DNS configuration:| DHCP on router pointing to Pi device for DNS
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian GNU/Linux 9 (stretch)

**Comment by hmage** [comment]
What binary did you download? arm? arm64? amd64? i386?

**Comment by planet0** [comment]
I replicated the same behaviour/steps [from the Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi) like 0.9-hotfix1, so I got the arm one (AdGuardHome_v0.91_linux_arm.tar.gz)

**Comment by hmage** [comment]
Can you try to run it from the terminal instead of systemd?

Just run it from terminal:
```
cd $HOME/AdGuardHome
./AdGuardHome
```

And show us what it says.

That would be greatly appreciated to figure out what's going on.

**Comment by planet0** [comment]
```
2018/11/29 21:54:04 AdGuard Home web interface backend, version v0.91
2018/11/29 21:54:04 Current working directory is /home/pi/AdGuardHome
Would you like to set user/password for the web interface authentication (yes/no)?
Please type 'yes' or 'no': no
2018/11/29 21:54:12 Reading YAML file: /home/pi/AdGuardHome/AdGuardHome.yaml
2018/11/29 21:54:12 YAML file doesn't exist, skipping: /home/pi/AdGuardHome/AdGuardHome.yaml
2018/11/29 21:54:12 Updating schema from 0 to 1
2018/11/29 21:54:12 Seting ID=1543488843 for filter https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
2018/11/29 21:54:12 Downloading update for filter 1543488843 from https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
2018/11/29 21:54:12 Couldn't request filter from URL https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt, skipping: Get https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: dial tcp: lookup adguardteam.github.io on 0.0.0.0:53: read udp 127.0.0.1:40240->127.0.0.1:53: read: connection refused
2018/11/29 21:54:12 Get https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: dial tcp: lookup adguardteam.github.io on 0.0.0.0:53: read udp 127.0.0.1:40240->127.0.0.1:53: read: connection refused
```

**Comment by hmage** [comment]
Breaking commit is 32d4e80c93cba5b3ef4bb96c79f7256b5cb4d913 -- it tries to use DNS _before_ the dns server is up.

**Comment by hmage** [comment]
As a workaround, please change /etc/resolv.conf to point to another server, for example 8.8.8.8

**Comment by planet0** [comment]
The contents of /etc/resolv.conf are currently:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.100
nameserver 0.0.0.0
```

---

Awesome. Changing the nameservers to Cloudflare (1.1.1.1 and 1.0.0.1) allowed v0.91 to launch successfully.

I then rebooted the Pi, and /etc/resolv.conf reverted back to the above, and AdGuard Home v0.91 continued to work successfully.

It also continues to work after rebooting Pi a few times.

Seems to only happen on first run/install?

**Comment by ameshkov** [comment]
> Seems to only happen on first run/install?

Yep, that's right.

**Comment by ameshkov** [comment]
Resolved in the master branch
