### ISSUE TITLE
控制程序页面报错Error: control/version.json | checking ability to bind privileged ports: invalid argument | 500

### ISSUE THREAD

**Issue by CJM88888** [AdguardTeam/AdGuardHome#4670]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version yes
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.108.0-a.148+d3f39b0a
* **How did you install AdGuard Home:**
  * usb形式在梅林系统安装
* **How did you setup DNS configuration:**
  * 使用adgardhome自身dhcp
* **If it's a router or IoT, please write device model:**
  * r8500
* **CPU architecture:**
  * armV5
* **Operating system and version:**
  * 

### Expected Behavior
进入控制程序页面出现报错Error: control/version.json | checking ability to bind privileged ports: invalid argument | 500

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

![1655261170626](https://user-images.githubusercontent.com/87486596/173725886-ca67d987-cc5c-41e8-a6dd-eb0c0a08d81b.png)

**Comment by chatbuddy21** [comment]
It seems I'm also running into the same issue. Not sure what caused it.

**Comment by yurividal** [comment]
I have the same problem

**Comment by ainar-g** [comment]
Apologies for the long silence.  We can reproduce the issue and we'll try to fix it.

**Comment by ainar-g** [comment]
@CJM88888, @yurividal, @rivalcomp, the latest Edge release, `v0.108.0-a.182+8a3d5f04`, contains a fix for this issue.  Could any one of you please check it?

**Comment by berga** [comment]
Latest version v0.107.9 fixed the problem on armv7

**Comment by ainar-g** [comment]
We'll close this issue for now.  Please feel free to open new issues if you find new bugs.

**Comment by CJM88888** [comment]
thanks

在 2022-08-04 06:57:02，"Marco Bergantin" ***@***.***> 写道：


Latest version v0.107.9 fixed the problem on armv7
