### ISSUE TITLE
Add a time between 12 and 1 hours (6 hour proposed)

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdGuardHome#4672]
### Problem Description
I have many list so updating them every hour is overkill, but the problem (when we take cache etc (of the computer)) into account 12 hours is too slow.

### Proposed Solution
Add a 6 Hours to the update list time.

### Alternatives Considered
Add a time more often than 12 hours.

### Additional Information
with cache the worst case (of not updated) become higher every time the cache is longer and to reduce dns traffic (i do use tailscale to connect to adguard) mine is quite high

**Comment by AAraonWPaul** [comment]
I think they should add a custom specified time

**Comment by ainar-g** [comment]
Apologies for the long wait.  What @AAraonWPaul said is probably what we're going to do.  Leave a few options in the UI, but also allow people to set any value either through the configuration file or through a separate input.
