### ISSUE TITLE
Question: Why does documentation say that AdGuardHome listens on 3000 when it actually listens on 3010 ?

### ISSUE THREAD

**Issue by yurivict** [AdguardTeam/AdGuardHome#4676]
Docs say [here](https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#first-time) that on the first start it "starts listening to 0.0.0.0:3000".

But the actual port is 3010:
```
2022/06/17 15:08:16.048283 [info] AdGuard Home, version 
2022/06/17 15:08:16.215378 [info] Initializing auth module: /usr/local/bin/data/sessions.db
2022/06/17 15:08:16.221140 [info] auth: initialized.  users:1  sessions:0
2022/06/17 15:08:16.221164 [info] Initialize web module
2022/06/17 15:08:16.222781 [info] AdGuard Home is available at the following addresses:
2022/06/17 15:08:16.222883 [info] Go to http://192.168.5.3:3010
2022/06/17 15:08:16.222891 [info] Go to http://192.168.5.3:3001 (BETA)
2022/06/17 15:08:16.222895 [info] Go to http://[::1]:3010
2022/06/17 15:08:16.222899 [info] Go to http://[::1]:3001 (BETA)
2022/06/17 15:08:16.222903 [info] Go to http://127.0.0.1:3010
2022/06/17 15:08:16.222907 [info] Go to http://127.0.0.1:3001 (BETA)
```

FreeBSD 13.1

**Comment by cyb3rz3us** [comment]
Perhaps this is a FreeBD specific issue but I've built four AGH servers on Rocky Linux in the last 2 weeks and all were initially accessed via TCP:3000.

**Comment by sourpatched** [comment]
Port 3000 and port 443 for HTTPs

How did you install it?

**Comment by yurivict** [comment]
> How did you install it?

From the FreeBSD package.

**Comment by sourpatched** [comment]
> > How did you install it?
> 
> From the FreeBSD package.

Yes I get that, I am guessing was via CLI? 
have you seen this? https://forums.freebsd.org/threads/guide-how-to-install-adguardhome-on-freebsd.75496/

**Comment by yurivict** [comment]
I found the reason for port=3010.

When run from /usr/local/bin it was reading the configuration saved in /usr/local/bin/AdGuardHome.yaml which had 3010.

Is there a way to place this into /usr/local/etc using CLI? (```--config``` didn't do it.)
Is there a default AdGuardHome.yaml ?

**Comment by sourpatched** [comment]
Edit  /usr/local/bin/AdGuardHome.yaml `sudo nano  /usr/local/bin/AdGuardHome.yaml` and edit the port, restart and that should fix it.

**Comment by yurivict** [comment]
How to move AdGuardHome.yaml to etc? Is there a command line switch?

**Comment by sourpatched** [comment]
Yes that is a command line command.
Adguard reads the config file as that has all the info

**Comment by yurivict** [comment]
AdGuardHome fails with the above config file:
```
$ cat ./x.yaml
bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
$ sudo /usr/local/bin/adguardhome --config ./x.yaml 
2022/07/02 19:30:32.002857 [info] AdGuard Home, version 
2022/07/02 19:30:32.003040 [info] home.upgradeSchema0to1(): called
2022/07/02 19:30:32.003068 [info] deleting /usr/local/bin/dnsfilter.txt as we don't need it anymore
2022/07/02 19:30:32.003094 [info] home.upgradeSchema1to2(): called
2022/07/02 19:30:32.003100 [info] deleting /usr/local/bin/Corefile as we don't need it anymore
2022/07/02 19:30:32.003119 [info] home.upgradeSchema2to3(): called
2022/07/02 19:30:32.003127 [fatal] dns configuration is not a map
```

**Comment by sourpatched** [comment]
> sudo /usr/local/bin/adguardhome --config ./x.yaml

Is this your start command?

**Comment by yurivict** [comment]
I wanted to try it with the config file.

**Comment by sourpatched** [comment]
> I wanted to try it with the config file.

bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0.0.0.0
users:
- name: __ADMIN__
  password: __PASSWORD__
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
0.0.0.0.0
  port: 54
  statistics_interval: 1
  querylog_enabled: true
  querylog_file_enabled: true
  querylog_interval: 90
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  - https://dns10.quad9.net/dns-query
  upstream_dns_file: ""
  bootstrap_dns:
  - 9.9.9.10
  - 149.112.112.10
  - 2620:fe::10
  - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
  - version.bind
  - id.server
  - hostname.bind
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  ipset: []
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  local_domain_name: lan
  resolve_clients: true
  local_ptr_upstreams: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: __DNS_OVER_HTTPS__
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard DNS filter
  id: 1
- enabled: false
  url: https://adaway.org/hosts.txt
  name: AdAway Default Blocklist
  id: 2
- enabled: false
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
whitelist_filters: []
user_rules: []
dhcp:
  enabled: false
  interface_name: ""
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients: []
log_compress: false
log_localtime: false
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_file: ""
verbose: false
schema_version: 10

**Comment by yurivict** [comment]
I would like to have this default config added to the FreeBSD port.
Can this default config file be committed to the repository?

**Comment by sourpatched** [comment]
You'll have to submit an issue to FreeBSD or a pull request.

**Comment by yurivict** [comment]
Ok, thanks.
