### ISSUE TITLE
AGH Service fails to install on OpenWrt

### ISSUE THREAD

**Issue by mercyground** [AdguardTeam/AdGuardHome#4677]
### Prerequisites

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details
FYI i'm reporting this on behalf of others as my existing install is fine. However, it appears since https://github.com/AdguardTeam/AdGuardHome/issues/4480 was fixed and patched in. OpenWrt installs fail to install AGH service as OpenWrt does not use systemd's update-rc. OpenWrt uses [libubox](https://openwrt.org/docs/techref/libubox)+[ubus](https://openwrt.org/docs/techref/ubus)+[procd](https://openwrt.org/docs/techref/procd).

https://forum.openwrt.org/t/how-to-updated-2021-installing-adguardhome-on-openwrt-manual-and-opkg-method/113904/257

```
starting AdGuard Home installation script
2022/06/16 11:43:34 [info] service: control action: install
6/16/2022 11:43:34 [fatal] service: executing action "install": Failed to install AdGuard Home service: command "update-rc.d" failed: exec: "update-rc.d": executable file not found in $PATH:
cannot install AdGuardHome as a service
```

Attempting this manually from the fix thread :
```
root@OpenWrt:~# sudo update-rc.d AdGuardHome defaults
sudo: update-rc.d: command not found
```

Is it possible to either check on if AGH installs correctly as a service and if the systemd method fails then you fall back to init.d method? Or even check the distribution and thus pick either systemd or init.d?

* **Version of AdGuard Home server:**
  *  v0.108.0-a.155+b04d1ed6 
* **How did you install AdGuard Home:**
  * https://forum.openwrt.org/t/how-to-updated-2021-installing-adguardhome-on-openwrt-manual-and-opkg-method

### Expected Behavior
Using the install script should install AGH and activate the service.

### Actual Behavior
Install script executes but fails to install as OpenWrt does not have systemds update-rc.d

</details>

**Comment by EugeneOne1** [comment]
@mercyground, we've just pushed the newest edge build.  It now should be able to successfully install itself as a service on OpenWrt.  Could you please check if it works?

**Comment by mercyground** [comment]
Will do. I reported back to the forum and i'll go find a spare Sdcard to try a new build and let you guys know. tyvm for the quick fix! Thread is here btw. https://forum.openwrt.org/t/how-to-updated-2021-installing-adguardhome-on-openwrt-manual-and-opkg-method/113904/265

**Comment by mercyground** [comment]
Confirmed. Clean install on the new OpenWrt 22.03.0-rc4 on a NanoPi R4S router. Thank you!

```
starting AdGuard Home installation script
2022/06/20 16:55:55 [info] service: control action: install
2022/06/20 16:55:57 [info] service: started
2022/06/20 16:55:57 [info] Almost ready!
AdGuard Home is successfully installed and will automatically start on boot.
There are a few more things that must be configured before you can use it.
Click on the link below and follow the Installation Wizard steps to finish setup.
AdGuard Home is now available at the following addresses:
```

**Comment by EugeneOne1** [comment]
@mercyground, thanks for contributing your time.
