### ISSUE TITLE
make build-docker fails with cp: cannot stat 'dist/AdGuardHome_linux_386/AdGuardHome/AdGuardHome': No such file or directory

### ISSUE THREAD

**Issue by fischer-felix** [AdguardTeam/AdGuardHome#4678]
### Issue Details

* **CPU architecture:**
  * x86
* **Operating system and version:**
  * Arch Linux 

### Expected Behavior

Running `make init`, `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes`, `docker buildx create --name buildx-builder --driver docker-container --use` and `make build-docker` builds the docker image.

### Actual Behavior

`make build-docker` fails with 
```
cp: cannot stat 'dist/AdGuardHome_linux_386/AdGuardHome/AdGuardHome': No such file or directory
make: *** [Makefile:86: build-docker] Error 1
```

### Additional Information

I tried both my local system and GitHub Codespaces, neither of which worked.
I searched, but could not figure out what should place binaries in ./dist, but maybe I missed something?

**Comment by EugeneOne1** [comment]
@fischer-felix, hello.  The thing is the Docker build is essentially a Linux build wrapped with container.  To build AdGuardHome itself use `build-release` recipe either for all platforms or for the specific combination of Architecture/OS (`linux`/`386` in case of docker).  And run `make build-docker` afterwards.  If that worked?

Consider also reading the [README](https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts#readme) in the scripts directory.

**Comment by fischer-felix** [comment]
When running `make CHANNEL='development' BUILD_SNAP='0' VERBOSE='3' SIGN='0' build-release` I now get 
```
+ log pieces don't fit, 'snapcraft' not found
+ [ 3 -gt 0 ]
+ echo pieces don't fit, 'snapcraft' not found
pieces don't fit, 'snapcraft' not found
+ exit 1
make: *** [Makefile:89: build-release] Error 1
```

**Comment by EugeneOne1** [comment]
@fischer-felix, it seems, the `snapcraft` can't be found within your environment, I suppose you haven't got it installed.  We wouldn't like to obfuscate the with checks for the needed software only but we'll consider adding an option to skip these checks.

To keep it simple you may just comment out the lines 112-130 in the `build-release.sh` script.  If it now builds the package?

**Comment by fischer-felix** [comment]
That fixed it, thanks!
