### ISSUE TITLE
Time Shown Incorrectly in DNS Blocklist

### ISSUE THREAD

**Issue by gary-hammer** [AdguardTeam/AdGuardHome#4679]
### Issue Details

* **Version of AdGuard Home server:**
  * Version: 0.108.0-a.155+b04d1ed6
* **How did you install AdGuard Home:**
  Manually using AdGuard Home directions from github
* **If it's a router or IoT, please write device model:**
  * FriendlyElec NanoPi R4S
* **CPU architecture:**
  * ARMv8 Processor rev 4
* **Operating system and version:**
  * OpenWrt 22.03.0-rc1
  * 
### Expected Behavior
Show the correct time the lists were updated.
### Actual Behavior
Shows past 23:59 as 24:xx (xx is actual minute)

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot 2022-06-17 6 29 40 AM](https://user-images.githubusercontent.com/12861605/174460455-69dfcd6c-7762-4a29-b115-2fdaaffc8e26.png)

**Comment by ainar-g** [comment]
Hello and apologies for the slow response.  Time formats on the UI depend on your browser's locale.  Can you please check, which one is used there?  Thanks.

**Comment by gary-hammer** [comment]
Hi,

I use Chrome (latest release channel) on Win 11.
I choose nothing past the stock install, so Win 11 is US English, I'd guess Chrome is the same.
I'm not aware of any locale using 24:32 as 00:32 though.
That is what is being done here.

**Comment by ainar-g** [comment]
You can check your browser's locale here: <https://www.localeplanet.com/support/browser.html>.  Please add your results here.  Make sure to check the browser where this issue can be reproduced.

Showing midnight as `24` as opposed to `00` or `12` is used in some locales, but AdGuard Home doesn't have any code to force this usage unless the locale is defined to use it.

**Comment by gary-hammer** [comment]
Here you go. It is not going to be that all my devices (PC, Chromebook,
Pop!OS, Pixel phone, iPhone) all had the locale changed.

Could the device AGH is running on have anything to do with it?

navigator.browserLanguage: undefined
navigator.language: en-US
navigator.userAgent: Mozilla/5.0 (X11; CrOS x86_64 14909.132.0)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
date: Tue Sep 06 2022 06:06:27 GMT-0400 (Eastern Daylight Time)
date.toLocaleDateString(): 9/6/2022
date.toLocaleTimeString(): 6:06:27 AM
date.toLocaleString(): 9/6/2022, 6:06:27 AM
date.toUTCString(): Tue, 06 Sep 2022 10:06:27 GMT

date.getTimezoneOffset(): 240

**Comment by ainar-g** [comment]
Thanks for the info.

 >  Could the device AGH is running on have anything to do with it?

It shouldn't, since this is a UI issue.

@Blakhard, please investigate.

**Comment by gary-hammer** [comment]
Looked good on my system.
