### ISSUE TITLE
See used Upstream DNS server

### ISSUE THREAD

**Issue by s-timm** [AdguardTeam/AdGuardHome#468]
Hello!

I have configured several upstream DNS servers in the seetings page, e.g. Cloudflare, Quad9, Google,...

Is there a way to see (in the Query Log) which Upstream DNS-Server was used?

Thanks

**Comment by hmage** [comment]
That's actually a good idea, thanks!

After we do #450, we will have access to such data and it will be easy to implement.

**Comment by ibksturm** [comment]
cool idear :)

**Comment by mHatsune** [comment]
Already implemented?

**Comment by ameshkov** [comment]
Yep, it is implemented in v0.103
