### ISSUE TITLE
Update AdGuard Home to a core22 snap package

### ISSUE THREAD

**Issue by adasiko** [AdguardTeam/AdGuardHome#4682]
- [V ] I am running the latest version
- [V ] I checked the documentation and found no answer
- [V ] I checked to make sure that this issue has not already been filed

### Problem Description
Project is currently using a core20 snap package, where core22 is the latest.

### Proposed Solution
Migration to core22

### Additional Information
https://forum.snapcraft.io/t/micro-howto-migrate-from-core20-to-core22/30188

**Comment by ainar-g** [comment]
Apologies for not noticing this earlier.  This seems to have been fixed in #4844.
