### ISSUE TITLE
Inconsistent display of client names

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#4683]
### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home, version v0.107.7
* **How did you install AdGuard Home:**
  *  GitHub release
* **How did you setup DNS configuration:**
  *  AGH DNS server assigned by DHCP in router
* **If it's a router or IoT, please write device model:**
  *  TP-Link Omada ER605
* **CPU architecture:**
  *  i686
* **Operating system and version:**
  * Debian 11

### Expected Behavior
I expect either the Canonical Name or the Alias to be displayed in the client list when reading entries from /etc/hosts

### Actual Behavior
I have an /etc/hosts file defined with a Canonical Name and and Alias defined for each client
```
192.168.10.10 my-machine.mydomain.com my-machine # MAC Address
```
On the list of Top Clients and on the Settings -> Client Settings -> Runtime Clients, some entries show the canonical name and some show the alias, seemingly at random.

I have tried altering the format of the hosts file, with a single space between each entry (default), tabs and fixed width columns, all of which made no difference.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@tescophil, hello and thanks for the report.  This is a bug actually, we're going to fix it soon.

**Comment by ainar-g** [comment]
@tescophil, the latest edge build, `v0.108.0-a.160+3505ce87`.  Could you please check if it fixes the issue for you?

**Comment by tescophil** [comment]
Happy to give this a go, but have no idea how to install a specific edge version, cant find anything in the docs...

**Comment by tescophil** [comment]
Update: Managed to find the download lionk for the latest edge version which is v0.108.0-a.161+77e5e27d

In this version the canonical name is displayed consistently for every host I have (70'ish), which was not the case with the current release.
