### ISSUE TITLE
ADGuard Home appears to not be blocking IPv6 

### ISSUE THREAD

**Issue by Thorazin** [AdguardTeam/AdGuardHome#4687]
As the title states, AdGuard Home no longer appears to be blocking IPv6 requests as they have completely disappeared from the clients list. I run AdGuard Home on a Raspberry Pi4 that runs the Ubuntu Server for ARM 64 bit OS and I installed it via command line from Github. I have made no changes to settings anywhere on my network nor to AdGuard Home itself. AdGuard Home is as up to date as it can be, ie: it is not telling me there is an update. I can not be positive because I did not notice, but this may have started after the latest update. It normally just works quietly and well on the network without interruption and I generally leave it alone. I have Comcast gig internet and a Comcast provided router/wifi device.

<img width="1605" alt="Screen Shot 2022-06-23 at 10 42 30 AM" src="https://user-images.githubusercontent.com/36058075/175341012-72bb17d7-bcf1-4816-9518-4949dd1c90ba.png">

**Comment by Thorazin** [comment]
I solved my own problem. Turns out the IPv6 addresses had changed, probably when Comcast did a reboot of my router/modem over night.

**Comment by jeromelarras** [comment]
hi 

how can i make a dhcp bail for ipv6 please
is there some missing on dchp parameters ?

thanks

**Comment by jeromelarras** [comment]
hi  i found it
i've putt the information in Persistant Client part

another thing, how can i make valid certificate  to secure it

thanks
