### ISSUE TITLE
Issue with Opnsense integration

### ISSUE THREAD

**Issue by 3suns-org** [AdguardTeam/AdGuardHome#4690]
### Issue Details

* **Version of AdGuard Home server:**
  * 0.107.7
* **How did you install AdGuard Home:**
  * Opnsense integration
* **How did you setup DNS configuration:**
  * System->Router
* **If it's a router or IoT, please write device model:**
  * Opnsense
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Opnsense

### Expected Behavior
Service should be running

### Actual Behavior
Service stops and internet access stops as a result

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by 3suns-org** [comment]
Any thoughts here? This continues to fail.

**Comment by ainar-g** [comment]
Hello.  There isn't a lot of information, and we aren't the ones maintaining the Opnsense integration, so you're better off asking the people who do.  You should also be able to [configure][1] AdGuard Home to collect logs by setting  `verbose` to `true`and see if there are any error messages there that could clarify the situation.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by 3suns-org** [comment]
Who maintains it so that I can reach out directly?



________________________________

**Comment by ainar-g** [comment]
I think, it's this one: <https://github.com/mimugmail/opn-repo>.  But even if you file an issue there, please check (and, possibly, attach) the verbose logs.
