### ISSUE TITLE
Can't save wildcard domain in Encryption settings

### ISSUE THREAD

**Issue by STaRDoGG** [AdguardTeam/AdGuardHome#4694]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.7
* **How did you install AdGuard Home:**
  * Docker

### Expected Behavior

Ability to enter/save a wildcard domain to match it's cert.

### Actual Behavior

Inability to do the above (see screenshot).

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/1524526/175777739-74d25986-266f-48ac-9286-636577e3f54f.png)
</details>

### Additional Information

If I remove the `*.` from the domain name, it shows the error:

> Your certificate does not verify: x509: certificate is valid for *.redacted.rocks, not redacted.rocks

BUT I **can** save the config. If I add the `*.`, the error is gone and it verifies correctly, but the 'save config' button gets grayed out and unable to save the config.

**Comment by ainar-g** [comment]
Apologies for this slipping through the cracks.  Is this still an issue on the most recent releases?

Also, just to be clear, are you sure that you want to use a certificate that is only valid for `*.???.rocks` as opposed to both that and `???.rocks`?  That means that users will only be able to use it with ClientIDs.

**Comment by STaRDoGG** [comment]
@ainar-g Thanks, at least ya noticed eventully, lol.

It's been a while since I've messed with it, maybe because I got stuck there, I forget offhand, so I'll have to revisit it and check out where I left off, and then I'll report back (it might be a few days though, as I'm particularly busy atm). =)

**Comment by STaRDoGG** [comment]
Hi @ainar-g 

I'm finally getting a quick chance to mess with this again, and it is still behaving exactly the same way in Version: v0.107.16

Regarding the cert: I'm using the SWAG container to generate the certs automatically for my domains, and that's what it's creating. I have SWAG setup to use wildcard certs for any *.mydomain.rocks.

I use docker to run a bunch of services at home, all on subdomains, while hosting the root domain on a shared host accessible to the world.

I'm _cert_ainly :p no cert wizard, so may have this config not setup ideally due to ignorance, but chose not to have SWAG create a cert for just the root domain alone, as I'm not really sure how that might conflict with the one generated for that root domain by my shared host, both of which are using LetsEncrypt as it's free cert provider). (i.e. if I have my shared host generating one for mydomain.rocks, and also having SWAG generating one for the same mydomain.rocks).

I chose this mostly due to keeping things simple, and not having to manually copy cert files around all over the place and maintain them if/when something ever changes with them.

**Comment by overwatch3560** [comment]
@STaRDoGG is it still an issue?

**Comment by STaRDoGG** [comment]
> @STaRDoGG is it still an issue?

TBH I don't even know; I gave on on Adguard for now, for several reasons. One day I'll revisit it.

**Comment by overwatch3560** [comment]
@STaRDoGG then for now I wish you a very nice rest of your day and we hope to see you back soon! If you encounter any issues you know where to find us!
