### ISSUE TITLE
ipv6 does not fit in column

### ISSUE THREAD

**Issue by IgorKha** [AdguardTeam/AdGuardHome#4697]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.7
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Actual Behavior

ipv6 does not fit in column
### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20220627_163241](https://user-images.githubusercontent.com/2268209/175956395-74ac87a2-7f7c-4dd9-ba32-7c5cb2b1f9ce.png)

</details>

**Comment by fernvenue** [comment]
So what's your point? And what is your expected behavior? We can easily see the full address by hovering over it, and we can also add devices as clients based on IP or other information. Do you have a better solution about that?

**Comment by ainar-g** [comment]
Apologies for the slow response.

@IldarKamalov, can we somehow extend the space for those cells without hurting the readability of other columns?  I feel like there should be plenty of space, but perhaps there are other issues?
