### ISSUE TITLE
DNS resolving 127.0.0.1 for my domain

### ISSUE THREAD

**Issue by BaldEagleX02** [AdguardTeam/AdGuardHome#470]
I have installed AdGuard Home on my Raspberry Pi. 

When I resolve the RPi's hostname using the installed DNS it returns 127.0.0.1, so I tried setting `RPiPublicIP RPiHostname` in my rules but it doesn't work. 
I also checked the .yaml file but it is OK (my rule is installed correctly). 
What can I do to fix this issue?

**Comment by ameshkov** [comment]
@BaldEagleX02 what's the exact hostname just in case? We'll try reproducing it on our end.

**Comment by ameshkov** [comment]
Chrome? It might be caching old DNS records, try clearing its own cache:
chrome://net-internals/#dns

**Comment by BaldEagleX02** [comment]
I retried and it worked. Firefox was caching DNS records so when I changed the rules they weren't working as expected.

**Comment by BaldEagleX02** [comment]
Hoverer before I had changed the rules it was returning 127.0.0.1. Why?

**Comment by BaldEagleX02** [comment]
The problem is solved anyway

**Comment by hmage** [comment]
@BaldEagleX02 
> Hoverer before I had changed the rules it was returning 127.0.0.1. Why?

Is it possible that you had the same hostname listed in custom rules or additional hosts-format filters that you've added in the settings?

Thanks for reporting the issue either way ^.^
