### ISSUE TITLE
 [error] handling tcp: reading msg: reading msg: unexpected EOF

### ISSUE THREAD

**Issue by lioArther** [AdguardTeam/AdGuardHome#4716]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ✓] I am running the latest version
- [ ✓] I checked the documentation and found no answer
- [ ✓] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
version v0.107.7
* **How did you install AdGuard Home:**
Portainer
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
QNAP TS-464C
* **CPU architecture:**
x86
* **Operating system and version:**
QNAP Systems 5.0.0.2055（2022/05/31）

### Expected Behavior
After the installation is complete, you can enter the settings panel port and DNS port page normally. Once created, you can no longer enter

### Actual Behavior
After the installation is complete, you can enter the settings panel port and DNS port page normally. Once created, you can no longer enter
### Screenshots

![1](https://user-images.githubusercontent.com/27990398/177775778-df3baa10-5c75-435d-82e4-c88e9ea78bb8.png)
![2](https://user-images.githubusercontent.com/27990398/177775801-68a234f2-511c-4e38-a5ac-05e539f46712.png)
![3](https://user-images.githubusercontent.com/27990398/177775811-f60d53ea-32fa-4501-b882-dbf2edcdc87b.png)
![4](https://user-images.githubusercontent.com/27990398/177775821-15ef5a04-59d0-4f15-9ae0-aabe821c558f.png)
![5](https://user-images.githubusercontent.com/27990398/177775825-fc6eb95b-4123-46b5-aacd-e438e92cfd46.png)
![6](https://user-images.githubusercontent.com/27990398/177775830-8b154918-75b4-4fa2-8938-21c7e49488b9.png)

**Comment by ainar-g** [comment]
Apologies for the long wait.  I cannot quite understand, what the problem is.  If you're worried about the error message, please see the comment in #4859.  If not, please describe the issue in more detail, in any language you're comfortable with.

**Comment by ainar-g** [comment]
No response for over a year.  Closing.
