### ISSUE TITLE
ios 16 no ip route in agh.

### ISSUE THREAD

**Issue by kuduacz** [AdguardTeam/AdGuardHome#4718]
Hi there.
Im running on my iphone on ios 16 beta.
Configure my router to route via agh and my iphone via agh too.
Other mobile phones work same as my iphone. And when i run some site i can see it in agh querry log by client.
When i try to run some page on my iphone log is under router client/ no iphone ip adress.
why? and how to fix it?
i have enabled private wifi adress and limit ip adress tracking.

Latest agh and HA

**Comment by riiveraluis** [comment]
Limit IP address tracking if you have iCloud+ uses cloudfare dns and not your manual dns settings.

**Comment by ainar-g** [comment]
Hello and apologies for the belated response.  Do you have iCloud Private Relay or any other VPN on?  Those will often use their own DNS servers.
