### ISSUE TITLE
Update button doesn’t update

### ISSUE THREAD

**Issue by paulux666** [AdguardTeam/AdGuardHome#4721]
- [no ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [na ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.102
* **How did you install AdGuard Home:**
  * wget GitHub 
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  *  Raspberry Pi 3 Model B
* **CPU architecture:**
Arm
* **Operating system and version:**
  * raspberian lite

### Expected Behavior

Clicking the update button, resulting in updating the software. And or at the notice a button to update

### Actual Behavior

Nothing happens except a message. No update button at the new available notice

### Screenshots

![1C4B968C-B483-4569-8B1B-2336EEC69467](https://user-images.githubusercontent.com/38701184/177921533-36e82b87-f437-4666-a7aa-1e4fe38d9829.jpeg)
![A4F2EC9C-B23B-4E8F-BA3B-E8A993B550BB](https://user-images.githubusercontent.com/38701184/177921537-c026f9e0-039d-4cf8-b395-d66ee09fb030.jpeg)

<details><summary>Screenshot:</summary>

</details>

**Comment by fernvenue** [comment]
You can get more information from verbose log, or you can just follow the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update) to update the AdGuardHome manually.

**Comment by ainar-g** [comment]
Apologies for the long silence.  We've made several improvements to the autoupdate feature in the latest releases.  Could you please check if this is still an issue?  Thanks!

**Comment by paulux666** [comment]
Dear adguard team,

I switched back to pihole, I’ll fire up the docker for adguard and have a check
(Will take some time for testing)
Thanks for the follow up!!

Regards

Paul Arts

**Comment by overwatch3560** [comment]
Has it worked @paulux666 ?

**Comment by paulux666** [comment]
Looks like it works.I’m running the release from feb .44Initial install was done last summer .35/36So it updated correctly multiple times now( sorry for the late update.. and thanks for the reminder)Regards,PaulOn 25 Mar 2024, at 18:15, overwatch3560 ***@***.***> wrote:﻿
Has it worked @paulux666 ?

**Comment by overwatch3560** [comment]
not a problem at all, if you have any other issues we are always open to help you out!
Have a nice rest of your morning, afternoon or evening wherever you are!
