### ISSUE TITLE
Content leak using familyshield_dns

### ISSUE THREAD

**Issue by navigos** [AdguardTeam/AdGuardHome#4724]
- [ok] I am running the latest version
- [ok] I checked the documentation and found no answer
- [ok] I checked to make sure that this issue has not already been filed

- OpenWrt 21.02.3
- Adguardhome 0.107.6-1

### Problem Description

I have adguardhome installed on openwrt.
I set familyshield.opendns.com and family.cloudflare-dns.com to block adult content. With this the sites are properly blocked.
I also tried with the AdGuard parental control service.
But on google, when searching xvideo and switching to the images tab, it is possible to view multiple images from that site.

### Proposed Solution

Block loading of images, videos, etc. from the locked domain?

### Alternatives Considered

Google's Safesearch fulfills this purpose. (easy bypass)

### Additional Information

Maybe not possible due to https? Cache google?
Without this feature, all it takes is one additional click and images or videos and children are exposed.

**Comment by ainar-g** [comment]
Hello and apologies for the late response.  There is no way to block particular images using DNS blocking.  You can enable AdGuard Home's Safe Search feature, which will return the safe search IPs in response to all `google.TLD` queries, which should solve the issue.

**Comment by navigos** [comment]
Tanks @ainar-g 
Easy!!!
