### ISSUE TITLE
Specific Client IP does not get DNS rewritten

### ISSUE THREAD

**Issue by PsclDev** [AdguardTeam/AdGuardHome#4725]
### Issue Details

* **Version of AdGuard Home server:**
  * Version: v0.107.7
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * FritzBox Router
* **If it's a router or IoT, please write device model:**
  * FritzBox 5730
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 11

### Expected Behavior
If I do `dig` `ping` or `http` request, it should rewrite it to a internal ip and resolve it correctly.

### Actual Behavior
Every Request from and just only from any client with the IP `10.0.0.11` doesn't get rewritten. They get passed to a public DNS which does not resolve a valid ip. Because everything is inside a local network.

Any other IP of my network are not having this issue. There is no filters or rules applied, just DNS rewrites

In the Screenshots section there are two examples, one from the IP with the problem and another request which is rewritten correctly

### Screenshots
<details><summary>Screenshot:</summary>
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/25869641/178053061-9e73e779-b846-4b06-91c7-273148589754.png">
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/25869641/178053093-2ca3e459-7501-4566-ad4b-5d90ba5d5b3f.png">
</details>

### Additional Information
I have analysed a TCPDump of my Host System where AdGuard is running and there is no Issue with the request before it gets to AdGuard.

**Comment by jchhenderson** [comment]
DNS rewrites don't work for me at all since upgrading to 0.107.8 - not sure if that it a coincidance though.  DNS rewrites has always been flaky for me and I have given up on it - not worth the hassle when it stops working.

**Comment by jchhenderson** [comment]
Thanks for replying 👍 

I'm not sure, tbh.  I think the problem may have been related to the tld (.local or similar).  I'll have another go and report back.
