### ISSUE TITLE
Request header Fields Too Large

### ISSUE THREAD

**Issue by grasshide** [AdguardTeam/AdGuardHome#4727]
Since I fully switched to IPv6, the overview page with the statistics are no longer working.
I'm getting a red error box telling me "Error control/clients/find?ip0=start_of_one_of_my_IPv6_addresses_here | 431 Request Header Fields Too Large | 431"
I can go to Settings and Flush all statistics, then it works for a little while. I guess to the point where to many different clients are in the stats so that the Request Header Field gets too Large.

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.107.7
* **How did you install AdGuard Home:**
official docker image
* **How did you setup DNS configuration:**
Router
* **If it's a router or IoT, please write device model:**
Unifi USG
* **CPU architecture:**
AMD64
* **Operating system and version:**
Debian Bullseye

### Expected Behavior
Stats are shown despite the long IPv6 addresses

### Actual Behavior
Stats page shows an error. All values are set to 0.

**Comment by EugeneOne1** [comment]
@grasshide, hello and apologies for the late response.  Unfortunately we can't reproduce it on our machines, a hundred of full IPv6 addresses is handled as expected.  Have you got some kind of proxy behind the AdGuard Home's web interface?  Also could you please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  You may send it to the devteam@adguard.com.

**Comment by Sebclem** [comment]
Hello,
I had the same issue and i found out this was caused by Authelia.
I had to increase `server.buffers.read` in config:
```yaml
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 8184
```

**Comment by grasshide** [comment]
> Hello, I had the same issue and i found out this was caused by Authelia. I had to increase `server.buffers.read` in config:
> 
> ```yaml
> server:
>   host: 0.0.0.0
>   port: 9091
>   buffers:
>     read: 8184
> ```

Oh wow, I would never have guessed this. No idea how you found this ;-).
I'm in fact using Authelia. Most probably this will be the fix for me as well.
Unfortunately I just erased all history so that I currently don't have the issue.
I'll close the case and reopen it should the problem remain.
Thanks @Sebclem for the hint!
