### ISSUE TITLE
feature request: blocking aaaa (ipv6) records

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#473]
hi guys
background:
cause of my .... isp im running a ipv6 tunnel (tunnelbroker) over my homenetwork

netflix now think i use a vpn to kickout country regulations. so earlier this evening video get blocket

the solutions was in the middle of the night, that i abused an instanz of dnscrypt-proxy where i deactivated AAAA ipv6 records that belongs to netflix.com . so only A ipv4 records would deploy. 

so my idear is now, that would be a nice little feature in future :) maybe when you hacked the dns zone files, there will be an option for „ipv4 only“ records #461

greets and good night

**Comment by ArchiveBase** [comment]
_Seems no upvotes for this request_ 🥺 

![image](https://user-images.githubusercontent.com/46082456/67146200-fdf05f80-f2b2-11e9-97fe-0ac7daebdd3b.png)

**Comment by ameshkov** [comment]
@szolin this setting should available in the program UI.

Requires this first:
https://github.com/AdguardTeam/dnsproxy/issues/70
