### ISSUE TITLE
Recursive agh-backup directories

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#4734]
It seems like AGH will sometimes put a previous `agh-backup/` directory into the new `agh-backup/`, for example `agh-backup/agh-backup/agh-backup/`.  Which is not the desired behaviour, since it creates a tree-like structure of previous AGH installations.

We must find out, how that happens, and prevent that from happening in the future.

**Comment by Mizzick** [comment]
The problem was an incorrect path of an executable and actually has been fixed in 1eafb4e7cf64f0027674e59e4a4b5ccc33c44c43.
