### ISSUE TITLE
Allow list

### ISSUE THREAD

**Issue by i-DeWalt** [AdguardTeam/AdGuardHome#4737]
Hello, I've been struggling with figuring how to add to the allow list OwletCare. They use a few different domains, however for some reason AdGuard is blocking functionality to the Owlet App. 

Can you please give me an example for an allow list to add:

www.owletcare.com

**Comment by fernvenue** [comment]
Hi @i-DeWalt, you can simply allow that domain and all its subdomains like this:

```
@@||owletcare.com^
```

And you can read this [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#basic-examples) for more.

![screenshot](https://user-images.githubusercontent.com/84565547/178656235-52efe349-a772-4184-8b20-18a8d5107a79.png)

Actually, you can also unblock some domains for one or all devices in Web UI like above.
