### ISSUE TITLE
can't use 0.0.0.0 to bind all ipv4&ipv6address,if use 0.0.0.0,ipv6 or ipv4 will have one don't work

### ISSUE THREAD

**Issue by c15412** [AdguardTeam/AdGuardHome#4739]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * AdGuard Home, version v0.107.7
* **How did you install AdGuard Home:**
  * GitHub releases
* **How did you setup DNS configuration:**
  * System
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Windows 11 InsiderPreview dev 25151.1000

### Expected Behavior

My native language is not English, so please forgive me if there are any mistakes
I try to use 0.0.0.0 on setting to bind all ip address,but it failed.The program received the request, but other programs and the host did not receive the program's response,only ipv4 or only ipv6 can receive a response,
and I try to use :: or [::] ,the ADGuard Home has quit
I add ipv6 address like the screenshot,it works well
![image](https://user-images.githubusercontent.com/70379135/178741551-862eea60-0080-4880-ba54-6baf8947b7de.png)

### Screenshots

![image](https://user-images.githubusercontent.com/70379135/178740010-2b3bcdd7-c32b-449e-96a0-25e2738b1362.png)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/70379135/178740010-2b3bcdd7-c32b-449e-96a0-25e2738b1362.png)

</details>

**Comment by agneevX** [comment]
Please provide logs.

**Comment by c15412** [comment]
> Please provide logs.

I'm sorry to trouble you, I forgot to save the log. After I restarted my computer, the problem disappeared. There may be bugs in the system firewall rules of Windows 11 Insider Preview

**Comment by c15412** [comment]
> Please provide logs.

I had this problem again today

Could you please tell me how to export the log? After I set the path for the log item in the configuration file and restart AdGuard, it will crash.
I set the path d:/logs.txt

**Comment by Birbber** [comment]
@c15412 Hi! Sorry for the long silence. Is this issue still actual?
Have you already seen [the instruction](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) on how to configure AdGuard Home to collect the verbose logs?

**Comment by c15412** [comment]
It looks like this issue is fixed/disappeared with the update of ADGuard Home as well as the update of Windows
I will continue to use ADGuard Home, so as soon as I encounter any bugs, I will submit Issues again
