### ISSUE TITLE
Notify users that a page is blocked by the browsing security filter

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardHome#474]
Is it possible to show a dummy page instead of what we have now?

![image](https://user-images.githubusercontent.com/15856304/49684780-4232a100-fae1-11e8-8c27-c8813e0c6d0d.png)

**Comment by sc0rp10** [comment]
@Eugene-Savenko should be fixed now. Can you please check it?

**Comment by Eugene-Savenko** [comment]
@sc0rp10 Works fine, thank you.
