### ISSUE TITLE
Lots of timeouts since v0.107.7

### ISSUE THREAD

**Issue by pattyland** [AdguardTeam/AdGuardHome#4740]
#4568 ## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.107.7
* **How did you install AdGuard Home:**
  * Docker/Home Assistant Addon
* **How did you setup DNS configuration:**
  * via external DHCP Server
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  *  x86-64
* **Operating system and version:**
  * Home Assistant OS

### Expected Behavior

Fast lookups like in v0.107.6

### Actual Behavior

Since the update to v0.107.7 I often get timeouts while resolving hostnames. I'm using AGH since years without these problems

test in cmd:
```
C:\Users\x>nslookup test.de 192.168.178.3
Server:  UnKnown
Address:  192.168.178.3

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Zeitüberschreitung bei Anforderung an UnKnown.

C:\Users\x>nslookup test.de 192.168.178.3
Server:  UnKnown
Address:  192.168.178.3

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Zeitüberschreitung bei Anforderung an UnKnown.

C:\Users\x>nslookup test.de 192.168.178.3
Server:  UnKnown
Address:  192.168.178.3

Nicht autorisierende Antwort:
Name:    test.de
Address:  20.101.0.28
```

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Upstream DNS servers:
quic://dns-unfiltered.adguard.com:784
[/local/]192.168.178.1:53

Bootstrap DNS servers: 9.9.9.10
149.112.112.10
2620:fe::10
2620:fe::fe:10

**Comment by jbg** [comment]
Also experiencing this, with 1.1.1.1 as upstream. Rolling back to 0.107.6 immediately fixes it.

**Comment by pattyland** [comment]
@ainar-g I postet my upstreams in the first post. I use "Parallel requests" as upstream modes.

Since the update, the only way to monitor AGH: `nslookup -timeout=1 $RANDOM.neverssl.com 192.168.178.3 | grep "Non-authoritative answer" | wc -l`

Each red bar is a failure of more than 5 failed lookups in 5 minutes:
![agh_fail](https://user-images.githubusercontent.com/838758/181042405-8bbd5853-798b-403e-9e94-7fdcaac7572e.jpg)

**Comment by ainar-g** [comment]
Thanks for the info and for the metrics to detect that!  We'll investigate further.

**Comment by ainar-g** [comment]
So far, the only timeouts we've observed were either from the upstream itself or from the Safe Browsing and Parental Control services.  Do you have those on?  Also, does changing the upstream to a DoH one improve the situation?

If not, can you [configure][1] AdGuard Home to collect logs by setting  `verbose` to `true`, reproduce the timeouts, and send the logs to us at devteam@adguard.com (with the words “AdGuard Home Issue 4740” in the subject line)?  Thanks!


[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by marufmax** [comment]
Tried using google and cloudflare dns as upstream, still getting timeout for reddit.com

**Comment by finzzz** [comment]
it has less timeouts with DoH/DoT, I thought my IP gets rate limited for some reasons.

**Comment by ainar-g** [comment]
No response for over a year, closing.

**Comment by fribse** [comment]
I think I have found the culprit for my breakdown of adguardhome, reverse dns, it was enabled, and set to the wrong server. Setting it right, made it respond properly again.
