### ISSUE TITLE
DHCP lease created with empty hostname 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardHome#4745]
### Issue Details
Steps to reproduce: 
1. Enable DHCP server 
2. Configure DHCP IPv4 settings 
3. Add DHCP static lease with name Example
4. Use command `udhcpc -x hostname:'Example'` from the client with different MAC address to create a temporary lease with the same name.

* **Version of AdGuard Home server:**
  * v.0107.8
* **How did you install AdGuard Home:**
  * Snapcraft
* **How did you setup DNS configuration:**
  * classic set up
* **If it's a router or IoT, please write device model:**
  * Lenovo 
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Ubuntu 20.04.4 LTS

### Expected Behavior
Temporary lease created with the requested hostname

### Actual Behavior
Temporary lease created with an empty hostname

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by EugeneOne1** [comment]
@Versty, hello.  Unfortunately, we can't reproduce it on our machines.  Could you please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) to help us troubleshoot the issue?  It'll really help if you'll send those to devteam@adguard.com with the **Issue 4745** in the subject.
