### ISSUE TITLE
Add adguardhome to the umbrel app store

### ISSUE THREAD

**Issue by BirbEXE** [AdguardTeam/AdGuardHome#4749]
Hey all.

I'm here to request that an umbrel integration be made for adguardhome.

Umbrel is a server "OS" if you will, with a built in app store. 
The integration would allow a one-click install for adguardhome.

Pi-Hole already has an integration on umbrel, but I still prefer adguardhome and would like to be able to use it on umbrel.

here's the instructions for umbrel's super simple app framework

https://github.com/getumbrel/umbrel-apps#readme

**Comment by ainar-g** [comment]
Hello and apologies for the long silence.  We do not plan on adding official support for any new package managers.  Community members are free to support these on their own.
