### ISSUE TITLE
Query Log problem with ip address filtering

### ISSUE THREAD

**Issue by majer2022** [AdguardTeam/AdGuardHome#4752]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

if i enter address  in Query Log 192.168.1.10 i gets a list of addresses
192.168.1.10 and 192.168.1.101

**Comment by cyb3rz3us** [comment]
This seems valid to me as the search engine cannot assume when you are done typing.

For example, if you were to just type `192.168.1`, you should get all entires with those first 3 octets.  Or consider URLs - you may have `example1.com` and `example2.com` in the query log.  Would you agree that both be shown if you only type `example`?

**Comment by RonKhondji** [comment]
![firefox_roFB7jjs4H](https://user-images.githubusercontent.com/6552970/179395266-ef909d49-8971-43c9-b9a2-91a1a66e1230.png)

**Comment by majer2022** [comment]
Thx RonKhondji  everything works
