### ISSUE TITLE
Update without update ? AGH want Update from Beta .10 to b.9 ?!?

### ISSUE THREAD

**Issue by whyisthisbroken** [AdguardTeam/AdGuardHome#4768]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.108.0-b.10

### Actual Behavior
AdGuard would be update to Version v0.108.0-b.9, but i have Version v0.108.0-b.10 installed ? What´s happening here ?

### Screenshots
![3](https://user-images.githubusercontent.com/96284773/180244688-62f8d595-2599-4a42-884f-b73ac10273a6.jpg)
![2](https://user-images.githubusercontent.com/96284773/180244691-4c165100-a240-41c1-a088-cd495b8ee54c.jpg)
![1](https://user-images.githubusercontent.com/96284773/180244693-62527e35-19ce-413f-b025-3c945deeedb9.jpg)

If i hit the Update Button, AGH get a update and then it is b.9. But i dont get a update offer for b.10. 

I restored my Raspi Backup and let it run now with the Update Notification. Would be nice if someone can get me some infos..

**Comment by ainar-g** [comment]
Hello and thanks for the report.  It seems like there were issues with CDN caching.  The issue should be fixed by now.  Can you please check if the message disappears when you restart AdGuard Home or recheck updates now?

**Comment by whyisthisbroken** [comment]
Hi,

yep it´s gone.  i restarted AGH and the Update Notification dont appear again.

Thx for the quick support :)
