### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by arymas49** [AdguardTeam/AdGuardHome#4771]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [* ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

Hello, greetings.
I am an adguard home user.
I would like a suggestion, it's better to add a dark display theme.
so there are 2 choices of themes, dark and light.
Thank you

**Comment by whyisthisbroken** [comment]
> * [* ] I checked the documentation and found no answer

Really?

https://github.com/AdguardTeam/AdGuardHome/issues/613
