### ISSUE TITLE
Ошибка сети при использовании HTTP/3 в NGINX реверс-прокс

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#4772]
Здравствуйте,

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

* **Version of AdGuard Home server:**
  * v0.107.8
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * System and Router
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian GNU/Linux 11 (bullseye), Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

Я использую NGINX с поддержкой QUIC качестве реверс-прокси. Всё работает исправно, но периодически получаю ошибку сети при работе в GUI:

![image](https://user-images.githubusercontent.com/45385632/180611164-7d89f9f4-dc30-4a88-b3be-e830bf00bf99.png)

При подключении по HTTP/2 такой ошибки нет. Во время ошибки в логе NGINX:

```
2022/07/23 15:12:57 [error] 7#7: *99 failed to send stream cancellation while closing request, client: 46.242.14.23, server: 0.0.0.0:8443
46.242.14.23 - - [23/Jul/2022:15:12:57 +0000] "POST /control/filtering/set_rules HTTP/3.0" 400 0 "https://dns.ammnt.app/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15"
```

Dockerfile тут:
https://gist.github.com/ammnt/cbad6052bba62ee8199f36b477cd038f

Docker-compose файл тут:
https://gist.github.com/ammnt/58f62740b711b9df658169b7993c1b93

Образ тут:
https://hub.docker.com/r/ammnt/nginx

Verbose-лог AdGuard Home тут:
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/9174042/log.txt)

Прошу помочь разобраться почему проблема возникает именно в таком контексте😒

Спасибо.

**Comment by ainar-g** [comment]
Добрый день.  HTTP API AdGuard Home не поддерживает HTTP/3 в настоящий момент.  В стандартную библиотеку языка го ещё не добавили.  Есть сторонние имплементации, но их надо проинспектировать перед добавлением.

Поэтому, объединяю с #3955.

**Comment by ammnt** [comment]
@ainar-g, я извиняюсь, но честно говоря не совсем понятен ответ. Я знаю что AGH не поддерживает сейчас HTTP/3, ведь тикет #3955 писал тоже я😀 Но неужели AGH на бэкенде тоже должен поддерживать HTTP/3 для работы NGINX как реверс-прокси на фронтенде, чтобы не было ошибок. Сетевая ошибка же возникает только при работе с полями фильтров🙂

**Comment by ainar-g** [comment]
Это зависит от того, как Nginx обращается к AGH.  AGH сейчас не поддерживает HTTP/3 ни в обработчике DNS-over-HTTPS, ни в обработчике HTTP API («морде»), ни в других обработчиках.  Из вашей конфигурации я, честно говоря, не понял, какую версию протокола использует ваш Nginx для доступа к AGH, но если там используется HTTP/3, то проблема очевидна.  А если там не он, то я бы сказал, что дело вообще не в AdGuard Home.

**Comment by ammnt** [comment]
@ainar-g, к сожалению проблема до сих пор сохраняется. Я перепробовал все возможные решения и при использовании HTTP/3 я стабильно получаю ошибку:
![2022-10-05_19-50-48](https://user-images.githubusercontent.com/45385632/194117347-36857445-5d63-47b2-87f0-1496fc2d6954.png)
![2022-10-05_19-51-20](https://user-images.githubusercontent.com/45385632/194117365-84c3afd8-bfc6-46c8-a27c-ffd83553d61d.png)

Сбой происходит только при взаимодействиями с элементами UI. Всё остальное, в том числе DoH работает исправно.

**Comment by ainar-g** [comment]
@ammnt, если проблема только в одном браузере, то вероятнее всего проблема в нём, и мы с этим вряд ли что-то можем сделать.

Если у вас на клиентской машине Windows, вот тут есть обсуждение схожей проблемы: <https://serverfault.com/q/131935>.
