### ISSUE TITLE
adguardhome doesn't show its version

### ISSUE THREAD

**Issue by yurivict** [AdguardTeam/AdGuardHome#4774]
When ```adguardhome``` is installed from the FreeBSD port it doesn't show its version:
```
$ adguardhome  -v
2022/07/24 10:27:31.863848 64717#1 [info] AdGuard Home, version 
2022/07/24 10:27:31.863916 64717#1 [debug] current working directory is /usr/local/bin
2022/07/24 10:27:31.863950 64717#1 [info] This is the first time AdGuard Home is launched
2022/07/24 10:27:31.863973 64717#1 [info] Checking if AdGuard Home has necessary permissions
2022/07/24 10:27:31.863998 64717#1 [fatal] This is the first launch of AdGuard Home. You must run it as Administrator.
```

The version is blank.

Where does the version information normally come from?

**Comment by ainar-g** [comment]
This seems like an issue with the FreeBSD port, to be honest.  This isn't the first time that a third-party builder doesn't set one of the parameters during build.  Please notify the port maintainers and point them to [our documentation about building AdGuard Home releases][1].  Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/tree/master/scripts#build-releasesh-build-a-release-for-all-platforms
