### ISSUE TITLE
关于DNS重写提议-About DNS rewrite proposal

### ISSUE THREAD

**Issue by hc990275** [AdguardTeam/AdGuardHome#4779]
希望可以增加网络获取DNS重写的规则，就像DNS拦截那样的网络获取。
It is hoped that the rules of network access DNS rewrite can be increased, such as network access like DNS interception.

**Comment by fernvenue** [comment]
Actually, you can use DNS block lists as rewrite rules, that is the same thing, just write your rewrite rules in your online DNS block lists and add it to the AdGuardHome. For examples:

```
# Rewrite multiple domains to specific IP
/^(example1|example2).example.com/$important,dnsrewrite=192.0.2.1

# Rewrite one domain to specific IP.
192.0.2.2 example3.example.com

# Rewrite one domain to another domain.
example3.example.com$dnsrewrite=example4.example.com

...
```

For more information, you can just read the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite).

**Comment by ainar-g** [comment]
@hc990275, could you please provide a more concrete example of what you're trying to achieve?  Thanks.

**Comment by hc990275** [comment]
首先感谢您能看到并回答我的问题，我的意思是，在DNS重写这里可以像，DNS拦截列表一样可以添加自己的用一些重写数据，否则一项一项的在网页里添加有点耗时间。



---原始邮件---
发件人: "Ainar ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdGuardHome] 关于DNS重写提议-About DNS rewrite proposal (Issue #4779)




 
@hc990275, could you please provide a more concrete example of what you're trying to achieve?  Thanks.

**Comment by hc990275** [comment]
我感觉电脑操作好编写，放在服务器更新也可以给我朋友们用



---原始邮件---
发件人: "Ainar ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上8:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdGuardHome] 关于DNS重写提议-About DNS rewrite proposal (Issue #4779)




 
@hc990275, see fernvenue's answer above.  dnsrewrite rules allow you do perform many types of DNS rewrites, and they work in blocklists as well, so you can put them into a list.
 
Does that work for you, or is something lacking in this feature?

**Comment by fernvenue** [comment]
@hc990275 As I said, you can just use online DNS block lists as online Rewrite rules.

**Comment by hc990275** [comment]
好的谢谢，我去尝试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月28日(周四) 晚上9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdguardTeam/AdGuardHome] 关于DNS重写提议-About DNS rewrite proposal (Issue #4779)




 
@hc990275 As I said, you can just use online DNS block lists as online Rewrite rules.

**Comment by fernvenue** [comment]
I'm going to give you some examples, and you can write your own rules like them:

```
ad.mi.com$dnsrewrite=124.71.226.17
/^(ad|ad1).xiaomi.com/$dnsrewrite=124.71.226.17
...
```

You can use whatever is convenient for you, or you can even write hosts style:

```
124.71.226.17 ad.mi.com
124.71.226.17 ad.xiaomi.com
124.71.226.17 ad1.xiaomi.com
...
```

They all work well, and just as I said above, actually you can read the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite) to learn how to rewrite them.
