### ISSUE TITLE
Client ID does not work in DoT and DoQ

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdGuardHome#4782]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
v0.108.0-b.10
* **How did you install AdGuard Home:**
GitHub Release
* **How did you setup DNS configuration:**
Dedicated server
* **If it's a router or IoT, please write device model:**
Dedicated server
* **CPU architecture:**
AMD64
* **Operating system and version:**
Debian 11

### Expected Behavior

When requesting DNS via `tls://<client-id>.domain.tld` and `quic://<client-id>.domain.tld`, AdGuard Home should be able to correctly identify the Client ID and display it in the statistics.

### Actual Behavior

The statistics do not show the Client ID, but only the IP address of the requesting party. Only DoH (`https://domain.tld/dns-query/<client-id>`) can be correctly counted as Client ID.

AdGuard Home has a wildcard certificate containing SAN `*.domain.tld` and has properly added wildcard DNS resolution.

The Server Name in the encryption settings has been left blank.

Tests performed using [dnslookup](https://github.com/ameshkov/dnslookup) as a client.

### Screenshots

<details><summary>Screenshot:</summary>

![01](https://user-images.githubusercontent.com/13190004/180983651-49731c38-468b-48f0-89f8-8f88fd83f07a.png)

![02](https://user-images.githubusercontent.com/13190004/180983664-1d579e29-728b-4686-a12e-6047ab8454a5.png)

![03](https://user-images.githubusercontent.com/13190004/180984071-89c26821-3485-43c2-b836-7515a8d93a8b.png)

![04](https://user-images.githubusercontent.com/13190004/180983679-db477420-723d-46e0-add2-50ffcc221551.png)

</details>

**Comment by ainar-g** [comment]
Hello.

 >  The Server Name in the encryption settings has been left blank.

This is the mistake.  AdGuard Home uses the data from that field to separate the ClientIDs from the rest of the ClientHello TLS message.

We should probably mention that both in the UI as well as in the Wiki.

**Comment by ZeroClover** [comment]
Sorry, it's my bad. I misunderstood the meaning of the prompt.

The Server Name field prompts that leaving it blank will accept incoming TLS connections for all domains, which I thought I needed to leave blank in order for the wildcard domain to work properly.

Should I keep this issue open?

**Comment by ainar-g** [comment]
Yes, we'll close it once the UI and the docs are updated.
