### ISSUE TITLE
Bad information for Regex blocklists

### ISSUE THREAD

**Issue by RoboMagus** [AdguardTeam/AdGuardHome#4786]
### Issue Details
Trying to write regex block rules and keep running into issues where the rules just don't seem to apply. 
Carefully browsing documentation and cross checking syntax...
Turns out that the [documentation for regex in blocklists](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#regular-expressions) simply links to JS's Regex docs. AGH runs in Go, which does not support e.g. the _negative lookahead assertion_ I was trying to use. 
There is also no warning or other feedback on the UI stating that I'm trying to provide unsuported Regex features.

**To resolve:**
1: Refer to a Golang Regex guide
2: Provide feedback in the UI when what is entered by the user cannot be interpreted.

### Expected Behavior

Reference to documentation that matches the implementation.

### Actual Behavior

A reference to Java Regex implementation, which has more features than are available for use to us, as the used implementation is in Go.

**Comment by ainar-g** [comment]
Thanks for reporting the documentation inconsistency!  Rule validation is planned in #2500, but that will require more thorough changes.

**Comment by ainar-g** [comment]
We've fixed the regexp link on the [“How to Write Hosts Blocklists” page].  Sorry that it took so long.  We'll close this issue now.  Please feel free to open new ones if you find any issues with documentation.

[1]:https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#regular-expressions
