### ISSUE TITLE
Add option to encrypt traffic in local network (from device to AdGuard Home server)

### ISSUE THREAD

**Issue by thantrongtri3** [AdguardTeam/AdGuardHome#4787]
### Prerequisites

- [X] I have checked the Wiki and Discussions and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### What problem are you trying to solve?
I am using univeristy's network (eduroam), and am concerned about the security of traffic from my devices to Adguard Home server that is hosted on my Raspberry Pi.

### Proposed solution
Add end-to-end encryption.

**Comment by ainar-g** [comment]
Wouldn't using one of the encrypted protocols—DoH, DoQ, or DoT—suffice?

**Comment by thantrongtri3** [comment]
To use those protocols, I have to rent a domain name (which is not free),
and set up port forwarding (which my university doesnt allow, and I'd
prefer not to rent some public servers because they cost money). I would
say those protocols are more suitable for accessing Adguard Home over the
internet, but not very convenient for ones who host AdGuard Home on a local
server.

**Comment by ainar-g** [comment]
You can generate a self-signed certificate for an IP address.  [Here][1] is one example of how to do that.

I'm not sure, what you mean by port forwarding.  Can you elaborate?

[1]: https://medium.com/@antelle/how-to-generate-a-self-signed-ssl-certificate-for-an-ip-address-f0dd8dddf754

**Comment by thantrongtri3** [comment]
By port forwarding, I meant DoH can be achievable by accessing AdGuard Home
over the internet, sorry if my understanding wasn't correct. And could you
resend the link, I couldn't open it.

**Comment by ainar-g** [comment]
Generally, as long as your Pi has a static IP address (or some kind of stable local hostname, such as `mac-11-22-33-44-55-66.network.local`), and isn't behind a NAT of some sort, you should be able to access the HTTPS port on it.  You could test that with the `nc` utility.

I'm not sure what you mean by “resend the link”, but here it is again, verbatim:

```none
https://medium.com/@antelle/how-to-generate-a-self-signed-ssl-certificate-for-an-ip-address-f0dd8dddf754
```

**Comment by thantrongtri3** [comment]
My Pi is behind a NAT, so I have to self-sign a certificate, right? But isn't it more convenient for users if you guys add a new feature to automatically do that?

**Comment by ainar-g** [comment]
>  My Pi is behind a NAT, so I have to self-sign a certificate, right?

You're confusing two things here.  Self-signed certificates are just a general way to get a certificate without a certificate authority.  NAT is a thing that could prevent access to the Pi in question directly, at least over IPv4.

 >  But isn't it more convenient for users if you guys add a new feature to automatically do that?

By… inventing a new encrypted DNS protocol?  Possibly with an entirely new certificate authority mechanism?  There are already three encrypted DNS protocols (four, if you include DNSCrypt), and any new protocol would have to deal with exactly the same issues as those do w.r.t. certificates, NAT, firewalls, and things alike.  Many users use these in all kinds of network configurations today.

I'm sorry, but your best bet is to make your Pi accessible to the other devices in that network and use an allowlist of ClientIDs for them to make sure that they're the only ones using it.  So unless there is a more concrete proposal, I'll have to close this as `wontfix`.
