### ISSUE TITLE
有一个小建议，关天禁用功能

### ISSUE THREAD

**Issue by sshappys** [AdguardTeam/AdGuardHome#4796]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

你好
        我遇到一个问题，当然使用“禁用保护”功能的时候，会导致我失去网络，无法上网，因为DNS，所以我希望是不是可以使用两个“禁用”功能，一个禁用DNS，一个禁用“过滤器”。

**Comment by fernvenue** [comment]
Can not reproduce, AdGuardHome will still work as a pure DNS server when disable protection on web UI, if you wanna fully disable AdGuardHome, you can just stop AdGuardHome service on your server.

**Comment by sshappys** [comment]
ok, thanks

**Comment by fernvenue** [comment]
@sshappys I think maybe we can close this issue now.
