### ISSUE TITLE
Systemd-Resolved and AdGuardHome -- Connection reset by peer

### ISSUE THREAD

**Issue by ebanDev** [AdguardTeam/AdGuardHome#4797]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Raspbian 10

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.8

#### What did you do?
I am using normally AdGuardHome with systemd-resolved querying it in DoT
#### Expected result
To not have this error
#### Actual result

```
2022/07/31 18:33:34.937310 30435#3668 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleTCPConnection(): handling tcp: started handling tls request from 10.0.0.8:55144
2022/07/31 18:33:34.968972 30435#3668 [error] handling tcp: reading msg: reading len: read tcp 10.0.50.199:853->10.0.0.8:55144: read: connection reset by peer
```

#### Additional information

The service actually works fine, I'm having the right record, but still having this error is not normal I guess. It seems that I'm having those only on local requests, fyi I'm using tailscale with the "MagicDNS" feature, so I actually have to put the `100.100.100.100` IP in my resolver IPs for my DNS IPs to get resolved

![image](https://user-images.githubusercontent.com/57091497/182038643-d5e3f7c1-52df-478a-8903-8b9fb1c6864f.png)

So for example if I do `dig dns.local.eban.eu.org` it actually does
dns.local.eban.eu.org -> CNAME (ad guard home rewrite) `XXXX.ebandev.github.beta.tailscale.net` -> (asks over DoH to both quad9 and 100.100.100.100, but only 100.100.100.100 respond) 100.90.XXX.XXX

**Comment by agneevX** [comment]
100.100.100.100 from Tailscale only servers queries for machines within your Tailnet.

In order to get rDNS support for your Tailnet, you would need the following instead:

```
[/100.in-addr.arpa/]100.100.100.100
```

**Comment by ebanDev** [comment]
I tried and it works ! No more weird log 😅 Thanks ! :D
