### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by s-timm** [AdguardTeam/AdGuardHome#480]
Running v0.91 on a Qnap NAS (x86)

I have some questions (sorry, but there doesn't seem to be a forum for AdGuardHome)

1.
On the Settings page, when I press "Test upstreams" I always get

`Server "tls://1.1.1.1": could not be used, please check that you've written it correctly`

I have several upstream servers configured, 1.1.1.1 is third on the list. Is there any reasons that tls://1.1.1.1 is not working? When I try just 1.1.1.1 (no DNS-over-TLS) I get the same:

`Server "1.1.1.1": could not be used, please check that you've written it correctly`

However, I can ping 1.1.1.1 without problems.
Is this a bug? Does AdGuardHome produce a log of the communications/errors with the upstream DNS servers?

2.
Unrelated to the first question: 
What is the difference between enabling "Use AdGuard browsing security web service" on the Settings page and using the "MalwareDomainList.com Hosts List" on the Filters page? (Apart from the fact that the first does an online check?) Don't they share a similar database of malware domains?

3.
On the "Query Log" page, it would be great to be able to specify a time range, e.g. show only queries from 11:48:00 to 11:49:00
Also, when I want to see more rows of data and select "100 rows" on the bottom of the screen, it would be great if AdGuard would remember that choice.

Great work so far! Thanks!

**Comment by ameshkov** [comment]
> Is there any reasons that tls://1.1.1.1 is not working?

Happens with Cloudflare DNS sometimes.

To check if it works from your location try smth like that: `nslookup example.org 1.1.1.1`

> Does AdGuardHome produce a log of the communications/errors with the upstream DNS servers?

It prints more info to stdout.

> Don't they share a similar database of malware domains?

No, AdGuard's database is much larger and that's why it is a web service, it's too heavy to be downloaded.

> On the "Query Log" page, it would be great to be able to specify a time range

Makes sense, thank you! I've created a separate feature request for that: https://github.com/AdguardTeam/AdGuardHome/issues/481
