### ISSUE TITLE
Save/restore settings button

### ISSUE THREAD

**Issue by blixten85** [AdguardTeam/AdGuardHome#4802]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I want a save and restore settings button for Adguard Home. So i can save settings, reinstall my router and just pop everything back in again.

**Comment by fernvenue** [comment]
You can just back up the `AdGuardHome.yaml` configuration file manually, it's in the root directory of AdGuardHome, on most Unix systems the default directory is `/opt/AdGuardHome`, but on macOS it's `/Applications/AdGuardHome`. It depends on how you installed AdGuardHome.

```
~# find / -name AdGuardHome.yaml
/opt/AdGuardHome/AdGuardHome.yaml
```

Or you can use `find` command to find the configuration file in whole `/` directory like above.

**Comment by ainar-g** [comment]
What fernvenue said is the current best practice.  See also #573 and #1147 for similar requests.
