### ISSUE TITLE
Statistics wrong or missing?

### ISSUE THREAD

**Issue by laughtLOOL** [AdguardTeam/AdGuardHome#4808]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

107.8

#### What did you do?
see the request times and the precent, a simple calculate can know the number is wrong, but problem is who is wrong and correct.
#### Expected result
Like the first device have 5k request, second was same, both two of them have almost 11k
#### Actual result
But at the block list and the allow list was only a little Number on that way, all list add just maybe in 3 thousands
#### Screenshots (if applicable)
![Screenshot_20220805-013727_Kiwi Browser](https://user-images.githubusercontent.com/83571492/182918989-7a6097c0-cc47-4335-9178-7bb8c243fc7f.png)
#### Additional information
I set the log and the Statistics on same time clear, 
![Screenshot_20220805-020713_Kiwi Browser](https://user-images.githubusercontent.com/83571492/182922691-5f45c86a-6529-4386-96db-826eccadf6e3.png)

But it still wrong, does any requests not show on the list like the TCP or IP request, and the device request times was increased.

**Comment by fernvenue** [comment]
Why don't you swipe the list and add other values to the calculation? Can't you see the slider?

**Comment by ZhiShengYuan** [comment]
PLZ VIEW ALL IN THE LIST FIRST

**Comment by laughtLOOL** [comment]
> Why don't you swipe the list and add other values to the calculation? Can't you see the slider?
I know have swipe, please not genius, I have been say total two list number just thousand not largest than 10k, the list below you can see that just 100 less each list

**Comment by laughtLOOL** [comment]
> PLZ VIEW ALL IN THE LIST FIRST

我算过列表的内容了，他就是下面所有统计的跟上面设备请求的对不上，我开了dns缓存，我现在怀疑它禁止和允许列表是与外界请求次数，而设备请求哪里算的是dns缓存了的响应而这个响应没记录在禁止和允许列表里面，但是上面设备请求列表是禁止和允许列表与外界请求次数总和。

**Comment by laughtLOOL** [comment]
ok, I clear the genies calculate way, allow list calculate depend for the total number,  ban list calculate depend the total ban number, rather than total number

**Comment by laughtLOOL** [comment]
.
