### ISSUE TITLE
DNS IP v6 address keeps changing

### ISSUE THREAD

**Issue by JavDMBrett** [AdguardTeam/AdGuardHome#4810]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0,107,9

#### What did you do?

I installed the home version of Adguard on a 8bg Raspberry Pi 4. It works just fine

#### Expected result

The primary DNS lookup is my IPv6 address.

#### Actual result
The IPv6 address keep changing on the Home page.
I have to manually change them on the router everyday.

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/69807190/183069377-557625cb-4589-40da-99ed-f687269037b8.png)

#### Additional information

I want to be able to leave my Pi alone and not have to check to see if the IPv6 address has changed everyday?

**Comment by ppfeufer** [comment]
Set a static IP address on your RasPi

For RasPi OS:
```shell
sudo nano /etc/dhcpcd.conf
```

And you'll see this example
```plaintext
# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
```

Uncomment what you need and change values accordingly

**Comment by JavDMBrett** [comment]
Fantastic of Course


Mit freundlichen Grüßen,

Dave Brett CertHE
MiMgt GCGI

Multi Media BbS Hannover
Cisco Instructor Training und Academy Support Center
Expo Plaza 3
D-30539 Hannover
***@***.******@***.***>
+49 151 41470087
***@***.******@***.******@***.******@***.***
