### ISSUE TITLE
Buggy Query Log interaction on tablet viewports

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#4815]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.9

#### Bug description

On v0.107.9, attempting to look up information of logs in Query Log on tablet viewports is quite buggy to say the least.

(From #4775)

Specifically, it exhibits the following issues:

1. Unable to click/tap on the question glyphs to view pop-up boxes
2. Instead, a modal meant for mobile viewports pops up, which spans across the screen
3. 
> agneevX: This modal pops up when I tap just about anywhere in Query Log.

> ainar-g: I  cannot reproduce that. For me, it only opens when I click on a query log record.

I meant to say that clicking on areas other than the question glyphs brings up the modal. This includes any part of a log row.

4. There is no visible way to dismiss the modal
5. The boxes do show up

> If I simulate a tablet device on desktop, click anywhere, close the modal by pressing <kbd>Esc</kbd> and immediately hover over a question glyph, it shows the box.

This modal is also different from the modal that is displayed on mobile devices, as it does not have bold text. This can be demonstrated by shrinking the viewport.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/19761269/183136866-be3b22d0-4c81-4351-91a3-98cfe055e26a.png">

### Screenshots

![image](https://user-images.githubusercontent.com/19761269/182634555-0db99f49-c645-4f92-bd1e-1351a0ea7d3a.png)

#### Additional information

**Comment by ainar-g** [comment]
@agneevX, hello.  Most of this should be fixed on the Edge channel.  Could you please check if the fixes to how the modal behaves work for you?

**Comment by agneevX** [comment]
I'll be testing this and will report back.

**Comment by agneevX** [comment]
Is it possible that some of these changes are present in the stable channel?

This is how it looks now, for reference... still a mobile modal presented on a tablet interface.

I think the data can be presented a bit better by grouping items, therein utilizing the vertical space available instead of having to scroll.

![image](https://user-images.githubusercontent.com/19761269/193248328-501f665d-bb08-4d80-89d1-715dd761da0d.png)

**Comment by ainar-g** [comment]
@IldarKamalov, is there a way to put the single-line info to the right of the headers?

**Comment by IldarKamalov** [comment]
> @IldarKamalov, is there a way to put the single-line info to the right of the headers?

I think yes

**Comment by agneevX** [comment]
Yup, it's perfect. Thanks for listening and implementing the changes.
