### ISSUE TITLE
Add the specified ip segment client settings

### ISSUE THREAD

**Issue by liangfyx** [AdguardTeam/AdGuardHome#4834]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

I hope that the option to increase the client ip segment in the client settings.

**Comment by fernvenue** [comment]
You can just use [CIDR range](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#identifying-clients) to do that, are you sure you really checked the wiki before you open this issue?

**Comment by EugeneOne1** [comment]
@liangfyx, if the **fernvenue**'s suggestion helped?
