### ISSUE TITLE
DHCP darwin and v0.108.0-b.11 

### ISSUE THREAD

**Issue by kour1er** [AdguardTeam/AdGuardHome#4836]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

macOS (aka Darwin)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.11 

#### What did you do?
Upgraded via the built in upgrade mechanism from b.10 to b.11

#### Expected result
For DHCP to work

#### Actual result
In b.11, in my environment, DHCP fails. After the lease time expires, clients do not receive new information. If I manually stop and restart DHCP via the Adguard Home web interface, I get this error:

"Error: control/dhcp/set_config | enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: listen packet [redacted MAC address] packet: not implemented on darwin | 400"

If I roll back to b.10 DHCP starts working again correctly. Am I missing something obvious?

**Comment by EugeneOne1** [comment]
@kour1er, hello and thanks for the report.  It's indeed a bug, I suppose it affects all the AGH users with macOS.  We'll try to fix it as soon as possible.

**Comment by ainar-g** [comment]
@kour1er, hello.  We've reverted some of the changes that could cause that in `f58265ec`.  This change has now been published to the Edge channel.  Could you please see if that fixes the issue for you?  If it does, we'll try to release the fix to Beta and Release channels sometime this week.

**Comment by kour1er** [comment]
Wow that was fast 👍
So I've tested with the edge build linked from the main page - it reports version: v0.108.0-a.196+6e63757f

With this build, DHCP is working fine again (this is the mac 64 bit version on Intel). Cheers

**Comment by ainar-g** [comment]
Thanks for checking out!
