### ISSUE TITLE
Filters tab only show the first 20 subscriptions

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdGuardHome#484]
[Bug] [GUI]
Currently, the web portal Filters tab doesn't show more than the first 20 filter lists/subscriptions. _Pretty unique situation I realize_

It's important to note that all the filters that don't show up on the GUI are fully functioning and modifiable through yaml.

**Comment by ameshkov** [comment]
@IldarKamalov please do, the fix is trivial
