### ISSUE TITLE
Auto update blocklist after reboot

### ISSUE THREAD

**Issue by hongdat1106** [AdguardTeam/AdGuardHome#4845]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
My router set cron to reboot weekly, I saw that AdGuardHOME was not updated automatically so my kids always play games before I recognize and update blocklist manual, I used Adblock before, adblock always update blocklist after reboot.

#### Proposed solution
Force AdGuardHOME update blocklist after router reboot.
#### Alternatives considered
Add update button in Dashboard

**Comment by ainar-g** [comment]
Please include a description of the feature request.

**Comment by ainar-g** [comment]
Essentially, this would mean updating filters immediately on every AdGuard Home start, since detecting, whether or not a reboot has happened lately could get tricky.  That could increase start up time, if we're not careful.

**Comment by gvijayakumar-16** [comment]
I ran into the exact same issue today. This would be a really useful feature. 
On another note, why did the old filters get removed when the router was restarted? Was it a because of the install location of Adguard in openwrt or is that expected?

**Comment by mangkoran** [comment]
I saw this issue has been closed as "completed". Does it mean AGH able to update filter list on startup now? I couldn't find the relevant configuration.
