### ISSUE TITLE
blocked_response_ttl purge button

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdGuardHome#485]
[Feature Request]

Provide a button on the GUI to purge the blocked_response_ttl to experience instant effect upon unblocking a domain/modifying filter lists.

Some background:
Thanks to the brilliant feature proposed by @hmage I get an astonishing Average Processing Time on a gigantic 2 million ruleset. The downside is when rapidly changing a list or unblocking a domain, it would take too long for the change to work. A simple button that can be pressed when modifications are needed to work instantly would fix this situation.

**Comment by pizdec** [comment]
I'm just curious, how many secods you set up for ttl? 
And what upstream settings you are using: udp, tcp...?

**Comment by ameshkov** [comment]
The problem with this is that this is a TTL of a DNS client cache, we can't do anything from the server side with it.
