### ISSUE TITLE
Query Log: Goes into compact-view, but doesn't return to default-view (upon window resize)

### ISSUE THREAD

**Issue by sjhgvr** [AdguardTeam/AdGuardHome#4854]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not ask a question

**AdGuard Home version**
v0.107.11

**Description:**
1: Go to the AdGuard Home Query Log page (starting with a browser window window wide enough so default-view is used)
2: Resize the window so it enters compact-view
3: Resize the windows back to it's former size

**Expected result:**
Should return to default-view

**Actual result:**
Stays in compact-view

**Additional information;**
Chrome Version 104.0.5112.101

**Comment by agneevX** [comment]
Related to #3586.

**Comment by sjhgvr** [comment]
> @sjhgvr, this should be fixed on the Edge channel. Could you please check?

Unfortunately not. I'm on stable.

**Comment by ainar-g** [comment]
@sjhgvr, hello.  Can you confirm that it's fixed as of v0.107.15?

**Comment by sjhgvr** [comment]
> @sjhgvr, hello. Can you confirm that it's fixed as of v0.107.15?

The issue changed into a new bug;

Description:
1: Go to the AdGuard Home Query Log page (starting with a browser window window wide enough so default-view is used)
2: Switch to compact-view 
3: Resize the window (make it smaller)
4: Resize the windows back to it's former size

Expected result:
Stay in chosen view (compact)

Actual result:
Goes to default view

**Comment by ainar-g** [comment]
Thanks for testing!  Sooner or later we'll rewrite the entire page, and those interaction issues should be fixed as well.
