### ISSUE TITLE
Upstream_dns_file using doh/DOT cause the configuration to fail

### ISSUE THREAD

**Issue by XUANJI233** [AdguardTeam/AdGuardHome#4856]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.108.0-a.225+1afd73ad

#### What did you do?
Setting upstream_dns_file in AdGuardHome.yaml and using doh/DOT in the file will cause the configuration to fail

#### Additional information

√ server=/google.com/8.8.8.8
× server=/google.com/https://dns.google/dns-query

**Comment by fernvenue** [comment]
So what happens when you just populate the DNS upstream with `https://dns.google/dns-query` instead of using an upstream file and test it? Are you able to use it normally?

**Comment by ainar-g** [comment]
@XUANJI233, I cannot reproduce this.  Please make sure that you:

1.  Follow the correct format from our [instructions][1].

2.  Provide a default upstream as well.

3.  Provide the actual error message you're getting.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains
