### ISSUE TITLE
[error] handling tcp: reading msg: reading msg: unexpected EOF

### ISSUE THREAD

**Issue by rayap88** [AdguardTeam/AdGuardHome#4859]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

107.11

#### What did you do?
Setup Adguard home on Qnap NAS using container station
#### Expected result
Expected Adguard home to display hostname next to IP while performing filters but hostname not being output on client list. Found [error] handling tcp: reading msg: reading msg: unexpected EOF
#### Actual result
Flooded with [error] handling tcp: reading msg: reading msg: unexpected EOF and hostname not appearing on Client List
#### Additional information
2022/08/24 11:35:01.799967 [error] handling tcp: reading msg: reading msg: unexpected EOF
2022/08/24 11:35:25.339559 [error] handling tcp: reading msg: reading msg: unexpected EOF
2022/08/24 11:35:48.964322 [error] handling tcp: reading msg: reading msg: unexpected EOF

Flooded with above errors but filters are still working fine

**Comment by ainar-g** [comment]
Hello and thank you for the report.

> Expected Adguard home to display hostname next to IP while performing filters but hostname not being output on client list.

I'm not quite sure about what you mean here.  AdGuard Home has several sources of client information, including ARP and PTR.  You should inspect [verbose logs][1] to see if those work correctly.

> Found [error] handling tcp: reading msg: reading msg: unexpected EOF

This looks like one of your upstream servers misbehaving.  If this is the upstream server that you've set up for the PTR resolving, this could explain the absence of hostnames for runtime clients.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog
