### ISSUE TITLE
We should use weighted random when choosing upstream

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#487]
We can backport this for instance:
https://github.com/AdguardTeam/dnsproxy/blob/master/proxy/proxy.go#L192

**Comment by mHatsune** [comment]
[0.103] Load balancing?

**Comment by ameshkov** [comment]
Yeah, thank you:)

**Comment by yeezylife** [comment]
Could you please elaborate the strategy of the adguardhome Load balancing？
Like:
first (always pick the fastest server in the list)
p2 (randomly choose between the top 2 fastest servers)
ph (randomly choose between the top fastest half of all servers)
random (just pick any random server from the list)

I'm wondering which one is it。。

**Comment by ameshkov** [comment]
@yeezylife hi, it's weighted random, so with a higher probability it will choose the fastest server, but there's still a chance that it will pick the other one.
