### ISSUE TITLE
AdGuardHome will not start if system time is wrong, because the certificate check is invalid, and since the DNS server is not yet enabled, obtaining pool.ntp.org to set time is impossible.

### ISSUE THREAD

**Issue by UnconditionalLoop** [AdguardTeam/AdGuardHome#4880]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.1

#### What did you do?

AdGuardHome can't start when system time is wrong, because the certificate check fails. This can happen on a box with incorrect time, or missing CMOS battery.

#### Expected result

This should happen for security reasons.

####  Quick and dirty fix
This will update system time using Cloudflare's DNS server, before AdGuardHome is launched.
My system didn't have dig, so I used nslookup. With AdGuardHome installed as a service, put this in the service file:

ExecStartPre=/bin/bash -c "ntpd -d -n -q -p `nslookup pool.ntp.org 1.1.1.1 | awk '/Name:/{getline;print \$3}'`"

(github refuses to show backticks, and I don't know how to fix it in the example. It should be before nslookup, and between single and double quotes.)

#### Additional information

Possible fix could be to check if time is wrong by being earlier than build date/or filter.txt, then check the time externally, or simply set the system clock first like I'm doing. Obviously running nslookup and ntpd takes a second.

**Comment by ainar-g** [comment]
I'm honestly not sure that this is something AdGuard Home should do.  Keeping the time in sync in order to validate TLS certificates sounds like a prerequisite for any reasonable system.

**Comment by UnconditionalLoop** [comment]
Yes, but every reasonable system needs to use dns to sync time with an ntp server. You can't hardcode ntp IP addresses.

**Comment by pierre2113** [comment]
I found the solution here


https://www.snbforums.com/threads/adguard-home-fails-to-start-after-reboot.78904/page-3

placing the following in Settings->DNS Settings->Upstream DNS servers

[/pool.ntp.org/]1.1.1.1
[/pool.ntp.org/]1.0.0.1
[/time1.google.com/]8.8.8.8

**Comment by nmhung1985** [comment]
> I found the solution here
> 
> https://www.snbforums.com/threads/adguard-home-fails-to-start-after-reboot.78904/page-3
> 
> placing the following in Settings->DNS Settings->Upstream DNS servers
> 
> [/pool.ntp.org/]1.1.1.1 [/pool.ntp.org/]1.0.0.1 [/time1.google.com/]8.8.8.8

You should just use time.google.com

**Comment by UnconditionalLoop** [comment]
This is absolutely pathetic that you people are suggesting to use a corporate NTP server, instead of the REAL NTP servers that exist, for this purpose. You all make me want to puke! ntp.pool.org is the only NTP server anyone should ever use!
If you seriously can't bootstrap with your own local ISP DNS, then simply type: "nslookup ntp.pool.org 9.9.9.9" before starting AdGaurd. At least quad9 cares about privacy.
