### ISSUE TITLE
Custom rules for specific clients is not working.

### ISSUE THREAD

**Issue by deam0n** [AdguardTeam/AdGuardHome#4881]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.11

#### What did you do?
Created a custom rule:
192.168.178.53 google.com^$client=192.168.178.0/24

#### Expected result
when querying google.com from 192.168.178.0/24 to have 192.168.178.53 returned.

#### Actual result
when querying google.com from 192.168.178.0/24 some other ip is returned 

#### Additional information
||google.com^$client=192.168.178.0/24 works as expected.

**Comment by ainar-g** [comment]
Hello.  `/etc/hosts`-style rules do not support modifiers.  We should really make that clearer in our documentation.

Your query should work with the [`dnsrewrite` modifier][1]:

```none
|google.com^$client=192.168.178.0/24,dnsrewrite=NOERROR;A;192.168.178.53
```

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite
