### ISSUE TITLE
Update the Version a.261 exception

### ISSUE THREAD

**Issue by sshappys** [AdguardTeam/AdGuardHome#4889]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.261+1fb04376

### Description

hi:
PVE--->LXC--->centos7---->adgardHome
Updated the latest version today
some bug maybe，DNS not working
No problem with the previous upgrade
hint:
unreachable\",\"dial tcp
[2400:3200: baba::1]:443: connect: network is unreachable\"","requesting https://dns. adguard-dns. com:443/dns-
query: Get \"https://dns. adguard-
dns. com:443/dns-query?
dns=J3IBAAABAAAAAAAABnNOYXRpY..
all dialers failed:2 errors:\"dial tcp[2a10:50c0: ad1: ff]:443: connect: network is unreachable\",\"dial tcp
[2a10:50c0: ad2: ff]:443: connect: network is unreachable\"","requesting https://1.0.0.1:443/dns-query: Get
\"https://1.0.0.1:443/dns-query?
dns=J3IBAAABAAAAAAAABnNOYXRpY..
context deadline exceeded
(Client. Timeout exceeded while awaiting headers)","requesting https://1.1.1.1:443/dns-query: Get
\"https://1.1.1.1:443/dns-query?
1dns-J3IBAAABAAAAAAAABnNOYXRpY..
net/http: request canceled while waiting for connection(Client. Timeout exceededwhile awaiting headers)","initializing http client: timeout exceeded:
14.121609409s","initializing http client: timeout exceeded:14.136578299s",
"initializing http client: timeout exceeded:14.148318673s","initializing http client: timeout exceeded:
14.182937259s","initializing http client: timeout exceeded:24.185664127s"|502

**Comment by ainar-g** [comment]
Hello.  It looks like your network was having issues, as those errors indicate timeouts.  Please make sure that the network is up and that the upstreams are reachable.

**Comment by sshappys** [comment]
> 

OK，THANKS
