### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by niyazialpay** [AdguardTeam/AdGuardHome#4890]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [x] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.261+1fb04376

#### What did you do?

When I update to v0.108.0-a.230+bdcf3451 version I get the following error

#### Actual result

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x4eb1b7]

goroutine 1544 [running]:
github.com/AdguardTeam/dnsproxy/fastip.(*FastestAddr).pingAll(0x0, {0xc0004444e0, 0x12}, {0xc000013b00, 0x3, 0xc001fc1cf0?})
        github.com/AdguardTeam/dnsproxy@v0.44.0/fastip/ping.go:39 +0x77
github.com/AdguardTeam/dnsproxy/fastip.(*FastestAddr).ExchangeFastest(0x1baa540?, 0xc000e76f30, {0xc000098300?, 0x2?, 0x2?})
        github.com/AdguardTeam/dnsproxy@v0.44.0/fastip/fastest.go:81 +0x10d
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).exchange(0x30004?, 0xc0004444e0?, {0xc000098300?, 0x1ba5b2e?, 0xc00207aea0?})
        github.com/AdguardTeam/dnsproxy@v0.44.0/proxy/exchange.go:17 +0x69
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).replyFromUpstream(0xc0000c2380, 0xc0010e8c00)
        github.com/AdguardTeam/dnsproxy@v0.44.0/proxy/proxy.go:409 +0x119
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(0xc0000c2380, 0xc0010e8c00)
        github.com/AdguardTeam/dnsproxy@v0.44.0/proxy/proxy.go:492 +0xb4
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).lookupIPAddr(0xc0000c2380, {0xc0004444e0, 0x12}, 0x1c, 0x0?)
        github.com/AdguardTeam/dnsproxy@v0.44.0/proxy/lookup.go:30 +0x19c
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).LookupIPAddr
        github.com/AdguardTeam/dnsproxy@v0.44.0/proxy/lookup.go:43 +0x19d

**Comment by ainar-g** [comment]
@niyazialpay, hello and thank you for the report.  The most recent release on the Edge channel contains a fix for this issue.  Could you please check if it works for you?

**Comment by niyazialpay** [comment]
hello, the problem have been resolved, thank you
