### ISSUE TITLE
Add a new upstream DNS request policy

### ISSUE THREAD

**Issue by Xarth-Mai** [AdguardTeam/AdGuardHome#4892]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I have an unstable upstream server A and a stable upstream server B, and I want it to be preferred when upstream server A is running, only to automatically select a backup upstream server when he fails

#### Proposed solution
Can a weighted parallel request mode be added? Request multiple upstreams at the same time, continue to wait for the upstream server with higher weight for a period of time after getting the result, if you get the response from the upstream server with higher weight within the set time, return the answer from the server with higher weight, otherwise reply to other weight Low server promises.

#### Alternatives considered
Request the first server and wait for a certain amount of time, if it times out, select the second server in turn, which is less efficient but easy to implement.

#### Additional information
If AdGuardHome can have two upstream server lists, one is more high-quality and the other is more stable, use the algorithm to select the appropriate upstream to take into account better experience and disaster tolerance.

**Comment by bobsiboo** [comment]
I am looking for the same thing.

I have a local Caching server as upstream running on my NAS, however if for some reason my NAS goes down (eg. during an os update) I want it to failover to another upsteam server eg 1.1.1.1. 

As long as the NAS is up i do want all traffic to go trough, otherwise the Caching mechanism doesn't work.

**Comment by cloudwindy** [comment]
+1
This can be very useful for a multi dns server setup.

**Comment by Heshmatkhah** [comment]
Hi
I have AGH as my ad blocker, also we have a caching DNS server on my network, I want the AGH forward requests to the local DNS server, and if it failed, forward it to 1.1.1.1 or 8.8.8.8
