### ISSUE TITLE
DHCP Server in .12 stops certain IoT devices from connecting

### ISSUE THREAD

**Issue by jgriffiths014** [AdguardTeam/AdGuardHome#4904]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.12

#### What did you do?
updated to v0.107.12, after the DHCP leases expired, my Blink camera system refused to re-connect. Connecting the devices to a guest network that uses a different DHCP server brings the devices back online. rolling back to v0.107.11 also brings the devices back online.
#### Expected result
All devices should stay online after a DHCP lease renewal
#### Actual result
devices unable to renew DHCP lease and therefore cannot connect to the network.

**Comment by EugeneOne1** [comment]
@jgriffiths014, hello and thanks for reporting.  Could you please [collect a verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us, capturing the moment of DHCP messages interchange?  You're welcome to send it to devteam@adguard.com.

**Comment by EugeneOne1** [comment]
@jgriffiths014, we've just pushed the newest edge build.  It's intended to check the assumption that the message size causes this issue.  Could you please give it a try?

**Comment by djusHa** [comment]
My Sonos Play 1 has same issue. No IP Adress from DHCP. Revert back to Version: v0.107.11, is all ok. Pihole working good also.

**Comment by EugeneOne1** [comment]
@djusHa, could you please also try the latest edge build?  It reverts some changes made in 0.107.12.

**Comment by djusHa** [comment]
@EugeneOne1: Edge build seems to work flawless, DHCP on my Sonos Play 1 works again.
No Problems so far with Tasmota Plugs and Tuya Devices, if this is interesting for you. 
.lan suffix for my Debian Server works, was brocken in 0.107.11

So far, so good :-)

**Comment by rhraziel** [comment]
Ugh, I bought a new Roku thinking my old one was bad. Found this after the new one came and didn't work either.

**Comment by jgriffiths014** [comment]
Sorry @EugeneOne1, I've been away for a few days - I'll reconfigure my instance for you today and grab the logs.

Thanks

**Comment by EugeneOne1** [comment]
@rhraziel, have you tried the latest edge build of AdGuard Home.  It seems, we've introduced a little bug into DHCP recently.

**Comment by jgriffiths014** [comment]
Hi,

log running latest edge version mailed over for you, everything seems to work - devices rebooted and came back online. Didn't capture in the logs but I reset all leases and rebooted the devices - they came back online ok.

Thanks

**Comment by EugeneOne1** [comment]
@jgriffiths014, great to hear.  I'll close the issue then, if you don't mind.

**Comment by rhraziel** [comment]
@EugeneOne1 Yes, the edge build worked for me.
