### ISSUE TITLE
Client IP not showing on GUI

### ISSUE THREAD

**Issue by z3r0c0nf1gs** [AdguardTeam/AdGuardHome#4910]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Main OS Ubuntu 20.04 > Docker container Alpine Linux 3.16.2

### CPU architecture

AMD64

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

adguard/adguardhome:latest v0.107.12

#### What did you do?
Installed AdGuard to my VPS via CapRover and added the port mapping to expose ports and mounted persistent data.
![image](https://user-images.githubusercontent.com/111920854/189552578-e0c4ecd9-3492-4b67-97be-e262d820728e.png)
![image](https://user-images.githubusercontent.com/111920854/189552607-983b58cb-7fb6-4b8a-bb13-2b3aa88f8e43.png)

Added my VPS IP as trusted proxies
1xx.xxx.xxx.239/0
![image](https://user-images.githubusercontent.com/111920854/189553230-a04d09a0-5429-4ac4-91e5-f00999512ce7.png)
![image](https://user-images.githubusercontent.com/111920854/189552717-6b8077e2-51ff-49e4-9edb-6b5d08406ca6.png)

#### Expected result
Will show the actual IP of clients.

#### Actual result
all traffic just shows under 1 docker IP.

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/111920854/189552752-eb362a10-8129-4fe8-92bc-a540eb8bc55e.png)

#### Additional information
I've tried using both adguard/adguardhome:latest and adguard/adguardhome:edge but got same result.
netstat output
![image](https://user-images.githubusercontent.com/111920854/189552816-26dcc81e-7a96-4a58-b7e1-3e99c5134a90.png)

**Comment by ainar-g** [comment]
Good day.  If you're using DoH AdGuard Home with a reverse proxy, the proxy should add the `X-Forwarded-For` header with the original client IP address, and AdGuard Home must be set up to trust this proxy, so make sure that the IPs in your `trusted_proxies` settings are *the ones that the container sees.*  For other protocols, `--network=host` is usually required.

**Comment by z3r0c0nf1gs** [comment]
Hi @ainar-g im actually not using DoH. rather I'm sending request to port 53 of my VPS that is running the docket version of ADG.
![image](https://user-images.githubusercontent.com/111920854/189733594-73a8d978-1c63-4e1d-9488-1e3e18cf9d32.png)

**Comment by ainar-g** [comment]
@z3r0c0nf1gs, I see.  Have you tried using `--network=host` when running the container?  Also, does your VPS provide the original IPs?  Because it may be that the VPS service is acting as a proxy or runs the virtual machines in a configuration that doesn't proxy the IPs to the guest.

**Comment by z3r0c0nf1gs** [comment]
yep i got a dedicated ipv4 and ipv6 ip i will try that --network=host

**Comment by ainar-g** [comment]
No response for over a year, closing.
