### ISSUE TITLE
Adguard Home Doesn't work after Router Sudden Power Failure

### ISSUE THREAD

**Issue by xenstar** [AdguardTeam/AdGuardHome#4915]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.12

#### What did you do?
Due to load shedding in one of my office locations, the R2S will shut down suddenly. When the electricity is back, Adguard will start but can't browse anything. I have to turn off adguard home, then it will work. Then I have to enable it manually then it will work. 

#### Expected result

Before even with sudden poweroff, adguard will still work automatically. 

#### Actual result

But it doesn't start. Any website I visit it shows DNS Probe Error. 

#### Screenshots (if applicable)

Manually I turn off and turn on, then it was working

Here is the Log

2022/09/13 09:53:29.694775 [info] Updated filter #1660804183.  Rules: 58434 -> 57962
2022/09/13 09:53:29.694758 [info] Updated filter #1659512593.  Rules: 25961 -> 26412
2022/09/13 09:53:29.694744 [info] Updated filter #1659512592.  Rules: 11126 -> 11147
2022/09/13 09:53:29.694730 [info] Updated filter #1659512591.  Rules: 1729 -> 1730
2022/09/13 09:53:29.694714 [info] Updated filter #1659512587.  Rules: 439 -> 439
2022/09/13 09:53:29.694699 [info] Updated filter #1659512586.  Rules: 332350 -> 333280
2022/09/13 09:53:29.694683 [info] Updated filter #1628750871.  Rules: 55502 -> 55503
2022/09/13 09:53:29.694666 [info] Updated filter #1628750870.  Rules: 48683 -> 48820
2022/09/13 09:53:29.694643 [info] updated filter 1660804183: 1161655 bytes, 57962 rules
2022/09/13 09:53:29.694458 [info] saving filter 1660804183 contents to: /etc/AdGuardHome/data/filters/1660804183.txt
2022/09/13 09:53:24.135909 [info] updated filter 1659512593: 721196 bytes, 26412 rules
2022/09/13 09:53:24.135691 [info] saving filter 1659512593 contents to: /etc/AdGuardHome/data/filters/1659512593.txt
2022/09/13 09:53:23.657266 [info] updated filter 1659512592: 652767 bytes, 11147 rules
2022/09/13 09:53:23.657056 [info] saving filter 1659512592 contents to: /etc/AdGuardHome/data/filters/1659512592.txt
2022/09/13 09:53:23.455889 [info] updated filter 1659512591: 54341 bytes, 1730 rules
2022/09/13 09:53:23.455671 [info] saving filter 1659512591 contents to: /etc/AdGuardHome/data/filters/1659512591.txt
2022/09/13 09:53:22.080373 [info] updated filter 1659512587: 25323 bytes, 439 rules
2022/09/13 09:53:22.080155 [info] saving filter 1659512587 contents to: /etc/AdGuardHome/data/filters/1659512587.txt
2022/09/13 09:53:21.723591 [info] updated filter 1659512586: 7335387 bytes, 333280 rules
2022/09/13 09:53:21.723427 [info] saving filter 1659512586 contents to: /etc/AdGuardHome/data/filters/1659512586.txt
2022/09/13 09:53:19.682387 [info] updated filter 1628750871: 1093402 bytes, 55503 rules
2022/09/13 09:53:19.682218 [info] saving filter 1628750871 contents to: /etc/AdGuardHome/data/filters/1628750871.txt
2022/09/13 09:53:18.977125 [info] updated filter 1628750870: 944074 bytes, 48820 rules
2022/09/13 09:53:18.976920 [info] saving filter 1628750870 contents to: /etc/AdGuardHome/data/filters/1628750870.txt
2022/09/13 09:53:18.209548 [info] Entering the tcp listener loop on [::]:53
2022/09/13 09:53:18.209492 [info] Entering the UDP listener loop on [::]:53
2022/09/13 09:53:18.209254 [info] Listening to tcp://[::]:53
2022/09/13 09:53:18.209154 [info] Creating a TCP server socket
2022/09/13 09:53:18.209128 [info] Listening to udp://[::]:53
2022/09/13 09:53:18.208947 [info] Creating the UDP server socket
2022/09/13 09:53:18.208908 [info] MaxGoroutines is set to 300
2022/09/13 09:53:18.208882 [info] DNS cache is enabled
2022/09/13 09:53:18.208866 [info] Cache TTL override is enabled. Min=300, Max=3600
2022/09/13 09:53:18.208809 [info] Starting the DNS proxy server
2022/09/13 09:53:01.332236 [info] Go to http://219.317.208.227:8080
2022/09/13 09:53:01.332222 [info] Go to http://192.168.31.1:8080
2022/09/13 09:53:01.332206 [info] Go to http://[::1]:8080
2022/09/13 09:53:01.332159 [info] Go to http://127.0.0.1:8080
2022/09/13 09:53:01.330200 [info] AdGuard Home is available at the following addresses:
2022/09/13 09:53:00.529333 [info] Initialize web module
2022/09/13 09:53:00.529290 [info] auth: initialized.  users:1  sessions:4
2022/09/13 09:53:00.529011 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
2022/09/13 09:53:00.491959 [info] AdGuard Home, version v0.107.11
2016/01/21 10:34:47.222914 [info] Entering the tcp listener loop on [::]:53
2016/01/21 10:34:47.222863 [info] Entering the UDP listener loop on [::]:53
2016/01/21 10:34:47.222636 [info] Listening to tcp://[::]:53
2016/01/21 10:34:47.222536 [info] Creating a TCP server socket
2016/01/21 10:34:47.222506 [info] Listening to udp://[::]:53
2016/01/21 10:34:47.222289 [info] Creating the UDP server socket
2016/01/21 10:34:47.222250 [info] MaxGoroutines is set to 300
2016/01/21 10:34:47.222221 [info] DNS cache is enabled
2016/01/21 10:34:47.222205 [info] Cache TTL override is enabled. Min=300, Max=3600
2016/01/21 10:34:47.222146 [info] Starting the DNS proxy server
2016/01/21 10:34:30.362571 [info] Go to http://219.317.208.227:8080
2016/01/21 10:34:30.362556 [info] Go to http://192.168.31.1:8080
2016/01/21 10:34:30.362541 [info] Go to http://[::1]:8080
2016/01/21 10:34:30.362491 [info] Go to http://127.0.0.1:8080
2016/01/21 10:34:30.360391 [info] AdGuard Home is available at the following addresses:
2016/01/21 10:34:29.539946 [info] Initialize web module
2016/01/21 10:34:29.539903 [info] auth: initialized.  users:1  sessions:4
2016/01/21 10:34:29.539573 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
2016/01/21 10:34:29.496322 [info] AdGuard Home, version v0.107.11
2016/01/21 10:00:00.100089 [error] stats: deleting unit: bucket not found
2016/01/21 09:00:00.951018 [error] stats: deleting unit: bucket not found
2016/01/21 08:51:11.180232 [info] Received signal "hangup"
2016/01/21 08:50:45.620474 [info] Entering the tcp listener loop on [::]:53
2016/01/21 08:50:45.620373 [info] Entering the UDP listener loop on [::]:53
2016/01/21 08:50:45.620173 [info] Listening to tcp://[::]:53
2016/01/21 08:50:45.620076 [info] Creating a TCP server socket
2016/01/21 08:50:45.620055 [info] Listening to udp://[::]:53
2016/01/21 08:50:45.619833 [info] Creating the UDP server socket
2016/01/21 08:50:45.619769 [info] MaxGoroutines is set to 300
2016/01/21 08:50:45.619740 [info] DNS cache is enabled
2016/01/21 08:50:45.619719 [info] Cache TTL override is enabled. Min=300, Max=3600
2016/01/21 08:50:45.619660 [info] Starting the DNS proxy server
2016/01/21 08:50:28.634361 [info] Go to http://192.168.31.1:8080
2016/01/21 08:50:28.634300 [info] Go to http://[::1]:8080
2016/01/21 08:50:28.633235 [info] Go to http://127.0.0.1:8080
2016/01/21 08:50:28.632404 [info] AdGuard Home is available at the following addresses:
2016/01/21 08:50:27.128358 [info] Initialize web module
2016/01/21 08:50:27.128240 [info] auth: initialized.  users:1  sessions:4
2016/01/21 08:50:27.118637 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
2016/01/21 08:50:27.025924 [info] AdGuard Home, version v0.107.11

What I can see that, when the power was turn off, and when the power came back, the date was not same in the device. 

#### What did you do?
Due to load shedding in one of my office locations, the R2S will shut down suddenly. When the electricity is back, Adguard will start but can't browse anything. I have to turn off adguard home, then it will work. Then I have to enable it manually then it will work. 

#### Expected result

Before even with sudden poweroff, adguard will still work automatically. 

#### Actual result

But it doesn't start. Any website I visit it shows DNS Probe Error. 

#### Screenshots (if applicable)

Manually I turn off and turn on, then it was working

Here is the Log

2022/09/13 09:53:29.694775 [info] Updated filter #1660804183.  Rules: 58434 -> 57962
2022/09/13 09:53:29.694758 [info] Updated filter #1659512593.  Rules: 25961 -> 26412
2022/09/13 09:53:29.694744 [info] Updated filter #1659512592.  Rules: 11126 -> 11147
2022/09/13 09:53:29.694730 [info] Updated filter #1659512591.  Rules: 1729 -> 1730
2022/09/13 09:53:29.694714 [info] Updated filter #1659512587.  Rules: 439 -> 439
2022/09/13 09:53:29.694699 [info] Updated filter #1659512586.  Rules: 332350 -> 333280
2022/09/13 09:53:29.694683 [info] Updated filter #1628750871.  Rules: 55502 -> 55503
2022/09/13 09:53:29.694666 [info] Updated filter #1628750870.  Rules: 48683 -> 48820
2022/09/13 09:53:29.694643 [info] updated filter 1660804183: 1161655 bytes, 57962 rules
2022/09/13 09:53:29.694458 [info] saving filter 1660804183 contents to: /etc/AdGuardHome/data/filters/1660804183.txt
2022/09/13 09:53:24.135909 [info] updated filter 1659512593: 721196 bytes, 26412 rules
2022/09/13 09:53:24.135691 [info] saving filter 1659512593 contents to: /etc/AdGuardHome/data/filters/1659512593.txt
2022/09/13 09:53:23.657266 [info] updated filter 1659512592: 652767 bytes, 11147 rules
2022/09/13 09:53:23.657056 [info] saving filter 1659512592 contents to: /etc/AdGuardHome/data/filters/1659512592.txt
2022/09/13 09:53:23.455889 [info] updated filter 1659512591: 54341 bytes, 1730 rules
2022/09/13 09:53:23.455671 [info] saving filter 1659512591 contents to: /etc/AdGuardHome/data/filters/1659512591.txt
2022/09/13 09:53:22.080373 [info] updated filter 1659512587: 25323 bytes, 439 rules
2022/09/13 09:53:22.080155 [info] saving filter 1659512587 contents to: /etc/AdGuardHome/data/filters/1659512587.txt
2022/09/13 09:53:21.723591 [info] updated filter 1659512586: 7335387 bytes, 333280 rules
2022/09/13 09:53:21.723427 [info] saving filter 1659512586 contents to: /etc/AdGuardHome/data/filters/1659512586.txt
2022/09/13 09:53:19.682387 [info] updated filter 1628750871: 1093402 bytes, 55503 rules
2022/09/13 09:53:19.682218 [info] saving filter 1628750871 contents to: /etc/AdGuardHome/data/filters/1628750871.txt
2022/09/13 09:53:18.977125 [info] updated filter 1628750870: 944074 bytes, 48820 rules
2022/09/13 09:53:18.976920 [info] saving filter 1628750870 contents to: /etc/AdGuardHome/data/filters/1628750870.txt
2022/09/13 09:53:18.209548 [info] Entering the tcp listener loop on [::]:53
2022/09/13 09:53:18.209492 [info] Entering the UDP listener loop on [::]:53
2022/09/13 09:53:18.209254 [info] Listening to tcp://[::]:53
2022/09/13 09:53:18.209154 [info] Creating a TCP server socket
2022/09/13 09:53:18.209128 [info] Listening to udp://[::]:53
2022/09/13 09:53:18.208947 [info] Creating the UDP server socket
2022/09/13 09:53:18.208908 [info] MaxGoroutines is set to 300
2022/09/13 09:53:18.208882 [info] DNS cache is enabled
2022/09/13 09:53:18.208866 [info] Cache TTL override is enabled. Min=300, Max=3600
2022/09/13 09:53:18.208809 [info] Starting the DNS proxy server
2022/09/13 09:53:01.332236 [info] Go to http://219.317.208.227:8080
2022/09/13 09:53:01.332222 [info] Go to http://192.168.31.1:8080
2022/09/13 09:53:01.332206 [info] Go to http://[::1]:8080
2022/09/13 09:53:01.332159 [info] Go to http://127.0.0.1:8080
2022/09/13 09:53:01.330200 [info] AdGuard Home is available at the following addresses:
2022/09/13 09:53:00.529333 [info] Initialize web module
2022/09/13 09:53:00.529290 [info] auth: initialized.  users:1  sessions:4
2022/09/13 09:53:00.529011 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
2022/09/13 09:53:00.491959 [info] AdGuard Home, version v0.107.11
2016/01/21 10:34:47.222914 [info] Entering the tcp listener loop on [::]:53
2016/01/21 10:34:47.222863 [info] Entering the UDP listener loop on [::]:53
2016/01/21 10:34:47.222636 [info] Listening to tcp://[::]:53
2016/01/21 10:34:47.222536 [info] Creating a TCP server socket
2016/01/21 10:34:47.222506 [info] Listening to udp://[::]:53
2016/01/21 10:34:47.222289 [info] Creating the UDP server socket
2016/01/21 10:34:47.222250 [info] MaxGoroutines is set to 300
2016/01/21 10:34:47.222221 [info] DNS cache is enabled
2016/01/21 10:34:47.222205 [info] Cache TTL override is enabled. Min=300, Max=3600
2016/01/21 10:34:47.222146 [info] Starting the DNS proxy server
2016/01/21 10:34:30.362571 [info] Go to http://219.317.208.227:8080
2016/01/21 10:34:30.362556 [info] Go to http://192.168.31.1:8080
2016/01/21 10:34:30.362541 [info] Go to http://[::1]:8080
2016/01/21 10:34:30.362491 [info] Go to http://127.0.0.1:8080
2016/01/21 10:34:30.360391 [info] AdGuard Home is available at the following addresses:
2016/01/21 10:34:29.539946 [info] Initialize web module
2016/01/21 10:34:29.539903 [info] auth: initialized.  users:1  sessions:4
2016/01/21 10:34:29.539573 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
2016/01/21 10:34:29.496322 [info] AdGuard Home, version v0.107.11
2016/01/21 10:00:00.100089 [error] stats: deleting unit: bucket not found
2016/01/21 09:00:00.951018 [error] stats: deleting unit: bucket not found
2016/01/21 08:51:11.180232 [info] Received signal "hangup"
2016/01/21 08:50:45.620474 [info] Entering the tcp listener loop on [::]:53
2016/01/21 08:50:45.620373 [info] Entering the UDP listener loop on [::]:53
2016/01/21 08:50:45.620173 [info] Listening to tcp://[::]:53
2016/01/21 08:50:45.620076 [info] Creating a TCP server socket
2016/01/21 08:50:45.620055 [info] Listening to udp://[::]:53
2016/01/21 08:50:45.619833 [info] Creating the UDP server socket
2016/01/21 08:50:45.619769 [info] MaxGoroutines is set to 300
2016/01/21 08:50:45.619740 [info] DNS cache is enabled
2016/01/21 08:50:45.619719 [info] Cache TTL override is enabled. Min=300, Max=3600
2016/01/21 08:50:45.619660 [info] Starting the DNS proxy server
2016/01/21 08:50:28.634361 [info] Go to http://192.168.31.1:8080
2016/01/21 08:50:28.634300 [info] Go to http://[::1]:8080
2016/01/21 08:50:28.633235 [info] Go to http://127.0.0.1:8080
2016/01/21 08:50:28.632404 [info] AdGuard Home is available at the following addresses:
2016/01/21 08:50:27.128358 [info] Initialize web module
2016/01/21 08:50:27.128240 [info] auth: initialized.  users:1  sessions:4
2016/01/21 08:50:27.118637 [info] Initializing auth module: /etc/AdGuardHome/data/sessions.db
2016/01/21 08:50:27.025924 [info] AdGuard Home, version v0.107.11

What I can see that, when the power was turn off, and when the power came back, the date was not same in the device. 

#### Additional information
I am using this AdguardHome IPK file from herehttps://op.supes.top/packages/aarch64_generic/adguardhome_0.107.12-64_aarch64_generic.ipk
https://op.supes.top/packages/aarch64_generic/

#### Additional information
I am using this AdguardHome IPK file from herehttps://op.supes.top/packages/aarch64_generic/adguardhome_0.107.12-64_aarch64_generic.ipk
https://op.supes.top/packages/aarch64_generic/

**Comment by ainar-g** [comment]
Hello and thanks for the report.  You've mentioned that you use a custom OpenWrt package.  Does the issue persist if you install AdGuard Home using our official releases?

If it does, please collect [verbose logs][1] for when that happens and send them to us at devteam@adguard.com (please add the words “AdGuard Home Issue 4915” to the Subject line).  You should also probably check other system logs to see if this could be an issue with the init script.  Thanks!

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by xenstar** [comment]
Hello, I have install the Adguard Home official release, and also sent you the verbose log. Once I suddenly turn of my device, and turn it on, the date was changed to 2016. You can see in the log. If you need any further information, feel free to let me know.

**Comment by ainar-g** [comment]
We have received your logs, thanks.  Some comments:

1.  The logs look a bit weird, because they're reversed and also have some HTML entities in them.  Are you sure that this is a log file produced by AdGuard Home as opposed to some other log viewer software?

2.  Precise time is important for TLS (encryption) to work properly, so you should probably set up your system to either perform NTP sync on boot or at least not start AGH until the time is synchronized.

**Comment by ainar-g** [comment]
No response for over a year, closing.
