### ISSUE TITLE
功能增加

### ISSUE THREAD

**Issue by kuke21** [AdguardTeam/AdGuardHome#4918]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

希望可以增加域名解析后跳转即 访问A跳转到B
场景： 在美国苹果官网apple.com  (A) 在中国官网为apple.com.cn (B)  在iPhone Safari默认为美国苹果官网 访问后Safari会提示让我访问中国苹果官网，希望可以增加解析跳转功能

I hope to increase the domain name resolution and then jump, that is, visit A and jump to B
Scenario: Apple.com in the United States (A) Apple.com.cn in China (B) On iPhone Safari, the default is Apple's official website in the United States. After accessing the Apple's official website in the United States, Safari will prompt me to visit the Apple's official website in China, hoping to increase the parsing jump Function

**Comment by ameshkov** [comment]
我不太懂你要什么。你要不要访问 apple.com 的时候自动跳转 apple.com？

**Comment by kuke21** [comment]
访问 apple.com跳转apple.com.cn

**Comment by ameshkov** [comment]
那你能试试用 $dnsrewrite: https://adguard-dns.io/kb/general/dns-filtering-syntax/#dnsrewrite

可是我不太确定这个办法做好，DNS级的重写不是HTTP级的，它可能坏网站。
