### ISSUE TITLE
user rules in different config

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#492]
I don't really like the fact that the whole userrules block is just mashed string in the main config. Can we move it to user_rules.txt or smth?

**Comment by ameshkov** [comment]
User rules list is supposed to be short, that's why we simply keep it in the main config. You can add a custom filter if you want to have smth huge?

**Comment by Bluscream** [comment]
I know but even if it's supposed to be short that won't help because it will still fill up over time and in that case it's easier to bulk edit / maintain if it's a seperate file.

**Comment by ArchiveBase** [comment]
Take care this within web interface https://github.com/AdguardTeam/AdGuardHome/issues/817#issuecomment-534275463

**Comment by szolin** [comment]
You can add a filter list from a local file.
