### ISSUE TITLE
ssllab result capped to B

### ISSUE THREAD

**Issue by ssrahul96** [AdguardTeam/AdGuardHome#4925]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.15

#### What did you do?

SSL Lab test result is `B`

ref : https://blog.qualys.com/product-tech/2018/02/02/forward-secrecy-authenticated-encryption-and-robot-grading-update

Seems like additional config changes at go http listener

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/15570570/190858692-98504a1d-f0b1-4c6b-ae47-d33e45bb1271.png)

#### Additional information

Reference Article to check : https://www.namecheap.com/support/knowledgebase/article.aspx/9653/38/how-to-check-whether-the-server-supports-forward-secrecy/

tried `openssl s_client -connect example.com:443 -cipher "DHE, EDH"` , the request was failing,

I dont ve idea about these ciphers. I tried for few sites with ssl lab report `A+` the above command was passing

**Comment by ssrahul96** [comment]
@ainar-g , Kindly check https://github.com/AdguardTeam/AdGuardHome/pull/4936

**Comment by ssrahul96** [comment]
updated PR https://github.com/AdguardTeam/AdGuardHome/pull/4990

**Comment by ainar-g** [comment]
If I recall correctly, both the ciphers and the HSTS issues are now resolved?

**Comment by ssrahul96** [comment]
Yes, we are good, 

For SSL Cipher, Users Can choose what they needs, 
HSTS is enabled by default when we enable https
