### ISSUE TITLE
Scroll is not working when pressing on device logo

### ISSUE THREAD

**Issue by MkQtS** [AdguardTeam/AdGuardHome#4926]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.13

#### What did you do?

1. Visit AdGuard Home Setup Guide page using a mobile browser
2. Press on the device logo and try to scroll horizontally

#### Expected result

The device logo folows my finger

#### Actual result

It's not scrollable when pressing on the device logos

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/81752398/190861815-fc61b87b-addb-4a32-a0fd-8f074897a6b3.png)

Only the green area is scrollable, pressing and scrolling on red area is not working.

**Comment by ainar-g** [comment]
@MkQtS, hello.  This should be fixed on the Edge channel.  Could you please check if the UI behaves correctly now?
