### ISSUE TITLE
Cannot unblock website blocked by parental controls

### ISSUE THREAD

**Issue by crnh** [AdguardTeam/AdGuardHome#4932]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

1.107.13

#### What did you do?

I am running AdGuard Home as a Home Assistant Addon on Home Assistant OS, with DHCP being handled by the router. I am also using a similar, second setup in a different location (and network), where I get the same problem.
If I try to visit bol.com (a Dutch webshop), I get the parental controls blockpage. I tried to whitelist this webpage, but still can't access this webpage. This has been a problem for at least two months, so I don't expect it to be a caching issue.

This problem may seem the same as the problem mentioned in https://github.com/AdguardTeam/AdGuardHome/issues/3062, but due to the problem duration, I am not sure whether this is a caching issue.

#### Steps to reproduce

1. Add these custom filtering rules:
  ```
  @@||bol.com^
  @@||www.bol.com^
  @@||s-bol.com^
  ```
2. Visit https://bol.com

#### Expected result

Bol.com can be accessed normally

#### Actual result

The parental controls blockpage of AdGuard Home is shown

Interestingly, the query log shows bol.com as being unblocked (see screenshot), and it doesn't show any other websites being blocked by parental controls.
Furthermore, the verbose logs (which I turned on in the config file) doesn't mention Bol.com being blocked (see additional information)

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/30109443/191091552-250ae573-c633-4c23-9217-bbab2a9e6d00.png)

#### Additional information

Verbose logs:

```
;; QUESTION SECTION:
;bol.com.	IN	 A

2022/09/19 20:16:32.196309 577#673 [debug] looking up settings for client with ip xxx.xxx.xxx.xxx and clientid ""
2022/09/19 20:16:32.196416 577#673 [debug] using settings for client "xxxx" with ip xxx.xxx.xxx.xxx and clientid ""
2022/09/19 20:16:32.196538 577#673 [debug] hosts container: handling the request
2022/09/19 20:16:32.197098 577#673 [debug] filtering: found rule "@@||bol.com^" for host "bol.com", filter list id: 0
2022/09/19 20:16:32.197133 577#617 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).replyFromUpstream(): RTT: 6.892742ms
2022/09/19 20:16:32.197347 577#617 [debug] Override TTL from 279 to 3600
2022/09/19 20:16:32.197393 577#674 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*TLSPool).Get(): Returning existing connection to 1.0.0.3:853 with updated deadLine
2022/09/19 20:16:32.197522 577#617 [debug] Override TTL from 1779 to 3600
2022/09/19 20:16:32.197559 577#674 [debug] tls://family.cloudflare-dns.com:853: sending request A bol.com.
2022/09/19 20:16:32.197666 577#617 [debug] Override TTL from 279 to 3600
2022/09/19 20:16:32.197761 577#617 [debug] Override TTL from 39 to 3600
2022/09/19 20:16:32.197833 577#617 [debug] Override TTL from 219 to 3600
2022/09/19 20:16:32.197902 577#617 [debug] Override TTL from 219 to 3600
2022/09/19 20:16:32.197971 577#617 [debug] Override TTL from 219 to 3600
2022/09/19 20:16:32.198114 577#617 [debug] dnsforward: checking CNAME aadcdnoriginwus2.azureedge.net for aadcdn.msauth.net.
2022/09/19 20:16:32.198424 577#617 [debug] dnsforward: checking CNAME aadcdnoriginwus2.afd.azureedge.net for aadcdnoriginwus2.azureedge.net.
2022/09/19 20:16:32.198572 577#617 [debug] dnsforward: checking CNAME firstparty-azurefd-prod.trafficmanager.net for aadcdnoriginwus2.afd.azureedge.net.
2022/09/19 20:16:32.199007 577#617 [debug] dnsforward: checking CNAME dual.part-0013.t-0009.t-msedge.net for firstparty-azurefd-prod.trafficmanager.net.
2022/09/19 20:16:32.199177 577#617 [debug] dnsforward: checking CNAME part-0013.t-0009.t-msedge.net for dual.part-0013.t-0009.t-msedge.net.
2022/09/19 20:16:32.199298 577#617 [debug] dnsforward: checking A 13.107.246.41 for part-0013.t-0009.t-msedge.net.
2022/09/19 20:16:32.199389 577#617 [debug] dnsforward: checking A 13.107.213.41 for part-0013.t-0009.t-msedge.net.
2022/09/19 20:16:32.199475 577#617 [debug] client ip: xxx.xxx.xxx.xxx
2022/09/19 20:16:32.199640 577#617 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: NOERROR, id: 42682
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0
```

**Comment by ainar-g** [comment]
Since your query log clearly shows that the query is allowed, the most likely scenario is that your browser or system has cached the filtered response.

**Comment by crnh** [comment]
Sure, that was my initial thought as well. But how likely is a caching problem to persist for over 2 months, on all devices in the same network, and even survive reboots?

If more data are needed, feel free to ask and I'll supply them.

**Comment by ainar-g** [comment]
Hm.  In that case, I'm kind of lost, to be honest.  Some additional pointers:

1.  I've noticed that you're using a persistent client.  Do the settings for the client sync with the default settings?

2.  What do you see when you query your AGH using a plain DNS tool, like `nslookup bol.com $AGH_ADDR`?

**Comment by crnh** [comment]
1. Except for the blocked services, all settings are synced with the default settings. The problem does also occur on non-persistent clients.
2. I get this:
    ```
    Non-authoritative answer:
    Name:    bol.com
    Address:  185.14.169.113
    ```
    And that seems to be correct (I verified it with https://nslookup.io, which gave the same response).

However, I also see this in the logs:

![image](https://user-images.githubusercontent.com/30109443/191443293-8c850b42-77d0-44ba-8d7c-b3ed75fd9933.png)

And as far as I know, that IP belongs to the AdGuard block page... so sometimes AGH seems to return the blockpage IP, but this is not always the case, since I also see log entries listing the correct bol.com IP address.

**Comment by crnh** [comment]
I just changed my upstream DNS servers from

```
tls://family.cloudflare-dns.com
quic://family.adguard-dns.com
```

to the UDP cloudflare family DNS servers:

```
1.1.1.3
1.0.0.3
```

and now bol.com is accessible. AGH is set to use parallel requests. Before, most (if not all) queries were resolved via the adguard DNS-over-quic server. Could it be that the problem is caused by using this server? If so, does anyone know where I can file an issue for this?

**Comment by ainar-g** [comment]
Ah, I see.  AdGuard Home and AdGuard DNS use pretty much the same lists for their parental control features.  Essentially, even though you unblocked the site in AGH, AGD still blocked it.

Use a different upstream for that domain only:

```none
tls://family.cloudflare-dns.com
quic://family.adguard-dns.com
[/bol.com/]1.1.1.1
```

**Comment by crnh** [comment]
Okay, that does indeed fully explain it. Thanks for the advice about using a different upstream!
