### ISSUE TITLE
ERROR in host resolution name with "_" and ok with "-"

### ISSUE THREAD

**Issue by eddie7332** [AdguardTeam/AdGuardHome#4937]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Versión:  v0.107.13

#### What did you do?
n/a
#### Expected result
n/a
#### Actual result
n/a
#### Screenshots (if applicable)
n/a
#### Additional information
In local name resolution it does not support a compound name with an underscore "_". Instead, it does accept a hyphen "-". Both in the local configuration in Adguard and in /etc/hosts.

Example:
OK --> "machine-number1.local"
KO --> "machine_number1.local"

Is it possible that they can solve it?

Thank you very much.

**Comment by ainar-g** [comment]
Hello.  Underscores are generally considered invalid in domain names, apart from specific cases such as `SRV` question targets.  From `man hosts`:

 >  Host names may contain only alphanumeric characters, minus signs ("-"), and periods (".").

**Comment by eddie7332** [comment]
OK

thx
