### ISSUE TITLE
Client name is not updating on same IP

### ISSUE THREAD

**Issue by ctr-privat** [AdguardTeam/AdGuardHome#4939]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.13

### Description

I had a client running on IP x.x.x.21 with a name A-BBBB-C. Now that client is changed and so it's name is now A-B-C. 
The Client is also listed with it's IP address under "Private reverse DNS servers" as it is one of my Windows domain DC's. 
The dashboards "Top Client list" is still displaying that client to be the old name. Same old name is found at settings menue "Client settings -> Runtime Clients".
My reverse DNS servers only have entrys to the new name. 
I expect ADguard Home to update the name frequently, at least on statistics auto-cleanup/once a day. 
Im running ADguard Home on Ubuntu 20.04.5 LTS, running as vm guest on Hyper-V.

**Comment by ainar-g** [comment]
@EugeneOne1, please investigate.  I think, runtime clients may not have a concept of staleness?  There also may be something weird going on with caching of rDNS results.

**Comment by EugeneOne1** [comment]
@ctr-privat, hello.  We've pushed an update to the edge channel.  The build should now update the RDNS-received names at least once a day.  Could you please check if it works properly with your clients?

**Comment by ctr-privat** [comment]
Thank you, this seem to work now :)
