### ISSUE TITLE
DNS cache poison of DNSSEC?

### ISSUE THREAD

**Issue by PeterDaveHello** [AdguardTeam/AdGuardHome#4942]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.12

#### What did you do?

Use `dig` to query `sigfail.verteiltesysteme.net` with and without `+cd` flag(to set the CD _(checking disabled)_ bit in the query) to ask or not ask the resolver to bypass the DNSSEC check

#### Expected result

Without `+cd` flag, we shouldn't receive the IP address but only [SERVFAIL](https://dnssec.vs.uni-due.de/dig-sigfail)

#### Actual result

Once we used `+cd` flag to query the record, the result was successful and cached, but the following query to the same record without `+cd` flag will also get the same result.

#### Additional information

```sh
/opt/adguardhome/work $ dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work $ dig +cd +short sigfail.verteiltesysteme.net @127.0.0.1
134.91.78.139
/opt/adguardhome/work $ dig +short sigfail.verteiltesysteme.net @127.0.0.1
134.91.78.139
```

**Comment by EugeneOne1** [comment]
@PeterDaveHello, hello.  We've pushed the latest edge build that should fix the issue.  Shortly, we've decided to avoid cache for requests and responses with `CD` flag.  Could you please check if it works as expected?

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello, hello. We've pushed the latest edge build that should fix the issue. Shortly, we've decided to avoid cache for requests and responses with `CD` flag. Could you please check if it works as expected?

sure, just to make sure, does that edge build including Docker images on Docker Hub? Thanks.

**Comment by PeterDaveHello** [comment]
Okay, looks like it works:


```
/opt/adguardhome/work # dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work # dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work # dig +cd +short sigfail.verteiltesysteme.net @127.0.0.1
134.91.78.139
/opt/adguardhome/work # dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work # dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work # dig +cd +short sigfail.verteiltesysteme.net @127.0.0.1
134.91.78.139
/opt/adguardhome/work # dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work # dig +cd +short sigfail.verteiltesysteme.net @127.0.0.1
134.91.78.139
/opt/adguardhome/work # dig +short sigfail.verteiltesysteme.net @127.0.0.1
/opt/adguardhome/work # 
```

**Comment by EugeneOne1** [comment]
@PeterDaveHello, great.  I'll close the issue if you don't mind.  Thanks for reporting and testing.

**Comment by PeterDaveHello** [comment]
Sure! Thanks for your effort!
