### ISSUE TITLE
AGH binary identified/deleted as malware on Win 10

### ISSUE THREAD

**Issue by iophobia** [AdguardTeam/AdGuardHome#4943]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b15

#### What did you do?
nothing
#### Expected result
server keeps running
#### Actual result
sudden AGH server shutdown, checked PC on which it's running, exe was gone from program folder + notification about found malware (weirdly couldn't get it to bring up what was seemingly found or even remove anything from quarantine.
#### Additional information
excluded AGH directory from further scans (assuming it's a false positive at this stage)
Edit: Not necessarily a bug report with AGH but I guess you guys should get in touch with MS to have them update their signatures/heuristics...

**Comment by ainar-g** [comment]
Apologies for no response for almost a year.  It's a common issue with Go binaries.  See <https://go.dev/doc/faq#virus>.
