### ISSUE TITLE
Custom filtering rules dissappeared,

### ISSUE THREAD

**Issue by RonKhondji** [AdguardTeam/AdGuardHome#4945]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Built from 'Master'

### Description

Commit "Pull request: 4871 imp filtering" {47c9c946a3698c22305e69dc67e8ba585eb681d6} has deleted all my custom filtering rules from AdGuardHome.yaml.

The relevant line has reverted to "user_rules: []".

I had a backup of most of them so it was easy enough to put them back, but it looks like an unintended effect of the filtering improvements.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Same happened here (latest ARM64 release). I also wasn't able to save rules once I pasted them from earlier YAML file. I had to revert to previous release to get everything back up and running.

**Comment by Dynasty-Dev** [comment]
Having the same issue here on the latest edge build

**Comment by tmiland** [comment]
Same issue.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Has this been fixed?

**Comment by EugeneOne1** [comment]
@RonKhondji, hello and thanks for the report.  Indeed we've introduced a bug in the recent update.  Should be fixed in the latest edge build.  Could you please check it out?

@7ArxS2PrqAUF9Gom, @Dynasty-Dev, @tmiland, could you also please give a feedback on the issue status?

**Comment by RonKhondji** [comment]
New build did not delete custom rules. All good again.

**Comment by EugeneOne1** [comment]
@RonKhondji, great to hear.  Thanks for testing, we're closing the issue now.  Please, feel free to open new issues on found problems.
