### ISSUE TITLE
How to set reverse proxy for AdGuardHome Dashboard with apache correctly?

### ISSUE THREAD

**Issue by cpiekacz** [AdguardTeam/AdGuardHome#4946]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (Debian)

### CPU architecture

x86

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.7

#### What did you do?

I try to set up reverse proxy on Apache2 for AdGuard Home Dashboard but each time I open https://mydomain/adguard/ it gets redirected to /login.html. I've enabled `allow_unencrypted_doh: true` in the _AdGuardHome.yaml_ just in case but it makes no difference. The dashboard works correctly when accessed directly through a dedicated port.

```
<VirtualHost *:443>
    ServerName mydomain

    RewriteEngine on

    ProxyPreserveHost On
    ProxyRequests Off
    
    # AdGuard
    RewriteRule ^/adguard$ /adguard/ [END,NE,R]
    <Location /adguard/>
        ProxyPass http://localhost:3000/
        ProxyPassReverse http://localhost:3000/
    </Location>

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile ...
    SSLCertificateKeyFile ...
</VirtualHost>
```

#### Expected result

Browser opens AdGuard Home Dashboard

#### Actual result

Browser gets redirected to /login.html

#### Screenshots (if applicable)

```
root@dell:~# curl -I https://mydomain/adguard/
HTTP/1.1 302 Found
Date: Sat, 24 Sep 2022 16:49:58 GMT
Server: Apache/2.4.38 (Debian)
Access-Control-Allow-Origin: http://mydomain
Location: /login.html
Vary: Origin

```

**Comment by fernvenue** [comment]
You need something support path prefex like [traefik](https://doc.traefik.io/), as far as I know, apache can not do that, or...hard to do.

**Comment by cpiekacz** [comment]
After many hours I've managed to configure it correctly. You need to enable `remoteip` module and then add the following two lines to the config:

```
ProxyVia On
RemoteIPHeader X-Forwarded-For

```

**Comment by ppfeufer** [comment]
Apache vhost

```apache
<VirtualHost *:80>
    ServerName my_adguard

    ProxyPreserveHost On

    <Location "/dns-query">
        ProxyPass "http://127.0.0.1:8100/dns-query"
        ProxyPassReverse "http://127.0.0.1:8100/dns-query"
    </Location>

    <Location "/">
        ProxyPass "http://127.0.0.1:8100/"
        ProxyPassReverse "http://127.0.0.1:8100/"
    </Location>

    ErrorLog /path_to//error.log
    CustomLog /path_to/access.log combined

    # SSL Redirect
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =my_adguard
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

Replace `my_adguard` with your domain name for obvious reasons :-)

SSL vhost should look similar, just with all the SSL stuff in it.

**Comment by henosch** [comment]
>     # SSL Redirect
>     RewriteEngine on
>     RewriteCond %{SERVER_NAME} =my_adguard
>     RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
> </VirtualHost>
> ```
> 
> Replace `my_adguard` with your domain name for obvious reasons :-)
> 
> SSL vhost should look similar, just with all the SSL stuff in it.

This doesn't work with SSL.  I can access adguard from the Internet, but without SSL.  And we don't want that.
