### ISSUE TITLE
Ignore invalid rule

### ISSUE THREAD

**Issue by dishuostec** [AdguardTeam/AdGuardHome#495]
### Steps to reproduce
1. Add filter https://easylist-downloads.adblockplus.org/easylistchina.txt
2.
3.
4.

### Expected behavior
Load filters and ignore invalid rule or disable whole filter.

### Actual behavior
DNS server is unavailable and log is full of text:
> plugin/dnsfilter: error parsing regexp: invalid or unsupported Perl syntax: \`(?!`

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.91
| How did you setup DNS configuration:| SBC
| If it's a router or IoT, please write device model:| NanoPi-NEO2
| Operating system and version:| Ubuntu 16.04.4 LTS

**Comment by ameshkov** [comment]
That's a good bug, AG Home mustn't be broken by invalid rules

**Comment by hmage** [comment]
This is not v0.91. `plugin/dnsfilter` is from coredns plugin, we've removed coredns in 0.91. Are you sure you're running v0.91?

Either way, on v0.91 it does not crash and works just fine.

**Comment by hmage** [comment]
If the problem still happens on latest version, feel free to reopen this issue.

**Comment by hmage** [comment]
My mistake. v0.91 is still coredns-based. Next release will have the issue fixed.

**Comment by ameshkov** [comment]
Resolved in the master branch.
