### ISSUE TITLE
DoQ and TLS can use,but DoH can't use,after add ClientID and the DoQ and TLS can't use too.

### ISSUE THREAD

**Issue by Zhzy223** [AdguardTeam/AdGuardHome#4950]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.13

**Comment by ainar-g** [comment]
Please fill the issue template properly.

**Comment by overwatch3560** [comment]
is there still an issue @Zhzy223 ?
