### ISSUE TITLE
Error while adding custom upstream in the client settings 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardHome#4952]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v.0.107.13

#### Prerequisites: 
- AdGuard Home installed and running 
- At least one device added as a client 

#### Steps to reproduce: 

1. Open https://adguard-dns.io/kb/general/dns-providers/
2. Select by double-click and copy any DNS address from the list 
3. Open **Settings** tab -> **Client settings** 
4. Click on the **Edit** button 
5. Paste the copied DNS address in the client upstream field   
6. Click on the **Save** button 

#### Expected result
Settings successfully saved 

#### Actual result
Error occurred
![image (3)](https://user-images.githubusercontent.com/107266340/192280488-e70b1f7f-db8c-4674-83ff-d6962bdefbb5.png)

#### Additional information
If you perform the same actions in the main DNS settings tab (**Settings** -> **DNS settings**), changes will be saved successfully.

**Comment by ppfeufer** [comment]
Remove the trailing whitespace from the IPs

**Comment by ainar-g** [comment]
@ppfeufer, the bug is actually about the inconsistency between the behaviours of the main upstream input and the input of custom upstreams for users.  The main one strips them automatically.
