### ISSUE TITLE
Changing HTTP port doesn't stop it hosting on port 80

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#4959]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Custom port

### Setup

On one machine

### AdGuard Home version

Latest Beta

#### What did you do?

Changed the config file to edit port 80 to a custom port

#### Expected result

Port 80 would be unused and AdGuard Home would only run on the custom port in config file leaving Port 80 usable by other software

#### Actual result

Port 80 is used by AdGuard Home anyway and is not usable by other software regardless of custom port config.

#### Screenshots (if applicable)

Not applicable

#### Additional information

Ubuntu 20 LTS

**Comment by ishanjain28** [comment]
Hey OP, Did you restarted the application after changing port?
