### ISSUE TITLE
Whitelisting a website so that ads are not blocked

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdGuardHome#496]
[Can]([url]()) u plz tell me how to whitelist kissmanga.com and kissanime.ru?
Adguard blocks the ads on the website so when I open a specific manga it first loads then breaks 
![screenshot_20181227-153909_chrome](https://user-images.githubusercontent.com/46019727/50475138-cfd12480-09ed-11e9-810d-75ef71288183.jpg)

**Comment by ameshkov** [comment]
DNS-level blocking is not that flexible, you cannot unblock ads on a single website.

What you need to do is figure blocking which domain breaks the website, and unblock that domain in your user filter.

**Comment by ameshkov** [comment]
Try using dev tools on your desktop computer and see what domains are blocked, then try unblocking them one by one.
