### ISSUE TITLE
use safe search is not working and parental contole web servers is not working

### ISSUE THREAD

**Issue by cchalifo999** [AdguardTeam/AdGuardHome#4960]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

latest

### Description

![Adguard-docker](https://user-images.githubusercontent.com/2941510/192650580-cdc9568d-1445-44bc-9c68-915d349bd2ec.png)
use safe search is not working and parental contole web servers is not working

**Comment by cchalifo999** [comment]
> Adguard DNS over HTTPS is unreachable:
> 
>     * https://family.adguard-dns.com/dns-query
> 
>     * https://dns.adguard-dns.com/dns-query

ty

**Comment by ameshkov** [comment]
Hm, I am not sure how that's possible.

What do you see when you run `https://dns.adguard-dns.com/info.txt` in the browser?

Could you please run `traceroute 94.140.14.14` and show the results?
