### ISSUE TITLE
DNS settings over DHCP don't seems to work, with complications

### ISSUE THREAD

**Issue by NBSDEVApp** [AdguardTeam/AdGuardHome#4971]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [x] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.13

#### What did you do?
Hello, I have setup my AdGuard to manage the network as a DHCP server. It manage well my client with ip and some request, but for some client like my Mac, he get no requests at all. And I have check the dns side of this client and I don't see other dns specific.

So, I have try to manually add the dns suggered in the adguardhome panel inside my mac network config, the DNS actually worked and block stuff, but I can't reach any local IP like adguard panel or other hosted app (even the one with domain name+ reverse proxy).

Do I need to add any more stuff? Or the issue is on my DHCP? Because I think with the DHCP on Adguard I would not need to manually add dns ...

#### Additional information
DNS PAGE:
DNS: https://dns.quad9.net/dns-query
Reverse private DNS servers: Nothing inside, the two next box unchecked
No EDNS
DNSSEC On
No ipv6 resolve
(tell me if you need more info..)

**Comment by dylandjian** [comment]
I currently seem to have the same issue for some reason... 

I can see in the DHCP settings that leases are properly attributed to different devices in the network when they connect and that the gateway works well but sadly it seems that no traffic goes through the DNS of the AdGuard Home.

Also, it seems that the network doesn't go through for the device the DHCP server is activated on (like it is not properly using the gateway itself) !

Thanks for the help

**Comment by ainar-g** [comment]
Hello.  A few clarifications:

1.  Are the DHCP settings are correct?  I.e., is the gateway address is actually the address of the interface on which AGH is serving DHCP?

2.  Are there any other routers on the network?

3.  Do you see requests for IP addresses in the logs if you enable [verbose logging][1]?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by NBSDEVApp** [comment]
1. The gateway is my original router ipv4 and 6
2. Yes, my internet router
3. No I don't see any requests
The thing that is weird is that's it's only on my two Apple Devices (Mac and iphone), my android tv and android tablet get automaticly the good gateway and are visible in the log.
The two devices with issues (mac and iphone) are still on the adguard dhcp IP I have assigned them, but I don't know how they "bypass" the gateway for the original one...

**Comment by daniellwdb** [comment]
I'm facing a similar issue. I set up Adguard on a raspberry pi 4 with docker compose using `192.168.178.77` as static local ip:
```yaml
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.107.10
    volumes:
      - ${DATA_DIR}/adguardhome:/opt/adguardhome/work
      - ${CONFIG_DIR}/adguardhome:/opt/adguardhome/conf
    network_mode: host
    restart: unless-stopped
```
I configured DHCP in Adguard:
![image](https://user-images.githubusercontent.com/44723767/194814009-ce25a0fd-4630-4b24-a877-3dc48a645deb.png)
Then I disabled DHCP in my router. In the list of DHCP leases I see ip's being given properly, but nothing is being logged / blocked. On my iOS device I tried to set the DNS manually to my pi's IP (`192.168.178.77`) which does work but it's not ideal. 

Docker logs:

<details>
  <summary>Open</summary>
<pre>
adguardhome  | 2022/10/10 07:04:31.196180 [info] AdGuard Home, version v0.107.10
adguardhome  | 2022/10/10 07:04:31.204377 [info] dhcp: loaded leases v4:8  v6:0  total-read:8 from DB
adguardhome  | 2022/10/10 07:04:31.219713 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguardhome  | 2022/10/10 07:04:31.220091 [info] auth: initialized.  users:1  sessions:5
adguardhome  | 2022/10/10 07:04:31.220159 [info] Initialize web module
adguardhome  | 2022/10/10 07:04:31.442229 [info] dhcpv4: listening
adguardhome  | 2022/10/10 07:04:31.442412 [info] AdGuard Home is available at the following addresses:
adguardhome  | [dhcpv4] 2022/10/10 07:04:31 Server listening on 0.0.0.0:67
adguardhome  | [dhcpv4] 2022/10/10 07:04:31 Ready to handle requests
adguardhome  | 2022/10/10 07:04:31.443293 [info] Go to http://127.0.0.1:8089
adguardhome  | 2022/10/10 07:04:31.443322 [info] Go to http://[::1]:8089
adguardhome  | 2022/10/10 07:04:31.443335 [info] Go to http://192.168.178.77:8089
adguardhome  | 2022/10/10 07:04:31.443353 [info] Go to http://[2001:1c04:3519:c00:e65f:1ff:fea6:4e42]:8089
adguardhome  | 2022/10/10 07:04:31.443366 [info] Go to http://172.17.0.1:8089
adguardhome  | 2022/10/10 07:04:36.856788 [info] Starting the DNS proxy server
adguardhome  | 2022/10/10 07:04:36.856853 [info] Ratelimit is enabled and set to 20 rps
adguardhome  | 2022/10/10 07:04:36.856888 [info] The server is configured to refuse ANY requests
adguardhome  | 2022/10/10 07:04:36.856902 [info] MaxGoroutines is set to 300
adguardhome  | 2022/10/10 07:04:36.856937 [info] Creating the UDP server socket
adguardhome  | 2022/10/10 07:04:36.857193 [info] Listening to udp://[::]:53
adguardhome  | 2022/10/10 07:04:36.857224 [info] Creating a TCP server socket
adguardhome  | 2022/10/10 07:04:36.857358 [info] Listening to tcp://[::]:53
adguardhome  | 2022/10/10 07:04:36.857589 [info] Entering the UDP listener loop on [::]:53
adguardhome  | 2022/10/10 07:04:36.857706 [info] Entering the tcp listener loop on [::]:53
adguardhome  | [dhcpv4] 2022/10/10 07:05:03 Handling request from 0.0.0.0:68
adguardhome  | 2022/10/10 07:05:03.504140 [info] dhcp: stored 8 leases in db
adguardhome  | [dhcpv4] 2022/10/10 07:07:41 Handling request from 192.168.178.13:68
adguardhome  | 2022/10/10 07:07:41.166646 [info] dhcp: stored 8 leases in db
</pre>
</details>

**Comment by ainar-g** [comment]
@NBSDEVApp, @daniellwdb, which network interface are you using?  If you're only using the wired interface (e.g. `eth0`) then only the clients connected over the wire will get DHCP leases.

**Comment by daniellwdb** [comment]
> @NBSDEVApp, @daniellwdb, which network interface are you using? If you're only using the wired interface (e.g. `eth0`) then only the clients connected over the wire will get DHCP leases.

I don't think that's true? I have my PC and raspberry pi connected via ethernet to my router and phone over Wi-Fi and both show up in the DHCP leases list. But also both have the same issue of me having to manually set the DNS to the static raspberry pi ip in order for Adguard to work

**Comment by ainar-g** [comment]
@daniellwdb, your version of AdGuard Home is outdated, by the way.  There have been various fixes, including to the DHCP server.

Other than that, please enable [verbose logs][1] to see exactly what AdGuard Home is sending to the devices.  In particular, looking for the `Name Server` option.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by daniellwdb** [comment]
My bad. I actually downgraded to see if the issue was also there on older versions. I had the same issue on :latest the moment I posted my first comment. I will try to enable verbose logging when I get home and post the results

**Comment by NBSDEVApp** [comment]
> 

(I'm on v0.107.14) The thing is I don't see "eth0" but I see the local IP of my Pi, who run AdGuard. I don't know if this is a bug.

**Comment by NBSDEVApp** [comment]
<img width="1208" alt="Capture d’écran 2022-10-12 à 11 48 05" src="https://user-images.githubusercontent.com/26217768/195310437-67190b34-8304-4e02-9e87-9a1c716343d6.png">

**Comment by NBSDEVApp** [comment]
My issue is fixed, it was the ipv6 of my router who grabbed some devices to the router dns...
I have fix this by disabling ipv6 on my router, because I can't create range on this router.

**Comment by overwatch3560** [comment]
Nice to hear your issue has been resolved. I wish you a very nice rest of your day! You know where to find us if any issues come up
