### ISSUE TITLE
Add ability to define custom A/AAAA records. 

### ISSUE THREAD

**Issue by grogi** [AdguardTeam/AdGuardHome#4972]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

User needs to manually define a DNS record (be it A or AAAA). Typically those are hosts with statically configured IP addresses, not obtained via DHCP. 

#### Proposed solution

A UI dialog that allows to define custom DNS records. The dialog could be very similar to the one where administrator defines the resolvers. But now, instead of the resolver address, the user specifies the IP or IPv6 addresses to resolve.

#### Alternatives considered

AdGuardHome respects the /etc/hosts file. While this acts as a hackaround solution, it is not ideal. Editing the file requires shell access to the appliance with root privilege.

**Comment by ainar-g** [comment]
Please see the [documentation for `dnsrewrite` rules on our Wiki][1].

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite
