### ISSUE TITLE
Unable to select next during initial setup | Authentication Sep 3 | Error: control/install/configure | Timeout 503

### ISSUE THREAD

**Issue by ozsmac** [AdguardTeam/AdGuardHome#4973]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.108.0-b.16 (have tried both Standard and Beta channel versions, same issue)

#### What did you do?
After following the instructions in the main Github page, I'm able to install and get the web setup running, however it is failing on step 3, Authentication.  The next button changes colour and can be clicked, however nothing happens, then I start seeing "Error: control/install/configure | Timeout | 503.  

I'm unable to proceed, however can click back to get to the step 2 page, when click next and get to step 3, same issue occurs.

I have uninstalled and re-installed, and tested both normal and beta channel relelases with the same issue.

#### Expected result
To be able to enter a username and password, then click next to get to step 4.

#### Actual result
When clicking the Next button (that changes colour when fields are completed on the page, it clicks and the colour changes again, however nothing happens, then I start seeing "Error: control/install/configure | Timeout | 503.  

#### Screenshots (if applicable)
<img width="626" alt="image" src="https://user-images.githubusercontent.com/71823638/193225311-a3567d16-ba67-4434-aef5-ff8c479cafaf.png">

![image](https://user-images.githubusercontent.com/71823638/193225347-a7961e5b-1436-4d08-b3a5-1121a949ebc5.png)

#### Additional information

O/S: Ubuntu 22.04.2 LTS (5.15.0.48-generic aarch64
Hardware: Mac Studio M1, using Multipass for virtualisation 
Client (web): Safari, Chrome & Firefox tested on MacMS and iPad

I have looked at issue 3987 (and duplicate 3999), however this doesn't quite match my issue and appears to have been fixed quite a while ago.

Wasn't sure if I should open a discussion topic or report as a bug, thank you for any help or guidance.

**Comment by ainar-g** [comment]
Hello.  This 503 doesn't look like it's coming from AdGuard Home, because AdGuard Home doesn't currently use that status.  Are you sure that there isn't another service or HTTP proxy in the system?

**Comment by overwatch3560** [comment]
Is there still an issue @ozsmac ?

**Comment by ozsmac** [comment]
I gave up on using multiphase for various reasons, I inspect this issue was something to do with the specific multiphase implementation on MacOS Apple Silicon.
