### ISSUE TITLE
Direct IP connections to the server doesn't work when using AGH in Windows 11 22H2

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#4975]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.14

#### What did you do?

I updated my Windows 11 PC to 22H2 stable on launch day.

#### Expected result

Connecting to an AdGuard Home server with an IPv4 or IPv6 connection works, especially so on LAN connections.

#### Actual result

Direct IP connections to AGH are either no longer working, or are so ultra-slow that connections to it time out, after updating the server OS to Windows 11 22H2, both with AGH 0.107.14, 0.107.13, and 0.108.0-b.15. Apparently my server has been down for 10 days except for DoH and possibly DoQ.

From what I can tell on my end:
* `netstat -an` shows `0.0.0.0:53` and `[::]:53` as `LISTENING` on TCP, and as `*:*` on UDP.
* `AdGuardHomeLogFile.txt` shows `[info] Listening to udp://[::]:53`, but strangely enough does **not** show `[info] Listening to udp://127.0.0.1:53`. There seem to be no mention of listeners being closed.
* "Windows Defender Firewall with Advanced Settings" claims that port 53 has been completely opened, though it has been mistaken before.
* Port 53 seems to be forwarded on both IPv4 and IPv6 on my ASUS router.
* `.\AdGuardHome.exe --service restart` seems to make it work for between 2 and 60 seconds again, after which it no longer works again.
* The AdGuard for Android logger shows `04:47:43.039 [AsyncTask #7] WARN  com.adguard.android.filtering.dns.c - Failed to test 192.168.1.188 java.lang.IllegalArgumentException: Request timed out`
* My Nintendo Switch can't connect either, usually with either `Error Code: 2110-3127 (...) Could not perform DNS name resolution` or `Error Code: 2160-8006 (...) There is no response from the server`.
* The failed connections don't show up at all on AGH's admin GUI log page.
* Trying to connect to `127.0.0.1` as DNS from the server PC doesn't work either, remarkably enough.

#### Screenshots (if applicable)

<details><summary>1 screenshot of Android</summary>

![Screenshot_20220930-150500](https://user-images.githubusercontent.com/22780683/193276223-c07a4a1d-1280-4865-ac65-e04b6205c1b5.png)

</details>

<details><summary>3 screenshots of Nintendo Switch</summary>

![2022093014591700-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/22780683/193276665-c48ae794-236c-4db1-99dc-6014d78457ec.jpg)
![2022093014592000-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/22780683/193276667-12e591c3-7340-4152-bd38-c16ecf5c155c.jpg)
![2022093014585500-919080947E4F48ABDD3B8E0133C73FB5](https://user-images.githubusercontent.com/22780683/193276661-097801d2-1158-4419-a31e-c44dfbd270a9.jpg)

</details>

<details><summary>1 screenshot of Nintendo 3DS</summary>

![image](https://user-images.githubusercontent.com/22780683/193282157-0b6e2305-7c4e-450e-8508-1ec8c9c1d465.png)

</details>

More can be provided on request.

#### Additional information

Carried over from https://github.com/AdguardTeam/AdGuardHome/discussions/4949 due to a lack of attention there.

**Comment by DandelionSprout** [comment]
Okay, so the problem seems to have got fixed after I installed the KB5017389 Windows update. How exactly it fixed it? Who knows.

**Comment by vNa3006** [comment]
In my case, only direct IP works
DoH doesn't work on Windows 11 22h2 with KB5017389 installed.
