### ISSUE TITLE
Web UI HTTP/3 not working

### ISSUE THREAD

**Issue by Harvester57** [AdguardTeam/AdGuardHome#4986]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.17

#### What did you do?

Enabled HTTP/3 support for the web UI with `serve_http3` set to `true`, and checked with Google Chrome stable (v106) and canary (v108) with `Experimental QUIC support` set to `Enabled` in `chrome://flags` if it is working.

#### Expected result

Request should show `h3` in the Dev Tools > Network > Protocol column, but it is still showing `h2`

#### Actual result

Request showing the protocol used is `h2`

#### Screenshots (if applicable)

Not working
![H3](https://user-images.githubusercontent.com/7060295/193657560-9413a1e1-a21e-4d7f-bf24-e827a31e60e4.png)

Same web browser, when connecting to youtube.com
![image](https://user-images.githubusercontent.com/7060295/193657798-72cd1ad9-6cec-4459-aab4-fe545878d71e.png)

#### Additional information

HTTP/3 for upstream servers seems to be working fine, I was able to force the Google DNS with `h3://8.8.8.8/dns-query`

**Comment by flavorgold1** [comment]
I have `AdGuardHome` (edge) installed on `Ubuntu 22 LTS on docker` and on `Windows 11`.

Unless I cheat and run it thru `Caddy`, I can't seem to get it to be accessible via `HTTP/3`.

The good news is that I can clearly see that, on both `Windows 11` and `Ubuntu 22`, `AdGuardHome` is listening on `UDP` and `UDP6` on the `HTTPS` port (so, basically, QUIC is listening and waiting, I guess).

**Comment by ssrahul96** [comment]
same here, checked the `h3` status at https://geekflare.com/tools/http3-test as well, no `h3` available

**Comment by ssrahul96** [comment]
found the issue, [Alt-Svc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc) is not set in the header

**Comment by daryll-swer** [comment]
HTTP/2 is over TCP/443, HTTP/3 (QUIC) is over UDP/443.

But that would conflict with DoQ, right? Can we use UDP/443 for both the Web UI and DoQ?

**Comment by flavorgold1** [comment]
Are you confusing `DoH3` with `DoQ`?

Those are 2 different things, AFAIK.

`DoQ` goes by protocol form `quic://`.

`DoH3` goes by `https://` if you're not being specific and would like a fallback to `HTTP2` to be available.

If you don't want a fallback, `h3://` is what you'd go for, to require `DoH3`.

**Comment by Harvester57** [comment]
Working as expected with the Edge channel, thanks !

![image](https://user-images.githubusercontent.com/7060295/194955478-5d984211-b75c-42ca-8741-d53ebce6f775.png)

**Comment by Gandulf78** [comment]
Still not working for me with v0.108.0-b.19.
<img width="1079" alt="Capture d’écran 2022-10-19 à 22 38 49" src="https://user-images.githubusercontent.com/44120190/196799378-3c7bc713-092c-42cd-a656-e94758547b44.png">

**Comment by ssrahul96** [comment]
> Still not working for me with v0.108.0-b.19. Adguardhome is working on Docker and listening to UDP/443 and TCP/443. Anyway as I encounter issue #5052 too I revert back to v0.108.0-b.18.
> 
> <img alt="Capture d’écran 2022-10-19 à 22 38 49" width="1079" src="https://user-images.githubusercontent.com/44120190/196799378-3c7bc713-092c-42cd-a656-e94758547b44.png">

Could you check the headers?? And try to refresh it??

**Comment by ainar-g** [comment]
@Gandulf78, in some browsers, HTTP/3 is only enabled if the browser trusts the certificate.  So a self-signed cert would only work if you add it (and its root CA) to the browser's cert storage.

**Comment by Gandulf78** [comment]
> @Gandulf78, in some browsers, HTTP/3 is only enabled if the browser trusts the certificate.  So a self-signed cert would only work if you add it (and its root CA) to the browser's cert storage.

Ok, I will try again after trusting the certificate. Thanks.

**Comment by Gandulf78** [comment]
I tried again. I am not using self-signed cert.
<img width="904" alt="Capture d’écran 2022-10-20 à 22 19 35" src="https://user-images.githubusercontent.com/44120190/197049985-984c3edb-c318-48f4-838d-33e0c39128ae.png">
<img width="698" alt="Capture d’écran 2022-10-20 à 22 18 03" src="https://user-images.githubusercontent.com/44120190/197050186-bb1c7432-4074-4b22-b004-489957797ab5.png">

**Comment by Harvester57** [comment]
Did you enable the experimental QUIC support in Chrome flags ?

**Comment by daryll-swer** [comment]
@Harvester57 the “default” value for QUIC support in Chrome is equivalent with “enabled” in the past recent versions dating to almost two years. I myself see QUIC just [refuses to work with ADH](https://github.com/AdguardTeam/AdGuardHome/issues/5011#issuecomment-1279530186).

QUIC on Firefox/Chrome works fine for me on Google sites etc.

**Comment by ssrahul96** [comment]
@daryll-swer , did you set `serve_http3` to `true` in adguard config?

**Comment by Gandulf78** [comment]
> Did you enable the experimental QUIC support in Chrome flags ?

I tried (I thought it was not useful since http/3 is enabled by default). No change.

**Comment by daryll-swer** [comment]
@ssrahul96 enabled the flag in the config file since day 1, when the initial support was added and changelogs mentioned it as well.

**Comment by Gandulf78** [comment]
> did you set serve_http3 to true in adguard config?

I missed that. It is working after setting it.
