### ISSUE TITLE
Auto-update Fix - v0.107.15

### ISSUE THREAD

**Issue by privacy-advo** [AdguardTeam/AdGuardHome#4987]
### Installation

GitHub releases or script from README

### AdGuard Home version

v0.107.14

#### What did you do?
Auto-update
#### Expected result
Updated version
#### Actual result
"Auto-update failed. Please follow these steps to update manually."
#### Additional information
3 machines:
Raspberry Pi 3B+ (AGH: arm64)
2x Ubuntu 20.04.5 LTS (AGH: linux_amd64)

#### More people experiencing this?

**Comment by Harvester57** [comment]
Had the same error, followed the guide to update manually and it worked fine.

**Comment by TheCeet** [comment]
Same here

**Comment by ppfeufer** [comment]
It fails because of the bug (#4970) it's fixing.

**Comment by sausje** [comment]
Autoupdate broken ok, but why is manual SUCH a big hassle to do?? This needs to change for future manual updates if needed....

**Comment by ppfeufer** [comment]
What big hassle?

- Download the update
- Stop the service
- Make a backup
- Extract the downloaded archive into the right directory
- Restart the service

I mean, that's exactly how updates work ...

**Comment by sausje** [comment]
> What big hassle?
> 
>     * Download the update
> 
>     * Stop the service
> 
>     * Make a backup
> 
>     * Extract the downloaded archive into the right directory
> 
>     * Restart the service
> 
> 
> I mean, that's exactly how updates work ...

That's not how it says for Windows, look at all those commands for just a simple file replacement...

https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update-win

**Comment by privacy-advo** [comment]
> Autoupdate broken ok, but why is manual SUCH a big hassle to do?? Especially for a single executable... This needs to change for future manual updates if needed....

Well - if this is a hobby project and you're not stressed out by downtime, your doing well. 
But if **a lot** of people rely on your servers, it's a different ball game. Downtime of a few seconds vs. xx minutes.

**Comment by ppfeufer** [comment]
> > What big hassle?
> > ```
> > * Download the update
> > 
> > * Stop the service
> > 
> > * Make a backup
> > 
> > * Extract the downloaded archive into the right directory
> > 
> > * Restart the service
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I mean, that's exactly how updates work ...
> 
> That's not how it says for Windows, look at all those commands for just a simple file replacement...
> 
> https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update-win
> 
> Edit thought so, all those are bs and don't know why they give these instructions when simple shutdown of exe via taskmanager and replace all files is so much easier...

You only need the Powershell to stop and start the service. Download the update in your browser, and use your file explorer for all the rest, like extracting the archive, backing up the old installation and moving the new files into place ...

Downtime, max 1 minute.

**Comment by sausje** [comment]
> > > What big hassle?
> > > ```
> > > * Download the update
> > > 
> > > * Stop the service
> > > 
> > > * Make a backup
> > > 
> > > * Extract the downloaded archive into the right directory
> > > 
> > > * Restart the service
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I mean, that's exactly how updates work ...
> > 
> > 
> > That's not how it says for Windows, look at all those commands for just a simple file replacement...
> > https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update-win
> > Edit thought so, all those are bs and don't know why they give these instructions when simple shutdown of exe via taskmanager and replace all files is so much easier...
> 
> You only need the Powershell to stop and start the service. Download the update in your browser, and use your file explorer for all the rest, like extracting the archive, backing up the old installation and moving the new files into place ...
> 
> Downtime, max 1 minute.

That's not how it's worded there and you don't need even powershell to stop the service, can do that from taskmanager. Stop blindly defending shitty worded practices.

**Comment by ppfeufer** [comment]
> That's not how it's worded there and you don't need even powershell to stop the service, can do that from taskmanager. Stop blindly defending shitty worded practices.

Well, I guess you can do a better job and we'll see some contributions from you soon to improve this. I'm sure the dev team is happy about every help they can get ...

**Comment by sausje** [comment]
> > That's not how it's worded there and you don't need even powershell to stop the service, can do that from taskmanager. Stop blindly defending shitty worded practices.
> 
> Well, I guess you can do a better job and we'll see some contributions from you soon to improve this. I'm sure the dev team is happy about every help they can get ...

If I get paid sure, otherwise AdGuard home their parent company has $/€ enough to pay people to properly word shit like that.

**Comment by privacy-advo** [comment]
Oh boi.
@EugeneOne1

**Comment by ainar-g** [comment]
@sausje, please refrain from using inflammatory language like that, especially if it's off-topic to the issue at hand.  You can request documentation improvements by opening new issues instead.

**Comment by sausje** [comment]
> @sausje, please refrain from using inflammatory language like that, especially if it's off-topic to the issue at hand. You can request documentation improvements by opening new issues instead.

"inflammatory language"

What is this? The local snowflake community on git?
Just ban me then as I'm not gonna change who I am for a bunch of randoms thinking they live in a snowflake world. Especially towards Germans hahaha

**Comment by Jefffish09** [comment]
Hi @privacy-advo , I meet same error on openwrt. Is there only one way  (manual update) to solve this problem? Can I wait for the next version to auto-update? I am a newer to Linux.

**Comment by ppfeufer** [comment]
> @ainar-g How do I use the command if my pwd contains the symbol @. I tried ' and " with the pwd but couldn't get it to work. Do I have to change it first? thanks.

You can try `\@` or `\\@`

Bottom line, you have to escape the `@` in your PW, and I can never remember how many `\` that needs in an URL string or if that is even possible.

Another try would be something like this:
```shell
MY_PASSWORD="your_pw_here" curl -H 'Content-Type: application/json' -X POST -v 'http://LOGIN:${MY_PASSWORD}@127.0.0.1/control/update'
```
Pretty much stuffing your password into a variable (`MY_PASSWORD`) and using the variable in the command.

**Comment by Jefffish09** [comment]
> Hi @privacy-advo , I meet same error on openwrt. Is there only one way (manual update) to solve this problem? Can I wait for the next version to auto-update? I am a newer to Linux.

@privacy-advo I have seen your solution in latest update, thanks!

**Comment by speedingcheetah** [comment]
The Curl command not working for me. 
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to 127.0.0.1 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

**Comment by speedingcheetah** [comment]
Could not get curl command to work for me. Maybe cause password is complex with special characters (as it should be).  I tried the manual method officially posted and that new AGH executable failed to start.  I noticed a agh-backup folder and instead replaced the 0.107.14 executable with the backup (that was 0.107.13) and that started up fine, and its auto update worked fine to get to 0.107.15.

**Comment by fonic** [comment]
> Could not get curl command to work for me. Maybe cause password is complex with special characters (as it should be).

If the password is (too) complex, this command will do the trick:
`curl -H 'Content-Type: application/json' -X POST -v -u USER 'http://HOST:PORT/control/update`

Replace _USER_, _HOST_ and _PORT_ to match your setup, `curl` will ask for the password interactively.

It is also worth mentioning that the command can be run remotely, it is not restricted to the actual machine running _AdGuard Home_.

**Comment by cqjerry** [comment]
![image](https://user-images.githubusercontent.com/7488975/194734984-2c6f3619-46b9-4822-978d-49fe0dfec308.png)

I get this error message,how can i do fix it？
