### ISSUE TITLE
v0.92 - Error on startup "Syntax error: ";" unexpected"

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#499]
Updated from v0.91 to v0.92
On launch, I get an error "Syntax error: ";" unexpected"
Revert back to v0.91 and everything OK.

### Steps to reproduce
1. Copied contents of AdGuardHome_v0.92_linux_arm64.tar.gz over working v0.91 installation
2. Run AGH (sudo /mnt/d/Applications/AdGuardHome/AdGuardHome)
3. Enter SU password

### Expected behavior
AGH to launch

### Actual behavior
Error produced:
```
anthonyb@ANTNEWPC:~$ sudo /mnt/d/Applications/AdGuardHome/AdGuardHome
[sudo] password for anthonyb:
/mnt/d/Applications/AdGuardHome/AdGuardHome: 1: /mnt/d/Applications/AdGuardHome/AdGuardHome: Syntax error: ";" unexpected
```

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92
| How did you setup DNS configuration:| DHCP on Windows Server 2012 R2
| If it's a router or IoT, please write device model:| n/a
| Operating system and version:| Ubuntu 18.04.1 running under WSL on Windows 10 1809 (17763.195)

**Comment by ameshkov** [comment]
Make sure that you unpacked it properly, from the error it looks as if you have a text file by that path

**Comment by AnthonyBe** [comment]
Yep - rechecked. Same result.

Just confirming that the Adguardhome file has shrunk in size quite significantly since v0.91?
v0.91 - 21,785,088 bytes
v0.92 - 9,605,888 bytes

**Comment by ameshkov** [comment]
Yep, that's right, since we dropped CoreDNS the overall size is less now.

I've just re-checked it on my side and everything seems okay:
```
wget https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.92/AdGuardHome_v0.92_linux_amd64.tar.gz
tar xvfz AdGuardHome_v0.92_linux_amd64.tar.gz
cd AdGuardHome
./AdGuardHome
```

**Comment by AnthonyBe** [comment]
Cool. That was what I expected, but just wanted to validate.

I've just redownloaded, expanded into fresh directory (i.e. not upgrade v0.91), and I still get exact same result.

**Comment by ameshkov** [comment]
Try looking inside:
```
cat /mnt/d/Applications/AdGuardHome/AdGuardHome | more
```

It definitely does not think it's a binary file.

**Comment by ameshkov** [comment]
Btw have you tried the Windows binary already?

**Comment by AnthonyBe** [comment]
>           Btw have you tried the Windows binary already?

Yep, testing Windows binary on another box right now. Just logged first bug :)

**Comment by AnthonyBe** [comment]
Result of 
`cat /mnt/d/Applications/AdGuardHome/AdGuardHome | more`

looks normal:
![ubuntu_2018-12-31_11-17-38](https://user-images.githubusercontent.com/17214552/50552739-02309980-0cee-11e9-9cbf-5acd50660a26.jpg)

**Comment by AnthonyBe** [comment]
might be something to do with the fact I'm running this under WSL on Win10.

**Comment by hmage** [comment]
Make sure you're running the binary for correct architecture.

Please type this:
`uname -a`
and
`file /mnt/d/Applications/AdGuardHome/AdGuardHome`

the architectures must match.

**Comment by AnthonyBe** [comment]
ergh.. I checked, and double-checked.. and still got the ARM instead of the AMD version!!!

I know it is my fault entirely, but the filenames are so so similar.. maybe try and change the file naming convention to make them look a little less similar? The 'm' character I find makes them look almost identical even though it is in a different position. Then put an 'r' in front and you get 'rm' which looks just like an 'm' when skimming...

AdGuardHome_v0.92_linux_amd64.tar.gz
AdGuardHome_v0.92_linux_arm64.tar.gz

Anywho.. problem solved. Thanks!!
