### ISSUE TITLE
Adguard 4.0 nightly. 

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdGuardHome#4999]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv6

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v4.0 nightly 35 (79)   09–2022. AdGuard Software 

#### What did you do?
If the Adguard is working and active cannot updating applications from Google Play Store,  getting error messages Unable to update Gmail application Please try again and if it fails again, I will find out about common solutions to the problem. When i turn it off then upadating running good and stable - everyting is normal . 

#### Expected result
Expect - change filtering and or Adguard connection to Google Play Store.  

#### Actual result
Cannot updating applications from Google Play Store without turning off Adguard app

#### Screenshots (if applicable)
Screenshot . 
![Screenshot_20221004-112500_Google Play Store](https://user-images.githubusercontent.com/100161152/193891902-9656d442-5d5e-4fdb-b92b-7fe643849058.jpg)

#### Additional information.
Samsung Galaxy Note 10 Plus .Android 12 OneUI 4.1 
Google Play Store  32.5.14-21 [0] [PR] 476431188
Adguard 4.0 nightly 35 (79) 09-2022 . Updating timer  daily 1 hour

**Comment by ainar-g** [comment]
This is a repository for the AdGuard Home DNS server.  To get support for the AdGuard Android app, please consule [AdGuard For Android support page][1].

[1]: https://adguard.com/en/support/adguard_for_android.html
