### ISSUE TITLE
v0.92 | Windows 2012 R2 | Cannot connect to tls://1.1.1.1

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#500]
v0.92 Windows binary
AGH working fine, but UI is ONLY showing blocked traffic stats and data.

### Steps to reproduce
1. unpack and run v0.92 Windows binary

### Expected behavior
Main page UI and Query Log should show ALL DNS traffic

### Actual behavior
Main page UI and Query Log ONLY shownig filtered traffic

<details><summary>Screenshot:</summary>

![applicationframehost_2018-12-31_11-03-45](https://user-images.githubusercontent.com/17214552/50552659-27240d00-0cec-11e9-956f-ffc504b4edf3.jpg)
![agh092querylog](https://user-images.githubusercontent.com/17214552/50552691-add8ea00-0cec-11e9-9f5c-63ed68e329b5.jpg)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92
| How did you setup DNS configuration:| DHCP on Windows Server 2012 R2
| If it's a router or IoT, please write device model:| n/a
| Operating system and version:| Windows Server 2012 R2

**Comment by AnthonyBe** [comment]
Verbose console output here - https://pastebin.com/i8wWF1uD

Blocks are being performed by the AdGuard and hpHosts filters.

**Comment by AnthonyBe** [comment]
hmm... actually, my initial testing was flawed.
Now that I've set the SGH Windows box as ONLY DNS server nothing is working. The above verbose log seems to show that AGH is blocking as per filters, but all remaining good DNS requests are failing on upstream.

**Comment by ameshkov** [comment]
Yeah, for some reason it fails to establish an encrypted connection with Cloudflare:
https://github.com/AdguardTeam/dnsproxy/issues/2

**Comment by ameshkov** [comment]
I can't reproduce it on my Windows VM though, that's weird

**Comment by ameshkov** [comment]
What if you use some other upstreams?

For instance:
```
tls://one.one.one.one
tls://dns.adguard.com
```

**Comment by AnthonyBe** [comment]
Yep - they work!

**Comment by ameshkov** [comment]
I must say this is super-weird:) You're on `Windows Server 2012 R2` right?

**Comment by AnthonyBe** [comment]
Correct.

**Comment by ameshkov** [comment]
Got it, thank you! We'll try to reproduce it on this Windows version then. It might be a known golang bug, though.

**Comment by AnthonyBe** [comment]
Well, good thing is that we have a workaround that doesn't compromise performance, security, or capability!

**Comment by AnthonyBe** [comment]
Also confirming that
`tls://1dot1dot1dot1.cloudflare-dns.com`
works fine.

**Comment by hmage** [comment]
This is very likely because your ISP blocks packets to 1.1.1.1.

You can confirm this by running `ping 1.1.1.1`. You should be able getting ping replies but if your ISP blocks, you won't get any.

If that's the case, please contact your ISP to fix routing to 1.1.1.1.

You will also be unable to open https://1.1.1.1 in your browser as well, regardless of AdGuardHome running or not.

**Comment by AnthonyBe** [comment]
Nothing to do with ISP blocking.
I have another Windows box running AGH under WSL using tls://1.1.1.1:853 and tls://1.0.0.1:853 just fine.

**Comment by hmage** [comment]
Alright. My apologies for jumping to conclusions.

It really does seem like a bug that can be fixed.

**Comment by Eyeborgs** [comment]
У меня такая же проблема с Windows Server 2012 R2 но с Windows 10 такого нет..

**Comment by ameshkov** [comment]
This is a bug of golang and there's no easy way to fix it from our side. @admitrevskiy has filed it to golang repo: https://github.com/golang/go/issues/30985
