### ISSUE TITLE
Manual Update Instructions does not backup leases.db

### ISSUE THREAD

**Issue by webmihir** [AdguardTeam/AdGuardHome#5000]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

ARMv6

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.17

#### What did you do?

- I followed the instructions here to manually backup and update to the b.17 beta: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update 

#### Expected result
- Step 4 would backup my static IP leases

#### Actual result
- Step 4 only backs up the yaml config and stats data. leases.db is not backed up

#### Additional information
Please update the steps to add leases.db if that file exists

**Comment by ainar-g** [comment]
Thanks for reporting that!  We've added a mention of it to both Unix and Windows versions.
