### ISSUE TITLE
Documentation section on "Reset Web Password" has incorrect instructions for Fedora.

### ISSUE THREAD

**Issue by TheSiman** [AdguardTeam/AdGuardHome#5001]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Fedora repos don't have a package called apache2, in Fedora the apache is called httpd.
#### Proposed solution
Change "sudo dnf install apache2" -> "sudo dnf install httpd-tools"
#### Alternatives considered
Another option is "sudo dnf install httpd" which has httpd-tools as a dependency and would be closer to Ubuntu's/Debian's apache2 package, but that seems unnecessary as we don't need a full web server for this use case.

**Comment by ainar-g** [comment]
Thanks for the report!  We've replaced the package.
