### ISSUE TITLE
Update from version V0.107.14 to V0.107.15 not possible

### ISSUE THREAD

**Issue by lubertus4** [AdguardTeam/AdGuardHome#5006]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.14

### Description

I'll try to Update from Version V0.107.14 using the AutoUpdate mechanism to Version V0.107.15 on a Raspberry 3b running on hoops: https://www.youtube.com/watch?v=J3Zq5UHvSU4 

Autoupdate runs smoothly and I do not need to run manually Updates

Autoupdate not possible due to following reported Error:
"Auto-update not possible. Please follow these steps to update manually"
https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update

**Comment by angrynerd** [comment]
Duplicate, see #4987
