### ISSUE TITLE
With IPv6 enabled on the client it falls back on the public dns from my provider

### ISSUE THREAD

**Issue by unbekn0wn** [AdguardTeam/AdGuardHome#5007]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.15

#### What did you do?
I have setup AdGuard Home on my raspberry Pi 4 and put my DNS server on my windows PC to the IP of the Pi. With IPv6 disabled it will resolve DNS requests through AdGuard. However with IPv6 enabled it resolves through a different DNS and not AdGuard thus letting through ads.

I tried to add IPv6 addresses in the upstream DNS servers but they can't seem to get a connection.

#### Expected result
I expected that AdGuard would pick the IPv6 DNS requests up as well.

#### Actual result
Windows resolves the DNS request through an IPv6 DNS from my provider.

#### Screenshots (if applicable)
![dns](https://user-images.githubusercontent.com/10568521/194228710-55f75c2d-72a3-4616-a078-ad89decb505e.png)

**Comment by unbekn0wn** [comment]
IPv4:
![image](https://user-images.githubusercontent.com/10568521/194510007-608a9e4d-27dd-4402-b8fb-73c85c18ede8.png)

IPv6:
![image](https://user-images.githubusercontent.com/10568521/194509790-e85838a6-92cc-40d2-8f9d-f84cc20fa9c8.png)

That said, I decided to retry turning it on after reinstalling adguard on a docker-compose and it seems to work now. Not sure where the misconfiguration was. Everything seems to work properly now. As well as my Pi still can resolve the dns.

**Comment by ainar-g** [comment]
I see.  If the problem disappeared, I'll close this issue.

With that said, I do recommend that you put the AdGuard Home IP addresses to both *Preferred* and *Alternative DNS server* fields, because otherwise the OS can just switch between them at any moment.  (The alternative one is not a fallback, as some people think.)

**Comment by unbekn0wn** [comment]
Thanks for the info, that's exactly what I thought it was. I will change it in my config.
