### ISSUE TITLE
Ecosia search engine added to safe searching

### ISSUE THREAD

**Issue by JaapvanderVeen** [AdguardTeam/AdGuardHome#5009]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

I would like to see the Ecosia search engine added to the list of supported search engine's.

**Comment by ainar-g** [comment]
Last time I've checked, Ecosia didn't have dedicated safe search IP addresses.  Has that been changed?

**Comment by Mizzick** [comment]
Please have a look, we have implemented the requested changes.
The new build version `v0.108.0-a.947+b6ed7696` has been just published to the edge channel.

**Comment by Mizzick** [comment]
Feel free to reopen in case it doesn't work as expected.
