### ISSUE TITLE
Feature Req for Windows - Install as a Windows service

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#501]
Now that we have Windows binaries, it would be ideal if there was the capability to install and run as a native Windows service.

As an alternative, it would be good to have a recommended way to run as a service using 3rd party options or Task Scheduler.

Free options: http://runasservice.com (https://github.com/luisperezphd/RunAsService)
Paid for options:
https://www.firedaemon.com
https://www.coretechnologies.com/products/AlwaysUp

**Comment by ameshkov** [comment]
Duplicates #490
