### ISSUE TITLE
Local IPv6 binding does not longer work on FreeBSD 

### ISSUE THREAD

**Issue by Marvo2011** [AdguardTeam/AdGuardHome#5012]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.108.0-b.17

#### What did you do?
After an upgrade to the latest version IPv6 binding does not longer work.

#### Expected result
Bind to local IPv4 Address and local IPv6!

#### Actual result
```
2022/10/07 09:23:02.799636 49214#23 [debug] web: starting https server
2022/10/07 09:23:05.448623 49214#22 [debug] initialized filtering engine
2022/10/07 09:23:05.448787 49214#22 [info] Starting the DNS proxy server
2022/10/07 09:23:05.448832 49214#22 [info] Cache TTL override is enabled. Min=0, Max=3600
2022/10/07 09:23:05.448861 49214#22 [info] Ratelimit is enabled and set to 20 rps
2022/10/07 09:23:05.448890 49214#22 [info] The server is configured to refuse ANY requests
2022/10/07 09:23:05.448922 49214#22 [info] DNS cache is enabled
2022/10/07 09:23:05.448995 49214#22 [info] MaxGoroutines is set to 300
2022/10/07 09:23:05.449189 49214#22 [info] Creating the UDP server socket
2022/10/07 09:23:05.449389 49214#22 [info] Listening to udp://xxx.xxx.xxx.1:53
2022/10/07 09:23:05.449509 49214#22 [info] Creating the UDP server socket
2022/10/07 09:23:05.449797 49214#22 [debug] stats: flushing unit with id 462535 and total of 385
2022/10/07 09:23:05.458208 49214#22 [debug] stats: database closed
2022/10/07 09:23:05.458384 49214#22 [debug] querylog: there's nothing to write to a file
2022/10/07 09:23:05.458518 49214#22 [debug] all dns modules are closed
2022/10/07 09:23:05.458642 49214#22 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [fdxx:xxxx:xxxx:xxxx::1]:53: bind: can't assign requested address
```

#### Additional information
Runs on:
- OPNsense 21.7.7-amd64
- FreeBSD 12.1-RELEASE-p21-HBSD

**Comment by ainar-g** [comment]
Hello.  We haven't really changed anything related to FreeBSD, as far as I can recall.  Perhaps, the local IP has changed?

**Comment by Marvo2011** [comment]
Thanks, but the local IP has not changed. There is also no service listening on port 53. I will try to add a different IP and take a look if AdGuard can listen there.

**Comment by Marvo2011** [comment]
Strange after adding a new IPv6 address [fdxx:xxxx:xxxx:xxxx::2] it can listen to both... Seams for me a FreeBSD bug...
Thanks for me it's solved.
