### ISSUE TITLE
DHCP add lease workflow

### ISSUE THREAD

**Issue by euro2** [AdguardTeam/AdGuardHome#5016]
### Prerequisites

- [ ] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [ ] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Clunky overview of the DHCP leases with multiple pages to go through. (domotica IOT)
#### Proposed solution
A. button to list ALL leases without going though multiple pages. 
B. Ability to change hostname once one is set. Now i have to copy MAC/IP/NAME delete it, and re-set it.

#### Alternatives considered
X
#### Additional information
X

**Comment by ainar-g** [comment]
Merging into #1700.
