### ISSUE TITLE
Redirect to https 

### ISSUE THREAD

**Issue by rahulreddyln** [AdguardTeam/AdGuardHome#5018]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

107.16

**Comment by rahulreddyln** [comment]
OS : ubuntu 22.04

**Comment by fernvenue** [comment]
You can not redirect HTTP to HTTPS when 80 disabled, because user need to connect to the HTTP port first and get the redirect message from that port.
