### ISSUE TITLE
Filter modifier "$client" no longer accepts host names

### ISSUE THREAD

**Issue by Norde** [AdguardTeam/AdGuardHome#5019]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.16

### Description

Under AdGuardHome v106.3 I was using filtering rules applied according to the host name (with the modifier "client").

Exemple:
```
||*^$client='host.name'
@@||example.com^$client='host.name'
```

With the latest release (from v0.107.14 to 0.107.16), the "client" modifier does not recognize hostnames anymore (although IP's are still recognized).

My setup has not changed except for the version of AdguardHome (and OpenWRT).

**Comment by ainar-g** [comment]
Hello.  As far as I can tell, the `client` modifier has never worked this way.  It has only accepted IP addresses, CIDRs, and persistent client names.  Perhaps, your client was named `host.name` and then you've changed the name?

**Comment by overwatch3560** [comment]
is there still an issue @Norde
