### ISSUE TITLE
Cannot remove filters - Error: no such file or directory | 500

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#502]
### Steps to reproduce

1. Fresh install v0.92
2. Try to remove any of the default filters (except AdGuard Simplified)

### Expected behavior
It removes it

### Actual behavior
"Error: control/filtering/remove_url | Couldn't remove the filter file: remove /home/pi/AdGuardHome/data/filters/2.txt: no such file or directory | 500"

<details><summary>Screenshot:</summary>

<img width="1314" alt="adg" src="https://user-images.githubusercontent.com/46271764/50553267-b5ea5700-0cf7-11e9-9941-240f3f9b265c.png">
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92
| How did you setup DNS configuration:| Pi
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Up to date Raspbian

**Comment by hmage** [comment]
Hi!

This is definitely a bug, thanks for reporting!

**Comment by planet0** [comment]
No problem @hmage!

Is there a temp workaround to get those filters removed in the meantime (and just keep AdGuard Simplified)?

**Comment by planet0** [comment]
All good! Figured it out.

1. `sudo nano AdGuardHome/AdGuardHome.yaml`
2. Cut lines related to the other filters (go to line and Control + K)
3. Save (Control + X, 'Yes')
4. Restart AdGuard Home using `sudo systemctl stop adguard-home` and `sudo systemctl start adguard-home`
