### ISSUE TITLE
HTTPS DNS Record - H3 ALPN broken for DoH3 in Chromium browsers 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#5020]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.320+960a7a75

#### What did you do?

I added RFC standard HTTPS records to my DNS where my AGH resolver resides in an attempt to activate DoH3 and HTTP/3, and made sure my chrome flags had the DNS ALPN flags set to enabled.

#### Expected result

DNS queries work as normal.

#### Actual result

Browser starts kicking out "Not Resolved" errors relating to the DoH settings.

#### Additional information

Set an HTTPS record in your DNS with the same name as the A/AAAA records as your AGH hostname set to:

alpn="h3,h2"

Then, after browsing for a while, you should notice hostname not resolved errors showing up. I am testing this on Android but it may also occur on desktop Chromium browsers too.

**Comment by ainar-g** [comment]
Hello.  Can you provide the exact `dnsrewrite` rule that you've added?  Possibly with the anonymized hostname.

Also, are there any connection-related issues in the [verbose logs][1]?

Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Harvester57** [comment]
No, he wants to signal to browsers and compatible devices that the server supports HTTP/3 with an DNS HTTPS query. More infos here:

https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns/
https://kalfeher.com/https-records-simple/
