### ISSUE TITLE
AdGuard parental control web service is not working

### ISSUE THREAD

**Issue by knieselpriem** [AdguardTeam/AdGuardHome#5028]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.16

#### What did you do?
- enabled General Settings: Use AdGuard parental control web service

#### Expected result
- block adult websites with configured response code `REFUSED`

#### Actual result
- Status: `Blocked by Parental Control`
- Elapsed: `31 ms`
- Response code: `NOERROR`
- Rule(s): `parental CATEGORY_BLACKLISTED
Parental Control`
- Response: `A: 94.140.14.35 (ttl=741)`

#### Screenshots (if applicable)
n.a.

#### Additional information
- debug logs for domain "youporn.com" as an example: 
[adguard.log](https://github.com/AdguardTeam/AdGuardHome/files/9758973/adguard.log)
- config file: 
[adguard_conf.txt](https://github.com/AdguardTeam/AdGuardHome/files/9758999/adguard_conf.txt)

**Comment by ainar-g** [comment]
Sorry for a long time with no response.  That IP address, if you follow it, is the address of our block page.  You can use a different address by setting `filtering.parental_block_host` in the configuration file.
