### ISSUE TITLE
[Storage Driver: zfs] Can't pull Docker image

### ISSUE THREAD

**Issue by Jip-Hop** [AdguardTeam/AdGuardHome#5037]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.16

#### What did you do?

`docker pull adguard/adguardhome:v0.107.16`
`docker pull adguard/adguardhome:v0.108.0-b.18`

#### Expected result

Docker would successfully pull the image.

#### Actual result

Docker hangs indefinitely.

#### Additional information

Docker version 20.10.12, build e91ed57
TrueNAS-SCALE-22.02.4 (Debian 11)

#### Logging

```txt
docker image pull adguard/adguardhome
Using default tag: latest
latest: Pulling from adguard/adguardhome
213ec9aee27d: Pull complete 
31f9e8542749: Pull complete 
35797e6c4bae: Pull complete 
3c40b1afc955: Extracting [==================================================>]  11.72MB/11.72MB
4f4fb700ef54: Download complete 

HANGS INDEFINITELY
```

Pulling the alpine base image works:
```txt
root@nas[/mnt/data/debeer.it/shares/jip/sync]# docker run -it alpine:3.16 /bin/sh
Unable to find image 'alpine:3.16' locally
3.16: Pulling from library/alpine
Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
Status: Downloaded newer image for alpine:3.16
/ # 
```

An unofficial AdguardHome image works:
```txt
docker run -it ksey/adguardhome /bin/sh 
Unable to find image 'ksey/adguardhome:latest' locally
latest: Pulling from ksey/adguardhome
cf92e523b49e: Pull complete 
9df9f1260781: Pull complete 
Digest: sha256:014ea860f63a375911c5b481654e5dde9904f8167b9ee43b8f8cd4fb14664df4
Status: Downloaded newer image for ksey/adguardhome:latest
2022/10/15 11:35:52 [error] unknown option /bin/sh
Usage:

/opt/AdGuardHome/AdGuardHome [options]
```

Docker info:
```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: dev
 Storage Driver: zfs
  Zpool: data
  Zpool Health: ONLINE
  Parent Dataset: data/_docker2
  Space Used By Parent: 103358464
  Space Available: 5016750365136
  Parent Quota: no
  Compression: zstd
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
 Kernel Version: 5.10.142+truenas
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 62.56GiB
 Name: nas
```

I tried `ls -laR /mnt/data/_docker2`, but this hangs indefinitely at `./zfs/graph/3039b7f148ebcb01b77be166b0546f7de7b86371364dc82dbd8782c`. See [dockerls.txt](https://github.com/AdguardTeam/AdGuardHome/files/9791969/dockerls.txt).

The image does work with overlay2 storage driver (ext4) on ZFS zvol.

Docker info:
```txt
Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
```

```txt
docker run -it adguard/adguardhome /bin/sh
Unable to find image 'adguard/adguardhome:latest' locally
latest: Pulling from adguard/adguardhome
213ec9aee27d: Pull complete 
31f9e8542749: Pull complete 
35797e6c4bae: Pull complete 
3c40b1afc955: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:d6c7532726d132d44cc006a9b25f810225554264a905870fc9dbeb71e7405471
Status: Downloaded newer image for adguard/adguardhome:latest
2022/10/15 11:44:07 [error] unknown option /bin/sh
Usage:

/opt/adguardhome/AdGuardHome [options]
```

**Comment by agneevX** [comment]
Does this happen for all images or just this one? Either way, this issue does not concern AdGuard Home.

**Comment by Jip-Hop** [comment]
I have not tried all AdGuard Home images, but it happend for all the official AdGuard Home images I tried. All other images I use from Docker Hub don't have this issue. So it seems to be an issue between AdGuard Home, Docker and ZFS.

**Comment by Jip-Hop** [comment]
Since it doesn't happen with the base image on which AdGuard Home is buit it seems to be introduced / triggered by the layers AdGuard Home put on top.

**Comment by Jip-Hop** [comment]
I tried today with Ubuntu 22.04 LTS with ZFS root and the latest docker and I was able to pull the latest AdGuard Home image just fine. So seems like this issue has been fixed in a more recent Docker version.
