### ISSUE TITLE
Custom filters doesnt work anymore

### ISSUE THREAD

**Issue by Saku241** [AdguardTeam/AdGuardHome#5039]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.352+aaaa56fc

#### What did you do?
First, all my custom filters were removed for an unknown reason, so I decided to put them back and they dont work as it should
I put for exemple this filter : 
`@@/*.videoplaza.tv^/$important` and it should allow every *.videoplaza.tv domain but exemple.videoplaza.tv is still blocked
So I tried 
`@@||videoplaza.tv^$important` and have the same behaviour... nothing is allow
BUT, Only if I put this : 
`@@||exemple.videoplaza.tv^$important` there it starts to allow only this subdomain...

EDIT : I removed the "important" flag and it works as normal...
EDIT2: Adding a comment after the line broke it like : `@@||something.tv^$important` works but `@@||something.tv^$important #This is for something` doesnt work

**Comment by ainar-g** [comment]
Your regular expression contains several mistakes:

 *  `^` means the start of the line within regexps;
 *  a wildcard in regexps is spelled `.*`;
 *  literal dots must be escaped: `\.`.
 
The correct regexp rule is: `@@/.*\.videoplaza\.tv/`.  It works for me without the need for `important`.

Comments should be on their own line.  That is [documented](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#comments-1), albeit somewhat indirectly:

 >  Any **line** that **starts** with an exclamation mark is a comment.  \[…\]
 
I could not reproduce the rest of it.  If you're sure that there is an issue, please provide both a valid rule that blocks `videoplaza.tv` and a valid rule that should unblock `exemple.videoplaza.tv` but doesn't.  Thanks.
