### ISSUE TITLE
AdGuard parental control web service not fully functional

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#504]
### Steps to reproduce

1. Enable 'AdGuard parental control web service'
2. Visit pornhub.com

### Expected behavior
Website is blocked

### Actual behavior
Website half loads, can be bypassed

<details><summary>Screenshot:</summary>

<img width="1020" alt="pron" src="https://user-images.githubusercontent.com/46271764/50553758-116d1280-0d01-11e9-9db9-802f48f96afe.png">

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92
| How did you setup DNS configuration:| Pi/Router
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Up to Date Raspbian

**Comment by ameshkov** [comment]
Could it be Chrome's DNS cache messing things up?

**Comment by planet0** [comment]
> Could it be Chrome's DNS cache messing things up?

I disabled QUIC, that's made a difference - it does go to a blocking page now 👍
