### ISSUE TITLE
[solved] Enable browsing/parental control make my internet stop working "Was a port issue"

### ISSUE THREAD

**Issue by laggis** [AdguardTeam/AdGuardHome#5053]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.16

#### What did you do?

Nothing it just stop working didt know why so i try to reinstall adguard home and everything working but enable browsing/parental control just make my internet stop working. On a fresh install of adguard home.

#### Expected result

Have browsing/parental control on without having my internet shut down

#### Actual result

Just make all my device stop working.

#### Screenshots (if applicable)

![adguard](https://user-images.githubusercontent.com/18127838/196848100-f05abe3e-c460-4f9d-a89d-59f3160e7f07.png)
![console](https://user-images.githubusercontent.com/18127838/196848102-daae6ca2-8fe6-4da3-bc01-81a63f2c3b9a.png)

#### Additional information

I have try reinstall the adguard. Not sure what more i can do no errors in the console.

Update everything its working fine if a uncheck browsing/parental control

**Comment by laggis** [comment]
It was a port error sorry for the problem.

**Comment by laggis** [comment]
It was a port error sorry for the problem.

**Comment by slayermaster** [comment]
> It was a port error sorry for the problem.

can you explain this? I'm having the same problem.

**Comment by laggis** [comment]
> > It was a port error sorry for the problem.
> 
> can you explain this? I'm having the same problem.

Sorry didt see you type here if you still have the problem is that i forgot to open some ports.

53 TCP/UDP

67 UDP

853 TPC 

784 UDP 

8853 UDP
