### ISSUE TITLE
first choose dnssec catch

### ISSUE THREAD

**Issue by Bitcion** [AdguardTeam/AdGuardHome#5054]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

I use some dns on adh，some support dnssec，but not fast。some don't support dnssec
 hope parallel requests can first save/use dnssec record

**Comment by ainar-g** [comment]
Hello.  Unfortunately, I do not understand the feature request.  Can you please elaborate, in any language you're comfortable with?
