### ISSUE TITLE
auto-update Blacklists DNS

### ISSUE THREAD

**Issue by m1nuzz** [AdguardTeam/AdGuardHome#5056]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

make the function automatic updating DNS blacklists on "server/application" startup. Which could be toggled on and off

**Comment by ainar-g** [comment]
Duplicate of #4845
