### ISSUE TITLE
application always on

### ISSUE THREAD

**Issue by eduaddad** [AdguardTeam/AdGuardHome#506]
is there any way to leave the application always on or force on startup in Windows?

**Comment by OMICRON3069** [comment]
There is some trick to start program as services in Windows.
[NSSM - the Non-Sucking Service Manager](http://nssm.cc/)
or
[SvcGuest](https://github.com/Jamesits/SvcGuest)

**Comment by ameshkov** [comment]
This will be easy to solve when #490 is ready
