### ISSUE TITLE
Creating custom rules using ipv6 suffix syntax is not supported

### ISSUE THREAD

**Issue by michaelchen644** [AdguardTeam/AdGuardHome#5061]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Creating custom rules using ipv6 suffix matching syntax is not supported. Looking to add that feature, or does anyone have any other suggestions for me?
![2022-10-21 174243](https://user-images.githubusercontent.com/66155014/197167693-20c75777-2461-4234-a1ac-86df1d25b067.png)

**Comment by ainar-g** [comment]
Hello.  What exactly are you trying to achieve?  IPv6 CIDRs (e.g. `2001:db8:a::/64`) are supported, and I'm not sure what the syntax you've used is supposed to mean.

**Comment by michaelchen644** [comment]
> Hello. What exactly are you trying to achieve? IPv6 CIDRs (e.g. `2001:db8:a::/64`) are supported, and I'm not sure what the syntax you've used is supposed to mean.

In fact my prefix changes every 12 hours and I use SLAAC for device address configuration. In order to avoid manually editing the custom rules many times, I had to find a way to configure the rules using the 64-bit suffix of this device.

**Comment by michaelchen644** [comment]
> I see, thanks. If the device supports encrypted protocols (such as DNS-over-HTTPS, etc.), wouldn't it be easier to assign it an [AdGuard Home ClientID](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid) and use the client's name in the rules?

Tks.But Unfortunately my device doesn't support DoT and DoH, and I can't even use ssh to control it.Now I added an ipv6 record in the client configuration, and used the sh script to update the ipv6 address in AdguardHome.yaml regularly. I think this will solve it.

**Comment by michaelchen644** [comment]
Finally, I solved the problem by doing suffix matching via ::xxxx:xxxx/0.
![2022-11-01 101032](https://user-images.githubusercontent.com/66155014/199143691-834298af-b94a-42b5-a2e8-a9c57ca3188c.jpg)
