### ISSUE TITLE
False positive on poki.com

### ISSUE THREAD

**Issue by erew70** [AdguardTeam/AdGuardHome#5063]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.16

#### What did you do?

Tried playing Subway Surfers on Poki

#### Expected result

Game loads, and I can play without ads

#### Actual result

The game doesn't load and it is blocked.

#### Screenshots (if applicable)

https://photos.app.goo.gl/btd2Y8V5qYMZzFPt5

#### Additional information

I am using the latest release of Raspbian OS Desktop.

I checked if the poki game is blocked by searching for the domain/ip in my hosts files but it isn't in the list at all

**Comment by DandelionSprout** [comment]
I know this is probably very late, but https://github.com/AdguardTeam/AdGuardSDNSFilter seem to be the ideal place to report broken pages like these.
