### ISSUE TITLE
HTTPS Filtering without a domain

### ISSUE THREAD

**Issue by githubissocool** [AdguardTeam/AdGuardHome#5065]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

HTTPS filtering without requiring a domain

#### Proposed solution

Idk

#### Alternatives considered

idk

#### Additional information

I am a teenager and I cannot pay for a domain just for https filtering. I want to filter https without buying a domain which I cannot do

**Comment by agneevX** [comment]
Use a free DDNS service like DuckDNS??

**Comment by Karmylr** [comment]
AGH can only reject domains.

**Comment by CDzungx** [comment]
DuckDNS + Certbot. Working well.
![image](https://user-images.githubusercontent.com/59353870/198828926-fce5b8b3-876d-40b3-9e32-effa224fcac9.png)

**Comment by Birbber** [comment]
Closing as completed. Please re-open if needed.
