### ISSUE TITLE
[Feature request] Clear DNS cache when network changes

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdGuardHome#5068]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Whenever network connection changes, eg. like reconnecting to wifi, connecting to hotspot, connecting to vpn, etc. Adguard Home should detect it and clear DNS cache automatically.

**Comment by agneevX** [comment]
Please fill the issue template as your feature request does not make much sense.
