### ISSUE TITLE
Import wg.conf info into the persistent clients info

### ISSUE THREAD

**Issue by DanielLester83** [AdguardTeam/AdGuardHome#5073]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Easy Integration and Remote Management

#### Proposed solution
Scan each peer in every wg.conf file and automatically add the ip/cidr info for each peer as a persistent client.

#### Additional information
It would be nice to eventually be able to directly manage all aspects of wireguard (creation, private/public key generation, qr code/configuration file generation, deletion) through Adguardhome as a single server.

**Comment by ainar-g** [comment]
Hello and apologies for the late response.

I'll be honest, this is outside of the scope of AdGuard Home, especially with regards to the full Wireguard configuration management.  As for the `wg.conf` import, the AdGuard Home configuration file format is relatively stable, and whenever we change it, there is a migration, so it shouldn't be too hard to create a script to do just that.  If anyone wants to publish such script, we'll be happy to mention that in the README.
