### ISSUE TITLE
Add Auto-Refresh option to query log page

### ISSUE THREAD

**Issue by Lagicrus** [AdguardTeam/AdGuardHome#5080]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Adds auto-refreshing logs when you as the user want to monitor traffic without having to spam the refresh button to do so every say 5 seconds
#### Proposed solution
Adding a button that enabled auto-refreshing every X seconds
#### Additional information
Being able to possibly configure the delay for auto refresh

**Comment by fernvenue** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/3612.
