### ISSUE TITLE
documentation: AdGuardHome wont start on FreeBSD with 'adguardhome -s start', must use 'adguardhome -s run'

### ISSUE THREAD

**Issue by triantos** [AdguardTeam/AdGuardHome#5081]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

AdGuard Home, version v0.108.0-b.19

#### What did you do?
I had to manually update (the auto-update failed and said to manually update). Docs say to use 'AdGuardHome -s start' but on my system, at least, the correct command is 'AdGuardHome -s run'

#### Expected result
I expcted 'AdGuardHome -s start' to start the service

#### Actual result
root@opnsense:/usr/local/AdGuardHome # ./AdGuardHome -s start
2022/10/30 14:29:41 [info] AdGuard Home, version v0.107.16
2022/10/30 14:29:41 [info] service: control action: start
2022/10/30 14:29:41 [fatal] service: executing action "start": Failed to start AdGuard Home service: exit status 1

Note that even with verbose logging, nothing is written to the log file.

#### Additional information
From looking in /etc/rc.d/adguardhome, I see that the correct syntax on FreeBSD is to run with '-s run'

**Comment by ainar-g** [comment]
Hello and apologies for the late response.  Is the issue still occurring with the latest release?

 >  I expcted 'AdGuardHome -s start' to start the service

The `start` action starts AdGuard Home as a service.  It requires that you first install it as a service using the `install` action.  If you want to run it in the current terminal, `run` is the correct action.
