### ISSUE TITLE
自启与日志

### ISSUE THREAD

**Issue by 201259461** [AdguardTeam/AdGuardHome#5082]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

开机没有自启动功能，查询日志不显示具体请求、响应信息，日志抓取不完善。

**Comment by fernvenue** [comment]
For automatically start on boot, just add AdGuardHome to the system services, use `-s install` as [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#official-releases) said. And you can use `-v` or `--verbose` to enable verbose log, that will give you more information.

By the way, make sure you really checked wiki and discussions, searched other issues, and I think you really need to describe your problem specifically and tell other people some details such as your system and how you install the AdGuardHome. Ask questions like that is just wasting everyone's time, including yourself.

Maybe we can close this issue for now.

**Comment by Birbber** [comment]
Closing due to the lack of information. If it's still relevant please open a new issue describing your problem in details.
