### ISSUE TITLE
Make adguard home services priority

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#5084]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
You recently added iCloud Private Relay to the blockable services section however I also have a blocklist that blocks DoH domains however it does not block it using NXDOMAIN which is required. Since adguard home services arent the priority the blocklist is applied before the service.
#### Proposed solution
add ^important

**Comment by devipasigner** [comment]
I have a question. When I block apple private relay by putting the rules in custom filtering rules the response code in the query log is NXDOMAIN. However when using the option in the new blocked services its repsonse is NOERROR. Is this expected?

**Comment by ainar-g** [comment]
@Dynasty-Dev, sorry for the late response.  Can you provide an example of a rule that is triggered instead of the `$dnsrewrite` in the blocked services rules?
