### ISSUE TITLE
Unable to resolve domain when AdGuard browsing security web service is not available

### ISSUE THREAD

**Issue by ajin** [AdguardTeam/AdGuardHome#5085]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

v0.107.16

### Description

It appears that AdGuardHome (DNS server) is not responding if the "AdGuard browsing security web service" is enabled and the security web service is not reachable. 

The following entry is seen in the logs. 

`2022-10-31T22:45:14+01:00 adguard-home.adguard-home[7953]: 2022/10/31 22:45:14.067994 7953#670 [debug] https://family.adguard-dns.com:443/dns-query: response: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDY4ZDcEZTA2ZQQwZmEyAnNiA2RucwdhZGd1YXJkA2NvbQAAEAAB": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: connect: connection refused", "dial tcp 94.140.15.16:443: connect: connection refused", "dial tcp [2a10:50c0::bad1:ff]:443: connect: network is unreachable", "dial tcp [2a10:50c0::bad2:ff]:443: connect: network is unreachable"`

Workaround is to temporary disable the "AdGuard browsing security web service" in the General settings option.

**Comment by zilexa** [comment]
I can confirm this! And plenty of others on Tweakers forum as well.

**Comment by q54528** [comment]
My AGH setting is good , but I can't visit "https" websites
