### ISSUE TITLE
Can I use openvpn with adguard home?

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdGuardHome#509]
I followed the instruction on wiki and managed to setup adguard home on my vps. That not enough I want to use it with my openvpn (using pivpn) is it possible?

**Comment by ameshkov** [comment]
Check it out here:
https://github.com/pivpn/pivpn/issues/66#issuecomment-256740509

**Comment by Lmarto2** [comment]
I have the same problem, I have my pfsnese with adguardhome configured, but I can't use openvpn, the client doesn't connect, it gives a tls error, how to solve it?
