### ISSUE TITLE
validating certificate pair: certificate has no IP addresses, this may cause issues with DNS-over-TLS clients

### ISSUE THREAD

**Issue by qurislee** [AdguardTeam/AdGuardHome#5094]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

v0.107.17

### Description

May I ask how to solve it?
![Screenshot 2022-11-04 022131](https://user-images.githubusercontent.com/6596534/199804014-8b1541f6-610a-4a9e-ac0c-90ca58a39173.png)

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/4927#issuecomment-1302492786

You can safely ignore this warning.
