### ISSUE TITLE
Add 6 hours statistics retention

### ISSUE THREAD

**Issue by devipasigner** [AdguardTeam/AdGuardHome#5106]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
In the AdGuard Home settings you can set query log retention to 6 hours but the lowest setting for statistics in only 24 hours.
#### Proposed solution
Add a 6 and 12 hour option

**Comment by whyisthisbroken** [comment]
![image](https://user-images.githubusercontent.com/96284773/201384506-292055ba-e433-460b-b330-fd988b4978ea.png)

dont see any problem here ...

**Comment by ainar-g** [comment]
Merging into #3404.
