### ISSUE TITLE
IPv6 Clients No Longer Appearing in Dashboard

### ISSUE THREAD

**Issue by arubamon** [AdguardTeam/AdGuardHome#5110]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.17

#### What did you do?

For the last year and a half since I first installed AdGuard Home, IPv6, as well as IPv4, clients were appearing in my dashboard.  As of a few days ago, only IPv4 clients are being recognized.  I do not believe I have changed anything in my home network that would cause this issue.  I had been running the latest edge build of AdGuard Home, however, a day or two ago I uninstalled the edge build and installed the latest stable release, v0.107.17 to see if it may be an issue with a recent build.  This issue still persists after installing the most recent stable release

I have native IPv6 from my ISP and have verified that I can still ping and access IPv6 addresses and that I still have IPv6 connectivity on both my Windows 10 (x64) machine hosting AdGuard Home as well as my client devices connected to my hosting machine

IPv6 traffic is still being filtered through AdGuard Home but IPv6 clients are no longer appearing in my dashboard

I have not modified any settings in AdGuard Home immediately prior to this issue occurring

#### Expected result

Both IPv6, as well as IPv4, clients should appear in my dashboard

#### Actual result

Only IPv4 clients now appear in my dashboard

#### Screenshots (if applicable)

![Screenshot on 2022-11-06 at 10 30 53](https://user-images.githubusercontent.com/71743798/200188770-70d0b1be-39ce-477e-bcf4-1ceb2e1bd663.png)
![Screenshot on 2022-11-06 at 10 31 12](https://user-images.githubusercontent.com/71743798/200188814-96f7e4ab-7264-4689-b2f4-1ec4249574a5.png)
![Screenshot on 2022-11-06 at 10 31 27](https://user-images.githubusercontent.com/71743798/200188841-c5a6ddf1-4c3c-421a-81ca-a545f80073a5.png)
![Screenshot on 2022-11-06 at 10 31 43](https://user-images.githubusercontent.com/71743798/206941131-f30bd869-7437-4626-a6ae-af0dd7a4f497.png)
![Screenshot on 2022-11-06 at 10 31 51](https://user-images.githubusercontent.com/71743798/200188884-af842c51-2b79-4e1a-a529-b63f7279a9cb.png)
![Screenshot on 2022-11-06 at 10 32 23](https://user-images.githubusercontent.com/71743798/200189031-7de34cfb-b847-4510-a8bc-bff7da2c3df2.png)
![Screenshot on 2022-11-06 at 10 33 00](https://user-images.githubusercontent.com/71743798/200189054-3fe67ed0-f2fe-40a7-8e18-288a8d611fd3.png)

#### Additional information

Screenshots attached, which may help me resolve this issue

**Comment by arubamon** [comment]
This issue is still present after upgrading to AdGuard Home v0.107.18, the latest stable release

**Comment by arubamon** [comment]
This issue still persists on the lastest edge build, v0.108.0-a.393.  Any ideas?  Thanks again

**Comment by arubamon** [comment]
I am now on the latest **edge** build, **v0.108.0-a.416**.  Can anyone help me figure out why my **IPv6 clients** are no longer showing up in my AdGuard Home dashboard?  Thank you again

**Comment by arubamon** [comment]
Does no one have a solution for this issue, which i submitted almost four months ago?  Thank you again

**Comment by ainar-g** [comment]
Apologies for this issue not getting attention.  What are the values in the `dns.bind_hosts` array in your `AdGuardHome.yaml`?  Are there any IPv6 addresses?  Does it start working if you add them?  (Make sure to stop AdGuard Home before editing the file to prevent AGH from overwriting it.)

**Comment by arubamon** [comment]
Thank you, @ainar-g, for getting back with me after all these months.  As this was my first post here, I wasn't sure if maybe I wasn't doing something correctly

It seems my IPv6 clients have not been showing up in my AdGuard Home dashboard for the last four months or so basically because I'm an idiot, which I will explain below.  As I have been using computers since around around 1992 when my parents got our first one, which was a 486DX2-66 running Windows 3.1, I should be more familiar with what is essentially basic networking knowledge, however, it appears I need to ask for assistance

To reiterate, I am hosting my AdGuard Home DNS server locally from my PC running Windows 10 (x64).  I have native IPv6 from my ISP and have verified that I can still ping and access IPv6 addresses and that I still have IPv6 connectivity on both my Windows 10 hosting machine as well as my client devices connected to this hosting machine

I may not have configured my DNS server correctly after moving and using a new ISP, modem, and router, so essentially a new network, last September, but until about six weeks or so later, around the beginning of November, my IPv6, as well as my IPv4, clients were appearing in my AdGuard Home dashboard.  Since then, only IPv4 clients have been showing up.  It appears I have just now, after reading your reply, figured out why

Obviously, a device's local IPv4 addresses do not change when set statically, however, IPv6 addresses have at least one temporary IP address per device which does change, which is part of the networking basics I mentioned that I should not have to get clarification on.  I had the DNS servers in Windows machine, on my TV, and on my Android phone using the IPv4 and IPv6 addresses of both my Windows machine's wired and wireless connections, and I was able to see both IPv4 and IPv6 clients for all my devices.  It appears now, however, after reading your reply, that my IPv6 addresses for my Windows machine., which is hosting my DNS server, have all changed

For the past month or so, I have only been using my wired connection on my hosting machine, so even though I did not remove the IPv6 address for my wireless connection from the secondary DNS server for any of my clients, including on my Windows machine, I have not been seeing any IPv6 clients because the IPv6 addresses of my hosting machine's wired connection have changed

My questions now are as follows:
1. On the attached screen, why is there an IPv6 address on the sixth line and also on the ninth line, in addition to the temporary IPv6 address on the tenth line down under my wired connection 'Ethernet adapter Ethernet'?
2. Which IPv6 address(es) should I be using for my IPv6 DNS address(es) on my client machines?
3. Should I also be using the above IPv6 address(es) for my IPv6 DNS address(es) on my Windows machine, which is hosting my DNS server, since it is also a client?  It seems I should, as everything was working until my IPv6 addresses changed

As Android 12.1, or any Android version, I believe, does not have the built-in capability to modify your IPv6 DNS addresses, I am using a DNS changer, as well as also routing my traffic through a local HTTP proxy in AdGuard for Android on my rooted device.  Until the beginning of November, this device also showed up as an IPv6 client in my dashboard

I just changed the IPv6 DNS address on my Windows hosting machine as well as in my DNS changer app on my Android device to the DNS server of my Windows machine located on the sixth line in the attached screen from my ipconfig /all command.  My Windows machine now shows up as an IPv6 client, however, my Android device, which is the only other device I'm using at the moment, still does not.  This device does not appear as a IPv6 client for me when I either use my DNS changer or when routing my traffic through a local HTTP proxy in AdGuard for Android in addition to using my DNS changer app.  I did, at one time, try running the below script, which I modified slightly, on my device, but I can't quite remember the outcome:

#!/system/bin/sh
# Enable IPv6
echo 1 > /proc/sys/net/ipv6/conf/wlan0/accept_ra
echo 1 > /proc/sys/net/ipv6/conf/wlan1/accept_ra
echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6

I'm not sure what the best way to achieve this is, which hopefully you do.  It appears the DNS changer app I have been using, though, is doing exactly what it should be, at least when I the server(s) configured correctly

And to finally answer your question, I went through several backups of my AdGuardHome.yaml file I have from the middle of September until now, and every single one, including the ones when everything worked as expected, show:

dns:
  bind_hosts:
    - 0.0.0.0

I know I made this much more complicated that it needed to be, but I hope you were able to follow along and that the extra information was helpful.  Thank you again for your assistance


![Screenshot on 2023-02-27 at 05 57 45 (redacted)](https://user-images.githubusercontent.com/71743798/221597540-ab7fa630-cb51-4c26-ad2b-a30e96c4ad14.png)

**Comment by arubamon** [comment]
Thank you for getting back to me almost immediately.  The main, well, I guess, only reason I'm having to use a DNS changer on my Android device, is because the gateway (modem + router) provided by my current ISP has several router settings which are not configurable, namely changing the DNSv6 addresses.  I am able to configure my IPv4 and IPv6 address ranges by modifying my DHCPv4 and DHCPv6 beginning and ending addresses, but I don't know enough about IPv6 addresses to modify those.  I also have two options for LAN IPv6 Address Assignment, Stateless (Auto-Config) and Stateful (Use DHCP Server), however, the SLAAC option is grayed out, which may or may not have anything to do with my other router settings.  I briefly skimmed over the below page for additional info regarding these two options:

https://networkengineering.stackexchange.com/questions/47829/dhcpv6-stateful-vs-stateless-what-is-difference-between-it

I am also able to also modify both my Link-Local Gateway Address and my Global Gateway Address, however, I cannot change my DNS servers, either DNSv4 or DNSv6.  Setting all my devices static with the IPv4 address of my Windows machine hosting my AdGuard Home DNS server as each client's DNS server is beneficial, of course, only if I did not also have IPv6 enabled.  So without changing my DNSv6 address on my Android device, by either using a DNS changer or some other method, that traffic is not routed through my DNS server, which, of course, is what I want.  There is at least one other device currently on my network, my cable box from the same company, which I cannot modify the DNS addresses on at all, either IPv4 or IPv6, so I obviously cannot block any traffic on this device, since I cannot change the DNS addresses on my gateway

It looks like it was helpful that I changed the DNSv6 address for both my Windows machine and Android device from the IPv6 address of my Windows machine on the sixth line to the one of the ninth line, since the one on the sixth line just changed.  This one, however, does not say 'Temporary' like the one on the tenth line, so I still am not sure why there are three DNS addresses for my wired network adapter and why one of the two that does not say 'Temporary' is changing

Hopefully this additional information clarified things and I didn't make it more confusing, since I have a habit of overexplaining and confusing others, and occasionally myself.  :}  If so, are you now able to answer my three previous questions as well as determine what may be the cause of my Android device still not appearing as an IPv6 client in my AdGuard Home dashboard?

Again, thank you for your prompt reply, @ainar-g

**Comment by ainar-g** [comment]
By the sound of it, it seems like DHCPv6 is enabled in the router, and if so, there is probably a way to set a static IPv6 address lease to the Windows machine the same way you've set it a static IPv4 one.  And if there is, you should set it a static IPv6 address lease and use the address from it.

If not, another way to try would be DynDNS.  Assuming that your router supports that, and that the devices can use hostnames as DNS addresses, using the router as the bootstrap server, the router would respond to `AAAA` queries with the currently leased IPv6 address.  In theory.

**Comment by arubamon** [comment]
@ainar-g, thank you again for getting back with me.  If this were a router I purchased, I wouldn't have a problem being able to modify my DNSv6 addresses, either in the router settings of the official firmware or a custom one, such as DD-WRT.  However, I am using a gateway (modem + router) that I rent from my ISP, which has limited configurable settings.  I am attaching a screen of the local IP Config settings, which shows the options I mentioned earlier.  All redacted settings can be modified other than the first four groups of hexadecimal digits of the DHCPv6 Beginning and Ending Addresses

After setting the DNSv6 address in my DNS Changer app on my rooted Android device to the IPv6 address on the ninth line from my ipconfig /all command from the screen I previously attached, IPv6 traffic is now only sometimes being routed through my DNS server, and I'm not sure why.  I can tell this because, not only is there no increase in IPv6 requests from my current IPv6 address of this device in AdGuard Home, there are several entries in the DNS log from my DNS changer app where one request from a particular domain is blocked and another request from the same domain is allowed.  Every check I've done on https://www.top10vpn.com/tools/what-is-my-dns-server on this device, whether I am using the DNS changer by itself or in conjunction with AdGuard for Android, returns only Cloudflare DNS servers, which tells me this device is using my DNS server for both DNSv4 and DNSv6, since I have the Bootstrap DNS Servers in AdGuard Home set to:

```
1.1.1.1
1.0.0.1
2606:4700:4700::1111
2606:4700:4700::1001
```

Otherwise, it would show my ISP's DNSv6 addresses, which again, I do not believe is possible to modify with a DNS changer, unless possibly with a shell command such as the one I posted previously.  I'm still unsure why this device's IPv6 traffic is only sometimes being routed through my DNS server though

A few minutes ago, I also just got 50 requests in 8 seconds from domains, all of which I recognize as initiating from this same Android device, but from a client with an IPv6 address belonging to my mobile carrier, not my ISP.  How is it possible that traffic from a device can go through my DNS server on my LAN when this device was using cell data rather than being connected to my local network via Wi-Fi?  I've seen this before in the past as well

Thank you again.  Additional screens to follow


![Screenshot on 2023-02-27 at 23 56 17](https://user-images.githubusercontent.com/71743798/221798504-0bd3294a-5c44-4e32-95e2-da3be82c3a55.png)

**Comment by ainar-g** [comment]
<https://www.manualslib.com/manual/659561/Comcast-Xfinity.html?page=28#manual>

According to this, you should be able to set a static IP address for your Windows machine on the *Connected Devices > Computers* page.  If that's not available, or if it only works with IPv4 addresses, then I'm not sure if there is a better way than those I've listed above, sorry.

Also, whatever addresses you use, make sure to put the address into both primary and secondary address inputs, if there are two or more.  Otherwise devices will often use their default addresses.

**Comment by arubamon** [comment]
@ainar-g, thank you again for getting back with me.  While the user manual you linked in your last reply was not the correct one for my gateway, which is a Technicolor CGM4331COM, with a relevant user manual located at https://www.manualslib.com/manual/1877122/Technicolor-Cgm4331-Series.html, I knew where to look for the info you provided.  Only IPv4 addresses can be set statically in the router settings

Again, for reference, I am able to configure my IPv4 and IPv6 address ranges by modifying my DHCPv4 and DHCPv6 beginning and ending addresses, but I don't know enough about IPv6 addresses to modify those. I also have two options for LAN IPv6 Address Assignment, Stateless (Auto-Config) and Stateful (Use DHCP Server), however, the SLAAC option is grayed out, which may or may not have anything to do with my other router settings.  Since it is not possible to give devices a static IPv6 address in my router settings, I do not believe modifying my Link-Local Gateway Address, Global Gateway Address, or the DHCPv6 Beginning Address or DHCPv6 Ending Address will do me any good, correct?  From your previous replies, it seems my only option then would be to use a dynamic DNS provider, is this correct as well?  I do not believe even this is possible with the gateway I lease from Comcast Xfinity, therefore, is seems I have no available options, as far as I can tell

None of the below may even matter anymore then, but please let me know if anything here would be beneficial to my situation:

You can set both primary and secondary DNS servers in both Android settings and well as in the settings for my DNS changer app, which I did following your last reply, however, it appeared my Android device's IPv6 traffic was still only sometimes being routed through my DNS server, since there are several entries in the DNS log of my DNS changer app where one request from a particular domain is blocked and another request from the same domain is allowed.  However, all of these requests are blocked in my Query Log for AdGuard Home, so it seems none are actually getting through.  Is this was you would conclude as well?  I do not have screens showing all allowed domains that correspond to every blocked domain in the DNS log of my DNS changer app that I am attaching a screen of, but, as you can see, per my Query Log for AdGuard Home, all of these domains were indeed blocked, at least in AdGuard Home

You cannot natively set both the Preferred and Alternate DNS servers in Windows to the same IP address though, either for IPv4 or IPv6.  Screens attached

Again, my current AdGuardHome.yaml file, and all backups that I have since at least the middle of September, show:

```
dns:
  bind_hosts:
    - 0.0.0.0
```

My additional questions are still as follows:

1. On the previously attached screen, why is there an IPv6 address on the sixth line and also on the ninth line, in addition to the temporary IPv6 address on the tenth line down under my wired connection 'Ethernet adapter Ethernet'?
2. Which IPv6 address(es) should I be using for my IPv6 DNS address(es) on my client machines?
3. Should I also be using the above IPv6 address(es) for my IPv6 DNS address(es) on my Windows machine, which is hosting my DNS server, since it is also a client? It seems I should, as everything was working until my IPv6 addresses changed
4. As Android does not have the capability to natively modify DNSv6 addresses, would a script such as the below achieve the same outcome as using a DNS changer app.  I have been using https://play.google.com/store/apps/details?id=mobi.freeapp.dns.changer, which is the only one I have been able to get to work as intended

```
#!/system/bin/sh
# Enable IPv6
echo 1 > /proc/sys/net/ipv6/conf/wlan0/accept_ra
echo 1 > /proc/sys/net/ipv6/conf/wlan1/accept_ra
echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
```
5. I previously stated that requests from domains, all of which I recognize as initiating from my Android device, came from an IPv6 address belonging to my mobile carrier, not my ISP.  How is it possible that traffic from a device can go through my DNS server on my LAN when this device was using cell data rather than being connected to my local network via Wi-Fi?  I have seen this before in the past as well

I know I again made this much more complicated that it needed to be, but I hope the extra information is helpful.  If there are any questions which are beyond your expertise, since many do not deal specially with AdGuard Home, please notate this in your reply.  Hopefully, with your next reply, I can close this issue, as you are probably tired of replying to my long and complex responses.  Thank you once again for your assistance


![Screenshot on 2023-02-28 at 03 16 19](https://user-images.githubusercontent.com/71743798/222331101-fa3036ee-10a8-4952-8ed1-6472c0111326.png)
![Screenshot on 2023-03-01 at 19 34 36](https://user-images.githubusercontent.com/71743798/222331103-aa6c1ec3-d833-4915-98b0-69642db6ebed.png)
![Screenshot on 2023-03-01 at 19 34 49](https://user-images.githubusercontent.com/71743798/222331105-326e2f30-e9f3-45e8-963c-23d9c9689c29.png)
![Screenshot on 2023-03-01 at 19 35 03](https://user-images.githubusercontent.com/71743798/222331107-bd841520-479b-43d8-9a91-16bc56177d9b.png)
![Screenshot on 2023-03-01 at 19 35 08](https://user-images.githubusercontent.com/71743798/222331086-84a33da6-0acc-4f40-bb1e-d1a357337d8c.png)
![Screenshot on 2023-03-01 at 19 36 03](https://user-images.githubusercontent.com/71743798/222331087-5da8943e-92dc-49d6-b09d-c56fd626346c.png)
![Screenshot on 2023-03-01 at 19 36 09](https://user-images.githubusercontent.com/71743798/222331089-225576f6-7b61-4af5-b6d1-e7f5bbc808bb.png)
![Screenshot_20230227-195436_DNS Changer](https://user-images.githubusercontent.com/71743798/222331092-0549d869-7313-47f0-aaa5-c403e100c5d1.png)
![Screenshot_20230301-203323_DNS Changer](https://user-images.githubusercontent.com/71743798/222331094-f970f14b-7b01-4946-9a47-96ea937eaa38.png)
![Screenshot_20230301-203332_DNS Changer](https://user-images.githubusercontent.com/71743798/222331095-053e9fdd-8058-4832-9a2b-20127e7a4c6a.png)
![Screenshot_20230301-203918_DNS Changer](https://user-images.githubusercontent.com/71743798/222331097-d6c39b0c-eddf-4d0b-bbd2-472a9f131744.png)

**Comment by arubamon** [comment]
@ainar-g, thank you again for all your previous responses to my issue.  A week ago today I did create one additional rather long and detailed post to try and get one last bit of feedback regarding the questions I still have for this issue.  If you have time, would it be possible to follow up with me one final time so I can get clarification on, and then close, this first issue I have ever posted  of on this site?

Thank you again  :)

**Comment by ainar-g** [comment]
@arubamon, good day.  I do not have any new ideas, as the issue seems to not be with AdGuard Home but with this particular network configuration.  And also, if I can be honest, Windows network stack isn't exactly my _forte._  You might have more luck asking in the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a), since the Issues section is for bugs and feature requests in AdGuard Home itself.

**Comment by arubamon** [comment]
@ainar-g, got it.  That's what I was not sure about, which was the reason I mentioned "_If there are any questions which are beyond your expertise, since many do not deal specially with AdGuard Home, please notate this in your reply._" in a recent reply

Thank you again though for all your assistance in helping me deal with this issue.  Have a great day  :)
