### ISSUE TITLE
Massive traffic to x.x.x.x-.in-addr.arpa, thousands of requests

### ISSUE THREAD

**Issue by Knubbel** [AdguardTeam/AdGuardHome#5114]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.17

#### What did you do?
I have Adguard Home running on a Raspberry Pi 3b and 64bit Raspi-OS (fully updated).
Since the last update of AGH my statistics show a massive number of DNS requests to 8 different  x.x.x.x-.in-addr.arpa, Domains.
The top one has 175.000 hits in 7 days. In the request log I can see that sometimes there were thousands of requests in the very same second.
It all happens between the Raspi-AGH installation and my router (a AVM Friztbox with current OS).

**Comment by fernvenue** [comment]
Hi @Knubbel, these `.in-addr.arpa` are PTR records, are used for reverse DNS lookups, you can disable reverse resolving of client's IP addresses in Web UI, or add `*.in-addr.arpa` to disallowed domains. [Here](https://www.cloudflare.com/learning/dns/dns-records/dns-ptr-record/) is an explanation about PTR records.

**Comment by whyisthisbroken** [comment]
I´ve the same problem - okay i know this is not a Problem but it would be nice to exclude the PTR Requests from the Query Log and log them everywhere else.

Why ? The processesing time is to damn high (beyond 1000ms) and the Average processing time is negatively affected by this.

![Screenshot 2022-11-08 072612](https://user-images.githubusercontent.com/96284773/200491832-90fd8a01-5321-48cd-8c95-b6d06ad6a77b.jpg)
![Screenshot 2022-11-08 072526](https://user-images.githubusercontent.com/96284773/200491838-3be4b0d9-d198-4f5d-9637-c0f71700a398.jpg)

**Comment by Birbber** [comment]
Closing as completed. Please re-open if needed.
