### ISSUE TITLE
On DHCP server, allow to add additional fallback DNS servers

### ISSUE THREAD

**Issue by felipecrs** [AdguardTeam/AdGuardHome#5115]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

I use AdGuard Home's built-in DHCP server since my router doesn't let me change the DNS address. AdGuard Home's DHCP server instructs the devices to use `192.168.1.10` as DNS server, which is AdGuard's IP address. This can't be changed, and it's ok.

However, if I restart my Raspberry Pi running AdGuard, all DNS resolutions in my network will fail since `192.168.1.10` is down. It's less of an issue for DHCP since the devices keep their DHCP data cached for some hours by default, therefore a system reboot does not affect it much (except for new devices requesting DHCP, but that's another case).

#### Proposed solution

This could be easily fixed if AdGuard Home could serve DHCP entries with DNS servers as following:

```
192.168.1.10
1.1.1.1
1.0.0.1
```

Which the devices understands as, if server 1 isn't available, use the second, and so on. This would prevent DNS resolution in my network to fail while my Raspberry Pi is restarting.

So, this feature request is to allow setting extra DNS servers in the DHCP server configuration.

#### Alternatives considered

I haven't found any, except perhaps setting the DNS manually in each device?

#### Additional information

None.

**Comment by ppfeufer** [comment]
> Which the devices understands as, if server 1 isn't available, use the second, and so on. 
Common misconception. The provided DNS servers are randomly used. In other words, even if your Adguard Pi is online, as soon as there is more than one defined DNS server, it's not safe to say that a device in your network will always use them in the order provided.

**Comment by felipecrs** [comment]
Wow. If that's the case then my suggestion is meaningless. Thanks for the clarification.

**Comment by felipecrs** [comment]
Well, this doesn't seem to be what happens in Windows:

https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd197552(v=ws.10)?redirectedfrom=MSDN#:~:text=The%20DNS%20Client%20service%20queries%20the%20DNS%20servers%20in%20the%20following%20order%3A

**Comment by ppfeufer** [comment]
Read a bit further on that page ...

> The DNS Client service keeps track of which servers answer name queries more quickly, and it moves servers up or down on the list based on how quickly they reply to name queries.

It's even illustrated

![image](https://user-images.githubusercontent.com/2989985/200357145-32cd76a9-5449-4319-8955-f20d7db74a9f.png)

So there is a good chance that your AdGuard will be ignored after its reboot ...

**Comment by felipecrs** [comment]
Makes total sense. Sorry.
