### ISSUE TITLE
Latest release is broken

### ISSUE THREAD

**Issue by KruseLuds** [AdguardTeam/AdGuardHome#5116]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Version: v0.107.17

### Description

I am running a Raspberry Pi 4b 8GB Ram running Debian 64 bit on an SSD with an ethernet 1Gig internet connection , Home Assistant Supervised running in a container (SUPPORTED - see info at the end)

Functionality suddenly broken 

#### What did you do?

Click on check boxes - 
0. "Block domains using filters and hosts files" works fine.

1. "Use AdGuard browsing security web service" check box does not work and I get error message - 
	"Error: control/safebrowsing/enable | empty body with content-type "application/octet-stream" not allowed | 415"

2. "Use AdGuard parental control web service" check box does not work and I get error messages.
	"Error: control/parental/enable | empty body with content-type "application/octet-stream" not allowed | 415"

3. "Use Safe Search"  check box does not work and I get error messages.
	"Error: control/safesearch/enable | empty body with content-type "application/octet-stream" not allowed | 415"

#### Expected result

Able to enable those services.

#### Actual result

Listed above, then when that message appears at the same time the respective check box immediately becomes unchecked. The messages that appear are their briefly, then fade away:

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/96640689/200374522-933b61bf-5ae4-4f24-b951-198d674d6af7.png)

#### Additional information

I am running a Raspberry Pi 4b 8GB Ram running Debian 64 bit on an SSD with an ethernet 1Gig internet connection , Home Assistant Supervised running in a container (SUPPORTED - see info at the end)

The below was from Settings -> Hardware -> Repairs -> System Information menu option. The below is pasted from when I clicked the "copy" button at the bottom of that dialog:

## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.10.0-19-arm64
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4856
Installed Version | 1.28.3
Stage | running
Available Repositories | 1210
Downloaded Repositories | 22

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.dev0401
agent_version | 1.4.1
docker_version | 20.10.21
disk_total | 915.4 GB
disk_used | 13.4 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Log Viewer (0.14.0), Samba share (10.0.0), Home Assistant Google Drive Backup (0.108.4), File editor (5.4.1), Duck DNS (1.15.0), AdGuard Home (4.7.5), Terminal & SSH (9.6.1), Core DNS Override (0.1.1), Mosquitto broker (6.1.3), AppDaemon (0.10.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 15
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 9, 2022 at 12:59 AM
-- | --
current_recorder_run | November 7, 2022 at 11:51 AM
estimated_db_size | 1448.00 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by ainar-g** [comment]
Hello and thanks for the thorough report.  We cannot reproduce this, and in fact, we haven't changed anything related to those APIs since v0.107.15.  Our frontend code is not sending a `Content-Type` with such requests, so my first intuition is that either there are some browser extensions that do that or it's the Home Assistant plugin.  Whatever it is, it should not send any `Content-Type` with requests that nave ho bodies.

**Comment by junado** [comment]
I have just installed AdGuard Home (an hour ago) on HA 2022.11.1 (Supervisor 2022.10.2, OS 9.3) and get the same errors. Any additional info we could provide ?

**Comment by KruseLuds** [comment]
Well @ainar-g you have at lease three folks with the same issue. What would you need from us to help troubleshoot?

**Comment by KruseLuds** [comment]
Still an issue - just checked, here is a scrfeen shot and below is the status of my machine:
![image](https://user-images.githubusercontent.com/96640689/200664782-06594947-be3e-4aed-8bd4-25d86fd97906.png)

## System Information

version | core-2022.11.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.10.0-19-arm64
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4568
Installed Version | 1.28.3
Stage | running
Available Repositories | 1210
Downloaded Repositories | 22

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.dev0401
agent_version | 1.4.1
docker_version | 20.10.21
disk_total | 915.4 GB
disk_used | 13.6 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Log Viewer (0.14.0), Samba share (10.0.0), Home Assistant Google Drive Backup (0.109.1), File editor (5.4.1), Duck DNS (1.15.0), AdGuard Home (4.7.5), Terminal & SSH (9.6.1), Core DNS Override (0.1.1), Mosquitto broker (6.1.3), AppDaemon (0.10.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 15
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 9, 2022 at 5:43 PM
-- | --
current_recorder_run | November 8, 2022 at 2:57 PM
estimated_db_size | 1448.00 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by realdeadbeef** [comment]
Having the same problem here

**Comment by HanvanVilsteren1969** [comment]
same problem

**Comment by hhuitema** [comment]
Having exactly the same problem running Adguard addon on the latest edition of HAos on a NUC.

**Comment by KruseLuds** [comment]
@ainar-g we are still waiting a response from your end - what do you want us to do to help troubleshoot?

**Comment by snapsl** [comment]
The breaking change is the content-type policy introduced in v0.107.15.
See hassio-addons/addon-adguard-home/issues/359

**Comment by ainar-g** [comment]
@snapsl is correct.  That change has been documented, and removing that line from the Home Assistant's Nginx configuration should most likely fix the issue.

See hassio-addons/addon-adguard-home#359.

**Comment by sysadmin-info** [comment]
I have exactly the same issue. I cannot clear the cache in Adguard Home Addon in Home Assistant Supervised version:
Home Assistant 2022.11.2
Supervisor 2022.10.2
Frontend 20221108.0 - latest

**Comment by jackhax1** [comment]
Experiencing the same exact issue

**Comment by computermaster0101** [comment]
Same issue on new install

**Comment by usInagaZs** [comment]
Same issue here.

**Comment by lolobar** [comment]
Same issue using Homeassistant 2022.11.4

**Comment by Deki60** [comment]
hi, same problem with fresh Home Assistant installation. Need to manually update/modify any file for solve problem or wait update ?

**Comment by computermaster0101** [comment]
I was able to work around the issue by updating configuration for adguard in the addon to expose adguard on port 3000. Next I connected to adguard directly to make the change

**Comment by Deki60** [comment]
thank for reply, could you tell us where is the config file ? (maybe stupid question but i can't find it in ssh ) thank you

**Comment by computermaster0101** [comment]
In home assistant:

settings> add-ons> Adguard Home> Configuration (tab)> Show disabled port> Web Interface

**Comment by Deki60** [comment]
thank you i have find :) 
it's solution temporary 

for me, need to uncheck SSL 
after fo directly : http://ipofhomeassistant:3000
(login / pass of HA) and now i can activate all settings.
again Thank you

**Comment by toddel68** [comment]
I have the same issue. Will there be a fix soon?

**Comment by Liftboy222** [comment]
> In home assistant:
> 
> settings> add-ons> Adguard Home> Configuration (tab)> Show disabled port> Web Interface

Could you please concrete this. I'm more than blind.

Basically - a fix will be fine ;)

**Comment by toddel68** [comment]
> > In home assistant:
> > settings> add-ons> Adguard Home> Configuration (tab)> Show disabled port> Web Interface
> 
> Could you please concrete this. I'm more than blind.
> 
> Basically - a fix will be fine ;)
![Screenshot_20221204_175939](https://user-images.githubusercontent.com/87937203/205504644-3cb3d424-63f1-429c-ae5f-d1cebf2c6721.png)

This?

**Comment by Dengesiz07** [comment]
> > > In home assistant:
> > > settings> add-ons> Adguard Home> Configuration (tab)> Show disabled port> Web Interface
> > 
> > 
> > Could you please concrete this. I'm more than blind.
> > Basically - a fix will be fine ;)
> > ![Screenshot_20221204_175939](https://user-images.githubusercontent.com/87937203/205504644-3cb3d424-63f1-429c-ae5f-d1cebf2c6721.png)
> 
> This?

Basicly, navigating to homeassistant using this port on web interface lands you in adguard (you'll need to provide HA user & password) then you can change the settings successfully.

![image](https://user-images.githubusercontent.com/25850782/205513532-adf16248-27fa-4ed4-ae37-317693694691.png)

**Comment by toddel68** [comment]
Okay, got it - I managed to switch Safe Search of via port 3000. Thanks a lot for helping me out here!

**Comment by Liftboy222** [comment]
Unfortunately, the workaround does not work for me. I don't really have time to take care of it at the moment. Is there a chance that this problem will be fixed in the future?

**Comment by smarthome286** [comment]
confirming this solution work for me by access port 3000.
Thank to @computermaster0101 for value info

**Comment by Liftboy222** [comment]
With Adguard Version v0.107.17 does not seem to run an automatic updates.
Is there a work arround to solve this problem?

As a beginner idea:
Would a way be to make a complete backup of the homeassistant, to uninstall the plugin adguard and then to get the current version with a new installation and then to get the settings back with the restore of the backup?

**Comment by Liftboy222** [comment]
I have now the Add-on version: 4.7.5 with the actual AdGuard. The settings for parental still not working also with the port 3000. I will wait for the next update and look forward. For the childs it would be nice to add the safe search and parental settings. Else I will take a seperat raspberry to arrange this ;)

**Comment by sysadmin-info** [comment]
All is working. Upgrade Home Assistant Supervised, upgrade core and upgrade Adguard Home addon. Also integration in home panel is working correctly. 
![Screenshot_20230107_100009_Home Assistant](https://user-images.githubusercontent.com/23638074/211146504-4d58294a-f92f-4085-8762-4df328849c99.jpg)
