### ISSUE TITLE
unable to add the MobileFilter specific_app.txt

### ISSUE THREAD

**Issue by techroy23** [AdguardTeam/AdGuardHome#5119]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Custom port

### Setup

On one machine

### AdGuard Home version

v0.107.17 and v0.108.0-b.20

#### What did you do?
Update to latest version

#### Expected result
not get any error

#### Actual result
2022/11/08 06:13:56.381409 [info] Failed to update filter https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/specific_app.txt: data is HTML, not plain text

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/53241974/200489079-f67f4369-df18-4ac7-b0fc-c4f33a5061b6.png)

**Comment by ainar-g** [comment]
Sorry for a long time with no response.  Seems like the same error as in #5237.  Re-adding the list should fix the issue.
