### ISSUE TITLE
Questions: DHCPd? Default config?

### ISSUE THREAD

**Issue by prologic** [AdguardTeam/AdGuardHome#512]
Hi, just a couple of (//hopefully easy questions//):

1. Does AdGuardHome also have a built-in DHCP server? I notice this in the source code but not seeing any mention of it anywhere else. If so; what is the intended use-cases for this?

2. I found `tests/dns.txt` but no other "thing" that looks like a default config. Where does AdGuardHome get its default config from? Specifically a default list of DNS names to block/filter?

Thanks!

**Comment by ameshkov** [comment]
> Does AdGuardHome also have a built-in DHCP server? I notice this in the source code but not seeing any mention of it anywhere else. If so; what is the intended use-cases for this?

It does, scroll the settings screen down a bit:)

The use case is to run a DHCP server that will define AG Home as the default DNS server for the network.

> 2) -- Looks like on startup a AdGuardHome.yaml config is generated and seems to use this remote file as it's DNs filter list: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

Depending on what filters are configured, it downloads them on the first startup.
