### ISSUE TITLE
Adguard Home not blocking/filtering anything on from my LAN

### ISSUE THREAD

**Issue by Ironfist69** [AdguardTeam/AdGuardHome#5125]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

0.107.18

#### Additional information

Yesterday I have installed ADH on Oracle cloud instance, added the Public IP address of the ubuntu instance in my Routers DNS settings. But it's not blocking any single ads. I've checked the Query Logs and all requests are coming from 127.0.0.1, not from my LAN. My ISP provides Dynamic IP not the static one. Is it the main culprit or I'm missing something??

![Screenshot (5)](https://user-images.githubusercontent.com/70436487/201011734-5ab3fd73-3496-4e8f-8949-ef5103d05463.png)

**Comment by TypicalGamer07** [comment]
> Have you restart your router? Restart it for all devices to change to new DNS. (Just reconnect) And you just leaked your Oracle IP on the screenshot. 😂

Obviously YES !

**Comment by Legendofallpro** [comment]
Same issue here, anybody have a solution

(exact scenario as OP)
