### ISSUE TITLE
插件突然大量占用系统资源导致系统无响应也无法上网

### ISSUE THREAD

**Issue by jdydhking** [AdguardTeam/AdGuardHome#5128]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.18

###  时常突然占用大量系统资源，导致系统无响应，同时无法上网******

**Comment by bh** [comment]
OpenWRT on what hardware?
