### ISSUE TITLE
Admin Interface 404's

### ISSUE THREAD

**Issue by prologic** [AdguardTeam/AdGuardHome#513]
On a fresh build the Admin Interface 404's :/

```#!bash
$ git id
fd629be
```

See attached.

<img width="1312" alt="screen shot 2019-01-02 at 10 22 26 am" src="https://user-images.githubusercontent.com/1290234/50577666-9464a900-0e78-11e9-8704-aa6097c21059.png">

**Comment by prologic** [comment]
Is this becuase the `./client/` interface isn't built?

```#!bash
$ make
npm --prefix client install
make: npm: No such file or directory
make: *** [client/node_modules] Error 1
```

I don't have or use npm locally so it would be nice if we didn't pollute the local system with npm modules everywhere and unnecessary tooling. is it possible to have a prebuilt dev version committed?

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/514#issuecomment-467088012
