### ISSUE TITLE
Adguard not blocking ads

### ISSUE THREAD

**Issue by mcspidey95** [AdguardTeam/AdGuardHome#5132]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.18

#### What did you do?
Installed Adguard Home on my Raspberry Pi 4

#### Expected result
Blocks Ads

#### Actual result
Doesn't block ads

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/90018162/201358272-9993bd44-605f-4498-b508-882dce83eafd.png)

#### Additional information
ive already changed the dns settings on my router, phone and laptop as well, doesnt block ads at all.
On the Dashboard it says it blocks ads (counter increases), but it actually doesnt block any ads, or block the websites i manually restricted.

It even doesnt show up on the logs.

**Comment by mcspidey95** [comment]
![image](https://user-images.githubusercontent.com/90018162/201358898-812865c0-7362-45ab-b00f-3f656bb90c5e.png)
![Screenshot_20221111_074823](https://user-images.githubusercontent.com/90018162/201358983-d48a88f6-d151-421f-b991-eadc4de8ce77.png)

i have also updated my filters, still nothing!

**Comment by whyisthisbroken** [comment]
Check the DNS Server Settings on you Notebook.
Open CMD and enter this:

echo exit | nslookup

What is the Output ?
It should be your Rasperry IP.

**Comment by mcspidey95** [comment]
![Screenshot_20221111_094956](https://user-images.githubusercontent.com/90018162/201390998-fd80655d-339d-4022-8c37-33ef600ce893.png)

**Comment by whyisthisbroken** [comment]
Mhm - it looks like your DNS settings are not correct.
Is the ipv6 "Adress:" the ip from your raspberry?

Try the following in cmd

ipconfig /flushdns

And post the result.

**Comment by mcspidey95** [comment]
it is fixed now.. i manually configured the IPv4, v6 addresses on my laptop for it to work. But if i set it back to automatic, the issue persists, any fix?

**Comment by whyisthisbroken** [comment]
I think that there is a problem with the network settings from your raspberry or router.
The devices don't get the information who is the DNS server.
Maybe the DHCP server from Adguard (i don't use it)

**Comment by mcspidey95** [comment]
anyways, thanks for your help. I'll just use the manually configured settings till i figure out the issue.

PS: Nice username and location :)
