### ISSUE TITLE
Can't Use doh3 due to the quic's problem

### ISSUE THREAD

**Issue by WY-WY-W** [AdguardTeam/AdGuardHome#5133]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [x] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.18

### Description

####System
Ubuntu 20.10 
Raspberry Pi 4B
#### What did you do?
I want to create a doh3 for my android phone since the private dns mode can only be either dot or doh3.

#### Expected result
works fine

#### Actual result
 HTTP/3 is fine but QUIC isn't work. Therefore, doh3 doesn't work
#### Screenshots (if applicable)
<img width="1260" alt="Screenshot 2022-11-11 at 10 58 45 PM" src="https://user-images.githubusercontent.com/69680622/201367632-6ffc4aef-88ee-4301-9408-b29c80a28b25.png">

#### Additional information
with a proper ssl cert and set the http port to 443 already
udp and tls 443 port have already been listened by the AdGuard Home

**Comment by ameshkov** [comment]
Where do these screenshots come from?

**Comment by WY-WY-W** [comment]
A website called https://http3check.net/
It tells me that whether the doh3 works or not in a easier way.

**Comment by ameshkov** [comment]
I am not entirely sure what this "QUIC is not supported" means. HTTP/3 does work over QUIC, it cannot work without QUIC in general. Maybe it reacts to support for some draft protocol versions?

Regarding Android, as far as I know it only allows using a limited set of DNS resolvers with DoH3 and you cannot just add a custom DoH3 resolver.

**Comment by ameshkov** [comment]
Figured that out. `Alt-Svc` header does not specify quic, it only specifies HTTP/3 in our case and that's why that websites shows that QUIC is not supported.

This is not a mistake and it's not related to DoH3 anyways.
