### ISSUE TITLE
Docker multi-stage builds?

### ISSUE THREAD

**Issue by prologic** [AdguardTeam/AdGuardHome#514]
it would be good to use multi-stage docker builds here. This would help with #513

**Comment by prologic** [comment]
Here's a working multi-stage `Dockerile`:

```#!Dockerfile
FROM golang:alpine AS build

RUN apk add --update git make build-base npm && \
    rm -rf /var/cache/apk/*

WORKDIR /src/AdGuardHome
COPY . /src/AdGuardHome
RUN make

FROM alpine:latest
LABEL maintainer="Erik Rogers <erik.rogers@live.com>"

# Update CA certs
RUN apk --no-cache --update add ca-certificates \
    rm -rf /var/cache/apk/*

COPY --from=build /src/AdGuardHome/AdGuardHome /AdGuardHome

EXPOSE 53 3000

VOLUME /data

ENTRYPOINT ["/AdGuardHome"]
CMD ["-h", "0.0.0.0"]
```

For those on macOS and using [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) you can easily try out AdGuardHome like this:

```#!bash
$ docker build -t adguardhome .
$ docker run -t --rm -p 53:53/udp -p 3000:3000/tcp adguardhome
$ sudo networksetup -setdnsservers Wi-Fi 127.0.0.1
```

So far so good :) -- @adguardteam LMK if you'd like a PR for this?

**Comment by prologic** [comment]
A PR and/or some version of the above multi-stage `Dockerfile` would solve #513

**Comment by ameshkov** [comment]
I've collected all the Docker-related issues and questions in a separate milestone, we'll discuss it with the team once I am back from vacations (~20th of Jan).

The current plan is to publish a hotfix release with some major bugs of v0.92 fixed asap: https://github.com/AdguardTeam/AdGuardHome/milestone/7

Then we should get back to what's planned on [v0.93](https://github.com/AdguardTeam/AdGuardHome/milestone/4). Maybe we'll be able to squeeze the Docker-related issues somewhere in between.

**Comment by prologic** [comment]
I'm pretty happy with my set-up here. Consolidating all te Docker related issues into one sounds good 👍In order of importance I'd like to see:

1. Automated Builds via Docker Hub
2. Multi-stage Dockerfile
3. A traditional `docker-compose.yml` for `docker-compose up` and "Stackfile" (//CNAB?//) for `docker stack deploy`

**Comment by ameshkov** [comment]
Well, we've not done multi-stage builds, but we now have the official image that is updated automatically on every new commit to `master` (`edge` tag on Docker Hub), I hope it's enough:
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.93
