### ISSUE TITLE
Unable to set tls://, quic://, etc

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#5150]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.18

#### What did you do?
Set Upstream DNS servers (they were previously set, they decided to stop working...)
tls://unfiltered.adguard-dns.com
quic://unfiltered.adguard-dns.com
tls://dot.securedns.eu
https://dns.cloudflare.com/dns-query
sdns://AgUAAAAAAAAAACAe9iTP_15r07rd8_3b_epWVGfjdymdx-5mdRZvMAzBuQ5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs
tls://dns.google

#### Expected result
Expected them to work...

#### Actual result
Server "https://dns.cloudflare.com/dns-query": could not be used, please check that you've written it correctly
Server "sdns://AgUAAAAAAAAAACAe9iTP_15r07rd8_3b_epWVGfjdymdx-5mdRZvMAzBuQ5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs": could not be used, please check that you've written it correctly
Server "tls://dns.google": could not be used, please check that you've written it correctly
Server "tls://dot.securedns.eu": could not be used, please check that you've written it correctly
Server "tls://unfiltered.adguard-dns.com": could not be used, please check that you've written it correctly

#### Additional information
I've noticed the other issue where you suggest it's an "internet connection problem" - it's not. I've got 1 Gbps fiber, 0 packet loss.

**Comment by Onepamopa** [comment]
Update:

I'm using AGH installed as a service.

I think something's restricting AGH from working when placed in some locations (c:\agh\ or c:\users\theuser\Downloads\agh).

I've moved the agh folder to "Program Files" and it started working with the exception of:

2022/11/15 19:54:39.006269 [info] upstream "tls://dot.securedns.eu" fails to exchange: couldn't communicate with upstream: getting connection to tls://dot.securedns.eu:853: couldn't find any suitable IP address for host dot.securedns.eu


Before that, it was giving the following errors @ the verbose log:

2022/11/15 19:48:41.524182 [info] upstream "tls://dot.securedns.eu" fails to exchange: couldn't communicate with upstream: getting connection to tls://dot.securedns.eu:853: couldn't find any suitable IP address for host dot.securedns.eu
2022/11/15 19:48:41.555293 [info] upstream "https://dns.cloudflare.com/dns-query" fails to exchange: couldn't communicate with upstream: requesting https://dns.cloudflare.com:443/dns-query: Get "https://dns.cloudflare.com:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ": read tcp 192.168.254.129:43554->104.16.132.229:443: wsarecv: An established connection was aborted by the software in your host machine.
2022/11/15 19:48:41.584222 [info] upstream "sdns://AgUAAAAAAAAAACAe9iTP_15r07rd8_3b_epWVGfjdymdx-5mdRZvMAzBuQ5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs" fails to exchange: couldn't communicate with upstream: requesting https://dns.google.com:443/experimental: Get "https://dns.google.com:443/experimental?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ": read tcp 192.168.254.129:43555->8.8.4.4:443: wsarecv: An established connection was aborted by the software in your host machine.
2022/11/15 19:48:41.613692 [info] upstream "tls://dns.google" fails to exchange: couldn't communicate with upstream: getting connection to tls://dns.google:853: connecting to dns.google: read tcp 192.168.254.129:43556->8.8.4.4:853: wsarecv: An established connection was aborted by the software in your host machine.

**Comment by fernvenue** [comment]
Hi @Onepamopa, which Windows version do you use? And could you please try using IP instead of domain like `tls://1.0.0.1` and see what's happen?
