### ISSUE TITLE
Disable protection still does dnsrewrite

### ISSUE THREAD

**Issue by andekande** [AdguardTeam/AdGuardHome#5152]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.18

#### What did you do?
In Dashboard click on Disable protection. Wait for expired ttl of the dns block cache (a minute).

#### Expected result
Every DNS query is passed through 1:1 to upstreams without modifications.

#### Actual result
[$dnsrewrite rules](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite and entries from [DNS rewrites](http://localhost:81/#dns_rewrites) screen are applied.

#### Additional information
@ainar-g #5060

**Comment by fernvenue** [comment]
Actually, I think that's a reasonable behavior, sometimes we do need DNS-REWRITE for private network, and there is nothing to do with protection, they should work fine even when we disable block list. And if you use DNS-REWRITE to block some ads or something else, I think you probably need to use filter to do that instead of using DNS-REWRITE.

**Comment by andekande** [comment]
Well, in my case the rewrites are used for external addresses I can not control. Internal infrastructure is configurable though.
So I guess then AdGuard would need to distinct if the rewrite is for an external tld and leave the others intact.

**Comment by fernvenue** [comment]
> Well, in my case the rewrites are used for external addresses I can not control. I don't want to block them but have them redirected to an internal IP - except when AG filtering is off, then the "real" IP shall be resolved.

I see, so some people want to keep the rewrites, but the others don't. I think maybe keep the rewrites in **Filters - DNS rewrites** when disable protection but disable any other rules such as rewrites in **Filters - Custom filtering rules** will be great.

**Comment by andekande** [comment]
On the other hand I read in the discussion forums that the first option is to be deprecated somewhen.
