### ISSUE TITLE
Rule matching process wrong

### ISSUE THREAD

**Issue by dairywg** [AdguardTeam/AdGuardHome#5153]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.18

#### What did you do?
\> <code>nslookup www.bmcx.com</code>

#### Expected result
\> <code>nslookup www.bmcx.com</code>
Server:		127.0.0.1
Address:	127.0.0.1#53
Non-authoritative answer:
www.bmcx.com	canonical name = vvv-auto-1.7x24s.com.
Name:	vvv-auto-1.7x24s.com
Address: 47.97.111.188

#### Actual result

> **Domain(cpu.bmcx.com) is machted by Rule(||7x24s.com^).**

[root@htpc filters]# <code>nslookup www.bmcx.com</code>
Server:		127.0.0.1
Address:	127.0.0.1#53
Non-authoritative answer:
Name:	www.bmcx.com
Address: 0.0.0.0

#### Additional information

> **Log from AdGuard-Home's WebUI:** 
Response details
Status  Blocked by CNAME or IP
DNS server 127.0.0.1:5353 (served from cache)
Elapsed 0.25 ms
Response code NOERROR
Rule(s) ||7x24s.com^  anti-AD
Response  A: 0.0.0.0 (ttl=10)
Original response  A: 0.0.0.0 (ttl=10)

**Comment by Disqu3-mirOir-qt** [comment]
https://adguard.com/en/blog/cname-tracking.html?cname

old article

**Comment by Birbber** [comment]
Closing as completed. Please re-open if needed.
