### ISSUE TITLE
Couldn't start ipv4 listen

### ISSUE THREAD

**Issue by Diedparty** [AdguardTeam/AdGuardHome#5162]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.383+93882d68

### Description

Yestersday I install it with LXCDebian on Unraid,It was successfully installed,But record doesn't show anything about ipv4 but ipv6. I try to use command "isof -i:53",But I found it couldn't start listen ipv4 on port 53. Only show it start with ipv6. And no other use ipv4 on port 53.The guide page show ipv4 address and my Debian has an ipv4 connection, I'm confused. How to I fix it? Sorry for my poor English. I'm still learning it. Thanks anyway.

**Comment by ppfeufer** [comment]
If a device supports both, IPv4 and IPv6 and has both address types assigned to it, it seems IPv6 is prioritized. At least from my experience.

**Comment by Diedparty** [comment]
> If a device supports both, IPv4 and IPv6 and has both address types assigned to it, it seems IPv6 is prioritized. At least from my experience.

Well,Later I found some documents about ipv6 and ipv4 with Linux. From RFC2553, it seems that Linux will auto transform ipv4 format to ipv6 format based on AF_INET6. When "bindv6only" in kernel set as "0", all ipv4 format requests bind to it's ipv6 format. When it set as "1", ipv4 and ipv6 will open different ports for each use. You are right. Thank you.
