### ISSUE TITLE
android peripherals not protected

### ISSUE THREAD

**Issue by hpi06** [AdguardTeam/AdGuardHome#5172]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

ARMv5

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

0.107.18

### Description

Hello.
i Installed adguard home on a raspberry pi in my home network.
it works fine on all computers under windows but not working on all androids peripherals: 3 smartphones Huawey and samsung, and 1 tablet Huawei.
i don't understand why android peripherals are not filtred... They all are connected on the wifi network where the adguardhome server is installed.
On my Adsl Box, i entered the IP of the adguardhome server in the dns.

Can you help me?
thanks

**Comment by ppfeufer** [comment]
From AGH's setup page:

> Android
> 1. From the Android Menu home screen, tap Settings.
> 2. Tap Wi-Fi on the menu. The screen listing all of the available networks will be shown (it is impossible to set custom DNS for mobile connection).
> 3. Long press the network you're connected to, and tap Modify Network.
> 4. On some devices, you may need to check the box for Advanced to see further settings. To adjust your Android DNS settings, you will need to switch the IP settings from DHCP to Static.
> 5. Change DNS 1 and DNS 2 values to your AdGuard Home server addresses.

**Comment by hpi06** [comment]
Hi.
Thanks for your answer. I allready did it but it doesn't work...

**Comment by Harvester57** [comment]
Do you have IPv6 enabled ?

Also, a non-negligeable maount of Android apps are bypassing the system provided DNS servers, you need to have redirecting rules at the firewall level for DNS queries on port 53 TCP/UDP to almost-fully filter DNS requests from Android devices.

**Comment by Waldorf3** [comment]
I have almost the exact same situation.  Everything works as it should for Linux and Windows clients, but Android devices seems to sail straight through, particularly apps.  It would make perfect sense that developers wised up to dns-blockers and either hardcode the adservers IP addresses or use a public dns server to get them.  I would say, this throws a huge spanner in the effectiveness of ad-blockers such as AdguardHome. 

Blocking/redirecting DNS queries in a firewall is a fair suggestion, except I think most people probably have consumer router equipment without this functionality.   I have a TP-link Archer and as far as I can see there is no way I can trip this kind of port activity. The closest seems to be some kind of reverse NAT forwarding that I don't think will help here.

![image](https://user-images.githubusercontent.com/104714194/213318004-385b0ea5-f386-47e0-8123-6f141727f490.png)

Any other ideas?  Maybe some sort of VPN client directing traffice elsewhere, but I guess it would still try to go direct to the adserver?

**Comment by Harvester57** [comment]
I use my own publicly reacheable instance of AdGuard Home for my Android devices, and I use the Private DNS feature (introduced in Android 9) to direct the device DNS requests to it, so far it is working as expected and even in-app ads are blocked.

Or as you mentionned, you can try with a VPN, but it's kind of the same solution (with more overhead)

**Comment by Waldorf3** [comment]
Actually the problem is how Android phones deal with DNS, possibly due to how it dynamically shifts between mobile and wifi connections.   Normally DHCP device respect the DNS servers offered by DHCP, but Android defaults to using the DNS servers provided by the mobile provider, even when using wifi.  

Android phones from version 9 have an option to select Private DNS in the setup. **This only accepts DNS-over-TLS (DoT) on port 853.**   So forget about all other options and ports, setup AGH to listen on port 853 and add a good certificate, then it ought to work.
