### ISSUE TITLE
a very important requirement,Unreasonable parsing speed

### ISSUE THREAD

**Issue by Atlantis829** [AdguardTeam/AdGuardHome#5176]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
The third method of DNS query (choose the fastest IP) has no time limit and the query time will be very long
#### Proposed solution
It is recommended to add a definable time limit
#### Alternatives considered
Add this option next to that option
#### Additional information
This is very necessary. We know that sometimes, we cannot ensure that the encrypted DNS service provider I filled in is always working uninterrupted, or due to some technical problems, it is impossible to connect to the selected encrypted DNS server. At this time, we need not wait for all servers to respond after waiting for a few seconds, but choose the fastest among all the current results. Without this option, I would have waited 40 seconds or more like now, which is very unreasonable, after all, we cannot guarantee that all servers will always work normally. I'm really looking forward to my suggestion being adopted, it's a feature I've needed so much, thank you.
![图片](https://user-images.githubusercontent.com/95276002/203017382-0c312343-92dd-4d24-b196-2579f83972f8.png)

**Comment by fernvenue** [comment]
You can use `fastest_timeout` to set timeout used for dialing the addresses while picking the fastest, make sure you really checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer before you open an issue :)

**Comment by Atlantis829** [comment]
> You can use `fastest_timeout` to set timeout used for dialing the addresses while picking the fastest, make sure you really checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer before you open an issue :)

I'm sorry that I asked this stupid question carelessly, which delayed your time. Thank you very much
