### ISSUE TITLE
Keep statistics longer than 90 days

### ISSUE THREAD

**Issue by myxor** [AdguardTeam/AdGuardHome#5183]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

Keeping the statistics longer than the currently maximum time frame of 90 days

#### Proposed solution

Allow configuration of longer time frames (e.g. 180 days, 365 days).

**Comment by lutfor-diu** [comment]
I need this option too. Why only limited to 90 days? I also dont like the graph look. Pi hole has a better looking graph.

**Comment by chdeimos** [comment]
Tambien estoy interesado en esta mejora. Ademas me permitiria añadir algo mas, como es la busqueda de registros, para una ip en un periodo de tiempo. (como pi-hole).
![image](https://user-images.githubusercontent.com/120095607/206418006-f5bf6222-4e1e-4839-8960-780f995ec335.png)

**Comment by mailforvenky** [comment]
Actually all i wanted in this is the count of statistics and since when its active similar to Adguard app.

**Comment by ainar-g** [comment]
Merging into #3404.
