### ISSUE TITLE
DHCP ipv6 doesn't distribute Adguardhome DNS ip adress but router's - static IP adresses are not kept

### ISSUE THREAD

**Issue by Gandulf78** [AdguardTeam/AdGuardHome#5185]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

ARMv7

### Installation

Docker

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.108.0-b.22

#### What did you do?
I have set up adguardhome as DHCP IPv6 server (IPv4 is working fine).
#### Expected result
The DNS adress of AGH is distributed to all devices on the network. Thus i can see all the clients in the logs and apply customized rules on IPv6 as on IPv4.
#### Actual result
The DNS address distributed on the devices is the router IPv6 address. The static IP adresses are not respected. Thus all the DNS requests seems to come from the router address.
The clients under test are on iOS 16.1.1 and iOS15.7.

**Comment by neon-dev** [comment]
I have been experiencing progress.
In v0.107.35 some Windows clients randomly receive IPv6 DNS adresses from AdGuard Home:
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/1169307/f3248a18-d219-479f-aefd-6adaeba74f21)
The first four IPs are from AdGuard Home but the last one is the one of my cable router, which of course should not be there.
Also the fe80 one times out with `nslookup` even though it can be pinged, not sure if that's an error on my end.

**Comment by neon-dev** [comment]
Hi, I just checked on my machine and yes, IPv6 DNS server address is my router's currently:
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/1169307/82de4cb3-6433-4f6d-8933-f28b98f894fe)
Tested on v0.107.43 initially and now updated to v0.107.46 and ran `ipconfig /release` + disabled then enabled the network adapter, same result.

**Comment by overwatch3560** [comment]
@neon-dev have you already tried ipconfig /renew after the release? If yes do you get the same result?

**Comment by neon-dev** [comment]
@overwatch3560 yes, just tried it still got the same DNS IPs.

**Comment by overwatch3560** [comment]
@neon-dev and did you disable the dhcp server entirely on your router?

**Comment by neon-dev** [comment]
Yes, although now that you say it, I cannot fully rule out that my router's buggy firmware maybe still advertises its IPv6, as some other settings also don't quite work as they should.
Would you know how I could test this?

**Comment by overwatch3560** [comment]
Have you tried updating your router to the latest firmware update?

**Comment by neon-dev** [comment]
There is no way for users to manually update it but it has received several updates by my ISP and the last one was just a few weeks ago.

**Comment by overwatch3560** [comment]
I would ask them if they can fully disable the dhcp server

**Comment by neon-dev** [comment]
At this point it would be best if others could report their findings with their setups. Maybe this issue really is solved already or not related to AGH.
@Gandulf78 are you still experiencing this?

**Comment by overwatch3560** [comment]
Do you have a modem and behind that the router where you configured adguard in or ?
