### ISSUE TITLE
Add Clear DNS Cache Button in DNS Settings

### ISSUE THREAD

**Issue by L8X** [AdguardTeam/AdGuardHome#5190]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

Clearing cache currently requires restarting or setting cache size to 0 and back to the old number, which is tedious.

#### Proposed solution

Add a clear cache button under DNS Settings that will purge the cache file of AGH.

#### Alternatives considered

There are no realistic or simpler alternatives.

#### Additional information

N/A

**Comment by whyisthisbroken** [comment]
Would be also nice to see how much entries are inside the cache or size like MB.
The cache feature is nice but no one can see any stats. I mean, stats are essential within a server program or not :)

**Comment by ainar-g** [comment]
See also #4695.

**Comment by ainar-g** [comment]
This is implemented as of `v0.108.0-a.391+09f88cf2` on the Edge channel.  Can you please check if the new feature works for you?
