### ISSUE TITLE
The new --update flag does not work

### ISSUE THREAD

**Issue by siavashs** [AdguardTeam/AdGuardHome#5191]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

32-bit MIPS LE

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.19

#### What did you do?
Ran `./AdGuardHome --update` on EdgeRouter X
#### Expected result
AdGuardHome to check for updates and exit as it's already running the latest version.
#### Actual result
It printed a DHCP error and just waited:
```
# ./AdGuardHome --update
2022/11/25 11:58:06.612383 [info] AdGuard Home, version v0.107.19
2022/11/25 11:58:06.675757 [info] tls: using default ciphers
2022/11/25 11:58:06.690595 [error] creating dhcpv4 srv: dhcpv4: invalid IP is not an IPv4 address
2022/11/25 11:58:06.722682 [info] Initializing auth module: /config/AdGuardHome/data/sessions.db
^C
2022/11/25 11:58:47.843287 [info] Received signal "interrupt"
2022/11/25 11:58:47.843436 [info] stopping AdGuard Home
2022/11/25 11:58:47.844284 [info] stopped
```

**Comment by EugeneOne1** [comment]
@siavashs, hello and apologies for the response.  The latest `edge` release should fix the behavior of the `--update` flag to make it update the binary and restart the service if the one installed.  Note that in order to update the edge release, the next `edge` release should be published first.  You may also want to wait for the following `beta` build or even the `release` one.

**Comment by EugeneOne1** [comment]
@siavashs, hello again.  It works on our machines so far, so I'll close the issue for now if you don't mind.  You're welcome to reopen it on issues with the fix.
