### ISSUE TITLE
Custom dns record

### ISSUE THREAD

**Issue by Garbg** [AdguardTeam/AdGuardHome#5194]
LocalDNS is what I'm talking about
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I would like it so I can add a custom dns record for the servers hosted on my local network without buying a domain name. For example going to nextcloud.host would bring me to my nextcloud server
#### Proposed solution
Add a setting called custom domains to do it
#### Alternatives considered
There are none

**Comment by ppfeufer** [comment]
That sounds like seomthing you can do wth DNS Rewrites » https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by Garbg** [comment]
How would I make it so nextcloud.host for example connects me to 127.0.0.1/nextcloud?

**Comment by Garbg** [comment]
Or myserver.host/nextcloud connects me to 127.0.0.1/nextcloud

**Comment by Garbg** [comment]
> That sounds like something you can do with DNS Rewrites » https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

Where would I put the dns rewrite?

**Comment by ppfeufer** [comment]
THAT is outside of AGH's scope and capabilities. You'll need a webserver/proxy for this. AGH can point a custom domain name to an IP, not to a path.

**Comment by ppfeufer** [comment]
> Where would I put the dns rewrite?

2 Options:
- Settings » DNS Rewrites
- A `.txt` file you load as "Blocklist" under Filters » DNS Blicklists

**Comment by Garbg** [comment]
> THAT is outside of AGH's scope and capabilities. You'll need a webserver/proxy for this. AGH can point a custom domain name to an IP, not to a path.

That's fine with me :)

**Comment by Garbg** [comment]
> THAT is outside of AGH's scope and capabilities. You'll need a webserver/proxy for this. AGH can point a custom domain name to an IP, not to a path.

Does dns rewrite work with links that use a port that isn't port 80?

**Comment by Garbg** [comment]
> > THAT is outside of AGH's scope and capabilities. You'll need a webserver/proxy for this. AGH can point a custom domain name to an IP, not to a path.
> 
> Does dns rewrite work with links that use a port that isn't port 80?

For example could I make jellyfin.host connect to 127.0.0.1:8096

**Comment by ppfeufer** [comment]
> For example could I make jellyfin.host connect to 127.0.0.1:8096

No, that's what you need the webproxy for (Apache or Nginx)

**Comment by Garbg** [comment]
> > For example could I make jellyfin.host connect to 127.0.0.1:8096
> 
> No, that's what you need the webproxy for (Apache or Nginx)

But you said dns rewrite dosent work with paths?

**Comment by Garbg** [comment]
> > > For example could I make jellyfin.host connect to 127.0.0.1:8096
> > 
> > 
> > No, that's what you need the webproxy for (Apache or Nginx)
> 
> But you said dns rewrite dosent work with paths?

And a reverse proxy would turn 127.0.0.1:8096 into 127.0.0.1/jellyfin

**Comment by Garbg** [comment]
> > > > For example could I make jellyfin.host connect to 127.0.0.1:8096
> > > 
> > > 
> > > No, that's what you need the webproxy for (Apache or Nginx)
> > 
> > 
> > But you said dns rewrite dosent work with paths?
> 
> And a reverse proxy would turn 127.0.0.1:8096 into 127.0.0.1/jellyfin

But it's fine if it's just my server.host/jellyfin

**Comment by ppfeufer** [comment]
Ok, it seems you might have to do some reading about what DNS, web server, web proxy and so on are, what they are supposed to do and how they are working before you are setting something up that requires at least a basic understanding of these things.

I'm not saying don't set up AGH in your home network. But if you want to do some DNS manipulation with it (which is entirely possible to an extent), please make sure you understand what it is you're trying to do first or you'll end up disappointed.

And to teach you the basics of networking, this is the wrong platform I'm afraid.

Some pointers:

AGH is a DNS Proxy/Filter/Forwarder. Its purpose is to filter the DNS requests from your network or any connected device. It does not turn a DNS name (device.lan) into a website you can view on your browser. All it does is resolved the DNS name into its IP and return it to the device querying. (DNS rewrites included, which are nothing else but mapping a DNS name to an IP)

Webservers are services running on a device that provides a website you can view in your browser. They can listen to an IP or DNS name, doesn't matter. The web server turns the DNS name/IP it's listening to into the website that is stored somewhere on the machine the webserver is running on. In other words, that's the thing working with the paths and directories and so on.

Web proxies are specially configured web servers that act as a gateway into a network by "proxying" other "normal" webservers which wouldn't be reachable otherwise.

Please don't mix them up, they are all different things that serve different purposes.

**Comment by Garbg** [comment]
> Ok, it seems you might have to do some reading about what DNS, web server, web proxy and so on are, what they are supposed to do and how they are working before you are setting something up that requires at least a basic understanding of these things.
> 
> I'm not saying don't set up AGH in your home network. But if you want to do some DNS manipulation with it (which is entirely possible to an extent), please make sure you understand what it is you're trying to do first or you'll end up disappointed.
> 
> And to teach you the basics of networking, this is the wrong platform I'm afraid.
> 
> Some pointers:
> 
> AGH is a DNS Proxy/Filter/Forwarder. Its purpose is to filter the DNS requests from your network or any connected device. It does not turn a DNS name (device.lan) into a website you can view on your browser. All it does is resolve the DNS name into its IP and return it to the device querying. (DNS rewrites included, which are nothing else but mapping a DNS name to an IP)
> 
> Webservers are services running on a device that provides a website you can view in your browser. They can listen to an IP or DNS name, doesn't matter. The web server turns the DNS name/IP it's listening to into the website that is stored somewhere on the machine the webserver is running on. In other words, that's the thing working with the paths and directories and so on.
> 
> Web proxies are specially configured web servers that act as a gateway into a network by "proxying" other "normal" webservers which wouldn't be reachable otherwise.
> 
> Please don't mix them up, they are all different things that serve different purposes.

I know all that. I'm just getting a bit confused as I'm not currently home so I'm not able to figure the stuff out

**Comment by Garbg** [comment]
All I really want is AGH to resolve my server.host to my servers ip. Lets say 127.0.0.1 for example. And then I could use a reverse proxy to allow me to connect to 127.0.0.1:8096 using 127.0.0.1/jellyfin. And then the final result would be connecting to my server.host/jellyfin would display the page hosted at 127.0.0.1:8096

**Comment by ppfeufer** [comment]
And that's the DNS rewrite part I mentioned [here](https://github.com/AdguardTeam/AdGuardHome/issues/5194#issuecomment-1327789118) and [here](https://github.com/AdguardTeam/AdGuardHome/issues/5194#issuecomment-1327793161).

**Comment by Garbg** [comment]
> And that's the DNS rewrite part I mentioned [here](https://github.com/AdguardTeam/AdGuardHome/issues/5194#issuecomment-1327789118) and [here](https://github.com/AdguardTeam/AdGuardHome/issues/5194#issuecomment-1327793161).

I know

**Comment by Garbg** [comment]
> > And that's the DNS rewrite part I mentioned [here](https://github.com/AdguardTeam/AdGuardHome/issues/5194#issuecomment-1327789118) and [here](https://github.com/AdguardTeam/AdGuardHome/issues/5194#issuecomment-1327793161).
> 
> I know

I just was getting confused

**Comment by Garbg** [comment]
I'll close it now
