### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by DeadSledge989** [AdguardTeam/AdGuardHome#5195]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
too bright screen at night
#### Proposed solution
add dark mode

**Comment by Disqu3-mirOir-qt** [comment]
#616

**Comment by Birbber** [comment]
We already have an issue on that matter. Closing as a duplicate.
