### ISSUE TITLE
Adguard Home Openwrt error version json

### ISSUE THREAD

**Issue by thursday15** [AdguardTeam/AdGuardHome#5199]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.19

### Description

Error: control/version.json | getting version info from https://static.adtidy.org/adguardhome/release/version.json: updater: HTTP GET https://static.adtidy.org/adguardhome/release/version.json: Get "https://static.adtidy.org/adguardhome/release/version.json": all upstreams failed to respond: 2 errors: "read udp 192.168.8.100:37711->8.8.4.4:53: i/o timeout", "read udp 192.168.8.100:49554->8.8.8.8:53: i/o timeout" | 502

this error effect to DNS changing every 15 minutes so that it makes it difficult to surf the internet and needs to be restarted

**Comment by ainar-g** [comment]
Apologies for a long time with no response.  This error means that your upstreams cannot resolve the addresses for AdGuard servers hosting the updates, see #5976.  You should try using other upstreams.
