### ISSUE TITLE
Please remove energized.pro blocklist.

### ISSUE THREAD

**Issue by Garbg** [AdguardTeam/AdGuardHome#5215]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Blocklist is currently empty
#### Proposed solution
Remove their blocklist. There is no reason to have it anymore
#### Alternatives considered
None
#### Additional information
Here is some more info: https://github.com/EnergizedProtection/block/issues/980

**Comment by ainar-g** [comment]
If still necessary, please open an issue on the <https://github.com/AdguardTeam/HostlistsRegistry> repo, as that is where AdGuard Home's list of vetter filters comes from.
