### ISSUE TITLE
Clearing /tmp on Ubuntu bootloops / bricks AGH

### ISSUE THREAD

**Issue by L8X** [AdguardTeam/AdGuardHome#5221]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Alpha

#### What did you do

Cleared /tmp directory to clean up cached files for another program 

#### Expected result

Doesn't break anything

#### Actual result

Bricks AGH and makes it constantly try to start and fail

#### Screenshots (if applicable)

Not Applicable.

#### Additional information

This is urgent.

**Comment by ainar-g** [comment]
It is [generally not safe](https://unix.stackexchange.com/a/11240/105635) to remove everything in `/tmp` without a reboot.  `systemd` in particular tends to store some service-related files in there, I think.  If you fell like there is still an issue here then please inspect the logs of AdGuard Home as well as `journalctl`.

**Comment by ainar-g** [comment]
The only part of AGH that seems to use `/tmp/` are the filtering updates, which definitely need more work.  We'll work on that in #5258, so I'll merge this issue into that one.
