### ISSUE TITLE
Adguard Home Unresponsive after List Updates

### ISSUE THREAD

**Issue by blauter** [AdguardTeam/AdGuardHome#5224]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

ARMv7

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b.21

### Description

AdGuard Home goes unresponsive frequently. Every single time its during list update.  

I only have these two lists enabled:
AdGuard DNS filter
OISD Blocklist Full

Nothing else in the logs except for these right when the issue occurs.
`Dec  1 11:46:46 bklrouter1 AdGuardHome[6885]: 2022/12/01 11:46:46.392134 [info] saving filter 1 contents to: /tmp/mnt/router_data/entware/etc/AdGuardHome/data/filters/1.txt
Dec  1 11:46:46 bklrouter1 AdGuardHome[6885]: 2022/12/01 11:46:46.492313 [info] updated filter 1: 1001426 bytes, 51454 rules
Dec  1 11:46:54 bklrouter1 AdGuardHome[6885]: 2022/12/01 11:46:54.687990 [info] saving filter 1668132868 contents to: /tmp/mnt/router_data/entware/etc/AdGuardHome/data/filters/1668132868.txt
Dec  1 11:46:55 bklrouter1 AdGuardHome[6885]: 2022/12/01 11:46:54.731044 [info] updated filter 1668132868: 5810932 bytes, 266928 rules
Dec  1 11:46:55 bklrouter1 AdGuardHome[6885]: 2022/12/01 11:46:55.001359 [info] Updated filter #1.  Rules: 51411 -> 51454
Dec  1 11:46:55 bklrouter1 AdGuardHome[6885]: 2022/12/01 11:46:55.001436 [info] Updated filter #1668132868.  Rules: 264704 -> 266928
`

**Comment by blauter** [comment]
Also, if I kill it and restart it, everything works fine.

**Comment by jamie-dit** [comment]
I'm also having similar issues since yesterday where AdGuard Home will stop responding to DNS queries. Issue is fixed after a reboot.

**Comment by U0101100** [comment]
I have the same problem with DNS Adguard , cannot set it up android dns in settings connection dns : cannot set up that parameters,  no connection or not properly entered data's . I copy past any data from adguard dns site .

**Comment by robinostlund** [comment]
I also have the same issue, it happens when it tries to update the list and when the list url is not responding properly it hungs so i have to restart my docker container running adguard.

**Comment by b255ea006** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/5459#issue-1572689749

I have an similar issue? Any advice?

**Comment by b255ea006** [comment]
> Also, if I kill it and restart it, everything works fine.

Hi @blauter 

Which command line do you use to kill and restart AGH?

**Comment by geoffrothman** [comment]
same issue; i'm in a docker image and have to restart it
