### ISSUE TITLE
Planned DHCP capabilities

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#523]
Just wondering what the planned future feature set is for the AGH DHCP server?

Features I'm hoping to see added include:

1. Support for MAC address reservations
2. Reporting on active/non-active reservations
3. Support for multiple IP ranges/multiple scopes (i.e. support non-contiguous IP blocks in the same subnet but also support multiple IP ranges that may have a different subnet mask and possibly different gateway/DNS/etc.)
4. Collision detection (if not already capable), i.e. detect if allocated IP already exists on the network.
5. DNS registration of clients

**Comment by ameshkov** [comment]
Thank you for the questions! We'll discuss it once I am back from vacations at the end of January, and see what we're going to do.

**Comment by ibksturm** [comment]
got some more idears: 

- posibility to do dhcp spezific option
example
dhcp option 6,192.168.0.2 (dns server)
dhcp option 3,192.168.0.1 (gateway)

https://tools.ietf.org/html/rfc2132

and as i wrote some months earlier, own hostfiles would be great
