### ISSUE TITLE
Getting error when accessing Adguard

### ISSUE THREAD

**Issue by chatbuddy21** [AdguardTeam/AdGuardHome#5231]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.19

#### What did you do?
Just open Adguard

#### Expected result
No error

#### Actual result
Error: control/version.json | getting version info from https://static.adtidy.org/adguardhome/release/version.json: updater: HTTP GET https://static.adtidy.org/adguardhome/release/version.json: Get "https://static.adtidy.org/adguardhome/release/version.json": x509: certificate has expired or is not yet valid: current time 2022-12-05T09:59:04+08:00 is after 2021-09-30T14:01:15Z | 502

#### Screenshots (if applicable)
![error](https://user-images.githubusercontent.com/38348868/205533493-de073403-4dc1-4ef7-b146-8c1e5af839d0.png)

#### Additional information
Installed on QNAP NAS 
https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.19/AdGuardHome_linux_amd64.tar.gz

**Comment by ainar-g** [comment]
Hello.  This was most likely a temporary error.  The certificate of the update server should be okay now.  Please let us know if that happens again.

**Comment by chatbuddy21** [comment]
Just upgraded to Version: v0.107.21 and still getting the same issue.

**Comment by sancome** [comment]
try this, i sloved it.
# yum install ca-certificates -y
# update-ca-trust force-enable
# reboot
