### ISSUE TITLE
Several Quality of life proposals.

### ISSUE THREAD

**Issue by LinuxMeow** [AdguardTeam/AdGuardHome#5233]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Introduction of several quality of life features for convenience to end user of the product.
#### Proposed solution
Adding ability for groups, configuration backup, improvement to statistics.
## Intro to groups proposals

It would be convenient, for the first feature in this list, for users to be able to assign groups and group different blocklist under different groups.

In example, for my own client I block all, I block even facebook, twitter tiktok, instagram, some custom list services as well etc. Which doesn't really suit the rest of my family still using these services. I do not wanna block them out just cause I want to block them on my own end. There is a thing in pihole which every blocklist can be assigned to certain group. Then you can block clients with groups that are good for them, and block other clients with the groups that suits others. There is no option to separate which client is getting which blocklist, they are universal across all the clients.

## Backups easy as 1 2 3 click import export

Secondly, there is no easy config backup functionality in adguard home web interface such as is the case for again... Pihole and teleporter feature. It would be more than needed to have export config and import config buttons in some advanced tab features or maintenance, where we can export configs of lists and other things adguard related. I think this is of the most importance, due to installations sometimes going brick and generally changing environment in a terms of switching OS etc, which prompts reconfiguring adguard from ground 0 up to final setup again. Now I am aware there might be (maybe) some way of backing up configs, through cli and stuff, but that is not convenient task for everyone using the product. Even me as linux user over 20 years and such a knowledge of cli this is a bit tedious task cause I need to hunt first where all the files are located on system tree, but also to know what each file I find represents and which ones I need to back up and which not. Very time consuming. And especially for new to linux users.

## Statistics need to be more robust and meaningful rather than being just cool graphics to look at

Lastly, home page with statistics needs a MAJOR redesign. With features like in pihole that show clients, client requests made, client blocks made, with easy block buttons next to domains that are not blocked (maybe even by mistake, just for quality of life.)

Now do not get me wrong that I reference pihole here to much but, hand on heart, some things adguard is nailing 10 times better than pihole. But these small quality of life things I think pihole is just doing better. Now my question is... Why not have the best things from the both worlds to make product the world class in the end.
#### Additional information
I hope this doesn't come to you as wrong bashing and misunderstanding why I am referrencing other project here. I do it just to point good things other projects do which are not in adguard, to encourage adguard team to create even better project which will be easy for many, with a lot of simple quality of life conveniences, but also easy for any other perople trying to transition from said products to adguard and feel just like at home.

The warmest greetings,

`LinuxMeow.`

**Comment by LinuxMeow** [comment]
We would also benefit from, `reboot adguard` button in ui. And this is so simple to implement, add button, call system command to reboot or reboot now. I would submit patch but my front end skills are terrible and that's why my websites look like circus show. But I know how it is done and how long it takes. Small change to benefit all. Now above mentioned groups can take anywhere 1 to 24 hours to implement, but I think they are CRUCIAL to implement, cause I do not want to block all the clients with the exact same set of blocklists. I might block all I need on my end. But some other people on my network need access to google, facebook, other services blocked that there is no switch for them to block.... I hope you get my point.

**Comment by ainar-g** [comment]
Good day.  Please don't write one issue for several feature proposals and please check the existing issues and feature requests for duplicates.

Better support for per-client filtering lists is #435.  Settings export is #1147 (and the discussion in #573 may help with the current workarounds).  Statistics improvements are #1453.  And the reboot button is #2677.

**Comment by benisai** [comment]
#435 is closed tho. When will client group filtering be added?
