### ISSUE TITLE
Configurable Query Log timestamp format

### ISSUE THREAD

**Issue by sinus-x** [AdguardTeam/AdGuardHome#5235]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

In Query Log, the dates are formatted as `M/D/YYYY`. While that is natural for US folks, it can be confusing for people outside, as we usually use some form of `D. M. YYYY`.

Both the system's and container's locale are set to `en_US.UTF_8`. But even when I added `LC_TIME=en_GB.UTF-8` to the container's environment, the format did not change, so I assume it is hardcoded or not respecting the environment variable.

#### Proposed solution

Add a dropdown to the configuration, or a free text field to add own format string.

#### Alternatives considered

Respect the `LC_TIME` environment variable.

#### Additional information

I have English l10n set in the UI. The version is v0.107.18.

**Comment by ainar-g** [comment]
Hello.  The UI uses the date-time format from the browser's locale, so the backend isn't to blame here.  You can check your browser's locale here: <https://www.localeplanet.com/support/browser.html>.  Mine has `navigator.language: en-GB` and a sensible `DD/MM/YYYY` date format, so you may want to change your browser's settings until the format looks good to you.

The feature request itself is a dup of #1498, so I'll close this one.
