### ISSUE TITLE
DNS Blocklist Error

### ISSUE THREAD

**Issue by Alyciazsa** [AdguardTeam/AdGuardHome#5237]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.19

#### What did you do?
Enable DNS Blocklist "List-KR"

#### Expected result
Blocklist working

#### Actual result
Error: control/filtering/add_url | Couldn't fetch filter from url https://github.com/List-KR/List-KR: data is HTML, not plain text | 400

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/97645837/206132242-cbc33a4e-9cdb-4b8e-9d5e-e86a4fd7c224.png)
![image](https://user-images.githubusercontent.com/97645837/206132278-6fa3d411-fc85-4c35-9d91-93a79b28247c.png)

**Comment by ainar-g** [comment]
Hello and thanks for the report.  This should be fixed in v0.107.20.  Unfortunately, the previous release used wrong URLs for the vetted blocklists, and you may need to re-add them to make sure that new, valid URLs are used.

**Comment by Alyciazsa** [comment]
updated to v0.107.20. but every enabled list become disabled.  re-added them and clear old list. now everything is working fine. Thank.
