### ISSUE TITLE
DoH set up [TLS and QUIC works]

### ISSUE THREAD

**Issue by rafalohaki** [AdguardTeam/AdGuardHome#5240]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.20

#### What did you do?
I try to enable doh 
#### Expected result
working doh
#### Actual result
tls and quic working but doh isnt
#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/20607107/206387576-3b63e016-53bf-4c3b-a3aa-58b8fd7c55f3.png)
![image](https://user-images.githubusercontent.com/20607107/206387580-f6fed30f-4c76-48a9-9561-25ecc9637cf6.png)
![image](https://user-images.githubusercontent.com/20607107/206387592-3794b722-167a-43a9-a12f-2ae4b20ea89e.png)
![image](https://user-images.githubusercontent.com/20607107/206387698-67ab74fc-875a-4012-8e4d-19c05833f83a.png)
#### Additional information

linux debian 11

**Comment by ainar-g** [comment]
Hello.  Which tool are you using to check if DoH works or not?  Can you reach your server using e.g. [`dnslookup`](https://github.com/ameshkov/dnslookup)?

Also, do you see any errors in the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?

Thanks.

**Comment by rafalohaki** [comment]
I was trying to add it to adguard client
![image](https://user-images.githubusercontent.com/20607107/206427525-57da2f89-9598-489f-b934-e2c3fdf79c1c.png)

**Comment by rafalohaki** [comment]
ok, i did recheck on nslookup
![image](https://user-images.githubusercontent.com/20607107/206431382-37a493ae-d499-42e2-a6a8-6cc63aa844a5.png)
something like that, right?

**Comment by rafalohaki** [comment]
should i bind panel to 443 port? have it like this
![image](https://user-images.githubusercontent.com/20607107/206435349-b44ba217-3103-4edd-b432-63aaf3e90d2d.png)

**Comment by ainar-g** [comment]
Yes, port 443 must be proxied to AdGuard Home.  Depending on the exact configuration of your deployment, that may or may not require you to change the `bind_host` to the address of another interface.
