### ISSUE TITLE
DNS Cache not working since v0.107.17

### ISSUE THREAD

**Issue by Mickur** [AdguardTeam/AdGuardHome#5241]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.20

#### What did you do?
I've tried both paths and neither of them is working as expected
* Updated from v0.107.16 (A bit unsure about this version but I usually upgrade when possible) to v0.107.17
* Clean install of v0.107.20

#### Expected result
DNS caching working

#### Actual result
Most (maybe all) requests goes through to upstream server

#### Additional information
Installed using the DietPi installer, which might be doing something weird. But there is at least one other person with the problem, as can be seen here https://www.reddit.com/r/Adguard/comments/you0vc/adguard_home_no_longer_caching_queries/

**Comment by Mickur** [comment]
Downgrading to v0.107.16 and then upgrading one release at a time seems to have fixed it for the moment. I have no clue why.

**Comment by Mickur** [comment]
I was wrong, something definitely happened with v0.107.17 that broke caching.

For example, running yt-dlp (which hammers DNS with youtube lookups for some reason) on v0.107.17 makes all the requests go through to the upstream server while v0.107.16 caches it correctly.

**Comment by Mickur** [comment]
![bild](https://user-images.githubusercontent.com/38385999/206433962-0c81b090-9ff0-45b9-8321-c61c7b575b96.png)

**Comment by ainar-g** [comment]
This is weird.  I'm on the latest version, and most queries seem to come from the cache.

If you look at the Query log, do most responses have a `(served from cache)` note on them?  Also, your cache size is below 1 MiB, which is rather small.  Does increasing it to at least 4 MiB (`4194304`) improve the situation in later versions?

**Comment by Mickur** [comment]
If I'm not mistaken, my cache size is double that. :)
Since I'm on version 16, requests are served from cache. On 17+ it's all from upstream.

**Comment by Mickur** [comment]
![bild](https://user-images.githubusercontent.com/38385999/206440737-052493ac-e3e5-4163-8aad-3fe8c1a10a11.png)
On v0.107.16 I'm getting results like these when running yt-dlp

**Comment by Mickur** [comment]
![bild](https://user-images.githubusercontent.com/38385999/206441099-16456f7a-eae8-4460-8ba7-9c25afc10d0a.png)
And on v0.107.17 it looks like this. Not from cache.

**Comment by ainar-g** [comment]
Oh, my bad, you're right about the size.  Thanks for the screenshots.  If you don't mind, which upstreams are you using?  Does the problem persist if you switch to another upstream server?

@EugeneOne1, I've checked, and it seems that we've changed some TTL logic in the cache between those two releases.  Please investigate.

**Comment by Mickur** [comment]
I'm currently using CloudFlare ZeroTrust (https://xxxxxxxxxxxxxx.cloudflare-gateway.com/dns-query)
Changing it to regular google (8.8.8.8) doesn't help.

**Comment by EugeneOne1** [comment]
@Mickur, could you please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  It would really help us to troubleshoot the issue.  You may send it to the devteam@adguard.com.

**Comment by Mickur** [comment]
It should now be in your inbox! Good luck!

**Comment by EugeneOne1** [comment]
@Mickur, hello again.  After a little investigation it turned out that we indeed changed some caching logic in `v0.107.17`.  Particularly AdGuard Home stopped caching the queries with CD (DNSSEC Checking Disabled) bit set due to possible cache poisoning (#4942).  You may want to look into configurations of the used resolvers to enable DNSSEC validation (make them not set the CD bit).

**Comment by Mickur** [comment]
I was under the impression that DNSSEC is used by default when using Cloudflare or Cloudflare Zero Trust. I can only find options to disable DNSSEC, and they are not activated.

**Comment by Mickur** [comment]
![bild](https://user-images.githubusercontent.com/38385999/206684662-a5ae3b06-057a-476d-908e-3147dddf3c79.png)
This is on version 16, and I am getting some requests validated by DNSSEC.

**Comment by ainar-g** [comment]
@Mickur, Eugene means that either the tool you're using (`yt-dlp`) or your OS's resolver is sending queries with the CD bit.  You can see it in your verbose logs:

```none
;; flags: rd cd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
```

Whenever the `flags:` field contains `cd`, this means that DNSSEC check is disabled, and so AGH cannot cache those queries.

**Comment by Mickur** [comment]
Well, that's sad. I guess I'm stuck on version 16 then.

**Comment by ainar-g** [comment]
I don't see if you've mentioned the type of Linux OS you're using, but either way, there is perhaps a way to disable that behaviour, if we assume that it is indeed the OS resolver that sets the bit.

We'll close the issue for now, if you don't mind.

**Comment by Mickur** [comment]
Some requests still do get cached with the newer versions, so I don't know what would be the best way to track down the problem.
I'm running AdGuard Home on DietPi in a VM. I would assume that would be a Debian distro.

**Comment by Mickur** [comment]
Actually, it seems like most of the "regular" requests do get cached. Looks like yt-dlp is the main culprit here. Thanks for the help!

**Comment by Mickur** [comment]
Well, that was interesting. Not using the --force-ipv4 in yt-dlp flag seems to have fixed the issue.
For anyone else having the same problem, well, here you go!

**Comment by andylau004** [comment]
@Mickur 
I had the same problem

1. when i check my doh client code。 i find client request set cd=1.
2. then doh server unpack request, if find CD option being set, then doh server will disable cache,like below pic, i dont why


![image](https://github.com/AdguardTeam/AdGuardHome/assets/2648844/665ab494-e934-4e7c-857d-a9f03203e340)



@Mickur @ainar-g
