### ISSUE TITLE
Minimal rule length should not be applied to `*` in the hostname mask

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#5245]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.391+09f88cf2

#### What did you do?

Trying to block requests from all devices, except clients from the list.

#### Actual result

The rules with AdGuard ad blocker syntax with `*` or empty host(url) part do not work
`$client=~'Allowed client'`
`*$client=~'Allowed client'`

A similar rule with few `*` is working
****$client=~'Allowed client'

Probably this is caused by a minimal rule length(3 symbols, as I see. In ad blockers - 4 symbols.)

#### Expected result

These rules must work

```
`$client=~'Allowed client'`
`*$client=~'Allowed client'`
```

**Comment by ameshkov** [comment]
It should depend on the rule modifiers. Of course it should not be applied when there's a `$client` modifier, but when there're no modifiers at all I think we still should.

**Comment by ameshkov** [comment]
Fixed in urlfilter v0.16.1

**Comment by ainar-g** [comment]
This will be released in the upcoming v0.107.23.  Sorry it took too long.
