### ISSUE TITLE
Error when saving configuration 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardHome#5251]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.20

#### Steps to reproduce 
1. In the DNS settings change upstream to tls://1.1.1.1
2. Open the encryption settings screen 
3. Mark the "Enable Encryption" checkbox
4. Mark the "Redirect to HTTPS automatically" 
5. Add the valid certificate and key 
6. Click the "Save configuration" button 

#### Expected result
Configuration saved successfully, encryption enabled 
#### Actual result
`Error: control/tls/configure | starting forwarding dns server: could not reconfigure the server: closing primary resolvers: stopping dns proxy server: failed to close some upstreams: failed to close some connections: 3 errors: "tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 192.XXX.XX.XXX:35292->1.1.1.1:853: write: broken pipe", "tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 192.XXX.XX.XXX:35304->1.1.1.1:853: write: broken pipe", "tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 192.XXX.XX.XXX:38572->1.1.1.1:853: write: broken pipe" | 500`

**Comment by ainar-g** [comment]
I've seen the same in Cache settings.

**Comment by pendie** [comment]
same

**Comment by Eyeborgs** [comment]
@EugeneOne1 The problem has disappeared

**Comment by monkitrainer** [comment]
@EugeneOne1 looking good. Thanks!

**Comment by EugeneOne1** [comment]
It seems, Snap builds are loaded as well.

**Comment by Commy** [comment]
@EugeneOne1 Working without issue so far. Thanks for addressing it!
