### ISSUE TITLE
Cannot enable DHCP server using UI

### ISSUE THREAD

**Issue by yehoshuadimarsky** [AdguardTeam/AdGuardHome#5256]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.20

#### What did you do?
Installed AGH on a Raspberry Pi (4 Model B Rev 1.1) running Debian Bullseye 64 bit, using the install script in the github readme. Unfortunately my router doesn't let me set DNS directly, so I have to set the DHCP server. I already have this set up working with PiHole, and I'm trying to upgrade it to use AGH. But when I go to the DHCP page, the button is "greyed out", it doesn't let me click it to enable it. When I check for existing DHCP it gives me the error/warning message.

Similar to https://github.com/AdguardTeam/AdGuardHome/issues/3289 but I don't see a fix there. Also found this https://github.com/hassio-addons/addon-adguard-home/issues/73 but not helping.

I also cannot set any of the settings for DHCP, like the gateway etc.

#### Expected result
I can use the web UI to enable DHCP

#### Actual result
Web UI does not let me enable DHCP

#### Screenshots (if applicable)
<img width="657" alt="image" src="https://user-images.githubusercontent.com/24758845/206890012-8b8d5203-780c-493c-b8ce-3963277d0194.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/24758845/206890027-40735b91-75c6-4738-87ea-2a22991dbaf0.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/24758845/206890038-57eb230d-bb34-40f6-91d3-62b4ea2f776b.png">

#### Additional information
I originally was using it inside Docker on the Pi, thought that was the issue. But even on bare metal getting this issue.

**Comment by ainar-g** [comment]
Hello.  Just to be clear, did you fill the rest of the fields?  That is, *Range of IP addresses* and others?
