### ISSUE TITLE
It would be great if adguard home could support txt records

### ISSUE THREAD

**Issue by markussiebert** [AdguardTeam/AdGuardHome#5268]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I am using adguard home as my dns server in my lab. So far so good. It would be nice, if I could use [external dns](https://github.com/kubernetes-sigs/external-dns) with adguard home and would like to implement the "extension". But for full functionality, adguard must allow creation of txt records (as they hold the state for external dns)

#### Proposed solution
Allow txt records

#### Alternatives considered
none

#### Additional information
none

**Comment by fernvenue** [comment]
You can create TXT record in Custom filtering rules like this:

```
example.com$dnstype=TXT,dnsrewrite=NOERROR;TXT;example
```

That's quite simple, read [the docs](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists) for more information about that feature.

**Comment by ainar-g** [comment]
See also #5266.

**Comment by markussiebert** [comment]
Thank you a lot! This works! I searched the docs for txt and the issues but didn't found anything. So I will try to create an external dns integration.
