### ISSUE TITLE
Block RIOT GAMES launcher

### ISSUE THREAD

**Issue by gajotnt** [AdguardTeam/AdGuardHome#5269]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
The same way we can block EPIC, STEAM, ORIGIN, theres also RIOT GAMES, that installs League of Legends, Valorant, TFT
https://www.riotgames.com/en

#### Proposed solution
Add the Service to your blockable services

**Comment by ainar-g** [comment]
The list of blocked services is taken from the [Hostlists Registry][1].  Please file such issues there.  Thanks.

[1]: https://github.com/AdguardTeam/HostlistsRegistry
