### ISSUE TITLE
Cannot add Tspprs filter lists.

### ISSUE THREAD

**Issue by ugaugabuga** [AdguardTeam/AdGuardHome#527]
### Steps to reproduce

1. Go to Filters>Add filter
2. Enter a name
3. Type https://tspprs.com/dl/cl1 in url box and click add filter. 

### Expected behavior

The filter should be added to AG home.
### Actual behavior

Adding the filter fails with the following message "Error: control/filtering/add_url | Couldn't fetch filter from url https://tspprs.com/dl/cl1: non-text response | 400"

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46380770/50699527-5501ac80-1072-11e9-9474-af0e0453d49e.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92
| How did you setup DNS configuration:| 
| If it's a router or IoT, please write device model:| 
| Operating system and version:|

**Comment by planet0** [comment]
> This header is missing in this case so that's why. In order to fix this issue, we'll have to come up with another way of checking the filter list content.

Would be good, currently unable to add Disconnect, MinimalHostsBlocker, and others due to this.

**Comment by rapdodge** [comment]
Yeah, v0.94 still have this issue, i hope fix soon :D

**Comment by miwagner1** [comment]
A bunch of filters from https://firebog.net suffer from this issue

**Comment by jamieshaw** [comment]
Just adding that this is also an issue for me, having recently migrated to AGH from Pi-hole.

Looking forward to a fix.
