### ISSUE TITLE
updater: invalid PackageURL error

### ISSUE THREAD

**Issue by siavashs** [AdguardTeam/AdGuardHome#5270]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

32-bit MIPS LE

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.20

#### What did you do?
- Stopped the service `./AdGuardHome -s stop`
- Ran update `./AdGuardHome --update`
#### Expected result
AdGuardHome to perform the update.
#### Actual result
The update fails with `updater: finished; errors: invalid PackageURL`:
```
./AdGuardHome --update
2022/12/15 17:12:55.682598 [info] AdGuard Home, version v0.107.20
2022/12/15 17:12:55.746224 [info] tls: using default ciphers
2022/12/15 17:12:55.791702 [info] Initializing auth module: /config/AdGuardHome/data/sessions.db
2022/12/15 17:12:55.793107 [info] auth: initialized.  users:1  sessions:1
2022/12/15 17:12:55.818225 [info] tls: number of certs: 3
2022/12/15 17:12:55.818616 [info] tls: got an intermediate cert
2022/12/15 17:12:55.819374 [info] tls: got an intermediate cert
2022/12/15 17:12:56.393899 [info] web: initializing
2022/12/15 17:12:56.750807 [info] DNS cache is enabled
2022/12/15 17:12:56.751026 [info] MaxGoroutines is set to 300
2022/12/15 17:12:56.769921 [info] starting update
2022/12/15 17:12:57.537672 [info] updater: updating
2022/12/15 17:12:57.540487 [info] updater: finished; errors: invalid PackageURL
2022/12/15 17:12:57.540658 [fatal] invalid PackageURL
```
#### Additional information
The host is an EdgeRouter X.

**Comment by Mizzick** [comment]
Hello!

Please try update with verbose flag to get more details:
`$ ./AdGuardHome -v --update`

**Comment by ainar-g** [comment]
We're going to close this issue for now.  If any of you still have the issue in v0.107.26, please open a new issue.
