### ISSUE TITLE
Compliment - not a problem

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#5279]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

adguardhome:edge

### Description

go-acme/lego and aghome.. 

Thank you.. 

enabled serve_http3: true in the config.. did not see a gui toggle for it

![image](https://user-images.githubusercontent.com/55087301/208311774-cae1b1ae-1c24-4f4f-952f-64aa977be715.png)

![image](https://user-images.githubusercontent.com/55087301/208311810-534c6ea1-825f-4bd9-a068-446e4a598d50.png)

**Comment by DandelionSprout** [comment]
Good to hear, at least. 🌞
