### ISSUE TITLE
Duplicated lines

### ISSUE THREAD

**Issue by Piber0** [AdguardTeam/AdGuardHome#5280]
https://github.com/AdguardTeam/AdGuardHome/blob/307654f648ede191966b5efca6556eb80f554d12/internal/filtering/blocked.go#L240 is the same line as https://github.com/AdguardTeam/AdGuardHome/blob/307654f648ede191966b5efca6556eb80f554d12/internal/filtering/blocked.go#L250

**Comment by EugeneOne1** [comment]
@Piber0, hello.  These rules are actually generated automatically from the [HostlistsRegistry](https://github.com/AdguardTeam/HostlistsRegistry/) repo in the newer releases.  However, the duplicate rules are removed during the engine's compilation thus having no performance overhead at all.
