### ISSUE TITLE
ads

### ISSUE THREAD

**Issue by kidsam999** [AdguardTeam/AdGuardHome#5284]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

latest

**Comment by Dynasty-Dev** [comment]
????????????????????????

**Comment by Birbber** [comment]
Hello. This issue doesn't include any details. Please fill the form properly so we can understand the issue you've faced.
