### ISSUE TITLE
"Application error" log file errors causes DoQ to fail to initialise

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#5285]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.24

#### What did you do?

For unclear reasons, setting a DoQ port in Encryption Settings causes a couple dozen `[info] got error when accepting a new QUIC stream: APPLICATION_ERROR` and `[info] got error when accepting a new QUIC stream: Application error 0x1` errors in the log file when "Save configuration" is clicked or when AGH is starting up. 

#### Expected result

Setting a QUIC port, makes AGH initiate its DoQ functionality without problems.

#### Actual result

Not only does setting a QUIC port fail at initiating DoQ functionality, but it also causes direct IP DNS connections to the server to get stuck and time out.

#### Screenshots (if applicable)

N/A

#### Additional information

[AdGuardHomeLogFile.txt](https://github.com/AdguardTeam/AdGuardHome/files/10265246/AdGuardHomeLogFile.txt) (Focus especially on the part from `2022/12/20 05:14:11.157532` - `2022/12/20 05:14:30.624020`, which was when I tested the problem specifically for this issue report by setting a QUIC port.)

**Comment by DandelionSprout** [comment]
IP connections seem to work nowadays, but QUIC still results in that error.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/22780683/c338e048-eb8f-49fb-9eca-a0bf4dc8b242)

**Comment by ainar-g** [comment]
Apologies for this issue slipping through our attention.  If you enable verbose log, do you see `[debug]` messages like:

```none
closing quic conn … with code …
```

If so, at least a part of those logs are probably from 0-RTT rejection from upstreams or a short read from a QUIC client, which really shouldn't produce this much messaging.

@Mizzick, we'll probably need better error processing in QUIC servers and upstreams in the DNS proxy module.

**Comment by DandelionSprout** [comment]
I am indeed getting errors pretty similar to what you described, now that I've tested with verbose:
```
2023/06/23 11:42:25.436780 14368#13370 [error] accepting quic stream: APPLICATION_ERROR (remote)
2023/06/23 11:42:25.436780 14368#13370 [debug] closing quic conn [::]:41396 with code 0
```

**Comment by ainar-g** [comment]
@DandelionSprout, thanks!  It would really help us if you posted a longer log either here or to <devteam@adguard.com>.  That `with code 0`, at the very least, looks weird, and there may be more weird codes.

**Comment by DandelionSprout** [comment]
Okay, I think I've sent it to that E-mail address now (provided it can receive an 8.5 MB attachment).

**Comment by Mizzick** [comment]
@DandelionSprout, please check the latest `v0.108.0-a.585+c652653e` version in the edge channel.

**Comment by DandelionSprout** [comment]
I'll see if I can do so this weekend.

**Comment by ainar-g** [comment]
Just to be clear, the most recent Beta release also includes the fix.

**Comment by DandelionSprout** [comment]
The in-GUI query log seems to imply that DoQ does work properly in b.38 (and that it works alongside all the other DNS connection methods as well). So it seems this can be closed for the time being, and I thank you all for the help with it.
