### ISSUE TITLE
How to use Quad101 as the Upstream DNS servers? (question)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#529]
https://101.101.101.101/index_en.html

Quad101 DNS supports DoT.
https://blog.twnic.net.tw/2018/07/02/1086/

$ kdig +tls-host=101.101.101.101 @101.101.101.101 twnic.net.tw. a
;; TLS session (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 59758
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR

;; QUESTION SECTION:
;; twnic.net.tw.                IN      A

;; ANSWER SECTION:
twnic.net.tw.           3599    IN      A       124.9.9.9

;; Received 57 B
;; Time 2018-06-29 13:22:24 CST
;; From 101.101.101.101@853(TCP) in 26.7 ms

$

But it's failed if I input the below and test upstreams in AG Home.
tls://101.101.101.101
tls://101.102.103.104

Why?

Oops...
Only tls://101.102.103.104 has the issue.
It seems that only 101.101.101.101 supports DoT, but 101.102.103.104 doesn't support DoT.
Sorry.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NA351mt.png)
</details><br/>

**Comment by Yuan573** [comment]
I also face the same problem.
I use `https://dns.twnic.tw/dns-query` and ` tls://101.101.101.101` now.

**Comment by lancelot-moon** [comment]
Maybe its secondary DNS **101.102.103.104** doesn't support DoT.**
Only its primary DNS **101.101.101.101** supports DoT.

**Comment by ameshkov** [comment]
```
tls://101.101.101.101
https://dns.twnic.tw/dns-query
```

Both of these work okay
