### ISSUE TITLE
Upstream usage statistics

### ISSUE THREAD

**Issue by rafalohaki** [AdguardTeam/AdGuardHome#5293]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Hello,
Im using parallel requests, im not sure but it seems logs showing which dns is used the most because its faster than others?
Would be nice to have statistics showing ranking of upstream used and  if one of my upstreams is even used from list.
![image](https://user-images.githubusercontent.com/20607107/209439453-186e905e-75e8-4998-9d23-d5cc8e07d888.png)
for example in logs i hardly see `dns https://blitz.ahadns.com` being used 
so if statistics could show me that its so rare being used i could remove it from the list

**Comment by Disqu3-mirOir-qt** [comment]
in linux easy 


grep "upstrream_adresss" querylog.json | wc -l

**Comment by rafalohaki** [comment]
> in linux easy
> 
> grep "upstrream_adresss" querylog.json | wc -l

i meant something like this
![image](https://user-images.githubusercontent.com/20607107/209444987-0701ff63-391e-46b5-b351-ed441cf58e84.png)

**Comment by whyisthisbroken** [comment]
> in linux easy
> 
> grep "upstrream_adresss" querylog.json | wc -l

Tell me more how... i dont get it work... is this a script ?

**Comment by ainar-g** [comment]
We've added this on the Edge channel while working on #1453.  Merging into that one.

@rafalohaki, you can test the feature on the Edge channel now.

**Comment by rafalohaki** [comment]
> 

thank you very much!
