### ISSUE TITLE
AG Home caused Windows 10 crashed.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#530]
When I was running AG Home and browsing on internet for some time (after several tens minutes), my Windows 10 would almost crash every time.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/gJePPor.jpg)
</details><br/>

stopcode: DPC_WATCHDOG_VIOLATION

Andrey taught me to use the command, "adguardhome.exe -v > log.txt".
But the log.txt is 0 KB (empty).

How can I help if you need the log file?
Thanks.

**Comment by ameshkov** [comment]
> stopcode: DPC_WATCHDOG_VIOLATION

This code indicates that the problem is inside one of your kernel drivers, the operation inside it took too much time. So I guess AG Home could somehow trigger it, but it's not the real cause.

Can you find the minidump?

**Comment by lancelot-moon** [comment]
Hi,
I had sent the .dmp file to you on telegram after I reproduced the issue.

**Comment by ameshkov** [comment]
The crash happens in GlassWire network driver:
http://www.osronline.com/dump/DA2.cfm

DPC_WATCHDOG_VIOLATION means that some operation there took more time than it is allowed.

This needs to be reported to GlassWire.

**Comment by lancelot-moon** [comment]
It seems that the issue occurred with GlassWire v2.1.140 on Windows 10.
Before I reported the issue to GlassWire, GlassWire v2.1.152 was released.
After updating to GlassWire v2.1.152, everything is ok.

**Comment by lancelot-moon** [comment]
AG Home with Bitdefender firewall or old GlassWire firewall v2.1.140 will cause Windows 10 to crash.

I had disabled Bitdefender firewall.
Before, AG Home never caused Windows 10 to crash with the latest GlassWire firewall v2.1.152.
But Windows 10 suddenly and rarely crash today with AG Home and GlassWire firewall v2.1.152.

By telegram, I will send you the file under C:\windows\minidump\.
May you check it?

Thanks.

**Comment by ameshkov** [comment]
@lancelot-moon here's a nice online tool for minidumps analysis:
http://www.osronline.com/page.cfm?name=Analyze

The crash is caused by glasswire again.

**Comment by ameshkov** [comment]
> AG Home never caused

AG Home never caused or cause any crashes simply because it cannot. 

It works in "user" space and the cause of a BSOD is always something (a driver) working in "kernel" space.

**Comment by lancelot-moon** [comment]
Thanks for the useful tool, which lets me analyze by myself.
Sorry to bother you.

**Comment by ameshkov** [comment]
@lancelot-moon yeah, that's your dump:
http://www.osronline.com/dump/DA2.cfm

Scroll down to the end of the stack trace, you'll find `gwdrv` there, that's glasswire driver.
