### ISSUE TITLE
Loss DNS Function When Enabling Use AdGuard browsing Security Web Service

### ISSUE THREAD

**Issue by begundal** [AdguardTeam/AdGuardHome#5327]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

v0.107.21

### Description
Linux Armbian 22.11.1 Jammy on FriendlyARM ZeroPi

#### What did you do?
Enabling Use AdGuard browsing Security Web Service causing loss dns resolver

#### Additional information
from https://dns.adguard.com/info.txt
dns2-dp-jhn-1

**Comment by begundal** [comment]
perhaps similar to #3029 and #3593

**Comment by gajotnt** [comment]
Same here.

**Comment by zhqu1148980644** [comment]
Same here, the ADGH DNS server is dead(Time out) when the security check server is unavailable.

System: openwrt 22.03.3
ADGH: v0.107.21

Solution: disable/uncheck 'Use AdGuard browsing security web service' in adgh dashboard general settings.

Logs:
`
Fri Aug 18 19:58:05 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:05.091776 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "netease.com": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGUwMTcCc2IDZG5zB2FkZ3VhcmQDY29tAAAQAAE": read tcp 111.79.255.228:64690->94.140.14.15:443: read: connection reset by peer
Fri Aug 18 19:58:08 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:08.965834 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "netease.com": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGUwMTcCc2IDZG5zB2FkZ3VhcmQDY29tAAAQAAE": read tcp 111.79.255.228:10280->94.140.14.15:443: read: connection reset by peer
Fri Aug 18 19:58:09 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:09.896217 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "netease.com": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGUwMTcCc2IDZG5zB2FkZ3VhcmQDY29tAAAQAAE": read tcp 111.79.255.228:10344->94.140.14.15:443: read: connection reset by peer
Fri Aug 18 19:58:10 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:10.375767 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "mainnet.infura.io": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDQwNjIENjk5YgJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
Fri Aug 18 19:58:10 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:10.949992 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "netease.com": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGUwMTcCc2IDZG5zB2FkZ3VhcmQDY29tAAAQAAE": read tcp 111.79.255.228:10356->94.140.14.15:443: read: connection reset by peer
Fri Aug 18 19:58:12 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:12.633189 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "mainnet.infura.io": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDY5OWIENDA2MgJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": read tcp 111.79.255.228:10508->94.140.14.15:443: read: connection reset by peer
Fri Aug 18 19:58:12 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:12.637522 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "mainnet.infura.io": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDQwNjIENjk5YgJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": read tcp 111.79.255.228:10530->94.140.14.15:443: read: connection reset by peer
Fri Aug 18 19:58:13 2023 daemon.err AdGuardHome[12710]: 2023/08/18 11:58:13.677074 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "mainnet.infura.io": safe browsing: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDQwNjIENjk5YgJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": read tcp 111.79.255.228:10624->94.140.14.15:443: read: connection reset by peer
`
