### ISSUE TITLE
Unable to enable DHCP on TrueNAS

### ISSUE THREAD

**Issue by gmcdon** [AdguardTeam/AdGuardHome#5330]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.21

### Description

When completing a fresh install of AdGuard on TrueNAS, it is impossible to enable built-in DHCP service.  When trying to save settings, you receive the following error message:

_Error: control/dhcp/set_config | enabling dhcp: starting dhcp server: dhcpv4: creating raw udp connection: open /dev/bpf0: no such file or directory | 400_
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/122064952/210906727-e158d3c4-b9d5-429a-bc8a-7b93a25f6b86.png">

With TrueNAS within a jailed environment, you do not have permissions to modify the _**/dev/**_ directory.  Config/setup would need to be changed to a tmp directory or default install dir of AdGuard
<img width="440" alt="image" src="https://user-images.githubusercontent.com/122064952/210907461-02f881b1-4c21-41e0-a312-af1cec9d5b76.png">

**Comment by bcookatpcsd** [comment]
https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#dhcp

```
[DHCP server](https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#dhcp)

If you want to use AdGuardHome's DHCP server, you should pass --network host argument when creating the container:

docker run --name adguardhome --network host ...

This option instructs Docker to use the host's network rather than a docker-bridged network. Note that port mapping with -p is not necessary in this case.
```

I think you would need the bsd jail equivalent if such a thing existed..  

possibly mounting the interface within the jail.. (devfs, etc..) 

my 0.02

**Comment by bcookatpcsd** [comment]
I was trying to offer a solution for the OP.

I'm good with docker and standalone installs..
