### ISSUE TITLE
Clients are not displayed

### ISSUE THREAD

**Issue by LookinTVB** [AdguardTeam/AdGuardHome#5338]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Добрый день, имеется vps на нем установлен wireguard и а adguard, подключены 2 устройства, но в списке клиентов показывает только один ip адрес, и все остальные устройства определяет на один и тот же ip адрес, в чем может быть проблема? как сделать что бы новое устройство отображалось в списке клиентов под своим ip адресом?
![image](https://user-images.githubusercontent.com/98187452/211186111-be1bc996-0c7c-48e0-80eb-c51fe838cfee.png)

**Comment by wwng2333** [comment]
Try to use DoH 
https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid
