### ISSUE TITLE
AdGuard filtered videos on youtube

### ISSUE THREAD

**Issue by knoebi** [AdguardTeam/AdGuardHome#5342]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.21

#### Expected result
With AdGuard Home as DNS-Server some YouTube-Video in Playlists from Youtubers is missing!!

#### Actual result
Change to P*-H*l* everything works fine.
Filtered  Videos inside a YT-Channel is a no go. That is no DNS anymore.

#### Additional information
Here is the channel that i used.
https://www.youtube.com/@TisiSchubech/videos

**Comment by chatbuddy21** [comment]
Is "use safe search" on? What filters are you using?

**Comment by knoebi** [comment]
All General Settings are activated.
My Blocklists:
https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt (Dan Pollock)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt (Steven Black)

I've disabeled all Blocklist with the same result.

**Comment by Harvester57** [comment]
Then try disabling safe search and parental control:

![image](https://user-images.githubusercontent.com/7060295/212496299-d5d5f84b-858c-4b4a-b606-14ffa47ce9f4.png)

**Comment by knoebi** [comment]
@Harvester57 - That was the trick. Thank you.
