### ISSUE TITLE
Comments in ipset_file

### ISSUE THREAD

**Issue by NoAdO** [AdguardTeam/AdGuardHome#5345]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I'm trying to add comments to /ipset.conf to organise rules. Neither
```
myip.ru/bypass # test
```
nor
```
myip.ru/bypass
# test
2ip.ru
``` 
work. In both cases i got dead service at Entware:
```
~ # nano /opt/etc/AdGuardHome/ipset.conf
~ # /opt/etc/init.d/S99adguardhome restart
 Starting AdGuardHome...              done.
~ # /opt/etc/init.d/S99adguardhome status
 Checking AdGuardHome...              dead.
```

#### Proposed solution
Any way to add comments

#### Additional information
AdHome v0.107.21 at Entware in Keenetic router 
[Related Wiki-article](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration), page search ipset_file
[No discussions](https://github.com/AdguardTeam/AdGuardHome/discussions?discussions_q=ipset_file) for filter ipset_file

**Comment by NoAdO** [comment]
`myip.ru/bypass,bypass6 #test`

`myip.ru/bypass,bypass6
#test
windguru.cz/bypass,bypass6`

`windguru.cz/bypass,bypass6
;test
myip.ru/bypass,bypass6`

`windguru.cz/bypass,bypass6 ;test`
All fail. Yes, problem still exists. No comments allowed or i do not know how to mark them.

**Comment by schzhn** [comment]
Support for comments in the ipset file available in the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions).
```
# comment
example.com/example_set
```
