### ISSUE TITLE
Domain-only filter lists support

### ISSUE THREAD

**Issue by furunos** [AdguardTeam/AdGuardHome#535]
When adding il.com to the blocking rule, gmail.com is blocked and in trouble.

**edit (by ameshkov)** see this comment for the details: https://github.com/AdguardTeam/AdGuardHome/issues/535#issuecomment-452489005

**Comment by furunos** [comment]
I suggest adding the following code.

```
dnsfilter/rule_to_regexp.go
@@ -1,11 +1,13 @@
 package dnsfilter
 
 import (
+	"regexp"
 	"strings"
 )
 
 func ruleToRegexp(rule string) (string, error) {
 	const hostStart = `(?:^|\.)`
+	const hostStartNoSub = `^`
 	const hostEnd = `$`
 
 	// empty or short rule -- do nothing
@@ -23,6 +25,12 @@
 	if rule[0] == '|' && rule[1] == '|' {
 		sb.WriteString(hostStart)
 		rule = rule[2:]
+	} else {
+		sb.WriteString(hostStartNoSub)
+		ruleRegexp := regexp.MustCompile(`[a-zA-Z]$`)
+		if ruleRegexp.MatchString(rule) {
+			rule += `^`
+		}
 	}
 
 	for i, r := range rule {
```

**Comment by ameshkov** [comment]
You need to add `||il.com^` if you want to block `il.com` and its subdomains

**Comment by furunos** [comment]
If you use the following filter, AGH will block "gmail.com" because "il.com" is written.

https://v.firebog.net/hosts/Airelle-hrsk.txt

**Comment by furunos** [comment]
If I use a domain only filter like "il.com", AGH blocks by domain partial match. Therefore, the AGH blocks domains not intended by the user. This is inconvenient because many filters that are published can not be used.

**Comment by furunos** [comment]
```il.com``` = ```||il.com```

Do not you assume that "il.com" and "|| il.com" are the same ? This can reduce the number of wrong blocks by domains list. Implementation is also simple.

```
dnsfilter/rule_to_regexp.go
@@ -20,8 +20,9 @@
 
 	var sb strings.Builder
 
+	sb.WriteString(hostStart)
 	if rule[0] == '|' && rule[1] == '|' {
-		sb.WriteString(hostStart)
 		rule = rule[2:]
 	}
```

**Comment by Apexgh0st** [comment]
Some Domain-only filter lists would have "#" or sometimes "$" at the start for notes ex. https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt . Just wondering if those special characters would conflict your syntax rules in the future (I'm not familiar with adguard syntax/adblock rules).

**Comment by ameshkov** [comment]
No prob, these lines will be discarded.

**Comment by szolin** [comment]
AGH v0.103 doesn't block `gmail.com` in case `il.com` rule is active.
