### ISSUE TITLE
Backup and import of function settings

### ISSUE THREAD

**Issue by woyaozuoai** [AdguardTeam/AdGuardHome#5350]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

The program lacks backup and import of setting parameters

Each reinstallation requires reconfiguring the relevant functions

I hope the author can add this function to facilitate rapid deployment settings

**Comment by Birbber** [comment]
Hello! Thanks for the suggestion. Looks like it's related to #1147. Will close this one as a duplicate.
