### ISSUE TITLE
AdguardHome stops working after a few hours

### ISSUE THREAD

**Issue by kiamgrebgnur** [AdguardTeam/AdGuardHome#5352]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.21

### Description

Hi,

I'm using 2 AdguardHome instances, both v0.107.21.
One is a plugin in home assistant which is working fine. One is running as docker container on Debian GNU/Linux 11 (bullseye) where I have strange issues since a few days.
Everything works fine at start but until a few hours the service doesn't answer any dns requests. If I restart the container it works again until a few hours. Even if I disable the Protection this happens. 
Last time was this night at around 2:00 with no error logs (verbose is set to true).

Log just shows that there is only status checking:

> 2023/01/11 02:08:42.707857 1#59781 [debug] applying filters: looking for client with ip 192.168.1.18 and clientid ""
> 2023/01/11 02:08:42.708089 1#59781 [debug] applying filters: no clients with ip 192.168.1.18 and clientid ""
> 2023/01/11 02:08:42.708325 1#59781 [debug] hosts container: handling the request
> 2023/01/11 02:08:42.708619 1#59781 [debug] dnsproxy: cache: serving cached response
> 2023/01/11 02:08:42.708858 1#59781 [debug] client ip: 192.168.1.18
> 2023/01/11 02:08:43.833024 1#59782 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(): Start handling new UDP packet from 192.168.1.16:58205
> 2023/01/11 02:08:43.833064 1#59782 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 1316
> ;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
> ;; QUESTION SECTION:
> ;checkonline.home-assistant.io.       IN       A
> 2023/01/11 02:08:43.833123 1#59782 [debug] applying filters: looking for client with ip 192.168.1.16 and clientid ""
> 2023/01/11 02:08:43.833143 1#59782 [debug] applying filters: no clients with ip 192.168.1.16 and clientid ""
> 2023/01/11 02:08:43.833171 1#59782 [debug] hosts container: handling the request
> 2023/01/11 02:08:43.833232 1#59782 [debug] dnsproxy: cache: serving cached response
> 2023/01/11 02:08:43.833253 1#59782 [debug] client ip: 192.168.1.16
> 2023/01/11 02:08:44.970417 1#59290 [debug] started GET 192.168.1.14:3080 /control/status
> 2023/01/11 02:08:44.970548 1#59290 [debug] finished GET 192.168.1.14:3080 /control/status in 146.817µs
> 2023/01/11 02:08:45.027429 1#59290 [debug] started GET 192.168.1.14:3080 /control/parental/status
> 2023/01/11 02:08:45.027480 1#59290 [debug] finished GET 192.168.1.14:3080 /control/parental/status in 72.837µs
> 2023/01/11 02:08:45.091226 1#59290 [debug] started GET 192.168.1.14:3080 /control/safesearch/status
> 2023/01/11 02:08:45.091307 1#59290 [debug] finished GET 192.168.1.14:3080 /control/safesearch/status in 89.95µs
> 2023/01/11 02:08:45.147880 1#59290 [debug] started GET 192.168.1.14:3080 /control/safebrowsing/status

Config is attached.

[AdGuardHome.yaml.txt](https://github.com/AdguardTeam/AdGuardHome/files/10391949/AdGuardHome.yaml.txt)

**Comment by jintechk** [comment]
I'm also having this as of a week or so.
running version 0.107.21 on a VM with Debian Bullseye, had no real issues prior to this.

Log also doesn't show any real reason as to why it's no longer responding, when checking with htop no real strain is put on the VM, restarting the appliance from the cli will result in a functioning service again.

Time interval seems to be completely random as it's worked fine for 20 odd hours then crapped out every 2 hours, network traffic also doesn't seem to be a direct cause as it decides to behave like this mid day (when more activity is on the network) or in the dark of the night when pretty much nothing is happening.

**Comment by kiamgrebgnur** [comment]
Without doing anything it's ok for me now. Maybe an issue with some lists?

**Comment by EugeneOne1** [comment]
@kiamgrebgnur, hello and thanks for the report.  Does AdGuard Home responds to requests for locally served (DHCP, filters) or cached data?  And also, if it begins answering again after disabling/enabling the Safe Browsing or Parental Control features?  If yes, it looks really similar to #4825.

**Comment by jintechk** [comment]
> @kiamgrebgnur, hello and thanks for the report. Does AdGuard Home responds to requests for locally served (DHCP, filters) or cached data? And also, if it begins answering again after disabling/enabling the Safe Browsing or Parental Control features? If yes, it looks really similar to #4825.

Can't speak for kiamgrebgnur but on my end Adguard only does DNS, DHCP is handled by a different device which points to AdGuard as the primary network DNS, the VM itself uses 9.9.9.9 as it's own resolv.conf, parental control has never been enabled and is turned off, same with safe browsing. 

When this occurs cached sites also don't respond and when going to the webgui the screen shows a loading icon indefinitely in AdGuard's webui.

Seemed stable for a few days after the latest update and then it started again, moved the VM to a different nic now to make sure it's not a config error or failing hardware on the OS.
