### ISSUE TITLE
"https://static.adtidy.org/adguardhome/edge/version.json: version.json: packageURL not found" Err

### ISSUE THREAD

**Issue by sunindersingh** [AdguardTeam/AdGuardHome#5373]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-a.413+cd76a307

#### What did you do?
Upgrade Version

Error :- Wed Jan 18 20:37:11 2023 [1674054431.711] daemon.err AdGuardHome[4932]: 2023/01/18 15:07:11.710182 [error] POST x.x.x.x:8080 /control/version.json: getting version info from https://static.adtidy.org/adguardhome/edge/version.json: version.json: packageURL not found

**Comment by timkgh** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/23507658/213538497-065a57d2-5ff2-4dda-aa7b-0ed8f856b580.png">

**Comment by sunindersingh** [comment]
> <img alt="image" width="356" src="https://user-images.githubusercontent.com/23507658/213538497-065a57d2-5ff2-4dda-aa7b-0ed8f856b580.png">

Yes this also sometime shows on dashboard.

**Comment by donald2612** [comment]
Same here, installed on an Edgerouter 4... and for several versions auto-updating fails, have to do it manually each time.
No problem with DNS resolving on the clients...

**Comment by dnwe** [comment]
I think this issue will affect anyone running with a `GOARCH` of `mips64`. OP mentioned AMD64, but I think the issue for Edgerouter (and other mips-based devices) is the check done here which only adds the `softfloat` suffix if the GOARCH is `mips`, but it should also handle `mips64` in this codepath when forming the package key in the version.json:
https://github.com/AdguardTeam/AdGuardHome/blob/6e8033750da25f7cff1040ea969030d808c70910/internal/updater/check.go#L113-L115

**Comment by elad-bar** [comment]
+1

**Comment by ppfeufer** [comment]
`adtidy.org` might be on a blacklist that is used.

**Comment by donald2612** [comment]
> `adtidy.org` might be on a blacklist that is used.

negative

**Comment by timkgh** [comment]
As posted by @dnwe, the problem on EdgeRouter is that `mips64` needs to be handled too
https://github.com/AdguardTeam/AdGuardHome/issues/5373#issuecomment-1399637498
On my ER-12 the arch is `linux_mips64_softfloat`

**Comment by ameshkov** [comment]
We'll soon resolve this. Sorry for the delay, had some troubles with CI yesterday.

**Comment by ainar-g** [comment]
@sunindersingh, @timkgh, @chermy, and others, could any of you please check the latest Edge release, v0.108.0-a.449+a772212d?  It should fix this issue for the Edge update channel.  The upcoming beta and final releases should also fix it for the corresponding release channels.  If the error still persists, please inspect the verbose logs.  Apologies once again for not reacting sooner.

**Comment by snapspizza** [comment]
@ainar-g seems to work flawlessly on my Edgerouter X with mipsle CPU. Thank you!
