### ISSUE TITLE
Dark theme readability feedback and API bugs issue

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#5375]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

In this issue we would like to gather feedback regarding the dark theme (#613).

**Please read the following instructions before posting!**

1.  **do not** post feedback based on personal taste (i.e. “I don't like this colour”, etc.);
2.  **do** post feedback regarding contrast and readability issues (i.e. “the text in this dialog becomes barely readable”) or API breaking;
3.  **do** look through the previous comments to make sure someone hadn't made one about the same issue before;
4.  **add** a screenshot or a video of the issue;
5.  **add** your browser and OS information;

**Comment by Birbber** [comment]
- Too light fields for dhcp settings (Encryption settings too): https://uploads.adguard.org/annrgy_u7t2e.png
- "Previous" and "Next" are almost invisible in dark mode (client settings, etc.): https://uploads.adguard.org/annrgy_54gtv.png
- Scroll colors should be less bright: https://uploads.adguard.org/annrgy_dga4l.png
- Fix hint color: https://uploads.adguard.org/annrgy_g9bqf.png
- The login form is always light: https://uploads.adguard.org/annrgy_e0okw.png
- Color for blocked services is too bright: https://uploads.adguard.org/annrgy_ajjts.png
- Tabs on "New client" section should be highlighted by clicking: https://uploads.adguard.org/annrgy_dlwmk.mp4
- The background is not transparent after opening the add client window: https://uploads.adguard.org/annrgy_279ma.mp4
- Fields turn gray when disabled: https://uploads.adguard.org/annrgy_3d7qg.mp4

**Comment by ainar-g** [comment]
It seems like we forgot to include the updates locales for the theme selector into the release.  This should be fixed as well.

**Comment by WildByDesign** [comment]
The only issue that I noticed so far is that the initial Login page does not have dark mode yet even after dark has been manually selected.

Great work, AdGuard Team. Everything looks quite good so far.

**Comment by Alex-302** [comment]
The highlighting of blocked requests is too pale.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/213459131-8de6bd10-807c-4d83-b00a-ddf856efa077.png)


</details>

**Comment by ameshkov** [comment]
Flashing navigating to the dashboard:
https://uploads.adguard.org/up04_screencast_gj29c.mp4

**Comment by CodeSapiens** [comment]
I appreciate the work and time involved in making this change, but I believe it should be a configurable option. Users should be able to switch themes to accommodate their individual lighting conditions, rather than assuming everyone wants dark theme.
Perhaps it should be under Settings -> General Settings?

**Comment by ainar-g** [comment]
@CodeSapiens, the theme selector is at the bottom of the page, near the language selector.

**Comment by CodeSapiens** [comment]
![Screenshot 2023-01-19 083203](https://user-images.githubusercontent.com/40335803/213469385-fce40358-a88f-45ec-b274-0326cb261046.png)
It does not show up for me.

**Comment by CodeSapiens** [comment]
I have closed the browser, cleared cookies, restarted the router, and still no joy. I have two AGH installations, and only the one installed on a GL.iNet router (OpenWRT) prompted me to upgrade to the new version. The other installation is on a Raspberry Pi, also OpenWRT, and that one is still running v0.107.21 and does not show an icon to check for updates at the bottom of the page. The updated OpenWRT package list still shows 0.107.21-1 as the latest version, which as you suggested, is most likely due to their APIs not being updated yet.

Question: Is there something I can change on the Raspberry Pi installation to force AGH to check for updates automatically?

Thanks for your time Ainar-g.

**Comment by CodeSapiens** [comment]
Thanks again for your time.

**Comment by Alex-302** [comment]
Dark theme applies too late after refreshing a page

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/213696180-64ee3934-de1f-43cc-bdb8-ea696c10cbe4.png)


</details>

**Comment by Birbber** [comment]
When checking filters updates 'Loading' is too dark: https://uploads.adguard.org/annrgy_pemty.mp4

**Comment by Haniffaez** [comment]
The queries dropdown menu is barely readable

![queries_filter](https://user-images.githubusercontent.com/98368603/213745926-d198ecfe-ef57-4f41-ad48-d56e1e1578f5.png)

**Comment by EugeneOne1** [comment]
The coloring of log entries for rewritten requests makes the IP of a client unreadable.
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/38542664/214015125-8cb3d203-b868-4b15-a328-b459417f7bc1.png">

**Comment by Skyxim** [comment]
![image](https://user-images.githubusercontent.com/70276018/215398140-966d8682-6510-4a1b-9d9c-58b19da8dcab.png)
I had a problem viewing the details log with the font reversed and the background still white. It works the same way on my phone

**Comment by unknown4849** [comment]
in firefox seem imposible to read this.
![image](https://user-images.githubusercontent.com/74445408/215920587-be2b24e0-6f89-47a5-8a1c-6169417989a1.png)

but in Chromium base (brave , edge) can be read but text gray and white background
![image](https://user-images.githubusercontent.com/74445408/215920882-8988f106-de75-4611-9523-7eeee6700653.png)

**Comment by ainar-g** [comment]
Most of the issues should now be fixed on the Edge channel, and the fixes will be shipped in the upcoming release.  There are some elements which aren't as easily styled, and we'll try to figure them out later.  If anyone finds other issues, please report them separately.  Thanks everyone for the feedback!

**Comment by ngosang** [comment]
Great work but there are still some issues.
![image](https://user-images.githubusercontent.com/10577978/216458195-cdec88eb-8bd7-41dd-8cab-bd8d22f41682.png)

**Comment by ameshkov** [comment]
@ngosang could you please explain what was there in the light theme?

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/216539124-f9d565ee-081d-4b4c-a151-7e90c1985b7e.png)

**Comment by ameshkov** [comment]
@ngosang thank you! Opened a new issue: https://github.com/AdguardTeam/AdGuardHome/issues/5375#issuecomment-1415227391
