### ISSUE TITLE
speed problem

### ISSUE THREAD

**Issue by Atlantis829** [AdguardTeam/AdGuardHome#5381]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Hello, sorry to bother you, I searched the wiki for this problem but couldn't find any solution. When it is selected as the fastest IP mode, the dns resolution time will reach 40 seconds when the expiration time is set to 1 second, which is unreasonable. At the same time, when it is set to 400ms or even lower, there is no query record in dns, so we cannot Ensure that each dns server can be connected smoothly, but I can at least ensure that among the dozens of servers in my upstream dns list, there will always be a few servers that can maintain connections, but this connection is not fixed. I want to give up waiting after it waits 1 second and pick the fastest IP address instead of 40 seconds. (When selecting simultaneous query, the parsing time is 100 milliseconds or even lower), can you help me solve this proble
![屏幕截图 2023-01-20 145137](https://user-images.githubusercontent.com/95276002/213678129-51bc8a0e-198a-48f4-9b64-19bcad58d0a3.png)
![屏幕截图 2023-01-20 184220](https://user-images.githubusercontent.com/95276002/213678134-8c15974a-0a1c-4a51-b661-029fe3d765e1.png)
m? [thanks]

**Comment by lutfor-diu** [comment]
i'm also facing the same.

**Comment by Vulcankta** [comment]
I have the same confusion.

**Comment by wwng2333** [comment]
What's ur upstream dns? 
Try add https://223.5.5.5/dns-query into ur list ,if u in China.

**Comment by Atlantis829** [comment]
> What's ur upstream dns? 
> Try add https://223.5.5.5/dns-query into ur list ,if u in China.

Yes, but I think the DNS providers in Chinese Mainland have pollution problems, so I will not use the service providers in Chinese Mainland. This is Alibaba's server, and there should be polluted information

**Comment by wwng2333** [comment]
> > What's ur upstream dns?
> > Try add https://223.5.5.5/dns-query into ur list ,if u in China.
> 
> Yes, but I think the DNS providers in Chinese Mainland have pollution problems, so I will not use the service providers in Chinese Mainland. This is Alibaba's server, and there should be polluted information

That's the point, but other services like 1111 or 8888 have connection problem here. 
Try to use the [dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list) to accelerate.
For example: 
```
[/biblibili.com/biliapi.com/biliapi.net/biliaudiocdn.xyz/bilibii.com/bilibil.com/bilibili.cc/bilibili.co/bilibili.com/bilibiligame.net/bilibilihelper.com/bilibilijj.com/bilibilis0.one/bilibiliyoo.com/bilicdn1.com/bilicdn2.com/bilicomic.com/bilicomics.com/biligame.com/biligame.net/bilihot.com/biliimg.com/bilimoe.com/bilive.com/bilivideo.com/]https://223.5.5.5/dns-query
```
use alidns to resolve bilibili.

**Comment by wwng2333** [comment]
![image](https://user-images.githubusercontent.com/17147265/215422386-3041f4f6-e2be-4f74-b742-b95728f5d0db.png)
Acceptable speed.

**Comment by Atlantis829** [comment]
> ![image](https://user-images.githubusercontent.com/17147265/215422386-3041f4f6-e2be-4f74-b742-b95728f5d0db.png)
> Acceptable speed.

When I use tls8.8.4.4(Google),it's just 30ms so quickly,but if in the fastest model,it will be 40s+

**Comment by wwng2333** [comment]
If you use the "Fastest ip"mode, it will queue for all the server and wait for them response. dns.google is not stable in China, so you will get the 40s wait.Try to use parallel mode maybe.

**Comment by Atlantis829** [comment]
> If you use the "Fastest ip"mode, it will queue for all the server and wait for them response. dns.google is not stable in China, so you will get the 40s wait.Try to use parallel mode maybe.

This is not surprising. This is caused by the differences in the network environment in various parts of China. For example, in China Mobile Network, 1.1.1.1 is not accessible, while 1.0.0.1 is available (19ms). You can use port scanning. I tested Google dns in most network environments, and the results are as follows: 8.8.8.8's 443 (https) and 853 (tls) ports are not available, 53 ports are available, 8.8.4.4's 853 and 53 ports are available, 443 is not available (that's why I choose tls://8.8..4.4 , even if the network environment is changed, it can still be used). In addition, I recommend a service tls of 中華電信that I have been using tls://101.101.101.101,As for 40s, I think it is a software design problem. It should be abandoned when some IP addresses are unavailable
![屏幕截图 2023-01-31 105618](https://user-images.githubusercontent.com/95276002/215652534-de7d769e-6dbb-4a4c-9ac3-5b59b57dc33d.png)

**Comment by wwng2333** [comment]
> 

Should set a value of timeout, avoid this kind of situation.

**Comment by Atlantis829** [comment]
> 

yep i already set but donnot work
