### ISSUE TITLE
Google image requests get an ERR_HTTP2_PROTOCOL_ERROR and doesn't go through

### ISSUE THREAD

**Issue by bastienhugues** [AdguardTeam/AdGuardHome#5384]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

  v0.107.22

### Description

Adguard is running on a Qnap, installed through qnapclub directly.

#### What did you do?
When trying to run a seach in Google, if I click on the "Images" Tab, it will start loading forever and ends with a ERR_HTTP2_PROTOCOL_ERROR

#### Expected result
It would be supposed to show images related to the search

#### Actual result
ERR_HTTP2_PROTOCOL_ERROR

#### Screenshots (if applicable)
![2023-01-20_12-28-43](https://user-images.githubusercontent.com/123196060/213764900-640b3c29-a803-4021-a5d2-f6890c5e2a80.png)

**Comment by rafalohaki** [comment]
same problem but for https://www.xda-developers.com/
