### ISSUE TITLE
Error adding certificate

### ISSUE THREAD

**Issue by filisdiez** [AdguardTeam/AdGuardHome#5385]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.22

### Description

Hello!

When adding a certificate to a domain, the error indicated in the screenshot pops up. I managed to get rid of it by creating a certificate for an ip address, but I would like to log in by domain name, and not by ip. This error is present, as I subtracted on the Internet, after updating from v0.107.17, but there is no solution - so I write here in the hope that this error will be fixed.

There is also a problem if you install AdGuard Home on a PC with Ubuntu server 20.04 with the amd64 installation package, I did not try to install it on windows.

![domain](https://user-images.githubusercontent.com/31742254/213775994-cfbef264-97e5-48d6-9fee-e153d2a8e987.jpg)

**Comment by Vulcankta** [comment]
I have tried on Linux centos7.6.Windows sever 2008,Windows sever 2012,Windows sever 2016 and also encountered the same error.  DOH and DOT are not working, but DOQ is working fine. I feel very confused.
