### ISSUE TITLE
Hide some domains in "Top queried domains"

### ISSUE THREAD

**Issue by Dan-Sun** [AdguardTeam/AdGuardHome#5397]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Hello!

I was looking to hide some specific domains for "Top queried domains" on the dashboard because the requests of specific domains can be quite high for example with multiple email clients in one network with the same email server etc. 

I've started recently a discussion https://github.com/AdguardTeam/AdGuardHome/discussions/5366 and it seems it's not possible, yet?

It would be great if only domains that I don't already know were listed.

Thanks!

**Comment by JourneyOver** [comment]
Would not mind seeing this myself tbh

**Comment by schzhn** [comment]
Hello, @Dan-Sun, @JourneyOver.
You can solve this by specifying *Ignored domains* for statistics on the *General settings* page.

**Comment by JourneyOver** [comment]
Funny how I completely missed that in the settings when I was looking at them in the past >.<

**Comment by Dan-Sun** [comment]
Yeah, weird O_o
Anyhow, thanks @JourneyOver for reply and thanks @schzhn for letting us know ;)
