### ISSUE TITLE
Invalid Upstream DNS Providers

### ISSUE THREAD

**Issue by mfwinker** [AdguardTeam/AdGuardHome#5398]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Version:  v0.107.22

#### What did you do?
Entered in several upstream DNS providers found using the link provided in the settings, all of which failed
#### Expected result
DNS provider would work
#### Actual result
Server "https://1.1.1.1/dns-query": could not be used, please check that you've written it correctly.  Same error for every provider I enetered

#### Screenshots (if applicable)
<img width="390" alt="Screenshot 2023-01-24 011026" src="https://user-images.githubusercontent.com/123085742/214232261-d2c3ccaf-7a61-4f66-96db-6517fcca3e52.png">

#### 
Additional information

**Comment by rhsCZ** [comment]
![obrazek](https://user-images.githubusercontent.com/15573547/214357149-56a61ef0-a341-4c4d-b0a1-ae198c5a4bd1.png)
try https://dns.cloudflare.com/dns-query
i nowhere found https://1.1.1.1/dns-query so i wonder where you got that.
btw. dns over https needs domain to work properly.

**Comment by dcomputerhelper** [comment]
getting the same error after the latest update. 
Even with AdGuard upstream DNS.  
Have tried everything from cloudflare, opendns, quad9, controld.... etc  
Something is broken in the most recent update

**Comment by ainar-g** [comment]
@mfwinker, @dcomputerhelper, hello.  We cannot reproduce this.  If you are sure that your Internet connection is working and the bootstrap servers are available, please inspect the [verbose logs][1] to collect more data about the issue.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog
