### ISSUE TITLE
DNS-Rewrites not working with custom client settings (DEB 10)

### ISSUE THREAD

**Issue by Ser1ous1** [AdguardTeam/AdGuardHome#5402]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.22

#### What did you do?
I wanted to disable all my DNS filtering Servers / settings for two clients.

#### Expected result
DNS Filter only for these devices disabled

#### Actual result
Selfmade DNS-Rewrites are not working anymore (for local redirect)
e.g.
192.168.1.254 firewall.home.domain
192.168.1.10 webserver.home.domain

==
EXT_PUBLIC_IP firewall.home.domain
EXT_PUBLIC_IP webserver.home.domain
#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/33761882/214637556-da92b78f-c598-447f-b4c4-9e8ab3ffb3b5.png)
![image](https://user-images.githubusercontent.com/33761882/214636846-00b07328-18e2-48eb-866f-57beaee8b084.png)
![image](https://user-images.githubusercontent.com/33761882/214637718-8e8e4566-266e-4c82-abe7-a901b818fb0b.png)
![image](https://user-images.githubusercontent.com/33761882/214638020-4158cb41-33b0-4a94-99c2-600b689dad63.png)

#### Additional information
Please fix asap.

**Comment by ppfeufer** [comment]
Have a look here » https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by Ser1ous1** [comment]
Came to the same idea seconds before. But it's not a beautiful way.

**Comment by iAmSaugata** [comment]
> Came to the same idea seconds before. But it's not a beautiful way.
> 
> That's what i did for the two clients @@||^$client='192.168.1.105' @@||^$client='192.168.1.111'
> 
> *Well this doesnt work. Blocklists are still kicking in, is there no global wildcard?
> 
> **Update disable complete domain filtering for ip:** @@||*^$client='ip'
> 
> leaving this issue open, the custom client settings should not remove my dns-rewrites. seperate it please from the blocklists!

Could you please try this?

@@||*^$client=192.168.1.105
@@||*^$client=192.168.1.111

**Comment by Ser1ous1** [comment]
> 

@@||*^$client='ip'

Works for me:
![image](https://user-images.githubusercontent.com/33761882/214660286-189aed7b-fc3f-4b9c-aaa2-0ae6ffda0ea6.png)

**Comment by iAmSaugata** [comment]
> > 
> 
> @@||*^$client='ip'
> 
> Works for me: ![image](https://user-images.githubusercontent.com/33761882/214660286-189aed7b-fc3f-4b9c-aaa2-0ae6ffda0ea6.png)

Awesome! Happy new year!! :)
