### ISSUE TITLE
Add API (feature request) 

### ISSUE THREAD

**Issue by tjorim** [AdguardTeam/AdGuardHome#541]
### Description 

An AdGuard Home add-on for Home Assistant is in the works. 
Some users (including myself) would like to show statistics,
the same way as it's possible with [the Pi-hole sensor](https://www.home-assistant.io/components/sensor.pi_hole/). 
However, at the moment there doesn't seem to be an API to gat data like this from AdGuard. 
While Pi-hole is preparing [their new API](https://pi-hole.net/2018/10/15/announcing-our-restful-api-contributions-welcome/), the docs for the current one are available [here](https://discourse.pi-hole.net/t/pi-hole-api/1863) to check out. 

### Expected behavior

An API to pull statistics data is available 

### Actual behavior

It is not implemented currently 

### Your environment
NA

### Additional details
Below is a short list of statistics that are available for Pi-hole in Home Assistant:

> ads_blocked_today
> Total number of blocked ads today.
> 
> ads_percentage_today
> Percentage of blocked ads.
> 
> dns_queries_today
> Total number of DNS queries handled by Pi-hole today.
> 
> domains_being_blocked
> Total number of domains blocked by Pi-hole.
> 
> queries_cached
> Total number of cache queries on the last 24 hours.
> 
> queries_forwarded
> Total number of forwarded queries on the last 24 hours.
> 
> unique_clients
> Total number of unique clients on the last 24 hours.
> 
> unique_domains
> Total number of unique domains on the last 24 hours.
> 
> clients_ever_seen
> Total number of seen clients

**Comment by ameshkov** [comment]
First of all, please check what API is available:
https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

If there's something you'd like to be added, please post a comment here with the details on what you'd like to have there and why you need it.

**Comment by tjorim** [comment]
Thanks for pointing me to this, didn't find it at first (just searched the readme and wiki), will check it out!

**Comment by rothgar** [comment]
I also would love metrics. Another possibility besides building it into the API is to have a prometheus compatible /metrics endpoint that serves plain text metrics.

More information available here https://prometheus.io/docs/concepts/data_model/

**Comment by ameshkov** [comment]
@rothgar there's already a feature request for that: #516

**Comment by frenck** [comment]
@tjorim You question regarding Home Assistant availability, that integration is currently in progress and expected to land in Home Assistant pretty soon (stats & controls).

**Comment by frenck** [comment]
This can be closed actually, since Home Assistant now has an AdGuard Home integration.
