### ISSUE TITLE
Web login loop using FQDN vs IP address

### ISSUE THREAD

**Issue by gdtms247** [AdguardTeam/AdGuardHome#5424]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

Version:  v0.107.22

#### What did you do? 
Created a local A record for adguard in internal DNS solution to use FQDN to access webpage vs IP. 

#### Expected result
Webpage loads and allows login to manage adguard.

#### Actual result
Webpage loops on login returning to login page after successful login. Adguard logs show login was successful. 
Webpage loads properly using IPv4 address assigned to docker

#### Additional information
2 instances of adguard-home installed through docker
  a) unraid docker deployment - x86 hardware
  b) raspberry pi script deployment from ReadMe - ARMv7

**Comment by gdtms247** [comment]
Issue was something with laptop/browser, disregard.

**Comment by sripwoud** [comment]
@gdtms247 
Can you add more details about the issue you had with your browser and how you fixed it?
I am experiencing something similar.
Running with docker.
I can see in my logs that the auth is successful. But in my browser I keep being redirected to the login page.
I can login without issues with mobile clients.
Didn't tweak my records though.

**Comment by gdtms247** [comment]
It was related to running GUI with SSL enabled using FQDN and "same name" security of those certificates/cookies.
