### ISSUE TITLE
handling TCP error

### ISSUE THREAD

**Issue by Arketsu** [AdguardTeam/AdGuardHome#5429]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b.25

### Description

Hello not sure what else to do but this is the error I am getting.
#### Problem
2023/01/31 17:24:08.355371 [error] handling tcp: reading msg: reading len: read tcp 192.168.0.104:53->192.168.0.104:55262: wsarecv: An established connection was aborted by the software in your host machine.

#### What did you do?
1. closing programs like: docker desktop & aida64 extreme really don't have anything else that would conflict with this.
2. port forwarding
3. updating adguard home, changing settings, reinstalling.
4. check network traffic but couldn't find anything.
5. using different browsers

#### Last time adguard home was working?
probably 1 or 2 months ago

####Update!!
1.reinstalled windows (clean install) same error occurs

**Comment by ainar-g** [comment]
Hello.

 >  Setup
 >  On a router, DHCP is handled by the router

Is your router running Windows, or did you select this option by mistake?  What does the network really look like?

Also, how does the error interfere with AdGuard Home exactly?  Errors like this can occur simply when a connection breaks.

In any case, please make sure that your antivirus software isn't interfering with AGH.

**Comment by Arketsu** [comment]
1.router asus GT-AC5300 (firmware  3.0.0.4.386_48377-g3e428e2) latest one date of released 2022/04/01.
2. haven't made any changes in the router since basically that day.
3. turned off firewall and antivirus but still same results
4. running adguard home on windows for over 3 years problem started occurring about 2 ish months ago.
5. even tested after a clean install.
