### ISSUE TITLE
League of Legend icon wonky in the latest version 

### ISSUE THREAD

**Issue by photomme** [AdguardTeam/AdGuardHome#5433]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.23

#### Screenshots 
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/84580500/216066170-994ab784-ecd2-4d32-927c-361220a3f3dd.png">

**Comment by ainar-g** [comment]
@Blakhard, we should use the same presentation logic as the one used in AdGuard DNS.  I don't think that the latter ever had serious issues with these.

It is also important to make sure that `fill="currentColor"` is used consistently among all icons.

**Comment by sandervankasteel** [comment]
@photomme As the person that made to PR to allow blocking of League of Legends. This is my bad :sweat_smile:. 

However, I just made a PR with a fix towards the repository where the icon is coming from.

**Comment by ainar-g** [comment]
@photomme, version v0.108.0-a.425+6a032bb8 on the Edge release channel now contains the fixed icon from @sandervankasteel.  Please don't close this issue, though, as we still need to improve a couple of things to make such bugs less likely in the future.
