### ISSUE TITLE
I lose "Static DHCP Assignments" on every update

### ISSUE THREAD

**Issue by jozemanue** [AdguardTeam/AdGuardHome#5436]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.23

### Description

installed in docker in Synology DS 720+

every time a new update comes out, by doing it i lose all the ip reserved in dhcp. (there are about 30)

**Comment by ainar-g** [comment]
Hello.  What `docker` command are you using to run AdGuard Home?  Are you sure that the volume you use for configuration is mounted correctly?

**Comment by jozemanue** [comment]
hello,
i have this compose:

version: '3.3'
services:
    adguardhome:
        container_name: adguard
        environment:
            - TZ=Europe/Madrid
        volumes:
            - '/volume1/docker/adguard/config:/opt/adguardhome/conf'
            - '/volume1/docker/adguard/data:/opt/adguardhome/work/data'
        network_mode: host
        restart: always
        image: adguard/adguardhome

the mounted volume is correct.

**Comment by RealKev79** [comment]
when you add following volume the static leases will not be deleted. I have the same issue and after that every update works fine.

- '/volume1/docker/adguard/work:/opt/adguardhome/work'

The leases are stored in the "work"-Directory and not in "work/data".

**Comment by jozemanue** [comment]
> when you add following volume the static leases will not be deleted. I had the same issue and after that every update works fine.
> 
> * '/volume1/docker/adguard/work:/opt/adguardhome/work'
> 
> The leases are stored in the "work"-Directory and not in "work/data".

Thanks, I see that a database is created with my dhcp!

**Comment by ainar-g** [comment]
@jozemanue, apologies for the lack of response.  Is the issue fixed for you now?

**Comment by jozemanue** [comment]
> @jozemanue, apologies for the lack of response.  Is the issue fixed for you now?

I think so!  but I won't know until the next update.  thanks for answering!
