### ISSUE TITLE
Server "2a10:50c0::ad1:ff": could not be used, please check that you've written it correctly

### ISSUE THREAD

**Issue by Arthur-Kenichi-Condino** [AdguardTeam/AdGuardHome#5437]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.23

#### What did you do?
updated AdGuard home through admin interface on Edge

#### Expected result
updates applied and no error is presented with Test upstreams

#### Actual result
AdGuard fails to resolve some web pages like Steam Community
AdGuard Test upstreams fails for:
2a10:50c0::ad1:ff
2a10:50c0::ad2:ff
so the line [/adguard-dns.com/]94.140.14.14 must be added in the DNS servers list so the IPv6 isn't used by the system.

#### Additional information
ping 2a10:50c0::ad1:ff
in windows terminal results in:
Disparando 2a10:50c0::ad1:ff com 32 bytes de dados:
Resposta de 2a10:50c0::ad1:ff: tempo=118ms
Resposta de 2a10:50c0::ad1:ff: tempo=118ms
Resposta de 2a10:50c0::ad1:ff: tempo=118ms
Resposta de 2a10:50c0::ad1:ff: tempo=123ms

Estatísticas do Ping para 2a10:50c0::ad1:ff:
    Pacotes: Enviados = 4, Recebidos = 4, Perdidos = 0 (0% de
             perda),
Aproximar um número redondo de vezes em milissegundos:
    Mínimo = 118ms, Máximo = 123ms, Média = 119ms

**Comment by Arthur-Kenichi-Condino** [comment]
tried to use 2a10:50c0:0:0:0:0:ad1:ff in the:
"Private reverse DNS servers"
because:
"By default, AdGuard Home uses the following reverse DNS resolvers: "2a10:50c0::ad1:ff"."
But still:
"Server "2a10:50c0:0:0:0:0:ad1:ff": could not be used, please check that you've written it correctly"
Searching more, maybe this is the same problem?
https://github.com/AdguardTeam/AdGuardHome/discussions/3039

**Comment by ainar-g** [comment]
Hello.  I cannot reproduce the issue.  Two things that could shed some light:

1.  Enable [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see if there are any clues.

2.  A better way to test the DNS reachability is by using `dig` or `nslookup`.  For example:

    ```sh
    nslookup -debug "test." "2a10:50c0::ad1:ff"
    ```

**Comment by rmandjes** [comment]
Hi,

I've the same problems on my raspberry pi. I'm using the latest version.
If I enable verbose logging I see the following error message:
2023/02/10 10:33:19.490781 31411#153 [debug] dnsforward: upstream "192.168.178.1" is ok
2023/02/10 10:33:19.572034 31411#152 [debug] [2a10:50c0::ad2:ff]:53: response: ok
2023/02/10 10:33:19.572353 31411#152 [debug] dnsforward: upstream "2a10:50c0::ad2:ff" is ok
2023/02/10 10:33:19.616397 31411#156 [debug] [2a10:50c0::1:ff]:53: response: ok
2023/02/10 10:33:19.616784 31411#156 [debug] dnsforward: upstream "2a10:50c0::1:ff" is ok
2023/02/10 10:33:29.441628 31411#151 [debug] [2a10:50c0::ad1:ff]:53: response: read udp [2001:1c03:620e:6200:8c32:ddff:33c8:5cb0]:55389->[2a10:50c0::ad1:ff]:53: **i/o timeout**


But when I do a nslookup from my windows computer (not using Adguard), I get this result:
nslookup -debug "test." "2a10:50c0::ad1:ff"
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        f.f.0.0.1.d.a.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.c.0.5.0.1.a.2.ip6.arpa, type = PTR, class = IN
    ANSWERS:
    ->  f.f.0.0.1.d.a.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.c.0.5.0.1.a.2.ip6.arpa
        name = dns.adguard.com
        ttl = 69698 (19 hours 21 mins 38 secs)

------------
Server:  dns.adguard.com
Address:  2a10:50c0::ad1:ff

------------
Got answer:
    HEADER:
        opcode = QUERY, id = 2, rcode = NOERROR
        header flags:  response, auth. answer, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        test, type = A, class = IN
    AUTHORITY RECORDS:
    ->  test
        ttl = 10800 (3 hours)
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 3600 (1 hour)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)

------------
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 3, rcode = NOERROR
        header flags:  response, auth. answer, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        test, type = AAAA, class = IN
    AUTHORITY RECORDS:
    ->  test
        ttl = 10800 (3 hours)
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 3600 (1 hour)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)

------------
Name:    test

**Comment by overwatch3560** [comment]
is this still an issue @Arthur-Kenichi-Condino

**Comment by Arthur-Kenichi-Condino** [comment]
> is this still an issue @Arthur-Kenichi-Condino

hello! Sorry for the long delay to respond! The problem persists until today but I forgot about it because it doesn't show anything wrong while using AdGuard Home in the day to day; but recently I went to eventvwr and I have a lot of errors from AdGuard Home saying:
"2024/05/11 22:34:36.435283 [error] dnsproxy: [2a10:50c0:0000:0000:0000:0000:ad2:ff]:53: response received over udp: 'exchanging with [2a10:50c0:0000:0000:0000:0000:ad2:ff]:53 over udp: read udp [2804:431:c7da:dd63:7515:7745:ddf4:d7bd]:57220->[2a10:50c0::ad2:ff]:53: i/o timeout'"

Maybe this can shed some light to the problem? 

Sincerely, Arthur Condino
