### ISSUE TITLE
Drop-down menu in query log page is light-colored  in dark mode, difficult to read.

### ISSUE THREAD

**Issue by sonicprogrammer** [AdguardTeam/AdGuardHome#5441]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.26

#### What did you do?

IN DARK MODE:
Visit 'Query Log page', using Edge/Chrome/Firefox (latest release verion).
Click the filter drop-down menu (for example: 'All queries') in the upper right.

#### Expected result

An easy-to-read drop-down menu with a dark background and light texts, same as 'Settings -> General settings' page.

#### Actual result

A dropdown menu with a light background and grey/light texts. Hard to read in Edge/Chrome. Invisible in Firefox.

#### Screenshots (if applicable)

Edge/Chrome
![ec](https://user-images.githubusercontent.com/10679335/216502677-83ad58cb-fd47-4d19-88c6-f5644a4916c1.png)

Firefox
![f](https://user-images.githubusercontent.com/10679335/216502691-048b1e06-f967-462c-b328-d7718fb1d945.png)

#### Additional information

N/A

**Comment by Ketan-Agarwal** [comment]
same going on with me 
![image](https://user-images.githubusercontent.com/73290289/216597617-76cf4d3e-b28c-4714-acb1-09030c1333cd.png)

**Comment by Ketan-Agarwal** [comment]
same going on with me 
![image](https://user-images.githubusercontent.com/73290289/216597787-f2f002e8-ab4a-427d-a895-834939cdd1f9.png)

**Comment by Beet4** [comment]
Can confirm, although mine is completely white for non-selected items, so it's impossible to read.

![image](https://user-images.githubusercontent.com/38279393/217947373-8c8dd422-fa90-4c56-9965-e03a8c107e88.png)

**Comment by GritsanY** [comment]
![image](https://user-images.githubusercontent.com/17610768/219306688-b78cd012-ea50-4750-b580-2c26da2f018d.png)
same for me, firefox 109.0.1

**Comment by ainar-g** [comment]
@sonicprogrammer, @Ketan-Agarwal, @Beet4, @GritsanY, this should be fixed on the Edge channel.  Could any of you please check?

**Comment by Beet4** [comment]
@ainar-g Confirmed working on edge-channel on Firefox 110.0

![image](https://user-images.githubusercontent.com/38279393/221380217-dee110da-1de2-4736-ac18-1a9ee2ff16a9.png)

![image](https://user-images.githubusercontent.com/38279393/221380225-2248058a-2948-4819-80e4-bc75d68621e6.png)

![image](https://user-images.githubusercontent.com/38279393/221380231-81bfa7d3-552d-4d85-9641-8f2687fae757.png)
