### ISSUE TITLE
Dark theme: Client name is not visible in the Query Log when the status is "Rewritten"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#5442]
Here's how it looks like:
![image](https://user-images.githubusercontent.com/10577978/216458195-cdec88eb-8bd7-41dd-8cab-bd8d22f41682.png)

Light theme:
![image](https://user-images.githubusercontent.com/5947035/216539558-6f2adc85-e242-4b10-9cf6-2882fed3adec.png)

_Originally posted by @ngosang in https://github.com/AdguardTeam/AdGuardHome/issues/5375#issuecomment-1414426673_

**Comment by NPCDW** [comment]
![image](https://user-images.githubusercontent.com/32638459/216611160-bc4c184a-4ae2-4a9a-a0bd-b8f1d992df58.png)

**Comment by Erwan-loot** [comment]
Hello, i confirm here a screenshot[](url)
![2023_02_03_21_53_09_NVIDIA_GeForce_Overlay_DT](https://user-images.githubusercontent.com/62173453/216709074-efce43be-cbe3-47ef-8113-ac6e99bd47be.jpg)
