### ISSUE TITLE
Add an option to work as a DNS recursor

### ISSUE THREAD

**Issue by ncleis** [AdguardTeam/AdGuardHome#5446]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

**Add recursive mode to work with root DNS servers directly**, without using dns resolvers like unbound, powerdns recursor, knot-dns resolver and others. I would like to set the interval of update file by link https://www.internic.net/domain/named.root or make an option in the menu, which will be entered a link to the root DNS zones and the period in which they will be updated (as now for example works black and white list). This mode of working directly without using third-party DNS such as cloudflare, google and others will allow to use AGH for a large number of clients, and not to have problems with cache while using a combination of for example unbound + AGH, and not to face restrictions on DNS requests from the same google and cloudflare.

**Comment by devipasigner** [comment]
You know caching can be disable on AdGuard home

**Comment by cjmaxik** [comment]
Root DNS servers are not meant to be used by end users.

**Comment by ncleis** [comment]
> Root DNS servers are not meant to be used by end users.

Who are they for? Public DNS such as google and cloudflare work with root DNS. Unbound, powerdns recursor, and others also work with root DNS. Why aren't they designed to work with end users? You need a special approach to deal with them, not just providing an ip address.

**Comment by cjmaxik** [comment]
They are maintaining top-level domains. It is actually a waste of requests, since they will ALWAYS redirect you to other DNS servers for specific domain zones.

**Comment by ncleis** [comment]
> They are maintaining top-level domains. It is actually a waste of requests, since they will ALWAYS redirect you to other DNS servers for specific domain zones.

Do you know how a DNS query works? I don't want to use intermediaries such as cloudflare and google, I want to use a direct query to the root servers and then down the chain to the NS servers.

**Comment by cjmaxik** [comment]
Why would you even need that? I am confused. What is the rationale?

**Comment by ncleis** [comment]
> Why would you even need that? I am confused. What is the rationale?

The point is NOT to use intermediaries in the DNS query chain and to be independent of them

**Comment by 6aink** [comment]
我也有这样的想法，直接请求根不好吗

**Comment by ameshkov** [comment]
We've explored this in the past.

Long story short:
1. There are no good pure go recursive resolver implementations. If there were, implementing this feature would be a no-brainer.
2. We could try integrating with `libunbound`, but we generally would like to keep AdGuard Home a pure go application to keep it small and cross-platform. Also, using `libunbound` is pretty much the same as setting up your own local unbound instance and using it as an upstream in AdGuard Home.

Keeping this as an open feature request. If at some point there will be a pure go recursor good enough to use, we'll get back to it.

**Comment by JeffWDH** [comment]
Would this be suitable for implementing native DNS recursion? It appears to be written in Go. 
https://github.com/semihalev/sdns

**Comment by gramakri** [comment]
Dup of https://github.com/AdguardTeam/AdGuardHome/issues/790 ?
