### ISSUE TITLE
Wrong URL for clients ID in journal section

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#5449]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.23

### Description

Hello,

there is wrong URL for the client ID in journal:
![image](https://user-images.githubusercontent.com/45385632/216775268-41e2b6c2-0ade-481b-b924-9f09674feed6.png)

It has to be something concrete:
![image](https://user-images.githubusercontent.com/45385632/216775317-c0a183ad-831d-4327-91ec-e49989aea528.png)

Because in this case will be filtered queries by the IP/anonymised subnet and not client ID. The queries from another device but from the same subnet will included!

Thank you.
Best regards.

**Comment by ainar-g** [comment]
The query log doesn't really have proper filtering by fields right now, using only one query term.  See #1933, #594, and other blocked on #2290.

Or do you mean that the current query log should provide several query term links if there are more than one?

**Comment by ammnt** [comment]
@ainar-g, no. You're right! Thanks for the answer😅
