### ISSUE TITLE
Too slow in the fastest ip mode

### ISSUE THREAD

**Issue by Atlantis829** [AdguardTeam/AdGuardHome#5456]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.23

#### What did you do?

When the fastest ip mode is selected, it cannot be resolved or is slow。According to the wiki, I modified the fast in the yaml file_ Timeout and upstream_ The value of timeout, whether I set them to 800ms or 1s.

#### Expected result

It should obtain the correct IP address within the specified 1600ms or 2s, no longer wait for the unanswered DNS server, but choose the fastest IP address and return it to the computer

#### Actual result

It will wait for more than 40 seconds. The browser cannot load the website.

#### Screenshots (if applicable)

![1](https://user-images.githubusercontent.com/95276002/216922155-a2c6f5c8-894c-4dd0-a0e0-f4c3526eeaac.png)

The resolution speed difference between the fastest ip mode and the concurrent request mode:
![2](https://user-images.githubusercontent.com/95276002/216922404-280be9e4-d5d7-426c-907c-f5f6464f6df6.png)
![3](https://user-images.githubusercontent.com/95276002/216922430-7c3b26e4-77f7-4554-9aaa-9c3660bc44aa.png)

#### Additional information
I think this function is very necessary in areas with poor network quality, rather than requiring users to ensure the connection stability of upstream dns servers. It should be that only in places with poor network needs to choose the fastest IP. In places with poor network, we can't guarantee that the DNS server can always be connected, but I can guarantee that there are always servers online in the list I provide and can provide reliable connection better than 1s, but this server is not fixed. It should be that we will write dozens of DNS servers to the DNS list.
I hope you can refer to this logic, request all DNS servers simultaneously, then stop receiving within the number of seconds set by the user (such as 300ms), and then test the speed of the server within the existing IP and return an optimal IP address.
Or you can test the connectivity of dns in the background before concurrent requests, and do not use an unconnectable dns server for a certain period of time.

！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
I think this mode is used by people in areas where the network is unstable, so users cannot be required to ensure that every DNS server can connect!
！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

Good luck, thank you!

**Comment by agneevX** [comment]
> In places with poor network, we can't guarantee that the DNS server can always be connected

If there's issue with something as measly as DNS, do you really expect web pages to load?

**Comment by Atlantis829** [comment]
> > In places with poor network, we can't guarantee that the DNS server can always be connected
> 
> If there's issue with something as measly as DNS, do you really expect web pages to load?

But I think that is improtant
