### ISSUE TITLE
AGH loads indefinitely after adding further predefined filter lists

### ISSUE THREAD

**Issue by b255ea006** [AdguardTeam/AdGuardHome#5459]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

Release 

#### What did you do?
I have installed the AdGuard Home with the following comand

curl -L -s -k -O https://raw.githubusercontent.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/master/installer && sh installer

Everything seems to work, i go to the settings confirm with "y" and give my Logging/ Username and password but then after installing and starting und running it for the first time everything is ok but then a second later the system reboots and the installation vanishes and the module download fails for some unknown reason.  View Screenshoot.

Everything happens without any action of myself automatically and i do not know why or how to stop it.

I am using ASUS RT-AX86S with Merlin Firmware 388.1

The router has a dual core CPU and the normal OS.

the whole thing should run on my SanDisk 32 GB USB 3.1 Flash Drive.

#### Expected result
running AdGuard

#### Actual result

fails to load

#### Screenshots (if applicable)
![2023-02-06](https://user-images.githubusercontent.com/107177138/216998085-bb08a18c-787b-4fa8-9cb5-cc576055b3f2.png)
#### Additional information
Getting from fwupdate.asuswrt-merlin.net
 ! Module AdGuardHome.mod download failed
 ! using fallback server diversion.ch
 ! Module AdGuardHome.mod download failed

**Comment by ppfeufer** [comment]
This doesn't seem to be an official install method provided by the AGH team. You might be better off reporting your issue here » https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer

**Comment by b255ea006** [comment]
I am sharing the comment. Thanks

**Comment by b255ea006** [comment]
Hi,

now i do have the same issue with using the following to install AdGuardHome


curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v

View Screenshot.

Right after i have installed AdGuardHome it fails to load and vanishes on the USB drive and the WebInterface hangs up and loads endlessly but before that "view second screenshot" AdGuardHome is unable to load the filters.

What's wrong?

![2023-02-09 (1)](https://user-images.githubusercontent.com/107177138/217839797-75a65ace-a150-419e-a2fb-48e67493363e.png)

![2023-02-09](https://user-images.githubusercontent.com/107177138/217840317-cddf459a-9b18-4418-b71c-5da349ebdabe.png)

**Comment by b255ea006** [comment]
> This doesn't seem to be an official install method provided by the AGH team. You might be better off reporting your issue here » https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer

I now have used the original code to install the AdGuardHome but as you can see and read it does not work or run. But why?

**Comment by b255ea006** [comment]
Correction:

I have checked and my DHCP Server is not handled by AdGuardHome.

**Comment by b255ea006** [comment]
Now i have made successful progress but still run into an issue and this time it happens always if i want to ad new Filter Lists over the WebUI of AdGuard. I am able to add one maybe two new predefined lists but then the system hangs up and freezes. How does that come?

**Comment by b255ea006** [comment]
Now i have made successful progress but still run into an issue and this time it happens always if i want to ad new Filter Lists over the WebUI of AdGuard. I am able to add one maybe two new predefined lists but then the system hangs up and freezes. How does that come?

**Comment by b255ea006** [comment]
Now i have made successful progress but still run into an issue and this time it happens always if i want to ad new Filter Lists over the WebUI of AdGuard. I am able to add one maybe two new predefined lists but then the system hangs up and freezes. How does that come?

**Comment by jumpsmm7** [comment]
> 

What are the DNS settings on your WAN settings page? Also, what upstream dns servers do you have defined in adguardhome webui? 
Also, have you changed to confirm your flash drive is in proper working order? 
Also, what does your router memory usage look like when you try to load that many lists? Keep in mind the router does not have a lot of RAM. 

Try running this 
`grep Vm  /proc/`pidof AdGuardHome`/status`

and report its output

**Comment by b255ea006** [comment]
Behavior has changed, now it is working differently. 

Thanks 👍
