### ISSUE TITLE
Injecting own DNS names with AGHome

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdGuardHome#546]
Hello, i created a custom Filter (https://gist.githubusercontent.com/Bluscream/abb44b800220f4a90406505f6bdb86d0/raw/redirect.txt) to redirect some domains in my local network to specific IPs. But they almost never get resolved successfully:
![image](https://user-images.githubusercontent.com/3318223/51095582-1c6e7b00-17b6-11e9-9739-bad831e95101.png)

My question is: Can i make these redirects work for all devices using AGHome?

**Comment by ameshkov** [comment]
I think you need to change `192.168.2.25	pi2 cctv cctv.fritz.box` to:
```
192.168.2.25	pi2
192.168.2.25	cctv
192.168.2.25	cctv.fritz.box
```

**Comment by Bluscream** [comment]
Why is that? According to all sites it is okay to have multiple domains per line (Example: [Wikipedia](https://en.wikipedia.org/wiki/Hosts_(file))

```
127.0.0.1  localhost loopback
::1        localhost
```

**Comment by ameshkov** [comment]
Filed a new bug report:
https://github.com/AdguardTeam/AdGuardHome/issues/735

I suppose this is the root cause.
