### ISSUE TITLE
v0.107.23 does not build with Go 1.20

### ISSUE THREAD

**Issue by an0nfunc** [AdguardTeam/AdGuardHome#5464]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.23

#### What did you do?

Trying to build [v0.107.23](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.23) with Go 1.20 on Archlinux fails with

```
# github.com/lucas-clemente/quic-go/internal/qtls
/build/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

Seems like go-quic has a Go 1.20 compatible release in [v0.32.0](https://github.com/quic-go/quic-go/releases/tag/v0.32.0).

#### Expected result

AdGuardHome building successfully with go 1.20.

#### Actual result

Builderror (see above).

**Comment by ainar-g** [comment]
Hello.  This is fixed in the current `master`, and will soon reach the Edge channel.  See 137d280032c8f2f0331f16b00cba83682369a43f.

**Comment by an0nfunc** [comment]
Hi! Must have missed that commit, thanks. Is there any chance this will reach the stable branch?
