### ISSUE TITLE
Drop HTTPS queries in the "Disallowed domains"

### ISSUE THREAD

**Issue by kultfigur** [AdguardTeam/AdGuardHome#5468]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
There are mainly Apple devices in my home network which issue lots of dns query of type "HTTPS"

In the Custom Filtering Rules this line is working:
||*^$dnstype=HTTPS

But I want to get rid of them earlier in the "Disallowed domains" 

(Not to be confused with filters. AdGuard Home drops DNS queries matching these domains, and these queries don't even appear in the query log. You can specify exact domain names, wildcards, or URL filter rules, e.g. "example.org", "*.example.org", or "||example.org^" correspondingly.)

||*^$dnstype=HTTPS
version.bind
id.server
hostname.bind

But here the filter has no effect? My fault oder isn't this possible here?

Best regards
Frank

**Comment by ainar-g** [comment]
Apologies for the long time it took us to respond.  We've added this feature in the most recent Edge version, v0.108.0-a.449+a772212d.  Could you check if this works for you now?
