### ISSUE TITLE
After Recent Edge Update, Nginx Keeps Throwing 502 Bad Gateway Almost All the Time

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#5469]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.429+137d2800

#### What did you do?

Updated via update prompt

#### Expected result

No side effects

#### Actual result

Nginx + AGH broken (May even be a core HTTP library causing this)

**Comment by ainar-g** [comment]
We recently updated the Go version to 1.19, but, as far as I know, that should not interfere with the HTTP API.  What errors are you seeing in the Nginx log and AdGuard Home's [verbose logs]?

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by RonKhondji** [comment]
If you have "limit_except GET POST HEAD {deny all;}" in your nginx.conf, you need to add 'PUT' to that.

**Comment by ainar-g** [comment]
What do you mean by “making the backend go over HTTPS”?  Removing Nginx and letting AGH handle the TLS connection or something else?

**Comment by ainar-g** [comment]
This is rather weird and shouldn't really be necessary.  Is `http_backend` an IP address?

**Comment by ainar-g** [comment]
I see.  I don't think I have any other guesses as to what could have changed.

**Comment by ainar-g** [comment]
@L8X, have you tried updating to v0.107.25?  If so, make sure that you've added `proxy_set_header Host $host;` in the AdGuard Home settings.  If that doesn't work, please send your verbose logs to devteam@adguard.com, and please add the words “AdGuard Home Issue 5469” to the subject line.
