### ISSUE TITLE
Why was CoreDns dropped?

### ISSUE THREAD

**Issue by ciokan** [AdguardTeam/AdGuardHome#547]
Just my curiosity. I took inspiration from your code to build a simple dns server for my own needs and today I noticed that CoreDns was dropped. Can you share with us why?

**Comment by ameshkov** [comment]
We explained it in the v0.92 release notes:
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.92

Briefly, here's the rationale behind that:

1. The DNS server is supposed to be a mere part of AdGuard Home. It is the main part at the moment, but it won't be like that forever.
2. If we had continued to use CoreDNS, we would have had to build everything around CoreDNS. It's just CoreDNS is supposed to be the center of a program, and it's hard to embed it.

**Comment by ciokan** [comment]
Exactly the feeling I had when they said CoreDns cannot be used as a library. Thanks for the clarification.
