### ISSUE TITLE
DNSSEC missing AD flag

### ISSUE THREAD

**Issue by Virsacer** [AdguardTeam/AdGuardHome#5479]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.23

#### What did you do?
Run perl script:

    use Net::DNS;
    my $resolver = new Net::DNS::Resolver(nameservers => "ADGUARD-IP", dnssec => 1, debug => 1);
    print "\n\nAD-flag: " . $resolver->send("example.com", "A")->header->ad . "\n";
#### Expected result
AD-flag: 1
#### Actual result
AD-flag: 0
#### Additional information
I enabled DNSSEC in Adguard.
When running the script there is no AD flag set in the result.
In the query-log there is a green lock for the query and the debug-output shows the RRSIG, so this part seems to be working.
And yes, 'example.com' is actually a signed domain.

When running the script using my bind9, google or cloudflare as nameserver the AD flag is set.

**Comment by ainar-g** [comment]
Thanks for the report! This should be fixed in the latest build on the Edge channel.  Could you please check if that works for you now?

**Comment by Virsacer** [comment]
Can confirm: The docker image with "edge" tag does work correctly.

Thank you for the quick fix :-)
