### ISSUE TITLE
AdGuard Home installed but dashboard is a blank screen

### ISSUE THREAD

**Issue by nagaden2** [AdguardTeam/AdGuardHome#548]
### Steps to reproduce

1. Install AdGuard Home using "How to run" instructions (placed in user directory)
2. Go to http://localhost:3000

### Expected behavior
Should see control panel/dashboard

### Actual behavior
The page is blank
<details><summary>Screenshot:</summary>
![screen shot 2019-01-14 at 4 56 32 pm](https://user-images.githubusercontent.com/46695503/51150975-adc50800-181d-11e9-994b-95448ab3efef.png)
</details>

### Your environment

|   Description  |     Value    |

| Version of AdGuard Home server:| .92 hotfix 2
| How did you setup DNS configuration:| System (could not set it up since I could not access the screen)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| OS X 10.7.5

**Comment by ameshkov** [comment]
What browser is it?

**Comment by nagaden2** [comment]
> What browser is it? (specify the browser version please)
It's Safari 6.1.6 (7537.78.2)

I am not certain everything was installed or configured correctly.

**Comment by ameshkov** [comment]
Tbh, I think our web interface simply does not work with the browsers so old.

@IldarKamalov can enlighten us on what are the minimum browser versions it supports.

**Comment by nagaden2** [comment]
Ah, OK.

I am going this route because originally I had trouble getting my router to _keep_ the DNS addresses. So, I thought I'd put my old Mac Mini to use but only got so far! Finally, I was able to add AdGuard on my router but I *still* see ads all over the place. I am not sure what else I could do? I also tried changing DNS on my Mac Network settings but that didn't seem to do anything either.

The next step is to use the browser extension...

**Comment by ameshkov** [comment]
> So, I thought I'd put my old Mac Mini to use but only got so far

You can open the admin panel from your normal computer (use the old Mac Mini address to do that). Also, you will anyway need to configure the DNS address in your router settings.

You see, AG Home is basically a DNS server, it won't do anything automatically.

> Finally, I was able to add AdGuard on my router but I still see ads all over the place

Execute this command in the terminal of your main computer: `nslookup ad.doubleclick.net`

If your devices are configured properly, you'll see smth like this: `** server can't find ad.doubleclick.net: NXDOMAIN`

**Comment by nagaden2** [comment]
What am I navigating to exactly on the Mac Mini to get the admin panel? The IP address is 192.168.0.37 and the install is at /Users/newuser/AdGuardian

**Comment by IldarKamalov** [comment]
> Tbh, I think our web interface simply does not work with the browsers so old.
> 
> @IldarKamalov can enlighten us on what are the minimum browser versions it supports.

Current browsers support – Chrome > 49, Firefox > 45, Safari > 9, Opera > 36

**Comment by nagaden2** [comment]
I installed Chrome Version 49.0.2623.112 (64-bit) and still cannot connect. I now get this message:

This site can’t be reached

localhost refused to connect.
ERR_CONNECTION_REFUSED

I tried http://localhost:3000/ and http://192.168.0.37:3000/

**Comment by nagaden2** [comment]
UPDATE: I ran the installer again and it works now! I can see the Dashboard in Chrome. 
nslookup ad.doubleclick.com is now showing it's blocked! Hooray!!
It did crap out on me but I re-ran the installer and it came back up. 

Thanks!

**Comment by ameshkov** [comment]
> However, even though my devices on the network reflect the AdGuard DNS entries, I still get ads like there's no protection. Any idea why this would not work?

You need to make sure (somehow) that they really use AG Home. Try opening `ad.doubleclick.net` in the browser, if it is not blocked - something is not okay and they don't use it.
