### ISSUE TITLE
Update breaks adguard

### ISSUE THREAD

**Issue by KruseLuds** [AdguardTeam/AdGuardHome#5481]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

4.7.6

#### What did you do?
Upgraded to 4.8.0, error lessages in the log and adguard not workiing. So I rolled back. (Note a few weeks back I upgraded to 4.7.8, which did not work so I rolled back to 4.7.6 then as well. I had thought I had entered a bug report for that release but I guess not... Also when people we discussing problems they had with the previous version that I could not use, it appears if people turn on IP6 then it would work - I tried but I am unabole to do that, talked to my ISP and they said IP6 was not yet available in my area.). 
#### Expected result
For Adguard to work.
#### Actual result
Adguard stopped working, since I use it as my DNS server I then lost internet access and had error messages in my log as well.
#### Additional information
When I try to view adguard it tells me the addon is not loaded, when I try to load it then it would try to load then unload itself again. Below is my current setup, and below that, a copy of the syslog sections with the error messages

## System Information

version | core-2023.2.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.10.0-21-arm64
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4843
Installed Version | 1.30.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 24

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 915.4 GB
disk_used | 13.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.11.0), Core DNS Override (0.1.1), Duck DNS (1.15.0), File editor (5.5.0), Home Assistant Google Drive Backup (0.110.1), Log Viewer (0.14.0), Mosquitto broker (6.1.3), Samba share (10.0.0), Terminal & SSH (9.6.1), AdGuard Home (4.7.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 15
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 16, 2023 at 6:55 PM
-- | --
current_recorder_run | February 12, 2023 at 6:12 PM
estimated_db_size | 1884.11 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

A snippet from my logs is also attached.

[syslogsnippet.txt](https://github.com/AdguardTeam/AdGuardHome/files/10717640/syslogsnippet.txt)

**Comment by ainar-g** [comment]
>  GitHub releases or script from README

Judging by the versions, you're using the Home Assistant plugin.

AdGuard Home shouldn't add any addresses into `dns.bind_hosts` by itself.  Reading through the recent commits of the Home Assistant plugin, there is [this one](https://github.com/hassio-addons/addon-adguard-home/commit/e2a804139853750abefaeded05902170b70705b1), which unconditionally adds `::1` as an address, which seems like a mistake.  I can see that that has already been mentioned in hassio-addons/addon-adguard-home#385.  I think, the addon maintainers should either roll that change back or make it take the machine's actual network setup into account and not add the IPv6 address if there is no IPv6 connectivity.

**Comment by KruseLuds** [comment]
@ainar-g thank you for the update - I thought there was a previous issue but I could not find it - sorry for the hassle and thank you for supplying a link to it! I am disheartened however, that that issue has been open for three weeks!

**Comment by KruseLuds** [comment]
Just to make life easier for folks reading this stuff later, as it is no longer an issue for me - steps to resolve (thank you @InToSSH  for the below):

pi@kruse-pi: sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
pi@kruse-pi: sudo ifdown lo
pi@kruse-pi: sudo ifup lo
pi@kruse-pi: sudo ip addr show lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

Running the latest flavor of adguard now does work, so to make it permanent, I updated update in: /etc/sysctl.conf, this statement
 from
net.ipv6.conf.all.disable_ipv6 = 1
 to
net.ipv6.conf.all.disable_ipv6 = 0
