### ISSUE TITLE
Adguard Home - Cisco IOX Docker Image

### ISSUE THREAD

**Issue by dvaguirre** [AdguardTeam/AdGuardHome#5484]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Run Arm64 AdGuardHome docker image in local Cisco switches/routers, to DoH/dnscrypt cloud AdGuardHome

#### Proposed solution
Pack Arm64 Adguard Home docker image using Cisco IOX client, in .tar format with package.yaml 

#### Alternatives considered
Use Cisco Umbrella that intercepts any DNS queries to send to OpenDNS servers. ANY (and you cant block some ads, malware etc unless you pay)

#### Additional information

https://developer.cisco.com/docs/app-hosting-ap/#!create-an-iox-application-package/create-packagetar

package.yaml sample

```
descriptor-schema-version: 2.8
info:
  name: adguardhome
  version: v0.107.23

app:
  type: docker
  cpuarch: aarch64

  resources:
    profile: custom
    cpu: 1000
    memory: 256
    disk: 256

  devices:
    network:
      -   
        interface-name: eth0
          ports:
              tcp:
              - 53
              - 80
              - 443
              - 853
              - 3000
              - 5443
              udp:
              - 53
              - 443
              - 784
              - 853
              - 5443
              - 8853

  startup:
    rootfs: rootfs.tar
    target: /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work
```

**Comment by dvaguirre** [comment]
https://github.com/etychon/iox-aarch64-hello-world

**Comment by ainar-g** [comment]
Hello.  I'm not quite sure, what your actual request is.

**Comment by dvaguirre** [comment]
> Hello. I'm not quite sure, what your actual request is.

modern Cisco devices can run Docker images (some can even run VM images), but you need to prepare those images.

I want AdGuardHome ready images to run on top of Cisco devices. I dont want to "prepare" every single update to run on it.

**Comment by ainar-g** [comment]
Sorry about the late response.  Just to be clear, is your request that we publish and support these Cisco images?  Because we'd rather not expand the list of packages/installation methods we support on our own for now.

**Comment by dvaguirre** [comment]
is the same arm64/x64 docker image, just need to pack in tar format with yaml. 
every single update need to spin up a arm64 at cloud, install docker, download adguard docker image, save/export, install Cisco IOx tools, tar pack with yaml, download and replace current image.
ps: and every 30 days need to replace letsencrypt cert, do u plan make somenthing to get those certs through gui, for ddns? would be amazing...

**Comment by ainar-g** [comment]
I don't think have the capacity to support this, sorry.  Feel free to make a fork.

 >  ps: and every 30 days need to replace letsencrypt cert, do u plan make somenthing to get those certs through gui, for ddns? would be amazing...

See #1603.
