### ISSUE TITLE
Upstream DNS adds active/standby mode

### ISSUE THREAD

**Issue by AEGEGE** [AdguardTeam/AdGuardHome#5485]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I have a usage scenario where I need to set the upstream dns of AdGuard Home to the address of other local software, but this will cause a problem. When there is a problem with that software, the entire network will not be able to resolve dns

#### Proposed solution
Upstream DNS adds active/standby mode，Use the primary upstream when the primary upstream is available, use the standby upstream when the primary upstream is unavailable, and switch back to the primary upstream when the primary upstream recovers

#### Alternatives considered
At present, the script is used to detect, if it is found that it cannot be parsed, the configuration file will be replaced, and the application will be reloaded

**Comment by ainar-g** [comment]
Sounds very similar to #3701?

**Comment by AEGEGE** [comment]
Exactly the same, looking forward to this feature, thanks！
