### ISSUE TITLE
Do it run on Asus Tinker Board S?

### ISSUE THREAD

**Issue by Golab** [AdguardTeam/AdGuardHome#549]
Hello I’m a Asus Tinker Board S user I’m wondering if your server program can be run on a Asus Tinker Board S? It’s almost like a Raspberry Pi 3, Tinker Board S has more memory and more cpu cores and faster CPU and 16 Gb Integrated eMMC disk

**Comment by hmage** [comment]
Yes, it should work. We didn't test Asus Tinker Board S specifically, but since it's an ARM processor with Linux, it should work. Just download an ARM binary from [the releases page](https://github.com/AdguardTeam/AdGuardHome/releases/latest).
