### ISSUE TITLE
Release "AdGuard Home v0.107.24" is broken [Service integration]

### ISSUE THREAD

**Issue by LerainL** [AdguardTeam/AdGuardHome#5496]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.23

#### What did you do?

Since yesterday there is a message about a new update (it's the v0.107.24)
![image](https://user-images.githubusercontent.com/57292109/219494255-441e277f-1132-4c96-8453-7eb6fe58e2d4.png)

If i click on the "Update Now" the GUI will get stuck

![image](https://user-images.githubusercontent.com/57292109/219494447-9bdab2ea-d79d-4c97-a5eb-4a83f395d964.png)

But if i open my local URL endpoint again (http://192.168.1.101/) i will see that the service is dead and actually i have the new version already pulled and the old version inside "agh-backup" folder.

If i go to services.msc and try to manually start the "AdGuard Home service" i will get this

![image](https://user-images.githubusercontent.com/57292109/219494690-68d8ddb9-5dbe-489f-8323-a9063d3499f1.png)

And if i bring back the old v0.107.23 version from "agh-backup" - everything works fine as before. I can start the service with no problem. 

![image](https://user-images.githubusercontent.com/57292109/219501508-f03d6eab-009e-42a3-b208-7daac907fb79.png)

So for me "v0.107.24" is completely broken regarding service integration.

I've tried to manually download it from here - same problem. The files pulled from the update and the ones from GitHub are identical.

![image](https://user-images.githubusercontent.com/57292109/219495293-93f7a5f7-95a0-4409-9fca-b40d7614feac.png)

#### Additional information

I've also tried the "AdGuard Home v0.108.0-b.27" version and that one have the same problem.

However, starting the new v0.107.24 version from "AdGuardHome.exe" directly as a cmd process will work. It will also work with the v0.108.0-b.27 version

![image](https://user-images.githubusercontent.com/57292109/219502030-929da10c-8181-42b8-8acd-4c60c3f67393.png)

So only the service integration is broken.

Please take a look at this problem. Gratitude

**Comment by LerainL** [comment]
I've also tried the "AdGuard Home v0.108.0-b.27" version and that one have the same problem. So what happened on 107.24 is obviously persisting.

**Comment by Nonsense112** [comment]
Same thing for me. This is the error from Event Viewer when I try to start the service:

_dnsforward.NewServer: initializing system resolvers: systemResolvers: can't get addresses: looking up cmd path: exec: "nslookup.exe": cannot run executable found relative to current directory_

**Comment by LerainL** [comment]
Ok, this might be just a stupid hunch but i've did some versions comparison and found out this:

![image](https://user-images.githubusercontent.com/57292109/219612765-2b743a1f-94a5-41f5-98cf-f6d5ced70d03.png)

"internal\dnsforward\dnsforward.go" had several changes, one of which is "dns64Pref**s**" to "dns64Pref"

So on version  v0.107.24 "dns64Pref" is changed almost everywhere, but not in config.go
![image](https://user-images.githubusercontent.com/57292109/219613549-6966d353-ac27-4193-8738-9f38f8e361a0.png)

If you got the "internal\dnsforward\config.go" - on the function createProxyConfig() - DNS64Prefs is still referenced as "DNS64Pref**s**" even in the new version.
![image](https://user-images.githubusercontent.com/57292109/219613047-09883812-3ac6-4c73-b9d4-71802b1690c9.png)

Might be something completely difrerent and unrelated, but i thought sharing wont hurt. Who knows..

**Comment by PVasileff** [comment]
Any with similar problem on linux (no docker) ? I have notification about new version v0.107.24 but may be I'll wait with update :)

**Comment by ppfeufer** [comment]
Updates on 2 Linux machines, no issues.

**Comment by kleinum** [comment]
Tried updating on 2.4.5 PfSense box and failed on service. Had to revert back to re-install v0.107.23 and then it worked again

**Comment by harnseen** [comment]
same issues

**Comment by LerainL** [comment]
Well, the problem was fixed in "AdGuard Home v0.107.25". Now everything is fine.

No idea what happened tho.

**Comment by mega-optimus** [comment]
I recently encountered the same problem, and saw the _"dnsforward.NewServer: initializing system resolvers: systemResolvers: can't get addresses: looking up cmd path: exec: "nslookup.exe": cannot run executable found relative to current directory"_  error message in debug log. 
After some experimentation, I think it is caused by **incompatibility of the yaml config file**, if you happen to keep the old one in place.

**Comment by mdimitrovg** [comment]
> Same thing for me. This is the error from Event Viewer when I try to start the service:
> 
> _dnsforward.NewServer: initializing system resolvers: systemResolvers: can't get addresses: looking up cmd path: exec: "nslookup.exe": cannot run executable found relative to current directory_

Hi, I keep having the issue with v0.107.32 on Win11 pro.
I solved it by adding a new system variable with variable name "GODEBUG" and variable value "execerrdot=0".
Now it's working fine as a service.

**Comment by Crlone** [comment]
> > Same thing for me. This is the error from Event Viewer when I try to start the service:
> > _dnsforward.NewServer: initializing system resolvers: systemResolvers: can't get addresses: looking up cmd path: exec: "nslookup.exe": cannot run executable found relative to current directory_
> 
> Hi, I keep having the issue with v0.107.32 on Win11 pro. I solved it by adding a new system variable with variable name "GODEBUG" and variable value "execerrdot=0". Now it's working fine as a service.

Thank you! I'm having this issue since v0.107.24,now it's finally working!
