### ISSUE TITLE
On Query Log svg "#chevron-down" is not showing on Safari and other Webkit Browser (Orion, SigmaOS)

### ISSUE THREAD

**Issue by bolopendem** [AdguardTeam/AdGuardHome#5505]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

macOS (aka Darwin)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.439+6f6ced33

#### What did you do?
On Query Log page, svg icon "#chevron-down" is not showing on Safari and other Webkit Browsers (Orion, SigmaOS), tested on Safari 16.3 and Safari Tech Preview 16.4. Still Showing on Safari 16.1, disappear after updating to Safari 16.3.

No problem on Chromium browser like Chrome, Opera, Brave, Vivaldi, and on Firefox

#### Expected result
Icon must showed on Safari and other webkit browsers

#### Actual result
Icon is not showing on Safari and other webkit browsers

#### Screenshots (if applicable)
[
<img width="1217" alt="SCR-20230218-jef" src="https://user-images.githubusercontent.com/75177014/219846574-fd72bf9e-172d-4adb-82fd-0de4ddb83011.png">
](url)
#### Additional information
macOS Ventura 13.2.1

**Comment by ainar-g** [comment]
Good day.  This should be fixed on the Edge channel.  Could you please check if the fix works for you?

**Comment by bolopendem** [comment]
@ainar-g great, it's all fixed now! Thank you so much!
<img width="380" alt="SCR-20230308-buib" src="https://user-images.githubusercontent.com/75177014/223508730-a47a7d0f-6c28-4611-a09e-5d75f8b00e18.png">
