### ISSUE TITLE
Random upstream server selection

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [AdguardTeam/AdGuardHome#5510]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

It would be nice to have an option to have AdGuard Home select random upstream server for each query. It would have to be fully random, not dependent on server response latency.

**Comment by PeterDaveHello** [comment]
Duplicated with #4751?
