### ISSUE TITLE
Add Multi-Factor Authentication and Fail2ban

### ISSUE THREAD

**Issue by jackspiering** [AdguardTeam/AdGuardHome#5512]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Adding an extra layer of authentication to protect sensitive DNS data.

#### Proposed solution
Add the possibility to authenticate to Adguard Home with key based and/or app based authentication. 

#### Alternatives considered
Add fail2ban to Adguard Home, or let the user decide when to block failed logins to the application.

#### Additional information
https://github.com/AdguardTeam/AdGuardHome/issues/1667
https://www.cr-t.com/blog/why-multi-factor-authentication-is-way-better-than-just-passwords/

**Comment by ainar-g** [comment]
Merging into #1667.
