### ISSUE TITLE
DNS-over-HTTP(behind HTTPS reverse proxy) not working, `Empty reply from server` since v0.107.24

### ISSUE THREAD

**Issue by PeterDaveHello** [AdguardTeam/AdGuardHome#5513]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Ubuntu 20.04.5 LTS

### CPU architecture

AMD64

### Installation

Docker 23.0.1

### Setup

On one machine

### AdGuard Home version

v0.107.24

#### What did you do?

Upgrade AdGuard Home from v0.107.23 to v0.107.24, than DoH via reverse proxy to AdGuard Home plain-text http service broken.

#### Expected result

The upgrade shouldn't break anything as there's no related changes mentioned, before the upgrade, use `curl` to test the query will get a DoH binary output.

#### Actual result

Use `curl` to send DoH HTTP GET request to the service with get `curl: (52) Empty reply from server` error.

#### Additional information

`allow_unencrypted_doh` is set to `true` in `AdGuardHome.yaml` already, manually change the `schema_version` back to `14` and rollback AdGuard Home from v0.107.24 to v0.107.23 will make everything working again.

**Comment by Disqu3-mirOir-qt** [comment]
you can't use GET in doh you need use POST and set json header

**Comment by PeterDaveHello** [comment]
> you can't use GET in doh you need use POST and set json header
>
> @Disqu3-mirOir-qt Are you sure? I don't even think a json header need to
be set.

**Comment by Disqu3-mirOir-qt** [comment]
yes this reason why delete my awnser json need set for talk with api not for doh request i think 

sorry

**Comment by PeterDaveHello** [comment]
Oh, okay, I got it, thanks!

**Comment by ainar-g** [comment]
The unit tests have already been added, and some other process changes are in the works.  Thanks for testing!
