### ISSUE TITLE
Better Checkmarks/Tick-marks + Dark Login screen for Dark Mode theme 

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [AdguardTeam/AdGuardHome#5515]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

This is just a cosmetic-related issue. When Dark Mode/Theme is applied, the login screen continues to use Light Mode/Theme and I think it should be darkened.

The checkmarks/tick-marks in boxes are hard to see when Dark Mode/Theme is enabled. They should be made darker (black or dark grey, but not light grey) to make them easier to see. They can also be made blue (like the blue dots marks).

**Comment by ainar-g** [comment]
@GY8VSdYYzvL8-K6T, the most recent update on the Edge channel fixes a few issues with the dark theme, including checkboxes for most browsers.  Can you please check?

 >  When Dark Mode/Theme is applied, the login screen continues to use Light Mode/Theme and I think it should be darkened.

It actually uses automatic theme detection, so if your OS and browser both send a theme preference for dark theme, it should use it as well.

**Comment by ainar-g** [comment]
We'll close this issue for now.  Feel free to file new ones if you find anything wrong with the dark theme or anything else.
