### ISSUE TITLE
Split Cache for EDNS0/ECS

### ISSUE THREAD

**Issue by L8X** [AdguardTeam/AdGuardHome#5521]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

When using ECS upstreams and results are cached, values are cached for the most recent request, rather than based on per client, meaning if a client from Germany was to request a domain, and then a client from the US requests the same domain, the US client gets the Germany client's response instead of it's own, defeating the purpose of ECS entirely.

#### Proposed solution

Add an option to split the cache based on ECS values / response values.

#### Alternatives considered

Turning off AGH's cache - this resulted in major performance losses

#### Additional information

Most major DNS resolvers like Google and Quad9 that support ECS do their own caching this way, so I believe AGH should have the ability to adopt this approach as well

**Comment by ainar-g** [comment]
ECS queries already use a separate cache.  Can you provide an example of a query that shows the problematic results?

**Comment by ainar-g** [comment]
@L8X, what exactly do you mean by “work correctly with AGH's ECS”?  Can  you provide an example of AGH settings (upstream, ECS, etc.) and a query that doesn't work as it should?
