### ISSUE TITLE
DHCP not working

### ISSUE THREAD

**Issue by Edgaras1995** [AdguardTeam/AdGuardHome#5524]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.25

#### What did you do?
reset
#### Additional information
DHCP server not workig

**Comment by ainar-g** [comment]
Please fill out the issue template, including steps you've made and whether or not there are error messages in the UI and in the log.
