### ISSUE TITLE
DNS Cache stats

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#553]
After using AdGuard Home instead of Pi-hole, I was wondering if there is a cache implementation like Pi-hole has, in order to reduce loading times?

**Comment by hmage** [comment]
It does cache requests, yes.

**Comment by hmage** [comment]
That sounds like a good idea, thanks! No promises when and if it's gonna be implemented.

**Comment by thb007** [comment]
Would there be any way to have this indicated in the UI? Like how many are currently cached (and the limit AdGuard will keep), and also display in the log which queries were cached?

**Comment by ameshkov** [comment]
@thb007 I guess that's what this feature request is about

**Comment by ibksturm** [comment]
vote +1

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1214

**Comment by handcoding** [comment]
For whatever it’s worth, it looks like #1453 may be along similar lines?

**Comment by ainar-g** [comment]
Merging into #1453.
