### ISSUE TITLE
Request to update the API changelog with changes in AdGuard Home v0.107.24

### ISSUE THREAD

**Issue by jojost1** [AdguardTeam/AdGuardHome#5533]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

I was reading the [AdGuard Home v0.107.24 changelog](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.24) and I think there have been some changes to the API. However, [the API changelog only mentions changes in v0.107.23](https://github.com/AdguardTeam/AdGuardHome/blob/master/openapi/CHANGELOG.md#v010723-api-changes).

#### Proposed solution

Could the API changelog be updated please? 😄 it would help me a lot in making sure I properly change my third party app to comply.

Thank you!

**Comment by ainar-g** [comment]
Hello.  There were no changes to API in that release, only in configuration.  At least, that was the intent.  Or do you want to report an unintended API change?

**Comment by jojost1** [comment]
Ah, I was assuming there would be some API changes - my bad. Nevermind then! Thanks for your reply 😄
