### ISSUE TITLE
Editable DNS rewrites

### ISSUE THREAD

**Issue by SpinDreams** [AdguardTeam/AdGuardHome#5534]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Please make it possible to edit DNS rewrite entries

**Comment by fernvenue** [comment]
You can use Custom filtering rules with [https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists) to do that.

**Comment by ainar-g** [comment]
Duplicate of #1577
