### ISSUE TITLE
Abort "Domain or client" search on query log breaks query log view

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardHome#5546]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.25

#### What did you do?

1. Go to Query Log
2. Start search something without quick result, so that AG actually shows a loading circle to search (it's better to have a big Query logs retention)
3. Abort the search in searchbar on the X -> the query log will freak out

It looks like the query log is rapidly refreshing. Like showing requests in real time ... finally ( ͡° ͜ʖ ͡°)

#### Expected result

Aborting the search and continue normally where I left before start searching

#### Actual result

query log is rapidly refreshing. You still can use the top navigation

#### Video

https://user-images.githubusercontent.com/6276915/221667992-5d6cee04-f140-4b54-9edb-b63e3765eca9.mp4

**Comment by ainar-g** [comment]
Good day.  This should be fixed on the Edge channel.  Could you please check if the fix works for you?

**Comment by Morku** [comment]
Thank you. I will test on Thursday/Friday.
