### ISSUE TITLE
Eating a lot of RAM

### ISSUE THREAD

**Issue by ookangzheng** [AdguardTeam/AdGuardHome#555]
I'm using Debian9 on VPS 1gb, 1 core ( 3.2ghz), 40gb SSD.
I have almost 60 connections using the DNS server
Around 1 hour, the program almost eats 600~700MB of RAM.
While I use pi-hole, just around 300MB
Is there any way to optimize it?

**Comment by ibksturm** [comment]
as an idear, you could use nginx as a loadbalancer

see my solution on ibksturm.synology.me (running public dns server)

solution found public under [https://github.com/ibksturm/dnscrypt-switzerland](https://github.com/ibksturm/dnscrypt-switzerland)

**Comment by ookangzheng** [comment]
What does AGH stand for?

**Comment by ibksturm** [comment]
AdGuardHome......

**Comment by ameshkov** [comment]
I guess this should be marked as a duplicate of #714
