### ISSUE TITLE
Devices do not have internet access when using Adguard for DHCP

### ISSUE THREAD

**Issue by dalepmay7** [AdguardTeam/AdGuardHome#5554]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)
Running in Docker, on DietPi on a NanoPi Neo3

### CPU architecture

ARMv7

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.25

### Description

Enable DHCP Server

Expected internet to work on connected devices.

Devices are able to obtain an IP address in the specified range, but no internet access.

DHCP Interface: eth0 - 192.168.7.5
Gateway IP: 192.168.7.1
Range of IP Addresses: 192.168.7.100 - 192.168.7.200
Subnet Mask: 255.255.255.0

**Comment by ainar-g** [comment]
Hello.  A few questions:

1.  What kind of network adapter are you using with Docker?  [As documented][1], we recommend using `--network host`.

2.  Are there any errors or suspicious data in AdGuard Home's [verbose logs][2]?

3.  Are there any errors in the logs of the DHCP clients?  On Debian, you can use `sudo grep -F -e dhcp -i -- /var/log/syslog`.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#dhcp
[2]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by lucascbd** [comment]
I have the exact same problem.
