### ISSUE TITLE
Error: control/dns_config | decoding request: attempted to read more than 65536 bytes | 400

### ISSUE THREAD

**Issue by Hzao** [AdguardTeam/AdGuardHome#5565]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.25

#### What did you do?
Due to the special network environment in China, I want to set up **upstream DNS server rules**. I found a list of commonly used websites in China and wanted AdGuard Home to use the Chinese domestic upstream DNS server when encountering them, and use the foreign DNS upstream server for all websites other than that. This will maximize DNS query speed while preventing DNS hijacking by the government. (Yes, foreign DNS upstream servers do not have nodes in China, so latency is high when accessing them)

So I pasted the rule to make AdGuard Home refer to Chinese domestic upstream DNS server when processing a list of Chinese domains.

#### Expected result
AdGuard Home save the rules successfully.

#### Actual result
An error popped up with a message: **Error: control/dns_config | decoding request: attempted to read more than 65536 bytes | 400**

#### Screenshots (if applicable)
![CleanShot 2023-03-05 at 19 15 59@2x](https://user-images.githubusercontent.com/53562907/222957188-206eb3f5-ae0c-43c2-bce3-09c2922aebf6.jpg)

#### Additional information
This issue is very similar to issue #2675. However, that issue is about configuring filter rules, while this one is about configuring upstream DNS server. Since that issue has been fixed, I believe this one can also be done easily using the same fix method.

If you want to reproduce this issue, you can add this sample upstream DNS server rule to Settings->DNS settings->Upstream DNS servers. Sample download link:https://cloud.hzao.top/s/jKUW

**Comment by Hzao** [comment]
If you want to reproduce this issue, you can add this sample upstream DNS server rule to Settings->DNS settings->Upstream DNS servers.  Sample download link:https://cloud.hzao.top/s/jKUW

**Comment by ainar-g** [comment]
Hello.  Large upstream configurations should be set using an upstream file and the `dns.upstream_dns_file` configuration option.  [Our documentation][1] explicitly mentions the China use-case.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file

**Comment by Hzao** [comment]
> Hello. Large upstream configurations should be set using an upstream file and the `dns.upstream_dns_file` configuration option. [Our documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file) explicitly mentions the China use-case.

I am very sorry for not carefully reading the documentation. I just found this similar to #2675 so I assumed it's something that needs to be fixed. Thank you for your help and patience.
