### ISSUE TITLE
Google winning Top Blocked Domains with 2000% and nothing in Query Log

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdGuardHome#5568]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.25

#### What did you do?

Keep the dashboard open in a pinned tab and refresh the page periodically. Set to hold 7 days of metrics / logs.

#### Expected result

See correct metrics, changing over time.

#### Actual result

The Top Blocked Domains box on the dashboard shows `www.google.com` in first place with over 2000% representation, but there are no results when looking for blocked entries in the Query Log.

I haven't seen anything like this before, so I assume it's since the last update but with nothing in the Query Log to check dates against I can't say for sure.

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1901532/222979690-76bd15ee-ce71-4ccb-a819-2c3fc3dc1a9f.png)

![image](https://user-images.githubusercontent.com/1901532/222979781-52d13740-a392-4788-90ab-d8ffc10e7b6f.png)

#### Additional information

Running on a Raspberry Pi 4 (ARMv8) using the official OS release, acting as the primary DNS for my home router over Ethernet.

**Comment by Ultrabenosaurus** [comment]
It looks like Top Blocked Domains might be hooked into the Enforce Safe Search option.

![image](https://user-images.githubusercontent.com/1901532/222980010-a308c883-a114-4c74-9886-b143bda0f240.png)

![image](https://user-images.githubusercontent.com/1901532/222980068-49b9661d-033d-4dc2-b93e-7843826e1748.png)

**Comment by ainar-g** [comment]
Hello.  It being in this part of the statistics isn't a bug, but the percentage very clearly is.

@Blakhard, it seems like `num_replaced_safesearch` is ignored when calculating the total number of blocked/processed domains.  Is there a reason for that, or is it just a bug?

**Comment by ainar-g** [comment]
We have made a few fixes in the Edge channel recently.  Could you please check if the numbers look saner now?

**Comment by ainar-g** [comment]
We'll close the issue for now.  Please feel free to reopen if the issue reappears.
