### ISSUE TITLE
System wont update

### ISSUE THREAD

**Issue by Cah1982** [AdguardTeam/AdGuardHome#5574]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

Custom port

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

Version:  v0.108.0-a.449+a772212d

### Description

When i run update i get the below

2023/03/07 12:42:21.428405 [info] AdGuard Home, version v0.108.0-a.449+a772212d
2023/03/07 12:42:21.435825 [info] tls: using default ciphers
2023/03/07 12:42:21.446393 [info] dnsproxy: cache: enabled, size 4096 b
2023/03/07 12:42:21.446441 [info] MaxGoroutines is set to 300
2023/03/07 12:42:21.447184 [info] cmdline update: performing update
2023/03/07 12:42:21.772592 [info] updater: updating
2023/03/07 12:42:21.884575 [error] updater: failed: downloading package file: io.ReadAll() failed: attempted to read more than 327680 bytes
2023/03/07 12:42:21.884737 [fatal] downloading package file: io.ReadAll() failed: attempted to read more than 327680 bytes

**Comment by ainar-g** [comment]
Thanks for reporting!  This bug was accidentally introduced in one of the Edge channel commits and fixed in ae653f166f244e7066d558e9bef3aed67af36e27.  Please follow the [instructions for manual update][1].  All versions after that should not have that bug.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update

**Comment by Cah1982** [comment]
cheers, how do I find out which version i need

'https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz'

As the above will be wrong

**Comment by ainar-g** [comment]
You'll probably want the link to the latest Edge release.  All such links are collected on our [_Platforms_ page](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms).

```none
https://static.adguard.com/adguardhome/edge/AdGuardHome_linux_amd64.tar.gz
````

**Comment by Cah1982** [comment]
Sorry what i mean is this is oing on a NanoPi r4s, not a AMD platfor but looking up the chip it says ARM8

but i can only see upto ARMv7 on downloads

**Comment by ainar-g** [comment]
ARMv8 is a 64-bit ARM, so you can download that one.
