### ISSUE TITLE
0.107.26 and new Beta version can‘t work

### ISSUE THREAD

**Issue by monsm** [AdguardTeam/AdGuardHome#5579]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv5

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.26、0.108.0-b.28、0.108.0-b.29、0.108.0-b.29

### Description

Here is the boot log for 0.107.25：
-----******------
2023/03/10 02:17:57.953013 [info] AdGuard Home, version v0.107.25
2023/03/10 02:17:58.033779 [info] tls: using default ciphers
2023/03/10 02:17:58.035072 [error] hosts container: host "RT-AC3100-C207." is invalid, ignoring
2023/03/10 02:17:58.057049 [info] Initializing auth module: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/data/sessions.db
2023/03/10 02:17:58.073383 [info] auth: initialized.  users:1  sessions:5
2023/03/10 02:17:58.073532 [info] web: initializing
2023/03/10 02:17:59.634014 [info] dnsproxy: cache: enabled, size 4096 b
2023/03/10 02:17:59.634109 [info] MaxGoroutines is set to 300
2023/03/10 02:17:59.636756 [info] AdGuard Home is available at the following addresses:
2023/03/10 02:17:59.639953 [info] go to http://127.0.0.1:3000
2023/03/10 02:17:59.640020 [info] go to http://127.0.1.1:3000
2023/03/10 02:17:59.640057 [info] go to http://[::1]:3000
2023/03/10 02:17:59.640088 [info] go to http://[fe80::ac6f:3ff:fe76:de50%ifb0]:3000
2023/03/10 02:17:59.640119 [info] go to http://[fe80::8499:feff:fecf:3809%ifb1]:3000
2023/03/10 02:17:59.640148 [info] go to http://[fe80::200:ff:fe00:0%fwd0]:3000
2023/03/10 02:17:59.640176 [info] go to http://[fe80::200:ff:fe00:0%fwd1]:3000
2023/03/10 02:17:59.640205 [info] go to http://[fe80::200:ff:fe00:0%agg]:3000
2023/03/10 02:17:59.640233 [info] go to http://[fe80::200:ff:fe00:0%dpsta]:3000
2023/03/10 02:17:59.640261 [info] go to http://[fe80::6adb:54ff:fe43:c207%eth1]:3000
2023/03/10 02:17:59.640289 [info] go to http://[fe80::6adb:54ff:fe43:c209%eth2]:3000
2023/03/10 02:17:59.640318 [info] go to http://[fe80::6adb:54ff:fe43:c207%vlan1]:3000
2023/03/10 02:17:59.640347 [info] go to http://[fe80::6adb:54ff:fe43:c207%vlan2]:3000
2023/03/10 02:17:59.640373 [info] go to http://192.168.50.1:3000
2023/03/10 02:17:59.640408 [info] go to http://[fe80::6adb:54ff:fe43:c207%br0]:3000
2023/03/10 02:17:59.640454 [info] go to http://211.161.154.172:3000
2023/03/10 02:18:17.397225 [info] Starting the DNS proxy server
2023/03/10 02:18:17.397326 [info] Ratelimit is enabled and set to 20 rps
2023/03/10 02:18:17.397380 [info] The server is configured to refuse ANY requests
2023/03/10 02:18:17.397418 [info] dnsproxy: cache: enabled, size 4194304 b
2023/03/10 02:18:17.397490 [info] MaxGoroutines is set to 300
2023/03/10 02:18:17.397601 [info] Creating the UDP server socket
2023/03/10 02:18:17.397915 [info] Listening to udp://[::]:53
2023/03/10 02:18:17.398074 [info] Creating a TCP server socket
2023/03/10 02:18:17.398254 [info] Listening to tcp://[::]:53
2023/03/10 02:18:17.398576 [info] Entering the UDP listener loop on [::]:53
2023/03/10 02:18:17.399123 [info] Entering the tcp listener loop on [::]:53
-----*****-----

Here is the boot log for 0.107.26、0.108.0-b.28、0.108.0-b.29、0.108.0-b.29：
-----*****-----
2023/03/10 02:17:53.953013 [info] AdGuard Home, version v0.107.26
2023/03/10 02:17:54.033779 [info] tls: using default ciphers
-----*****-----

The log is so short that no other logs are written after waiting too long，new version can't work for me

**Comment by ainar-g** [comment]
Hello.  Please enable the [verbose logs][1] to diagnose the issue.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by monsm** [comment]
Booted twice without success, here is the  log
-----*****-----


2023/03/11 08:53:44.736049 8825#1 [info] AdGuard Home, version v0.107.26
2023/03/11 08:53:44.792588 8825#1 [debug] current working directory is /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome
2023/03/11 08:53:44.793290 8825#1 [debug] reading config file: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/AdGuardHome.yaml
2023/03/11 08:53:44.802178 8825#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 16
2023/03/11 08:53:44.802465 8825#1 [info] Upgrade yaml: 16 to 17
2023/03/11 08:53:44.904225 8825#1 [info] tls: using default ciphers
2023/03/11 08:53:44.905488 8825#1 [debug] hosts container: starting
2023/03/11 08:53:44.905774 8825#1 [debug] hosts container: refreshing
2023/03/11 08:53:44.906371 8825#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost.localdomain"
2023/03/11 08:53:44.906824 8825#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"

-----****-----


2023/03/11 08:54:35.967310 9042#1 [info] AdGuard Home, version v0.107.26
2023/03/11 08:54:35.979848 9042#1 [debug] current working directory is /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome
2023/03/11 08:54:35.980376 9042#1 [debug] reading config file: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/AdGuardHome.yaml
2023/03/11 08:54:35.988818 9042#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 17
2023/03/11 08:54:35.989167 9042#1 [debug] reading config file: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/AdGuardHome.yaml
2023/03/11 08:54:35.998672 9042#1 [info] tls: using default ciphers
2023/03/11 08:54:35.999801 9042#1 [debug] hosts container: starting
2023/03/11 08:54:36.000041 9042#1 [debug] hosts container: refreshing
2023/03/11 08:54:36.000784 9042#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost.localdomain"
2023/03/11 08:54:36.001134 9042#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"

**Comment by monsm** [comment]
here is 0.107.25 log

-----*****-----

2023/03/11 09:01:18.786711 9818#1 [info] AdGuard Home, version v0.107.25
2023/03/11 09:01:18.797620 9818#1 [debug] current working directory is /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome
2023/03/11 09:01:18.798580 9818#1 [debug] reading config file: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/AdGuardHome.yaml
2023/03/11 09:01:18.806159 9818#1 [debug] github.com/AdguardTeam/AdGuardHome/internal/home.upgradeConfig(): got schema version 16
2023/03/11 09:01:18.806496 9818#1 [debug] reading config file: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/AdGuardHome.yaml
2023/03/11 09:01:18.815341 9818#1 [info] tls: using default ciphers
2023/03/11 09:01:18.816750 9818#1 [debug] hosts container: starting
2023/03/11 09:01:18.816999 9818#1 [debug] hosts container: refreshing
2023/03/11 09:01:18.817644 9818#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost.localdomain"
2023/03/11 09:01:18.817995 9818#1 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"
2023/03/11 09:01:18.818257 9818#1 [error] hosts container: host "RT-AC3100-C207." is invalid, ignoring
2023/03/11 09:01:18.818592 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"RT-AC3100-C207"
2023/03/11 09:01:18.819035 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"RT-AC3100-C207.local"
2023/03/11 09:01:18.819443 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusrouter.com"
2023/03/11 09:01:18.819818 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrouter.com"
2023/03/11 09:01:18.820204 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusrepeater.com"
2023/03/11 09:01:18.820513 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrepeater.com"
2023/03/11 09:01:18.820810 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusap.com"
2023/03/11 09:01:18.821118 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusap.com"
2023/03/11 09:01:18.821452 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusswitch.com"
2023/03/11 09:01:18.821764 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusswitch.com"
2023/03/11 09:01:18.822134 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"router.asus.com"
2023/03/11 09:01:18.822483 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"repeater.asus.com"
2023/03/11 09:01:18.822794 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"ap.asus.com"
2023/03/11 09:01:18.823120 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusnetwork.net"
2023/03/11 09:01:18.823433 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusswitch.net"
2023/03/11 09:01:18.823733 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrepeater.net"
2023/03/11 09:01:18.824034 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusap.net"
2023/03/11 09:01:18.824370 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"zenwifi.net"
2023/03/11 09:01:18.824863 9818#1 [debug] hosts container: added ip-host pair "192.168.50.1"-"expertwifi.net"
2023/03/11 09:01:18.825229 9818#1 [debug] hosts container: added ip-host pair "::1"-"ip6-localhost"
2023/03/11 09:01:18.825538 9818#1 [debug] hosts container: added ip-host pair "::1"-"ip6-loopback"
2023/03/11 09:01:18.825841 9818#1 [debug] hosts container: added ip-host pair "fe00::"-"ip6-localnet"
2023/03/11 09:01:18.826142 9818#1 [debug] hosts container: added ip-host pair "ff00::"-"ip6-mcastprefix"
2023/03/11 09:01:18.826441 9818#1 [debug] hosts container: added ip-host pair "ff02::1"-"ip6-allnodes"
2023/03/11 09:01:18.826781 9818#1 [debug] hosts container: added ip-host pair "ff02::2"-"ip6-allrouters"
2023/03/11 09:01:18.830025 9818#1 [debug] hosts container: sending upd
2023/03/11 09:01:18.834368 9818#1 [debug] filtering: initialized 48 services
2023/03/11 09:01:18.834835 9818#1 [debug] dhcpd: warning: creating dhcpv4 srv: dhcpv4: invalid IP is not an IPv4 address
2023/03/11 09:01:18.835787 9818#1 [debug] clients: added "主路由器": ID:["192.168.50.1" "127.0.0.1"] [1]
2023/03/11 09:01:18.836024 9818#1 [debug] clients: added "副路由器": ID:["192.168.50.17"] [2]
2023/03/11 09:01:18.836284 9818#1 [debug] clients: added "q": ID:["192.168.50.121" "192.168.50.156"] [3]
2023/03/11 09:01:18.836517 9818#1 [debug] clients: added "z": ID:["192.168.50.141" "192.168.50.242" "192.168.50.208"] [4]
2023/03/11 09:01:18.836732 9818#1 [debug] clients: added "油烟机": ID:["192.168.50.164"] [5]
2023/03/11 09:01:18.836928 9818#1 [debug] clients: added "洗衣机": ID:["192.168.50.52"] [6]
2023/03/11 09:01:18.837119 9818#1 [debug] clients: added "电脑": ID:["192.168.50.32"] [7]
2023/03/11 09:01:18.837330 9818#1 [debug] clients: added "电视": ID:["192.168.50.13"] [8]
2023/03/11 09:01:18.837538 9818#1 [debug] clients: added "电饭煲": ID:["192.168.50.110"] [9]
2023/03/11 09:01:18.837751 9818#1 [debug] clients: added "x": ID:["192.168.50.167" "192.168.50.3" "192.168.50.186"] [10]
2023/03/11 09:01:18.837954 9818#1 [debug] clients: removed 0 client aliases
2023/03/11 09:01:18.838143 9818#1 [debug] clients: added 0 client aliases from dhcp
2023/03/11 09:01:18.838530 9818#9 [debug] clients: removed 0 client aliases
2023/03/11 09:01:18.838618 9818#1 [debug] writing config file "/tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/AdGuardHome.yaml"
2023/03/11 09:01:18.838865 9818#9 [debug] clients: added ff02::2 -> "ip6-allrouters" [1]
2023/03/11 09:01:18.839055 9818#9 [debug] clients: added 127.0.0.1 -> "localhost.localdomain" [2]
2023/03/11 09:01:18.839229 9818#9 [debug] clients: added 192.168.50.1 -> "RT-AC3100-C207" [3]
2023/03/11 09:01:18.839494 9818#9 [debug] clients: added ::1 -> "ip6-localhost" [4]
2023/03/11 09:01:18.839680 9818#9 [debug] clients: added fe00:: -> "ip6-localnet" [5]
2023/03/11 09:01:18.839836 9818#9 [debug] clients: added ff00:: -> "ip6-mcastprefix" [6]
2023/03/11 09:01:18.839986 9818#9 [debug] clients: added ff02::1 -> "ip6-allnodes" [7]
2023/03/11 09:01:18.840121 9818#9 [debug] clients: added 7 client aliases from system hosts file
2023/03/11 09:01:18.876135 9818#1 [info] Initializing auth module: /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/data/sessions.db
2023/03/11 09:01:18.929487 9818#1 [debug] auth: loaded 5 sessions from DB (removed 1 expired)
2023/03/11 09:01:18.929664 9818#1 [info] auth: initialized.  users:1  sessions:5
2023/03/11 09:01:18.929937 9818#1 [info] web: initializing
2023/03/11 09:01:18.930366 9818#1 [debug] stats: opening database
2023/03/11 09:01:18.989979 9818#1 [debug] stats: database opened
2023/03/11 09:01:18.990215 9818#1 [debug] stats: deleting old units until id 464096
2023/03/11 09:01:19.012402 9818#1 [debug] stats: initialized
2023/03/11 09:01:19.013045 9818#1 [debug] filtering: loading filter 1674552952 from /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/data/filters/1674552952.txt
2023/03/11 09:01:19.013304 9818#1 [debug] filtering: file /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/data/filters/1674552952.txt, id 1674552952, length 19453432
2023/03/11 09:01:20.655490 9818#1 [debug] filtering: loading filter 1674552953 from /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/data/filters/1674552953.txt
2023/03/11 09:01:20.655834 9818#1 [debug] filtering: file /tmp/mnt/sda1/asusware.arm/etc/AdGuardHome/data/filters/1674552953.txt, id 1674552953, length 25626
2023/03/11 09:01:20.662528 9818#1 [debug] dnsforward: added 0 a and ptr entries from dhcp
2023/03/11 09:01:20.663006 9818#1 [debug] Bootstraps: [9.9.9.10 149.112.112.10 2620:fe::10 2620:fe::fe:10 211.161.157.232 10.206.8.58]
2023/03/11 09:01:20.663265 9818#1 [debug] Upstream 0: 223.6.6.6:53
2023/03/11 09:01:20.663479 9818#1 [debug] Upstream 1: 119.29.29.29:53
2023/03/11 09:01:20.663675 9818#1 [debug] Upstream 2: 114.114.114.114:53
2023/03/11 09:01:20.663946 9818#1 [debug] Upstream 3: 211.161.157.232:53
2023/03/11 09:01:20.664143 9818#1 [debug] Upstream 4: 10.206.8.58:53
2023/03/11 09:01:20.664334 9818#1 [debug] Upstream 5: 8.8.8.8:53
2023/03/11 09:01:20.664525 9818#1 [debug] Upstream 6: 149.112.112.112:53
2023/03/11 09:01:20.664853 9818#1 [debug] Upstream 7: 101.226.4.6:53
2023/03/11 09:01:20.665098 9818#1 [debug] Upstream 8: 117.50.10.10:53
2023/03/11 09:01:20.665368 9818#1 [info] dnsproxy: cache: enabled, size 4096 b
2023/03/11 09:01:20.665560 9818#1 [info] MaxGoroutines is set to 300
2023/03/11 09:01:20.666870 9818#1 [debug] upstreams to resolve PTR for local addresses: [10.206.8.58 211.161.157.232]
2023/03/11 09:01:20.667199 9818#1 [debug] Upstream 0: 10.206.8.58:53
2023/03/11 09:01:20.667420 9818#1 [debug] Upstream 1: 211.161.157.232:53
2023/03/11 09:01:20.667787 9818#1 [debug] web: applying new tls configuration
2023/03/11 09:01:20.674875 9818#1 [info] AdGuard Home is available at the following addresses:
2023/03/11 09:01:20.677956 9818#1 [info] go to http://127.0.0.1:3000
2023/03/11 09:01:20.678219 9818#1 [info] go to http://127.0.1.1:3000
2023/03/11 09:01:20.678408 9818#1 [info] go to http://[::1]:3000
2023/03/11 09:01:20.678589 9818#1 [info] go to http://[fe80::ac6f:3ff:fe76:de50%ifb0]:3000
2023/03/11 09:01:20.678764 9818#1 [info] go to http://[fe80::8499:feff:fecf:3809%ifb1]:3000
2023/03/11 09:01:20.678924 9818#1 [info] go to http://[fe80::200:ff:fe00:0%fwd0]:3000
2023/03/11 09:01:20.679079 9818#1 [info] go to http://[fe80::200:ff:fe00:0%fwd1]:3000
2023/03/11 09:01:20.679238 9818#1 [info] go to http://[fe80::200:ff:fe00:0%agg]:3000
2023/03/11 09:01:20.679404 9818#1 [info] go to http://[fe80::200:ff:fe00:0%dpsta]:3000
2023/03/11 09:01:20.679566 9818#1 [info] go to http://[fe80::6adb:54ff:fe43:c207%eth1]:3000
2023/03/11 09:01:20.679721 9818#1 [info] go to http://[fe80::6adb:54ff:fe43:c209%eth2]:3000
2023/03/11 09:01:20.679874 9818#1 [info] go to http://[fe80::6adb:54ff:fe43:c207%vlan1]:3000
2023/03/11 09:01:20.680026 9818#1 [info] go to http://[fe80::6adb:54ff:fe43:c207%vlan2]:3000
2023/03/11 09:01:20.680178 9818#1 [info] go to http://192.168.50.1:3000
2023/03/11 09:01:20.680335 9818#1 [info] go to http://[fe80::6adb:54ff:fe43:c207%br0]:3000
2023/03/11 09:01:20.680493 9818#1 [info] go to http://211.161.154.172:3000
2023/03/11 09:01:23.061147 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:23.069189 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 8.178686ms
2023/03/11 09:01:24.570765 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:24.574206 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 3.2667ms
2023/03/11 09:01:26.582820 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:26.587239 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 4.485049ms
2023/03/11 09:01:27.649736 9818#8 [debug] hosts container: refreshing
2023/03/11 09:01:27.650469 9818#8 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost.localdomain"
2023/03/11 09:01:27.650928 9818#8 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"
2023/03/11 09:01:27.651203 9818#8 [error] hosts container: host "RT-AC3100-C207." is invalid, ignoring
2023/03/11 09:01:27.651525 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"RT-AC3100-C207"
2023/03/11 09:01:27.651939 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"RT-AC3100-C207.local"
2023/03/11 09:01:27.652343 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusrouter.com"
2023/03/11 09:01:27.652721 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrouter.com"
2023/03/11 09:01:27.653160 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusrepeater.com"
2023/03/11 09:01:27.653466 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrepeater.com"
2023/03/11 09:01:27.653723 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusap.com"
2023/03/11 09:01:27.653954 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusap.com"
2023/03/11 09:01:27.654198 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusswitch.com"
2023/03/11 09:01:27.654448 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusswitch.com"
2023/03/11 09:01:27.674833 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"router.asus.com"
2023/03/11 09:01:27.675232 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"repeater.asus.com"
2023/03/11 09:01:27.675679 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"ap.asus.com"
2023/03/11 09:01:27.676059 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusnetwork.net"
2023/03/11 09:01:27.676344 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusswitch.net"
2023/03/11 09:01:27.676672 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrepeater.net"
2023/03/11 09:01:27.677098 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusap.net"
2023/03/11 09:01:27.677384 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"zenwifi.net"
2023/03/11 09:01:27.677714 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"expertwifi.net"
2023/03/11 09:01:27.677996 9818#8 [debug] hosts container: added ip-host pair "::1"-"ip6-localhost"
2023/03/11 09:01:27.678234 9818#8 [debug] hosts container: added ip-host pair "::1"-"ip6-loopback"
2023/03/11 09:01:27.678471 9818#8 [debug] hosts container: added ip-host pair "fe00::"-"ip6-localnet"
2023/03/11 09:01:27.678793 9818#8 [debug] hosts container: added ip-host pair "ff00::"-"ip6-mcastprefix"
2023/03/11 09:01:27.679050 9818#8 [debug] hosts container: added ip-host pair "ff02::1"-"ip6-allnodes"
2023/03/11 09:01:27.679338 9818#8 [debug] hosts container: added ip-host pair "ff02::2"-"ip6-allrouters"
2023/03/11 09:01:27.679530 9818#8 [debug] hosts container: no changes detected
2023/03/11 09:01:27.679645 9818#8 [debug] hosts container: refreshing
2023/03/11 09:01:27.680116 9818#8 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost.localdomain"
2023/03/11 09:01:27.680383 9818#8 [debug] hosts container: added ip-host pair "127.0.0.1"-"localhost"
2023/03/11 09:01:27.680570 9818#8 [error] hosts container: host "RT-AC3100-C207." is invalid, ignoring
2023/03/11 09:01:27.680792 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"RT-AC3100-C207"
2023/03/11 09:01:27.681135 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"RT-AC3100-C207.local"
2023/03/11 09:01:27.681379 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusrouter.com"
2023/03/11 09:01:27.681615 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrouter.com"
2023/03/11 09:01:27.681867 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusrepeater.com"
2023/03/11 09:01:27.682200 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrepeater.com"
2023/03/11 09:01:27.682454 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusap.com"
2023/03/11 09:01:27.682693 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusap.com"
2023/03/11 09:01:27.682924 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusswitch.com"
2023/03/11 09:01:27.683249 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusswitch.com"
2023/03/11 09:01:27.683561 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"router.asus.com"
2023/03/11 09:01:27.683881 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"repeater.asus.com"
2023/03/11 09:01:27.684276 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"ap.asus.com"
2023/03/11 09:01:27.694747 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"www.asusnetwork.net"
2023/03/11 09:01:27.695168 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusswitch.net"
2023/03/11 09:01:27.695437 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusrepeater.net"
2023/03/11 09:01:27.695706 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"asusap.net"
2023/03/11 09:01:27.696018 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"zenwifi.net"
2023/03/11 09:01:27.696271 9818#8 [debug] hosts container: added ip-host pair "192.168.50.1"-"expertwifi.net"
2023/03/11 09:01:27.696546 9818#8 [debug] hosts container: added ip-host pair "::1"-"ip6-localhost"
2023/03/11 09:01:27.696779 9818#8 [debug] hosts container: added ip-host pair "::1"-"ip6-loopback"
2023/03/11 09:01:27.697096 9818#8 [debug] hosts container: added ip-host pair "fe00::"-"ip6-localnet"
2023/03/11 09:01:27.697381 9818#8 [debug] hosts container: added ip-host pair "ff00::"-"ip6-mcastprefix"
2023/03/11 09:01:27.697641 9818#8 [debug] hosts container: added ip-host pair "ff02::1"-"ip6-allnodes"
2023/03/11 09:01:27.697942 9818#8 [debug] hosts container: added ip-host pair "ff02::2"-"ip6-allrouters"
2023/03/11 09:01:27.698233 9818#8 [debug] hosts container: no changes detected
2023/03/11 09:01:28.580549 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:28.584282 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 3.72389ms
2023/03/11 09:01:30.583918 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:30.588442 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 4.486484ms
2023/03/11 09:01:32.568697 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:32.572845 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 4.126191ms
2023/03/11 09:01:34.586654 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:34.590861 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 5.964438ms
2023/03/11 09:01:36.582612 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:36.587158 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 4.431902ms
2023/03/11 09:01:38.573204 9818#13 [debug] started GET 192.168.50.1:3000 /control/status
2023/03/11 09:01:38.577345 9818#13 [debug] finished GET 192.168.50.1:3000 /control/status in 4.081723ms
2023/03/11 09:01:40.088200 9818#24 [debug] initialized filtering engine
2023/03/11 09:01:40.088473 9818#24 [info] Starting the DNS proxy server
2023/03/11 09:01:40.088648 9818#24 [info] The server is configured to refuse ANY requests
2023/03/11 09:01:40.088844 9818#24 [info] dnsproxy: cache: enabled, size 4194304 b
2023/03/11 09:01:40.089053 9818#50 [debug] clients: removed 0 client aliases
2023/03/11 09:01:40.089079 9818#24 [info] MaxGoroutines is set to 300
2023/03/11 09:01:40.089348 9818#50 [debug] clients: added 192.168.50.32 -> "" [8]
2023/03/11 09:01:40.089351 9818#24 [info] Creating the UDP server socket
2023/03/11 09:01:40.089560 9818#50 [debug] clients: added 192.168.50.189 -> "" [9]
2023/03/11 09:01:40.089723 9818#50 [debug] clients: added 192.168.50.156 -> "" [10]
2023/03/11 09:01:40.089970 9818#24 [debug] stats: flushing unit with id 466257 and total of 0
2023/03/11 09:01:40.089976 9818#50 [debug] clients: added 192.168.50.164 -> "" [11]
2023/03/11 09:01:40.090337 9818#50 [debug] clients: added 192.168.50.52 -> "" [12]
2023/03/11 09:01:40.091105 9818#50 [debug] clients: added 192.168.50.167 -> "" [13]
2023/03/11 09:01:40.091351 9818#50 [debug] clients: added 192.168.50.208 -> "" [14]
2023/03/11 09:01:40.091546 9818#50 [debug] clients: added 192.168.50.121 -> "" [15]
2023/03/11 09:01:40.092089 9818#50 [debug] clients: added 192.168.50.13 -> "" [16]
2023/03/11 09:01:40.092251 9818#50 [debug] clients: added 9 client aliases from arp neighborhood
2023/03/11 09:01:40.169453 9818#24 [debug] stats: database closed
2023/03/11 09:01:40.169674 9818#24 [debug] querylog: there's nothing to write to a file
2023/03/11 09:01:40.169784 9818#24 [debug] all dns modules are closed
2023/03/11 09:01:40.169896 9818#24 [fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp 0.0.0.0:53: bind: address already in use

**Comment by monsm** [comment]
0.107.25 works fine,0.107.26 can't open web ui

**Comment by trngkn** [comment]
on my fresh new vps both of 0.107.25 and beta can't open web ui. It was not show any error on install process but cant open web ui to config

**Comment by ainar-g** [comment]
@monsm, thanks for the logs.  We have a theory that it may be connected to the `/etc/hosts` parser.  Could you see if setting `clients.runtime_sources.hosts` to `false` works around the issue?

**Comment by monsm** [comment]
@ainar-g after changing clients.runtime_sources.hosts to false, the web ui works fine, thanks. @trngkn you can do the same

**Comment by trngkn** [comment]
> @ainar-g after changing clients.runtime_sources.hosts to false, the web ui works fine, thanks. @trngkn you can do the same

Where i can edit this setting? I figured out that it not has .yaml in adguardhome folder

**Comment by monsm** [comment]
@trngkn Use search

**Comment by ainar-g** [comment]
@monsm, thank you for testing!  It is likely the same error as #5584.  We're working on fixing it.

**Comment by monsm** [comment]
@ainar-g Do I need to change clients.runtime_sources.hosts back to true when 0.107.27 is released?

**Comment by ainar-g** [comment]
You can if you want your `/etc/hosts` records to be taken into account by AdGuard Home.  This isn't strictly necessary.
