### ISSUE TITLE
Idea: consider adding ECS extension support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#558]
Here's the thread that gave me this idea:
https://github.com/AdguardTeam/dnsproxy/issues/7

If `/32` (IPv4) or `/128` (IPv6) address is specified in the [ECS](https://en.wikipedia.org/wiki/EDNS_Client_Subnet) extension, we might want to use it instead of client address in the query log and stats modules.

In this case, we will be able to chain DNS queries keeping information about the actual client. For instance, from a local AdGuard Home or `dnsproxy` to a remote AdGuard Home instance located on a VPS.

**Comment by szolin** [comment]
implemented? @ameshkov

**Comment by ameshkov** [comment]
@szolin not really. The point of this feature request is to use ECS to identify clients.

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdGuardHome/issues/1727
