### ISSUE TITLE
DHCP devices table unreadable on mobile

### ISSUE THREAD

**Issue by KaKi87** [AdguardTeam/AdGuardHome#5581]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

0.107.26

#### What did you do?

Opened DHCP settings on mobile

#### Expected result

Being able to read MAC addresses, hostnames, expiration dates

#### Actual result

Unable to read MAC addresses, hostnames, expiration dates

#### Screenshots (if applicable)

![Screenshot_20230310-120726_crDroid Home-01](https://user-images.githubusercontent.com/21284089/224301381-9f932e6b-a6ed-4465-bb50-20f932fbc542.jpeg)

#### Additional information

None

---

Thanks

**Comment by ainar-g** [comment]
Hello.  We've made some improvements in the recent Edge builds.  Could you please check if the table looks better for you now?

**Comment by KaKi87** [comment]
I don't feel like installing that kind of build while my home Internet access would depend on it, sorry 😅

**Comment by ainar-g** [comment]
I see.  We'll close the issue for now then, and if you have issues with the feature in the final release, feel free to reopen.

**Comment by KaKi87** [comment]
I'm afraid this isn't quite right yet : 

![Screenshot_20230406-033048_Trebuchet](https://user-images.githubusercontent.com/21284089/230250208-001a2537-9d3d-40db-8fb1-b1dc2d0f0f33.png)

If I'm reading correctly, you increased the size but kept it fixed.

Meanwhile, the proper way to fix this, I think, is to automatically increase it for the content to fit.

No need for limits, since there's a scrollbar.

Thanks
