### ISSUE TITLE
ADH frequently fails on Android

### ISSUE THREAD

**Issue by Gooman-rus** [AdguardTeam/AdGuardHome#5589]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.26

#### What did you do?
I use DoT address on my android phones. 
#### Expected result
Name resolution on android phones works fine without any errors.
#### Actual result
Almost every day I got a problem when my android phones stop to resolve domains. When I disable DoT in android connection settings everything starts to work fine.
Also this happens on **different** Wi-Fi points. But it never happens on mobile data.

#### Additional information
Android 8
Android 12

**Comment by ainar-g** [comment]
Hello.  Please enable [verbose logging][1] and see if there are any clues there.  You can also send them to devteam@adguard.com (please add the words “AdGuard Home Issue 5589” to the subject line).


[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by ainar-g** [comment]
Questions, and especially those that are not directly related to AdGuard Home, are better asked in the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions).
