### ISSUE TITLE
Add a RegEx example to the "Custom filtering rules" settings

### ISSUE THREAD

**Issue by liberodark** [AdguardTeam/AdGuardHome#559]
Hi,

Please add regex support for filter the web pages.

Cordialy

**Comment by ameshkov** [comment]
Regular expressions are supported, you can add something like this to the custom filtering rules to test it: `/example/`

**Comment by semaf** [comment]
What about regex to filter term in url string?

Let's say "porn" should not be able to search on google
https://www.google.com/search?q=porn

**Comment by ameshkov** [comment]
Unfortunately, that's not possible on the DNS-level.

**Comment by semaf** [comment]
> Unfortunately, that's not possible on the DNS-level.

Would be great as feature for family protection. Keeps popup with adult content or search of term away.
