### ISSUE TITLE
Ability to re configure network interface without reinstall 

### ISSUE THREAD

**Issue by talonric332** [AdguardTeam/AdGuardHome#5607]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I want the ability to re configure the network interface AGH uses, from the settings page instead of reinstalling it to do this
#### Proposed solution
Add an option in general settings to re configure the interface
#### Alternatives considered
None
#### Additional information
I want to have this option so that if I take the computer running AGH with me places, I don’t have to reinstall the software.

**Comment by fernvenue** [comment]
You can edit `AdGuardHome.yaml` manually to do that, read [docs](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) to get more information about it.

**Comment by ainar-g** [comment]
Also, the ability to set the web UI addresses should be coming in v0.108.0.
