### ISSUE TITLE
Google maps not working/slow on samsung Galaxy s8

### ISSUE THREAD

**Issue by KammAndRe** [AdguardTeam/AdGuardHome#561]
When adguard home is running. My wifes samsung will not display a trip in Google maps. When disconnected from wifi it's (maps) working again. 

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

**Comment by ameshkov** [comment]
I cannot reproduce it on my side. Could you please take a look at the Query Log of AG Home and try to figure blocking of which domain is causing it?

Also, what filters subscriptions do you have enabled?

**Comment by KammAndRe** [comment]
Hello Andrey,

I add a couple if screenshots.

The first one is of my wifes galaxy (in dutch). But whit an error it cannot reach maps. After de blocking a site. It works.
[Afbeelding]




If i unblock this site. It works. (even after putting the lock back it still works)

[Afbeelding]


[Afbeelding]



[Afbeelding]









André Kamman
(via mobiel)



Van: Andrey Meshkov
Verstuurd: maandag 28 januari 07:47
Onderwerp: Re: [AdguardTeam/AdGuardHome] Google maps not working/slow on samsung Galaxy s8 (#561)
Aan: AdguardTeam/AdGuardHome
Cc: André Kamman, Author


I cannot reproduce it on my side. Could you please take a look at the Query Log of AG Home and try to figure blocking of which domain is causing it?
Also, what filters subscriptions do you have enabled?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdguardTeam%2FAdGuardHome%2Fissues%2F561%23issuecomment-458015551&data=02%7C01%7C%7C5ea876ddb79e47d197d208d684ec6ba1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636842548296472413&sdata=RPoj2o3GM%2BrXw%2FB3xKEP%2BfVobKugKWCOlcbaFqQ1oWs%3D&reserved=0>, or mute the thread<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPRn51m5s6IfHY1ntjFEq5Crybc4pTOIks5vHpzmgaJpZM4aUWnR&data=02%7C01%7C%7C5ea876ddb79e47d197d208d684ec6ba1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636842548296482430&sdata=zQcEdFaGY6hAGHFuuV8dC76Ozghl21D3x0oz%2F48IxPw%3D&reserved=0>.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AdguardTeam/AdGuardHome","title":"AdguardTeam/AdGuardHome","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AdguardTeam/AdGuardHome"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ameshkov in #561: I cannot reproduce it on my side. Could you please take a look at the Query Log of AG Home and try to figure blocking of which domain is causing it?\r\n\r\nAlso, what filters subscriptions do you have enabled?"}],"action":{"name":"View Issue","url":"https://github.com/AdguardTeam/AdGuardHome/issues/561#issuecomment-458015551"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/AdguardTeam/AdGuardHome/issues/561#issuecomment-458015551", "url": "https://github.com/AdguardTeam/AdGuardHome/issues/561#issuecomment-458015551", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by ameshkov** [comment]
@KammAndRe screenshots weren't attached to the message, you need to upload them here on Github
