### ISSUE TITLE
(Feature request) full backup/restore via web interface

### ISSUE THREAD

**Issue by seebaer1976** [AdguardTeam/AdGuardHome#5610]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

could you add the function that you can create and download a complete backup (settings and data) via the web interface. and that you can simply upload it again later after a new installation or misconfiguration and the settings and data are restored.

**Comment by ainar-g** [comment]
Duplicate of #1147
