### ISSUE TITLE
ADH Not Using Local Time

### ISSUE THREAD

**Issue by SCPdesign** [AdguardTeam/AdGuardHome#5611]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.26

#### What did you do?
1. Checked to ensure that BIOS date and time were set to current/local time. <Good>
2. Checked to ensure that FIREWALL date and time were set to current/local time. <Good>
3. Checked to ensure that AdGuardHome YAML "log_localtime: false" set that to "log_localtime: true".  <Failed>  Ad Guard keeps resetting it back to "false".

#### Expected result
1  Both BIOS and FIREWALL dates are current and match local time. AdGuardHome should be using local server time and does not. 

#### Actual result
1.  AdGuard is using UTC and my server is Central. Seems to be related to DST recent changes. 

#### Additional information
I strongly feel this is a bug related to DST and in order to use 2FA for all clients, I have to disable AdGuard.

**Comment by ainar-g** [comment]
Hello.  There seems to be a few pieces of information missing:

 >  ADH Not Using Local Time (all 2FA logins fail because of this)

AdGuard Home doesn't have any kind of two-factor authentication, so I'm not exactly sure what you mean by this.

 >  Checked to ensure that AdGuardHome YAML "log_localtime: false" set that to "log_localtime: true". Ad Guard keeps resetting it back to "false".

Are you stopping the AdGuard Home process *before* editing the file, as written in the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?  Without it, the file can be overwritten by the running process.

 >  AdGuardHome should be using local server time and does not.

Please make sure that the environment provides a correct value for the `TZ` variable.  See #4207 and #3482 for some clues as well.

**Comment by SCPdesign** [comment]
Hi!

Yeah, sorry about 2FA. Not related to ADGH. However time is still an issue. I did halt ADGH to makes the changes in yaml. Ut;s now set to true ADGH still on UTC time.

zdump /etc/localtime == /etc/localtime  Mon Mar 20 17:00:09 2023 CDT (My system)

For privacy reasons I'm going to only show blocklist pull logs.

![03-20-2023-170138_ScreenShot-000014](https://user-images.githubusercontent.com/75589096/226475390-a6d86d03-0cc6-468f-9e10-071888f2785d.png)

**Comment by ainar-g** [comment]
`log_localtime` controls the textual system logs, not the query log.  All dates in the UI are shown in the browser's timezone.  See #3079 and the related issues.
