### ISSUE TITLE
Setup Guide issue

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardHome#5612]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.467+48431f8b (edge channel)

### Description

After setup of AGH on RaspberryPi there is an issue with the IP adress.

On "fe80" IPv6 adress it shows "%eth0" at the end.
example: fe80:: ....... :b426%eth0

Go to: Web interface -> Setup Guide

**Comment by ainar-g** [comment]
This is a [scoped IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses_(with_zone_index)).
