### ISSUE TITLE
Use AGH as a router

### ISSUE THREAD

**Issue by talonric332** [AdguardTeam/AdGuardHome#5617]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I want the ability to use adguard home as a router system/AP
#### Proposed solution
Add a section in settings to set up the router properties. This functionality would be useful for setting up the system as a portable or secondary router so devices that connect are automatically added to AGH
#### Alternatives considered
None
#### Additional information
Also allow the device to auto configure the listening interfaces based on if the device is connected to the internet vie ethernet or wifi

**Comment by cjom** [comment]
I don't think what you ask makes any sense... how can an app be a router?
AGH already can manage DHCP, but a router has to receive connections (wired or wifi), manage those connections, etc. Besides the hardware part, there is an entire operating system managing the hardware (also drivers), managing connections, routing, firewall, etc.

**Comment by talonric332** [comment]
Is there an OS that has the functionality that I need? Also has the ability to install Adguard home. Just so I can use it as my main AP and be able to use it when I travel?
