### ISSUE TITLE
websites not working with adguard

### ISSUE THREAD

**Issue by computernerd4** [AdguardTeam/AdGuardHome#5623]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

they lastest version on may 19th

### Description

speedtest.net wont work open up the app error could not do speedtest result i installed it on rasberry pi 400 it just websites. wont load i tried websites on iphone complete fail same with mac fail windows fail

**Comment by ainar-g** [comment]
Please fill the issue template.  In particular the version, since the 19th of May 2023 is in the future, and there have been a lot of releases of AdGuard Home since the 19th of May 2022.

**Comment by computernerd4** [comment]
i just had to update mine to arm v7
