### ISSUE TITLE
contents of filter list seems not  all used correctly

### ISSUE THREAD

**Issue by Phil353556** [AdguardTeam/AdGuardHome#5626]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.26

### Description
OS : Raspbian GNU/Linux 10 (buster)

#### What did you do?
try to verify ad guard runs has expected
test the list : https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
This one works as expected 
$ host 121-psychic-reading.co.uk
121-psychic-reading.co.uk has address 0.0.0.0
121-psychic-reading.co.uk has IPv6 address ::
Host 121-psychic-reading.co.uk not found: 3(NXDOMAIN)

this one not
host 112.213.84.94
94.84.213.112.in-addr.arpa domain name pointer mx8494.superdata.vn.

#### Expected result
address or domain blocked

#### Actual result
not blocked 

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/64729485/227291068-c688ac63-8b99-40f4-94a6-ae1c21f46948.png)
![image](https://user-images.githubusercontent.com/64729485/227295646-4e3d518f-06ca-4871-82f5-3504fbdf5bfa.png)

**Comment by fernvenue** [comment]
That's because this is an IP address, not a domain, so your device will not send any DNS request to AdGuardHome. If you wanna make it work on your device, add it to the hosts.

**Comment by Phil353556** [comment]
Ok.
Thank you
