### ISSUE TITLE
Incorrect count of the number of days when AGH was active

### ISSUE THREAD

**Issue by AuthFailed** [AdguardTeam/AdGuardHome#5630]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.475+bea39934

#### What did you do?
Watchtower automatically updated docker image today of AGH container and restarted it, then this error appears
#### Expected result
The number of days must be correct
#### Actual result
The number of days shows that AGH has been active for 77760000 days
#### Screenshots (if applicable)
![chrome_R9QCXtnoeU](https://user-images.githubusercontent.com/21986465/227498647-c5598797-5197-4000-9fd6-52f6e0241241.jpg)
#### Additional information
I did not find any errors in the terminal.

**Comment by ainar-g** [comment]
This should be fixed in the latest builds on the Edge channel.  Could you please check if the fixes work for you as well?

**Comment by AuthFailed** [comment]
Yes, problem solved. Thanks for the prompt solution to the problem and the great product!
