### ISSUE TITLE
"Invalid date" when hovering the mouse over charts

### ISSUE THREAD

**Issue by AuthFailed** [AdguardTeam/AdGuardHome#5633]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.485+fb7b8bba

#### What did you do?
Updated docker image to edge latest version
#### Expected result
The graphs must show the correct date in the selected language. If I have made it difficult to explain, the charts don't work in the installed English language either. 
#### Actual result
The graphs show "Invalid date", given that the AGH language is different from English
#### Screenshots (if applicable)
![chrome_9O1IRdWhw8](https://user-images.githubusercontent.com/21986465/227624674-59138cd2-21c5-4b0d-81e7-1e21d45b7929.jpg)
![chrome_Ja2whDpRrV](https://user-images.githubusercontent.com/21986465/227624702-65f08fd4-5511-4b1b-96fc-be4aa9c79965.jpg)

**Comment by ainar-g** [comment]
This issue should be fixed in the latest Edge release.  Could you please check?

**Comment by AuthFailed** [comment]
> This issue should be fixed in the latest Edge release.  Could you please check?

Yes, problem fixed
