### ISSUE TITLE
Error: control/tls/validate | port 443 is not available, cannot enable HTTPS on it | 400

### ISSUE THREAD

**Issue by araoof** [AdguardTeam/AdGuardHome#5636]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv5

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

Version:  v0.107.8

**Comment by ainar-g** [comment]
Please fill out the full issue template and make sure that port 443 is actually available on the machine.  Please note that v0.107.8 is a rather old version, and there have been a lot of updates since then.
