### ISSUE TITLE
Better management of blocked pages

### ISSUE THREAD

**Issue by TheCableGuy99** [AdguardTeam/AdGuardHome#5640]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
A nice web page saying the page has been blocked.

#### Proposed solution
Get a grip and really sort this out. The community is crying out for it!

#### Alternatives considered
Moving back to Pi.Hole, NextDNS or any other alternative... every other DNS provider seems to be able to offer a custom block page so why can't you?

#### Additional information
I don't see why practically every other DNS solution out there can offer a custom block page and redirect to a secure URL with a nice page but you can't? The best you seem to be able to offer if redirecting to an IP address which is why it's obviously going to give a shared SSL error. It's a blooming DNS server, you can redirect it to a different URL for blocked pages surely?

I just think it's silly, the amount of topics on people wanting this on the web is crazy and it's still not got anything viable.

**Comment by ppfeufer** [comment]
If I'm not mistaken, what you're asking for would result in some form of DNS hijacking, which is generally not a good thing to do.

**Comment by TheCableGuy99** [comment]
For pages we intend to block I don't see that as a bad thing. As said, all other services/providers are able to do it (and doing it).

**Comment by ainar-g** [comment]
[The current solution](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#customblock) is documented in the FAQ, along with the known limitations of DNS blocking.  I'm not sure what you mean by Pi-Hole providing a better variation of that feature, since this is pretty much the only way to do that on the DNS level, and in fact there seem to be a lot of people in the Pi-Hole forums for whom its solution also produces HTTPS errors.  Can you provide an example of a configuration that makes Pi-Hole's custom blocking page work with HTTPS while AdGuard Home's one doesn't?

**Comment by TheCableGuy99** [comment]
okay, firstly you have my apologies as it doesn't appear to be as easy with PiHole as I first thought. There are solutions but they struggle with https as well. I have managed to resolve it through by pointing it to an IP and that has a meta-refresh to redirect users to the secure blocked page.

Rather than that though would it be that difficult to give us the option to point users to a specific URL instead of an IP for custom blocklists? It's already doing that for your family and safety filters.

**Comment by ainar-g** [comment]
URLs exist on the level of HTTP, and you can't “point” clients to an HTTP URL on the DNS level.  This is currently something that only content-filtering proxies can do.  

And I'm not quite sure what you mean by “already doing that for your family and safety filters”, because those filters use exactly the same algorithm: they reply with the IP addresses of the block pages (which you can change, as described in the FAQ entry).  And they produce exactly the same TLS validation issues, especially if you use something like Firefox's HTTPS-only mode.

**Comment by TheCableGuy99** [comment]
What I meant was in the AdGuardHome.yaml file you specify the following which point to URLs not IPs:
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com

So if it's possible to redirect based on those filters to URLs and not IPs I don't understand why you can't let us specify an URL other than IP in the control panel for blocklist based blocking.

Regardless I have now managed to resolve it by doing the following:
I have a webserver hosted locally with a spare public IP so I created a sub domain "blocked.mydomain.com" and assigned the subdomain to the IP as a dedicated IP.
I turned off auto-redirect to https so http pages could be served without an ssl error.
In the index page I added a meta-refresh with instant redirect to https://blocked.mydomain.com/blocked.html

So when someone gets redirected to http://xxx.xxx.xxx.xxx (my websites dedicated IP) it loads the index page which redirects it to the https version of my blocked page.

I also added restrictions in the .htaccess so spiders can't read it and locked it down to my subnets and public IP.

If I can setup that up I'm pretty sure you could come up with something within the system to make it a little easier for people.

If not I hope this helps someone else but you can close this now as it's working well for me.

**Comment by TheCableGuy99** [comment]
What I meant was in the AdGuardHome.yaml file you specify the following which point to URLs not IPs:
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com

So if it's possible to redirect based on those filters to URLs and not IPs I don't understand why you can't let us specify an URL other than IP in the control panel for blocklist based blocking.

Regardless I have now managed to resolve it by doing the following:
I have a webserver hosted locally with a spare public IP so I created a sub domain "blocked.mydomain.com" and assigned the subdomain to the IP as a dedicated IP.
I turned off auto-redirect to http so https so the index page could load without an error and could then redirecting the user to the final https blocked page.
In the index page I added a meta-refresh with instant redirect to https://blocked.mydomain.com/blocked.html

So when someone gets redirected to http://xxx.xxx.xxx.xxx (my websites dedicated IP) it loads the index page which redirects them to the https version of my blocked page.

I also added restrictions in the .htaccess so spiders can't read it and locked it down to my subnets and public IP.

If I can setup that up I'm pretty sure you could come up with something within the system to make it a little easier for people.

If not I hope this helps someone else but you can close this now as it's working well for me.

**Comment by iptvcld** [comment]
> What I meant was in the AdGuardHome.yaml file you specify the following which point to URLs not IPs: parental_block_host: family-block.dns.adguard.com safebrowsing_block_host: standard-block.dns.adguard.com
> 
> So if it's possible to redirect based on those filters to URLs and not IPs I don't understand why you can't let us specify an URL other than IP in the control panel for blocklist based blocking.
> 
> Regardless I have now managed to resolve it by doing the following: I have a webserver hosted locally with a spare public IP so I created a sub domain "blocked.mydomain.com" and assigned the subdomain to the IP as a dedicated IP. I turned off auto-redirect to http so https so the index page could load without an error and could then redirecting the user to the final https blocked page. In the index page I added a meta-refresh with instant redirect to https://blocked.mydomain.com/blocked.html
> 
> So when someone gets redirected to http://xxx.xxx.xxx.xxx (my websites dedicated IP) it loads the index page which redirects them to the https version of my blocked page.
> 
> I also added restrictions in the .htaccess so spiders can't read it and locked it down to my subnets and public IP.
> 
> If I can setup that up I'm pretty sure you could come up with something within the system to make it a little easier for people.
> 
> If not I hope this helps someone else but you can close this now as it's working well for me.

@TheCableGuy99 I was wondering if I may disturb you and ask how exactly you got this going? I have been at this for a week now that I also feel should be build it!
