### ISSUE TITLE
Docker healthcheck fails with HTTPS on Edge

### ISSUE THREAD

**Issue by ralfi** [AdguardTeam/AdGuardHome#5642]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

edge

#### What did you do?
using docker edge image at home server and renew with persistent volumes since many month

#### Expected result
starting docker with edge agh container

#### Actual result
container starts with unhealthy state, this error appears

481B3F835C7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: ssl_client: SSL_connect wget: error getting response: Connection reset by peer

#### Additional information
using a bash script since many month but today the error message above appears. Are there changes inside the container? I am using letsencryt certonly certs

**Comment by ainar-g** [comment]
Thanks for reporting!  We're looking into it.

**Comment by ralfi** [comment]
Thank YOU, and if course a new edge image was pushed 13 hours ago...

**Comment by EugeneOne1** [comment]
@ralfi, hello again.  We've pushed the new edge build that should avoid the SSL validation.  Could you please check if it now weoks properly?

**Comment by ralfi** [comment]
Yeah, fix it. Thanks!
