### ISSUE TITLE
Error: control/install/configure | dnsforward.NewServer: initializing system resolvers: systemResolvers: can't get addresses: looking up cmd path: exec: "nslookup.exe": cannot run executable found relative to current directory | 500

### ISSUE THREAD

**Issue by mega-optimus** [AdguardTeam/AdGuardHome#5644]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.26

#### What did you do?
My OS is Win7.

I was running v0.107.23, and mistakenly clicked the "update now" button at the top of the administration page (127.0.0.1). Then the upgrade never completed successfully. 

As a second try, I downloaded the binary, manually removed the old yaml config file, deleted the windows service, and execute the cmd "AdGuardHome -s install", which turn out to be success at first.

When I logged in to the administration web page (127.0.0.1), followed the setup guide, and finally arrived at the error message stated. 

#### Expected result
No error.

#### Actual result
"Error: control/install/configure | dnsforward.NewServer: initializing system resolvers: systemResolvers: can't get addresses: looking up cmd path: exec: "nslookup.exe": cannot run executable found relative to current directory | 500"

#### Additional information
Running AdGuardHome in console instead of service seems to be fine.
My AdGuardHome.exe is in E:\software\AdGuardHome, does that matter?

**Comment by mega-optimus** [comment]
My AdGuardHome.exe is in E:\software\AdGuardHome\, does that matter?

**Comment by ainar-g** [comment]
Hello.  It seems like your `PATH` may contain relative paths, which is [considered a security issue in Go 1.19](https://go.dev/doc/go1.19#os-exec-path).  You can inspect your value of `PATH` by using this command in PowerShell:

```ps1
$env:PATH -split ';'
```

**Comment by mega-optimus** [comment]
> Hello. It seems like your `PATH` may contain relative paths, which is [considered a security issue in Go 1.19](https://go.dev/doc/go1.19#os-exec-path). You can inspect your value of `PATH` by using this command in PowerShell:
> 
> ```powershell
> $env:PATH -split ';'
> ```

Hi, thanks for this hint!
I did find some anomaly in the PATH variable, which is a leading `;` at the beginning.
After removing it, I still encounter the same error, though.
See below.

![image](https://user-images.githubusercontent.com/69918075/228219199-391ea60d-309a-414e-9a17-735fa13849f1.png)

**Comment by ainar-g** [comment]
You need to persist that change to the `PATH` and reboot the machine for AdGuard Home to see the change, if I recall correctly.

**Comment by mega-optimus** [comment]
Why does it insist on a `static IP address`? 
I'm installing on my laptop and it is used by my laptop only.
I looked up the v0.107.23 yaml file, which does not mention this.

**Comment by mega-optimus** [comment]
> You need to persist that change to the `PATH` and reboot the machine for AdGuard Home to see the change, if I recall correctly.

echo %PATH% already show the latest changes.

**Comment by mega-optimus** [comment]
After rebooting, it works smoothly, thank you!
