### ISSUE TITLE
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.

### ISSUE THREAD

**Issue by ahmedRSA** [AdguardTeam/AdGuardHome#5658]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

Latest

### Description

running this command giving this error

```bash
sudo docker run --name adguardhome\
    --restart unless-stopped\
    -v /my/own/workdir:/opt/adguardhome/work\
    -v /my/own/confdir:/opt/adguardhome/conf\
    -p 53:53/tcp -p 53:53/udp\
    -p 67:67/udp -p 68:68/udp\
    -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 1337:1337/tcp\
    -p 853:853/tcp\
    -p 784:784/udp -p 853:853/udp -p 8853:8853/udp\
    -p 5443:5443/tcp -p 5443:5443/udp\
    -d adguard/adguardhome
```

### error
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint adguardhome (78d64ae66417bc96176c11ca4d6d3529682b0086ffaa26c8c75b024488817389): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.
```
### sudo lsof -nP | grep LISTEN
![image](https://user-images.githubusercontent.com/77731877/228516150-e100c25c-1972-493e-a9a4-7f7c6a2566e9.png)

### nginx config [dns.DOMAIN.in.conf]
```js
server { listen 80; server_name dns.DOMAIN.in;

location / { 
    proxy_pass http://localhost:1337; 
}}
```

**Comment by ainar-g** [comment]
If you already have something, Nginx in this case, running on port 80, you can't use the same port for AdGuard Home.  AdGuard Home uses whatever port you tell it during the initial configuration (on port 3000, which should also be free or reconfigured with `--port`).  You should also remove `-p 80:80/tcp` from your Docker call.
