### ISSUE TITLE
DNS upstream for specific domains stucks

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#5662]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.26

#### What did you do?
i try to specify upstreams that will be used for specific domains 
#### Expected result
these domains resolved by opendns (or any other)
[/bing.com/bingapis.com/windowsupdate.com/update.microsoft.com/prod.do.dsp.mp.microsoft.com/emdl.ws.microsoft.com/delivery.mp.microsoft.com/adl.windows.com/tsfe.trafficshaping.dsp.mp.microsoft.com/www.msftconnecttest.com/v10.events.data.microsoft.com/self.events.data.microsoft.com/client.wns.windows.com/dmd.metaservices.microsoft.com/tmdb.org/themoviedb.org/spotify.com/whoer.net/play.google.com/openai.com/img-prod-cms-rt-microsoft-com.akamaized.net/livetileedge.dsx.mp.microsoft.com/wns.windows.com/storecatalogrevocation.storequality.microsoft.com/manage.devcenter.microsoft.com/displaycatalog.mp.microsoft.com/pti.store.microsoft.com/share.microsoft.com/storeedgefd.dsx.mp.microsoft.com/go.microsoft.com/bard.google.com/]https://dns.opendns.com/dns-query
#### Actual result
dns requests for specific domains get stuck periodically. these domains that do not open periodically, while others respond normally. if you set this DOH in the windows settings, then everything works fine.

**Comment by fernvenue** [comment]
Maybe you can try this feature: [upstreams from file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file).

**Comment by YBS-PC** [comment]
I have glinet with agh.  and it seems to remove everything superfluous on every reboot.  if you place this file in a folder with agh, then you need to specify just the file name in the configuration file?  and if in a folder inside a folder with agh , then specify the name of the folder and file, or the full path from etc?
I disabled dnssec .  I thought that it interferes, especially since the ControlD documentation says that it is useless when using doh or doq.  did not help …

**Comment by YBS-PC** [comment]
> Maybe you can try this feature: [upstreams from file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-from-file).

it doesn't help

when the smart dns from controld is used, it returns its own ip`s for the redirected domains.  For example, if you configure controld to redirect openai.com and bing.com , and bypass youtube.com in the logs you can see the ip addresses belonging to controld for openai and bing, but for youtube you will see youtube ip. And it is precisely such domains that stop opening over time. But if you specify the same DNS in the windows network settings, then everything works fine.

**Comment by BigBobDalton** [comment]
I am having a similar issue and am forced to do a DNS flush in order to get many pages to open,  I have tested by bypassing AGH and using only my routers IP as a DNS server and can reach every web page, of course with ads.  This is a REAL problem
