### ISSUE TITLE
Can we introduce the "Equivalent DNS" feature in the Upstream DNS servers?

### ISSUE THREAD

**Issue by xiaoyaoyaowww** [AdguardTeam/AdGuardHome#5667]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to request a feature or enhancement and not ask a question

### Description

"Equivalent DNS" refers to DNS servers operated by the same service provider. As they return the same results, it is only necessary for one of them to be able to return the correct DNS resolution result.

In "Fastest IP address", if one of the DNS servers in the "equivalent DNS" fails, the overall DNS resolution speed will drop sharply. Therefore, it would be sufficient to only use the fastest DNS server in the "equivalent DNS" group to participate in the IP address speed test and ignore the others.

Can we do this?

**Comment by fernvenue** [comment]
I don't know how the dev team thinks about this, but I think we don't really need AdGuardHome to do this by itself, because we can just set a load balancer for them by another application, that's quite simple.

**Comment by ainar-g** [comment]
A related feature: #724.
