### ISSUE TITLE
Customized Landing Pages for Blocked domains 

### ISSUE THREAD

**Issue by shayp2007** [AdguardTeam/AdGuardHome#5669]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

Hi there, 
would it be possible to create a customized landing pages for blocked domains, I think this would a very valuable and sought-after feature.
Thanks.

**Comment by fernvenue** [comment]
It's not possible, because most of the sites using HTTPS now, you can't set customized pages for them just use a DNS server, you can only set customized pages for HTTP sites, but I still don't think AdGuardHome should do that by itself. For HTTP sites, You can resolve them to your web server and host your customized pages on it, you can use [NGINX](https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/), [Traefik](https://doc.traefik.io/traefik/routing/overview/#example-with-a-file-provider), [Caddy](https://caddyserver.com/docs/quick-starts/static-files) or any other web server applications you prefer.

**Comment by shayp2007** [comment]
> It's not possible, because most of the sites using HTTPS now, you can't set customized pages for them just use a DNS server, you can only set customized pages for HTTP sites, but I still don't think AdGuardHome should do that by itself. For HTTP sites, You can resolve them to your web server and host your customized pages on it, you can use [NGINX](https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/), [Traefik](https://doc.traefik.io/traefik/routing/overview/#example-with-a-file-provider), [Caddy](https://caddyserver.com/docs/quick-starts/static-files) or any other web server applications you prefer.



I disagree with you. It is definitely possible and a number of other solutions do this already (https://help.dnsfilter.com/hc/en-us/articles/1500008111221-Block-Pages)
Using a custom redirect function, which is hosted on the server. HTTPS does not stop the domain address being read.

**Comment by fernvenue** [comment]
I think you should read this first: [Installing SSL Certificates](https://help.dnsfilter.com/hc/en-us/articles/1500008110241-Installing-SSL-Certificates)

> It is utilized to display block page messages when users attempt to visit https:// websites that are blocked in your Policy. Without certificate installation, the user will receive an error in their browser when attempting to visit blocked sites. (This is because of how HTTPS operates, and is why SSL certificates are a technical requirement for any filtering provider)

As they said in their documentaion, they also **CAN NOT** handle HTTPS connection with just a DNS server, they need to do more on all the client devices.

**Comment by ainar-g** [comment]
We have an [FAQ entry](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#customblock) about how you can do this.  As fernvenue has mentioned, the clients will most likely experience certificate issues with HTTPS pages, and there isn't really a way to prevent that.  You can also look at the recent discussion in #5640.
