### ISSUE TITLE
DHCP - IP Address bug

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#567]
When using DHCP, connecting new devices to the network causes the DHCP list to show really odd randomised IP Addresses, not the actual LAN IPs.

![dhcp](https://user-images.githubusercontent.com/46271764/52011623-9b8cde80-252c-11e9-9a1f-ac0ba8fb2ec2.jpg)

![dhcp2](https://user-images.githubusercontent.com/46271764/52011720-e4dd2e00-252c-11e9-88ae-19fe96cc7af6.jpg)

**Comment by hmage** [comment]
thanks! Will investigate.

What hardware and OS is that?

**Comment by planet0** [comment]
Raspberry PI 3 B+
Raspbian GNU/Linux 9 (stretch)

![dhcp3](https://user-images.githubusercontent.com/46271764/52015465-27efcf00-2536-11e9-8c2d-7c876aa2a66e.jpg)

**Comment by hmage** [comment]
Thank you. Is there anything common for those clients that have wonky IP's? Hardware? OS? Wifi? Ethernet?

**Comment by planet0** [comment]
Unfortunately not, the devices change as well. I think this is a UI bug as the addresses given do stay as 192.168.0.x addresses.

(1) Is an iPhone via Wi-Fi
(2) Is a Desktop PC via Ethernet
(3) Is a Roku Streaming device via Ethernet

![dhcp4](https://user-images.githubusercontent.com/46271764/52015842-0a6f3500-2537-11e9-978c-50280f964ac7.jpg)

**Comment by Threefish1024** [comment]
Do you have news about this problem?
Because sometimes the ip assigned as well as being wrong on the web side, but correct on the machine side, is not assigned and ambiguity happens at the DHCP level

**Comment by ameshkov** [comment]
@Threefish1024 not yet, debugging DHCP is painful:( We'll try to solve it quickly, v0.94 release won't take as much time as v0.93.

What you describe is most likely due to this bug: #584

**Comment by Threefish1024** [comment]
> @Threefish1024 not yet, debugging DHCP is painful:( We'll try to solve it quickly, v0.94 release won't take as much time as v0.93.
> 
> What you describe is most likely due to this bug: #584

Thanks!

**Comment by szolin** [comment]
@planet0 
Can you enable verbose logging so we can see what's going on with the lease table?
In your `AdGuardHome.yaml` set `verbose true`.

And then the log will contain info about the current state of leases table, e.g.:
```
github.com/AdguardTeam/AdGuardHome/dhcpd.(*Server).ServeDHCP(): Leases:
github.com/AdguardTeam/AdGuardHome/dhcpd.(*Server).ServeDHCP(): Lease #0: hwaddr 08:00:27:56:2c:6c, ip 192.169.56.2, expiry 0001-01-01 00:00:00 +0000 UTC
```

Let's see whether it prints correct IP addresses.
