### ISSUE TITLE
certificate for unfiltered.adguard-dns.com does not include ipv6 addresses, fails

### ISSUE THREAD

**Issue by gtxaspec** [AdguardTeam/AdGuardHome#5670]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

edge

### Description

via adguard home, was getting errors when using `quic://2a10:50c0::2:ff`  or `tls://2a10:50c0::2:ff` upstream servers.

so I tested via dnslookup, error that stands out is:

```
2023/04/01 00:02:21 [fatal] Cannot make the DNS request: opening quic connection to quic://[2a10:50c0::1:ff]:853: CRYPTO_ERROR (0x12a): x509: certificate is valid for 94.140.14.14, 94.140.14.140, 94.140.14.141, 94.140.14.15, 94.140.15.15, 94.140.15.16, not 2a10:50c0::1:ff
```

Looks like they are failing because the certificate does not include the ipv6 addresses.  This is working with other providers, tested cloudflare, quad9, google. 

full log:

```
root@test:~$ host unfiltered.adguard-dns.com
unfiltered.adguard-dns.com has address 94.140.14.141
unfiltered.adguard-dns.com has address 94.140.14.140
unfiltered.adguard-dns.com has IPv6 address 2a10:50c0::2:ff
unfiltered.adguard-dns.com has IPv6 address 2a10:50c0::1:ff
root@test:~$ dnslookup 'example.com' 'quic://[2a10:50c0::2:ff]'
dnslookup v. 1.8.1-8619
2023/04/01 00:01:48 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/04/01 00:01:48 [fatal] Cannot make the DNS request: opening quic connection to quic://[2a10:50c0::2:ff]:853: CRYPTO_ERROR (0x12a): x509: certificate is valid for 94.140.14.14, 94.140.14.140, 94.140.14.141, 94.140.14.15, 94.140.15.15, 94.140.15.16, not 2a10:50c0::2:ff
root@test:~$ dnslookup 'example.com' 'quic://[2a10:50c0::1:ff]'
dnslookup v. 1.8.1-8619
2023/04/01 00:02:21 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/04/01 00:02:21 [fatal] Cannot make the DNS request: opening quic connection to quic://[2a10:50c0::1:ff]:853: CRYPTO_ERROR (0x12a): x509: certificate is valid for 94.140.14.14, 94.140.14.140, 94.140.14.141, 94.140.14.15, 94.140.15.15, 94.140.15.16, not 2a10:50c0::1:ff
root@test:~$ dnslookup 'example.com' 'tls://[2a10:50c0::1:ff]'
dnslookup v. 1.8.1-8619
2023/04/01 00:19:21 [fatal] Cannot make the DNS request: getting conn to tls://[2a10:50c0::1:ff]:853: connecting to 2a10:50c0::1:ff: x509: certificate is valid for 94.140.14.14, 94.140.14.140, 94.140.14.141, 94.140.14.15, 94.140.15.15, 94.140.15.16, not 2a10:50c0::1:ff

```

**Comment by ainar-g** [comment]
Regarding the IPv6 addresses of AdGuard DNS, it's probably better to propose adding them to the certs in the [AdguardTeam/AdGuardDNS repo](https://github.com/AdguardTeam/AdGuardDNS).

If you're using an IPv6 address instead of the hostname because the currently-preferred IPv4 address is blocked then that problem should be resolved once we fix #4262.  You could also ask @ameshkov to add IP protocol preference to `dnslookup` as well.
