### ISSUE TITLE
Safe search not working despite being enabled

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#5685]
1. I use Docker to run the edge branch, the version is v0.108.0-a.496+3575aa05. (`docker run --name adguardhome -p 53:53/udp -p 3000:3000 -d adguard/adguardhome:edge`)
2. Then I turned on the safe search option and enabled all services.
3. Finally I use `kdig` to send a query to AdGuard Home.

As you can see, `www.youtube.com` does not return SafeSearch results, nor does SafeSearch appear in the query log.

![image](https://user-images.githubusercontent.com/25147395/229512587-1222ed80-42da-4dcb-a3a9-3b5446f874aa.png)

_Originally posted by @Hill-98 in https://github.com/AdguardTeam/AdGuardHome/issues/5416#issuecomment-1494257041_

**Comment by ainar-g** [comment]
@Hill-98, could you please enable [verbose logs], make a few queries for `www.youtube.com` and `www.google.com`, and send the resulting logs to us at devteam@adguard.com, with the subject line “AdGuard Home issue 5685”?  That would help us diagnose the issue.

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Hill-98** [comment]
Ok, I'll run the test again later with verbose logs and send the logs to you guys.

**Comment by Hill-98** [comment]
I sent logs and configuration files, the test version is `v0.108.0-b.31`, because I don't know why the latest Docker's edge branch version is `v0.108.0-a.24+e9c59b09`?

**Comment by ainar-g** [comment]
Thanks for the info!  There might be something wrong with the safesearch cache.  We'll look into it.

**Comment by ainar-g** [comment]
@Hill-98, could you please check the latest Edge version, `v0.108.0-a.504+f553eee8`, or later?  We have found a few issues in the Safe Search feature and fixed them there.

**Comment by Hill-98** [comment]
No problem anymore, working great!

**Comment by ainar-g** [comment]
Thanks for testing!

**Comment by WildByDesign** [comment]
@ainar-g  Did (https://github.com/AdguardTeam/AdGuardHome/commit/61b4043775ecc3e06aebcdabc070b732c6dd0ff0) ever make it into Stable branch builds?

The reason why I ask is because I just noticed that Safe Search is not working here on stable **v0.107.40**. I don't know how long it's not been working for, unfortunately.

I searched all Stable release builds notes and have not found any details for (https://github.com/AdguardTeam/AdGuardHome/commit/61b4043775ecc3e06aebcdabc070b732c6dd0ff0) being included. I see it being included in **v0.108.0-b.33** but not stable. 

Can you please confirm if this made it into stable?

**Comment by ainar-g** [comment]
@WildByDesign, it's better to not add new comments to old closed issues.  The commit in question has been released, and the safe search is working for me.  If it isn't for you, please file a new issue with the details, including the precise DNS query you're making.

**Comment by WildByDesign** [comment]
@ainar-g  Sorry about that.

I have put several hours now into testing and running troubleshooting steps to collect as much info and understanding of the problem as possible.

Here is the new bug report: https://github.com/AdguardTeam/AdGuardHome/issues/6352

Thank you for your time and patience.
