### ISSUE TITLE
Disabling encryption disables protection

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#5689]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.501+10bffd89

#### What did you do?

Disabled encryption.

#### Expected result

Encryption is disabled, protection stays enabled.

#### Actual result

Both protection and encryption are disabled.

**Comment by EugeneOne1** [comment]
It seems, the bug is actually on the frontend.
