### ISSUE TITLE
Cannot bind host 0.0.0.0 in IPv4 - Raspberry PI 4

### ISSUE THREAD

**Issue by aaleeexx** [AdguardTeam/AdGuardHome#5693]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.27

#### What did you do?
I installed AGH on my Raspberry, then followed this [FAQ](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse) to free the port 53 since systemd-resolved was using it. Then I modified the `dns_bind_hosts` in the .yaml file and set `0.0.0.0` as host but after I reloaded AGH, I lost access to the web interface and can't surf the web. I tried to add multiple hosts such as `::1` and `0.0.0.0` together, but the issue it's still there.
If I do set `127.0.0.1` I gain access to the web interface, but can't resolve nameservers and access the Internet.
#### Expected result
When binding the host `0.0.0.0` in the .yaml file, saving, reloading AGH and running the command `sudo lsof -i :53` it should return the output of AGH using the port 53 in IPv4 and IPv6, not only IPv6 (am I right?)
#### Actual result
See screenshot.
#### Screenshots (if applicable)
![image_2023-04-05_19-12-38](https://user-images.githubusercontent.com/32374191/230217697-b49a308d-e1c8-490b-b6f8-d281c9ae003c.png)

#### Additional information
Might having a VPN (OpenVPN configured with PiVPN) interfere with this issue ? (I personally do not think so...)

**Comment by ainar-g** [comment]
Hello.

 >  When binding the host `0.0.0.0` in the .yaml file, saving, reloading AGH and running the command `sudo lsof -i :53` it should return the output of AGH using the port 53 in IPv4 and IPv6, not only IPv6 (am I right?)

Not necessarily.  `0.0.0.0` is interpreted as “all interfaces and all protocols”, and on Linux Go accomplishes this by using the (rather poorly named) `IPV6_V6_ONLY` socket option, which makes a socket accept both IPv4 and IPv6 connections.  I have the same `lsof` output, but both IPv4 and IPv6 queries are processed, so in most cases this doesn't make a difference.

See `man 7 ipv6`.
