### ISSUE TITLE
Smartphone compatible design on malware page alerts

### ISSUE THREAD

**Issue by portalvasco** [AdguardTeam/AdGuardHome#57]
Malware page alert actual design is not compatible with smartphones, letters show very small.

I think its better a smartphone compatible or responsive design.

**Comment by ameshkov** [comment]
Agreed, we'll change it

**Comment by portalvasco** [comment]
Thanks.

**Comment by ArchiveBase** [comment]
Possible consider same time smartphones related things https://github.com/AdguardTeam/AdGuardHome/issues/978 ;)

**Comment by KizunaH** [comment]
Very old issue (maybe outdated) - https://github.com/AdguardTeam/AdGuardHome/issues/2075
