### ISSUE TITLE
Can Adguardhome support riscv64 architecture ？

### ISSUE THREAD

**Issue by cyqtmxk** [AdguardTeam/AdGuardHome#5704]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
When I compile the Adguardhome 0.107.21 for riscv64 using openwrt master source code, it shows the error:
![image](https://user-images.githubusercontent.com/10682818/231233740-5148bf15-a70e-4982-b3bb-c63833b2c0c5.png)
I dont know how to resolve the issue and I wonder if adguardhome support riscv？
Can anyone help me ？🙏🙏🙏  Thanks!

**Comment by ainar-g** [comment]
Commit b23ea0a has resolved this particular issue.  AdGuard Home does not currently support RISC-V CPUs, see the [current list of supported platforms](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms).  We'll see how many :+1: this issue will collect, although I'm not sure if there is even enough real hardware in the world.

**Comment by cyqtmxk** [comment]
> Commit [b23ea0a](https://github.com/AdguardTeam/AdGuardHome/commit/b23ea0a690e8f5b892e34ac38111efae732e77d3) has resolved this particular issue. AdGuard Home does not currently support RISC-V CPUs, see the [current list of supported platforms](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms). We'll see how many 👍 this issue will collect, although I'm not sure if there is even enough real hardware in the world.

Thanks! I have built adguardhome v0.107.28 on riscv SBC successfully! 
![image](https://user-images.githubusercontent.com/10682818/232037490-5e6be4ea-2b57-4a96-a081-7d81c2d287de.png)
and I have purchased an AdGuard Ad Blocker license as a reward for your teams help！
![image](https://user-images.githubusercontent.com/10682818/232040239-b2996bef-3264-4370-82c3-f6f2733597e2.png)

**Comment by liberodark** [comment]
I hope you add officially `riscv64` support same as Debian.

**Comment by liberodark** [comment]
For me compilation fail : 

```
#!/bin/bash

apt install -y golang-go rsync gpg git nodejs npm
git clone https://github.com/AdguardTeam/AdGuardHome
cd AdGuardHome
make init
make
```

**Comment by ainar-g** [comment]
@liberodark, that looks like a front-end error not directly related to AdGuard Home.  If you'd like to get help with that one, please use Discussions and try to keep the comments in the issue related to RISC-V builds of AGH.

**Comment by schzhn** [comment]
@liberodark, https://github.com/AdguardTeam/AdGuardHome/issues/6585

**Comment by liberodark** [comment]
Thank @schzhn for the issue
Also @ainar-g yes i know that have build gitea without frontend.

**Comment by liberodark** [comment]
Hi,

Any news about this issue ?
I hope you can add support to riscv64 for improve your compatibility.

Best Regards

**Comment by ainar-g** [comment]
@liberodark, can you please elaborate?  As far as I see, AdGuard Home can currently be built with `GOOS=riscv64`.  And if you mean providing official builds, not that much has changed since https://github.com/AdguardTeam/AdGuardHome/issues/5704#issuecomment-1503792836.

**Comment by liberodark** [comment]
Hi, 

@ainar-g Indeed I was talking about being able to have official support rather than having to compile each update.

Best Regards

**Comment by ainar-g** [comment]
As mentioned before, we're not sure if there is enough hardware for this to make sense.

@ameshkov, what do you think?

**Comment by ameshkov** [comment]
If it's an easy task then why not.

**Comment by liberodark** [comment]
Thank you, it will be much easier for us users.

**Comment by Mizzick** [comment]
Please have a look, we have implemented the requested changes.
The new build version `v0.108.0-a.950+cdf970fc` has been just published to the edge channel.
