### ISSUE TITLE
False Positive: Adguard DNS Family blocks Etsy.

### ISSUE THREAD

**Issue by lewisje** [AdguardTeam/AdGuardHome#5707]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

Other (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

just the public family-filtering DNS

#### What did you do?
navigated to etsy.com

#### Expected result
redirection to https://www.etsy.com/ followed by a page-load

#### Actual result
a privacy error because the blocked-site page doesn't have an HTTPS certificate for https://www.etsy.com/ and I can't even navigate past the TLS-error page, because Etsy uses HSTS and it's a built-in configuration in Chrome so I can't even disable *that*

#### Screenshots (if applicable)
(none)

#### Additional information
I ended up searching what the IP address that ping returned went to, and indeed 94.140.14.35 is the blocked-site page; using nslookup with the regular DNS servers and some notable third-party servers returned accurate IP addresses; I fail to see how Etsy qualifies as "adult content" worthy of blocking via the family filter, but at this point I have no choice but to switch DNS servers.

**Comment by ainar-g** [comment]
Hello.  This is the repository of AdGuard Home, not AdGuard DNS.  As the issue form suggested, issues regarding filters should be reported using the [AdGuard feedback form](https://reports.adguard.app/en/new_issue.html?utm_campaign=report&utm_medium=github&utm_source=home).

**Comment by lewisje** [comment]
I guess the team at [the correct repository](https://github.com/AdguardTeam/AdguardFilters/issues/148111) would rather not hear about an issue that could be described with a couple of `nslookup` outputs and instead I had to take a couple of screenshots; oh, and they also don't seem to like to make it obvious that this is not only where to complain about the apps and browser extension but also about the DNS service, instead feeding complaints through a multi-page form.

I guess idiots are just so common in GitHub Issues that I had to be treated like one too.
