### ISSUE TITLE
AGH docker container after month not longer working on RPi

### ISSUE THREAD

**Issue by Homer-Sim** [AdguardTeam/AdGuardHome#5708]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

1.17.27

#### What did you do?

I am running AGH for month on my RPi 3b+ (Raspbian GNU/Linux 10 (buster)) as a second AGH device in my homenet. Router is haveing both IP addresses as DNS Server)
Since some days the RPi AGH is not longer working. All other services are running fine. SD-Card test was ok.

Web UI is accessible, I can change settings but no protocol entries nor stats are shown. If I am switching off the main AGH (on a different physical server) I have no access to internet anymore. It was working before.

Both instances of AGH are running with the same docker command (on different IPs)

docker run --name adguardhome\
    --restart unless-stopped\
    -v ~/docker/adguardhome/daten:/opt/adguardhome/work\
    -v ~/docker/adguardhome/config:/opt/adguardhome/conf\
    -p 53:53/tcp -p 53:53/udp\
    -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 3000:3000/tcp\
    -p 853:853/tcp\
    -p 784:784/udp\
    -p 5443:5443/tcp -p 5443:5443/udp\
    -d adguard/adguardhome:v0.107.27

docker version: 23.0.3

#### Expected result
working as second DNS and failover AGH
#### Actual result
not working
#### Additional information
Please help me with this issue.

**Comment by Homer-Sim** [comment]
Maybe this will help finding a solution; this is the starting log of my container.

`2023/04/13 08:03:22.816332 [info] AdGuard Home, version v0.107.27
2023/04/13 08:03:22.816576 [info] AdGuard Home updates are disabled
2023/04/13 08:03:22.832588 [info] tls: using default ciphers
2023/04/13 08:03:22.866445 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2023/04/13 08:03:22.866850 [info] auth: initialized.  users:1  sessions:7
2023/04/13 08:03:22.866911 [info] web: initializing
2023/04/13 08:03:23.076718 [info] dnsproxy: cache: enabled, size 4096 b
2023/04/13 08:03:23.076955 [info] MaxGoroutines is set to 300
2023/04/13 08:03:23.078648 [info] AdGuard Home is available at the following addresses:
2023/04/13 08:03:23.079848 [info] go to http://127.0.0.1:80
2023/04/13 08:03:23.080609 [info] go to http://172.17.0.2:80
2023/04/13 08:03:24.847506 [info] Starting the DNS proxy server
2023/04/13 08:03:24.847566 [info] The server is configured to refuse ANY requests
2023/04/13 08:03:24.847597 [info] dnsproxy: cache: enabled, size 33554432 b
2023/04/13 08:03:24.847632 [info] MaxGoroutines is set to 300
2023/04/13 08:03:24.848358 [info] Creating the UDP server socket
2023/04/13 08:03:24.848831 [info] Listening to udp://[::]:53
2023/04/13 08:03:24.848878 [info] Creating a TCP server socket
2023/04/13 08:03:24.849750 [info] Listening to tcp://[::]:53
2023/04/13 08:03:24.850822 [info] Entering the tcp listener loop on [::]:53
2023/04/13 08:03:24.850892 [info] Entering the UDP listener loop on [::]:53
`

**Comment by sanderbohm** [comment]
i'm having the same problem (exact stop at the log line above)

2023/04/13 08:03:24.850892 [info] Entering the UDP listener loop on [::]:53

Docker ps says unhealthy container and portainer is giving me the error:

Last output | nslookup failed for 0.0.0.0:53
