### ISSUE TITLE
AdGuard Dashboard && Query log

### ISSUE THREAD

**Issue by chayan-cse** [AdguardTeam/AdGuardHome#5709]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.27

### Description

Every think is okay But Dashboard don't show [DNS Queries] [Blocked by Filters] [Blocked malware/phishing] [Blocked adult websites] And also don't work Query log.

How to fix the problem?

AdGuardHome is install OrangePi Pc.
This pc IP address also static

**Comment by devipasigner** [comment]
> Also how do we enable malware/phishing filter so it shows in the statistics?

That's driven by the adguard malware/parental option. In the future they will allow users to categorize block lists so that it will show in statistics. Ads, malware, trackers, etc.
