### ISSUE TITLE
Docker container fails to start with release v0.107.28

### ISSUE THREAD

**Issue by NaterGator** [AdguardTeam/AdGuardHome#5711]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.28

#### What did you do?

I am running AGH on my Synology NAS inside a docker container, I'm using the DSM 7.1 docker interface to manage the container. I downloaded the newest release via the `latest`  tag from docker hub and reset the container to upgrade. Upon trying to restart the container it exits and respawns immediately, spamming the logs with: 
`[FATAL tini (8)] exec -h failed: No such file or directory`

#### Expected result

Docker container starts after upgrading.

#### Actual result

Docker container fails to start

#### Additional information

Running the most recent DSM release for my DS1618+: DSM 7.1.1-42962. DSM indicates the container execution command is `/sbin/tini -- -h 0.0.0.0 -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work --no-check-update`

**Comment by NaterGator** [comment]
Seems to be a limitation of the synology DSM interface, and the container must be completely removed and re-added to pick up the new entrypoint / execution command.

**Comment by ovizii** [comment]
I'm not running it on DSM and the same problem occurred. docker compose down followed by docker compose up -d did not help.

Any other ideas?

**Comment by NaterGator** [comment]
@ovizii you'll need to ensure that your container's execution command is correct. The Dockerfile has changed so now the correct command as reported by DMS/portainer is `/sbin/tini -- /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work` 

This means the entrypoint is `/sbin/tini --` (to reap zombie processes when exiting) and the command is `/opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work`

**Comment by pascalwinters** [comment]
I have the same issue on Synology DSM:
`[FATAL tini (9)] exec --no-check-update failed: No such file or directory`

What to do?
@NaterGator Did you already found a solution?
