### ISSUE TITLE
AGH v0.107.28 docker image does not start

### ISSUE THREAD

**Issue by szjani** [AdguardTeam/AdGuardHome#5713]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.28

#### What did you do?

I was using v0.107.27 in Docker on a Synology NAS. Watchtower updated the container to v0.107.28 and the container is continuously restarted as it cannot not start. I had a lot of successful version updates with Watchtower, this is the first time it fails.

#### Expected result

Minor version upgrade should happen without any issues.

#### Actual result

The container does not start. I can see the followings in the log:

```
[FATAL tini (7)] exec -h failed: No such file or directory
[FATAL tini (11)] exec -h failed: No such file or directory
[FATAL tini (8)] exec -h failed: No such file or directory
```

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/545872/231602524-7dbe6b53-672b-4e3f-93ec-f9cefe2432c4.png)

#### Additional information

Moving back to v0.107.27 the container starts without any errors, works as expected.

**Comment by dmmmuse** [comment]
I am experiencing the same issue running AGH Version:  v0.107.28 on a k8s cluster. When I revert to Version:  v0.107.27, everything works perfectly. Same error as stated above

**Comment by Turbine1313** [comment]
Same problem here after upgrade to v0.107.28. Running on portainer via debian.

**Comment by maxcanna** [comment]
Set both `CMD` and `ENTRYPOINT` to the default. Watchtower during the update carries the settings from the old version (even if they were default) and those are incompatible with the new one

**Comment by Turbine1313** [comment]
> Set both `CMD` and `ENTRYPOINT` to the default. Watchtower during the update carries the settings from the old version (even if they were default) and those are incompatible with the new one

This is what I have there now :
CMD	-c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work
ENTRYPOINT	/sbin/tini --

What should I use instead ?

**Comment by maxcanna** [comment]
> > Set both `CMD` and `ENTRYPOINT` to the default. Watchtower during the update carries the settings from the old version (even if they were default) and those are incompatible with the new one
> 
> This is what I have there now : CMD -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work ENTRYPOINT /sbin/tini --
> 
> What should I use instead ?

As I said, do not set them. Leave them as specified in the image

**Comment by ovizii** [comment]
> Set both `CMD` and `ENTRYPOINT` to the default. Watchtower during the update carries the settings from the old version (even if they were default) and those are incompatible with the new one

OK, so what do we do now watchtower has updated the container? Stopping and removing it and then starting it again doesn't fix the problem nor is there any error to be seen in its logs.

**Comment by maxcanna** [comment]
> > Set both `CMD` and `ENTRYPOINT` to the default. Watchtower during the update carries the settings from the old version (even if they were default) and those are incompatible with the new one
> 
> OK, so what do we do now watchtower has updated the container? Stopping and removing it and then starting it again doesn't fix the problem nor is there any error to be seen in its logs.

As I told you, you've to create the container w/o setting those values. If you start it with the same values set it's obviously gonna crash again 🤷🏻
BTW the error is clearly visible in the log present in the OP

**Comment by ovizii** [comment]
My bad, wrong thread, sorry about that :-( I had too many tabs open, replied to the wrong thread.

**Comment by Aad3229** [comment]
Same problem here after upgrade to v0.107.28 ([FATAL tini (9)] exec -h failed: No such file or directory). Running on Synology DS218+ in Docker

**Comment by maxcanna** [comment]
> Same problem here after upgrade to v0.107.28 ([FATAL tini (9)] exec -h failed: No such file or directory). Running on Synology DS218+ in Docker

Did you try https://github.com/AdguardTeam/AdGuardHome/issues/5713#issuecomment-1506397905 ?

**Comment by Aad3229** [comment]
> > Same problem here after upgrade to v0.107.28 ([FATAL tini (9)] exec -h failed: No such file or directory). Running on Synology DS218+ in Docker
> 
> Did you try [#5713 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/5713#issuecomment-1506397905) ?

 I do not use Watchtower. As always I manually updated the image, stopped and reset the container. Unfortunately it does not start now. I do not know how or where to do the actions described in #5713

**Comment by Laibalion** [comment]
@Aad3229 , I was in the same boat as you. Afaik there is no way to alter the Execution Command of the container once it is created, which is what you need to do.
So what you can do is export the configuration of the container to your local computer, for reference.
Delete the existing container
Create new container and set it up with the needed volume bindings, network mode, and env variables (ie. TZ etc)

**Comment by NebzHB** [comment]
Same error on synology. CMD and ENTRYPOINT are not set anywhere.

**Comment by JaZo** [comment]
Easiest way to fix this on a Synology:

1. Export the settings to JSON;
2. Change `cmd` to `"/opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work"` with your favorite text editor (as taken from the [Dockerfile](https://github.com/AdguardTeam/AdGuardHome/blob/master/docker/Dockerfile#L81-L87));
3. Delete the existing container;
4. Import the JSON file.

**Comment by ovar0409** [comment]
FYI, I had the same problem after upgrade to v0.107.28 or .29. Also running on Synology DS218+ in Docker.
In Portainer I duplicated the container, and in "Advanced Container Settings" I changed the Command and the Entrypoint to Default as indicated by maxcanna. AGH is now running again...

**Comment by szjani** [comment]
I am closing this issue. There is a solution, I don't know if using watchtower to update AGH is a good idea though.
