### ISSUE TITLE
fix webpack-dev-server vulnerability

### ISSUE THREAD

**Issue by happyhater** [AdguardTeam/AdGuardHome#572]
I found 2 low severity vulnerabilities:

Change with this line "webpack-dev-server": ">=3.1.11" in client/package.json
and
npm update merge --depth 7

**Comment by IldarKamalov** [comment]
Fixed in https://github.com/AdguardTeam/AdGuardHome/commit/c494e17df57a0f4d96cf947bf9ce7b2e74d23a9c
