### ISSUE TITLE
Docker: exec --no-check-update failed: No such file or directory

### ISSUE THREAD

**Issue by prosperot** [AdguardTeam/AdGuardHome#5730]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

x86

### Installation

Synology Docker

### Setup

On one machine

### AdGuard Home version

0.107.28

### Description

After resetting the container with 0.127.28, the container does not start.

Error message is : 
stdout | [FATAL tini (7)] exec --no-check-update failed: No such file or directory

After the error message, the container tries to restart, but this gives the same error

Rolled back to 0.107.27 , and the problem has disappeared. 

It might be the new Docker run command in .28:  /sbin/tini. afaik Synology Docker does not have the tini command in sbin

**Comment by nklmilojevic** [comment]
Same here - just `--conf` error. Rolling back to .27 worked.

**Comment by pascalwinters** [comment]
#5721 related/same issue

**Comment by gerritjanh** [comment]
Had the same problem. Removing an re-installing the container solved this for now.

**Comment by ainar-g** [comment]
Merging into #5721 and #5713.

**Comment by FlorisHigh3IT** [comment]
Same issue here, rolled back to 0.107.27

**Comment by Fr3d3rick83** [comment]
Same issue here, wie Synology and docker:
[FATAL tini (9)] exec --no-check-update failed: No such file or directory

**Comment by nrlatsha** [comment]
From what I gathered from previous interactions with the Synology development team - they don't care about consumer problems, only corporate support.

Everyone is going to have to figure this out for themselves.  Rebuild your containers, as long as you re-map the required directories, you should still have your configs.
