### ISSUE TITLE
Request: Add counter for usage/hits of blocklists to identify the more successful blocklists

### ISSUE THREAD

**Issue by Knubbel** [AdguardTeam/AdGuardHome#5736]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Reduce number of blocklists loaded by identifying which ones help me most (to later remove those blocklists which did not block anything over a certain time)

#### Proposed solution
**Add a "counter" that is incremented each time a DNS request is blocked by an item on a certain blocklist.** Display the number of "hits" per blocklist.
Very similar to today's offering where I can see which domains were blocked most often oder how many blocked requests there were per client. **I want to see which of my blocklists help a lot and which ones never score.**

Bonus request (priority 2):
The cream on top would be to also count which blocklists gets overridden how often by my individual allowlists. That is the inverse situation and would allow me to identify blocklists which want to block too much.

#### Alternatives considered
none

#### Additional information
There are dozens of blocklists available and I assume most of them are great for certain usecases but not for everyone.
Today if I want to get best blocking I either invest major effort in pimping my individual blocklist or I load multiple blocklists from the internet. But I can not tell which ones are actually useful. So basically I stress my system with potentially thousands of blocklist entries which do not make sense for my use case.
Just staring at samples of the activity log is no robust way.
And adding counters doesnt sound hard to implement to me or stressing system performance.

**Comment by ainar-g** [comment]
Merging into #4524.
