### ISSUE TITLE
Chaos with eero+ObserverIP weather station

### ISSUE THREAD

**Issue by flipphillips** [AdguardTeam/AdGuardHome#574]
### Steps to reproduce

1. eero set to not use ipv6 (otherwise, bypasses adguard when necessary and uses Google DNS)
2. eero DNS caching off
3. ObserverIP station configured to get fixed IP from eero
4. Latest firmware / AdGuardHome on all

### Expected behavior

ObserverIP weather station should be able to get proper entry for `rtupdate.wunderground.com` and go on its way

### Actual behavior

ObserverIP cannot connect to upstream weather server. Makes a call to get IP for `rtupdate.wunderground.com` repeatedly, every 10 sec. 

It seems to be getting the right 'embedded' ip
```
maxwell:~> nslookup rtupdate.wunderground.com
Server:		192.168.7.179
Address:	192.168.7.179#53

Non-authoritative answer:
rtupdate.wunderground.com	canonical name = prod-pws-ng-ingest-368531364.us-west-2.elb.amazonaws.com.
Name:	prod-pws-ng-ingest-368531364.us-west-2.elb.amazonaws.com
Address: 54.68.202.145
Name:	prod-pws-ng-ingest-368531364.us-west-2.elb.amazonaws.com
Address: 54.68.5.241
```

The firmware also makes reference to `api.ambientweather.net`

```
maxwell:Desktop> nslookup api.ambientweather.net
Server:		192.168.7.179
Address:	192.168.7.179#53

Non-authoritative answer:
api.ambientweather.net	canonical name = ambient-weather-amb.nanoapp.io.
Name:	ambient-weather-amb.nanoapp.io
Address: 107.170.198.71
```

which seems to resolve OK too...  so I have no idea what is going on...

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92-hotfix2
| How did you setup DNS configuration:| eero control panel → Raspberry Pi 3
| If it's a router or IoT, please write device model:| Raspberry Pi 3
| Operating system and version:| Linux adguardhole 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

**Comment by ameshkov** [comment]
Questions:

1. What upstream do you have configured in AdGuardHome? Is there any change when you use a different upstream?
2. Do you see this or related DNS requests in the query log?
3. Try running AG Home with `-v` argument, maybe there will be something useful in the verbose log.

> Linux adguardhole

Lol 😄

**Comment by flipphillips** [comment]
1. 1.1.1.1 and friends
2. the `wunderground` requests show up, interestingly, the `ambientweather` don't seem to be there. IIRC, the device does try to 'go there' first. When I get back home today I'll look and see more carefully.
3. Will do-
