### ISSUE TITLE
/control/querylog no longer returns 'status' value

### ISSUE THREAD

**Issue by jojost1** [AdguardTeam/AdGuardHome#5740]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.28

#### What did you do?

GET /control/querylog

#### Expected result

<img width="466" alt="image" src="https://user-images.githubusercontent.com/8880568/232307759-f5e998da-280d-42b1-9941-ab6dc4d4ad3d.png">

#### Actual result

For example:
```json
{"data":[{"cached":true,"client":"192.168.1.68","client_info":{"whois":{},"name":"","disallowed_rule":"192.168.1.68","disallowed":false},"client_proto":"","elapsedMs":"0.119869","original_answer":[{"type":"A","value":"17.248.176.47","ttl":89},{"type":"A","value":"17.248.176.231","ttl":89},{"type":"A","value":"17.248.176.54","ttl":89},{"type":"A","value":"17.248.176.51","ttl":89},{"type":"A","value":"17.248.177.44","ttl":89},{"type":"A","value":"17.248.176.198","ttl":89},{"type":"A","value":"17.248.177.9","ttl":89},{"type":"A","value":"17.248.177.236","ttl":89}],"question":{"class":"IN","name":"gateway.fe.apple-dns.net","type":"A"},"reason":"NotFilteredNotFound","rules":[],"time":"2023-04-16T13:47:17.670577437+02:00","upstream":"1.1.1.1:53"}],"oldest":"2023-04-16T13:47:17.670577437+02:00"}
```

The "status" variable is missing, while it was pretty much always there before. Possible values were for example 'NOERROR' and 'NXDOMAIN'.

**Comment by ainar-g** [comment]
Hello.  This is likely a dup of #5725. Can you please check the latest Edge build to see if that fixes new queries for you?

**Comment by jojost1** [comment]
Hi, could be. I'm running the `beta` channel so not sure if I can check the fix (that was just released to production, but not to beta it seems).

**Comment by jojost1** [comment]
Thanks, helpful to know! As the fix is already out, I'd rather wait for a new beta release to spare the hassle if that's okay 😄 assuming there will be a new beta build very soon.

**Comment by EugeneOne1** [comment]
@jojost1, the beta release is coming later today, by the way.

**Comment by jojost1** [comment]
@ainar-g I've checked and it seems like the `status` value is back for some queries, **but not all**. The API documentation says the value is always there, right? Can you reproduce my issue?

**Comment by ainar-g** [comment]
@jojost1, it's likely that it is missing for the older records that were corrupted by the bug.  Or are you seeing records without that property on newer logs on the current release as well?

**Comment by jojost1** [comment]
That could have been it, I'm not seeing any missing status values right now :-) I'll close this for now, thanks!
