### ISSUE TITLE
Unable to start DHCP server on FreeBSD with multiple interfaces

### ISSUE THREAD

**Issue by rcunov** [AdguardTeam/AdGuardHome#5742]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

FreeBSD

### CPU architecture

AMD64

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.28

#### What did you do?
When trying to enable the DHCP server on any interface on my OPNsense machine, it fails to set a static IP even though all interfaces on the machine have a static IP set in the OPNsense GUI.

I saw a [closed issue](https://github.com/AdguardTeam/AdGuardHome/issues/3967) related to this that recommended adding a line like `defaultrouter="<address>"` to the `rc.conf`, but that didn't work for me. To test fixes, I tried setting up the DHCP server on the VLAN 100 interface, `vlan0.100` (which has a static IP of 192.168.146.1/24), and my `/etc/rc.conf.d/adguardhome` file looks like this: 
```
adguardhome_enable="YES"
ifconfig_vlan0.100="inet 192.168.146.1 netmask 0xffffff00"
defaultrouter="192.168.146.1"
```
I tried including only the second line, only the third line, and both to trick AGH into thinking there's a static IP to no avail. I also tried this idea for all VLAN interfaces and a standard interface, without any luck.

#### Expected result
DHCP server to successfully start and pass out addresses on multiple interfaces

#### Actual result
Fails with this error message:
`Error: control/dhcp/set_config | enabling dhcp: setting static ip: setting static ip is unsupported on freebsd | 500`

#### Screenshots (if applicable)
After clicking "Save configuration":
<img width="976" alt="image" src="https://user-images.githubusercontent.com/61329286/232559115-06d15f26-da43-434c-a16b-a711204e9c84.png">

#### Additional information
I don't think this should be problematic, but I installed AGH through an OPNsense community repository. I followed these [installation instructions](https://0x2142.com/how-to-set-up-adguard-on-opnsense/#configure-opnsense-dhcp-to-use-adguard) using this [community repository](https://www.routerperformance.net/opnsense-repo/).

**Comment by ainar-g** [comment]
Hello.  This is most likely the same issue as #5712.  Can you test the latest Edge build and see if that fixes the issue for you?
