### ISSUE TITLE
Cant resolve local domain ip using reversed dns resolver.

### ISSUE THREAD

**Issue by vadimkara** [AdguardTeam/AdGuardHome#5743]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

 v0.107.28

#### What did you do?
Try to open local domain site in browser.

#### Expected result
Site is loded

#### Actual result
Time out.
#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/7599876/232572454-f5583c83-7cb5-4e5e-8db2-1da78ce1d4a9.png)
![image](https://user-images.githubusercontent.com/7599876/232572545-7ddd1bfc-2d35-4708-8ce6-d3d76eaedb6b.png)

**Comment by vadimkara** [comment]
![image](https://user-images.githubusercontent.com/7599876/232572968-fb56f173-32b2-461b-9215-9781172eba82.png)
![image](https://user-images.githubusercontent.com/7599876/232572996-a592d14e-c1c5-4685-8c24-68ca50fd1dc3.png)
![image](https://user-images.githubusercontent.com/7599876/232573205-095d9e8a-5a82-432c-82fc-2039d20695e3.png)

**Comment by ainar-g** [comment]
Hello.  We cannot reproduce this.  Based on the query log screenshots, the queries are processed, but your cmdlet doesn't get the response for some reason.  Please try the following:

1.  Enable [verbose logging][1] in AdGuard Home and see if there are any clues when you make the requests.

2.  Try explicitly using the DNS server based on the address:

    ```ps1
    Resolve-DnsName -DnsOnly -Name '….local' -Server '192.168.90.9' -Verbose
    ```

3.  Try using `dig` or `nslookup` instead.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by vadimkara** [comment]
![image](https://user-images.githubusercontent.com/7599876/232799530-ed72602d-b4a3-40df-a30c-56994de5d194.png)
![image](https://user-images.githubusercontent.com/7599876/232800590-a4ea8e26-9bac-4f6c-8812-8d200873f596.png)

Log has no errors adress resolved.

**Comment by vadimkara** [comment]
yes i tried it also time out.
![image](https://user-images.githubusercontent.com/7599876/233118092-73a07faf-66ca-4fc2-9f06-a5eb8f0f8c3d.png)

**Comment by vadimkara** [comment]
Before i was on 108 edge version and it was working very well.

**Comment by ainar-g** [comment]
That is weird.  Can you remember, which Edge version was the last one that worked for you?

Also, if you could record the verbose logs during AdGuard Home startup and those queries and send them to <devteam@adguard.com> with the words “AdGuard Home Issue 5742” in the subject line, that could help us diagnose the issue.
