### ISSUE TITLE
v0.107.28 default upstream DNS configuration is not working

### ISSUE THREAD

**Issue by bbartlomiej** [AdguardTeam/AdGuardHome#5744]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.28

#### What did you do?
Similarly to #4315 a default installation of AdGuardHome from sources (v0.107.28) is configured to use https://dns10.quad9.net/dns-query which doesn't work:

`Server "https://dns10.quad9.net/dns-query": could not be used, please check that you've written it correctly`

It's unable to download even the default filter list. After changing to any other DNS resolver it works.
For instance using "https://dns.adguard-dns.com/dns-query" instead is perfectly fine.

#### Expected result

Default configuration of AdGuardHome is operational out of the box.

#### Actual result

Default DNS server https://dns10.quad9.net/dns-query doesn't work.

#### Additional information
Built from sources on NetBSD (expect a pull request soon)

**Comment by ainar-g** [comment]
We cannot reproduce that, unfortunately.  What errors do you see if you [enable verbose logs][1] when testing the upstream?

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by bbartlomiej** [comment]
I get
`Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.997975 2586#45 [debug] dnsforward: checking if upstream "https://dns10.quad9.net/dns-query" works 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998066 2586#45 [debug] creating a new http client 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998181 2586#131 [debug] [2620:fe::fe:10]:53: sending request AAAA dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998221 2586#22 [debug] 149.112.112.10:53: sending request AAAA dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998253 2586#116 [debug] 9.9.9.10:53: sending request AAAA dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998226 2586#115 [debug] 9.9.9.10:53: sending request A dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998382 2586#130 [debug] [2620:fe::fe:10]:53: sending request A dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998411 2586#106 [debug] [2620:fe::10]:53: sending request A dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998336 2586#107 [debug] [2620:fe::10]:53: sending request AAAA dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998320 2586#21 [debug] 149.112.112.10:53: sending request A dns10.quad9.net. 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998632 2586#107 [debug] [2620:fe::10]:53: response: dial udp [2620:fe::10]:53: connect: no route to host 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998641 2586#130 [debug] [2620:fe::fe:10]:53: response: dial udp [2620:fe::fe:10]:53: connect: no route to host 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998647 2586#106 [debug] [2620:fe::10]:53: response: dial udp [2620:fe::10]:53: connect: no route to host 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.998801 2586#48 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): failed to lookup for dns10.quad9.net in 670.59<U+b5>s using 2620:fe::10: dial udp [2620:fe::10]:53: connect: no route to host 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.999818 2586#116 [debug] 9.9.9.10:53: response: ok 
Apr 18 13:16:21 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:21.999840 2586#22 [debug] 149.112.112.10:53: response: ok 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.000678 2586#131 [debug] [2620:fe::fe:10]:53: response: dial udp [2620:fe::fe:10]:53: connect: no route to host 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.000715 2586#49 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): failed to lookup for dns10.quad9.net in 2.593231ms using 2620:fe::fe:10: dial udp [2620:fe::fe:10]:53: connect: no route to host 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.010689 2586#21 [debug] 149.112.112.10:53: response: ok 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.010738 2586#115 [debug] 9.9.9.10:53: response: ok 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.010758 2586#47 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns10.quad9.net in 12.592878ms using 149.112.112.10. Result : [{0.0.0.0 }] 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.010774 2586#46 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns10.quad9.net in 12.646408ms using 9.9.9.10. Result : [{0.0.0.0 }] 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.011026 2586#45 [debug] using HTTP/2 for this upstream: HTTP3 support is not enabled 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.011692 2586#45 [debug] https://dns10.quad9.net:443/dns-query: sending request A test. 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.012050 2586#90 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): Dialing to 0.0.0.0:443 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.012165 2586#90 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): dialer failed to initialize connection to 0.0.0.0:443, in 63.6<U+b5>s, cause: dial tcp 0.0.0.0:443: connect: connection refused 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.012245 2586#45 [debug] https://dns10.quad9.net:443/dns-query: response: requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ": all dialers failed: dial tcp 0.0.0.0:443: connect: connection refused 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.012298 2586#45 [debug] re-creating the http client due to requesting https://dns10.quad9.net:443/dns-query: Get "https://dns10.quad9.net:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ": all dialers failed: dial tcp 0.0.0.0:443: connect: connection refused 
Apr 18 13:16:22 NetBSD AdGuardHome[2586]: 2023/04/18 13:16:22.012328 2586#45 [debug] using HTTP/2 for this upstream: HTTP3 support is not enabled 
`
So this looks like bootstrap servers don't work properly.

**Comment by bbartlomiej** [comment]
It was a problem with my router blocking access to this specific bootstrap server. Fixed.

**Comment by bbartlomiej** [comment]
It was a problem with my router blocking access to this specific bootstrap server. Fixed.
