### ISSUE TITLE
 #5691 is happening again (Sites misclassified as adult)

### ISSUE THREAD

**Issue by rschuetzler** [AdguardTeam/AdGuardHome#5745]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.28

### Description

See the report from #5691. Spike started about 3 hours ago, with sites like cdn.taboola.com, ad.turn.com, and geo.query.yahoo.com showing up in the adult site filtering.

**Comment by ainar-g** [comment]
Thanks for reporting, but AdGuard Home is only a client of the AdGuard Parental Control services.  Whenever there is a misclassification in the data there, it's better to report it through the [filter issue report form](https://reports.adguard.com/en/new_issue.html).  I've alerted the filter maintenance team, but please use the form directly next time.

**Comment by jaytay79** [comment]
What should we report it as on the form @ainar-g? There doesn't seem to be an option for misclassified sites (maybe there should be?)

**Comment by ainar-g** [comment]
@jaytay79, another way to report adult-blocking and safe-browsing filter errors is through E-mail at <support@adguard.com>.  The form needs some improvement as well, and I've let the people who support it know.

**Comment by jaytay79** [comment]
@ainar-g I tried the email address and they told me to come here instead!

> AdGuard Home is an open source project and is being supported by their developers directly. If you have any questions or problems regarding the product left - go to AdGuard Home Github page, [Issues](https://github.com/AdguardTeam/AdGuardHome/issues) tab.
