### ISSUE TITLE
Google Wifi can't access youtube.com and netflix.com via AdGuardHome

### ISSUE THREAD

**Issue by integrii** [AdguardTeam/AdGuardHome#575]
Steps to reproduce:
- Have a google wifi system
- have an adguard home instance on GCP
- disable all dns filtering on AdBlockHome
- point your google wifi DNS at the GCP instance with adguard home
- netflix.com and youtube.com along with various other domains stop resolving by timeout, but various websites like ebay.com and others work fine
- `nslookup` and `host` seem to resolve all DNS properly at all times

This is repeatable on every device in the house, including phones and playstation

I have poked this from several angles and here is a summary:

*Broken:*
- chrome dns client -> google wifi dns server as served by DHCP -> AdGuardHome (as custom dns in google wifi). 
Note: The query is shown in AdGuardHome's log as NOT filtered

*Works:*
- chrome dns client  -> google wifi dns server as served by DHCP -> Google DNS
- chrome dns client  -> google wifi dns server as served by DHCP -> opendns public server
- `nslookup`/`host` -> google wifi dns server as served by DHCP -> AdGuardHome
- any device/client -> directly AdGuardHome IP

Summary:

It appears that when all of the conditions below are true, DNS times out:
- when a client that isn't a cli-tool is used
- when accessing netflix.com or youtube.com
- Google wifi is used
- Google wifi is configured to use AdGuard DNS as a custom DNS server

AdGuardHome always appears to log and return all queries properly, but the response never makes it back to the client.

It looks like this is an issue with Google Wifi when used with AdGuardHome.  Specifically it looks like Google home is blocking or dropping specific domain responses from AdGuardHome.  Strangely though, this never fails when using CLI tools.

Any ideas from anyone?

**Comment by ameshkov** [comment]
What upstream do you have configured in AG Home?

From the description, it reminds me of the bug with handling truncated responses which was fixed in dnsproxy already: https://github.com/AdguardTeam/dnsproxy/commit/c26e194b68e47724a7dd08d057737a222fb567d8

It'd be better to check it again once we updated the dnsproxy dependency in AG Home.

**Comment by integrii** [comment]
Hey @ameshkov - sorry I never got back to you or relied here.  This is fixed in the newest docker image of AdGuardHome today!  I just turned it on again 48 hours ago and things are working great.

**Comment by ameshkov** [comment]
Thank you!

**Comment by integrii** [comment]
This problem mysteriously returned, but I found a fix.  Maybe you can tell me what is going on.

When netflix.com or youtube.com were queried from chrome, nothing worked.  This does not occur on android or iphone devices, my playstation, xbox, or even from command line.

I simply went to AdGuard Home and clicked 'Disable Protection' on the main page.  I already had all filtering off, but apparently this button disables something even more.

![image](https://user-images.githubusercontent.com/98695/59008179-7102a900-87de-11e9-992a-cbe50fee0ba8.png)

Upstream, I am using Cloudflare's DNS over HTTPs endpoint, FYI.

As soon as I Enable Protection (whatever its doing) the problem returns.  Seems to be a bug?  Very strange that it only effects chrome.

**Comment by ameshkov** [comment]
What other settings do you have in AdGuard?
Safe search, filter lists, etc?
