### ISSUE TITLE
Bootstrapping errors in v0.108.0-b.34

### ISSUE THREAD

**Issue by ealap** [AdguardTeam/AdGuardHome#5755]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.34

#### What did you do?
Upgrade from v0.108.0-b.33 to v0.108.0-b.34

#### Expected result
All supported settings are still working as expected 

#### Actual result
Setting for upstream server fails to save because it seems unable to resolve the hostnames of another container from the same network, e.g.
```
udp://unbound:53
```
Explicitly specifying the IP address of the same container still works.

**Comment by ainar-g** [comment]
Hello.  AdGuard Home uses the bootstrap servers to resolve hostnames.  Did you add the bootstrap IP address of the server that knows what `unbound` is?

**Comment by ainar-g** [comment]
Then you should add the IP address of the resolver that knows the IP address of `unbound` into the bootstrap servers input, and that should restore the functionality.  The previous behavior, using bootstrap servers for some upstreams but not others, was incorrect, and has been fixed in v0.108.0-b.34.
