### ISSUE TITLE
SafeSearch does not work for Google

### ISSUE THREAD

**Issue by mveplus** [AdguardTeam/AdGuardHome#576]
Google safe search is not applied when "safesearch_enabled: true" and using default upstream_dns.
Running latest offical version: v0.92-hotfix2 
Local address: 192.168.0.254:53

### Steps to reproduce
1. Grab binary archive 
2. Extract and run as root, listening on :53, 3000
3. Navigate to the web interface and turn on Enforce SafeSearch
4. dig or nslookup should return Google VIP or CNAME
 
### Expected behavior
Google will serve SafeSearch Search and Image Search results for requests that we receive on this VIP.

### Actual behavior
Looking at the results ( DNS queries)  no  SafeSearch Search and Image Search is applied.

All family protections ticket on under General settings:
nslookup www.google.com 176.103.130.132
Server:		176.103.130.132
Address:	176.103.130.132#53
Name:	www.google.com
Address: 216.239.38.120

nslookup www.google.com 192.168.0.254
Server:		192.168.0.254
Address:	192.168.0.254#53
Non-authoritative answer:
Name:	www.google.com
Address: 216.58.206.132

Only Enforce SafeSearch ticket on under General settings:
nslookup www.google.com 192.168.0.254
Server:		192.168.0.254
Address:	192.168.0.254#53
Non-authoritative answer:
Name:	www.google.com
Address: 172.217.23.36

nslookup www.google.com 176.103.130.132
Server:		176.103.130.132
Address:	176.103.130.132#53
Name:	www.google.com
Address: 216.239.38.120

### Your environment

Proxmox - LXC container Debian GNU/Linux 8 (jessie)
|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (v0.92-hotfix2 )
| How did you setup DNS configuration:| System and Router, 
| Upstream DNS servers - default AdGuard Home server tls://
| If it's a router or IoT, please write device model:| Dell Vostro 460
| Operating system and version:| Debian GNU/Linux 8 (jessie)

If I do change Upstream DNS servers in AdGuard Home Settings to AdGuard Family shield .132/.133 it works.

**Comment by ameshkov** [comment]
Confirmed, thank you!
