### ISSUE TITLE
AdGuard Home, version v0.107.29 - but in Web interface it shows v0.107.26

### ISSUE THREAD

**Issue by akondrasev** [AdguardTeam/AdGuardHome#5771]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.29 or v0.107.26 (see the title)

#### What did you do?
I had version 0.107.27(!!) running on my router. Then I read about Adguard Home has released new version 0.107.28 and decided to ignore this. However, when 0.107.29 released I decided to update to that version. 
I logged in to the router via Putty and ran "AdGuardHome --update" command which showed all messages about how successful the update was. Now I can check the version of the application, which shows it is .29: 
![image](https://user-images.githubusercontent.com/9110254/234357496-474587c0-1824-4775-aed0-dcba32f56fbf.png)

Then I go to the router web interface and open adguard home web interface, which then shows me I am actually using .26 version, which is kind of surprising after updating from .27 I went down to .26. 
![image](https://user-images.githubusercontent.com/9110254/234358301-6115cb06-8457-4e0f-a324-0d37e9105778.png)

#### Expected result
I should be able to use the latest web interface version

#### Actual result
Somehow, I am at the lower version of web interface than it was before update

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/9110254/234357496-474587c0-1824-4775-aed0-dcba32f56fbf.png)
![image](https://user-images.githubusercontent.com/9110254/234358301-6115cb06-8457-4e0f-a324-0d37e9105778.png)

**Comment by EugeneOne1** [comment]
@akondrasev, as per [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments) the `--update` option does the following:

 >  Update the current binary and restart the service in case it's installed.

So if it wrote a message about successful update and nothing more, this is weird and needs investigation.  However, I should ask if you tried to restart the service (binary) manually?

**Comment by akondrasev** [comment]
I just happened to have a router restart recently and it seems the problem is solved now, will try to monitor output of `--update` carefuller next time

**Comment by EugeneOne1** [comment]
@akondrasev, I'd say, it would be useful to run it with both `-v` and `--update` options.  Thus, the occured error will also be printed.  Closing the issue for now, please feel free to reopen it if the problem will appear again.
