### ISSUE TITLE
Unable to update filter normally after v0.107.21

### ISSUE THREAD

**Issue by kai855** [AdguardTeam/AdGuardHome#5777]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

32-bit MIPS LE

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.29

#### What did you do?
After updating the new version, check for updates the filter
#### Expected result
Normal update filter
#### Actual result
Filter update is stuck. After WinSCP inspection, it was found that the rule download speed was slow. Even if a very small file is updated, it will be downloaded again after completion and will not be applied.
#### Additional information
V0.107.21 version is updated normally, and this situation will occur in any subsequent version

**Comment by EugeneOne1** [comment]
@kai855, hello and thanks for the report.  Unfortunately, we can't reproduce the double downloading.  Could you please capture the filter updates with [verbose log](https://github.com/adguardteam/adguardhome/wiki/FAQ#verboselog)?  You may send it here or to devteam@adguard.com.

**Comment by kai855** [comment]
@EugeneOne1 When I used v0.107.29, the download filter was very slow, downloading at a speed of approximately 2KB per second. But using v0.107.21 and earlier versions is quite fast. It may be caused by the filters updating strategy of v0.107.22.
