### ISSUE TITLE
client Upstream DNS servers not use cache

### ISSUE THREAD

**Issue by sleepm** [AdguardTeam/AdGuardHome#5779]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.29

**Comment by EugeneOne1** [comment]
@sleepm, it indeed doesn't.  See AdguardTeam/dnsproxy#169.
