### ISSUE TITLE
AGH Login page no longer works (Traefik File Provider + Adguard Home in Docker)

### ISSUE THREAD

**Issue by benisai** [AdguardTeam/AdGuardHome#5782]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.29

### Description

VPS with Treaefik as reverse proxy.
AGH in Docker at home server (Ubuntu 22.4.2) 

I've been using Traefik as my reverse proxy for a while now, but recently, AGH login page does not load. F12 shows 
these 2 not loading. Something changed in AGH code where it doesnt reply to the proxy. 
AGH logs dont provide much. Treafik logs shows the connection going outbound, but AGH does not respond, it kicks back this error
""2023/04/28 22:38:40 reverseproxy.go:667: httputil: ReverseProxy read error during body copy: read tcp 172.18.0.10:41890->10.10.10.5:84: read: connection reset by peer." 

I can curl my agh webport, so I have connectivity. AGH is killing the request. I need to know why/how to fix it.

/login.c6c85272422dd3c3b02f.css
/login.c6c85272422dd3c3b02f.js

**Comment by benisai** [comment]
Rolling back to a version from 5 months ago doesnt work because the scheme isnt recognized ([fatal] unknown configuration schema version 20), so I cant prove when it broken.

**Comment by rfgamaral** [comment]
I'm having the same issue.

I've been running AdGuard Home with Traefik for years, and this never happened before.

I've only noticed this today, and I'm pretty sure everything was working fine for me a couple of weeks ago. Don't know exactly which version I was running, but I have auto-updates on my containers with watchtower so I'm tempted to say that this was a recent change, but @benisai opened this issue back in April. Not sure what to make of this.

**Comment by rfgamaral** [comment]
@ainar-g Can we please get some feedback on this one?

**Comment by ainar-g** [comment]
@benisai, @rfgamaral, have you tried the recent versions, including the required steps as [described in the release notes for v0.107.34](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.34)?  (See the “Removed” section.)

If so, [verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) of AdGuard Home should shed some light on what's happening.

**Comment by rfgamaral** [comment]
@ainar-g Awesome. Pulled the latest version, recreated the container, all is working for me with v0.107.36. Thank you!

**Comment by ainar-g** [comment]
Good to hear.  Assuming that OP has the same issue, I'll close this one.  Feel free to reopen if it's not the same, preferably with the verbose log data.

**Comment by benisai** [comment]
Not fixed for me. AGH is not responding from what treafik logs show. 
F12 shows the same 502 bad gateway. 
<img width="1466" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/59147467/39a3fc84-a26a-4e60-8890-84ec95d6bb41">

Traefik Logs:

> time="2023-08-16T01:53:34Z" level=debug msg="'502 Bad Gateway' caused by: read tcp 172.18.0.19:42206->10.10.10.5:84: read: connection reset by peer"
time="2023-08-16T01:55:37Z" level=debug msg="'502 Bad Gateway' caused by: read tcp 172.18.0.19:54528->10.10.10.5:84: read: connection reset by peer"

**Comment by benisai** [comment]
my Toml file looks like this, I do have Authelia inbetween as well:

`
 [http]
  [http.middlewares]
    [http.middlewares.adhome-redirect.redirectScheme]
        scheme = "https"

  [http.routers.adhome-redirect]
    entrypoints = ["http"]
    rule = "Host(`adguard.example.com`)"
    middlewares = ["adhome-redirect"]
    service = "adhome"

  [http.routers.adhome]
    entrypoints = ["https"]
    rule = "Host(`adguard.example.com`)"
    service = "adhome"
    middlewares = ["authelia@docker"]
    [http.routers.adhome.tls]
        certResolver = "letsencrypt"

  [http.services]
    [http.services.adhome.loadbalancer]
      [[http.services.adhome.loadbalancer.servers]]
        url = "http://10.10.10.5:84"
`

**Comment by benisai** [comment]
when I browse http://10.10.10.5:84/ locally, I can browse the webpage. When Treafik tries, it doesnt get a response from AGH.

**Comment by benisai** [comment]
My Traefik is able to ping/traceroute the subnet and telnet 10.10.10.5:84

so it has to be AGH not returning the response.

**Comment by ainar-g** [comment]
@benisai, please provide the verbose logs.  It's hard to diagnose anything without them.  If you have issues getting them, please describe the steps you're taking.

**Comment by dontcrash** [comment]
I am having the same result when using Traefik and AdGuardHome
![image](https://github.com/AdguardTeam/AdGuardHome/assets/32660358/d01f1cd3-5b25-4f7b-b48d-3e4e89dc01e6)

**Comment by iDevEngineer** [comment]
@dontcrash know this is an older post but I've got the same... ish issue. Ubuntu for AdGuard Home using Unbound on a VM. Traefik running Docker too. Below is my static YAML.
Did you get it resolved? Any help appreciated.

---
http:
  routers:
    adguard-https:
      rule: "Host(`adguard.dev.test`)"
      service: adguard-service
      entrypoints:
        - websecure
      tls:
        certResolver: cfresolver
    adguard-http:
      rule: "Host(`adguard.dev.test`)"
      service: adguard-service
      entrypoints:
        - web
      middlewares:
        - https-redirect
  services:
    adguard-service:
      loadBalancer:
        servers:
          - url: "https://10.20.5.1"
