### ISSUE TITLE
View statistics for particular host in the Dashboard

### ISSUE THREAD

**Issue by mahirchavda** [AdguardTeam/AdGuardHome#5784]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
I would like to view statistics shown in the dashboard for particular client/host/ip

#### Proposed solution
Add dropdown or text in the dashboard which will have default option all. Based on selection show the statistics for particular host

#### Alternatives considered
Not sure

#### Additional information
Not sure

**Comment by EugeneOne1** [comment]
@mahirchavda, hello and thanks for the request.  I suppose, this is an extension of #1336.  I'll merge it there if you don't mind, please consider adding a comment about particular hostnames and IPs.
