### ISSUE TITLE
`main.js` causes major page load delay on SD card installations

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#5788]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to request a feature or enhancement and not ask a question

### Description

The singular `main.js` file is the main cause of the delay that happens when the AGH web page is loaded.

<img width="975" alt="Screenshot" src="https://user-images.githubusercontent.com/19761269/235338215-907740b7-e67e-4f13-bee0-cbda55675ba5.png">

It would be great if this could be optimized, perhaps by dividing them into different files and loading only when needed.

**Comment by agneevX** [comment]
A temporary solution is to implement a caching reverse proxy but that comes with its own limitations

<img width="982" alt="image" src="https://user-images.githubusercontent.com/19761269/235347948-fc73d7c6-59bc-4463-9f31-2ce6acf37379.png">

**Comment by IRainman** [comment]
Static content always needs to be cached – this is a solution.

**Comment by agneevX** [comment]
It is a whole lot better now as it seems to take around half a sec:

<img width="999" alt="Screenshot 2024-05-01 at 11 18 27 AM" src="https://github.com/AdguardTeam/AdGuardHome/assets/19761269/9aeff8dc-dc88-439d-9bb3-f7578c268d32">
