### ISSUE TITLE
mikrotik container can not use latest version

### ISSUE THREAD

**Issue by it-cybertech** [AdguardTeam/AdGuardHome#5789]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest

### Description

mikrotik installed error latest version
if down Version: v0.107.23 can use and installed

**Comment by bfmatei** [comment]
Pretty sure this is due to #5495
