### ISSUE TITLE
I've 40 adguard Blocklist. When I click "Check for Updates" ADH gets stuck on pi4 model B

### ISSUE THREAD

**Issue by amrmzr** [AdguardTeam/AdGuardHome#5792]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

I want to check for adguard blocklist updates.

#### Proposed solution

Adguard should update the blocklists under filters

**Comment by whyisthisbroken** [comment]
I think that 40 are too much and the ram runs out...
You should consider to choose your lists for quality, not quantity.
Oisd, hagezi's, 1host. It's enough

**Comment by amrmzr** [comment]
> I think that 40 are too much and the ram runs out... You should consider to choose your lists for quality, not quantity. Oisd, hagezi's, 1host. It's enough

Hi!
I realised same, and delete most of them now working fine. Thanks alot :)
