### ISSUE TITLE
specify a specific port for a DNS rewrite

### ISSUE THREAD

**Issue by talonric332** [AdguardTeam/AdGuardHome#5796]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### Description

[feature request] add the ability to enter a specific port when entering an ip address for a DNS rewrite. this would be useful when having multiple services hosted on one machine.

**Comment by Khaled0Ebrahim** [comment]
Simply this does not exist
dns is used for ip resolution only.
Only the user or the router can change the port.
To achieve what you want, you will have to buy a good firewall router and make some rules to redirect traffic from one port to another using (destination nat).

**Comment by zunami** [comment]
Too bad, I would have the same wish: that DNS rewrites are forwarded by one port. I have an Opnsense firewall running AdGuard Home. I need to forward the internal traffic from the domain to a Synology, which in turn splits each app with ports.

**Comment by Khaled0Ebrahim** [comment]
@zunami you still can do it
just do the rewrite in adguard and port forwarding in opnsense. If you need more help seek opnsense community or search the internet.
