### ISSUE TITLE
"Allowed clients" feature block the internal container localhost address, so healthcheck returns "nslookup failed for localhost:53"

### ISSUE THREAD

**Issue by ShlomoShai18** [AdguardTeam/AdGuardHome#5799]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.29

#### What did you do?

I added a list of CDIRs to `allowed clients` in the DNS settings

#### Expected result

Block those who are not on the list, but exclude internal addresses like `localhost`

#### Actual result

it make the container to **fail the healtcheck** with error `nslookup failed for localhost:53`

#### Additional information
OS Version: Ubuntu 22.04.2 LTS
Docker Version: 20.10.21, build 20.10.21-0ubuntu1~22.04.3
Docker-compose Version: 1.29.2
after I added 127.0.0.1 myself to the `Allowed clients` it solve the problem.
i think you need to exclude it from the feature.
thank you!!!

**Comment by waltersobchak40** [comment]
+1 I've experienced this as well. It causes my Docker containers to get into an "unhealthy" state. 

nslookup: clock_gettime(MONOTONIC) failed nslookup: can't connect to remote host: Address not available /opt/adguardhome/scripts/healthcheck.sh: line 98: host: parameter not set

**Comment by EugeneOne1** [comment]
@ShlomoShai18, @waltersobchak40, FYI, we've also updated the [Docker wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/Docker#configuration) about it.

**Comment by gkeyes** [comment]
Add 172.17.0.1/24?

**Comment by ShlomoShai18** [comment]
@Mizzick @EugeneOne1 thank you!

**Comment by EugeneOne1** [comment]
@gkeyes, not really sure if containers may automatically assign it to `wget` and `nslookup`, but if the `127.0.0.1` doesn't make it works, probably you may want to try it.
