### ISSUE TITLE
Datacenter map on adguard dns web page

### ISSUE THREAD

**Issue by portalvasco** [AdguardTeam/AdGuardHome#58]
It will be a good point to show a datacenter map on any place of adguard dns web.

**Comment by ameshkov** [comment]
Yeah, that's a good idea. We'll do it after NL servers will be ready.

**Comment by portalvasco** [comment]
Ok, thank you very much. :)

**Comment by vozersky** [comment]
it will be nice to see it on the new website :)

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardDNS/issues/190

**Comment by ibksturm** [comment]
Any Progress there on map for datanters?

**Comment by ameshkov** [comment]
@ibksturm we'll do it after the new version is released (and the code is published)

**Comment by TPS** [comment]
@ameshkov Is this the map found mid-page @ https://adguard.com/en/adguard-dns/overview.html ?

**Comment by ameshkov** [comment]
@TPS yep it is
