### ISSUE TITLE
i cant login in 80

### ISSUE THREAD

**Issue by fenghuan1994** [AdguardTeam/AdGuardHome#5804]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.29

#### What did you do?
**I encountered a very unusual problem, docker installed adguardhome, after initialization the computer browser cannot access the dashboard. It will be redirected to HTTPS and cannot be accessed normally. But I can access it normally with a mobile browser. The system is ubuntu22.04.2server.

docker run --name adguardhome -v /home/fenghuan/docker/AdguardHome/work:/opt/adguardhome/work -v /home/fenghuan/docker/AdguardHome/conf:/opt/adguardhome/conf -p 53:53/tcp -p 53:53/udp -p 67:67/udp -p 688:68/tcp -p 688:68/udp -p 80:80/tcp -p 443:443/tcp -p 853:853/tcp -p 3000:3000/tcp -d adguard/adguardhome:latest

sudo netstat -nltp ：
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      1696/docker-proxy   
tcp        0      0 127.0.0.1:45457         0.0.0.0:*               LISTEN      622/containerd      
tcp        0      0 0.0.0.0:853             0.0.0.0:*               LISTEN      1598/docker-proxy   
tcp        0      0 0.0.0.0:688             0.0.0.0:*               LISTEN      1739/docker-proxy   
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1618/docker-proxy   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1717/docker-proxy   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      655/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1655/docker-proxy   
tcp6       0      0 :::3000                 :::*                    LISTEN      1703/docker-proxy   
tcp6       0      0 :::853                  :::*                    LISTEN      1605/docker-proxy   
tcp6       0      0 :::688                  :::*                    LISTEN      1746/docker-proxy   
tcp6       0      0 :::443                  :::*                    LISTEN      1624/docker-proxy   
tcp6       0      0 :::80                   :::*                    LISTEN      1724/docker-proxy   
tcp6       0      0 :::22                   :::*                    LISTEN      655/sshd: /usr/sbin 
tcp6       0      0 :::53                   :::*                    LISTEN      1661/docker-proxy 

sudo ufw status
Status: inactive**

**Comment by Freebase394** [comment]
@fenghuan1994  Please try more times. 

Your issue is related to someting on your docker end! 
Not AdGuardHome issue.

Please close this issue!

**Comment by DandelionSprout** [comment]
The very little I personally understand of the log, is that the log problem is for Docker instead of AdGuard Home, so I at least think I can close this after all.

**Comment by fenghuan1994** [comment]
I've solved it, it's an environmental issue. Forgot to close.Sorry
