### ISSUE TITLE
Add enforceable DNSSEC validation setting

### ISSUE THREAD

**Issue by L8X** [AdguardTeam/AdGuardHome#5806]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

To be fully able to benefit from DNSSEC, a DNS resolver needs to be able to reject responses which have invalid DNSSEC data.

See: https://developers.google.com/speed/public-dns/docs/security#dnssec

#### Proposed solution

Add an option in the DNS settings to enforce DNSSEC validation

#### Alternatives considered

Considered the use of external upstreams for this, but none offer the ability to reject responses with invalid DNSSEC, at least not mandatorily, anyway.

#### Additional information
 
N/A

**Comment by ainar-g** [comment]
Merging into #1579.
