### ISSUE TITLE
Fail to save custom filtering rule

### ISSUE THREAD

**Issue by tuapuikia** [AdguardTeam/AdGuardHome#581]
### Steps to reproduce
1. Run the docker image.
2. Go to adguard home filtering rules and add new regex
3. Error appear and failed to save (TypeError: Cannot read property 'data' of undefined)
4.

### Expected behavior
Custom rule should be able to save.

### Actual behavior
Error shown and rules are not updated.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.92-hotfix2-35-g5fed
| How did you setup DNS configuration:| System with docker
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

**Comment by tuapuikia** [comment]
Found the issue. My nginx drop PUT method by default. Enable PUT have solved the problem.

**Comment by ameshkov** [comment]
@tuapuikia is it a default nginx configuration? Does it also disable `DELETE` method?

We might consider switching everything to `POST` if so

**Comment by tuapuikia** [comment]
Nginx default allow PUT and DELETE. It just my nginx hardening script disable those method by default.
