### ISSUE TITLE
Error: control/querylog/config/update | attempted to read more than 65536 bytes | 400

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#5811]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.29

#### What did you do?
配置一个不启用日志的列表，这个列表很长，超出了 adguardhome 允许的范围

#### Expected result
可以正常添加而不报错

#### Actual result
Error: control/querylog/config/update | attempted to read more than 65536 bytes | 400

#### Screenshots (if applicable)
![报错了](https://user-images.githubusercontent.com/79040749/237041591-1f649bbb-1ab2-4d17-a068-c36cd134667a.jpg)

**Comment by schzhn** [comment]
As a workaround, you can manually edit the `querylog.ignored` property in the [configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).
