### ISSUE TITLE
Can't save ignored domains

### ISSUE THREAD

**Issue by Timdebruijn** [AdguardTeam/AdGuardHome#5813]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.29

#### What did you do?
I've tryed to add a domain to the "Ignored domains" for statistics.
#### Expected result
domain should be ignored and saved after saving.
#### Actual result
nothing happens, it's not added to the ignore list after hitting save.
#### Screenshots (if applicable)
<img width="609" alt="Screenshot 2023-05-09 at 13 50 47" src="https://github.com/AdguardTeam/AdGuardHome/assets/36660743/ba38c672-d30f-4539-948f-cfb9a4bdb181">
#### Additional information
the OS is Debian GNU/Linux 11 (bullseye)

**Comment by EugeneOne1** [comment]
@Timdebruijn, hello and thanks for the report.  If there any error message appears in the web UI?  Also could you please try to enable verbose logging and check if some related messages are written there?

**Comment by Mizzick** [comment]
Hello @Timdebruijn !

You may find lines like these in the verbose logs:

```
2023/05/17 11:31:33.194199 53843#47 [debug] started PUT 127.0.0.1:8089 /control/stats/config/update
2023/05/17 11:31:33.194361 53843#47 [debug] writing config file "[PATH-TO-CONFIG]/AdGuardHome.yaml"
2023/05/17 11:31:33.203514 53843#47 [debug] finished PUT 127.0.0.1:8089 /control/stats/config/update in 9.304156ms
```

Also it could be helpful if  you check your browser console.

**Comment by Timdebruijn** [comment]
After some more debugging, i found out that it was generating a 403 response on a PUT request. Turned out that my nginx reverse proxy was blocking PUT requests.
