### ISSUE TITLE
protection_disabled_until format blocks start up

### ISSUE THREAD

**Issue by jdheyburn** [AdguardTeam/AdGuardHome#5817]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

0.107.29

### Description

I'm running AdGuardHome via NixOS. It seems the protection_disabled_until config that gets set live doesn't like a particular format. I had disabled protection for 10 mins (I am in BST) and so it updated the config for protection_disabled_until. The value that is saved to this config is not one recognised by AGH

May 10 07:42:21 dee adguardhome[1947217]: 2023/05/10 07:42:21.578916 [error] parsing configuration file: parsing time "2023-05-06 12:06:15.134805+01:00" as "2006-01-02T15:04:05Z07:00": cannot parse " 12:06:15.134805+01:00" as "T"

**Comment by EugeneOne1** [comment]
@jdheyburn, hello and apologies for the late response.  Just to ensure, didn't you edit the configuration file manually?  Unfortunately, we aren't able to reproduce the behavior on our test machines.  Is it an option for you to share your configuration file to devteam@adguard.com?

**Comment by adamdicarlo0** [comment]
I just ran into this on AdGuard Home v0.107.55... **also on NixOS**.

And I figured out the problem! It is not AdGuardHome's bug.

When NixOS's systemd service starts AGH, it first runs adguardhome with `--check-config` (this is OK), and then runs `yaml-merge` [before starting the service](https://github.com/NixOS/nixpkgs/blob/b9045fe034554e9d1a388f812c179ddf8a990b32/nixos/modules/services/networking/adguardhome.nix#L188). `yaml-merge` rewrites the `protection_disabled_until` date like this:

```diff
-  protection_disabled_until: 2026-01-25T10:01:00.856538-08:00
+  protection_disabled_until: 2026-01-25 10:01:00.856538-08:00
```
