### ISSUE TITLE
SafeSearch with DNS over HTTPS has compatibility issues with Chrome

### ISSUE THREAD

**Issue by Hill-98** [AdguardTeam/AdGuardHome#5818]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

ARMv5

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.29

#### What did you do?

1. Enable SafeSearch and DNS over HTTPS
2. Set up a custom DNS over HTTPS provider in Chrome
3. Go to duckduckgo.com.

#### Expected result

everything is normal

#### Actual result

Can't access duckduckgo.com or other SafeSearch enabled sites, prompting DNS_PROBE_FINISHED_NXDOMAIN.

#### Additional information

I use kdig to test DNS over HTTPS and everything works fine

```
> kdig duckduckgo.com +https @dns.xxx.xxx
;; TLS session (TLS1.3)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(CHACHA20-POLY1305)
;; HTTP session (HTTP/2-POST)-(dns.xxx.xxx/dns-query)-(status: 200)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 0
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; duckduckgo.com.              IN      A

;; ANSWER SECTION:
duckduckgo.com.         600     IN      A       20.43.161.151

;; Received 48 B
;; Time 2023-05-10 16:23:44 CST
;; From 10.10.10.1@443(TCP) in 96.6 ms
```

**Comment by Khaled0Ebrahim** [comment]
I believe chrome doesn't support numeric doh
e.g you can't type in custom 1.1.1.1
one solution for this is to make a domain name for your dns via dns rewrite in adguard
for example mydns.local and put the ip address of the adguard dns server
then use mydns.local in chrome custom doh tab and try again

**Comment by Hill-98** [comment]
@Khaled0Ebrahim I have my own domain name and I'm using it too.

**Comment by Khaled0Ebrahim** [comment]
you see in requests coming from your pc in adguard when you try to use chrome in visiting any website?

**Comment by Hill-98** [comment]
Of course, I've checked the Adguard Home verbose logs and everything seems to be fine.

And this problem didn't exist before the SafeSearch option was changed.

**Comment by Khaled0Ebrahim** [comment]
can you show a part of your log with some blur on your sensitive data

**Comment by Hill-98** [comment]
[adguardhome.log](https://github.com/AdguardTeam/AdGuardHome/files/11467255/adguardhome.log)

The logs can be a bit messy, I removed some sensitive information, the focus is on duckduckgo.com, which I don't have access to.

**Comment by Khaled0Ebrahim** [comment]
I started reading the log file now
there is something weird here
ipv6 is used that can cause a problem let me finish reading

**Comment by Khaled0Ebrahim** [comment]
part of the requests in the log file here are AAAA
which means that they are done using ipv6
not all the websites have ipv6 so you get no response
I guess you should disable ipv6 in your router as an easy solution for now if you are not using it of course

**Comment by Hill-98** [comment]
I guess this has nothing to do with IPv6 because it automatically falls back to IPv4 when IPv6 is not available, other sites with or without IPv6 support work fine, sites with only SafeSearch don't work.

**Comment by Khaled0Ebrahim** [comment]
just try to disable ipv6 from your interface settings in your pc and try again

**Comment by Khaled0Ebrahim** [comment]
the thing you are talking about doesn't actually happen
because it receives domain doesn't exist Error
so it won't try using A type (ipv4)
It is from chrome side I geuss because ipv6 is preferred more than ipv4 and since it is there they use it for dns requests
this is happening for the sites having safe search only because when you try to access duckduckgo.com for example
adguard sends this to the server and knows that it should work in safe mode
so it returns this domain
safe.duckduckgo.com using the same type which came in the first place (AAAA)
so it returns doesn't exist
so you try again and you are stuck in a loop forever

**Comment by Hill-98** [comment]
Well, you are right, it does work fine after disabling IPv6.

But it's still a quirk, if I don't use secure search, my upstream DNS, still won't resolve the IPv6 address of duckduckgo.com (since I'm in China, I use a special DNS server as my upstream).

So the cause of this problem may be that Chrome is sending AAAA requests and receiving the wrong response, causing it to not use the A response.

**Comment by Khaled0Ebrahim** [comment]
there is no ipv6 for duckduckgo.com.
also it is not totally chrome's fault there is ways to organize ipv4 and ipv6 you can search in the topic if you are interested or ask anywhere related to networking how to fix it.

**Comment by Hill-98** [comment]
I'm just using duckduckgo.com as an example, my upstream DNS blocks AAAA resolution for some sites.

I don't have any issues with my IPv4 and IPv6 networks, they only occur when SafeSearch is enabled, and only for sites that support SafeSearch.

So this is still a quirk that AGH needs to fix.

**Comment by Khaled0Ebrahim** [comment]
It is not related to AGH
your pc sends an AAAA asking for something
AGH checkes if something is in parental list or safe search list
something is in the safesearch list so it returns the answer as for safe.something
which is doesn't exist in case of duckduckgo.com in any part of the world not only china
you can try Google google have ipv6

**Comment by Khaled0Ebrahim** [comment]
Forgot. google is not there in china

**Comment by Hill-98** [comment]
First, I can access Google using a proxy, my proxy only supports IPv4, that's why I block some sites AAAA in upstream DNS.  Then, when I turned off SafeSearch, I was always accessing Google on IPv4 because of my upstream DNS.

I'm going to bed, thanks for helping me troubleshoot, but I'm still waiting for an answer from the official developer.

**Comment by Khaled0Ebrahim** [comment]
No problem! I'm glad I could help. I hope that the official developer is able to help you resolve this issue.
