### ISSUE TITLE
AdGuardHome front-end style messed up

### ISSUE THREAD

**Issue by JiaRG** [AdguardTeam/AdGuardHome#5823]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv5

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.29

#### What did you do?

did nothing

I enabled ipv6 on my router 3 hours ago, it was working then, but now it's not working

#### Expected result

AdGuardHome front-end style is normal

#### Actual result

AdGuardHome front-end style messed up

#### Screenshots (if applicable)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/31472350/2a5c5b21-023b-4cee-99f7-dd80490ab6b0)

#### Additional information

`Linux uname -a` :
`Linux RT-AC68U-00B0 2.6.36.4brcmarm #1 SMP PREEMPT Sun May 14 12:48:19 EDT 2023 armv7l ASUSWRT-Merlin`

**Comment by muok** [comment]
Try clearing your browser cache.
