### ISSUE TITLE
Artist/Album filtering on Spotify by URL not working

### ISSUE THREAD

**Issue by daloki83** [AdguardTeam/AdGuardHome#5825]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

ARMv7

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.29

### Description

Operating system type: Home Assistant Operating System 2023.5.3 (https://www.home-assistant.io/installation/raspberrypi) 
How did you install AdGuard Home?: Its provided as an Add-on

#### What did you do?
Setup everything according the many manuals as DNS (DHCP will be done by Router) etc. and so far its working great.
Then my little daughter found some stuff on Spotify what is definetly not for her age, but the child-profile from Spotify will not filter this. So i started with custom filter rules (also with filterfiles from my website). 
For example:
`||https://open.spotify.com/intl-de/artist/0lFLP59V4TY3XgnrkFIwxK^`
`||https://open.spotify.com/intl-de/album/6X06cIAYz5nsDnVbDftsi3?si=yZQxhYedSDiaFi95iUby7Q^`
and many more. Even ChatGPT could give me a working solution :/

#### Expected result
i expected that these artist/album will be filtered from AdGuard so she will no longer has access to this. But nothing happend. Testet on different machines and also in the logfiles there is no entry to block this.

#### Actual result
Artist/Album blocking on Spotify with AdGuard isn't working

#### Screenshots (if applicable)
makes no sense ;-)
#### Additional information
Great tool which is almost perfect. But fixing this would such a great improvement for us!

**Comment by Khaled0Ebrahim** [comment]
You misunderstood something
the dns name is the part open.spotify.com only
the dns server doesn't see the whole URL
actually no one can see the whole url but the device and the server (in https connections because it is encrypted)
either you block the whole Spotify for her device or keep it no middle solutions using adguard or any other dns servers

**Comment by daloki83** [comment]
sounds reasonable. - bad for me. So it will also make no sense to search for any alternative (firewalls etc) if i got you correct?
Blocking (in this case) must be done on the device directly (which is on iphone, Alexa etc. not possible).

**Comment by Khaled0Ebrahim** [comment]
There are solutions for this but it is advanced and also can cause privacy problems, governments usually use DPI techniques to decrypt your data (it is not that easy but not impossible) there are also some firewalls specialized in that but it will cost you a lot.
I believe man in the middle to capture and decrypt data from the device side is not possible on iPhone
though it is on Android but either ways there are no firewalls for mobile that uses man in the middle and search for a url in the data and drop it
no software on mobile usually have this flexibility and the people in need just make it by there hands if they are a developers.
ask chatgpt for help it won't harm if it suggested an innovative idea but remember it always hallucinates about the things it doesn't know.
if nothing helps you will have to teach your daughter that this is not appropriate and make her a good person not accepting those things or listening to them (if you couldn't use an external firewall use her as a firewall)

**Comment by Khaled0Ebrahim** [comment]
chatgpt's answer: If you want to block a specific URL path, such as "spotify.com/username," while allowing other variations like "spotify.com/username1" to work, you will need a more advanced filtering mechanism that can inspect the full URL path.

One way to accomplish this is by using a web application firewall (WAF) or a proxy server with advanced URL filtering capabilities. These solutions can examine the complete URL and apply specific rules based on the path.

Here's an example of how you can configure a WAF or proxy server to block "spotify.com/username" while allowing other variations:

1. Set up a WAF or proxy server: Deploy a web application firewall or a proxy server that supports URL filtering.

2. Configure URL filtering rules: Within the WAF or proxy server settings, create a URL filtering rule to block the specific URL path. For example, you would set a rule to block "spotify.com/username."

3. Regular expression matching: Use regular expressions (regex) to create a rule that matches the desired URL path. For instance, you can use a regex pattern like "^spotify.com/username$" to match only that exact path.

4. Block action: Define the action to be taken when a URL matching the rule is encountered. In this case, the action would be to block or deny access to the specific URL path.

By implementing these steps, the WAF or proxy server will block requests to "spotify.com/username" while allowing other variations like "spotify.com/username1" or any other paths within the domain to pass through.

It's important to note that the exact configuration steps may vary depending on the specific WAF or proxy server solution you choose. Consult the documentation or vendor resources for detailed instructions on configuring URL filtering rules.
me: give example for a popular free solution
ChatGPT: One popular free solution for implementing URL filtering and blocking specific URL paths is using the open-source software Squid Proxy Server. Squid is a widely used caching proxy that can also be configured to block URLs based on patterns.

**Comment by daloki83** [comment]
Thanks for this hint. Im not sure, but maybe i will try it with that proxy or simply block the app. However its not your fault and thanks for the feedback!
Btw.: Have you ever noticed how hard it is to get a simple MP3 player....without all of this bloadware :-( strange thing ^^

**Comment by Khaled0Ebrahim** [comment]
It depends on the platform
in android specifically Samsung mp3 player they have Spotify integrated and they encourage you to download it
so does the other ones
I think youtube music might be a good way specially because they have parental control.
