### ISSUE TITLE
Inconsistent logging of remote IP address with reverse proxy

### ISSUE THREAD

**Issue by tunip** [AdguardTeam/AdGuardHome#5829]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.29

#### What did you do?
I am using AdGuard Home with Caddy as reverse proxy, which works fine so far.
Logging is inconsistent with this type of setup.

When I try to log in to the WebUI with incorrect credentials, the upstream IP (127.0.0.1) is logged.
However, when I log in successfully, the real remote IP (2006:af:cf02:8200:c5ef:71ff:fd21:8) is logged.

#### Expected result
When I try to log in to the WebUI with incorrect credentials, I expect the actual remote IP of the client to be logged as follows:
2023/05/18 11:28:24.546178 [error] POST dns.example.com /control/login: from ip 2006:af:cf02:8200:c5ef:71ff:fd21:8 invalid username or password

#### Actual result
2023/05/18 11:28:24.546178 [error] POST dns.example.com /control/login: from ip 127.0.0.1: invalid username or password
2023/05/18 11:28:33.794298 [info] auth: user "admin" successfully logged in from ip 2006:af:cf02:8200:c5ef:71ff:fd21:8

**Comment by fernvenue** [comment]
As you can see in [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption#reverse-proxy), AdGuardHome accept like `X-Real-IP`, `X-Forwarded-For`, `True-Client-IP` these kind of headers to forward remote IP address when using reverse proxy.

**Comment by tunip** [comment]
Thx for your answer. I see the real client IP address in the query logs and on successful logins to the WebUI. No issue here.

Only the "invalid username or password" log entries are showing not the real client IP address, although the information is available.

Let me ask different:
Which IP address is shown in the log entry `/control/login: from ip x.x.x.x: invalid username or password`?
Is the `x.x.x.x` IP extracted from the `X-Real-IP`, `X-Forwarded-For` or `True-Client-IP` header? All those headers are set on the reverse proxy and are shown in the query logs and successful login log entry.

**Comment by TomTonic** [comment]
Btw.: The code uses remoteIP not realIP. See
https://github.com/AdguardTeam/AdGuardHome/blob/ae7bd79a6c2dba0061db4d5d46b9069e4bd3f22c/internal/home/auth.go#L446

**Comment by AndreyShpilevoy** [comment]
I have the same problem with Traefik.
On successful login, it shows the correct IP, and on invalid password it shows Proxy IP

**Comment by priyankub** [comment]
Facing this same issue. Thought I would comment to prevent the issue from being closed as stale. I cannot employ Crowdsec IPS if the IP with incorrect login cannot be reliably determined

**Comment by priyankub** [comment]
Looks like it is how the ```handleLogin``` function is handled. @schzhn - was that intentional to include remoteIP on failed login and realIP on valid login?
With the inclusion of trustedproxies, should it not be realIP in both cases?

**Comment by de-es** [comment]
Is this (still) working for everyone?

I have NGINX as reverse proxy on the same machine as AdGuard. Headers are set, `trusted_proxies` is set. Everything is working correctly for a long time. Except the IP for failed login attempts is still 127.0.0.1 like OP stated.

Already tried the different proxy headers to no avail.

AG v0.108.0-b.78
