### ISSUE TITLE
#5691 is happening again (Sites misclassified as adult)

### ISSUE THREAD

**Issue by sl33pyon3** [AdguardTeam/AdGuardHome#5830]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [x] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

64-bit ARM

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

0.107.29

### Description

AdGuard Home, installed on a Home Assistant via the Home Assistant add-on.

#### What did you do?

Open the desktop application Quicken Deluxe.

#### Expected result

I should have been prompted for my User Name and Password.

#### Actual result

I get "This site is blocked due to content filtering" from OpenDNS.

#### Screenshots (if applicable)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/38362903/81d4db2f-441b-4781-ac5e-6a9260885a9b)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/38362903/35ca690f-3212-4c97-ab44-696e75ff1e87)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/38362903/0a6ec597-cce3-4d88-b2cf-fd23fca304d7)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/38362903/cf029667-097b-4894-b0c8-4c8655644bb3)

#### Additional information

I know this initially looks like an OpenDNS issue but I have worked with OpenDNS Support and we ran numerous tests and have found that AdGuard Home is blocking portions of the web calls from Quicken Deluxe. One test we did was bypass AdGuard Home and pointed my DNS on my PC to OpenDNS servers directly and I was prompted to enter my credentials. Once I returned my PC DNS to point to AdGuard I am unable to download any of my financial information into Quicken Deluxe. 

I just looked in my AdGuard dashboard and noticed the increase in Blocked by Parental Control. Clicking on the quantity I see in the log that Adguard is blocking three of the URL's needed for Quicken Deluxe to contact the backend servers to allow access. I have updated the DNS blocklists but the sites are still being falsely blocked.

I searched the bug list here and I found Issue 5691 which seems simliar to the issue I am experiening. I am seeing more and more of this false positive in the past two months. I see from issue 5691 that there was an accidental merging of lists. I guess that is why I was having the same issues with ParamountPlus.com and not able to have episodes of shows track properly. I had to spend time debugging in my browser to figure out which URLs to whitelist to get it to work properly. I should have checked here first. 

Thank you for taking the time to read through this issue.

**Comment by Khaled0Ebrahim** [comment]
I don't recommend using adguard parental list
you can check the website here  https://reports.adguard.app
it will be classified as for adults you can send a report there or just use another list
personally I use OISD lists (https://oisd.nl/) and safe search by adguard
OISD BIG or SMALL list for ads based on what you like
and OISD NSFW for adult content
that is much more better than using adguard ad list and parental control

**Comment by sl33pyon3** [comment]
Hello,

Has anyone looked into this yet? I have stopped and started AdGuard Home. I have cleared the cache under DNS Settings. I have changed the Cache size to blank to disable caching, then I stopped and started AdGuard Home and ADGuard home is still blocking download.quicken.com, services.quicken.com and www.quicken.com.

Even though this site, which is run by AdGuard says they are safe
![image](https://github.com/AdguardTeam/AdGuardHome/assets/38362903/d4e94206-07f8-4cbc-99a2-b4086bfb093a)

In AdGuard Home it says otherwise
![image](https://github.com/AdguardTeam/AdGuardHome/assets/38362903/97874dfc-4a52-43f5-ac2e-4ad750b32cad)

Are there any other logs or information that you need to help troubleshoot this? I would be more than willing to help out. It is frustrating to have to keep changing my PC's DNS server setting every time I need to use Quicken Deluxe.

**Comment by Khaled0Ebrahim** [comment]
If you didn't notice the site is considered as an adult content by mistake and you are using adguard parental control
either you disable parental control and use another list to filter adult content or make a report in the site.
The place here is not related with what is being blocked and what is not the AGH is just using the service from the online web server. it is the main adguard web service who decides what to be blocked.

**Comment by Khaled0Ebrahim** [comment]
@sl33pyon3 send a report here
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/new/choose

**Comment by enakr** [comment]
The website has been removed from the Adult category, and will soon become accessible to AdGuard users. Thanks for bringing that to our attention, and sorry for any inconvenience caused !
