### ISSUE TITLE
Ability to setup separate certificates for DoH, DoT, DoQ

### ISSUE THREAD

**Issue by L11R** [AdguardTeam/AdGuardHome#5837]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Currently I know only one CA which issues SSL certificates for IPs, it's ZeroSSL. But in their free tier they issue one cert for the exactly one IP/domain, so I can't issue single certificate for both DoH and DoT.

#### Proposed solution
Add ability to choose separate certificates for DoH, DoT and probably DoQ. AFAIK it will allow to use DDR.

#### Alternatives considered
Buy ZeroSSL 50$ per month tier and create cert with IP, domain and wildcard domain to complete fulfill our needs with one certificate.

**Comment by fernvenue** [comment]
> But in their free tier they issue one cert for the exactly one IP/domain, so I can't issue single certificate for both DoH and DoT.

May I ask why you can't use single certificate for both DoH and Dot? They are just working on different ports.

**Comment by L11R** [comment]
> May I ask why you can't use single certificate for both DoH and Dot? They are just working on different ports.

By certificate for IP I mean something like https://1.1.1.1 where Cloudflare issued cert with SAN=IP:1.1.1.1

It allows to use DDR standard.

**Comment by ainar-g** [comment]
Merging into #741.
