### ISSUE TITLE
Service fails to install on windows 11

### ISSUE THREAD

**Issue by medtor** [AdguardTeam/AdGuardHome#5838]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.34

### Description

Hi, when I tried to install as a windows service I got this error :
2023/05/21 [14:07:05](https://www.youtube.com/watch?v=Uod2x3l6_XI&t=43200s) [info] AdGuard Home, version v0.108.0-b.34
2023/05/21 [14:07:05](https://www.youtube.com/watch?v=Uod2x3l6_XI&t=43200s) [info] service: control action: install
2023/05/21 [14:07:05](https://www.youtube.com/watch?v=Uod2x3l6_XI&t=43200s) [fatal] service: executing action "install": Failed to install AdGuard Home service: Access is denied.
any help plz!!

**Comment by fernvenue** [comment]
Have you tried to install as Administrator?

**Comment by CordoWEB** [comment]
You must use an account in Administors Group. Do you have UAC activated ?

**Comment by DandelionSprout** [comment]
I remember struggling substantially with the same problem, eventually landing on adding `C:\AdGuardHome\AdGuardHome.exe -s run` (Change the main filepath to wherever AGH is installed) manually to Windows Task Manager's Services list, which I was able to do with my main Windows account.

If I'm not wrong (I may very well be), manually creating a new service is done at Task Manager → Services → Run New Task → and then paste the above command. Nevertheless, the procedure is so complicated that I'll rank this as top priority.

**Comment by ainar-g** [comment]
@medtor, @DandelionSprout, please describe exactly what commands you were running.  If I recall correctly, AGH needs to be installed using the administrator account on Windows.

**Comment by DandelionSprout** [comment]
Seeing as I created my service 1½ years ago, that may be a bit tricky for me to remember, most sadly. 😅
