### ISSUE TITLE
DHCP server leases an IP that is already occupied

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#584]
### Steps to reproduce

1. Run AG Home with the built-in DHCP server
2. Connect to this network from the device 1 (it'll receive the first IP from the configured range)
3. Restart AG Home (the leases table will be cleared)
4. Connect to this network from the device 2

### Expected behavior
Device 2 receives the next IP from the configured range

### Actual behavior
The DHCP server is not aware of the current leases so it will return the same IP that was used for the device 1.

**Comment by szolin** [comment]
```
In some environments it will be necessary to reassign network
   addresses due to exhaustion of available addresses.
...
As a consistency check, the allocating
   server SHOULD probe the reused address before allocating the address,
   e.g., with an ICMP echo request, and the client SHOULD probe the
   newly received address, e.g., with ARP.
```
https://tools.ietf.org/html/rfc2131#section-2.2
