### ISSUE TITLE
AGH cached DNS entries have 200+ms elapsed response times

### ISSUE THREAD

**Issue by Dynamic5912** [AdguardTeam/AdGuardHome#5842]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.29

### Description

Cached responses served from AGH have elapsed response times of 200ms+. 

Some responses are even 500ms+.

Others are 1ms or less as expected to be.

Running on RPi4 with 8GB RAM.

**Comment by overwatch3560** [comment]
@Dynamic5912 is it still an issue with the most recent version ?

**Comment by Dynamic5912** [comment]
> @Dynamic5912 if you enable them, do you immediately see a latency of over 500ms again?
> 
> Does it happen when using one or the other, or both?

I'd have to clear the cache etc. in AGH and Unbound and test again which I don't particularly want to do.

**Comment by Dynamic5912** [comment]
Re-enabled this to test. 

Cached items are being returned with 200+ms response times.

Non-cached items are taking 300-400ms+ response times:

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/a8ce8e81-8dd0-4cbe-b6df-21e56170eb84)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/30e82a47-31a0-4f4d-9d3e-009ca1577030)
