### ISSUE TITLE
sudo: ./AdGuardHome: command not found

### ISSUE THREAD

**Issue by karipu** [AdguardTeam/AdGuardHome#585]
If I write in Terminal    sudo: ./AdGuardHome

I got this error message    : command not found

What might be wrong?

**Comment by ameshkov** [comment]
Well, you might be under root already, try running it without sudo

**Comment by karipu** [comment]
Does not work either:

iMac:~ karipu$ ./AdGuardHome
-bash: ./AdGuardHome: No such file or directory
iMac:~ karipu$

**Comment by ameshkov** [comment]
You're in the wrong directory, you need to be in the AdGuardHome directory.

Use `ls -la` command to see what's inside the current directory.
Use `cd ` command to switch to another directory (for instance, `cd AdGuard Home`).

**Comment by karipu** [comment]
Thank you, I found it.

**Comment by ameshkov** [comment]
Also, about sudo, you shouldn't use colon there, just `sudo ./AdGuardHome`
