### ISSUE TITLE
AdGuard Home/ Filter not working

### ISSUE THREAD

**Issue by b255ea006** [AdguardTeam/AdGuardHome#5854]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

Other (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.29

#### What did you do?
Normal installation via amtm / Putty interface, activated pre defined filterlists, run an adblock test page with low result

#### Expected result
100% result at adblock testpages and safety without browser addons, access to the internet for my android devices android TV, Tablets and Smartphone

no ads in windows 11 pro and edge browser start page

browsing without cookie notifications and "I don't care about cookies" browser addon

#### Actual result

lot´s of ads at the edge browser Start Page in windows 11 pro

33% adblock result at https://d3ward.github.io/toolz/adblock.html
Total : 147
49 blocked
98 not blocked

no connection to the internet with non of my android devices, only the Windows laptop can access the internet.

lots of ads and pop ups at https://canyoublockit.com/

error fixed  [error] handling tcp: reading msg: reading len: read tcp 192.168.50.1:53->192.168.50.245:31085: read: connection reset by peer

ads in windows 11 pro and edge browser Start Page 

lot´s of cookies and notifications and pop ups

#### Screenshots (if applicable)
![2023-05-29](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/5440fefb-e0a9-4674-b257-0c19ba4a7bcd)
![2023-05-29 (1)](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/be2b0160-f74f-4be4-8c70-0c456224ec01)
![2023-05-29 (2)](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/48282d76-952c-4eea-9ca1-daddd1e8fe25)
![2023-05-29 (3)](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/2c3f82d9-58e1-4ac9-b7c7-e2a907565a70)

**Comment by b255ea006** [comment]
The issue has changed. Now there is only one client visibel but why?

And the filters are still hockend but out of service aka not working.

![Screenshot (2)](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/68e46196-5599-4e7e-9c75-9b9678f7c601)

**Comment by b255ea006** [comment]
Update. I found https://adguard.com/de/test.html and read https://forum.adguard.com/index.php?threads/adguard-testing-site.1918/post-214236 with the following result!

![Screenshot 2023-06-14 182456](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/b1bddeb8-db16-45ea-bf0d-96f8192abd98)

It says that no AdGuard Service is running. But AdGuard Home says it´s active! Also there are Ads everywhere, and stuff i do not want. 



![Screenshot 2023-06-14 182512](https://github.com/AdguardTeam/AdGuardHome/assets/107177138/f335f794-efb0-4973-a33c-caf8ead3330c)


How is that possible? What am i doing wrong?
I also switched to AdGuard Home Version: v0.108.0-a.558+329e144b but it changed nothing.

Please help! 

@adguard @sophisticated-zero

**Comment by b255ea006** [comment]
@jumpsmm7 

How do i extract the files i do get with this command:

One can use this command to create a tar archive of these files:

_echo .config > exclude-files; tar -cvf AdGuardHome.tar -X exclude-files /opt/etc/AdGuardHome /opt/sbin/AdGuardHome /opt/etc/init.d/S99AdGuardHome /opt/etc/init.d/rc.func.AdGuardHome /jffs/addons/AdGuardHome.d /jffs/scripts/init-start /jffs/scripts/dnsmasq.postconf /jffs/scripts/services-stop /jffs/scripts/service-event-end; rm exclude-files_


The positive response was:

B255ea006@RT-AX86U_Pro/tmp/home/root# pidof AdGuardHome
21774
B255ea006@RT-AX86U_Pro:/tmp/home/root# /opt/etc/init.d/S99AdGuardHome check
 Checking AdGuardHome...              alive.
B255ea006@RT-AX86U_Pro:/tmp/home/root# echo .config > exclude-files; tar -cvf AdGuardHome.tar -X exclude-files /opt/etc/
AdGuardHome /opt/sbin/AdGuardHome /opt/etc/init.d/S99AdGuardHome /opt/etc/init.d/rc.func.AdGuardHome /jffs/addons/AdGuardHome
.d /jffs/scripts/init-start /jffs/scripts/dnsmasq.postconf /jffs/scripts/services-stop /jffs/scripts/service-event-end; rm ex
clude-files
tar: removing leading '/' from member names
opt/etc/AdGuardHome/
opt/etc/AdGuardHome/README.md
opt/etc/AdGuardHome/AdGuardHome
opt/etc/AdGuardHome/AdGuardHome.sig
opt/etc/AdGuardHome/LICENSE.txt
opt/etc/AdGuardHome/data/
opt/etc/AdGuardHome/data/filters/
opt/etc/AdGuardHome/data/filters/1685192724.txt
opt/etc/AdGuardHome/data/filters/1685192748.txt
opt/etc/AdGuardHome/data/filters/1685192718.txt
opt/etc/AdGuardHome/data/filters/1685192732.txt
opt/etc/AdGuardHome/data/filters/1685192744.txt
opt/etc/AdGuardHome/data/filters/2.txt
opt/etc/AdGuardHome/data/filters/1685352886.txt
opt/etc/AdGuardHome/data/filters/1686384197.txt
opt/etc/AdGuardHome/data/filters/1685192716.txt
opt/etc/AdGuardHome/data/filters/1685192723.txt
opt/etc/AdGuardHome/data/filters/1.txt
opt/etc/AdGuardHome/data/filters/1686384195.txt
opt/etc/AdGuardHome/data/filters/1685352883.txt
opt/etc/AdGuardHome/data/filters/1685192730.txt
opt/etc/AdGuardHome/data/filters/1685192717.txt
opt/etc/AdGuardHome/data/filters/1685352882.txt
opt/etc/AdGuardHome/data/filters/1685192738.txt
opt/etc/AdGuardHome/data/filters/1685192733.txt
opt/etc/AdGuardHome/data/filters/1686384202.txt
opt/etc/AdGuardHome/data/filters/1685352884.txt
opt/etc/AdGuardHome/data/filters/1686157951.txt
opt/etc/AdGuardHome/data/filters/1686384187.txt
opt/etc/AdGuardHome/data/filters/1685192746.txt
opt/etc/AdGuardHome/data/filters/1686384185.txt
opt/etc/AdGuardHome/data/filters/1685192729.txt
opt/etc/AdGuardHome/data/filters/1686384194.txt
opt/etc/AdGuardHome/data/filters/1685192722.txt
opt/etc/AdGuardHome/data/filters/1686157952.txt
opt/etc/AdGuardHome/data/filters/1685192747.txt
opt/etc/AdGuardHome/data/filters/1685192720.txt
opt/etc/AdGuardHome/data/filters/1686384186.txt
opt/etc/AdGuardHome/data/filters/1685192719.txt
opt/etc/AdGuardHome/data/filters/1685192721.txt
opt/etc/AdGuardHome/data/filters/1686384196.txt
opt/etc/AdGuardHome/data/filters/1686384201.txt
opt/etc/AdGuardHome/data/filters/1686384189.txt
opt/etc/AdGuardHome/data/filters/1685192750.txt
opt/etc/AdGuardHome/data/filters/1685192735.txt
opt/etc/AdGuardHome/data/filters/1685192731.txt
opt/etc/AdGuardHome/data/filters/1686384191.txt
opt/etc/AdGuardHome/data/filters/1685192742.txt
opt/etc/AdGuardHome/data/filters/1685192725.txt
opt/etc/AdGuardHome/data/filters/1686384193.txt
opt/etc/AdGuardHome/data/filters/1686384192.txt
opt/etc/AdGuardHome/data/filters/1685192740.txt
opt/etc/AdGuardHome/data/filters/1685192745.txt
opt/etc/AdGuardHome/data/filters/1686384190.txt
opt/etc/AdGuardHome/data/filters/1686384200.txt
opt/etc/AdGuardHome/data/filters/1685192749.txt
opt/etc/AdGuardHome/data/filters/1686384198.txt
opt/etc/AdGuardHome/data/filters/1685192737.txt
opt/etc/AdGuardHome/data/filters/1686384205.txt
opt/etc/AdGuardHome/data/filters/1685277445.txt
opt/etc/AdGuardHome/data/filters/1685192734.txt
opt/etc/AdGuardHome/data/filters/1686384199.txt
opt/etc/AdGuardHome/data/filters/1686384188.txt
opt/etc/AdGuardHome/data/filters/1686384203.txt
opt/etc/AdGuardHome/data/filters/1685192739.txt
opt/etc/AdGuardHome/data/filters/1685192727.txt
opt/etc/AdGuardHome/data/filters/1686157950.txt
opt/etc/AdGuardHome/data/filters/1686384204.txt
opt/etc/AdGuardHome/data/filters/1685352885.txt
opt/etc/AdGuardHome/data/filters/1685192741.txt
opt/etc/AdGuardHome/data/filters/1685192743.txt
opt/etc/AdGuardHome/data/filters/1685192728.txt
opt/etc/AdGuardHome/data/filters/1685192736.txt
opt/etc/AdGuardHome/data/filters/1685277444.txt.old
opt/etc/AdGuardHome/data/filters/1685192726.txt
opt/etc/AdGuardHome/data/sessions.db
opt/etc/AdGuardHome/data/stats.db
opt/etc/AdGuardHome/data/querylog.json
opt/etc/AdGuardHome/AdGuardHome.yaml
opt/etc/AdGuardHome/CHANGELOG.md
opt/etc/AdGuardHome/.AdGuardHome.yaml.ori
opt/etc/AdGuardHome/installer
opt/sbin/AdGuardHome
opt/etc/init.d/S99AdGuardHome
opt/etc/init.d/rc.func.AdGuardHome
jffs/addons/AdGuardHome.d/
jffs/addons/AdGuardHome.d/AdGuardHome.sh
jffs/addons/AdGuardHome.d/localtime
jffs/scripts/init-start
jffs/scripts/dnsmasq.postconf
jffs/scripts/services-stop
jffs/scripts/service-event-end
B255ea006@RT-AX86U_Pro:/tmp/home/root#


How do i extract those file for you to send them to you? @jumpsmm7

**Comment by jumpsmm7** [comment]
The effectiveness of AdGuardHome at blocking ads is not limited to adguardhome, but also the filters, dns servers, and allowlists you use. This is not something that can be troubleshooted. You have not adequately confirmed that every single item inside your filters is not being blocked. Please stop spamming.
