### ISSUE TITLE
Significant increase in response time when using Cloudflare with cache enabled

### ISSUE THREAD

**Issue by ADV-R** [AdguardTeam/AdGuardHome#5856]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Other (please mention in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.29

#### What did you do?

Used Cloudflare as an upstream with cache enabled

#### Expected result

Average processing time will become lower, not higher

#### Actual result

Average processing time is higher, not lower

#### Additional information

With the cache turned off Cloudflare responds steadily with a delay of 22-27 ms. But if you turn it on there are regular spikes of 50, 80 and even 300+ ms. However, responses from the cache itself take less than 1 ms.

Cache size, upstream type, amount of go routines, blocklists does not matter. The only way to get rid of spikes is to turn off cache completely.

I've tried it on two machines (Windows and OpenWRT), both AMD64. The weakest is i5 4670K with 8GB RAM so it is definitely not the lack of hardware performance.

Dnsproxy behaves the same way. CoreDNS and Blocky have no such problem and respond equally with or without cache enabled, no spikes.

**Comment by agneevX** [comment]
I'm unable to reproduce this.

**Comment by ppfeufer** [comment]
CPU and RAM don't matter that much for the cache. The cache is written to and read from the hard drive/SSD, and if that's a slow one or it's busy, it's going to take a moment to write/read the data.

**Comment by ADV-R** [comment]
Delayed responses always contain the original TTL.

Here's an example:

Cache enabled:

![cache](https://github.com/AdguardTeam/AdGuardHome/assets/63790295/edf92922-6f15-4802-a6fe-27b9ea876c81)

Cache disabled:

![nocache](https://github.com/AdguardTeam/AdGuardHome/assets/63790295/f1fb2717-675d-4ade-aee5-43ffbf7767ad)

A domain like www.google.com is definitely cached by Cloudflare all the time. Is there any chance that AGH with the cache enabled is requesting something extra from the upstream that leads to recursion instead of a response from the upstream's own cache?

With CoreDNS (cache enabled) in front of AGH (cache disabled) the problem disappears.

**Comment by agneevX** [comment]
Let me try reproducing this again in [dnsproxy](https://github.com/AdguardTeam/dnsproxy) with the help of [godnsbench](https://github.com/ameshkov/godnsbench).

```sh
 ~> docker run -d -p 1053:53/udp hezhijie0327/dnsproxy:latest \
--upstream=https://one.one.one.one/dns-query
2023/06/01 09:57:19 [info] Starting dnsproxy 0.49.1-ZHIJIE-936B4C7C
2023/06/01 09:57:19 [info] dnsproxy: starting dns proxy server
2023/06/01 09:57:19 [info] dnsproxy: cache: disabled
2023/06/01 09:57:19 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2023/06/01 09:57:19 [info] dnsproxy: listening to udp://[::]:53
2023/06/01 09:57:19 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2023/06/01 09:57:19 [info] dnsproxy: listening to tcp://[::]:53
2023/06/01 09:57:19 [info] dnsproxy: entering tcp listener loop on [::]:53
2023/06/01 09:57:19 [info] dnsproxy: entering udp listener loop on [::]:53

~> godnsbench -q {random}.example.net --count=100 --address=127.0.0.1:1053
2023/06/01 15:27:22 [info] Run godnsbench with the following configuration:
{
    "Address": "127.0.0.1:1053",
    "Connections": 1,
    "Query": "{random}.example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 100,
    "Verbose": false,
    "LogOutput": ""
}
2023/06/01 15:27:22 [info] Starting the test and running 1 connections in parallel
2023/06/01 15:27:52 [info] Processed 100 queries, errors: 0
2023/06/01 15:27:52 [info] Queries per second: 3.301484
2023/06/01 15:27:52 [info] Finished running all connections
2023/06/01 15:27:52 [info] The test has finished.
2023/06/01 15:27:52 [info] The test results are:
2023/06/01 15:27:52 [info] Elapsed: 30.290140631s
2023/06/01 15:27:52 [info] Average QPS: 3.301391
2023/06/01 15:27:52 [info] Processed queries: 100
2023/06/01 15:27:52 [info] Average per query: 302.90524ms
2023/06/01 15:27:52 [info] Errors count: 0
```

With cache enabled:

```sh
 ~> docker run -d -p 1053:53/udp hezhijie0327/dnsproxy:latest \
--upstream=https://one.one.one.one/dns-query \
--cache --cache-size=1000000
2023/06/01 09:55:08 [info] Starting dnsproxy 0.49.1-ZHIJIE-936B4C7C
2023/06/01 09:55:08 [info] dnsproxy: starting dns proxy server
2023/06/01 09:55:08 [info] dnsproxy: cache: enabled, size 1000000 b
2023/06/01 09:55:08 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2023/06/01 09:55:08 [info] dnsproxy: listening to udp://[::]:53
2023/06/01 09:55:08 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2023/06/01 09:55:08 [info] dnsproxy: listening to tcp://[::]:53
2023/06/01 09:55:08 [info] dnsproxy: entering udp listener loop on [::]:53
2023/06/01 09:55:08 [info] dnsproxy: entering tcp listener loop on [::]:53

~> godnsbench -q {random}.example.net --count=100 --address=127.0.0.1:1053
2023/06/01 15:25:13 [info] Run godnsbench with the following configuration:
{
    "Address": "127.0.0.1:1053",
    "Connections": 1,
    "Query": "{random}.example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 100,
    "Verbose": false,
    "LogOutput": ""
}
2023/06/01 15:25:13 [info] Starting the test and running 1 connections in parallel
2023/06/01 15:25:43 [info] Processed 100 queries, errors: 0
2023/06/01 15:25:43 [info] Queries per second: 3.384416
2023/06/01 15:25:43 [info] Finished running all connections
2023/06/01 15:25:43 [info] The test has finished.
2023/06/01 15:25:43 [info] The test results are:
2023/06/01 15:25:43 [info] Elapsed: 29.547805894s
2023/06/01 15:25:43 [info] Average QPS: 3.384329
2023/06/01 15:25:43 [info] Processed queries: 100
2023/06/01 15:25:43 [info] Average per query: 295.481577ms
2023/06/01 15:25:43 [info] Errors count: 0
```

**Comment by ADV-R** [comment]
With this tool, I can't reproduce it either. But the only thing it can do is to show how fast the upstream throws NXDOMAIN.

Cache enabled:

> godnsbench -q {random}.example.net --count=100 --address=10.1.1.3
2023/06/01 14:03:57 [info] Run godnsbench with the following configuration:
{
    "Address": "10.1.1.3",
    "Connections": 1,
    "Query": "{random}.example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 100,
    "Verbose": false,
    "LogOutput": ""
}
2023/06/01 14:03:57 [info] Starting the test and running 1 connections in parallel
2023/06/01 14:04:10 [info] Processed 100 queries, errors: 0
2023/06/01 14:04:10 [info] Queries per second: 7.547747
2023/06/01 14:04:10 [info] Finished running all connections
2023/06/01 14:04:10 [info] The test has finished.
2023/06/01 14:04:10 [info] The test results are:
2023/06/01 14:04:10 [info] Elapsed: 13.2496796s
2023/06/01 14:04:10 [info] Average QPS: 7.547312
2023/06/01 14:04:10 [info] Processed queries: 100
2023/06/01 14:04:10 [info] Average per query: 132.498462ms
2023/06/01 14:04:10 [info] Errors count: 0

Cache disabled:

> godnsbench -q {random}.example.net --count=100 --address=10.1.1.3
2023/06/01 14:05:22 [info] Run godnsbench with the following configuration:
{
    "Address": "10.1.1.3",
    "Connections": 1,
    "Query": "{random}.example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 100,
    "Verbose": false,
    "LogOutput": ""
}
2023/06/01 14:05:22 [info] Starting the test and running 1 connections in parallel
2023/06/01 14:05:35 [info] Processed 100 queries, errors: 0
2023/06/01 14:05:35 [info] Queries per second: 7.560466
2023/06/01 14:05:35 [info] Finished running all connections
2023/06/01 14:05:35 [info] The test has finished.
2023/06/01 14:05:35 [info] The test results are:
2023/06/01 14:05:35 [info] Elapsed: 13.2274068s
2023/06/01 14:05:35 [info] Average QPS: 7.559982
2023/06/01 14:05:35 [info] Processed queries: 100
2023/06/01 14:05:35 [info] Average per query: 132.277711ms
2023/06/01 14:05:35 [info] Errors count: 0

However, in real usage it looks like this:

Cache enabled:

![cache](https://github.com/AdguardTeam/AdGuardHome/assets/63790295/c61a65e2-cf8d-4501-8e51-c00fef81784f)

Cache disabled:

![nocache](https://github.com/AdguardTeam/AdGuardHome/assets/63790295/cf51e691-e9fb-4dae-84b2-c0e4572d77d6)

Waited more than an hour for the caching on the upstream caused by my own requests to go away.

And it is reproducible at any moment. Just turn on the cache and there it is. Turn it off and it's gone.

**Comment by ADV-R** [comment]
@jslawler-gh

Yeah. And I think I may have found the reason why it's happening.

You can reproduce exactly the same behavior without AGH with dig and DO flag. Like dig www.twitch.tv @1.1.1.1 will always return a response from the upstream cache. But dig www.twitch.tv @1.1.1.1 +do will return a response with the original TTL quite often. Which introduces this extra delay.

Only Cloudflare seems to be affected by this. Google always responds from the cache even if the DO flag is set.

**Comment by ADV-R** [comment]
The exact same problem was fixed in CoreDNS a few years ago: https://github.com/coredns/coredns/pull/5671
