### ISSUE TITLE
docker - AdGuardHome.yaml is not persistent

### ISSUE THREAD

**Issue by hexeth** [AdguardTeam/AdGuardHome#586]
Currently AdGuardHome.yaml appears to be stored in `/` instead of `/opt/adguardhome/conf` when running the docker. The current instructions in the readme claim the configuration files should be mapped to here, however this do not create any persistence. 

```
Configuration - /opt/adguardhome/conf
Filters and data - /opt/adguardhome/work
```

**Comment by ameshkov** [comment]
@hexeth the README is a bit inconsistent at the moment. It will be okay once we release v0.93 update.

**Comment by ezbiranik** [comment]
@hexeth to have persistent configuration and data you can use `adguard/adguardhome:edge` version of the image for now.

**Comment by ameshkov** [comment]
`latest` should be also okay now
