### ISSUE TITLE
CSS min-height issue

### ISSUE THREAD

**Issue by dontcrash** [AdguardTeam/AdGuardHome#5862]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.29

### Description

There is a large empty gap that forces browsers to render a scrollbar and put the footer too far below the dashboard div.

What it currently looks like:
![before](https://github.com/AdguardTeam/AdGuardHome/assets/32660358/74a1e869-c43d-4d9d-aa84-d4b69d443e7d)

Proposed:
![after](https://github.com/AdguardTeam/AdGuardHome/assets/32660358/380cd9f2-097d-486f-8233-bba0add28380)

The CSS code likely responsible:
~~~CSS
@media screen and (min-width: 992px)
.container--wrap {
    min-height: calc(100vh - 117px);
}
.container--wrap {
    min-height: calc(100vh - 160px);
}
~~~

**Comment by agneevX** [comment]
On what browser, do you see that? Unable to reproduce in Safari.

<img width="1145" alt="Screenshot" src="https://github.com/AdguardTeam/AdGuardHome/assets/19761269/79dc66ba-59c8-47c4-95af-d3a95bda523a">

**Comment by dontcrash** [comment]
> On what browser, do you see that? Unable to reproduce in Safari.
> 
> <img alt="Screenshot" width="1145" src="https://user-images.githubusercontent.com/19761269/244703205-79dc66ba-59c8-47c4-95af-d3a95bda523a.png">

Chrome on Windows.
