### ISSUE TITLE
Limit querylog.json size

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#5863]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
Trying to prevent flash wear on (cheap) routers, I put `querylog.json` in `/tmp` which is in-memory `tmpfs`. But now the query log can take up all the tmpfs space.

#### Proposed solution
Add an option to limit the size of `querylog.json`, including the rotated file `querylog.json.1`

#### Alternatives considered
- Do not log to file at all, but that doesn't seem ideal
- Reduce the log file rotation to a couple of days so that it keeps /tmp use low
- Manage the file with a script that pushes it to another device

#### Additional information
Flash wear is a concern on consumer grade routers

**Comment by EugeneOne1** [comment]
@timkgh, hello.  We're already have the similar feature request (#5346).  Please consider upvoting it.
