### ISSUE TITLE
108.b.35上游无法添加其他插件的端口地址

### ISSUE THREAD

**Issue by xilaochengv** [AdguardTeam/AdGuardHome#5875]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

64-bit ARM

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

108.b.35

### Description

更新最新版108.b35后，上游服务器添加127.0.0.1:1053或192.168.1.1:54都会显示无法连接！
b.34没有这个问题

**Comment by ainar-g** [comment]
Merging into #5873, as it is the most likely cause.
