### ISSUE TITLE
v0.107.30 require upstream DNS servers to support both TCP and UDP?

### ISSUE THREAD

**Issue by libuke** [AdguardTeam/AdGuardHome#5876]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.30 

### Description

My DNS server 127.0.0.1:1153 only supports UDP.
Upstream DNS servers: udp://127.0.0.1:1153
Test upstreams: Server "udp://127.0.0.1:1153": could not be used, please check that you've written it correctly

```sh
# AdguardHome Debug info:
2023/06/08 03:55:44.954242 6518#27 [debug] dnsforward: checking if upstream "udp://127.0.0.1:1153" works
2023/06/08 03:55:44.954322 6518#27 [debug] 127.0.0.1:1153: sending request A test.
2023/06/08 03:55:44.954378 6518#27 [debug] bootstrap: dialing 127.0.0.1:1153 (1/1)
2023/06/08 03:55:44.954506 6518#27 [debug] bootstrap: connection to 127.0.0.1:1153 succeeded in 89.999µs
2023/06/08 03:55:44.954948 6518#27 [debug] 127.0.0.1:1153: response: ok
2023/06/08 03:55:44.954985 6518#27 [debug] 127.0.0.1:1153: sending request A test.
2023/06/08 03:55:44.955010 6518#27 [debug] bootstrap: dialing 127.0.0.1:1153 (1/1)
2023/06/08 03:55:44.955220 6518#27 [debug] bootstrap: connection to 127.0.0.1:1153 failed in 165.932µs: dial tcp 127.0.0.1:1153: connect: connection refused
2023/06/08 03:55:44.955275 6518#27 [debug] 127.0.0.1:1153: response: dialing 127.0.0.1:1153 over tcp: all dialers failed: dial tcp 127.0.0.1:1153: connect: connection refused
```
```sh
~ % nslookup google.com              
Server: xxx
Address:	xxx
** server can't find google.com: SERVFAIL

With v0.107.29, the same configuration works fine.

## AdGuard Home v0.107.30 changelog
* Provided bootstrap servers are now used to resolve the hostnames of plain UDP/TCP upstream servers.
(Could it be due to this change?)

**Comment by ainar-g** [comment]
Thanks for the report.  Yes, this was an accidental change, and we're fixing it in #5873.  Merging into that one.
