### ISSUE TITLE
Version v0.107.31 still broke on RP4 

### ISSUE THREAD

**Issue by bones78** [AdguardTeam/AdGuardHome#5878]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.31

#### What did you do?
update to [v0.107.31](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.31). 
#### Expected result
working AdGuard Home
#### Actual result
complete broke. Website of adh down, connection refused
#### Additional information

AdGuardHome.service - AdGuard Home: Network-level blocker
     Loaded: loaded (/etc/systemd/system/AdGuardHome.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-06-08 20:50:41 CEST; 8s ago
    Process: 2739 ExecStartPre=/bin/mkdir -p /var/log/ (code=exited, status=0/SUCCESS)
    Process: 2740 ExecStart=/home/pi/AdGuardHome/AdGuardHome -s run (code=exited, status=2)
   Main PID: 2740 (code=exited, status=2)
        CPU: 8.355s

Raspberry Pi OS Bullseye 64 bit. If I go back to 107.29 everything is fine.

**Comment by wrcuz-github** [comment]
Same here, it's still broken

**Comment by fishscene** [comment]
I don't know what this is referencing, but here's what I discovered today:
DNS resolution 100% fails for AdGuard Home on both my rPi and docker instance. 
If I go to the dashboard and "Disable protection", DNS works perfectly. 

I suspected I might have a bad rule, so I disabled all the rules and re-enabled protection. DNS stopped working.
Basically, if protection is enabled, DNS stops working completely. I suppose I could consider myself 100% protected at this point, but It'd be nice to be able to browse some websites.

**Comment by wrcuz-github** [comment]
I've given up on AdGuard for now, I'm going back to PiHole. I will check @ least once a week for a fix though, I prefer AdGuard but it's unusable for me.

**Comment by bones78** [comment]
I have installed the beta version v0.108.0-b.36 (https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.108.0-b.36). Now agh works again.

**Comment by wulfy23** [comment]
fyi, also tested above (v0.108.0-b.36) on openwrt rpi4 just now and works fine

**Comment by ainar-g** [comment]
We cannot reproduce this on our machines.  Please provide the full failure logs ([verbose logs][1] would be even better) either by posting them here or by sending them to devteam@adguard.com, with the corresponding subject line.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by ainar-g** [comment]
We have just released v0.107.32, which should fix another reason for crashes.  Please check if the new version fixes those issues.

**Comment by bones78** [comment]
v0.107.32 fix the problem. Now everything is fine, thanks!

**Comment by peter1960** [comment]
This does not look to be fixed
https://github.com/hassio-addons/addon-adguard-home/issues/427
