### ISSUE TITLE
Wrong date/time in statistics

### ISSUE THREAD

**Issue by moyuanbo** [AdguardTeam/AdGuardHome#5880]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.31

### Description

![1686281627143](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/07bea360-0010-4dc8-bd4f-72b8dc92d335)
![1686281627147](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/430a4fdf-951e-4ff9-be17-51d94cfb795d)

**Comment by RoboMagus** [comment]
Please just keep issues in English... :slightly_frowning_face:
That way its:
1. Easier for you to get help
2. Easier for others to help you
3. Easier for people with similar issues to find this thread

Thats __Definately__ true for text in images that you do not translate for us!

**Comment by ainar-g** [comment]
@moyuanbo, please add a more thorough explanation of the issue, in any language you're comfortable with.  It's not clear what is wrong from the provided screenshot.

**Comment by stevenzhu25** [comment]
@moyuanbo 你可能需要检查一下你系统时间再说的… AdGuard Home的统计数据保留是自从AdGuard Home安装开始保留最后48小时（按你设置的数据周期） 的数据， 但是你截图里面显示的时间是2023年6月29号… 今天都没到6/29…

There's probably something wrong with your date & time setting since on the second screenshot the time is June 29th, 2023... that's still considered future when I'm generating this comment.

**Comment by moyuanbo** [comment]
@stevenzhu25 There is no problem with my system time. I use the zone time in the East Eighth Time Zone as the standard time. Is this related?
我的系统时间是没有问题的，我这边是按照东八时区的区时作为标准时间，会不会有这个有关？
![1687657528608](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/c2830702-8ccd-4547-a93b-46bb6ed6b0d5)

**Comment by stevenzhu25** [comment]
> @stevenzhu25 There is no problem with my system time. I use the zone time in the East Eighth Time Zone as the standard time. Is this related?
> 我的系统时间是没有问题的，我这边是按照东八时区的区时作为标准时间，会不会有这个有关？
> ![1687657528608](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/c2830702-8ccd-4547-a93b-46bb6ed6b0d5)
> 

没有

如果你现在看AdGuard Home面板， 显示的有从建立开始到现在的统计数据吗？

**Comment by moyuanbo** [comment]
No, the statistics are still very confusing!
不是，统计出来的还是很错乱！
![image](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/0741e3eb-5da3-4aac-9650-4aeda578843f)
![1687658220635](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/be10ab58-10ef-434b-ad53-fe03141b02f4)
![1687658210715](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/94b3f2c3-af39-4b9e-bfa5-8d931d6accc6)

**Comment by stevenzhu25** [comment]
I searched this repo to see if there's any similar issues, and noticed that someone mentioned this could be due to your local system (browser/PC)'s time is wrong... https://github.com/AdguardTeam/AdGuardHome/issues/4310#issuecomment-1045950593

Can you check if your system's date and time is correct (for whichever device you are using?)

(Not trying to endorse or suggest something) one convenient site I used is https://time.is

After that, I would strongly suggest you to "clear statistic" and let AdGuard Home redo the statistic retention. 

我搜了下看到另外一个issue上面写的这个时间可能是用你本地/浏览器报告的时间， 所以你本地系统的时间可能是混乱的。建议同时检查一下你本地系统的时间设置。 我一般用 time.is 查， 但是随便Google或者百度一下当前时间也行…

建议在校准时间后在AdGuard Home界面上清除统计数据，然后让AGH重新统计

**Comment by moyuanbo** [comment]
Thank you very much for providing me with the method, but I tried and found that the system time is consistent with my local time, but it is also the same problem!
多谢你为我提供的方法，但我试了一下，系统时间和我本地的时间是一致的，但也是一样的问题！

**Comment by stevenzhu25** [comment]
> Thank you very much for providing me with the method, but I tried and found that the system time is consistent with my local time, but it is also the same problem!
> 多谢你为我提供的方法，但我试了一下，系统时间和我本地的时间是一致的，但也是一样的问题！

Can you go to your query log and see if the latest queries are in sync with your system time? There's got to be something wrong in here or there lol

能否去AdGuard Home的日志里面看最新的记录的时间戳是不是正确的么？

**Comment by moyuanbo** [comment]
Hello, there is nothing unusual about the timestamp of the log
你好，日志的时间戳并没有什么异常的
![1687661782958](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/04ecc3cf-2535-429e-b2b0-e470993be297)
![1687661960454](https://github.com/AdguardTeam/AdGuardHome/assets/41987997/4bbc01e1-78e7-4f1c-b469-73987046a880)

**Comment by stevenzhu25** [comment]
okay... I have no idea why then.
Suggestion: Modify the title of this issue to say "Wrong date/time in statistics"
好吧我也不知道了……
小建议： 把标题改一下写成 统计信息内日期/时间错误

**Comment by larrvyll** [comment]
Please look at issue #5793 as it addresses the same problem.

**Comment by larrvyll** [comment]
just checked. problem solved. thank you

**Comment by ainar-g** [comment]
@moyuanbo, hello.  Do you see this issue in the latest release?

**Comment by ainar-g** [comment]
Good to hear!  We'll close the issue then.
