### ISSUE TITLE
v0.107.31 adguardhome exits for no reason after running as service on windows 10

### ISSUE THREAD

**Issue by DEiYdaIWVt** [AdguardTeam/AdGuardHome#5885]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

AMD64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.31

#### What did you do?
run adguardhome as a service on win10
#### Expected result
working normally
#### Actual result
the service always shutdown after a few minutes

**Comment by ainar-g** [comment]
Please make sure that your antivirus software isn't triggered erroneously.  See https://github.com/AdguardTeam/AdGuardHome/issues/5889#issuecomment-1588835211.
