### ISSUE TITLE
The application is difficult to scale (K8S, Docker Swarm, OSH etc.) (TBD)

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#5887]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

For example, I want to deploy a Kubernetes cluster with two nodes and eight replicas with any cloud provider. But the application is difficult to scale because it uses local files to store the database (logs etc.) and configuration. This causes external CSI and persistent volumes to be used. But sharing the query database and configuration file does not work well between replicas/pods🫣

#### Proposed solution

Use an external NoSQL database or otherwise change the algorithm for working with the database and configuration file. We also can consider to other ways🤔

#### Additional information

I can provide in pm my k8s manifest to deploy Kubernetes so you can play back the inconvenience I encountered trying to cluster the app😀

**Comment by ainar-g** [comment]
Merging into #573.
