### ISSUE TITLE
Add MIPS binary release

### ISSUE THREAD

**Issue by qokelate** [AdguardTeam/AdGuardHome#589]
#### I want run at openwrt, https://openwrt.org/

**Comment by ameshkov** [comment]
Hi, we haven't tested it on mips yet.

Can you check if it works if I build it for you?
Do you need mipsle or mips64le?

**Comment by qokelate** [comment]
#### Yet, i can test, but i don't know 32 or 64, it's `MT7620A` device, installed software binary file is: `ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, stripped`, so i think is `mipsle/mips32le`?
#### You can send for me `udf.q###qq.com`, i will test it.

**Comment by qokelate** [comment]
#### I installed `go1.11.2 darwin/amd64` and download with `go get github.com/AdguardTeam/AdGuardHome`, but take a error:

```
# github.com/AdguardTeam/AdGuardHome/dnsforward
AdguardTeam/AdGuardHome/dnsforward/dnsforward.go:94:46: cannot use "" (type string) as type []string in argument to upstream.AddressToUpstream
```

#### So, I replace all `upstream.AddressToUpstream(addr, "", DefaultTimeout)` to `upstream.AddressToUpstream(addr, []string{""}, DefaultTimeout)`, it works now!
#### Thanks Very Much!


#### BTW: My build command is `GOARCH=mipsle GOOS=linux GOMIPS=softfloat go build -ldflags "-s -w"`, it must set `GOMIPS=softfloat`, because openwrt default build settings is not enable FPU emulator, if missing, it will take ` illegal hardware instruction` Error!

**Comment by ameshkov** [comment]
Well, it seems as if you have go modules disabled.

You should `git clone` AdGuard to some place outside of your GOPATH and then run `make`

**Comment by ameshkov** [comment]
Check `release.sh` to see how we build platform-specific binaries, that will give you the idea on how to build it for MIPS.

**Comment by qokelate** [comment]
Okay, thanks!

**Comment by ameshkov** [comment]
Oh, please don't close it yet, I am interested in the result:)

If it works okay, we might add an official build as well. Just one important thing: MIPS is quite slow so I'd recommend changing upstream settings so that it used some regular plain DNS instead of the encrypted DNS-over-TLS that we have there by default.

**Comment by qokelate** [comment]
OKay, i will try before this, my solution is dnsmasq+dnscrypt-proxy, maybe i can remove some rules to save
I will report again after some days

**Comment by qokelate** [comment]
It's high cpu usage, so, i back to dnscrypt-proxy.

**Comment by qokelate** [comment]
Maybe released binary, let the user choose

**Comment by ameshkov** [comment]
> It's high cpu usage, so, i back to dnscrypt-proxy.

Have you changed the upstreams settings as I suggested here?
https://github.com/AdguardTeam/AdGuardHome/issues/589#issuecomment-465573282

You see, DNS-over-TLS would be extremely slow on MIPS CPUs, hence the high cpu usage.

**Comment by qokelate** [comment]
I will try tcp later, i cann't get the right dns with udp(DNS cache pollution).

**Comment by ameshkov** [comment]
Hi, here's a MIPS and MIPSLE binaries I've just built for you:

[AdGuardHome_v0.93-dirty_linux_mips.tar.gz](https://github.com/AdguardTeam/AdGuardHome/files/2909507/AdGuardHome_v0.93-dirty_linux_mips.tar.gz)
[AdGuardHome_v0.93-dirty_linux_mipsle.tar.gz](https://github.com/AdguardTeam/AdGuardHome/files/2909508/AdGuardHome_v0.93-dirty_linux_mipsle.tar.gz)

When you run it for the first time, it will use plain DNS by default when MIPS is detected.

**Comment by qokelate** [comment]
It looks not include FPU emulator, GOMIPS=softfloat

```
# mipsle
>./AdGuardHome -h
[1]    1737 illegal hardware instruction  ./AdGuardHome -h

# mips
>./AdGuardHome -h
zsh: exec format error: ./AdGuardHome

```

**Comment by qokelate** [comment]
I am running 0.92 and use DNS-over-HTTPS,

**Comment by ameshkov** [comment]
Could you please try this?

[AdGuardHome_v0.93-1-gbd31-dirty_linux_mipsle.tar.gz](https://github.com/AdguardTeam/AdGuardHome/files/2915667/AdGuardHome_v0.93-1-gbd31-dirty_linux_mipsle.tar.gz)

**Comment by qokelate** [comment]
It works. Thanks!

**Comment by qokelate** [comment]
2 features request(optional):
 1. add `--pidfile` argument(save self pid to file)
 2. add symbol link config support(if changed any settings on web, adguard will overwrite symbol link file)

**Comment by ameshkov** [comment]
@qokelate could you please create new issues for both feature requests?

**Comment by xman55555** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/releases 这个是界面么，没有程序，有木有编译好的？

**Comment by rufengsuixing** [comment]
> 
> 
> https://github.com/rufengsuixing/luci-app-adguardhome/releases 这个是界面么，没有程序，有木有编译好的？

界面可以自动下程序
