### ISSUE TITLE
AdGuard invalidated my password

### ISSUE THREAD

**Issue by blackeyeliner** [AdguardTeam/AdGuardHome#5894]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.31

#### What did you do?

1) Updated docker container to latest version. AdGuard started normally and performs normally, but

2) Attempted to access web UI with a password that has been set on initial installation

3) Discovered that password is no longer valid

4) Went into AdGuardHome.yaml and compared password hash to output of htpasswd with my previous known password. Discovered they were different

5) Changed password hash in AdGuardHome.yaml to output of htpasswd with my previous known password

6) Verified password is working in web UI now

#### Expected result

1) AdGuard would not change my password

#### Actual result

1) Password is invalid, even though no configuration changes were made (resolved, but did happen, and shouldn't have happened)

#### Additional information

UPDATE: Further investigation showed that password was changed in AdGuardHome.yaml long time ago (not on this contained update), and for a long time I was operating on previously authenticated sessions. 

Sessions stopped being authenticated because of contained update which is understandable. However, password used was definitely correct at the moment these sessions were initially set up.

Running AdGuardHome in a docker container on Synology DS218+
Linux synology 4.4.180+ #42962 SMP Sat Apr 8 00:14:26 CST 2023 x86_64 GNU/Linux synology_apollolake_218+

**Comment by martinspaniol** [comment]
I have the same problem. AGH is working fine and suddenly I cannot login due to invalid password.
