### ISSUE TITLE
Stops responding randomly

### ISSUE THREAD

**Issue by TheCableGuy99** [AdguardTeam/AdGuardHome#5898]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.31

### Description

I am running AdGuard Home on a "CentOS Linux release 7.9.2009 (Core) (x86_64)"

A couple of times now it has stopped responding to lookup requests. I can still access the web interface but it won't do any lookups.

I have tried to search for logs but cannot see where they are located. If you can advise where they should be I will check them but there's nothing I can see in "/var/log" or "/opt/AdGuardHome/" (installation path).

Restarting the service brings it back online so I doubt it's the O/S.

I have 2 servers setup, one on a Raspberry Pi with Ubuntu running the same AdGuard Home version but this doesn't appear to be affected.

Thanks.

**Comment by timkgh** [comment]
Seeing a similar behavior and reported it here: https://github.com/AdguardTeam/AdGuardHome/issues/5896
It seems to have started with .30 or .31, there is something going on.

**Comment by TheCableGuy99** [comment]
Am I right in thinking the latest update today resolves this? If so there's no need for me to proceed with the logging capture?

If not, I can still go ahead with it, please just confirm if I need to?

**Comment by timkgh** [comment]
> Am I right in thinking the latest update today resolves this?

The fix seems very specific to DNSCrypt which I'm not using.

**Comment by TheCableGuy99** [comment]
I'll enable logging then and wait for it to stop responding then. Might take a few days though. Cheers

**Comment by slyticoon** [comment]
I am experiencing the same issues. I have two instances of adguard home running, one is primary, one is backup. Primary resides on a home assistant server and is installed as an addon. The secondary is a docker deployment on unraid. Several days ago, the Primary stopped responding to DNS queries, so I restarted it. Once it came back, it was fine, but in just a few hours time it had done it again. I switched completely over to my Secondary and it has been working for a few days, but it just now went down. I have experienced this issue before, but it happened about every 6 months or so, and one restart fixed it. Now, running adguard requires restarts every few hours to work.

**Comment by TheCableGuy99** [comment]
It has to be a bug, I've enabled verbose logging so hopefully it won't be too long before it happens again. I also noted somewhere someone else said their CPU was running at 100% so i'll be checking that as well as soon as it happens again.

**Comment by timkgh** [comment]
What type of upstreams are you guys using? I use a plain UDP 53 upstream + 1.1.1.2 over http/3.

**Comment by jrust-ES** [comment]
Same problem here since v0.107.30. Interruptions come suddenly and completely irregularly. 
I have just rolled back to v0.107.29 to see if that solves the problem.

@timkgh 
In my case I use...
h3://dns.nextdns.io/dns-query
h3://cloudflare-dns.com/dns-query
h3://unfiltered.adguard-dns.com/dns-query

**Comment by TheCableGuy99** [comment]
> What type of upstreams are you guys using? I use a plain UDP 53 upstream + 1.1.1.2 over http/3.

Also using standard UDP:53 and my servers are:
https://dns.nextdns.io
https://dns.google/dns-query
https://dns.cloudflare.com/dns-query
https://unfiltered.adguard-dns.com/dns-query

But I'm 99.999999% sure this is not the issue.

**Comment by TheCableGuy99** [comment]
p.s. I still have mine switched to verbose logging and awaiting it to occur again so I will report back asap.

**Comment by TheCableGuy99** [comment]
Okay this has just happened again with version 107.32..

CPU Shows 100% for AdGuard while the issue is occuring see image:
![2](https://github.com/AdguardTeam/AdGuardHome/assets/39552752/a7f289cc-004d-44a2-b440-ec194bc38d4c)

I also have the time it stopped and logs but I don't want to publicly share the logs as they may contain sensitive data. Is there a way I share them with a representative of AdGuard only?

Thanks.

**Comment by jrust-ES** [comment]
There was an email address mentioned in another thread for that:
**devteam@adguard.com**

Thanks for your effort.

**Comment by TheCableGuy99** [comment]
Brilliant, I've emailed them with the logs and time.... thanks :)

**Comment by ainar-g** [comment]
@TheCableGuy99, thanks for the logs.  We have a few hypotheses, but nothing concrete at the moment.  A few things that could help us:

1.  You've mentioned that another AGH instance in your network is not affected.  Do these two differ in their settings, and in particular which filters they use, how often the filters are updated, and which upstream modes they use?

2.  If you switch the problematic AGH instance from Fastest IP mode to Load-balancing mode, does that improve the situation?

3.  If all else fails, could you send us the CPU profile taken when AGH gets stuck?  To do that, stop AGH, set `debug_pprof` in the configuration file to `true`, restart AGH, and get the profile from `http://127.0.0.1:6060/debug/pprof/goroutine?debug=1` (using e.g. `curl` or `wget`).

**Comment by TheCableGuy99** [comment]
yes I run 2 name servers....

The first is the one affected and is running on a Synology VM with CentOS 7.

The second is a Raspberry Pi 4B with 2GB RAM and on Ubuntu 22.04.1 and not affected.

Both are setup Identically and are using the following filters:
AdGuard DNS filter
AdGuard MobileFilter

The upstream servers are:
https://dns.nextdns.io
https://dns.google/dns-query
https://dns.cloudflare.com/dns-query
https://unfiltered.adguard-dns.com/dns-query

I have switched them both to "Load Balancing" now and will have to get back to you in a few days after seeing if it improves now. Although I do have my reservations this is the issue or it would be affecting the other server wouldn't it?

In regards to getting the CPU profile is this something you need me to set debug_pprof on now and then next time it locks up I should get the profile while still stuck? Or is it something you just want me to grab now as the data is always the same?

Thanks.

**Comment by ainar-g** [comment]
>  In regards to getting the CPU profile is this something you need me to set debug_pprof on now and then next time it locks up I should get the profile while still stuck? Or is it something you just want me to grab now as the data is always the same?

You need to enable it now and wait for the issue to occur before getting the profile.  The profile should tell us what's going on in the process at that exact moment, hopefully leading to some clues as to what could cause the 100 % CPU bug.  And please include the new verbose logs with the profile, so that we could compare the two logs and look for common features.

**Comment by TheCableGuy99** [comment]
Okay thanks, I've set both those options and restarted adguard again.

Will probably happen within 3 days (fingers crossed) and lets hope it reveals something.

I'll update the thread and forward the logs to the email as before when I have more info.

Thanks again.

**Comment by rcky711** [comment]
Thanks for your efforts all.
Also experiencing this issue after the upgrade as timkgh stated.

My setup is also a RaspberryPi Zero W that only has 512 MB ram I believe.  I hadn't experienced any issues running AdguardHome on this device for at least 6 months until the upgrade to .30 I believe.

I'll also try to capture some logs and profiles.  I'm new to linux, so will do my best.

Appreciate you all & the product!

**Comment by irrweg** [comment]
> Seeing a similar behavior and reported it here: #5896 It seems to have started with .30 or .31, there is something going on.

I have the same issues with my Raspberry Pi 4 4GB.
Stops responding to requests and I have to load the Pages multiple times to show up the website, the same with the other devices like Streaming Sticks and Smartphones.

Started with the Version .30, good thing on update the last version gets backup so I reverted back to .29

**Comment by pikachurus** [comment]
the same here.

collected debug logs sent to devteam@adguard.com

**Comment by TheCableGuy99** [comment]
> > Seeing a similar behavior and reported it here: #5896 It seems to have started with .30 or .31, there is something going on.
> 
> I have the same issues with my Raspberry Pi 4 4GB. Stops responding to requests and I have to load the Pages multiple times to show up the website, the same with the other devices like Streaming Sticks and Smartphones.
> 
> Started with the Version .30, good thing on update the last version gets backup so I reverted back to .29
> 
> Using features DoH, DoT, DoQ, DNSCrypt

What O/S are you using on your Pi? I'm wondering if it's the same or different to mine which I don't have an issue with?

**Comment by blong112** [comment]
I have 4 instances of Adguard home running and I too face sudden spikes in CPU usage in almost all of them.
It would run normally and have these sudden CPU spikes. And after that, it would no longer resolve any DNS queries however the web interface would be still be working. The CPU spike will remain. A restart of the server would then be needed to enable DNS queries again.

All 4 instances are using very low end VPS (1GB RAM & 1vCPU) on different hosting providers - Vultr, GreenVPS and Hostinger. However I never had any performance issues until this sudden spike. And it seems that Adguard uses very little resources 'normally'.

They are all running the latest version of Adguard home - at the moment v0.107.32. It happened to the previous versions as well. I am rather quick when it comes to updating my Adguard instances. They are all on Ubuntu as well.

I will try reducing my blocklists and get back on the performance.

**Comment by irrweg** [comment]
> > > Seeing a similar behavior and reported it here: #5896 It seems to have started with .30 or .31, there is something going on.
> > 
> > I have the same issues with my Raspberry Pi 4 4GB. Stops responding to requests and I have to load the Pages multiple times to show up the website, the same with the other devices like Streaming Sticks and Smartphones.
> > 
> > Started with the Version .30, good thing on update the last version gets backup so I reverted back to .29
> > 
> > Using features DoH, DoT, DoQ, DNSCrypt
> 
> What O/S are you using on your Pi? I'm wondering if it's the same or different to mine which I don't have an issue with?

Using Raspbian (Raspberry Pi OS) not sure about the version, gonna check it when home.

**Comment by TheWoodsy** [comment]
Same issue.
AGH on Ubuntu 22.04 snap v0.107.32
Pegged a core at 100%
Nothing in logs around time of death in syslog/journal/AdGuardHome.err
WebUI works, DNS doesn't.
Yikes...

**Comment by TheCableGuy99** [comment]
Just to confirm this I'm still logging. This is the longest it's gone for me personally without having the issue (since the problem started). I'll update ASAP.

**Comment by dioey** [comment]
same issue using  ARMBIAN 5.88, Ubuntu 18.04.6 LTS 5.1.0-aml-s905, but after change the buffer size to 4 MB it stop hang using 100% CPU maybe same problem with #5903

**Comment by ricardonadao** [comment]
I am having a similar problem too, running 3 instances in debian vms and being load balanced with a health monitor querying "www.google.com" every 10secs with a timeout of 5sec, and if I run anything above v0.108.0-b.30 (or the stable equivalent) I get one, or several of them failing the health checks in a span of 10/15m, once rolled back to .30, no more issues.

I tried the Beta and Stable branch and both manifest similar issues once I upgrade from .30 (or equivalent)

**Comment by TheCableGuy99** [comment]
@ainar-g This has finally happened again and so I have forwarded the new verbose logs and the requested goroutine debug log to: devteam@adguard.com

I hope this finally sheds some light on the issue.

Thanks.

**Comment by TheCableGuy99** [comment]
Sorry I forgot to mention that this happened at 20:05 (approx) so that should help you a little.

**Comment by ainar-g** [comment]
@TheCableGuy99, thanks for the logs!  The logs seem to show a pattern similar to the one we've fixed in https://github.com/AdguardTeam/AdGuardHome/issues/5896#issuecomment-1620283087.  Could you please install one of the latest Edge releases and see if that fixes the issue for you as well?

**Comment by TheCableGuy99** [comment]
@ainar-g okay I'm not familiar with these 'edge' releases... are they simply pre-releases?

If so, how do I upgrade to one of these versions?

Thanks.

**Comment by Freebase394** [comment]
Nice work guys. Nice to see some and good improvements on the code

**Comment by ainar-g** [comment]
@TheCableGuy99, yes, they are essentially daily builds.  See the [*Platforms* Wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms#releases) for links and go through the same procedure as for [manual update as described in the *FAQ* Wiki page](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update-unix).  It is important to backup your configuration file and the `data/` directory.

**Comment by Freebase394** [comment]
How can I install the beta version ?

**Comment by Freebase394** [comment]
Hi there! 
I'm testing beta version! ...
And is working very well so far... 
 [have posted here my feedback](https://github.com/AdguardTeam/AdGuardHome/issues/5964#issuecomment-1632966963)

**Comment by Pofilo** [comment]
I still have an issue with "0.107.34" (also had it with "0.108.0-b.34" and "0.108.0-b.38").

I don't have 100% CPU usage (never when it is stuck).
I used to use the disable for 10 minutes button.
I have the feeling that I experience this issue always after using this feature.
The DNS requests never responds, the UI (while connected) does not respond (but the connection page does).

I don't know if someone also experiences softlocks while using this feature (I may create a dedicated issue if needed).

**Comment by irrweg** [comment]
Version .34 fixed it for me on my Raspberry running Bullseye.

**Comment by Freebase394** [comment]
For me too. Fixed on "AdGuard Home, version v0.108.0-b.41"

**Comment by redbaron-gt** [comment]
Fixed for me, on version: v0.108.0-a.604+7b92d53b now
