### ISSUE TITLE
No Dashboard available after new installation

### ISSUE THREAD

**Issue by XavPi** [AdguardTeam/AdGuardHome#5904]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

Other (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

AdGuard Home v0.107.32

#### What did you do?
I installed AdGuard Home on a newly installed Pi OS (latest version - installed on 2023-06-13) on a Raspberry Pi 3 Model B Plus Rev 1.3.
Tested AdGuardHome is running using :  "systemctl status AdGuardHome"
● AdGuardHome.service - AdGuard Home: Network-level blocker
     Loaded: loaded (/etc/systemd/system/AdGuardHome.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-06-14 11:04:04 CEST; 52min ago
    Process: 354 ExecStartPre=/bin/mkdir -p /var/log/ (code=exited, status=0/SUCCESS)
   Main PID: 431 (AdGuardHome)
      Tasks: 7 (limit: 1595)
        CPU: 146ms
     CGroup: /system.slice/AdGuardHome.service
             └─431 /opt/AdGuardHome/AdGuardHome -s run

Jun 14 11:04:04 Adguard systemd[1]: Starting AdGuard Home: Network-level blocker...
Jun 14 11:04:04 Adguard systemd[1]: Started AdGuard Home: Network-level blocker.

#### Expected result
Dashboard available at my Pi IP address xxx.xxx.xxx.xxx:80

#### Actual result
No Dashboard responding at my Pi IP address xxx.xxx.xxx.xxx:80
No service listening on port 80 : it seems webserver is not active on my Adguard Home instance.

#### Additional information
> sudo netstat -at
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 localhost:ipp           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
tcp        0    192 RaspberryPi.lan:ssh     DESKTOP-LD4HNNH.l:64906 ESTABLISHED
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
tcp6       0      0 localhost:ipp           [::]:*                  LISTEN
tcp6       0      0 [::]:3000               [::]:*                  LISTEN

> ss -tulnp
Netid     State      Recv-Q     Send-Q         Local Address:Port          Peer Address:Port    Process
udp       UNCONN     0          0                    0.0.0.0:68                 0.0.0.0:*
udp       UNCONN     0          0                    0.0.0.0:631                0.0.0.0:*
udp       UNCONN     0          0                    0.0.0.0:5353               0.0.0.0:*
udp       UNCONN     0          0                    0.0.0.0:44279              0.0.0.0:*
udp       UNCONN     0          0                          *:546                      *:*
udp       UNCONN     0          0                          *:55383                    *:*
udp       UNCONN     0          0                          *:5353                     *:*
tcp       LISTEN     0          128                127.0.0.1:631                0.0.0.0:*
tcp       LISTEN     0          128                  0.0.0.0:22                 0.0.0.0:*
tcp       LISTEN     0          128                     [::]:22                    [::]:*
tcp       LISTEN     0          128                    [::1]:631                   [::]:*
tcp       LISTEN     0          4096                       *:3000                     *:*

**Comment by ainar-g** [comment]
[As documented](https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#first-start), AdGuard Home's initial setup is done on port 3000.  The `netstat`/`ss` and outputs both show that something is listening on that port.

**Comment by XavPi** [comment]
Oops, I missed the starting http port... :fearful: 
Everything is OK now. :+1: 
Thanks for your quick answer.
Regards

**Comment by XavPi** [comment]
Oops, I missed the starting http port... :fearful: 
Everything is OK now. :+1: 
Thanks for your quick answer.
Regards
