### ISSUE TITLE
Ningx as Proxy, need help

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#591]
dobri dem

hi there

as some of you know, im running ibksturm.synology.me (dnscrypt, DoH, DoT)

today i updated Backend AGH by source, works fine
(on Linux, amd64 you need to modify Makefile by following code
`npm --prefix client install --no-optional -f`
)

now i try to query DoT and DoH in this kind

Router (853) -> Ningx Stream (DoT) -> AGH -> Unbound = Running
Router (443) -> nginx stream (DNSCRYPT) > DNSCRYPT-Wrapper -> AGH -> Unbound = Running
Router (443 & /dns-query) -> nginx stream (DoH) > AGH -> Unbound = Running Not

the old way (and currently use)
Router (443 & /dns-query) -> nginx HTTPS (DoH) -> doh-httpproxy -> AGH -> Unbound = Running

does some Body here's got a solution or idear how i could modify nginx conf?

i use nginx still as a loadbalancer and as a proxy  to masquerading external ip addresses and sources. 

sbazibo

**Comment by ameshkov** [comment]
> Router (443) -> nginx stream (DNSCRYPT) > DNSCRYPT-Wrapper -> AGH -> Unbound = Running
> Router (443 & /dns-query) -> nginx stream (DoH) > AGH -> Unbound = Running Not

Well, I need to take a look at the nginx configuration file to figure what's wrong here.

**Comment by ibksturm** [comment]
config as running now:
(/etc/nginx/conf.d/doh.conf)
```
#### doh ######

#limit_req_zone $binary_remote_addr zone=mylimit:50m rate=200r/s;

server{
    listen 192.168.0.191:8443 ssl http2 reuseport; # managed by Certbot

    ssl_certificate           /etc/dyncert.d/fullchain.pem;
    ssl_certificate_key       /etc/dyncert.d/privkey.pem;
    ssl_protocols              TLSv1.2 TLSv1.3;
    ssl_dhparam               /etc/dyncert.d/dh2048.pem;
  #     ssl_session_timeout 2m;

        if ( $request_method !~ ^(GET|POST|HEAD)$ ) {
        return 501;
        }

      location /dns-query {
              proxy_set_header Host $http_host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_redirect off;
              proxy_buffering off;
              proxy_pass http://dohproxy_backend;
        }

}

upstream dohproxy_backend {
        server [::1]:8540;
        server [::1]:8541;
        server [::1]:8542;
}
```

(/etc/nginx/stream/stream.conf)
```

### dnscrypt
stream {
        server {
            listen 8443 udp  reuseport;
            proxy_pass dnscrypt-backends;
            proxy_buffer_size 8k;
            proxy_connect_timeout 240s;
            proxy_timeout 60s;
          }

#       server {
#               listen 8543 ssl;
#               proxy_pass dns_tcp_servers;
#          ssl_certificate       /etc/dyncert.d/fullchain.pem;
#          ssl_certificate_key   /etc/dyncert.d/privkey.pem;
#          ssl_protocols         TLSv1.2 TLSv1.3;
#          ssl_ciphers           ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
#          ssl_session_tickets on;
#          ssl_session_timeout   4h;
#          ssl_handshake_timeout 20s;
#       }

        upstream dnscrypt-backends {
            server 127.0.5.1:8441;
            server 127.0.5.1:8442;
            server 127.0.5.1:8440;
        }



#       upstream dns_tcp_servers {
#       server 127.0.1.1:54;
#       server 127.0.0.1:853;
#        }

}
```
thats the configuration it's running 
nginx makes a splitt
8443 -> dnscrypt
8443 & /dns-query -> doh
dot -> directly AGH

this day, i'll try follow things to running directly doh on AGH. all without success

1. change backend server in doh.conf to 127.0.0.1:443 (directly to AGH and yeah, Crypto with certs is activated
2. Try to configure only stream proxy to AGH (similar to TLS -> outcommented)
  problem is, that in the stream-modules you can't handle /dns-query or other urls (or maybe i don't know how)

3. Try to reconfigure doh.conf without the ssl configuration stuff

sadly i'm not deep as i wish in nginx to solve this question

**Comment by ameshkov** [comment]
I am not an expert as well, but let's wait for @ezbiranik, maybe he can help

**Comment by ibksturm** [comment]
dobri!

what work is nginx -> dnscrypt on port 8443 (proxing udp > loadbalancing dnscrypt-wrapper)
DOH on Port 8443 -> directly to AGH

but with this solution i havn't got 
- load balancing
- external ip's are logged

but performance would rice up

**Comment by ameshkov** [comment]
What do you have on `dohproxy_backend`? Is it some DOH proxy?

**Comment by ibksturm** [comment]
> What do you have on `dohproxy_backend`? Is it some DOH proxy?

i used at the moment this

https://github.com/facebookexperimental/doh-proxy#doh-httpproxy

but i would to change do AGH

**Comment by ameshkov** [comment]
> Update, now i use for experimental

Well, frankly, I'd suggest using [dnsproxy](https://github.com/AdguardTeam/dnsproxy). At least you can enable logging there and see what requests are coming in.

Or simply use AGH directly:).

**Comment by ibksturm** [comment]
solved :)

use your https://github.com/AdguardTeam/dnsproxy/


nginx:

```
### dnscrypt
stream {
        server {
            listen 8443 udp  reuseport;
            proxy_pass dnscrypt-backends;
            proxy_buffer_size 8k;
            proxy_connect_timeout 240s;
            proxy_timeout 60s;
          }
        upstream dnscrypt-backends {
            server 127.0.5.1:8441;
            server 127.0.5.1:8442;
            server 127.0.5.1:8440;
        }



##### dns over tls

        server {
                listen 8543;
                proxy_pass dns_tcp_servers;
       }


        upstream dns_tcp_servers {
        server 127.0.0.2:8530;
        server 127.0.0.2:8531;
        server 127.0.0.2:8532;
        }


##### dns over https

        server {
                listen 8443;
                proxy_pass dns_dot_servers;
       }


        upstream dns_dot_servers {
        server 127.0.0.2:8540;
        server 127.0.0.2:8541;
        server 127.0.0.2:8542;
        }

}
```
systemd service /etc/systemd/system/httpproxy-8540.service (And -8541, -8542)

```
[Unit]
Description=DOH HTTP Proxy on %I
After=syslog.target network.target
Before=nginx.target

[Service]
Type=simple
AmbientCapabilities=CAP_NET_BIND_SERVICE


#ExecStart=/etc/dnscrypt-wrapper/doh-proxy --listen-address 127.0.5.2:8540 --server-address 192.168.0.191:53 --timeout 10
#ExecStart=/etc/dnscrypt-wrapper/doh-httpproxy --upstream-resolver ::1 --listen-address=::1 --port 8540
#ExecStart=/usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server-8540.conf

ExecStart=/etc/dnsproxy/dnsproxy --listen=127.0.0.2 --port 53000 \
                --https-port=8540 --tls-port=8530\
                --bootstrap=9.9.9.9 --upstream=127.0.0.1:53 \
                --tls-crt=/etc/dyncert.d/fullchain.pem --tls-key=/etc/dyncert.d/privkey.pem \
                --refuse-any



LimitNOFILE=1000000
LimitFSIZE=infinity
LimitCPU=infinity
LimitAS=infinity
LimitNPROC=495000

Restart=allways

[Install]
WantedBy=multi-user.target

```

**Comment by ameshkov** [comment]
Great:)
