### ISSUE TITLE
SERVFAIL is cached

### ISSUE THREAD

**Issue by gshpychka** [AdguardTeam/AdGuardHome#5924]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.29

### Action

Query an address that causes a SERVFAIL multiple times:

```sh
dig sigfail.verteiltesysteme.net
```

### Expected result

The request is not cached and forwarded to upstream for every request 

### Actual result

SERVFAIL is cached, subsequent results are returned from AGH cache as specified by the query log

### Additional information and/or screenshots

<img width="382" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/23005347/4cef88d3-e210-440c-81d3-678bae7fd8d6">

A comment [here](https://github.com/AdguardTeam/AdGuardHome/issues/4373#issuecomment-1063216344) suggests that AGH does not cache SERVFAIL, but that's not what I'm observing

**Comment by ainar-g** [comment]
The comment is rather incorrect, as AdGuard Home does cache SERVFAIL results, but only to a maximum of 30 seconds.

See https://datatracker.ietf.org/doc/html/rfc2308#section-7.1:

 >  ```none
 >     In either case a resolver MAY cache a server failure response.  If it
 >     does so it MUST NOT cache it for longer than five (5) minutes, and it
 >     MUST be cached against the specific query tuple <query name, type,
 >     class, server IP address>.
 >  ```

**Comment by gshpychka** [comment]
@ainar-g thanks. When it returns a SERVFAIL, does this mean that AdGuard checked all upstreams and all of them returned a SERVFAIL?

**Comment by ainar-g** [comment]
That depends on your upstream mode.  See *Settings → DNS settings.*

**Comment by candybars2021** [comment]
I just saw this post, and can say that even in parallel query mode, server fail will be served first and cached! There should be a way to define it differently - btw with regular expressions can you rewrite this to be considered failure? and on another note and bug reported - can it be used to override TTL? just checking :)

**Comment by swissbyte** [comment]
I have the same problem. Would be great that it a SERVFAIL happens, the next upstream DNS would be queried.

**Comment by Sakura-Luna** [comment]
@ainar-g I think there should be an option to **not cache SERVFAIL responses**, because the problem that causes it is quite complex.

**Comment by yyysuo** [comment]
I would like to cache all the SERVFAIL responses, and when AdGuard Home is shut down, I want the cached results to be preserved so that they can be loaded again when it restarts.

**Comment by yurividal** [comment]
> I just saw this post, and can say that even in parallel query mode, server fail will be served first and cached! There should be a way to define it differently - btw with regular expressions can you rewrite this to be considered failure? and on another note and bug reported - can it be used to override TTL? just checking :)

Had the same issue today. Seems like SERFAIL responses are not considered failed by AGH, which obviiusly causes issues

**Comment by kmahyyg** [comment]
@ainar-g please correct me if I was wrong. query log is attached for your reference. From what I observed today, it's cached more than 30 seconds.

[querylog.json](https://github.com/user-attachments/files/17320981/querylog.json)
