### ISSUE TITLE
Allow pre-resolved DNS hostname IP to bypass bootstrap_dns.

### ISSUE THREAD

**Issue by 57382** [AdguardTeam/AdGuardHome#5926]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

bootstrap_dns has many disadvantages, for example I want to use DOH only.
In this case a pre-resolved DOH IP is required. Use DOH domain names with pre-resolved IPs.
Some open source resolvers allow this, one example is SmartDNS.

I noticed that bootstrap_dns cannot be disabled, if I delete all DNS it will revert to default configured DNS.
For this I had to configure a DNS of 0.0.0.0 to disable bootstrap_dns. Oh My God.

Please allow me to specify IP for DOH.

one example:
https://freedom.mydns.network/dns-query [2606:4700:3037::ac43:cfde] This can be IPv6 or IPv4.

As well as allowing to disable bootstrap_dns.

### Proposed solution

https://freedom.mydns.network/dns-query [2606:4700:3037::ac43:cfde]

### Alternatives considered and additional information

hosts?

**Comment by ainar-g** [comment]
I think we should be able to do that through `/etc/hosts` once #5902 is fixed, so I'll merge it there, if you don't mind.

**Comment by ainar-g** [comment]
@ainar-g, please fill a new feature request for that, describing the problem that it solves, so that it doesn't get lost.
