### ISSUE TITLE
Provide binaries for Windows x86

### ISSUE THREAD

**Issue by MS-PC** [AdguardTeam/AdGuardHome#593]
Thanks for the great work you did with AdGuard Home, you could provide the binaries for Windows x86 - 32-bit, since for almost all systems its x86 version is provided, and it would be very helpful for some people who want to implement it in a Windows x86.

It's just a suggestion/request, it's up to you.

**Comment by ameshkov** [comment]
@MS-PC do you have access to an x86 Windows PC?

I can build it for you, but I need you to perform some quick test to see if it works okay.

**Comment by MS-PC** [comment]
If I have a small Notebook to do the test, only the test would do it on Thursday or Friday.
It would be great if you would give me the build for Windows x86 :+1:.

**Comment by ameshkov** [comment]
Here is the Win x86 binary:
[AdGuardHome_v0.93-dirty_Windows_386.zip](https://github.com/AdguardTeam/AdGuardHome/files/2909504/AdGuardHome_v0.93-dirty_Windows_386.zip)

**Comment by MS-PC** [comment]
@ameshkov 
It works fine!, but apparently the pre-established DNS servers did not work (Cloudflare), but when removing the letters and only leaving the numbers to solve it, it is worth noting that it does not configure any of the features that Adguard Home has.

Finally I could not register the AdGuardHome.exe service according to the Wiki.

**Comment by ameshkov** [comment]
@MS-PC huh, you had some issues according to the email notification with the original comment text.

Have you been able to solve them all?

**Comment by MS-PC** [comment]
@ameshkov
I do not know if I consider them issues, in case it is helpful I will describe them:

1. I had a issue when working with the DNS server, specifically with the pre-defined DNS (Cloudflare), and the only way it worked was to remove (tls://) and just leave the "numbers".
2. I could not register the AdGuardHome.exe service according to the Wiki.

**Comment by ameshkov** [comment]
> 1. I had a issue when working with the DNS server, specifically with the pre-defined DNS

Most likely this is #500 

> 2. I could not register the AdGuardHome.exe service according to the Wiki.

What went wrong?

**Comment by MS-PC** [comment]
>What went wrong?

Sorry for any inconvenience, I tried again to register the service and this time I could, it was my mistake.

**Comment by ameshkov** [comment]
Great, thank you! We'll include x86 binaries in the next release then.

**Comment by ameshkov** [comment]
Done
