### ISSUE TITLE
Adguard no respond DNS request after certain Time - Docker Contener become Unealthy

### ISSUE THREAD

**Issue by bartounet16** [AdguardTeam/AdGuardHome#5933]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.32

### Action

:~$ nslookup -debug -type=a 'www.free.fr' '10.0.0.250'
;; connection timed out; no servers could be reached

### Expected result

Container runs normally

### Actual result

nslookup failed for 0.0.0.0:53 after certain time 
Contener becom Unealthy

### Additional information and/or screenshots

023/06/23 19:10:29.288547 [info] AdGuard Home, version v0.107.32

2023/06/23 19:10:29.288580 [info] AdGuard Home updates are disabled

2023/06/23 19:10:29.289872 [info] tls: using default ciphers

2023/06/23 19:10:29.292120 [info] safesearch default: reset 253 rules

2023/06/23 19:10:29.341228 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db

2023/06/23 19:10:29.341298 [info] auth: initialized.  users:1  sessions:3

2023/06/23 19:10:29.341309 [info] web: initializing

2023/06/23 19:10:29.359633 [info] dnsproxy: cache: enabled, size 4096 b

2023/06/23 19:10:29.359645 [info] dnsproxy: max goroutines is set to 300

2023/06/23 19:10:29.359769 [info] AdGuard Home is available at the following addresses:

2023/06/23 19:10:29.359860 [info] go to http://127.0.0.1:80

2023/06/23 19:10:29.359866 [info] go to http://172.24.0.2:80

2023/06/23 19:10:29.506545 [info] dnsproxy: starting dns proxy server

2023/06/23 19:10:29.506561 [info] Ratelimit is enabled and set to 20 rps

2023/06/23 19:10:29.506564 [info] The server is configured to refuse ANY requests

2023/06/23 19:10:29.506567 [info] dnsproxy: cache: enabled, size 4194304 b

2023/06/23 19:10:29.506571 [info] dnsproxy: max goroutines is set to 300

2023/06/23 19:10:29.506589 [info] dnsproxy: creating udp server socket 0.0.0.0:53

2023/06/23 19:10:29.506663 [info] dnsproxy: listening to udp://[::]:53

2023/06/23 19:10:29.506672 [info] dnsproxy: creating tcp server socket 0.0.0.0:53

2023/06/23 19:10:29.506695 [info] dnsproxy: listening to tcp://[::]:53

2023/06/23 19:10:29.507321 [info] dnsproxy: entering udp listener loop on [::]:53

2023/06/23 19:10:29.507373 [info] dnsproxy: entering tcp listener loop on [::]:53

2023/06/24 19:10:29.758499 [info] saving contents of filter #1 into /opt/adguardhome/work/data/filters/1.txt

2023/06/24 19:10:29.758721 [info] updated filter 1: 1072167 bytes, 54152 rules

2023/06/24 19:10:30.965258 [info] got status code 403 from https://curben.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt, skip

2023/06/24 19:10:30.965377 [info] Failed to update filter https://curben.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt: got status code 403, want 200

2023/06/24 19:10:31.352596 [info] saving contents of filter #1665227529 into /opt/adguardhome/work/data/filters/1665227529.txt

2023/06/24 19:10:31.372661 [info] updated filter 1665227529: 46721 bytes, 2570 rules

2023/06/24 19:10:35.157537 [info] Updated filter #1.  Rules: 54012 -> 54152

2023/06/24 19:10:35.157551 [info] Updated filter #1665227529.  Rules: 2724 -> 2570
.
---.
13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee

    AppArmorProfile
    Args [ --, /opt/adguardhome/AdGuardHome, --no-check-update, -c, /opt/adguardhome/conf/AdGuardHome.yaml, -h, 0.0.0.0, -w, /opt/adguardhome/work ]
    Config { AttachStderr: true, AttachStdin: false, AttachStdout: true, Cmd: /opt/adguardhome/AdGuardHome,--no-check-update,-c,/opt/adguardhome/conf/AdGuardHome.yaml,-h,0.0.0.0,-w,/opt/adguardhome/work, Domainname: , Entrypoint: /sbin/tini,--, Env: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, ExposedPorts: [object Object], Healthcheck: [object Object], Hostname: 13a0ed4c5bce, Image: adguard/adguardhome, Labels: [object Object], OnBuild: null, OpenStdin: false, StdinOnce: false, Tty: false, User: , Volumes: null, WorkingDir: /opt/adguardhome/work }
    Created 2023-06-23T19:10:28.958217393Z
    Driver overlay2
    ExecIDs [ a10307bfd16dd21a873029b09ceff62474cace6e3b88f37b72922a639d2fc108 ]
    GraphDriver { Data: [object Object], Name: overlay2 }
    HostConfig { AutoRemove: false, Binds: /srv/dev-disk-by-uuid-25f755f1-7df4-483e-948d-53ba17d264e5/NASLV2/DOCKER/ADGUARD:/opt/adguardhome/work:rw,/srv/dev-disk-by-uuid-25f755f1-7df4-483e-948d-53ba17d264e5/NASLV2/DOCKER/ADGUARD:/opt/adguardhome/conf:rw, BlkioDeviceReadBps: null, BlkioDeviceReadIOps: null, BlkioDeviceWriteBps: null, BlkioDeviceWriteIOps: null, BlkioWeight: 0, BlkioWeightDevice: null, CapAdd: null, CapDrop: null, Cgroup: , CgroupParent: , CgroupnsMode: private, ConsoleSize: 0,0, ContainerIDFile: , CpuCount: 0, CpuPercent: 0, CpuPeriod: 0, CpuQuota: 0, CpuRealtimePeriod: 0, CpuRealtimeRuntime: 0, CpuShares: 0, CpusetCpus: , CpusetMems: , DeviceCgroupRules: null, DeviceRequests: null, Devices: null, Dns: null, DnsOptions: null, DnsSearch: null, ExtraHosts: , GroupAdd: null, IOMaximumBandwidth: 0, IOMaximumIOps: 0, IpcMode: private, Isolation: , Links: null, LogConfig: [object Object], MaskedPaths: /proc/asound,/proc/acpi,/proc/kcore,/proc/keys,/proc/latency_stats,/proc/timer_list,/proc/timer_stats,/proc/sched_debug,/proc/scsi,/sys/firmware, Memory: 0, MemoryReservation: 0, MemorySwap: 0, MemorySwappiness: null, NanoCpus: 0, NetworkMode: adguard_default, OomKillDisable: null, OomScoreAdj: 0, PidMode: , PidsLimit: null, PortBindings: [object Object], Privileged: false, PublishAllPorts: false, ReadonlyPaths: /proc/bus,/proc/fs,/proc/irq,/proc/sys,/proc/sysrq-trigger, ReadonlyRootfs: false, RestartPolicy: [object Object], Runtime: runc, SecurityOpt: null, ShmSize: 67108864, UTSMode: , Ulimits: null, UsernsMode: , VolumeDriver: , VolumesFrom: null }
    HostnamePath /DOCKER/containers/13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee/hostname
    HostsPath /DOCKER/containers/13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee/hosts
    Id 13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee
    Image sha256:c96bfe259bf645b50c5c1275e78056cdd4d9ed0528d94f76a6c09e7ed862aa26
    LogPath /DOCKER/containers/13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee/13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee-json.log
    MountLabel
    Mounts [ [object Object], [object Object] ]
    Name /adguardhome
    NetworkSettings { Bridge: , EndpointID: , Gateway: , GlobalIPv6Address: , GlobalIPv6PrefixLen: 0, HairpinMode: false, IPAddress: , IPPrefixLen: 0, IPv6Gateway: , LinkLocalIPv6Address: , LinkLocalIPv6PrefixLen: 0, MacAddress: , Networks: [object Object], Ports: [object Object], SandboxID: 40523d3693387e979ba1d480b9a3c7e6185b83c34ad5d4602b66cdd7903f90ba, SandboxKey: /var/run/docker/netns/40523d369338, SecondaryIPAddresses: null, SecondaryIPv6Addresses: null }
    Path /sbin/tini
    Platform linux
    Portainer { ResourceControl: [object Object] }
    ProcessLabel
    ResolvConfPath /DOCKER/containers/13a0ed4c5bcecf704df7d33efdee3bb2527245d3c099d4a029ae7aad86168dee/resolv.conf
    RestartCount 0
    State { Dead: false, Error: , ExitCode: 0, FinishedAt: 0001-01-01T00:00:00Z, Health: [object Object], OOMKilled: false, Paused: false, Pid: 2117162, Restarting: false, Running:

**Comment by bartounet16** [comment]
This morning same problem..
Adguard no respond DNS request after certain Time

**Comment by julichan** [comment]
Same problem with me.

**Comment by jrust-ES** [comment]
Guys, this is a problem which was already discussed [here](https://github.com/AdguardTeam/AdGuardHome/issues/5898) and [here](https://github.com/AdguardTeam/AdGuardHome/issues/5896).

Till the Adguard team has located and fixed the problem, you should downgrade to version **v.0.107.29**.

**Comment by bartounet16** [comment]
Thanks a lot
So the problem is known and identified but not solved and we have to downgrade to V.0.107.29
how to downgrade on a Stack Docker ... and block the update with watchtower ?
Do you have an idea of the problem and the resolution time?

**Comment by jrust-ES** [comment]
I use docker compose and have put the following in the docker-compose.yml:

services:
  adguardhome:
    container_name: adguardhome
    restart: always
    image: adguard/adguardhome:**v0.107.29** (instead of :latest)
    healthcheck:
      disable: true
...

Like that docker will always use v0.107.29 and will never update to a more recent version.

Hope this helps.

**Comment by Freebase394** [comment]
Hi there,

Recently, about a month ago, I've been noticing some anomalous behavior, somehow always on the latest (having all updates up to date) AdGuardHome. My raspbery Pi 3 b+ would always get unresponsive after some time randomly. 
A few days ago (3 - 4 days) I upgraded to x64 intel and the same thing happened.

Can someone help me, and confirm this logical reasoning, please ?

I have creatd this issue: 
#5964

**Comment by bigwookie** [comment]
#5962

**Comment by julichan** [comment]
thanks trying v0.107.29 too

**Comment by n0rt0nthec4t** [comment]
Just found this thread and on v0.107.34.. Docker container gets reported as 'unhealthy" in portainer

**Comment by BlackScript** [comment]
same in current beta 
v0.108.0-b.41 shows in portainer as unhealthy

**Comment by bigwookie** [comment]
> 

Running this @ainar-g and is working well no crashes, spiking CPU and DNS requests are still running.

@n0rt0nthec4t @BlackScript the docker health in portainer and the Synology Container manager are staying up saying healthy. I have setup the container as bridged so expect you might be running on a different system.

**Comment by brknkfr** [comment]
I have the same problem starting from version 0.107.32. Version 0.107.31 seems to work fine ...

**Comment by julichan** [comment]
Has anyone tried 0.107.34 ? I've seen on another thread that related problems have been fixed but i m unsure if it is the same bug.

**Comment by ainar-g** [comment]
OP has indicated in another issue that the problem has been resolved, see https://github.com/AdguardTeam/AdGuardHome/issues/5896#issuecomment-1638756252.  Do not forget that a full image/container re-creation may be necessary, as documented in the [https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.34](release notes).

I'll close this issue, as it seems to have been the same as the one linked above.
