### ISSUE TITLE
invalid memory address when I try to add a client

### ISSUE THREAD

**Issue by daemon-byte** [AdguardTeam/AdGuardHome#5946]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.586+2069eddf

### Action

I just setup a docker instance of adguard home behind a reverse proxy. I have it all working and I can see the interface and make changes to any part except one. When I try to add a client, whatever options I pick I get a 502 bad gateway. When I check the logs on the server I see a run time error about invalid memory address. 

### Expected result

To be able to add a client. 

### Actual result

An error that prevents me from doing so.

### Additional information and/or screenshots

2023/06/29 18:28:40.533983 7#108 [debug] started POST adguard.*******.eu /control/clients/add
2023/06/29 18:28:40.534164 7#108 [debug] finished POST adguard.*******.eu /control/clients/add in 192.05µs
2023/06/29 18:28:40.534328 7#108 [debug] web: plain: http: panic serving 172.16.0.1:38062: runtime error: invalid memory address or nil pointer dereference
goroutine 108 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1850 +0xbf
panic({0xcbff80, 0x1f06180})
	runtime/panic.go:890 +0x262
github.com/AdguardTeam/AdGuardHome/internal/home.(*clientsContainer).jsonToClient(0x1f24640, {0x0, 0x0, 0x0, 0xc00011ae40, {0xc001996a80, 0xc}, {0x0, 0x0, 0x0}, ...}, ...)
	github.com/AdguardTeam/AdGuardHome/internal/home/clientshttp.go:127 +0x81
github.com/AdguardTeam/AdGuardHome/internal/home.(*clientsContainer).handleAddClient(0xc7b920?, {0x1982940, 0xc00018a4d0}, 0xc002a73200)
	github.com/AdguardTeam/AdGuardHome/internal/home/clientshttp.go:207 +0x187
github.com/AdguardTeam/AdGuardHome/internal/home.ensure.func1({0x1982940, 0xc00018a4d0}, 0xc002a73200)
	github.com/AdguardTeam/AdGuardHome/internal/home/control.go:231 +0x397
github.com/AdguardTeam/AdGuardHome/internal/home.(*httpHandler).ServeHTTP(0xc7c320?, {0x1982940?, 0xc00018a4d0?}, 0x4?)
	github.com/AdguardTeam/AdGuardHome/internal/home/control.go:285 +0x2f
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x1982790, 0xc000268620}, 0xc000133235?)
	github.com/NYTimes/gziphandler@v1.1.1/gzip.go:336 +0x249
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1982790?, 0xc000268620?}, 0x40d75f?)
	net/http/server.go:2109 +0x2f
github.com/AdguardTeam/AdGuardHome/internal/home.optionalAuth.func1({0x1982790, 0xc000268620}, 0xc002a73200)
	github.com/AdguardTeam/AdGuardHome/internal/home/auth.go:613 +0x23d
github.com/AdguardTeam/AdGuardHome/internal/home.(*authHandler).ServeHTTP(0x7f0d35fcdf18?, {0x1982790, 0xc000268620}, 0xc000358f20?)
	github.com/AdguardTeam/AdGuardHome/internal/home/auth.go:640 +0x9f
github.com/AdguardTeam/AdGuardHome/internal/home.postInstall.func1({0x1982790, 0xc000268620}, 0xc002a73200)
	github.com/AdguardTeam/AdGuardHome/internal/home/control.go:411 +0x102
github.com/AdguardTeam/AdGuardHome/internal/home.(*postInstallHandlerStruct).ServeHTTP(0xc002a7b700?, {0x1982790, 0xc000268620}, 0xd14ee0?)
	github.com/AdguardTeam/AdGuardHome/internal/home/control.go:420 +0x9f
net/http.(*ServeMux).ServeHTTP(0xd14ee0?, {0x1982790, 0xc000268620}, 0xc002a73200)
	net/http/server.go:2487 +0x149
github.com/AdguardTeam/AdGuardHome/internal/home.limitRequestBody.func1({0x1982790, 0xc000268620}, 0xc002a73100)
	github.com/AdguardTeam/AdGuardHome/internal/home/middlewares.go:75 +0x379
net/http.HandlerFunc.ServeHTTP(0x7f0d0e962c70?, {0x1982790?, 0xc000268620?}, 0xc000268620?)
	net/http/server.go:2109 +0x2f
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x197c160?, 0xc00011a5d0?}, 0xc000100820?}, {0x1982790, 0xc000268620}, 0xc002a73100)
	golang.org/x/net@v0.11.0/http2/h2c/h2c.go:125 +0x59b
net/http.serverHandler.ServeHTTP({0x197f7c0?}, {0x1982790, 0xc000268620}, 0xc002a73100)
	net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc00042a500, {0x1983370, 0xc00025f5c0})
	net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x4db

**Comment by dajappie** [comment]
+1 same issue. No issue with beta 37. Problem happens from the GUI as well as via API.

**Comment by ainar-g** [comment]
Version `v0.108.0-a.593+91f3e29c` should contain the fix to this issue.  Could anyone affected please check if the fix works for you?

**Comment by daemon-byte** [comment]
> Version `v0.108.0-a.593+91f3e29c` should contain the fix to this issue. Could anyone affected please check if the fix works for you?

yeh I updated my docker to the edge which seems to be that version and the problem has gone. Thanks for the fast fix

**Comment by lordvalium** [comment]
Cand update via the web, have the same issue

**Comment by MilesTEG1** [comment]
> Version `v0.108.0-a.593+91f3e29c` should contain the fix to this issue. Could anyone affected please check if the fix works for you?

I've got the same issue.
But I can't see how to test the version you suggested. I use a docker version.

**Comment by dajappie** [comment]
> > Version `v0.108.0-a.593+91f3e29c` should contain the fix to this issue. Could anyone affected please check if the fix works for you?
> 
> I've got the same issue. But I can't see how to test the version you suggested. I use a docker version.

You can simply download the edge version of the docker image from docker hub to test it. But it seems to work.

**Comment by daemon-byte** [comment]
> > > Version `v0.108.0-a.593+91f3e29c` should contain the fix to this issue. Could anyone affected please check if the fix works for you?
> > 
> > 
> > I've got the same issue. But I can't see how to test the version you suggested. I use a docker version.
> 
> You can simply download the edge version of the docker image from docker hub to test it. But it seems to work.

You add :edge to the image you are using. That will then use the edge image instead of stable and give you the latest version. You can switch it back later when that version hits stable

**Comment by MilesTEG1** [comment]
Thanks, I'll try the edge version.

**Comment by MilesTEG1** [comment]
This edge version worked very well.
Do you think the stable version based on this edge one will be released soon?
I'm not comfortable with using an alpha version in my production environment (private LAN).

**Comment by ainar-g** [comment]
Thanks you all for testing.  The fix should be coming very soon to Beta and Release channels.

**Comment by MilesTEG1** [comment]
Hello
Can we revert to the `:latest` image version?
