### ISSUE TITLE
Edge builds are pushed to the `latest` tag on Docker Hub

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#5947]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS)/AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.586+2069eddf

### Action

Update the Docker image using `latest`.

### Expected result

A stable release.

### Actual result

An Edge release.

**NOTE:** That release is actually the same as the most recent Beta release, `v0.108.0-b.38.`

**Comment by AzagraMac** [comment]
It seems that they have mixed a beta version in a stable one... 
That's what happens to me, with 107, everything was perfect. Now I have problems #5945

**Comment by dontcrash** [comment]
This was closed but the latest build on dockerhub is still an edge build.

**Comment by ainar-g** [comment]
@dontcrash, see the update at the top of the original comment.

**Comment by dontcrash** [comment]
> @dontcrash, see the update at the top of the original comment.

I saw that, but why not roll back the release on dockerhub? In the interim, people will end up using an edge build :/

**Comment by ainar-g** [comment]
Because their configuration files have already been migrated, and reverting back to the previous release would break them.

**Comment by ainar-g** [comment]
v0.107.33 has been pushed to `latest` as well as its own tag.
