### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by codac** [AdguardTeam/AdGuardHome#5948]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.32

### Action

1. adguard is running as a docker (via docker-compose) on a Synology DS420+ with DSM 7.2-64570 Update 1.
2. every couple of hours adguard crashes, no traffic running through anymore, after it restarts you can continue, but it crashes again

### Expected result

No crahes.

### Actual result

Synology Docker LOG:
2023/06/29 18:40:00.908346 [info] Received signal "terminated"
2023/06/29 18:40:00.916664 [info] stopping AdGuard Home
2023/06/29 18:40:00.916701 [info] stopping http server...
2023/06/29 18:40:00.925037 [info] stopped http server
2023/06/29 18:40:02.946945 [info] dnsproxy: stopping dns proxy server
2023/06/29 18:40:02.951355 [info] dnsproxy: stopped dns proxy server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a0 pc=0x866a98]

**Comment by ainar-g** [comment]
Thanks for the report.  Please provide the full panic log (with the backtrace).  Enabling [verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and including them into the output would help as well.

**Comment by codac** [comment]
verbose mode is running, I'll add an update after the next crash.

**Comment by codac** [comment]
I have trouble to get the verbose log running. I followed your link and set in the AdGuardHome.yaml the value for "log_file:" to `/opt/adguardhome/work/logs/aghlog.txt`
Afterwards I went to Container Manager on my Synology and added this file as a volume (file). It is mounted to a local file that exists.
The file stays at 0byte. 

Here is another extract of the container protocol:

```
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy@v0.50.2/proxy/server_udp.go:81 +0x37e
2023/07/18 06:42:40	stdout	created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy@v0.50.2/proxy/server_udp.go:82 +0x4f
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1()
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy@v0.50.2/proxy/server_udp.go:115 +0x2e6
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(0xc000105500, {0xc0048675c0, 0x5a, 0x5a}, {0xc0035a4b20, 0x10, 0x10}, 0xc005e9a4b0, 0xc000226108)
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy@v0.50.2/proxy/server.go:131 +0x3d7
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0xc000105500, 0xc00483b100)
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:124 +0x3a2
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).handleDNSRequest(0xc0000c4000, 0xdab2c0?, 0xc00483b100)
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:210 +0x205
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).processInitial(0xc0000c4000, 0xc004ec67e0)
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/filter.go:56 +0x5e
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).getClientRequestFilteringSettings(0xc0000c4000, 0xc004ec67e0)
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/filtering/filtering.go:303 +0x58
2023/07/18 06:42:40	stdout	github.com/AdguardTeam/AdGuardHome/internal/filtering.(*DNSFilter).GetConfig(0xc002fd7b68?)
2023/07/18 06:42:40	stdout	goroutine 3815562 [running]:
2023/07/18 06:42:40	stdout	
2023/07/18 06:42:40	stdout	[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a0 pc=0x866a98]
2023/07/18 06:42:40	stdout	panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by ainar-g** [comment]
Apologies for the long wait.  This log actually hints at an issue we might have, so thank you for posting this.

**Comment by schzhn** [comment]
Hello, @codac.
We've pushed the edge release, containing the fix. Could you please check it?

**Comment by codac** [comment]
@schzhn 
It turned out, that tis error message show up after I have restarted the docker. 
Why do I need to restart the docker? Becaus every 5-12 hours the traffic turns extremely slow or even dead. 
Then I need to restart the docker and the traffic is at its best performance.
The logs are empty though regarding this behaviour.
Any ideas how to investigate?

**Comment by schzhn** [comment]
Hello, @codac. Sounds like a different issue. Let's try to put things in order.
If this issue is resolved close it and start a new one with all info you have. And we will look into it.

**Comment by ainar-g** [comment]
@codac

> It turned out, that tis error message show up after I have restarted the docker.

Just to be clear, do you mean that the message is still there on the Edge channel?

> The logs are empty though regarding this behaviour.
> Any ideas how to investigate?

We've landed a fix of log settings recently, so one of the things you could do is update to the latest `edge` Docker tag.  (Backing up your configuration, of course.)

**Comment by ainar-g** [comment]
We'll close this issue.  Please reopen with new data if you see the same panic again.
