### ISSUE TITLE
Couple of times a day shoots to 100% cpu and stops working

### ISSUE THREAD

**Issue by TheBartoMan** [AdguardTeam/AdGuardHome#5952]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.586+2069eddf

### Action

a couple of times a day, it just crashes and looks like it jumps to 100% CPU. I have no option othen to to kill it and  restart it.

I did have this problem with it running on my pfsense router, so I instead installed it new into a docker on my nas.

I still get the same issue.

### Expected result

I expected it to stay steady.

### Actual result

First thing i know about the problem is all my DNS resolution stops, then I go lool and see its jumped to 100% CPU and not working.

### Additional information and/or screenshots

Here are two screen shots to show how I see it when it crashes.

<img width="810" alt="CleanShot 2023-06-30 at 15 09 27@2x" src="https://github.com/AdguardTeam/AdGuardHome/assets/28529964/aa1c80c3-8e2e-432d-9e8e-0e328b2d2f7d">
<img width="1746" alt="CleanShot 2023-06-30 at 15 07 36@2x" src="https://github.com/AdguardTeam/AdGuardHome/assets/28529964/0f0c00b4-0290-49c2-82fc-138bce17b40b">

**Comment by bigwookie** [comment]
I am experiencing the same result running two instances. Often it runs for a few hrs and other times onlyy 30 mins.

**Comment by ainar-g** [comment]
Please see https://github.com/AdguardTeam/AdGuardHome/issues/5896#issuecomment-1613290094.  Collecting the logs and the profiles would help us a lot.

Merging into that issue.
