### ISSUE TITLE
[Feature request] Intelligent Optimal DNS Resolution

### ISSUE THREAD

**Issue by Zhijie327** [AdguardTeam/AdGuardHome#596]
[Feature request] Intelligent Optimal DNS Resolution
1. Setting up multiple upstream DNS servers
2. Send parsing commands to multiple DNS servers at the same time when visiting a website
3. Choose the fastest IP feedback from multiple parsing results to the client

**Comment by ameshkov** [comment]
Well, actually it will be relatively easy to implement as [dnsproxy](https://github.com/AdguardTeam/dnsproxy) already supports this behavior (see `--all-servers` there).

**Comment by evilvibes** [comment]
I just made a post about this [Feature Request: Load-balancing strategy](https://github.com/AdguardTeam/AdGuardHome/issues/614) checking out  `--all-servers`
