### ISSUE TITLE
Someting went wrong, when I'm using Adguard and Clash together

### ISSUE THREAD

**Issue by LawyZheng** [AdguardTeam/AdGuardHome#5960]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS)/ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

版本 2.11.0.1292 release

### Action

My mac mini has already installed AdGuard And ClashX Pro.

Recently, if I enabled ClashX Pro, I found my browser injection endpoint turned into injections.adguard.org from local.adguard.org when I use Chrome to browse websites.

And I found that requests to this domain didn't return any data until err happened or timed out (about 60s to time out). So, it slows me down to browse the websites.

### Expected result

return as soon as possible

### Actual result

return very slow

### Additional information and/or screenshots

<img width="858" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/26927551/9ec05c70-fb2f-417e-8e73-b173286a336b">

**Comment by ainar-g** [comment]
This is the repository of AdGuard Home, a filtering DNS server, not of the AdGuard application.
