### ISSUE TITLE
DNS requests stop being processed but GUI responsive with high CPU usage.

### ISSUE THREAD

**Issue by bigwookie** [AdguardTeam/AdGuardHome#5962]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS)/AMD64 (aka x86_64)

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

0.107.33

### Action

Unable to resolve DNS address, no queries being processed.
![Query](https://github.com/AdguardTeam/AdGuardHome/assets/29947155/1f0c3191-75e7-4af5-a56f-a3696a5ca904)

Also the CPU was high but Adguard web interface was responding, just not to DNS requests. From teh query you can see when DNS requests stopped.

Logs attached, this happens sporadically and have tow DNS of these that do the same.

This is a docker container running on Synology DSM 7.2-64570 Update 1 and Docker Manager 20.10.23-1413

### Expected result

DNS requests being logged and returned

### Actual result

clive@R2D2:~$ nslookup -debug -type=a 'www.microsoft.com' '192.168.2.10'
;; communications error to 192.168.2.10#53: timed out
;; communications error to 192.168.2.10#53: timed out
;; communications error to 192.168.2.10#53: timed out
;; no servers could be reached

### Additional information and/or screenshots

Log file too large to upload even compress.

**Comment by bigwookie** [comment]
![stats](https://github.com/AdguardTeam/AdGuardHome/assets/29947155/b7afe0e6-7c7c-4c49-90f3-06bed50944bf)
This show high CPU usage

**Comment by ainar-g** [comment]
Thank you for the log, we're looking into this issue in #5896.  Let's continue there.
