### ISSUE TITLE
BUG - CPU 100% - Randomly

### ISSUE THREAD

**Issue by Freebase394** [AdguardTeam/AdGuardHome#5964]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found this possible related issue:
#5933
#5898
#5962 
#5896

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

AdGuard Home, version v0.107.33

### Action

```sh
nslookup -debug -type=a 'www.example.com' '127.0.0.1'
```
RESUSULT:
adguard02:/opt/AdGuardHome# nslookup -debug -type=a 'www.google.com' '127.0.0.1'
Server:         127.0.0.1
Address:        127.0.0.1:53

Query #0 completed in 35ms:
Non-authoritative answer:
Name:   www.google.com
Address: 216.239.38.120

### Expected result

I expected the AdGuardHome process to run stably and normally! 

### Actual result

But it turns out that somehow, it has some entropy and is being used abruptly consuming all system CPU resources.
WARNING: This is my 3rd attempt, I had AdGuardHome running on my RaspberyPi3 b+, I had the version "AdGuard Home v0.107.28xx" on it and it ran smoothly and beautifully, I even had my raspbery pi on for weeks straight, no anomalies.

But from some of the versions "AdGuard Home v0.107.30xx" totally randomly, and without explanation my raspbery pi simply crashed and stopped responding[From the looks of it, it seemed to be stuck somehow, as the system was totally down because it was completely in use (all its cores being in use randomly at 100%)] I tried to reinstall multiple times, but always the same, "A few hours later, the same thing"
Since a few days ago I switched to a x64 environment "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz".

Note: I can guarantee this single vCore is as strong or even stronger than the 4 cores of my raspberryPi 3 b+.
I've enabling the following features on the new AdGuardHome machine:
**1 vCore - Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz**
**4096 Mb(4GB) RAM**
"**AlpineOS --> 3.18.0**"

I can prove that the maximum CPU consumptions when updating BlockLists etc... It just represents this:
This always responding and processing to more and 10 clients in house....
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/ca81c725-c5f5-4222-9d56-5029123932af)

Suddenly and out of nowhere, something happens: I don't understand where the anomaly comes from:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/ae59f34a-3ecb-477c-8d93-7e0f75151d97)

### Additional information and/or screenshots

My virtual machine is currently in this state:
CPU consumption status: 100%.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/8082ebdf-e10f-4e66-b241-71ad9e19d475)
My cluster usualy is at 30ºC || = 86°F  on vCore0, and now is like this:

![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/598c98f6-1555-4b2f-b4d3-f6fddcdbcf7e)

**Comment by Freebase394** [comment]
It seems to be tested and try the fixes on edge versions here #5898 ...
Later, if fixed we can close this issue ...

**Comment by locolupo** [comment]
same issue here, thanks for reporting @Freebase394

**Comment by Freebase394** [comment]
@locolupo Thank you for your post. 
This proves that I am not the only human being having this problem.
Could you please post some Prints of the anomalies of your problem, like cpu status.... machine with 100% usage... print of the crash of your virtual machine etc... logs etc...please

**Comment by ainar-g** [comment]
@Freebase394, @locolupo, #5896 is the issue where we're tracking this.  As the fix developed there has been ported to Edge and Beta channels, could any one of you check if it works for you?

**Comment by Freebase394** [comment]
@ainar-g Thanks! Installed Beta version using the folowing command:
Script to install a beta version:
curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c beta

I'm going to leave this server running, it's being the primary DNS for my entire home network, with 7~10 devices around here on the network! 
Let's see how the one behaves! 
Hopefully well! 
I promise to bring new feedback in a few days! 


My VM  properties:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/fd0171bd-f8fe-4c0f-9402-0281b1915d1e)

For Beta installed just now:
All ok for now:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/4b611cf1-3d4c-46d7-a36b-8d7b6f28a847)

**Comment by Freebase394** [comment]
Well... 
For now everything has been running "quite" stable and solid! 
Now i'm using a total of rules equal to:  (+/-) **6365523** on my  own AdGuardHome [DNS blocklists AdGuard Home will block domains matching the blocklists]

######
**My Hypervisor:** Proxmox 8.0.3
**CPU:** i5-3470 CPU @ 3.20GHz (4 total cores)
######

**My VM running:**
 **Status**: running
 **HA State:** none
 **Node:** pve
 **CPU usage:** 0.04% of 2 CPU(s) (I'm only have 2 vCPU)
 **Memory usage**: 32.00% (511.96 MiB of 1.56 GiB)
 **SWAP usage:** 2.50% (9.99 MiB of 400.00 MiB)
 **Bootdisk size:** 3.02% (240.61 MiB of 7.78 GiB)
 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/70c01f40-4c9c-4349-9893-0a3ba81704be)


Every time I update my lists, this is the status of the VM behavior on top of an LX container(Alpine OS Linux --> Very small distro) 
It does not reach values above 30%/45% of the entire cpu! 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/8c9a5742-25ee-4852-b168-13f6c1002298)

Memory Consuption:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/cad37e94-397e-4de3-b0c7-8ad588c40f82)


Network status: 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/fda6108d-1f27-4917-a017-fe54419e80f7)


Disk IO
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19652056/be23ce0c-2213-4581-a0d6-58a736cb968f)

**Comment by ainar-g** [comment]
Short-term CPU spikes during filter updates are to be expected, especially if there are a lot of rules.  I assume, as long as the persistent 100 % CPU spike is gone, the issue can be be considered resolved by the update?

**Comment by Freebase394** [comment]
> Short-term CPU spikes during filter updates are to be expected, especially if there are a lot of rules. I assume, as long as the persistent 100 % CPU spike is gone, the issue can be be considered resolved by the update?

Yes, please! I will be especially attentive to the next days and weeks, it may be a little early to say that it may be 100% resolved, but for now, everything ok! ! 
But for now, we can close this thread, otherwise we can open it again.

**Comment by Freebase394** [comment]
Seems to be fixed. 
"AdGuard Home, version v0.108.0-b.41" 
All ok after 5 days running! 
I will close this issue now!
