### ISSUE TITLE
moved text on mobile wide

### ISSUE THREAD

**Issue by nillebor** [AdguardTeam/AdGuardHome#5968]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.33

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

The problem has been occurring for quite some time after a line has been extended.
Wide on desktop (PC) is ok

### Actual result

Android wide (90°):
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/59985723/55a85f3a-4a9a-4c12-9836-20a633882fc7)

Android high (0°) > ok
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/59985723/49146908-42a5-4872-b368-5f3fa33be9b7)

**Comment by IldarKamalov** [comment]
Could you please provide information what browser and operating system you are using?

**Comment by nillebor** [comment]
Problem is solved. 
It is due to the old version of the browser. An update to a new LineageOS version with the current browser shows everything correctly.
