### ISSUE TITLE
Greek Language

### ISSUE THREAD

**Issue by JN19aban** [AdguardTeam/AdGuardHome#5973]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Hi,

I want to request to support Greek language if possible.

Regards.

### Proposed solution

Add language pack.

**Comment by ainar-g** [comment]
Good day.  As [stated in the README](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#translate), we use [Crowdin](https://crowdin.com/project/adguard-applications/en#/adguard-home) to manage our translations.  Most translations are done by the community, and the Greek translation seems to be mostly done, but it needs proofreading and approval.  If you want to become the project's proofreader for Greek texts, please register on Crowdin and send an E-mail to <translate@adguard.com> with your username and a link to this issue.

See also <https://adguard.com/kb/miscellaneous/contribute/translate/program/>.
