### ISSUE TITLE
Unable to Find ghcr.io Entry for Geoipupdate

### ISSUE THREAD

**Issue by ZaxLofful** [AdguardTeam/AdGuardHome#5975]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I see that there is a docker file for this project, but I cannot find the GitHub Container Registry for this project. I do see it on Docker Hub, but I no longer use that as my default due to licensing issues.

### Proposed solution

Use GitHub actions to build a Docker container and then add it to GHCR.

### Alternatives considered and additional information

There is no guarantee that Docker won't take down the free container registry at some point, so this essentially is the backup option.

**Comment by ainar-g** [comment]
We are not planning on adding new packages and distributions in the nearest future, sorry.

**Comment by ainar-g** [comment]
It is never “just it”, I'm afraid.  Every new packaging method adds complexity in support, maintenance, internal and external release processes, etc.  If there are people who'd like to provide community support for other release methods, they're welcome to do so (especially considering that our builds are reproducible), but our team would rather not add more complexity to the (already excessive, imo) packaging processes we have to support.

**Comment by ZaxLofful** [comment]
Isn't it the same package? it's just a Dockerfile?
