### ISSUE TITLE
Inconsistent display of ClientID for DoH/DoT

### ISSUE THREAD

**Issue by pwsnla** [AdguardTeam/AdGuardHome#5979]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

Version: v0.107.33

### Action

Display of ClientIDs obtained from the URL for DoH and DoT is inconsistent.
I can see ClientIds on the Dashboard in the Top Clients  section but in the Query Log ClientIds are not displayed. Instead I see names obtained from reverse DNS lookup. I can however search the Query Log by ClientId and it works.

### Expected result

I think ClientIds from the URL should be displayed in the Query Log just like they are displayed in the Top Clients section of the Dashboard. Names from the reverse DNS lookup are less useful as most of my clients connect from the same public IP.

### Actual result

Client names from reverse DNS lookup are displayed in the Query Log section of Adguard Home.

### Additional information and/or screenshots

If I disable reverse resolving of client's IP addresses ClientID is displayed in the query log. I still think that query log display should be consistent with Dashboard display and display ClientID (if available) even if reverse resolving of client IP addresses is enabled.

**Comment by muok** [comment]
Yes, this happens on my instances as well.
