### ISSUE TITLE
系统重启后 adguard的DHCP服务器 静态分配地址全部消失，客户端地址重新分配

### ISSUE THREAD

**Issue by lb7432** [AdguardTeam/AdGuardHome#5984]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.33

### Action

系统重启后 adguard的DHCP服务器 静态分配地址全部消失，客户端地址重新分配

### Expected result

系统重启静态地址分配不会消失

### Actual result

系统重启静态地址分配消失了

**Comment by buzidjy** [comment]
我也遇到了一样的问题
