### ISSUE TITLE
`Runtime clients` tables contains duplicates of `Persistent clients` table

### ISSUE THREAD

**Issue by nareddyt** [AdguardTeam/AdGuardHome#5985]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARMv6

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.33

### Action

Visit Settings --> Client Settings on AGH web UI

### Expected result

As mentioned in the `Runtime Clients` table

> Devices **not** on the list of Persistent clients that may still use AdGuard Home

So Runtime Clients should NOT contain any devices from Persistent Clients

### Actual result

Duplicates listed, see screenshot

![image](https://github.com/AdguardTeam/AdGuardHome/assets/11142171/a82d84b0-d4ee-457a-8c26-71f21d08ce4a)

### Additional information and/or screenshots

Running Adguard on HomeAssistant via addon

Other users notice this issue, but there is no resolution: https://github.com/AdguardTeam/AdGuardHome/discussions/5466

**Comment by ainar-g** [comment]
Thanks for the report.  It seems like it's the UI label that is incorrect, since one is not a strict subset of the other.  We'll fix the label.

**Comment by nareddyt** [comment]
Sounds good to change the UI label.

In addition, would you be open to adding functionality to keep the behavior described in the UI label? It is useful to filter out the runtime clients and only show unknown ones.

Maybe we can add another column to the runtime clients table that maps the client to a persistent client. This would allow for sorting on clients that are unknown.

Lmk if I can contribute this

**Comment by ainar-g** [comment]
Better not, at least not now.  We're planning a lot of changes to the client logic between now and v0.108.0; both persistent and runtime.  There is a chance that your changes could be lost in the process.

If you'd like a temporary workaround for that, I've noticed that most dups in your case are from the ARP resolving, so if you don't really need it, you can just set `clients.runtime_sources.arp` to `false`.

**Comment by ainar-g** [comment]
We have improved the text on the Edge channel.  It will be included in a future release.
