### ISSUE TITLE
AD Guard (Home Assistant integration) is not filtering anything

### ISSUE THREAD

**Issue by AntonKNZ** [AdguardTeam/AdGuardHome#5987]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS)/AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

0.107.33

### Action

AD Guard Home (Home Assistant integration) stopped working. First, it failed to block and report adult content, now it stopped working completely. I tried to restart it - no effect. I tried to disable it and now it is not responding

it was working for 3 months, no  configuration changes were done in 2 months

### Expected result

integration to be functioning

### Actual result

Integration not functioning

**Comment by M4ndaL0re** [comment]
Same here (if i understood corectly)
Installed on NAS and since Update to version: 0.107.38, AGH is showing that Filter is working „blocked“ but Sites still can be opened.

no other DNS Set.

reboot AGH causes no internet, so AGH is the only DNS resolver in Network.

**Comment by M4ndaL0re** [comment]
> Same here (if i understood corectly) Installed on NAS and since Update to version: 0.107.38, AGH is showing that Filter is working „blocked“ but Sites still can be opened.
> 
> no other DNS Set.
> 
> reboot AGH causes no internet, so AGH is the only DNS resolver in Network.

Found Problem: IOS wifi settings „disable Tracking“ Forced the Problem. After deaktivation my mobile phones now blocks correctly websites
