### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by CWo42** [AdguardTeam/AdGuardHome#599]
Thanks for the nice work and the encryption

but how can i use DNS over HTTPS from Client side

https://adguardurl/dns-querry seems not to work ? what URL should i use?

Thanks and keep going
Chris

**Comment by ameshkov** [comment]
It does work actually. What client do you use?

**Comment by CWo42** [comment]
I tried it with Firefox

**Comment by ameshkov** [comment]
Well, I've just tested my AGH instance with FF and it works okay.

Here's what you need to check:
1. Check that you configured the bootstrap address (it's necessary): https://www.ghacks.net/2018/04/02/configure-dns-over-https-in-firefox/
2. Check that you're using a valid certificate and FF trusts it.

**Comment by CWo42** [comment]
Thanks, works well. I was just missing the bootstrap -.-

**Comment by ameshkov** [comment]
Yeah, the fact that bootstrap is mandatory is a bit confusing.
