### ISSUE TITLE
unable to access dashboard after manual update

### ISSUE THREAD

**Issue by youngunix** [AdguardTeam/AdGuardHome#5993]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD/AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.33

### Action

The automatic update keeps failing and providing a link to manually update AGH. I followed the steps as described in the link below (I'm on FreeBSD instead of Linux, so I downloaded the correct 'gz' file) and now I am unable to access the AGH dashboard. 

[https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update](url)

### Expected result

Update to the latest version and be able to access the dashboard.

### Actual result

AGH dashboard is no longer accessible.

**Comment by ainar-g** [comment]
Hello.  Inspecting the [AdGuard Home logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#logs) and enabling [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) should help you diagnose the issue.

**Comment by youngunix** [comment]
I spent a couple of hours yesterday on this issue without any luck. So, here is what I've done that didn't work:

- I backed up the previous version of the AdGuardHome binary file and the SIG one as well.
- since the manual update did not work and I could no longer access the login page, I restored the back up files the same way I did the manual update, but that did nothing.
- I rebooted the firewall, also did nothing, so I left it alone.

Now, when I tried to access the login page a few minutes ago, bam! I can login now and AGH was updated! I have no idea why the automatic update failed in the first place, why the manual update did not work, or why restoring the previous version did not work either. 

Even though this issue has solved itself, I'm afraid that any other end user with this issue might not benefit from this post. 

I'll leave it up to you guys to decide if you want to close it as resolved or if there are any other info you need that would perhaps determine the root cause of this issue.

**Comment by ainar-g** [comment]
I'm glad something helped, heh.  If you do want to investigate it, you can save the logs next time it happens and post the errors here or send them to <devteam@adguard.com> and reopen the issue.
