### ISSUE TITLE
AdGuard Blocks Internet Connection

### ISSUE THREAD

**Issue by GammaPotato** [AdguardTeam/AdGuardHome#5994]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows/ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0v107v33

### Action

AdGuard Home Worked fine for a 1 or 2 Hours.  My Router is Connected to adguard via DNS. After That the Complett Internet Connection got Broken. When i turn of The Protection everything is working but with protection everything got blocked. 

Windows Server restart, hardware Restart, nothing helped. 

EDIT:
the message "invalid basic authorization value" shows up after running a while

The Log shows an Error but i dont know what that means.
I Tested Upstream and it easy everything is fine
```
2023/07/11 13:30:12.794399 [info] AdGuard Home, version v0.107.33
2023/07/11 13:30:12.825625 [info] tls: using default ciphers
2023/07/11 13:30:12.825625 [info] safesearch default: reset 253 rules
2023/07/11 13:30:12.825625 [info] Initializing auth module: C:\Users\Administrator\Desktop\AdGuardHome\data\sessions.db
2023/07/11 13:30:12.825625 [info] auth: initialized.  users:1  sessions:3
2023/07/11 13:30:12.825625 [info] tls: number of certs: 3
2023/07/11 13:30:12.825625 [info] tls: got an intermediate cert
2023/07/11 13:30:12.825625 [info] tls: got an intermediate cert
2023/07/11 13:30:12.854032 [info] web: initializing
2023/07/11 13:30:12.902438 [info] dnsproxy: cache: enabled, size 4096 b
2023/07/11 13:30:12.902438 [info] dnsproxy: max goroutines is set to 300
2023/07/11 13:30:12.902438 [info] AdGuard Home is available at the following addresses:
2023/07/11 13:30:12.902438 [info] go to http://192.168.31.140:80
2023/07/11 13:30:12.902438 [info] go to https://privatnas.servebeer.com:443
2023/07/11 13:30:13.104936 [info] dnsproxy: starting dns proxy server
2023/07/11 13:30:13.104936 [info] Ratelimit is enabled and set to 50 rps
2023/07/11 13:30:13.104936 [info] The server is configured to refuse ANY requests
2023/07/11 13:30:13.104936 [info] dnsproxy: cache: enabled, size 4194304 b
2023/07/11 13:30:13.104936 [info] dnsproxy: max goroutines is set to 300
2023/07/11 13:30:13.104936 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2023/07/11 13:30:13.104936 [info] dnsproxy: listening to udp://[::]:53
2023/07/11 13:30:13.104936 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2023/07/11 13:30:13.114939 [info] dnsproxy: listening to tcp://[::]:53
2023/07/11 13:30:13.114995 [info] dnsproxy: creating tls server socket 0.0.0.0:853
2023/07/11 13:30:13.114995 [info] dnsproxy: listening to tls://[::]:853
2023/07/11 13:30:13.114995 [info] Creating a QUIC listener
2023/07/11 13:30:13.114995 [info] Listening to quic://[::]:853
2023/07/11 13:30:13.114995 [info] dnsproxy: entering tcp listener loop on [::]:53
2023/07/11 13:30:13.114995 [info] dnsproxy: entering udp listener loop on [::]:53
2023/07/11 13:30:13.114995 [info] dnsproxy: entering tls listener loop on [::]:853
2023/07/11 13:30:13.114995 [info] Entering the DNS-over-QUIC listener loop on [::]:853
2023/07/11 13:32:01.877615 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "www.google.at": safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDc2ZGQEYTc2MAJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2023/07/11 13:32:14.139708 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "www.google.com": safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDE5MTMEZDRjOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2023/07/11 13:32:14.283235 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "www.google.at": safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDc2ZGQEYTc2MAJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2023/07/11 13:32:14.695091 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "www.google.at": safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDc2ZGQEYTc2MAJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2023/07/11 13:32:25.082487 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "clients4.google.com": safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABGI5YjgEZDRjOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
2023/07/11 13:32:26.551878 [error] handling tcp: handling tcp request: talking to dns upstream: checking host "lh3.google.com": safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDY4NWUEZDRjOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"
```

### Expected result

Access Internet without get blocked by AdGuard Home

### Actual result

Complett network got blocked

**Comment by GammaPotato** [comment]
i dont understand that. i added the following lines to "upstream-DNS Server"

[tcp://94.140.14.140:53
udp://unfiltered.adguard-dns.com
tls://unfiltered.adguard-dns.com
h3://unfiltered.adguard-dns.com/dns-query
quic://unfiltered.adguard-dns.com
94.140.14.140](url)

and now everything works fine?

**Comment by muok** [comment]
Why are you using duplicates on the upstream server?

Try using just one;
tls://unfiltered.adguard-dns.com

**Comment by ainar-g** [comment]
>  `safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDY4NWUEZDRjOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"`

Seems like AdGuard DNS, where AdGuard Home's Safe Browsing feature gets its data, is blocked for you.  You should try disabling Safe Browsing and seeing if that helps.

 >   The console spams "[info] auth: invalid Basic Authorization value" every 1-5 min

Is your web interface publicly available?  Someone could be trying to guess your password.

**Comment by GammaPotato** [comment]
> > `safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDY4NWUEZDRjOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"`
> 
> Seems like AdGuard DNS, where AdGuard Home's Safe Browsing feature gets its data, is blocked for you. You should try disabling Safe Browsing and seeing if that helps.
> 
> > The console spams "[info] auth: invalid Basic Authorization value" every 1-5 min
> 
> Is your web interface publicly available? Someone could be trying to guess your password.

not anymore. Now in my privat Wireguard VPN. 

Tryed turn off safe browser but doesnt work. I added does dns server and now it works fine.

**Comment by Freebase394** [comment]
> > > `safe browsing: getting hashes: requesting https://family.adguard-dns.com:443/dns-query: Get "https://family.adguard-dns.com:443/dns-query?dns=AAABAAABAAAAAAAABDY4NWUEZDRjOQJzYgNkbnMHYWRndWFyZANjb20AABAAAQ": all dialers failed: 4 errors: "dial tcp 94.140.14.15:443: i/o timeout", "dial tcp 94.140.15.16:443: i/o timeout", "dial tcp [2a10:50c0::bad1:ff]:443: i/o timeout", "dial tcp [2a10:50c0::bad2:ff]:443: i/o timeout"`
> > 
> > 
> > Seems like AdGuard DNS, where AdGuard Home's Safe Browsing feature gets its data, is blocked for you. You should try disabling Safe Browsing and seeing if that helps.
> > > The console spams "[info] auth: invalid Basic Authorization value" every 1-5 min
> > 
> > 
> > Is your web interface publicly available? Someone could be trying to guess your password.
> 
> not anymore. Now in my privat Wireguard VPN.
> 
> Tryed turn off safe browser but doesnt work. I added does dns server and now it works fine.
Can you be more specific please?
What dns did you insert or put in?
Did you insert DNS different from AdGuardHome default DNS? Which one's?

**Comment by GammaPotato** [comment]
Sorry i have a bad English. i try with Translater

I only ever had the problem with these messages with the "timeout" and the entire internet was blocked

I then added these upstream DNS servers:

```
tcp://94.140.14.140:53
udp://unfiltered.adguard-dns.com
tls://unfiltered.adguard-dns.com
h3://unfiltered.adguard-dns.com/dns-query
quic://unfiltered.adguard-dns.com
94.140.14.140
```

Now everything works without problems


The message
```
auth: invalid Basic Authorization value
```
is now also gone since I integrated AdGuard Home into my private VPN
