### ISSUE TITLE
AdGuard thinks all requests are . domains?

### ISSUE THREAD

**Issue by Lagicrus** [AdguardTeam/AdGuardHome#5995]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.33

### Action

I attempted to use the internet and it failed. 
I was able to ping through to 1.1.1.1 with no issues, and google.com also worked but I believe that was cached.
Yet for 40-45mins straight I couldn't access the internet.
All the requests that were sent to AdGuard were like the following screenshot
![image](https://github.com/AdguardTeam/AdGuardHome/assets/24227350/9f261477-c02c-4321-a8f6-35dcfcb545d8)
To such a degree it is now at the top of my stats
![image](https://github.com/AdguardTeam/AdGuardHome/assets/24227350/55301103-8ade-4177-b573-70cf63756826)

I am currently "blaming" AdGuard as when I set another device to not go through it by changing the IP to 1.1.1.1 (which is set as a DNS provider within AdGuard itself), instant internet.
It has currently healed itself but I have 0 idea why this happened in the first place or how to avoid it

### Expected result

Access the internet

### Actual result

No access to the internet

**Comment by ainar-g** [comment]
`NS .` is a type of query a device in the network is sending. You can make one yourself using something like:

```sh
nslookup -debug -type=NS '.'
```

As for DNS filtering shutting down, it could be #5896, a tentative fix for which has been released on the Beta channel today.  We'd appreciate it if you tried the Beta build and see if that fixes the issue for you.

**Comment by gyCfjSnO** [comment]
I have the same thing happening.

<img width="426" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/49738152/a7a3bfa2-9f3c-4e32-8653-41ea527c22a7">

**Comment by ainar-g** [comment]
@gyCfjSnO

 >  These ‘.’ entries were not present before one of the updates.

Because there was a bug preventing them from appearing.  See #5910.  It doesn't mean they weren't there.

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO
> 
> > These ‘.’ entries were not present before one of the updates.
> 
> Because there was a bug preventing them from appearing. See #5910. It doesn't mean they weren't there.

How do I stop them from appearing and filling up my logs?

**Comment by ainar-g** [comment]
See #5990.  It'll land in an upcoming release.

**Comment by gyCfjSnO** [comment]
> See #5990. It'll land in an upcoming release.

Thanks. Will it be pushed to beta channel shortly?

**Comment by Lagicrus** [comment]
Hey, thanks for the feedback @ainar-g 
I ended up looking up what a type NS was because I was confused. It was more the confusion that for 30 mins straight, my DNS logs were either the dot domains or custom allowed. No "normal" DNS requests went through
I don't mind that they did appear; it is the fact my DNS requests were apparently only them

If it starts to act the same again, I will try swapping to that beta you specified, thanks :)

**Comment by ainar-g** [comment]
The fix for the mentioned issue has been released in v0.107.34, so you can just update.

**Comment by Lagicrus** [comment]
Thanks :pray:
