### ISSUE TITLE
Client tags become invalid after an attempt to add the client with a duplicated identifier 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardHome#6002]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.34

### Steps to reproduce 
1. Go to the Settings -> Client settings 
2. Click the `Add Client` button and add a client with an identifier by IP 
3. Press the `Add Client` button once again, enter any name, select some tags and enter the same identifier
4. Click the `Save` button 

### Expected result

An error about an already existing client is displayed. Tags remain unchanged. 

### Actual result

The error about an existing client is displayed, but the tags have become invalid. 

### Additional information and/or screenshots

![Screenshot from 2023-07-11 19-45-43](https://github.com/AdguardTeam/AdGuardHome/assets/107266340/3d9c6958-aa4c-40b7-968b-74a698a72367)

**Comment by Freebase394** [comment]
How can i 

> ### Prerequisites
> * [x]  I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer
> * [x]  I have searched other issues and found no duplicates
> * [x]  I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)
> * [x]  I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)
> 
> ### Platform (OS and CPU architecture)
> Linux/AMD64 (aka x86_64)
> 
> ### Installation
> GitHub releases or script from README
> 
> ### Setup
> On one machine
> 
> ### AdGuard Home version
> v0.107.34
> 
> ### Action
> ### Steps to reproduce
> 1. Go to the Settings -> Client settings
> 2. Click the `Add Client` button and add a client with an identifier by IP
> 3. Press the `Add Client` button once again, enter any name, select some tags and enter the same identifier
> 4. Click the `Save` button
> 
> ### Expected result
> An error about an already existing client is displayed. Tags remain unchanged.
> 
> ### Actual result
> The error about an existing client is displayed, but the tags have become invalid.
> 
> ### Additional information and/or screenshots
> ![Screenshot from 2023-07-11 19-45-43](https://user-images.githubusercontent.com/107266340/253042897-3d9c6958-aa4c-40b7-968b-74a698a72367.png)

Please describe, in detail, so that I can try to reproduce as closely as possible this problem that is happening on your side!

**Comment by ainar-g** [comment]
@Freebase394, I'm once again asking you to please not speak on our behalf.  Moreover, OP is a member of our organization, and the issue has already been reproduced and assigned by me.

**Comment by Freebase394** [comment]
> , I'm once again asking you to please not speak on our behalf. Moreover, OP is a member of our organization, and the issue has already been reproduced and assigned by me.

Sorry!
