### ISSUE TITLE
[Docker] Health check fails with "healthcheck.sh: no such file or directory: unknown"

### ISSUE THREAD

**Issue by rursache** [AdguardTeam/AdGuardHome#6007]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.34

### Action

Watchtower updated the AdGuard container last night. Since then, the health check fails but the container is running and everything works as expected. 

### Expected result

The health check should report the container as being healthy.

### Actual result

```sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "/opt/adguardhome/scripts/healthcheck.sh": stat /opt/adguardhome/scripts/healthcheck.sh: no such file or directory: unknown
```

### Additional information and/or screenshots

Docker run command:
```sh
docker run -d \
  --name adguard \
  --restart always \
  --network host \
  -e TZ=Europe/Bucharest \
  -v /home/USER/.adguard:/opt/adguardhome/work \
  -v /home/USER/.adguard:/opt/adguardhome/conf \
  adguard/adguardhome:latest
```

**Comment by ainar-g** [comment]
Please read this note in the [release notes](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.34):

> **NOTE:** Some Docker tools may cache `ENTRYPOINT` and `HEALTHCHECK` sections, so some users may be required to backup their configuration, stop the container, purge the old image, and reload it from scratch.

Watchtower is likely to be one of these tools

**Comment by rursache** [comment]
Indeed, a fresh container install fixed it. The relevant piece of the release notes would be:
> Docker users should note that the Docker HEALTHCHECK mechanism has been removed, since it was causing a lot of issues, especially when used with Podman and other popular Docker tools.
So it wasn't lying, the heathcheck script was missing but that was on purpose. 
All good now!

**Comment by Turbine1313** [comment]
Will a recrate or duplicate container will work as well ?
Because I still get that error.
Thanks
