### ISSUE TITLE
Is this  correct?

### ISSUE THREAD

**Issue by monsm** [AdguardTeam/AdGuardHome#6012]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARMv5

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.34

### Action

Here's what I see：

Time
16:20:00.460
Date
2023/7/14
Status
Blocked by CNAME or IP
Domain
accscdn.cp12.ott.cibntv.net
Type
A
Protocol
Plain DNS
Response details
DNS server
211.137.64.163:53 (served from cache)
Elapsed
1 ms
Rule(s)
||accscdn.m.taobao.com^
X
Response
A: 0.0.0.0 (ttl=10)
Response code
NOERROR
Client details
IP address
2409:8a4c:1064:e6f0:292b:7a97:d574:342d
Country
CN
Network
China Mobile
Original response
A: 0.0.0.0 (ttl=10)

The address of the Rule I'm using is: https://github.com/monsm/XXKiller/raw/main/x-adguard.txt

### Expected result

Is this Blocked correct？If this is correct and I don't want to use this feature, how do I Turn It Off?

### Actual result

nothing

**Comment by monsm** [comment]
Here's another one. Let's see if it's right?

Time
15:57:15.393
Date
2023/7/14
Status
Blocked by CNAME or IP
Domain
www.feishu.cn
Type
AAAA
Protocol
Plain DNS
Response details
DNS server
211.137.64.163:53
Elapsed
6 ms
Rule(s)
||queniurc.com^
X
Response
AAAA: :: (ttl=10)
Response code
NOERROR
Client details
IP address
2409:8a4c:1064:e6f0:8152:461a:22cc:d642
Country
CN
Network
China Mobile
Original response
AAAA: :: (ttl=10)

**Comment by ainar-g** [comment]
Please pay attention to this line:

> Blocked by CNAME or IP

If you perform a query, you'll see that `accscdn.cp12.ott.cibntv.net` has a CNAME with `accscdn.m.taobao.com` in it:

```sh
dig IN A 'accscdn.cp12.ott.cibntv.net' @8.8.8.8
```

```none
…
;; ANSWER SECTION:
accscdn.cp12.ott.cibntv.net. 600 IN     CNAME   accscdn.m.taobao.com.
accscdn.m.taobao.com.   300     IN      CNAME   zb-center-accscdn.m.taobao.com.
zb-center-accscdn.m.taobao.com. 300 IN  CNAME   zb-center-accscdn.m.taobao.com.gds.alibabadns.com.
zb-center-accscdn.m.taobao.com.gds.alibabadns.com. 300 IN A 59.82.113.217
…

**Comment by monsm** [comment]
@ainar-g ,I don't want to use this feature(blocked by cname), how do I Turn It Off?

**Comment by ainar-g** [comment]
You can't.  [CNAME cloaking](https://blog.apnic.net/2020/08/04/characterizing-cname-cloaking-based-tracking/) is a common way for trackers and advertisers to work around blocking.  If you think there is a mistake in the filter, you can report it to the filter maintainers.  In the meantime, you can use something like `||accscdn.m.taobao.com^$badfilter` to remove this rule from the engine.
