### ISSUE TITLE
Accessing adguardHome administration interface from outside of subnet results in "Forbidden"

### ISSUE THREAD

**Issue by poshul** [AdguardTeam/AdGuardHome#6019]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux/ARM64

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

cde1f5f2c3f0cda425caddd47fba1a2168d591b48772f6303e3bf2aa07f3ba5a

### Action

I've set up AdGuardHome on my router in a container. I've got the containers in a separate subnet from the end user devices (routing between the subnets works fine). Configuration on port 3000 works fine, but after finishing setup I am unable to connect to the management interface (the DNS server itself works fine) from the end-user subnet. I get a 403 Forbidden message instead.

### Expected result

going to the management interface pulls up the login page

### Actual result

Forbidden

**Comment by poshul** [comment]
Turns out it was just firefox being "helpful" and auto-completing my $IPADDR to $IPADDR/admin, because I'd previously used the same IP for a pi-hole instance.

**Comment by poshul** [comment]
Please ignore the above. Going directly to $IPADDR/index.html allowed login, but all other pages still gave 403. I've redeployed in the same subnet and everything works as it should, so it's clearly something with trying to access the admin page from outside of the subnet.

**Comment by poshul** [comment]
Issue was solved by clearing the whole cache of firefox. I've opened up a bug with them https://bugzilla.mozilla.org/show_bug.cgi?id=1843757.

**Comment by ainar-g** [comment]
@poshul, do I understand correctly that there is no bug with AGH?

**Comment by poshul** [comment]
It appears that way. I can close this, and try to figure out what in the heck is going with the caching over in firefox.
