### ISSUE TITLE
Hope add a custom server name function or option

### ISSUE THREAD

**Issue by Zhijie327** [AdguardTeam/AdGuardHome#602]
C:\Windows\system32>nslookup www.google.com
Server:  UnKnown <== ==
Address:  10.0.1.2
Non-authoritative answer:
Name:    www.google.com
Addresses:  2404:6800:4012:1::2004
                   173.252.110.21

Could you add a custom server name function or option? For Example: Server: AdGuardHomeDNS

**Comment by ameshkov** [comment]
Do you mean some custom hostname?

For now, you can add them in the filters settings using the hosts files syntax:
`127.0.0.1 example.org`

Or do you mean something else?

**Comment by Zhijie327** [comment]
THANKS!
