### ISSUE TITLE
Get blocklist names from "! Title:" definition for Adblock lists

### ISSUE THREAD

**Issue by cenk** [AdguardTeam/AdGuardHome#6020]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

AGH should respect adblock blocklist's name (title) definition in DNS blocklists page.

### Proposed solution

Geting blocklist names from "! Title: " definition for Adblock lists.

**Comment by Freebase394** [comment]
I could not understand perfectly what you mean.
Could you give an example or be more specific please?

Snario 1###
AdBlock as an extension has the particularity to eliminate efficiently the scripts | functions | injectors inserted in the pages and this can be analyzed which [HERE](https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_privacy.txt).
These extensions are very efficient as in sites with many ads, as in Youtube.com itself for example!


Snario 2###
Or do you want to block all domains that contain that specific keyword?
For example, you want to block the word "statistics":
dl1.**statistics**.universalwebsite.com
**statistics**.youtube.com
**statistics**.blogspot.com
**statistics**.facebook.com
Do you want to block all domains that contain the specified keyword (target words) in AdGuardHome ?

**Comment by ainar-g** [comment]
I guess we could let users leave the Name field blank, which would use the `! Title` directive content instead.  But we'll need a third option in case there is neither a user-provided name nor a directive.

**Comment by cenk** [comment]
I think there is a title parser function for Adblock blocklists. But I'm really not sure why it is not working. Or it is completly different thing. I'm not familiar with Go. 🙂

https://github.com/AdguardTeam/AdGuardHome/blob/0cd441f04f4ed243c79e23e4ba146843fe2e1962/internal/filtering/rulelist/parser.go#L166

**Comment by Mizzick** [comment]
Please have a look, we have implemented the requested changes.
The new build version `v0.108.0-a.650+c54635e8` has been just published to the edge channel.

**Comment by cenk** [comment]
Yes works on v0.108.0-a.650+c54635e8.
When I leave the name blank, getting from adblock file. Thanks.
