### ISSUE TITLE
v0.107.33 v0.107.34 doh bug

### ISSUE THREAD

**Issue by bloodopensun** [AdguardTeam/AdGuardHome#6028]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.33 v0.107.34

### Action

Using AdGuard Home
Enable encryption settings
https auto redirect fasle
HTTPS port 2096
domain a.com
SSL certificate is good

Use caddy reverse proxy installed by another server
domain b.com

In version v0.107.33
https://b.com/dns-query is good
But in v0.107.33 and v0.107.34
As long as you use doh to visit once, the program will not respond
Any new dns requests show nothing in the logs
Including UDP port 53 as well

After a period of time, the log can see several logs with high latency
Subsequent udp port 53 requests are back to normal

When a doh request comes in, repeat the above situation

### Expected result

Such as v0.107.33 normal use doh

### Actual result

not working

**Comment by bloodopensun** [comment]
> 没有猜错的话。你运行adguardhome后几分钟内，收到的dns请求延迟超过5000ms。

是的,但是全程使用53端口并不会出现
只有使用一次doh后会出现假死
web管理可以使用 53端口超时

过一会web管理的日志模块能看到超高延迟的纪录
后续53端口就恢复正常

只要再次有doh的请求进来 又回重复

Yes, but using port 53 all the way will not appear
Only after using doh once will there be a suspended animation
Web management can use port 53 to time out

After a while, the log module of web management can see the record of ultra-high delay
Subsequent port 53 will return to normal

As long as doh requests come in again, repeat

**Comment by krombel** [comment]
I have the same issue with v0.107.34 when DOH or DOT is configured. Even checking causes a freeze (as in 53 timeout)
