### ISSUE TITLE
token too long

### ISSUE THREAD

**Issue by Ghost108** [AdguardTeam/AdGuardHome#6031]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.34

### Action

Since the last update of adguard, my docker container status shows "warning"
Platform: Synology Docker (container Manager)

![Bildschirmfoto 2023-07-20 um 11 42 38](https://github.com/AdguardTeam/AdGuardHome/assets/17011498/0bc5553d-09ad-47ec-a3cc-9440a1c94385)

### Expected result

Stauts "OK" instead of warning

### Actual result

Stauts "warning" instead of ok

**Comment by ppfeufer** [comment]
![image](https://github.com/AdguardTeam/AdGuardHome/assets/2989985/5a41171b-9209-4357-b4e0-30dd1eb38445)
Nope, you didn't search. The issue is literally pinned at the top of the issues list …

See: https://github.com/AdguardTeam/AdGuardHome/issues/6003

**Comment by Ghost108** [comment]
sorry, didnt see this :(
