### ISSUE TITLE
DNS LEAK ADguard  bypass selected own "Upstream DNS servers"

### ISSUE THREAD

**Issue by klisza1993** [AdguardTeam/AdGuardHome#6037]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.34

### Action

I have notice that during configuring firewall "fortinet" i couldnt access internet. Started digging and issue is that, im using my own "Upstream DNS servers" with DoH and DoTLS, and somehow Adguard is bypassing my servers cuzing DNS LEAKE.
You can see logs from my firewall, and if i'll not pass"dns-family.adguard.com" then im cut off from internet, where im only allowing my own DNS mentioned before.. 
Solution to this was to disable protection i GUI, but is it ok, that it behaves  like this way..
screenshot of what i had to disable:
![agh3](https://github.com/AdguardTeam/AdGuardHome/assets/76993967/4c5daaac-9a27-4c20-b5b3-558a61946071)

Screenshot of potential dns Leak
![agh2](https://github.com/AdguardTeam/AdGuardHome/assets/76993967/0118f496-64b8-4ebe-aafb-a934d06b6662)

Screenshot of my own rule allowing only my desired DNSs - which isnt working.
![agh](https://github.com/AdguardTeam/AdGuardHome/assets/76993967/57d458dc-b47c-41a9-a633-22243176eec7)

### Expected result

...

### Actual result

..

**Comment by bayasdev** [comment]
Disable safe browsing nor parental control since it works by making DoH queries to Adguard DNS

**Comment by EvilBox** [comment]
Confirmed. Adguard is leaking. 
I did turn off features:
1. Safe browsing 
2. Parent control 
3. Safe search
4. and push "Disable protection" on Dashboard 

I wrote only my private DNS (without any cryptography, just classic dns) on "Upstream DNS servers"
and I get dns.adguard-dns.com domain in DNS Leak test

**Comment by klisza1993** [comment]
> Confirmed. Adguard is leaking. I did turn off features:
> 
> 1. Safe browsing
> 2. Parent control
> 3. Safe search
> 4. and push "Disable protection" button on Dashboard
> 
> I wrote only my private DNS (without any cryptography, just classic dns) on "Upstream DNS servers" and I get dns.adguard-dns.com domain in DNS Leak test
> 
> <img alt="Screenshot1" width="1008" src="https://user-images.githubusercontent.com/10662826/256210777-6f792008-a3f8-47d4-b778-7267b20f2483.png">

Ooh i had true.. is it mention in documentation simewhere? I did sesrch but didnt find.
