### ISSUE TITLE
Update check failed. Please check your Internet connection.

### ISSUE THREAD

**Issue by 301resa** [AdguardTeam/AdGuardHome#6038]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

AdGuard Home v0.107.34

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```
set static ip okay 

Rasbery pi 64X has internet but AdG doesnt update
Install 8 times using Ubuntu and RP X64  = same issue

### Expected result

fixed error

### Actual result

error presist 

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/62164313/4814f0f3-ae20-47d5-9aa0-441f4f1e9690)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/62164313/e1ecd0ce-e4ac-4dab-92e9-9d3522ac3aa2)

**Comment by 301resa** [comment]
Internet is working OK, i can SSH into the RP. all my programs that use internet are connected and working however Adguard fails to connect.

**Comment by reunionboy** [comment]
Hi,
I have the same installation and same problem. I try to reinstall older version like 107.33 and 107.32 and it the same problem.

**Comment by sadegh-askari** [comment]
same problem for me
any update?

**Comment by lutfor-diu** [comment]
same problem. latest build bug. i'm sure!

**Comment by 1sraphel** [comment]
Hi, same problem for me.
