### ISSUE TITLE
Unopened ad filters (DNS blacklist/whitelist) will occupy excess memory of Adguard Home.

### ISSUE THREAD

**Issue by xiaoyaoyaowww** [AdguardTeam/AdGuardHome#6039]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Unopened ad filters (DNS blacklist/whitelist) will occupy excess memory of Adguard Home.

### Proposed solution

Unenabled ad filters (DNS blacklist/whitelist) will not be written into the memory.

**Comment by Freebase394** [comment]
Could you please explain your point of view better, what you mean in more detail ...

**Comment by yaozijin** [comment]
> Could you please explain your point of view better, what you mean in more detail ...

Well, the issues has been changed.
