### ISSUE TITLE
Block and allow lists per device

### ISSUE THREAD

**Issue by rubenvarela** [AdguardTeam/AdGuardHome#6044]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I have a subscription to paramount+. 

Looking online, to make it work, I need to add a few domains to the allowlist, 

- https://www.reddit.com/r/pihole/comments/lxnjdg/paramountplus_pihole_whitelist/
- https://www.reddit.com/r/pihole/comments/nw2yht/has_anybody_figured_out_what_to_whitelist_for/
- https://github.com/schrebra/paramount.plus.whitelist
- https://github.com/f3bandit/paramount.plus.whitelist

Looking at the lists, it contains things like facebook, amazon ads, doubleclick, etc.

### Proposed solution

I only need this on one device. Since a request contains the address of the host asking for resolution, I propose we have a way of adding, per host, allow and block rules.

### Alternatives considered and additional information

Running another instance. Leaving the current one as the default propagated to device on the network and for the one device, set it's DNS server manually.

The con is that I have to add another instance just for this device. In my case, that's another VM to get another IP which is heavy on it's own vs managing it within the current instance.

**Comment by ainar-g** [comment]
@rubenvarela, sounds like either a use for the [`client` modifier](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#client) or a duplicate of #435?

**Comment by rubenvarela** [comment]
@ainar-g Dupe of #435. Thank you for pointing that one out.
