### ISSUE TITLE
Root (".") domain request does not drop even though it is on the disallowed domains list

### ISSUE THREAD

**Issue by cenk** [AdguardTeam/AdGuardHome#6049]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.633+5f8fa006

### Action

```sh
dietpi@ulasdietpi:~$ dig @10.0.0.15 .
; <<>> DiG 9.16.42-Raspbian <<>> @10.0.0.15 .
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62964
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;.                              IN      A
;; AUTHORITY SECTION:
.                       8512    IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2023072700 1800 900 604800 86400
;; Query time: 10 msec
;; SERVER: 10.0.0.15#53(10.0.0.15)
;; WHEN: Thu Jul 27 16:06:35 +03 2023
;; MSG SIZE  rcvd: 103
```

### Expected result

Drop request.

### Actual result

Resolving disallowed root (".") domain.

### Additional information and/or screenshots

![IMG_20230727_161059](https://github.com/AdguardTeam/AdGuardHome/assets/391865/b64aa7eb-6bde-4b84-be7a-68d199e73bcb)

Root (".") domain is resolving but others dropping.

**Comment by ainar-g** [comment]
Thanks for the report.  Please try version v0.108.0-a.635+79306cb4 or newer on the Edge channel.

**Comment by cenk** [comment]
Yes. Works with `|.^` on v0.108.0-a.635+79306cb4.
```shell
dietpi@ulasdietpi:~$ dig @10.0.0.15 .
; <<>> DiG 9.16.42-Raspbian <<>> @10.0.0.15 .
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
