### ISSUE TITLE
Add "Setup guide" menu item

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#605]
Here is what we show in the UI at the moment:
https://uploads.adguard.com/up04_b66dc_AdGuard_Home.png

This is not really useful to the users so I suggest making it a bit more helpful.

1. Replace "FAQ" with "Setup guide"
2. Click on the Setup guide opens the same guide we use in the first-run wizard
3. Regarding "address", in the case of multiple listen addresses specified in the status response, you should make it a dynamic link (dashed border button), and show all available addresses in a popover.

We'll need to discuss API changes required for this.

**Comment by szolin** [comment]
> 3. Regarding "address", in the case of multiple listen addresses specified in the status response, you should make it a dynamic link (dashed border button), and show all available addresses in a popover.

`"dns_address":"0.0.0.0"` -> `"dns_addresses":["127.0.0.1", "::1", ...]`
