### ISSUE TITLE
IPv4 in IPv6

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#6050]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.35

### Action

Я добавил запись в Перезапись DNS-запросов ::ffff:85.**.**.** но ожидаемый результат ответа не тот..

![1111111111](https://github.com/AdguardTeam/AdGuardHome/assets/46345396/694f2d66-7726-414b-889a-55939d5de3c3)
![2222222222222](https://github.com/AdguardTeam/AdGuardHome/assets/46345396/d3ca93aa-6c22-4a3e-8d0b-ca02b27714cd)

### Expected result

Ожидается что в ответе IPv6 то есть AAAA будет присутствовать IPv4

### Actual result

IPv4 дублируется в ответах игноря IPv6

**Comment by ainar-g** [comment]
@EugeneOne1, it's about time we've moved away from the old `net.IP` type both in the legacy rewrites and in the handling of `dnsrewrite` rules.

**Comment by EugeneOne1** [comment]
@Eyeborgs, hello again.  We've finally migrated to the new standard internal IP address representation, so this should be fixed in [v0.108.0-b.44](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.108.0-b.44).  Could you please check it out?  Thanks in advance.

**Comment by Eyeborgs** [comment]
@EugeneOne1 Hello, checked, works

**Comment by EugeneOne1** [comment]
@Eyeborgs, great, we'll close the for now.  Thanks for testing.
