### ISSUE TITLE
希望首页及查询时显示ipv4，ipv6客户端的ip地址对应的设备

### ISSUE THREAD

**Issue by liyiranlab** [AdguardTeam/AdGuardHome#6054]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

希望客户端更好确认，而不是一串串陌生的ip地址（v6，v4），ipv4还好一些，ipv6对于是那个客户端太麻烦。

### Proposed solution

希望 首页客户端排行 和 查询窗口 多一项客户端的名字。

### Alternatives considered and additional information

我发现 客户端设置>客户端（运行时间）中可以显示客户带名称。

**Comment by fernvenue** [comment]
Here you go: [AdGuard Home - Configuring clients](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients)

And make sure you **REALLY** checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer next time before you submit an issue!

**Comment by ppfeufer** [comment]
Also probably related » https://github.com/AdguardTeam/AdGuardHome/issues/6046

**Comment by liyiranlab** [comment]
不能自动添加名字吗？路由器的 DHCP分配 有客户端名字？

________________________________
发件人: fernvenue ***@***.***>
发送时间: 2023年7月30日 0:37
收件人: AdguardTeam/AdGuardHome ***@***.***>
抄送: liyiranlab ***@***.***>; Author ***@***.***>
主题: Re: [AdguardTeam/AdGuardHome] 希望首页及查询时显示ipv4，ipv6客户端的ip地址对应的设备 (Issue #6054)


Here you go: AdGuard Home - Configuring clients<https://github.com/AdguardTeam/AdGuardHome/wiki/Clients>

And make sure you REALLY checked the Wiki<https://github.com/AdguardTeam/AdGuardHome/wiki> and Discussions<https://github.com/AdguardTeam/AdGuardHome/discussions> and found no answer next time before you submit an issue!

―

**Comment by liyiranlab** [comment]
在 客户带>持久客户带 中添加mac地址 作为标识符，还是无法关联 IPV4 和 IPV6 地址

**Comment by liyiranlab** [comment]
好像临时ipv6地址是孤立的

**Comment by fernvenue** [comment]
> 在 客户端>持久客户端 中添加mac地址 作为标识符，还是无法关联 IPV4 和 IPV6 地址

Try to set DHCP static leases for these devices.

> 好像临时ipv6地址是孤立的

Make sure you use DHCPv6 with AdGuardHome, not SLAAC from your gateway.

**Comment by ainar-g** [comment]
What exactly is the feature request here?

**Comment by liyiranlab** [comment]
自动显示客户带名字。这个能实现吗？
________________________________
发件人: Ainar Garipov ***@***.***>
发送时间: 2023年8月1日 16:57
收件人: AdguardTeam/AdGuardHome ***@***.***>
抄送: liyiranlab ***@***.***>; Author ***@***.***>
主题: Re: [AdguardTeam/AdGuardHome] 希望首页及查询时显示ipv4，ipv6客户端的ip地址对应的设备 (Issue #6054)


What exactly is the feature request here?

―

**Comment by liyiranlab** [comment]
或者，在 客户端>持久客户端 中添加mac地址 作为标识符，能自动关联 IPV4 和 IPV6 地址显示客户的名字

**Comment by ainar-g** [comment]
Clients are already resolved with rDNS if you have enabled that option.  See the issue that ppfeufer has mentioned for a recent bug for which there is a fix on the Edge channel.  For recognizing clients without DHCP, see #961, but it's not an easy thing to do portably and reliably.

Seems like this issue is a duplicate.  If you need help debugging your configuration, please use [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a).
