### ISSUE TITLE
Log query cannot search for a specific string

### ISSUE THREAD

**Issue by Sakura-Luna** [AdguardTeam/AdGuardHome#6057]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.42

### Action

Search for "google.com" in the query log

### Expected result

Display the log of the corresponding domain name

### Actual result

Got an error `Error: control/querylog?search=google.com&response_status=&older_than=&limit=20 | Network Error`

![image](https://github.com/AdguardTeam/AdGuardHome/assets/53183413/5a479d9e-fa30-4d9a-8607-0ee4bb1f332d)

### Additional information and/or screenshots

This issue is not logged by the run log and has no other impact.

**Comment by ainar-g** [comment]
We cannot reproduce this issue.

> This issue is not logged by the run log and has no other impact.

Does that include the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?  Also, do you use some sort of reverse proxy, like Nginx?

**Comment by Sakura-Luna** [comment]
> We cannot reproduce this issue.
> 
> > This issue is not logged by the run log and has no other impact.
> 
> Does that include the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)? Also, do you use some sort of reverse proxy, like Nginx?

This is a javascript error, which looks unlikely to be logged. I tried checking the query log file and it seems there is no json format error.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/53183413/dfc21524-a64e-48bd-8268-0744d2593f47)

**Comment by ainar-g** [comment]
That JavaScript error is just a general error handler.  Please inspect the verbose log of AGH and of your proxy, if you use one.

**Comment by Sakura-Luna** [comment]
There are no records other than "info" level in the log, do I need to enable verbose?

**Comment by ainar-g** [comment]
Yes.  As previously stated, [verbose logs are enabled through the configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog).

**Comment by Sakura-Luna** [comment]
There are no records other than debug and info in the log, and there is no valid information when searching for the content that caused the error.

**Comment by Sakura-Luna** [comment]
Changing browsers resolved the issue, it appears to be a user-side conflict.
