### ISSUE TITLE
v0.93 Windows - Cannot specify absolute path in log_file

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#606]
I am trying to config AGH to generate a local log file rather than log to Windows Event Log by populating the log_file settnig in the config file. I can't seem to get it to work and everything permutation I try results in the AGH service not starting and an error being logged:

`yaml: line 70: found unknown escape character`

NOTE: The documentation for this setting states:
`log_file — Path to the log file. If empty, writes to stdout, if syslog -- system log (or eventlog on Windows).`
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration

### Steps to reproduce

1. Change log_file setting from "" to
2. log_file: "c:\install\AdGuardHome"
3. log_file: "c:\install\AdGuardHome\"
4. log_file: "c:\install\AdGuardHome\AGH.log"
none of which worked and all generated the above error.

What finally worked was "log_file: AGH.log"

Could I suggest either:
1. fixing the Wiki and remove the word 'path' and just say 'filename', OR
2. Fix AGH so you can actually put a path in the setting.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.93
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| Windows Server 2012 R2

**Comment by ameshkov** [comment]
try either `c:/install/AdGuardHome` or `c:\\install\\AdGuardHome`

**Comment by AnthonyBe** [comment]
Sorry, forgot to mention that I'd tried `c:/install/AdGuardHome` (I'm used to working with UNIX ports to Windows forgetting to change forward-slashes to back-slashes :)

Both `c:/install/AdGuardHome` and `c:\\install\\AdGuardHome` failed with same error as original post.

**Comment by ameshkov** [comment]
Yeah, on Windows there's an issue with specifying an absolute path which we should fix.

Even if you make it a valid YAML (by removing quotes or escaping `\`) it won't work anyway:
```
2019/02/27 15:06:56 cannot create a log file: open c:\AdGuardHome_v0.93_Windows\
c:\adguard.log: The filename, directory name, or volume label syntax is incorrec
t.
```
