### ISSUE TITLE
Contributor Schzhn

### ISSUE THREAD

**Issue by Siox0911** [AdguardTeam/AdGuardHome#6060]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

.29

### Action

No profile, no nothing. And he is allowed to publish cheerfully? And he intervenes decisively in the code? I am very confused!

### Expected result

Nothing

### Actual result

Most filter lists doesn't work.

### Additional information and/or screenshots

FreeBSD

**Comment by ameshkov** [comment]
@Siox0911 no worries, he's AdGuard employee.
