### ISSUE TITLE
Page height is always slightly too large

### ISSUE THREAD

**Issue by FugiMuffi** [AdguardTeam/AdGuardHome#6062]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.29

### Action

Log in to the web interface.

### Expected result

If the page content completely fits into the viewport, it should not be required to scroll to see the footer.

### Actual result

The footer is always slightly off-screen, even if the viewport is large enough.

### Additional information and/or screenshots

Installation: NixOS module

This is how it looks:
![Screenshot 2023-07-31 at 16-08-24 AdGuard Home](https://github.com/AdguardTeam/AdGuardHome/assets/21362942/4eada4fa-e875-4167-b7e8-d3ec0fed457a)

I have created a fix, if it's alright with you I can make a PR: 36ca30ab6042a2540704e4717bc2562a58bd0486

The same page with my fix applied:
![Screenshot 2023-07-31 at 16-10-41 AdGuard Home](https://github.com/AdguardTeam/AdGuardHome/assets/21362942/46b21f3c-5059-467e-9d31-ce64e2fadca3)

My change also elimitates the need for media queries in this case, it works on all screen sizes.

**Comment by ainar-g** [comment]
@IldarKamalov, please inspect if the fix interferes with some other issues.

**Comment by varunsripad** [comment]
Can i work on this

**Comment by ainar-g** [comment]
@FugiMuffi, we've committed a fix in the latest Edge build, v0.108.0-a.669+e1f6229e.  Could you please check?

**Comment by FugiMuffi** [comment]
I tested again using the latest edge build, it is fixed. Thanks!
