### ISSUE TITLE
Filter is applied after removal

### ISSUE THREAD

**Issue by talonric332** [AdguardTeam/AdGuardHome#6065]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.35

### Action

When removing a filter from the filters list, the query log shows that stuff is being blocked by an unknown filter.

### Expected result

The filter needs to stop blocking stuff and all query log items for that filter needs to be removed

### Actual result

The unknown filter shows up in the log

### Additional information and/or screenshots

![IMG_0463](https://github.com/AdguardTeam/AdGuardHome/assets/127520122/c7226217-2ed3-4537-94b0-e6940c4da91a)
![IMG_0462](https://github.com/AdguardTeam/AdGuardHome/assets/127520122/5f5f2e48-297e-4789-ac1e-dd2fae5dba35)

**Comment by ainar-g** [comment]
“Unknown filter 123” in the query log just means that the log has been deleted, and we don't have any information on it besides its internal ID (the 123 part).

Or are you implying that its rules keep being applied?  Because without the time when you've deleted the filter it's impossible to tell just from the screenshot.

**Comment by talonric332** [comment]
The rules for the game console Adblock list keep being applied after the removal. I don’t think it is a problem with the list itself but with AGH

**Comment by Mizzick** [comment]
Well it seems to be fine on my setup, I cannot reproduce this issue.

@talonric332 it could be useful if you run AdGuardHome with verbose logging enabled and check the logs output?

**Comment by talonric332** [comment]
I do update, add and remove block lists frequently.

**Comment by Mizzick** [comment]
It would be really helpful if we can see your [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?

Since this log may contain sensitive info, you may sent it to our [devteam@adguard.com](mailto:devteam@adguard.com).

**Comment by hubbsterx** [comment]
the same here.
I even deactivated ALL rules and an "unknown filter" still blocks some page. So it's a bug.

**Comment by hubbsterx** [comment]
it works after upgrade of dietpi. Maybe just the reboot solves the problem.
