### ISSUE TITLE
IPv4/IPv6 Preferred on Specifics Sub/Domain

### ISSUE THREAD

**Issue by rapdodge** [AdguardTeam/AdGuardHome#6066]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

My home network is dual-stack. And I've wanted to steer some sub/domain to just use IPv4/IPv6

### Proposed solution

I think it's nice to having custom filtering rules like dns rewrites.

Maybe it's nice to looks like this.

```
||upos-sz-mirroralibstar1.bilivideo.com^$forceaf=v4
||cloudflare.com^$forceaf=v6
```

*notes
af = address family

**Comment by ainar-g** [comment]
You can already do that by rewriting the `A` queries to be responded with a `NODATA` response.  For example, to force IPv6 on `www.google.com`:

```AdBlock
|www.google.com^$dnstype=A,dnsrewrite=NOERROR
```
