### ISSUE TITLE
Use different DNS servers for a list of domain (Feature request)

### ISSUE THREAD

**Issue by Ahhydri** [AdguardTeam/AdGuardHome#6069]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

is there a possibility to use different DNS server for the list of domains mention by the admin/user so that people using VPNs can route the no VPN traffic in better way.

Appreciate a positive response.

### Proposed solution

use different DNS server for the list of domains mention by the admin/user so that people using VPNs can route the no VPN traffic in better way.

**Comment by chatbuddy21** [comment]
This is already support right? On the upstream dns settings

e.g.
[/yahoo.com/]9.9.9.9
[/youtube.com/]8.8.8.8

**Comment by fernvenue** [comment]
Do you mean use different list for different user or just use different DNS servers for a list?
