### ISSUE TITLE
Add possibility to redirect a domain or add html code in blocked dns queries

### ISSUE THREAD

**Issue by CYAsistemas** [AdguardTeam/AdGuardHome#6070]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Actually there is not an option to add it in dns server configuration

![image](https://github.com/AdguardTeam/AdGuardHome/assets/140634218/93e85dba-5b6d-4a93-9c23-258a48e140b8)

### Proposed solution

Add possibility to redirect a domain or add html code (for show a pege like with adult content blocked) in blocked dns queries

**Comment by fernvenue** [comment]
Here you go: [How to show a custom block page?](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#customblock), make sure you really checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer next time before submit an issue.

**Comment by CYAsistemas** [comment]
Chromium engine had already support for RFC 8914
 https://chromium-review.googlesource.com/c/chromium/src/+/3760874

**Comment by ainar-g** [comment]
@CYAsistemas, please upvote #2261, which is the issue about EDE.
