### ISSUE TITLE
High CPU Usage when enabling DNS-over-TLS in Adguard Home

### ISSUE THREAD

**Issue by bennydiamond** [AdguardTeam/AdGuardHome#6076]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b.43 (currently) and v0.107.36

### Action

![Screenshot from 2023-08-02 20-07-02](https://github.com/AdguardTeam/AdGuardHome/assets/6563977/240f2495-e68d-4032-a9c3-2018d5136dc8)

Encryption enabled in AdguardHome Settings
DoT enabled. Port configured with value of 853.
Just idling A couple of request coming in from time to time, nothing excessive.

### Expected result

![Screenshot from 2023-08-02 20-15-53](https://github.com/AdguardTeam/AdGuardHome/assets/6563977/c7acd061-1bee-46d8-a628-5ea53809f3da)

Encryption enabled in AdguardHome Settings
DoT disabled. No value configured in "port" field.
Still idling just as before but this time, CPU usage is much more reasonable.

### Actual result

![Screenshot from 2023-08-02 20-07-02](https://github.com/AdguardTeam/AdGuardHome/assets/6563977/240f2495-e68d-4032-a9c3-2018d5136dc8)

When DoT is configured and enabled in Adguard Home, all CPU cores in the VM are at 100%.
When I disable DoT by removing the value in the field "DNS-over-TLS port", CPU usage returns to normal.

### Additional information and/or screenshots

CPU Intel N100
8GB DDR5-4800
256GB nVME SSD

Proxmox 8.0
VM running OPNSense 23.7

When DoT is disabled, CPU usage is normal. The rest of the "encryption settings" are active.

**Comment by bennydiamond** [comment]
I forgot to mention I have it set up with a certificate issued by Letsencrypt. Using a RSA-4096 key.

**Comment by ainar-g** [comment]
Hello.  You've mentioned that you're using a custom package?  Which package that is?

Also, are you seeing any excessive errors or warnings in the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?
