### ISSUE TITLE
Hope add "Reboot" and "Clear Log" button on the WEB UI

### ISSUE THREAD

**Issue by Zhijie327** [AdguardTeam/AdGuardHome#608]
1. Add a "Reboot" button on the home page
2. Add a "Clear Log" button between "Disable log" and "Download log file"

**Comment by Zhijie327** [comment]
Add something like Server Load Monitor？

**Comment by ameshkov** [comment]
Sorry for the delay.

I think we have a "clear log" feature request already.
What for "reboot", why would you need it?

**Comment by Zhijie327** [comment]
I think after the update process, a reboot can be better to apply its new feature. Or in another case, the problem of slow response due to the long running time may be solved by a reboot.

**Comment by ameshkov** [comment]
It does restart the DNS server internally every time you change settings.

**Comment by Zhijie327** [comment]
Alright, I got it.
