### ISSUE TITLE
I want to be able to specify the IP address of the DNS servers hostname.

### ISSUE THREAD

**Issue by yaozijin** [AdguardTeam/AdGuardHome#6083]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Some DNS (especially professional version DNS) may correspond to multiple IP addresses, some of which are not very fast, but these DNS addresses do not support direct use of IP (for example: https://1.12.34.56/dns-query), but only can use hostname (for example: your private ID.doh.pub).

### Proposed solution

So I hope Adguard Home can specify the IP address of DNS servers hostname.

### Alternatives considered and additional information

Use the following format.
encrypted [DNS-over-HTTPS]:
Use the same hostname.
https://unfiltered.adguard-dns.com:443/dns-query[Specify IP address 1(IPv4/IPv6)]
https://unfiltered.adguard-dns.com:443/dns-query[Specify IP address 2(IPv4/IPv6)]
https://unfiltered.adguard-dns.com:443/dns-query[Specify IP address 3(IPv4/IPv6)]

**Comment by ainar-g** [comment]
If what you're requesting is a way to assign an IP address to a hostname that can be used without a bootstrap server, you can already use /etc/hosts for that.  Is that what you're requesting?

**Comment by yaozijin** [comment]
> If what you're requesting is a way to assign an IP address to a hostname that can be used without a bootstrap server, you can already use /etc/hosts for that. Is that what you're requesting?

Not only that, this requesting has the advantage of being able to correspond the same hostname to multiple IPs.

**Comment by fernvenue** [comment]
@ainar-g AdGuardHome already supports to use `/etc/hosts` as bootstrap? Sounds great :)

**Comment by ainar-g** [comment]
@yaozijin, that sounds a lot like #5217, so merging into that one.

@fernvenue, it has been supported for quite some time, but we broke it for a few releases and then fixed it.  See #5902.
