### ISSUE TITLE
Error: control/access/list | Network Error

### ISSUE THREAD

**Issue by Darrex13** [AdguardTeam/AdGuardHome#6085]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

v0.107.36

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

That everything works smoothly

### Actual result

I could no longer reach my AdGuard Home and access the network

### Additional information and/or screenshots

debian

**Comment by ainar-g** [comment]
Please fill out the issue template.  In particular, which OS and installation method you've used and which errors you see in the browser's console and AGH's [verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog).
