### ISSUE TITLE
QUIC protocol does not work.

### ISSUE THREAD

**Issue by yeraycito** [AdguardTeam/AdGuardHome#6092]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.36

### Action

Adguard Home installed in Opnsense:

So far I have been using dns0.eu DNS via QUIC (quic://dns0.eu) without any problems but now they have stopped working, however Adguard DNS via QUIC (quic://unfiltered.adguard-dns.com) works without any problems.

### Expected result

![1](https://github.com/AdguardTeam/AdGuardHome/assets/65027248/9a993089-191b-496e-b81a-1cc966263439)

### Actual result

No working.

**Comment by ainar-g** [comment]
I cannot reproduce this.  Is the server available to you using a tool like [`dnslookup`](https://github.com/ameshkov/dnslookup)?

**Comment by yeraycito** [comment]
![2](https://github.com/AdguardTeam/AdGuardHome/assets/65027248/f1b7ae0a-478e-4a6c-a4ff-77910bd3cab9)

**Comment by yeraycito** [comment]
I am not allowed to test with quic

![2](https://github.com/AdguardTeam/AdGuardHome/assets/65027248/ef4bb9a3-801c-4d75-badf-fb2b0b6a6eec)

**Comment by yeraycito** [comment]
![3](https://github.com/AdguardTeam/AdGuardHome/assets/65027248/902ced92-3675-4c5c-9b7f-e1e2f1bbfbbd)

**Comment by yeraycito** [comment]
![4](https://github.com/AdguardTeam/AdGuardHome/assets/65027248/0cbafb74-bb0e-4b5c-8602-52cad62c8f83)

**Comment by yeraycito** [comment]
These servers work:

tls://dns0.eu
https://dns0.eu/
quic://unfiltered.adguard-dns.com

These do not work:

dns0.eu
quic://dns0.eu

**Comment by ainar-g** [comment]
> I am not allowed to test with quic

I don't understand, sorry.  The screenshots don't seem to add any useful information.  Are you able to use `dnslookup` to reach the server?  If you don't want to use the tool then [verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) could help you.
