### ISSUE TITLE
When I edit AdGuardHome.yaml about the log section it doesn't seem to take effect

### ISSUE THREAD

**Issue by MiKing233** [AdguardTeam/AdGuardHome#6093]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.36

### Action

我遇到一些問題, 發現AdGuardHome會無節制的向我的/tmp輸出log日志, 直到填滿我的/tmp, 這將導致其他相關服務停擺, 我瞭解到AdGuardHome的配置文件中可以對log輸出行爲進行設定

在我的/etc/AdGuardHome.yaml中, 我的log配置部分内容如下
```typescript
log:
  file: ""
  max_backups: 0
  max_size: 10
  max_age: 1
  compress: true
  local_time: true
  verbose: false
``` 
關於我瞭解到的内容
file: log文件的存放路徑
max_backups: 指定保留的日志文件备份数量
max_size: 指定日志文件的最大大小 (以MB为单位)
max_age: 指定日志文件的最长存储时间(以天为单位)
compress: 设置是否压缩日志文件
local_time: 指定是否使用本地时间记录日志
verbose: 指定日志记录的详细程度

### Expected result

對於目前我的log配置, 預期結果應爲:
log將默認輸出在/tmp/AdGuardHome.log
AdGuardHome將不保留log备份文件
日志文件的最大大小是100MB
日志文件最长存储1天
AdGuardHome將對log文件進行壓縮
AdGuardHome將使用本地时间记录log
详细日志是關閉的

### Actual result

但我實際看到的是, AdGuardHome仍然在以每100MB/個的大小對日志進行切割, 在/tmp中使用ll -h檢查如下
```typescript
-rw------- 1 root root 100.0M Aug 9 18:26 AdGuardHome-2023-08-09T10-26-10.364.log
-rw------- 1 root root 100.0M Aug 9 20:42 AdGuardHome-2023-08-09T12-42-34.702.log
-rw------- 1 root root 100.0M Aug 9 23:54 AdGuardHome-2023-08-09T15-54-29.918.log
-rw------- 1 root root 100.0M Aug 10 03:02 AdGuardHome-2023-08-09T19-02-24.025.log
-rw------- 1 root root 100.0M Aug 10 07:33 AdGuardHome-2023-08-09T23-33-22.349.log
-rw------- 1 root root 26.6M Aug 10 08:40 AdGuardHome.log
``` 
除了AdGuardHome.log是預期的log輸出檔案外, 我不清楚以上的幾個以100MB分割的log是如何被輸出的, 并且我已經在AdGuardHome.yaml中用於區分將max_size設定爲10 (MB), 但實際仍然以100MB來切割, 并且我還發現max_age參數也不生效, 它并不會只保留一天的log量, 即使我設定max_age: 1, 他仍然會一直如此輸出直至/tmp被寫入滿, 此外local_time似乎也沒有正常工作, 我已經制定爲了true但我檢查保存的log日志發現他并不是以我當前設備的時間來記錄的;

還有一些我不能確定是否在按預期工作的
verbose: false 我不確定是否禁用了详细记录日志的功能, 但我檢查log發現仍然有大量的[debug]被輸出, 我懷疑他沒有生效
compress: true 我不確定AdGuardHome是否真的對log進行了壓縮

經過我測試, 似乎只有這一個在正常工作
file: ""
當我輸入我的目標文件路徑后, 例如file: "/tmp/adgh.log", 啓動AdGuardHome, 它會被自動更改為file: /tmp/adgh.log (引號將被自動去除), 但實際結果是正確的, 它會被輸出在指定的路徑上

我有很多疑問, 爲何AdGuardHome.yaml中的log部分大多數都不按指定的設定進行?
我檢索了相關資料, 找到了一些内容, 在[How to configure AdGuard Home to write verbose-level logs?](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)中, 有如下的描述
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/92179192-3343-48d6-b8e6-1552f760f684)

指示在v0.107.34之後, 使用了類似與log.file和log.verbose的設定, 在Before v0.107.34 use verbose and log_file

對於我目前的v0.107.36, 我嘗試將AdGuardHome.yaml中的log部分修改爲了如下配置
```typescript
log:
  log.file: ""
  max_backups: 0
  max_size: 10
  max_age: 1
  compress: true
  local_time: true
  log.verbose: false
``` 
但當我運行AdGuardHome后, 再次檢查AdGuardHome.yaml, 發現已經被自動恢復原樣
```typescript
log:
  file: ""
  max_backups: 0
  max_size: 10
  max_age: 1
  compress: true
  local_time: true
  verbose: false
``` 

難道是我設定的方式不對嗎, 還是AdGuardHome本身的Bug導致的問題, 又或是之後的版本對這部分又進行了修改, 我要如何設定才能讓log按照我的要求進行輸出從而避免無節制的輸出使得/tmp被寫滿, 目前我只能透過每天手動刪除log檔案來維持設備的正常運作, 這個問題正困擾著我😵‍💫

**Comment by ainar-g** [comment]
`log.file` means “property `file` of object `log`”, and the properties aren't applied when you don't set the `file`.  But there also seems to be a bug regarding the other log settings.

@Mizzick, please investigate.

**Comment by Mizzick** [comment]
Indeed, there is a bug to fix, I can reproduce it.

**Comment by Mizzick** [comment]
Please check the edge channel, we have published `v0.108.0-a.651+85e87b9c` with the fix for this issue.

**Comment by ainar-g** [comment]
We'll close the issue for now.  Please feel free to reopen if you find that the fix didn't work.

**Comment by a904055262** [comment]
> We'll close the issue for now. Please feel free to reopen if you find that the fix didn't work.

"max_size" Can it be added to querylog selection?
