### ISSUE TITLE
遇到一个很奇怪的问题，解析没有响应

### ISSUE THREAD

**Issue by DreamsCat** [AdguardTeam/AdGuardHome#6095]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.32

### Action

我在本机 docker 搭建了一个 AdGuardHome，之前试着一直没有问题。但是今天遇到一个问题：
我本地尝试 dig @127.0.0.1 nssurge.com ，一直返回没有结果。

我尝试去控制台查看日志，发现一直没有解析 nssurge.com 的日志，我尝试把 AdGuardHome 关闭后再运行 dig @127.0.0.1 nssurge.com ，就会返回没有服务响应，所以应该是走了 AdGuardHome 的，但是为啥解析了，但是又没有记录日志呢？

### Expected result

正常解析

### Actual result

正常解析

**Comment by ainar-g** [comment]
1.  Please use English in titles so that it's easier for people to find duplicates.
2.  v0.107.32 is an older version.  Have you tried the more recent builds?
3.  Have you enabled [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?  If so, what exactly do you see when you make the query?

**Comment by DreamsCat** [comment]
Thank you, this problem is caused by not setting the proxy, thank you~

**Comment by ainar-g** [comment]
Do you want to say that the issue is resolved?

**Comment by DreamsCat** [comment]
> Do you want to say that the issue is resolved?

yes
