### ISSUE TITLE
Specifying UDP resolvers with hostnames broken in edge release

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#6103]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)
- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)
Linux, ARM64

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.108.0-a.650+c54635e8

### Action

Adding an upstream server with `udp://<HOSTNAME>` scheme does not work in the latest edge build.

### Expected result

For it to be added successfully

### Actual result

Server cannot be added:

<img width="376" alt="Screenshot" src="https://github.com/AdguardTeam/AdGuardHome/assets/19761269/141d7cf7-9cbd-4fd6-a515-d7dd499ca8f2">

### Additional information and/or screenshots

I can add the IP address directly and I've verified that the hostname resolution works inside the Docker container.

**Comment by ainar-g** [comment]
I cannot reproduce this.  I've tried:

* `udp://` with an IP address;
* `udp://` with a publicly available hostname;
* `udp://` with a hostname from `/etc/hosts`;

To clarify:

1. Is `pdns` a real hostname in your case?  If so, where is it defined?

2. Are there any clues in the verbose logs?

3. As you've mentioned Docker, is something like `dig IN A 'www.example.com' @pdns` works from within the container?

**Comment by agneevX** [comment]
> 3\. As you've mentioned Docker, is something like `dig IN A 'www.example.com' @pdns` works from within the container?

This does not work as the binary is not installed but a ping works:

<img width="594" alt="Screenshot 2023-08-14 at 6 55 10 PM" src="https://github.com/AdguardTeam/AdGuardHome/assets/19761269/9b7a5ffa-267d-4db9-b0ed-75df7b3c8ebe">

**Comment by agneevX** [comment]
Should note that `pdns` is a Docker container attached to a common network.

**Comment by agneevX** [comment]
> Does the resolving still work on v0.107.36?

I am not able to test this due to schema changes. Have there been changes to the base image at all? Seems like this is a Container/OS thing since it cannot reach other clients in the network.

**Comment by ainar-g** [comment]
Sorry, I haven't noticed that you were on the Edge channel already.  Then, the latest Edge or the latest Beta could work, as there were changes to how `/etc/hosts` is being processed.  Also the answers to the other two questions would also help.

**Comment by agneevX** [comment]
Thanks for getting back, I'll will try to provide an update as soon as I can.

**Comment by mlincett** [comment]
You don't mention which was the last working version for you, so this may not be relevant: but since this is a docker setup did you ensure you have `127.0.0.11:53` on upstream servers? I remember this became necessary in order to use docker hostnames some time ago.

**Comment by agneevX** [comment]
This has been fixed.

**Comment by agneevX** [comment]
This is still an issue with v0.107.40 unfortunately.

![Screenshot](https://github.com/AdguardTeam/AdGuardHome/assets/19761269/a8a2204c-0af3-497b-9e66-205a4686568e)

![Screenshot 2](https://github.com/AdguardTeam/AdGuardHome/assets/19761269/96c06992-7079-4093-9ecf-f6cf92fd5b31)

**Comment by ainar-g** [comment]
@agneevX, did you set `127.0.0.11` (or what is the address for Docker's own resolver these days) as the upstream for top-level domains?  E.g.:

```none
…
[//]127.0.0.11
```

Also, what errors are the in the verbose log of the check?

**Comment by agneevX** [comment]
> [//]127.0.0.11

This does not work either.

I will get a verbose log shortly.

**Comment by overwatch3560** [comment]
were you able to send the verbose logs? @agneevX

**Comment by agneevX** [comment]
This is still the case as of v.48.

Easy way to repro is to set up AGH and a dnsproxy container in the same Docker network and add `udp://dnsproxy` as an upstream resolver and test
