### ISSUE TITLE
Use EDNS (ECS) to identify Clients

### ISSUE THREAD

**Issue by Echelon101** [AdguardTeam/AdGuardHome#6104]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I'm migrating from pi-hole to adguard and my current setup forwards all dns requests via my gateway to adgaurd. I was able to get client IPs on pi-hole after I configured edns for dnsmasq on opnsense.
The following options are set in my dnsmaq config;
`add-mac
add-subnet=32,128`

unfortunately adguard doesn't recognize the extra information to split clients in the UI.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/22678948/d7a12448-67b9-40c8-b34b-e3ccd2ecd854)

### Proposed solution

Parse EDNS Information from clients in local network. Display IP's from edns to seperate client requests in UI

### Alternatives considered and additional information

Add DNS Server to DHCP options -> I know that that is the easy solution. But I like the config via my gateway because if I change the DNS Server the change is instant and I don't need to remember what IP my DNS server has if I configure static IPs on devices

**Comment by ainar-g** [comment]
Merging into #4383.
