### ISSUE TITLE
List automatically updates new time periods

### ISSUE THREAD

**Issue by duckxx** [AdguardTeam/AdGuardHome#6105]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

The  list is automatically updated by adding 6 hours or customizing any time period.

### Proposed solution

The  list is automatically updated by adding 6 hours or customizing any time period.

**Comment by ainar-g** [comment]
What exactly do you mean by “suggestion list”?

**Comment by duckxx** [comment]
> What exactly do you mean by “suggestion list”?

是黑/白名单自动更新，新增6小时或自定义任意时段。自定义任意时段更新这样可以充分在闲事更新规则库，避免更新时出现占用服务器负载导致解析高延迟问题。新增6小时自动更新是让多规则库的用户更加充分更新，一天更新4次，因为规则列表在任意时段都可能会更新。

![Screenshot_20230814_211538](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/8791d6dd-eee7-409a-aad9-baeb86c00d23)

**Comment by woyaozuoai** [comment]
> “建议清单”到底是什么意思？

Should be adding custom update rule time

**Comment by ainar-g** [comment]
I see, thanks.  Merging into #3044.
