### ISSUE TITLE
Encountered a panic when using the update command

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#6106]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.651+85e87b9c

### Action

```sh
.\AdGuardHome.exe --update;
```

### Expected result

Check for updates and update if there are any.

### Actual result

```log
2023/08/15 08:25:49.870951 [info] AdGuard Home, version v0.108.0-a.651+85e87b9c
2023/08/15 08:25:49.889996 [info] tls: using default ciphers
2023/08/15 08:25:49.891004 [info] safesearch default: disabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x108 pc=0x72ac1c]

goroutine 1 [running]:
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).prepareUpstreamConfig(0xc000570580, {0xc000582180?, 0x200000003?, 0x0?}, {0x1a3be60, 0x1, 0x1}, 0xc0000c8d60?)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/upstreams.go:97 +0x1dc
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).prepareUpstreamSettings(0xc000570580)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/upstreams.go:52 +0x225
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).Prepare(0xc000570580, 0x0?)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dnsforward.go:549 +0x185
github.com/AdguardTeam/AdGuardHome/internal/home.initDNSServer(0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x6e3ca?, 0xc0000c9610)
        github.com/AdguardTeam/AdGuardHome/internal/home/dns.go:160 +0x2d8
github.com/AdguardTeam/AdGuardHome/internal/home.cmdlineUpdate({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:904 +0x85
github.com/AdguardTeam/AdGuardHome/internal/home.run({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:557 +0x625
github.com/AdguardTeam/AdGuardHome/internal/home.Main({0x1518ba0, 0x152ef40})
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:126 +0x228
main.main()
        github.com/AdguardTeam/AdGuardHome/main.go:19 +0x27
```

### Additional information and/or screenshots

I encountered the same situation on two computers.

**Comment by schzhn** [comment]
We've pushed the edge release containing the fix.

**Comment by bestpika** [comment]
Currently, there are no issues after manually updating and running `–update`!
