### ISSUE TITLE
Add export/import all configuration in general settings

### ISSUE THREAD

**Issue by CYAsistemas** [AdguardTeam/AdGuardHome#6113]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

There is no option to export/import all settings, it is useful in containers, especially mikrotik router, because to update adguard we need to recreate the container and lose all settings (filters, lists, logs, etc.)

### Proposed solution

Add an option for that in general settings.

**Comment by ainar-g** [comment]
Duplicate of #1147
