### ISSUE TITLE
MATCH  DOESN'T WORKS (word: banner) AT URLS

### ISSUE THREAD

**Issue by nandish486** [AdguardTeam/AdGuardHome#6118]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

0.107.36

### Action

on website: that is https://adblock-tester.com/banners/pr_advertising_ads_banner.png

i put in filters a custom filter : /(ads_|ads|ads |)banner/

on testing it , it says blocked but still not gets blocked, 

dns : dns.kingx.dev

### Expected result

TO BLOCK URLS CONTAING MATCH

### Actual result

![Screenshot (1834)](https://github.com/AdguardTeam/AdGuardHome/assets/93249676/627c1ae0-a167-4c79-ba6f-3410ba2b754e)
![Screenshot (1835)](https://github.com/AdguardTeam/AdGuardHome/assets/93249676/3abae93c-51b9-4c9b-8f66-54287d061a4d)

### Additional information and/or screenshots

MY ALL CONFIGS ARE WORKING PROPRERLY,

and it is quiet blocking good

**Comment by fernvenue** [comment]
As [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#limitations) said:

> Essentially, any advertising that shares a domain with content cannot be blocked by a DNS-level blocker.

So you can't block this, because AdGuardHome is working on DNS level, you may need uBlock or something like that.

**Comment by nandish486** [comment]
> 

But then how shall I do it with dns level adblocker to filter urls, because ublock origin or the adguard app must be installed to each and every device for that,


I just want to block urls containing match

**Comment by fernvenue** [comment]
As above, you can't, any other DNS level blocker also can't do that.
