### ISSUE TITLE
Prevent HTTPS queries responding IPv6 addresses

### ISSUE THREAD

**Issue by starryloki** [AdguardTeam/AdGuardHome#6122]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.36

### Action

Example:
```sh
nslookup -debug -type=type65 'cdn.v2ex.com' '$YOUR_AGH_ADDRESS'
```
I have turned on `Disable resolving of IPv6 addresses`. 

### Expected result

`HTTPS: 1 . alpn="h3,h2" ipv4hint="104.20.9.218,104.20.10.218,172.67.3.188"`

### Actual result

In AdGuard Home, I checked the DNS resolution records and found that the corresponding response is as follows: 
`HTTPS: 1 . alpn="h3,h2" ipv4hint="104.20.9.218,104.20.10.218,172.67.3.188" ipv6hint="2606:4700:10::6814:9da,2606:4700:10::6814:ada,2606:4700:10::ac43:3bc" `

Just as described in "Disable resolving of IPv6 addresses", enabling it should result in blocking all IPv6 addresses, but it seems that only AAAA records are being blocked and not the IPv6 addresses within HTTPS records.
It appears that using HTTPS records allows for bypassing the restrictions on IPv6 resolution.

**Comment by ipv4dns** [comment]
丢弃所有 IPv6 地址 (AAAA) 的 DNS 查询。已经写明禁用是aaaa记录，你那个是HTTPS记录。是直接解析aaaa的记录。

**Comment by duckxx** [comment]
但是注释那里写的是：丢弃所有 IPv6 地址 (AAAA) 的 DNS 查询。
是禁止直接解析aaaa的记录，不包括HTTPS记录。

**Comment by starryloki** [comment]
> 但是注释那里写的是：丢弃所有 IPv6 地址 (AAAA) 的 DNS 查询。
> 是禁止直接解析aaaa的记录，不包括HTTPS记录。

I know that the comments have already provided an explanation. However, disabling AAAA records is a means to prevent IPv6 resolution. It is clear that with the widespread use of HTTPS records, this method is no longer effective in blocking IPv6 resolution. Therefore, it is necessary to update this option or similar filtering rules to address it.

**Comment by fernvenue** [comment]
Totally agree with @starryloki, just disable AAAA records seems not enough.

**Comment by Mizzick** [comment]
Please have a look, we have implemented the requested changes.
The new build version `v0.108.0-a.657+cb6d4620` has been just published to the edge channel.
