### ISSUE TITLE
'http://' is displayed in the query log

### ISSUE THREAD

**Issue by duckxx** [AdguardTeam/AdGuardHome#6124]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

107.36

### Action

在查询日志中发现了异常。
An exception was found in the query log Procedure.

![Screenshot_20230821_002007](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/e85056d0-e2fd-45a9-a468-0198ddc0e860)

![Screenshot_20230821_002035](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/68b1b122-9fc2-4756-be63-b8c574aa87a8)

![Screenshot_20230821_002210](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/643f70f2-7b57-479d-b32d-41c786de53f8)

![Screenshot_20230821_002256](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/a61c6fe4-12bf-4aba-90af-e9e68da56c16)

### Expected result

domain.com

### Actual result

http://domain.com
http://domain.com/ads
domain.com/ads
https://domain.com:8080/ads

**Comment by fernvenue** [comment]
They are application's behavior, nothing wrong with AdGuardHome, you can just ignore them.

**Comment by nandish486** [comment]
Man you are getting complete urls, how is that possible, if u think it is error or else, let me tell u that it is blessings, u can block banner ads etc or YouTube ads completely,

Please inbox me i want to know how u did da?

T.me/kslaver instagram.com/kingx.dev 

Mail: nandishchauhan.ssstd9@gmail.com

**Comment by ainar-g** [comment]
As @fernvenue said, these are most likely queries from misconfigured applications trying to resolve the URL scheme as a part of a domain name, à la `dig 'http://www.example.com' @1.1.1.1`.  Most of these are invalid, and you can block such queries using a regular expression.

**Comment by nandish486** [comment]
> As @fernvenue said, these are most likely queries from misconfigured applications trying to resolve the URL scheme as a part of a domain name, à la `dig 'http://www.example.com' @1.1.1.1`. Most of these are invalid, and you can block such queries using a regular expression.

How to generate this type of thing in my server, please tell me. As the thread said it can't be done but yet it's .

**Comment by ainar-g** [comment]
@nandish486, I'm not sure I understand.  If you want to generate invalid DNS queries, I've already provided a `dig` command in the previous message.  If you want actual content filtering, AGH isn't able to do that yet.

**Comment by duckxx** [comment]
这种也是吗？
![Screenshot_20230822_223221](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/f446c548-9606-4c1d-92db-82e41ab175d2)

**Comment by nandish486** [comment]
> 这种也是吗？ ![Screenshot_20230822_223221](https://user-images.githubusercontent.com/116968444/262388667-f446c548-9606-4c1d-92db-82e41ab175d2.jpg)

what browser are u using
