### ISSUE TITLE
Unable to unblock a website which is blocked by parental control

### ISSUE THREAD

**Issue by m8522s** [AdguardTeam/AdGuardHome#6128]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.36

### Action

Parental control blocks a website, which I want to unblock using _Custom filtering rules_.
My rule to unblock the sample site `de.triumph.com` is:
```
@@||de.triumph.com^
```

### Expected result

I expect, that the site is permitted and the log message is `Allowed, Custom filtering rules`.

### Actual result

The site is still blocked. The log file still says: `Blocked by Parental control`.
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/43844394/411a08a6-888e-4d5c-ae17-75d01dd9d0af)

**Comment by ainar-g** [comment]
I cannot reproduce this, see the screenshot for before and after applying the exact rule.

![Screenshot from 2023-08-22 13-45-32](https://github.com/AdguardTeam/AdGuardHome/assets/4964986/a3375a89-af14-4987-bc06-398d9a938e70)

Are you able to see the difference when using e.g. `dig`?
