### ISSUE TITLE
As long as the router is restarted and the domain name is opened, the response time will increase

### ISSUE THREAD

**Issue by woyaozuoai** [AdguardTeam/AdGuardHome#6129]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

OpenBSD, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.36

### Action

As long as the router is restarted and the domain name is opened, the response time will increase

### Expected result

Directly retrieve cache information after restarting the router

### Actual result

![QQ截图20230822183904](https://github.com/AdguardTeam/AdGuardHome/assets/68744668/cae4b0fd-2873-489c-bda7-4740905f71f6)

### Additional information and/or screenshots

![QQ截图20230822183904](https://github.com/AdguardTeam/AdGuardHome/assets/68744668/5a843f01-1f02-4aaf-91c1-7d1277536854)

**Comment by ainar-g** [comment]
If I understood you correctly, what you want is a persistent cache, which is #3859.  If it is not, please elaborate on your request, in any language you're comfortable with.
