### ISSUE TITLE
Adding CNAME Flattening Feature in AdGuard Home

### ISSUE THREAD

**Issue by ttimochan** [AdguardTeam/AdGuardHome#6137]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I believe that the CNAME flattening option could be made available for users who are seeking optimal performance. In typical scenarios, CDN often employ one or multiple CNAME records. Flattening these records could reduce the number of iterative queries, thereby potentially accelerating AdGuard Home's response speed. I find this feature to be highly anticipated and promising.

### Proposed solution

I believe it would be possible to directly cache the ultimate domain name after it has undergone multiple iterative queries. The caching of this domain name could adhere to the minimum TTL set by the user's caching preferences. Could this be considered as a part of the caching functionality?

**Comment by ainar-g** [comment]
Merging into #2559.  The previous title there had a typo, which is probably why finding it was harder.
