### ISSUE TITLE
Feature Request: Load-balancing strategy

### ISSUE THREAD

**Issue by evilvibes** [AdguardTeam/AdGuardHome#614]
This would be a good feature for users using two or more Upstream DNS servers.

[Load Balancing Options](https://github.com/jedisct1/dnscrypt-proxy/wiki/Load-Balancing-Options)

**Comment by ameshkov** [comment]
The current implementation is the same as `fastest` from that list.

Tbh, I am not convinced that there should be a choice of different strategies. I'd prefer to have one that covers most of the use-cases. The question is whether `fastest` is better than other options or not.

**Comment by ibksturm** [comment]
i think it's for some privacy reason 

similar thinking like i wrote on [https://github.com/AdguardTeam/AdGuardHome/issues/790](https://github.com/AdguardTeam/AdGuardHome/issues/790)

share the request's over 2+n resolvers would be more privacy than over one single... so none of the servers got all your request
