### ISSUE TITLE
control/stats/config/update | ignored: at index 1: hostname is empty

### ISSUE THREAD

**Issue by g0dz1** [AdguardTeam/AdGuardHome#6140]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

версия:  v0.108.0-b.44

### Action

enter "startup.mobile.yandex.net"

### Expected result

save

### Actual result

Error: control/stats/config/update | ignored: at index 1: hostname is empty | 422

### Additional information and/or screenshots

![chrome_eWMFT4W53m](https://github.com/AdguardTeam/AdGuardHome/assets/48619661/5e72cc51-0044-455c-9b33-eadfdcbace1b)

**Comment by ainar-g** [comment]
@IldarKamalov, looks like the front-end doesn't strip empty lines from the input.

**Comment by g0dz1** [comment]
> @ainar-g Yes, sure. Thanks!
