### ISSUE TITLE
Add an option to set the TTL of blocked domains

### ISSUE THREAD

**Issue by RWTighnari** [AdguardTeam/AdGuardHome#6147]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

TTL settings do not apply to blocked domains.

### Proposed solution

Add an option to set the TTL of blocked domains.

**Comment by RWTighnari** [comment]
Thanks for your reply. I hope to add a GUI interface on the web instead of configuring it in a file, which would be more convenient.

**Comment by ainar-g** [comment]
See/upvote #4569.
