### ISSUE TITLE
Add UI BG Language translation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#615]
https://github.com/AdguardTeam/AdGuardHome/pull/612

1. [x] Upload translated strings to oneskyapp
2. [x] Add the new UI language
3. [x] Close that pull request once the work is done

**Comment by IldarKamalov** [comment]
Added: https://github.com/AdguardTeam/AdGuardHome/commit/10fcfefcfd7220d68880cd735a3844ec4e617555
