### ISSUE TITLE
Website `premierfsdo.com` won't load with AdGuard 

### ISSUE THREAD

**Issue by wizzard007** [AdguardTeam/AdGuardHome#6151]
I am using AdGuard home. I have been having issues accessing https://premierfsdo.com/desktop/home. The website would load but only a white background and nothing else. The only way to access the website is to disable the AdGuard completely.

When I tried to add the site to Allowlist, I got "Error: control/filtering/add_url | Couldn't fetch filter from URL "https://premierfsdo.com/desktop/home": data is HTML, not plain text | 400"

**Comment by ainar-g** [comment]
That input is for pasting the addresses of allowlists.  AdGuard Home works on the DNS level, not URL level.  If you think that AdGuard Home is blocking your query, you can add an exception rule from the query log.

**Comment by wizzard007** [comment]
> That input is for pasting the addresses of allowlists. AdGuard Home works on the DNS level, not URL level. If you think that AdGuard Home is blocking your query, you can add an exception rule from the query log.

So why does the website load fine after I disable the AdGuard?
