### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#6158]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.675+18d15be4

### Action

```sh
.\adguardHome.exe --update
```

### Expected result

Check for updates. If there are updates, then update. If not, then exit.

### Actual result

Clearly, after this update, I have encountered the same issue as #6106 again.
In addition to that, I have also observed some phenomena, such as getting stuck when using `-s restart`.

### Additional information and/or screenshots

```sh
2023/08/31 11:38:41.267488 [info] AdGuard Home, version v0.108.0-a.675+18d15be4
2023/08/31 11:38:41.285819 [info] tls: using default ciphers
2023/08/31 11:38:41.287327 [info] safesearch default: disabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xe8 pc=0x153fb1b]

goroutine 1 [running]:
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).Prepare(0xc000598000, 0x0?)
        github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dnsforward.go:546 +0x7b
github.com/AdguardTeam/AdGuardHome/internal/home.initDNSServer(0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0xe9e3ca?, 0xc000145600)
        github.com/AdguardTeam/AdGuardHome/internal/home/dns.go:159 +0x2d8
github.com/AdguardTeam/AdGuardHome/internal/home.cmdlineUpdate({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:918 +0x85
github.com/AdguardTeam/AdGuardHome/internal/home.run({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:571 +0x6c5
github.com/AdguardTeam/AdGuardHome/internal/home.Main({0x23695a0, 0x237f940})
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:130 +0x270
main.main()
        github.com/AdguardTeam/AdGuardHome/main.go:19 +0x27
```

**Comment by schzhn** [comment]
Hello, @bestpika.
Thank you for the report. We are looking into it.

**Comment by schzhn** [comment]
We've pushed the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) containing the fixes.

**Comment by bestpika** [comment]
After manually updating, there are currently no issues. I hope it doesn’t happen again in a few days.
