### ISSUE TITLE
Enhanced CSS style in Dark Mode for Query Log page

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#6160]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Please enhance the Query Log page's dark mode styling.

Currently links in the Client column are near illegible.

e.g.

![example](https://github.com/AdguardTeam/AdGuardHome/assets/17044982/cf07dd73-14b0-4cb9-984e-59a4025b29e9)

### Proposed solution

Please enhance the Query Log page's dark mode styling to have legible text and a proper hover state for links (considering the colored category of the item).

**Comment by ainar-g** [comment]
Which version are you using?  The latest Beta doesn't have this kind of grey background for clients in the query log.

![Screenshot at 2023-09-01 12-59-11](https://github.com/AdguardTeam/AdGuardHome/assets/4964986/68631712-9b4d-4c45-9614-659246e415d6)

**Comment by hl2guide** [comment]
> Which version are you using? The latest Beta doesn't have this kind of grey background for clients in the query log.
> 
> ![Screenshot at 2023-09-01 12-59-11](https://user-images.githubusercontent.com/4964986/264990420-68631712-9b4d-4c45-9614-659246e415d6.png)

Version: v0.107.36

The green background entries appear in the "All queries" and "Filtered" filtered views.

**Comment by ainar-g** [comment]
Ah, I see now, thanks.

@IldarKamalov, I think we should use the same white text there, like we already do for allowed requests.  That should fix the contrast.

**Comment by ainar-g** [comment]
Should be fixed in the latest releases.
