### ISSUE TITLE
[i18n] Migrate to the Crowdin platform

### ISSUE THREAD

**Issue by MS-PC** [AdguardTeam/AdGuardHome#617]
@ameshkov
It seems that once I saw a comment about the migration to Crowdin, my question when it will be?. I could also contribute with the Adguard Home translation and if I had more time I would help with the other AdGuard products. This request is because some translations are very literal and do not make sense.

And if you agree me to as proofreader, it's up to you.

**Comment by ameshkov** [comment]
Well, we anyway will migrate all the existing translations to Crowdin as well so if you use oneskyapp, it won't be lost. We want to migrate everything at once, and it makes the task pretty complicated, maybe in a couple of months we'll be finally able to do it.

**Comment by MS-PC** [comment]
@ameshkov
You could assign me as proofreader/moderator and thus approve the correct translations. I already translated and corrected several lines in the AdGuard Home project.

**Comment by ameshkov** [comment]
@MS-PC paging @aalpatkina she can do it. Could you please tell her your details?

**Comment by MS-PC** [comment]
@ameshkov
I prefer not to give any details, for personal reasons. I only say that my translations are be reviewed and/or approved. Thanks.

**Comment by ameshkov** [comment]
> I prefer not to give any details, for personal reasons. I only say that my translations are be reviewed and/or approved. Thanks.

By details I mean your username on oneskyapp so that she could grant you the proofreader/moderator role :) Her email is `aalpatkina at adguard.com`

**Comment by MS-PC** [comment]
>By details I mean your username on oneskyapp so that she could grant you the proofreader/moderator role :) Her email is `aalpatkina at adguard.com`

So that this conversation does not get longer, my nickname in `oneskyapp` is the same that I use in GitHub, and about the email for personal reasons I will not provide it. My goal is not to collaborate to obtain rewards/licenses by `adguard.com`, it is only so that the people who speak my language understand it. I only say that my translations are be reviewed and/or approved. Thanks.

`AdGuard Home` is a product that I use and that's why I want to help with its translation of it.

**Comment by ameshkov** [comment]
@aalpatkina please assist.

@MS-PC Spanish language, right?

**Comment by aalpatkina** [comment]
@MS-PC now you have a moderator's access. You can check and approve/disapprove translations. 
Please do not click on "Finalize" button after approval.

For further information, please contact me at aalpatkina@adguard.com

**Comment by MS-PC** [comment]
>MS-PC now you have a moderator's access. You can check and approve/disapprove translations.
Please do not click on "Finalize" button after approval.

@aalpatkina could review who you gave her access as a moderator?, my profile does not have access as a moderator.

>MS-PC Spanish language, right?

Yes, my language is Spanish.

I can not waste more time in this conversation, it depends on you, if you approve or disapprove my translations, if you give me access as a moderator or not. In the meantime, I will collaborate with the translation of `AdGuard Home`.

**Comment by aalpatkina** [comment]
@MS-PC that's weird. Is this your account shown on the screenshot?

![up17k7eaj](https://user-images.githubusercontent.com/31620257/54980565-29c69380-4fb7-11e9-8f5f-52dc6986c531.png)

**Comment by MS-PC** [comment]
@aalpatkina 2 things may have happened:
1.- It may be an account that I created a long time ago, how strange, since I asked them to delete that account, and OneSky confirmed that it was deleted. But the profile is still visible?
2.- That someone has created a profile equal to the one I have on GitHub.

In addition to this, this does not happen in **Crowdin**, that a profile can appear twice.
This is my profile, without image **(I will delete this comment after you read it)**: https://adguard.oneskyapp.com/account/profile/644502

**Comment by aalpatkina** [comment]
@MS-PC please check the account you specified. I've just changed your status to "moderator" there.
So now you can delete your comment :)

**Comment by MS-PC** [comment]
@aalpatkina I would be grateful if you would assign me as proofreader for the Spanish language in the "AdGuard Websites", "AdGuard Applications" and "AdGuard Glossary" projects, since they are now in Crowdin. Thanks.

(As I said before, please do not respond since I will delete this comment and thus not lengthen this thread, please react with a thumb up to know what is done.)
