### ISSUE TITLE
No comments in Bootstrap DNS servers field

### ISSUE THREAD

**Issue by saint-lascivious** [AdguardTeam/AdGuardHome#6173]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

93d7be1

### Action

Attempted to use comments in Bootstrap DNS servers field.

```
# comment test one
192.168.1.10:5335
# comment test two
192.168.1.20:5335
```

### Expected result

Comments accepted in Bootstrap DNS servers field (and preferably for all comments to be handled uniformly in terms of styling for all fields).

### Actual result

Comments rejected in Bootstrap DNS servers field.

```
Error: control/dns_config | checking bootstrap # comment test one: invalid address: bootstrap # comment test one:53: ParseAddr("# comment test one"): unable to parse IP | 400
```

### Additional information and/or screenshots

Self build of 93d7be1, personal AGH instances behind `dnsdist` on aarch64 Ubuntu Server 23.04.

Upstream, Fallback, Custom etc. DNS server fields all accept comments (though only Upstreams features comments styled in grey). The Boostrap DNS servers field appears to be parsed differently.

**Comment by ainar-g** [comment]
Merging into #6126.
