### ISSUE TITLE
Upstream DNS servers can not use ipv6 doh/dot servers

### ISSUE THREAD

**Issue by cyouhi** [AdguardTeam/AdGuardHome#6175]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.36

### Action

When setting the server address in the upstream DNS to https://2400:3200::1/dns-query or https://[2400:3200::1]/dns-query, an error occurs

An error is also reported when setting tls://2400:3200::1 or tls://[2400:3200::1]

### Expected result

no error

### Actual result

Server "https://[2400:3200::1]/dns-query": could not be used, please check that you've written it correctly

**Comment by ainar-g** [comment]
Using `dnslookup` I get this:

```sh
env DEBUG=1 dnslookup 'www.example.com' 'tls://[2400:3200::1]'
```

```none
[fatal] Cannot make the DNS request: getting conn to tls://[2400:3200::1]:853: connecting to 2400:3200::1: tls: failed to verify certificate: x509: certificate is valid for 223.5.5.5, 223.6.6.6, not 2400:3200::1
```

The TLS certificate must be valid for the IP address.

**Comment by cyouhi** [comment]
What about https://[2400:3200::1]/dns-query ？

**Comment by ainar-g** [comment]
Anything that uses TLS, including HTTPS, must have a valid certificate for the domain name or an IP address.  Have you tried using [`dnslookup`](https://github.com/ameshkov/dnslookup) yourself?

**Comment by cyouhi** [comment]
OK thanks
