### ISSUE TITLE
Show output from the configuration check if updater fails

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#6176]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

During the update process, the new binary checks the configuration.  This is done using `updater.Updater.check` method.  However, if the new binary returns an error, all we get in the logs is:

```none
exec.Command(): exit status 1 1
```

### Proposed solution

1.  Improve the error message itself so that the exit code information isn't duplicated.
2.  Save and printout the actual output from the new binary.

**Comment by schzhn** [comment]
This feature is available since v0.107.38.
