### ISSUE TITLE
Docker healthcheck script missing

### ISSUE THREAD

**Issue by Leah96xxx** [AdguardTeam/AdGuardHome#6179]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.37

### Action

Started adguard docker container (starts on boot, managed by docker compose). Portainer healthcheck shows unhealthy.

Output of `docker inspect --format "{{json .State.Health }}" adguard`:
```
    {
      "Start": "2023-09-07T17:36:48.246890431+01:00",
      "End": "2023-09-07T17:36:48.383885122+01:00",
      "ExitCode": -1,
      "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"/opt/adguardhome/scripts/healthcheck.sh\": stat /opt/adguardhome/scripts/healthcheck.sh: no such file or directory: unknown"
    }
```
(repeated several times)

Confirmed the same occurs after recreating the container and re-pulling the image.

### Expected result

Healthcheck returns healthy

### Actual result

As above, healthcheck returns unhealthy with reason as above.

### Additional information and/or screenshots

I'm not sure how long this has been like this. I only just noticed it after powering off my RasPi for a move. Container updates are handled by Watchtower.

**Comment by ainar-g** [comment]
There is no healthcheck since v0.107.34, as it was causing a lot of issues in a lot of Docker installations.  See #5939 and the [release notes for that release](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.34).

**Comment by Leah96xxx** [comment]
As I mentioned above, I had already tried recreating the container and it didn't work, however it seems to be fine this time.
