### ISSUE TITLE
Enabling MalwareDomainList.com Hosts List causes frequent DNS calls to www.malwaredomainlist.com

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#618]
### Steps to reproduce

1. Enable MalwareDomainList.com Hosts List in filters
2. Leave running for 1 hour
3. Check logs and filter by www.malwaredomainlist.com
4. Many DNS logs should show for www.malwaredomainlist.com (as frequently as 1 per minute)
5. Disable MalwareDomainList.com Hosts List in filters
6. Leave running for 1 hour
7. Check logs and filter by www.malwaredomainlist.com
8. Few DNS logs should show for www.malwaredomainlist.com 

### Expected behavior

Very few DNS calls to www.malwaredomainlist.com should be made when MalwareDomainList.com Hosts List is enabled.

### Actual behavior

Many DNS calls to www.malwaredomainlist.com are made frequently when MalwareDomainList.com Hosts List is enabled.

<details><summary>Screenshot:</summary>
!https://user-images.githubusercontent.com/5121135/53818318-8e6e6f80-3f70-11e9-83e1-aa93bd4ab301.JPG

!https://user-images.githubusercontent.com/5121135/53818320-8e6e6f80-3f70-11e9-8a9e-0c168743598d.JPG

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server: | 0.93 in Docker Container
| How did you setup DNS configuration: | Router DNS servers point to Adguard Home
| If it's a router or IoT, please write device model: | Raspberry Pi 3 Model B
| Operating system and version: | Raspbian GNU/Linux 9.8 (stretch)

**Comment by adrianh-za** [comment]
I think I may have found the cause of these strange logs.

**Old setup**

Router has IP of 192.168.10.1
Router has DNS of 192.168.10.13 (AdGuard) and 8.8.8.8
All devices given DHCP ip addresses from router
DNS in the DHCP was blank, therefore router added itself as DNS server (192.168.10.1)
The RPi (AdGuardHome) was also assigned DHCP, but a reserved DHCP ip address = 192.168.10.13
DNS priority from any device that got DHCP = 192.168.10.1, 8.8.8.8, 8.8.4.4

Therefore, all devices on the network used the DNS ip address supplied in the DHCP which was 192.168.10.1, including the RPi (AdGuard).

**New Setup**

Router has IP of 192.168.10.1 **(BOLD IS WHAT CHANGED)**
**Router has DNS of 8.8.8.8 and 8.8.4.4**
All devices given DHCP ip addresses from router
**DNS in the DHCP is set to 192.168.10.13 (RPi - AdGuardHome)**
The Raspberry pi was given a reserved DHCP ip address = 192.168.10.13
DNS priority from any device that got DHCP = 192.168.10.13, 192.168.10.1, 8.8.8.8, 8.8.4.4

Therefore all devices on the network used the DNS ip address supplied in the DHCP (192.168.10.13), including the RPi (AdGuard) when doing DNS queries.

**************************************************

I think that what was happening in old setup, when AdGuardHome (or any device for that matter) would query the DNS, it would use the DNS server as received in the DHCP which was 192.168.10.1 (router).  The DNS query would be sent to the router who then would query it against the DNS address of 192.168.10.13 (AdGuard) as configured,  I then think AdGuard take the request, and would try query the DNS by pushing it back to 192.168.10.1 (router) as this is the DNS address in its DHCP.  Does this make sense?

Since I made the change, no more funny logs are appearing.

**Comment by adrianh-za** [comment]
Unfortunately it came back, and it seems to be an issue with missing IPv6 records.

Adguard is trying to check the filter lists, probably doing a periodic update check.  When hitting each filter's URL, if the DNS record for the filter does not have an AAAA (IPv6) entry, it seems to go into loop and retries once per minute for that filter.  Also, this only seems to occur when Adguard is using itself as the DNS server.

Info:
- Raspberry Pi 3 where Adguard runs is 192.168.10.13
- Router DHCP (reserved IP of 192.168.10.13) gives the Raspberry Pi DNS servers where 192.168.10.13 is first in list (as I want all devices connecting to router to use Adguard as DNS server).
- Adguard is then using this DNS server (itself) to check the filter URLs updates (as it also has DHCP assigned address).
- I can see the Raspberry Pi IP address doing the DNS query in Adguard Query Log which is correct.
- If I give the Raspberry Pi static DNS servers (override the DNS servers assigned in DHCP and remove 192.168.10.13), Adgaurd then does the DNS query directly against the static DNS server bypassing itself.

This can be reproduced by alternating between the source and mirror of Malware Domain List if the Raspberry Pi (Adgaurd) is configured to use itself as the DNS server,

https://www.malwaredomainlist.com/hostslist/hosts.txt (no AAAA record- frequent entries for this filter in query log)

https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt (has AAAA record- single log for this filter in query log)

**Comment by ameshkov** [comment]
@adrianh-za is this issue gone in v0.94 or is it still there?

**Comment by adrianh-za** [comment]
I'll test over the next 24 hours and revert.

**Comment by adrianh-za** [comment]
@ameshkov 

It is fixed, refreshes every 30 minutes like it should.

I actually think it was similar to #644 where the filter update interval too frequent.
