### ISSUE TITLE
Dashboard scrollbar issue

### ISSUE THREAD

**Issue by gexiaopeng** [AdguardTeam/AdGuardHome#6180]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Scroll bar appears when there is not much data.
![微信图片_20230908142742](https://github.com/AdguardTeam/AdGuardHome/assets/7857056/001a17f7-07d0-4498-851a-c9535051ed11)

### Proposed solution

Hide the scrollbar when there is no data or when there is not much data.

**Comment by ainar-g** [comment]
Please do not file bugs under the `feature request` label.

**Comment by ainar-g** [comment]
@gexiaopeng, please add which browser and OS you're using.

**Comment by ppfeufer** [comment]
Confirmed.

Chrome on Linux
![image](https://github.com/AdguardTeam/AdGuardHome/assets/2989985/a310c35f-fbe8-4852-8062-f896ceda2e13)

Firefox only shows them on mouse enter, but they are there as well.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/2989985/2744ea34-b38a-4240-b7cb-08b9031da77c)

**Comment by gexiaopeng** [comment]
> @gexiaopeng, please add which browser and OS you're using.

Edge and Chrome on Windows10

**Comment by ainar-g** [comment]
@gexiaopeng, the latest Edge and Beta releases contain a fix for this and some related issues.  Can you please check?

**Comment by gexiaopeng** [comment]
> @gexiaopeng, the latest Edge and Beta releases contain a fix for this and some related issues. Can you please check?

The problem still exists.
![QQ截图20231018143420](https://github.com/AdguardTeam/AdGuardHome/assets/7857056/0e5ce7cb-fb89-4373-8f8d-d9caea0c2317)
![QQ截图20231018143643](https://github.com/AdguardTeam/AdGuardHome/assets/7857056/37316057-5f92-4b86-875b-8f418b2c527c)

**Comment by gexiaopeng** [comment]
This issue has been fixed.（AdGuard Home v0.108.0-b.48，Edge）
