### ISSUE TITLE
Setting up a Fallback DNS over UI commented out cause error and freeze of adguard

### ISSUE THREAD

**Issue by ev4x** [AdguardTeam/AdGuardHome#6182]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.37

### Action

Setting up a fallback commented out like #tls://1.1.1.1

### Expected result

It will be ignored like in normal dns configuration

### Actual result

This error
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/129671265/ceb9869b-3a78-4e6c-a279-3e0b5d3b096d)
When not updated over ui directly it will freeze adguard and after restart of docker container it will start but webinterface not work and everything else also not and you need to manually edit the .yamml file i dont know if its only a docker issue or also for normal installation but things with comment # should be just ignored and dont cause this

**Comment by ainar-g** [comment]
Seems like the invalid value gets written to the configuration despite being invalid.  The workaround is to stop AGH, remove the invalid value from `dns.fallback_dns` field, and start it again.

@schzhn, please investigate what causes this.

**Comment by schzhn** [comment]
We've pushed the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) containing the fix.

**Comment by duckxx** [comment]
后备DNS延迟非常大。

![IMG_20230909_022844](https://github.com/AdguardTeam/AdGuardHome/assets/116968444/8729c177-2abc-4138-adb2-7f1285fd454f)

**Comment by ainar-g** [comment]
@duckxx, please file as a separate issue.

**Comment by yaozijin** [comment]
> 后备DNS延迟非常大。
> 
> ![IMG_20230909_022844](https://user-images.githubusercontent.com/116968444/266698416-8729c177-2abc-4138-adb2-7f1285fd454f.jpg)

这通常是因为主DNS无解析结果才会切换会备用DNS，但是你的主DNS和备用DNS是一个服务商提供的，所以除非主DNS丢包要不然备用DNS也会无解析结果。
