### ISSUE TITLE
Allowed and disallowed clients lists does not accept IPv6 Link-local CIDRs

### ISSUE THREAD

**Issue by cenk** [AdguardTeam/AdGuardHome#6192]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.698+8b8ae8ff

### Action

My ips:
```
10.0.0.15/24
fe80::15/64
```

My Allowed clients list:
```
10.0.0.0/24
fe80::/64
127.0.0.1
```

### Expected result

Should be resolved with ipv6.

### Actual result

IPv6 result:
```sh
dietpi@ulasdietpi:~$ dig @fe80::15 google.com
; <<>> DiG 9.16.42-Raspbian <<>> @fe80::15 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

IPV4 result (OK):
```sh
dietpi@ulasdietpi:~$ dig @10.0.0.15 google.com
; <<>> DiG 9.16.42-Raspbian <<>> @10.0.0.15 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50769
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A
;; ANSWER SECTION:
google.com.             21392   IN      A       172.217.17.142
;; Query time: 10 msec
;; SERVER: 10.0.0.15#53(10.0.0.15)
;; WHEN: Sun Sep 10 08:52:45 +03 2023
;; MSG SIZE  rcvd: 55
```

### Additional information and/or screenshots

But when I clear allowed clients list everything is OK.

I think allowed clients lists does not accept IPv6 CIDRs.

**Comment by cenk** [comment]
Update:
The problem seems to be related to link-local (fe80:) addresses.

When I use LUA (fdXX:) there is no problem.

**Comment by ainar-g** [comment]
I'm not sure if there is a good solution here.  There isn't really a CIDR syntax for link-local IPv6 addresses, as far as I know.  Since `fe80::%wlan0/10` could be considered either a prefix with the zone `wlan0` or a single address with the zone `wlan0/10`.  Go's parser currently considers it the latter.  Using `fe80::/10` would only work if we remove the zone from the client's address before feeding it into the access processing method, but that would mean that that rule blocks all link-local addresses.

**Comment by schzhn** [comment]
Fixed in the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions). In the access settings, you can now add a Link-Local subnet, i.e. `fe80::/10`.
