### ISSUE TITLE
0.107.37 fails to compile: internal/aghnet/dhcp_unix.go:63:52: cannot convert ip (variable of type net.IP) to type [4]byte

### ISSUE THREAD

**Issue by yurivict** [AdguardTeam/AdGuardHome#6198]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

0.107.37

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

n/a

### Actual result

```
# github.com/AdguardTeam/AdGuardHome/internal/aghnet
internal/aghnet/dhcp_unix.go:63:52: cannot convert ip (variable of type net.IP) to type [4]byte
internal/aghnet/interfaces_bsd.go:26:15: undefined: errors.Join
note: module requires Go 1.20
```

**Comment by ainar-g** [comment]
> ```none
> note: module requires Go 1.20
> ```

Go 1.19 support has been deprecated in v0.107.24 (2023-02-15) and removed in v0.107.36 (2023-08-02), since it had reached EOL and won't get security updates anymore.  Although we had forgotten to put the removal into the changelog explicitly for some reason.  I'll add the removal back.
