### ISSUE TITLE
Consistently uses a large amount of RAM(13.9GiB/16GiB)

### ISSUE THREAD

**Issue by Winnie0408** [AdguardTeam/AdGuardHome#6202]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.37

### Action

*This issue was translated from Chinese to English using DeepL translation software, which may make errors in translation.*

I deployed AdGuard Home on my home server(Running Ubuntu Server 22.04.3) and enabled extranet access so that other devices on the Internet could use the DoH and DOT services it provides.
Recently I have noticed that AdGuard Home takes up a lot of memory (as shown in the picture below) if it runs for a long period of time (e.g., 3 days), and I'm not sure if this is normal or if it's a "memory leak" or something like that?

Although my machine has plenty of RAM and Linux has excellent memory management mechanisms, I would like to report this problem and hope that it can be fixed!

Also, I have noticed that, when it comes to the situation metioned above, if I try to change the configuration of AdGuard Home, as soon as I click on "Save", "Apply", etc., AdGuard Home goes into an unresponsive state, and unable to process any DNS requests until it either resumes responding automatically (which can take at least 20 minutes), or I manually restart its Docker container.

I configured the DNS cache size to be 128MiB (134217728 bytes), with a minimum TTL of 300 seconds and a maximum TTL of 1500 seconds, and did not enable "optimistic caching".

### Expected result

AdGuard Home doesn't take up much memory (at least not 13GiB)

### Actual result

AdGuard Home takes up 13.9GiB of RAM

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/42741874/cb6bc951-dc63-4442-8472-40369f04209b)

**Comment by catfluoride** [comment]
I have observed sluggishness when I added a lot of forbidden IPs... Maybe you should share your entire config (minus personal stuff). By the way I'm not an expert, but isn't 128 MB cache a bit overkill?

**Comment by Werewolfke** [comment]
I have a setup with over 3Milion domains blocked, over 50 devices on my network, and my installation never goes over 2gb of ram.
Ofcourse what i think it does, is scale itself... meaning if u allocate 16Gb of ram, it will try to use as much as it can? yet i have set it to use 4 and it stays below 2 most of the time. so im not sure about it.

is ur linux install up-to-date? apt update and apt upgrade... who knows maybe its a linux thingy?

**Comment by Winnie0408** [comment]
This issue appears to have been fixed on v0.107.38
