### ISSUE TITLE
`$important,dnsrewrite` rules do not take precedence over `@@`'d dnsrewrite rules

### ISSUE THREAD

**Issue by nagisa** [AdguardTeam/AdGuardHome#6204]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description): NixOS package

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.36

### Action

I set up my AdGuardHome rules as such:

```
# Tell users can find home at google.com…
||home.lan^$dnsrewrite=NOERROR;CNAME;google.com
# Except for sw0; the rule above should not apply…
@@||sw0.home.lan^$dnsrewrite
# use this important rule instead.
|sw0.home.lan^$important,dnsrewrite=NOERROR;A;192.168.90.3
```

Then run

```
dig home.lan sw0.home.lan
```

### Expected result

I expected query for `sw0.home.lan` query to answer with record A pointing at `192.168.90.3` as per the `important` rule, which should override the `@@` rule.

### Actual result

The `sw0.home.lan` query responds with `NXDOMAIN` (this comes from an `upstream_dns` server), as if the `improtant` rule did not exist.

**Comment by nagisa** [comment]
The only way I found how to write the rules that achieve the desired behaviour is

```
||home.lan^$denyallow=sw0.home.lan,dnsrewrite=NOERROR;CNAME;google.com
|sw0.home.lan^$dnsrewrite=NOERROR;A;192.168.90.3
```

however this is particularly unmaintainable due to its non-locality. That is, I have a couple dozen `*.home.lan` subdomains, and then half a dozen `home.lan^$client=$DIFFERENT_SUBNETS` rules. In order to set up everything correctly I would need to list all the `*.home.lan` subdomains in 6 different places, and without making any mistakes!

**Comment by Mizzick** [comment]
Please have a look, we have implemented the requested changes.
The new build version `v0.108.0-a.741+2a56c78f` has been just published to the edge channel.

**Comment by nagisa** [comment]
Thank you, I’ll make a note to myself to give it a spin this weekend.

**Comment by nagisa** [comment]
Can confirm it now works as expected.
