### ISSUE TITLE
UI settings not permanently saved

### ISSUE THREAD

**Issue by Erik262** [AdguardTeam/AdGuardHome#6206]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.38

### Action

Pictures are worth more than thousands of words.

![12-09-2023 at 10-40-06](https://github.com/AdguardTeam/AdGuardHome/assets/11977647/50c797d3-0742-4910-b850-08bd8e13d7bf)

### Expected result

Keeping my selected rows saved.

### Actual result

I am having an issue where the number of rows displayed keeps resetting to 10 rows.

**Comment by rankokrneta** [comment]
I kindly concur with the previous poster; I share the same question/request.

**Comment by ainar-g** [comment]
Please add the precise command you're using to run the container.  See also #6214.

**Comment by Erik262** [comment]
@ainar-g I'm using portioner and this is what I found under commands:
'-h' '0.0.0.0' '-c' '/opt/adguardhome/conf/AdGuardHome.yaml' '-w' '/opt/adguardhome/work' '--no-check-update'

**Comment by ainar-g** [comment]
@Erik262, the latest release should contain a fix for this.  Can you please check?
