### ISSUE TITLE
v0.107.38 service wont start on OpenWrt

### ISSUE THREAD

**Issue by WildByDesign** [AdguardTeam/AdGuardHome#6212]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.38

### Action

I was running v0.107.37 successfully for the past few days with zero issues.

I decided to upgrade to v0.107.38 since it was a very small update (not many changes).

I am unable to start the `adguardhome` service via `/etc/init.d/adguardhome restart` or `/etc/init.d/adguardhome start` as I normally do with each update.

I have had no success getting it to start and therefore have reverted to v0.107.37 for now.

### Expected result

Expecting `adguardhome` service to run.

### Actual result

The `adguardhome` service did not run.

### Additional information and/or screenshots

I have my `adguardhome` set to log to a file on the router. From all of my attempts to run (start service) of `adguardhome` v0.107.38, nothing at all gets logged to file. No details at all, which is unusual.

**Comment by ainar-g** [comment]
Are you able to access the router and run `./AdGuardHome -v` from the directory with the file?  Are there any errors there?

**Comment by WildByDesign** [comment]
I apologize, but this was an error on my end and not a bug. For the first time ever, I forgot to assign execute permission on the binary.

Lesson learned: Bug reports after coffee; not before coffee
