### ISSUE TITLE
Configuration lost 

### ISSUE THREAD

**Issue by cust0muser** [AdguardTeam/AdGuardHome#6214]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.38

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

No data lost! 

### Actual result

I don't fully understand the development at adguard home.  Until a few versions ago, the entire configuration was taken over after an upgrade.  Since the last two updates I have had to set up Adguard from scratch, which takes a lot of time and is annoying.  In addition, adguard does not have a backup function, which might make it easier.  Why is this so complicated?  I use adguard on Docker on my synology.  There are no files in the two directories that adguard creates.  So how do you save the configuration when upgrading???

**Comment by Dynamic5912** [comment]
Take a manual backup of the YAML file

**Comment by cust0muser** [comment]
In docker there are just two folders but there are empty. O don't know why. There is no yaml file

**Comment by cust0muser** [comment]
Any chance to get help how to find the YAML file?

**Comment by ainar-g** [comment]
Please add the exact command you're using to run the AdGuard Home image.  It could be that the directory you use for the data or configuration directory either doesn't exist or the process doesn't have permissions to write there.

**Comment by cust0muser** [comment]
![grafik](https://github.com/AdguardTeam/AdGuardHome/assets/125823408/6ec506aa-425d-4855-b0ed-41eef9d68b3b)

**Comment by ainar-g** [comment]
You have an extra `\` in the path.  In any case, please try actually using the `docker` command.  If it works like it should with the command, there's probably something wrong with other parts of the configuration as well.

**Comment by cust0muser** [comment]
Thanks  i change the path
