### ISSUE TITLE
'certificate does not verify: x509' error after encryption setting reset

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardHome#6217]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.38

### Action

1. Configure the encryption settings with an expired certificate
2. Reset settings

### Expected result

The settings should be reset, no additional messages are expected

### Actual result

'certificate does not verify: x509' error appeared: https://uploads.adguard.org/annrgy_nm10s.png

(disappears after webpage refresh)

**Comment by schzhn** [comment]
We've pushed the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) containing the fix.
