### ISSUE TITLE
Query  Log - Compact Mode

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#622]
Possibly add an option to view the Query Log in a "Compact Mode" as some of the rows can become quite large.  See attached.

![compact](https://user-images.githubusercontent.com/5121135/53897676-53873d00-403f-11e9-9315-298f98e978ba.JPG)

**Comment by szolin** [comment]
AGH v0.103 has a button to view logs in compact mode.
