### ISSUE TITLE
Error checking for updates. Check your internet connection.

### ISSUE THREAD

**Issue by nevidimka89** [AdguardTeam/AdGuardHome#6225]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.38

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

Error checking for updates. Check your internet connection.

### Actual result

Error checking for updates. Check your internet connection.

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/37609261/38044e5d-800b-4e55-b79d-1b04e88e8a9d)

**Comment by ainar-g** [comment]
The error suggests that your upstreams cannot resolve the addresses for AdGuard servers hosting the updates, see #5976. Please try using a different upstream configuration.

If you think that it's not that error, please enable [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see which errors pop out whenever an update check is performed.
