### ISSUE TITLE
feature: improved Simplified Chinese translation

### ISSUE THREAD

**Issue by ttimochan** [AdguardTeam/AdGuardHome#6229]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Hello,

I really like the Adguard Home project. It has greatly improved my internet experience in my network environment. However, some of the translations for simplified chinese are not very accurate, which might confuse Simplified Chinese users. Therefore, I have made some modifications to the translations to make them more precise.

Thanks.

### Proposed solution

I can't access https://crowdin.com for some reason, so there's no way for me to submit content to the specified page

Pull Request https://github.com/AdguardTeam/AdGuardHome/pull/6223

**Comment by ainar-g** [comment]
See https://github.com/AdguardTeam/AdGuardHome/pull/6223#issuecomment-1727476954.
