### ISSUE TITLE
Cannot use 127.0.0.1 as private rDNS server (but adding port fixes it)

### ISSUE THREAD

**Issue by mxk** [AdguardTeam/AdGuardHome#6231]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

OpenBSD, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.38

### Action

Configured `127.0.0.1` under "Private reverse DNS servers" (`local_ptr_upstreams`), which is my dnsmasq server.

If I change the server IP to either `127.0.0.1:53` or `10.0.0.1`, both of which point to the same dnsmasq instance, then everything works correctly.

### Expected result

PTR queries for private IPs should be forwarded to dnsmasq and resolved correctly.

### Actual result

I get a `SERVFAIL` response. Adding `:53` to the upstream server IP fixes the problem.

### Additional information and/or screenshots

Debug log output:

```
[debug] dnsproxy: handling new udp packet from 10.0.0.3:11768
[debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): IN: ;; opcode: QUERY, status: NOERROR, id: 12254
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags:; udp: 4096

;; QUESTION SECTION:
;1.1.0.10.in-addr.arpa.        IN       PTR

dnsforward: started processing recursion
dnsforward: finished processing recursion
dnsforward: started processing initial
applying filters: looking for client with ip 10.0.0.3 and clientid ""
applying filters: no clients with ip 10.0.0.3 and clientid ""
clients: processing 10.0.0.3 with rdns
dnsforward: finished processing initial
dnsforward: started processing ddr
clients: finished processing 10.0.0.3 with rdns in 175.332M-BM-5s
dnsforward: finished processing ddr
clients: processing 10.0.0.3 with whois
clients: finished processing 10.0.0.3 with whois in 26.731M-BM-5s
dnsforward: started processing local detection
dnsforward: finished processing local detection
dnsforward: started processing dhcp hosts
dnsforward: finished processing dhcp hosts
dnsforward: started processing local restriction
dnsforward: addr 10.0.1.1 is from locally served network
dnsforward: finished processing local restriction
dnsforward: started processing dhcp addrs
dnsforward: finished processing dhcp addrs
dnsforward: started processing filtering before req
dnsforward: finished processing filtering before req
dnsforward: started processing local ptr
dnsproxy: cache: disabled; not caching
dnsforward: resolving private address: selecting general upstream: no upstream specified
dnsforward: finished processing local ptr
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(): OUT: ;; opcode: QUERY, status: SERVFAIL, id: 12254
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;1.1.0.10.in-addr.arpa.        IN       PTR
```

**Comment by xRuffKez** [comment]
Have you trietr127.0.0.53?

**Comment by EugeneOne1** [comment]
@mxk, hello and sorry for delayed response.  We've tried to fix it in the latest [edge build](https://github.com/AdguardTeam/AdGuardHome/#test-unstable-versions), so could you please try it?  AdGuard Home should now consider the port while filtering its own listening addresses from private upstreams.

**Comment by mxk** [comment]
Can confirm that this is fixed in the edge build. Thanks!
