### ISSUE TITLE
upstream_timeout option not supported in the WebUI and be override everytime

### ISSUE THREAD

**Issue by rrfeng** [AdguardTeam/AdGuardHome#6232]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

AdGuard Home, version v0.107.38

### Action

Cannot find upstream_timeout  in the WebUI, then I modified the AdguardHome.yaml to set upstream_timeout = 1s, and restart it. It works fine.

Then I changed some configs from the WebUI, the upstream_timeout go back to default(upstream_timeout=10s).

### Expected result

Even if an option do not support config through the WebUI, do not override it when saving configurations.

### Actual result

the upstream_timeout go back to default(upstream_timeout=10s).

**Comment by schzhn** [comment]
Did you stop AdGuard Home before modifying the [configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file)?

**Comment by rrfeng** [comment]
> Did you stop AdGuard Home before modifying the [configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file)?

Yes, I am sure. I modified the config and restart AdGuard Home, so that option works.

I tried to reproduce the problem just now, and I think I may have found why:
The WebUI not reloaded after the modification, so WebUI held the OLD CONFIG, when I click save, it send old config to the server.
