### ISSUE TITLE
ipset cached responses 

### ISSUE THREAD

**Issue by odcold** [AdguardTeam/AdGuardHome#6233]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

AdguardHome adds addresses to ipset only when first query is made. So if response is already in cache - entry in ipset  list will not be readded or renewed when using ipset create with for ex "-timeout 300" key to keep list in actual state 

### Proposed solution

Add addresses to ipset lists when response is received from cache

**Comment by ainar-g** [comment]
Merging into #4501.

**Comment by odcold** [comment]
Sorry to bother, but it's not the same issue as mentioned  above. timeout in ipset is already supported, and I'm just asking you to add the ability to add entries to ipset list if request is served from cache
