### ISSUE TITLE
Suggest to use detailed date format in filters' update time and log.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#624]
1. Suggest to use detailed date format in filters' update time and log.
ex: March 08, 2019 11:23:56
Chinese date format:
2019年3月8日 11:23:56
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/NV13ooC.png)

![image](https://i.imgur.com/C8aPXce.png)
</details><br/>

2. Please use Chinese date format in Chinese interface such as my example.
Use 24-hour clock.
Don't need AM or PM.
ex: March 08, 2019 19:23:56
Chinese date format:
2019年3月8日 19:23:56
("YYYY年MM月dd日 HH:mm:ss")

**Comment by rapdodge** [comment]
Agree! More transparent :)

**Comment by ArchiveBase** [comment]
+1 vote and expect AM/PM :)
