### ISSUE TITLE
rDNS not correctly resolving private range address

### ISSUE THREAD

**Issue by aiden0w0** [AdguardTeam/AdGuardHome#6240]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.38

### Action

```sh
nslookup -debug -type=a 'nas.lan' '10.0.0.215'
```

### Expected result

```
Server:         10.0.0.215
Address:        10.0.0.215#53    

------------
    QUESTIONS:
        nas.lan, type = A, class = IN
    ANSWERS:
    ->  nas.lan
        internet address = 10.0.0.215
        ttl = 0
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Name:   nas.lan
Address: 10.0.0.215
```

### Actual result

```
Server:         10.0.0.215
Address:        10.0.0.215#53

------------
    QUESTIONS:
        nas.lan, type = A, class = IN
    ANSWERS:
    AUTHORITY RECORDS:
    ->  .
        origin = a.root-servers.net
        mail addr = nstld.verisign-grs.com
        serial = 2023092002
        refresh = 1800
        retry = 900
        expire = 604800
        minimum = 86400
        ttl = 85687
    ADDITIONAL RECORDS:
------------
** server can't find nas.lan: NXDOMAIN
```

### Additional information and/or screenshots

I have AGH installed on a nas and a router running openwrt that handles DHCP. I have the device config as follow:
```
AGH (10.0.0.215)
Openwrt Router (10.0.0.2)
```

AGH automatically picks up 10.0.0.2 as private rDNS and is able to show local names in client settings.
However when resolving it simply returns ```NXDOMAIN```.
Directly request the router from AGH installed device or 3rd device yield correct result.

**Comment by aiden0w0** [comment]
Simply putting ```[/lan/]10.0.0.2``` solves the problem.
Is it because ```all_servers``` was used?

**Comment by EugeneOne1** [comment]
@aiden0w0, I believe this is because AdGuard Home is not a DHCP server and therefore does not consider the `lan` TLD to point to a private address space.  So the `[/lan/]10.0.0.2` makes it route `*.lan` requests to where they are intended.
