### ISSUE TITLE
SafeSearch Not working for Google

### ISSUE THREAD

**Issue by ckarson** [AdguardTeam/AdGuardHome#6242]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

0.107.38

### Action

Google safeSearch selected in the options but safesearch blocking is not enforced on my network.

### Expected result

safesearch should not be configurable with block enabled

### Actual result

safesearch can be turned off in the browser

**Comment by ainar-g** [comment]
Hello.  Unfortunately, I cannot understand what the issue is.  If it's a DNS filtering issue, please provide a command that reproduces it.  If it's a UI issue, please attach a screenshot.

**Comment by ckarson** [comment]
I don't know how to explain except that the safesearch is not locked on chrome even when the option is selected and enabled in the UI.

**Comment by ainar-g** [comment]
What do you mean by “safesearch is not locked”?  The Safe Search feature should replace the IP address of the search engine with the address of the engine's safe version.  Did you configure your browser to use AGH as its DNS server?  Do you see the queries from the browser in the query log?

**Comment by ckarson** [comment]
Safesearch remains configurable on my network.  It did work previously but currently it does not.  [https://www.google.com/safesearch](url) should not be configurable.  I do not configure anything in the browser specific to AGH (nor should i have to).  This is functionality that works at my cottage with a nearly identical setup and had worked here before a few months ago.

**Comment by overwatch3560** [comment]
@ckarson are you still experiencing this issue?
