### ISSUE TITLE
Please add v2,v3,v4 protocol??

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#6247]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [x] I have searched other issues and found no duplicates

- [x] I want to request a feature or enhancement and not ask a question

### The problem

Can you join the v2 protocol??
https://github.com/golang/go/wiki/MinimumRequirements#amd64

### Proposed solution

Please add v2,v3,v4
https://github.com/golang/go/wiki/MinimumRequirements#amd64

### Alternatives considered and additional information

There is no

**Comment by ainar-g** [comment]
I don't think we'll ever support anything higher than v1 for AMD64, sorry.

We can improve the build scripts and the documentation to make it easier for people to build their own AGH with a higher level though.

**Comment by schzhn** [comment]
This feature will be available in the upcoming v0.107.39.

**Comment by schzhn** [comment]
You need to set the flag manually `make go-build GOAMD64=v4`.

**Comment by ainar-g** [comment]
As already mentioned, we do not have plans for separate builds for v2 etc.  We have documented the way you can build these yourself.
