### ISSUE TITLE
favicon.ico is fetched from Adguard servers

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#625]
### Steps to reproduce

1.Load up any page of Adguard Home
2.The favicon.ico is loaded from Adguard servers

### Expected behavior

favicon.ico to be loaded from local server
### Actual behavior

favicon.ico to be loaded from Adguard server

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5121135/54067159-5784ac00-4245-11e9-8039-55f601785234.png)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.93
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B
| Operating system and version:| Raspian 9

**Comment by ameshkov** [comment]
Uh, really, thank you!
