### ISSUE TITLE
DoC not working

### ISSUE THREAD

**Issue by maxtar** [AdguardTeam/AdGuardHome#6250]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.38

### Action

1. Add quic dns server.
2. Press check upstream servers.

### Expected result

All checks done.

### Actual result

Got error that incorrect quic address. See screenshot.

### Additional information and/or screenshots

![изображение](https://github.com/AdguardTeam/AdGuardHome/assets/10290098/57cf16e7-3292-467b-83d8-482ec9216301)

**Comment by ainar-g** [comment]
AdGuard has been receiving lots of reports that many ISPs in Russia are blocking QUIC right now, especially HTTP/3 and DNS-over-QUIC, so this is probably another one of these cases.

If you think that this isn't the case here, please [enable verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see which error is printed in the service logs.  It is likely that it's either `connection refused` or `i/o timeout`.

**Comment by maxtar** [comment]
Looks like you are right. I see timeouts:
```
upstream quic://dns.adguard-dns.com:853 failed to exchange ;oPEN.stEaLth.S
i.        IN       A in 36.895664299s: opening quic connection to quic://dns.adguard-dns.com:853: timeout: no recent network activity
```

**Comment by maxtar** [comment]
@ainar-g but why it works on mobile?

**Comment by ainar-g** [comment]
@maxtar, as I've mentioned, the situation seems to be dependent on the ISP, and we've reports that even within a single ISP's networks there may be differences between regions and/or connection types.

**Comment by maxtar** [comment]
> @maxtar, as I've mentioned, the situation seems to be dependent on the ISP, and we've reports that even within a single ISP's networks there may be differences between regions and/or connection types.

Sorry, I mean that AdguardHome server and mobile phone connected to the same LAN behind the same router.

**Comment by ainar-g** [comment]
Them I'm not sure what you meant when you said “it works on mobile”, sorry.  Do you have a DNS-over-QUIC client on your phone?

**Comment by maxtar** [comment]
> Them I'm not sure what you meant when you said “it works on mobile”, sorry. Do you have a DNS-over-QUIC client on your phone?

Yes. I have installed payed adguard for android. And use your adguard-dns.io private server by quic protocol.

**Comment by ainar-g** [comment]
Could be an issue with the bootstrap servers or IP version then.  You can try using a different set of bootstrap servers and also set `dns.bootstrap_prefer_ipv6` to `true`.

**Comment by maxtar** [comment]
> Could be an issue with the bootstrap servers or IP version then. You can try using a different set of bootstrap servers and also set `dns.bootstrap_prefer_ipv6` to `true`.

Hm. How I can see which bootstrap servers use in AdGuard for Android? Or this question to AdGuard android developers?
Unfortunately my provider doesn't support ipv6.

**Comment by ainar-g** [comment]
Apologies for the long response.  Yes, you should probably contact the support about that.

https://github.com/ameshkov/dnslookup

Here's a cross-platform CLI tool you can also use to check the availability of various upstreams and protocols.

**Comment by maxtar** [comment]
Interesting. After last Adguard update quic started work again. But maybe this not related things.
