### ISSUE TITLE
DNS Rewrites Hierarchy broken since version 0.107.37

### ISSUE THREAD

**Issue by mikurth** [AdguardTeam/AdGuardHome#6253]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.37

### Action

```sh
nslookup -debug -type=a 'XXX.ZZZ.YYY.com' '$YOUR_AGH_ADDRESS'
```
Server:         172.22.1.3
Address:        172.22.1.3#53

------------
    QUESTIONS:
        XXX.ZZZ.YYY.com, type = A, class = IN
    ANSWERS:
    ->  XXX.ZZZ.YYY.com
        internet address = 172.22.1.11
        ttl = 10
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:  XXX.ZZZ.YYY.com
Address: 172.22.1.11

### Expected result

response with ip 172.22.1.10

### Actual result

response with ip 172.22.1.11

### Additional information and/or screenshots

Since version [107.37](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.37) the DNS overwrite hierarchy is no longer correct. I have two overwrites defined:

`  rewrites:
    - domain: '*.YYY.com'
      answer: 172.22.1.11
    - domain: '*.ZZZ.YYY.com'
      answer: 172.22.1.10`

Until version 0.107.36 (I just tested it out) a dns query for XXX.ZZZ.YYY.pro returned the 172.22.1.10 ip however since version 0.107.37 it returns the one from higher level 172.22.1.11.

**Comment by EugeneOne1** [comment]
@mikurth, should be fixed on edge, see #6226.
