### ISSUE TITLE
[error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key

### ISSUE THREAD

**Issue by iceye2072** [AdguardTeam/AdGuardHome#6254]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.38

### Action

2023/09/24 11:42:30.211047 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:30.210485 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:25.184091 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:25.183671 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:20.158049 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:20.157755 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:15.134436 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:15.134255 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:10.123780 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:10.123572 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:06.146000 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:06.144730 [info] AdGuard Home, version v0.107.382023/09/24 11:42:30.211047 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:30.210485 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:25.184091 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:25.183671 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:20.158049 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:20.157755 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:15.134436 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:15.134255 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:10.123780 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:10.123572 [info] AdGuard Home, version v0.107.38
2023/09/24 11:42:06.146000 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key
2023/09/24 11:42:06.144730 [info] AdGuard Home, version v0.107.38 

### Expected result

normal

### Actual result

fail to start

**Comment by pcleon** [comment]
v0.107.40 have the same problem

2023/10/28 21:57:18 [error] Couldn't get logging settings from the configuration: yaml: line 15: did not find expected key
2023/10/28 21:57:18.275343 8876#1 [info] AdGuard Home, version v0.107.40
2023/10/28 21:57:18.275911 8876#1 [debug] current working directory is /etc/AdGuardHome
2023/10/28 21:57:18.277243 8876#1 [debug] reading config file: /etc/AdGuardHome.yaml
2023/10/28 21:57:18.698015 8876#1 [error] parsing configuration file: parsing config file for upgrade: yaml: line 15: did not find expected key

**Comment by anqiuy** [comment]
In my case, the error was caused by [luci-app-adguardhome](https://github.com/rufengsuixing/luci-app-adguardhome). It invokes /usr/share/AdGuardHome/gfw2adg.sh script to add upstream_dns items with the incorrect indent in /etc/AdGuardHome.yaml when I try to add gfw list. [How to fix it](https://github.com/kongfl888/luci-app-adguardhome/commit/4553150ba6afacff8d89619470cb8fba98353eaa)
