### ISSUE TITLE
ipv6 issue

### ISSUE THREAD

**Issue by aaozgur** [AdguardTeam/AdGuardHome#6256]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.38

### Action

I am using mikrotik hapax3 and it is installed on this router. When IPv4 is turned off, it does not connect to DNS servers via IPv6. I use 3 different doh dns servers

### Expected result

Works only with ipv6 when no ipv4

### Actual result

no internet connection because there is no dns query

### Additional information and/or screenshots

Adguard has ipv6 global and linklocal addresses. I can access AdGuard from all addresses. but adguard does not make dns query over ipv6.

![resim](https://github.com/AdguardTeam/AdGuardHome/assets/145943462/a1938f88-a640-4fe0-b6d3-8c8064f324ac)
![resim](https://github.com/AdguardTeam/AdGuardHome/assets/145943462/58ccbe45-4fde-4ed0-b3b3-4facbcb0f4b8)
![resim](https://github.com/AdguardTeam/AdGuardHome/assets/145943462/a68a20cc-a1e9-4d20-a431-158966d3442a)

**Comment by aaozgur** [comment]
does not make dns query over ipv6.

![resim](https://github.com/AdguardTeam/AdGuardHome/assets/145943462/c6584140-e03c-419d-abda-99b3d84497f6)

**Comment by aaozgur** [comment]
green window from same prefix ping. Adguard responding.
yellow window from global ping. Adguard not responding. I can see packets go to adguard, no response

![resim](https://github.com/AdguardTeam/AdGuardHome/assets/145943462/882552f1-fad9-4bdd-88b5-ecc9a4333423)

**Comment by ainar-g** [comment]
Some pointers to diagnose the issue:

1.  Please enable [verbose logging] and see which errors are printed there.\

2.  Make sure you've set `dns.bootstrap_prefer_ipv6` to `true`.

3.  Try running AGH outside of Docker.  Perhaps it's a containerization issue.

**Comment by aaozgur** [comment]
Hello,

I did research but couldn't find how to access the yaml file. Can you show me a source to learn this? I guess I won't be able to activate logging without accessing the yaml file.
I use the container package on Mikrotik.

Thank you in advance

**Comment by aaozgur** [comment]
I fix it. Problem is missing gateway6 on veth.
