### ISSUE TITLE
No compression (gzip) enabled

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#626]
### Steps to reproduce

1. Open Chrome DevTools (F12)
2. Go to Network tab
3. Click record and CTRL-F5 on any Adguard Home page
4. User size column, two sizes will shows if resources are compressed. (top = compressed, bottom = actual).  Only a single size means its not compressed.

### Expected behavior

The various resources being loaded (JS, CSS, etc) should be compressed.

### Actual behavior

The various resources being loaded (JS, CSS, etc) are not be compressed.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5121135/54067504-81d86880-4249-11e9-8d50-8dd2a23edd2c.png)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.93
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B
| Operating system and version:| Raspbian 9

**Comment by ameshkov** [comment]
@szolin relevant library:
https://github.com/lpar/gzipped
