### ISSUE TITLE
Phishing URL Blocklist - Overly Broad entry: dualstack.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdGuardHome#6260]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

The "Phishing URL Blocklist (PhishTank and OpenPhish)" blocks [s3.dualstack.us-east-1.amazonaws.com](http://s3.dualstack.us-east-1.amazonaws.com/).

Steam, a gaming platform, uses [steamcloud-us-east.s3.dualstack.us-east-1.amazonaws.com](http://steamcloud-us-east.s3.dualstack.us-east-1.amazonaws.com/) to save game state.
This overly-broad block breaks the Steam client's ability to save game data.

### Proposed solution

The following allowlist entry resolves the issue:

@@||[steamcloud-us-east.s3.dualstack.us-east-1.amazonaws.com](http://steamcloud-us-east.s3.dualstack.us-east-1.amazonaws.com/)^$important

### Alternatives considered and additional information

https://www.reddit.com/r/Steam/comments/16ea7uj/if_steam_cloud_isnt_working_for_some_games_take_a/
https://www.reddit.com/r/Steam/comments/dlrse6/suspicious_steam_subdomains_getting_blocked_by/

**Comment by ainar-g** [comment]
Please use the [link that is provided on the New Issue form](https://link.adtidy.org/forward.html?action=report&app=home&from=github) to report issues with filtering lists.  Do not use the feature request label for these.
