### ISSUE TITLE
Statistics not updating

### ISSUE THREAD

**Issue by lolleri200** [AdguardTeam/AdGuardHome#6261]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Version:  v0.107.38

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

Before the statistics were updated, but after booting up my Raspberry Pi where my AdGuard is configured and the IP is connected to my router now all my statistics are stuck at zero for a moth now and can't get it to display any other info. 
![Screenshot_20230926_231117_Chrome](https://github.com/AdguardTeam/AdGuardHome/assets/45740831/88a58830-a28c-451a-979b-0e9ffb5f2710)
![Screenshot_20230926_231142_Chrome](https://github.com/AdguardTeam/AdGuardHome/assets/45740831/ea60cc40-e8d8-4570-b39d-3ecd531e6c5b)

### Actual result

I expected to see the statistics changing numbers like before. If anyone can help please let me know. Thanks!

**Comment by ainar-g** [comment]
Some things that can help you diagnose the issue:

* Enable [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and look for messages related to statistics.

* Try moving `data/stats.db` in AdGuard Home's working directory.

* Make sure that the statistics are enabled on the *Settings → General settings* page.

**Comment by DandelionSprout** [comment]
Are the home's devices that run through the AdGuard Home server, properly running through the server?
