### ISSUE TITLE
How to remove empty frame 

### ISSUE THREAD

**Issue by dheer99** [AdguardTeam/AdGuardHome#6266]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Adguard Home able to block ads from websites, but its really very bad if we still see empty ad frame 

### Proposed solution

empty frame

**Comment by agneevX** [comment]
You can't. Different browsers display inaccessible content in different manners.

**Comment by monta990** [comment]
This is not possible with adguard, because is CSS.

**Comment by ainar-g** [comment]
See #1228.
