### ISSUE TITLE
New features needed

### ISSUE THREAD

**Issue by rapdodge** [AdguardTeam/AdGuardHome#627]
1. Add GUI feature on dashboard can change port for administrator dashboard from port 80 to another port (like 8080)
2. Make 2 level administration (login button), if not login, non login user can look "Dashboard" & "Query Log" but cannot change any configuration
3. If a domain blocked on filterlist, administrator can change the redirect to a blocked page (not show NXDOMAIN)

**Comment by ameshkov** [comment]
Could you please file two different feature requests?

**Comment by rapdodge** [comment]
> Could you please file two different feature requests?

on separate? you mean?

**Comment by ameshkov** [comment]
Yeah

**Comment by rapdodge** [comment]
> 
> 
> Yeah

Okay.
