### ISSUE TITLE
Specify IP address for DoH or DoT request

### ISSUE THREAD

**Issue by Bliod-Cook** [AdguardTeam/AdGuardHome#6270]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Sometimes the Boostrap DNS return a ip which is not the fastest ip. It will make it cost more time to get a result

### Proposed solution

Is it possible to add a new grammer to specify the target address of DoH request?

Like I want to request one.one.one.one use 1.0.0.1 not 1.1.1.1

### Alternatives considered and additional information

My English is not very good. Sorry.

**Comment by Sakura-Luna** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/6083
By the way, your example is also valid if you directly use IP instead of domain name.

**Comment by ainar-g** [comment]
#5217, too.
