### ISSUE TITLE
PROBLEM 

### ISSUE THREAD

**Issue by ford220102** [AdguardTeam/AdGuardHome#6286]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

0.107.38

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

Hello, about this matter, you can quite a letter that I can block automatic only I want the same as the same as a plug under your browsers, you can give you a letter quite automatically and I still have a problem with configuration I do not block something in a fixed one as I refresh quite well, they do nothing
It is possible to give whether it is possible to be the possibility or not to dermal again

### Actual result

-

### Additional information and/or screenshots

RPI 4

**Comment by ainar-g** [comment]
I'm sorry, I do not understand what you're requesting.  Please describe the issue more clearly, in any language you're comfortable with.

**Comment by DandelionSprout** [comment]
As the "Expected result" question is, sorry to say this, completely incomprehensible, I think it's just as well to simply close the issue report for now.
