### ISSUE TITLE
Disable Healthcheck

### ISSUE THREAD

**Issue by Ghost108** [AdguardTeam/AdGuardHome#6292]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Synology Diskstation

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.38

### Action

no action needed

### Expected result

-

### Actual result

-

### Additional information and/or screenshots

Is it possible to disable the internal adguard healthcheck?
I see every 30 seconds a request from 127.0.0.1 to cloudflare:

![Bildschirmfoto 2023-10-10 um 09 20 11](https://github.com/AdguardTeam/AdGuardHome/assets/17011498/9c8de87f-5902-44d9-bf7c-77370b8d4b27)

**Comment by fernvenue** [comment]
That's not AdGuardHome's behavior.

**Comment by Ghost108** [comment]
you are right! this comes from my unbound container!
Thanks!
