### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by marcovecchione** [AdguardTeam/AdGuardHome#6296]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.38

### Action

The time shown in the statistics (24 hours, retained 90 days) is exactly one hour ahead of UTC and one hour less than my time zone (Italy) CET. Changing the timezone on Linux does not change anything in the adguard interface

### Expected result

I expected to see synced time in statistics

### Actual result

Described before

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/68564594/2a2a4935-80f2-4eb9-abe1-325afde51720)

**Comment by marcovecchione** [comment]
> Potential duplicates:
> 
> * [[ipv6 issue #6256](https://github.com/AdguardTeam/AdGuardHome/issues/6256)] ipv6 issue (60%)

not duplicate

**Comment by ainar-g** [comment]
@marcovecchione, the latest Edge and Beta releases contain a fix for this.  Can you please check?

**Comment by marcovecchione** [comment]
I checked in stable version 107.40, it works fine

    Il martedì 17 ottobre 2023 alle ore 17:29:39 CEST, Ainar Garipov ***@***.***> ha scritto:  
 
 


@marcovecchione, the latest Edge and Beta releases contain a fix for this. Can you please check?
