### ISSUE TITLE
Update check failed. Please check your Internet connection Error

### ISSUE THREAD

**Issue by mahmoudhamadeh** [AdguardTeam/AdGuardHome#6298]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

Version:  v0.107.39

### Action

#6297 

Platform: Raspberry PI 3B+ | Raspbian Lite
Installation: SSH wget command, fresh install
DHCP is handled by the router "UniFi Dream Machine Pro"

After Adguard update today it stopped working, when I login the Adguard Dashboard I get this message "Update check failed. Please check your Internet connection." even after a fresh install. No changes on the router side or on the devices side. No filters or rules set on the router side.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/26927138/d24edce4-9d7a-494e-8142-fff404780ef5)

### Expected result

Working DNS

### Actual result

All devices cant connect to internet, Adguard show an error "Update check failed. Please check your Internet connection"

**Comment by mahmoudhamadeh** [comment]
It must be something related to the upstream DNS over HTTPS, when I enter the IPv4 it works correctly. But with the DNS-over-HTTPS it fails. I'm using DNS-over-HTTPS before the update nothing changed.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/26927138/a9adeea2-bc9e-4937-8a3b-7ce9b93426ea)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/26927138/9dfb8dba-7907-47cf-a8f3-79dcd107d61b)

**Comment by pipip** [comment]
same for me. DNS over HTTPS has not been working anymore since upgrade, IPv4 works.

**Comment by glasseffects** [comment]
It's the same issue here on one ISP, the other works fine. With 127.0.0.1 as IP4 DNS, there's virtually no internet connection on my Windows 11 machine. It's the same issue with the same ISP on another location but with different connection. I have no networking expertise, hence not sure what could be the issue.

Request the AGH team to resolve the issue.

**Comment by pekkle-hksar** [comment]
+1
IPv4 upstream is working, but not DoT or DoH

**Comment by ainar-g** [comment]
@mahmoudhamadeh, we cannot reproduce these.  Please [enable verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see what kind of errors are there when you check for updates or check the upstreams.

**Comment by glasseffects** [comment]
> @ainar-g During the last week I was using only IPv4 since DoT & DoH were not working. Today I tested to change to DoH trying to reproduce the error and to my surprise it was working without an issue! no change during this week, it fixes it self apparently. @kiwilad-nz @glasseffects @pekkle-hksar can you check and confirm all is good before this is closed?
> 
> ![image](https://user-images.githubusercontent.com/26927138/275568511-f7f630c8-b183-462a-b84b-6f3c3701f7ea.png)

I would be happy to share the debug info. Can you guide me? What to look for and what commands to issue?

Thanks.

**Comment by SCPdesign** [comment]
Rolling back to v0.107.38 fixed this for me.

quic://94.140.14.14
quic://94.140.15.15
quic://dns.adguard.com
quic://dns.adguard-dns.com


I'm on FreeBDS

**Comment by mahmoudhamadeh** [comment]
@glasseffects 
> I would be happy to share the debug info. Can you guide me? What to look for and what commands to issue?
> 
> Thanks.

Sure, here are the steps:
- Navigate to AdGuardHome folder usually under `opt` on the root directory.
- Stop AdGuard using this command `sudo ./AdGuardHome -s stop`
- Edit AdGuardHome.yaml using `sudo nano AdGuardHome.yaml`
- Use arrows to go to the end of the file and change the following value under Log:
   - [ ] file: /tmp/aghlog.txt
   - [ ] verbose: true
- Save `Ctrl+O`, Exit `Ctrl-X`
- Start AdGuard once again using this command `sudo ./AdGuardHome -s start`
- Reproduce the issue as many as you can.
- Navigate to `tmp` folder under the root directory, and download the `aghlog.txt file`

**Comment by pekkle-hksar** [comment]
> @ainar-g During the last week I was using only IPv4 since DoT & DoH were not working. Today I tested to change to DoH trying to reproduce the error and to my surprise it was working without an issue! no change during this week, it fixes it self apparently. @kiwilad-nz @glasseffects @pekkle-hksar can you check and confirm all is good before this is closed?
> 
> ![image](https://user-images.githubusercontent.com/26927138/275568511-f7f630c8-b183-462a-b84b-6f3c3701f7ea.png)

tested everything is working fine now
