### ISSUE TITLE
DoT not working with v0.108.0-a.725+5fa11567

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/AdGuardHome#6299]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.725+5fa11567

### Action

After update to Edge version v0.108.0-a.725+5fa11567, DoT (Android Private DNS) is not working.
DoH is working fine when input the server in Android AdGuard DNS filter; while DoT also is not working.

### Expected result

DoT should still work fine after update

### Actual result

DoT is not working

**Comment by ainar-g** [comment]
We cannot reproduce the issue.  If you enable [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and make requests from the Android device, do you see any errors in the log?

**Comment by pekkle-hksar** [comment]
Further check, my AGH server hostname is single blocked by Google. Case could be closed. Thanks!!!
