### ISSUE TITLE
Per Device Unblocking not working 

### ISSUE THREAD

**Issue by Dynamic5912** [AdguardTeam/AdGuardHome#6300]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.39

### Action

Adding a custom allow rule for a single device to access a site/domain that is blocked by a blocklist - e.g.  **@@||telemetry.api.2kcoretech.online^$client='GARYXBOXONES'**

### Expected result

The site/domain should be unblocked for the device in question

### Actual result

The site/domain remains blocked and is not accessible.

Only by allowing the site/domain for **all devices** does it then become unblocked and accessible.

**Comment by Dynamic5912** [comment]
Update - Unblocking by client name is no longer working. However unblocking by IP address **does** work. Using the client name has worked in the past, so something has changed to stop this working in the most recent update.

Clients are set as Persistent Clients in AdGuard Home.

**Comment by ainar-g** [comment]
I cannot reproduce this.  Can you enable [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see if the client is recognized?  Perhaps the IP address has changed?

You should see a message along the lines of:

```none
[debug] filtering: found rule "@@||example.com^$client=\"Client\"" for host "www.example.com", filter list id: 0

**Comment by Dynamic5912** [comment]
Hi,

So interestingly between the stopping and starting of the AGH service, this has now started working again, and domains etc. can now be unblocked by device names.

Thanks for the assistance - this can be closed now.
