### ISSUE TITLE
h3, quic upstreams not working in v0.107.39 on FreeBSD

### ISSUE THREAD

**Issue by avhm** [AdguardTeam/AdGuardHome#6301]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.39

### Action

I've previously been using upstreams designated as:
`h3://unfiltered.adguard-dns.com/dns-query`

However, once updating to v0.107.39 these now all fail. Swapping back to:
`https://unfiltered.adguard-dns.com/dns-query`
fixes the issue, but not ideal.

Happy to dig into this in more detail if required, just lmk what's helpful for diagnosis.

### Expected result

I expected forcing http3 to function

### Actual result

All requests to these upstreams fail.

**Comment by utlimate** [comment]
same issue

**Comment by m0d3rnX** [comment]
At least DNS-over-Quic and DNS-over-HTTPS3 are making problems now. 
DNS-over-TLS is still working and DNS-over-HTTPS are still working.

**Comment by avhm** [comment]
@ainar-g It's the same for all http3 upstreams (was using three separate upstreams), I've only tested the h3:// designation in the DNS upstream UI, not by changing the http3 config (configuration yml is defaults otherwise)

Platform is OPNsense 23.7.6-amd64 on FreeBSD 13.2-RELEASE-p3 installed via [mimugmail](https://github.com/mimugmail/opn-repo/commits?author=mimugmail) community plugin

**Comment by ainar-g** [comment]
Thanks, we've received the logs, but unfortunately they show the opposite, that the HTTP/3 is actually used:

```none
[debug] using HTTP/3 for this upstream: QUIC was faster
[debug] REDACTED:443: sending request over udp: A REDACTED.
…
[debug] upstream REDACTED:443 exchanged ;REDACTED.	IN	 A successfully in 879.419711ms
```

Perhaps the upstream check is faulty?  Can you send the logs that appear when you push *Test upstreams* with an `h3://` upstream?

**Comment by m0d3rnX** [comment]
This is what i get when i test upstreams:
`2023/10/12 16:20:08.987901 1#177 [debug] handling tcp: reading msg: connection timed out; original error: reading len: read tcp 192.168.1.11:853->213.147.164.91:2740: i/o timeout`

**Comment by avhm** [comment]
It was another use who sent in the logs I assume, but can confirm (for me at least) that this was an issue with resolution, not just the test.

After updating, no requests were returning until I manually set the upstream resolvers to https instead of h3.

I'll run the logging on my side with the test trigger too before sending them in later.

**Comment by ainar-g** [comment]
Seems like there are quite a few people with issues with QUIC and HTTP/3 in v0.107.39.  This is most likely related to quic-go/quic-go#4105.  We'll try to rollback to a previous version and see if that fixes the situation.

**Comment by avhm** [comment]
Logs sent, only thing jumping out at me in the log is failing IPV6 requests - my ISP doesn't route IPV6, so wondering if this is causing the failure state. 

It looks to me like the IPv4 queries were successful and that H3 is actually working as intended, but for some reason the failing IPv6 queries trigger a failure.

**Comment by ainar-g** [comment]
Thanks for the logs, @avhm!

```none
INTERNAL_ERROR (local): write udp [::]:4288->94.140.14.140:443: sendmsg: invalid argument
```

Looks like it is indeed the quic-go error I've mentioned previously.  We'll try a rollback of the library.

**Comment by ainar-g** [comment]
We've released v0.108.0-a.729+506d7131 on the Edge channel.  Could any of you please try it out and tell us if QUIC and HTTP/3 upstreams work again?  (See the [Platforms page](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms#releases) on the Wiki for links to the builds and follow the [manual update](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update) instructions with the archive.)

**Comment by donfeduardo** [comment]
Testing upstreams (including QUIC but not H3) is successful with the Edge channel version for me.

**Comment by marten-seemann** [comment]
Does https://github.com/quic-go/quic-go/pull/4110 fix the problem?

Do you have any advice for us how we can find these kind of bugs in the future before a release? This would have been discovered if we had run our test suite on FreeBSD, but unfortunately GitHub Actions doesn't come with any FreeBSD runners.

**Comment by ainar-g** [comment]
@marten-seemann, I've pushed a [branch](https://github.com/AdguardTeam/dnsproxy/tree/test-quic-go-fix) of `dnsproxy`, which uses the same DNS libraries as AdGuard Home, but is simpler to set up.  Running it with:

```sh
./dnsproxy -u 'quic://dns.adguard-dns.com' -v
```

on a FreeBSD VM in Qemu seems to work, unlike the version currently in our `master`.

(Anyone willing to test that fix on a real FreeBSD can switch to that branch, run `make go-build`, run the same command, and make queries with something like `host 'www.example.com' '127.0.0.1'`.)

 >  Do you have any advice for us how we can find these kind of bugs in the future before a release?

I've been thinking about the same thing for a while now.  There are GitHub actions that run VMs on one of GitHub's blessed systems, but at that point it's not that different from cross-compiling the test binary with `go test -c` and hacking together a large `qemu` call.

If anybody else has any suggestions, please share.

**Comment by Adgbeta** [comment]
I have same problem here, I am using Version: v0.108.0-b.47, I am on FreeBSD too.

In DNS settings, when I test the DNS upstream, I have this erros:

Server "h3://unfiltered.adguard-dns.com/dns-query": could not be used, please check that you've written it correctly
Server "quic://dns.adguard-dns.com": could not be used, please check that you've written it correctly
Server "quic://unfiltered.adguard-dns.com": could not be used, please check that you've written it correctly

I didn't have this issue before. This was after installing v0.108.0-b.47

**Comment by ainar-g** [comment]
Did anybody else test the fix by @marten-seemann?  We need to decide whether to rollback to the previous version or wait for quic-go to merge the fix.

**Comment by donfeduardo** [comment]
My OPNsense firewall isn't set up to build anything, but I tried this on a different FreeBSD box and it seems to be doing the right thing with commit a27ca72:

[dnsproxy_test_log.txt](https://github.com/AdguardTeam/AdGuardHome/files/12919022/dnsproxy_test_log.txt)

**Comment by Adgbeta** [comment]
> Did anybody else test the fix by @marten-seemann? We need to decide whether to rollback to the previous version or wait for quic-go to merge the fix.

I just tested Version: v0.108.0-a.730+733d6c1f with only quic://unfiltered.adguard-dns.com and quic://dns.adguard-dns.com is working. This is the response:

Response details
Status
Processed
DNS server
quic://dns.adguard-dns.com:853 (served from cache)
Elapsed
0.35 ms
Response code
NOERROR
Response
A: 172.253.122.99 (ttl=213)
A: 172.253.122.147 (ttl=213)
A: 172.253.122.103 (ttl=213)
A: 172.253.122.104 (ttl=213)
A: 172.253.122.105 (ttl=213)
A: 172.253.122.106 (ttl=213) 

Response details
Status
Processed
DNS server
quic://dns.adguard-dns.com:853 (served from cache)
Elapsed
0.23 ms
Response code
NOERROR
Response
AAAA: 2607:f8b0:4004:c08::8a (ttl=46)
AAAA: 2607:f8b0:4004:c08::71 (ttl=46)
AAAA: 2607:f8b0:4004:c08::8b (ttl=46)
AAAA: 2607:f8b0:4004:c08::64 (ttl=46) 

this is the response for h3://unfiltered.adguard-dns.com/dns-query :

Response details
Status
Processed
DNS server
https://unfiltered.adguard-dns.com:443/dns-query (served from cache)
Elapsed
0.24 ms
Response code
NOERROR
Response
A: 172.253.122.99 (ttl=92)
A: 172.253.122.147 (ttl=92)
A: 172.253.122.106 (ttl=92)
A: 172.253.122.104 (ttl=92)
A: 172.253.122.103 (ttl=92)
A: 172.253.122.105 (ttl=92) 

Response details
Status
Processed
DNS server
https://unfiltered.adguard-dns.com:443/dns-query (served from cache)
Elapsed
0.24 ms
Response code
NOERROR
Response
AAAA: 2607:f8b0:4004:c08::64 (ttl=157)
AAAA: 2607:f8b0:4004:c08::8b (ttl=157)
AAAA: 2607:f8b0:4004:c08::71 (ttl=157)
AAAA: 2607:f8b0:4004:c08::8a (ttl=157)

**Comment by marten-seemann** [comment]
I just released [v0.39.1](https://github.com/quic-go/quic-go/releases/tag/v0.39.1) with the fix for the ECN control message on FreeBSD.

**Comment by ainar-g** [comment]
The newest Beta release, v0.108.0-b.48, contains the fix from @marten-seemann.  If we get a confirmation that it works on FreeBSD for anyone here, we'll be able to ship the final release this week.

**Comment by donfeduardo** [comment]
"Test upstreams" and a `host` query both work for me with v0.108.0-b.48.

[adguard_test_v0.108.0-b.48.txt](https://github.com/AdguardTeam/AdGuardHome/files/12934241/adguard_test_v0.108.0-b.48.txt)

**Comment by ainar-g** [comment]
@avhm, this should be fixed in v0.107.40.  Can you (or anyone else experiencing the issue in v0.107.39) please check?

**Comment by avhm** [comment]
@ainar-g confirmed, just updated and ran the tests gain, all looking good.

Thanks for the fast turn around!

**Comment by Mirabis** [comment]
I can also confirm that the update fixed it, see attached screenshots:
<img width="1320" alt="SCR-20231018-qncn" src="https://github.com/AdguardTeam/AdGuardHome/assets/3105038/cd870c59-ec02-4b97-90b9-97ec44402436">
<img width="1362" alt="SCR-20231018-qnpo" src="https://github.com/AdguardTeam/AdGuardHome/assets/3105038/4b8b110d-9264-4be8-a540-d542e5c1184e">
