### ISSUE TITLE
Upstream DNS over QUIC has failed in v0.107.39

### ISSUE THREAD

**Issue by donfeduardo** [AdguardTeam/AdGuardHome#6306]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.39

### Action

Tested upstreams using button in UI

### Expected result

Tests should pass

### Actual result

Error: Server "quic://dns.adguard-dns.com": could not be used, please check that you've written it correctly

### Additional information and/or screenshots

AdGuard Home running on OPNsense firewall as a resolver only for certain devices in the network. This problem seems to have started immediately after updating to v0.107.39. I originally did not have any fallback servers defined and so all outbound requests were (incorrectly) going to my local resolver (and being appended with '.mydomain.com' in the search).

I have now added another resolver to the main configuration and added fallbacks, and they all work correctly. I tried adding a different QUIC server and got the same failure in the UI. With other resolvers configured everything seems to be working, so it seems the error is specifically with QUIC.

I looked at the firewall logs and there's no indication the firewall is blocking the request or reply (and in fact it shouldn't, because the origin/destination are the firewall itself, open by rule).

Verbose log attached.

[adguard_test_upstream.txt](https://github.com/AdguardTeam/AdGuardHome/files/12885346/adguard_test_upstream.txt)

**Comment by ainar-g** [comment]
Thank you for the log!  Unfortunately, there aren't any QUIC-related errors in the log.  In fact, the connection seems to be successful:

```none
[debug] dnsforward: checking if upstream "quic://dns.adguard-dns.com" works
[debug] bootstrap: dialing 94.140.14.14:853 (1/4)
[debug] bootstrap: connection to 94.140.14.14:853 succeeded in 47.892µs
```

HTTP/3 upstreams seem to be affected in this release as well, so I'll merge this one into #6301, if you don't mind.
