### ISSUE TITLE
DHCP problem.....

### ISSUE THREAD

**Issue by Suspectxyzz** [AdguardTeam/AdGuardHome#6307]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.39

### Action

what I did for verification
```sh
I installed adguard home all 3 versions (normal, beta , edge)
reinstalled the operating system 2 times (on 2 different memory cards, one of 32 and one of 128) ubuntu server 23.04 32bit
I have reconfigured the router
```
[logs.txt](https://github.com/AdguardTeam/AdGuardHome/files/12885568/logs.txt)

### Expected result

I also have a problem, for a few days my adguard home has stopped working, as I see in the client table, only 2 android devices are still working my ios phone/pc doesn't work  ()
I also added my PC to Persistent clients, but in vain 
why only android phones work?

### Actual result

nothing works

### Additional information and/or screenshots

![NVIDIA_Share_DYeQX9eeGh](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/bed86488-dc37-4661-b88c-f245c1b11551)
![NVIDIA_Share_uI8XAy4tpG](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/112d2e8a-c8ab-4f6a-b8b2-d0f56e56cbce)

![ShareX_IaCXN77Mfc](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/a3b994b9-4750-47d8-a9bd-645db79019fb)
![ShareX_3cuyEfqyJc](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/36310dd5-1a8a-4ff7-a1b0-c23d4431e635)

**Comment by ainar-g** [comment]
Unfortunately, the logs do not show any errors.

```none
[info] dnsproxy: creating udp server socket 0.0.0.0:55
[info] dnsproxy: listening to udp://[::]:55
[info] dnsproxy: creating tcp server socket 0.0.0.0:55
[info] dnsproxy: listening to tcp://[::]:55
[info] dnsproxy: entering udp listener loop on [::]:55
[…]
[info] dnsproxy: entering tcp listener loop on [::]:55
```

Any reason you're listening on a non-standard port?  Do you have a DNS proxy forwarding queries to port 55?

**Comment by Suspectxyzz** [comment]
> Unfortunately, the logs do not show any errors.
> 
> ```
> [info] dnsproxy: creating udp server socket 0.0.0.0:55
> [info] dnsproxy: listening to udp://[::]:55
> [info] dnsproxy: creating tcp server socket 0.0.0.0:55
> [info] dnsproxy: listening to tcp://[::]:55
> [info] dnsproxy: entering udp listener loop on [::]:55
> […]
> [info] dnsproxy: entering tcp listener loop on [::]:55
> ```
> 
> Any reason you're listening on a non-standard port? Do you have a DNS proxy forwarding queries to port 55?

![NVIDIA_Share_wOtWevzT6Z](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/9db74521-5623-461d-b2aa-2fd488bb634d)

before I didn't have the port open for 55 and it worked, now I opened it and still in vain

![NVIDIA_Share_dA3uU0kJEn](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/f8e24c74-b8f3-429f-aa8b-177a57588c98)
only "rDNS" works, as you can see

**Comment by Suspectxyzz** [comment]
do you have any ideas what I could do? 
suddenly it didn't work anymore, I didn't change anything on the router, but I think it's a "dhcp" problem, I also tried with an older version but nothing...
![image](https://github.com/AdguardTeam/AdGuardHome/assets/45514952/0cb71214-8022-4b5a-95ff-20370d3a5593)

**Comment by ainar-g** [comment]
I'm not sure I got the answer.  What is forwarding queries from port 53, on which DNS clients expect a DNS server to be, to port 55?

Also, I'm not sure if it's just missing on your screenshot or not, but you need both TCP and UDP for DNS (and also QUIC) to work.
