### ISSUE TITLE
PTR response issues for specific upstream DNS servers

### ISSUE THREAD

**Issue by MiKing233** [AdguardTeam/AdGuardHome#6309]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.39

### Action

對於所有設備的默認上游伺服器, 我的設定如下
```typescript
# NanoPiR4S-Dnsmasq
10.128.20.2:54
``` 

除此之外我還單獨為一些設備做了其他設定, 在設置-客戶端設置中, 設定如下
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/2c544e54-3a50-459c-9748-9c1ab373b96a)
對於它的上游DNS伺服器
```typescript
#ChinaTelecomDNS
#dns1.ctcdma.com
218.2.2.2:53
#dns2.ctcdma.com
218.4.4.4:53
#AliDNS
#public1.alidns.com
223.5.5.5:53
#public2.alidns.com
223.6.6.6:53
``` 

### Expected result

在以往的版本中, 對於這樣單獨設定過的客戶端DNS請求, 會根據演算法在我設定的四個上游DNS伺服器中選擇, PTR請求也不例外

### Actual result

在v0.107.39中, 這樣設定的客戶端, PTR請求回應的DNS伺服器將變爲對於所有設備設定的默認上游伺服器, 而不是單獨為其設定的四個伺服器内
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/46c24770-e40d-4f19-a660-6b7930d1f402)
我之所以這樣設定, 是因爲我不希望此設備通過PTR請求來知曉網域内的各設備主機名, 以往的版本PTR查詢將會被這樣的單獨設定直接轉交給外部DNS, 從而使得PTR請求主機名得到錯誤的結果, 這是我的預期

**Comment by ainar-g** [comment]
@EugeneOne1, please investigate if this behaviour had changed recently.

**Comment by EugeneOne1** [comment]
@MiKing233, unfortunately we can't reproduce this behaviour.  Could you please send us the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) that captures the invalid routing?  Isn't it also possible that you have changed the default [set of subnets](https://github.com/adguardTeam/adGuardHome/wiki/Configuration#rdns-private) that are considered private?

**Comment by MiKing233** [comment]
@EugeneOne1 已將verbose log以郵件發送至devteam@adguard.com, Title:AdGuardHome Issues #6309 verbose log

**Comment by ainar-g** [comment]
@MiKing233, thank you, we have received your logs.  Just to be clear: are you claiming that this behavior has changed in v0.107.39?  That is, if you rollback to v0.107.38, does it work the way you describe in the “Expected result” section?

**Comment by SCPdesign** [comment]
Rolling back to v0.107.38 fixed this for me.

quic://94.140.14.14
quic://94.140.15.15
quic://dns.adguard.com
quic://dns.adguard-dns.com


I'm on FreeBDS. Could not use the new version at all. Failure all around.

**Comment by MiKing233** [comment]
@ainar-g 是的, 在之前的版本中它工作的很好, 對於特定的客戶機, 它只會在我指定的幾個DNS伺服器中進行查詢, 而現在對於PTR請求的回應會出現指定列表之外的DNS伺服器, 在此期間我只是更新了我的ADGH版本至v0.107.39, 我沒有修改任何配置文件, 直到我檢查此設備的查詢日志才發現此問題

**Comment by EugeneOne1** [comment]
@MiKing233, Hi and sorry for the late reply.  AdGuard Home does indeed route all PTR requests for private addresses to the private RDNS upstream servers, regardless of the client's custom upstream settings.  However, trying to reproduce this on versions `v0.107.0`, `v0.107.36`, `v0.107.37` and `v0.107.38` resulted in the same behavior.  Could you please help us a bit more and capture the verbose log on one of the working versions, as the current behavior, as I said, is actually decent.

Probably my reproduction steps are wrong:
 1. Add the client defined by IP, set the custom upstream server (**1**) to it;
 2. set another upstream server (**2**) for all PTR requests for private addresses.

Then request:
 * PTR for private address (e.g. 10.0.0.1), which will be forwarded to server **2**;
 * PTR for non-private address (e.g. 8.8.8.8), which will be forwarded to server **1**.
 
Also do you use a custom set of private networks or DNS64 functionality?

**Comment by EugeneOne1** [comment]
@MiKing233, I see, and I actually think that the custom private RDNS upstream configuration is worthy of a separate feature request.  However, the behavior you describe may be caused by another uncaught bug that was unintentionally fixed in `v0.107.39`, so we would still like to see the verbose log of this behavior, e.g. captured on [`v0.107.38`](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.38).

**Comment by MiKing233** [comment]
> v0.107.38

很抱歉, 我嘗試將版本回退到[v0.107.38](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.38).來獲取詳細日志, 但我發現回退后行爲沒有差異, 我嘗試回退到更舊的版本例如[v0.107.36](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.36).但我的配置文件無法再工作于此版本.

對於這個問題, 我還可以提供一些細節:
對於默認的客戶端, 即未進行自定義, 使用全局設定的DNS伺服器的客戶端, 當他們發起私有地址的PTR請求時, 在log中將被顯示爲重寫(rewrite)並有藍色的佈景
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/b55b7dc6-e259-48f9-8a12-65d8c9c50d1f)

如對於我自定義過的客戶端, 他們并沒有被標識為重寫, 僅僅是正常的已處理, 也沒有藍色佈景
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/1d1eae25-4fc3-4cb3-a373-b510babcbdc7)

但我記得非常清楚, 在先前的版本中, 這應當被返回一個錯誤, 因爲自定義的客戶端指定的上游伺服器例如8.8.8.8, 是不可能響應私有地址的PTR請求的, 此客戶端也只能在指定的上游伺服器例如8.8.8.8中發起請求, 如不是現在這樣能被我當前設備的Dnsmasq相應得到私有地址設備主機名
![image](https://github.com/AdguardTeam/AdGuardHome/assets/26044744/f9c10566-e1e6-41cc-b70f-5e9bce68f3f2)

正如之前所説的, 無論這是否被視爲是一個問題, 我認爲最好的解決方案是"在自定義客戶端中的上游DNS伺服器標籤頁中, 增加一個新的選項, 用於給不同的自定義客戶端設定local_ptr_upstreams", 我想知道這是否應該新開一個issues?

**Comment by EugeneOne1** [comment]
@MiKing233, I can't recall such a feature request, so you may freely fill it.

Regarding the issue, I think I got a few ideas.  Firstly, rewriting the responses has nothing to do with domain-specific upstream routing, so the behavior changes could be related to custom filtering rules or `/etc/hosts` file.  Have you changed any of those, or, probably, switched the global filtering settings for some clients?

**Comment by MiKing233** [comment]
@EugeneOne1 在我的印象裏是沒有對任何配置進行修改的包含`/etc/hosts`文件.

稍後我會提交新的功能請求, 非常感謝您的協助!
