### ISSUE TITLE
Installation Wiki, script and wizard for Raspberry Pi with v0.93

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#631]
Following the Wiki steps for Raspberry Pi, there is a missing step:

Before you can run `sudo ./AdGuardHome -s install`, you need to run `cd AdGuardHome` into the AdGuardHome folder that was unpacked, otherwise you will get a `sudo: ./AdGuardHome: command not found` error without doing so.

Also, after running the installation script, it would be nice if it had a little more detail on what it did, eg. "AdGuard Home is now creating a service...", "AdGuard Home installation was successful. AdGuard Home is now running and will automatically run on startup.". Then following it up by telling the user to visit the IP 192.X.X.X:3000 via a web browser to continue setup for the wizard.

Lastly, during the web browser setup wizard, it ran into its own error if port 80 is already is use. Since we are visiting the setup via port 3000 already, when clicking next and it can't bind port 80 (Pi-hole leaves this occupied after uninstalling), it tries to use port 3000 instead, and you get a 'port already in use' error. You cannot continue setup unless you change it to a different port, so this should either be that the Wizard uses a different port for setup and allows port 3000 for the Web Interface, or vice versa.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/685
