### ISSUE TITLE
Post update, update check failure issue has popped up. 

### ISSUE THREAD

**Issue by saketkoria** [AdguardTeam/AdGuardHome#6313]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

 v0.107.39

### Action

Dear Team
Post the update, i have started getting update check fail issue. please help

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

THough on the latest version, yet should have done the check successfully.

### Actual result

Check fail. CHeck internet connection

**Comment by daryll-swer** [comment]
I can confirm, I'm facing the same issues. The latest update v0.107.39 cannot consistently reach upstream DNS.

<img width="400" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/80836254/5e80f70f-86c3-4e53-a67d-b4a26f78f851">

**Comment by pekkle-hksar** [comment]
tested with ipv4 upstream is working.
but fail if DoT or DoH, wonder DoQ also failed

**Comment by ainar-g** [comment]
@saketkoria, we cannot reproduce these.  Please [enable verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see what kind of errors are there when you check for updates.

**Comment by glasseffects** [comment]
Apparently, AGH has come unusable. Same settings, different locations, but same ISP, and tow days back it stopped working. Either something changed on ISP side, or AGH underwent a change. If anyone knows what kind of debug information is required (and how to obtain it), I can do so.

Thanks.

**Comment by SCPdesign** [comment]
Rolling back to v0.107.38 fixed this for me.

quic://94.140.14.14
quic://94.140.15.15
quic://dns.adguard.com
quic://dns.adguard-dns.com


I'm on FreeBDS. Could not use the new version at all. Failure all around.

**Comment by pekkle-hksar** [comment]
> tested with ipv4 upstream is working. but fail if DoT or DoH, wonder DoQ also failed

tested again with latest edge version and everything is working fine now

**Comment by ainar-g** [comment]
Thanks for testing, @pekkle-hksar!  It is likely that the issue could be with HTTP/3.

@saketkoria, can you please try the latest Edge builds and see if it fixes the issue for you?
