### ISSUE TITLE
Support query pipelining per RFC 7766

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdGuardHome#6314]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When rfc7766(dns over tcp and dns over tls) is supported
https://www.rfc-editor.org/rfc/pdfrfc/rfc7766.txt.pdf

### Proposed solution

Join rfc7766

**Comment by ainar-g** [comment]
I assume you mean query pipelining, as described in [section 6.2.1.1](https://datatracker.ietf.org/doc/html/rfc7766#section-6.2.1.1).  We'll probably need to modify `dnsproxy` for that.
