### ISSUE TITLE
HTTP Redirect is 'Always ON'

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#6316]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.39

### Action

browse to the HTTP site

### Expected result

I expect but to be redirected to the HTTPS site

### Actual result

I am automatically redirected to the HTTPS site 

### Additional information and/or screenshots

Since the latest update I am redirected to the HTTPS page. Tried checking and unchecking the auto redirect option in the config but this had no affect.

**Comment by ainar-g** [comment]
This is likely due to HSTS.  Please clear the HSTS status for your AGH site.  [This article](https://appuals.com/how-to-clear-or-disable-hsts-for-chrome-firefox-and-internet-explorer/) may be helpful.
