### ISSUE TITLE
adguard on home assistant doesn't show anything 

### ISSUE THREAD

**Issue by julerobb1** [AdguardTeam/AdGuardHome#6317]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

home assistant 

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

I expected it to act as a dns server, and show me the quereies I've done. 

### Actual result

I've waited an hour for any queries to appear snd and there's nothing, everything on it says 0 

### Additional information and/or screenshots

adguard is hosted on home assistant os docker image runnin in a vmware virtual machine

**Comment by overwatch3560** [comment]
Have you tried configuring your devices to use adguard dns?
