### ISSUE TITLE
Add support for $dnstype to "DNS Settings" due to an ongoing international emergency DDoS situation

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#6318]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

There's apparently been a **massive** DDoS attempt against Cisco from seemingly **every single ISP** in Brazil for the past 1½ weeks or so, to the point where even my 2021 Ryzen 5 CPU is brought to its knees, and where 16 GB RAM can get stuffed to the point where PC audio begin to stutter. My server has received more than ***1,000,000*** TXT-type spam requests for `cisco.com` in just the past 7 days, virtually all of them from Brazil.

Worth noting is that all of the spam request IPs use regular DNS (i.e. not DoH, DoT, nor DoQ) and IPv4 addresses.

### Proposed solution

• Allow specifying something like `$dnstype` and/or `$connection` in Denied Clients, so I can do stuff like `45.128.0.0/9$dnstype=TXT` or `45.128.0.0/9$connection=regular`.
• Allow specifying `$dnstype` in DNS Settings → Blocked Domains.

### Alternatives considered and additional information

This is an **ongoing emergency situation**. I refuse to let this issue report linger still for 2 years as with most other AGH reports.

**Comment by DandelionSprout** [comment]
Hmm… turns out that adding `|cisco.com|$dnstype=TXT` to DNS Settings → Blocked Domains actually *does* work already after all.

I'll keep one of the Slack groups updated if there's any further developments.

**Comment by ainar-g** [comment]
Yes, the *Blocked domains* field supports DNS type.  `NS .` queries are a bit tricker, as they require the rather unintuitive `|.^` syntax, but these should work as well, if anyone uses these for attacks.
