### ISSUE TITLE
AdBlock-Style DNS Rewrites Wildcard/Exception logic broken 

### ISSUE THREAD

**Issue by mxbchr** [AdguardTeam/AdGuardHome#6328]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.39

### Action

DNS Lookup

Configuration specified below.

### Expected result

It should resolve to only one A record, the specified IP AdBlock-Style DNS Rewrites, that can be set under "Custom filtering Rules".

### Actual result

It gave back two A records, the specified exception Record in the AdBlock-Style DNS Rewrites, that can be set under "Custom filtering Rules", plus the wildcard rule record itself.
It seems it is no longer possible to make more specified exceptions.

### Additional information and/or screenshots

Short Disclaimer:
This is not a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/6226
The referenced issue regarded the DNS Rewrites Table Wildcard/Exception logic. This issue Regards the AdBlock-Style DNS Rewrites Wildcard/Exception logic, that can be set under "Custom filtering Rules" which seems to be broken as well. The Issue itself is quite similar though. While it seems to be fixed for the DNS Rewrites Table, it is still present for the AdBlock-Style DNS Rewrites, that can be set under "Custom filtering Rules".
I mentioned this first here: https://github.com/AdguardTeam/AdGuardHome/issues/6226
But I tried downgrading to v0.107.38 now, with the same result. So It was not the v0.107.39 update that broke it, as I first suspected it, it was just the first time I noticed after that.
It probably was broken by the v0.107.37 update that broke the DNS Rewrites Table Wildcard/Exception logic as well. 

....

I use AdGuard Addon on HomeAssistantOS.

I have set a few DNS rewrites so that the selfhosted services can be accessed by there internal IP while I'm home. Most services are run through a reverse proxy at 10.0.2.8 with hostnames *.example.org, the vnp server is hosted on 10.0.2.1 with hostname vpn.example.org. Theres a few more services that are hosed under a different IP, but I'll stick with the vpn example for simlicity.

So I set the rules:
```
||example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.8
||vpn.example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.1
```

This worked perfectly fine when I set it up a few weeks ago. anything.example.org returned 10.0.2.8, vpn.example.org returned 10.0.2.1.
Now the DNS query suddenly gives back two A records:

```
Non-authoritative answer:
Name: vpn.example.org
Address: 10.0.2.1
Name: vpn.example.org
Address: 10.0.2.8
```

Setting the rule to:
`||vpn.example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.1,important`
does not solve the issue.

Neither does:
```
@@||vpn.example.org^$dnsrewrite=10.0.2.8
||vpn.example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.1
```
both with and without important modifier.
As well as:
```
||example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.8
|vpn.example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.1
```
Or one of these
```
@@||vpn.example.org^$dnsrewrite=NOERROR;A;10.0.2.8,important
@@||vpn.example.org^$dnsrewrite=10.0.2.8,important
@@||vpn.example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.1
@@||vpn.example.org^$dnsrewrite=10.0.2.8,client=10.0.2.0/24
```
plus
`||vpn.example.org^$client=10.0.2.0/24,dnsrewrite=NOERROR;A;10.0.2.1`

Details from query log:
```
Response details
Status: Rewritten
Elapsed: 0.15 ms
Response code: NOERROR
Rule(s):
||vpn.example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.1
||example.org^$client=10.0.2.0/24|192.168.3.0/24,dnsrewrite=NOERROR;A;10.0.2.8
Custom filtering rules

Response:
A: 10.0.2.1 (ttl=10)
A: 10.0.2.8 (ttl=10)
```

**Comment by ainar-g** [comment]
Seems like a duplicate of #5347 instead.

**Comment by mxbchr** [comment]
> Seems like a duplicate of #5347 instead.

It is. I'm sorry, I didn't search that far back, was too biased it was something recent.

The denyallow modifier actually solves the problem https://github.com/AdguardTeam/AdGuardHome/issues/5347#issuecomment-1377295020

Thank you!
