### ISSUE TITLE
Dark mode not applying for check filter response if rewrite is applied

### ISSUE THREAD

**Issue by hisel-sabermetrics** [AdguardTeam/AdGuardHome#6329]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.40

### Action

1. Set up rewrite for a domain
2. Go to Check the filtering under Custom filtering rules

### Expected result

The response in dark mode

### Actual result

The response is in light mode
![Screenshot](https://github.com/AdguardTeam/AdGuardHome/assets/96913686/894b762e-365b-4737-9ba0-354122e4c6e0)

**Comment by ainar-g** [comment]
The fix will be a part of the upcoming release.
