### ISSUE TITLE
AdGuard Home cannot work for 5 minutes after boot, DNS timeouts (Raspberry Pi)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#633]
When setting the Upstream DNS servers from the default TLS to Cloudflare's DoH (https://cloudflare-dns.com/dns-query), rebooting the Pi causes AdGuard Home to behave unexpectedly once booted.

No clients can use DNS, the DNS requests all timeout. Trying to visit the admin page causes the settings page to freeze and not load for a very long time, with errors about timeouts for version checks to github. If I can get it to eventually load, I need to clear the DoH entry so it reverts back to the default TLS entries.

Once it uses TLS again, all clients can use DNS fine and the AdGuard Home admin interface works normally again.

So DNS-over-HTTPS does not work for me once I restart the Pi.

**Comment by ameshkov** [comment]
Could you please collect AGH logs (preferably, with verbose logging enabled)?

**Comment by ameshkov** [comment]
Tbh, it sounds like some kind of a recursion issue (AGH tries to resolve Cloudflare domain name through itself). What bootstrap DNS server do you have configured?

**Comment by planet0** [comment]
Oops, you are right. I do have 1.1.1.1 as the bootstrap DNS server, does this mean the bootstrap must be different to the Upstream DNS server, or can I use IP addresses instead of the domain name, since the default TLS works at the moment?

eg. instead of `https://cloudflare-dns.com/dns-query`, I set
`https://1.1.1.1/dns-query` and
 `https://1.0.0.1/dns-query`

**Comment by ameshkov** [comment]
> Oops, you are right. I do have 1.1.1.1 as the bootstrap DNS server, does this mean the bootstrap must be different to the Upstream DNS server

Well, actually it should've worked just okay, what matters is that bootstrap DNS shouldn't be 127.0.0.1.

Could you please export logs just in case? We want to make a DOH upstream default so it might be important.

**Comment by planet0** [comment]
> Could you please export logs just in case? We want to make a DOH upstream default so it might be important.

I've done it with verbose, but there is quite a bit of metadata. Could I email it to you so it's not public on here?

From what I see, if you set the DoH without rebooting, it can work fine:
`2019/03/12 09:51:22 [42] proxy.exchangeWithUpstream(): upstream https://cloudflare-dns.com:443/dns-query successfully finished exchange of ;adguardteam.github.io`

But once rebooted you get this instead:
`2019/03/12 09:54:18 [40] proxy.exchangeWithUpstream(): upstream https://cloudflare-dns.com:443/dns-query failed to exchange ;sb.adtidy.org.`

And since the admin interface relies on external connections, it also suffers.

**Comment by ameshkov** [comment]
> I've done it with verbose, but there is quite a bit of metadata. Could I email it to you so it's not public on here?

Sure, please send it to `devteam@adguard.com`

**Comment by planet0** [comment]
Thank you, sent it now.

**Comment by ameshkov** [comment]
Got the log, thank you!

Quick analysis:

1. Bootstrap DNS is okay, it managed to resolve `cloudflare-dns.com`
    ```
    2019/03/12 09:54:08 [40] upstream.lookup(): successfully finish lookup for cloudflare-dns.com in 34 milliseconds using 1.1.1.1:53. Result : [{104.16.112.25 } {104.16.111.25 } {2606:4700::6810:7019 } {2606:4700::6810:6f19 }]
    ```

2. It has successfully connected to the DOH server:
```
2019/03/12 09:54:13 [75] upstream.createDialContext.func1(): Dialing to 104.16.112.25:443
2019/03/12 09:54:13 [75] upstream.createDialContext.func1(): dialer successfully initialize connection to 104.16.112.25:443 in 25 milliseconds
```

3. Then the HTTP request timed out:
```
2019/03/12 09:54:18 [40] proxy.exchangeWithUpstream(): upstream https://cloudflare-dns.com:443/dns-query failed to exchange ;sb.adtidy.org.	IN	 A in 10043665621 milliseconds. Cause: couldn't do a POST request to 'https://cloudflare-dns.com:443/dns-query', cause: Post https://cloudflare-dns.com:443/dns-query: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

It means that the TLS connection was also established without issues, but there's no response from CF to the DNS query.

Is this how it behaves every time or is it just after rebooting the pi?

**Comment by planet0** [comment]
> Is this how it behaves every time or is it just after rebooting the pi?

Once I save the settings for the DoH server to overwrite the existing TLS defaults, it can still function. But, once I either restart the service or restart the Pi, all DNS stops working no matter what I do. Once I set it back to TLS defaults and restart the service or Pi, all is working again.

**Comment by ameshkov** [comment]
@planet0 is it specific to Cloudflare or to any DOH resolver? Have you tried any other DOH server?

**Comment by planet0** [comment]
I tried to use Quad9's DoH and the same issue occurred. Unfortunately I also managed to completely break the entire AdGuard Home service as the default Cloudflare TLS also stopped working and rebooting the Pi wasn't doing anything either. Deleting the .yaml file and setting it up again still didn't work. Reinstalling the service didn't work either.

I reinstalled Pi-hole and the DNS started to work again without a reboot.

I think I need to try using AdGuard Home with a fresh install of Raspbian and not from a previous Pi-hole installation, and revisit this another time.

**Comment by ameshkov** [comment]
Sounds really unusual, I don't understand what can possibly cause all this:( As if something is preventing connecting to non-standard ports or smth like this.

**Comment by planet0** [comment]
It might be how much Pi-hole modifies or configs the Pi, but I won't know until I fresh install... does any over at AdGuard have a Raspberry Pi that could replicate installing Pi-hole, uninstalling it and then trying to run AdGuard Home for this?

**Comment by ameshkov** [comment]
@planet0 yeah, I guess we can try that. Btw, have you been using the built-in DHCP in pi-hole and AGH?

@szolin could you please try doing it?

**Comment by planet0** [comment]
> Btw, have you been using the built-in DHCP in pi-hole and AGH?
For Pi-hole I was using the built-in DHCP as it works really good, for this instance I used my TP-Link to manage DHCP for AdGuard Home as there are still some bugs to iron out, and no ability for static leases

The only other thing I can think of is that I was able to use 'cloudflared' alongside Pi-hole so I could use DNS-over-HTTPS for 1.1.1.1, with this guide: https://docs.pi-hole.net/guides/dns-over-https/

It was working really well.

I did uninstall the service and remove all cloudflared files before trying AdGuard Home, but the fact that cloudflared can work for DoH and not AdGuard Home is confusing.

**Comment by ameshkov** [comment]
@planet0 btw, any idea where `Koala` postfix comes from in the DNS questions after the service restart?

```
;; QUESTION SECTION:
;adguardteam.github.io.Koala.	IN	 A
```

**Comment by ameshkov** [comment]
Ah, nvm

**Comment by planet0** [comment]
It was the DHCP Domain name, yeah.

**Comment by ameshkov** [comment]
It'd interesting to check a couple more things:

1. Try using `https://1.1.1.1/dns-query` as a DOH upstream
2. After restart try this command to check connectivity to CF DNS: `openssl s_client -connect 104.16.112.25:443 -servername cloudflare-dns.com`. Make sure that this command is executed under the same user as AGH.

**Comment by planet0** [comment]
Okay, I've played around with it some more after uninstalling Pi-hole again.

I found the root issue, and it's that when I reboot the Pi, AdGuard Home is unable to use the DNS port for about 5 minutes.

Once 5 minutes passes, all DNS traffic works and the version checks in the Admin page pass. I used v0.92-hotfix1 so I can see the banner appear for the new version.

**Comment by ameshkov** [comment]
> to use the DNS port 

The issue is valid for DOH only, right?
Is it okay when you select a plain DNS upstream?

> yet Pi-hole is able to load instantly

Were you using it's own DHCP when testing?

**Comment by planet0** [comment]
It got to the point where nothing was working, including regular upstreams or changing the bootstrap. After 5 minutes, all DNS types can work.

Pi-hole was still using the TP-Link DHCP device, I simply ran the install command and once finished, dns started to work. Rebooting the Pi also works seconds after finishing boot.

**Comment by ameshkov** [comment]
Do they both (AGH and Pi-Hole) work under the same user?

**Comment by planet0** [comment]
> Do they both (AGH and Pi-Hole) work under the same user?
> Is it root?

From what I can see and from looking at their [install script](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh), I believe Pi-hole uses their own user (cloudflared does too).

Line 1708 in that script adds a user 'pihole'.

Also looking at this issue over at Pi-hole (https://github.com/pi-hole/pi-hole/issues/1547), they mention that they use setcaps for binding ports, which I personally do not understand but might shed some light in how they operate it.

> FTLDNS now runs as non-root but with setcap's for binding to lower ports and that's a big exposure reduced.

**Comment by planet0** [comment]
I think this is a wider non-AGH related issue, as I have had the same issue with cloudflared. Others are experiencing the same issue as me, so I suspect something Pi related and not an issue with AdGuard Home.

https://github.com/cloudflare/cloudflared/issues/23

**Comment by ameshkov** [comment]
Seems to be some consequence of pi-hole installation, but I still can't understand what's that exactly.

I do think it needs to be reported to pi-hole and not to cloudflared, they'll be as clueless as we are

**Comment by planet0** [comment]
This is a greater issue, as it is Raspbian related.

I fresh installed Raspbian from NOOBS, seemed to be a package from Nov 2018.
AdGuard Home working perfect, cloudflared working perfect.

Now I updated my Pi to the latest, and the same issue has occurred right away with AdGuard Home.

I took note of what was updated for reference:

``
apt apt-transport-https apt-utils base-files bluez-firmware curl gnupg gnupg-agent gpgv libapt-inst2.0 libapt-pkg5.0
  libc-bin libc-dev-bin libc-l10n libc6 libc6-dbg libc6-dev libcurl3 libcurl3-gnutls libpam-systemd libperl5.24
  libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0 libraspberrypi-bin libraspberrypi-dev
  libraspberrypi-doc libraspberrypi0 libssl1.0.2 libssl1.1 libsystemd0 libudev1 libwbclient0 libxapian30 locales
  multiarch-support openssh-client openssh-server openssh-sftp-server openssl perl perl-base perl-modules-5.24
  policykit-1 python-rpi.gpio python3-six raspberrypi-bootloader raspberrypi-kernel raspberrypi-sys-mods raspi-config
  raspi-copies-and-fills samba-common ssh systemd systemd-sysv tzdata udev wireless-regdb wpasupplicant
``

@ameshkov, so it seems like it could be easily replicated now, just update Raspbian to the latest versions via `sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade`, then `sudo reboot` and watch AdGuard Home not work for 5 minutes. 😢

**Comment by planet0** [comment]
Also need to figure out why services like _AGH_ and _cloudflared_ experience this issue, but _Pi-hole_ is able to avoid this 'bug' somehow in its functionality. Might help determine what exactly is the cause.

**Comment by saltama** [comment]
I've seen the same issue since 0.92 too (the first version i tried) and while i had installed pi-hole first too I doubt that pi-hole could be the cause (can't imagine how?!). Regarding the user, i'm starting it with root, i guess they are using `cap_net_bind_service` to be able to open the privileged 53 port with another user.

**Comment by szolin** [comment]
Hello!

When AGH is installed as a service and DHCP server is enabled, the first run fails because network interface isn't set up yet.  So the system tries to restart the service after some time.

After I've disabled DHCP server in my config, AGH starts quickly after reboot and there are no attempts by OS to restart the service, because it doesn't fail.

Here's my log:

```
Mar 28 14:43:08 raspberrypi AdGuardHome[347]: 2019/03/28 14:43:08 347#19 [info] Couldn't find IPv4 address of interface eth0 &{Index:2 MTU:1500 Name:eth0 HardwareAddr:b8:27:eb:40:2a:a2 Flags:up|broadcast|multicast}
Mar 28 14:43:08 raspberrypi AdGuardHome[347]: 2019/03/28 14:43:08 347#19 [fatal] Couldn't start DHCP server, cause: Couldn't find IPv4 address of interface eth0 &{Index:2 MTU:1500 Name:eth0 HardwareAddr:b8:27:eb:40:2a:a2 Flags:up|broadcast|multicast}
Mar 28 14:43:08 raspberrypi systemd[1]: AdGuardHome.service: Main process exited, code=exited, status=1/FAILURE
Mar 28 14:43:08 raspberrypi systemd[1]: AdGuardHome.service: Unit entered failed state.
Mar 28 14:43:08 raspberrypi systemd[1]: AdGuardHome.service: Failed with result 'exit-code'.
Mar 28 14:45:16 raspberrypi systemd[1]: AdGuardHome.service: Service hold-off time over, scheduling restart.
```

@planet0 
Please run this command:

`grep AdGuard /var/log/daemon.log`

Do you see any lines similar to 'AdGuardHome.service: Service hold-off time over, scheduling restart.' ?

**Comment by planet0** [comment]
@szolin are you on an up to date Raspbian build and packages via apt-get? I can replicate the issue every time on fresh raspbian installs+ installing AGH + updating + rebooting, regardless of DHCP being enabled or not.

I’ll need to check the log as soon as I can to see what there is regarding AGH.

**Comment by saltama** [comment]
Same here, i've never enabled DHCP since i'm using the one on my router.
I have configured the service like this:
```
[Unit]
Description=AdGuardHome DNS
After=network.target syslog.target nss-lookup.target

[Service]
Type=simple
Restart=always
ExecStart=/opt/AdGuardHome/AdGuardHome

[Install]
WantedBy=multi-user.target
```

And this is the non-verbose log from when i restarted a few minutes ago:
```
-- Logs begin at Thu 2019-03-28 14:04:15 GMT, end at Thu 2019-03-28 14:12:01 GMT. --
Mar 28 14:04:46 raspberrypi systemd[1]: Started AdGuardHome DNS.
Mar 28 14:04:47 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:47 [info] AdGuard Home, version v0.94-4-g0c86-dirty
Mar 28 14:04:48 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:48 [info] Upstream 0: 9.9.9.9:853
Mar 28 14:04:48 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:48 [info] Upstream 1: 1.1.1.1:853
Mar 28 14:04:48 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:48 [info] Upstream 2: 149.112.112.112:853
Mar 28 14:04:48 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:48 [info] Upstream 3: 1.0.0.1:853
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Start DNS server periodic jobs
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Starting the DNS proxy server
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] The server is configured to refuse ANY requests
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] DNS cache is enabled
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Creating the UDP server socket
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Listening to udp://[::]:53
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Creating the TCP server socket
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Listening to tcp://[::]:53
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] AdGuard Home is available on the following addresses:
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Go to http://127.0.0.1:3000
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Go to http://10.0.0.165:3000
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Entering the UDP listener loop on [::]:53
Mar 28 14:04:59 raspberrypi AdGuardHome[449]: 2019/03/28 14:04:59 [info] Entering the tcp listener loop on [::]:53
Mar 28 14:05:09 raspberrypi AdGuardHome[449]: 2019/03/28 14:05:09 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:37922->127.0.0.1:53: i/o timeout
Mar 28 14:05:09 raspberrypi AdGuardHome[449]: 2019/03/28 14:05:09 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:37922->127.0.0.1:53: i/o timeout
Mar 28 14:05:59 raspberrypi AdGuardHome[449]: crypto/rand: blocked for 60 seconds waiting to read random data from the kernel
Mar 28 14:06:09 raspberrypi AdGuardHome[449]: 2019/03/28 14:06:09 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:58905->127.0.0.1:53: i/o timeout
Mar 28 14:06:09 raspberrypi AdGuardHome[449]: 2019/03/28 14:06:09 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:58905->127.0.0.1:53: i/o timeout
Mar 28 14:07:09 raspberrypi AdGuardHome[449]: 2019/03/28 14:07:09 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:38551->127.0.0.1:53: i/o timeout
Mar 28 14:07:09 raspberrypi AdGuardHome[449]: 2019/03/28 14:07:09 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:38551->127.0.0.1:53: i/o timeout
Mar 28 14:08:12 raspberrypi AdGuardHome[449]: 2019/03/28 14:08:12 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:36919->127.0.0.1:53: i/o timeout
Mar 28 14:08:12 raspberrypi AdGuardHome[449]: 2019/03/28 14:08:12 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:36919->127.0.0.1:53: i/o timeout
Mar 28 14:09:11 raspberrypi AdGuardHome[449]: 2019/03/28 14:09:11 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:33154->127.0.0.1:53: i/o timeout
Mar 28 14:09:11 raspberrypi AdGuardHome[449]: 2019/03/28 14:09:11 [info] Failed to update filter https://hosts-file.net/ad_servers.txt: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:33154->127.0.0.1:53: i/o timeout
Mar 28 14:10:11 raspberrypi AdGuardHome[449]: 2019/03/28 14:10:11 [info] Couldn't request filter from URL https://hosts-file.net/ad_servers.txt, skipping: Get https://hosts-file.net/ad_servers.txt: dial tcp: lookup hosts-file.net on 127.0.0.1:53: read udp 127.0.0.1:37166->127.0.0.1:53: i/o timeout
```

Still not working after 20 minutes this time, with the AdGuardHome process that has hundreds of threads as shown in htop (vs the usual 8).

**Comment by saltama** [comment]
And this is the log of the service after a reboot, but WITH verbose enabled: 
[adh3.log.txt.zip](https://github.com/AdguardTeam/AdGuardHome/files/3018487/adh3.log.txt.zip)

Not much too see other than some requests failing after 200s. Still hundreds of threads in htop.
Both these tests are using only tls and parallel enabled.

But... i got it working right at boot with two DoH servers and no parallel, first time ever.

Edit: Tried again after 2 minutes, it stopped working again. :(

**Comment by szolin** [comment]
In the log file above there are 1228 attempted connections to 4 upstream servers from function AdguardTeam/dnsproxy/upstream.createDialContext() - 4 connections per 1 DNS request, plus 16 times AGH tried to get an update for a filter.

148 out of those 1228 requests failed with "i/o timeout" error after ~3 minutes.
It means that 1k requests are still pending (and their socket fd's are still opened) while they are waiting for network I/O.

So looking at this log I can only see that AGH simply can't reach the Internet servers - they all fail after timeout.
I recommend using a network traffic sniffer like tcpdump or wireshark to ensure that those connection attempts are really delivered to the network interface.  And if they do, we need to check whether any packets from the upstream servers are delivered back to AGH.

Currently we don't know where the packets get stuck, so the first step is to find where this issue comes from.

**Comment by ameshkov** [comment]
@planet0 @saltama I just stumbled upon this comment in the similar issue of CF repo:
https://github.com/cloudflare/cloudflared/issues/23#issuecomment-471933889

> BUT after the connection is restored it still doesn't return DNS responses. I can fix it by pinging 1.0.0.1 (not restarting cloudflared) . This makes me suspect a lower layer issue - routing, perhaps?

Could you please check if it helps to ping 1.1.1.1/1.0.0.1?

**Comment by saltama** [comment]
> Could you please check if it helps to ping 1.1.1.1/1.0.0.1?

Doesn't work for me, the pings go through but adguard is still blocked(after 20 mins it still is) with the hundreds of threads.

> It means that 1k requests are still pending (and their socket fd's are still opened) while they are waiting for network I/O.

Should these be there in the first place? I mean, if we have another thread trying to make i/o to an unresponding address, should we open more? (also, shouldn't we have some limit?)
But ok, i don't even know what creates those threads and why so... nevermind.

> I recommend using a network traffic sniffer like tcpdump or wireshark to ensure that those connection attempts are really delivered to the network interface.

As last resort yes.

**Comment by planet0** [comment]
Quickly adding that it is possible to ping 1.1.1.1/1.0.0.1 during this time, but it doesn’t affect AGH regardless until 5 minutes after boot.

**Comment by ameshkov** [comment]
> Should these be there in the first place? I mean, if we have another thread trying to make i/o to an unresponding address, should we open more? (also, shouldn't we have some limit?)

@saltama well, yeah, but it will only fix one of the symptoms, it will not fix the root cause.

Also, I think the i/o timeout issue you're experiencing is different from this one.

There are two different issues:

1. No connection for the first 5 min after RPi reboot.
2. i/o timeout errors that starting to appear after a few minutes of working without issues.

We tried updating our test RPi and installing the same packages, but still, we weren't able to reproduce it. So it seems we really need your help to figure what's wrong.

@planet0 @saltama could you please collect tcpdump for us?

Here's what needs to be done:
1. Wait until the issue is reproduced.
2. Run `tcpdump -i IFACE -w FILE.pcap` where IFACE is the name of the network interface, FILE is the dump filename.
3. We'll need this file to analyze.

**Comment by ameshkov** [comment]
Sure, np.

Btw, as I recall, you can limit tcpdump to specific IP addresses so that there will be no risk in leaking anything private (communication with DOH/DOT is encrypted anyways).

**Comment by planet0** [comment]
Haven't had the chance to test it yet, but Raspbian had a [new update released on April 8](https://downloads.raspberrypi.org/raspbian/release_notes.txt), I would like to see if that has made any changes regarding this issue.

Forgot to mention, I'm running Raspbian Lite instead of the desktop version.

**Comment by planet0** [comment]
Tried with cloudflared, still experiencing the same issue even with the recent updates for Raspbian and cloudflared. Going to assume that AdGuard Home would still experience the same issue then. Mentioned it at https://github.com/cloudflare/cloudflared/issues/91.

**Comment by szolin** [comment]
@planet0 Does the issue still persist?  If yes, how about that tcpdump data for DNS requests?  You can use tcpdump's filters (IPs, ports) and give us only related information.

**Comment by planet0** [comment]
@szolin I haven't forgotten about this! I've found some time to work on this now - would you be able to help me figure out how to get the required tcpdump data from a Raspberry Pi running Raspbian Lite?

**Comment by planet0** [comment]
Some good news @szolin @ameshkov, it seems that with Raspbian Buster, I no longer need to wait 5 minutes on boot - network connections are going through just fine.  🎉

**Comment by szolin** [comment]
Glad to hear!

**Comment by saltama** [comment]
Can confirm this too!

**Comment by i553041** [comment]
> When setting the Upstream DNS servers from the default TLS to Cloudflare's DoH (https://cloudflare-dns.com/dns-query), rebooting the Pi causes AdGuard Home to behave unexpectedly once booted.
> 
> No clients can use DNS, the DNS requests all timeout. Trying to visit the admin page causes the settings page to freeze and not load for a very long time, with errors about timeouts for version checks to github. If I can get it to eventually load, I need to clear the DoH entry so it reverts back to the default TLS entries.
> 
> Once it uses TLS again, all clients can use DNS fine and the AdGuard Home admin interface works normally again.
> 
> So DNS-over-HTTPS does not work for me once I restart the Pi.

I have this problem too,I found that when u reboot the Pi,systemd-resolved this process will run,listen udp port 53,it make AGH cannot use port 53,it make AGH fail to run,so use this command to disable systemd-resolved.

sudo service systemd-resolved stop
sudo systemctl disable systemd-resolved
sudo reboot

after reboot,everything will back to normal

sorry for my bad english.

**Comment by planet0** [comment]
@i553041 I'm not sure if it's universal, but it seems that on my vanilla install of Raspbian, systemd-resolved is already disabled on my end. But this is still good, thank you.
