### ISSUE TITLE
Table titles should be fixed instead of disappearing with scrolling

### ISSUE THREAD

**Issue by devioa** [AdguardTeam/AdGuardHome#6337]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-a.763+01e60cd1

### Action

![动画](https://github.com/AdguardTeam/AdGuardHome/assets/38558065/9aeb9ba7-3988-46aa-91ba-7754247ec30f)

### Expected result

It should be fixed instead of disappearing with scrolling

### Actual result

disappearing with scrolling

**Comment by EugeneOne1** [comment]
@devioa, hello and thanks for the report.  Could you please try the latest edge release and tell if it fixes the headers?

**Comment by devioa** [comment]
> @devioa, hello and thanks for the report. Could you please try the latest edge release and tell if it fixes the headers?

yes, I am sure it has been fixed, thanks for your work!
