### ISSUE TITLE
Top Clients small view

### ISSUE THREAD

**Issue by TheCeet** [AdguardTeam/AdGuardHome#6338]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.40

### Action

Update to v0.107.40

### Expected result

Wider text area, name of the client like the past.

### Actual result

Since release 0.107.40, the ‘Top clients’ name view on a mobile device is not that clear.  
Device: iPhone 13 Pro, Safari. 
see:
![IMG_5246](https://github.com/AdguardTeam/AdGuardHome/assets/82833275/7acbca9d-9458-49c3-b789-21e2f815f1d6)

**Comment by EugeneOne1** [comment]
@TheCeet, hello and apologies for late response.  We've improved the Top Clients' names appearance in the latest edge, could you please check it out?

**Comment by TheCeet** [comment]
@EugeneOne1 I’m unable to install edge builds. You may close this. 
When next update is available, I’ll check it and re-open it if necessary.
Thanks in advance for the fix!

**Comment by TheCeet** [comment]
![IMG_5336](https://github.com/AdguardTeam/AdGuardHome/assets/82833275/d27105c6-9b13-4344-b106-44b7b7e0edab)
@EugeneOne1 
I updated to v0.107.41.
It's a little better but still (my opinion) the request count field is wide. And I think it could shrink a little to fit it better.

Here, I edited the width which is perfect for me:
![IMG_5337](https://github.com/AdguardTeam/AdGuardHome/assets/82833275/abb85d46-7b4d-439e-b663-c38883eb8923)
