### ISSUE TITLE
Using ‘Use custom IP for EDNS’ may cause domain resolution to return REFUSED/使用“为EDNS使用自定义IP”时 可能导致域名解析返回 REFUSED

### ISSUE THREAD

**Issue by bcseputetto** [AdguardTeam/AdGuardHome#6345]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.40

### Action

使用“为EDNS使用自定义IP”时 可能导致域名解析返回 REFUSED
为了使开发人员更好地理解我暂时将AGH的界面语言更改到了英文
________
Using ‘Use custom IP for EDNS’ may cause domain name resolution to return REFUSED
To help developers understand better, I have temporarily changed the interface language of AGH to English.
```
ubuntu@tk2-410-46346:~$ sudo netstat -anp |grep :53 |grep LISTEN
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      2105045/AdGuardHome 
ubuntu@tk2-410-46346:~$ nslookup cl3-cdn.origin-apple.com.akadns.net
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find cl3-cdn.origin-apple.com.akadns.net: REFUSED

ubuntu@tk2-410-46346:~$ nslookup cl3-cdn.origin-apple.com.akadns.net 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
cl3-cdn.origin-apple.com.akadns.net     canonical name = cl3-cdn-us.origin-apple.com.akadns.net.
cl3-cdn-us.origin-apple.com.akadns.net  canonical name = cl3.g.aaplimg.com.
Name:   cl3.g.aaplimg.com
Address: 17.253.69.199
Name:   cl3.g.aaplimg.com
Address: 17.253.69.209
Name:   cl3.g.aaplimg.com
Address: 2403:300:a0c:f000::201
Name:   cl3.g.aaplimg.com
Address: 2403:300:a0c:f100::202

ubuntu@tk2-410-46346:~$ nslookup cl3-cdn.origin-apple.com.akadns.net
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find cl3-cdn.origin-apple.com.akadns.net: REFUSED

ubuntu@tk2-410-46346:~$ nslookup cl3-cdn.origin-apple.com.akadns.net
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
cl3-cdn.origin-apple.com.akadns.net     canonical name = cl3-cdn-us.origin-apple.com.akadns.net.
cl3-cdn-us.origin-apple.com.akadns.net  canonical name = cl3.g.aaplimg.com.
Name:   cl3.g.aaplimg.com
Address: 17.253.71.208
Name:   cl3.g.aaplimg.com
Address: 17.253.71.202

ubuntu@tk2-410-46346:~$ nslookup cl3-cdn.origin-apple.com.akadns.net
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find cl3-cdn.origin-apple.com.akadns.net: REFUSED
```

### Expected result

希望你们能修好它
________
I hope you can fix it.

### Actual result

https://github.com/AdguardTeam/AdGuardHome/assets/29139573/5dc9d3cf-2d28-4c61-8209-020ac4f1efb9

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/29139573/80e8fdab-1d06-4057-b2a4-f1e55a897a9b)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/29139573/e99884c0-7cac-4fc1-b7b6-b3bc8a51c39c)

**Comment by bcseputetto** [comment]
我又测试了一下发现只有谷歌的DNS(DoH)会对自定义IP的EDNS返回REFUSED，而cloudflare的不会
__________
I have tested again and found that only Google’s DNS (DoH) will return REFUSED for EDNS with custom IP, while Cloudflare’s will not.

**Comment by agneevX** [comment]
> I have tested again and found that only Google’s DNS will return REFUSED for EDNS with custom IP, while Cloudflare’s will not.

This goes for the only two public resolvers that explicitly support ECS from Akamai, Google Public DNS and OpenDNS. 

Cloudflare (1.1.1.1) does not send ECS and their enterprise solution, Zero Trust sends ECS however does not support sending a subnet other than the one from where the request originates.

**Comment by ainar-g** [comment]
Thank you for the thorough report!  You are correct in that it might be an issue more with the way Google chooses to respond to some queries.  I'll merge this into #3652, if you don't mind.  Please use the :+1: reaction on that issue to show your support for retries or some other solution for these cases.
