### ISSUE TITLE
Query being blocked by IP if the resolved address contains the string of the IP in the rule

### ISSUE THREAD

**Issue by hisel-sabermetrics** [AdguardTeam/AdGuardHome#6348]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.40

### Action

1. Add a list of ip to the blocklist
2. Query an unrelated domain

### Expected result

The query being processed successfully as the IPs of the site does not match the rules in the blocklist.

### Actual result

The query is blocked by a filter rule despite IP not being a complete match.

The rule involved here is the ip 212.51.144.4

The only relation with the DNS response is the address 212.51.144.4*4*

![Screenshot](https://github.com/AdguardTeam/AdGuardHome/assets/96913686/0b35e12c-1bd4-4046-9a88-1d936abc786c)

**Comment by ainar-g** [comment]
The AdBlock rules are indeed for text matching, so if you want to block an exact IP address you should use the `|` characters to explicitly point to the beginning and end of the pattern:

```AdBlock
|212.51.144.4|
```
