### ISSUE TITLE
AdguardHome and ipFire - can not update .93

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#635]
Have ipFire upstream of the Router, Computer.  Running version: v0.92-hotfix2 address: 127.0.0.1:53 after install of .93.  Terminal Reports:
Last login: Sun Mar 10 09:35:36 on ttys000
A:~ $ cd desktop/firewall
A: $ sudo ./adguardhome
Password:
2019/03/10 12:19:14 AdGuard Home, version v0.93
2019/03/10 12:19:14 Reading config file: /Users/X/Desktop/Firewall/AdGuardHome.yaml
2019/03/10 12:19:14 Start DNS server periodic jobs
2019/03/10 12:19:14 Starting the DNS proxy server
2019/03/10 12:19:14 Ratelimit is enabled and set to 20 rps
2019/03/10 12:19:14 The server is configured to refuse ANY requests
2019/03/10 12:19:14 DNS cache is enabled
2019/03/10 12:19:14 Creating the UDP server socket
2019/03/10 12:19:14 Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: address already in use
A:firewall $ 

### Steps to reproduce

1.install .93 over .92.  
2.Terminal start .93 
3.Terminal couldn't start .93 
4.open web browser See .92: Query Log is Blank 

### Expected behavior

AS USUAL .93 SHOULD HAVE STARTED.
### Actual behavior

IPFIRE MAY BE BLOCKING .93
IPFIRE IS A NEW INSTALL
<img width="1036" alt="ADGUARDHOME Screen Shot 2019-03-10 at 12 45 17 PM" src="https://user-images.githubusercontent.com/48414915/54089033-685f1b80-4332-11e9-8894-baf82b74c7ed.png">

<details><summary>Screenshot:</summary>

REVERTED TO REGULAR DNS:
<img width="1123" alt="ADGUARDHOME Screen Shot 2019-03-10 at 12 51 05 PM" src="https://user-images.githubusercontent.com/48414915/54089097-39957500-4333-11e9-87b4-e2639b7c77e8.png">

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0) .93
| How did you setup DNS configuration:| (System/Router/IoT) SAME AS WITH .92
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B) ASUS RT N66U
| Operating system and version:| (e.g. Ubuntu 18.04.1) MOJAVE

**Comment by ameshkov** [comment]
> Couldn't start forwarding DNS server, cause: couldn't listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: address already in use

Have you stopped AGH prior to updating & starting it?
