### ISSUE TITLE
Feature to block specific services for specific users/IPs

### ISSUE THREAD

**Issue by amrmzr** [AdguardTeam/AdGuardHome#6351]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

block facebook to specific user/IP/mac address

### Proposed solution

facebook should be blocked for that user only

**Comment by ainar-g** [comment]
You can already do that with custom service-blocking settings and schedule for persistent clients.
