### ISSUE TITLE
Make dialog for adding vetted blocklists taller

### ISSUE THREAD

**Issue by hl2guide** [AdguardTeam/AdGuardHome#6358]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

In the "Filters > DNS blocklists" page if you:
- click the "Add blocklist" button 
- click the "Choose from the list" button

the "Choose blocklists" dialog has a small height making it less useful.

### Proposed solution

Please consider making it 80% height.

### Alternatives considered and additional information

Using as is.

**Comment by EugeneOne1** [comment]
@hl2guide, hello and thanks for the suggestion.  We've increased the height of the list and this will be included in the next release, but you can try it already with the latest edge build.  Would you mind checking it out?

**Comment by hl2guide** [comment]
> @hl2guide, hello and thanks for the suggestion. We've increased the height of the list and this will be included in the next release, but you can try it already with the latest edge build. Would you mind checking it out?

Where can I find the latest edge release?

**Comment by EugeneOne1** [comment]
@hl2guide, it's described in the [README.md](https://github.com/adguardteam/adguardhome/#test-unstable-versions).

**Comment by hl2guide** [comment]
Seems like this may not have taken effect. 

On a 1440p monitor I get:
