### ISSUE TITLE
Filtering in Query Log difficult with IP

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#636]
Trying to view the Query Log for particular clients, typing in the IP address at the top shows all queries from IP addresses containing the same term, not just the IP typed.

Would be good for a way to either auto detect when an exact IP is typed, or to provide the ability to use "term" marks to search for the exact IP, eg. typing "192.168.1.2" only shows results from that client.

### Steps to reproduce

1. Have clients connected with AdGuard Home with examples IP of 192.168.1.2, 192.168.1.20, and 192.168.1.200
2. Type `192.168.1.2` in the Query Log

### Expected behavior
You see all queries for 192.168.1.2

### Actual behavior
You see all queries for 192.168.1.2, 192.168.1.20 and 192.168.1.200

**Comment by rfgamaral** [comment]
I need this too. Can't tell you how many times I've wanted to filter requests for a particular client and wasn't able to.

**Comment by ArchiveBase** [comment]
Same https://github.com/AdguardTeam/AdGuardHome/issues/636

**Comment by szolin** [comment]
Starting with v0.99 searching is not strict unless double quotes are used.

**Comment by slekk** [comment]
I need this as well, it´s really a mess, when a specific device has problems with a domain and you want to unblock it. But you can´t finde the domain for this IP-Adress because you have so much content from other IP-adresses which you were not looking for

**Comment by ameshkov** [comment]
@slekk you should just use double-quotes to search for the exact match: `"192.168.0.1"`
