### ISSUE TITLE
Allow specifying what subnets the rate limiter is applied to

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#6368]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Currently, the rate limiter uses `ipv4/32` and `ipv6/128` to count queries and there's no way to change this.

### Proposed solution

* [ ] I suggest exposing it via the configuration file and allowing specifying subnet lengths.
* [ ] I also suggest changing the default subnet length to `/24` and `/64`. Practice shows that on a public server `/32` is no good as DDOSing the whole `/24` subnet is a common practice.

**Comment by schzhn** [comment]
This feature is available in [v0.107.41](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.41).
Default subnet mask length is `24` for IPv4 addresses and `56` for IPv6 addresses.

**Comment by ainar-g** [comment]
@schzhn, the UI is not finished yet.

**Comment by schzhn** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/6369 for UI.
