### ISSUE TITLE
User-friendly client name -- using hosts file

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#637]
This is the first part of a whole set of client management settings we will need to implement.

Here's what we should:

1. Scan the /etc/hosts file
2. If hostname is configured for the IP address, change how it looks like in the query log and in the "Top Clients" section: https://uploads.adguard.com/up04_9luee_AdGuard_Home.png

**Comment by OmgImAlexis** [comment]
Can we also add using DNS todo the lookups? I have a unifi router sitting between my adGuard server and the internet which handles local DNS resolving.

**Comment by ameshkov** [comment]
Done

**Comment by tonyklawrence** [comment]
This is great - would it be possible to be able to resolve these clients?
I've added many hostnames into /etc/hosts but when I try to resolve the IP for them they are unknown?

**Comment by ameshkov** [comment]
@tonyklawrence hm, maybe. Could you please file a feature request?

Meanwhile, as a temporary solution you can copy/paste your hosts file contents to the AGH custom rules field.
