### ISSUE TITLE
Logging no longer working

### ISSUE THREAD

**Issue by gmcdon** [AdguardTeam/AdGuardHome#6372]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.40

### Action

Reviewing logs within query log has stopped updating since October 14th. Tested domains what are on allow and block lists.
Reviewed settings confirming logging is still enabled and log rotation is set to 7 days
Checked/confirmed AdGuard is up to date 
Updated/rebooted hostOS

### Expected result

DNS requests recorded within logs, highlighting blocked and allowed domains
Logs being rotated

### Actual result

Domains correctly blocked/allowed but upon reviewing logs, no records of DNS requests
Log rotation not working past 7 days
Graph stats appear to be updating as expected 

### Additional information and/or screenshots

Install Raspberry Pi 3B on Raspbian

**Comment by ainar-g** [comment]
>  Reviewing logs within query log has stopped updating since October 14th. Tested domains what are on allow and block lists.

 >  Reviewed settings confirming logging is still enabled and log rotation is set to 7 days

I'm not sure what you mean here.  The query log retains one additional file, meaning that if the rotation interval is set to 7 days, you'll have about 14 days of query logs, which seems to be precisely what you're observing?

**Comment by ainar-g** [comment]
Ah, I see, thanks.  What are the settings in the `querylog` object in your configuration file?  I.e.:

```yaml
querylog:
  ignored: []
  interval: 2160h
  size_memory: 1000
  enabled: true
  file_enabled: true
```

Also, do you see any querylog-related errors in the [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog)?

**Comment by gmcdon** [comment]
Thank you for your help
For some reason, memory size had changed to 0. Modified the yaml config and set it to 1000, same as your example and now able to see queries in the query search again.

**Comment by lbtboy** [comment]
> А, я вижу, спасибо. Какие настройки в `querylog`объект в вашем файле конфигурации? Т.е.:
> 
> ```yaml
> querylog:
>   ignored: []
>   interval: 2160h
>   size_memory: 1000
>   enabled: true
>   file_enabled: true
> ```
> 
> Кроме того, видите ли вы какие-либо ошибки, связанные с журналом запросов, в [ подробном журнале ](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) ?
Спасибо за помощь. Тоже стояло почему-то значение 0. Исправил на 1000, запросы появились в журнале.
