### ISSUE TITLE
 Incorrect time in the log

### ISSUE THREAD

**Issue by fizsef** [AdguardTeam/AdGuardHome#6376]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

107.40

### Action

```sh
I'm looking at the AdGuardHome.log log file
```

### Expected result

I expect to see the correct time selected in the system

### Actual result

The time in the log file is incorrect, less than three hours. 

### Additional information and/or screenshots

OpenWRT 23.05, Xiaomi AX6s router.
The Europe-Moscow time zone is selected in the system, the zoneinfo-all package is installed.

**Comment by ainar-g** [comment]
@fizsef

> Europe-Moscow time zone is selected in the system

Please make sure that this is the case for the user which launches the `AdGuardHome` process as well.

**Comment by fizsef** [comment]
> @fizsef
> 
> > Europe-Moscow time zone is selected in the system
> 
> Please make sure that this is the case for the user which launches the `AdGuardHome` process as well.

Sorry, but how to do it, how to check?

**Comment by ainar-g** [comment]
I do not know the peculiarities of the OpenWrt port, but generally you need to find out the system user of the process running `AdGuardHome` and see if it is set for them.  If you can modify the service environment, you can add something like `TZ=Europe/Moscow` to it.

**Comment by Sakura-Luna** [comment]
There seems to be a bug in the log. When you enable `local_time` and update the list, the new record changes back to UTC time.

**Comment by fizsef** [comment]
Changing the lokal_time option does not affect anything for me. What is enabled, what is disabled, the UTC time is still in the log, minus 3 hours from the time set in OpenWRT. It is not clear at all what this option affects.

**Comment by ainar-g** [comment]
@Sakura-Luna, please make sure that you're stopping AGH before making any changes to the configuration file.  Otherwise the changes are overwritten.

@fizsef, have you configured the environment as proposed above?
