### ISSUE TITLE
New Feature: DNS Blocklists, enable button visibility

### ISSUE THREAD

**Issue by joel72265** [AdguardTeam/AdGuardHome#6380]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Thank you for a wonderful application

New Feature: the enable button on the DNS Blocklists is not visible 

### Proposed solution

make the enable button more visible (please see screenshot for possible changes)

![AdGuard02](https://github.com/AdguardTeam/AdGuardHome/assets/118885352/44b58439-2eef-4676-8628-d24e5a8fb732)

**Comment by ainar-g** [comment]
Thank you for your kind words.  Unfortunately, I'm not quite sure I understand what the problem is with the current checkmark.  If it's about contrast, I don't really see how the suggested options are better, as they seem to have even less contrast.

**Comment by joel72265** [comment]
Yes, about contrast and adding color to the check-box to indicate that the list is Active for better visibility

**Comment by ainar-g** [comment]
If I recall correctly, we currently do not modify checkboxes, so the way they look is most likely due to your browser's built-in style.  Stylized checkboxes are planned in the v0.108 UI redesign, so I'll merge this into #2554.
