### ISSUE TITLE
show "correct" dns name of device

### ISSUE THREAD

**Issue by sadden3194** [AdguardTeam/AdGuardHome#6386]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Client name will shown in adguard as "original name":

<img width="311" alt="Bildschirmfoto 2023-11-04 um 18 10 38" src="https://github.com/AdguardTeam/AdGuardHome/assets/17011498/61e560b9-1872-4498-b6dd-8afa59bee31d">

But I rename it in my router (fritzbox) to FireTV

<img width="1104" alt="Bildschirmfoto 2023-11-04 um 18 10 03" src="https://github.com/AdguardTeam/AdGuardHome/assets/17011498/239d79da-9135-4f09-bbce-f8caed2f33ac">

nslookup shows this:

```
nslookup 192.168.108.27
Server:		192.168.108.250
Address:	192.168.108.250#53

27.108.168.192.in-addr.arpa	name = FireTV.fritz.box.
27.108.168.192.in-addr.arpa	name = 192-168-108-27.fritz.box.
27.108.168.192.in-addr.arpa	name = Android.fritz.box.
27.108.168.192.in-addr.arpa	name = amazon-060b66ea5.fritz.box.
```

### Proposed solution

I am not sure, but It would be "better" if the same name will shown in adguard as in the fritzbox.
And much bore better, without the ".fritz.box" suffix.

Only: FireTV (same like Fritzbox)

**Comment by ainar-g** [comment]
The rDNS data is updated on reboot, if I recall correctly.  The best way to ensure that a particular client has a consistent name is to add the client to *Persistent clients.*

**Comment by distante** [comment]
@ainar-g I know this is closed but I just migrated my install to another LXC container and I see an inconsistent behavior.

The rDNS names on my Fritzbox were long set.

On my old machine running AdguardHome Version `v0.107.29` the hostnames resolve as `my-personal-hostname.fritz.box`

While on the new machine running `v0.107.43` the same device resolves as `some-random-initial-hostname.fritz.box`

After reboots of Adguard home nothing changes in both systems. I had toggle the DNS pointer on the router to test both installs and both work.

Both resolved hostnames return the correct IP on ping BTW.
