### ISSUE TITLE
Wiki: Htpasswd reset 10 iterations

### ISSUE THREAD

**Issue by privacy-advo** [AdguardTeam/AdGuardHome#6387]
### The problem

I recommend to add the 10 iteration cost in the wiki page for htpasswd reset.

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset

`.\Htpasswd -B -n -b <USERNAME> <PASSWORD>`
Spits out a 5 iteration hash by default. My AGH v107.40 instance only accepts 10 iterations ($2y$10).

### Proposed solution

This:
`.\Htpasswd -B -C 10 -n -b <USERNAME> <PASSWORD>`

Thanks for the awesome work. 

### Alternatives considered and additional information

Maybe that might have been behind https://github.com/AdguardTeam/AdGuardHome/issues/4784

**Comment by ainar-g** [comment]
Thanks for the suggestion.  We've added that flag.
