### ISSUE TITLE
[BUG] Social media buttons block filter lists don't work

### ISSUE THREAD

**Issue by MariuxReloaded** [AdguardTeam/AdGuardHome#639]
### Steps to reproduce
1. Adding all the possible social media button block filter lists (e.g. Fanboy Anti-Facebook List, AdGuard Social Media Filter, Fanboy's Social Blocking List, etc.)
2. Trying using each one of them alone or all together
3. Social media buttons still appear in both cases
4. Updating filter lists doesn't help

### Expected behavior
Social media buttons should disappear

### Actual behavior
Social media buttons are still there

### Your environment
Desktop PC

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.93
| How did you setup DNS configuration:| My router doesn't allow the usage of public DNS, so I've configured all home devices to use my personal AdGuard Home DNS
| Operating system and version:| Windows 10 Pro 1809 x64 build 17763.379

**Comment by ameshkov** [comment]
Well, this requires using cosmetic filtering rules, and it is not possible on the DNS level.

In the future, we are planning to add a MITM proxy option to AGH, then it will become possible.

**Comment by MariuxReloaded** [comment]
> Well, this requires using cosmetic filtering rules, and it is not possible on the DNS level.
> 
> In the future, we are planning to add a MITM proxy option to AGH, then it will become possible.

Oh, I understand, thank you very much and I'm eager to try the MITM proxy in the future 👍
