### ISSUE TITLE
The query log is not displayed

### ISSUE THREAD

**Issue by lbtboy** [AdguardTeam/AdGuardHome#6392]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.40

### Action

Hello. After upgrading to version 0.107.40, the log stopped being displayed. There are clients, they are connected, but there is no information in the log.
![AdGuard Home - aeza red-rebel ru - 06 11 2023_14_24_19](https://github.com/AdguardTeam/AdGuardHome/assets/57795912/85aeee37-8b7b-4647-acec-2ca66dfd85e5)
![AdGuard Home - aeza red-rebel ru - 06 11 2023_14_25_15](https://github.com/AdguardTeam/AdGuardHome/assets/57795912/72a391dd-0c79-4375-b1dc-d5d715930e9b)
![AdGuard Home - aeza red-rebel ru - 06 11 2023_14_25_43](https://github.com/AdguardTeam/AdGuardHome/assets/57795912/2e0f8670-5728-4c42-8ac3-dc1c18e53b9d)

What could be the problem?

### Expected result

_

### Actual result

_

### Additional information and/or screenshots

_

**Comment by schzhn** [comment]
Hello, @lbtboy.
Related https://github.com/AdguardTeam/AdGuardHome/issues/6372
