### ISSUE TITLE
Blocked Services timezone does not work

### ISSUE THREAD

**Issue by lgeraher** [AdguardTeam/AdGuardHome#6401]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.40

### Action

I'm running AdGuard Home in a local MicroK8S cluster, the DHCP is managed by a router and only the DNS service is provided by AdGuard. I'm trying to schedule the Pause service blocking but every time I set the timezone I need, it is sent as UTC to the API.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/83613958/56126caa-2e19-46f7-b4dc-325eabd9f0e0)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/83613958/c55ab364-cb8b-4f1c-bd03-f8c6649a4acd)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/83613958/a6c77f9f-89e1-402a-9797-cff4e16da94e)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/83613958/c3f17d61-59a2-4219-99ae-a01622a664d3)

### Expected result

Store the schedule in the selected timezone

### Actual result

Storing the schedule in UTC

**Comment by ainar-g** [comment]
The fix will be a part of the upcoming release.
