### ISSUE TITLE
DHCP leases Action button opens Wrong Popup window.

### ISSUE THREAD

**Issue by lutfor-diu** [AdguardTeam/AdGuardHome#6402]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.40

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```
1. Got to DHCP settings
2. Scroll to "DHCP leases" section
3. There will be "plus" sign action button saying "make it static"
4. Click on that plus button
![Web capture_9-11-2023_81855_192 168 31 58](https://github.com/AdguardTeam/AdGuardHome/assets/32225836/1e56f8b6-df8a-49b1-9426-b4f99ce0e3cd)

### Expected result

when click on plus action button it should add that DHCP lease to Static Lease section.

### Actual result

But it opens wrong popup window of " add new leases"
![Web capture_9-11-2023_81929_192 168 31 58](https://github.com/AdguardTeam/AdGuardHome/assets/32225836/56830dea-6be3-4ec0-8553-81df0bde1fcb)

### Additional information and/or screenshots

Adgurad install on Dietpi Lightweight os.

**Comment by ainar-g** [comment]
Thanks for the report.  The window is correct, but the data should be pre-filled with the dynamic lease's.  Seems like a UI bug.

**Comment by ainar-g** [comment]
v0.108.0-b.50 should contain the fix for this issue.  Can you please check?

**Comment by ainar-g** [comment]
We'll close this issue now.  Please let us know if the issue persists.
