### ISSUE TITLE
Block By response

### ISSUE THREAD

**Issue by Heshmatkhah** [AdguardTeam/AdGuardHome#6403]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

An attacker in my ISP hijacks DNS queries and returns `10.10.34.34` for some critical domains, such as banking systems.
I want to block the response if it points to that address because it's phishing.
Also because my IP wants me to use their DNS system (so they can hijack) it blocked DoH, DoT, and other secure DNS systems.
It also prevents using DNSsec.

### Proposed solution

If you add the possibility for block rules based on the response, it will be great.
Just like [$dnstype](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnstype).
What I suggest is something like this:

```
||mybank.com^$a_response=10.10.34.34
||*^$a_response=10.10.34.34
```

and this checks for a record response and if they match with the given IP address, it will be blocked!

**Comment by ainar-g** [comment]
Hello.  This is already a feature AGH has.  Try this, without any modifiers:

```AdBlock
|10.10.34.34|
```
