### ISSUE TITLE
DNS Cache Bug

### ISSUE THREAD

**Issue by MIAONECYAN** [AdguardTeam/AdGuardHome#6406]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.40

### Action

If I specify the difference Upstream DNS Servers for the Client(Settings-Client Settings-Edit the Client-Upstream DNS Servers), The DNS Cache was not working.

### Expected result

I think the DNS Cache should work even if I Specify the Client's Upstream DNS Server.

### Actual result

If I do not Specify the Upstream DNS Server for the Client(Settings-Client Settings-Edit the Client-Upstream DNS Servers), the DNS Cache works  normally.

**Comment by Sakura-Luna** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/6263
