### ISSUE TITLE
DNS cache config: impossible to override minimum TTL without overriding max TTL

### ISSUE THREAD

**Issue by ardel** [AdguardTeam/AdGuardHome#6409]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

0.107.40

### Action

In the web UI
Put any reasonable value in "Override minimum TTL"

### Expected result

My min TTL setting persisted without specifying the max TTL

### Actual result

The error message is displayed "Minimum cache TTL override must be less than or equal to the maximum"
![image](https://github.com/AdguardTeam/AdGuardHome/assets/2864136/2045e90d-5b6b-4784-8fb9-b693f27f0c95)

**Comment by ardel** [comment]
Potential reoccurrence of #2459

**Comment by schzhn** [comment]
We've pushed the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) containing the fix.
