### ISSUE TITLE
docker adguard home updater

### ISSUE THREAD

**Issue by jeromel1980** [AdguardTeam/AdGuardHome#6411]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

hi
on my synology nas, i run adguardhome docker container
in docker, on the dashboard i can see that
run command  : --no-check-update

but from the registry, i pick the first choice "adguard/adguardhome"
then i chosse the latest image

![image](https://github.com/AdguardTeam/AdGuardHome/assets/150483940/86b08dcf-243f-4c7a-91d3-c81d15cdbc83)

and thn  my adguardhome interface looks like
![image](https://github.com/AdguardTeam/AdGuardHome/assets/150483940/f8f2fbbf-db5a-4a3e-897e-9e999974d94a)

is the update ofadguardhome automatic or it's normal because i choose "latest" ?

thanks

### Proposed solution

... ?

**Comment by ainar-g** [comment]
Please use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for asking questions.

It is assumed that updates of the Docker images are handled by the users themselves.  Updating the binary within the image without updating the image itself may lead to weird bugs, so it's better to update the image.
