### ISSUE TITLE
Adguard Home DNS Fails to Resolve.

### ISSUE THREAD

**Issue by Skyler0x2** [AdguardTeam/AdGuardHome#6416]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

 v0.107.26

### Action

DNS fails to resolve.

### Expected result

DNS resolves. 

### Actual result

DNS fails to resolve.

### Additional information and/or screenshots

![DNS Resolving Error](https://github.com/AdguardTeam/AdGuardHome/assets/30445480/9fc74f08-157b-40b6-9c24-7897ac5879a9)

**Comment by ainar-g** [comment]
> Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

Please actually mention the complete information

> v0.107.26

This is a rather old version, and we recommend updating.

The errors themselves show that these upstream servers are not reachable by AGH.  Most likely, either a network issue or a misconfigured container/VM.  You find out more about what exactly goes wrong by enabling [verbose logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and reading the logs.
