### ISSUE TITLE
dnsmasq regex patch?

### ISSUE THREAD

**Issue by privacyguy123** [AdguardTeam/AdGuardHome#6417]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Regex not accepted in IPSet.

### Proposed solution

Any chance to include this patch in inbuilt dnsmasq?

https://github.com/lixingcong/dnsmasq-regex

**Comment by ainar-g** [comment]
Duplicate of #2432

**Comment by privacyguy123** [comment]
Duplicate was closed - still requesting this a year later ...
