### ISSUE TITLE
Manage connected devices in the Admin Web Interface of AG Home.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#642]
Such like what a router does.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/inCGGBt.png)
</details><br/>

1. Devices List
2. Show devices' information, like MAC address, IP, devices' names.
3. Manage devices. Ex: Allow or ban some devices.
4. Custom configurations for specified devices.
ex: AG parental control for specified devices, not for other connected devices.
Different filters sets for specified devices.

**Comment by alexsannikov** [comment]
Agree. This feature is required urgently. It would be great to have the specific configuration as "per device".

**Comment by ameshkov** [comment]
Done: #727
