### ISSUE TITLE
DNS rewrites Add enable and disable option

### ISSUE THREAD

**Issue by luweijun1992** [AdguardTeam/AdGuardHome#6423]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

DNS rewrites Add enable and disable option

### Proposed solution

DNS rewrites Add enable and disable option

**Comment by ainar-g** [comment]
Duplicate of #1765
