### ISSUE TITLE
AdGuardHome 0.107.41 [error] handling tcp: reading msg: reading len: read tcp

### ISSUE THREAD

**Issue by juanico10** [AdguardTeam/AdGuardHome#6429]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.41

### Action
I check that everything works correctly, but the log is flooded with messages:

```sh
Query #0 completed in 6ms:
Non-authoritative answer:
Name:   www.google.com
Address: 172.217.17.4
```

### Expected result

Error log flooded with following events:
```sh
adguard  | 2023/11/16 11:36:27.849457 [error] handling tcp: reading msg: reading len: read tcp X.X.X.X:853->X.X.X.X:56351: read: connection reset by peer
adguard  | 2023/11/16 12:48:52.039087 [error] handling tcp: reading msg: reading len: read tcp X.X.X.X:853->X.X.X.X:56345: read: connection reset by peer
```

### Additional information and/or screenshots
![photo_2023-11-16_15-40-07](https://github.com/AdguardTeam/AdGuardHome/assets/95724863/c85bc08e-a0b9-4d9b-baec-22c2bc046fa0)

**Comment by ovizii** [comment]
I'm also seeing these errors flooding my container logs with Version: v0.107.44

**Comment by frlinux** [comment]
Same issue, these show up every now and then too. I started looking into debug because one to twice a day, my whole DNS resolution stops working then i need to restart adguard. Not using containers, vanilla ubuntu install on bare metal.

**Comment by hajiboy95** [comment]
I get the same error. for me it's several times a minute. Logs are just flooded...
Anyone found a fix for that?

**Comment by skarpinis** [comment]
I am experiencing same issue.

**Comment by hajiboy95** [comment]
> I am experiencing same issue.

Was able to fix it. Since I also use a guard as DNS resolver it was due to the following setting under DNS settings 
`enable reverse resolving of client's IP addresses` (on the very bottom). 

Since a guard handles all DNS requests there's not external source (e.g. your modem) who resolves DNS requests, therefore since I deactivated it, the error log in the console disappeared.

**Comment by skarpinis** [comment]
> > I am experiencing same issue.
> 
> Was able to fix it. Since I also use a guard as DNS resolver it was due to the following setting under DNS settings Activate resolve host name of client (on the very bottom).
> 
> Since a guard handles all DNS requests there's not external source (e.g. your modem) who resolves DNS requests, therefore since I deactivated it, the error log in the console disappeared.

Hi, can you be more specific I cannot find this setting? thank you

**Comment by hajiboy95** [comment]
> > > I am experiencing same issue.
> > 
> > 
> > Was able to fix it. Since I also use a guard as DNS resolver it was due to the following setting under DNS settings Activate resolve host name of client (on the very bottom).
> > Since a guard handles all DNS requests there's not external source (e.g. your modem) who resolves DNS requests, therefore since I deactivated it, the error log in the console disappeared.
> 
> Hi, can you be more specific I cannot find this setting? thank you

Sorry only had the German name available back then. 

Go to Settings -> DNS Settings and scroll to the very bottom, there untick the box besides `enable reverse resolving of client's IP addresses`

![Image](https://github.com/user-attachments/assets/543c5230-51cd-4005-b238-c96f91ece160)

**Comment by skarpinis** [comment]
thank you but did not help still getting error
