### ISSUE TITLE
Increase the default timeout used for downloading filters updates

### ISSUE THREAD

**Issue by OmgImAlexis** [AdguardTeam/AdGuardHome#643]
### Steps to reproduce

1. Add `https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt`
2. Read error

### Expected behavior
No error.

### Actual behavior
```
Error: control/filtering/add_url | Couldn't fetch filter from url https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt: net/http: request canceled (Client.Timeout exceeded while reading body) | 400
```

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.93
| How did you setup DNS configuration:| N/A
| If it's a router or IoT, please write device model:| N/A
| Operating system and version:| Docker container

**Comment by lancelot-moon** [comment]
You didn't carefully read the phrase:
AdGuard Home understands **basic adblock rules and hosts files syntax**.

What are basic adblock rules and hosts files syntax?
Are you sure of importing correct and supported rule syntax?

**Comment by OmgImAlexis** [comment]
Well the error thrown doesn’t seem like it’s even gotten to the point of parsing the file yet? 400 is a HTTP error.

**Comment by ameshkov** [comment]
Hi! This is a timeout error while downloading the file. 

How long does it take to download it using `wget` or `curl`?

**Comment by OmgImAlexis** [comment]
```
➜  Downloads time wget https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt
--2019-03-15 22:41:39--  https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt
Resolving easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)... 176.9.127.15, 176.9.139.5, 94.130.73.112, ...
Connecting to easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)|176.9.127.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3273295 (3.1M) [text/plain]
Saving to: ‘easyprivacy+easylist.txt’

easyprivacy+easylist.txt                           100%[=============================================================================================================>]   3.12M  19.3KB/s    in 56s

2019-03-15 22:42:38 (56.7 KB/s) - ‘easyprivacy+easylist.txt’ saved [3273295/3273295]

wget https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt  0.10s user 0.12s system 0% cpu 59.174 total
```

**Comment by ameshkov** [comment]
Got it, thank you! We'll increase the default timeout, it seems that currently it is less than 1 minute.
