### ISSUE TITLE
Filter update interval is too frequent

### ISSUE THREAD

**Issue by gontazaka** [AdguardTeam/AdGuardHome#644]
Filter update runs every 1 minute.

### Steps to reproduce

1. Go to "Filters" in web UI
2. Add filter

### Expected behavior

30-minute cycle...?

### Actual behavior

1. 30 minutes later. HTTP GET access to filter file URL
2. 1 minutes later. HTTP GET access to filter file URL
3. 1 minutes later. HTTP GET access to filter file URL ... *Repeated*

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.93
| How did you setup DNS configuration:| System
| If it's a router or IoT, please write device model:| -
| Operating system and version:| QNAP QTS 4.3.4.0820 (Linux 3.4.6)

**Comment by szolin** [comment]
Fixed: https://github.com/AdguardTeam/AdGuardHome/commit/91ec996ffbd289798bab98ed426926f0b13a7b76
