### ISSUE TITLE
DNS Names / selection by AdGuard Home

### ISSUE THREAD

**Issue by Just2Confuse** [AdguardTeam/AdGuardHome#6443]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

Version: v0.108.0-b.49

### Action

```
root@DietPi:~# uname -a
Linux DietPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
root@DietPi:~# date
Mon Nov 20 06:47:15 GMT 2023
root@DietPi:~# nslookup 192.168.1.44
44.1.168.192.in-addr.arpa       name = FireTV2.fritz.box.
44.1.168.192.in-addr.arpa       name = Android.fritz.box.
44.1.168.192.in-addr.arpa       name = 192-168-1-44.fritz.box.
44.1.168.192.in-addr.arpa       name = amazon-d97e3ab28.fritz.box.

root@DietPi:~# nslookup 192.168.1.103
103.1.168.192.in-addr.arpa      name = echo3-gross.fritz.box.
103.1.168.192.in-addr.arpa      name = linux.fritz.box.
103.1.168.192.in-addr.arpa      name = avs-ffreg-1211303361.fritz.box.

root@DietPi:~#

```

### Expected result

I expect in the GUI/Browser the first names of that DHCP Devices, not the names provided by the devices. 
Setup:
Raspi Zero 2W with DietPi and AdGuard Home. No "unbound". 
Hardware what you see here
Router: AVM 6690 Cable
192.168.1.44 -> FireTV (native, no root or anything)
192.168.1.103 -> Amazon Echo

### Actual result
![adguard_3](https://github.com/AdguardTeam/AdGuardHome/assets/140651588/9847727a-1f91-472b-85eb-5e466bbf3b3c)
![adguard_1](https://github.com/AdguardTeam/AdGuardHome/assets/140651588/0d5ce1f9-610f-4cec-af4e-8f2c0b373d06)
![adguard_2](https://github.com/AdguardTeam/AdGuardHome/assets/140651588/c867af38-e596-4f75-84c5-086eb081bf05)

### Additional information and/or screenshots

I got some more devices with that behavior (Synology Diskstation, more Echos/Dots...). As with PiHole, I would expect the first names from the nslookups to appear in the evaluation of the client. I am not a networker, but these are probably the names of the devices that respond to a DHCP request. 
I am unfortunately unsure if this is a bug (why can Pihiole do it) or a feature request.

**Comment by ainar-g** [comment]
Between the UI and the PTR queries, I'm not quite sure what your issue is, sorry.

> I expect in the GUI/Browser the first names of that DHCP Devices, not the names provided by the devices.

If this is the issue, the best way would be to just add these clients as persistent clients and set the desirable human-readable names.

**Comment by Just2Confuse** [comment]
OK. I would like to save myself the double work, especially since Pihole manages the resolution correctly. But "yes", then I'll have to think about what suits me better personally. Thx
