### ISSUE TITLE
What Are These Connections 

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#645]
My connection is Cable Router > ipFire > Wireless Router > MACbook or iPad
I use Vallum Firewall and Log all connections.  AdguardHome is connecting to the internet and not using the DNS over TLS.  Please explain these connections:
ADDRESS		PORT
8.8.8.8			53
192.168.1.1		53
198.255.78.6		53
::ffff:127.0.0.1	56331
176.103.133.60	80
104.20.30.130	80
143.215.130.61	80
1.1.1.1			853
1.0.0.1			853
2606:4700:4700::1111		9
2606:4700:4700::1001	9
2606:4700:10::6814:1e82	9

Image follows of a few

### Steps to reproduce

1. Observed my Firewall report See Image
2.
3.
4.

### Expected behavior

all connections outside LAN > WAN should have used DNS over TLS or used the ipfire Firewall DNS

### Actual behavior

AdGuardHome Appears able to access unprotected outside the protected environment
 

<details><summary>Screenshot:</summary>

<img width="1031" alt="Screen Shot 2019-03-20 at 7 19 29 PM" src="https://user-images.githubusercontent.com/48414915/54727504-24e08a80-4b46-11e9-84d4-fd00a1656619.png">

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0).93
| How did you setup DNS configuration:| (System/Router/IoT) CABLE ROUTER HAS FIXED DNS. IPFIRE SHOULD HAVE CONTROL OVER UPSTREAM DNS WITH ITS PROTECTED DNS. WIRELESS ROUTER DEFERS DNS TO IPFIRE.  Mac and iPad Defer DNS UpSteam.  openVPN is used, not continuously.  
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B) ASUS RT66N, IpFire v128, NetGear Router
| Operating system and version:| (e.g. Ubuntu 18.04.1) Mac is Mojave, Ipad is older version, ASUS is Wrt, ipFire is Linux.

**Comment by ameshkov** [comment]
* `8.8.8.8` -- bootstrap DNS (resolving the IP address of a DOT/DOH resolver). You can configure it in `AdGuardHome.yaml` btw.
* `192.168.1.1	53` -- this must be your network default resolver which is used when AGH downloads filters updates (we don't use custom resolvers for these connections, maybe we should btw).
* `198.255.78.6	53` -- no idea, maybe your secondary resolver?
* `::ffff:127.0.0.1	56331` -- this is localhost.

* `176.103.133.60	80` -- `sb.adtidy.org` (browsing security web service, read the explanation in AGH settings). Also, using port 80 is a mistake, we should be using `https` by default for these connections.

Most likely these are IP addresses of the filter lists servers (check their domains):
* `104.20.30.130	80` 
* `143.215.130.61	80`
* `143.215.130.61	80`
* `2606:4700:10::6814:1e82	9`

Cloudflare IP addresses (853 is the DNS-over-TLS port)
* `1.1.1.1	853`
* `1.0.0.1	853`
* `2606:4700:4700::1111	9`
* `2606:4700:4700::1001	9`

**Comment by All4Gears** [comment]
When AdGuatdHome is configured with encrypted DNS, AdGuard is unable to connect.  The problem may be ipfire is not allowing that.  Prior to using ipfire AdGuard was able to connect using encrypted DNS.  If ipfire was configured to allow -white list- AdGuard's various DNS what would those ip or expressions look like, just as written on the settings page?



On Mar 21, 2019, at 3:10 AM, Andrey Meshkov <notifications@github.com> wrote:

8.8.8.8 -- bootstrap DNS (resolving the IP address of a DOT/DOH resolver). You can configure it in AdGuardHome.yaml btw.

192.168.1.1	53 -- this must be your network default resolver which is used when AGH downloads filters updates (we don't use custom resolvers for these connections, maybe we should btw).

198.255.78.6	53 -- no idea, maybe your secondary resolver?

::ffff:127.0.0.1	56331 -- this is localhost.

176.103.133.60	80 -- sb.adtidy.org (browsing security web service, read the explanation in AGH settings). Also, using port 80 is a mistake, we should be using https by default for these connections.

Most likely these are IP addresses of the filter lists servers (check their domains):

104.20.30.130	80
143.215.130.61	80
143.215.130.61	80
2606:4700:10::6814:1e82	9
Cloudflare IP addresses (853 is the DNS-over-TLS port)

1.1.1.1	853
1.0.0.1	853
2606:4700:4700::1111	9
2606:4700:4700::1001	9

**Comment by ameshkov** [comment]
@All4Gears 

Ideally, you need to whitelist all of them OR you need to change AGH settings.

Here's what you can change:

* `8.8.8.8` -- change it to `1.1.1.1` in `AdGuardHome.yaml`
* `176.103.133.60` -- you can disable "browsing security" and "parental control" in the settings, in this case, you won't need it.
