### ISSUE TITLE
clash fake ip  mode ，adguardhome dns test fail

### ISSUE THREAD

**Issue by wangqaq** [AdguardTeam/AdGuardHome#6458]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.41

### Action

i set clash dns server port of adguardhome upstram dns server,but clash is work as fake ip mode.so when i touch test dns buttom it will notice me clash dns server test fail.because its return a fake ip. but it actully work will .

REQUIRE IAMGE
![image](https://github.com/AdguardTeam/AdGuardHome/assets/48088450/90fb2b6a-6941-4f79-927e-22c5a3d54fe6)

### Expected result

TEST SUCCESS
![image](https://github.com/AdguardTeam/AdGuardHome/assets/48088450/36a3e274-ccf4-4fb9-97f7-1e09b43014bd)

### Actual result

TEST FAIL IMAGE
![image](https://github.com/AdguardTeam/AdGuardHome/assets/48088450/34b581ec-e1ed-4244-b7a4-e76ee9b7c9e7)

**Comment by nmreadelf** [comment]
did you use dns utils test this address? e.g: `dig www.bing.com @127.0.0.1 -p7874`

**Comment by wangqaq** [comment]
> @wangqaq, which actual part of the returned HTTP response corresponds to this upstream? It may be related to the test we perform for healthchecking the servers, so this one may respond in an unexpected way.
TEST FAIL IMAGE  127.0.0.1:7874，this is clash dns server,maybe adguardhome test upstream dns server is compare upstream dns server response ip to some domain real ip? because clash work in fake ip mode,it will give a ip such as 192.18.0.15 mapping to that domain to proxy?

**Comment by binarri** [comment]
I'v encountered the same issue too.

**Comment by overwatch3560** [comment]
You didn't  provide an answer

**Comment by wangqaq** [comment]
> > @wangqaq, which actual part of the returned HTTP response corresponds to this upstream? It may be related to the test we perform for healthchecking the servers, so this one may respond in an unexpected way.
> > TEST FAIL IMAGE  127.0.0.1:7874，this is clash dns server,maybe adguardhome test upstream dns server is compare upstream dns server response ip to some domain real ip? because clash work in fake ip mode,it will give a ip such as 192.18.0.15 mapping to that domain to proxy?

yes ,clash work in fake-ip  mode will give a such as 192.18.0.15 mapping to that domian to proxy,and its not true ip which is domain registered

**Comment by wangqaq** [comment]
> > > @wangqaq, which actual part of the returned HTTP response corresponds to this upstream? It may be related to the test we perform for healthchecking the servers, so this one may respond in an unexpected way.
> > > TEST FAIL IMAGE  127.0.0.1:7874，this is clash dns server,maybe adguardhome test upstream dns server is compare upstream dns server response ip to some domain real ip? because clash work in fake ip mode,it will give a ip such as 192.18.0.15 mapping to that domain to proxy?
> 
> yes ,clash work in fake-ip mode will give a such as 192.18.0.15 mapping to that domian to proxy,and its not true ip which is domain registered

when clash monitor that ip requrst will proxy to ur proxy group node,& i ping that fake ip in cmd, it actually responsed.

**Comment by lddsb** [comment]
Try this, it should work

```yaml
fake-ip-filter:
  - test.
  - in-addr.arpa.
```
