### ISSUE TITLE
v0.108.0-b.50 version has a memory leak issue.

### ISSUE THREAD

**Issue by xiaoyaoyaowww** [AdguardTeam/AdGuardHome#6461]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.50

### Action

v0.108.0-b.50 version has a memory leak issue.
With a large number of requests, AdGuard Home's memory footprint will quickly reach 500MB+!

### Expected result

And v0.108.0-b.49 does not have this issue.
I didn't do anything, just backed out to v0.108.0-b.49 and everything worked fine.

### Actual result

A memory leak has occurred.

**Comment by EugeneOne1** [comment]
Hello, @xiaoyaoyaowww.  Could it be related to #6438, or, in other words, is it reproducible with the latest edge build?

**Comment by xiaoyaoyaowww** [comment]
> Hello, @xiaoyaoyaowww. Could it be related to #6438, or, in other words, is it reproducible with the latest edge build?你好，它是否与#6438有关，或者换句话说，它是否可以在最新的边缘构建中重现？

Probably yes, I'm trying the Edge build.

**Comment by xiaoyaoyaowww** [comment]
> Hello, @xiaoyaoyaowww. Could it be related to #6438, or, in other words, is it reproducible with the latest edge build?你好，它是否与#6438有关，或者换句话说，它是否可以在最新的边缘构建中重现？

Thank! This issue has been fixed.
