### ISSUE TITLE
Unable to log in to the management background

### ISSUE THREAD

**Issue by pototazhang** [AdguardTeam/AdGuardHome#6462]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

AdGuard Home

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```
Unable to log in to the background, fill in the account password, click to log in, refresh the login page repeatedly, and do not enter the background.

### Expected result

Help me, I don't know how to solve it.

### Actual result

I have been refreshing the landing page repeatedly.

### Additional information and/or screenshots

<img width="1272" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/52278509/21d14603-853c-4f50-b25c-bbf0854f516b">

**Comment by ainar-g** [comment]
The password for AdGuard Home is the password you've entered when setting it up, not the one for your machine.  See [these instructions](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#password-reset) to reset/change the password.

**Comment by winfordguo** [comment]
check config: `http.session_ttl`, the default value `0s` does not work. Change it to 1m or longer.

> bad
```yaml
http:
  # ...
  session_ttl: 0s
  # ...
```

> good
```yaml
http:
  #...
  session_ttl: 1m
  #...
```
