### ISSUE TITLE
Don't use the system default resolver implicitly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#647]
There're a couple of places in the code where we use system default resolver implicitly:

* Downloading filters updates
* Communicating with the browsing security and parental control web services
* Checking application update

Ideally, we should avoid doing it. But I don't like the idea of propagating the custom resolver to every place where we make a http request. Can we somehow change the default resolver globally?

**Comment by szolin** [comment]
May be relevant: https://github.com/golang/go/issues/12503

**Comment by ameshkov** [comment]
Here's what I see on first run:
```
2019/04/23 19:01:35 [info] Couldn't request filter from URL https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt, skipping: Get https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: lookup adguardteam.github.io on 192.168.10.125:53: read udp 127.0.0.1:57264->127.0.0.1:53: read: connection refused
2019/04/23 19:01:35 [info] Failed to update filter https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: Get https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: lookup adguardteam.github.io on 192.168.10.125:53: read udp 127.0.0.1:57264->127.0.0.1:53: read: connection refused
```

We shouldn't load filters unless AGH DNS server is running.

**Comment by ameshkov** [comment]
And here's the second issue: handle DNS host=0.0.0.0 -- use 127.0.0.1 in this case.

**Comment by ameshkov** [comment]
Fixed

**Comment by ameshkov** [comment]
I had to roll it back due to Docker-related issue:
https://github.com/AdguardTeam/AdGuardHome/issues/730

See some details here:
https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach/52858101#52858101

**Comment by ameshkov** [comment]
False alarm
