### ISSUE TITLE
clients.runtime_sources.hosts within configuration does not work

### ISSUE THREAD

**Issue by NunoHiggs** [AdguardTeam/AdGuardHome#6473]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases

### Setup

On one machine

### AdGuard Home version

AdGuard Home v0.107.41

### Action

I am trying to set clients.runtime_sources.hosts on the appropriate AdGuardHome.yaml file.
However, after stopping, adding the parameter, and starting AdGuard, the parameter gets deleted from said file.

### Expected result

The parameter to stay there and work as expected.

### Actual result

The parameter is deleted, and AdGuard keeps getting data from the /etc/hosts files and this is not desirable.

**Comment by schzhn** [comment]
Hello, @NunoHiggs.
You need to not add, but set the existing parameter to `false`.
```yaml
# …
clients:
  runtime_sources:
    hosts: false
    # …
  # …
# …
```

**Comment by NunoHiggs** [comment]
Perfect it solved my issue. Maybe this should be better documented somewhere. Is the documentation also git-enabled? Want me to put in a PR to add this?

**Comment by schzhn** [comment]
@NunoHiggs, there is a [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and a section on [configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).
