### ISSUE TITLE
Local Domains (DNS-Redirections) suddenly asked via Upstream DNS?

### ISSUE THREAD

**Issue by furchtlos76** [AdguardTeam/AdGuardHome#6474]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, MIPS64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.41

### Action

Was there any change that conflicts with local DNS-Redirections lately? I added *.mylocaldomain.com to Filter, DNS-Redirections. And the setup worked for some weeks without a problem. After an update of the docker some days ago, i can not open local domains with example.mylocaldomain.com anymore. Checking the log on adguard home it shows me

DNS-Server
1.0.0.1:53
Verstrichen
0.07 ms
Antwortcode
NXDOMAIN

So, somehow it does ask the 1.0.0.1 dns (settet in Fallback-DNS-Server configuration of adguard) for that local domain name. 

### Expected result

DNS Redirects are redirected to the IP set there and not queried at 1.1.1.1 oder 1.0.0.1

### Actual result

Local Domains not fount anymore

**Comment by furchtlos76** [comment]
I could not find out what the problem was, downgrading did not work too. So i set up a new docker with adguard. Now DNS rewrite works again. Really strange. Is there a database where the DNS rewrite ist inside that could be got corrupted, or just the .json file?

**Comment by patrick984** [comment]
Also just started having the same problem since upgrading to 0.170.42.

**Comment by furchtlos76** [comment]
> We haven't changed anything regarding these rewrites, as far as I can remember. You've mentioned Docker updates. Could it be that the client wasn't recognized because your Docker installation assigned it a different IP address?

After it worked after reinstall till today, i have the problem again, did not do anything or changed anything. Even the domain is inside the rewrite rules - as before - in the protocols i can see that instead reroote to a local ip, it does ask one of the internet DNS

Status
Verarbeitet
DNS-Server
https://dns.cloudflare.com:443/dns-query (aus dem Cache abgerufen)
Verstrichen
0.14 ms
Antwortcode
NXDOMAIN

and ofcouse the subdomain does not exist on any internet DNS, it gives a NXDOMAIN back.

**Comment by furchtlos76** [comment]
> Also have this problem. I think this stopped to work a couple of months ago. I'm running the 0.170.40 as an addon in home assistant.

@HakanP @patrick984 did you find anything more? dont want to reinstall this every some weeks :-/

**Comment by furchtlos76** [comment]
@ainar-g  i just saw this issue, could this be maybe related? as i have the same constellation, a real domain that is avain in the internet (to be able to get SSL Certs via LetsEncrypt!) and subdomains only local for my homelab. And they are not working from time to time... maybte is this the couse of it: https://github.com/AdguardTeam/AdGuardHome/issues/6497  ?

**Comment by furchtlos76** [comment]
And an update on this, even when clicking on CLEAR CACHE inside DNS Settings local redirected domains or subdomains are still resolved from cache, only other domains are getting fresh from dns! Guess thats the bug

**Comment by EugeneOne1** [comment]
@furchtlos76, hello and apologies for the long wait.  We still can't reproduce the problem unfortunately, so could you please [collect a verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  We'd like to see the failed resolutions (`NXDOMAIN`s) captured as well as the successful ones (possibly, after restarting AdGuard Home), this would help us to troubleshoot the issue.  You may send the log to our devteam@adguard.com with an issue number in subject.

A few more questions about setup, if you don't mind:
1.  Are these requests coming from a persistent client (configured on _Client settings_ page)?  If yes, does this client uses some custom upstream configuration and if it has its own cache enabled?
2.  Are all these queries has the same DNS type?

And also, just to make it clear, this page is called _DNS rewrites_ and the feature itself is intended to substitute the response data, not to redirect the query to the specific upstream server.  The second purpose should be achieved with the [domain-specific upstreams](https://github.com/adguardTeam/adGuardHome/wiki/Configuration#upstreams-for-domains) feature.

**Comment by furchtlos76** [comment]
@EugeneOne1 i will try to produce such a log. Well just to exmplain again more clearly.

I use DNS Rewrite with a domain i own.

*.mydomain.de
192.168.1.100

the domain is available in the internet. however the subdomains are not. On 192.16.1.100 there is a reverse proxy running that does proxy the homelab ips and ports. for example 

adguard.mydomain.de  should go to 192.168.1.120

so i can open adguard with that subdomain - when everything works (like it does after reinstall!)
there are alot of other subdomains going to different dockers and NAS and so on on other ips.

on upstream i have this:

https://dns10.quad9.net/dns-query
https://dns.google/dns-query
https://dns.cloudflare.com/dns-query

ans also checked "private reverse resolver"  and "hostnames for clients" those 2 boxes. And i guess there is no missconfiguration, as it worked for some days.

one of the clients i inside persitant clients the other not, both have the same problem. now, if i for example open

nas.mydomain.de   in browser. the log of adguard home shows

Status
Verarbeitet
DNS-Server
https://dns.google:443/dns-query (aus dem Cache abgerufen)
Verstrichen
0.04 ms
Antwortcode
NXDOMAIN

But for my understanding, as *.mydomain.de is stading inside DNS rewiter it should not ask GOOGLE DNS for the ip, it should send 192.168.1.100 to the client! not?

**Comment by thorazine74** [comment]
Hi, just want to report that I've never experienced the issue mentioned in (https://github.com/AdguardTeam/AdGuardHome/issues/6497) any more after I've removed the fallback dns servers i had configured in the settings and changed the query mode to load balancing from the setting I had before (don't remember if I had it set up as load balancing or fastest ip address). 
I don't know if they are related because my router and internet gateway is the local internal domain dns server too, so it would not be possible for AGH to reach any internet dns servers when the router is down.
I still think an option to disable caching of nxdomain answer could be an easy solution for this issue, dnsmasq has this option but its probably only useful for local-only domains.
Maybe it would be better an option to disable caching completely for specific domains would be the more reasonable solution, if you have a local dns server inside your lan answering some queries caching does not have much benefit in that kind of setups.

**Comment by EugeneOne1** [comment]
@furchtlos76, well, the #6497 actually seems related, so we'd like to merge this issue there.  However, we'll reopen this one if it comes up later.

**Comment by starlingfire** [comment]
Just wanted to add here that I started experiencing this issue this week as well. I upgraded my docker image for the first time in a while and starting getting upstream responses (NXDOMAIN) from my phone which is connected to the wifi, where my router is using Adguard as its DNS resolver. 

I removed the Fallback DNS Server entries and it started working correctly. Query mode had been Load Balancing already, so no change there.

**Comment by furchtlos76** [comment]
> Just wanted to add here that I started experiencing this issue this week as well. I upgraded my docker image for the first time in a while and starting getting upstream responses (NXDOMAIN) from my phone which is connected to the wifi, where my router is using Adguard as its DNS resolver.
> 
> I removed the Fallback DNS Server entries and it started working correctly. Query mode had been Load Balancing already, so no change there.

After some month without any problem, i got that again today! LOcal Domains that are given bei "DNS Local rewrite" where asked online ad as they do not exist i got a DNS_PROBE_FINISHED_NXDOMAIN Error on all my local subdomains. Removing the Fallback DNS worked for me, too! @EugeneOne1 for me this is still kind of bug, why are those domains like *.localdomain.com that are inside "local dns redirect" not excluded completly inside dns requests? Would this not fix that problem?
