### ISSUE TITLE
Feature Request: AdGuard Home Android App

### ISSUE THREAD

**Issue by et6at** [AdguardTeam/AdGuardHome#648]
I would like to request the consideration for future builds or major versions of AdGuard, a lateral main entry setting, in order to access AdGuard Home from the AdGuard for Android apk, or a standalone apk for AdGuard Home separated from the main one.

I am not sure if doing so will increase the size of the AdGuard apk too much, we have similar examples of apps for PiHole like https://play.google.com/store/apps/details?id=sterrenburg.github.flutterhole

I wait for your considerations about this, thank you.

**Comment by Ultrabenosaurus** [comment]
@et6at why close this?
