### ISSUE TITLE
Disable protect for 30s is not enough for devices recognize

### ISSUE THREAD

**Issue by hongdat1106** [AdguardTeam/AdGuardHome#6485]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

time disabled for 30s and 1 minute are same, i usually use 30s for testing adguardhome but time was not enough for devices in lan recognize any change of dns.

### Proposed solution

 I wish you change this option: 1m 10m 30m 1h tomorrow and best option is custom time :). Thanks for viewing my suggestions features.

**Comment by fernvenue** [comment]
It's actually quite useful for manually debugging, so I think remove it is a bad idea. By the way, we do have 1m, 10m, 1hour and tomorrow options, we have choices right? Why remove this specific one option is necessary?

And yea, custom time is good, but we already have an issue here https://github.com/AdguardTeam/AdGuardHome/issues/6432 about it :)
