### ISSUE TITLE
Impossible d'ajouter un service ou site bloqué

### ISSUE THREAD

**Issue by louislemaire44** [AdguardTeam/AdGuardHome#6491]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.41

### Action

impossible to block websites or services on raspberry pi 400
### Expected result

Error message :
Error: control/filtering/add_url | Couldn't fetch filter from URL "https://apple.com": data is HTML, not plain text | 400

### Actual result

That it works

**Comment by louislemaire44** [comment]
Pourquoi avez vous fermé ?

**Comment by ainar-g** [comment]
As is written in the UI, you should put the URL of the filtering-rule list into that field, not the URL of the site you want to block.  The URL must lead to a plain-text file.
