### ISSUE TITLE
cant add an additional user by requesting control/install/configure endpoint

### ISSUE THREAD

**Issue by AkashKumar7902** [AdguardTeam/AdGuardHome#6498]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

latest

### Action

I tried sending with a POST request to /install/configure but I am getting an error:
`curl: (7) Failed to connect to 127.0.0.1 port 3000 after 0 ms: Connection refused`

request:
```cmd
curl --request POST \
      --url http://127.0.0.1:3000/control/install/configure \
      --header 'Accept: application/json, text/plain, */*' \
      --header 'Content-Type: application/json' \
      --header 'Host: 127.0.0.1:3000' \
      --header 'User-Agent: curl/7.81.0' \
      --data '{"web":{"ip":"0.0.0.0","port":80,"status":"","can_autofix":false},"dns":{"ip":"0.0.0.0","port":54,"status":"","can_autofix":false},"username":"admin","password":"password"}'
```

### Expected result

a new user should have been created 

### Actual result

Connection refused

**Comment by schzhn** [comment]
AdGuard Home supports only one user.
Related https://github.com/AdguardTeam/AdGuardHome/issues/997
