### ISSUE TITLE
Is it possible to again update blocking page's translations?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#650]
In January, I updated blocking page's translations (locale: zh-TW). (Browsing security)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JzYs1ai.png)
</details><br/>

But it's still old translation in the blocking page of v0.93.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/GBzXTsH.png)
</details><br/>

May you also update the blocking page's translations since I guess you'll add other new languages in AG Home v0.94?

Will @timirila1 do this?
https://github.com/AdguardTeam/CoreLibs/issues/805#issuecomment-474759075

Please note that some languages may use longer translations there.
Need suitable length per line and line break for a long translation.
https://github.com/AdguardTeam/CoreLibs/issues/805#issuecomment-475619747

Thanks.

**Comment by ameshkov** [comment]
These pages are hosted on the server side, translating them in AGH will be possible when we finish with #454

**Comment by ameshkov** [comment]
What for the server side, we'll update their translations in due course (update of AG DNS is required, and it will happen later)
