### ISSUE TITLE
DNS rewrite rules are invalid when applied only to specific clients with IPV6 addresses

### ISSUE THREAD

**Issue by wl223600** [AdguardTeam/AdGuardHome#6503]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [x] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.41

### Action

Note: The client and ADH are on the same local area network. In fact, "abc::d" is a local area network IPV6 address starting with "fe80".
I have set up a local reverse proxy for a site. And I configured the DNS Rewrite rule in ADH like this:
(client&reverse proxy's real ip address is replaced with ```1.2.3.4```/```abc::d```. Server's real ip is replaced with ```5.6.7.8```/```ab::cd```)
```
||steamcommunity.com^$dnsrewrite=NOERROR;A;1.2.3.4,client=1.2.3.4|abc::d
```
or
```
||steamcommunity.com^$dnsrewrite=NOERROR;A;1.2.3.4,client=1.2.3.4
```
or
```
||steamcommunity.com^$dnsrewrite=NOERROR;A;1.2.3.4,client=abc::d
```
and I executed the following command.
```sh
# lookup when using IPV4
nslookup steamcommunity.com 5.6.7.8
```
OR
```sh
# lookup when using IPV6
nslookup steamcommunity.com ab::cd
```

### Expected result

```
Server:  UnKnown
Address:  1.2.3.4
```

### Actual result

```
# using IPV4
# nslookup steamcommunity.com 5.6.7.8
Server:  UnKnown
Address:  1.2.3.4

# using IPV6
# nslookup steamcommunity.com ab::cd
Server:  UnKnown
Address:  2a03:2880:f12c:83:face:b00c:0:25de
       157.240.10.41
```

It seems that DNS rewrite rule does not work when looking up the dns record via ADH's **IPV6** address.

**Comment by ainar-g** [comment]
Merging into #6312, as the underlying reason is the same.
