### ISSUE TITLE
cannot resolve domains from vlan after upgrading to v0.108.0-b.51

### ISSUE THREAD

**Issue by iwzoo** [AdguardTeam/AdGuardHome#6510]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.51

### Action

```
nslookup -debug -type=a 'www.baidu.com' 192.168.0.1
```

### Expected result

Server:         192.168.0.1
Address:        192.168.0.1#53

------------
    QUESTIONS:
        www.baidu.com, type = A, class = IN
    ANSWERS:
    ->  www.baidu.com
        canonical name = www.a.shifen.com.
        ttl = 329
    ->  www.a.shifen.com
        internet address = 110.242.68.4
        ttl = 329

### Actual result

;; reply from unexpected source: 10.168.0.1#53, expected 192.168.0.1#53

;; reply from unexpected source: 10.168.0.1#53, expected 192.168.0.1#53

;; reply from unexpected source: 10.168.0.1#53, expected 192.168.0.1#53

;; connection timed out; no servers could be reached

### Additional information and/or screenshots

I have two vLANs, 192.168.0.0/24 and 10.168.0.0/24 
192.168.0.1 is the router, which adg runs on. 

After upgrading to v0.108.0-b.51, devices in vlan 10.168.0.0/24 cannot resolve domains. Rolling back to v0.108.0-b.50, everything works as expected.

**Comment by ainar-g** [comment]
@Mizzick, I have a feeling that it could be related to the `dnsproxy` changes, in particular the detection of destination addresses.  Please investigate.

**Comment by ainar-g** [comment]
@iwzoo, can you please check version v0.108.0-a.788+7b5cce51 on the Edge channel?
