### ISSUE TITLE
Zone transfer over QUIC (XFR-over-QUIC) RFC 9250 support

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardHome#6515]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

This document describes the use of QUIC to provide transport confidentiality for DNS. The encryption provided by QUIC has similar properties to those provided by TLS, while QUIC transport eliminates the head-of-line blocking issues inherent with TCP and provides more efficient packet-loss recovery than UDP. DNS over QUIC (DoQ) has privacy properties similar to DNS over TLS (DoT) specified in RFC 7858, and latency characteristics similar to classic DNS over UDP. This specification describes the use of DoQ as a general-purpose transport for DNS and includes the use of DoQ for stub to recursive, recursive to authoritative, and zone transfer scenarios.

### Proposed solution

Proposed solution:
https://www.ietf.org/rfc/rfc9250.html

### Alternatives considered and additional information

Possible related with:
https://github.com/AdguardTeam/AdGuardHome/issues/790

**Comment by ainar-g** [comment]
Let's consolidate all zone-transfer issues into #6511, if you don't mind.
