### ISSUE TITLE
hope to add custom edns client subnet for different clients

### ISSUE THREAD

**Issue by hjchjchjc4352** [AdguardTeam/AdGuardHome#6516]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Currently, adgh allows customizing edns client subnet, but this can only be done globally in the DNS settings. Is it possible to add a feature that allows customization of ECS for different clients individually?

### Proposed solution

add custom edns client subnet for different clients

**Comment by ainar-g** [comment]
Duplicate of #6492
