### ISSUE TITLE
Adguard Home stops working after a few minutes

### ISSUE THREAD

**Issue by stammsg** [AdguardTeam/AdGuardHome#6517]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.42

### Action

After a few minutes AGH stops working. No filtering. Counter for blocked requests remains the same.

### Expected result

Correct working AGH.

### Actual result

AGH not working.

**Comment by francismanjares** [comment]
I am not sure if this is related, but I recently upgraded to v0.107.42 it broke AdguardHome,and for some reason it stops resolving any websites, using dig doesnt show any results. Only way to get it working is going back to v0.107.41.

My AdguardHome is installed in debian12 and in a raspberry4.

**Comment by stammsg** [comment]
> I am not sure if this is related, but I recently upgraded to v0.107.42 it broke AdguardHome,and for some reason it stops resolving any websites, using dig doesnt show any results. Only way to get it working is going back to v0.107.41.
> 
> My AdguardHome is installed in debian12 and in a raspberry4.

That sounds very interesting. I think I'll give it a try with version v0.107.41. Did you just replace the Adguard executable or did you install Adguard completely new?

**Comment by francismanjares** [comment]
> That sounds very interesting. I think I'll give it a try with version v0.107.41. Did you just replace the Adguard executable or did you install Adguard completely new?

I uninstalled AdguardHome first, then manually install x.41. it will/should not remove the config, but to be safe backup and or copy  your settings in a notepad. *I dunno where the config file go lol*

**Comment by stammsg** [comment]
> > That sounds very interesting. I think I'll give it a try with version v0.107.41. Did you just replace the Adguard executable or did you install Adguard completely new?
> 
> I uninstalled AdguardHome first, then manually install x.41. it will/should not remove the config, but to be safe backup and or copy your settings in a notepad. _I dunno where the config file go lol_

I already thought that a clean reinstallation is the safest way. I will try that tomorrow. I will report how it turns out. My platform is similar to yours, same OS (but lite version) only the hardware is a Raspberry Pi Zero 2 W.

**Comment by stammsg** [comment]
Yesterday I installed version v0.107.41 on the Raspberry Zero W 2. Since then Adguard has been running without any problems. However, so far I have only carried out local tests on the Raspberry itself. If it still works tomorrow, I will switch the dns in the router to the raspberry and adguard and continue testing.
