### ISSUE TITLE
Ignored domains and domain start with a number

### ISSUE THREAD

**Issue by don-dolarson** [AdguardTeam/AdGuardHome#6519]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.42

### Action

Ignored domains with e.g. filter for |debian.pool.ntp.org not filtering request on dashboard from 2.debian.pool.ntp.org. ||debian.pool.ntp.org filter does work. Problem applies only to DNS requests starting with a number like the mentioned 2.debian domain, reverse.ip.arpa addresses etc.

### Expected result

-

### Actual result

-

### Additional information and/or screenshots

-

**Comment by ainar-g** [comment]
Please read the [documentation on AdBlock-style filters](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#adblock-style).  `|debian.pool.ntp.org` with a single pipe will only block domains starting with `debian.pool.ntp.org`.  The one with two pipes is what you're probably looking for.
