### ISSUE TITLE
Missed translations on the settings screen

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#652]
Just a minor question.

1. This might be a new phrase which isn't on onesky.
So there is no translation.
`[/example.local/]1.1.1.1 – you can specify DNS upstream for a specific domain(s)`
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/UwzlizR.png)
</details><br/>

28th March:
Well, you had uploaded that phrase #49068669 on onesky several days ago.

2. #48664002 was translated in February.
But it shows English phrase there.
`Copy/paste your PEM-encoded private key for your certificate here.`
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8jOUtMV.png)
</details><br/>

( I completed the translations of #48663998 and #48664002 at the same day.
#48663998 `Copy/paste your PEM-encoded certificates here.` correctly shows its translation.
It's strange that #48664002 lacks its translation.)

**Comment by Eyeborgs** [comment]
In the language of "Russian" is the same problem.
