### ISSUE TITLE
No sites resolve after upgrade to Version:  v0.107.42

### ISSUE THREAD

**Issue by msalmon4** [AdguardTeam/AdGuardHome#6530]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

Version:  v0.107.42

### Action

All computers on network cannot resolve sites by name. 
Ping to IP works.
Ping to name times out.
Changed DNS to 8.8.8.8 from IP of my Adguard IP and devices work

### Expected result

connection to websites normally by name

### Actual result

all sites dont resolve by name

**Comment by vincejv** [comment]
There was a critical bug in v0.107.42, try to upgrade to v0.107.43
- https://github.com/AdguardTeam/AdGuardHome/issues/6506

**Comment by knaggsy2000** [comment]
@msalmon4 Do you have multiple network interfaces/VLANs?  If so, I have found that an issue and also a workaround has been found.

[https://github.com/AdguardTeam/AdGuardHome/issues/6500]

**Comment by msalmon4** [comment]
Thanks @knaggsy2000 I do have vlans, however once I updated issue resolved.
Also it may have been tied more to a virtual IP using keepalived. For back up adjured servers. After update, all worked and traffic passed to the servers via their main respective IPs
