### ISSUE TITLE
Clients settings keeps client IP addresses without an option to disable

### ISSUE THREAD

**Issue by crazycrystals** [AdguardTeam/AdGuardHome#6547]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

If you go to settings > clients settings and scroll down, IP addresses are still logged, even with all settings around logging being off.

### Proposed solution

For either there to be a setting in "Settings > General settings" or for the logs in client settings to be included in what is affected by the statistics logs toggle

**Comment by ainar-g** [comment]
Use the properties `clients.runtime_sources` to control which sources to use or disable them all entirely.  See the [configuration file documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) and #5550.
