### ISSUE TITLE
Ads cannot be blocked.

### ISSUE THREAD

**Issue by SungJun9212** [AdguardTeam/AdGuardHome#6548]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

./AdguardHome -s install 후
ip:3000
들어가고 
admin ip 랑 dns ip 를 모두 ubuntu 서버의 고정ip (192.168.xx.xx) 로 설정하고
계정 만들어서 로그인까지 했습니다.

필터 차단목록에 정상적으로 체크까지 되어있는데 광고가 그대로 보입니다

### Proposed solution

After ./AdguardHome -s install
ip:3000
go in
Set both the admin IP and DNS IP to the fixed IP of the Ubuntu server (192.168.xx.xx)
I even created an account and logged in.

Even though the filter block list is properly checked, the ad still appears.

**Comment by ainar-g** [comment]
Please do not report non-features as feature requests.

Make sure you have disabled/redirected your browser's custom DNS features, as browsers often have their own settings.  See [this entry in the FAQ](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#doesntblock).  If you have more questions, it's better to use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a).
