### ISSUE TITLE
'All Interfaces' redirects Wizard to 0.0.0.0 in browser instead of IP

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#655]
If I select 'All Interfaces' during the Wizard for the Web Interface, when configured and taken to the Web Interface afterwards, I get redirected to 0.0.0.0 instead of the IP address of the device.

### Steps to reproduce

1. Install AdGuard Home on Raspberry Pi via SSH/PuTTY
2. Leave all defaults during Wizard
3. Complete Wizard

### Expected behavior
Redirected to Web Interface via IP of Pi device

### Actual behavior
Redirected to 0.0.0.0 resulting in instant 'ERR_ADDRESS_INVALID' error. Manually entering Pi IP address works.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.94
| How did you setup DNS configuration:| IoT
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+

**Comment by ameshkov** [comment]
@IldarKamalov when `0.0.0.0` is selected, you should redirect user to the same `document.location.hostname` she has at the moment.
