### ISSUE TITLE
[error] dnsproxy: upstream [::1]:5337 failed to exchange ;

### ISSUE THREAD

**Issue by liyiranlab** [AdguardTeam/AdGuardHome#6552]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

核心版本:v0.107.43

### Action

什么也没做，日志报错

### Expected result

日志看不懂什么意思。

### Actual result

不知道有什么影响。

### Additional information and/or screenshots

2023/12/17 09:22:18.975453 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;ChainedboxPro.lan.	IN	 A in 679.73µs: exchanging with [::1]:5337 over udp: read udp [::1]:36245->[::1]:5337: read: connection refused
2023/12/17 09:22:18.975439 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;ChainedboxPro.lan.	IN	 AAAA in 545.929µs: exchanging with [::1]:5337 over udp: read udp [::1]:37201->[::1]:5337: read: connection refused
2023/12/17 09:22:18.974689 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;ChainedboxPro.lan.	IN	 AAAA in 772.229µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:48598->127.0.0.1:5337: read: connection refused
2023/12/17 09:22:18.974689 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;ChainedboxPro.lan.	IN	 A in 746.239µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:55709->127.0.0.1:5337: read: connection refused
2023/12/17 09:22:18.972369 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;ChainedboxPro.lan.	IN	 AAAA in 542.336µs: exchanging with [::1]:5337 over udp: read udp [::1]:33210->[::1]:5337: read: connection refused
2023/12/17 09:22:18.972346 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;ChainedboxPro.lan.	IN	 A in 615.512µs: exchanging with [::1]:5337 over udp: read udp [::1]:49620->[::1]:5337: read: connection refused
2023/12/17 09:22:18.971631 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;ChainedboxPro.lan.	IN	 AAAA in 815.769µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:34980->127.0.0.1:5337: read: connection refused
2023/12/17 09:22:18.971631 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;ChainedboxPro.lan.	IN	 A in 750.719µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:51368->127.0.0.1:5337: read: connection refused2023/12/17 09:21:29.019627 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;github.com.	IN	 HTTPS in 614.479µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:46981->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:29.019605 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;github.com.	IN	 A in 532.552µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:43222->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:29.019605 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;github.com.	IN	 AAAA in 738.698µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:39635->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:29.019018 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;github.com.	IN	 A in 803.073µs: exchanging with [::1]:5337 over udp: read udp [::1]:42416->[::1]:5337: read: connection refused
2023/12/17 17:21:29.018764 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;github.com.	IN	 HTTPS in 863.385µs: exchanging with [::1]:5337 over udp: read udp [::1]:52038->[::1]:5337: read: connection refused
2023/12/17 17:21:29.018763 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;github.com.	IN	 AAAA in 798.385µs: exchanging with [::1]:5337 over udp: read udp [::1]:48108->[::1]:5337: read: connection refused
2023/12/17 17:21:29.016628 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;github.com.	IN	 A in 815.73µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:49724->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:29.016571 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;github.com.	IN	 HTTPS in 550.729µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:47529->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:29.016531 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;github.com.	IN	 AAAA in 588.542µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:58096->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:29.015722 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;github.com.	IN	 HTTPS in 817.031µs: exchanging with [::1]:5337 over udp: read udp [::1]:52356->[::1]:5337: read: connection refused
2023/12/17 17:21:29.015722 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;github.com.	IN	 AAAA in 808.854µs: exchanging with [::1]:5337 over udp: read udp [::1]:56547->[::1]:5337: read: connection refused
2023/12/17 17:21:29.015722 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;github.com.	IN	 A in 711.25µs: exchanging with [::1]:5337 over udp: read udp [::1]:46128->[::1]:5337: read: connection refused
2023/12/17 17:21:28.398664 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 A in 641.041µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:47497->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:28.397950 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 A in 621.562µs: exchanging with [::1]:5337 over udp: read udp [::1]:46616->[::1]:5337: read: connection refused
2023/12/17 17:21:28.397591 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 AAAA in 692.865µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:46442->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:28.396810 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 AAAA in 850.833µs: exchanging with [::1]:5337 over udp: read udp [::1]:47436->[::1]:5337: read: connection refused
2023/12/17 17:21:28.395841 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 A in 1.460052ms: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:59946->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:28.394578 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;b.1.8.e.f.8.c.d.c.3.4.c.9.7.0.8.0.0.0.0.7.f.6.a.7.4.3.1.a.0.d.f.ip6.arpa.	IN	 PTR in 665.156µs: exchanging with [::1]:5337 over udp: read udp [::1]:51855->[::1]:5337: read: connection refused
2023/12/17 17:21:28.394509 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 HTTPS in 500.937µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:38316->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:28.394341 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 AAAA in 626.875µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:53159->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:28.393598 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 A in 655.365µs: exchanging with [::1]:5337 over udp: read udp [::1]:37651->[::1]:5337: read: connection refused
2023/12/17 17:21:28.393603 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 HTTPS in 798.594µs: exchanging with [::1]:5337 over udp: read udp [::1]:46564->[::1]:5337: read: connection refused
2023/12/17 17:21:28.393598 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;b.1.8.e.f.8.c.d.c.3.4.c.9.7.0.8.0.0.0.0.7.f.6.a.7.4.3.1.a.0.d.f.ip6.arpa.	IN	 PTR in 748.646µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:34644->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:28.393598 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 AAAA in 737.969µs: exchanging with [::1]:5337 over udp: read udp [::1]:44698->[::1]:5337: read: connection refused
2023/12/17 17:21:27.377562 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 HTTPS in 498.177µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:35362->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:27.376992 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 HTTPS in 823.229µs: exchanging with [::1]:5337 over udp: read udp [::1]:55990->[::1]:5337: read: connection refused
2023/12/17 17:21:27.374864 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 A in 533.125µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:53552->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:27.374839 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 HTTPS in 611.094µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:55443->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:27.374838 [error] dnsproxy: upstream 127.0.0.1:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 AAAA in 706.562µs: exchanging with 127.0.0.1:5337 over udp: read udp 127.0.0.1:58722->127.0.0.1:5337: read: connection refused
2023/12/17 17:21:27.374010 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 A in 850.885µs: exchanging with [::1]:5337 over udp: read udp [::1]:46286->[::1]:5337: read: connection refused
2023/12/17 17:21:27.374007 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 HTTPS in 769.167µs: exchanging with [::1]:5337 over udp: read udp [::1]:38832->[::1]:5337: read: connection refused
2023/12/17 17:21:27.374001 [error] dnsproxy: upstream [::1]:5337 failed to exchange ;passwordsleakcheck-pa.googleapis.com.	IN	 AAAA in 809.323µs: exchanging with [::1]:5337 over udp: read udp [::1]:43079->[::1]:5337: read: connection refused
2023/12/17 17:20:40.844937 [info] dnsproxy: entering tcp listener loop on [::]:53
2023/12/17 17:20:40.844810 [info] dnsproxy: entering udp listener loop on [::]:53
2023/12/17 17:20:40.844667 [info] dnsproxy: listening to tcp://[::]:53
2023/12/17 17:20:40.844564 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2023/12/17 17:20:40.844533 [info] dnsproxy: listening to udp://[::]:53
2023/12/17 17:20:40.844327 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2023/12/17 17:20:40.844268 [info] dnsproxy: max goroutines is set to 300
2023/12/17 17:20:40.844255 [info] dnsproxy: cache: disabled
2023/12/17 17:20:40.844240 [info] The server is configured to refuse ANY requests
2023/12/17 17:20:40.844221 [info] Ratelimit is enabled and set to 20 rps, IPv4 subnet mask len 24, IPv6 subnet mask len 56
2023/12/17 17:20:40.844113 [info] dnsproxy: starting dns proxy server
2023/12/17 17:20:40.835782 [info] go to http://[fe80::8ede:f9ff:fe33:6423%phy0-ap0]:3000
2023/12/17 17:20:40.835766 [info] go to http://[fe80::8ede:f9ff:fe33:6422%phy1-ap0]:3000
2023/12/17 17:20:40.835749 [info] go to http://[fe80::8ede:f9ff:fe33:6422%br-lan]:3000
2023/12/17 17:20:40.835733 [info] go to http://[fd0a:1347:a6f7::1]:3000
2023/12/17 17:20:40.835694 [info] go to http://192.168.10.1:3000
2023/12/17 17:20:40.835677 [info] go to http://[fe80::8ede:f9ff:fe03:893d%wan]:3000
2023/12/17 17:20:40.835658 [info] go to http://[::1]:3000
2023/12/17 17:20:40.835602 [info] go to http://127.0.0.1:3000
2023/12/17 17:20:40.830985 [info] clients: processing addresses
2023/12/17 17:20:40.830958 [info] AdGuard Home is available at the following addresses:
2023/12/17 17:20:40.829415 [info] dnsproxy: max goroutines is set to 300
2023/12/17 17:20:40.829348 [info] dnsproxy: cache: enabled, size 4096 b
2023/12/17 17:20:40.823804 [info] web: initializing
2023/12/17 17:20:40.823722 [info] auth: initialized.  users:1  sessions:1
2023/12/17 17:20:40.821105 [info] Initializing auth module: /usr/bin/AdGuardHome/data/sessions.db
2023/12/17 17:20:40.813464 [info] safesearch default: disabled
2023/12/17 17:20:40.787791 [info] tls: using default ciphers
2023/12/17 17:20:40.779091 [info] AdGuard Home, version v0.107.43

**Comment by ainar-g** [comment]
```[::1]:5337: read: connection refused```

This looks like whatever is on port `5337` is refusing connections.  Assuming it's one of your upstreams, you should probably inspect it.

For questions and answers, please use [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a).

**Comment by liyiranlab** [comment]
谢谢解答，我下回注意规矩。

**Comment by llity** [comment]
> 谢谢解答，我下回注意规矩。

解决了吗？为也遇到这个问题，ROS
