### ISSUE TITLE
Androoid phone loses internet connection over WiFi when AdGuard Home is running on router.

### ISSUE THREAD

**Issue by rivaros** [AdguardTeam/AdGuardHome#6554]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

 v0.107.36

### Action

What we have:

1. AdGuardHome is running on OpenWRT router and is processing all DNS requests from home network.
2. DHCP is being done by router itself (not by AdGuardHome), based on device MAC addresses.

**Important note:** all devices, including mobile phones within router WiFi use their own MAC addresses, "hide MAC address" features are turned off, so everybody is assigned a strict IP address.

3. All blocklists are disabled, so adguardhome service is running without any blocking

Problem:

1. Android phones lose internet connection through WiFi within 3-4 minutes of connection. Only reconnection to WiFi fixes the issue for next few minutes.
2. All other devices, including macbooks, iphones work without any issues.

If AdguardHome is stopped and dns handled by router, Android works as usual.

Probable cause:
Definitely AdGuardHome messes up with some DNS queries even when all filtering is disabled,
For e.x. maybe this is related:
<img width="1186" alt="Screenshot 2023-12-17 at 11 04 59 PM" src="https://github.com/AdguardTeam/AdGuardHome/assets/1242369/722d7517-397f-4ac9-acda-e9dd31fa24c4">

### Expected result

Android phones should not lose connection

### Actual result

Android loses connection

**Comment by ainar-g** [comment]
Hello and thanks for the report.

> v0.107.36

We're on v0.107.43 now.  Are you not updating because the OpenWrt package did not catch up yet?

Are all clients in your log `127.0.0.1`?  Does the router proxy DNS queries to AdGuard Home?

Also, are you only using plain DNS?

**Comment by rivaros** [comment]
@ainar-g 
> We're on v0.107.43 now. Are you not updating because the OpenWrt package did not catch up yet?
yes, exactly

> Are all clients in your log 127.0.0.1?
No, usually it shows internal IP there 192.168.x.x assigned by DHCP
Also for Android phone. But then suddenly it starts whowing these records with 127.0.0.1 (i thin kits only for Android, as other devices not affected)

>> Does the router proxy DNS queries to AdGuard Home?
No, DNS is switched off on router

>> Also, are you only using plain DNS?
I guess yes, nothing not standard

**Comment by rivaros** [comment]
I will try to install some network tools on Android phone to track whats happening. What i can see that approximately after 3-4 minutes on WiFi connection is lost (WiFi is connected, but no internet access). Later after 10 minutes it switches off WiFi (maybe it's done by the OS bcz it cannot detect internet)

**Comment by DandelionSprout** [comment]
• *"Btw, is AdGuardHome IPv6 compatible?"*
Yes. 🌞

• *"Have figured out the issue was with another openwrt router announcing itself as IPv6 DNS server."*
Sounds like a successful closed case, so I'll mark the issue as fixed.
