### ISSUE TITLE
DHCP filtering function

### ISSUE THREAD

**Issue by pengtaohong** [AdguardTeam/AdGuardHome#6556]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

In the DHCP service, I want to manually configure the devices that are allowed to access.

### Proposed solution

Add dhcp filtering function to allow manual configuration of black and white lists.

**Comment by ainar-g** [comment]
Duplicate of #5908
