### ISSUE TITLE
Chrome asks to translate English Web Interface from Portuguese 

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#656]
When visiting the Web Interface in Google Chrome, the browser asks to translate the page even though it is already in English. Seems to be new since v0.94.

### Steps to reproduce

1. Set Chrome to use English
2. Install AdGuard Home
3. Visit Web Interface

### Expected behavior
Page loads without any translation pop-ups.

### Actual behavior
Chrome suggests to translate the page as it thinks it is in Portuguese.

<details><summary>Screenshot:</summary>

![translate](https://user-images.githubusercontent.com/46271764/54862425-b7736a80-4d8e-11e9-904c-ea963e659526.jpg)

![translate2](https://user-images.githubusercontent.com/46271764/54862440-f99cac00-4d8e-11e9-8295-c753f6a4f385.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.94
| How did you setup DNS configuration:| IoT
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+

**Comment by adrianh-za** [comment]
I get this as well on Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by ameshkov** [comment]
Yeah, and I just got this on mobile :(
