### ISSUE TITLE
DNS rewrites not working

### ISSUE THREAD

**Issue by GenkaOk** [AdguardTeam/AdGuardHome#6567]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

```sh
$ nslookup -debug -type=a 'eu-api.coolkit.cc' '192.168.2.220'

Server:		192.168.2.220
Address:	192.168.2.220#53

------------
    QUESTIONS:
	eu-api.coolkit.cc, type = A, class = IN
    ANSWERS:
    ->  eu-api.coolkit.cc
	canonical name = eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com.
	ttl = 76
    ->  eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
	internet address = 18.184.132.196
	ttl = 37
    ->  eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
	internet address = 3.122.96.241
	ttl = 44
    ->  eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
	internet address = 3.64.223.105
	ttl = 57
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
eu-api.coolkit.cc	canonical name = eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com.
Name:	eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
Address: 18.184.132.196
Name:	eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
Address: 3.122.96.241
Name:	eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
Address: 3.64.223.105
```

### Expected result

Ожидается ответ с IP адресом: 192.168.2.220, но по факту получаем обычный ответ от вышестоящих DNS-серверов

```
Non-authoritative answer:	
Address: 192.168.2.220
```

### Actual result

```
Non-authoritative answer:
eu-api.coolkit.cc	canonical name = eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com.
Name:	eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
Address: 18.184.132.196
Name:	eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
Address: 3.122.96.241
Name:	eu-api-elb-1968000189.eu-central-1.elb.amazonaws.com
Address: 3.64.223.105
```

### Additional information and/or screenshots

![Снимок экрана 2023-12-20 в 11 19 41](https://github.com/AdguardTeam/AdGuardHome/assets/2690324/392f74e5-b436-434d-be29-543cf0b000e2)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/2690324/d793f37f-51a1-473b-b377-592caeeecf47)

**Comment by ainar-g** [comment]
Добрый день.  Мы не можем это воспроизвести.  Убедитесь, что у вас вклчена галка _Блокировать домены с использованием фильтров и файлов hosts_ на страние _Настройки → Основные настройки,_ так как перезапись является частью фильтрации.

Если проблема не в этом, мы рекомендуем включить [сбор debug-логов](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) чтобы лучше продиагностировать ситуацию.

**Comment by Tostibrand** [comment]
I have the same issue with the "block domains using filters and hosts files" enabled.

i can manually add my local DNS redirect on every machine i own in the hosts file, but thats alot of work..

**Comment by Tostibrand** [comment]
> I have the same issue with the "block domains using filters and hosts files" enabled.
> 
> i can manually add my local DNS redirect on every machine i own in the hosts file, but thats alot of work..

After disabling "use private reverse DNS resolvers" and "Enable reverse resolving of clients IP adresses" under "DNS settings" it seems to be working correctly now!
