### ISSUE TITLE
Enhance the security of doh

### ISSUE THREAD

**Issue by DFIUGFSguygs** [AdguardTeam/AdGuardHome#6571]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I checked my doh and found that adguard home did not prioritize the use of FS series cipher suites. I couldn't find how to open it on Google. If you don't prioritize the use of encryption suites that support forward security (Forward Secrecy), it may increase the risk of man-in-the-middle attacks.

### Proposed solution

Set the switch or force open the FS series encryption suite

**Comment by ainar-g** [comment]
See https://github.com/AdguardTeam/AdGuardHome/issues/4925#issuecomment-1253976072 and https://github.com/AdguardTeam/AdGuardHome/pull/4990#issuecomment-1279967769.
