### ISSUE TITLE
DNS Rewrite with Wildcard dont work

### ISSUE THREAD

**Issue by whyisthisbroken** [AdguardTeam/AdGuardHome#6573]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.51

### Action

```sh
*.pool.ntp.org -> Local Time Server 192.168.178.10
```

### Expected result

Rewrite and redirect to the local NTP

### Actual result

Resolve to pool.ntp.org and not local...
![Screenshot 2023-12-22 092049](https://github.com/AdguardTeam/AdGuardHome/assets/96284773/178b7453-d1dd-4482-97ff-31f37cc2f923)

### Additional information and/or screenshots

If i set it to "pool.ntp.org" the rewrite is correct - but if i set a wildcard option to "*.pool.ntp.org" it doesnt work anymore. It ignores completly the Rule

**Comment by xRuffKez** [comment]
It works for me. Using AGH on Debian 12 publicly.

**Comment by whyisthisbroken** [comment]
> It works for me. Using AGH on Debian 12 x86_64 publicly.

So, your Rule is under Filter / DNS Rewrites with *.pool.ntp.org to a Local or Public Adress of your choice and it works?
Also on beta AGH ?
My OS is DietPi on a Raspberry 4

**Comment by xRuffKez** [comment]
![Screenshot_20231222_134338_Samsung Internet](https://github.com/AdguardTeam/AdGuardHome/assets/92758042/d89758a9-3154-4317-a47e-6357b9d941a7)

I have added *.pool.ntp.org to rewrite with A record 1.1.1.1 for testing. It rewrites correctly.

Using v0.107.43 on Debian 12 x86_64 on public dedicated Server.

**Comment by xRuffKez** [comment]
Btw, have you cleared dns cache on AGH?

**Comment by whyisthisbroken** [comment]
try it with 1.1.1.1 - same problem.
It works only with the RegEx Rule... dont know why. Maybe a Beta Bug...
Seems that the Wildcard doesnt take effect.

AGH is Cache disabled. I use Unbound + Redis as Cache Database and i´ve cleared that before testing.
The Rewrite works - but only without Wildcard. So i dont think that the Cache is the Problem here....

**Comment by xRuffKez** [comment]
Your picture Shows AAAA, but have you Set an ipv6 address also in rewrite? Else you can ignore the AAAA NXDOMAIN Response.
With your rule only the A record gets rewritten

**Comment by xRuffKez** [comment]
To prevent AAAA leaking when using A record only, also rewrite by setting NOERROR

**Comment by whyisthisbroken** [comment]
Damn - wow i´m feeling stupid now xD I forgot the AAAA Rule  - make sense yeah...
so i added now 4 Rules:
2x *.pool.ntp.org for A
2x pool.ntp.org for AAAA

And it works now without the RegEx. Thank you. Have nice Christmas Days.

**Comment by xRuffKez** [comment]
> Damn - wow i´m feeling stupid now xD I forgot the AAAA Rule - make sense yeah... so i added now 4 Rules: 2x *.pool.ntp.org for A 2x pool.ntp.org for AAAA
> 
> And it works now without the RegEx. Thank you. Have nice Christmas Days.

Or just add two rules:

*.pool.ntp.org ::ffff:192.168.178.10
*.pool.ntp.org 192.168.178.10

Happy Hollidays :)
