### ISSUE TITLE
Option “Private reverse DNS servers” isn't working properly

### ISSUE THREAD

**Issue by IRainman** [AdguardTeam/AdGuardHome#6579]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

I try to set
Private reverse DNS servers
as
192.168.2.2

### Expected result

Server test passed

### Actual result

Server test failed

### Additional information and/or screenshots

The nslookup command is successfully worked for the server 192.168.2.2

Windows 2008 R2

**Comment by ainar-g** [comment]
Hello.  To better understand what's going on, please:

1.  Enable [debug logging](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and see which errors and debug logs are printed when the upstream check is performed.

2.  Add the `nslookup` command you're using and its result.  AdGuard Home uses the `in-addr.arpa.` FQDN, so your query should be something like:

    ```ps1
    nslookup -debug -type=ptr 'in-addr.arpa.' '192.168.2.2'
    ```

    N.B. the final dot in `in-addr.arpa.`.

**Comment by IRainman** [comment]
nslookup -debug -type=ptr 'in-addr.arpa.' '192.168.2.2'
*** Can't find server address for ''192.168.2.2'':
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NOERROR
        header flags:  response, auth. answer, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        1.1.168.192.in-addr.arpa, type = PTR, class = IN
    ANSWERS:
    ->  1.1.168.192.in-addr.arpa
        name = control
        ttl = 3600 (1 hour)

------------
Server:  control
Address:  192.168.1.1

DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
*** Request to control timed-out

C:\Users\Administrator>nslookup -debug -type=ptr 'in-addr.arpa.' '192.168.1.1'
*** Can't find server address for ''192.168.1.1'':
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NOERROR
        header flags:  response, auth. answer, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 0

    QUESTIONS:
        1.1.168.192.in-addr.arpa, type = PTR, class = IN
    ANSWERS:
    ->  1.1.168.192.in-addr.arpa
        name = control
        ttl = 3600 (1 hour)

------------
Server:  control
Address:  192.168.1.1

DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
*** Request to control timed-out

**Comment by overwatch3560** [comment]
is this still an issue @IRainman
