### ISSUE TITLE
"Anonymize client IP" does not work on latest version

### ISSUE THREAD

**Issue by Raviu56** [AdguardTeam/AdGuardHome#6584]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.43

### Action

Normal usage of AdguardHome installed on a cloud server as DNS resolver for many devices and routers.
After recent upgrade to v0.107.43 also I got a high rush of DNS requests , I can see all IPs in Top clients and in query log are not anonymized any more, they are stated as is.

### Expected result

Expected to see anonymized IPs as usual

### Actual result

Plain IPs

### Additional information and/or screenshots

I've made sure `anonymize_client_ip: true` in yaml and restarted the service and whole server, cleared logs and stats many times without success.
It was working very fine few days ago before upgrade

**Comment by schzhn** [comment]
We've pushed the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) that contains the fix. Could you please check it?

**Comment by schzhn** [comment]
We will close this issue for now. If the problem persists, feel free to reopen it.
