### ISSUE TITLE
Allow set different "Custom IP for ECS" for each client

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/AdGuardHome#6586]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When using VPN tunnel, the client uses LAN IP, such like `10.192.224.255`. If add "Custom IP for ECS" for each client support, then user can set specific ECS IP for it. For current version, AGH only can using the IP from server settings if query has no ECS IP.

### Proposed solution

Add a checkbox and textbox similar to the "Upstream DNS cache configuration"
<img width="495" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/58100052/535a0343-83b7-453e-bb9f-944f77f0f283">

**Comment by EugeneOne1** [comment]
Closed due to duplication of #6492.
