### ISSUE TITLE
Add "AWAvenue Ads Rule" to AdGuard Home Filter list

### ISSUE THREAD

**Issue by TG-Twilight** [AdguardTeam/AdGuardHome#6590]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

This rule has been added to the "HostlistsRegistry" and is visible in the AdGuard DNS filter list. Hope to add it to the filter list of AdGuard Home to facilitate users to subscribe.

### Proposed solution

Add "AWAvenue Ads Rule" to AdGuard Home Filter list，thanks!

Use Adblock syntax to fight against various advertising SDKs in Android applications from the network level , prevent them from loading.

https://github.com/TG-Twilight/AWAvenue-Ads-Rule

https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/filter_53.txt

**Comment by DandelionSprout** [comment]
To the best of my knowledge, AdGuard Home *does* use AdGuard DNS Filter by default in the "DNS blocklists" settings.

**Comment by ainar-g** [comment]
Please send requests regarding filtering rule lists to <https://github.com/AdguardTeam/HostlistsRegistry>.
