### ISSUE TITLE
Enhanced Per client/ctag configuration

### ISSUE THREAD

**Issue by coaoac** [AdguardTeam/AdGuardHome#6599]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I am trying to set up basic parents controls for my kids’ devices with specific blocklists and blocked domains that get activated during certain times of the year. 
In Pihole this easily achieved with their ”groups” functionality. One can allocate devices, block lists and block domains to ceratin groups activate or deactivate groups using a very simple cron job. 
I am not able to achieve the same result in Adguard Home. the closest I can do is activate/deactivate services on a schedule, which is far from a good solution because services, while very useful, are not always reliable, the pausing feature cannot go beyond midnight, and there is no way to pause blocking via domains or block lists.

### Proposed solution

Add new tabs to the per client configuration to define block lists to apply as well as manual domains with an option to pause the blocking during specific times. 
Same can be applied to upstream servers and other settings.
(in addition to allow the pausing to accept for multiple time intervals per days and to go beyond 23:59)

### Alternatives considered and additional information

Implement a way to activate/deactivate ctags based on schedule.
(also fix the scheduling feature as per above)

**Comment by EugeneOne1** [comment]
@coaoac, hello.  It seems we already have an exact feature request about client tags (#5143).  We're also have a bunch of schedule-related feature/enhancement requests (#5870, #6326, #6598).  Please consider following and upvoting those.
