### ISSUE TITLE
Add DNSSEC support

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [AdguardTeam/AdGuardHome#66]
I think adding full DNSSEC validation will making all queries more reliable unless clients explicitly opt out.

**Comment by ameshkov** [comment]
It makes sense, thank you for the feature request!

**Comment by Itsnothectic** [comment]
I came here to make this same request. 

To test if DNSSEC is enabled opening sigfail.verteiltesysteme.net you should get an error. If you test sigok.verteilesysteme.net you should see a blank page.

**Comment by sergeevabc** [comment]
Unfortunately, [another][1] DNSSEC resolver test fails so far.

[1]: http://dnssec.vs.uni-due.de/

**Comment by TPS** [comment]
So many other major improvements have been finished or are in progress, I'm afraid to ask, but is there any publicly available update toward this?

**Comment by ameshkov** [comment]
Not yet, guys. I am sorry for the delays, we're a bit limited in resources, and I'd like not to switch to DNS tasks until we can really focus on them.

**Comment by TPS** [comment]
No worries!  Just figuring, since [DNSCrypt](https://github.com/AdguardTeam/AdguardDNS/issues/118) got done, perhaps this got some love as well.  Keep on 🚚ing! 📣

**Comment by evilvibes** [comment]
Any update on this?

**Comment by ameshkov** [comment]
@evilvibes we don't want to touch the current installation until the updated version is ready. That's why this issue is still open.

**Comment by TPS** [comment]
So, does that mean there's ß version someplace?  Will it be accessible to ~~play with~~ test sometime?

**Comment by ameshkov** [comment]
> So, does that mean there's ß version someplace? Will it be accessible to play with test sometime?

I'd say it's more of a "demo" at the moment. The old code was tossed out, and the new version is basically a patched Unbound DNS server. Not yet available publicly.

**Comment by Corsten56** [comment]
Yes. Will wait for DNSSEC support. Most important thing in modern Russia.

**Comment by ibksturm** [comment]
Hi there, any news about dnssec?

and do you think hheres a opinion do start a server in central europe example frankfurt or zurich?

greets

**Comment by jonathanmmm** [comment]
Central Europe Server would be great, yes 👍

**Comment by ibksturm** [comment]
jupp, would be great, so my route don't have to go over the half of the world as i wrote months ago ^^

**Comment by Ryan-Goldstein** [comment]
Any updates on this issue? DNSSEC is very important and has been receiving increased attention lately, including as a part of Cloudflare's Crypto Week 2018 (https://blog.cloudflare.com/automatically-provision-and-maintain-dnssec/).

**Comment by CWo42** [comment]
I was planning to open also a DNSSEC Request but since there is already one, one more who wishes this option

**Comment by ameshkov** [comment]
We'll prioritize this issue, guys, thank you!

**Comment by Mikiya83** [comment]
Do you have any news ? it's a big feature now for a DNS server. Thanks !

**Comment by ameshkov** [comment]
No news yet on this yet, sorry

**Comment by lordraiden** [comment]
How far are you from implement this?
Is the only thing I still keep pihole together with https://github.com/AdguardTeam/AdGuardHome/issues/922 and a few other thing of milestone 0.101

**Comment by Revertron** [comment]
Just to keep in mind: it should be possible to mark some domains and zones as "unsecure", not to try verification at all.

**Comment by ibksturm** [comment]
ьолшо сьасибо 👍

**Comment by kmahyyg** [comment]
Recently, I enabled the dnsmasq's DNSSEC on my openwrt router and it works as a dns proxy just working the same as the normal router, ADH on my laptop. I set to use ADH as local dns and CF (DoT) as upstream. However, when dnsmasq's DNSSEC enabled, the ADH failed to dispatch any valid DNS response. According to the verbose log of ADH, it seems that ADH just got connection error from upstream and then returned error(But I'm not so sure about that, my internet connectivity is working properly). I tried to switch off the dnsmasq's DNSSEC, ADH works properly.

Any suggestion?

**Comment by ameshkov** [comment]
@kmahyyg have you tried checking what exactly dnsmasq returns for these queries?

**Comment by kmahyyg** [comment]
Yes, I tried. works perfectly.

Send from Evangeline's Android

________________________________

**Comment by ameshkov** [comment]
Weird, what kind of connection error does AGH receives?

**Comment by kmahyyg** [comment]
> Weird, what kind of connection error does AGH receives?

I don't know. I turned on verbose , all logging seems perfect, just get response from upstream as NORESPONSE FROM UPSTREAM. but those domains really exists. I tried to use `kdig` and set the upstream correctly, the domain is exists.

After I turned off DNSSEC on my router, all things get working.  BTW, I'm in china mainland, which has serious network censorship.

**Comment by ameshkov** [comment]
Could you please post a part of the log with these requests and responses? Maybe I'll see something there

**Comment by kmahyyg** [comment]
> Could you please post a part of the log with these requests and responses? Maybe I'll notice something there

[logfile-20200416-2.log](https://github.com/AdguardTeam/AdGuardHome/files/4484627/logfile-20200416-2.log)

Here's the full log after I enabled DNSSEC on my router. Since I've configured the upstream as log shown, it shouldn't be failed to response.

**Comment by szolin** [comment]
@kmahyyg Can you disable SafeBrowsing ?
In your logs I only see `SafeBrowsing: checking...` but no sign of the results of SB check.  That's very strange considering 3sec timeout for those operations.
Looks like a global dead lock to me: no goroutine has woken up from SB check.

**Comment by kmahyyg** [comment]
> @kmahyyg Can you disable SafeBrowsing ?
> In your logs I only see `SafeBrowsing: checking...` but no sign of the results of SB check. That's very strange considering 3sec timeout for those operations.
> Looks like a global dead lock to me: no goroutine has woken up from SB check.

I will try later... But I think dnssec shouldn't have affiliate with SB?

**Comment by ameshkov** [comment]
@szolin 

Here's why it happens:
```
2020/04/16 10:40:18 17356#55 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns-family.adguard.com in 59 milliseconds using 176.103.130.131. Result : []
2020/04/16 10:40:18 17356#54 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns-family.adguard.com in 78 milliseconds using 176.103.130.130. Result : []
```

@kmahyyg 
Could it be that your router intercepts plain DNS queries and does some additional filtering? Because it seems that when DNSSEC is enabled, we cannot resolve `dns-family.adguard.com` address (empty "Result: []" in the log)

**Comment by kmahyyg** [comment]
> @szolin
> 
> Here's why it happens:
> 
> ```
> 2020/04/16 10:40:18 17356#55 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns-family.adguard.com in 59 milliseconds using 176.103.130.131. Result : []
> 2020/04/16 10:40:18 17356#54 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns-family.adguard.com in 78 milliseconds using 176.103.130.130. Result : []
> ```
> 
> @kmahyyg
> Could it be that your router intercepts plain DNS queries and does some additional filtering? Because it seems that when DNSSEC is enabled, we cannot resolve `dns-family.adguard.com` address (empty "Result: []" in the log)

pretty weird......

![image](https://user-images.githubusercontent.com/16604643/79585038-ce0b0300-8101-11ea-81af-5b06e277dfe0.png)

**Comment by kmahyyg** [comment]
Okay, I see the problem. The last photo is DNSSEC disabled.

![image](https://user-images.githubusercontent.com/16604643/79585228-162a2580-8102-11ea-8c1c-f1084dd7cbf4.png)

 This is enabled. Problem is `SERVFAIL`. But even so, this should not happen. Why does DNSSEC use my router's DNS instead of using the upstream DNSs I specified in the AGH setting?

**Comment by ameshkov** [comment]
> Why does DNSSEC use my router's DNS instead of using the upstream DNSs I specified in the AGH setting?

We use it just one time - when we resolve `dns-family.adguard.com` address for the first time.

**Comment by ibksturm** [comment]
> > Why does DNSSEC use my router's DNS instead of using the upstream DNSs I specified in the AGH setting?
> 
> We use it just one time - when we resolve `dns-family.adguard.com` address for the first time.

maybe thats the problem... theres a circle

look (example):

routerdns (dnsmasq) 127.0.0.1:53 forwards to AGH on 127.0.0.1:55

AGH ask router onfirst time „hey whats dns-family.adguard...“. router ask back... we‘ve got a circle

possible solution is, if AGH do allways the first request to quad9 or $upstreamresolvers

**Comment by szolin** [comment]
> AGH ask router onfirst time „hey whats dns-family.adguard...“

Are you sure?  Can you show the packets AGH sends to your router?
AGH uses these 2 IP addresses "176.103.130.130", "176.103.130.131" to resolve `dns-family.adguard.com`.

**Comment by ameshkov** [comment]
@szolin I suppose that the router may be intercepting plain DNS queries.

**Comment by szolin** [comment]
> I suppose that the router may be intercepting plain DNS queries.

In this case there's nothing wrong with AGH - it's this particular router's configuration problem.

**Comment by ameshkov** [comment]
> In this case there's nothing wrong with AGH - it's this particular router's configuration problem.

Sure, but we shouldn't be stuck in the case when we cannot resolve that address, the safe browsing check should simply quickly fail

**Comment by szolin** [comment]
#1612
