### ISSUE TITLE
Prompting to update to 0.94 when 0.94 is updated and running

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#660]
Prompting to update to 0.94 from 0.94

Occurring in Chrome and Edge

![image](https://user-images.githubusercontent.com/5121135/54866019-ae2ad380-4d77-11e9-9c08-b4d0304fd9d8.png)

**Comment by kang-mk** [comment]
me too

**Comment by Ultrabenosaurus** [comment]
Looks like I don't ned to open my own issue for this...

![image](https://user-images.githubusercontent.com/1901532/54886347-f97bd980-4e7e-11e9-950f-cf089b152b4f.png)

**Comment by ameshkov** [comment]
@szolin @IldarKamalov guys, please check what went wrong. Can we temporarily fix this by making some change to https://github.com/AdguardTeam/AdGuardHome/blob/master/version.json ?

**Comment by AnthonyBe** [comment]
I *was* getting this as well for about the first 48 hours but then it seemed to just go away.

AGH 0.94 running on Windows x64 binaries.
Edge browser and Chrome

**Comment by boatmac** [comment]
I tried to install it on my Pi 3 with the link https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.94/AdGuardHome_v0.94_linux_arm.tar.gz, however, it is always v0.92-hotfix2 after installation which is strange.

**Comment by Ultrabenosaurus** [comment]
@boatmac that seems like a different problem, you may want to open a new issue for that.
