### ISSUE TITLE
Cant add any filter

### ISSUE THREAD

**Issue by JohnFawkes** [AdguardTeam/AdGuardHome#6603]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest edge

### Action

Adding any filter list to the blocklist, including the built in ones (this works fine on a new install but not using my current yaml file I've been using for over a year now.

### Expected result

The blocklist filter to be added correctly

### Actual result

```
Error: control/filtering/add_url | Couldn't fetch filter from URL "https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt": reading from url: Get "https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt": proxyconnect tcp: invalid port : strconv.Atoi: parsing "": invalid syntax | 400
```

**Comment by Caesarovich** [comment]
@JohnFawkes Does the problem occur only when you use your YAML config file ?

**Comment by JohnFawkes** [comment]
Yes it does. Which ive never edited the yaml directly. Ive used the same config for the past year and a half. What i had to do to get it working was start fresh and readd everything manually via the ui. Yaml validators also showed the yaml as being valid. I still have that yaml file that was causing this

**Comment by JohnFawkes** [comment]
> @JohnFawkes Does the problem occur only when you use your YAML config file ?

Yes it does. Which ive never edited the yaml directly. Ive used the same config for the past year and a half. What i had to do to get it working was start fresh and readd everything manually via the ui. Yaml validators also showed the yaml as being valid. I still have that yaml file that was causing this

**Comment by xRuffKez** [comment]
nano /etc/resolv.conf

nameserver 1.1.1.1

**Comment by JohnFawkes** [comment]
This can be closed. I thunk at some point i had set http_proxy thinking it was for reverse proxy however its trusted_proxies that is for that. After removing http_proxy everything is back to working
