### ISSUE TITLE
Filter list name not showing

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#661]
Randomly the filter list name for a list does not show, even though the names are configured in config

![filters1](https://user-images.githubusercontent.com/5121135/54866114-d0712100-4d78-11e9-9227-7b8b62baae02.JPG)

![filters2](https://user-images.githubusercontent.com/5121135/54866117-d830c580-4d78-11e9-846d-2e97b2c209d0.JPG)

![filter3](https://user-images.githubusercontent.com/5121135/54866124-e2eb5a80-4d78-11e9-89d1-015d4eed22f2.JPG)

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.94
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:|  Raspberry Pi 3 Model B
| Operating system and version:| (Raspian 9

**Comment by ameshkov** [comment]
@adrianh-za are there any "steps to reproduce" the issue? Does it happen for the same lists all the time, or the lists are random?

**Comment by adrianh-za** [comment]
It is happening to the same lists all the time as shown in the screenshot above.  "Randomly" was the incorrect word to use in my initial statement. I also just checked in Chrome and Edge, and both show the same list names as empty. 

I believe its a server side rendering issue as the HTML element is blank as screen-shotted above, and it happens in multiple browsers.

I am attaching my yaml file (starred out the username and password, and changed extension to txt).  Hope it helps.

[AdGuardHome.txt](https://github.com/AdguardTeam/AdGuardHome/files/3002653/AdGuardHome.txt)

**Comment by szolin** [comment]
The problem is that after filter is updated its name is reset to the value of `! Title` from the filter's contents.  Since those filters don't have their Title set, we reset filter name to an empty string.

This bug has appeared in v0.94, thank you for noticing it!
