### ISSUE TITLE
v0.107.43 doesn't respond to requests over port 53

### ISSUE THREAD

**Issue by ossandcad** [AdguardTeam/AdGuardHome#6611]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

dig +short @192.168.50.31 NS google.com - This works on v0.107.42, BUT not on v0.107.43.
kdig -d @192.168.50.31 +tls-ca +tls-host=MYLOCALCN www.google.com - this works in both v0.107.42 and .43

Downgrading snap to .42 fixes the problem with no other changes.

### Expected result

ns4.google.com.
ns3.google.com.
ns2.google.com.
ns1.google.com.

### Actual result

;; communications error to 192.168.50.31#53: timed out
;; communications error to 192.168.50.31#53: timed out
;; communications error to 192.168.50.31#53: timed out
;; no servers could be reached

**Comment by udtcp** [comment]
for me it is working on v0.107.43
![image](https://github.com/AdguardTeam/AdGuardHome/assets/154565507/58d7191e-d540-4598-99c6-9172f94ee787)

**Comment by blaine07** [comment]
> for me it is working on v0.107.43 ![image](https://private-user-images.githubusercontent.com/154565507/294627611-58d7191e-d540-4598-99c6-9172f94ee787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzQzMTAsIm5iZiI6MTcwNDU3NDAxMCwicGF0aCI6Ii8xNTQ1NjU1MDcvMjk0NjI3NjExLTU4ZDcxOTFlLWQ1NDAtNDU5OC05OWM2LTkxNzJmOTRlZTc4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQyMDQ2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGY5OWZhMmZjZjUwYTBiMmEzZTI2YTM0M2I5ZGNhOWRjOTk3MGIwMjQwZDY1NmY5MDAwMDkyMzRkOTdjMjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G0DnkeMrfVu-i6GDSNWkmovzFanHf-oux_XW7rqldbY)

Is your instance Docker or in Ubuntu or etc?

**Comment by udtcp** [comment]
adguard home running on openwrt 23.05 on netgear r 7800

**Comment by ossandcad** [comment]
In my case:
1. Ubuntu 22.04.03 LTS
2. Installed via snap:
 Name          Version    Rev   Tracking       Publisher  Notes
adguard-home  v0.107.42  6432  latest/stable  ameshkov✓  -
adguard-home  v0.107.43  6448  latest/stable  ameshkov✓  disabled
3. ufw status
443                        ALLOW       Anywhere
53                         ALLOW       Anywhere 
53/tcp                     ALLOW       Anywhere
853                        ALLOW       Anywhere     
53 (v6)                    ALLOW       Anywhere (v6)
853 (v6)                   ALLOW       Anywhere (v6)  
53/tcp (v6)                ALLOW       Anywhere (v6)  


(apologies - missed this since email went to Promotions folder)

**Comment by knaggsy2000** [comment]
I've been getting some weird issues regarding resolving too, please check my post involving it - #6500

It might help, but can't promise anything,

**Comment by ossandcad** [comment]
Thanks @jslawler-gh - I should have clarified earlier - later versions definitely do not have this problem. Auto-updates via Snap and only had to blacklist that one version.
