### ISSUE TITLE
disable webinterface on https

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#662]
Dobri dem guys

first: thank to your work on release 0.94, you all did a great job!

second:
i think i'm to stupid, but how could i disable webconfig on httpsport WITHOUT disabling DoT and DoH server...

Reason is i did some updates on ibksturm.synology.me DoT, DoH and DNSCRYPT Server Backend...
Setup:
Router.... NGINX (LoadBalancer) 
-> DoT (AGH)
-> DoH (AGH)
-> DNSCRYPT (dnscrypt-wrapper - AGH)

so i enabled on AGH Webinterface Crypto. All Belongs to resolver works fine....

But NOW if i tip in browser ibksturm.synology.me, the login screen from AGH pops up... from outside the world (tested with my handy on 4G mobilenetwork)... it would be ok if it's only behind my router but from otherworld...  better would be my little index.html website i configured on nginx 

any idears to deactivated or a go around? i' not really motivated go code back into nginx - http-proxy - AGH....

Greets

**Comment by ameshkov** [comment]
> i think i'm to stupid, but how could i disable webconfig on httpsport WITHOUT disabling DoT and DoH server...

Well, the intention was to make the configuration simple, that's why there is none:)

> any idears to deactivated or a go around? i' not really motivated go code back into nginx - http-proxy - AGH....

For the complicated configuration like yours, it is recommended to use nginx, I just don't see any alternative. Also, you already have nginx as a load balancer, why not just prohibit all locations except `/dns-query`?

**Comment by ibksturm** [comment]
dobri dem guys

i think i knocket the bas***

`
server {

         listen 8443 ssl http2 reuseport;
        root /var/www/ibksturm;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name ibksturm.synology.me;

        include /etc/nginx/ssl.conf;


        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
               try_files $uri $uri/ =404;
        }

        if ( $request_method !~ ^(GET|POST|HEAD)$ ) {
        return 501;
        }

        location /dns-query {
              proxy_redirect off;
              proxy_buffering off;
              proxy_pass https://dohproxy_backend; #important to write **https**://backend
        }


        location ~ /\.ht {
                deny all;
        }
}

        upstream dohproxy_backend {
                server 192.168.0.191:8545;
        }


`

**Comment by ibksturm** [comment]
some news to everybody

since yesterday, the responsetime for doh-queries geting lower with nginx as loadbalancer

so at the time, i use again 

Router.... NGINX (LoadBalancer)
-> DoT (AGH)
-> DoH (AGH)
-> DNSCRYPT (dnscrypt-wrapper - AGH)
-> public website ibksturm.synology.me (as default on 443)

maybe when the kids are in bed, i'll publish my config

**Comment by lightmaster** [comment]
@ibksturm I would strongly recommend you go through your old comments and issues and redact your actual URL and replace it with something like `domain.example.com`. No point giving bad actors a target to point at...
