### ISSUE TITLE
Installer shows success message when the default port 3000 is alread used

### ISSUE THREAD

**Issue by anasfik** [AdguardTeam/AdGuardHome#6621]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

AdGuard Home, version v0.107.43

### Action

Hi,

I had a service running on port 3000, when I ran the bash installed for AdGuard, it showed no error at all, showing that I can open my private ip on port 3000:

it didn't show that the port is already in use (the other service is listening on all local hosts, ::3000), and so to resolve it, I had to disable the other service so the port 3000 would be unused, then run the installer again and it works great.

The issue is that I got no notice, if I wasn't aware of it, I would just be confused like other might be.

### Expected result

when the installer ran and the port is used, it should inform about itruns

### Actual result

it still shows success message even the port is used by other servicea if 

### Additional information and/or screenshots

Ubuntu server 22.04

![Screenshot from 2024-01-07 16-37-08](https://github.com/AdguardTeam/AdGuardHome/assets/25140579/f95b2ce3-af7d-45d0-b083-a1bccdc915ae)

**Comment by overwatch3560** [comment]
@anasfik could you show a screenshot after installation when you want to configure adguard on port 3000 on your web brouwser?
