### ISSUE TITLE
Request the capability to redirect domain and subdomains

### ISSUE THREAD

**Issue by imTHAI** [AdguardTeam/AdGuardHome#663]
Hello,
As talked on telegram channel, I'd like to be able to redirect domains and their subdomains to a specific ip.
Currently, the only way to redirect domains with AdguardHome is using host files.
But If I declare:
`doubleclick.net 192.168.12.1`
It will redirect only doubleclick.net but not ads.doubleclick.net

It is possible with dnsmasq
In config file I can specify a list of domains to redirect and a separate list with only hostnames to redirect.
conf-file=/adblock/domains.txt
addn-hosts=/adblock/hostnames.txt

It is very useful.

Thank you

**Comment by imTHAI** [comment]
Hello, do you think you can implement that soon ? It still is impossible to redirect a complete domain (including subs) to a specific server.
Thank you !

**Comment by ameshkov** [comment]
It depends on the number of upvotes

**Comment by ibksturm** [comment]
👍 +1

**Comment by szolin** [comment]
Rewrites
