### ISSUE TITLE
client ip always nginx-proxy manager docker container

### ISSUE THREAD

**Issue by kajvans** [AdguardTeam/AdGuardHome#6635]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

look at the dashboard. there is no failure log because it thinks it is the correct ip

### Expected result

i expect that the dashboard shows what user is connected to the dns and makes what requests

### Actual result

it is always the domain of the nginx proxy manager docker container on the same docker network

### Additional information and/or screenshots

i run a reverse proxy because adguard does not run on port 443 because nginx uses that port so an request comes in and gets routed to port 443 via the docker network to the correct container.
nginx uses this address: https://homeDNS:443
name of the container is homeDNS

**Comment by overwatch3560** [comment]
There is no screenshot?
