### ISSUE TITLE
Config clients.runtime_sources.hosts false without effect

### ISSUE THREAD

**Issue by Dennis14e** [AdguardTeam/AdGuardHome#6644]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

AdGuard Host:
```sh
$ cat /etc/hosts
127.0.0.1	localhost
192.168.0.1	dnshost.my.domain	dnshost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

AdGuard gets the IP from /etc/hosts, which is disabled per config
```sh
$ host dnshost.my.domain 127.0.0.1
Using domain server:
Name: 127.0.0.1
Address: 127.0.0.1#53
Aliases: 

dnshost.my.domain has address 192.168.0.1
```

This is the right answer from upstream DNS server
```sh
$ host dnshost.my.domain 192.168.5.1
Using domain server:
Name: 192.168.5.1
Address: 192.168.5.1#53
Aliases: 

dnshost.my.domain has address 192.168.2.1
```

AdGuardHome.yaml
```yaml
[...]
dns:
  upstream_dns:
    - '[/my.domain/]192.168.5.1'
clients:
  runtime_sources:
    hosts: false
[...]
```

### Expected result

AdGuard Home is configured to redirect all queries for my domain (my.domain) to an upstream DNS server, which generally works.
I set the option clients.runtime_sources.hosts to false and restarted AdGuard Home, with no effect.
The GUI states "Status: Rewritten, Rule: System hosts files".

For domain dnshost.my.domain I get 192.168.0.1 (from hosts file).

### Actual result

I should get 192.168.2.1 as result (from upstream DNS server)

### Additional information and/or screenshots

I replaced all values with placeholders.

AdGuard server: dnshost.my.domain / 127.0.0.1
IP in /etc/hosts: 192.168.0.1

Other DNS server: 192.168.5.1
IP of dnshost.my.domain on upstream DNS server: 192.168.2.1

**Comment by schzhn** [comment]
As a workaround, you can use the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) that includes the panic fix with the `--no-etc-hosts` flag.
```
./AdGuardHome --no-etc-hosts
```

**Comment by ainar-g** [comment]
Merging into #6610.  Please describe in that issue, why do you want to keep the “incorrect” mapping in your `/etc/hosts`.

**Comment by tjharman** [comment]
I don't quite follow this thread.

Is ```clients.runtime_sources.hosts=false``` supposed to work, or are we supposed to use --no-etc-hosts ?

The reason I don't want /etc/hosts to be read is I use split-horizon DNS, and I host websites on the same server I run my AdguardHome.

When I'm out on the road, remote (offnet) clients are cofigured to use a public DNS server, and thus I want the public IP address returned of my webserver.  Because it's reading /etc/hosts though it's saying that my public website's IP is 192.168.0.5 which obviously doesn't work.

I want all AdGuardDNS to be driven by DNS requests, not /etc/hosts lookup.

I'm using AdGuardHome v0.107.43

**Comment by GingerAdonis** [comment]
For anyone coming across this issue: Make sure to disable `dns.hostsfile_enabled` in the configuration as well.
