### ISSUE TITLE
v0.108.0-b51 客户端排行中的ipv6设备会自动加上%br-lan标识

### ISSUE THREAD

**Issue by xilaochengv** [AdguardTeam/AdGuardHome#6645]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b51

### Action

这是b.50版本的客户端排行
![PixPin_2024-01-17_00-22-55](https://github.com/AdguardTeam/AdGuardHome/assets/134846861/3dc12c45-bf48-41ee-a25a-3381184c4cbd)

### Expected result

这是b.51版本的客户端排行
![PixPin_2024-01-17_00-24-25](https://github.com/AdguardTeam/AdGuardHome/assets/134846861/403bf7b7-813f-4b02-a83e-afeb095a415d)

### Actual result

直接点击客户端后无法查看日志，需要手动删除%br-lan字符才能显示
![PixPin_2024-01-17_00-24-37](https://github.com/AdguardTeam/AdGuardHome/assets/134846861/d15921fd-81d5-4dc7-891c-5cf752f14b65)

**Comment by schzhn** [comment]
Related https://github.com/AdguardTeam/AdGuardHome/issues/6584
The upcoming v0.108.0-b.52 release will contain the fix.
You can also check the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions).
