### ISSUE TITLE
Add support for remote logging

### ISSUE THREAD

**Issue by mfbloom** [AdguardTeam/AdGuardHome#6664]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

DNS query results are only stored via QueryLog to a file, and there is no current method to ship the logs remotely to an external system.

### Proposed solution

Give users the ability to remotely ship logs via TCP or UDP. Users will have the ability to update these settings from the UI under the General -> Logs configuration section.

In this section, the user will be able to specify if remote logging is enabled/disabled, the endpoint/port of the remote host, and the protocol to utilize (UDP/TCP). Additionally, users will be provided limited options in how the message will be formatted and the fields that can be included. This will be written so it can be expanded easily in the future. 

### Alternatives considered and additional information

A separate logging system could be utilized to retrieve the logs from disk. However, it would be beneficial to have the option to ship the logs directly.

I have started writing the code and am almost ready for a PR.

**Comment by ainar-g** [comment]
Merging into #4233, if you don't mind.

> I have started writing the code and am almost ready for a PR.

The current query logging code is not the best and will probably be replaced for v0.108, see #2290.  This is also a big feature that sounds like it would need a lot of support, and most users won't have use for it, so I want to be honest and say that the possibility of merging it in the near future is not that high.
