### ISSUE TITLE
DNS 重写异常

### ISSUE THREAD

**Issue by exewen** [AdguardTeam/AdGuardHome#6665]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Snapcraft

### Setup

On one machine

### AdGuard Home version

v0.107.43

### Action

DNS重写异常，当后台配置exweb.com 为139.159.181.223正常
```sh
nslookup exweb.com 
Server:         10.0.2.1
Address:        10.0.2.1#53

Non-authoritative answer:
Name:   exweb.com
Address: 139.159.181.223
```
当后台配置exweb.com 为10.0.8.1或者192.168.5.44 不正常
```
nslookup exweb.com 
Server:         10.0.2.1
Address:        10.0.2.1#53

Non-authoritative answer:
*** Can't find exweb.com: No answer
```
已被过滤器拦截为0，插件是否对网段有限制？

### Expected result

```
nslookup exweb.com 
```

### Actual result

出现重写解析

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/22954029/7d1dbabe-eeb7-4ca2-ae4e-7223d40977e5)

**Comment by ainar-g** [comment]
Which kind of DNS rewrites are you using: the UI ones or the rule-based, `$dnsrewrite` ones?  We recommend using the latter.

If the former, what does your record look like?
