### ISSUE TITLE
dns: overflowing header size

### ISSUE THREAD

**Issue by xuelei9300** [AdguardTeam/AdGuardHome#6666]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

AdGuard Home, version v0.107.43

### Action

```sh
nslookup -debug -type=a 'www.youtube.com' '$YOUR_AGH_ADDRESS'


Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 query[A] www.youtube.com from 127.0.0.1
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 forwarded www.youtube.com to 127.0.0.1#5353
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply www.youtube.com is <CNAME>
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.66.142
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.207.78
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.24.110
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.24.238
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.25.14
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.27.14
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.27.46
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.31.14
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.199.78
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.204.46
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.204.78
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.204.110
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 142.250.204.142
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 172.217.24.78
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 216.58.200.238
Tue Jan 23 11:46:09 2024 daemon.info dnsmasq[1]: 118 127.0.0.1/45020 reply youtube-ui.l.google.com is 216.58.203.78
Tue Jan 23 11:46:09 2024 user.notice AdGuardHome[4748]: 2024/01/23 11:46:09.079028 [error] dnsproxy: upstream 127.0.0.1:5352 failed to exchange ;www.youtube.com.	IN	 A in 55.550624ms: exchanging with 127.0.0.1:5352 over udp: dns: overflowing header size


```

### Expected result

➜  ~ nslookup -port=5352  www.youtube.com 192.168.1.1
Server:		192.168.1.1
Address:	192.168.1.1#5352

Non-authoritative answer:
www.youtube.com	canonical name = youtube-ui.l.google.com.
Name:	youtube-ui.l.google.com
Address: 142.250.199.78
Name:	youtube-ui.l.google.com
Address: 142.250.204.46
Name:	youtube-ui.l.google.com
Address: 142.250.204.78
Name:	youtube-ui.l.google.com
Address: 142.250.204.110
Name:	youtube-ui.l.google.com
Address: 142.250.204.142
Name:	youtube-ui.l.google.com
Address: 172.217.24.78
Name:	youtube-ui.l.google.com
Address: 216.58.200.238
Name:	youtube-ui.l.google.com
Address: 216.58.203.78
Name:	youtube-ui.l.google.com
Address: 142.251.220.14
Name:	youtube-ui.l.google.com
Address: 142.251.220.46
Name:	youtube-ui.l.google.com
Address: 142.251.220.78
Name:	youtube-ui.l.google.com
Address: 142.251.220.110
Name:	youtube-ui.l.google.com
Address: 142.251.130.14
Name:	youtube-ui.l.google.com
Address: 142.251.222.206
Name:	youtube-ui.l.google.com
Address: 142.250.66.46
Name:	youtube-ui.l.google.com
Address: 142.250.66.78

### Actual result

➜  ~ nslookup www.youtube.com 192.168.1.1
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
*** Can't find www.youtube.com: No answer

### Additional information and/or screenshots

dns查询路径：
pc_client->AdGuardHome:53->dnsmasq:5352->sing-box:5353

**Comment by ainar-g** [comment]
`dns: overflowing header size` is an internal error of the `miekg/dns` library, and this error most likely means that `RDLENGTH` is not set correctly on the response.  Please check the responses from the upstreams.
