### ISSUE TITLE
Old local DNS Hostname (rDNS) resolved on v0.107.43 

### ISSUE THREAD

**Issue by distante** [AdguardTeam/AdGuardHome#6678]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.43 

### Action

Go to the Query Log  and see the hostnames listed

### Expected result

The first hostname resolved by the local DNS server (router) should be used.

### Actual result

If there is two entries (one old and one new) the old one is used.

### Additional information and/or screenshots

I just migrated my install from docker to an LXC container and I see this inconsistent behavior.

The rDNS names on my Fritzbox were long set (like years ago).

On my old instance of AdguardHome Version `v0.107.29` the hostnames resolve as `my-personal-hostname.fritz.box`

While on the new machine running `v0.107.43` the same device resolves as `some-random-initial-hostname.fritz.box`

After reboots of Adguard home, nothing changes in both systems. 

Querying the router resolves:

```
 nslookup 47.69.168.192 ${router-ip}
Server:		${router-ip}
Address:	${router-ip}#53

47.69.168.192.in-addr.arpa	name = my-personal-hostname.fritz.box.
47.69.168.192.in-addr.arpa	name = some-random-initial-hostname.fritz.box.
```

Querying AdguardHome IP resolves the same.

**Comment by ainar-g** [comment]
Thanks for the `nslookup` output.  From AdGuard Home's point of view, these two are the same thing, and the order of hostnames isn't really defined and does change between releases.  If you want to see consistent naming in the query logs, it's better to add that client to _Persistent clients._

**Comment by distante** [comment]
Thanks for your answer.

How about adding a feature request to add a client directly from the query log? when having an existent network with more than 100 hostnames, adding each one Adguard is not that fast or maybe even stable?

Or if you point me on the right direction I could prepare a PR for "use last known hostname" "use first known hostname" for example.

**Comment by ainar-g** [comment]
I don't think that a setting like that is necessary, but a new item in the query log entry menu that opens the _Client settings_ page with pre-filled client IP and name in a dialog does sound like a good UI improvement.  Can you please file that as a separate feature request?

**Comment by distante** [comment]
Done https://github.com/AdguardTeam/AdGuardHome/issues/6679
