### ISSUE TITLE
Add a context menu in Query Log to add a Clients to the Persisted client list

### ISSUE THREAD

**Issue by distante** [AdguardTeam/AdGuardHome#6679]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

As per https://github.com/AdguardTeam/AdGuardHome/issues/6678, the rDNS names obtained from our local routers are not stable enough and can break between release and release of Adguard, and the safe way to keep those names is to add to the Persistent Client.

Doing this requires that we manually fill every client data, even when it is already known by AdGuard

### Proposed solution

A context menu with the text "Add as Persisted client" or similar, that opens the Clients page with the prefill information of the client will make things easier and faster. Including Mac Address.

### Alternatives considered and additional information

Another alternative would be to list all the hostname entries in the log extended view if not persisted client info exists.

**Comment by distante** [comment]
I updated the feature request to include MAC Address since in the current implementation, we can just see either the current IP or the Hostname and both are not stable enough to persist.

<img width="324" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/5490201/63f31c20-bcb6-4bc5-a9c0-6221ca021e04">

**Comment by ainar-g** [comment]
@distante, if I recall correctly, MAC info isn't available directly from the query log, but maybe it will become in the future.  We'll see if we can get it done in the current API.

**Comment by ainar-g** [comment]
@distante, the latest Edge channel releases have the feature, without MAC though.  Can you please check to see if it works for you?

**Comment by distante** [comment]
thanks @ainar-g I will see how to test it after work. Do I can enable Edge channels on my running instance (and go back if needed) or should I better deploy a test instance?

**Comment by ainar-g** [comment]
Whatever is easier for you, but we recommend backing up your configuration and data either way.  You can find the links to builds on our [*Platforms* page](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms), and in general you can just replace the original binary with the new one.

**Comment by distante** [comment]
Hi @ainar-g sorry it took too long.

I have tested the latest Edge and it works as expected. Maybe I would recommend to put the existing rDNS name on the field (in case it is valid at that point) so, instead of

```
Client xxx.yyy.zzz.52
```

I would use:

```
Client MyRDNSName  xxx.yyy.zzz.52
```

One last thing. Although not related to this feature. The name shown on the `Persistent clients` list is not the same shown on `Runtime clients`

**Comment by ainar-g** [comment]
Thanks for testing!

Most other client-related improvements will become easier once we refactor some internals, which is an ongoing process.
