### ISSUE TITLE
FQDN DNS server fastest IP priority

### ISSUE THREAD

**Issue by pduchnovsky** [AdguardTeam/AdGuardHome#6687]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When using dns0 or quad9 providers it very often happens that AdGuard home instance starts using slower IP from the dns provider (For DNS queries). 
e.g. when using h3://zero.dns0.eu upstream, they work over two IPs essentially - 193.110.81.9 and 185.253.5.9
The first IP has the lowest latency and fastest response time while the second IP has slower response and much higher latency for me. 
However AdGuard begins to route requests through the second IP most of the time. 

When using h3://193.110.81.9 instead, everything is fast. 

### Proposed solution

AdGuard should be at least testing latency via ping and prioritizing the faster server IP

**Comment by fernvenue** [comment]
Have you ever tried `fastest_addr` mode as your `upstream_mode` just like [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) said?

**Comment by pduchnovsky** [comment]
@fernvenue based on my understanding that slows down response time in general since then AdGuard queries and waits for all upstream responses and tests for fastest IP for the Query (not fastest dns server) so how would that help ?

**Comment by fernvenue** [comment]
Well, if you wanna use the fastest IP, you need that, and if you wanna use the first response, than you need `all_servers` to enable parallel queries to all configured upstream servers to speed up resolving. As documentation said:

> `all_servers` (before v0.107.44): Enables parallel queries to all configured upstream servers to speed up resolving. If enabled, the queries are sent to each server simultaneously and the first response is chosen. If disabled, the queries are sent to each upstream server one-by-one and then sorted by RTT. Note that more stable upstream servers are preferred by the algorithm.

Whether you want the fastest result returned or the fastest one among all the results returned, I think these two options can fully meet your different needs.

**Comment by pduchnovsky** [comment]
@fernvenue You probably don't understand what I wrote in my initial post.
My problem is NOT adguard home returning answers from client queries.
My problem is that adguard home when querying bootstrap servers for upstream fqdn, it does not then use fastest IP returned from bootstrap servers for the upstream queries.

**Comment by fernvenue** [comment]
> My problem is that adguard home when querying bootstrap servers for upstream fqdn, it does not then use fastest IP returned from bootstrap servers for the upstream queries.

Even when you enabled `fastest_addr` mode? I thought bootstrap servers will also respect that option, at least in my tests.

**Comment by pduchnovsky** [comment]
> > My problem is that adguard home when querying bootstrap servers for upstream fqdn, it does not then use fastest IP returned from bootstrap servers for the upstream queries.
> 
> Even when you enabled `fastest_addr` mode? I thought bootstrap servers will also respect that option, at least in my tests.

I dont want to enable fastest_addr because it then slows down ALL client queries because adguard has to wait for all upstreams, then does test the speed towards response IP... my suggestion is pretty clear, adguard should use fastest_addr itself for bootstrap server queries automatically, so it then uses fastest upstream IP.
This should be decoupled from the fastest_addr setting.
I want to use parallel requests of course, for speedy responses to the clients.

**Comment by fernvenue** [comment]
Ah, things are much clearer now. I agree with you on this point, these two options should be allowed to separate :)

**Comment by Sakura-Luna** [comment]
- `parallel: Parallel queries to all configured upstream servers to speed up resolving.`

Why don't you discuss Parallel? It should return results the fastest.

**Comment by pduchnovsky** [comment]
@Sakura-Luna are you guys even reading :D

I use parallel requests, the problem is, adguard queries **BOOTSTRAP** server to **resolve zero.dns0.eu**, gets two IP's (193.110.81.9 and 185.253.5.9) and then **decides to use second slower IP** instead of using the fastest one.
