### ISSUE TITLE
admin password unrecognised 

### ISSUE THREAD

**Issue by shrifromaptsys** [AdguardTeam/AdGuardHome#6692]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

AdGuard Home

### Action

All at a sudden password for Admin is no more recognised

### Expected result

Login using existing password

### Actual result

error 403

**Comment by ainar-g** [comment]
Do you see any login attempts in the logs of your AdGuard Home?  Is the record about your login still present in the configuration file?

**Comment by overwatch3560** [comment]
@shrifromaptsys were you able to login?
