### ISSUE TITLE
Dashboard Graphs became daily instead of Hourly in v0.107.44

### ISSUE THREAD

**Issue by target123** [AdguardTeam/AdGuardHome#6712]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.107.44

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

Graphs used to contain hourly data where you can see device activity graphed every hour for the last several days.

Allowing you to see detailed patterns of usage - (e.g. sleeping / wake times, when someone is home or not)

### Actual result

Graph details in the dashboard contain less details and information compared to the previous versions. 

It used to be the case that each data point in the graph represents an hour. Now, each data point represents 1 day - making the chart less detailed. 

Hope that this change can be reverted as detailed graphs provide great insights and value to several use cases.

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/20024570/a09aa97f-9743-468d-bd9f-0d90274a2c2c)

**Comment by schzhn** [comment]
@target123, in [v0.107.44](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.44)
```
Statistics for 7 days displayed as 168 hours on the dashboard.
```
As a workaround, you can set the statistics retention interval to 167 hours on the *General settings* page.

**Comment by target123** [comment]
> @target123, in [v0.107.44](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.44)
> 
> ```
> Statistics for 7 days displayed as 168 hours on the dashboard.
> ```
> 
> As a workaround, you can set the statistics retention interval to 167 hours on the _General settings_ page.

Why not 168 Hours? Since 24*7=168?

**Comment by schzhn** [comment]
```
Fixed
 -  Statistics for 7 days displayed as 168 hours on the dashboard.
```

If the interval is 168 hours or more, statistics are displayed by day.

Related #6595

**Comment by schzhn** [comment]
On the contrary, the bug has been fixed.

**Comment by joadamou** [comment]
This hasn't been fixed, the graphs are clearly displayed in the daily format, no detailed information as it's highly summarised for the seven day period. This is a change in behaviour from all previous builds and a new issue

Image below is taken from an ARM instance

![image](https://github.com/AdguardTeam/AdGuardHome/assets/66736781/85c8bb64-abdd-4752-a94a-a42b0f4e32c2)

**Comment by ainar-g** [comment]
@schzhn, the issue here is the incorrect solution of the original issue.  The backend should send hourly data for interval ≤ 168 hours, while the UI should not use the backend units when showing the number of days/hours in the statistics cards.  See the behavior in the older releases.

**Comment by target123** [comment]
Bug seems to remain in v0.107.45

**Comment by schzhn** [comment]
Fixed in [edge](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) and upcoming beta release
