### ISSUE TITLE
Ability to be able to exclude clients from specific blocklists via filter/or otherwise

### ISSUE THREAD

**Issue by knaggsy2000** [AdguardTeam/AdGuardHome#6718]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

With the many blocklists, which can be quite intense.  Sometimes we need just to exclude a specific client from it for either testing or debugging.  But I don't see a way of doing this at this point in time.

Especially with certain smart TVs.

### Proposed solution

Let myself be able to filter the blocklist, by it's ID or something - so I can exclude a specific client from it.

**Comment by ainar-g** [comment]
This is basically #435, from what I can tell?  Once clients get custom configurations, you'll be able to remove the unnecessary lists from theirs.

**Comment by knaggsy2000** [comment]
@ainar-g My apologies, I did not spot the specified issue as you mentioned.
