### ISSUE TITLE
[Feature request] Save (keep) log view mode

### ISSUE THREAD

**Issue by alexsannikov** [AdguardTeam/AdGuardHome#672]
I almost sure people are going to the log page to check any "disabled" hits generally.
Can we somehow manage the way how we want to see the log page?
It might be:
1. Settings like "Show Disabled only/Show enabled only/Show all"
or
2. Just remember the last mode of view.
Thanks.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/845

**Comment by ameshkov** [comment]
Yup, let's keep #845 open and this merge into there
