### ISSUE TITLE
Cant Access Web Pannel From Other Devices On The Same Network

### ISSUE THREAD

**Issue by TeamTagzTikTok** [AdguardTeam/AdGuardHome#6721]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.44

### Action

I cannot go to the web pannel without going onto the server. I have tried port forwarding, using the pc's name. Changing the port.

OS: Windows Server 2022

### Expected result

I expect to get a explanation of how to fix my problem.

### Actual result

Have not gotten a result.

### Additional information and/or screenshots

WINDOWS SERVER 2022

**Comment by Jaksa101** [comment]
Where did you setup port forwarding? If on your router please delete that again. You don´t need that on the same network. 
Did you open the port in the windows firewall?

**Comment by TeamTagzTikTok** [comment]
Hello, Yes I did allow the port on the firewall.

*Frankie Try*

***@***.***

+44 7555335390

CEO Of KarmsClothing <http://karmsclothing.com/#link?=footer:email>

**Comment by Jaksa101** [comment]
Can you telnet to that server through the port? Open CMD and then type `telnet ip port`

**Comment by TeamTagzTikTok** [comment]
Unfortunately I cannot now due to the server down for maintenance. I will
give it ago when it’s back online

*Frankie Try*

***@***.***

+44 7555335390

CEO Of KarmsClothing <http://karmsclothing.com/#link?=footer:email>

**Comment by overwatch3560** [comment]
@TeamTagzTikTok were you able to telnet to the server ?

**Comment by TeamTagzTikTok** [comment]
Yes, I did.

**Comment by overwatch3560** [comment]
And did it work?

**Comment by TeamTagzTikTok** [comment]
Yes, it worked.
