### ISSUE TITLE
ENHANCE SECURITY for AdGuardHome

### ISSUE THREAD

**Issue by Shintaromardux** [AdguardTeam/AdGuardHome#6722]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

At the moment, my AdGuardHome works just fine. the only problem here, there's too many outsiders IPs that appears on my AdGuardHome 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/51293060/f394d748-ff0c-4286-acd7-efab7f2a052e)

I setup my AGH on my own CentOS server. 

### Proposed solution

How can i remove the outsiders IPs access my AGH? If there's any solution, please tell me.

**Comment by bundyland** [comment]
You need to set up client-ids like mentioned here:

https://github.com/AdguardTeam/AdGuardHome/wiki/Clients#clientid

**Comment by ainar-g** [comment]
See https://github.com/AdguardTeam/KnowledgeBaseDNS/blob/7d7eb1305262a6e9890d2d64be2918cc50ab31ba/docs/adguard-home/running-securely.md, which should soon be published to the DNS Knowledge Base.

**Comment by Shintaromardux** [comment]
For example, my wifi named is "WLAN HOME", and i want that all devices connected to my wifi can have access to AdGuardHome. The others can not, how can i do that?
