### ISSUE TITLE
0.107.44 broke DoT

### ISSUE THREAD

**Issue by boardlord1** [AdguardTeam/AdGuardHome#6723]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

0.107.44

### Action

I've been using AGH for a long time as an addon in HAOS on an rPI4.
I've set up DHCP on my OWRT router to direct all clients to use AGH as the resolver (using DoT with cloudflare and quad9), and in AGH I direct local requests to dnsmasq on my router.  

### Expected result

Just like for the past couple of years, to work as it should.

### Actual result

Since upgrading to 0.107.44, DoT has become very flaky. I noticed that name resolving stops working from all clients at random times, for a random length of time. Restarting the addon fixes the issue until it crops up again. 

I've noticed message like these in the logs (while in this snippet there's only quadn9's address, it happens with cloudflare as well.

```
2024/02/10 13:39:57.901787 [error] dnsproxy: upstream tls://dns.quad9.net:853 failed to exchange ;mobile-data.onetrust.io.	IN	 A in 806.934µs: getting conn to tls://dns.quad9.net:853: connecting to dns.quad9.net: dial tcp [2620:fe::9]:853: connect: network is unreachable
dial tcp [2620:fe::fe]:853: connect: network is unreachable
2024/02/10 13:43:28.883745 [error] dnsproxy: upstream tls://dns.quad9.net:853 failed to exchange ;graph.facebook.com.	IN	 A in 1.423221ms: getting conn to tls://dns.quad9.net:853: connecting to dns.quad9.net: dial tcp [2620:fe::9]:853: connect: network is unreachable
dial tcp [2620:fe::fe]:853: connect: network is unreachable
2024/02/10 13:44:11.147678 [error] dnsproxy: upstream tls://dns.quad9.net:853 failed to exchange ;i4.gtm.eset.com.	IN	 A in 835.192µs: getting conn to tls://dns.quad9.net:853: connecting to dns.quad9.net: dial tcp [2620:fe::9]:853: connect: network is unreachable
dial tcp [2620:fe::fe]:853: connect: network is unreachable
2024/02/10 13:44:47.581381 [error] dnsproxy: upstream tls://dns.quad9.net:853 failed to exchange ;api.cloudflare.com.	IN	 A in 692.639µs: getting conn to tls://dns.quad9.net:853: connecting to dns.quad9.net: dial tcp [2620:fe::9]:853: connect: network is unreachable
dial tcp [2620:fe::fe]:853: connect: network is unreachable
2024/02/10 13:45:11.561544 [error] dnsproxy: upstream tls://dns.quad9.net:853 failed to exchange ;i3.gtm.eset.com.	IN	 A in 725.304µs: getting conn to tls://dns.quad9.net:853: connecting to dns.quad9.net: dial tcp [2620:fe::9]:853: connect: network is unreachable
dial tcp [2620:fe::fe]:853: connect: network is unreachable
2024/02/10 13:45:51.059642 [error] dnsproxy: upstream tls://dns.quad9.net:853 failed to exchange ;ocsp.entrust.net.	IN	 A in 592.417µs: getting conn to tls://dns.quad9.net:853: connecting to dns.quad9.net: dial tcp [2620:fe::9]:853: connect: network is unreachable
dial tcp [2620:fe::fe]:853: connect: network is unreachable
```

I tested plain DNS and DoH and both works uninterrupted, only when I use DoT resolvers do I see this issue.

**Comment by steve28** [comment]
I am seeing this as well:
```
2024/02/10 10:43:18.477035 [error] dnsproxy: upstream tls://1dot1dot1dot1.cloudflare-dns.com:853 failed to exchange ;17-courier.push.apple.com.	IN	 HTTPS in 213.582µs: getting conn to tls://1dot1dot1dot1.cloudflare-dns.com:853: connecting to 1dot1dot1dot1.cloudflare-dns.com: dial tcp [2606:4700:4700::1001]
:853: connect: network is unreachable
dial tcp [2606:4700:4700::1111]:853: connect: network is unreachable
2024/02/10 10:43:18.478251 [error] dnsproxy: upstream tls://1dot1dot1dot1.cloudflare-dns.com:853 failed to exchange ;17-courier.push.apple.com.	IN	 A in 150.652µs: getting conn to tls://1dot1dot1dot1.cloudflare-dns.com:853: connecting to 1dot1dot1dot1.cloudflare-dns.com: dial tcp [2606:4700:4700::1001]:853
: connect: network is unreachable
dial tcp [2606:4700:4700::1111]:853: connect: network is unreachable
2024/02/10 10:43:18.737234 [error] dnsproxy: upstream tls://1dot1dot1dot1.cloudflare-dns.com:853 failed to exchange ;fmfmobile.fe2.apple-dns.net.	IN	 A in 197.015µs: getting conn to tls://1dot1dot1dot1.cloudflare-dns.com:853: connecting to 1dot1dot1dot1.cloudflare-dns.com: dial tcp [2606:4700:4700::1
001]:853: connect: network is unreachable
dial tcp [2606:4700:4700::1111]:853: connect: network is unreachable
2024/02/10 10:43:25.284583 [error] dnsproxy: upstream tls://1dot1dot1dot1.cloudflare-dns.com:853 failed to exchange ;bookkeeper.itunes.apple.com.	IN	 A in 204.573µs: getting conn to tls://1dot1dot1dot1.cloudflare-dns.com:853: connecting to 1dot1dot1dot1.cloudflare-dns.com: dial tcp [2606:4700:4700::1
001]:853: connect: network is unreachable
dial tcp [2606:4700:4700::1111]:853: connect: network is unreachable
```
I do notice that it's trying an IPv6 address [2620:fe::fe] but I do not have IPv6 on my network.  Maybe a clue?

**Comment by iluvatyr** [comment]
can confirm

**Comment by TChilderhose** [comment]
Observing the same thing as well with DoT. DoH has been working fine

**Comment by mesacarlos** [comment]
Same here. AdGuard Home randomly stops resolving DNS over TLS.
Logs show that AdGuard is trying to connect to upstream DNS (Google/Quad1) using IPv6 in a machine with no IPv6.

**Comment by mesacarlos** [comment]
Found a duplicate already in the current milestone: https://github.com/AdguardTeam/AdGuardHome/issues/4354

**Comment by EugeneOne1** [comment]
@boardlord1, hello and thanks for the report.  The errors in the log may sign that the the `dns.quad9.net` upstream has been bootstrapped into the only IPv6 address.  Could you please collect a [verbose log](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) for us?  You may send it to devteam@adguard.com.

Also, do you have the `dns.bootstrap_prefer_ipv6` configuration field set to `false`?

**Comment by boardlord1** [comment]
@EugeneOne1 The snippet I've shared indeed only showed quad9, but there were identical entries for cloudflare as well.

And yes,  `dns.bootstrap_prefer_ipv6` is set to `false`

Log file is on it's way to [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by MichaelAndoid** [comment]
Same problema after update to v.0.107.44 i have random problems resolving DNS requests with DOT.

`
2024/02/16 08:25:34.160783 [error] dnsproxy: upstream tls://unfiltered.adguard-dns.com:853 failed to exchange ;mail.google.com. IN  HTTPS in 8.739224ms: dialing tls://unfiltered.adguard-dns.com:853: connecting to unfiltered.adguard-dns.com: dial tcp [2a10:50c0::1:ff]:853: socket: address family not supported by protocol
dial tcp [2a10:50c0::2:ff]:853: socket: address family not supported by protocol

2024/02/16 07:35:27.650641 [error] dnsproxy: upstream tls://1dot1dot1dot1.cloudflare-dns.com:853 failed to exchange ;edge-consumer-static.azureedge.net. IN  HTTPS in 5.821702ms: getting conn to tls://1dot1dot1dot1.cloudflare-dns.com:853: connecting to 1dot1dot1dot1.cloudflare-dns.com: dial tcp [2606:4700:4700::1001]:853: socket: address family not supported by protocol
dial tcp [2606:4700:4700::1111]:853: socket: address family not supported by protocol

`

**Comment by MichaelAndoid** [comment]
Hi changed from DOT(tls://) to HTTPS:// let's see iff temporary resolve before the new version.

**Comment by Haravikk** [comment]
I'm another seeing this problem with DoT (Cloudflare), hopefully switching to DoH solves it for me for now.

**Comment by Shiwigy** [comment]
**Platform (OS and CPU architecture)**
Linux (Debian 11.9), amd64

**Installation**
Docker
adguard/adguardhome         latest     20888152689b

**Version**
v0.107.44

I have the exact same problem since update, see logs from docker below

**Log output**
dial tcp [2001:4860:4860::8888]:853: connect: network is unreachable
2024/02/18 11:58:11.643067 [error] dnsproxy: upstream tls://dns.google:853 failed to exchange ;<redacted>  IN       SRV in 205.995µs: getting conn to tls://dns.google:853: connecting to dns.google: dial tcp [2001:4860:4860::8844]:853: connect: network is unreachable
dial tcp [2001:4860:4860::8888]:853: connect: network is unreachable

**Settings**
bootstrap_prefer_ipv6: false
blocking_ipv6: ""

**Comment by EugeneOne1** [comment]
@boardlord1, hello again.  We've pushed the `edge` build which includes a fix for this issue.  Could you please check if the DNS-over-TLS upstreams are working better now?

**Comment by boardlord1** [comment]
Apologies, I won't be able to test as I don't have a spare pi4, and home assistant addon repo doesn't provide an edge build (and I need internet access, don't want to reconfigure my whole dns resolution config).
