### ISSUE TITLE
Cant connect to interface while DNS is connected on Android

### ISSUE THREAD

**Issue by GammaPotato** [AdguardTeam/AdGuardHome#6735]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, ARM64

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.44

### Action

Since the New update im not able to connect to Adguard webpage on android and all other external devices while they are Connected to the AdGuard DNS. Tried Restared Server, Restarted AgGuard and reinstalling Ad Guard

 Im Running AdGuard Home onna Windows Server 2019 64 Bit.

Prove Video here (File to big for Github):
https://mega.nz/file/WkZT3TJJ#2bccms_8V4Di3sWTq9Qsrql3eH5qBBYfkczDVy3D1Yw

### Expected result

That all works fine again

### Actual result

Nothing, Same issue that before

**Comment by fernvenue** [comment]
Seems you blocked yourself:

```
~$ dig A @privatnas.servebeer.com +https privatnas.servebeer.com +short
0.0.0.0
```

So nothing wrong with AdGuardHome.

**Comment by GammaPotato** [comment]
I checked the entire blocklist. Nothing with blocked found. Added it in to unblock and now it works. Idk what happend. Its working now. Thanks

**Comment by fernvenue** [comment]
> I checked the entire blocklist. Nothing with blocked found.

Go *Filters - Custom filtering rules - Check the filtering* and test your domain to see what's going on.
