### ISSUE TITLE
[Question]  Parallel queries with 2 DOT upstreams

### ISSUE THREAD

**Issue by gurgun-dayioglu** [AdguardTeam/AdGuardHome#674]
Will enabling parallel queries speed up 2 dns over tls upstreams.

Maybe an easy one but wondering if being over tls would have a negative impact on it.

Plus what is the default behavior when parallel queries is not selected with multiple upstreams...

**Comment by ameshkov** [comment]
> Maybe an easy one but wondering if being over tls would have a negative impact on it.

Well, it will require a little bit more CPU, but other than that nothing negative.

> Plus what is the default behavior when parallel queries is not selected with multiple upstreams...

It will query upstreams one by one starting from the fastest one.
