### ISSUE TITLE
Keep Losing the Connection?

### ISSUE THREAD

**Issue by Haravikk** [AdguardTeam/AdGuardHome#6745]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.44

### Action

Making DNS requests.

### Expected result

AdGuard Home should be able to make outgoing connections as long as my network/system is able to do so.

### Actual result

Periodically, maybe 3-4 times a day, AdGuard Home just loses its ability to make outgoing connections for no apparent reason. I can still connect to the UI, at which point I'll usually see it complaining that it can't check for updates, which is how I know it's lost the ability to make **any** outgoing connections, not just DNS requests.

If I disable protection, then reenable it, the problem is fixed until it happens again. I've not been able to determine any specific trigger other than making a new DNS request.

### Additional information and/or screenshots

Unfortunately I don't remember what version I upgraded from, so I don't know when exactly this issue first started occurring (could have been another version between the old one and latest that started it), all I know is that it's happening in v0.107.44.

It's annoying, as I usually never have any problems with AdGuard Home, which is why I usually only update sporadically as it's so invisible that I forget.

**Comment by MichaelAndoid** [comment]
This is after update?

Do you already check this?
https://github.com/AdguardTeam/AdGuardHome/issues/6723

What is the log in AdguardHome.err?

**Comment by Haravikk** [comment]
Looks like the same issue, I was using DoT as well so hopefully DoH resolves this for now. I'll close this issue since it appears to be a duplicate.
