### ISSUE TITLE
Query Log won't update, not even manually

### ISSUE THREAD

**Issue by Pre-Venti** [AdguardTeam/AdGuardHome#6747]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, 32-bit Intel (aka 386)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.44

### Action

Updating Query Log in the Webinterface

### Expected result

Get the latest DNS Queries and blocked DNS Queries

### Actual result

No new queries are added, nothing happens, no refresh

### Additional information and/or screenshots

Very often, when I try to update the Query Log, because a website is not working correctly and I need to look up wheter it's blocked or not, it just wont update. Right now, I can only see the last blocked DNS from over 24h ago, and apparently only a few requests for the whole day, which can't be true. This is also not always the case when tested at the same time on different devices, where one device gets the update, while the other one doesn't. This is especially true for mobile devices (Laptop, Phone, etc.).
<img width="971" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/157218045/8bb8e1cf-7f22-42f9-a641-53209e70225d">
<img width="996" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/157218045/8db75c10-286c-4454-a610-274182a284da">

**Comment by tiobane** [comment]
Hi,

adding to that:

Platform (OS and CPU architecture)
Unraid 6.12.8, x86 64 bit (intel j5005)

Installation
Docker

Setup
DHCP handled by FritzBox 7590ax, IPv4 + IPv6

AdGuard Home version
v0.107.44

Action
Updating Query Log in the Webinterface, Updating statistics in overview

Expected result
Get any entries

Actual result
No new queries are added, nothing happens, no refresh

Additional information and/or screenshots:

Worked perfectly, until I had to change my IP range for a test.
After returning it to the former, no new statistics, querys etc. were added.
Tried deactivating/reactivating statistics, uninstalled, deleted the adguard folder completely, fresh installation of the docker, ran the setup again.
Adguard seems to work but it doesn't show.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/12412657/3940eda7-c8b2-40ee-a825-6ce7321bb8e6)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/12412657/d28b312a-c661-4e13-8e5b-19732d38f75d)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/12412657/7699c9b4-ecea-408f-afc7-7a71bf1a4e65)


Found that error in the log:
[error] querylog: closing: flushing log buffer: nothing to write to a file



context:


2024/02/21 16:20:41.758819 [info] AdGuard Home, version v0.107.44
2024/02/21 16:20:41.763056 [info] tls: using default ciphers
2024/02/21 16:20:41.765640 [info] safesearch default: disabled
2024/02/21 16:20:41.773219 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2024/02/21 16:20:41.773971 [info] auth: initialized.  users:1  sessions:1
2024/02/21 16:20:41.773989 [info] AdGuard Home updates are disabled
2024/02/21 16:20:41.773997 [info] web: initializing
2024/02/21 16:20:42.970038 [info] dnsproxy: cache: enabled, size 4096 b
2024/02/21 16:20:42.970064 [info] dnsproxy: max goroutines is set to 300
2024/02/21 16:20:42.970526 [info] dnsproxy: cache: disabled
2024/02/21 16:20:42.970859 [info] AdGuard Home is available at the following addresses:
2024/02/21 16:20:42.970930 [info] clients: processing addresses
2024/02/21 16:20:42.971351 [info] go to http://127.0.0.1:3000
2024/02/21 16:20:42.971366 [info] go to http://[::1]:3000
2024/02/21 16:20:42.971377 [info] go to http://192.168.178.2:3000
2024/02/21 16:20:42.971388 [info] go to http://[fd00::70b5:e800:8ad:75e6]:3000
2024/02/21 16:20:42.971399 [info] go to http://[2a01:c23:741b:7400:70b5:e800:8ad:75e6]:3000
2024/02/21 16:20:42.971411 [info] go to http://[fd00::2]:3000
2024/02/21 16:20:42.971422 [info] go to http://[fe80::70b5:e800:8ad:75e6%eth0]:3000
2024/02/21 16:20:48.594336 [info] dnsproxy: starting dns proxy server
2024/02/21 16:20:48.594421 [info] Ratelimit is enabled and set to 20 rps, IPv4 subnet mask len 24, IPv6 subnet mask len 56
2024/02/21 16:20:48.594431 [info] The server is configured to refuse ANY requests
2024/02/21 16:20:48.594441 [info] dnsproxy: cache: enabled, size 4194304 b
2024/02/21 16:20:48.594457 [info] dnsproxy: max goroutines is set to 300
2024/02/21 16:20:48.594479 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2024/02/21 16:20:48.594654 [info] dnsproxy: listening to udp://[::]:53
2024/02/21 16:20:48.594671 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2024/02/21 16:20:48.594735 [info] dnsproxy: listening to tcp://[::]:53
2024/02/21 16:20:48.594903 [info] dnsproxy: entering udp listener loop on [::]:53
2024/02/21 16:20:48.595116 [info] dnsproxy: entering tcp listener loop on [::]:53
2024/02/21 16:21:31.236472 [info] dnsforward: starting reconfiguring server
2024/02/21 16:21:31.236490 [info] dnsproxy: stopping dns proxy server
2024/02/21 16:21:31.236632 [info] dnsproxy: stopped dns proxy server
2024/02/21 16:21:31.337431 [info] dnsproxy: cache: enabled, size 4096 b
2024/02/21 16:21:31.337487 [info] dnsproxy: max goroutines is set to 300
2024/02/21 16:21:31.338274 [info] dnsproxy: cache: disabled
2024/02/21 16:21:31.340802 [info] dnsproxy: starting dns proxy server
2024/02/21 16:21:31.340878 [info] The server is configured to refuse ANY requests
2024/02/21 16:21:31.340892 [info] dnsproxy: cache: enabled, size 4194304 b
2024/02/21 16:21:31.340905 [info] dnsproxy: max goroutines is set to 300
2024/02/21 16:21:31.340925 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2024/02/21 16:21:31.341124 [info] dnsproxy: listening to udp://[::]:53
2024/02/21 16:21:31.341140 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2024/02/21 16:21:31.341183 [info] clients: processing addresses
2024/02/21 16:21:31.341221 [info] dnsproxy: listening to tcp://[::]:53
2024/02/21 16:21:31.341240 [info] dnsforward: finished reconfiguring server
2024/02/21 16:21:31.341379 [info] dnsproxy: entering udp listener loop on [::]:53
2024/02/21 16:21:31.341400 [info] dnsproxy: entering tcp listener loop on [::]:53
2024/02/21 16:21:43.020764 [info] Received signal "terminated"
2024/02/21 16:21:43.020786 [info] stopping AdGuard Home
2024/02/21 16:21:43.020794 [info] stopping http server...
2024/02/21 16:21:43.021119 [info] stopped http server
2024/02/21 16:21:43.021446 [info] dnsproxy: stopping dns proxy server
2024/02/21 16:21:43.021534 [info] dnsproxy: stopped dns proxy server
2024/02/21 16:21:43.026666 [error] querylog: closing: flushing log buffer: nothing to write to a file
2024/02/21 16:21:43.027024 [info] stopped
2024/02/21 16:21:43.380820 [info] AdGuard Home, version v0.107.44
2024/02/21 16:21:43.384810 [info] tls: using default ciphers
2024/02/21 16:21:43.388037 [info] safesearch default: disabled
2024/02/21 16:21:43.394568 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2024/02/21 16:21:43.395297 [info] auth: initialized.  users:1  sessions:1
2024/02/21 16:21:43.395447 [info] AdGuard Home updates are disabled
2024/02/21 16:21:43.395557 [info] web: initializing
2024/02/21 16:21:44.589715 [info] dnsproxy: cache: enabled, size 4096 b
2024/02/21 16:21:44.589738 [info] dnsproxy: max goroutines is set to 300
2024/02/21 16:21:44.590154 [info] dnsproxy: cache: disabled
2024/02/21 16:21:44.590555 [info] AdGuard Home is available at the following addresses:
2024/02/21 16:21:44.590653 [info] clients: processing addresses
2024/02/21 16:21:44.591007 [info] go to http://127.0.0.1:3000
2024/02/21 16:21:44.591029 [info] go to http://[::1]:3000
2024/02/21 16:21:44.591042 [info] go to http://192.168.178.2:3000
2024/02/21 16:21:44.591056 [info] go to http://[fd00::2]:3000
2024/02/21 16:21:44.591070 [info] go to http://[fe80::70b5:e800:9ad:75e6%eth0]:3000
2024/02/21 16:21:50.221293 [info] dnsproxy: starting dns proxy server
2024/02/21 16:21:50.221333 [info] The server is configured to refuse ANY requests
2024/02/21 16:21:50.221343 [info] dnsproxy: cache: enabled, size 4194304 b
2024/02/21 16:21:50.221357 [info] dnsproxy: max goroutines is set to 300
2024/02/21 16:21:50.221376 [info] dnsproxy: creating udp server socket 0.0.0.0:53
2024/02/21 16:21:50.221515 [info] dnsproxy: listening to udp://[::]:53
2024/02/21 16:21:50.221532 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
2024/02/21 16:21:50.221598 [info] dnsproxy: listening to tcp://[::]:53
2024/02/21 16:21:50.221711 [info] dnsproxy: entering udp listener loop on [::]:53
2024/02/21 16:21:50.221781 [info] dnsproxy: entering tcp listener loop on [::]:53

**Comment by AlphaInfamous** [comment]
something happening on Latest install of AdGuard Home
<img width="1267" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/29665623/f4c5904c-7203-4a50-9592-99e3e0f81372">

nothing gets updated, only a handful of Queries got logged
<img width="1234" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/29665623/c7a82ebf-63a0-44d6-930e-e56dab6fe58b">

Version: v0.107.48
OS: Debian
 DHCP handled by router , DNS pointed to Adguard installation

**Comment by AlphaInfamous** [comment]
its resolved, sometime ago Unifi added ad blocking need to turn it off for getting adguard to work
