### ISSUE TITLE
Add "lockout period" after username and password entered incorrectly a number of times.

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#675]
Possibility of adding enhancement to lockout the web interface for a period of time after username and password has been incorrectly entered a number of times?

**Comment by ameshkov** [comment]
Lock just for this client IP or globally?

**Comment by CWo42** [comment]
i would block for 5min after 10 attempts on IP Lvl

**Comment by adrianh-za** [comment]
> Lock just for this client IP, username, or globally?

Not sure to be honest.  I guess as a first phase, globally would be easiest.  Maybe per IP can be a phase 2 approach?

**Comment by ArchiveBase** [comment]
_If you loved to see failed attempts history with timestamp/ IP, follow https://github.com/AdguardTeam/AdGuardHome/issues/1006_ 😉

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2826
