### ISSUE TITLE
没有正确监听全部IPV6地址 \ Not properly listening to all IPv6 addresses.

### ISSUE THREAD

**Issue by cuiplay** [AdguardTeam/AdGuardHome#6754]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.44

### Action

PC1 has 2 IPv4 addresses and 6 IPv6 addresses, as shown in the figure

![微信截图_20240221223250](https://github.com/AdguardTeam/AdGuardHome/assets/2078438/39448361-fb9c-4b3f-a237-a47bfa29af47)

### Expected result

All are valid

### Actual result

During validation, PC2 has 6 IPv6 addresses, of which only 1 is valid; the other 5 IPv6 addresses are invalid.
![QQ图片20240221223119](https://github.com/AdguardTeam/AdGuardHome/assets/2078438/8d72c788-7b1a-4aaf-a832-c02705e6f356)
![QQ截图20240221225128](https://github.com/AdguardTeam/AdGuardHome/assets/2078438/00fc85ac-4c20-4121-ab8e-b49cffa107bf)

### Additional information and/or screenshots

![QQ截图20240221225335](https://github.com/AdguardTeam/AdGuardHome/assets/2078438/a0635b6c-9ce4-47c8-a7a6-5d8130c42e49)
Listening to all addresses, firewall is turned off.

**Comment by ainar-g** [comment]
Thanks for the thorough report.  As the logs show, the addresses seem unreachable.  Please use `nslookup` on PC2 first to see if it has access to these addresses on PC1.  For example:

```ps1
nslookup -debug 'www.example.com' '240e:345:270:8f01::2d5'
```

If this command fails then PC1 is not accessible and there is something somewhere preventing it from access.

**Comment by ainar-g** [comment]
As the timeout shows, those addresses are not reachable.  The fact that the web interface is reachable doesn't really matter, as the web interface uses a different port.  Please inspect your network configuration and make sure that port 53 is open and isn't blocked for these addresses on any stage.
