### ISSUE TITLE
Something is wrong when installing or updating filters causing crashes and 100% CPU usage

### ISSUE THREAD

**Issue by searayeah** [AdguardTeam/AdGuardHome#6756]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

AdGuard Home v0.107.44

### Action

I perform a setup AdGuard Home on Debian DigitalOcean (6 dollar/mo) server using your website [guide](https://adguard.com/en/blog/adguard-home-on-public-server.html) (I just do basic setup, without domain name and DoH). The exact commands after creating a fresh Debian12 x64 25 GB SSD 1 GB RAM droplet are

```shell
apt update
apt install curl
apt install dnsutils
curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v
```

After installing I also execute instructions 1-4 to fix 53 port issue according to this [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#bindinuse), as I'm getting an error at the beginning of UI setup (seems common).

So, everything seems to work fine after these setup steps. The issue comes when touching filterlists. I recreated droplet several times with the same steps described above and every time there was some random lags and crashes when adding filterlists.

On first installation I just enabled almost all __filterlists provided by default__ in UI (20-40 lists without regional ones). When adguard was downloading them the UI lagged and stopped responding, I refreshed the page and it said "Restarting Adguard...". The restart was too long and the CPU usage was like 100%. The droplet didn't respond.

On second installation I was enabling 5 filters at a time. Everything was downloading and enabling fine, until the last 5, when it lagged again similarly to the first time. I waited quite some time for it to restart and noticed that the dashboard stats (dns queries, blocked quries) were reset.

On third installation, I was adding filterlists one by one and it finally worked without crashes. I set the droplet's IP as DNS server in my router DCHP settings and everything worked perfectly for 24 hours (filterlists blocking worked, processing time was fast). It seems that there was a filter update after 24 hours since the installation and the server lagged again. The UI lagged and didn't respond for almost 15 minutes, the dashboard stats were reset again, and while it was lagging no DNS queires were processed, so my internet stopped working. I attach the screenshots of droplet's metrics. You can see 100% CPU usage for like 20 minutes. After this 'update', everything works as intended.

### Expected result

Adding or updating filterlists should not crash the entire app.

### Actual result

There is some sort of bug or memory leak connected to filterlists. I just pressed `check for updates` button in UI and it took like 3 seconds to update all the lists. I do not understand why the crashes are happening. It is so random.

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/57370975/fb338829-4e1a-47ff-9c1a-b1811154900f)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/57370975/33ba33a3-1fa7-471b-8959-2f344965ea20)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/57370975/84d51331-f2e7-4186-93b7-1d4aa7295ec9)

**Comment by ainar-g** [comment]
Hello and thanks for the thorough report.  I don't think that this is a bug or a leak, as rebuilding the filtering engine is an expensive operation, and enabling all filters is not the intended use.  Especially with 1 GiB of RAM.  There aren't any precise recommended specs, but in general the more rules one uses, the more RAM and CPU they need, and a couple of generic lists along with one or two regional filters should generally be enough.
