### ISSUE TITLE
No Tab Icon in Safari - Adguard behind Authentik and Reverse Nginx Proxmox Manager

### ISSUE THREAD

**Issue by ramsnerm** [AdguardTeam/AdGuardHome#6757]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.44

### Action

Adguard is setup in the Docker Container and uses macVLAN to be accessable. It is behind a Nginx Proxy Manger and for Security Reason the access control is setup with Authentik (proxy headers). The Installation works so far fine and as expected except the presentation of the Adguard  Logo

### Expected result

To See the correct logo.

![CleanShot 2024-02-22 at 11 14 31](https://github.com/AdguardTeam/AdGuardHome/assets/19633012/e7efdffd-a6fe-4d8b-b380-baf0748bbedf)

### Actual result

No Logo

![CleanShot 2024-02-22 at 11 10 29](https://github.com/AdguardTeam/AdGuardHome/assets/19633012/cc754302-6ed4-4c5d-94a3-ddbb8c968a49)

### Additional information and/or screenshots

**OS and Software Version**
Used OS Image in Docker: Alpine Linux 3.18.6
MacOS Version: Sonoma 14.2.1
Safari Version: Version 17.2.1 (19617.1.17.11.12)

**My Workaround**
To sollte the issue for me I added the following NGINX directive:
```
location /assets/safari-pinned-tab.svg {
    proxy_pass http://192.xxx.xxx.xx/assets/safari-pinned-tab.svg;
}
```

**Comment by ainar-g** [comment]
Thanks for the thorough report.  It is likely that there is an issue with the system, since AdGuard Home doesn't really perform any sort of custom handling of that file.  Perhaps one of the things in the system overriding the `/assets/` path for itself?

**Comment by ramsnerm** [comment]
Sorry bothering you about. You might been right although I was not able to find it yet. This kind of "malfunction" is only with the Mac Safari. Using Chrome everything is fine.
