### ISSUE TITLE
AGH script on uninstall doesn't remove all of its files

### ISSUE THREAD

**Issue by knaggsy2000** [AdguardTeam/AdGuardHome#6761]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Edge

### Action

When testing different versions of AGH, I noticed upon uninstall and the install of the new version - that it errors out with: -

```
installation failed, removing /opt/AdGuardHome
cannot install AdGuardHome as a service
```

That's because the AGH script didn't remove the init.d script.  So had to issue: -

`# rm /usr/local/etc/rc.d/AdGuardHome`

Then after last issue the install again and it goes fine.

### Expected result

I expect the uninstall to remove any file it had installed previously

### Actual result

Error mentioned above

**Comment by knaggsy2000** [comment]
This further extends to how the "uninstall" script works, as it just wipes out the installation directory without ANY regard to the files/folders currently installed - that's NOT good practice, especially with BSD-based OS'es.

**Comment by knaggsy2000** [comment]
That's the thing with BSD-based OS'es - they ALL have strict directories for events (and more).  But with every Linux OS - nope, it seems to be free-rain, there isn't a standard at all.  This is one on the reasons I've settled on a BSD system.

**Comment by knaggsy2000** [comment]
@ainar-g @EugeneOne1 This issue isn't about the reference "symbolic links" issue mentioned earlier (please remove that).  Just a simple issue with the script used for uninstalling.

**Comment by knaggsy2000** [comment]
@ainar-g @EugeneOne1 And update on this issue?

**Comment by knaggsy2000** [comment]
@ainar-g Any update on this issue?

**Comment by EugeneOne1** [comment]
@knaggsy2000, hello and apologies for the late reply.  Do you still experience this?  Unfortunately we can't reproduce the issue, the service file is successfully removed on our machines.

Could you please collect a [verbose log](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) recorded while performing the "uninstall" action?  You may send it to our devteam@adguard.com.

**Comment by knaggsy2000** [comment]
@EugeneOne1 I would need to re-test this when I can, but yes - close the issue until further notice.
