### ISSUE TITLE
Stuck on "Initializing auth module" on setup

### ISSUE THREAD

**Issue by orimandel** [AdguardTeam/AdGuardHome#6764]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.44

### Action

```sh
2024/02/23 15:48:19.578544 [info] AdGuard Home, version v0.107.44
2024/02/23 15:48:19.578643 [info] This is the first time AdGuard Home is launched
2024/02/23 15:48:19.578650 [info] Checking if AdGuard Home has necessary permissions
2024/02/23 15:48:19.578783 [info] AdGuard Home can bind to port 53
2024/02/23 15:48:19.579206 [info] safesearch default: disabled
2024/02/23 15:48:19.579246 [info] Initializing auth module: /Applications/AdGuardHome/data/sessions.db
```

### Expected result

Finish setup

### Actual result

Process is stuck on this step for a long time, without change. Tried again and same thing happens.

### Additional information and/or screenshots

Running on MacOS 14.3 Beta

**Comment by tjharman** [comment]
Another user reported this issue on windows, they had [OneDrive getting in the way](https://github.com/AdguardTeam/AdGuardHome/issues/6688).  Are you trying to install it somewhere there's a synced drive or similar involved?  I realise you're on MacOS so it's probably a different issue, but worth looking at maybe?
