### ISSUE TITLE
Persistent clients name in dashboards and logs

### ISSUE THREAD

**Issue by nathannogueira** [AdguardTeam/AdGuardHome#6765]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Showing the IP on panels and logs is not always intuitive to find out which device it belongs to, so it would be viable if it were possible to use a nickname or name to display it.

### Proposed solution

Show the name of the client configured in Persistent clients so that it appears in the Statistics Dashboard and in the Query Log instead of the IP

**Comment by nathannogueira** [comment]
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30486860/1e32aa8b-a621-42f3-ba34-3a4ae3587334)

**Comment by nathannogueira** [comment]
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30486860/b5bb69dc-2bcd-4d16-8216-39ba0a3d1527)

**Comment by whyisthisbroken** [comment]
You can add the Hostnames to etc/hosts

So AGH read it and show you the names... 
Works flawless.

Also you can simply add names in the Client Settings or got them from rDNS if configured in the router...
