### ISSUE TITLE
h3 doh not working as fallback server

### ISSUE THREAD

**Issue by hisel-sabermetrics** [AdguardTeam/AdGuardHome#6766]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.44

### Action

1. Add a DoH server to upstream with forced http/3
2. Test upstreams to check that it is working
3. Move DoH server to fallback
4. Test upstreams to check that it is working

### Expected result

Test upstream shows the same result

### Actual result

Forced http/3 works in upstream but not fallback

**Comment by overwatch3560** [comment]
Have you got any screenshots when adding the doh server what exactly happens @hisel-sabermetrics
