### ISSUE TITLE
配置好了进后台看一切都是正常的但是广告仍然在

### ISSUE THREAD

**Issue by cdwmhcc** [AdguardTeam/AdGuardHome#677]
把AdGuardHome安装到了AC86U路由器中了，进入后台查看都是正常的，拦截器也开启了，但是我打开google，youtube，baidu等网站还是有广告，广告拦截没有起作用。

**Comment by ameshkov** [comment]
Hi! For hiding Google ads it is necessary to support cosmetic filters. This is not possible on the DNS-level, unfortunately.

On the other hand, we're planning to implement an HTTP proxy eventually, then it will become possible.

**Comment by cdwmhcc** [comment]
> Hi! For hiding Google ads it is necessary to support cosmetic filters. This is not possible on the DNS-level, unfortunately.
> 
> On the other hand, we're planning to implement an HTTP proxy eventually, then it will become possible.

Thanks.
The official website says that AdGuard Home can filter advertisements comprehensively. You said that it can't filter advertisements. So what's the function of AdGuard Home?

**Comment by cdwmhcc** [comment]
[https://drive.google.com/file/d/1lYQ6cOP7RtiwiNakdJ23dZ9ihTTYvkWO/view?usp=sharing](url)

I purchased a license for AdGuard, but I don't want to use the desktop version of the filter, I need a filter used in the router, all devices can filter ads after installation.

Can AdGuardHome meet this need?

**Comment by ameshkov** [comment]
@cdwmhcc 

AdGuard Home can block ad servers, and it does that pretty well.

But it is not as good as the desktop programs. Please mind, that AdGuard Home is a relatively new product. It will evolve eventually.

**Comment by cdwmhcc** [comment]
> @cdwmhcc
> 
> AdGuard Home can block ad servers, and it does that pretty well.
> 
> But it is not as good as the desktop programs. Please mind, that AdGuard Home is a relatively new product. It will evolve eventually.


You didn't understand what I said.

I want to ask AdGuard how to set up to filter ads, now it works, but can't filter any ads.

One more thing, I set a ban on accessing google.com in the background prohibition custom rules, but the device can still access google, why?

Thanks！

**Comment by ameshkov** [comment]
> I want to ask AdGuard how to set up to filter ads, now it works, but can't filter any ads.

Have you configured your devices to use AdGuard Home as a DNS server?

**Comment by cdwmhcc** [comment]
> > I want to ask AdGuard how to set up to filter ads, now it works, but can't filter any ads.
> 
> Have you configured your devices to use AdGuard Home as a DNS server?

 I have set the DNS of my router to DNS 192.168.50.1 in the AdGuard Home Wizard

**Comment by cdwmhcc** [comment]
> > I want to ask AdGuard how to set up to filter ads, now it works, but can't filter any ads.
> 
> Have you configured your devices to use AdGuard Home as a DNS server?

 Thank you for replying to my question.

**Comment by ameshkov** [comment]
Both ads on the screenshots require cosmetic filtering which is not supported by AdGuard Home yet.
However, I can see that a lot of ad requests were blocked according to the stats.

Please be patient, this is a new product, we need time.

**Comment by cdwmhcc** [comment]
@ameshkov Is there a plan? Is there a rough time? Can pay for subscriptions

**Comment by ameshkov** [comment]
@cdwmhcc there is a plan to add cosmetic filtering to AGH. It is not about money, the only thing required is time :)

**Comment by cdwmhcc** [comment]
@ameshkov Now there are applications that can be installed on the route, but I only love AdGuard, I can't wait to use it right away. Thank you very much for developing and sharing such a great adguardhome, it would be great if you have planned time!

**Comment by VwEl** [comment]
老哥带带我怎么装

**Comment by syaofox** [comment]
期待http代理

**Comment by Mosney** [comment]
弱智issue，DNS怎么可能拦截页面元素

**Comment by n0thing2speak** [comment]
> 弱智issue，DNS怎么可能拦截页面元素

你这个回答更弱智，这个问题的本质是广告的分发展跟主网站是一个二级域名，导致没有办法屏蔽，跟页面元素没有关系
