### ISSUE TITLE
configuration saving and restoration

### ISSUE THREAD

**Issue by minisind** [AdguardTeam/AdGuardHome#6779]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

AdGuard Home 是非常强大和有效的。但容易发生“未运行”“未重定向”的报错，尤其是对于在GFW内的用户，与GITHUB和adguard.com的链接都不稳定。 去年开始学习使用ADGH时总是不停报错，然后停止了一段时间再来学习，发现ADGH的配置文件中有计算核心文件和过滤规则文件的MD5校验码。稍有偏差就会出错。
希望能增加一个配置的备份和恢复功能，把ADGH的所有配置及相关文件完整的备份下来，在路由器出现故障需要重新刷机或恢复出厂设置时能快速恢复ADGH的功能和设置以及自定义的各种过滤规则等。

### Proposed solution

通过备份功能把ADGH的核心文件和配置直接保存在本地的电脑中，
通过恢复功能把本地电脑中保存的所有配置恢复到路由器中使ADGH快速恢复运行。

**Comment by schzhn** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1147
