### ISSUE TITLE
AGH built-in DHCP always return another DHCP server thus can't be enabled on Rasbian OS bookworm release

### ISSUE THREAD

**Issue by amrmzr** [AdguardTeam/AdGuardHome#6783]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.44 stable

### Action

As I disabled the router DHCP and DHCPv6 server and enabled AGH built-in DHCP server on fresh install of AGH and Raspbian OS(64 bit) on raspberry pi 4 model B

### Expected result

AGH built-in server should not find another DHCP server on eth0 and thus can be enabled.

### Actual result

It finds another instance of DHCP IDK from where and can't be enabled. It shows that's its safe to use built-in dhcp server as well as with error line "If you want to enable DHCP server anyway, make sure that there is no other active DHCP server in your network"

**Comment by amrmzr** [comment]
Works Fine on Rasbian OS Bullseye.

**Comment by sunjam** [comment]
Also not working on Bookworm in DietPi.  Was able to return a green "no other dhcp server. you may enable" after disabling existing dhcp server, but still could not click the enable button despite having defined a static ip.

**Comment by amrmzr** [comment]
> Also not working on Bookworm in DietPi. Was able to return a green "no other dhcp server. you may enable" after disabling existing dhcp server, but still could not click the enable button despite having defined a static ip.

Hi!
Are you getting any error with green status notification under "Enable DHCP" ? and with DietPi you cannot use AGH DHCP server.
bcoz DietPi doesn't come with built-in DHCP client. you have to stick with router's DHCP with custom DNS settings in router as far as I know.
else you can download raspbian os legacy bullseye version (lite/with desktop).

**Comment by sunjam** [comment]
I was able to resolve this.

- [x] Set static ip on device
- [x] Set static ip on router
- [x] `Reset settings` on Adguard DHCP settings page
- [x] Manually write in the information auto-propogated in each field for eth0 interface
- [x] Write in static leases to match existing static IP's / DHCP Reservations from router
- [x] Enable button worked!

**Comment by amrmzr** [comment]
> I was able to resolve this.
> 
> - [x] Set static ip on device
> - [x] Set static ip on router
> - [x] `Reset settings` on Adguard DHCP settings page
> - [x] Manually write in the information auto-propogated in each field for eth0 interface
> - [x] Write in static leases to match existing static IP's / DHCP Reservations from router
> - [x] Enable button worked! 

Hi!
Do we have to assign static ip to every device to connect?

**Comment by amrmzr** [comment]
So, you're using dietpi with AGH DHCP server?

**Comment by overwatch3560** [comment]
Is it solved for you @amrmzr

**Comment by amrmzr** [comment]
> Is it solved for you @amrmzr 

Hi greetings!
I don't know because it's an issue on raspbian bookworm OS.

I fixed the solution by installing the legacy raspbian bullseye OS.

works fine 👍🏼 now.

Idk if they fixed it for bookworm version.
