### ISSUE TITLE
Setup adguard home router 

### ISSUE THREAD

**Issue by overwatch3560** [AdguardTeam/AdGuardHome#6786]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Latest

### Action

It’s not a bug just a question/problem

I’m setting up my adguard home server on my pi but constantly my pi ip adress doesn’t get recognized as it says the ip adress is not valid for ipv6 it works not a problem but for ipv4 it keeps saying that I know it’s on my alternate dns server tried on my main but same issue 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/97532332/f52f3b8c-cf43-4f8c-832a-2fcb1e84d720)

### Expected result

The dns server would work

### Actual result

Not recognized

**Comment by DandelionSprout** [comment]
Sounds like a mid-major bug in the router's firmware, where it refuses to recognise private-range IP addresses as valid for this kind of stuff.

I personally don't think there's any easy fixes for this bug.

**Comment by overwatch3560** [comment]
Well it does recognize and accept the 10.0.0 range only the 192.168 range doesn't work apparently
