### ISSUE TITLE
AdGuard Blocked Services!

### ISSUE THREAD

**Issue by HanyDaim** [AdguardTeam/AdGuardHome#6794]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Hello!

I’m using AdGuard Home and I also use blocked services from filters but unfortunately the Instagram service is still working even though I blocked it; the other phones can easily access to the service through Instagram app! While its website is blocked. So, it seems that the feature is working only the website not all service, so please help to fix this issue ASAP.

### Proposed solution

Update feature

### Alternatives considered and additional information

I can’t find!

**Comment by ainar-g** [comment]
Please follow the [FAQ](https://adguard-dns.io/kb/adguard-home/faq/#doesntblock) checklist.  It is likely that either your clients don't actually use AGH or there may be some domains that aren't blocked by the current rules, in which case see the <https://github.com/AdguardTeam/HostlistsRegistry> repo.
