### ISSUE TITLE
Domain filter in query log is case-sensitive

### ISSUE THREAD

**Issue by johannrichard** [AdguardTeam/AdGuardHome#680]
### Steps to reproduce
1. Open the Query Log
2. Search for a domain in the list, but using Uppercase letters (e.g. `Google`)
3. Don't find anything 
4. Search for the same domain, all lowercase (e.g. `google`)
5. Find something

### Expected behavior
Domain filter should be case-insensitive (especially on mobile where text input is auto-capitalised)

### Actual behavior
Domain filter/search in the Query log is case-sensitive

<details><summary>Screenshot:</summary>

![Screenshot 2019-03-28 at 20 09 59](https://user-images.githubusercontent.com/189003/55186060-ee35f000-5195-11e9-821f-b488e06f4c3c.png)

![Screenshot 2019-03-28 at 20 11 03](https://user-images.githubusercontent.com/189003/55186072-f5f59480-5195-11e9-9489-f5c3ca4c6019.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.94
| How did you setup DNS configuration:| IOT
| If it's a router or IoT, please write device model:| BananaPi v1
| Operating system and version:| ARMBIAN 5.75 stable Debian GNU/Linux 9 (stretch) 4.19.20-sunxi

**Comment by szolin** [comment]
fixed
