### ISSUE TITLE
AGH sometime answer A request with HTTPS

### ISSUE THREAD

**Issue by lux5am** [AdguardTeam/AdGuardHome#6801]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On one machine

### AdGuard Home version

v.0.107.44

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
>>kdig superuser.com @8.8.8.8 +https
;; TLS session (TLS1.3)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)
;; HTTP session (HTTP/2-POST)-(8.8.8.8/dns-query)-(status: 200)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 0
;; Flags: qr rd ra; QUERY: 1; ANSWER: 2; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR
;; PADDING: 390 B

;; QUESTION SECTION:
;; superuser.com.               IN      A

;; ANSWER SECTION:
superuser.com.          300     IN      A       104.18.43.79
superuser.com.          300     IN      A       172.64.144.177

;; Received 468 B
;; Time 2024-03-05 06:23:24 WITA
;; From 8.8.8.8@443(TCP) in 1073.3 ms

>>kdig superuser.com @192.168.1.1 -p 5354
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 22795
;; Flags: qr aa rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; superuser.com.               IN      A

;; ANSWER SECTION:
superuser.com.          81      IN      HTTPS   1 . alpn=h2 ipv4hint=104.18.43.79,172.64.144.177

;; Received 65 B
;; Time 2024-03-05 06:23:41 WITA
;; From 192.168.1.1@7874(UDP) in 3.0 ms
```

### Expected result

AGH should answer A request with A response

### Actual result

Sometimes AGH answer A request with HTTPS. So in my browser I can't open the web it says DNS probe not found or something like that. It's sometimes. But everyday.
By clearing the cache it back to normal answering correctly. Or it will be resolved automatically after the cache expired. But because I modify min ttl to 1800 it will be long before getting fixed so I was forced to clearing the cache manually. I don't know what's wrong maybe the upstream responded incorrectly or AGH make https request. Should AGH has some intelligence to check if the answer is correct or not.

![Screenshot_20240305-064330_Kiwi Browser.png](https://github.com/AdguardTeam/AdGuardHome/assets/110870661/c831b7f9-0cf4-4d98-8c05-71d7006d73c8)

### Additional information and/or screenshots

my upstream servers
- https://8.8.8.8/dns-query
- https://9.9.9.8/dns-query
- https://1.1.1.1/dns-query

**Comment by ainar-g** [comment]
@schzhn, please investigate.

@lux5am, can you please enable verbose logging and see what the response from the upstream was?  Just to rule out upstream issues.

**Comment by lux5am** [comment]
I'm using openwrt with limited resources. Running verbose logging for long isn't suitable. It froze the router for some reason, maybe out of memory I store it in tempfs. I'm sorry.
It's hard to deliberately cause the bug to appears. Sometimes it's github, superuser, reddit or others.
I notice in the query log when a client querying DNS it's asking for a and https type at the same time. Maybe they got mixed in? furthermore with many upstream servers?
I only put google DNS and it seems to be ok for now. I will update later.

**Comment by schzhn** [comment]
Unfortunately, we have not been able to reproduce it. And suspect its strange upstream DNS behavior.
We will close the issue for now. If the problem persists, feel free to reopen.
([Verbose logs](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) will be very helpful).

**Comment by Legendary-Lava** [comment]
I have been getting this as well on cloudflare domains, & I have a selfhosted unbound resolver. I use fastest ip address which uses only the fastest response from that resolver but this returns multiple implying that its circumventing fastest IP as well.

**Comment by jiatern** [comment]
@Legendary-Lava I face the same issues recently (especially on firefox - both windows and android) and I happen to have a self-hosted unbound resolver as the upstream for AGH. Have you found a solution yet?

**Comment by Legendary-Lava** [comment]
I have no solution, only a hacky workaround. go to the DNS tab, very bottom titled "disallowed domains" then paste these 2 lines 
*$dnstype=HTTPS
*$dnstype=SVCB

wait 2? yeah, I read into the RFC behind this, SVCB is for plain http as well. RFC 9460 btw
I dislike this workaround, it blocks Encrypted Client Hello, the use of other ports for websites, & the ALPN which specifies the HTTP versions in advance.

**Comment by lux5am** [comment]
There might be some race condition somewhere. A modern browser typically sends both A and AAAA dns request simultaneously. Additionally also HTTPS for ECH. It might be mixed up when storing it to the cache when the server give the answer the same time.
