### ISSUE TITLE
Minimum TTL is not always implemented

### ISSUE THREAD

**Issue by tescophil** [AdguardTeam/AdGuardHome#6815]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.45

### Action

I having a minimum TTL setting of 3600. Many of the DNS response responses do not implement this minimum time
![Screenshot_2024-03-10-08-16-41-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdGuardHome/assets/59442445/3fbef7c9-4708-4928-87cf-713c9c88378e)

### Expected result

TTL for all responses to honour the minimum set in the configuration.

### Actual result

DNS responses do not honour the minimum TTL configured 

![Screenshot_2024-03-10-08-27-02-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdGuardHome/assets/59442445/42bb4628-b319-48ce-a4c5-65a60c89a6d8)

**Comment by tescophil** [comment]
Hi,

AdGuardHome.yaml:  session_ttl: 720h
AdGuardHome.yaml:  cache_ttl_min: 3600
AdGuardHome.yaml:  cache_ttl_max: 86400
AdGuardHome.yaml:  cache_optimistic: true

The cache TTL of 10 seconds could explain this, however I see multiple requests for the same domain a few minutes apart all with a TTL response of 10s. I could understand the first 'optomistic' response with a TTL of 10, but then the entry should be refreshed and update with a new TTL.

Here is an example

![Screenshot_2024-03-26-08-30-46-60_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdGuardHome/assets/59442445/c5d743b7-f10f-420f-8894-8c6a37706ada)
![Screenshot_2024-03-26-08-29-35-21_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdGuardHome/assets/59442445/cc2c4d15-1613-4199-9614-3f2ac94acb07)

Same request, served from cache 10 mins apart, both with a TTL of 10s

**Comment by tescophil** [comment]
Any update on this ? It's been 4 months since I provided more info and this is still tagged "waiting for data". Am I the only one that sees this as a fundamental problem with the caching system? (which as far as I can see is broken...)

**Comment by EugeneOne1** [comment]
@tescophil, hello and apologies for the late reply.  There are some concerns about the optimistic cache implementation, I think you've encountered the one described in AdguardTeam/dnsproxy#318.  In short, the once successfully resolved request has been cached and all subsequent attempts to resolve it have failed, causing AdGuard Home to continue responding to you with the old optimistic response.  Please consider upvoting the above issue with "👍" so we can see that this is a popular topic and address it in a higher priority.  I believe this issue can be closed now.  Thanks.

**Comment by tescophil** [comment]
That's not what this is as clearly there are multiple resolvers returning a result as with the last example I gave with a TTL of 10s moving to a TTL of 60s with the next query.

**Comment by VDuyHoang** [comment]
I had the same issue, from beginning it works fine, how ever in my situation after 2 days. many domain keep get response from cache with ttl = 10s
Some verbose log: 

> 2024/12/02 13:27:12.675010 1#10391 [debug] dnsproxy: handling new udp packet raddr=10.88.0.1:59482
2024/12/02 13:27:12.675287 1#10391 [debug] dnsproxy: in line_num=1 line=";; opcode: QUERY, status: NOERROR, id: 58985"
2024/12/02 13:27:12.675459 1#10391 [debug] dnsproxy: in line_num=2 line=";; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1"
2024/12/02 13:27:12.675594 1#10391 [debug] dnsproxy: in line_num=3 line=""
2024/12/02 13:27:12.675759 1#10391 [debug] dnsproxy: in line_num=4 line=";; OPT PSEUDOSECTION:"
2024/12/02 13:27:12.675922 1#10391 [debug] dnsproxy: in line_num=5 line="; EDNS: version 0; flags:; udp: 4096"
2024/12/02 13:27:12.676134 1#10391 [debug] dnsproxy: in line_num=6 line="; COOKIE: 95e98ccdd45709f6"
2024/12/02 13:27:12.676313 1#10391 [debug] dnsproxy: in line_num=7 line=""
2024/12/02 13:27:12.676468 1#10391 [debug] dnsproxy: in line_num=8 line=";; QUESTION SECTION:"
2024/12/02 13:27:12.676617 1#10391 [debug] dnsproxy: in line_num=9 line=";clients.l.google.com.\tIN\t A"
2024/12/02 13:27:12.676746 1#10391 [debug] dnsproxy: in line_num=10 line=""
2024/12/02 13:27:12.676895 1#10391 [debug] dnsforward: started processing initial
2024/12/02 13:27:12.677098 1#10391 [debug] applying filters: looking for client with ip 10.88.0.1 and clientid ""
2024/12/02 13:27:12.677382 1#10391 [debug] applying filters: no clients with ip 10.88.0.1 and clientid ""
2024/12/02 13:27:12.677397 1#5855 [debug] addrproc: processing rdns ip=10.88.0.1
2024/12/02 13:27:12.677498 1#10391 [debug] dnsforward: finished processing initial
2024/12/02 13:27:12.677805 1#5855 [debug] addrproc: finished processing rdns ip=10.88.0.1 host="" elapsed=474.931µs
2024/12/02 13:27:12.677859 1#10391 [debug] dnsforward: started processing ddr
2024/12/02 13:27:12.678124 1#5855 [debug] addrproc: processing whois ip=10.88.0.1
2024/12/02 13:27:12.678126 1#10391 [debug] dnsforward: finished processing ddr
2024/12/02 13:27:12.678341 1#5855 [debug] addrproc: finished processing whois ip=10.88.0.1 whois=<nil> elapsed=346.668µs
2024/12/02 13:27:12.678430 1#10391 [debug] dnsforward: started processing dhcp hosts
2024/12/02 13:27:12.678579 1#10391 [debug] dnsforward: finished processing dhcp hosts
2024/12/02 13:27:12.678709 1#10391 [debug] dnsforward: started processing dhcp addrs
2024/12/02 13:27:12.678841 1#10391 [debug] dnsforward: finished processing dhcp addrs
2024/12/02 13:27:12.679001 1#10391 [debug] dnsforward: started processing filtering before req
2024/12/02 13:27:12.679157 1#10391 [debug] dnsforward: finished processing filtering before req
2024/12/02 13:27:12.679289 1#10391 [debug] dnsforward: started processing upstream
2024/12/02 13:27:12.679600 1#10391 [debug] dnsproxy: setting ecs subnet=171.253.128.0/24
2024/12/02 13:27:12.679771 1#10391 [debug] legacy logger: got prefix "cache" in record for logger with prefix "dnsproxy"
2024/12/02 13:27:12.679930 1#10391 [debug] dnsproxy: replying from cache ecs_enabled=true
2024/12/02 13:27:12.680120 1#10391 [debug] dnsforward: finished processing upstream
2024/12/02 13:27:12.680277 1#10391 [debug] dnsforward: started processing filtering after resp
2024/12/02 13:27:12.680401 1#10391 [debug] dnsforward: finished processing filtering after resp
2024/12/02 13:27:12.680576 1#10391 [debug] ipset: started processing
2024/12/02 13:27:12.680774 1#10391 [debug] ipset: finished processing
2024/12/02 13:27:12.680883 1#10391 [debug] dnsforward: started processing querylog and stats
2024/12/02 13:27:12.681007 1#10391 [debug] dnsforward: client ip for stats and querylog: 10.88.0.1
2024/12/02 13:27:12.681216 1#10391 [debug] dnsforward: finished processing querylog and stats
2024/12/02 13:27:12.681392 1#10391 [debug] dnsproxy: out line_num=1 line=";; opcode: QUERY, status: NOERROR, id: 58985"
2024/12/02 13:27:12.681557 1#10391 [debug] dnsproxy: out line_num=2 line=";; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1"
2024/12/02 13:27:12.681687 1#10391 [debug] dnsproxy: out line_num=3 line=""
2024/12/02 13:27:12.681848 1#10391 [debug] dnsproxy: out line_num=4 line=";; OPT PSEUDOSECTION:"
2024/12/02 13:27:12.682033 1#10391 [debug] dnsproxy: out line_num=5 line="; EDNS: version 0; flags:; udp: 4096"
2024/12/02 13:27:12.682248 1#10391 [debug] dnsproxy: out line_num=6 line=""
2024/12/02 13:27:12.682443 1#10391 [debug] dnsproxy: out line_num=7 line=";; QUESTION SECTION:"
2024/12/02 13:27:12.682641 1#10391 [debug] dnsproxy: out line_num=8 line=";clients.l.google.com.\tIN\t A"
2024/12/02 13:27:12.682755 1#10391 [debug] dnsproxy: out line_num=9 line=""
2024/12/02 13:27:12.682941 1#10391 [debug] dnsproxy: out line_num=10 line=";; ANSWER SECTION:"
2024/12/02 13:27:12.683136 1#10391 [debug] dnsproxy: out line_num=11 line="CLIeNTs.L.GooGLE.COm.\t10\tIN\tA\t142.250.207.46"
2024/12/02 13:27:12.683324 1#10391 [debug] dnsproxy: out line_num=12 line=""
2024/12/02 13:27:12.701392 1#10392 [debug] dnsproxy: resolved src=upstream rtt=21.113059ms
2024/12/02 13:27:12.701643 1#10392 [debug] dnsproxy: ttl overwritten old=214 new=3600
2024/12/02 13:27:12.701794 1#10392 [debug] dnsproxy: ttl overwritten old=214 new=3600
2024/12/02 13:27:12.701930 1#10392 [debug] dnsproxy: ttl overwritten old=214 new=3600
2024/12/02 13:27:12.702096 1#10392 [debug] dnsproxy: ttl overwritten old=214 new=3600
2024/12/02 13:27:12.702244 1#10392 [debug] dnsproxy: ttl overwritten old=214 new=3600
2024/12/02 13:27:12.702392 1#10392 [debug] dnsproxy: ttl overwritten old=214 new=3600
2024/12/02 13:27:12.702538 1#10392 [debug] legacy logger: got prefix "cache" in record for logger with prefix "dnsproxy"
2024/12/02 13:27:12.702720 1#10392 [debug] dnsproxy: ecs option in response ecs=171.253.128.0/20
2024/12/02 13:27:15.738451 1#10393 [debug] dnsproxy: handling new udp packet raddr=10.88.0.1:40529
2024/12/02 13:27:15.738734 1#10393 [debug] dnsproxy: in line_num=1 line=";; opcode: QUERY, status: NOERROR, id: 49203"
2024/12/02 13:27:15.738928 1#10393 [debug] dnsproxy: in line_num=2 line=";; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1"
2024/12/02 13:27:15.739140 1#10393 [debug] dnsproxy: in line_num=3 line=""
2024/12/02 13:27:15.739318 1#10393 [debug] dnsproxy: in line_num=4 line=";; OPT PSEUDOSECTION:"
2024/12/02 13:27:15.739499 1#10393 [debug] dnsproxy: in line_num=5 line="; EDNS: version 0; flags:; udp: 4096"
2024/12/02 13:27:15.739643 1#10393 [debug] dnsproxy: in line_num=6 line="; COOKIE: 98b4a6587655f2e5"
2024/12/02 13:27:15.739800 1#10393 [debug] dnsproxy: in line_num=7 line=""
2024/12/02 13:27:15.739943 1#10393 [debug] dnsproxy: in line_num=8 line=";; QUESTION SECTION:"
2024/12/02 13:27:15.740155 1#10393 [debug] dnsproxy: in line_num=9 line=";clients.l.google.com.\tIN\t A"
2024/12/02 13:27:15.740298 1#10393 [debug] dnsproxy: in line_num=10 line=""
2024/12/02 13:27:15.740440 1#10393 [debug] dnsforward: started processing initial
2024/12/02 13:27:15.740593 1#10393 [debug] applying filters: looking for client with ip 10.88.0.1 and clientid ""
2024/12/02 13:27:15.740795 1#5855 [debug] addrproc: processing rdns ip=10.88.0.1
2024/12/02 13:27:15.740863 1#10393 [debug] applying filters: no clients with ip 10.88.0.1 and clientid ""
2024/12/02 13:27:15.741178 1#10393 [debug] dnsforward: finished processing initial
2024/12/02 13:27:15.741187 1#5855 [debug] addrproc: finished processing rdns ip=10.88.0.1 host="" elapsed=210.668µs
2024/12/02 13:27:15.741377 1#10393 [debug] dnsforward: started processing ddr
2024/12/02 13:27:15.741577 1#5855 [debug] addrproc: processing whois ip=10.88.0.1
2024/12/02 13:27:15.741778 1#10393 [debug] dnsforward: finished processing ddr
2024/12/02 13:27:15.742028 1#5855 [debug] addrproc: finished processing whois ip=10.88.0.1 whois=<nil> elapsed=192.872µs
2024/12/02 13:27:15.742092 1#10393 [debug] dnsforward: started processing dhcp hosts
2024/12/02 13:27:15.742280 1#10393 [debug] dnsforward: finished processing dhcp hosts
2024/12/02 13:27:15.742386 1#10393 [debug] dnsforward: started processing dhcp addrs
2024/12/02 13:27:15.742582 1#10393 [debug] dnsforward: finished processing dhcp addrs
2024/12/02 13:27:15.742674 1#10393 [debug] dnsforward: started processing filtering before req
2024/12/02 13:27:15.742875 1#10393 [debug] dnsforward: finished processing filtering before req
2024/12/02 13:27:15.743003 1#10393 [debug] dnsforward: started processing upstream
2024/12/02 13:27:15.743361 1#10393 [debug] dnsproxy: setting ecs subnet=171.253.128.0/24
2024/12/02 13:27:15.743634 1#10393 [debug] legacy logger: got prefix "cache" in record for logger with prefix "dnsproxy"
2024/12/02 13:27:15.743824 1#10393 [debug] dnsproxy: replying from cache ecs_enabled=true
2024/12/02 13:27:15.743941 1#10393 [debug] dnsforward: finished processing upstream
2024/12/02 13:27:15.744192 1#10393 [debug] dnsforward: started processing filtering after resp
2024/12/02 13:27:15.744332 1#10393 [debug] dnsforward: finished processing filtering after resp
2024/12/02 13:27:15.744565 1#10393 [debug] ipset: started processing
2024/12/02 13:27:15.744750 1#10393 [debug] ipset: finished processing
2024/12/02 13:27:15.744867 1#10393 [debug] dnsforward: started processing querylog and stats
2024/12/02 13:27:15.745069 1#10393 [debug] dnsforward: client ip for stats and querylog: 10.88.0.1
2024/12/02 13:27:15.745265 1#10393 [debug] dnsforward: finished processing querylog and stats
2024/12/02 13:27:15.745482 1#10393 [debug] dnsproxy: out line_num=1 line=";; opcode: QUERY, status: NOERROR, id: 49203"
2024/12/02 13:27:15.745611 1#10393 [debug] dnsproxy: out line_num=2 line=";; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1"
2024/12/02 13:27:15.745784 1#10393 [debug] dnsproxy: out line_num=3 line=""
2024/12/02 13:27:15.745908 1#10393 [debug] dnsproxy: out line_num=4 line=";; OPT PSEUDOSECTION:"
2024/12/02 13:27:15.746132 1#10393 [debug] dnsproxy: out line_num=5 line="; EDNS: version 0; flags:; udp: 4096"
2024/12/02 13:27:15.746286 1#10393 [debug] dnsproxy: out line_num=6 line=""
2024/12/02 13:27:15.746412 1#10393 [debug] dnsproxy: out line_num=7 line=";; QUESTION SECTION:"
2024/12/02 13:27:15.746590 1#10393 [debug] dnsproxy: out line_num=8 line=";clients.l.google.com.\tIN\t A"
2024/12/02 13:27:15.746765 1#10393 [debug] dnsproxy: out line_num=9 line=""
2024/12/02 13:27:15.746899 1#10393 [debug] dnsproxy: out line_num=10 line=";; ANSWER SECTION:"
2024/12/02 13:27:15.747147 1#10393 [debug] dnsproxy: out line_num=11 line="CLIeNTs.L.GooGLE.COm.\t10\tIN\tA\t142.250.207.46"
2024/12/02 13:27:15.747278 1#10393 [debug] dnsproxy: out line_num=12 line=""
2024/12/02 13:27:15.765540 1#10394 [debug] dnsproxy: resolved src=upstream rtt=21.367204ms
2024/12/02 13:27:15.765793 1#10394 [debug] dnsproxy: ttl overwritten old=211 new=3600
2024/12/02 13:27:15.765994 1#10394 [debug] dnsproxy: ttl overwritten old=211 new=3600
2024/12/02 13:27:15.766207 1#10394 [debug] dnsproxy: ttl overwritten old=211 new=3600
2024/12/02 13:27:15.766389 1#10394 [debug] dnsproxy: ttl overwritten old=211 new=3600
2024/12/02 13:27:15.766522 1#10394 [debug] dnsproxy: ttl overwritten old=211 new=3600
2024/12/02 13:27:15.766698 1#10394 [debug] dnsproxy: ttl overwritten old=211 new=3600
2024/12/02 13:27:15.766867 1#10394 [debug] legacy logger: got prefix "cache" in record for logger with prefix "dnsproxy"
2024/12/02 13:27:15.767064 1#10394 [debug] dnsproxy: ecs option in response ecs=171.253.128.0/20
2024/12/02 13:27:17.752541 1#10395 [debug] dnsproxy: handling new udp packet raddr=10.88.0.1:57450
2024/12/02 13:27:17.752838 1#10395 [debug] dnsproxy: in line_num=1 line=";; opcode: QUERY, status: NOERROR, id: 50424"
2024/12/02 13:27:17.753120 1#10395 [debug] dnsproxy: in line_num=2 line=";; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1"
2024/12/02 13:27:17.753285 1#10395 [debug] dnsproxy: in line_num=3 line=""
2024/12/02 13:27:17.753538 1#10395 [debug] dnsproxy: in line_num=4 line=";; OPT PSEUDOSECTION:"
2024/12/02 13:27:17.753754 1#10395 [debug] dnsproxy: in line_num=5 line="; EDNS: version 0; flags:; udp: 4096"
2024/12/02 13:27:17.753915 1#10395 [debug] dnsproxy: in line_num=6 line="; COOKIE: fa736d4e9927aeda"
2024/12/02 13:27:17.754155 1#10395 [debug] dnsproxy: in line_num=7 line=""
2024/12/02 13:27:17.754320 1#10395 [debug] dnsproxy: in line_num=8 line=";; QUESTION SECTION:"
2024/12/02 13:27:17.754517 1#10395 [debug] dnsproxy: in line_num=9 line=";clients.l.google.com.\tIN\t A"
2024/12/02 13:27:17.754671 1#10395 [debug] dnsproxy: in line_num=10 line=""
2024/12/02 13:27:17.754852 1#10395 [debug] dnsforward: started processing initial
2024/12/02 13:27:17.755064 1#10395 [debug] applying filters: looking for client with ip 10.88.0.1 and clientid ""
2024/12/02 13:27:17.755176 1#5855 [debug] addrproc: processing rdns ip=10.88.0.1
2024/12/02 13:27:17.755366 1#10395 [debug] applying filters: no clients with ip 10.88.0.1 and clientid ""
2024/12/02 13:27:17.755482 1#5855 [debug] addrproc: finished processing rdns ip=10.88.0.1 host="" elapsed=254.265µs
2024/12/02 13:27:17.755577 1#10395 [debug] dnsforward: finished processing initial
2024/12/02 13:27:17.755720 1#5855 [debug] addrproc: processing whois ip=10.88.0.1
2024/12/02 13:27:17.755994 1#5855 [debug] addrproc: finished processing whois ip=10.88.0.1 whois=<nil> elapsed=273.174µs
2024/12/02 13:27:17.755748 1#10395 [debug] dnsforward: started processing ddr
2024/12/02 13:27:17.756180 1#10395 [debug] dnsforward: finished processing ddr
2024/12/02 13:27:17.756280 1#10395 [debug] dnsforward: started processing dhcp hosts
2024/12/02 13:27:17.756380 1#10395 [debug] dnsforward: finished processing dhcp hosts
2024/12/02 13:27:17.756472 1#10395 [debug] dnsforward: started processing dhcp addrs
2024/12/02 13:27:17.756598 1#10395 [debug] dnsforward: finished processing dhcp addrs
2024/12/02 13:27:17.756732 1#10395 [debug] dnsforward: started processing filtering before req
2024/12/02 13:27:17.756840 1#10395 [debug] dnsforward: finished processing filtering before req
2024/12/02 13:27:17.756983 1#10395 [debug] dnsforward: started processing upstream
2024/12/02 13:27:17.757262 1#10395 [debug] dnsproxy: setting ecs subnet=171.253.128.0/24
2024/12/02 13:27:17.757439 1#10395 [debug] legacy logger: got prefix "cache" in record for logger with prefix "dnsproxy"
2024/12/02 13:27:17.757580 1#10395 [debug] dnsproxy: replying from cache ecs_enabled=true
2024/12/02 13:27:17.757692 1#10395 [debug] dnsforward: finished processing upstream
2024/12/02 13:27:17.757810 1#10395 [debug] dnsforward: started processing filtering after resp
2024/12/02 13:27:17.758001 1#10395 [debug] dnsforward: finished processing filtering after resp
2024/12/02 13:27:17.758195 1#10395 [debug] ipset: started processing
2024/12/02 13:27:17.758365 1#10395 [debug] ipset: finished processing
2024/12/02 13:27:17.758492 1#10395 [debug] dnsforward: started processing querylog and stats
2024/12/02 13:27:17.758635 1#10395 [debug] dnsforward: client ip for stats and querylog: 10.88.0.1
2024/12/02 13:27:17.758855 1#10395 [debug] dnsforward: finished processing querylog and stats
2024/12/02 13:27:17.759092 1#10395 [debug] dnsproxy: out line_num=1 line=";; opcode: QUERY, status: NOERROR, id: 50424"
2024/12/02 13:27:17.759269 1#10395 [debug] dnsproxy: out line_num=2 line=";; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1"
2024/12/02 13:27:17.759451 1#10395 [debug] dnsproxy: out line_num=3 line=""
2024/12/02 13:27:17.759587 1#10395 [debug] dnsproxy: out line_num=4 line=";; OPT PSEUDOSECTION:"
2024/12/02 13:27:17.759773 1#10395 [debug] dnsproxy: out line_num=5 line="; EDNS: version 0; flags:; udp: 4096"
2024/12/02 13:27:17.759928 1#10395 [debug] dnsproxy: out line_num=6 line=""
2024/12/02 13:27:17.760138 1#10395 [debug] dnsproxy: out line_num=7 line=";; QUESTION SECTION:"
2024/12/02 13:27:17.760308 1#10395 [debug] dnsproxy: out line_num=8 line=";clients.l.google.com.\tIN\t A"
2024/12/02 13:27:17.760446 1#10395 [debug] dnsproxy: out line_num=9 line=""
2024/12/02 13:27:17.760581 1#10395 [debug] dnsproxy: out line_num=10 line=";; ANSWER SECTION:"
2024/12/02 13:27:17.760713 1#10395 [debug] dnsproxy: out line_num=11 line="CLIeNTs.L.GooGLE.COm.\t10\tIN\tA\t142.250.207.46"
2024/12/02 13:27:17.760842 1#10395 [debug] dnsproxy: out line_num=12 line=""
2024/12/02 13:27:17.779236 1#10409 [debug] dnsproxy: resolved src=upstream rtt=21.288586ms
2024/12/02 13:27:17.779453 1#10409 [debug] dnsproxy: ttl overwritten old=209 new=3600
2024/12/02 13:27:17.779676 1#10409 [debug] dnsproxy: ttl overwritten old=209 new=3600
2024/12/02 13:27:17.779864 1#10409 [debug] dnsproxy: ttl overwritten old=209 new=3600
2024/12/02 13:27:17.780137 1#10409 [debug] dnsproxy: ttl overwritten old=209 new=3600
2024/12/02 13:27:17.780407 1#10409 [debug] dnsproxy: ttl overwritten old=209 new=3600
2024/12/02 13:27:17.780567 1#10409 [debug] dnsproxy: ttl overwritten old=209 new=3600
2024/12/02 13:27:17.780795 1#10409 [debug] legacy logger: got prefix "cache" in record for logger with prefix "dnsproxy"
2024/12/02 13:27:17.780987 1#10409 [debug] dnsproxy: ecs option in response ecs=171.253.128.0/20
