### ISSUE TITLE
docker pull failed to register layer: lsetxattr security.capability

### ISSUE THREAD

**Issue by dc-me** [AdguardTeam/AdGuardHome#6816]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest

### Action

docker pull adguard/adguardhome:latest

### Expected result

pull the image

### Actual result

failed to register layer: lsetxattr security.capability /opt/adguardhome/AdGuardHome: operation not supported

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/8910772/002d1eea-c560-4dd3-94f0-8604d9cd8ea0)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/8910772/67161572-5484-4fdc-a30e-d72281fd3d9a)

**Comment by dc-me** [comment]
I've set it on openwrt use the official package, but can't run it on openwrt docker, I think it's platform dependent, I can use it to pull other images run containers fine, but can't pull adguardhome image. 

OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-24.048.61449-c66fc92

**Comment by dc-me** [comment]
Here's the cuase CONFIG_KERNEL_EXT4_FS_SECURITY is not the default setting for OpenWrt's kernels
Just for a reference https://lists.openwrt.org/pipermail/openwrt-devel/2024-January/041978.html

**Comment by hubrichc** [comment]
Have the same problem. Want to run a Caddy Container in openwrt. Does not work. Same failure.
docker: failed to register layer: lsetxattr security.capability /usr/bin/caddy: operation not supported.
OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256

**Comment by dc-me** [comment]
For anyone who's kernel does not have CONFIG_KERNEL_EXT4_FS_SECURITY option set, such as OpenWrt, use this image 
docker pull danychen/adguardhome-dev
