### ISSUE TITLE
Can I block a exact https url but not a domain？

### ISSUE THREAD

**Issue by arfaWong** [AdguardTeam/AdGuardHome#682]

**Comment by ameshkov** [comment]
Currently, you cannot. AGH provides a DNS server, and for what you want we'll have to provide a mitm-proxy with filtering capabilities. Spoiler: we're going to do it eventually.

**Comment by hplee0120** [comment]
> Currently, you cannot. AGH provides a DNS server, and for what you want we'll have to provide a mitm-proxy with filtering capabilities. Spoiler: we're going to do it eventually.

Is this filtering plan that supports HTTP/HTTPS on the agenda?  The dns filtering scheme used now has a lot of manslaughters and is not very accurate.  I wonder if you can understand what I mean by filtering HTTP/HTTPS.  Filter rules refer to https://github.com/houzi-/CDN/blob/master/koolproxy.txt

**Comment by ameshkov** [comment]
@hplee0120 yep, there's a plan for that: https://github.com/AdguardTeam/AdGuardHome/issues/1228

**Comment by hplee0120** [comment]
> @hplee0120 yep, there's a plan for that: #1228

Thank you, this is a very good feature, look forward to going online
