### ISSUE TITLE
Top Blocked Clients on the dashboard

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#683]
Pretty self explanatory, a list on the AGH Dashboard displaying the top blocked clients next to top queried clients.

(This leaves room for either 6 more "General Statistics" or a table for other items ;))

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2150

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/2075
