### ISSUE TITLE
AGH DNS not work on Openwrt 22.03.05

### ISSUE THREAD

**Issue by vanchienbmt** [AdguardTeam/AdGuardHome#6834]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, MIPS

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.21-1

### Action

I have install AGH on Openwrt 22.03.5 and config all working but AGH can't grant DNS for client , i change default DNS to port 54 and AGH use port 53. Haven't any guide fix this problem.

### Expected result

i want fixed DNS AGH on Openwrt 22.03.5

### Actual result

AGH don't grant DNS for client

**Comment by Cebeerre** [comment]
Hi,

Did you actually follow the procedure explained on the OpenWRT wiki ? Once you change the default port of dnsmasq, the DNS assignation over DHCP stops working and you need to set this manually:

https://openwrt.org/docs/guide-user/services/dns/adguard-home#setup

Xavi
