### ISSUE TITLE
Google DNS rejected the query when EDNS was enabled.

### ISSUE THREAD

**Issue by bigbabybubble** [AdguardTeam/AdGuardHome#6839]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.46

### Action

Google DNS query 
Client - External IPv4

### Expected result

No error

### Actual result

Refused

![IMG_3469](https://github.com/AdguardTeam/AdGuardHome/assets/135120237/9fa537fc-204d-4029-937f-7f7f1f099cde)
![IMG_3470](https://github.com/AdguardTeam/AdGuardHome/assets/135120237/27e752a1-1bf5-4208-8055-2b8ee70d7e41)

**Comment by ainar-g** [comment]
This is likely some weird behavior between Google and the Akamai servers, and not an AdGuard Home bug, as this can be reproduced using `dig`:

```sh
dig @8.8.8.8 e2063.e9.akamaiedge.net +subnet=1.2.0.0/16
```

```none
[…]
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 12345
[…]
```

You can just [redirect](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains) `akamaiedge.net` queries to a different upstream.
