### ISSUE TITLE
Less Obtrusive Block/Unblock Button in Query Log

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardHome#684]
<img width="1158" alt="Screen Shot 2019-03-30 at 01 28 20" src="https://user-images.githubusercontent.com/6005161/55243581-715b5280-5237-11e9-81f9-a2a4ba80483d.png">
As you can see by the screenshot the block/unblock button is covering up the IP of the client when the hostname has been set making it impossible to identify the last set of numerals.

I recommend adding an extra column for the button.

_Note: For the purpose of aesthetics, if an extra column is created a way of highlighting each line as you hover over it will be needed as the block/unblock button will no longer act as this indicator._

**Comment by ArchiveBase** [comment]
That belongs to both desktop and mobile when browser window size small https://github.com/AdguardTeam/AdGuardHome/issues/978

**Comment by ainar-g** [comment]
The latest Edge and Beta releases have a better UI with a tooltip menu, so we'll close this.  If anyone has issues with those, please file new issues with descriptions and screenshots.

**Comment by hexclann** [comment]
@ainar-g Can we please have an option to disable this feature and have the block button always visible? I get around 5 million queries every month from 15+ devices and I actively use the query log page to block the domains and moving the button to tooltip will add an extra step in the process.

The old UI was much more usable than the current one.

**Comment by agneevX** [comment]
This is good but there's still too much space for clients in the default view:

![Screenshot](https://github.com/AdguardTeam/AdGuardHome/assets/19761269/917b26e9-63cc-47a9-9c4c-2c8d191d6e8d)

**Comment by lucktu** [comment]
I think that after the modification, the use of the forbidden function is not as convenient as before, I suggest this one to restore back.

I'll stick with AdGuard Home v0.107.39.
