### ISSUE TITLE
关于DNS功能增强的建议

### ISSUE THREAD

**Issue by lemontealin** [AdguardTeam/AdGuardHome#6840]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

当前版本的“乐观缓存”功能在缓存过期情况下需要等待重新查询，这个较长的时间间隔很容易让设备误以为是连接失效

### Proposed solution

希望在后续版本中加入乐观缓存的生存时间设置，即设定时间后强制乐观缓存刷新。
如果能考虑假如域名预加载功能就更好了😘

**Comment by ainar-g** [comment]
> The current version of the "Optimistic Cache" feature needs to wait for a new query when the cache expires, and this long time interval can easily cause the device to think that the connection has failed.

I'm not sure what you mean by this.  When the optimistic mode is enabled, records are updated in the background, while clients receive responses immediately.  Please describe the issue you're having in more detail.

**Comment by qingxiaoxinrou** [comment]
你应该是没有懂ADGH的原理，你缓存够大的情况下，过时缓存是一直在内存的，除非内存缓存不够后会被从内存删除，这种问题就不用提单了，至于你说的域名热度预加载，没必要，除非你客户端极少，不用考虑edns的情况下，这对ADGH来实现还是比较麻烦的，官方不会考虑，这个东西应该是递归考虑的东西，而不是像 ADGH这种转发器。解答完毕

**Comment by lemontealin** [comment]
主要是乐观缓存过期之后会有几秒转圈的加载时间，遇到过有些网站在这种情况下丢图，所以想问问能不能加入乐观缓存的生存时间设置😂

**Comment by qingxiaoxinrou** [comment]
仔细阅读我的回答，你的解析速度由你的上游决定，和过时缓存的生存时间没有关系，你缓存设置的足够大的情况下，过时缓存是一直在的

**Comment by lemontealin** [comment]
行吧，我再研究研究，感谢解答
