### ISSUE TITLE
Adguard Sucks whole internet over night || cant use "protection"

### ISSUE THREAD

**Issue by FoxXxHater** [AdguardTeam/AdGuardHome#6845]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

latest (v0.107.46)

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.google.com' '192.168.20.2'
```

PS C:\Users\John> nslookup -debug -type=a 'www.google.com' '192.168.20.2'
------------
Got answer:
    HEADER:
        opcode = QUERY, id = 1, rcode = NXDOMAIN
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 0,  authority records = 1,  additional = 0

    QUESTIONS:
        2.20.168.192.in-addr.arpa, type = PTR, class = IN
    AUTHORITY RECORDS:
    ->  2.20.168.192.in-addr.arpa
        ttl = 10 (10 secs)
        primary name server = fake-for-negative-caching.adguard.com
        responsible mail addr = hostmaster.2.20.168.192.in-addr.arpa
        serial  = 100500
        refresh = 1800 (30 mins)
        retry   = 900 (15 mins)
        expire  = 604800 (7 days)
        default TTL = 86400 (1 day)

------------
Server:  UnKnown
Address:  192.168.20.2

DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
DNS request timed out.
    timeout was 2 seconds.
timeout (2 secs)
*** Zeitüberschreitung bei Anforderung an UnKnown.

### Expected result

Dont know, that it works :LuL:

### Actual result

If the "protection" is on no, and i mean NO connection is possible. But the pings to 1.1.1.1 or 8.8.8.8 are posible, so its not my ISP.

Yesterday everything works fine
![image](https://github.com/AdguardTeam/AdGuardHome/assets/54017453/f8648cea-86ad-48dd-a77a-a0c1879e8c5d)
But at 2am the connection was down, the docker log of both AdGuard servers are full with the error entries...

### Additional information and/or screenshots

The docker logs are attached.
[_AdGuard-update-24-11-23_logs.txt](https://github.com/AdguardTeam/AdGuardHome/files/14730861/_AdGuard-update-24-11-23_logs.txt)

**Comment by FoxXxHater** [comment]
P.S. If the protection is of the connection are back...

**Comment by FoxXxHater** [comment]
P.P.S. 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/54017453/2913c250-b32c-48d5-92a2-2982e59cff3d)
the 192.168.178.1 and the 192.168.20.2 isnt listed as upstream DNS server... 

![image](https://github.com/AdguardTeam/AdGuardHome/assets/54017453/5b5fcf38-6fe6-4bfc-936f-afba236ee5ac)

**Comment by FoxXxHater** [comment]
> Are you able to access the dashboard when protection is enabled? Did you map the ports?
> 
> > Ports mappings you may need:
> > -p 53:53/tcp -p 53:53/udp: plain DNS.
> > -p 67:67/udp -p 68:68/tcp -p 68:68/udp: add if you intend to use AdGuard Home as a DHCP server.
> > -p 80:80/tcp -p 443:443/tcp -p 443:443/udp -p 3000:3000/tcp: add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an [HTTPS/DNS-over-HTTPS](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption) server.
> > -p 853:853/tcp: add if you are going to run AdGuard Home as a [DNS-over-TLS](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption) server.
> > -p 784:784/udp -p 853:853/udp -p 8853:8853/udp: add if you are going to run AdGuard Home as a [DNS-over-QUIC](https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption) server. You may only leave one or two of these.
> > -p 5443:5443/tcp -p 5443:5443/udp: add if you are going to run AdGuard Home as a [DNSCrypt](https://github.com/AdguardTeam/AdGuardHome/wiki/DNSCrypt) server.

As already mentioned, everything worked wonderfully until around 2 and has done so for months... all necessary ports are gamapt. And I have switched off the protection via the web interface, so yes.

**Comment by Cebeerre** [comment]
> the 192.168.178.1 and the 192.168.20.2 isnt listed as upstream DNS server...

If they show there, then they're configured as Private Resolvers.

Your log actually shows timeouts both connecting to your upstreams and the Adguard Family Protection DNS server, so I guess you ticked the "Adguard Parental control web service". That might not be caused 100% by your ISP, but it doesn't look like a bug.

**Comment by FoxXxHater** [comment]
Hay there, 

what you are meaning with the "Adguard Parental control web service"?
The interessting is... the fail comes at 2am in the night. I go 8pm offline (Sleeping) so nothing was changed...

**Comment by FoxXxHater** [comment]
I found my failure...

The Unify Console ha blocked the internet connection to the up DNS servers. You can't turn on the add filtering on that network from the AdGuard server. So I turned it off and now it works!
