### ISSUE TITLE
Failed to install on Home Assitant Yellow hardware 

### ISSUE THREAD

**Issue by multinet33** [AdguardTeam/AdGuardHome#6846]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

latest

### Action

Install vi ssh (root user) and command : wget --no-verbose -O - https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v

### Expected result

AdGuardHome installed and running as a service

### Actual result

[core-ssh ~]$ wget --no-verbose -O - https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v
Connecting to raw.githubusercontent.com (185.199.109.133:443)
writing to stdout
-                    100% |**************************************************************************************************************************************************| 13133  0:00:00 ETA
written to stdout
starting AdGuard Home installation script
channel: release
operating system: linux
cpu type: arm64
AdGuard Home will be installed into /opt/AdGuardHome
checking tar
script is executed with root privileges
no need to uninstall
downloading package from https://static.adtidy.org/adguardhome/release/AdGuardHome_linux_arm64.tar.gz -> AdGuardHome_linux_arm64.tar.gz
successfully downloaded AdGuardHome_linux_arm64.tar.gz
unpacking package from AdGuardHome_linux_arm64.tar.gz into /opt
successfully unpacked, contents: 
total 29676
-rwxrwxrwx    1 root     root      30212096 Mar 20 15:29 AdGuardHome
-rw-rw-rw-    1 root     root           587 Mar 20 15:29 AdGuardHome.sig
-rw-r--r--    1 root     root        109975 Mar 20 15:29 CHANGELOG.md
-rw-r--r--    1 root     root         35149 Mar 20 15:29 LICENSE.txt
-rw-r--r--    1 root     root         22300 Mar 20 15:29 README.md
2024/03/23 09:57:16 [info] AdGuard Home, version v0.107.46
2024/03/23 09:57:16 [info] service: control action: install
2024/03/23 09:57:16 [fatal] service: executing action "install": Failed to install AdGuard Home service: Init already exists: /etc/init.d/AdGuardHome
installation failed, removing /opt/AdGuardHome
**cannot install AdGuardHome as a service**

### Additional information and/or screenshots

[core-ssh ~]$ uname -a
Linux core-ssh 6.1.73-haos-raspi #1 SMP PREEMPT Wed Mar 13 12:11:08 UTC 2024 aarch64 Linux

**Comment by Cebeerre** [comment]
Given that you're using the Yellow appliance and this comes with HAOS, probably makes more sense that you install AGH as an HAOS Add-on. Have you tried ?
