### ISSUE TITLE
Unexpected upstream DNS server reset after changing DNS cache configuration

### ISSUE THREAD

**Issue by OctaDevelop** [AdguardTeam/AdGuardHome#6851]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.46

### Action

changed Override minimum TTL and Override maximum TTL in DNS cache configuration

### Expected result

ONLY these two parameters changed

### Actual result

two parameters changed as expected, **plus an unexpected upstream DNS server query mode reset to the default Load-balancing**

**Comment by Cebeerre** [comment]
Can confirm. If having "Parallel Requests", doing any change to "DNS server configuration" or "DNS cache configuration" reverts it back to "Load-balancing".

@ainar-g

**Comment by ainar-g** [comment]
@EugeneOne1, please investigate.

**Comment by EugeneOne1** [comment]
@OctaDevelop, hello and thanks for the report.  We've pushed the edge release containing a fix for this issue, could you please check it and confirm the upstream mode doesn't reset now?

**Comment by OctaDevelop** [comment]
@EugeneOne1 hey, thanks for your help, I just tried the latest edge channel build on a dedicated Debian 12 machine, and I believe this issue has been resolved.

**Comment by EugeneOne1** [comment]
@OctaDevelop, glad to hear.  We'll close the issue for now.  Feel free to reopen it if the problem appears again.
