### ISSUE TITLE
Unable to Use Windows RDP! Ports Are 4002

### ISSUE THREAD

**Issue by Jay8454** [AdguardTeam/AdGuardHome#6868]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

March 30th 2024

### Action

 attempted to establish a remote desktop connection to a Windows PC using the Remote Desktop Protocol (RDP) with a custom port of 4002.

Here are the steps I followed:

Opened the Remote Desktop Connection application on my local machine.
Entered the IP address of the Windows PC.
Specified the custom port 4002 in the format "IP_Address:4002" in the Remote Desktop Connection settings.
Attempted to establish the connection by clicking on the "Connect" button.
Upon attempting to connect, the Remote Desktop Connection application failed to establish a connection to the Windows PC.

To diagnose the issue, I performed an nslookup command to verify the DNS resolution for the IP address of the Windows PC.

### Expected result

I expected to successfully establish a remote desktop connection to the Windows PC using the custom RDP port 4002. Upon entering the correct IP address and specifying the custom port in the Remote Desktop Connection settings, I anticipated seeing the Windows desktop environment displayed on my local machine's screen. Additionally, I expected to be able to interact with the Windows PC as usual through the RDP session.

I did not expect any errors or connectivity issues during the connection process.

If the connection was successful, I would have seen the Windows login screen or the desktop environment, depending on whether a user session was already active on the Windows PC.

If possible, I would have provided screenshots demonstrating the successful establishment of the RDP connection and the Windows desktop environment displayed on my local machine's screen.

### Actual result

Instead of successfully establishing the remote desktop connection to the Windows PC using the custom RDP port 4002, I encountered connection issues and was unable to access the Windows desktop environment.

Upon attempting to connect using the Remote Desktop Connection settings with the correct IP address and specifying port 4002, I received an error message indicating that the connection could not be established. Despite multiple attempts, the RDP connection failed to establish.

The specific error message or indication varied depending on the client application used for the RDP connection. However, common issues included timeouts, connection refused errors, or simply no response from the target Windows PC.

As a result, I was unable to access the Windows PC remotely via RDP as intended. This prevented me from performing tasks or accessing resources on the Windows PC from a remote location.

Unfortunately, I was unable to provide screenshots as the RDP connection was unsuccessful and no desktop environment was displayed on my local machine's screen.

### Additional information and/or screenshots

Non-Standard Port: The Remote Desktop Protocol (RDP) connection is configured to use a non-standard port, specifically port 4002, instead of the default port 3389. This was set up to enhance security by using an alternative port for RDP access.

Firewall and Port Forwarding: Port 4002 is correctly forwarded in the router's settings to the internal IP address of the Windows PC running the RDP service. Additionally, firewall rules have been configured to allow incoming connections on port 4002.

Network Configuration: The network environment is a standard home network setup, with devices connected to a TP-Link Archer A9 router. The Windows PC running the RDP service is assigned a static IP address of 192.168.0.188.

Client Configuration: The Remote Desktop Connection client software is configured with the correct IP address of the Windows PC (192.168.0.188) and port 4002 for the RDP connection. The client machine is running a standard operating system (e.g., Windows 10) with no custom configurations affecting RDP functionality.

Troubleshooting Steps: Various troubleshooting steps were attempted to resolve the issue, including checking network connectivity, verifying port forwarding settings on the router, ensuring firewall rules are correctly configured, and restarting both the client and server machines.

Logs and Error Messages: Despite these efforts, no successful connection was established, and error messages varied depending on the client used for the RDP connection. Common errors included timeouts, connection refused, or no response from the target Windows PC.

Screenshot Availability: Unfortunately, screenshots of the errors encountered during the RDP connection attempts are not available, as the connection failures occurred without displaying any desktop environment or error dialogs.
![PCInfo](https://github.com/AdguardTeam/AdGuardHome/assets/152249515/bdb8f5cf-b6fe-42dc-898e-bb785413f825)

**Comment by dMopp** [comment]
And this is related to adguard home why?

**Comment by Jay8454** [comment]
The issue is distinctly localized to the machine harboring the containerized AdGuard instance. Notably, this occurs even with default settings in place and the router configured to utilize the appropriate DNS. Upon startup of the AdGuard Home container through Portainer, the host machine experiences a complete internet blackout, including the disruption of Windows Remote Desktop Protocol (RDP) connectivity. This blackout persists until the AdGuard container is manually halted, at which point normal internet access is promptly restored.
