### ISSUE TITLE
[Feature Request] Static DHCP Lease Configuration

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#687]
As part of #681 started getting conflicting IP addresses from devices that fell outside the specified AGH DHCP server IP range due to the static IP setup I had prior to enabling the AGH DHCP server.

I recommend a static DHCP lease configuration section to allow for such setups.

**Comment by szolin** [comment]
We can add exclusion list of IP addresses so the server won't use them.
For example, configuration is:
```
range_start: 192.169.56.1
range_end: 192.169.56.255
```

And we add:
`exclude: [192.169.56.3, 192.169.56.10]`

And there will be one more edit box for this in UI.

As a result these 2 IP addresses will be marked as 'occupied' and DHCP server won't use them.
Does this sound OK?

**Comment by jslawler** [comment]
That should suffice.

**Comment by szolin** [comment]
On the other hand, it may be better to add a complete support for static leases.

There will be a new table in UI to add lease entries, one by one:

```
MAC address    IP address    Action
=====================================
...            ...           <Delete>
[    ]         [    ]        <Add>
```

And `POST /control/dhcp/set_config` request should be modified:

```
--- a/AGHTechDoc.md
+++ b/AGHTechDoc.md
@@ -254,6 +254,14 @@ Request:
                "subnet_mask":"255.255.255.0",
                "range_start":"192.169.56.3",
                "range_end":"192.169.56.3",
+               "static_leases":[
+                       {
+                               "mac":"...",
+                               "ip":"...",
+                               "hostname":"..."
+                       },
+                       ...
+               ]
                "lease_duration":60,
                "icmp_timeout_msec":0
        }
```

`GET /control/dhcp/status` request is modified accordingly.
