### ISSUE TITLE
When a DNS upstream returns 0.0.0.0 and use the fastest IP mode

### ISSUE THREAD

**Issue by puteulanus** [AdguardTeam/AdGuardHome#6875]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.46

### Action

I set the test domain's record to 1.2.3.4, but on another DNS server (B), I rewrote it to 0.0.0.0.

I added B to the upstream DNS list of AdGuard Home (A), selecting the mode to query all DNS servers and return the IP address with the fastest response from all replies. 

Then, I initiated a DNS query to A.

```sh
doggo testdns.puteulanus.com @udp://192.168.1.1:5354
NAME                   	TYPE	CLASS	TTL	ADDRESS	NAMESERVER
testdns.puteulanus.com.	A   	IN   	10s	0.0.0.0	192.168.1.1:5354
```

### Expected result

When not all upstream servers return 0.0.0.0, AdGuard Home can exclude this result instead of considering it as the fastest IP, then I get 1.2.3.4 as result. Alternatively, there could be an option to configure whether a record like 0.0.0.0 should be regarded as the fastest or the slowest.

### Actual result

AdGuard Home considers 0.0.0.0 as the fastest IP, so as long as one upstream returns this IP, it will definitely be selected in this mode, resulting in downstream being unable to access. Currently, I can only avoid this problem by disabling the problematic upstream.

### Additional information and/or screenshots

The rewrite record of device B:
<img width="716" alt="图片" src="https://github.com/AdguardTeam/AdGuardHome/assets/4849177/7b88b3a4-7b29-4e6a-bd78-942d6e28291e">
The DNS settings of device A:
<img width="914" alt="图片" src="https://github.com/AdguardTeam/AdGuardHome/assets/4849177/c1429a82-fbf8-4424-9074-038ac14e54ba">
The DNS query record of device A:
<img width="809" alt="图片" src="https://github.com/AdguardTeam/AdGuardHome/assets/4849177/86d90504-e6d6-4e07-bdc8-890e80b60a7c">
The query results from other upstream DNS servers:
<img width="586" alt="图片" src="https://github.com/AdguardTeam/AdGuardHome/assets/4849177/2ea238e0-94b9-4641-83ee-e4a47c2ed0ee">

**Comment by ainar-g** [comment]
> I set the test domain's record to 1.2.3.4, but on another DNS server (B), I rewrote it to 0.0.0.0.

What you probably want is to make sure your domain is only resolved on server A.

```none
[/testdns.puteulanus.com/]https://doh.pub/dns-query
```

With that said, the fact that `0.0.0.0` is basically localhost on many Linux systems should probably be taken into account by the Fastest mode.

**Comment by EugeneOne1** [comment]
@puteulanus, hello again.  We've pushed the `edge` release which should fix the issue, could you please check, if it still pings `0.0.0.0`?

**Comment by puteulanus** [comment]
> @puteulanus, hello again. We've pushed the `edge` release which should fix the issue, could you please check, if it still pings `0.0.0.0`?

Hello and thank you for the update!

I've tested using the edge docker image, and it seems the issue has not occurred (the issue can still be reproduced with the latest image using the same settings).

Thanks for the swift response and the effort put into fixing this issue.

**Comment by Somalia0932** [comment]
The ISP’s DNS servers block certain domains by returning addresses like 0.0.0.0, 127.0.0.1, or ::1. Could an option be added to ignore upstream responses that contain only these addresses?
