### ISSUE TITLE
Use private reverse DNS resolvers for SOA records

### ISSUE THREAD

**Issue by Dennis14e** [AdguardTeam/AdGuardHome#6882]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

SOA records for private network addresses (e.g. 10.in-addr.arpa) are currently sent to the standard upstream DNS resolver (= Internet). This affects e.g. dynamic DNS updates from Windows.

### Proposed solution

I think it would be useful if SOA records for a private network address (e.g. 10.in-addr.arpa) are also to the configured private upstreams, if it is set that private PTR requests should also be sent there.
A separate option for this case would also be possible, identical to "Use private reverse DNS resolvers", only with SOA records.

**Comment by Cebeerre** [comment]
If you add the private resolver as an upstream, it works. I've tested to add this to my config in the upstreams:

```
[/13.168.192.in-addr.arpa/]127.0.0.1:1053
```

And it passed the SOA query to the upstream.

**Comment by Dennis14e** [comment]
I know this would work, but something like this:
```
[/10.in-addr.arpa/]127.0.0.1:1053
[/16.172.in-addr.arpa/]127.0.0.1:1053
[/17.172.in-addr.arpa/]127.0.0.1:1053
[/18.172.in-addr.arpa/]127.0.0.1:1053
[/19.172.in-addr.arpa/]127.0.0.1:1053
[/20.172.in-addr.arpa/]127.0.0.1:1053
[/21.172.in-addr.arpa/]127.0.0.1:1053
[/22.172.in-addr.arpa/]127.0.0.1:1053
[/23.172.in-addr.arpa/]127.0.0.1:1053
[/24.172.in-addr.arpa/]127.0.0.1:1053
[/25.172.in-addr.arpa/]127.0.0.1:1053
[/26.172.in-addr.arpa/]127.0.0.1:1053
[/27.172.in-addr.arpa/]127.0.0.1:1053
[/28.172.in-addr.arpa/]127.0.0.1:1053
[/29.172.in-addr.arpa/]127.0.0.1:1053
[/30.172.in-addr.arpa/]127.0.0.1:1053
[/31.172.in-addr.arpa/]127.0.0.1:1053
[/168.192.in-addr.arpa/]127.0.0.1:1053
```

is not as easy as clicking on a single checkbox.

**Comment by Cebeerre** [comment]
> is not as easy as clicking on a single checkbox.

You're completely right, I was just suggesting a workaround as your case is quite specific ... mostly people just adds the DNS of the router that is handling the DHCP, tipically a dnsmasq that doesn't even respond to SOA records.

@ainar-g what you think ? makes probably sense not just filtering PTR queries and directly send to the private upstream anything that is a query related to private address ranges.

**Comment by EugeneOne1** [comment]
@Dennis14e, hello again.  We've pushed the edge build, it should redirect SOA and NS requests with private domain names to the private upstreams as well as it does for PTR requests.  Could you please install it and check if it doesn't require additional domain specifications?

**Comment by Dennis14e** [comment]
@EugeneOne1 It currently looks to me as if the feature is working as expected.
All SOA/NS queries I made to private in-addr.arpa records were forwarded to the reverse DNS upstream.

**Comment by EugeneOne1** [comment]
@Dennis14e, great to hear.  We'll close this issue for now, please feel free to report another problems.
