### ISSUE TITLE
upgrades.talk4free.com is marked as malware

### ISSUE THREAD

**Issue by Dalethium** [AdguardTeam/AdGuardHome#6887]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.47

### Action

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

a standard dns reply

### Actual result

```
Server:         192.168.6.222
Address:        192.168.6.222#53

------------
    QUESTIONS:
        upgrades.talk4free.com, type = A, class = IN
    ANSWERS:
    ->  upgrades.talk4free.com
        internet address = 94.140.14.33
        ttl = 3494
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:   upgrades.talk4free.com
Address: 94.140.14.33
```

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/22735418/77366af0-9a46-4eff-98f0-dd9c53e57f02)

Although AdGuard Home actually replies with an IP address, it seems to mark the result as malware in the AdGuard Home interface. I don't think this is intended as I can't find any information on this domain being a virus online as well as the fact that it is associated with the magicJack. Magicjack is a simple VoIP dongle. If I am mistaken and this is actually malware, please let me know. But this appears to be simply associated with the magicJack software as that's the software that's making the query.

**Comment by ainar-g** [comment]
See <https://github.com/AdguardTeam/AdGuardHome/blob/master/CONTRIBUTING.md#general-recommendations>.

> Please don’t:
>
> \[…\]
>
> - file issues about a particular filtering-rule list misbehaving.  These are tracked through the [separate form for filtering issues][form].
>
> [form]:     https://link.adtidy.org/forward.html?action=report&app=home&from=github
