### ISSUE TITLE
Webserver not reachable on Setup (Almalinux 8/9)

### ISSUE THREAD

**Issue by xRuffKez** [AdguardTeam/AdGuardHome#6891]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

latest

### Action

curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v

sudo /opt/AdGuardHome/AdGuardHome -s install

sudo /opt/AdGuardHome/AdGuardHome -s start

sudo /opt/AdGuardHome/AdGuardHome -s uninstall

sudo /opt/AdGuardHome/AdGuardHome -s install

sudo /opt/AdGuardHome/AdGuardHome -s restart

ss -tunlp (shows *:3000 listening)

### Expected result

Setup reachable over Port 3000

### Actual result

Setup not reachable over Port 3000

ss -tunlp shows *:3000 listening.
Port 53 is not in use through the system.
http://ip:3000 shows unable to connect.

No firewalls active! I also doublechecked protocol e.g. http / https mixup.

### Additional information and/or screenshots

uname -a
```
Linux redacted.hostname 4.18.0-513.18.2.el8_9.x86_64 #1 SMP Sat Mar 30 06:10:41 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```

ss -tunlp
```
Netid  State   Recv-Q  Send-Q                         Local Address:Port
                 Peer Address:Port                Process
udp    UNCONN  0       0                                  127.0.0.1:323
                      0.0.0.0:*
udp    UNCONN  0       0                                      [::1]:323
                         [::]:*
udp    UNCONN  0       0          [fe80::redacted]%enp9s0:546
                         [::]:*
tcp    LISTEN  0       128                                  0.0.0.0:22
                      0.0.0.0:*
tcp    LISTEN  0       128                                     [::]:22
                         [::]:*
tcp    LISTEN  0       128                                        *:3000
                            *:*
```

**Comment by xRuffKez** [comment]
With pre configured Adguard home 
(Using AdGuardHome.yml) from a Debian Mashine, Interface is reachable.

**Comment by xRuffKez** [comment]
Tried with ```--web-addr``` too, but no luck either. Though of binding issue, but nope.

**Comment by bcookatpcsd** [comment]
```
curl -v -I http://your.ip.add.ress:3000
```

What does that return?

(windows also has curl these days if you are working from a windows box.. which would be more applicable.. ) 

Try to run curl from your workstation/desktop/laptop, whatever that may be.. 

Thank you in advance.

**Comment by xRuffKez** [comment]
> please make sure there is no \"superhelpful default block everything in\" firewall in the way as well..

As mentioned above, no firewalls are active.

```
curl -v -I http://10.0.0.2:3000
*   Trying 10.0.0.2:3000...
* connect to 10.0.0.2 port 3000 failed: No route to host
* Failed to connect to 10.0.0.2 port 3000: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.0.0.2 port 3000: No route to host
```

**Comment by xRuffKez** [comment]
How shameful... firewalld was in panic mode. I'm sorry for the inconvenience i made you @bcookatpcsd
