### ISSUE TITLE
Slow cached responses 

### ISSUE THREAD

**Issue by Dynamic5912** [AdguardTeam/AdGuardHome#6904]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Latest

### Action

N/A

### Expected result

Lower MS response times when served from cached

### Actual result

With reference to original Issue **5842** - https://github.com/AdguardTeam/AdGuardHome/issues/5842

Cached DNS replies have high MS response times when using AdGuard Web Security and Parental Control services. 

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/594ea2e2-13a6-46c2-a0cc-fdb0dd52e95b)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/6a0304c4-c173-490d-af97-6f0270b547bd)

**Comment by Dynamic5912** [comment]
Disabling services reduces back to expected response times 

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/e5e33f6e-f5d5-4977-8048-957cdf257fe5)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/8190aeab-30e7-4de1-a8bc-f00543957696)

**Comment by Dynamic5912** [comment]
What DNS servers were you testing with?

I think the issue only exhibits itself if using Unbound and going to the Root DNS servers.

**Comment by xRuffKez** [comment]
> I understand.
> 
> Without the information requested in my previous comment, I can't do much to reproduce the issue, let alone get it resolved though.

It doesn't matter, he is using root servers with his local unbound instance.
Queries served from cache should not have such high latency and upstreams are not touched when cache is served.

**Comment by Dynamic5912** [comment]
Still having this issue even with the Parental and Security options unchecked. 

Cached responses are being served with circa 10ms or more latency times.

Surely the cached responses should be served at 1ms or less?

**Comment by Dynamic5912** [comment]
I think I've found the issue. 

If I **disable** all of my blocklists, resolution returns to a low latency for new requests (as expected, since it doesn't need to parse through any blocklists) and cached responses drop to 1ms or lower - in most cases below 0.5ms - which is good!

However with blocklists **enabled**, latency for new requests is higher (expected I guess due to blocklist checking), but cached responses are now also back to 5-10ms+ response times.

So it seems that cached response are still subject to blocklist checking and therefore this increases the response time in which they are served back to clients.

I also have opportunistic caching enabled - disabling this _slightly_ reduces the response time for cached requests by 1-2ms but this could just be placebo. 

Thoughts?

**Comment by Dynamic5912** [comment]
I've tested this again to confirm and my findings are still correct. 

Is this normal behaviour?

**Comment by ainar-g** [comment]
Seems like the community moderator following the issue originally has left.

Responses are filtered, regardless of whether they're cached or not.  Simply because the response that wasn't blocked before could be blocked now, after a filter update, or vice versa.  Lowering the amount of rules in your filtering engines should help, especially if the machine in question doesn't have a very powerful CPU.

**Comment by Dynamic5912** [comment]
> Seems like the community moderator following the issue originally has left.
> 
> 
> 
> Responses are filtered, regardless of whether they're cached or not.  Simply because the response that wasn't blocked before could be blocked now, after a filter update, or vice versa.  Lowering the amount of rules in your filtering engines should help, especially if the machine in question doesn't have a very powerful CPU.

I'm running a Pi4 with 8GB RAM.

This hasn't been an issue in the past and has developed over the last 2-3 months, even using the same lists as previously averaging the same number of rules. 

I get that cached responses need filtering - but it shouldn't take 15ms or longer to serve a response back to the client.

Something is amiss here.

**Comment by ainar-g** [comment]
> This hasn't been an issue in the past and has developed over the last 2-3 months, even using the same lists as previously averaging the same number of rules. 

What is the current number of lists and rules?  And also, what is the load and how did it change over that time period?

In any case you can enable [verbose logging](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) to see where the filtering spends most of its time.

**Comment by Dynamic5912** [comment]
> > This hasn't been an issue in the past and has developed over the last 2-3 months, even using the same lists as previously averaging the same number of rules. 
> 
> 
> 
> What is the current number of lists and rules?  And also, what is the load and how did it change over that time period?
> 
> 
> 
> In any case you can enable [verbose logging](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) to see where the filtering spends most of its time.

Lists and rules:

![image](https://github.com/AdguardTeam/AdGuardHome/assets/134324737/790ca56b-4933-4a9d-b1a7-0c9d8d34e192)

Even after disabling the larger lists, the issue still persists with fewer lists running.

Will provide some logs later - what am I looking for in the log file that generates?

**Comment by ainar-g** [comment]
I'd recommend decreasing the amount of rules anyway.  After about a couple of hundreds of rules, it's all diminishing returns for most cases.

> Will provide some logs later - what am I looking for in the log file that generates?

Basically anything between the start of the query and its end, but in particular anything with `filtering:` prefix; `safe browsing:` and `parental control:` may be interesting as well, as these use TXT queries to fetch the domain hashes.

**Comment by Dynamic5912** [comment]
It's worth noting I've disabled Safe Browsing and Parental Control as these were causing resquests to spike to 200ms and upwards (cached and new requests).

Disabling it has bought response times down to around 15-20ms when cached which is still high.
