### ISSUE TITLE
AdGuardHome app for appleTV

### ISSUE THREAD

**Issue by tropicaljungle** [AdguardTeam/AdGuardHome#6907]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

For most families they don't have a 24-hrs server in house, but safe browing via internet is required.

### Proposed solution

apple TV with tvOS 17 now can act as a gateway of the home network. Could it be considered to develop an AdGuardHome app for apple TV, so that the apple TV runs as an AdGuardHome server.

**Comment by overwatch3560** [comment]
Totally right indeed that's not possible unfortunately
