### ISSUE TITLE
adguardhome: OpenWRT package missing in snapshots/packages/aarch64_cortex-a53 tree

### ISSUE THREAD

**Issue by nextgen-networks** [AdguardTeam/AdGuardHome#6918]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.42 & 0.107.48

### Action

OpenWRT package has been disappeared from aarch64_cortex-a53 device tree.

### Expected result

Install / update of package should be possible.
Imagebuilder (https://firmware-selector.openwrt.org/?version=SNAPSHOT&target=mediatek%2Ffilogic&id=bananapi_bpi-r4) should build images pith adgaurdhome package

### Actual result

No fresh install or update of AGH or image build with image builder for aarch64_cortex-a53 devices (in my case Banana Pi BPI-4) is possible.

### Additional information and/or screenshots

in fact Platform (OS and CPU architecture) is Linux, Armv8 - but this architecture is not available.

**Comment by ainar-g** [comment]
The OpenWrt package is not maintained by us, see #6115.  Please notify the package maintainers about the issue.
