### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by tolga7t** [AdguardTeam/AdGuardHome#692]
When installing, during one of the steps, there is a message that says **"Port 53 is not available for binding -- this will make DNs clients unable to contact AdGuard Home."** Putting in 5353 instead doesn't help. No matter what port I use, I get to the next page where I enter my UN and PW, then when I click next I get an error that says "Error: control/install/configure | Impossible to listen on IP:port 0.0.0.0:53 due to listen udp 0.0.0.0:53: bind: permission denied | 400" Choosing a different interface doesn't change results either. Any suggestions for a fix? Thanks.

**Comment by jslawler** [comment]
It sounds like 2 things are happening here.

1. 53 is not forwarded on your router, or
2. Both ports are being used on your system.

If you need any help with checking either of these items, let me know.

**Comment by tolga7t** [comment]
> It sounds like 2 things are happening here.
> 
> 1. 53 is not forwarded on your router, or
> 2. Both ports are being used on your system.
> 
> If you need any help with checking either of these items, let me know.

I am a complete noob, and would love a help with both of those!

**Comment by ameshkov** [comment]
What device/OS are you trying to install AGH on?

**Comment by tolga7t** [comment]
I'm trying to install it on a Raspberry Pi 3

**Comment by ameshkov** [comment]
@tolga7t are you running AGH with `sudo`?

**Comment by tolga7t** [comment]
How would I go about seeing that?

I setup a pi by following this directly -
https://projects.raspberrypi.org/en/projects/raspberry-pi-setting-up

And then I followed this exactly until I saw the error messages. -
hihttps://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi

**Comment by ameshkov** [comment]
`bind: permission denied ` -- this error means that AGH is running under a user with limited privileges.

If you were running all AGH commands with sudo, this wouldn't be the case. It means you should type your commands starting with `sudo`: `sudo ./AdGuardHome`

**Comment by tolga7t** [comment]
Got it, thanks, I will uninstall and try again later today, making sure to
use sudo for my commands.

**Comment by tolga7t** [comment]
Since I followed this guide word for word (
https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi) is there any
command there that *should *be run under sudo? I used sudo for most
commands, as the guide told me to.

**Comment by ameshkov** [comment]
Well, `sudo ./AdGuardHome -s install` should've been enough. Do you still have the issue?

**Comment by tolga7t** [comment]
Unfortunately I'll have to wait until I go home to check, about 10 hours
from now :\

**Comment by tolga7t** [comment]
> 
> 
> Well, `sudo ./AdGuardHome -s install` should've been enough. Do you still have the issue?

yes I uninstalled and re-installed using sudo numerous times, but I still get the same error when I'm at the welcome page on the web interface. any reason why I may be getting this error?

**Comment by ameshkov** [comment]
It's really hard to diagnose properly:(

The error text means that AGH is running without `root` privileges (maybe under a different user?), but I can't say why.

Please execute `ps aux | grep AdGuardHome` and check under which user it is running.

**Comment by tolga7t** [comment]
This is what I get what I run that:
root 4952 0.0 1.6 806104 15860 ? Ssl Apr03 1:15
/home/pi/AdGuardHome/AdGuardHome -s run
pi 15478 0.0 0.0 4372 544 pts/0 S+ 17:10 0:00 grep --color=auto AdGuardHome

if that means anything, I can try something, otherwise no worries since
I've got pihole working now.

**Comment by ameshkov** [comment]
It looks as if it is running under root after all.

Well, I am out of ideas, it can't be happening. Are you sure the error is "permission denied" and not smth like "the address is already in use"?

**Comment by tolga7t** [comment]
There are two errors. The first error is during Step 2 of 5 during the
Welcome screen, and it says*:*


*"Port 53 is not available for binding -- this will make DNS clients unable
to contact AdGuard Home" *

That error doesn't stop me from clicking Next and going to Step 3. I input
a username and password, but when I click to go to Step 4, I get the second
error that says:


*"Error: control/install/configure | Impossible to listen on IP:port
0.0.0.0:53 <http://0.0.0.0:53> due to listen udp 0.0.0.0:53
<http://0.0.0.0:53>: bind: permission denied | 400" *

When I see this error, I'm kicked back to Step 2 (where you identify
interface, port etc)
