### ISSUE TITLE
Parental Control active but not selected

### ISSUE THREAD

**Issue by maurxce** [AdguardTeam/AdGuardHome#6926]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

Version:  v0.107.44

### Action

I have three examples, two of which I'm pretty certain have to do with AdGuard Home:

1. When visiting some websites
2. When watching YouTube, a lot of videos become unavailable
4. I couldn't watch videos on Crunchyroll anymore

### Expected result

1. I can visit the website
2. I can watch all YouTube videos
3. I can watch videos on Crunchyroll

### Actual result

1. Popup saying that Parental Control is enabled
2. The restricted mode is turned on "by a network administrator"
3. Video wouldn't play, I got told to download the App instead

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/91284394/dcf10445-7432-4776-b534-dfc635d52313)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/91284394/cbf44df5-0397-4581-ba37-1fe66a6bafa8)

I sadly don't have any screenshots of the website popup or Crunchyroll issue, those two only happened once or twice so far. The YouTube issue is occurring multiple times per day

The issue does disappear briefly once I enable and then disable Parental Control

**Comment by Dynamic5912** [comment]
What DNS servers are you using?

**Comment by maurxce** [comment]
Upstream:
- https://dns10.quad9.net/dns-query
- 94.140.14.15

**Comment by maurxce** [comment]
> That last one is AdGuards Family DNS. This enforces Safesearch by DNS.

Oh... Not sure when or why I decided to add that. This seemed to fix my issue!
Thanks for helping ^^
