### ISSUE TITLE
Resolve local network names

### ISSUE THREAD

**Issue by lbreggi** [AdguardTeam/AdGuardHome#694]
Hi! I will be nice if Adguard could resolve local names or has de capability to set a domain that can be redirected to a local server

**Comment by ibksturm** [comment]
there is still this option... look at the manual 👍

[/yourdomaine/]aaa.bbb.ccc.ddd

**Comment by lbreggi** [comment]
many thanks @ibksturm !! I will try and see how it works. do you know If I set my local domain in this way the list of my local computers will show the names instead of IPs? I have some already set in Hosts file but for the ones under DHCP is hard to set. thanks!!!

**Comment by ameshkov** [comment]
I guess this is a duplicate of #461 

Currently, you can add custom entries to your custom filtering rules (smth like `192.168.0.1 host.local`)

**Comment by lordvalium** [comment]
> many thanks @ibksturm !! I will try and see how it works. do you know If I set my local domain in this way the list of my local computers will show the names instead of IPs? I have some already set in Hosts file but for the ones under DHCP is hard to set. thanks!!!

did that work for you?
