### ISSUE TITLE
AdGuardHome didn't block any ads

### ISSUE THREAD

**Issue by EllisXillia** [AdguardTeam/AdGuardHome#6943]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.48

### Action

![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/7bfe7021-8b63-400d-ac92-5e594a4fd350)

### Expected result

Block ads

### Actual result

doesn't block any ads

### Additional information and/or screenshots

previously, i install AdGuardHome at Unraid via custom bridge. but didn't because i installed everything on single machine, now i install it on Raspberry Pi 3 and still doesn't block any ads. I use TP-Link AX5400 as a router

![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/82ee70ae-eb63-4027-b4cb-bf001ddb230c)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/01391674-34ac-47d3-9206-56bfb7940c97)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/6e69d0fe-44fc-487a-9248-181ec70ab04c)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/1c98af94-4c9c-4cea-9ee6-dac54aeafc79)

i tried to follow instruction from other thread, but it didn't work like this 
https://github.com/AdguardTeam/AdGuardHome/issues/5132
https://github.com/AdguardTeam/AdGuardHome/issues/4256

**Comment by xRuffKez** [comment]
Use Hagezi Pro, OISD Big and Hagezi TIF, and most of them are gone. Some stay, because ads are delivered from same domain like the site itself. For that i recommend uBlock Origin.

```
https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/adblock/pro.txt
https://big.oisd.nl
https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/tif.txt
```

And for phishing i also recommend my port:
```
https://raw.githubusercontent.com/xRuffKez/Phishfort-Domain-Lists/main/phishfort_full_adguardhome.txt
```

**Comment by EllisXillia** [comment]
> Use Hagezi Pro, OISD Big and Hagezi TIF, and most of them are gone. Some stay, because ads are delivered from same domain like the site itself. For that i recommend uBlock Origin.
> 
> ```
> https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@main/adblock/pro.txt
> ```
> 
> ```
> https://big.oisd.nl
> ```
> 
> ```
> https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/tif.txt
> ```
> 
> And for phishing i also recommend my port:
> 
> ```
> https://raw.githubusercontent.com/xRuffKez/Phishfort-Domain-Lists/main/phishfort_full_adguardhome.txt
> ```
> 
> Also double check if AdguardHome is updating the lists automatically.

hello, thanks for give me advice. last one really have big list, however none of them be able to block ads site link Speedtest and Kompas.com. already added everything you said on my dns blocklist
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/68da8cfc-16e1-4d9e-a150-f53c2da5ac54)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/c0f14c19-25fc-46e9-97af-f55124c60cd9)

but, they able to block some tracking site from baidu and from torrent tracker 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/a28e5019-6c12-4fa0-8d8f-5551439c924d)
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/328bf571-9113-4114-b35e-92e8b13768f7)

**Comment by xRuffKez** [comment]
Maybe you have DNS leak? You can check it with the site https://dnscheck.tools

And for the Hagezi List: The Ultimate List you use is enough. You dont need to add Pro++, because Ultimate is a list where it is included.

**Comment by EllisXillia** [comment]
> Maybe you have DNS leak? You can check it with the site https://dnscheck.tools
> 
> And for the Hagezi List: The Ultimate List you use is enough. You dont need to add Pro++, because Ultimate is a list where it is included.
> 
> Is this issue only on your Windows PC or do other devices also show so many ads? Be sure no VPN or Proxy is evading your DNS.
> 
> If you can firewall on your router, block Port 53 TCP/UDP. Not necessary, but it is the last mile to block DNS leaks.
> 
> Ensure you don't have setup "secure dns" or such settings in your browsers, they might use other DNS servers.
> 
> And the Adaway and Adguard Lists are in every Hagezi list included.
> 
> If the last phishfort list is too big, there is also a small (hotlist):
> 
> ```
> https://raw.githubusercontent.com/xRuffKez/Phishfort-Domain-Lists/main/phishfort_small_adguardhome.txt
> ```

hey, i'm sorry late to reply. i have been busy in last 2 days

> Is this issue only on your Windows PC or do other devices also show so many ads? Be sure no VPN or Proxy is evading your DNS.
AGH doesn't block any ads including phones and smart TVs. I have to tell you, this problem is not only in AGH but PiHole has same issue on my network. i only enable browser cloundflare dns on max protection settings on firefox

> If you can firewall on your router, block Port 53 TCP/UDP. Not necessary, but it is the last mile to block DNS leaks.
i added 8.8.8.8 and 1.1.1.1 on AX5400 but doesn't work

> Ensure you don't have setup "secure dns" or such settings in your browsers, they might use other DNS servers.
is Max Protection DNS setting on Firefox are included ? should i enable or not ?

> And the Adaway and Adguard Lists are in every Hagezi list included. If the last phishfort list is too big, there is also a small (hotlist):
i don't really have problem with the size, but most of dns blocklist i added doesn't block any ads 

>Maybe you have DNS leak? You can check it with the site https://dnscheck.tools/
how you tell if this leaks or not ? i don't have any experience with this. 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/30818281/a4213493-9ca8-4a51-8203-67c400937db1)

**Comment by overwatch3560** [comment]
@EllisXillia what kind of ads does your tv/phone not block?

**Comment by GusAntoniassi** [comment]
In my case it was simply the "Block domains using filters and hosts files" option that was unchecked, under general settings.

**Comment by cyb3rMatt3r** [comment]
Hi. Have you found a solution to this problem?

**Comment by Blockr22** [comment]
I was having same issue with adguard home not blocking more than 30% ads in [adblock test](https://d3ward.github.io/toolz/adblock). I checked with https://www.dnscheck.tools/ for dns leaks and seems like i had dns leak on my windows laptop and macbook but was working normally on my iphone's and no dns leak detected on iphone. So, to fix this issue i had to disable ipv6 of my wifi network and Adguard home working normally now.

**Comment by fbimm** [comment]
I think i'm a bit late, but I had the same problem before. I solved it by just set my router's primary AND secondary DNS to my Adguard Home. If you set your secondary DNS to Google or Cloudflare or anything else, AGH somehow didn't work properly.

**Comment by lipe123** [comment]
> I think i'm a bit late, but I had the same problem before. I solved it by just set my router's primary AND secondary DNS to my Adguard Home. If you set your secondary DNS to Google or Cloudflare or anything else, AGH somehow doesn't work properly.

Thanks man!!

I was struggling with ads not being blocked and it was the same issue, I had my adguard home server as primary dns but then I set quad9 as secondary dns.
