### ISSUE TITLE
Update banner still there after update to 0.94

### ISSUE THREAD

**Issue by GOODTESTA** [AdguardTeam/AdGuardHome#695]
Hello, guys. The banner of the update notification still there after I update AdGuardHome from 0.93 to 0.94. Is this kind of bug....

![image](https://user-images.githubusercontent.com/35817374/55301940-9f2bdb80-5471-11e9-8611-9102cd762aeb.png)

**Comment by ameshkov** [comment]
Duplicate of #660

This is a UI bug, it'll be gone in v0.95.
