### ISSUE TITLE
No connection to my Miele dryer & Buderus oil heater (web km200)

### ISSUE THREAD

**Issue by toxicman2002** [AdguardTeam/AdGuardHome#696]
Hello,

i've installed Adguard Home 0.94 on my Raspberry Pi 3+ (OS Raspbian). It works well, when i change the DNS- Server in my Fritz!Box 7590 to the Adguard-Server. I have access to my Somfy Tahoma but i've no connection to my Buderus Oil-Heater OUTSIDE my Lan. Normaly, the Oilheater connects to wa2.mz36-qrmzh6.bosch.de and i can access the heater with the Buderus-App "MyDevice".

The ports 5222 & 5223 are open (is needed say Buderus).

Insinde my LAN, i can access the Heater. Adguard block something i think.

Normally, my Miele-Dryer connects to their server (Miele.com) and with the Miele@home-App i can see the status of the dryer. But when i set the DNS to my Adguard-Server is no connection inside and outside my Lan.

I've unblockrules to both server but this dosn't work. Any ideas why my Somfy Tahoma works and Miele & Buderus not?

What can i do?

PS: My ISP is Deutsche Telekom.
PPS: Sorry for my bad english ;-)

Thanks, Oli

**Comment by szolin** [comment]
Hello!
Can you attach logs?  You can use this command to create a log file:

`grep AdGuardHome /var/log/daemon.log >aghome.log`

I'll look for requests to miele.com and wa2.mz36-qrmzh6.bosch.de there.  Or you can try to find the necessary information by yourself and send us only the relevant lines.

Also, it' would be better if you use `verbose: true` setting in .yaml config file.

**Comment by toxicman2002** [comment]
Hello,

here is  a little log from Bosch. Later, i csn give you more. Im at work now... The miele dryer is off at the moment, i'll turn on him after work.

[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/3034535/log.txt)

**Comment by toxicman2002** [comment]
Hi,
here are the logs from bosch and miele. I hope,  it can help you to find the failure..

Thanks, Oli

[miele+bosch.txt](https://github.com/AdguardTeam/AdGuardHome/files/3035555/miele%2Bbosch.txt)

**Comment by ameshkov** [comment]
@toxicman2002 does it work okay when you disable protection completely in AGH?

Also, you could try to find the problematic rule by unblocking domains one by one in the query log.

**Comment by toxicman2002** [comment]
Hi ameshkov,

i disabled AGH and its's still the same. No connection with bosch outside my lan. Can it be raspian? Its a brand new clean installaltion. Shouldni unblock with "@@||wa2-mz36-qrmzh6.bosch.de^" or what do you mean?

**Comment by ameshkov** [comment]
If the issue is there even when AGH is disabled, this might be caused by the upstream you're using.

Try using your ISP's DNS address instead of Cloudflare DNS

**Comment by toxicman2002** [comment]
That doesn't work :-(. I'va added my DNS from my ISP in the "Upstream DNS"-section and in the " bootstrap DNS"-section.

I don't understand why all other work fine but miele and bosch not :-((

**Comment by ameshkov** [comment]
> I'va added my DNS from my ISP in the "Upstream DNS"-section and in the " bootstrap DNS"-section.

Added or replaced? You should try using just your ISP's DNS.

> I don't understand why all other work fine but miele and bosch not :-((

Is it possible to somehow get the logs from these devices?
