### ISSUE TITLE
log problem

### ISSUE THREAD

**Issue by PDSB001** [AdguardTeam/AdGuardHome#6966]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

107.48

### Action

l find when other devices was used
zh-cn:连接此路由的其他设备进行DNS查询

### Expected result

the devices can find ip and log will be write

### Actual result

device can find ip but the action isn't in log

### Additional information and/or screenshots

I use the Openwrt 21.02,but isn't ipk

**Comment by EugeneOne1** [comment]
Hello, @PDSB001.  Which log do you mean exactly?  If you've installed AdGuard Home as a service via script, it usually uses the operating system's service manager log, which AFAIK can be accessed on OpenWRT with `logread -e AdGuardHome`.  You can also specify a log file, see [FAQ](https://adguard-dns.io/kb/adguard-home/faq/#verboselog).

If it's "Query Log", check if it's enabled in "Settings".  If it is, please collect the above verbose log and send it to devteam@adguard.com.  Thank you.
