### ISSUE TITLE
AGH crashes/hangs on Pi Zero 2W regularly - Any log or statistics setting beyond 24 hours

### ISSUE THREAD

**Issue by HVR88** [AdguardTeam/AdGuardHome#6972]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv6

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

 v0.107.48

### Action

AGH crashes at some seemingly random point in time, apparently due to excessive log information. Either Query Logs or Statistics, it's not obvious. This last hang, as described and pictured below, was with Logs set to 24hr and Stats set to 7 days.

### Expected result

AGH to remain active and running perpetually

### Actual result

AGH crashes and prevents entire network from resolving domains every couple of days.

The only resolution is to reboot AGH, easiest by cutting power to the RPi.

### Additional information and/or screenshots

I ran AGH in Docker on a dual Xeon server (Unraid) for a few weeks and never experienced such an issue. But running on a homelab server isn't a sustainable practise as resetting or restarting such a server would then impact the entire network.

You can see the moment it stopped responding to traffic in the image just after 18:08

![image](https://github.com/AdguardTeam/AdGuardHome/assets/33399216/4089df8b-18d9-45aa-94ba-e324ae7861b4)

I'd love to capture some additional info, but there's nothing I can find in the UI to enable any kind of debug logging.

**Comment by EugeneOne1** [comment]
Hello, @HVR88.  I'm not sure how exactly have you installed AdGuard Home on Raspberry Pi.  The script mentioned in the issue installs the native version of the app, and the configuration file should by default appear in the same directory as the binary.  On Linux script by default puts it into `/opt/AdGuardHome/`, don't forget stopping the service before editing the `AdGuardHome.yaml`.

The docker images, which aren't recommended on low-spec machines like older versions of Raspberry Pi, are using mounted volumes for configuration and working directories.

To configure the verbose logging, use [this](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) guide.  You may send it to `devteam@adguard.com` with the issue number in subject.

**Comment by HVR88** [comment]
It's installed as per the RPi instructions on AGH download page - Pi running lite Raspian, originally by SSH to the Pi and then installing AGH.

I only mentioned that the UI contained no debug info, not that I had gone back with SSH and rooted around the filesystem looking for files or rerunning the service with different options.

I'll take another look at this when I'm able to move to new hardware, I just dont have the bandwidth at this time and I've removed the AGH deployment as it's just not stable enough to be on the network on a Pi Zero2 right now.

**Comment by HVR88** [comment]
Now running on Pi4b and so far so good after approximately 48 hours. Access to the webUI and DNS queries are definitely improved, with average access time around 24ms. So far no hangs nor other unexpected behavior.
