### ISSUE TITLE
 Parental control protocol is empty

### ISSUE THREAD

**Issue by ghost74de** [AdguardTeam/AdGuardHome#6973]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.48

### Action

In the overview I see blocked sites in parental controls but when I click on the log it is empty. If I delete the log it works again for a few days and at some point I have the same problem

### Expected result

the locked pages and which device tried to open them

### Actual result

nothing found
<img width="1196" alt="Bildschirmfoto 2024-05-06 um 09 07 26" src="https://github.com/AdguardTeam/AdGuardHome/assets/94167816/12265a85-0284-40a6-b9cc-89e66fcbe747">

**Comment by EugeneOne1** [comment]
Hello, @ghost74de, and thanks for the report.  We can't reproduce the issue, could you please collect a [verbose log](https://adguard-dns.io/kb/adguard-home/faq/#verboselog), when the issue appears again?  You may send it to `devteam@adguard.com` with `#6973` in the subject.
