### ISSUE TITLE
the ‘’Answer‘’ field of querylog.json encrypted

### ISSUE THREAD

**Issue by Somalia0932** [AdguardTeam/AdGuardHome#6974]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Why is the ‘’Answer‘’ field of querylog.json encrypted, which prevents me from collecting log data properly. Can it be changed to non encrypted?

### Proposed solution

Change the ‘’answer‘’ field of querylog.json to non encrypted

**Comment by EugeneOne1** [comment]
Hello, @Somalia0932.  The thing is, they're not really encrypted, they're Base64-encoded.  You can literally access the data in the `"Answer"` field with any Base64 decoder you can find online.  The data is also packed and possibly compressed to reduce the size of the query log files, but the format of `querylog.json` files isn't designed to be human readable anyway.  Accessing query log data with third-party tools is beyond the scope of this project.
