### ISSUE TITLE
badfilter modifier not disabling rule which contains dnsrewrite modifier

### ISSUE THREAD

**Issue by gdzevo** [AdguardTeam/AdGuardHome#6979]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.48

### Action

After reviewing  https://github.com/AdguardTeam/AdGuardHome/issues/5304 discussion I've tried to disable bad dnsrewrite rule from the block-list with no luck.

Add following rules in "Custom filtering rules"
```
||api2.branch.io^$dnsrewrite=127.0.0.1
||api2.branch.io^$dnsrewrite=127.0.0.1,$badfilter
```

### Expected result

The second rule should disable the first one.

### Actual result

dnsrewrite rule is still active

### Additional information and/or screenshots

Following rule is added to "AdGuard DNS filter" list and it breaks some apps deep-linking functionality and could not be disabled because of this issue.
For now the only option is to completely disable "AdGuard DNS filter" list.
```
||api2.branch.io^$dnsrewrite=127.0.0.1
```

**Comment by harelamir** [comment]
i have a similar prooblem
https://github.com/AdguardTeam/AdguardFilters/issues/189245

**Comment by gdzevo** [comment]
I've found a workaround for my issue, m.b. it could help in your case as well.
The more major issue https://github.com/AdguardTeam/AdGuardHome/issues/5304 stuck for almost 2 years, so it doesn't look like Adguard team prioritize such issues at all.
```
||api2.branch.io^$important,dnsrewrite=api2.branch.io
```

**Comment by harelamir** [comment]
thank you!

**Comment by krystian3w** [comment]
Try skip second `$`:

```adb
||api2.branch.io^$dnsrewrite=127.0.0.1
||api2.branch.io^$dnsrewrite=127.0.0.1,badfilter
```

**Comment by gdzevo** [comment]
@krystian3w I've just verified your suggestions with minor modifications (AdGuard DNS filter list rewrites it to 0.0.0.0) and that's what I got:

```||api2.branch.io^$dnsrewrite=0.0.0.0,badfilter```
badfilter flag was ignored as it was described in this issue

```@@||api2.branch.io^$dnsrewrite=0.0.0.0```
this one fixed the issue and it is better than solution I've proposed because it eliminates one additional request

thank you for your suggestions, I will replace my workaround

**Comment by krystian3w** [comment]
I was mainly concerned about the incorrect use of the modifier, we do not duplicate `$`, The notation as in the guide/Wiki makes sense when the network rule does not have a limiting `$something`.
