### ISSUE TITLE
Viewable Data API

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#698]
This relates to #691 in respect to the amount of viewable data being requested by users.

As the AGH project proceeds, users are requesting large amounts of data to be displayed in a multitude of forms.
To deal with future ambiguous requests of viewable data I recommend some form of api to deal with these requests and allow users to create and export their own data.

**Comment by ameshkov** [comment]
Have you checked this?
https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

**Comment by jslawler** [comment]
> Have you checked this?
> https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

I have now - That should do the trick just fine. Now to push that information on to the rest of the population. ;)
