### ISSUE TITLE
DNS Average Processing Time

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#699]
This relates to #691 in response to discussions about how to better handle DNS average processing time readout.

> I think a trimmed mean should come into play for the average processing time, instead of simply the mean of all DNS requests.
> 
> Basically, trim the top and bottom (for theories sake)20% of DNS request time data and give the mean on the remainder. Extra thought will need to be put into this to factor in all the possible outcomes though.

It's more likely that you won't just be able to trim the top and bottom percentage of DNS request time as there will be other factors that likely come into play to make the calculation accurate per each user. Further discussion will be needed.

**Comment by ameshkov** [comment]
Wouldn't it be better to simply calculate more than avg?

For instance, we could calc: min, max, stddev, and median values.

**Comment by jslawler** [comment]
> Wouldn't it be better to simply calculate more than avg?
> 
> For instance, we could calc: min, max, stddev, and median values.

It would depend on how you present it. If the end goal is to have a product that's user friendly I'd want the processing time displayed as a 1 line number as it is already.
All the extra calculations could either be provided in the hover over for the processing time, or could go towards a calculation targetted towards a more accurate 1 line number.

You could always take an alternative route and not present it as a number, but as a line graph over a 24 hour period, where x = Processing time in ms and y = interval in 24hr period, customisable by the user. 
This could be presentable on the dashboard in an expandable box where when expanded would display the graph, and when collapsed would display the calculated query time from the issue topic.

I personally like the latter option as it would show me instantly whether I have any issues on my network, and it's quite user friendly by providing a snapshot of what's going on rather than requiring users to interpret data.

Thoughts?

**Comment by adrianh-za** [comment]
Maybe you could separate the "Adguard security web service" time into separate value as well?
