### ISSUE TITLE
Random upstream dns appears in statistics

### ISSUE THREAD

**Issue by rclarsfull** [AdguardTeam/AdGuardHome#7000]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

Other (please mention in the description)

### AdGuard Home version

Version:  v0.107.48

### Action

not sure maybe it was an update of the docker container

### Expected result

nothing should change

### Actual result

An random DNS server appears in my upstrem dns List. I can´t tell what it is. The first one:
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19623214/a0117775-bd10-44a3-999e-6b2b2de7ac19)
This are my settings: 
![image](https://github.com/AdguardTeam/AdGuardHome/assets/19623214/97d74a57-fc4f-4d45-9a3a-33d082f76de8)

Can this happen due to an update? The setting for the kind of access to the upstream dns servers was changed from parallel to automatic too.
Or should I be concerned that my network is compromised?

**Comment by rclarsfull** [comment]
My setup: The docker host is the dns server that is served to any device by my pfsense dhcp server

**Comment by Dynamic5912** [comment]
Router IP address?

**Comment by rclarsfull** [comment]
No this address Isn't in my local network. I have an 192.168.1.0 network.

**Comment by catfluoride** [comment]
That address is private, i.e., it only belongs to LAN. Isn't that the ip address of your container i.e., the actual internal ip of your ADGH instance?

**Comment by ainar-g** [comment]
This is likely the automatically detected address for private rDNS.  See *Settings → DNS settings → Private reverse DNS servers.*

**Comment by rclarsfull** [comment]
> This is likely the automatically detected address for private rDNS. See _Settings → DNS settings → Private reverse DNS servers._

Thx, this was it.👍
