### ISSUE TITLE
Ad blocking very inconsistent.

### ISSUE THREAD

**Issue by FrederikSchack** [AdguardTeam/AdGuardHome#7001]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.48

### Action

I have AGH running, added all the 14 general block lists and it's the only DNS for a broad range of devices in our house. 

### Expected result

Ads should be broadly blocked.

### Actual result

Ads seems to appear on most devices, most of the time.

My devices fails most tests in the ad block tester (.com), the score is 30 out of 100.

### Additional information and/or screenshots

AGH in Docker on AlpineLinux VM
Router only has AGH as DNS
The tested Windows Computers have been ipconfig /dnsflush, restarted and verified that they only have AGH as DNS and have been running for some days.
I've made a rewrite from home.lan to 192.168.1.52.
"home.lan" is a local domain I've never used before using AGH

**Comment by ainar-g** [comment]
Please follow the [FAQ entry](https://adguard-dns.io/kb/adguard-home/faq/#doesntblock).  It is most likely that there are other DNS servers configured either on the computers, the browsers (which have separate DNS settings these days), or both.
