### ISSUE TITLE
Version 0.107.49 casues error during initalize

### ISSUE THREAD

**Issue by AnonymousX86** [AdguardTeam/AdGuardHome#7013]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.49

### Action

Simply start Docker container, go to initialize page and try to fill forms.

### Expected result

Proper AdGuard Home initialize.

### Actual result

Getting error:
```plaintext
Error: control/install/configure | dnsServer.Prepare: preparing internal proxy: validating private RDNS upstreams: no upstream specified | 500
```

### Additional information and/or screenshots

![Screenshot 2024-05-21 at 19-12-45 Setup AdGuard Home](https://github.com/AdguardTeam/AdGuardHome/assets/53279236/e2c18bb3-af59-4952-9f66-104f8f9aacbe)

Installing previous version `0.107.48` resolves the issue.

**Comment by gidder** [comment]
Probably the same issue, but with already deployed AdGuardHome after update to 0.107.49.
The server won't start, and I see these lines repeating in the logs:
```
2024/05/21 19:48:20.212312 [info] AdGuard Home, version v0.107.49
2024/05/21 19:48:20.215945 [info] tls: using default ciphers
2024/05/21 19:48:20.218690 [info] safesearch default: disabled
2024/05/21 19:48:20.225038 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2024/05/21 19:48:20.225245 [info] auth: initialized.  users:1  sessions:0
2024/05/21 19:48:20.225378 [info] AdGuard Home updates are disabled
2024/05/21 19:48:20.225559 [info] web: initializing
2024/05/21 19:48:20.376319 [error] querylog: closing: flushing log buffer: nothing to write to a file
2024/05/21 19:48:20.376330 [fatal] dnsServer.Prepare: preparing internal proxy: validating private RDNS upstreams: no upstream specified
```

**Comment by MRobi1** [comment]
Seeing the same issue both from a new install and from an update

**Comment by PiuPiuson** [comment]
Same here in an existing setup. Downgrading fixed it.

**Comment by silentkiller88** [comment]
Same here in existing docker setup, doNgrading fixed the issue indeed

**Comment by geriguy43** [comment]
Just wanted to confirm, I have same issue,
AdGuard won't start after the update (automatic update by whatchtower.)

Synology NAS, Adguard in a Docker container, redirected to an own IP address.

Needed to roll back to the latest stable version which solved the problem.

**Comment by nickwilkie** [comment]
Me too, just happened to do an update a few minutes ago and my network went down, downgrading fixed. Using adguard in a docker compose on a proxmox vm.

**Comment by jerheij** [comment]
Same here, the latest version caused the error and prevented it to start. Downgrading to `v0.107.48` fixed it.

**Comment by middreks** [comment]
Managed to get it up and running by setting `use_private_ptr_resolvers` to false in AdGuardHome.yaml config.
While this is not ideal, for a temp solution it could help.

**Comment by solidgonk** [comment]
LXC from helper-scripts deployed fine, but Docker deployment failed with this error.

**Comment by Tommatheussen** [comment]
> Managed to get it up and running by setting `use_private_ptr_resolvers` to false in AdGuardHome.yaml config. While this is not ideal, for a temp solution it could help.

If this helps for the Devs: I never set that flag (from UI) before, now I just toggled it on and back off from the UI (in version 0.107.48) and the latest version correctly boots up now

**Comment by Xazziri** [comment]
More info: 
I have 3 docker instances running of which 2 failed like described. These two show, under the Private reverse DNS servers heading: AdGuard Home could not determine suitable private reverse DNS resolvers for this system. The third (not docker but podman) did not fail and has a different message: By default, AdGuard Home uses the following reverse DNS resolvers: "10.89.2.1:53".
Setting use_private_ptr_resolvers to false in AdGuardHome.yaml config for the 2 that failed did fix the problem, but enabling local resolving on the docker hosts also works.
I would propose to check if AdGuard Home can determine suitable private reverse DNS resolvers for this system. If not, set use_private_ptr_resolvers to false.

**Comment by jerheij** [comment]
> More info: I have 3 docker instances running of which 2 failed like described. These two show, under the Private reverse DNS servers heading: AdGuard Home could not determine suitable private reverse DNS resolvers for this system. The third (not docker but podman) did not fail and has a different message: By default, AdGuard Home uses the following reverse DNS resolvers: "10.89.2.1:53". Setting use_private_ptr_resolvers to false in AdGuardHome.yaml config for the 2 that failed did fix the problem, but enabling local resolving on the docker hosts also works. I would propose to check if AdGuard Home can determine suitable private reverse DNS resolvers for this system. If not, set use_private_ptr_resolvers to false.

I wonder if it wouldn't be better to disable the feature by default unless specifically disabled. Reverse DNS is, as far as I am concerned, a more advanced feature. Especially when talking about a system primarily being used for ad, and other malicious crap, blocking.

**Comment by thepod7** [comment]
I have set use_private_ptr_resolvers to false on both of my containers and the systems will still not load, they continue to fail with this error:

adguardhome_2  | 2024/05/22 11:26:28.013219 [fatal] dnsServer.Prepare: preparing internal proxy: validating private RDNS upstreams: no upstream specified

My only fix was to downgrade - adguard/adguardhome:v0.107.48

I should add that I am also running unbound along with adguard

**Comment by jerheij** [comment]
> I have set use_private_ptr_resolvers to false on both of my containers and the systems will still not load, they continue to fail with this error:
> 
> adguardhome_2 | 2024/05/22 11:26:28.013219 [fatal] dnsServer.Prepare: preparing internal proxy: validating private RDNS upstreams: no upstream specified
> 
> My only fix was to downgrade - adguard/adguardhome:v0.107.48
> 
> I should add that I am also running unbound along with adguard

Have you stopped the container, updated the values and then started the containers? I read somewhere that if you do it while AGH is still running it might change it again.

**Comment by thepod7** [comment]
I have stopped the containers, even went as far as restarting the Pi's they are running on - as mentioned the only solution was to force the systems back to v0.107.48

**Comment by ainar-g** [comment]
Thank you all for the report.  We have reproduced the error and working on a fix.

**Comment by EugeneOne1** [comment]
Hello @AnonymousX86 and everyone else.  We've just pushed the edge build that should fix this to the Docker Hub.  Could you please give it a try?  We'll include this fix into the upcoming release if it fixes the problem.

**Comment by Liziloo** [comment]
> Hello @AnonymousX86 and everyone else. We've just pushed the edge build (`v0.108.0-a.908+a030dd45`) that should fix this to the Docker Hub. Could you please give it a try? We'll include this fix into the upcoming release if it fixes the problem.

Worked for me! Thank you.

**Comment by ItsMelody** [comment]
Had this same issue. Gave me this error

> dnsServer.Prepare: preparing internal proxy: validating private RDNS upstreams: no upstream specified

Forcing adguard/adguardhome:v0.107.48 seems to have fixed the issue.

**Comment by EugeneOne1** [comment]
@ItsMelody, could you please try the `adguard/adguardhome:edge` version?  It should fix the issue as well.

**Comment by doedelgit** [comment]
> @ItsMelody, could you please try the `adguard/adguardhome:edge` version? It should fix the issue as well.

I just tried this and it's working fine for me while it failed before on 0.107.49.

**Comment by ItsMelody** [comment]
> @ItsMelody, could you please try the `adguard/adguardhome:edge` version? It should fix the issue as well.

Works!

**Comment by EugeneOne1** [comment]
Thank you all for testing.  We're closing this issue for now, the release with the fix is coming soon.

**Comment by EugeneOne1** [comment]
FYI, [v0.107.50](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.50) is released now.
