### ISSUE TITLE
Request forbidden after upgrade to 0.107.49

### ISSUE THREAD

**Issue by tigermick** [AdguardTeam/AdGuardHome#7014]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.49

### Action

Hi,
With 0.107.48 on my server, all work fine.
After 0.107.49 update successfully, I don't know why but my adguardhome server address forced with https and I have a forbidden error request if I try to access to web interface ... 
In my resolv.conf, I have my Adguardhome server address and if I change for an external DNS Server, then all work fine and I can access to my web interface of my adguardhome server ...
Do you have an idea, why 0.107.49 has this problem please ?

### Expected result

I 'd rather to update my adguardhome server

### Actual result

But now, my adguardhome server crashed

**Comment by ainar-g** [comment]
What do you see in AdGuard Home's logs?  Enabling [verbose logging](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) would help as well.

**Comment by tigermick** [comment]
> What do you see in AdGuard Home's logs? Enabling [verbose logging](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) would help as well.

I downgraded to 0.107.48 ... 
I have to upgrade again and try to have more information about this problem ?

**Comment by tigermick** [comment]
I am just ugrading again with command line and I can see the lastest version is 0.107.50 and no problems now ...
Thank you
