### ISSUE TITLE
Um.. what is with the cache? (107.50 related?)

### ISSUE THREAD

**Issue by bcookatpcsd** [AdguardTeam/AdGuardHome#7024]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

107.50

### Action

10:08:01 someone asked for www.apa.org from external IP via DoH got an answer ttl set to 600

10:09:10 someone asked for www.apa.org from internal ip via 53/udp got an answer ttl set to 600

? 

### Expected result

both services would use the same cache? 

### Actual result

seems to use different cache?

### Additional information and/or screenshots

10:08:01
![image](https://github.com/AdguardTeam/AdGuardHome/assets/55087301/e066086e-0b3c-4097-a898-7a6c2bf7fff5)

10:09:10
![image](https://github.com/AdguardTeam/AdGuardHome/assets/55087301/70869341-574a-4c79-b9f4-20050367f27b)

**Comment by ainar-g** [comment]
These have two different types: `A` and `HTTPS`.  And please use the Discussions for questions and not the issue tracker.

**Comment by bcookatpcsd** [comment]
10:08:01
![image](https://github.com/AdguardTeam/AdGuardHome/assets/55087301/0dd2572c-9b70-47a1-8a35-995dfeba203b)
Looks like an A record request

10:09:10
![image](https://github.com/AdguardTeam/AdGuardHome/assets/55087301/0d9a3b5a-5a03-4108-bf99-62f74cbbb921)
Also looks like an A record request

Looks like the original screenshot was the wrong record request, sorry.

**Comment by ainar-g** [comment]
That could be caused by a number of things, including custom caches for clients' custom upstream configurations, the `CD` flag, the `AD` flag, etc.  As usual, inspecting the verbose logs should help.
