### ISSUE TITLE
Blocked client service does not work with DHCP IP range

### ISSUE THREAD

**Issue by stuffu** [AdguardTeam/AdGuardHome#7028]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.50

### Action

On my router, I have set DHCP range from 100-250, others are fixed addresses.

If I block a specific service on a device and set client id either by mac or ip address and the client has an ip address within the DHCP range, the service is not blocked.

If I force the device to a static ip address outside DHCP range, let's say .55 it works as intended.

### Expected result

All clients should have blocked services independent of DHCP range settings.

### Actual result

Only static ip adresses outside of DHCP range is getting filtered. Now when I think about it, my phone is not picking up the ad filtering either so I guess that is also affected.

### Additional information and/or screenshots

I run adguard on my router (opnsense), I guess it could have something to do with opnsense as well.

**Comment by schzhn** [comment]
@stuffu, if DHCP is handled by the router, you can't use a MAC as a Client Idenfier.
What does Query Log show?

**Comment by stuffu** [comment]
@schzhn oh, I didn’t know that I couldn’t use MAC with DHCP, would be neat to have that function though.

the funny part is that I tested just now with my iphone, YouTube in this case don’t show up at all in query log and fully functions. Tried another device and YouTube is blocked (global).

**Comment by stuffu** [comment]
@schzhn I found out what caused it, iPhone’s Private address. Guess I either have to live with it not being part of adguard or disable it?

**Comment by schzhn** [comment]
@stuffu, is the AGH address the only DNS server for your iPhone?

**Comment by stuffu** [comment]
@schzhn I have OPNSense as DNS server, so I’m not sure where the problem is tbh. AGH points to the router, checking the clients they also point to the router. 

Comparing two devices they have the same ip settings (both getting ip from dhcp) but the phone is not showing in the query log. Also checked both with https://d3ward.github.io/toolz/adblock, phone ends up on 4%, the other 95%.

I have no clue how this happens…

**Comment by schzhn** [comment]
@stuffu, the main culprit here is Private Relay.

**Comment by stuffu** [comment]
@schzhn wow, how did you come to think of that? I have been trying to solve this for so long. I was sure there was a bug after trying everything else, well not everything apparently. Huge thanks for finding the cause!
