### ISSUE TITLE
Unnecessary error

### ISSUE THREAD

**Issue by mikropsoft** [AdguardTeam/AdGuardHome#7029]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

 v0.107.49

### Action

When I navigate between pages, I sometimes encounter warnings like this. Of course, the warnings are not always the same and seem to be specific to the page, resembling some sort of error. However, when I refresh the page, the warnings disappear. Once, I even saw the page completely blank (it gave a similar error), but when I refreshed the page, there was no issue.

### Screenshot

![Ekran Görüntüsü (20)](https://github.com/AdguardTeam/AdGuardHome/assets/75412448/5e32cd05-4b69-4856-ba2e-92b4dcbc6b87)

**Comment by tjharman** [comment]
This sounds like a local host issue - the browser is unable to talk to the AdguardHome server.

Can you confirm this is still an issue for you?
