### ISSUE TITLE
Update adguard home 

### ISSUE THREAD

**Issue by Caruso8677** [AdguardTeam/AdGuardHome#7032]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Not being able to update adguard home from the web UI

### Proposed solution

Check for update button in the web ui

**Comment by Dynamic5912** [comment]
Are you saying it's not currently working?

**Comment by tjharman** [comment]
Hi @Caruso8677 AdguardHome will automatically allow you to upgrade from the GUI when a new version is released.  This feature already exists.  I am closing this ticket, but please reply with new information if you feel it isn't working for you.  Please provide details of your OS, the version you're running, and any screenshots/details you can to show it not working or errors.
Thanks!

**Comment by kilvn** [comment]
https://github.com/AdguardTeam/AdGuardHome/blob/master/docker/Dockerfile#L56
How to delete this startup command?

**Comment by tjharman** [comment]
It's a docker container. The whole point is you update the container, not the binaries within it.
