### ISSUE TITLE
Adguard does not block for queries outside assigned subnets

### ISSUE THREAD

**Issue by imasonaz** [AdguardTeam/AdGuardHome#7033]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.50

### Action

I have multiple subnets configured:
- Default/DMZ (8)
- Trusted (11)
- IOT (12)
- Admin (13)

I have my AGH docker host configured to be on the Default/DMZ network at 192.168.8.10 and rules such that all other VLANs can access the 8 network. I have AGH setup to use macvlan driver and gave it the IP 192.168.8.13.

I am able to query and ping across VLANs and networks without issue, but if I query from a subnet that isn't on 192.168.8.0/24 that AGH is assigned, it will not filter the query:
(queried from 192.168.10.15)
```
C:\Users\me>nslookup app-measurement.com
Server:  UnKnown
Address:  192.168.8.13

Non-authoritative answer:
Name:    app-measurement.com
Addresses:  2607:f8b0:4007:818::200e
          142.250.72.142
```
The above query does not show in the query log.
When queried from 192.168.8.15:
```
C:\Users\me>nslookup 192.168.8.13 app-measurement.com
*** Can't find server address for 'app-measurement.com':
Server:  c5f2c04d4647
Address:  192.168.8.13

Name:    c5f2c04d4647
Address:  192.168.8.13
```

I confirmed this by adding AGH's Docker host and AGH to the IOT VLAN and assigning it a secondary IP of 192.168.12.13 and then queries are blocked as expected:
```
C:\Users\me>nslookup 192.168.8.13 app-measurement.com
*** Can't find server address for 'app-measurement.com':
Server:  UnKnown
Address:  192.168.12.13

Name:    UnKnown
Address:  192.168.12.13
```
I have confirmed that AGH should be listening on all interfaces, as expected:
```
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
```

### Expected result

Blocked domains return NXDOMAIN as configured.

### Actual result

Blocked hosts resolve.

**Comment by tjharman** [comment]
I can't reproduce this.
I have a AdGuardHome server sitting on 192.168.0.5/24
I can query it no issues from the public Internet (TLS 853) from any public address, and from my VPN endpoints which are routed to it, 192.168.10.0/24

Any host that can contact it gets the correct Adblocking.

Do you have an iptables rule or something similar at play relating to Docker?  Or a NAT rule somewhere else?

My AdGuardHome isn't in Docker and I can't reproduce this at all.  If I can contact the AdGuardServer it will return the results as expected/configured.
