### ISSUE TITLE
Google SafeSearch enforced despite AGH "Use Safe Search" configuration

### ISSUE THREAD

**Issue by saint-lascivious** [AdguardTeam/AdGuardHome#7042]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

Multiple dedicated servers, DHCP is handled by the router

### AdGuard Home version

v0.107.50, also present on edge

### Action

AGH is configured as a caching proxy where no blocking/filtering is applied, and "Use Safe Search" is not enabled, nor enabled for any vendor listed.
![Screenshot_20240531_112909_Chrome](https://github.com/AdguardTeam/AdGuardHome/assets/1484933/77344fe5-6c76-4c97-97d9-128a045718b9)

### Expected result

Clients should not be prevented from modifying Google SafeSearch.

![Screenshot_20240531_105911_Google](https://github.com/AdguardTeam/AdGuardHome/assets/1484933/277dae21-7d78-4dd2-a9c3-75e43afb08f0)
![Screenshot_20240531_105854_Google](https://github.com/AdguardTeam/AdGuardHome/assets/1484933/e392120f-98d8-4ff3-8cc8-461e3433637c)

### Actual result

Clients are prevented from modifying Google SafeSearch.

![Screenshot_20240531_105933_Google](https://github.com/AdguardTeam/AdGuardHome/assets/1484933/335ebb9f-aa24-4dbe-afdb-bf1bd948cca8)

### Additional information and/or screenshots

Initially discovered on edge, I downgraded to v0.107.50 in an attempt to roll back to an unaffected build.

I am not aware of exactly when this behaviour started.

I was made aware of it by a house guest, and put it off as a "huh, that's weird" thing with the intent to look at it later, then some life happened and I forgot about it for a while until now.

I trashed my .yaml, and fully reinstalled the v0.107.50 release with just barely enough configuration to get things working in an effort to rule out a client level configuration issue on my end as I had several clients defined with their own pretty specific configurations.

To rule out the (also local) upstreams servers, filtering was disabled there, and finally several external public recursive nameservers were used (Google, Cloudflare, Quad 9, etc.), and the issue was still observed.

To attempt to rule out Google somehow going "hey, fuck that IP in particular" for some reason, affected clients were statically addressed with one or more of the aforementioned remote public nameservers, where the issue was no longer observed and clients could configure Google SafeSearch again.

My suspicion is that this may be a Google change rather than an AGH change.

I am happy to add any additional information that may assist or help to indicate either way upon request.

**Comment by Dynamic5912** [comment]
What DNS is set in the Upstream DNS?

**Comment by saint-lascivious** [comment]
This was (fairly clearly, IMO) addressed in the body text.

As stated it doesn't matter what the upstream DNS is set to (if it did, that wouldn't be an AGH issue).

The issue was present with the default upstream (which IIRC was Quad 9 TLS), my local upstreams (with and without filtering enabled, covered in the initial post), and any one of numerous public recursive nameservers (also covered in the initial post).

**Comment by saint-lascivious** [comment]
I would just like to make it clear that this issue is not in fact 'waiting for data'.

The information requested is present, and was equally present at the time of its request. It was simply never read.

**Comment by jaumard** [comment]
How to fix this ? besoin I have last version and safe search is always forced...

**Comment by Dynamic5912** [comment]
> How to fix this ? besoin I have last version and safe search is always forced...

What upstream dns servers are you using?

**Comment by jaumard** [comment]
Look like it was not AdGuard, I tried different devices and only my phone was using safe guard... Look like if on Android you have set Private DNS to automatic and AdGuard with no TLS enabled then android is forcing the safe search... I set it to "off" instead and no more issue. 
Sorry for the noise, hope it will help someone in the future who has this issue ˆˆ 
Thanks!
