### ISSUE TITLE
Установка в alpine linux

### ISSUE THREAD

**Issue by Cryo777** [AdguardTeam/AdGuardHome#705]
Добавьте мануал по установке в alpine linux.

**Comment by ameshkov** [comment]
@Cryo777 а что за проблема с ним? Всмысле в чем отличие от любого другого дистрибутива?

**Comment by Cryo777** [comment]
Там вместо systemctl используется openrc
https://wiki.alpinelinux.org/wiki/Writing_Init_Scripts

**Comment by ameshkov** [comment]
Да мы вроде нигде напрямую systemctl не говорим использовать, а предлагаем через `AdGuardHome -s install/start/stop` с сервисом работать. Оно поддерживает systemd и sysv в таком случае.

Работает ли это на alpine?
