### ISSUE TITLE
AdguardHome.err keeps growing causing high cpu usage

### ISSUE THREAD

**Issue by zbugrkx** [AdguardTeam/AdGuardHome#7053]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.50

### Action

cd /var/log/
ll -h
check : AdguardHome.err 

### Expected result

Configuration or option to rotate/clear the log files without having to intervene manually.

### Actual result

File was several gb's causing 80/100% cpu usage on raspberry pi. After stopping adguardhome, deleting the file and restarting adguardhome, usage got back to 3/4%

**Comment by zbugrkx** [comment]
File is up around 1.5gb after 24hours :-/ Becoming quite an issue and stopping the service, deleting the file, then restarting the service is not an ideal solution at the moment. Hoping someone has a better process or suggestion to automate this maybe without DNS interruption ideally.

**Comment by zbugrkx** [comment]
We need to have an option to be able to turn off completely logging. I understand it can be useful and should stay enabled by default but the current behavior is not possible to maintain when some situations can cause the log file to grow forever. 

A third instance that I had forgotten about had run out of storage, the file was 66gb 😄 

For now, what seems to work is a symlink to /dev/null. Not the nicest but i don't have to worry about it daily.

**Comment by ainar-g** [comment]
@EugeneOne1, I think the last time we wanted to use systemd's rotation feature there were some kind of version conflicts?  Can you please investigate?

As for the matter at hand, the solution is to set the log file and rotation explicitly.  For example:

```yaml
log:
  file: /var/log/AdGuardHome.log
  max_backups: 3
  max_size: 100
  max_age: 3
  compress: false
  local_time: true
  verbose: false
```

**Comment by zbugrkx** [comment]
Thank you for the suggestion I had not realize you needed your specify a file name for the rest of the options to work. For now my symlink works and that's a bit less flash wear eh! Being able to turn them all on/off as an option in that section would be great.

**Comment by EugeneOne1** [comment]
@zbugrkx, hello again.  We've looked through the code and found that our `systemd` service script pipes `stdout` and `stderr` to `/var/log/AdGuardHome.log` and `/var/log/AdGuardHome.err` respectively.  However, there is another [`journal`](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#StandardOutput=) option that sends the output to the `journald` service, and it actually seems to be a better choice for `systemd`-based service.  What do you think?

**Comment by zbugrkx** [comment]
@EugeneOne1 . Hi! I'm not 200% an expert on everything linux but that could potentially be. I think, a better solution yes. That means we would then rely on that service and linux defaults to handle log cleanup/rotation (which would be better for many users who would not be aware of the .yaml specific changes). And I guess we would always have the possibility to push it out somewhere else by forcing the options in the .yaml

**Comment by EugeneOne1** [comment]
@zbugrkx, could you please help us to check the solution?  We can actually try it without AdGuardHome's update, here is how:
 1. Stop the service:
    - either with `systemctl stop AdGuardHome.service`;
    - or with `AdGuardHome -s stop`.
 1. Open and edit `/etc/systemd/system/AdGuardHome.service` file:
    - remove the line starting with `ExecStartPre=`;
    - replace the line `StandardOutput=file:/var/log/AdGuardHome.out` with `StandardOutput=journal`;
    - replace the line `StandardError=file:/var/log/AdGuardHome.out` with `StandardError=journal`;
 1. Start the service again.  It should now write directly to `journald` and not use any files.

If it improves the CPU and disk usage?  If it does, we'll put the fix into the following release.

**Comment by zbugrkx** [comment]
@EugeneOne1 . So far it seems to behave alright (for sure better than current). journald can be also configured to a certain max size (this however affects every program so have to be aware of that) with SystemMaxUse= in the journald.conf

Would be great to have other people try it just to have a larger sample size and ensure the solution is good for everyone just in case :-)

**Comment by EugeneOne1** [comment]
@zbugrkx, thank you for your help.  We'll push the fix in the near future.

**Comment by zbugrkx** [comment]
@EugeneOne1 Thanks a lot for feedback and work on this!
If I may add, having an option in the yaml to say, log=none to totally disable them, would be a nice option as well. Even less flash wear and cpu usage as long as we know what we are doing and don't need to troubleshoot. In normal use, a lot of errors can be generated due to upstream dns servers sending malformed packets, timeouts, network issues. Being able to discard it all would be great.

**Comment by EugeneOne1** [comment]
@zbugrkx, I think this is actually a good feature request.  We're trying to keep our issue tracker organized, so could you please file a separate issue for this feature?

**Comment by zbugrkx** [comment]
@EugeneOne1 will do !

**Comment by EugeneOne1** [comment]
@zbugrkx, we've pushed the edge release with the fix.  Would you like to try it before closing the issue?  Note that the service should be reinstalled, see [CHANGELOG](https://github.com/AdguardTeam/AdGuardHome/blob/master/CHANGELOG.md#unreleased).

**Comment by zbugrkx** [comment]
@EugeneOne1 all good to close the issue on my side! I prefer to update the system when the release gets available via the standard process to update to avoid any issues. Thanks so much for the great reactivity and work on this!
