### ISSUE TITLE
poweropti / powerfox  is blocket  i cant open the port for poweropti 

### ISSUE THREAD

**Issue by theo20r** [AdguardTeam/AdGuardHome#7054]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

poweropti / powerfox  is blocket  i cant open the port for poweropti 

### Proposed solution

ip  or  link direkt open   in Pihole is this ok 

### Alternatives considered and additional information

ip  or  link direkt open   in Pihole is this ok

**Comment by ainar-g** [comment]
Please use [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for questions, as is recommended both in the contribution guidelines and the issue template.
