### ISSUE TITLE
User-friendly client name -- Using Reverse DNS lookup

### ISSUE THREAD

**Issue by nightah** [AdguardTeam/AdGuardHome#706]
Similar to #637 it would be nice if AdGuardHome had the ability to perform a reverse DNS lookup to determine the hostname associated to a specific IP address.

This has the advantage of not requiring manual modification of the `/etc/hosts` file which often will lead to pain and clutter. 

In the case of a host entry existing for said IP address, this should overwrite and take precedence over the reverse DNS specified hostname.

**Comment by ameshkov** [comment]
@nightah this makes sense indeed, thank you!

**Comment by ameshkov** [comment]
We missed one thing here: after AGH started up and loaded the "Top clients" list, we should schedule top clients IP addresses for the reverse lookup.

**Comment by ameshkov** [comment]
I see a lot of unnecessary errors in the log:
```
2019/06/04 16:27:01 [error] len(resp.Answer) != 1
2019/06/04 16:27:01 [error] len(resp.Answer) != 1
2019/06/04 16:27:01 [error] len(resp.Answer) != 1
2019/06/04 16:27:01 [error] not a dns.PTR response
2019/06/04 16:27:01 [error] len(resp.Answer) != 1
2019/06/04 16:27:02 [error] len(resp.Answer) != 1
2019/06/04 16:27:02 [error] len(resp.Answer) != 1
2019/06/04 16:27:02 [error] len(resp.Answer) != 1
2019/06/04 16:27:03 [error] len(resp.Answer) != 1
```

1. First of all, these are not actually errors. Not every IP can be looked up, this is a normal behavior
2. Second, the error message does not explain which of the lookups failed exactly.

**Comment by ameshkov** [comment]
No rDNS lookups are made for clients that use DOH

**Comment by Termi79** [comment]
rDNS lookups would be even better if it was possible to define a specific upstream server for a specific (internal) IP range, for example IP range 192.168.0.1/24 use DNS server 192.168.0.1 for rDNS.

**Comment by ameshkov** [comment]
@Termi79 makes sense. Could you please file a feature request about that?

**Comment by anoma** [comment]
Reverse link as google makes this ticket much easier to find than the follow on Feature Request

https://github.com/AdguardTeam/AdGuardHome/issues/842
