### ISSUE TITLE
AdGuard Home Using DNS Providers That Have Been Removed From Upstream DNS Settings

### ISSUE THREAD

**Issue by phneeley** [AdguardTeam/AdGuardHome#7062]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.50

### Action

I’ve been experimenting with different DNS providers from AdGuard’s list of known and trusted providers to identify the ones that provide the best performance. I’ve gone through several rounds of adding, deleting, and commenting out providers, mostly using their DoH addresses. I’ve finally settled on a few providers. However, running dnscheck.tools, I can see that  frequently, but not all the time, AdGuard is continuing to use some of the providers that I’ve removed or commented out of the Upstream DNS Servers list.
![IMG_0106](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/9684f54d-1f78-4cca-b77f-02ebd15cbc18)
![IMG_0105](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/52916c58-2905-4c7b-8dda-f606b599f382)

### Expected result

After deleting or commenting out DNS providers from Upstream DNS Servers field, AdGuard home should cease to use these providers.

### Actual result

Frequently, but not all the time, AdGuard continues to use DNS providers that have been removed or commented out of the Upstream DNS Servers field.
![IMG_0107](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/a8b9b55a-be9b-4c30-afa9-6064472b6f7a)
![IMG_0108](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/8d0a6f99-c441-49a0-a1af-a01ff73e4c1a)

### Additional information and/or screenshots

Adguard installed on Raspberry Pi 4 and through Dietpi O/S. Unbound is also installed, though I’ve encountered this same problem when Unbound is not installed/when entering text directly into the Upstream DNS Server box.

**Comment by phneeley** [comment]
Hi! Thanks for the quick response.

 I’ve rebooted the hosts each time. I have two identical instances running, both on RPi4s.

Thanks!

**Comment by ainar-g** [comment]
How do you actually verify that AdGuard Home is using the removed upstreams?  Do you see queries with these upstreams in the query logs?

Also, are you sure that neither the fallback servers, nor the private rDNS servers, nor the server on port 5335 are the ones making the queries?  What are the DNS settings besides the upstream file?

**Comment by phneeley** [comment]
I’m using https://www.dnscheck.tools/ to monitor DNS resolvers. Deleted DNS servers occasionally show up there though I cannot find corresponding log entries in querylog.json.

I’m not using any fallback. Bootstrap is set to Quad9 standard. The server is set to localhost though I’ve also occasionally had it set to Quad9’s standard IPv4 addresses.
![IMG_0111](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/d0a363da-ad18-487f-99aa-6f2c50724f18)
![IMG_0112](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/d7efe2a5-8484-41bb-80ac-1c5d1990e94c)
![IMG_0113](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/9c1e4c38-5c4e-4efa-a66f-8c121f0f0a4b)
![IMG_0114](https://github.com/AdguardTeam/AdGuardHome/assets/155403255/5a173bf6-f44b-4f7c-b188-17f3da640f4d)

**Comment by phneeley** [comment]
I’m starting to think this is a problem with dnscheck.tools. 

One at a time, I completely wiped / reinstalled DietPi on both RPis and re-installed AdGuard Home using AdGuard Sync to make sure I didn’t lose all my non-DNS server settings (by the way, it would be great to have a settings back-up/restore option in the GUI). 

I still get the same strange results on occasion. Other DNS leak test sites don’t suggest there’s an issue. I don’t know how to explain the results on dnscheck.tools, but it seems this is not an issue with AdGuard Home so far as I can tell.

**Comment by phneeley** [comment]
Ok, this is actually a NextDNS issue/feature. I have been using https://anycast.dns.nextdns.io/ and https://dns.nextdns.io/, which appear to occasionally use servers in various different locations.
