### ISSUE TITLE
Client location isn't considered in DNS resolves.

### ISSUE THREAD

**Issue by MistakingManx** [AdguardTeam/AdGuardHome#7067]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.51

### Action

Ping the Minecraft Authentication server.

### Expected result

The IP for the closest server to the client.

### Actual result

It always returns the IP closest to the VPS's location instead.
This doesn't add delay, it outright prevents the service from connecting, effectively preventing clients further away from the server to login to Minecraft whatsoever.

### Additional information and/or screenshots

The server runs Ubuntu, and is hosted in New York, myself and most of my friends live near this area, only a few hours or a day away from it. All of us can use Minecraft fine, however a friend in Texas loses the ability to login to Minecraft entirely when on my DNS server.

Further testing reveals that the IP returned by a ping is different when he is and isn't on my network, where-as the friends who are closer have the same IP, and the friends in the middle zone also have a different IP.

I'm not entirely sure what kind of information is shared with a DNS resolve, so I thought I'd ask about it.
There's not much we could do if they do IP-lookups to serve their own IP, yeah?

**Comment by ainar-g** [comment]
I don't think there's anything we can do here, if the server in question has this kind of geoblocking based on DNS.  If the upstream DNS server supports ECS, you can enable ECS setting on the *DNS settings* page and see if that makes a difference.  You could also create a set of `$dnsrewrite` rules with the “correct” IP addresses for each client, but that obviously requires maintenance to update the IPs when they change.

**Comment by MistakingManx** [comment]
Is there a way to specifically block the domain from being cached, or would that not be an issue with ECS on?

**Comment by ainar-g** [comment]
I'm not exactly sure what you're asking, sorry.  The cache is split based on the ECS data from the response when ECS is enabled.
