### ISSUE TITLE
Synology RT2600ac with SRM 1.2.2-7915 refuses DNS server address 

### ISSUE THREAD

**Issue by cvandray** [AdguardTeam/AdGuardHome#707]
In trying to configure DNS server setting (127.0.0.1) on Synology RT2600ac router, the following error occurs on the router: "The IP address you entered in invalid" in the DND field and I have to revert to the existing server address.

This is strange behaviour for 2 reasons:
- Adguard DNS addresses work without a problem;
- The above DNS server address works on my Mac and I can "see" the AdGuard Home portal.

Any suggestions?

| Version of AdGuard Home server:| (v0.94)
| How did you setup DNS configuration:| (Router)
| If it's a router or IoT, please write device model:| (RT2600ac)
| Operating system and version:| (SRM 1.2.2-7915)

**Comment by ameshkov** [comment]
127.0.0.1 is the address of your local machine (so for your Mac -- this is the address of it, and for your router, this is the address of your router).

If you have AGH installed on your Mac, you might need to use the local address of it instead.
