### ISSUE TITLE
build error...the newest version.

### ISSUE THREAD

**Issue by andylau004** [AdguardTeam/AdGuardHome#7070]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

master

### Action

build error output: log.txt

[log.txt](https://github.com/user-attachments/files/15802948/log.txt)

### Expected result

build success

### Actual result

```shell
> dashboard@0.1.0 build-prod
> cross-env BUILD_ENV=prod webpack --config webpack.prod.js

(node:215964) [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH] DeprecationWarning: [hash] is now [fullhash] (also consider using [chunkhash] or [contenthash], see documentation for details)
(Use `node --trace-deprecation ...` to show where the warning was created)
12 assets
453 modules

WARNING in ./src/initialState.ts 82:23-44
export 'DEFAULT_BLOCKING_IPV4' (imported as 'DEFAULT_BLOCKING_IPV4') was not found in './reducers/dnsConfig' (possible exports: default)

WARNING in ./src/initialState.ts 83:23-44
export 'DEFAULT_BLOCKING_IPV6' (imported as 'DEFAULT_BLOCKING_IPV6') was not found in './reducers/dnsConfig' (possible exports: default)

ERROR in ./src/components/App/index.js 104:57
Module parse failed: Unexpected token (104:57)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

### Additional information and/or screenshots

<img width="468" alt="cc 2024-06-12T07_49_59 888Z" src="https://github.com/AdguardTeam/AdGuardHome/assets/2648844/626657d6-d48d-4d9e-890a-d66dad1ed83e">

_No response_

**Comment by schzhn** [comment]
Try
```
make js-deps
make
```

**Comment by schzhn** [comment]
We assume it worked. Feel free to reopen the issue if the problem persists.

**Comment by andylau004** [comment]
> We assume it worked. Feel free to reopen the issue if the problem persists.我们假设它奏效了。如果问题仍然存在，请随时重新打开问题。

OK

have already solved
