### ISSUE TITLE
Never-ending loop

### ISSUE THREAD

**Issue by dannymichel** [AdguardTeam/AdGuardHome#7073]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

2.14.1.1603

### Action

https://auth.adguard.org/auth/apple is a never-ending loop on safari

### Expected result

log in with apple when activating license 

### Actual result

never-ending loop
page keeps trying to load 
![sc](https://github.com/AdguardTeam/AdGuardHome/assets/1161544/9f069e30-14a0-4e52-8d5d-0e6f9fc7363d)

### Additional information and/or screenshots

![sc](https://github.com/AdguardTeam/AdGuardHome/assets/1161544/c3aa3fea-66c4-4c6d-8e09-f463729b86a5)

**Comment by lip2443** [comment]
similar issue here, but on yunohost+rpi4

**Comment by tjharman** [comment]
@dannymichel This github repo is for AdGuardHome - it sounds like you've got an issue with an AdGuard for Mac application, which you can report [bugs against here](https://github.com/AdguardTeam/AdguardForMac).

@lip2443 This seems unrelated to the post by @dannymichel which was incorrectly logged against AdGuardHome.  I suggest starting another issue if this is still a problem for you.
