### ISSUE TITLE
AdGuard Home not working on Windows 11

### ISSUE THREAD

**Issue by Totix92** [AdguardTeam/AdGuardHome#7074]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.51

### Action

Filtering does not occur on Windows 11 x64, the adguard server IP address is entered as DNS in the Windows network settings.
It works correctly on Linux PCs and smartphones.

### Expected result

I expect AdGuard to filter everything on Windows too

### Actual result

Filter not working

**Comment by bcookatpcsd** [comment]
https://woshub.com/powershell-configure-windows-networking/

(we have custom ps scripts at work.. but this is the closest..) 

Is this home or 'work'.. do you have a proxy defined, or is there a proxy discovered.. 

do a straight nslookup to the server and see if that query shows..
