### ISSUE TITLE
Load-balancing mode not picking the fastest servers

### ISSUE THREAD

**Issue by renatoyamane** [AdguardTeam/AdGuardHome#7075]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

At least since 0.107.46

### Action

Load-balancing mode says:

![image](https://github.com/AdguardTeam/AdGuardHome/assets/31208391/90900de5-6086-45e8-9d12-f8da1a21d9e6)

The fastest servers are:

![image](https://github.com/AdguardTeam/AdGuardHome/assets/31208391/ddf53af9-c645-4de2-a745-d6e81deda373)

But the fastest SDNS servers are not used more often as they should be:

![image](https://github.com/AdguardTeam/AdGuardHome/assets/31208391/664e6c72-6223-4f2c-9b5c-185251749da1)

### Expected result

Fastest servers should be on the top

### Actual result

SDNS servers are the fastest servers, but they are **NOT** being picked by ADGuard Home

### Additional information and/or screenshots

Upstream servers:

```
https://dns.quad9.net/dns-query
https://doh.opendns.com/dns-query
https://security.cloudflare-dns.com/dns-query
tls://security.cloudflare-dns.com
quic://dns.adguard-dns.com
quic://zero.dns0.eu
https://dns.adguard-dns.com/dns-query
tls://dns.adguard-dns.com
h3://cloudflare-dns.com/dns-query
h3://doh3.dns.nextdns.io
# Cisco OpenDNS:
sdns://AQAAAAAAAAAADjIwOC42Ny4yMjAuMjIwILc1EUAgbyJdPivYItf9aR6hwzzI1maNDL4Ev6vKQ_t5GzIuZG5zY3J5cHQtY2VydC5vcGVuZG5zLmNvbQ
# Quad9:
sdns://AQMAAAAAAAAADDkuOS45Ljk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0
# AdGuard:
sdns://AgMAAAAAAAAADDk0LjE0MC4xNC4xNCCaOjT3J965vKUQA9nOnDn48n3ZxSQpAcK6saROY1oCGQw5NC4xNDAuMTQuMTQKL2Rucy1xdWVyeQ
# Comodo Secure DNS:
sdns://AQAAAAAAAAAACjguMjAuMjQ3LjIg0sJUqpYcHsoXmZb1X7yAHwg2xyN5q1J-zaiGG-Dgs7AoMi5kbnNjcnlwdC1jZXJ0LnNoaWVsZC0yLmRuc2J5Y29tb2RvLmNvbQ
quic://x-hagezi-proplus.freedns.controld.com
quic://x-1hosts-lite.freedns.controld.com
```

Boostrap servers:

```
208.67.222.222
1.1.1.1
208.67.220.220
9.9.9.9
8.8.8.8
149.112.112.10
94.140.15.15
2a10:50c0::ad1:ff
94.140.14.14
2a10:50c0::ad2:ff
[2a10:50c0::ad1:ff]:5443
2001:4860:4860:0:0:0:0:6464
76.76.2.42
45.90.28.128
```

DNS Blocklists under use:

```
# ADGuard DNS Filter
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

# 1Hosts (mini)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt

# Perflyst and Dandelion Sprout's Smart-TV Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt

# OISD Blocklist Full
https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt

# Hagezi Multipro++
https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.plus.txt

# Hagezi TIF
https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.txt
```

**Comment by EugeneOne1** [comment]
@renatoyamane, hello.  The thing is that the algorithm uses not only the statistics of successful resolution, which is contained in the "Average upstream response time" table, but also considers the resolution failures to calculate the upstream score.  I think we should improve the documentation about this as well as the UI hints.

**Comment by EugeneOne1** [comment]
@renatoyamane, hello again.  We've released the edge build with updated UI text that should more accurately describe the load-balancing upstream mode.  We've also reflected this in the [wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).  I think this issue can now be considered resolved.
