### ISSUE TITLE
Fatal error while initing hosts watcher

### ISSUE THREAD

**Issue by oompaloomp** [AdguardTeam/AdGuardHome#7076]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.51

### Action

Platform:
Linux RM-AC2100 3.4.113 #1 SMP Sat Jun 1 02:51:01 EEST 2024 mips GNU/Linux aka Padavan (https://gitlab.com/hadzhioglu/padavan-ng/-/commits/master), router RM-AC2100.
Log AdGuard Home:
2024/06/14 04:32:26.322121 [info] AdGuard Home, version v0.107.51
2024/06/14 04:32:26.771555 [info] tls: using default ciphers
2024/06/14 04:32:26.771998 [fatal] initing hosts watcher: os watcher: creating watcher: function not implemented

### Expected result

AdGuard Home web ui not up.

### Actual result

Web not up, In log file - fatal error.

**Comment by ainar-g** [comment]
Please specify the OS, the CPU architecture, and the filesystem type more precisely.

This is most likely due to the FS not supporting notifications.  Which should definitely be an error, but not a fatal one.  @EugeneOne1, please inspect why this is considered fatal and, if there aren't good reasons, fix.

In the meantime, setting `dns.hostsfile_enabled` and `clients.runtime_sources.hosts` to false could be the workaround.

**Comment by oompaloomp** [comment]
@ainar-g , don't see in my file setting dns.hostsfile_enabled.
Setting clients.runtime_sources.hosts to false but web ui is't up.
File attached.
[AdGuardHome.zip](https://github.com/user-attachments/files/15836217/AdGuardHome.zip)

**Comment by EugeneOne1** [comment]
@oompaloomp, hello again and sorry for the late reply.  We've pushed the edge build that disables `/etc/hosts' tracking for systems that don't support it, could you please check if it works?

**Comment by oompaloomp** [comment]
@EugeneOne1, unfortunately can't.
Changed the router to Keenetic Hopper DSL (KN-3610).
