### ISSUE TITLE
Add option to fully disable logging/error

### ISSUE THREAD

**Issue by zbugrkx** [AdguardTeam/AdGuardHome#7079]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Following discussion in https://github.com/AdguardTeam/AdGuardHome/issues/7053 this is to implement an option, in the YAML or other, to fully disable writing to logs for errors/infos (.out / . err). This is in addition to the future enhancement to add logging to journald

### Proposed solution

Implement option to disable all logging in yaml or config

**Comment by schzhn** [comment]
Support for the configuration property `log.enabled` has been added in the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions).

**Comment by gkajaia1979** [comment]
Better to implement to disable separate types of logs. for example adguard home error logs only that file AdGuardHome.err is growing fast in my case.

**Comment by gkajaia1979** [comment]
How do I implement log.enabled in yaml?
