### ISSUE TITLE
Stopping AdGuardHome in Docker on RPi not savinglogs before stopping

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#708]
When running AdGuard Home on Raspberry Pi in docker container, upon stopping the docker container, AdGuard Home is not saving logs before stopping.  Running

`docker stop adguardhome` stops the docker container, but the logs are lost from when they were last persisted.

**NOTE: The two volumes have been mapped for persistence

Configuration - /opt/adguardhome/conf
Filters and data - /opt/adguardhome/work**

Version of AdGuard Home server:| 0.94
How did you setup DNS configuration:| Router
If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B
Operating system and version:| Raspian 9, Latest Docker

**Comment by ameshkov** [comment]
Hm, we just did test this on our side, and AGH receives the SIGTERM on docker stop:
```
2019/04/09 08:38:08 [info] Stopping AdGuard Home
```

What does it print to the log in your case?

**Comment by adrianh-za** [comment]
@ameshkov 

I can't seem to locate the log file.  Where can I find the log file?

**Comment by ameshkov** [comment]
It prints everything to stderr by default (unless you set a path to log file in the cconfig yaml)

**Comment by adrianh-za** [comment]
I haven't changed the log path.

I am not to clued up on Raspberry Pi and how to get this log.  AG Home was my first attempt, please can you guide me in how to grab this log for you?

**Comment by ameshkov** [comment]
Try `docker logs --follow`

**Comment by ameshkov** [comment]
(Frankly, I am not a Docker expert either :) )

**Comment by adrianh-za** [comment]
I stopped and restarted

docker stop adguardhome
docker start adguardhome

2019/04/09 09:15:41 [info] Stopping AdGuard Home
2019/04/09 09:15:41 [info] Stopping the DNS proxy server
2019/04/09 09:15:41 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/04/09 09:15:41 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2019/04/09 09:15:41 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/04/09 09:15:41 [info] Stopped the DNS proxy server
2019/04/09 09:15:54 [info] AdGuard Home, version v0.94

2019/04/09 09:15:54 [info] Upstream 0: 1.1.1.1:853
2019/04/09 09:15:54 [info] Upstream 1: 9.9.9.9:853
2019/04/09 09:15:54 [info] Upstream 2: 1.1.1.1:53
2019/04/09 09:15:54 [info] Upstream 3: 9.9.9.9:53
2019/04/09 09:15:58 [info] Start DNS server periodic jobs
2019/04/09 09:15:58 [info] Starting the DNS proxy server
2019/04/09 09:15:58 [info] Ratelimit is enabled and set to 20 rps
2019/04/09 09:15:58 [info] The server is configured to refuse ANY requests
2019/04/09 09:15:58 [info] DNS cache is enabled
2019/04/09 09:15:58 [info] Creating the UDP server socket
2019/04/09 09:15:58 [info] Listening to udp://[::]:53
2019/04/09 09:15:58 [info] Creating the TCP server socket
2019/04/09 09:15:58 [info] Listening to tcp://[::]:53
2019/04/09 09:15:58 [info] Creating the TLS server socket
2019/04/09 09:15:58 [info] Listening to tls://[::]:4853
2019/04/09 09:15:58 [info] Entering the tcp listener loop on [::]:53
2019/04/09 09:15:58 [info] Entering the tls listener loop on [::]:4853
2019/04/09 09:15:58 [info] Entering the UDP listener loop on [::]:53
2019/04/09 09:15:58 [info] AdGuard Home is available on the following addresses:
2019/04/09 09:15:58 [info] number of certs - 2
2019/04/09 09:15:58 [info] got an intermediate cert

**Comment by ameshkov** [comment]
Hm, so it should've flushed the query log just okay (the message about it is printed if AGH is launched with `-v` argument)

**Comment by adrianh-za** [comment]
OK, I want to try another experiment.

I'll wait about 30 minutes for logs to build up, then I will stop the container, and then I will reboot the RPi.  I will revert back with the results.

**Comment by adrianh-za** [comment]
@ameshkov 

Maybe this has been my error.  I am thinking I merely did a `sudo reboot` without doing a `docker stop adguardhome` when the logs disappeared.

I suppose a test would be to reboot the RPi without stopping the docker container and see what happens.

**Comment by adrianh-za** [comment]
@ameshkov 

To be honest, I haven't been able to reproduce this today.  The odd thing is the log file has a large gap which is probably the gap I saw in query log.  I do not remember stopped the server yesterday morning, so I am a bit frustrated, feels like I am wasting your time and mine.  That said, I think close this and I will keep an eye on things over the next few days.

**2019/04/08 08:11:12 [info] Stopped the DNS proxy server
2019/04/08 18:58:01 [info] AdGuard Home, version v0.94**

2019/04/08 08:11:12 [info] Stopping AdGuard Home
2019/04/08 08:11:12 [info] Stopping the DNS proxy server
2019/04/08 08:11:12 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/04/08 08:11:12 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2019/04/08 08:11:12 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/04/08 08:11:12 [info] Stopped the DNS proxy server
2019/04/08 18:58:01 [info] AdGuard Home, version v0.94

2019/04/08 18:58:01 [info] Upstream 0: 1.1.1.1:853
2019/04/08 18:58:01 [info] Upstream 1: 9.9.9.9:853
2019/04/08 18:58:01 [info] Upstream 2: 1.1.1.1:53
2019/04/08 18:58:01 [info] Upstream 3: 9.9.9.9:53
2019/04/08 18:58:04 [info] Start DNS server periodic jobs
2019/04/08 18:58:04 [info] Starting the DNS proxy server

**Comment by ameshkov** [comment]
Got it! Please reopen if there are news

**Comment by adrianh-za** [comment]
@ameshkov 

This has occurred again, 6 hours of query logs are are missing.  I wanted to update the user name in the yaml file, so did the following:

stopped container with **docker stop adguardhome**
edited yaml file with **sudo nano AdGuardHome.yaml** with new credentials
started container with **docker start adgaurdhome**

Here is the putty dump:

```
login as: pi
pi@192.168.10.14's password:
Linux RPi-Black 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Apr 26 16:14:58 2019 from 192.168.10.113
pi@RPi-Black:~ $ docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                    NAMES
1ce6b3fddd47        mrhadenough/rpi-socks5-server      "/socks5 --restart=u…"   3 days ago          Up 3 days           0.0.0.0:1080->1080/tcp   socks5-rpi
12c8539b5d7c        adguard/adguardhome:armhf-latest   "/opt/adguardhome/Ad…"   3 days ago          Up 3 days                                    adguardhome
7e74d495e70b        tkoopman/shellinabox-rpi           "/usr/bin/entry.sh /…"   2 weeks ago         Up 2 weeks          0.0.0.0:4200->4200/tcp   shell-in-a-box
20195a6ea2f4        michaelmiklis/rpi-monitor:latest   "/usr/bin/entry.sh /…"   2 weeks ago         Up 2 weeks          0.0.0.0:8888->8888/tcp   rpi-monitor
pi@RPi-Black:~ $ docker stop adguardhome
adguardhome
pi@RPi-Black:~ $ cd ..
pi@RPi-Black:/home $ cd ..
pi@RPi-Black:/ $ cd usr
pi@RPi-Black:/usr $ cd share
pi@RPi-Black:/usr/share $ cd docker-data
pi@RPi-Black:/usr/share/docker-data $ cd adguardhome
pi@RPi-Black:/usr/share/docker-data/adguardhome $ sudo nano AdGuardHome.yaml
pi@RPi-Black:/usr/share/docker-data/adguardhome $ docker start adguardhome
adguardhome
```


![Adguard-logs](https://user-images.githubusercontent.com/5121135/56849933-9eb12400-68fb-11e9-8a7c-7ada6ee86100.JPG)

**Comment by ameshkov** [comment]
@szolin could there be some race condition when we're stopping AGH?

**Comment by szolin** [comment]
Most likely it's because currently we write querylog to a file in a separate thread, and we don't wait for it to finish when Stop command is received.  Right now we just exit the process, even if querylog file writer haven't finished yet.
We need to have only one thread for this job and we should synchronize it with the main thread.

**Comment by ameshkov** [comment]
Marking this as a bug then.

**Comment by ameshkov** [comment]
This one must be resolved in v0.96

**Comment by adrianh-za** [comment]
Sorry guys.  Did update and the logs are missing about 3 hours of logs.  Below is my Putty session for the update.

> pi@RPi-Black:~ $ docker stop adguardhome
> adguardhome
> pi@RPi-Black:~ $ docker rm adguardhome
> adguardhome
> pi@RPi-Black:~ $ docker pull adguard/adguardhome:armhf-latest
> armhf-latest: Pulling from adguard/adguardhome
> 11f8b7d78d21: Pull complete
> 7fd6c618dc2b: Pull complete
> 30d51e7c0813: Pull complete
> f83cc39f96e2: Pull complete
> fff53d841e4c: Pull complete
> Digest: sha256:de20cdcb73278e56e48d81cb2928c28337faeaea31cd0984d221c6cec6f5e72e
> Status: Downloaded newer image for adguard/adguardhome:armhf-latest
> pi@RPi-Black:~ $ sudo docker run --name adguardhome -v /usr/share/docker-data/adguardhome:/opt/adguardhome/work -v /usr/share/docker-data/adguardhome:/opt/adguardhome/conf --net=host -d adguard/adguardhome:armhf-latest
> f5193037414ec28facc38f3ad7d590354848590b9b1305840c07e42f1c27a5b9
> pi@RPi-Black:~ $ sudo docker update --restart=unless-stopped adguardhome
> adguardhome
> pi@RPi-Black:~ $

![image](https://user-images.githubusercontent.com/5121135/61132702-33b7c800-a4bc-11e9-9812-6a1a2dc158a6.png)

**Comment by szolin** [comment]
Can you show application logs?
