### ISSUE TITLE
How to obtain real user IP through port forwarding

### ISSUE THREAD

**Issue by skoy03** [AdguardTeam/AdGuardHome#7089]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

How to obtain the real user IP address after forwarding on the DOT port

### Proposed solution

How to obtain the real user IP address after forwarding on the DOT port

**Comment by ainar-g** [comment]
Duplicate of #2798
