### ISSUE TITLE
Regex Allow list not taking precedence over Adguard Syntax Block rules

### ISSUE THREAD

**Issue by kiwilad-nz** [AdguardTeam/AdGuardHome#7093]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.51

### Action

nslookup www.gov.wales
Server:  flat.lan
Address:  10.0.3.1

Non-authoritative answer:
Name:    www.gov.wales
Address:  0.0.0.0

### Expected result

Status
Allowed
DNS server
127.0.0.1:5353
Served from cache
Elapsed
0.34 ms
Response code
NOERROR
Response
CNAME: d220i9qfduvrqt.cloudfront.net. (ttl=10)
CNAME: d220i9qfduvrqt.cloudfront.net. (ttl=10)
CNAME: d220i9qfduvrqt.cloudfront.net. (ttl=10)
CNAME: d220i9qfduvrqt.cloudfront.net. (ttl=10)
A: 13.227.74.29 (ttl=10)
A: 13.227.74.128 (ttl=10)
A: 13.227.74.120 (ttl=10)
A: 13.227.74.103 (ttl=10)
Rule(s)
/.*\.gov(t)?(\.[a-z]{2,4})?$/

### Actual result

Status
Blocked
Elapsed
5 ms
Response code
NOERROR
Rule(s)
||wales^

### Additional information and/or screenshots

I tried adding the $important flag to regex which the rule seems to work still but as I understand it when using regex this theoretically isn't supported by regex, correct?

/.*\.gov(t)?(\.[a-z]{2,4})?$/$important

Does regex only trump hosts syntax lists? if the case this isn't really a bug but maybe a feature request? If adguard syntax rules take take precedence over regex, regex in allow lists become pretty much a moot point in it's use case as mosts blocklists I use are in adguard syntax.

**Comment by ainar-g** [comment]
Your regexp doesn't match `www.gov.wales`, as the word “Wales” has five letters, which is more than four.  Also, you aren't escaping dots, but that's a relatively minor issue.  The `$important` modifier does work, but is unnecessary.

Please use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) to ask questions about filtering rules.
