### ISSUE TITLE
round robin/load balancing requests for a domain | set specefic ip for a domain on group of clients ( via geo and via ip subnets ) 

### ISSUE THREAD

**Issue by miladsoltaniantemp** [AdguardTeam/AdGuardHome#7094]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

- roundrobin/load balancing requests for a domain to multiple ip addresses
for i.e:

we could set multi ip via rewrite rules for example.com, everytime the client request example.com, one of the ip addresses would go to client ( it should support the below feature too - something like roundrobing geodns system ! ) 

- set specefic ip for a domain on group of clients ( via geo and via ip subnets ) 
for i.e:

if clients from 192.168.0.0/24 querid example.com, adguard would say its on 125.251.2.1
if clients from 192.168.10.0/24 querid example.com, adguard would say its on 243.251.2.1
if clients from Germany (country) querid example.com, adguard would say its on 2.2.2.2
if clients from 192.168.0.10/24,185.2.12.0/24,19.2.1.2/24 querid example.com, adguard would say its on 6.2.2.5

### Proposed solution

to maintain loadbalancing and advanced ip rewrite rules

### Alternatives considered and additional information

I didn't see such

**Comment by ainar-g** [comment]
Please rewrite your issue to only request one thing.  Also, your second request can already be done through the `$client` modifier, albeit not with countries.
