### ISSUE TITLE
Log rate limited clients

### ISSUE THREAD

**Issue by Buco7854** [AdguardTeam/AdGuardHome#7105]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

There is currently no way to see when a client is rate limited (please correct me if I am wrong). It can be quite a headache to debug.

### Proposed solution

Display rate limited client in a log file or even in the querylog as rate limited. Or maybe some rate limit stats as requested in #5488 that could make it obvious that some clients are being ratelimited.

**Comment by EugeneOne1** [comment]
@Buco7854, hello.  The rate-limiting events are actually logged at `debug' level, so the verbose log mode is required to see them.  See the [knowledge base](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) for the log configuration.

The desired lines contain the word "ratelimited" and the IP of the restricted client.  Note that rate limiting only applies to the plain DNS-over-UDP protocol.

**Comment by Buco7854** [comment]
> @Buco7854, hello. The rate-limiting events are actually logged at `debug' level, so the verbose log mode is required to see them. See the [knowledge base](https://adguard-dns.io/kb/adguard-home/faq/#verboselog) for the log configuration.
> 
> The desired lines contain the word "ratelimited" and the IP of the restricted client. Note that rate limiting only applies to the plain DNS-over-UDP protocol.

I see, thanks for the reply.

**Comment by JannemanDev** [comment]
edit .`/conf/AdGuardHome.yaml`

add/change:
```yaml
log:
  verbose: true
```

```bash
docker restart adguard
docker logs -f adguard 2>&1 | grep -Ei 'rate.?limit|ratelimit|limited'
```

You can set ratelimit in AdGuard Dashboard > settings >DNS server configuration > Rate limit

you will see lines like `2026/05/15 11:17:07.373560 1#1464 [debug] ratelimit: ratelimited based on ip only addr=192.168.11.155:56478`
