### ISSUE TITLE
why node high cpu usage? when my press test tools execute doh query.

### ISSUE THREAD

**Issue by andylau004** [AdguardTeam/AdGuardHome#7106]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

master

### Action

When I run my stress test tool, executing DOH queries 1000 times per second, the node js process cpu usage is also very high.

when execute  my stress test ,   No web operations are performed  at the same time

i don't know why?

Has anyone has been seen this before

![1719807398696](https://github.com/AdguardTeam/AdGuardHome/assets/2648844/b2e0693a-9266-44e0-a571-3daab79655ea)

### Expected result

I expect node/node js to take up less cpu

### Actual result

![1719807398696](https://github.com/AdguardTeam/AdGuardHome/assets/2648844/d4cd9f6b-01b5-44f2-9448-9328756afeeb)

**Comment by tjharman** [comment]
Hi,

Sorry I'm not sure I understand - what is the issue? I understand your `node` process is showing high CPU, but node has nothing to do with AdGuardHome.  I'm not sure what relationship node has to AdGuardHome?  AdGuardHome doesn't use/rely on node in anyway.

Can you explain more clearly how your node CPU issue is related to AdGuardHome?
