### ISSUE TITLE
I need to change the username.

### ISSUE THREAD

**Issue by bzkmsjy** [AdguardTeam/AdGuardHome#7109]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

My two OpenWrt routers have different usernames for AdGuardHome: one is "root" and the other is "admin." I don't know why this difference exists, but it prevents me from using the same saved account credentials in the browser to log into both devices. I have to manually change the username every time I log in. AdGuardHome does not provide an interface to change the username, and I am not familiar with using terminal commands to modify configuration files. I hope the official team can provide an option to change the username.

### Proposed solution

A graphical interface to change the username

**Comment by Dynamic5912** [comment]
Just change it in the YAML file?

**Comment by tjharman** [comment]
Changing the username is currently only available via editing the config file - a fairly simple process.  I would read up on how to make a simple text edit on your OpenWRT router - the OpenWRT forums should be able to help you with this.
