### ISSUE TITLE
DNS server blocking legit site.

### ISSUE THREAD

**Issue by razz100** [AdguardTeam/AdGuardHome#711]
Hi,

I'm using Adguard DNS servers ( 176.103.130.130
176.103.130.131 ) with my WiFi modem configuration i.e 192.168.1.1.

Everything was working fine but of late it is giving trouble with legit sites.

For example this legit mobile site is not opening with Adguard DNS server :  https://www.91mobiles.com/ . I get DNS_PROBE_FINISHED_NXDOMAIN error on trying to access this site.

What is the issue here? I have checked everything on my end. The site promptly opens up when I use 4g on my phone!

Please look into it and rectify the error. This must be happening with other sites as well!

**Comment by Alex-302** [comment]
@razz100 https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/59

**Comment by razz100** [comment]
Why have you closed the thread/issue without resolving it?

**Comment by ameshkov** [comment]
@razz100 the issue is actually resolved, but it'll take a few hours for the filter list to be updated on the server

**Comment by razz100** [comment]
Ok. Thanks. Pardon my ignorance. Sorry.

**Comment by razz100** [comment]
It is been more than 21 hours, you said few hours, and the issue is still there. I still cannot access 91mobiles.com from your DNS servers.

How much you will need to fix it? Thanks.

**Comment by ameshkov** [comment]
Check your DNS cache:
```
$ nslookup 91mobiles.com 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	91mobiles.com
Address: 13.126.49.44
```

**Comment by razz100** [comment]
Hi,

The issue with the mentioned site Was solved but from today onwards the issue has came back!!

Site not opening with adguard on!! Opening only after disabiling it!!

Please look into it.

Thanks.

**Comment by ameshkov** [comment]
Can't confirm it:
```
$ nslookup 91mobiles.com 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	91mobiles.com
Address: 13.126.49.44
```
