### ISSUE TITLE
2 PTR records are being shown for AGH

### ISSUE THREAD

**Issue by iptvcld** [AdguardTeam/AdGuardHome#7117]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

0.107.51

### Action

nslookup 10.200.1.50
50.1.200.10.in-addr.arpa        name = AdGuardDNS1.example.com.
50.1.200.10.in-addr.arpa        name = AdGuardDNS1.

Authoritative answers can be found from:

My 2nd instance is fine

nslookup 10.200.1.51
51.1.200.10.in-addr.arpa        name = AdGuardDNS2.example.com.

### Expected result

nslookup 10.200.1.50
50.1.200.10.in-addr.arpa        name = AdGuardDNS1.example.com.

### Actual result

I seem to have 2 PTR records for my AGH 1st instance. But if I run the same lookup on my 2nd agh it’s fine and only shows 1 PTR

**Comment by iptvcld** [comment]
This is my host file

127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
# --- BEGIN PVE ---
10.200.1.50 AdGuardDNS1.example.com AdGuardDNS1
# --- END PVE ---

**Comment by iptvcld** [comment]
Any suggestions?

**Comment by tjharman** [comment]
Do you have the same host configured for reverse lookups?

<img width="1154" alt="image" src="https://github.com/AdguardTeam/AdGuardHome/assets/1025029/d3b8b3ed-f11b-4851-b446-b195043f608d">

**Comment by iptvcld** [comment]
@tjharman  yes, I have the same IP on both dns servers. That IP is for my pfsense interface and since I am using sync for my dns servers, they both are the same 

![IMG_4440](https://github.com/AdguardTeam/AdGuardHome/assets/34818686/e3505ca2-4d56-4f32-a6f4-f877799f2cf1)

**Comment by tjharman** [comment]
I see you're running Proxmox.

Is the output of `cat /etc/resolv.conf` the same on both instances?

Also: How are you syncing the two AdGuardHome instances?

**Comment by iptvcld** [comment]
@tjharman Yes, both my DNS AGH servers are on a proxmox node - I have 2 proxmox servers running.

**cat /etc/resolv.conf (DNS1)**
 --- BEGIN PVE ---
search example.com
nameserver 10.200.1.50
nameserver 10.200.1.51
 --- END PVE ---

**cat /etc/resolv.conf (DNS2)**
 --- BEGIN PVE ---
search example.com
nameserver 10.200.1.50
nameserver 10.200.1.51
 --- END PVE ---

As for Sync, i am using an Unraid docker with "lscr.io/linuxserver/adguardhome-sync:latest" as the repo

**Comment by tjharman** [comment]
One last thing before I raise this up to the devs - can you setup a unix/linux host with the "dig" tool installed and verify you get the same results with 
```dig @10.200.1.50 -x 10.200.1.50
dig @10.200.1.50 -x 10.200.1.51
dig @10.200.1.51 -x 10.200.1.50
dig @10.200.1.501 -x 10.200.1.51```

**Comment by iptvcld** [comment]
No problem - I just ran these on a different linux host, below are the results
```
root@Mon:~# **dig @10.200.1.50 -x 10.200.1.50**

; <<>> DiG 9.18.24-1-Debian <<>> @10.200.1.50 -x 10.200.1.50
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31058
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;50.1.200.10.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
50.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS1.example.com.
50.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS1.

;; Query time: 1 msec
;; SERVER: 10.200.1.50#53(10.200.1.50) (UDP)
;; WHEN: Mon Jul 08 16:02:54 EDT 2024
;; MSG SIZE  rcvd: 107
```

```
**root@Mon:~# dig @10.200.1.50 -x 10.200.1.51**

; <<>> DiG 9.18.24-1-Debian <<>> @10.200.1.50 -x 10.200.1.51
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3648
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;51.1.200.10.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
51.1.200.10.in-addr.arpa. 3600  IN      PTR     AdGuardDNS2.example.com.

;; Query time: 1 msec
;; SERVER: 10.200.1.50#53(10.200.1.50) (UDP)
;; WHEN: Mon Jul 08 16:04:06 EDT 2024
;; MSG SIZE  rcvd: 93
```

```
**root@Mon:~# dig @10.200.1.51 -x 10.200.1.50**

; <<>> DiG 9.18.24-1-Debian <<>> @10.200.1.51 -x 10.200.1.50
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36144
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;50.1.200.10.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
50.1.200.10.in-addr.arpa. 3600  IN      PTR     AdGuardDNS1.example.com.

;; Query time: 0 msec
;; SERVER: 10.200.1.51#53(10.200.1.51) (UDP)
;; WHEN: Mon Jul 08 16:05:07 EDT 2024
;; MSG SIZE  rcvd: 93
```

```
**root@Mon:~# dig @10.200.1.51 -x 10.200.1.51**

; <<>> DiG 9.18.24-1-Debian <<>> @10.200.1.51 -x 10.200.1.51
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39601
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;51.1.200.10.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.example.com.
51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.

;; Query time: 0 msec
;; SERVER: 10.200.1.51#53(10.200.1.51) (UDP)
;; WHEN: Mon Jul 08 16:05:47 EDT 2024
;; MSG SIZE  rcvd: 107
```

**Comment by iptvcld** [comment]
Do you think my host file is causing this?

```
127.0.0.1 localhost
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
--BEGIN PVE ---
10.200.1.50 AdGuardDNS1.example.com AdGuardDNS1
--- END PVE ---

My 2nd instance
127.0.0.1 localhost
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
--- BEGIN PVE ---
10.200.1.51 AdGuardDNS2.example.com AdGuardDNS2
--- END PVE ---
```

**Comment by tjharman** [comment]
Ok great to see you're getting 
`51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.` when you query the second host for its IP.

This is just going to be because of your hosts file, yes.
If you were to add

`10.200.1.50 AdGuardDNS1.example.com AdGuardDNS1` to AdGuardDNS2's host file and
`10.200.1.51 AdGuardDNS2.example.com AdGuardDNS2` to AdGuardDNS1's host file I'm sure you'd then find you're getting the same results then.

Please test and confirm.

Thanks!

**Comment by iptvcld** [comment]
```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
# --- BEGIN PVE ---
10.200.1.50 AdGuardDNS1.example.com AdGuardDNS1
10.200.1.51 AdGuardDNS2.example.com AdGuardDNS2
# --- END PVE ---
```

```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
# --- BEGIN PVE ---
10.200.1.51 AdGuardDNS2.example.com AdGuardDNS2
10.200.1.50 AdGuardDNS1.example.com AdGuardDNS1
# --- END PVE ---
```

```
nslookup 10.200.1.50
50.1.200.10.in-addr.arpa        name = AdGuardDNS1.example.com.
50.1.200.10.in-addr.arpa        name = AdGuardDNS1.

Authoritative answers can be found from:
```

```
nslookup 10.200.1.51
51.1.200.10.in-addr.arpa        name = AdGuardDNS2.example.com.
51.1.200.10.in-addr.arpa        name = AdGuardDNS2.

Authoritative answers can be found from:
```

**Comment by tjharman** [comment]
Ok neat - happy to close this as not an Adguard issue?

**Comment by iptvcld** [comment]
So this is normal behavior?

**Comment by tjharman** [comment]
I believe so, yes, but I will ask the devs to look at this ticket before I close it.

**Comment by iptvcld** [comment]
Its just odd that the configs are the same and yet AGH2 shows 1 PTR while AGH1 shows 2 records

**Comment by iptvcld** [comment]
Also, as a test i just I just added both lines to only my AGH1 DNS server
```
10.200.1.50 AdGuardDNS1.example.com AdGuardDNS1
10.200.1.51 AdGuardDNS2.example.com AdGuardDNS2
```

and nslookup has 2 PTR records when i lookup 50 and 51 without having the add the other line to the 2nd dns server

**Comment by tjharman** [comment]
Right, but the second entry is obviously being added by the hosts file entry - we proved that with the fact you get the same result when you query AdguardHome2 for its hostname:

From your post above:
```
root@Mon:~# dig @10.200.1.51 -x 10.200.1.51

; <<>> DiG 9.18.24-1-Debian <<>> @10.200.1.51 -x 10.200.1.51
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39601
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;51.1.200.10.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.example.com.
51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.

;; Query time: 0 msec
;; SERVER: 10.200.1.51#53(10.200.1.51) (UDP)
;; WHEN: Mon Jul 08 16:05:47 EDT 2024
;; MSG SIZE  rcvd: 107
```
You can fix this if it's annoying by following what's in [this thread](https://github.com/AdguardTeam/AdGuardHome/issues/6610).

**Comment by iptvcld** [comment]
Ok, i just changed this config to false and rebooted
```
hostsfile_enabled: false
```

```
nslookup 10.200.1.50
50.1.200.10.in-addr.arpa        name = AdGuardDNS1.example.com.
```

```
dig @10.200.1.50 -x 10.200.1.50

; <<>> DiG 9.18.24-1-Debian <<>> @10.200.1.50 -x 10.200.1.50
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62293
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;50.1.200.10.in-addr.arpa.      IN      PTR

;; ANSWER SECTION:
50.1.200.10.in-addr.arpa. 3600  IN      PTR     AdGuardDNS1.example.com.

;; Query time: 1 msec
;; SERVER: 10.200.1.50#53(10.200.1.50) (UDP)
;; WHEN: Mon Jul 08 21:30:36 UTC 2024
;; MSG SIZE  rcvd: 93
```

Looks like this is fixed the issue for me, thank you! Would you know why this was an issue only for my 1st AGH and was fine for my 2nd server even though they has that config option set to true on both?

**Comment by tjharman** [comment]
It _was_ an issue for your second AdGuardHome. You proved as much with your output [here](https://github.com/AdguardTeam/AdGuardHome/issues/7117#issuecomment-2215139502)

You queried your AdGuard2 host for it's Hostname and you got the same duplicate result:

```
;; ANSWER SECTION:
51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.example.com.
51.1.200.10.in-addr.arpa. 10    IN      PTR     AdGuardDNS2.
```

The issue only appears when you a query a host for its hostname. So when you queried AdguardHome2 for it's Hostname you got the same double result.

**Comment by iptvcld** [comment]
Correct - before i made this change, when i performed a lookup for the IP on AGH1, i was seeing 1 records but only seeing 1 record for the 2nd dns server

```
nslookup 10.200.1.50
50.1.200.10.in-addr.arpa name = AdGuardDNS1.example.com.
50.1.200.10.in-addr.arpa name = AdGuardDNS1.

Authoritative answers can be found from:

nslookup 10.200.1.51
51.1.200.10.in-addr.arpa name = AdGuardDNS2.example.com.
```

**Comment by tjharman** [comment]
That nslookup you're doing is only querying .50 I suspect.
If you force nslookup to query .51 I bet you get the reverse results.

**Comment by iptvcld** [comment]
Before I made the change - I did query both AGH IP's.  The output shown above is one for .50 and the other for .51 just doing a normal nslookup <ip> and only the .50 was returning the 2 records using this command.

I know using the dig commands you provided did indeed show both servers have 2 records each but it was just odd that when performing the above nslookup that only the .50 was showing 2 records.

**Comment by tjharman** [comment]
This is because nslookup is only querying you .50 server.  You were never querying your .51 server with nslookup.

**Comment by tjharman** [comment]
If you revert your change and do

nslookup 10.200.1.51 10.200.1.51 (which will force nslookup to query your .51 server) you'll see what I mean.

You were only ever querying .50, which is why you only saw it on one side, you wery only querying 1 side.

**Comment by iptvcld** [comment]
Thank you, i know get it!  I reversed the changes and can see that it was the same on the 2nd server as well...

Thanks for your guidance on that config change `hostsfile_enabled: false`

**Comment by tjharman** [comment]
Excellent, good stuff. Closing this ticket.
