### ISSUE TITLE
Text overflows on the Query log page

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdGuardHome#7119]
That happens in ipv6 rows.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/11857205/fc8690b3-e034-4338-8c64-240b3ad6b906)

**Comment by trmdi** [comment]
> Could you please state the version you're using, and the browser you're using please?

Adguard Hone Version: v0.107.52
Browser: MS Edge (latest stable version)

**Comment by tjharman** [comment]
Thank you and sorry, I should have asked - has this just started happening (i.e. was it a problem on previous versions)?

**Comment by trmdi** [comment]
> Thank you and sorry, I should have asked - has this just started happening (i.e. was it a problem on previous versions)?

Idk since I've just enabled ipv6 for AGH since this version.

**Comment by tjharman** [comment]
Thanks - I will raise this to the devs.

**Comment by ainar-g** [comment]
Should be fixed in the upcoming v0.107.53.
