### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by no-replies** [AdguardTeam/AdGuardHome#712]
### Steps to reproduce

1. Run time error after adding filter lists

### Actual behavior

2019/04/11 16:08:18 [info] Upstream 0: https://dns.cloudflare.com:443/dns-query
2019/04/11 16:08:18 [info] Upstream 1: 1dot1dot1dot1.cloudflare-dns.com:853
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xa6566d, 0x16)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc024000000, 0x4000000, 0x105a018)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x1041900, 0x2000, 0x1041910, 0x1)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x1041900, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mheap.go:1232 +0x42
runtime.(*mheap).allocSpanLocked(0x1041900, 0x1, 0x105a028, 0xc00002f320)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mheap.go:1150 +0x3a7
runtime.(*mheap).alloc_m(0x1041900, 0x1, 0xc00005001a, 0x454b6b)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mheap.go:1048 +0x4c
runtime.systemstack(0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:311 fp=0xc000079480 sp=0xc000079478 pc=0x456940
runtime.(*mheap).alloc(0x1041900, 0x1, 0x1001a, 0x9f)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mheap.go:1047 +0x8a fp=0xc0000794d0 sp=0xc000079480 pc=0x4246fa
runtime.(*mcentral).grow(0x1042300, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mcentral.go:256 +0x95 fp=0xc000079518 sp=0xc0000794d0 pc=0x417635
runtime.(*mcentral).cacheSpan(0x1042300, 0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mcentral.go:106 +0x2ff fp=0xc000079578 sp=0xc000079518 pc=0x41713f
runtime.(*mcache).refill(0x7fe38f4ef008, 0x1a)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/mcache.go:135 +0x86 fp=0xc000079598 sp=0xc000079578 pc=0x416bd6
runtime.(*mcache).nextFree(0x7fe38f4ef008, 0x1a, 0xa5bdff, 0x3, 0xa5bdfc)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/malloc.go:786 +0x88 fp=0xc0000795d0 sp=0xc000079598 pc=0x40b4f8
runtime.mallocgc(0xc0, 0xa3ed20, 0xa5c001, 0x4)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/malloc.go:939 +0x76e fp=0xc000079670 sp=0xc0000795d0 pc=0x40be0e
runtime.newobject(0xa3ed20, 0xc0066ffc02)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/malloc.go:1068 +0x38 fp=0xc0000796a0 sp=0xc000079670 pc=0x40c218
github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).AddRule(0xc0003440a0, 0xc0066ffc02, 0xd, 0x5caf647f, 0x0, 0x0)
	/home/travis/gopath/src/github.com/AdguardTeam/AdGuardHome/dnsfilter/dnsfilter.go:878 +0x153 fp=0xc0000797d0 sp=0xc0000796a0 pc=0x7894a3
github.com/AdguardTeam/AdGuardHome/dnsfilter.(*Dnsfilter).AddRules(0xc0003440a0, 0xc000114000, 0x20, 0x20, 0x0, 0x12a)
	/home/travis/gopath/src/github.com/AdguardTeam/AdGuardHome/dnsfilter/dnsfilter.go:842 +0xf0 fp=0xc000079898 sp=0xc0000797d0 pc=0x789190
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).initDNSFilter(0xc00008c240, 0x42, 0xde0c8)
	/home/travis/gopath/src/github.com/AdguardTeam/AdGuardHome/dnsforward/dnsforward.go:204 +0xc2 fp=0xc0000798e8 sp=0xc000079898 pc=0x8a49d2
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).startInternal(0xc00008c240, 0xc000079bf0, 0xc00008c26c, 0xc000373800)
	/home/travis/gopath/src/github.com/AdguardTeam/AdGuardHome/dnsforward/dnsforward.go:140 +0x10e fp=0xc000079ad0 sp=0xc0000798e8 pc=0x8a421e
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).Start(0xc00008c240, 0xc000079bf0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/AdguardTeam/AdGuardHome/dnsforward/dnsforward.go:119 +0x80 fp=0xc000079b08 sp=0xc000079ad0 pc=0x8a40d0
main.startDNSServer(0xc000024ae0, 0x16)
	dns.go:77 +0x14c fp=0xc000079cd8 sp=0xc000079b08 pc=0x93235c
main.run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	app.go:116 +0xa4e fp=0xc000079e70 sp=0xc000079cd8 pc=0x91d1ae
main.main()
	app.go:54 +0x1ae fp=0xc000079f98 sp=0xc000079e70 pc=0x91c73e
runtime.main()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200 +0x20c fp=0xc000079fe0 sp=0xc000079f98 pc=0x42dacc
runtime.goexit()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000079fe8 sp=0xc000079fe0 pc=0x458891

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
main.main.func1(0xc000064780)
	app.go:48 +0x34
created by main.main
	app.go:47 +0x17d

</details>

### environment

| Operating system and version:| (e.g. Ubuntu 16)
Clean install

**Comment by ameshkov** [comment]
Could you please attach the `AdguardHome.yaml` file?

**Comment by no-replies** [comment]
Is there a reporting tool like in pihole. Yaml file contains all rules, links, private key etc

**Comment by ameshkov** [comment]
@no-replies well, what I need is the filters section of the config.

> Is there a reporting tool like in pihole.

Nope, not yet.

**Comment by ameshkov** [comment]
@no-replies well, what I need is the filters section of the config.

> Is there a reporting tool like in pihole.

Nope, not yet.

**Comment by no-replies** [comment]
I don't see a reply privately option here either ?

**Comment by ameshkov** [comment]
> I don't see a reply privately option here either ?

You can send it to me directly to `devteam at adguard.com`

**Comment by no-replies** [comment]
Thanks but prefer not too. 

I added whitelist rules, regex and all was ok. Then started added filter lists and only did about 10 and it died. And it won't restart.

**Comment by ameshkov** [comment]
Well, clearly we should optimize memory usage of the filtering engine.

Merged into https://github.com/AdguardTeam/AdGuardHome/issues/714

**Comment by no-replies** [comment]
Any idea how I can get it to restart? I guess delete the .txt 

On another topic it takes ages to set up through GUI. It would be easier if there was a way to add a lists of filter files, whitelist files, regex.

**Comment by ameshkov** [comment]
> Any idea how I can get it to restart?

Just edit the `.yaml` file manually and remove a few filters from there.

**Comment by no-replies** [comment]
OK will do.
FYI it was clean build and was setting up;
Was trying to add 50+ filter links ( which would result in approx 2m when cleaned)
100 regex lines
100+ whitelist lines
100+ blacklist lines

**Comment by no-replies** [comment]
I thought that it was having a number of lists or those with malformed entries that caused the issue but seems that even one host list will do it. [https://github.com/no-replies/blocklist/raw/master/gravity](url)

**Comment by ameshkov** [comment]
@no-replies is there a version of this gravity list that uses hosts files syntax?

This one that you linked will be considered an adblock list, and it will be parsed into a heavier structure.

**Comment by no-replies** [comment]
sorry yes I should've mentioned. It gets converted by a script. But you have got me thinking; Possible causes:
Error Adblock list / error in regex
host file in .txt being added to Adblock list because its a .txt even though in host format

**Comment by ameshkov** [comment]
What matters is that it should look like this:
`0.0.0.0    example.org`

If it is just a list of domains, AGH thinks that this is an adblock list.

**Comment by no-replies** [comment]
well most are 0.0.0.0 but a few are 127.0.0.1 but that should be ok

for example here is another large'ish 127.0.0.1 which will cause the error

**Comment by ameshkov** [comment]
@no-replies let's wait for #714 then. AGH mustn't be that greedy for RAM as it is now.
