### ISSUE TITLE
AdGuard Home freezes by itself after one day 

### ISSUE THREAD

**Issue by Aura67** [AdguardTeam/AdGuardHome#7120]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, ARMv6

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

AdGuard Home v0.107.52 

### Action

I don't know what the action should be, I do nothing and AdGuard home is just freez by itself.

### Expected result

AdGuard Home freezes after about a day, so I have to restart my Raspberry Pi once and then AdGuard works again, but there is a crazy bug in AdGuard Home at the moment. I don't actually do anything, the internet connection is simply gone, and my upstream server is a localhost that listens to 127.0.0.1.

### Actual result

If I restart my Raspberry Pi it works again.

### Additional information and/or screenshots

My OS is Debian Bookworm 12 the current version.

**Comment by tjharman** [comment]
Hi there,

This sounds like a fault with your Raspberry Pi I'm afraid.  But let's explore it a bit more.

When it fails, can you still SSH onsite your Raspberry pi?  If not, can you ping your Raspberry pi?
  
If you still have full remote access to the Raspberry Pi, what does the process table on it look like? Is AdGuardHome still running, or has it ceased running?  If it's ceased, could you please then copy off the log file and upload it to this issue?

Thanks!

**Comment by Aura67** [comment]
How am I supposed to do that now that it has crashed? I restarted it and it is working again. Strangely enough, when I used pihole I never had any crashes with the local host. I didn't change anything on the localhost. And as for the question, do I still have access to the Raspberry Pi when it crashes? No, I don't, only when I restart it. If AdGuard home keeps crashing and it's my Pi then I wonder why pihole never had any problems with it.

**Comment by tjharman** [comment]
It sounds like your entire Raspberry Pi is crashing. I'm sorry but this isn't an AdGuardHome problem.  Potentially your SDCard is failing, maybe AdGuardHome is using a bit more CPU causing it to overheat and lockup, or drawing more power causing instability and crashing.
  
I suggest you go and ask on the Raspberry Pi forums for the best way to debug what might be causing your Pi to fail, but certainly the SDCard would be the first place to look.
