### ISSUE TITLE
Need Latest Magisk Module for AdGuardHome

### ISSUE THREAD

**Issue by mdrakibur179** [AdguardTeam/AdGuardHome#7123]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I want latest AdGuardHome flash able zip of AdGuardHome. There are two Magisk Module of AdGuardHome but those are backdated and after updating, it doesn't work or load AdGuardHome server.

### Proposed solution

Need flash able zip for Magisk of AdGuardHome.

**Comment by tjharman** [comment]
You're probably mixing up the Android version of AdGuard with AdguardHome.  I'm sorry but you've posted in the wrong forum/place and even if it was the correct place, AdGuard do not support (as far as I'm aware) 3rd party builds/setups using Magisk.

**Comment by BokaRoka** [comment]
i think the version made by twoone-3 in GitHub seems stable enough with Magisk v27, i've been using for months now and it's just easy for 3G/4G and wifi to block the ads flawlessly, no battery drain issues so far or RAM chugging's..
