### ISSUE TITLE
Why does this version have a lot of http,https requests to the extranet

### ISSUE THREAD

**Issue by fmqer** [AdguardTeam/AdGuardHome#7127]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```
no

### Expected result

![image](https://github.com/AdguardTeam/AdGuardHome/assets/105900097/1a09c938-cd7b-49be-9721-80c0f4cb0923)

### Actual result

Why does this version have a lot of http,https requests to the extranet

### Additional information and/or screenshots

![image](https://github.com/AdguardTeam/AdGuardHome/assets/105900097/a9ae52d0-616a-4a52-875f-1cbfefde938c)

**Comment by ainar-g** [comment]
You have “Fastest IP address” upstream mode enabled, and that's what it does.  It tries connecting to every IP address to measure the connection speed.
