### ISSUE TITLE
Adguard fail to start when activate "Blocked services" and use web and ios app

### ISSUE THREAD

**Issue by Goldex60** [AdguardTeam/AdGuardHome#7128]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

AdGuard Home, version v0.107.52

### Action

When using web access to configure blocking by service, the service name contains an underscore as a separator, whereas when using the IOS application, the same service name is written with a space.

For example, for "Bingo Live" via web access, the configuration is as follows 
```
  blocked_services:
    schedule:
      time_zone: Local
    ids:
      - bigo_live
```

whereas the configuration via the IOS, the configuration is as follows
```
  blocked_services:
    schedule:
      time_zone: Local
    ids:
      - bigo live
```

Then, when a modification is made, the following error is displayed:
```
Error: control/blocked_services/update | validating: unknown blocked-service "bigo live" | 422
```
and the service won't start until you clean up the AdGuardHome.yaml configuration file.

### Expected result

Via the IOS application, the service names must be correctly entered in the configuration file.

### Actual result

Currently, services are not registered in the same way as via the web interface.

**Comment by tjharman** [comment]
Can you please clarify what you mean by "The iOS application"?  There is no application for AdguardHome.

**Comment by Goldex60** [comment]
Hello,
This is the one
https://apps.apple.com/us/app/adguard-home/id1667119601
I reported the bug to the developer

**Comment by tjharman** [comment]
Thanks. As we can see this isn't an official AdguardHome App, so I am going to close this ticket and you can continue with the developer of the app.
