### ISSUE TITLE
Is this memory usage under Docker considered normal or could this be memory leaks?

### ISSUE THREAD

**Issue by rfgamaral** [AdguardTeam/AdGuardHome#713]
I have opened two issues in these past days that I assumed it was a problem with AdGuard and not my fault, but it actually was my fault (kinda). I'm referring to these two:

- https://github.com/AdguardTeam/AdGuardHome/issues/703
- https://github.com/AdguardTeam/AdGuardHome/issues/709

Both were caused due to me AdGuard Home setup. I'm using this in a Synology NAS with Docker and after a basic observation of memory usage I decided to impose a memory limit of **128MB** to AdGuard's container (as I do to all my containers). This limit was not enough and caused the issues above. Removing the limit, and the problems mentioned on those issues don't even exist (sorry about that guys).

Anyway...

A default installation of AdGuard Home under Docker does not that much memory, 128MB seemed just fine. However, as soon as I added Energized Ultimate Protection list (a 19MB list with more than 800,000 rules), the container memory usage spiked to **more than 300MB**. Doesn't feel right, does it?

Also, at the time of writing my AdGuard Home container is using 281MB and for testing purposes I'm adding `||example.org^` as a custom filter rule. Pressed the "Apply" button and the container just spiked to **more than 500MB**. What!? Removed the filter, pressed the "Apply" button again and memory usage is still above 500MB.

You can now understand why was having issue #703 (while uploading such large list) and issue #709 (while adding/removing custom filter rules) with just 128MB allocated to this container.

For now I just disabled the memory limit for this container but I'm not feeling very comfortable with this, especially judging by the observations above. I'm afraid AdGuard Home container's will use too much memory of my host and bring it to a halt (Docker itself uses all the memory from the host if it can, there's not limits).

So, two questions:

1. Is this memory usage under Docker considered normal or could this be memory leaks? (issue title)
2. What's a sensible memory limit one could use for AdGuard Home Docker container?

**Comment by ameshkov** [comment]
Do you mean virtual memory or RSS?

**Comment by rfgamaral** [comment]
I mean RAM.

**Comment by ameshkov** [comment]
How do you measure it?

The difference is quite important. Go is known to allocate quite a lot of VSZ, but it does not matter much, what's really important is RSS.

> RSS is the Resident Set Size and is used to show how much memory is allocated to that process and is in RAM. It does not include memory that is swapped out. It does include memory from shared libraries as long as the pages from those libraries are actually in memory. It does include all stack and heap memory.

> VSZ is the Virtual Memory Size. It includes all memory that the process can access, including memory that is swapped out, memory that is allocated, but not used, and memory that is from shared libraries.

**Comment by ameshkov** [comment]
How do you measure it?

The difference is quite important. Go is known to allocate quite a lot of VSZ, but it does not matter much, what's really important is RSS.

> RSS is the Resident Set Size and is used to show how much memory is allocated to that process and is in RAM. It does not include memory that is swapped out. It does include memory from shared libraries as long as the pages from those libraries are actually in memory. It does include all stack and heap memory.

> VSZ is the Virtual Memory Size. It includes all memory that the process can access, including memory that is swapped out, memory that is allocated, but not used, and memory that is from shared libraries.

**Comment by ameshkov** [comment]
And one more question -- what exact format of the list did you use?

**Comment by ameshkov** [comment]
I mean from this list: 
https://uploads.adguard.com/up04_9stf6_Energized_Protection_-_ad.porn.malware_blocking..png

**Comment by c0b41** [comment]
I have same problem, after 30 minute adguarhome container crashing.

**Comment by ameshkov** [comment]
There's already a task for optimizing RAM usage on the filter lists: #714

Closing this as duplicate.

**Comment by rfgamaral** [comment]
Sorry for the delay, was on vacation.

> How do you measure it?

Memory usage is reported by the Docker engine.

> And one more question -- what exact format of the list did you use?

AdBlock Filter

**Comment by ameshkov** [comment]
> AdBlock Filter

This is the most "heavy" format, hosts format will use much less.

**Comment by rfgamaral** [comment]
> 
> 
> > AdBlock Filter
> 
> This is the most "heavy" format, hosts format will use much less.

What do you mean by "heavy"? AdBlock Filter takes 19M while RAW hosts takes 23M.

**Comment by ameshkov** [comment]
@rfgamaral AdGuard builds in-memory index structures for both of them.

In the case of hosts files, the structure is a trivial map while for adblock syntax the structure is much more complicated -> more heavy on ram.

**Comment by rfgamaral** [comment]
> In the case of hosts files, the structure is a trivial map while for adblock syntax the structure is much more complicated -> more heavy on ram.

How heavy on RAM would that be once #714 is done?

**Comment by ameshkov** [comment]
> How heavy on RAM would that be once #714 is done?

Twice less heavy, but anyway, adblock-based filter list will be heavier than the hosts file-based.

We might also allow serializing unused filters on a disk, but I am not sure if it's a right thing to do on RPi -- intense disk operations might hurt the SSD.

**Comment by rfgamaral** [comment]
> Twice less heavy, but anyway, adblock-based filter list will be heavier than the hosts file-based.

To conclude, is there any benefit in using an adblock based filter list or the support for that format is available just for feature completeness and/or flexibility?

**Comment by ameshkov** [comment]
> To conclude, is there any benefit in using an adblock based filter list or the support for that format is available just for feature completeness and/or flexibility?

Only if this filter list was created with advanced capabilities in mind (like AdGuard SDN filter for instance).

If this is a hosts file simply converted to adblock syntax, there's no reason to use it.

**Comment by rfgamaral** [comment]
Thank you!
