### ISSUE TITLE
Optimistic caching working principle

### ISSUE THREAD

**Issue by macrocodea** [AdguardTeam/AdGuardHome#7131]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

"I've searched through several articles but I'm still unclear about how AdGuard Home's optimistic cache functions. With optimistic caching enabled, entries are not updated even after the TTL expires, as long as the IP remains accessible. This poses a significant issue for users relying on the fastest IP address, as we always aim to obtain and locally cache as many recent IP addresses as possible, while ensuring they are kept updated."

### Proposed solution

The optimistic cache of AdGuard Home returns the previous result to the client first. However, once the TTL expires, it ensures that the cache is refreshed every time.

### Alternatives considered and additional information

Under this setting, frequently requested DNS entries trigger automatic updates whenever their TTL expires.

**Comment by Dynamic5912** [comment]
What don't you understand?

**Comment by macrocodea** [comment]
> What don't you understand?

How does its cache update—based on the TTL time I set? Does it refresh every time the cache expires, or is there a chance it refreshes as long as the IP can still connect?

**Comment by Dynamic5912** [comment]
> > What don't you understand?
> 
> 
> 
> How does its cache update—based on the TTL time I set? Does it refresh every time the cache expires, or is there a chance it refreshes as long as the IP can still connect?

It's in the documentation?

**Comment by quyleanh** [comment]
> Please send questions to the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a), as is recommended in the checkbox that you've checked while filing this issue as well as in the contribution guidelines.
> 
> If this is a feature request, I do not understand what you're asking for, so please rephrase that. Currently, optimistic mode just makes the cache return expired results with a small TTL while also triggering a refresh.

So what will happen when the expired result from cache is incorrect? Like the IP of a domain has changed?

I think the possibility is low since the result with small TTL will not likely change their IP frequently. But just in case, so I’m asking.

**Comment by Dynamic5912** [comment]
> > Please send questions to the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a), as is recommended in the checkbox that you've checked while filing this issue as well as in the contribution guidelines.
> > 
> > If this is a feature request, I do not understand what you're asking for, so please rephrase that. Currently, optimistic mode just makes the cache return expired results with a small TTL while also triggering a refresh.
> 
> So what will happen when the expired result from cache is incorrect? Like the IP of a domain has changed?
> 
> I think the possibility is low since the result with small TTL will not likely change their IP frequently. But just in case, so I’m asking.

It will get served to clients whilst updating in the background so you get the correct later once updated
