### ISSUE TITLE
High response times with DoT upstream servers

### ISSUE THREAD

**Issue by orosseel** [AdguardTeam/AdGuardHome#7145]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

Using DoT upstream server.

### Expected result

Lower response times then DoH.

### Actual result

Much higher response times.

### Additional information and/or screenshots

<img width="559" alt="Scherm­afbeelding 2024-07-19 om 11 50 47" src="https://github.com/user-attachments/assets/1946fad8-58be-4736-ad6a-9efda0179700">

**Comment by CYAsistemas** [comment]
In my 3 adguard instances
![image](https://github.com/user-attachments/assets/69f3c93a-fe05-445c-be99-3f9c026bd30a)
![image](https://github.com/user-attachments/assets/d9fbdfdf-406b-42e0-944a-ac41744ca1fa)
![image](https://github.com/user-attachments/assets/385abf07-687e-45fc-81bb-393f35941c9c)
