### ISSUE TITLE
Feature request: test TCP connection speed and return the fastest IP

### ISSUE THREAD

**Issue by Zxilly** [AdguardTeam/AdGuardHome#715]
When upstream return a DNS resolved answer,could AdGuard try to connect all the ip and give the client the IP fastest?
This is because in China the “clean” always means slow.

**Comment by ameshkov** [comment]
You mean this?

![](https://uploads.adguard.com/up04_dy3gk_AdGuard_Home.png)

**Comment by Zxilly** [comment]
> You mean this?
> 
> ![](https://camo.githubusercontent.com/50ddd71e4e7a5e254b4c0c45a10736da9902aa12/68747470733a2f2f75706c6f6164732e616467756172642e636f6d2f757030345f647933676b5f416447756172645f486f6d652e706e67)

This means the fastest result from DNS server.Sometimes,the DNS server will return serveral IP,if the AdGuard could try to connect these IP and give the fastest IP to client,the client could get the  better experience

**Comment by Zxilly** [comment]
@ameshkov Any suggestion?

**Comment by ameshkov** [comment]
@Zxilly I got the idea, thank you!

Marked as a feature request, let's see how many people vote for it.

Meanwhile, do you have any examples of the software that actually does it?

**Comment by Zxilly** [comment]
@ameshkov 
https://github.com/pymumu/smartdns
https://github.com/zwhFocus/Installtion/tree/master/DNS-choose/dnschooser
But both are not open-source and the document is in Chinese(Maybe because only China has such terrible network environment)

**Comment by ameshkov** [comment]
What I am interested in is how exactly do they check if IP is available.

Do they send ICMP (ping) the address, or do they actually are try to connect to ports 80 or 443?

**Comment by Zxilly** [comment]
@ameshkov 
According to the article of the second project,it choose to make TCP connect to 80 and 443 because ICMP sometimes is not not allowed by some server.
This means it can not make effort on those applications whick are not using standard http port,but it truly improve the experience of HTTP.

**Comment by alexsannikov** [comment]
1. Test depends on protocol (HTTP/HTTPS/TCP/UDP/etc.);
2. ICMP may be measured, not sure about others protocols;
3. Idea sounds good, looks like some simplified PfR (Performance Routing);
but:
1. Realization of the check may be difficult enough;
2. Fastest response doesn't guarantee fastest service (back-end may be overloaded, for example);
3. Anyway, it must be a user's choice to turn this feature on.

**Comment by ameshkov** [comment]
Well, let's see how many upvotes does this feature request collect. 

It is doable, but it is not easy of course.

**Comment by Zhijie327** [comment]
The Project "SmartDNS" 's document in English
https://github.com/pymumu/smartdns/blob/master/ReadMe_en.md

**Comment by WhoJave** [comment]
Sometimes, I use parallel queries, it return an IP address that  have no access to it . Cause we use Chinese public DNS... Maybe you could according the GEOIP to judge which DNS Server we could use , Or give us a choice . thx

**Comment by thb007** [comment]
I also requested to increase the DNS resolution to return the fastest ip to the user, otherwise this will cause the page to open very slowly.

**Comment by rufengsuixing** [comment]
there are some downloads use muti cdn to speedup download,block slower ip may have bad influence,if you want to use,maybe you can set smartdns as the only upstream of AdGuardHome

**Comment by QiuSimons** [comment]
> Well, let's see how many upvotes does this feature request collect.
> 
> It is doable, but it is not easy of course.

SmartDNS is finally open source, can you refer to its source code? I think this will be helpful for this project.

https://github.com/pymumu/smartdns

**Comment by ameshkov** [comment]
@QiuSimons thank you, we'll take a look!

**Comment by lordraiden** [comment]
Is smartdns functionality going to be release in 0.102?

**Comment by ameshkov** [comment]
Yes

**Comment by lordraiden** [comment]
> 
> 
> Yes
This is a huge improvement, thanks a lot.
Please try to expose as much configuration settings as possible if not all through the interface, if this is too much put it somewhere more hidden under advanced settings but still available in the UI.
https://github.com/pymumu/smartdns/blob/master/ReadMe_en.md#configuration-parameter

Having as well advanced settings for the cache avaialable in the interface would be nice.
Similar to what you can see in the right side of this screenshot.
https://forum.netgate.com/assets/uploads/files/1567263869587-settings.png

**Comment by sassansh** [comment]
Any benefit in using this outside of China?

**Comment by ameshkov** [comment]
@sassansh regardless of your location, it can improve connection quality and make it more reliable as it will make sure that the IP addresses are really reachable from your locations. Just don't use it with too many resolvers, 2-3 max.

**Comment by sassansh** [comment]
@ameshkov cool! can it be used with just 1 resolver?

**Comment by ameshkov** [comment]
@sassansh sure, but in this case, it will simply filter out unreachable/slow IPs from domains with multiple IPs (different CDNs and such).

**Comment by sassansh** [comment]
@ameshkov so is it best to use 2-3 resolvers when using this feature?

**Comment by sassansh** [comment]
I set it up as such:
![image](https://user-images.githubusercontent.com/40008576/82078107-72e31680-9695-11ea-8285-8711c5d16534.png)
We'll see how it goes...

**Comment by yegle** [comment]
Scratching my head for a while before realizing the options "Fastest IP address" and "Parallel requests" are mutual exclusive :-(

Why not changing them to radio?

**Comment by ameshkov** [comment]
Yeah, we'll make it clear in the next update:)
