### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xhily** [AdguardTeam/AdGuardHome#716]
### Steps to reproduce

add dns 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x89eb26]

goroutine 54 [running]:
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).logDNSMessage(0xc00008d200, 0x0)
        /home/travis/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.12.0/proxy/proxy.go:903 +0x26
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0xc00008d200, 0xc001974500, 0x1f, 0x1f)
        /home/travis/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.12.0/proxy/proxy.go:851 +0x178
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(0xc00008d200, 0xc00197c100, 0x1f, 0x1f, 0xc0e340, 0xc001925a40, 0xc001571b80)
        /home/travis/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.12.0/proxy/proxy.go:583 +0x219
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
        /home/travis/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.12.0/proxy/proxy.go:553 +0x322
![image](https://user-images.githubusercontent.com/15966687/56058463-09a71a80-5d94-11e9-92f0-d5f3f08058ab.png)

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)
CENTOS 7 X64

**Comment by xhily** [comment]
Sorry, I found the problem.

**Comment by ameshkov** [comment]
@xhily what was the problem?

It's just this is not okay for AGH to crash, we'd better handle this case.

**Comment by htjain** [comment]
I am facing same issue today. @xhily  what was the problem ?

`[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x43b944]

goroutine 36 [running]:
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).handleDNSRequest(0x2888360, 0x28a6000, 0x3aa4050, 0x0, 0x0)
        /home/pi/AdGuardHome/dnsforward/dnsforward.go:463 +0x1fc
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0x28a6000, 0x3aa4050, 0x2c, 0x2c)
        /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:927 +0x1c4
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(0x28a6000, 0x2b0a090, 0x2c, 0x2c, 0x7988e8, 0x3970020, 0x2c399d8)
        /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:638 +0x1b8
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0x28a6000, 0x2b0a090, 0x2c, 0x2c, 0x7988e8, 0x3970020, 0x2c399d8)
        /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:606 +0x4c
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
        /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:605 +0x340
`

**Comment by szolin** [comment]
@htjain What did you do before this happened? Can you show logs?

**Comment by ameshkov** [comment]
@szolin I've filed a new bug report about this:
https://github.com/AdguardTeam/AdGuardHome/issues/941

**Comment by htjain** [comment]
> 
> 
> @htjain What did you do before this happened? Can you show logs?

It was working fine for sometime. Suddenly stopped working after reboot.
I think it has something to do with  config in AdGuardHome.yaml file. 
After creating new config file its not crashing anymore.  
I dont have access to my rpi right now will share original config file in sometime, AdGuardHome always crashing with that file.

**Comment by xhily** [comment]
> I am facing same issue today. @xhily what was the problem ?
> 
> `[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x43b944]
> 
> goroutine 36 [running]:
> github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).handleDNSRequest(0x2888360, 0x28a6000, 0x3aa4050, 0x0, 0x0)
> /home/pi/AdGuardHome/dnsforward/dnsforward.go:463 +0x1fc
> github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0x28a6000, 0x3aa4050, 0x2c, 0x2c)
> /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:927 +0x1c4
> github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleUDPPacket(0x28a6000, 0x2b0a090, 0x2c, 0x2c, 0x7988e8, 0x3970020, 0x2c399d8)
> /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:638 +0x1b8
> github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0x28a6000, 0x2b0a090, 0x2c, 0x2c, 0x7988e8, 0x3970020, 0x2c399d8)
> /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:606 +0x4c
> created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
> /home/pi/gopath/pkg/mod/github.com/!adguard!team/dnsproxy@v0.18.3/proxy/proxy.go:605 +0x340
> `

I added a wrong ad source, delete it and start it.
