### ISSUE TITLE
Encrypted DNS invalid

### ISSUE THREAD

**Issue by Honglan233** [AdguardTeam/AdGuardHome#7165]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

I enabled encrypted DNS

### Expected result

Encrypted DNS be running

### Actual result

https shows that the certificate is configured correctly, but it is unable to connect to the encrypted DNS

**Comment by tjharman** [comment]
Are you sure you're quering your adguard home DNS?

Have you setup a proper valid SSL certificate on your Adguard Home DNS server?

**Comment by Honglan233** [comment]
> 你确定你正在查询你的adguard家庭DNS吗？
> 
> 您是否在Adguard Home DNS服务器上设置了正确有效的SSL证书？

yes
![Screenshot_20240805_124300_com microsoft emmx](https://github.com/user-attachments/assets/588f30a8-967d-42e6-831b-9adabd1496ab)

**Comment by Honglan233** [comment]
> 你确定你正在查询你的adguard家庭DNS吗？
> 
> 您是否在Adguard Home DNS服务器上设置了正确有效的SSL证书？

yes
![Screenshot_20240805_124300_com microsoft emmx_edit_103869608291961](https://github.com/user-attachments/assets/493f912c-bd10-44fc-a962-ca4db342f8ed)

**Comment by Honglan233** [comment]
Encrypted DNS is now invalid'

**Comment by tjharman** [comment]
What is the client that is unable to connect? Is it an Android phone?

**Comment by Honglan233** [comment]
> What is the client that is unable to connect? Is it an Android phone?

right, but I didn't test the other devices

**Comment by Honglan233** [comment]
Well, I found a weird thing, when I use VPN, I can access encrypted DNS normally

**Comment by ainar-g** [comment]
1. What precisely do you mean by “unable to connect to the encrypted DNS”?  Can you use tools like [`dnslookup`](https://github.com/ameshkov/dnslookup) or `dig +tls` to reach it?
2. Do you see any errors in the [verbose logs](https://adguard-dns.io/kb/adguard-home/faq/#verboselog)?
3. As mentioned before, please make sure that your AGH instance is actually accessible from the device you're using.

**Comment by Honglan233** [comment]
> 1. What precisely do you mean by “unable to connect to the encrypted DNS”?  Can you use tools like [`dnslookup`](https://github.com/ameshkov/dnslookup) or  to reach it?`dig +tls`
> 2. Do you see any errors in the [verbose logs](https://adguard-dns.io/kb/adguard-home/faq/#verboselog)?
> 3. As mentioned before, please make sure that your AGH instance is actually accessible from the device you're using.

1. The phone can't use dnslookup and dig, so I used ping, and all domains are unknown hosts
2. Not in my opinion, I'm here to provide the documents
[err.txt](https://github.com/user-attachments/files/16495125/err.txt)

**Comment by ainar-g** [comment]
> Well, I found a weird thing, when I use VPN, I can access encrypted DNS normally

Considering this and the lack of any TLS-related errors in the log, it is likely some form of misconfiguration.

**Comment by Honglan233** [comment]
> > Well, I found a weird thing, when I use VPN, I can access encrypted DNS normally
> 
> Considering this and the lack of any TLS-related errors in the log, it is likely some form of misconfiguration.

you are right

**Comment by Honglan233** [comment]
I finally found the problem：
 The PRC government blocked the undocumented port 853 used to encrypt DNS
