### ISSUE TITLE
Adding mysql/mariadb connection

### ISSUE THREAD

**Issue by joaopinto14** [AdguardTeam/AdGuardHome#7172]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I wanted to store the session data and statistics in a database to facilitate the use of several redundancy instances with docker swarm, and not only

### Proposed solution

It would be better to access through other applications if it had the possibility of saving to a database

**Comment by D13410N3** [comment]
Hello.
AdGuard Home stores query log in JSON file.
You can use log processing software, such as logstash or vector for collecting logs and sending them to MySQL.
