### ISSUE TITLE
Can we have dns over quic ? 

### ISSUE THREAD

**Issue by Techguyprivate** [AdguardTeam/AdGuardHome#718]
Does AdGuardHome support dns over quic ? 

If not , can we have dns ove quic support  ? 

I read that dns over quic is fast , with low latency . It is basically dns over udp but secure.

**Comment by ameshkov** [comment]
Well, eventually we will get it, but at the moment it is not ready. There are no clients nor servers implementation, it's pure theory at the moment.

Hopefully, IETF QUIC will become a part of the Go language, it will make things easier.
