### ISSUE TITLE
Entries with $important followed by comments are ignored

### ISSUE THREAD

**Issue by Retold3202** [AdguardTeam/AdGuardHome#7182]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

Create a rule with `$important` followed by a comment. Ex:

`@@||domain.com^$important # Test`

### Expected result

`domain.com` should be whitelisted.

### Actual result

`domain.com` is not whitelisted, and instead the entire rule is ignored.

**Comment by ainar-g** [comment]
Comments must be on their own lines.  See <https://adguard-dns.io/kb/general/dns-filtering-syntax/#comments>.

**Comment by Retold3202** [comment]
@ainar-g Why doesn't this same behavior occur then for rules without modifiers? 

Ex. `||domain.com^ # Comment` works fine?

**Comment by ainar-g** [comment]
No, it won't work either.  If you have an example, please demonstrate with e.g. `dig` and make sure it's not blocked by one of the other enabled lists.

**Comment by Retold3202** [comment]
@ainar-g I just tested, and I'm embarassed to admit that you're correct...

Apologies for wasting your time & thanks for getting back to me promptly.
