### ISSUE TITLE
Youtube Adds

### ISSUE THREAD

**Issue by cey-tech** [AdguardTeam/AdGuardHome#7187]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

OpenBSD, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

Version: v0.107.52

### Action

Hi,

I use the AGH version on unraid OS and try to build my own DNS-:Server at home.
It blocks most contents,  gut it didn't block Youtube Add like the brwoser plugin.

The thing is, yes google ist against addblocker, but there was a case for europa and
the judge's decided, that google can't do anything in europa against add-blocker
so in the perspectives of the law, we can use add-blocker.

The question is: is there any way to block YT-Adds in all devices via adguard home?

### Expected result

Block Youtube Adds

### Actual result

Block most adds, but not the adds from youtube.

**Comment by Aura67** [comment]
You can't block YouTube ads with AdGuard Home and Pihole. It won't work at DNS level. If you want to block ads on YouTube, you should install an adblocker from Adguard for your browser, which can block it for you. The question is how long this will last, because YouTube is taking extreme action against adblockers.
