### ISSUE TITLE
How to disable Adgaurdhome for a short period of time quickly, easily with a few clicks ?

### ISSUE THREAD

**Issue by Techguyprivate** [AdguardTeam/AdGuardHome#719]
Extremely sorry for asking such a question, but I use adguardhome on linux mint. Sometimes, I need to have my isp dns , that unsecured cause when my data cap end , it prompted me to recharge . But with adguard , the prompt or redirection doesn't happen. It happen only when using my isp default dns , that unsecure, plain . Also sometimes , it is required for some local stuffs like streaming ,accessing certain website or  features. 

So my basic question is how to disable adguardhome or dns for 

1. Quickly . With a few clicks.

2. For a short period of time.

Doing  just  ,  " ./AdGuardHome -s stop " ( without the bracket of course) , stops the adguardhome service, but my net stops. I have to either enable or start  systemd-resolved , then restart my computer. I haven't found any reliable , fast ,easy way to quickly stop, disable for a short time & then enable it  again. 

Anyway, thanks for your free service in advacnce.

**Comment by ameshkov** [comment]
The only way is to do the following:
1. Click "Disable protection" in AGH
2. Go to settings -> enter your ISP DNS addresses instead of what you have there

**Comment by Techguyprivate** [comment]
ok, thank you a lot.

**Comment by Levdbas** [comment]
Hi @ameshkov , 

I switched from Pi-hole to Adguard Home a few months back and no regret! It works perfectly! One feature I miss from Pi-hole though is to disable the filtering for a set amount of time. See [screenshot of pihole feature](https://discourse.pi-hole.net/uploads/default/original/1X/d6495d1b86e09666c66322ba5a378155ca0bb58c.png).

As a webdeveloper I have to work on analytics integrations from time to time or other tracking tools. Something I do not like about my job, but here we are. In pihole I could disable the filtering for a set amount of time. Say a few hours. And it would turn on afterwards. Right now I disable Adguard home via the interface but I forget to turn it back on at the end of the day. So I would really like some this being implemented. If I need to reiterate a bit more in a new issue, let me know :)
