### ISSUE TITLE
[Wiki] Please add article about regexp usage in own filters

### ISSUE THREAD

**Issue by alexsannikov** [AdguardTeam/AdGuardHome#721]
AdGuard Home is a DNS filter.
As this is not complete filtering solution, several features are not applicable for filter rules (i.e. cosmetic filters, 3rd party stuff etc.). 
Could you explain in the new article how to build own filters and how to use regular expressions for this purpose?
I understand that AdGuard has well documentation on their web site, but as I mentioned above only DNS-related filtering may be applied for AG Home, and we need to know exact scope.
Thanks.

**Comment by ameshkov** [comment]
Makes sense, we will add a better explanation.

**Comment by ameshkov** [comment]
@IldarKamalov please add a link here:
https://kb.adguard.com/en/general/dns-filtering-syntax
