### ISSUE TITLE
Is there a way to sync user filters across devices with AdGuard Chrome extension?

### ISSUE THREAD

**Issue by os9sur** [AdguardTeam/AdGuardHome#7211]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

As the number of user filtering rules increases with the use time, it is hoped that automatic backup can be achieved so that it can be synchronized across devices. Similar to tempermonkey, which can automatically back up to Google Drive, etc. 

### Proposed solution

Hope to synchronize the user filter rule list across devices

**Comment by Dynamic5912** [comment]
AGH doesn't offer a browser extension
