### ISSUE TITLE
WebUI can't change dns rewrites

### ISSUE THREAD

**Issue by JunTsao** [AdguardTeam/AdGuardHome#7214]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

Last

### Action

When I attempt to modify a record in DNS rewrite through the web console

### Expected result

Successfully saved the DNS rewrite record

### Actual result

Unable to save changes.

### Additional information and/or screenshots

Good Evening Sir

I am running AdGuard Home on a Windows Server 2019, and it had been running smoothly before. However, recently I noticed that I am unable to modify DNS rewrite records. When I attempt to modify a record in DNS rewrite through the web console, AdGuard fails to update the existing record. There is a notification in the bottom right corner that says, 'Error: control/rewrite/update | Network Error'. I couldn't find any useful information in the Windows logs.

I found that other functional modules are working fine. After testing, I discovered that the web console allows me to add and delete DNS rewrite records, but I am unable to modify existing records. However, I can directly update records by editing the YAML configuration file. I've also tried running the AdGuard Home service under a different administrator account and even reinstalling the service, but the issue still persists.

![20240827-090758](https://github.com/user-attachments/assets/0bdfeda4-5cd8-47af-8b0f-eae95871dcbd)

**Comment by ainar-g** [comment]
A few questions:
1. What errors do you see in the browser console?
2. What errors do you see in the logs of the AdGuard Home service?

**Comment by JunTsao** [comment]
> A few questions:
> 
> 1. What errors do you see in the browser console?
> 2. What errors do you see in the logs of the AdGuard Home service?

Hello, Sir. I apologize for forgetting to check the browser's devtools. In the Edge browser's devtools, I obtained some information, but for the AdGuard service, there are no error messages recorded in the Windows Event Viewer
![PixPin_2024-08-28_09-42-12](https://github.com/user-attachments/assets/a2b0c36c-bd87-43b1-9896-ee78eba0eaee)

**Comment by JunTsao** [comment]
> A few questions:
> 
> 1. What errors do you see in the browser console?
> 2. What errors do you see in the logs of the AdGuard Home service?

Thank you for the hint. I found the issue: there is a firewall between the client and the AdGuard server that was filtering HTTP PUT requests, which prevented me from modifying the DNS rewrite records from my computer.
