### ISSUE TITLE
Dont limit max password limit

### ISSUE THREAD

**Issue by Mrgaton** [AdguardTeam/AdGuardHome#7222]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Its useless to have a password length limit if some users want long passwords why limit it?

### Proposed solution

Just hash the password and send it already hash it for example

**Comment by polarathene** [comment]
> Its useless to have a password length limit if some users want long passwords why limit it?

IIRC, one issue some have had with no limit was an attacker could send a password that was like many GB in size to disrupt/OOM services. So you'd still want to have some kind of limit?

As you opened an issue about length as an issue, did you have a specific length you tried that was problematic?

---

> Just hash the password and send it already hash it for example

Pre-hashing client-side before sending as input server-side should be fine too, but that'd be a breaking change (_existing bcrypt hash is for original input_). Could be an opt-in, but you could still set a length limit without pre-hashing.

bcrypt does have a limit of 72 bytes IIRC which can be as short as 3 emoji. Depends if AdGuard hashes the input server-side already before putting through bcrypt, otherwise raising limit doesn't help AFAIK (_in some past bcrypt implementations it actually weakened security as 73 byte length truncated the first 72 bytes and the password instead became that last byte, such as a single letter_).

**Comment by Mrgaton** [comment]
Bcrypt has a hash length limit?

**Comment by polarathene** [comment]
The hash/digest you get as output from bcrypt is always fixed size, but the input length has affected some implementations of bcrypt before:

https://security.stackexchange.com/questions/92175/what-are-the-pros-and-cons-of-using-sha256-to-hash-a-password-before-passing-it/243834#243834

> _While the limit is 72 bytes, [some implementations may truncate/limit input to a 55 character length string](https://en.wikipedia.org/wiki/Bcrypt#User_input)(56 when including the null terminator byte)._

> _Using a hash to keep the length of input constrained also avoids implementation bugs (fixed OpenBSD 2014, [NodeJS 2020](https://portswigger.net/daily-swig/bcrypt-hashing-library-bug-leaves-node-js-applications-open-to-brute-force-attacks)), where passwords exceeding 255 bytes overflowed an 8-bit string length which could treat the password as only a few characters long instead._

https://en.wikipedia.org/wiki/Bcrypt#User_input

> _Many implementations of bcrypt truncate the password to the first 72 bytes, following the OpenBSD implementation._
> 
> _One brief comment in the text mentions, but does not mandate, the possibility of simply using the ASCII encoded value of a character string: "Finally, the key argument is a secret encryption key, which can be a user-chosen password of up to 56 bytes (including a terminating zero byte when the key is an ASCII string)."_

> _bcrypt has a maximum password length of 72 bytes._
> 
> _The password (which is UTF-8 encoded), is repeated until it is 72-bytes long. For example, a password of:_
> 
> _`correct horse battery staple␀` (29 bytes)_
> 
> _Is repeated until it matches the 72-bytes of the 18 P per-round subkeys:_
> 
> _`correct horse battery staple␀correct horse battery staple␀correct horse` (72 bytes)_

---

Some implementations offer to put the input through something like SHA-512 or similar to compress the input into a fixed size that avoids those concerns, or the software that calls into bcrypt pre-hashes the input for the same purpose to avoid such concerns.

**Comment by Mrgaton** [comment]
Pre compressing with sha512 looks good to me

**Comment by polarathene** [comment]
> the problem is that would be a breaking change

Yes I said that in my first comment to you. You could have it as an opt-in.

For the most part though, you should have enough length as-is. For example `detailed snail summons slim lab coat` is 36 chars/bytes long and offers 48 bits of entropy (_generated from `getapassphrase.com`_).

Once that is put through something like bcrypt with a work factor of 10, that type of entropy would take [over 1000 years with a single nvidia RTX 4080 GPU](https://github.com/FusionAuth/fusionauth-issues/issues/85#issuecomment-1493371525) to attack

That is if the attacker has your bcrypt hash already available to them (_otherwise latency is way higher_), along with [Kerckhoffs's principle](https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle) where they are assumed to know how you created your password (_otherwise entropy is higher_). Other than that, you'd have to question how valuable is that adguard password to the attacker, are they really going to invest that much resources into acquiring it, or would it be more affordable to get that information through other attacks if they want it that badly?

A better password policy would be a better solution for you. Hopefully this information makes you more comfortable. Please note the passphrase example I gave above while strong under the conditions mentioned is not strong if you can't trust the service is storing the password correctly (_some still use plain text, or much weaker password hash methods_). It should be fine with most notable/trustworthy services, but you're often better using a password manager that generates and manages the passwords for you.

**Comment by Mrgaton** [comment]
It's not big deal if isn't implemented but I got a bit angry when my favorite password for mi domain didn't worked for sing up my account. But if you want to make new installation use the new unrestricted hash generator no problema for me.
