### ISSUE TITLE
when nslookup , resturn result server : Unhnown

### ISSUE THREAD

**Issue by Poiig** [AdguardTeam/AdGuardHome#7229]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

PS C:\Users\PoiigZhao> nslookup www.recloud.com.cn 10.10.10.2
服务器:  UnKnown
Address:  10.10.10.2

非权威应答:
名称:    www.recloud.com.cn
Address:  139.217.235.117

### Expected result

![image](https://github.com/user-attachments/assets/de266db2-ced8-4f73-8715-3216b9906193)

when i use 218.4.4.4  to resolve dns , show servername is correct

### Actual result

![image](https://github.com/user-attachments/assets/a2772dc2-7a57-4014-a88a-dcebfab1da88)

**Comment by tjharman** [comment]
There is no fault here. You are still getting the DNS name resovled.

The "UnKnown" is just it doesn't have a DNS name for your 10.10.10.2 DNS server.
If you add a static entry into adguard that maps 10.10.10.2 to whatever hostname you want to appear, that error will go away.

There's no fault here, however.

**Comment by Poiig** [comment]
![image](https://github.com/user-attachments/assets/b28fc68a-3c15-4347-a106-0ac6e786e757)

I have tried this method, but it was useless.

![image](https://github.com/user-attachments/assets/c88f6d3f-c0ba-4b52-99d0-c6b70c5bc7ed)

**Comment by tjharman** [comment]
I'm pretty sure that Windows uses the currently configured DNS server for the 10.10.10.2 reverse lookup.

Is 10.10.10.2 currently Window's configured DNS server?

**Comment by Poiig** [comment]
![image](https://github.com/user-attachments/assets/36af2c9f-9b10-45c7-838d-181185430616)

Yes

**Comment by tjharman** [comment]
Hmm yes, I guess AdguardHome doesn't support reverse DNS lookups configured on itself.  It works for me, but that's becuase my upstream DNS server is doing the reverse mapping.

Regardless, I still don't consider this a bug.  AdguardHome is designed to block ads, I don't think there's a valid use-case for needing to properly answer specific reverse DNS lookups, is there (aside from the fact it reports unknown in nslookup)

**Comment by Poiig** [comment]
Yes, I also don't think it's a bug. But as an optimization item, we hope to support it in the future. SmartDns seems to have this feature.
