### ISSUE TITLE
Is there no default timeout for upstream DNS queries?

### ISSUE THREAD

**Issue by daitou05** [AdguardTeam/AdGuardHome#7234]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

AdGuardHome
```sh
[root@localhost ~]# /usr/local/AdGuardHome/AdGuardHome --version
AdGuard Home, version v0.107.52
[root@localhost ~]#
[root@localhost ~]# cat /proc/version
Linux version 3.10.0-1160.119.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 4 14:43:51 UTC 2024
[root@localhost ~]#

```
I found that when I fill in some DNS with relatively slow responses in "Upstream DNS servers", the AdGuardHome process will freeze. After freezing, it cannot provide DNS services. The DNS strategy is "fastest ip address".

![image](https://github.com/user-attachments/assets/2b776353-13b2-4cac-99ee-85ab1e369961)

### Expected result

I suspect that multiple upstream DNS queries are initiated simultaneously, and the DNS does not respond in time, resulting in the AdGuardHome process freezing. Can I configure a request timeout time for upstream DNS?

### Actual result

Can I configure a request timeout time for upstream DNS?

**Comment by Dynamic5912** [comment]
Use Parallel instead

**Comment by he-pennypacker** [comment]
> Use Parallel instead

Agreed

FWIW, DNS timeout is configurable in AdGuardHome.yaml

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

There's a section there called Other settings, and in there is `upstream_timeout`. Default is 10s.

**Comment by daitou05** [comment]
@he-pennypacker thanks a lot
