### ISSUE TITLE
It continues to work even when disabled

### ISSUE THREAD

**Issue by SionS4R** [AdguardTeam/AdGuardHome#7238]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

The disable protection button is not working properly.

Logs are suspended correctly, but filters are found to be active.
The only way to stop filtering is to act on the individual blacklists by disabling them

Thank you

### Expected result

Disable protection

### Actual result

protection still active

**Comment by Dynamic5912** [comment]
How are you finding the filters still active?

**Comment by tjharman** [comment]
Could you be a little clearer on the steps to reproduce?

It sounds like the issue is probably your client caching the fact a domain has been blocked.

Can you clearly reproduce the problem by quering your AdguardHome with nslookup/dig etc?

**Comment by schzhn** [comment]
We assume that you are getting a cached response in the browser.
```
