### ISSUE TITLE
How to disable the URL path of a domain name

### ISSUE THREAD

**Issue by lan-teacher** [AdguardTeam/AdGuardHome#7240]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

For example, I have a domain name that is http://example.com/test/123.txt This is a normal request, but he also requested an advertising address http://example.com/test/456.txt I need to intercept this 456.txt. How should I intercept it

### Proposed solution

You can add it directly to the custom rules. I tried adding it directly|| http://example.com/test/456.txt ^This rule was intercepted by adguardhouse's test, but the request in the app still passed

### Alternatives considered and additional information

I don't know what other options are available. If you have any, please provide them to me

**Comment by tjharman** [comment]
You are confusing Adguard DNS server with a Web Filter.

AdGuardHome can control a yes/no answer on http://**example.com**/test/456.txt the bit in bold.  It can't control if you're making a http or a https (or SNMP, SMTP, SSH) connection, nor if it's a HTTP/HTTPS connection, the path that's being requested.
