### ISSUE TITLE
block spam websites

### ISSUE THREAD

**Issue by olumolu** [AdguardTeam/AdGuardHome#7242]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

1000fapvids.online
ddbca.localmeets.link

### Proposed solution

Spam websites i find this but does not have a good look what it does actually.

**Comment by tjharman** [comment]
This Issue tracker is for issues with the AdguardHome software itself. Filter list issues should be raised with the relevant maintainers, or of course you can add your own filters to AdguardHome to control what is/isn't allowed.
