### ISSUE TITLE
Custom client upstream DNS cache configuration not working properly

### ISSUE THREAD

**Issue by MiKing233** [AdguardTeam/AdGuardHome#7250]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

Custom package (OpenWrt, HomeAssistant, etc; please mention in the description)

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.52

### Action

在ADGH的web管理界面頂部的"Settings-Client settings"中, 點擊"Add Client", 設定名稱, 並使用IP地址Identifier辨識該客戶端, 在"Upstream DNS servers"標籤頁, 設定一個與全局上游DNS不一樣的DNS伺服器, 並在底部勾選"Enable DNS caching for this client's custom upstream configuration", 并設定"DNS cache size", 例如134217728bytes

### Expected result

此時, 該客戶端的DNS請求應使用單獨設定的DNS上游伺服器, 并且存在DNS緩存

### Actual result

但實際結果是, 自定義客戶端的DNS緩存并不生效, 通過檢查log發現, 每一次請求都會從上游DNS伺服器請求, 即使一直請求相同的域名, DNS緩存也不會正常工作, 檢查請求詳情, 其中也并未出現"Served from cache:✅"

**Comment by schzhn** [comment]
We've pushed the [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) that contains the fix.
