### ISSUE TITLE
Cannot enable TLS via `-s reload`

### ISSUE THREAD

**Issue by rea1shane** [AdguardTeam/AdGuardHome#7265]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

```sh
sed -i '/^tls:$/!b;n;/^  enabled: false$/s/false/true/' /opt/adguardhome/conf/AdGuardHome.yaml
/opt/adguardhome/AdGuardHome -s reload
```

### Expected result

TLS enabled

### Actual result

TLS not enabled

**Comment by tjharman** [comment]
Do you have valid SSL certificates?

**Comment by rea1shane** [comment]
Yes. Manually enable it works, but reload it doesn't.

**Comment by fernvenue** [comment]
Because enable TLS need to bind on additional port, reload can't do that, that's expected behavior.
