### ISSUE TITLE
Add "Clients" settings section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#727]
The idea is to have different client configurations.

Mockups:
* https://uploads.adguard.com/up04_gpo58_Diagrams_-_AGHome_Clients__Moqups.png
* https://uploads.adguard.com/up04_c1xw7_Diagrams_-_AGHome_Clients__Moqups.png

**Edit:** I missed the `Name` field in the mockups.

Possible "client" identifiers:

* IP address
* Mac address

> Mac address is useable only if AGH DHCP server is active.

What can be configured for a client:
1. Blocking domains
2. Browsing security
3. Parental control
4. Safe search

**Comment by rfgamaral** [comment]
I just want to add to this feature request that you should allow multiple IPs for the identifier and not just one. For instance, I have some clients on my network that make requests both in IPv4 and IPv6 and would love to categorized them both as the same client.

There's also another similar situation that is when you're using a VPN to access your home network or redirecting all traffic through your home connection. I have my VPN configured to use the AdGuard DNS server and all clients are identified by the VPN IP instead. So I need at least 2 IPv4 and one IPv6 identifier for a particular client.

Perhaps the IP field could support a mix of IPv4/IPv6 addresses and you could allow for that field to be a list of IPs, separated by commas, and not just a single IP.

Food for thought :)

**Comment by ameshkov** [comment]
Hm, this might complicate things. @szolin thoughts?

**Comment by szolin** [comment]
I think we can support a list of IP addresses per client, but not in the upcoming release.  We should start with just a single IP per client.

**Comment by Vansinnet** [comment]
Hello!

This feature is not working for me in 0.96. The client I have configured is filtered according to global rules (no security module, no parental controls and no enforced Safe Search), even though I set client to this:

![2019-06-06](https://user-images.githubusercontent.com/46295914/59053620-1fb3f180-8892-11e9-9186-5623c6a8b37f.png)

Is this a known issue or is there anything wrong on my end?

**Comment by ameshkov** [comment]
Just when I started thinking there will be a release without a hotfix following it :)

@szolin I can confirm, something is broken.

**Comment by ameshkov** [comment]
@Vansinnet the build with the fix is available in the beta channel - `v0.96-3-g07db`.

If nothing serious happens, we'll publish this fix to the release channel.

**Comment by rfgamaral** [comment]
> 
> 
> I think we can support a list of IP addresses per client, but not in the upcoming release. We should start with just a single IP per client.

Since this issue is now closed, should I open an individual feature request for this?

**Comment by ameshkov** [comment]
> Since this issue is now closed, should I open an individual feature request for this?

Yeah, unless #809 is what you want, then simply upvote it:)

**Comment by rfgamaral** [comment]
Yep, it's the same thing. thanks.

**Comment by rzcat** [comment]
@Vansinnet 
did you solve your problem?
im running v0.101.0, with general settings "block domains use filters and hosts files" unchecked, checking "block domains use filters and hosts files" in client settings makes no effect

**Comment by Vansinnet** [comment]
> @Vansinnet
> did you solve your problem?
> im running v0.101.0, with general settings "block domains use filters and hosts files" unchecked, checking "block domains use filters and hosts files" in client settings makes no effect
Makes no effect? Do you mean the specific client isn't blocking advertisement in your scenario?

**Comment by rzcat** [comment]
> Makes no effect? Do you mean the specific client isn't blocking advertisement in your scenario?
> 
> > @Vansinnet
> > did you solve your problem?
> > im running v0.101.0, with general settings "block domains use filters and hosts files" unchecked, checking "block domains use filters and hosts files" in client settings makes no effect

yes
general settings, unchecked, client settings, checked
use ip addr as identifier, specific client(my desktop) goes without filter
im wondering if anybody else has the same issue, or rather it's my config problem

**Comment by szolin** [comment]
@rzcat Please create a new task and describe your problem more in detail.  This task is closed and we may forget to resolve your problem.
