### ISSUE TITLE
 Why don't certificates work?

### ISSUE THREAD

**Issue by kazantsev97** [AdguardTeam/AdGuardHome#7272]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

107

### Action

I entered full chain and graft, but he writes about incorrectness, what’s the problem?

### Expected result

certificate performance

### Actual result

error

### Additional information and/or screenshots

![Screenshot_141](https://github.com/user-attachments/assets/b0f04593-2e03-4508-a691-2d0e83f7772b)
 
v0.107.52

**Comment by fernvenue** [comment]
You need to paste certificate and private key, not certificate on both.

**Comment by kazantsev97** [comment]
> Вам необходимо вставить сертификат и закрытый ключ, а не сертификат в оба устройства.

Here
![Screenshot_166](https://github.com/user-attachments/assets/f733fff6-f530-42e8-85d7-0095cba9a3bd)
![Screenshot_165](https://github.com/user-attachments/assets/836d1b86-3684-4ded-91e6-8b2b2704e753)

**Comment by fernvenue** [comment]
Make sure you use fullchain certificate.

**Comment by schzhn** [comment]
We assume that the certificate wasn't valid.
