### ISSUE TITLE
AdGuardHome got stuck during AdGuard DNS outage

### ISSUE THREAD

**Issue by knabed** [AdguardTeam/AdGuardHome#7284]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

AdGuard was running normal as a major outage of AdGuard DNS with info  about degraded performance in Frankfurt occurred  today.
Upstream DNS configuration within AdGuard Home consists of Cloudflare, Quad9, Adguard and Google.
Fallback-DNS-Server are 8.8.8.8 and 1.1.1.1

### Expected result

continue running DNS service without any impact

### Actual result

As AdGuard DNS outage occurred in Frankfurt AdGuard Home stopped DNS service and did not provide any DNS response any longer until AdGuard DNS outage was solved

### Additional information and/or screenshots

Raspverry Pi 4 with Debian Linux 12 Linux 6.6.47-v8+ on aarch64, all packages uptodate

**Comment by schzhn** [comment]
Hello, @knabed. You probably have Safe Browsing or Parental Control services enabled and they use AdGuard servers.

**Comment by knabed** [comment]
@schzhn: oh yes, Safe Browsing is/was enabled. Many thanks!

**Comment by knabed** [comment]
Assume it was a configuration issue
