### ISSUE TITLE
The encrypted DNS checkmark does not work

### ISSUE THREAD

**Issue by kazantsev97** [AdguardTeam/AdGuardHome#7287]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Ubuntu server 22.04 (

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

107

### Action

The encrypted dns checkmark does not work, if I disable unencrypted dns, then the Internet immediately stops working, how do I make the encrypted dns work? there is a domain name

### Expected result

what is missing, what ports can be opened in ubuntu so that encrypted dns works?I want to disable the unencrypted DNS, certificate and domain name added
![Screenshot_2024-09-25-05-51-32-062_com android chrome~2](https://github.com/user-attachments/assets/b0c1b02d-638b-492b-a678-47432e56b718)

### Actual result

encrypted DNS does not work

**Comment by schzhn** [comment]
Discussed in https://github.com/AdguardTeam/AdGuardHome/discussions/7286
