### ISSUE TITLE
Adguard Home blocking Indian government websites

### ISSUE THREAD

**Issue by maxakash** [AdguardTeam/AdGuardHome#7289]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

Hi
I am using AdGuard Home on Home Assistant. It works great except it all blocks most of the Indian government websites. Most of the domains ending with 'gov.in' fails to load. I then have to use VPN on my device to use them. But sometime, I am able to open these websites.
The error I get is 
```
DNS_PROBE_FINISHED_NXDOMAIN
```

### Expected result

I should be able to access domains ending with 'gov.in' all the time.

### Actual result

The error I get is 
```
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by Dynamic5912** [comment]
So.. check where it's getting blocked.

Is it by a filtered DNS server or a blocklist?

**Comment by maxakash** [comment]
> So.. check where it's getting blocked.
> 
> Is it by a filtered DNS server or a blocklist?

I think it's by a filtered DNS. I have checked the blocklist. Also out of a sudden certain websites that were not working works.'
I have even tried changing Upstream DNS servers
Here is one such screenshot
<img width="2560" alt="Screenshot 2024-10-02 at 10 04 19 AM" src="https://github.com/user-attachments/assets/7668f0f8-c71a-4b03-956b-66e3e2706582">

**Comment by Dynamic5912** [comment]
So change the DNS server then to something else?

**Comment by maxakash** [comment]
> So change the DNS server then to something else?

I have tried multiple ones but still the same error. Can you recommend one that block ads? 
I can test that.

**Comment by Dynamic5912** [comment]
> > So change the DNS server then to something else?
> 
> 
> 
> I have tried multiple ones but still the same error. Can you recommend one that block ads? 
> 
> I can test that.

Use an unfiltered dns server. 

And disable all blocklists. 

Does it work?

**Comment by maxakash** [comment]
> > > So change the DNS server then to something else?
> > 
> > 
> > I have tried multiple ones but still the same error. Can you recommend one that block ads?
> > I can test that.
> 
> Use an unfiltered dns server.
> 
> And disable all blocklists.
> 
> Does it work?

Yes, it works now. Thanks. But what about the popup sites that open, will they be blocked or not?

**Comment by Dynamic5912** [comment]
Not if you have protection disabled.

You need to ascertain if the site is being blocked by a blocklist (or multiple) or a filtered DNS server.

**Comment by maxakash** [comment]
> Not if you have protection disabled.
> 
> You need to ascertain if the site is being blocked by a blocklist (or multiple) or a filtered DNS server.

Ok, I will look into it.
Thanks for your help.
