### ISSUE TITLE
Hulu (and Disney) skipping too far ahead after blocked ad

### ISSUE THREAD

**Issue by ckmccollim** [AdguardTeam/AdGuardHome#7298]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

I installed AdGuard Home (Version: v0.107.52) on Raspberry Pi following NetworkChuck's YouTube video and enjoyed the learning and process.

https://youtu.be/B2V_8M9cjYw?si=tsifeyfGydfdwNEw

Everything is working very well with the exception of the Hulu app on both Android Fire Tablet and Sony Android TV.
Hulu app is playing the intended program fine and then instead of going to the ad (which is then blocked by AdGuard Home DNS) the player jumps ahead skipping part of the program--further down the timeline than it should be.

Even if you jog back, you still cannot see the missing program video.

If I "disable protect" in AdGuard Home webpage then Hulu works correctly again--with the ad showing.

I posted this question on reddit and the only response that I got was from another person saying they were also having trouble with this working "I get the same issue with Disney plus"

https://www.reddit.com/r/Adguard/comments/1f2z9gu/comment/lkb0tgp/?context=3

Thank you.

### Expected result

I expected Hulu to start playing the movie again where it had left off to play the ad.

### Actual result

Hulu started playing the movie further down the timeline, and there was no way to scrub or rewind the timeline back to where it had left off for the ad.

### Additional information and/or screenshots

I have posted this question to reddit.com/r/Adguard/ and directly to support@adguard.com.
support@adguard.com told me "AdGuard Home is our free for use product that is supported by our developers directly at GitHub. Please move your query here: https://github.com/AdguardTeam/AdGuardHome/issues "

**Comment by tjharman** [comment]
I'm sorry there is nothing AdGuardHome can do to resolve this.  AdGuardHome blocks ads.  If an Ad is blocked, the way the client (Hulu) handles that is completely outside of AdGuardHome's Control.
  
Really this comes down to how Hulu handles a blocked ad - and of course you can't complain to them because they don't want you blocking ad.

But I'm sorry there's no way a DNS adblock can influence how a client reacts to its inability to load an ad.

**Comment by ckmccollim** [comment]
How would I go about allowing the ad sites for Hulu in order for Hulu to work correctly?
Is there an article or FAQ that would describe how I could do this?
Thank you for your help. I was so impressed with Adguard Home and how powerful it is, but then when Hulu didn't work correctly, it was a deal breaker for my wife and I :(

**Comment by tjharman** [comment]
the best way would be, when watching Hulu, look at the list of sites being blocked in the main AdGuardHome interface.  When an ad is about to play/is blocked, look at what host(s) appear in the logs.  You can then whitelist them and try again.
