### ISSUE TITLE
Repeated request

### ISSUE THREAD

**Issue by huxia86465** [AdguardTeam/AdGuardHome#7309]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.52

### Action

![上传IMG_0231.png...]（）In the filter domain name, each request will be repeated twice. The dns resolved is the same.

### Expected result

Not have

### Actual result

Not have

### Additional information and/or screenshots

Adguard hone installed on Windows

**Comment by huxia86465** [comment]
![IMG_0231](https://github.com/user-attachments/assets/e2c465af-8e7e-42b4-8377-3a98c28bea16)

**Comment by Dynamic5912** [comment]
They are probably different types of DNS requests. Hence listed twice

**Comment by huxia86465** [comment]
> They are probably different types of DNS requests. Hence listed twice

Thanks for your answer.
