### ISSUE TITLE
Improve Windows permission checks

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#7314]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.53

### Action

In v0.107.53 we have added a migration that should automatically detect and fix lax permissions on files on Unix-like systems.  Unfortunately, the poor support of the Windows permission model from the standard Go library prevented us from doing the same on Windows.

We must find or develop libraries to make the migration and these mitigations work on Windows, as well just generally allow us to control file permissions properly.

### Expected result

v0.107.53 fixes applied automatically on Windows.

### Actual result

v0.107.53 fixes are not applied automatically on Windows.

**Comment by SanderBouwhuis** [comment]
After this update, Adguard Home no longer works for me.
Access is denied, and the service won't start anymore.
