### ISSUE TITLE
v0.95 goes into an infinite loop when both browsing security and parental control are enabled

### ISSUE THREAD

**Issue by twu2** [AdguardTeam/AdGuardHome#732]
rollback to v0.94
### Steps to reproduce

1. upgrade from v0.94 to v0.95, when start adguardhome service, will get too many open files error in syslog.

<details><summary>Screenshot:</summary>
Apr 24 08:36:38 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:38 [info] AdGuard Home, version v0.95
Apr 24 08:36:38 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:38 [info] Upstream 0: https://dns.cloudflare.com:443/dns-query
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Start DNS server periodic jobs
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Starting the DNS proxy server
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] The server is configured to refuse ANY requests
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] DNS cache is enabled
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Creating the UDP server socket
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Listening to udp://[::]:5353
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Creating the TCP server socket
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Listening to tcp://[::]:5353
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] AdGuard Home is available on the following addresses:
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://127.0.0.1:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://192.168.1.12:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://192.168.0.12:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://[2002:c000:203::1]:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Entering the UDP listener loop on [::]:5353
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Entering the tcp listener loop on [::]:5353
Apr 24 08:36:41 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:41 [info] Added 24 client aliases from /etc/hosts
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get http://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=63195F3E/5ED74CE3/: lookup sb.adtidy.org on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get http://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=63195F3E/5ED74CE3/: lookup sb.adtidy.org on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get http://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=63195F3E/5ED74CE3/: lookup sb.adtidy.org on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95
| How did you setup DNS configuration:| System
| Operating system and version:| Debian Buster

**Comment by twu2** [comment]
syslog:
Apr 24 08:36:38 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:38 [info] AdGuard Home, version v0.95
Apr 24 08:36:38 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:38 [info] Upstream 0: https://dns.cloudflare.com:443/dns-query
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Start DNS server periodic jobs
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Starting the DNS proxy server
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] The server is configured to refuse ANY requests
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] DNS cache is enabled
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Creating the UDP server socket
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Listening to udp://[::]:5353
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Creating the TCP server socket
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Listening to tcp://[::]:5353
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] AdGuard Home is available on the following addresses:
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://127.0.0.1:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://192.168.1.12:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://192.168.0.12:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Go to http://[2002:c000:203::1]:3000
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Entering the UDP listener loop on [::]:5353
Apr 24 08:36:40 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:40 [info] Entering the tcp listener loop on [::]:5353
Apr 24 08:36:41 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:41 [info] Added 24 client aliases from /etc/hosts
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get http://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=63195F3E/5ED74CE3/: lookup sb.adtidy.org on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get http://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=63195F3E/5ED74CE3/: lookup sb.adtidy.org on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do parental HTTP lookup, ignoring check: Get http://pctrl.adguard.com/check-parental-control-hash?prefixes=71047D11/8EE7B2F5/&sensitivity=13: lookup pctrl.adguard.com on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files
Apr 24 08:36:42 fw2 AdGuardHome[3507951]: 2019/04/24 08:36:42 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get http://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=63195F3E/5ED74CE3/: lookup sb.adtidy.org on 192.168.0.1:53: dial udp 127.0.0.1:5353: socket: too many open files

**Comment by ameshkov** [comment]
@twu2 hi, how and where do you run AG Home?

**Comment by ameshkov** [comment]
@twu2 also, could you please try running it with `-v` argument so that we could take a look at the detailed log?

**Comment by ameshkov** [comment]
@twu2 also, could you please attach your `AdGuardHome.yaml` (delete passwords and keys from it)

**Comment by twu2** [comment]
running amd64 version in normal PC (Debian testing).
the log with -v: https://www.teatime.com.tw/~tommy/test/adg_v095_debug.tgz
my AdGuardHome.yaml:

bind_host: 0.0.0.0
bind_port: 3000
auth_name: ""
auth_pass: ""
language: ""
rlimit_nofile: 0
dns:
  bind_host: 0.0.0.0
  port: 5353
  protection_enabled: true
  filtering_enabled: true
  blocked_response_ttl: 10
  querylog_enabled: true
  ratelimit: 0
  ratelimit_whitelist: []
  refuse_any: true
  bootstrap_dns:
  - 101.101.101.101:53
  all_servers: false
  parental_sensitivity: 13
  parental_enabled: true
  safesearch_enabled: true
  safebrowsing_enabled: true
  resolveraddress: ""
  upstream_dns:
  - tls://101.101.101.101
  - tls://8.8.8.8
  - tls://1.1.1.1
  - tls://8.8.4.4
  - tls://1.0.0.1
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 9443
  port_dns_over_tls: 9853
  certificate_chain: ""
  private_key: ""
filters:
- enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1543445578
- enabled: true
  url: https://adaway.org/hosts.txt
  name: Adaway
  id: 1549961562
- enabled: true
  url: https://hosts-file.net/ad_servers.txt
  name: hpHosts AD
  id: 1549961563
- enabled: true
  url: https://hosts-file.net/emd.txt
  name: hpHosts malware
  id: 1549961564
- enabled: true
  url: https://hosts-file.net/hjk.txt
  name: hpHosts Hijack
  id: 1549961565
- enabled: true
  url: https://hosts-file.net/psh.txt
  name: hpHosts phish
  id: 1549961566
- enabled: true
  url: http://www.malwaredomainlist.com/hostslist/hosts.txt
  name: malwaredomainlist
  id: 1549961567
user_rules:
- '@@||cdburnerxp.se^$important'
- '@@||alcpu.com^$important'
- '@@||dreamhost.com^$important'
- '@@||mobisystems.com^$important'
- ""
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 0
  icmp_timeout_msec: 0
log_file: ""
verbose: false
schema_version: 3

**Comment by ameshkov** [comment]
@twu2 thank you! The hotfix will be ready soon.

**Comment by ameshkov** [comment]
@twu2 https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.95-hotfix
