### ISSUE TITLE
Sync two adguard servers and their zones

### ISSUE THREAD

**Issue by Stephan-4711** [AdguardTeam/AdGuardHome#7321]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

For redundancy reasons there are more than 1 adguard servers needed.
Integrated into some appliances like addons for heterogenous hardware like opnsense, home assistant etc. There is a sync between multiple hardware needed. 

### Proposed solution

Add a feature to sync the adguard settings and the dns zones into the adguard home code.

**Comment by schzhn** [comment]
Duplicate of #573
