### ISSUE TITLE
General Statistic comma format the numbers

### ISSUE THREAD

**Issue by melucas** [AdguardTeam/AdGuardHome#7329]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

On the Dashboard page (index) in the General Statistics section, could you please format the numbers with a comma (thousand separator) for the items in the list. 

See the yellow highlighted numbers in the screen capture attached.

![Screen](https://github.com/user-attachments/assets/e040e24a-254d-4209-8bed-e33fbd0048a0)

### Proposed solution

Format the number using the same formatting as the Top Clients and Top Domains counts.

The values are formatted in the HTML which looks like it will require some backend changes to the main.js.

**Comment by ainar-g** [comment]
@handcoding, it's a reasonable improvement, yeah, but please open a new issue about it.

**Comment by handcoding** [comment]
> [@handcoding](https://github.com/handcoding), it's a reasonable improvement, yeah, but please open a new issue about it.

@ainar-g Sounds good! I’ve filed that as issue #7590.

**Comment by melucas** [comment]
Thank you for including the General Statistics fix in the latest release build.  Working as expected on my 2 instances.
