### ISSUE TITLE
Randomly sends everything to sinkhole

### ISSUE THREAD

**Issue by BP-777** [AdguardTeam/AdGuardHome#7330]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.53

### Action

Everything worked fine for a long time, but then everything started getting sent to 0.0.0.0 no matter what it was.
I did an NSlookup to google.com to test and saw it resolve to 0.0.0.0

### Expected result

Unblocked websites to resolve properly.

### Actual result

everything from Google to personal DNS records resolved to 0.0.0.0

**Comment by Dynamic5912** [comment]
What does the query log show?

**Comment by BP-777** [comment]
> What does the query log show?

Looks like everything was getting flagged by the Anti-Malware filter.

it brought down the whole network till I turned off filtering. I changed the DNS to a public DOH server in my router for now.


Response details
Status
Blocked
Elapsed
0.05 ms
Response code
NOERROR
Rule(s)
://
Anti Malware
Response
A: 0.0.0.0 (ttl=10)

**Comment by Dynamic5912** [comment]
It's not a good idea to use the malware/security filtering anyway as it adds significant latency to requests. 

You'd be better off using an active and maintained malware blocklist instead

**Comment by BP-777** [comment]
> It's not a good idea to use the malware/security filtering anyway as it adds significant latency to requests.
> 
> You'd be better off using an active and maintained malware blocklist instead

I thought that's what it was referring to, the Anti Malware list here that has 25k entries.

![image](https://github.com/user-attachments/assets/03ab445f-a8c1-4bc2-85cd-1080555a4dc1)

**Comment by Dynamic5912** [comment]
Ah ok. So it was a list.

There must have been an errant entry in that list that was black-holing everything then.
