### ISSUE TITLE
stats: warning: deleting bucket err="bucket not found"

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#7338]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, MIPS LE

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.108.0-b.58

### Action

AGH log is spammed every hour with:
```
2024/10/09 22:00:00.005244 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/09 23:00:00.598413 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 00:00:00.159797 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 01:00:00.729389 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 02:00:00.358223 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 03:00:00.956796 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 04:00:00.546444 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 05:00:00.175385 [info] stats: warning: deleting bucket err="bucket not found"
2024/10/10 06:00:00.781174 [info] stats: warning: deleting bucket err="bucket not found"
```

### Expected result

no warnings

### Actual result

warnings

### Additional information and/or screenshots

These bugs seem to be back:
https://github.com/AdguardTeam/AdGuardHome/issues/4900
https://github.com/AdguardTeam/AdGuardHome/issues/4850

**Comment by AndyLin2020** [comment]
yes, so you're getting this log message once per hour, and reverting back to version v0.107.52 fixes the issue
