### ISSUE TITLE
Add a link to the list of known DNS providers to Upstream DNS settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#734]
List:
https://kb.adguard.com/general/dns-providers

https://uploads.adguard.com/up04_owcp6_AdGuard_Home.png

Text:
`Here is a [list of known DNS providers](https://kb.adguard.com/general/dns-providers) to choose from.`

**Comment by ibksturm** [comment]
today i did some changes on dns-providers [https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/321/commits/b6d1c8cb7536f730b290d003e636e2dbf598a56b](https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/321/commits/b6d1c8cb7536f730b290d003e636e2dbf598a56b), hope @admitrevskiy oke and accept it

**Comment by ameshkov** [comment]
Thank you! Plz ping me if there's no answer from him in a couple of days

**Comment by ibksturm** [comment]
@ameshkov 
dobri i will do so :)

**Comment by balupton** [comment]
Why isn't AdGuard DNS the default for AdGuard Home?

**Comment by ameshkov** [comment]
@balupton the answer is here: https://github.com/AdguardTeam/AdGuardHome/issues/1116
