### ISSUE TITLE
How to Use GoodByeDPI with AdguardHome?

### ISSUE THREAD

**Issue by buadamlaz** [AdguardTeam/AdGuardHome#7340]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Hello,
I have a small computer with AdGuardHome installed. The modem distributes DNS via this computer as a DNS server. In this way, I apply ads and filters.

Unfortunately, there are a lot of internet restrictions in my country, many large sites are blocked. I use [GoodByeDPI ](https://github.com/ValdikSS/GoodbyeDPI)to access prohibited sites without needing a VPN on my Windows computer.

Is there a way to bypass these prohibited sites by installing [Zapret](https://github.com/bol-van/zapret), which is the Linux version of this, on the AdGuardHome server?

Can we set up the zapper so that all devices on the network can use it?

### Proposed solution

I want to exchange ideas.

**Comment by scratcher28** [comment]
+1

**Comment by tjharman** [comment]
Surely this is a question better asked of the Zapret/GoodByeDPI teams?  AdGuardHome is a DNS server with some filtering capabilities.

Why don't you setup a squid (or similar) proxy on your Linux box running GoodByeDPI/Zapret and configure your clients to use the Proxy?  

I'm going to close this as I really don't think this is the relevant forum, the only connection appears to be you have a Linux Server already running AdGuardHome.
