### ISSUE TITLE
rpi block facebook

### ISSUE THREAD

**Issue by iokapsalas** [AdguardTeam/AdGuardHome#7352]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

how can block facebook

### Proposed solution

block facebook

### Alternatives considered and additional information

block facebook

**Comment by overwatch3560** [comment]
You can already block Facebook going into the filters tab and then blocked services @iokapsalas so what's the problem?

**Comment by schzhn** [comment]
Answered in https://github.com/AdguardTeam/AdGuardHome/discussions/7353
