### ISSUE TITLE
Very slow response from upstream servers with a lot of `context deadline exceeded`

### ISSUE THREAD

**Issue by SukkaW** [AdguardTeam/AdGuardHome#7357]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

Raspberry Pi 4

```sh
sukka@sukka-pi:/tmp $ uname -a
Linux sukka-pi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
```

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.53

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.example.com' '127.0.0.1'
dig www.example.com @127.0.0.1
```

### Expected result

The result returned immdiately.

### Actual result

The result returned in about 20 seconds.

### Additional information and/or screenshots

I have set following upstream servers in the `DNS settings`:

```
https://120.53.53.53/dns-query
https://1.12.12.12/dns-query
tls://120.53.53.53
tls://1.12.12.12
```

But when I use the `Test upstreams` button, AdGuardHome says all those servers could not be used:

<img width="355" alt="image" src="https://github.com/user-attachments/assets/768cf721-438f-4f6d-8ea3-4bba36ce5c51">

I have tested those servers locally, they return the result very fast, so definitely no internet connectivity issue, and also there is no problem with the upstream servers:

```
sukka@sukka-pi:/tmp $ time dig www.example.com @120.53.53.53 +https +short
93.184.215.14

real    0m0.342s
user    0m0.060s
sys     0m0.014s
sukka@sukka-pi:/tmp $ time dig www.example.com @120.53.53.53 +tls +short
93.184.215.14

real    0m0.250s
user    0m0.054s
sys     0m0.025s
sukka@sukka-pi:/tmp $ time dig www.example.com @1.12.12.12 +https +short
93.184.215.14

real    0m0.128s
user    0m0.056s
sys     0m0.024s
sukka@sukka-pi:/tmp $ time dig www.example.com @1.12.12.12 +tls +short
93.184.215.14

real    0m0.185s
user    0m0.059s
sys     0m0.020s
```

I have also tried with `curl`:

```
sukka@sukka-pi:/tmp $ time curl https://120.53.53.53/dns-query

real    0m0.212s
user    0m0.147s
sys     0m0.025s

sukka@sukka-pi:/tmp $ time curl https://1.12.12.12/dns-query

real    0m0.214s
user    0m0.149s
sys     0m0.016s
```

I then enabled `log.verbose` in the config file (`AdGuardHome.yaml`), and I got those logs:

```
2024/10/18 22:29:36.482822 1090#350 [error] dnsproxy: exchange failed upstream=tls://1.12.12.12:853 question=";www.example.com.\tIN\t A" duration=10.011039607s err="getting conn to tls://1.12.12.12:853: connecting to 1.12.12.12: read tcp 10.10.1.200:60174->1.12.12.12:853: i/o timeout"
2024/10/18 22:29:38.492967 1090#485 [debug] started GET 10.10.1.200:11451 /control/status
2024/10/18 22:29:38.494299 1090#485 [debug] finished GET 10.10.1.200:11451 /control/status in 1.363265ms
2024/10/18 22:29:46.495655 1090#350 [error] dnsproxy: exchange failed upstream=tls://120.53.53.53:853 question=";www.example.com.\tIN\t A" duration=10.012209931s err="getting conn to tls://120.53.53.53:853: connecting to 120.53.53.53: read tcp 10.10.1.200:40744->120.53.53.53:853: i/o timeout"
2024/10/18 22:29:46.496177 1090#350 [debug] dnsproxy: resolving err src=upstream err="all upstreams failed to exchange request: requesting https://120.53.53.53:443/dns-query: Get \"https://120.53.53.53:443/dns-query?dns=AAABAAABAAAAAAABA3d3dwdleGFtcGxlA2NvbQAAAQABAAApCAAAAIAAAAA\": context deadline exceeded\nrequesting https://1.12.12.12:443/dns-query: Get \"https://1.12.12.12:443/dns-query?dns=AAABAAABAAAAAAABA3d3dwdleGFtcGxlA2NvbQAAAQABAAApCAAAAIAAAAA\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\ngetting conn to tls://1.12.12.12:853: connecting to 1.12.12.12: read tcp 10.10.1.200:60174->1.12.12.12:853: i/o timeout\ngetting conn to tls://120.53.53.53:853: connecting to 120.53.53.53: read tcp 10.10.1.200:40744->120.53.53.53:853: i/o timeout"
2024/10/18 22:29:46.496360 1090#350 [debug] dnsforward: finished processing upstream
2024/10/18 22:29:46.496644 1090#350 [debug] dnsproxy: out line_num=1 line=";; opcode: QUERY, status: SERVFAIL, id: 32875"
2024/10/18 22:29:46.496905 1090#350 [debug] dnsproxy: out line_num=2 line=";; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0"
2024/10/18 22:29:46.497117 1090#350 [debug] dnsproxy: out line_num=3 line=""
2024/10/18 22:29:46.497331 1090#350 [debug] dnsproxy: out line_num=4 line=";; QUESTION SECTION:"
2024/10/18 22:29:46.497545 1090#350 [debug] dnsproxy: out line_num=5 line=";www.example.com.\tIN\t A"
2024/10/18 22:29:46.497752 1090#350 [debug] dnsproxy: out line_num=6 line=""
2024/10/18 22:29:46.498229 1090#350 [debug] dnsproxy: handling dns request proto=udp err="using request handler: all upstreams failed to exchange request: requesting https://120.53.53.53:443/dns-query: Get \"https://120.53.53.53:443/dns-query?dns=AAABAAABAAAAAAABA3d3dwdleGFtcGxlA2NvbQAAAQABAAApCAAAAIAAAAA\": context deadline exceeded\nrequesting https://1.12.12.12:443/dns-query: Get \"https://1.12.12.12:443/dns-query?dns=AAABAAABAAAAAAABA3d3dwdleGFtcGxlA2NvbQAAAQABAAApCAAAAIAAAAA\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\ngetting conn to tls://1.12.12.12:853: connecting to 1.12.12.12: read tcp 10.10.1.200:60174->1.12.12.12:853: i/o timeout\ngetting conn to tls://120.53.53.53:853: connecting to 120.53.53.53: read tcp 10.10.1.200:40744->120.53.53.53:853: i/o timeout"
2024/10/18 22:32:17.276231 1090#486 [debug] started GET 10.10.1.200:11451 /control/status
2024/10/18 22:32:17.277575 1090#486 [debug] finished GET 10.10.1.200:11451 /control/status in 1.398173ms
2024/10/18 22:32:19.917784 1090#486 [debug] started POST 10.10.1.200:11451 /control/test_upstream_dns
2024/10/18 22:32:29.919010 ERROR response received addr=https://1.12.12.12:443/dns-query proto=tcp status="requesting https://1.12.12.12:443/dns-query: Get \"https://1.12.12.12:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2024/10/18 22:32:29.919133 ERROR response received addr=https://120.53.53.53:443/dns-query proto=tcp status="requesting https://120.53.53.53:443/dns-query: Get \"https://120.53.53.53:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ\": context deadline exceeded"
2024/10/18 22:32:29.933972 1090#486 [debug] finished POST 10.10.1.200:11451 /control/test_upstream_dns in 10.016169079s
2024/10/18 22:32:48.354208 1090#486 [debug] started GET 10.10.1.200:11451 /control/status
2024/10/18 22:32:48.355457 1090#486 [debug] finished GET 10.10.1.200:11451 /control/status in 1.294076ms
2024/10/18 22:34:47.290447 1090#554 [debug] started GET 10.10.1.200:11451 /control/status
2024/10/18 22:34:47.291737 1090#554 [debug] finished GET 10.10.1.200:11451 /control/status in 1.338358ms
2024/10/18 22:34:48.408058 1090#554 [debug] started POST 10.10.1.200:11451 /control/test_upstream_dns
2024/10/18 22:34:58.409273 ERROR response received addr=https://120.53.53.53:443/dns-query proto=tcp status="requesting https://120.53.53.53:443/dns-query: Get \"https://120.53.53.53:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ\": context deadline exceeded"
2024/10/18 22:34:58.409278 ERROR response received addr=https://1.12.12.12:443/dns-query proto=tcp status="requesting https://1.12.12.12:443/dns-query: Get \"https://1.12.12.12:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2024/10/18 22:34:58.445246 1090#554 [debug] finished POST 10.10.1.200:11451 /control/test_upstream_dns in 10.037199239s
```

Also average upstream servers response time:

<img width="607" alt="image" src="https://github.com/user-attachments/assets/b05d41d5-5318-4aa1-af39-bc475bcbdacb">

So somehow AdGuardHome failed to connect to upstream servers while `dig` works just fine.

**Comment by xWTF** [comment]
Same issue, `v0.107.53` takes ~20s to resolve through DoH and throws several generic timeout messages. The problem is gone after reverting back to `v0.107.52`.
Possibly related: https://github.com/AdguardTeam/AdGuardHome/issues/7346 (similar issue from v0.108.0-b.58, which is released between these two versions).

Environment: `Linux 4.1.52 aarch64 ASUSWRT-Merlin 3004.388.7`

I'm stunned by the [huge amount of changes between these two versions](https://github.com/AdguardTeam/AdGuardHome/compare/v0.107.52...v0.107.53), not sure how to investigate what's going on from these `29,523 additions and 27,647 deletions`.

**Comment by SukkaW** [comment]
@xWTF Even w/ verbose logging I can't see any useful information. So I assume the most likely cause would be the bumping of go from `1.22` to `1.23`.

**Comment by xWTF** [comment]
> @xWTF Even w/ verbose logging I can't see any useful information. So I assume the most likely cause would be the bumping of go from `1.22` to `1.23`.

Yep, on my device the log simply says "timeout" without any additional information, appears to be a regular connection problem but curl and old version works fine.
Nothing suspicious from the changelog / milestone, so the version bump could be the cause. Currently I don't have evidence tho, the changes are just too much for me to review.

**Comment by SukkaW** [comment]
@xWTF It is also possible that our chosen DoH server doesn't support HTTP/3, and meanwhile, the AdGuardHome might always try with HTTP/3 first without a proper fallback. Per https://github.com/AdguardTeam/AdGuardHome/issues/7346 described.

**Comment by schzhn** [comment]
The [edge release](https://github.com/AdguardTeam/AdGuardHome/blob/master/README.md#test-unstable-versions) contains several bug fixes.
Could you please check it?

You can also download the binary for your platform from the following link
https://static.adtidy.org/adguardhome/edge/version.json

**Comment by xWTF** [comment]
Well I've confirmed this is indeed an MTU issue, check your local MTU configurations. Never thought about this possibility before.

In AGH 0.73.2, the TLS client hello is classic 252 bytes, which is short enough to be sent without any issue.

![image](https://github.com/user-attachments/assets/06472f37-3f05-436f-b6a6-9ec2b5743486)

However, in 0.73.3+, a `key_share` extension is sent, boosting the record size to1476 bytes. Which can cause problems when the MTU size is misconfigured.

![image](https://github.com/user-attachments/assets/1c0c5af8-127f-48dd-a57e-8fea2b5e55c3)

![image](https://github.com/user-attachments/assets/84c923fd-8ac0-4604-aab3-236c7d53017c)

And the change is related to Golang version bump, as we guessed previously. See [here](https://tip.golang.org/doc/go1.23#:~:text=The%20experimental%20post%2Dquantum%20key%20exchange%20mechanism%20X25519Kyber768Draft00%20is%20now%20enabled%20by%20default%20when%20Config.CurvePreferences%20is%20nil.%20The%20default%20can%20be%20reverted%20by%20adding%20tlskyber%3D0%20to%20the%20GODEBUG%20environment%20variable.) for the relevant changelog.

I can confirm this by setting `GODEBUG=tlskyber=0`, which disables the key_share extension and the handshake can be done normally.

**Comment by xWTF** [comment]
> > You may also set the `GODEBUG=tlskyber=0` environment, or switch to other DoH/DoT providers without this issue.
> 
> OK, it seems that my problem is not related to this issue. Turning off tlskyber is indeed effective. Thanks for your help

Sorry for the confusion caused by the previous reply. It is indeed the same problem. The MSS configuration error occurs on Tencent's side, not on our local side. You may want to check the edited version of my second comment for more details.

**Comment by SukkaW** [comment]
Similar issue: https://github.com/hashicorp/terraform-provider-aws/issues/39311

cc @xWTF

**Comment by SukkaW** [comment]
Created a few social posts to raise the concern:

- Twitter: https://fxtwitter.com/isukkaw/status/1862888987595280883
- Bluesky: https://bsky.app/profile/skk.moe/post/3lc6hhgg6zc2y
- Mastodon (zh_CHS): https://acg.mn/@sukka/113572701104608722
- Telegram (zh_CHS): https://t.me/s/SukkaChannel/977

**Comment by schzhn** [comment]
It appears that Tencent has updated the TLS configuration of their DNS servers, as I can no longer reproduce the issue on my setup. Thank you all for reporting, testing, and investigating this matter.

**Comment by galpt** [comment]
> [!NOTE]  
> I din't mean to bump this closed issue.
> just leaving a feedback here in case someone wants to confirm it and open a new issue later.


I'm using `v0.107.56-r1` on an intel n100 (x86, amd64 arch), and I noticed I got like 3000 - 14000ms response time when I tried to use `h3://`, but everything works "okay" when I use https (h2). I don't use DoT or non-encrypted upstreams since I'm using AGH so that my ISP won't mess with my DNS responses.

but I believe it's something to do with how QUIC works in Go, since h2 works fine but when using h3 suddenly got spikes in the avg processing time.

there's also a possibility that the used upstreams didn't implement h3 properly, but I'm using cloudflare's DoH, I think it's very unlikely they didn't implement quic/h3 right, so I'd just assume that it's probably the Go deps used by AGH that caused this to happen.

if you want to reproduce it, simply use any DoH upstreams and force it to use `h3://`, it won't take long until you can see things go wrong.

**Comment by fbernier** [comment]
I just installed adguardhome on my OrangePI 5 Max and experienced this issue. I was previously running adguardhome on my Unifi dream machine. h3 was working perfectly there but the orangepi experiences the issues described here. Switching to DoT resolved it.
