### ISSUE TITLE
Логотип для Organizr

### ISSUE THREAD

**Issue by GutsyHeart** [AdguardTeam/AdGuardHome#736]
Не могли бы вы предоставить логотип хорошего качества для встраивания в Organizr?

https://github.com/causefx/Organizr/issues/1137

**Comment by ameshkov** [comment]
Можем конечно, а какой размер нужен?

**Comment by GutsyHeart** [comment]
Большинство логотипов в 512x512px
https://github.com/causefx/Organizr/tree/v2-master/plugins/images/tabs

**Comment by ameshkov** [comment]
@AlikhanAliev подсоби пожалуйста с SVG

**Comment by AlikhanAliev** [comment]
https://github.com/causefx/Organizr/pull/1152
@GutsyHeart @ameshkov
