### ISSUE TITLE
The web panel does not work after the upgrade

### ISSUE THREAD

**Issue by Maksim990** [AdguardTeam/AdGuardHome#7367]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [x] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.53

### Action

I updated AdGuardHome then restarted the system and when I needed to see the logs, it loaded for 5 minutes and then the web panel suddenly stopped working but AdGuardHome itself works. There is no access to its management through the website

### Expected result

View logs, and manage AdGuardHome through the site

### Actual result

When trying to access the site it says: ERR_TIMED_OUT. Reinstalled AdGuardHome with user data intact, this problem happened again
![chrome_VVZebFVNHL](https://github.com/user-attachments/assets/4e89f18b-0aae-4f73-a892-9a8c71bd3abb)

### Additional information and/or screenshots

![image](https://github.com/user-attachments/assets/e4780854-0222-4e62-adcb-1add0a9aac6d)

**Comment by tjharman** [comment]
Are you able to show more detail/logs etc?
What steps did you take to do the upgrade?
What happens if you try with a new/new config file (backup your existing first)
