### ISSUE TITLE
Error: Control/Version

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#737]
Red Error screen pop-up Error:controll/version.json 

### Steps to reproduce

1.did nothing 
2.
3.
4.

### Expected behavior

obviously internal error or my set up
### Actual behavior

<details><summary>Screenshot:</summary>

<img width="347" alt="Screen Shot 2019-04-24 at 8 02 47 AM" src="https://user-images.githubusercontent.com/48414915/56658175-f3d50780-6667-11e9-9367-541ab8bfd791.png">

</details>

### Your environment
MACbook pro ethernet vpn new location

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0) .95
| How did you setup DNS configuration:| (System/Router/IoT) router
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B) ASUS RT N66U 
| Operating system and version:| (e.g. Ubuntu 18.04.1) MAC 10.14.4

**Comment by ameshkov** [comment]
First of all, could you please update to v0.95-hotfix and check if it's still there?

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.95-hotfix
