### ISSUE TITLE
Allow to change the default permissions on query logfile

### ISSUE THREAD

**Issue by nycom83** [AdguardTeam/AdGuardHome#7389]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I have an external program that read query logfile to build a dashboard.
But since the last version (v0.107.53), default permissions on query logfile have been changed from 0644 to 0600.

### Proposed solution

Give the ability to change the default permissions on query log file

**Comment by EugeneOne1** [comment]
@nycom83, hello.  The permissions for each file are checked on every run, but the actual change is only made when the configuration file (`AdGuardHome.yaml`) has invalid permissions.  So you can freely manipulate the access to the querylog file, but AdGuard Home will print a warning message about it, as setting such permissions is not considered safe.

**Comment by handymenny** [comment]
@EugeneOne1 The issue is that the permissions revert to the default ones when the logs rotate: 
![image](https://github.com/user-attachments/assets/e13bea34-f1d7-42cd-a521-ed6740c8235f)

**Comment by LittleJake** [comment]
@EugeneOne1 Also encounter this problem when the log get rotated. I have changed the permission to 0644 of the log files and it will get reverted to 0600 any way.

AdGuard Home, version v0.108.0-b.58

![image](https://github.com/user-attachments/assets/8bf311ae-3160-465b-a6ee-dec274e9692c)
