### ISSUE TITLE
GitHub repo website URL is incorrect

### ISSUE THREAD

**Issue by gene1wood** [AdguardTeam/AdGuardHome#7396]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer
- [X] I have searched other issues and found no duplicates
- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)
- [ ] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Other (please mention in the description)

### Setup

Other (please mention in the description)

### AdGuard Home version

None

### Action

The `Website URL` configured in the `About` section for this repo is incorrect.

The URL is currently configured as

https://adguard.com/adguard-home.html

Which 404s

![image](https://github.com/user-attachments/assets/b072bbdb-fa2c-498e-b668-ace7711f58ac)

### Expected result

It should be changed to

https://adguard.com/adguard-home/overview.html

### Actual result

A 404 page is shown

**Comment by tjharman** [comment]
I will make the Adguard Team aware of this. Thanks.
