### ISSUE TITLE
./AdGuardHome -s install was not working

### ISSUE THREAD

**Issue by CWo42** [AdguardTeam/AdGuardHome#740]
was installing x64 on a vhost with Debian 18.04
./AdGuardHome -s install showed normal output
also ./AdGuardHome -s stop gave a normal response that the service was stopped

BUT there was no adguard service installed 
./AdGuardHome -s uninstall also said - deinstallation successful

i used the old way to get it working and it runs smooth

maybe someone else got a similar issue?

P.S. was using user root - so no sudo ;)

**Comment by szolin** [comment]
> BUT there was no adguard service installed

How did you check it?  After consequent `install` and `stop` commands the service should be installed, but not running.  If `uninstall` command showed `Action uninstall has been done successfully on linux-systemd` then the service is successfully removed from your system - this means that `install` command had correctly installed it previously.
Can you describe the problem more specifically?

**Comment by CWo42** [comment]
after install and start the service should be running but there was no running adguard
but ./Adguard -s was thinking there is a installed running service
so stop and uninstalled showed normal output

**Comment by szolin** [comment]
Can you run these commands once again and copy-paste the output here?
```
./AdGuardHome -s uninstall
./AdGuardHome -s install
ps aux | grep AdGuardHome
```

**Comment by CWo42** [comment]
i will try it later on a new machine, since the origin machine runs AGH with manual installed service now

**Comment by CWo42** [comment]
was my issue - installing Service named Service AdGuard - manuell its adguard 
the difference in service names was the problem
