### ISSUE TITLE
Implement NULL blocking in addition to NXDOMAIN

### ISSUE THREAD

**Issue by alexzeitgeist** [AdguardTeam/AdGuardHome#742]
Filtered queries are currently answered with an empty response and status NXDOMAIN. It would be nice if there was an option to answer filtered queries with the unspecified address 0.0.0.0 instead.

For reference, see the [pi-hole documentation](https://docs.pi-hole.net/ftldns/blockingmode/).

**Comment by ameshkov** [comment]
Marked as a feature request, thank you!

Please note, that it uses NXDOMAIN for adblock syntax filter lists only. If you use a hosts file, AGH will respond with the IP address specified there.

**Comment by ameshkov** [comment]
@szolin considering that it's done in https://github.com/AdguardTeam/AdGuardHome/pull/743, I assigned it to v0.96.

The only thing left to be done is updating Wiki: https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file
