### ISSUE TITLE
Здравствуйте, Adguard Home блокирует rutracker.org как это исправить? Если Adguard отключить, то rutracker.org отлично открывается....

### ISSUE THREAD

**Issue by Rinat7483** [AdguardTeam/AdGuardHome#7423]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.52

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```

### Expected result

Хочу чтобы rutracker.org работал через adguard

### Actual result

Хочу чтобы rutracker.org работал через adguard

**Comment by Marcus1Pierce** [comment]
@Rinat7483 Please use English to make it easier for others to understand. 

To access rutracker.org, simply add rutracker.org to the whitelist to allow access. You can manually add it through the menu by going to Filters > Custom filtering rules and adding rules like @@||rutracker.org^$important and than apply.

**Comment by golimer** [comment]
Russian war ship learn english .... :D

**Comment by Chinaski1** [comment]
As advised to you above, you can simply add the site to allowlist
