### ISSUE TITLE
Quick toggle to enable/disable ad blocking of specific client

### ISSUE THREAD

**Issue by distante** [AdguardTeam/AdGuardHome#7434]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Sometimes due work or specific network issues, I have to let a client bypass Adguard. 

This can be for:

1. Not-yet completed configurations like when I let my kid play Minecraft on my windows PC and with AdGuard enabled the Minecraft Bedrock account can not be correctly linked to my kids microsoft account.

or

2. While working on the development of an app that contains ads and I need to see that the functions linked to ads (rewards, unlocks, etc) are still working.

### Proposed solution

I propose to include a toggle in the client list that lets the client get non-blocked DNS responses.

### Alternatives considered and additional information

Right now (AFAIK) the only way existent is to disable AdguardHome for the hole network. Which is not the best option.

**Comment by tjharman** [comment]
You can already do this.

First untick the yellow box, then untick the red box.

![image](https://github.com/user-attachments/assets/4e5eb82d-9801-49d8-b066-b74c9b1ef703)

**Comment by distante** [comment]
> You can already do this.
> 
> First untick the yellow box, then untick the red box.
> 
> ![image](https://private-user-images.githubusercontent.com/1025029/385921774-4e5eb82d-9801-49d8-b066-b74c9b1ef703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MjgyNTQsIm5iZiI6MTczMTUyNzk1NCwicGF0aCI6Ii8xMDI1MDI5LzM4NTkyMTc3NC00ZTVlYjgyZC05ODAxLTQ5ZDgtYjA2Ni1iNzRjOWIxZWY3MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTk1OTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE2YTUxZGI2MGYxZmFmNDU5OTE0YzBjYTFmZjkyYWU1OGY2MWY4MGQ4OTczNjFiYzc3YmViOGVmODAwMjMxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6NRdYietxMY2UIsqtrrBLU53zesTzKW3uez5u-w_V_s)

The problem with this, is that there is no signal on the client list that this client has his settings disabled unless you go until the details. In a big list is even harder to do.

**Comment by distante** [comment]
The title says "quick toggle", and in the description it says "I propose to include a toggle in the client list that lets the client get non-blocked DNS responses." 

I know we can change the configurations from each client, but we do not have a quick toggle.

Do I really need to open another ticket?
