### ISSUE TITLE
Realize domain name resolution forwarding

### ISSUE THREAD

**Issue by Matinal111** [AdguardTeam/AdGuardHome#7436]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I am using AdGuardHome by installing it on a cloud server, certain cloud server merchant services by default rely on VPC's default DNS resolution, such as access to NTP, S3, and Monitoring and Reporting, which all rely on the default cloud VPC DNS, and if the customer's customized DNS is unable to resolve these domains, it makes these essential services unavailable. I know that DNS rewriting makes it easy to configure custom DNS responses for specific domains, but if some services have both internal IPs and public IPs resolving to the same internal domains, they can't be resolved automatically using DNS rewriting.

### Proposed solution

I wish AdGuardHome could implement custom domains or generic domains to be forwarded to a specific DNS for resolution instead of being resolved by AdGuardHome.

**Comment by tjharman** [comment]
This feature [already exists](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#specifying-upstreams-for-reverse-dns).

**Comment by Matinal111** [comment]
I'm sorry. It was an oversight.
