### ISSUE TITLE
"Couldn't get version check json from" error after clean install

### ISSUE THREAD

**Issue by keshenmathura** [AdguardTeam/AdGuardHome#744]
### Steps to reproduce
After a clean install on Raspberry Pi (Stretch), AdGuard Home pops up with this error:
Error: control/version.json | Couldn't get version check json from https://adguardteam.github.io/AdGuardHome/version.json: *url.Error Get https://adguardteam.github.io/AdGuardHome/version.json: lookup adguardteam.github.io on [fe80::56be:53ff:fe7b:76ad%eth0]:53: read udp 127.0.0.1:42315->127.0.0.1:53: i/o timeout | 502

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server: 0.95 hotfix
| How did you setup DNS configuration: System
| If it's a router or IoT, please write device model: Raspberry Pi 3 Model B
| Operating system and version: Stretch 4.14

**Comment by ameshkov** [comment]
Please try replacing Cloudflare DNS with a different DNS provider. Most likely, AGH cannot connect to it.

**Comment by inhedgerow** [comment]
same problem.  raspbian buster lite.  only variation from stock is user pi removed and custom sudo user used.

**Comment by ameshkov** [comment]
@inhedgerow please try installing the latest beta version:
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions
