### ISSUE TITLE
Calls Adguard servers constantly

### ISSUE THREAD

**Issue by keshenmathura** [AdguardTeam/AdGuardHome#745]
### Steps to reproduce
After clean install AdGuard keeps calling AdGuard servers. This screenshot is 30 minutes after installation.
<img width="1195" alt="Image-1" src="https://user-images.githubusercontent.com/50288637/57190907-362bfd80-6f20-11e9-845d-5145cc54deb5.png">

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.95 Hotfix
| How did you setup DNS configuration:| System
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B
| Operating system and version:| Stretch 4.14

**Comment by rfgamaral** [comment]
Wow, 30 minutes? This is what I have with an uptime of 21 hours:

![image](https://user-images.githubusercontent.com/96476/57199581-a5cdd700-6f78-11e9-9153-8e89929f3097.png)

And even that I think this is too much...

**Comment by szolin** [comment]
Do you mean that the counter of requests to `sb.adtidy.org` is still being increased, even when safe browsing is disabled?  Do those requests also appear in Query Log?

**Comment by rfgamaral** [comment]
> 
> 
> Do you mean that the counter of requests to `sb.adtidy.org` is still being increased, even when safe browsing is disabled? Do those requests also appear in Query Log?

Yes.

![image](https://user-images.githubusercontent.com/96476/57383065-0db53500-71a6-11e9-89d5-c82fd9079ae7.png)

**Comment by szolin** [comment]
Just to be sure, what is the value of `safebrowsing_enabled` setting in your configuration file?

**Comment by rfgamaral** [comment]
> 
> 
> Just to be sure, what is the value of `safebrowsing_enabled` setting in your configuration file?

I'm so sorry but I just realized that while you're always saying "safe browsing" I was reading "safe search". That's my bad and I apologize for the confusion.

I do have safe browsing enabled so it makes sense that AdGuard is making those requests.

**Comment by ameshkov** [comment]
I'd still say this is a problem that the log is full of these internal DNS requests.

@szolin let's modify `dnsfilter.customDialContext` and cache `addrs`.
