### ISSUE TITLE
doh.pub DoH failed to complete upstream test

### ISSUE THREAD

**Issue by Skyxim** [AdguardTeam/AdGuardHome#7459]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by AdGuard Home

### AdGuard Home version

v0.108.0-b.60

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
root@OPNsense:~ # dig test. @doh.pub +https A

; <<>> DiG 9.20.2 <<>> test. @doh.pub +https A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47246
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 825c390e640b11a9 (echoed)
; PAD: (360 bytes)
;; QUESTION SECTION:
;test.				IN	A

;; AUTHORITY SECTION:
test.			301	IN	SOA	localhost. nobody.invalid. 1 3600 1200 604800 10800

;; Query time: 62 msec
;; SERVER: 120.53.53.53#443(doh.pub) (HTTPS)
;; WHEN: Mon Nov 25 16:59:44 CST 2024
;; MSG SIZE  rcvd: 468

root@OPNsense:~ # ./q @https://doh.pub/dns-query test. -S A
Stats:
Received 472 B from https://doh.pub:443/dns-query in 178.7ms (16:59:50 11-25-2024 CST)
Opcode: QUERY Status: NOERROR ID 51392: Flags: qr rd ra (1 Q 0 A 1 N 1 E)
```

### Expected result

Successfully tested upstream server https://doh.pub/dns-query

### Actual result

Show test failed
![image](https://github.com/user-attachments/assets/16cdee69-0a44-4a18-83a2-b5e8704cb130)

```log
2024/11/25 17:02:44.445413 ERROR response received addr=https://doh.pub:443/dns-query proto=tcp status="requesting https://doh.pub:443/dns-query: Get \"https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAABHRlc3QAAAEAAQ\": context deadline exceeded"
```

**Comment by wlshdjj** [comment]
The same to
https://doh.pub/dns-query
https://dns.alidns.com/dns-query
