### ISSUE TITLE
Reset statistics

### ISSUE THREAD

**Issue by xenio** [AdguardTeam/AdGuardHome#746]
Is it possible to reset the dashboard statistics with the web interface or via command line?

**Comment by rfgamaral** [comment]
I'm not sure it's possible. I usually just stop AdGuard (I have it running in a container so it's easy to stop/start), delete the `querylog.json` file and start AdGuard again. It's a bit cumbersome and I give my support for a "Clear Statistics" button 👍

**Comment by xenio** [comment]
@rfgamaral thanks it is enough for me, I need sometime to reset the statistics and deleting the file is ok.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/446
