### ISSUE TITLE
Googleadservices blocked even of adguard is disabled

### ISSUE THREAD

**Issue by skycryer** [AdguardTeam/AdGuardHome#7460]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.57

### Action

I try Open Google search URLs with Domain googleadservices.com but they got blocked. I added also Filters to whitelist the Domain and also disabled adguard without difference. URLs still get blocked. 

### Expected result

Whitelist googleadservices.com or disabled adguard should make the URL Work again. 

### Actual result

URLs get blocked

**Comment by schzhn** [comment]
Browsers cache DNS responses.
