### ISSUE TITLE
Adguard Home not using local cache

### ISSUE THREAD

**Issue by arcticfoxwpg** [AdguardTeam/AdGuardHome#7461]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.54

### Action

Not using local cache. A few days of use and every query is sent out despite visiting the same website continually. Dashboard upstreams only show DNS, no local cache.

### Expected result

Local cache

### Actual result

No local cache

**Comment by tjharman** [comment]
There is nowhere near enough information in this bug report I'm sorry.
Can you show some screenshots of how your cache is setup, how your client(s) are setup etc for caching, and then show multiple rapid requests to a host that aren't being cached?

**Comment by arcticfoxwpg** [comment]
Sure. What is the best thing to definitively show that the cache isn't working - refresh a website mutliple times?

**Comment by tjharman** [comment]
No, because your client will cache DNS as well.
Run "dig" or "nslookup" against your nameserver 10-15 times.

**Comment by tjharman** [comment]
I just ran ~15 rapid "dig @<my adugard> adguard.com" commands and you can see here the cache is working

![image](https://github.com/user-attachments/assets/5785e6b0-98e2-489b-97f4-6a5eb6bc39af)

**Comment by arcticfoxwpg** [comment]
<img width="450" alt="Screenshot 2024-11-25 at 8 28 40 PM" src="https://github.com/user-attachments/assets/b39e63b2-7cab-4867-9b2d-e719be5ad9da">

Cache is supposed to show here right?

**Comment by tjharman** [comment]
No, that's exactly what it say it is, the "average" response time when Adguard hasn't got a cached answer and has to go upstream.

Nothing to do with cache.

**Comment by arcticfoxwpg** [comment]
Ok I thought I saw before that the Cache server appears here as well with a response time.

I am on MacOS - tell me how I do a dig? I cannot find an entry in the Querry log that hasn't gone out to one of the DNS

**Comment by tjharman** [comment]
The command is just "dig"

![image](https://github.com/user-attachments/assets/11cdece6-8b30-4063-a2ee-4da278284663)

Replace 192.168.0.1 with the IP address of your Adguard server.

**Comment by soyelmismo** [comment]
i thought the cache worked automatically when i installed it, but for some reason it doesn't... days ago i edited my config like this:

![imagen](https://github.com/user-attachments/assets/3290d9dd-c84d-4e02-8dc8-d9f6b2ecc43e)

and by doing it now all the responses passed from 80-200ms to 0.2ms 👌

**Comment by arcticfoxwpg** [comment]
Ok I got it to work, thank you - the dig is showing served from cache.

However, the above settings posted by @soyelmismo with the overrides of TTL - is this recommended and if so why isn't it set as default?

Thanks for your help.

**Comment by soyelmismo** [comment]
> is this recommended

hmm idk, i think its the seconds it keeps the domain inside the cache before prioritizing another new domain. so i set it to 1day in seconds, at the moment i don't see issues

**Comment by tjharman** [comment]
Unsure if it's the default or not sorry, I can't remember when I set it up if it was default or not.
Possible it's not default because a lot of people will point it to a very close caching nameserver anyway and there's no point caching it twice?
Keep in mind your clients will also cache DNS entries, so there's often not a LOT of actual performance to be had by the DNS server caching as well _unless_ you have a large number of clients querying it.

I will close this ticket.
