### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by simpleandstupid** [AdguardTeam/AdGuardHome#7465]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

Other (please mention in the description)

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.990+4a49c4db

### Action

在webui中更新至最新edge版本，然后AdGuard Home停止工作，它使我的网络中断。
尝试启动它：
```sh
.\AdGuardHome --no-permcheck
```

### Expected result

AdguardHome正常工作。

### Actual result

```powershell
2024/11/27 20:54:34.945464 [info] AdGuard Home, version v0.108.0-a.990+4a49c4db
2024/11/27 20:54:34.987702 [info] tls: using default ciphers
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x118eb8c]

goroutine 1 [running]:
net/url.(*URL).String(0xc0001db748?)
        net/url/url.go:832 +0x2c
github.com/AdguardTeam/AdGuardHome/internal/updater.NewUpdater(0xc0001db7c8)
        github.com/AdguardTeam/AdGuardHome/internal/updater/updater.go:117 +0x25
github.com/AdguardTeam/AdGuardHome/internal/home.newUpdater({0x251c3f8, 0x30e3fa0}, 0xc00041d860, {0xc0003ac1a0, 0x1c}, {0xc00002d080, 0x2d}, {0xc00002cf30, 0x2c}, 0x2b5dfc0)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:737 +0x4f8
github.com/AdguardTeam/AdGuardHome/internal/home.run({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:631 +0x550
github.com/AdguardTeam/AdGuardHome/internal/home.Main({0x25136c0, 0x25310a0})
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:140 +0x33c
main.main()
        github.com/AdguardTeam/AdGuardHome/main.go:23 +0x25
```

### Additional information and/or screenshots

除此之外，程序webui提供的自动更新似乎存在一些问题，会覆盖原有的文件权限。它使得我的当前用户及SYSTEM失去对它的访问权限。我在手动更改文件权限后受到这个问题的影响。
![图片](https://github.com/user-attachments/assets/4170e213-e0bd-4e0d-bd12-b238e93a31bb)

**Comment by Huntback52** [comment]
Same error here Adguard Home on Docker Synology:
![Scherm­afbeelding 2024-11-27 om 15 16 57](https://github.com/user-attachments/assets/2683eeb8-ddf4-4dea-8131-75afaf91b036)

**Comment by EugeneOne1** [comment]
@simpleandstupid, hello and thanks for the report.  Should be fixed as of `v0.108.0-a.991+9789e5b0`, could you please check it?

**Comment by Huntback52** [comment]
@EugeneOne1, works again :)
Thanks.

**Comment by EugeneOne1** [comment]
Closing, thank you all for testing.
