### ISSUE TITLE
When AdGuard Home Protection is off, Home Assistant UI becomes unavailable

### ISSUE THREAD

**Issue by kimme1024** [AdguardTeam/AdGuardHome#7469]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.54

### Action

Sometimes it's necessary to deactivate the AdGuardHome Protection to be able to let some websites connect services (FamilyCard for example).

I have 2 switches in Home Assistant to deactivate Home Protection and Filtering.

After deactivating these services I can't connect to Home Assistant WebUI anymore. Not via a browser, not via the companion app.

When I reactivate the services via the AdGuardHome WebUI it works again. Also, when I turn off WiFI I can connect to my Home Assistant instance via the companion to re-enable the services that way. Therefore I guess there's something wrong with the DNS settings.

Any way this is fixable?

Thanks in advance!

### Expected result

Home Assistant remains available

### Actual result

Home Assistant becomes unavailable via local network.

### Additional information and/or screenshots

I don't use that HA add-on as I was using AdGuardHome before I switched to HA Supervised.

**Comment by tjharman** [comment]
I'm sorry but I can't see how this is related to Adguard DNS.  If you can clearly state how/why you think this is related to Adguard Home please.

I have Home Assistant and Adguard Home, and I can tweak any settings and Home Assistant keeps working.

I would debug this from the HomeAssistant logs, and raise a ticket with the HomeAssistant Adguard Integration.
