### ISSUE TITLE
DNS rewrites are being ignored

### ISSUE THREAD

**Issue by monogoat** [AdguardTeam/AdGuardHome#7476]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.54

### Action

Accessing a domain specified in the dns rewrites via network clients.

### Expected result

I expect to be redirecting to the IP address that has been configured, like it has previously done.

![image](https://github.com/user-attachments/assets/b91364f0-1eb0-4f2f-b87c-f2380cd06eff)

### Actual result

Adguard's log shows that it is passing the ip address (or lack thereof) that it is getting from the upstream server, instead of rewriting it.

![image](https://github.com/user-attachments/assets/d8170014-bc2f-464b-88e4-6bf38750a381)

### Additional information and/or screenshots

I'm not sure when this stopped working, I've been extra busy at work the last couple months and haven't done much at home. I have two raspberry pi 4s running adguard as primary and secondary dns servers, and both are serving the incorrect information.

**Comment by monogoat** [comment]
I'm sorry, nevermind. I just had a brainstorm as I posted this. The adguard integration in home assistant has protection and filtering switches separated but the adguard GUI has no indication of the filtering switch's status. They had been flipped off somehow.

**Comment by tjharman** [comment]
Seems to work for me just fine?

![image](https://github.com/user-attachments/assets/b3a8b400-d6b6-47fa-9bb3-45912b791a18)
![image](https://github.com/user-attachments/assets/f3938afd-55c6-497d-b0de-554bf66934a6)

Are you sure you're not trying a subdomain like test.chickens.com and that's failing because you haven't' set *.server.cz

**Comment by tjharman** [comment]
Ahhh, posted 2 seconds before my reply! All good glad you sussed it.

**Comment by Onepamopa** [comment]
Same deal @ home assistant... the integration shows "ON", but dns rewrites aren't working?
How did you solve it?!

**Comment by monogoat** [comment]
> Same deal @ home assistant... the integration shows "ON", but dns rewrites aren't working? How did you solve it?!

In my case, Protection was switched on but filtering was switched off in the integration (I believe it was that way around). There was no indication in the adguard UI that filtering was off, just that switch in home assistant.
