### ISSUE TITLE
Link in Readme goes to an outdated page

### ISSUE THREAD

**Issue by MaggieFero** [AdguardTeam/AdGuardHome#7477]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Custom (please mention in the description)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

N/A

### Action

Replace the following command with the one you're calling or a
description of the failing action:

In the Manual Installation section of the Readme, click the link to the getting started article

### Expected result

I expect to see the current version of the getting started article

### Actual result

The article it links to says it's outdated, and suggests a newer version on the knowledgebase website instead.

### Additional information and/or screenshots

Sorry this is a weird one, but I couldn't find a better issue template for a docs bug. I have a PR ready to file but docs said you'd always like an issue first, so here it is. I can't imagine you want to be linking to a doc you've labeled outdated, but just in case, here you go!

**Comment by ainar-g** [comment]
Good day!  Yes, this is a mistake, and the link should indeed lead to the current version in the DNS Knowledge Base.  Please do send the PR and thank you for reporting this!

**Comment by MaggieFero** [comment]
Thanks for the quick response, and you're welcome for the report! I've filed the PR.
