### ISSUE TITLE
Cache is not used for persistent clients those have specific upstream set

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdGuardHome#7489]
When you add a client into the Persistent client section and set upstream dns server for that client to e.g. `[/example.local/]94.140.14.140`. 
![image](https://github.com/user-attachments/assets/7f9dacfb-5f9f-4f88-b622-0aa223f30ade)
Then AGH will no longer use cache for any query from that client, no matter what domain is being queried.
![image](https://github.com/user-attachments/assets/7b65ded0-4f24-49c5-9421-91364893c75f)

AGH version: v0.107.54

**Comment by Dynamic5912** [comment]
Have you ticked the box at the bottom of the custom DNS page to enable client caching?

![image](https://github.com/user-attachments/assets/918301cf-ee85-4c7a-93c0-87234f8a7a69)

**Comment by trmdi** [comment]
No, it's not checked. The cache is intended to work only when that one is checked?

**Comment by Dynamic5912** [comment]
When using a custom upstream per client - yes.
