### ISSUE TITLE
address: 0.0.0.0:80 works，  address: [::]:80  does not work

### ISSUE THREAD

**Issue by U201413497** [AdguardTeam/AdGuardHome#7490]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARMv7

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.54

### Action

http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:80
  session_ttl: 720h

### Expected result

http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:80
  address: [::]:80
  session_ttl: 720h

### Actual result

AdguardHome can not start

**Comment by ainar-g** [comment]
That is not valid YAML.  IPv6 addresses must be within quotation marks and there must not be any duplicated keys.
