### ISSUE TITLE
service and permissions issues Windows 11 

### ISSUE THREAD

**Issue by McR1983** [AdguardTeam/AdGuardHome#7492]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.54

### Action

As soon as I start the service there are problems with the permissions under Windows.
These are overwritten and after a Windows restart the Adguard service says no more access. Then I can take over the folder again and then it works again. But it's a huge effort. The same applies when the service has been started. Then I can no longer adjust filter lists because the folder/file permissions are lost.

### Expected result

C:\Program Files (x86)\AdGuardHome>adguardhome.exe --check-config
2024/12/11 03:17:08.572531 [info] AdGuard Home, version v0.107.54
2024/12/11 03:17:08.642775 [info] tls: using default ciphers
2024/12/11 03:17:08.642775 [info] configuration file is ok

C:\Program Files (x86)\AdGuardHome>adguardhome.exe --update
2024/12/11 03:18:15.343930 [info] AdGuard Home, version v0.107.54
2024/12/11 03:18:15.409401 [info] tls: using default ciphers
2024/12/11 03:18:15.458820 [info] dnsproxy: upstream mode is set mode=load_balance
2024/12/11 03:18:15.459388 [info] dnsproxy: cache enabled size=4096
2024/12/11 03:18:15.461185 [info] dnsproxy: max goroutines is set count=300
2024/12/11 03:18:15.461185 [info] dnsproxy: cache ttl override is enabled min=1800 max=7200
2024/12/11 03:18:15.461185 [info] dnsproxy: ratelimit is enabled rps=5000 ipv4_subnet_mask_len=24 ipv6_subnet_mask_len=56
2024/12/11 03:18:15.461814 [info] dnsproxy: server will refuse requests of type any
2024/12/11 03:18:15.461814 [info] dnsproxy: upstream mode is set mode=load_balance
2024/12/11 03:18:15.461814 [info] dnsproxy: cache enabled size=10000000
2024/12/11 03:18:15.461814 [info] dnsproxy: max goroutines is set count=300
2024/12/11 03:18:15.462410 [info] cmdline update: performing update
2024/12/11 03:18:15.462988 [info] addrproc: processing addresses
2024/12/11 03:18:15.809439 [info] no updates available

### Actual result

![2024-12-11 03_20_00-AdGuard Home ](https://github.com/user-attachments/assets/c7a5b715-bad4-430e-802a-ce88b115692b)

### Additional information and/or screenshots

Edition	Windows 11 Pro
Version	24H2
Installiert am	‎27.‎11.‎2024
Betriebssystembuild	26100.2454
Leistung	Windows Feature Experience Pack 1000.26100.36.0

Prozessor	Intel(R) Core(TM) i7-14700K   3.40 GHz
Installierter RAM	64,0 GB (63,3 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

**Comment by McR1983** [comment]
No result since Nov 9 // windows folder permissions change issue #7426 
https://github.com/AdguardTeam/AdGuardHome/discussions/7426

**Comment by EugeneOne1** [comment]
@McR1983, hello and thanks for the report.  It's a known issue with `v0.107.54`, see #7400.  Please consider using the latest release, which doesn't seem to cause this problem.  The permissions should be fixed manually before the update, see the https://github.com/adguardTeam/adGuardHome/issues/7400#issuecomment-2483341957.  If you have installed the AdGuard Home as a Windows service, you may need to stop it first.

We'll close this issue for now, please consider reporting it on #7400 or ask any further questions in the **Discussions** section.
