### ISSUE TITLE
Blocked Splash Screen

### ISSUE THREAD

**Issue by bfnboertjie** [AdguardTeam/AdGuardHome#7493]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

the lack of build in blocked splash screens. IE malware , parental etc

### Proposed solution

The feature was removed in newer versions a return of the feature would look nice.

**Comment by Dynamic5912** [comment]
It was never included in AGH.

**Comment by ainar-g** [comment]
Duplicate of #1165.  See [our FAQ](https://adguard-dns.io/kb/adguard-home/faq/#customblock) for the limitations and the current recommended workaround.
