### ISSUE TITLE
domain server lookup mapping

### ISSUE THREAD

**Issue by bigstusexy** [AdguardTeam/AdGuardHome#7495]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

Lookups don't always happen the way I'd like, sometimes I get not results because of the server that responds fastest or the preferred server isn't responding. (This is different than not getting a response) 

### Proposed solution

The ability to set the preferred server for a specified domain.

for example, where adguard is only acting as a DNS proxy.  Local clients are still getting DHCP and registering their names with another system.  
Lets say 192.168.1.254/24 is myhome.internal
Also       10.10.200.1/24    is remote.domain  (VPN)

I'd like to be able to tell adguard that any requests for *.myhome.internal should only be resolved by 192.168.1.254, .., ...
As well as any requests for *.remote.domain be resolved by 10.10.200.1 

This should be per domain as listed, so if you specify that subdomain, that is all it does, if one where to put IDontActuallyOwnThis.com, then that's all it does, not send all .com TLD there - unless they were foolish enough to enter *.com

This will guarantee resolution for domains.  Currently, what can and is happening in my case is that my local internal DNS is not responding either fast enough for at all, remote DNS servers, according to the logs, are returning nxdomain responses, which tells clients, they can't find the target.  However under this idea, they should get no response from the local server.  Be it slow, or no response at all - which will trigger client timeouts which will cause different error messages, possibly letting the user know the DNS server is not responding rather than a response that the item doesn't exist. 

### Alternatives considered and additional information

Running a different DNS server as a forwarding server which can do this.  Mark out your forwarding for those domains and send everything else to AdGuard and then on. 

Looking into AdGuard as the DHCP server and local domains, would not resolve VPN domains though. 

Only using AdGuard for things that will not look for local clients. 

This could be windows being stupid. Although I can see nxdomain results for these queries in the logs, windows, browsers cannot resolve these names, an nslookup does.  This issue isn't persistent, I have had this working.

**Comment by ainar-g** [comment]
How exactly is this different from the current ability to [set upstreams for domains](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains)?

**Comment by bigstusexy** [comment]
It is not!  I haven't read through all the documentation, didn't even know there was a command line, I thought it was exposed on the web interface.  I guess that would be my one ask, to have it be in the web interface.  I've got a cloud AP product and every time I ask about something advanced, "Oh you can do it via the API" Which is more involved than command line, and it drives me nuts. 

Thank you.
