### ISSUE TITLE
 edns-client-subnet (ECS) support

### ISSUE THREAD

**Issue by portalvasco** [AdguardTeam/AdGuardHome#75]
Its a good point if Adguard DNS supports ECS.

**Comment by ameshkov** [comment]
We don't yet support it.

Some info for devs below:

**RFC**
https://tools.ietf.org/html/draft-ietf-dnsop-edns-client-subnet-08

Google public DNS supports it:
https://groups.google.com/forum/#!topic/public-dns-announce/67oxFjSLeUM

**Comment by portalvasco** [comment]
OpenDNS supports too.

**Comment by ArchiveBase** [comment]
#75 https://github.com/AdguardTeam/AdGuardHome/commit/2b14a043a984d536358405833aff6f47c0067b9d
