### ISSUE TITLE
Custom filtering rules don't applicated for all

### ISSUE THREAD

**Issue by moi162001** [AdguardTeam/AdGuardHome#7507]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

version:  v0.107.55

### Action

Following the latest AdGuard update, the custom filter rules are behaving oddly.
A concrete example with openproject.org:
The allow rule is correctly set: @@||openproject.org^, but access is only granted if AdGuard is disabled.
This behavior is also observed on Brave.

### Expected result

Custom filtering rules
@@||openproject.org^

openproject.org
Open source project management software

### Actual result

Ce site est inaccessible
www.openproject.org n'autorise pas la connexion.
Voici quelques conseils :

Vérifier la connexion
[Vérifier le proxy et le pare-feu](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

**Comment by Dynamic5912** [comment]
What does the query log show?

**Comment by moi162001** [comment]
Exactly, the logs show nothing being blocked.

**Comment by ainar-g** [comment]
I cannot reproduce this.  If you do not see the queries in the query log, it could be that the browser isn't using AdGuard Home at all, and can instead use its own secure DNS server.  Additionally, it could be that your upstream is actually blocking the domain (i.e. when your Private AdGuard DNS server is the upstream).

**Comment by moi162001** [comment]
Hi,
Ok, i check parameter again.
Close this issue.
thanks
