### ISSUE TITLE
Dashboard log filtering improvement

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#751]
I suggest you make the filtering as a drop-down, since, for example if I write IP 10.0.0.3
I also get results from 10.0.0.33, which does not interest me in that particular instance.

In an attempt to remedy this, I added hosts entries to all the local IPs, however, the "filter" only works with an IP address, not host names: thehostname (10.0.0.3)

**Comment by ArchiveBase** [comment]
Same https://github.com/AdguardTeam/AdGuardHome/issues/636

**Comment by szolin** [comment]
Use double quotes for strict matching of client's IP address
