### ISSUE TITLE
Block Odysee as a service

### ISSUE THREAD

**Issue by semiju** [AdguardTeam/AdGuardHome#7518]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I'd like to be able to block the video platform, Odysee, as a service (under client settings). For now I have it blocked via the custom filtering rules, but I'd like to be able to use scheduling and more easily apply and remove the blocking to specific clients.

### Proposed solution

Add Odysee as a service that can be blocked. I am not sure if blocking each is necessary, but the following domains are associated with Odysee:
odysee.tv
odysee.com
odysee.live
odycdn.com

### Alternatives considered and additional information

The only alternative is to use custom filtering rules, but there the minor drawbacks of this process being a bit more difficult, and being unable to use scheduling that is available with blocking services.

**Comment by ainar-g** [comment]
See the [contribution guidelines](https://github.com/AdguardTeam/AdGuardHome/blob/20e56b71719aa9aa74f78851f31a54d27d4d5602/CONTRIBUTING.md).

> Please don't:
> - …
> - send or request updates to filtering-rule lists, such as the ones for the Blocked Services feature or the list of approved filtering-rule lists. We update them from the [separate repository](https://github.com/AdguardTeam/HostlistsRegistry) once before each Beta and Release build.
