### ISSUE TITLE
Internet totally blocked

### ISSUE THREAD

**Issue by sdennis91** [AdguardTeam/AdGuardHome#7524]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Darwin (aka macOS), AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

2838

### Action

Replace the following command with the one you're calling or a
description of the failing action:

```sh
nslookup -debug -type=a 'www.example.com' '$YOUR_AGH_ADDRESS'
```
Blocks internet complete. You guys are a joke. 

### Expected result

To be able to block ads. Not block the entire internet.

### Actual result

Total internet outage.

**Comment by ainar-g** [comment]
> 2838

That's not a valid AdGuard Home version.  Please fill out the issue template and also make sure you've [configured your devices properly](https://adguard-dns.io/kb/adguard-home/faq/#doesntblock).

**Comment by bcookatpcsd** [comment]
The second video is more relevant.. but if you don't know the IT Crowd you need the first for reference/scaffolding.. 

1st: https://www.youtube.com/watch?v=iDbyYGrswtg

2nd: https://www.youtube.com/watch?v=Vywf48Dhyns

![image](https://github.com/user-attachments/assets/ff902c2c-bbc0-4a97-b5ca-69dc2aba4c5f)

Thankfully the Internet is still working..
