### ISSUE TITLE
AGH fails to start when the query log is corrupted

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#753]
Failed to decode: invalid character '\x00' looking for beginning of value

Unable to start AdGuardHome at all, this log message spams the syslog.

The problem is related to unexpected power down of the linux machine. The query log file was causing the problem when AdGuardHome was initializing.

After removing the contents of query log, it runs normally.

**Comment by Eyeborgs** [comment]
I had it on Windows 10 after an emergency restart.

**Comment by Onepamopa** [comment]
They should do some sanity-check on the log before loading, else it spams a lot of these...

**Comment by ameshkov** [comment]
Thank you for reporting this! This needs to be addressed indeed.

**Comment by Onepamopa** [comment]
@ameshkov Not only that it fails to start, it can fill a 60GB partition with "failed to decode" in 10-20 minutes....

**Comment by szolin** [comment]
In an attempt to skip corrupted log entries when reading from file we put the program into an endless loop.  We should stop reading from a corrupted log file, delete it, and then start operating as normal.

**Comment by Onepamopa** [comment]
@szolin or just skip the corrupted lines and proceed.

**Comment by ilya-fedin** [comment]
Are there any progress on this issue? This bug is very painful when AGH acts as a DHCP server. It would be very good if AGH renamed (but did not delete) the existing log and reported damage in the web interface.

**Comment by ameshkov** [comment]
@ilya-fedin assigned this but to v0.100, thanks for reminding us!

**Comment by szolin** [comment]
In the upcoming v0.99 this issue won't affect startup anymore.
However, we still need to skip corrupted lines.
