### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by SpirioSpirio** [AdguardTeam/AdGuardHome#7533]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.55

### Action

Setup Firefox with DOH enable with https://dns.spirio.fr/dns-query

![image](https://github.com/user-attachments/assets/d29d49a1-2baf-4e0b-8fdc-7df8b04021b5)
Run a dnsleak test - https://browserleaks.com/dns
![image](https://github.com/user-attachments/assets/fbbabe44-8a8e-4b7f-89db-143c14568ade)

I did with the Nextdns offered by default.
![image](https://github.com/user-attachments/assets/003eb68b-5baf-42fb-a9b9-cc28c3280abe)
No leak...
![image](https://github.com/user-attachments/assets/8ccb0d75-d9a4-455c-9d14-3880a11e8a13)

I put all my configuration below, it is run in a Docker container.

### Expected result

Your DNS Servers	
IP Address :	ISP :	Location :
[178.255.154.89](https://browserleaks.com/ip/178.255.154.89) 	ANEXIA Internetdienstleistungs GmbH	Czechia, Prague
[2a00:11c0:4:350::7](https://browserleaks.com/ip/2a00:11c0:4:350::7) 	ANEXIA Internetdienstleistungs GmbH	Czechia, Prague

### Actual result

Test Results	Found 9 Servers, 2 ISP, 2 Locations
Your DNS Servers	
IP Address :	ISP :	Location :
[35.212.17.126](https://browserleaks.com/ip/35.212.17.126) 	Google LLC	United States, Washington D.C.
[35.212.55.229](https://browserleaks.com/ip/35.212.55.229) 	Google LLC	United States, Washington D.C.
[35.212.56.10](https://browserleaks.com/ip/35.212.56.10) 	Google LLC	United States, Washington D.C.
[35.212.59.223](https://browserleaks.com/ip/35.212.59.223) 	Google LLC	United States, Washington D.C.
[35.212.63.167](https://browserleaks.com/ip/35.212.63.167) 	Google LLC	United States, Washington D.C.
[35.212.84.34](https://browserleaks.com/ip/35.212.84.34) 	Google LLC	United States, Washington D.C.
[35.212.97.244](https://browserleaks.com/ip/35.212.97.244) 	Google LLC	United States, Washington D.C.
[178.255.154.89](https://browserleaks.com/ip/178.255.154.89) 	ANEXIA Internetdienstleistungs GmbH	Czechia, Prague
[2a00:11c0:4:350::7](https://browserleaks.com/ip/2a00:11c0:4:350::7) 	ANEXIA Internetdienstleistungs GmbH	Czechia, Prague

### Additional information and/or screenshots

Current configuration :
http:
  pprof:
    port: 6060
    enabled: false
  address: XXX
  session_ttl: 720h
users:
  - name: XXX
    password: XXX
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
theme: auto
dns:
  bind_hosts:
    - XXX
  port: 53
  anonymize_client_ip: false
  ratelimit: 10
  ratelimit_subnet_len_ipv4: 24
  ratelimit_subnet_len_ipv6: 56
  ratelimit_whitelist:
  refuse_any: true
  upstream_dns:
    - 193.110.81.0
    - 185.253.5.0
  upstream_dns_file: ""
  bootstrap_dns:
    - 193.110.81.0
  fallback_dns: []
  upstream_mode: load_balance
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - '||cisco.com'
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: true
  edns_client_subnet:
    custom_ip: ""
    enabled: true
    use_custom: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  bootstrap_prefer_ipv6: false
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  use_dns64: false
  dns64_prefixes: []
  serve_http3: false
  use_http3_upstreams: false
  serve_plain_dns: true
  hostsfile_enabled: true
tls:
  enabled: true
  server_name: dns.spirio.fr
  force_https: true
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 853
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: |-
    -----BEGIN CERTIFICATE-----
    MIIDezCCAwGgAwIBAgISBK3WHrwqSoDqdmjOkPG4Tuz7MAoGCCqGSM49BAMDMDIx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
    NTAeFw0yNDExMTYwNTEwMDJaFw0yNTAyMTQwNTEwMDFaMBgxFjAUBgNVBAMTDWRu
    cy5zcGlyaW8uZnIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATM1XKVCuZx3kOe
    GEBqfZqGMoRabF/Qk46XpuRa6yLVzx5wU6TnVsr9hju0Z/+hy7ljC5ST/EJ2om/i
    JkSujAXao4ICDzCCAgswDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUF
    BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQPlqb+N7KZDGEq
    77AyMFoiYbSgzTAfBgNVHSMEGDAWgBSfK1/PPCFPnQS37SssxMZwi9LXDTBVBggr
    BgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9lNS5vLmxlbmNyLm9yZzAi
    BggrBgEFBQcwAoYWaHR0cDovL2U1LmkubGVuY3Iub3JnLzAYBgNVHREEETAPgg1k
    bnMuc3BpcmlvLmZyMBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBAYKKwYBBAHWeQIE
    AgSB9QSB8gDwAHYAzxFW7tUufK/zh1vZaS6b6RpxZ0qwF+ysAdJbd87MOwgAAAGT
    M5Zd9QAABAMARzBFAiAeua1CiS8tpNhn3oljXNj0XNlycVGoPtWuuKbUqCMLBQIh
    AKRFDgIuPvkps0GIr9U/ogNLEt131bz9KtdqC73ag/QEAHYAE0rfGrWYQgl4DG/v
    THqRpBa3I0nOWFdq367ap8Kr4CIAAAGTM5ZefQAABAMARzBFAiB0AyOQJNGKG5f0
    wUWXeZhpaSDMNaJDS93ENxmt3YnXyAIhAM6Jp+wTFooXQ8hwMsi31zvA9VSntHpF
    yKoTHJBOQXYlMAoGCCqGSM49BAMDA2gAMGUCMQCLZ/Yxj1rUSkp7HV3E0eR0q0Nd
    xFNc2LZxuqlVi7BGhOYSRDWMJegn6V1HiY6csYgCMEJdTeKA/hls7PIfl6LCSjjh
    WulLCg5J042RSwpqWvtI2wrHAWHKWl5PVFFWjaRsLQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEVzCCAj+gAwIBAgIRAIOPbGPOsTmMYgZigxXJ/d4wDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
    WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCRTUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQNCzqK
    a2GOtu/cX1jnxkJFVKtj9mZhSAouWXW0gQI3ULc/FnncmOyhKJdyIBwsz9V8UiBO
    VHhbhBRrwJCuhezAUUE8Wod/Bk3U/mDR+mwt4X2VEIiiCFQPmRpM5uoKrNijgfgw
    gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
    ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSfK1/PPCFPnQS37SssxMZw
    i9LXDTAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
    AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
    BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
    Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAH3KdNEVCQdqk0LKyuNImTKdRJY1C
    2uw2SJajuhqkyGPY8C+zzsufZ+mgnhnq1A2KVQOSykOEnUbx1cy637rBAihx97r+
    bcwbZM6sTDIaEriR/PLk6LKs9Be0uoVxgOKDcpG9svD33J+G9Lcfv1K9luDmSTgG
    6XNFIN5vfI5gs/lMPyojEMdIzK9blcl2/1vKxO8WGCcjvsQ1nJ/Pwt8LQZBfOFyV
    XP8ubAp/au3dc4EKWG9MO5zcx1qT9+NXRGdVWxGvmBFRAajciMfXME1ZuGmk3/GO
    koAM7ZkjZmleyokP1LGzmfJcUd9s7eeu1/9/eg5XlXd/55GtYjAM+C4DG5i7eaNq
    cm2F+yxYIPt6cbbtYVNJCGfHWqHEQ4FYStUyFnv8sjyqU8ypgZaNJ9aVcWSICLOI
    E1/Qv/7oKsnZCWJ926wU6RqG1OYPGOi1zuABhLw61cuPVDT28nQS/e6z95cJXq0e
    K1BcaJ6fJZsmbjRgD5p3mvEf5vdQM7MCEvU0tHbsx2I5mHHJoABHb8KVBgWp/lcX
    GWiWaeOyB7RP+OfDtvi2OsapxXiV7vNVs7fMlrRjY1joKaqmmycnBvAq14AEbtyL
    sVfOS66B8apkeFX2NY4XPEYV4ZSCe8VHPrdrERk2wILG3T/EGmSIkCYVUMSnjmJd
    VQD9F6Na/+zmXCc=
    -----END CERTIFICATE-----
  private_key: |-
    -----BEGIN PRIVATE KEY-----
PRIVATE
    -----END PRIVATE KEY-----
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false

**Comment by Dynamic5912** [comment]
Why are you using browser DOH with AGH?

**Comment by SpirioSpirio** [comment]
> Why are you using browser DOH with AGH?

Sometime, you don't have the possibility to set the global DNS of your computer, and you can only set the one used by your browser.

I got the same behaviour DNS leak when I set it globally, but I wanted to exclude others parameters. So with DOH configured, the DNS leak could only come from ADG.

**Comment by Dynamic5912** [comment]
What dns servers are set in AGH?

**Comment by saint-lascivious** [comment]
> What dns servers are set in AGH?

Try reading the supplied config.

**Comment by whyisthisbroken** [comment]
The Problem is not AGH, its the DNS Provider itself. I´ve got the same results as you with the Firefox Settings and "https://dns.spirio.fr/"

Neither Quad9, Cloudflare, or NextDNS have this behavior.
It will probably be the case that the provider spirio.fr uses some Google servers to offer its service.

![Screenshot 2024-12-29 091517](https://github.com/user-attachments/assets/856358ed-2868-47c5-9e09-25ec0e4f7275)

So I don't see any problem other than the DNS provider you choose.

**Comment by SpirioSpirio** [comment]
Thank you for your analysis @whyisthisbroken!

I didn't write it, but I am the administrator of dns.spirio.fr, and I set dns0.eu as DNS server for dns.spirio.fr. I trusted them blindly, as they claim to be The European public DNS that makes your Internet safer. It was a mistake, their DNS server leaks! :o

I change the configuration of AdGuardHome in order to use 9.9.9.9 and there is no leak any more.

Thank you for your help!

**Comment by whyisthisbroken** [comment]
No problem, but you shouldn't make your address public yet, at the moment it looks like this when I call up the following: https://dns.spirio.fr/ (it will go to https://dns.spirio.fr/login.html )
![Screenshot 2024-12-29 094455](https://github.com/user-attachments/assets/4d9aa418-04f6-4226-b030-2e75e1e3191a)
