### ISSUE TITLE
AdGuardHome Runs when Browser is closed

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#754]
Should have an option on/off such that when Browser is closed computer resources are reduced if AdGuardHome was not working.  Also!! Very important.  Time Machine was unbelievably slow, taking hours for what once took minutes - when AdGuardHome was turned off the backups went faster.  

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

MACbookPro Open VPN ipFire Cable Router
|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0).95 HotFix
| How did you setup DNS configuration:| (System/Router/IoT) DNS is CloudFlare from within ipFire
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1) Mojave 10.14.4

**Comment by ameshkov** [comment]
AdGuard Home is not supposed to be running this way.

You'd better use a traditional ad blocker instead.
