### ISSUE TITLE
[Feature Request] - Show unique filtered

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#755]
It would be nice if we had "Show unique filtered" so we can easily whitelist what's needed.

And I'm not talking about "Show filtered" where it shows the whitelisted entries as well. I mean - show only the records that are blocked, not whitelisted.

If We need "Show Whitelisted" - you can do that too.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/733

**Comment by ArchiveBase** [comment]
Already listed here https://github.com/AdguardTeam/AdGuardHome/issues/882#issuecomment-511571911

> And I'm not talking about "Show filtered" where it shows the whitelisted entries as well. I mean - show only the records that are blocked

1. Show blocked by filters

> If We need "Show Whitelisted" - you can do that too

4. Show whitelisted
