### ISSUE TITLE
Youtube with Adguard DNS gives "This video is restricted. Try signing in with a Google Apps account."

### ISSUE THREAD

**Issue by ajongsma** [AdguardTeam/AdGuardHome#756]
When using the Adguard DNS servers YouTube videos mention "This video is restricted. Try signing in with a Google Apps account." after which the video is blocked from viewing.
When changing the DNS to for example Google, the video plays without issues.

### Steps to reproduce
1. Change Upstream DNS servers to tls://dns.adguard.com
2. Open YouTube and try to play PS4 game related videos, for example https://www.youtube.com/watch?v=EDn3dXgEZf0

### Expected behavior
Video should be playing without issues

### Actual behavior
Video is blocked due to "This video is restricted. Try signing in with a Google Apps account."
</details>

### Your environment
AdGuard Home v0.94

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.94
| How did you setup DNS configuration:| Raspberry Pi 3 Model B with Upstream DNS configured
| Operating system and version:| RaspBian

**Comment by ameshkov** [comment]
Check if you have "Safe Search" enabled in AGH settings. It forces restricted mode on Youtube.

**Comment by snothub** [comment]
Why is safe search messing with Google restricted mode? Shouldn't those be separated? I'd like to keep the safe search but not restricted mode, as it blocks way too much on YouTube.

**Comment by ameshkov** [comment]
There's a different feature request for that: #1349
