### ISSUE TITLE
localbitcoins blocked by adguard

### ISSUE THREAD

**Issue by syabro** [AdguardTeam/AdGuardHome#757]
### Steps to reproduce
1. Register at localbitcoins.net
2. Select a merchant to buy bitcoins
3. Enter any amount and press "send trade request"
4.  Page is blocked with `/* Blocked by AdGuard */`

### Expected behavior
Page not blocked

### Actual behavior
Page is blocked

<details><summary>Screenshot:</summary>
<img width="597" alt="image" src="https://user-images.githubusercontent.com/29029/57675027-7595d080-7629-11e9-92b5-cf67e85a8dc0.png">
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.5.4)
| How did you setup DNS configuration:| (System)
| If it's a router or IoT, please write device model:| 
| Operating system and version:| Mac OS Mojave 10.14.4 (18E226) |

**Comment by Alex-302** [comment]
It seems you are using AdGuard for Mac. Please try to add this rule to custom filter:
```
@@||localbitcoins.net/ad/
```

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #33802](https://github.com/AdguardTeam/AdguardFilters/issues/33802) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Moved to correct repository.
