### ISSUE TITLE
Google DoH server can't use

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#759]
### Steps to reproduce
1. Add `https://dns.google.com/resolve?`
1. Click `test upstreams`

### Expected behavior

`Specified DNS servers are working correctly`

### Actual behavior

`Server "https://dns.google.com/resolve?": could not be used, please check that you've written it correctly`

### Your environment
| Description | Value |
| - | - |
| Version of AdGuard Home server: | v0.95-hotfix
| How did you setup DNS configuration: | System
| If it's a router or IoT, please write device model: | PC
| Operating system and version: | Windows 8.1 x64

**Comment by ameshkov** [comment]
Google's DOH server is on `https://dns.google.com/experimental`

**Comment by bestpika** [comment]
So https://kb.adguard.com/en/general/dns-providers#google-dns have to fix

**Comment by ameshkov** [comment]
Yeah, you're right, thank you!
