### ISSUE TITLE
Add filter issue

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#760]
### Steps to reproduce

1. Try add `https://mirror1.malwaredomains.com/files/domains.hosts`

### Actual behavior

`Error: control/filtering/add_url | Couldn't fetch filter from url https://mirror1.malwaredomains.com/files/domains.hosts: non-text response application/octet-stream | 400`

### Your environment

| Description | Value |
| - | - |
| Version of AdGuard Home server: | v0.95-hotfix
| How did you setup DNS configuration: | System
| If it's a router or IoT, please write device model: | PC
| Operating system and version: | Windows 8.1 x64

**Comment by szolin** [comment]
Note: only `text/plain` content-type is currently supported.  Maybe we should just remove this check.

**Comment by bestpika** [comment]
If website response content type setting wrong then the filter can't add.

**Comment by szolin** [comment]
Will be fixed here: https://github.com/AdguardTeam/AdGuardHome/issues/527
