### ISSUE TITLE
How to get dOT dns server running behind traefik

### ISSUE THREAD

**Issue by Akruidenberg** [AdguardTeam/AdGuardHome#762]
It would be nice if someone want's to write a tuturial to get the Adgard DoT server running behind traefik. Web interface behind port 3000 works perfectly fine. But port 443 dont works with Traefik.

Update: web intrafece works with port 443. Using a wildcard domain with the content from the .cert file. 
/dns-query wont work, and when set the domain with my phone, (moto g6 android pie) it wont connect. 

What to do now?

**Comment by ibksturm** [comment]
hi there

a) what is traefik? is that the smart ikea bulbs and led? and no, i‘m not joking

b) just thinking loud, maybe you could use nginx as „balancer as i did it on my public dns server. look at https://github.com/ibksturm/dnscrypt-switzerland
 how i used nginx

**Comment by BurtonChia** [comment]
I'm running it behind Traefik. You'll need to map port 853 not 443 for DoT. I'm mapping both TCP and UDP in host mode.
