### ISSUE TITLE
Uninstalling AGH

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#763]
Nothing comes to the top when the FAQ are asked.  Per AGH instructions AGH was installed using Terminal and runs on start-up of the MAC.  I'd like to return to starting AGH on demand from the the GUI.  How is AGH uninstalled using Terminal.  Once uninstalled how does AGH start normally.

The reason I am uninstalling AGH from auto start is that according to Activity Monitor AGH runs even when the Browser is not even in the dock.  While it doesn't use much resources there was a note from github that it should not be doing that.
  

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment
The image attached from Activity Monitor show AGH and another Privacy ( part of AGH ?) using resources though AGH is red/off from the GUI.

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)95 hot fix
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)MAC 14.4.4
<img width="860" alt="Screen Shot 2019-05-16 at 7 46 25 PM" src="https://user-images.githubusercontent.com/48414915/57894067-696d6700-7813-11e9-9dcc-e322ab425e02.png">

**Comment by ameshkov** [comment]
Uninstalling the service? It's all there: https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#service

The command:
`sudo ./AdGuardHome -s uninstall`

**Comment by All4Gears** [comment]
$ ./Adguardhome -s uninstall
2019/05/21 14:32:45 [info] Service control action: uninstall
2019/05/21 14:32:45 [fatal] Failed to uninstall AdGuard Home service: remove /Library/LaunchDaemons/AdGuardHome.plist: permission denied
$

**Comment by ameshkov** [comment]
@All4Gears you need to run it with `sudo`:
`sudo ./AdGuardHome -s uninstall`
