### ISSUE TITLE
Strengthen the config file permissions

### ISSUE THREAD

**Issue by Rowno** [AdguardTeam/AdGuardHome#764]
The `AdGuardHome.yaml` config file contains a couple of plain text secrets (like the auth password and SSL certificate private key) but the file is readable by every user on the system. The config file should only be readable by the `root` user in the same way that the `certbot` generated certificate private keys are.

From what I can tell, this code is causing the config file permissions to be set to readable by all users on every server boot:
https://github.com/AdguardTeam/golibs/blob/dda471290533922d19c132eff717804a811b6a53/file/file.go#L20

### Steps to reproduce
1. `sudo chmod 0600 /opt/adguardhome/conf/AdGuardHome.yaml`
2. Restart the server.

### Expected behavior
`ls -l /opt/adguardhome/conf/AdGuardHome.yaml` should  output `-rw------- 1 root root`.

### Actual behavior
`ls -l /opt/adguardhome/conf/AdGuardHome.yaml` outputs `-rw-r--r-- 1 root root`.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95-hotfix
| How did you setup DNS configuration:| System
| If it's a router or IoT, please write device model:| N/A
| Operating system and version:| Ubuntu 18.04.2

**Comment by ameshkov** [comment]
Yep, thank you!

**Comment by Rowno** [comment]
Another way to mitigate it would be to add support for loading the SSL certificate from a separate file (would make setting up automated Let Encrypt certificate renewals a lot easier too).

#634

**Comment by ainar-g** [comment]
I will merge this issue into #3200, if nobody minds.  We will make permissions more restrictive for other files as well.
