### ISSUE TITLE
ntent.com block githubusercontent.com

### ISSUE THREAD

**Issue by vsim3** [AdguardTeam/AdGuardHome#768]
rule ntent.com block githubusercontent.com

### Steps to reproduce

1. AdGuardHome 0.95-hotfix with this pullrequest https://github.com/AdguardTeam/AdGuardHome/pull/743
2. add this hosts https://raw.githubusercontent.com/vsim3/hosts/master/ads
3. go to githubusercontent.com

### Expected behavior

adguard not block it

### Actual behavior

adguard block the site

<details><summary>Screenshot:</summary>

![Screenshot_20190519_155218](https://user-images.githubusercontent.com/50333987/57980014-c97f2b80-7a14-11e9-8940-eb3efbc83453.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95-hotfix with https://github.com/AdguardTeam/AdGuardHome/pull/743
| How did you setup DNS configuration:| System
| Operating system and version:| Fedora 29

**Comment by ameshkov** [comment]
The issue will go away in v0.96 when we start using https://github.com/AdguardTeam/urlfilter library
