### ISSUE TITLE
Comments are counted as rules

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#771]
### Steps to reproduce

1. Add `https://bestpika.github.io/abp/hosts.txt`

### Expected behavior

Rules count is zero.

### Actual behavior

Rules count show 1.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/5698157/58027782-f6822a00-7b4b-11e9-944c-0237870a2d7d.png)
![image](https://user-images.githubusercontent.com/5698157/58027531-66dc7b80-7b4b-11e9-820d-84870fdbf623.png)

</details>

### Your environment

| Description | Value |
| - | - |
| Version of AdGuard Home server: | v0.95-hotfix
| How did you setup DNS configuration: | System
| If it's a router or IoT, please write device model: | PC
| Operating system and version: | Windows 10 x64/Windows 8.1 x64

**Comment by szolin** [comment]
Yes, that's because we don't handle `#...` as a line comment.  We should fix `parseFilterContents()`.
