### ISSUE TITLE
localhost "blocked"

### ISSUE THREAD

**Issue by Omoeba** [AdguardTeam/AdGuardHome#772]
### Steps to reproduce

1.install adguard home and select all filters
2.set adguard home as system dns server for client(s)
3.look at query log and top blocked domains

### Expected behavior

localhost should not be marked as blocked when a hosts file defines it as 127.0.0.1 and ::1; for example in hpHosts
### Actual behavior

localhost is listed as the top blocked domain and the query log is filled by it

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95-hotfix
| Operating system and version:| Ubuntu 18.04 LTS

**Comment by ameshkov** [comment]
I am not sure if this can be considered a bug.

Every domain listed in any filter list is marked as blocked, why localhost should be an exception

**Comment by alexsannikov** [comment]
Omoeba, delete localhost from any filter file.
Everything in filter files will be blocked.
I personally cleanup the hosts files from different sources before use, removing all the "localhost" records and replacing 127.0.0.1  -> 0.0.0.0

**Comment by Omoeba** [comment]
localhost should be an exception because it is not blocked by defining the IP as 127.0.0.1 or ::1. The correct ip for localhost is 127.0.0.1 or ::1. For example, doubleclick.net is blocked by defining it as 127.0.0.1 when the IP is not.

**Comment by ameshkov** [comment]
Pointing a hostname to 127.0.0.1 does not necessarily mean blocking. It just means that the client app will try to connect to 127.0.0.1 and if there's no one listening, the connection will fail.

Also, a hosts file can redefine `localhost` and point it to some remote IP. So highlighting the fact that there's a line for it in the query log makes sense - you need to be aware of it.
