### ISSUE TITLE
AdGuardHome and ipFire 

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#774]
Can AdGuard Home scripts be added to ipFire URLFilter

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
| How did you setup DNS configuration:| (System/Router/IoT)
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1)

**Comment by ameshkov** [comment]
They use slightly different syntax so I guess no.
