### ISSUE TITLE
DNS kicked out

### ISSUE THREAD

**Issue by All4Gears** [AdguardTeam/AdGuardHome#777]
When AdGuardHome DNS is into the MAC it gets kicked out or erased or deleted when the MAC connects to VPN.  When connected to the VPN it connects then drops then connects until the Adguard DNS is kicked out.  How to keep safe Adguard DNS in the MAC? 

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0) .95 Hot
| How did you setup DNS configuration:| (System/Router/IoT) in the MAC
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B) GL inet Slate 750
| Operating system and version:| (e.g. Ubuntu 18.04.1)Mojave

**Comment by ameshkov** [comment]
Well, it seems your VPN overrides DNS settings. Maybe your VPN service provider allows using custom DNS, you should ask them.
