### ISSUE TITLE
Add a command-line flag for disabling built-in auto-update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#778]
See the reason here:
https://github.com/AdguardTeam/AdGuardHome/issues/428#issuecomment-495758858

In case if this flag is enabled, we should still indicate that the new version is available, but we shouldn't show the "Update" button.

1. [ ] Command-line flag
2. [ ] Use this flag in the Docker file
3. [ ] Add information about updating the Docker image to the "How to update" section on Wiki
4. [ ] Add information about updating the Hass.io add-on to the "How to update" section on Wiki

@frenck could you please help us with the step 4? What should we link there?

**Comment by szolin** [comment]
> Command-line flag
I have some doubts whether it's really necessary:
* Can't we detect at initialization that we're running under Docker?
* Why would user want to click on "Update Now" button, if he already knows that AGH under Docker can't be updated this way?
* Can't we use configuration setting instead?

**Comment by ameshkov** [comment]
Recording what we discussed in-private:

1. This flag is really necessary:)
2. It should completely disable update checks, not just disable the auto-update

**Comment by ameshkov** [comment]
I've just tried the image from the `edge` tag, and it tries to update anyway.

I suppose we should mention this flag on Wiki: https://github.com/AdguardTeam/Adguardhome/wiki/Configuration#command-line

Also, there's no information about Docker and Hass.io updates on the Wiki page (see the checklist in the issue). The only thing we should write there is that the auto-update is disabled for them.
