### ISSUE TITLE
Add support for DHCPv6

### ISSUE THREAD

**Issue by bbsec3** [AdguardTeam/AdGuardHome#779]
Can it support DHCPv6 RA+SLAAC

**Comment by ameshkov** [comment]
Not at the moment, but I marked this as a feature request. Let's see how many people vote for it.

**Comment by ibksturm** [comment]
Vote +1

**Comment by Omoeba** [comment]
vote +1

**Comment by snakwu** [comment]
vote+1

**Comment by rookietribe** [comment]
vote +1

**Comment by ameshkov** [comment]
Wow:)

**Comment by bbsec3** [comment]
is it support now?

**Comment by bbsec3** [comment]
is it support now?

**Comment by ameshkov** [comment]
No, it does not. This requires us changing the library we use for the DHCP support.

@szolin let's take a look at these:
https://github.com/insomniacslk/dhcp

These two use it under the hood:

* https://github.com/coredhcp/coredhcp
* https://github.com/rtr7/router7 -- 

There are some issues with compiling this for Windows, though.

**Comment by gorip96** [comment]
Vote +1

**Comment by szolin** [comment]
DHCPv6 server implementation was merged into master branch, but RA and SLAAC are not currently implemented.  I think it's better to open a separate issue for them.

**Comment by ameshkov** [comment]
RA+SLAAC --> https://github.com/AdguardTeam/AdGuardHome/issues/2076

This task is now merely about DHCPv6.
