### ISSUE TITLE
API to check if domain is blacklisted SHA256

### ISSUE THREAD

**Issue by happyhater** [AdguardTeam/AdGuardHome#782]
"...will check if domain is blacklisted by the browsing security web service. It will use privacy-friendly lookup API to perform the check: only a short prefix of the domain name SHA256 hash is sent to the server."

Can you share the example how you do that? cuz I did SHA256 for a domain and didn't work.
Thanks!

**Comment by ameshkov** [comment]
Hi! It should be a prefix of the SHA256 hash, not the full hash.

It's all here in the source code:
https://github.com/AdguardTeam/AdGuardHome/blob/master/dnsfilter/dnsfilter.go#L673
