### ISSUE TITLE
Don't block DNS, DHCP and WebUI loading with query log parsing

### ISSUE THREAD

**Issue by ilya-fedin** [AdguardTeam/AdGuardHome#784]
### Steps to reproduce
1. Buy Irbis A or other device with Alisa (or make a lot of requests)
2. If block telemtry (which in default lists so), it will generate ~100-200K requests in 24 hours
3. In 24 hours log will have size of ~96MB
4. Adguard will start very long (at least on HDD)

### Expected behavior
DNS, DHCP and WebUI start immediately, query log parsing in other thread

### Actual behavior
DNS, DHCP and WebUI waits query log parsing to be end, as result, some services may working incorrectly without DNS on start (and it happens)

### Your environment
Raspberry Pi 2 with Raspbian Stretch and HDD connected over USB as root

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95-hotfix
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| Raspberry Pi 2
| Operating system and version:| Raspbian Stretch

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/776#issuecomment-499468432

**Comment by szolin** [comment]
Query logs access is now dynamic - it doesn't interfere with startup.
