### ISSUE TITLE
API does not decode form parameters correctly

### ISSUE THREAD

**Issue by frenck** [AdguardTeam/AdGuardHome#785]
### Steps to reproduce

1. Open postman, make a `POST` request against `/control/filtering/remove_url`
2. Set `Content-Type` to `application/x-www-form-urlencoded`
3. Add `url` parameter with, e.g., `https://filters.adtidy.org/extension/chromium/filters/1.txt`
4. Send request.

### Expected behavior
The request to succeed, since it is according to specifications.

### Actual behavior
The request fails: `URL parameter is not valid request URL`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/195327/58723963-ae7cc600-83db-11e9-8cbc-9efd3e40eae4.png)

</details>

Raw request:
```txt
POST /control/filtering/remove_url HTTP/1.1
Host: 10.10.100.10:8585
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

url=https%3A%2F%2Ffilters.adtidy.org%2Fextension%2Fchromium%2Ffilters%2F1.txt
```

I've worked around it in my Python client library for now, by sending in compatible data in the request body: <https://github.com/frenck/python-adguardhome/blob/master/adguardhome/filtering.py#L58>

This works, because AdGuard Home does not check `Content-Type` headers in these cases (which is a secondary issue).

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.95-hotfix
| How did you setup DNS configuration:| Router (directly given out by DHCP)
| If it's a router or IoT, please write device model:|  EdgeRouter 4
| Operating system and version:| Alpine 3.9.4 (Hass.io Add-on v1.1.1)

**Comment by szolin** [comment]
We don't support URL-encoded values, so you need to set `url=` value without replacing special characters:
`url=https://filters.adtidy.org/windows/filters/15.txt`

Also, the description of `/add_url` in openapi isn't correct: now it uses json as input.
e.g.:
`{"name":"name","url":"https://filters.adtidy.org/windows/filters/15.txt"}`

**Comment by ameshkov** [comment]
@szolin well, the point is that we **should** support it.

**Comment by szolin** [comment]
1. I think it's better to change `/remove_url` input format to json.
2. fix `/add_url` openapi format

**Comment by ameshkov** [comment]
@szolin yep, I suppose this would also solve this issue.

Will we be able to include it in v0.96?
