### ISSUE TITLE
Error processing blocklist

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#786]
### Steps to reproduce

1. Load this block list https://dbl.oisd.nl/
2. this is blocked raw.githubusercontent.com

### Expected behavior

It should not block it because that domain is not in that list.

### Actual behavior

Allow

### Your environment

Running in docker latest version

**Comment by lunik1** [comment]
I had this same issue. It's because entries in a list are treated as regex and that list contains "ntent.com", which matches "raw.githubusercontent.com".

It would be nice to have better handling of lists in this format.

**Comment by ameshkov** [comment]
Guys, this issue will be resolved in v0.96 alongside #535.

I'll keep it open for now so that we don't forget to re-test it.
