### ISSUE TITLE
Upstreams servers local redirection

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#787]
### Steps to reproduce

1. I have configure upstreams DNS servers with this
[/abcd.duckdns.org/]192.168.1.220
when I resolver this abcd.duckdns.org it gives me an error page
It's a website hosted in my network I want local queries to redirect to the IP.

When I test the servers I get this error 
Server "[/abcd.duckdns.org/]192.168.1.220": could not be used, please check that you've written it correctly

192.168.1.220 it's a nginx server. with piholes wortks.

### Expected behavior
It should give me the website behind

### Actual behavior
when I resolver this abcd.duckdns.org it gives me an error page

### Your environment
Running docker latest version

**Comment by ameshkov** [comment]
@lordraiden 

Here's how it should look like:
`/abcd.duckdns.org/192.168.1.220`

Square brackets just indicate that this part of the server line is optional, you shouldn't include them

**Comment by lordraiden** [comment]
Now I get this error

Server "/abcd.duckdns.org/192.168.1.220:443": could not be used, please check that you've written it correctly

Error: control/set_upstreams_config | wrong upstreams specification: address /abcd.duckdns.org/192.168.1.220: missing port in address | 400

And if I put  /abcd.duckdns.org/192.168.1.220:443

Error: control/set_upstreams_config | wrong upstreams specification: /abcd.duckdns.org/192.168.1.220 is not a valid IP | 400

**Comment by admitrevskiy** [comment]
@lordraiden hi!
The right way to specify upstream per host is [/abcd.duckdns.org/]192.168.1.220

I think that you get an error because it's the only one upstream server which you specified. It means that you should specify any other upstream to resolve all queries except for abcd.duckdns.org

**Comment by lordraiden** [comment]
Sorry I feel stupid right now

This is my configuration, it doesn't matter if I use [] or not it doesnt work.
What I want is adguard home to resolve 192.168.1.220 when this domain is called abcd.duckdns.org. How can I do this?
@ameshkov @admitrevskiy 

> 1.1.1.1
9.9.9.9
/abcd.duckdns.org/192.168.1.220
tls://1dot1dot1dot1.cloudflare-dns.com
https://dns.cloudflare.com/dns-query

**Comment by admitrevskiy** [comment]
@lordraiden I don't understand what's going on, your configuration with `[]` looks correct :)

Let's clarify: your goal is to resolve `abcd.duckdns.org` with `192.168.1.220` upstream `or` you'd like to be redirected to `192.168.1.220` when try to resolve `abcd.duckdns.org`?

-If you try to reach the goal #1 - please, send me verbose logs (run AGHome with -v option)
-If you try to reach the goal #2 - upstream-per-domain specification is not the right place to do it

**Comment by lordraiden** [comment]
@admitrevskiy 
I'm trying nº2, how can I do it?

**Comment by admitrevskiy** [comment]
Try the following:

-Go to `Filters` -> `Custom filtering rules`
-Add this rule: `192.168.1.220 abcd.duckdns.org`

Please, let me know if something goes wrong.

**Comment by lordraiden** [comment]
@admitrevskiy  
It doesn't work, if I do a nslookup it says that the domain doesn't exits, in pihole can be done by editing the settings with this solution
https://discourse.pi-hole.net/t/howto-using-pi-hole-as-lan-dns-server/533

**Comment by ameshkov** [comment]
Could you please take a screenshot of what you have in the filtering log?
Works for me just okay:
https://uploads.adguard.com/up04_d9vz4_adguard-dns__-bash__14238.png

**Comment by lordraiden** [comment]
For some reason now it works. Thanks a lot for the patience. 
BTW nice update the 0.96, I hope this proyect will continue growing, better analytics would be awesome

**Comment by lordraiden** [comment]
@ameshkov 
One more thing, when I add the rule in the filter log appears as something blocked by the filter while actually is just a redirection, maybe you could change in the interface the way this is treated and change the color from red to blue or something

![imagen](https://user-images.githubusercontent.com/17175395/59145711-0624be00-89e8-11e9-8a3d-2bf23a1e08d6.png)

**Comment by ameshkov** [comment]
Yeah, this will be handled with #818
