### ISSUE TITLE
Business and features ideas

### ISSUE THREAD

**Issue by lordraiden** [AdguardTeam/AdGuardHome#794]
Take a look to this service
https://www.nextdns.io/
https://www.reddit.com/r/privacytoolsIO/comments/bt2o66/we_are_launching_nextdnsio_a_combination_of/
https://news.ycombinator.com/item?id=20012687
You could do the same, monetize the protect, make money and speed up the development

**Comment by ameshkov** [comment]
Yeah, I saw it. This is a very nice idea indeed, and we could use it for AdGuard DNS.

However, AdGuard Home is a little bit different product that is supposed to control your home devices. There can be several ways of expanding into a "cloud" service, and we have not yet decided which one to follow.
