### ISSUE TITLE
对安卓设备支持不够好,不能去除手机上的广告,还有我的安卓盒子,如果连上adg,wifi会提示已连接,无法访问网络!

### ISSUE THREAD

**Issue by snakwu** [AdguardTeam/AdGuardHome#797]
对安卓设备支持不够好,不能去除手机上的广告,还有我的安卓盒子,如果连上adg,wifi会提示已连接,无法访问网络!

**Comment by ameshkov** [comment]
Please use English, we don't speak Chinese.

From what I understand in the google-translated version, your configuration is wrong. But what exactly is wrong is quite hard to say. Try checking the query log, are there any requests there?

**Comment by snakwu** [comment]
Configuration, is in routing, forwarding DNS to adg, the log has a display request!

**Comment by ibksturm** [comment]
> Please use English, we don't speak Chinese.
> 
> From what I understand in the google-translated version, your configuration is wrong. But what exactly is wrong is quite hard to say. Try checking the query log, are there any requests there?

or russia ;)
