### ISSUE TITLE
Auto-update: remove backup directory after successful update

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#801]
Currently we create a backup directory e.g. `agh-backup-v0.96...`.
We need to remove it after update has succeeded.

**Comment by szolin** [comment]
I've just thought about it once again and I don't think we should automatically do it.
The whole point of backups is that user can revert AGH to the same state it was before upgrading.
Should we break something in the new version, even after a successful start - user can go back, reset to the working state.

**Comment by ameshkov** [comment]
We should at least remove all save for the last.
