### ISSUE TITLE
Expand table to row amount

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardHome#803]
When extra rows are selected it would be nice to have the option for the page to be auto-expanded to the set row limit.

E.g.
1. Set rows to 20
2. Table and container auto-expands to 20 rows

Currently
1. Set rows to 20
2. Row amount increases to 20 and container amount stays at 5

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/845

**Comment by ArchiveBase** [comment]
@jslawler it seems not a issue further on v0.98.1
