### ISSUE TITLE
Long sub-domain queries unable copy through web interface 

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#814]
Short domains, sub-domains queries able copy within web-interface by highlight query text and right-click then copy as we copy any web page contents

### Steps to reproduce
1. You need to have any longer sub-domain query on AGH ;)
2. Just able view it when bring cursor near it but no way for copy it 
_(hard way, download log file and find where is it)_

-----------

### Expected behavior

If has copy clipboard way for each query then that solves as better way. so It can be ex:

a) 
![image](https://user-images.githubusercontent.com/46082456/59085599-5557e980-8929-11e9-8411-1e32ade3dc28.png)
(copy clipboard button next to each query)

Or

b) 
![image](https://user-images.githubusercontent.com/46082456/59086565-50486980-892c-11e9-8bd6-3b93044a26d0.png)

(expand option to copy)

------

### Actual behavior
![Screenshot_1](https://user-images.githubusercontent.com/46082456/59085723-c4354280-8929-11e9-90d4-8e2287dbb72c.png)
(not possible copy within web-interface even zoom out page through browser)

------

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (v0.96)
| How did you setup DNS configuration:| (System/Router/IoT)
| Operating system and version:| (Windows 10 1809)

**Comment by ameshkov** [comment]
You can resize the column.

But yeah, this is inconvenient indeed.

**Comment by ArchiveBase** [comment]
Thanks^^ i didn't know if possible resize column but such copy clipboard option save time (one-click) without extra task to copy each query ;)
