### ISSUE TITLE
Add an option to check for updates forcibly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#815]
Currently, we cache the `version.json` contents for 8 hours. There should be a way to reload the file contents forcibly.

Here's how to do it in the UI:
1. Add a "Refresh icon" next to the version: https://uploads.adguard.com/up04_r0rdb_AdGuard_Home.png (also change "version" to "Version")
2. Click on this icon should trigger the update check.
3. If a new version is found, show the regular "new version found" topline.
4. If nothing found, show notification: "AdGuard Home is up-to-date.

**Comment by ArchiveBase** [comment]
**Let's do some enhancement**

- ☐ **Check program updates automatically** (enabled by default)
 (or ☐ **Check for program updates every 8 hours/days**) 
[already adguardhome v0.96 check updates and notify user]

- ☐ **Automatically download program updates**
 _(if checked, program updates will be automatically downloaded. You will still need to choose when to install them)_

- ☐ **Automatically install program updates**
 (or ☐ **Automatically install program updates in critical situations**)

_If user disabled that all then AdGuardHome shouldn't make any request and Third option fulfill # 813 feature request._

**Comment by Eyeborgs** [comment]
@ArchiveBase 
This is what I want
