### ISSUE TITLE
Systemd service file for CentOS/Fedora

### ISSUE THREAD

**Issue by carlbennett** [AdguardTeam/AdGuardHome#816]
I've been using this service file with Systemd on Fedora since I started using this project earlier this year. It's always worked for me. I left the commented Exec lines because that's how it's documented to behave as a service, but I found them not necessary.

```
[Unit]
Description=AdGuard Home
Documentation=https://github.com/AdguardTeam/AdGuardHome
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/AdGuardHome
ExecStart=/opt/AdGuardHome/AdGuardHome
#KillSignal=SIGINT
#ExecStart=/opt/AdGuardHome/AdGuardHome -s start
#ExecRestart=/opt/AdGuardHome/AdGuardHome -s restart
#ExecStop=/opt/AdGuardHome/AdGuardHome -s stop
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by ameshkov** [comment]
Thank you!

Merging into https://github.com/AdguardTeam/AdGuardHome/issues/765
