### ISSUE TITLE
[Feature Request] Add filters and hosts blocklists from local hard disk

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#817]
- This feature shouldn't affect to low-end devices disk or ram
- Detect blocklists changes automatically

**Comment by anindyamaiti** [comment]
You can have a web server running on 127.0.0.1 and serving those lists. Then 'add filter' like you would do for any other online list and use the localhost address in the URL field. Have different files for categorization.

**Comment by ArchiveBase** [comment]
@anindyamaiti Never. Why more complex? (If so i already not open this feature request)

**Comment by anindyamaiti** [comment]
I was just giving an alternate solution that will work right now, because I didn't see any response from the devs yet.

Also, setting up a web server is not as complex as you make it sound. It takes couple of package installations and less than 5 minutes of time. I recommend trying out [`lighttpd`](https://www.lighttpd.net/) if you have resource constraints:

`sudo apt-get update`
`sudo apt-get install lighttpd`

**Comment by ArchiveBase** [comment]
@anindyamaiti Thank you for suggestion^^ Yes you're right. It will helpful for everyone looking this facility urgent.

 "because I didn't see any response from the devs yet." 
      - It's already marked as feature request then response no necessary ;) however no milestone yet, likely we have to wait long time.

**Comment by ameshkov** [comment]
> however no milestone yet, likely we have to wait long time.

As of usual, it depends on the number of upvotes:)

**Comment by ArchiveBase** [comment]
Page marketing appreciated 😉

**Comment by ArchiveBase** [comment]
I thought to explain bit how this feature necessary to implement because recently some opened issues took my attention about people who run AGHome on servers dislike access to instance often normally web interface always perfect for every type of users.

**Create local filter**
![Screenshot_5](https://user-images.githubusercontent.com/46082456/65451737-fda6a500-de69-11e9-92dd-0b9d62747666.png)

_(Tags help assign specific filters to a client or multiple clients easily. See https://github.com/AdguardTeam/AdGuardHome/issues/435 It has advantage than use filter name because we can set several tags to each filter or use same tag name to multiple filters)
(Global filter is an option to apply specific filter for all connected devices without keep as inactive except used by 'Client')_

**Maintain a local filter (add or remove rules)**

Actions > Update
_(Update:: the same button(icon) can be also use for update each cloud filter manually. See https://github.com/AdguardTeam/AdGuardHome/issues/820 so if it a remote filter then check for update otherwise appear window for local filter)_

We can let to maintain each local filter in pop up window. ex: 500x500 size suitable for average screen however keep in mind to auto resize depend on window/screen size include mobile devices.
![Screenshot_8](https://user-images.githubusercontent.com/46082456/65457210-41eb7280-de75-11e9-90c8-48ceb8b1685c.png)

_(Search component helps user to find specific rule quickly without scroll huge list and reduce mistakenly add duplicate)_

**Comment by ArchiveBase** [comment]
- [ ] **Detect invalid rules.**
 
![65457210-41eb7280-de75-11e9-90c8-48ceb8b1685c](https://user-images.githubusercontent.com/46082456/67691661-8c5e9280-f9d1-11e9-9966-98242f5b5455.png)
_(Do not allow user to save filter with invalid rules and notify for re-correct them)_

- [ ] **Detect duplicate rules.**
even this requested feature https://github.com/AdguardTeam/AdGuardHome/issues/856 for detect existing rules however insufficient to fulfill this requirement
 
![65457210-41eb7280-de75-11e9-90c8-48ceb8b1685c (1)](https://user-images.githubusercontent.com/46082456/67695132-2aa12700-f9d7-11e9-95a6-7171483bf4b8.png)

**Comment by ArchiveBase** [comment]
- [ ] **Toolbox**

![65457210-41eb7280-de75-11e9-90c8-48ceb8b1685c](https://user-images.githubusercontent.com/46082456/69690452-70e4c580-10fe-11ea-841b-c220a8989020.png)

- [1] Just add a rule then only necessary to type the domain.
- [2] It means apply a rule for bulk at once
- [3] Find duplicate rules within that local list
- [4] Find duplicate rules from all added filter lists.
- [5] When we copy rules list from somewhere then auto arrange feature must identify  Domains, IPs separately also necessary to remove invalid rules belong to those and rest of words or numbers must list as comments
- Last feature helps to remove everything may not valid as Domain or IP

**Comment by ameshkov** [comment]
@ArchiveBase most of the comments should be separate feature requests.

Regarding adding lists from local hard disk, we'll do this in v0.102:
1. Change text on the "New blocklist/whitelist" dialogs: "Enter URL or path to the blocklist"
2. Please note that you will still need to click "Check for updates" when you change the local list

**Comment by ArchiveBase** [comment]
> most of the comments should be separate feature requests.

Which comments?
(Sorry, summarized them bit. i thought this feature may implement after many years)

> 2. Please note that you will still need to click "Check for updates" when you change the local list

It's something like kill two birds with one stone 😊 (i mean instead 'edit' button)

**Comment by ArchiveBase** [comment]
> 1. Change text on the "New blocklist/whitelist" dialogs: "Enter URL or path to the blocklist"
I think it's possible to use default filters folder too without custom paths(?)

**Comment by ameshkov** [comment]
> Which comments?
> (Sorry, summarized them bit. i thought this feature may implement after many years)

Well, the ones about creating a custom filter and about the filter editor that's built-in.

The original feature request sounds a little bit easier than this:)

> I think it's possible to use default filters folder too without custom paths(?)

I don't think so. This folder is a part of the internal AGH configuration and it shouldn't be touched. What if at some point we will move filter lists to DB?

**Comment by ArchiveBase** [comment]
> I don't think so. This folder is a part of the internal AGH configuration and it shouldn't be touched. What if at some point we will move filter lists to DB?

I prefer force most features configurable, customizable and maintain within web interface because user friendly(easier) and development tasks may not drive on two paths or complex when someday offer adguardhome in the cloud ;)

**Comment by ArchiveBase** [comment]
> I don't think so. This folder is a part of the internal AGH configuration and it shouldn't be touched. What if at some point we will move filter lists to DB?

I prefer force most features configurable, customizable and maintain within web interface because user friendly(easier) and development tasks may not drive on two paths or complex when someday offer adguardhome in the cloud ;)

Something like that (not NextDNS)
https://cdome.comodo.com/dome-shield
https://www.comodo.com/cdomeshield/freelicense/index.php

> What if at some point we will move filter lists to DB?

Any preferred method 😊

**Comment by HopHop20** [comment]
Looking forward to this feature :)

**Comment by szolin** [comment]
@ArtemBaskal 

1.
> Change text on the "New blocklist/whitelist" dialogs: "Enter URL or path to the blocklist"

2. UI validation:
Absolute file path on UNIX: the path starts with /
Absolute file path on Windows: the path starts with / or \ or [a-zA-Z]:/ or [a-zA-Z]:\
