### ISSUE TITLE
Support Whitelist Lists

### ISSUE THREAD

**Issue by alexzeitgeist** [AdguardTeam/AdGuardHome#822]
Suggestion. Currently it is only possible to whitelist domains using the 'Custom filtering rules'  form. It would be nice if we could add whitelist lists that are dynamically updated just as blacklist lists. For reference see the lists here:

https://github.com/anudeepND/whitelist
https://github.com/anudeepND/whitelist/tree/master/domains

**Comment by ameshkov** [comment]
AGH supports common adblock syntax where you can whitelist URLs with rules like `@@||example.org^`. Transforming the anudeepND's whitelist would be fairly easy.

**Comment by planet0** [comment]
I would really like this feature, as although I have manually added the domains to the custom area, now I need to constantly check my sources for any updates or changes made in case more are discovered or domains change (Microsoft & Facebook does that a lot).

Since those lists are in a format just like the blocking ones, I would love to be able to have it automated.

**Comment by magnu5** [comment]
I made a script to parse those whitelists, and added a few of my own lists, the parsing is easy,it's just a sed command:
`sed -i 's/^/@@||/' whitelist.txt`

[https://raw.githubusercontent.com/magnu5/whitelist-1/master/domains/AdguardHome](https://raw.githubusercontent.com/magnu5/whitelist-1/master/domains/AdguardHome)

**Comment by NetE1** [comment]
@ameshkov Is there way for block all dns requests by one rule? ex: ||^/||all^ so i can allow domains only included on custom whitelist. that's usable when implemented https://github.com/AdguardTeam/AdGuardHome/issues/435

**Comment by planet0** [comment]
@NetE1 I wonder if you could use this regex at the top of the Custom filtering rules: 
`/.+/`

Explanation: https://regex101.com/r/DVU7nM/1

**Comment by NetE1** [comment]
@planet0 Thank you^^ I'll check it and let's see what will @ameshkov say although i still have to wait for https://github.com/AdguardTeam/AdGuardHome/issues/435 because 'custom filtering rules' apply for all connected devices

**Comment by ameshkov** [comment]
Yeah, what @planet0 proposed is a solution.

**Comment by NetE1** [comment]
Thanks for both.

**Comment by ameshkov** [comment]
We'll need to change UI for this task:

First of all, split "Filters" into three pages:

* `DNS blocklists`
* `DNS whitelists`
* `Custom rules`
