### ISSUE TITLE
Sudo ./AdGuardHome -s install can't be installed on OpenWrt

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#824]
Openwrt system
VMware, Inc. VMware Virtual Platform
Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz

I am installing adg home prompt error in openwrt

```
2019/06/09 23:36:40 [info] Action uninstall has been done successfully on unix-systemv
root@Openwrt:~/AdGuardHome# ./AdGuardHome -s install
2019/06/09 23:36:49 [info] Service control action: install
2019/06/09 23:36:49 [info] Action install has been done successfully on unix-systemv
2019/06/09 23:36:49 [fatal] Failed to start the service: Failed to start AdGuard Home service: "service" failed: exec: "service": executable file not found in $PATH
root@Openwrt:~/AdGuardHome# 
```

**Comment by thb007** [comment]
Firmware Version Openwrt Koolshare mod V2.31 r10822-50aa0525d1 / LuCI Master (f138fc93)
Kernel version 4.14.115

**Comment by ameshkov** [comment]
> "service": executable file not found

https://forum.openwrt.org/t/service-not-found-error/14384/6

**Comment by thb007** [comment]
> > “service”：找不到可执行文件
> 
> https://forum.openwrt.org/t/service-not-found-error/14384/6

Sorry, I don't understand what it means. Can you explain it?

**Comment by ameshkov** [comment]
It might be that there's a problem with your openwrt configuration, read the relevant thread that I linked.

Also, I am not sure that this is it, maybe some other user with openwrt can come and comment on the issue.

**Comment by thb007** [comment]
> 可能是您的openwrt配置存在问题，请阅读我链接的相关主题。
> 
> 此外，我不确定是不是这样，也许其他一些openwrt用户可以来评论这个问题。

hmm I went to the openwrt forum for help.

**Comment by wzhich** [comment]
Hello, if this question have some solution?
I'm use openwrt base on arm of inux OpenWrt 4.14.94 #0 SMP Wed Jan 23 01:52:05 2019 armv7l GNU/Linux.
I have download AdGuardHome_linux_arm.tar.gz, and unzip to my local fold.
but it cant run correct, when I try to run ./AdGuardHome -s install, it will alert: "Illegal instruction".
Hopeful ur reply, thank u.

**Comment by thb007** [comment]
This is the latest ipk file that can be run on the X86-64 platform.

[AdGuardHome_v0.96-hotfix_x86_64.zip](https://github.com/AdguardTeam/AdGuardHome/files/3373261/AdGuardHome_v0.96-hotfix_x86_64.zip)

**Comment by hjchjchjc4352** [comment]
> 
> 
> This is the latest ipk file that can be run on the X86-64 platform.
> 
> [AdGuardHome_v0.96-hotfix_x86_64.zip](https://github.com/AdguardTeam/AdGuardHome/files/3373261/AdGuardHome_v0.96-hotfix_x86_64.zip)



> 
> 
> This is the latest ipk file that can be run on the X86-64 platform.
> 
> [AdGuardHome_v0.96-hotfix_x86_64.zip](https://github.com/AdguardTeam/AdGuardHome/files/3373261/AdGuardHome_v0.96-hotfix_x86_64.zip)

兄弟，openwrt怎么安装。。。我安装了你上传的ipk无法启动服务

**Comment by szolin** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1348
