### ISSUE TITLE
[Feature request]  exclude some process with its command line

### ISSUE THREAD

**Issue by hesss5** [AdguardTeam/AdGuardHome#828]
i want AH able to exclude some process from filtering
so don't need to disable and enable it again
thank you

### Expected behavior
want it don't filter anything for process running with this command(another Firefox profile) and with default dns
"C:\Program Files\Mozilla Firefox\firefox.exe" -no-remote -P "unfiltredfirefox"
and with single process no command work too
"C:\Program Files\Mozilla Firefox\firefox.exe

### Actual behavior
currently filter all process

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (v0.96)
| How did you setup DNS configuration:| (System)
| Operating system and version:| (windows 8.1)

**Comment by ameshkov** [comment]
Well, AGH works on a different level, it is not aware of what process connects to it.

You could configure your Firefox to use a different DNS resolver instead.
