### ISSUE TITLE
Allow DNS to work across subnets

### ISSUE THREAD

**Issue by jhorn1992** [AdguardTeam/AdGuardHome#829]
Feature Request

Allow AdGuardHome to reply to dns queries from a different address than an address on the subnet that the AdGuardHome Server is on. Allow customizing this option from the web interface, choose which addresses/subnets to allow AdGuardHome to reply to.

**Comment by ameshkov** [comment]
Do you mean that you want AGH to listen to multiple IP addresses at once?

**Comment by jhorn1992** [comment]
I want AdGuardHome to accept DNS queries from any private IP address, so I can have the AdGuardHome on my Server subnet and have it accept queries from my Home subnet and my IoT Subnet.

**Comment by ameshkov** [comment]
In theory, you can configure it to listen to 0.0.0.0 and then use Access settings to limit the subnets it accepts DNS queries from: https://uploads.adguard.com/up04_x7u8m_AdGuard_Home.png

**Comment by Yuan573** [comment]
Maybe like this?
![AdGuardHome_Dashborad](https://i.imgur.com/SxxCvFP.png)
