### ISSUE TITLE
Panic problem with AdGuardHome

### ISSUE THREAD

**Issue by Threefish4096** [AdguardTeam/AdGuardHome#834]
### Steps to reproduce

1. Start AdGuardHome from crontab at the boot after a sleep of 30 seconds
2.Wait 1 or 2 minutes

### Expected behavior
It start and stay in background

### Actual behavior
Stop after 2 minutes

<details><summary>Screenshot:</summary>

![immagine](https://user-images.githubusercontent.com/43168947/59496764-702ede80-8e92-11e9-93e3-2c7826535f67.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.96
| How did you setup DNS configuration:| Only Router can contact the system for DNS query
| If it's a router or IoT, please write device model:| BananaPi R2
| Operating system and version:| Linux bpi-iot-ros-ai 4.14.122-bpi-r2-main #1 SMP Mon May 27 17:16:26 UTC 2019 armv7l GNU/Linux

**Comment by szolin** [comment]
Can you enable verbose logging?  (Set `verbose: true` in yaml config file.)

I think it crashes because there is a nil `dns.RR` object inside `Extra[]` array.  Without logs I don't see which code could make such request. 
```
func (dns *Msg) IsEdns0() *OPT {
...
	for i := len(dns.Extra) - 1; i >= 0; i-- {
>>>		if dns.Extra[i].Header().Rrtype == TypeOPT {
```
