### ISSUE TITLE
Allow wildcard domains under 'Allowed Clients'

### ISSUE THREAD

**Issue by keithah** [AdguardTeam/AdGuardHome#835]
I have a backup DNS running in the cloud and would like to restrict it, but I don't know the potential range of my ISP in case my IP changes, so I would like to restrict to any IP's that are from a certain domain to let through.

**Comment by ameshkov** [comment]
Wouldn't it be easier to list your ISP ranges?

Whois your IP address, find what "org" it belongs to, then query RIPE database to find all subnets that belong to it.

**Comment by keithah** [comment]
ISP's like comcast have 30 million+ users, and I'm unaware of a way to know which ranges belong to which area, so it'd be hard to limit it that way.

**Comment by ameshkov** [comment]
Got it, could you please explain more about this domain idea? Would it somehow point to a dynamic IP?

**Comment by keithah** [comment]
basically, instead of having to find every *.comcast.net subnet, be able to allow *.comcast.net.

The other idea is to be able to use 'blah.dyndns.org' as a host, instead of an IP, which will resolve to the allowed IP.

**Comment by ameshkov** [comment]
Yep, I got the idea. 

The problem is that this won't be easy to implement as reverse DNS queries are asynchronous in the current implementation, but let's see how popular this feature request will become.

**Comment by BlohoJo** [comment]
I need exactly this feature. I have a remote computer I want to use my Adguard Home, but it has a dynamic IP. I set up a dynamic DNS for it and it works well. It would be nice if you could enter the DNS into "allowed clients" then Adguard would use the upstream or bootstrap DNS to resolve it and then use the resulting IP.

I would actually prefer to do it via Windows Firewall, but that only allows IP addresses or ranges. It seems like a script should be possible to resolve the dynamic DNS, then update the resulting IP as a firewall rule. But I don't have the skill to write one! :\

**Comment by Termi79** [comment]
Voting for this feature!

Why do this? It would be possible to use an own external server on lines with dynamic IP adresses without have DNS services for everybody. Just use a DDNS service and add the hostname in AdGuard Home

**Comment by szolin** [comment]
AGH v0.103 allows to set Allowed clients in `IP/CIDR` format

**Comment by MilorES** [comment]
Will this be implemented?
It would be nice to limit the requests per host.
For instance:
test.duckdns.org
casa.freedns.org
host.domain.ee 

Each X could check the IP of those domains and put in the allowed or a special list.

**Comment by jaalcorta** [comment]
I setup AdGuard Home in a cloud server and every time my IP changes at home (which is often) all my devices lose DNS resolution and I have to login to the Adguard web interface to update my IP in the Allowed Clients section under the DNS Settings.

I noticed that NextDNS has this feature already implemented. When you setup your account there's an option that says:
You can use Dynamic DNS (DDNS) to have your linked IP updated automatically.
