### ISSUE TITLE
Unable to update adguard

### ISSUE THREAD

**Issue by skalra631** [AdguardTeam/AdGuardHome#836]
Running adguard home on raspbian.

I had 0.92 hotfix 2. There is a messae saying that there is an update available (0.96) but i cant see a way to update it.

I even removed the service, the AdGuardHome folder and downloaded 0.96, ran tjhrough installation but its still showing as 0.92 with an update available and the filers are still there.

I thought the filters are stored in AdGuardHome/Data so how are they still in the webui after i have deleted the folder

**Comment by ameshkov** [comment]
The only way to update AGH from v0.92 is to download the newer version, replace the binary, and run it. Make sure that you've replaced the binary.
