### ISSUE TITLE
Error while making an rDNS lookup for 127.0.0.1: read udp 127.0.0.1:63996->127.0.0.1:53: i/o timeout

### ISSUE THREAD

**Issue by GreatDick** [AdguardTeam/AdGuardHome#838]
Error while making an rDNS lookup for 127.0.0.1: read udp 127.0.0.1:63996->127.0.0.1:53: i/o timeout

**Comment by hesss5** [comment]
i get this error to sometimes seems same?
Error while making an rDNS lookup for 148.161.1.2: read udp 127.0.0.1:55016->127.0.0.1:53: i/o timeout

**Comment by szolin** [comment]
This probably happens while the server is reconfiguring so it can't respond to DNS requests.
I think we just shouldn't print an error message in this case.

**Comment by hesss5** [comment]
148.161.1.2 is one of dns address that app provide
also i got some error like this later rerun the app

2019/08/07 15:52:12 [info] error while responding to a DNS request: write udp [::]:53->127.0.0.1:61717: use of closed network connection
2019/08/07 15:52:18 [info] error while responding to a DNS request: write udp [::]:53->48.131.1.2:62688: use of closed network connection

**Comment by hesss5** [comment]
also seems  when such error happen when i go "query log" in 127.0.0.1/#logs
it just log "blocked by filter url" so wont show any other url

**Comment by hesss5** [comment]
hello please update beta build i used instruction to build it build the app when i try access setting 
its say "404 page not found" 
here some log from build i makes :)

https://gist.github.com/hesss5/60507f8b262a10a2f8e0645c508d0111
