### ISSUE TITLE
Strange client request of DNS

### ISSUE THREAD

**Issue by GOODTESTA** [AdguardTeam/AdGuardHome#839]
I've using Adguard home from the begining till now, but there are some strange request of DNS lookup from my query...

Strange client like：
eml-srv.info (185.222.211.12)
hosting-by.directwebhost.org (45.227.253.242)
customer.worldstream.nl (91.229.23.68)
141.98.80.54
customer.worldstream.nl (62.112.9.43)
swim.diverseenvironment.com (185.211.245.198)

Which lots of query request I don'n know who are them, I'm not sure these query will make my computer slow, or make my computer like a middle server to attach other website.
Can I block these user I don't know? Thank you.

![image](https://user-images.githubusercontent.com/35817374/59687089-546b6580-920f-11e9-93e2-8b253d45e450.png)
![image](https://user-images.githubusercontent.com/35817374/59688053-94324d00-920f-11e9-992f-37e734bf1420.png)

**Comment by ameshkov** [comment]
Well, you know what, this is weird. I see the same requests in my VPS-hosted AGH.

**Comment by ameshkov** [comment]
On the other hand, it might be someone trying DNS amplification attacks and scanning all public DNS servers.

**Comment by szolin** [comment]
You should block unwanted clients via Access configuration settings.
If a DNS server can be accessed from the Internet - it's normal if someone else starts using it.

**Comment by ameshkov** [comment]
I can't see anything like this on our side, this is DNS amplification after all.
