### ISSUE TITLE
When open the non-https website,it pop up "Your connection to this website is not private" and always let me enter username and password.

### ISSUE THREAD

**Issue by GreatDick** [AdguardTeam/AdGuardHome#841]
When open the non-https website,it pop up "Your connection to this website is not private" and always let me enter username and password.

**Comment by GreatDick** [comment]
like"jiandan.net"

**Comment by ArchiveBase** [comment]
Does it appear(username and password) only when use AdGuardHome? have you tried set and use adguard-dns or google-dns directly on your PC without AGH?

**Comment by ameshkov** [comment]
I don't fully understand what is the question and what AGH has to do with this
