### ISSUE TITLE
[Feature Request] Specific upstream server for client rDNS

### ISSUE THREAD

**Issue by Termi79** [AdguardTeam/AdGuardHome#842]
Please add the possibility to add a specific upstream server for a specific (local) IP range for client rDNS, for example on 192.168.0.1/24 use 192.168.0.1 as rDNS server.

**Comment by aredan** [comment]
I'm running 0.97.1 and can do this using:
[/22.172.in-addr.arpa/]10.10.10.1 on **Upstream DNS servers**

All requests to resolve 172.22.0.1 are forwarded to 10.10.10.1.
Was this option added already?
Or this is for some easier UI for this kind of configurations?

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/962

**Comment by szolin** [comment]
wiki will be updated

**Comment by anoma** [comment]
Was the wiki updated as it is unclear if this feature is currently available?

**Comment by szolin** [comment]
Not yet.  Waiting for git push to github.  Most likely it will be done along v0.99.3 release.

**Comment by anoma** [comment]
My apologies I completely did not notice the date of the wiki comment. I was working from the original ticket June date.
