### ISSUE TITLE
[Feature Request] Add more information about the client’s connection to the AdGuard Home

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#844]
Я думаю эта было бы полезно если бы AdGuard Home мог бы определять через какой протокол к нему идет соединения от клиента 
Пример я на картинке сделал 

![DNS-connect](https://user-images.githubusercontent.com/46345396/59896735-5a6d6c00-93f2-11e9-9cfd-12d01e537f07.PNG)

**Comment by szolin** [comment]
There's a "Protocol" field in query log for each entry shown while hovering on "Request details" icon.
