### ISSUE TITLE
Cannot see queries on mobile devices

### ISSUE THREAD

**Issue by HappyGuy22** [AdguardTeam/AdGuardHome#846]
### Steps to reproduce

1. Open Adguard home dashboard
2. Go to logs

### Expected behavior
Logs should be clearly displayed on mobile devices.

### Actual behavior
Logs doesn't display correctly on smaller displays.

Screenshot: [Screenshot_20190623-170605_Chrome](https://user-images.githubusercontent.com/29010784/59975865-d6c2a380-95da-11e9-88a9-278e700800c0.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| 0.96-hotfix
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| Raspberry pi 3b+
| Operating system and version:| Raspbian Stretch

**Comment by davidbdeath** [comment]
I also find this frustrating. The mobile UX is horrible. Simple things like the menu not retracting after selecting an item.

**Comment by ArchiveBase** [comment]
Same https://github.com/AdguardTeam/AdGuardHome/issues/978

**Comment by ameshkov** [comment]
Fixed
