### ISSUE TITLE
Parental filter service timing out

### ISSUE THREAD

**Issue by prologic** [AdguardTeam/AdGuardHome#849]
Looks like the Parental Filter service is experiencing problems right now:

```
adguard_adguardhome.1.88i7skgu5lkk@dm1.mydomain.io    | 2019/06/24 11:44:38 [info] Failed to do parental HTTP lookup, ignoring check: Get https://pctrl.adguard.com/check-parental-control-hash?prefixes=FCA58A48/DA0CAE9C/3938902C/3B2DDC6F/71B4F3A3/&sensitivity=3: dial tcp 104.20.30.130:443: connect: connection timed out
adguard_adguardhome.1.88i7skgu5lkk@dm1.mydomain.io    | 2019/06/24 11:44:38 [info] Failed to do parental HTTP lookup, ignoring check: Get https://pctrl.adguard.com/check-parental-control-hash?prefixes=7D02E639/3EEE0FBD/2265CBCC/&sensitivity=3: dial tcp 104.20.30.130:443: connect: connection timed out
adguard_adguardhome.1.88i7skgu5lkk@dm1.mydomain.io    | 2019/06/24 11:44:38 [info] error while responding to a DNS request: write udp [::]:53->10.0.0.193:53681: use of closed network connection
```

I've had to disable this feature as it was also causing DNS queries to take longer and potentially fail entirely.

**Comment by ameshkov** [comment]
Could it be due to yesterday's outage?
https://blog.cloudflare.com/how-verizon-and-a-bgp-optimizer-knocked-large-parts-of-the-internet-offline-today/

**Comment by prologic** [comment]
if anyone could confirm this and also confirm the service's availability we can close this and I can re-enable the configuration.

Perhaps a "status page" on the adguard home page would also be useful so I don't have to report issues like this next time :D

**Comment by ameshkov** [comment]
It works okay right now so I guess we can close this indeed:)
