### ISSUE TITLE
Full stop in Filter Name breaks AdGuard

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#850]
I noticed when naming one filter with a period/full stop inside it, it caused AdGuard Home to hang/freeze. Once I edited the yaml file to remove it and restarted AGH, all worked again.

### Steps to reproduce

1. Add filter list (I added https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts)
2. Name it 'add.Spam' and click Add
3. Allow filter to save

### Expected behavior

Can continue to use Web Interface

### Actual behavior

Connection is Refused, broken.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.96-hotfix
| How did you setup DNS configuration:| ISP Modem, Pi
| If it's a router or IoT, please write device model:| Raspberry Pi 3 Model B+
| Operating system and version:| Up-to-date Raspbian Lite

**Comment by szolin** [comment]
Can't reproduce.  I've just tested v0.96-hotfix and UI works fine after adding this filter.
Can you show application logs?  If you have "Connection is Refused" error, then I think AGH just crashes.

**Comment by planet0** [comment]
@szolin I don't think this occurs anymore, so I'm happy to close this issue. It may have been an unrelated event which was coincidentally when I was adding filters.
