### ISSUE TITLE
DHCP client list empty

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#852]
I’m using AdGuard Home with my Modem/Gateway supplied by my ISP which took a very long time to play nice with each other, but I’m now noticing that my client list for DHCP is completely empty, even though the DHCP server is working as expected. (Only one DHCP server active [AGH’s one], and DNS queries coming through)

During testing/setting up I was seeing my one computer on the list, but since adding the rest of my devices to the network and increasing the lease time, I’m not seeing any clients now.

**Comment by szolin** [comment]
I found this issue recently: https://github.com/AdguardTeam/AdGuardHome/issues/799
`leases.db` file was not written as expected on app stop.
Also, we should write to this file each time we make a change in Leases table, and not just on app stop.

**Comment by planet0** [comment]
Ah, that might make sense then, I was having a few issues with it crashing or freezing and also manually stopping and rebooting during adding new Filter lists.

Any recommended temp workaround or quick fix to get the clients visible for now?

**Comment by szolin** [comment]
> Any recommended temp workaround or quick fix to get the clients visible for now?
Clients should re-appear in UI listing after they make another request for IP address.  Probably after a day (lease timeout).

**Comment by planet0** [comment]
Thank you, I did set it back to 24 hours. 🙌
