### ISSUE TITLE
DHCP static leases - Hostname?

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#854]
Might be a silly question, but when setting DHCP static leases, does the hostname need to match the existing Hostname shown in the 'DHCP leases' section?

During setup and testing for setting a static lease for a device, I had a different entry for the hostname (but the same MAC and IP) and it seems that it didn't work.

**Comment by ibksturm** [comment]
here too

**Comment by planet0** [comment]
Seems to be resolved, working fine now.
