### ISSUE TITLE
Test/Check domain against Filter rules

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#856]
It would be a neat idea to have a user-friendly option for them to test their filter setup, similar to how you are able to check for DHCP, or Test Upstream DNS Servers.

The user could type a particular URL or Domain into a text field and click 'Check' for AdGuard Home to tell them if AdGuard Home is currently blocking it, unblocking it, or passing through.

eg. user types google.com, or pastes a long URL from google.com into text field, clicks 'Check' button
- Output if blocked: red notification: "_**google.com** is currently blocked in your filters._"
- Output if no entry in filter: grey notification: "_**google.com** does not exist in any filter._"
- Output if unblocked: green notification: "_**google.com** is currently unblocked in your filters._"

**Comment by Yuan573** [comment]
We can use a block page like AdGuard DNS, redirect blocked domain to `176.103.130.133`.
If AdGuard Home server uses port 80/443, maybe can try to redirect to AdGuard Home and display related information.

**Comment by ArchiveBase** [comment]
Same request here to implement within v0.101 https://github.com/AdguardTeam/AdGuardHome/issues/1003 and +1 vote for @planet0 UI suggestion
