### ISSUE TITLE
A Question Regarding the Product Displayed on AdGuard.com

### ISSUE THREAD

**Issue by mozdevcontrib** [AdguardTeam/AdGuardHome#857]
How much is it; how do I purchase it? I see no info on AdGuard.com. Thank-you!

**Comment by ameshkov** [comment]
Hm, but the purchase button is right in the main menu on the website?

There are different products -- some of them are paid, and some are free.
Also, contributors and filter lists maintainers do not have to pay anything: https://adguard.com/en/rewards.html

**Comment by mozdevcontrib** [comment]
AdGuard Home, specifically?
I’ll take another look. :)

**Comment by ameshkov** [comment]
Well, AGH is free anyways, the only paid products are AG for Win/Mac/Android/IOS
