### ISSUE TITLE
Compatibility with Raspbian Buster

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#859]
Raspbian released Buster lately: https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/

<s>I just upgraded</s> on my Pi 3 B+ ... Is there 'official confirmation' that AdGuard Home works as expected with this release?

**Comment by planet0** [comment]
Seems to be working.

**Comment by ameshkov** [comment]
@planet0 hey, thanks for checking it!

And what about these old weird issues you were having? #633 

Did it go away with the new rapsbian?

**Comment by planet0** [comment]
@ameshkov So far I've been waiting 5 minutes from habit before I try using anything on the network. I'll restart the Pi when no one is using the network and let you know the results on #633 for you.

**Comment by planet0** [comment]
@ameshkov Good news... the 5 minute on boot issue seems to no longer occur as of Buster 🎉
