### ISSUE TITLE
The default value of blocked_response_ttl is too short.

### ISSUE THREAD

**Issue by 280blocker** [AdguardTeam/AdGuardHome#860]
The default value of blocked_response_ttl is too short.

Currently, the default value of blocked_response_ttl is very short (10 seconds), so the blocking domain information is queried many times.

If blocked_response_ttl is long, information on blocked domains is cached for a long time, which stabilizes the block performance.

I think it is better to set as long as 3600-18000 seconds (1-5 hours).

**Comment by ameshkov** [comment]
Hi! The problem with high TTL is that you won't be able to easily unblock the domain -- clients will have it cached for the whole hour.

**Comment by 280blocker** [comment]
I can understand the disadvantages you point out, but I still think that 10 seconds is too short.
Since the optimal value varies depending on the usage environment, I also respect your opinion.

Thank you for your reply.

**Comment by ameshkov** [comment]
It is too low for a VPS installation indeed, but I suppose that if you setup AGH inside your home network, extra DNS queries don't hurt much.
