### ISSUE TITLE
can't run in raspberrypi 3B+

### ISSUE THREAD

**Issue by sosp** [AdguardTeam/AdGuardHome#862]
I install adguardhome on 3b+,after set up,always appear that"Error: control/version.json | Network Error",and then the web can't open anymore

**Comment by mmotti** [comment]
I don't mean to discredit this issue but it works on my 3b running Raspbian Stretch or Buster - So it's not an issue across the board

**Comment by planet0** [comment]
Also running fine on my 3 B+.

The error seems that AdGuard Home can't connect to the Internet. Does your 3 B+ have an active internet connection? If you run this command below, does Raspbian successfully download and check for updates?

`sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade`
