### ISSUE TITLE
Top clients board do not show the actual client name

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdGuardHome#864]
If you assign a specific name to the client instead of his IP (via MAC address), then it is not displayed on the "top clients" board. Adguard Home version: v0.96-hotfix (See the screenshot)

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagi9ub82.jpg)

</details>

**Comment by ameshkov** [comment]
Even after refreshing the homepage?

**Comment by TheHasagi** [comment]
@ameshkov Even if I restart from terminal

**Comment by szolin** [comment]
We can convert MAC to IP only if the client uses AGH's built-in DHCP server.

**Comment by TheHasagi** [comment]
Then we should make a better explanation about Client settings/add client via MAC

**Comment by szolin** [comment]
Oh, it seems we already have it:
> Please note, that using MAC as identifier is possible only if AdGuard Home is also a DHCP server
