### ISSUE TITLE
Use login page instead of browser login

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#865]
Similar to modern Router/Gateway/Modem login pages and with Pi-hole, I would like to see AdGuard Home use a login page instead of relying on the browser to show the form fields.

By doing this, you do not need to rely on the client's browser, and this also allows the user to login and save via their Password Managers (Lastpass, Bitwarden, etc.).

Could also be an opportunity to use further protection methods like two-factor auth, reCaptcha, and more.

Also a 'remember me' checkbox like Pi-hole does, they allow you to stay logged in for 7 days from memory.

**Comment by ibksturm** [comment]
vote + 1

**Comment by BooBerry** [comment]
Was just thinking about this exact thing this morning. +1 from me too.

**Comment by ArchiveBase** [comment]
![5f9d4efd-fdcd-4104-8376-7f715b0b2b9c](https://user-images.githubusercontent.com/46082456/61867282-0b3ebd80-af01-11e9-936d-a3fe5e71b971.gif)
Login

![signup-and-password-field-reaction-for-yeti-mascot-on-login-form](https://user-images.githubusercontent.com/46082456/61867541-a46dd400-af01-11e9-8857-eb54bc46fdb4.gif)
Login

**Comment by ArchiveBase** [comment]
![5d39898d7decd179586120](https://user-images.githubusercontent.com/46082456/61869048-efd5b180-af04-11e9-9285-27601589a3ea.gif)

**Comment by ameshkov** [comment]
@szolin 

Here's what we need here:

1. We should still continue to support HTTP basic auth (for the API backward compatibility);
2. We should add an option to have multiple users in the configuration file (do not expose it to the UI yet);
3. We should provide two pages: login page (see https://preview.tabler.io/login.html) and "forgot password" page (just static text there: go to the config file and change your password there).

**Comment by thueske** [comment]
What about https://github.com/AdguardTeam/AdGuardHome/issues/394? :)
