### ISSUE TITLE
Docker Query Log showing filtered but not blocking site with AdGuard Bear

### ISSUE THREAD

**Issue by mpgoebel** [AdguardTeam/AdGuardHome#869]
### Steps to reproduce

1.Install Docker via instructions
2.Set Parental Controls
3.Try PornHub
4.Shows PornHub was blocked but site was displayed

### Expected behavior

Bear screen showing AdGuard blocked it
### Actual behavior

Saw lots of nude ladies

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/32761115/60615803-a080e300-9d95-11e9-9df4-822a9491c746.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| Tried both .96 hotfix and the Edge with same results
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| Unifi Security Gateway
| Operating system and version:| Unraid docker 6.7.2

**Comment by ameshkov** [comment]
Hm, the question is why does your browser ignore the DNS response by AGH. Could it be that you're using some proxy or VPN as well?
