### ISSUE TITLE
Make: cannot use uint64(val) (type uint64) as type int64 in assignment

### ISSUE THREAD

**Issue by rubenverhoef** [AdguardTeam/AdGuardHome#870]
When trying to build this project i get this:
````
# github.com/AdguardTeam/AdGuardHome/home
home/os_unix.go:16:11: cannot use uint64(val) (type uint64) as type int64 in assignment
home/os_unix.go:17:11: cannot use uint64(val) (type uint64) as type int64 in assignment
*** Error code 2
````
Any idea's? i'm trying to compile the code on FreeBSD.

**Comment by szolin** [comment]
You can replace `uint64` with `int64`.
It seems that `Rlimit struct` has different types on FreeBSD.

**Comment by ameshkov** [comment]
@szolin I guess we should fix this. The fix seems to be trivial, let's just wait for the confirmation that changing the type helps

**Comment by rubenverhoef** [comment]
@szolin @ameshkov That works for me, it compiles now. Now i have to find out how to start it to test the software.
