### ISSUE TITLE
some URLs are incorrect on the page Популярные DNS-провайдеры

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#871]
some URLs are incorrect on the page https://kb.adguard.com/ru/general/dns-providers

Google DOH DNS https://developers.google.com/speed/public-dns/docs/doh/
**wrong** https://dns.google.com/experimental **correct** https://dns.google/dns-query
Cloudflare DOH DNS https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure/
**wrong** https://dns.cloudflare.com/dns-query **correct** https://cloudflare-dns.com/dns-query
Quad9 DNS https://www.quad9.net/doh-quad9-dns-servers/
**correct** https://dns.quad9.net/dns-query

**Comment by ameshkov** [comment]
@YBS-PC thank you!

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardKnowledgeBase #369](https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/369) via [**ZenHub**](https://www.zenhub.com/)
