### ISSUE TITLE
Stop without no reason

### ISSUE THREAD

**Issue by Threefish4096** [AdguardTeam/AdGuardHome#872]
### Steps to reproduce

1. Start AdGuardHome with crontab : http://prntscr.com/oan5ff

### Expected behavior
Stay in background after it start

### Actual behavior
Start, stay in background but after some hours it stop alone

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.96-hotfix
| How did you setup DNS configuration:| Router
| If it's a router or IoT, please write device model:| BananaPi R2
| Operating system and version:| Linux bpi-iot-ros-ai 4.14.131-bpi-r2-main #1 SMP Sat Jun 29 10:46:41 UTC 2019 armv7l GNU/Linux

**Comment by ameshkov** [comment]
Please save the stderr somewhere, this is necessary to figure why it stopped.

**Comment by ameshkov** [comment]
Actually, my bet is that it was due to #831 which is now fixed in v0.97. Please reopen if it happens again.

**Comment by ibksturm** [comment]
let is look how long it belobgs to 0.97-hotfix-1 🤪

**Comment by ameshkov** [comment]
:(

**Comment by ibksturm** [comment]
> :(

just joking, as it looks you broke with traditional „one-day-after-release-rollout-hotfix“

👍👍👍
