### ISSUE TITLE
[Feature Request] Add FreeBSD releases

### ISSUE THREAD

**Issue by rubenverhoef** [AdguardTeam/AdGuardHome#873]
I have tested this on FreeBSD and works great, exept for this "Bug" #870 

It would be nice to see the FreeBSD version official supported so i can easy update and install the software.

**Comment by ameshkov** [comment]
Shouldn't be a problem. Will amd64 be enough?

**Comment by rubenverhoef** [comment]
Yes, for me it would be enough.

Expect for the compiling, how about installing it as an service for freebsd? Right now I made an very simple service to start adguard but it needs improvements. 

I don't think I can run the `-s install` command on my compiled freebsd version?

**Comment by ameshkov** [comment]
As I understand, the library we use does not support FreeBSD:
https://github.com/kardianos/service/issues/98

**Comment by mrloop** [comment]
@rubenverhoef could you post your simple service to start adgaurd on freebsd please?

**Comment by mrloop** [comment]
This is what I came up with, mostly copy and paste from https://redbyte.eu/en/blog/supervised-freebsd-init-script-for-go-deamon/
```
#!/bin/sh
#
# PROVIDE: AdGuardHome
# REQUIRE: networking
# KEYWORK:
#
# see https://redbyte.eu/en/blog/supervised-freebsd-init-script-for-go-deamon/
# remember to add `adguardhome_enable='YES` to `/etc/rc.conf`

. /etc/rc.subr

name=AdGuardHome
rcvar="adguardhome_enable"
adguardhome_command="/AdGuardHome/AdGuardHome"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${adguardhome_command}"

load_rc_config $name
: ${adguard_enable:=no}

run_rc_command $1
```

I've got AdGuardHome in a jail, running as root, and installed at `/AdGuardHome/AdGuardHome`

**Comment by rubenverhoef** [comment]
This is the service i'm using to run adguard:
https://github.com/rubenverhoef/iocage-plugin-adguard/blob/master/overlay/usr/local/etc/rc.d/adguard
