### ISSUE TITLE
Using DoH upstream causes DNS timeout on WAN failover.

### ISSUE THREAD

**Issue by ruifung** [AdguardTeam/AdGuardHome#875]
When using DoH upstreams, DNS queries to AGH will timeout when my router switches to the backup internet connection. After few minutes it proceeds to work again. 

This does not occur when using DoT instead of DoH. My personal suspicion is that with DoH, persistent HTTPS connections are used and it would stop DNS resolution until the existing connections times out.

### Steps to reproduce
1. Test DNS resolution - it works
2. Shut down the main internet connection to cause a failover.
3. Test DNS resolution again - times out
4. Wait a few minutes, DNS resolution works again.

### Expected behavior
DNS Resolution should work without timing out on WAN connection failover

### Actual behavior
DNS starts timing out for a few minutes.

### Your environment
Router has 2 internet connections, one fiber connection and a backup LTE.
AGH is installed in a docker container and exposed to network with MACVLAN.

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server: | 0.96-hotfix
| How did you setup DNS configuration:| Docker container w/ MACVLAN
| If it's a router or IoT, please write device model:| Official AGH Docker Image
| Operating system and version:| Docker on Ubuntu 19.04

**Comment by ameshkov** [comment]
> My personal suspicion is that DoH is that persistent HTTPS connections are used and it would stop DNS resolution until the existing connections times out.

Yeah, most likely this is the reason.

**Comment by szolin** [comment]
https://github.com/AdguardTeam/dnsproxy/commit/484cc3a1e45fd5375189c977519c651267ec4c8f
