### ISSUE TITLE
[feature request] change querylog.json location or add live view only (no write to disk)

### ISSUE THREAD

**Issue by kt1024** [AdguardTeam/AdGuardHome#876]
I'm running adguardhome container in  SBC, system(dietpi/debian OS, at home and office) is install on a TF card, so I want to  lower writes to TF card (to make it live longer). but also want to keep a litle latest logs for analysis.

is it able to 
**(a)** move log file "_querylog.json_" to a separate folder, like _/opt/adguardhome/work/logs_ ?  

(so I can map the sub folder to host OS _/var/log_ folder, it's in RAM and clear every hour) I have tried map the querylog.json with a empty file, container will fail and _docker logs_ is empty

**OR** 

**(b)** just save some latest logs (like 100 query) in ram and show in web console, and **disable** log write to disk.

thank you.

**Comment by ameshkov** [comment]
Check out how we do it in the Docker file:
https://github.com/AdguardTeam/AdGuardHome/blob/master/Dockerfile.travis#L23

`-w` changes the working dir (so all the data including query log will be stored there).

**Comment by kt1024** [comment]
@ameshkov in dietpi, move whole working to ramdisk(/var/log) will cause filters be deleted with querylogs.json

**Comment by ameshkov** [comment]
@kt1024 marked as a feature request then, we'll need to think about it.

**Comment by kt1024** [comment]
update of my misunderstand about diet-pi ramlog, it won't delete all files in /var/log/, just OS logs will be purged. so my _suggestion **a)**_ will not work as intend. 
(querylog.json will persist and use same size physical ram, so it's not a good idea, my bad)

suggestions 
b) save x lines to ram and show/update in console , c) send query logs to a syslog server

thank you.

**Comment by ameshkov** [comment]
@szolin what do you think about it in the light of #827 ?

**Comment by szolin** [comment]
I support option b.  We can add these settings related to query log:
1. `query_log_mem_size 100` - how many query log entries we keep in memory before writing to file
2. `query_log_expire 24h` - how much time we keep query log entries in file before they expire and are removed.  By default - 24 hours (this value is currently hard-coded).
If `expire 0` - don't store data in file at all.

**Comment by ameshkov** [comment]
The problem of option b is that it effectively disables statistics.

**Comment by szolin** [comment]
...Also, we can add the setting with query log file path:
3. `query_log_path ./data/querylog.json`

Regarding statistics - yes, it's true that currently we won't be able to show full statistics if query log file isn't available, because the statistics data is generated by reading the query log file on startup.  So there are 2 options:
1. Use separate file for statistics (another big feature)
2. Agree with the fact that statistics will only be shown while AGH is running and it will reset on every startup.

**Comment by kt1024** [comment]
for myself, I won't check the statics very often, I can accept statics be reset in short time. 
knowing AGH is working will be just fine.

**Comment by szolin** [comment]
We have a separate statistics file now, so nothing prevents us from adding an option to stop writing logs to disk.

**Comment by ameshkov** [comment]
Well, we now have the option to disable query log, but we're missing this:
> just save some latest logs (like 100 query) in ram and show in web console, and disable log write to disk.

**Comment by Mosney** [comment]
I think it is necessary that separate query log file into different path like /tmp, I deploy AGH in OpenWrt and also use USB flash, so I have same needs. Even AGH may use DB in the future, I think allow frequent-files located in some ramdisk path is significant.

**Comment by ameshkov** [comment]
@Mosney that's why we allow configuring the `data` folder path -- all files there (maybe save for filters) are frequently accessed/changed.

**Comment by Mosney** [comment]
> @Mosney that's why we allow configuring the `data` folder path -- all files there (maybe save for filters) are frequently accessed/changed.

Got it, it is reasonable.
