### ISSUE TITLE
Are you considering adding a custom ttl cache time?

### ISSUE THREAD

**Issue by jsda** [AdguardTeam/AdGuardHome#877]
This software is very useful, really great! Thank you AGH!

**Comment by Yuan573** [comment]
Are you talking about this?
![Config](http://imgur.com/nhuSL6S.png)
https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

**Comment by jsda** [comment]
@Yuan573 Will this cache the normal response time?
