### ISSUE TITLE
Filter Access is denied.

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#878]
У меня появилась проблема на двух устройствах после обновления AdguardHome с версии 0.96 на версию 0.97.0 проблема заключается в том что все неактивные фильтры(где не стоит галочка) заработали и при удалении их ошибка выскакивает которую я прикрепил а после того когда обновляешь страницу то все фильтры исчезают и после перезапуска AdguardHome все восстанавливается.
До этого не было такого и все работало стабильно.
Обновлял как обычно заменив AdGuardHome.exe на новый.

### Actual behavior

<details><summary>Screenshot:</summary>

![500](https://user-images.githubusercontent.com/46345396/61156945-63d38b00-a4fd-11e9-8303-5179dcb082d5.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| v0.97.0
| Operating system and version:| Windows 10
| Operating system and version:| Windows Server 2012 R2

**Comment by ameshkov** [comment]
Хм, возможно специфичный для Windows баг, проверим, спасибо!

**Comment by ameshkov** [comment]
Про выключенные фильтры да, подтверждаю, действительно есть такой дефект. Будет хотфикс видимо в понедельник.

**Comment by Eyeborgs** [comment]
Хорошо, буду ждать.

**Comment by szolin** [comment]
duplicate: #879

**Comment by ameshkov** [comment]
@szolin not really, what about the "access denied" issue?

**Comment by szolin** [comment]
"access denied" error occurs because we try to remove the file which is being used by our urlfilter.
When we fix the issue with "enabled/disabled" checkbox, an old instance of urlfilter will close the file, while the new instance will not open it again (because the filter is disabled).

**Comment by ameshkov** [comment]
@szolin you won't be able to remove the filter which is enabled

**Comment by szolin** [comment]
Everyone who is experiencing this issue can now upgrade to the new beta version we've just released:
https://static.adguard.com/adguardhome/beta/version.json
(Download an archive, unpack and replace files)

**Comment by Eyeborgs** [comment]
Обновился на test версию AdGuard Home 0.97.0-8-g4326

Стало выходить сообщение после удаления фильтра и перезагрузки страницы (F5)<details><summary>Screenshot:</summary>
![You_are_currently_not_using_AdGuard_Home](https://user-images.githubusercontent.com/46345396/61238265-f2861900-a744-11e9-89f5-f2dd531a6a8c.png)
</details>

Эта проблема с доступом к фильтрам таки осталась в консоли<details><summary>Screenshot:</summary>
![Failed_to_save_the_updated_filter](https://user-images.githubusercontent.com/46345396/61238272-f6b23680-a744-11e9-8d01-798506ac92e1.png)
</details>

Решилась проблема с рабочими фильтрами которые отключены.

**Comment by szolin** [comment]
new beta version:
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

**Comment by Eyeborgs** [comment]
При первом запуске v0.97.0-12-g87cc все работало но после того как я удалил фильтр и добавил его обратно то AdGuard Home полностью перестал работать даже после когда я вернул версии v0.97.0-8-g4326 с папки agh-backup и повторное обновления. <details><summary>Screenshot:</summary>
![1](https://user-images.githubusercontent.com/46345396/61291607-a506bc00-a7d7-11e9-9aca-4dca1aad35e2.png)
![2](https://user-images.githubusercontent.com/46345396/61291626-afc15100-a7d7-11e9-9583-1aa66fc8007c.png)
</details>

Сейчас я вернулся на версию v0.97.0-8-g4326

**Comment by szolin** [comment]
beta-3 (v0.97.0-14):
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

**Comment by Eyeborgs** [comment]
Обновился до v0.97.0-14-g55a45 и заметил что AdGuard Home перестает работать через несколько секунд (закрывается консоль). 
Вернулся на версию v0.97.0-8-g4326

**Comment by ameshkov** [comment]
А что выводит в консоль?

**Comment by Eyeborgs** [comment]
Не чего - я думаю может что то выходит но я не успеваю этого увидеть потому что он сразу же закрывается..

**Comment by szolin** [comment]
Чтобы консоль не закрывалась, можно в начале запустить cmd.exe, перейти в папку с программой и затем запустить оттуда приложение.

**Comment by Eyeborgs** [comment]
![cmd](https://user-images.githubusercontent.com/46345396/61294223-00d44380-a7de-11e9-8d4c-456faf0ff9e6.png)

**Comment by szolin** [comment]
beta-4 (v0.97.0-16):
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions

Должно всё починиться

**Comment by Eyeborgs** [comment]
Да, все починилось.
Если что то произойдет я напишу.

**Comment by szolin** [comment]
Отлично!  Спасибо, что помогли протестировать!

**Comment by hkthomas** [comment]
: https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions
The best it can be put in the link update on time, so we can know the beta update,
Thank you
