### ISSUE TITLE
Filters are not disabled after unchecking

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#879]
Steps to reproduce

1.remove a tick from filter
2.open url

### Expected behavior
the site should open

### Actual behavior
site opens only if you remove the filter

| Version of AdGuard Home 0,97
| How did you setup DNS configuration: Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Buster

**Comment by ameshkov** [comment]
Confirmed, expect a hotfix soon. It will first be published to the [beta channel](https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions).

**Comment by szolin** [comment]
Filter's `enabled` property wasn't checked before passing filter rules further.
This bug appeared in v0.92 or maybe even older versions.

**Comment by szolin** [comment]
Everyone who is experiencing this issue can now upgrade to the new beta version we've just released:
https://static.adguard.com/adguardhome/beta/version.json
(Download an archive, unpack and replace files)
