### ISSUE TITLE
Debug for version 0.97

### ISSUE THREAD

**Issue by hkthomas** [AdguardTeam/AdGuardHome#885]
WINDOWS 7 32 bit.

Works on version 0.97.

The filter rules file cannot be written. A TMP file is generated.

Console prompt: access denied.

I can't edit it manually.

**Comment by szolin** [comment]
duplicate: #878

**Comment by szolin** [comment]
Fixed in AGH beta:
https://github.com/AdguardTeam/AdGuardHome#test-unstable-versions
(Download an archive, unpack and replace files)

**Comment by hkthomas** [comment]
Thank you very much!
