### ISSUE TITLE
Couldn't start forwarding DNS server

### ISSUE THREAD

**Issue by hesss5** [AdguardTeam/AdGuardHome#888]
C:\Users\gg\Desktop>AdGuardHome.exe
2019/07/16 21:12:05 [info] AdGuard Home, version v0.97.0, channel release

2019/07/16 21:12:05 [info] Added 1 client aliases from C:\Windows\system32\drive
rs\etc\hosts
2019/07/16 21:12:05 [info] Upstream 0: https://dns.cloudflare.com:443/dns-query
2019/07/16 21:12:06 [info] Start DNS server periodic jobs
2019/07/16 21:12:06 [info] Starting the DNS proxy server
2019/07/16 21:12:06 [info] Ratelimit is enabled and set to 20 rps
2019/07/16 21:12:06 [info] The server is configured to refuse ANY requests
2019/07/16 21:12:06 [info] DNS cache is enabled
2019/07/16 21:12:06 [info] Creating the UDP server socket
2019/07/16 21:12:06 [fatal] Couldn't start forwarding DNS server, cause: couldn'
t listen to UDP socket, cause: listen udp 0.0.0.0:53: bind: Only one usage of ea
ch socket address (protocol/network address/port) is normally permitted.

### Steps to reproduce
can not tell you how since don't know it
today started pc and keep getting above 
when accessing interface nothing logged
but a few connection that app itself make
uninstalled restarted pc installed again nothing help
### Expected behavior
no fatal error should happen
and seems AH dont work
log something

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
|version  0.97.0
| How did you setup DNS configuration:| (in windows )
| Operating system and version:|windows 8.1 latest update)

**Comment by ameshkov** [comment]
> bind: Only one usage of each socket address (protocol/network address/port) is normally permitted

Check if there's another instance of AdGuardHome running in background

**Comment by hesss5** [comment]
> 
> 
> > bind: Only one usage of each socket address (protocol/network address/port) is normally permitted
> 
> Check if there's another instance of AdGuardHome running in background

just one instance

**Comment by ameshkov** [comment]
Then you need to figure what another process is using this port

Use `netstat -a`

**Comment by hesss5** [comment]
Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:53             user:0               LISTENING
  TCP    0.0.0.0:135            user:0               LISTENING
  TCP    0.0.0.0:1025           user:0               LISTENING
  TCP    0.0.0.0:1026           user:0               LISTENING
  TCP    0.0.0.0:1027           user:0               LISTENING
  TCP    0.0.0.0:1028           user:0               LISTENING
  TCP    0.0.0.0:1029           user:0               LISTENING
  TCP    0.0.0.0:25255          user:0               LISTENING
  TCP    modemr:139         user:0               LISTENING
  TCP    modemr:2962        104.19.198.29:https    ESTABLISHED
  TCP    modemr:2971        185.199.109.153:https  ESTABLISHED
  TCP    modemr:3567        ec2-52-11-35-6:https   TIME_WAIT
  TCP    modemr:3569        server-54-230-202-225:https  TIME_WAIT
  TCP    127.0.0.1:1001         user:0               LISTENING
  TCP    127.0.0.1:25362        user:3482            TIME_WAIT
  TCP    [::]:53                user:0               LISTENING
  TCP    [::]:135               user:0               LISTENING
  TCP    [::]:1025              user:0               LISTENING
  TCP    [::]:1026              user:0               LISTENING
  TCP    [::]:1027              user:0               LISTENING
  TCP    [::]:1028              user:0               LISTENING
  TCP    [::]:1029              user:0               LISTENING
  TCP    [::]:25255             user:0               LISTENING
  UDP    0.0.0.0:53             *:*
  UDP    0.0.0.0:500            *:*
  UDP    0.0.0.0:4500           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    modemr:137         *:*
  UDP    modemr:138         *:*
  UDP    [::]:53                *:*
  UDP    [::]:500               *:*
  UDP    [::]:4500              *:*
  UDP    [::]:5355              *:*

**Comment by ameshkov** [comment]
Here it is:
```
UDP 0.0.0.0:53 :
UDP [::]:53 :
```

Read here how to find what process it is:
https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows
