### ISSUE TITLE
AdGuard Home As Default Gateway

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdGuardHome#889]
Can you please give the option to use AdGuard Home as the default gateway and then forward traffic to the real default gateway, this could be set via DHCP.

**Comment by ibksturm** [comment]
@zero77 hi there

i think this is definitly not a good idear, arguments are:

acting as a gateway is mutch more complicated than dns (corebussines  of AGH Guys) or DHCP (still in beta). you have to look at firewall , different connection types (ipv4, ipv4, pppe, mobileshit, isdn etc etc), tunneling stuff (6in4, 4in6 etc). story wanna go forward with vpn solutions (ipsec, openvpn, wireguard and how them all named). and if all things are implement, the magic and mystical unicorn wanna dmz, static routes, portforwarding, port triggering and perhaps triggered port. oooh i forgett acting as NAS, DECt/SIP releaise and so on...

don‘t missunderstand me, i just think about and got the experience that openwrt (actual 18.06.4) with AGH makes much more sence. 

as a simple calculation, on AGH works about 15...20 people, on openwrt (who‘s core job IS acting as a gateway) worked over years about 800...1200 peoples... thats 40..60 time more ressources & knowledge. 

hope you understand my opinion

**Comment by ameshkov** [comment]
Tbh, this is extremely complicated. I'll keep it open as a feature request, though.

**Comment by KizunaH** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2206

**Comment by ameshkov** [comment]
Let's close it in favor of #2206
