### ISSUE TITLE
Allow changing safebrowsing and parental caches size

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#890]
Currently, they're hard-coded. We should allow changing them via the configuration file.

Ideally, we should be able to control its size in bytes, and not in the number of records.

Also, expose cache size setting to the yaml configuration.

**Comment by ameshkov** [comment]
Consider using https://github.com/VictoriaMetrics/fastcache

**Comment by szolin** [comment]
> Fastcache automatically evicts old entries when reaching the maximum cache size set on its creation.

It removes *old* entry, instead of removing *least recently used* entry which is what AGH currently does.
With fastcache we will send more requests over network, than we do now, in case when cache capacity is reached.

**Comment by szolin** [comment]
e09ec5d38e883b222cdf4758c8d9533bf7111248
