### ISSUE TITLE
querylog.json no longer being written to after upgrading to 0.97.1

### ISSUE THREAD

**Issue by BlohoJo** [AdguardTeam/AdGuardHome#894]
I'm running Windows x64 version of AdGuardHome as a service on Windows 7 SP1.

The log no longer writes to disk (i.e., to data\querylog.json). It appears to only be active in memory. If the service is stopped and restarted, the log is lost.

The querylog.json file is there under AdGuardHome\data, but the modified time stamp is 07/17/2019 12:49 PM, exactly the time that I stopped the service, upgraded to 0.97.1, then restarted the service.

I had upgraded from 0.97, so querylog.json was definitely being written to as of that version. It appears to have broken in 0.97.1.

**Comment by szolin** [comment]
Can you show application logs?  Maybe AGH doesn't have permission to write to querylog.json for some reason.
