### ISSUE TITLE
[Feature Request] Statistics on the use of filters

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#895]
It would be nice to see statistics about the use of filters. So you can see which filters are not used at all and turn them off.

**Comment by YBS-PC** [comment]
Было бы хорошо видеть статистику использования фильтров, чтобы знать какие фильтры вообще не используются или используются очень редко. Или количество заблокированных (или открытых с помощью белого списка) запросов по каждому фильтру. Например, добавить ещё одну колонку в таблице где добавляют фильтры с наименованием "количество отработанных запросов". Таким образом, напротив каждого фильтра отражалась бы статистика его использования. Сори за не английский.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/580

**Comment by ameshkov** [comment]
Closed as dup of #580

Please upvote it if you want it to be done faster.
