### ISSUE TITLE
[Feature Request] Add button to block client in top clients from dashboard?

### ISSUE THREAD

**Issue by JoseGalRe** [AdguardTeam/AdGuardHome#896]
I do not know if this goes against the design rules,
but it would be very useful to block clients from the dashboard,
it would be very useful in vps, as there are many companies scanning dns servers,
and it is annoying to see unknown clients.

in my case, sometimes there are up to 15 unknown ip addresses in 24 hours,
and it is boring to add one by one to the blacklist in the dns settings,
a button would do it faster, and would have better control.

it could be something similar to blocking address in query log.

like this:
![adguard](https://user-images.githubusercontent.com/1406297/61584551-e6180c80-ab06-11e9-9d6d-1b73671e4a54.png)

**Comment by radutopala** [comment]
I'm looking for the same feature.

**Comment by ameshkov** [comment]
Additionally, we should highlight clients that are blocked (i.e. access is denied for this IP address).

@szolin I suggest extending `clients/find` method -- add information whether the IP address is blocked or not.

**Comment by ameshkov** [comment]
In the beta version using this button, sometimes leads to losing everything I had in the "Disallowed clients" list.

@IldarKamalov you should request the current disallowed list before modifying it.
