### ISSUE TITLE
Custom filtering rules not working correct

### ISSUE THREAD

**Issue by hdtvspace** [AdguardTeam/AdGuardHome#897]
Custom rules
...
||stern.de/gujAd.js$match-case
||commsvc.stern.de^$important
||www.stern.de/gujAd.js$match-case
||commsvc.stern.de^
...

Adguard Home is not blocking the anti adblocker script from commsvc.stern.de or an simple ad script gujAd.js withe the custom rules above. Tried also 0.0.0.0 commsvc.stern.de. But the subdomain commsvc.stern.de is always loaded.

And the webmaster from stern has made a big mistake and delivers the script from a subdomain, easy to block. But adguard home is not blocking it.
 

### Steps to reproduce

1. Load the site www.stern.de, click and read an article and scroll down. Load the browser developer tools and the scripts are loaded.
2.
3.
4.

### Expected behavior

Customs riles are not applied
### Actual behavior

The scripts are loaded. Also the safari browser cache is before loading the site cleared. 

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0)
0.97.1
| How did you setup DNS configuration:| (System/Router/IoT)
Router
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
Raspberry Pi 3 Model B
| Operating system and version:| (e.g. Ubuntu 18.04.1)
raspian buster

**Comment by hdtvspace** [comment]
So after an whole restart of the raspberry and the imac the  ||commsvc.stern.de^ is working and blocked, but not rules with match-case e.g. ||stern.de/gujAd.js$match-case

The JS file is always loaded.

**Comment by ameshkov** [comment]
DNS server operates with domains, not full URLs.

The only way to filter actual HTTP requests is to implement a proxy. Vote for this feature request if you'd like to have it: #391
