### ISSUE TITLE
[Feature Request] Tool to consolidate and adjust filters

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#899]
can you add a tool to consolidate, sorting and adjust filters, remove duplicates, like here:
https://github.com/mmotti/adguard-home-filters/tree/master/generator
?

**Comment by ameshkov** [comment]
I think this is kinda out-of-scope for us.

On the other hand, what stops you from using the same script @mmotti does?

**Comment by el-ef** [comment]
Hi there,
are there any further plans on integrating such a feature? Would be really nice to have a mechanism that automatically boils down the filter lists, removing duplicates, comments and faulty entries.

Have a nice day.
Ellef

**Comment by ameshkov** [comment]
There's already a tool for that: https://github.com/AdguardTeam/HostlistCompiler
