### ISSUE TITLE
use parallel queries to speed up resolving by simultaneously querying all upstreams servers

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#901]
does the option "use parallel queries to speed up resolving by simultaneously querying all upstreams servers" really work? sometimes checking this option I don't pass the dnssec test, sometimes speed down resolving. 
maybe it's just a coincidence.

and what happens if you disable this option but specify several resolvers - ADGH selects the fastest resolver or the top one?

using dns resolvers:
https://dns.google/dns-query
https://cloudflare-dns.com/dns-query
https://doh.cleanbrowsing.org/doh/security-filter/
sdns://AQMAAAAAAAAADDkuOS45Ljk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0

| Version of AdGuard Home 0.97.1
| How did you setup DNS configuration: Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Buster

**Comment by hdtvspace** [comment]
Do not waste time with DoH and security. Its slow over http and the dns provider AND your ISP see all what you do... After tests I am back to only dnnsec and thats all.

**Comment by YBS-PC** [comment]
> Do not waste time with DoH and security. Its slow over http and the dns provider AND your ISP see all what you do... After tests I am back to only dnnsec and thats all.

that is, you just specified DNS with dnssec support (for example, 1.1.1.1 or 8.8.8.8) ?

**Comment by ameshkov** [comment]
> sometimes checking this option I don't pass the dnssec test

Are you sure all four of them are DNSSEC-enabled?

> sometimes speed down resolving.

Three of four resolvers use DOH so it may be that you're doing three TLS handshakes simultaneously. This might be a considerable overhead for slow devices.

> and what happens if you disable this option but specify several resolvers - ADGH selects the fastest resolver or the top one?

Yes, that's right.

**Comment by YBS-PC** [comment]
> Yes, that's right.
which answer is right?
1 - AGH selects the fastest resolver
or
2 - AGH selects the top one

**Comment by ameshkov** [comment]
The fastest:)

**Comment by RealAmes** [comment]
Using the default  Cloudflare over HTTTPS felt slow so over several days I did a lot of testing with namebench.  Cloudflare HTTPS was by far the slowest. Cloudflare TLS was always the fastest. Google and Cloudflare regular DNS was in the middle; closer to TLS.

Whenever I tried parallel queries it was always slower than just TLS by itself.

Is namebench a good testing tool?

**Comment by ameshkov** [comment]
Tbh, this feature makes sense only when your connection is not really good (mobile, for instance). In any other case, it creates overhead on extra TLS handshakes.

**Comment by cpaig** [comment]
> Tbh, this feature makes sense only when your connection is not really good (mobile, for instance). In any other case, it creates overhead on extra TLS handshakes.

This feature is refer to parallel queries or DoH？

**Comment by ameshkov** [comment]
@cpaig parallel queries
