### ISSUE TITLE
[QUESTION] is it possible have a path to a certificate?

### ISSUE THREAD

**Issue by Omoeba** [AdguardTeam/AdGuardHome#902]
I have an Nginx server that includes auto-updating the letsencrypt certificate. Is it possible to use a path to the certificate instead of copy and pasting to AdGuardHome?

**Comment by Akruidenberg** [comment]
+this is my most wanted feature. Frustrated to update changes from new certificate.

**Comment by szolin** [comment]
duplicate of #634

**Comment by ameshkov** [comment]
Closed as dup
