### ISSUE TITLE
[QUESTION] is it possible to specify a local filter file?

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#904]
is it possible to specify a local filter file? 

| Version of AdGuard Home 0.97.1
| How did you setup DNS configuration: Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Buster

**Comment by Cloud-O** [comment]
Is this? https://github.com/AdguardTeam/AdGuardHome/issues/817

**Comment by ameshkov** [comment]
Dup of #817 indeed.
