### ISSUE TITLE
Adguard home stops working randomly

### ISSUE THREAD

**Issue by zeus10000** [AdguardTeam/AdGuardHome#905]
Noticed, Adguard home stopped resolving domains over both UDP and TLS. HTTPS GUI was working at the same time. Attaching error logs for the same. The system had plenty of CPU and Memory available and had not run out of resources. The issue was recovered by rebooting the virtual instance. 

| Version of AdGuard Home server:| v0.97.1
| How did you setup DNS configuration:| VPS
| Operating system and version:| Debian 10
[AdGuardHome.txt](https://github.com/AdguardTeam/AdGuardHome/files/3449371/AdGuardHome.txt)

**Comment by ameshkov** [comment]
INFO-level logs are not enough to figure what went wrong. Please enable "verbose" level logging in the configuration (set `verbose` to true in the yaml config file).

We will also need to know when exactly did the issue happen.

**Comment by zeus10000** [comment]
Sure enabled verbose for logging, waiting for the issue to happen again.
