### ISSUE TITLE
[Feature Request] Define IP for log

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#906]
Хотелось бы чтоб AdGuard Home мог определять IP блокировки или перенаправления с помощью правил HOST например: 192.168.1.166 example.org или публичный IP адрес с хостом но при этом писался сам адрес и ttl в "ответе" в журнале как на картинки плюс так же цвет поменять например на зеленый или другой..
![Снимок0](https://user-images.githubusercontent.com/46345396/62248551-0c845480-b3f1-11e9-913f-175e7ff5d7e5.PNG)
IP которые 127.0.0.1 и 0.0.0.0 оставить как есть с надписью "Filtered by BlackList"

Я думаю будет полезно, но мне например этого очень не хватает..

**Comment by ameshkov** [comment]
То есть по сути вы хотите чтобы в логе помимо статуса был еще и ответ, который отправлен?

**Comment by Eyeborgs** [comment]
да

**Comment by ameshkov** [comment]
Понял, хорошая идея.

Оформил в отдельную задачу:
https://github.com/AdguardTeam/AdGuardHome/issues/912
