### ISSUE TITLE
[Feature Request] Make a professional menu for adding DNS rules

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#907]
Сделайте профессиональное меню для возможности добавлять DNS параметры домена например: CNAME, TXT а так же A и AAAA и другие параметры..
Сейчас A и AAAA идет через правила HOST но хотелось бы меню и больше функций для добавления правил.

**Comment by szolin** [comment]
related: #818
Пока планируется поддержка CNAME, A и AAAA
