### ISSUE TITLE
Add openwrt luci-app please

### ISSUE THREAD

**Issue by kai456789** [AdguardTeam/AdGuardHome#908]
Add openwrt luci-app please

**Comment by ameshkov** [comment]
Could you please be more specific? I am not an expert on OpenWRT so I'd appreciate if you explain what it is and why we should do it.

**Comment by zxlhhyccc** [comment]
> Could you please be more specific? I am not an expert on OpenWRT so I'd appreciate if you explain what it is and why we should do it.
A package that is configured directly from the routing interface

**Comment by shenzt68** [comment]
Phicomm K3 (CpuMark : 10035.695143 Scores)
ARMv7 Processor rev 0 (v7l) x 2
but,ARMv7 Processor Rev 0 (v7l) does not have Fpu

**Comment by Cloud-O** [comment]
@zxlhhyccc We know. then is that asking integration? You all guys elaborate things but not tell what to do exactly personally i'm struggling to realize that

**Comment by ameshkov** [comment]
> A package that is configured directly from the routing interface

Why would you need it? AGH provides its own web interface already

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1201
https://github.com/rufengsuixing/luci-app-adguardhome/releases
