### ISSUE TITLE
regex takes precedence over @@|| .... ^$important

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#909]
regex takes precedence over @@|| .... ^$important
1) use filter with regex like https://github.com/mmotti/adguard-home-filters/blob/master/regex.txt
2) use whitelist with 
@@||https://xn--80afnfom.xn--80ahmohdapg.xn--80asehdb^$important
(https://мойгаз.смородина.онлайн)
3) try open 
https://xn--80afnfom.xn--80ahmohdapg.xn--80asehdb/login

| Version of AdGuard Home 0.97.1
| How did you setup DNS configuration: Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Buster

**Comment by ameshkov** [comment]
The whitelist rule should be:
`@@||xn--80afnfom.xn--80ahmohdapg.xn--80asehdb^$important`
