### ISSUE TITLE
 x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kai456789** [AdguardTeam/AdGuardHome#911]
2019/08/04 09:02:55 [info] Go to http://192.168.1.1:81
2019/08/04 09:02:56 [info] Couldn't request filter from URL https://adaway.org/hosts.txt, skipping: Get https://adaway.org/hosts.txt: x509: certifi                                          cate signed by unknown authority
2019/08/04 09:02:56 [info] Failed to update filter https://adaway.org/hosts.txt: Get https://adaway.org/hosts.txt: x509: certificate signed by unkn                                          own authority

2019/08/04 09:02:56 [error] os.Chtimes(): chtimes /tmp/mnt/disc0_1/data/filters/2.txt: no such file or directory

run at openwrt

VER:0.97.1

source:mipsel

cpu model               : MIPS 74K V4.0

**Comment by ameshkov** [comment]
Make sure that you have proper root certificates on your device. It seems that it's unaware of COMODO CA, therefore it cannot download anything from `https://adaway.org`

**Comment by dheeoo** [comment]
Hi, I having same problem....

Reboot many times router and dont work..
