### ISSUE TITLE
AdGuardHome cannot run on phicomm-k3 route. Why?

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#913]
AdGuardHome cannot run on phicomm-k3 route. Why?

**Comment by ameshkov** [comment]
Tbh, I have no clue what is it:)

You really need to supply more details:
1. What type of CPU do you have?
2. Which of AGH binaries have you tried to run?
3. What was printed to the output?

**Comment by shenzt68** [comment]
Phicomm K3 use ARMv7 Processor rev 0 (v7l) x 2. but , ARMv7 Processor Rev 0 (v7l) is a simplified version of the CPU without Fpu

**Comment by zxlhhyccc** [comment]
> Tbh, I have no clue what is it:)
> 
> You really need to supply more details:
> 
> 1. What type of CPU do you have?
> 2. Which of AGH binaries have you tried to run?
> 3. What was printed to the output?

Yes, is currently AdGuardHome not running because the CPU architecture is FPU free? Of course, other types of binaries can be executed, such as v2ray, which performs architectures below armv7, and K3 routers that are compiled or installed without compression will work fine.

**Comment by ameshkov** [comment]
Well, we don't have such hardware so I guess we'll need help with testing this.

1. You can try recompiling AdGuard for different CPU/architectures using the following command:
`CHANNEL=beta GOOS=linux GOARCH=arm GOARM=6 make`

2. Try different options from here: https://github.com/golang/go/wiki/GoArm

**Comment by shenzt68** [comment]
> Well, we don't have such hardware so I guess we'll need help with testing this.
> 
> 1. You can try recompiling AdGuard for different CPU/architectures using the following command:
>    `CHANNEL=beta GOOS=linux GOARCH=arm GOARM=6 make`
> 2. Try different options from here: https://github.com/golang/go/wiki/GoArm

GOOS=linux GOARCH=amd64 GO111MODULE=off go get -v github.com/gobuffalo/packr/...
PATH=/root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/node/bin:/usr/local/go/bin packr -z
CGO_ENABLED=0 go build -ldflags="-s -w -X main.version=v0.97.1-60-g6189 -X main.channel=beta" -asmflags="-trimpath=/root/AdGuardHome" -gcflags="-trimpath=/root/AdGuardHome"
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/gobuffalo/envy v1.6.7
go: finding github.com/gobuffalo/packd v0.0.0-20181031195726-c82734870264
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/spaolacci/murmur3 v1.0.1-0.20190317074736-539464a789e9
go: finding github.com/spf13/pflag v1.0.3
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding golang.org/x/text v0.3.0
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/allegro/bigcache v1.2.1-0.20190218064605-e24eb225f156
go: finding github.com/spf13/cobra v0.0.3
go: finding github.com/markbates/oncer v0.0.0-20181014194634-05fccaae8fc4
go: finding github.com/joho/godotenv v1.3.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding golang.org/x/net v0.0.0-20181102091132-c10e9556a7bc
go: finding github.com/AdguardTeam/urlfilter v0.4.1
go: finding github.com/davecgh/go-spew v1.1.0
go: github.com/AdguardTeam/urlfilter@v0.4.1: unknown revision v0.4.1
go: finding github.com/cespare/xxhash/v2 v2.0.1-0.20190104013014-3767db7a7e18
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/OneOfOne/xxhash v1.2.5
go: finding github.com/AdguardTeam/dnsproxy v0.15.0
go: github.com/AdguardTeam/dnsproxy@v0.15.0: unknown revision v0.15.0
go: error loading module requirements
Makefile:24: recipe for target 'AdGuardHome' failed
make: *** [AdGuardHome] Error 1

**Comment by ameshkov** [comment]
Uhhhh, that's our mistake -- `dnsproxy` tags were removed

**Comment by ameshkov** [comment]
@shenzt68 it should be okay now

**Comment by ameshkov** [comment]
@zxlhhyccc try building AdGuardHome with this command and see if it works:
```
CHANNEL=release GOOS=linux GOARCH=arm GOARM=5 make
```

**Comment by zxlhhyccc** [comment]
> 1. CHANNEL=beta GOOS=linux GOARCH=arm GOARM=6 make
请问你是用CHANNEL=beta GOOS=linux GOARCH=arm GOARM=6 make编译还是CHANNEL=release GOOS=linux GOARCH=arm GOARM=5 make编译？

**Comment by zxlhhyccc** [comment]
> @zxlhhyccc尝试使用此命令构建AdGuardHome并查看它是否有效：
> 
> ```
> CHANNEL=release GOOS=linux GOARCH=arm GOARM=5 make
> ```

The AdGuardHome compiled by shenzt68 can run on the K3 route compiled by shenzt68, but my compiled AdGuardHome cannot run, may I ask why? I compiled CHANNEL=beta GOOS= Linux GOARCH=arm GOARM=6 make and CHANNEL=beta GOOS= Linux GOARCH=arm GOARM=5 make...

**Comment by ameshkov** [comment]
What flags did @shenzt68 use?
