### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#915]
There are a lot of new translations on Crowdin.

1. Check if we can add new languages
2. Update translations

**Comment by lancelot-moon** [comment]
I checked for all phrases as possible.
It seems only the following phrases on onesky and Crowdin are a little different.
onesky:
block access to the domains matching the specified regular expression
Crowdin:
block access to the domains matching the <0>specified regular expression</0>

So translators need to modify it to <0>specified regular expression</0> in their translations.
