### ISSUE TITLE
[Feature Request] Add setting to remove client IP addresses from logs

### ISSUE THREAD

**Issue by jamesponddotco** [AdguardTeam/AdGuardHome#916]
Hi 👋🏻,

It would be great if we could have a setting that completely excluded IP addresses from clients to the logs, which would allow us to have statics on domains and whatnot, while not keeping any kind of IP addresses from people.

While logging IPs may not be an issue when running on localhost for your family, it becomes one when running AdGuard Home as an open resolver. Right now we can either log or not log at all, but a middle ground would be helpful.

*I apologize if this has been asked before, but I searched the issues and could not find it, so here I am.*

**Comment by ArchiveBase** [comment]
+1 vote too but dont make anything exclude clients from logging like this request https://github.com/AdguardTeam/AdGuardHome/issues/767

**Comment by ArchiveBase** [comment]
+1 vote too but dont make anything like exclude log specific clients traffic similar https://github.com/AdguardTeam/AdGuardHome/issues/767 sadly @ameshkov marked it as feature request

**Comment by ameshkov** [comment]
Just one question: would you like to completely remove the IP address or would it be enough to anonymize it by zeroing subnets?

**Comment by jamesponddotco** [comment]
Whatever is easier I guess, as both would accomplish the same goal.

**Comment by ameshkov** [comment]
1. Add "Anonymize client IP" setting to the "General - Logs configuration".
2. It should be disabled by default.
3. Anonymizes client IP by zeroing (keep /24 or something else for IPv6) subnet. Add a description to that setting and warn users that they won't be able to see the Client name in the log.
