### ISSUE TITLE
Version:  v0.97.1-54-ga59b

### ISSUE THREAD

**Issue by RealAmes** [AdguardTeam/AdGuardHome#918]
What is v0.97.1-54-ga59b? I don't see any release history on it?

**Comment by ameshkov** [comment]
We don't usually publish release notes for beta versions, but you can take a look here:
https://github.com/AdguardTeam/AdGuardHome/commits/master 

Or you can take a look at the list of closed issues:
https://github.com/AdguardTeam/AdGuardHome/milestone/13?closed=1
