### ISSUE TITLE
Add support for filtering IP addresses

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#921]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

After testing with `93.184.216.34`, `||93.184.216.34`, and (just to be fully certain) `93.184.216.34$network` (as per [this help doc](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier) for other versions of AdGuard), it seems to me personally that AdGuard Home does not yet support filtering domains based on their IP addresses, something that e.g. https://raw.githubusercontent.com/EnergizedProtection/block/master/extensions/ips/formats/list.txt base their lists around. So I hereby propose adding support for that.

Since the logger already registers the IP address of all queried domains, adding support for this doesn't seem to me to be as difficult as it'd otherwise be.

![image](https://user-images.githubusercontent.com/22780683/62666977-f8f36380-b985-11e9-9d58-264c71804a76.png)

### Proposed Solution

Simultaneously add support for IP address filtering, and making `93.184.216.34$network` equivalent to `93.184.216.34` (or the other way around) to ensure compatibility with AdGuard's own lists.

### Alternatives Considered

None that I can come up at the time of writing.

### Additional Information

While only 24 IP-based filterlists are listed on FilterLists.com, https://github.com/firehol/blocklist-ipsets/ lists a whopping 365 such lists (and that's just the non-range ones), although most of them only cover very narrow uses. All in all, there's a decent amount of and support for IP-blocking lists out there.

**Comment by ameshkov** [comment]
Tbh, I think this makes little sense to add this functionality to the DNS server.

However, when we finally implement the #391 this will be possible

**Comment by DandelionSprout** [comment]
Now that this has been accomplished for some 2 months by now, I figure it's time for me to close this.
