### ISSUE TITLE
/var/log/AdGuardHome.out size explode

### ISSUE THREAD

**Issue by Who-42** [AdguardTeam/AdGuardHome#923]
running 0.97.1 on 2 vps
yesterday i needed to maintenance both because the hdd was full
1. vps /var/log/AdGuardHome.out was around 30G
2.vps /var/log/AdGuardHome.out was around 60G

since i needed to rm the files to get the machines work again - i can't give any hint about the context of the files

but shouldn't there a size limit or something to prevent killing space?

**Comment by ameshkov** [comment]
Did you have `verbose` logging enabled?

We don't use any log rotation mechanism at the moment, but you can file a feature request:) We'll need some examples, though

**Comment by CWo42** [comment]
no verbose active

**Comment by ameshkov** [comment]
Then this is not okay at all.

Could you please take a look and check what it writes there?

**Comment by Who-42** [comment]
sorry since i needed to delete the files to get the machines back on, i can't say what was logged

i have an eye on the files if they explode again
