### ISSUE TITLE
MIPSLE BIN NOT WORK

### ISSUE THREAD

**Issue by kai456789** [AdguardTeam/AdGuardHome#925]
install my router ASUS RT-N16

change AdGuardHome dns port 53 to 54 

set my computer dns 192.168.1.1

can not Internet access

VER：0.97.1

**Comment by ArchiveBase** [comment]
@kai456789
> can not Internet access

It seems that's right as per your configuration. Just you need set AGH running device configured IP address as default DNS

You can see it under setup guide,
 "AdGuard Home DNS server is listening on the following addresses: xxx.xx.xx.xx" It can be 127.0.0.1 / 192.168.8.102 for example.
