### ISSUE TITLE
Paid custom AdGuard Home + Proxy & DNS server hosting.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#930]
Originally, I ever suggested such custom AdGuard DNS service (DNS filters subscription, custom blacklist & whitelist) on AdGuard chat when AG Pro for iOS was discontinued due to Apple in the past.
I can't believe that it's realized by other developers.
Honestly, it gives faultless features in the aspect of DNS service.
https://www.nextdns.io/
(nextDNS provides AdGuard SDN filter in its default lists.)

Customers also don't need to waste time on searching good VPS service if the price is reasonable.
AdGuard Home will be automatically up to date on your servers for customers.
You can also push the client apps of AdGuard Home on google play and app store.

DNS server should be anycast.
Suggested Asian locations: Taiwan, Japan and Singapore.
Cloudflare or Google has DNS servers in Taiwan.

Especially, it seems that URL filter will be built in AdGuard Home, right?
Then, it might be a proxy server + DNS server.
AdGuard Home can have its unique features (as a proxy server), compared with nextDNS.
URL filter in a router only can filter HTTP requests.
I don't know if yours can do remote HTTPS filtering...

If you can give a paid plan of AdGuard Home with proxy server + DNS server hosting, it's useful.
At least, it's easy to set AdGuard certificate as a trusted certificate without Jailbreaking on iOS.
Any browsers (ex: Chrome) on iOS can be filtered by HTTPS filtering.
Don't need to depend on Safari content blockers which are only for Safari.

3 paid plans:
`Basic`: AdGuard Home + DNS server hosting.
`Advanced`: AdGuard Home + Proxy & DNS server hosting.
`Ultimate`: AdGuard Home + Proxy & DNS server hosting + allow customers establishing blog, photo gallery or website on the host.
ex: https://www.photo.gallery/
(daydream)

Just an idea.
Please don't mind.

**Comment by ameshkov** [comment]
Yeah, this idea crossed my mind, but we don't have any definite plans yet.

**Comment by lancelot-moon** [comment]
https://www.nextdns.io/
I think nextDNS doesn't give customers hosting.

How can it provide custom DNS service?
If AdGuard DNS can be the same, it's very good.
Now AG DNS is free.
I think you can push paid custom AG DNS.
The incomes can be for maintaining DNS servers and adding new servers in more regions.
