### ISSUE TITLE
logs of v0.97.1-71-g1f0c

### ISSUE THREAD

**Issue by hesss5** [AdguardTeam/AdGuardHome#934]
hello
here some logs of new beta v0.97.1-71-g1f0c
https://gist.github.com/hesss5/22291e924f1b991bfb03668d411977e0
about adaway.org when i open https://adaway.org/hosts.txt   in  browser
its load with and without vpn not sure why its not get updated.

thanks for update

**Comment by hesss5** [comment]
with new beta error gone so far
just adaway problem persist. i can ignore it.
i close it if this happen again i will reopen.but if you think its bug for adaway  reopen it
thanks

**Comment by hesss5** [comment]
its back
https://gist.github.com/hesss5/0a0a87e44e00ba71d75a75e048e0dcb3
and when accessing interface
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/beta/version.json: *url.Error Get https://static.adguard.com/adguardhome/beta/version.json: read udp 127.0.0.1:64036->127.0.0.1:53: i/o timeout | 502

**Comment by hesss5** [comment]
so far in last  beta version everything ok :)

**Comment by szolin** [comment]
Error messages that end with `127.0.0.1:53: i/o timeout` are most likely due to reload of our DNS server.  A solution to this may be to retry downloading of version.json.

`error while responding to a DNS request: write udp [::]:53->127.0.0.1:59086: use of closed network connection`
These error messages (also because of DNS server reload) may be simply suppressed or printed with debug log level.

**Comment by hesss5** [comment]
thank you then i close issue
working so far no new log

**Comment by hesss5** [comment]
@szolin yes do what is correct its very annoying.seems i do by mistake closed issue
 
sorry

**Comment by krevoit** [comment]
I still do not understand how to fix this issue. Even after reinstall on multiple servers and using latest version I cannot update any of the filters which I believe is related to this issue

**Comment by ameshkov** [comment]
@krevoit could you please file a new bug report and attach your logs there?
