### ISSUE TITLE
Make leases database path configurable

### ISSUE THREAD

**Issue by frenck** [AdguardTeam/AdGuardHome#935]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Currently, the leases database file for the DHCP server is hardcoded. This causes issues on the Adguard Home add-on for Home Assistant on Hass.io, since it cannot be pointed/directed to persistent storage.

### Proposed Solution

Make the leases database file location configurable.

### Alternatives Considered

🤷‍♂ 

### Additional Information

None.

**Comment by ameshkov** [comment]
@szolin it seems to be really easy to fix so let's do it in v0.98.

The only thing we need to do is to start using `configuration.ourWorkingDir` for the db file location.

**Comment by ameshkov** [comment]
@frenck would it be enough? You'll be able to use `--work-dir` command-line argument in this case.

**Comment by frenck** [comment]
Thanks, guys! 👍
