### ISSUE TITLE
sb.adtidy.org unreachable, AdGuardHome stopped working.

### ISSUE THREAD

**Issue by aredan** [AdguardTeam/AdGuardHome#936]
I just notice that my Internet wasn't working and looking around found out that DNS request was the culprit. Hit Disable Protection and everything came back, saw a lot of requests to **sb.adtidy.org**, disabled a few options on Settings -> General Settings except "Block domains using filters and host files", filtering functions came back.

What is the dependency of this domain in AGH?
Also, adguard.com is down.

**Comment by Audioboxer** [comment]
It's the browsing security webservice.

**Comment by ameshkov** [comment]
Sorry for the late reply.

Webzilla data center in Amsterdam was under a heavy DDOS, and AdGuard servers are there. So the browsing security web service was unavailable, and that's what was causing the issue.

It'd be much more reliable and faster when we replace this web service with AG DNS as [explained here](https://github.com/AdguardTeam/AdGuardHome/issues/525#issuecomment-520482071).
