### ISSUE TITLE
AdGuard For Windows and AdGuard Home

### ISSUE THREAD

**Issue by rashidjehangir** [AdguardTeam/AdGuardHome#942]
Hi Guys, I have 5 licenses for AdGuard For Windows and I am using them on all my PC's/Macs at Home. I am also running Adguard Home. Do the 2 work together? Do I keep using AdGuard For Windows or just use Adguard Home? I'm confused - I would hope they would work together. Which blocks first?

**Comment by ameshkov** [comment]
@rashidjehangir hi!

AdGuard Home makes sense on a home device like Raspberry Pi and lets you control various devices in your network. It doesn't replace the traditional ad blocker like AG4W.
