### ISSUE TITLE
Allow configuring DNS cache size

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#947]
Currently, we're using the small default cache sizes. We should make them configurable instead.

* `cache_size` -- DNS cache size
* `safebrowing_cache_size` -- safebrowsing service cache size
* `parental_cache_size` -- parental control service cache size

Default values should be relatively small, I think 5000 for each should be enough.

**Comment by szolin** [comment]
> we're using the small default cache sizes
Current DNS cache size is 1000 elements.
However, current safebrowing/parental/safesearch cache size is 64k elements.

**Comment by ameshkov** [comment]
> However, current safebrowing/parental/safesearch cache size is 64k elements.

Yeah, and it makes little sense to have them that big by default:)

**Comment by skydrome** [comment]
can we get a setting to modify ttl values also?

**Comment by thueske** [comment]
+1

**Comment by ameshkov** [comment]
@skydrome yep, there will be a value for safebrowsing/parental caches TTL.
