### ISSUE TITLE
AGH release v0.98.0 binaries

### ISSUE THREAD

**Issue by tjorim** [AdguardTeam/AdGuardHome#949]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

AGH version 0.98.0 has been tagged and Docker-images are built and published. However, there are no binaries released.

### Expected Behavior

There are binaries with the release.

### Actual Behavior

The binaries are missing.

### Screenshots

<details><summary>Screenshot: Releases page</summary>

![image](https://user-images.githubusercontent.com/1294876/63500303-f0447680-c4c9-11e9-91fb-39f5131212b4.png)

</details>

<details><summary>Screenshot: Published Docker tags</summary>

![image](https://user-images.githubusercontent.com/1294876/63500392-0fdb9f00-c4ca-11e9-8818-ecea8d56aa66.png)

</details>

### Additional Information

NA

**Comment by ameshkov** [comment]
Hi! Worry not, we'll publish release notes really soon.
