### ISSUE TITLE
Add possibility to setup schedule for blocked services on per-client basis

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdGuardHome#951]
It would be cool to add a schedule for blocked services/sites in order to turn on/off automatically.

**Comment by ArchiveBase** [comment]
+1 vote

---------

#### According to Day/Time based for all services

**_Time Range_**
_Daily: 3pm to 8pm_ 

**_Custom Range_**
_Mon-Fri: 12pm to 6pm_
_Sat: 8am to 4pm_
_Sun: none_

---------

#### According to per service based (Complex)

**_Youtube_**
_Daily: 3pm to 8pm_ 

**_Steam_**
_Mon-Sat: 12pm to 2pm_
_Sun: none_

**Comment by ArchiveBase** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/46082456/63674343-86510780-c810-11e9-9f24-55b13b45f42e.png)

**Comment by ApeviaX** [comment]
I like @ArchiveBase explanation. It'll be great two time frames morning(6am-9am) and afternoon(6pm-10pm). there's always way to avoid locks, it doesn't matter. we can afford to use this product

**Comment by ameshkov** [comment]
One more relevant feature request:
https://github.com/AdguardTeam/AdGuardHome/issues/1838

**Comment by ameshkov** [comment]
And one more:
https://github.com/AdguardTeam/AdGuardHome/issues/1594

**Comment by valaria247** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by valaria247** [comment]
More blocked services feature > https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by mHatsune** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1692

**Comment by ay89607** [comment]
Hi! I'd like to contribute to development of this feature. Is there design approach/hint which configuration files/format/etc is preferable? I.e. how should I take it form here?

**Comment by ameshkov** [comment]
@ay89607 thank you! Let's get back to it in approximately 2 months, we're planning to conduct a massive refactoring, implementing this feature right now may be problematic.

**Comment by Mosney** [comment]
Schedule blocked have any progress until now?

**Comment by ameshkov** [comment]
Not yet

**Comment by thanhcv** [comment]
I'm looking for this feature, please progress it.

**Comment by gaetan-p** [comment]
This would be a awesome feature to have, I am looking forward to it !

**Comment by allhailCdosdude** [comment]
Can I also please add my voice to this feature request. And perhaps add another. Is it possible to see 'live' per client activity on the network; what services are being used, what URLs visited, etc.

**Comment by danmed** [comment]
Would like to throw my vote in for this one.. It's the only way i can think of to stop my daughter using the "1 more minute" once her phone locks!

**Comment by allhailCdosdude** [comment]
On Thu, 24 Mar 2022 14:12:55 -0700
danmed ***@***.***> wrote:

> Would like to throw my vote in for this one.. It's the only way i can think of to stop my daughter using the "1 more minute" once her phone locks!

I join you in throwing my vote in for this as well, and perhaps for the very same reason!


--
whoami ***@***.***>

**Comment by ainar-g** [comment]
@danmed, @allhailCdosdude, please do not “+1” type messages, as reacting to the original message with a “:+1:” is enough.  The feature is already scheduled for the next major release, but precise timing is still unclear.

**Comment by BrianGilbert** [comment]
> So as understand this feature is planned for version 1.0.8? 2023?

no due date https://github.com/AdguardTeam/AdGuardHome/milestone/24

**Comment by moshecom** [comment]
@ainar-g  I'd like to contribute and help write this functionality. 
Let me know what's the best way to help.

Thanks,
Moshe

**Comment by sikosis** [comment]
Very much looking forward to this ... even just a way to do the service blocking via command line would be good, then I can just use a cron job. Been searching and can't find any info about doing this. I use to be able to do this with Pi-hole.

**Comment by dongu54321** [comment]
I think we can use the API and cronjob to achieve that.
We have /parental/enable and /parental/disenable. Also 
/filtering/add_url and /filtering/remove_url.
i'm trying this now!
more about the [api](https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi)

**Comment by ainar-g** [comment]
This will be released in the upcoming v0.107.37.

**Comment by grf692** [comment]
Hi, I apologize if I did not get it, but the title says "on per-client basis" - which is the feature I was looking for - and I don't think it is what is provided in 0.107.37. This release "only" enables to schedule the on/off the service-blocking filter globally. Am I wrong ?

**Comment by ainar-g** [comment]
@grf692, I'm afraid that you are, heh.  The schedule for a client is the next tab after blocked services, and it's called *Pause service blocking.*  The UI needs improvement, but that will probably come in v0.108 cycle.

**Comment by grf692** [comment]
Sorry for being stupid, I did see the "Pause service blocking" but I can't find where I select the individual client/device. All I see is that I can add a schedule per week day to pause the service blocking filter globally (= for all clients).
Can you share a screenshot where I can select the individual client/device please ?

**Comment by ainar-g** [comment]
@grf692, *Settings → Client settings → New client/Edit*.  *Pause service blocking* tab is to the right of the *Block specific services* tab.

![Screen Shot 2023-09-08 at 11 41 26](https://github.com/AdguardTeam/AdGuardHome/assets/4964986/a6a20c6b-e341-4459-8a15-1e7da3597955)

**Comment by BrianGilbert** [comment]
Thanks for adding this feature.

A not that it appears you can only add the same schedule for every day of the week.

When I created a schedule for the weekend, it is replaced altogether in the UI when I subsequently add a different schedule for weekdays.

**Comment by ainar-g** [comment]
@BrianGilbert, that's #6177.

**Comment by venethia** [comment]
Thanks for adding this feature. 

If I want to suspend a service two times the same day from 8:00 to 14:00 and from 20:00 to 23:59 how can I do?

**Comment by ainar-g** [comment]
@venethia, there is only one interval currently.  You can create a feature request for multiple intervals within the same weekday.

**Comment by venethia** [comment]
Just did it: https://github.com/AdguardTeam/AdGuardHome/issues/6326
