### ISSUE TITLE
PHHICOMM k3 is the architecture of arm_cortex-a9. Can you compile a binary of this architecture? !

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#954]
PHHICOMM k3 is the architecture of arm_cortex-a9. The boss estimates that your current instruction set is wrong, so all binaries cannot be run in this way. Could the boss compile a binary? ! #

**Comment by Zxilly** [comment]
k3阉割了。。。go的交叉编译链里似乎没有k3

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/913#issuecomment-529240208
