### ISSUE TITLE
A compiler error！

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#955]
![9R`%_L$43VJOA@0 JMAZR$C](https://user-images.githubusercontent.com/45259624/63602864-fc7c2100-c5fa-11e9-8255-dea58d238336.png)
使用命令：CHANNEL=beta GOOS=linux GOARCH=arm GOARM=6 make

**Comment by IldarKamalov** [comment]
Please update [node.js](https://nodejs.org) to the latest LTS (10.16.3)

**Comment by zxlhhyccc** [comment]
update node.js to the latest LTS (10.16.3)
![M9% V P2KYL$HD_E9UH0B5Q](https://user-images.githubusercontent.com/45259624/63636905-7d452680-c6a8-11e9-9791-bb994206e7c0.png)
