### ISSUE TITLE
Leases not read on startup using a custom work dir

### ISSUE THREAD

**Issue by frenck** [AdguardTeam/AdGuardHome#956]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

In 0.98.0 (by #935), DHCP leases are stored in the user set work directory.
This seems to work well. A `leases.db` appears in the work directory nicely.
However, on restart of AdGuard, the leases from the UI are gone, but still listed in the `leases.db` file that resides in my work dir.

My conclusions at this moment is: The leases file is written to the right location, but on AdGuard start not read.

* **Version of AdGuard Home server:**
  * v0.98.1
* **How did you setup DNS configuration:**
  *  IoT
* **If it's a router or IoT, please write device model:**
  *  Hass.io
* **Operating system and version:**
  *  Alpine 0.10.2

### Expected Behavior

To show all leases after a restart of AdGuard Home.

### Actual Behavior

DHCP settings are there (loaded from config yaml), all data from the `leases.db` file is missing in the UI.

### Screenshots

```
$ cat /data/adguard/leases.db
[{"mac":"ABGqABGq","ip":"CgoKzQ==","host":"Test","exp":1}]
```
<details>

![image](https://user-images.githubusercontent.com/195327/63635702-c627bb80-c665-11e9-9dd5-5f0bf0c5b1d6.png)

</details>

### Additional Information

n/a

**Comment by szolin** [comment]
Please search in application logs for messages that start with `DHCP:`.
The most interesting are `DHCP: loaded %d leases from DB` and `DHCP: stored %d leases in DB`.
