### ISSUE TITLE
 update node.js to the latest LTS (10.16.3)，Compilation problems！

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#957]
![M9% V P2KYL$HD_E9UH0B5Q](https://user-images.githubusercontent.com/45259624/63636911-a5348a00-c6a8-11e9-8fcd-f4fb38db5011.png)

**Comment by zxlhhyccc** [comment]
![1G00K4}5Y3ZG5(NR9RNTDK2](https://user-images.githubusercontent.com/45259624/63636921-c5644900-c6a8-11e9-813a-5cd20bb04026.png)

**Comment by ameshkov** [comment]
You need to have GOPATH configured
https://github.com/golang/go/wiki/SettingGOPATH
