### ISSUE TITLE
Ability to forward logs to syslog/Splunk/logstash

### ISSUE THREAD

**Issue by MadDud** [AdguardTeam/AdGuardHome#958]
### Prerequisites

- [ yes ] I am running the latest version
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed

### Problem Description

I would like to better analyze DNS queries in my network. I would like to forward DNS requests, responses and information about, blocked websites and by which list to an external event collector such as syslog, Splunk, logstash etc.

### Proposed Solution
A web interface, where I can configure a remote IP, port and protocol (tcp/udp) to send events to. 
Optionally an ability to select a type of events, that would be sent such as "all" or "only blocked".

### Alternatives Considered

A wiki article on how to configure it manually.

**Comment by ameshkov** [comment]
@szolin please take this into account while refactoring the query log

**Comment by hoshsadiq** [comment]
Imo this shouldn't be built into adguard home in the sense that it needs to be able to push to a log server. This adds unnecessary overheads and complexity to the application. Instead it'll be better to simple have an option to out in json and use something fluentd, or similar tool to push to the server.

**Comment by MadDud** [comment]
@hoshsadiq It is fine to just save logs to a file. Then we at least would be able to modify docker container, so that it gets these logs in `docker logs` and we can then send logs whenever we need.

**Comment by ArchiveBase** [comment]
> Imo this shouldn't be built into adguard home 

_Special vote @hoshsadiq 😉_

**Comment by szolin** [comment]
I don't think we should support syslog or anything other than our own file.

In v0.99.3 we're slightly changing the format of query log.  It allows to use standard tools like `sort` and `grep` to process our `querylog.json` file.
We need to add a configuration setting for controlling how many log messages are kept in memory before they are flushed to disk (currently it's hard-coded to 5000) - #876.  Once it's implemented, you'll be able to synchronize our log file with other logging systems.

**Comment by kmahyyg** [comment]
Same problem here, I just checked the code, `dns.Msg{}` has been marshalled into "Answer" field as a base64-ed text, this really make fields extraction and data decode difficult. Shall we consider change the binary format to something like: `{"SimplifiedAnswer": ["1.2.3.4","5.6.7.8"]}`, so that would be a relief of SIEM administrators.
