### ISSUE TITLE
Can't resolve address on QNAP NAS

### ISSUE THREAD

**Issue by OkazakiP** [AdguardTeam/AdGuardHome#959]
I'm using AdGuardHome on NAS of QNAP(TS231P).
Most ads. are blocked when I access Internet via NAS with openVPN,
but it can't resolve names when I set my NAS as DNS server on iOS and macOS.

With SSH connection to my NAS,
it failed and connection timed out in bellow.(nas means ip of my NAS)
dig www.google.co.jp @nas
dig www.google.co.jp @nas -p 16553
dig www.google.co.jp @127.0.0.1
dig www.google.co.jp @127.0.0.1 -p 16553

On the other hand, it was succeeded.
dig www.google.co.jp @127.0.1.1

Please tell me how I can use AdGuardHome without openVPN.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.
