### ISSUE TITLE
Use DOH or DOT as bootstrap

### ISSUE THREAD

**Issue by Omoeba** [AdguardTeam/AdGuardHome#960]
Make it possible to use something that doesn't need to be resolved like tls://1.1.1.1 as bootstrap resolver.

**Comment by ameshkov** [comment]
This is a difficult task actually, so labeling it as a low-priority.

As an alternative, you can use DNS stamps with the server IP specified there.

**Comment by NetE1** [comment]
@Omoeba 

> that doesn't need to be resolved like tls://1.1.1.1 as bootstrap? 🤔

**Comment by Omoeba** [comment]
@NetE1 some DOH/DOT servers have multiple/changing IP addresses, especially IPv6 ones.

**Comment by szolin** [comment]
You can set `tls://1.1.1.1` as a bootstrap address.

**Comment by temporallyaccount** [comment]
> You can set `tls://1.1.1.1` as a bootstrap address.

No idea to offer that for AG DNS than telling about others?
