### ISSUE TITLE
FR - Client groups

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardHome#962]
### Problem Description
I wish to block my son's multiple devices (phone, laptop, tablet, Xbox) in a consistent fashion.

Currently, if I want to perform any form of client blocking or blocking of services for all of the devices that a person uses, I have to add the client and create the blocking profile for each device.

This is extra work and could result in inconsistencies between different clients and thus not achieve the desired result.

### Proposed Solution
Would it be possible to have "Client Groups", whereby you can assign multiple IP/MAC client to the group, and then the filtering/blocking configuration applies at the group level.

This ensure a consistent filtering strategy across all the devices used by a person (or people) and also makes it easy to add/remove devices from the Client group.

**Comment by ArchiveBase** [comment]
+1 vote. @AnthonyBe brought the idea with suitable name "Client Groups" I was thinking to suggest 'AGH Profiles' to fulfill this requirement however exist component called  'Clients' made me keep silence for months then below rest of details ;)

Filters and hosts blocklists for each 'Client' https://github.com/AdguardTeam/AdGuardHome/issues/435 and 'Client Group'. 
(additionally may able to use 'target tags' for those filters and each tag able use for multiple filters then it helps avoid unwanted task) 

Different DNS for each 'Client' https://github.com/AdguardTeam/AdGuardHome/issues/82 and 'Client Group'

Setup schedule for blocked services per 'Client' https://github.com/AdguardTeam/AdGuardHome/issues/951 and 'Client Group' - 

Block p2p/proxy/VPN/anonymizers for each 'Client' https://github.com/AdguardTeam/AdGuardHome/issues/101 and 'Client Group' 

Query log enhancement for view 'Client Group' statistics https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-524655134

**Comment by ameshkov** [comment]
I like the idea of having multiple devices under a single entity, but I don't really like the idea of adding a new entity for that.

It'd be easier to implement if we allow a single AGHome "Client" instance to have multiple different identifiers, it can be IP addresses, CIDR ranges, or Mac addresses.

**Comment by ArchiveBase** [comment]
@ameshkov sure that's ok.  we only expect the feature so suggested the idea but even add as CIDR ranges however prefer see main statistics about each device within 'Client' component area without effort. anyway exist UI too insufficient (and it isn't something must go to dashboard)

I also want to mention, while ongoing development related this idea enough for home users etc but if AGH use for office environment for example then that should be more advanced when compare with other enterprise solutions as my opinion.

Also certain single entity logged data must be able to view easily by 'entity name' and those result necessary to apply for query log and dashboard as well excluding rest of logs https://github.com/AdguardTeam/AdGuardHome/issues/481#issuecomment-524655134

**Comment by ArchiveBase** [comment]
> AGHome "Client" instance to have multiple different identifiers, it can be IP addresses, CIDR ranges, or Mac addresses.

Listed on https://github.com/AdguardTeam/AdGuardHome/issues/809

**Comment by ameshkov** [comment]
@ArchiveBase thank you!

Closing this as duplicate then. #809 is assigned to v0.100
