### ISSUE TITLE
Specify Port Numbers for DNS Rewrites?

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdGuardHome#963]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I am currently running a few things on a single Raspberry Pi, including AdGuard Home. These are all on the same IP address but different ports. At the moment I am using my `hosts` file to map some domains like `adguard-home.lan` to my Pi's IP address, but still have to put the correct port in the URL and I have to make sure I update the `hosts` file on every device I want to access them from. 

I am hoping to use AGH's new DNS Rewrites feature to accomplish the same thing, so they get correctly mapped on all devices without me having to edit every `hosts` file. I thought it would be great if I could also specify a port for each DNS Rewrite entry. At the moment this does not work as in the screenshot: 

![DNS Rewrites don't accept port numbers](http://puu.sh/E9gfg/74881b34a1.png)

### Proposed Solution

Allow specifying ports in DNS Rewrites either using standard URL notation (`address:port`) or with a separate text box. 

### Alternatives Considered

Although it would only work for AdGuard Home and not other services running on the network,  being able to add a "domain name" in the AGH settings would be helpful. Whenever an internal device requests that domain they get the Dashboard, even if the port is not specified.

**Comment by ameshkov** [comment]
That's not possible on the DNS level :(
