### ISSUE TITLE
Couldn't get version check

### ISSUE THREAD

**Issue by YBS-PC** [AdguardTeam/AdGuardHome#968]
What does it mean:
Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *url.Error Get https://static.adguard.com/adguardhome/release/version.json: read udp "AGH local IP:39083->AGH local IP:53: i/o timeout | 502

I sometimes get it when open filters

| Version of AdGuard Home 0.97.1
| How did you setup DNS configuration: Raspberry Pi 3 Model B+
| Operating system and version:| Raspbian Buster

**Comment by szolin** [comment]
duplicate: #934

> Error messages that end with 127.0.0.1:53: i/o timeout are most likely due to reload of our DNS server. A solution to this may be to retry downloading of version.json.
