### ISSUE TITLE
(Mac) Remove the adguard for safari logo in the dock

### ISSUE THREAD

**Issue by chribbex** [AdguardTeam/AdGuardHome#969]
The adguard icon launches in my dock every time I boot my Mac. The app Is only "active" for a couple of seconds, and then stays "inactive" in the dock. It would be neat if there were a toggle to hide the icon as there is one for the icon in the menu bar.

**Comment by ameshkov** [comment]
@Mizzick is this a MAS build problem or do we have this issue on the standalone build as well?

**Comment by ameshkov** [comment]
@Mizzick a normal behavior for an Electron app you mean?:)

**Comment by Mizzick** [comment]
Well as I know recently used app icons stays in dock for some time and there is no way to launch without an icon in the dock for electron apps.

**Comment by leolelego** [comment]
@ameshkov 
wontfix ? most Mac app that don't need user interaction mostly just have a menubar icon (on top) and no Dock icon. 
Also, I'm not a Electron dev at all and I found how to do it in the official documentation here : 
https://electronjs.org/docs/api/dock#dockhide-macos

**Comment by ameshkov** [comment]
@Mizzick ping.

Btw, what this issue does in the AGH repo?:)
