### ISSUE TITLE
v0.98.1 Increased Latency? Average Processing Time Broken?

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdGuardHome#972]
Since upgrading to v0.98.1 I have noticed the "Average processing time" metric on my AGH Dashboard is usually sitting between 1200 to 1500ms where as previously on v0.97.1 it was usually between 100 to 300ms. I have restarted the AGH process and service, and the Raspberry Pi 3B (Raspbian 9.8) it is running on. 

The only things I have changed since the upgrade are: 

- adding 10 custom filter entries, bringing my total up to 17 
- adding two DNS Rewrite entries pointing to the same IP, which is the device AGH is running on 

I have tried undoing those two changes and sometimes the APT drops as low as 700ms but I've not seen it go any lower. I haven't added, removed, disabled, or enabled any lists, though obviously they do update in the background and could potentially be the cause. I'm not sure how to investigate / confirm that. 

Can I downgrade to v0.97.1 by overwriting the AGH executable, like a manual update, or will I need to delete everything and do a "fresh install" and reconfigure all my settings?

**Comment by Ultrabenosaurus** [comment]
Apparently my average processing time is now over 13.7 seconds? As in nearly 14 whole seconds? 

![image](https://user-images.githubusercontent.com/1901532/64067453-8e4de480-cc20-11e9-814b-46f3ebb93570.png)

**Comment by Ultrabenosaurus** [comment]
...help please? It's up to 404,000ms now. 404 seconds average processing time over 24 hours can't be right, can it? Is the stat / data broken or something? 

![image](https://user-images.githubusercontent.com/1901532/64077285-c1e34a00-ccc6-11e9-86c7-887be07b3472.png)

**Comment by ArchiveBase** [comment]
Hi @Ultrabenosaurus 

> can't be right, can it? Is the stat / data broken or something?

I didn't noticed such issue with v0.98.1 and 18.36ms average processing time with AdGuard DNS. maybe you can perform DNS benchmark and use a proper one.

---

> Can I downgrade to v0.97.1 by overwriting the AGH executable, like a manual update, or will I need to delete everything and do a "fresh install" and reconfigure all my settings?

If you really want to try old version, below very basic way suitable for everyone.

1. Open command prompt and run 'sc stop AdGuardHome' then 'sc delete AdGuardHome' and backup your whole AdGuardHome folder (copy and paste it to another location). 
2. Delete AdGuardHome.exe on original folder and place the v0.97.1 executable.
3. Delete yaml file if prefer but you'll need to configure settings
4. It's not necessary to delete data folder 
5. Open command prompt with admin privileges and navigate original folder location then run 'AdGuardHome.exe -s install'. Done.

Once your test finished then repeat step 1 (no backup) and delete whole AdGuardHome original folder. now you can place back previous backup folder and run 'AdGuardHome.exe -s install'. you'll see everything as had before also no reconfiguration required.

**Comment by Ultrabenosaurus** [comment]
I have been using these upstreams since I first started using AGH though I don't remember what version that was. 

```
https://cloudflare-dns.com/dns-query
tls://1dot1dot1dot1.cloudflare-dns.com
tls://1.1.1.1
tls://1.0.0.1
```

I've just changed them to the following: 

```
176.103.130.130
176.103.130.131
8.8.8.8
8.8.4.4
```

It doesn't really make sense to think that my upstreams are the problem, though, as I they're the same as I was using with v0.97.1 without issues. The speedtest.net Windows app takes over 3 - 4 seconds from hitting the GO button to actually starting the test now, whereas it used to be almost instant, and then shows 1500 - 2000ms ping. However, the download and upload speeds are unaffected and averaging the same as before. 

I'll see what my stats are like in the morning (it's just after 23:00 here) and as soon as I finish work tomorrow. If it's still not back to something reasonable by tomorrow evening I'll try rolling back to v0.97.1. If it's still stupidly high 24 hours after that, I'll have to consider moving to Pi-hole until AGH hits v0.99 or even wait for v1.0. 

Even if it doesn't actually feel like 13+ seconds latency when I'm browsing, it is definitely slower since upgrading to v0.98.1 and there is a noticeable delay on every web request.

**Comment by aptonline** [comment]
Although I don’t have as much data to backup the issue as @Ultrabenosaurus I too seem to be seeing noticeable speed hits when browsing on 0.98.1 with a recent average processing time of 1311.61 but it has been higher.

**Comment by evilvibes** [comment]
Try disabling "Use AdGuard browsing security web service" under general settings

**Comment by ArchiveBase** [comment]
@Ultrabenosaurus 

> I'll see what my stats are like in the morning (it's just after 23:00 here) and as soon as I finish work tomorrow. If it's still not back to something reasonable by tomorrow evening I'll try rolling back to v0.97.1.

Check and let us know however i didn't experience such issue with windows and linux-amd releases. maybe any issue with raspberry pi (arm) guys @aptonline if you're too. i'm lazy have a look at source code changes. @ameshkov or someone else on AG will continue then ;)

> after that, I'll have to consider moving to Pi-hole until AGH hits v0.99 or even wait for v1.0.

You don't have to do it. Just use v0.97.1 and see 0.98 milestone, no much enhancements within it https://github.com/AdguardTeam/AdGuardHome/milestone/13?closed=1

**Comment by Ultrabenosaurus** [comment]
@ArchiveBase it was at 388,500ms when I went to bed, now it's just over 800ms. Maybe it somehow was due to using DoH / DoT upstreams even though they worked fine on v0.97.1? True test will be this evening after I get back from work and use my PC for a few hours.

@evilvibes I will try that this evening if my APT is still over 300ms this evening.  

> Try disabling "Use AdGuard browsing security web service" under general settings

**Comment by ArchiveBase** [comment]
@Ultrabenosaurus 
> it was at 388,500ms when I went to bed, now it's just over 800ms.

In this cause according to your result i think issue with cloudflare for your region and AdGuardDNS might also not perfect. its reason suggested perform DNS benchmark.

@evilvibes said
> Try disabling "Use AdGuard browsing security web service" under general settings

You can read ongoing discussion https://github.com/AdguardTeam/AdGuardHome/issues/525 

> Source @AnthonyBe
So I turned off 'browsing security' yesterday and now my Average Processing time is 47ms
That is a pretty significant impact!

**Comment by Ultrabenosaurus** [comment]
@ArchiveBase that is possible, but Cloudflare's status page shows no issues currently nor in the past few days for my region.

https://www.cloudflarestatus.com/

**Comment by ArchiveBase** [comment]
@Ultrabenosaurus
> but Cloudflare's status page shows no issues currently nor in the past few days for my region.
 
Status page usually suitable for know certain service notable outage however they may have changed network and servers as their own preference, any system modification or internal issue so it affect to users as well then run benchmark, it's one way to identify it. there're many tools 
https://www.grc.com/dns/benchmark.htm (windows) 
https://github.com/catap/namebench (linux)
 
However it might also possible show acceptable performance although AGHome is very small application then you can run another instance temporally on your computer for testing purpose if necessary. basically here we try to identify whether any strange bug on v0.98.1

Anyway now how about your average processing time after changed DNS and disabled browsing security web service?

**Comment by Ultrabenosaurus** [comment]
@ArchiveBase I'm still at work for another 2.5 hours, I'll let you know as soon as I get home. I'm also going to install that Python API thing linked in the README so I can check stats remotely over SSH in the future. 

I'll do some DNS benchmarks as soon as I get home as well, thanks for the links.

**Comment by pttien1106** [comment]
Remove all upstream DNS and set it to
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query

**Comment by Ultrabenosaurus** [comment]
Just got home after being out of the house for 10.5 hours and APT is 336ms. A massive improvement but still quite high considering how little "active" web activity I've been doing in the last 24 hours. All traffic overnight and while I'm out is a mix of my Android phone and some smart home products.

![](https://puu.sh/Eczvi/028f1ad5f3.jpg)

**Comment by Ultrabenosaurus** [comment]
Okay, so for the record these are my current upstreams:

````
176.103.130.130
176.103.130.131
8.8.8.8
8.8.4.4
````

I have just run the GRC DNS Benchmark as suggested by @ArchiveBase and here is a snapshot of the results comparing AGH (the first table) to Cloudflare and Google. Uncached results are all between 70 and 80ms compared to 1148ms for AGH.

````
192.168.1.101   |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
+ Cached Name   | 0.020 | 0.021 | 0.026 | 0.001 | 100.0 |
+ Uncached Name | 0.023 | 1.148 | 5.002 | 1.095 | 100.0 |
+ DotCom Lookup | 0.198 | 1.344 | 5.017 | 1.211 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
rpi.lan
Local Network Nameserver

1.  0.  0.  1   |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
- Cached Name   | 0.020 | 0.022 | 0.043 | 0.003 | 100.0 |
- Uncached Name | 0.021 | 0.072 | 0.261 | 0.074 | 100.0 |
- DotCom Lookup | 0.022 | 0.041 | 0.148 | 0.032 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
one.one.one.one
··· unknown owner ···

1.  1.  1.  1   |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
- Cached Name   | 0.020 | 0.022 | 0.026 | 0.001 | 100.0 |
- Uncached Name | 0.022 | 0.077 | 0.320 | 0.083 | 100.0 |
- DotCom Lookup | 0.021 | 0.026 | 0.033 | 0.003 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
one.one.one.one
··· unknown owner ···

8.  8.  4.  4   |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
- Cached Name   | 0.020 | 0.021 | 0.024 | 0.001 | 100.0 |
- Uncached Name | 0.023 | 0.073 | 0.320 | 0.074 | 100.0 |
- DotCom Lookup | 0.031 | 0.036 | 0.044 | 0.003 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
dns.google
RICE-AS - Rice University, US

8.  8.  8.  8   |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
- Cached Name   | 0.020 | 0.022 | 0.024 | 0.001 | 100.0 |
- Uncached Name | 0.024 | 0.076 | 0.299 | 0.078 | 100.0 |
- DotCom Lookup | 0.030 | 0.034 | 0.043 | 0.002 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
dns.google
GOOGLE - Google LLC, US
```

My next step is to disable the AdGuard browsing security service and run three more benchmarks for comparison, once the GRC software finished my "top 50 ranking" in 25 mins.

1. using same upstreams 
2. using @pttien1106 suggested upstreams 
3. using my old upstreams

**Comment by ameshkov** [comment]
Well, the web security service will make the average processing time higher, that's for sure.

Unlike AG DNS, it has just one location. Also, 5sec is the timeout value AGH uses for the web service requests so that's why you're seeing ~5sec max time. The situation will improve when we start using [AG DNS for these lookups](https://github.com/AdguardTeam/AdGuardHome/issues/525#issuecomment-520482071).

Also, "average processing time" is not an ideal metric. DNS queries do occasionally time out, DNS works over UDP and packet loss can occur. This timed out queries can make the "average" value quite high, while the median processing time is much much lower, and you don't really feel any slowdown.

**Comment by Ultrabenosaurus** [comment]
Here are those three further benchmarks I promised in my previous comment.

```
#### benchmark 1 ####

192.168.  1.101 |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
+ Cached Name   | 0.026 | 0.042 | 0.054 | 0.005 | 100.0 |
+ Uncached Name | 0.044 | 0.905 | 5.030 | 0.932 | 100.0 |
+ DotCom Lookup | 0.153 | 0.911 | 3.316 | 0.677 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
rpi.lan
Local Network Nameserver

#### benchmark 2 ####

192.168.  1.101 |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
+ Cached Name   | 0.020 | 0.033 | 0.046 | 0.009 | 100.0 |
+ Uncached Name | 0.030 | 1.182 | 5.012 | 1.142 | 100.0 |
+ DotCom Lookup | 0.035 | 0.956 | 2.676 | 0.576 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
rpi.lan
Local Network Nameserver

#### benchmark 3 ####

192.168.  1.101 |  Min  |  Avg  |  Max  |Std.Dev|Reliab%|
----------------+-------+-------+-------+-------+-------+
+ Cached Name   | 0.022 | 0.061 | 0.101 | 0.022 | 100.0 |
+ Uncached Name | 0.035 | 1.085 | 3.971 | 1.035 | 100.0 |
+ DotCom Lookup | 0.081 | 1.123 | 5.034 | 1.339 | 100.0 |
---<-------->---+-------+-------+-------+-------+-------+
rpi.lan
Local Network Nameserver
```

AGH is averaging around 1000ms with a high of 5000ms regardless of which upstreams I use compared to CloudFlare or Google which average around 75ms and peak at 320ms. This makes AGH over 100 times slower than regular DNS for me. 

The web security service doesn't have too much of an impact on my times because they're already so high.

**Comment by ameshkov** [comment]
Do you have the same upstream as the one you measure in the AGH settings?
Do you have "parallel queries" enabled in the AGH settings

**Comment by ameshkov** [comment]
Oh, and one more thing. I don't really know how this GRC benchmark works, but make sure that your IP address is in `ratelimit_whitelist`:
https://github.com/AdguardTeam/AdguardHome/wiki/Configuration#configuration-file

The default rate limit is rather low.

**Comment by Ultrabenosaurus** [comment]
@ameshkov 

> Do you have the same upstream as the one you measure in the AGH settings?
> Do you have "parallel queries" enabled in the AGH settings

I do have parallel queries enabled. 

I was originally using these upstreams when I upgraded and noticed the Average Processing Time rapidly increasing: 

```
https://cloudflare-dns.com/dns-query
tls://1dot1dot1dot1.cloudflare-dns.com
tls://1.1.1.1
tls://1.0.0.1
```

I then changed to the following which reduced the APT back down to 300ms - 400ms. The first DNS benchmarks I posted were using these upstreams with web security enabled.

```
176.103.130.130
176.103.130.131
8.8.8.8
8.8.4.4
```

The second benchmark was the above upstreams with web security disabled. I have not turned web security back on at all. 

The third benchmark was using these upstreams:

```
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
```

The 4th benchmark is back to my original upstreams. 

It may be a symptom of doing so several DNS benchmarks, or it could be that my preferred upstreams are simply slower than the others, but my APT is currently sitting at 443ms. 

The lowest it has been since upgrading to v0.98.1 is 330ms whereas it was normally at 100ms with v0.97.1.

**Comment by ameshkov** [comment]
First of all, any benchmark will try to send more than 20 requests per second so you should add your IP address to the `ratelimit_whitelist` in AGH configuration.

Second, if you want to understand what overhead AGH creates, you should use the very same upstream you're comparing to. If you are comparing AGH to Google DNS, you should also use Google DNS in the AGH settings.

> I do have parallel queries enabled.

Actually, this might be the reason for the high avg processing times. We should test how it behaves on a DNS query that times out on all upstreams, I've filed an issue about that: https://github.com/AdguardTeam/AdGuardHome/issues/977

**Comment by Ultrabenosaurus** [comment]
Thanks for pointing out that whitelist, I'll try it tomorrow evening with more benchmarks. However over just noticed that after only a couple of hours back on my preferred upstreams the APT has shot back up to nearly 7000ms. I've deleted the only DoH line to see if that's the problem, otherwise I'm going to go through all the combinations of those four to see what works best. 

![](https://puu.sh/EcGGE/0555814708.jpg)

I'm still confused about this. Nothing like it happened with v0.97.1 with all the same upstreams and settings.

**Comment by ameshkov** [comment]
@Ultrabenosaurus my bet is that "parallel queries" feature misbehaves on DNS queries that time out, which cause some abnormally high "elapsed" values for a DNS query -> it causes high "average" aggregate. Imagine that 100 queries take 10ms, and one takes 1000 seconds. This has nothing to do with the actual performance (DNS clients do not wait for responses that much), but it distorts the stats. Try disabling "parallel queries" and check if it changes anything.

**Comment by pttien1106** [comment]
Can you public your .yaml config file? Old config file 0.97.x not suitable for 0.98.1. I used to be like that. So I setup a fresh config .yaml when reinstall 0.98.1

**Comment by Ultrabenosaurus** [comment]
I've done a clean install of v0.97.1, reconfigured everything except upstreams, waited a day to see if it's stable, upgraded to v0.98.1 yesterday, then this morning added my preferred upstreams again. It has been consistently between 100ms to 250ms so far which is good enough for me. I don't do any online gaming that requires low latency, mostly just browsing and watching videos. 

I assume something must have gone weird the first time I updated from v0.97.1 to v0.98.1, but only the gods might know what or why. 

Thanks for all the help and suggestions, folks. Sorry I don't have a concrete conclusion to this.

**Comment by admitrevskiy** [comment]
@Ultrabenosaurus hi!
I'd like to find out what was going on. 
Please send logs to devteam@adguard.com if you've configured the log file and it still remains.
Otherwise, if the problem occurs again, specify the path for the log file in .yaml config file and run AdGuard Home with `-v` flag to record verbose log.
