### ISSUE TITLE
AdGuard Home doesnt honor system time

### ISSUE THREAD

**Issue by timesflying** [AdguardTeam/AdGuardHome#973]
Dear AdGuard Team,
I have recently set-up AdGuard Home on a Raspberry Pi 3B+. I have noticed that the query log timestamps are not consistent with the system time of the Raspi.
Thanks for AdGuard Home, cool stuff!

Best, Christian.

**Comment by ameshkov** [comment]
Hmm, it must be consistent, there's no other time we can use.

What exactly do you mean by "not consistent", how much does it lag?

**Comment by timesflying** [comment]
The timestamps in AdGuard Home are exactly two hours behind system time (e.g., when I use date on CLI). I would assume that it has something to do with the time zone settings on the host?

Best, Christian.

**Comment by ameshkov** [comment]
@szolin any idea?

**Comment by szolin** [comment]
Can you run `./AdGuardHome`, `Ctrl+C` and then `date` ?  What exactly do they print?

**Comment by timesflying** [comment]
I have done so and the result is that it shows the correct time.

pi@AdGuard:~/AdGuardHome $ ./AdGuardHome
2019/09/03 19:54:17 [info] AdGuard Home, version v0.98.1, channel release

2019/09/03 19:54:17 [info] Added 5 client aliases from /etc/hosts
2019/09/03 19:54:17 [info] Added 2 client aliases from 'arp -a' command output
^C2019/09/03 19:54:19 [info] Stopping AdGuard Home
2019/09/03 19:54:19 [info] Stopped

pi@AdGuard:~/AdGuardHome $ date
Tue Sep  3 19:54:22 CEST 2019

**Comment by NetE1** [comment]
@timesflying If you login to web interface through any other device (ex: windows) browser then does it consistent with that system time?
_Maybe you can run a time sync for Raspberry Pi than set manually._

**Comment by timesflying** [comment]
> On 16.09.2019, at 14:59, NetE1 <notifications@github.com> wrote:
> 
> @timesflying <https://github.com/timesflying> If you login to web interface through any other device (ex: windows) browser then does it consistent with that system time?
> 
I am checking this via the web interface of AdguardHome. I can confirm that the time zone is configured correctly, yet, still the time stamps are lagging by two hours (the difference between UTC and my current time zone CEST). I should probably note that this is really not a big deal for me, yet perhaps can eventually be solved in a subsequent release.

Thanks, Christian.

**Comment by NetE1** [comment]
I guess that's so far belong to your device then update us if could solved yourself later and meantime, lets see if other people have similar issue. :)

**Comment by ameshkov** [comment]
@timesflying could you plz download the query log and take a look at the raw json -- what timestamp values do you have there?

Please post an example:
1. Timestamp from raw json
2. What you see in the UI for this record
3. What you **should** have there

**Comment by timesflying** [comment]
Hi,
I think you are on to something because the time stamps in the downloaded log file are correct, while they show up by the 2 hours delay in the web interface of AdGuard Home.
.
One example from the log file:

{"answer":[{"ttl":1800,"type":"CNAME","value":"geoycpi-uno-deluxe.gycpi.b.yahoodns.net."},{"ttl":251,"type":"A","value”:”---.---.--.---"},{"ttl":251,"type":"A","value”:”—.—.--.---"}],"client”:”---.---.-.-","elapsedMs":"300.946577","question":{"class":"IN","host":"developer.yahoo.com","type":"A"},"reason":"NotFilteredNotFound","status":"NOERROR","time":"2019-09-19T22:11:12+02:00”}

Thats the correct time right there in the log file.

Best, Christian.

**Comment by ameshkov** [comment]
@IldarKamalov how do we transform `time` in the query log?

**Comment by IldarKamalov** [comment]
We use `format` helper `HH:mm:ss` from [date-fns](https://date-fns.org/v1.29.0/docs/format)

**Comment by ameshkov** [comment]
@IldarKamalov could it be that it's losing the time zone somehow? Because it seems that that's what's happening in the @timesflying's case

**Comment by a5hs** [comment]
I had this same issue. Turns out it was caused by Firefox, having resist fingerprinting enabled in about:config. Tried it in another browser and found the time stamps to be correct.

**Comment by timesflying** [comment]
I confirm that. When using a different browser the time stamps are correct.

**Comment by ameshkov** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1330890
