### ISSUE TITLE
Does AdGuardHome0.98.1 solve the problem of not running on PHICOMM k3?

### ISSUE THREAD

**Issue by zxlhhyccc** [AdguardTeam/AdGuardHome#974]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by ameshkov** [comment]
No, the original task is still marked as "help wanted".

If you know how to compile a golang program for this device, this would be helpful because I don't :(
