### ISSUE TITLE
Responsive Design on Query Log page (smartphone)

### ISSUE THREAD

**Issue by ConfiDev** [AdguardTeam/AdGuardHome#978]
I'm currently testing the usability of adguard home on my smartphone.

One important feature is the possibility to enable / disable domains on the smartphone itself via the web ui.

This is currently nearly impossible, since the table on the Query Log page is not responsive.
I can only see a couple of characters which are not sufficient to make a proper decision.
Since I use huge filter lists, false positives are common and I want to be able to fix it quickly.

A possible solution could be, to hide some columns on smaller screen like client, response, type. (But I'm afraid that it could not be enough)

**Comment by ameshkov** [comment]
We're going to slightly change the query log layout in v0.99, let's see how it goes after that.

I'll assign this issue to v0.100 just in case we need to make more changes after that.

**Comment by ArchiveBase** [comment]
Similar https://github.com/AdguardTeam/AdGuardHome/issues/846

**Comment by ameshkov** [comment]
Done as a part of the query log redesign: https://github.com/AdguardTeam/AdGuardHome/issues/1421
