### ISSUE TITLE
Empty dashboard

### ISSUE THREAD

**Issue by thueske** [AdguardTeam/AdGuardHome#981]
### Prerequisites

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

Hello, I noticed that the dashboard no longer displays any values (statistics) when the query log is disabled. Is this a desired state? In one of the older releases this was different in my opinion, but it can also deceive me...

Thanks :)

**Comment by ameshkov** [comment]
Well, yeah, that's because all the stats are currently calculated from the query log.

The good news is that we're about to change that in v0.99 :)
