### ISSUE TITLE
Missed translations

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#982]
Доброго времени суток, можете исправить пропуски в переводе на Русском языке.
На данный момент у меня стоит последняя версия 0.98.1
<details><summary>Screenshot:</summary>
Основные настройки -> Заблокированные сервисы

![PNG](https://user-images.githubusercontent.com/46345396/64399299-92d72a80-d070-11e9-98fe-9640e1c027e9.PNG)
</details>
<details><summary>Screenshot:</summary>
Настройки DNS -> Перенаправления DNS

![PNG](https://user-images.githubusercontent.com/46345396/64399414-0e38dc00-d071-11e9-8b7b-d83a4e094494.PNG)
</details>
<details><summary>Screenshot:</summary>
Настройки DNS -> Перенаправления DNS (после нажатия кнопки Добавить правило перенаправления DNS)

![PNG](https://user-images.githubusercontent.com/46345396/64399359-d6ca2f80-d070-11e9-8609-a483e679b94d.PNG)
</details>

**Comment by ameshkov** [comment]
Кстати можете тоже поучаствовать:
https://crowdin.com/project/adguard-applications/en#/adguard-home

**Comment by Eyeborgs** [comment]
@ameshkov я попробовал исправить некоторый текст и так же добавить возможные переводы со смыслом, строго не судите.

**Comment by ameshkov** [comment]
@Eyeborgs спасибо! @aalpatkina посмотришь?

**Comment by IldarKamalov** [comment]
Fixed in https://github.com/AdguardTeam/AdGuardHome/commit/30ca77303b18c567b61da154066440a4010f4db9
