### ISSUE TITLE
Problems with the text

### ISSUE THREAD

**Issue by Eyeborgs** [AdguardTeam/AdGuardHome#983]
Доброго времени суток, можете исправить повтор в тексте на Русском языке.
На данный момент у меня стоит последняя версия 0.98.1
<details><summary>Screenshot:</summary>
Инструкция по настройке -> Windows

![PNG](https://user-images.githubusercontent.com/46345396/64399703-1f361d00-d072-11e9-8929-0ef9ea182683.PNG)
</details>

Тут не много другая проблема в тексте: сейчас "Если он настроек" а правильно "Если он настроен"
<details><summary>Screenshot:</summary>
Настройки DNS -> Настройки доступа

![PNG](https://user-images.githubusercontent.com/46345396/64399782-70461100-d072-11e9-8146-226c524d725d.PNG)
</details>

**Comment by IldarKamalov** [comment]
Fixed in https://github.com/AdguardTeam/AdGuardHome/commit/30ca77303b18c567b61da154066440a4010f4db9
