### ISSUE TITLE
Dashboard is not opening after installation

### ISSUE THREAD

**Issue by 1985kasper** [AdguardTeam/AdGuardHome#984]
After completing the installation steps the Open Dashboard button does not lead to the dashboard. 

installed on a Vultr VPS debian 9
port 80 and 3000 are opened in the firewall. DNS server is working on a iOS client but i can't get to the dashboard itself.

**Comment by ZExplore** [comment]
Hi
I use debian but no such issue. Can't you go manually without 'Open Dashboard' button by entering <vps ip>:80 ? also make sure no any software firewall block applications or ports on your server
Maybe you've configured 'bind host' and 'bind port' incorrectly then open AdGuardHome.yml file to  check it and restart AGH service.

lf still unable solve you can specify a path for the log file in .yaml config file and run AdGuard Home with -v flag to record verbose log
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#logs
