### ISSUE TITLE
I found that I can't use reboot in openwrt.

### ISSUE THREAD

**Issue by orzgithub** [AdguardTeam/AdGuardHome#985]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.98.1
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Xiaomi mifi MINI
* **Operating system and version:**
  * OpenWrt R9.8.17

I installed it on my router with OPENWRT and found that I can't reboot my router by using reboot on the LUCI interface. I have to kill the progress of AdGuardHome.Is it caused by openwrt itself?Or by AdGuardHome?
</details>

**Comment by ArchiveBase** [comment]
"ssh the openwrt and go the terminal and type reboot. Which will reboot the system."
> credits: https://stackoverflow.com/a/46504209

**Comment by ameshkov** [comment]
AGH does not do anything like this on purpose so I guess it has smth to do with luci.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1201
https://github.com/rufengsuixing/luci-app-adguardhome/releases
