### ISSUE TITLE
Runing on Mac problem

### ISSUE THREAD

**Issue by vikingboss** [AdguardTeam/AdGuardHome#986]
If i turn off my Mac, the Adguard Home can not work?Whether or not it means my Mac need can not stop working？

**Comment by ArchiveBase** [comment]
> If i turn off my Mac, the Adguard Home can not work?

If you're running AGHome on Mac device, Yes. that's right.

> Whether or not it means my Mac need can not stop working？

If use AGHome for cover any other devices like your smartphones, other computers, router then you have to keep it turned on.
