### ISSUE TITLE
Data on the clients that use AdGuard Home, but not stored in the configuration

### ISSUE THREAD

**Issue by VwEl** [AdguardTeam/AdGuardHome#987]
The devices are on this list.
Clients is only localhost.localdomain (127.0.0.1)

**Comment by VwEl** [comment]
Top clients s only localhost.localdomain (127.0.0.1)

**Comment by RunningMelos** [comment]
😥 the same

**Comment by ameshkov** [comment]
Could you please explain better what exactly is wrong?
Try filing a new bug report using the proper template: https://github.com/AdguardTeam/AdGuardHome/issues/new?template=Bug_report.md
