### ISSUE TITLE
Content modification 

### ISSUE THREAD

**Issue by ArchiveBase** [AdguardTeam/AdGuardHome#990]
AdGuardHome footer 'Report an issue' link necessary to modify 

_https://github.com/AdguardTeam/AdGuardHome/issues/new (current)_ 

https://github.com/AdguardTeam/AdGuardHome/issues/new?template=Bug_report.md or https://github.com/AdguardTeam/AdGuardHome/issues/new/choose

**Comment by ameshkov** [comment]
@IldarKamalov use this one plz:
`https://github.com/AdguardTeam/AdGuardHome/issues/new/choose`
