### ISSUE TITLE
AdGuardHome seem's to leak memory until the machine dies

### ISSUE THREAD

**Issue by Xuxe** [AdguardTeam/AdGuardHome#991]
[AdGuard.txt](https://github.com/AdguardTeam/AdGuardHome/files/3596021/AdGuard.txt)
### Issue Details

* **Version of AdGuard Home server:**
  * Version: v0.98.1 [had the issue also with v0.97 and hotfixes]
* **How did you setup DNS configuration:**
  * LXC Container, 1x Core, 512MB Memory, 1GB SWAP
* **Operating system and version:**
  * Debian 10 - had the issue before with Ubuntu 18.04 also

### Expected Behavior
AdGuard doesn't leaks memory until  the machine gets unresponsive and ends in high cpu usage. 
May relates to #905 ?
I have the issue with two instances of AdGuard Home with the same version and setup.  

### Actual Behavior
The memory usage constantly goes up: 

Memory graph from  09.09.19 8:52 to 10.09.19 0:58: 
![grafik](https://user-images.githubusercontent.com/6413398/64618495-a7a11e80-d3e0-11e9-82ba-cd917604792d.png)

and ends with high cpu usage until the machine dies:

CPU graph of the last 4 Hours:
![grafik](https://user-images.githubusercontent.com/6413398/64618372-6dd01800-d3e0-11e9-88ce-2060087f4c90.png)

### Additional Information
My current work a round is to set a CPU Quota of 50% with systemd, which helps to kill the process  ASAP when the issue rises before it kills the complete system.  This is what you can see in the Memory graphs when the usage drops and increments again.

**Comment by szolin** [comment]
Hello!
Can you run this command and show the output?
`ps aux | grep AdGuardHome`

**Comment by Xuxe** [comment]
@szolin 

Hi :)

this is the output: 

root@dns01:~# ps aux | grep AdGuardHome
root       604  0.0 13.1 116836 68704 ?        Ssl  13:21   0:08 /opt/AdGuard/AdGuardHome -s run
root      4515  0.0  0.1   3080   824 pts/2    S+   14:00   0:00 grep AdGuardHome

Also added my config quickly to the issue, if needed.

**Comment by ameshkov** [comment]
How many different clients does it have?

@szolin it'd be helpful if we had http/pprof registered: https://golang.org/pkg/net/http/pprof/

**Comment by Xuxe** [comment]
@ameshkov 

My current setup is: 

2x PowerDNS Recursor with a PowerDNS Authorative for a local domain in front of AdGuard all clients talking to the PDNS Recursor and the recursors are talking to AdGuard for non local domains. Around 20-25 clients.  The Recursors also do there own caching, there shouldn't be much load on AdGuard its self. What i see in the UI is 7k querys since the reset around an hour ago.

**Comment by szolin** [comment]
> root 604 0.0 13.1 116836 68704 ? Ssl 13:21 0:08 /opt/AdGuard/AdGuardHome -s run

AGH uses 68mb of RAM - it's normal.
Are there any other processes that use more of your system memory?
When your CPU usage is 100% - what process uses it?

**Comment by Xuxe** [comment]
@szolin 

Sorry if it was not clear. I had to reset the system because it was inaccesable by SSH or console.  At the moment the issue doesn't exists. AdGuard is the only thing that runs in this LXC container. 

As you can see from check mk event history: 

![grafik](https://user-images.githubusercontent.com/6413398/64623654-9b6d8f00-d3e9-11e9-99a5-6df4a49199e7.png)

The very first issue Check MK reports is DNS runs in a timeout. Then ASAP the system freaks out in terms of CPU. I try to cover you the ps output as soon as the memory increases again. I'm not sure if there is a way to reproduce it at the moment.  I tested also to do a nslookup which isn't working too at that point.

**Comment by szolin** [comment]
AGH's system usage looks normal.
We need to see what it looks like when (or just before) your memory usage becomes too high.

**Comment by ameshkov** [comment]
What about AGH logs?

**Comment by Xuxe** [comment]
It looks like AdGuard is not the root cause. Somehow systemd socket activation which is used by Check_MK seems to leak memory and triggers that OOM condition on Debian 10 followed by high CPU usage from AdGuard as side effect. 

I close the issue, sorry for blaming AGH.  Thanks for AGH, keep up the work :)
