### ISSUE TITLE
Incredibly high response time

### ISSUE THREAD

**Issue by 1985kasper** [AdguardTeam/AdGuardHome#994]
Hi,

I have been testing Adguard Home in the cloud on a vultr VPS (AMS DC) for a while now.

First with just a couple of clients. But yesterday i changed the DNS server in my router to the AdGuard server. I have about a dozen clients that would be using it both on and off premises.

Today i noticed incredibly long response times to resolve DNS and the adguard dashboard is also reporting a very high average lookup time. 
![Processing time](https://user-images.githubusercontent.com/24982692/64694828-f612f380-d49a-11e9-83d6-48bff95b4035.png)

Can you please indicate if this is something that would be down to configuration for example or this would be a problem with the VPS?

As it stands Adguard deployed on a VPS would not be suitable for my situation unfortunately.

**Comment by ameshkov** [comment]
To troubleshoot this issue we need to see AdGuard Home logs.

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by 1985kasper** [comment]
Thanks. I have setup logging. Specified path /home/<username>/logs
Restarted Adguardhome but i don't see any logs yet. Does this take a while?

**Comment by 1985kasper** [comment]
I just tried another VPS at Digital ocean. Same story websites are not loading at all. I do see in the query log queries are being made. I don't have any custom settings apart from the whitelist only for certain IP's. This is to avoid getting messages from the VPS providers that ports 53 are open which they consider a security risk.

Not sure what's going on it was working fine before. But as soon as i added multiple clients the response time skyrocketed and the service is not very usable anymore.

**Comment by 1985kasper** [comment]
I figures out what causes the issue. It’s the browsing security web service option. Whenever i enable this browsing becomes very slow. 

Maybe this is only intended for a LAN setup?

**Comment by ArchiveBase** [comment]
If it then here's upcoming solution https://github.com/AdguardTeam/AdGuardHome/issues/525#issuecomment-520482071
