### ISSUE TITLE
Cross-platform installation script

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#995]
Reading through the "Get Started" documentation is tiresome, it'd be great to provide a simple one-step install script - like what pi-hole does: `curl -sSL https://install-home.adguard.com | bash`

Unlike pi-hole, most of the initial configuration is done in the web interface so the script will be MUCH simpler.

Here's what it should do:
1. Detect the operating system and CPU
2. Choose among AdGuard Home binaries: https://static.adguard.com/adguardhome/release/version.json
3. Download it
4. Prompt for the installation directory (use `/opt/adguardhome` as a default location) 
5. Unpack the archive there
6. Register AGH as a service: https://github.com/AdguardTeam/AdguardHome/wiki/Getting-Started#service
7. Run it
8. Clean up

**Comment by kang-mk** [comment]
yes  good

**Comment by yegle** [comment]
Might be a good idea to take a look at https://gobinaries.com
